### ISSUE TITLE
flutter run -v stuck at "Waiting for observatory port to be available..."

### ISSUE THREAD

**Issue by lebtron** [flutter/flutter#57783]
Some information:
* Old version of flutter worked on this phone before.
* It works on Emulator but not on real device (which like I said used to work before)
* This happens even on a new project created with "flutter create hello_world".
* I have cleaned and reinstalled everything to do with flutter and android to no avail.
* I tried all solutions proposed in other similar threads about "stuck at: waiting for observatory port".

```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.1 at C:\tools\flutter
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\neut\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\neut\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • LG H918 • LGH91894c26aef • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

First I clean logcat with `logcat -c` and run `logcat -e flutter\|Observatory *:I`
Result:
```
1|elsa:/ $ logcat -e flutter\|Observatory *:I
--------- beginning of main
--------- beginning of system
```

Then on another terminal I run `flutter run -v`
```
C:\Users\neut\Desktop\hello>flutter run -v
[  +13 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +39 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[        ] executing: [C:\tools\flutter/] git tag --contains HEAD
[ +140 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.1
[   +7 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +62 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +26 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +11 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +26 ms] List of devices attached
           LGH91894c26aef         device product:elsa_tmo_us model:LG_H918 device:elsa transport_id:1
[   +5 ms] C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe -s LGH91894c26aef shell getprop
[ +122 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +123 ms] Generating C:\Users\neut\Desktop\hello\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +17 ms] ro.hardware = elsa
[        ] ro.build.characteristics = default
[  +31 ms] Launching lib\main.dart on LG H918 in debug mode...
[   +7 ms] C:\tools\flutter\bin\cache\dart-sdk\bin\dart.exe C:\tools\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\tools\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\neut\AppData\Local\Temp\flutter_tool.36efa857-9be6-11ea-89ec-001a7dda7113\app.dill --packages
C:\Users\neut\Desktop\hello\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[   +9 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree C:\Users\neut\Desktop\hello\build\app\outputs\apk\app.apk
AndroidManifest.xml
[   +8 ms] Exit code 0 from: C:\Users\neut\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\neut\Desktop\hello\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.hello" (Raw: "com.example.hello")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hello" (Raw: "hello")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.hello.MainActivity" (Raw: "com.example.hello.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe -s LGH91894c26aef shell -x logcat -v time -t 1
[ +120 ms] Exit code 0 from: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe -s LGH91894c26aef shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           05-22 07:39:27.590 V/WifiServerServiceExt( 1748): checkPollTimer Cnt= 0 rssi =-23 threshold=-100
[   +9 ms] <- compile package:hello/main.dart
[   +5 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +27 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +16 ms] Building APK
[  +11 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from C:\Users\neut\Desktop\hello\android\gradlew.bat.
[   +1 ms] C:\Users\neut\Desktop\hello\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +5 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +63 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +3 ms] executing: [C:\Users\neut\Desktop\hello\android/] C:\Users\neut\Desktop\hello\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\neut\Desktop\hello\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1360 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:cleanMergeDebugAssets
[  +85 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[  +97 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[   +1 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[  +93 ms] > Task :app:processDebugResources UP-TO-DATE
[   +1 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[        ] > Task :app:packageDebug UP-TO-DATE
[  +88 ms] > Task :app:assembleDebug
[   +1 ms] BUILD SUCCESSFUL in 1s
[        ] 31 actionable tasks: 4 executed, 27 up-to-date
[ +607 ms] Running Gradle task 'assembleDebug'... (completed in 2.4s)
[  +27 ms] calculateSha: LocalDirectory: 'C:\Users\neut\Desktop\hello\build\app\outputs\apk'/app.apk
[  +48 ms] calculateSha: reading file took 46us
[ +422 ms] calculateSha: computing sha took 421us
[   +6 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[   +3 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree C:\Users\neut\Desktop\hello\build\app\outputs\apk\app.apk
AndroidManifest.xml
[  +13 ms] Exit code 0 from: C:\Users\neut\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
C:\Users\neut\Desktop\hello\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.hello" (Raw: "com.example.hello")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="hello" (Raw: "hello")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.hello.MainActivity" (Raw: "com.example.hello.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on LG H918.
[   +1 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe -s LGH91894c26aef shell am force-stop com.example.hello
[ +185 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe -s LGH91894c26aef shell pm list packages com.example.hello
[ +957 ms] package:com.example.hello
[   +3 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe -s LGH91894c26aef shell cat /data/local/tmp/sky.com.example.hello.sha1
[  +66 ms] 038e4bcf74bf4ebb2a8f9bd527a778342236b4ee
[   +1 ms] Latest build already installed.
[        ] LG H918 startApp
[   +1 ms] executing: C:\Users\neut\AppData\Local\Android\sdk\platform-tools\adb.exe -s LGH91894c26aef shell am start -a android.intent.action.RUN -f
0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.hello/com.example.hello.MainActivity
[ +108 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.hello/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
```

Logcat:
```
1|elsa:/ $ logcat -e flutter\|Observatory *:I
--------- beginning of main
--------- beginning of system
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer: Well this is awkward; package io.flutter.app.FlutterApplication had UID -1
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer: java.lang.Throwable
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at com.android.server.pm.PackageDexOptimizer.performDexOptLI(PackageDexOptimizer.java:148)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at com.android.server.pm.PackageDexOptimizer.performDexOpt(PackageDexOptimizer.java:123)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:19431)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:18976)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at com.android.server.pm.PackageManagerService.-wrap35(Unknown Source:0)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:16235)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at android.os.Handler.handleCallback(Handler.java:789)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at android.os.Handler.dispatchMessage(Handler.java:98)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at android.os.Looper.loop(Looper.java:164)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at android.os.HandlerThread.run(HandlerThread.java:65)
05-22 07:38:08.236  1748  1887 E PackageManager.DexOptimizer:   at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-22 07:38:11.982 26513 26544 I ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
05-22 07:38:11.984 26513 26544 I ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
05-22 07:38:12.064 26513 26544 I ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
05-22 07:38:12.532 26513 26625 I flutter : Observatory listening on http://127.0.0.1:34470/-C6AWg4XP_4=/
```

**Comment by iapicca** [comment]
Hi @lebtron 
the device involved seems to be an LG V20 runing Android 7.0

I see there's an open [issue](https://github.com/flutter/flutter/issues/57766) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by lebtron** [comment]
> 
> 
> Hi @lebtron
> the device involved seems to be an LG V20 runing Android 7.0
> 
> I see there's an open [issue](https://github.com/flutter/flutter/issues/57766) addressing the case you described.
> Please follow up on that issue,
> I'm closing the current one as duplicate.
> If you disagree please write in the comments
> and I will reopen it.
> Thank you

Yes! but my android version is 8.0! The issue is not specific to android version 7.0.
