### ISSUE TITLE
AssetImage is not woring in list

### ISSUE THREAD

**Issue by bigwaytechnology** [flutter/flutter#57788]
```bash
Performing hot reload...
Syncing files to device Android SDK built for x86...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Skill(dirty, dependencies: [MediaQuery], state: _SkillState#66489):
type 'List<Image>' is not a subtype of type 'List<AssetImage>' of 'function result'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Skill file:///E:/flutter_project/mykam/lib/main.dart:12:12
When the exception was thrown, this was the stack: 
#0      _icons (package:mykam/serviceSelect.dart)
#1      _SkillState.build (package:mykam/serviceSelect.dart:105:29)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 2 of 588 libraries in 2,126ms.

```

**Comment by iapicca** [comment]
Hi @bigwaytechnology 
from the logs you are providing is possible that 
the error is cause by your implementation rather than flutter itself;

can you please provide your `flutter doctor -v` ,
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
