### ISSUE TITLE
Flutter AnimationController dispose() 

### ISSUE THREAD

**Issue by mustafayldz** [flutter/flutter#57797]
```
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching notifications for AppStateProvider:
flutter: AnimationController.stop() called after AnimationController.dispose()
flutter: AnimationController methods should not be used after calling dispose.
flutter: 'package:flutter/src/animation/animation_controller.dart':
flutter: Failed assertion: line 732 pos 7: '_ticker != null'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      AnimationController.stop (package:flutter/src/animation/animation_controller.dart:732:7)
flutter: #3      AnimationController.fling (package:flutter/src/animation/animation_controller.dart:670:5)
flutter: #4      _SlidingUpPanelState._open (package:sliding_up_panel/src/panel.dart:381:9)
flutter: #5      PanelController.open (package:sliding_up_panel/src/panel.dart:503:5)
flutter: #6      _AppPageState.togglePanel (package:transporter/src/pages/app_page.dart:74:46)
flutter: #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
flutter: #8      AppStateProvider.getUserPicture.<anonymous closure> (package:transporter/src/providers/app_state_provider.dart:249:11)
flutter: #17     UploadService.getDetail (package:transporter/src/services/api/upload_service.dart)
flutter: <asynchronous suspension>
flutter: #18     AppStateProvider.getUserPicture (package:transporter/src/providers/app_state_provider.dart:240:14)
flutter: #19     AppStateProvider.resetUserPicture (package:transporter/src/providers/app_state_provider.dart:260:5)
flutter: #20     _DrawerWidgetState.build.<anonymous closure>.<anonymous closure> (package:transporter/src/widgets/drawer_widget.dart:208:46)
flutter: #21     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
flutter: #22     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
flutter: #23     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #24     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
flutter: #25     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
flutter: #26     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
flutter: #27     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
flutter: #28     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
flutter: #29     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #30     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #31     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #32     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #36     _invoke1 (dart:ui/hooks.dart:273:10)
flutter: #37     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
flutter: (elided 13 frames from class _AssertionError, package dart:async, and package dart:async-patch)
flutter:
flutter: The AppStateProvider sending notification was:
flutter:   Instance of 'AppStateProvider'
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by VladyslavBondarenko** [comment]
Hi @mustafayldz 
could you provide your `flutter doctor -v` and minimal complete code sample to reproduce the exception?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
