### ISSUE TITLE
Google maps is blurring parent widgets

### ISSUE THREAD

**Issue by marcusvbp** [flutter/flutter#57826]
I have noticied the google maps plugin applies a blur effect in parent widgets. 

![image](https://user-images.githubusercontent.com/4376611/82717568-55084980-9c73-11ea-8574-a8b0f6530071.png)

My code is something like this:

```
Container(
            color: Colors.red,
            padding: EdgeInsets.all(20),
            child: Container(
              color: Colors.green,
              padding: EdgeInsets.all(20),
              child: map
            )
```
this (side) effect is very annoying, it give-me some trouble with my layout:

![image](https://user-images.githubusercontent.com/4376611/82717630-ccd67400-9c73-11ea-848a-2d8ea6c18286.png)

**Comment by iapicca** [comment]
Hi @marcusvbp 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by marcusvbp** [comment]
```
flutter doctor -v
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale pt-BR)
    • Flutter version 1.19.0-1.0.pre at /Users/marcusviniciusbarrospontes/Projetos/flutter
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marcusviniciusbarrospontes/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/marcusviniciusbarrospontes/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • C456B5BD-0356-4150-A492-0F03A69E9A92 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

```
[        ] Waiting for observatory port to be available...
[+1526 ms] Observatory URL on device: http://127.0.0.1:52700/sqvSqbtNwWs=/
[  +30 ms] Connecting to service protocol: http://127.0.0.1:52700/sqvSqbtNwWs=/
[ +215 ms] Successfully connected to service protocol: http://127.0.0.1:52700/sqvSqbtNwWs=/
[        ] Waiting for iPhone SE (2nd generation) to report its views...
[   +5 ms] Waiting for iPhone SE (2nd generation) to report its views... (completed in 5ms)
[  +10 ms] DevFS: Creating new filesystem on the device (null)
[  +18 ms] DevFS: Created new filesystem on the device
(file:///Users/marcusviniciusbarrospontes/Library/Developer/CoreSimulator/Devices/C456B5BD-0356-4150-A492-0F03A69E9A92/data/Containers/Data/Application/D90995EB-C2
5D-4F0C-88EA-8E2B2954606C/tmp/vidadeinseto7yJK3G/vidadeinseto/)
[   +4 ms] Updating assets
[+1999 ms] Syncing files to device iPhone SE (2nd generation)...
[   +8 ms] Scanning asset files
[  +68 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +6 ms] <- recompile package:vidadeinseto/main.dart 8cf0f000-614c-4d04-9cb0-2b42b323ced2
[        ] <- 8cf0f000-614c-4d04-9cb0-2b42b323ced2
[+2161 ms] Updating files
[+1341 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone SE (2nd generation)... (completed in 3.587ms, longer than expected)
[   +1 ms] Synced 5.2MB.
[   +4 ms] <- accept
[   +3 ms] Connected to _flutterView/0x7fb25a02aa20.
[   +4 ms] Flutter run key commands.
[   +4 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone SE (2nd generation) is available at: http://127.0.0.1:52700/sqvSqbtNwWs=/
[+23264 ms] flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[  +24 ms] flutter: The following assertion was thrown resolving an image codec:
[        ] flutter: Unable to load asset: [137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0,
[        ] flutter: 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 10, 73, 68, 65, 84, 120, 156, 99, 0, 1, 0, 0, 5,
[        ] flutter: 0, 1, 13, 10, 45, 180, 0, 0, 0, 0, 73, 69, 78, 68, 174]
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:664:31)
[        ] flutter: #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:648:14)
[        ] flutter: #3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:501:13)
[   +4 ms] flutter: #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:358:22)
[        ] flutter: #5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:499:80)
[        ] flutter: #6      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
[        ] flutter: #7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:330:9)
[        ] flutter: #8      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:460:26)
[   +1 ms] flutter: #9      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:29)
[        ] flutter: #10     ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:457:11)
[        ] flutter: #14     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:449:16)
[        ] flutter: #15     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:327:5)
[        ] flutter: #16     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1114:16)
[        ] flutter: #17     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1067:5)
[        ] flutter: #18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4665:12)
[        ] flutter: #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
[        ] flutter: ...     Normal element mounting (4 frames)
[        ] flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
[        ] flutter: #24     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
[        ] flutter: ...     Normal element mounting (58 frames)
[        ] flutter: #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
[        ] flutter: #83     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
[  +32 ms] flutter: ...     Normal element mounting (89 frames)
[        ] flutter: #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
[        ] flutter: #173    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
[        ] flutter: ...     Normal element mounting (7 frames)
[        ] flutter: #180    ObserverElementMixin.mount (package:flutter_mobx/src/observer_widget_mixin.dart:67:11)
[        ] flutter: ...     Normal element mounting (7 frames)
[        ] flutter: #187    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
[        ] flutter: #188    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
[        ] flutter: ...     Normal element mounting (53 frames)
[        ] flutter: #241    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
[        ] flutter: #242    Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
[        ] flutter: #243    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1162:36)
[        ] flutter: #244    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1147:20)
[        ] flutter: #245    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
[        ] flutter: #246    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1140:11)
[        ] flutter: #247    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
[        ] flutter: #248    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)
[        ] flutter: #249    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
[        ] flutter: #250    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)
[        ] flutter: #251    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
[        ] flutter: #252    RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:427:5)
[        ] flutter: #253    RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
[        ] flutter: #254    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] flutter: #255    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:452:13)
[        ] flutter: #256    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1444:12)
[        ] flutter: #257    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1353:20)
[        ] flutter: #258    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] flutter: #259    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
[        ] flutter: #260    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] flutter: #261    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
[        ] flutter: #262    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] flutter: #263    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
[        ] flutter: #264    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[  +13 ms] flutter: #265    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
[        ] flutter: #266    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] flutter: #267    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
[        ] flutter: #268    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] flutter: #269    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
[        ] flutter: #270    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] flutter: #271    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
[        ] flutter: #272    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
[        ] flutter: #273    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
[        ] flutter: #274    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:480:7)
[        ] flutter: #275    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
[        ] flutter: #276    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
[        ] flutter: #277    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
[        ] flutter: #278    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
[        ] flutter: #279    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
[  +12 ms] flutter: #280    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
[        ] flutter: #281    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
[        ] flutter: #282    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
[        ] flutter: #283    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1013:9)
[        ] flutter: #284    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:929:5)
[        ] flutter: #288    _invoke (dart:ui/hooks.dart:277:10)
[        ] flutter: #289    _drawFrame (dart:ui/hooks.dart:235:3)
[        ] flutter: (elided 6 frames from dart:async)
[        ] flutter:
[        ] flutter: Image provider: AssetImage(bundle: null, name: "[137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73,
[        ] flutter:   72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0, 0, 0, 10, 73, 68, 65, 84,
[   +3 ms] flutter:   120, 156, 99, 0, 1, 0, 0, 5, 0, 1, 13, 10, 45, 180, 0, 0, 0, 0, 73, 69, 78, 68, 174]")
[        ] flutter: Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#898ed(), name: "[137, 80, 78, 71, 13, 10,
[        ] flutter:   26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0, 31, 21, 196, 137, 0,
[        ] flutter:   0, 0, 10, 73, 68, 65, 84, 120, 156, 99, 0, 1, 0, 0, 5, 0, 1, 13, 10, 45, 180, 0, 0, 0, 0, 73, 69,
[        ] flutter:   78, 68, 174]", scale: 1.0)
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[+9223 ms] Google Maps SDK for iOS version: 3.8.0.0
[        ] New version of Google Maps SDK for iOS available: 3.8.2.0
```

pubspec:

```
name: vidadeinseto
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  esys_flutter_share: ^1.0.2
  flutter_cache_manager: ^1.2.2
  fluster: ^1.1.2
  scrollable_positioned_list: ^0.1.4
  styled_text: ^1.0.0+1
  flutter_feather_icons: ^1.0.3
  photo_view: ^0.9.2
  flushbar: ^1.9.1
  gradient_widgets: ^0.5.2
  expandable: ^4.1.2
  convex_bottom_bar: ^2.1.0+1
  flutter_html: ^0.11.1
  google_fonts: ^0.3.9
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2
  percent_indicator: ^2.1.1+1
  badges: ^1.1.0
  camera: ^0.5.7+3
  dio: ^3.0.8
  after_layout: ^1.0.7+2
  geolocator: ^5.2.1
  google_maps_flutter: ^0.5.22
  hidden_drawer_menu: ^1.1.2
  transparent_image: ^1.0.0
  jiffy: ^2.2.0
  json_annotation: ^3.0.1
  carousel_slider: ^1.4.1
  flip_card: ^0.4.4
  flare_flutter: ^1.8.2
  flare_splash_screen: ^3.0.0
  sticky_headers: ^0.1.8+1
  intro_slider: ^2.2.8
  path_provider: ^1.5.1
  hive_flutter: ^0.3.0+1
  hive: ^1.3.0
  provider: ^4.0.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  mobx_codegen: ^1.0.2
  flutter_rename_app: ^1.0.0
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4
  json_serializable: ^3.2.5
  hive_generator: 0.7.0+2
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  quiver: 2.1.3
  path: 1.7.0
```

**Comment by marcusvbp** [comment]
code:

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';


class ExploreMapTest extends StatefulWidget {
  ExploreMapTest({Key key}) : super(key: key);

  @override
  _ExploreMapTestState createState() => _ExploreMapTestState();
}

class _ExploreMapTestState extends State<ExploreMapTest> {
  Completer<GoogleMapController> _controller = Completer();
  GoogleMapController mapController;

  @override
  Widget build(BuildContext context) {
    Widget map = GoogleMap(
      mapToolbarEnabled: false,
      zoomControlsEnabled: false,
      mapType: MapType.normal,
      myLocationButtonEnabled: false,
      initialCameraPosition: CameraPosition(
              target: LatLng(-7.122802,-34.858036),
              zoom: 15.5,
            ),
      onMapCreated: (GoogleMapController controller) async {
        mapController = controller;
        _controller.complete(controller);
      },
    );

    return Container(
      padding: EdgeInsets.all(20),
      margin: EdgeInsets.all(20),
      color: Colors.red,
      child: Container(
        padding: EdgeInsets.all(20),
        color: Colors.green,
        child: map,
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Hi @marcusvbp 
Just running your code sample has no blur effect  in latest `dev` 

<details> 
<summary>Code Sample</summary> 

``` 
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: ExploreMapTest(),
        ),
      ),
    );
  }
}

class ExploreMapTest extends StatefulWidget {
  ExploreMapTest({Key key}) : super(key: key);

  @override
  _ExploreMapTestState createState() => _ExploreMapTestState();
}

class _ExploreMapTestState extends State<ExploreMapTest> {
  Completer<GoogleMapController> _controller = Completer();
  GoogleMapController mapController;

  @override
  Widget build(BuildContext context) {
    Widget map = GoogleMap(
      mapToolbarEnabled: false,
      zoomControlsEnabled: false,
      mapType: MapType.normal,
      myLocationButtonEnabled: false,
      initialCameraPosition: CameraPosition(
        target: LatLng(-7.122802, -34.858036),
        zoom: 15.5,
      ),
      onMapCreated: (GoogleMapController controller) async {
        mapController = controller;
        _controller.complete(controller);
      },
    );

    return Container(
      padding: EdgeInsets.all(20),
      margin: EdgeInsets.all(20),
      color: Colors.red,
      child: Container(
        padding: EdgeInsets.all(20),
        color: Colors.green,
        child: map,
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details> 

![flutter_02](https://user-images.githubusercontent.com/48603081/82879761-0bfa1300-9f5b-11ea-8218-17495a92a6f4.png)

Please try this code sample
Thank you

**Comment by marcusvbp** [comment]
@TahaTesser Hi, how I can use the latest dev?

**Comment by snwagbata** [comment]
Hi @marcusvbp run `flutter channel dev` on the command line

**Comment by marcusvbp** [comment]
> Hi @marcusvbp run `flutter channel dev` on the command line

I am already in the flutter channel dev. But I think @TahaTesser is talking about the google_maps repo plugin, not the flutter

**Comment by TahaTesser** [comment]
Hi @marcusvbp 
Result i have commented is from latest `Channel dev, 1.19.0-1.0.pre` in this [comment](https://github.com/flutter/flutter/issues/57826#issuecomment-633892514) and using latest `  google_maps_flutter: ^0.5.28+1`

Please check out the code sample i posted earlier with latest dev and maps 
Thank you

**Comment by marcusvbp** [comment]
thanks. it worked.

**Comment by onats1** [comment]
Hello I've tried the solutions suggested above but widgets above the google maps widget still get blurred once the map loads (Specific to IOS devices).

**Comment by marcusvbp** [comment]
> Hello I've tried the solutions suggested above but widgets above the google maps widget still get blurred once the map loads (Specific to IOS devices).

do you have tried the code sample from @TahaTesser ?
