### ISSUE TITLE
[tool_crash] FormatException: No ':' on line (at offset 12)

### ISSUE THREAD

**Issue by ericzile** [flutter/flutter#57864]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=37A84260-B0F7-4083-B3A0-A34596ACF057 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException: FormatException: No ':' on line (at offset 12)
```
#0      parse (package:package_config/packages_file.dart:64:7)
#1      _parse (package:flutter_tools/src/dart/package_map.dart:17:10)
#2      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:49:14)
#3      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:53:5)
#4      new PackageUriMapper (package:flutter_tools/src/compile.dart:199:116)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:647:26)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:408:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:388:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:693:23)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#16     _rootRun (dart:async/zone.dart:1180:38)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
```
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale fr-CI)
    • Flutter version 1.17.0 at /Users/ericzile/AndroidStudioProjects/flutter
    • Framework revision e6b34c2b5c (3 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ericzile/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 37A84260-B0F7-4083-B3A0-A34596ACF057 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by jonahwilliams** [comment]
This should be fixed by the latest updates to package_config usage, but this change is not in stable

**Comment by jonahwilliams** [comment]
This is fixed via the removal of package_map

**Comment by pavanpodila** [comment]
Is this going to be in Stable soon? I am seeing an issue where the tool crashes and fails to report the proper coverage with this exact exception: https://github.com/mobxjs/mobx.dart/runs/1176235974?check_suite_focus=true#step:6:80

**Comment by jonahwilliams** [comment]
@pavanpodila I don't see any frames from the flutter tool in that crash, seems more like a package test issue?

**Comment by pavanpodila** [comment]
Thing is `pub run test` works just fine and does not fail any test. It's only when I run thru coverage, when I see this exception.

**Comment by jonahwilliams** [comment]
@pavanpodila then you need to file an issue against coverage, because the flutter tool is not involved there is nothing I can do specifically.

**Comment by pavanpodila** [comment]
> @pavanpodila then you need to file an issue against coverage, because the flutter tool is not involved there is nothing I can do specifically.

Ya, just realized that. I'll do that.
