### ISSUE TITLE
Unable to find package:flutter in ..flutter\packages\flutter

### ISSUE THREAD

**Issue by Gcastelo** [flutter/flutter#57935]
Hi, recently installed flutter 1.17.1-stable and ran into this issue when calling `flutter create`. 

## Steps to Reproduce

1. Updated PATH to have h:\tools\flutter\bin 
2. flutter create -v h:\projects\hello_world_flutter

## Logs

```
H:\tools\flutter\bin>flutter create -v h:\Projects\hello_world_flutter
The system cannot find the file specified.
[   +9 ms] executing: [H:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +61 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[        ] executing: [H:\tools\flutter/] git tag --contains HEAD
[ +172 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.1
[   +6 ms] executing: [H:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [H:\tools\flutter/] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +80 ms] executing: [H:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +28 ms] "flutter create" took 122ms.
Unable to find package:flutter in H:\tools\flutter\packages\flutter

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:297:7)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

### flutter doctor -v

```
H:\tools\flutter\bin>flutter doctor -v
The system cannot find the file specified.
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.17134.1488], locale en-GB)
    • Flutter version 1.17.1 at H:\tools\flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at H:\Users\Gustavo\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = H:\Users\Gustavo\AppData\Local\Android\sdk
    • Java binary at: H:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at H:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code
    • VS Code at H:\Users\Gustavo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at H:\Program Files\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • SM A505FN • R58M629K2LR • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @Gcastelo 
does the directory `H:\tools\flutter\packages\flutter` exist?

**Comment by Gcastelo** [comment]
It does and its contents are:

Directory of H:\tools\flutter\packages\flutter

25/05/2020  10:23    <DIR>          .
25/05/2020  10:23    <DIR>          ..
25/05/2020  10:23    <DIR>          .dart_tool
13/05/2020  18:59               739 BUILD.gn
13/05/2020  18:59               104 build.yaml
25/05/2020  10:23    <DIR>          coverage
13/05/2020  19:00               683 flutter.iml
25/05/2020  10:23    <DIR>          lib
               3 File(s)          1,526 bytes
               5 Dir(s)  16,295,665,664 bytes free

**Comment by jonahwilliams** [comment]
The line that is failing is:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart#L295

This is looking for a pubspec.yaml in the flutter directory. @Gcastelo it looks like there is no pubspec in the directory listing that you posted, can you confirm that it is absent?

**Comment by Gcastelo** [comment]
Indeed, the file is not there.

**Comment by jonahwilliams** [comment]
I can verify that these files are present in the uploaded zip. Perhaps try downloading again to see if they're getting extracted properly?

**Comment by Gcastelo** [comment]
Seems it was a problem with the previous zip file.

Just unzipped again and everything worked. Thank you!

**Comment by jonahwilliams** [comment]
Sorry for the trouble, glad everything is working now!
