### ISSUE TITLE
bug with path_provider

### ISSUE THREAD

**Issue by philos3** [flutter/flutter#57930]
# flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G4032,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/zby0520/flutter/flutter
    • Framework revision 0b8abb4724 (3 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.0-rc2)
    • Android SDK at /Users/zby0520/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-R, build-tools 29.0.0-rc2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/zby0520/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android
      Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/zby0520/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (1 available)
    • Feifei的 iPhone • 0f6cdb20033e5aded603a62d9a45f5079e4e09c2 • ios • iOS 12.1

# here is my code 
```
 Directory tempDir = await getTemporaryDirectory();
    double value = await _getTotalSizeOfFilesInDir(tempDir);
```

```
Future<double> _getTotalSizeOfFilesInDir(final FileSystemEntity file) async {
    if (file is File) {
      int length = await file.length();
      return double.parse(length.toString());
    }
    if (file is Directory) {
      final List<FileSystemEntity> children = file.listSync();
      double total = 0;
      if (children != null)
        for (final FileSystemEntity child in children)
          total += await _getTotalSizeOfFilesInDir(child);
      return total;
    }
    return 0;
  }
```

# here is the logs 
```
2020-05-25 16:51:38.752654+0800 Runner[3678:1075133] flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
2020-05-25 16:51:38.753130+0800 Runner[3678:1075133] flutter: The following FileSystemException was thrown:
2020-05-25 16:51:38.753358+0800 Runner[3678:1075133] flutter: Directory listing failed, path =
2020-05-25 16:51:38.753558+0800 Runner[3678:1075133] flutter: '/var/mobile/Containers/Data/Application/39BFC390-A961-47CE-96EE-EB858F08FA53/Library/Caches/Snapshots/'
2020-05-25 16:51:38.753934+0800 Runner[3678:1075133] flutter: (OS Error: Operation not permitted, errno = 1)
2020-05-25 16:51:38.754096+0800 Runner[3678:1075133] flutter:
2020-05-25 16:51:38.754390+0800 Runner[3678:1075133] flutter: When the exception was thrown, this was the stack:
2020-05-25 16:51:38.755720+0800 Runner[3678:1075133] flutter: #0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:39:68)
2020-05-25 16:51:38.756435+0800 Runner[3678:1075133] flutter: #1      _Directory.listSync (dart:io/directory_impl.dart:251:5)
2020-05-25 16:51:38.756650+0800 Runner[3678:1075133] flutter: #2      _CacheListTitleState._getTotalSizeOfFilesInDir (package:flutterbeauty/ui/page/tab/user_page.dart:467:52)
2020-05-25 16:51:38.756845+0800 Runner[3678:1075133] flutter: #3      _CacheListTitleState._getTotalSizeOfFilesInDir (package:flutterbeauty/ui/page/tab/user_page.dart:471:26)
2020-05-25 16:51:38.757055+0800 Runner[3678:1075133] flutter: <asynchronous suspension>
2020-05-25 16:51:38.757394+0800 Runner[3678:1075133] flutter: #4      _CacheListTitleState.loadCache (package:flutterbeauty/ui/page/tab/user_page.dart:438:26)
2020-05-25 16:51:38.757588+0800 Runner[3678:1075133] flutter: <asynchronous suspension>
2020-05-25 16:51:38.757742+0800 Runner[3678:1075133] flutter: #5      _CacheListTitleState.initState (package:flutterbeauty/ui/page/tab/user_page.dart:395:5)
2020-05-25 16:51:38.757910+0800 Runner[3678:1075133] flutter: #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
2020-05-25 16:51:38.758090+0800 Runner[3678:1075133] flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-05-25 16:51:38.758252+0800 Runner[3678:1075133] flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-05-25 16:51:38.758430+0800 Runner[3678:1075133] flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-05-25 16:51:38.758617+0800 Runner[3678:1075133] flutter: #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-05-25 16:51:38.758779+0800 Runner[3678:1075133] flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-05-25 16:51:38.759145+0800 Runner[3678:1075133] flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-05-25 16:51:38.759319+0800 Runner[3678:1075133] flutter: #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
2020-05-25 16:51:38.759550+0800 Runner[3678:1075133] flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-05-25 16:51:38.759714+0800 Runner[3678:1075133] flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-05-25 16:51:38.759930+0800 Runner[3678:1075133] flutter: #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-05-25 16:51:38.760102+0800 Runner[3678:1075133] flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-05-25 16:51:38.760288+0800 Runner[3678:1075133] flutter: #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-05-25 16:51:38.760471+0800 Runner[3678:1075133] flutter: #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-05-25 16:51:38.760605+0800 Runner[3678:1075133] flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-05-25 16:51:38.760798+0800 Runner[3678:1075133] flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-05-25 16:51:38.760980+0800 Runner[3678:1075133] flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-05-25 16:51:38.761137+0800 Runner[3678:1075133] flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-05-25 16:51:38.761313+0800 Runner[3678:1075133] flutter: #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-05-25 16:51:38.761477+0800 Runner[3678:1075133] flutter: #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-05-25 16:51:38.761665+0800 Runner[3678:1075133] flutter: #26     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)
2020-05-25 16:51:38.761873+0800 Runner[3678:1075133] flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-05-25 16:51:38.762061+0800 Runner[3678:1075133] flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-05-25 16:51:38.762227+0800 Runner[3678:1075133] flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-05-25 16:51:38.762446+0800 Runner[3678:1075133] flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-05-25 16:51:38.762608+0800 Runner[3678:1075133] flutter: #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-05-25 16:51:38.762789+0800 Runner[3678:1075133] flutter: #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
2020-05-25 16:51:38.762945+0800 Runner[3678:1075133] flutter: #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-05-25 16:51:38.763104+0800 Runner[3678:1075133] flutter: #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-05-25 16:51:38.763271+0800 Runner[3678:1075133] flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-05-25 16:51:38.763432+0800 Runner[3678:1075133] flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
2020-05-25 16:51:38.763604+0800 Runner[3678:1075133] flutter: #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
2020-05-25 16:51:38.763759+0800 Runner[3678:1075133] flutter: #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
2020-05-25 16:51:38.763903+0800 Runner[3678:1075133] flutter: #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
2020-05-25 16:51:38.764120+0800 Runner[3678:1075133] flutter: #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
2020-05-25 16:51:38.764367+0800 Runner[3678:1075133] flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
2020-05-25 16:51:38.764524+0800 Runner[3678:1075133] flutter: #42     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1288:36)
2020-05-25 16:51:38.764726+0800 Runner[3678:1075133] flutter: #43     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1273:20)
2020-05-25 16:51:38.764913+0800 Runner[3678:1075133] flutter: #44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
2020-05-25 16:51:38.764959+0800 Runner[3678:1075133] flutter: #45     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1266:11)
2020-05-25 16:51:38.764998+0800 Runner[3678:1075133] flutter: #46     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
2020-05-25 16:51:38.765503+0800 Runner[3678:1075133] flutter: #47     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1823:58)
2020-05-25 16:51:38.765783+0800 Runner[3678:1075133] flutter: #48     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
2020-05-25 16:51:38.766188+0800 Runner[3678:1075133] flutter: #49     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1823:13)
2020-05-25 16:51:38.766396+0800 Runner[3678:1075133] flutter: #50     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
2020-05-25 16:51:38.766555+0800 Runner[3678:1075133] flutter: #51     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
2020-05-25 16:51:38.766853+0800 Runner[3678:1075133] flutter: #52     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
2020-05-25 16:51:38.767007+0800 Runner[3678:1075133] flutter: #53     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
2020-05-25 16:51:38.767182+0800 Runner[3678:1075133] flutter: #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.767357+0800 Runner[3678:1075133] flutter: #55     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
2020-05-25 16:51:38.767550+0800 Runner[3678:1075133] flutter: #56     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
2020-05-25 16:51:38.767768+0800 Runner[3678:1075133] flutter: #57     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
2020-05-25 16:51:38.767960+0800 Runner[3678:1075133] flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.768136+0800 Runner[3678:1075133] flutter: #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.768301+0800 Runner[3678:1075133] flutter: #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.768434+0800 Runner[3678:1075133] flutter: #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.768634+0800 Runner[3678:1075133] flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.768796+0800 Runner[3678:1075133] flutter: #63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.768978+0800 Runner[3678:1075133] flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.769140+0800 Runner[3678:1075133] flutter: #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.769323+0800 Runner[3678:1075133] flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.769477+0800 Runner[3678:1075133] flutter: #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.769663+0800 Runner[3678:1075133] flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.769847+0800 Runner[3678:1075133] flutter: #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.770016+0800 Runner[3678:1075133] flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.770182+0800 Runner[3678:1075133] flutter: #71     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
2020-05-25 16:51:38.770366+0800 Runner[3678:1075133] flutter: #72     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
2020-05-25 16:51:38.770521+0800 Runner[3678:1075133] flutter: #73     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
2020-05-25 16:51:38.770688+0800 Runner[3678:1075133] flutter: #74     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
2020-05-25 16:51:38.770958+0800 Runner[3678:1075133] flutter: #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.771188+0800 Runner[3678:1075133] flutter: #76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.771380+0800 Runner[3678:1075133] flutter: #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.771542+0800 Runner[3678:1075133] flutter: #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.771713+0800 Runner[3678:1075133] flutter: #79     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
2020-05-25 16:51:38.771903+0800 Runner[3678:1075133] flutter: #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.772061+0800 Runner[3678:1075133] flutter: #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.772239+0800 Runner[3678:1075133] flutter: #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.772421+0800 Runner[3678:1075133] flutter: #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2020-05-25 16:51:38.772588+0800 Runner[3678:1075133] flutter: #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.772741+0800 Runner[3678:1075133] flutter: #85     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:245:18)
2020-05-25 16:51:38.772926+0800 Runner[3678:1075133] flutter: #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.773092+0800 Runner[3678:1075133] flutter: #87     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:134:11)
2020-05-25 16:51:38.773282+0800 Runner[3678:1075133] flutter: #88     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver.dart:1165:11)
2020-05-25 16:51:38.773440+0800 Runner[3678:1075133] flutter: #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
2020-05-25 16:51:38.773611+0800 Runner[3678:1075133] flutter: #90     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
2020-05-25 16:51:38.773768+0800 Runner[3678:1075133] flutter: #91     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
2020-05-25 16:51:38.773930+0800 Runner[3678:1075133] flutter: #92     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
2020-05-25 16:51:38.774059+0800 Runner[3678:1075133] flutter: #93     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
2020-05-25 16:51:38.774227+0800 Runner[3678:1075133] flutter: #94     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
2020-05-25 16:51:38.774406+0800 Runner[3678:1075133] flutter: #95     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
2020-05-25 16:51:38.774638+0800 Runner[3678:1075133] flutter: #96     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
2020-05-25 16:51:38.774822+0800 Runner[3678:1075133] flutter: #97     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
2020-05-25 16:51:38.774988+0800 Runner[3678:1075133] flutter: #98     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
2020-05-25 16:51:38.775169+0800 Runner[3678:1075133] flutter: #99     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
2020-05-25 16:51:38.775336+0800 Runner[3678:1075133] flutter: #100    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
2020-05-25 16:51:38.775512+0800 Runner[3678:1075133] flutter: #104    _invoke (dart:ui/hooks.dart:259:10)
2020-05-25 16:51:38.775684+0800 Runner[3678:1075133] flutter: #105    _drawFrame (dart:ui/hooks.dart:217:3)
2020-05-25 16:51:38.775859+0800 Runner[3678:1075133] flutter: (elided 3 frames from package dart:async)
2020-05-25 16:51:38.776094+0800 Runner[3678:1075133] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by iapicca** [comment]
Hi @philos3 
could you please run `flutter upgrade —force`,
If the issue persist please provide your updated `flutter doctor -v` 
your `flutter run --verbose`,
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
