### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, path = '/Volumes/SD256/Github/flutter_module/build/ios/iphoneos/Runner.app' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by slanska** [flutter/flutter#57950]
## Command
```
flutter build ios --release
```

## Steps to Reproduce
1. Create a new Flutter module, according to https://flutter.dev/docs/development/add-to-app/ios/project-setup
2. Build iOS version (debug mode by default), integrated it into existing app, added call to Flutter module, run the app in a simulator, everything worked OK
3. Run Fastlane build (this is what we are using for CI/CD), got error that Flutter needs to run in release mode or have FLUTTER_BUILD_MODE = release.
4. Try rebuilding Flutter module using 'flutter build ios -- release'. Every second run it fails with the error "FileSystemException, path ... OS Error: No such file or directory"
5. Also, even after successful running release build manually, fastlane still fails

## Logs
FileSystemException: FileSystemException: Deletion failed, path = '/Volumes/SD256/Github/flutter_module/build/ios/iphoneos/Runner.app' (OS Error: No such file or directory, errno = 2)
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:208:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:460:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:385:41)
<asynchronous suspension>
#4      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:83:43)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#13     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
```
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.1 19B88, locale en-CA)
    • Flutter version 1.17.1 at ~/flutter
    • Framework revision f7a6a7906b (13 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ~/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: ~/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at ~/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 6s • A906D945-1904-4A95-8EBB-EC8E080ADA77 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.***.flutter_module
**iOS bundle identifier**: com.***.flutterModule
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe

**Comment by TahaTesser** [comment]
might be related to https://github.com/flutter/flutter/issues/51138

**Comment by jmagman** [comment]
Wonder how the delete keeps failing, it's inside an exists check (`isDirectorySync` should return false if the file doesn't exist...):

https://github.com/flutter/flutter/blob/1.17.1/packages/flutter_tools/lib/src/ios/mac.dart#L382-L386
```dart
      if (globals.fs.isDirectorySync(outputDir)) {
        // Previous output directory might have incompatible artifacts
        // (for example, kernel binary files produced from previous run).
        globals.fs.directory(outputDir).deleteSync(recursive: true);
      }
```

**Comment by Aziz-cs** [comment]
I solved this issue by doing these steps:

 1. Go to this path which it says Runner.app does not exist. (Typically it's "../projectName/build/ios/iphonesimulator/Runner.app').
 2. Copy 'Runner.app' then Paste it again in the same directory, it will produce a new file named 'Runner copy.app'
 3. Delete the original file which is not detected 'Runner.app'
 4. Rename the copied file from 'Runner copy.app' to 'Runner.app'.
 5. Try to re-run the app again and it should work.

**Comment by Aziz-cs** [comment]
I changed the directory of the project to the root directory which Mac OS is installed and it worked.
