### ISSUE TITLE
[WebView] Issue in using Hero with webview and global keys, "Multiple widgets used the same GlobalKey."

### ISSUE THREAD

**Issue by renenucci** [flutter/flutter#57969]
Hi, I'm facing an "Multiple widgets used the same GlobalKey."  issue when tried put a global key in 2 webviews that is the same, according this video (https://youtu.be/RA-vLF_vnng?t=281), she said to put a global key in two widgets to prevent flutter to re-render the second one.

I Tried even the Navigator.pushReplacement to avoid duplicate keys, (but in my case, I need to have the possibility to go to previous page)

Here is a full sample, the hero transition works, but the go "back" freezes on my iOS, and the console logs "Multiple widgets used the same GlobalKey."

`import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:test_web_view/example.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'page.dart';

void main() {
  runApp(StockDetailsPage());
}

class StockDetailsPage extends StatelessWidget {
  const StockDetailsPage({Key key, this.symbol}) : super(key: key);
  final String symbol;

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView(
        children: <Widget>[
          Container(
            height: 500,
            child: Example(
              foo: false,
              child: Hero(
                tag: 'Teste',
                child: WebView(
                  key: gkey,
                  initialUrl: 'https://www.google.com.br',
                  javascriptMode: JavascriptMode.unrestricted,
                ),
              ),
            ),
          ),
          RaisedButton(
            child: Text('Go to Page 2'),
            onPressed: () async {
              await Navigator.of(context).push(
                MaterialPageRoute(builder: (context) => PageTwo()),
              );
            },
          ),
          Container(height: 600, color: Colors.red),
        ],
      ),
    );
  }
}

class PageTwo extends StatefulWidget {
  @override
  _PageState createState() => _PageState();
}

class _PageState extends State<PageTwo> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Hero(
        tag: 'Teste',
        child: WebView(key: gkey),
      ),
    );
  }
}

final gkey = GlobalKey();
`

Flutter Doctor
`[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.17.1 at /Users/Mycap/documents/flutter
    • Framework revision f7a6a7906b (13 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Mycap/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone de Hb • 00008020-00113DD222C3002E • ios • iOS 13.3`

Any idea?

**Comment by TahaTesser** [comment]
Hi @renenucci 
Can you please provide complete minimal code sample? 
Thank you

**Comment by renenucci** [comment]
> Hi @renenucci
> Can you please provide complete minimal code sample? you have some missing code in your code sample
> Thank you

Hi, sorry, I have updated the code!

**Comment by TahaTesser** [comment]
```
════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 3233 pos 12: 'offstage': is not true.
The relevant error-causing widget was
    Hero 
lib/main.dart:87
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Multiple widgets used the same GlobalKey.
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!

``` 

</details>

**Comment by TahaTesser** [comment]
<details>
<summary>logs</summary>

```bash

           2021-01-15 20:59:47.412 xcodebuild[61067:562784]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
           Details:  (null) deviceType from 00008020-000255113EE8402E was NULL when -platform called.
           Object:   <DTDKMobileDeviceToken: 0x7fda3d870d80>
           Method:   -platform
           Thread:   <NSThread: 0x7fda398868b0>{number = 3, name = (null)}
           Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[ +248 ms] executing: xcrun simctl install 2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/webview_flutter_example/build/ios/iphonesimulator/Runner.app
[+1010 ms] executing: /usr/bin/plutil -convert json -o - /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/webview_flutter_example/build/ios/iphonesimulator/Runner.app/Info.plist
[  +31 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/tahatesser/AndroidStudioProjects/triage-examples/flutter_plugin_examples/webview_flutter_example/build/ios/iphonesimulator/Runner.app/Info.plist
[        ] {"DTXcode":"1230","DTSDKName":"iphonesimulator14.3","CFBundleName":"webview_flutter_example","UILaunchStoryboardName":"LaunchScreen","CFBundleIcons~ipad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60","AppIcon76x76","AppIcon83.5x83.5"],"CFBundleIconName":"AppIcon"}},"DTSDKBuild":"18C61","CFBundleDevelopmentRegion":"en","io.flutter.embedded_views_preview":true,"CFBundleVersion":"1","BuildMachineOSBuild":"20C69","DTPlatformName":"iphonesimulator","CFBundleShortVersionString":"1.0.0","UIMainStoryboardFile":"Main","CFBundleSupportedPlatforms":["iPhoneSimulator"],"CFBundlePackageType":"APPL","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"Runner","DTCompiler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"MinimumOSVersion":"9.0","CFBundleIdentifier":"com.nevercode.triage","UIDeviceFamily":[1,2],"DTPlatformVersion":"14.3","CFBundleSignature":"????","CFBundleIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"12C33","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"NSBonjourServices":["_dartobservatory._tcp"],"DTPlatformBuild":"18C61","NSLocalNetworkUsageDescription":"Allow Flutter tools on your computer to connect and debug your application. This prompt will not appear on release builds."}
[   +2 ms] executing: xcrun simctl launch 2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF com.nevercode.triage --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
[ +280 ms] com.nevercode.triage: 61091
[        ] Waiting for observatory port to be available...
[ +849 ms] Observatory URL on device: http://127.0.0.1:64812/_dbVYIonhqo=/
[   +3 ms] Caching compiled dill
[ +149 ms] Connecting to service protocol: http://127.0.0.1:64812/_dbVYIonhqo=/
[   +4 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:64812/_dbVYIonhqo=/.
[ +192 ms] DDS is listening at http://127.0.0.1:64816/wFiPhzZigHI=/.
[  +90 ms] Successfully connected to service protocol: http://127.0.0.1:64812/_dbVYIonhqo=/
[+1142 ms] DevFS: Creating new filesystem on the device (null)
[  +24 ms] DevFS: Created new filesystem on the device (file:///Users/tahatesser/Library/Developer/CoreSimulator/Devices/2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF/data/Containers/Data/Application/8EAF4FE7-5A99-4348-9188-9052C2D37695/tmp/webview_flutter_exampleserFsl/webview_flutter_example/)
[   +3 ms] Updating assets
[  +96 ms] Syncing files to device iPhone 12...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +4 ms] <- recompile package:triage/main.dart 8a494414-5280-48f5-8a1a-01a07b4572ac
[        ] <- 8a494414-5280-48f5-8a1a-01a07b4572ac
[ +154 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device iPhone 12... (completed in 161ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +5 ms] Connected to _flutterView/0x7fc07181c420.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 12 is available at: http://127.0.0.1:64816/wFiPhzZigHI=/
[   +1 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on iPhone 12 is available at: http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A64816%2FwFiPhzZigHI%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+9149 ms] 
           ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
           The following assertion was thrown while finalizing the widget tree:
           Duplicate GlobalKey detected in widget tree.
           The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of
           the widget tree being truncated unexpectedly, because the second time a key is seen, the previous
           instance is moved to the new location. The key was:
           - [GlobalKey#17681]
           This was determined by noticing that after the widget with the above global key was moved out of its
           previous parent, that previous parent never updated during this frame, meaning that it either did
           not update at all or updated before the widget was moved, in either case implying that it still
           thinks that it should have a child with that global key.
           The specific parent that did not update after having one or more children forcibly removed due to
           GlobalKey reparenting is:
           - KeyedSubtree-[GlobalKey#f6141]
           A GlobalKey can only be specified on one widget at a time in the widget tree.

           When the exception was thrown, this was the stack:
           #0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2845:15)
           #1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2870:8)
           #2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:871:19)
           #3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
           #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
           #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
           #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
           #10     _invoke (dart:ui/hooks.dart:157:10)
           #11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
           #12     _drawFrame (dart:ui/hooks.dart:120:31)
           (elided 3 frames from dart:async)
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +50 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[  +18 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[ +149 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[ +108 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios           • iOS 14.3
    • iPhone 12 (mobile)   • 2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.365, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.365 at /Users/tahatesser/Code/flutter_master
    • Framework revision 9209319dd1 (7 hours ago), 2021-01-15 14:34:03 +0530
    • Engine revision efa768683e
    • Dart version 2.12.0 (build 2.12.0-225.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.3
    • iPhone 12 (mobile)   • 2FC46D8B-2A58-4ABB-B3FF-76F1AEC857FF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by GiacomoRandazzo** [comment]
I encountered the same problem.
Is there any update?

**Comment by danagbemava-nc** [comment]
The issue is reproducible on the latest `master 2.5.0-6.0.pre.29` and `stable 2.2.3` with `webview_flutter: ^2.0.10`.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.29, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.5.0-6.0.pre.29 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6876c52b5b (8 hours ago), 2021-08-08 15:34:09 -0700
    • Engine revision c0e59bc7b6
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```


```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```

</details>

<details>
<summary>logs</summary>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.
The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of
the widget tree being truncated unexpectedly, because the second time a key is seen, the previous
instance is moved to the new location. The key was:
- [GlobalKey#a9bdf WebViewKey]
This was determined by noticing that after the widget with the above global key was moved out of its
previous parent, that previous parent never updated during this frame, meaning that it either did
not update at all or updated before the widget was moved, in either case implying that it still
thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to
GlobalKey reparenting is:
- KeyedSubtree-[GlobalKey#01cfb]
A GlobalKey can only be specified on one widget at a time in the widget tree.

When the exception was thrown, this was the stack:
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2900:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2925:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:877:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#10     _invoke (dart:ui/hooks.dart:163:10)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#12     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Multiple widgets used the same GlobalKey.
```
</details>

**Comment by SAGARSURI** [comment]
Any update on this?
