### ISSUE TITLE
Assertion failure when using baseline alignment in Table widget

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#58053]
# Steps to reproduce

Run the following app:

```dart
void main() {
  runApp(FailingApp());
}

class FailingApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'textBaseline assertion failure',
      home: Scaffold(
        body: Table(
          defaultVerticalAlignment: TableCellVerticalAlignment.baseline,
          children: <TableRow>[
            TableRow(
              children: <Widget>[
                Text('SCI - Overhead'),
                TextField(),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
```

# Expected Behavior

You expect the table cells to be baseline aligned

# Actual behavior

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/table.dart': Failed assertion: line 1047 pos 22: 'textBaseline !=
flutter: null': is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: The relevant error-causing widget was:
flutter:   Table file:///Users/tvolkert/project/sci/apps/payouts/lib/main.dart:41:15
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderTable.performLayout (package:flutter/src/rendering/table.dart:1047:22)
flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #4      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
flutter: #5      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:480:7)
flutter: #6      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
flutter: #7      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
flutter: #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #12     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1267:11)
flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #20     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #33     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3219:13)
flutter: #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #35     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:700:15)
flutter: #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
flutter: #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #49     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
flutter: #50     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
flutter: #51     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
flutter: #52     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
flutter: #53     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
flutter: #54     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #55     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #56     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #57     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:861:7)
flutter: (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter: 
flutter: The following RenderObject was being processed when the exception was fired: RenderTable#f4f8b relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: Table ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
flutter:     CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
flutter:     _InkFeatures-[GlobalKey#6e62e ink renderer] ← NotificationListener<LayoutChangedNotification> ←
flutter:     PhysicalModel ← AnimatedPhysicalModel ← ⋯
flutter:   parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=1213.0, 0.0<=h<=684.0)
flutter:   size: MISSING
flutter:   default column width: FlexColumnWidth(1.0)
flutter:   table size: 2×1
flutter:   column offsets: 0.0, 606.5
flutter:   row offsets: 0.0
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child (0, 0): RenderParagraph#73f52 NEEDS-LAYOUT NEEDS-PAINT
flutter:       text: TextSpan
flutter:     child (1, 0): RenderIgnorePointer#9ee2e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child: RenderMouseRegion#4c3d0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderSemanticsAnnotations#c0070 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderPointerListener#ddf27 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: _RenderDecoration#2c064 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
```

**Comment by goderbauer** [comment]
Looks like you'll have to provide the textBaseline to use to the Table when using `TableCellVerticalAlignment.baseline` by setting this property: https://master-api.flutter.dev/flutter/widgets/Table/textBaseline.html

We definitely need to document this better and we could also add an assert to the Table constructor that warns if `textBaseline` is unset when using `TableCellVerticalAlignment.baseline`.

**Comment by tvolkert** [comment]
Should we default `textBaseline` to `alphabetic` in the `Table` constructor?

**Comment by AyushBherwani1998** [comment]
@tvolkert But having `textBaseline` will make no difference until `defaultVerticalAlignment` is `TableCellVerticalAlignment.baseline` which can be confusing to users unless we have mentioned the behaviour in the docs. So instead of having that in constructor, can we check if the `defaultVerticalAlignment` is `TableCellVerticalAlignment.baseline` and `textBaseline` is null then `textBaseline` should be by default `TextBaseline.alphabetic`, WDYT?

**Comment by tvolkert** [comment]
That's analogous to how `TextField` defaults `obscuringCharacter` to `•` even though `obscureText` defaults to `false`...

**Comment by goderbauer** [comment]
Defaulting it seems fine to me (even if it us not used in the current context).

**Comment by Hixie** [comment]
We should revert this. We have no way to know that the correct baseline is alphabetic.

**Comment by tvolkert** [comment]
@Hixie 

> We have no way to know that the correct baseline is alphabetic.

Devil's advocate: we have no way to know that the correct MainAxisAlignment for a Row is MainAxisAlignment.start either.  It's just a default value that can be explicitly specified by the caller if it's not the right default.

**Comment by Hixie** [comment]
Ok, in that case let's use the Thai hanging baseline as the default.

**Comment by tvolkert** [comment]
Not sure what you mean -- `TextBaseline` is an enum with two values... (alphabetic and ideographic)

**Comment by Hixie** [comment]
Well we should add the Thai hanging baseline first of course.

My point is that an arbitrary default for textBaseline cannot help but introduce an ethnocentric cultural bias. See also the design discussion for dart:ui's [TextDirection](https://master-api.flutter.dev/flutter/dart-ui/TextDirection-class.html) in the API docs.

**Comment by tvolkert** [comment]
TIL about the various types of baselines.  I wasn't aware that an alphabetic baseline introduced an ethnocentric cultural bias because I wasn't aware of the various baselines, and their absence from our enum just confused me more in this discussion 🙂 

![4KFN3ceRPR63zrF](https://user-images.githubusercontent.com/15253456/96950735-d91f6100-149f-11eb-848f-f9df09a2d1c4.png)

(source: https://drafts.csswg.org/css-inline/)

So, it looks like in your revert, you're fixing the error messages to no longer trigger the "Either the assertion indicates an error in the framework itself, ..." error message?
