### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:adb.exe: error: device '4d00eadcc6b94200' not found  Command: C:\Android\tools\platform-tools\adb.exe -s 4d00eadcc6b94200 forward --remove tcp:55329

### ISSUE THREAD

**Issue by fariswidaa** [flutter/flutter#58091]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: ProcessException: Process exited abnormally:
adb.exe: error: device '4d00eadcc6b94200' not found
  Command: C:\Android\tools\platform-tools\adb.exe -s 4d00eadcc6b94200 forward --remove tcp:55329
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      _AndroidDevicePortForwarder.unforward (package:flutter_tools/src/android/android_device.dart:1284:24)
#3      _AndroidDevicePortForwarder.dispose (package:flutter_tools/src/android/android_device.dart:1293:13)
#4      AndroidDevice.dispose (package:flutter_tools/src/android/android_device.dart:732:27)
#5      HotRunner.cleanupAtFinish (package:flutter_tools/src/run_hot.dart:1110:34)
#6      ResidentRunner.waitForAppToFinish (package:flutter_tools/src/resident_runner.dart:1008:11)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:309:22)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:342:12)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:556:37)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:669:18)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
```
```
[✓] Flutter (Channel master, v1.15.2-pre.34, on Microsoft Windows [Version 6.3.9600], locale ar-SA)
    • Flutter version 1.15.2-pre.34 at C:\flutter_windows_v1.12.13+hotfix.5-stable\flutter
    • Framework revision 5c28e3eeea (4 months ago), 2020-02-07 06:35:50 +0100
    • Engine revision f34bc65bee
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 b3396cbdca)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android\tools
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Android\tools
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\LENOVO G50\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.42.1)
    • VS Code at C:\Users\LENOVO G50\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • SM G360H   • 4d00eadcc6b94200 • android-arm    • Android 4.4.4 (API 19)
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.61
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
firebase_auth-0.16.0
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2

**Comment by TahaTesser** [comment]
Hi @fariswidaa 
I noticed you've 4 months old `master` channel, please upgrade to latest `master`
If the problem persist with latest `master`, please create a new issue and provide necessary details
Thank you
