### ISSUE TITLE
The problem of FlutterEngine in native communication

### ISSUE THREAD

**Issue by romantiskt** [flutter/flutter#58160]
pubspec.yaml
`
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_easyrefresh: ^2.1.1
  flutter_swiper : ^1.1.4
  flutter:
    sdk: flutter
`
flutter channel --> master

**1.When I initialize the MethodChannel in the FragmentActivity configureFlutterEngine**
`
class MyFlutterActivity : FlutterActivity() {
    private val CHANNEL_NETWORK = "native_network"
    private val CHANNEL_LOG = "native_log"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            CHANNEL_NETWORK
        ).setMethodCallHandler {
            // Note: this method is invoked on the main thread.
                call, result ->
            //call.method是获取调用的方法名字
            //call.arguments 是获取参数
            if (call.method == "test") {
                val batteryLevel: String = "hello kotlin"
                if (batteryLevel != null) {
                    result.success(batteryLevel) // 相当于是调用方法的return
                } else {
                    result.error("UNAVAILABLE", "Battery level not available.", null) // 告诉调用者失败了
                }
            } else {
                result.notImplemented() // 告诉调用者没有此方法，避免一直等到阻塞在这
            }
        }

        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            CHANNEL_LOG
        ).setMethodCallHandler(MethodCallHandler { call, result ->
            var tag: String = call.argument("tag") ?: "flutter"
            var message: String = call.argument("msg") ?: ""
            when (call.method) {
                "logV" -> Log.v(tag, message)
                "logD" -> Log.d(tag, message)
                "logI" -> Log.i(tag, message)
                "logW" -> Log.w(tag, message)
                "logE" -> Log.e(tag, message)
            }
            result.success("success");
        })
    }

}
`
**2.I use the Cache Engine in my app**

`
class App:Application() {
     lateinit var flutterEngine : FlutterEngine

    /**
     * 这里有坑，如果dark中有调用native的代码，此处应该会去初始化dark代码，从而报错
     * 即你在原生注册的方法MethodChannel不会生效，
     */
    override fun onCreate() {
        super.onCreate()
        flutterEngine = FlutterEngine(this)
        flutterEngine.dartExecutor.executeDartEntrypoint(
            DartExecutor.DartEntrypoint.createDefault()
        )
        FlutterEngineCache
            .getInstance()
            .put("my_engine_id", flutterEngine)
    }
}
`
**3.And then I start flutter somewhere in my app**
`
  var intent = Intent(context, MyFlutterActivity::class.java)
        intent.putExtra("cached_engine_id", "my_engine_id")
        intent.putExtra("background_mode", FlutterActivityLaunchConfigs.BackgroundMode.transparent.name)
        startActivity(intent)
`
**4.The code in the dark is normal, I won't list it**

**5.Then I get the following error**
`
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method logD on channel native_log)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
    #2      LogUtils.d (package:fluttermodule/util/LogUtils.dart:11:13)
    #3      MinePageState.initState (package:fluttermodule/module/home/MinePage.dart:43:14)
    #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4649:58)
    #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
    #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
    #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
    #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
    #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
    #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
`

**6.When I initialize the MethodChannel in my App, this problem doesn't arise**

`
class App:Application() {
     lateinit var flutterEngine : FlutterEngine
    private val CHANNEL_NETWORK = "native_network"
    private val CHANNEL_LOG = "native_log"
    /**
     * 这里有坑，如果用缓存engine,则应在此处初始化MethodChannel,
     * 而不是FlutterActivity中的configureFlutterEngine方法
     */
    override fun onCreate() {
        super.onCreate()
        flutterEngine = FlutterEngine(this)
        flutterEngine.dartExecutor.executeDartEntrypoint(
            DartExecutor.DartEntrypoint.createDefault()
        )
        FlutterEngineCache
            .getInstance()
            .put("my_engine_id", flutterEngine)

        initMethodChannel()
    }

    private fun initMethodChannel() {
        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            CHANNEL_NETWORK
        ).setMethodCallHandler {
                call, result ->
            if (call.method == "test") {
                val batteryLevel: String = "hello kotlin"
                if (batteryLevel != null) {
                    result.success(batteryLevel) // 相当于是调用方法的return
                } else {
                    result.error("UNAVAILABLE", "Battery level not available.", null) // 告诉调用者失败了
                }
            } else {
                result.notImplemented() // 告诉调用者没有此方法，避免一直等到阻塞在这
            }
        }

        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            CHANNEL_LOG
        ).setMethodCallHandler(MethodChannel.MethodCallHandler { call, result ->
            var tag: String = call.argument("tag") ?: "flutter"
            var message: String = call.argument("msg") ?: ""
            when (call.method) {
                "logV" -> Log.v(tag, message)
                "logD" -> Log.d(tag, message)
                "logI" -> Log.i(tag, message)
                "logW" -> Log.w(tag, message)
                "logE" -> Log.e(tag, message)
            }
            result.success("success");
        })
    }
}
`

**Comment by TahaTesser** [comment]
Hi 
Can you please provide your `flutter doctor -v`, and if you provide an example repo, would be helpful
Thank you

**Comment by romantiskt** [comment]
@TahaTesser 
Thank you for your reply. This should be a problem caused by the use of cache engine. As there are other tasks at hand, I cannot provide the demo for the moment
```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.19.0-2.0.pre.143 at /Users/wangyang/flutter
    • Framework revision 9d58a87066 (9 days ago), 2020-05-22 22:37:01 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wangyang/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/wangyang/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.3.1 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] Connected device (1 available)
    • MI 8 • 37f16afd • android-arm64 • Android 9 (API 28)

```

**Comment by jmagman** [comment]
Sounds like an add-to-app specific version of https://flutter.dev/docs/development/platform-integration/platform-channels#step-3-add-an-android-platform-specific-implementation documentation would be helpful.

**Comment by xster** [comment]
This is a guess so it may or may not solve your issue. 

When you call `flutterEngine.dartExecutor.executeDartEntrypoint` you're already running your dart code. If that dart code makes a platform channel call right then and there, it would be before you have setup your callback handlers. The configureFlutterEngine of your FlutterActivity happens after you show your activity.

**Comment by xster** [comment]
We should definitely fix https://flutter.dev/docs/development/platform-integration/platform-channels#step-3-add-an-android-platform-specific-implementation and add add-to-app caveats

**Comment by originlan** [comment]
@xster Thank you very much. Now the problem is that the first jump is still misspluging, but I went back to the last page and found that I was still flutter page and channel is working. What a wonder!
So I should execute the configureflengine first, and then activate getContext().startActivity(
FlutterActivity. CreateDefaultIntent (getApplicationContext ())
)? Now it's the other way around with Debug

**Comment by chenchongyu** [comment]
Thanks Very Much! You solved my Problem.  我搜索了好久好多地方，终于在这里看到了答案
