### ISSUE TITLE
Compilation fails with 'InvalidType doesn't have nullability'

### ISSUE THREAD

**Issue by muzzah** [flutter/flutter#58167]
## Steps to Reproduce

I actually am still investigating why this is happening but when I try to compile/run the web version of my multi platform app, the compilation fails with the stack trace and message below.

Im hoping I can get some guidance on why this type of error occurs so I can try to nail it down.
Note, mobile compilation works without issues

```Launching lib/main.dart on Web Server in debug mode...
Syncing files to device Web Server...
Unhandled exception:
InvalidType doesn't have nullability
#0      InvalidType.nullability (package:kernel/ast.dart:6709:34)
#1      ProgramCompiler._mustBeNonNullable (package:dev_compiler/src/kernel/compiler.dart:3129:14)
#2      ProgramCompiler._emitArgumentInitializers.initParameter (package:dev_compiler/src/kernel/compiler.dart:3163:18)
#3      ProgramCompiler._emitArgumentInitializers (package:dev_compiler/src/kernel/compiler.dart:3185:20)
#4      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1375:16)
#5      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1355:19)
#6      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:3122:24)
#7      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1354:15)
#8      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2096:25)
#9      ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3112:18)
#10     ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1352:16)
#11     ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:972:38)
#12     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:567:19)
#13     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:510:21)
#14     List.forEach (dart:core-patch/growable_array.dart:282:8)
#15     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:459:23)
#16     List.forEach (dart:core-patch/growable_array.dart:282:8)
#17     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:345:15)
#18     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:133:33)
<asynchronous suspension>
#19     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:627:20)
<asynchronous suspension>
#20     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:533:15)
<asynchronous suspension>
#21     _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#22     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1164:26)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#37     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#38     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#39     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#40     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:315:20)
#41     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:308:5)
#42     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#43     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#44     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#45     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#46     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#47     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#48     _StreamController._add (dart:async/stream_controller.dart:655:7)
#49     _StreamController.add (dart:async/stream_controller.dart:597:5)
#50     _Socket._onData (dart:io-patch/socket_patch.dart:1999:41)
#51     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#55     _StreamController._add (dart:async/stream_controller.dart:655:7)
#56     _StreamController.add (dart:async/stream_controller.dart:597:5)
#57     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1544:33)
#58     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1036:14)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.
```

## Logs

```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-NL)
    • Flutter version 1.18.0-11.1.pre at /usr/local/Cellar/flutter/0.5.1
    • Framework revision 2738a1148b (2 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mustuhfa/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM T580    • 52007eeafeb1b44f • android-arm    • Android 8.1.0 (API 27)
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 81.0.4044.138
```

**Comment by VladyslavBondarenko** [comment]
Hi @muzzah 
could you provide your `flutter run -d web-server --verbose`?

**Comment by muzzah** [comment]
I seem to solve this problem, was with a dependency that did not have web support.

**Comment by jonahwilliams** [comment]
We should crash with a better error than this then, re-opening

**Comment by pmdatgithub** [comment]
"I seem to solve this problem, was with a dependency that did not have web support." - Can someone please elaborate what the problem was?

**Comment by pmdatgithub** [comment]
> dependency

Could you please elaborate? I have the same problem.

I have below dependencies
dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.1.1
  provider: ^4.0.5
  flutter_mobx: ^1.1.0
  introduction_screen: ^1.0.8
  shared_preferences: ^0.5.6+3
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.0.0
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  stripe_payment: ^1.0.7
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.3
  flutter_credit_card: ^0.1.3
  json_annotation: ^3.0.1
  barcode_scan: ^3.0.1
  qr_flutter: ^3.1.0
  numberpicker: ^1.2.0
  collection: ^1.14.12
  css_colors:
  firebase_storage: ^3.1.5
  progress_dialog: ^1.2.2
  flutter_sticky_header: ^0.4.2
  badges: ^1.1.0
  auto_size_text: ^2.1.0
  dio: ^3.0.9
  http: ^0.12.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^1.0.3
  path_provider: ^1.6.5
  json_serializable: ^3.3.0

**Comment by pmdatgithub** [comment]
> I seem to solve this problem, was with a dependency that did not have web support.

Could you please elaborate?

**Comment by muzzah** [comment]
@pmdatgithub I am using moor package for storing data and without following some steps, it does not support web. I completed those steps to enable web support (conditional importing of certain files) and the error went away and web compilation worked again

**Comment by piyushbhatia892** [comment]
flutter run -d web-server --verbose 
This command does help by telling you exactly where the error is in project and yes the error is related to web when you use certain package in your project which does not have web support.

**Comment by Garrison88** [comment]
> @pmdatgithub I am using moor package for storing data and without following some steps, it does not support web. I completed those steps to enable web support (conditional importing of certain files) and the error went away and web compilation worked again

@muzzah Could you specify what changes you made? I'm having the same issue and following the guide provided by the creator of Moor isn't sufficient. Do you mind sharing the changes you made in order to make Flutter web work with Moor?

**Comment by muzzah** [comment]
@Garrison88 Have a look at https://moor.simonbinder.eu/web/
You can find an example project there. The magic is when creating the database object. You have to conditional import the database type.

**Comment by Garrison88** [comment]
I've followed the steps in that article and also looked through the sample code to fix my issue, but I'm still getting the same error. I hope we can see a more helpful error message soon

**Comment by Garrison88** [comment]
**Update**
I was able to solve my issue by removing all the unused imports in my project

**Comment by asknishant** [comment]
I just run the command
-> flutter pub get

if you are connected to any github repositories then run above command after doing git stash.

**Comment by darshankawar** [comment]
I tried to replicate this using latest master version and added a community plugin which doesn't have web support, ex: https://pub.dev/packages/moor2csv/install, ran `flutter run -d web-server` and also `flutter run -d chrome` with which I didn't get the originally reported error or a similar one.

Based on this, I am going ahead and closing this as not replicable. If anybody disagrees, write in comments and I'll reopen it.
