### ISSUE TITLE
Correctly dispose a camera controller/preview

### ISSUE THREAD

**Issue by panmari** [flutter/flutter#58187]
## Steps to Reproduce

Create an app containing the sample code from the camera plugin:

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';

List<CameraDescription> cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(CameraApp());
}

class CameraApp extends StatefulWidget {
  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  CameraController controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(cameras[0], ResolutionPreset.medium);
    controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller.value.isInitialized) {
      return Container();
    }
    return AspectRatio(
        aspectRatio:
        controller.value.aspectRatio,
        child: CameraPreview(controller));
  }
}
```

1. Open the app
2. Tap *back* on android
3. The app crashes with a fatal exception: `java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.`

**Expected results:** 

The app should close successfully. I also have a more complex example where I would want to return to another screen.

**Actual results:** 

On tapping the back button, the app crashes with

```
I/CameraManagerGlobal(25558): Connecting to camera service
W/Gralloc3(25558): allocator 3.x is not supported
D/AndroidRuntime(25558): Shutting down VM
E/AndroidRuntime(25558): FATAL EXCEPTION: main
E/AndroidRuntime(25558): Process: com.example.cam_example, PID: 25558
E/AndroidRuntime(25558): java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
E/AndroidRuntime(25558): 	at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:222)
E/AndroidRuntime(25558): 	at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:543)
E/AndroidRuntime(25558): 	at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:295)
E/AndroidRuntime(25558): 	at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:35)
E/AndroidRuntime(25558): 	at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:141)
E/AndroidRuntime(25558): 	at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:211)
E/AndroidRuntime(25558): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(25558): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(25558): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(25558): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25558): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(25558): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process (25558): Sending signal. PID: 25558 SIG: 9
Lost connection to device.
Exited (sigterm)
```

```
$ flutter analyze
Analyzing cam_example...                                                
No issues found! (ran in 2.7s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.1 at /home/mazzzy/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/mazzzy/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 15)
    • IntelliJ at /opt/idea-IC-143.382.35
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] Connected device (1 available)
    • Pixel 3a • 9CHAY1PMEX • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

</details>

**Comment by iapicca** [comment]
Hi @panmari 
I tested the [sample app](https://github.com/flutter/plugins/blob/master/packages/camera/example/lib/main.dart)
with the latest master
<details>
  <summary>logs</summary>

```bash
[   +2 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:50774/vdAwsbSk6fA=/
[+5161 ms] W/s.cameraexampl( 3021): Suspending all threads took: 297.824ms
[ +654 ms] W/ActivityThread( 3021): handleWindowVisibility: no activity for token android.os.BinderProxy@e84a523
[+13345 ms] I/Choreographer( 3021): Skipped 39 frames!  The application may be doing too much work on its main thread.
[   +7 ms] W/Gralloc3( 3021): allocator 3.x is not supported
[+15243 ms] W/ActivityThread( 3021): handleWindowVisibility: no activity for token android.os.BinderProxy@8bc3f14
[+7551 ms] I/Choreographer( 3021): Skipped 70 frames!  The application may be doing too much work on its main thread.
[+4697 ms] I/Choreographer( 3021): Skipped 141 frames!  The application may be doing too much work on its main thread.
[ +146 ms] W/FlutterJNI( 3021): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel:
flutter.io/cameraPlugin/cameraEvents0. Response ID: 0
[ +911 ms] W/ActivityThread( 3021): handleWindowVisibility: no activity for token android.os.BinderProxy@61967ae
[ +116 ms] W/System  ( 3021): A resource failed to call release.
[ +215 ms] W/System  ( 3021): A resource failed to call release.
[+5881 ms] Service protocol connection closed.
[   +3 ms] Lost connection to device.
[   +7 ms] executing: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +8 ms] Exit code 0 from: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:50774 tcp:40123
[   +1 ms] executing: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --remove tcp:50774
[  +12 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/io.flutter.plugins.cameraexample/code_cache/exampleWAPXGU/example/)
[ +263 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] executing: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +8 ms] Exit code 0 from: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +2 ms] "flutter run" took 108,965ms.
[ +265 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +5 ms] Shutdown hooks complete
```

</details>

and latest stable

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.192, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-2.0.pre.192 at /Users/nevercode/development/flutter_master
    • Framework revision 9b3634f422 (7 hours ago), 2020-05-29 00:58:01 -0400
    • Engine revision c5d012900f
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>


<details>
  <summary>logs</summary>

```bash
[   +1 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:50534/CXP8bW3Kp4k=/
[+45988 ms] W/ActivityThread( 2375): handleWindowVisibility: no activity for token android.os.BinderProxy@aaeee52
[+3462 ms] W/ActivityThread( 2375): handleWindowVisibility: no activity for token android.os.BinderProxy@71f5b50
[+4881 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/io.flutter.plugins.cameraexample/code_cache/exampleFNBRDC/example/)
[   +1 ms] Sending to VM service: _deleteDevFS({fsName: example})
[  +69 ms] Result: {type: Success}
[        ] DevFS: Deleted filesystem on the device (file:///data/user/0/io.flutter.plugins.cameraexample/code_cache/exampleFNBRDC/example/)
[ +116 ms] Sending to VM service: ext.flutter.exit({isolateId: isolates/1865087444137775})
[  +20 ms] Result: {type: Sentinel, kind: Collected, valueAsString: <collected>}
[   +1 ms] Application finished.
[   +4 ms] executing: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +9 ms] Exit code 0 from: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:50534 tcp:43377
[   +1 ms] executing: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --remove tcp:50534
[  +12 ms] executing: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +8 ms] Exit code 0 from: /Users/nevercode/Library/Android/sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +2 ms] "flutter run" took 129,122ms.
```

</details>


<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.2 at /Users/nevercode/development/flutter
    • Framework revision 5f21edf8b6 (16 hours ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Pixel 3a • 965AY0WP5C • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

and I cannot reproduce the behaviour you are describing.

Can you please provide your `flutter run --verbose`
and your `pubspec.yaml`
Thank you

**Comment by panmari** [comment]
I compared the handling of the example you gave with the example I gave (from the official documentation). Looks like setting things up with a `WidgetsBindingObserver` makes all the difference. Thanks for pointing me there! Here's the code that doesn't crash anymore:

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';

List<CameraDescription> cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(CameraApp());
}

class CameraApp extends StatefulWidget {
  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> with WidgetsBindingObserver {
  CameraController controller;

  @override
  void initState() {
    super.initState();
    initCam();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // App state changed before we got the chance to initialize.
    if (controller == null || !controller.value.isInitialized) {
      return;
    }
    if (state == AppLifecycleState.inactive) {
      controller?.dispose();
    } else if (state == AppLifecycleState.resumed) {
      if (controller != null) {
        initCam();
        if (mounted) {
          setState(() {});
        }
      }
    }
  }

  void initCam() {
    controller?.dispose();

    controller = CameraController(cameras[0], ResolutionPreset.medium);

    // If the controller is updated then update the UI.
    controller.addListener(() {
      if (mounted) setState(() {});
      if (controller.value.hasError) {
        print('Camera error ${controller.value.errorDescription}');
      }
    });

    controller.initialize();
  }

  @override
  Widget build(BuildContext context) {
    if (controller == null || !controller.value.isInitialized) {
      return Container();
    }
    return AspectRatio(
        aspectRatio: controller.value.aspectRatio,
        child: CameraPreview(controller));
  }
}
```
