### ISSUE TITLE
Flutter build apk failed

### ISSUE THREAD

**Issue by saeedhpro** [flutter/flutter#58196]
this is my log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

ProcessException: ProcessException: Permission denied
  Command: /home/saeedhpro/other/softwares/flutter/.pub-cache/hosted/pub.dartlang.org/device_id-0.2.0/android/gradlew -I=/home/saeedhpro/other/softwares/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/home/saeedhpro/other/softwares/flutter -Poutput-dir=/home/saeedhpro/works/projects/arabzade/send_tracking_data/send_tracking_app/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    [32m•[39m Flutter version 1.12.13+hotfix.9 at /home/saeedhpro/other/softwares/flutter
    [32m•[39m Framework revision f139b11009 (8 weeks ago), 2020-03-30 13:57:30 -0700
    [32m•[39m Engine revision af51afceb8
    [32m•[39m Dart version 2.7.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/saeedhpro/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /home/saeedhpro/Android/Sdk
    [32m•[39m Java binary at: /softwares/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /softwares/android-studio
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m Proxy Configuration
    [32m•[39m HTTP_PROXY is set
    [32m•[39m NO_PROXY is .github.com,.getcomposer.org,.laravel.com,.packagist.org,.npmjs.org,localhost,127.0.0.1,.yarnpkg.com,https://production.cloudflare.docker.com
    [32m•[39m NO_PROXY contains 127.0.0.1
    [32m•[39m NO_PROXY contains localhost

[32m[✓][39m Connected device (2 available)
    [32m•[39m SM J701F          • 5200acc94e1cb43d    • android-arm • Android 9 (API 28)
    [32m•[39m Samsung Galaxy S6 • 192.168.58.101:5555 • android-x86 • Android 7.1.1 (API 25)

[32m•[39m No issues found!
```

**Comment by TahaTesser** [comment]
Related to  https://github.com/flutter/flutter/issues/47038 https://github.com/flutter/flutter/issues/50880
