### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command: C:\Users\BAYOH\Downloads\chat_app-master\chat_app-master\android\gradlew.bat, OS error code: 1

### ISSUE THREAD

**Issue by Bayohturay** [flutter/flutter#58198]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s Command: C:\Users\BAYOH\Downloads\chat_app-master\chat_app-master\android\gradlew.bat, OS error code: 1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      flavorUndefinedHandler.<anonymous closure> (package:flutter_tools/src/android/gradle_errors.dart:277:57)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:73)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#12     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#13     _rootRunUnary (dart:async/zone.dart:1192:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#20     _rootRun (dart:async/zone.dart:1184:13)
#21     _CustomZone.run (dart:async/zone.dart:1077:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
```
```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18362.175], locale en-US)
    • Flutter version 1.18.0-11.1.pre at C:\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Framework revision 2738a1148b (2 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\BAYOH\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\BAYOH\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
### Plugins
flutter_native_image-884d50a6cd4b88d78a849dc7ccd70eaf23fd0cab
camera-0.5.7+4
cloud_firestore-0.12.11
emoji_picker-0.0.3
firebase_auth-0.16.0
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_database-3.1.5
firebase_storage-3.1.5
flutter_facebook_login-1.2.0
flutter_plugin_android_lifecycle-1.0.7
fluttertoast-4.0.1
image_picker-0.6.6+1
onesignal-1.1.0
path_provider-1.6.7
path_provider_macos-0.0.4+2
permission_handler-4.4.0+hotfix.4
shared_preferences-0.5.7+1
shared_preferences_macos-0.0.1+8
shared_preferences_web-0.1.2+5
sqflite-1.3.0+1
url_launcher-5.4.5
url_launcher_macos-0.0.1+5
url_launcher_web-0.1.1+4

**Comment by lualbertovargas** [comment]
Hello, with all due respect I try not to give negative comments, but if I do give feedback, the user @darshankawar is only dedicated to closing topics "responding" subjectively, "since data on the problem is missing" or "with possible causes". If we want to collaborate, at least if we don't know the answer, leave the topic open so that someone can help or be taken into account.
Entering and seeing your user is like knowing that the problem will not have a solution directly in that forum

**Comment by bkonyi** [comment]
Closing this issue as stale. Please reopen if this is still a problem.
