### ISSUE TITLE
Could not determine the dependencies of task ':app:compileFlutterBuildDebug'

### ISSUE THREAD

**Issue by ElHassaniWalid** [flutter/flutter#58274]
Hello,
Am using a 'hello world' application, when I tried to run it, i got this error : 
main.dart code : 
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Container(
      color: Colors.red,
    );
  }
}
```

flutter run -v
```
D:\walidTest\Flutter\TestApp> flutter run -v
[  +33 ms] executing: [c:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +172 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 5f21edf8b66e31a39133177319414395cc5b5f48
[        ] executing: [c:\src\flutter/] git tag --contains HEAD
[ +357 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.17.2
[  +12 ms] executing: [c:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +151 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [c:\src\flutter/] git ls-remote --get-url origin
[ +101 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +204 ms] executing: [c:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +115 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +89 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +20 ms] executing: C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +164 ms] List of devices attached
           WCR7N18B22002507       device product:CLT-L29 model:CLT_L29 device:HWCLT transport_id:2
[  +17 ms] C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe -s WCR7N18B22002507 shell getprop
[ +150 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +20 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +666 ms] Generating D:\walidTest\Flutter\TestApp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +86 ms] ro.hardware = kirin970
[   +4 ms] ro.build.characteristics = default
[ +183 ms] Launching lib\main.dart on CLT L29 in debug mode...
[  +20 ms] c:\src\flutter\bin\cache\dart-sdk\bin\dart.exe c:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
c:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\hp\AppData\Local\Temp\flutter_tool.b1eb82ca-a1ef-11ea-b44e-70f395a29270\app.dill --packages D:\walidTest\Flutter\TestApp\.packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[  +47 ms] executing: C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe -s WCR7N18B22002507 shell -x logcat -v time -t 1
[ +260 ms] Exit code 0 from: C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe -s WCR7N18B22002507 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           05-29 21:02:29.939 V/AudioManager(24779): getStreamVolume  streamType: 3 volume: 4
[  +58 ms] <- compile package:TestApp/main.dart
[  +61 ms] executing: C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[ +197 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe
[  +14 ms] executing: C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[ +194 ms] Building APK
[  +91 ms] Running Gradle task 'assembleDebug'...
[  +14 ms] gradle.properties already sets `android.enableR8`
[  +11 ms] Using gradle from D:\walidTest\Flutter\TestApp\android\gradlew.bat.
[   +3 ms] D:\walidTest\Flutter\TestApp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +26 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +425 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +9 ms] executing: [D:\walidTest\Flutter\TestApp\android/] D:\walidTest\Flutter\TestApp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=D:\walidTest\Flutter\TestApp\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2837 ms] FAILURE: Build failed with an exception.
[  +31 ms] * Where:
[   +2 ms] Script 'c:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 962
[  +28 ms] * What went wrong:
[  +16 ms] Could not determine the dependencies of task ':app:compileFlutterBuildDebug'.
[   +7 ms] > 1
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 2s
[ +359 ms] Running Gradle task 'assembleDebug'... (completed in 3,8s)
[+7968 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 14 256ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

flutter doctor -v : 
```
D:\walidTest\Flutter\TestApp> flutter doctor -v
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [version 6.1.7601], locale fr-FR)
    • Flutter version 1.17.2 at c:\src\flutter
    • Framework revision 5f21edf8b6 (25 hours ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\hp\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\hp\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\hp\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • CLT L29 • WCR7N18B22002507 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by ElHassaniWalid** [comment]
Hello, 
solution is running this command  : 
flutter clean
