### ISSUE TITLE
Flutter.podspec being changed and badly formatted automatically by flutter run command.

### ISSUE THREAD

**Issue by mcruzie** [flutter/flutter#58283]
## Context
Flutter is weirdly changing the file `Flutter.podspec` during the build process. It is applying a template which is badly formatted and as a result, the compilation process gets stuck.
The issue is limited to the parameters `s.homepage` and `s.source` and once I enclose the string using `'`, things come back to normality.

This error became evident after adding the dependency: `shared_preferences: ^0.5.7+3`

## Steps to Reproduce
1. Run `flutter run`.
2. The file `Flutter.podspec` will get changed automatically badly formatted.

```
#
# NOTE: This podspec is NOT to be published. It is only used as a local source!
#

Pod::Spec.new do |s|
  s.name             = 'Flutter'
  s.version          = '1.0.0'
  s.summary          = 'High-performance, high-fidelity mobile apps.'
  s.description      = <<-DESC
Flutter provides an easy and productive way to build and deploy high-performance mobile apps for Android and iOS.
                       DESC
  s.homepage         = 'https:
  s.license          = { :type => 'MIT' }
  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :git => 'https:
  s.ios.deployment_target = '8.0'
  s.vendored_frameworks = 'Flutter.framework'
end
```

3. The following error will be shown as output.
```
devuser@codermac ios % flutter run
Changing current working directory to: XXX
Launching lib/main.dart on iPhone 11 Pro in debug mode...
 
Running pod install...                                              0.9s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    [!] Failed to load 'Flutter' podspec: 
    [!] Invalid `Flutter.podspec` file: syntax error, unexpected tFLOAT, expecting '}'
    ... s.ios.deployment_target = '8.0'
    ...                            ^~~
    /Users/devuser/dev/myapp/ios/Flutter/Flutter.podspec:17: syntax error, unexpected tCONSTANT, expecting end-of-input
    ....vendored_frameworks = 'Flutter.framework'
    ...                        ^~~~~~~.

     #  from /Users/devuser/dev/myapp/ios/Flutter/Flutter.podspec:16
     #  -------------------------------------------
     #    s.source           = { :git => 'https:
     >    s.ios.deployment_target = '8.0'
     #    s.vendored_frameworks = 'Flutter.framework'
     #  -------------------------------------------

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/abstract_external_source.rb:175:in `rescue in store_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/abstract_external_source.rb:161:in `store_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:980:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:959:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:958:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:958:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:957:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this
    target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro.
```

## My flutter analyze output
```
devuser@codermac ios % flutter analyze
Analyzing ios...                                                        
No issues found! (ran in 0.9s)
```

## My flutter doctor output

```
devuser@codermac ios % flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.1 at /Users/devuser/dev/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/devuser/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 11 Pro • 46361B04-5DFB-4651-BCAA-70770B380C92 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @mcruzie 
Not able to reproduce this on latest `stable` channel, can you please upgrade to latest `stable` and try again with a new project?

Here it is after running ` shared_preferences: ^0.5.7+3`
```
#
# NOTE: This podspec is NOT to be published. It is only used as a local source!
#

Pod::Spec.new do |s|
  s.name             = 'Flutter'
  s.version          = '1.0.0'
  s.summary          = 'High-performance, high-fidelity mobile apps.'
  s.description      = <<-DESC
Flutter provides an easy and productive way to build and deploy high-performance mobile apps for Android and iOS.
                       DESC
  s.homepage         = 'https://flutter.io'
  s.license          = { :type => 'MIT' }
  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :git => 'https://github.com/flutter/engine', :tag => s.version.to_s }
  s.ios.deployment_target = '8.0'
  s.vendored_frameworks = 'Flutter.framework'
end

```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.17.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 5f21edf8b6 (4 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • SM M305F  • 32003c30dc19668f                     • android-arm64 • Android 10 (API 29)
    • iPhone 11 • 0EC80516-8F99-4A0C-89ED-2273579862F9 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
``` 

</details>

**Comment by mcruzie** [comment]
Hi, @TahaTesser. Thanks for your reply.
I confirm I followed your instructions and I keep experiencing the same issue. The Podspec is being arbitrarily changed.

Here are steps the I took.

1. Flutter upgrade

```
Upgrading Flutter from /Users/devuser/dev/flutter...
Downloading Dart SDK from Flutter engine b851c718295a896918dc93cb1ff14f2f895a1b90...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  212M    0 10674    0     0  14119      0  4:22:58 --:--:--  4:22:58 14100
  1  212M    1 2574k    0     0  1927k      0  0:01:52  0:00:01  0:01:51 1925k
  6  212M    6 14.8M    0     0  6444k      0  0:00:33  0:00:02  0:00:31 6441k
 15  212M   15 32.8M    0     0   9.8M      0  0:00:21  0:00:03  0:00:18  9.8M
 26  212M   26 55.9M    0     0  12.8M      0  0:00:16  0:00:04  0:00:12 12.8M
 36  212M   36 77.6M    0     0  14.5M      0  0:00:14  0:00:05  0:00:09 16.9M
 47  212M   47  100M    0     0  15.8M      0  0:00:13  0:00:06  0:00:07 19.5M
 58  212M   58  124M    0     0  16.9M      0  0:00:12  0:00:07  0:00:05 22.0M
 68  212M   68  146M    0     0  17.5M      0  0:00:12  0:00:08  0:00:04 22.7M
 79  212M   79  168M    0     0  17.9M      0  0:00:11  0:00:09  0:00:02 22.2M
 89  212M   89  190M    0     0  18.4M      0  0:00:11  0:00:10  0:00:01 22.5M
 99  212M   99  211M    0     0  18.5M      0  0:00:11  0:00:11 --:--:-- 21.8M
100  212M  100  212M    0     0  18.3M      0  0:00:11  0:00:11 --:--:-- 20.6M
Building flutter tool...

Upgrading engine...
Downloading Android Maven dependencies...                          99.7s
Downloading android-arm-profile/darwin-x64 tools...                 1.0s
Downloading android-arm-release/darwin-x64 tools...                 1.1s
Downloading android-arm64-profile/darwin-x64 tools...               1.4s
Downloading android-arm64-release/darwin-x64 tools...               0.9s
Downloading android-x64-profile/darwin-x64 tools...                 0.7s
Downloading android-x64-release/darwin-x64 tools...                 0.9s
Downloading android-x86 tools...                                    2.3s
Downloading android-x64 tools...                                    1.8s
Downloading android-arm tools...                                    1.2s
Downloading android-arm-profile tools...                            1.0s
Downloading android-arm-release tools...                            0.4s
Downloading android-arm64 tools...                                  1.2s
Downloading android-arm64-profile tools...                          0.7s
Downloading android-arm64-release tools...                          1.2s
Downloading android-x64-profile tools...                            1.2s
Downloading android-x64-release tools...                            0.9s
Downloading android-x86-jit-release tools...                        0.8s
Downloading ios tools...                                            2.7s
Downloading ios-profile tools...                                    2.0s
Downloading ios-release tools...                                    8.7s
Downloading package sky_engine...                                   0.3s
Downloading flutter_patched_sdk tools...                            1.3s
Downloading flutter_patched_sdk_product tools...                    1.1s
Downloading darwin-x64 tools...                                     2.0s
Downloading darwin-x64/font-subset tools...                         1.1s

Flutter 1.17.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f21edf8b6 (5 days ago) • 2020-05-28 12:44:12 -0700
Engine • revision b851c71829
Tools • Dart 2.8.3

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

``` 

2. Flutter clean

```
Cleaning Xcode workspace...                                         8.6s
Deleting build...                                                  320ms
Deleting .dart_tool...                                               3ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting App.framework...                                            6ms
```

3. Flutter Run

```
Launching lib/main.dart on iPhone 11 Pro in debug mode...
 
Running pod install...                                              1.6s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Firebase
      - Flutter
      - shared_preferences
      - shared_preferences_macos
      - shared_preferences_web

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    [!] Failed to load 'Flutter' podspec: 
    [!] Invalid `Flutter.podspec` file: syntax error, unexpected tCONSTANT, expecting end
    ...ense          = { :type => 'MIT' }
    ...                            ^~~
    /Users/devuser/dev/myapp/ios/Flutter/Flutter.podspec:14: syntax error, unexpected tCONSTANT, expecting end-of-input
    ...s.author           = { 'Flutter Dev Team' => 'flutter-dev@go...
    ...                        ^~~~~~~.

     #  from /Users/devuser/dev/myapp/ios/Flutter/Flutter.podspec:13
     #  -------------------------------------------
     #    s.homepage         = 'https:
     >    s.license          = { :type => 'MIT' }
     #    s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
     #  -------------------------------------------

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/abstract_external_source.rb:175:in `rescue in
    store_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/abstract_external_source.rb:161:in `store_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:980:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:959:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:958:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:958:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:957:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a
    platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro.

```

**Comment by jmagman** [comment]
That is extremely strange.  That file is coming from https://storage.googleapis.com/flutter_infra/flutter/b851c718295a896918dc93cb1ff14f2f895a1b90/ios-release/artifacts.zip
And the podspec is
```
#
# NOTE: This podspec is NOT to be published. It is only used as a local source!
#

Pod::Spec.new do |s|
  s.name             = 'Flutter'
  s.version          = '1.0.0'
  s.summary          = 'High-performance, high-fidelity mobile apps.'
  s.description      = <<-DESC
Flutter provides an easy and productive way to build and deploy high-performance mobile apps for Android and iOS.
                       DESC
  s.homepage         = 'https://flutter.io'
  s.license          = { :type => 'MIT' }
  s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source           = { :git => 'https://github.com/flutter/engine', :tag => s.version.to_s }
  s.ios.deployment_target = '8.0'
  s.vendored_frameworks = 'Flutter.framework'
end

```
You can download it and unzip it and see the full URLs like 'https://flutter.io'.

That should be copied to `ios/Flutter/Flutter.podspec` when you `flutter run`, but that would happen after the `pod install` step, which is failing.

This is the only report we have of this.  If you first delete `ios/Flutter/Flutter.podspec` then try again, does it work?  Or try it with a new project as @TahaTesser suggested?

**Comment by mcruzie** [comment]
Hi. When using a fresh project, this issue is not experienced however it does not include some dependencies either.

My project has just a few dependencies, being:
  shared_preferences: ^0.5.7+3
  http: ^0.12.1

The issue aforementioned started to happen right after the addition of the shared_preferences package. I'm happy to help you with further investigations.
