### ISSUE TITLE
MissingPluginException(No implementation found for method on channel)

### ISSUE THREAD

**Issue by toshi0383** [flutter/flutter#58295]
I know there are plenty of issues with same title, but here is what I've got with slightly different scenario. (I guess)
I'm trying to call native from dart, from the `FlutterActivity` **which is launched from Native code**.
I couldn't find the right example for this.
This MethodChannel works fine on iOS.

### MainActivity.kt
```kotlin
class MainActivity : FlutterActivity() {
    companion object {
        private const val CHANNEL = "tutorial_channel"
        private const val METHOD_GET_LIST = "tutorialDidFinish"
    }

    private lateinit var channel: MethodChannel

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        // did not make any difference if engine configuration is here or in onCreate
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val flutterEngine = getFlutterEngine()
        if (flutterEngine != null) {
            GeneratedPluginRegistrant.registerWith(flutterEngine)
        }

        if (flutterEngine != null) {
            channel = MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
        }
        channel.setMethodCallHandler { methodCall: MethodCall, result: MethodChannel.Result ->
            print("tutorial finished!")
            result.success(null);
        }

        fab.setOnClickListener { view ->
            startActivity(FlutterActivity.createDefaultIntent(this));
        }
    }
```

### Flutter code
```dart

    final channel = MethodChannel('tutorial_channel');

    ...
          channel.invokeMethod('tutorialDidFinish');
      ...
```

## Logs

```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method tutorialDidFinish on channel tutorial_channel)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #2      BottomButton.build.<anonymous closure> (package:tutorial_module/bottom_button.dart:33:19)
    #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
    #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
    #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
    #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
    #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
    #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
    #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
    #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
    #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
    #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
    #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
    #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
    #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #20     _rootRunUnary (dart:async/zone.dart:1196:13)
    #21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
    #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
    #23     _invoke1 (dart:ui/hooks.dart:275:10)
    #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

## `flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale ja-JP)
    • Flutter version 1.17.1 at /Users/suzukitoshihiro/dev/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/suzukitoshihiro/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/AndroidStudio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/AndroidStudio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by toshi0383** [comment]
Resolved by using `FlutterEngineCache`. Closing. Thank you!

```kotlin
class MainActivity : FlutterActivity() {
    companion object {
        private const val CHANNEL = "tutorial_channel"
        private const val METHOD_GET_LIST = "tutorialDidFinish"
        private const val ENGINE_ID = "tutorial_engine"
    }

    private lateinit var channel: MethodChannel

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)

        FlutterEngineCache.getInstance().put(ENGINE_ID, flutterEngine)

        channel = MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
        channel.setMethodCallHandler { methodCall: MethodCall, result: MethodChannel.Result ->
            result.success(null);
        }

    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        fab.setOnClickListener { view ->

            flutterEngine?.let {
                val intent = FlutterActivity.withCachedEngine(ENGINE_ID).build(this)
                startActivity(intent);
            }
        }
    }
```

**Comment by yinzelin627** [comment]
I did not solve it in your way。
