### ISSUE TITLE
HttpException: Unexpected response (unsolicited response without request) - related to DNS Blocking software

### ISSUE THREAD

**Issue by alenofx** [flutter/flutter#58325]
Testing Flutter on Arch Linux this error happens every time a new application (generated by "flutter create") is executed for the second time, or after a second "hot reload".

The only "temporary fix" found is to delete the "~/.gradle" folder, but this cause a redownload of the gradle dist bundle at the next application run.

## command

flutter run -v

## exception

HttpException: HttpException: Unexpected response (unsolicited response without request).

```
#0      new _HttpClientConnection.<anonymous closure> (dart:_http/http_impl.dart:1704:9)
#1      _rootRunUnary (dart:async/zone.dart:1192:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#7      _StreamController._add (dart:async/stream_controller.dart:655:7)
#8      _StreamController.add (dart:async/stream_controller.dart:597:5)
#9      _HttpParser._headersEnd (dart:_http/http_parser.dart:413:17)
#10     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#11     _HttpParser._parse (dart:_http/http_parser.dart:328:7)
#12     _HttpParser._onData (dart:_http/http_parser.dart:850:5)
#13     _rootRunUnary (dart:async/zone.dart:1192:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#18     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#19     _StreamController._add (dart:async/stream_controller.dart:655:7)
#20     _StreamController.add (dart:async/stream_controller.dart:597:5)
#21     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#22     _rootRunUnary (dart:async/zone.dart:1192:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#28     _StreamController._add (dart:async/stream_controller.dart:655:7)
#29     _StreamController.add (dart:async/stream_controller.dart:597:5)
#30     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1018:19)
#31     _rootRun (dart:async/zone.dart:1180:38)
#32     _CustomZone.run (dart:async/zone.dart:1077:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#35     _rootRun (dart:async/zone.dart:1184:13)
#36     _CustomZone.run (dart:async/zone.dart:1077:19)
#37     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
#38     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#39     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#40     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.2 at /home/alenofx/Applications/flutter
    • Framework revision 5f21edf8b6 (2 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/alenofx/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/alenofx/Applications/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/alenofx/Applications/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by cbreezier** [comment]
I have the same symptom, running on Mac. Actually, I even observe the same error when simply running `flutter doctor -v`:

Here is the exact output I get (reliably):
```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.3 19D76 darwin-x64, locale en-AU)
    • Flutter version 2.0.4 at /Users/lhuang/flutter
    • Framework revision b1395592de (4 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lhuang/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    ! Xcode 11.7.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7223.99
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

⣽                                                                                                                                                                                                                                                     ⣷Oops; flutter has exited unexpectedly: "HttpException: Unexpected response (unsolicited response without request).".
⣾                                                                                                                                                                                                                                                     ⡿Oops; flutter has exited unexpectedly: "HttpException: Unexpected response (unsolicited response without request).".
⣟                                                                                                                                                                                                                                                     [✓] Connected device (2 available)
    • Pixel 3 (mobile) • 8BQX1DZHY • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome    • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
                                                                                                                                                                                                                                                      ⣾

                                                                                                                                                                                                                                                      ⡿Oops; flutter has exited unexpectedly: "HttpException: Unexpected response (unsolicited response without request).".
⣟Oops; flutter has exited unexpectedly: "HttpException: Unexpected response (unsolicited response without request).".
⣻Oops; flutter has exited unexpectedly: "HttpException: Unexpected response (unsolicited response without request).".
⣽Oops; flutter has exited unexpectedly: "HttpException: Unexpected response (unsolicited response without request).".
A crash report has been written to /Users/lhuang/wbs/elumen_mobile/flutter_35.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+HttpException%3A+Unexpected+response+%28unsolicited+response+without+request%29.

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
Oops; flutter has exited unexpectedly: "HttpException: Unexpected response (unsolicited response without request).".
A crash report has been written to /Users/lhuang/wbs/elumen_mobile/flutter_36.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+HttpException%3A+Unexpected+response+%28unsolicited+response+without+request%29.

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!                                                                                                                                        A crash report has been written to /Users/lhuang/wbs/elumen_mobile/flutter_37.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+HttpException%3A+Unexpected+response+%28unsolicited+response+without+request%29.

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!                                                                                                                                        ⣷https://git.io/J3IdK
                                                                                                                                                                                                                                                      ⣽https://git.io/J3IdK
```

> The only "temporary fix" found is to delete the "~/.gradle" folder, but this cause a redownload of the gradle dist bundle at the next application run.

I also found this workaround to be effective, but in a limited fashion. I don't really understand the pattern, but here's what I observe:
1. `flutter run` -> error
2. `rm -r ~/.gradle`
3. `flutter doctor -v` -> error
4. `flutter run` -> okay
5. `flutter run` -> okay
6. `flutter run` -> error

**Comment by cbreezier** [comment]
I had a think about what was special about my setup such that it would produce an error that seemed to be obscure enough that not many other people were seeing the same problem.

I realised that I had set up DNS-based ad-blocking at my router. Specifically, I have been using Diversion on my ASUS Merlin router. https://diversion.ch/

I disabled that, and I seem to be able to use Flutter more stably now. Still not conclusive, but this may have been the root cause for me.

**Comment by KMDgit** [comment]
Here is how I fixed this issue. 

Delete all software that restrict content on your laptop (Qstudio,...). It's an issue with DNS blocking.

**Comment by brianquinlan** [comment]
This is probably not a Dart issue. It looks like gradle is attempting to make a network request request and it is being blocked by @alenofx's ad blocker.
