### ISSUE TITLE
ADB issue while trying to run flutter doctor and run an app

### ISSUE THREAD

**Issue by adityavrao** [flutter/flutter#58331]
I am getting an issue while trying to run the 

Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: C:\Users\hp\AppData\Local\Android\sdk\platform-tools\adb.exe

This issue arrised from the time I updated the flutter plugin ....and not able to resolve in any way..
Please help if someone have any idea to solve it.

Thanks in advance

**Comment by iapicca** [comment]
Hi @adityavrao 
could you please provide the output of
`flutter devices -v` and `flutter doctor -v`
Thank you

**Comment by alexgann** [comment]
Having same issue on Windows 10:
```
PS C:\Users\Alex> flutter doctor -v
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.19.0-4.1.pre at C:\src\flutter
    • Framework revision f994b76974 (11 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Alex\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\Alex\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\Alex\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      C:\Users\Alex\AppData\Local\Android\Sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:64:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:340:60)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:330:12)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:165:20)
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:957:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1190:13)
      #8      _CustomZone.run (dart:async/zone.dart:1093:19)
      #9      _runZoned (dart:async/zone.dart:1630:10)
      #10     runZonedGuarded (dart:async/zone.dart:1618:12)
      #11     runZoned (dart:async/zone.dart:1547:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:182:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:281:47)
      #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:47)
      #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:797:18)
      #17     _rootRunUnary (dart:async/zone.dart:1198:47)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #23     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
      #24     _rootRun (dart:async/zone.dart:1190:13)
      #25     _CustomZone.run (dart:async/zone.dart:1093:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 1 category.
```

Using the specified adb path and the underlying command that I believe flutter uses yields:
```
PS C:\Users\Alex> C:\Users\Alex\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
List of devices attached
892X04G5K              device product:blueline model:Pixel_3 device:blueline transport_id:3
```

**Comment by alexgann** [comment]
Extra bit of info:

- In PowerShell flutter doctor fails on devices but adb can run as shown above.
- In CommandPrompt flutter doctor fails, but calling adb returns nothing, no matter what is passed to it.  It is able to be found fine with `where adb`, there is no "command not found" error, but trying to run adb from cmd.exe returns no error or any text whatsoever, just a brief delay and then a new prompt line
- In Git Bash from git for Windows, with nothing else changed above, `flutter doctor` works successfully as does adb, so I've switched to use git-bash for my prompt to move forward.

I'm not sure what is wrong with my cmd.exe that adb won't run in it.  I wonder if @adityavrao has the same results?

**Comment by alexgann** [comment]
I guess no-response closure is tied to original poster @adityavrao.  Update from myself (having experienced the same bug) was that I was able to create a new local user on Windows 10 and using the same C:\windows\system32\cmd.exe executable and adb.exe this returns successfully and `flutter doctor` runs without issue across both Powershell and cmd.

Best I can figure there is some user permission issue/corruption that is causing adb to return empty on my primary Windows user account (though not in powershell, just in cmd.exe).  Really unsure what that could be or how to fix it, but running flutter dev in a separate account works for me as a workaround, and obviously isn't Flutter team's scope to solve if it is some form of specific windows account + cmd.exe + adb.exe issue.  Hopefully if @adityavrao can follow up on this would be interesting to see if their experience is the same as mine.
