### ISSUE TITLE
Camera Issue

### ISSUE THREAD

**Issue by pateltanmay98** [flutter/flutter#58349]
<details>
  <summary>logs</summary>

```bash
  +70 ms] executing: [D:\Flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +224 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +9 ms] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[   +5 ms] executing: [D:\Flutter\flutter/] git tag --contains HEAD
[ +794 ms] Exit code 0 from: git tag --contains HEAD
[   +4 ms] 1.17.1
[  +31 ms] executing: [D:\Flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +119 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] origin/stable
[   +4 ms] executing: [D:\Flutter\flutter/] git ls-remote --get-url origin
[  +99 ms] Exit code 0 from: git ls-remote --get-url origin
[   +4 ms] https://github.com/flutter/flutter.git
[+1125 ms] executing: [D:\Flutter\flutter/] git rev-parse --abbrev-ref HEAD
[ +101 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +4 ms] stable
[ +108 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +18 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] executing: D:\Android\sdk\platform-tools\adb.exe devices -l
[ +132 ms] List of devices attached
                    W8RSNZFMPJMRKBA6       device product:aio_otfp model:Lenovo_K50a40 device:K50a40 transport_id:1
[  +29 ms] D:\Android\sdk\platform-tools\adb.exe -s W8RSNZFMPJMRKBA6 shell getprop
[ +206 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +191 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +14 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +344 ms] Running "flutter pub get" in camera...
[  +18 ms] Using D:\Flutter\flutter\.pub-cache for the pub cache.
[   +8 ms] executing: [D:\ApplicationDevelopment\FlutterDevelopment\camera/]
D:\Flutter\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose get --no-precompile
[ +394 ms] FINE: Pub 2.8.2
[  +21 ms] IO  : Spawning "cmd /c ver" in D:\ApplicationDevelopment\FlutterDevelopment\camera\.
[  +12 ms] IO  : Finished ver. Exit code 0.
[   +5 ms]     | stdout:
[   +5 ms]     | |
[   +4 ms]     | | Microsoft Windows [Version 10.0.10586]
[   +6 ms]     | Nothing output on stderr.
[ +178 ms] MSG : Resolving dependencies...
[ +136 ms] SLVR: fact: camera is 1.0.0+1
[  +34 ms] SLVR: derived: camera
[  +91 ms] SLVR: Version solving took 0:00:00.146009 seconds.
[   +6 ms]     | Tried 1 solutions.
[   +6 ms] FINE: Resolving dependencies finished (0.270s).
[ +105 ms] ERR : Error on line 31, column 3 of pubspec.yaml: A package may not list itself as a dependency.
[  +15 ms]     |    ╷
[   +6 ms]     | 31 │   camera:
[   +5 ms]     |    │   ^^^^^^
[   +4 ms]     |    ╵
[   +4 ms] FINE: Exception type: PubspecException
[  +55 ms] FINE: package:pub/src/pubspec.dart 787:5                 Pubspec._error
[   +8 ms]     | package:pub/src/pubspec.dart 604:9                 Pubspec._parseDependencies.<fn>
[   +9 ms]     | dart:collection                                    MapView.forEach
[  +10 ms]     | package:pub/src/pubspec.dart 600:15                Pubspec._parseDependencies
[   +8 ms]     | package:pub/src/pubspec.dart 164:9                 Pubspec.dependencies
[   +9 ms]     | package:pub/src/solver/package_lister.dart 211:35  PackageLister.incompatibilitiesFor
[  +10 ms]     | ===== asynchronous gap ===========================
[   +7 ms]     | dart:async                                         Future.catchError
[   +9 ms]     | package:pub/src/utils.dart 113:52                  captureErrors.wrappedCallback
[   +6 ms]     | package:stack_trace                                Chain.capture
[   +7 ms]     | package:pub/src/utils.dart 126:11                  captureErrors
[   +6 ms]     | package:pub/src/command_runner.dart 191:13         PubCommandRunner.runCommand
[   +7 ms]     | dart:async                                         _completeOnAsyncReturn
[   +5 ms]     | package:pub/src/command_runner.dart                PubCommandRunner._validatePlatform
[   +8 ms]     | dart:async                                         _completeOnAsyncReturn
[   +5 ms]     | package:pub/src/io.dart                            runProcess.<fn>
[  +95 ms] Running "flutter pub get" in camera... (completed in 1.3s)
[  +10 ms] "flutter run" took 2,707ms.
pub get failed (65;     | package:pub/src/io.dart                            runProcess.<fn>)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:298:7)
#2      _rootRunUnary (dart:async/zone.dart:1192:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

</details>

**Comment by pateltanmay98** [comment]
Please help me

**Comment by iapicca** [comment]
Hi @pateltanmay98 
Can you please provide your `flutter doctor -v`,
and your `pubspec.yaml`.

Please note the error
`[ +105 ms] ERR : Error on line 31, column 3 of pubspec.yaml: A package may not list itself as a dependency.`

Thank you
