### ISSUE TITLE
Camera  plugin  Issue

### ISSUE THREAD

**Issue by jackzhangkun** [flutter/flutter#58351]
```bash
CameraDeviceState: Legacy camera service transitioning to state ERROR

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
        at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
        at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:143)
```

**Comment by iapicca** [comment]
Hi @jackzhangkun 
Can you please provide your `flutter doctor -v`,
your `flutter run  --verbose` 
and your `pubspec.yaml`.
Thank you

**Comment by VladyslavBondarenko** [comment]
@jackzhangkun 
closing since additional information isn't provided
