### ISSUE TITLE
[tool_crash] ProcessException: The process cannot access the file because it is being used by another process.  Command: "C:\Program Files (x86)\Git\cmd\git.EXE" tag --contains HEAD

### ISSUE THREAD

**Issue by KANCybernet** [flutter/flutter#58410]
## Command
```
flutter 
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: ProcessException: The process cannot access the file because it is being used by another process.

  Command: "C:\Program Files (x86)\Git\cmd\git.EXE" tag --contains HEAD
```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:640:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#5      _runGit (package:flutter_tools/src/version.dart:665:23)
#6      GitTagVersion.determine (package:flutter_tools/src/version.dart:755:31)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:59:36)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:133:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:119:23)
#14     flutterVersion (package:flutter_tools/src/globals.dart:77:46)
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:305:25)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#18     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 1.17.1 at C:\Users\MACBOOK\Desktop\flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\MACBOOK\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\MACBOOK\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by christopherfujino** [comment]
@KANCybernet were you by any chance simultaneously doing a git operation in another terminal (such as doing a `git pull`)?

**Comment by KANCybernet** [comment]
> 
> 
> @KANCybernet were you by any chance simultaneously doing a git operation in another terminal (such as doing a `git pull`)?

Yes, i later realized that, though that wasn't the issue i wanted to report.. But its all good now
