### ISSUE TITLE
Queued memory pressure event can crash Binding initialization (from integration_ui_test)

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#58453]
```
stdout: [ +759 ms] flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
2020-06-01T17:10:20.942466: stdout: [   +1 ms] flutter: The following NoSuchMethodError was thrown during a platform message callback:
2020-06-01T17:10:20.943403: stdout: [        ] flutter: The method 'clear' was called on null.
stdout: [        ] flutter: Receiver: null
stdout: [        ] flutter: Tried calling: clear()
stdout: [        ] flutter:
stdout: [        ] flutter: When the exception was thrown, this was the stack:
2020-06-01T17:10:20.944151: stdout: [        ] flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
stdout: [        ] flutter: #1      PaintingBinding.handleMemoryPressure (package:flutter/src/painting/binding.dart:105:16)
stdout: [        ] flutter: #2      WidgetsBinding.handleMemoryPressure (package:flutter/src/widgets/binding.dart:660:11)
2020-06-01T17:10:20.944751: stdout: [        ] flutter: #3      ServicesBinding.handleSystemMessage (package:flutter/src/services/binding.dart:75:9)
stdout: [        ] flutter: #4      PaintingBinding.handleSystemMessage (package:flutter/src/painting/binding.dart:122:17)
2020-06-01T17:10:20.945308: stdout: [        ] flutter: #5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
stdout: [        ] flutter: #6      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:265:33)
stdout: [        ] flutter: #7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:299:13)
2020-06-01T17:10:20.945883: stdout: [        ] flutter: #8      ChannelBuffers.drain (dart:ui/channel_buffers.dart:188:21)
stdout: [        ] flutter: #9      _DefaultBinaryMessenger.setMessageHandler (package:flutter/src/services/binding.dart:298:23)
stdout: [        ] flutter: #10     TestDefaultBinaryMessenger.setMessageHandler (package:flutter_test/src/binding.dart:134:14)
2020-06-01T17:10:20.947071: stdout: [        ] flutter: #11     BasicMessageChannel.setMessageHandler (package:flutter/src/services/platform_channel.dart:73:23)
stdout: [        ] flutter: #12     ServicesBinding.initInstances (package:flutter/src/services/binding.dart:30:27)
2020-06-01T17:10:20.947884: stdout: [        ] flutter: #13     GestureBinding.initInstances (package:flutter/src/gestures/binding.dart:64:11)
stdout: [        ] flutter: #14     PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:21:11)
2020-06-01T17:10:20.949063: stdout: [        ] flutter: #15     SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
stdout: [        ] flutter: #16     RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:30:11)
2020-06-01T17:10:20.949453: stdout: [        ] flutter: #17     WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:255:11)
stdout: [        ] flutter: #18     new BindingBase (package:flutter/src/foundation/binding.dart:57:5)
stdout: [        ] flutter: #19     new __DriverBinding&BindingBase&SchedulerBinding (package:flutter_driver/src/extension/extension.dart)
stdout: [        ] flutter: #20     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding (package:flutter_driver/src/extension/extension.dart)
2020-06-01T17:10:20.949789: stdout: [        ] flutter: #21     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding (package:flutter_driver/src/extension/extension.dart)
2020-06-01T17:10:20.950070: stdout: [        ] flutter: #22     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&PaintingBinding (package:flutter_driver/src/extension/extension.dart)
2020-06-01T17:10:20.950588: stdout: [        ] flutter: #23     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&PaintingBinding&SemanticsBinding (package:flutter_driver/src/extension/extension.dart)
2020-06-01T17:10:20.951097: stdout: [        ] flutter: #24     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter_driver/src/extension/extension.dart)
2020-06-01T17:10:20.951667: stdout: [        ] flutter: #25     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter_driver/src/extension/extension.dart)
2020-06-01T17:10:20.952790: stdout: [        ] flutter: #26     new _DriverBinding (package:flutter_driver/src/extension/extension.dart)
2020-06-01T17:10:20.953166: stdout: [        ] flutter: #27     enableFlutterDriverExtension (package:flutter_driver/src/extension/extension.dart:91:3)
2020-06-01T17:10:20.953449: stdout: [        ] flutter: #28     main (package:integration_ui/keyboard_resize.dart:11:3)
stdout: [        ] flutter: #29     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:247:25)
stdout: [        ] flutter: #34     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:239:5)
2020-06-01T17:10:20.953650: stdout: [        ] flutter: #35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
2020-06-01T17:10:20.953822: stdout: [        ] flutter: (elided 5 frames from class _RawReceivePortImpl and dart:async)

```

**Comment by jonahwilliams** [comment]
The obvious fix seems to be to make `imageCache?.clear()`, but this one is definitely a head scratcher in terms of testing.

**Comment by Hixie** [comment]
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      PaintingBinding.handleMemoryPressure (package:flutter/src/painting/binding.dart:105:16)
#2      WidgetsBinding.handleMemoryPressure (package:flutter/src/widgets/binding.dart:660:11)
#3      ServicesBinding.handleSystemMessage (package:flutter/src/services/binding.dart:75:9)
#4      PaintingBinding.handleSystemMessage (package:flutter/src/painting/binding.dart:122:17)
#5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
#6      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:265:33)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:299:13)
#8      ChannelBuffers.drain (dart:ui/channel_buffers.dart:188:21)
#9      _DefaultBinaryMessenger.setMessageHandler (package:flutter/src/services/binding.dart:298:23)
#10     TestDefaultBinaryMessenger.setMessageHandler (package:flutter_test/src/binding.dart:134:14)
#11     BasicMessageChannel.setMessageHandler (package:flutter/src/services/platform_channel.dart:73:23)
#12     ServicesBinding.initInstances (package:flutter/src/services/binding.dart:30:27)
#13     GestureBinding.initInstances (package:flutter/src/gestures/binding.dart:64:11)
#14     PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:21:11)
#15     SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
#16     RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:30:11)
#17     WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:255:11)
#18     new BindingBase (package:flutter/src/foundation/binding.dart:57:5)
#19     new __DriverBinding&BindingBase&SchedulerBinding (package:flutter_driver/src/extension/extension.dart)
#20     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding (package:flutter_driver/src/extension/extension.dart)
#21     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding (package:flutter_driver/src/extension/extension.dart)
#22     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&PaintingBinding (package:flutter_driver/src/extension/extension.dart)
#23     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&PaintingBinding&SemanticsBinding (package:flutter_driver/src/extension/extension.dart)
#24     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter_driver/src/extension/extension.dart)
#25     new __DriverBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter_driver/src/extension/extension.dart)
#26     new _DriverBinding (package:flutter_driver/src/extension/extension.dart)
#27     enableFlutterDriverExtension (package:flutter_driver/src/extension/extension.dart:91:3)
#28     main (package:integration_ui/keyboard_resize.dart:11:3)
#29     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:247:25)
#34     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:239:5)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
(elided 5 frames from class _RawReceivePortImpl and dart:async)

```
