### ISSUE TITLE
Sentry plugin unhandled exception

### ISSUE THREAD

**Issue by andromeda911** [flutter/flutter#58477]
Hi there! I have a problem with Sentry plugin v3.0.1.
Here is my reporting function:
```
Future<Null> reportError(SentryClient sentry, Object error, StackTrace stackTrace) async {
	print('Caught error: $error');

	print('Reporting to Sentry.io...');

	final PackageInfo info = await PackageInfo.fromPlatform();

	Map<String, dynamic> extra = {};
	if (defaultTargetPlatform == TargetPlatform.android) {
		extra['device_info'] = await DeviceInfoPlugin.channel.invokeMethod('getAndroidDeviceInfo');
	}
	else if (defaultTargetPlatform == TargetPlatform.iOS) {
		extra['device_info'] = await DeviceInfoPlugin.channel.invokeMethod('getIosDeviceInfo');
	}

       Map<String, dynamic> uiValues = {};
       uiValues['locale'] = ui.window.locale.toString();
       uiValues['pixel_ratio'] = ui.window.devicePixelRatio;
       uiValues['default_route'] = ui.window.defaultRouteName;
       uiValues['physical_size'] = [ui.window.physicalSize.width, ui.window.physicalSize.height];
       uiValues['text_scale_factor'] = ui.window.textScaleFactor;
       uiValues['view_insets'] = [ui.window.viewInsets.left, ui.window.viewInsets.top, 
       ui.window.viewInsets.right, ui.window.viewInsets.bottom];


	Map<String, dynamic> memory = {};
	memory['phys_total'] = '${SysInfo.getTotalPhysicalMemory() ~/ MEGABYTE}MB';
	memory['phys_free'] = '${SysInfo.getFreePhysicalMemory() ~/ MEGABYTE}MB';
	memory['virt_total'] = '${SysInfo.getTotalVirtualMemory() ~/ MEGABYTE}MB';
	memory['virt_free'] = '${SysInfo.getFreeVirtualMemory() ~/ MEGABYTE}MB';
	extra['memory'] = memory;

	extra['dart_version'] = Platform.version;

	final Event event = Event(
		loggerName: '',
		exception: error,
		stackTrace: stackTrace,
		extra: extra,
	);


	final SentryResponse response = await sentry.capture(event: event);
	if (response.isSuccessful) {
		print('Success! Event ID: ${response.eventId}');
	} else {
		print('Failed to report to Sentry.io: ${response.error}');
	}

}
```

Map objects with data have element type indications, but I get an exception “from under the plug-in hood” about type mismatch in the plug-in's internal function “mergeAttributes” when my function tries send a report:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'
E/flutter (12662): #0      mergeAttributes.<anonymous closure> 
package:sentry/src/utils.dart:22
E/flutter (12662): #1      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (12662): #2      mergeAttributes 
package:sentry/src/utils.dart:14
E/flutter (12662): #3      mergeAttributes.<anonymous closure> 
package:sentry/src/utils.dart:22
E/flutter (12662): #4      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (12662): #5      mergeAttributes 
package:sentry/src/utils.dart:14
E/flutter (12662): #6      SentryClient.capture 
package:sentry/src/base.dart:171
E/flutter (12662): #7      reportError 
package:myapp/errorReporting.dart:96
E/flutter (12662): <asynchronous suspension>
E/flutter (12662): #8      main.<anonymous closure> 
package:myapp/main.dart:55
E/flutter (12662): #9      _rootRunBinary  (dart:async/zone.dart:1208:13)
E/flutter (12662): #10     _CustomZone.runBinary  (dart:async/zone.dart:1093:19)
E/flutter (12662): #11     runZonedGuarded.<anonymous closure>  (dart:async/zone.dart:1591:19)
E/flutter (12662): #12     _CustomZone.handleUncaughtError  (dart:async/zone.dart:1059:19)
E/flutter (12662): #13     main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> 
package:tbccwallet/main.dart:46
E/flutter (12662): #14     FlutterError.reportError 
.......
```
flutter doctor:

```
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code, 64-bit edition (version 1.45.1)
[√] Connected device (1 available)
```

**Comment by andromeda911** [comment]
I solved the problem by adding Map<String,dynamic>.from( )  to the function call in plugin source

```
void mergeAttributes(Map<String, dynamic> attributes,
    {@required Map<String, dynamic> into}) {
  assert(attributes != null && into != null);
  attributes.forEach((String name, dynamic value) {
    dynamic targetValue = into[name];
    if (value is Map) {
      if (targetValue is! Map) {
        // Let mergeAttributes make a deep copy, because assigning a reference
        // of 'value' will expose 'value' to be mutated by further merges.
        into[name] = targetValue = <String, dynamic>{};
      }
      mergeAttributes(Map<String,dynamic>.from(value), into: Map<String,dynamic>.from(targetValue));
    } else {
      into[name] = value;
    }
  });
}
```
