### ISSUE TITLE
Flutter Web: window.cookiestore.set throws exception: The following JSNoSuchMethodError was thrown building Builder: TypeError: Cannot read property 'Symbol(dartx.set)' of undefined

### ISSUE THREAD

**Issue by antholeole** [flutter/flutter#58488]
## Steps to Reproduce

1. Start a flutter project with web enabled
2. import "dart:html"
3. add "window.cookiestore.set("test", "test")"
4. watch error with root cause: "Cannot read property 'Symbol(dartx.set)' of undefined"
Expected results:
Wanted to see a cookie set in the browser

Actual results:
Exception thrown

<details>
Stacktrace: 

```
TypeError: Cannot read property 'Symbol(dartx.set)' of undefined
    at login_page._LoginPageState.new._login (http://localhost:53322/packages/nemesis_dashboard/features/login/display/login_page.dart.lib.js:1293:34)
    at _login.next (<anonymous>)
    at onValue (http://localhost:53322/dart_sdk.js:35655:33)
    at _RootZone.runUnary (http://localhost:53322/dart_sdk.js:35540:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:53322/dart_sdk.js:30956:29)
    at handleValueCallback (http://localhost:53322/dart_sdk.js:31466:49)
    at Function._propagateToListeners (http://localhost:53322/dart_sdk.js:31498:17)
    at _Future.new.[_completeWithValue] (http://localhost:53322/dart_sdk.js:31357:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53322/dart_sdk.js:31377:35)
    at Object._microtaskLoop (http://localhost:53322/dart_sdk.js:35756:13)
    at _startMicrotaskLoop (http://localhost:53322/dart_sdk.js:35762:13)
    at http://localhost:53322/dart_sdk.js:31704:9
```

Flutter doctor result: 

```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.18.0-11.1.pre at /Users/anthony/flutter
    • Framework revision 2738a1148b (3 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/anthony/Library/Android/SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/anthony/Library/Android/SDK
    • ANDROID_SDK_ROOT = /Users/anthony/Library/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61
```

</details>

**Comment by VladyslavBondarenko** [comment]
Reproduces with current master `1.19.0-3.0.pre.13` as well.

```
import 'package:flutter/material.dart';
import 'dart:html' as html;

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
          body: Center(
            child: RaisedButton(
              child: Text('button'),
              onPressed: () {
                print(html.window.cookieStore); // null
                html.window.cookieStore.set("test", "test");
              },
            ),
          )
      ),
    );
  }
}
```

**Comment by agreensh** [comment]
html.window.cookieStore is always null.
Is there any other way to access cookies in a flutter web project?
This is blocking.

**Comment by agreensh** [comment]
Any more info on this? Still present in Flutter 1.22.0-12.0.pre
Any other way to access the cookies?

**Comment by balazsbokanyi** [comment]
@agreensh there is an alternative, you can access cookies stored in the browser via dart:html package. 
import 'dart:html' as html;
print(html.document.cookie);
https://api.dart.dev/stable/2.10.2/dart-html/Document-class.html

**Comment by agreensh** [comment]
@balazsbokanyi I've already tried that (with httpOnly=false).

html.document.cookie is not set.

The cookie I set on the server is: "/5kjUhXU8zA7a0/CsNIDFQ==", expires: 2020-10-30 15:51:09 +0000, maxAge: nil, domain: nil, path: "/", isSecure: true, isHTTPOnly: false

(I can successfully read this cookie using Flutter on iOS / Macos / Android / Windows from the http response header, and it also works fine in Postman).

**Comment by TahaTesser** [comment]
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:html' as html;

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
          body: Center(
        child: RaisedButton(
          child: Text('button'),
          onPressed: () {
            print(html.window.cookieStore); // null
            html.window.cookieStore.set("test", "test");
          },
        ),
      )),
    );
  }
}
```
</details>


<details>
<summary>logs</summary>

```bash
[  +87 ms] Using Google Chrome 87.0.4280.141 

[+4768 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:51050/devtools/browser/65eb2c8c-b11e-46e7-9bcc-5eec13a0566f
[ +753 ms] DwdsInjector: Received request for entrypoint at http://localhost:51036/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[   +9 ms] MetadataProvider: Loaded debug metadata
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:51036/main_module.bootstrap.js
[+1781 ms] DevHandler: Debug service listening on ws://127.0.0.1:51068/EJkBKByoYVU=/ws

[  +11 ms] Debug service listening on ws://127.0.0.1:51068/EJkBKByoYVU=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+10888 ms] [object CookieStore]
[   +5 ms] TypeError: Failed to execute 'set' on 'CookieStore': Cannot modify a secure cookie on insecure origin
               at CookieStore.[dartx.set] (http://localhost:51036/dart_sdk.js:70710:57)
               at http://localhost:51036/packages/triage/main.dart.lib.js:226:46
               at ink_well._InkResponseState.new.[_handleTap] (http://localhost:51036/packages/flutter/src/material/icon_button.dart.lib.js:50706:42)
               at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:51036/packages/flutter/src/gestures/recognizer.dart.lib.js:203:18)
               at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:51036/packages/flutter/src/gestures/tap.dart.lib.js:411:40)
               at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:51036/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
               at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:51036/packages/flutter/src/gestures/tap.dart.lib.js:164:23)
               at tap.TapGestureRecognizer.new.handleEvent (http://localhost:51036/packages/flutter/src/gestures/recognizer.dart.lib.js:458:16)
               at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:51036/packages/flutter/src/gestures/pointer_router.dart.lib.js:103:9)
               at http://localhost:51036/packages/flutter/src/gestures/pointer_router.dart.lib.js:138:26
               at LinkedMap.new.forEach (http://localhost:51036/dart_sdk.js:26101:11)
               at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:51036/packages/flutter/src/gestures/pointer_router.dart.lib.js:135:29)
               at pointer_router.PointerRouter.new.route (http://localhost:51036/packages/flutter/src/gestures/pointer_router.dart.lib.js:127:37)
               at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:331:26)
               at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:314:24)
               at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:51036/packages/flutter/src/rendering/layer.dart.lib.js:6092:13)
               at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
               at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:258:43)
               at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:247:14)
               at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:237:65)
               at Object.invoke1 (http://localhost:51036/dart_sdk.js:182362:7)
               at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:51036/dart_sdk.js:163172:15)
               at _engine.PointerBinding.__.[_onPointerData] (http://localhost:51036/dart_sdk.js:163806:49)
               at http://localhost:51036/dart_sdk.js:164258:26
               at http://localhost:51036/dart_sdk.js:164211:16
               at http://localhost:51036/dart_sdk.js:163910:11
[ +547 ms] [object CookieStore]
[   +4 ms] TypeError: Failed to execute 'set' on 'CookieStore': Cannot modify a secure cookie on insecure origin
               at CookieStore.[dartx.set] (http://localhost:51036/dart_sdk.js:70710:57)
               at http://localhost:51036/packages/triage/main.dart.lib.js:226:46
               at ink_well._InkResponseState.new.[_handleTap] (http://localhost:51036/packages/flutter/src/material/icon_button.dart.lib.js:50706:42)
               at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:51036/packages/flutter/src/gestures/recognizer.dart.lib.js:203:18)
               at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:51036/packages/flutter/src/gestures/tap.dart.lib.js:411:40)
               at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:51036/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
               at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:51036/packages/flutter/src/gestures/tap.dart.lib.js:164:23)
               at tap.TapGestureRecognizer.new.handleEvent (http://localhost:51036/packages/flutter/src/gestures/recognizer.dart.lib.js:458:16)
               at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:51036/packages/flutter/src/gestures/pointer_router.dart.lib.js:103:9)
               at http://localhost:51036/packages/flutter/src/gestures/pointer_router.dart.lib.js:138:26
               at LinkedMap.new.forEach (http://localhost:51036/dart_sdk.js:26101:11)
               at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:51036/packages/flutter/src/gestures/pointer_router.dart.lib.js:135:29)
               at pointer_router.PointerRouter.new.route (http://localhost:51036/packages/flutter/src/gestures/pointer_router.dart.lib.js:127:37)
               at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:331:26)
               at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:314:24)
               at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:51036/packages/flutter/src/rendering/layer.dart.lib.js:6092:13)
               at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
               at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:258:43)
               at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:247:14)
               at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:51036/packages/flutter/src/gestures/binding.dart.lib.js:237:65)
               at Object.invoke1 (http://localhost:51036/dart_sdk.js:182362:7)
               at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:51036/dart_sdk.js:163172:15)
               at _engine.PointerBinding.__.[_onPointerData] (http://localhost:51036/dart_sdk.js:163806:49)
               at http://localhost:51036/dart_sdk.js:164258:26
               at http://localhost:51036/dart_sdk.js:164211:16
               at http://localhost:51036/dart_sdk.js:163910:11
[+2093 ms] DevHandler: Stopped debug service on ws://127.0.0.1:51066
```
</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (5 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
```bash
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-8.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision b9d06fffb2 (12 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.419, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.419 at /Users/tahatesser/Code/flutter_master
    • Framework revision 913d5933c1 (4 hours ago), 2021-01-19 22:34:03 -0800
    • Engine revision b58dbc88fc
    • Dart version 2.12.0 (build 2.12.0-240.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by antholeole** [comment]
Not sure when this got fixed, but it's fixed! Yay!
