### ISSUE TITLE
Dart crash: unreachable code crash on macOS/CI

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#58523]
From customer_testing_shard: https://cirrus-ci.com/task/6654103428268032?command=main#L7

```
flutter test
| ../../third_party/dart/runtime/vm/kernel_binary.h: 371: error: unreachable code
| version=2.9.0-13.0.dev.flutter-3d53df52af (be) (Tue Jun 2 13:25:01 2020 +0000) on "macos_x64"
| pid=77039, thread=10499, isolate_group=main(0x7fe0e7019000), isolate=main(0x7fe0e7009800)
| isolate_instructions=1051e3840, vm_instructions=1051e3840
|   pc 0x000000010548efc5 fp 0x0000700008bf3e40 dart::Profiler::DumpStackTrace(void*)+0x85
|   pc 0x00000001051e3992 fp 0x0000700008bf3f20 dart::Assert::Fail(char const*, ...)+0x82
|   pc 0x0000000105720541 fp 0x0000700008bf3f50 dart::kernel::KernelReaderHelper::ReadNullability()+0xa1
|   pc 0x000000010573e9da fp 0x0000700008bf3f90 dart::kernel::TypeTranslator::BuildInterfaceType(bool)+0x2a
|   pc 0x0000000105740e75 fp 0x0000700008bf4070 dart::kernel::TypeTranslator::SetupFunctionParameters(dart::Class const&, dart::Function const&, bool, bool, dart::kernel::FunctionNodeHelper*)+0x5c5
|   pc 0x00000001053eeeb3 fp 0x0000700008bf4200 dart::kernel::KernelLoader::LoadProcedure(dart::Library const&, dart::Class const&, bool, long)+0x803
|   pc 0x00000001053efe2e fp 0x0000700008bf43c0 dart::kernel::KernelLoader::FinishClassLoading(dart::Class const&, dart::Library const&, dart::Class const&, long, dart::kernel::ClassIndex const&, dart::kernel::ClassHelper*)+0xbee
|   pc 0x00000001053f04c2 fp 0x0000700008bf48a0 dart::kernel::KernelLoader::FinishLoading(dart::Class const&)+0x422
|   pc 0x0000000105348ef7 fp 0x0000700008bf4a30 dart::ClassFinalizer::FinalizeClass(dart::Class const&)+0xf7
|   pc 0x0000000105349c7f fp 0x0000700008bf4b20 dart::ClassFinalizer::LoadClassMembers(dart::Class const&)+0xbf
|   pc 0x000000010541e044 fp 0x0000700008bf4b80 dart::Class::LookupFunctionAllowPrivate(dart::String const&, dart::Class::MemberKind) const+0x74
|   pc 0x0000000105733815 fp 0x0000700008bf4bc0 dart::kernel::TranslationHelper::LookupStaticMethodByKernelProcedure(dart::kernel::NameIndex)+0x125
|   pc 0x0000000105719dd4 fp 0x0000700008bf4c60 dart::kernel::StreamingFlowGraphBuilder::BuildStaticInvocation(dart::TokenPosition*)+0x84
|   pc 0x0000000105712535 fp 0x0000700008bf4cc0 dart::kernel::StreamingFlowGraphBuilder::BuildExpression(dart::TokenPosition*)+0x2a5
|   pc 0x0000000105720227 fp 0x0000700008bf4d50 dart::kernel::StreamingFlowGraphBuilder::BuildVariableDeclaration()+0x1d7
|   pc 0x000000010571466e fp 0x0000700008bf4d90 dart::kernel::StreamingFlowGraphBuilder::BuildStatement()+0x8e
|   pc 0x000000010571c6f8 fp 0x0000700008bf4df0 dart::kernel::StreamingFlowGraphBuilder::BuildBlock()+0x88
|   pc 0x0000000105714695 fp 0x0000700008bf4e30 dart::kernel::StreamingFlowGraphBuilder::BuildStatement()+0xb5
|   pc 0x0000000105715b17 fp 0x0000700008bf4ed0 dart::kernel::StreamingFlowGraphBuilder::BuildFunctionBody(dart::Function const&, dart::LocalVariable*, bool)+0x107
|   pc 0x00000001057161da fp 0x0000700008bf5050 dart::kernel::StreamingFlowGraphBuilder::BuildGraphOfFunction(bool)+0x2ca
|   pc 0x0000000105716744 fp 0x0000700008bf52b0 dart::kernel::StreamingFlowGraphBuilder::BuildGraph()+0x164
|   pc 0x0000000105726ead fp 0x0000700008bf55b0 dart::kernel::FlowGraphBuilder::BuildGraph()+0x7d
|   pc 0x0000000105537de4 fp 0x0000700008bf57b0 dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool)+0x54
|   pc 0x0000000105538f18 fp 0x0000700008bf5e70 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)+0x428
|   pc 0x0000000105539dea fp 0x0000700008bf6040 dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long)+0x44a
|   pc 0x0000000105539960 fp 0x0000700008bf60d0 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)+0x190
|   pc 0x000000010553822d fp 0x0000700008bf6180 dart::DRT_CompileFunction(dart::NativeArguments)+0x20d
|   pc 0x00000001090812b8 fp 0x0000700008bf61c8 Unknown symbol
|   pc 0x0000000109081314 fp 0x0000700008bf61f8 Unknown symbol
|   pc 0x0000000110a778c0 fp 0x0000700008bf6240 Unknown symbol
|   pc 0x0000000110a77549 fp 0x0000700008bf6290 Unknown symbol
|   pc 0x0000000110a75704 fp 0x0000700008bf6360 Unknown symbol
|   pc 0x000000010e451547 fp 0x0000700008bf6398 Unknown symbol
|   pc 0x0000000110a75061 fp 0x0000700008bf63d0 Unknown symbol
|   pc 0x0000000110a74f14 fp 0x0000700008bf6418 Unknown symbol
|   pc 0x000000010e418473 fp 0x0000700008bf6490 Unknown symbol
|   pc 0x000000010e4182bd fp 0x0000700008bf6500 Unknown symbol
|   pc 0x000000010e417753 fp 0x0000700008bf65a0 Unknown symbol
|   pc 0x000000010e46a985 fp 0x0000700008bf6610 Unknown symbol
|   pc 0x000000010e46a83c fp 0x0000700008bf6660 Unknown symbol
|   pc 0x000000010e418597 fp 0x0000700008bf66d8 Unknown symbol
|   pc 0x000000010e4182bd fp 0x0000700008bf6748 Unknown symbol
|   pc 0x000000010e417753 fp 0x0000700008bf67e8 Unknown symbol
|   pc 0x000000010e46a985 fp 0x0000700008bf6858 Unknown symbol
|   pc 0x000000010e46a83c fp 0x0000700008bf68a8 Unknown symbol
|   pc 0x000000010e43c353 fp 0x0000700008bf68f0 Unknown symbol
|   pc 0x000000010e43bfb4 fp 0x0000700008bf6930 Unknown symbol
|   pc 0x000000010e43bec7 fp 0x0000700008bf6970 Unknown symbol
|   pc 0x000000010e43bcd3 fp 0x0000700008bf69b0 Unknown symbol
|   pc 0x000000010b826f8d fp 0x0000700008bf69d8 Unknown symbol
|   pc 0x000000010908174c fp 0x0000700008bf6a48 Unknown symbol
|   pc 0x0000000105389d80 fp 0x0000700008bf6ae0 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x120
|   pc 0x0000000105389a4b fp 0x0000700008bf6b80 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x2db
|   pc 0x000000010538bf08 fp 0x0000700008bf6be0 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x1e8
|   pc 0x00000001053c14f6 fp 0x0000700008bf6dd0 dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)+0x4b6
|   pc 0x00000001053f3dc6 fp 0x0000700008bf6e50 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x136
|   pc 0x00000001053f4404 fp 0x0000700008bf6eb0 dart::MessageHandler::TaskCallback()+0x1e4
|   pc 0x0000000105527322 fp 0x0000700008bf6f40 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x152
|   pc 0x00000001055275ef fp 0x0000700008bf6f70 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
|   pc 0x000000010548b031 fp 0x0000700008bf6fb0 dart::ThreadStart(void*)+0x61
|   pc 0x00007fff6ab6ee65 fp 0x0000700008bf6fd0 _pthread_start+0x94
|   pc 0x00007fff6ab6a83b fp 0x0000700008bf6ff0 thread_start+0xf
| -- End of DumpStackTrace
| [exit     : sp(0) fp(0x700008bf61c8) pc(0)]
| [stub     : sp(0x700008bf61d8) fp(0x700008bf61f8) pc(0x109081314)]
| [dart     : sp(0x700008bf6208) fp(0x700008bf6240) pc(0x110a778c0) package:test_core/src/runner/parse_metadata.dart__Parser@1033257374__Parser@1033257374. ]
| [dart     : sp(0x700008bf6250) fp(0x700008bf6290) pc(0x110a77549) package:test_core/src/runner/parse_metadata.dart_::_parseMetadata ]
| [dart     : sp(0x700008bf62a0) fp(0x700008bf6360) pc(0x110a75704) package:test_core/src/runner/loader.dart_Loader_loadFile__async_op ]
| [dart     : sp(0x700008bf6370) fp(0x700008bf6398) pc(0x10e451547) dart:core__Closure@0150898_call ]
| [dart     : sp(0x700008bf63a8) fp(0x700008bf63d0) pc(0x110a75061) dart:async__AsyncStarStreamController@4048458_runBody ]
| [dart     : sp(0x700008bf63e0) fp(0x700008bf6418) pc(0x110a74f14) dart:async__AsyncStarStreamController@4048458_runBody_runBody ]
| [dart     : sp(0x700008bf6428) fp(0x700008bf6490) pc(0x10e418473) dart:async_::__rootRun@4048458 ]
| [dart     : sp(0x700008bf64a0) fp(0x700008bf6500) pc(0x10e4182bd) dart:async_::__rootRun@4048458__rootRun@4048458 ]
| [dart     : sp(0x700008bf6510) fp(0x700008bf65a0) pc(0x10e417753) dart:async__CustomZone@4048458_run ]
| [dart     : sp(0x700008bf65b0) fp(0x700008bf6610) pc(0x10e46a985) dart:async__CustomZone@4048458_runGuarded ]
| [dart     : sp(0x700008bf6620) fp(0x700008bf6660) pc(0x10e46a83c) dart:async__CustomZone@4048458_bindCallbackGuarded_<anonymous closure> ]
| [dart     : sp(0x700008bf6670) fp(0x700008bf66d8) pc(0x10e418597) dart:async_::__rootRun@4048458 ]
| [dart     : sp(0x700008bf66e8) fp(0x700008bf6748) pc(0x10e4182bd) dart:async_::__rootRun@4048458__rootRun@4048458 ]
| [dart     : sp(0x700008bf6758) fp(0x700008bf67e8) pc(0x10e417753) dart:async__CustomZone@4048458_run ]
| [dart     : sp(0x700008bf67f8) fp(0x700008bf6858) pc(0x10e46a985) dart:async__CustomZone@4048458_runGuarded ]
| [dart     : sp(0x700008bf6868) fp(0x700008bf68a8) pc(0x10e46a83c) dart:async__CustomZone@4048458_bindCallbackGuarded_<anonymous closure> ]
| [dart     : sp(0x700008bf68b8) fp(0x700008bf68f0) pc(0x10e43c353) dart:async_::__microtaskLoop@4048458 ]
| [dart     : sp(0x700008bf6900) fp(0x700008bf6930) pc(0x10e43bfb4) dart:async_::__startMicrotaskLoop@4048458 ]
| [dart     : sp(0x700008bf6940) fp(0x700008bf6970) pc(0x10e43bec7) dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]
| [dart     : sp(0x700008bf6980) fp(0x700008bf69b0) pc(0x10e43bcd3) dart:isolate_::__runPendingImmediateCallback@1026248 ]
| [dart     : sp(0x700008bf69c0) fp(0x700008bf69d8) pc(0x10b826f8d) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
| [entry    : sp(0x700008bf69e8) fp(0x700008bf6a48) pc(0x10908174c)]
| /private/tmp/flutter sdk/bin/internal/shared.sh: line 210: 77039 Abort trap: 6 
```

**Comment by christopherfujino** [comment]
Possibly related https://cirrus-ci.com/task/6037175961649152?command=main#L385:

```
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x100118a29300
version=2.9.0-11.0.dev.flutter-6489a0c68d (be) (Wed May 27 05:50:13 2020 +0000) on "macos_x64"
pid=76996, thread=13315, isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=108bc0260
  pc 0x0000000108f384db fp 0x000070000c7e0e40 dart::MarkingVisitorBase<true>::DrainMarkingStack()+0x1bb
  pc 0x0000000108f38e8c fp 0x000070000c7e0eb0 dart::ConcurrentMarkTask::Run()+0x6c
  pc 0x0000000108f03302 fp 0x000070000c7e0f40 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x152
  pc 0x0000000108f035cf fp 0x000070000c7e0f70 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
  pc 0x0000000108e66d51 fp 0x000070000c7e0fb0 dart::ThreadStart(void*)+0x61
  pc 0x00007fff6ab6ee65 fp 0x000070000c7e0fd0 _pthread_start+0x94
  pc 0x00007fff6ab6a83b fp 0x000070000c7e0ff0 thread_start+0xf
-- End of DumpStackTrace
analysis server exited: -6
Expected: <0>
  Actual: <1>
#0      fail (package:test_api/src/frontend/expect.dart:154:30)
#1      _expect (package:test_api/src/frontend/expect.dart:148:3)
#2      expect (package:test_api/src/frontend/expect.dart:60:3)
#3      _analyzeProject (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:1593:3)
<asynchronous suspension>
#4      _createAndAnalyzeProject (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:1510:9)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:124:11)
#6      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:152:42)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _runZoned (dart:async/zone.dart:1630:10)
#11     runZoned (dart:async/zone.dart:1550:10)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:141:30)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZonedGuarded (dart:async/zone.dart:1618:12)
#18     runZoned (dart:async/zone.dart:1547:12)
#19     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:139:18)
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#21     _rootRun (dart:async/zone.dart:1190:13)
#22     _CustomZone.run (dart:async/zone.dart:1093:19)
#23     _runZoned (dart:async/zone.dart:1630:10)
#24     runZoned (dart:async/zone.dart:1550:10)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#26     testUsingContext.<anonymous closure>.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:105:22)
#27     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:62:18)
<asynchronous suspension>
#28     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#30     _rootRun (dart:async/zone.dart:1190:13)
#31     _CustomZone.run (dart:async/zone.dart:1093:19)
#32     _runZoned (dart:async/zone.dart:1630:10)
#33     runZoned (dart:async/zone.dart:1550:10)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#35     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
#36     testUsingContext.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:104:11)
#37     test.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/common.dart:169:18)
#38     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#39     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#40     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#41     _rootRun (dart:async/zone.dart:1190:13)
#42     _CustomZone.run (dart:async/zone.dart:1093:19)
#43     _runZoned (dart:async/zone.dart:1630:10)
#44     runZoned (dart:async/zone.dart:1550:10)
#45     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#46     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#47     _rootRun (dart:async/zone.dart:1190:13)
#48     _CustomZone.run (dart:async/zone.dart:1093:19)
#49     _runZoned (dart:async/zone.dart:1630:10)
#50     runZoned (dart:async/zone.dart:1550:10)
#51     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#52     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
#53     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#54     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#55     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#56     _rootRun (dart:async/zone.dart:1182:47)
#57     _CustomZone.run (dart:async/zone.dart:1093:19)
#58     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#59     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#60     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#61     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#62     _rootRun (dart:async/zone.dart:1190:13)
#63     _CustomZone.run (dart:async/zone.dart:1093:19)
#64     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#65     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#66     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#67     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
05:00 +29 -1: test/commands.shard/permeable/create_test.dart: creates a module project correctly [E]                                                                                                   
  Expected: <0>
    Actual: <1>
  package:test_api                                       expect
  test/commands.shard/permeable/create_test.dart 1593:3  _analyzeProject
  ===== asynchronous gap ===========================
  dart:async                                             _asyncErrorWrapperHelper
  test/src/context.dart 141:30                           testUsingContext.<fn>.<fn>.<fn>.<fn>
  dart:async                                             runZoned
  test/src/context.dart 139:18                           testUsingContext.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 150:29     AppContext.run.<fn>
  dart:async                                             runZoned
  package:flutter_tools/src/base/context.dart 149:18     AppContext.run
  test/src/context.dart 105:22                           testUsingContext.<fn>.<fn>
  package:flutter_tools/src/context_runner.dart 62:18    runInContext.runnerWrapper
  ===== asynchronous gap ===========================
  dart:async                                             _asyncThenWrapperHelper
  package:flutter_tools/src/context_runner.dart          runInContext.runnerWrapper
  package:flutter_tools/src/base/context.dart 150:29     AppContext.run.<fn>
  dart:async                                             runZoned
  package:flutter_tools/src/base/context.dart 149:18     AppContext.run
  package:flutter_tools/src/context_runner.dart 65:24    runInContext
  test/src/context.dart 104:11                           testUsingContext.<fn>
  test/src/common.dart 169:18                            test.<fn>
```

**Comment by zanderso** [comment]
Teasing out the Dart version: `2.9.0-13.0.dev.flutter-3d53df52af`

@jonahwilliams could you paste in here the commands the bot is running when this crash happens?

@christopherfujino that looks like a different bug. Could you file a new issue?

**Comment by jonahwilliams** [comment]
Specifically:

```
dart --enable-asserts dev/customer_testing/run_tests.dart --skip-on-fetch-failure --skip-template bin/cache/pkg/tests/registry/*.test
```

That in turn is calling `flutter test`. I can't tell if it is the first process or the second that is crashing

**Comment by christopherfujino** [comment]
will do

**Comment by christopherfujino** [comment]
> @christopherfujino that looks like a different bug. Could you file a new issue?

Opened https://github.com/flutter/flutter/issues/58531, linking here in case the root cause is the same.

**Comment by zanderso** [comment]
The `UNREACHABLE()` is here: https://github.com/dart-lang/sdk/blob/2707880f1b486f2a2f87d7e2de7baea12c6ca362/runtime/vm/kernel_binary.h#L371

/cc @alexmarkov

**Comment by alexmarkov** [comment]
This looks like a corrupted dill file. 

I wasn't able to reproduce the problem on my Mac. Is it flaky?

Can you reproduce the crash? Could you reduce this down to a `dart` command line which crashes (instead of spawning other `dart` processes which crash)? If this test harness generates dill files in some way, it would be useful to extract the dill file which crashed the VM and figure out how it is generated.

**Comment by mkustermann** [comment]
Are the tools involved here caching kernel files on disc by any chance. Please be aware that we do not maintain any compatibility across VM versions atm.

See https://github.com/dart-lang/sdk/issues/41802 for efforts in-progress to make the VM give a nice error message when it's given an incompatible dill file.

**Comment by jonahwilliams** [comment]
As far as I can tell this is an immediate crash with no cached dill files. Its possible that the CI environment is not entirely clean but I do not think that is the case, and we don't have any specific logic to cache dill files

> Please be aware that we do not maintain any compatibility across VM versions atm.

Thats fine, but surely we shouldn't crash like this if an old dill _is_ encountered.
