### ISSUE TITLE
[image_picker_for_web / video_player_web] Can't preview PickedFile videos in Safari

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#58527]
1. Compile the `example` app of the `image_picker` plugin for web. 
2. In Safari, try to select a video from your local drive.

Playback of the selected file doesn't start.

Looking at the DOM, it doesn't even seem that the plugin is attempting to render *anything* at all. 

There's no errors in the JS console.

Is this a problem with the `image_picker_for_web` plugin, or the `video_player_web`? Is this a problem with supported formats?

**Comment by ditman** [comment]
There's a bunch of issues at play here. So far that I've found:

1. Safari doesn't like users to mess with Blob uris, and [this](https://github.com/flutter/plugins/blob/master/packages/video_player/video_player_web/lib/video_player_web.dart#L72) is breaking all videos regardless of the format. It seems that the Blob URI can't be parsed and then reconstructed; it needs to be passed through as is from the browser for Safari to pick it up.
2. Some video formats are not supported (even if they are selectable!) Errors are being swallowed by the web plugin somewhere, and never surfaced to the end user (or the JS console).
3. Some code in the image_picker example app is attempting to reuse a discarded video player controller is throwing an unhandled exception and breaking subsequent playback attempts in Safari. This errors happen in other browsers, but they're not fatal there. Why?

**Comment by ditman** [comment]
Number 2 above is not exactly accurate. If the browser lets you select a video, it'll be able to play it back. The issue is that Safari now disallows auto-play of videos if they have sound, unless the "muted" attribute is added to the video player (at least).

**Comment by pedromassangocode** [comment]
This is still a valid issue. video does not play on web.

![Screen Shot 2021-02-12 at 15 15 24](https://user-images.githubusercontent.com/67424416/107779043-23756800-6d45-11eb-88cf-aa835948777b.png)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
  PickedFile _pickedFile;
  final picker = ImagePicker();

  Future getImage() async {
    var v = ImageSource.gallery;
    var pickedFile = await picker.getVideo(source: v);

    setState(() {
      if (pickedFile != null) {
        _pickedFile = pickedFile;
      } else {
        print('No image selected.');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Image Picker Example'),
      ),
      body: Center(
        child: Builder(
          builder: (c) {
            if (_pickedFile == null)
              return Text('Select Video!');
            return VideoPlayer(
                VideoPlayerController.network(_pickedFile.path)
            );
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          getImage();
        },
        tooltip: 'Pick Video',
        child:
        Icon(Icons.add_a_photo),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-2.0.pre.77, on macOS 11.2 20D64 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-2.0.pre.77 at /Users/pedromassango/Code/flutter_master
    • Framework revision 9296a527b3 (3 hours ago), 2021-02-11 18:33:24 -0800
    • Engine revision cdc49c575b
    • Dart version 2.13.0 (build 2.13.0-25.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment]
Hi @ditman,
Thanks for filing the issue, I can confirm the issue still persists, I verified this on the latest stable and master channel with  ```image_picker: ^0.8.1+1``` and ```video_player: ^2.1.6```, The selected video using image_picker neither plays on safari nor in chrome.

<details>
<summary>code sample</summary>

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: VideoPicker(),
    ),
  );
}

class VideoPicker extends StatefulWidget {
  @override
  _VideoPickerState createState() => _VideoPickerState();
}

class _VideoPickerState extends State {
  PickedFile? _pickedFile;
  final picker = ImagePicker();

  Future getVideo() async {
    var v = ImageSource.gallery;
    var pickedFile = await picker.getVideo(source: v);

    setState(() {
      if (pickedFile != null) {
        _pickedFile = pickedFile;
        initializeVideo();
      } else {
        print('No image selected.');
      }
    });
  }

  void initializeVideo() {
    if (_pickedFile != null) {
      _controller = VideoPlayerController.file(File(_pickedFile!.path));
      _controller.initialize().then((value) => setState(() {}));
    } else {
      _controller = VideoPlayerController.file(File(''));
    }
  }

  late VideoPlayerController _controller;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    initializeVideo();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Image Picker Example'),
        ),
        body: Center(
          child: Builder(
            builder: (c) {
              if (_pickedFile == null) return Text('Select Video!');
              return VideoPlayer(_controller);
            },
          ),
        ),
        floatingActionButton: Row(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            FloatingActionButton(
              onPressed: () {
                getVideo();
              },
              tooltip: 'Pick Video',
              child: Icon(Icons.add_a_photo),
            ),
            SizedBox(
              width: 20,
            ),
            FloatingActionButton(
              onPressed: () {
                setState(() {
                  // If the video is playing, pause it.
                  if (_controller.value.isPlaying) {
                    _controller.pause();
                  } else {
                    // If the video is paused, play it.
                    _controller.play();
                  }
                });
              },
              tooltip: 'Pick Video',
              child: Icon(
                _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
              ),
            ),
          ],
        ));
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.538, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.3.0-17.0.pre.538 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1fd2f7c400 (32 hours ago), 2021-06-27 22:51:02 -0400
    • Engine revision 5d287a2061
    • Dart version 2.14.0 (build 2.14.0-250.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

<details>
<summary>Exception logs when running on chrome</summary>

```
Error: UnimplementedError: web implementation of video_player cannot play local files
    Non-error `null` thrown by JS does not have stack trace.
Caught in Dart at:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:20  missing
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 152:24  stackTrace
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 165:10  stackTraceForError
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 286:33            get stackTrace
dart-sdk/lib/async/async_error.dart 26:29                                     defaultStackTrace
dart-sdk/lib/async/future.dart 277:31                                         error
packages/video_player_web/video_player_web.dart 89:23                         create
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/video_player_web/video_player_web.dart 69:21                         create
packages/video_player/video_player.dart 308:46                                initialize
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/video_player/video_player.dart 273:26                                initialize
packages/video_player_example/video_picker_player.dart 41:32                  initializeVideo
packages/video_player_example/video_picker_player.dart 31:9                   <fn>
packages/flutter/src/widgets/framework.dart 1088:30                           setState
packages/video_player_example/video_picker_player.dart 28:5                   getVideo
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1613:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 155:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 707:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 736:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 542:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 580:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
    at Object.createErrorWithStack (http://localhost:56169/dart_sdk.js:5054:12)
    at Object._rethrow (http://localhost:56169/dart_sdk.js:37670:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:56169/dart_sdk.js:37666:13)
    at Object._microtaskLoop (http://localhost:56169/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:56169/dart_sdk.js:37532:13)
    at http://localhost:56169/dart_sdk.js:33303:9

```
</details>

**Comment by balvinderz** [comment]
@maheshmnj  @pedromassangocode . Both your examples use VideoPlayerController.file for testing whether video works on web or not.  VideoPlayerController.network should be used in web case.

**Comment by maheshmnj** [comment]
> @maheshmnj @pedromassangocode . Both your examples use VideoPlayerController.file for testing whether video works on web or not. VideoPlayerController.network should be used in web case.

@balvinderz this issue is about playing local videos picked via image picker on the web so `VideoPlayerController.file` has been used.

**Comment by gautham-designway** [comment]
### kmll           **hgffd**  **_httn_**

**Comment by gabrielokura** [comment]
@maheshmnj Could this issue be closed?

**Comment by ditman** [comment]
Yes, let's close it based on the investigation that @maheshmnj did above. It can be re-opened (or a new one be created) as needed.
