### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = '/Users/sguslystyi/.flutter_tool_state' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by juicesharp** [flutter/flutter#58529]
## Command
```
flutter upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = '/Users/sguslystyi/.flutter_tool_state' (OS Error: Permission denied, errno = 13)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:137:22)
#6      ErrorHandlingFile._runSync (package:flutter_tools/src/base/error_handling_file_system.dart:163:16)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:136:5)
#8      Config._flushValues (package:flutter_tools/src/base/config.dart:86:11)
#9      Config.setValue (package:flutter_tools/src/base/config.dart:75:5)
#10     _DefaultPersistentToolState.updateLastActiveVersion (package:flutter_tools/src/persistent_tool_state.dart:109:13)
#11     UpgradeCommandRunner.recordState (package:flutter_tools/src/commands/upgrade.dart:151:33)
#12     UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:138:5)
<asynchronous suspension>
#13     UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:85:13)
#14     UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:60:27)
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#16     _rootRunUnary (dart:async/zone.dart:1192:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.17.1 at /Users/sguslystyi/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sguslystyi/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by visual-velocity** [comment]
We are facing this issue Android 29 on real device. How we can solve it because we faced issue on production app.

**Comment by jmagman** [comment]
@zanderso re: https://github.com/flutter/flutter/pull/50125

**Comment by zanderso** [comment]
@juicesharp The tool is trying to write some persistent state under `$HOME`. I think without more information we won't be able to diagnose why the write is failing with permission denied. Does the file already exist? If so what are the user and group flags set on it? What user/group is the Flutter process running under? Do those match up with the `$HOME` environment variable of the process? Thanks!

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
