### ISSUE TITLE
`tools_tests-commands-macos` segmentation fault 

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#58531]
link: https://cirrus-ci.com/task/6037175961649152

```
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x100118a29300
version=2.9.0-11.0.dev.flutter-6489a0c68d (be) (Wed May 27 05:50:13 2020 +0000) on "macos_x64"
pid=76996, thread=13315, isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=108bc0260
  pc 0x0000000108f384db fp 0x000070000c7e0e40 dart::MarkingVisitorBase<true>::DrainMarkingStack()+0x1bb
  pc 0x0000000108f38e8c fp 0x000070000c7e0eb0 dart::ConcurrentMarkTask::Run()+0x6c
  pc 0x0000000108f03302 fp 0x000070000c7e0f40 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x152
  pc 0x0000000108f035cf fp 0x000070000c7e0f70 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
  pc 0x0000000108e66d51 fp 0x000070000c7e0fb0 dart::ThreadStart(void*)+0x61
  pc 0x00007fff6ab6ee65 fp 0x000070000c7e0fd0 _pthread_start+0x94
  pc 0x00007fff6ab6a83b fp 0x000070000c7e0ff0 thread_start+0xf
-- End of DumpStackTrace
analysis server exited: -6
Expected: <0>
  Actual: <1>
#0      fail (package:test_api/src/frontend/expect.dart:154:30)
#1      _expect (package:test_api/src/frontend/expect.dart:148:3)
#2      expect (package:test_api/src/frontend/expect.dart:60:3)
#3      _analyzeProject (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:1593:3)
<asynchronous suspension>
#4      _createAndAnalyzeProject (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:1510:9)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:124:11)
#6      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:152:42)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _runZoned (dart:async/zone.dart:1630:10)
#11     runZoned (dart:async/zone.dart:1550:10)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:141:30)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZonedGuarded (dart:async/zone.dart:1618:12)
#18     runZoned (dart:async/zone.dart:1547:12)
#19     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:139:18)
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#21     _rootRun (dart:async/zone.dart:1190:13)
#22     _CustomZone.run (dart:async/zone.dart:1093:19)
#23     _runZoned (dart:async/zone.dart:1630:10)
#24     runZoned (dart:async/zone.dart:1550:10)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#26     testUsingContext.<anonymous closure>.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:105:22)
#27     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:62:18)
<asynchronous suspension>
#28     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#30     _rootRun (dart:async/zone.dart:1190:13)
#31     _CustomZone.run (dart:async/zone.dart:1093:19)
#32     _runZoned (dart:async/zone.dart:1630:10)
#33     runZoned (dart:async/zone.dart:1550:10)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#35     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
#36     testUsingContext.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/context.dart:104:11)
#37     test.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter_tools/test/src/common.dart:169:18)
#38     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#39     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#40     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#41     _rootRun (dart:async/zone.dart:1190:13)
#42     _CustomZone.run (dart:async/zone.dart:1093:19)
#43     _runZoned (dart:async/zone.dart:1630:10)
#44     runZoned (dart:async/zone.dart:1550:10)
#45     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#46     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#47     _rootRun (dart:async/zone.dart:1190:13)
#48     _CustomZone.run (dart:async/zone.dart:1093:19)
#49     _runZoned (dart:async/zone.dart:1630:10)
#50     runZoned (dart:async/zone.dart:1550:10)
#51     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#52     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
#53     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#54     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#55     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#56     _rootRun (dart:async/zone.dart:1182:47)
#57     _CustomZone.run (dart:async/zone.dart:1093:19)
#58     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#59     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#60     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#61     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#62     _rootRun (dart:async/zone.dart:1190:13)
#63     _CustomZone.run (dart:async/zone.dart:1093:19)
#64     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#65     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#66     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#67     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
05:00 +29 -1: test/commands.shard/permeable/create_test.dart: creates a module project correctly [E]                                                                                                   
  Expected: <0>
    Actual: <1>
  package:test_api                                       expect
  test/commands.shard/permeable/create_test.dart 1593:3  _analyzeProject
  ===== asynchronous gap ===========================
  dart:async                                             _asyncErrorWrapperHelper
  test/src/context.dart 141:30                           testUsingContext.<fn>.<fn>.<fn>.<fn>
  dart:async                                             runZoned
  test/src/context.dart 139:18                           testUsingContext.<fn>.<fn>.<fn>
  package:flutter_tools/src/base/context.dart 150:29     AppContext.run.<fn>
  dart:async                                             runZoned
  package:flutter_tools/src/base/context.dart 149:18     AppContext.run
  test/src/context.dart 105:22                           testUsingContext.<fn>.<fn>
  package:flutter_tools/src/context_runner.dart 62:18    runInContext.runnerWrapper
  ===== asynchronous gap ===========================
  dart:async                                             _asyncThenWrapperHelper
  package:flutter_tools/src/context_runner.dart          runInContext.runnerWrapper
  package:flutter_tools/src/base/context.dart 150:29     AppContext.run.<fn>
  dart:async                                             runZoned
  package:flutter_tools/src/base/context.dart 149:18     AppContext.run
  package:flutter_tools/src/context_runner.dart 65:24    runInContext
  test/src/context.dart 104:11                           testUsingContext.<fn>
  test/src/common.dart 169:18                            test.<fn>
```

**Comment by christopherfujino** [comment]
It passed on re-run https://cirrus-ci.com/task/6484488861515776

**Comment by zanderso** [comment]
With flutter/flutter at df45748de68bd50d6487feca4e122ab2ee744c21

From the logs it looks like the VM GC marker thread segfaulted while running the analyzer while running the test `test/commands.shard/permeable/create_test.dart`:

Under `packages/flutter_tools` run:
```
$ pub run test test/commands.shard/permeable/create_test.dart
```

@a-siva @rmacnak-google

**Comment by rmacnak-google** [comment]
Does not reproduce.

**Comment by zanderso** [comment]
@rmacnak-google do you have any advice for what we can do to file a more useful issue if we see this crasher again?

**Comment by rmacnak-google** [comment]
In decreasing order of usefulness: rr traces, reproducible failures, core dumps. Unfortunately a stack trace alone is almost never sufficient to debug a GC crash.

**Comment by zanderso** [comment]
How worried are you about this crash? Should we expend a lot of effort trying to get something more useful?

Also, what's an 'rr trace'? =)

**Comment by mkustermann** [comment]
> Also, what's an 'rr trace'? =)

Trace produced by `rr record` (using https://github.com/mozilla/rr) which can be replayed using `rr replay` :)
