### ISSUE TITLE
[webview_flutter] update SingleViewPresentation context/dialogs to prevent select crash

### ISSUE THREAD

**Issue by cg021** [flutter/flutter#58548]
## Steps to Reproduce

1. Run `flutter channel stable`
2. Open webview_flutter example and change initialUrl to a page with a `<select>` element
4. Click on it. 

**Expected results:** 
Doesn't crash app
**Actual results:** 

<details>
  <summary>Logs</summary>

```
W/System.err(19182): java.lang.ClassCastException: $Proxy0 cannot be cast to android.view.WindowManagerImpl
W/System.err(19182): 	at android.view.Window.setWindowManager(Window.java:778)
W/System.err(19182): 	at android.view.Window.setWindowManager(Window.java:760)
W/System.err(19182): 	at android.app.Dialog.<init>(Dialog.java:207)
W/System.err(19182): 	at android.app.AlertDialog.<init>(AlertDialog.java:204)
W/System.err(19182): 	at android.app.AlertDialog$Builder.create(AlertDialog.java:1105)
W/System.err(19182): 	at BF.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410408383:7)
W/System.err(19182): 	at org.chromium.content.browser.input.SelectPopup.show(chromium-TrichromeWebViewGoogle.apk-stable-410408383:12)
W/System.err(19182): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(19182): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(19182): 	at android.os.Looper.loop(Looper.java:174)
W/System.err(19182): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(19182): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19182): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(19182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

```
Running "flutter pub get" in webview_flutter...                     1.2s
Analyzing webview_flutter...                                            
No issues found! (ran in 7.5s)
```

```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en)
    • Flutter version 1.17.2 at /Users/gonzchristian/Desktop/git/flutter
    • Framework revision 5f21edf8b6 (5 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/gonzchristian/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Pixel 3a • 055AY1WRX3 • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

**Comment by cg021** [comment]
Fix: https://github.com/flutter/engine/pull/18674

**Comment by pcsosinski** [comment]
thanks for tagging - any reports of this crashing in the field or an assessment of impact to our developers?

**Comment by cg021** [comment]
yes, I think the first issue made about this was opened in 2018: https://github.com/flutter/flutter/issues/25767

**Comment by pcsosinski** [comment]
thanks - generally we only do cherrypicks to releases if we introduced a serious regression.  as this is not a regression, I don't think it's a candidate for a cherrypick.

**Comment by cg021** [comment]
apologies for opening- the fix is in master but not stable, so I figured it would be good to add the changes.

**Comment by blasten** [comment]
should we close this issue?
