### ISSUE TITLE
[luci] mac try bots failing to reboot after task failure

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#58559]
1135 2020-05-31 22:09:27.050 E: force rebooting via health checker failed
Traceback (most recent call last):
  File "injected.py", line 232, in on_after_task
  File "/b/s/swarming_bot.1.zip/utils/subprocess42.py", line 560, in __init__
    super(Popen, self).__init__(args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by godofredoc** [comment]
54 failed reboots in 3 days

**Comment by godofredoc** [comment]
Link to dead bot caused by this problem:

https://chromium-swarm.appspot.com/task?id=4c917f37e76af310

Also you can take a look at any bot_died tasks in the following list:

https://chromium-swarm.appspot.com/bot?id=flutter-try-mac-1

**Comment by godofredoc** [comment]
Fixed all the issues causing the flakiness and the bot reboots. The remaining work needed to close this bug is just to remove the noise from bot logs.

**Comment by godofredoc** [comment]
Obsolete: flutter-try- test beds have been removed.
