### ISSUE TITLE
[luci] mac try jobs fail to mount namedcache

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#58563]
35369 2020-06-02 22:56:24.750 E: NamedCache: failed to load named cache state file; obliterating
Traceback (most recent call last):
  File "/b/s/swarming_bot.1.zip/client/local_caching.py", line 850, in __init__
    self._lru = lru.LRUDict.load(self.state_file)
  File "/b/s/swarming_bot.1.zip/utils/lru.py", line 74, in load
    'Broken state file %s with "%s": %s' % (state_file, json_state, e))
ValueError: Broken state file /b/s/c/state.json with "": No JSON object could be decoded

**Comment by godofredoc** [comment]
Flutter builds now need more than 30G space available and three machines had less than 30G disk space available causing all sorts of errors. After removing those three machines we haven't seen the error anymore.
