### ISSUE TITLE
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1039/

### ISSUE THREAD

**Issue by ldowens** [flutter/flutter#58588]
App launch fails: physical device-6th Gen iPad, iOS 13.4.1.
The app gets installed but the connection fails so debugging is not possible. This seems to happen much much more often in 1.17 than it did in 1.12

## Steps to Reproduce
- plug iPad into laptop
- from vscode, Run | Start debugging
in debug console see the error noted below in actual results

**Expected results:** 
my app running on my iPad and connected for debugging

**Actual results:** 
my app, built, installed, but not launched -with this error in the debug console:

```
Launching lib/main.dart on iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 3X949YE9K2
Xcode build done.                                           27.4s
Installing and launching...                                        36.0s
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1039/
Exited (sigterm)
```

<details>
  <summary>Logs</summary>

```
[+1005 ms] Forwarded port ForwardedPort HOST:1045 to DEVICE:65042
[   +3 ms] Installing and launching... (completed in 33.2s)
[  +18 ms] Connecting to service protocol: http://127.0.0.1:1045/
[ +125 ms] Fail to connect to service protocol: http://127.0.0.1:1045/: HttpException: , uri = http://127.0.0.1:1045/ws
[   +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:1045/
[   +6 ms] "flutter run" took 62,755ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#19     _rootRun (dart:async/zone.dart:1184:13)
#20     _CustomZone.run (dart:async/zone.dart:1077:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
Analyzing app...                                              
No issues found! (ran in 9.5s)
```

```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.17.2 at /Users/dev/Documents/development/flutter
    • Framework revision 5f21edf8b6 (4 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPad • aeb0dd50cf0b173f23b83dc325189a6bd1b9de4c • ios • iOS 13.4.1

• No issues found!
```

</details>

**Comment by namclu** [comment]
When I ran `flutter doctor` it told me Android Studio didn't have the Flutter plugin installed (probably after 4.0 update) so I reinstalled the plugin and it's working now

**Comment by VladyslavBondarenko** [comment]
@ldowens 
please follow up on https://github.com/flutter/flutter/issues/60804,
closing current one as duplicate since new issue has output from verbose log
