### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/sushil/Library/Android/sdk/build-tools/29.0.3/aapt.

### ISSUE THREAD

**Issue by satosh205** [flutter/flutter#58662]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=52109025b485a385 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/sushil/Library/Android/sdk/build-tools/29.0.3/aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:417:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:361:31)
#8      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:518:23)
#9      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:580:26)
#10     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:578:38)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
#13     _rootRun (dart:async/zone.dart:1184:13)
#14     _CustomZone.run (dart:async/zone.dart:1077:19)
#15     _runZoned (dart:async/zone.dart:1619:10)
#16     runZoned (dart:async/zone.dart:1539:10)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
```
```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.2 at /Users/sushil/Documents/flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sushil/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/sushil/Library/Android/sdk
    ✗ Android SDK file not found: /Users/sushil/Library/Android/sdk/build-tools/29.0.3/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • SM G610F                  • 52109025b485a385                     • android-arm • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone 11 Pro             • 1CAAF3EC-B252-4FFE-8DA4-4744653ECA9D • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
android_intent-0.3.7+2
assets_audio_player-1.7.0
contacts_service-0.3.10
device_id-0.2.0
device_info-0.4.2+4
firebase_auth-0.11.1+12
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
flutter_share-1.0.2+1
fluttertoast-4.0.1
path_provider-1.6.10
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3
permission_handler-4.4.0+hotfix.4
share-0.6.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sms-0.2.4
sms_autofill-1.2.1
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/54418

**Comment by nb312** [comment]
I have the same error:
`
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --verbose --track-widget-creation --device-id=64ce9508 --flavor=developer lib/main_debug.dart

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/niebin/Library/Android/sdk/build-tools/29.0.2/aapt.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#12     _rootRun (dart:async/zone.dart:1184:13)
#13     _CustomZone.run (dart:async/zone.dart:1077:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
    • Flutter version 1.17.0-3.2.pre at /Users/niebin/Tools/flutter
    • Framework revision 2a7bc389f2 (7 weeks ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/niebin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    ✗ Android SDK file not found: /Users/niebin/Library/Android/sdk/build-tools/29.0.2/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M362v
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (3 available)
    • MIX 2      • 64ce9508   • android-arm64  • Android 8.0.0 (API 26)
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

`

**Comment by charleshan** [comment]
This was happening for me as well. Here's something you can try: Reinstall the specific version of the build tool using SDK Tools Manager.

**Comment by pedromassangocode** [comment]
Hi @satosh205 
I see there's an open issue (https://github.com/flutter/flutter/issues/54418) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
