### ISSUE TITLE
flutter_gallery__back_button_memory is flaky

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#58691]
We need to fix the flakiness or delete the test if it is no longer relevant.

Broken out from #58338 /cc @Hixie

**Comment by gspencergoog** [comment]
Investigtating some of the failures, it seems like sending a key event via ADB is causing the soft keyboard to crash:
```
2020-06-04T10:45:52.818025: "/home/flutter/Android/Sdk/platform-tools/adb" exit code: 0
2020-06-04T10:45:52.820064: back/forward iteration 0
2020-06-04T10:45:52.820995: 
Executing: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ45 shell input keyevent KEYCODE_BACK in /home/flutter/.cocoon/flutter/dev/integration_tests/flutter_gallery
>>> 2020-06-04T10:45:53.657356: adb logcat: 06-04 10:44:27.494 14057 15087 I ActivityManager: Killing 1286:com.google.android.inputmethod.latin/u0a101 (adj 200): crash
2020-06-04T10:45:53.690318: "/home/flutter/Android/Sdk/platform-tools/adb" exit code: 0
2020-06-04T10:46:01.354888: adb logcat: 06-04 10:44:35.193 14057 14599 I ActivityManager: Killing 32304:com.android.chrome/u0a78 (adj 906): empty #13
2020-06-04T10:46:05.778122: adb logcat: 06-04 10:44:39.616 14057 15055 I ActivityManager: Killing 1106:com.android.providers.calendar/u0a15 (adj 906): empty #13
2020-06-04T10:46:21.303304: adb logcat: 06-04 10:44:55.140 14057 14081 I ActivityManager: Killing 1123:com.google.android.calendar/u0a75 (adj 906): empty #13
2020-06-04T10:59:40.039307: Task timed out in framework.dart after 0:15:00.000000.
TimeoutException after 0:15:00.000000: Future not completed
```

**Comment by gspencergoog** [comment]
Strange, it looks like the failure has something to do with the LatinIME using `java.nio.file.Paths`, and that not existing in the classpath.

<details>
<pre>
2020-06-03T22:16:31.229969: adb logcat: 06-03 22:15:55.137 20701 20847 I ActivityManager: Start proc 22793:com.google.android.inputmethod.latin/u0a94 for service com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
2020-06-03T22:16:31.890981: adb logcat: --------- beginning of crash
2020-06-03T22:16:31.900142: stdout: [ +741 ms] E/AndroidRuntime(22793): FATAL EXCEPTION: main
2020-06-03T22:16:31.900748: stdout: [        ] E/AndroidRuntime(22793): Process: com.google.android.inputmethod.latin, PID: 22793
2020-06-03T22:16:31.901308: stdout: [        ] E/AndroidRuntime(22793): java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
2020-06-03T22:16:31.901933: stdout: [        ] E/AndroidRuntime(22793): 	at efg.<init>(PG:4)
2020-06-03T22:16:31.902436: stdout: [        ] E/AndroidRuntime(22793): 	at eem.a(PG:4)
2020-06-03T22:16:31.903235: stdout: [        ] E/AndroidRuntime(22793): 	at efb.<init>(PG:9)
2020-06-03T22:16:31.903883: stdout: [        ] E/AndroidRuntime(22793): 	at eem.<init>(PG:1)
2020-06-03T22:16:31.904375: stdout: [        ] E/AndroidRuntime(22793): 	at efc.<init>(PG:10)
2020-06-03T22:16:31.905031: stdout: [        ] E/AndroidRuntime(22793): 	at efc.a(PG:16)
2020-06-03T22:16:31.905480: stdout: [        ] E/AndroidRuntime(22793): 	at com.google.android.apps.inputmethod.libs.handwriting.ime.HandwritingImeExtension.a(PG:4)
2020-06-03T22:16:31.906287: stdout: [        ] E/AndroidRuntime(22793): 	at khy.b(PG:15)
2020-06-03T22:16:31.906969: stdout: [        ] E/AndroidRuntime(22793): 	at khy.a(PG:29)
2020-06-03T22:16:31.909903: stdout: [        ] E/AndroidRuntime(22793): 	at kih.a(PG:100)
stdout: [        ] E/AndroidRuntime(22793): 	at kig.b(PG:10)
stdout: [        ] E/AndroidRuntime(22793): 	at kia.run(PG:2)
stdout: [        ] E/AndroidRuntime(22793): 	at kjt.d(PG:7)
2020-06-03T22:16:31.910443: stdout: [        ] E/AndroidRuntime(22793): 	at kjw.b(PG:8)
2020-06-03T22:16:31.910865: stdout: [        ] E/AndroidRuntime(22793): 	at kjs.a(PG:10)
2020-06-03T22:16:31.911309: stdout: [        ] E/AndroidRuntime(22793): 	at kjs.a(PG:11)
2020-06-03T22:16:31.912247: stdout: [        ] E/AndroidRuntime(22793): 	at kke.run(PG:7)
2020-06-03T22:16:31.912672: stdout: [        ] E/AndroidRuntime(22793): 	at android.os.Handler.handleCallback(Handler.java:751)
2020-06-03T22:16:31.914273: stdout: [        ] E/AndroidRuntime(22793): 	at android.os.Handler.dispatchMessage(Handler.java:95)
stdout: [        ] E/AndroidRuntime(22793): 	at android.os.Looper.loop(Looper.java:154)
2020-06-03T22:16:31.914468: stdout: [        ] E/AndroidRuntime(22793): 	at android.app.ActivityThread.main(ActivityThread.java:6123)
2020-06-03T22:16:31.915488: stdout: [        ] E/AndroidRuntime(22793): 	at java.lang.reflect.Method.invoke(Native Method)
stdout: [        ] E/AndroidRuntime(22793): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
2020-06-03T22:16:31.916391: stdout: [        ] E/AndroidRuntime(22793): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
2020-06-03T22:16:31.916713: stdout: [        ] E/AndroidRuntime(22793): Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList[[zip file "/data/app/com.google.android.inputmethod.latin-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.inputmethod.latin-1/lib/arm, /data/app/com.google.android.inputmethod.latin-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2020-06-03T22:16:31.917555: stdout: [        ] E/AndroidRuntime(22793): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
2020-06-03T22:16:31.917900: stdout: [        ] E/AndroidRuntime(22793): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
2020-06-03T22:16:31.918617: stdout: [        ] E/AndroidRuntime(22793): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-06-03T22:16:31.918913: stdout: [        ] E/AndroidRuntime(22793): 	... 24 more
</pre>
</details>

**Comment by gspencergoog** [comment]
`java.nio.file.Paths` isn't available on Android until API level 26 (Oreo), but I think that is what is on the devicelab machines.

**Comment by gspencergoog** [comment]
I wonder if re-installing (or removing) the HandwritingImeExtension on the devices would solve this problem.  It seems to happen when trying to initialize that extension (or at least that extension is in all of the crash stack traces I've seen so far).

Or maybe we just need to reinstall/update GBoard?

**Comment by gspencergoog** [comment]
Of the last 43 log files and 154 tests, out of seven different devices, the test always passed on two of the devices. On the other five, it failed every time.

My guess is that there is some configuration problem on the devices that fail. Either the OS is out of date, or GBoard is the wrong version, or something.

The Serial numbers of the devices where the tests always pass:
 - ZY223D6B7B
 - ZY22465WKN

The Serial numbers of the devices where the tests always fail:
 - ZY22465W9K
 - ZY223TDZ45
 - ZY223D5F28
 - ZY2238CGGC
 - ZY223TDZ7R

@godofredoc, is there any way to tell what the differences between these devices are?

**Comment by goderbauer** [comment]
I've made a similar observation in https://github.com/flutter/flutter/issues/58690. Are devices ZY22465WKN and ZY223D6B7B connected to bots flutter-devicelab-linux-1 and flutter-devicelab-linux-4?

**Comment by gspencergoog** [comment]
Yes, that's what they're connected to.

My analysis of the log files comes up with this count of crashes:

 - flutter-devicelab-linux-1 (ZY223D6B7B): 0
 - flutter-devicelab-linux-2 (ZY223TDZ45): 11
 - flutter-devicelab-linux-3 (ZY22465W9K): 14
 - flutter-devicelab-linux-4 (ZY22465WKN): 0
 - flutter-devicelab-linux-5 (ZY223TDZ7R): 5
 - flutter-devicelab-linux-6 (ZY223D5F28): 15
 - flutter-devicelab-linux-7 (ZY2238CGGC): 4

So, the two flaky tests (this one and #58690) are similar in that they fail on the same devices with the same cause (a crash in `com.google.android.inputmethod.latin`, a.k.a. GBoard).

I was able to determine that the devices that crash have the package `com.google.android.apps.inputmethod.latin.ImeLatinApp` installed, and the devices that don't crash don't have it installed.

**Comment by gspencergoog** [comment]
Also, the passing devices have GBoard version v24511808, and the failing devices have v26891113

**Comment by godofredoc** [comment]
@gspencergoog Is this something we'll try to fix at the test level or something will require to try to force the same versions on the devices?

**Comment by gspencergoog** [comment]
I think we have to force the same versions on the devices: the test isn't doing anything other than running `adb shell input keyevent KEYCODE_BACK` on the device, so it's not doing anything strange, and the test is exactly to test that there isn't a memory leak when the back button is pressed, so we can't skip that step.

**Comment by gspencergoog** [comment]
OK, I've reinstalled the latest version of GBoard available for our device on linux-2's device (GBoard v26941125). Now I just need to figure out how to get the test to run on that device... Of course, the problem is that the version that works is the _earlier_ version of the app, so there's no guarantee that this newest version will work any better than the one that was there before (v26891113).

**Comment by Hixie** [comment]
Do we have any idea why the new GBoard fails? Is it something that makes sense to report to the team?

**Comment by gspencergoog** [comment]
It's not the latest Gboard that fails, it's just a newer one than the one that succeeded. In order to fix things, I upgraded to the latest release. Also, @goderbauer found what we think is a bug report for this that the team fixed, which is probably why the latest version works.

**Comment by Hixie** [comment]
Ah ok, excellent news. Thanks!
