### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = '/home/althea/Documents/FlutterProjects/shop/.packages' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by murprakoso** [flutter/flutter#58782]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = '/home/althea/Documents/FlutterProjects/shop/.packages' (OS Error: Operation not permitted, errno = 1)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:213:19)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:706:17)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel stable, v1.17.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.2 at /usr/lib/flutter
    • Framework revision 5f21edf8b6 (8 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • Redmi Note 5 • 43b0ede0 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5f21edf8b66e31a39133177319414395cc5b5f48

**Comment by zanderso** [comment]
Fixed on master by https://github.com/flutter/flutter/pull/57077
