### ISSUE TITLE
[cocoon] Flaky test in cocoon pre-submit runs of app_flutter

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#58833]
Have been seeing this error now and then for couple of times. such as https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8878298302027573632/+/steps/app_flutter/0/stdout?format=raw
```
The following TestFailure object was thrown running a test:
  Expected: one widget whose rasterized image matches golden image
"task_overlay_test.nondevicelab_closed.png"
  Actual: _WidgetTypeFinder:<exactly one widget with type "MaterialApp" (ignoring offstage widgets):
MaterialApp(state: _MaterialAppState#7f2ae)>
   Which: Golden "task_overlay_test.nondevicelab_closed.png": Pixel test failed, 0.05% diff
detected.
          Failure feedback can be found at /b/s/w/ir/k/cocoon/app_flutter/test/widgets/failures

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:154:30)
#1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:128:9)
#13     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
<asynchronous suspension>
#14     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
#15     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:921:22)
#18     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:919:26)
#19     MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#20     _expect (package:test_api/src/frontend/expect.dart:117:26)
#21     expectLater (package:test_api/src/frontend/expect.dart:76:5)
#22     expectLater (package:flutter_test/src/widget_tester.dart:406:10)
#23     main.<anonymous closure> (file:///b/s/w/ir/k/cocoon/app_flutter/test/widgets/task_overlay_test.dart:252:11)
#34     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:192:32)
#35     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1102:19)
(elided 35 frames from dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  TaskOverlay shows the right message for nondevicelab tasks
```

**Comment by CaseyHillers** [comment]
```
~/cocoon/app_flutter$ flutter test
Running "flutter pub get" in app_flutter...                         1.8s
00:16 +165: All tests passed!                                                                                                                                                                                                                                                                                                                                                             
~/cocoon/app_flutter$ flutter test --test-randomize-ordering-seed=1793925245
Shuffling test order with --test-randomize-ordering-seed=1793925245
00:13 +153: /usr/local/google/home/chillers/cocoon/app_flutter/test/widgets/task_overlay_test.dart: TaskOverlay shows the right message for nondevicelab tasks                                                                                                                                                                                                                            
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: one widget whose rasterized image matches golden image
"task_overlay_test.nondevicelab_closed.png"
  Actual: _WidgetTypeFinder:<exactly one widget with type "MaterialApp" (ignoring offstage widgets):
MaterialApp(state: _MaterialAppState#558f0)>
   Which: Golden "task_overlay_test.nondevicelab_closed.png": Pixel test failed, 0.05% diff
detected.
          Failure feedback can be found at
/usr/local/google/home/chillers/cocoon/app_flutter/test/widgets/failures

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:154:30)
#1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:128:9)
#13     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
<asynchronous suspension>
#14     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
#15     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:957:22)
#18     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:955:26)
#19     MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#20     _expect (package:test_api/src/frontend/expect.dart:117:26)
#21     expectLater (package:test_api/src/frontend/expect.dart:76:5)
#22     expectLater (package:flutter_test/src/widget_tester.dart:406:10)
#23     main.<anonymous closure> (file:///usr/local/google/home/chillers/cocoon/app_flutter/test/widgets/task_overlay_test.dart:252:11)
#34     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:192:32)
#35     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1138:19)
(elided 35 frames from dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  TaskOverlay shows the right message for nondevicelab tasks
════════════════════════════════════════════════════════════════════════════════════════════════════
00:13 +153 -1: /usr/local/google/home/chillers/cocoon/app_flutter/test/widgets/task_overlay_test.dart: TaskOverlay shows the right message for nondevicelab tasks [E]                                                                                                                                                                                                                     
  Test failed. See exception logs above.
  The test description was: TaskOverlay shows the right message for nondevicelab tasks
  
00:17 +164 -1: Some tests failed.                                           
```
Seems to be an issue with tests modifying global state and not cleaning up afterwards.

**Comment by CaseyHillers** [comment]
![image](https://user-images.githubusercontent.com/2148558/83928734-99044f80-a745-11ea-85d5-1e0dca50ea18.png)

From a high level, it seems like the cirrus icon is using the dark mode filter when the test flakes whereas the test expects no filter.

This test doesn't require the task icons, and just needs one task box. To fix it, we could just refactor so the tester only pumps a single task box.

**Comment by CaseyHillers** [comment]
This test specifically tests how the render widgets are looking up and passing data for the task overlay. It does need the grid, which shows TaskIcons. 

Because of this, I think the solution is to find why it flakes and to fix that issue.
