### ISSUE TITLE
com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect

### ISSUE THREAD

**Issue by mrhmamun** [flutter/flutter#58916]
I tried this #19588, [this](https://stackoverflow.com/questions/59588918/exoplayer-player-error-unable-to-connect-to-hls-link)
This [link ](http://server-23.stream-server.nl:8438) playing well, error showing on this [link](https://whsh4u-panel.com/proxy/xegagooy?mp=/live) that I want to play.

## Steps to Reproduce

#Main streak
```
Launching lib/main.dart on P9 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device P9...
D/GraphicBuffer(22895): register, handle(0x7e889d1800) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
D/GraphicBuffer(22895): register, handle(0x7e88d2f440) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
D/GraphicBuffer(22895): register, handle(0x7e83f0b040) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
I/art     (22895): Enter while loop.
I/art     (22895): After futex lock.
D/MPlugin (22895): com.mediatek.common.telephony.IOnlyOwnerSimSupportClazz exists on mapping table : false
E/MPlugin (22895): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
I/ExoPlayerImpl(22895): Init e5070b2 [ExoPlayerLib/2.11.4] [P9, P9, Symphony, 24]
D/NetworkSecurityConfig(22895): No Network Security Config specified, using platform default
D/libc-netbsd(22895): getaddrinfo: whsh4u-panel.com get result from proxy gai_error = 0
I/System.out(22895): [socket][0] connection whsh4u-panel.com/5.9.140.203:443;LocalPort=-1(8000)
D/        (22895): [Posix_connect Debug]Process com.justhabbo.justhabbo_fm :443 
I/System.out(22895): [socket][/192.168.1.101:58688] connected
D/NativeCrypto(22895): ssl=0x7ea5057f80 NativeCrypto_SSL_do_handshake fd=0x7e83dfc858 shc=0x7e83dfc85c timeout_millis=8000 client_mode=1 npn=0x0
D/NativeCrypto(22895): ssl=0x7ea5057f80 info_callback calling handshakeCompleted
D/NativeCrypto(22895): ssl=0x7ea5057f80 cert_verify_callback => 0
D/OpenSSLLib(22895): OpensslErr:Module:16(125:); file:external/boringssl/src/ssl/s3_clnt.c ;Line:2089;Function:ssl3_verify_server_cert
D/NativeCrypto(22895): ssl=0x7ea5057f80 NativeCrypto_SSL_do_handshake exception => 0
I/System.out(22895): close [socket][/192.168.1.101:58688]
I/System.out(22895): [socket][1] connection whsh4u-panel.com/5.9.140.203:443;LocalPort=-1(8000)
D/        (22895): [Posix_connect Debug]Process com.justhabbo.justhabbo_fm :443 
I/System.out(22895): [socket][/192.168.1.101:58689] connected
D/NativeCrypto(22895): ssl=0x7ea5057f80 NativeCrypto_SSL_do_handshake fd=0x7e83dfc858 shc=0x7e83dfc85c timeout_millis=8000 client_mode=1 npn=0x0
D/NativeCrypto(22895): ssl=0x7ea5057f80 info_callback calling handshakeCompleted
D/NativeCrypto(22895): ssl=0x7ea5057f80 cert_verify_callback => 0
D/OpenSSLLib(22895): OpensslErr:Module:16(125:); file:external/boringssl/src/ssl/s3_clnt.c ;Line:2089;Function:ssl3_verify_server_cert
D/NativeCrypto(22895): ssl=0x7ea5057f80 NativeCrypto_SSL_do_handshake exception => 0
I/System.out(22895): close [socket][/192.168.1.101:58689]
I/System.out(22895): [socket][2] connection whsh4u-panel.com/5.9.140.203:443;LocalPort=-1(8000)
D/        (22895): [Posix_connect Debug]Process com.justhabbo.justhabbo_fm :443 
I/System.out(22895): [socket][/192.168.1.101:58690] connected
D/NativeCrypto(22895): ssl=0x7ea5057f80 NativeCrypto_SSL_do_handshake fd=0x7e83dfc858 shc=0x7e83dfc85c timeout_millis=8000 client_mode=1 npn=0x0
D/NativeCrypto(22895): ssl=0x7ea5057f80 info_callback calling handshakeCompleted
D/NativeCrypto(22895): ssl=0x7ea5057f80 cert_verify_callback => 0
D/OpenSSLLib(22895): OpensslErr:Module:16(125:); file:external/boringssl/src/ssl/s3_clnt.c ;Line:2089;Function:ssl3_verify_server_cert
D/NativeCrypto(22895): ssl=0x7ea5057f80 NativeCrypto_SSL_do_handshake exception => 0
I/System.out(22895): close [socket][/192.168.1.101:58690]
D/libc-netbsd(22895): getaddrinfo: whsh4u-panel.com get result from proxy gai_error = 0
I/System.out(22895): [socket][3] connection whsh4u-panel.com/5.9.140.203:443;LocalPort=-1(8000)
D/        (22895): [Posix_connect Debug]Process com.justhabbo.justhabbo_fm :443 
I/System.out(22895): [socket][/192.168.1.101:58691] connected
D/NativeCrypto(22895): ssl=0x7ea5057f80 NativeCrypto_SSL_do_handshake fd=0x7e83dfc858 shc=0x7e83dfc85c timeout_millis=8000 client_mode=1 npn=0x0
D/NativeCrypto(22895): ssl=0x7ea5057f80 info_callback calling handshakeCompleted
D/NativeCrypto(22895): ssl=0x7ea5057f80 cert_verify_callback => 0
D/OpenSSLLib(22895): OpensslErr:Module:16(125:); file:external/boringssl/src/ssl/s3_clnt.c ;Line:2089;Function:ssl3_verify_server_cert
D/NativeCrypto(22895): ssl=0x7ea5057f80 NativeCrypto_SSL_do_handshake exception => 0
I/System.out(22895): close [socket][/192.168.1.101:58691]
E/ExoPlayerImplInternal(22895): Source error
E/ExoPlayerImplInternal(22895):   com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal(22895):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:282)
E/ExoPlayerImplInternal(22895):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
E/ExoPlayerImplInternal(22895):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(22895):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
E/ExoPlayerImplInternal(22895):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal(22895):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/ExoPlayerImplInternal(22895):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/ExoPlayerImplInternal(22895):       at java.lang.Thread.run(Thread.java:761)
E/ExoPlayerImplInternal(22895):   Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:366)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.Connection.connectTls(Connection.java:260)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.Connection.connectSocket(Connection.java:224)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.Connection.connect(Connection.java:197)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:392)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:356)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
E/ExoPlayerImplInternal(22895):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
E/ExoPlayerImplInternal(22895):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:550)
E/ExoPlayerImplInternal(22895):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:454)
E/ExoPlayerImplInternal(22895):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:280)
E/ExoPlayerImplInternal(22895):       ... 7 more
E/ExoPlayerImplInternal(22895):   Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
E/ExoPlayerImplInternal(22895):       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
E/ExoPlayerImplInternal(22895):       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:611)
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/ExoPlayerImplInternal(22895):       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:362)
E/ExoPlayerImplInternal(22895):       ... 21 more
E/ExoPlayerImplInternal(22895):   Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(22895):       ... 31 more
E/AudioPlayer(22895): TYPE_SOURCE: Unable to connect
I/flutter (22895): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
I/art     (22895): Enter while loop.
I/art     (22895): Enter while loop.
I/art     (22895): Enter while loop.
I/art     (22895): Enter while loop.
I/art     (22895): Enter while loop.
I/art     (22895): Enter while loop.
D/SurfaceView(22895): 176954403 windowPositionLostRT RT, frameNr = 0`

```

**flutter doctor -v**

```
[✓] Flutter (Channel master, v1.18.1-pre.9, on Mac OS X 10.15.1 19B88, locale en-BD)
    • Flutter version 1.18.1-pre.9 at /Users/mamun/Developer/flutter
    • Framework revision 17079f26b5 (9 weeks ago), 2020-04-06 01:21:01 -0400
    • Engine revision 9b8dcc7ecf
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 05103dfe5a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mamun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • P9         • P9170526000200 • android-arm64  • Android 7.0 (API 24)
    • Chrome     • chrome         • web-javascript • Google Chrome 83.0.4103.97
    • Web Server • web-server     • web-javascript • Flutter Tools

• No issues found!
````
**main.dart**

```
class MyHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext context){
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  }
}

void main(){
  HttpOverrides.global = new MyHttpOverrides();
  runApp(new MyApp());
}
`

`class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {

  final String url = 'https://whsh4u-panel.com/proxy/xegagooy?mp=/live';
//#final String url = 'http://server-23.stream-server.nl:8438';



  AudioPlayer _player;
  @override
  void initState() {
    super.initState();
    _player = AudioPlayer();

    _player.setUrl(url)
        .catchError((error) {
      // catch audio error ex: 404 url, wrong url ...
      print(error);
    });
  }

  @override
  void dispose() {
    _player.dispose();
    super.dispose();
  }





  FlatButton headerBtn({Function onPressed, String text}) {
    return FlatButton(
        onPressed: onPressed,
        child: Text(
          text,
          style: TextStyle(
              color: Colors.white, fontWeight: FontWeight.bold, fontSize: 15),
        ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xFF00BBDC),
      appBar: AppBar(
        backgroundColor: Color(0xFF414141),
        leading: Container(),
        actions: [
          headerBtn(
            text: 'Home',
            onPressed: null,
          ),
          headerBtn(
            text: 'About',
            onPressed: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (_) => About()));
            },
          ),
          headerBtn(
            text: 'Version',
            onPressed: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (_) => AppUpdates()));
            },
          ),
          headerBtn(
            text: 'More',
            onPressed: () {
              Navigator.push(context,
                  MaterialPageRoute(builder: (_) => More()));
            },
          ),
        ],
      ),
      body: ListView(
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 50),
            child: Column(
              children: [
                Stack(
                  children: [
                    Container(
                      height: MediaQuery.of(context).size.height * .4,
                      decoration: BoxDecoration(
                        color: const Color(0xff7c94b6),
                        image: const DecorationImage(
                          image: AssetImage('assets/images/paris.png'),
                          fit: BoxFit.cover,
                        ),
                        border: Border.all(
                          color: Colors.white,
                          width: 5,
                        ),
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    Positioned.fill(
                      child: Align(
                        alignment: Alignment.center,
                        child: Text(
                          'JustHabbo',
                          textAlign: TextAlign.center,
                          style: GoogleFonts.passionOne(
                              textStyle: TextStyle(
                                  shadows: [
                                    Shadow(
                                      color: Colors.blue.shade900.withOpacity(1.0),
                                      offset: Offset(5.0, 5.0),
                                      blurRadius: 4.0,
                                    ),
                                  ],
                                  fontSize: 50,
                                  color: Colors.white,
                                  fontWeight: FontWeight.bold)),
                        ),
                      ),
                    )
                  ],
                ),
              StreamBuilder<FullAudioPlaybackState>(
                 stream: _player.fullPlaybackStateStream,
                 builder: (context, snapshot) {
                   final fullState = snapshot.data;
                   final state = fullState?.state;
                   final buffering = fullState?.buffering;
                   return Row(
                     mainAxisSize: MainAxisSize.min,
                     children: [
                       if (state == AudioPlaybackState.connecting ||
                           buffering == true)
                         Container(
                           margin: EdgeInsets.all(8.0),
                           width: 64.0,
                           height: 64.0,
                           child: CircularProgressIndicator(),
                         )
                       else if (state == AudioPlaybackState.playing)
                         IconButton(
                           icon: Icon(Icons.pause_circle_outline,color: Colors.white,),
                           iconSize: 80.0,
                           onPressed: _player.pause,
                         )
                       else
                         IconButton(
                           icon: Icon(Icons.play_circle_filled,color: Colors.white,),
                           iconSize: 80.0,
                           onPressed: _player.play,
                         ),
                     ],
                   );
                 },
               ),
              ],
            ),
          ),
        ],
      ),
      bottomNavigationBar: bottomInfoBar(),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Hi @mrhmamun 
Can you please try to reproduce this issue without using 3rd party package like network image https?

Otherwise,
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rxlabz/audioplayer/issues).
Thank you

**Comment by mrhmamun** [comment]
@TahaTesser I bypass certificate by adding a self-signed certificate manually, though it's risky.
