### ISSUE TITLE
[web]: flutter compiler started failing with "The getter 'fileOffset' was called on null."

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#58932]
Flutter compiler started failing when I run 'flutter run -d chrome', on iOS.
I did not change my environment and did not upgrade flutter. It happened out of the blue.
I tried to run another application that worked before and got the same error.

I created new app from scratch following [get started](https://flutter.dev/docs/get-started/web) and got the sam error.

Error in Android Studio:
```
Launching lib/main.dart on Web Server in debug mode...
Syncing files to device Web Server...
Unhandled exception:
NoSuchMethodError: The getter 'fileOffset' was called on null.
Receiver: null
Tried calling: fileOffset
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ProgramCompiler._nodeStart (package:dev_compiler/src/kernel/compiler.dart:3341:30)
#2      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1401:45)
#3      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1355:19)
#4      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:3122:24)
#5      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1354:15)
#6      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2096:25)
#7      ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3112:18)
#8      ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1352:16)
#9      ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:972:38)
#10     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:567:19)
#11     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:510:21)
#12     List.forEach (dart:core-patch/growable_array.dart:282:8)
#13     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:459:23)
#14     List.forEach (dart:core-patch/growable_array.dart:282:8)
#15     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:345:15)
#16     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:133:33)
<asynchronous suspension>
#17     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:627:20)
<asynchronous suspension>
#18     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:533:15)
<asynchronous suspension>
#19     _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#20     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1164:26)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#37     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#38     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:315:20)
#39     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:308:5)
#40     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#46     _StreamController._add (dart:async/stream_controller.dart:655:7)
#47     _StreamController.add (dart:async/stream_controller.dart:597:5)
#48     _Socket._onData (dart:io-patch/socket_patch.dart:1999:41)
#49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#53     _StreamController._add (dart:async/stream_controller.dart:655:7)
#54     _StreamController.add (dart:async/stream_controller.dart:597:5)
#55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1544:33)
#56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1036:14)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.
```

Error in console:
```
Running "flutter pub get" in example2...                            1.4s
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
Unhandled exception:                                            
NoSuchMethodError: The getter 'fileOffset' was called on null.                                                     
Receiver: null                                                                                                     
Tried calling: fileOffset                                                                                          
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)                                               
#1      ProgramCompiler._nodeStart (package:dev_compiler/src/kernel/compiler.dart:3341:30)                         
#2      ProgramCompiler._emitConstructorBody (package:dev_compiler/src/kernel/compiler.dart:1401:45)               
#3      ProgramCompiler._emitConstructor.<anonymous closure>.<anonymous closure>                                   
(package:dev_compiler/src/kernel/compiler.dart:1355:19)
#4      ProgramCompiler._superDisallowed (package:dev_compiler/src/kernel/compiler.dart:3122:24)                   
#5      ProgramCompiler._emitConstructor.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:1354:15)
#6      ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2096:25)                      
#7      ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3112:18)               
#8      ProgramCompiler._emitConstructor (package:dev_compiler/src/kernel/compiler.dart:1352:16)                   
#9      ProgramCompiler._defineConstructors (package:dev_compiler/src/kernel/compiler.dart:972:38)                 
#10     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:567:19)               
#11     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:510:21)                          
#12     List.forEach (dart:core-patch/growable_array.dart:282:8)                                                   
#13     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:459:23)                        
#14     List.forEach (dart:core-patch/growable_array.dart:282:8)                                                   
#15     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:345:15)                          
#16     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:133:33)                      
<asynchronous suspension>                                                                                          
#17     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:627:20)               
<asynchronous suspension>                                                                                          
#18     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:533:15)                             
<asynchronous suspension>                                                                                          
#19     _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)                       
#20     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1164:26)                
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)                                                   
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)                                
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)                                      
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)                        
#25     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)                                          
#26     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)                                        
#27     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)                                       
#28     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)                                         
#29     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)                                  
#30     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)                
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)                                                   
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)                                
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)                                      
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)                        
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)                                          
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)                                        
#37     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)                                    
#38     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:315:20)                                  
#39     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:308:5)                                        
#40     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)                                 
#41     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)                
#42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)                                                   
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)                                
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)                                      
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)                         
#46     _StreamController._add (dart:async/stream_controller.dart:655:7)                                           
#47     _StreamController.add (dart:async/stream_controller.dart:597:5)                                            
#48     _Socket._onData (dart:io-patch/socket_patch.dart:1999:41)                                                  
#49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)                                                   
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)                                
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)                                      
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)                         
#53     _StreamController._add (dart:async/stream_controller.dart:655:7)                                           
#54     _StreamController.add (dart:async/stream_controller.dart:597:5)                                            
#55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1544:33)                               
#56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1036:14)                               
#57     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)                                                  
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)                                              
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)                                
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)                           
the Dart compiler exited unexpectedly.                                                                             
Syncing files to device Chrome...                               10,909ms (!)                                       
Failed to compile application.
```

**Comment by polina-c** [comment]
Reinstallation of SDK helped. Closing.
