### ISSUE TITLE
Downloading package sky_engine... Could not authenticate download server.

### ISSUE THREAD

**Issue by RyanDrx** [flutter/flutter#58940]
**Running `flutter doctor -v`** 

Shows this error: 

```
Downloading package sky_engine...
Could not authenticate download server. You may be experiencing a man-in-the-middle attack,
your network may be compromised, or you may have malware installed on your computer.
URL: https://storage.googleapis.com/flutter_infra/flutter/ee76268252c22f5c11e82a7b87423ca3982e51a7/sky_engine.zip

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      Net._attempt (package:flutter_tools/src/base/net.dart:126:7)
<asynchronous suspension>
#2      Net.fetchUrl (package:flutter_tools/src/base/net.dart:63:33)
#3      Cache.downloadFile (package:flutter_tools/src/cache.dart:466:16)
#4      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:608:23)
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:604:55)
#6      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:638:26)
#7      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#8      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:625:12)
#9      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:753:13)
#10     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:698:27)
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#21     _rootRun (dart:async/zone.dart:1184:13)
#22     _CustomZone.run (dart:async/zone.dart:1077:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by RyanDrx** [comment]
I am in the USA, not Bangladesh or China.

**Comment by TahaTesser** [comment]
Hi @RyanDrx 
Can you please post the result of the following command?
```
curl -I https://storage.googleapis.com/flutter_infra/flutter/ee76268252c22f5c11e82a7b87423ca3982e51a7/sky_engine.zip
```

Also can you please provide  **complete** `flutter doctor -v` result
Thank you

**Comment by RyanDrx** [comment]
> Hi @RyanDrx
> Can you please post the result of the following command?
> 
> ```
> curl -I https://storage.googleapis.com/flutter_infra/flutter/ee76268252c22f5c11e82a7b87423ca3982e51a7/sky_engine.zip
> ```
> 
> Also can you please provide **complete** `flutter doctor -v` result
> Thank you

The error in the message is the result of running `flutter doctor -v`

**Comment by RyanDrx** [comment]
> Hi @RyanDrx
> Can you please post the result of the following command?
> 
> ```
> curl -I https://storage.googleapis.com/flutter_infra/flutter/ee76268252c22f5c11e82a7b87423ca3982e51a7/sky_engine.zip
> ```
> 
> Also can you please provide **complete** `flutter doctor -v` result
> Thank you

Output of running curl

```
sky_engine.zip
HTTP/1.1 200 OK
X-GUploader-UploadID: AAANsUkoC4Qf-tzF1ZkhtEFXk3xOf1Pd1aniAb-iR2kNeD40RnnJ_zbd-lBz3BSNaYYN-WF0UpEBz3kVuw1z_k0uy9Y
Expires: Mon, 08 Jun 2020 16:36:44 GMT
Date: Mon, 08 Jun 2020 15:36:44 GMT
Cache-Control: public, max-age=3600
Last-Modified: Wed, 03 Jun 2020 22:43:02 GMT
ETag: "790b631d4bae523438500f9ed564e81e"
x-goog-generation: 1591224182667092
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 1153751
Content-Type: application/zip
x-goog-hash: crc32c=0ZF/7Q==
x-goog-hash: md5=eQtjHUuuUjQ4UA+e1WToHg==
x-goog-storage-class: STANDARD
Accept-Ranges: bytes
Content-Length: 1153751
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type
Server: UploadServer
Alt-Svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

**Comment by TahaTesser** [comment]
Hi @RyanDrx 
Thank you for this
Can you please provide complete `flutter doctor -v` result? just paste complete, which flutter version you have dwnloaded?
Thank you

**Comment by TahaTesser** [comment]
Hi @RyanDrx 
Glad you resolved the issue
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by tomkmangattu** [comment]
I used hotspot of my mobile the same problem occurred I restarted my divice and problem is solved
