### ISSUE TITLE
Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable. (Can't Find Solution in previous answers)

### ISSUE THREAD

**Issue by henryandersen** [flutter/flutter#58960]
## Steps to Reproduce

1. I had android studio and Xcode installed previously
2. When I delete android studio I can run the flutter app on iOS emulator
3. When android studio is installed I get this error

## Logs

```
flutter doctor -v
```

```
 [✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.3 at /Users/henryandersen/flutter
    • Framework revision b041144f83 (4 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/henryandersen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/henryandersen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this
      issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      /Users/henryandersen/Library/Android/sdk/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:62:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:321:52)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:311:12)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:152:20)
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:926:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1184:13)
      #8      _CustomZone.run (dart:async/zone.dart:1077:19)
      #9      _runZoned (dart:async/zone.dart:1619:10)
      #10     runZonedGuarded (dart:async/zone.dart:1608:12)
      #11     runZoned (dart:async/zone.dart:1536:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:172:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:271:47)
      #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:60:39)
      #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
      #17     _rootRunUnary (dart:async/zone.dart:1192:38)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
      #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
      #23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
      #24     _rootRun (dart:async/zone.dart:1184:13)
      #25     _CustomZone.run (dart:async/zone.dart:1077:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

I tried to fix this by redownloading platform-tools, no luck.
I also tried to set ANDROID_HOME environment variable with this in my .zshrc: 
```
export PATH="$PATH:/Users/henryandersen/Library/Android/sdk/platform-tools"
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH=/Users/henryandersen/flutter/bin:$PATH
```

I would appreciate any help

**Comment by henryandersen** [comment]
I dont believe this is a repeat because https://github.com/flutter/flutter/issues/54469 and https://github.com/flutter/flutter/issues/30772 do not have a solution that works for me

**Comment by VladyslavBondarenko** [comment]
Hi @henryandersen 
please follow up on https://github.com/flutter/flutter/issues/55267,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it
