### ISSUE TITLE
Cannot use coroutines in method call handlers (in kotlin)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#59024]
```kotlin
package com.damowmow.gc

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import kotlinx.coroutines.*

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "gc.damowmow.com/test").setMethodCallHandler {
      call, result ->
        GlobalScope.launch {
          withContext(Dispatchers.Main) {
            try {
              result.success(null) // this throws (!)
            } catch (e: Throwable) {
              println("caught exception: $e");
            }
          }
        }
    }
  }
}
```

**Comment by Hixie** [comment]
Specifically, we get `caught exception: java.lang.ClassCastException: io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler cannot be cast to io.flutter.plugin.common.MethodChannel$Result`.

**Comment by Hixie** [comment]
The stack trace in the case above is:
```
W/System.err(15248):    at com.damowmow.gc.MainActivity$configureFlutterEngine$1$1$1.invokeSuspend(MainActivity.kt:21)
W/System.err(15248):    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(15248):    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
W/System.err(15248):    at android.os.Handler.handleCallback(Handler.java:883)
W/System.err(15248):    at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(15248):    at android.os.Looper.loop(Looper.java:214)      
W/System.err(15248):    at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(15248):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15248):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(15248):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by Hixie** [comment]
Threaded version works fine:
```
package com.damowmow.gc

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import android.os.*

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "gc.damowmow.com/test").setMethodCallHandler {
      call, result ->
        val backgroundThread = object: Thread("background") {
          override fun run() {
            Handler(Looper.getMainLooper()).post {
              result.success(null)
            };
          }
        }
        backgroundThread.start()
    }
  }
}
```

**Comment by Hixie** [comment]
For the record, this is how I'm driving this from Dart:
```
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  print(await MethodChannel('gc.damowmow.com/test').invokeMethod('a'));
}
```

**Comment by Hixie** [comment]
no crash with:
```kotlin
package com.damowmow.gc

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.*            
import kotlinx.coroutines.*

var lastResult: MethodChannel.Result? = null

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "gc.damowmow.com/test").setMethodCallHandler(
      object: MethodChannel.MethodCallHandler {
        override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
          lastResult = result
          GlobalScope.launch(block = CoroutineScope::test);
        }
    });
  }
}

suspend fun CoroutineScope.test() {
  withContext(Dispatchers.Main) {
    try {
      lastResult!!.success(null) // this throws (!)
      lastResult = null
    } catch (e: Throwable) {
      println("caught exception: $e");
    }
  }
}
```

**Comment by JohnGu9** [comment]
I met this problem too. But finally found out that I misunderstand kotlin croroutine. 
Kotlin croroutine is different from Dart
In your case, you should create a scope on `Dispatchers.Main` and work on this scope. But do not dispatch mission on `Dispatchers.Main` by `withContext(Dispatchers.Main){ }`. 

The easiest code: 
```
// create scope anywhere, for example inside the class
private val _mainScope = CoroutineScope(Dispatchers.Main)

// And launch
_mainScope.launch{
    val res = withContext(Dispatchers.IO) {
        //  do your work on other thread, for example in IO thread, not Main thread
        // ......
        // last line is your return value, but without return keyword, not like Dart
        valueForTheMission
    }
    // return to Main thread and call [result.success]
    result.success(res)
}
```

**Comment by larssn** [comment]
@JohnGu9 Mind posting a complete example?

**Comment by TahaTesser** [comment]
Can reproduce the issue using https://github.com/flutter/flutter/issues/59024#issue-634978408
This runs fine https://github.com/flutter/flutter/issues/59024#issuecomment-640936874
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.92, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.25.0-5.0.pre.92 at C:\Code\flutter_master
    • Framework revision 90f08769a3 (3 hours ago), 2020-12-07 12:33:03 +0100
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.4
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.630]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 87.0.664.52

• No issues found!
```

</details>

**Comment by larssn** [comment]
So I've been working with coroutines for about a month now, and it seems the idiomatic way of doing the the OP's code example is:

```kotlin
override fun onMethodCall(call: MethodCall, result: Result) = runBlocking {
    Log.e(TAG, "onMethodCall: I'm working in thread ${Thread.currentThread().name}")
    when (call.method) {
      "hello" -> {
        withContext(Dispatchers.IO) {
           // Run code on a IO thread (the amount of IO threads are 64 by default).
           myHttpTask()
        }
        withContext(Dispatchers.Default) {
          // Run code on a CPU thread (the amount equals the amount of CPU cores).
          myCpuTask()
        }

        // This will run on the default thread that the invoker of onMethodCall was using (the main/UI thread in this case)
        // This is due to runBlocking inheriting that thread.
        result.success("world")
      }
      else -> result.notImplemented()
    }
  }
```

**Comment by slavonnet** [comment]
1. MainScope is allreqdy object . MainScope
2. MainScope.launch is loke view.post {} . Not garant now execute
3. laucnh is not async. Function may wait lauch ending (i dont  except about non suspend fun)
4.  Network calls  must call in non main thread

try this


```
                    suspendCoroutine<Response?> {
                        val callback = object : Callback {
                            override fun onFailure(call: Call, e: IOException) {
                                it.resume(null)
                            }

                            override fun onResponse(call: Call, response: Response) {
                                it.resume(response)
                            }
                        }
                        okHttp.newCall(Request.Builder().url(url).build()).enqueue(callback)
                    }?.let { response ->
                        if (response.isSuccessful) {
                            CoroutineScope(Dispatchers.IO + Job() + exceptionHandler).lauch{
//////

                         } } }

```

**Comment by nt4f04uNd** [comment]
Hey @Hixie, I just tried and I cannot reproduce it on current master, it prints `null`

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.6.0-12.0.pre.689, on Microsoft Windows [Version 10.0.19041.1288], locale ru-RU)
    • Flutter version 2.6.0-12.0.pre.689 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 51e7c618ab (4 days ago), 2021-11-11 01:23:05 -0500
    • Engine revision d5cadd28b0
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.62.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1288]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 95.0.1020.44

! Doctor found issues in 1 category.
```
</details>

**Comment by darshankawar** [comment]
Verified this issue using latest master and below code sample and observed that there's no crash but it prints `null`:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Building with Flutter multidex support enabled.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:51800/b5yKy1t8phM=/ws
Syncing files to device Android SDK built for x86...
I/flutter (19588): null

```

```
package com.nevercode.flutter_app

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import kotlinx.coroutines.*

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "com.nevercode.flutter_app/test").setMethodCallHandler {
            call, result ->
            GlobalScope.launch {
                withContext(Dispatchers.Main) {
                    try {
                        result.success(null) // this throws (!)
                    } catch (e: Throwable) {
                        println("caught exception: $e");
                    }
                }
            }
        }
    }
}
```

main.dart:

```
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  print(await MethodChannel('com.nevercode.flutter_app/test').invokeMethod('a'));
}
```

I'll go ahead and optimistically close as fixed and not reproducible.
