### ISSUE TITLE
[tool_crash] NoSuchMethodError: The getter 'length' was called on null.Receiver: nullTried calling: length

### ISSUE THREAD

**Issue by PayialeeVARTOU** [flutter/flutter#59048]
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Utf8Encoder.convert (dart:convert/utf.dart:81:31)
#2      Codec.encode (dart:convert/codec.dart:23:32)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:31)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:137:22)
#6      ErrorHandlingFile._runSync (package:flutter_tools/src/base/error_handling_file_system.dart:163:16)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:136:5)
#8      Cache.setStampFor (package:flutter_tools/src/cache.dart:371:35)
#9      CachedArtifact.update (package:flutter_tools/src/cache.dart:562:13)
<asynchronous suspension>
#10     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:698:27)
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#15     _rootRun (dart:async/zone.dart:1184:13)
#16     _CustomZone.run (dart:async/zone.dart:1077:19)
#17     _runZoned (dart:async/zone.dart:1619:10)
```
```
[✓] Flutter (Channel stable, v0.0.0-unknown, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 0.0.0-unknown at C:\flutter
    • Framework revision  (), 1970-01-01 07:00:00.000
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\LaoSE\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\LaoSE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment]
Hi @Popew 
Please check your computer time and date is correct and  
Can you please provide your `flutter doctor -v`?
Thank you

**Comment by VladyslavBondarenko** [comment]
Closing as additional information isn't provided and there is something wrong with flutter installation. 
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted may help
