### ISSUE TITLE
SliverAppBar changes color when NOT expanded

### ISSUE THREAD

**Issue by tapizquent** [flutter/flutter#59088]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: Add `CustomScrollView` with `SliverAppBar` with extended height and set its color to any color. Add a `FlexibleSpaceBar` to flexibleSpace, and add a `Container` as a title and set its color to the same color you set the `SliverAppBar.backgroundColor` 
3. Scroll down to contract the `SliverAppBar`.

**Expected results:** 
`SliverAppBar` should not change colors (to a lighter shade) when contracted. It should stay the same color as it was when expanded and match the color of the title (Container).

**Actual results:** 
Color changed to a lighter shade when contracted.

Please take a look at these images and notice how the title (in this case a `Container` with the same color as `SliverAppBar` background color with a `Text` as a child) stays the same color but the SliverAppBar gets a bit lighter.

**Expanded SliverAppBar:**

![IMG_0518 2](https://user-images.githubusercontent.com/26445812/84190183-8438fc00-aa64-11ea-9e2d-a63351124d39.jpg)

**Contracted SliverAppBar:**

![IMG_0519 2](https://user-images.githubusercontent.com/26445812/84190195-88fdb000-aa64-11ea-8991-7474559b9e32.jpg)

I do have to mention that this was not happening in stable channel v1.17.3 but I just had to change to dev channel because of #56826 which was causing my disk to fill up way too quickly, therefore I am not sure when this behavior was introduced, but certainly after 1.17.3

flutter Analyze
```bash
No issues found! (ran in 8.0s)
```

flutter doctor -v
```console
[✓] Flutter (Channel dev, 1.19.0-4.0.pre, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.19.0-4.0.pre at /Users/josetapizquent/Projects/Tools/flutter
    • Framework revision 2f7a59a8da (4 days ago), 2020-06-05 03:44:02 -0700
    • Engine revision d17c84e7af
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 02915ec5ce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/josetapizquent/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Users/josetapizquent/SSDrive/Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @tapizquent 
I tested this [code sample](https://dartpad.dev/8db99c02152bc4b9059dff1933aa9930)
with the latest master

the issue doesn't seem to occur on web, android or ios

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-6.0.pre.42, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.19.0-6.0.pre.42 at /Users/nevercode/development/flutter_master
    • Framework revision d9653445f4 (10 hours ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Pixel 3a                   • 965AY0WP5C                           • android-arm64  • Android 10 (API 29)
    • iPhone SE (2nd generation) • 96856728-4BA4-47CD-A70E-4AB604D0D5B6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server                 • web-server                           • web-javascript • Flutter Tools
    • Chrome                     • chrome                               • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

</details>

are you experiencing the issue with the latest master?
Thank you

**Comment by TahaTesser** [comment]
HI @tapizquent 
Tested multiple color on latest `master`
it doesn't seem to background as shown in your screenshot, on iPhone XR physical device

![flutter_01](https://user-images.githubusercontent.com/48603081/84361034-afe4ef00-abe8-11ea-871c-6ff20f52ea29.png)
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-6.0.pre.57, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.19.0-6.0.pre.57 at /Users/tahatesser/Code/flutter_master
    • Framework revision daddc914c7 (9 hours ago), 2020-06-11 01:35:01 +0200
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by tapizquent** [comment]
I was finally able to reproduce it @TahaTesser. I noticed this was only happening with DarkTheme, so I went ahead and added my darkTheme settings.

Please check this repo with the bug being reproduced: https://github.com/tapizquent/bug

Change your iPhone to dark mode and you'll see the behavior I'm talking about.

Maybe you can help me figure out why adding these darkTheme settings causes this behavior, because without it, the behavior is not present.

Thank you!

**Comment by tapizquent** [comment]
After some tweaking, I realized that this behavior is caused by the property `applyElevationOverlayColor: true` of the DarkTheme and setting it to false doesn't make the appBar lighter. I am not closing this yet as I would like to get a bit more insight as to why was this not happening before (v1.17.3) and it's happening now. Also, because disabling this property will indeed change the feel and look of several items in the app that have elevation in darkTheme.

**Comment by iapicca** [comment]
Hi @tapizquent 
testing a simplified version of your [code sample](https://github.com/tapizquent/bug) with the latest master
<details>
  <summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const _home = MyHomePage();
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Flutter Demo',
        darkTheme: ThemeData.dark().copyWith(
          applyElevationOverlayColor: true,
        ),
        home: _home,
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage();

  @override
  Widget build(BuildContext context) => Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverAppBar(
              brightness: ThemeData.estimateBrightnessForColor(Colors.teal),
              pinned: true,
              stretch: true,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.vertical(
                  bottom: Radius.circular(20),
                ),
              ),
              expandedHeight: MediaQuery.of(context).size.height / 3,
              backgroundColor: const Color(0xFF45BBA5),
              actions: <Widget>[
                IconButton(
                  icon: Icon(Icons.share),
                  onPressed: () {},
                ),
              ],
              iconTheme: IconThemeData(color: Colors.white),
              flexibleSpace: FlexibleSpaceBar(
                centerTitle: true,
                title: Container(
                  padding: EdgeInsets.symmetric(horizontal: 8),
                  decoration: BoxDecoration(
                    color: const Color(0xFF45BBA5),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: GestureDetector(
                    onTap: () {},
                    child: Text(
                      'Test',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ),
              ),
            )
          ],
        ),
      );
}

```

</details>

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-1.0.pre.29, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.29 at /Users/nevercode/development/flutter_master
    • Framework revision 1d407de925 (9 hours ago), 2020-06-11 19:45:02 -0400
    • Engine revision d417772d7a
    • Dart version 2.9.0 (build 2.9.0-15.0.dev f043f9e5f6)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

</details>


<details>
  <summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/84485439-d1a3ac00-aca4-11ea-88f4-13d11cb9d5bb.png)

</details>

I'm not sure if this behaviour is desired, but definitely reproduces
Thank you

**Comment by tapizquent** [comment]
Has anyone been able to take a look at this? It’s been quite a while since labels and all were assigned

**Comment by danagbemava-nc** [comment]
I can no longer reproduce this on `stable 2.10.5` with the sample in [this comment](https://github.com/flutter/flutter/issues/59088#issuecomment-643163956) or the sample in [this repo](https://github.com/tapizquent/bug).

<details>
<summary>screenshots</summary>

| repo sample | simplified sample |
| -- | -- | 
| <img src="https://user-images.githubusercontent.com/88313112/164009370-98d3152f-875a-4a83-9838-c6ce29683c14.png" /> | <img src="https://user-images.githubusercontent.com/88313112/164009395-4abf0fc4-2529-4bcc-9afe-9844c98eea53.png"/> |

</details>

Closing this is as fixed. 

<details>
<summary> stable flutter doctor </summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (20 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 15.3 19D50
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>
