### ISSUE TITLE
ERROR:flutter/lib/ui/ui_dart_state.cc(148)

### ISSUE THREAD

**Issue by rishesh007** [flutter/flutter#59134]
I don't know why flutter is throwing these errors. Previously is working fine.
Need Help..

```
E/flutter (16196): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: No element
E/flutter (16196): #0      _GrowableList.get:single (dart:core-patch/growable_array.dart:226)
E/flutter (16196): #1      ScrollController.get:position (package:flutter/src/widgets/scroll_controller.dart:112)
E/flutter (16196): #2      PageController.get:page (package:flutter/src/widgets/page_view.dart:147)
E/flutter (16196): #3      CarouselState.initState.<anonymous closure> (package:carousel_pro/src/carousel_pro.dart:110)
E/flutter (16196): #4      _rootRunUnary (dart:async/zone.dart:1132)
E/flutter (16196): #5      _CustomZone.runUnary (dart:async/zone.dart:1029)
E/flutter (16196): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
E/flutter (16196): #7      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968)
E/flutter (16196): #8      _rootRunUnary (dart:async/zone.dart:1136)
E/flutter (16196): #9      _CustomZone.runUnary (dart:async/zone.dart:1029)
E/flutter (16196): #10     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:952)
E/flutter (16196): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382)
E/flutter (16196): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416)
E/flutter (16196): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)
E/flutter (16196):
```

**Comment by VladyslavBondarenko** [comment]
Hi @rishesh007 
could you provide your `flutter doctor -v` and a minimal complete reproducible code sample?

may be something similar to https://github.com/flutter/flutter/issues/47040

**Comment by rishesh007** [comment]
Here is my `flutter doctor -v`
```
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.17.3 at C:\src\flutter
    • Framework revision b041144f83 (6 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\rishe\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\rishe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0
```

Since you asked for demo code, well it's not even working on the `demo-code` given by flutter after starting a new project
```

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {

      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}

```

**Code is working perfectly but why I'm getting these error**

**Comment by rishesh007** [comment]
@VladyslavBondarenko 
Thanks for your help 
It's working fine now.

**Comment by VladyslavBondarenko** [comment]
@rishesh007 
Then closing the issue
