### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:FAILURE: Build failed with an exception.* What went wrong:Project 'app' not found in root project 'android'.* Try:Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.* Get more help at https://help.gradle.orgBUILD FAILED in 0s Command: /Users/bhavneetsingh/Documents/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by developerpaaji** [flutter/flutter#59312]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s Command: /Users/bhavneetsingh/Documents/android/gradlew, OS error code: 1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
<asynchronous suspension>
#2      flavorUndefinedHandler.<anonymous closure> (package:flutter_tools/src/android/gradle_errors.dart:277:57)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:73)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
```
```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.19.0-4.1.pre at /Users/bhavneetsingh/Documents/Github/flutter
    • Framework revision f994b76974 (2 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/bhavneetsingh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • ONEPLUS A6010 • 192.168.0.101:5555 • android-arm64  • Android 10 (API 29)
    • Web Server    • web-server         • web-javascript • Flutter Tools
    • Chrome        • chrome             • web-javascript • Google Chrome 83.0.4103.97

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 20e59316b8b8474554b38493b8ca888794b0234a
### Plugins
camera-0.5.8+2
cloud_firestore-0.12.11
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_database-3.1.6
firebase_storage-3.1.6
flutter_custom_tabs-0.6.0
flutter_plugin_android_lifecycle-1.0.8
google_sign_in-4.0.7
image_picker-0.6.7+1
location-3.0.2
location_web-1.0.0
path_provider-1.6.10
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3
permission_handler-5.0.1
razorpay_flutter-1.2.1
share-0.6.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6
video_player-0.10.2

**Comment by bkonyi** [comment]
Since this is an Android specific failure, reassigning to `team-android`.

**Comment by camsim99** [comment]
Thank you for taking the time to file this issue. Without additional information, we're unfortunately not sure how to resolve this issue. I'm therefore reluctantly going to close this for now. Please don't hesitate to comment on the issue if you have any more information to add; we'll reopen it right away!

**Comment by ash2moon** [comment]
Cannot find project app is generally caused by a misconfigured directory structure or Gradle build files. Unfortunately how it can be misconfigured can be caused my many different factors.

We need more information about the project directory structure or a link to a project that fails this way.
To get the directory structure, run the following:
```
find .
```

@bkonyi Looking at the tool crash using the internal dashboard shows a different crash than what this crash is showing. (Cannot find app task vs cannot find app directory)

> ## Command
> ```
> flutter build apk
> ```
> 
> ## Steps to Reproduce
> 1. ...
> 2. ...
> 3. ...
> 
> ## Logs
> ProcessException: Process exited abnormally:
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Project 'app' not found in root project 'android'.
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 0s Command: /Users/bhavneetsingh/Documents/android/gradlew, OS error code: 1
> 
> ```
> #0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
> #1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
> <asynchronous suspension>
> #2      flavorUndefinedHandler.<anonymous closure> (package:flutter_tools/src/android/gradle_errors.dart:277:57)
> #3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:73)
> #4      _rootRunUnary (dart:async/zone.dart:1198:47)
> #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
> #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
> #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
> #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
> #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
> #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
> #12     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
> #13     _rootRunUnary (dart:async/zone.dart:1198:47)
> #14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> #15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
> #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
> #17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
> #18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
> #19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
> #20     _rootRun (dart:async/zone.dart:1190:13)
> #21     _CustomZone.run (dart:async/zone.dart:1093:19)
> #22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> ```
> 
> ```
> [✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.3 19D76, locale en-IN)
>     • Flutter version 1.19.0-4.1.pre at /Users/bhavneetsingh/Documents/Github/flutter
>     • Framework revision f994b76974 (2 days ago), 2020-06-09 15:53:13 -0700
>     • Engine revision 9a28c3bcf4
>     • Dart version 2.9.0 (build 2.9.0-14.1.beta)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/bhavneetsingh/Library/Android/sdk
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.4, Build version 11E146
>     • CocoaPods version 1.9.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio 2.app/Contents
>     • Flutter plugin version 38.2.3
>     • Dart plugin version 191.8423
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] VS Code (version 1.46.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.11.0
> 
> [✓] Connected device (3 available)
>     • ONEPLUS A6010 • 192.168.0.101:5555 • android-arm64  • Android 10 (API 29)
>     • Web Server    • web-server         • web-javascript • Flutter Tools
>     • Chrome        • chrome             • web-javascript • Google Chrome 83.0.4103.97
> 
> • No issues found!
> ```
> 
> ## Flutter Application Metadata
> **Type**: app **Version**: 1.0.0+1 **Material**: true **Android X**: false **Module**: false **Plugin**: false **Android package**: null **iOS bundle identifier**: null **Creation channel**: stable **Creation framework version**: [20e5931](https://github.com/flutter/flutter/commit/20e59316b8b8474554b38493b8ca888794b0234a)
> 
> ### Plugins
> camera-0.5.8+2 cloud_firestore-0.12.11 firebase_auth-0.16.1 firebase_auth_web-0.1.3+1 firebase_core-0.4.5 firebase_core_web-0.1.1+2 firebase_database-3.1.6 firebase_storage-3.1.6 flutter_custom_tabs-0.6.0 flutter_plugin_android_lifecycle-1.0.8 google_sign_in-4.0.7 image_picker-0.6.7+1 location-3.0.2 location_web-1.0.0 path_provider-1.6.10 path_provider_linux-0.0.1+1 path_provider_macos-0.0.4+3 permission_handler-5.0.1 razorpay_flutter-1.2.1 share-0.6.4+3 shared_preferences-0.5.7+3 shared_preferences_macos-0.0.1+10 shared_preferences_web-0.1.2+7 sqflite-1.3.1 url_launcher-5.4.10 url_launcher_macos-0.0.1+7 url_launcher_web-0.1.1+6 video_player-0.10.2
