### ISSUE TITLE
assertion was thrown while handling a gesture

### ISSUE THREAD

**Issue by claudiadroste** [flutter/flutter#59362]
```bash
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/localizations.dart': Failed assertion: line 447 pos 12: 'context != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      Localizations.of (package:flutter/src/widgets/localizations.dart:447:12)
#3      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:71:23)
#4      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:92:4)
#5      showDialog (package:flutter/src/material/dialog.dart:914:10)
#6      AccountCardBarState.createNotSelectedBar.<anonymous closure> (package:pocket_money/gui/account/AccountCardBar.dart:89:19)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#85486
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(381.7, 115.0)
  finalLocalPosition: Offset(32.3, 25.0)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by iapicca** [comment]
Hi @claudiadroste 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
@claudiadroste 
Closing as additional information isn't provided
