### ISSUE TITLE
in_app_purchase 0.3.4 crashes when fetching products from the Play Store

### ISSUE THREAD

**Issue by LugonjaAleksandar** [flutter/flutter#59400]
I am facing an issue after installing and implementing using in_app_purchase plugin.

What I did so far: 
1. added 2 products on Play Store that are visible and active. 
2. submitted build for alpha testing, since that is required for in-app purchase to work.
3. added `InAppPurchaseConnection.enablePendingPurchases();` at the app launch
4. created a sequence of requests to the app store out of which last one fails with nasty log I can't work around

```
bool available = await _iap.isAvailable();
  if (!available) {
    print('=========> The store cannot be reached or accessed.');
  } else {
    Set<String> _kIds = {'farm', 'forest'};
    ProductDetailsResponse productsResponse = await _iap.queryProductDetails(_kIds);
    List<ProductDetails> products = productsResponse.productDetails;
  }      
}
```
5. At the moment `queryProductDetails` crashes every single time with the following log:

```
E/AndroidRuntime( 9053): java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in /data/app/com.my.fancy.app-6ImcBn8ELPgiO8hTXXp_3Q==/base.apk)
E/AndroidRuntime( 9053): 	at io.flutter.plugins.inapppurchase.Translator.fromSkuDetail(Translator.java:27)
E/AndroidRuntime( 9053): 	at io.flutter.plugins.inapppurchase.Translator.fromSkuDetailsList(Translator.java:49)
E/AndroidRuntime( 9053): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl$1.onSkuDetailsResponse(MethodCallHandlerImpl.java:185)
E/AndroidRuntime( 9053): 	at com.android.billingclient.api.zzj.run(com.android.billingclient:billing@@3.0.0:8)
E/AndroidRuntime( 9053): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 9053): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9053): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 9053): 	at android.app.ActivityThread.main(ActivityThread.java:6746)
E/AndroidRuntime( 9053): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9053): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 9053): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

6. I've tried running this on multiple example projects, and it fails. Tried with both Kotlin and Java project, just to see if there is something buggy with one or the other, but no luck.
  
Flutter doctor results: 

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-RS)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by stonekase** [comment]
Anything on this issue yet?

**Comment by handicraftsman** [comment]
I have got exact same issue, do you have `com.android.billingclient:billing:3.0.0` in your `android/app/build.gradle`'s `dependencies`?

**Comment by yetunnaing18121996** [comment]
I have already add billing library "com.android.billingclient:billing-ktx:3.0.0" to my gradle file , uploaded app to google play as production and defined some of my in app products in my play console. After then I start implementing the flutter code, fetching product's detail from the google play console, my app crash and I got those error messages in my log cat.

java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in /data/app/com.test.inapppurchase/base.apk)
E/AndroidRuntime(20258): at io.flutter.plugins.inapppurchase.Translator.fromSkuDetail(Translator.java:27)
E/AndroidRuntime(20258): at io.flutter.plugins.inapppurchase.Translator.fromSkuDetailsList(Translator.java:49)
E/AndroidRuntime(20258): at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl$1.onSkuDetailsResponse(MethodCallHandlerImpl.java:185)
E/AndroidRuntime(20258): at com.android.billingclient.api.zzj.run(com.android.billingclient:billing@@3.0.0:8)

how can I solve that?
please

**Comment by handicraftsman** [comment]
Sorry for responding too late: the solution for me was to remove `com.android.billingclient:billing` from app's build.gradle - I think it is conflicting with plugin's own `com.android.billingclient:billing` dependency somehow (flutter plugins are separate libraries for your platform which have access to the flutter embedder - making your application being able to task to them -, but are managed with platform native package manager)

**Comment by yetunnaing18121996** [comment]
> Sorry for responding too late: the solution for me was to remove `com.android.billingclient:billing` from app's build.gradle - I think it is conflicting with plugin's own `com.android.billingclient:billing` dependency somehow (flutter plugins are separate libraries for your platform which have access to the flutter embedder - making your application being able to task to them -, but are managed with platform native package manager)

ok thanks, after I removed the billing dependency and asked the permissions in androidmanifest file, the in appproduct list comes to me but, when i try to buy it, it shows me like that
![Screenshot_1601692476](https://user-images.githubusercontent.com/38392529/94981402-0c816680-0558-11eb-914f-ef37881bd487.png)
how can I solve that?please

**Comment by handicraftsman** [comment]
@yetunnaing18121996 are you sure you are using the right SKU? As in, that ID you've entered in the play console.

**Comment by yetunnaing18121996** [comment]
@handicraftsman  yes I'm fetching in app product list from google play console and used that sku as purchase param. I have no idea why it says me like that? how about you, is it work?

**Comment by handicraftsman** [comment]
> @handicraftsman yes I'm fetching in app product list from google play console and used that sku as purchase param. I have no idea on that? how about you, is it work?

IDK then, I hardcode SKUs in the app.

**Comment by TahaTesser** [comment]
Hi @LugonjaAleksandar 
Using the `in_app_purchase: ^0.3.5+1` and  I created a runnable minimal code sample below, the app runs with no issues, details are correctly shown, and no errors in the `logcat`.


<details> 
<summary>complete code sample</summary> 

```dart

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:in_app_purchase/in_app_purchase.dart';

void main() {
  InAppPurchaseConnection.enablePendingPurchases();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: IAPScreen(),
    );
  }
}

class IAPScreen extends StatefulWidget {
  @override
  _IAPScreenState createState() => _IAPScreenState();
}

class _IAPScreenState extends State<IAPScreen> {
  InAppPurchaseConnection _iap = InAppPurchaseConnection.instance;
  bool _available = true;
  List<ProductDetails> products = [];
  StreamSubscription<List<PurchaseDetails>> _subscription;
  String productId;
  String title;
  String price;
  String skuDetail;
  String skuProduct;

  void fetchAndSetProducts() async {
    bool a = await _iap.isAvailable();
    setState(() {
      _available = a;
    });

    print(_available);
    final ProductDetailsResponse response = await InAppPurchaseConnection
        .instance
        .queryProductDetails({"consumable"});

    setState(() {
      for (ProductDetails item in response.productDetails) {
        productId = "response.productDetails[productId]: ${item.id}";
        title = "response.productDetails[title]: ${item.title}";
        price = "response.productDetails[price]: ${item.price}";
        skuDetail =
            "response.productDetails[skuDetail]: ${item.skuDetail.title}";
        skuProduct = "response.productDetails[skuProduct]: ${item.skProduct}";
      }
      // result = "response.productDetails: ${response.productDetails}";
    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    fetchAndSetProducts();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text(productId ?? 'No data'),
            Text(title ?? 'No data'),
            Text(price ?? 'No data'),
            Text(skuDetail ?? 'No data'),
            Text(skuProduct ?? 'No data'),
          ],
        ),
      ),
    );
  }
}

``` 

</details>
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.22.5 at C:\Code\flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Code\SDK
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by LugonjaAleksandar** [comment]
@pedromassangocode solution that was proposed with billing client library fixed the issue. Maybe not just closing this issue but creating PR for the documentation update that users should check billing client library to make sure it's correct would be useful?

**Comment by jbryanh** [comment]
@LugonjaAleksandar what solution are you referring to?

**Comment by LugonjaAleksandar** [comment]
@jbryanh There is a response above which was voted up because it worked for other people too. https://github.com/flutter/flutter/issues/59400#issuecomment-702731624
