### ISSUE TITLE
flutter build web -> The compiler crashed when compiling this element

### ISSUE THREAD

**Issue by lukehassel** [flutter/flutter#59419]
When I run flutter web in browser all works fine.
But when running the flutter build web command it throws this error below.

```dart
@override
  Stream<LoginState> mapEventToState(LoginEvent event) async* {
    if (event is GetLoginEvent) {
      yield LoginLoadingState();
      final failureOrModel = getLoginUseCase(event.aid);
      await for (var value in failureOrModel) {
        yield* _eitherLoadedOrErrorState(value);
      }
    }
  }

```
```bash
Target dart2js failed: Exception: lib/features/login/presentation/bloc/login_bloc.dart:25:22:
Internal Error: The compiler crashed when compiling this element.
  Stream<LoginState> mapEventToState(LoginEvent event) async* {
                     ^

The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system:(Mac OS),

* the Dart SDK build number (2.9.0-edge.2b917f5b6a0e1524516f214c6d0df49f4abfd378), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

The compiler crashed: NoSuchMethodError: The getter 'classNode' was called on null.
Receiver: null
Tried calling: classNode
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ClosedWorldClassHierarchy.getTypeArgumentsAsInstanceOf (package:kernel/class_hierarchy.dart:719:54)
#2      ClosedWorldClassHierarchy.getTypeAsInstanceOf (package:kernel/class_hierarchy.dart:704:9)
#3      HierarchyBasedTypeEnvironment.getTypeAsInstanceOf (package:kernel/src/hierarchy_based_type_environment.dart:24:22)
#4      StaticTypeVisitor.visitForInStatement (package:compiler/src/ir/static_type.dart:1254:53)
#5      ForInStatement.accept (package:kernel/ast.dart:5832:43)
#6      StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:82:18)
#7      StaticTypeVisitor.visitBlock (package:compiler/src/ir/static_type.dart:1004:22)
#8      Block.accept (package:kernel/ast.dart:5462:43)
#9      StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:82:18)
#10     StaticTypeVisitor._handleConditional (package:compiler/src/ir/static_type.dart:922:28)
#11     StaticTypeVisitor.visitIfStatement (package:compiler/src/ir/static_type.dart:1334:12)
#12     IfStatement.accept (package:kernel/ast.dart:5998:43)
#13     StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:82:18)
#14     StaticTypeVisitor.visitBlock (package:compiler/src/ir/static_type.dart:1004:22)
#15     Block.accept (package:kernel/ast.dart:5462:43)
#16     StaticTypeBase.visitNode (package:compiler/src/ir/static_type_base.dart:82:18)
#17     StaticTypeVisitor.visitProcedure (package:compiler/src/ir/static_type.dart:1429:5)
#18     Procedure.accept (package:kernel/ast.dart:2397:40)
#19     KernelToElementMapImpl.computeWorldImpact (package:compiler/src/kernel/element_map_impl.dart:1445:12)
#20     KernelWorkItem.run.<anonymous closure>.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:403:47)
#21     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#22     KernelWorkItem.run.<anonymous closure> (package:compiler/src/kernel/kernel_strategy.dart:402:28)
#23     CompilerTask.measure (package:compiler/src/common/tasks.dart:64:51)
#24     KernelWorkItem.run (package:compiler/src/kernel/kernel_strategy.dart:377:26)
#25     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:70)
#26     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#27     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:460:32)
#28     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#29     Compiler.emptyQueue.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:458:28)
#30     CompilerDiagnosticReporter.withCurrentElement (package:compiler/src/compiler.dart:743:15)
#31     Compiler.emptyQueue.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:456:18)
#32     ResolutionEnqueuer._forEach (package:compiler/src/enqueue.dart:449:12)
#33     ResolutionEnqueuer.forEach (package:compiler/src/enqueue.dart:465:5)
#34     Compiler.emptyQueue.<anonymous closure> (package:compiler/src/compiler.dart:452:16)
#35     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#36     Compiler.emptyQueue (package:compiler/src/compiler.dart:451:14)
#37     Compiler.processQueue.<anonymous closure> (package:compiler/src/compiler.dart:477:7)
#38     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#39     Compiler.processQueue (package:compiler/src/compiler.dart:470:14)
#40     Compiler.computeClosedWorld (package:compiler/src/compiler.dart:339:5)
#41     Compiler.compileFromKernel.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:407:17)
#42     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#43     Compiler.compileFromKernel.<anonymous closure> (package:compiler/src/compiler.dart:406:43)
#44     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#45     Compiler.compileFromKernel (package:compiler/src/compiler.dart:405:14)
#46     Compiler.runInternal (package:compiler/src/compiler.dart:257:13)
<asynchronous suspension>
#47     Compiler.run.<anonymous closure>.<anonymous closure> (package:compiler/src/compiler.dart:212:38)
#48     new Future.sync (dart:async/future.dart:222:31)
#49     Compiler.run.<anonymous closure> (package:compiler/src/compiler.dart:212:20)
#50     CompilerTask.measureSubtask (package:compiler/src/common/tasks.dart:179:35)
#51     Compiler.run (package:compiler/src/compiler.dart:209:41)
#52     CompilerImpl.run.<anonymous closure>.<anonymous closure> (package:compiler/src/apiimpl.dart:91:22)
#53     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#54     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#55     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#56     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#57     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#58     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)



Compiling lib/main.dart for the Web...                              9.4s
Exception: Failed to compile application for the Web.
```

**Comment by iapicca** [comment]
Hi @lukehassel 
Can you please provide your `flutter doctor -v`, 
your `flutter build web --verbose`,
your `pubspec.yaml`
and a minimal complete reproducible code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
