### ISSUE TITLE
[video_player] Allow audio track selection

### ISSUE THREAD

**Issue by tmp05** [flutter/flutter#59437]
Video_player needs a possibility to change audio tracks in video, like TrackSelector in Exoplayer do.

**Comment by balvinderz** [comment]
i have actually done some work in this. I have worked on the android part . Only ios part is remaining. I will create a PR When i m done.

**Comment by tmp05** [comment]
> i have actually done some work in this. I have worked on the android part . Only ios part is remaining. I will create a PR When i m done.

I look forward for it!

**Comment by balvinderz** [comment]
https://www.youtube.com/watch?v=96sFGuuAQxU&feature=youtu.be 
works on flutter web too :D

**Comment by tmp05** [comment]
> https://www.youtube.com/watch?v=96sFGuuAQxU&feature=youtu.be
> works on flutter web too :D



> i have actually done some work in this. I have worked on the android part . Only ios part is remaining. I will create a PR When i m done.

how's it going?

**Comment by balvinderz** [comment]
you can use my fork
in pubspec.yaml
for getting my fork
copy this
video_player:
    git:
      url: https://github.com/balvinderz/plugins
      ref: features/change_audio
      path: packages/video_player/video_player

call getAudios() after initialize() and call setAudio to set the audio. 
To make it work on web 
add 
`  <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"  type="application/javascript"></script>
`
in index.html above 
`  <script src="main.dart.js" type="application/javascript"></script>
`
.
I have also uploaded a demo app if you want to see a demo 
https://github.com/balvinderz/change_audio_demo

**Comment by tmp05** [comment]
oh, great! thank you very much! I'll try it!)

**Comment by balvinderz** [comment]
ok

**Comment by tmp05** [comment]
Hello! When I use controller.getAudios() I get a List<String>,  sometimes names are the same, like this ['Stereo, 0.19 Mbps','Stereo, 0.19 Mbps','Stereo, 0.19 Mbps','Stereo, 0.20 Mbps']. So, video has 3 audio tracks with name 'Stereo, 0.19 Mbps'. And when I setAudio ('Stereo, 0.19 Mbps') it works always for one track.

**Comment by balvinderz** [comment]
send me the link that you are trying to play

**Comment by tmp05** [comment]
sorry, I'm in closed project with api and access token(

**Comment by balvinderz** [comment]
ok

**Comment by balvinderz** [comment]
i will make a function called setAudioByIndex . you can use that function to set the audio

**Comment by tmp05** [comment]
it's great!

**Comment by balvinderz** [comment]
run pub upgrade and try the setAudioByIndex function

**Comment by tmp05** [comment]
Thank you, it's working perfect!

**Comment by tmp05** [comment]
> run pub upgrade and try the setAudioByIndex function

how do you think, is' it possible to use your fork and chewie together? chewie is more user-friendly, has a better video progress indicator, full screen, sound and so on. When I try to use it I get an error  'Because chewie >=0.9.6 depends on video_player from hosted and MyApp depends on video_player from git, chewie >=0.9.6 is forbidden.'

**Comment by balvinderz** [comment]
check the demo's app pubspec.yaml

**Comment by tmp05** [comment]
chewie: any also gives an error..
Because chewie <0.4.0 requires SDK version <2.0.0 and chewie ^0.4.0 depends on video_player ^0.4.0, chewie <0.5.0 requires video_player ^0.4.0.
And because chewie ^0.5.0 depends on video_player ^0.5.0 and chewie >=0.6.0 <0.8.0 depends on video_player ^0.6.0, chewie <0.8.0 requires video_player ^0.4.0 or ^0.5.0 or ^0.6.0.
And because chewie ^0.8.0 depends on video_player ^0.7.0 and chewie >=0.9.0 <0.9.4 depends on video_player >=0.7.0 <0.9.0, chewie <0.9.4 requires video_player ^0.4.0 or ^0.5.0 or ^0.6.0 or >=0.7.0 <0.9.0.
And because chewie >=0.9.4 <0.9.6 depends on video_player >=0.7.0 <0.10.0 and chewie >=0.9.6 depends on video_player >=0.7.0 <0.11.0, every version of chewie requires video_player from hosted.
So, because MyApp depends on both video_player from git and chewie any, version solving failed.
pub get failed (1; So, because avideo depends on both video_player from git and chewie any, version solving failed.)

**Comment by tmp05** [comment]
thank you, you saved me)

**Comment by vishal-akg** [comment]
For better user experience, is there anyway to get the initially selected audio track? just in case I can show user with tick mark.

**Comment by balvinderz** [comment]
Currently , it is not possible but maybe i can add that function

**Comment by gumilar1995** [comment]
is it working with HLS source?

**Comment by balvinderz** [comment]
@gumilar1995  yes this works with hls source . you can check the demo app to see how to use it.
https://github.com/balvinderz/change_audio_demo

**Comment by gumilar1995** [comment]
have you created a PR for this? I think it's gonna really helpful for some people

**Comment by balvinderz** [comment]
@gumilar1995  This uses external library on web so i don't think they will accept this PR.

**Comment by gumilar1995** [comment]
Hello @balvinderz 

sometimes this error occured on android

E/flutter (13096): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true.
E/flutter (13096): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (13096): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (13096): #2      new PlatformException (package:flutter/src/services/message_codec.dart:111:15)
E/flutter (13096): #3      VideoPlayerApi.getAudios (package:video_player_platform_interface/messages.dart:378:13)
E/flutter (13096): <asynchronous suspension>
E/flutter (13096): #4      MethodChannelVideoPlayer.getAudios (package:video_player_platform_interface/method_channel_video_player.dart:63:45)
E/flutter (13096): #5      VideoPlayerController.getAudios (package:video_player/video_player.dart:354:33)
E/flutter (13096): #6      PlayVideoState._setVideoController (package:stro/ui/player/player.dart:443:34)
E/flutter (13096): #7      PlayVideoState._getVideo.<anonymous closure> (package:stro/ui/player/player.dart:343:7)
E/flutter (13096): #8      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (13096): #9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13096): #10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (13096): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (13096): #12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (13096): #13     Future._chainCoreFuture (dart:async/future_impl.dart:496:7)
E/flutter (13096): #14     Future._chainFuture (dart:async/future_impl.dart:580:9)
E/flutter (13096): #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:37:15)
E/flutter (13096): #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (13096): #17     compute (package:flutter/src/foundation/_isolates_io.dart)
E/flutter (13096): #18     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (13096): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13096): #20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (13096): #21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (13096): #22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (13096): #23     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (13096): #24     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (13096): #25     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13096): #26     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13096): #27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (13096): #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (13096): #29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (13096): #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

is it because the source doesn't have audio tracks?

**Comment by balvinderz** [comment]
@gumilar1995 can you give me link that you are trying to play

**Comment by gumilar1995** [comment]
sorry i can't, i'm in closed project.

all i can provide that the source doesn't have an audio tracks like this :

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="english",FORCED=NO,AUTOSELECT=YES,URI="",LANGUAGE="eng"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="indonesia",FORCED=NO,AUTOSELECT=YES,URI="",LANGUAGE="ind"

#EXT-X-STREAM-INF:BANDWIDTH=800000,RESOLUTION=640x360

#EXT-X-STREAM-INF:BANDWIDTH=1400000,RESOLUTION=854x480

#EXT-X-STREAM-INF:BANDWIDTH=2800000,RESOLUTION=1280x720

#EXT-X-STREAM-INF:BANDWIDTH=5000000,RESOLUTION=1920x1080

**Comment by gumilar1995** [comment]
@balvinderz  the issue is in my code, solved now

thank you for your responses, and sorry for taking your time :)

**Comment by urvashi-godumalani** [comment]
Is there a way to save video after changing its audio

**Comment by balvinderz** [comment]
> Is there a way to save video after changing its audio and also I tried setAudio function with remote audio url in your demo project but it's not changing it's audio

@urvashi-godumalani  you dont need to pause audio url . you need to pass the name of the audio( which you can get from getAudios function) .

**Comment by urvashi-godumalani** [comment]
@balvinderz Oh okay but I wanted to use remote url. The task was to record video from camera and overwrite it's audio from remote audio url

**Comment by balvinderz** [comment]
@urvashi-godumalani  that is not possible with this.

**Comment by urvashi-godumalani** [comment]
@balvinderz oh alright. Thanks for your time

**Comment by Sourav9063** [comment]
badly in need of this feature. Why hasn't yet this been merged? Can you clearly give the pubspec.yaml guideline to install your fork. Not working the previous answer.

**Comment by balvinderz** [comment]
> badly in need of this feature. Why hasn't yet this been merged? Can you clearly give the pubspec.yaml guideline to install your fork. Not working the previous answer.

you can checkout the demo app's pubspec.yaml to see how you can integrate this in your app 
`https://github.com/balvinderz/change_audio_demo/blob/master/pubspec.yaml`

**Comment by Sourav9063** [comment]
thank you so much

**Comment by balvinderz** [comment]
You can fork my repo and add that

**Comment by lavara123** [comment]
Please AvPlayer (IOS)?

**Comment by balvinderz** [comment]
works on ios too @lavara123

**Comment by Joseph-Nathan** [comment]
in my case i have url to video source and 2 url to 2 audio source ,
how can manage change between this 2 audio source .

**Comment by aliyazdi75** [comment]
I made a better issue mentioned above. Feel free to track this feature there.

**Comment by JDPradyut** [comment]
Can  we change subtitles also?

**Comment by TejasDhanda-L11** [comment]
@balvinderz
the fork you provided doesn't support null safety and so I am not able to use it.

I don't want to disable null safety for obvious reasons.

what should I do?

**Comment by TejasDhanda-L11** [comment]
complete error message is

`Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:video_player
- package:video_player_platform_interface

For solutions, see https://dart.dev/go/unsound-null-safety
3

FAILURE: Build failed with an exception.

* Where:
Script '/home/tejas/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1052

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/tejas/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by JDPradyut** [comment]
> @balvinderz
> the fork you provided doesn't support null safety and so I am not able to use it.
> 
> I don't want to disable null safety for obvious reasons.
> 
> what should I do?

Use flutter vlc player...it supports null safety and also has many options

**Comment by gumilar1995** [comment]
> complete error message is
> 
> `Error: Cannot run with sound null safety, because the following dependencies
> don't support null safety:
> 
> * package:video_player
> * package:video_player_platform_interface
> 
> For solutions, see https://dart.dev/go/unsound-null-safety
> 3
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script '/home/tejas/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1052
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command '/home/tejas/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1m 14s
> Exception: Gradle task assembleDebug failed with exit code 1
> `

You can use my fork, I've migrated this feature to nulllsafety

video_player:
    git:
      url: https://github.com/gumilar1995/plugins-1
      ref: agumi
      path: packages/video_player/video_player

**Comment by JDPradyut** [comment]
> > complete error message is
> > `Error: Cannot run with sound null safety, because the following dependencies
> > don't support null safety:
> > 
> > * package:video_player
> > * package:video_player_platform_interface
> > 
> > For solutions, see https://dart.dev/go/unsound-null-safety
> > 3
> > FAILURE: Build failed with an exception.
> > 
> > * Where:
> >   Script '/home/tejas/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1052
> > * What went wrong:
> >   Execution failed for task ':app:compileFlutterBuildDebug'.
> > 
> > > Process 'command '/home/tejas/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
> > 
> > 
> > 
> > * Try:
> >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > * Get more help at https://help.gradle.org
> > 
> > BUILD FAILED in 1m 14s
> > Exception: Gradle task assembleDebug failed with exit code 1
> > `
> 
> You can use my fork, I've migrated this feature to nullsafety
> 
> video_player:
> git:
> url: https://github.com/gumilar1995/plugins-1
> ref: agumi
> path: packages/video_player/video_player

Does it supports fetching subtitles  and audio tracks from video?

**Comment by gumilar1995** [comment]
> > > complete error message is
> > > `Error: Cannot run with sound null safety, because the following dependencies
> > > don't support null safety:
> > > 
> > > * package:video_player
> > > * package:video_player_platform_interface
> > > 
> > > For solutions, see https://dart.dev/go/unsound-null-safety
> > > 3
> > > FAILURE: Build failed with an exception.
> > > 
> > > * Where:
> > >   Script '/home/tejas/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1052
> > > * What went wrong:
> > >   Execution failed for task ':app:compileFlutterBuildDebug'.
> > > 
> > > > Process 'command '/home/tejas/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
> > > 
> > > 
> > > 
> > > * Try:
> > >   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > > * Get more help at https://help.gradle.org
> > > 
> > > BUILD FAILED in 1m 14s
> > > Exception: Gradle task assembleDebug failed with exit code 1
> > > `
> > 
> > You can use my fork, I've migrated this feature to nullsafety
> > 
> > video_player:
> > git:
> > url: https://github.com/gumilar1995/plugins-1
> > ref: agumi
> > path: packages/video_player/video_player
> 
> Does it supports fetching subtitles  and audio tracks from video?

Currently only supports audio tracks

**Comment by loeffel-io** [comment]
any update?

**Comment by abdoutech93** [comment]
We are preparing a PR but it was tested only with Android, I don't know if it will be accepted !!

**Comment by usilitel** [comment]
any update?

**Comment by nateshmbhat** [comment]
I'm working on this adding this audio track selection feature. As of now, i'm focusing on just providing a method to get the list of audio tracks available on android and ios to start with.

on android i've implemented and tested it. works fine. 
ios WIP.

I might need some help to get this PR landed in this repo as its my first contribution to this flutter repo.

**Comment by nateshmbhat** [comment]
Once this gets merged, I will be adding functionality for selecting a particular track.

**Comment by NavidFarahmandian** [comment]
> Once this gets merged, I will be adding functionality for selecting a particular track.

What's up on this? how we can have your code?
