### ISSUE TITLE
Invalid argument(s): Missing canonical name for Reference to UnmodifiableListView

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#59438]
This is trying to run kevmoo/slide_puzzel@a23d035e87e77b74dd18b832cf7def51b8250aed
using a build of flutter/engine@5c87c31fd3e721f15aca687108f4c64ee2087892 on windows.

```
 .\src\flutter\tools\gn --unoptimized --full-dart-sdk
ninja -C .\out\host_debug_unopt
``

I built with the VSCode 2019 toolchain.

My guess is that this is caused by some partial NNDB conversion confusing things?

```
C:\Users\Study\Documents\GitHub\slide_puzzle [master ≡]> flutter run -d web --web-port 8080 --local-engine=host_debug_unopt --local-engine-src-path=/src/engine/src
Launching lib\main.dart on Web Server in debug mode...
Syncing files to device Web Server...
Unhandled exception:
Invalid argument(s): Missing canonical name for Reference to UnmodifiableListView
#0      BinaryPrinter.writeNonNullReference (package:kernel/binary/ast_to_binary.dart:854:9)
#1      BinaryPrinter.writeAdditionalExports (package:kernel/binary/ast_to_binary.dart:1019:7)
#2      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:953:5)
#3      Library.accept (package:kernel/ast.dart:605:38)
#4      BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:402:10)
#5      BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:708:9)
#6      BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:551:7)
#7      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#8      BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:535:14)
#9      IncrementalSerializer.serialize (package:front_end/src/fasta/incremental_serializer.dart:308:13)
#10     IncrementalSerializer.writePackagesToSinkAndTrimComponent (package:front_end/src/fasta/incremental_serializer.dart:159:24)
#11     FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:733:31)
#12     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:556:13)
<asynchronous suspension>
#13     _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#14     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1187:26)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#20     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#21     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#22     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#23     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#28     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#29     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#30     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#31     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#32     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#33     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#34     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#36     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#39     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#40     _StreamController._add (dart:async/stream_controller.dart:655:7)
#41     _StreamController.add (dart:async/stream_controller.dart:597:5)
#42     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#43     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#46     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#47     _StreamController._add (dart:async/stream_controller.dart:655:7)
#48     _StreamController.add (dart:async/stream_controller.dart:597:5)
#49     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#50     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#51     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
the Dart compiler exited unexpectedly.
Syncing files to device Web Server...                           49,655ms (!)
Failed to compile application.
```

**Comment by eseidel** [comment]
https://github.com/dart-lang/sdk/issues/34644 is the only bug I've seen with a similar error message.  But @alexmarkov fixed that back in 2018, so I suspect this  is unrelated.

This may very well be user error on my part.  Just not sure where to go next.

**Comment by alexmarkov** [comment]
@eseidel I can confirm that https://github.com/dart-lang/sdk/issues/34644 is unrelated as it was specific to AOT.

/cc @jensjoha @johnniwinther

**Comment by eseidel** [comment]
Suggestions as to how I might go about debugging?  I'm stuck here trying to a locally built engine working with Flutter Web. :)

**Comment by eseidel** [comment]
Ha!  Turns out when I passed -v there was actually an underlying error which was not bubbling up to the top level:

```
C:\Users\Study\AppData\Local\Temp\flutter_tools.cf539761\flutter_tool.5e16578d\app.dill --libraries-spec
file:///src/engine/src/out/host_debug_unopt/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\Study\AppData\Local\Temp\flutter_tools.cf539761\flutter_tools.b657518a --filesystem-scheme org-dartlang-app
--initialize-from-dill build\cache.dill.track.dill --platform
file:///C:/Users/Study/Documents/GitHub/slide_puzzle//src/engine/src/out/host_debug_unopt/flutter_web_sdk/kernel/flutter
_ddc_sdk.dill
[   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+1584 ms] Error: Error when reading '/src/engine/src/out/host_debug_unopt/flutter_web_sdk/kernel/flutter_ddc_sdk.dill':
The system cannot find the path specified.
[+1558 ms] Warning: Tried to initialize from a previous compilation (build/cache.dill.track.dill), but couldn't.
[   +1 ms] Error message was 'NoSuchMethodError: The getter 'modeRaw' was called on null.
[        ] Receiver: null
[        ] Tried calling: modeRaw'.
[        ] Stacktrace included '#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
[        ] #1      BinaryBuilder._readOneComponent (package:kernel/binary/ast_from_binary.dart:730:35)
[        ] #2      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:526:33)
[        ] #3      Timeline.timeSync (dart:developer/timeline.dart:163:22)
[        ] #4      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:499:21)
[        ] #5      IncrementalCompiler.initializeFromDill
(package:front_end/src/fasta/incremental_compiler.dart:1494:14)
[        ] <asynchronous suspension>
[        ] #6      IncrementalCompiler.ensurePlatformAndInitialize
(package:front_end/src/fasta/incremental_compiler.dart:1025:34)
[        ] <asynchronous suspension>
[        ] #7      IncrementalCompiler.computeDelta.<anonymous closure>
(package:front_end/src/fasta/incremental_compiler.dart:227:17)
[        ] <asynchronous suspension>
[        ] #8      IncrementalCompiler.computeDelta.<anonymous closure>
(package:front_end/src/fasta/incremental_compiler.dart)
[        ] #9      CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
[        ] #10     new Future.sync (dart:async/future.dart:222:31)
[        ] #11     CompilerContext.runInContext.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:19)
[        ] #12     _rootRun (dart:async/zone.dart:1190:13)
[        ] #13     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #14     _runZoned (dart:async/zone.dart:1630:10)
[        ] #15     runZoned (dart:async/zone.dart:1550:10)
[        ] #16     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
[        ] #17     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:218:20)
[        ] #18     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)
[        ] #19     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:519:59)
[        ] #20     new Future.<anonymous closure> (dart:async/future.dart:174:37)
[        ] #21     _rootRun (dart:async/zone.dart:1182:47)
[        ] #22     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ] #25     _rootRun (dart:async/zone.dart:1190:13)
[        ] #26     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
[        ] #28     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
[        ] #29     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
[        ] #30     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
[        ] #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[        ] '.
[        ] This might be a bug.
[        ] The Dart team would greatly appreciate it if you would take a moment to report this problem at
http://dartbug.com/new.
[        ] If you are comfortable with it, it would improve the chances of fixing any bug if you included the file
../../../AppData/Local/Temp/initialize_from.dillcf30d01a/initialize_from.dill.gz in your error report, but be aware that
this file includes your source code.
[        ] Either way, you should probably delete the file so it doesn't use unnecessary disk space.
```

**Comment by eseidel** [comment]
[initialize_from.dill.gz](https://github.com/flutter/flutter/files/4783418/initialize_from.dill.gz)

**Comment by jonahwilliams** [comment]
This will be fixed by: https://github.com/flutter/flutter/pull/59184

We've been accidentally suppressing compiler messages from web builds.

**Comment by eseidel** [comment]
FWIW, `C:\src\engine\src\out\host_debug_unopt\flutter_web_sdk\kernel\flutter_ddc_sdk.dill` exists:

**Comment by eseidel** [comment]
@jonahwilliams the compiler failure or the hiding of the failure message (which I filed separately as https://github.com/flutter/flutter/issues/59510)?

**Comment by jonahwilliams** [comment]
hiding of the failure message. The compiler error looks new but it _should_ be non-fatal

**Comment by jonahwilliams** [comment]
```
[+1584 ms] Error: Error when reading '/src/engine/src/out/host_debug_unopt/flutter_web_sdk/kernel/flutter_ddc_sdk.dill':
The system cannot find the path specified.
```

I wonder where it went? this is definitely new

**Comment by eseidel** [comment]
I moved the build dir out of the way, and that made the NoSuchMethodError from nodeRaw go away (since it's no longer trying to resume a build).  However the build still fails with the same failing to read the engine .dill file and then missing cannonical name.

Gist: https://gist.github.com/eseidel/1b9615393615085337696b9fc504c5a5

**Comment by jonahwilliams** [comment]
I wonder if the local engine is passing through the flag incorrectly, maybe it should be a file URI and not a  ... whatever it is now.

**Comment by jonahwilliams** [comment]
The logic to convert it to a path is here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/artifacts.dart#L556

It is passed to the compiler here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/compile.dart#L671

I bet converting to a file URI would fix the issue

**Comment by eseidel** [comment]
In support of Jonah's theory, when running normally, the dill path is a file:/// url.  Here is a gist from a normal run: https://gist.github.com/eseidel/49d031cf3eb821a92a374ad27b92caad

**Comment by eseidel** [comment]
Seems to work if I pass `--local-engine-src-path=C:\src\engine\src`.  So the bug may just be user error.  If you pass a unix-style path to flutter when using a local engine on windows it doesn't notice your error, but later causes the dart compiler to fail?

**Comment by eseidel** [comment]
Successful run using a windows-style path: https://gist.github.com/eseidel/7f2f7bc5211c5c87a95d5c9c298efd82

**Comment by jonahwilliams** [comment]
🔥

**Comment by ferhatb** [comment]
@jonahwilliams : any update on this, since it seems to be path related, dropped priority.

**Comment by jonahwilliams** [comment]
The tool needs to validate local engine paths better for windows. I've started refactoring the paths here: https://github.com/flutter/flutter/commit/7f2ca5e532b4052bd1e00d466493f9b583a7ca23#diff-e0fab19c064de2842e3d958d9eab00bcbbdf1426916becdfcc878a35bd5f9935 .

Thanks for the FYI, I'll make sure this is updated to include windows style path validation
