### ISSUE TITLE
Execution FAILED for task ':app:compileFlutterBuildDebug'.

### ISSUE THREAD

**Issue by ManukrishnanP** [flutter/flutter#59449]
## Steps to Reproduce

1. ...flutter create flutterapp5
2. ...flutter run

## Logs

```FLUTTER RUN -V OUTPUT
[√] Flutter (Channel dev, 1.20.0-0.0.pre, on Windows, locale en-US)
    • Flutter version 1.20.0-0.0.pre at C:\Users\admin\AppData\Local\Android\flutter
    • Framework revision d9653445f4 (5 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\admin\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\admin\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • vivo 1901 • 192.168.0.2:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
```

FLUTTER RUN -V OUTPUT

[ +150 ms] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +89 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] d9653445f4d1257b5f5adb4b271d1316469e8cf1
[   +1 ms] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git tag --contains HEAD
[ +249 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.0-0.0.pre
[  +17 ms] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +73 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/dev
[        ] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git ls-remote --get-url origin
[  +57 ms] Exit code 0 from: git ls-remote --get-url origin
[   +9 ms] https://github.com/flutter/flutter.git
[ +127 ms] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +113 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +88 ms] List of devices attached
           192.168.0.2:5555       device product:1901 model:vivo_1901 device:1901 transport_id:3
[   +9 ms] C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.2:5555 shell getprop
[+2053 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +27 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +36 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +283 ms] Generating E:\fxs\flutterprojects\flutter_app5\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +42 ms] ro.hardware = mt6765
[   +1 ms] ro.build.characteristics = overseas
[ +107 ms] Starting incremental build...
[   +6 ms] Initializing file store
[  +49 ms] Skipping target: gen_localizations
[  +26 ms] complete
[  +33 ms] Launching lib\main.dart on vivo 1901 in debug mode...
[  +13 ms] C:\Users\admin\AppData\Local\Android\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\admin\AppData\Local\Android\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\admin\AppData\Local\Android\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\admin\AppData\Local\Temp\flutter_tools.4b8f5f61\flutter_tool.e04696cb\app.dill --packages .packages -Ddart.vm.profile=false    
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts    
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[ +120 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.2:5555 shell -x logcat -v time -t 1
[ +277 ms] Exit code 0 from: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 192.168.0.2:5555 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           06-15 10:35:27.475 E/BrightnessChangeTracker( 1078): abstat is empty
[  +23 ms] <- compile package:flutterapp5/main.dart
[  +40 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[ +202 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.2-6538114
                    Installed as C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +6 ms] executing: C:\Users\admin\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +92 ms] Building APK
[  +53 ms] Running Gradle task 'assembleDebug'...
[  +27 ms] gradle.properties already sets `android.enableR8`
[  +11 ms] Using gradle from E:\fxs\flutterprojects\flutter_app5\android\gradlew.bat.
[  +50 ms] E:\fxs\flutterprojects\flutter_app5\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +58 ms] executing: C:\Program Files\Android\Android Studio2\jre\bin\java -version
[ +187 ms] Exit code 0 from: C:\Program Files\Android\Android Studio2\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +8 ms] executing: [E:\fxs\flutterprojects\flutter_app5\android/] E:\fxs\flutterprojects\flutter_app5\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=E:\fxs\flutterprojects\flutter_app5\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+4589 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [ +179 ms] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +136 ms] [  +95 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +58 ms] [        ] d9653445f4d1257b5f5adb4b271d1316469e8cf1
[  +99 ms] [   +1 ms] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git tag --contains HEAD
[  +36 ms] [ +303 ms] Exit code 0 from: git tag --contains HEAD
[  +69 ms] [        ] 1.20.0-0.0.pre
[   +1 ms] [  +20 ms] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] [  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] [        ] origin/dev
[   +5 ms] [        ] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git ls-remote --get-url origin
[  +52 ms] [  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] [        ] https://github.com/flutter/flutter.git
[   +5 ms] [ +159 ms] executing: [C:\Users\admin\AppData\Local\Android\flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] [ +141 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +54 ms] [        ] dev
[  +62 ms] [  +78 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +55 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +57 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] [  +54 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +55 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +52 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +59 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +62 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +8 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +55 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +57 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +2 ms] [ +157 ms] Initializing file store
[   +2 ms] [  +44 ms] Done initializing file store
[   +5 ms] [  +86 ms] Skipping target: gen_localizations
[ +789 ms] [+1324 ms] Skipping target: kernel_snapshot
[ +509 ms] [ +529 ms] Skipping target: debug_android_application
[  +48 ms] [   +1 ms] Persisting file store
[ +115 ms] [  +32 ms] Done persisting file store
[  +32 ms] [  +11 ms] build succeeded.
[  +76 ms] [  +43 ms] "flutter assemble" took 2,321ms.
[   +2 ms] [   +8 ms] ensureAnalyticsSent: 1ms
[   +1 ms] [   +3 ms] Running shutdown hooks
[  +64 ms] [        ] Shutdown hooks complete
[  +12 ms] [  +15 ms] exiting with code 0
[  +63 ms] > Task :app:compileFlutterBuildDebug FAILED
[  +48 ms] 1 actionable task: 1 executed
[   +5 ms] FAILURE: Build failed with an exception.
[  +65 ms] * Where:
[   +1 ms] Script 'C:\Users\admin\AppData\Local\Android\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
[   +1 ms] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command 'C:\Users\admin\AppData\Local\Android\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[  +64 ms] BUILD FAILED in 7s
[ +328 ms] Running Gradle task 'assembleDebug'... (completed in 8.4s)
[+3271 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 15,461ms.
[  +35 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:578:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:829:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[ +194 ms] ensureAnalyticsSent: 121ms
[   +1 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +34 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

```
```

**Comment by ManukrishnanP** [comment]
I have tried changing the channel to master, stable, and beta.
Nothing Works. :-(
I have reinstalled Android SDK, Flutter SDK, and android studio.
The issue persists no matter what.
Thanks for help in advance!!

**Comment by iapicca** [comment]
Hi @ManukrishnanP 
given the error
```bash
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command 'C:\Users\admin\AppData\Local\Android\flutter\bin\flutter.bat'' finished with non-zero exit value 1
```
could you please run `which flutter` from your windows terminal 
(not inside android studio, vs code or other ide)
Thank you

**Comment by ManukrishnanP** [comment]
I think there is no which in windows and an equivalent of that is the 'where' command and here is what came for that thank you BTW!! :-)
![image](https://user-images.githubusercontent.com/60788038/84684116-d478f800-af55-11ea-91de-1ccc10f8306c.png)

**Comment by TahaTesser** [comment]
Hi @ManukrishnanP 
I am not sure why you have two outputs
@iapicca was referring  to https://flutter.dev/docs/get-started/install/windows#update-your-path

Open your environmental variable and provide screenshot 
Thank you

**Comment by ManukrishnanP** [comment]
Thank you for the response hope the problem gets solved asap
![image](https://user-images.githubusercontent.com/60788038/84752657-a2aa7480-afdb-11ea-9dce-5f019ec20aab.png)

**Comment by ManukrishnanP** [comment]
Any Update needed??

**Comment by ManukrishnanP** [comment]
Pleeeaaaaaseeee help

**Comment by exeptionerror** [comment]
[[Solved] How to solve Execution failed for task ‘:app:compileFlutterBuildDebug’ in Flutter
](https://fluttercorner.com/how-to-solve-execution-failed-for-task-appcompileflutterbuilddebug-in-flutter/)

**Comment by ashumeow** [comment]
Hello everybody here,

I undergone the issue despite of getting no issue even after running <code>flutter doctor -v</code> --- No solution available anywhere including stackoverflow

Earlier, I tried keeping the backup copy after everytime I update my production base and I replace once it gets similar error during the build. This was totally hectic and horrifying. --- I got this idea from stackoverflow, but this was not a solution.

Finally, I resolved the issue this wednesday and I felt to share it out here... 

After getting the issue, then immediately follow the below steps.

<b>Step 1:</b> Goto <code>build.gradle</code> and go down, you will find the below piece of code along with run icon 

![image](https://user-images.githubusercontent.com/5597047/114780776-8654a100-9d80-11eb-8b58-d2e17ca82a24.png)

<b>Step 2: </b> Click run icon and click the first option as show below.

![image](https://user-images.githubusercontent.com/5597047/114780915-ae440480-9d80-11eb-8490-b698ce2c0c1b.png)

<b>Step 3:</b> This will completely clean your project. After that, run your build / project (i.e. main.dart). It will work. 

I hope that it will help others who undergone same issue. This also resolves https://github.com/flutter/flutter/issues/27593

:)
