### ISSUE TITLE
Crash report sent (report ID: 9ae32a07e20ee59e) Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by jyothimarkal** [flutter/flutter#59452]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color build apk

## exception

NoSuchMethodError: NoSuchMethodError: The method 'reinitialize' was called on null.
Receiver: null
Tried calling: reinitialize()

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:105:18)
<asynchronous suspension>
#2      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:106:26)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at E:\Flutter\flutter
    • Framework revision 27321ebbad (6 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = C:\Users\INTEL\androidsdk
      but Android SDK not found at this location.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @jyothimarkal 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
Hi @jyothimarkal 
Make sure you have Android SDK at your ANDROID_HOME location.
The crash should be fixed at https://github.com/flutter/flutter/issues/46888, closing as duplicate
