### ISSUE TITLE
StackOverFlowError: While doing test for production

### ISSUE THREAD

**Issue by bookreader732** [flutter/flutter#59466]
```bash
Mate 9
Test ID

1
Screen Size

1080 × 1920
Test Duration

300 seconds
Screen Density (dpi)
480
Model Name
Mate 9
RAM
4096 MB
Manufacturer
Huawei
OpenGL ES Version
3.2
Android Version
Android 7.0
Native Platform
armeabi-v7a
Locale
fr_FR
CPU Make
HiSilicon
CPU Model
KIRIN960
Issue: java.lang.StackOverflowError: stack size 1037KB

FATAL EXCEPTION: Thread-3
Process: androidx.test.tools.crawler.stubapp, PID: 10669
java.lang.StackOverflowError: stack size 1037KB
	at android.util.LongArray.clone(LongArray.java:117)
	at android.view.accessibility.AccessibilityNodeInfo.init(AccessibilityNodeInfo.java:2887)
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:2704)
	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:198)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:272)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:851)
	at android.support.test.uiautomator.e.a(ByMatcher.java:24)
	at android.support.test.uiautomator.e.a(ByMatcher.java:27)
```

**Comment by iapicca** [comment]
Hi @bookreader732 
Can you please provide your `flutter doctor -v`, 
your `crash logs`, 
your `pubspec.yaml`, 
the list of affected devices and if possible 
your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by VladyslavBondarenko** [comment]
@bookreader732 
closing the issue as non-actionable. Please provide steps to reproduce it and I'll reopen
