### ISSUE TITLE
Flutter Web release version Attempted to build a minified:N2, but it already has an HTML element FLT-PICTURE.

### ISSUE THREAD

**Issue by mayankjanmejay** [flutter/flutter#59473]
Hi, 

I designed my app on flutter for android and now i am trying to compile it for web. The application loads and works correctly in debug mode but when I build a release version of the app and post it to any server or try to run it on localhost the login page loads currently but after login when I try to go to usermain I get endless number of errors as shown in the image. 

The project files can be found at https://github.com/mayankjanmejay/gTMSpwa

Login password is "Green123"

![image](https://user-images.githubusercontent.com/35850067/84672018-b6e56780-af30-11ea-8ce8-5feda9de32dd.png)

Attempted to build a minified:N_, but it already has an HTML element FLT-CLIP.
js_primitives.dart:47 Throw of null.
    at Object.c (http://localhost/6/main.dart.js:2254:3)
    at N_.dV (http://localhost/6/main.dart.js:28537:26)
    at N_.dV (http://localhost/6/main.dart.js:28580:6)
    at MY.dV (http://localhost/6/main.dart.js:28587:8)
    at MV.dV (http://localhost/6/main.dart.js:28587:8)
    at MY.dV (http://localhost/6/main.dart.js:28587:8)
    at MY.dV (http://localhost/6/main.dart.js:28587:8)
    at MY.dV (http://localhost/6/main.dart.js:28587:8)
    at N_.dV (http://localhost/6/main.dart.js:28587:8)
    at MY.dV (http://localhost/6/main.dart.js:28587:8)
js_primitives.dart:47 Attempted to build a minified:N2, but it already has an HTML element FLT-PICTURE.
js_primitives.dart:47 Throw of null.

**Expected results:** 
The app is meant to navigate to another page after login script. The login script works on web too but after the login script is finished it just wont navigate to another page.

```
flutter analyze
Analyzing 5...                                                          

   info - Unused import: 'package:GreenTMSPWA/shared/classes.dart' - lib\builders\userMainIcons.dart:6:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/functions.dart' - lib\builders\userMainIcons.dart:7:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/functionsHTTP.dart' - lib\builders\userMainIcons.dart:8:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/globals.dart' - lib\builders\userMainIcons.dart:9:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/classesHTTP.dart' - lib\builders\userMainIcons.dart:10:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/routes.dart' - lib\builders\userMainIcons.dart:11:8 - unused_import
   info - Unused import: 'package:draggable_scrollbar/draggable_scrollbar.dart' - lib\builders\userMainIcons.dart:13:8 - unused_import
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\builders\userMainIcons.dart:52:7 - missing_return
   info - Unused import: 'package:GreenTMSPWA/shared/functions.dart' - lib\components\addTiles.dart:2:8 - unused_import
   info - Unused import: 'package:font_awesome_flutter/font_awesome_flutter.dart' - lib\components\addTiles.dart:4:8 - unused_import
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: AddTile.scaffoldKey - lib\components\addTiles.dart:6:7 - must_be_immutable       
   info - Unused import: 'package:GreenTMSPWA/shared/app_localizations.dart' - lib\main.dart:3:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/application.dart' - lib\main.dart:4:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/functionsHTTP.dart' - lib\main.dart:5:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/globals.dart' - lib\main.dart:7:8 - unused_import
   info - Unused import: 'package:flutter_ip/flutter_ip.dart' - lib\main.dart:14:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/functionsHTTP.dart' - lib\shared\allTranslations.dart:4:8 - unused_import
   info - Equality operator `==` invocation with references of unrelated types - lib\shared\classes.dart:179:28 - unrelated_type_equality_checks
   info - Equality operator `==` invocation with references of unrelated types - lib\shared\classes.dart:179:38 - unrelated_type_equality_checks
   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\shared\classesHTTP.dart:4:8 - unused_import
   info - Unused import: 'package:flutter/material.dart' - lib\shared\classesHTTP.dart:5:8 - unused_import
   info - Unused import: 'package:url_launcher/url_launcher.dart' - lib\shared\classesHTTP.dart:6:8 - unused_import
   info - Unused import: 'dart:convert' - lib\shared\functions.dart:2:8 - unused_import
   info - Unused import: 'dart:io' - lib\shared\functions.dart:3:8 - unused_import
   info - Unused import: 'dart:math' - lib\shared\functions.dart:4:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/classes.dart' - lib\shared\functions.dart:6:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/functionsHTTP.dart' - lib\shared\functions.dart:7:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/pageLogin.dart' - lib\shared\functions.dart:8:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/private.dart' - lib\shared\functions.dart:9:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/translations.dart' - lib\shared\functions.dart:11:8 - unused_import
   info - Unused import: 'package:animated_text_kit/animated_text_kit.dart' - lib\shared\functions.dart:12:8 - unused_import
   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\shared\functions.dart:13:8 - unused_import
   info - Unused import: 'package:crypto/crypto.dart' - lib\shared\functions.dart:14:8 - unused_import
   info - Don't import implementation files from another package - lib\shared\functions.dart:15:8 - implementation_imports
   info - Unused import: 'package:convert/src/hex.dart' - lib\shared\functions.dart:15:8 - unused_import
   info - Unused import: 'package:flutter_html_to_pdf/flutter_html_to_pdf.dart' - lib\shared\functions.dart:17:8 - unused_import
   info - Unused import: 'package:http/http.dart' - lib\shared\functions.dart:19:8 - unused_import
   info - Unused import: 'package:http/http.dart' - lib\shared\functions.dart:22:8 - unused_import
   info - Unused import: 'package:mongo_dart/mongo_dart.dart' - lib\shared\functions.dart:23:8 - unused_import
   info - Unused import: 'package:url_launcher/url_launcher.dart' - lib\shared\functions.dart:25:8 - unused_import
   info - Duplicate import - lib\shared\functions.dart:29:8 - duplicate_import
   info - Unused import: 'dart:convert' - lib\shared\functions.dart:29:8 - unused_import
   info - Duplicate import - lib\shared\functions.dart:31:8 - duplicate_import
   info - Unused import: 'dart:io' - lib\shared\functions.dart:31:8 - unused_import
   info - The value of the local variable 'externalDirectory' isn't used - lib\shared\functions.dart:240:11 - unused_local_variable
   info - The value of the local variable 'tempDirectory' isn't used - lib\shared\functions.dart:243:11 - unused_local_variable
   info - Unused import: 'dart:io' - lib\shared\functionsHTTP.dart:5:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/functions.dart' - lib\shared\functionsHTTP.dart:7:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/globals.dart' - lib\shared\functionsHTTP.dart:8:8 - unused_import
   info - Unused import: 'package:cloud_firestore/cloud_firestore.dart' - lib\shared\functionsHTTP.dart:10:8 - unused_import
   info - Unused import: 'package:flutter/cupertino.dart' - lib\shared\functionsHTTP.dart:11:8 - unused_import
   info - Unused import: 'package:flutter/foundation.dart' - lib\shared\functionsHTTP.dart:12:8 - unused_import
   info - Unused import: 'package:flutter/material.dart' - lib\shared\functionsHTTP.dart:13:8 - unused_import
   info - Unused import: 'package:shared_preferences/shared_preferences.dart' - lib\shared\functionsHTTP.dart:15:8 - unused_import
   info - Unused import: 'package:http/http.dart' - lib\shared\functionsHTTP.dart:18:8 - unused_import
   info - This function has a return type of 'FutureOr<String>', but doesn't end with a return statement - lib\shared\functionsHTTP.dart:39:16 - missing_return
   info - Unused import: 'package:GreenTMSPWA/shared/app_localizations.dart' - lib\shared\pageLogin.dart:7:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/application.dart' - lib\shared\pageLogin.dart:8:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/translations.dart' - lib\shared\pageLogin.dart:11:8 - unused_import
   info - The value of the local variable 'selector' isn't used - lib\shared\pageLogin.dart:118:20 - unused_local_variable
   info - Unused import: 'dart:convert' - lib\shared\private.dart:4:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/globals.dart' - lib\shared\private.dart:6:8 - unused_import
   info - Unused import: 'package:flutter/foundation.dart' - lib\shared\private.dart:7:8 - unused_import
   info - Unused import: 'package:http/http.dart' - lib\shared\private.dart:8:8 - unused_import
   info - Unused import: 'package:shared_preferences/shared_preferences.dart' - lib\shared\private.dart:9:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/classesHTTP.dart' - lib\shared\private.dart:11:8 - unused_import
   info - Unused import: 'package:http/http.dart' - lib\shared\private.dart:12:8 - unused_import
   info - Unused import: 'package:GreenTMSPWA/shared/functionsHTTP.dart' - lib\shared\translations.dart:3:8 - unused_import

68 issues found. (ran in 3.2s)
```

```
PS C:\Users\MJ\Desktop\5> flutter doctor -v
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.19.0-4.1.pre at D:\flutter
    • Framework revision f994b76974 (6 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at C:\Users\MJ\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\MJ\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

```

</details>

**Comment by vinnytwice** [comment]
@mayankjanmejay Hi, I have the same problem but I see you closed the issue without any solution. What was causing it in your case? I get the error in one of my screen if I use a Textfield.. I'm using them as I use the in another screen and I don't have a problem in the other one..well.. kinda weird...
Thank you.
