### ISSUE TITLE
Building for Moto G4 with older Flutter versions gives "Bad CPU type in executable

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#59486]
I tried building the following sample code with "flutter run --release", when synced to the `v1.2.1` stable release, and got the error "Bad CPU type in executable" when building release. It also failed identically in `v1.7.8+hotfix.4`.

Yes, we could ask people to upgrade (this builds on `v1.9.1+hotfix.6`, for instance), but it does hinder our ability to bisect issues.

<details>
<pre>
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            TextField(
              autofocus: true,
            ),
            Text(
              'You have pushed the button this many times:',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
</pre>
</details>

## command

flutter build aot --suppress-analytics --quiet --target /Users/gspencer/code/manual_tests/lib/simple_test.dart --target-platform android-arm --output-dir /Users/gspencer/code/manual_tests/build/app/intermediates/flutter/release --release

## exception

ProcessException: ProcessException: Bad CPU type in executable
  Command: /Users/gspencer/code/flutter.stable/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot --causal_async_stacks --packages=.packages --deterministic --snapshot_kind=app-aot-blobs --vm_snapshot_data=/Users/gspencer/code/manual_tests/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/Users/gspencer/code/manual_tests/build/app/intermediates/flutter/release/isolate_snapshot_data --vm_snapshot_instructions=/Users/gspencer/code/manual_tests/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/Users/gspencer/code/manual_tests/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /Users/gspencer/code/manual_tests/build/app/intermediates/flutter/release/app.dill

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:140:27)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:68:12)
#2      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:55)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:137:56)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:111:11)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:51:10)
#35     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#36     main (file:///Users/gspencer/code/flutter.stable/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[!] Flutter (Channel unknown, v1.2.1, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.2.1 at /Users/gspencer/code/flutter.stable
    • Framework revision 8661d8aecd (1 year, 4 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Users/gspencer/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.10.0
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/gspencer/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Moto G 4 • ZY223M6WQF • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 2 categories.
```

**Comment by aam** [comment]
Might be related to dropping support of 32-bit binaries on recent versions of mac os.
The command above works fine on that version of flutter on linux.

**Comment by mraleph** [comment]
Yeah, I don't think this is really actionable. You can't target ARM32 using old flutter releases on Catalina.
