### ISSUE TITLE
 ArgumentError: Invalid argument(s): Cannot find executable for ~/flutter/bin/cache/artifacts/usbmuxd/iproxy.

### ISSUE THREAD

**Issue by Alex-Daocaoren** [flutter/flutter#59544]
Today, I  found that my project could not be debugged in my iPhone8(iOS 13.3.1). But, it's work in 
Xcode iPhone8(iOS 13.5) simulator. I open my flutter project by Android Studio, and then attach my iPhone8 device, the IDE Console log like blow:
```
Sending crash report to Google.
```
I copy the crash report log content and paste here, hope useful.

## command

flutter attach --app-id com.myApp.identifier --verbose

## exception
ArgumentError: Invalid argument(s): Cannot find executable for  /Users/byAlex/flutter/bin/cache/artifacts/usbmuxd/iproxy.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:413:27)
#3      IOSDevicePortForwarder.forward (package:flutter_tools/src/ios/devices.dart:703:36)
#4      buildObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:189:20)
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:154:30)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:237:51)
<asynchronous suspension>
#7      AttachCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/attach.dart:177:19)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1465:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#14     AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:176:19)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at  /Users/byAlex/flutter
    • Framework revision f139b11009 (3 个月前), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at  /Users/byAlex/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.7.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone (3) • 6011cdaca0d4c69e1c97fdc605f9298970a97824 • ios • iOS 13.5

! Doctor found issues in 2 categories.
```

**Comment by Alex-Daocaoren** [comment]
After I clean the cache in " /Users/byAlex/flutter/bin/cache/artifacts/engine", and rebuild my project, everything is ok!
