### ISSUE TITLE
I have a problem with urlLaunch

### ISSUE THREAD

**Issue by EchoPuda** [flutter/flutter#59558]
I do not install WhatsApp, but the canLaunch('whatsapp://') return true.

**Comment by EchoPuda** [comment]
and the launch() success with no error, return true but do nothing

**Comment by TahaTesser** [comment]
Hi @EchoPuda 
No whatsapp on my device, i get the error 

<details> 
<summary>logs</summary> 

``` 
E/ViewRootImpl@ff07fbc[MainActivity](29414): Surface is not valid.
D/ViewRootImpl@ff07fbc[MainActivity](29414): MSG_RESIZED_REPORT: frame=(0,0,1080,2340) ci=(0,83,0,39) vi=(0,83,0,39) or=1
E/ViewRootImpl@ff07fbc[MainActivity](29414): Surface is not valid.
D/ViewRootImpl@ff07fbc[MainActivity](29414): stopped(false) old=true
D/SurfaceView(29414): windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{db5d5a7 V.E...... ........ 0,0-1080,2301} of ViewRootImpl@ff07fbc[MainActivity]
D/ViewRootImpl@ff07fbc[MainActivity](29414): stopped(false) old=false
D/SurfaceView(29414): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{db5d5a7 V.E...... ........ 0,0-1080,2301} of ViewRootImpl@ff07fbc[MainActivity]
W/libEGL  (29414): EGLNativeWindowType 0x7a6e01b810 disconnect failed
D/ViewRootImpl@ff07fbc[MainActivity](29414): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=9 res=0x40001 s={true 523565035520} ch=true
D/ViewRootImpl@ff07fbc[MainActivity](29414): RELAYOUT_RES_KEEP_ALIVE_SURFACE on 40001
D/OpenGLRenderer(29414): createReliableSurface : 0x7a6e01b800, 0x79e6e87000
D/mali_winsys(29414): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(29414): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{db5d5a7 V.E...... ........ 0,0-1080,2301}
D/mali_winsys(29414): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(29414): surfaceChanged (1080,2301) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{db5d5a7 V.E...... ........ 0,0-1080,2301}
D/ViewRootImpl@ff07fbc[MainActivity](29414): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(29414): prepareNavigationBarInfo() DecorView@4994a90[MainActivity]
D/InputMethodManager(29414): getNavigationBarColor() -855310
D/InputMethodManager(29414): prepareNavigationBarInfo() DecorView@4994a90[MainActivity]
D/InputMethodManager(29414): getNavigationBarColor() -855310
V/InputMethodManager(29414): Starting input: tba=com.nevercode.triage ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(29414): startInputInner - Id : 0
I/InputMethodManager(29414): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(29414): Input channel destroyed: 'ClientS', fd=87
D/ViewRootImpl@ff07fbc[MainActivity](29414): ViewPostIme pointer 0
D/ViewRootImpl@ff07fbc[MainActivity](29414): ViewPostIme pointer 1
E/flutter (29414): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Could not launch whatsapp://
[38;5;248mE/flutter (29414): #0      Home._launchURL[39;49m
E/flutter (29414): <asynchronous suspension>
[38;5;244mE/flutter (29414): #1      _InkResponseState._handleTap[39;49m
[38;5;244mE/flutter (29414): #2      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244mE/flutter (29414): #3      GestureRecognizer.invokeCallback[39;49m
[38;5;244mE/flutter (29414): #4      TapGestureRecognizer.handleTapUp[39;49m
[38;5;244mE/flutter (29414): #5      BaseTapGestureRecognizer._checkUp[39;49m
[38;5;244mE/flutter (29414): #6      BaseTapGestureRecognizer.handlePrimaryPointer[39;49m
[38;5;244mE/flutter (29414): #7      PrimaryPointerGestureRecognizer.handleEvent[39;49m
[38;5;244mE/flutter (29414): #8      PointerRouter._dispatch[39;49m
[38;5;244mE/flutter (29414): #9      PointerRouter._dispatchEventToRoutes.<anonymous closure>[39;49m
[38;5;244mE/flutter (29414): #10     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)[39;49m
[38;5;244mE/flutter (29414): #11     PointerRouter._dispatchEventToRoutes[39;49m
[38;5;244mE/flutter (29414): #12     PointerRouter.route[39;49m
[38;5;244mE/flutter (29414): #13     GestureBinding.handleEvent[39;49m
[38;5;244mE/flutter (29414): #14     GestureBinding.dispatchEvent[39;49m
[38;5;244mE/flutter (29414): #15     GestureBinding._handlePointerEvent[39;49m
[38;5;244mE/flutter (29414): #16     GestureBinding._flushPointerEventQueue[39;49m
[38;5;244mE/flutter (29414): #17     GestureBinding._handlePointerDataPacket[39;49m
[38;5;244mE/flutter (29414): #18     _rootRunUnary  (dart:async/zone.dart:1206:13)[39;49m
[38;5;244mE/flutter (29414): #19     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter (29414): #20     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)[39;49m
[38;5;244mE/flutter (29414): #21     _invoke1  (dart:ui/hooks.dart:281:10)[39;49m
[38;5;244mE/flutter (29414): #22     _dispatchPointerDataPacket  (dart:ui/hooks.dart:190:5)[39;49m
E/flutter (29414):

``` 

</details> 


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';


void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: _launchURL,
      ),
    );
  }

  _launchURL() async {
    const url = 'whatsapp://';
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (6 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!

``` 

</details>

**Comment by EchoPuda** [comment]
@TahaTesser Hi, Could you run on ios? I forgot to mention that It happens on iOS, Android is normal.

**Comment by TahaTesser** [comment]
```
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           35.0s
Connecting to VM Service at ws://127.0.0.1:55305/pDfleROOuL0=/ws
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Could not launch whatsapp://
[38;5;248m#0      Home._launchURL[39;49m
<asynchronous suspension>
[38;5;244m#1      _InkResponseState._handleTap[39;49m
[38;5;244m#2      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244m#3      GestureRecognizer.invokeCallback[39;49m
[38;5;244m#4      TapGestureRecognizer.handleTapUp[39;49m
[38;5;244m#5      BaseTapGestureRecognizer._checkUp[39;49m
[38;5;244m#6      BaseTapGestureRecognizer.handlePrimaryPointer[39;49m
[38;5;244m#7      PrimaryPointerGestureRecognizer.handleEvent[39;49m
[38;5;244m#8      PointerRouter._dispatch[39;49m
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/ges<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Could not launch whatsapp://
[38;5;248m#0      Home._launchURL[39;49m
<asynchronous suspension>
[38;5;244m#1      _InkResponseState._handleTap[39;49m
[38;5;244m#2      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244m#3      GestureRecognizer.invokeCallback[39;49m
[38;5;244m#4      TapGestureRecognizer.handleTapUp[39;49m
[38;5;244m#5      BaseTapGestureRecognizer._checkUp[39;49m
[38;5;244m#6      BaseTapGestureRecognizer.handlePrimaryPointer[39;49m
[38;5;244m#7      PrimaryPointerGestureRecognizer.handleEvent[39;49m
[38;5;244m#8      PointerRouter._dispatch[39;49m
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/ges<…>

```

**Comment by EchoPuda** [comment]
@TahaTesser ok, I will try again. Thank you for your answer.

**Comment by EchoPuda** [comment]
oh, my bad!
I add whatsapp to CFBundleURLTypes, it make that pass always.
Only need to add it to LSApplicationQueriesSchemes.
Thank you for your time
