### ISSUE TITLE
Having problem to run flutter. First time. Need help .

### ISSUE THREAD

**Issue by fathizack** [flutter/flutter#59560]
I have copy gradle zip to the giberish name under gradle all file and then this happen after that

![image](https://user-images.githubusercontent.com/67011548/84790158-a19d3580-b023-11ea-885a-dae17dac7274.png)

Flutter run

```bash
C:\Users\user.user-PC\Desktop\Flutter Tutorial\app>flutter run
Launching lib\main.dart on Google in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.lang.RuntimeException: Gradle distribution 'C:\Users\user.user-PC\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb' does not contain any directories. Expected to find exactly 1 directory.

        at org.gradle.wrapper.Install.getAndVerifyDistributionRoot(Install.java:115)

        at org.gradle.wrapper.Install.access$000(Install.java:27)

        at org.gradle.wrapper.Install$1.call(Install.java:52)

        at org.gradle.wrapper.Install$1.call(Install.java:48)

        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)

        at org.gradle.wrapper.Install.createDist(Install.java:48)

        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)

        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                              5.6s
Exception: Gradle task assembleDebug failed with exit code 1

```
Doctor 
```console
C:\Users\user.user-PC\Desktop\Flutter Tutorial\app>flutter doctor -v
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.17.3 at C:\src\flutter\flutter
    • Framework revision b041144f83 (12 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\user.user-PC\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\user.user-PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Google • 192.168.55.101:5555 • android-x86 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

Force upgrade  

```bash
C:\Users\user.user-PC\Desktop\Flutter Tutorial\app>flutter upgrade --force
ProcessException: Process exited abnormally:
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
  Command: git fetch --tags
```

Run Verbose
```bash
C:\Users\user.user-PC\Desktop\Flutter Tutorial\app>flutter run --verbose
[  +77 ms] executing: [C:\src\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +421 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] b041144f833e05cf463b8887fa12efdec9493488
[   +2 ms] executing: [C:\src\flutter\flutter/] git tag --contains HEAD
[ +761 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.17.3
[  +28 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +456 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\src\flutter\flutter/] git ls-remote --get-url origin
[ +287 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +498 ms] executing: [C:\src\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[ +392 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +146 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +103 ms] executing: C:\Users\user.user-PC\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +181 ms] List of devices attached
           192.168.55.101:5555    device product:vbox86p model:Google device:vbox86p transport_id:3
[  +14 ms] C:\Users\user.user-PC\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.55.101:5555 shell getprop
[ +202 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +674 ms] Generating C:\Users\user.user-PC\Desktop\Flutter Tutorial\app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +69 ms] ro.hardware = vbox86
[   +1 ms] ro.build.characteristics = nosdcard
[ +116 ms] Launching lib\main.dart on Google in debug mode...
[  +22 ms] C:\src\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root C:\src\flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\USER~1.USE\AppData\Local\Temp\flutter_tool.ae87e6b9-afdd-11ea-b230-cfdcb6445cb1\app.dill
--packages C:\Users\user.user-PC\Desktop\Flutter Tutorial\app\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[ +108 ms] executing: C:\Users\user.user-PC\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.55.101:5555 shell -x logcat -v time -t 1
[ +188 ms] Exit code 0 from: C:\Users\user.user-PC\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.55.101:5555 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           06-16 10:28:36.387 W/WifiMode(  556): WiredSSID, Invalid SupportedRates!!!
[ +118 ms] <- compile package:app/main.dart
[ +297 ms] executing: C:\Users\user.user-PC\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +434 ms] Android Debug Bridge version 1.0.41
           Version 30.0.2-6538114
           Installed as C:\Users\user.user-PC\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +5 ms] executing: C:\Users\user.user-PC\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +226 ms] Building APK
[ +170 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[  +12 ms] Using gradle from C:\Users\user.user-PC\Desktop\Flutter Tutorial\app\android\gradlew.bat.
[   +3 ms] C:\Users\user.user-PC\Desktop\Flutter Tutorial\app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +18 ms] executing: [C:\Users\user.user-PC\Desktop\Flutter Tutorial\app\android/] C:\Users\user.user-PC\Desktop\Flutter Tutorial\app\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-x86 -Ptarget=C:\Users\user.user-PC\Desktop\Flutter Tutorial\app\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2142 ms] Exception in thread "main" java.lang.RuntimeException: Gradle distribution
'C:\Users\user.user-PC\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb' does not contain any directories. Expected to find exactly 1
directory.
[   +7 ms]      at org.gradle.wrapper.Install.getAndVerifyDistributionRoot(Install.java:115)
[   +1 ms]      at org.gradle.wrapper.Install.access$000(Install.java:27)
[   +1 ms]      at org.gradle.wrapper.Install$1.call(Install.java:52)
[   +1 ms]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[   +2 ms]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[   +2 ms]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[   +1 ms]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[   +1 ms]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[ +232 ms] Running Gradle task 'assembleDebug'... (completed in 2.4s)
[+13374 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +7 ms] "flutter run" took 19,378ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by jonahwilliams** [comment]
Sounds like Gradle downloaded a corrupted zip. I would recommend deleting that directory and restarting.

**Comment by fathizack** [comment]
> Sounds like Gradle downloaded a corrupted zip. I would recommend deleting that directory and restarting.

Will try that

**Comment by fathizack** [comment]
> Sounds like Gradle downloaded a corrupted zip. I would recommend deleting that directory and restarting.

nope, still got the same problem. Other suggestion ?

**Comment by TahaTesser** [comment]
Hi @fathizack 
From which location you have deleted `.gradle` from app? App or home directory?

Go to C -> users -> name -> .gradle folder (show hidden files to see this) and you will see something with wrapper and gradle versions **go back and delete `.gradle` from user directory** 
Run the app and it will take time to download new gradle an launch the app 

<img width="645" alt="Screenshot 2020-06-18 at 3 19 46 PM" src="https://user-images.githubusercontent.com/48603081/85006047-3f554980-b177-11ea-8d7f-273ff0627e42.png">

**Comment by fathizack** [comment]
> Hi @fathizack
> Go to C -> users -> delete `.gradle` from user directory** and also delete .gradle from your app android folder
> Run the app and it will take time to download new gradle an launch the app and most importantly let it download properly, don't stop or pause it otherwise it will get issues

I use vs code. Andr studio is too much for my laptop. I already download it and takes ages(in flutter run), i dont want to download it again. Also i download gradle zip from their website(in the picture in my desc. I see your pic in my gmail. do i have to download all of that gradle version ?

**Comment by TahaTesser** [comment]
@fathizack 
As far as i know, you don't need to download zip gradle, simply delete the  `.gradle` folder as mentioned [earlier](https://github.com/flutter/flutter/issues/59560#issuecomment-645912305) execute `flutter run --verbose` and it will download gradle and launch the app fro you

**Comment by fathizack** [comment]
> @fathizack
> As far as i know, you don't need to download zip gradle, simply delete the `.gradle` folder as mentioned [earlier](https://github.com/flutter/flutter/issues/59560#issuecomment-645912305) execute `flutter run --verbose` and it will download gradle and launch the app fro you
I tried that but even with fast internet it's taking forever to finish. The hell XD

**Comment by TahaTesser** [comment]
@fathizack 
Did you manage to solve the issue?
Thank you

**Comment by fathizack** [comment]
@TahaTesser 
No. I try at least 5 hour download everyday, but that don't even finish the gradle. I just want to give up now.

**Comment by iapicca** [comment]
Hi @fathizack 
I'm sorry to hear that,

I'm closing the issue for now;
when you will have the opportunity of completing the steps indicated by @TahaTesser 
please comment below and I will reopen it

Thank you
