### ISSUE TITLE
 flutter channel beta/ flutter upgrade， Unhandled exception

### ISSUE THREAD

**Issue by YI--** [flutter/flutter#59649]
## Steps to Reproduce

1.  flutter channel beta
2.  flutter upgrade

## Logs

```
PS C:\Users\erem> flutter doctor                                                                                        Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[!] Proxy Configuration
    ! NO_PROXY is not set
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
PS C:\Users\erem> flutter upgrade
Flutter is already up to date on channel stable
Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (13 days ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
PS C:\Users\erem> flutter channel beta
Switching to flutter channel 'beta'...
git: Branch 'beta' set up to track remote branch 'beta' from 'origin'.
git: Switched to a new branch 'beta'
Successfully switched to flutter channel 'beta'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
PS C:\Users\erem> flutter upgrade
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 9a28c3bcf40ce64fee61e807ee3e1395fd6bd954...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...


Unhandled exception:
Invalid argument(s): Cannot find executable for git.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      _runGit (package:flutter_tools/src/version.dart:665:23)
#4      new FlutterVersion (package:flutter_tools/src/version.dart:54:26)
#5      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:138:29)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#10     flutterVersion (package:flutter_tools/src/globals.dart:88:46)
#11     new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:192:51)
#12     new Usage (package:flutter_tools/src/reporting/usage.dart:79:9)
#13     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:195:20)
#14     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#15     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#16     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#18     flutterUsage (package:flutter_tools/src/globals.dart:51:35)
#19     _handleToolError (package:flutter_tools/runner.dart:122:13)
#20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:76:13)
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:70:17)
#22     _rootRunBinary (dart:async/zone.dart:1222:13)
#23     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#24     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1601:18)
#25     _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
#26     Future._propagateToListeners (dart:async/future_impl.dart:646:16)
#27     Future._completeError (dart:async/future_impl.dart:537:5)
#28     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
#30     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#31     _rootRunBinary (dart:async/zone.dart:1214:47)
#32     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#33     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#34     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#35     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#36     Future._completeError (dart:async/future_impl.dart:537:5)
#37     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
#38     _rootRun (dart:async/zone.dart:1190:13)
#39     _CustomZone.run (dart:async/zone.dart:1093:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
PS C:\Users\erem>

```

```
PS C:\Users\erem> flutter doctor                                                                                        Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[!] Proxy Configuration
    ! NO_PROXY is not set
[!] Connected device
    ! No devices available
```

**Comment by YI--** [comment]
Please close, the problem has been solved

**Comment by mawg** [comment]
Could you please say how it was solved? I am still having the identical problem.
