### ISSUE TITLE
Oops; flutter has exited unexpectedly: "ProcessException: Process exited abnormally:

### ISSUE THREAD

**Issue by Denmal1982** [flutter/flutter#59662]
## command

flutter build ios

## exception

```bash
ProcessException: ProcessException: Process exited abnormally:
xcodebuild: error: Scheme Runner is not currently configured for the build action.
  Command: /usr/bin/env xcrun xcodebuild -configuration Release -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/admin/StudioProjects/.../app/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/j8/fxvkntdj03n1s1g55sv1gyg80000gn/T/flutter_build_log_pipe.Mffx2W/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```

```bash
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:386:21)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:332:66)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     _runBuildWithRetries (package:flutter_tools/src/ios/mac.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
#28     _rootRunUnary (dart:async/zone.dart:1192:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#33     Future._complete (dart:async/future_impl.dart:516:7)
#34     Stream.fold.<anonymous closure> (dart:async/stream.dart:808:18)
#35     _rootRun (dart:async/zone.dart:1180:38)
#36     _CustomZone.run (dart:async/zone.dart:1077:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#38     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#39     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
#40     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
#41     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#42     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#43     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#44     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#45     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:83:18)
#46     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#47     _rootRun (dart:async/zone.dart:1180:38)
#48     _CustomZone.run (dart:async/zone.dart:1077:19)
#49     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#50     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#51     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
#52     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
#53     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:787:19)
#54     _StreamController._closeUnchecked (dart:async/stream_controller.dart:644:7)
#55     _StreamController.close (dart:async/stream_controller.dart:637:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:1989:21)
#57     _rootRunUnary (dart:async/zone.dart:1196:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#62     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#63     _StreamController._add (dart:async/stream_controller.dart:655:7)
#64     _StreamController.add (dart:async/stream_controller.dart:597:5)
#65     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1534:35)
#66     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1012:18)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#69     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.14.6 18G5033, locale ru-RU)
    • Flutter version 1.17.2 at /Users/admin/flutter
    • Framework revision 5f21edf8b6 (3 недели назад), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @Denmal1982 
does this possible [solution](https://github.com/flutter/flutter/issues/47261#issuecomment-567571747) fix the issue?
Thank you

**Comment by VladyslavBondarenko** [comment]
@Denmal1982 
I hope you solved the issue, closing since long time without a response

**Comment by xz013** [comment]
same , any fix ?

**Comment by iapicca** [comment]
this issue was closed 4 months ago and isn't currently worked on
if the solution mentioned [above](https://github.com/flutter/flutter/issues/59662#issuecomment-645264300) doesn't work for you
please open a new issue providing  your `flutter doctor -v`and your `flutter build ios -v`
