### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/infi_mini/Desktop/Work/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.

### ISSUE THREAD

**Issue by hardikkumbhaniinfilon** [flutter/flutter#59672]
## Command
```
flutter assemble --output=/Users/infi_mini/Desktop/Hardik Flutter/Yoshan/flutter_yoshan/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation= -dDartObfuscation=false -dEnableBitcode= --DartDefines= -dExtraFrontEndOptions= release_ios_bundle_flutter_assets
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/infi_mini/Desktop/Work/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:69:31)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
#12     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
```
```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.2 at /Users/infi_mini/Desktop/Work/flutter
    • Framework revision 5f21edf8b6 (3 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/infi_mini/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro             • 151B8408-68DE-456E-B95F-A7A71E87BDC2 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b712a172f9694745f50505c93340883493b505e5
### Plugins
camera-0.5.2+2
connectivity-0.4.4
fluttertoast-3.1.3
image_picker-0.6.1
path_provider-1.2.0
shared_preferences-0.5.3+4
url_launcher-5.1.1

**Comment by VladyslavBondarenko** [comment]
Hi @hardikkumbhaniinfilon ,
this should be fixed in https://github.com/flutter/flutter/pull/57874, closing as duplicate.
Please file a new issue if you are experiencing this with current dev channel
