### ISSUE TITLE
[video_player] StreamBuilder A VideoPlayerController was used after being disposed

### ISSUE THREAD

**Issue by crtl** [flutter/flutter#59715]
When using multiple VideoPlayerControllers (with StreamBuilders) disposing the controller throws an error when the widget is built despite being disposed correctly and only once.
I have linked a demo with an complete example.

## Steps to Reproduce
1. Clone demo repo: [crtl/flutter-bugs](https://github.com/crtl/flutter-bugs/)
2. Checkout branch `video_player/usedAfterDisposed`
3. Run app
4. Press the button
5. Despite calling dispose before initializing next controller an error is thrown.

**Expected results:**
Should work.

**Actual results:**
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building StreamBuilder<VideoPlayerController>(state:
_StreamBuilderBaseState<VideoPlayerController, AsyncSnapshot<VideoPlayerController>>#f93e0):
A VideoPlayerController was used after being disposed.
Once you have called dispose() on a VideoPlayerController, it can no longer be used.

The relevant error-causing widget was:
  StreamBuilder<VideoPlayerController>
  file:///D:/dev/projects/flutter/flutter-bugs/lib/main.dart:105:16

When the exception was thrown, this was the stack:
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:108:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:114:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:169:12)
#3      _VideoPlayerState.didUpdateWidget (package:video_player/video_player.dart:537:26)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4734:58)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1115:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1054:9)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:970:5)
#20     _invoke (dart:ui/hooks.dart:267:10)
#21     _drawFrame (dart:ui/hooks.dart:225:3)
(elided 3 frames from dart:async)
```

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel master, 1.20.0-1.0.pre.30, on Microsoft Windows [Version 10.0.18362.900], locale de-DE)
    • Flutter version 1.20.0-1.0.pre.30 at D:\dev\flutter
    • Framework revision e96b13c72f (5 days ago), 2020-06-12 09:02:19 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\dev\android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\dev\android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

```

</details>

**Comment by TahaTesser** [comment]
Hi @crtl 
This is an issue with your code, you're disposing controller and then using it 

Try this code sample  and switch video using FAB, i have commented issue line 

<details> 
<summary>Code Sample</summary> 

``` 
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _videos = [
    VideoPlayerController.network(
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"),
    VideoPlayerController.network(
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"),
    VideoPlayerController.network(
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"),
    VideoPlayerController.network(
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"),
  ];

  int _currentIndex = -1;

  VideoPlayerController _activeController;

  final StreamController<VideoPlayerController> _streamController =
      StreamController.broadcast();

  _changeVideo() async {
    _currentIndex++;

    if (_currentIndex > _videos.length) {
      _currentIndex = 0;
    }

    // if (_activeController != null) {
    //   await _activeController.dispose();
    // }

    _activeController = _videos[_currentIndex];

    _activeController.initialize().then((_) {
      _streamController.add(_activeController);
    });

    _activeController.play();
  }

  @override
  void initState() {
    super.initState();

    _changeVideo();
  }

  @override
  void dispose() {
    _activeController?.dispose();
    _streamController.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: StreamBuilder<VideoPlayerController>(
          stream: _streamController.stream,
          builder: (_, snapshot) {
            if (!snapshot.hasData) {
              return CircularProgressIndicator();
            }

            return AspectRatio(
                aspectRatio: snapshot.data.value.aspectRatio,
                child: VideoPlayer(snapshot.data));
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _changeVideo,
        tooltip: 'Change video',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

``` 

</details> 
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (9 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.106

• No issues found!

``` 

</details>

**Comment by crtl** [comment]
Your solution is not working.
You are just omitting the call to dispose so the previous video is not disposed and keeps playing in the background. You will still hear its sound even though its not displayed.

I have added an workaround to the example which is working.
You can now change the behaviour by changing `shouldProduceBug` to true.

**Comment by crtl** [comment]
Any news?

**Comment by kalismeras61** [comment]
@ctrl 

> Any news? Can you please reopen it?

Did you find anything ?

**Comment by maheshmnj** [comment]
Hi @crtl,
Thanks for filing the issue, The issue is reproducible on the latest stable and the master channel with ```video_player: ^2.1.6```. 

 <details>
 <summary>code sample</summary>

 ```
 import 'dart:async';

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: VideoPlayerStream(),
    ),
  );
}

class VideoPlayerStream extends StatefulWidget {
  @override
  _VideoPlayerStreamState createState() => _VideoPlayerStreamState();
}

class _VideoPlayerStreamState extends State<VideoPlayerStream> {
  final List<VideoPlayerController> _videos = [
    VideoPlayerController.network(
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4"),
    VideoPlayerController.network(
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"),
    VideoPlayerController.network(
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4"),
    VideoPlayerController.network(
        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"),
  ];

  int _currentIndex = -1;

  late VideoPlayerController? _activeController;

  final StreamController<VideoPlayerController?> _streamController =
      StreamController.broadcast();

  _changeVideo() async {
    _currentIndex++;
    _currentIndex = _currentIndex % _videos.length;
    _activeController = _videos[_currentIndex];
    await _activeController!.initialize().then((_) {
      _streamController.add(_activeController);
      setState(() {});
    });
  }

  @override
  void initState() {
    super.initState();
    _changeVideo();
  }

  @override
  void dispose() {
    _activeController!.dispose();
    _streamController.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Video Player StreamBuilder'),
        ),
        body: Center(
          child: StreamBuilder<VideoPlayerController?>(
            stream: _streamController.stream,
            builder: (BuildContext _,
                AsyncSnapshot<VideoPlayerController?> snapshot) {
              if (snapshot.data == null || !snapshot.hasData) {
                return CircularProgressIndicator();
              }
              return AspectRatio(
                  aspectRatio: snapshot.data!.value.aspectRatio,
                  child: VideoPlayer(snapshot.data!));
            },
          ),
        ),
        floatingActionButton: StreamBuilder<VideoPlayerController?>(
            stream: _streamController.stream,
            builder: (BuildContext _,
                AsyncSnapshot<VideoPlayerController?>? snapshot) {
              if (!snapshot!.hasData) {
                return Container();
              }
              return Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  FloatingActionButton(
                    onPressed: () {
                      _activeController!.dispose();
                      _streamController.add(null);
                      _changeVideo();
                    },
                    tooltip: 'Change video',
                    child: Icon(Icons.add),
                  ),
                  SizedBox(
                    width: 20,
                  ),
                  FloatingActionButton(
                    onPressed: () {
                      setState(() {
                        // If the video is playing, pause it.
                        if (snapshot.data!.value.isPlaying) {
                          snapshot.data!.pause();
                        } else {
                          // If the video is paused, play it.
                          snapshot.data!.play();
                        }
                      });
                    },
                    tooltip: 'control playback',
                    child: Icon(
                      snapshot.data!.value.isPlaying
                          ? Icons.pause
                          : Icons.play_arrow,
                    ),
                  ),
                ],
              );
            }));
  }
}

 ```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.538, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.3.0-17.0.pre.538 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1fd2f7c400 (2 days ago), 2021-06-27 22:51:02 -0400
    • Engine revision 5d287a2061
    • Dart version 2.14.0 (build 2.14.0-250.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>


<details>
<summary>logs</summary>

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Xcode build done.                                           27.8s
Connecting to VM Service at ws://127.0.0.1:61595/oCpJnFrwqkM=/ws
TX and TY are 0. Rotation: 0. Natural width,height: 1920.000000, 1080.000000
TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building StreamBuilder<VideoPlayerController?>(state: _StreamBuilderBaseState<VideoPlayerController?, AsyncSnapshot<VideoPlayerController?>>#81623):
A VideoPlayerController was used after being disposed.

Once you have called dispose() on a VideoPlayerController, it can no longer be used.
The relevant error-causing widget was
StreamBuilder<VideoPlayerController?>
When the exception was thrown, this was the stack
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
#1      ChangeNotifier._debugAssertNotDisposed
#2      ChangeNotifier.removeListener
#3      _VideoPlayerState.deactivate
#4      StatefulElement.deactivate
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
A VideoPlayerController was used after being disposed.
The relevant error-causing widget was
StreamBuilder<VideoPlayerController?>
════════════════════════════════════════════════════════════════════════════════
Application finished.
Exited (sigterm)
```
</details>
