### ISSUE TITLE
Failed to create datagram socket, OS Error Address already in use

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#59748]
I can't run my app using my iPhone connected to my MacBook Pro. I am keep getting below error. But when I open iOS folder using Xcode my app runs perfectly. But I am developing my app using AndroidStudio and I am not be able debug my app codes. Any idea?

```
Launching lib/main.dart on NTMS iPhone’u in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: **********
Running Xcode build...
Xcode build done.                                           19.5s
Installing and launching...
Failed to establish a debug connection with 00008030-000E54122E21802E using mdns: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.12.13+hotfix.7 at /Users/**********************/flutter
    • Framework revision 9f5ff2306b (5 months ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/****************/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • NTMS iPhone’u • 0000803***********2E • ios • iOS 13.5.1

• No issues found!
```

**Comment by fogelfish** [comment]
Similar or identical issue for me using IntelliJ IDEA 2020.1.  I get the following exception if I press the **Rerun 'main.dart'** bug icon in the Debug panel.

## command

flutter --no-color attach --machine --device-id=DACDF07A-867D-40D3-A6FE-A9D4D18C2CEF lib/main.dart

## exception

SocketException: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353

```
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:760:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:2095:26)
#2      RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:2053:31)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:127:71)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:59:20)
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:151:57)
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:235:51)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
Here is flutter doctor output:

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.4 at /Users/brianfogel/flutter/flutter
    • Framework revision 1ad9baa8b9 (9 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/brianfogel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/brianfogel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 47.0.3
    • Dart plugin version 201.7223.99

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • DACDF07A-867D-40D3-A6FE-A9D4D18C2CEF • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

```

DevTools works as expected. If I set a breakpoint in DevTools, code execution also stops in IntelliJ at the same position, but I do not see the call stack or variables in the IDE.  If I place a breakpoint inside IntelliJ and simply hot reload, code execution does not stop at the breakpoint.

**Comment by jmagman** [comment]
```
  /// The [mDnsPort] allows configuring what port is used for the mDNS
  /// query. If not provided, defaults to `5353`.
```
Hm, guess we should give it an available port.
