### ISSUE TITLE
[tool_crash] FileSystemException: Cannot resolve symbolic links, path = 'D:\development\flutter' (OS Error: The system cannot find the file specified., errno = 2)

### ISSUE THREAD

**Issue by imamnurhy** [flutter/flutter#59770]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot resolve symbolic links, path = 'D:\development\flutter' (OS Error: The system cannot find the file specified.
, errno = 2)
```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:828:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:391:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:58:49)
#3      _compareResolvedPaths (package:flutter_tools/src/runner/flutter_command_runner.dart:529:65)
#4      FlutterCommandRunner._checkFlutterCopy (package:flutter_tools/src/runner/flutter_command_runner.dart:513:21)
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:303:9)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#15     new Future.sync (dart:async/future.dart:224:31)
#16     CommandRunner.run (package:args/command_runner.dart:112:14)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
```
```
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale en-ID)
    • Flutter version 1.17.3 at D:\development\flutter
    • Framework revision b041144f83 (2 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\AndroidStudio\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:/AndroidStudio/Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.46.0)
    • VS Code at C:\Users\Hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • HK1 Max                   • 192.168.0.2:5555 • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 8.0.0 (API 26) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b041144f833e05cf463b8887fa12efdec9493488

**Comment by Blakeboy02** [comment]
Same problem here

**Comment by JoyEnergiser** [comment]
I'm also getting this now out of the blue.I can't remember how it happened but I feel like I did something bad, I think I was doing flutter clean moments after building in debug, then I stared getting this in my output,but everything seems to work fine.

 Socket error: FileSystemException(path=c:\dev\yourcart-flut\build; message=Cannot resolve symbolic links): FileSystemException(path=c:\dev\yourcart-flut\build; message=Cannot resolve symbolic links)
#0      _PhysicalFolder.resolveSymbolicLinksSync (package:analyzer/file_system/physical_file_system.dart:332:7)
#1      _OverlayResource.resolveSymbolicLinksSync (package:analyzer/file_system/overlay_file_system.dart:400:32)
#2      ContextRootImpl._includedFilesInFolder (package:analyzer/src/dart/analysis/context_root.dart:105:40)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:181:26)
#4      DeclarationsContext._findPackages (package:analyzer/src/services/available_declarations.dart:343:51)
#5      DeclarationsTracker.addContext (package:analyzer/src/services/available_declarations.dart:548:25)
#6      LspServerContextManagerCallbacks.listenAnalysisDriver (package:analysis_server/src/lsp/lsp_analysis_server.dart:806:11)
#7      ContextManagerImpl._createAnalysisContexts (package:analysis_server/src/context_manager.dart:429:17)
#8      ContextManagerImpl._handleWatchEventImpl (package:analysis_server/src/context_manager.dart:544:7)
#9      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:524:5)
#10     _rootRunUnary (dart:async/zone.dart:1362:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#16     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:256:10)
#17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#18     _rootRunUnary (dart:async/zone.dart:1362:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
#24     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#25     _rootRunUnary (dart:async/zone.dart:1370:13)
#26     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#29     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#30     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#31     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#32     _rootRun (dart:async/zone.dart:1346:47)
#33     _CustomZone.run (dart:async/zone.dart:1258:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#36     _rootRun (dart:async/zone.dart:1354:13)
#37     _CustomZone.run (dart:async/zone.dart:1258:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#43     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by SebghatYusuf** [comment]
Same problem here
