### ISSUE TITLE
`dart:ffi` conflicts with `System.loadLibrary` on Android API <=23

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#59834]
## Summary

I'm not sure if this is a Dart SDK issue or a Flutter issue.

On Android API versions <=23, calling a function in the Android SDK that does `System.loadLibrary`, followed by a `dart:ffi` `DynamicLibrary.open` fails.

Some examples of the former can be:

- `android.media.SoundPool`, because of the static block [here](https://cs.android.com/android/platform/superproject/+/android-6.0.1_r81:frameworks/base/media/java/android/media/SoundPool.java;l=115;drc=5c768f4c8584d93fae3f5e87c8fdcc88ecfba002)
- `android.webkit.CookieManager.getInstance()`, because it loads `WebViewChromiumFactoryProvider` which loads a library [here](https://source.chromium.org/chromium/chromium/src/+/44.0.2403.119:android_webview/glue/java/src/com/android/webview/chromium/WebViewChromiumFactoryProvider.java;l=370;drc=9d51f6856cb4522a94d0484f0592f18ba99d95a0?originalUrl=https:%2F%2Fcs.chromium.org%2F)

More info in a doc in b/159167352

### Why this happens

When calling `System.loadLibrary` on Android <=23, the Java runtime actually overrides the paths searched during a `dlopen` call ([`g_ld_library_paths`](https://cs.android.com/android/platform/superproject/+/android-6.0.1_r81:bionic/linker/linker.cpp;l=92;drc=379003621a1d2c28c18b42236d1d61ce80c1e92a)) to match that of the classloader for the caller, before calling `dlopen` on the library.

When this is called by a function in the Android SDK (i.e. down the call chain of `CookieManager`), the classloader is different than that of the users application code, and this overrides the `g_ld_library_paths` to exclude the `g_ld_library_paths` of the current application / APK.

`DynamicLibrary.load(‘libsomething.so’)` in Dart is just a thin layer around `dlopen`. This means that if it is called after the `g_ld_library_paths` are overridden, the linker will be unable to find the `libsomething.so` if this was provided from the APK.

## Steps to Reproduce

https://github.com/jiahaog/ffi_android_linker_conflict/commit/a8971f405789a1181dc858e33c5d96a7d6f361ff is a minimal repro

The important files are just 
- app/lib/main.dart
- app/android/app/src/main/java/com/example/ffi_android_linker_conflict/MainActivity.java

**Expected results:** 

`DynamicLibrary.open` succeeds.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
I/flutter ( 5755): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 5755): The following ArgumentError was thrown while handling a gesture:
I/flutter ( 5755): Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libnative_add.so" not
I/flutter ( 5755): found)
I/flutter ( 5755): When the exception was thrown, this was the stack:
I/flutter ( 5755): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
I/flutter ( 5755): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
I/flutter ( 5755): #2      _MyHomePageState._incrementCounter (package:ffi_android_linker_conflict/main.dart:59:26)
I/flutter ( 5755): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
I/flutter ( 5755): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
I/flutter ( 5755): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
I/flutter ( 5755): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
I/flutter ( 5755): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
I/flutter ( 5755): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
I/flutter ( 5755): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
I/flutter ( 5755): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
I/flutter ( 5755): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
I/flutter ( 5755): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
I/flutter ( 5755): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
I/flutter ( 5755): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
I/flutter ( 5755): #18     _invoke1 (dart:ui/hooks.dart:283:10)
I/flutter ( 5755): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:192:5)
I/flutter ( 5755): (elided 3 frames from dart:async)
I/flutter ( 5755): Handler: "onTap"
I/flutter ( 5755): Recognizer:
I/flutter ( 5755):   TapGestureRecognizer#2c717
I/flutter ( 5755): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.118, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.20.0-1.0.pre.118 at /Users/jiahaog/flutter
    • Framework revision 8665e13801 (5 hours ago), 2020-06-18 18:08:01 -0700
    • Engine revision b5f5e6332c
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 54481776c9)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/jiahaog/Library/Android/sdk
    • Platform android-stable, build-tools 30.0.0-rc2
    • Java binary at: /Applications/Android Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by dcharkes** [comment]
Thanks for reporting.

To conform to this we need to make Flutter aware we want to `dlopen` open something, and let Flutter do it: https://github.com/dart-lang/sdk/issues/37771.

**Comment by CaptainDario** [comment]
I am encountering a similar error using the tflite_flutter_plugin.
@dcharkes Currently I am trying to solve this with the workaround (2nd one) you gave [here](https://github.com/flutter/flutter/issues/73318#issuecomment-754598119).
I forked the repo put the following code:
```java
package com.tfliteflutter.tflite_flutter_plugin;

import androidx.annotation.NonNull;
import io.flutter.embedding.engine.plugins.FlutterPlugin;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.PluginRegistry.Registrar;

/** TfliteFlutterPlugin */
public class TfliteFlutterPlugin implements FlutterPlugin, MethodCallHandler {
  @Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
    final MethodChannel channel = new MethodChannel(flutterPluginBinding.getFlutterEngine().getDartExecutor(), "tflite_flutter_plugin");
    channel.setMethodCallHandler(new TfliteFlutterPlugin());
    loadLibrary();
  }

  // This static function is optional and equivalent to onAttachedToEngine. It supports the old
  // pre-Flutter-1.12 Android projects. You are encouraged to continue supporting
  // plugin registration via this function while apps migrate to use the new Android APIs
  // post-flutter-1.12 via https://flutter.dev/go/android-project-migration.
  //
  // It is encouraged to share logic between onAttachedToEngine and registerWith to keep
  // them functionally equivalent. Only one of onAttachedToEngine or registerWith will be called
  // depending on the user's project. onAttachedToEngine or registerWith must both be defined
  // in the same class.
  public static void registerWith(Registrar registrar) {
    final MethodChannel channel = new MethodChannel(registrar.messenger(), "tflite_flutter_plugin");
    channel.setMethodCallHandler(new TfliteFlutterPlugin());    
  }

  @Override
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
    if (call.method.equals("getPlatformVersion")) {
      result.success("Android " + android.os.Build.VERSION.RELEASE);
    } else {
      result.notImplemented();
    }
  }

  @Override
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
  }

  private static boolean isLibraryLoaded = false;

  private static void loadLibrary() {
    if (isLibraryLoaded) {
      return;
    }

    // Loads `libX.so`.
    System.loadLibrary("tensorflowlite_c");
    isLibraryLoaded = true;
  }
}
```

However I am still getting:
```bash
E/flutter ( 2644): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (Cannot load library: load_library[1093]: Library 'libtensorflowlite_c.so' not found)
```

Am I applying the workaround wrongly or is it not working anymore?

**Comment by ilkercankaya** [comment]
@CaptainDario having the same issue, this workaround used to work when i tried it on an x86 emulator android API 16, but it is not working anymore `System.loadLibrary`can not find my native library

**Comment by chinmaygarde** [comment]
From Triage: @jiahaog This issue came up during triage after the tags were updated. It seems like dlopen and loadLibrary don't have identical search paths on all platforms. Is that right? Is this still happening? Also, perhaps there is a workaround where an absolute path is specified. Or, we could use loadLibrary in Java code before calling DylibLibrary.process() in Dart?

**Comment by jiahaog** [comment]
I think this is specific to Android. Some Android SDK methods can override the search paths for dlopen, causing `DynamicLibrary.load` in Dart to fail. I just checked and this is still an issue, at least internally on emulators.

I'm not sure if specifying an absolute path would work, but as you mentioned the workaround we use internally is to use loadLibrary first in Java - see http://shortn/_VKPTUyNSTA

**Comment by dcharkes** [comment]
FWIW, we want to move to more static bindings with `FfiNative`s, with an asset system. In this asset system the embedder will resolve the asset name + symbol name to a memory address. So then the embedder is both in charge of bundling and resolving at runtime.

As such, we have not pursued making the existing `DynamicLibrary.open` go through the embedder. If this is blocking you, we could also do that.

**Comment by leisim** [comment]
@dcharkes This is quite a big issue for me. Is there a known workaround or rough timeline for a fix? This issue has been open for quite a long time.

**Comment by CaptainDario** [comment]
@dcharkes is there still hope for this to be looked at?

**Comment by dcharkes** [comment]
Workarounds are mentioned above.

> FWIW, we want to move to more static bindings with `FfiNative`s, with an asset system. In this asset system the embedder will resolve the asset name + symbol name to a memory address. So then the embedder is both in charge of bundling and resolving at runtime.

This work is in progress. I'd need to double check what is happening with native assets in Android currently. (That landed behind an experiment flag in Flutter last week.) I'd assume that that's also not working currently, because the `dlopen` does not go via Flutter. Flutter only influences the path. I'll take a look at this.

**Comment by CaptainDario** [comment]
Thank you very much! Sadly the workarounds mentioned above do not seem to work for me.

**Comment by reidbaker** [comment]
Closing as the minimum android api version currently supported by flutter is 24.
