### ISSUE TITLE
ArgumentError: Invalid argument (URI scheme not allowed):  while running app on web

### ISSUE THREAD

**Issue by abhiverma825** [flutter/flutter#59924]
```bash
#0      DartUri._recordAbsoluteUri (package:dwds/src/utilities/dart_uri.dart:86:7)
#1      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:60:9)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:87:19)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:145:24)
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:166:37)
<asynchronous suspension>
#5      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:134:23)
#6      DebugService.start (package:dwds/src/services/debug_service.dart:140:55)
#7      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:152:25)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```console
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 1.19.0-4.1.pre at D:\fluttersetup\flutter_windows_v1.12.13+hotfix.9-stable\flutter
    • Framework revision f994b76974 (11 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Abhishek\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Abhishek\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.61

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @abhiverma825 
Can you please provide your `flutter run -d chrome --verbose`,
your `pubspec.yaml`
and a minimal complete reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
@abhiverma825 
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with filling out template

**Comment by berrylawchingman** [comment]
😾🦾
