### ISSUE TITLE
command Flutter doctor seems to crash on Windows 8.1

### ISSUE THREAD

**Issue by shastrisubramaniam** [flutter/flutter#59958]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Subramaniam>cd flutter

C:\Users\Subramaniam\flutter>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine ee76268252c22f5c11e82a7b87423ca3982e51a7...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find
executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable fo
please let us know at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find
executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable fo
please let us know at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:149:7)
#1      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#2      _rootRunBinary (dart:async/zone.dart:1204:38)
#3      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#7      Future._completeError (dart:async/future_impl.dart:534:5)
#8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#9      _informUserOfCrash (package:flutter_tools/runner.dart)
#10     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#11     _rootRunBinary (dart:async/zone.dart:1204:38)
#12     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#13     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#14     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#15     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#16     Future._completeError (dart:async/future_impl.dart:534:5)
#17     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#18     _doctorText (package:flutter_tools/runner.dart)
#19     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#20     _rootRunBinary (dart:async/zone.dart:1204:38)
#21     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#22     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#23     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#24     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#25     Future._completeError (dart:async/future_impl.dart:534:5)
#26     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#27     AppContext.run (package:flutter_tools/src/base/context.dart)
#28     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#29     _rootRunBinary (dart:async/zone.dart:1204:38)
#30     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#31     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#32     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#33     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#34     Future._completeError (dart:async/future_impl.dart:534:5)
#35     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart)
#37     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#38     _rootRunBinary (dart:async/zone.dart:1204:38)
#39     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#40     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#41     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#42     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#43     Future._completeError (dart:async/future_impl.dart:534:5)
#44     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:582:7)
#45     _rootRun (dart:async/zone.dart:1184:13)
#46     _CustomZone.run (dart:async/zone.dart:1077:19)
#47     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by PixelToast** [comment]
Is `C:\Windows\System32\` in your PATH?

**Comment by shastrisubramaniam** [comment]
It was not in my PATH. I have added it in PATH and the issue is resolved.
