### ISSUE TITLE
Android ApplicationDocumentsDirectory contains unwanted Flutter data

### ISSUE THREAD

**Issue by Mirageofmage** [flutter/flutter#59952]
Is it normal for Flutter to store its application data within the application document directory? I'm currently having issues dealing with data that isn't supposed to be present.

## Steps to Reproduce

1. Using path and path_provider, access the Application Documents Directory using getApplicationDocumentsDirectory() in Debug mode.
2. Using StreamBuilder, generate a ListView from a AsyncSnapshot<Directory>
3. Map the snapshot data to list tiles, typecasting the FileSystemEntity to a File

**Expected results:** 
Any files created by the user (within the context of the application) will appear in the ApplicationDocumentsDirectory

**Actual results:** 
The directory flutter_assets also exists in the ApplicationDocumentsDirectory, leading to a typecast exception for _Directory to File. Another file "res_timestamp-5-1592757959383" is also present within the directory.

These files don't appear on iOS builds, so there is no issue there.

<details>
  <summary>Code</summary>

```
Widget build(BuildContext context) {
    return new Scaffold(
      key: _scaffoldKey,
      appBar: new AppBar(
        brightness: Brightness.light,
        title: Text("Local Recordings", style: TextStyle(fontFamily: "Comfortaa")),
      ),
      body: StreamBuilder(
        stream: getApplicationDocumentsDirectory().asStream(),
        builder: (BuildContext context, AsyncSnapshot<Directory> snapshot) {
          if (!snapshot.hasData) return new Text("This is an error 🤔");
          return new ListView(children: getIndivRec(snapshot));
        },
      ),
    );
  }

getIndivRec(AsyncSnapshot<Directory> snapshot) {
    return snapshot.data
        .listSync()
        .map(
          (f) => RecordingsListTile(
            keyD: f.hashCode.toString(),
            text: basename(f.path),
            subtext:
                "File created: ${(f as File).lastModifiedSync().toString()} \nFile Size: ${formatBytes((f as File).lengthSync(), 1)}", //(f as File).lastModifiedSync().toString(), formatBytes((f as File).lengthSync(), 1)
            onSwipe: deletePrompt,
            onConfirm: (DismissDirection dir) async {
              f.delete();
            },
            onTap: () => uploadPrompt(f as File),
          ),
        )
        .toList();
  }

```
</details>

<details>
  <summary>Logs</summary>

flutter run --verbose
```
[  +72 ms] Updating files
[ +739 ms] DevFS: Sync finished
[        ] Syncing files to device AOSP on IA Emulator... (completed in 832ms)
[        ] Synced 1.5MB.
[        ] <- accept
[   +5 ms] Connected to _flutterView/0xdb46a310.
[   +5 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on AOSP on IA Emulator is available at: http://127.0.0.1:57597/rOWCxIX8O7A=/
[ +146 ms] D/EGL_emulation(13505): eglMakeCurrent: 0xdb4118a0: ver 3 0 (tinfo 0xdce03fd0)
[   +8 ms] D/eglCodecCommon(13505): setVertexArrayObject: set vao to 0 (0) 1 0
[+1540 ms] I/com.Jerbb.FoPP(13505): Background concurrent copying GC freed 27184(1581KB) AllocSpace objects, 16(872KB) LOS objects, 49% free,
2MB/4MB, paused 3.117ms total 120.754ms
[  +63 ms] E/flutter (13505): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter 'authentication'
was called on null.
[        ] E/flutter (13505): Receiver: null
[        ] E/flutter (13505): Tried calling: authentication
[        ] E/flutter (13505): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
[        ] E/flutter (13505): #1      AuthService.googleSignInSilent (package:FoPPS/services/auth.dart:69:64)
[        ] E/flutter (13505): <asynchronous suspension>
[        ] E/flutter (13505): #2      _MyHomePageState.initState (package:FoPPS/main.dart:98:17)
[        ] E/flutter (13505): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
[        ] E/flutter (13505): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
[        ] E/flutter (13505): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[        ] E/flutter (13505): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[        ] E/flutter (13505): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
[        ] E/flutter (13505): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[        ] E/flutter (13505): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[        ] E/flutter (13505): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
[        ] E/flutter (13505): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
[        ] E/flutter (13505): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
[        ] E/flutter (13505): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
[        ] E/flutter (13505): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[        ] E/flutter (13505): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[  +11 ms] E/flutter (13505): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
[   +1 ms] E/flutter (13505): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[   +1 ms] E/flutter (13505): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[   +4 ms] E/flutter (13505): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
[        ] E/flutter (13505): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[        ] E/flutter (13505): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[        ] E/flutter (13505): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
[        ] E/flutter (13505): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
[        ] E/flutter (13505): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
[        ] E/flutter (13505): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
[        ] E/flutter (13505): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
[        ] E/flutter (13505): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
[        ] E/flutter (13505): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[        ] E/flutter (13505): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[        ] E/flutter (13505): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
[        ] E/flutter (13505): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[        ] E/flutter (13505): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[        ] E/flutter (13505): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
[        ] E/flutter (13505): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[        ] E/flutter (13505): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[        ] E/flutter (13505): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
[  +11 ms] E/flutter (13505): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
[        ] E/flutter (13505): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
[        ] E/flutter (13505): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
[        ] E/flutter (13505): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
[   +1 ms] E/flutter (13505): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
[   +1 ms] E/flutter (13505): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
[   +1 ms] E/flutter (13505): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
[   +2 ms] E/flutter (13505): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
[        ] E/flutter (13505): #45     Element.rebuil
[  +64 ms] W/DynamiteModule(13505): Local module descriptor class for providerinstaller not found.
[  +18 ms] I/DynamiteModule(13505): Considering local module providerinstaller:0 and remote module providerinstaller:0
[        ] W/ProviderInstaller(13505): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote
version is 0.
[  +60 ms] I/com.Jerbb.FoPP(13505): The ClassLoaderContext is a special shared library.
[  +75 ms] I/chatty  (13505): uid=10090(com.Jerbb.FoPPS) AsyncTask #2 identical 1 line
[        ] I/com.Jerbb.FoPP(13505): The ClassLoaderContext is a special shared library.
[        ] W/com.Jerbb.FoPP(13505): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
[ +136 ms] V/NativeCrypto(13505): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
[  +14 ms] W/com.Jerbb.FoPP(13505): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light
greylist, reflection)
[  +53 ms] D/NetworkSecurityConfig(13505): No Network Security Config specified, using platform default
[   +8 ms] I/ProviderInstaller(13505): Installed default security provider GmsCore_OpenSSL
[ +273 ms] W/com.Jerbb.FoPP(13505): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
[   +2 ms] W/com.Jerbb.FoPP(13505): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist,
linking)
[   +3 ms] W/com.Jerbb.FoPP(13505): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
[   +1 ms] W/com.Jerbb.FoPP(13505): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
[  +66 ms] W/com.Jerbb.FoPP(13505): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light
greylist, reflection)
[  +25 ms] W/com.Jerbb.FoPP(13505): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy;
(light greylist, linking)
[        ] W/com.Jerbb.FoPP(13505): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
[+83831 ms] I/flutter (13505): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +1 ms] I/flutter (13505): The following _CastError was thrown building StreamBuilder<Directory>(dirty, state:
[        ] I/flutter (13505): _StreamBuilderBaseState<Directory, AsyncSnapshot<Directory>>#10bc4):
[        ] I/flutter (13505): type '_Directory' is not a subtype of type 'File' in type cast
[        ] I/flutter (13505): 
[        ] I/flutter (13505): The relevant error-causing widget was:
[        ] I/flutter (13505):   StreamBuilder<Directory> file:///Users/Jerry/Desktop/FoPPSApp/lib/myRecordings.dart:31:13
[        ] I/flutter (13505): 
[        ] I/flutter (13505): When the exception was thrown, this was the stack:
[        ] I/flutter (13505): #0      _MyRecordingsState.getIndivRec.<anonymous closure> (package:FoPPS/myRecordings.dart:49:37)
[        ] I/flutter (13505): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
[        ] I/flutter (13505): #2      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
[        ] I/flutter (13505): #3      new List.from (dart:core-patch/array_patch.dart:38:29)
[        ] I/flutter (13505): #4      new List.of (dart:core-patch/array_patch.dart:68:17)
[        ] I/flutter (13505): #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
[        ] I/flutter (13505): #6      _MyRecordingsState.getIndivRec (package:FoPPS/myRecordings.dart:57:10)
[        ] I/flutter (13505): #7      _MyRecordingsState.build.<anonymous closure> (package:FoPPS/myRecordings.dart:35:41)
[        ] I/flutter (13505): #8      StreamBuilder.build (package:flutter/src/widgets/async.dart:514:81)
[  +14 ms] I/flutter (13505): #9      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:129:48)
[        ] I/flutter (13505): #10     StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
[        ] I/flutter (13505): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
[        ] I/flutter (13505): #12     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
[   +1 ms] I/flutter (13505): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
[   +1 ms] I/flutter (13505): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
[        ] I/flutter (13505): #15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
[        ] I/flutter (13505): #16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
[        ] I/flutter (13505): #17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1115:15)
[        ] I/flutter (13505): #18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1054:9)
[        ] I/flutter (13505): #19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:970:5)
[        ] I/flutter (13505): #23     _invoke (dart:ui/hooks.dart:267:10)
[        ] I/flutter (13505): #24     _drawFrame (dart:ui/hooks.dart:225:3)
[   +7 ms] I/flutter (13505): (elided 3 frames from dart:async)
[        ] I/flutter (13505): 
[   +1 ms] I/flutter (13505): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

flutter analyze
```
Analyzing FoPPSApp...                                                   
No issues found! (ran in 3.6s)
```

flutter doctor -v
```
[✓] Flutter (Channel master, 1.20.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.20.0-1.0.pre at /Users/Jerry/Library/Flutter
    • Framework revision 401690a64f (9 days ago), 2020-06-12 19:45:48 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/Jerry/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
    • macOS               • macOS         • darwin-x64  • Mac OS X 10.15.4 19E287

• No issues found!
```

</details>

I am already aware of the existing (and separate) authentication issue

**Comment by PixelToast** [comment]
Various plugins might use this directory to cache application data, I suggest saving files to a subdirectory so they don't interfere.

**Comment by VladyslavBondarenko** [comment]
@Mirageofmage 
To avoid the typecast exception you can check `(f is File)`.
Closing since it's not an issue with flutter. If you disagree please write in comments and I'll reopen
