### ISSUE TITLE
The property definitions for the core build system are missing

### ISSUE THREAD

**Issue by iqbalmineraltown** [flutter/flutter#60064]
I tried to clean and build via Xcode with the legacy build system and it's done successfully

but when I tried to execute `flutter build ios`, it produces the following output:

```
Running pod install...                                             55.4s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           12.8s

Sending crash report to Google.
Crash report sent (report ID: 465860bb5814430e)
Oops; flutter has exited unexpectedly.
```
---------

# `flutter_01.log`'s Content

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build ios

## exception

ProcessException: ProcessException: Process exited abnormally:
Build settings for action build and target Runner:

2020-06-23 12:48:26.741 xcodebuild[24400:153766] Error:  The property definitions for the core build system are missing.  Please make sure that the file 'Core Build System.~' is present and has valid syntax.
2020-06-23 12:48:26.809 xcodebuild[24400:153766] warning: file type '::wrapper.xcdatamodeld' is based on missing file type 'default::sourcecode'
2020-06-23 12:48:26.810 xcodebuild[24400:153766] warning: file type '::wrapper.xcdatamodel' is based on missing file type 'default::sourcecode'
2020-06-23 12:48:26.810 xcodebuild[24400:153766] warning: file type '::folder.skatlas' is based on missing file type 'default::wrapper'
2020-06-23 12:48:26.819 xcodebuild[24400:153766] warning: file type '::text.xml.dae' is based on missing file type 'default::text.xml'
2020-06-23 12:48:26.824 xcodebuild[24400:153766] warning: file type '::file.mlmodel' is based on missing file type 'default::sourcecode'
2020-06-23 12:48:26.825 xcodebuild[24400:153766] warning: file type '::compiled.air' is based on missing file type 'default::compiled'
2020-06-23 12:48:26.827 xcodebuild[24400:153766] warning: file type '::sourcecode.swift' is based on missing file type 'default::sourcecode'
2020-06-23 12:48:26.829 xcodebuild[24400:153766] warning: file type '::com.apple.instruments.package-definition' is based on missing file type 'default::text.xml'
2020-06-23 12:48:26.829 xcodebuild[24400:153766] warning: file type '::file.xib' is based on missing file type 'default::file'
2020-06-23 12:48:26.861 xcodebuild[24400:153766] warning: file type '::sourcecode.metal' is based on missing file type 'default::sourcecode'
2020-06-23 12:48:26.862 xcodebuild[24400:153766] warning: file type '::wrapper.storyboardc' is based on missing file type 'default::wrapper'
2020-06-23 12:48:26.862 xcodebuild[24400:153766] warning: file type '::file.skybox' is based on missing file type 'default::file'
2020-06-23 12:48:26.863 xcodebuild[24400:153766] warning: file type '::wrapper.xcmappingmodel' is based on missing file type 'default::sourcecode'
2020-06-23 12:48:26.902 xcodebuild[24400:153766] warning: file type '::file.storyboard' is based on missing file type 'default::file'
2020-06-23 12:48:26.912 xcodebuild[24400:153766] warning: file type '::wrapper.scncache' is based on missing file type 'default::wrapper'
2020-06-23 12:48:26.924 xcodebuild[24400:153766] warning: file type '::file.rcproject' is based on missing file type 'default::sourcecode'
2020-06-23 12:48:26.926 xcodebuild[24400:153766] warning: file type '::file.usdz' is based on missing file type 'default::file'
2020-06-23 12:48:26.947 xcodebuild[24400:153766] warning: file type '::wrapper.scnassets' is based on missing file type 'default::wrapper'
2020-06-23 12:48:26.968 xcodebuild[24400:153766] warning: file type '::file.intentdefinition' is based on missing file type 'default::sourcecode'
2020-06-23 12:48:27.417 xcodebuild[24400:153766] warning: file type '::file.playground' is based on missing file type 'default::wrapper'
2020-06-23 12:48:27.417 xcodebuild[24400:153766] warning: file type '::file.scp' is based on missing file type 'default::file'
2020-06-23 12:48:27.417 xcodebuild[24400:153766] warning: file type '::file.sks' is based on missing file type 'default::file'
2020-06-23 12:48:27.417 xcodebuild[24400:153766] warning: file type '::com.apple.instruments.instrdst' is based on missing file type 'default::wrapper'
2020-06-23 12:48:27.417 xcodebuild[24400:153766] warning: file type '::file.xcplaygroundpage' is based on missing file type 'default::wrapper'
2020-06-23 12:48:27.417 xcodebuild[24400:153766] warning: file type '::wrapper.xcclassmodel' is based on missing file type 'default::wrapper'
2020-06-23 12:48:27.417 xcodebuild[24400:153766] warning: file type '::archive.metal-library' is based on missing file type 'default::archive'
2020-06-23 12:48:27.431 xcodebuild[24400:153766] warning: build system 'embedded::com.apple.build-system.core' is based on missing build system 'embedded::com.apple.buildsettings.standard'
2020-06-23 12:48:27.432 xcodebuild[24400:153766] warning: build system 'embedded::com.apple.build-system.native' is based on missing build system 'default::com.apple.build-system.native'
2020-06-23 12:48:27.433 xcodebuild[24400:153766] warning: build system 'embedded-shared::com.apple.build-system.core' is based on missing build system 'embedded-shared::com.apple.buildsettings.standard'
2020-06-23 12:48:27.467 xcodebuild[24400:153766] warning: build system 'embedded-shared::com.apple.build-system.native' is based on missing build system 'default::com.apple.build-system.native'
2020-06-23 12:48:27.468 xcodebuild[24400:153766] warning: build system 'macosx::com.apple.build-system.core' is based on missing build system 'macosx::com.apple.buildsettings.standard'
2020-06-23 12:48:27.473 xcodebuild[24400:153766] warning: build system 'macosx::com.apple.build-system.native' is based on missing build system 'default::com.apple.build-system.native'
2020-06-23 12:48:27.497 xcodebuild[24400:153766] Error:  The property definitions for the native build system are missing.  Make sure that the file 'Native Build System.xcspec' is present and has valid syntax.
2020-06-23 12:48:36.108 xcodebuild[24400:153766] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-16131/DVTFoundation/FileTypes/DVTFileDataType.mm:632
Details:  stringRep should be a non-empty string, but it is nil
Object:   <DVTFileDataType>
Method:   +fileDataTypeFromStringRepresentation:
Thread:   <NSThread: 0x7f93b6709390>{number = 1, name = main}
Hints: 

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   +[DVTFileDataType fileDataTypeFromStringRepresentation:] (in DVTFoundation)
  4   +[DVTFileDataType fileDataTypeWithIdentifier:] (in DVTFoundation)
  5   -[XCBuildFileRefDGSnapshot initWithInformationFromBuildFile:fileReference:groupReference:forTargetSnapshot:withResolver:] (in DevToolsCore)
  6   -[XCBuildPhaseDGSnapshot initWithInformationFromBuildPhase:forTargetSnapshot:withResolver:] (in DevToolsCore)
  7   -[XCSourcesBuildPhaseDGSnapshot initWithInformationFromBuildPhase:forTargetSnapshot:withResolver:] (in DevToolsCore)
  8   -[PBXBuildPhase createDependencyGraphSnapshotForTargetSnapshot:withResolver:] (in DevToolsCore)
  9   -[PBXBuildPhase createDependencyGraphSnapshotsForTargetSnapshot:withResolver:] (in DevToolsCore)
 10   -[XCTargetDGSnapshot initWithInformationFromTarget:withBuildParameters:] (in DevToolsCore)
 11   -[XCNativeTargetDGSnapshot initWithInformationFromTarget:withBuildParameters:] (in DevToolsCore)
 12   -[PBXTarget createDependencyGraphSnapshotWithTargetBuildParameters:] (in DevToolsCore)
 13   -[PBXTarget propagateTargetSnapshotIfNeededWithCompletionBlock:] (in DevToolsCore)
 14   __48-[Xcode3CommandLineBuildTool _showBuildSettings]_block_invoke.3323 (in Xcode3Core)
 15   -[DVTFuture initWithBlock:] (in DVTFoundation)
 16   +[DVTFuture futureWithBlock:] (in DVTFoundation)
 17   -[Xcode3CommandLineBuildTool _showBuildSettings] (in Xcode3Core)
 18   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 19   main (in xcodebuild)
 20   start (in libdyld.dylib)
  Command: /usr/bin/env xcrun xcodebuild -configuration Release -quiet DEVELOPMENT_TEAM=724A38P25U -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/iqbal/Documents/kgprojects/myvalue-mobile/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/12/zj3ddh45479b3jhmmfm4j97r0000gn/T/flutter_build_log_pipe.LIoLZz/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:339:21)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:503:66)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#21     _rootRunUnary (dart:async/zone.dart:1134:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#28     _rootRun (dart:async/zone.dart:1126:13)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.5 19F101, locale en-ID)
    [32m•[39m Flutter version 1.12.13+hotfix.9 at /Users/iqbal/dev/flutter_stable_dev
    [32m•[39m Framework revision f139b11009 (3 months ago), 2020-03-30 13:57:30 -0700
    [32m•[39m Engine revision af51afceb8
    [32m•[39m Dart version 2.7.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at /Users/iqbal/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m ANDROID_HOME = /Users/iqbal/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.5)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.5, Build version 11E608c
    [32m•[39m CocoaPods version 1.9.3

[32m[✓][39m Android Studio (version 3.6)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 44.0.2
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[32m[✓][39m VS Code (version 1.46.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.11.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 6 • D3356BD5-69AA-4D71-BC75-F391C8F67F7B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-1 (simulator)

[32m•[39m No issues found!
```

**Comment by iqbalmineraltown** [comment]
I solved this by reinstalling xcode 11.5 and xcode command line
Seems like I have deleted something on my `~/Library/Caches`
