### ISSUE TITLE
Invalid argument(s): Cannot find executable for /Users/XXXX/Development/flutter/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.

### ISSUE THREAD

**Issue by netrager** [flutter/flutter#60079]
Hi,
I'm currently trying to build the following iOS app https://github.com/open-xchange/ox-coi which is based on flutter. I've followed their instructions to install flutter but i'm getting the following error while building the app in XCode.

`Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for /Users/avogel/Development/flutter/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.".`

I know of the closed issue https://github.com/flutter/flutter/issues/57859, but could not find a solution of the problem.

---
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

`flutter assemble --output=/Users/avogel/Development/git/mvolution/COI/ox-coi/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation= -dDartObfuscation=false -dEnableBitcode= --DartDefines= -dExtraFrontEndOptions= release_ios_bundle_flutter_assets`

## exception

`ArgumentError: Invalid argument(s): Cannot find executable for /Users/avogel/Development/flutter/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.`

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:69:31)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
#12     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#22     _rootRun (dart:async/zone.dart:1184:13)
#23     _CustomZone.run (dart:async/zone.dart:1077:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale de-DE)
    • Flutter version 1.17.4 at /Users/avogel/Development/flutter/flutter
    • Framework revision 1ad9baa8b9 (5 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/avogel/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 Pro • 3E3B0B02-ECE6-4286-AB8B-766394B78D4B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

**Comment by iapicca** [comment]
Hi @netrager 
are you experiencing the issue with the current [dev channel](https://github.com/flutter/flutter/issues/59672#issuecomment-645302114)?
Thank you

**Comment by netrager** [comment]
Switching to the dev channel helped with this problem

**Comment by TahaTesser** [comment]
Hi @netrager 
Looks like this is fixed dev channel 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
