### ISSUE TITLE
FileSystemException: Exists failed

### ISSUE THREAD

**Issue by leonardoayres** [flutter/flutter#60088]
Even running with administrator permissions, i'm getting this error:

## command

flutter --quiet assemble --depfile E:\Projetos\<my project>\build\app\intermediates\flutter\debug/flutter_build.d --output E:\Projetos\<my project>\build\app\intermediates\flutter\debug -dTargetFile=E:\Projetos\<my project>\lib\main.dart -dTargetPlatform=android -dBuildMode=debug debug_android_application

## exception

FileSystemException: FileSystemException: Exists failed, path = 'E:\Projetos\<my project>\.dart_tool\flutter_build\bf60ec93bdc9c98b94a5fa0a3e69d26b' (OS Error: Access is denied.
, errno = 5)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:133:11)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:474:26)
#4      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#9      _rootRun (dart:async/zone.dart:1184:13)
#10     _CustomZone.run (dart:async/zone.dart:1077:19)
#11     _runZoned (dart:async/zone.dart:1619:10)
#12     runZoned (dart:async/zone.dart:1539:10)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#19     _rootRun (dart:async/zone.dart:1184:13)
#20     _CustomZone.run (dart:async/zone.dart:1077:19)
#21     _runZoned (dart:async/zone.dart:1619:10)
#22     runZoned (dart:async/zone.dart:1539:10)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#30     _rootRun (dart:async/zone.dart:1184:13)
#31     _CustomZone.run (dart:async/zone.dart:1077:19)
#32     _runZoned (dart:async/zone.dart:1619:10)
#33     runZonedGuarded (dart:async/zone.dart:1608:12)
#34     runZoned (dart:async/zone.dart:1536:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#36     run.<anonymous closure> (package:flutter_tools/runner.dart)
#37     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#38     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#40     _rootRun (dart:async/zone.dart:1184:13)
#41     _CustomZone.run (dart:async/zone.dart:1077:19)
#42     _runZoned (dart:async/zone.dart:1619:10)
#43     runZoned (dart:async/zone.dart:1539:10)
#44     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#45     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#46     run (package:flutter_tools/runner.dart:48:10)
#47     main (package:flutter_tools/executable.dart:69:9)
#48     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.900], locale en-GB)
    • Flutter version 1.17.3 at C:\flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\---\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\---\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.46.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Mi 9T • a4a473f7 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @leonardoayres  
I see there's an open [issue](https://github.com/flutter/flutter/issues/50880) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
