### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = 'C:\scr\flutter\bin\cache\pkg\sky_engine/lib/io/io_resource_info.dart' (OS Error: The file or directory is corrupted and unreadable., errno = 1392)

### ISSUE THREAD

**Issue by DEVSOG12** [flutter/flutter#60107]
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = 'C:\scr\flutter\bin\cache\pkg\sky_engine/lib/io/io_resource_info.dart' (OS Error: The file or directory is corrupted and unreadable.
, errno = 1392)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:131:16)
#4      ErrorHandlingFile.writeAsBytesSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:106:22)
#5      ErrorHandlingFile._runSync (package:flutter_tools/src/base/error_handling_file_system.dart:163:16)
#6      ErrorHandlingFile.writeAsBytesSync (package:flutter_tools/src/base/error_handling_file_system.dart:105:5)
#7      _WindowsUtils._unpackArchive (package:flutter_tools/src/base/os.dart:375:16)
#8      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:326:5)
#9      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:619:16)
#10     _rootRunUnary (dart:async/zone.dart:1192:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#18     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#19     _rootRunUnary (dart:async/zone.dart:1192:38)
```
```
[✓] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.778], locale en-GB)
    • Flutter version 1.17.4 at C:\scr\flutter
    • Framework revision 1ad9baa8b9 (6 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\SOLARINS\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\SOLARINS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by DEVSOG12** [comment]
Re-installed Flutter

Seemed to be a System Problem

Thanks!
