### ISSUE TITLE
Flutter VideoPlayerController network request from web api error

### ISSUE THREAD

**Issue by cableman127** [flutter/flutter#60155]
I get an error when using VideoPlayerController.network to get a video file from my .NET Core backend web api.

It worked before with a direct link to an AWS S3 object within a bucket.

This is the error:

```bash
E/ExoPlayerImplInternal(26886): Source error.
E/ExoPlayerImplInternal(26886): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://192.168.1.157:4000/Post/get-object/0b6976f2-36d2-4189-9dea-64c9aec5f64b-file_example_MP4_1280_10MG.mp4
E/ExoPlayerImplInternal(26886): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal(26886): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(26886): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(26886): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(26886): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(26886): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(26886): 	at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(26886): Caused by: java.io.IOException: Cleartext HTTP traffic to 192.168.1.157 not permitted
E/ExoPlayerImplInternal(26886): 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
E/ExoPlayerImplInternal(26886): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
E/ExoPlayerImplInternal(26886): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal(26886): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
E/ExoPlayerImplInternal(26886): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:444)
E/ExoPlayerImplInternal(26886): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
E/ExoPlayerImplInternal(26886): 	... 6 more
E/flutter (26886): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://192.168.1.157:4000/Post/get-object/0b6976f2-36d2-4189-9dea-64c9aec5f64b-file_example_MP4_1280_10MG.mp4, null)
```

Stackoverflow [link](https://stackoverflow.com/questions/62506493/flutter-videoplayercontroller-network-request-from-web-api) for more information

Image.network works for my web api endpoint. However, video does not work. I really am not sure why. The video can be seen inline from the browser.

**Comment by iapicca** [comment]
Hi @cableman127 
Can you please provide your `flutter doctor -v`, 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a minimal reproducible code sample.
Thank you

**Comment by cableman127** [comment]
nvm, i saw when i ran --verbose i saw the cleartext HTTP traffic not permitted error and i fixed it. TYVM!
