### ISSUE TITLE
A crash report when run flutter build ios --debug

### ISSUE THREAD

**Issue by MisariLin** [flutter/flutter#60178]
I have a problem when run “ flutter build ios —debug”.I tried “flutter clean” & clean bin/cache,but not work.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build ios --debug

## exception

FileSystemException: FileSystemException: Deletion failed, path = '/var/folders/7k/xqflj8f525z8x7gdlvnf78kwybpxtf/T/flutter_build_log_pipe.BfrrFf' (OS Error: Operation not supported, errno = 45)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:208:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:435:22)
<asynchronous suspension>
#4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:452:39)
<asynchronous suspension>
#5      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:78:43)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:638:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:537:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1465:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:527:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:112:14)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#29     _rootRun (dart:async/zone.dart:1126:13)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _runZoned (dart:async/zone.dart:1518:10)
#32     runZoned (dart:async/zone.dart:1502:12)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _runZoned (dart:async/zone.dart:1518:10)
#38     runZoned (dart:async/zone.dart:1465:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#40     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#41     run (package:flutter_tools/runner.dart:51:10)
#42     main (package:flutter_tools/executable.dart:65:9)
#43     main (file:///Users/linwei/Library/Application%20Support/fvm/versions/1146/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel unknown, v1.14.6, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
    • Flutter version 1.14.6 at /Users/linwei/.fvm/versions/1146
    • Framework revision fabeb2a16f (5 months ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/linwei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • 0DAF171A-3C31-4C33-AA47-3C2C396D602E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • macOS             • macOS                                • darwin-x64
      • Mac OS X 10.14.6 18G95
    • Chrome            • chrome                               • web-javascript
      • Google Chrome 83.0.4103.106
    • Web Server        • web-server                           • web-javascript
      • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @MisariLin 
Could you please run `flutter upgrade --force`. 

Also you may want to try this possible [solution](https://github.com/flutter/flutter/issues/31111#issuecomment-514648272).

If the issue persists, 
please provide your updated `flutter doctor -v`, your `flutter run --verbose` and a minimal reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
@MisariLin 
I hope you've solved the issue. Closing since long time without a response and obsolete flutter version was used.
Could everyone who still has this problem please file a new issue with filling out template
