### ISSUE TITLE
Crashing on Nougat once in a while

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6025]
This happened ~20 seconds before the crash:

```
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: Flutter service provider connection error
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: MojoResult(3): INVALID_ARGUMENT
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: at org.chromium.mojo.system.impl.CoreImpl.adb I  9315  9315 commandline.cpp:339] read_and_dump(): pre adb_read(fd=3)
adb I  9315  9315 commandline.cpp:341] read_and_dump(): post adb_read(fd=3): length=8192
writeMessage(CoreImpl.java:293)
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: at org.chromium.mojo.system.impl.MessagePipeHandleImpl.writeMessage(MessagePipeHandleImpl.java:46)
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: at org.chromium.mojo.bindings.Connector.accept(Connector.java:104)
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: at org.chromium.mojo.bindings.RouterImpl.accept(RouterImpl.java:157)
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: at org.chromium.mojo.bindings.RouterImpl$ResponderThunk.accept(RouterImpl.java:57)
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: at org.chromium.mojom.vsync.VSyncProvider_Internal$VSyncProviderAwaitVSyncResponseParamsProxyToResponder.call(VSyncProvider_Internal.java:301)
09-23 15:39:31.600  3752  3752 W ServiceProviderImpl: at org.chromium.mojom.vsync.VSyncProvider_Internal$VSyncProviderAwaitVSyncResponseParamsProxyToResponder.call(VSyncProvider_Internal.java:275)
```

**Comment by apwilson** [comment]
Actual crash trace:
```
--------- beginning of crash
09-23 15:39:54.674  3752  3770 F libc    : Fatal signal 4 (SIGILL), code 1, fault addr 0xb9716fc4 in tid 3770 (Thread-3)
09-23 15:39:54.679   165   165 W         : debuggerd: handling request: pid=3752 uid=10199 gid=10199 tid=3770
09-23 15:39:54.761  3800  3800 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-23 15:39:54.761  3800  3800 F DEBUG   : Build fingerprint: 'google/ryu/dragon:7.0/NRD90R/3141966:user/release-keys'
09-23 15:39:54.761  3800  3800 F DEBUG   : Revision: '0'
09-23 15:39:54.761  3800  3800 F DEBUG   : ABI: 'arm'
09-23 15:39:54.761  3800  3800 F DEBUG   : pid: 3752, tid: 3770, name: Thread-3  >>> com.google.fuchsia.armadillo <<<
09-23 15:39:54.761  3800  3800 F DEBUG   : signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xb9716fc4
09-23 15:39:54.761  3800  3800 F DEBUG   :     r0 c0dbe0b5  r1 e18d5021  r2 00000043  r3 c0dbe20d
09-23 15:39:54.761  3800  3800 F DEBUG   :     r4 c0dbe0b5  r5 b41dc9e9  r6 c71952c9  r7 c71952a9
09-23 15:39:54.761  3800  3800 F DEBUG   :     r8 e18d5021  r9 c4e93f30  sl e1815100  fp ce8670adb I  9315  9315 commandline.cpp:339] read_and_dump(): pre adb_read(fd=3)
adb I  9315  9315 commandline.cpp:341] read_and_dump(): post adb_read(fd=3): length=8192
9c
09-23 15:39:54.761  3800  3800 F DEBUG   :     ip e18d5021  sp ce867064  lr b9716ec4  pc b9716fc4  cpsr 60060010
09-23 15:39:54.761  3800  3800 F DEBUG   : 
09-23 15:39:54.761  3800  3800 F DEBUG   : backtrace:
09-23 15:39:54.761  3800  3800 F DEBUG   :     #00 pc 00016fc4  <anonymous:b9700000>
09-23 15:39:54.761  3800  3800 F DEBUG   :     #01 pc 00016ec0  <anonymous:b9700000>
09-23 15:39:55.190   184   195 E hwc-drm-compositor-worker: Failed to squash all -114
09-23 15:39:55.443  3752  3770 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x56 in tid 3770 (Thread-3)
09-23 15:39:55.443  3752  3770 I libc    : Another thread contacted debuggerd first; not contacting debuggerd.
09-23 15:39:55.446   165   165 W         : debuggerd: resuming target 3752
09-23 15:39:55.467   507   524 I BootReceiver: Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
09-23 15:39:55.475   507  3801 W ActivityManager:   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
09-23 15:39:55.495   182   182 E lowmemorykiller: Error writing /proc/3752/oom_score_adj; errno=22
09-23 15:39:55.546   507   673 I ActivityManager: Process com.google.fuchsia.armadillo (pid 3752) has died
09-23 15:39:55.546   507  1271 D GraphicsStats: Buffer count: 3
09-23 15:39:55.546   507  2545 I WindowManager: WIN DEATH: Window{53a0e40 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}

```

**Comment by apwilson** [comment]
Again:
```
09-23 17:12:33.341  4755  4780 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 4780 (ui_thread)
09-23 17:12:33.342   165   165 W         : debuggerd: handling request: pid=4755 uid=10200 gid=10200 tid=4780
09-23 17:12:33.412  5002  5002 E         : debuggerd: process stopped due to unexpected signal 27
09-23 17:12:33.413   507  5003 W ActivityManager:   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
09-23 17:12:33.413   165   165 W         : debuggerd: resuming target 4755
09-23 17:12:33.415   507   524 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
09-23 17:12:33.422  5004  5004 E crash_dispatcher: Failed to read. errno = 0
09-23 17:12:33.427   182   182 E lowmemorykiller: Error writing /proc/4755/oom_score_adj; errno=22
09-23 17:12:33.460   507   579 I OpenGLRenderer: Initialized EGL, version 1.4
09-23 17:12:33.460   507   579 D OpenGLRenderer: Swap behavior 2
09-23 17:12:33.470   507   518 D GraphicsStats: Buffer count: 2
09-23 17:12:33.470   507   788 I ActivityManager: Process com.google.fuchsia.armadillo (pid 4755) has died
09-23 17:12:33.470   507   518 I WindowManager: WIN DEATH: Window{2b09295 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
09-23 17:12:33.470   507   518 W WindowManager: Force-removing child win Window{80d94da u0 SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity} from container Window{2b09295 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
09-23 17:12:33.471   507   518 I WindowManager: Destroying surface Surface(name=SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2457 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 
09-23 17:12:33.472   507   518 I WindowManager: Destroying surface Surface(name=com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
09-23 17:12:33.473   507   603 W WindowManager: Failed looking up window
09-23 17:12:33.473   507   603 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@615ffaa does not exist
09-23 17:12:33.473   507   603 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9100)
09-23 17:12:33.473   507   603 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9091)
09-23 17:12:33.473   507   603 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1777)
09-23 17:12:33.473   507   603 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
09-23 17:12:33.473   507   603 I WindowManager: WIN DEATH: null
09-23 17:12:33.490  2695  2695 I Finsky  : [1] com.google.android.finsky.utils.dm.onTrimMemory(25): Memory trim requested to level 60
09-23 17:12:33.521  1178  1178 I MemoryTrimmer: Trimming objects from memory, since app is in the background.
09-23 17:12:33.528  1961  5008 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
09-23 17:12:33.547  1961  5008 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
09-23 17:12:34.048  1132  1236 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

**Comment by eseidelGoogle** [comment]
Ideally we would get that tombstone: /data/tombstones/tombstone_03

We publish symbols for libskyshell.so these days, in the same GCS bucket as the jar, etc is published.

@jason-simmons may be able to help you debug.  We need to get the C++ stacktrace (part of which you've posted), symbolicate it and then debug from there.  Alternatively we could run inside a debugger on the device, but that's likely not necessary.

**Comment by chinmaygarde** [comment]
Is this on a JIT (debug) build or using precompiled code (profile and release)?

**Comment by Hixie** [comment]
Closing as ancient.
