### ISSUE TITLE
INVALID_ARGUMENT on Nougat

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6026]
Happens whenever I run:  flutter run --hot

Seems to not repeat on shift-R though.

```
09-23 15:51:13.828  4069  4069 W ServiceProviderImpl: Flutter service provider connection error
09-23 15:51:13.828  4069  4069 W ServiceProviderImpl: MojoResult(3): INVALID_ARGUMENT
09-23 15:51:13.828  4069  4069 W ServiceProviderImpl:   at org.chromium.mojo.system.impl.CoreImpl.writeMessage(CoreImpl.java:293)
09-23 15:51:13.828  4069  4069 W ServiceProviderImpl:   at org.chromium.mojo.system.impl.MessagePipeHandleImpl.writeMessage(MessagePipeHandleImpl.java:46)
09-23 15:51:13.828  4069  4069 W ServiceProviderImpl:   at org.chromium.mojo.bindings.Connector.accept(Connector.java:104)
09-23 15:51:13.828  4069  4069 W ServiceProviderImpl:   at org.chromium.mojo.bindings.RouterImpl.accept(RouterImpl.java:157)
09-23 15:51:13.828  4069  4069 W ServiceProviderImpl:   at org.chromium.mojo.bindings.RouterImpl$ResponderThunk.accept(RouterImpl.java:57)
09-23 15:51:13.828  4069  4069 W ServiceProviderImpl:   at org.chromium.mojom.vsync.VSyncProvider_Internal$VSyncProviderAwaitVSyncResponseParamsProxyToResponder.call(VSyncProvider_Internal.java:301)
```

**Comment by eseidelGoogle** [comment]
This is from the VSyncProvider_Internal service.  @chinmaygarde  or @abarth are your peeps.

**Comment by chinmaygarde** [comment]
We teardown the platform service provider and set it back up on a hot reload. It may be that we don't do the reset correctly. Though I don't understand why this is Nougat only. Will try to reproduce this.

**Comment by chinmaygarde** [comment]
We don't use mojo any more and haven't seen this issue recently. Closing.
