### ISSUE TITLE
palette_generator package works on some images and fails on some

### ISSUE THREAD

**Issue by Elemenopeee** [flutter/flutter#60289]
I don't know how to reproduce this. What I don't understand is why it works on some images and fails on some images. Either it should fail, or it should work. But this error is consistent. And if I reinstall the application from scratch, the images on which it used 
to work previously, it starts failing on them and working on some others.

Code -

```
  Future<void> _generatePalette(context, String imagePath) async {
    _paletteGenerator = await PaletteGenerator.fromImageProvider(
      FileImage(
        File(imagePath),
      ),
      size: Size(100, 100),
    );
    if (_paletteGenerator != null){
      customLightColor = _paletteGenerator.lightVibrantColor.color ?? Colors.black;
      customDarkColor = _paletteGenerator.dominantColor.color ?? Colors.black;
      setState(() {
        _cardGradient = LinearGradient(
          begin: Alignment.bottomLeft,
          end: Alignment.topRight,
          colors: [
            customLightColor ?? Colors.black,
            customDarkColor ?? Colors.black,
          ],

        );
      });
    }
  }
```

This code works fine on some images but throws this error on some images

```
E/flutter (11644): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'color' was called on null.
E/flutter (11644): Receiver: null
E/flutter (11644): Tried calling: color
E/flutter (11644): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (11644): #1      _CreateThisWidget._generatePalette (package:someApp/widgets/some_widget.dart:52:62)
E/flutter (11644): <asynchronous suspension>
E/flutter (11644): #2      _CreateThisWidget._onBasicAlertPressed.<anonymous closure> (package:someApp/widgets/some_widget.dart:299:23)
E/flutter (11644): <asynchronous suspension>
E/flutter (11644): #3      _CreateThisWidget._onBasicAlertPressed.<anonymous closure> (package:someApp/widgets/some_widget.dart)
E/flutter (11644): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (11644): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (11644): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (11644): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (11644): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (11644): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (11644): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (11644): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (11644): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (11644): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (11644): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (11644): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (11644): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (11644): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (11644): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (11644): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (11644): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (11644): #21     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (11644): #22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (11644): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (11644): #24     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (11644): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (11644): 
D/ViewRootImpl@d41c318[UCropActivity](11644): Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][1440,2560] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
D/Graph   (11644): removeVertex() : insertDummyVertex, because there is no ancestor.
D/ViewRootImpl@d41c318[UCropActivity](11644): mHardwareRenderer.destroy()#4
D/ViewRootImpl@d41c318[UCropActivity](11644): dispatchDetachedFromWindow
D/InputTransport(11644): Input channel destroyed: fd=192
V/FA      (11644): Inactivity, disconnecting from the service
```

**Comment by VladyslavBondarenko** [comment]
Hi @Elemenopeee 
could you provide your `flutter doctor -v` and are you using the last version palette_generator 0.2.3?

**Comment by Elemenopeee** [comment]
flutter doctor - v is

[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
    • Flutter version 1.17.4 at C:\src\flutter\flutter
    • Framework revision 1ad9baa8b9 (8 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

Yes. I am using 0.2.3

**Comment by Elemenopeee** [comment]
**Thanks**
Resolved Android toolchain and ran flutter doctor again. This is the output.
_But_
I also reinstalled the app from scratch and its still throwing the same error.


`[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
    • Flutter version 1.17.4 at C:\src\flutter\flutter
    • Framework revision 1ad9baa8b9 (8 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ofthe\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM G920I • 0816085b4b4e1704 • android-arm64 • Android 7.0 (API 24)

• No issues found!
Process finished with exit code 0`

**Comment by VladyslavBondarenko** [comment]
@Elemenopeee 
using `?.` should solve it, since these properties as `lightVibrantColor` may be null.
```
customLightColor = _paletteGenerator.lightVibrantColor?.color ?? Colors.black;
```
You could see it in [the example](https://pub.dev/packages/palette_generator#-example-tab-)

Closing since this isn't an issue with flutter,
if you disagree please write in the comments and I will reopen it
