### ISSUE TITLE
Some engine checks stay pending even though they succeeded

### ISSUE THREAD

**Issue by rmistry** [flutter/flutter#60312]
For example in https://github.com/flutter/engine/pull/19311
There are 4 checks that show up as pending, and cause the "waiting for tree to go green" bot to not merge the PR.

But if you click through each of them, they actually succeeded:

- https://ci.chromium.org/p/flutter/builders/try/Mac%20Android%20AOT%20Engine/4775?reload=30
- https://ci.chromium.org/p/flutter/builders/try/Mac%20Android%20Debug%20Engine/4703?reload=30
- https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20Engine/8762?reload=30
- https://ci.chromium.org/p/flutter/builders/try/Windows%20Web%20Engine/5947?reload=30

**Comment by rmistry** [comment]
@godofredoc FYI

**Comment by rmistry** [comment]
Seems to be happening very frequently.
Eg:
- https://github.com/flutter/engine/pull/19316
- https://github.com/flutter/engine/pull/19314

**Comment by rmistry** [comment]
Happened in https://github.com/flutter/engine/pull/19742

**Comment by rmistry** [comment]
Again in https://github.com/flutter/engine/pull/19765

**Comment by godofredoc** [comment]
I took a look yesterday and sometimes cirrus tasks are not updating the status either. Checking if this is related to API quotas.

**Comment by godofredoc** [comment]
Confirmed this is a API quota problem, yesterday(07/14/2020) from 1:00 PM to 7:00 PM we were getting API quota problems: 

```

2020-07-14 16:31:07.670 PDT
Available tags: [build_address:luci.flutter.try/Linux Web Engine/6853, builder:Linux Web Engine, buildset:pr/git/19756, buildset:sha/git/707a60a67912718f24b0ec8f101355f049f1800a, github_link:https://github.com/flutter/engine/pull/19756, swarming_hostname:chromium-swarm.appspot.com, swarming_tag:log_location:logdog://logs.chromium.org/flutter/buildbucket/cr-buildbucket.appspot.com/8874756748532080352/+/annotations, swarming_tag:luci_project:flutter, swarming_tag:os:Debian, swarming_tag:recipe_name:web_engine, swarming_tag:recipe_package:flutter/recipe_bundles/flutter.googlesource.com/recipes, swarming_task_id:4d687c2df08aa610, user_agent:flutter-cocoon]
2020-07-14 16:31:07.670 PDT
Setting status: {build: Instance of 'Build', hostname: cr-buildbucket.appspot.com, user_data: {"retries":0}} for Linux Web Engine
2020-07-14 16:32:09.150 PDT
GitHub Error: API rate limit exceeded for user ID 52682268.
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:435:5)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:36:33)
<asynchronous suspension>
#3      PaginationHelper.jsonObjects (package:github/src/common/util/pagination.dart:99:34)
<asynchronous suspension>
#4      PaginationHelper.objects (package:github/src/common/util/pagination.dart:132:12)
#5      RepositoriesService.listStatuses (package:github/src/common/repos_service.dart:1221:10)
#6      GithubStatusService.setPendingStatus (package:cocoon_service/src/service/github_status_service.dart:69:38)
<asynchronous suspension>
#7      LuciStatusHandler.post (package:cocoon_service/src/request_handlers/luci_status.dart:130:56)
<asynchronous suspension>
#8      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
#9      _rootRun (dart:async/zone.dart:1184:13)
#10     _CustomZone.run (dart:async/zone.dart:1077:19)
#11     _runZoned (dart:async/zone.dart:1619:10)
#12     runZoned (dart:async/zone.dart:1539:10)
#13     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#14     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:124:23)
#15     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#16     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#17     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _runZoned (dart:async/zone.dart:1619:10)
#21     runZonedGuarded (dart:async/zone.dart:1608:12)
#22     runZoned (dart:async/zone.dart:1536:12)
#23     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#24     fork (package:gcloud/service_scope.dart:104:30)
#25     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#26     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#27     _rootRunUnary (dart:async/zone.dart:1192:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#33     _StreamController._add (dart:async/stream_controller.dart:655:7)
#34     _StreamController.add (dart:async/stream_controller.dart:597:5)
#35     _HttpServer._handleRequest (dart:_http/http_impl.dart:2837:19)
#36     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2596:19)
#37     _rootRunUnary (dart:async/zone.dart:1192:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#43     _StreamController._add (dart:async/stream_controller.dart:655:7)
#44     _StreamController.add (dart:async/stream_controller.dart:597:5)
#45     _HttpParser._headersEnd (dart:_http/http_parser.dart:413:17)
#46     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#47     _HttpParser._parse (dart:_http/http_parser.dart:328:7)
#48     _HttpParser._onData (dart:_http/http_parser.dart:850:5)
#49     _rootRunUnary (dart:async/zone.dart:1192:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#55     _StreamController._add (dart:async/stream_controller.dart:655:7)
#56     _StreamController.add (dart:async/stream_controller.dart:597:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#58     _rootRunUnary (dart:async/zone.dart:1196:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#63     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#64     _StreamController._add (dart:async/stream_controller.dart:655:7)
#65     _StreamController.add (dart:async/stream_controller.dart:597:5)
#66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#70     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by godofredoc** [comment]
I'm removing the additional pub/sub subscription created for staging as we are processing the status updates twice:

![image](https://user-images.githubusercontent.com/54371434/87566662-32dde700-c678-11ea-95ab-c8765c047361.png)
