### ISSUE TITLE
Hot Reload - Unimplemented handling of static target arity change

### ISSUE THREAD

**Issue by vagrantrobbie** [flutter/flutter#60323]
## Steps to Reproduce

I am building a new app with the latest version of Flutter 1.17.4 but when I try to create a Routes map or use a generator I always receive this error on hot reload "Unimplemented handling of static target arity change".  

This is happening on both platforms Android Samsung Galaxy S9 and iPhoneX

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _CompileTimeError was thrown building Builder(dirty):
Unimplemented handling of static target arity change

The relevant error-causing widget was: 
  MyTester _${path to project}_/lib/main.dart:4:23
When the exception was thrown, this was the stack: 
#0      CupertinoPageRoute.buildPage (package:flutter/src/cupertino/route.dart:252:33)
#1      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:804:43)
#2      Builder.build (package:flutter/src/widgets/basic.dart:6998:48)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
```

I have tried using MaterialApp as well as CupertinoApp but both these have the same result after using hot reload.  

### My Flutter doctor output  

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-NZ)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.1)
```

## A minimal example

```
import 'package:flutter/cupertino.dart';
//import 'package:flutter/material.dart';

void main() => runApp(MyTester());

class SomethingView extends StatefulWidget {
  @override
  _SomethingViewState createState() => _SomethingViewState();
}

class _SomethingViewState extends State<SomethingView> {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Hello Root 2"),
      ),
      child: SafeArea(
        child: Container(
          child: Text("The Root"),
        ),
      ),
    );
  }
}


class MyTester extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("Hello MyTester");
    return CupertinoApp(
        title: 'Flutter Demo',
        routes: {
          "/": (BuildContext context) => SomethingView(),
          "signIn": (BuildContext context) => CupertinoPageScaffold(
            navigationBar: CupertinoNavigationBar(
              middle: Text("Hello Sign In"),
            ),
            child: SafeArea(
              child: Container(
                child: Text("The Sign In"),
              ),
            ),
          ),
        }
    );
  }
}
```

**Comment by vagrantrobbie** [comment]
Please note that this is always happening, even after creating a new project again to check if something was corrupted when first creating.

I have also used `flutter clean`

**Comment by VladyslavBondarenko** [comment]
@vagrantrobbie 
I tried with stable v1.17.4 and with current dev  1.20.0-1.0.pre running on Redmi Note 7 Android 9 (API 28), but couldn't reproduce

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.220, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.220 at /Users/nevercode/dev/flutter
    • Framework revision 1e6e7150f3 (7 hours ago), 2020-06-26 12:01:59 +0800
    • Engine revision 22b099bc63
    • Dart version 2.9.0 (build 2.9.0-19.0.dev ea87c9b01a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Redmi Note 7  • 6345c469   • android-arm64  • Android 9 (API 28)
    • macOS desktop • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
nevercode@Nevercodes-MacBook-Pro ~ % flutterd doctor -v
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre at /Users/nevercode/dev/flutter_dev
    • Framework revision f73f498da1 (8 days ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • Redmi Note 7       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.5
    • macOS              • macOS                                    • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server         • web-server                               • web-javascript • Flutter Tools
    • Chrome             • chrome                                   • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

can you reproduce it with other flutter channels?

**Comment by vagrantrobbie** [comment]
Hi there, 

I did try using the dev channel (Channel dev, 1.20.0-1.0.pre) and it seems to have fixed itself. I may try to switch back to stable in the near future but for now due to no one else receiving this error, I will close this ticket
