### ISSUE TITLE
'dart:ui/geometry.dart': Failed assertion: line 19: '<optimized out>': is not true.

### ISSUE THREAD

**Issue by praharshbhatt** [flutter/flutter#60338]
Cannot post the code here, but a related issue: https://stackoverflow.com/questions/61640415/i-got-stuck-with-a-problem-in-flutter-the-following-assertion-was-thrown-buildi/62588365#62588365

**Expected results:** Not a red error screen
**Actual results:** Red error screen with following logs:

<details>
  <summary>Logs</summary>

```
I/flutter (25205): Home Page
I/flutter (25205): Flutter error caught by Crashlytics plugin:
I/flutter (25205): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (25205): The following assertion was thrown building HomePage(dirty, dependencies: [MediaQuery], state:
I/flutter (25205): HomePageState#88b10):
I/flutter (25205): 'dart:ui/geometry.dart': Failed assertion: line 19: '<optimized out>': is not true.
I/flutter (25205):
I/flutter (25205): The relevant error-causing widget was:
I/flutter (25205):   HomePage file:///D:/Kinderpass/kp-flutter-app/lib/main.dart:424:26
I/flutter (25205):
I/flutter (25205): When the exception was thrown, this was the stack:
I/flutter (25205): #2      new OffsetBase (dart:ui/geometry.dart:19:16)
I/flutter (25205): #3      new Size (dart:ui/geometry.dart:350:45)
I/flutter (25205): #4      HomePageState.build (package:kinderpass_app/home/home_page.dart:388:26)
I/flutter (25205): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (25205): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (25205): #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (25205): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (25205): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (25205): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (25205): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (25205): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
I/flutter (25205): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (25205): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
I/flutter (25205): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (25205): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #23     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
I/flutter (25205): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (25205): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (25205): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (25205): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
I/flutter (25205): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (25205): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (25205): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (25205): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
I/flutter (25205): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #45     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
I/flutter (25205): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #48     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (25205): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
I/flutter (25205): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (25205): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:4862:5)
I/flutter (25205): #57     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
I/flutter (25205): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (25205): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #62     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (25205): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #64     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
I/flutter (25205): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #68     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
I/flutter (25205): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (25205): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #74     ProxyElement.update (package:flutter/src/widgets/framework.dart:4862:5)
I/flutter (25205): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (25205): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (25205): #77     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (25205): #78     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (25205): #79     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (25205): #80     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter (25205): #81     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (25205): #82     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (25205): #83     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (25205): #84     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:861:7)
I/flutter (25205): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Android SDK built for x86...             3,742ms (!)

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:63540/HlLkUQMaEyo=/
```

```
D:\Kinderpass\kp-flutter-app>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18363.900], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

```
</details>

**Comment by iapicca** [comment]
Hi @praharshbhatt 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`, your `pubspec.yaml` and a minimal reproducible code sample without 3rd party plugins
Thank you

**Comment by praharshbhatt** [comment]
Found the Issue.

The error was in the following line:
preferredSize: Size(null, 100),

Changed to:
preferredSize: Size(double.infinity, 100),


Now works properply.
