### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, path = 'F:\rexx\correctionflutter\androidtooflutter\demoflutter\.android' (OS Error: The process cannot access the file because it is being used by another process., errno = 32)

### ISSUE THREAD

**Issue by jayadevi-rexx** [flutter/flutter#60414]
## Command
```
flutter --no-color packages get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Deletion failed, path = 'F:\rexx\correctionflutter\androidtooflutter\demoflutter\.android' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:208:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:460:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      _deleteIfExistsSync (package:flutter_tools/src/project.dart:822:15)
#4      AndroidProject._regenerateLibrary (package:flutter_tools/src/project.dart:721:5)
#5      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:682:13)
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:212:21)
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:23)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
```
```
[✓] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.17134.885], locale en-US)
    • Flutter version 1.17.4 at D:\flutter sdk\flutter
    • Framework revision 1ad9baa8b9 (9 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Jaya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\Jaya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.demoflutter
**iOS bundle identifier**: com.example.demoflutter
**Creation channel**: stable
**Creation framework version**: 1ad9baa8b99a2897c20f9e6e54d3b9b359ade314

**Comment by christopherfujino** [comment]
Thanks for filing this! However, I am closing it as a duplicate https://github.com/flutter/flutter/issues/50880. Please follow there for status/updates.
