### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by tanvibattu** [flutter/flutter#60441]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

i get this error while running 
flutter run
Launching lib/main.dart on Redmi 5 in debug mode...
/usr/bin/env: ‘bash\r’: No such file or directory                       
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         0.2s

<details>
  <summary>Logs</summary>

```
flutter run --verbose
[  +32 ms] executing: [/home/tanvi/Documents/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5f21edf8b66e31a39133177319414395cc5b5f48
[   +1 ms] executing: [/home/tanvi/Documents/development/flutter/] git tag --contains HEAD
[ +328 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.17.2
[  +28 ms] executing: [/home/tanvi/Documents/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/tanvi/Documents/development/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +124 ms] executing: [/home/tanvi/Documents/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +45 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] executing: /home/tanvi/Android/Sdk/platform-tools/adb devices -l
[  +95 ms] List of devices attached
           b44eda3e7d25           device usb:1-2 product:rosy model:Redmi_5 device:rosy transport_id:2
[  +13 ms] /home/tanvi/Android/Sdk/platform-tools/adb -s b44eda3e7d25 shell getprop
[  +64 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +145 ms] Found plugin cloud_firestore at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.7/
[  +15 ms] Found plugin cloud_firestore_web at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[  +23 ms] Found plugin firebase_auth at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.11.1+12/
[  +10 ms] Found plugin firebase_core at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +7 ms] Found plugin firebase_core_web at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +29 ms] Found plugin flutter_webview_plugin at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.11/
[  +45 ms] Found plugin share at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.4+3/
[ +303 ms] Found plugin cloud_firestore at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.7/
[   +5 ms] Found plugin cloud_firestore_web at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[  +12 ms] Found plugin firebase_auth at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.11.1+12/
[   +3 ms] Found plugin firebase_core at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +7 ms] Found plugin firebase_core_web at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +18 ms] Found plugin flutter_webview_plugin at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.11/
[  +21 ms] Found plugin share at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.4+3/
[ +101 ms] Generating /home/tanvi/Desktop/News_app_2.0/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +45 ms] ro.hardware = qcom
[  +80 ms] Launching lib/main.dart on Redmi 5 in debug mode...
[  +11 ms] /home/tanvi/Documents/development/flutter/bin/cache/dart-sdk/bin/dart
/home/tanvi/Documents/development/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/tanvi/Documents/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.DYZSJN/app.dill --packages /home/tanvi/Desktop/News_app_2.0/.packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill
[  +35 ms] executing: /home/tanvi/Android/Sdk/platform-tools/adb -s b44eda3e7d25 shell -x logcat -v time -t 1
[  +85 ms] Exit code 0 from: /home/tanvi/Android/Sdk/platform-tools/adb -s b44eda3e7d25 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           06-28 01:38:09.686 E/NetlinkEvent(  862): NetlinkEvent::FindParam(): Parameter 'UID' not found
[  +25 ms] <- compile package:pocketnews/main.dart
[  +36 ms] executing: /home/tanvi/Android/Sdk/platform-tools/adb version
[  +24 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/tanvi/Android/Sdk/platform-tools/adb
[  +11 ms] executing: /home/tanvi/Android/Sdk/platform-tools/adb start-server
[  +64 ms] Building APK
[  +48 ms] Running Gradle task 'assembleDebug'...
[  +10 ms] gradle.properties already sets `android.enableR8`
[   +9 ms] Using gradle from /home/tanvi/Desktop/News_app_2.0/android/gradlew.
[   +2 ms] /home/tanvi/Desktop/News_app_2.0/android/gradlew mode: 33277 rwxrwxr-x.
[  +16 ms] executing: /home/tanvi/Documents/development/android-studio/jre/bin/java -version
[ +118 ms] Exit code 0 from: /home/tanvi/Documents/development/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +8 ms] executing: [/home/tanvi/Desktop/News_app_2.0/android/] /home/tanvi/Desktop/News_app_2.0/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=/home/tanvi/Desktop/News_app_2.0/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[  +84 ms] /usr/bin/env: ‘bash\r’: No such file or directory
[  +21 ms] Running Gradle task 'assembleDebug'... (completed in 0.3s)
[+9921 ms] Exception: Gradle task assembleDebug failed with exit code 127
[   +3 ms] "flutter run" took 11,702ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
```

```
flutter run --verbose
[  +32 ms] executing: [/home/tanvi/Documents/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 5f21edf8b66e31a39133177319414395cc5b5f48
[   +1 ms] executing: [/home/tanvi/Documents/development/flutter/] git tag --contains HEAD
[ +328 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] 1.17.2
[  +28 ms] executing: [/home/tanvi/Documents/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/tanvi/Documents/development/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +124 ms] executing: [/home/tanvi/Documents/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +45 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] executing: /home/tanvi/Android/Sdk/platform-tools/adb devices -l
[  +95 ms] List of devices attached
           b44eda3e7d25           device usb:1-2 product:rosy model:Redmi_5 device:rosy transport_id:2
[  +13 ms] /home/tanvi/Android/Sdk/platform-tools/adb -s b44eda3e7d25 shell getprop
[  +64 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +145 ms] Found plugin cloud_firestore at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.7/
[  +15 ms] Found plugin cloud_firestore_web at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[  +23 ms] Found plugin firebase_auth at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.11.1+12/
[  +10 ms] Found plugin firebase_core at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +7 ms] Found plugin firebase_core_web at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +29 ms] Found plugin flutter_webview_plugin at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.11/
[  +45 ms] Found plugin share at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.4+3/
[ +303 ms] Found plugin cloud_firestore at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.7/
[   +5 ms] Found plugin cloud_firestore_web at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.1+2/
[  +12 ms] Found plugin firebase_auth at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.11.1+12/
[   +3 ms] Found plugin firebase_core at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +7 ms] Found plugin firebase_core_web at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +18 ms] Found plugin flutter_webview_plugin at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.11/
[  +21 ms] Found plugin share at /home/tanvi/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.4+3/
[ +101 ms] Generating /home/tanvi/Desktop/News_app_2.0/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +45 ms] ro.hardware = qcom
[  +80 ms] Launching lib/main.dart on Redmi 5 in debug mode...
[  +11 ms] /home/tanvi/Documents/development/flutter/bin/cache/dart-sdk/bin/dart
/home/tanvi/Documents/development/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/tanvi/Documents/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.DYZSJN/app.dill --packages /home/tanvi/Desktop/News_app_2.0/.packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill
[  +35 ms] executing: /home/tanvi/Android/Sdk/platform-tools/adb -s b44eda3e7d25 shell -x logcat -v time -t 1
[  +85 ms] Exit code 0 from: /home/tanvi/Android/Sdk/platform-tools/adb -s b44eda3e7d25 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           06-28 01:38:09.686 E/NetlinkEvent(  862): NetlinkEvent::FindParam(): Parameter 'UID' not found
[  +25 ms] <- compile package:pocketnews/main.dart
[  +36 ms] executing: /home/tanvi/Android/Sdk/platform-tools/adb version
[  +24 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/tanvi/Android/Sdk/platform-tools/adb
[  +11 ms] executing: /home/tanvi/Android/Sdk/platform-tools/adb start-server
[  +64 ms] Building APK
[  +48 ms] Running Gradle task 'assembleDebug'...
[  +10 ms] gradle.properties already sets `android.enableR8`
[   +9 ms] Using gradle from /home/tanvi/Desktop/News_app_2.0/android/gradlew.
[   +2 ms] /home/tanvi/Desktop/News_app_2.0/android/gradlew mode: 33277 rwxrwxr-x.
[  +16 ms] executing: /home/tanvi/Documents/development/android-studio/jre/bin/java -version
[ +118 ms] Exit code 0 from: /home/tanvi/Documents/development/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +8 ms] executing: [/home/tanvi/Desktop/News_app_2.0/android/] /home/tanvi/Desktop/News_app_2.0/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=/home/tanvi/Desktop/News_app_2.0/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[  +84 ms] /usr/bin/env: ‘bash\r’: No such file or directory
[  +21 ms] Running Gradle task 'assembleDebug'... (completed in 0.3s)
[+9921 ms] Exception: Gradle task assembleDebug failed with exit code 127
[   +3 ms] "flutter run" took 11,702ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @tanvibattu 
is https://github.com/flutter/flutter/issues/27076#issuecomment-487300955 your case?

**Comment by tanvibattu** [comment]
> Hi @tanvibattu
> is [#27076 (comment)](https://github.com/flutter/flutter/issues/27076#issuecomment-487300955) your case?

Yes similar to this issue...but could not find solution for it yet.
I get this error in one of my projects while running while other projects run fine

**Comment by VladyslavBondarenko** [comment]
@tanvibattu 
could you provide your `flutter doctor -v`?
can you run a new project fine?
doesn't any of workarounds from mentioned issue help?

**Comment by tanvibattu** [comment]
> @tanvibattu
> could you provide your `flutter doctor -v`?
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.17.2 at /home/tanvi/Documents/development/flutter
    • Framework revision 5f21edf8b6 (5 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/tanvi/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/tanvi/Documents/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/tanvi/Documents/development/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Redmi 5 • b44eda3e7d25 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
> can you run a new project fine?
> doesn't any of workarounds from mentioned issue help?
no workarounds from mentioned issue didn't help

**Comment by tanvibattu** [comment]
I deleted gradlew file present in android folder and copied gradlew file from another new flutter project and i don't know how but this helped me solve my problem.

**Comment by aishvergil** [comment]
Well you just have to remove gradlew file inside android folder and run flutter create --org <your-application-domain> .

**Comment by thegausiantheory** [comment]
I also have the same problem

mgr@ICB0495:~$ flutter doctor
/usr/bin/env: ‘bash\r’: No such file or directory
mgr@ICB0495:~$ vim /usr/bin/env
mgr@ICB0495:~$ cd /usr/bin/env
bash: cd: /usr/bin/env: Not a directory
mgr@ICB0495:~$ flutter doctor -v
/usr/bin/env: ‘bash\r’: No such file or directory
mgr@ICB0495:~$ flutter run --verbose
/usr/bin/env: ‘bash\r’: No such file or directory
mgr@ICB0495:~$
