### ISSUE TITLE
WebSocketChannelException in Android Studio while launching all tests

### ISSUE THREAD

**Issue by alekskuzmin** [flutter/flutter#60450]
Steps to Reproduce

1. Try to run all tests in `test` folder by clicking with the right mouse button 

## Logs

```
Testing started at 9:26 AM ...
<...>\FlutterSDK\bin\cache\dart-sdk\bin\pub.bat run test -r json <...>/my_project

Unhandled exception:
WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:56875/AiGdShZ_Shs=/ws
#0      new IOWebSocketChannel._withoutSocket.<anonymous closure> (package:web_socket_channel/io.dart:89:24)
#1      _invokeErrorHandler (dart:async/async_error.dart:16:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:282:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1396:10)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#8      _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:788:19)
#9      _StreamController._addError (dart:async/stream_controller.dart:663:7)
#10     _RootZone.runBinaryGuarded (dart:async/zone.dart:1396:10)
#11     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#12     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#13     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#14     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:788:19)
#15     _StreamController._addError (dart:async/stream_controller.dart:663:7)
#16     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:178:18)
#17     _RootZone.runBinary (dart:async/zone.dart:1455:54)
#18     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#20     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#21     Future._completeError (dart:async/future_impl.dart:537:5)
#22     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

Process finished with exit code 255
```

`flutter doctor -v` output:
```

[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.19.0-4.2.pre at <...>
    • Framework revision 9b9b543d92 (5 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at <...>
    • Platform android-30, build-tools 29.0.2
    • Java binary at: <...>
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at <...>

[√] Android Studio (version 4.0)
    • Android Studio at <...>
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at <...>
    • Flutter extension version 3.12.0

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!


```

**Comment by TahaTesser** [comment]
Hi @alekskuzmin 
Not able to reproduce this issue using default test folder with counter example 

Please check your internet connection and make sure you're not protected/private network 

If the problem persist, "Hi @... 
Can you please provide your `flutter --verbose test  test` for test and a complete reproducible minimal code sample
Thank you

**Comment by alekskuzmin** [comment]
If I create an example "counter" project there is another issue - when I click the right button on the default test folder there is no option for test launch.

![Screensdfghdfghhot_5](https://user-images.githubusercontent.com/6849426/86097748-b380dd00-bae7-11ea-9ddb-17e8d6d4eea4.png)

When I click on widget_test a dart test is launched instead of a flutter test.

![dffghdfghdf](https://user-images.githubusercontent.com/6849426/86097875-e3c87b80-bae7-11ea-90e3-de971a731928.png)

**Comment by TahaTesser** [comment]
Hi @alekskuzmin 
You can create test configuration in Android Studio toolbar as you might have done before before or try to reproduce the issue using `flutter --verbose test test` and provide the logs
Thank you

**Comment by alekskuzmin** [comment]
This was a bug in Intellij Flutter plugin.
