### ISSUE TITLE
[web] Scrolling a list of cards with BeveledRectangleBorder crashes

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#60461]
While using a `RoundedRectangleBorder` works as expected, when scrolling upwards on a grid of cards with `BeveledRectangleBorder` I get the following exception:

```
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...
Debug service listening on ws://127.0.0.1:50447/W8IC4xRFsHg=
Debug service listening on ws://127.0.0.1:50447/W8IC4xRFsHg=

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/clip.dart:298:12
_clipElement == null
is not true

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
lib/_engine/engine/surface/clip.dart 298:28                                   [_applyShape]
lib/_engine/engine/surface/clip.dart 221:5                                    apply
lib/_engine/engine/surface/surface.dart 364:5                                 build
lib/_engine/engine/surface/surface.dart 662:11                                build
lib/_engine/engine/surface/surface.dart 681:14                                build
lib/_engine/engine/surface/surface.dart 966:19                                [_updateManyToMany]
lib/_engine/engine/surface/surface.dart 718:7                                 update
lib/_engine/engine/surface/clip.dart 101:11                                   update
lib/_engine/engine/surface/surface.dart 878:15                                [_updateManyToOne]
lib/_engine/engine/surface/surface.dart 714:7                                 update
lib/_engine/engine/surface/offset.dart 46:11                                  update
lib/_engine/engine/surface/surface.dart 853:15                                [_updateManyToOne]
lib/_engine/engine/surface/surface.dart 714:7                                 update
lib/_engine/engine/surface/offset.dart 46:11                                  update
lib/_engine/engine/surface/surface.dart 950:17                                [_updateManyToMany]
lib/_engine/engine/surface/surface.dart 718:7                                 update
lib/_engine/engine/surface/offset.dart 46:11                                  update
lib/_engine/engine/surface/surface.dart 950:17                                [_updateManyToMany]
lib/_engine/engine/surface/surface.dart 718:7                                 update
lib/_engine/engine/surface/transform.dart 43:11                               update
lib/_engine/engine/surface/surface.dart 853:15                                [_updateManyToOne]
lib/_engine/engine/surface/surface.dart 714:7                                 update
lib/_engine/engine/surface/scene_builder.dart 545:25                          <fn>
lib/_engine/engine/profiler.dart 36:18                                        timeAction
lib/_engine/engine/surface/scene_builder.dart 541:12                          build
packages/flutter/src/rendering/layer.dart 810:35                              buildScene
packages/flutter/src/rendering/view.dart 232:36                               compositeFrame
packages/flutter/src/rendering/binding.dart 408:18                            drawFrame
packages/flutter/src/widgets/binding.dart 867:13                              drawFrame
packages/flutter/src/rendering/binding.dart 286:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1115:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1054:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 970:5                             [_handleDrawFrame]
lib/_engine/engine/window.dart 745:13                                         _invoke
lib/_engine/engine/window.dart 358:5                                          invokeOnDrawFrame
lib/_engine/engine.dart 214:18                                                <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/clip.dart:298:12
_clipElement == null
is not true

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
lib/_engine/engine/surface/clip.dart 298:28                                   [_applyShape]
lib/_engine/engine/surface/clip.dart 221:5                                    apply
lib/_engine/engine/surface/surface.dart 364:5                                 build
...
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
PersistedPhysicalShape: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.created
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
PersistedPhysicalShape: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.created
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
PersistedPhysicalShape: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.created
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ImageGrid(),
    );
  }
}

class ImageGrid extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: (MediaQuery.of(context).size.width / 180).floor(),
        childAspectRatio: 2.4,
      ),
      itemCount: 1000,
      itemBuilder: (BuildContext context, int index) {
        return ImageCard('https://picsum.photos/seed/$index/300/200');
      },
    );
  }
}

class ImageCard extends StatelessWidget {
  const ImageCard(this.url);

  final String url;

  @override
  Widget build(BuildContext context) {
    return Card(
      shape: const BeveledRectangleBorder(
        borderRadius: BorderRadius.only(
          topRight: Radius.circular(10.0),
        ),
      ),
      child: Image.network(url, fit: BoxFit.cover),
    );
  }
}
```

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.78, on Mac OS X 10.15.5 19F101, locale en-CH)
    • Flutter version 1.20.0-3.0.pre.78 at /Users/ben/flutter
    • Framework revision 2962912d68 (25 hours ago), 2020-06-27 00:59:50 -0700
    • Engine revision fc0e27210c
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 63cf56d925)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ben/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • macOS desktop • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by iapicca** [comment]
Hi @cbenhagen 
I can confirm this behaviour in the latest master

<details><summary>logs</summary>

```bash
[ +286 ms] Launching lib/main.dart on Chrome in debug mode...
[  +79 ms] Updating assets
[ +153 ms] Syncing files to device Chrome...
[  +61 ms] Generating /Users/nevercode/Desktop/projects/master/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +48 ms] <- reset
[  +14 ms] /Users/nevercode/development/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/nevercode/development/flutter_master/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true
--output-dill /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.y1mUO1/flutter_tool.unKtpp/app.dill --libraries-spec
file:///Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.y1mUO1/flutter_tools.7JnUiP --filesystem-scheme org-dartlang-app
--initialize-from-dill build/cache.dill.track.dill --platform file:///Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +36 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+12234 ms] Syncing files to device Chrome... (completed in 12,384ms, longer than expected)
[   +1 ms] Synced 23.0MB.
[        ] <- accept
[        ] Caching compiled dill
[ +628 ms] [CHROME]:
[   +3 ms] [CHROME]:DevTools listening on ws://127.0.0.1:64872/devtools/browser/9d722858-ba0c-4c9d-8a72-4311ca5f996f
[+5044 ms] Debug service listening on ws://127.0.0.1:64894/zFbMa37vUXs=

[ +304 ms] Debug service listening on ws://127.0.0.1:64894/zFbMa37vUXs=
[   +3 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+16680 ms] ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════

[   +5 ms] The following assertion was thrown during a scheduler callback:

[   +1 ms] Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/clip.dart:298:12

[   +4 ms] _clipElement == null

[   +1 ms] is not true

[   +3 ms] When the exception was thrown, this was the stack:

[   +2 ms] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_

[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed

[        ] lib/_engine/engine/surface/clip.dart 298:28                                   [_applyShape]

[        ] lib/_engine/engine/surface/clip.dart 333:7                                    update

[        ] lib/_engine/engine/surface/surface.dart 878:15                                [_updateManyToOne]

[        ] lib/_engine/engine/surface/surface.dart 714:7                                 update

[        ] lib/_engine/engine/surface/offset.dart 46:11                                  update

[        ] lib/_engine/engine/surface/surface.dart 960:19                                [_updateManyToMany]

[   +2 ms] lib/_engine/engine/surface/surface.dart 718:7                                 update

[        ] lib/_engine/engine/surface/clip.dart 101:11                                   update

[        ] lib/_engine/engine/surface/surface.dart 878:15                                [_updateManyToOne]

[        ] lib/_engine/engine/surface/surface.dart 714:7                                 update

[        ] lib/_engine/engine/surface/offset.dart 46:11                                  update

[        ] lib/_engine/engine/surface/surface.dart 853:15                                [_updateManyToOne]

[        ] lib/_engine/engine/surface/surface.dart 714:7                                 update

[   +7 ms] lib/_engine/engine/surface/offset.dart 46:11                                  update

[        ] lib/_engine/engine/surface/surface.dart 950:17                                [_updateManyToMany]

[   +1 ms] lib/_engine/engine/surface/surface.dart 718:7                                 update

[   +1 ms] lib/_engine/engine/surface/offset.dart 46:11                                  update

[        ] lib/_engine/engine/surface/surface.dart 950:17                                [_updateManyToMany]

[        ] lib/_engine/engine/surface/surface.dart 718:7                                 update

[        ] lib/_engine/engine/surface/transform.dart 43:11                               update

[        ] lib/_engine/engine/surface/surface.dart 853:15                                [_updateManyToOne]

[        ] lib/_engine/engine/surface/surface.dart 714:7                                 update

[        ] lib/_engine/engine/surface/scene_builder.dart 545:25                          <fn>

[  +15 ms] lib/_engine/engine/profiler.dart 36:18                                        timeAction

[        ] lib/_engine/engine/surface/scene_builder.dart 541:12                          build

[        ] packages/flutter/src/rendering/layer.dart 810:35                              buildScene

[        ] packages/flutter/src/rendering/view.dart 232:36                               compositeFrame

[  +19 ms] packages/flutter/src/rendering/binding.dart 408:18                            drawFrame

[        ] packages/flutter/src/widgets/binding.dart 867:13                              drawFrame

[        ] packages/flutter/src/rendering/binding.dart 286:5                             [_handlePersistentFrameCallback]

[        ] packages/flutter/src/scheduler/binding.dart 1115:15                           [_invokeFrameCallback]

[        ] packages/flutter/src/scheduler/binding.dart 1054:9                            handleDrawFrame

[   +6 ms] packages/flutter/src/scheduler/binding.dart 970:5                             [_handleDrawFrame]

[        ] lib/_engine/engine/window.dart 745:13                                         _invoke

[        ] lib/_engine/engine/window.dart 358:5                                          invokeOnDrawFrame

[        ] lib/_engine/engine.dart 214:18                                                <fn>

[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════

[ +152 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

[  +26 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

[  +23 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

[ +540 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

[  +13 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

[  +18 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

[  +54 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

[ +100 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.

[  +57 ms] Another exception was thrown: PersistedPhysicalShape: is in an unexpected state.
```




</details>

<details><summary>logs</summary>

```console
[✓] Flutter (Channel master, 1.20.0-3.0.pre.78, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.78 at /Users/nevercode/development/flutter_master
    • Framework revision 2962912d68 (2 days ago), 2020-06-27 00:59:50 -0700
    • Engine revision fc0e27210c
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 63cf56d925)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • D6967F45-CB0F-4D4E-AFD5-278816A21CAE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS desktop     • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server        • web-server                           • web-javascript • Flutter Tools
    • Chrome            • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```


</details>

**Comment by sgehrman** [comment]
I'm getting something similar.  I am using the 'bubble' pub, and if I put them in a list view and scroll up, I get this:

stops at layer.dart line 776

Exception has occurred.
"Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/clip.dart:295:12
_clipElement == null
is not true
    at Object.throw_ [as throw] (http://localhost:45989/dart_sdk.js:4322:11)
    at Object.assertFailed (http://localhost:45989/dart_sdk.js:4271:15)
    at _engine.PersistedPhysicalShape.new.[_applyShape] (http://localhost:45989/dart_sdk.js:152095:47)
    at _engine.PersistedPhysicalShape.new.apply (http://localhost:45989/dart_sdk.js:152013:24)
    at _engine.PersistedPhysicalShape.new.build (http://localhost:45989/dart_sdk.js:150428:12)
    at _engine.PersistedPhysicalShape.new.build (http://localhost:45989/dart_sdk.js:150649:13)
    at _engine.PersistedOffset.new.build (http://localhost:45989/dart_sdk.js:150665:17)
    at _engine.PersistedClipRect.new.[_updateManyToMany] (http://localhost:45989/dart_sdk.js:150860:22)
    at _engine.PersistedClipRect.new.update (http://localhost:45989/dart_sdk.js:150691:32)
    at _engine.PersistedClipRect.new.update (http://localhost:45989/dart_sdk.js:151812:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45989/dart_sdk.js:150808:18)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:150687:31)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:152521:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45989/dart_sdk.js:150786:18)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:150687:31)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:152521:13)
    at _engine.PersistedOffset.new.[_updateManyToMany] (http://localhost:45989/dart_sdk.js:150848:20)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:150691:32)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:152521:13)
    at _engine.PersistedClipRRect.new.[_updateManyToMany] (http://localhost:45989/dart_sdk.js:150848:20)
    at _engine.PersistedClipRRect.new.update (http://localhost:45989/dart_sdk.js:150691:32)
    at _engine.PersistedClipRRect.new.update (http://localhost:45989/dart_sdk.js:151898:13)
    at _engine.PersistedTransform.new.[_updateManyToMany] (http://localhost:45989/dart_sdk.js:150848:20)
    at _engine.PersistedTransform.new.update (http://localhost:45989/dart_sdk.js:150691:32)
    at _engine.PersistedTransform.new.update (http://localhost:45989/dart_sdk.js:160161:13)
    at _engine.PersistedPhysicalShape.new.[_updateManyToMany] (http://localhost:45989/dart_sdk.js:150848:20)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:45989/dart_sdk.js:150691:32)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:45989/dart_sdk.js:152122:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45989/dart_sdk.js:150786:18)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:150687:31)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:152521:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45989/dart_sdk.js:150786:18)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:150687:31)
    at _engine.PersistedOffset.new.update (http://localhost:45989/dart_sdk.js:152521:13)
    at _engine.PersistedTransform.new.[_updateManyToOne] (http://localhost:45989/dart_sdk.js:150786:18)
    at _engine.PersistedTransform.new.update (http://localhost:45989/dart_sdk.js:150687:31)
    at _engine.PersistedTransform.new.update (http://localhost:45989/dart_sdk.js:160161:13)
    at _engine.PersistedScene.new.[_updateManyToOne] (http://localhost:45989/dart_sdk.js:150786:18)
    at _engine.PersistedScene.new.update (http://localhost:45989/dart_sdk.js:150687:31)
    at http://localhost:45989/dart_sdk.js:159907:33
    at Object.timeAction (http://localhost:45989/dart_sdk.js:168719:14)
    at _engine.SurfaceSceneBuilder.new.build (http://localhost:45989/dart_sdk.js:159903:22)
    at layer$.TransformLayer.new.buildScene (http://localhost:45989/packages/flutter/src/rendering/layer.dart.lib.js:1132:27)
    at view.RenderView.new.compositeFrame (http://localhost:45989/packages/flutter/src/rendering/layer.dart.lib.js:4370:32)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:45989/packages/flutter/src/rendering/layer.dart.lib.js:5405:25)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:45989/packages/flutter/src/widgets/widget_span.dart.lib.js:44386:15)
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:45989/packages/flutter/src/rendering/layer.dart.lib.js:5381:12)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:45989/packages/flutter/src/scheduler/binding.dart.lib.js:727:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:45989/packages/flutter/src/scheduler/binding.dart.lib.js:699:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:45989/packages/flutter/src/scheduler/binding.dart.lib.js:656:12)
    at Object._invoke (http://localhost:45989/dart_sdk.js:170562:7)
    at _engine.EngineWindow.new.invokeOnDrawFrame (http://localhost:45989/dart_sdk.js:167120:15)
    at http://localhost:45989/dart_sdk.js:167678:28"

**Comment by pedromassangocode** [comment]
I can confirm that this issue exist in the latest master channel.

<details>
<summary> complete sample code</summary>

```
import 'package:flutter/material.dart';

class Sample extends StatefulWidget {
  static const routeName = '/sample';
  Sample({Key key}) : super(key: key);

  @override
  _SampleState createState() => _SampleState();
}

class _SampleState extends State<Sample> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: Drawer(),
      body: Container(width: 600, child: ListoftextS()),
    );
  }
}

class ListoftextS extends StatefulWidget {
  const ListoftextS({Key key}) : super(key: key);

  @override
  _ListoftextSState createState() => _ListoftextSState();
}

class _ListoftextSState extends State<ListoftextS> {
  List listoftext;
  @override
  Widget build(BuildContext context) {
    listoftext = List<int>.generate(20, (i) => i + 1);
    return Container(
      color: Colors.black12,
      padding: EdgeInsets.all(5),
      child: Column(
        children: [
          SizedBox(height: 10),
          SizedBox(height: 5),
          Expanded(
            child: ListView.builder(
              shrinkWrap: true,
              itemBuilder: (context, idx) {
                return Card(
                    elevation: 5,
                    margin: EdgeInsets.all(1.5),
                    shape: BeveledRectangleBorder(),
                    child: Container(
                        child: Text('${listoftext[idx]}'),
                        width: 100,
                        height: 70));
              },
              itemCount: listoftext.length,
            ),
          ),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.191, on Mac OS X 10.15.6 19G73,
    locale en)
    • Flutter version 1.21.0-6.0.pre.191 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision f3b7788f77 (9 hours ago), 2020-08-05 00:11:03 -0400
    • Engine revision e1828008b9
    • Dart version 2.10.0 (build 2.10.0-3.0.dev 987c9e347c)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.4
    • Dart plugin version 202.6397.47

[✓] Connected device (4 available)
    • iPhone SE (2nd generation) (mobile) • 1119074E-0493-4533-9212-6758A33EB40C
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 84.0.4147.105

! Doctor found issues in 2 categories.
```
</details>

**Comment by ferhatb** [comment]
@cbenhagen Thank you so much for providing sample to repro this issue. Issue is resolved (was crash in debug mode, potential leak in release mode). In review, should land in master channel shortly.

**Comment by ferhatb** [comment]
In master.

**Comment by jonaird** [comment]
I'm getting this issue again in the beta channel (1.24.0-10.2.pre) except with a different exception:
```

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/picture.dart:54:10
canvas == null || !_recycledCanvases.contains(canvas)
is not true


When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
lib/_engine/engine/html/picture.dart 54:62                                    _recycleCanvas
lib/_engine/engine/html/picture.dart 316:7                                    [_applyPaint]
lib/_engine/engine/html/picture.dart 576:7                                    update
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
PersistedPhysicalShape: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
PersistedPhysicalShape: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention
════════════════════════════════════════════════════════════════════════════════
```

**Comment by cbenhagen** [comment]
It might be the best to create a new issue with a full example.

**Comment by arualana** [comment]
To me in happens when I add a gradient background to a completely unrelated Container that is somewhere completely different in the tree
