### ISSUE TITLE
[Bug] Animation with changing element Widget on a Table Widget needs a delay before start

### ISSUE THREAD

**Issue by CareF** [flutter/flutter#60488]
Internal: b/169206304

A minimum example https://dartpad.dev/23a5a2cfe720344911103270782cb203
This example has `Script error.` but uncomment the `Future` sentence surrounding `_controller.repeat()` it will run normally. 

The error message if running from a desktop IDE will look like: 
```
I/flutter (12477): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12477): The following assertion was thrown building _BodyBuilder:
I/flutter (12477): 'package:flutter/src/rendering/table.dart': Failed assertion: line 682 pos 12: 'x != null': is not
I/flutter (12477): true.
I/flutter (12477): 
I/flutter (12477): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12477): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12477): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12477):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12477): 
I/flutter (12477): The relevant error-causing widget was:
I/flutter (12477):   Scaffold file:///Users/minglyu/tmp/sample/lib/main.dart:41:16
I/flutter (12477): 
I/flutter (12477): When the exception was thrown, this was the stack:
I/flutter (12477): #2      RenderTable.setChild (package:flutter/src/rendering/table.dart:682:12)
I/flutter (12477): #3      _TableElement.removeChildRenderObject (package:flutter/src/widgets/table.dart:286:18)
I/flutter (12477): #4      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:5732:36)
I/flutter (12477): #5      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:3390:13)
I/flutter (12477): #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
I/flutter (12477): #7      Element.detachRenderObject (package:flutter/src/widgets/framework.dart:3389:5)
I/flutter (12477): #8      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:3390:13)
I/flutter (12477): #9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
I/flutter (12477): #10     Element.detachRenderObject (package:flutter/src/widgets/framework.dart:3389:5)
I/flutter (12477): #11     Element.deactivateChild (package:flutter/src/widgets/framework.dart:3525:11)
I/flutter (12477): #12     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5659:11)
......
```

I believe this is due to some scheduling issue and triggers animation before fully initialize the Table widget.

**Comment by CareF** [comment]
@HansMuller

**Comment by goderbauer** [comment]
In the latest version of Flutter this still fails, but the error is slightly different:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building _BodyBuilder:
Null check operator used on a null value

The relevant error-causing widget was:
  Scaffold file:///Users/goderbauer/dev/playground/lib/main.dart:40:16

When the exception was thrown, this was the stack:
#0      _TableElement.removeRenderObjectChild (package:flutter/src/widgets/table.dart:396:44)
#1      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:5831:37)
#2      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:3557:13)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4686:14)
#4      Element.detachRenderObject (package:flutter/src/widgets/framework.dart:3556:5)
#5      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:3557:13)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4686:14)
#7      Element.detachRenderObject (package:flutter/src/widgets/framework.dart:3556:5)
#8      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3697:11)
#9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5752:11)
#10     _TableElement.update (package:flutter/src/widgets/table.dart:431:19)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#14     StatelessElement.update (package:flutter/src/widgets/framework.dart:4713:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#18     ProxyElement.update (package:flutter/src/widgets/framework.dart:4985:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#22     ProxyElement.update (package:flutter/src/widgets/framework.dart:4985:5)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#24     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5659:32)
#25     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6308:17)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4805:11)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#30     StatefulElement.update (package:flutter/src/widgets/framework.dart:4837:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#34     ProxyElement.update (package:flutter/src/widgets/framework.dart:4985:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4805:11)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#39     StatefulElement.update (package:flutter/src/widgets/framework.dart:4837:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6154:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#45     StatelessElement.update (package:flutter/src/widgets/framework.dart:4713:5)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6154:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4805:11)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#52     StatefulElement.update (package:flutter/src/widgets/framework.dart:4837:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#55     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4805:11)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#57     StatefulElement.update (package:flutter/src/widgets/framework.dart:4837:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#61     ProxyElement.update (package:flutter/src/widgets/framework.dart:4985:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#65     StatelessElement.update (package:flutter/src/widgets/framework.dart:4713:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4805:11)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#70     StatefulElement.update (package:flutter/src/widgets/framework.dart:4837:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#74     ProxyElement.update (package:flutter/src/widgets/framework.dart:4985:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#77     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4805:11)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#79     StatefulElement.update (package:flutter/src/widgets/framework.dart:4837:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3401:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4657:16)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4805:11)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#84     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2619:33)
#85     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:878:21)
#86     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#87     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1147:15)
#88     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1084:9)
#89     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:867:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```
