### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = '/home/marcio/curso_flutter/olamundo/.packages' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by marcio0782** [flutter/flutter#60484]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = '/home/marcio/curso_flutter/olamundo/.packages' (OS Error: Operation not permitted, errno = 1)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:213:19)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#12     _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart)
#13     _rootRunUnary (dart:async/zone.dart:1192:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
```
```
[✓] Flutter (Channel stable, v1.17.3, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.17.3 at /usr/local/flutter
    • Framework revision b041144f83 (3 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/marcio/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/90/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.0

[!] Connected device
    • Device 0050110863 is not authorized.
      You might need to check your device for an authorization dialog.

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b041144f833e05cf463b8887fa12efdec9493488

**Comment by iapicca** [comment]
Hi @marcio0782 
I see there's an open [issue](https://github.com/flutter/flutter/issues/50880) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
