### ISSUE TITLE
[Windows] Unable to run desktop application 

### ISSUE THREAD

**Issue by hillelcoren** [flutter/flutter#60520]
Creating a blank Flutter project and trying to run it on Windows desktop results in an error. 

Let me know if there's any other info I can provide.

Thanks for your help!

```
$ flutter doctor -v
[√] Flutter (Channel master, 1.20.0-3.0.pre.78, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.20.0-3.0.pre.78 at C:\Users\hillel\Documents\flutter
    • Framework revision 2962912d68 (2 days ago), 2020-06-27 00:59:50 -0700
    • Engine revision fc0e27210c
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 63cf56d925)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\hillel\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\hillel\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30204.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (5 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows desktop           • windows       • windows-x64    • Microsoft Windows [Version 10.0.18362.900]
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.116
    • Edge                      • edge          • web-javascript • Microsoft Edge 81.0.416.81

• No issues found!
```

```
$ flutter run -d windows -v
[  +79 ms] executing: [C:\Users\hillel\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2962912d68fb72d6c9fd60f652e27f3593d692d6
[        ] executing: [C:\Users\hillel\Documents\flutter/] git tag --contains HEAD
[ +141 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [C:\Users\hillel\Documents\flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +21 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.20.0-2.0.pre-78-g2962912d6
[   +6 ms] executing: [C:\Users\hillel\Documents\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Users\hillel\Documents\flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[  +38 ms] executing: [C:\Users\hillel\Documents\flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] executing: C:\Users\hillel\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +34 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +132 ms] Generating C:\Users\hillel\Documents\windows_test\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +84 ms] Starting incremental build...
[   +2 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +2 ms] Launching lib\main.dart on Windows desktop in debug mode...
[   +3 ms] C:\Users\hillel\Documents\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\hillel\Documents\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\hillel\Documents\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\hillel\AppData\Local\Temp\flutter_tools.d2add905\flutter_tool.a86fa8cd\app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +14 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64
[  +18 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64
[        ] [
             {
               "instanceId": "9f3ef85d",
               "installDate": "2020-06-17T15:20:41Z",
               "installationName": "VisualStudio/16.6.2+30204.135",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.6.30204.135",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.6.2",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2020-06-17T15:20:41.6954092Z",
               "catalog": {
                 "buildBranch": "d16.6",
                 "buildVersion": "16.6.30204.135",
                 "id": "VisualStudio/16.6.2+30204.135",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.6.2",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "2",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.6.2+30204.135",
                 "requiredEngineVersion": "2.6.2109.55756"
               },
               "properties": {
                 "campaignId": "1616871430.1579023946",
                 "channelManifestId": "VisualStudio.16.Release/16.6.2+30204.135",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[   +1 ms] Building Windows application...
[   +1 ms] executing: [C:\Users\hillel\Documents\windows_test\windows/] C:\Users\hillel\Documents\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[   +3 ms] <- compile package:windows_test/main.dart
[ +149 ms] **********************************************************************
[        ] ** Visual Studio 2019 Developer Command Prompt v16.6.2
[        ] ** Copyright (c) 2020 Microsoft Corporation
[        ] **********************************************************************
[ +510 ms] \Microsoft was unexpected at this time.
[   +7 ms] Building Windows application... (completed in 0.7s)
[+3650 ms] Exception: Build process failed. To view the stack trace, please run `flutter run -d windows -v`.
[        ] "flutter run" took 4,670ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:853:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +252 ms] ensureAnalyticsSent: 251ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by TahaTesser** [comment]
Hi @hillelcoren 
Even tho you can ran `flutter run -d windows -v`, logs still says, which is weird
```
[+3650 ms] Exception: Build process failed. To view the stack trace, please run `flutter run -d windows -v`.
```

**Comment by stuartmorgan** [comment]
> Even tho you can ran flutter run -d windows -v, logs still says

That's just a tool bug; it logs that on any build failure on Windows without checking if it's already in verbose mode.

The issue is:
> \Microsoft was unexpected at this time.

This is similar to https://github.com/google/flutter-desktop-embedding/issues/687, which was never resolved, but was below the level of Flutter tooling. Are you able to run `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat` successfully directly, or does it give the same error?

When I investigated that issue at the time, general search results for that type of error message suggested it might be a problem with something in your `PATH` configuration (e.g., something improperly quoted).

**Comment by hillelcoren** [comment]
Thanks for the info! If I try running the .bat file directly I see the same error.

I don't see anything wrong in my path, happy to post it if it will help 

If it's quote related maybe it's from the space in "Program Files (x86)"?

**Comment by hillelcoren** [comment]
Just noticed the comment in the other issue, I'll try to debug the script...

Thanks again!

**Comment by stuartmorgan** [comment]
> If it's quote related maybe it's from the space in "Program Files (x86)"?

Everyone has that space in their path; almost nobody has this problem. There's something specific to your machine/configuration.

Given that you can't run `vcvars64.bat`, this definitely isn't at all Flutter-specific. You might try posting about the issue on some Windows and/or Visual Studio support forums, where more people will see it (especially more people with Windows development experience), as I don't have any suggestions a this point other than digging into the script.

Please do update if you find out what the cause is though, in case others hit this in the future.

**Comment by hillelcoren** [comment]
Thanks for your help, I found the problem. You were correct, it was path related. 

In the "Edit environment variable" UI on Windows I had `%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools` listed as one value, breaking it up into `%ANDROID_HOME%\tools` and `%ANDROID_HOME%\platform-tools` solved it.
