### ISSUE TITLE
`flutter ide-config` is broken

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#60561]
See the crash report below. I suspect that it's caused by https://github.com/flutter/flutter/pull/59507/

##############################################################
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter ide-config --overwrite

## exception

_AssertionError: Failed assertion: boolean expression must not be null

```
#0      Template.render.renderPath (package:flutter_tools/src/template.dart:128:59)
#1      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:187:53)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#3      Template.render (package:flutter_tools/src/template.dart:181:24)
#4      IdeConfigCommand._renderTemplate (package:flutter_tools/src/commands/ide_config.dart:257:21)
#5      IdeConfigCommand.runCommand (package:flutter_tools/src/commands/ide_config.dart:237:23)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:853:18)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.90, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.20.0-3.0.pre.90 at e:\src\flutter\flutter
    • Framework revision 09cca73aee (89 minutes ago), 2020-06-29 13:44:38 -0700
    • Engine revision c332675a8c
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 63cf56d925)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Yuqian\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.46.0)
    • VS Code at C:\Users\Yuqian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by liyuqian** [comment]
CC @cyanglaz @jonahwilliams @jmagman

**Comment by liyuqian** [comment]
I confirmed that it won't crash with 14992c59518782fc8f4448378db68791b7fe265e. I guess that we don't have CI test coverages for `flutter ide-config` and it may be nice to add one.

**Comment by jonahwilliams** [comment]
Not that we shouldn't fix this, but flutter ide-config is now hidden and we're going to eventually remove it from the tool altogether (https://github.com/flutter/flutter/issues/29805) since it is not a customer facing tool.

**Comment by jonahwilliams** [comment]
Assigning to  @cyanglaz  to investigate.

**Comment by jonahwilliams** [comment]
Closing as fixed
