### ISSUE TITLE
Flutter drive returns no error in stdout in case app crashes

### ISSUE THREAD

**Issue by vvargas90** [flutter/flutter#60584]
As part of the CI I've a set of UI tests that are completely mocked. These tests are part of the CI pipeline we have in Jenkins and are executed using `flutter drive`. I want that in case the tests fail for any kind of reason build is marked as failure. Sometimes that wasn't happening but I found a way to reproduce it.

**Steps to reproduce:**
1. Stub all the network requests using mockito. 
2. Configure all stubs to `throwOnMissingStub`, making it throw a NoSuchMethodError (you can read further about it [here](https://pub.dev/documentation/mockito/latest/mockito/throwOnMissingStub.html))
3. Make app exit(1) in case something not expected happens. This is the code we use:
```  
void _onError(Object error, StackTrace st) {
    if (ErrorUtils.isFatalError(error)) {
      _printError(error, st);
      _stopApp();
    } else {
      throw error;
    }
  }

  void _printError(Object error, StackTrace st) {
    print('Exception: $error');
    print(st ?? 'No stacktrace available');
  }

  void _stopApp() {
    print('============================================================');
    print('Fatal error found!!! Stopping the app...');
    print('============================================================');
    exit(1);
  }
```
4. Make the UI test fail not stubbing something 

**Expected result**
App crash, test execution is aborted and error is captured in stdout making build fail.

**Actual result**
App crash, test execution is aborted but there's no error

**Comment by TahaTesser** [comment]
Hi @vvargas90 
Can you please provide your `flutter doctor -v` your `flutter driver -t  --verbose test_driver/example.dart` with test fail and a complete reproducible minimal code sample or sample code repository 
Thank you

**Comment by vvargas90** [comment]
Flutter doctor:
```[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.14.6 18G4032, locale en)
    • Flutter version 1.17.4 at /Users/victorvargas/Desktop/flutter
    • Framework revision 1ad9baa8b9 (13 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/victorvargas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/victorvargas/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API
      29) (emulator)```

Sadly I can't share the codebase as it belongs to the company I'm working at, would you accept the test logs?

**Comment by vvargas90** [comment]
This is the last log from the failing test I was mentioning you:
```
[  +17 ms] I/flutter ( 8197): Exception: NoSuchMethodError: Class 'Object' has no instance method 'setShouldShowLastJobWarning'.
[        ] I/flutter ( 8197): Receiver: Instance of 'Object'
[        ] I/flutter ( 8197): Tried calling: setShouldShowLastJobWarning(true)
[   +1 ms] I/flutter ( 8197): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] I/flutter ( 8197): #1      Mock._noSuchMethod (package:mockito/src/mock.dart:136:22)
[        ] I/flutter ( 8197): #2      Mock.noSuchMethod (package:mockito/src/mock.dart:130:45)
[        ] I/flutter ( 8197): #3      MockUserSettingsRepository.setShouldShowLastJobWarning
           (package:driver/repository/user_settings/user_settings_repository.dart:26:16)
[        ] I/flutter ( 8197): #4      StatusButtonPresenter.lastJobAlertDismissed (package:driver/presenters/status_button_presenter.dart:137:10)
[        ] I/flutter ( 8197): #5      StatusButtonsContainerState.showLastJobWarning.<anonymous closure>.<anonymous closure>
           (package:driver/widgets/status_buttons_container.dart:156:20)
[  +19 ms] I/flutter ( 8197): #6      _LastJobAlertDialogState.build.<anonymous closure> (package:driver/dialogs/last_job_alert_dialog.dart:48:41)
[        ] I/flutter ( 8197): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
[        ] I/flutter ( 8197): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
[        ] I/flutter ( 8197): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] I/flutter ( 8197): #10 
[        ] I/flutter ( 8197): ============================================================
[        ] I/flutter ( 8197): Fatal error found!!! Stopping the app...
[        ] I/flutter ( 8197): ============================================================
[ +162 ms] VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
[        ] VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
[+4801 ms] VMServiceFlutterDriver: tap message is taking a long time to complete...
[+17466 ms] 02:00 +20 -1: main_screen tests should set driver status last job [E]
[   +1 ms]   TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
[  +26 ms]   package:test_api/src/backend/invoker.dart 333:28               Invoker._handleError.<fn>
[        ]   dart:async/zone.dart 1180:38                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   package:test_api/src/backend/invoker.dart 331:10               Invoker._handleError
[        ]   package:test_api/src/backend/invoker.dart 287:9                Invoker.heartbeat.<fn>.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   package:test_api/src/backend/invoker.dart 286:38               Invoker.heartbeat.<fn>
[        ]   package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
[        ]   package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
[        ]   dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
[        ]   dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
[        ]   dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
[        ]   dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
[        ]   dart:async/zone.dart 1002:22                                   _CustomZone.bindCallback
[        ]   dart:async/zone.dart 1251:21                                   _rootCreateTimer
[        ]   dart:async/zone.dart 1145:19                                   _CustomZone.createTimer
[        ]   package:test_api/src/backend/invoker.dart 285:34               Invoker.heartbeat
[        ]   package:test_api/src/backend/invoker.dart 239:5                Invoker.waitForOutstandingCallbacks
[        ]   package:test_api/src/backend/declarer.dart 170:33              Declarer.test.<fn>.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1619:10                                   _runZoned
[        ]   dart:async/zone.dart 1539:10                                   runZoned
[        ]   package:test_api/src/backend/declarer.dart 169:13              Declarer.test.<fn>
[        ]   package:test_api/src/backend/invoker.dart 400:30               Invoker._onRun.<fn>.<fn>.<fn>.<fn>
[        ]   dart:async/future.dart 176:37                                  new Future.<fn>
[        ]   package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
[        ]   package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
[        ]   dart:async/zone.dart 1180:38                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
[  +33 ms]   dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
[        ]   package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
[        ]   package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
[        ]   dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
[        ]   dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
[        ]   dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
[        ]   dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
[        ]   ===== asynchronous gap ===========================
[        ]   dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
[        ]   dart:async/zone.dart 1018:22                                   _CustomZone.bindCallbackGuarded
[        ]   dart:async/timer.dart 54:45                                    new Timer
[        ]   dart:async/timer.dart 91:9                                     Timer.run
[        ]   dart:async/future.dart 174:11                                  new Future
[        ]   package:test_api/src/backend/invoker.dart 399:21               Invoker._onRun.<fn>.<fn>.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1619:10                                   _runZoned
[        ]   dart:async/zone.dart 1539:10                                   runZoned
[        ]   package:test_api/src/backend/invoker.dart 387:9                Invoker._onRun.<fn>.<fn>
[        ]   package:test_api/src/backend/invoker.dart 438:15               Invoker._guardIfGuarded
[        ]   package:test_api/src/backend/invoker.dart 386:7                Invoker._onRun.<fn>
[        ]   package:stack_trace/src/chain.dart 101:24                      Chain.capture.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 1619:10                                   _runZoned
[        ]   dart:async/zone.dart 1539:10                                   runZoned
[        ]   package:stack_trace/src/chain.dart 99:12                       Chain.capture
[        ]   package:test_api/src/backend/invoker.dart 385:11               Invoker._onRun
[        ]   package:test_api/src/backend/live_test_controller.dart 197:11  LiveTestController._run
[        ]   package:test_api/src/backend/live_test_controller.dart 50:37   _LiveTest.run
[        ]   dart:async/future.dart 202:37                                  new Future.microtask.<fn>
[        ]   dart:async/zone.dart 1180:38                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
[        ]   dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
[        ]   dart:async/zone.dart 1184:13                                   _rootRun
[        ]   dart:async/zone.dart 1077:19                                   _CustomZone.run
[        ]   dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
[        ]   dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
[        ]   dart:async/schedule_microtask.dart 43:21                       _microtaskLoop
[        ]   dart:async/schedule_microtask.dart 52:5                        _startMicrotaskLoop
[        ]   dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
[        ]   dart:isolate-patch/timer_impl.dart 405:11                      _Timer._runTimers
[        ]   dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
[        ]   dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
[+4964 ms] VMServiceFlutterDriver: request_data message is taking a long time to complete...
[  +64 ms] Stopping application instance.
[        ] Stopping application.
[        ] executing: /Users/blabla/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.stuart.driver.beta
[  +97 ms] "flutter drive" took 174,850ms.
```
There you can see the exception I did on purpose that I described on the bug report and then flutter drive finishing without error but with tests to be completed.

**Comment by TahaTesser** [comment]
Hi @vvargas90 
Can you please.provide a complete reproducible minimal code sample or sample code repository
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
