### ISSUE TITLE
[Linux] A lot of logs from TextField when viewing Flutter App

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [flutter/flutter#60729]
## Steps to Reproduce

When a Flutter app with TextField is launched and the system **clipboard is empty**, a lot of logs are displayed.

1. $ git clone https://github.com/google/flutter-desktop-embedding.git
2. $ cd flutter-desktop-embedding/testbed
3. $ flutter run -d linux

flutter doctor -v

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.117, on Linux, locale ja_JP.UTF-8)
    • Flutter version 1.20.0-3.0.pre.117 at /opt/flutter
    • Framework revision 3f4f91532f (7 hours ago), 2020-07-01 13:58:01 -0400
    • Engine revision 88a8e9db18
    • Dart version 2.9.0 (build 2.9.0-19.0.dev bec128612c)
```

<details>
  <summary>Logs</summary>

```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                   
Waiting for Linux to report its views...                             3ms
Syncing files to device Linux...                                   430ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:38209/4FRCNpoeZkU=/
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(Clipboard Request Failed, Failed to retrieve clipboard text from GTK, null)
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:151:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
<asynchronous suspension>
#2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:458:18)
#3      Clipboard.getData (package:flutter/src/services/clipboard.dart:58:71)
#4      ClipboardStatusNotifier.update (package:flutter/src/widgets/text_selection.dart:1544:15)
#5      ClipboardStatusNotifier.addListener (package:flutter/src/widgets/text_selection.dart:1561:7)
#6      EditableTextState.initState (package:flutter/src/widgets/editable_text.dart:1385:23)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#14     _RenderDecorationElement._mountChild (package:flutter/src/material/input_decorator.dart:1561:30)
#15     _RenderDecorationElement.mount (package:flutter/src/material/input_decorator.dart:1576:5)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#70     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#74     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#81     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#85     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#92     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#95     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#109    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
#110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#117    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#120    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#123    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#126    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#129    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#132    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#135    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#141    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#144    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#146    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#148    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#150    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#151    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#152    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#155    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#161    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#165    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#166    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#167    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#168    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#170    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#174    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#176    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#177    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#178    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#179    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#182    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#183    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#184    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#185    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#188    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#190    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#193    _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:137:18)
#194    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
#195    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:117:11)
#196    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1868:58)
#197    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:920:15)
#198    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1868:13)
#199    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:226:7)
#200    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:299:5)
#201    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#202    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
#203    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:495:7)
#204    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
#205    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
#206    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#207    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#208    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#209    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#210    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
#211    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#212    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#213    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#214    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#215    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#216    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#217    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#218    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#219    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#220    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#221    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#222    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#223    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#224    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#225    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#226    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#227    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3238:13)
#228    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#229    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#230    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#231    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
#232    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#233    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#234    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#235    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#236    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#237    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#238    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#239    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#240    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#241    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#242    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#243    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
#244    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#245    RenderView.performLayout (package:flutter/src/rendering/view.dart:169:13)
#246    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
#247    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
#248    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
#249    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#250    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#251    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1115:15)
#252    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1054:9)
#253    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
#254    _rootRun (dart:async/zone.dart:1182:47)
#255    _CustomZone.run (dart:async/zone.dart:1093:19)
#256    _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#257    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#258    _rootRun (dart:async/zone.dart:1190:13)
#259    _CustomZone.run (dart:async/zone.dart:1093:19)
#260    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#261    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#262    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#263    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#264    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

</details>

**Comment by stuartmorgan** [comment]
/cc @robert-ancell 

(@HidenoriMatsubayashi you don't need to indicate that you're using GTK now that it's the only option. My comment before was about identifying GTK bugs filed when GLFW was the embedding that was used and someone had to go way out of their way to use GTK.)

**Comment by robert-ancell** [comment]
I guess we shouldn't report this as an error. The GTK [documentation](https://developer.gnome.org/gtk3/stable/gtk3-Clipboards.html#gtk-clipboard-request-text) states:

> The text parameter to callback will contain the resulting text if the request succeeded, or NULL if it failed. This could happen for various reasons, in particular if the clipboard was empty or if the contents of the clipboard could not be converted into text form.

**Comment by stuartmorgan** [comment]
This was fixed by the PR above.

**Comment by HidenoriMatsubayashi** [comment]
I confirmed the issue was fixed. Thank you so much.
