### ISSUE TITLE
Tried to paint a RenderObject before its compositing bits were updated

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#60746]
## Steps to reproduce

Run the following app:

```dart
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TestWidget(
      child: ColoredBox(
        color: Color(0xffff0000),
        child: SizedBox(width: 10, height: 10),
      ),
    );
  }
}

class TestWidget extends RenderObjectWidget {
  const TestWidget({this.child});

  final Widget child;

  @override
  RenderObjectElement createElement() => _TestElement(this);

  @override
  RenderObject createRenderObject(BuildContext context) => _RenderTest();
}

class _TestElement extends RenderObjectElement {
  _TestElement(TestWidget widget) : super(widget);

  Element _child;

  @override
  TestWidget get widget => super.widget as TestWidget;

  @override
  void mount(Element parent, dynamic newSlot) {
    super.mount(parent, newSlot);
    _child = inflateWidget(widget.child, 'slot');
  }

  @override
  void visitChildren(ElementVisitor visitor) {
    visitor(_child);
  }

  @override
  void insertChildRenderObject(RenderObject child, dynamic slot) {
    final _RenderTest renderObject = this.renderObject;
    renderObject.child = child;
  }

  @override
  void moveChildRenderObject(RenderObject child, dynamic slot) {
    throw UnsupportedError('moveChildRenderObject()');
  }

  @override
  void removeChildRenderObject(RenderObject child) {
    final _RenderTest renderObject = this.renderObject;
    renderObject.child = null;
  }
}

class _RenderTest extends RenderBox {
  RenderBox _child;
  RenderBox get child => _child;
  set child(RenderBox value) {
    if (_child != null) dropChild(_child);
    _child = value;
    if (_child != null) adoptChild(_child);
  }

  @override
  void performLayout() {
    child.layout(BoxConstraints.tightForFinite(), parentUsesSize: true);
    size = constraints.biggest;
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    context.paintChild(child, offset);
  }
}
```

## Expected Behavior

You expect the app to render a small colored box.  Or if there's an implementation error in TestWidget, then you hope for an informative error as to what you've done wrong.

## Actual behavior

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
Tried to paint a RenderObject before its compositing bits were updated.
The following RenderObject was marked as having dirty compositing bits at the time that it was painted:
  _RenderColoredBox#94d87 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: ColoredBox ← TestWidget ← BugReport ← [root]
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(unconstrained)
  size: Size(10.0, 10.0)
  behavior: opaque
A RenderObject that still has dirty compositing bits cannot be painted because this indicates that
the tree has not yet been properly configured for creating the layer tree.
This usually indicates an error in the Flutter framework itself.

The relevant error-causing widget was:
  TestWidget file:///Users/tvolkert/project/sci/apps/payouts/lib/bug_report.dart:11:12

When the exception was thrown, this was the stack:
#0      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2235:9)
#1      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2255:6)
#2      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#3      _RenderTest.paint (package:payouts/bug_report.dart:86:13)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:186:13)
#6      RenderView.paint (package:flutter/src/rendering/view.dart:215:15)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2266:7)
#8      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:137:11)
#9      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:97:5)
#10     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:982:29)
#11     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:406:19)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1115:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1054:9)
#16     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

The following RenderObject was being processed when the exception was fired: _RenderTest#27566:
  creator: TestWidget ← BugReport ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=772.0, h=621.0)
  size: Size(772.0, 621.0)
This RenderObject has no descendants.
```

**Comment by tvolkert** [comment]
The issue is that I didn't override `visitChildren(RenderObjectVisitor visitor)` in `_RenderTest` to visit the child.  I wonder if there's any way for the framework to detect this in debug mode and provide a better error message?
