### ISSUE TITLE
[tool_crash] FormatException: No ':' on line (at offset 2037)

### ISSUE THREAD

**Issue by rudirudman** [flutter/flutter#60781]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException: FormatException: No ':' on line (at offset 2037)
```
#0      parse (package:package_config/packages_file.dart:64:7)
#1      _parse (package:flutter_tools/src/dart/package_map.dart:17:10)
#2      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:49:14)
#3      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:53:5)
#4      new PackageUriMapper (package:flutter_tools/src/compile.dart:199:116)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:647:26)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:408:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:388:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:693:23)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#16     _rootRun (dart:async/zone.dart:1182:47)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
```
```
[✓] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.900], locale en-ZA)
    • Flutter version 1.17.0 at C:\flutter
    • Framework revision d3ed9ec945 (3 months ago), 2020-04-06 14:07:34 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\rudir\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\rudir\AppData\Local\Android\Sdk\platforms
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\rudir\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • SM J600F • 52000dda58c25559 • android-arm • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: d3ed9ec945f8869f0e136c357d0c2a6be2b60c98

**Comment by iapicca** [comment]
Hi @rudirudman 
I see there's an open [issue](https://github.com/flutter/flutter/issues/57864) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
