### ISSUE TITLE
file attached

### ISSUE THREAD

**Issue by chandupolu** [flutter/flutter#60815]
[flutter_02.log](https://github.com/flutter/flutter/files/4869495/flutter_02.log)

## command

flutter run --machine --target lib\main.dart -d 2c92c28e --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused

## exception

ArgumentError: Invalid argument(s): Cannot find executable for C:\chandu\New folder\MY PROJECTS\Flutter\sample\android\gradlew.bat.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:384:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:102:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:513:28)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale en-GB)
    • Flutter version 1.17.5 at C:\Flutter
    • Framework revision 8af6b2f038 (3 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\anjaiah\Android\SDK
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\anjaiah\Android\SDK
    • Java binary at: C:\chandu\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\chandu\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\anjaiah\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • RMX1971 • 2c92c28e • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by chandupolu** [comment]
[flutter_02.log](https://github.com/flutter/flutter/files/4869507/flutter_02.log)

**Comment by VladyslavBondarenko** [comment]
@chandupolu 
please follow up on https://github.com/flutter/flutter/issues/56975,
I'm closing current issue as duplicate. Check if https://github.com/flutter/flutter/issues/56975#issuecomment-633432999 is your case
