### ISSUE TITLE
Android build fails with cloud_firestore exception

### ISSUE THREAD

**Issue by CrispinPowers** [flutter/flutter#60830]
Android build fails, problem seems to be in the android\build.gradle file. 
Didn't change anything from last successful build.

What I tried so far:

1. Run 'flutter clean' & 'flutter run'
2. Uninstalled & reinstalled the app on the emulator
3. Upgrade & downgrade Flutter

Thanks for your help.

## Error
```
FAILURE: Build failed with an exception.

* Where:
Build file '...\android\build.gradle' line: 27

* What went wrong:
A problem occurred evaluating root project 'android'.
Project with path ':app' could not be found in project ':cloud_firestore'.
```

## android\build.gradle file
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'  
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

## Steps to Reproduce
1. Run 'flutter run'

## flutter run --verbose
```
[  +53 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +246 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[  +17 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +696 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.5
[  +29 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +92 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +94 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +220 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +145 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +14 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +155 ms] executing: C:\Users\xx\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +97 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +17 ms] C:\Users\xx\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +128 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +21 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +17 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +44 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +250 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.7\
[  +18 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +18 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-0.5.0\
[  +33 ms] Found plugin cloud_functions_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-1.1.0\
[  +36 ms] Found plugin file_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.12.0\
[  +30 ms] Found plugin firebase_analytics at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[  +29 ms] Found plugin firebase_analytics_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[  +31 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[  +38 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +33 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.6\
[  +41 ms] Found plugin flutter_plugin_android_lifecycle at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[  +45 ms] Found plugin flutter_video_compress at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_video_compress-0.3.7+8\
[ +107 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[  +13 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[  +10 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[  +64 ms] Found plugin screen at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\screen-0.0.5\
[  +31 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[  +34 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[  +37 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +47 ms] Found plugin video_player at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+2\
[  +18 ms] Found plugin video_player_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.3+2\
[  +25 ms] Found plugin wakelock at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.4+2\
[ +108 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.7\
[   +6 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +3 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-0.5.0\
[  +26 ms] Found plugin cloud_functions_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-1.1.0\
[  +11 ms] Found plugin file_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.12.0\
[  +27 ms] Found plugin firebase_analytics at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.16\
[  +28 ms] Found plugin firebase_analytics_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics_web-0.1.1\
[   +3 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.5\
[   +8 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +19 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.6\
[   +5 ms] Found plugin flutter_plugin_android_lifecycle at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[   +8 ms] Found plugin flutter_video_compress at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_video_compress-0.3.7+8\
[  +56 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.11\
[   +9 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +4 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[  +18 ms] Found plugin screen at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\screen-0.0.5\
[  +15 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +3 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +7 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +41 ms] Found plugin video_player at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.11+2\
[  +20 ms] Found plugin video_player_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-0.1.3+2\
[  +28 ms] Found plugin wakelock at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\wakelock-0.1.4+2\
[ +123 ms] Generating D:\Projekte\advent\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +86 ms] ro.hardware = ranchu
[  +69 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with
           "--enable-software-rendering".
[  +57 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +19 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true--output-dill C:\Users\xx\AppData\Local\Temp\flutter_tool.222adba7-bde4-11ea-9e42-f4d10832ce12\app.dill --packages D:\Projekte\advent\.packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts  
--track-widget-creation --filesystem-scheme org-dartlang-root
[  +53 ms] executing: C:\Users\xx\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[ +113 ms] Exit code 0 from: C:\Users\xx\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           07-04 10:50:14.635 E/GnssHAL_GnssInterface( 1806): gnssSvStatusCb: b: input svInfo.flags is 8
[  +51 ms] <- compile package:advent/main.dart
[  +31 ms] executing: C:\Users\xx\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +103 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.3-6597393
                    Installed as C:\Users\xx\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +7 ms] executing: C:\Users\xx\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +85 ms] Building APK
[  +37 ms] Running Gradle task 'assembleDebug'...
[   +6 ms] gradle.properties already sets `android.enableR8`
[  +18 ms] Using gradle from D:\Projekte\advent\android\gradlew.bat.
[   +3 ms] D:\Projekte\advent\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +37 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +198 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +23 ms] executing: [D:\Projekte\advent\android/] D:\Projekte\advent\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=D:\Projekte\advent\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3034 ms] FAILURE: Build failed with an exception.
[  +28 ms] * Where:
[  +86 ms] Build file 'D:\Projekte\advent\android\build.gradle' line: 27
[   +6 ms] * What went wrong:
[  +35 ms] A problem occurred evaluating root project 'android'.
[   +1 ms] > Project with path ':app' could not be found in project ':cloud_firestore'.
[   +2 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.       
[   +4 ms] * Get more help at https://help.gradle.org
[  +31 ms] BUILD FAILED in 2s
[ +493 ms] Running Gradle task 'assembleDebug'... (completed in 4,0s)
[+13887 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +11 ms] "flutter run" took 21.062ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor -v
```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale de-DE)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (4 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\xx\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\xx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by ChiranthSH007** [comment]
same issue found can u suggest if any solution for the same
