### ISSUE TITLE
Hello i m having issue in flutter with ios

### ISSUE THREAD

**Issue by atta1234** [flutter/flutter#60857]
when i create fresh new project, then working smoothly,

but when i copy from project my window to mac ,  and run flutter command  flutter run.
i m getting the following issues, i m not sure hw to resolved these ?

DU243170:fffdesign admin$ flutter run
Launching lib/main.dart on iPhone 11 in debug mode...
 
```
Running pod install...                                              4.2s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_braintree` from `.symlinks/plugins/flutter_braintree/ios`
    -> Fetching podspec for `flutter_country_picker` from
    `.symlinks/plugins/flutter_country_picker/ios`
    -> Fetching podspec for `flutter_facebook_login` from
    `.symlinks/plugins/flutter_facebook_login/ios`
    -> Fetching podspec for `flutter_keyboard_visibility` from
    `.symlinks/plugins/flutter_keyboard_visibility/ios`
    -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `google_sign_in_web` from `.symlinks/plugins/google_sign_in_web/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from
    `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from
    `.symlinks/plugins/shared_preferences_web/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is
      only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_braintree":
      In Podfile:
        flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)

    Specs satisfying the `flutter_braintree (from `.symlinks/plugins/flutter_braintree/ios`)`
    dependency were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in
    `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in
    unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in
    `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in
    `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in
    `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in
    `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in
    `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in
    `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in
    resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in
    `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no
    platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11.
DU243170:fffdesign admin$
```

**Comment by TahaTesser** [comment]
Hi @atta1234 
First clean your project with `flutter clean` and open `ios` folder in terminal and execute `pod init`, `pod install` and `pod update`. Make sure you've iOS configuration for your packages

After this if the problem persist, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and code smaple
Thank you

**Comment by atta1234** [comment]
nothing work still same issue

**Comment by TahaTesser** [comment]
Hi @atta1234 
Please provide the details https://github.com/flutter/flutter/issues/60857#issuecomment-654085615
Thank you

**Comment by atta1234** [comment]
sir i use online mac https://www.macincloud.com/, i can give the login details, everything is installed, and my project is on desktop,

**Comment by atta1234** [comment]
here is the error of commands you said,

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
DU243170:ios admin$ pod init
[!] Existing Podfile found in directory
DU243170:ios admin$ pod install

[!] Invalid `Podfile` file: Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first.

 #  from /Users/admin/Desktop/fffdesign/ios/Podfile:51
 #  -------------------------------------------
 #      unless File.exist?(generated_xcode_build_settings_path)
 >        raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
 #      end
 #  -------------------------------------------
DU243170:ios admin$ pod install

[!] Invalid `Podfile` file: Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first.

 #  from /Users/admin/Desktop/fffdesign/ios/Podfile:51
 #  -------------------------------------------
 #      unless File.exist?(generated_xcode_build_settings_path)
 >        raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
 #      end
 #  -------------------------------------------
DU243170:ios admin$

**Comment by atta1234** [comment]
```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
DU243170:ios admin$ pod init
[!] Existing Podfile found in directory
DU243170:ios admin$ pod install

[!] Invalid `Podfile` file: Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first.

 #  from /Users/admin/Desktop/fffdesign/ios/Podfile:51
 #  -------------------------------------------
 #      unless File.exist?(generated_xcode_build_settings_path)
 >        raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
 #      end
 #  -------------------------------------------
DU243170:ios admin$ pod install

[!] Invalid `Podfile` file: Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first.

 #  from /Users/admin/Desktop/fffdesign/ios/Podfile:51
 #  -------------------------------------------
 #      unless File.exist?(generated_xcode_build_settings_path)
 >        raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
 #      end
 #  -------------------------------------------
DU243170:ios admin$
```

**Comment by TahaTesser** [comment]
Hi @atta1234 
Looks like an issue with your. pod file 
Please try
```
$  brew upgrade ruby
$  gem uninstall cocoapods
$  gem install cocoapods
```

and then delete pod files from your `ios` folder of your project then execute following root of your `ios` folder
`pod init`
`pod install`
`pod update` 

try running the app now with `flutter run --verbose`

After trying this if problem persist and please try new project 
Thank you

**Comment by atta1234** [comment]
the issue was with braintree sdk i removed that, and clean rerun it works

**Comment by TahaTesser** [comment]
Hi  @atta1234 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
