### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/m/Library/Android/sdk/build-tools/30.0.0/aapt.

### ISSUE THREAD

**Issue by developerslearnit** [flutter/flutter#60882]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/m/Library/Android/sdk/build-tools/30.0.0/aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#5      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:524:34)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:429:54)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:361:31)
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:564:37)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/m/Desktop/flutter
    • Framework revision 8af6b2f038 (5 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/m/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/m/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/m/Library/Android/sdk
    ✗ Android SDK file not found:
      /Users/m/Library/Android/sdk/build-tools/30.0.0/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[!] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4

**Comment by iapicca** [comment]
Hi @developerslearnit 
I see there's an open [issue](https://github.com/flutter/flutter/issues/58662) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
