### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /home/abhishek/flutter/bin/cache/dart-sdk/bin/pub.

### ISSUE THREAD

**Issue by abhishekdana1999** [flutter/flutter#60880]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. flutter pub get (taking long time)
2. flutter upgrade (thrown error)

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /home/abhishek/flutter/bin/cache/dart-sdk/bin/pub.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:466:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:484:35)
#4      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:281:34)
<asynchronous suspension>
#5      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:209:15)
#6      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:94:17)
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:125:11)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
```
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.126, on Linux, locale en_IN)
    • Flutter version 1.20.0-3.0.pre.126 at /home/abhishek/flutter
    • Framework revision 462b0ea76e (11 hours ago), 2020-07-05 14:58:01 -0400
    • Engine revision f8bbcc396b
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 8afe9875a6)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/abhishek/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /home/abhishek/Downloads/android-studio-ide-191.5900203-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/abhishek/Downloads/android-studio-ide-191.5900203-linux/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • CPH1909 (mobile) • EUHQSOYLY9V8KFMV • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3

**Comment by Abderrezak-douba** [comment]
any  solution i cannot find one

**Comment by bkonyi** [comment]
Closing as stale.
