### ISSUE TITLE
: Failed assertion: line 3839 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by vikas1993** [flutter/flutter#60890]
I have also removed navigation codes but still it showing same error

```
Performing hot reload...
Syncing files to device Android SDK built for x86 64...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#b70b6](dirty, state: NavigatorState#4e948(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3839 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/vikasaggarwal/Documents/flutterWorkshop/flutter_contact_app/lib/main.dart:14:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:3839:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4628:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4511:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 7 of 648 libraries in 690ms.
```

**Comment by TahaTesser** [comment]
Hi @vikas1993 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
