### ISSUE TITLE
[tool_crash] adb: error: listener 'tcp:61146' not found

### ISSUE THREAD

**Issue by LiveLikeCounter** [flutter/flutter#60893]
## Steps to Reproduce

Due this is a private project, I can't share the source. But I followed this steps.
1. Run VS Code
2. Make sure you run an Android Emulator
3. Run the app with `flutter run --verbose`

**Expected results:** The App running in the Android Emulator.

**Actual results:** Nothing happens. When I click the app on the Android Emulator, the error "<App> keeps stopping". On the iOS-Simulator it runs fine.

<details>
  <summary>Logs</summary>

## command

flutter run --verbose

## exception

ProcessException: ProcessException: Process exited abnormally:
adb: error: listener 'tcp:61146' not found
  Command: /Users/johan/Library/Android/sdk/platform-tools/adb -s emulator-5556 forward --remove tcp:61146

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:322:19)
#2      _rootRunUnary (dart:async/zone.dart:1192:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.5 at /Users/johan/flutter
    • Framework revision 8af6b2f038 (5 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/johan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

## flutter analyse

```
Analyzing app...                                                
   info • This function has a return type of 'Timestamp', but doesn't end with a return statement •
          lib/modules/shared/util/serialization.dart:24:20 • missing_return
```

</details>

**Comment by jonahwilliams** [comment]
Fixed by https://github.com/flutter/flutter/pull/57173

**Comment by LiveLikeCounter** [comment]
@jonahwilliams Thanks! When or in which version will the fix be available?
