### ISSUE TITLE
[fix-request] Search for sdkmanager under {ANDROID_SDK_ROOT}/cmdline-tools/tools/ also.

### ISSUE THREAD

**Issue by joe733** [flutter/flutter#60904]
## Steps to Reproduce
1. Install Android SDK using command line tools. `$ ./sdkmanager --sdk_root=ANDROID_HOME "platform-tools" "platforms;android-28"` where `ANDROID_HOME` was initially pointed to an empty directory `~/Android/Sdk`.
2. Copied the downloaded SDK to `~/Android/SDK` as well as the `tools` folder which is the extracted version of command line tools zip.
Here's what the `Sdk` folder looks like with [this directory structure](https://p.ip.fi/VPo0).
![image](https://user-images.githubusercontent.com/38415384/86598472-cbaa9d80-bfba-11ea-88c0-7c63e785720f.png)

The contents of `.zshrc`:
```bash
# >>> Android & Flutter >>>
export PATH="$PATH:/home/joe733/flutter/bin"
export PATH="$PATH:$HOME/flutter/flutter/.pub-cache/bin"

export ANDROID_SDK_ROOT="$PATH:/home/joe733/Android/Sdk"
export ANDROID_HOME=$ANDROID_SDK_ROOT


export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
# <<< Android & Flutter <<<
```

Platform API 28 info & Java version
```bash
joe733 in ~ at xpsl502x 
➜ ls Android/Sdk/platforms/android-28 
android.jar	       build.prop  framework.aidl  package.xml	   skins	      templates
android-stubs-src.jar  data	   optional	   sdk.properties  source.properties  uiautomator.jar

joe733 in ~ at xpsl502x 
➜ java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

3. Run `flutter doctor -v` and see the error.

## Logs
```bash
joe733 in ~ at xpsl502x 
➜ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0-3.0.pre.130, on Linux, locale en_IN)
    • Flutter version 1.20.0-3.0.pre.130 at /home/joe733/flutter
    • Framework revision a74310242e (18 hours ago), 2020-07-05 14:58:01 -0400
    • Engine revision f8bbcc396b
    • Dart version 2.9.0 (build 2.9.0-20.0.dev c190fc3a31)

[!] Android toolchain - develop for Android devices
    • Android SDK at /home/joe733/Android/Sdk/
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    • ANDROID_HOME =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • ANDROID_SDK_ROOT =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    ✗ No valid Android SDK platforms found in /home/joe733/Android/Sdk/platforms. Candidates were:
        - android-28
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • itel L5503 (mobile) • 054283103J164335 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

I've went through this: https://github.com/flutter/flutter/issues/25397 & https://github.com/flutter/flutter/issues/19805 but it did not help. I've tried setting the sdk using: `flutter configure --android-sdk /home/joe733/Android/Sdk`. What else should I try out?

**Comment by joe733** [comment]
Okay I solved it. Here's how.

## Downloading `platform-tools` & `build-tools`

- This time I tried: `./sdkmanager --sdk_root=ANDROID_HOME "platform-tools" "platforms;android-28" "build-tools;29.0.2"`. It downloaded the `build-tools` too.
- Now I arranged the `~/Android/Sdk` folder as follows (with some other sub-folders):
```dart
Android
└── Sdk
    ├── build-tools
    ├── emulator
    ├── licenses
    ├── patcher
    ├── platforms
    ├── platform-tools
    └── tools
        └── bin
            └── sdkmanager
```

- After that I ran `flutter doctor -v`:
```dart
joe733 in ~ at xpsl502x 
➜ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0-3.0.pre.130, on Linux, locale en_IN)
    • Flutter version 1.20.0-3.0.pre.130 at /home/joe733/flutter
    • Framework revision a74310242e (31 hours ago), 2020-07-05 14:58:01 -0400
    • Engine revision f8bbcc396b
    • Dart version 2.9.0 (build 2.9.0-20.0.dev c190fc3a31)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/joe733/Android/Sdk
    • Platform android-28, build-tools 29.0.2
    • ANDROID_HOME =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • ANDROID_SDK_ROOT =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

## Fixing Android Licences

- To fix licence issue, I executed `flutter doctor --android-licenses` and it lead me to this error:
```dart
joe733 in ~ at xpsl502x took 10s 
➜ flutter doctor --android-licenses
Warning: Could not create settings
java.lang.IllegalArgumentException
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:428)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:152)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:134)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:57)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Usage:
  sdkmanager [--uninstall] [<common args>] [--package_file=<file>] [<packages>...]
  sdkmanager --update [<common args>]
  sdkmanager --list [<common args>]
  sdkmanager --licenses [<common args>]
  sdkmanager --version

With --install (optional), installs or updates packages.
    By default, the listed packages are installed or (if already installed)
    updated to the latest version.
With --uninstall, uninstall the listed packages.

    <package> is a sdk-style path (e.g. "build-tools;23.0.0" or
             "platforms;android-23").
    <package-file> is a text file where each line is a sdk-style path
                   of a package to install or uninstall.
    Multiple --package_file arguments may be specified in combination
    with explicit paths.

With --update, all installed packages are updated to the latest version.

With --list, all installed and available packages are printed out.

With --licenses, show and offer the option to accept licenses for all
     available packages that have not already been accepted.

With --version, prints the current version of sdkmanager.

Common Arguments:
    --sdk_root=<sdkRootPath>: Use the specified SDK root instead of the SDK
                              containing this tool

    --channel=<channelId>: Include packages in channels up to <channelId>.
                           Common channels are:
                           0 (Stable), 1 (Beta), 2 (Dev), and 3 (Canary).

    --include_obsolete: With --list, show obsolete packages in the
                        package listing. With --update, update obsolete
                        packages as well as non-obsolete.

    --no_https: Force all connections to use http rather than https.

    --proxy=<http | socks>: Connect via a proxy of the given type.

    --proxy_host=<IP or DNS address>: IP or DNS address of the proxy to use.

    --proxy_port=<port #>: Proxy port to connect to.

    --verbose: Enable verbose output.

* If the env var REPO_OS_OVERRIDE is set to "windows",
  "macosx", or "linux", packages will be downloaded for that OS.
```

- The solution to which I found on [stackoverflow](https://stackoverflow.com/a/61176718/). Which asked me to wrap the `cmdline-tools` folder around `tools`. So the modified directory structure looked like this:
```dart
Android
└── Sdk
    ├── build-tools
    ├── cmdline-tools
    │    └── tools
    │        └── bin
    │            └── sdkmanager
    ├── emulator
    ├── licenses
    ├── patcher
    ├── platforms
    └── platform-tools
```
- But on running `flutter doctor --android-licenses` gave me yet another error.
```dart
joe733 in ~ at xpsl502x took 58s 
➜ flutter doctor --android-licenses
Android sdkmanager tool not found (/home/joe733/Android/Sdk/tools/bin/sdkmanager).
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
```
> Here's where I want to bring the developers' attention.
> - If the installation is via Android Studio none of these errors show-up (well... it won't if I do it the right way w/o Android Studio also...), even when there is only the `tools` directory and not the `cmdline-tools` directory.
> - But then `flutter doctor --android-licenses` looks for `sdkmanager` only at `/home/joe733/Android/Sdk/tools/bin/sdkmanager`.
> - *I think this command should search for `sdkmanager` under `{ANDROID_SDK_ROOT}/cmdline-tools/tools/` also.*

- So for now, as a workaround I created a symlink: `ln -s /home/joe733/Android/Sdk/cmdline-tools/tools /home/joe733/Android/Sdk/tools`.
- The final directory structure looks like this:
```dart
Android
└── Sdk
    ├── build-tools
    ├── cmdline-tools
    │    └── tools
    │        └── bin
    │            └── sdkmanager
    ├── emulator
    ├── licenses
    ├── patcher
    ├── platforms
    ├── platform-tools
    └── tools //(symlink to ~/Android/Sdk/cmdline-tools/tools)
```

- And yes on running `flutter doctor --android-licenses` in produces an expected warning.
```dart
joe733 in ~ at xpsl502x 
➜ flutter doctor --android-licenses                                                 
Warning: Observed package id 'tools' in inconsistent location '/home/joe733/Android/Sdk/cmdline-tools/tools' (Expected '/home/joe733/Android/Sdk/tools')
5 of 6 SDK package licenses not accepted. 100% Computing updates...
```

- Finally: `flutter doctor -v`
```dart
joe733 in ~ at xpsl502x took 27s 
➜ flutter doctor -v                                                                 
[✓] Flutter (Channel master, 1.20.0-3.0.pre.130, on Linux, locale en_IN)
    • Flutter version 1.20.0-3.0.pre.130 at /home/joe733/flutter
    • Framework revision a74310242e (32 hours ago), 2020-07-05 14:58:01 -0400
    • Engine revision f8bbcc396b
    • Dart version 2.9.0 (build 2.9.0-20.0.dev c190fc3a31)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/joe733/Android/Sdk
    • Platform android-28, build-tools 29.0.2
    • ANDROID_HOME =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • ANDROID_SDK_ROOT =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by joe733** [comment]
After installing build tools for Linux it again began complaining about Android SDK.
```dart
joe733 in Sdk/tools/bin at xpsl502x 
➜ flutter doctor -v 
[✓] Flutter (Channel master, 1.20.0-3.0.pre.130, on Linux, locale en_IN)
    • Flutter version 1.20.0-3.0.pre.130 at /home/joe733/flutter
    • Framework revision a74310242e (2 days ago), 2020-07-05 14:58:01 -0400
    • Engine revision f8bbcc396b
    • Dart version 2.9.0 (build 2.9.0-20.0.dev c190fc3a31)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/joe733/Android/Sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • ANDROID_SDK_ROOT =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    ✗ Android SDK file not found: /home/joe733/Android/Sdk/build-tools/28.0.3/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.
```

This time it's weirder, cause it's pointing at SDK and says it's not seen. 😳

**Comment by joe733** [comment]
I did it all over again. This time:

- Initial directory structure:
```dart
Android
└── Sdk
    ├── cmdline-tools
    │    └── tools
    │        └── bin
    │            └── sdkmanager
    └── tools //(symlink to ~/Android/Sdk/cmdline-tools/tools)
```
- Then I ran `./sdkmanager "platform-tools" "platforms;android-28" "build-tools;29.0.2"` from the symlink folder
```dart
joe733 in Sdk/tools/bin at xpsl502x 
➜ ./sdkmanager "platform-tools" "platforms;android-28" "build-tools;29.0.2"
Warning: Observed package id 'tools' in inconsistent location '/home/joe733/Android/Sdk/cmdline-tools/tools' (Expected '/home/joe733/Android/Sdk/tools')
Warning: Observed package id 'tools' in inconsistent location '/home/joe733/Android/Sdk/cmdline-tools/tools' (Expected '/home/joe733/Android/Sdk/tools')
License android-sdk-license:            ] 10% Computing updates...              
---------------------------------------
Terms and Conditions

...
...

January 16, 2019
---------------------------------------
Accept? (y/N): y
[=======================================] 100% Unzipping... platform-tools/systr
```

- Flutter doctor asks to fix licences:
```dart
joe733 in ~ at xpsl502x 
➜ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0-3.0.pre.130, on Linux, locale en_IN)
    • Flutter version 1.20.0-3.0.pre.130 at /home/joe733/flutter
    • Framework revision a74310242e (2 days ago), 2020-07-05 14:58:01 -0400
    • Engine revision f8bbcc396b
    • Dart version 2.9.0 (build 2.9.0-20.0.dev c190fc3a31)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/joe733/Android/Sdk
    • Platform android-28, build-tools 29.0.2
    • ANDROID_HOME =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • ANDROID_SDK_ROOT =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.

joe733 in ~ at xpsl502x took 14s 
➜ flutter doctor --android-licenses
Warning: Observed package id 'tools' in inconsistent location '/home/joe733/Android/Sdk/cmdline-tools/tools' (Expected '/home/joe733/Android/Sdk/tools')
Warning: Observed package id 'tools' in inconsistent location '/home/joe733/Android/Sdk/cmdline-tools/tools' (Expected '/home/joe733/Android/Sdk/tools')
5 of 6 SDK package licenses not accepted. 100% Computing updates...             
Review licenses that have not been accepted (y/N)? y

1/5: License android-googletv-license:
---------------------------------------

...
...

---------------------------------------
Accept? (y/N): y
All SDK package licenses accepted
```

- Finally:
```dart
joe733 in ~ at xpsl502x took 26s 
➜ flutter doctor -v                
[✓] Flutter (Channel master, 1.20.0-3.0.pre.130, on Linux, locale en_IN)
    • Flutter version 1.20.0-3.0.pre.130 at /home/joe733/flutter
    • Framework revision a74310242e (2 days ago), 2020-07-05 14:58:01 -0400
    • Engine revision f8bbcc396b
    • Dart version 2.9.0 (build 2.9.0-20.0.dev c190fc3a31)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/joe733/Android/Sdk
    • Platform android-28, build-tools 29.0.2
    • ANDROID_HOME =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • ANDROID_SDK_ROOT =
      /home/joe733/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/gam
      es:/home/joe733/flutter/bin:/home/joe733/flutter/flutter/.pub-cache/bin:/home/joe733/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.
```

**Comment by joe733** [comment]
I think the issue is with the command line `sdkmanager` itself rather than flutter, and the following output points to such a possibility:

> ```dart
> joe733 in Sdk/tools/bin at xpsl502x 
> ➜ ./sdkmanager "platform-tools" "platforms;android-28" "build-tools;29.0.2"
> Warning: Observed package id 'tools' in inconsistent location '/home/joe733/Android/Sdk/cmdline-tools/tools' (Expected '/home/joe733/Android/Sdk/tools')
> Warning: Observed package id 'tools' in inconsistent location '/home/joe733/Android/Sdk/cmdline-tools/tools' (Expected '/home/joe733/Android/Sdk/tools')
> License android-sdk-license:            ] 10% Computing updates...
> ```

At your convenience, if any of you folks got an advice regarding this, please do.

---
> I'm closing this tagged as <kbd>out-of-scope</kbd> issue.

**Comment by es3technologies** [comment]
If you have plenty of sure that your SDK directory is right and flutter doctor still with error, execute the command below.

**flutter config --android-sdk <YOUR_SDK_DIRECTORY>**

**Comment by joe733** [comment]
> If you have plenty of sure that your SDK directory is right and flutter doctor still with error, execute the command below.
> 
> **flutter config --android-sdk <YOUR_SDK_DIRECTORY>**

> I've went through this: #25397 & #19805 but it did not help. I've tried setting the sdk using: flutter configure --android-sdk /home/joe733/Android/Sdk. What else should I try out?

@es3technologies It's in my first comment just before labelling the issue. I've tried that too.

**Comment by phamconganh** [comment]
you just delete sdk and re-install with path-to-sdk/android_sdk/cmdline-tools/tools/bin with ANDROID_HOME=path-to-sdk/android_sdk

**Comment by joe733** [comment]
> I did it all over again. This time:

@phamconganh I did that too but the steps in my https://github.com/flutter/flutter/issues/60904#issuecomment-655245021 only worked.

**Comment by RakeshChowdhury** [comment]
I'm facing the same problem as well. The problem here is worse as im on windows and windows doesn't support symlinks. I think flutter sdk needs to update the commandline tools bin folder according to the new Android SDK updates. Although that would break support for old sdk.

> I think the issue is with the command line `sdkmanager` itself rather than flutter
Yes. It's actually the Android SDK responsible for breaking changes. According to the [official documentation](https://developer.android.com/studio/command-line) the commandline-tools directory is now 'android_sdk/cmdline-tools/version/bin'. While flutter is still using 'android_sdk/tools/bin'.

Changing this can break old sdk support. I'd suggest a custom configuration option to set path for command line bin folder.
Noticed the 'flutter config --android-sdk' sets the path to new sdk location. maybe its storing the config somewhere. I'm looking into manually editing the configuration files to change the tools folder path if that's possible :P

**Comment by RakeshChowdhury** [comment]
Turns out [it's fixed now](https://github.com/flutter/flutter/blob/a51dc3d913344f3073da12f4aae654c3299dec6c/packages/flutter_tools/lib/src/android/android_sdk.dart#L382). I had to upgrade flutter (`flutter upgrade`) and also replace the current commandline tools with [latest version](https://developer.android.com/studio#command-tools). Extracted the bin and lib into /sdk/cmdline-tools/latest/* and it works now.

```dart
Android
└── Sdk
    ├── build-tools
    ├── cmdline-tools
    │    └── latest
    │        └── lib
    │        └── bin
    │            └── sdkmanager
    ├── emulator
    ├── licenses
    ├── patcher
    ├── platforms
    └── platform-tools
```

I hope that helps anyone searching for the fix.
