### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = '/var/www/html/flutter/first_app/.packages' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by ranasl62** [flutter/flutter#60912]
## Command
```
flutter run --machine --target lib/main.dart -d emulator-5554 --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = '/var/www/html/flutter/first_app/.packages' (OS Error: Operation not permitted, errno = 1)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:213:19)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:706:17)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.5 at /home/ranasl62/development/flutter
    • Framework revision 8af6b2f038 (6 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/ranasl62/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/ranasl62/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[!] Android Studio (version 4.0)
    • Android Studio at /home/ranasl62/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3

**Comment by VladyslavBondarenko** [comment]
Fixed by https://github.com/flutter/flutter/pull/57077, not yet in stable
