### ISSUE TITLE
Android webview crash 'package:flutter/src/services/platform_views.dart': Failed assertion: line 320 pos 15: 'downTime != null': is not true.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#60921]
https://github.com/flutter/flutter/issues/35394#issuecomment-570881018

```
The following assertion was thrown while routing a pointer event:
'package:flutter/src/services/platform_views.dart': Failed assertion: line 320 pos 15: 'downTime != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new AndroidMotionEvent (package:flutter/src/services/platform_views.dart:320:15)
#3      _MotionEventsDispatcher.dispatchPointerEvent (package:flutter/src/rendering/platform_view.dart:633:51)
#4      _MotionEventsDispatcher.handlePointerEvent (package:flutter/src/rendering/platform_view.dart:577:5)
#5      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:511:7)
#6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
...
Event: PointerCancelEvent#df5cb(position: Offset(0.0, 0.0), localPosition: Offset(0.0, -348.3), pointer: 41, kind: touch, down: false, pressure: 0.0)
```

To reproduce:
```
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('First Route'),
        ),
        body: ListView(
          children: <Widget>[
            SizedBox(
              height: 500,
              child: WebView(
                initialUrl: 'https://flutter.io',
                javascriptMode: JavascriptMode.unrestricted,
                gestureRecognizers: {
                  Factory<PlatformViewVerticalGestureRecognizer>(
                    () => PlatformViewVerticalGestureRecognizer()
                      ..onUpdate = (_) {},
                  ),
                },
              ),
            ),
            DropdownButton(
              items: [
                DropdownMenuItem(
                  child: Text('first'),
                ),
                DropdownMenuItem(
                  child: Text('second'),
                )
              ],
              onChanged: (value) {},
            )
          ],
        ),
      ),
    );
  }
}

class PlatformViewVerticalGestureRecognizer
    extends VerticalDragGestureRecognizer {
  PlatformViewVerticalGestureRecognizer({PointerDeviceKind kind})
      : super(kind: kind);

  Offset _dragDistance = Offset.zero;

  @override
  void addPointer(PointerEvent event) {
    startTrackingPointer(event.pointer);
  }

  @override
  void handleEvent(PointerEvent event) {
    _dragDistance = _dragDistance + event.delta;
    if (event is PointerMoveEvent) {
      final double dy = _dragDistance.dy.abs();
      final double dx = _dragDistance.dx.abs();

      if (dy > dx && dy > kTouchSlop) {
        // vertical drag - accept
        resolve(GestureDisposition.accepted);
        _dragDistance = Offset.zero;
      } else if (dx > kTouchSlop && dx > dy) {
        resolve(GestureDisposition.accepted);
        // horizontal drag - stop tracking
        stopTrackingPointer(event.pointer);
        _dragDistance = Offset.zero;
      }
    }
  }

  @override
  String get debugDescription => 'horizontal drag (platform view)';

  @override
  void didStopTrackingLastPointer(int pointer) {}
}```

Reproduction steps:
1- Use 2 fingers to pinch on the webview portion, as if you're zooming in/out (zoom doesn't work on Android so it will not react).
2- tap on the dropdown button while you are still pinching with 2 fingers on the webview.

Tested on OnePlus 5T, Android 8.1

**Comment by cyanglaz** [comment]
cc @bparrishMines

**Comment by blasten** [comment]
@cyanglaz is this a new issue or old issue?

**Comment by blasten** [comment]
@cyanglaz is this a new issue? Do you know when it started happening?

**Comment by cyanglaz** [comment]
@blasten It was first reported around Jan 2020. Don't think it is related to the hybrid composition platform view tho.

**Comment by bparrishMines** [comment]
It looks like the crash is caused when a `PointerEvent` is converted to a `AndroidMotionEvent`. `downTime` isn't allowed to be `null` on the framework side even though we never use it for anything. With only a quick look at the framework, we may be able to solve this by just removing the assertion. I'll have to look in the engine to see how we use the value and or if there is a default value that we can use. 

For Reference: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_views.dart#L592

**Comment by blasten** [comment]
do we know why `downTimeMillis` is `null`? 

 FWIW, I wonder if this becomes a race condition: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_views.dart#L511

**Comment by blasten** [comment]
was this fixed recently @cyanglaz by the workaround in the framework?  I'm unable to reproduce it on `master`

**Comment by cyanglaz** [comment]
I haven't confirmed if the workaround in the framework fixed this tho. I wasn't able to reproduce this before the fix. I remember @bparrishMines had looked into this maybe he knows.

**Comment by johncerpa** [comment]
Still a problem :-1:

**Comment by pedromassangocode** [comment]
[first-triage-team]

I'm not sure if this is related but I'm getting null related issues while trying to reproduce this issue. To reproduce just try to zoom-in on the `webview` using the code above.

```console
E/flutter (18480): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
E/flutter (18480): #0      _AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure> (package:flutter/src/services/platform_views.dart:601:73)
E/flutter (18480): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter (18480): #2      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter (18480): #3      new List.from (dart:core-patch/array_patch.dart:38:29)
E/flutter (18480): #4      new List.of (dart:core-patch/array_patch.dart:68:17)
E/flutter (18480): #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
...

```

The thing is that it looks like I cannot reproduce the actual issue because of this null-related issue. Should I open a new issue?

<details><summary>Logs</summary>

```
E/flutter (18480): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
E/flutter (18480): #0      _AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure> (package:flutter/src/services/platform_views.dart:601:73)
E/flutter (18480): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter (18480): #2      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter (18480): #3      new List.from (dart:core-patch/array_patch.dart:38:29)
E/flutter (18480): #4      new List.of (dart:core-patch/array_patch.dart:68:17)
E/flutter (18480): #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
E/flutter (18480): #6      _AndroidMotionEventConverter.toAndroidMotionEvent (package:flutter/src/services/platform_views.dart:602:12)
E/flutter (18480): #7      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:864:31)
E/flutter (18480): #8      List.forEach (dart:core-patch/growable_array.dart:313:8)
E/flutter (18480): #9      _PlatformViewGestureRecognizer._flushPointerCache (package:flutter/src/rendering/platform_view.dart:560:35)
E/flutter (18480): #10     _PlatformViewGestureRecognizer.acceptGesture (package:flutter/src/rendering/platform_view.dart:542:5)
E/flutter (18480): #11     _CombiningGestureArenaMember.acceptGesture (package:flutter/src/gestures/team.dart:42:14)
E/flutter (18480): #12     GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:264:12)
E/flutter (18480): #13     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:223:9)
E/flutter (18480): #14     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53:12)
E/flutter (18480): #15     _CombiningGestureArenaMember._resolve (package:flutter/src/gestures/team.dart:79:15)
E/flutter (18480): #16     _CombiningGestureArenaEntry.resolve (package:flutter/src/gestures/team.dart:17:15)
E/flutter (18480): #17     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:261:13)
E/flutter (18480): #18     PlatformViewVerticalGestureRecognizer.handleEvent (package:triage/main.dart:73:9)
E/flutter (18480): #19     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (18480): #20     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (18480): #21     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (18480): #22     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (18480): #23     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (18480): #24     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (18480): #25     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (18480): #26     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (18480): #27     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (18480): #28     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (18480): #29     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (18480): #30     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (18480): #31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (18480): #32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (18480): #33     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (18480): #34     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (18480): 
I/chatty  (18480): uid=10511(com.nevercode.triage) 1.ui identical 35 lines
E/flutter (18480): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
E/flutter (18480): #0      _AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure> (package:flutter/src/services/platform_views.dart:601:73)
E/flutter (18480): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter (18480): #2      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter (18480): #3      new List.from (dart:core-patch/array_patch.dart:38:29)
E/flutter (18480): #4      new List.of (dart:core-patch/array_patch.dart:68:17)
E/flutter (18480): #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
E/flutter (18480): #6      _AndroidMotionEventConverter.toAndroidMotionEvent (package:flutter/src/services/platform_views.dart:602:12)
E/flutter (18480): #7      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:864:31)
E/flutter (18480): #8      List.forEach (dart:core-patch/growable_array.dart:313:8)
E/flutter (18480): #9      _PlatformViewGestureRecognizer._flushPointerCache (package:flutter/src/rendering/platform_view.dart:560:35)
E/flutter (18480): #10     _PlatformViewGestureRecognizer.acceptGesture (package:flutter/src/rendering/platform_view.dart:542:5)
E/flutter (18480): #11     _CombiningGestureArenaMember.acceptGesture (package:flutter/src/gestures/team.dart:42:14)
E/flutter (18480): #12     GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:264:12)
E/flutter (18480): #13     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:223:9)
E/flutter (18480): #14     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53:12)
E/flutter (18480): #15     _CombiningGestureArenaMember._resolve (package:flutter/src/gestures/team.dart:79:15)
E/flutter (18480): #16     _CombiningGestureArenaEntry.resolve (package:flutter/src/gestures/team.dart:17:15)
E/flutter (18480): #17     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:261:13)
E/flutter (18480): #18     PlatformViewVerticalGestureRecognizer.handleEvent (package:triage/main.dart:73:9)
E/flutter (18480): #19     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (18480): #20     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (18480): #21     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (18480): #22     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (18480): #23     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (18480): #24     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (18480): #25     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (18480): #26     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (18480): #27     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (18480): #28     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (18480): #29     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (18480): #30     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (18480): #31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (18480): #32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (18480): #33     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (18480): #34     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (18480): 
E/flutter (18480): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
E/flutter (18480): #0      _AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure> (package:flutter/src/services/platform_views.dart:601:73)
E/flutter (18480): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter (18480): #2      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter (18480): #3      new List.from (dart:core-patch/array_patch.dart:38:29)
E/flutter (18480): #4      new List.of (dart:core-patch/array_patch.dart:68:17)
E/flutter (18480): #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
E/flutter (18480): #6      _AndroidMotionEventConverter.toAndroidMotionEvent (package:flutter/src/services/platform_views.dart:602:12)
E/flutter (18480): #7      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:864:31)
E/flutter (18480): #8      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:535:26)
E/flutter (18480): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (18480): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (18480): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (18480): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (18480): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (18480): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (18480): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (18480): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (18480): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (18480): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (18480): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (18480): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (18480): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (18480): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (18480): #23     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (18480): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (18480): 
I/chatty  (18480): uid=10511(com.nevercode.triage) 1.ui identical 52 lines
E/flutter (18480): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
E/flutter (18480): #0      _AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure> (package:flutter/src/services/platform_views.dart:601:73)
E/flutter (18480): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
E/flutter (18480): #2      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
E/flutter (18480): #3      new List.from (dart:core-patch/array_patch.dart:38:29)
E/flutter (18480): #4      new List.of (dart:core-patch/array_patch.dart:68:17)
E/flutter (18480): #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
E/flutter (18480): #6      _AndroidMotionEventConverter.toAndroidMotionEvent (package:flutter/src/services/platform_views.dart:602:12)
E/flutter (18480): #7      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:864:31)
E/flutter (18480): #8      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:535:26)
E/flutter (18480): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (18480): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (18480): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (18480): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (18480): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (18480): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (18480): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (18480): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (18480): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (18480): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (18480): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (18480): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (18480): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (18480): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (18480): #23     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (18480): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (18480): 
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s
E/chromium(18480): [ERROR:page_load_metrics_update_dispatcher.cc(169)] Invalid first_paint 7.302 s for first_image_paint 7.202 s

```
</details>

<details><summary>flutter doctor</summary>

```
/Users/pedromassango/dev/SDKs/flutter_stable/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Redmi 5 Plus (mobile)      • 0258ff700005  • android-arm64 • Android 8.1.0 (API 27)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64   • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by hunter-kaan** [comment]
Still a problem 👎
Flutter 2.2.1, with three finger gesture

```
E/flutter (29838): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (29838): #0      _AndroidMotionEventConverter.toAndroidMotionEvent (package:flutter/src/services/platform_views.dart:595:31)
E/flutter (29838): #1      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:868:31)
E/flutter (29838): #2      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:564:26)
E/flutter (29838): #3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter (29838): #4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter (29838): #5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (29838): #6      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter (29838): #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter (29838): #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter (29838): #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (29838): #10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter (29838): #11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (29838): #12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (29838): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (29838): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (29838): #15     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (29838): #16     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (29838): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (29838): #18     _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter (29838): #19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter (29838): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

<details>
  <summary>doctor -v</summary>

```
[✓] Flutter (Channel unknown, 2.2.1, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-RU)
    • Flutter version 2.2.1 at /Users/_/fvm/versions/2.2.1
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/_/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] Connected device (2 available)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 91.0.4472.106

! Doctor found issues in 1 category.

```
</details>

**Comment by cccodaisy** [comment]
I got same problem... 
Flutter 2.2.0-10.3
The Issue started happen when I using palm swipe to capture.
Is that same issue?

E/flutter (25432): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (25432): #0      _AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure> (package:flutter/src/services/platform_views.dart:600:73)
E/flutter (25432): #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
E/flutter (25432): #2      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
E/flutter (25432): #3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter (25432): #4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter (25432): #5      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter (25432): #6      ListIterable.toList (dart:_internal/iterable.dart:212:44)
E/flutter (25432): #7      _AndroidMotionEventConverter.toAndroidMotionEvent (package:flutter/src/services/platform_views.dart:601:12)
E/flutter (25432): #8      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:868:31)
E/flutter (25432): #9      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:564:26)
E/flutter (25432): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter (25432): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter (25432): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (25432): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter (25432): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter (25432): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter (25432): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter (25432): #17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter (25432): #18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter (25432): #19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter (25432): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter (25432): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter (25432): #22     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (25432): #23     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (25432): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (25432): #25     _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter (25432): #26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter (25432): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)

**Comment by shivangguptaa** [comment]
still a problem. I am using flutter_inappwebview. Please fix this.

**Comment by DCrow** [comment]
Also getting this error when using PlatformViews for Android.

**Comment by huynhnhutlam** [comment]
I also have the same problem when touching three fingers on the screen.
I use flutter 2.2.3.

**Comment by liasica** [comment]
> I also have the same problem when touching three fingers on the screen.
> I use flutter 2.2.3.

ME TOO

Please fix it.

**Comment by blasten** [comment]
is anyone still able to reproduce this issue on the master channel?
