### ISSUE TITLE
Draggable's feedback cannot access InheritedWidgets because it doesn't share the same BuildContext as Draggable

### ISSUE THREAD

**Issue by HeliumEnd** [flutter/flutter#60941]
Here is a code example of the problem:

https://dartpad.dev/9b23c8bdfbe53e41bbeba2f055f88eff

If you replace the line with `Text("blah")` with `DataMessage()` then `Draggable` works. The problem is a widget that uses a `InheritedWidget.dependOnInheritedWidgetOfExactType` will return null for the `feedback` case. Nowhere in the documentation says this should be the case.

I expected `InheritedWidget.dependOnInheritedWidgetOfExactType` to not return `null` as I thought it was part of the widget tree. Is this not the case?

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: DataContext(
        message: 'Flutter is the best',
        child: SimplePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class DataContext extends InheritedWidget {
  final String message;

  DataContext({Key key, Widget child, this.message})
      : super(key: key, child: child);

  static DataContext of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<DataContext>();
  }

  @override
  bool updateShouldNotify(DataContext oldWidget) =>
      message != oldWidget.message;
}

class DataMessage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final dataCtx = DataContext.of(context);

    return Text(dataCtx.message);
  }
}

class SimplePage extends StatelessWidget {
  final String title;

  SimplePage({Key key, this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final dataCtx = DataContext.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(this.title),
      ),
      body: Center(
          child: Draggable<String>(
        data: dataCtx.message,
        child: DataMessage(),
        feedback: DataMessage(), // Text("blah")
      )),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (3 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!

``` 

</details>

**Comment by EriKWDev** [comment]
Still in latest dev

```
Flutter 1.24.0-10.2.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (8 days ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)
```

Is this expected behaviour or a bug?

I also tried wrapping the feedback widget in a builder to get a fresh new context but I still can't access data from InheritedWidget

**Comment by jhoogstraat** [comment]
Behavior is still the same.
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (4 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by maheshmnj** [comment]
Reproduces as of stable 3.3 and master 3.7

```
Restarted application in 794ms.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building DataMessage(dirty):
Null check operator used on a null value

The relevant error-causing widget was:
  DataMessage DataMessage:file:///Users/mahesh/Desktop/flutter_issue/lib/main.dart:77:25

When the exception was thrown, this was the stack:
#0      DataMessage.build (package:flutter_issue/main.dart:51:24)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (32 frames)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#38     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#40     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#41     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#46     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#47     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#48     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#49     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#50     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#51     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#52     _invoke (dart:ui/hooks.dart:145:13)
#53     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#54     _drawFrame (dart:ui/hooks.dart:112:31)

════════════════════════════════════════════════════════════════════════════════════════════════════


```

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: DataContext(
        message: 'Flutter is the best',
        child: const SimplePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class DataContext extends InheritedWidget {
   String message;

  DataContext({Key? key, required Widget child, required this.message})
      : super(key: key, child: child);

  static DataContext? of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<DataContext>();
  }

  // set message 
  void setMessage(String message) {
    this.message = message;
  }

  @override
  bool updateShouldNotify(DataContext oldWidget) =>
      message != oldWidget.message;
}

class DataMessage extends StatelessWidget {
  const DataMessage({super.key});

  @override
  Widget build(BuildContext context) {
    final dataCtx = DataContext.of(context);

    return Text(dataCtx!.message);
  }
}

class SimplePage extends StatelessWidget {
  final String title;

  const SimplePage({Key? key,required this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final dataCtx = DataContext.of(context);

    return Scaffold(
      floatingActionButton:  FloatingActionButton(
        onPressed: () {
          dataCtx!.setMessage("Flutter is the best");
        },
        child: const Icon(Icons.add),
      ),
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
          child: Draggable<String>(
        data: dataCtx!.message,
        feedback: const DataMessage(),
        child: const DataMessage()
      )),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by victorsanni** [comment]
Still a valid issue. As @huycozy pointed out in #136723, this is because `Draggable` and `Draggable.feedback` don't share the same `BuildContext context`.

**Comment by Solido** [comment]
Still a very valid issue. It happen in nearly all cases that use a proper approach of design by theme as they are setup at the app root.

This make high level like https://www.fluttermix.com/ kinda impotent with D&D.
