### ISSUE TITLE
Unhandled exceptions are not surfaced in physical iOS devices

### ISSUE THREAD

**Issue by HelloJunWei** [flutter/flutter#61056]
If I have a bug at async function (like **bad element** or something), it won't display error message on real iphone device. But it will display on iphone simulator.

### Here is my situation.

I create a new flutter project.

```
flutter create flutter_playground
```

and I add a bug code on ***_incrementCounter*** function.

```
class _MyHomePageState extends State<MyHomePage> {
    int _counter = 0;
  
    void _incrementCounter() {
      List list = ['foo', 'bar'];
      String foo = list.firstWhere((value) => value == 'oo');
      print(foo);
      
      // Error:   Bad state: No element
  
      setState(() {
       // This call to setState tells the Flutter framework that something has
       // changed in this State, which causes it to rerun the build method below
       // so that the display can reflect the updated values. If we changed
       // _counter without calling setState(), then the build method would not be
       // called again, and so nothing would appear to happen.
       _counter++;
     });
    }
```

It will show error message on both deivces. (iphone simulator and real iphone device)
```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following StateError was thrown while handling a gesture:
flutter: Bad state: No element
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ListMixin.firstWhere (dart:collection/list.dart:150:5)
flutter: #1      _MyHomePageState._incrementCounter (package:flutter_playground/main.dart:57:23)
flutter: #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
flutter: #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
flutter: #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
flutter: #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
flutter: #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
flutter: #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
flutter: #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #17     _invoke1 (dart:ui/hooks.dart:275:10)
flutter: #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: Handler: "onTap"
flutter: Recognizer:
flutter:   TapGestureRecognizer#20070
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

However, when I add an **async** function in my code.

```
class _MyHomePageState extends State<MyHomePage> {
    int _counter = 0;
  
    void _incrementCounter() async{
      List list = ['foo', 'bar'];
      String foo = list.firstWhere((value) => value == 'oo');
      print(foo);
      
      // Error:   Bad state: No element
  
      setState(() {
       // This call to setState tells the Flutter framework that something has
       // changed in this State, which causes it to rerun the build method below
       // so that the display can reflect the updated values. If we changed
       // _counter without calling setState(), then the build method would not be
       // called again, and so nothing would appear to happen.
       _counter++;
     });
    }

```

It will **only** display error message on iphone simulator.

error message on  iphone simulator
<img width="1674" alt="截圖 2020-07-08 上午9 26 50" src="https://user-images.githubusercontent.com/18310281/86865454-99f01e80-c101-11ea-84c9-f1c9be25bc8f.png">

**real iphone device isn't display any error message, no matter how many times I click the button.**
<img width="1673" alt="截圖 2020-07-08 上午9 28 54" src="https://user-images.githubusercontent.com/18310281/86865576-d6237f00-c101-11ea-8f52-f83d83eb2031.png">

**additional**: It will display error message on both  android simluator (android 10) and real android device (android 10).

**Comment by HelloJunWei** [comment]
## flutter doctor -v 
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.4 19E287, locale zh-Hant-TW)
    • Flutter version 1.17.5 at /Users/aimm/Desktop/bitbucket/flutter
    • Framework revision 8af6b2f038 (7 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/aimm/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available
```

**Comment by jonahwilliams** [comment]
This is a side effect of using the VM service for logs on phyiscal iOS devices, due to the loss of logging APIs in iOS13. In the second case, we're missing the exception because it is going through the isolate unhandled exception handler. Ideally it would also go to the stderr stream in the VM service

**Comment by HelloJunWei** [comment]
**additional**: If I build my code by Xcode, it will display error message on real iphone device.

![截圖 2020-07-08 上午9 48 25](https://user-images.githubusercontent.com/18310281/86866363-644c3500-c103-11ea-92aa-fd0bc703068f.png)

**Comment by TahaTesser** [comment]
I can see exceptions are thrown on a physical device too

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    List list = ['foo', 'bar'];
    String foo = list.firstWhere((value) => value == 'oo');
    print(foo);

    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details> 

<details> 
<summary>physical logs</summary> 

```bash
[38;5;248mLaunching lib/main.dart on Taha’s iPhone in debug mode...[39;49m
 package:master_flutter/main.dart
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Xcode build done.                                           15.7s
(lldb) 2020-10-22 19:39:20.448405+0530 Runner[1392:355199] flutter: Observatory server failed to start after 1 tries
flutter: Observatory server failed to start after 2 tries
flutter: Observatory server failed to start after 3 tries
flutter: Falling back to automatic port selection
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Connecting to VM Service at ws://127.0.0.1:50641/ZWJimW-Ye0w=/ws

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
[38;5;244mThe following StateError was thrown while handling a gesture:[39;49m
Bad state: No element

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)[39;49m
[38;5;248m#1      _MyHomePageState._incrementCounter[39;49m
 package:master_flutter/main.dart
[38;5;244m#2      _InkResponseState._handleTap[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244m#3      _InkResponseState.build.<anonymous closure>[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244m#4      GestureRecognizer.invokeCallback[39;49m
 package:flutter/…/gestures/recognizer.dart
[38;5;244m...[39;49m
[38;5;244mHandler: "onTap"[39;49m
[38;5;244mRecognizer: TapGestureRecognizer#b5827[39;49m
    [38;5;244mdebugOwner: GestureDetector[39;49m
    [38;5;244mstate: ready[39;49m
    [38;5;244mwon arena[39;49m
    [38;5;244mfinalPosition: Offset(367.5, 823.0)[39;49m
    [38;5;244mfinalLocalPosition: Offset(25.5, 17.0)[39;49m
    [38;5;244mbutton: 1[39;49m
    [38;5;244msent tap down[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

```

</details> 

<details> 
<summary>logs</summary> 

```bash
[38;5;248mLaunching lib/main.dart on iPhone 12 in debug mode...[39;49m
 package:master_flutter/main.dart
Xcode build done.                                           24.6s
Connecting to VM Service at ws://127.0.0.1:50413/UECxR2M2S6Q=/ws

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
[38;5;244mThe following StateError was thrown while handling a gesture:[39;49m
Bad state: No element

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)[39;49m
[38;5;248m#1      _MyHomePageState._incrementCounter[39;49m
 package:master_flutter/main.dart
[38;5;244m#2      _InkResponseState._handleTap[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244m#3      _InkResponseState.build.<anonymous closure>[39;49m
 package:flutter/…/material/ink_well.dart
[38;5;244m#4      GestureRecognizer.invokeCallback[39;49m
 package:flutter/…/gestures/recognizer.dart
[38;5;244m...[39;49m
[38;5;244mHandler: "onTap"[39;49m
[38;5;244mRecognizer: TapGestureRecognizer#fea71[39;49m
    [38;5;244mdebugOwner: GestureDetector[39;49m
    [38;5;244mstate: ready[39;49m
    [38;5;244mwon arena[39;49m
    [38;5;244mfinalPosition: Offset(369.3, 762.3)[39;49m
    [38;5;244mfinalLocalPosition: Offset(28.0, 28.0)[39;49m
    [38;5;244mbutton: 1[39;49m
    [38;5;244msent tap down[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
Bad state: No element
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.24.0-2.0.pre.111, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-2.0.pre.111 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision fe189baf34 (11 hours ago), 2020-10-21 22:25:53 -0400
    • Engine revision f459a86610
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.1
    • iPhone 12 (mobile)     • 722C6A4C-3FCA-4FC6-9D30-9702A0E784B8 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 86.0.4240.80

• No issues found!

```

</details> 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by shinewanna** [comment]
This what happen is u r assigning the list and search from the list at one time.
so the search function is conflict.
u can use like that
`
     List list = ['foo', 'bar'];  
     String foo;
     for (var each in list) {
              if (each =='oo') {
                foo = each;
                break;
              }
      }
      print(foo);
`
