### ISSUE TITLE
ScrollableState asserts

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6108]
```
15:36:23.600: I/flutter : ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
15:36:23.602: I/flutter : The following assertion was thrown during performLayout():
15:36:23.606: I/flutter : Build scheduled during frame.
15:36:23.609: I/flutter : While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild
15:36:23.611: I/flutter : the widget tree. This might be because setState() was called from a layout or paint callback. If a
15:36:23.613: I/flutter : change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a
15:36:23.616: I/flutter : change for the subsequent frame instead results in an interface that lags behind by one frame. If
15:36:23.618: I/flutter : this was done to make your build dependent on a size measured at layout time, consider using a
15:36:23.620: I/flutter : LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one
15:36:23.624: I/flutter : frame delay is the desired effect, for example because this is an animation, consider scheduling the
15:36:23.627: I/flutter : frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an
15:36:23.630: I/flutter : AnimationController to trigger the animation.
15:36:23.633: I/flutter :
15:36:23.636: I/flutter : When the exception was thrown, this was the stack:
15:36:23.646: I/flutter : #0      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:199:9)
15:36:23.649: I/flutter : #2      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:197:12)
15:36:23.652: I/flutter : #3      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:1553:23)
15:36:23.656: I/flutter : #4      BuildableElement.markNeedsBuild (package:flutter/src/widgets/framework.dart:2528:11)
15:36:23.658: I/flutter : #5      State.setState (package:flutter/src/widgets/framework.dart:852:14)
15:36:23.661: I/flutter : #6      ScrollableState._setScrollOffset (package:flutter/src/widgets/scrollable.dart:438:5)
15:36:23.665: I/flutter : #7      ScrollableState.scrollTo (package:flutter/src/widgets/scrollable.dart:487:7)
15:36:23.668: I/flutter : #8      ScrollableState.didUpdateScrollBehavior (package:flutter/src/widgets/scrollable.dart:524:5)
15:36:23.671: I/flutter : #9      ScrollableState.handleExtentsChanged (package:flutter/src/widgets/scrollable.dart:539:5)
15:36:23.674: I/flutter : #10     ScrollableViewport._buildViewport.<anonymous closure> (package:flutter/src/widgets/scrollable.dart:995:15)
15:36:23.677: I/flutter : #11     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:289:46)
15:36:23.680: I/flutter : #12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1448:21)
15:36:23.683: I/flutter : #13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:897:18)
15:36:23.686: I/flutter : #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:207:19)
15:36:23.689: I/flutter : #15     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:297:23)
15:36:23.692: I/flutter : #16     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:152:5)
15:36:23.695: I/flutter : #17     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:608:15)
15:36:23.698: I/flutter : #18     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:543:9)
15:36:23.701: I/flutter : #19     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:48)
15:36:23.704: I/flutter : (elided one frame from class _AssertionError)
```

**Comment by Hixie** [comment]
same as #5846.
