### ISSUE TITLE
Either the assertion indicates an error in the framework itself, or we should provide substantially more information

### ISSUE THREAD

**Issue by eldarj** [flutter/flutter#61143]
Reporting this

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#414a7](dirty, state: NavigatorState#de1f2(tickers: tracking 3 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3803 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///home/myapp/flutter/lib/main.dart:20:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:3803:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 705 libraries in 413ms.
```

**Comment by darshankawar** [comment]
Hi @eldarj,
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample that shows this issue.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
