### ISSUE TITLE
Flutter does not start / find files - after upgrade from [ 1.19.0-4.0.pre.95 ] to [ 1.20.0-3.0.pre.174 ]

### ISSUE THREAD

**Issue by CAoTx** [flutter/flutter#61148]
## Steps to Reproduce

Running Flutter on Ubuntu 18.04, which is also the target.
I upgraded from 1.19.0-4.0.pre.95 to 1.20.0-3.0.pre.174 via flutter upgrade, installed the two new remaining packages: 
1. apt install pkg-config
2. apt install libgtk-3-dev

Now it always gives me this error or a similar.
I tried already:
1. Flutter clean 
2. Comment out imports from the pubspec file

on VSC i got two errors, both c++ import related: 
1. Include error in generated_plugin_registrant.cc: #include "generated_plugin_registrant.h"
2. cannot open source file \"gio/gio.h\" (dependency of \"generated_plugin_registrant.h\")

with 
flutter run -d Linux -v 
I get: 

## Logs

```
[ +101 ms] executing: [/home/sbey/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 80b5ee4e7c54875ccc70ca7c1b5510b7399b4fc2
[        ] executing: [/home/sbey/flutter/] git tag --contains HEAD
[ +159 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/home/sbey/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +12 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.20.0-2.0.pre-174-g80b5ee4e7c
[   +9 ms] executing: [/home/sbey/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/sbey/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +60 ms] executing: [/home/sbey/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +48 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] executing: /home/sbey/Android/Sdk/platform-tools/adb devices -l
[  +33 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +119 ms] Found plugin video_player at /home/sbey/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.11+2/
[   +6 ms] Found plugin video_player_web at /home/sbey/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.3+2/
[  +59 ms] Found plugin video_player at /home/sbey/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.11+2/
[   +1 ms] Found plugin video_player_web at /home/sbey/flutter/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.3+2/
[  +49 ms] Generating
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +71 ms] Starting incremental build...
[   +2 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +6 ms] Launching lib/main.dart on Linux in debug mode...
[   +5 ms] /home/sbey/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/sbey/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/sbey/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tools.QNZCBQ/flutter_tool.CRFEMF/app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +17 ms] Building Linux application...
[  +11 ms] <- compile package:flutterReference/main.dart
[   +4 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux
[ +158 ms] -- The CXX compiler identification is Clang 6.0.0
[   +5 ms] -- Check for working CXX compiler: /usr/bin/clang++
[ +126 ms] -- Check for working CXX compiler: /usr/bin/clang++ - works
[   +1 ms] -- Detecting CXX compiler ABI info
[ +122 ms] -- Detecting CXX compiler ABI info - done
[  +12 ms] -- Detecting CXX compile features
[        ] -- Detecting CXX compile features - done
[   +3 ms] -- Configuring done
[   +5 ms] -- Generating done
[        ] -- Build files have been written to: /home/sbey/Projects/bachelorresearch/Flutter/flutterReference/build/linux/debug
[  +10 ms] executing: ninja -C build/linux/debug install
[   +6 ms] ninja: Entering directory `build/linux/debug'
[+12408 ms] [1/15] Generating /home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/libflutter_linux_glfw.so,
flutter_export.h, flutter_glfw.h, flutter_messenger.h, flutter_plugin_registrar.h,
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc,
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc,
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc,
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc,
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc, _phony_
[   +3 ms] [ +123 ms] executing: [/home/sbey/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +28 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 80b5ee4e7c54875ccc70ca7c1b5510b7399b4fc2
[        ] [        ] executing: [/home/sbey/flutter/] git tag --contains HEAD
[        ] [ +184 ms] Exit code 0 from: git tag --contains HEAD
[        ] [   +2 ms] executing: [/home/sbey/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] [  +12 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] [        ] 1.20.0-2.0.pre-174-g80b5ee4e7c
[        ] [   +8 ms] executing: [/home/sbey/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/sbey/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +49 ms] executing: [/home/sbey/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +7 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +98 ms] Initializing file store
[        ] [  +21 ms] Skipping target: gen_localizations
[        ] [   +2 ms] unpack_linux: Starting due to {}
[        ] [ +120 ms] unpack_linux: Complete
[        ] [  +26 ms] kernel_snapshot: Starting due to {}
[        ] [  +38 ms] /home/sbey/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/sbey/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/sbey/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --packages /home/sbey/Projects/bachelorresearch/Flutter/flutterReference/.packages --output-dill
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/.dart_tool/flutter_build/d07d7e574c9ddfb5610f72276fc3f6be/app.dill --depfile
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/.dart_tool/flutter_build/d07d7e574c9ddfb5610f72276fc3f6be/kernel_snapshot.d
package:flutterReference/main.dart
[   +2 ms] [+9672 ms] kernel_snapshot: Complete
[        ] [ +600 ms] debug_bundle_linux_assets: Starting due to {}
[        ] [ +111 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[        ] [  +10 ms] debug_bundle_linux_assets: Complete
[        ] [ +661 ms] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +7 ms] build succeeded.
[        ] [   +7 ms] "flutter assemble" took 11,412ms.
[        ] [   +4 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[   +5 ms] [2/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o
[        ] FAILED: flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o 
[        ] /usr/bin/clang++
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral -g   -Wall -Werror -MD -MT
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o -MF
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o.d -o
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc
[   +2 ms] clang: error: no such file or directory:
'/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc'
[   +1 ms] clang: error: no input files
[        ] [3/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o
[        ] FAILED: flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o 
[        ] /usr/bin/clang++
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral -g -fPIC -fvisibility=hidden   -Wall -Werror -MD -MT
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o -MF
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o.d -o
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc
[   +1 ms] clang: error: no such file or directory:
'/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc'
[        ] clang: error: no input files
[        ] [4/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o
[        ] FAILED: flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o 
[        ] /usr/bin/clang++
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral -g -fPIC -fvisibility=hidden   -Wall -Werror -MD -MT
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o -MF
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o.d -o
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc
[   +1 ms] clang: error: no such file or directory:
'/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc'
[        ] clang: error: no input files
[        ] [5/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc.o
[        ] FAILED: flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc.o 
[        ] /usr/bin/clang++
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral -g -fPIC -fvisibility=hidden   -Wall -Werror -MD -MT
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc.o -MF
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc.o.d -o
flutter/CMakeFiles/flutter_wrapper_plugin.dir/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc
[   +1 ms] clang: error: no such file or directory:
'/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc'
[        ] clang: error: no input files
[        ] [6/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc.o
[        ] FAILED: flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc.o 
[        ] /usr/bin/clang++
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral -g   -Wall -Werror -MD -MT
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc.o -MF
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc.o.d -o
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc
[   +1 ms] clang: error: no such file or directory:
'/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_engine.cc'
[        ] clang: error: no input files
[        ] [7/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc.o
[        ] FAILED: flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc.o 
[        ] /usr/bin/clang++
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral -g   -Wall -Werror -MD -MT
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc.o -MF
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc.o.d -o
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc
[   +1 ms] clang: error: no such file or directory:
'/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc'
[        ] clang: error: no input files
[        ] [8/15] Building CXX object flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o
[        ] FAILED: flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o 
[        ] /usr/bin/clang++
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral -g   -Wall -Werror -MD -MT
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o -MF
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o.d -o
flutter/CMakeFiles/flutter_wrapper_app.dir/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc
[   +1 ms] clang: error: no such file or directory:
'/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc'
[        ] clang: error: no input files
[  +16 ms] [9/15] Building CXX object CMakeFiles/flutterReference.dir/window_configuration.cc.o
[   +5 ms] [10/15] Building CXX object CMakeFiles/flutterReference.dir/flutter/generated_plugin_registrant.cc.o
[        ] FAILED: CMakeFiles/flutterReference.dir/flutter/generated_plugin_registrant.cc.o 
[        ] /usr/bin/clang++   -I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include -g   -Wall -Werror -MD -MT
CMakeFiles/flutterReference.dir/flutter/generated_plugin_registrant.cc.o -MF
CMakeFiles/flutterReference.dir/flutter/generated_plugin_registrant.cc.o.d -o
CMakeFiles/flutterReference.dir/flutter/generated_plugin_registrant.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/generated_plugin_registrant.cc
[        ] In file included from /home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/generated_plugin_registrant.cc:5:
[        ] In file included from /home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/generated_plugin_registrant.h:8:
[        ] In file included from
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/flutter_linux/flutter_linux.h:10:
[        ] /home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h:12:10:
fatal error: 'gio/gio.h' file not found
[        ] #include <gio/gio.h>
[        ]          ^~~~~~~~~~~
[        ] 1 error generated.
[ +148 ms] [11/15] Building CXX object CMakeFiles/flutterReference.dir/main.cc.o
[        ] FAILED: CMakeFiles/flutterReference.dir/main.cc.o 
[        ] /usr/bin/clang++   -I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral
-I/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include -g   -Wall -Werror -MD -MT
CMakeFiles/flutterReference.dir/main.cc.o -MF CMakeFiles/flutterReference.dir/main.cc.o.d -o CMakeFiles/flutterReference.dir/main.cc.o -c
/home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/main.cc
[        ] /home/sbey/Projects/bachelorresearch/Flutter/flutterReference/linux/main.cc:1:10: fatal error: 'flutter/flutter_engine.h' file not found
[        ] #include <flutter/flutter_engine.h>
[        ]          ^~~~~~~~~~~~~~~~~~~~~~~~~~
[        ] 1 error generated.
[        ] ninja: build stopped: subcommand failed.
[   +9 ms] Building Linux application... (completed in 13.1s)
[        ] Exception: Build process failed
[   +2 ms] "flutter run" took 13,532ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +6 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.174, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by CAoTx** [comment]
I downgraded to the prior version with: 
- flutter version 2f7a59a

Now works again.

**Comment by gspencergoog** [comment]
@CAoTx have you tried regenerating the generated code in the `linux/` directory in your flutter project?  You can do that by moving `linux` out of the way (and you can delete it later if it works), and then running `flutter create .` in your project directory with the updated Flutter.

**Comment by CAoTx** [comment]
> @CAoTx have you tried regenerating the generated code in the `linux/` directory in your flutter project? You can do that by moving `linux` out of the way (and you can delete it later if it works), and then running `flutter create .` in your project directory with the updated Flutter.

This works, thanks! 

What i did exactly, being in project directory: 
1. `flutter upgrade`
2. `flutter clean`
3. `mv linux ~/Desktop` (move it out of the way)
4. `flutter create .`

`flutter run -d Linux` works now
