### ISSUE TITLE
[video_player] Plugin provided example doesn't work (throws Unhandled Exception)

### ISSUE THREAD

**Issue by llucax** [flutter/flutter#61189]
I'm trying to just run the example in https://github.com/flutter/plugins/tree/master/packages/video_player/video_player/example but I get this error:

<details>
<summary><code>E/flutter (32671): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null)</code></summary>
<pre><code>
E/flutter (32671): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null)
E/flutter (32671): #0      VideoPlayerApi.initialize (package:video_player_platform_interface/messages.dart:220:7)
E/flutter (32671): <asynchronous suspension>
E/flutter (32671): #1      MethodChannelVideoPlayer.init (package:video_player_platform_interface/method_channel_video_player.dart:20:17)
E/flutter (32671): #2      _videoPlayerPlatform (package:video_player/video_player.dart:23:5)
E/flutter (32671): #3      _videoPlayerPlatform (package:video_player/video_player.dart)
E/flutter (32671): #4      VideoPlayerController.initialize (package:video_player/video_player.dart:265:24)
E/flutter (32671): #5      _BumbleBeeRemoteVideoState.initState (package:video_player_example/main.dart:229:17)
E/flutter (32671): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4649:58)
E/flutter (32671): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter (32671): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
E/flutter (32671): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
E/flutter (32671): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (32671): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (32671): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
E/flutter (32671): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter (32671): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
E/flutter (32671): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
E/flutter (32671): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:14)
E/flutter (32671): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
E/flutter (32671): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
E/flutter (32671): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5839:14)
E/flutter (32671): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
E/flutter (32671): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
E/flutter (32671): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (32671): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (32671): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
E/flutter (32671): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter (32671): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
E/flutter (32671): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
E/flutter (32671): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (32671): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (32671): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
E/flutter (32671): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter (32671): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
E/flutter (32671): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
E/flutter (32671): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (32671): #35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
E/flutter (32671): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (32671): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
E/flutter (32671): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter (32671): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4485:5)
E/flutter (32671): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
E/flutter (32671): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
E/flutter (32671): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (32671): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (32671): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4490:5)
E/flutter (32671): #45     ComponentElement.mount
</code></pre>
</details>

This happens for every tab I try. I also tried using the latest tag to the time of writing ([`video_player-v0.10.11+2`](
https://github.com/flutter/plugins/tree/video_player-v0.10.11%2B2/packages/video_player/video_player/example)) and I still get the same error.

<details>
<summary>In case it helps to diagnose the problem here is the <code>flutter doctor -v</code> output</summary>
<pre><code>
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_IE.UTF-8)
    • Flutter version 1.19.0-4.3.pre at /home/luca/software/flutter
    • Framework revision 8fe7655ed2 (8 days ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/luca/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /home/luca/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Android Studio (version 4.0)
    • Android Studio at /home/luca/software/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • MotoE2 4G LTE • TA36401C3Z • android-arm    • Android 6.0 (API 23)
    • Web Server    • web-server • web-javascript • Flutter Tools
    • Chrome        • chrome     • web-javascript • Chromium 83.0.4103.116 built on Debian bullseye/sid, running on Debian bullseye/sid

• No issues found!
</code></pre>
<details>

Let me know if this is expected or if you need any other information.

**Comment by llucax** [comment]
Steps I did to end up with this:
```
mkdir video
cd video
git init
git remote add -f origin https://github.com/flutter/plugins.git
git config core.sparseCheckout true
echo packages/video_player/video_player/ >> .git/info/sparse-checkout
git pull --depth=1 origin master
cd packages/video_player/video_player/example
flutter run
```

**Comment by darshankawar** [comment]
Hi @llucax,
I tried to replicate the issue by cloning the official `video_player` plugin and ran on latest `beta`, but didn't see the exception you mentioned. I am able to navigate through all 3 tabs without getting that exception.

I tested it on Android 8 (Samsung Galaxy A2Core).  I see that the device you tried on is Android 6. Can you try it on some other device ( > 6) and confirm if you still experience the same exception ?

**Comment by llucax** [comment]
Hi @darshankawar, I just tried with a LG G6 (`LG H870    • LGH8701d9f7a4 • android-arm64  • Android 9 (API 28)`) and it worked fine, so it seems it is related to the Android version. I tried to look for any minimum Android version in the plugin info page but I can see any.

**Comment by llucax** [comment]
Just for the records, the [simple example in the project's `README.md`](https://github.com/flutter/plugins/tree/video_player-v0.10.11%2B2/packages/video_player/video_player#example) does work on the Android 6 device (I had to replace the video URL though, because the provided one doesn't seem to work anymore).

**Comment by khanna007** [comment]
I tried to upgrade flutter to stable channel version 1.20.1 and stop all the task and run the code again this will work

**Comment by llucax** [comment]
Hi @khanna007, thanks for trying it out. Which Android version though? Because this also only happened to me on an Android 6.0 (API 23) phone.

**Comment by khanna007** [comment]
HI @llucax I took video_player: ^0.10.12+2 and the android version is 4.0.1

**Comment by danagbemava-nc** [comment]
I just tested the `video_player` example app on an android emulator running android 6 and the example worked just fine. 

@llucax are you still able to reproduce this issue with the latest version of video_player?
