### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: Data error (cyclic redundancy check)., errno = 23

### ISSUE THREAD

**Issue by muneeb900** [flutter/flutter#61264]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readSync failed, OS Error: Data error (cyclic redundancy check).
, errno = 23
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:763:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:562:23)
#2      _File.readAsStringSync (dart:io/file_impl.dart:594:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#5      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:36:51)
#6      FlutterProject._readManifest (package:flutter_tools/src/project.dart:208:34)
#7      FlutterProjectFactory.fromDirectory.<anonymous closure> (package:flutter_tools/src/project.dart:46:55)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#9      FlutterProjectFactory.fromDirectory (package:flutter_tools/src/project.dart:45:21)
#10     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart:81:86)
#11     FlutterProject.fromPath (package:flutter_tools/src/project.dart:89:50)
#12     PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart:78:55)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:790:21)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:694:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _runZoned (dart:async/zone.dart:1619:10)
#20     runZoned (dart:async/zone.dart:1539:10)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:684:20)
```
```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.18.0-11.1.pre at C:\flutter
    • Framework revision 2738a1148b (8 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\LENOVO\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • HUAWEI TIT AL00 • AVY9KA9640208091 • android-arm64  • Android 5.1 (API 22)
    • Web Server      • web-server       • web-javascript • Flutter Tools
    • Chrome          • chrome           • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 2738a1148ba6c9a6114df62358109407c3ef2553
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
firebase_analytics-5.0.15
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
google_sign_in-4.5.1
google_sign_in_web-0.9.1+1
path_provider-1.6.11
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3

**Comment by jonahwilliams** [comment]
@muneeb900 your hard drive is busted.

https://askleo.com/how_do_i_fix_a_cyclic_redundancy_check_error_when_i_try_to_copy_a_file/#:~:text=A%20cyclic%20redundancy%20check%2C%20or,and%20repair%20your%20hard%20drive.

**Comment by muneeb900** [comment]
Thanks, @jonahwilliams exactly hard drive problem and solved.
