### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by SolomonRosemite** [flutter/flutter#61260]
Hey, so I ran into an small issue lately. I tried to remove and add some images while flutter was running on a emulated android device after trying to hot reload it in throw me an error that the deleted file couldn't be found which makes sense but I didn't try to access the image.

Then I tried to quit the application and it throw me this error here.

Note: Afterwards I tried it again and it worked just fine.

## Logs
FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:458:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      ResidentRunner.preExit (package:flutter_tools/src/resident_runner.dart:1264:25)
#4      HotRunner.preExit (package:flutter_tools/src/run_hot.dart:1152:17)
<asynchronous suspension>
#5      ResidentRunner.exit (package:flutter_tools/src/resident_runner.dart:947:11)
<asynchronous suspension>
#6      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1500:30)
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1584:13)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#15     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#21     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#22     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
```
```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.31, on Microsoft Windows [Version 10.0.18363.900], locale de-DE)
    • Flutter version 1.20.0-8.0.pre.31 at C:\Users\Jesse\OneDrive\Dokumente\flutter
    • Framework revision 0268096bcd (24 hours ago), 2020-07-09 17:11:01 -0400
    • Engine revision a48f05f833
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06cb010247)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at F:\Files\TMFiles\android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = F:\Files\TMFiles\android-sdk
    • ANDROID_SDK_ROOT = F:\Files\TMFiles\android-sdk\tools
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30225.117
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\IntelliJ IDEA Community Edition 2019.3.4
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.47.0)
    • VS Code at C:\Users\Jesse\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 5.0.2 (API 21) (emulator)
    • Windows (desktop)                  • windows       • windows-x64 • Microsoft Windows [Version 10.0.18363.900]

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 462b0ea76eca028a7776f60a20a05ebce30dfdbd
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_storage-3.1.6

**Comment by jonahwilliams** [comment]
@SolomonRosemite  please fill out the steps to reproduce with more details on the commands run and devices targeted.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
