### ISSUE TITLE
[tool_crash] StateError: Bad state: The client closed with pending request "streamCancel".

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#61274]
## Command
```
flutter run --hot -d ZY2245JZ8D --benchmark --verbose --resident --output-dill build/app.dill
```

## Steps to Reproduce
1. run smoke_catalina hot reload benchmarl

## Logs
StateError: Bad state: The client closed with pending request "streamCancel".
```
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _rootRun (dart:async/zone.dart:1182:47)
#2      _CustomZone.run (dart:async/zone.dart:1093:19)
#3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
#4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
#5      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
#6      Future._chainCoreFuture (dart:async/future_impl.dart:496:7)
#7      Future._complete (dart:async/future_impl.dart:508:9)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:55:12)
#9      ChannelManager.close (package:json_rpc_2/src/channel_manager.dart:74:22)
#10     Client.close (package:json_rpc_2/src/client.dart:90:30)
#11     Peer.close (package:json_rpc_2/src/peer.dart:150:28)
#12     _rootRun (dart:async/zone.dart:1182:47)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
#15     Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
#16     Future._propagateToListeners (dart:async/future_impl.dart:722:37)
#17     Future._complete (dart:async/future_impl.dart:519:7)
#18     _SyncCompleter.complete (dart:async/future_impl.dart:55:12)
#19     ChannelManager.listen.<anonymous closure> (package:json_rpc_2/src/channel_manager.dart:58:55)
#20     _rootRun (dart:async/zone.dart:1182:47)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#23     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#24     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
```
```
[✓] Flutter (Channel unknown, 1.20.0-8.0.pre.49, on Mac OS X 10.15 19A582a, locale en-US)
    • Flutter version 1.20.0-8.0.pre.49 at /Users/flutter/.cocoon/flutter
    • Framework revision fe7bbf7226 (8 minutes ago), 2020-07-10 15:35:21 -0700
    • Engine revision 9b3e3410f0
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06cb010247)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (4 available)
    • Moto G 4 (mobile) • ZY2245JZ8D • android-arm    • Android 7.0 (API 24)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15 19A582a
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: null
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-0.4.9
connectivity_for_web-0.3.0
connectivity_macos-0.1.0+3
device_info-0.4.2+4
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2
video_player-0.10.6
video_player_web-0.1.2+3

**Comment by jonahwilliams** [comment]
Fixed by rolling back dds change
