### ISSUE TITLE
Assert when removing a DragTarget that has a candidate from the widget tree.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6128]
```
13:45:29.772: I/flutter : ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
13:45:29.780: I/flutter : The following assertion was thrown while routing a pointer event:
13:45:29.783: I/flutter : setState() called after dispose(): _DragTargetState<StoryCluster>(479045494;
13:45:29.786: I/flutter : _StateLifecycle.defunct; not mounted)
13:45:29.789: I/flutter : This error happens if you call setState() on a State object for a widget that no longer appears in
13:45:29.793: I/flutter : the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error
13:45:29.795: I/flutter : can occur when code calls setState() from a timer or an animation callback. The preferred solution
13:45:29.798: I/flutter : is to cancel the timer or stop listening to the animation in the dispose() callback. Another
13:45:29.802: I/flutter : solution is to check the "mounted" property of this object before calling setState() to ensure the
13:45:29.805: I/flutter : object is still in the tree.
13:45:29.808: I/flutter : This error might indicate a memory leak if setState() is being called because another object is
13:45:29.811: I/flutter : retaining a reference to this State object after it has been removed from the tree. To avoid memory
13:45:29.813: I/flutter : leaks, consider breaking the reference to this object during dispose().
13:45:29.816: I/flutter :
13:45:29.819: I/flutter : When the exception was thrown, this was the stack:
13:45:29.823: I/flutter : #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:818:9)
13:45:29.826: I/flutter : #2      State.setState (package:flutter/src/widgets/framework.dart:816:12)
13:45:29.829: I/flutter : #3      _DragTargetState.didLeave (package:flutter/src/widgets/drag_target.dart:319:5)
13:45:29.832: I/flutter : #4      _DragAvatar._leaveAllEntered (package:flutter/src/widgets/drag_target.dart:455:26)
13:45:29.835: I/flutter : #5      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:428:5)
13:45:29.838: I/flutter : #6      _DragAvatar.update (package:flutter/src/widgets/drag_target.dart:389:5)
13:45:29.842: I/flutter : #7      MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:84:15)
13:45:29.845: I/flutter : #8      MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:208:13)
13:45:29.848: I/flutter : #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
13:45:29.851: I/flutter : #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
13:45:29.854: I/flutter : #11     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:133:19)
13:45:29.857: I/flutter : #12     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:111:22)
13:45:29.860: I/flutter : #13     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:92:7)
13:45:29.863: I/flutter : #14     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:51:7)
13:45:29.866: I/flutter : #15     BindingBase&SchedulerBinding&GestureBinding._handlePointerPacket (package:flutter/src/gestures/binding.dart:44:5)
13:45:29.868: I/flutter : #16     _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:43)
13:45:29.872: I/flutter : (elided one frame from class _AssertionError)
13:45:29.875: I/flutter :
13:45:29.878: I/flutter : Event:
13:45:29.881: I/flutter :   PointerMoveEvent(Point(639.0, 343.5))
13:45:29.884: I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by abarth** [comment]
This probably needs a `mounted` check in that callback.

**Comment by apwilson** [comment]
This is only an issue for me in that there's no way to 'disable' a drag target without removing it from the widget tree.

**Comment by apwilson** [comment]
This was my workaround of removing the drag target fromt he tree that cause the assert.

**Comment by apwilson** [comment]
```
Future main() async {
  runApp(
    new Overlay(
      initialEntries: [
        new OverlayEntry(
          builder: (BuildContext context) => new Foo(),
        ),
      ],
    ),
  );
}

class Foo extends StatefulWidget {
  @override
  FooState createState() => new FooState();
}

class FooState extends State<Foo> {
  bool _includeTarget = true;
  @override
  Widget build(BuildContext context) {
    Widget target = new Container(
      width: 100.0,
      height: 100.0,
      decoration: new BoxDecoration(
        backgroundColor: new Color(0xFF00FFFF),
      ),
    );
    Widget draggable = new Container(
      width: 100.0,
      height: 100.0,
      decoration: new BoxDecoration(
        backgroundColor: new Color(0xFFFFFF00),
      ),
    );
    List<Widget> stackChildren = [
      new Draggable<int>(
        data: 1,
        dragAnchor: DragAnchor.pointer,
        maxSimultaneousDrags: 1,
        childWhenDragging: draggable,
        feedback: draggable,
        child: draggable,
      ),
      _includeTarget
          ? new DragTarget<int>(
              onWillAccept: (int data) {
                setState(() {
                  _includeTarget = false;
                });
                return true;
              },
              onAccept: (int data) {},
              builder: (
                BuildContext context,
                List<int> candidateData,
                List<dynamic> rejectedData,
              ) =>
                  target,
            )
          : target,
    ];
    return new Row(
      children: stackChildren,
    );
  }
}
```
