### ISSUE TITLE
removeActivityResultListener() is causing an ConcurrentModificationException

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#61293]
## Steps to Reproduce

1. Checkout my sample project: https://github.com/rekire/activity_result_crash
2. Run the code

**Expected results:** 
The app should not crash

**Actual results:** 
ConcurrentModificationException

<details>
  <summary>Logs</summary>

```
Launching lib\main.dart on Pixel 2 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Flutter is taking longer than expected to report its views. Still trying...
W/t_crash_exampl(29998): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist, reflection, allowed)
W/t_crash_exampl(29998): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/t_crash_exampl(29998): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/t_crash_exampl(29998): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Debug service listening on ws://127.0.0.1:54493/_eOoR4uJf38=/ws
Syncing files to device Pixel 2...
W/Gralloc3(29998): mapper 3.x is not supported
I/System.out(29998): letItCrash() invoked
I/System.out(29998): Adding ActivityResultListeners
I/System.out(29998): Starting second activity...
W/ActivityThread(29998): handleWindowVisibility: no activity for token android.os.BinderProxy@c78988d
I/System.out(29998): Second activity created and finishing now
I/System.out(29998): Let it crash by removing the listener
D/AndroidRuntime(29998): Shutting down VM
E/AndroidRuntime(29998): FATAL EXCEPTION: main
E/AndroidRuntime(29998): Process: eu.rekisoft.flutter.activity_result_crash.activity_result_crash_example, PID: 29998
E/AndroidRuntime(29998): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {eu.rekisoft.flutter.activity_result_crash.activity_result_crash_example/eu.rekisoft.flutter.activity_result_crash.activity_result_crash_example.MainActivity}: java.util.ConcurrentModificationException
E/AndroidRuntime(29998): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime(29998): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime(29998): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(29998): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(29998): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(29998): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(29998): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(29998): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(29998): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(29998): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29998): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(29998): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(29998): Caused by: java.util.ConcurrentModificationException
E/AndroidRuntime(29998): 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
E/AndroidRuntime(29998): 	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
E/AndroidRuntime(29998): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:689)
E/AndroidRuntime(29998): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(29998): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime(29998): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:574)
E/AndroidRuntime(29998): 	at android.app.Activity.dispatchActivityResult(Activity.java:8135)
E/AndroidRuntime(29998): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime(29998): 	... 11 more
I/Process (29998): Sending signal. PID: 29998 SIG: 9
Lost connection to device.
```

```
(skipped `flutter analyze` since I think this is not relevant)
```

```
(skipped `flutter doctor -v` since I think this is not relevant)
```
</details>

As discussed here https://github.com/rekire/autologin_plugin/issues/3, the issue seems to be that I call in the `ActivityResultListener` the method [`removeActivityResultListener()`](https://github.com/rekire/autologin_plugin/blob/44292526d884c37418dc6ae2f7f26dbd197c0b39/android/src/main/kotlin/eu/rekisoft/flutter/autologin/LoginHelper.kt#L113). Which breaks [the iterator](https://github.com/flutter/engine/blob/025e2d82dda54af7f33a0d511bde47ec835593b1/shell/platform/android/io/flutter/embedding/engine/FlutterEnginePluginRegistry.java#L688) and causes the `ConcurrentModificationException`.

Out of my view there are two solutions:
1. When the result was consumed break the loop, there should be only one consumer out of my view anyway.
2. Create a copy of the listeners to avoid breaking the interator.

I would like to create a pull request to solve this issue, however I would like to get some feedback before.

**Comment by NoamDev** [comment]
Hi!
If you find minimal code that triggers it abd that always works, it'd be much easier to understand the problem and try to help/fix it.

**Comment by rekire** [comment]
You are right, I created a sample project which will cause that crash https://github.com/rekire/activity_result_crash

**Comment by NoamDev** [comment]
Very interesting. 
Here is the code causing crash in the minimal repro.
https://github.com/rekire/activity_result_crash/blob/1cc32e891e17f4e6a60d815e23da1de713528f01/android/src/main/kotlin/eu/rekisoft/flutter/activity_result_crash/activity_result_crash/ActivityResultCrashPlugin.kt#L67

**Comment by NoamDev** [comment]
Another solution could be using CopyOnWriteArrayList, which just supports editing while iterating.
What do you think about that?

**Comment by rekire** [comment]
To be honest I don't know that special implementation. I'll check it. As long as modification doesn't break the interator it should be fine

**Comment by rekire** [comment]
I checked the implementation: that should work fine. I'm wondering what happens more often, that the array is modified or that the iterator is called. I think the iterator is less often called. So I think that there will be less memory allocation when a copy is made only when the iterator is used. Micro optimizations sure, but it should be the same amount of code changes for my solution *let's copy the data of the iterator*.

**What should happen if you remove two listeners at once?** Would you expect that the second uncalled listener should be called or not? I would expect that the removed lister would not be called. Both solutions would not cover that.

The third way just to break the loop when you found the "handling" observer could break some tracking code or other meta observers.

What do you think about it?

**Comment by NoamDev** [comment]
You're right about CopyOnWriteArrayList, I wasn't aware to the exact implementation. As you said it's not efficient and doesn't solve much.
I'm not sure however that one should expect the listeners to be called in the order of adding..
Therefore, removing a listener during an iteration should not affect the iteration, and it's stupid to remove two listeners when one of them is called isn't it?
I agree that breaking the loop might lead to unexpected results.

I think that copying the list before an iteration is good, but am not sure if there are any performance implications.
Have you experienced setting up engine development enviroment before? well, it's not very easy nor quick.
I thought you might want to do something interesting instead, because this is a very little change.
Maybe open a template pr and in the title include [work in progress] [do not review].
Then the CI would run all his checks, I think that even performance so you can get feedback from it.

Generally people should check their code on their own first, but who cares 😉

**Comment by TahaTesser** [comment]
Hi @rekire 
running your example app not causing the exception even tried hot reload/hot restart

<details> 
<summary>logs</summary> 

``` 
Launching lib/main.dart on SM M305F in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:63658/lTRv6wqBbWM=/ws
I/System.out(26113): letItCrash() invoked
I/System.out(26113): Adding ActivityResultListeners
I/System.out(26113): Starting second activity...
W/ActivityThread(26113): handleWindowVisibility: no activity for token android.os.BinderProxy@3fd895b
I/System.out(26113): Second activity created and finishing now
I/MultiWindowDecorSupport(26113): updateCaptionType >> DecorView@d102ad1[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport(26113): setCaptionType = 0, DecorView = DecorView@d102ad1[]
D/ViewRootImpl@d7edc5e[MainActivity](26113): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(26113): prepareNavigationBarInfo() DecorView@949c112[MainActivity]
D/InputMethodManager(26113): getNavigationBarColor() -855310
I/System.out(26113): Listener 2 called, only executed when the bug is fixed
I/System.out(26113): Let it crash by removing the listener
D/ViewRootImpl@d7edc5e[MainActivity](26113): stopped(false) old=false
D/ViewRootImpl@d7edc5e[MainActivity](26113): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(26113): prepareNavigationBarInfo() DecorView@949c112[MainActivity]
D/InputMethodManager(26113): getNavigationBarColor() -855310
D/ViewRootImpl@d7edc5e[MainActivity](26113): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=10 res=0x1 s={true 491927035904} ch=false

``` 

</details> 

![flutter_01](https://user-images.githubusercontent.com/48603081/87302240-a70c7380-c52e-11ea-8846-2ab1f35c6ed7.png)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (2 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.5
      19F101
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
```

</details>

**Comment by NoamDev** [comment]
@rekire notice that the logs are not in the correct order..
That's beacuse it is a hashset and no a list.
You need to change your code so that works no matter what the order of calling is.
For example I made both listeners equivalent:
``` kotlin
var removed: boolean = false
 private fun letItCrash(binding: ActivityPluginBinding, result: Result) {
    println("Adding ActivityResultListeners")
    binding.addActivityResultListener(object: PluginRegistry.ActivityResultListener {
      override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean {
        if(! removed) {
            removed = true
            println("Let it crash by removing the listener")
            binding.removeActivityResultListener(this)
            // assume that you waited for the result
            result.success(42)
            return true
        } else {
                println("Listener 2 called, only executed when the bug is fixed")
                false
        }
      }
    })
    binding.addActivityResultListener(object: PluginRegistry.ActivityResultListener {
      override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean {
        if(! removed) {
            removed = true
            println("Let it crash by removing the listener")
            binding.removeActivityResultListener(this)
            // assume that you waited for the result
            result.success(42)
            return true
        } else {
                println("Listener 2 called, only executed when the bug is fixed")
                false
        }
      }
    })
    println("Starting second activity...")
    binding.activity.startActivityForResult(Intent(binding.activity, SecondActivity::class.java), 1)
  }
```

**Comment by rekire** [comment]
@NoamDev great catch! I missed that fact that the order is not stable. I will update my sample code

**Comment by rekire** [comment]
@TahaTesser I updated my sample code, please try again

**Comment by chinmaygarde** [comment]
cc @blasten @xster

**Comment by rekire** [comment]
FYI: I am working on a fix here: https://github.com/flutter/engine/pull/19702
However since I am unable to run the code local, my new test is failing and it is a bit hard for me to get it running

**Comment by NoamDev** [comment]
The problem is the test's code style.
Look at the failed check it's a code style check.
It says exactly what you should do in order to fix it.

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

``` 
Launching lib/main.dart on SM M305F in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Connecting to VM Service at ws://127.0.0.1:65274/RAauftAyEaE=/ws
D/SurfaceView(21569): surfaceChanged (1080,2301) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{b941936 V.E...... ......ID 0,0-1080,2301}
I/System.out(21569): letItCrash() invoked
I/System.out(21569): Adding ActivityResultListeners
I/System.out(21569): Starting second activity...
I/System.out(21569): Second activity created and finishing now
I/MultiWindowDecorSupport(21569): updateCaptionType >> DecorView@401c8d3[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport(21569): setCaptionType = 0, DecorView = DecorView@401c8d3[]
D/SurfaceView(21569): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{b941936 V.E...... ........ 0,0-1080,2301} of ViewRootImpl@a2f65f8[MainActivity]
D/SurfaceView(21569): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{b941936 V.E...... ........ 0,0-1080,2301}
D/SurfaceView(21569): remove() io.flutter.embedding.android.FlutterSurfaceView{b941936 V.E...... ........ 0,0-1080,2301} Surface(name=SurfaceView - eu.rekisoft.flutter.activity_result_crash.activity_result_crash_example/eu.rekisoft.flutter.activity_result_crash.activity_result_crash_example.MainActivity@b941936@0)/@0xd3403d4
W/libEGL  (21569): EGLNativeWindowType 0x728d41bd10 disconnect failed
D/ViewRootImpl@a2f65f8[MainActivity](21569): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=15 res=0x40005 s={false 0} ch=true
I/System.out(21569): Let it crash by removing the listener
D/AndroidRuntime(21569): Shutting down VM
E/AndroidRuntime(21569): FATAL EXCEPTION: main
E/AndroidRuntime(21569): Process: eu.rekisoft.flutter.activity_result_crash.activity_result_crash_example, PID: 21569
E/AndroidRuntime(21569): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {eu.rekisoft.flutter.activity_result_crash.activity_result_crash_example/eu.rekisoft.flutter.activity_result_crash.activity_result_crash_example.MainActivity}: java.util.ConcurrentModificationException
E/AndroidRuntime(21569): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
E/AndroidRuntime(21569): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138)
E/AndroidRuntime(21569): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(21569): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(21569): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(21569): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
E/AndroidRuntime(21569): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(21569): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(21569): 	at android.app.ActivityThread.main(ActivityThread.java:7807)
E/AndroidRuntime(21569): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21569): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(21569): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
E/AndroidRuntime(21569): Caused by: java.util.ConcurrentModificationException
E/AndroidRuntime(21569): 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
E/AndroidRuntime(21569): 	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
E/AndroidRuntime(21569): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:689)
E/AndroidRuntime(21569): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(21569): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:619)
E/AndroidRuntime(21569): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:584)
E/AndroidRuntime(21569): 	at android.app.Activity.dispatchActivityResult(Activity.java:8292)
E/AndroidRuntime(21569): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5090)
E/AndroidRuntime(21569): 	... 11 more
I/Process (21569): Sending signal. PID: 21569 SIG: 9
Lost connection to device.
Exited (sigterm)

``` 

</details> 
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (3 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • SM M305F (mobile)      • 32003c30dc19668f                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.5.1
    • iPhone 11 (mobile)     • C56E212F-BE8E-4766-8610-12CFADC797F0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.5 19F101
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

</details>

**Comment by gaaclarke** [comment]
fixed in https://github.com/flutter/engine/pull/19702

**Comment by rekire** [comment]
It seems there are two very similar places where this bug is hidden. While testing the result I found a second implementation which causes a crash. I would like to reopen this and fix the issue in a second PR.

**Comment by gaaclarke** [comment]
@rekire Done.

**Comment by rekire** [comment]
Seems to work on the master, regarding the other issues I'm not absolutely sure. I will open a new bug when I find it there too.
