### ISSUE TITLE
'flutter run -d linux' fails with "undefined reference to `fcntl64@GLIBC_2.28"

### ISSUE THREAD

**Issue by lordtiva** [flutter/flutter#61329]
### Steps to Reproduce

```
$ flutter run -d linux
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[  +73 ms] executing: [/home/lordtiva/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +19 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8bd2e6585b0eda5ccdc10c1e1d35105e11f84424
[        ] executing: [/home/lordtiva/snap/flutter/common/flutter/] git tag --contains HEAD
[ +114 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/home/lordtiva/snap/flutter/common/flutter/] git describe --match *.*.*-*.*.pre --first-parent
--long --tags
[   +8 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.20.0-7.0.pre-57-g8bd2e6585
[   +4 ms] executing: [/home/lordtiva/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/lordtiva/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +25 ms] executing: [/home/lordtiva/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +23 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +6 ms] executing: /home/lordtiva/Android/Sdk/platform-tools/adb devices -l
[  +21 ms] List of devices attached
[   +6 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] executing: unzip -t -qq
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64/linux-x64-flutter-gtk.zip
[   +3 ms] Downloading linux-x64/linux-x64-flutter-gtk tools...
[   +5 ms] Downloading:
https://storage.googleapis.com/flutter_infra/flutter/9b3e3410f02681e446ca48038164a553ababb143/linux-x64/linux-x64-flutt
er-gtk.zip
[ +786 ms] Received response from server, collecting bytes...
[+3041 ms] Downloading linux-x64/linux-x64-flutter-gtk tools... (completed in 3,8s)
[        ] executing: unzip -o -q
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64/linux-x64-flutter-gtk.zip -d
/home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64
[ +695 ms] Exit code 0 from: unzip -o -q
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64/linux-x64-flutter-gtk.zip -d
/home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64
[  +13 ms] executing: unzip -t -qq
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64-profile/linux-x64-flutter-gtk.zip
[   +3 ms] Downloading linux-x64-profile/linux-x64-flutter-gtk tools...
[        ] Downloading:
https://storage.googleapis.com/flutter_infra/flutter/9b3e3410f02681e446ca48038164a553ababb143/linux-x64-profile/linux-x
64-flutter-gtk.zip
[ +355 ms] Received response from server, collecting bytes...
[+1925 ms] Downloading linux-x64-profile/linux-x64-flutter-gtk tools... (completed in 2,3s)
[        ] executing: unzip -o -q
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64-profile/linux-x64-flutter-gtk.zip -d
/home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64-profile
[ +428 ms] Exit code 0 from: unzip -o -q
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64-profile/linux-x64-flutter-gtk.zip -d
/home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64-profile
[   +9 ms] executing: unzip -t -qq
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64-release/linux-x64-flutter-gtk.zip
[   +4 ms] Downloading linux-x64-release/linux-x64-flutter-gtk tools...
[        ] Downloading:
https://storage.googleapis.com/flutter_infra/flutter/9b3e3410f02681e446ca48038164a553ababb143/linux-x64-release/linux-x
64-flutter-gtk.zip
[ +697 ms] Received response from server, collecting bytes...
[+1519 ms] Downloading linux-x64-release/linux-x64-flutter-gtk tools... (completed in 2,2s)
[        ] executing: unzip -o -q
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64-release/linux-x64-flutter-gtk.zip -d
/home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64-release
[ +344 ms] Exit code 0 from: unzip -o -q
/home/lordtiva/snap/flutter/common/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/9b3e3410f0
2681e446ca48038164a553ababb143/linux-x64-release/linux-x64-flutter-gtk.zip -d
/home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64-release
[  +17 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] Generating
/home/lordtiva/counter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +42 ms] Starting incremental build...
[   +1 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +2 ms] Launching lib/main.dart on Linux in debug mode...
[   +3 ms] /home/lordtiva/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tools.SVBROU/flutter_tool.FNWWTX/app.dill
--packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avo
id-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/cache.dill.track.dill
[   +9 ms] Building Linux application...
[   +6 ms] <- compile package:counter/main.dart
[   +2 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/lordtiva/counter/linux
[  +90 ms] -- The CXX compiler identification is Clang 6.0.0
[   +2 ms] -- Check for working CXX compiler: /snap/flutter/21/usr/bin/clang++
[  +47 ms] -- Check for working CXX compiler: /snap/flutter/21/usr/bin/clang++ -- works
[        ] -- Detecting CXX compiler ABI info
[  +48 ms] -- Detecting CXX compiler ABI info - done
[   +2 ms] -- Detecting CXX compile features
[ +229 ms] -- Detecting CXX compile features - done
[   +3 ms] -- Found PkgConfig: /snap/flutter/21/usr/bin/pkg-config (found version "0.29.1") 
[        ] -- Checking for module 'gtk+-3.0'
[   +9 ms] --   Found gtk+-3.0, version 3.22.30
[  +39 ms] -- Checking for module 'glib-2.0'
[   +7 ms] --   Found glib-2.0, version 2.56.4
[  +19 ms] -- Checking for module 'gio-2.0'
[   +7 ms] --   Found gio-2.0, version 2.56.4
[  +25 ms] -- Configuring done
[   +4 ms] -- Generating done
[        ] -- Build files have been written to: /home/lordtiva/counter/build/linux/debug
[   +2 ms] executing: ninja -C build/linux/debug install
[   +5 ms] ninja: Entering directory `build/linux/debug'
[+6064 ms] [1/6] Generating /home/lordtiva/counter/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/lordtiva/counter/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +1 ms] [  +73 ms] executing: [/home/lordtiva/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [  +17 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 8bd2e6585b0eda5ccdc10c1e1d35105e11f84424
[        ] [        ] executing: [/home/lordtiva/snap/flutter/common/flutter/] git tag --contains HEAD
[        ] [ +118 ms] Exit code 0 from: git tag --contains HEAD
[        ] [   +1 ms] executing: [/home/lordtiva/snap/flutter/common/flutter/] git describe --match *.*.*-*.*.pre
--first-parent --long --tags
[        ] [   +8 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] [        ] 1.20.0-7.0.pre-57-g8bd2e6585
[        ] [   +5 ms] executing: [/home/lordtiva/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/lordtiva/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +1 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +24 ms] executing: [/home/lordtiva/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +23 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +60 ms] Initializing file store
[        ] [   +9 ms] Skipping target: gen_localizations
[        ] [        ] unpack_linux: Starting due to {}
[        ] [  +50 ms] unpack_linux: Complete
[        ] [  +11 ms] kernel_snapshot: Starting due to {}
[        ] [  +17 ms] /home/lordtiva/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/lordtiva/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avo
id-closure-call-instructions --enable-asserts --track-widget-creation --packages /home/lordtiva/counter/.packages
--output-dill /home/lordtiva/counter/.dart_tool/flutter_build/fdebf48d398ff59ebf28195c733943d8/app.dill --depfile
/home/lordtiva/counter/.dart_tool/flutter_build/fdebf48d398ff59ebf28195c733943d8/kernel_snapshot.d
package:counter/main.dart
[        ] [+4279 ms] kernel_snapshot: Complete
[        ] [ +356 ms] debug_bundle_linux_assets: Starting due to {}
[        ] [  +71 ms] debug_bundle_linux_assets: Complete
[        ] [ +419 ms] Persisting file store
[        ] [   +4 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [   +4 ms] "flutter assemble" took 5.303ms.
[        ] [ +148 ms] ensureAnalyticsSent: 146ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +301 ms] [2/6] Building CXX object CMakeFiles/counter.dir/flutter/generated_plugin_registrant.cc.o
[   +4 ms] [3/6] Building CXX object CMakeFiles/counter.dir/main.cc.o
[   +7 ms] [4/6] Building CXX object CMakeFiles/counter.dir/my_application.cc.o
[  +58 ms] [5/6] Linking CXX executable counter
[        ] FAILED: counter 
[        ] : && /snap/flutter/21/usr/bin/clang++  -g  -L/snap/flutter/21/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/21/usr/lib/x86_64-linux-gnu -L/snap/flutter/21/usr/lib/ CMakeFiles/counter.dir/main.cc.o
CMakeFiles/counter.dir/my_application.cc.o CMakeFiles/counter.dir/flutter/generated_plugin_registrant.cc.o  -o counter
-L/home/lordtiva/counter/linux/flutter/ephemeral -Wl,-rpath,/home/lordtiva/counter/linux/flutter/ephemeral:
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so -lflutter_linux_gtk
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[        ] //lib64/libblkid.so.1: undefined reference to `fcntl64@GLIBC_2.28'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] ninja: build stopped: subcommand failed.
[   +1 ms] Building Linux application... (completed in 7,0s)
[        ] Exception: Build process failed
[   +1 ms] "flutter run" took 17.087ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +152 ms] ensureAnalyticsSent: 151ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +7 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
```
$ flutter analyze
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Analyzing counter...                                                    
No issues found! (ran in 5.5s)

```
```
$ flutter doctor -v
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[✓] Flutter (Channel master, 1.20.0-8.0.pre.57, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.20.0-8.0.pre.57 at /home/lordchelo/snap/flutter/common/flutter
    • Framework revision 8bd2e6585b (hace 23 horas), 2020-07-11 12:15:19 -0700
    • Engine revision 9b3e3410f0
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 06cb010247)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/lordchelo/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /var/lib/snapd/snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /var/lib/snapd/snap/android-studio/90/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```
Running on Fedora Workstation 32
`$ uname -a
Linux fedora-lan 5.7.8-200.fc32.x86_64 #1 SMP Thu Jul 9 14:34:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jonahwilliams** [comment]
Failure is:

```
 FAILED: counter 
[        ] : && /snap/flutter/21/usr/bin/clang++  -g  -L/snap/flutter/21/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/21/usr/lib/x86_64-linux-gnu -L/snap/flutter/21/usr/lib/ CMakeFiles/counter.dir/main.cc.o
CMakeFiles/counter.dir/my_application.cc.o CMakeFiles/counter.dir/flutter/generated_plugin_registrant.cc.o  -o counter
-L/home/lordtiva/counter/linux/flutter/ephemeral -Wl,-rpath,/home/lordtiva/counter/linux/flutter/ephemeral:
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so -lflutter_linux_gtk
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[        ] //lib64/libblkid.so.1: undefined reference to `fcntl64@GLIBC_2.28'
```

**Comment by chinmaygarde** [comment]
cc @csells

**Comment by stuartmorgan** [comment]
@robert-ancell Thoughts on this build failure? Are we under-specifying our required library versions?

**Comment by yzg-github** [comment]
you can run : strings /lib64/libc.so.6 |grep GLIBC_  
to Confirm whether it has been installed if not you may install it first
you can download from http://www.gnu.org/software/libc/

**Comment by lordtiva** [comment]
@yzg-github I have glibc 2.31 installed on my system

**Comment by stuartmorgan** [comment]
I just noticed that this (and the duplicate just filed) appear to be using the snap-based install. @kenvandine is there something missing from the image?

**Comment by kenvandine** [comment]
@MarcusTomlinson can you take a look at this?  I had tested this on Fedora 31 last month and it built fine, but now I can reproduce this.  I tried adding libblkid1 to the stage-snaps and it still fails.

**Comment by MarcusTomlinson** [comment]
Still waiting on https://github.com/flutter/flutter/pull/62979.
