### ISSUE TITLE
Android license status unknown

### ISSUE THREAD

**Issue by aluu4445** [flutter/flutter#61354]
## Steps to Reproduce

When I run `flutter doctor -v` I get an 'Android license status unknown' issue (see below)

The following are already installed in Android SDK:
- Android SDK Platform-Tools
- Android SDK Tools (Obselete)

I've tried:
- Reinstalling Android SDK Platform-Tools and Android SDK Tools (Obselete)
- Installing Java 8 and updating my `JAVA_HOME` system variable
- Installing Android SDK Command-line Toolss
- Reinstalling Android Studio

## Logs

**When running `flutter doctor -v`:**
```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale en-AU)
    • Flutter version 1.17.5 at C:\Users\Andy\flutter
    • Framework revision 8af6b2f038 (13 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Andy\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2019.2
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052

[√] VS Code (version 1.47.0)
    • VS Code at C:\Users\Andy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[!] Connected device
    • Device R58N30DPMZB is not authorized.
      You might need to check your device for an authorization dialog.

```

When running `flutter doctor --android-licenses`
```
C:\Users\Andy\AndroidStudioProjects\flutter_app>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more

```

**Comment by TahaTesser** [comment]
Hi @aluu4445 
Please check solution https://github.com/flutter/flutter/issues/56778#issuecomment-653635824
Thank you

**Comment by aluu4445** [comment]
Thanks that fixed it!
