### ISSUE TITLE
App Crashing on launch after adding package_info: 0.4.1

### ISSUE THREAD

**Issue by ArunYogeshwaran** [flutter/flutter#61367]
Please find the logs below:

```
E/flutter ( 6140): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
E/flutter ( 6140): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6140): <asynchronous suspension>
E/flutter ( 6140): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6140): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359:48)
E/flutter ( 6140): #3      PackageInfo.fromPlatform (package:package_info/package_info.dart:43:25)
E/flutter ( 6140): #4      About.buildMoreInfo.<anonymous closure> (package:fluttertrees/pages/about.dart:111:53)
E/flutter ( 6140): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:953:19)
E/flutter ( 6140): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1059:38)
E/flutter ( 6140): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 6140): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
E/flutter ( 6140): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 6140): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter ( 6140): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 6140): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 6140): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 6140): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 6140): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 6140): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 6140): #17     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 6140): #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6140): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 6140): #20     _invoke1 (dart:ui/hooks.dart:281:10)
E/flutter ( 6140): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:190:5)
E/flutter ( 6140): 

```

Environment:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by darshankawar** [comment]
Hi @ArunYogeshwaran,
If you are trying to hot reload the app after adding the plugin, you are likely to get this error. If so, stop the app instance, run `flutter pub cache repair` and then `flutter run` to see if it resolves your issue.
If the problem still persists, then please provide `flutter run --verbose` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
