### ISSUE TITLE
'pendingDelta.distance <= kTouchSlop' is not true.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6156]
```
14:14:47.954: E/flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
14:14:47.957: E/flutter : 'package:flutter/src/gestures/multidrag.dart': Failed assertion: line 400 pos 12: 'pendingDelta.distance <= kTouchSlop' is not true.
14:14:47.960: E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
14:14:47.962: E/flutter : #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
14:14:47.965: E/flutter : #2      _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:400:12)
14:14:47.967: E/flutter : #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
14:14:47.970: E/flutter : #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
14:14:47.973: E/flutter : #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
14:14:47.976: E/flutter : #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

**Comment by apwilson** [comment]
This seems to break draggables in some way.

**Comment by apwilson** [comment]
Seems to be due to some interaction with the Android System UI.

```
14:48:26.293: E/flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
14:48:26.295: E/flutter : 'package:flutter/src/gestures/multidrag.dart': Failed assertion: line 400 pos 12: 'pendingDelta.distance <= kTouchSlop' is not true.
14:48:26.298: E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
14:48:26.301: E/flutter : #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
14:48:26.304: E/flutter : #2      _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:400:12)
14:48:26.307: E/flutter : #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
14:48:26.309: E/flutter : #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
14:48:26.312: E/flutter : #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
14:48:26.314: E/flutter : #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by abarth** [comment]
Somehow the arena has already resolved, which means we don't cancel the timer.

**Comment by abarth** [comment]
Looks like if we were accepted, then if the pending delta gets too big, we'll try to reject, but that won't do anything because the arena is resolved.  Then the timer will fire and we'll be sad.

**Comment by abarth** [comment]
Got it in a test.
