### ISSUE TITLE
[ios] platform_views_layout crashes on subsequent runs

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#61584]
Here's a sample log:
```
platform_channel.dart:161)
stdout: [   +3 ms] <asynchronous suspension>
stdout: [        ] #2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:219)
stdout: [        ] <asynchronous suspension>
stdout: [        ] #3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:624)
stdout: [        ] <asynchronous suspension>
stdout: [   +1 ms] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(create_failed, can't create a view on a headless engine, null)
stdout: [        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572)
stdout: [        ] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161)
stdout: [        ] <asynchronous suspension>
stdout: [        ] #2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:219)
stdout: [        ] <asynchronous suspension>

2020-07-15T14:52:19.045273: INFO [task runner] [platform_views_scroll_perf_ios__timeline_summary] stdout: [        ] #3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:624)
stdout: [        ] <asynchronous suspension>
stdout: [        ] [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(create_failed, can't create a view on a headless engine, null)
stdout: [        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572)
stdout: [        ] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161)
stdout: [        ] <asynchronous suspension>
stdout: [        ] #2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:219)
stdout: [        ] <asynchronous suspension>
stdout: [        ] #3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:624)
stdout: [        ] <asynchronous suspension>
```

fwiw, the framework fires a message to create the native view, which is handled in https://github.com/flutter/engine/blob/24d2143b98d6b0dfffd52eaad60d3900ea6a5190/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L124.  

cc @dnfield, @cyanglaz

**Comment by dnfield** [comment]
I'm able to reproduce this locally with a profile build of platform_views_layout. Every so often running it results in failure.  Escalating priority until we determine cause.

**Comment by dnfield** [comment]
Root cause is https://github.com/flutter/engine/pull/19592

**Comment by dnfield** [comment]
Steps to recreate: `flutter run --profile` in platform_views_layout, exit the app, run it a second time.

**Comment by pcsosinski** [comment]
this also affects 1.20 as 0dc86cda19d55aba8b719231c11306eeaca4b798 was our engine branch point

**Comment by pcsosinski** [comment]
this will require a manual merge into flutter-1.20-candidate.7

**Comment by pcsosinski** [comment]
for posterity the 1.20 cherrypick is https://github.com/flutter/engine/pull/19848
