### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\Ankitha Pinky\Desktop\Mine\flutter_course\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\Users\Ankitha Pinky\Downloads\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by anku-caps** [flutter/flutter#61601]
## Command
```
flutter create flutter_course
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\Ankitha Pinky\Desktop\Mine\flutter_course\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\Users\Ankitha Pinky\Downloads\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:227:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#6      Template.render (package:flutter_tools/src/template.dart:153:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:630:21)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```
```
[✓] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.900], locale en-IN)
    • Flutter version 1.17.4 at C:\Users\Ankitha Pinky\Downloads\flutter
    • Framework revision 1ad9baa8b9 (4 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Ankitha Pinky\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[✓] VS Code (version 1.46.1)
    • VS Code at C:\Users\Ankitha Pinky\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[✓] Connected device (1 available)
    • S6s • DEW8NRIN65GMS8G6 • android-arm64 • Android 7.0 (API 24)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by YazeedAlKhalaf** [comment]
We need more info to be able to help. Did you make any changes to the app? If yes please provide a replicable sample of code so we can replicate the error and solve it

**Comment by anku-caps** [comment]
> We need more info to be able to help. Did you make any changes to the app? If yes please provide a replicable sample of code so we can replicate the error and solve it

I,myself solved the problem.
Thankyou.

**Comment by YazeedAlKhalaf** [comment]
You're welcome
