### ISSUE TITLE
Support custom ADB sockets while debugging

### ISSUE THREAD

**Issue by fhuonder** [flutter/flutter#61604]
Hi,

I am working with a vscode devcontainer that contains the flutter installation.
My environment is Windows 10 with WSL2 and Docker (WSL2-backend). The devcontainer runs on this WSL2-backend-Docker instance.
First I created this issue https://github.com/Dart-Code/Dart-Code/issues/2640 but it turned out that it looks like a problem with flutter itself.

Due to the fact that it is currently not possible to attach USB devices directly in WSL2 we need ADB (in the devcontainer) to communicate with the ADB on Windows.

ADB supports this by having the possibility to override its SOCKET (flag `-L` or as we did it by setting the environment variable `ADB_SERVER_SOCKET`). In the devcontainer (where flutter runs) we changed to socket to `tcp:host.docker.internal:5037` via environment variable. On the windows side we run `adb -a -P 5037 nodaemon server`. With this setup ADB in the devcontainer has the same output as ADB on Windows (e.g. for `adb devices`).

Unfortunately, with this setup it is not possible to debug a flutter app from the devcontainer.
On startup it says
```
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 48590
This was attempt #1. Will retry in 0:00:00.100000.
```
and on the device I get a white screen.

I also tried by setting the argument `--host-vmservice-port=9999` but this has no effect. The output then is
```
Forwarded host port 9999 to device port 46347 for Observatory
Connecting to service protocol: http://127.0.0.1:9999/PH5EDsAqjMw=/
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 48590
This was attempt #1. Will retry in 0:00:00.100000.
```

The output of flutter doctor is
```
[4781 ms] [✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Linux, locale en_US)
[4782 ms]     • Flutter version 1.20.0-7.1.pre at /flutter
[4782 ms]     • Framework revision 7736f3bc90 (5 days ago), 2020-07-10 16:33:05 -0700
[4783 ms]     • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)
[4784 ms] 
[9737 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /android-sdk
[9738 ms]     • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/bin/java
[9738 ms]     • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
[9738 ms]     • All Android licenses accepted.

[9739 ms] [!] Android Studio (not installed)
[9739 ms]     • Android Studio not found; download from https://developer.android.com/studio/index.html
[9740 ms]       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[9740 ms] 
[9741 ms] [✓] Connected device (1 available)
[9741 ms]     • Nexus 5X                     • 0263ecc816b81901 • android-arm64  • Android 8.1.0 (API 27)
```

Am I missing something or is this a bug/missing feature?

Regards,
Florian

**Comment by fhuonder** [comment]
Would be nice if someone could have a look at this issue :).
Depending on the needed changes, if such are necessary, I might delivery a PR.

**Comment by Dinduks** [comment]
Hey Florian! Thanks for opening this issue.  
I get the same errors when trying to use an emulator (running on Windows; I code on WSL2).

I am new to Flutter/Dart and was wondering what port 9999 refers to.  
I tried using it along with the `adb tcpip X` trick to connect to my phone, yet I get the same white screen issue and those `Exception attempting to connect to the VM Service` errors.  
Can you please help me resolve this?

**Comment by fhuonder** [comment]
Hi @Dinduks 

The `adb tcpip` is to be used without `--host-vmservice-port`. And further, as written above, `adb tcpip` does (as far as I know) not work with an emulator, only a real device.

**Comment by alexisbg** [comment]
It's the same if I try to debug a flutter Android app from WSL2 (but not into a container):
```
[ +266 ms] Connecting to service protocol: http://127.0.0.1:52258/MN7cYgZWGt8=/
[   +3 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:52258/MN7cYgZWGt8=/.
[  +82 ms] Fail to connect to service protocol: http://127.0.0.1:52258/MN7cYgZWGt8=/: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 59658
[   +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:52258/MN7cYgZWGt8=/
```

It is so bad because Flutter seems to run fine with WSL2 except this show stopper issue.

**Comment by fhuonder** [comment]
Hi all,

I have an update.
I am currently working on Flutter version 1.24.0-7.0.pre and I got it working (almost).

I have to start flutter with `--host-vmservice-port 10388` and that it works I had to add a proxy like this 
```
socat tcp-listen:10388,bind=127.0.0.1,fork tcp:host.docker.internal:10388
```

The proxy was needed because flutter  tries to connect to the observatory on 127.0.0.1 and when running in a devcontainer (or wsl2) this is not the host machine where ADB runs and ADB opens a port forward from the host machine.
It is still needed to make the ADB socket by having the environment variable `ADB_SERVER_SOCKET=tcp:host.docker.internal:5037`.

As soon as the emulator/device is started on windows flutter sees it (because of the ADB socket settings) and can then interact with it.

Still not working:
Interacting with the emulators. The emulators (or devices) must be managed/started from Windows. It's not possible to start en emualtor (on Windows) from the devcontainer.

Maybe we are a step further?

Regards,
Florian

**Comment by murbanowicz** [comment]
@fhuonder What can I do while running Flutter directly in WSL? I have exactly same issues, it is also causing hot-reload not working.

**Comment by fhuonder** [comment]
Hi @murbanowicz 
In the WSL 2 (not WSL 1) it should be the same. If or how it works in WSL 1, I did not check.
It shouldn't make any difference if you are running in WSL2 or a docker-based devcontainer.

Do the same as I wrote in the initial post and my last comment. And check your flutter version, for me it only works with a newer one.

I never had problems with hot reloading, this works this way.

Regards,
Florian

**Comment by fhuonder** [comment]
An issue that persists..
After starting the devcontainer and trying to start the flutter app the first time, an error occurrs that the flutter daemon has terminated.
In the logs it says `[6:35:14 AM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"error","message":"Unable to run \"adb\", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: /android-sdk/platform-tools/adb"}}]`

After hitting restart it works as expected.

**Comment by janlinders** [comment]
Dears, any update on this issue.
I did research all the topics about this on Google Search and seems everyone is providing a possible solution that worked for them but not for others. Tried all the provided solutions but no luck.
I'm experiencing the same intermittent problem.
Need to reboot system several time a day to get it working again and after some tests it fails all over again.
This is becoming a non workable development env.

See error below.

Snippet of the last flutter run -v

[ ] Installing APK.
[ +1 ms] Installing build/app/outputs/flutter-apk/app.apk...
[ ] executing: /home/admin/Android/Sdk/platform-tools/adb -s c0808941f928e60 install -t -r
/home/admin/StudioProjects/meet_station/build/app/outputs/flutter-apk/app.apk
[+30407 ms] Performing Push Install
/home/admin/StudioProjects/meet_station/build/app/outputs/flutter-apk/app.apk: 1 file pushed, 0 skipped. 6.3 MB/s (66137504 bytes in 10.036s)
pkg: /data/local/tmp/app.apk
Success
[ ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 30.4s)
[ +2 ms] executing: /home/admin/Android/Sdk/platform-tools/adb -s c0808941f928e60 shell echo -n 1f76ec2bdd1cef8d95db95676fc591c3028e2835 >
/data/local/tmp/sky.com.linders.meet_station.sha1
[ +35 ms] executing: /home/admin/Android/Sdk/platform-tools/adb -s c0808941f928e60 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.linders.meet_station/com.linders.meet_station.MainActivity
[+1704 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.linders.meet_station/.MainActivity (has extras) }
[ ] Waiting for observatory port to be available...
[ +9 ms] Observatory URL on device: http://127.0.0.1:45859/IhRC5rC4nXY=/
[ +1 ms] executing: /home/admin/Android/Sdk/platform-tools/adb -s c0808941f928e60 forward tcp:0 tcp:45859
[ +10 ms] 37799
[ ] Forwarded host port 37799 to device port 45859 for Observatory
[ +7 ms] Caching compiled dill
[ +84 ms] Connecting to service protocol: http://127.0.0.1:37799/IhRC5rC4nXY=/
[ +3 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:37799/IhRC5rC4nXY=/.
[ +93 ms] Warning: Failed to start DDS: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received,
uri = http://127.0.0.1:37799/IhRC5rC4nXY=/ws
[ ] Fail to connect to service protocol: http://127.0.0.1:37799/IhRC5rC4nXY=/: DartDevelopmentServiceException: WebSocketChannelException:
WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:37799/IhRC5rC4nXY=/ws
[ +1 ms] Error connecting to the service protocol: failed to connect to http://127.0.0.1:37799/IhRC5rC4nXY=/
[ +3 ms] "flutter run" took 46,697ms.
[ +3 ms]
#0 throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1 RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)

#2 FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)

#3 FlutterCommand.run. (package:flutter_tools/src/runner/flutter_command.dart:986:27)

#4 AppContext.run. (package:flutter_tools/src/base/context.dart:150:19)

#5 AppContext.run (package:flutter_tools/src/base/context.dart:149:12)

#6 CommandRunner.runCommand (package:args/command_runner.dart:197:13)

#7 FlutterCommandRunner.runCommand. (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)

#8 AppContext.run. (package:flutter_tools/src/base/context.dart:150:19)

#9 AppContext.run (package:flutter_tools/src/base/context.dart:149:12)

#10 FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)

#11 run.. (package:flutter_tools/runner.dart:63:9)

#12 run. (package:flutter_tools/runner.dart:61:12)

#13 AppContext.run. (package:flutter_tools/src/base/context.dart:150:19)

#14 AppContext.run (package:flutter_tools/src/base/context.dart:149:12)

#15 runInContext (package:flutter_tools/src/context_runner.dart:70:10)

#16 main (package:flutter_tools/executable.dart:88:3)
[ +2 ms] Running shutdown hooks
[ ] Shutdown hook priority 4
[ +5 ms] Shutdown hooks complete
[ ] exiting with code 2

**Comment by fhuonder** [comment]
@janlinders 

Did you see my comment: https://github.com/flutter/flutter/issues/61604#issuecomment-739885494 ?

**Comment by janlinders** [comment]
@fhuonder 
Thx,. I did see your comment, but your setup is different (running a dev container)
I experience the problem connecting to a real device via USB ADB from Linux.
The Linux system is running Android Studio and I start the testing from within AS.
No command line flutter or anything.
Sometimes it keeps working for hours and then suddenly (still trying to figure out what i did) it stops working and need to reboot.
Until now, I cannot get a hold of the root cause

**Comment by fhuonder** [comment]
To all

This here https://github.com/flutter/flutter/issues/74084 applies here as well.
You have to set the "--dds-port" that it still works.

**Comment by sleshJdev** [comment]
> 
> 
> Hi all,
> 
> I have an update.
> I am currently working on Flutter version 1.24.0-7.0.pre and I got it working (almost).
> 
> I have to start flutter with `--host-vmservice-port 10388` and that it works I had to add a proxy like this
> 
> ```
> socat tcp-listen:10388,bind=127.0.0.1,fork tcp:host.docker.internal:10388
> ```
> 
> The proxy was needed because flutter tries to connect to the observatory on 127.0.0.1 and when running in a devcontainer (or wsl2) this is not the host machine where ADB runs and ADB opens a port forward from the host machine.
> It is still needed to make the ADB socket by having the environment variable `ADB_SERVER_SOCKET=tcp:host.docker.internal:5037`.
> 
> As soon as the emulator/device is started on windows flutter sees it (because of the ADB socket settings) and can then interact with it.
> 
> Still not working:
> Interacting with the emulators. The emulators (or devices) must be managed/started from Windows. It's not possible to start en emualtor (on Windows) from the devcontainer.
> 
> Maybe we are a step further?
> 
> Regards,
> Florian

Thanks for sharing this. I faced accross example the same proble with one except that I use WSL2. It's shame that flutter do not resolve this issue so long. 

Regardng your comment, may I ask what service/whatever should lister 10388 port on windows side? Can I use another port? Am I right that in case of WSL2, "host.docker.internal" it's ip address of host machine, i.e. Windows?

**Comment by fhuonder** [comment]
Hi @sleshJdev 

Port 10388: It is used by adb to open up the port on the device/emulator where the debugger connects to.
But this port is opened on Windows, where the device is attached. Therefore this port is in WSL/devcontainer opened and forwarded to Windows (with socat) because Flutter only accesses it on localhost. It's not possible to define the host. There is only the `--host-vmservice-port` flag.
You can choose any free port you'd like.

And yes `host.docker.internal` referes to the IP of the Windows machine.

Hope I could help you.
Regards,
Florian

**Comment by lattice0** [comment]
I am having this problem as well. The Android Emulator can't connect and keeps trying random ports that have nothing to do with the specific port on `--host-vmservice-port 10388`
