### ISSUE TITLE
Issue::  Unhandled Exception: NoSuchMethodError: The getter 'value' was called on null.

### ISSUE THREAD

**Issue by johnmelodyme** [flutter/flutter#61603]
```
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[   +7 ms] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1218:14)
[        ] flutter: #3      RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1195:5)
[        ] flutter: #4      RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1209:7)
[        ] flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
[        ] flutter: #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
[        ] flutter: #7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:880:20)
[        ] flutter: #8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
[        ] flutter: #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
[        ] flutter: #10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
[        ] flutter: #11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
[        ] flutter: #15     _invoke (dart:ui/hooks.dart:253:10)
[        ] flutter: #16     _drawFrame (dart:ui/hooks.dart:211:3)
[        ] flutter: (elided 5 frames from class _AssertionError and dart:async)
[        ] flutter: ```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-8.0.pre.125, on Mac OS X 10.15.4 19E287, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] VS Code (version 1.47.0)
 
[✓] Connected device (1 available)            

• No issues found!
```

**Comment by darshankawar** [comment]
Hi @johnmelodyme,
Please provide a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by johnmelodyme** [comment]
IT doesnot specify which line of my code is the error, but I got this instead 
```
lutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown attaching to the render tree:
flutter: 'package:flutter/src/widgets/binding.dart': Failed assertion: line 1218 pos 14: '_child != null': is
flutter: not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1218:14)
flutter: #3      RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1195:5)
flutter: #4      RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1209:7)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
flutter: #6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
flutter: #7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:880:20)
flutter: #8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #15     _invoke (dart:ui/hooks.dart:253:10)
flutter: #16     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ══════════════════════════════════════════════```

**Comment by darshankawar** [comment]
Hi @johnmelodyme,
You'll need to provide a minimal complete reproducible code sample that is throwing this issue. Without that, it'll be hard to know what exactly is causing this error.
