### ISSUE TITLE
java.lang.AssertionError: java.lang.NoSuchFieldException: DrawableResource

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#61615]
```
: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.AssertionError: java.lang.NoSuchFieldException: DrawableResource
E/flutter (25397): 	at c.a.a.y.n.n$j0.<init>(Unknown Source:87)
E/flutter (25397): 	at c.a.a.y.n.n$w.a(Unknown Source:29)
E/flutter (25397): 	at c.a.a.f.a(Unknown Source:74)
E/flutter (25397): 	at c.a.a.y.n.i.a(Unknown Source:42)
E/flutter (25397): 	at c.a.a.y.n.i.a(Unknown Source:123)
E/flutter (25397): 	at c.a.a.y.n.i.a(Unknown Source:22)
E/flutter (25397): 	at c.a.a.f.a(Unknown Source:74)
E/flutter (25397): 	at c.a.a.f.a(Unknown Source:4)
E/flutter (25397): 	at c.a.a.f.a(Unknown Source:8)
E/flutter (25397): 	at c.a.a.f.a(Unknown Source:5)
E/flutter (25397): 	at c.a.a.f.a(Unknown Source:13)
E/flutter (25397): 	at com.dexterous.flutterlocalnotifications.b.b(Unknown Source:4)
E/flutter (25397): 	at com.dexterous.flutterlocalnotifications.b.g(Unknown Source:19)
E/flutter (25397): 	at com.dexterous.flutterlocalnotifications.b.a(Unknown Source:169)
E/flutter (25397): 	at d.a.b.a.j$a.a(Unknown Source:17)
E/flutter (25397): 	at io.flutter.embedding.engine.b.b.a(Unknown Source:57)
E/flutter (25397): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (25397): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25397): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (25397): 	at android.os.Looper.loop(Looper.java:197)
E/flutter (25397): 	at android.app.ActivityThread.main(ActivityThread.java:8034)
E/flutter (25397): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25397): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/flutter (25397): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
E/flutter (25397): Caused by: java.lang.NoSuchFieldException: DrawableResource
E/flutter (25397): 	at java.lang.Class.getField(Class.java:1604)
E/flutter (25397): 	at c.a.a.y.n.n$j0.<init>(Unknown Source:34)
E/flutter (25397): 	... 23 more
E/flutter (25397):
F/flutter (25397): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)]
```

flutter run can work, flutter build apk got this break.

Also this error is sometime happen, sometimes not...

**Comment by VladyslavBondarenko** [comment]
Hi @jinfagang 
do last comments from https://github.com/flutter/flutter/issues/56019 help?

**Comment by jinfagang** [comment]
Yes, solved, thanks
