### ISSUE TITLE
[flutter_tools] `flutter update-packages --force-upgrade` broke create test

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#61687]
This was caused by https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/pubspec.yaml.tmpl#L49 hard-coding the test version. I fixed the breakage by manually updating the template, but this will break again someday.

https://cirrus-ci.com/task/5360493143523328

```
Exception: pub get failed (1; ---- End log transcript ----)
#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:334:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:218:15)
#3      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:680:17)
<asynchronous suspension>
#4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:435:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:872:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:750:33)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _runZoned (dart:async/zone.dart:1630:10)
#12     runZoned (dart:async/zone.dart:1550:10)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:739:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _runZoned (dart:async/zone.dart:1630:10)
#22     runZoned (dart:async/zone.dart:1550:10)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:282:19)
<asynchronous suspension>
#25     TestFlutterCommandRunner.runCommand.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter_tools/test/src/common.dart:388:25)
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#27     _rootRun (dart:async/zone.dart:1190:13)
#28     _CustomZone.run (dart:async/zone.dart:1093:19)
#29     _runZoned (dart:async/zone.dart:1630:10)
#30     runZoned (dart:async/zone.dart:1550:10)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#32     TestFlutterCommandRunner.runCommand (file:///tmp/flutter%20sdk/packages/flutter_tools/test/src/common.dart:384:20)
#33     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#34     new Future.sync (dart:async/future.dart:223:31)
#35     CommandRunner.run (package:args/command_runner.dart:112:14)
#36     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#37     _createProject (file:///tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:1959:16)
#38     _createAndAnalyzeProject (file:///tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:1987:9)
#39     main.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter_tools/test/commands.shard/permeable/create_test.dart:535:12)
```

**Comment by zanderso** [comment]
Should the test package version be an input to the template?

**Comment by jonahwilliams** [comment]
The only fix here would be to dynamically generate the template based on the test version - that seems like way more work than just updating the version when this test fails.

The test keeps us from getting out of sync, and that seems good enough to me.

**Comment by christopherfujino** [comment]
> The only fix here would be to dynamically generate the template based on the test version - that seems like way more work than just updating the version when this test fails.
> 
> The test keeps us from getting out of sync, and that seems good enough to me.

makes sense, closing.
