### ISSUE TITLE
Crash while TabBar is used outside of AppBar

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter#6169]
## Steps to Reproduce

Playing around with some widgets, I came across some unexpected behavior.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
      new MaterialApp(
          title: 'Flutter Demo',
          theme: new ThemeData(
              primarySwatch: Colors.blue,
              ),
          home: new FlutterDemo(),
          ),
      );
}

class FlutterDemo extends StatefulWidget {
  FlutterDemo({Key key}) : super(key: key);

  @override
  _FlutterDemoState createState() => new _FlutterDemoState();
}

enum TestTab { one, two }

class _FlutterDemoState extends State<FlutterDemo> {

  Widget _buildTab(BuildContext context, TestTab tab) {
    return new Center(
        child: new Text(tab == TestTab.one ? 'one' : 'two')
    );
  }

  @override
  Widget build(BuildContext context) {
    return new TabBarSelection<TestTab>(
        values: <TestTab>[TestTab.one, TestTab.two],
        child: new Scaffold(
            body: new Column(
                children: [
                  new TabBar<TestTab>(
                      labels: <TestTab, TabLabel> {
                        TestTab.one: new TabLabel(text: "one"),
                        TestTab.two: new TabLabel(text: "two"),
                      }
                  ),
                  new TabBarView<TestTab>(
                      children: <Widget>[
                        _buildTab(context, TestTab.one),
                        _buildTab(context, TestTab.two),
                      ]
                  )
                ],
            )
        )
    );
  }

}
```

The above code produces the following (the tabs are hard to see at the top as they are white):
<img width="642" alt="screen shot 2016-10-02 at 11 50 08 pm" src="https://cloud.githubusercontent.com/assets/871169/19027176/de1d9f66-88fb-11e6-8955-de093039ec9a.png">

The tab bar is drawn at the top as expected, but whats unexpected is the giant red bar at the bottom of the screen. Also if I horizontal swipe or press a tab I get an error screen:
<img width="642" alt="screen shot 2016-10-02 at 11 50 45 pm" src="https://cloud.githubusercontent.com/assets/871169/19027204/242b6ab0-88fc-11e6-8936-248ff9880808.png">

Everything works as expected though if the `TabBar` is a child of an `AppBar`:

```dart
enum TestTab { one, two }

class _FlutterDemoState extends State<FlutterDemo> {

  Widget _buildTab(BuildContext context, TestTab tab) {
    return new Center(
        child: new Text(tab == TestTab.one ? 'one' : 'two')
    );
  }

  @override
  Widget build(BuildContext context) {
    return new TabBarSelection<TestTab>(
        values: <TestTab>[TestTab.one, TestTab.two],
        child: new Scaffold(
            appBar: new AppBar(
                bottom: new TabBar<TestTab>(
                    labels: <TestTab, TabLabel> {
                      TestTab.one: new TabLabel(text: "one"),
                      TestTab.two: new TabLabel(text: "two"),
                    }
                )),
            body: new TabBarView<TestTab>(
                children: <Widget>[
                  _buildTab(context, TestTab.one),
                  _buildTab(context, TestTab.two),
                ]
            )
        )
    );
  }

}
```

## Flutter Doctor

```
flutter doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Volumes/MacintoshHD/Users/spierce7/frameworks/flutter
    • Framework revision 4c1e4a24ae (10 days ago), 2016-09-23 08:52:10
    • Engine revision 3551e7a48e
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
    • Android SDK at /Volumes/MacintoshHD/Users/spierce7/Android/sdk
    • Platform android-24, build-tools 24.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

[-] iOS toolchain - develop for iOS devices
    x XCode not installed; this is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[x] Atom - a lightweight development environment for Flutter
    x Atom not installed; download at https://atom.io.

[✓] Connected devices
    • Google Nexus 5X, 6 0 0, API 23, 1080x1920 • 192.168.56.101:5555 • android-x86
```

## Logs and Crash Reports

```
I/flutter : Another exception was thrown: RenderSemanticsGestureHandler object was given an infinite size during layout.
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/virtual_viewport.dart': Failed assertion: line 196: 'base != null' is not true.
I/flutter : Another exception was thrown: RenderSemanticsGestureHandler object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderList object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderIgnorePointer object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderPointerListener object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderSemanticsGestureHandler object was given an infinite size during layout.
I/flutter : Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1516: '!_debugDoingThisLayout' is not true.
```

**Comment by Hixie** [comment]
The log that you want is the one immediately prior to the first "Another exception was thrown".

The red at the bottom of the screen is https://github.com/flutter/flutter/issues/2387

**Comment by ScottPierce** [comment]
```
spierce7$ flutter logs
Showing Google Nexus 5X, 6 0 0, API 23, 1080x1920 logs:
--------- beginning of main
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/virtual_viewport.dart': Failed assertion: line 196: 'base != null' is not true.
I/flutter : Another exception was thrown: RenderSemanticsGestureHandler object was given an infinite size during layout.
```

**Comment by Hixie** [comment]
Try using `flutter run`, it should give you the logs from the start of the app. `flutter logs` is prone to missing logs between when the application starts and when you run `flutter logs`.

Alternatively if you're using an IDE to launch the app look for the logs in the IDE itself, or run `flutter logs` before you start the app from the IDE.

**Comment by ScottPierce** [comment]
So using `flutter run` I got a much more useful stacktrace. I was using `flutter listen` to play around. 

Why wouldn't I get these exceptions while using `flutter listen`? Is `flutter run` the only way to get these exceptions?

The exception seems to indicate it's an issue probably with how I've configured the layout, allowing something to have an infinite size that shouldn't. I'm not familiar enough with flutter yet to determine what I'm setting incorrectly. This can probably be closed and accounted to user error :-)

```
flutter run --no-hot
Running lib/main.dart on Google Nexus 5X, 6 0 0, API 23, 1080x1920...
--------- beginning of system
Observatory listening on http://127.0.0.1:51029
Diagnostic server listening on http://127.0.0.1:51033
Exception from flutter run: Class 'IOWebSocketChannel' has no instance method 'cast'.

NoSuchMethodError: method not found: 'cast'
Receiver: Instance of 'IOWebSocketChannel'
Arguments: []
dart:core                                                         Object.noSuchMethod
package:flutter_tools/src/vmservice.dart 29                       VMService.connect.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/vmservice.dart 34                       VMService.connect.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/vmservice.dart                          VMService.connect
package:flutter_tools/src/resident_runner.dart 106                ResidentRunner.connectToServiceProtocol.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/resident_runner.dart                    ResidentRunner.connectToServiceProtocol
package:flutter_tools/src/run.dart 180                            RunAndStayResident._run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/android/android_device.dart 342         AndroidDevice.startBundle.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/android/android_device.dart 259         AndroidDevice._forwardPort.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/android/android_device.dart 788         _AndroidDevicePortForwarder.forward.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/run.dart                                RunAndStayResident._run
package:flutter_tools/src/run.dart 49                             RunAndStayResident.run.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/run.dart 48                             RunAndStayResident.run
package:flutter_tools/src/commands/run.dart 194                   RunCommand.runCommand.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/run.dart                       RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 61                        pubGet.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 122                   RunCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 199         FlutterCommand.findTargetDevice.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 70                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 71                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 97                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 91                          main.<async>

I/flutter : ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown during performLayout():
I/flutter : RenderList object was given an infinite size during layout.
I/flutter : This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter : inside another render object that allows its children to pick their own size.
I/flutter : The nearest ancestor providing an unbounded height constraint is:
I/flutter :   RenderFlex NEEDS-LAYOUT
I/flutter :   creator: Column ← LayoutId-['_ScaffoldSlot.body'] ← CustomMultiChildLayout ← DefaultTextStyle ←
I/flutter :   AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey ink renderer] ←
I/flutter :   NotificationListener<LayoutChangedNotification> ← DecoratedBox ← Container ← DecoratedBox ← ⋯
I/flutter :   parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body
I/flutter :   constraints: BoxConstraints(w=0.0, h=0.0)
I/flutter :   size: MISSING
I/flutter :   direction: Axis.vertical
I/flutter :   mainAxisAlignment: MainAxisAlignment.start
I/flutter :   mainAxisSize: MainAxisSize.max
I/flutter :   crossAxisAlignment: CrossAxisAlignment.center
I/flutter :   textBaseline: null
I/flutter : The constraints that applied to the RenderList were:
I/flutter :   BoxConstraints(w=0.0, 0.0<=h<=Infinity)
I/flutter : The exact size it was given was:
I/flutter :   Size(0.0, Infinity)
I/flutter : See https://flutter.io/layout/ for more information.
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1104)
I/flutter : #2      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1063)
I/flutter : #3      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:967)
I/flutter : #5      RenderBox.size= (package:flutter/src/rendering/box.dart:967)
I/flutter : #6      RenderList.performLayout (package:flutter/src/rendering/list.dart:150)
I/flutter : #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #8      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #10     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #12     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #14     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:457)
I/flutter : #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #16     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:72)
I/flutter : #17     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:103)
I/flutter : #18     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:142)
I/flutter : #19     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:281)
I/flutter : #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #21     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #33     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #34     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2102)
I/flutter : #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #38     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:354)
I/flutter : #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #40     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #42     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #44     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #46     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #48     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:91)
I/flutter : #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1571)
I/flutter : #50     RenderView.performLayout (package:flutter/src/rendering/view.dart:113)
I/flutter : #51     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1448)
I/flutter : #52     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:897)
I/flutter : #53     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:207)
I/flutter : #54     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:297)
I/flutter : #55     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:152)
I/flutter : #56     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:608)
I/flutter : #57     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:543)
I/flutter : #58     runApp (package:flutter/src/widgets/binding.dart:368)
I/flutter : #59     main (/Users/spierce7/workspace/WMBA/dart/alpha-bible/lib/main.dart:4)
I/flutter : #60     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
I/flutter : #61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
I/flutter : (elided 2 frames from class _AssertionError)
I/flutter : The following RenderObject was being processed when the exception was fired:
I/flutter :   RenderList relayoutBoundary=up4 NEEDS-LAYOUT
I/flutter : This RenderObject had the following creator information:
I/flutter :   PageViewport ← IgnorePointer ← Listener ← _GestureSemantics ← RawGestureDetector-[GlobalKey
I/flutter :   754518352] ← TabBarView<TestTab> ← Column ← LayoutId-['_ScaffoldSlot.body'] ←
I/flutter :   CustomMultiChildLayout ← DefaultTextStyle ← ⋯
I/flutter : This RenderObject has no descendants.
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter : Another exception was thrown: RenderIgnorePointer object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderPointerListener object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderSemanticsGestureHandler object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderList object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderIgnorePointer object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderPointerListener object was given an infinite size during layout.
I/flutter : Another exception was thrown: RenderSemanticsGestureHandler object was given an infinite size during layout.
```

**Comment by Hixie** [comment]
Wow, I didn't know we still had `flutter listen`. We will remove it. It's redundant with `flutter run` these days.

That exception log indicates that the problem is that you're putting a vertical list (which tries to be as tall as possible then scrolls its children within that vertical space) inside a vertical flex (which tries to make its children as tall as they can be, then stacks them). Put a `Flexible` around the list to indicate that the list should just use the remaining space instead.

**Comment by ScottPierce** [comment]
@Hixie so with `flutter run` I get different results:

My screen ends up stuck here:
<img width="642" alt="screen shot 2016-10-03 at 5 39 20 pm" src="https://cloud.githubusercontent.com/assets/871169/19055103/60e94406-8990-11e6-88b3-815f12bb30a9.png">


```
flutter run
Launching loader on Google Nexus 5X, 6 0 0, API 23, 1080x1920...
--------- beginning of main
Observatory listening on http://127.0.0.1:52685
Diagnostic server listening on http://127.0.0.1:52688
Exception from flutter run: Class 'IOWebSocketChannel' has no instance method 'cast'.

NoSuchMethodError: method not found: 'cast'
Receiver: Instance of 'IOWebSocketChannel'
Arguments: []
dart:core                                                         Object.noSuchMethod
package:flutter_tools/src/vmservice.dart 29                       VMService.connect.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/vmservice.dart 34                       VMService.connect.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/vmservice.dart                          VMService.connect
package:flutter_tools/src/resident_runner.dart 106                ResidentRunner.connectToServiceProtocol.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/resident_runner.dart                    ResidentRunner.connectToServiceProtocol
package:flutter_tools/src/hot.dart 246                            HotRunner._run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/android/android_device.dart 342         AndroidDevice.startBundle.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/android/android_device.dart 259         AndroidDevice._forwardPort.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/android/android_device.dart 788         _AndroidDevicePortForwarder.forward.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/hot.dart                                HotRunner._run
package:flutter_tools/src/hot.dart 147                            HotRunner.run.<fn>
dart:async                                                        runZoned
package:flutter_tools/src/hot.dart 146                            HotRunner.run
package:flutter_tools/src/commands/run.dart 194                   RunCommand.runCommand.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/commands/run.dart                       RunCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 61                        pubGet.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/commands/run.dart 122                   RunCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/runner/flutter_command.dart 199         FlutterCommand.findTargetDevice.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 70                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/run.dart                       RunCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 176                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 129                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 71                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 103                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 103                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 97                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 91                          main.<async>
```

**Comment by Hixie** [comment]
Try updating to tip of tree. The IOWebSocketChannel.cast issue should be solved as of https://github.com/flutter/flutter/pull/6153.
