### ISSUE TITLE
Fuchsia_ctl recipe fails if not git_url is passed as a property

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#61694]
Link to builder:
https://ci.chromium.org/p/flutter/builders/try/recipes-with-led/b8874560370454578144?

```
Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 554, in run_steps
    raw_result = recipe_obj.run_steps(api, engine)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/recipe_deps.py", line 733, in run_steps
    properties_def, api=api)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 89, in invoke_with_properties
    arg_names, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 52, in _invoke_with_properties
    return callable_obj(*props, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/fuchsia_ctl.py", line 32, in RunSteps
    api.properties['git_url'],
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_modules/properties/api.py", line 46, in __getitem__
    return self._properties[key]
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/types.py", line 98, in __getitem__
    return self._d[key]
KeyError: 'git_url'```

**Comment by godofredoc** [comment]
This is blocking the rolls of recipe dependencies.

**Comment by godofredoc** [comment]
Here is an example:

https://flutter-review.googlesource.com/c/recipes/+/4401

**Comment by digiter** [comment]
This is fixed.
