### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\Nana Konadu\Desktop\flutterF\new_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by MirangelNanakonadu** [flutter/flutter#61692]
## Command
```
flutter create new_app
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\Nana Konadu\Desktop\flutterF\new_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:227:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#6      Template.render (package:flutter_tools/src/template.dart:153:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:630:21)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version
    10.0.18362.900], locale en-US)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Nana Konadu\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Users\Nana Konadu\Desktop\intellij\IntelliJ IDEA Community
      Edition 2019.2.4
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761

[✓] VS Code (version 1.47.2)
    • VS Code at C:\Users\Nana Konadu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SM T285 • 52007b41ec123500 • android-arm • Android 5.1.1 (API 22)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Related to [60283](https://github.com/flutter/flutter/issues/60283), [59637](https://github.com/flutter/flutter/issues/59637) and [50539](https://github.com/flutter/flutter/issues/50539)

**Comment by darshankawar** [comment]
Hi @MirangelNanakonadu,
I see there's a similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
