### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, path = '/root/.pub-cache/hosted/pub.dartlang.org/flutter_template_images-1.0.0/lib/' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by mjlalani** [flutter/flutter#61716]
## Command
```
flutter create testa
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Exists failed, path = '/root/.pub-cache/hosted/pub.dartlang.org/flutter_template_images-1.0.0/lib/' (OS Error: Permission denied, errno = 13)
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#2      _templateImageDirectory (package:flutter_tools/src/template.dart:253:79)
#3      Template.fromName (package:flutter_tools/src/template.dart:63:38)
#4      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:629:46)
#5      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:543:29)
#6      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:380:37)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#15     FlutterProject.organizationNames (package:flutter_tools/src/project.dart)
#16     _rootRunUnary (dart:async/zone.dart:1192:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_IN)
    • Flutter version 1.17.5 at /opt/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/rivigo/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /home/rivigo/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/rivigo/Downloads/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Hi @mjlalani,
I see there's a similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
I am going ahead and closing this as a duplicate. I'd suggest you follow-up in that issue for updates.
If you disagree, write in comments and I'll reopen.
Thanks.
