### ISSUE TITLE
Compiler nor Android Studio doesn't flag incorrect createState() method

### ISSUE THREAD

**Issue by Tahfimul** [flutter/flutter#61732]
## Steps to Reproduce

1. Create a class for a stateless widget in Android Studio 4.0
2. Inherit the StatelessWidget class. But do not write the createState() method.
3. Android Studio flags that the class is missing createState method of the StatelessWidget parent class.
4. Click on flag and hit `ALT+ENTER`
5. select `create missing override(s)`
6. Android Studio should then add the following method:
       
          @override 

          State<StatefulWidget> createState() 
          {
              // TODO: implement createState
              throw UnimplementedError();
          }
7. Create a state class inheriting the State class with the Widget class as the T object like so:
      ` class StateClass extends State<WIDGET_CLASS>`

8. Modify overridden method in Widget Class like so:     
          
          @override

          State<StatefulWidget> createState() 
          {
             new StateClass();
          }
          
        
**Expected results:** 

I expected to see the StatefulWidget inflated in my Activity View.

 **Additional Comments:** The compiler did not flag the issue being around the createState() method implementation in addition Android Studio suggested an implementation that is not in line with the documentations (such as [(https://flutter.dev/docs/get-started/flutter-for/android-devs)]), given I am using the latest Flutter version and Android Studio version. My solution was to implement the createState() method as per the documentations. 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
Showing Android SDK built for x86 logs:
I/flutter ( 9939): MainActivity
I/flutter ( 9939): TopMenu
I/flutter ( 9939): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9939): The following NoSuchMethodError was thrown building TopMenu:
I/flutter ( 9939): The method '_debugTypesAreRight' was called on null.
I/flutter ( 9939): Receiver: null
I/flutter ( 9939): Tried calling: _debugTypesAreRight(Instance of 'MainBar')
I/flutter ( 9939): 
I/flutter ( 9939): The relevant error-causing widget was:
I/flutter ( 9939):   TopMenu $DIR/flutter_app/lib/main.dart:132:16
I/flutter ( 9939): 
I/flutter ( 9939): When the exception was thrown, this was the stack:
I/flutter ( 9939): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 9939): #1      new StatefulElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:4594:19)
I/flutter ( 9939): #2      new StatefulElement (package:flutter/src/widgets/framework.dart:4605:6)
I/flutter ( 9939): #3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:894:38)
I/flutter ( 9939): ...     Normal element mounting (171 frames)
I/flutter ( 9939): #174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter ( 9939): #175    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter ( 9939): ...     Normal element mounting (253 frames)
I/flutter ( 9939): #428    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter ( 9939): #429    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter ( 9939): #430    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
I/flutter ( 9939): #431    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
I/flutter ( 9939): #432    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
I/flutter ( 9939): #433    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter ( 9939): #434    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
I/flutter ( 9939): #435    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
I/flutter ( 9939): #436    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
I/flutter ( 9939): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter ( 9939): 
I/flutter ( 9939): ════════════════════════════════════════════════════════════════════════════════════════════════════

```
```

 [✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.5 at $DIR
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at $DIR
    • Platform android-29, build-tools 29.0.3
    • Java binary at: $DIR
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at $DIR
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 3.6)
    • Android Studio at $DIR
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0
      (API 26) (emulator)

! Doctor found issues in 1 category.


```
</details>

**Comment by VladyslavBondarenko** [comment]
@Tahfimul 
Android Studio highlights the issue
![image](https://user-images.githubusercontent.com/17024977/87922629-ec77f600-ca84-11ea-844e-974a37f9b1ac.png)

Do you expect to see clear description of the exception?

Could you provide the example about 

> Android Studio suggested an implementation that is not in line with the documentations (such as [(https://flutter.dev/docs/get-started/flutter-for/android-devs)])

?

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
