### ISSUE TITLE
[tool_crash] TemplateException - Value was missing for section tag: androidX. (3:1){{#androidX}}^

### ISSUE THREAD

**Issue by gkodikara** [flutter/flutter#61765]
When running "flutter create project_name" or getting more specific as I have done in the latest log

## Command
```
flutter create --androidx -t app --org com.companyname.packagename -a kotlin -i swift myapp
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
TemplateException: Value was missing for section tag: androidX. (3:1)
{{#androidX}}
^

```
#0      Renderer._renderSection (package:mustache_template/src/renderer.dart:135:9)
#1      Renderer.visitSection (package:mustache_template/src/renderer.dart:113:7)
#2      SectionNode.accept (package:mustache_template/src/node.dart:66:43)
#3      Renderer.render.<anonymous closure> (package:mustache_template/src/renderer.dart:52:30)
#4      List.forEach (dart:core-patch/growable_array.dart:282:8)
#5      Renderer.render (package:mustache_template/src/renderer.dart:52:13)
#6      Template.render (package:mustache_template/src/template.dart:42:14)
#7      Template.renderString (package:mustache_template/src/template.dart:34:5)
#8      MustacheTemplateRenderer.renderString (package:flutter_tools/src/build_runner/mustache_template.dart:15:67)
#9      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:217:66)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#11     Template.render (package:flutter_tools/src/template.dart:153:24)
#12     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:630:21)
#13     _rootRunUnary (dart:async/zone.dart:1192:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.5 19F101, locale en-AU)
    • Flutter version 1.17.0 at /Users/gregkodikara/Documents/development/flutter/flutter
    • Framework revision e6b34c2b5c (3 months ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/gregkodikara/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29)
      (emulator)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment]
Executing `flutter create --androidx -t app --org com.companyname.packagename -a kotlin -i swift myapp` on latest stable has no issue 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.17.5 at /Users/taha/Code/flutter_stable
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (2 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64 • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios           • iOS 13.6

• No issues found!
```

</details>

**Comment by jmagman** [comment]
I thought this was removed from the templates in https://github.com/flutter/flutter/pull/52340 (v1.15.20).
What's the output of:
```
$ cd /path/to/flutter/sdk
$ git status
```

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
