### ISSUE TITLE
null assertion error thrown from hooks.dart when enabling --null_assertions

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#61770]
The stack trace is:

```
Installing build\app\outputs\flutter-apk\app.apk...                 3.1s
E/flutter (25674): [ERROR:flutter/shell/common/shell.cc(209)] Dart Unhandled Exception: #0      _AssertionError._doThrowNewSource (dart:core-patch/errors_patch.dart:48:45)
E/flutter (25674): #1      _AssertionError._throwNewNullAssertion (dart:core-patch/errors_patch.dart:42:5)
E/flutter (25674): #2      _startMainIsolate (dart:isolate-patch/isolate_patch.dart:232:58)
E/flutter (25674): #3      _runMainZoned (dart:ui/hooks.dart:224:27)
```

which is https://github.com/flutter/engine/blob/master/lib/ui/hooks.dart#L224

This is either a bug in the definition of startMainIsolateFunction or in hooks.dart

**Comment by jonahwilliams** [comment]
Potential fix is https://dart-review.googlesource.com/c/sdk/+/154833

**Comment by jonahwilliams** [comment]
Waiting on engine roll to confirm

**Comment by chinmaygarde** [comment]
@jonahwilliams I am bumping the milestone for this as the month is out. Please re-adjust as necessary.

**Comment by jonahwilliams** [comment]
This actually rolled, marking as fixed
