### ISSUE TITLE
Unhandled exception while printing value using box.get() | Hive

### ISSUE THREAD

**Issue by himanshunikhare** [flutter/flutter#61798]
## Steps to Reproduce

The application is raising an exception whenever I am trying to print a Hive object in my flutter application. 
Line which is raising this exeption is:

```
 Box box = await Hive.openBox('Reservation');
 print("INSIDE BOX RESERVATION LIST ${await box.get('roomId')}");
 return box;
```

my model is:
```
@HiveType(typeId: 3)
class Reservation extends HiveObject {
  @HiveField(0)
  final List<String> listKeys;
  @HiveField(1)
  String roomId;
  @HiveField(2)
  String staffId;
  @HiveField(3)
  String bookingMode;
  @HiveField(4)
  DateTime bookingStartTime;
  @HiveField(5)
  DateTime bookingEndTime;
  @HiveField(6)
  DateTime bookingDate;
  @HiveField(7)
  String groupSize;
  @HiveField(8)
  String bookingId;
  @HiveField(9)
  String status;
  @HiveField(10)
  String amount;
  @HiveField(11)
  String instrumentAmount;
  @HiveField(12)
  String statusDescription;
  @HiveField(13)
  String bookedByAdmin;
  @HiveField(14)
  DateTime createdAt;
  @HiveField(15)
  DateTime updatedAt;
  @HiveField(16)
  String checksComplete;
  @HiveField(17)
  int totalHours;
  Reservation(
    this.listKeys,
    this.roomId,
    this.staffId,
    this.bookingMode,
    this.bookingStartTime,
    this.bookingEndTime,
    this.bookingDate,
    this.groupSize,
    this.bookingId,
    this.status,
    this.amount,
    this.instrumentAmount,
    this.statusDescription,
    this.bookedByAdmin,
    this.createdAt,
    this.updatedAt,
    this.checksComplete,
    this.totalHours,
);
}
```

and I am storing values in my database like this:
```

//Get Customer Details
Future<Response> getReservation(String token) async {
  try {
    print(token);
    dio.options.headers['content-Type'] = 'application/json';
    dio.options.headers["authorization"] = token;
    Response response = await dio.get(bookingHistoryAPI);
    print(response.statusCode);
    DateTime now = DateTime.now();
    int day = now.day;
    int hour = now.hour;
    print("BOOKING RESPONSE");
    print(response.data);
    final list = ['roomId','staffId', 'bookingMode','bookingStartTime', 'bookingEndTime', 'bookingDate', 'groupSize', 'bookingId', 'status',
      'amount', 'instrumentAmount', 'statusDescription', 'bookedByAdmin', 'createdAt', 'updatedAt', 'checksComplete', 'totalHours'];
    List result = response.data['bookings'];
    int totalCount = response.data['total_count'];
  
    await result.forEach((data) async {
      print('Data is   -->  ${data}');
      final res = await Reservation(
        list,
        data['room_id'],
        data['staff_id'],
        data['booking_mode'],
        DateTime.parse(data['booking_start_time']),
        DateTime.parse(data['booking_end_time']),
        DateTime.parse(data['booking_date']),
        data['group_size_type'],
        data['booking_id'],
        data['status'],
        data['amount'],
        data['instrument_amount'],
        data['status_description'],
        data['booked_by_admin'].toString(),
        DateTime.parse(data['created_at']),
        DateTime.parse(data['updated_at']),
        data['checks_complete'].toString(),
        data['total_hours'],
      );
      await sdb.storeReservation(res);
    });
//    end
    return response;
  } catch (e) {
    print(e);
    return e.response;
  }
}

```

<details>
  <summary>Logs</summary>

```
[  +30 ms] E/flutter ( 9699): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.
[        ] E/flutter ( 9699): #0      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:249:7)
[        ] E/flutter ( 9699): #1      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:17:26)
[        ] E/flutter ( 9699): #2      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:41:12)
[        ] E/flutter ( 9699): <asynchronous suspension>
[        ] E/flutter ( 9699): #3      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:82:30)
[        ] E/flutter ( 9699): <asynchronous suspension>
[        ] E/flutter ( 9699): #4      BoxBaseImpl.initialize (package:hive/src/box/box_base_impl.dart:90:20)
[        ] E/flutter ( 9699): #5      HiveImpl._openBox (package:hive/src/hive_impl.dart:90:17)
[        ] E/flutter ( 9699): <asynchronous suspension>
[        ] E/flutter ( 9699): #6      HiveImpl.openBox (package:hive/src/hive_impl.dart:111:18)
[        ] E/flutter ( 9699): #7      _loadData (package:cloud9_app/views/pages/Dashboard/ReservationList.dart:4:24)
[        ] E/flutter ( 9699): #8      ReservationList (package:cloud9_app/views/pages/Dashboard/ReservationList.dart:9:21)
[        ] E/flutter ( 9699): #9      DashboardWidget (package:cloud9_app/views/pages/Dashboard/DashboardWidget.dart:111:24)
[        ] E/flutter ( 9699): #10     _DashboardPageState.build (package:cloud9_app/views/pages/Dashboard/Dashboard.dart:72:32)
[        ] E/flutter ( 9699): #11     StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
[        ] E/flutter ( 9699): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
[        ] E/flutter ( 9699): #13     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] E/flutter ( 9699): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] E/flutter ( 9699): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
[        ] E/flutter ( 9699): #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
[        ] E/flutter ( 9699): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
[        ] E/flutter ( 9699): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
[        ] E/flutter ( 9699): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
[        ] E/flutter ( 9699): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
[        ] E/flutter ( 9699): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
[        ] E/flutter ( 9699): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
[        ] E/flutter ( 9699): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] E/flutter ( 9699): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] E/flutter ( 9699): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
[        ] E/flutter ( 9699): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
[        ] E/flutter ( 9699): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
[        ] E/flutter ( 9699): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
[        ] E/flutter ( 9699): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
[        ] E/flutter ( 9699): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
[        ] E/flutter ( 9699): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
[        ] E/flutter ( 9699): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
[        ] E/flutter ( 9699): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
[        ] E/flutter ( 9699): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
[        ] E/flutter ( 9699): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] E/flutter ( 9699): #36     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] E/flutter ( 9699): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] E/flutter ( 9699): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
[        ] E/flutter ( 9699): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
[        ] E/flutter ( 9699): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
[        ] E/flutter ( 9699): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
[        ] E/flutter ( 9699): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
[        ] E/flutter ( 9699): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
[        ] E/flutter ( 9699): #44     Element.inflateWidget (package:flutter/src/widgets/f
[ +353 ms] I/flutter ( 9699): 200

```

```
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_IN)
    • Flutter version 1.17.5 at /home/thevagrantcoder/development/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/thevagrantcoder/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/90/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /home/thevagrantcoder/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • HD1901 • 542ae46e • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.```

</details>

**Comment by darshankawar** [comment]
Hi @himanshunikhare,
This seem to be an issue with the 3rd party plugin you are using in the app, Hive. I'd suggest you file this issue against that repo (https://github.com/hivedb/hive/issues) and follow-up there for updates.
Closing this, as this doesn't seem to be issue with Flutter. Iif you disagree, write in comments and I'll reopen.
Thanks.
