### ISSUE TITLE
Add supported platforms to plugin: Unable to get Xcode project information 

### ISSUE THREAD

**Issue by namniav** [flutter/flutter#61805]
Runing `flutter create -t plugin .` in a plugin project always throws 
> Unable to get Xcode project information: 
> xcodebuild: error: The directory /path/to/my_plugin/ios does not contain an Xcode project, workspace or package.

, even with `--platforms=<no matter which platform>` specified.

## Steps to Reproduce

1. `flutter channel master`
2. `flutter upgrade`
3. `flutter config --enable-macos-desktop`
4. `flutter create -t plugin my_plugin`
5. `cd my_plugin`
6. `flutter create -t plugin .` or `flutter create -t plugin --platforms <no matter which platform> .`

## Logs

1. `flutter --verbose channel master`
```
[  +38 ms] git: Already on 'master'
[ +122 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 54c9441723ec61baaeb0fbf71fdcf4e415116e6e
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git tag --contains HEAD
[ +172 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.21.0-1.0.pre-66-g54c9441723
[   +9 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[+3596 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +6 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E2269
[  +43 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +20 ms] Switching to flutter channel 'master'...
[   +1 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git fetch
[+3868 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git show-ref --verify --quiet refs/heads/master
[  +16 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git checkout master --
[   +2 ms] git: Your branch is up to date with 'origin/master'.
[   +3 ms] Successfully switched to flutter channel 'master'.
[        ] To ensure that you're on the latest build from this channel, run 'flutter upgrade'
[   +9 ms] "flutter channel" took 3,984ms.
[ +263 ms] ensureAnalyticsSent: 256ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

2. `flutter --verbose upgrade`
```
[ +124 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 54c9441723ec61baaeb0fbf71fdcf4e415116e6e
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git tag --contains HEAD
[ +165 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.21.0-1.0.pre-66-g54c9441723
[  +28 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +4 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E2269
[  +54 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git tag --contains HEAD
[ +148 ms] Exit code 0 from: git tag --contains HEAD
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.21.0-1.0.pre-66-g54c9441723
[   +3 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git fetch --tags
[+3268 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --verify @{u}
[  +13 ms] 54c9441723ec61baaeb0fbf71fdcf4e415116e6e
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] Flutter is already up to date on channel master
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 26 hours ago
[  +16 ms] Flutter 1.21.0-2.0.pre.66 • channel master • https://github.com/flutter/flutter.git
           Framework • revision 54c9441723 (26 hours ago) • 2020-07-17 18:56:12 -0400
           Engine • revision d327828632
           Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)
[   +9 ms] "flutter upgrade" took 3,539ms.
[ +263 ms] ensureAnalyticsSent: 258ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

3. `flutter --verbose config --enable-macos-desktop`
```
[ +123 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 54c9441723ec61baaeb0fbf71fdcf4e415116e6e
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git tag --contains HEAD
[ +155 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.21.0-1.0.pre-66-g54c9441723
[   +8 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +55 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +6 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E2269
[  +61 ms] Setting "enable-macos-desktop" value to "true".
[        ] 
           You may need to restart any open editors for them to read new settings.
[  +11 ms] "flutter config" took 32ms.
[   +6 ms] ensureAnalyticsSent: 4ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

4. `flutter create -t plugin my_plugin`
The large verbose output: [flutter_create_verbose_log_1.txt](https://github.com/flutter/flutter/files/4943116/flutter_create_verbose_log_1.txt)
```
Creating project my_plugin...
The plugin project was generated without specifying the `--platforms` flag, no new platforms are added.
To add platforms, run `flutter create -t plugin --platforms <platforms> .` under the same
directory. You can also find detailed instructions on how to add platforms in the `pubspec.yaml` at https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms.

  my_plugin/LICENSE (created)
  my_plugin/ios/.gitignore (created)
  my_plugin/ios/Assets/.gitkeep (created)
  my_plugin/test/my_plugin_test.dart (created)
  my_plugin/my_plugin.iml (created)
  my_plugin/.gitignore (created)
  my_plugin/.metadata (created)
  my_plugin/pubspec.yaml (created)
  my_plugin/README.md (created)
  my_plugin/ios/my_plugin.podspec (created)
  my_plugin/ios/Classes/MyPlugin.m (created)
  my_plugin/ios/Classes/SwiftMyPlugin.swift (created)
  my_plugin/ios/Classes/MyPlugin.h (created)
  my_plugin/lib/my_plugin.dart (created)
  my_plugin/.idea/runConfigurations/example_lib_main_dart.xml (created)
  my_plugin/.idea/libraries/Dart_SDK.xml (created)
  my_plugin/.idea/modules.xml (created)
  my_plugin/.idea/workspace.xml (created)
  my_plugin/CHANGELOG.md (created)
Running "flutter pub get" in my_plugin...                           1.1s
  my_plugin/example/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  my_plugin/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  my_plugin/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  my_plugin/example/ios/Runner/Info.plist (created)
  my_plugin/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  my_plugin/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  my_plugin/example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  my_plugin/example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  my_plugin/example/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  my_plugin/example/ios/Runner/Base.lproj/Main.storyboard (created)
  my_plugin/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  my_plugin/example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  my_plugin/example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  my_plugin/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  my_plugin/example/ios/Flutter/Debug.xcconfig (created)
  my_plugin/example/ios/Flutter/Release.xcconfig (created)
  my_plugin/example/ios/Flutter/AppFrameworkInfo.plist (created)
  my_plugin/example/ios/.gitignore (created)
  my_plugin/example/test/widget_test.dart (created)
  my_plugin/example/my_plugin_example.iml (created)
  my_plugin/example/.gitignore (created)
  my_plugin/example/.metadata (created)
  my_plugin/example/pubspec.yaml (created)
  my_plugin/example/README.md (created)
  my_plugin/example/ios/Runner/Runner-Bridging-Header.h (created)
  my_plugin/example/ios/Runner/AppDelegate.swift (created)
  my_plugin/example/ios/Runner.xcodeproj/project.pbxproj (created)
  my_plugin/example/lib/main.dart (created)
  my_plugin/example/.idea/runConfigurations/main_dart.xml (created)
  my_plugin/example/.idea/libraries/Dart_SDK.xml (created)
  my_plugin/example/.idea/libraries/KotlinJavaRuntime.xml (created)
  my_plugin/example/.idea/modules.xml (created)
  my_plugin/example/.idea/workspace.xml (created)
Running "flutter pub get" in example...                             1.0s
Wrote 69 files.

All done!
[✓] Flutter: is fully installed. (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.4 19E2269, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.5)
[✓] Android Studio: is fully installed. (version 3.6)
[✓] Connected device: is fully installed. (3 available)

In order to run your application, type:

  $ cd my_plugin/example
  $ flutter run

Your application code is in my_plugin/example/lib/main.dart.

Your plugin code is in my_plugin/lib/my_plugin.dart.

Host platform code is in the  directories under my_plugin.
To edit platform code in an IDE see https://flutter.dev/developing-packages/#edit-plugin-package.
```

5. `cd my_plugin && tree -L 3`
```
.
├── CHANGELOG.md
├── LICENSE
├── README.md
├── example
│   ├── README.md
│   ├── build
│   │   └── ios
│   ├── ios
│   │   ├── Flutter
│   │   ├── Podfile
│   │   ├── Runner
│   │   ├── Runner.xcodeproj
│   │   └── Runner.xcworkspace
│   ├── lib
│   │   └── main.dart
│   ├── my_plugin_example.iml
│   ├── pubspec.lock
│   ├── pubspec.yaml
│   └── test
│       └── widget_test.dart
├── ios
│   ├── Assets
│   ├── Classes
│   │   ├── MyPlugin.h
│   │   ├── MyPlugin.m
│   │   └── SwiftMyPlugin.swift
│   └── my_plugin.podspec
├── lib
│   └── my_plugin.dart
├── my_plugin.iml
├── pubspec.lock
├── pubspec.yaml
└── test
    └── my_plugin_test.dart

15 directories, 19 files
```

6. `flutter -v create -t plugin --platforms=android .`
```
[ +128 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 54c9441723ec61baaeb0fbf71fdcf4e415116e6e
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git tag --contains HEAD
[ +169 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +20 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.21.0-1.0.pre-66-g54c9441723
[   +9 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/namniav/namniav-space/third_party/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [/Users/namniav/namniav-space/third_party/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +6 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E2269
[  +54 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +75 ms] executing: /usr/bin/xcodebuild -version
[  +95 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.5
           Build version 11E608c
[   +4 ms] executing: [./ios/] /usr/bin/xcodebuild -list
[ +507 ms] Command line invocation:
               /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list


           xcodebuild: error: The directory /Users/namniav/namniav-space/my_plugin/ios does not contain an Xcode project, workspace or package.
[  +12 ms] "flutter create" took 722ms.
[   +6 ms] Unable to get Xcode project information:
            xcodebuild: error: The directory /Users/namniav/namniav-space/my_plugin/ios does not contain an Xcode project, workspace or package.


[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:403:7)
           <asynchronous suspension>
           #2      IosProject.projectInfo (package:flutter_tools/src/project.dart:527:67)
           #3      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:509:41)
           #4      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:451:56)
           #5      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:428:47)
           #6      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:110:19)
           #7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:380:63)
           #8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:872:18)
           #9      _rootRunUnary (dart:async/zone.dart:1198:47)
           #10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #16     _rootRun (dart:async/zone.dart:1190:13)
           #17     _CustomZone.run (dart:async/zone.dart:1093:19)
           #18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +261 ms] ensureAnalyticsSent: 259ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

7. `flutter doctor -v`
```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.4 19E2269, locale zh-Hans-CN)
    • Flutter version 1.21.0-2.0.pre.66 at /Users/namniav/namniav-space/third_party/flutter
    • Framework revision 54c9441723 (27 hours ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/namniav/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • ONEPLUS A5000 (mobile) • 47949631                  • android-arm64 • Android 10 (API 29)
    • iPhone (mobile)        • 00008030-00150539222A802E • ios           • iOS 13.5
    • macOS (desktop)        • macos                     • darwin-x64    • Mac OS X 10.15.4 19E2269

• No issues found!
```

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.66, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.66 at /Users/taha/Code/flutter_master
    • Framework revision 54c9441723 (2 days ago), 2020-07-17 18:56:12 -0400
    • Engine revision d327828632
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (6 available)            
    • SM M305F (mobile)      • 32003c30dc19668f                     • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.6
    • iPhone 11 (mobile)     • AAB605C7-0569-43D6-9D8D-2AC1A9C36264 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!

```

</details>

**Comment by namniav** [comment]
@TahaTesser 
OK. Now I can back up `ios`, add other platforms, then merge `ios`. Thank you.
