### ISSUE TITLE
web: SecureSocket.connect() not supported?

### ISSUE THREAD

**Issue by robert-virkus** [flutter/flutter#61821]
I am trying to use a Dart IMAP library https://pub.dev/packages/enough_mail on a Flutter Web project. However, when calling `SecureSocket.connect(host, port)` Flutter throws the following exception:

```
Error: Unsupported operation: RawSocket constructor
    at Object.throw_ [as throw] (http://localhost:61478/dart_sdk.js:4463:11)
    at Function.connect (http://localhost:61478/dart_sdk.js:57606:17)
    at Function.connect (http://localhost:61478/dart_sdk.js:55742:27)
    at Function.connect (http://localhost:61478/dart_sdk.js:55607:33)
    at imap_client.ImapClient.new.connectToServer (http://localhost:61478/packages/enough_mail/message_builder.dart.lib.js:8558:67)
```

Needless to say that the same code runs fine on Android.

## Steps to Reproduce

1. Create an app that connects to a server using a SecureSocket
2. Run the app on the web

**Expected results:** 
The connection should be established.

**Actual results:** 
Flutter fails with `Error: Unsupported operation: RawSocket constructor`.

<details>
  <summary>Logs</summary>

```

Error: Unsupported operation: RawSocket constructor
    at Object.throw_ [as throw] (http://localhost:61478/dart_sdk.js:4463:11)
    at Function.connect (http://localhost:61478/dart_sdk.js:57606:17)
    at Function.connect (http://localhost:61478/dart_sdk.js:55742:27)
    at Function.connect (http://localhost:61478/dart_sdk.js:55607:33)
    at imap_client.ImapClient.new.connectToServer (http://localhost:61478/packages/enough_mail/message_builder.dart.lib.js:8558:67)

```

```
flutter doctor -v
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.19041.388], locale de-DE)
    • Flutter version 1.19.0-4.3.pre at C:\Users\rober\Documents\Development\flutter
    • Framework revision 8fe7655ed2 (3 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\rober\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.47.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment]
@robert-virkus yes it's not supported, you can't create Socket objects in a web browser

**Comment by ihorvitruk** [comment]
any updates on it?
