### ISSUE TITLE
Not able to sign via google sign plugin in linux

### ISSUE THREAD

**Issue by apravint** [flutter/flutter#61831]
I am using the plugin google_sign_in. I am able to run the flutter application in ubuntu but I am getting below sign-in error. Please help me to solve this issue?

#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:611:61)
#3      MobileAd.show (package:firebase_admob/firebase_admob.dart:236:12)
#4      _TamilKavithaiPageState.build (package:tamilkavithai/main.dart:42:9)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4674:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4557:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4730:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#9      StatefulElement.update (package:flutter/src/widgets/framework.dart:4762:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5892:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:4638:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5892:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5892:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4730:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:4762:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5892:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5892:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4730:11)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#33     StatefulElement.update (package:flutter/src/widgets/framework.dart:4762:5)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#37     StatelessElement.update (package:flutter/src/widgets/framework.dart:4638:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4730:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:4762:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5892:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#48     ProxyElement.update (package:flutter/src/widgets/framework.dart:4917:5)
#49     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5892:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4730:11)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#56     StatefulElement.update (package:flutter/src/widgets/framework.dart:4762:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#60     ProxyElement.update (package:flutter/src/widgets/framework.dart:4917:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4730:11)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:4762:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#69     StatelessElement.update (package:flutter/src/widgets/framework.dart:4638:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5892:14)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#75     ProxyElement.update (package:flutter/src/widgets/framework.dart:4917:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3247:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4582:16)
#78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4730:11)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#80     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#81     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:880:20)
#82     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#83     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#84     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#85     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
#86     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#87     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#88     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#89     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
flutter: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/46157#issuecomment-562249211 applies here as well.

**Comment by allComputableThings** [comment]
Are there 3rd party libraries providing this important and missing functionality?
