### ISSUE TITLE
FLUTTER CRASH: [VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: Closure call with mismatched arguments: function 'transformDebugCreator' Receiver: Closure: (_SyncIterator<DiagnosticsNode>) => bool

### ISSUE THREAD

**Issue by nsjcorps** [flutter/flutter#61860]
## Steps to Reproduce

I created a flutter app and started working on it with my android emulator. It works fine.

I then tried to test in on my ios simulator and it shows a black screen on the simulator with these logs.

## Logs

```
VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2611 pos 20: '_debugCurrentBuildTarget == context': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2611:20)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2615:12)
#4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
#5      WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
#6      WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
#7      _rootRun (dart:async/zone.dart:1182:47)
#8      _CustomZone.run (dart:async/zone.dart:1093:19)
#9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#10     _Cus<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: Closure call with mismatched arguments: function 'transformDebugCreator'
Receiver: Closure: (_SyncIterator<DiagnosticsNode>) => bool
Tried calling: transformDebugCreator()
Found: transformDebugCreator(_SyncIterator<DiagnosticsNode>) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:118:45)
#2      new List.from (dart:core-patch/array_patch.dart:50:19)
#3      new List.of (dart:core-patch/array_patch.dart:68:17)
#4      Iterable.toList (dart:core/iterable.dart:404:12)
#5      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1004:66)
#6      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2943:105)
#7      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1238:63)
#8      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:111<…>

```

Flutter doctor -v

```
(base) MacBook-Pro:squizelschools jayaikendu$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-NG)
    • Flutter version 1.17.5 at /Users/jayaikendu/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jayaikendu/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/jayaikendu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.2

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone 11 Pro • E6A0DC9B-B4B1-4537-BEC2-32E6559BDF02 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @nsjcorps 
does flutter clean help? https://github.com/flutter/flutter/issues/59245#issuecomment-660031528

**Comment by nsjcorps** [comment]
I tried flutter clean multiple times. It doesn't help

**Comment by nsjcorps** [comment]
I will attempt that now

**Comment by nsjcorps** [comment]
I get the same output on the new project

**Comment by nsjcorps** [comment]
It definitely gets to the build function because I added some print statements there and it printed to the console. Here is my code for my main Widget

```
class MyApp extends StatefulWidget {
  final String initialRoute;

  MyApp({this.initialRoute});

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final navigatorKey = GlobalKey<NavigatorState>();

  Route onGenerateRoute(RouteSettings settings) {
    Route page;

    Map<String, dynamic> routeObj = RouteConstants.DRAWER_ROUTES[settings.name];

    if(routeObj != null)
      return page = CupertinoPageRoute(
        builder: (context) => routeObj['page'],
        settings: RouteSettings(
          name: settings.name
        )
      );

    switch(settings.name) {
      case RouteConstants.CREATE_TEACHER:
        RouteArguments args = settings.arguments;
        page = CupertinoPageRoute(
          fullscreenDialog: true,
          builder: (context) => ChangeNotifierProvider<TeachersListState>.value(
            value: args.data['teachers'],
            child: CreateTeacher(isNew: true,),
          ),
        );
        break;
      case RouteConstants.UPDATE_TEACHER:
        RouteArguments args = settings.arguments;
        page = CupertinoPageRoute(
          builder: (context) => ChangeNotifierProvider<TeacherState>.value(
            value: args.data['teacher'],
            child: CreateTeacher(isNew: false,),
          ),
        );
        break;
      case RouteConstants.CREATE_CLASS:
        RouteArguments args = settings.arguments;
        page = CupertinoPageRoute(
          fullscreenDialog: true,
          builder: (context) => ChangeNotifierProvider<ClassesListState>.value(
            value: args.data['classes'],
            child: CreateOrEditClass(isNew: true,),
          ),
        );
        break;
      case RouteConstants.UPDATE_CLASS:
        RouteArguments args = settings.arguments;
        page = CupertinoPageRoute(
          builder: (context) => ChangeNotifierProvider<ClassesState>.value(
            value: args.data['class'],
            child: CreateOrEditClass(isNew: false,),
          ),
        );
        break;

    }
    return page;
  }

  @override
  Widget build(BuildContext context) {
    print(widget.initialRoute);
    return MaterialApp(
      title: 'Squizel Console',
      theme: StyleConstants.DEFAULT_THEME,
      darkTheme: StyleConstants.DEFAULT_DARK_THEME,
      builder: (context, child) {
        return ScrollConfiguration(
          behavior: MyBehavior(),
          child: child,
        );
      },
      home: Navigator(
        key: navigatorKey,
        onGenerateRoute: onGenerateRoute,
        initialRoute: widget.initialRoute
      )
    );
  }
}
```

**Comment by nsjcorps** [comment]
https://github.com/flutter/flutter/issues/52074 . Someone may have had a similar problem

**Comment by nsjcorps** [comment]
@VladyslavBondarenko

**Comment by nsjcorps** [comment]
@VladyslavBondarenko I switched to flutter dev channel and it worked fine

**Comment by VladyslavBondarenko** [comment]
@nsjcorps 
if it's fixed with dev then there is not need to track the issue, at some point it'll be in stable, closing.
Could everyone who still has this problem with latest flutter version please file a new issue with filling out template
