### ISSUE TITLE
[Cocoon] /api/refresh-chromebot-status hits RangeError (index): Invalid value: Only valid value is 0: 2

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#61873]
Cocoon has been hitting below error over the weekend. It is blocking luci tasks status updates on dashboard.
```
RangeError (index): Invalid value: Only valid value is 0: 2
#0      List.[] (dart:core-patch/growable_array.dart:146:60)
#1      LuciService.getBranchRecentTasks (package:cocoon_service/src/service/luci.dart:71:113)
<asynchronous suspension>
#2      RefreshChromebotStatus.get (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:51:93)
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
#4      _rootRun (dart:async/zone.dart:1184:13)
#5      _CustomZone.run (dart:async/zone.dart:1077:19)
#6      _runZoned (dart:async/zone.dart:1619:10)
#7      runZoned (dart:async/zone.dart:1539:10)
```

**Comment by godofredoc** [comment]
Do we have logs of which commit sha's are causing this problem?

**Comment by keyonghan** [comment]
This is caused by LUCI runs not having commit info. Such as the Windows builder case:
![Screen Shot 2020-07-20 at 9 50 52 AM](https://user-images.githubusercontent.com/54558023/87964103-90a27280-ca6e-11ea-9c9f-0ea87986c975.png)
