### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\HP\AppData\Local\Android\sdk\build-tools\30.0.0\aapt.

### ISSUE THREAD

**Issue by Ahmed-ALshmre** [flutter/flutter#61923]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\HP\AppData\Local\Android\sdk\build-tools\30.0.0\aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:477:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:381:31)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
```
```
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.10586], locale ar-IQ)
    • Flutter version 1.19.0-4.3.pre at C:\src\flutter
    • Framework revision 8fe7655ed2 (3 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    ✗ Android SDK file not found: C:\Users\HP\AppData\Local\Android\sdk\build-tools\30.0.0\aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.2)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 84.0.4147.89

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.5.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
android_intent-0.3.7+2
firebase_messaging-6.0.16
flutter_inappbrowser-2.0.2
flutter_plugin_android_lifecycle-1.0.8
fluttertoast-4.0.1
geolocator-5.3.2+2
google_api_availability-2.0.4
google_map_location_picker-3.3.2
google_maps_flutter-0.5.28+1
location-3.0.2
location_permissions-3.0.0+1
location_web-1.0.0
package_info-0.4.1
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
screen-0.0.5
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2
video_player-0.10.11+2
video_player_web-0.1.3+2
wakelock-0.1.4+2
webview_flutter-0.3.22+1

**Comment by darshankawar** [comment]
Hi @Ahmed-ALshmre,
I see there's a similar open issue describing your case, [58662](https://github.com/flutter/flutter/issues/58662).
I'd suggest you to follow-up there for updates.
I am closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
