### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by joerush18** [flutter/flutter#62007]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: Access is denied.
, errno = 5
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:126:11)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:609:26)
#4      ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:816:44)
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:354:13)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:573:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:844:18)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
```
```
[✓] Flutter (Channel master, 1.19.0-2.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
    • Flutter version 1.19.0-2.0.pre at D:\My room\flutter
    • Framework revision 8abf0a6d8c (9 weeks ago), 2020-05-16 15:07:34 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\joeru\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\joeru\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29613.14
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code, 64-bit edition (version 1.46.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM G615F   • 4200199968da942f • android-arm    • Android 8.1.0 (API 27)
    • Windows    • Windows          • windows-x64    • Microsoft Windows [Version 10.0.18363.959]
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 84.0.4147.89
    • Edge       • edge             • web-javascript • Microsoft Edge 83.0.478.64

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: bb6c3f813146b72ea0f97098c913b45e93b694c4
### Plugins
cloud_firestore-0.9.13+1
firebase_auth-0.8.4+5
firebase_core-0.3.4
firebase_messaging-4.0.0+1
firebase_storage-2.1.1+2
geolocator-5.0.1
google_api_availability-2.0.1
google_sign_in-4.0.2
image_picker-0.6.0+10
location_permissions-2.0.2
path_provider-0.5.0+1
sqflite-1.1.5

**Comment by darshankawar** [comment]
Hi @joerush18,
I see there's a similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
