### ISSUE TITLE
range error(index)

### ISSUE THREAD

**Issue by sriram613** [flutter/flutter#62004]
im having trouble can some help me??
this is the log 

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --template app --description A new Flutter application. --org com.example flutter_app123

## exception

IndexError: RangeError (index): Index out of range: no indices are valid: 0

```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:3932:7)
#1      InputStream.readUint16 (package:archive/src/util/input_stream.dart:206:22)
#2      GZipDecoder._readHeader (package:archive/src/gzip_decoder.dart:89:29)
#3      GZipDecoder.decodeBuffer (package:archive/src/gzip_decoder.dart:26:5)
#4      GZipDecoder.decodeBytes (package:archive/src/gzip_decoder.dart:17:12)
#5      _WindowsUtils.verifyGzip (package:flutter_tools/src/base/os.dart:352:21)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:605:20)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:638:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#9      CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:630:12)
#10     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:1070:12)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:698:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _runZoned (dart:async/zone.dart:1619:10)
#20     runZoned (dart:async/zone.dart:1539:10)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#23     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZoned (dart:async/zone.dart:1539:10)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#32     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#33     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CommandRunner.run (package:args/command_runner.dart:112:14)
#36     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#37     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#38     _rootRun (dart:async/zone.dart:1184:13)
#39     _CustomZone.run (dart:async/zone.dart:1077:19)
#40     _runZoned (dart:async/zone.dart:1619:10)
#41     runZonedGuarded (dart:async/zone.dart:1608:12)
#42     runZoned (dart:async/zone.dart:1536:12)
#43     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#44     run.<anonymous closure> (package:flutter_tools/runner.dart)
#45     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#46     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#47     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#48     _rootRun (dart:async/zone.dart:1184:13)
#49     _CustomZone.run (dart:async/zone.dart:1077:19)
#50     _runZoned (dart:async/zone.dart:1619:10)
#51     runZoned (dart:async/zone.dart:1539:10)
#52     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#53     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#54     run (package:flutter_tools/runner.dart:48:10)
#55     main (package:flutter_tools/executable.dart:69:9)
#56     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#57     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.17763.1158], locale en-IN)
    • Flutter version 1.17.5 at C:\Users\srira\Desktop\fluttter finall\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\srira\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.2)
    • VS Code at C:\Users\srira\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

**Comment by sriram613** [comment]
Some one help me with this issue please

**Comment by darshankawar** [comment]
Hi @sriram613,
I see there's a similar open issue describing your case, [48014](https://github.com/flutter/flutter/issues/48014).
I'd suggest you follow-up there for updates.
Closing this as duplicate.

**Comment by sriram613** [comment]
i resolved this by setting up environment variables.
thank u
