### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\HP\Desktop\nkflutter\projects\test_1\android\app\src\main\res\mipmap-mdpi\ic_launcher.png', path = 'C:\Users\HP\Desktop\nkflutter\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-mdpi\ic_launcher.png' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by vyshnavi7120** [flutter/flutter#62042]
## Command
```
flutter create test_1
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\HP\Desktop\nkflutter\projects\test_1\android\app\src\main\res\mipmap-mdpi\ic_launcher.png', path = 'C:\Users\HP\Desktop\nkflutter\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-mdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:227:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#6      Template.render (package:flutter_tools/src/template.dart:153:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:630:21)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.592], locale en-IN)
    • Flutter version 1.17.5 at C:\Users\HP\Desktop\nkflutter\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_SDK_ROOT = C:\Users\HP\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.2)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by timsneath** [comment]
That error simply means that Windows can't copy the file to your target directory. Could be because you already have it open in a different application, or because you don't have permissions to that directory.

**Comment by darshankawar** [comment]
Hi @vyshnavi7120,
I see there's a similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by vyshnavi7120** [comment]
I solved this error. Thanks for your advices.
