### ISSUE TITLE
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

### ISSUE THREAD

**Issue by DankTestAcc** [flutter/flutter#62048]
#Steps to Reproduce
1. Install Flutter in VSCode or Android Studio
2. Run the Example App (Initial Template)

**Expected results:** 
The usual template app

**Actual results:** 
Build Error

<details>
  <summary>Logs</summary>
*On flutter run*

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform artifact 'kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50)' to match attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=16, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\Paleolithic_Space\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.3.50\3d9cd3e1bc7b92e95f43d45be3bfbcf38e36ab87\kotlin-stdlib-common-1.3.50.jar.
         > Cannot parse result path string:
*On flutter run --verbose*
```
C:\Users\Paleolithic_Space\Desktop\testapp>flutter run --verbose
[  +18 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[        ] executing: [C:\src\flutter/] git tag --contains HEAD
[ +222 ms] Exit code 0 from: git tag --contains HEAD
[  +23 ms] 1.17.5
[   +8 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +152 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +109 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +22 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +42 ms] executing: C:\Users\Paleolithic_Space\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +56 ms] List of devices attached
           52033661b864b341       device product:a3xeltexx model:SM_A310F device:a3xelte transport_id:2
[   +7 ms] C:\Users\Paleolithic_Space\AppData\Local\Android\sdk\platform-tools\adb.exe -s 52033661b864b341 shell getprop
[ +221 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1680 ms] Generating
C:\Users\Paleolithic_Space\Desktop\testapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +203 ms] ro.hardware = samsungexynos7580
[  +70 ms] Launching lib\main.dart on SM A310F in debug mode...
[   +8 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\PALEOL~1\AppData\Local\Temp\flutter_tool.feade639-cc3e-11ea-b73d-f48e3886fe58\app.dill --packages
C:\Users\Paleolithic_Space\Desktop\testapp\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[ +157 ms] executing: C:\Users\Paleolithic_Space\AppData\Local\Android\sdk\platform-tools\adb.exe -s 52033661b864b341 shell -x logcat -v
time -t 1
[ +155 ms] Exit code 0 from: C:\Users\Paleolithic_Space\AppData\Local\Android\sdk\platform-tools\adb.exe -s 52033661b864b341 shell -x
logcat -v time -t 1
[   +4 ms] --------- beginning of main
           07-22 21:15:55.441 I/art     (22114): Background partial concurrent mark sweep GC freed 1029(44KB) AllocSpace objects,        
           94(17MB) LOS objects, 23% free, 52MB/68MB, paused 2.066ms total 139.686ms
[  +60 ms] <- compile package:testapp/main.dart
[  +15 ms] executing: C:\Users\Paleolithic_Space\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +67 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as C:\Users\Paleolithic_Space\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\Paleolithic_Space\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +41 ms] Building APK
[  +23 ms] Running Gradle task 'assembleDebug'...
[  +16 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from C:\Users\Paleolithic_Space\Desktop\testapp\android\gradlew.bat.
[   +1 ms] C:\Users\Paleolithic_Space\Desktop\testapp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[ +427 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +206 ms] Exit code 1 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] Error: could not open `C:\Program Files\Android\Android Studio\jre\jre\lib\amd64\jvm.cfg'
[   +4 ms] executing: [C:\Users\Paleolithic_Space\Desktop\testapp\android/]
C:\Users\Paleolithic_Space\Desktop\testapp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm
-Ptarget=C:\Users\Paleolithic_Space\Desktop\testapp\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root     
assembleDebug
[+47002 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [  +17 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+5316 ms] [+6180 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +98 ms] [   +3 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[   +1 ms] [   +2 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[+9699 ms] [+9770 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] [        ] 1.17.5
[        ] [  +13 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +99 ms] [  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +98 ms] [  +93 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[ +198 ms] [ +203 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +201 ms] [ +257 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[   +1 ms] [  +13 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +13 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +78 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +15 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +59 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +30 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +63 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +12 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +46 ms] [   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +59 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +4 ms] [ +132 ms] Initializing file store
[   +1 ms] [  +44 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [  +21 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages C:\Users\Paleolithic_Space\Desktop\testapp\.packages   
--output-dill C:\Users\Paleolithic_Space\Desktop\testapp\.dart_tool\flutter_build\673b37474d5febe3b66ee23e7f3d2043\app.dill --depfile    
C:\Users\Paleolithic_Space\Desktop\testapp\.dart_tool\flutter_build\673b37474d5febe3b66ee23e7f3d2043\kernel_snapshot.d
package:testapp/main.dart
[+9640 ms] [+9650 ms] kernel_snapshot: Complete
[+8598 ms] [+8529 ms] debug_android_application: Starting due to {}
[+1001 ms] [+1131 ms] debug_android_application: Complete
[ +500 ms] [ +464 ms] Persisting file store
[   +1 ms] [  +10 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [  +15 ms] "flutter assemble" took 20,344ms.
[+1796 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[  +98 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[  +99 ms] > Task :app:compileDebugAidl NO-SOURCE
[ +299 ms] > Task :app:checkDebugManifest UP-TO-DATE
[ +101 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[ +199 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +999 ms] > Task :app:cleanMergeDebugAssets
[ +202 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[  +95 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[+1200 ms] > Task :app:mergeDebugAssets
[+3299 ms] > Task :app:copyFlutterAssetsDebug
[   +3 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[ +195 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResources UP-TO-DATE
[+1096 ms] > Task :app:mergeDebugResources UP-TO-DATE
[ +499 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[+1300 ms] > Task :app:processDebugManifest UP-TO-DATE
[ +399 ms] > Task :app:processDebugResources UP-TO-DATE
[ +800 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[ +201 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +197 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +2 ms] > Task :app:compileDebugSources UP-TO-DATE
[ +397 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +500 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[ +299 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[ +699 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[ +201 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[ +100 ms] > Task :app:mergeExtDexDebug FAILED
[ +399 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[  +64 ms] Execution failed for task ':app:mergeExtDexDebug'.
[   +2 ms] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[   +1 ms]    > Failed to transform artifact 'kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50)' to match      
attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=16,
org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
[   +4 ms]       > Execution failed for DexingWithClasspathTransform:
C:\Users\Paleolithic_Space\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.3.50\3d9cd3e1bc7b92e95f43d45be3bfbcf38e36ab87\kotlin-stdlib-common-1.3.50.jar.
[   +3 ms]          > Cannot parse result path string:
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scanto get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 1m 35s
[   +1 ms] 23 actionable tasks: 5 executed, 18 up-to-date
[+1962 ms] Running Gradle task 'assembleDebug'... (completed in 101.2s)
[   +5 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +11 ms] "flutter run" took 104,277ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

*Flutter analyze output*
```
No issues found! (ran in 135.8s)
```

flutter doctor
```
C:\Users\Paleolithic_Space\Desktop\testapp>flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-GB)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Paleolithic_Space\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Java\jdk1.8.0_251\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Paleolithic_Space\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • SM A310F • 52033661b864b341 • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

</details>

I saw a solution which told me to increase minSdkVersion from 16 to 21, but I need 16 for this project..

**Comment by VladyslavBondarenko** [comment]
Hi @DankTestAcc 
I just tried with stable 1.17.5 on mac, created a new app (it has minSdkVersion 16 by default) and run it on Android 9 device. And it's working.
Does the error persist? Does changing minSdkVersion to 21 helps? Can you see the error again after switching back to 16?
