### ISSUE TITLE
If a view is cached in PlatformViewFactory#create then an exception occurrs

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#62079]
The stacktrace is:

```
E/flutter ( 7209): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
E/flutter ( 7209): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5150)
E/flutter ( 7209): 	at android.view.ViewGroup.addView(ViewGroup.java:4979)
E/flutter ( 7209): 	at android.view.ViewGroup.addView(ViewGroup.java:4919)
E/flutter ( 7209): 	at android.view.ViewGroup.addView(ViewGroup.java:4892)
E/flutter ( 7209): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:697)
```

**Comment by blasten** [comment]
cc @pcsosinski
