### ISSUE TITLE
Crash when doing full reload (shift-R) w/ flutter run --hot

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6210]
flutter run --hot output on crash:

```
R16:04:00.714: Syncing files to device...                           0.1s
16:04:02.540: W/ActivityManager:   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
16:04:02.686: Application finished.
```

adb logcat:

```
10-04 16:03:08.124 E/hwc-drm-compositor-worker(  184): Failed to squash all -114
10-04 16:03:37.875 E/hwc-drm-compositor-worker(  184): Failed to squash all -114
10-04 16:03:40.896 E/hwc-drm-compositor-worker(  184): Failed to squash all -114
10-04 16:04:00.612 E/hwc-drm-compositor-worker(  184): Failed to squash all -114
10-04 16:04:02.008 E/hwc-drm-compositor-worker(  184): Failed to squash all -114
10-04 16:04:02.561 E/hwc-drm-compositor-worker(  184): Failed to squash all -114
10-04 16:04:05.046 E/hwc-drm-compositor-worker(  184): Failed to squash all -114
10-04 16:04:07.584 I/DownloadManagerWrapper(  624): onReceive() : Charging = true
10-04 16:04:08.117 E/hwc-drm-compositor-worker(  184): Failed to squash all -114
10-04 16:04:09.565 F/libc    (30784): Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 30802 (Thread-14)
10-04 16:04:09.566 W/        (  165): debuggerd: handling request: pid=30784 uid=10200 gid=10200 tid=30802
10-04 16:04:09.628 E/        (30942): debuggerd: process stopped due to unexpected signal 27
10-04 16:04:09.630 W/ActivityManager(  507):   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
10-04 16:04:09.631 W/        (  165): debuggerd: resuming target 30784
10-04 16:04:09.638 I/BootReceiver(  507): Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
10-04 16:04:09.649 E/lowmemorykiller(  182): Error writing /proc/30784/oom_score_adj; errno=22
10-04 16:04:09.688 I/OpenGLRenderer(  507): Initialized EGL, version 1.4
10-04 16:04:09.688 D/OpenGLRenderer(  507): Swap behavior 2
10-04 16:04:09.693 E/JavaBinder(  507): !!! FAILED BINDER TRANSACTION !!!  (parcel size = 68)
10-04 16:04:09.698 D/DropBoxEntryAddedChimeraService( 1961): User is not opted-in to Usage & Diagnostics or Lockbox.
10-04 16:04:09.702 I/WindowManager(  507): WIN DEATH: Window{126db4c u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
10-04 16:04:09.702 D/GraphicsStats(  507): Buffer count: 2
10-04 16:04:09.702 W/WindowManager(  507): Force-removing child win Window{9a954d5 u0 SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity} from container Window{126db4c u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
10-04 16:04:09.702 I/ActivityManager(  507): Process com.google.fuchsia.armadillo (pid 30784) has died
10-04 16:04:09.702 I/WindowManager(  507): Destroying surface Surface(name=SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2457 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 
10-04 16:04:09.710 I/WindowManager(  507): Destroying surface Surface(name=com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
10-04 16:04:09.711 W/WindowManager(  507): Failed looking up window
10-04 16:04:09.711 W/WindowManager(  507): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@d24b795 does not exist
10-04 16:04:09.711 W/WindowManager(  507):  at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9100)
10-04 16:04:09.711 W/WindowManager(  507):  at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9091)
10-04 16:04:09.711 W/WindowManager(  507):  at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1777)
10-04 16:04:09.711 W/WindowManager(  507):  at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
10-04 16:04:09.711 I/WindowManager(  507): WIN DEATH: null
10-04 16:04:09.737 D/DropBoxEntryAddedChimeraService( 1961): User is not opted-in to Usage & Diagnostics or Lockbox.
10-04 16:04:09.750 I/Finsky  (29922): [1] com.google.android.finsky.utils.dm.onTrimMemory(25): Memory trim requested to level 80
10-04 16:04:09.886 I/MemoryTrimmer(27863): Trimming objects from memory, since app is in the background.
10-04 16:04:10.348 W/OpenGLRenderer( 1132): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

```

**Comment by eseidelGoogle** [comment]
I think we'd need the flutter version as well as the tombstone file (which would have the arm stack trace) to take action here.

**Comment by apwilson** [comment]
I'll see what I can do.

**Comment by apwilson** [comment]
New crash, the tombstone was empty - zero bytes.

```
--------- beginning of crash
10-05 18:25:37.900  4444  4471 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 4471 (ui_thread)
10-05 18:25:37.901   171   171 W         : debuggerd: handling request: pid=4444 uid=10079 gid=10079 tid=4471
10-05 18:25:37.967  4538  4538 E         : debuggerd: process stopped due to unexpected signal 27
10-05 18:25:37.974   171   171 W         : debuggerd: resuming target 4444
10-05 18:25:37.976   520   538 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
10-05 18:25:37.981  4543  4543 E crash_dispatcher: Failed to read. errno = 0
10-05 18:25:37.981   520  4542 W ActivityManager:   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
10-05 18:25:37.987   187   187 E lowmemorykiller: Error writing /proc/4444/oom_score_adj; errno=22
10-05 18:25:38.032   520  1321 I ActivityManager: Process com.google.fuchsia.armadillo (pid 4444) has died
10-05 18:25:38.033   520   638 D GraphicsStats: Buffer count: 4
10-05 18:25:38.040   520  3340 I OpenGLRenderer: Initialized EGL, version 1.4
10-05 18:25:38.040   520  3340 D OpenGLRenderer: Swap behavior 2
10-05 18:25:38.042   520   799 I WindowManager: WIN DEATH: Window{3a0cfcf u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
10-05 18:25:38.042   520   799 W WindowManager: Force-removing child win Window{a194e7f u0 SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity} from container Window{3a0cfcf u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
10-05 18:25:38.043   520   799 I WindowManager: Destroying surface Surface(name=SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2457 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 
10-05 18:25:38.044   520   799 I WindowManager: Destroying surface Surface(name=com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
10-05 18:25:38.046   520  2343 W WindowManager: Failed looking up window
10-05 18:25:38.046   520  2343 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@3e3bd5c does not exist
10-05 18:25:38.046   520  2343 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9100)
10-05 18:25:38.046   520  2343 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9091)
10-05 18:25:38.046   520  2343 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1777)
10-05 18:25:38.046   520  2343 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
10-05 18:25:38.046   520  2343 I WindowManager: WIN DEATH: null
10-05 18:25:38.058  1184  4547 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
10-05 18:25:38.089  1184  4547 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
10-05 18:25:38.138  1069  2009 I Scheduler: Cleaning up unwanted schedulers, if there are any.
10-05 18:25:38.608  3248  3278 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

**Comment by apwilson** [comment]
New crash, this time with tombstone!

```
10-06 19:34:45.591  6533  6551 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 6551 (Thread-35)
10-06 19:34:45.592   171   171 W         : debuggerd: handling request: pid=6533 uid=10079 gid=10079 tid=6551
10-06 19:34:45.653  7487  7487 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-06 19:34:45.653  7487  7487 F DEBUG   : Build fingerprint: 'google/ryu/dragon:7.0/NRD90R/3141966:userdebug/dev-keys'
10-06 19:34:45.653  7487  7487 F DEBUG   : Revision: '0'
10-06 19:34:45.653  7487  7487 F DEBUG   : ABI: 'arm'
10-06 19:34:45.654  7487  7487 F DEBUG   : pid: 6533, tid: 6551, name: Thread-35  >>> com.google.fuchsia.armadillo <<<
10-06 19:34:45.654  7487  7487 F DEBUG   : signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
10-06 19:34:45.654  7487  7487 F DEBUG   :     r0 d0272ce8  r1 d0272d34  r2 5d928154  r3 00000008
10-06 19:34:45.654  7487  7487 F DEBUG   :     r4 8ce6bdcc  r5 5d928154  r6 5d928154  r7 8db5ad88
10-06 19:34:45.654  7487  7487 F DEBUG   :     r8 8db5ab74  r9 5d928154  sl 8db5af24  fp 8db5af9c
10-06 19:34:45.654  7487  7487 F DEBUG   :     ip d0272cdc  sp 8db5a91c  lr 8d46a075  pc eabf2114  cpsr 680e0010
10-06 19:34:45.658  7487  7487 F DEBUG   : 
10-06 19:34:45.658  7487  7487 F DEBUG   : backtrace:
10-06 19:34:45.658  7487  7487 F DEBUG   :     #00 pc 00017114  /system/lib/libc.so (sigsetjmp+116)
10-06 19:34:45.658  7487  7487 F DEBUG   :     #01 pc 8d46a073  <unknown>
10-06 19:34:46.343   520  7492 W ActivityManager:   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
10-06 19:34:46.345   171   171 W         : debuggerd: resuming target 6533
10-06 19:34:46.345   520   538 I BootReceiver: Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
10-06 19:34:46.393   520  3340 I OpenGLRenderer: Initialized EGL, version 1.4
10-06 19:34:46.393   520  3340 D OpenGLRenderer: Swap behavior 2
10-06 19:34:46.405  1184  7497 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
10-06 19:34:46.430  1184  7497 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
10-06 19:34:46.451   520   638 D GraphicsStats: Buffer count: 4
10-06 19:34:46.451   520  2342 I WindowManager: WIN DEATH: Window{d49fb57 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
10-06 19:34:46.451   520  2342 W WindowManager: Force-removing child win Window{993c69b u0 SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity} from container Window{d49fb57 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
10-06 19:34:46.451   520  2342 I WindowManager: Destroying surface Surface(name=SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2457 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 
10-06 19:34:46.452   520   763 I ActivityManager: Process com.google.fuchsia.armadillo (pid 6533) has died
10-06 19:34:46.453   520  2342 I WindowManager: Destroying surface Surface(name=com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
10-06 19:34:46.454   520   638 W WindowManager: Failed looking up window
10-06 19:34:46.454   520   638 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@f5eb644 does not exist
10-06 19:34:46.454   520   638 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9100)
10-06 19:34:46.454   520   638 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9091)
10-06 19:34:46.454   520   638 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1777)
10-06 19:34:46.454   520   638 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
10-06 19:34:46.455   520   638 I WindowManager: WIN DEATH: null
10-06 19:34:46.494   260   260 I Zygote  : Process 6533 exited due to signal (11)
10-06 19:34:46.495   260   260 I Zygote  : Process 6533 dumped core.
10-06 19:34:46.560  1069  2009 I Scheduler: Cleaning up unwanted schedulers, if there are any.
10-06 19:34:47.025  3248  3278 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-06 19:36:32.495   734   734 E PhoneInterfaceManager: [PhoneIntfMgr] queryModemActivityInfo: Empty response
10-06 19:36:32.498   520   537 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 [mEnergyUsed=0}](url)
```

Tombstone attached.
[tombstone_01.txt](https://github.com/flutter/flutter/files/514986/tombstone_01.txt)

**Comment by apwilson** [comment]
Another crash, this one had a 0 byte tombstone:

```
10-06 19:49:56.417  7973  7998 F libc    : Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 7998 (ui_thread)
10-06 19:49:56.417   171   171 W         : debuggerd: handling request: pid=7973 uid=10079 gid=10079 tid=7998
10-06 19:49:56.433  8020  8020 E         : debuggerd: process stopped due to unexpected signal 27
10-06 19:49:56.434   171   171 W         : debuggerd: resuming target 7973
10-06 19:49:56.434   520   538 I BootReceiver: Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
10-06 19:49:56.437   520  8021 W ActivityManager:   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
10-06 19:49:56.447   187   187 E lowmemorykiller: Error writing /proc/7973/oom_score_adj; errno=22
10-06 19:49:56.453  8022  8022 E crash_dispatcher: Failed to read. errno = 0
10-06 19:49:56.483   520   761 I ActivityManager: Process com.google.fuchsia.armadillo (pid 7973) has died
10-06 19:49:56.483   520  2342 D GraphicsStats: Buffer count: 4
10-06 19:49:56.495   520  3340 I OpenGLRenderer: Initialized EGL, version 1.4
10-06 19:49:56.495   520  3340 D OpenGLRenderer: Swap behavior 2
10-06 19:49:56.497   520   531 I WindowManager: WIN DEATH: Window{1fb0771 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
10-06 19:49:56.497   520   531 W WindowManager: Force-removing child win Window{9240190 u0 SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity} from container Window{1fb0771 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity}
10-06 19:49:56.498   520   531 I WindowManager: Destroying surface Surface(name=SurfaceView - com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2457 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 
10-06 19:49:56.499   520   531 I WindowManager: Destroying surface Surface(name=com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowState$DeathRecipient.binderDied:1780 android.os.BinderProxy.sendDeathNotice:688 <bottom of call stack> 
10-06 19:49:56.500   520   763 W WindowManager: Failed looking up window
10-06 19:49:56.500   520   763 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@68cc956 does not exist
10-06 19:49:56.500   520   763 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9100)
10-06 19:49:56.500   520   763 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9091)
10-06 19:49:56.500   520   763 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1777)
10-06 19:49:56.500   520   763 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
10-06 19:49:56.500   520   763 I WindowManager: WIN DEATH: null
10-06 19:49:56.598  1184  8025 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
10-06 19:49:56.609  1184  8025 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
10-06 19:49:57.057  3248  3278 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-06 19:50:00.020   520   534 I ProcessStatsService: Prepared write state in 4ms
10-06 19:50:07.320  1069  1357 W ctxmgr  : [SyncServerInterestRecordsOperation]No available gcm id.  Cannot proceed server interest records sync.
```

**Comment by eseidelGoogle** [comment]
Well, your one tombstone has a single frame on the stack, which can't be right.  We may need to provide you with a debug engine and/or enlist the help of @chinmaygarde or @jason-simmons here to get to the bottom of this.

**Comment by johnmccutchan** [comment]
Is this still an active issue?

**Comment by eseidelGoogle** [comment]
It would appear not.  Happy to assist further if this comes up again!  Sorry for such a slow response the first time.

**Comment by mraleph** [comment]
Duplicate of #27077
