### ISSUE TITLE
Flutter flavor xcode changes trigger - ArgumentError: Invalid argument(s): Cannot find executable for /Users/xxx/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.

### ISSUE THREAD

**Issue by amirulabu** [flutter/flutter#62116]
## Steps to Reproduce

1. change setting in xcode to setup flutter flavors, referring to[ this youtube video](https://www.youtube.com/watch?v=gdqnxcV7_FY&list=PLUiueC0kTFqLdkuj4j8FNy1qlzcI0nyCu&index=3)
    - create new scheme - `Production` , `Staging` by duplicating `Runner` scheme
    - go to Project > Runner > Info > Configurations
    - duplicate `Debug` with `Debug-production` and `Debug-staging`
    - duplicate `Release` with `Release-production` and `Release-staging`
    - Edit schema `Production` , `Staging` to use the build configurations that is duplicated earlier following the scheme name (eg. Debug-production for Debug schema etc.) in `Run` and `Archive` step
    - Added Firebase folder under Runner folder and add `production`, `staging` folder, and add the appropriate GoogleService-Info.plist under it
    - go to Target > Runner > Build phases. click + and click `New run script phase` added this script

```bash
if [ "${CONFIGURATION}" == "Debug-production" ] || [ "${CONFIGURATION}" == "Release-production" ] || [ "${CONFIGURATION}" == "Release" ]; then

cp -r "${PROJECT_DIR}/Runner/Firebase/production/GoogleService-Info.plist" "${PROJECT_DIR}/Runner/GoogleService-Info.plist"

echo "Production plist copied"

elif [ "${CONFIGURATION}" == "Debug-staging" ] || [ "${CONFIGURATION}" == "Release-staging" ] || [ "${CONFIGURATION}" == "Debug" ]; then

cp -r "${PROJECT_DIR}/Runner/Firebase/staging/GoogleService-Info.plist" "${PROJECT_DIR}/Runner/GoogleService-Info.plist"

echo "Staging plist copied"

fi
```

- Drag the build phase on top of Compile sources
- Go to build settings > change Product Bundle Identifier to appropriate bundle name for each flavor
- close xcode

2. open iPhone SE (2nd generation) ios simulator 
3. do flutter run - `flutter run --flavor staging -t lib/main_staging.dart --verbose`

## command
```
flutter assemble --output=/Users/amirulabu/workspace/flutterapp/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=/Users/amirulabu/workspace/flutterapp/lib/main_staging.dart -dBuildMode=release -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --DartDefines=flutter.inspector.structuredErrors=true -dExtraFrontEndOptions= release_ios_bundle_flutter_assets
```
## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/amirulabu/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:69:31)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
#12     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _runZoned (dart:async/zone.dart:1619:10)
#21     runZoned (dart:async/zone.dart:1539:10)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#23     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#24     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _runZoned (dart:async/zone.dart:1619:10)
#31     runZoned (dart:async/zone.dart:1539:10)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#33     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#34     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#35     new Future.sync (dart:async/future.dart:224:31)
#36     CommandRunner.run (package:args/command_runner.dart:112:14)
#37     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#38     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#39     _rootRun (dart:async/zone.dart:1184:13)
#40     _CustomZone.run (dart:async/zone.dart:1077:19)
#41     _runZoned (dart:async/zone.dart:1619:10)
#42     runZonedGuarded (dart:async/zone.dart:1608:12)
#43     runZoned (dart:async/zone.dart:1536:12)
#44     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#45     run.<anonymous closure> (package:flutter_tools/runner.dart)
#46     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#47     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#48     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#49     _rootRun (dart:async/zone.dart:1184:13)
#50     _CustomZone.run (dart:async/zone.dart:1077:19)
#51     _runZoned (dart:async/zone.dart:1619:10)
#52     runZoned (dart:async/zone.dart:1539:10)
#53     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#54     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#55     run (package:flutter_tools/runner.dart:48:10)
#56     main (package:flutter_tools/executable.dart:69:9)
#57     main (file:///Users/amirulabu/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#58     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/amirulabu/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) • 1F721F08-168F-463C-A733-BF4DC36DB95E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

## full `flutter run --flavor staging -t lib/main_staging.dart --verbose` log

https://gist.github.com/amirulabu/08750e4e876e1afe231bc6560d866529

**Comment by TahaTesser** [comment]
Hi @amirulabu 
Can you upgrade to dev and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persist with ugprade to dev. Can you please provide your `flutter doctor -v`, your `flutter run --flavor staging -t lib/main_staging.dart --verbose` and a complete reproducible minimal code sample in a. repository 
Thank you

**Comment by amirulabu** [comment]
> Hi @amirulabu
> Can you upgrade to dev and try again
> `flutter channel dev`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the problem persist with ugprade to dev. Can you please provide your `flutter doctor -v`, your `flutter run --flavor staging -t lib/main_staging.dart --verbose` and a complete reproducible minimal code sample in a. repository
> Thank you

Hi, i tried reproducing the issue with minimal code sample, but no luck. On the minimal code sample, i tried flavor with ios and it works as expected

Closing this issue for now and will sent a new issue once I can reproduce it with a code sample
