### ISSUE TITLE
Attempting to dismiss a non-dismissable modal dialog on desktop should play system alert sound

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#62143]
Proposed API:

* Add a [`SystemSoundType.alert`](https://api.flutter.dev/flutter/services/SystemSoundType-class.html) enum value, such that callers can play the system alert sound by calling:

```dart
SystemSound.play(SystemSoundType.alert)
```

... then wire that API up to [`ModalBarrier`](https://api.flutter.dev/flutter/widgets/ModalBarrier-class.html)

On mobile platforms, no sound should be played, since those platforms don't natively play a sound when the user taps on a modal barrier.

**Comment by stuartmorgan** [comment]
From quick searching, it looks like this is probably `MessageBeep` on Windows and `gdk_display_beep` for Linux.

**Comment by tvolkert** [comment]
Update: this works on MacOS now - still needed: Linus and Windows.

**Comment by vegidio** [comment]
I found this issue while I was searching for a solution for my problem on Flutter for Android.

I created a non-dismissable `AlertDialog`, with the parameter `barrierDismissible: false` to prevent the user from clicking on the barrier to dismiss the dialog. However, when I click on the barrier I get the exception below:

```
E/flutter (17624): [ERROR:flutter/lib/ui/ui_dart_state.cc(167)] Unhandled Exception: PlatformException(error, No such SoundType: SystemSoundType.alert, null)
E/flutter (17624): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:151:7)
E/flutter (17624): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (17624): <asynchronous suspension>
E/flutter (17624): #2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:458:18)
E/flutter (17624): #3      SystemSound.play (package:flutter/src/services/system_sound.dart:41:35)
E/flutter (17624): #4      ModalBarrier.build.<anonymous closure> (package:flutter/src/widgets/modal_barrier.dart:108:27)
E/flutter (17624): #5      _AnyTapGestureRecognizer.handleTapUp (package:flutter/src/widgets/modal_barrier.dart:231:17)
E/flutter (17624): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter (17624): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter (17624): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter (17624): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter (17624): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:123:9)
E/flutter (17624): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (17624): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:121:18)
E/flutter (17624): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:107:7)
E/flutter (17624): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (17624): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (17624): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter (17624): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter (17624): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter (17624): #19     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (17624): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (17624): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (17624): #22     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter (17624): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
```

This happens only on Android, not on iOS.

**Comment by stuartmorgan** [comment]
[This](https://github.com/flutter/engine/blob/16272b0df3196275c6a8250aa16053394abf9c66/shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformChannel.java#L55) should be changed from returning an error to returning not-implemented.

**Comment by tvolkert** [comment]
https://github.com/flutter/engine/pull/20139 should fix this.

**Comment by tvolkert** [comment]
@vegidio the fix is in master channel now.

**Comment by vegidio** [comment]
@tvolkert Working great! Thanks.

**Comment by TahaTesser** [comment]
Definitely working on Mac, not on Windows yet 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          SystemSound.play(SystemSoundType.alert);
        },
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.340 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1fef5912cf (6 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.0
    • iPhone 11 (mobile)     • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

</details>
