### ISSUE TITLE
Error: NoSuchMethodError: '[]' Dynamic call of null. Receiver: null

### ISSUE THREAD

**Issue by cdunn612** [flutter/flutter#62168]
When trying to make an API Call, i get an error of Error: NoSuchMethodError: '[]'
Dynamic call of null.
Receiver: null

Is there a solution to this?

`import 'package:dunninvestment/stockscreen.dart';
import 'package:dunninvestment/theme.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:async';

class StockInput extends StatefulWidget {
  @override
  _StockInput createState() => _StockInput();
}

class _StockInput extends State<StockInput> {
  final namedTicker = TextEditingController();
  final String apiKey = 'a3d4cdaedb3617fa0a828bdb0d6a0c03';

  double data;

  Future<double> getDCF() async {
    var response = await http.get(
      'URL',
    );
    setState(
      () {
        data = json.decode(response.body)[0]['data'];
        data.toString();
        print(data);
      },
    );
  }

  @override
  void initState() {
    super.initState();
    namedTicker.addListener(() {
      print(namedTicker.text);
    });
    this.getDCF();
  }

  @override
  void dispose() {
    namedTicker.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: AppBar(
        title: Text("Stock Screener"),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Expanded(
            child: TextEntryText(
              namedTicker,
              'Enter the Ticker You Would Like to Analyze',
            ),
          ),
          ReusableBox2(
            cardChild: Column(
              children: <Widget>[
                GestureDetector(
                  child: Text(
                    'ANALYZE',
                    style: cardText,
                  ),
                  onTap: () {
                    namedTicker.toString();
                    getDCF();
                    return Scaffold(
                      body: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: <Widget>[
                          ReusableBox2(
                            cardChild: Text(
                              data.toStringAsFixed(2),
                              style: cardText,
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                ),
              ],
            ),
          ),
          SizedBox(
            height: 15,
          ),
        ],
      ),
    );
  }
}
`
Here is my code that is currently producing the issue. Below is the run error I receive. I am currently running the most up to date flutter in Android Studio and currently have my application running through Chrome(Web).

Performing hot restart...
Syncing files to device Chrome...
Restarted application in 220ms.
Error: NoSuchMethodError: '[]'
Dynamic call of null.
Receiver: null
Arguments: ["dcf"]
    at Object.throw_ [as throw] (http://localhost:60868/dart_sdk.js:4322:11)
    at Object.defaultNoSuchMethod (http://localhost:60868/dart_sdk.js:4760:15)
    at Object.noSuchMethod (http://localhost:60868/dart_sdk.js:4755:27)
    at callNSM (http://localhost:60868/dart_sdk.js:4495:19)
    at Object._checkAndCall (http://localhost:60868/dart_sdk.js:4497:27)
    at Object.callMethod (http://localhost:60868/dart_sdk.js:4575:17)
    at Object.dsend (http://localhost:60868/dart_sdk.js:4578:17)
    at http://localhost:60868/packages/dunninvestment/stockinput.dart.lib.js:539:41
    at stockinput._StockInput.new.setState (http://localhost:60868/packages/flutter/src/widgets/widget_span.dart.lib.js:13380:22)
    at stockinput._StockInput.new.getDCF (http://localhost:60868/packages/dunninvestment/stockinput.dart.lib.js:538:14)
    at getDCF.next (<anonymous>)
    at http://localhost:60868/dart_sdk.js:37211:33
    at _RootZone.runUnary (http://localhost:60868/dart_sdk.js:37065:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:60868/dart_sdk.js:32049:29)
    at handleValueCallback (http://localhost:60868/dart_sdk.js:32596:49)
    at Function._propagateToListeners (http://localhost:60868/dart_sdk.js:32634:17)
    at _Future.new.[_completeWithValue] (http://localhost:60868/dart_sdk.js:32477:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60868/dart_sdk.js:32499:35)
    at Object._microtaskLoop (http://localhost:60868/dart_sdk.js:37326:13)
    at _startMicrotaskLoop (http://localhost:60868/dart_sdk.js:37332:13)
    at http://localhost:60868/dart_sdk.js:32851:9

Thank you for any help!

**Comment by jonahwilliams** [comment]
The Github issue tracker is for bugs and features requests for the Flutter SDK. Help and support questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community .
