### ISSUE TITLE
/C:/src/flutter/packages/flutter/lib/src/painting/image_provider.dart:667:7: Error: The getter 'ethrow' isn't defined for the class 'AssetBundleImageProvider'.

### ISSUE THREAD

**Issue by abdllhcay** [flutter/flutter#62170]
## Steps to Reproduce

1. Create a flutter template app
2. Run the app

**Expected results:** 
The default counter app should come up

**Actual results:** 
The app is crushing with this error:

```
/C:/src/flutter/packages/flutter/lib/src/painting/image_provider.dart:667:7: Error: The getter 'ethrow' isn't defined for the class 'AssetBundleImageProvider'.
 - 'AssetBundleImageProvider' is from 'package:flutter/src/painting/image_provider.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/image_provider.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ethrow'.
      ethrow;
```
<details>
  <summary>Logs</summary>

```
[  +67 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +136 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +373 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.17.5
[  +28 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +70 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +300 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +80 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +63 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.   
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] executing: C:\Users\yusuf\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +94 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:4
[  +28 ms] C:\Users\yusuf\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +245 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +61 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +47 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +491 ms] Generating C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +103 ms] ro.hardware = ranchu
[ +120 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[ +153 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +75 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\yusuf\AppData\Local\Temp\flutter_tool.000c229b-cd40-11ea-b472-6c88145c5418\app.dill --packages
C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root
[  +60 ms] executing: C:\Users\yusuf\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[ +120 ms] Exit code 0 from: C:\Users\yusuf\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +14 ms] --------- beginning of system
           07-24 02:54:22.262 I/UsageStatsService( 1623): User[0] Flushing usage stats to disk
[  +31 ms] <- compile package:my_first_app/main.dart
[  +66 ms] executing: C:\Users\yusuf\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +374 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.1-6435776
                    Installed as C:\Users\yusuf\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +43 ms] executing: C:\Users\yusuf\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +246 ms] Building APK
[ +490 ms] Running Gradle task 'assembleDebug'...
[ +213 ms] gradle.properties already sets `android.enableR8`
[ +169 ms] Using gradle from C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\android\gradlew.bat.
[ +103 ms] C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +60 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +522 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +21 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +74 ms] executing: [C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\android/] C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+10311 ms] > Task :app:compileFlutterBuildDebug
[ +226 ms] [  +85 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +288 ms] [ +654 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +200 ms] [   +1 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[ +185 ms] [   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +573 ms] 
                    Compiler message:
[ +210 ms] /C:/src/flutter/packages/flutter/lib/src/painting/image_provider.dart:667:7: Error: The getter 'ethrow' isn't defined for the class 'AssetBundleImageProvider'.
[ +378 ms]  - 'AssetBundleImageProvider' is from 'package:flutter/src/painting/image_provider.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/image_provider.dart').
[ +122 ms] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ethrow'.
[ +265 ms]       ethrow;
[ +168 ms]       ^^^^^^
[ +513 ms] [+1144 ms] Exit code 0 from: git tag --contains HEAD
[ +162 ms] [        ] 1.17.5
[ +237 ms] [  +27 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +274 ms] [ +536 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[ +150 ms] [        ] origin/stable
[ +191 ms] [        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +435 ms] [ +350 ms] Exit code 0 from: git ls-remote --get-url origin
[ +286 ms] [        ] https://github.com/flutter/flutter.git
[ +255 ms] [ +340 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +479 ms] [ +515 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[ +334 ms] [        ] stable
[ +261 ms] [  +38 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[ +305 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ +385 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ +585 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +413 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +411 ms] [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +726 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +709 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ +449 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ +700 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +953 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +344 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +96 ms] [  +54 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ +209 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ +146 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +102 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +58 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[  +67 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +62 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +23 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +45 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +133 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +371 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[ +106 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +45 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[ +186 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +22 ms] [ +220 ms] Initializing file store
[   +2 ms] [  +39 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [  +38 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages      
C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\.packages --output-dill C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\.dart_tool\flutter_build\275497fa05aba6c1b5a2c551509ec092\app.dill--depfile C:\Users\yusuf\workspace\flutter\my_first_app\my_first_app\.dart_tool\flutter_build\275497fa05aba6c1b5a2c551509ec092\kernel_snapshot.d package:my_first_app/main.dart
[+5030 ms] [+15076 ms] 
[  +13 ms]             Compiler message:
[ +105 ms] [   +3 ms] /C:/src/flutter/packages/flutter/lib/src/painting/image_provider.dart:667:7: Error: The getter 'ethrow' isn't defined for the class 'AssetBundleImageProvider'.
[ +113 ms] [        ]  - 'AssetBundleImageProvider' is from 'package:flutter/src/painting/image_provider.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/image_provider.dart').
[ +162 ms] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'ethrow'.
[  +85 ms] [        ]       ethrow;
[   +5 ms] [        ]       ^^^^^^
[+6529 ms] [+7023 ms] Persisting file store
[  +36 ms] [  +16 ms] Done persisting file store
[  +82 ms] [  +18 ms] "flutter assemble" took 23,096ms.
[ +139 ms] [   +5 ms] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[  +52 ms] build failed.
[ +147 ms] #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[  +99 ms] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:202:7)
[  +11 ms] #2      _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[ +131 ms] #4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[  +29 ms] #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[  +60 ms] #6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +1 ms] #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[   +2 ms] #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +2 ms] #10     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[ +119 ms] #11     _rootRunUnary (dart:async/zone.dart:1192:38)
[  +13 ms] #12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +7 ms] #13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[  +58 ms] #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +2 ms] #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[  +17 ms] #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[  +42 ms] #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[   +1 ms] #20     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +2 ms] #21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #22     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[   +1 ms] #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[  +80 ms] #24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +1 ms] #26     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
[ +147 ms] #27     _rootRunUnary (dart:async/zone.dart:1192:38)
[  +61 ms] #28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #29     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[   +3 ms] #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #31     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[ +120 ms] #32     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[  +18 ms] #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[   +2 ms] #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[   +1 ms] #35     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[   +2 ms] #36     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
[   +2 ms] #37     _rootRunBinary (dart:async/zone.dart:1204:38)
[   +1 ms] #38     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
[   +1 ms] #39     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
[  +72 ms] #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
[   +1 ms] #41     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
[   +2 ms] #42     Future._completeError (dart:async/future_impl.dart:534:5)
[   +2 ms] #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
[   +3 ms] #44     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart)
[  +81 ms] #45     _rootRunUnary (dart:async/zone.dart:1192:38)
[  +40 ms] #46     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #47     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[   +2 ms] #48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +3 ms] #49     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #50     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[        ] #52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
[        ] #53     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
[   +2 ms] #54     _rootRunUnary (dart:async/zone.dart:1192:38)
[  +42 ms] #55     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] #56     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] #57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[   +1 ms] #58     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[   +1 ms] #59     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +1 ms] #60     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
[  +52 ms] #61     _rootRun (dart:async/zone.dart:1184:13)
[   +1 ms] #62     _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] #63     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] #64     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[   +1 ms] #65     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[   +1 ms] #66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[   +1 ms] #67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ] #68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[   +2 ms] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[   +1 ms] Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882
[  +52 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:compileFlutterBuildDebug'.
[   +1 ms] > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 35s
[   +2 ms] > Task :app:compileFlutterBuildDebug FAILED
[   +1 ms] 1 actionable task: 1 executed
[  +27 ms] Running Gradle task 'assembleDebug'... (completed in 39.1s)
[  +62 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +39 ms] "flutter run" took 42,598ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
```

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\yusuf\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\yusuf\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
@abdllhcay did you modify the source code of the SDK? The version of flutter that you've linked does not contain `ethrow` and that looks like `rethrow` with a deletion.

**Comment by abdllhcay** [comment]
No, I didn't. Maybe I should uninstall Flutter completely and install again from stratch.

**Comment by jonahwilliams** [comment]
you don't need to reinstall flutter, just change `ethrow` to `rethrow`

**Comment by abdllhcay** [comment]
Yeah it worked. I don't understand how the source code might have changed, but thank you anyway.

**Comment by victorhez** [comment]
Thank you @jonahwilliams. You really solved my issue

**Comment by tasaddaq-hussain** [comment]
where we find the ethrow to rethrow in our project plz tell mw

**Comment by Askani66** [comment]
> where we find the ethrow to rethrow in our project plz tell mw
this is the path>>>> **Flutter/Sdk/flutter/packages/flutter/lib/src/painting**
In painting directory there is a dart file name: **image_provider.dart,** in **image_provider.dart** file search for the word>> **srethrow** or **ethrow**(or what ever your error is) and replace it with **rethrow** .

**Comment by Askani66** [comment]
> where we find the ethrow to rethrow in our project plz tell mw

this is the path>>>> Flutter/Sdk/flutter/packages/flutter/lib/src/painting
In painting directory there is a dart file name: image_provider.dart, in image_provider.dart file search for the word>> srethrow or ethrow(or what ever your error is) and replace it with rethrow .
