### ISSUE TITLE
[camera 0.5.8+2] java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#62188]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference
       at android.hardware.camera2.legacy.LegacyCameraDevice.configureOutputs(LegacyCameraDevice.java:326)
       at android.hardware.camera2.legacy.CameraDeviceUserShim.endConfigure(CameraDeviceUserShim.java:478)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:80)
       at java.lang.reflect.Proxy.invoke(Proxy.java:397)
       at $Proxy4.endConfigure()
       at android.hardware.camera2.impl.CameraDeviceImpl.configureOutputsChecked(CameraDeviceImpl.java:383)
       at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:437)
       at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:344)
       at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:283)
       at io.flutter.plugins.camera.Camera.startPreview(Camera.java:425)
       at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
       at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:118)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5631)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

![image](https://user-images.githubusercontent.com/47334522/88376474-26f3d280-cda6-11ea-9756-c05713e74d60.png)

**Comment by kw2019ltd** [comment]
√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-IL)
    • Flutter version 1.17.5 at C:\Tools\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
Can you please provide your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices and a complete reproducible minimal code sample
Thank you

**Comment by kw2019ltd** [comment]
@TahaTesser its happening for 1 of my users can't reproduce it for you , pls investigate the issue from your side

**Comment by liuwei1992** [comment]
I had the same problem,
"phonedeviceInfo":"sdkInt:22;fingerprint:samsung/graceltexx/gracelte:7.0/MMB29K/G950FXXU1APFO:user/release-keys;manufacturer:samsung;
flutter --version:Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (5 days ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2

**Comment by zhuozhi666666** [comment]
!!!!!!!Is this problem solved?

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference
1
at android.hardware.camera2.legacy.LegacyCameraDevice.configureOutputs(LegacyCameraDevice.java:326)
2
at android.hardware.camera2.legacy.CameraDeviceUserShim.endConfigure(CameraDeviceUserShim.java:478)
3
at java.lang.reflect.Method.invoke(Method.java)
4
at java.lang.reflect.Method.invoke(Method.java:372)
5
at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:80)
6
at java.lang.reflect.Proxy.invoke(Proxy.java:397)
7
at $Proxy23.endConfigure($Proxy23.java)
8
at android.hardware.camera2.impl.CameraDeviceImpl.configureOutputsChecked(CameraDeviceImpl.java:383)
9
at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:437)
10
at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:15)
11
at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:1)
12
at io.flutter.plugins.camera.Camera.startPreview(Camera.java:2)
13
at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:2)
14
at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:118)
15
at android.os.Handler.handleCallback(Handler.java:815)
16
at android.os.Handler.dispatchMessage(Handler.java:104)
17
at android.os.Looper.loop(Looper.java:194)
18
at android.app.ActivityThread.main(ActivityThread.java:5637)
19
at java.lang.reflect.Method.invoke(Method.java)
20
at java.lang.reflect.Method.invoke(Method.java:372)
21
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
22
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by carman247** [comment]
Also have users affected by the same issue.

Using:
camera: ^0.5.6

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.2 19C57 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/chris/Developer/flutter
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
```

**Comment by darshankawar** [comment]
@kw2019ltd 
Is the NPE issue still valid at your end ?
The `camera` plugin has gone through lot of fixes for Android recently, https://pub.dev/packages/camera/changelog#090
So please confirm if you are still seeing this issue or not and I suggest you to verify using latest plugin version.

**Comment by carman247** [comment]
> @kw2019ltd
> Is the NPE issue still valid at your end ?
> The `camera` plugin has gone through lot of fixes for Android recently, https://pub.dev/packages/camera/changelog#090
> So please confirm if you are still seeing this issue or not and I suggest you to verify using latest plugin version.

I think I am still having the issue but I am about to update the camera package from a PR that was recently merged and became v0.9.0. 

If there are any errors logged I will report back.

**Comment by carman247** [comment]
Pretty sure still getting this issue with `camera 0.9.2+2`

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference

io.flutter.plugins.camera.Camera.createCaptureSession

android.hardware.camera2.legacy.LegacyCameraDevice.configureOutputs (LegacyCameraDevice.java:398)
android.hardware.camera2.legacy.CameraDeviceUserShim.endConfigure (CameraDeviceUserShim.java:538)
android.hardware.camera2.impl.ICameraDeviceUserWrapper.endConfigure (ICameraDeviceUserWrapper.java:111)
android.hardware.camera2.impl.CameraDeviceImpl.configureStreamsChecked (CameraDeviceImpl.java:466)
android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal (CameraDeviceImpl.java:632)
android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession (CameraDeviceImpl.java:501)
io.flutter.plugins.camera.Camera.createCaptureSession (Camera.java:4)
io.flutter.plugins.camera.Camera.createCaptureSession (Camera.java:171)
io.flutter.plugins.camera.Camera.createCaptureSession (Camera.java:1)
io.flutter.plugins.camera.Camera.startPreview (Camera.java:30)
io.flutter.plugins.camera.Camera$1.onOpened (Camera.java:7)
android.hardware.camera2.impl.CameraDeviceImpl$1.run (CameraDeviceImpl.java:139)
android.os.Handler.handleCallback (Handler.java:790)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:164)
android.os.HandlerThread.run (HandlerThread.java:65)
```

```
Device
Brand:TCL
Model:Alcatel 1
Orientation: Portrait
RAM free: 289.32 MB
Disk free: 1.53 GB
```

```
Operating system
Version:8.1.0
Orientation: Portrait
Rooted:No
```

**Comment by blasten** [comment]
cc @camsim99 - this seems like a good bug

**Comment by blasten** [comment]
@godo

**Comment by blasten** [comment]
`resolutionFeature.getPreviewSize()` returns null  in this [line](https://github.com/flutter/plugins/blob/8a71e0ee47c770f29977f6c3810867cb4d1e4376/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java#L336-L337), when either[ this case](https://github.com/flutter/plugins/blob/8a71e0ee47c770f29977f6c3810867cb4d1e4376/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java#L168), or this second [case](https://github.com/flutter/plugins/blob/8a71e0ee47c770f29977f6c3810867cb4d1e4376/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/resolution/ResolutionFeature.java#L43) are reached.

`cameraName` name must be a string with a numeric value that is >=0. These values are obtained from Dart in [1](https://github.com/flutter/plugins/blob/8a71e0ee47c770f29977f6c3810867cb4d1e4376/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/MethodCallHandlerImpl.java#L372), and sent from [2](https://github.com/flutter/plugins/blob/08c9b40d020bf249f346322ec395220e36889b42/packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart#L90).

These IDs come from `getAvailableCameras` called from Dart that uses a native API in [3](https://github.com/flutter/plugins/blob/8a71e0ee47c770f29977f6c3810867cb4d1e4376/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraUtils.java#L94).

The docs for `CameraManager#getCameraIdList()` can be found [here](https://developer.android.com/reference/android/hardware/camera2/CameraManager#getCameraIdList()).

The conclusion is that these cameras are likely to fall under "removable cameras have a unique identifier for each individual device, even if they are the same model.", which is NOT a number >=0 necessarily.
