### ISSUE TITLE
[camera] Initialize failing on samsung s20 ultra 5g and samsung note 10+

### ISSUE THREAD

**Issue by JoseGeorges8** [flutter/flutter#62197]
I'm instantiating the camera controller like

`controller = CameraController(cameras[CameraLensDirection.back], ResolutionPreset.medium);`

## Steps to Reproduce

I haven't reproduce it myself but users are notifying camera does not work on app and I've found this crash on my firebase console

1. Get a high-end samsung device (s20 
2. Try to initialize a camera with the camera api

**Expected results:** 

Camera functioning

**Actual results:** 

User's device crash. This is the log from the firebase console

```
Caused by java.lang.IllegalArgumentException: No capture session available for current capture session.
       at io.flutter.plugins.camera.CameraUtils.getBestAvailableCamcorderProfileForResolutionPreset(CameraUtils.java:106)
       at io.flutter.plugins.camera.Camera.<init>(Camera.java:125)
       at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:175)
       at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0(MethodCallHandlerImpl.java:65)
       at io.flutter.plugins.camera.f.onResult(f.java:6)
       at io.flutter.plugins.camera.CameraPermissions.lambda$requestPermissions$0(CameraPermissions.java:37)
       at io.flutter.plugins.camera.e.onResult(e.java:4)
       at io.flutter.plugins.camera.CameraPermissions$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPermissions.java:80)
       at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:196)
       at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:122)
       at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:140)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8476)
       at android.app.Activity.dispatchActivityResult(Activity.java:8298)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5248)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5296)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8034)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=9796, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.logisticaldataservices.upstart/com.logisticaldataservices.upstart.MainActivity}: java.lang.IllegalArgumentException: No capture session available for current capture session.
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5255)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5296)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8034)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

Flutter doctor:
```
[✓] Flutter (Channel dev, 1.20.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-CA)
    • Flutter version 1.20.0-1.0.pre at
      /Users/josegeorges/Desktop/development/flutter
    • Framework revision f73f498da1 (5 weeks ago), 2020-06-18 08:23:22 -0700
    • Engine revision c0d52b98d1
    • Dart version 2.9.0 (build 2.9.0-16.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/josegeorges/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.2.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment]
May be related to https://github.com/flutter/flutter/issues/61544,
I'll label this, but I don't have such device to test

**Comment by Shivamtruein** [comment]
Even I am experiencing the same with some users for Samsung m30s device. The camera is not initializing. Did not get the crashalytics on this but the capture button is disabled because of the same condition.

Code below

`try {
      cameras = await availableCameras();
      controller = new CameraController(cameras[cameraSide],
           ResolutionPreset.max);
      await controller.initialize();
    }`

to Setup a camera.

Button disabled because of not Initialization.

` onPressed: controller != null &&
                        controller.value.isInitialized 
                    ? onTakePictureButtonPressed
                    : null`

**Comment by JoseGeorges8** [comment]
My team was able to resolve the issue. It isn't an issue from the plugin.

We were instantiating the available cameras on a map like:

```
camerasList = await availableCameras();
for (CameraDescription cameraDescription in camerasList) {
  cameras[cameraDescription.lensDirection] = cameraDescription;
}
```

and it seemed like the cameras from a Samsung S20+ retrieved from the `availableCameras()` method were:

```
07-29 23:03:01.977 I/flutter (26780): xm(0, CameraLensDirection.back, 90)
07-29 23:03:01.977 I/flutter (26780): xm(1, CameraLensDirection.front, 270)
07-29 23:03:01.977 I/flutter (26780): xm(2, CameraLensDirection.back, 90)
07-29 23:03:01.977 I/flutter (26780): xm(3, CameraLensDirection.front, 270)
07-29 23:03:01.977 I/flutter (26780): xm(4, CameraLensDirection.back, 90)
```

So our map was overriding camera 0 with 2 and 2 with 4.

We changed the instantiation of the map to:

```
for (CameraDescription cameraDescription in camerasList) {
  if (!cameras.containsKey[cameraDescription.lensDirection]) 
    cameras[cameraDescription.lensDirection] = cameraDescription;
}
```

So we use camera 0, and that one worked! 

I guess we're still in a limbo as to why camera on index 4 didn't work, but this is good enough for us and thought would be good to document for other developers.

Thanks!
