### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/leahy.nduwamungu/Downloads/flutter/bin/cache/dart-sdk/bin/pub.

### ISSUE THREAD

**Issue by Agape-nduwamungu** [flutter/flutter#62204]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/leahy.nduwamungu/Downloads/flutter/bin/cache/dart-sdk/bin/pub.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:262:33)
<asynchronous suspension>
#5      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:176:15)
#6      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:95:17)
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:126:11)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.5 at /Users/leahy.nduwamungu/Downloads/flutter
    • Framework revision 8af6b2f038 (), 1970-01-01 02:00:00.000
    • Engine revision 
    • Dart version 2.8.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4

**Comment by pedromassangocode** [comment]
Hi @Agape-nduwamungu 
I see there's an open issue (https://github.com/flutter/flutter/issues/60880) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
