### ISSUE TITLE
Invalid Podfile error when running the project with the latest stable version 

### ISSUE THREAD

**Issue by pepejeria** [flutter/flutter#62201]
## Steps to Reproduce

1. Create new project using master (version will be 1.20 or higher). A Podfile will be added to the iOS project. 
2. Run project with no issues
3. Change flutter to a stable version and run project again

## Logs

```
CocoaPods' output:
↳
    [!] Invalid `Podfile` file: cannot load such file -- /Users/my-user/flutter/stable/packages/flutter_tools/bin/podhelper.
     #  from /Users/my-user/d/code/project-name/player-mobile/ios/Podfile:26
     #  -------------------------------------------
     #  
     >  require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
     #  
     #  -------------------------------------------
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:293:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile.rb:259:in `from_file'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/config.rb:200:in `podfile'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:46:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
```

Do I need to change the Podfile to make it work with the stable version? If yes how? 

Thank you.

**Comment by darshankawar** [comment]
Hi @pepejeria,
I see there's similar open issue describing your case, [59522](https://github.com/flutter/flutter/issues/59522).
I'd suggest you to follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
