### ISSUE TITLE
Cannot pass deleted object as a pointer of type sk_sp<SkPicture>

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#62208]
A few minutes after loading the Flutter devicelab dashboard, it locks up and throws this exception:
Cannot pass deleted object as a pointer of type sk_sp<SkPicture>
```
VM1866:1 console.trace
eval @ VM1866:1
ac @ canvaskit.js:formatted:3503
tc @ canvaskit.js:formatted:3635
SkCanvas$drawPicture @ VM1200:9
IT @ main.dart.js:22852
```
pretty print of the `SkCanvas$drawPicture` frame shows it's at the `var arg0Wired = argType0.toWireType(destructors, arg0); // sk_sp<SkPicture>` line below:
```js
(function anonymous(throwBindingError,invoker,fn,runDestructors,retType,classParam,argType0
) {
return function SkCanvas$drawPicture(arg0) {
if (arguments.length !== 1) {
throwBindingError('function SkCanvas.drawPicture called with ' + arguments.length + ' arguments, expected 1 args!');
}
var destructors = [];
var thisWired = classParam.toWireType(destructors, this);
var arg0Wired = argType0.toWireType(destructors, arg0); // sk_sp<SkPicture>
invoker(fn, thisWired, arg0Wired);
runDestructors(destructors);
}

})
```

**Comment by passsy** [comment]
Still receive this error when dealing with platform views. I can't really reproduce it, it just happens from time to time when multiple platform views are added/removed quickly.

```
RNING: Too many active WebGL contexts. Oldest context will be lost.

in.dart.js:2984 Uncaught BindingError: Cannot pass deleted object as a pointer of type Surface*
    at Error.<anonymous> (canvaskit.js:166:76)
    at new <anonymous> (canvaskit.js:165:316)
    at Y (canvaskit.js:168:250)
    at yc.xc [as toWireType] (canvaskit.js:177:144)
    at oc._getCanvas (canvaskit.js:181:456)
    at a.Surface.getCanvas (canvaskit.js:60:90)
    at v3.a1n (main.dart.js:49980:16)
    at alv.aRi (main.dart.js:48479:3)
    at tear_off.<anonymous> (main.dart.js:3106:65)
    at at.ab (main.dart.js:59391:31)
e @ main.dart.js:2984
cvJ @ main.dart.js:5458
Em @ main.dart.js:5710
$0 @ main.dart.js:57007
cIE @ main.dart.js:4437
cJf @ main.dart.js:4439
$1 @ main.dart.js:55931
cLT @ main.dart.js:3065
(anonymous) @ main.dart.js:3073
childList (async)
$1 @ main.dart.js:55938
ckS @ main.dart.js:4444
D8 @ main.dart.js:4534
Fg @ main.dart.js:56262
ahP @ main.dart.js:56243
cjJ @ main.dart.js:4274
i @ main.dart.js:4270
(anonymous) @ main.dart.js:142247
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
FH @ main.dart.js:142251
aD @ main.dart.js:142255
er @ main.dart.js:101879
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
TD @ main.dart.js:101807
er @ main.dart.js:101861
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
TD @ main.dart.js:101807
er @ main.dart.js:101899
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
mJ @ main.dart.js:101873
TD @ main.dart.js:101807
er @ main.dart.js:101880
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
TD @ main.dart.js:101807
er @ main.dart.js:101899
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
TD @ main.dart.js:101807
er @ main.dart.js:101861
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
mJ @ main.dart.js:101873
TD @ main.dart.js:101807
er @ main.dart.js:101880
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
mJ @ main.dart.js:101873
TD @ main.dart.js:101807
er @ main.dart.js:101880
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
mJ @ main.dart.js:101873
TD @ main.dart.js:101807
er @ main.dart.js:101880
iE @ main.dart.js:101674
mJ @ main.dart.js:101841
TD @ main.dart.js:101807
er @ main.dart.js:101861
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
er @ main.dart.js:102063
iE @ main.dart.js:101674
$0 @ main.dart.js:103455
Hb @ main.dart.js:101600
aRQ @ main.dart.js:103440
(anonymous) @ main.dart.js:3106
$0 @ main.dart.js:88640
aKy @ main.dart.js:88327
a2Z @ main.dart.js:88463
bZ @ main.dart.js:103489
aRT @ main.dart.js:88437
anh @ main.dart.js:88326
a1U @ main.dart.js:85732
a1U @ main.dart.js:98248
aPf @ main.dart.js:85725
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
adT @ main.dart.js:93812
anx @ main.dart.js:93797
aNo @ main.dart.js:93770
(anonymous) @ main.dart.js:3105
Db @ main.dart.js:660
$1 @ main.dart.js:50767
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
Ez @ main.dart.js:93720
b1_ @ main.dart.js:93890
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
$2 @ main.dart.js:93847
ab @ main.dart.js:55553
eI @ main.dart.js:47342
anv @ main.dart.js:93782
aMR @ main.dart.js:93766
(anonymous) @ main.dart.js:3106
aO_ @ main.dart.js:663
$1 @ main.dart.js:50766
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
Ez @ main.dart.js:93720
b1_ @ main.dart.js:93890
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
$2 @ main.dart.js:93847
ab @ main.dart.js:55553
eI @ main.dart.js:47342
anv @ main.dart.js:93782
aMR @ main.dart.js:93766
(anonymous) @ main.dart.js:3106
aO_ @ main.dart.js:663
$1 @ main.dart.js:50766
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
a23 @ main.dart.js:93737
aMT @ main.dart.js:98042
(anonymous) @ main.dart.js:3105
a6A @ main.dart.js:101592
eM @ main.dart.js:101802
aoZ @ main.dart.js:156757
(anonymous) @ main.dart.js:3105
K @ main.dart.js:71740
qr @ main.dart.js:143232
(anonymous) @ main.dart.js:34895
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
RP @ main.dart.js:34900
(anonymous) @ main.dart.js:141903
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
atj @ main.dart.js:141906
$1 @ main.dart.js:141896
MD @ main.dart.js:99207
(anonymous) @ main.dart.js:96224
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aQz @ main.dart.js:96350
Yz @ main.dart.js:96168
(anonymous) @ main.dart.js:96146
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aSh @ main.dart.js:96167
Ns @ main.dart.js:96141
(anonymous) @ main.dart.js:3106
(anonymous) @ main.dart.js:95227
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aMN @ main.dart.js:95255
N2 @ main.dart.js:95219
$1 @ main.dart.js:95258
(anonymous) @ main.dart.js:94712
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
atd @ main.dart.js:94733
$2 @ main.dart.js:94706
cLS @ main.dart.js:665
ht @ main.dart.js:62036
a4s @ main.dart.js:62043
aqt @ main.dart.js:62057
oR @ main.dart.js:51237
$1 @ main.dart.js:53835
beU @ main.dart.js:53497
(anonymous) @ main.dart.js:3106
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
main.dart.js:7216 Flutter was unable to create enough overlay surfaces. This is usually caused by too many platform views being displayed at once. You may experience incorrect rendering.
b4 @ main.dart.js:7216
$1 @ main.dart.js:50453
bhK @ main.dart.js:48216
qv @ main.dart.js:49322
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
qv @ main.dart.js:49198
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
qv @ main.dart.js:49264
wo @ main.dart.js:49159
$0 @ main.dart.js:49405
cmP @ main.dart.js:695
bid @ main.dart.js:49400
b9u @ main.dart.js:49742
bjs @ main.dart.js:49869
b6n @ main.dart.js:92884
a1U @ main.dart.js:85735
a1U @ main.dart.js:98248
aPf @ main.dart.js:85725
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
adT @ main.dart.js:93812
anx @ main.dart.js:93797
aNo @ main.dart.js:93770
(anonymous) @ main.dart.js:3105
Db @ main.dart.js:660
$1 @ main.dart.js:50767
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
Ez @ main.dart.js:93720
b1_ @ main.dart.js:93890
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
$2 @ main.dart.js:93847
ab @ main.dart.js:55553
eI @ main.dart.js:47342
anv @ main.dart.js:93782
aMR @ main.dart.js:93766
(anonymous) @ main.dart.js:3106
aO_ @ main.dart.js:663
$1 @ main.dart.js:50766
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
Ez @ main.dart.js:93720
b1_ @ main.dart.js:93890
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
$2 @ main.dart.js:93847
ab @ main.dart.js:55553
eI @ main.dart.js:47342
anv @ main.dart.js:93782
aMR @ main.dart.js:93766
(anonymous) @ main.dart.js:3106
aO_ @ main.dart.js:663
$1 @ main.dart.js:50766
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
Ez @ main.dart.js:93720
b1_ @ main.dart.js:93890
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
$2 @ main.dart.js:93847
ab @ main.dart.js:55553
eI @ main.dart.js:47342
anv @ main.dart.js:93782
aMR @ main.dart.js:93766
(anonymous) @ main.dart.js:3106
aO_ @ main.dart.js:663
$1 @ main.dart.js:50766
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
a23 @ main.dart.js:93737
aMT @ main.dart.js:98042
(anonymous) @ main.dart.js:3105
a6A @ main.dart.js:101592
eM @ main.dart.js:101802
aoZ @ main.dart.js:156757
(anonymous) @ main.dart.js:3105
K @ main.dart.js:71740
qr @ main.dart.js:143232
(anonymous) @ main.dart.js:34895
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
RP @ main.dart.js:34900
(anonymous) @ main.dart.js:141903
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
atj @ main.dart.js:141906
$1 @ main.dart.js:141896
MD @ main.dart.js:99207
(anonymous) @ main.dart.js:96224
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aQz @ main.dart.js:96350
Yz @ main.dart.js:96168
(anonymous) @ main.dart.js:96146
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aSh @ main.dart.js:96167
Ns @ main.dart.js:96141
(anonymous) @ main.dart.js:3106
(anonymous) @ main.dart.js:95227
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aMN @ main.dart.js:95255
N2 @ main.dart.js:95219
$1 @ main.dart.js:95258
(anonymous) @ main.dart.js:94712
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
atd @ main.dart.js:94733
$2 @ main.dart.js:94706
cLS @ main.dart.js:665
ht @ main.dart.js:62036
a4s @ main.dart.js:62043
aqt @ main.dart.js:62057
oR @ main.dart.js:51237
$1 @ main.dart.js:53835
beU @ main.dart.js:53497
(anonymous) @ main.dart.js:3106
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
main.dart.js:2984 Uncaught TypeError: Cannot read properties of undefined (reading 'Cs')
    at alv.ayl (main.dart.js:48373:13)
    at biG.b9u (main.dart.js:49747:9)
    at aen.bjs (main.dart.js:49869:12)
    at a0B.b6n (main.dart.js:92884:3)
    at ay_.a1U (main.dart.js:85735:30)
    at ay_.a1U (main.dart.js:98248:3)
    at ay_.aPf (main.dart.js:85725:13)
    at tear_off.<anonymous> (main.dart.js:3106:65)
    at ay_.adU (main.dart.js:93808:7)
    at ay_.adT (main.dart.js:93812:22)
e @ main.dart.js:2984
cvJ @ main.dart.js:5458
Em @ main.dart.js:5710
$0 @ main.dart.js:57007
cIE @ main.dart.js:4437
cJf @ main.dart.js:4439
$1 @ main.dart.js:55931
cLT @ main.dart.js:3065
(anonymous) @ main.dart.js:3073
childList (async)
$1 @ main.dart.js:55938
ckS @ main.dart.js:4444
cJ7 @ main.dart.js:4446
D7 @ main.dart.js:4514
$1 @ main.dart.js:134106
ez @ main.dart.js:11088
adU @ main.dart.js:93811
adT @ main.dart.js:93812
anx @ main.dart.js:93797
aNo @ main.dart.js:93770
(anonymous) @ main.dart.js:3105
Db @ main.dart.js:660
$1 @ main.dart.js:50767
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
Ez @ main.dart.js:93720
b1_ @ main.dart.js:93890
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
$2 @ main.dart.js:93847
ab @ main.dart.js:55553
eI @ main.dart.js:47342
anv @ main.dart.js:93782
aMR @ main.dart.js:93766
(anonymous) @ main.dart.js:3106
aO_ @ main.dart.js:663
$1 @ main.dart.js:50766
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
Ez @ main.dart.js:93720
b1_ @ main.dart.js:93890
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
$2 @ main.dart.js:93847
ab @ main.dart.js:55553
eI @ main.dart.js:47342
anv @ main.dart.js:93782
aMR @ main.dart.js:93766
(anonymous) @ main.dart.js:3106
aO_ @ main.dart.js:663
$1 @ main.dart.js:50766
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
Ez @ main.dart.js:93720
b1_ @ main.dart.js:93890
(anonymous) @ main.dart.js:3106
adU @ main.dart.js:93808
$2 @ main.dart.js:93847
ab @ main.dart.js:55553
eI @ main.dart.js:47342
anv @ main.dart.js:93782
aMR @ main.dart.js:93766
(anonymous) @ main.dart.js:3106
aO_ @ main.dart.js:663
$1 @ main.dart.js:50766
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
requestAnimationFrame (async)
b4 @ main.dart.js:7216
$0 @ main.dart.js:50755
qX @ main.dart.js:51326
qX @ main.dart.js:93745
a23 @ main.dart.js:93737
aMT @ main.dart.js:98042
(anonymous) @ main.dart.js:3105
a6A @ main.dart.js:101592
eM @ main.dart.js:101802
aoZ @ main.dart.js:156757
(anonymous) @ main.dart.js:3105
K @ main.dart.js:71740
qr @ main.dart.js:143232
(anonymous) @ main.dart.js:34895
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
RP @ main.dart.js:34900
(anonymous) @ main.dart.js:141903
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
atj @ main.dart.js:141906
$1 @ main.dart.js:141896
MD @ main.dart.js:99207
(anonymous) @ main.dart.js:96224
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aQz @ main.dart.js:96350
Yz @ main.dart.js:96168
(anonymous) @ main.dart.js:96146
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aSh @ main.dart.js:96167
Ns @ main.dart.js:96141
(anonymous) @ main.dart.js:3106
(anonymous) @ main.dart.js:95227
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
aMN @ main.dart.js:95255
N2 @ main.dart.js:95219
$1 @ main.dart.js:95258
(anonymous) @ main.dart.js:94712
(anonymous) @ main.dart.js:4281
$2 @ main.dart.js:55987
o @ main.dart.js:4267
atd @ main.dart.js:94733
$2 @ main.dart.js:94706
cLS @ main.dart.js:665
ht @ main.dart.js:62036
a4s @ main.dart.js:62043
aqt @ main.dart.js:62057
oR @ main.dart.js:51237
$1 @ main.dart.js:53835
beU @ main.dart.js:53497
(anonymous) @ main.dart.js:3106
cgt @ main.dart.js:2944
cdZ @ main.dart.js:5447
cGZ @ main.dart.js:7197
(anonymous) @ main.dart.js:7193
main.dart.js:2984 Uncaught RuntimeError: null function or function signature mismatch
    at canvaskit.wasm:0x82b3c
    at canvaskit.wasm:0x41a2c
    at canvaskit.wasm:0x2f9917
    at canvaskit.wasm:0x35f960
    at canvaskit.wasm:0x3eedb
    at oc._clear (canvaskit.js:182:52)
    at a.Canvas.clear (canvaskit.js:46:315)
    at l7.BG (main.dart.js:47705:16)
    at TH.BG (main.dart.js:49442:38)
    at b2o.$0 (main.dart.js:49412:3)
e
```

The Flutter app then becomes unresponsive and the console is full of 

<img width="595" alt="Screen-Shot-2023-04-12-14-38-40 20" src="https://user-images.githubusercontent.com/1096485/231459808-11fce429-83fb-4f40-a0f2-20a77578fae6.png">

The platform views (a map in my case) is still responsive.
