### ISSUE TITLE
Async errors created with Future.error() crash dumpErrorToConsole()

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#62223]
### Steps to reproduce

Run the following code in a Flutter app:

```dart
  final Future<void> future = Future<void>.error('no_stack');
  try {
    await future;
  } catch (error, stack) {
    FlutterError.dumpErrorToConsole(FlutterErrorDetails(
      exception: error,
      stack: stack,
    ));
  }
```

### Expected results

You expect some indication of the "no_stack" error to be dumped to the console.

### Actual results

The following assertion fails:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 114 pos 12: 'match != null': Expected  to match RegExp: pattern=^(.+) (\d+):(\d+)\s+(.+)$ flags=.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      StackFrame._parseWebDebugFrame (package:flutter/src/foundation/stack_frame.dart:114:12)
#3      StackFrame._parseWebFrame (package:flutter/src/foundation/stack_frame.dart:100:14)
#4      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:202:14)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#7      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:875:20)
#8      new List.from (dart:core-patch/array_patch.dart:50:19)
#9      new List.of (dart:core-patch/array_patch.dart:68:17)
#10     Iterable.toList (dart:core/iterable.dart:404:12)
#11     StackFrame.fromStackString (package:flutter/src/foundation/stack_frame.dart:95:10)
#12     FlutterError.defaultStackFilter (package:flutter/src/foundation/assertions.dart:999:54)
#13     DiagnosticsStackTrace._applyStackFilter (package:flutter/src/foundation/assertions.dart:1168:43)
#14     new DiagnosticsStackTrace (package:flutter/src/foundation/assertions.dart:1143:17)
#15     FlutterErrorDetails.debugFillProperties (package:flutter/src/foundation/assertions.dart:682:22)
#16     DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2945:17)
#17     DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2948:8)
#18     _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1190:56)
#19     DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2962:105)
#20     TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1248:63)
#21     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1126:14)
#22     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:954:11)
```

## Other information
I tried to write a test to replicate this in [`error_reporting_test.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter/test/foundation/error_reporting_test.dart):

```dart
test('Error reporting - empty stack', () async {
  final Future<void> future = Future<void>.error('no_stack');
  try {
    await future;
  } catch (error, stack) {
    FlutterError.dumpErrorToConsole(FlutterErrorDetails(
      exception: error,
      stack: stack,
    ));
  }
});
```

... but unfortunately the same results don't replicate in a test, because stack traces look different in tests and run into [this assertion](https://github.com/flutter/flutter/blob/e64fe11542238376fdfbf351d81e22d08296da45/packages/flutter/lib/src/foundation/stack_frame.dart#L192-L197) (do we pass `--no-causal_async_stacks` in tests?).  You can _simulate_ this error condition in tests by running the following code:

```dart
FlutterError.dumpErrorToConsole(FlutterErrorDetails(
  exception: 'exception',
  stack: StackTrace.fromString(''),
));
```

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/issues/52685
