### ISSUE TITLE
[engine] Some rollers are not triggering all the builders

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#62233]
Some PRs are triggering a single build, this is an example:
* https://github.com/flutter/engine/pull/20021

![image](https://user-images.githubusercontent.com/54371434/88442162-54517800-cdc8-11ea-8a10-73af740724ff.png)

**Comment by Hixie** [comment]
@godofredoc What's the status of this bug?

**Comment by godofredoc** [comment]
I'm adding more logging to understand what is happening. From reviewing the code and the current logs we haven't found the bug.

**Comment by godofredoc** [comment]
We finally got logs for a repro:

```

2020-07-31 15:34:38.001 PDT
Creating check run for PR: 62445, Commit: ca71cbbb12cc53be4ae3d3f48d995365b940bd2a, Owner: flutter and Repo: flutter
2020-07-31 15:34:38.302 PDT
Trigger build for: Windows
2020-07-31 15:34:38.302 PDT
Creating check run for PR: 62445, Commit: ca71cbbb12cc53be4ae3d3f48d995365b940bd2a, Owner: flutter and Repo: flutter
2020-07-31 15:34:38.365 PDT
GitHub Error: Access Forbidden
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:403:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      GitHub.requestJson (package:github/src/common/github.dart:268:28)
#3      GitHub.postJSON (package:github/src/common/github.dart:194:7)
#4      _CheckRunsService.createCheckRun (package:github/src/common/checks_service.dart:67:19)
#5      GithubChecksUtil.createCheckRun (package:cocoon_service/src/foundation/github_checks_util.dart:78:42)
#6      LuciBuildService.scheduleTryBuilds (package:cocoon_service/src/service/luci_build_service.dart:176:65)
<asynchronous suspension>
#7      GithubWebhook._scheduleIfMergeable (package:cocoon_service/src/request_handlers/github_webhook.dart:167:28)
<asynchronous suspension>
#8      GithubWebhook._handlePullRequest (package:cocoon_service/src/request_handlers/github_webhook.dart:137:15)
<asynchronous suspension>
#9      GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:73:17)
<asynchronous suspension>
#10     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
<asynchronous suspension>
#11     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart)
#12     _rootRun (dart:async/zone.dart:1184:13)
#13     _CustomZone.run (dart:async/zone.dart:1077:19)
#14     _runZoned (dart:async/zone.dart:1619:10)
#15     runZoned (dart:async/zone.dart:1539:10)
#16     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#17     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:127:23)
<asynchronous suspension>
#18     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart)
```

**Comment by godofredoc** [comment]
The build succeeded running the first builder but failed in the second one with a permission problem. This is most likely related to the enhanced authentication workflow for the flutter dashboard where we are using short lived tokens and the token expires in the middle of a request.

**Comment by godofredoc** [comment]
Fixed by https://github.com/flutter/cocoon/pull/888
