### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for C:\Users\berry\Music\Progetto PROGMOB\ubeach\android\gradlew.bat.

### ISSUE THREAD

**Issue by AndreaSenese** [flutter/flutter#62275]
## Command
```
flutter run --machine --target lib\main.dart -d emulator-5554 --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\berry\Music\Progetto PROGMOB\ubeach\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:384:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:102:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:513:28)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Versione 10.0.18362.959], locale it-IT)
    • Flutter version 1.17.5 at C:\Users\berry\Downloads\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\berry\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.2)
    • VS Code at C:\Users\berry\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-0.13.6
cloud_firestore_web-0.1.1+2
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
flutter_plugin_android_lifecycle-1.0.8
geolocator-5.3.2+2
google_api_availability-2.0.4
google_maps_flutter-0.5.28+1
location_permissions-3.0.0+1

**Comment by darshankawar** [comment]
Hi @AndreaSenese,
I see there's similar open issue describing your case, [56975](https://github.com/flutter/flutter/issues/56975).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
