### ISSUE TITLE
[tool_crash] FileSystemException: flush failed, OS Error: Input/output error, errno = 5

### ISSUE THREAD

**Issue by sayanmondal31** [flutter/flutter#62278]
## Command
```
flutter pub get
```

```
#0      _RandomAccessFile.flushSync (dart:io/file_impl.dart:974:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:607:25)
#2      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#3      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#4      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:186:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_file_system.dart:351:14)
#6      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:185:5)
#7      _writeFlutterPluginsListLegacy (package:flutter_tools/src/plugins.dart:512:15)
#8      refreshPluginsList (package:flutter_tools/src/plugins.dart:1137:30)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:241:11)
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:23)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:872:18)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.37, on Linux, locale en_IN)
    • Flutter version 1.21.0-6.0.pre.37 at /home/sayan/flutter
    • Framework revision 35e7005184 (12 hours ago), 2020-07-25 09:44:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/sayan/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/90/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • ASUS X00TD (mobile) • J5AAB7610475EL4 • android-arm64 • Android 9 (API 28)
    • Linux (desktop)     • linux           • linux-x64     • Linux

• No issues found!
```

**Comment by sayanmondal31** [comment]
update flutter path then restart your pc and it'll work
