### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:Stderr:unzip:  cannot find or open /Users/lebcir/Public/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip, /Users/lebcir/Public/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.zip or /Users/lebcir/Public/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.ZIP. Command: unzip, OS error code: 9

### ISSUE THREAD

**Issue by AkramLebcir** [flutter/flutter#62284]
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. $flutter upgrade

## Logs
ProcessException: The command failed
Stdout:

Stderr:
unzip:  cannot find or open /Users/lebcir/Public/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip, /Users/lebcir/Public/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.zip or /Users/lebcir/Public/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.ZIP.
 Command: unzip, OS error code: 9
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:459:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:226:19)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:648:16)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Net.fetchUrl (package:flutter_tools/src/base/net.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.37, on Mac OS X 10.15.5 19F101, locale en-DZ)
    • Flutter version 1.21.0-6.0.pre.37 at /Users/lebcir/Public/flutter
    • Framework revision 35e7005184 (15 hours ago), 2020-07-25 09:44:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/lebcir/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Hi @AkramLebcir,
I see there's similar open issue describing your case, [62284](https://github.com/flutter/flutter/issues/62284).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
