### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:Stderr:unzip:  cannot find or open /Users/gintas/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip, /Users/gintas/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.zip or /Users/gintas/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.ZIP. Command: unzip, OS error code: 9

### ISSUE THREAD

**Issue by Gintasz** [flutter/flutter#62302]
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. flutter upgrade

## Logs
ProcessException: The command failed
Stdout:

Stderr:
unzip:  cannot find or open /Users/gintas/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip, /Users/gintas/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.zip or /Users/gintas/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.ZIP.
 Command: unzip, OS error code: 9
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:459:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:226:19)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:648:16)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Net.fetchUrl (package:flutter_tools/src/base/net.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.37, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.37 at /Users/gintas/flutter
    • Framework revision 35e7005184 (26 hours ago), 2020-07-25 09:44:17 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/gintas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.6183.88
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM G903F (mobile) • 33003cf13f6172fd • android-arm    • Android 6.0.1 (API 23)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.89
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Hi @Gintasz,
I see there's similar open issue describing your case, [52437](https://github.com/flutter/flutter/issues/52437).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
