### ISSUE TITLE
flutter run: BUILD FAILED 

### ISSUE THREAD

**Issue by chauhannaman98** [flutter/flutter#62336]
## Minimal Reproduction
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('I am rich'),
        ),
      ),
    ),
  );
}
```

## Output on using `flutter run`

```bash
[  +16 ms] executing: [/home/techmirtz/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e6b34c2b5c96bb95325269a29a84e83ed8909b5f
[        ] executing: [/home/techmirtz/flutter/] git tag --contains HEAD
[ +192 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.0
           1.17.0-3.4.pre
           1.17.1
           1.17.2
           1.17.3
           1.17.4
           1.17.5
[   +7 ms] executing: [/home/techmirtz/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/techmirtz/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +91 ms] executing: [/home/techmirtz/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +21 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb devices -l
[  +53 ms] List of devices attached
           J7AAGF06T826H7Z        device usb:1-1 product:WW_X00TD model:ASUS_X00TD device:ASUS_X00T_2 transport_id:2
[  +18 ms] /home/techmirtz/Android/Sdk/platform-tools/adb -s J7AAGF06T826H7Z shell getprop
[ +179 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +394 ms] Generating /home/techmirtz/projects/flutter_apps/iamrich/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +30 ms] ro.hardware = qcom
[  +33 ms] Launching lib/main.dart on ASUS X00TD in debug mode...
[  +12 ms] /home/techmirtz/flutter/bin/cache/dart-sdk/bin/dart /home/techmirtz/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/techmirtz/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true
--output-dill /tmp/flutter_tool.YQIEBR/app.dill --packages /home/techmirtz/projects/flutter_apps/iamrich/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill
[  +21 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb -s J7AAGF06T826H7Z shell -x logcat -v time -t 1
[  +86 ms] Exit code 0 from: /home/techmirtz/Android/Sdk/platform-tools/adb -s J7AAGF06T826H7Z shell -x logcat -v time -t 1
[        ] --------- beginning of main
           07-27 20:07:22.024 I/ThermalEngine(  995): Sensor:msm_therm:40000 mC
[  +47 ms] <- compile package:iamrich/main.dart
[  +76 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb version
[  +52 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as /home/techmirtz/Android/Sdk/platform-tools/adb
[   +8 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb start-server
[  +40 ms] Building APK
[  +64 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from /home/techmirtz/projects/flutter_apps/iamrich/android/gradlew.
[   +1 ms] /home/techmirtz/projects/flutter_apps/iamrich/android/gradlew mode: 33277 rwxrwxr-x.
[  +13 ms] executing: /home/techmirtz/android-studio/jre/bin/java -version
[ +135 ms] Exit code 0 from: /home/techmirtz/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +8 ms] executing: /home/techmirtz/android-studio/jre/bin/java -version
[  +88 ms] Exit code 0 from: /home/techmirtz/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +7 ms] executing: [/home/techmirtz/projects/flutter_apps/iamrich/android/] /home/techmirtz/projects/flutter_apps/iamrich/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=/home/techmirtz/projects/flutter_apps/iamrich/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+1095 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[   +1 ms] Settings file '/home/techmirtz/projects/flutter_apps/iamrich/android/settings.gradle' line: 15
[   +1 ms] * What went wrong:
[        ] A problem occurred evaluating settings 'android'.
[   +1 ms] > Could not read script '/home/techmirtz/flutter/packages/flutter_tools/gradle/app_plugin_loader.gradle' as it does not exist.
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +4 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 962ms
[ +424 ms] Running Gradle task 'assembleDebug'... (completed in 1.8s)
[+5490 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 8,513ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:609:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _runZoned (dart:async/zone.dart:1619:10)
#19     runZoned (dart:async/zone.dart:1539:10)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZonedGuarded (dart:async/zone.dart:1608:12)
#31     runZoned (dart:async/zone.dart:1536:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     run.<anonymous closure> (package:flutter_tools/runner.dart)
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#37     _rootRun (dart:async/zone.dart:1184:13)
#38     _CustomZone.run (dart:async/zone.dart:1077:19)
#39     _runZoned (dart:async/zone.dart:1619:10)
#40     runZoned (dart:async/zone.dart:1539:10)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#42     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#43     run (package:flutter_tools/runner.dart:48:10)
#44     main (package:flutter_tools/executable.dart:69:9)
#45     main (file:///home/techmirtz/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

`flutter doctor -v`

```bash
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.0 at /home/techmirtz/flutter
    • Framework revision e6b34c2b5c (3 months ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/techmirtz/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/techmirtz/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/techmirtz/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • ASUS X00TD • <SERIAL_NUMBER> • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by YazeedAlKhalaf** [comment]
From what I can see, you have a missing file:
```
[+1095 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[   +1 ms] Settings file '/home/techmirtz/projects/flutter_apps/iamrich/android/settings.gradle' line: 15
[   +1 ms] * What went wrong:
[        ] A problem occurred evaluating settings 'android'.
[   +1 ms] > Could not read script '/home/techmirtz/flutter/packages/flutter_tools/gradle/app_plugin_loader.gradle' as it does not exist.
```

What I suggest is doing the following:

1) creating a new project and running it, check if the failure is from the project itself or not.
2) (recommended) delete your current flutter installation and download a new one. 
`flutter/packages/flutter_tools/gradle/app_plugin_loader.gradle` this fille is missing which is from the framework itself

**Comment by chauhannaman98** [comment]
> 2\. (recommended) delete your current flutter installation and download a new one.

I noticed that there were more files absent there in `gradle/` folder. I reinstalled it using an easy way of snap on my Linux machine.
As recommended, I have reinstalled the SDK. But I don't know the reason why those files got deleted from the SDK directory?
