### ISSUE TITLE
[add-to-app] Error while merging dex archives: BuildConfig defined multiple times

### ISSUE THREAD

**Issue by arnemolland** [flutter/flutter#62388]
Note: tested with Android Studio Gradle plugin 3.6.3, 3.6.4 and 4.0.0 as well as `multiDexEnabled` set to both `true`and `false`

## Steps to Reproduce

1. Create Android project
2. Create Flutter module
3. `flutter packages get` in Flutter module
3. Run Android release build

**Expected results:** 
Successful build

**Actual results:** 
BuildConfig defined multiple times
```
Execution failed for task ':app:mergeDexUatRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type no.dnb.bmpuls.BuildConfig is defined multiple times: /Users/arnemolland/dnb/puls/android/app/build/intermediates/
project_dex_archive/uatRelease/out/no/dnb/bmpuls/BuildConfig.dex, /Users/arnemolland/dnb/puls/android/flutter-module/.andro
id/Flutter/build/.transforms/2224dc58b465bff14e446c1db23e5b4e/classes/classes.dex
```

<details>
  <summary>Gradle logs</summary>

```
Task :app:mergeDexUatRelease FAILED
/Users/arnemolland/dnb/puls/android/app/build/intermediates/project_dex_archive/uatRelease/out/no/dnb/bmpuls/BuildConfig.de
x: D8: Type no.dnb.bmpuls.BuildConfig is defined multiple times: /Users/arnemolland/dnb/puls/android/app/build/intermediate
s/project_dex_archive/uatRelease/out/no/dnb/bmpuls/BuildConfig.dex, /Users/arnemolland/dnb/puls/android/flutter-module/.and
roid/Flutter/build/.transforms/2224dc58b465bff14e446c1db23e5b4e/classes/classes.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type no.dnb.bmpuls.BuildConfig is defined multiple times: /Users/arnemolland/dnb/puls/android/app/build/intermediates/proje
ct_dex_archive/uatRelease/out/no/dnb/bmpuls/BuildConfig.dex, /Users/arnemolland/dnb/puls/android/flutter-module/.android/Fl
utter/build/.transforms/2224dc58b465bff14e446c1db23e5b4e/classes/classes.dex
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:119)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102
)
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:441)
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:242)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:198)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.W.a(:87)
        at com.android.tools.r8.D8.run(:11)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
        ... 33 more
Caused by: com.android.tools.r8.utils.b: Error: /Users/arnemolland/dnb/puls/android/app/build/intermediates/project_dex_archive/uatRelease/out/no/dnb/bmpuls/BuildConfig.dex, Type no.dnb.bmpuls.BuildConfig is defined multiple times: /Users/arnemolland/dnb/puls/android/app/build/intermediates/project_dex_archive/uatRelease/out/no/dnb/bmpuls/BuildConfig.dex, /Users/arnemolland/dnb/puls/android/flutter-module/.android/Flutter/build/.transforms/2224dc58b465bff14e446c1db23e5b4e/classes/classes.dex
        at Version.fakeStackEntry(Version_2.0.74.java:0)
        at com.android.tools.r8.utils.M0.a(:21)
        at com.android.tools.r8.utils.L0.b(:7)
        at com.android.tools.r8.utils.L0.a(:27)
        at com.android.tools.r8.utils.L0.a(:10)
        at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
        at com.android.tools.r8.utils.L0.a(:6)
        at com.android.tools.r8.graph.D0$c.f(:3)
        at com.android.tools.r8.dex.a.a(:83)
        at com.android.tools.r8.dex.a.a(:10)
        at com.android.tools.r8.D8.d(:6)
        at com.android.tools.r8.D8.b(:1)
        at com.android.tools.r8.utils.W.a(:30)
        ... 35 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexUatRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type no.dnb.bmpuls.BuildConfig is defined multiple times: /Users/arnemolland/dnb/puls/android/app/build/intermediates/
project_dex_archive/uatRelease/out/no/dnb/bmpuls/BuildConfig.dex, /Users/arnemolland/dnb/puls/android/flutter-module/.andro
id/Flutter/build/.transforms/2224dc58b465bff14e446c1db23e5b4e/classes/classes.dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --s
can to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings
```

`flutter analyze`
```
flutter analyze     
Analyzing flutter-module...                                             
No issues found! (ran in 3.5s)
```
</details>

**Comment by TahaTesser** [comment]
Hi @arnemolland 
Can you please provide your `flutter doctor -v` 
Thank you

**Comment by arnemolland** [comment]
Sure!
<details>
<summary>flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, v1.17.5, on macOS 10.16 20A4300b, locale en-NO)
    • Flutter version 1.17.5 at /Users/arnemolland/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/arnemolland/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • ANDROID_HOME = /Users/arnemolland/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/arnemolland/Library/Android/sdk
    • Java binary at: /Users/arnemolland/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A8169g
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/arnemolland/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (1 available)            
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment]
Hi @arnemolland 
Please try code sample attached, no issues on stable channel 

[a2a.zip](https://github.com/flutter/flutter/files/4988716/a2a.zip)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.17.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

**Comment by arnemolland** [comment]
Thanks @TahaTesser, I resolved the issue after a deeper look!

The flutter module was set up with the same bundle identifier as the host application, resulting in identical packages/classes being generated, explaining in the `Type no.dnb.bmpuls.BuildConfig is defined multiple times` message. Might be worth noting in the a2a docs.

Original pubspec.yaml:
```yaml
flutter:
  module:
    androidX: true
    androidPackage: no.dnb.bmpuls
    iosBundleIdentifier: no.dnb.bmpuls
```

Updated pubspec.yaml:
```yaml
flutter:
  module:
    androidX: true
    androidPackage: no.dnb.bmpuls_flutter
    iosBundleIdentifier: no.dnb.bmpulsFlutter
```
