### ISSUE TITLE
Error "The Flutter Daemon has terminated" after waking PC from sleep mode

### ISSUE THREAD

**Issue by kinex** [flutter/flutter#62398]
I see error dialogs "The Flutter Daemon has terminated." and "Cannot call write after a stream was destroyed."  every time I wake up my PC from sleep mode and try to start a new debug session. 

Steps to reproduce:
1. Connect a device to USB cable for debugging
2. Open your Flutter project in VS Code
3. Start a debug session, works normally
4. Stop the debug session
5. Put your PC to sleep
6. Wake up your PC
7. Try starting a new debug session
8. The error dialogs are shown and debugging is not started
9. Click "Cancel" button in the "Cannot call write after a stream was destroyed." dialog and the "Restart" button in the "The Flutter Daemon has terminated." dialog.
10. Start a debug session, now it works again.

Log created with these steps:
- Run flutter daemon -v from a terminal
- Paste in [{"id":"2","method":"device.enable"}] and press enter
- Wait for your device to show up in the JSON output
- Put your PC to sleep
- Wake your PC

```
.
.
.
[   +6 ms] Starting device daemon...
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":23088}}]
[{"id":"2","method":"device.enable"}]
[{"id":"2","result":[null,null,null]}]
[+12447 ms] executing: c:\tools\android-sdk\platform-tools\adb.exe devices -l
[  +84 ms] List of devices attached
           ad0c16039914a951e1     device product:heroltexx model:SM_G930F device:herolte transport_id:12
[{"event":"device.added","params":{"id":"ad0c16039914a951e1","name":"SM G930F","platform":"android-arm64","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
[+4008 ms] executing: c:\tools\android-sdk\platform-tools\adb.exe devices -l
[  +87 ms] List of devices attached
           ad0c16039914a951e1     device product:heroltexx model:SM_G930F device:herolte transport_id:12
[+4003 ms] executing: c:\tools\android-sdk\platform-tools\adb.exe devices -l
[  +76 ms] List of devices attached
           ad0c16039914a951e1     device product:heroltexx model:SM_G930F device:herolte transport_id:12
[+4003 ms] executing: c:\tools\android-sdk\platform-tools\adb.exe devices -l
[  +81 ms] List of devices attached
           ad0c16039914a951e1     device product:heroltexx model:SM_G930F device:herolte transport_id:12
[+4004 ms] executing: c:\tools\android-sdk\platform-tools\adb.exe devices -l
[  +73 ms] List of devices attached
           ad0c16039914a951e1     device product:heroltexx model:SM_G930F device:herolte transport_id:12
[+4002 ms] executing: c:\tools\android-sdk\platform-tools\adb.exe devices -l
[+25213 ms] adb.exe F 07-28 13:23:35  1384  6580 fdevent_poll.cpp:64] failed to create fdevent interrupt socketpair: Invalid argument
Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: c:\tools\android-sdk\platform-tools\adb.exe

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:62:7)
<asynchronous suspension>
#2      PollingDeviceDiscovery._initTimer.<anonymous closure> (package:flutter_tools/src/device.dart:300:44)
#3      _rootRun (dart:async/zone.dart:1180:38)
#4      _CustomZone.run (dart:async/zone.dart:1077:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @kinex 
Following your steps, i cannot reproduce the issue on Windows 10 

`flutter daemon -v` 

<details> 
<summary>logs</summary> 

``` 
[  +15 ms] executing: [C:\Code\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[   +1 ms] executing: [C:\Code\flutter/] git tag --contains HEAD
[ +173 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.5
[   +7 ms] executing: [C:\Code\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Code\flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +67 ms] executing: [C:\Code\flutter/] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +27 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +20 ms] Starting device daemon...
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":9352}}]
 [{"id":"2","method":"device.enable"}]
[+204382 ms] "flutter daemon" took 204,523ms.
Terminate batch job (Y/N)? y
PS C:\Users\Taha\AndroidStudioProjects\example_app> flutter devices -v
[  +15 ms] executing: [C:\Code\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[        ] executing: [C:\Code\flutter/] git tag --contains HEAD
[ +170 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.5
[   +7 ms] executing: [C:\Code\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Code\flutter/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +69 ms] executing: [C:\Code\flutter/] git rev-parse --abbrev-ref HEAD
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +27 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +20 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +32 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:3
[   +5 ms] 1 connected device:

[   +8 ms] C:\Code\sdk\platform-tools\adb.exe -s 32003c30dc19668f shell getprop
[ +121 ms] ro.hardware = exynos7904
[   +1 ms] ro.build.characteristics = phone
[   +3 ms] SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)
[   +7 ms] "flutter devices" took 317ms.
PS C:\Users\Taha\AndroidStudioProjects\example_app> flutter daemon -v 
[  +15 ms] executing: [C:\Code\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +42 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[        ] executing: [C:\Code\flutter/] git tag --contains HEAD
[ +181 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.5
[   +7 ms] executing: [C:\Code\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Code\flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[  +71 ms] executing: [C:\Code\flutter/] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +26 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +20 ms] Starting device daemon...
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":7184}}]
[{"id":"1","method":"device.enable"}]
[{"id":"1","result":[null,null,null]}]
[+15078 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +25 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:3
[{"event":"device.added","params":{"id":"32003c30dc19668f","name":"SM M305F","platform":"android-arm64","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
[+4016 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +19 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:3
[+433264 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +24 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:3
[+4014 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +21 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:4
[+4008 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +25 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:4
[+4007 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +21 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:4
[+4016 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +22 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:4
[+4018 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +20 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:4
[+4009 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +20 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:4
[+4013 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +18 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:4
^A[{"id":"1","method":"device.enable"}][+4016 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +20 ms] List of devices attached
           32003c30dc19668f       device product:m30ltedd model:SM_M305F device:m30lte transport_id:4
[+1426 ms] "flutter daemon" took 486,269ms.
Terminate batch job (Y/N)? y
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.17.5 at C:\Code\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details> 

Do you have any power saving mode on? Antiivirus?

**Comment by kinex** [comment]
Hi @TahaTesser, Good to know the issue does not occur in your device. In my PC this issue happens every time (=several times a day, that's why it is so annoying) . Yes I have Antivirus (F-Secure) installed. I can try disabling AV when I am back at office next week. I will then check also my power saving settings.

**Comment by kinex** [comment]
The issue does not occur if I disable AV. My power saving settings are the default ones (this is a desktop PC, not a laptop).

**Comment by TahaTesser** [comment]
Hi @kinex 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.  
This can be addressed by https://github.com/flutter/flutter/issues/61997
Thank you

**Comment by kinex** [comment]
OK I guess this can be closed if you document what exactly needs to be excluded from AV to fix this. 

I already tried adding these folders to the AV exclude list, but it didn't solve the issue:
Flutter SDK dir
Android SDK dir
project dir
pub cache dir

I have always had this same AV installed, but this issue appeared few months ago (I think it was after some Flutter upgrade).

**Comment by jmagman** [comment]
It looks like `c:\tools\android-sdk\platform-tools\adb.exe` is the thing being killed? The polling discoverers should maybe be more resilient to temporary failures and retry?

**Comment by kinex** [comment]
I verified again that adding `c:\tools\android-sdk` to AV exclude list does not help.

Maybe this line in the log is the important one:
`[+25213 ms] adb.exe F 07-28 13:23:35  1384  6580 fdevent_poll.cpp:64] failed to create fdevent interrupt socketpair: Invalid argument`

This other error in the log does not make sense to me (there should not be any problems running `adb`, it is also in the PATH): 
`Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: c:\tools\android-sdk\platform-tools\adb.exe`.

**Comment by d-khomenko** [comment]
same
