### ISSUE TITLE
FormatException: FormatException: No ':' on line (at offset 7443) Upon Opening emulator on VSCode

### ISSUE THREAD

**Issue by ConfidenceYobo** [flutter/flutter#62391]
## Steps to Reproduce

- Open emulator with `flutter run --machine --target lib\main.dart -d emulator-5554 --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused`

**Expected results:** 

## flutteer_01.log file output

flutter run --machine --target lib\main.dart -d emulator-5554 --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused

## exception

FormatException: FormatException: No ':' on line (at offset 7443)

```
#0      parse (package:package_config/packages_file.dart:64:7)
#1      _parse (package:flutter_tools/src/dart/package_map.dart:17:10)
#2      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:49:14)
#3      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:53:5)
#4      new PackageUriMapper (package:flutter_tools/src/compile.dart:199:116)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:647:26)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:408:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:388:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:693:23)
#9      _rootRunUnary (dart:async/zone.dart:1192:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#16     _rootRun (dart:async/zone.dart:1180:38)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#20     _rootRun (dart:async/zone.dart:1184:13)
#21     _CustomZone.run (dart:async/zone.dart:1077:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\HP\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

**Comment by ConfidenceYobo** [comment]
Issue fixed by deleting `.dart_tool` directory generated by VSCode. A new `.dart_tool` directory was created when once I reopened the project and everything was fine.
