### ISSUE TITLE
[flutter_web]  AnimatedOpacity is crashing

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#62408]
I'm using AnimatedOpacity to show and hide a widget.

It works ok when showing and hiding the first time, but if I show it again, I get this.

<details>
<summary> Logs</summary>

```
Exception has occurred.
"Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/clip.dart:295:12
_clipElement == null
is not true
    at Object.throw_ [as throw] (http://localhost:45319/dart_sdk.js:4322:11)
    at Object.assertFailed (http://localhost:45319/dart_sdk.js:4271:15)
    at _engine.PersistedPhysicalShape.new.[_applyShape] (http://localhost:45319/dart_sdk.js:152095:47)
    at _engine.PersistedPhysicalShape.new.apply (http://localhost:45319/dart_sdk.js:152013:24)
    at _engine.PersistedPhysicalShape.new.build (http://localhost:45319/dart_sdk.js:150428:12)
    at _engine.PersistedPhysicalShape.new.build (http://localhost:45319/dart_sdk.js:150649:13)
    at _engine.PersistedOffset.new.build (http://localhost:45319/dart_sdk.js:150665:17)
    at _engine.PersistedOffset.new.build (http://localhost:45319/dart_sdk.js:150665:17)
    at _engine.PersistedOffset.new.build (http://localhost:45319/dart_sdk.js:150665:17)
    at _engine.PersistedOffset.new.build (http://localhost:45319/dart_sdk.js:150665:17)
    at _engine.PersistedOpacity.new.build (http://localhost:45319/dart_sdk.js:150665:17)
    at _engine.PersistedTransform.new.[_updateManyToMany] (http://localhost:45319/dart_sdk.js:150860:22)
    at _engine.PersistedTransform.new.update (http://localhost:45319/dart_sdk.js:150691:32)
    at _engine.PersistedTransform.new.update (http://localhost:45319/dart_sdk.js:160161:13)
    at _engine.PersistedPhysicalShape.new.[_updateManyToMany] (http://localhost:45319/dart_sdk.js:150848:20)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:45319/dart_sdk.js:150691:32)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:45319/dart_sdk.js:152122:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45319/dart_sdk.js:150786:18)
    at _engine.PersistedOffset.new.update (http://localhost:45319/dart_sdk.js:150687:31)
    at _engine.PersistedOffset.new.update (http://localhost:45319/dart_sdk.js:152521:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:45319/dart_sdk.js:150786:18)
    at _engine.PersistedOffset.new.update (http://localhost:45319/dart_sdk.js:150687:31)
    at _engine.PersistedOffset.new.update (http://localhost:45319/dart_sdk.js:152521:13)
    at _engine.PersistedTransform.new.[_updateManyToOne] (http://localhost:45319/dart_sdk.js:150786:18)
    at _engine.PersistedTransform.new.update (http://localhost:45319/dart_sdk.js:150687:31)
    at _engine.PersistedTransform.new.update (http://localhost:45319/dart_sdk.js:160161:13)
    at _engine.PersistedScene.new.[_updateManyToOne] (http://localhost:45319/dart_sdk.js:150786:18)
    at _engine.PersistedScene.new.update (http://localhost:45319/dart_sdk.js:150687:31)
    at http://localhost:45319/dart_sdk.js:159907:33
    at Object.timeAction (http://localhost:45319/dart_sdk.js:168719:14)
    at _engine.SurfaceSceneBuilder.new.build (http://localhost:45319/dart_sdk.js:159903:22)
    at layer$.TransformLayer.new.buildScene (http://localhost:45319/packages/flutter/src/rendering/layer.dart.lib.js:1132:27)
    at view.RenderView.new.compositeFrame (http://localhost:45319/packages/flutter/src/rendering/layer.dart.lib.js:4370:32)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:45319/packages/flutter/src/rendering/layer.dart.lib.js:5405:25)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:45319/packages/flutter/src/widgets/widget_span.dart.lib.js:44386:15)
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:45319/packages/flutter/src/rendering/layer.dart.lib.js:5381:12)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:45319/packages/flutter/src/scheduler/binding.dart.lib.js:727:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:45319/packages/flutter/src/scheduler/binding.dart.lib.js:699:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:45319/packages/flutter/src/scheduler/binding.dart.lib.js:656:12)
    at Object._invoke (http://localhost:45319/dart_sdk.js:170562:7)
    at _engine.EngineWindow.new.invokeOnDrawFrame (http://localhost:45319/dart_sdk.js:167120:15)
    at http://localhost:45319/dart_sdk.js:167678:28"
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-7.2.pre at /home/steve/google/flutter
    • Framework revision a2bde82fbd (10 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/steve/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/steve/google/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/steve/google/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • HD1905 (mobile)  • 0fa54b6e   • android-arm64  • Android 10 (API 29)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment]
Hi @sgehrman 
Can you please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
