### ISSUE TITLE
Image.network() with random errors when loading long list of images

### ISSUE THREAD

**Issue by 2math** [flutter/flutter#62406]
**When I try to load 100+ network images in a GridView and scrolling in both directions, some of the Images show this error in the logs :**

```
I/flutter (24285): setState() called after dispose(): _ImageState#6154c(lifecycle state: defunct, not mounted, stream: ImageStream#a0644(MultiFrameImageStreamCompleter#07c2a, unresolved, 2 listeners), pixels: null, loadingProgress: ImageChunkEvent#7c2a6(cumulativeBytesLoaded: 14320, expectedTotalBytes: 5185751), frameNumber: null, wasSynchronouslyLoaded: false)
I/flutter (24285): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
I/flutter (24285): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
I/flutter (24285): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been rem
I/flutter (24285): 
I/flutter (24285): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
I/flutter (24285): #1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
I/flutter (24285): #2      _ImageState._handleImageChunk (package:flutter/src/widgets/image.dart:1137:5)
I/flutter (24285): #3      new MultiFrameImageStreamCompleter.<anonymous closure> (package:flutter/src/painting/image_stream.dart:638:23)
I/flutter (24285): #4      _rootRunUnary (dart:async/zone.dart:1192:38)
I/flutter (24285): #5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
I/flutter (24285): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
I/flutter (24285): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter (24285): #8      _DelayedData.perform (dart:async/stream_impl.dart:594:14)
I/flutter (24285): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
I/flutter (24285): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
I/flutter (24285): #11     _rootRun (dart:async/zone.dart:1180:38)
I/flutter (24285): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
I/flutter (24285): #13     _CustomZone.runGuarded (dart:async/zone.dart:9
```

**The only way to prevent this was by overriding Image._handleImageFrame method**

  ```
void _handleImageFrame(ImageInfo imageInfo, bool synchronousCall) {
    if(!mounted) return;**// this is new**
    setState(() {
      _imageInfo = imageInfo;
      _loadingProgress = null;
      _frameNumber = _frameNumber == null ? 0 : _frameNumber + 1;
      _wasSynchronouslyLoaded |= synchronousCall;
    });
  }

</details>
```

**Comment by darshankawar** [comment]
Hi @2math,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by niyaode** [comment]
```
FadeInImage.assetNetwork(
                width: 260.rpx,
                height: 260.rpx,
                placeholder: "assets/images/loading.png",
                image: headImage,
                imageErrorBuilder: (context, error, stackTrace) {
                  return Image.asset(
                    "assets/images/load_err.png",
                    height: 260.rpx,
                    width: 260.rpx,
                  );
                },
                fit: BoxFit.cover,
              ),
```
### I also have this problem
```
if(mounted) { 
        setState(() {
          this.loadMore = 0;
          this.list.addAll(list);
        });
      }
```
It will also fail
When the number increases, there is a flicker

**Comment by darshankawar** [comment]
Hi @2math,
Please also provide `flutter doctor -v`.
Thanks.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
