### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by navaneeth-algorithm** [flutter/flutter#62432]
## Command
```
flutter --quiet assemble --depfile /media/navaneeth/Coder/ProgrammingLanguage/FlutterProjects/scan_pdf/build/app/intermediates/flutter/release/flutter_build.d --output /media/navaneeth/Coder/ProgrammingLanguage/FlutterProjects/scan_pdf/build/app/intermediates/flutter/release -dTargetFile=/media/navaneeth/Coder/ProgrammingLanguage/FlutterProjects/scan_pdf/lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true android_aot_bundle_release_android-arm
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:458:47)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#5      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:696:26)
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:584:5)
<asynchronous suspension>
#7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _runZoned (dart:async/zone.dart:1630:10)
#15     runZoned (dart:async/zone.dart:1550:10)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Linux, locale en_IN)
    • Flutter version 1.20.0-7.2.pre at /home/navaneeth/Flutter/flutter
    • Framework revision a2bde82fbd (10 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/navaneeth/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/navaneeth/Android/Sdk
    • Java binary at: /media/navaneeth/Coder/AndroidStudio/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /media/navaneeth/Coder/AndroidStudio/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • vivo 1603 (mobile) • fa3dcd4    • android-arm    • Android 6.0.1 (API 23)
    • Web Server (web)   • web-server • web-javascript • Flutter Tools
    • Chrome (web)       • chrome     • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 8fe7655ed20ffd1395f68e30539a847a01a30351
### Plugins
share
bitmap-0.0.6
flutter_image_compress-0.7.0
flutter_plugin_android_lifecycle-1.0.8
flutter_share-1.0.2+1
image_cropper-1.2.3
image_picker-0.6.7+4
multi_image_picker-4.6.9
open_file-3.0.1
opencv-1.0.2
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
permission_handler-5.0.1+1

**Comment by darshankawar** [comment]
Hi @navaneeth-algorithm,
I see there's a similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
