### ISSUE TITLE
Tell phone url lauching

### ISSUE THREAD

**Issue by joshua750** [flutter/flutter#62436]
```
2020-07-28 13:05:24.685160-0400 Runner[3447:2082257] [VERBOSE-
2:ui_dart_state.cc(157)] Unhandled Exception: 
PlatformException(NOT_A_WEB_SCHEME, To use webview or safariVC, you 
need to passin a web URL. This tel://18002509646 is not a web URL., null)

#0 launch (package:url_launcher/url_launcher.dart:71:5)
#1 Contactcus.customLaunch (package:tv/Contactus.dart:21:9)
<asynchronous suspension>
#2 Contactcus.build.<anonymous closure> (package:tv/Contactus.dart:65:35)
#3 _InkResponseState._handleTap 
(package:flutter/src/material/ink_well.dart:779:19)
#4 _InkResponseState.build.<anonymous closure> 
(package:flutter/src/material/ink_well.dart:862:36)
#5 GestureRecognizer.invokeCallback 
(package:flutter/src/gestures/recognizer.dart:182:24)
#6 TapGestureRecognizer.handleTapUp 
(package:flutter/src/gestures/tap.dart:504:11)
#7 BaseTapGestureRecognizer._checkUp 
(package:flutter/src/gestures/tap.dart:282:5)
#8 BaseTapGestureRecognizer.acceptGesture 
(package:flutter/src/gestures/tap.dart:254:7)
#9 GestureArenaManager.sweep 
(package:flutter/src/gestures/arena.dart:156:27)
#10 GestureBinding.handleEvent 
(package:flutter/src/gestures/binding.dart:222:20)
#11 GestureBinding.dispatchEvent 
(package:flutter/src/gestures/binding.dart:198:22)
#12 GestureBinding._handlePointerEvent 
(package:flutter/src/gestures/binding.dart:156:7)
#13 GestureBinding._flushPointerEventQueue 
(package:flutter/src/gestures/binding.dart:102:7)
#14 GestureBinding._handlePointerDataPacket 
(package:flutter/src/gestures/binding.dart:86:7)
#15 _rootRunUnary (dart:async/zone.dart:1196:13)
#16 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17 _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#18 _invoke1 (dart:ui/hooks.dart:275:10)
#19 _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

**Comment by darshankawar** [comment]
Hi @joshua750,
There's no info / description of the issue you are facing.
If you want to dial a phone number using `url_launcher` plugin, then follow the official example of the plugin [here](https://pub.dev/packages/url_launcher/example).
If problem persists, please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
