### ISSUE TITLE
latest master shows wrong icon

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#62472]
Hi, triaging this [issue](https://github.com/flutter/flutter/issues/47041#issuecomment-665466425)
I noticed that the latest master shows wrong icons

<details><summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/88766879-7872d780-d181-11ea-8030-a7f20890be27.png)

![image](https://user-images.githubusercontent.com/45637986/88767800-cdfbb400-d182-11ea-8ad1-b98384c37988.png)

</details>

<details><summary>logs</summary>

```bash
[ +348 ms] Debug service listening on ws://127.0.0.1:61063/KsukpaPa_i4=
[   +4 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +1 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +4 ms] For a more detailed help message, press "h". To quit, press "q".
[+2275 ms] Cannot find native JavaScript type (CanvasKit) for type check

[ +734 ms] Cannot find native JavaScript type (SkParagraph) for type check

[  +69 ms] Error: Unsupported operation: Picture.toImage not yet implemented for CanvasKit and HTML
               at Object.throw_ [as throw] (http://localhost:61030/dart_sdk.js:4324:11)
               at _engine.CkPicture.new.toImage (http://localhost:61030/dart_sdk.js:140618:17)
               at DefaultShaderWarmUp.execute (http://localhost:61030/packages/flutter/src/painting/shader_warm_up.dart.lib.js:106:23)
               at execute.next (<anonymous>)
               at http://localhost:61030/dart_sdk.js:37349:33
               at _RootZone.runUnary (http://localhost:61030/dart_sdk.js:37203:58)
               at _FutureListener.thenAwait.handleValue (http://localhost:61030/dart_sdk.js:32187:29)
               at handleValueCallback (http://localhost:61030/dart_sdk.js:32734:49)
               at Function._propagateToListeners (http://localhost:61030/dart_sdk.js:32772:17)
               at _Future.new.[_completeWithValue] (http://localhost:61030/dart_sdk.js:32615:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:61030/dart_sdk.js:32637:35)
               at Object._microtaskLoop (http://localhost:61030/dart_sdk.js:37464:13)
               at _startMicrotaskLoop (http://localhost:61030/dart_sdk.js:37470:13)
               at http://localhost:61030/dart_sdk.js:32989:9
[ +495 ms] Cannot find native JavaScript type (SkParagraph) for type check

[  +11 ms] Cannot find native JavaScript type (SkParagraph) for type check

[   +5 ms] Cannot find native JavaScript type (SkParagraph) for type check

[   +6 ms] Cannot find native JavaScript type (SkParagraph) for type check

[  +31 ms] Cannot find native JavaScript type (SkMaskFilter) for type check

[   +4 ms] Cannot find native JavaScript type (SkParagraph) for type check

[+9484 ms] Cannot find native JavaScript type (SkParagraph) for type check

[  +13 ms] Cannot find native JavaScript type (SkMaskFilter) for type check

[+23045 ms] Stopped debug service on ws://127.0.0.1:61063

[  +43 ms] Application finished.
[   +3 ms] "flutter run" took 56,106ms.
[   +7 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +96 ms] Shutdown hooks complete
[        ] exiting with code 0
```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.89, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.89 at /Users/nevercode/development/flutter_master
    • Framework revision ddb6d9d913 (4 hours ago), 2020-07-28 19:56:03 -0700
    • Engine revision 2d8a00e21d
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

Thank you

**Comment by iapicca** [comment]
Nevermind,
seems fixed with the new master

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/88772451-7a409900-d189-11ea-969b-39303ab77360.png)

</details>

<details><summary>logs</summary>

```console
[✓] Flutter: is fully installed. (Channel master, 1.21.0-6.0.pre.90, on Mac OS X 10.15.5 19F101, locale en-GB)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.5)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 4.0)
[✓] VS Code: is fully installed.
[✓] Connected device: is fully installed. (4 available)
```

</details>

Thanks @VladyslavBondarenko
