### ISSUE TITLE
Error when click FAB and textfield scroll to bottom of page

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#62477]
Here is the UI:

![image](https://user-images.githubusercontent.com/21303438/88776071-1386a400-d1b8-11ea-8b82-e3b1883a8fb7.png)

When I edit textfiled and scrolled the text filed to bottom, click FAB, it throws error:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter 'properties' was called on null.
Receiver: null
Tried calling: properties
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2961:113)
#2      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1250:63)
#3      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1128:14)
#4      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:955:11)
#5      FlutterError.onError.<anonymous closure> (package:flutter/src/foundation/assertions.dart:872:89)
#6      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1087:14)
#7      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:202:22)
#8      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#11     _rootRunUnary (dart:async/zone.dart:1206:13)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#14     _invoke1 (dart:ui/hooks.dart:267:10)
#15     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)

```

Does anybody knows this?

**Comment by TahaTesser** [comment]
Hi @jinfagang 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by jinfagang** [comment]
```
 flutter doctor -v                
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Linux, locale en_HK.UTF-8)
    • Flutter version 1.21.0-1.0.pre at /home//development/flutter
    • Framework revision f25bd9c55c (2 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home//Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
    • cmake version 3.17.1
    • ninja version 1.9.0.git.kitware.dyndep-1.jobserver-1
    • pkg-config version 0.29.1

[!] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.

```

I am call it in exectuable

**Comment by TahaTesser** [comment]
@jinfagang 
Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
