### ISSUE TITLE
FlutterError.onError doesn't catch Dart exceptions (e.g. in the 'Crashy' example)

### ISSUE THREAD

**Issue by alexobviously** [flutter/flutter#62490]
I've been trying to set up Sentry.io with Flutter with no success. I thought it was just something to do with my code but since an official Flutter example behaves in the same way, I assume it isn't. In the ['Crashy' example](https://github.com/flutter/crashy), which demonstrates how to integrate Sentry, there are three buttons: 'Dart exception', 'async Dart exception' and 'Java exception'. The latter two get caught by FlutterError.onError and run whatever code is in it. The first one, 'Dart exception', however, does not. I'm not an expert, but it seems like these exceptions are getting caught by something in Flutter before they can get to FlutterError, which only handles uncaught exceptions?

To reproduce:
Run the code in this repository: https://github.com/flutter/crashy

For async Dart exception, you will get some output like this:
```
`I/flutter (10543): Caught error: Bad state: This is an async Dart exception.
I/flutter (10543): #0      MyHomePage.build.<anonymous closure>.foo (package:crashy/main.dart:150:19)
I/flutter (10543): #1      MyHomePage.build.<anonymous closure>.bar (package:crashy/main.dart:153:28)
I/flutter (10543): #2      MyHomePage.build.<anonymous closure> (package:crashy/main.dart:155:26)
I/flutter (10543): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
I/flutter (10543): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
I/flutter (10543): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (10543): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
I/flutter (10543): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
I/flutter (10543): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
I/flutter (10543): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
I/flutter (10543): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
I/flutter (10543): #11     PointerRoute
I/flutter (10543): In dev mode. Not sending report to Sentry.io.`
```

For 'Dart exception', you will get some output like this:
```
`════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following StateError was thrown while handling a gesture:
Bad state: This is a Dart exception.

When the exception was thrown, this was the stack: 
#0      MyHomePage.build.<anonymous closure> (package:crashy/main.dart:142:17)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#83092
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(235.7, 351.4)
  finalLocalPosition: Offset(92.0, 35.7)
  button: 1
  sent tap down`

```

Also in the meantime if anyone has a functional workaround for Sentry integration I would much appreciate it, because I really need it working on a live app.

**Comment by darshankawar** [comment]
Hi @alexobviously,
I see there's a similar open issue describing your case, [48972](https://github.com/flutter/flutter/issues/48972).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
