### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = '/Users/apple/App/berlin_transport/.packages' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by prasanthlrb** [flutter/flutter#62498]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=QDT4C17B25007319 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = '/Users/apple/App/berlin_transport/.packages' (OS Error: Operation not permitted, errno = 1)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:213:19)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:706:17)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/apple/Developer/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • BND AL10 • QDT4C17B25007319 • android-arm64 • Android 9 (API 28)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 7a4c33425ddd78c54aba07d86f3f9a4a0051769b

**Comment by jonahwilliams** [comment]
Fixed by https://github.com/flutter/flutter/pull/57077 (will be in next stable)
