### ISSUE TITLE
Impossible assert?

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#6253]
```
16:19:06.719: I/flutter : ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
16:19:06.726: I/flutter : The following assertion was thrown while routing a pointer event:
16:19:06.729: I/flutter : 'package:flutter/src/painting/box_painter.dart': Failed assertion: line 1199 pos 12: '(Point.origin
16:19:06.731: I/flutter : & size).contains(position)' is not true.
16:19:06.831: I/flutter :
16:19:06.834: I/flutter : When the exception was thrown, this was the stack:
16:19:06.841: I/flutter : #2      BoxDecoration.hitTest (package:flutter/src/painting/box_painter.dart:1199:12)
16:19:06.844: I/flutter : #3      RenderDecoratedBox.hitTestSelf (package:flutter/src/rendering/proxy_box.dart:1187:24)
16:19:06.847: I/flutter : #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:58)
16:19:06.850: I/flutter : #5      RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.852: I/flutter : #6      RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:19:06.855: I/flutter : #7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.858: I/flutter : #8      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:101:19)
16:19:06.861: I/flutter : #9      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:146:19)
16:19:06.863: I/flutter : #10     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.866: I/flutter : #11     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:642:12)
16:19:06.869: I/flutter : #12     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.872: I/flutter : #13     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.874: I/flutter : #14     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:19:06.877: I/flutter : #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.879: I/flutter : #16     StoryListRenderBlock.hitTestChildren (/data/user/0/com.google.fuchsia.armadillo/cache/armadillocvzorl/lib/story_list_render_block.dart:85:17)
16:19:06.882: I/flutter : #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.884: I/flutter : #18     RenderViewport.hitTestChildren (package:flutter/src/rendering/viewport.dart:333:20)
16:19:06.887: I/flutter : #19     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.890: I/flutter : #20     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:101:19)
16:19:06.892: I/flutter : #21     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.895: I/flutter : #22     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2137:44)
16:19:06.897: I/flutter : #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:101:19)
16:19:06.900: I/flutter : #24     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:146:19)
16:19:06.902: I/flutter : #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:101:19)
16:19:06.905: I/flutter : #26     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.907: I/flutter : #27     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.910: I/flutter : #28     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:19:06.912: I/flutter : #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.914: I/flutter : #30     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.917: I/flutter : #31     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:19:06.919: I/flutter : #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.922: I/flutter : #33     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.925: I/flutter : #34     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:19:06.927: I/flutter : #35     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.930: I/flutter : #36     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.932: I/flutter : #37     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:19:06.935: I/flutter : #38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.938: I/flutter : #39     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:101:19)
16:19:06.940: I/flutter : #40     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.943: I/flutter : #41     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:218:19)
16:19:06.946: I/flutter : #42     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.949: I/flutter : #43     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.952: I/flutter : #44     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:642:12)
16:19:06.954: I/flutter : #45     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.957: I/flutter : #46     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:101:19)
16:19:06.960: I/flutter : #47     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.963: I/flutter : #48     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.965: I/flutter : #49     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:19:06.968: I/flutter : #50     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.971: I/flutter : #51     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:1597:17)
16:19:06.973: I/flutter : #52     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:424:12)
16:19:06.976: I/flutter : #53     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.979: I/flutter : #54     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:101:19)
16:19:06.981: I/flutter : #55     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:1812:33)
16:19:06.984: I/flutter : #56     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1306:11)
16:19:06.987: I/flutter : #57     RenderView.hitTest (package:flutter/src/rendering/view.dart:130:13)
16:19:06.989: I/flutter : #58     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:224:16)
16:19:06.992: I/flutter : #59     _DragAvatar.updateDrag (/data/user/0/com.google.fuchsia.armadillo/cache/armadillocvzorl/lib/armadillo_drag_target.dart:329:29)
16:19:06.995: I/flutter : #60     _DragAvatar.update (/data/user/0/com.google.fuchsia.armadillo/cache/armadillocvzorl/lib/armadillo_drag_target.dart:311:5)
16:19:06.997: I/flutter : #61     MultiDragPointerState._move (package:flutter/src/gestures/multidrag.dart:84:15)
16:19:07.000: I/flutter : #62     MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:208:13)
16:19:07.002: I/flutter : #63     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
16:19:07.005: I/flutter : #64     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
16:19:07.007: I/flutter : #65     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:122:19)
16:19:07.010: I/flutter : #66     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:100:22)
16:19:07.013: I/flutter : #67     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:81:7)
16:19:07.015: I/flutter : #68     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:40:7)
16:19:07.018: I/flutter : #69     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:33:5)
16:19:07.021: I/flutter : #70     _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:49)
16:19:07.023: I/flutter : (elided 2 frames from class _AssertionError)
16:19:07.026: I/flutter :
16:19:07.028: I/flutter : Event:
16:19:07.031: I/flutter :   PointerMoveEvent(Point(898.0, 35.0))
16:19:07.034: I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by abarth** [comment]
Any idea how to reproduce this issue?

**Comment by apwilson** [comment]
I think I was getting this when dragging something close to the top edge of the screen such that I triggered the android system ui to reveal itself (I'd hidden it on startup).  I'll see if I can reproduce.

**Comment by eseidelGoogle** [comment]
I'm guessing that we can close this now given it's age?  Please feel encouraged to re-open with additional info!
