### ISSUE TITLE
[flutter_tools] Flutter doctor should validate windows host architecture

### ISSUE THREAD

**Issue by rish-hyun** [flutter/flutter#62559]
I have Windows 7 Professional SP 1 32 bit.
I have just finished gathering flutter sdk and dart sdk and I am using VS code.

I created my first app and I encounter this
```
flutter run
Launching lib\main.dart on SM J710F in debug mode...
Running Gradle task 'assembleDebug'...
Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-dwarf_stack_traces causal_async_stacks
no-lazy_async_stacks use_bare_instructions no-dedup_instructions no-"asserts" "use_field_guards" "use_osr" no-code-comments x64-win
no-"null_safety" nnbd-experiment' but the VM has 'release no-dwarf_stack_traces causal_async_stacks no-lazy_async_stacks use_bare_instructions
no-dedup_instructions no-"asserts" "use_field_guards" "use_osr" no-code-comments ia32 no-"null_safety" nnbd-experiment'

the Dart compiler exited unexpectedly.

the Dart compiler exited unexpectedly.
```

I can't figure out what is this

When I run flutter doctor , I get this
```
flutter doctor -v

Oops; flutter has exited unexpectedly: "Invalid argument(s): join(null, "Microsoft VS Code"): part 0 was null, but part 1 was not.".
Unable to generate crash report due to secondary error: Invalid argument(s): join(null, "Microsoft VS Code"): part 0 was null, but part 1 was not.
please let us know at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "Invalid argument(s): join(null, "Microsoft VS Code"): part 0 was null, but part 1 was not.".
Unable to generate crash report due to secondary error: Invalid argument(s): join(null, "Microsoft VS Code"): part 0 was null, but part 1 was not.
please let us know at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:149:7)
#1      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#2      _rootRunBinary (dart:async/zone.dart:1204:38)
#3      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#7      Future._completeError (dart:async/future_impl.dart:534:5)
#8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#9      _informUserOfCrash (package:flutter_tools/runner.dart)
#10     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#11     _rootRunBinary (dart:async/zone.dart:1204:38)
#12     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#13     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#14     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#15     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#16     Future._completeError (dart:async/future_impl.dart:534:5)
#17     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#18     _doctorText (package:flutter_tools/runner.dart)
#19     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#20     _rootRunBinary (dart:async/zone.dart:1204:38)
#21     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#22     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#23     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#24     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#25     Future._completeError (dart:async/future_impl.dart:534:5)
#26     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#27     AppContext.run (package:flutter_tools/src/base/context.dart)
#28     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#29     _rootRunBinary (dart:async/zone.dart:1204:38)
#30     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#31     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#32     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#33     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#34     Future._completeError (dart:async/future_impl.dart:534:5)
#35     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart)
#37     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#38     _rootRunBinary (dart:async/zone.dart:1204:38)
#39     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#40     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#41     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#42     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#43     Future._completeError (dart:async/future_impl.dart:534:5)
#44     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:582:7)
#45     _rootRun (dart:async/zone.dart:1184:13)
#46     _CustomZone.run (dart:async/zone.dart:1077:19)
#47     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
#48     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#51     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#52     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

But when I run this command ```${env:ProgramFiles(x86)} = $env:ProgramFiles```
I get 
```
flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.17.5 at C:\Android\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android
    • ANDROID_SDK_ROOT = C:\Android\sdk
    • Java binary at: C:\Program Files\Java\jre1.8.0_261\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\Rishabh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • SM J710F • 520340de46635457 • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```
Any idea how to resolve this??

**Comment by stuartmorgan** [comment]
> I have Windows 7 Professional SP 1 32 bit.

Per [the installation instructions](https://flutter.dev/docs/get-started/install/windows), only 64-bit Windows is supported.

There should probably be a very early check with a clear error message when trying to run on a 32-bit machine.

**Comment by rish-hyun** [comment]
@stuartmorgan 

> > I have Windows 7 Professional SP 1 32 bit.
> 
> Per [the installation instructions](https://flutter.dev/docs/get-started/install/windows), only 64-bit Windows is supported.
> 
> There should probably be a very early check with a clear error message when trying to run on a 32-bit machine.

Ohhh, so shall I upgrade to 64-bit or is there any some way to work around with 32-bit?? I mean, is there any other way to make it run somehow by editing scripts in sdk or something like that?

**Comment by stuartmorgan** [comment]
> I mean, is there any other way to make it run somehow by editing scripts in sdk or something like that?

See https://github.com/flutter/flutter/issues/33862 for discussion of some of the technical work you would need to do to implement 32-bit support.

**Comment by christopherfujino** [comment]
> Ohhh, so shall I upgrade to 64-bit or is there any some way to work around with 32-bit?? I mean, is there any other way to make it run somehow by editing scripts in sdk or something like that?

I think it's safe to say you need 64-bit Windows to use Flutter. Per the issue that stuartmorgan linked, getting Flutter to work on 32-bit Windows would be a non-trivial amount of work. Basically, the existing tooling has a lot of assumptions that you are on a 64-bit architecture.

**Comment by stuartmorgan** [comment]
@christopherfujino Why was this closed? We could check the architecture in the batch script.

**Comment by christopherfujino** [comment]
@stuartmorgan sorry, I hit the wrong button.
