### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lio/flutter/plugins/imagepicker/ImagePickerPlugin$LifeCycleObserver;

### ISSUE THREAD

**Issue by krupalbhardiya** [flutter/flutter#62676]
## Steps to Reproduce

In out of the box vanilla flutter project, add [image picker plugin](https://pub.dev/packages/image_picker).
    image_picker: ^0.6.7+4

**Expected results:** 
The plugin works in debug variant for picking the images from Gallery. 
But when Flutter App is signed with certificate and installed in release build variant, the App crashed on the App run from the start.

**Actual results:** 
Plugin is missing the classes as seen in the exception. Perhaps proguard is removing the classes in the release build.

<details>
  <summary>Logs</summary>

    2010-01-06 02:33:28.067 13740-13740/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.axon.siesta_ams.admin, PID: 13740
    java.lang.NoClassDefFoundError: Failed resolution of: Lio/flutter/plugins/imagepicker/ImagePickerPlugin$LifeCycleObserver;
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.e(Unknown Source:20)
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.d(Unknown Source:40)
        at h.b.d.a.b(Unknown Source:112)
        at com.axon.siesta_ams.MainActivity.onCreate(Unknown Source:3)
        at android.app.Activity.performCreate(Activity.java:7044)
        at android.app.Activity.performCreate(Activity.java:7035)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2794)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2919)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6570)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
     Caused by: java.lang.ClassNotFoundException: io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.e(Unknown Source:20) 
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.d(Unknown Source:40) 
        at h.b.d.a.b(Unknown Source:112) 
        at com.axon.siesta_ams.MainActivity.onCreate(Unknown Source:3) 
        at android.app.Activity.performCreate(Activity.java:7044) 
        at android.app.Activity.performCreate(Activity.java:7035) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2794) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2919) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6570) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857) 
     Caused by: java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver' appears in /data/app/com.axon.siesta_ams.admin-n9UfsmeevCRUBLtC7FgoSw==/base.apk)
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.e(Unknown Source:20) 
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.d(Unknown Source:40) 
        at h.b.d.a.b(Unknown Source:112) 
        at com.axon.siesta_ams.MainActivity.onCreate(Unknown Source:3) 
        at android.app.Activity.performCreate(Activity.java:7044) 
        at android.app.Activity.performCreate(Activity.java:7035) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2794) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2919) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6570) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857) 
    2010-01-06 02:33:32.097 725-1646/? E/ActivityManager: Found activity ActivityRecord{fda6c99 u0 com.axon.siesta_ams.admin/com.axon.siesta_ams.MainActivity t-1 f} in proc activity list using null instead of expected ProcessRecord{86791c2 13740:com.axon.siesta_ams.admin/u0a169}

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.17.5 at D:\flutter_sdk
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\android_sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = D:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (2 available)
    • Z50                          • Z50418LA633363 • android-arm • Android 8.1.0 (API 27)
    • Android SDK built for x86 64 • emulator-5554  • android-x64 • Android 10 (API 29) (emulator)

```
```

</details>

**Comment by darshankawar** [comment]
Hi @krupalbhardiya,
There's a similar open issue describing your case using `image_picker` plugin, [58479](https://github.com/flutter/flutter/issues/58479).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
