### ISSUE TITLE
Access Forbidden when flutter dashboard tries to update issues

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#62698]
Flutter application is failing to add comments to issues. This may be because the application needs write access to issues:

```
GitHub Error: Access Forbidden
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:403:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      GitHub.requestJson (package:github/src/common/github.dart:268:28)
#3      GitHub.postJSON (package:github/src/common/github.dart:194:7)
#4      IssuesService.createComment (package:github/src/common/issues_service.dart:246:19)
#5      GithubWebhook._applyFrameworkRepoLabels (package:cocoon_service/src/request_handlers/github_webhook.dart:328:35)
<asynchronous suspension>
#6      GithubWebhook._checkForLabelsAndTests (package:cocoon_service/src/request_handlers/github_webhook.dart:232:17)
<asynchronous suspension>
#7      GithubWebhook._handlePullRequest (package:cocoon_service/src/request_handlers/github_webhook.dart:129:15)
<asynchronous suspension>
#8      GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:73:17)
<asynchronous suspension>
#9      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _runZoned (dart:async/zone.dart:1619:10)
#13     runZoned (dart:async/zone.dart:1539:10)
#14     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#15     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:127:23)
#16     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#17     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#18     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#19     _rootRun (dart:async/zone.dart:1184:13)
#20     _CustomZone.run (dart:async/zone.dart:1077:19)
#21     _runZoned (dart:async/zone.dart:1619:10)
#22     runZonedGuarded (dart:async/zone.dart:1608:12)
#23     runZoned (dart:async/zone.dart:1536:12)
#24     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#25     fork (package:gcloud/service_scope.dart:104:30)
#26     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#27     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#28     _rootRunUnary (dart:async/zone.dart:1192:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#34     _StreamController._add (dart:async/stream_controller.dart:655:7)
#35     _StreamController.add (dart:async/stream_controller.dart:597:5)
#36     _HttpServer._handleRequest (dart:_http/http_impl.dart:2837:19)
#37     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2596:19)
#38     _rootRunUnary (dart:async/zone.dart:1192:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#44     _StreamController._add (dart:async/stream_controller.dart:655:7)
#45     _StreamController.add (dart:async/stream_controller.dart:597:5)
#46     _HttpParser._headersEnd (dart:_http/http_parser.dart:413:17)
#47     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#48     _HttpParser._parse (dart:_http/http_parser.dart:328:7)
#49     _HttpParser._onData (dart:_http/http_parser.dart:850:5)
#50     _rootRunUnary (dart:async/zone.dart:1192:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#56     _StreamController._add (dart:async/stream_controller.dart:655:7)
#57     _StreamController.add (dart:async/stream_controller.dart:597:5)
#58     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#59     _rootRunUnary (dart:async/zone.dart:1196:13)
#60     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#64     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#65     _StreamController._add (dart:async/stream_controller.dart:655:7)
#66     _StreamController.add (dart:async/stream_controller.dart:597:5)
#67     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#68     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#69     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#71     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by godofredoc** [comment]
\cc @kf6gpe

**Comment by godofredoc** [comment]
The flutter dashboard app was updated with write access to "Issues 
Issues and related comments, assignees, labels, and milestones.". We'll monitor and close if the issue is solved.
