### ISSUE TITLE
Podspec dependency with http source ends up in missing framework

### ISSUE THREAD

**Issue by fotiDim** [flutter/flutter#62719]
## Steps to Reproduce
I have a Flutter plugin project and I want to add a podspec dependency. Adding a podspec dependency that has an http source (instead of git) ends up in missing framework. The podspec [here](https://github.com/CocoaPods/Specs/blob/master/Specs/8/a/d/SpotifyRemoteSDK/1.0.1/SpotifyRemoteSDK.podspec.json) has:
```
"source": {
    "http": "https://github.com/spotify/ios-sdk/archive/v1.0.0.zip",
    "flatten": true
  },
```
which essentially downloads the specified .framework as a zip file and then unzips it before including it into the project.
I opened my Flutter project's .podspec file and added `s.dependency 'SpotifyRemoteSDK', '~> 1.0.1'`. After running pod install or `flutter clean && flutter run` I should be able to go in my `MYPROJECTPlugin.m` file and do `#import <SpotifyiOS/SpotifyiOS.h>`. However this ends up in:

```
.../ios/Classes/MYPROJECTPlugin.m:4:9: fatal error:
    'SpotifyiOS/SpotifyiOS.h' file not found
    #import <SpotifyiOS/SpotifyiOS.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    ld: framework not found MYPROJECT
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```

This is not a CocoaPods bug. I cross tested with another project that has a standard podfile by using a local .podspec as the parent podspec for the Spotify podspec and it worked as expected. I believe it is something related with the podfile script that Flutter generates.

**Expected results:** 
Compilation should work when importing the 3rd party framework.

**Actual results:** 
Compilation failed with framework import error.

<details>
  <summary>Logs</summary>

```
flutter run --verbose -> too long to paste. Hitting the GitHub comment limit!
```

```
flutter analyze
Analyzing ios...                                                        
No issues found! (ran in 2.1s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.0-7.2.pre at /Users/fotidim/Dev/flutter
    • Framework revision a2bde82fbd (2 weeks ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fotidim/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/fotidim/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/fotidim/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) • 828E538D-C799-4392-9F15-ACC699FDE90E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)                    • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                               •
      web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
I also see missing framework error

```
Analyzing dependencies
Downloading dependencies
Installing Flutter (1.0.0)
Installing SpotifyRemoteSDK (1.0.1)
Installing hello (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 3 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```

### Xcode
```
Ld /Users/taha/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Runner normal x86_64 (in target 'Runner' from project 'Runner')
    cd /Users/taha/AndroidStudioProjects/hello/example/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios13.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk -L/Users/taha/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator -L/Users/taha/AndroidStudioProjects/hello/example/ios/Flutter -F/Users/taha/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator -F/Users/taha/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/hello -F/Users/taha/AndroidStudioProjects/hello/example/ios/Pods/../Flutter -F/Users/taha/AndroidStudioProjects/hello/example/ios/Pods/SpotifyRemoteSDK -F/Users/taha/AndroidStudioProjects/hello/example/ios/Flutter -filelist /Users/taha/AndroidStudioProjects/hello/example/build/ios/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/taha/AndroidStudioProjects/hello/example/build/ios/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/taha/AndroidStudioProjects/hello/example/build/ios/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner.swiftmodule -framework Flutter -framework Foundation -framework SpotifyiOS -framework UIKit -framework hello -framework Flutter -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/taha/AndroidStudioProjects/hello/example/build/ios/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app-Simulated.xcent -framework Pods_Runner -Xlinker -dependency_info -Xlinker /Users/taha/AndroidStudioProjects/hello/example/build/ios/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat -o /Users/taha/AndroidStudioProjects/hello/example/build/ios/Debug-iphonesimulator/Runner.app/Runner

ld: framework not found hello
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`flutter run -v`
```
[ +131 ms] executing: [/Users/taha/Code/flutter_beta/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e606910f28be51c8151f6169072afe3b3a8b3c5e
[        ] executing: [/Users/taha/Code/flutter_beta/] git tag --contains HEAD
[ +337 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.0-7.3.pre
[  +10 ms] executing: [/Users/taha/Code/flutter_beta/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/taha/Code/flutter_beta/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [/Users/taha/Code/flutter_beta/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +7 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.6
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19G73
[  +36 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +18 ms] executing: /Users/taha/Code/sdk/platform-tools/adb devices -l
[   +5 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +873 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.6
           Build version 11E708
[   +3 ms] executing: xcrun --find xcdevice
[  +14 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[        ] executing: xcrun xcdevice list --timeout 2
[   +6 ms] /usr/bin/xcrun simctl list --json devices
[        ] executing: /usr/bin/xcrun simctl list --json devices
[  +43 ms] List of devices attached
           32003c30dc19668f       device usb:336789504X product:m30ltedd model:SM_M305F device:m30lte
           transport_id:1
[  +82 ms] {
             "devices" : {
               "com.apple.CoreSimulator.SimRuntime.tvOS-13-4" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.watchOS-6-2" : [
                 {
                   "dataPath" :
                   "\/Users\/taha\/Library\/Developer\/CoreSimulator\/Devices\/9D907EC9-BD1A-4F76-84C0-
                   B6464DB86F57\/data",
                   "logPath" :
                   "\/Users\/taha\/Library\/Logs\/CoreSimulator\/9D907EC9-BD1A-4F76-84C0-B6464DB86F57",
                   "udid" : "9D907EC9-BD1A-4F76-84C0-B6464DB86F57",
                   "isAvailable" : true,
                   "deviceTypeIdentifier" :
                   "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm",
                   "state" : "Shutdown",
                   "name" : "Apple Watch Series 4 - 40mm"
                 },
                 {
                   "dataPath" :
                   "\/Users\/taha\/Library\/Developer\/CoreSimulator\/Devices\/8433BDFF-CFC2-4640-B586-
                   BA4472972933\/data",
                   "logPath" :
                   "\/Users\/taha\/Library\/Logs\/CoreSimulator\/8433BDFF-CFC2-4640-B586-BA4472972933",
                   "udid" : "8433BDFF-CFC2-4640-B586-BA4472972933",
                   "isAvailable" : true,
                   "deviceTypeIdentifier" :
                   "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm",
                   "state" : "Shutdown",
                   "name" : "Apple Watch Series 4 - 44mm"
                 }
               ],
               "com.apple.CoreSimulator.SimRuntime.iOS-13-6" : [
                 {
                   "dataPath" :
                   "\/Users\/taha\/Library\/Developer\/CoreSimulator\/Devices\/1EB615AF-5AB9-4AAA-A587-
                   A6642BB79484\/data",
                   "logPath" :
                   "\/Users\/taha\/Library\/Logs\/CoreSimulator\/1EB615AF-5AB9-4AAA-A587-A6642BB79484",
                   "udid" : "1EB615AF-5AB9-4AAA-A587-A6642BB79484",
                   "isAvailable" : true,
                   "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11",
                   "state" : "Booted",
                   "name" : "iPhone 11"
                 }
               ]
             }
           }
[+3189 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.2.1 (17T531)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch4,4",
                        "identifier" : "8433BDFF-CFC2-4640-B586-BA4472972933",
                        "architecture" : "i386",
                        "modelUTI" : "com.apple.watch-series4-1",
                        "modelName" : "Apple Watch Series 4 - 44mm",
                        "name" : "Apple Watch Series 4 - 44mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.2.1 (17T531)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch4,3",
                        "identifier" : "9D907EC9-BD1A-4F76-84C0-B6464DB86F57",
                        "architecture" : "i386",
                        "modelUTI" : "com.apple.watch-series4-1",
                        "modelName" : "Apple Watch Series 4 - 40mm",
                        "name" : "Apple Watch Series 4 - 40mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.6 (17G64)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,1",
                        "identifier" : "1EB615AF-5AB9-4AAA-A587-A6642BB79484",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-1",
                        "modelName" : "iPhone 11",
                        "name" : "iPhone 11"
                      }
                    ]
[   +8 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] "flutter run" took 4,304ms.
[  +21 ms] Target file "lib/main.dart" not found.
[   +3 ms] 
           #0      FlutterCommand.validateCommand
(package:flutter_tools/src/runner/flutter_command.dart:970:9)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:338:19)
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:836:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:741:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +261 ms] ensureAnalyticsSent: 258ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.20.0-7.3.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.0-7.3.pre at /Users/taha/Code/flutter_beta
    • Framework revision e606910f28 (5 days ago), 2020-07-28 16:06:37 -0700
    • Engine revision ac95267aef
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (4 available)
    • SM M305F (mobile)  • 32003c30dc19668f                     • android-arm64  • Android 10 (API 29)
    • iPhone 11 (mobile) • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      84.0.4147.105

• No issues found!
```

</details>

**Comment by jmagman** [comment]
I think they are doing something weird and explicitly adding the `SpotifyRemoteSDK ` directory to their pod's search path 
https://github.com/CocoaPods/Specs/blob/master/Specs/8/a/d/SpotifyRemoteSDK/1.0.1/SpotifyRemoteSDK.podspec.json#L30
I'm not an expert but I bet they did that because they didn't set up their vendored_framework correctly?

So you probably need the same hack the same in your podspec:
```
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64', 'FRAMEWORK_SEARCH_PATHS': '$(PODS_ROOT)/SpotifyRemoteSDK' }
```
Anyway the Flutter generated example Podfile isn't doing anything special here, it's calling:
```
pod 'MYPROJECT', :path '/path/to/your/podspec
```
and CocoaPods is responsible for hooking up all the dependencies.

Closing, Flutter doesn't hook up anything with transitive CocoaPod dependencies.

**Comment by fotiDim** [comment]
@jmagman @TahaTesser I think you were a bit too fast to dismiss this. `SpotifyRemoteSDK` does not provide official cocoapods support. This podspec I posted above is essentially a workaround. However it does work in a non Flutter project if I add as a dependency in another podspec.

Also apart from that I did my own local version of "podspec within podspec" with a vendored framework and that also didn't work under Flutter. I don't believe there is a problem with the example Spotify podscpec.

**Comment by jmagman** [comment]
> This podspec I posted above is essentially a workaround.

It needs to set up CocoaPods vendored frameworks correctly instead of hacking `FRAMEWORK_SEARCH_PATHS`.  I think you're getting luck that it's working in other places.

```
  "source_files": "SpotifyiOS.framework/**/*.h",
  "preserve_paths": "SpotifyiOS.framework",
  "header_dir": "SpotifyiOS.framework/Headers",
```
That's not how to set up a CocoaPods downloaded vendored framework.  

Flutter itself works as a downloaded vendored framework:

```ruby
Pod::Spec.new do |s|
  s.name                    = 'Flutter'
  s.version                 = '1.20.0'
  s.summary                 = 'Flutter Engine Framework'
  s.description             = <<-DESC
Flutter is Google’s UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.
This pod vends the iOS release mode Flutter engine framework. It is compatible with application frameworks created with this version of the engine and tools.
                            DESC
  s.homepage                = 'https://flutter.dev/'
  s.license                 = { :type => 'BSD', :text => <<-LICENSE
...
LICENSE
  }
  s.author                  = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
  s.source                  = { :http => 'https://storage.googleapis.com/flutter_infra/flutter/c8e3b9485386425213e2973126d6f57e7ed83c54/ios-release/artifacts.zip' }
  s.documentation_url       = 'https://flutter.dev/docs'
  s.ios.deployment_target   = '8.0'
  s.ios.vendored_frameworks = 'Flutter.framework'
  s.prepare_command         = <<-CMD
unzip Flutter.framework -d Flutter.framework
                            CMD
end
```

Closing.
