### ISSUE TITLE
access forbidden in refresh_github_commits.dart

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#62711]
This is happening because the pagination helpers are not passing the authentication token:

```
GitHub Error: Access Forbidden
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:403:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:36:33)
<asynchronous suspension>
#3      GithubService.listCommits (package:cocoon_service/src/service/github_service.dart:37:54)
#4      RefreshGithubCommits.get (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:68:66)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
<asynchronous suspension>
#6      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _runZoned (dart:async/zone.dart:1619:10)
#10     runZoned (dart:async/zone.dart:1539:10)
#11     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#12     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:134:19)
<asynchronous suspension>
#13     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _runZoned (dart:async/zone.dart:1619:10)
#17     runZoned (dart:async/zone.dart:1539:10)
#18     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:133:11)
<asynchronous suspension>
#19     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:127:23)
<asynchronous suspension>
```

**Comment by godofredoc** [comment]
The following handlers are being affected:

* push-engine-build-status-to-github
* refresh-github-commits
