### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by JoanMaina** [flutter/flutter#62726]
## Command
```
flutter create .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:131:16)
#4      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:81:17)
#5      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:84:9)
#6      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:84:9)
#7      CreateCommand._injectGradleWrapper (package:flutter_tools/src/commands/create.dart:798:21)
#8      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:671:25)
<asynchronous suspension>
#9      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:435:37)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#18     FlutterProject.organizationNames (package:flutter_tools/src/project.dart)
#19     _rootRunUnary (dart:async/zone.dart:1198:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
```
```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-6.0.pre.117 at /opt/flutter
    • Framework revision 7ec2d360bc (2 days ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/jojo/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /home/joan/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Android Studio (version 4.0)
    • Android Studio at /home/joan/Downloads/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 8bd2e6585b0eda5ccdc10c1e1d35105e11f84424

**Comment by emn10** [comment]
Hello. 
Do not change the name of the directory containing the flutter folders after you have unzipped the downloaded file.

**Comment by darshankawar** [comment]
Hi @JoanMaina,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate.

**Comment by JoanMaina** [comment]
Thank you
