### ISSUE TITLE
I am having difficulty creating a flutter project

### ISSUE THREAD

**Issue by samueltechoga** [flutter/flutter#62720]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create sam

## exception

FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\BRAIMOH VICTOR\Documents\flutter\sam\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\src\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:195:18)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#5      Template.render (package:flutter_tools/src/template.dart:132:24)
#6      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:667:21)
#7      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:578:23)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:429:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.175], locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    [32m•[39m Framework revision f139b11009 (4 months ago), 2020-03-30 13:57:30 -0700
    [32m•[39m Engine revision af51afceb8
    [32m•[39m Dart version 2.7.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Android\android-sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = C:\Android\android-sdk
    [32m•[39m Java binary at: C:\Program Files\Java\jdk1.8.0_211\bin\java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.47.3)
    [32m•[39m VS Code at C:\Users\BRAIMOH VICTOR\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.13.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Infinix X605 • 0408825919000698 • android-arm64 • Android 8.1.0 (API 27)

[33m![39m Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
Hi @samueltechoga,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate.
