### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, path = 'C:\And_Studio\flutter\bin\cache\artifacts\gradle_wrapper\NOTICE' (OS Error: The process cannot access the file because it is being used by another process., errno = 32)

### ISSUE THREAD

**Issue by masterofyourmind** [flutter/flutter#62732]
## Command
```
flutter doctor --android-licenses
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot delete file, path = 'C:\And_Studio\flutter\bin\cache\artifacts\gradle_wrapper\NOTICE' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File._deleteSync (dart:io/file_impl.dart:308:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:460:47)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#5      GradleWrapper.updateInner.<anonymous closure> (package:flutter_tools/src/cache.dart:1074:70)
#6      _rootRunUnary (dart:async/zone.dart:1192:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#14     CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart)
<asynchronous suspension>
#15     CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#16     CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:630:12)
#17     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:1070:12)
#18     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.17.5 at C:\And_Studio\flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\shobh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.47.3)
    • VS Code at C:\Users\shobh\AppData\Local\Programs\Microsoft VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • ASUS X00TD • JAAAGF00M3209TA • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Hi @masterofyourmind,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
