### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = 'bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\ee76268252c22f5c11e82a7b87423ca3982e51a7\sky_engine.zip' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by zeczen** [flutter/flutter#62750]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\seyal\Documents\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\ee76268252c22f5c11e82a7b87423ca3982e51a7\sky_engine.zip' (OS Error: Access is denied.
, errno = 5)
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
#1      _rootRunUnary (dart:async/zone.dart:1192:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959],
    locale he-IL)
    • Flutter version 1.17.5 at C:\Users\seyal\Documents\flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\seyal\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\seyal\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\seyal\Documents\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Users\seyal\Documents\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (1 available)
    • Redmi 6 • 6f19d81a7d28 • android-arm • Android 9 (API 28)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8661d8aecd626f7f57ccbcb735553edc05a2e713
### Plugins
geolocator-3.0.1
google_api_availability-2.0.4
path_provider_linux-0.0.1+2
permission_handler-3.3.0
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/ee12d7c3fcc861ec74edf4101ab1b9270f2634a8
