### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = 'C:\src\flutter\bin\cache\artifacts\gradle_wrapper\gradlew.bat' (OS Error: Acceso denegado., errno = 5)

### ISSUE THREAD

**Issue by DiegoHerbas** [flutter/flutter#62760]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = 'C:\src\flutter\bin\cache\artifacts\gradle_wrapper\gradlew.bat' (OS Error: Acceso denegado.
, errno = 5)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:131:16)
#4      ErrorHandlingFile.writeAsBytesSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:106:22)
#5      ErrorHandlingFile._runSync (package:flutter_tools/src/base/error_handling_file_system.dart:163:16)
#6      ErrorHandlingFile.writeAsBytesSync (package:flutter_tools/src/base/error_handling_file_system.dart:105:5)
#7      _WindowsUtils._unpackArchive (package:flutter_tools/src/base/os.dart:375:16)
#8      _WindowsUtils.unpack (package:flutter_tools/src/base/os.dart:346:5)
#9      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:619:16)
#10     CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:638:26)
#11     CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#12     CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:630:12)
#13     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:1070:12)
#14     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
#15     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
#16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:698:27)
#17     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [VersiÃ³n 10.0.18362.719], locale es-ES)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\dherbas\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[!] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\dherbas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Redmi Note 8 Pro • h6pntkm78d6lscto • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
connectivity-0.4.9
connectivity_for_web-0.3.0
connectivity_macos-0.1.0+3
esys_flutter_share-1.0.2
flutter_plugin_android_lifecycle-1.0.8
google_maps_flutter-0.5.28+1
path_provider-1.6.9
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
share-0.6.4+2
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
url_launcher-5.4.7
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6

**Comment by darshankawar** [comment]
Hi @DiegoHerbas,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate.
