### ISSUE TITLE
Flutter has exited unexpectedly :  "Invalid argument(s): Cannot find executable for where.".

### ISSUE THREAD

**Issue by thevirtualbuddy** [flutter/flutter#62802]
## Steps to Reproduce

1. I installed the extension for Flutter on VS Code and the dart language.
2. I set my environment variable for flutter.
3. In VSCode I tried to create a new project as: flutter create newproject and I got the error as shown below:

## Logs

```
thevirtualbuddy@DESKTOP-M4CHLQS MINGW64 ~/Desktop/FlutterLearn
$ flutter create newproject

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable for where.
please let us know at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable for where.
please let us know at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:149:7)
#1      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#2      _rootRunBinary (dart:async/zone.dart:1204:38)
#3      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#7      Future._completeError (dart:async/future_impl.dart:534:5)
#8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#9      _informUserOfCrash (package:flutter_tools/runner.dart)
#10     _as
```

```
thevirtualbuddy@DESKTOP-M4CHLQS MINGW64 ~/Desktop/FlutterLearn
$ flutter doctor -v

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable for where.
please let us know at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable for where.
please let us know at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:149:7)
#1      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#2      _rootRunBinary (dart:async/zone.dart:1204:38)
#3      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#7      Future._completeError (dart:async/future_impl.dart:534:5)
#8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#9      _informUserOfCrash (package:flutter_tools/runner.dart)
#10     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#11     _rootRunBinary (dart:async/zone.dart:1204:38)
#12     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#13     _FutureListener.handleError (dart:async/future_impl.dart:155
```

**Comment by thevirtualbuddy** [comment]
The issue can be fixed by setting the environment variables correctly.
