### ISSUE TITLE
platform_channel_sample_test failing with cocoon error

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#62830]
```

------------ TASK ------------
Task(id: 6519878520012800, parentKey: flutter/flutter/master/31ee51a3021d0d92e1750e5cd036824dc07baa18, key: 6519878520012800, commitKey: flutter/flutter/master/31ee51a3021d0d92e1750e5cd036824dc07baa18, createTimestamp: 1596500881801, startTimestamp: 1596502530447, endTimestamp: 1596502550622, name: platform_channel_sample_test, attempts: 2, isFlaky: false, timeoutInMinutes: 0, reason: Task failed on agent, requiredCapabilities: [mac/android], reservedForAgentId: flutter-devicelab-mac-18, stageName: devicelab, status: Failed, buildNumber: null, buildNumberList: null, builderName: null, luciBucket: null)

------------ LOG ------------


Task failed with the following reason:
ERROR: TimeoutException after 0:20:00.000000: Future not completed
#0      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:15)
<asynchronous suspension>
#1      _rootRun (dart:async/zone.dart:1126:13)
#2      _CustomZone.run (dart:async/zone.dart:1023:19)
#3      _runZoned (dart:async/zone.dart:1518:10)
#4      runZoned (dart:async/zone.dart:1502:12)
#5      ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#6      main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)



Task failed with the following reason:
ERROR: FileSystemException: Deletion failed, path = '/Users/flutter/.cocoon/flutter' (OS Error: Directory not empty, errno = 66)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:208:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      rrm (package:cocoon_agent/src/utils.dart:148:35)
#3      getFlutter (package:cocoon_agent/src/utils.dart:502:5)
#4      getFlutterAt (package:cocoon_agent/src/utils.dart:255:9)
<asynchronous suspension>
#5      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:21)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1502:12)
#10     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#11     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

This looks like an error downloading the flutter SDK, though the first failure might be legitimate, it is difficult to tell

**Comment by godofredoc** [comment]
Closing as obsolete.
