### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by bravolover520** [flutter/flutter#62849]
## Command
```
flutter build ios --debug
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1847:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#11     _StreamController._add (dart:async/stream_controller.dart:655:7)
#12     _StreamController.add (dart:async/stream_controller.dart:597:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#14     _rootRunUnary (dart:async/zone.dart:1206:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#20     _StreamController._add (dart:async/stream_controller.dart:655:7)
#21     _StreamController.add (dart:async/stream_controller.dart:597:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
```
```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.19.0-4.1.pre at /Users/zhangtao/flutter
    • Framework revision f994b76974 (8 weeks ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zhangtao/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/zhangtao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe
### Plugins
auto_orientation-1.0.6
connectivity-0.4.8+6
connectivity_macos-0.1.0+3
device_info-0.4.2+4
flutter_forbidshot-0.0.2
flutter_local_notifications-1.4.4+1
flutter_plugin_android_lifecycle-1.0.8
flutter_tencentplayer-0.7.0
image_picker-0.6.7+3
local_auth-0.6.2+3
location-3.0.2
location_web-1.0.0
package_info-0.4.1
path_provider-1.6.10
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3
permission_handler-5.0.1
photo_manager-0.5.3+1
screen-0.0.5
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6
video_player-0.10.11+2
video_player_web-0.1.3+1
wakelock-0.1.4+1
webview_flutter-0.3.22+1

**Comment by jmagman** [comment]
@bravolover520 Could you also attach the crash log file that was output at the same time as this crash?  The stack is truncated and it doesn't have the actual format exception error.

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
