### ISSUE TITLE
ReorderableListView throws exception when there is a ListView sibling in the same Stack Widget 

### ISSUE THREAD

**Issue by edandaria** [flutter/flutter#62855]
## Steps to Reproduce

bug project updated to show problem. Zip of /lib attached.
[bug.gz](https://github.com/flutter/flutter/files/5021894/bug.gz)

**Expected results:** 
long touch "five" should result in it moving in the ReorderableListView

**Actual results:**
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 113 pos 12: '_positions.length == 1'

The fundamental is:
      child: Stack(
          children: <Widget>[
            ListView(children: <Widget>[
            ...
            ReorderableListView(
            ...
  
The ListView is not a hierachical ancestor, like in issue 45458. So this should work. And I suggest it is necessary since Stack is an essential widget.
However the problem is related to the ListView: if you change it to Column, the ReorderableListView works.

<details>
  <summary>Logs</summary>

```
[        ] An Observatory debugger and profiler on P10 HD EEA is available at: http://127.0.0.1:39037/o4nsgQf8cvY=/
[+3005 ms] D/        (19804): Gralloc Register  w:1200, h:1920, f:0x1101, usage:0xb00, ui64Stamp:1087621, sSize:9236480, line = 2106
[+216239 ms] I/flutter (19804): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[        ] I/flutter (19804): The following assertion was thrown while handling a gesture:
[        ] I/flutter (19804): ScrollController attached to multiple scroll views.
[        ] I/flutter (19804): 'package:flutter/src/widgets/scroll_controller.dart':
[        ] I/flutter (19804): Failed assertion: line 113 pos 12: '_positions.length == 1'
[        ] I/flutter (19804): 
[        ] I/flutter (19804): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (19804): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (19804): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (19804):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (19804): 
[        ] I/flutter (19804): When the exception was thrown, this was the stack:
[        ] I/flutter (19804): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:113:12)
[        ] I/flutter (19804): #3      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:120:24)
[        ] I/flutter (19804): #4      _ReorderableListContentState._scrollTo (package:flutter/src/material/reorderable_list.dart:324:51)
[        ] I/flutter (19804): #5      _ReorderableListContentState._wrap.<anonymous closure>.<anonymous closure>
(package:flutter/src/material/reorderable_list.dart:543:11)
[        ] I/flutter (19804): #6      _DragTargetState.didEnter (package:flutter/src/widgets/drag_target.dart:553:88)
[        ] I/flutter (19804): #7      _DragAvatar.updateDrag.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:694:23)
[        ] I/flutter (19804): #8      ListMixin.firstWhere (dart:collection/list.dart:142:15)
[        ] I/flutter (19804): #9      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:691:51)
[        ] I/flutter (19804): #10     new _DragAvatar (package:flutter/src/widgets/drag_target.dart:627:5)
[        ] I/flutter (19804): #11     _DraggableState._startDrag (package:flutter/src/widgets/drag_target.dart:388:35)
[        ] I/flutter (19804): #12     LongPressDraggable.createRecognizer.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:326:36)
[        ] I/flutter (19804): #13     MultiDragGestureRecognizer._startDrag.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:272:59)
[        ] I/flutter (19804): #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
[        ] I/flutter (19804): #15     MultiDragGestureRecognizer._startDrag (package:flutter/src/gestures/multidrag.dart:272:14)
[        ] I/flutter (19804): #16     MultiDragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:262:48)
[        ] I/flutter (19804): #17     _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:474:15)
[        ] I/flutter (19804): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
[        ] I/flutter (19804): 
[        ] I/flutter (19804): Handler: "onStart"
[        ] I/flutter (19804): Recognizer:
[        ] I/flutter (19804):   DelayedMultiDragGestureRecognizer#bb347
[        ] I/flutter (19804): ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +242 ms] D/        (19804): Gralloc Register  w:1128, h:1920, f:0x1101, usage:0xb00, ui64Stamp:1087623, sSize:8744960, line = 2106


```

```
Analyzing bug...                                                        

   info • The value of the field '_counter' isn't used • lib/main.dart:53:7 • unused_field

1 issue found. (ran in 6.0s)
```

```
[✓] Flutter (Channel beta, 1.20.0-7.3.pre, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.20.0-7.3.pre at /home/edward/Development/flutter
    • Framework revision e606910f28 (hace 7 días), 2020-07-28 16:06:37 -0700
    • Engine revision ac95267aef
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/edward/android-sdks
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/edward/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/edward/Development/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • P10 HD EEA (mobile) • 68849784235148 • android-arm64  • Android 9 (API 28)
    • Web Server (web)    • web-server     • web-javascript • Flutter Tools
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 84.0.4147.105

• No issues found!

The result is the same with the master channel

[✓] Flutter (Channel master, 1.21.0-6.0.pre.160, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.21.0-6.0.pre.160 at /home/edward/Development/flutter
    • Framework revision 31ee51a302 (hace 13 horas), 2020-08-03 17:27:21 -0700
    • Engine revision fa16c3d0ba
    • Dart version 2.10.0 (build 2.10.0-2.0.dev 0f0e04ec3a)


```

</details>

**Comment by darshankawar** [comment]
Hi @edandaria,
I think the issue occurs when we use `ReorderableListView` along with other scroll views (listview, singlechildscrollview) inside same parent. I see there was an old [PR](https://github.com/flutter/flutter/pull/31666) to fix this issue but was closed.

Since the error says `ScrollController attached to multiple scroll views.`, we can probably make use of `ScrollController` and pass it to ListView.builder` which fixes the issue. Please see below code snippet:

```
ListView.builder(
              controller: _controller,
              itemCount: 2,
              itemBuilder: (context, index) {
                return Text("Index : $index");
              },
            ),
```
Where `_controller` is `ScrollController` variable and instantiate it within `initState()` as:

```
@override
  void initState() {
    _controller = ScrollController();
    super.initState();
  }
```

With above change, I was able to reorder the `five` element properly without any issues.

**Comment by edandaria** [comment]
Hi
Thanks. I put the ScrollController in the ListView and it works for me both in bug and the real application! But would it be safer, and more future proof, to instantiate a second screen controller and assign it to the ReorderableListView?

**Comment by darshankawar** [comment]
@edandaria,
According to official [documentation](https://api.flutter.dev/flutter/widgets/ScrollController-class.html), `A single scroll controller can be used to control multiple scrollable widgets,`. You may try to use same controller inside `ReorderableListView` and see if it answers your question.

**Comment by edandaria** [comment]
Thanks
