### ISSUE TITLE
Error after backing out of a Gallery page

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#629]
To reproduce:
- Run the material_gallery example
- Select a page from the drawer: tap on "Chips"
- Press the Android back button (the drawer reappears)
- tap on "Sliders"

```
android: W/ActivityManager: Force removing ActivityRecord{11f25191 u0 org.domokit.sky.shell/.SkyActivity t1452}: app died, no saved state
android: W/ActivityManager: Spurious death for ProcessRecord{1b660ad7 6501:org.domokit.sky.shell/u0a88}, curProc for 6501: null
android: E/flutter : [ERROR:dart_error.cc(16)] Unhandled exception:
android: E/flutter : The null object does not have a method 'pushNamed'.
android: E/flutter : 
android: E/flutter : NoSuchMethodError: method not found: 'pushNamed'
android: E/flutter : Receiver: null
android: E/flutter : Arguments: ["/time-picker"]
android: E/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
android: E/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
android: E/flutter : #2      GalleryPage._showDrawer.<anonymous closure> (/builds/dev/flutter/examples/material_gallery/lib/gallery_page.dart:24)
android: E/flutter : #3      _RenderInkSplashes._handleTap (packages/flutter/src/material/ink_well.dart:264)
android: E/flutter : #4      TapGestureRecognizer._checkUp (packages/flutter/src/gestures/tap.dart:92)
android: E/flutter : #5      TapGestureRecognizer.acceptGesture (packages/flutter/src/gestures/tap.dart:64)
android: E/flutter : #6      GestureArena._tryToResolveArena (packages/flutter/src/gestures/arena.dart:128)
android: E/flutter : #7      GestureArena._resolve (packages/flutter/src/gestures/arena.dart:145)
android: E/flutter : #8      GestureArenaEntry.resolve (packages/flutter/src/gestures/arena.dart:41)
android: E/flutter : #9      OneSequenceGestureRecognizer.resolve (packages/flutter/src/gestures/recognizer.dart:49)
android: E/flutter : #10     _DragGestureRecognizer.didStopTrackingLastPointer (packages/flutter/src/gestures/drag.dart:97)
android: E/flutter : #11     OneSequenceGestureRecognizer.stopTrackingPointer (packages/flutter/src/gestures/recognizer.dart:71)
android: E/flutter : #12     OneSequenceGestureRecognizer.stopTrackingIfPointerNoLongerDown (packages/flutter/src/gestures/recognizer.dart:76)
android: E/flutter : #13     _DragGestureRecognizer.handleEvent (packages/flutter/src/gestures/drag.dart:80)
android: E/flutter : #14     PointerRouter.route (packages/flutter/src/gestures/pointer_router.dart:45)
android: E/flutter : #15     FlutterBinding.handleEvent (packages/flutter/src/rendering/binding.dart:272)
android: E/flutter : #16     FlutterBinding.dispatchEvent (packages/flutter/src/rendering/binding.dart:266)
android: E/flutter : #17     FlutterBinding._handlePointerInputEvent (packages/flutter/src/rendering/binding.dart:251)
android: E/flutter : #18     FlutterBinding._handlePointerPacket (packages/flutter/src/rendering/binding.dart:212)
android: E/flutter : #19     _dispatchPointerPacket (file:///usr/local/google/home/ianh/dev/engine/src/out/android_Release/gen/sky/bindings/Customhooks.dart:40)
```

**Comment by HansMuller** [comment]
This now fails a little differently:
```
android: E/flutter : [ERROR:dart_error.cc(16)] Unhandled exception:
android: E/flutter : The null object does not have a method 'openTransaction'.
android: E/flutter : 
android: E/flutter : NoSuchMethodError: method not found: 'openTransaction'
android: E/flutter : Receiver: null
android: E/flutter : Arguments: [Closure: (NavigatorTransaction) => dynamic]
android: E/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
android: E/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
android: E/flutter : #2      Navigator.openTransaction (packages/flutter/src/widgets/navigator.dart:141)
android: E/flutter : #3      Navigator.pushNamed (packages/flutter/src/widgets/navigator.dart:113)
android: E/flutter : #4      GalleryPage._showDrawer.<anonymous closure> (/builds/dev/flutter/examples/material_gallery/lib/gallery_page.dart:24)
android: E/flutter : #5      _InkResponseState._handleTap (packages/flutter/src/material/ink_well.dart:64)
```

**Comment by abarth** [comment]
Appears to be fixed after the drawer refactor.
