### ISSUE TITLE
Dart analyzer could not be started in VS Code

### ISSUE THREAD

**Issue by s40723110** [flutter/flutter#62977]
Since I updated the version of DART, the VScode system kept popping up "The Dart Analyzer could not be started."
I have tried to clear the cache in  flutter/bin , open View (on the VScode toolbar)/Command Palette... and type "flutter doctor", but it has no effect. 😓
When i click on Show log :

```
[下午8:13:39] [General] [Info]     C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
[下午8:13:39] [General] [Info]     C:\WINDOWS\system32
[下午8:13:39] [General] [Info]     C:\WINDOWS
[下午8:13:39] [General] [Info]     C:\WINDOWS\System32\Wbem
[下午8:13:39] [General] [Info]     C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[下午8:13:39] [General] [Info]     C:\WINDOWS\System32\OpenSSH\
[下午8:13:39] [General] [Info]     C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
[下午8:13:39] [General] [Info]     C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
[下午8:13:39] [General] [Info]     C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
[下午8:13:39] [General] [Info]     C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
[下午8:13:39] [General] [Info]     D:\Dart\Dart\dart-sdk\bin
[下午8:13:39] [General] [Info]     C:\Program Files\Git\cmd
[下午8:13:39] [General] [Info]     C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin
[下午8:13:39] [General] [Info]     D:\tools\Andriod\sdk
[下午8:13:39] [General] [Info]     Y:\miktex-portable\miktex\bin\x64\
[下午8:13:39] [General] [Info]     E:\wcm2020\data\miktex-portable\miktex\bin\x64\
[下午8:13:39] [General] [Info]     D:\flutter\flutter\bin
[下午8:13:39] [General] [Info] Searching for flutter.bat
[下午8:13:39] [General] [Info]     Looking for flutter.bat in:
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\bin
[下午8:13:39] [General] [Info]         C:\Windows\system32
[下午8:13:39] [General] [Info]         C:\Windows\system32\bin
[下午8:13:39] [General] [Info]         C:\Windows
[下午8:13:39] [General] [Info]         C:\Windows\bin
[下午8:13:39] [General] [Info]         C:\Windows\System32\Wbem
[下午8:13:39] [General] [Info]         C:\Windows\System32\Wbem\bin
[下午8:13:39] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[下午8:13:39] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\IPT\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\system32
[下午8:13:39] [General] [Info]         C:\WINDOWS\system32\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS
[下午8:13:39] [General] [Info]         C:\WINDOWS\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\Wbem
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\Wbem\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\OpenSSH\
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\OpenSSH\bin
[下午8:13:39] [General] [Info]         E:\2018fall\Git\cmd
[下午8:13:39] [General] [Info]         E:\2018fall\Git\cmd\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\WiFi\bin\
[下午8:13:39] [General] [Info]         C:\Program Files\Common Files\Intel\WirelessCommon\
[下午8:13:39] [General] [Info]         C:\Program Files\Common Files\Intel\WirelessCommon\bin
[下午8:13:39] [General] [Info]         C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
[下午8:13:39] [General] [Info]         C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\system32
[下午8:13:39] [General] [Info]         C:\WINDOWS\system32\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS
[下午8:13:39] [General] [Info]         C:\WINDOWS\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\Wbem
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\Wbem\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\OpenSSH\
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\OpenSSH\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\bin
[下午8:13:39] [General] [Info]         D:\Dart\Dart\dart-sdk\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Git\cmd
[下午8:13:39] [General] [Info]         C:\Program Files\Git\cmd\bin
[下午8:13:39] [General] [Info]         C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin
[下午8:13:39] [General] [Info]         D:\tools\Andriod\sdk
[下午8:13:39] [General] [Info]         D:\tools\Andriod\sdk\bin
[下午8:13:39] [General] [Info]         Y:\miktex-portable\miktex\bin\x64\
[下午8:13:39] [General] [Info]         Y:\miktex-portable\miktex\bin\x64\bin
[下午8:13:39] [General] [Info]         E:\wcm2020\data\miktex-portable\miktex\bin\x64\
[下午8:13:39] [General] [Info]         E:\wcm2020\data\miktex-portable\miktex\bin\x64\bin
[下午8:13:39] [General] [Info]         D:\flutter\flutter\bin
[下午8:13:39] [General] [Info]     Found at:
[下午8:13:39] [General] [Info]         D:\flutter\flutter\bin
[下午8:13:39] [General] [Info]     Candidate paths to be post-filtered:
[下午8:13:39] [General] [Info]         D:\flutter\flutter
[下午8:13:39] [General] [Info]     Found at D:\flutter\flutter
[下午8:13:39] [General] [Info]     Returning SDK path D:\flutter\flutter for flutter.bat
[下午8:13:39] [General] [Info] Searching for dart.exe
[下午8:13:39] [General] [Info]     Looking for dart.exe in:
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\bin
[下午8:13:39] [General] [Info]         C:\Windows\system32
[下午8:13:39] [General] [Info]         C:\Windows\system32\bin
[下午8:13:39] [General] [Info]         C:\Windows
[下午8:13:39] [General] [Info]         C:\Windows\bin
[下午8:13:39] [General] [Info]         C:\Windows\System32\Wbem
[下午8:13:39] [General] [Info]         C:\Windows\System32\Wbem\bin
[下午8:13:39] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[下午8:13:39] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\DAL\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\Intel(R) Management Engine Components\IPT\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\system32
[下午8:13:39] [General] [Info]         C:\WINDOWS\system32\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS
[下午8:13:39] [General] [Info]         C:\WINDOWS\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\Wbem
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\Wbem\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\OpenSSH\
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\OpenSSH\bin
[下午8:13:39] [General] [Info]         E:\2018fall\Git\cmd
[下午8:13:39] [General] [Info]         E:\2018fall\Git\cmd\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Intel\WiFi\bin\
[下午8:13:39] [General] [Info]         C:\Program Files\Common Files\Intel\WirelessCommon\
[下午8:13:39] [General] [Info]         C:\Program Files\Common Files\Intel\WirelessCommon\bin
[下午8:13:39] [General] [Info]         C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
[下午8:13:39] [General] [Info]         C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\system32
[下午8:13:39] [General] [Info]         C:\WINDOWS\system32\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS
[下午8:13:39] [General] [Info]         C:\WINDOWS\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\Wbem
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\Wbem\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\bin
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\OpenSSH\
[下午8:13:39] [General] [Info]         C:\WINDOWS\System32\OpenSSH\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\bin
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
[下午8:13:39] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
[下午8:13:39] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\bin
[下午8:13:39] [General] [Info]         D:\Dart\Dart\dart-sdk\bin
[下午8:13:39] [General] [Info]         C:\Program Files\Git\cmd
[下午8:13:39] [General] [Info]         C:\Program Files\Git\cmd\bin
[下午8:13:39] [General] [Info]         C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin
[下午8:13:39] [General] [Info]         D:\tools\Andriod\sdk
[下午8:13:39] [General] [Info]         D:\tools\Andriod\sdk\bin
[下午8:13:39] [General] [Info]         Y:\miktex-portable\miktex\bin\x64\
[下午8:13:39] [General] [Info]         Y:\miktex-portable\miktex\bin\x64\bin
[下午8:13:39] [General] [Info]         E:\wcm2020\data\miktex-portable\miktex\bin\x64\
[下午8:13:39] [General] [Info]         E:\wcm2020\data\miktex-portable\miktex\bin\x64\bin
[下午8:13:39] [General] [Info]         D:\flutter\flutter\bin
[下午8:13:39] [General] [Info]         D:\flutter\flutter\bin\cache\dart-sdk
[下午8:13:39] [General] [Info]         D:\flutter\flutter\bin\cache\dart-sdk\bin
[下午8:13:39] [General] [Info]     Found at:
[下午8:13:39] [General] [Info]         D:\Dart\Dart\dart-sdk\bin
[下午8:13:39] [General] [Info]         D:\flutter\flutter\bin\cache\dart-sdk\bin
[下午8:13:39] [General] [Info]     Candidate paths to be post-filtered:
[下午8:13:39] [General] [Info]         D:\Dart\Dart\dart-sdk
[下午8:13:39] [General] [Info]         D:\flutter\flutter\bin\cache\dart-sdk
[下午8:13:39] [General] [Info]     Found at D:\Dart\Dart\dart-sdk
[下午8:13:39] [General] [Info]     Returning SDK path D:\Dart\Dart\dart-sdk for dart.exe
[下午8:13:39] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.13.1
Flutter extension: 3.13.1 (not activated)

App: Visual Studio Code
Version: 1.47.3
Platform: win

Workspace type: Dart
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: D:\Dart\Dart\dart-sdk
    Ver: 2.8.4
Flutter SDK:
    Loc: D:\flutter\flutter
    Ver: 1.17.5

HTTP_PROXY: undefined
NO_PROXY: undefined
[下午8:13:39] [Analyzer] [Info] Spawning D:\Dart\Dart\dart-sdk\bin\dart.exe with args ["D:\\Dart\\Dart\\dart-sdk\\bin\\snapshots\\analysis_server.dart.snapshot","--client-id=VS-Code","--client-version=3.13.1"]
[下午8:13:39] [Analyzer] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[下午8:13:39] [Analyzer] [Info]     PID: 11620
[下午8:13:39] [Analyzer] [Info] ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1596629619666}
[下午8:13:39] [General] [Info] Extension:Startup timing: 50ms
[下午8:13:39] [General] [Info] Found 1 folders requiring "pub get":
    C:\Users\User\Desktop\dart-learm
[下午8:13:41] [Analyzer] [Error] Wrong f
[下午8:13:41] [Analyzer] [Error] ull snapshot version, expected '20e5c4f7dc44368ac5a17643b93665f6' found 'be7d304ff826e2dfac63538e227c3cc5'
[下午8:13:41] [Analyzer] [Info] Process terminated! 255, null
[下午8:14:01] [Analyzer] [Info] ==> {"id":"2","method":"analysis.setSubscriptions","params":{"subscriptions":{"FOLDING":["C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart"],"OCCURRENCES":["C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart"],"OUTLINE":["C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart"]}},"clientRequestTime":1596629641331}
[下午8:14:01] [Analyzer] [Info] ==> {"id":"3","method":"analysis.updateContent","params":{"files":{"C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart":{"content":"import './phone.dart';\r\n\r\n\r\nmain(List<String>args){\r\n  var ad = Phone('android');\r\n  ad.startup();\r\n\r\n  var ios = Phone('ios');\r\n  ad.startup();\r\n\r\n}\r\n","type":"add"}}},"clientRequestTime":1596629641340}
[下午8:14:01] [Analyzer] [Info] ==> {"id":"4","method":"edit.getFixes","params":{"file":"C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart","offset":0},"clientRequestTime":1596629641343}
[下午8:14:01] [Analyzer] [Info] ==> {"id":"5","method":"edit.getAssists","params":{"file":"C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart","length":0,"offset":0},"clientRequestTime":1596629641347}
[下午8:14:01] [Analyzer] [Info] ==> {"id":"6","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart","length":0,"offset":0},"clientRequestTime":1596629641349}
[下午8:14:01] [Analyzer] [Info] ==> {"id":"7","method":"analysis.setPriorityFiles","params":{"files":["C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart"]},"clientRequestTime":1596629641353}
[下午8:14:01] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.13.1\out\dist\extension.js:1:152985)
	at b.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.13.1\out\dist\extension.js:1:147394)
	at c:\Users…
[下午8:14:01] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.13.1\out\dist\extension.js:1:152985)
	at b.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.13.1\out\dist\extension.js:1:147394)
	at c:\Users…
[下午8:14:01] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.13.1\out\dist\extension.js:1:152985)
	at b.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.13.1\out\dist\extension.js:1:147394)
	at c:\Users…
[下午8:14:01] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.13.1\out\dist\extension.js:1:152985)
	at b.sendMessage (c:\Users\User\.vscode\extensions\dart-code.dart-code-3.13.1\out\dist\extension.js:1:147394)
	at c:\Users…
[下午8:17:22] [Analyzer] [Info] ==> {"id":"8","method":"edit.getFixes","params":{"file":"C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart","offset":51},"clientRequestTime":1596629842792}
[下午8:17:22] [Analyzer] [Info] ==> {"id":"9","method":"edit.getAssists","params":{"file":"C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart","length":0,"offset":51},"clientRequestTime":1596629842795}
[下午8:17:22] [Analyzer] [Info] ==> {"id":"10","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\User\\Desktop\\dart-learm\\27-lib\\3-import-file.dart","length":0,"offset":51},"clientRequestTime":1596629842797}
```

I've restarted VS Code, uninstalled and reinstalled the extensions for Flutter and Dart, but the problem persists. 😭

**Comment by TahaTesser** [comment]
Hi @s40723110 
Can you please provide your `flutter doctor -v`? Can you run the app from terminal? 
Thank you

**Comment by DanTup** [comment]
This can happen if the Dart VM and analysis server snapshot are out of sync. How did you set up the Dart SDK (at `D:\Dart\Dart\dart-sdk\`)? Could you try reinstalling/extracting it?

**Comment by s40723110** [comment]
@TahaTesser  Thank you very much for your reply 😃, because I am a newbie so I don’t know much about the system😓

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale zh-TW)
    • Flutter version 1.17.5 at D:\flutter\flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (version 4.0)
    • Android Studio at D:\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 193.6015.53
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by s40723110** [comment]
@DanTup  Thank you very much! After I put ``` .\dart-sdk``` from ```D:\Dart\Dart\dart-sdk``` to ```D:\Dart\dart-sdk``` (Put in the previous directory), there is no such problem.
May I ask why this happens? 😟🥺

**Comment by DanTup** [comment]
@s40723110 Glad it's sorted! I'm not sure what happened here, but if you've previously moved the SDK around, is it possible you got `dart.exe` and `bin/snapshots/analysis_server.dart.snapshot` out of sync?
