### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:Stderr:unzip:  cannot find or open /Users/bilal/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/bb75f611b252accdbf5e73f15e0a4cb43de5a587/darwin-x64/artifacts.zip, /Users/bilal/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/bb75f611b252accdbf5e73f15e0a4cb43de5a587/darwin-x64/artifacts.zip.zip or /Users/bilal/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/bb75f611b252accdbf5e73f15e0a4cb43de5a587/darwin-x64/artifacts.zip.ZIP. Command: unzip, OS error code: 9

### ISSUE THREAD

**Issue by bilaldrndo** [flutter/flutter#63001]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed
Stdout:

Stderr:
unzip:  cannot find or open /Users/bilal/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/bb75f611b252accdbf5e73f15e0a4cb43de5a587/darwin-x64/artifacts.zip, /Users/bilal/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/bb75f611b252accdbf5e73f15e0a4cb43de5a587/darwin-x64/artifacts.zip.zip or /Users/bilal/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/bb75f611b252accdbf5e73f15e0a4cb43de5a587/darwin-x64/artifacts.zip.ZIP.
 Command: unzip, OS error code: 9
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:459:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:226:19)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:648:16)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Net.fetchUrl (package:flutter_tools/src/base/net.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.198, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.21.0-6.0.pre.198 at /Users/bilal/development/flutter
    • Framework revision 1df1631e5f (2 hours ago), 2020-08-05 12:36:06 -0400
    • Engine revision bb75f611b2
    • Dart version 2.10.0 (build 2.10.0-3.0.dev 8cb0afa882)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/bilal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • 84A1B0E0-4358-41F2-8079-17C9229D18F7 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    ! Error: Imran’s Ipad is not connected. Xcode will continue when Imran’s Ipad is connected. (code -13)
    ! Error: Bilal Drndo is not connected. Xcode will continue when Bilal Drndo is connected. (code -13)
    ! Error: Semir’s iPhone is not connected. Xcode will continue when Semir’s iPhone is connected. (code -13)
    ! Error: Almin Iphone  is not connected. Xcode will continue when Almin Iphone  is connected. (code -13)
    ! Error: Bilal is not connected. Xcode will continue when Bilal is connected. (code -13)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
file_picker-1.12.0
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_storage-3.1.6
flutter_device_locale-0.4.0
flutter_keyboard_visibility-2.0.0
flutter_plugin_android_lifecycle-1.0.8
flutter_secure_storage-3.3.3
geolocator-5.3.2+2
google_api_availability-2.0.4
google_maps_flutter-0.5.28+1
image_picker-0.6.7+4
location-3.0.2
location_permissions-3.0.0+1
location_web-1.0.0
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4
shared_preferences-0.4.3
sqflite-1.3.1
url_launcher-5.4.11
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2
video_player-0.10.11+2
video_player_web-0.1.3+2
wakelock-0.1.4+2

**Comment by darshankawar** [comment]
Hi @bilaldrndo,
There's similar open issue describing your case, [52437](https://github.com/flutter/flutter/issues/52437).
Please follow-up there for updates.
Closing this as duplicate.
