### ISSUE TITLE
Tool should handle gradle download failures more gracefully

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#63027]
For example, from a recent Cirrus failure:

```
[module_custom_host_app_name_test] [STDOUT] Executing: .\gradlew.bat flutter:assembleDebug in C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_module_test.4018fc12\hello\.android with environment {JAVA_HOME: C:\Program Files\Java\jdk1.8.0_211}
[module_custom_host_app_name_test] [STDOUT] stdout: Downloading https://services.gradle.org/distributions/gradle-5.6.2-all.zip
[module_custom_host_app_name_test] [STDOUT] stdout: ..................................................................
[module_custom_host_app_name_test] [STDOUT] stdout: Unzipping C:\Users\ContainerAdministrator\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip to C:\Users\ContainerAdministrator\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb
[module_custom_host_app_name_test] [STDOUT] stderr: Exception in thread "main" java.util.zip.ZipException: error in opening zip file
[module_custom_host_app_name_test] [STDOUT] stderr: 	at java.util.zip.ZipFile.open(Native Method)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at org.gradle.wrapper.Install.unzip(Install.java:214)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at org.gradle.wrapper.Install.access$600(Install.java:27)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at org.gradle.wrapper.Install$1.call(Install.java:74)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at org.gradle.wrapper.Install$1.call(Install.java:48)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at org.gradle.wrapper.Install.createDist(Install.java:48)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[module_custom_host_app_name_test] [STDOUT] stderr: 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[module_custom_host_app_name_test] [STDOUT] ".\gradlew.bat" exit code: 1
```

We should instead just retry with truncated exponential backoff or some such.

**Comment by blasten** [comment]
The tool has this feature actually, but this test doesn’t use the tool. Maybe it should.

**Comment by christopherfujino** [comment]
Closing this as done, as we now have https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle_errors.dart. If there are new gradle errors it does not handle, it is pretty easy to add new regexes there.
