### ISSUE TITLE
Execution failed for task ':app:generateDebugBuildConfig'.  Can't run Flutter app on my mobile

### ISSUE THREAD

**Issue by sofiaq2201** [flutter/flutter#63114]
Hi! It's my first time using flutter. I was trying to run the tapping app(the app when u first create a flutter app) in my smartphone which already has the developer and debugging options activated, but when I use flutter run or F5 on  VSCode it gives me an error. I tried on Android Studio as well, but the same happens.

This is the output using flutter run or F5.
```
FAILURE: Build failed with an exception.
Execution failed for task ':app:generateDebugBuildConfig'.
> com/squareup/javawriter/JavaWriter
BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done 4,4s
Exception: Gradle task assembleDebug failed with exit code 1
```
This is flutter doctor -v

```
`[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [VersiÃ³n 10.0.18362.959], locale es-AR)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Sofi\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Sofi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • SM G570M • 420029219ac45493 • android-arm • Android 8.0.0 (API 26)

• No issues found!`
```

This is the flutter run verbose: [output](https://www.pastiebin.com/5f2c4c4d4a0f9)

In addition, I used flutter clean and flutter run or F5 but it happens the same, as well as using flutter create and run.
 
I don't know what else could it be.

**Comment by TahaTesser** [comment]
Hi @sofiaq2201 
Can you upgrade to latest `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persist, Can you please provide your `flutter run --verbose`
Thank you

**Comment by sofiaq2201** [comment]
Hi @TahaTesser ! I've already upgraded to the stable version but the problem persist.
flutter run --verbose
```
[ +155 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +95 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +1 ms] executing: [C:\src\flutter/] git tag --contains HEAD
[ +306 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.1
[  +12 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +110 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +67 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing: C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +53 ms] List of devices attached
           420029219ac45493       device product:on5xelteub model:SM_G570M device:on5xelte transport_id:1
[   +9 ms] C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 420029219ac45493 shell getprop
[ +138 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +235 ms] Generating
S:\Programacion\Workspace\testapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +30 ms] ro.hardware = samsungexynos7570
[  +70 ms] Starting incremental build...
[   +4 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations
[  +12 ms] complete
[   +7 ms] Launching lib\main.dart on SM G570M in debug mode...
[   +9 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Sofi\AppData\Local\Temp\flutter_tools.3cff8cdd\flutter_tool.baf6f6e0\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[  +19 ms] executing: C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 420029219ac45493 shell -x logcat
-v time -t 1
[ +144 ms] Exit code 0 from: C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 420029219ac45493 shell -x
logcat -v time -t 1
[   +2 ms] --------- beginning of system
           08-07 22:54:22.507 D/WifiService( 3055): Retrieving backup data
[   +2 ms] executing: C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 420029219ac45493 shell -x logcat
-v time -t 1
[ +127 ms] Exit code 0 from: C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 420029219ac45493 shell -x
logcat -v time -t 1
[   +2 ms] --------- beginning of main
           08-07 22:54:22.614 E/adbd    (29870): service_to_fd: shell:logcat -v time -t 1
[  +23 ms] <- compile package:testapp/main.dart
[  +20 ms] executing: C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +67 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +5 ms] executing: C:\Users\Sofi\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +71 ms] Building APK
[  +25 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from S:\Programacion\Workspace\testapp\android\gradlew.bat.
[   +2 ms] S:\Programacion\Workspace\testapp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +11 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +100 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +5 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +96 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +5 ms] executing: [S:\Programacion\Workspace\testapp\android/] S:\Programacion\Workspace\testapp\android\gradlew.bat
-Pverbose=true -Ptarget-platform=android-arm -Ptarget=S:\Programacion\Workspace\testapp\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+4626 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [ +166 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] [ +101 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [        ] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +1 ms] [        ] executing: [C:\src\flutter/] git tag --contains HEAD
[   +1 ms] [ +347 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] [        ] 1.20.1
[   +1 ms] [  +12 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +72 ms] [  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[   +1 ms] [  +58 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] [        ] https://github.com/flutter/flutter.git
[ +101 ms] [ +100 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +91 ms] [  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[  +98 ms] [  +41 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [  +19 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +54 ms] [ +103 ms] Initializing file store
[   +1 ms] [  +24 ms] Done initializing file store
[  +97 ms] [  +47 ms] Skipping target: gen_localizations
[ +701 ms] [ +737 ms] Skipping target: kernel_snapshot
[ +299 ms] [ +345 ms] Skipping target: debug_android_application
[   +2 ms] [        ] Persisting file store
[ +100 ms] [  +12 ms] Done persisting file store
[   +2 ms] [   +9 ms] build succeeded.
[   +1 ms] [  +16 ms] "flutter assemble" took 1.336ms.
[   +1 ms] [   +4 ms] ensureAnalyticsSent: 0ms
[   +1 ms] [   +1 ms] Running shutdown hooks
[   +1 ms] [        ] Shutdown hooks complete
[   +1 ms] [   +3 ms] exiting with code 0
[  +93 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +6 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig FAILED
[  +53 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:generateDebugBuildConfig'.
[   +1 ms] > com/squareup/javawriter/JavaWriter
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 6s
[   +1 ms] 4 actionable tasks: 2 executed, 2 up-to-date
[ +336 ms] Running Gradle task 'assembleDebug'... (completed in 7,1s)
[ +850 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 9.101ms.
[   +7 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[  +92 ms] ensureAnalyticsSent: 89ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +5 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by TahaTesser** [comment]
Hi @sofiaq2201 
Can you please provide your `build.gradle` and a complete reproducible minimal code sample
Thank you

**Comment by sofiaq2201** [comment]
@TahaTesser  This is the build.gradle 
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

And the code I used was the default one, the counter of taps. Here it is :) https://github.com/sofiaq2201/flutterapp

**Comment by TahaTesser** [comment]
Hi @sofiaq2201 
I cannot reproduce this issue. with your repository, this could be local gradle issue  Could you please re-download Gradle, delete Gradle cache at `%USER_HOME%\.gradle/caches/`, run `flutter create bug`, and simply attempt to run the default project after deleting cache and make sure you're on stable internet connection, this will re-download gradle? 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details> 

Thank you

**Comment by sofiaq2201** [comment]
Hello! Sorry for answering late. I downloaded Gradle which  I didn't have on my pc. After that I tried to delete .gradle/cache but it won't let me delete **all** the folders inside it.  I'm not sure if it was necessary to delete all the folder. Anyways, i tried flutter create bug but the problem persists.

**Comment by TahaTesser** [comment]
Hi @sofiaq2201 
Some process might be using it, restart your PC then as soon as it starts, you should be able to delete` caches` folder very easily in `%USER_HOME%\.gradle/caches/`  and run the app again. it will download fresh gradle (make sure you're on stable internet connection) while running app after deleting cache 

Hope this helps

**Comment by sofiaq2201** [comment]
@TahaTesser It worked finally!!! Thank you so much for helping me! Now i can finally start my journey as a mobile developer ^^

Solution:

> delete Gradle cache at %USER_HOME%\.gradle/caches/
> flutter create bug
> flutter run
