### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by oliver-gomes** [flutter/flutter#63148]
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. Flutter New Project
2. Project Name and Location
3. Error!!!

## Logs
FileSystemException: Cannot open file, OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_file_system.dart:186:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_file_system.dart:351:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_file_system.dart:185:5)
#8      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:247:30)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#10     Template.render (package:flutter_tools/src/template.dart:181:24)
#11     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:781:21)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20     Template.fromName (package:flutter_tools/src/template.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
```
```
[✓] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.20.0 at C:\flutter
    • Framework revision 840c9205b3 (2 days ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ogome\AppData\Local\Android\Sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\ogome\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\ogome\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

I tried to look up every similar issues, none of the solution worked. Flutter worked all well in my PC until I updated it

**Comment by darshankawar** [comment]
Hi @oliver-gomes,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate.
