### ISSUE TITLE
upgraded the flutter SDK to channel stable, v1.17.5. Crash,

### ISSUE THREAD

**Issue by lishuliang28** [flutter/flutter#63168]
I upgraded the flutter SDK to channel stable, v1.17.5. Crash, unable to run, previous version is good
一、error log 
java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2818)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference
        at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:699)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:290)
        at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:519)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:413)
        at com.xiaoban.mobile.v4.ui.ActivityFlutter.onCreate(ActivityFlutter.java:163)
        at android.app.Activity.performCreate(Activity.java:6858)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2710)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2818) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6393) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
2020-08-07 10:20:00.671 13989-13989/com.xiaoban.mobile I/Process: Sending signal. PID: 13989 SIG: 9
二、Version
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.959], locale zh-CN)
    • Flutter version 1.17.5 at C:\D\flutter\flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Robust\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Robust\AppData\Local\Android\Sdk
    • Java binary at: C:\D\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\D\android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.3
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5901

[!] VS Code (version 1.43.0)
    • VS Code at C:\Users\Robust\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Redmi Note 5A • 192.168.137.30:5555 • android-arm64 • Android 7.1.2 (API 25)

**Comment by lishuliang28** [comment]
In the initial session of fluttextextureview, but in the assignment of rendersurface, it uses flutersurfaceview. Why. Now, because flutersurfaceview is not assigned a value, rendersurface is null, resulting in a null pointer  

private FlutterView(
      @NonNull Context context,
      @Nullable AttributeSet attrs,
      @NonNull FlutterTextureView flutterTextureView) {
    super(context, attrs);

    this.flutterTextureView = flutterTextureView;
    this.renderSurface = flutterSurfaceView;

    init();
  }

**Comment by amanv8060** [comment]
latest stable release is 1.20 , 
Try 
`flutter channel stable`
`flutter upgrade`
`flutter doctor`


reconfirm if the issue persists  with the output of `flutter doctor`

**Comment by lishuliang28** [comment]
thank you
