### ISSUE TITLE
image_picker: ^0.6.7+4 RumTimeException of Capture Image from Camera

### ISSUE THREAD

**Issue by pacifire** [flutter/flutter#63172]
Trying to capture an Image using camera, plugin used is `image_picker: ^0.6.7+4`. But the app thows error, once we capture image from camera.

Code to capture Image from Camera:

```
if (_picker == null) _picker = ImagePicker(); //Please declare variable at class level.

    if (_compressionClass == null)
      _compressionClass = globalUtils.IMAGE_COMPRESSION();

    PickedFile capturedImage = await _picker.getImage(
        source: ImageSource.camera,
        maxWidth: _compressionClass.IMG_HEIGHT.toDouble(),
        maxHeight: _compressionClass.IMG_WIDTH.toDouble(),
        imageQuality: _compressionClass.IMG_QUALITY); //Error is coming is this line.

    //Compressing image now... Below code can be ignored. Error is coming above....
    File compressedImage =
        await _compressionClass.compressPicture(File(capturedImage.path));

    //Adding the compressed image details in the list....
    UploadMediaModel compressedImageModel = UploadMediaModel();
    compressedImageModel.isExpanded = false;
    compressedImageModel.mediaName = "${compressedImage.path}";
    compressedImageModel.mediaSize =
        filesize(compressedImage.lengthSync().toInt());
    compressedImageModel.mediaType = MEDIA_TYPE.PICTURE;
    _uploadMediaList.add(compressedImageModel);

    setState(() {});
```

IMAGE COMPRESSION CLASS:

```
class IMAGE_COMPRESSION {
  final IMG_WIDTH = 480,
      IMG_HEIGHT = 640,
      IMG_FORMAT = ".jpg",
      IMG_ROTATION = 0,
      IMG_KEEP_EXIF = false,
      IMG_QUALITY = 80;

  ///This fucntion will save the picture, automatically at the saved path.
  Future<File> compressPicture(File imageFile) async {
    String compressedImgPath =
        imageFile.absolute.path + "_compressed$IMG_FORMAT";
    // print("Image path = $compressedImgPath");
    var result = await FlutterImageCompress.compressAndGetFile(
        imageFile.absolute.path, compressedImgPath,
        minWidth: IMG_WIDTH, minHeight: IMG_HEIGHT, quality: IMG_QUALITY);

    // print("Image Original size = ${imageFile.lengthSync()}");
    // print("Image New size = ${result.lengthSync()}");

    return result;
  } //compressPicture closes here.....

} //IMAGE_COMPRESSION closes here....
```

```
E/AndroidRuntime( 2497): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity {com.goilil.gulfcare/com.example.gulf_oil_ticketing_system.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
E/AndroidRuntime( 2497): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2497): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime( 2497): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2497): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime( 2497): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
E/AndroidRuntime( 2497): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime( 2497): 	at com.example.gulf_oil_ticketing_system.MainActivity.onActivityResult(MainActivity.kt)
E/AndroidRuntime( 2497): 	at android.app.Activity.dispatchActivityResult(Activity.java:7256)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
E/AndroidRuntime( 2497): 	... 9 more
```

**Comment by darshankawar** [comment]
Hi @pacifire,
In your code snippet, you are assigning `IMG_HEIGHT` to `maxWidth` and `IMG_WIDTH` to `maxHeight`.

```
maxWidth: _compressionClass.IMG_HEIGHT.toDouble(),
maxHeight: _compressionClass.IMG_WIDTH.toDouble(),
```

**Comment by pacifire** [comment]
@darshankawar : It is giving new error now:  Haven't searched the web yet for this:
This comes on 1st click itself, no other resource is using the image_picker classes/library.

```
2020-08-07 18:15:37.211 2307-4877/com.goilil.gulfcare E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
    #3      MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
    #4      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
    #5      ImagePicker.getImage (package:image_picker/image_picker.dart:101:21)
    #6      _RaiseTicketStep5State._addImageFromCamera (package:gulf_oil_ticketing_system/RaiseTicket/RaiseTicketStep5.dart:448:46)
    #7      _RaiseTicketStep5State._getCameraView.<anonymous closure> (package:gulf_oil_ticketing_system/RaiseTicket/RaiseTicketStep5.dart:314:13)
    #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:931:19)
    #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1018:38)
    #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
    #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
    #13     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
    #14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #20     _rootRunUnary (dart:async/zone.dart:1206:13)
    #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #23     _invoke1 (dart:ui/hooks.dart:281:10)
    #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:190:5)
```

**Comment by pacifire** [comment]
The issue was:

01. Add Permission in Manifest : `<uses-permission android:name="android.permission.CAMERA"/>`

02. Change `onActivityResult(requestCode: Int, resultCode: Int, data: Intent)` to 
`override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)`
