### ISSUE TITLE
CupertinoDatePicker in CupertinoDatePickerMode.date mode respects time while compare initialDateTime and minimumDate in assert

### ISSUE THREAD

**Issue by sanekyy** [flutter/flutter#63196]
CupertinoDatePicker in CupertinoDatePickerMode.date mode respects time while compare initialDateTime and minimumDate in assert.

I think that in this mode assert should compare just dates without time.

I ready to create PR with fix.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `main.dart` as follows:

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CupertinoDatePicker(
          initialDateTime: DateTime(2020, 8, 8),
          minimumDate: DateTime(2020, 8, 8, 8),
          mode: CupertinoDatePickerMode.date,
          onDateTimeChanged: (_) {},
        ),
      ),
    );
  }
}
```

3. Run

**Expected results:**  working app

**Actual results:**  exception in assert of CupertinoDatePicker

```
The following assertion was thrown building MyApp(dirty):
initial date 2020-08-08 00:00:00.000 is not greater than or equal to minimumDate 2020-08-08
08:00:00.000
'package:flutter/src/cupertino/date_picker.dart':
Failed assertion: line 277 pos 7: 'mode != CupertinoDatePickerMode.date || minimumDate == null ||
!minimumDate.isAfter(this.initialDateTime)'

The relevant error-causing widget was:
  MyApp file:///Users/sanekyy/Projects/flutter/cupertino_date_picker_assert_bug/lib/main.dart:5:10
```

<details>
  <summary>Logs</summary>

```
Performing hot reload...
Syncing files to device Pixel 4 XL...

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty):
initial date 2020-08-08 00:00:00.000 is not greater than or equal to minimumDate 2020-08-08
08:00:00.000
'package:flutter/src/cupertino/date_picker.dart':
Failed assertion: line 277 pos 7: 'mode != CupertinoDatePickerMode.date || minimumDate == null ||
!minimumDate.isAfter(this.initialDateTime)'

The relevant error-causing widget was:
  MyApp file:///Users/sanekyy/Projects/flutter/cupertino_date_picker_assert_bug/lib/main.dart:5:10

When the exception was thrown, this was the stack:
#2      new CupertinoDatePicker (package:flutter/src/cupertino/date_picker.dart:277:7)
#3      MyApp.build (package:cupertino_date_picker_assert_bug/main.dart:13:15)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4631:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4557:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:880:20)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#12     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 0 of 521 libraries in 81ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty):
initial date 2020-08-08 00:00:00.000 is not greater than or equal to minimumDate 2020-08-08 08:00:00.000
'package:flutter/src/cupertino/date_picker.dart':
Failed assertion: line 277 pos 7: 'mode != CupertinoDatePickerMode.date || minimumDate == null || !minimumDate.isAfter(this.initialDateTime)'

The relevant error-causing widget was: 
  MyApp file:///Users/sanekyy/Projects/flutter/cupertino_date_picker_assert_bug/lib/main.dart:5:10
When the exception was thrown, this was the stack: 
#2      new CupertinoDatePicker (package:flutter/src/cupertino/date_picker.dart:277:7)
#3      MyApp.build (package:cupertino_date_picker_assert_bug/main.dart:13:15)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4631:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4557:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4273:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
flutter analyze
Analyzing cupertino_date_picker_assert_bug...                           
No issues found! (ran in 2.2s)

```

```
flutter doctor -v
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-RU)
    • Flutter version 1.21.0-1.0.pre at /Users/sanekyy/Programs/flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sanekyy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/sanekyy/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/sanekyy/Library/Android/sdk
    • Java binary at: /Users/sanekyy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/sanekyy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /Users/sanekyy/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 47.1.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

 
[✓] Connected device (4 available)            
    • Pixel 4 XL (mobile) • 9C161FFBA001E2 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)     • macos          • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)    • web-server     • web-javascript • Flutter Tools
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 84.0.4147.105

! Doctor found issues in 1 category.
```

</details>

**Comment by markusaksli-nc** [comment]
Confirming as reproducible on latest dev `1.21.0-7.0.pre` and latest master `1.21.0-8.0.pre.122`.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-8.0.pre.122, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-8.0.pre.122 at /Users/markus/development/flutter_master
    • Framework revision 7c6f9dd239 (19 hours ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (5 available)            
    • sdk gphone x86 arm (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

**Comment by ewolis** [comment]
I got the same error.

For resolve this, I just do it :
`firstDate: DateTime.now().subtract(Duration(hours: 1)),`

**Comment by maheshmnj** [comment]
I can still reproduce the issue on stable 3.3  and master 3.6.

<details>
<summary>logs</summary>

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty):
initial date 2020-08-08 00:00:00.000 is not greater than or equal to minimumDate 2020-08-08
08:00:00.000
'package:flutter/src/cupertino/date_picker.dart':
Failed assertion: line 305 pos 7: 'mode != CupertinoDatePickerMode.date || minimumDate == null ||
!minimumDate!.isAfter(this.initialDateTime)'

The relevant error-causing widget was:
  MyApp MyApp:file:///Users/mahesh/Desktop/flutter_issue/lib/main.dart:5:10

When the exception was thrown, this was the stack:
#2      new CupertinoDatePicker (package:flutter/src/cupertino/date_picker.dart:305:7)
#3      MyApp.build (package:flutter_issue/main.dart:13:15)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1180:16)
#12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1149:5)
#13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1096:18)
#14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1095:13)
#16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:930:7)
#17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:910:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
````
</details> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by AfaqAnwar** [comment]
> I got the same error.
> 
> For resolve this, I just do it : `firstDate: DateTime.now().subtract(Duration(hours: 1)),`

Still an issue as of 2023, thanks for the quick fix!
