### ISSUE TITLE
Windows: Unable to paste in a focused TextField.

### ISSUE THREAD

**Issue by TheCGDF** [flutter/flutter#63226]
## Steps to Reproduce
Code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'test',
      theme: ThemeData.dark(),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final focusNode = FocusNode();
  final txtController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          focusNode: focusNode,
          autofocus: true,
          controller: txtController,
          onSubmitted: (token) => setState(() {
            txtController.clear();
            focusNode.requestFocus();
          }),
        ),
      ),
    );
  }
}

```
1. copy some text such as "aaa".
2. run this code
3. type some text into the textfield.
4. press Enter and ctrl+v

**Expected results:** 

the copied text should be pasted into the textfield.

if you click the textfield and then ctrl+v, it will be successfull.

**Actual results:** 
paste failed with error in console:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:393:7)
#1      TextRange.textBefore (dart:ui/text.dart:1533:17)
#2      RenderEditable._handleShortcuts (package:flutter/src/rendering/editable.dart:782:33)
<asynchronous suspension>
#3      RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:545:7)
#4      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:587:17)
#5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:75:49)
#6      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
#7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _invoke3 (dart:ui/hooks.dart:279:10)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
```
<details>
  <summary>Logs</summary>

`flutter doctor -v`

```
[√] Flutter (Channel master, 1.21.0-8.0.pre.98, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.21.0-8.0.pre.98 at D:\Software\flutter
    • Framework revision 77b4505c80 (19 hours ago), 2020-08-06 18:51:02 -0700
    • Engine revision cd3ea1e839
    • Dart version 2.10.0 (build 2.10.0-3.0.dev fcafd43f2c)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Software\AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Software\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.6.5)
    • Visual Studio at D:\Software\VS2019
    • Visual Studio Enterprise 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.0)
    • Android Studio at D:\Software\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.17763.1039]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
```

</details>

**Comment by stuartmorgan** [comment]
This sounds like it's related to the initial selection being invalid instead of empty.

**Comment by rydmike** [comment]
@stuartmorgan & @darshankawar 

## CTRL-V Paste issue on Desktop [Windows] + suspect [Linux] [macOS]

I just run into this issue as well. It might actually be reproducible on Mac and Linux as well, I recommend testing it on those platforms as well. I have not tried that, but see further below for why the issue **might** exist on them as well.

I just re-tested on **Windows** with:
* Channel dev, 1.27.0-8.0.pre,
* Channel master, 1.27.0-9.0.pre.126
* With both null-safe and non null safe version of SDK
**The issue is present on all combinations.**

I also tested on Web, the issue is *not* present on Web.

Here is another demo sample to show the issue and the odd behavior:

```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Text Edit',
      home: _TextFieldExample(),
    );
  }
}
class _TextFieldExample extends StatefulWidget {
  @override
  _TextFieldExampleState createState() => _TextFieldExampleState();
}
class _TextFieldExampleState extends State<_TextFieldExample> {
  final FocusNode _focusNode = FocusNode();
  final TextEditingController _textController = TextEditingController();
  @override
  void initState() {
    _textController.text = 'Some text';
    super.initState();
  }
  @override
  void dispose() {
    _focusNode.dispose();
    _textController.dispose();
    super.dispose();
  }
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Paste error demo'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () {
                _textController.text = 'Set by button';
                _focusNode.requestFocus();
              },
              child: Text('Set focus and value'),
            ),
            SizedBox(height: 8),
            SizedBox(
              width: 400,
              child: TextField(
                controller: _textController,
                focusNode: _focusNode,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

Build the app for Windows Desktop:
![image](https://user-images.githubusercontent.com/39990307/109435555-ab38c300-7a23-11eb-84f6-49bec6ddabb7.png)

Push the "**Set focus and value**" button once.
The value is set and the cursor shows up at end of text value is set.

![image](https://user-images.githubusercontent.com/39990307/109435582-cb688200-7a23-11eb-9d62-949b7004e08b.png)

Now copy eg this text: PASTEME

Just activate the Windows app again and press CTRL-V to paste it in:

The pasted string shows up after the text **as expected**.
![image](https://user-images.githubusercontent.com/39990307/109435662-226e5700-7a24-11eb-9ea2-33fe144ff940.png)

Now push the button again, the cursor now shows up at start of the field.
![image](https://user-images.githubusercontent.com/39990307/109435685-416ce900-7a24-11eb-832f-71b62f77af92.png)

Now go CTRL-V again to paste the "PASTEME" text again:

The result: **No text shows up and we get this error:**

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:399:7)
#1      TextRange.textBefore (dart:ui/text.dart:2666:17)
#2      RenderEditable._handleShortcuts (package:flutter/src/rendering/editable.dart:948:27)
<asynchronous suspension>
```

---

## CTRL-V Paste OK on Web

If we try the same sample app in a Flutter Web build, the cursor behavior is the same, but the 2nd paste operations succeeds and inserts the pasted text value before the current text, as one would expect based on where the cursor is.
You can try the Web OK variant in DartPad here: https://dartpad.dev/4a24276592bf0bf0657b2de5b49e7c0d

## Reason to Suspect Issue Applies to all Desktop Platforms

Since the Desktop and Web build have different event handlers for the shortcut keys, it certainly explains the difference in the outcome. Web just skips handling it here, as "done already". However, because major part of the keyboard shortcut handler logic `_handleKeyEvent` is shared on Windows/Mac/Linux platforms the issue might exist on all 3 platforms on just windows

**editable.dart**

```dart
639  void _handleKeyEvent(RawKeyEvent keyEvent) {
640    if (kIsWeb) {
641      // On web platform, we should ignore the key because it's processed already.
642      return;
643    }
```
There is the difference in generalizing the modifier difference on Mac vs Win/Linux, bit other than that it is the same and results in a call to

```dart
921  Future<void> _handleShortcuts(LogicalKeyboardKey key) async {
```` 

That contains the if case where the above error occurs:

```dart
946      if (data != null) {
947        value = TextEditingValue(
948          text: selection.textBefore(text) + data.text! + selection.textAfter(text),
949          selection: TextSelection.collapsed(
950            offset: math.min(selection.start, selection.end) + data.text!.length,
951          ),
952        );
953      }
```

**Comment by rydmike** [comment]
@stuartmorgan @goderbauer @darshankawar  just as info and update, I just retested this with latest **Channel stable, 2.0.1**, this paste issue from aug 7 2020 is still there, but now in stable channel.
