### ISSUE TITLE
Unable to add exiting android .aar module to a fresh flutter plugin: "error: cannot access [/imported class/], class file not found" but no issues from gradle

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#63234]
I am trying to add an existing module (.aar file) to a fresh Flutter plugin. The plugin compiles and runs when I do not make my class implement the imported aar file. As soon as I do that, the app no longer builds, giving an error that it cannot find the imported class, even though gradle reports no issues with it.

I added the module to build.gradle like this:
```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

// ...

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.aar'])
}
```

I'm able to import and use the module without any linting errors. The errors happen as soon as I try to compile the example app. Based on the error it seems like a problem in flutter given gradle / android studio are happy with it otherwise.

Please see the example here to reproduce it:
https://github.com/acoutts/flutter-aar-issue

## Steps to Reproduce

1. clone the source project here: https://github.com/acoutts/flutter-aar-issue
2. `cd example`
3. `flutter run -d android`

**Expected results:** 
The app should compile and run.

**Actual results:** 
```
[   +1 ms] /Users/andrewcoutts/Projects/flutter_trunarrative/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:16: error: cannot access VDDocumentCapture$IVDDocumentCapture
[   +2 ms]     flutterEngine.getPlugins().add(new com.bottlepay.flutter_trunarrative.FlutterTruNarrativePlugin());
[        ]                               ^
[        ]   class file for com.dasnano.vddocumentcapture.VDDocumentCapture$IVDDocumentCapture not found
[        ] 1 error
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDebugJavaWithJavac'.
```
<details>
  <summary>Logs</summary>

```
[ +119 ms] executing: [/Users/andrewcoutts/Projects/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +52 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f25bd9c55c48c139524139b477d04b13e9f36b2c
[        ] executing: [/Users/andrewcoutts/Projects/flutter/] git tag --contains HEAD
[ +334 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.21.0-1.0.pre
           1.21.0-5.0.pre
           1.21.0-7.0.pre
[   +9 ms] executing: [/Users/andrewcoutts/Projects/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/andrewcoutts/Projects/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +68 ms] executing: [/Users/andrewcoutts/Projects/flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +8 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.5
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19F101
[  +53 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] executing: /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +953 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.6
           Build version 11E708
[   +2 ms] executing: xcrun --find xcdevice
[  +10 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[        ] executing: xcrun xcdevice list --timeout 2
[   +7 ms] /usr/bin/xcrun simctl list --json devices
[        ] executing: /usr/bin/xcrun simctl list --json devices
[  +74 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:1
[ +159 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.tvOS-13-4" : [

                        ],
                        "com.apple.CoreSimulator.SimRuntime.watchOS-6-2" : [

                        ],
                        "com.apple.CoreSimulator.SimRuntime.iOS-13-6" : [
                          {
                            "dataPath" : "\/Users\/andrewcoutts\/Library\/Developer\/CoreSimulator\/Devices\/DE1664CC-B435-4E52-A84A-3CFF49A91EB9\/data",
                            "logPath" : "\/Users\/andrewcoutts\/Library\/Logs\/CoreSimulator\/DE1664CC-B435-4E52-A84A-3CFF49A91EB9",
                            "udid" : "DE1664CC-B435-4E52-A84A-3CFF49A91EB9",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11-Pro-Max",
                            "state" : "Shutdown",
                            "name" : "iPhone 11 Pro Max"
                          },
                          {
                            "dataPath" : "\/Users\/andrewcoutts\/Library\/Developer\/CoreSimulator\/Devices\/7FBE1B53-D5F8-46CC-8E56-1F920C9BC6DD\/data",
                            "logPath" : "\/Users\/andrewcoutts\/Library\/Logs\/CoreSimulator\/7FBE1B53-D5F8-46CC-8E56-1F920C9BC6DD",
                            "udid" : "7FBE1B53-D5F8-46CC-8E56-1F920C9BC6DD",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-SE--2nd-generation-",
                            "state" : "Shutdown",
                            "name" : "iPhone SE (2nd generation)"
                          }
                        ]
                      }
                    }
[+3580 ms] [
                      {
                        "modelCode" : "iPhone10,4",
                        "simulator" : false,
                        "modelName" : "iPhone 8 (Model A1863, A1905, A1906, A1907)",
                        "error" : {
                          "code" : -13,
                          "failureReason" : "",
                          "underlyingErrors" : [
                            {
                              "code" : 5,
                              "failureReason" : "allowsSecureServices: 1. isConnected: 0. Platform:
                              <DVTPlatform:0x7fb9edc172d0:'com.apple.platform.iphoneos':<DVTFilePath:0x7fb9edc17250:'\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform'>>.
                              DTDKDeviceIdentifierIsIDID: 0",
                              "description" : "Failed _shouldMakeReadyForDevelopment check even though device is not locked by passcode.",
                              "recoverySuggestion" : "",
                              "domain" : "com.apple.platform.iphoneos"
                            }
                          ],
                          "description" : "xFF0C 8 is not connected",
                          "recoverySuggestion" : "Xcode will continue when xFF0C 8 is connected.",
                          "domain" : "com.apple.platform.iphoneos"
                        },
                        "operatingSystemVersion" : "13.5.1 (17F80)",
                        "identifier" : "d7cab5675167dcdab847995b631648e5c309e1d3",
                        "platform" : "com.apple.platform.iphoneos",
                        "architecture" : "arm64",
                        "interface" : "usb",
                        "available" : false,
                        "name" : "xFF0C 8",
                        "modelUTI" : "com.apple.iphone-8-2"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.6 (17G64)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,8",
                        "identifier" : "7FBE1B53-D5F8-46CC-8E56-1F920C9BC6DD",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-se-1",
                        "modelName" : "iPhone SE (2nd generation)",
                        "name" : "iPhone SE (2nd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.6 (17G64)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,5",
                        "identifier" : "DE1664CC-B435-4E52-A84A-3CFF49A91EB9",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-pro-max-1",
                        "modelName" : "iPhone 11 Pro Max",
                        "name" : "iPhone 11 Pro Max"
                      }
                    ]
[   +8 ms] Error: xFF0C 8 is not connected. Xcode will continue when xFF0C 8 is connected. (code -13)
[   +5 ms] /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +39 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +11 ms] Changing current working directory to: /Users/andrewcoutts/Projects/flutter_trunarrative/example
[ +160 ms] Found plugin flutter_trunarrative at /Users/andrewcoutts/Projects/flutter_trunarrative/
[  +70 ms] Found plugin flutter_trunarrative at /Users/andrewcoutts/Projects/flutter_trunarrative/
[  +72 ms] Generating /Users/andrewcoutts/Projects/flutter_trunarrative/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +31 ms] ro.hardware = ranchu
[  +46 ms] Using hardware rendering with device Android SDK built for x86 64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +47 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +6 ms] Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
[   +8 ms] /Users/andrewcoutts/Projects/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/andrewcoutts/Projects/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/andrewcoutts/Projects/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill /var/folders/dv/xkfz56ls6fldcm8nc612gxg80000gn/T/flutter_tools.HpDMyf/flutter_tool.9CAlqn/app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +21 ms] executing: /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +47 ms] Exit code 0 from: /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           08-07 17:31:00.008 D/KeyguardClockSwitch( 2321): Updating clock: 531
[   +5 ms] executing: /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +53 ms] Exit code 0 from: /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           08-07 17:31:00.008 D/KeyguardClockSwitch( 2321): Updating clock: 531
[  +19 ms] <- compile package:flutter_trunarrative_example/main.dart
[  +14 ms] executing: /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb version
[  +22 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb
[   +2 ms] executing: /Users/andrewcoutts/Library/Android/sdk/platform-tools/adb start-server
[   +8 ms] Building APK
[  +20 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Users/andrewcoutts/Projects/flutter_trunarrative/example/android/gradlew.
[   +1 ms] /Users/andrewcoutts/Projects/flutter_trunarrative/example/android/gradlew mode: 33261 rwxr-xr-x.
[ +303 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +16 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/
lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","WorkingDirectory":"$APP_PACKAGE\/Contents\/bin","MainClass":"com.intellij.idea.Main","Properties":{"id
ea.paths.selector":"AndroidStudio4.0","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio
requests access to the user's Desktop folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-193.6911.18.40.6514223","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in Android
Studio requests access to the device's camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"st
udio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"4.0","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicatio
nCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android Studio requests access to the user's Documents
folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files
on a network volume.","CFBundleGetInfoString":"Android Studio 4.0, build AI-193.6911.18.40.6514223. Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An application in Android Studio requests
access to files on a removable volume."}
[  +13 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +129 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +3 ms] executing: [/Users/andrewcoutts/Projects/flutter_trunarrative/example/android/] /Users/andrewcoutts/Projects/flutter_trunarrative/example/android/gradlew -Pverbose=true -Ptarget-platform=android-x64
-Ptarget=/Users/andrewcoutts/Projects/flutter_trunarrative/example/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1632 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :flutter_trunarrative:preBuild UP-TO-DATE
[        ] > Task :flutter_trunarrative:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_trunarrative:checkDebugManifest UP-TO-DATE
[        ] > Task :flutter_trunarrative:processDebugManifest UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :flutter_trunarrative:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :flutter_trunarrative:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_trunarrative:mergeDebugShaders UP-TO-DATE
[        ] > Task :flutter_trunarrative:compileDebugShaders UP-TO-DATE
[        ] > Task :flutter_trunarrative:generateDebugAssets UP-TO-DATE
[        ] > Task :flutter_trunarrative:packageDebugAssets UP-TO-DATE
[  +76 ms] > Task :app:mergeDebugAssets
[ +400 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_trunarrative:generateDebugResValues UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :flutter_trunarrative:compileDebugRenderscript NO-SOURCE
[        ] > Task :flutter_trunarrative:generateDebugResources UP-TO-DATE
[        ] > Task :flutter_trunarrative:packageDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :flutter_trunarrative:generateDebugRFile UP-TO-DATE
[ +100 ms] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :flutter_trunarrative:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :flutter_trunarrative:prepareLintJar UP-TO-DATE
[        ] > Task :flutter_trunarrative:compileDebugKotlin UP-TO-DATE
[        ] > Task :flutter_trunarrative:generateDebugSources UP-TO-DATE
[        ] > Task :flutter_trunarrative:javaPreCompileDebug UP-TO-DATE
[        ] > Task :flutter_trunarrative:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :flutter_trunarrative:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:prepareLintJar UP-TO-DATE
[        ] > Task :app:generateDebugSources UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +194 ms] > Task :app:compileDebugJavaWithJavac FAILED
[   +1 ms] /Users/andrewcoutts/Projects/flutter_trunarrative/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:16: error: cannot access VDDocumentCapture$IVDDocumentCapture
[   +2 ms]     flutterEngine.getPlugins().add(new com.bottlepay.flutter_trunarrative.FlutterTruNarrativePlugin());
[        ]                               ^
[        ]   class file for com.dasnano.vddocumentcapture.VDDocumentCapture$IVDDocumentCapture not found
[        ] 1 error
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2s
[        ] 34 actionable tasks: 4 executed, 30 up-to-date
[ +388 ms] Running Gradle task 'assembleDebug'... (completed in 3.3s)
[+3695 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 12,595ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:593:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:869:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +106 ms] ensureAnalyticsSent: 105ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
Analyzing flutter_aar_issue...                                          
No issues found! (ran in 3.0s)
```

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.21.0-1.0.pre at /Users/andrewcoutts/Projects/flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andrewcoutts/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/andrewcoutts/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • macOS (desktop)                       • macos         • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)                      • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by acoutts** [comment]
The issue was in the way I was implementing the imported aar modules. When I moved their implementation into a new class (not using the one implementing the flutter plugin too), I was able to successfully build.
