### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = 'C:\Program Files\flutter\packages\flutter_tools\.packages' (OS Error: Accès refusé., errno = 5)

### ISSUE THREAD

**Issue by STE-DANIEL** [flutter/flutter#63266]
## Command
```
flutter create NEWAPP
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = 'C:\Program Files\flutter\packages\flutter_tools\.packages' (OS Error: Accès refusé.
, errno = 5)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:213:19)
#4      _ensurePackageDependencies (package:flutter_tools/src/template.dart:265:13)
#5      _templateImageDirectory (package:flutter_tools/src/template.dart:254:11)
#6      Template.fromName (package:flutter_tools/src/template.dart:63:38)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:629:46)
#8      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:543:29)
#9      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:380:37)
#10     _rootRunUnary (dart:async/zone.dart:1192:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#18     FlutterProject.organizationNames (package:flutter_tools/src/project.dart)
#19     _rootRunUnary (dart:async/zone.dart:1192:38)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [version 10.0.18363.900], locale fr-FR)
    • Flutter version 1.17.5 at C:\Program Files\flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\STE\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\STE\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\STE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • SM G955N • 127.0.0.1:62001 • android-x86 • Android 5.1.1 (API 22)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Hi @STE-DANIEL,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate.
Thanks.
