### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Unable to read project 'Runner.xcodeproj'.	Reason: Could not open workspace file at ~/projects/-Mobile/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata Command: /usr/bin/xcodebuild, OS error code: 74

### ISSUE THREAD

**Issue by VJPranay** [flutter/flutter#63280]
## Command
```
flutter build ios --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: Could not open workspace file at ~/projects/-Mobile/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata Command: /usr/bin/xcodebuild, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:323:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:381:50)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:122:78)
<asynchronous suspension>
#4      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:93:43)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#13     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#22     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
```
```
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.0 at /Users/vjpranay/.asdf/installs/flutter/1.17.4
    • Framework revision 916c3ac648 (7 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/Caskroom/android-platform-tools/30.0.0
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    ✗ No valid Android SDK platforms found in /usr/local/Caskroom/android-platform-tools/30.0.0/platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • VJ’s iPhone (mobile) • 00008020-001514813433002E • ios • iOS 13.5

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 659dc8129d4edb9166e9a0d600439d135740933f

**Comment by darshankawar** [comment]
Hi @VJPranay,
There's similar open issue describing your case, [57083](https://github.com/flutter/flutter/issues/57083).
Please follow-up there for updates.
Closing this as duplicate. Also there's [this](https://github.com/flutter/flutter/issues/57083#issuecomment-654394040) workaround, try and see if it works for you.

**Comment by jmagman** [comment]
This shouldn't have been closed as a duplicate.  Fortunately the error message from xcode is pretty good, so let's switch to a tool exit instead of crashing.
