### ISSUE TITLE
Build issue for any Flutter App.

### ISSUE THREAD

**Issue by Snick-m** [flutter/flutter#63298]
Hello,

Whenever I try to run / build a Flutter Application I'm facing this issue. 
```
FAILURE: Build failed with an exception.

* Where:
Build file 'F:\Intvill\Project_SecEnt\flutter_app_2\android\build.gradle' line: 8

* What went wrong:
A problem occurred evaluating root project 'android'.
> org/gradle/internal/fingerprint/impl/DefaultFileCollectionFingerprinterRegistry$1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 565ms
```

Contents of /android/build.gradle :-
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

System information :-
    OS : Windows 10 64bit
    CPU: AMD Ryzen 3500X ( Virtualization enabled. Hyper-V disabled.)
    GPU: AMD RX 550 4GB
    RAM: 8GBx2 3200MHz

    Flutter version : 
        Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
        Framework • revision 2ae34518b8 (3 days ago) • 2020-08-05 19:53:19 -0700
        Engine • revision c8e3b94853
        Tools • Dart 2.9.0

## Steps to Reproduce

1. Run `flutter create <anyNameYouWant>`.

**Expected results:** 

Application builds properly and runs on Phone or Emulator.

**Actual results:** 

`FAILURE: Build failed with an exception.`
Both for old working projects and newly created ones. New boilerplate and newly made ones with code. Also tried project from other system that's working

<details>
  <summary>Logs</summary>

```
flutter run --verbose

[  +90 ms] executing: [G:\Flutter_SDK\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +1 ms] executing: [G:\Flutter_SDK\flutter/] git tag --contains HEAD
[ +168 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.1
[   +9 ms] executing: [G:\Flutter_SDK\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [G:\Flutter_SDK\flutter/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +47 ms] executing: [G:\Flutter_SDK\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +44 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing: G:\ANDROID_SDK\platform-tools\adb.exe devices -l
[  +28 ms] List of devices attached
           6db96ae1               device product:whyred model:Redmi_Note_5_Pro device:whyred transport_id:2
[   +5 ms] G:\ANDROID_SDK\platform-tools\adb.exe -s 6db96ae1 shell getprop
[ +103 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +327 ms] Generating
F:\Intvill\Project_SecEnt\flutter_app_2\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +20 ms] ro.hardware = qcom
[ +211 ms] Starting incremental build...
[   +3 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +8 ms] complete
[   +3 ms] Launching lib\main.dart on Redmi Note 5 Pro in debug mode...
[   +5 ms] G:\Flutter_SDK\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
G:\Flutter_SDK\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
G:\Flutter_SDK\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\MUSHFI~1\AppData\Local\Temp\flutter_tools.5ce02d5a\flutter_tool.cde7434\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[  +15 ms] executing: G:\ANDROID_SDK\platform-tools\adb.exe -s 6db96ae1 shell -x logcat -v time -t 1
[ +212 ms] Exit code 0 from: G:\ANDROID_SDK\platform-tools\adb.exe -s 6db96ae1 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of crash
           08-08 22:27:44.208 F/linker  (21823): CANNOT LINK EXECUTABLE "/system/bin/dpmd":
           "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit
[   +1 ms] executing: G:\ANDROID_SDK\platform-tools\adb.exe -s 6db96ae1 shell -x logcat -v time -t 1
[ +147 ms] Exit code 0 from: G:\ANDROID_SDK\platform-tools\adb.exe -s 6db96ae1 shell -x logcat -v time -t 1
[        ] --------- beginning of crash
           08-08 22:27:44.208 F/linker  (21823): CANNOT LINK EXECUTABLE "/system/bin/dpmd":
           "/system/lib64/libdpmframework.so" is 32-bit instead of 64-bit
[   +9 ms] <- compile package:flutter_app_2/main.dart
[   +6 ms] executing: G:\ANDROID_SDK\platform-tools\adb.exe version
[  +16 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as G:\ANDROID_SDK\platform-tools\adb.exe
[   +2 ms] executing: G:\ANDROID_SDK\platform-tools\adb.exe start-server
[  +23 ms] Building APK
[  +14 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from F:\Intvill\Project_SecEnt\flutter_app_2\android\gradlew.bat.
[   +1 ms] F:\Intvill\Project_SecEnt\flutter_app_2\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +9 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +588 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +2 ms] executing: [F:\Intvill\Project_SecEnt\flutter_app_2\android/]
F:\Intvill\Project_SecEnt\flutter_app_2\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=F:\Intvill\Project_SecEnt\flutter_app_2\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +733 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[        ] Build file 'F:\Intvill\Project_SecEnt\flutter_app_2\android\build.gradle' line: 8
[        ] * What went wrong:
[        ] A problem occurred evaluating root project 'android'.
[        ] > org/gradle/internal/fingerprint/impl/DefaultFileCollectionFingerprinterRegistry$1
[   +1 ms] * Try:
[   +3 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 584ms
[ +337 ms] Running Gradle task 'assembleDebug'... (completed in 1.7s)
[+9053 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 11,987ms.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +253 ms] ensureAnalyticsSent: 251ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
Analyzing flutter_app_2...
No issues found! (ran in 38.2s)
```

```
flutter doctor -v

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
    • Flutter version 1.20.1 at G:\Flutter_SDK\flutter
    • Framework revision 2ae34518b8 (3 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at G:\ANDROID_SDK
    • Platform android-30, build-tools 30.0.1
    • ANDROID_SDK_ROOT = G:\ANDROID_SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Redmi Note 5 Pro (mobile) • 6db96ae1 • android-arm64 • Android 9 (API 28)

• No issues found!
```

</details>

**Comment by markusaksli-nc** [comment]
Hi @Snick-m 
I cannot reproduce this issue. Could you please re-download a fresh version of stable `1.20.1` from [flutter.dev](https://flutter.dev/docs/development/tools/sdk/releases), run `flutter create bug` and simply attempt to run the default project? Could you also provide the contents of `/android/app/build.gradle`?
Thank you

**Comment by Snick-m** [comment]
Hello, Thank you for the response.

I never installed Gradle separately I just got it with my flutter installation and project creation therefore I don't even know how I'd go about doing that. And I will try clearing the cache.

Meanwhile here's the contents of `/android/app/build.gradle` :-

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.intvill.flutter_app_2"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

**Comment by markusaksli-nc** [comment]
@Snick-m 
Please add the following compileOptions to your default `flutter create` app `/android/app/build.gradle` file

```
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
After this clear Gradle cache once again and then `flutter run` the default app. Flutter should set up Gradle again at this point. Let me know if this doesn't fix it.

**Comment by Snick-m** [comment]
Hello, Thanks for the response.

I've attempted that and yes the caches folder gets repopulated on `flutter run` but I'm still stuck with the same error.

**Comment by markusaksli-nc** [comment]
Not sure what more to recommend at this point. First triage cannot repro or help solve this, seems like an individual config or corruption issue with Gradle. Labeling as passed first triage. This means someone more qualified should show up to help you out.

**Comment by Snick-m** [comment]
Hello, Thank you for your effort.

I also believe this is an individual configuration issue and therefore mentioned system info. Is there any guide that will walk me through completely removing every trace of Flutter, Gradle, Android SDK, Android Studio and ANYTHING related to these so I can do a 100% clean reinstall of everything one by one?

**Comment by markusaksli-nc** [comment]
If you want to try deleting everything and start fresh I would:

1. Delete Flutter SDK
2. Delete [%LOCALAPPDATA%\Pub\Cache\bin](https://dart.dev/tools/pub/glossary#system-cache)
3. Uninstall Flutter and Dart plugins from Android Studio
4. Take a look at either [upgrading or manually re-installing Gradle](https://gradle.org/install/). 

This is just a personal guess at this point and you may end up doing a lot of work for no reason with these steps. The problem is more likely just with Gradle, but I'm not an expert on it.

**Comment by Snick-m** [comment]
Alright, thank you for all the assistance. I'll just give these a shot anyways while waiting for someone else to possibly help me out.

**Comment by Snick-m** [comment]
> If you want to try deleting everything and start fresh I would:
> 
> 1. Delete Flutter SDK
> 2. Delete [%LOCALAPPDATA%\Pub\Cache\bin](https://dart.dev/tools/pub/glossary#system-cache)
> 3. Uninstall Flutter and Dart plugins from Android Studio
> 4. Take a look at either [upgrading or manually re-installing Gradle](https://gradle.org/install/).
> 
> This is just a personal guess at this point and you may end up doing a lot of work for no reason with these steps. The problem is more likely just with Gradle, but I'm not an expert on it.

Okay so I followed these steps with no hope of actual progress but it seems to have done the job. It was most definitely a specific config problem unfortunately I failed to pinpoint what it exactly was but I'm guessing it was the manual reinstallation of Gradle.

And with that I'm closing this issue.
