### ISSUE TITLE
Failed assertion: line 4268 pos 12: '!_dirty': is not true. While using Flutter's built in Widgets.

### ISSUE THREAD

**Issue by yoniker** [flutter/flutter#63307]
## Steps to Reproduce

clone the repo https://github.com/buurzx/tinderCloneUI

Run it, and then press either the like or unlike buttons (swiping motions are working, pressing the green heart or red X (close) buttons shows the error at the consol

```
**Expected results:** <!-- what did you want to see? -->
Smoothly working
**Actual results:** <!-- what did you see? -->
Weird errors which might affect the behavior of apps.
Specifically this error;
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4268 pos 12: '!_dirty': is not
true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  CardStack file:///C:/Users/Yoni/Projects/tinderCloneUI/lib/main.dart:123:17

When the exception was thrown, this was the stack:
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4268:12)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#12     _invoke (dart:ui/hooks.dart:253:10)
#13     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)

The element being rebuilt at the time was index 0 of 2:
  CardStack
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4268 pos 12: '!_dirty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CardStack file:///C:/Users/Yoni/Projects/tinderCloneUI/lib/main.dart:123:17
When the exception was thrown, this was the stack: 
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4268:12)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...
The element being rebuilt at the time was index 0 of 2: CardStack
  dirty
  dependencies: [MediaQuery]
  state: _CardStackState#e734f
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8652): user decision: Like

Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4268 pos 12: '!_dirty': is not true.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4268 pos 12: '!_dirty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CardStack file:///C:/Users/Yoni/Projects/tinderCloneUI/lib/main.dart:123:17
When the exception was thrown, this was the stack: 
#2      Element.rebuild (package:flutter/src/widgets/framework.dart:4268:12)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
...
The element being rebuilt at the time was index 0 of 2: CardStack
  dirty
  dependencies: [MediaQuery]
  state: _CardStackState#e734f
<details>
  <summary>Logs</summary>

<!--
      Run your application with `flutter run --verbose` and attach all the
      log output below between the lines with the backticks. If there is an
      exception, please see if the error message includes enough information
      to explain how to solve the issue.
-->

```
```

<!--
     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.
-->
 flutter analyze
Analyzing tinderCloneUI...
No issues found! (ran in 3.4s)
```
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (3 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Yoni\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```
```

</details>

**Comment by TahaTesser** [comment]
Hi @yoniker 
There is a lot of things going on in your code, please isolate the the code that's causing this issue.
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample  
Please read  [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by yoniker** [comment]
Hi,

In the end, the problem was trying to access invalid index within the build(...) method,
which is a silly programming bug- but I do wish that Flutter would give me a relevant error rather than send me here.

If you are more interested in details, just notice that adding matchEngine.cycleMatch();  at main.dart at the BottomAppBar's offending buttons (like,superlike or dont like) onclick method resolves the issue,as it updates the indexes of the currentMatch and nextMatch.
Again,just wish the error message within build() would point me out to that :)

Going to close the issue in a day or two in case someone else won't close it before me.

**Comment by TahaTesser** [comment]
Hi @yoniker 
If you've suggestion for better error message, please provide minimal code sample as request earlier and steps to reproduce this error.
Better error message would be useful for sure.
Thank you
