### ISSUE TITLE
Windows: Flutter failed to upgrade, lacks sufficient permission

### ISSUE THREAD

**Issue by seadynamic8** [flutter/flutter#63349]
Flutter failed to upgrade on Windows 10 machine, because of permission error.  For: storage.googleapis.com

```
[flutter] flutter upgrade
Upgrading Flutter from C:\Users\*****\Documents\flutter...
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine c8e3b9485386425213e2973126d6f57e7ed83c54...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...

Upgrading engine...
Downloading Android Maven dependencies...                           8.6s
Downloading android-arm-profile/windows-x64 tools...            

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot open file, path = 'C:\Users\*****\Documents\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\c8e3b9485386425213e2973126d6f57e7ed83c54\android-arm-profile\windows-x64.zip' (OS Error: Access is denied.
, errno = 5)".
A crash report has been written to C:\Users\*****\Documents\flutter\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+open+file%2C+path+%3D+%27C%3A%5CUsers%5Cseady%5CDocuments%5Cflutter%5Cbin%5Ccache%5Cdownloads%5Cstorage.googleapis.com%5Cflutter_infra%5Cflutter%5Cc8e3b9485386425213e2973126d6f57e7ed83c54%5Candroid-arm-profile%5Cwindows-x64.zip%27+%28OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JJM8v

exit code 1
```

```
 flutter doctor -v
Downloading package sky_engine...

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot open file, path =
'C:\Users\*****\Documents\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\c8e3b9485386425213e2973126d6f57e7ed83c54\sky_engine.zip' (OS Error: Access is denied.
, errno = 5)".
A crash report has been written to D:\Code\flutter_04.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+open+file%2C+path+%3D+%27C%3A%5CUsers%5Cseady%5CDocuments%5Cflutter%5Cbin%5Ccache%5Cdownloads%5Cstorage.googleapis.com%5Cflutter_infra%5Cflutter%5Cc8e3b9485386425213e2973126d6f57e7ed83c54%5Csky_engine.zip%27+%28OS+Error%3A+Access+is+denied.%0D%0A%2C+errno+%3D+5%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JJM8U
```

### Logs

````
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\*****\Documents\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\c8e3b9485386425213e2973126d6f57e7ed83c54\sky_engine.zip' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.20.1 at C:\Users\*****\Documents\flutter
    • Framework revision 2ae34518b8 (4 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\*****\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\*****\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
Hi @seadynamic8,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates.
Closing this as duplicate.
