### ISSUE TITLE
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: io.flutter.embedding.android.FlutterSplashView$SavedState

### ISSUE THREAD

**Issue by WoYang** [flutter/flutter#63350]
I have been getting below exception in my flutter app's :
```
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: io.flutter.embedding.android.FlutterSplashView$SavedState
   at android.os.Parcel.readParcelableCreator(Parcel.java:2851)
   at android.os.Parcel.readParcelable(Parcel.java:2766)
   at android.os.Parcel.readValue(Parcel.java:2669)
   at android.os.Parcel.readSparseArrayInternal(Parcel.java:3130)
   at android.os.Parcel.readSparseArray(Parcel.java:2352)
   at android.os.Parcel.readValue(Parcel.java:2726)
   at android.os.Parcel.readArrayMapInternal(Parcel.java:3049)
   at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
   at android.os.BaseBundle.unparcel(BaseBundle.java:232)
   at android.os.Bundle.getSparseParcelableArray(Bundle.java:1010)
   at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2133)
   at android.app.Activity.onRestoreInstanceState(Activity.java:1135)
   at android.app.Activity.performRestoreInstanceState(Activity.java:1090)
   at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1317)
   at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2967)
   at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
   at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
   at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1819)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:206)
   at android.app.ActivityThread.main(ActivityThread.java:6683)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

flutter doctor log:
```
D:\flutter_workspace\Environment\flutter_windows_1.17.3-stable\flutter\bin\flutter.bat doctor --verbose
Waiting for another flutter command to release the startup lock...
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.17134.1610], locale zh-CN)
    • Flutter version 1.17.3 at D:\flutter_workspace\Environment\flutter_windows_1.17.3-stable\flutter
    • Framework revision b041144f83 (9 weeks ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Tools\Android\SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = D:\Tools\Android\SDK
    • Java binary at: D:\Tools\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at D:\Tools\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • *** • 16173480088805 • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
Process finished with exit code 0

```

**Comment by TahaTesser** [comment]
Hi @WoYang 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
