### ISSUE TITLE
Exception in shortcuts while using the widget inspector

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#63353]
Not sure how to repro, unfortunately, but hopefully the stack trace is helpful...

## Stack trace

```
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 77 pos 16: 'keys.isNotEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:77:16)
#3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
#4      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:181:63)
#5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:309:63)
#6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:472:20)
...
```

## Other info

```
[✓] Flutter (Channel master, 1.21.0-8.0.pre.120, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.21.0-8.0.pre.120 at /Users/tvolkert/project/flutter/flutter
    • Framework revision 4500a451dc (26 hours ago), 2020-08-08 18:21:45 -0700
    • Engine revision d7c98913ed
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0aa5b0f019)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tvolkert/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode_11.2.1.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

/cc @gspencergoog

**Comment by gspencergoog** [comment]
From what I can tell in the code, this could happen if it received a key down event, but no keys were actually down (as reported by `RawKeyboard.instance.keysPressed`). I'm not sure how that could happen, however. The code for generating the key down event shouldn't be able to get into that state.

It might be possible if you're simulating keys, and doing it badly (i.e. if the key down is a shift key, but the shift key modifier flag isn't set).

**Comment by tvolkert** [comment]
iirc I was alt-tabbing away at the time, but I can't reproduce the issue doing so...

**Comment by gspencergoog** [comment]
What platform was this on? Android, macOS, or web?

**Comment by tvolkert** [comment]
MacOS - desktop embedder
