### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/rishuroy/Developer/flutter/bin/cache/artifacts/engine/android-arm64-release/darwin-x64/gen_snapshot.

### ISSUE THREAD

**Issue by imrishuroy** [flutter/flutter#63409]
## Command
```
flutter --quiet assemble --depfile /Users/rishuroy/Documents/LAB/note_keeper/build/app/intermediates/flutter/release/flutter_build.d --output /Users/rishuroy/Documents/LAB/note_keeper/build/app/intermediates/flutter/release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/rishuroy/Developer/flutter/bin/cache/artifacts/engine/android-arm64-release/darwin-x64/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:466:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:484:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:235:52)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:795:27)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:738:35)
#9      new Future.sync (dart:async/future.dart:223:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:738:21)
<asynchronous suspension>
<asynchronous suspension>
#12     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#13     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#14     Future.wait (dart:async/future.dart:402:26)
#15     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:733:45)
#16     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:560:36)
#17     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#19     _rootRunUnary (dart:async/zone.dart:1198:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-IN)
    • Flutter version 1.20.1 at /Users/rishuroy/Developer/flutter
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/rishuroy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
### Plugins
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
sqflite-1.3.1

**Comment by darshankawar** [comment]
Hi @imrishuroy,
Can you try [this](https://github.com/flutter/flutter/issues/45329#issuecomment-572683413) solution and see if it works for you ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
