### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by HamzaNa1** [flutter/flutter#63408]
I think this is happening because https://dl.google.com/dl/android/maven2/androidx/core/core/1.1.0/core-1.1.0.jar outdated/broken

### Steps to reproduce

1. create a new project
2. paste the code from [this cookbook example](https://flutter.dev/docs/cookbook/plugins/picture-using-camera)
3. add latest dependencies

```
camera: ^0.5.8+2
path_provider: ^1.6.11
```

<details>
 <summary>flutter run --verbose </summary>

```
[  +90 ms] executing: [/home/hamza/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 840c9205b344a59e48a5926ee2d791cc5640924c
[   +1 ms] executing: [/home/hamza/snap/flutter/common/flutter/] git tag --contains HEAD
[ +169 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.0
[   +6 ms] executing: [/home/hamza/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/hamza/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +65 ms] executing: [/home/hamza/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +54 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +13 ms] executing: /home/hamza/Android/Sdk/platform-tools/adb devices -l
[  +49 ms] List of devices attached
           NB1GAD1780404016       device usb:2-1 product:TA-1004_00WW model:TA_1004 device:NB1 transport_id:4
[   +6 ms] /home/hamza/Android/Sdk/platform-tools/adb -s NB1GAD1780404016 shell getprop
[  +72 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +106 ms] Found plugin camera at /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.8+2/
[  +22 ms] Found plugin path_provider at /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11/
[   +2 ms] Found plugin path_provider_linux at /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +3 ms] Found plugin path_provider_macos at /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[  +61 ms] Found plugin camera at /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.8+2/
[   +8 ms] Found plugin path_provider at /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.11/
[   +2 ms] Found plugin path_provider_linux at /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +2 ms] Found plugin path_provider_macos at /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+3/
[  +65 ms] Generating /home/hamza/Desktop/flutter/image_editor/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +20 ms] ro.hardware = qcom
[  +69 ms] Starting incremental build...
[   +2 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +3 ms] Launching lib/main.dart on TA 1004 in debug mode...
[  +12 ms] /home/hamza/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/hamza/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/hamza/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tools.LNNDYK/flutter_tool.OAAZZO/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +34 ms] executing: /home/hamza/Android/Sdk/platform-tools/adb -s NB1GAD1780404016 shell -x logcat -v time -t 1
[  +59 ms] Exit code 0 from: /home/hamza/Android/Sdk/platform-tools/adb -s NB1GAD1780404016 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           08-10 21:08:25.071 D/WifiTrafficPoller( 1403):  packet count Tx=12560025 Rx=16653437
[   +1 ms] executing: /home/hamza/Android/Sdk/platform-tools/adb -s NB1GAD1780404016 shell -x logcat -v time -t 1
[  +52 ms] Exit code 0 from: /home/hamza/Android/Sdk/platform-tools/adb -s NB1GAD1780404016 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           08-10 21:08:25.071 D/WifiTrafficPoller( 1403):  packet count Tx=12560025 Rx=16653437
[   +5 ms] <- compile package:image_editor/main.dart
[  +24 ms] executing: /home/hamza/Android/Sdk/platform-tools/adb version
[   +9 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as /home/hamza/Android/Sdk/platform-tools/adb
[   +6 ms] executing: /home/hamza/Android/Sdk/platform-tools/adb start-server
[  +15 ms] Building APK
[  +27 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +8 ms] Using gradle from /home/hamza/Desktop/flutter/image_editor/android/gradlew.
[   +2 ms] /home/hamza/Desktop/flutter/image_editor/android/gradlew mode: 33277 rwxrwxr-x.
[  +13 ms] executing: /usr/local/android-studio/jre/bin/java -version
[  +84 ms] Exit code 0 from: /usr/local/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +3 ms] executing: [/home/hamza/Desktop/flutter/image_editor/android/] /home/hamza/Desktop/flutter/image_editor/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=/home/hamza/Desktop/flutter/image_editor/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +524 ms] Welcome to Gradle 5.6.2!
[        ] Here are the highlights of this release:
[   +1 ms]  - Incremental Groovy compilation
[        ]  - Groovy compile avoidance
[        ]  - Test fixtures for Java projects
[        ]  - Manage plugin versions via settings script
[        ] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[+4487 ms] > Task :app:compileFlutterBuildDebug
[        ] [ +109 ms] executing: [/home/hamza/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 840c9205b344a59e48a5926ee2d791cc5640924c
[        ] [        ] executing: [/home/hamza/snap/flutter/common/flutter/] git tag --contains HEAD
[   +5 ms] [ +175 ms] Exit code 0 from: git tag --contains HEAD
[        ] [        ] 1.20.0
[        ] [   +7 ms] executing: [/home/hamza/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/hamza/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +39 ms] executing: [/home/hamza/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +9 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +88 ms] Initializing file store
[        ] [  +16 ms] Done initializing file store
[        ] [  +32 ms] Skipping target: gen_localizations
[        ] [ +735 ms] Skipping target: kernel_snapshot
[        ] [ +403 ms] debug_android_application: Starting due to {InvalidatedReason.inputChanged}
[ +167 ms] [ +242 ms] debug_android_application: Complete
[ +400 ms] [ +409 ms] Persisting file store
[        ] [  +12 ms] Done persisting file store
[        ] [   +6 ms] build succeeded.
[        ] [   +9 ms] "flutter assemble" took 1,983ms.
[        ] [   +3 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +2 ms] exiting with code 0
[ +197 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +3 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +8 ms] > Task :camera:preBuild UP-TO-DATE
[        ] > Task :camera:preDebugBuild UP-TO-DATE
[        ] > Task :camera:compileDebugAidl NO-SOURCE
[        ] > Task :path_provider:preBuild UP-TO-DATE
[        ] > Task :path_provider:preDebugBuild UP-TO-DATE
[        ] > Task :path_provider:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :camera:packageDebugRenderscript NO-SOURCE
[        ] > Task :path_provider:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :camera:mergeDebugShaders UP-TO-DATE
[        ] > Task :camera:compileDebugShaders UP-TO-DATE
[        ] > Task :camera:generateDebugAssets UP-TO-DATE
[        ] > Task :camera:packageDebugAssets UP-TO-DATE
[        ] > Task :path_provider:mergeDebugShaders UP-TO-DATE
[        ] > Task :path_provider:compileDebugShaders UP-TO-DATE
[        ] > Task :path_provider:generateDebugAssets UP-TO-DATE
[        ] > Task :path_provider:packageDebugAssets UP-TO-DATE
[  +81 ms] > Task :app:mergeDebugAssets
[ +201 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :camera:generateDebugResValues UP-TO-DATE
[        ] > Task :path_provider:compileDebugRenderscript NO-SOURCE
[        ] > Task :camera:compileDebugRenderscript NO-SOURCE
[        ] > Task :camera:generateDebugResources UP-TO-DATE
[        ] > Task :camera:packageDebugResources UP-TO-DATE
[        ] > Task :path_provider:generateDebugResValues UP-TO-DATE
[        ] > Task :path_provider:generateDebugResources UP-TO-DATE
[        ] > Task :path_provider:packageDebugResources UP-TO-DATE
[  +95 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :camera:checkDebugManifest UP-TO-DATE
[        ] > Task :camera:processDebugManifest UP-TO-DATE
[        ] > Task :path_provider:checkDebugManifest UP-TO-DATE
[        ] > Task :path_provider:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :camera:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :camera:generateDebugRFile UP-TO-DATE
[        ] > Task :path_provider:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :path_provider:generateDebugRFile UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :camera:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :camera:javaPreCompileDebug FAILED
[  +91 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Execution failed for task ':camera:javaPreCompileDebug'.
[        ] > Could not resolve all files for configuration ':camera:debugCompileClasspath'.
[        ]    > Could not find core.jar (androidx.core:core:1.1.0).
[        ]      Searched in the following locations:
[        ]          https://dl.google.com/dl/android/maven2/androidx/core/core/1.1.0/core-1.1.0.jar
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 6s
[        ] 35 actionable tasks: 5 executed, 30 up-to-date
[ +328 ms] Running Gradle task 'assembleDebug'... (completed in 6.7s)
[   +2 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[   +8 ms] Building plugin camera...
[   +7 ms] Running Gradle task 'assembleAarRelease'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.8+2/android/gradlew.
[        ] /home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.8+2/android/gradlew mode: 33277 rwxrwxr-x.
[   +1 ms] executing: [/home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.8+2/android/]
/home/hamza/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/camera-0.5.8+2/android/gradlew
-I=/home/hamza/snap/flutter/common/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/home/hamza/snap/flutter/common/flutter
-Poutput-dir=/home/hamza/Desktop/flutter/image_editor/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+1343 ms] 
                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    A problem occurred configuring root project 'camera'.
                    > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 1s
[        ] Running Gradle task 'assembleAarRelease'... (completed in 1.4s)
[        ] 
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           A problem occurred configuring root project 'camera'.
           > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 1s
           
[   +3 ms] Exception: The plugin camera could not be built due to the issue above.
[   +1 ms] "flutter run" took 8,943ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +255 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +8 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0 at /home/hamza/snap/flutter/common/flutter
    • Framework revision 840c9205b3 (6 days ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/hamza/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • TA 1004 (mobile) • NB1GAD1780404016 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```
</details>

**Comment by markusaksli-nc** [comment]
Hi @HamzaNa1 
I can run the example perfectly well. Please try https://github.com/flutter/flutter/issues/57309#issuecomment-630721205
since this is likely an issue with your build.gradle. Closing since this is not an issue with Flutter.
Thank you
