### ISSUE TITLE
V1.20.1-- java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Surface.release()' on a null object reference

### ISSUE THREAD

**Issue by lishuliang28** [flutter/flutter#63449]
The page of the low version page is closed and the app crashes. I see that some people have mentioned it in previous versions, but the latest version of v1.20.1 still exists. When can this problem be upgraded to a stable version? Or we can't use it
一、log
    Process: com.xiaoban.mobile, PID: 8897
    java.lang.RuntimeException: Unable to destroy activity {com.xiaoban.mobile/com.xiaoban.mobile.v4.ui.ActivityFlutter}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Surface.release()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4109)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4127)
        at android.app.ActivityThread.access$1500(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5835)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Surface.release()' on a null object reference
        at io.flutter.embedding.android.FlutterTextureView.disconnectSurfaceFromRenderer(FlutterTextureView.java:224)
        at io.flutter.embedding.android.FlutterTextureView.detachFromRenderer(FlutterTextureView.java:166)
        at io.flutter.embedding.android.FlutterView.detachFromFlutterEngine(FlutterView.java:945)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDestroyView(FlutterActivityAndFragmentDelegate.java:456)
        at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:577)
        at com.xiaoban.mobile.v4.ui.ActivityFlutter.onDestroy(ActivityFlutter.java:172)
        at android.app.Activity.performDestroy(Activity.java:6451)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4096)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4127) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:172) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:5835) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
二、（flutter doctor -v`）

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.959], locale zh-CN)
    • Flutter version 1.20.1 at C:\D\flutter\flutter
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Robust\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Robust\AppData\Local\Android\Sdk
    • Java binary at: C:\D\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\D\android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.3
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5901

[!] VS Code (version 1.43.0)
    • VS Code at C:\Users\Robust\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM G9006W (mobile) • 192.168.137.170:5555 • android-arm • Android 5.0 (API 21)

! Doctor found issues in 1 category.

**Comment by lishuliang28** [comment]
Or is there any other solution to avoid this problem and use it normally

**Comment by lishuliang28** [comment]
// FlutterRenderer must be non-null.
  private void disconnectSurfaceFromRenderer() {
    if (flutterRenderer == null) {
      throw new IllegalStateException(
          "disconnectSurfaceFromRenderer() should only be called when flutterRenderer is non-null.");
    }

    flutterRenderer.stopRenderingToSurface();
    renderSurface.release();
    renderSurface = null;
  }

**Comment by darshankawar** [comment]
Hi @lishuliang28,
There's similar open issue describing your case, [50950](https://github.com/flutter/flutter/issues/50950).
Please follow-up there for updates.
Closing this as duplicate.
