### ISSUE TITLE
Couldn't find libflutter.so

### ISSUE THREAD

**Issue by Sepehr13** [flutter/flutter#63462]
## Steps to Reproduce

1. Run `flutter create myapp`.
2. Add your signing key to flutter
3. Sign your app and get a release varient

**Expected results:** 
The should work just fine on any android device

**Actual results:** 
the app crashes the moment you touch the app icon

The debug variant works fine but release variant doesn't work at all

**Just for the record:**
- i cleaned it. 
- i tried to remake my project from scratch. 
- i added abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'mips', 'mips64', 'arm64-v8a'. 
- i even built with --split-per-abi flag. i tried to sign the apk with android studio and then install it. that didn't work either. 
- i changed the version of flutter multiple time. changed to master beta stable channel. none of them fixed the issue. 
- i opened the fat apk and it's really weird that libflutter.so is there right in the proper folders but android can't pick it up ?

<details>
  <summary>Logs</summary>

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.moshaveron.app, PID: 26315
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.moshaveron.app/com.example.moshaveron.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/lib/x86, /data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/lib/x86, /data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(Unknown Source:246)
        at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:150)
        at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:19)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(Unknown Source:110)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:7)
        at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:22)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/lib/x86, /data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(Unknown Source:23)
        at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:150) 
        at io.flutter.embedding.engine.FlutterEngine.<init>(Unknown Source:19) 
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(Unknown Source:110) 
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:7) 
        at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:22) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/lib/x86, /data/app/com.moshaveron.app-5pAD9es955nc0lR2SqLCkQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(Unknown Source:10)
        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-08-10 23:45:50.092 26315-26315/? E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:764)
2020-08-10 23:45:50.101 1679-7140/? W/ActivityManager:   Force finishing activity com.moshaveron.app/com.example.moshaveron.MainActivity
```

**flutter analyze result:**

```
info - Cancel instances of dart.async.StreamSubscription - lib\bloc\NetworkConnectivityHandler.dart:8:22 - cancel_subscriptions
   info - Unused import: 'dart:convert' - lib\bloc\SocketIOHandler.dart:2:8 - unused_import
   info - Close instances of `dart.core.Sink` - lib\bloc\SocketIOHandler.dart:6:20 - close_sinks
   info - 'ControlledAnimation' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration -
          lib\helpers\AnimatedWave.dart:19:16 - deprecated_member_use
   info - 'Playback' is deprecated and shouldn't be used. See migration guide: https://pub.dev/packages/sa_v1_migration - lib\helpers\AnimatedWave.dart:20:23 -        
          deprecated_member_use
   info - The value of the field '_decoder' isn't used - lib\helpers\Signaling.dart:33:15 - unused_field
   info - Name non-constant identifiers using lowerCamelCase - lib\helpers\Signaling.dart:79:30 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\helpers\Signaling.dart:107:22 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\helpers\Signaling.dart:107:45 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\helpers\Signaling.dart:276:43 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\helpers\Signaling.dart:300:43 - non_constant_identifier_names
   info - Unused import: 'package:moshaveron/videoCall.dart' - lib\home.dart:22:8 - unused_import
   info - This function has a return type of 'FutureOr<bool>', but doesn't end with a return statement - lib\home.dart:413:18 - missing_return
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement - lib\intro.dart:55:18 - missing_return
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement - lib\login.dart:222:18 - missing_return
   info - Unused import: 'package:file_picker/file_picker.dart' - lib\moshaverShoPages\step2.dart:5:8 - unused_import
   info - Unused import: 'package:flutter/services.dart' - lib\moshaverShoPages\step5.dart:11:8 - unused_import
   info - The declaration '_getList' isn't referenced - lib\pages\checkOut.dart:159:8 - unused_element
   info - Unused import: 'dart:async' - lib\pages\commentsPage.dart:1:8 - unused_import
   info - Unused import: 'package:flutter_picker/flutter_picker.dart' - lib\pages\home.dart:9:8 - unused_import
   info - Unused import: 'package:moshaveron/pages/moshaverGramPage.dart' - lib\pages\home.dart:21:8 - unused_import
   info - Unused import: 'package:moshaveron/pages/moshaveranListPage.dart' - lib\pages\home.dart:22:8 - unused_import
   info - Unused import: 'package:page_indicator/page_indicator.dart' - lib\pages\home.dart:23:8 - unused_import
   info - The value of the field '_list' isn't used - lib\pages\home.dart:39:16 - unused_field
   info - This function has a return type of 'Future<String>', but doesn't end with a return statement - lib\pages\home.dart:91:50 - missing_return
   info - Unused import: 'package:animations/animations.dart' - lib\pages\moshaverGramPage.dart:1:8 - unused_import
   info - The value of the field '_categoriesList' isn't used - lib\pages\moshaverGramPage.dart:14:30 - unused_field
   info - The value of the field '_selectedCategory' isn't used - lib\pages\moshaverGramPage.dart:35:10 - unused_field
   info - Unused import: 'package:carousel_slider/carousel_slider.dart' - lib\pages\moshaveranPage.dart:4:8 - unused_import
   info - Unused import: 'package:moshaveron/pages/profilePage.dart' - lib\pages\moshaveranPage.dart:11:8 - unused_import
   info - The value of the local variable 'color' isn't used - lib\pages\profilePage.dart:1488:57 - unused_local_variable
   info - The value of the field '_isProccessing' isn't used - lib\pages\workHours.dart:23:8 - unused_field
   info - Unused import: 'dart:convert' - lib\videoCall.dart:3:8 - unused_import
   info - The value of the field '_peers' isn't used - lib\videoCall.dart:18:17 - unused_field
   info - Name non-constant identifiers using lowerCamelCase - lib\videoCall.dart:103:32 - non_constant_identifier_names
   info - The declaration '_muteMic' isn't referenced - lib\videoCall.dart:119:3 - unused_element
```

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.20.1 at C:\flutter
    • Framework revision 2ae34518b8 (5 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Sepehr\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Sepehr\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at E:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Sepehr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] VS Code, 64-bit edition (version 1.33.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

all the plugin i used: 
```
cupertino_icons: ^0.1.3
  provider: ^4.3.2
  shared_preferences: ^0.5.8
  animations: ^1.1.2
  flutter_svg: ^0.18.0
  page_indicator: ^0.3.0
  pin_code_fields: ^4.0.0
  shimmer: ^1.1.1
  carousel_slider: ^2.2.1
  like_button: ^1.0.1
  flutter_picker: ^1.1.5
  image_picker: ^0.6.7+4
  image_cropper: ^1.3.0
  path_provider: ^1.6.11
  file_picker: ^1.13.3
  dio: ^3.0.10
  connectivity: ^0.4.9
  transparent_image: ^1.0.0
  rxdart: ^0.24.1
  string_validator: ^0.1.4
  package_info: ^0.4.1
  url_launcher: ^5.5.0
  cached_network_image: ^2.2.0+1
  sliding_up_panel: ^1.0.2
  intl: ^0.16.1
  simple_animations: ^2.2.1
  video_player: ^0.10.11+2
  flutter_colorpicker: ^0.3.4
  font_awesome_flutter: ^8.8.1
  random_color: ^1.0.5
  http: ^0.12.2
  socket_io_client: ^0.9.11
  flutter_webrtc: ^0.2.8
  fluttertoast: ^7.0.2
```

</details>

**Comment by Sepehr13** [comment]
Apparently the problem was flutter_webrtc so don't use this plugin until it's fixed.
does anybody knows any alternative ?
