### ISSUE TITLE
ListView error occurs when returning to the top

### ISSUE THREAD

**Issue by Artem738** [flutter/flutter#63470]
The error occurred after updating to 1.20

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15:
'scrollOffsetCorrection != 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  ListView file:///C:/Android/store_app_v2/lib/pages/product_item_page.dart:97:16

When the exception was thrown, this was the stack:
#2      new SliverGeometry (package:flutter/src/rendering/sliver.dart:556:15)
#3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:180:20)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#5      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:11)
#6      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:377:11)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#8      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
#9      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
#10     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
#11     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
#12     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
#13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#22     _invoke (dart:ui/hooks.dart:253:10)
#23     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)

The following RenderObject was being processed when the exception was fired: RenderSliverList#da52b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#f5104] ←
    Semantics ← _PointerListener ← Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#991ed] ← _PointerListener ← Listener
    ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward,
    scrollOffset: 218.9, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection:
    AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 1072.3, cacheOrigin:
    -218.9)
  geometry: SliverGeometry(scrollExtent: 2079.0, paintExtent: 603.4, maxPaintExtent: 2079.0,
    hasVisualOverflow: true, cacheExtent: 1103.4)
  currently live children: 0 to 2
This RenderObject had the following descendants (showing up to depth 5):
    child with index 0: RenderIndexedSemantics#11a91 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderRepaintBoundary#91c0d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderConstrainedBox#ffe8f relayoutBoundary=up5 NEEDS-PAINT
    child with index 1: RenderIndexedSemantics#e6c75 relayoutBoundary=up3
      child: RenderRepaintBoundary#890a6 relayoutBoundary=up4
        child: RenderSemanticsGestureHandler#cb50b relayoutBoundary=up5
          child: RenderPointerListener#5ec8c relayoutBoundary=up6
            child: RenderConstrainedBox#131c5 relayoutBoundary=up7
    child with index 2: RenderIndexedSemantics#cf527 relayoutBoundary=up3
      child: RenderRepaintBoundary#e948b relayoutBoundary=up4
        child: RenderSemanticsAnnotations#cde22 relayoutBoundary=up5
          child: RenderPadding#be25c relayoutBoundary=up6
            child: RenderPhysicalShape#88d1a relayoutBoundary=up7
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: NoSuchMethodError: The method '-' was called on null.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15: 'scrollOffsetCorrection != 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ListView file:///C:/Android/store_app_v2/lib/pages/product_item_page.dart:97:16
When the exception was thrown, this was the stack: 
#2      new SliverGeometry (package:flutter/src/rendering/sliver.dart:556:15)
#3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:180:20)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#5      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:11)
#6      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:377:11)
...
The following RenderObject was being processed when the exception was fired: RenderSliverList#da52b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 218.9, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 1072.3, cacheOrigin: -218.9)
...  geometry: SliverGeometry(scrollExtent: 2079.0, paintExtent: 603.4, maxPaintExtent: 2079.0, hasVisualOverflow: true, cacheExtent: 1103.4)
...    scrollExtent: 2079.0
...    paintExtent: 603.4
...    maxPaintExtent: 2079.0
...    hasVisualOverflow: true
...    cacheExtent: 1103.4
...  currently live children: 0 to 2
RenderObject: RenderSliverList#da52b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 218.9, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 1072.3, cacheOrigin: -218.9)
  geometry: SliverGeometry(scrollExtent: 2079.0, paintExtent: 603.4, maxPaintExtent: 2079.0, hasVisualOverflow: true, cacheExtent: 1103.4)
    scrollExtent: 2079.0
    paintExtent: 603.4
    maxPaintExtent: 2079.0
    hasVisualOverflow: true
    cacheExtent: 1103.4
  currently live children: 0 to 2
...  child with index 0: RenderIndexedSemantics#11a91 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: index=0; layoutOffset=None (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 0.0)
...    index: 0
...    child: RenderRepaintBoundary#91c0d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      size: Size(411.4, 0.0)
...      usefulness ratio: no metrics collected yet (never painted)
...      child: RenderConstrainedBox#ffe8f relayoutBoundary=up5 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        size: Size(411.4, 0.0)
...        additionalConstraints: BoxConstraints(unconstrained)
...  child with index 1: RenderIndexedSemantics#e6c75 relayoutBoundary=up3
...    needs compositing
...    parentData: index=1; layoutOffset=0.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 340.0)
...    index: 1
...    child: RenderRepaintBoundary#890a6 relayoutBoundary=up4
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#436f4
...        engine layer: OffsetEngineLayer#cebc6
...        offset: Offset(0.0, -336.6)
...      size: Size(411.4, 340.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderSemanticsGestureHandler#cb50b relayoutBoundary=up5
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        size: Size(411.4, 340.0)
...        gestures: tap
...        child: RenderPointerListener#5ec8c relayoutBoundary=up6
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 340.0)
...          behavior: deferToChild
...          listeners: down
...  child with index 2: RenderIndexedSemantics#cf527 relayoutBoundary=up3
...    needs compositing
...    parentData: index=2; layoutOffset=340.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 1739.0)
...    index: 2
...    child: RenderRepaintBoundary#e948b relayoutBoundary=up4
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#1bf29
...        engine layer: OffsetEngineLayer#662b3
...        offset: Offset(0.0, 3.4)
...      size: Size(411.4, 1739.0)
...      metrics: 98.7% useful (1 bad vs 75 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#cde22 relayoutBoundary=up5
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(411.4, 1739.0)
...        child: RenderPadding#be25c relayoutBoundary=up6
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 1739.0)
...          padding: EdgeInsets(35.0, 10.0, 35.0, 10.0)
...          textDirection: ltr
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15: 'scrollOffsetCorrection != 0.0': is not true.

Another exception was thrown: NoSuchMethodError: The method '-' was called on null.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The method '-' was called on null.
Receiver: null
Tried calling: -(218.85081070498495)
The relevant error-causing widget was: 
  ListView file:///C:/Android/store_app_v2/lib/pages/product_item_page.dart:97:16
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15: 'scrollOffsetCorrection != 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ListView file:///C:/Android/store_app_v2/lib/pages/product_item_page.dart:97:16
When the exception was thrown, this was the stack: 
#2      new SliverGeometry (package:flutter/src/rendering/sliver.dart:556:15)
#3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:180:20)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
#5      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:11)
#6      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:377:11)
...
The following RenderObject was being processed when the exception was fired: RenderSliverList#da52b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 853.4, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 2079.0, paintExtent: 603.4, maxPaintExtent: 2079.0, hasVisualOverflow: true, cacheExtent: 1103.4)
...    scrollExtent: 2079.0
...    paintExtent: 603.4
...    maxPaintExtent: 2079.0
...    hasVisualOverflow: true
...    cacheExtent: 1103.4
...  currently live children: 0 to 2
RenderObject: RenderSliverList#da52b relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 853.4, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 2079.0, paintExtent: 603.4, maxPaintExtent: 2079.0, hasVisualOverflow: true, cacheExtent: 1103.4)
    scrollExtent: 2079.0
    paintExtent: 603.4
    maxPaintExtent: 2079.0
    hasVisualOverflow: true
    cacheExtent: 1103.4
  currently live children: 0 to 2
...  child with index 0: RenderIndexedSemantics#a6e12 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: index=0; layoutOffset=None (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 0.0)
...    index: 0
...    child: RenderRepaintBoundary#9753f relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      size: Size(411.4, 0.0)
...      usefulness ratio: no metrics collected yet (never painted)
...      child: RenderConstrainedBox#952c1 relayoutBoundary=up5 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        size: Size(411.4, 0.0)
...        additionalConstraints: BoxConstraints(unconstrained)
...  child with index 1: RenderIndexedSemantics#e6c75 relayoutBoundary=up3
...    needs compositing
...    parentData: index=1; layoutOffset=0.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 340.0)
...    index: 1
...    child: RenderRepaintBoundary#890a6 relayoutBoundary=up4
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#436f4 DETACHED
...        engine layer: OffsetEngineLayer#cebc6
...        offset: Offset(0.0, -336.6)
...      size: Size(411.4, 340.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderSemanticsGestureHandler#cb50b relayoutBoundary=up5
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        size: Size(411.4, 340.0)
...        gestures: tap
...        child: RenderPointerListener#5ec8c relayoutBoundary=up6
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 340.0)
...          behavior: deferToChild
...          listeners: down
...  child with index 2: RenderIndexedSemantics#cf527 relayoutBoundary=up3
...    needs compositing
...    parentData: index=2; layoutOffset=340.0 (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(411.4, 1739.0)
...    index: 2
...    child: RenderRepaintBoundary#e948b relayoutBoundary=up4
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      layer: OffsetLayer#1bf29 DETACHED
...        engine layer: OffsetEngineLayer#662b3
...        offset: Offset(0.0, 3.4)
...      size: Size(411.4, 1739.0)
...      metrics: 98.7% useful (1 bad vs 75 good)
...      diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...      child: RenderSemanticsAnnotations#cde22 relayoutBoundary=up5
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        semantic boundary
...        size: Size(411.4, 1739.0)
...        child: RenderPadding#be25c relayoutBoundary=up6
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 1739.0)
...          padding: EdgeInsets(35.0, 10.0, 35.0, 10.0)
...          textDirection: ltr
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The method '-' was called on null.
Receiver: null
Tried calling: -(0.0)
The relevant error-causing widget was: 
  ListView file:///C:/Android/store_app_v2/lib/pages/product_item_page.dart:97:16

```
```
flutter doctor 

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.14393], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

**Comment by TahaTesser** [comment]
Hi @Artem738 
Closing since this was fixed in https://github.com/flutter/flutter/pull/62615 and is being reviewed for a cherrypick to 1.20. Please follow up on https://github.com/flutter/flutter/issues/62198 for updates on this.
Thank you
