### ISSUE TITLE
Running Gradle task 'assembleDebug'...

### ISSUE THREAD

**Issue by Azri99** [flutter/flutter#63481]
## Steps to Reproduce

1. I ran 'flutter run' and 'flutter run -v' (this is my first time in mobile development no experience in mobile development)
2. And then it just stay that ways for a long time
3. I have tried disable my firewall and it still the same

## Logs

```
```

1. run 'flutter run'

<details> 
<summary>logs</summary> 

```
Launching lib\main.dart on RMX1941 in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\azrir\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                          
Running Gradle task 'assembleDebug'... Done                       122.5s (!)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\azrir\.gradle\wrapper        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       121.3s (!)
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1
2. Log when run 'flutter run -v'

[ +588 ms] executing: [C:\Program Files\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +350 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +3 ms] executing: [C:\Program Files\flutter/] git tag --contains HEAD
[ +814 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.1
[  +37 ms] executing: [C:\Program Files\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +185 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +1 ms] executing: [C:\Program Files\flutter/] git ls-remote --get-url origin
[ +222 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +351 ms] executing: [C:\Program Files\flutter/] git rev-parse --abbrev-ref HEAD
[ +277 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +11 ms] stable
[ +308 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +21 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +61 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +46 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +43 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +92 ms] executing: C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +158 ms] List of devices attached
                    INU8H67HEMTSU8GY       device product:RMX1941 model:RMX1941 device:RMX1941 transport_id:13
[  +31 ms] C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe -s INU8H67HEMTSU8GY shell getprop
[ +284 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +28 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +92 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +37 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +161 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +50 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +877 ms] Generating C:\Users\azrir\Desktop\sideProject\flutter\test_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java[ +133 ms] ro.hardware = mt6765
[   +2 ms] ro.build.characteristics = default
[ +239 ms] Starting incremental build...
[  +13 ms] Initializing file store
[ +103 ms] Skipping target: gen_localizations
[  +53 ms] complete
[  +25 ms] Launching lib\main.dart on RMX1941 in debug mode...
[  +51 ms] C:\Program Files\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Program
Files\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Program
Files\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\azrir\AppData\Local\Temp\flutter_tools.93cd3b04\flutter_tool.fcff848\app.dill       
--packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions  
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[ +114 ms] executing: C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe -s INU8H67HEMTSU8GY shell -x logcat -v time -t 1
[ +211 ms] Exit code 0 from: C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe -s INU8H67HEMTSU8GY shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           08-11 21:40:08.269 D/TrafficStatsHelper( 1728): transmitted_validWifiData.get(0) = wlan0
[  +52 ms] executing: C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe -s INU8H67HEMTSU8GY shell -x logcat -v time -t 1
[ +299 ms] Exit code 0 from: C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe -s INU8H67HEMTSU8GY shell -x logcat -v time -t 1
[   +9 ms] --------- beginning of main
           08-11 21:40:08.324 I/ADB_SERVICES(31256): post waitpid (pid=31344) status=0000
[ +143 ms] <- compile package:test_app/main.dart
[  +86 ms] executing: C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +856 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.4-6686687
                    Installed as C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe
[ +118 ms] executing: C:\Users\azrir\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +412 ms] Building APK
[ +174 ms] Running Gradle task 'assembleDebug'...
[ +117 ms] gradle.properties already sets `android.enableR8`
[  +22 ms] Using gradle from C:\Users\azrir\Desktop\sideProject\flutter\test_app\android\gradlew.bat.
[  +51 ms] C:\Users\azrir\Desktop\sideProject\flutter\test_app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +87 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +603 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +63 ms] executing: [C:\Users\azrir\Desktop\sideProject\flutter\test_app\android/]
C:\Users\azrir\Desktop\sideProject\flutter\test_app\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\azrir\Desktop\sideProject\flutter\test_app\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root        
assembleDebug
[+1201629 ms] FAILURE: Build failed with an exception.
[ +272 ms] * What went wrong:
[   +6 ms] A problem occurred configuring root project 'android'.
[   +1 ms] > Could not resolve all artifacts for configuration ':classpath'.
[   +2 ms]    > Could not download kotlin-compiler-embeddable.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50)
[   +1 ms]       > Could not get resource
'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.50/kotlin-compiler-embeddable-1.3.50.jar'.
[  +44 ms]          > Could not GET
'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.50/kotlin-compiler-embeddable-1.3.50.jar'.
[   +6 ms]             > jcenter.bintray.com
[   +1 ms]    > Could not download httpcore.jar (org.apache.httpcomponents:httpcore:4.4.10)
[   +8 ms]       > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar'.
[   +9 ms]          > Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar'.
[  +16 ms]             > jcenter.bintray.com
[   +8 ms]    > Could not download antlr4.jar (org.antlr:antlr4:4.5.3)
[   +1 ms]       > Could not get resource 'https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'.
[   +1 ms]          > Could not GET 'https://jcenter.bintray.com/org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'.      
[   +1 ms]             > jcenter.bintray.com
[   +5 ms]    > Could not download commons-io.jar (commons-io:commons-io:2.4)
[   +4 ms]       > Could not get resource 'https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4.jar'.
[  +19 ms]          > Could not GET 'https://jcenter.bintray.com/commons-io/commons-io/2.4/commons-io-2.4.jar'.
[ +103 ms]             > jcenter.bintray.com
[   +2 ms]    > Could not download juniversalchardet.jar (com.googlecode.juniversalchardet:juniversalchardet:1.0.3)
[   +2 ms]       > Could not get resource
'https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar'.
[   +8 ms]          > Could not GET
'https://jcenter.bintray.com/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar'.
[  +10 ms]             > jcenter.bintray.com
[   +5 ms]    > Could not download javapoet.jar (com.squareup:javapoet:1.8.0)
[   +2 ms]       > Could not get resource 'https://jcenter.bintray.com/com/squareup/javapoet/1.8.0/javapoet-1.8.0.jar'.
[  +13 ms]          > Could not GET 'https://jcenter.bintray.com/com/squareup/javapoet/1.8.0/javapoet-1.8.0.jar'.
[   +2 ms]             > jcenter.bintray.com
[   +6 ms]    > Could not download proguard-base.jar (net.sf.proguard:proguard-base:6.0.3)
[   +7 ms]       > Could not get resource 'https://jcenter.bintray.com/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.jar'.
[   +5 ms]          > Could not GET 'https://jcenter.bintray.com/net/sf/proguard/proguard-base/6.0.3/proguard-base-6.0.3.jar'.
[   +5 ms]             > jcenter.bintray.com
[   +8 ms]    > Could not download auto-value.jar (com.google.auto.value:auto-value:1.5.2)
[   +4 ms]       > Could not get resource 'https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar'.
[   +3 ms]          > Could not GET 'https://jcenter.bintray.com/com/google/auto/value/auto-value/1.5.2/auto-value-1.5.2.jar'.
[   +4 ms]             > jcenter.bintray.com
[   +4 ms]    > Could not download error_prone_annotations.jar (com.google.errorprone:error_prone_annotations:2.3.1)
[   +4 ms]       > Could not get resource
'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.3.1/error_prone_annotations-2.3.1.jar'.
[   +9 ms]          > Could not GET
'https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.3.1/error_prone_annotations-2.3.1.jar'.
[ +482 ms]             > jcenter.bintray.com
[  +70 ms]    > Could not download jdom2.jar (org.jdom:jdom2:2.0.6)
[ +152 ms]       > Could not get resource 'https://jcenter.bintray.com/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar'.
[  +69 ms]          > Could not GET 'https://jcenter.bintray.com/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar'.
[ +143 ms]             > jcenter.bintray.com
[+1609 ms]    > Could not download kotlin-script-runtime.jar (org.jetbrains.kotlin:kotlin-script-runtime:1.3.50)
[  +10 ms]       > Could not get resource
'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-script-runtime/1.3.50/kotlin-script-runtime-1.3.50.jar'.
[  +93 ms]          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-script-runtime/1.3.50/kotlin-script-runtime-1.3.50.jar'.[ +110 ms]             > jcenter.bintray.com
[ +409 ms]    > Could not download kotlin-daemon-embeddable.jar (org.jetbrains.kotlin:kotlin-daemon-embeddable:1.3.50)
[  +16 ms]       > Could not get resource
'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-daemon-embeddable/1.3.50/kotlin-daemon-embeddable-1.3.50.jar'.
[ +107 ms]          > Could not GET
'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-daemon-embeddable/1.3.50/kotlin-daemon-embeddable-1.3.50.jar'.
[ +129 ms]             > jcenter.bintray.com
[   +4 ms]    > Could not download trove4j.jar (org.jetbrains.intellij.deps:trove4j:1.0.20181211)
[   +4 ms]       > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.jar'.
[ +167 ms]          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/intellij/deps/trove4j/1.0.20181211/trove4j-1.0.20181211.jar'.
[ +117 ms]             > jcenter.bintray.com
[  +23 ms]    > Could not download kotlin-build-common.jar (org.jetbrains.kotlin:kotlin-build-common:1.3.50)
[  +70 ms]       > Could not get resource
'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.3.50/kotlin-build-common-1.3.50.jar'.
[  +83 ms]          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.3.50/kotlin-build-common-1.3.50.jar'.
[  +87 ms]             > jcenter.bintray.com
[  +68 ms]    > Could not download kotlinx-coroutines-core.jar (org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1)
[  +75 ms]       > Could not get resource
'https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.jar'.
[   +3 ms]          > Could not GET
'https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.jar'.
[ +246 ms]             > jcenter.bintray.com
[   +5 ms]    > Could not download kotlin-stdlib-common.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50)
[  +69 ms]       > Could not get resource
'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50/kotlin-stdlib-common-1.3.50.jar'.
[  +73 ms]          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50/kotlin-stdlib-common-1.3.50.jar'.
[   +3 ms]             > jcenter.bintray.com
[   +3 ms]    > Could not download annotations.jar (org.jetbrains:annotations:13.0)
[ +237 ms]       > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.jar'.
[   +3 ms]          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/annotations/13.0/annotations-13.0.jar'.
[   +3 ms]             > jcenter.bintray.com
[   +2 ms]    > Could not download commons-compress.jar (org.apache.commons:commons-compress:1.12)
[  +70 ms]       > Could not get resource 'https://jcenter.bintray.com/org/apache/commons/commons-compress/1.12/commons-compress-1.12.jar'.
[  +69 ms]          > Could not GET 'https://jcenter.bintray.com/org/apache/commons/commons-compress/1.12/commons-compress-1.12.jar'.
[   +3 ms]             > jcenter.bintray.com
[   +2 ms]    > Could not download trove4j.jar (org.jetbrains.trove4j:trove4j:20160824)
[   +2 ms]       > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.jar'.
[   +3 ms]          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.jar'.
[  +75 ms]             > jcenter.bintray.com
[   +4 ms]    > Could not download kxml2.jar (net.sf.kxml:kxml2:2.3.0)
[ +112 ms]       > Could not get resource 'https://jcenter.bintray.com/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.jar'.
[   +2 ms]          > Could not GET 'https://jcenter.bintray.com/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.jar'.
[   +2 ms]             > jcenter.bintray.com
[  +85 ms]    > Could not download jsr305.jar (com.google.code.findbugs:jsr305:3.0.2)
[  +81 ms]       > Could not get resource 'https://jcenter.bintray.com/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar'.
[  +70 ms]          > Could not GET 'https://jcenter.bintray.com/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar'.
[  +67 ms]             > jcenter.bintray.com
[  +68 ms]    > Could not download failureaccess.jar (com.google.guava:failureaccess:1.0.1)
[ +145 ms]       > Could not get resource 'https://jcenter.bintray.com/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar'.
[  +76 ms]          > Could not GET 'https://jcenter.bintray.com/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar'.
[   +2 ms]             > jcenter.bintray.com
[   +2 ms]    > Could not download listenablefuture.jar (com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava)
[  +73 ms]       > Could not get resource
'https://jcenter.bintray.com/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar'.
[   +6 ms]          > Could not GET
'https://jcenter.bintray.com/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar'.
[  +39 ms]             > jcenter.bintray.com
[  +42 ms]    > Could not download checker-qual.jar (org.checkerframework:checker-qual:2.5.2)
[   +2 ms]       > Could not get resource 'https://jcenter.bintray.com/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar'.
[   +2 ms]          > Could not GET 'https://jcenter.bintray.com/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar'.
[   +2 ms]             > jcenter.bintray.com
[ +144 ms]    > Could not download j2objc-annotations.jar (com.google.j2objc:j2objc-annotations:1.1)
[   +2 ms]       > Could not get resource 'https://jcenter.bintray.com/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar'.
[   +7 ms]          > Could not GET 'https://jcenter.bintray.com/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar'.
[  +73 ms]             > jcenter.bintray.com
[   +2 ms]    > Could not download animal-sniffer-annotations.jar (org.codehaus.mojo:animal-sniffer-annotations:1.17)
[   +2 ms]       > Could not get resource
'https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar'.
[  +70 ms]          > Could not GET
'https://jcenter.bintray.com/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar'.
[ +615 ms]             > jcenter.bintray.com
[  +56 ms]    > Could not download commons-logging.jar (commons-logging:commons-logging:1.2)
[+3024 ms]       > Could not get resource 'https://jcenter.bintray.com/commons-logging/commons-logging/1.2/commons-logging-1.2.jar'.
[ +695 ms]          > Could not GET 'https://jcenter.bintray.com/commons-logging/commons-logging/1.2/commons-logging-1.2.jar'.
[ +129 ms]             > jcenter.bintray.com
[  +16 ms]    > Could not download commons-codec.jar (commons-codec:commons-codec:1.10)
[   +2 ms]       > Could not get resource 'https://jcenter.bintray.com/commons-codec/commons-codec/1.10/commons-codec-1.10.jar'.
[   +2 ms]          > Could not GET 'https://jcenter.bintray.com/commons-codec/commons-codec/1.10/commons-codec-1.10.jar'.
[   +3 ms]             > jcenter.bintray.com
[   +3 ms]    > Could not download javax.activation.jar (com.sun.activation:javax.activation:1.2.0)
[ +678 ms]       > Could not get resource 'https://jcenter.bintray.com/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar'.
[ +124 ms]          > Could not GET 'https://jcenter.bintray.com/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar'.
[  +82 ms]             > jcenter.bintray.com
[   +3 ms]    > Could not download jaxb-runtime.jar (org.glassfish.jaxb:jaxb-runtime:2.2.11)
[ +105 ms]       > Could not get resource 'https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.jar'.
[   +3 ms]          > Could not GET 'https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.jar'.
[  +83 ms]             > jcenter.bintray.com
[  +97 ms]    > Could not download jaxb-core.jar (org.glassfish.jaxb:jaxb-core:2.2.11)
[ +164 ms]       > Could not get resource 'https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-core/2.2.11/jaxb-core-2.2.11.jar'.
[   +3 ms]          > Could not GET 'https://jcenter.bintray.com/org/glassfish/jaxb/jaxb-core/2.2.11/jaxb-core-2.2.11.jar'.
[ +131 ms]             > jcenter.bintray.com
[ +166 ms]    > Could not download stax-ex.jar (org.jvnet.staxex:stax-ex:1.7.7)
[   +4 ms]       > Could not get resource 'https://jcenter.bintray.com/org/jvnet/staxex/stax-ex/1.7.7/stax-ex-1.7.7.jar'.
[ +340 ms]          > Could not GET 'https://jcenter.bintray.com/org/jvnet/staxex/stax-ex/1.7.7/stax-ex-1.7.7.jar'.
[  +87 ms]             > jcenter.bintray.com
[   +4 ms]    > Could not download FastInfoset.jar (com.sun.xml.fastinfoset:FastInfoset:1.2.13)
[  +81 ms]       > Could not get resource 'https://jcenter.bintray.com/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.jar'.
[  +98 ms]          > Could not GET 'https://jcenter.bintray.com/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.jar'.
[   +2 ms]             > jcenter.bintray.com
[   +2 ms]    > Could not download jaxb-api.jar (javax.xml.bind:jaxb-api:2.2.12-b140109.1041)
[  +82 ms]       > Could not get resource 'https://jcenter.bintray.com/javax/xml/bind/jaxb-api/2.2.12-b140109.1041/jaxb-api-2.2.12-b140109.1041.jar'.[  +78 ms]          > Could not GET 'https://jcenter.bintray.com/javax/xml/bind/jaxb-api/2.2.12-b140109.1041/jaxb-api-2.2.12-b140109.1041.jar'.
[   +5 ms]             > jcenter.bintray.com
[ +206 ms]    > Could not download txw2.jar (org.glassfish.jaxb:txw2:2.2.11)
[  +21 ms]       > Could not get resource 'https://jcenter.bintray.com/org/glassfish/jaxb/txw2/2.2.11/txw2-2.2.11.jar'.
[ +179 ms]          > Could not GET 'https://jcenter.bintray.com/org/glassfish/jaxb/txw2/2.2.11/txw2-2.2.11.jar'.
[ +123 ms]             > jcenter.bintray.com
[   +3 ms]    > Could not download istack-commons-runtime.jar (com.sun.istack:istack-commons-runtime:2.21)
[  +76 ms]       > Could not get resource 'https://jcenter.bintray.com/com/sun/istack/istack-commons-runtime/2.21/istack-commons-runtime-2.21.jar'.
[   +2 ms]          > Could not GET 'https://jcenter.bintray.com/com/sun/istack/istack-commons-runtime/2.21/istack-commons-runtime-2.21.jar'.        
[   +3 ms]             > jcenter.bintray.com
[ +179 ms] * Try:
[  +37 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get fullinsights.
[ +361 ms] * Get more help at https://help.gradle.org
[ +138 ms] BUILD FAILED in 20m 0s
[ +105 ms] Running Gradle task 'assembleDebug'... (completed in 1217.7s, longer than expected)
[ +156 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +44 ms] "flutter run" took 1,223,213ms.
[ +124 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
                    #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
                    <asynchronous suspension>
                    #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
                    <asynchronous suspension>
                    #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
                    <asynchronous suspension>
                    #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
                    #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
                    #6      _rootRun (dart:async/zone.dart:1190:13)
                    #7      _CustomZone.run (dart:async/zone.dart:1093:19)
                    #8      _runZoned (dart:async/zone.dart:1630:10)
                    #9      runZoned (dart:async/zone.dart:1550:10)
                    #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
                    #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
                    #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
                    #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)                    #14     _rootRunUnary (dart:async/zone.dart:1198:47)
                    #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                    #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                    #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
                    #23     _rootRunUnary (dart:async/zone.dart:1198:47)
                    #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
                    #30     _rootRun (dart:async/zone.dart:1190:13)
                    #31     _CustomZone.run (dart:async/zone.dart:1093:19)
                    #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
                    #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
                    #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
                    #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
                    #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
                    #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +651 ms] Running shutdown hooks
[   +8 ms] Shutdown hook priority 4
[  +10 ms] Shutdown hooks complete
[ +164 ms] exiting with code 1
``` 

</details>

**Comment by TahaTesser** [comment]
Hi @Azri99 
Looks like you're having issues with android packages, please switch to a different, make sure you internet connection isn't provide network. 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and `build.gradle` from `<flutter app>/android/.gradle`
Thank you

**Comment by Azri99** [comment]
Thank you for you help.And yeah apparently I put the flutter sdk at the place where they need administrator permission. After changing those location to a new one. It seems to be running just find
