### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by jabedbd** [flutter/flutter#63511]
## Command
```
flutter --quiet assemble --depfile D:\PG Development\pg user\build\app\intermediates\flutter\debug/flutter_build.d --output D:\PG Development\pg user\build\app\intermediates\flutter\debug -dTargetFile=D:\PG Development\pg user\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#2      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#3      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#4      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#5      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#6      _File.createSync (dart:io/file_impl.dart:270:14)
#7      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#8      FileStore.persist (package:flutter_tools/src/build_system/file_store.dart:158:18)
#9      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:17)
<asynchronous suspension>
#10     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _runZoned (dart:async/zone.dart:1630:10)
#18     runZoned (dart:async/zone.dart:1550:10)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
```
```
[✓] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Jabed\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Jabed\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\Jabed\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by Abhishek01039** [comment]
First of all, Accept the Android license.
can you please provide flutter run -v and minimal reproduction code.
Thank you

**Comment by darshankawar** [comment]
Hi @jabedbd,
There's similar open issue describing your case, [60272](https://github.com/flutter/flutter/issues/60272).
Please follow-up there for updates and questions.
Closing this as duplicate.
