### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/akili/Library/Android/sdk/build-tools/29.0.3/aapt.

### ISSUE THREAD

**Issue by akiligedeon** [flutter/flutter#63557]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/akili/Library/Android/sdk/build-tools/29.0.3/aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:409:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:361:31)
#8      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:518:23)
#9      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:580:26)
#10     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:578:38)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
#13     _rootRun (dart:async/zone.dart:1184:13)
#14     _CustomZone.run (dart:async/zone.dart:1077:19)
#15     _runZoned (dart:async/zone.dart:1619:10)
#16     runZoned (dart:async/zone.dart:1539:10)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15 19A583, locale en-UG)
    • Flutter version 1.17.5 at /Users/akili/Desktop/flutter
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/akili/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    ✗ Android SDK file not found: /Users/akili/Library/Android/sdk/build-tools/29.0.3/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 83d4d63a716ec8551f0d59f852a40925ddd73d8a
### Plugins
audioplayers-0.15.1
barcode_scan-3.0.1
cloud_firestore-0.13.5
cloud_firestore_web-0.1.1+2
file_picker-1.4.3+1
firebase_auth-0.15.5+3
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_dynamic_links-0.5.1
firebase_messaging-6.0.16
firebase_storage-3.1.5
flutter_local_notifications-1.4.4+2
flutter_plugin_android_lifecycle-1.0.7
flutter_rounded_progress_bar-0.1.2
geocoder-0.2.1
geoflutterfire-2.1.0
geolocator-5.3.1
google_api_availability-2.0.4
google_maps_flutter-0.5.27+1
google_sign_in-4.4.4
google_sign_in_web-0.9.1
image_picker-0.6.6+1
location-3.0.2
location_permissions-2.0.5
location_web-1.0.0
multi_image_picker-4.7.10
path_provider-1.6.8
path_provider_macos-0.0.4+2
permission_handler-5.0.1+1
shared_preferences-0.5.7+1
shared_preferences_macos-0.0.1+8
shared_preferences_web-0.1.2+5
sqflite-1.3.0+1

**Comment by darshankawar** [comment]
Hi @akiligedeon,
There's similar open issue describing your case, [58662](https://github.com/flutter/flutter/issues/58662).
Please follow-up there for updates.
Closing this as duplicate.
