### ISSUE TITLE
Hero widget causes exception when navigating with a form key

### ISSUE THREAD

**Issue by NiamhG** [flutter/flutter#63565]
Running the below steps results in an exception only when using a hero widget. If you remove the hero widget, everything works as expected and there are no exceptions. 

## Steps to Reproduce

Testing on a real android device.

1. Run the below code
2. Press "Navigate" button
3. Press back button
4. Press "Navigate" button
5. Exception is thrown

```
import 'package:flutter/material.dart';

const heroKey = "heroKey";

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Column(
          children: [
            const Hero(
              tag: heroKey,
              child: Text("1"),
            ),
            RaisedButton(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute<void>(
                    builder: (context) {
                      return SecondScreen();
                    },
                  ),
                );
              },
              child: const Text("Navigate"),
            ),
          ],
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: Scaffold(
      body: _Pages(),
    ));
  }
}

class _Pages extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PageView(children: [_Page()]);
  }
}

class _Page extends StatelessWidget {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Hero(
      tag: heroKey,
      child: Form(
        key: _formKey,
        child: Center(child: Text("1")),
      ),
    );
  }
}
```

**Expected results:** 

No exception

**Actual results:**

Exception is thrown:

```
The relevant error-causing widget was: 
  Form-[LabeledGlobalKey<FormState>#82b4c] file:///A:/Documents/lib/test.dart:60:14
When the exception was thrown, this was the stack: 
#2      _WillPopScopeState.didUpdateWidget (package:flutter/src/widgets/will_pop_scope.dart:61:12)
#3      StatefulElement.update (package:flutter/src/widgets/framework.dart:4734:58)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
```

Strangely, if you have  _Page() instead of _Pages() in SecondScreen, the exception happens the first time you navigate instead of the second. 

Not entirely sure what's going on here? I don't believe I'm doing anything too silly.

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.1016], locale en-GB)
    • Flutter version 1.20.1 at A:\src\flutter
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at A:\AppData\Android
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = A:\AppData\Android
    • Java binary at: A:\Programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at A:\Programs\Android\Android Studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • CLT L09 (mobile) • LCL7N18B30006401 • android-arm64 • Android 10 (API 29)

```

</details>

**Comment by darshankawar** [comment]
Hi @NiamhG,
It seems `WillPopScope` expects immediate disposal of modal route in combination with Hero widget, but that's not happening at the moment.
I see there's similar open issue describing your case, [49952](https://github.com/flutter/flutter/issues/49952).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by NiamhG** [comment]
Ah, yes that seems to be the same. Thanks.
