### ISSUE TITLE
Crash after upgrade to the latest master version (1.20.1)

### ISSUE THREAD

**Issue by tiagoantunes** [flutter/flutter#63579]
## Steps to Reproduce

1. I was previously running the flutter version 1.17.5 without problems
2. I Ran the `flutter upgrade` to get the new stable version.
3. And I got the following error log,

## Logs

```
    ~/Workspace/FlutterProjects/flutter-sdk/flutter    master                                                16:45:36 
❯ flutter channel master
Building flutter tool...
Crash when compiling file://users/tiagoantunes/Workspace/FlutterProjects/flutter-sdk/flutter/packages/flutter_tools/bin/flutter_tools.dart,
at character offset null:
Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      _Uri._toFilePath (dart:core/uri.dart:2725:7)
#1      _Uri.toFilePath (dart:core/uri.dart:2720:65)
#2      _IoFileSystemEntity.exists (package:front_end/src/api_prototype/standard_file_system.dart:55:51)
#3      HybridFileSystemEntity.exists (package:front_end/src/fasta/hybrid_file_system.dart:51:51)
<asynchronous suspension>
#4      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:506:47)
#5      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:531:32)
#6      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:596:17)
#7      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:472:32)
#8      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:426:38)
<asynchronous suspension>
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:74:49)
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:223:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _runZoned (dart:async/zone.dart:1630:10)
#21     runZoned (dart:async/zone.dart:1550:10)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#25     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#26     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#27     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#28     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#29     _rootRun (dart:async/zone.dart:1182:47)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _rootRun (dart:async/zone.dart:1190:13)
#34     _CustomZone.run (dart:async/zone.dart:1093:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      _Uri._toFilePath (dart:core/uri.dart:2725:7)
#1      _Uri.toFilePath (dart:core/uri.dart:2720:65)
#2      _IoFileSystemEntity.exists (package:front_end/src/api_prototype/standard_file_system.dart:55:51)
#3      HybridFileSystemEntity.exists (package:front_end/src/fasta/hybrid_file_system.dart:51:51)
<asynchronous suspension>
#4      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:506:47)
#5      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:531:32)
#6      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:596:17)
#7      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:472:32)
#8      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:426:38)
<asynchronous suspension>
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:74:49)
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:223:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _runZoned (dart:async/zone.dart:1630:10)
#21     runZoned (dart:async/zone.dart:1550:10)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#25     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#26     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#27     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#28     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#29     _rootRun (dart:async/zone.dart:1182:47)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _rootRun (dart:async/zone.dart:1190:13)
#34     _CustomZone.run (dart:async/zone.dart:1093:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

```
flutter doctor -v
Building flutter tool...
Crash when compiling file://users/tiagoantunes/Workspace/FlutterProjects/flutter-sdk/flutter/packages/flutter_tools/bin/flutter_tools.dart,
at character offset null:
Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      _Uri._toFilePath (dart:core/uri.dart:2725:7)
#1      _Uri.toFilePath (dart:core/uri.dart:2720:65)
#2      _IoFileSystemEntity.exists (package:front_end/src/api_prototype/standard_file_system.dart:55:51)
#3      HybridFileSystemEntity.exists (package:front_end/src/fasta/hybrid_file_system.dart:51:51)
<asynchronous suspension>
#4      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:506:47)
#5      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:531:32)
#6      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:596:17)
#7      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:472:32)
#8      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:426:38)
<asynchronous suspension>
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:74:49)
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:223:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _runZoned (dart:async/zone.dart:1630:10)
#21     runZoned (dart:async/zone.dart:1550:10)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#25     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#26     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#27     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#28     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#29     _rootRun (dart:async/zone.dart:1182:47)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _rootRun (dart:async/zone.dart:1190:13)
#34     _CustomZone.run (dart:async/zone.dart:1093:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      _Uri._toFilePath (dart:core/uri.dart:2725:7)
#1      _Uri.toFilePath (dart:core/uri.dart:2720:65)
#2      _IoFileSystemEntity.exists (package:front_end/src/api_prototype/standard_file_system.dart:55:51)
#3      HybridFileSystemEntity.exists (package:front_end/src/fasta/hybrid_file_system.dart:51:51)
<asynchronous suspension>
#4      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:506:47)
#5      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:531:32)
#6      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:596:17)
#7      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:472:32)
#8      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:426:38)
<asynchronous suspension>
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:74:49)
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#12     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:223:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _runZoned (dart:async/zone.dart:1630:10)
#21     runZoned (dart:async/zone.dart:1550:10)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#25     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#26     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#27     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#28     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#29     _rootRun (dart:async/zone.dart:1182:47)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _rootRun (dart:async/zone.dart:1190:13)
#34     _CustomZone.run (dart:async/zone.dart:1093:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by TahaTesser** [comment]
Hi @tiagoantunes 
Just tired to upgrade from 1.17.5 to 1.20.1
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.17.5 at C:\Code\flutter_play
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
                                                                                                                        [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)                                            • Android SDK at C:\Code\sdk                                                                                            • Platform android-30, build-tools 30.0.1                                                                               • ANDROID_HOME = C:\Code\sdk                                                                                            • Java binary at: C:\Code\android-studio\jre\bin\java                                                                   • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)                                           • All Android licenses accepted.
[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2
[!] Connected device
    ! No devices available
! Doctor found issues in 1 category.
```

```
pgrading Flutter from C:\Code\flutter_play...
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine c8e3b9485386425213e2973126d6f57e7ed83c54...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Upgrading engine...
Downloading Android Maven dependencies...                          12.8s
Downloading android-arm-profile/windows-x64 tools...                0.9s
Downloading android-arm-release/windows-x64 tools...                0.4s
Downloading android-arm64-profile/windows-x64 tools...              0.6s
Downloading android-arm64-release/windows-x64 tools...              0.5s
Downloading android-x64-profile/windows-x64 tools...                0.5s
Downloading android-x64-release/windows-x64 tools...                0.6s
Downloading android-x86 tools...                                    2.6s
Downloading android-x64 tools...                                    3.5s
Downloading android-arm tools...                                    1.7s
Downloading android-arm-profile tools...                            0.9s
Downloading android-arm-release tools...                            0.7s
Downloading android-arm64 tools...                                  1.6s
Downloading android-arm64-profile tools...                          0.7s
Downloading android-arm64-release tools...                          0.9s
Downloading android-x64-profile tools...                            0.7s
Downloading android-x64-release tools...                            0.6s
Downloading android-x86-jit-release tools...                        0.9s
Downloading package sky_engine...                                   0.7s
Downloading flutter_patched_sdk tools...                            1.9s
Downloading flutter_patched_sdk_product tools...                    1.8s
Downloading windows-x64 tools...                                    3.3s
Downloading windows-x64/font-subset tools...                        0.9s
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (7 days ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[!] Connected device
    ! No devices available
! Doctor found issues in 1 category.
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝
PS C:\Users\Taha>
```

```
[✓] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.20.1 at C:\Code\flutter_play
    • Framework revision 2ae34518b8 (7 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.47.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2
[!] Connected device
    ! No devices available
! Doctor found issues in 1 category.
```

Could it be because of this weird path `Workspace/FlutterProjects/flutter-sdk/flutter    master   ` from your logs?

**Comment by TahaTesser** [comment]
I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by jmagman** [comment]
URI parsing didn't like `file://users/tiagoantunes/Workspace/FlutterProjects/flutter-sdk/flutter/packages/flutter_tools/bin/flutter_tools.dart`?

**Comment by tiagoantunes** [comment]
@jmagman If helps, I share my work path of the corresponding file.
<img width="1114" alt="Screenshot 2020-08-25 at 11 50 41" src="https://user-images.githubusercontent.com/6808483/91165796-36c64580-e6c9-11ea-96cd-457d2f43c9d5.png">

**Comment by Hixie** [comment]
We probably need to add some code that catches this error and prints more diagnostics to help us track down what's happening. Maybe there's some non-ASCII character in the path or maybe it's a different path we're trying to parse or something?

**Comment by johnniwinther** [comment]
@Hixie I've created https://dart-review.googlesource.com/c/sdk/+/160281 to help with this in the future.

For this error case, the error occurs when trying to determine whether the package config file is a directory. The package, either provided directly or pulled from `Platform.packageConfig`, ends with `/.packages` and we try to determine whether `/.dart_tool/package_config.json` exists. So if the given package config argument is `scheme://authority/foo/bar/.packages` we are trying to read `scheme://authority/foo/bar/.dart_tool/package_config.json`, and it's the `authority` part (like `localhost:8080`) that it crashes on. 

I can reproduce the crash locally (with a bit of hackering since I'm on Windows where the authority part _is_ allowed) by invoking 
```
dart --packages=file://localhost:8080/.packages temp\abc.dart
```

I don't know who sets the package config for this use case, but from the Dart front-end perspective we are not doing any other processing of the provided Uri than what is described above, and there has been no changes to this part of the front-end lately, so the change in behavior is likely in the tools that call the vm/compiler.

**Comment by mkustermann** [comment]
Isn't the issue here a missing forward slash in the local file uri? Instead of `file://users/tiagoantunes/...` it should say `file:///users/tiagoantunes/...`

When trying to convert the given uri to a file path it will throw this exception:
```dart
main() {
  print(Uri.parse(r'file://foo/bar').toFilePath());  // <-- Should use file:/// instead of file://
}
```
```
% dart test.dart
Unhandled exception:
Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      _SimpleUri._toFilePath (dart:core/uri.dart:4724:7)
#1      _SimpleUri.toFilePath (dart:core/uri.dart:4718:54)
#2      main (file:///.../test.dart:2:38)
```

**Comment by lambdaR** [comment]
Hi, I had the same problem on Ubuntu LTS 20.04.1
interesting though, when you run `which flutter dart` command the result came with an extra forward slash like this
```
//path-to-flutter-sdk/bin/flutter
//path-to-flutter-sdk/bin/dart
```
it should be 
```
/path-to-flutter-sdk/bin/flutter
/path-to-flutter-sdk/bin/dart
```
i used `zsh` to add flutter tools to `PATH` ... and i solved it by switching back to `bash ` added flutter tools again to `PATH` then run `source .bashrc`

**Comment by moda20** [comment]
I switched to the master channel of flutter in order to get the macOs building possibility and now I am stuck with this error. is there a temporary fix so that I can build the flutter tools?

**Comment by izzyaf** [comment]
This works for me. Go into `flutter_tools` folder and run:
```
../../bin/flutter --version
```

**Comment by Kaival-Patel** [comment]
Resolved the issue by renaming the folder from Uppercase to lowercase name (mine was Flutter)
