### ISSUE TITLE
Attempted to register plugin  but it was already registered

### ISSUE THREAD

**Issue by sc00n** [flutter/flutter#63614]
When I use

```
package com.example.flutterapp2;

import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;
import androidx.annotation.NonNull;

public class MainActivity extends FlutterActivity {

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

as MainActivity.java, (such as for example in https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects, or https://github.com/flutter/flutter/issues/58347)

I get the following error:

```
Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@d4ac178) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@a972051).
E/AndroidRuntime(20658): FATAL EXCEPTION: main
E/AndroidRuntime(20658): Process: io.m_Path.kuleuven, PID: 20658
E/AndroidRuntime(20658): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.m_Path.kuleuven/com.example.flutterapp2.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(20658): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
E/AndroidRuntime(20658): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/AndroidRuntime(20658): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(20658): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(20658): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(20658): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(20658): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20658): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(20658): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(20658): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20658): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(20658): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(20658): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(20658): 	at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
E/AndroidRuntime(20658): 	at xyz.luan.audioplayers.AudioplayersPlugin.<init>(AudioplayersPlugin.java:36)
E/AndroidRuntime(20658): 	at xyz.luan.audioplayers.AudioplayersPlugin.registerWith(AudioplayersPlugin.java:31)
E/AndroidRuntime(20658): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:18)
E/AndroidRuntime(20658): 	at com.example.flutterapp2.MainActivity.configureFlutterEngine(MainActivity.java:20)
E/AndroidRuntime(20658): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(20658): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:411)
E/AndroidRuntime(20658): 	at android.app.Activity.performCreate(Activity.java:7136)
E/AndroidRuntime(20658): 	at android.app.Activity.performCreate(Activity.java:7127)
E/AndroidRuntime(20658): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/AndroidRuntime(20658): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
E/AndroidRuntime(20658): 	... 11 more
```

The problematic line is 
``` 
GeneratedPluginRegistrant.registerWith(flutterEngine);
```

Without that line everything works.

flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.388], locale nl-BE)
    • Flutter version 1.20.1 at C:\src\flutter\flutter
    • Framework revision 2ae34518b8 (7 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\u0084978\AppData\Local\Android\sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

In my AndroidManifest I use
```
    <meta-data
        android:name="flutterEmbedding"
        android:value="2" />
```

I have no idea on what the problem could be.

Thank you for your help,

sc00n

**Comment by inceptusp** [comment]
You don't need this line anymore... `super.configureFlutterEngine(flutterEngine);` already do this job for you... It already calls the necessary functions to register plugins, if you call `GeneratedPluginRegistrant.registerWith(flutterEngine);` "again" it will produce this error...

**Comment by TahaTesser** [comment]
Hi @sc00n 
Looks like you're calling register twice, please check https://github.com/flutter/flutter/issues/63614#issuecomment-673348366, thanks @inceptusp 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by sc00n** [comment]
removing it worked fine 👍
