### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Developer/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: /usr/bin/xcodebuild, OS error code: 74

### ISSUE THREAD

**Issue by harzancs** [flutter/flutter#63632]
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Developer/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: /usr/bin/xcodebuild, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:323:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:381:50)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:122:78)
<asynchronous suspension>
#4      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:93:43)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#13     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#22     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
```
```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale th-TH)
    • Flutter version 1.20.1 at /Users/apple/Development/flutter
    • Framework revision 2ae34518b8 (7 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Developer/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0.beta.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 285F4671-6269-4AFC-87C3-7702BB79288B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
flutter_facebook_login-79ff08a06e9aa38f4cce82bd5294a563f0884e79
flutter_line_sdk-0701f0575054ea53947d29617e33f7ff630dde13

**Comment by darshankawar** [comment]
Hi @harzancs,
There's similar open issue describing your case, [57083](https://github.com/flutter/flutter/issues/57083).
Please follow-up there for updates and questions.
Closing this as duplicate.
