### ISSUE TITLE
Cant run and build my flutter apps because, Execution failed for ':app:mergeDebugNativeLibs'.

### ISSUE THREAD

**Issue by eerbee** [flutter/flutter#63648]
## Steps to Reproduce

I just finished my code and wanna to run it but i got these error, i dont know what happen and took many hours to figure out but i ended to make this issue, so what i've done is try to flutter clean, flutter cache repair, flutter upgrade, flutter pub get etc, try reinstall vs code, re install flutter sdk, clean my laptop chache with CCleaner even i try to open my old flutter project to make sure didn't get this error either but it got the error too, pls help 

 
[The Error] :
**FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.util.zip.ZipException: invalid stored block lengths**

<details>
  <summary>Logs</summary>

```
[ +180 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +113 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[  +16 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +387 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.20.1
[  +16 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +88 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +73 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +147 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +112 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +49 ms] executing: C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +138 ms] List of devices attached
                    RR8M90HZZ9N            device product:a50sxx model:SM_A507FN device:a50s transport_id:3
                    emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
                    transport_id:2
[  +24 ms] C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s RR8M90HZZ9N shell getprop
[ +131 ms] C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +65 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +25 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +123 ms] Multiple devices found:
[   +8 ms] ro.hardware = exynos9611
[        ] ro.build.characteristics = phone
[   +2 ms] ro.hardware = ranchu
[   +5 ms] SM A507FN (mobile)                 • RR8M90HZZ9N   • android-arm64 • Android 10 (API 29)
[  +24 ms] Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 6.0 (API 23) (emulator)
[   +7 ms] [0]: SM A507FN (RR8M90HZZ9N)
[  +69 ms] [1]: Android SDK built for x86 (emulator-5554)
[   +5 ms] Please choose one:
[   +1 ms]  [0|1]
[   +1 ms] : 
[+2641 ms] 1
[ +219 ms] Generating D:\Dataku\Universitas Brawijaya\Non - Akademik\Dicoding\Hybrid or Multiplatform Programming\Flutter\Codelab
3\wisata_bandung\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +80 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software
rendering with
           "--enable-software-rendering".
[  +66 ms] Starting incremental build...
[   +6 ms] Initializing file store
[  +18 ms] Skipping target: gen_localizations
[  +29 ms] complete
[  +13 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +17 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Asus\AppData\Local\Temp\flutter_tools.490f683b\flutter_tool.490113dd\app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill   
[  +38 ms] executing: C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +57 ms] Exit code 0 from: C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           08-13 16:49:07.580 I/Vision  ( 2528): Checking for download completion for 720418 -- ocr
[   +2 ms] executing: C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +76 ms] Exit code 0 from: C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           08-13 16:49:07.580 I/Vision  ( 2528): Checking for download completion for 720418 -- ocr
[  +29 ms] <- compile package:wisata_bandung/main.dart
[  +19 ms] executing: C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +184 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.4-6686687
                    Installed as C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +20 ms] executing: C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +90 ms] Building APK
[  +46 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[  +61 ms] Using gradle from D:\Dataku\Universitas Brawijaya\Non - Akademik\Dicoding\Hybrid or Multiplatform Programming\Flutter\Codelab
3\wisata_bandung\android\gradlew.bat.
[  +55 ms] D:\Dataku\Universitas Brawijaya\Non - Akademik\Dicoding\Hybrid or Multiplatform Programming\Flutter\Codelab
3\wisata_bandung\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +37 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +208 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +32 ms] executing: [D:\Dataku\Universitas Brawijaya\Non - Akademik\Dicoding\Hybrid or Multiplatform Programming\Flutter\Codelab
3\wisata_bandung\android/] D:\Dataku\Universitas Brawijaya\Non - Akademik\Dicoding\Hybrid or Multiplatform Programming\Flutter\Codelab      
3\wisata_bandung\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=D:\Dataku\Universitas Brawijaya\Non -
Akademik\Dicoding\Hybrid or Multiplatform Programming\Flutter\Codelab 3\wisata_bandung\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+6733 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [ +251 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +257 ms] [ +263 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +1 ms] [   +1 ms] executing: [C:\flutter/] git tag --contains HEAD
[ +499 ms] [ +571 ms] Exit code 0 from: git tag --contains HEAD
[  +32 ms] [        ] 1.20.1
[  +20 ms] [  +19 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +142 ms] [ +176 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +15 ms] [        ] origin/stable
[  +32 ms] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +55 ms] [  +92 ms] Exit code 0 from: git ls-remote --get-url origin
[  +22 ms] [        ] https://github.com/flutter/flutter.git
[ +176 ms] [ +200 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +299 ms] [ +297 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[  +99 ms] [  +86 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +26 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] [  +34 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +30 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[  +23 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +77 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +8 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +78 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +24 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[  +21 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +14 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +45 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +30 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +3 ms] [ +277 ms] Initializing file store
[ +125 ms] [  +37 ms] Done initializing file store
[ +102 ms] [ +162 ms] Skipping target: gen_localizations
[+1573 ms] [+1723 ms] Skipping target: kernel_snapshot
[   +2 ms] [  +15 ms] invalidated build due to missing files: D:\Dataku\Universitas Brawijaya\Non - Akademik\Dicoding\Hybrid or
Multiplatform Programming\Flutter\Codelab 3\wisata_bandung\DOES_NOT_EXIST_RERUN_FOR_WILDCARD223860831
[ +996 ms] [+1001 ms] debug_android_application: Starting due to {InvalidatedReason.inputMissing}
[ +304 ms] [ +371 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see
#56466.
[ +125 ms] [ +105 ms] debug_android_application: Complete
[+1370 ms] [+1393 ms] Persisting file store
[ +101 ms] [  +34 ms] Done persisting file store
[   +1 ms] [  +16 ms] build succeeded.
[  +34 ms] [  +44 ms] "flutter assemble" took 5,260ms.
[  +23 ms] [  +10 ms] ensureAnalyticsSent: 0ms
[  +44 ms] [   +3 ms] Running shutdown hooks
[  +18 ms] [        ] Shutdown hooks complete
[   +1 ms] [   +6 ms] exiting with code 0
[ +178 ms] Parameter format not correct -
[   +8 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[  +23 ms] > Task :app:preBuild UP-TO-DATE
[  +19 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +2 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +44 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +5 ms] > Task :app:mergeDebugAssets
[ +482 ms] > Task :app:copyFlutterAssetsDebug
[  +23 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[ +273 ms] > Task :app:generateDebugResValues UP-TO-DATE
[ +129 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +67 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +1 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +23 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +2 ms] > Task :app:processDebugManifest UP-TO-DATE
[  +32 ms] > Task :app:processDebugResources UP-TO-DATE
[   +4 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +2 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +30 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[   +5 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[ +216 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +81 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[ +186 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[  +23 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +1 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[  +52 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[   +4 ms] > Task :app:mergeDebugNativeLibs FAILED
[  +23 ms] 28 actionable tasks: 5 executed, 23 up-to-date
[  +36 ms] FAILURE: Build failed with an exception.
[  +87 ms] * What went wrong:
[   +2 ms] Execution failed for task ':app:mergeDebugNativeLibs'.
[   +4 ms] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[  +17 ms]    > java.util.zip.ZipException: invalid stored block lengths
[  +21 ms] * Try:
[  +26 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan toget full insights.
[  +14 ms] * Get more help at https://help.gradle.org
[  +11 ms] BUILD FAILED in 15s
[  +88 ms] Running Gradle task 'assembleDebug'... (completed in 16.4s)
[ +472 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 21,335ms.
[  +33 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +140 ms] ensureAnalyticsSent: 107ms
[   +2 ms] Running shutdown hooks
[  +59 ms] Shutdown hook priority 4
[  +61 ms] Shutdown hooks complete
[  +34 ms] exiting with code 1
```

```
No issues found! (ran in 17.2s)
```

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18363.752], locale en-ID)
    • Flutter version 1.20.1 at C:\flutter
    • Framework revision 2ae34518b8 (7 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • SM A507FN (mobile)                 • RR8M90HZZ9N   • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 6.0 (API 23) (emulator)

• No issues found!
```

</details>

**Comment by Abhishek01039** [comment]
https://stackoverflow.com/questions/61457909/how-to-fix-appmergedebugnativelibs-exection-failed-issue

**Comment by eerbee** [comment]
not work but thanks

**Comment by Abhishek01039** [comment]
can you try `File > Invalidate Caches/Restart..` in the android studio then try `flutter clean` then still problem is there then send the `flutter doctor -v`

**Comment by eerbee** [comment]
@Abhishek01039 well i use vs code, and for flutter clean also flutter doctor it show normal no error

![image](https://user-images.githubusercontent.com/57081157/90127284-2344e180-dd8f-11ea-91a9-ae895b0a3751.png)

**Comment by darshankawar** [comment]
Hi @eerbee,
What's the location of Flutter sdk in your machine ? Can you check if there are existing dart.exe processes running ? 
If you see any processes, terminate them and then try `flutter clean` and then `flutter run` to see if it resolves your issue ?

If the problem persists, provide a minimal complete reproducible code sample, `build.gradle`, `app/build.gradle` files.
Thanks.

**Comment by eerbee** [comment]
@darshankawar hi thanks for answering

- my flutted sdk is on C:/flutter/bin/...

-  for dart.exe processes running, i try check that with Process Explorer when i open my project on vs code then this is what i got : 
![image](https://user-images.githubusercontent.com/57081157/90138018-96a31f00-dda0-11ea-8a4e-66cbc76e5f33.png)
so its normal ? i've 2 dart.exe processes running?

- build.gradle
`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

- app/build.gradle
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.hello_word"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.multidex:multidex:2.0.1' 
}
`

**Comment by eerbee** [comment]
[SOLVED] just change my channel to master but still on channel stable didnt work
