### ISSUE TITLE
Flutter TimePicker Doesn't Work Properly

### ISSUE THREAD

**Issue by draxex** [flutter/flutter#63642]
Hi,

I implement timepicker in my flutter app but it's colors doesn't work properly. Here is my code

```
class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    _pickTime() async {
      await showTimePicker(
        context: context,
        initialTime: TimeOfDay.now(),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text("Time Picker"),
      ),
      body: RaisedButton(
        onPressed: () {
          _pickTime();
        },
        child: Text("Time Picker"),
      ),
    );
  }
}
```
![Screenshot_1597308565](https://user-images.githubusercontent.com/69625295/90114282-2f16b080-dd5b-11ea-9726-b1fc1a704c80.png)

**Comment by markusaksli-nc** [comment]
Hi @draxex 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by draxex** [comment]
**Here is my flutter doctor -v result**
![doctor-v](https://user-images.githubusercontent.com/69625295/90119401-31303d80-dd62-11ea-9c3c-b5e2dd6fb808.jpg)

**Here is my flutter run--verbose result**

```
[ +166 ms] executing: [D:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
[   +3 ms] executing: [D:\src\flutter/] git tag --contains HEAD
[ +267 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.20.1
[  +15 ms] executing: [D:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +3 ms] executing: [D:\src\flutter/] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +93 ms] executing: [D:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[  +92 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +50 ms] executing: C:\Users\Draxex\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +61 ms] List of devices attached
[   +6 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +66 ms] No supported devices connected.
[  +14 ms] "flutter run" took 265ms.
[  +25 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:343:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:836:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +278 ms] ensureAnalyticsSent: 266ms
[  +10 ms] Running shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +6 ms] exiting with code 1
```

**In my code, this function shows timepicker**

```
_pickTime() async {
      await showTimePicker(
        context: context,
        initialTime: TimeOfDay.now(),
      );
    }
```

**And I just trigger this function with my RaisedButton**

```
RaisedButton(
        onPressed: () {
          _pickTime();
        },
        child: Text("Time Picker"),
      ),
```

**Comment by markusaksli-nc** [comment]
@draxex What is the issue you are having with TimePiceker exactly?

**Comment by draxex** [comment]
My TimePicker views like this, it works properly but why it is viewing like that I don't know, It should have blue background on top.
![Screenshot_1597313096](https://user-images.githubusercontent.com/69625295/90122240-a7826f00-dd65-11ea-9eb8-7230ca5d5541.png)

**Comment by Zazo032** [comment]
That's the new Time Picker from Material guidelines: https://material.io/components/time-pickers

It no longer has a primary color header. However, the hour ring should show a circular background (maybe you changed that color)

**Comment by draxex** [comment]
@Zazo032 thank you so much, that's what I looking for

**Comment by markusaksli-nc** [comment]
The default TimePicker actually doesn't have the background for the hour ring. Leaving this open in case it doesn't match Material Design spec. Feel free to just close if this isn't the case.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(title: 'Sample', home: MyApp()));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Sample'),
      ),
      body: Container(
        child: Center(
          child: RaisedButton(
            onPressed: () {
              showTimePicker(context: context, initialTime: TimeOfDay.now());
            },
            child: Text("Time Picker"),
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.70, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.70 at C:\Development\flutter_master
    • Framework revision 0629030a05 (5 hours ago), 2020-08-13 00:01:03 -0400
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

**Comment by Zazo032** [comment]
@darrenaustin is this a fidelity issue with the new time picker?

**Comment by markusaksli-nc** [comment]
That was directed towards any flutter team member that looks at this issue @draxex

**Comment by draxex** [comment]
@markusaksli-nc thank you

**Comment by HansMuller** [comment]
CC @rami-a @darrenaustin

**Comment by rami-a** [comment]
Hello, the new time picker reads the colors from the `ColorScheme` by default. If you use `ColorScheme.light()` (or dark) in your theme you should get the correct colors. Additionally, you can customize basically all the colors by providing a `TimePickerThemeData` to your theme.

![Simulator Screen Shot - iPhone 8 - 2020-08-03 at 10 34 45](https://user-images.githubusercontent.com/2364772/90157718-14910700-dd5c-11ea-89ca-86bc564241d1.png)

**Comment by markusaksli-nc** [comment]
Thank you for clarifying, didn't know that. I don't see this mentioned in the documentation for [showTimePicker](https://master-api.flutter.dev/flutter/material/showTimePicker.html). Maybe a reference to [TimePickerTheme](https://master-api.flutter.dev/flutter/material/TimePickerTheme-class.html) should be added to the **See also:** section?

**Comment by rami-a** [comment]
@markusaksli-nc good idea, I've created a PR to update the documentation. https://github.com/flutter/flutter/pull/63776
