### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\umme habiba\Documents\flutterproject\flutter_cocktail\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by ummehabiba99** [flutter/flutter#63779]
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot copy file to 'C:\Users\umme habiba\Documents\flutterproject\flutter_cocktail\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:256:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      Template.render (package:flutter_tools/src/template.dart:182:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:781:21)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (24 hours ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\umme habiba\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.0)
    • VS Code at C:\Users\umme habiba\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by Abhishek01039** [comment]
Duplication of https://github.com/flutter/flutter/issues/50880

**Comment by Abhishek01039** [comment]
Hii @ummehabiba99 
I see there's a similar open issue describing your case, https://github.com/flutter/flutter/issues/50880
Please follow-up there for updates.
you can close the issue now
Thanks

**Comment by ummehabiba99** [comment]
there are no currently updates available

**Comment by Abhishek01039** [comment]
see one of the mentioned issues in https://github.com/flutter/flutter/issues/50880

**Comment by darshankawar** [comment]
Hi @ummehabiba99,
There's similar open issue related to the issue you are facing, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for progress, updates and any questions.
Closing this as duplicate.
