### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by Pranavparth** [flutter/flutter#63842]
## Command
```
flutter doctor --android-licenses
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:458:47)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#5      GradleWrapper.updateInner.<anonymous closure> (package:flutter_tools/src/cache.dart:1124:70)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#14     CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart)
<asynchronous suspension>
#15     CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:636:12)
#16     CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:662:12)
#17     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:1120:12)
#18     CachedArtifact.update (package:flutter_tools/src/cache.dart:592:11)
#19     Cache.updateAll (package:flutter_tools/src/cache.dart:458:24)
#20     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:831:27)
#21     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
```
```
[✓] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.20.0 at C:\flutter
    • Framework revision 916c3ac648 (2 weeks ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.0)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by Abhishek01039** [comment]
if you are working on windows then run your cmd as administrator
if you are working on Mac or Linux then give the necessary permission to your directory
Thanks

**Comment by darshankawar** [comment]
Hi @Pranavparth,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates and any questions.
Closing this as duplicate.
