### ISSUE TITLE
FileSystemException: FileSystemException: Deletion failed,

### ISSUE THREAD

**Issue by zhaojiewen** [flutter/flutter#63872]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter pub get

## exception

FileSystemException: FileSystemException: Deletion failed, path = '/Users/xuhaiqing/Desktop/MyKey/mykey_flutter/.ios' (OS Error: Permission denied, errno = 13)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:455:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#4      _deleteIfExistsSync (package:flutter_tools/src/project.dart:886:15)
#5      IosProject._regenerateFromTemplateIfNeeded (package:flutter_tools/src/project.dart:596:5)
#6      IosProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:547:11)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:246:17)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:907:18)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.110, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.21.0-10.0.pre.110 at /Users/xuhaiqing/FlutterGit/flutter
    • Framework revision 2b25e29192 (25 hours ago), 2020-08-15 01:06:03 +0100
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xuhaiqing/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • xu的 iPhoneg (mobile) • 00008030-00022C58229A802E • ios • iOS 14.0
    ! Error: SH is not connected. Xcode will continue when SH is connected. (code -13)

• No issues found!
```

**Comment by Tejaswgupta** [comment]
**Errno13** is a ownership error i beleive.
Try runnning with sudo instead,```sudo flutter pub get```

**Comment by jmagman** [comment]
@zhaojiewen Is this an add-to-app module?

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/9248fda41005ce0af2e522fabd0e9fedf2b3c863
