### ISSUE TITLE
App gives gray screen only on physical Android device

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#63881]
## Steps to Reproduce

I have an app that runs fine on Apple Simulator, Android Emulator, and an Apple physical device.  However, when I run it on an Android physical device, it fails to boot up correctly and I get a gray screen.  The weird part is that the same application runs fine on the physical device when remote debugging through VS Code or Android Studio.  I don't have any indication of a layout issue, other than the gray screen.

The problem with the Android physical device is consistent for both debug and release builds, and whether I am connecting to a dev environment or a production environment.

I am at a loss as to how to debug this, so I added _Firebase Crashlytics_ and it reported this:
```
Non-fatal Exception: java.lang.Exception: MediaQuery.of() called with a context that does not contain a MediaQuery.
       at MediaQuery.of(MediaQuery.java:819)
       at SafeArea.build(SafeArea.java:99)
       at StatelessElement.build(StatelessElement.java:4620)
       at ComponentElement.performRebuild(ComponentElement.java:4546)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at MultiChildRenderObjectElement.mount(MultiChildRenderObjectElement.java:5991)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at StatefulElement._firstBuild(StatefulElement.java:4710)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at SingleChildRenderObjectElement.mount(SingleChildRenderObjectElement.java:5874)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3258)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at Element.rebuild(Element.java:4262)
       at ComponentElement._firstBuild(ComponentElement.java:4525)
       at ComponentElement.mount(ComponentElement.java:4520)
       at Element.inflateWidget(Element.java:3490)
       at Element.updateChild(Element.java:3255)
       at ComponentElement.performRebuild(ComponentElement.java:4571)
       at StatefulElement.performRebuild(StatefulElement.java:4719)
       at Element.rebuild(Element.java:4262)
       at BuildOwner.buildScope(BuildOwner.java:2667)
       at WidgetsBinding.drawFrame(WidgetsBinding.java:866)
       at RendererBinding._handlePersistentFrameCallback(RendererBinding.java:286)
       at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1117)
       at SchedulerBinding.handleDrawFrame(SchedulerBinding.java:1056)
       at SchedulerBinding._handleDrawFrame(SchedulerBinding.java:972)
```

This is the best clue that I have.  However, this stack trace looks 100% Flutter Framework related -- I don't see any of my code in the stack trace.

The physical device is a **Lenovo Tab E7** running **Android 8.1.0** in _Portrait_ mode, with **381.48 MB** in Free RAM and **3.04 GB** in Free Disk.

**Expected results:** 

The app initializes some components (like Firebase Remote Config), and then presents a Welcome Screen where the user is presented login choices.

**Actual results:** 

I think the component initialization is working (because I do see a `CircularProgressIndicator`), but then it just goes to the gray screen.  (I tried commenting out the Welcome Screen and just showing a `Scaffold` with a `Text` body, but that failed too.)

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.2 at /Users/anthony/flutter
    • Framework revision bbfbf1770c (3 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/anthony/Library/Android/sdk
    • Platform android-R, build-tools 30.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

I will continue to investigate to see if I can narrow this issue down.  However, I figured that I'd share this in case others are plagued with similar issues.  I am also interested in hearing advice on how to best debug this since the natural remote debugging is ineffective.

**Comment by awhitford** [comment]
I was finally able to trace the issue to the _Firebase Remote Config_ initialization throwing an exception, "Unable to complete fetch.  Reason is unknown but this could be due to lack of connectivity."  (Of course, connectivity is fine.).

**Comment by awhitford** [comment]
FYI...  In case anyone is wondering how to resolve the Firebase Remote Config issue, this [comment](https://github.com/FirebaseExtended/flutterfire/issues/1572#issuecomment-634873953) pointed me in the right direction:  I had to add the SHA1 for the Android key.
