### ISSUE TITLE
java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported.

### ISSUE THREAD

**Issue by huntrist** [flutter/flutter#63927]
```
java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
    at org.chromium.android_webview.AwBrowserProcess.b(PG:10)
    at F5.g(PG:27)
    at E5.run(PG:2)
    at pt.f(PG:11)
    at ot.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7697)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)


java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Lock owner com.aaa.app:pushcore (pid 3699)
    at org.chromium.android_webview.AwDataDirLock.a(PG:26)
    at v7.g(PG:46)
    at u7.run(PG:2)
    at ov.f(PG:11)
    at nv.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8347)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

Ever since upgraded from 1.12.13+hotfix.9 to 1.17.5 the problem started to show up a lot more. (from 0.x% to 4.x%)
And upgrade to 1.20.1 did NOT help.

Not sure if this is caused by some change in Flutter
or  some plugin 
or just a bug in Chromium as described in: https://crbug.com/558377 that we need to wait for fixing

since this is only seen in some production app, I am unable to provide more bug information
or give minimum reproducible demo

flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.1016], locale zh-CN)
    • Flutter version 1.20.1 at D:\Env\flutter
    • Framework revision 2ae34518b8 (11 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Env\Android\SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Env\Android\SDK
    • Java binary at: D:\Executable\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Executable\Android\AndroidStudio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

pubspec.yaml plugins

```
version: 2.6.6+144

environment:
  sdk: ">=2.3.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  basic_utils: ^2.6.1 
  extended_text: ^4.0.0
  extended_image: ^1.1.0 
  image: ^2.1.14 #^2.1.12 
  chewie: ^0.9.10
  video_player: ^0.10.11+2

  path: ^1.7.0
  provider: ^4.3.2
  event_bus: ^1.1.1
  http: ^0.12.2
  device_info: ^0.4.2+4 
  uuid: ^2.2.0
  sqflite: ^1.3.1 
  flutter_secure_storage: ^3.3.3 
  shared_preferences: ^0.5.8
  path_provider: ^1.6.11
  
  filesize: ^1.0.4
  
  url_launcher: ^5.5.0 
  webview_flutter: ^0.3.22+1 
  permission_handler: ^5.0.1+1

  flutter_image_compress: ^0.7.0
  gallery_saver: ^2.0.1 
  image_gallery_saver: ^1.5.0

  image_picker: ^0.6.7+4
  keyboard_avoider: ^0.1.2
  extended_nested_scroll_view: ^1.0.1

  #sharesdk_plugin: ^1.2.6
  sharesdk_plugin:
    path: vendor/sharesdk_plugin

  fluwx: ^2.3.0
  uni_links: ^0.4.0

  pointycastle: ^1.0.2
  app_review: ^2.0.1

  flutter_native_timezone: ^1.0.4
  timezone: ^0.5.7

  umeng_analytics_plugin: ^1.0.3

  jpush_flutter: ^0.5.3

  qr_flutter: ^3.2.0
  smooth_page_indicator: ^0.2.0
  wechat_assets_picker: ^4.1.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Comment by TahaTesser** [comment]
Hi @huntrist 
Can you please provide the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by huntrist** [comment]
These are the top crashing devices: 

SEA-AL10
4.59%
ELE-AL00(华为P30)
4.33%
TAS-AN00
3.54%
HMA-AL00(华为 Mate 20)
3.15%
DUK-AL20(荣耀 V9)
2.49%

These are all Huawei devices
we have also received reports of crashing on Vivo/OPPO, and Meizu phones
Not sure if Huawei shows up as the top crashes just because the total number of devices are greater, or it has a higher crash rate.

These are the Top OS distribution
android 10
69.99%
android 9
29.88%

I am currently unable to provide ``` flutter run --release --verbose ``` due to lack of access to these devices

**Comment by TahaTesser** [comment]
I’m unable to reproduce the issue to pinpoint the cause,  as this is production app. The issue needs further investigation.

**Comment by Hixie** [comment]
This is just a limitation of the WebView, as noted in the bug linked to in the original comment. Nothing we can really do on our side about this.

**Comment by 948911908** [comment]
解决了吗，我也遇到了这个问题

**Comment by wanghuasheng** [comment]
解决了吗？这个问题还存在
