### ISSUE TITLE
How to capture a custom widget having multiple custom painter as an image in web

### ISSUE THREAD

**Issue by DeviArunaMurugan** [flutter/flutter#63955]
I have a custom widget which consists of multiple custom painter, I want to export the widget as an image. For that, I have placed the widget inside the RepaintBoundary and get its dart:ui.image. With the dart:ui.image, I have rendered the custom widget as an image.

```
import 'dart:async';
import 'dart:ui' as dart_ui;
import 'package:flutter/rendering.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  MyContainer _container = MyContainer();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            _container,
            RaisedButton(
              child: Text(
                'To Image',
              ),
              onPressed: _renderImage,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20)),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _renderImage() async {
    final dart_ui.Image data = await _container._toImage();
    final bytes = await data.toByteData(format: dart_ui.ImageByteFormat.png);
    if (data != null) {
      await Navigator.of(context).push(
        MaterialPageRoute(
          builder: (BuildContext context) {
            return Scaffold(
              appBar: AppBar(),
              body: Center(
                child: Container(
                  color: Colors.white,
                  child: Image.memory(bytes.buffer.asUint8List()),
                ),
              ),
            );
          },
        ),
      );
    }
  }
}

class MyContainer extends StatefulWidget {
  MyContainer({
    Key key,
  }) : super(key: key);

  _MyContainerState _currentState;
  @override
  _MyContainerState createState() {
    _currentState = _MyContainerState();
    return _currentState;
  }

  Future<dart_ui.Image> _toImage() async {
    return _currentState._toImage();
  }
}

class _MyContainerState extends State<MyContainer> {
  BuildContext _currentContext;
  @override
  Widget build(BuildContext context) {
    _currentContext = context;
    return RepaintBoundary(
      child: Container(
        height: 200,
        width: 200,
        color: Colors.blue,
      ),
    );
  }

  Future<dart_ui.Image> _toImage() async {
    final RenderRepaintBoundary boundary = _currentContext.findRenderObject();
    final dart_ui.Image data = await boundary.toImage(pixelRatio: 3.0);
    return data;
  }
}
```
Note: Since my widget has n number of the custom painter, in the above I have exposed the core logic of conversion with a container widget.

The above code is working fine on mobile. But on the web, exporting is not working.

Regards,
Devi

**Comment by markusaksli-nc** [comment]
Seems like `toImage` is not supported on web yet. This is being logged to the console correctly in most cases. These all say as much in the exception (to varying degrees of clarity):
<details>
 <summary>flutter run -d chrome --release</summary>

```
Uncaught Unsupported operation: toImage is not supported on the Web
    at Object.b (http://localhost:60745/main.dart.js:2588:3)
    at lj.Mv (http://localhost:60745/main.dart.js:18326:26)
    at http://localhost:60745/main.dart.js:31841:15
    at Rw.a (http://localhost:60745/main.dart.js:3920:72)
    at Rw.$2 (http://localhost:60745/main.dart.js:21663:23)
    at Object.ac (http://localhost:60745/main.dart.js:3906:20)
    at hL.Mw (http://localhost:60745/main.dart.js:31857:10)
    at hL.me (http://localhost:60745/main.dart.js:31828:30)
    at http://localhost:60745/main.dart.js:39950:15
    at Rw.a (http://localhost:60745/main.dart.js:3920:72)
```
</details>
<details>
 <summary>`flutter run --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome`</summary>

```
:60853/dart_sdk.js:5964 Uncaught (in promise) Error: Unsupported operation: LayerScene.toImage not implemented.
    at Object.throw_ [as throw] (:60853/dart_sdk.js:4330)
    at _engine.LayerScene.new.toImage (:60853/dart_sdk.js:139530)
    at layer$.OffsetLayer.new.toImage (:60853/packages/flutter/src/rendering/layer.dart.lib.js:1615)
    at toImage.next (<anonymous>)
    at runBody (:60853/dart_sdk.js:37610)
    at Object._async [as async] (:60853/dart_sdk.js:37641)
    at layer$.OffsetLayer.new.toImage (:60853/packages/flutter/src/rendering/layer.dart.lib.js:1606)
    at proxy_box.RenderRepaintBoundary.new.toImage (:60853/packages/flutter/src/rendering/proxy_box.dart.lib.js:3002)
    at main._MyContainerState.new._toImage (:60853/packages/master/main.dart.lib.js:706)
    at _toImage.next (<anonymous>)
    at runBody (:60853/dart_sdk.js:37610)
    at Object._async [as async] (:60853/dart_sdk.js:37641)
    at main._MyContainerState.new.[_toImage] (:60853/packages/master/main.dart.lib.js:704)
    at main.MyContainer.new._toImage$ (:60853/packages/master/main.dart.lib.js:666)
    at _toImage$.next (<anonymous>)
    at runBody (:60853/dart_sdk.js:37610)
    at Object._async [as async] (:60853/dart_sdk.js:37641)
    at main.MyContainer.new.[_toImage] (:60853/packages/master/main.dart.lib.js:665)
    at main._MyHomePageState.new._renderImage (:60853/packages/master/main.dart.lib.js:633)
    at _renderImage.next (<anonymous>)
    at runBody (:60853/dart_sdk.js:37610)
    at Object._async [as async] (:60853/dart_sdk.js:37641)
    at main._MyHomePageState.new.[_renderImage] (:60853/packages/master/main.dart.lib.js:632)
    at ink_well._InkResponseState.new.[_handleTap] (:60853/packages/flutter/src/material/icon_button.dart.lib.js:47080)
    at :60853/packages/flutter/src/material/icon_button.dart.lib.js:47182
    at tap.TapGestureRecognizer.new.invokeCallback (:60853/packages/flutter/src/gestures/recognizer.dart.lib.js:189)
    at tap.TapGestureRecognizer.new.handleTapUp (:60853/packages/flutter/src/gestures/tap.dart.lib.js:395)
    at tap.TapGestureRecognizer.new.[_checkUp] (:60853/packages/flutter/src/gestures/tap.dart.lib.js:201)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (:60853/packages/flutter/src/gestures/tap.dart.lib.js:148)
    at tap.TapGestureRecognizer.new.handleEvent (:60853/packages/flutter/src/gestures/recognizer.dart.lib.js:448)
    at pointer_router.PointerRouter.new.[_dispatch] (:60853/packages/flutter/src/gestures/pointer_router.dart.lib.js:74)
    at :60853/packages/flutter/src/gestures/pointer_router.dart.lib.js:109
    at LinkedMap.new.forEach (:60853/dart_sdk.js:24747)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (:60853/packages/flutter/src/gestures/pointer_router.dart.lib.js:106)
    at pointer_router.PointerRouter.new.route (:60853/packages/flutter/src/gestures/pointer_router.dart.lib.js:98)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (:60853/packages/flutter/src/gestures/binding.dart.lib.js:166)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (:60853/packages/flutter/src/gestures/binding.dart.lib.js:149)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (:60853/packages/flutter/src/gestures/binding.dart.lib.js:120)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (:60853/packages/flutter/src/gestures/binding.dart.lib.js:93)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (:60853/packages/flutter/src/gestures/binding.dart.lib.js:83)
    at Object._invoke1 (:60853/dart_sdk.js:175193)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (:60853/dart_sdk.js:171139)
    at _engine.PointerBinding.__.[_onPointerData] (:60853/dart_sdk.js:144863)
    at :60853/dart_sdk.js:145250
    at :60853/dart_sdk.js:145209
    at :60853/dart_sdk.js:144962
```
</details>
<details>
 <summary>flutter run --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome --release</summary>

```
js_helper.dart:1129 Uncaught Unsupported operation: LayerScene.toImage not implemented.
    at Object.a (http://localhost:60461/main.dart.js:1557:3)
    at uA.M6 (http://localhost:60461/main.dart.js:13472:26)
    at http://localhost:60461/main.dart.js:27725:15
    at PY.a (http://localhost:60461/main.dart.js:3034:72)
    at PY.$2 (http://localhost:60461/main.dart.js:17790:23)
    at Object.ac (http://localhost:60461/main.dart.js:3020:20)
    at hr.M7 (http://localhost:60461/main.dart.js:27741:10)
    at hr.lx (http://localhost:60461/main.dart.js:27712:30)
    at http://localhost:60461/main.dart.js:35839:15
    at PY.a (http://localhost:60461/main.dart.js:3034:72)
```
</details>

However, with just regular debug build it says something entirely different.
<details>
 <summary>flutter run -d chrome</summary>

```
:61640/dart_sdk.js:5964 Uncaught (in promise) Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:92:16
matrix4[0] == window.devicePixelRatio &&
           matrix4[5] == window.devicePixelRatio
is not true
    at Object.throw_ [as throw] (:61640/dart_sdk.js:4330)
    at Object.assertFailed (:61640/dart_sdk.js:4277)
    at _engine.SurfaceSceneBuilder.new.pushTransform (:61640/dart_sdk.js:162788)
    at layer$.OffsetLayer.new.toImage (:61640/packages/flutter/src/rendering/layer.dart.lib.js:1612)
    at toImage.next (<anonymous>)
    at runBody (:61640/dart_sdk.js:37610)
    at Object._async [as async] (:61640/dart_sdk.js:37641)
    at layer$.OffsetLayer.new.toImage (:61640/packages/flutter/src/rendering/layer.dart.lib.js:1606)
    at proxy_box.RenderRepaintBoundary.new.toImage (:61640/packages/flutter/src/rendering/proxy_box.dart.lib.js:3002)
    at main._MyContainerState.new._toImage (:61640/packages/master/main.dart.lib.js:706)
    at _toImage.next (<anonymous>)
    at runBody (:61640/dart_sdk.js:37610)
    at Object._async [as async] (:61640/dart_sdk.js:37641)
    at main._MyContainerState.new.[_toImage] (:61640/packages/master/main.dart.lib.js:704)
    at main.MyContainer.new._toImage$ (:61640/packages/master/main.dart.lib.js:666)
    at _toImage$.next (<anonymous>)
    at runBody (:61640/dart_sdk.js:37610)
    at Object._async [as async] (:61640/dart_sdk.js:37641)
    at main.MyContainer.new.[_toImage] (:61640/packages/master/main.dart.lib.js:665)
    at main._MyHomePageState.new._renderImage (:61640/packages/master/main.dart.lib.js:633)
    at _renderImage.next (<anonymous>)
    at runBody (:61640/dart_sdk.js:37610)
    at Object._async [as async] (:61640/dart_sdk.js:37641)
    at main._MyHomePageState.new.[_renderImage] (:61640/packages/master/main.dart.lib.js:632)
    at ink_well._InkResponseState.new.[_handleTap] (:61640/packages/flutter/src/material/icon_button.dart.lib.js:47080)
    at :61640/packages/flutter/src/material/icon_button.dart.lib.js:47182
    at tap.TapGestureRecognizer.new.invokeCallback (:61640/packages/flutter/src/gestures/recognizer.dart.lib.js:189)
    at tap.TapGestureRecognizer.new.handleTapUp (:61640/packages/flutter/src/gestures/tap.dart.lib.js:395)
    at tap.TapGestureRecognizer.new.[_checkUp] (:61640/packages/flutter/src/gestures/tap.dart.lib.js:201)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (:61640/packages/flutter/src/gestures/tap.dart.lib.js:148)
    at tap.TapGestureRecognizer.new.handleEvent (:61640/packages/flutter/src/gestures/recognizer.dart.lib.js:448)
    at pointer_router.PointerRouter.new.[_dispatch] (:61640/packages/flutter/src/gestures/pointer_router.dart.lib.js:74)
    at :61640/packages/flutter/src/gestures/pointer_router.dart.lib.js:109
    at LinkedMap.new.forEach (:61640/dart_sdk.js:24747)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (:61640/packages/flutter/src/gestures/pointer_router.dart.lib.js:106)
    at pointer_router.PointerRouter.new.route (:61640/packages/flutter/src/gestures/pointer_router.dart.lib.js:98)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (:61640/packages/flutter/src/gestures/binding.dart.lib.js:166)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (:61640/packages/flutter/src/gestures/binding.dart.lib.js:149)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (:61640/packages/flutter/src/gestures/binding.dart.lib.js:120)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (:61640/packages/flutter/src/gestures/binding.dart.lib.js:93)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (:61640/packages/flutter/src/gestures/binding.dart.lib.js:83)
    at Object._invoke1 (:61640/dart_sdk.js:175193)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (:61640/dart_sdk.js:171139)
    at _engine.PointerBinding.__.[_onPointerData] (:61640/dart_sdk.js:144863)
    at :61640/dart_sdk.js:145250
    at :61640/dart_sdk.js:145209
    at :61640/dart_sdk.js:144962
```
</details>

Going to mark this as an error message issue on the latest master `1.21.0-10.0.pre.114`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.135, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.135 at C:\Development\flutter_master
    • Framework revision 654022aecb (6 hours ago), 2020-08-18 03:01:02 +0300
    • Engine revision b9243713a0
    • Dart version 2.10.0 (build 2.10.0-36.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>
