### ISSUE TITLE
./dev/update_packages.py fails awkwardly if pub is not in your path

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#64]
./dev/update_packages.py          [/src/flutter]
Updating cassowary ...
Traceback (most recent call last):
  File "./dev/update_packages.py", line 19, in <module>
    update(os.path.join(FLUTTER_ROOT, 'packages'))
  File "./dev/update_packages.py", line 17, in update
    subprocess.check_call(['pub', 'get'], cwd=package_dir)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

%pub                               [/src/flutter]
zsh: command not found: pub

**Comment by abarth** [comment]
Fixed by integrating with the flutter tool.
