### ISSUE TITLE
flutter 

### ISSUE THREAD

**Issue by mosta91** [flutter/flutter#64043]
## Steps to Reproduce

I run simple flutter app. every things is good and app run correctly on android.
but now the app does not run at all.

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Unhandled exception:
Crash when compiling null,
at character offset null:
Not implemented
[38;5;248m#0      TypeBuilderComputer.visitInvalidType  (package:front_end/src/fasta/kernel/type_builder_computer.dart:56:5)[39;49m
[38;5;248m#1      InvalidType.accept  (package:kernel/ast.dart:7252:42)[39;49m

[38;5;248m#2      SourceLoader.computeTypeBuilder  (package:front_end/src/fasta/source/source_loader.dart:1267:17)[39;49m
[38;5;248m#3      ClassHierarchyNodeBuilder.inferMixinApplication  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2290:28)[39;49m
[38;5;248m#4      ClassHierarchyNodeBuilder.build  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1486:7)[39;49m
[38;5;248m#5      ClassHierarchyBuilder.build  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:614:14)[39;49m
[38;5;248m#6      SourceLoader.buildClassHierarchy  (package:front_end/src/fasta/source/source_loader.dart:1122:46)[39;49m
[38;5;248m#7      KernelTarget.buildOutlines.<anonymous closure>  (package:front_end/src/fasta/kernel/kernel_target.dart:326:14)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
#8      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
[38;5;248m#9      withCrashReporting  (package:front_end/src/fasta/crash.dart:122:24)[39;49m
[38;5;248m#10     KernelTarget.buildOutlines  (package:front_end/src/fasta/kernel/kernel_target.dart:301:12)[39;49m

[38;5;248m#11     IncrementalCompiler.computeDelta.<anonymous closure>  (package:front_end/src/fasta/incremental_compiler.dart:269:52)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
#12     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
[38;5;248m#13     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>  (package:front_end/src/fasta/compiler_context.dart:123:46)[39;49m
[38;5;244m#14     new Future.sync  (dart:async/future.dart:223:31)[39;49m
[38;5;248m#15     CompilerContext.runInContext.<anonymous closure>  (package:front_end/src/fasta/compiler_context.dart:123:19)[39;49m
[38;5;244m#16     _rootRun  (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#17     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#18     _runZoned  (dart:async/zone.dart:1630:10)[39;49m
[38;5;244m#19     runZoned  (dart:async/zone.dart:1550:10)[39;49m
[38;5;248m#20     CompilerContext.runInContext  (package:front_end/src/fasta/compiler_context.dart:122:12)[39;49m
[38;5;248m#21     IncrementalCompiler.computeDelta  (package:front_end/src/fasta/incremental_compiler.dart:206:20)[39;49m
[38;5;248m#22     IncrementalCompiler.compile  (package:vm/incremental_compiler.dart:69:46)[39;49m
[38;5;248m#23     FrontendCompiler.compile.<anonymous closure>  (package:frontend_server/frontend_server.dart:526:59)[39;49m
[38;5;244m#24     new Future.<anonymous closure>  (dart:async/future.dart:175:37)[39;49m
[38;5;244m#25     _rootRun  (dart:async/zone.dart:1182:47)[39;49m
[38;5;244m#26     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#27     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)[39;49m
[38;5;244m#28     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)[39;49m
[38;5;244m#29     _rootRun  (dart:async/zone.dart:1190:13)[39;49m

[38;5;244m#30     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#31     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1021:23)[39;49m
[38;5;244m#32     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:18:15)[39;49m
[38;5;244m#33     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19)[39;49m
[38;5;244m#34     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5)[39;49m
[38;5;244m#35     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m


[38;5;248m#0      TypeBuilderComputer.visitInvalidType  (package:front_end/src/fasta/kernel/type_builder_computer.dart:56:5)[39;49m
[38;5;248m#1      InvalidType.accept  (package:kernel/ast.dart:7252:42)[39;49m
[38;5;248m#2      SourceLoader.computeTypeBuilder  (package:front_end/src/fasta/source/source_loader.dart:1267:17)[39;49m
[38;5;248m#3      ClassHierarchyNodeBuilder.inferMixinApplication  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:2290:28)[39;49m
[38;5;248m#4      ClassHierarchyNodeBuilder.build  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:1486:7)[39;49m
[38;5;248m#5      ClassHierarchyBuilder.build  (package:front_end/src/fasta/kernel/class_hierarchy_builder.dart:614:14)[39;49m
[38;5;248m#6      SourceLoader.buildClassHierarchy  (package:front_end/src/fasta/source/source_loader.dart:1122:46)[39;49m
[38;5;248m#7      KernelTarget.buildOutlines.<anonymous closure>  (package:front_end/src/fasta/kernel/kernel_target.dart:326:14)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
#8      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart)
[38;5;248m#9      withCrashReporting  (package:front_end/src/fasta/crash.dart:122:24)[39;49m
[38;5;248m#10     KernelTarget.buildOutlines  (package:front_end/src/fasta/kernel/kernel_target.dart:301:12)[39;49m
[38;5;248m#11     IncrementalCompiler.computeDelta.<anonymous closure>  (package:front_end/src/fasta/incremental_compiler.dart:269:52)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
#12     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart)
[38;5;248m#13     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>  (package:front_end/src/fasta/compiler_context.dart:123:46)[39;49m
[38;5;244m#14     new Future.sync  (dart:async/future.dart:223:31)[39;49m
[38;5;248m#15     CompilerContext.runInContext.<anonymous closure>  (package:front_end/src/fasta/compiler_context.dart:123:19)[39;49m
[38;5;244m#16     _rootRun  (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#17     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#18     _runZoned  (dart:async/zone.dart:1630:10)[39;49m
[38;5;244m#19     runZoned  (dart:async/zone.dart:1550:10)[39;49m
[38;5;248m#20     CompilerContext.runInContext  (package:front_end/src/fasta/compiler_context.dart:122:12)[39;49m
[38;5;248m#21     IncrementalCompiler.computeDelta  (package:front_end/src/fasta/incremental_compiler.dart:206:20)[39;49m

[38;5;248m#22     IncrementalCompiler.compile  (package:vm/incremental_compiler.dart:69:46)[39;49m
[38;5;248m#23     FrontendCompiler.compile.<anonymous closure>  (package:frontend_server/frontend_server.dart:526:59)[39;49m
[38;5;244m#24     new Future.<anonymous closure>  (dart:async/future.dart:175:37)[39;49m
[38;5;244m#25     _rootRun  (dart:async/zone.dart:1182:47)[39;49m
[38;5;244m#26     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#27     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)[39;49m
[38;5;244m#28     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)[39;49m
[38;5;244m#29     _rootRun  (dart:async/zone.dart:1190:13)[39;49m
[38;5;244m#30     _CustomZone.run  (dart:async/zone.dart:1093:19)[39;49m
[38;5;244m#31     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1021:23)[39;49m
[38;5;244m#32     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:18:15)[39;49m
[38;5;244m#33     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19)[39;49m
[38;5;244m#34     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5)[39;49m
[38;5;244m#35     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)[39;49m

the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Exited (1)

```

```
```

```
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18363.418], locale en-US)
    • Flutter version 1.20.1 at C:\src\flutter
    • Framework revision 2ae34518b8 (12 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\ZarMehr\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\ZarMehr\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\ZarMehr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment]
Hi @mosta91 
Can you please try with new project by executing ` flutter create myapp` and  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by pro100svitlo** [comment]
I have the same error.
have no clue how it happened.
@mosta91 can you please share how you solved it?
