### ISSUE TITLE
Recipe Failure on ToT: Uncaught Exception: AssertionError

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#64121]
recipe infra failure: Uncaught Exception: AssertionError("Setting dynamic path to something other than a Path: 'https://github.com/flutter/flutter'",)

See https://github.com/flutter/flutter/pull/64120/checks?check_run_id=1001031978

**Comment by godofredoc** [comment]
reverting latest changes to recipes:

https://flutter-review.googlesource.com/c/recipes/+/5863

**Comment by christopherfujino** [comment]
From the stacktrace, this looks like it might be a cocoon regression:

```
The recipe has crashed at point 'Uncaught exception'!

Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 554, in run_steps
    raw_result = recipe_obj.run_steps(api, engine)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/recipe_deps.py", line 733, in run_steps
    properties_def, api=api)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 89, in invoke_with_properties
    arg_names, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 52, in _invoke_with_properties
    return callable_obj(*props, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/flutter/flutter_drone.py", line 41, in RunSteps
    api.properties.get('git_ref'))
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 544, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipe_modules/repo_util/api.py", line 101, in checkout
    tags=True)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 544, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/depot_tools/recipes/recipe_modules/git/api.py", line 175, in checkout
    self.m.path['checkout'] = dir_path
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 544, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_modules/path/api.py", line 461, in __setitem__
    'Setting dynamic path to something other than a Path: %r' % path)
AssertionError: Setting dynamic path to something other than a Path: 'https://github.com/flutter/flutter'
```

**Comment by godofredoc** [comment]
I'm checking the builder configurations, they are working correctly for prod but not for try

**Comment by godofredoc** [comment]
ok, I think I found the problem we were passing positional arguments and the values were swapped.

**Comment by godofredoc** [comment]
Relanding the revert: https://flutter-review.googlesource.com/c/recipes/+/5864

**Comment by godofredoc** [comment]
Task to validate the fix:

https://chromium-swarm.appspot.com/task?id=4e1d61117e01df10

**Comment by godofredoc** [comment]
This is also the reason why presubmits didn't catch this failure:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20framework_tests/109

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/5865

**Comment by christopherfujino** [comment]
> Fix: https://flutter-review.googlesource.com/c/recipes/+/5865

Awesome, thanks for tracking this down!

**Comment by godofredoc** [comment]
Two more PRs to close all the related issues:

https://github.com/flutter/infra/pull/192
https://github.com/flutter/flutter/pull/64125
