### ISSUE TITLE
flutter crash issue.

### ISSUE THREAD

**Issue by sudhanShu-hub** [flutter/flutter#64207]
flutter doctor

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\class\AppData\Local\Programs\Microsoft VS Code\resources\app\package.json' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#5      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#6      VsCode._getVersionFromPackageJson (package:flutter_tools/src/vscode/vscode.dart:266:64)
#7      new VsCode.fromDirectory (package:flutter_tools/src/vscode/vscode.dart:68:34)
#8      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:247:28)
#9      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:209:12)
#10     VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:98:14)
#11     VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:20:10)
#12     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:77:26)
#13     Doctor.validators (package:flutter_tools/src/doctor.dart:170:46)
#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:176:45)
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:282:47)
#16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:47)
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#18     _rootRunUnary (dart:async/zone.dart:1198:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#24     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#25     _rootRun (dart:async/zone.dart:1190:13)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (6 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\class\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code
    • VS Code at C:\Users\class\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by darshankawar** [comment]
Hi @sudhanShu-hub,
There's similar open issue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates and any questions.
Closing this as duplicate.
