### ISSUE TITLE
Android pass boolean parameters to flutter causes a crash

### ISSUE THREAD

**Issue by mrkoLeo** [flutter/flutter#64219]
- Android pass parameters to flutter with  Boolean 
`
 val map = hashMapOf<String, Any>()
 map["isTrue"] = true
`

- this is error message:

`
java.lang.RuntimeException: Unable to resume activity {xx.FlutterContainerActivity}: java.lang.IllegalArgumentException: Unsupported value: true
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4322)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4354)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalArgumentException: Unsupported value: true
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
        at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:36)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
        at com.idlefish.flutterboost.FlutterBoostPlugin.invokeMethod(FlutterBoostPlugin.java:139)
        at com.idlefish.flutterboost.FlutterBoostPlugin.invokeMethodUnsafe(FlutterBoostPlugin.java:97)
        at com.idlefish.flutterboost.ContainerRecord$MethodChannelProxy.invokeChannelUnsafe(ContainerRecord.java:264)
        at com.idlefish.flutterboost.ContainerRecord$MethodChannelProxy.appear(ContainerRecord.java:215)
        at com.idlefish.flutterboost.ContainerRecord$MethodChannelProxy.access$200(ContainerRecord.java:199)
        at com.idlefish.flutterboost.ContainerRecord.onAppear(ContainerRecord.java:94)
        at com.idlefish.flutterboost.containers.FlutterActivityAndFragmentDelegate.onResume(FlutterActivityAndFragmentDelegate.java:170)
        at com.idlefish.flutterboost.containers.BoostFlutterActivity.onResume(BoostFlutterActivity.java:260)
`
- debug with logic. the problem is this 'StandardMessageCodec' class
![StandardMessageCodec](https://user-images.githubusercontent.com/13517925/90711713-069b3300-e2d4-11ea-81e0-cd847e9e18f4.png)

- Found that TRUE is not the same object
![image](https://user-images.githubusercontent.com/13517925/90711835-4eba5580-e2d4-11ea-95a5-f22666758845.png)
- I try to solve
![image](https://user-images.githubusercontent.com/13517925/90711876-672a7000-e2d4-11ea-8def-8a540a397357.png)

- Don't know if i am right . What do you think?

**Comment by a5209527** [comment]
I had the same problem

**Comment by TahaTesser** [comment]
Hi @mrkoLeo 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by mrkoLeo** [comment]
I wrote a demo that does not depend on FlutterBoost, This bug does not exist. 
Excuse me
