### ISSUE TITLE
Check if template_manifest.json exists before attempting to read it, exit with corrupt SDK message if missing

### ISSUE THREAD

**Issue by alxx28** [flutter/flutter#64221]
I am triyng to create an app with flutter, but I am getting the following:
## command

flutter --no-color create --template app --description A new Flutter application. --org com.example --no-androidx flutter_app

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\flutter\packages\flutter_tools\templates\template_manifest.json' (OS Error: El sistema no puede encontrar el archivo especificado.
, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#5      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#6      CreateCommand._computeTemplateManifest (package:flutter_tools/src/commands/create.dart:295:37)
#7      CreateCommand.templateManifest (package:flutter_tools/src/commands/create.dart:281:58)
#8      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:779:25)
#9      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:665:29)
#10     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:435:37)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [VersiÃ³n 10.0.18362.1016], locale es-CO)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (7 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Alex-PC\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.0)
    • VS Code at C:\Users\Alex-PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by jmagman** [comment]
Another `C:\flutter` install.

**Comment by jonahwilliams** [comment]
I wonder if this is actually a permission issue? or perhaps it is a partial install. At any rate we should check for this file's existence and exit with an error in case
