### ISSUE TITLE
[Cocoon Backend] Failed to add commit 0fa1de3c78a0b2a61fe6aa5d1f5d312b6d530637

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#64265]
The latest github commit is not showing on the build dashboard. Found this error on Cocoon backend:

```
Failed to add commit 0fa1de3c78a0b2a61fe6aa5d1f5d312b6d530637: Invalid argument(s): Error while encoding entity (Bad state: Property validation failed for property startTimestamp while trying to serialize entity of kind Task. , #0      _ModelDescription._encodeProperty (package:gcloud/src/db/model_db_impl.dart:428:7)
#1      _ModelDescription.encodeModel.<anonymous closure> (package:gcloud/src/db/model_db_impl.dart:413:7)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#3      _ModelDescription.encodeModel (package:gcloud/src/db/model_db_impl.dart:412:34)
#4      ModelDBImpl.toDatastoreEntity (package:gcloud/src/db/model_db_impl.dart:109:31)
#5      _commitHelper (package:gcloud/src/db/db.dart:398:44)
#6      Transaction.commit (package:gcloud/src/db/db.dart:104:14)
#7      RefreshGithubCommits._saveData.<anonymous closure> (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:124:29)
#8      DatastoreService.withTransaction.<anonymous closure>.<anonymous closure> (package:cocoon_service/src/service/datastore.dart:293:31)
#9      DatastoreDB.withTransaction.<anonymous closure> (package:gcloud/src/db/db.dart:302:32)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#18     GrpcDatastoreImpl.beginTransaction (package:appengine/src/grpc_api_impl/datastore_impl.dart)
<asynchronous suspension>
#19     DatastoreDB.withTransaction (package:gcloud/src/db/db.dart:299:10)
#20     DatastoreService.withTransaction.<anonymous closure> (package:cocoon_service/src/service/datastore.dart:292:16)
#21     RetryOptions.retry (package:retry/retry.dart:130:24)
#22     runTransactionWithRetries (package:cocoon_service/src/service/datastore.dart:47:12)
#23     DatastoreService.withTransaction (package:cocoon_service/src/service/datastore.dart:291:11)
#24     RefreshGithubCommits._saveData (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:121:25)
<asynchronous suspension>
#25     RefreshGithubCommits.get (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:81:13)
<asynchronous suspension>
#26     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
#27     _rootRun (dart:async/zone.dart:1190:13)
#28     _CustomZone.run (dart:async/zone.dart:1093:19)
#29     _runZoned (dart:async/zone.dart:1630:10)
#30     runZoned (dart:async/zone.dart:1550:10)
#31     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#32     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:134:19)
#33     _rootRun (dart:async/zone.dart:1190:13)
#34     _CustomZone.run (dart:async/zone.dart:1093:19)
#35     _runZoned (dart:async/zone.dart:1630:10)
#36     runZoned (dart:async/zone.dart:1550:10)
#37     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:133:11)
<asynchronous suspension>
#38     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:127:23)
#39     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#40     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#41     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#42     _rootRun (dart:async/zone.dart:1190:13)
#43     _CustomZone.run (dart:async/zone.dart:1093:19)
#44     _runZoned (dart:async/zone.dart:1630:10)
#45     runZonedGuarded (dart:async/zone.dart:1618:12)
#46     runZoned (dart:async/zone.dart:1547:12)
#47     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#48     fork (package:gcloud/service_scope.dart:104:30)
#49     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#50     _Closure.call (dart:core-patch/function.dart)
#51     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#52     _rootRunUnary (dart:async/zone.dart:1198:47)
#53     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#57     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#58     _StreamController._add (dart:async/stream_controller.dart:682:7)
#59     _StreamController.add (dart:async/stream_controller.dart:624:5)
#60     _HttpServer._handleRequest (dart:_http/http_impl.dart:2874:19)
#61     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2629:19)
#62     _rootRunUnary (dart:async/zone.dart:1198:47)
#63     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#67     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#68     _StreamController._add (dart:async/stream_controller.dart:682:7)
#69     _StreamController.add (dart:async/stream_controller.dart:624:5)
#70     _HttpParser._headersEnd (dart:_http/http_parser.dart:393:19)
#71     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#72     _HttpParser._parse (dart:_http/http_parser.dart:323:7)
#73     _rootRunUnary (dart:async/zone.dart:1198:47)
#74     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#75     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#76     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#77     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#78     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#79     _StreamController._add (dart:async/stream_controller.dart:682:7)
#80     _StreamController.add (dart:async/stream_controller.dart:624:5)
#81     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#82     _rootRunUnary (dart:async/zone.dart:1206:13)
#83     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#84     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#85     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#86     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#87     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#88     _StreamController._add (dart:async/stream_controller.dart:682:7)
#89     _StreamController.add (dart:async/stream_controller.dart:624:5)
#90     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#91     _Closure.call (dart:core-patch/function.dart)
#92     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#93     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#94     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#95     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#96     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
).
```

**Comment by digiter** [comment]
Rolled backend back to the previous version.

**Comment by christopherfujino** [comment]
> Rolled backend back to the previous version. The incident is mitigated.

thanks
