### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by AmanMandloi** [flutter/flutter#64337]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:47:7)
<asynchronous suspension>
#1      AppInspector.contextId (package:dwds/src/debugging/inspector.dart:156:50)
#2      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:497:26)
#3      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:98:40)
<asynchronous suspension>
#4      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#5      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:184:37)
<asynchronous suspension>
#6      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:151:23)
#7      DebugService.start (package:dwds/src/services/debug_service.dart:143:55)
#8      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:190:25)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale en_IN)
    • Flutter version 1.21.0-9.1.pre at /home/aman/snap/flutter/common/flutter
    • Framework revision be9bc8cb39 (3 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/aman/Android/Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/aman/Android/Sdk
    • Java binary at: /snap/android-studio/91/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/91/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 83.0.4103.116

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: be9bc8cb3942bda5d8ef4e44b44616c470625e18

**Comment by pedromassangocode** [comment]
Hi @AmanMandloi 
I see there's an open issue addressing the case you described (https://github.com/flutter/flutter/issues/60495).
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
