### ISSUE TITLE
Bug: Hot Restart returns null at initState

### ISSUE THREAD

**Issue by Umbrien** [flutter/flutter#64384]
## Problem
I need a card with a row of checkboxes. On tap on each checkbox, I need to know if checkboxes are checked and then do some stuff. You can see three additional classes here: for checkbox, row, and card. With hot restart I except to normally restart the app, however, it throws an exception. At first load and after rebuilding this page with BottomNavigationBar it works fine.

## Steps to Reproduce
1. Update the files as follows:
**main.dart**:
```Dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: MyCard(),
      ),
    );
  }
}

class MyCheckBox extends StatefulWidget {
  final String weekDay;
  final Function onTap;
  bool _isChecked = false;

  bool get isChecked => this._isChecked;

  MyCheckBox({this.weekDay, this.onTap});

  @override
  _MyCheckBoxState createState() => _MyCheckBoxState();
}

class _MyCheckBoxState extends State<MyCheckBox> {
  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: widget.onTap,
      child: Text(widget.weekDay),
    );
  }
}

class MyCheckBoxRow extends StatefulWidget {
  final Function onTap;
  List<MyCheckBox> checkBoxes;

  List<int> get activeDays {
    List<int> _activeDays = <int>[];
    for (MyCheckBox day in this.checkBoxes) {
      if (day.isChecked) _activeDays.add(this.checkBoxes.indexOf(day));
    }
    return _activeDays;
  }

  MyCheckBoxRow({this.onTap});

  @override
  _MyCheckBoxRowState createState() => _MyCheckBoxRowState();
}

class _MyCheckBoxRowState extends State<MyCheckBoxRow> {
  @override
  void initState() {
    super.initState();
    widget.checkBoxes = [
      MyCheckBox(weekDay: 'Monday', onTap: widget.onTap),
      MyCheckBox(weekDay: 'Tuesday', onTap: widget.onTap),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Row(children: widget.checkBoxes);
  }
}

class MyCard extends StatefulWidget {
  MyCheckBoxRow _myCheckBoxRow;

  List<int> get activeDays => this._myCheckBoxRow.activeDays;

  @override
  _MyCardState createState() => _MyCardState();
}

class _MyCardState extends State<MyCard> {
  @override
  void initState() {
    super.initState();
    widget._myCheckBoxRow =
        MyCheckBoxRow(onTap: () => print(widget.activeDays));
  }

  @override
  Widget build(BuildContext context) {
    return widget._myCheckBoxRow;
  }
}

```
2. Run `flutter run`.
3. Run Hot Restart

**Expected results:** 
App will normally restart

**Actual results:** 
I got this exception
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞══════════════════════════
The following assertion was thrown building MyCard(dirty, state: _MyCardState#114a9):
A build function returned null.
The offending widget is:
  MyCard
Build functions must never return null.
```

<details>
  <summary>Logs</summary>

`flutter run --verbose`
```
[  +95 ms] executing: [/home/j/Downloads/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +22 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] bbfbf1770cca2da7c82e887e4e4af910034800b6
[        ] executing: [/home/j/Downloads/flutter/] git tag --contains HEAD
[ +162 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.2
[   +6 ms] executing: [/home/j/Downloads/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/j/Downloads/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +35 ms] executing: [/home/j/Downloads/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] executing: /home/j/Android/Sdk/platform-tools/adb devices -l
[  +27 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[   +6 ms] /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +15 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +155 ms] Generating /home/j/AndroidStudioProjects/buggy_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +17 ms] ro.hardware = ranchu
[  +10 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +24 ms] Starting incremental build...
[   +1 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +3 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +5 ms] /home/j/Downloads/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/j/Downloads/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/j/Downloads/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tools.PROEFG/flutter_tool.CIGWAC/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[   +7 ms] executing: /home/j/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/j/AndroidStudioProjects/buggy_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +3 ms] Exit code 0 from: /home/j/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/j/AndroidStudioProjects/buggy_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.pinkertone.buggy_app" (Raw: "com.pinkertone.buggy_app")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="buggy_app" (Raw: "buggy_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.pinkertone.buggy_app.MainActivity" (Raw: "com.pinkertone.buggy_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +7 ms] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +10 ms] Exit code 0 from: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           08-22 13:38:33.049 D/MDnsDS  ( 1183): Going to poll with pollCount 1
[   +1 ms] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[   +9 ms] Exit code 0 from: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           08-22 13:38:33.049 D/MDnsDS  ( 1183): Going to poll with pollCount 1
[   +4 ms] <- compile package:buggy_app/main.dart
[   +9 ms] executing: /home/j/Android/Sdk/platform-tools/adb version
[   +4 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as /home/j/Android/Sdk/platform-tools/adb
[   +2 ms] executing: /home/j/Android/Sdk/platform-tools/adb start-server
[   +3 ms] Building APK
[  +24 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +2 ms] Using gradle from /home/j/AndroidStudioProjects/buggy_app/android/gradlew.
[        ] /home/j/AndroidStudioProjects/buggy_app/android/gradlew mode: 33261 rwxr-xr-x.
[  +10 ms] executing: /home/j/Downloads/android-studio/jre/bin/java -version
[  +45 ms] Exit code 0 from: /home/j/Downloads/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +3 ms] executing: [/home/j/AndroidStudioProjects/buggy_app/android/] /home/j/AndroidStudioProjects/buggy_app/android/gradlew -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=/home/j/AndroidStudioProjects/buggy_app/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +715 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[  +65 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[  +99 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[  +96 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] Compatible side by side NDK version was not found.
[        ] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:assembleDebug
[        ] BUILD SUCCESSFUL in 927ms
[        ] 31 actionable tasks: 4 executed, 27 up-to-date
[ +349 ms] Running Gradle task 'assembleDebug'... (completed in 1.4s)
[  +32 ms] calculateSha: LocalDirectory: '/home/j/AndroidStudioProjects/buggy_app/build/app/outputs/flutter-apk'/app.apk
[  +30 ms] calculateSha: reading file took 29us
[ +453 ms] calculateSha: computing sha took 452us
[   +3 ms] ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing: /home/j/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/j/AndroidStudioProjects/buggy_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +3 ms] Exit code 0 from: /home/j/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/j/AndroidStudioProjects/buggy_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.pinkertone.buggy_app" (Raw: "com.pinkertone.buggy_app")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="buggy_app" (Raw: "buggy_app")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.pinkertone.buggy_app.MainActivity" (Raw: "com.pinkertone.buggy_app.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.pinkertone.buggy_app
[ +301 ms] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.pinkertone.buggy_app
[ +118 ms] package:com.pinkertone.buggy_app
[   +1 ms] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.pinkertone.buggy_app.sha1
[   +5 ms] a58c13ec77011fec61d0774d0bb42147aa42f71b
[        ] Latest build already installed.
[        ] Android SDK built for x86 startApp
[   +1 ms] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.pinkertone.buggy_app/com.pinkertone.buggy_app.MainActivity
[ +279 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.pinkertone.buggy_app/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +254 ms] Observatory URL on device: http://127.0.0.1:34671/VaAtXh5Hlm0=/
[   +1 ms] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:34671
[   +4 ms] 39905
[        ] Forwarded host port 39905 to device port 34671 for Observatory
[   +6 ms] Caching compiled dill
[  +31 ms] Connecting to service protocol: http://127.0.0.1:39905/VaAtXh5Hlm0=/
[ +297 ms] Successfully connected to service protocol: http://127.0.0.1:39905/VaAtXh5Hlm0=/
[        ] Waiting for Android SDK built for x86 to report its views...
[   +6 ms] Waiting for Android SDK built for x86 to report its views... (completed in 5ms)
[   +6 ms] DevFS: Creating new filesystem on the device (null)
[  +23 ms] DevFS: Created new filesystem on the device (file:///data/data/com.pinkertone.buggy_app/code_cache/buggy_appQZUMLG/buggy_app/)
[   +2 ms] Updating assets
[  +77 ms] Syncing files to device Android SDK built for x86...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:buggy_app/main.dart 231f2116-547a-4b45-be05-9816879cc54c
[        ] <- 231f2116-547a-4b45-be05-9816879cc54c
[  +59 ms] Updating files
[  +92 ms] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86... (completed in 155ms)
[        ] Synced 0.9MB.
[        ] <- accept
[   +2 ms] Connected to _flutterView/0xb4034810.
[        ] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:39905/VaAtXh5Hlm0=/
[+8095 ms] Starting incremental build...
[   +2 ms] Skipping target: gen_localizations
[   +1 ms] complete
[   +4 ms] Performing hot restart...
[  +14 ms] Scanned through 479 files in 8ms
[        ] Syncing files to device Android SDK built for x86...
[        ] Scanning asset files
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:buggy_app/main.dart 7c60ca04-5ade-41ee-b782-68a9671fcb80
[        ] <- 7c60ca04-5ade-41ee-b782-68a9671fcb80
[  +49 ms] Updating files
[ +353 ms] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86... (completed in 405ms)
[        ] Synced 21.1MB.
[        ] <- accept
[   +5 ms] error: HttpException: Connection closed while receiving data, uri = http://127.0.0.1:39905/VaAtXh5Hlm0=/
[ +133 ms] E/flutter (17366): [ERROR:flutter/shell/common/shell.cc(209)] Dart Error: Can't load Kernel binary: Invalid kernel binary: Indicated size is invalid.
[        ] E/flutter (17366): [ERROR:flutter/shell/common/engine.cc(205)] Could not prepare to run the isolate.
[        ] E/flutter (17366): [ERROR:flutter/shell/common/engine.cc(144)] Engine not prepare and launch isolate.
[  +64 ms] Performing hot restart... (completed in 624ms)
[        ] Restarted application in 634ms.
[  +10 ms] Application finished.
[   +5 ms] hot restart failed to complete: _flutter.runInView: (-32000) Could not run configuration in engine.

[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1528:11)
           <asynchronous suspension>
           #2      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1584:13)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
           #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
           #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
           #8      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
           #9      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
           #10     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
           #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
           #15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
           #16     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
           #17     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
           #18     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
           #19     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
           #20     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
           #21     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:256:17)
           #22     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:242:5)
           #23     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
           #24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
           #25     _rootRunUnary (dart:async/zone.dart:1198:47)
           #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
           #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
           #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
           #30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
           #31     _StreamController._add (dart:async/stream_controller.dart:682:7)
           #32     _StreamController.add (dart:async/stream_controller.dart:624:5)
           #33     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
           #34     _rootRunUnary (dart:async/zone.dart:1206:13)
           #35     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
           #37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
           #38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
           #39     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
           #40     _StreamController._add (dart:async/stream_controller.dart:682:7)
           #41     _StreamController.add (dart:async/stream_controller.dart:624:5)
           #42     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
           #43     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
           #44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +6 ms] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 forward --list
[   +5 ms] Exit code 0 from: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 forward --list
[        ] emulator-5554 tcp:39905 tcp:34671
[   +1 ms] executing: /home/j/Android/Sdk/platform-tools/adb -s emulator-5554 forward --remove tcp:39905
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 1

```

`flutter analyze`:
```
Analyzing buggy_app...                                          

   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MyCheckBox._isChecked • lib/main.dart:18:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MyCheckBoxRow.checkBoxes • lib/main.dart:41:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MyCard._myCheckBoxRow • lib/main.dart:75:7 • must_be_immutable

```

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.2 at /home/j/Downloads/flutter
    • Framework revision bbfbf1770c (9 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/j/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/j/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/j/Downloads/android-studio
    • Flutter plugin version 48.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment]
Hi @Umbrien 
Not sure what are you trying to achieve but I suggest you to try the code suggested on https://github.com/flutter/flutter/issues/64384#issuecomment-678675107 since improves your code and makes it a lot simpler. It is recommended to setup your widgets inside the `Build` method since it guarantees that your widgets will be read in the build/layout phase of your Stateful/Stateless widget.

Closing this as this is not an issue with Flutter itself. If you disagree comment and I will reopen if necessary.
Thank you.
