### ISSUE TITLE
Exception: Failed to compile application for the Web.

### ISSUE THREAD

**Issue by belolap** [flutter/flutter#64390]
I can build my application for web on local machine, but can't build inside docker container with beta channel with common error message:

```Exception: Failed to compile application for the Web.```

In local machine I do `flutter clean`, `flutter upgrade`, remove `pubspeck.lock` and do `flutter pub get`. App builded sucessful. Versions in `flutter doctor` are same.

`flutter doctor` output inside docker container:
```
$ flutter doctor -v
[✓] Flutter (Channel unknown, 1.21.0-9.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.1.pre at /home/cirrus/sdks/flutter
    • Framework revision be9bc8cb39 (4 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium-browser

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • unknown
```

Exception with stacktrace from `flutter build web --verbose`:

```
[   +3 ms] Exception: Failed to compile application for the Web.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:79:5)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
           #20     _rootRunUnary (dart:async/zone.dart:1198:47)
           #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #26     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
           #27     _rootRunUnary (dart:async/zone.dart:1198:47)
           #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #35     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
           #36     _rootRunUnary (dart:async/zone.dart:1198:47)
           #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #42     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
           #43     _rootRunUnary (dart:async/zone.dart:1198:47)
           #44     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #45     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #47     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #48     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #49     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #50     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #51     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
           #52     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #53     _rootRunBinary (dart:async/zone.dart:1214:47)
           #54     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #55     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #56     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #57     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #58     Future._completeError (dart:async/future_impl.dart:537:5)
           #59     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
           #60     Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart)
           #61     _rootRunUnary (dart:async/zone.dart:1198:47)
           #62     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #63     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #65     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #66     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #67     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
           #68     _rootRunUnary (dart:async/zone.dart:1198:47)
           #69     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #70     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #71     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #72     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #73     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #74     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #75     _rootRun (dart:async/zone.dart:1190:13)
           #76     _CustomZone.run (dart:async/zone.dart:1093:19)
           #77     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #78     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #79     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #80     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #81     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #82     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

Full log of build: [raw.txt](https://github.com/flutter/flutter/files/5112445/raw.txt). 

How can I fix build for web?

**Comment by pedromassangocode** [comment]
Hi @belolap 
Also please make sure you are using a valid Flutter channel.

> [✓] Flutter (Channel unknown, 1.21.0-9.1.pre, on Linux, locale en_US.UTF-8)

This line does not shows a valid Flutter channel that we can use with `flutter channel <channel_name>` to reproduce the issue.
Thank you

**Comment by belolap** [comment]
I'm on beta channel, and ok, I will doble check.

I can build in my docker container new empty application created with `flutter create` without any problems. I can build my empty application without any widgets in code. But when I uncomment interface in app's code the error is appear. So now I'm not sure if it is flutter bug.

I have large app and now I step-by-step try to find widget which broke build.

If you don't want that this issue be open we can close it, and then I found someting I can reopen it with details.

**Comment by pedromassangocode** [comment]
Hi @belolap 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by antdementyev** [comment]
I have the same issue. Local on mac without any problem, in docker container:
```
[   +3 ms] Target dart2js failed: Exception:
[  +15 ms] Compiling lib/main.dart for the Web... (completed in 118.8s)
[   +1 ms] "flutter web" took 119,986ms.
[   +5 ms] Exception: Failed to compile application for the Web.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWeb (package:flutter_tools/src/web/compile.dart:85:5)
           <asynchronous suspension>
           #2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:91:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```
@belolap have you managed to fix it?

**Comment by belolap** [comment]
Yes and no :)

I do full rewrite my app and problem gone.

**Comment by hamad22h** [comment]
في اثنين، 21 يونيو، 2021 في 8:12 ص، كتب Gennady Kovalev <
***@***.***>:
