### ISSUE TITLE
Crash report on flutter run

### ISSUE THREAD

**Issue by steowens** [flutter/flutter#64470]
First time using flutter run on brand new app after installing on Ubuntu 18.04.  See attached log.

[flutter_01.log](https://github.com/flutter/flutter/files/5119150/flutter_01.log)

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

FormatException: FormatException: Missing extension byte (at offset 102)

```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1887:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#11     _StreamController._add (dart:async/stream_controller.dart:682:7)
#12     _StreamController.add (dart:async/stream_controller.dart:624:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2043:41)
#14     _rootRunUnary (dart:async/zone.dart:1206:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#20     _StreamController._add (dart:async/stream_controller.dart:682:7)
#21     _StreamController.add (dart:async/stream_controller.dart:624:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1579:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1075:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.1.pre at /home/steve/snap/flutter/common/flutter
    • Framework revision be9bc8cb39 (6 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/android-sdk-linux
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    • ANDROID_HOME = /usr/local/android-sdk-linux/tools
    ✗ No valid Android SDK platforms found in /usr/local/android-sdk-linux/platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at /snap/android-studio/91/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.48.0)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 102)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1887:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
      #5      _rootRunUnary (dart:async/zone.dart:1198:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:682:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:624:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2043:41)
      #14     _rootRunUnary (dart:async/zone.dart:1206:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:682:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:624:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1579:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1075:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 3 categories.

**Comment by sidrao2006** [comment]
Hey @steowens , please try installing the Android SDK. `flutter doctor` also crashed

**Comment by jonahwilliams** [comment]
@steowens what sort of device were you attempting to run with?

**Comment by steowens** [comment]
It was an HP laptop.

**Comment by steowens** [comment]
I have kind of given up using this software so I probably won't be watching this thread.  Perhaps I will pick it up sometime in the future.

**Comment by jonahwilliams** [comment]
OK. If you're able to file a more complete bug report in the future please do
