### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: Acceso denegado., errno = 5

### ISSUE THREAD

**Issue by taneto-OG** [flutter/flutter#64481]
## Command
```
flutter run --verbose
```

## Steps to Reproduce
1. on VScode: flutter build web
2.                    flutter run --verbose

## Logs
FileSystemException: Exists failed, OS Error: Acceso denegado.
, errno = 5
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:126:11)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#4      writeBundle (package:flutter_tools/src/bundle.dart:235:13)
#5      WebDevFS.update (package:flutter_tools/src/build_runner/devfs_web.dart:801:15)
#6      _ResidentWebRunner._updateDevFS (package:flutter_tools/src/build_runner/resident_web_runner.dart:694:54)
<asynchronous suspension>
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:481:47)
<asynchronous suspension>
#8      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart)
#9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#10     _rootRun (dart:async/zone.dart:1190:13)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _runZoned (dart:async/zone.dart:1630:10)
#13     runZonedGuarded (dart:async/zone.dart:1618:12)
#14     runZoned (dart:async/zone.dart:1547:12)
#15     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#16     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:451:20)
<asynchronous suspension>
#17     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:602:37)
<asynchronous suspension>
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:909:18)
#19     _rootRunUnary (dart:async/zone.dart:1198:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
```
```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [VersiÃ³n 10.0.18363.1016], locale es-CL)
    • Flutter version 1.21.0-9.1.pre at C:\srx\flutter
    • Framework revision be9bc8cb39 (6 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\netot\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.1)
    • VS Code at C:\Users\netot\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.6.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6
### Plugins
android_intent-0.3.7+2
firebase_messaging-6.0.16
flutter_inappbrowser-2.0.2
flutter_plugin_android_lifecycle-1.0.8
fluttertoast-4.0.1
geolocator-5.3.2+2
google_api_availability-2.0.4
google_map_location_picker-3.3.3
google_maps_flutter-0.5.29
location-3.0.2
location_permissions-3.0.0+1
location_web-1.0.0
package_info-0.4.1
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
screen-0.0.5
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2+1
video_player-0.10.12
video_player_web-0.1.3+2
wakelock-0.1.4+2
webview_flutter-0.3.22+1

**Comment by Abhishek01039** [comment]
Hi @taneto-OG 
Don't copy .packages over from one machine to another. (It should be in .gitignore if using git.)
Instead, run flutter packages get on the mac, and it will recreate .packages.
Thanks.

-

**Comment by darshankawar** [comment]
Hi @taneto-OG,
There's similar open isssue describing your case, [50880](https://github.com/flutter/flutter/issues/50880).
Please follow-up there for updates and any questions.
Closing this as duplicate.
