### ISSUE TITLE
Potential race condition when launching browser in web benchmarks

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#64499]
@Hixie reports:

> how is https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/browser.dart#L117 not a race condition? we launch chrome, then as fast as possible we try to connect and read the tabs, but wouldn't it be normal for the tab to not yet have loaded if we just happen to get scheduled more aggressively than chrome?

[Sample log](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8871468306137185040/+/steps/run_test.dart_for_web_integration_tests_shard_and_subshard_None/0/stdout?format=raw). Interesting part:

```
Launching Chromium 82.0.4059.0 

[CHROME]: Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[CHROME]: 
[CHROME]: DevTools listening on ws://127.0.0.1:8081/devtools/browser/6ab694fb-e350-4703-9b79-48d3c6bb0a77
Connecting to DevTools: http://localhost:8081
Unhandled exception:
Bad state: No element
#0      Iterable.single (dart:core/iterable.dart:558:25)
#1      _connectToChromeDebugPort (package:flutter_devicelab/framework/browser.dart:272:30)
<asynchronous suspension>
#2      Chrome.launch (package:flutter_devicelab/framework/browser.dart:117:31)
<asynchronous suspension>
#3      evalTestAppInChrome (file:///b/s/w/ir/k/flutter/dev/bots/browser.dart:46:27)
<asynchronous suspension>
#4      _runWebStackTraceTest (file:///b/s/w/ir/k/flutter/dev/bots/test.dart:792:31)
<asynchronous suspension>
#5      _runWebIntegrationTests (file:///b/s/w/ir/k/flutter/dev/bots/test.dart:746:9)
<asynchronous suspension>
#6      _runFromList (file:///b/s/w/ir/k/flutter/dev/bots/test.dart:1475:22)
#7      selectShard (file:///b/s/w/ir/k/flutter/dev/bots/test.dart:1450:62)
#8      main (file:///b/s/w/ir/k/flutter/dev/bots/test.dart:123:11)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

We've been assuming that when we specify a URL to launch chrome with we don't go through `about:blank`, but perhaps that was a false assumption.

**Comment by jonahwilliams** [comment]
Could be happening in the flutter tool too. The correct fix would probably to add some polling logic until we locate the correct tab

**Comment by yjbanov** [comment]
As there were no reoccurrences of this issue since 2020, closing for now.
