### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument (URI scheme not allowed): "file:///C:/Users/xxxx/AndroidStudioProjects/yyyy/lib/charts/chart_1.dart"

### ISSUE THREAD

**Issue by predragcvetkovski** [flutter/flutter#64492]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument (URI scheme not allowed): "file:///C:/Users/xxxx/AndroidStudioProjects/yyyy/lib/charts/chart_1.dart"
```
#0      DartUri._recordAbsoluteUri (package:dwds/src/utilities/dart_uri.dart:86:7)
#1      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:60:9)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:88:19)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:184:37)
<asynchronous suspension>
#5      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:151:23)
#6      DebugService.start (package:dwds/src/services/debug_service.dart:143:55)
#7      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:190:25)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.21.0-9.1.pre at C:\src\flutter
    • Framework revision be9bc8cb39 (6 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\xxxx\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 84.0.522.49

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: e606910f28be51c8151f6169072afe3b3a8b3c5e
### Plugins
path_provider_linux-0.0.1+2
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2+1

**Comment by predragcvetkovski** [comment]
Error occurs after the latest upgrade to Flutter version 1.21.0-9.1.pre, causing a blank screen in Chrome

**Comment by darshankawar** [comment]
Hi @predragcvetkovski,
Can you try [this](https://github.com/flutter/flutter/issues/59924#issuecomment-678287123) solution and see if it works for you ?
Thanks.

**Comment by predragcvetkovski** [comment]
> Hi @predragcvetkovski,
> Can you try [this](https://github.com/flutter/flutter/issues/59924#issuecomment-678287123) solution and see if it works for you ?
> Thanks.

thanks @darshankawar, I've tried the fixes listed, it didn't help, however the cause was actually an outdated package path starting with file:///C:/Users/, once changed to package: the error was resolved. This path error was crashing the web support only, while the Android emulator was working fine.
