### ISSUE TITLE
Back Gesture away from persistent bottom sheet = dead Gallery

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#6451]
1.  Open Gallery > Persistent Bottom Sheet
2.  Click the button to open the sheet.
3.  With the sheet still showing, back-gesture back to the main page.
4.  Click on anything else, your routes are now in a bad state, app will go black or other badness.

See video.
https://youtu.be/kI-dzP66omQ

**Comment by eseidelGoogle** [comment]
Interestingly the modal bottom sheet knows how to close itself, and the snackbar doesn't cause this bug.

**Comment by Hixie** [comment]
Do you get any exceptions in checked mode?

**Comment by mpcomplete** [comment]
The sheet adds a LocalHistoryEntry to the navigator. Normally, if you hit `Back` with a sheet showing, it will dismiss the sheet first. I wonder if we should disallow the back gesture with the sheet showing? If not, we might need to dismiss the LocalHistoryEntry before disposing of the route being popped.

**Comment by eseidelGoogle** [comment]
```
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
setState() called after dispose(): _PersistentBottomSheetDemoState(120093726; _StateLifecycle.defunct; not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 580 pos 12: '_from.subtreeContext
!= null' is not true.
When the exception was thrown, this was the stack:
#2      HeroController._updateQuest (package:flutter/src/widgets/heroes.dart:580:12)
#3      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:648:15)
#4      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:591:9)
#5      _beginFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:69)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by eseidelGoogle** [comment]
The first setState exception happened during/right-after the back gesture iirc.  The rest happened when I tried to navigate somewhere else.
