### ISSUE TITLE
Not able to create new project in flutter through cmd

### ISSUE THREAD

**Issue by shivdevelop** [flutter/flutter#64537]
## Steps to Reproduce

1. ...run flutter create app_name in cmd
2. ...then wait for the app to get created
3. ...after some times shows error flutter has exited unexpectedly

## Logs

```Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter create flutter_complete_guide

## exception

FileSystemException: FileSystemException: readSync failed, path = 'E:\flutter\packages\flutter_tools\templates\template_manifest.json' (OS Error: Data error (cyclic redundancy check).
, errno = 23)

#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:760:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#5      CreateCommand._computeTemplateManifest (package:flutter_tools/src/commands/create.dart:295:37)
#6      CreateCommand.templateManifest (package:flutter_tools/src/commands/create.dart:281:58)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:779:25)
#8      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:665:29)
#9      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:435:37)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#18     FlutterProject.organizationNames (package:flutter_tools/src/project.dart)
#19     _rootRunUnary (dart:async/zone.dart:1198:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#27     IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart)
#28     _rootRunUnary (dart:async/zone.dart:1198:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#34     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#35     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#36     IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart)
#37     _rootRunUnary (dart:async/zone.dart:1198:47)
#38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#39     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#41     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#42     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#43     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#44     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#45     IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart)
#46     _rootRunUnary (dart:async/zone.dart:1198:47)
#47     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#51     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#52     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#53     _rootRun (dart:async/zone.dart:1190:13)
#54     _CustomZone.run (dart:async/zone.dart:1093:19)
#55     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#56     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.20.0 at E:\flutter
    • Framework revision 916c3ac648 (3 weeks ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by Abhishek01039** [comment]
Duplication of https://github.com/flutter/flutter/issues/61264

**Comment by markusaksli-nc** [comment]
Hi @shivdevelop 
Could you see if https://github.com/flutter/flutter/issues/61264#issuecomment-656898218 can solve this for you?
Thank you

**Comment by shivdevelop** [comment]
Thanks @Abhishek01039 @markusaksli-nc, did a error check on HDD now working fine.
