### ISSUE TITLE
Flutter Analyzer server hangs at 100% CPU when typing map getter 

### ISSUE THREAD

**Issue by sersorrel** [flutter/flutter#64566]
## Steps to Reproduce

1. Open Android Studio
2. Make some minor code modifications
3. Congratulations, the analysis server has hung at 100% CPU and now you don't get code analysis or completions

Specifically, removing a `migrations` getter from one of the `Model` classes in `lib/db.dart` then typing `Map<int, List<String>> get` seems to reliably cause the hang: [monch.zip](https://github.com/flutter/flutter/files/5124987/monch.zip)

## Logs

Logs from the analysis server can be found here (too large for GitHub apparently): https://sorrel.sh/public/d056f016-2e69-43b7-9929-9b68ef96e81d.txt

```
$ flutter doctor -v
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.21.0-9.1.pre at /home/ash/snap/flutter/common/flutter
    • Framework revision be9bc8cb39 (7 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ash/Android/Sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/ash/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 4.0)
    • Android Studio at /home/ash/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • moto g 8 power (mobile) • ZY2277ZRN5 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @sersorrel 
I can reproduce the issue using your code sample 

![OwUOLpc](https://user-images.githubusercontent.com/48603081/91282999-af9bcf00-e7a7-11ea-902a-d6beece37f47.png)

<details> 
<summary>logs</summary> 

```
taha@pop-os:~/AndroidStudioProjects/monch$ flutter analyze
Running "flutter pub get" in monch...                               0.3s
Analyzing monch...                                                      

   info • This function has a return type of 'FutureOr<Meal>', but doesn't end with a return
          statement • lib/db.dart:122:16 • missing_return
   info • 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows for an
          improved text-scaling experience. This feature was deprecated after v1.19.0. •
          lib/main.dart:98:60 • deprecated_member_use

2 issues found. (ran in 3.2s)
taha@pop-os:~/AndroidStudioProjects/monch$ flutter analyze -v
[ +125 ms] executing: [/home/taha/Code/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 707f995de35bdf887169fcd39448b877cbcc8992
[        ] executing: [/home/taha/Code/flutter/] git tag --points-at HEAD
[  +11 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [/home/taha/Code/flutter/] git describe --match *.*.* --first-parent --long
--tags
[  +25 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.22.0-1.0.pre-60-g707f995de
[   +8 ms] executing: [/home/taha/Code/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/taha/Code/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +40 ms] executing: [/home/taha/Code/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +98 ms] Found plugin sqflite at /home/taha/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/
[ +103 ms] Found plugin sqflite at /home/taha/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+1/
[  +23 ms] Generating
/home/taha/AndroidStudioProjects/monch/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRe
gistrant.java
[ +329 ms] dart --disable-dart-dev
/home/taha/Code/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--disable-server-feature-completion --disable-server-feature-search --sdk
/home/taha/Code/flutter/bin/cache/dart-sdk
[  +17 ms] ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[        ] ==>
{"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["/home/taha/AndroidStudioProject
s/monch"],"excluded":[]}}
[   +1 ms] Analyzing monch...
[ +318 ms] <== {"event":"server.connected","params":{"version":"1.28.0","pid":14004}}
[  +25 ms] <== {"id":"1"}
[ +235 ms] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/pubspec.yaml","er
rors":[]}}
[   +6 ms] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/android/app/src/m
ain/AndroidManifest.xml","errors":[]}}
[        ] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/android/app/src/d
ebug/AndroidManifest.xml","errors":[]}}
[        ] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/android/app/src/p
rofile/AndroidManifest.xml","errors":[]}}
[  +74 ms] <== {"id":"2"}
[ +803 ms] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[   +3 ms] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/test/widget_test.
dart","errors":[]}}
[  +45 ms] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/lib/new_timeline_
entry_screen.dart","errors":[{"severity":"INFO","type":"TODO","location":{"file":"/home/taha/AndroidS
tudioProjects/monch/lib/new_timeline_entry_screen.dart","offset":2884,"length":33,"startLine":93,"sta
rtColumn":30},"message":"TODO: this only handles LTR
lists","code":"todo","hasFix":false},{"severity":"INFO","type":"TODO","location":{"file":"/home/taha/
AndroidStudioProjects/monch/lib/new_timeline_entry_screen.dart","offset":2157,"length":56,"startLine"
:79,"startColumn":22},"message":"TODO: this should be factored out into a separate
widget","code":"todo","hasFix":false},{"severity":"INFO","type":"TODO","location":{"file":"/home/taha
/AndroidStudioProjects/monch/lib/new_timeline_entry_screen.dart","offset":1663,"length":35,"startLine
":64,"startColumn":16},"message":"TODO: save the meal to the
database","code":"todo","hasFix":false},{"severity":"INFO","type":"TODO","location":{"file":"/home/ta
ha/AndroidStudioProjects/monch/lib/new_timeline_entry_screen.dart","offset":3035,"length":54,"startLi
ne":95,"startColumn":30},"message":"TODO: can be in a wrong state if you rotate the
screen","code":"todo","hasFix":false},{"severity":"INFO","type":"TODO","location":{"file":"/home/taha
/AndroidStudioProjects/monch/lib/new_timeline_entry_screen.dart","offset":2947,"length":58,"startLine
":94,"startColumn":30},"message":"TODO: this looks bad when the ListTile draws an ink
splash","code":"todo","hasFix":false}]}}
[   +5 ms] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/lib/timeline_page
.dart","errors":[]}}
[        ] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/lib/placeholder_p
age.dart","errors":[]}}
[        ] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/lib/db.dart","err
ors":[{"severity":"INFO","type":"HINT","location":{"file":"/home/taha/AndroidStudioProjects/monch/lib
/db.dart","offset":3122,"length":8,"startLine":122,"startColumn":16},"message":"This function has a
return type of 'FutureOr<Meal>', but doesn't end with a return statement.","correction":"Try adding a
return statement, or changing the return type to
'void'.","code":"missing_return","url":"https://dart.dev/tools/diagnostic-messages#missing_return","h
asFix":false}]}}
[   +1 ms] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/lib/main.dart","e
rrors":[{"severity":"INFO","type":"HINT","location":{"file":"/home/taha/AndroidStudioProjects/monch/l
ib/main.dart","offset":3203,"length":5,"startLine":98,"startColumn":60},"message":"'title' is
deprecated and shouldn't be used. Use \"label\" instead, as it allows for an improved text-scaling
experience. This feature was deprecated after v1.19.0..","correction":"Try replacing the use of the
deprecated member with the
replacement.","code":"deprecated_member_use","url":"https://dart.dev/tools/diagnostic-messages#deprec
ated_member_use","hasFix":false}]}}
[   +2 ms] <==
{"event":"analysis.errors","params":{"file":"/home/taha/AndroidStudioProjects/monch/lib/multi_select_
screen.dart","errors":[]}}
[        ] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[  +12 ms] Analyzing monch... (completed in 1.5s)
[   +6 ms]    info • This function has a return type of 'FutureOr<Meal>', but doesn't end with a
return
                     statement • lib/db.dart:122:16 • missing_return
[   +2 ms]    info • 'title' is deprecated and shouldn't be used. Use "label" instead, as it allows
for an
                     improved text-scaling experience. This feature was deprecated after v1.19.0. •
                     lib/main.dart:98:60 • deprecated_member_use
[   +5 ms] "flutter analyze" took 2,153ms.
[   +7 ms] 2 issues found. (ran in 1.5s)
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:186:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     AnalysisServer.dispose (package:flutter_tools/src/dart/analysis.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +150 ms] ensureAnalyticsSent: 147ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.1.pre at /home/taha/Code/flutter
    • Framework revision be9bc8cb39 (8 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.60, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-2.0.pre.60 at /home/taha/Code/flutter
    • Framework revision 707f995de3 (21 hours ago), 2020-08-25 04:51:03 -0700
    • Engine revision 8107b36c7b
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!


```

</details>

**Comment by Hixie** [comment]
cc @devoncarew should this be moved to the Dart team's issue database?

**Comment by darshankawar** [comment]
This probably belongs to dart-lang github repo, but I tried to replicate this on latest master using the code shared in original description, but don't see the spike in CPU usage:

![Screenshot 2022-04-19 at 5 05 42 PM](https://user-images.githubusercontent.com/67046386/163994970-47df1f44-aeb9-4119-a59a-f1c18869b797.png)

`Channel master, 2.13.0-0.0.pre.617`

@sersorrel Is this still an issue at your end ?

**Comment by sersorrel** [comment]
I haven't used flutter for the last couple of years, sorry – if it no longer reproduces for you, I'd assume it's fixed.

**Comment by darshankawar** [comment]
Based on my verification and above comment, I am going to close this as fixed. If anybody disagrees, write in comment and I'll reopen it.
