### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'adbPath' was called on null.Receiver: nullTried calling: adbPath

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#64601]
## Command
```
flutter create --template=app sample_flutter_app
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'adbPath' was called on null.
Receiver: null
Tried calling: adbPath
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AndroidDevices.getDiagnostics (package:flutter_tools/src/android/android_device_discovery.dart:90:21)
#2      DeviceManager.getDeviceDiagnostics (package:flutter_tools/src/device.dart:195:29)
#3      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:983:59)
<asynchronous suspension>
#4      Doctor._summaryText.<anonymous closure> (package:flutter_tools/src/doctor.dart:219:69)
#5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZonedGuarded (dart:async/zone.dart:1618:12)
#10     runZoned (dart:async/zone.dart:1547:12)
#11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#12     Doctor._summaryText (package:flutter_tools/src/doctor.dart:219:24)
<asynchronous suspension>
#13     Doctor.summary (package:flutter_tools/src/doctor.dart:206:31)
#14     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:478:30)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
```
```
[✓] Flutter (Channel unknown, 1.22.0-2.0.pre.75, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.22.0-2.0.pre.75 at /Users/flutter/.cocoon/flutter
    • Framework revision 0305c1f1c5 (24 minutes ago), 2020-08-25 20:21:03 -0400
    • Engine revision 0f80fff356
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ NoSuchMethodError: The getter 'adbPath' was called on null.
      Receiver: null
      Tried calling: adbPath
    • #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
      #1      AndroidDevices.getDiagnostics (package:flutter_tools/src/android/android_device_discovery.dart:90:21)
      #2      DeviceManager.getDeviceDiagnostics (package:flutter_tools/src/device.dart:195:29)
      #3      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:983:59)
      <asynchronous suspension>
      #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #5      _rootRun (dart:async/zone.dart:1190:13)
      #6      _CustomZone.run (dart:async/zone.dart:1093:19)
      #7      _runZoned (dart:async/zone.dart:1630:10)
      #8      runZonedGuarded (dart:async/zone.dart:1618:12)
      #9      runZoned (dart:async/zone.dart:1547:12)
      #10     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:191:9)
      #12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:290:47)
      #13     _doctorText (package:flutter_tools/runner.dart:236:18)
      #14     _handleToolError (package:flutter_tools/runner.dart:161:27)
      #15     _rootRunUnary (dart:async/zone.dart:1198:47)
      #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
      #19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #21     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
      #22     _rootRun (dart:async/zone.dart:1190:13)
      #23     _CustomZone.run (dart:async/zone.dart:1093:19)
      #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
      #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jmagman** [comment]
Crashed during `basic_material_app_ios__compile` devicelab test.
[basic_material_app_ios__compile_0305c1f_3.log](https://github.com/flutter/flutter/files/5126938/basic_material_app_ios__compile_0305c1f_3.log)

**Comment by jmagman** [comment]
@jonahwilliams Looks like #64524?  Weird that it's flaky though.
