### ISSUE TITLE
NestedScrollView in-range value overflow problem.

### ISSUE THREAD

**Issue by ahyangnb** [flutter/flutter#64614]
When I use a button to expand the content in the body of the NestedScrollView:
```

════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1608 pos 12: 'result': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      _NestedOuterBallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/nested_scroll_view.dart:1608:12)
#3      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:545:10)
#4      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:137:19)
#5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:798:5)
#6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:240:12)
...
The AnimationController notifying listeners was: AnimationController#2af9a(▶ 2856.655; for _NestedOuterBallisticScrollActivity)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1608 pos 12: 'result': is not true.
```

### Error file:
`/flutter/packages/flutter/lib/src/widgets/nested_scroll_view.dart`
Code line 1607：
```dart
assert(result); // since we tried to pass an in-range value, it shouldn't ever overflow
```

### My code snippet:
```dart
...
    return new Scaffold(
      backgroundColor: MyTheme.bodyBgColor(),
      body: new Expanded(
            child: new CupertinoScrollbar(
              child: new NestedScrollView(
                headerSliverBuilder: _sliverBuilder,
                body: new ListView(padding: EdgeInsets.all(0), children: body),
              ),
            ),
          ),
    );
...
```
The button is inside the body to expand the content.

### My environment:
```
q1deMacBook-Pro:~ q1$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.14.5 18F2059, locale
    zh-Hans-CN)
    • Flutter version 1.20.2 at /Users/q1/flutter
    • Framework revision bbfbf1770c (13 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/q1/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/q1/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

• No issues found!
```

**Comment by meritozh** [comment]
[Expanded](https://api.flutter.dev/flutter/widgets/Expanded-class.html): A widget that expands a child of a **Row, Column, or Flex** so that the child fills the available space.

**Comment by pedromassangocode** [comment]
Hi @ahyangnb 
Can you please provide a minimal complete reproducible code sample? I need a complete code that I can just copy/paste and run it.
Thank you

**Comment by ahyangnb** [comment]
> [Expanded](https://api.flutter.dev/flutter/widgets/Expanded-class.html): A widget that expands a child of a **Row, Column, or Flex** so that the child fills the available space.

I only took a screenshot of part of the code. In fact, my Expanded is placed in the Column, and the effect is the same without Expanded.

**Comment by ahyangnb** [comment]
Resolved, CupertinoScrollbar level nesting problem.

**Comment by ahyangnb** [comment]
Resolved, CupertinoScrollbar level nesting problem.
