### ISSUE TITLE
[tool_crash] FileSystemException: Getting current working directory failed, OS Error: Too many open files in system, errno = 23

### ISSUE THREAD

**Issue by jawad12345A** [flutter/flutter#64610]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Getting current working directory failed, OS Error: Too many open files in system, errno = 23
```
#0      _Directory.current (dart:io/directory_impl.dart:42:7)
#1      Directory.current (dart:io/directory.dart:154:25)
#2      LocalFileSystem.currentDirectory (package:file/src/backends/local/local_file_system.dart:44:60)
#3      ForwardingFileSystem.currentDirectory (package:file/src/forwarding/forwarding_file_system.dart:38:46)
#4      FlutterProject.current (package:flutter_tools/src/project.dart:86:63)
#5      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:931:81)
#6      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:350:21)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:880:11)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:785:33)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZoned (dart:async/zone.dart:1550:10)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:774:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
```
```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.70, on Mac OS X 10.15.6 19G2021, locale en-PK)
    • Flutter version 1.21.0-10.0.pre.70 at /Users/apple/Flutter/flutter
    • Framework revision 0629030a05 (13 days ago), 2020-08-13 00:01:03 -0400
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/apple/Documents/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (6 available)
    • TECNO KC3 (mobile)                 • 04826259AN002250                     • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max (mobile)         • F69EBB33-8BA3-4C9E-BA4B-BF41643F7D13 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)                   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 84.0.4147.135

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.0+22
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
### Plugins
barcode_scan-3.0.1
firebase_auth-0.15.5+3
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_crashlytics-0.1.3+3
firebase_messaging-6.0.16
flutter_facebook_login-3.0.0
flutter_image_compress-0.6.8
flutter_plugin_android_lifecycle-1.0.8
fluttertoast-3.1.3
geocoder-0.2.1
google_places_picker-2.1.0+2
google_sign_in-4.5.1
google_sign_in_web-0.9.1+1
image_cropper-1.2.3
image_picker-0.6.7+2
package_info-0.4.1
path_provider-1.6.11
path_provider_linux-0.0.1+1
path_provider_macos-0.0.4+3
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
uni_links-0.2.0
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6

**Comment by darshankawar** [comment]
Hi @jawad12345A,
Are you using a large set of images in your app ?
Can you try [this](https://github.com/flutter/flutter/issues/20316#issuecomment-647174296) and [this](https://github.com/trentpiercy/trace/issues/1#issuecomment-404494469) solution and see if they work for you ?
Also see this : https://gist.github.com/devinrhode2/4cbf7f02a9701510d61f5be0515b8286.
Thanks.

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
