### ISSUE TITLE
Minimize the app window will trigger a Slider assert

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#64629]
## Steps to reproduce
1. Run the following app in **windows desktop**:
2. Minimize the APP Window，will trigger an assert below:
```

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:flutter/src/material/slider_theme.dart': Failed assertion: line 1456 pos 12: 'parentBox.size.width >= overlayWidth': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Slider file:///D:/My%20Documents/Desktop/flutter_app_demo/lib/main.dart:37:18
When the exception was thrown, this was the stack: 
#2      BaseSliderTrackShape.getPreferredRect (package:flutter/src/material/slider_theme.dart:1456:12)
#3      _RenderSlider.paint (package:flutter/src/material/slider.dart:1377:52)
#4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2323:7)
#5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:191:13)
#6      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
...
The following RenderObject was being processed when the exception was fired: _RenderSlider#12477
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=0.0, h=0.0)
...  size: Size(0.0, 0.0)
RenderObject: _RenderSlider#12477
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=0.0, h=0.0)
  size: Size(0.0, 0.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double value = 0.5;
  _onChange(newValue) {
    setState(() {
      print('$newValue');
      value = newValue;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Directionality(
      textDirection: TextDirection.ltr,
      child: Center(
        child: RepaintBoundary(
          child: Slider(
            value: value,
            onChanged: _onChange,
          ),
        ),
      ),
    ));
  }
}
```

**Comment by HansMuller** [comment]
CC @clocksmith @JoseAlba

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

```
event sent after app closed: {id: 0, progressId: null, message: Downloading windows-x64/windows-x64-flutter tools...}
event sent after app closed: {id: 0, progressId: null, finished: true}
event sent after app closed: {id: 1, progressId: null, message: Downloading windows-x64/flutter-cpp-client-wrapper tools...}
event sent after app closed: {id: 1, progressId: null, finished: true}
event sent after app closed: {id: 2, progressId: null, message: Downloading windows-x64-profile/windows-x64-flutter tools...}
event sent after app closed: {id: 2, progressId: null, finished: true}
event sent after app closed: {id: 3, progressId: null, message: Downloading windows-x64-release/windows-x64-flutter tools...}
event sent after app closed: {id: 3, progressId: null, finished: true}
Launching lib\main.dart on Windows in debug mode...
Connecting to VM Service at ws://127.0.0.1:54471/bYO2lOc1uJw=/ws

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during paint():[39;49m
'package:flutter/src/material/slider_theme.dart': Failed assertion: line 1456 pos 12: 'parentBox.size.width >= overlayWidth': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mSlider[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      BaseSliderTrackShape.getPreferredRect[39;49m
[38;5;244m#3      _RenderSlider.paint[39;49m
[38;5;244m#4      RenderObject._paintWithContext[39;49m
[38;5;244m#5      PaintingContext.paintChild[39;49m
[38;5;244m#6      RenderProxyBoxMixin.paint[39;49m
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: _RenderSlider#6cf88[39;49m
[38;5;244mRenderObject: _RenderSlider#6cf88[39;49m
    [38;5;244mparentData: <none> (can use size)[39;49m
    [38;5;244mconstraints: BoxConstraints(w=0.0, h=0.0)[39;49m
    [38;5;244msize: Size(0.0, 0.0)[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

               
``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.81, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.81 at C:\Code\flutter_master
    • Framework revision 8c8b91069d (2 hours ago), 2020-08-26 06:03:05 -0700
    • Engine revision c7467a4359
    • Dart version 2.10.0 (build 2.10.0-59.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30413.136
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by xu-baolin** [comment]
@clocksmith Hi, I have post a PR to fix this issue, please review, thank you.

**Comment by clocksmith** [comment]
> @clocksmith Hi, I have post a PR to fix this issue, please review, thank you.

Thanks, LGTM
