### ISSUE TITLE
Hit testing can be triggered while layout is still pending, causing assertion errors

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#64661]
## Steps to reproduce

Run the following app in the target that can produce `PointerScrollEvent` events (e.g. desktop or web with a trackpad or mouse with a scroll wheel connected).

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Align(
      child: FractionalTranslation(
        translation: Offset.zero,
        child: RelayoutOnMouseScroll(
          child: ConstrainedBox(
            constraints: BoxConstraints(
              minWidth: 200,
              minHeight: 200,
            ),
            child: ColoredBox(
              color: const Color(0xffff0000),
            ),
          ),
        ),
      ),
    );
  }
}

class RelayoutOnMouseScroll extends SingleChildRenderObjectWidget {
  const RelayoutOnMouseScroll({Key key, Widget child}) : super(key: key, child: child);

  @override
  RenderObject createRenderObject(BuildContext context) => RenderRelayoutOnMouseScroll();
}

class RenderRelayoutOnMouseScroll extends RenderBox with RenderObjectWithChildMixin<RenderBox> {
  @override
  void handleEvent(PointerEvent event, BoxHitTestEntry entry) {
    if (event is PointerScrollEvent) _handlePointerScrollEvent(event, entry);
    super.handleEvent(event, entry);
  }

  Offset _scrollDelta = Offset.zero;

  void _handlePointerScrollEvent(PointerScrollEvent event, BoxHitTestEntry entry) {
    _scrollDelta += event.scrollDelta;
    markNeedsLayout();
  }

  @override
  double computeMaxIntrinsicWidth(double height) {
    return child.getMaxIntrinsicWidth(height) + _scrollDelta.dx;
  }

  @override
  double computeMinIntrinsicWidth(double height) {
    return child.getMinIntrinsicWidth(height) + _scrollDelta.dx;
  }

  @override
  double computeMaxIntrinsicHeight(double width) {
    return child.getMaxIntrinsicHeight(width) + _scrollDelta.dy;
  }

  @override
  double computeMinIntrinsicHeight(double width) {
    return child.getMinIntrinsicHeight(width) + _scrollDelta.dy;
  }

  @override
  bool hitTestSelf(Offset position) => true;

  @override
  void performLayout() {
    final EdgeInsets deflation = EdgeInsets.fromLTRB(_scrollDelta.dx, _scrollDelta.dy, 0, 0);
    child.layout(constraints.deflate(deflation), parentUsesSize: true);
    size = constraints.constrain(child.size);
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    context.paintChild(child, offset);
  }
}
```

... then use the scroll wheel / trackpad to scroll over the red box.

## Expected behavior

You expect the red box to grow or shrink as you scroll.

## Actual behavior

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 2594 pos 12: '!debugNeedsLayout': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2594:12)
#3      RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2581:12)
#4      RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:85:24)
#5      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:777:31)
#6      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:80:21)
#7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2163:11)
#8      RenderView.hitTest (package:flutter/src/rendering/view.dart:189:13)
#9      RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:458:16)
#10     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:266:7)
#11     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
#12     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
#13     _rootRunUnary (dart:async/zone.dart:1206:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#16     _invoke1 (dart:ui/hooks.dart:265:10)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

## Diagnosis

We're calling `markNeedsLayout()` on the render object, which is scheduling a layout, but our event dispatcher is flushing the event queue before the layout happens.  This can be seen if you instrument the `GestureBinding._flushPointerEventQueue()` as well as `RenderRelayoutOnMouseScroll._handlePointerScrollEvent()` and `RenderRelayoutOnMouseScroll.performLayout()` -- which produces the following:

```
flutter: flushing 1 events
flutter: marking needing layout
flutter: laying out
flutter: flushing 1 events
flutter: marking needing layout
flutter: flushing 1 events
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 2594 pos 12: '!debugNeedsLayout': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
...
```

## Other info

```
$ flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-2.0.pre.51, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.22.0-2.0.pre.51 at /Users/tvolkert/project/flutter/flutter
    • Framework revision 9497c3ec54 (2 days ago), 2020-08-24 14:40:50 -0700
    • Engine revision aa08192a6b
    • Dart version 2.10.0 (build 2.10.0-52.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tvolkert/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode_11.2.1.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

**Comment by cbracken** [comment]
This'll be a problem for platform view hover events too due to: https://github.com/flutter/flutter/commit/fa0c49d77

**Comment by tvolkert** [comment]
It's capable of biting any render object that calls `markNeedsLayout()` in an event handler.  Practically speaking, the only events that come in fast enough to trigger this are going to be scroll events and hover events.

Per @Hixie, this is something we ran into early on in the framework, and the solution is to add something analogous to the widget build phase (which runs before `flushLayout()` is called in each frame).  Using this mechanism, the render object would mark itself as dirty in some way, then at the beginning of the next frame, the dirty bit would cause it to invalidate its layout... then the corresponding layout pass would happen synchronously in the same frame -- with no opportunity for input events to be dispatched while it was marked as needing layout.

The problem with the solution above is that it currently necessitates a hook to run code before `RendererBinding.drawFrame()` (such as `WidgetsBinding` does by overriding `drawFrame()` to do its build phase).  Attempting to call `SchedulerBinding.addPersistentFrameCallback()` won't work, because you'll be in line after the frame is drawn.

Adding a notion of "pre-frame" callbacks (`SchedulerBinding.addPreFrameCallback()`) would solve for this.

**Comment by Hixie** [comment]
We have that, it's called [`scheduleFrameCallback`](https://master-api.flutter.dev/flutter/scheduler/SchedulerBinding/scheduleFrameCallback.html).

**Comment by tvolkert** [comment]
Oh man, didn't see it because it didn't match the "add*Callback()" naming pattern. 🙄

**Comment by Hixie** [comment]
Yeah... a lot of our earliest APIs aren't perfectly aligned because we didn't yet know what we were building.

**Comment by tvolkert** [comment]
Is it not possible for events to be dispatched in between `window.beginFrame` and `window.drawFrame`?

**Comment by tvolkert** [comment]
Seems like it's safe:

> The onDrawFrame callback is invoked immediately after onBeginFrame, after draining any microtasks (e.g. completions of any Futures) queued by the onBeginFrame handler.

**Comment by tvolkert** [comment]
Ok, with the following mixin added to `RenderRelayoutOnMouseScroll ` above, and with replacing `markNeedsLayout()` with `markDirty()`, the issue is fixed.

```dart
mixin DeferMarkNeedsLayoutMixin on RenderObject {
  bool _dirty = false;
  void markDirty() {
    if (!_dirty) {
      _dirty = true;
      SchedulerBinding.instance.scheduleFrameCallback((Duration timeStamp) {
        if (_dirty) {
          _dirty = false;
          markNeedsLayout();
        }
      });
    }
  }
}
```
