### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method map#update on channel plugins.flutter.io/google_maps_1)

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#64664]
## Steps to Reproduce

1. Create a flutter new project with google_maps_flutter: ^0.5.30
2. Create a TabView with two chidren and place a Google Maps widget in each tab.
3. Change the tab

**Expected results:** 

check error logs and also notice the jerk transition

**Actual results:** 
No error, no jerk transition

<details>
  <summary>Logs</summary>

```
E/flutter (12346): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method markers#update on channel plugins.flutter.io/google_maps_1)
E/flutter (12346): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (12346): <asynchronous suspension>
E/flutter (12346): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (12346): #2      MethodChannelGoogleMapsFlutter.updateMarkers (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:224:27)
E/flutter (12346): #3      GoogleMapController._updateMarkers (package:google_maps_flutter/src/controller.dart:115:39)
E/flutter (12346): #4      _GoogleMapState._updateMarkers (package:google_maps_flutter/src/google_map.dart:287:16)
E/flutter (12346): <asynchronous suspension>
E/flutter (12346): #5      _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:265:5)
E/flutter (12346): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:58)
E/flutter (12346): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
E/flutter (12346): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
E/flutter (12346): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (12346): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (12346): #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
E/flutter (12346): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5531:32)
E/flutter (12346): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5966:17)
E/flutter (12346): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5531:32)
E/flutter (12346): #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5966:17)
E/flutter (12346): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
E/flutter (12346): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (12346): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (12346): #26     ProxyElement.update (package:flutter/src/widgets/framework.dart:4871:5)
E/flutter (12346): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (12346): #29     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
E/flutter (12346): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (12346): #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4716:5)
E/flutter (12346): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
E/flutter (12346): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (12346): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
E/flutter (12346): #37     StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
E/flutter (12346): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
E/flutter (12346): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
E/flutter (12346): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
E/flutter (12346): #42     Element.rebuild (package:flutter/
```

```
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.18362.1016], locale en-MU)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.43.2)
[√] Connected device (3 available)


```

</details>

**Comment by pedromassangocode** [comment]
Hi @tolotrasamuel 
Can you please provide your your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by zirho** [comment]
Not sure this is relevant but I've got something like this from `flutter run --verbose`

```
[+1298 ms] > Task :url_launcher:compileDebugJavaWithJavac
[        ] Note:
/Users/zirho6/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.5.1/android/src/main/java/io/flutter/plugin
s/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
[   +1 ms] Note: Recompile with -Xlint:deprecation for details.
[ +200 ms] > Task :app:mergeDebugResources
```
