### ISSUE TITLE
Flutter returned exit status -1

### ISSUE THREAD

**Issue by Drwt28** [flutter/flutter#64726]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color build apk

## exception

ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\DEEPANSHU\Desktop\GritFusion\pet_owners\android\gradlew.bat.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:473:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:390:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:103:13)
#6      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:120:26)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:909:18)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Microsoft Windows [Version 10.0.18363.1016], locale en-IN)
    • Flutter version 1.21.0-9.1.pre at D:\flutter\flutter
    • Framework revision be9bc8cb39 (9 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\DEEPANSHU\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.47.0)
    • VS Code at C:\Users\DEEPANSHU\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
Hi @Drwt28,
There's similar open issue describing your case, [56975](https://github.com/flutter/flutter/issues/56975).
Please follow-up there for updates and any questions.
Closing this as duplicate.
