### ISSUE TITLE
'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 77 pos 16: 'keys.isNotEmpty':

### ISSUE THREAD

**Issue by ydotmalik** [flutter/flutter#64777]
I see the following assertion in the run log:
```
I/flutter (14865): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (14865): The following assertion was thrown during a platform message callback:
I/flutter (14865): 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 77 pos 16: 'keys.isNotEmpty':
I/flutter (14865): is not true.
I/flutter (14865): 
I/flutter (14865): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14865): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14865): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14865):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (14865): 
I/flutter (14865): When the exception was thrown, this was the stack:
I/flutter (14865): #2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:77:16)
I/flutter (14865): #3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
I/flutter (14865): #4      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:181:63)
I/flutter (14865): #5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:309:63)
I/flutter (14865): #6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:472:20)
I/flutter (14865): #7      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1623:43)
I/flutter (14865): #8      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:598:68)
I/flutter (14865): #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:49)
I/flutter (14865): #10     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
I/flutter (14865): #11     _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
I/flutter (14865): #15     _invoke3 (dart:ui/hooks.dart:281:10)
I/flutter (14865): #16     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
I/flutter (14865): (elided 5 frames from class _AssertionError and dart:async)
I/flutter (14865): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
To reproduce:
- run any flutter mobile app through Android Studio. Set the device to the Bluestacks emulator
- with the Bluestacks window focused, switch away from the workspace containing Bluestacks to another workspace using Ctrl+Win+Left/Right

This doesn't cause any problems but it clutters my run window and prevents me from clearly seeing my own prints. This didn't happen in an earlier version of Flutter. How can I prevent this from happening?

As a workaround, I commented out package:flutter/src/widgets/shortcuts.dart:77.

This might be related to [this](https://github.com/flutter/flutter/issues/48442).

```
flutter doctor -v
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\ydotmalik\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • SM G955F (mobile) • emulator-5554 • android-x86 • Android 7.1.2 (API 25)

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @ydotmalik 
Can you please provide your `flutter doctor -v`, a minimal complete reproducible code sample and steps to reproduce?

Also, please share the ticket that you think is related to this one.
Thank you

**Comment by ydotmalik** [comment]
Done

**Comment by pedromassangocode** [comment]
Hi @ydotmalik 
I will suggest you to follow up on that issue (https://github.com/flutter/flutter/issues/48442) as it still opened and contains more informations related to the issue.

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
