### ISSUE TITLE
LUCI infra failure reported as build failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#64799]
https://ci.chromium.org/p/flutter/builders/prod/Mac%20iOS%20Engine%20Profile/4663

the step `build ios_profile` appears to fail during upload of ninja logs:

```
Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/depot_tools/ninjalog_uploader_wrapper.py", line 125, in <module>
    sys.exit(main())
  File "/b/s/w/ir/kitchen-checkout/depot_tools/ninjalog_uploader_wrapper.py", line 78, in main
    config = LoadConfig()
  File "/b/s/w/ir/kitchen-checkout/depot_tools/ninjalog_uploader_wrapper.py", line 33, in LoadConfig
    ninjalog_uploader.IsGoogler('chromium-build-stats.appspot.com'),
  File "/b/s/w/ir/kitchen-checkout/depot_tools/ninjalog_uploader.py", line 43, in IsGoogler
    _, content = h.request('https://' + server + '/should-upload', 'GET')
  File "/b/s/w/ir/cache/vpython/0307b3/lib/python2.7/site-packages/httplib2/__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/b/s/w/ir/cache/vpython/0307b3/lib/python2.7/site-packages/httplib2/__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/b/s/w/ir/cache/vpython/0307b3/lib/python2.7/site-packages/httplib2/__init__.py", line 1355, in _conn_request
    response = conn.getresponse()
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/httplib.py", line 1148, in getresponse
    response.begin()
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/httplib.py", line 404, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/ssl.py", line 754, in recv
    return self.read(buflen)
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/ssl.py", line 641, in read
    v = self._sslobj.read(len)
socket.error: [Errno 54] Connection reset by peer
```

**Comment by digiter** [comment]
Triage: The command failure `autoninja -C /b/s/w/ir/cache/builder/src/out/ios_profile` doesn't seems like an infra issue.

**Comment by zanderso** [comment]
I'm not totally familiar with this area, but from the backtrace above, it looks like a `depot_tools` python script tried to upload something and failed. How should the upload failure there be classified?

**Comment by digiter** [comment]
Sorry, after looking more closely, the `build ios_profile` step contains two parts: compiling an engine binary and uploading ninjalog. The second part is related to infra indeed. We need to find a way to tell which part has error.

Typically a LUCI step is either a build step or an infra step. But in this case they are mixed.

**Comment by godofredoc** [comment]
Closing as obsolete.
