### ISSUE TITLE
BUG '_debugLifecycleState == _StateLifecycle.ready': is not true.

### ISSUE THREAD

**Issue by tuzimoe** [flutter/flutter#64803]
```════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1313 pos 12: '_debugLifecycleState == _StateLifecycle.ready': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      State.dispose 
package:flutter/…/widgets/framework.dart:1313
#3      TickerProviderStateMixin.dispose 
package:flutter/…/widgets/ticker_provider.dart:240
#4      _SignUpPageState.dispose 
package:soda_runman/src/signup.dart:393
#5      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:4773
#6      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1935
...
════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1313 pos 12:
'_debugLifecycleState == _StateLifecycle.ready': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
#2      State.dispose 
package:flutter/…/widgets/framework.dart:1313
#3      TickerProviderStateMixin.dispose 
package:flutter/…/widgets/ticker_provider.dart:240
#27     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#28     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#29     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5861
#30     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#31     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#32     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#33     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#34     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#35     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5861
#36     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#37     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#38     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#39     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#40     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#41     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5861
#42     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#43     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#44     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#45     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#46     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#47     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#48     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#49     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#50     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#51     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#52     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#53     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5861
#54     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#55     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#56     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#57     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#58     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#59     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5861
#60     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#61     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#62     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#63     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#64     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#65     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#66     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#67     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#68     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#69     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#70     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#71     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#72     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#73     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#74     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5861
#75     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#76     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#77     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#78     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#79     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#80     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#81     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#82     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#83     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5861
#84     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#85     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#86     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#87     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#88     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#89     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#90     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#91     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1933
#92     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4600
#93     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1931
#94     ListIterable.forEach  (dart:_internal/iterable.dart:39:13)
#95     _InactiveElements._unmountAll 
package:flutter/…/widgets/framework.dart:1944
#96     BuildOwner.finalizeTree.<anonymous closure> 
package:flutter/…/widgets/framework.dart:2754
#97     BuildOwner.lockState 
package:flutter/…/widgets/framework.dart:2558
#98     BuildOwner.finalizeTree 
package:flutter/…/widgets/framework.dart:2753
#99     WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:868
#100    RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
#101    SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
#102    SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1056
#103    SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:972
#107    _invoke  (dart:ui/hooks.dart:253:10)
#108    _drawFrame  (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════```

**Comment by sidrao2006** [comment]
Hi @tuzimoe can you please post the output of `flutter doctor -v` and a minimal reproducible code sample.
Thank you

**Comment by darshankawar** [comment]
@tuzimoe please provide the details as requested above.
Thanks.

**Comment by tuzimoe** [comment]
flutter doctor -v
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.3 19D76, locale zh-Hant-NZ)
    • Flutter version 1.20.2 at /Users/usagi/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/usagi/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (1 available)            
```

**Comment by tuzimoe** [comment]
Thanks for the response. The error only appear when using the debug mode but not with flutter run. Still working on to locate the error lines.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
