### ISSUE TITLE
[test] FractionallySizedBox throws exceptions with widthFactor: 0

### ISSUE THREAD

**Issue by ravenblackx** [flutter/flutter#64825]
In the form of a test case:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('FractionallySizedBox exception', (tester) async {
    await tester.pumpWidget(
      Directionality(
        textDirection: TextDirection.ltr,
        child: Center(
          child: SizedBox(
            width: 100,
            height: 100,
            child: Stack(
              children: [
                Container(color: Colors.black),
                FractionallySizedBox(
                  widthFactor: 0.0,
                  child: Container(color: Colors.red),
                ),
              ],
            ),
          ),
        ),
      ),
    );
    await tester.pump();
  });
}
```

Throws exceptions:
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the RenderFractionallySizedOverflowBox class returned values that
violate the intrinsic protocol contract.
The following failures was detected:
 * getMinIntrinsicWidth(Infinity) returned a non-finite value: NaN
 * getMaxIntrinsicWidth(Infinity) returned a non-finite value: NaN
 * getMinIntrinsicWidth(100.0) returned a non-finite value: NaN
 * getMaxIntrinsicWidth(100.0) returned a non-finite value: NaN
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  FractionallySizedBox
  google3:///experimental/users/ravenblack/flutter_bugs/test/fractionally_sized_box_test.dart:17:17

When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2116:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2128:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1846:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1848:6)
#4      RenderFractionallySizedOverflowBox.performLayout (package:flutter/src/rendering/shifted_box.dart:959:7)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#6      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:560:15)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#8      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#10     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:394:14)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#12     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:14)
#13     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
#14     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
#15     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1091:23)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#19     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:961:9)
#22     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#23     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:948:27)
#24     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:524:22)
#27     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#28     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:521:27)
#29     main.<anonymous closure> (google3:///experimental/users/ravenblack/flutter_bugs/test/fractionally_sized_box_test.dart:7:18)
#30     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
<asynchronous suspension>
#31     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#32     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
<asynchronous suspension>
#35     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#36     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#37     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#42     withClock (package:clock/src/default.dart:48:10)
#43     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#48     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#49     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#50     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#51     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#52     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#57     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#58     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#63     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#64     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#65     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#70     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#71     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#72     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#79     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#80     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#81     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#86     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#87     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#105    _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#106    new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#110    CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#144    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#152    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#153    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#163    _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#172    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#173    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
(elided 115 frames from dart:async and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderFractionallySizedOverflowBox#087f8 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: FractionallySizedBox ← Stack ← SizedBox ← Center ← Directionality ← [root]
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=100.0, 0.0<=h<=100.0)
  size: Size(0.0, 100.0)
  alignment: center
  textDirection: ltr
  widthFactor: 0.0
  heightFactor: pass-through
This RenderObject had the following descendants (showing up to depth 5):
    child: _RenderColoredBox#f17d5 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderLimitedBox#9a471 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderConstrainedBox#06ea9 relayoutBoundary=up4 NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
```
Did not seem to throw exceptions when I tried it in https://codepen.io/pen/editor/flutter, so it might be a recent change.

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
void main() {
  testWidgets('FractionallySizedBox exception', (tester) async {
    await tester.pumpWidget(
      Directionality(
        textDirection: TextDirection.ltr,
        child: Center(
          child: SizedBox(
            width: 100,
            height: 100,
            child: Stack(
              children: [
                Container(color: Colors.black),
                FractionallySizedBox(
                  widthFactor: 1.0,
                  child: Container(color: Colors.red),
                ),
              ],
            ),
          ),
        ),
      ),
    );
    await tester.pump();
  });
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS
      13.6.1
    • iPhone 11 (mobile)     • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.139, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-2.0.pre.139 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision c0ea00ed3f (7 hours ago), 2020-08-30 22:20:16 -0700
    • Engine revision bada9fc5f3
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6.1
    • iPhone 11 (mobile)     • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by ravenblackx** [comment]
At the very least it's a bug because there's an assert that widthFactor >= 0, which if it's expected to not work with 0 should be an assert that widthFactor > 0.

But I don't think that's the place to make a change, because it should work with zero - a zero-width widget is a perfectly common thing, and if, e.g. you were using this widget for a progress bar or similar, zero is a valid value for most such things.

("Ugly" was in the bug description because if the assert was changed to exclude widthFactor 0 then it would still throw an exception but it would no longer be ugly!)

**Comment by darshankawar** [comment]
Verified this issue on latest stable (3.0.1) and confirmed that the exception doesn't occur anymore and the test passes successfully as below:

<img width="774" alt="Screenshot 2022-06-02 at 10 36 19 AM" src="https://user-images.githubusercontent.com/67046386/171556845-1b024fc6-5553-4160-a35a-71a73492f646.png">

<details>
<summary> stable flutter doctor -v </summary>

```

[✓] Flutter (Channel unknown, 3.0.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

Closing this as fixed in latest stable version.
