### ISSUE TITLE
Error while testing development on iOS device. Exception caught by scheduler library 

### ISSUE THREAD

**Issue by jgonzalezedu** [flutter/flutter#64835]
Exception caught by scheduler library 
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 790 pos 12: 'elapsedInSeconds >= 0.0': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack
#2      AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:790
#3      Ticker._tick 
package:flutter/…/scheduler/ticker.dart:240
#4      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:1032
#6      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
...

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#2      SchedulerBinding.scheduleFrameCallback 
package:flutter/…/scheduler/binding.dart:526
#3      Ticker.scheduleTick 
package:flutter/…/scheduler/ticker.dart:255
#4      Ticker.start 
package:flutter/…/scheduler/ticker.dart:164
#5      AnimationController._startSimulation 
package:flutter/…/animation/animation_controller.dart:715
#6      AnimationController._animateToInternal 

EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 790 pos 12:
'elapsedInSeconds >= 0.0': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

(elided 5 frames from class _AssertionError and dart:async)
This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack:

#29     EditableTextState._showCaretOnScreen.<anonymous closure> 
package:flutter/…/widgets/editable_text.dart:1904
#30     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
#31     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1064
#32     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:972
#36     _invoke  (dart:ui/hooks.dart:253:10)
#37     _drawFrame  (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _FrameCallbackEntry and dart:async)

**Comment by darshankawar** [comment]
Hi @jgonzalezedu,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.
