### ISSUE TITLE
Flutter web Firebase analytics  error on flutter beta latest

### ISSUE THREAD

**Issue by VishnuSuresh2000** [flutter/flutter#64889]
How to resolve this firebase error . this error is showing only on running in web

```
TypeError: dart.global.firebase.analytics is not a function
    at Object.analytics$ [as analytics] (http://localhost:5000/packages/firebase/src/top_level.dart.lib.js:110:102)
    at new firebase_analytics_web.FirebaseAnalyticsWeb.new (http://localhost:5000/packages/firebase_analytics_web/firebase_analytics_web.dart.lib.js:56:64)
    at Function.registerWith (http://localhost:5000/packages/firebase_analytics_web/firebase_analytics_web.dart.lib.js:19:82)
    at Object.registerPlugins (http://localhost:5000/packages/beru/generated_plugin_registrant.dart.lib.js:20:49)
    at main (http://localhost:5000/web_entrypoint.dart.lib.js:29:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:37623:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:37654:7)
    at main$ (http://localhost:5000/web_entrypoint.dart.lib.js:28:18)
    at http://localhost:5000/main_module.bootstrap.js:20:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:5000/main_module.bootstrap.js:19:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:5000/dwds/src/injected/client.js:8758:21)
    at http://localhost:5000/dwds/src/injected/client.js:22459:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:5000/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:5000/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:5000/dwds/src/injected/client.js:3766:20)
    at main__closure1.$call$body$main__closure (http://localhost:5000/dwds/src/injected/client.js:22471:16)
    at main__closure1.call$1 (http://localhost:5000/dwds/src/injected/client.js:22398:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:5000/dwds/src/injected/client.js:4136:16)
    at _CustomZone.runUnary$2$2 (http://localhost:5000/dwds/src/injected/client.js:12301:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:5000/dwds/src/injected/client.js:12233:14)
    at _ControllerSubscription._sendData$1 (http://localhost:5000/dwds/src/injected/client.js:11784:19)
    at _DelayedData.perform$1 (http://localhost:5000/dwds/src/injected/client.js:11936:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:5000/dwds/src/injected/client.js:11985:14)
    at Object._microtaskLoop (http://localhost:5000/dwds/src/injected/client.js:3969:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:5000/dwds/src/injected/client.js:3975:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:5000/dwds/src/injected/client.js:10865:9)
    at invokeClosure (http://localhost:5000/dwds/src/injected/client.js:1204:26)
    at invokeClosure (http://localhost:5000/dwds/src/injected/client.js:1204:26)
```
index.html firebase section

```
<script src="https://www.gstatic.com/firebasejs/7.19.1/firebase-app.js"></script>
  <script defer src="https://www.gstatic.com/firebasejs/7.19.1/firebase-auth.js"></script>
  <!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="https://www.gstatic.com/firebasejs/7.19.1/firebase-analytics.js"></script>

  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      apiKey: "A....",
      authDomain: "....",
      databaseURL: "......,
      projectId: "....",
      storageBucket: "....",
      messagingSenderId: "...",
      appId: ".....",
      measurementId: "...."
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    // firebase.analytics();
  </script>

```
Same error while initialized the  firebase.analytics()
```
<script src="https://www.gstatic.com/firebasejs/7.19.1/firebase-app.js"></script>
  <script defer src="https://www.gstatic.com/firebasejs/7.19.1/firebase-auth.js"></script>
  <!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="https://www.gstatic.com/firebasejs/7.19.1/firebase-analytics.js"></script>

  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      apiKey: "A....",
      authDomain: "....",
      databaseURL: "......,
      projectId: "....",
      storageBucket: "....",
      messagingSenderId: "...",
      appId: ".....",
      measurementId: "...."
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>

```

flutter doctor :

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.48.2)
[√] Connected device (2 available)  

! Doctor found issues in 1 category

```
The pubspec.yaml added the dependency 

```
styled_text: ^1.0.1+1
  firebase_core: ^0.5.0
  firebase_analytics: "^6.0.0"
  carousel_pro: ^1.0.0
```

when don't declare the  firebase_analytics there is no error and web is ruining 
```
styled_text: ^1.0.1+1
  firebase_core: ^0.5.0
  #firebase_analytics: "^6.0.0"
  carousel_pro: ^1.0.0
```

**Comment by iapicca** [comment]
this issue should be opened [here](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by darshankawar** [comment]
Hi @VishnuSuresh2000,
This seems to be an issue with firebase plugin that has separate repo for tracking. Please consider opening this issue here: https://github.com/FirebaseExtended/flutterfire/issues
Closing, as this isn't an issue with Flutter.
