### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'E:\repos\open-source-contribution\flutter\bin\cache\flutter_web_sdk\kernel\amd\dart_sdk.js', OS Error: Cannot create a file when that file already exists., errno = 183

### ISSUE THREAD

**Issue by varora1406** [flutter/flutter#64892]
## Command
```
flutter run
```

## Steps to Reproduce
1. `flutter run` for a new project to run in android emulator, which again working fine with other project

## Logs
FileSystemException: Cannot copy file to 'E:\repos\open-source-contribution\flutter\bin\cache\flutter_web_sdk\kernel\amd\dart_sdk.js', OS Error: Cannot create a file when that file already exists.
, errno = 183
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      FlutterWebSdk.updateInner (package:flutter_tools/src/cache.dart:725:16)
<asynchronous suspension>
#5      CachedArtifact.update (package:flutter_tools/src/cache.dart:589:11)
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:455:24)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:879:27)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:787:33)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZoned (dart:async/zone.dart:1550:10)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:776:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
    • Flutter version 1.21.0-9.2.pre at E:\repos\open-source-contribution\flutter
    • Framework revision 81a45ec2e5 (3 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\VaibhavArora\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at E:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.83

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: be9bc8cb3942bda5d8ef4e44b44616c470625e18
### Plugins
permission_handler-5.0.1+1

**Comment by iapicca** [comment]
the crash might be related to the 3rd party plugin [permission_handler](https://pub.dev/packages/permission_handler)
can you provide a reproducible code sample w/o 3rd party plugins?

**Comment by basantsingh-os** [comment]
open a particular directory.
sudo chmod -R 777 *
it will work on unix system if using windows do equivalent thing.

**Comment by hamdikahloun** [comment]
@varora1406 
Rename dart_sdk.js to dart_sdk.js.bak and try again.

**Comment by TahaTesser** [comment]
@varora1406 
Please try without using third party packages and provide details as mentioned https://github.com/flutter/flutter/issues/64892#issuecomment-683397585
