### ISSUE TITLE
CupertinoNavigationBar transition error on Navigator Push

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#64912]
## Steps to Reproduce

1. Run an app with a CupertinoTabScaffold and a CupertinoSliverNavigationBar inside. 

Example Tab Page:
```
CupertinoPageScaffold(
        child: CustomScrollView(
          slivers: <Widget>[
             CupertinoSliverNavigationBar(
      automaticallyImplyLeading: false,
      backgroundColor: Theme.of(context).backgroundColor,
      largeTitle: Text(
        tabName,
      ),
      heroTag: "tabs",
    ),
            SliverList(
              delegate: SliverChildListDelegate(
                [
                  new Column(
                    children: <Widget>[
                      Home(),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      )
```

2. Push to another page with a CupertinoNavigationBar.
3. The app will black screen and give similar errors.

**Expected results:**
Transition to the other page with the iOS last page title as back button.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
Analyzing the_unwanteds...                                              

   info • The value of the local variable 'sizingInformation' isn't used • lib/pages/artRoom/artRoom.dart:593:11 •
          unused_local_variable
   info • The value of the local variable 'sizingInformation' isn't used • lib/pages/profile/artRoomPosts.dart:297:11 •
          unused_local_variable
warning • The include file ../../analysis_options.yaml in
       /Users/elias/Documents/GitHub/the_unwanteds/plugins/color_panel/analysis_options.yaml cannot be found •
       plugins/color_panel/analysis_options.yaml:1:11 • include_file_not_found
  error • 1 positional argument(s) expected, but 0 found • test/widget_test.dart:16:38 • not_enough_positional_arguments

4 issues found. (ran in 6.5s)

```

```
[✓] Flutter (Channel stable, 1.20.2, on macOS 11.0 20A5354i, locale en-US)
    • Flutter version 1.20.2 at /Users/elias/flutter
    • Framework revision bbfbf1770c (2 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/elias/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 3EA13ACF-26B5-4438-A5D9-DD55AED906FF • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)
```

</details>

**Error:**

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building SpellInfo(dirty, dependencies: [_InheritedTheme,
flutter: _LocalizationsScope-[GlobalKey#a0222], _EffectiveTickerMode], state: SpellInfoState#0a6dd):
flutter: Cannot specify a heroTag override if this navigation bar does not transition due to
flutter: transitionBetweenRoutes = false.
flutter: 'package:flutter/src/cupertino/nav_bar.dart':
flutter: Failed assertion: line 235 pos 10: '!transitionBetweenRoutes || identical(heroTag, _defaultHeroTag)'
flutter:
flutter: The relevant error-causing widget was:
flutter:   SpellInfo file:///Users/elias/Documents/GitHub/the_unwanteds/lib/components/spellCard.dart:192:24
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new CupertinoNavigationBar (package:flutter/src/cupertino/nav_bar.dart:235:10)
flutter: #3      SpellInfoState.buildAppBar (package:the_unwanteds/pages/spellinfo.dart:281:14)
flutter: #4      SpellInfoState.build (package:the_unwanteds/pages/spellinfo.dart:1209:28)
flutter: #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
flutter: #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
flutter: #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
flutter: ...     Normal element mounting (24 frames)
flutter: #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
flutter: #36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
flutter: ...     Normal element mounting (136 frames)
flutter: #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
flutter: #173    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
flutter: #174    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5624:32)
flutter: #175    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
flutter: #176    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #179    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #180    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
flutter: #181    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #183    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #184    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
flutter: #185    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
flutter: #186    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #187    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
flutter: #188    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #190    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #191    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #192    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
flutter: #193    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #194    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
flutter: #195    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #196    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
flutter: #197    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #199    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #200    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
flutter: #201    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #203    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #204    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
flutter: #205    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
flutter: #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
flutter: #207    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #208    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #209    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
flutter: #210    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
flutter: #211    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #212    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #213    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #214    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #218    _invoke (dart:ui/hooks.dart:253:10)
flutter: #219    _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Flutter error caught by Crashlytics plugin:
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: There are multiple heroes that share the same tag within a subtree.
flutter: Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
flutter: have a unique non-null tag.
flutter: In this case, multiple heroes had the following tag: tabs
flutter: ├# Here is the subtree for one of the offending heroes: Hero
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:268:11)
flutter: #1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:279:8)
flutter: #2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:298:21)
flutter: #3      _SliverPersistentHeaderElement.visitChildren (package:flutter/src/widgets/sliver_persistent_header.dart:257:14)
flutter: #4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #6      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #8      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #10     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #12     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #14     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #16     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
flutter: #18     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #19     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #20     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #21     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #22     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #24     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #26     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #27     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #28     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #30     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #32     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #34     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #36     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #38     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #40     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #42     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #44     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #45     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #46     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #48     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #49     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
flutter: #50     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #51     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #52     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #54     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #56     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #57     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #58     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #60     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #62     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #63     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #64     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #66     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: Flutter error caught by Crashlytics plugin:
flutter: #67     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #68     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #69     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
flutter: #70     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #72     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #73     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #74     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #75     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #76     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #77     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
flutter: #78     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #79     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #80     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #81     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #82     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #84     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #86     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #87     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #88     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #89     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
flutter: #90     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #92     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #93     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #94     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #96     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #97     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #98     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #99     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #100    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #101    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #102    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #103    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #104    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #105    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #106    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #108    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #110    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #111    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #112    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #113    _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:70:14)
flutter: #114    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #116    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #117    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #118    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #119    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #120    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
flutter: #122    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:311:15)
flutter: #123    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
flutter: #124    Element.visitChildElements (package:flutter/src/widgets/framework.dart:3174:5)
flutter: #125    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:314:13)
flutter: #126    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:840:53)
flutter: #127    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:815:11)
flutter: #128    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #129    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1064:9)
flutter: #130    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #134    _invoke (dart:ui/hooks.dart:253:10)
flutter: #135    _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 3 frames from dart:async)
```

**Comment by pedromassangocode** [comment]
Hi @EliasDeuss 
Can you please provide your `flutter doctor -v`, and a minimal complete reproducible code sample?
Thank you

**Comment by EliasDeuss** [comment]
> Hi @EliasDeuss 
> 
> Can you please provide your `flutter doctor -v`, and a minimal complete reproducible code sample?
> 
> Thank you

Working on that, I haven’t been able to reproduce it myself on the example app, I am trying to figure out what else could cause it.
