### ISSUE TITLE
Project template doesn't run on Pixel

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6492]
```
$ flutter create myapp
...app created..
$ cd myapp
$ flutter run
```

This app produces the following error when run on a Pixel XL:

```
--------- beginning of main
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=19682, uid=10017 that is not exported from uid 10077
W/ActivityManager:   Force finishing activity com.yourcompany.myapp/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=4197, uid=10146 that is not exported from uid 10077
W/System.err: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT >
W/System.err:   @3:3 in java.io.InputStreamReader@48e3c2d) 
W/System.err:   at org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
W/System.err:   at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
W/System.err:   at com.erosnow.utils.ao.b(UtilFortumo.java:1129)
W/System.err:   at com.erosnow.utils.ap.a(UtilFortumo.java:174)
W/System.err:   at com.erosnow.utils.ap.doInBackground(UtilFortumo.java:138)
W/System.err:   at android.os.AsyncTask$2.call(AsyncTask.java:305)
W/System.err:   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:   at java.lang.Thread.run(Thread.java:761)
W/System.err: org.xmlpull.v1.XmlPullParserException: name expected (position:TEXT >
W/System.err:   @3:3 in java.io.InputStreamReader@48e3c2d) 
W/System.err:   at org.kxml2.io.KXmlParser.checkRelaxed(KXmlParser.java:305)
W/System.err:   at org.kxml2.io.KXmlParser.readName(KXmlParser.java:1548)
W/System.err:   at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1091)
W/System.err:   at org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
W/System.err:   at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
W/System.err:   at com.erosnow.utils.ao.b(UtilFortumo.java:1129)
W/System.err:   at com.erosnow.utils.aq.a(UtilFortumo.java:233)
W/System.err:   at com.erosnow.utils.aq.doInBackground(UtilFortumo.java:198)
W/System.err:   at android.os.AsyncTask$2.call(AsyncTask.java:305)
W/System.err:   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:   at java.lang.Thread.run(Thread.java:761)
Timed out while waiting for a debug connection.
Error launching DevFS loader on Pixel XL.
```

Below is the input from flutter doctor command

$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/nasir/flutter-work/flutter
    • Framework revision 022cb2d9dc (2 days ago), 2016-10-21 16:54:59
    • Engine revision db12c5e621
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /Users/nasir/android_sdk_L/android-sdk-macosx
    • Platform android-N, build-tools 24.0.0-preview
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
[-] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.42

[-] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • Pixel XL • HT6860200899 • android-arm

**Comment by eseidelGoogle** [comment]
@sethladd do we have one of these?

**Comment by sethladd** [comment]
We do not have a Pixel XL

**Comment by eseidelGoogle** [comment]
I've asked @tvolkert to see if he can find one locally and if not to just buy one and we'll add to our library. :)

**Comment by sethladd** [comment]
Does it happen in the simulator for Pixel, or just on hardware?

**Comment by sethladd** [comment]
Confirmed this happens on Pixel hardware (not only the XL):

```
~/tmp/testpixel $ flutter run
Building APK in debug mode (android-arm)...              
Warning: signing the APK using the debug keystore.
Built build/app.apk (8.7MB).
Launching loader on Pixel...
--------- beginning of main
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=19721, uid=10118 that is not exported from uid 10078
W/ActivityManager:   Force finishing activity com.yourcompany.testpixel/org.domokit.sky.shell.SkyActivity
W/ActivityManager:   Force finishing activity com.yourcompany.testpixel/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Duplicate finish request for ActivityRecord{e662f76 u0 com.yourcompany.testpixel/org.domokit.sky.shell.SkyActivity t465 f}
```

**Comment by sethladd** [comment]
FWIW, I just upgraded my Android SDK to 25, to match my Pixel, and here's the error that I now see:

```
~/tmp/testpixel $ flutter run
Device emulator-5554 is offline.
Launching loader on Pixel...
--------- beginning of main
W/ActivityManager:   Force finishing activity com.yourcompany.testpixel/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Failed setting process group of 32459 to 1
W/System.err: java.lang.IllegalArgumentException: Given thread 32485 does not exist
W/System.err: 	at android.os.Process.setThreadPriority(Native Method)
W/System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20438)
W/System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:20932)
W/System.err: 	at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:271)
W/System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1221)
W/System.err: 	at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:172)
W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err: 	at android.os.Looper.loop(Looper.java:154)
W/System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by tvolkert** [comment]
Phone ordered...

**Comment by FaisalAbid** [comment]
However if you run the release version it works.

flutter run --release and its easy to get working on Pixel

**Comment by jason-simmons** [comment]
I don't have a Pixel, but I'm able to run Flutter with a debug engine on an Android 7.1.1 image in the x64 emulator

**Comment by sethladd** [comment]
> I'm able to run Flutter with a debug engine on an Android 7.1.1 image in the x64 emulator

Same. Works for me in the emulator.

**Comment by eseidelGoogle** [comment]
I now believe this is the same as #6693.
