### ISSUE TITLE
[tool_crash] ArchiveException

### ISSUE THREAD

**Issue by braulio94** [flutter/flutter#64950]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArchiveException
```
#0      ZipDirectory._findSignature (package:archive/src/zip/zip_directory.dart:149:5)
#1      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:28:20)
#2      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:20:30)
#3      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
#4      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:334:42)
#5      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1478:18)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#14     Net.fetchUrl (package:flutter_tools/src/base/net.dart)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#23     Net._attempt (package:flutter_tools/src/base/net.dart)
#24     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
```
```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.140, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.22.0-2.0.pre.140 at C:\flutter
    • Framework revision 6d1242dd4b (6 hours ago), 2020-08-31 03:53:04 -0400
    • Engine revision 784e6d746e
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\braulio.cassule\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.47.1)
    • VS Code at C:\Users\braulio.cassule\AppData\Local\Programs\Microsoft VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 84.0.4147.135
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 84.0.522.59

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: 0.0.1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
flutter-share-1c9846abd440829eccd0f96a1d8cac1b7dde6a71
flutter_absolute_path-bb996460cdca763b1a884082ba37f7c95bf53110
camera-0.5.8+2
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
device_info-0.4.2+7
firebase_auth-0.16.0
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_ml_vision-0.9.5
flutter_plugin_android_lifecycle-1.0.8
fluttertoast-4.0.1
google_sign_in-4.5.3
google_sign_in_web-0.9.1+1
image_picker-0.6.7+4
open_file-3.0.1
path_provider-1.6.7
path_provider_ex-1.0.1
path_provider_macos-0.0.4+1
pdf_text-0.2.1
permission_handler-5.0.0+hotfix.4
sqflite-1.3.0

**Comment by jonahwilliams** [comment]
should be fixed by https://github.com/flutter/flutter/commit/68b39da34601bb0d53a259798a97794829ed9926
