### ISSUE TITLE
NestedScrollView with `extendBody = true`: position initializes to null

### ISSUE THREAD

**Issue by jagomf** [flutter/flutter#64959]
# Exception when `NestedScrollView` has `extendBody = true`: `position` initializes to `null`
### Exception caught by Widgets library

The following assertion was thrown building Builder(dirty):

`'package:flutter/src/widgets/nested_scroll_view.dart'`: Failed assertion: line 798 pos 14:
`'position.minScrollExtent != null && position.pixels != null'`: is not true.

Either the assertion indicates an error in the framework itself, or **we should provide substantially more information in this error message** to help you determine and fix the underlying cause. In either case, please report this assertion by filing a bug on GitHub.

The relevant error-causing widget was:
  `NestedScrollView`
When the exception was thrown, this was the stack:
```
#2      _NestedScrollCoordinator.hasScrolledBody
#3      NestedScrollViewState.build.<anonymous closure>
#4      Builder.build
#5      StatelessElement.build
#6      ComponentElement.performRebuild
#7      Element.rebuild
#8      StatelessElement.update
#9      Element.updateChild
#10     ComponentElement.performRebuild
#11     Element.rebuild
#12     ProxyElement.update
#13     Element.updateChild
#14     ComponentElement.performRebuild
#15     StatefulElement.performRebuild
#16     Element.rebuild
#17     StatefulElement.update
#18     Element.updateChild
#19     ComponentElement.performRebuild
#20     Element.rebuild
#21     StatelessElement.update
#22     Element.updateChild
#23     ComponentElement.performRebuild
#24     Element.rebuild
#25     ProxyElement.update
#26     Element.updateChild
#27     ComponentElement.performRebuild
#28     Element.rebuild
#29     ProxyElement.update
#30     Element.updateChild
#31     RenderObjectElement.updateChildren
#32     MultiChildRenderObjectElement.update
#33     Element.updateChild
#34     ComponentElement.performRebuild
#35     StatefulElement.performRebuild
#36     Element.rebuild
#37     StatefulElement.update
#38     Element.updateChild
#39     ComponentElement.performRebuild
#40     Element.rebuild
#41     ProxyElement.update
#42     Element.updateChild
#43     ComponentElement.performRebuild
#44     StatefulElement.performRebuild
#45     Element.rebuild
#46     StatefulElement.update
#47     Element.updateChild
#48     SingleChildRenderObjectElement.update
#49     Element.updateChild
#50     ComponentElement.performRebuild
#51     Element.rebuild
#52     StatelessElement.update
#53     Element.updateChild
#54     SingleChildRenderObjectElement.update
#55     Element.updateChild
#56     ComponentElement.performRebuild
#57     StatefulElement.performRebuild
#58     Element.rebuild
#59     StatefulElement.update
#60     Element.updateChild
#61     ComponentElement.performRebuild
#62     StatefulElement.performRebuild
#63     Element.rebuild
#64     StatefulElement.update
#65     Element.updateChild
#66     ComponentElement.performRebuild
#67     Element.rebuild
#68     ProxyElement.update
#69     Element.updateChild
#70     ComponentElement.performRebuild
#71     Element.rebuild
#72     ProxyElement.update
#73     Element.updateChild
#74     ComponentElement.performRebuild
#75     StatefulElement.performRebuild
#76     Element.rebuild
#77     StatefulElement.update
#78     Element.updateChild
#79     ComponentElement.performRebuild
#80     StatefulElement.performRebuild
#81     Element.rebuild
#82     StatefulElement.update
#83     Element.updateChild
#84     RenderObjectElement.updateChildren
#85     MultiChildRenderObjectElement.update
#86     Element.updateChild
#87     ComponentElement.performRebuild
#88     Element.rebuild
#89     ProxyElement.update
#90     Element.updateChild
#91     _LayoutBuilderElement._layout.<anonymous closure>
#92     BuildOwner.buildScope
#93     _LayoutBuilderElement._layout
#94     RenderObject.invokeLayoutCallback.<anonymous closure>
#95     PipelineOwner._enableMutationsToDirtySubtrees
#96     RenderObject.invokeLayoutCallback
#97     RenderConstrainedLayoutBuilder.rebuildIfNecessary
#98     _RenderLayoutBuilder.performLayout
#99     RenderObject.layout
#100    MultiChildLayoutDelegate.layoutChild
#101    _ScaffoldLayout.performLayout
#102    MultiChildLayoutDelegate._callPerformLayout
#103    RenderCustomMultiChildLayoutBox.performLayout
#104    RenderObject._layoutWithoutResize
#105    PipelineOwner.flushLayout
#106    RendererBinding.drawFrame
#107    WidgetsBinding.drawFrame
#108    RendererBinding._handlePersistentFrameCallback
#109    SchedulerBinding._invokeFrameCallback
#110    SchedulerBinding.handleDrawFrame
#111    SchedulerBinding._handleDrawFrame
#115    _invoke  (dart:ui/hooks.dart:253:10)
#116    _drawFrame  (dart:ui/hooks.dart:211:3)
```
(elided 5 frames from class `_AssertionError` and `dart:async`)

## Reproduction and app structure

In the main screen, I have a `Scaffold` with a `BottomAppBar` in the bottom and an `IndexedStack` in the body so that different other 'sub-screens' can be loaded:
```dart
Scaffold(
  body: IndexedStack(
    children: [ Screen1(), Screen2(), Screen3() ],
    index: _currentPage,
  ),
  extendBody: true,
  bottomNavigationBar: BottomAppBarBasedWidget(
    onItemTapped: (int itemTapped) {
      setState(() { _currentPage = itemTapped; });
    }
  )
)
```

Each of these 'sub-screens' has a `NestedScrollView` so that I can provide a `SliverAppBar` in the header and different slivers in the body:
```dart
Scaffold(
  body: NestedScrollView(
    headerSliverBuilder: (BuildContext context, innerBoxScrolled) => [
      SliverAppBar(...)
    ],
    body: CustomScrollView(
      slivers: <Widget>[ ... ]
    )
  )
)
```

Given the fact that part of the main screen's `BottomAppBar`-based widget has `shape: CircularNotchedRectangle()`, I want the content to extend the body so that the content is seen behind; that is why I need `extendBody: true`.

**And that `extendBody: true` is what is causing the `NestedScrollView`s in the sub-screens to throw the exception.**

Note: Exception is only thrown at the beginning. If you just ignore the exception and continue to use the app, eveyhting goes fine; the exception does not come up again.

**Comment by pedromassangocode** [comment]
Hi @jagomf 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample? I need a code that I can just copy/paste and run to reproduce the issue.

Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
