### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by RJSD3V** [flutter/flutter#65021]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#3      _readFileContent (package:flutter_tools/src/plugins.dart:510:35)
#4      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:452:46)
#5      refreshPluginsList (package:flutter_tools/src/plugins.dart:1124:24)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:241:11)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:843:21)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZoned (dart:async/zone.dart:1550:10)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
    • Flutter version 1.20.2 at C:\src\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\rjsod\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.48.2)
    • VS Code at C:\Users\rjsod\AppData\Local\Programs\Microsoft VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 68587a0916366e9512a78df22c44163d041dd5f3
### Plugins
flutter_full_pdf_viewer-1.0.6
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3

**Comment by jonahwilliams** [comment]
Crash happens here: https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/lib/src/plugins.dart#L452

Work around: delete .flutter-plugins from the project working directory

**Comment by liyan1105** [comment]
Does anybody kown how to solve this problem? 
I'm total crazy。

**Comment by yintaibing** [comment]
In my case, my ```gradle.properties``` file's encoding was GBK, then it caused this issue. I changed its encoding to TUF-8 and issue solved.
So it might be a solution that we travelsal all files' encoding in our project?

**Comment by rmahmadkhan** [comment]
Did anybody find the workaround for this issue? 

I have tried deleting the `.flutter-plugins` but it isn't working. Plus in my `gradle.properties` there's no encoding defined.

**Comment by qcks** [comment]
```
    file.readAsLinesSync(encoding: utf8);
```
Normal on Windows, abnormal on Mac;
Attempts to switch encoding latin1 resulted in garbled code in the second half of the document.

**Comment by EliasFazel10296** [comment]
remove any comment # from .gradle files specially at the first lines.

**Comment by zancheng** [comment]
I uninstall the encryption software and it will be normal.

**Comment by lilmistake** [comment]
Running `flutter clean` before `flutter run` fixed it for me

**Comment by estelson** [comment]
Avoid using any **accented characters** in comments in **.properties** files. In tests I did, I removed the accented characters and it worked.

**Comment by PoseidonMRT** [comment]
> how to solve it . i have del the .flutter-plugins,but always does not work

does u have solved it?

**Comment by zancheng** [comment]
> > how to solve it . i have del the .flutter-plugins,but always does not work
> 
> does u have solved it?

1. Delete Flutter Cache Folder `.pub cache`
2. Uninstalling encryption software

**Comment by Oandujar93** [comment]
If someone are using a mac, check if you have autogenerated files with ._ prefix, it would be the reason. In order to solve, you must to execute next prompt at root folder of the project:
`find . -name "._*" -type f -delete`

**Comment by abirajabi** [comment]
> > > how to solve it . i have del the .flutter-plugins,but always does not work
> > 
> > 
> > does u have solved it?
> 
> @PoseidonMRT
> 
>     1. Delete Flutter Cache Folder `.pub cache`
> 
>     2. Uninstalling encryption software

What kinds of software is considered as encryption software? Does antivirus and windows bitlocker count? I found this issue on running my build runner script on local-runner of gitlab pipeline. But if I run locally, the script works fine.

**Comment by GGSDDUAY** [comment]
ToDay is 2024/04/22,Keep an eye on this issue;

**Comment by abdullah-19-8** [comment]
I removed .dart-tool and it solved for me.

**Comment by sumaro** [comment]
I encountered this error on the Windows system, which was resolved by following the steps below
1.Uninstalling encryption software
2.Delete flutter sdk 
https://www.dhiwise.com/post/ultimate-guide-to-uninstall-flutter-a-step-by-step-tutorial
3.Install flutter sdk

**Comment by matanlurey** [comment]
`.flutter-plugins` no longer exists!
