### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/madison/Program/flutter_1.20.2/bin/cache/artifacts/usbmuxd/iproxy.

### ISSUE THREAD

**Issue by zhuangsen** [flutter/flutter#65090]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=c5d9b9f8e8eb24d5ee82ad6d24cac283bb947677 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/madison/Program/flutter_1.20.2/bin/cache/artifacts/usbmuxd/iproxy.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:466:28)
#3      IOSDevicePortForwarder.forward (package:flutter_tools/src/ios/devices.dart:835:37)
<asynchronous suspension>
#4      buildObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:243:20)
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:158:18)
<asynchronous suspension>
#6      FallbackDiscovery.discover (package:flutter_tools/src/ios/fallback_discovery.dart:85:58)
<asynchronous suspension>
#7      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:438:52)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:541:54)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:368:31)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#18     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart)
#19     _rootRunUnary (dart:async/zone.dart:1198:47)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.20.2 at /Users/madison/Program/flutter_1.20.2
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/madison/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 201.7846.93
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554                            • android-x86 • Android 11 (API 30) (emulator)
    • Madison's iPad (mobile) • c5d9b9f8e8eb24d5ee82ad6d24cac283bb947677 • ios         • iOS 13.6.1

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6

**Comment by hamdikahloun** [comment]
Hi @zhuangsen 

Can you delete please all folders and files in /Users/madison/Program/flutter_1.20.2/bin/cache ,run `flutter doctor -v` and try again.

**Comment by darshankawar** [comment]
Hi @zhuangsen,
A [fix](https://github.com/flutter/flutter/pull/63540) was made recently related to lack of permisisons, and has been merged into master. You may switch to latest master and try again to see if it works for you.
Thanks.

**Comment by darshankawar** [comment]
sorry, accidentally closed it.

**Comment by zhuangsen** [comment]
> Hi @zhuangsen
> 
> Can you delete please all folders and files in /Users/madison/Program/flutter_1.20.2/bin/cache ,run `flutter doctor -v` and try again.

Thank you. The problem has been solved
