### ISSUE TITLE
flutter upgrade fails in powershell 

### ISSUE THREAD

**Issue by btinaugus** [flutter/flutter#65136]
## Steps to Reproduce

```
1 - PS C:\appli\flutter> flutter upgrade                                                                                    Building flutter tool...
Running pub upgrade...
ProcessException: Process exited abnormally:
fatal: Needed a single revision
  Command: git rev-parse --verify @{u}
2 - PS C:\appli\flutter> git rev-parse --verify "@{u}"                                                                      fatal: Needed a single revision
3 - PS C:\appli\flutter> flutter channel master                                                                             Switching to flutter channel 'master'...
git: Already on 'master'
git: M  bin/flutter.bat
git: M  bin/internal/update_dart_sdk.ps1
git: Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
5 - PS C:\appli\flutter> git rev-parse origin/master                                                                        280e6d6c017f50a36e725f719daa4c271ade770e
6 - PS C:\appli\flutter> flutter upgrade -f -v                                                                              [ +110 ms] executing: [C:\appli\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +75 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] ee69eebfbdcd0df57f8afc941acc2528587b965b
[   +1 ms] executing: [C:\appli\flutter/] git tag --points-at HEAD
[  +62 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [C:\appli\flutter/] git describe --match *.*.* --first-parent --long --tags
[  +99 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[   +1 ms] 1.22.0-9.0.pre-53-gee69eebfb
[  +27 ms] executing: [C:\appli\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +72 ms] executing: [C:\appli\flutter/] git tag --points-at HEAD
[  +82 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [C:\appli\flutter/] git describe --match *.*.* --first-parent --long --tags
[  +98 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[   +1 ms] 1.22.0-9.0.pre-53-gee69eebfb
[   +6 ms] executing: [C:\appli\flutter/] git fetch --tags
[+3603 ms] executing: [C:\appli\flutter/] git rev-parse --verify @{u}
[  +60 ms] fatal: Needed a single revision
[  +11 ms] "flutter upgrade" took 3 889ms.
[   +5 ms] ProcessException: Process exited abnormally:
           fatal: Needed a single revision
             Command: git rev-parse --verify @{u}
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      UpgradeCommandRunner.fetchRemoteRevision (package:flutter_tools/src/commands/upgrade.dart:237:9)
           <asynchronous suspension>
           #2      UpgradeCommandRunner.runCommandFirstHalf (package:flutter_tools/src/commands/upgrade.dart:103:43)
           #3      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:85:13)
           #4      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:60:27)
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
           #6      _rootRunUnary (dart:async/zone.dart:1198:47)
           #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #12     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #13     _rootRun (dart:async/zone.dart:1190:13)
           #14     _CustomZone.run (dart:async/zone.dart:1093:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +263 ms] ensureAnalyticsSent: 256ms
[  +10 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +4 ms] exiting with code 1
```

**Comment by TahaTesser** [comment]
Hi @btinaugus 
Can you please go to flutter setup and execute`git pull` then execute `flutter upgrade --verbose` and provide complete logs from it
Thank you

**Comment by TahaTesser** [comment]
Hi @btinaugus 
`Channel @U`? Is that actual output from doctor -v output? 

You might want to switch to a channel 
`flutter channel master`
`flutter upgrade -v`
`flutter doctor -v`

**Comment by JoeCodeswell** [comment]
I have the same problem. 
AND many problems since upgrading to Flutter 1.22.1: 
E.g. Running Flutter 1.22.1 newly created, example project yields:
```
Launching lib\main.dart on Chrome in debug mode...
ERROR - 2020-10-10 12:03:11.474593
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
[38;5;244mObject.noSuchMethod (dart:core)[39;49m
[38;5;248mDwdsInjector.middleware.<fn>.<fn> (package:dwds/src/handlers/injector.dart:51:41))[39;49m


Exited (1)
```
Here is what i did to try to fix the above.

1. check which channel is selected  => shows NO CHANNEL SELECTED!???

```powershell
PS C:\Users\joeco> flutter channel
Flutter channels:
  master
  dev
  beta
  stable
  Hixie-patch-1
  Hixie-patch-2
  experimental_skshaper
  flexible-drawer-header-height
  flutter-1.17-candidate.0
  flutter-1.17-candidate.1
  flutter-1.17-candidate.2
  flutter-1.17-candidate.3
  flutter-1.17-candidate.4
  flutter-1.17-candidate.5
  flutter-1.18-candidate.0
  flutter-1.18-candidate.1
  flutter-1.18-candidate.10
  flutter-1.18-candidate.11
  flutter-1.18-candidate.12
  flutter-1.18-candidate.13
  flutter-1.18-candidate.2
  flutter-1.18-candidate.3
  flutter-1.18-candidate.4
  flutter-1.18-candidate.5
  flutter-1.18-candidate.6
  flutter-1.18-candidate.7
  flutter-1.18-candidate.8
  flutter-1.18-candidate.9
  flutter-1.19-candidate.0
  flutter-1.19-candidate.1
  flutter-1.19-candidate.2
  flutter-1.19-candidate.3
  flutter-1.19-candidate.4
  flutter-1.19-candidate.5
  flutter-1.20-candidate.0
  flutter-1.20-candidate.1
  flutter-1.20-candidate.2
  flutter-1.20-candidate.3
  flutter-1.20-candidate.3.renyou_experiment
  flutter-1.20-candidate.4
  flutter-1.20-candidate.5
  flutter-1.20-candidate.6
  flutter-1.20-candidate.7
  flutter-1.20-candidate.8
  flutter-1.21-candidate.0
  flutter-1.21-candidate.1
  flutter-1.21-candidate.10
  flutter-1.21-candidate.2
  flutter-1.21-candidate.3
  flutter-1.21-candidate.4
  flutter-1.21-candidate.5
  flutter-1.21-candidate.6
  flutter-1.21-candidate.7
  flutter-1.21-candidate.8
  flutter-1.21-candidate.9
  flutter-1.22-candidate.0
  flutter-1.22-candidate.1
  flutter-1.22-candidate.10
  flutter-1.22-candidate.11
  flutter-1.22-candidate.12
  flutter-1.22-candidate.13
  flutter-1.22-candidate.2
  flutter-1.22-candidate.3
  flutter-1.22-candidate.4
  flutter-1.22-candidate.5
  flutter-1.22-candidate.6
  flutter-1.22-candidate.7
  flutter-1.22-candidate.8
  flutter-1.22-candidate.9
  flutter-1.23-candidate.0
  flutter-1.23-candidate.1
  flutter-1.23-candidate.10
  flutter-1.23-candidate.11
  flutter-1.23-candidate.12
  flutter-1.23-candidate.13
  flutter-1.23-candidate.2
  flutter-1.23-candidate.3
  flutter-1.23-candidate.4
  flutter-1.23-candidate.5
  flutter-1.23-candidate.6
  flutter-1.23-candidate.7
  flutter-1.23-candidate.8
  flutter-1.23-candidate.9
  revert-65109-revert-64988-bonjour-service
  revert-67561-revert-67441-migrate_flutter_driver
  revert-67566-revert-64678-popup-menu
  v1.12.13-hotfixes
  v1.4.5-hotfixes
  v1.4.6-hotfixes
  v1.4.9-hotfixes
  v1.5.4-hotfixes
  v1.7.8-hotfixes
  v1.9.1-hotfixes
```

2. run `flutter doctor`, 
```powershell
PS C:\Users\joeco> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel @u, 1.22.1, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] VS Code (version 1.50.0)
[√] VS Code, 32-bit edition
[√] Connected device (3 available)

! Doctor found issues in 2 categories.
PS C:\Users\joeco>
```

3. run `flutter channel stable`, 

```powershell
PS C:\Users\joeco> flutter channel stable
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:  * [new branch]      flutter-1.23-candidate.14 -> origin/flutter-1.23-candidate.14
git:  * [new branch]      flutter-1.23-candidate.15 -> origin/flutter-1.23-candidate.15
git:  * [new branch]      flutter-1.23-candidate.16 -> origin/flutter-1.23-candidate.16
git:    cb0bdb4..1a9d635  master     -> origin/master
git:  * [new branch]      revert-67757-fast_start_test -> origin/revert-67757-fast_start_test
git: Already on 'stable'
git: Your branch is up-to-date with 'origin/stable'.
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

PS C:\Users\joeco>
```

4. run `flutter upgrade`
```powershell
PS C:\Users\joeco> flutter upgrade
ProcessException: Process exited abnormally:
fatal: Needed a single revision
  Command: git rev-parse --verify @{u}
PS C:\Users\joeco>    
```

5. run `flutter doctor -v`
```powershell
PS C:\Users\joeco> flutter doctor -v
[√] Flutter (Channel @u, 1.22.1, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (2 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at C:\Users\joeco\AppData\Local\Android\sdk
    • Platform android-29, build-tools 30.0.0-rc1
    • ANDROID_HOME = C:\Users\joeco\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 193.6911.31
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\joeco\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] VS Code, 32-bit edition
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.51

! Doctor found issues in 2 categories.
PS C:\Users\joeco>
```

I am at a TOTAL LOSS. I hope you folks can help.
Thanks in advance.
Love and peace,
Joe Dorocak aka JoeCodeswell@gmail.com

**Comment by TahaTesser** [comment]
Hi @JoeCodeswell 
please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
