### ISSUE TITLE
[install error] Cannot extract a non-Windows file path from a file URI with an authority

### ISSUE THREAD

**Issue by iHTCboy** [flutter/flutter#65158]
* Mac mini
* macOS 10.15
* Xcode 11.7

## Steps to Reproduce

1.  git clone https://github.com/flutter/flutter.git
2. flutter doctor

## Logs

```
Downloading Dart SDK from Flutter engine 165abef0a2cb304ab000cbc9153c59e656c6680d...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  174M  100  174M    0     0   613k      0  0:04:50  0:04:50 --:--:--  661k
Building flutter tool...
Crash when compiling file://volumes/APPLE-HDD/Document/Coding/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart,
at character offset null:
Invalid argument(s): Exception when reading 'file://volumes/APPLE-HDD/Document/Coding/Flutter/flutter/packages/flutter_tools/.dart_tool/package_config.json': Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:537:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:551:32)
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:616:17)
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:484:32)
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:438:38)
<asynchronous suspension>
#5      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:74:49)
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#7      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#8      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#9      CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#10     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#11     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZoned (dart:async/zone.dart:1550:10)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#20     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#21     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#22     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#23     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#24     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#25     _rootRun (dart:async/zone.dart:1182:47)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#32     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:537:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:551:32)
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:616:17)
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:484:32)
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:438:38)
<asynchronous suspension>
#5      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:74:49)
#6      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#7      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:73:10)
#8      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:53:18)
#9      CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#10     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart)
#11     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZoned (dart:async/zone.dart:1550:10)
#18     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#19     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#20     generateKernel (package:front_end/src/kernel_generator_impl.dart:52:32)
#21     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:99:17)
#22     SingleShotCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:441:17)
#23     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:208:45)
#24     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#25     _rootRun (dart:async/zone.dart:1182:47)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#32     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#33     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#34     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by iHTCboy** [comment]
@pedromassangocode thanks！ 

try `/Volumes/APPLE-HDD/Document/Coding/Flutter/flutter/bin/flutter doctor` is install ok!  

thank you very much!

**Comment by papiro** [comment]
Experiencing this trying to do a fresh flutter install in a Docker container from the base ubuntu image. Path name has no special chars unlike the OP.

```
root@793658133dec:/# flutter                                                                                                                                                                                
Downloading Dart SDK from Flutter engine d1bc06f032f9d6c148ea6b96b48261d6f545004f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  246M  100  246M    0     0  32.4M      0  0:00:07  0:00:07 --:--:-- 35.4M
Building flutter tool...
Crash when compiling file://flutter/packages/flutter_tools/bin/flutter_tools.dart,
at character offset null:
Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      _Uri._toFilePath (dart:core/uri.dart:2725:7)
#1      _Uri.toFilePath (dart:core/uri.dart:2720:65)
...
```

**Comment by pedromassangocode** [comment]
Hi @papiro 
Please open a new issue for your use-case.

**Comment by MarcusCambio** [comment]
I also had this issue without special characters in the path, just running flutter once with the absolute path downloaded everything needed and resolved the issue for me.
