### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\flutter\flutter\bin\cache\flutter_web_sdk\kernel\amd\dart_sdk.js', OS Error: Cannot create a file when that file already exists., errno = 183

### ISSUE THREAD

**Issue by farisshomali** [flutter/flutter#65162]
## Command
```
flutter run -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot copy file to 'C:\flutter\flutter\bin\cache\flutter_web_sdk\kernel\amd\dart_sdk.js', OS Error: Cannot create a file when that file already exists.
, errno = 183
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      FlutterWebSdk.updateInner (package:flutter_tools/src/cache.dart:725:16)
<asynchronous suspension>
#5      CachedArtifact.update (package:flutter_tools/src/cache.dart:589:11)
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:455:24)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:879:27)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     DeviceBasedDevelopmentArtifacts.requiredArtifacts (package:flutter_tools/src/runner/flutter_command.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
```
```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-9.2.pre at C:\flutter\flutter
    • Framework revision 81a45ec2e5 (7 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\fares shomali\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\fares shomali\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.44

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 5a2153d340f3c591d84d05d4634d34da32006943
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
google_sign_in-4.5.3
google_sign_in_web-0.9.1+1
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1+1

**Comment by jonahwilliams** [comment]
Fixed by https://github.com/flutter/flutter/pull/66461
