### ISSUE TITLE
Crashy the project Demo Sentry URI failed

### ISSUE THREAD

**Issue by sbigtree** [flutter/flutter#65165]
E/flutter (30777): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: FormatException: Invalid empty scheme (at character 1)
E/flutter (30777): :///api/4d6ccf3384a14719a5dc404e52954c33/store/
E/flutter (30777): ^
E/flutter (30777): 
E/flutter (30777): #0      _Uri._fail (dart:core/uri.dart:1628:5)
E/flutter (30777): #1      new _Uri.notSimple (dart:core/uri.dart:1461:9)
E/flutter (30777): #2      Uri.parse (dart:core/uri.dart:1022:17)
E/flutter (30777): #3      _fromUriOrString (package:http/src/base_client.dart:108:50)
E/flutter (30777): #4      BaseClient._sendUnstreamed (package:http/src/base_client.dart:75:35)
E/flutter (30777): #5      BaseClient.post (package:http/src/base_client.dart:32:7)
E/flutter (30777): #6      SentryClient.capture (package:sentry/src/base.dart:182:48)
E/flutter (30777): #7      SentryClient.captureException (package:sentry/src/base.dart:210:12)
E/flutter (30777): #8      main (package:crashy/main.dart:99:18)
E/flutter (30777): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:233:25)
E/flutter (30777): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (30777): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (30777): #12     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (30777): #13     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (30777): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:225:5)
E/flutter (30777): #15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (30777): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (30777):

**Comment by sbigtree** [comment]
重复了
