### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, path

### ISSUE THREAD

**Issue by akkav** [flutter/flutter#65173]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot create file, path = 'C:\Users\akash\Downloads\[FreeCourseSite.com] Udemy - The Complete Flutter UI Masterclass  iOS & Android in Dart\02 Food Delivery App\012 flutter-food-delivery-ui\flutter_food_delivery_ui\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: The system cannot find the path specified.
, errno = 3)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.createSync (dart:io/file_impl.dart:283:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:27:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:641:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1079:11)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:232:11)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#10     _rootRunUnary (dart:async/zone.dart:1192:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#17     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (9 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\akash\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.48.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aedbb1835bd6eb44550293d57d4d124f19901f0

**Comment by TahaTesser** [comment]
Hi @akkav 
Looks like you're running an older stable version,  This is probably fixed

Can you upgrade to latest `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by adilwahla** [comment]
hi got same error how to resolve it
