### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout

### ISSUE THREAD

**Issue by haidar786** [flutter/flutter#65206]
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed
Stdout:

Stderr:
unzip:  cannot find or open /Users/hussnainhaidar/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip, /Users/hussnainhaidar/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.zip or /Users/hussnainhaidar/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/75d35d37aa818c40ffb521a8165dbe7d3c1cb8c4/fonts.zip.ZIP.
 Command: unzip, OS error code: 9
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:459:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:226:19)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:648:16)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Net.fetchUrl (package:flutter_tools/src/base/net.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.21.0-9.2.pre at /Users/hussnainhaidar/flutter
    • Framework revision 81a45ec2e5 (7 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/hussnainhaidar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/hussnainhaidar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/hussnainhaidar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 85.0.4183.83

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Hi @haidar786,
There's similar open issue describing your case, [52437](https://github.com/flutter/flutter/issues/52437).
Please follow-up there for updates and any questions.
Closing this as duplicate.
