### ISSUE TITLE
[tool_crash] NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'Receiver: Closure: (_SyncIterator<Package>) => boolTried calling: MutablePackageTree.allPackages()Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool

### ISSUE THREAD

**Issue by srinivas-krishnamurthy** [flutter/flutter#65205]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
Receiver: Closure: (_SyncIterator<Package>) => bool
Tried calling: MutablePackageTree.allPackages()
Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      new SimplePackageConfig (package:package_config/src/package_config_impl.dart:26:36)
#3      parsePackageConfigJson (package:package_config/src/package_config_json.dart:213:10)
#4      parsePackageConfigBytes (package:package_config/src/package_config_json.dart:45:10)
#5      readAnyConfigFile (package:package_config/src/package_config_io.dart:55:18)
<asynchronous suspension>
#6      readAnyConfigFileUri (package:package_config/src/package_config_io.dart:76:14)
#7      loadPackageConfigUri (package:package_config/package_config.dart:88:5)
#8      DartUri._loadPackageConfig (package:dwds/src/utilities/dart_uri.dart:35:30)
#9      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:57:13)
#10     AppInspector._initialize (package:dwds/src/debugging/inspector.dart:87:19)
<asynchronous suspension>
#11     AppInspector.initialize (package:dwds/src/debugging/inspector.dart:145:24)
#12     ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:165:37)
<asynchronous suspension>
#13     ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:133:23)
#14     DebugService.start (package:dwds/src/services/debug_service.dart:140:55)
#15     DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:156:25)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
```
```
[✓] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.17.0 at C:\Flutter
    • Framework revision d3ed9ec945 (5 months ago), 2020-04-06 14:07:34 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\SK\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\SK\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.47.2)
    • VS Code at C:\Users\SK\AppData\Local\Programs\Microsoft VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • ONE E1003  • 2c5bc036   • android-arm    • Android 6.0.1 (API 23)
    • Chrome     • chrome     • web-javascript • Google Chrome 85.0.4183.83
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: d3ed9ec945f8869f0e136c357d0c2a6be2b60c98
### Plugins
firebase_auth-0.15.5+3
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2

**Comment by darshankawar** [comment]
Hi @srinivas-krishnamurthy,
There's similar [issue](https://github.com/flutter/flutter/issues/59245) describing your case with possible [solution](https://github.com/flutter/flutter/issues/59245#issuecomment-660031528). Can you try that and see if it works for you ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
