### ISSUE TITLE
webview_flutter插件加载h5页面时，h5页面中的视频播放不了

### ISSUE THREAD

**Issue by ZCHUANGJie** [flutter/flutter#65232]
I/libOpenSLES(18158): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
D/AudioTrack(18158): Client defaulted notificationFrames to 1922 for frameCount 3844
I/cr_MediaCodecBridge(18158): create MediaCodec video decoder, mime video/avc
I/OMXClient(18158): Treble IOmx obtained
W/VideoCapabilities(18158): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(18158): Unrecognized profile 2130706434 for video/avc
I/MediaCodec(18158): MediaCodec will operate in async mode
D/SurfaceUtils(18158): connecting to surface 0x7db3287010, reason connectToSurface
I/MediaCodec(18158): [OMX.qcom.video.decoder.avc] setting surface generation to 18593800
D/SurfaceUtils(18158): disconnecting from surface 0x7db3287010, reason connectToSurface(reconnect)
D/SurfaceUtils(18158): connecting to surface 0x7db3287010, reason connectToSurface(reconnect)
I/ExtendedACodec(18158): setupVideoDecoder()
I/ExtendedACodec(18158): Decoder will be in frame by frame mode
D/SurfaceUtils(18158): set up nativeWindow 0x7db3287010 for 636x360, color 0x7fa30c06, rotation 0, usage 0x20002900
W/GrallocMapperPassthrough(18158): buffer descriptor with invalid usage bits 0x2000
I/chatty  (18158): uid=10455(u0_a455) CodecLooper identical 1 line
W/GrallocMapperPassthrough(18158): buffer descriptor with invalid usage bits 0x2000
W/GrallocMapperPassthrough(18158): buffer descriptor with invalid usage bits 0x2000
E/ACodec  (18158): [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
E/ACodec  (18158): signalError(omxError 0x80001009, internalError -2147483648)
E/MediaCodec(18158): Codec reported err 0x80001009, actionCode 0, while in state 6
D/SurfaceUtils(18158): disconnecting from surface 0x7db3287010, reason disconnectFromSurface
E/cr_MediaCodecBridge(18158): MediaCodec.onError: android.media.MediaCodec.error_neg_2147479543
W/cr_MediaCodecBridge(18158): Releasing: OMX.qcom.video.decoder.avc
D/AudioTrack(18158): stop() called with 3844 frames delivered
D/        (18158): PlayerBase::stop() from IPlayer
E/Surface (18158): getSlotFromBufferLocked: unknown buffer: 0x7db164ff80
W/ACodec  (18158): [OMX.qcom.video.decoder.avc] can not return buffer 27 to native window
E/Surface (18158): getSlotFromBufferLocked: unknown buffer: 0x7db1680080
W/ACodec  (18158): [OMX.qcom.video.decoder.avc] can not return buffer 26 to native window
E/Surface (18158): getSlotFromBufferLocked: unknown buffer: 0x7dc5061a80
W/ACodec  (18158): [OMX.qcom.video.decoder.avc] can not return buffer 25 to native window
E/Surface (18158): getSlotFromBufferLocked: unknown buffer: 0x7db164f800
W/ACodec  (18158): [OMX.qcom.video.decoder.avc] can not return buffer 24 to native window
W/cr_MediaCodecBridge(18158): Codec released

**Comment by pedromassangocode** [comment]
Hi @ZCHUANGJie 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` a minimal complete reproducible code sample and steps to reproduce this issue?
Thank you

**Comment by ZCHUANGJie** [comment]
C:\ewhale\work\gitProject\nengbangjiubang>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.1016], locale zh-CN)
    • Flutter version 1.12.13+hotfix.8 at C:\ewhale\common\flutter
    • Framework revision 0b8abb4724 (7 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\EDZ\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\EDZ\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\EDZ\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • MI 5s Plus • cdb9adec • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

**Comment by ZCHUANGJie** [comment]
ms] Exit code 0 from: C:\Users\EDZ\AppData\Local\Android\Sdk\build-tools\29.0.1\aapt dump xmltree C:\ewhale\work\gitProject\nengbangjiubang\build\app\outputs\apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.paoding.nengbangjiubang" (Raw: "com.paoding.nengbangjiubang")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x13
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=23)
                 A: android:name(0x01010003)="android.permission.RECORD_AUDIO" (Raw: "android.permission.RECORD_AUDIO")
               E: uses-permission (line=24)
                 A: android:name(0x01010003)="android.permission.CAMERA" (Raw: "android.permission.CAMERA")
               E: uses-permission (line=25)
                 A: android:name(0x01010003)="android.permission.VIBRATE" (Raw: "android.permission.VIBRATE")
               E: uses-permission (line=26)
                 A: android:name(0x01010003)="android.permission.CHANGE_NETWORK_STATE" (Raw: "android.permission.CHANGE_NETWORK_STATE")
               E: uses-permission (line=27)
                 A: android:name(0x01010003)="android.permission.GET_TASKS" (Raw: "android.permission.GET_TASKS")
               E: uses-permission (line=28)
                 A: android:name(0x01010003)="android.permission.MODIFY_AUDIO_SETTINGS" (Raw: "android.permission.MODIFY_AUDIO_SETTINGS")
               E: uses-permission (line=29)
                 A: android:name(0x01010003)="android.permission.RECEIVE_BOOT_COMPLETED" (Raw: "android.permission.RECEIVE_BOOT_COMPLETED")
               E: uses-permission (line=30)
                 A: android:name(0x01010003)="com.android.launcher.permission.READ_SETTINGS" (Raw: "com.android.launcher.permission.READ_SETTINGS")
               E: uses-permission (line=31)
                 A: android:name(0x01010003)="android.permission.BROADCAST_STICKY" (Raw: "android.permission.BROADCAST_STICKY")
               E: uses-permission (line=32)
                 A: android:name(0x01010003)="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" (Raw: "android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS")
               E: uses-permission (line=33)
                 A: android:name(0x01010003)="android.permission.SYSTEM_ALERT_WINDOW" (Raw: "android.permission.SYSTEM_ALERT_WINDOW")
               E: uses-permission (line=34)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=35)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
               E: uses-permission (line=36)
                 A: android:name(0x01010003)="android.permission.ACCESS_COARSE_LOCATION" (Raw: "android.permission.ACCESS_COARSE_LOCATION")
               E: uses-permission (line=37)
                 A: android:name(0x01010003)="android.permission.ACCESS_FINE_LOCATION" (Raw: "android.permission.ACCESS_FINE_LOCATION")
               E: uses-permission (line=38)
                 A: android:name(0x01010003)="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" (Raw: "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS")
               E: uses-permission (line=39)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=40)
                 A: android:name(0x01010003)="android.permission.ACCESS_WIFI_STATE" (Raw: "android.permission.ACCESS_WIFI_STATE")
               E: uses-permission (line=41)
                 A: android:name(0x01010003)="android.permission.CHANGE_WIFI_STATE" (Raw: "android.permission.CHANGE_WIFI_STATE")
               E: uses-permission (line=42)
                 A: android:name(0x01010003)="android.permission.READ_PHONE_STATE" (Raw: "android.permission.READ_PHONE_STATE")
               E: uses-permission (line=43)
                 A: android:name(0x01010003)="android.permission.BLUETOOTH" (Raw: "android.permission.BLUETOOTH")
               E: uses-permission (line=44)
                 A: android:name(0x01010003)="android.permission.BLUETOOTH_ADMIN" (Raw: "android.permission.BLUETOOTH_ADMIN")
               E: uses-permission (line=45)
                 A: android:name(0x01010003)="android.permission.ACCESS_MEDIA_LOCATION" (Raw: "android.permission.ACCESS_MEDIA_LOCATION")
               E: uses-permission (line=46)
                 A: android:name(0x01010003)="android.permission.FLASHLIGHT" (Raw: "android.permission.FLASHLIGHT")
               E: uses-feature (line=48)
                 A: android:name(0x01010003)="android.hardware.camera" (Raw: "android.hardware.camera")
               E: uses-feature (line=49)
                 A: android:name(0x01010003)="android.hardware.camera.autofocus" (Raw: "android.hardware.camera.autofocus")
               E: uses-permission (line=51)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=52)
                 A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw: "com.google.android.c2dm.permission.RECEIVE")
               E: permission (line=54)
                 A: android:name(0x01010003)="com.paoding.nengbangjiubang.permission.C2D_MESSAGE" (Raw: "com.paoding.nengbangjiubang.permission.C2D_MESSAGE")
                 A: android:protectionLevel(0x01010009)=(type 0x11)0x2
               E: uses-permission (line=58)
                 A: android:name(0x01010003)="com.paoding.nengbangjiubang.permission.C2D_MESSAGE" (Raw: "com.paoding.nengbangjiubang.permission.C2D_MESSAGE")
               E: application (line=60)

**Comment by ZCHUANGJie** [comment]
这是代码
Builder(
        builder: (BuildContext context) {
          return WebView(
            initialUrl: "https://ceshi.xzypapp.com/console/#/articleEditor/68",
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (
                WebViewController webViewController,
                ) {
              _controller.complete(webViewController);
              _webViewController = webViewController;
              print("js==========");
//                _webViewController
//                    .evaluateJavascript("window.location.href")
//                    .then((data) {
//                  print("555555555555$data");
//                });
              /* webViewController.evaluateJavascript(
                'localStorage.setItem("cddUser",JSON.stringify({"id":135,"token":"11111111111111"})); ')
                .then((result) {
                  webViewController.reload();*/
              //flutterWebviewPlugin.reload();
              //});
            },
            javascriptChannels: <JavascriptChannel>[
              _toasterJavascriptChannel(context),
            ].toSet(),
            onPageFinished: (String url) {
              print('Page finished loading: $url');
              //addToken(_webViewController);
              print("12323312313123");
              print("sssssss === ${_webViewController.currentUrl()}");
              _webViewController
                  .evaluateJavascript("window.location.href")
                  .then((data) {
                print("555555555555$data");
              });
              print('========reload');

              //_webViewController.reload();
            },

          );
        }
      ),

**Comment by pedromassangocode** [comment]
Hi @ZCHUANGJie 
Please provide a code that does not contains any third-party plugin and that I can just copy/paste and reproduce the issue. Please provide the steps to reproduce the issue you are facing.
Thank you

**Comment by ZCHUANGJie** [comment]
[        ] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +9 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7de5251120, isolate: {type: @Isolate, fixedId: true, id: isolates/3673777968790387, name: main.dart$main-3673777968790387, number: 3673777968790387}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x7de5251120.
[   +2 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on MI 5s Plus is available at: http://127.0.0.1:57830/8Kaf5EDn4Ag=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+1943 ms] I/zygote64(27008): Do partial code cache collection, code=61KB, data=48KB
[   +1 ms] I/zygote64(27008): After code cache collection, code=61KB, data=48KB
[        ] I/zygote64(27008): Increasing code cache capacity to 256KB
[ +627 ms] D/NetworkSecurityConfig(27008): No Network Security Config specified, using platform default
[+1457 ms] I/chromium(27008): [INFO:CONSOLE(10)] "'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[   +1 ms] I/chromium(27008): [INFO:CONSOLE(10)] "'webkitURL' is deprecated. Please use 'URL' instead.", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[   +9 ms] I/chromium(27008): [INFO:CONSOLE(10)] "[system]", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[  +50 ms] I/chatty  (27008): uid=10469(u0_a469) com.ewhale.flutterappwebview identical 7 lines
[        ] I/chromium(27008): [INFO:CONSOLE(10)] "[system]", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[ +157 ms] I/chromium(27008): [INFO:CONSOLE(10)] "[object HTMLDivElement]", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[   +1 ms] I/chromium(27008): [INFO:CONSOLE(10)] "619", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[        ] I/chromium(27008): [INFO:CONSOLE(10)] "393", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[        ] I/chromium(27008): [INFO:CONSOLE(10)] "619", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[        ] I/chromium(27008): [INFO:CONSOLE(10)] "619", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[        ] I/chromium(27008): [INFO:CONSOLE(10)] "111111111111", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[   +4 ms] I/chromium(27008): [INFO:CONSOLE(10)] "[object Object]", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[        ] I/chromium(27008): [INFO:CONSOLE(10)] "<p class="ql-align-center">发射点发射点</p><iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://ceshi.xzypapp.com/attachment/mp4/6214/9024_2770.mp4"></iframe><p class="ql-align-center"><br></
p>",
source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[   +2 ms] I/chromium(27008): [INFO:CONSOLE(10)] "有没有进来", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[   +1 ms] I/chromium(27008): [INFO:CONSOLE(10)] "啥", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[        ] I/chromium(27008): [INFO:CONSOLE(10)] "ReferenceError: Toaster is not defined", source: https://ceshi.xzypapp.com/console/static/vconsole.min.js (10)
[  +14 ms] I/flutter (27008): Page finished loading: https://ceshi.xzypapp.com/console/#/articleEditor/68
[        ] I/flutter (27008): 12323312313123
[   +2 ms] I/flutter (27008): sssssss === Instance of 'Future<String>'
[   +7 ms] I/flutter (27008): ========reload
[  +52 ms] I/flutter (27008): 555555555555"https://ceshi.xzypapp.com/console/#/articleEditor/68"
[ +265 ms] D/        (27008): PlayerBase::PlayerBase()
[        ] D/        (27008): TrackPlayerBase::TrackPlayerBase()
[        ] I/libOpenSLES(27008): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
[  +12 ms] D/AudioTrack(27008): Client defaulted notificationFrames to 1922 for frameCount 3844
[  +15 ms] I/cr_MediaCodecBridge(27008): create MediaCodec video decoder, mime video/avc
[  +31 ms] I/OMXClient(27008): Treble IOmx obtained
[ +140 ms] W/VideoCapabilities(27008): Unrecognized profile 2130706433 for video/avc
[        ] W/VideoCapabilities(27008): Unrecognized profile 2130706434 for video/avc
[   +9 ms] I/MediaCodec(27008): MediaCodec will operate in async mode
[   +5 ms] D/SurfaceUtils(27008): connecting to surface 0x7dc234e010, reason connectToSurface
[        ] I/MediaCodec(27008): [OMX.qcom.video.decoder.avc] setting surface generation to 27656193
[        ] D/SurfaceUtils(27008): disconnecting from surface 0x7dc234e010, reason connectToSurface(reconnect)
[        ] D/SurfaceUtils(27008): connecting to surface 0x7dc234e010, reason connectToSurface(reconnect)
[        ] I/ExtendedACodec(27008): setupVideoDecoder()
[        ] I/ExtendedACodec(27008): Decoder will be in frame by frame mode
[  +93 ms] D/SurfaceUtils(27008): set up nativeWindow 0x7dc234e010 for 636x360, color 0x7fa30c06, rotation 0, usage 0x20002900
[        ] W/GrallocMapperPassthrough(27008): buffer descriptor with invalid usage bits 0x2000
[        ] W/GrallocMapperPassthrough(27008): buffer descriptor with invalid usage bits 0x2000
[        ] W/GrallocMapperPassthrough(27008): buffer descriptor with invalid usage bits 0x2000
[  +32 ms] W/GrallocMapperPassthrough(27008): buffer descriptor with invalid usage bits 0x2000
[   +1 ms] E/ACodec  (27008): [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
[   +1 ms] E/ACodec  (27008): signalError(omxError 0x80001009, internalError -2147483648)
[        ] E/MediaCodec(27008): Codec reported err 0x80001009, actionCode 0, while in state 6
[        ] D/SurfaceUtils(27008): disconnecting from surface 0x7dc234e010, reason disconnectFromSurface
[        ] E/cr_MediaCodecBridge(27008): MediaCodec.onError: android.media.MediaCodec.error_neg_2147479543
[        ] E/cr_MediaCodecBridge(27008): Failed to queue input buffer
[        ] E/cr_MediaCodecBridge(27008): java.lang.IllegalStateException
[        ] E/cr_MediaCodecBridge(27008):        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
[        ] E/cr_MediaCodecBridge(27008):        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2334)
[        ] E/cr_MediaCodecBridge(27008):        at org.chromium.media.MediaCodecBridge.queueInputBuffer(PG:164)
[  +24 ms] W/cr_MediaCodecBridge(27008): Releasing: OMX.qcom.video.decoder.avc
[        ] W/chromium(27008): [WARNING:audio_sync_reader.cc(187)] ASR: No room in socket buffer.: Broken pipe (32)
[  +30 ms] D/AudioTrack(27008): stop() called with 15364 frames delivered
[        ] D/        (27008): PlayerBase::stop() from IPlayer
[        ] E/Surface (27008): getSlotFromBufferLocked: unknown buffer: 0x7db6d48580
[        ] W/ACodec  (27008): [OMX.qcom.video.decoder.avc] can not return buffer 27 to native window
[        ] E/Surface (27008): getSlotFromBufferLocked: unknown buffer: 0x7db681a700
[        ] W/ACodec  (27008): [OMX.qcom.video.decoder.avc] can not return buffer 26 to native window
[        ] E/Surface (27008): getSlotFromBufferLocked: unknown buffer: 0x7db6698100
[   +1 ms] W/ACodec  (27008): [OMX.qcom.video.decoder.avc] can not return buffer 25 to native window
[   +1 ms] E/Surface (27008): getSlotFromBufferLocked: unknown buffer: 0x7db681a780
[        ] W/ACodec  (27008): [OMX.qcom.video.decoder.avc] can not return buffer 24 to native window
[        ] W/cr_MediaCodecBridge(27008): Codec released
[ +310 ms] I/zygote64(27008): Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
[ +505 ms] I/zygote64(27008): Do full code cache collection, code=124KB, data=96KB
[   +1 ms] I/zygote64(27008): After code cache collection, code=100KB, data=67KB
[+2053 ms] I/cr_MediaCodecBridge(27008): create MediaCodec video decoder, mime video/avc
[  +53 ms] I/OMXClient(27008): Treble IOmx obtained
[  +42 ms] W/VideoCapabilities(27008): Unrecognized profile 2130706433 for video/avc
[        ] W/VideoCapabilities(27008): Unrecognized profile 2130706434 for video/avc
[   +1 ms] I/MediaCodec(27008): MediaCodec will operate in async mode
[        ] D/SurfaceUtils(27008): connecting to surface 0x7dbb80f010, reason connectToSurface
[        ] I/MediaCodec(27008): [OMX.qcom.video.decoder.avc] setting surface generation to 27656194
[        ] D/SurfaceUtils(27008): disconnecting from surface 0x7dbb80f010, reason connectToSurface(reconnect)
[        ] D/SurfaceUtils(27008): connecting to surface 0x7dbb80f010, reason connectToSurface(reconnect)
[        ] I/ExtendedACodec(27008): setupVideoDecoder()
[   +3 ms] I/ExtendedACodec(27008): Decoder will be in frame by frame mode
[  +54 ms] D/SurfaceUtils(27008): set up nativeWindow 0x7dbb80f010 for 636x360, color 0x7fa30c06, rotation 0, usage 0x20002900
[  +13 ms] W/GrallocMapperPassthrough(27008): buffer descriptor with invalid usage bits 0x2000
[        ] W/GrallocMapperPassthrough(27008): buffer descriptor with invalid usage bits 0x2000
[  +24 ms] I/chatty  (27008): uid=10469(u0_a469) CodecLooper identical 1 line
[   +8 ms] W/GrallocMapperPassthrough(27008): buffer descriptor with invalid usage bits 0x2000
[        ] E/ACodec  (27008): [OMX.qcom.video.decoder.avc] ERROR(0x80001009)
[        ] E/ACodec  (27008): signalError(omxError 0x80001009, internalError -2147483648)
[        ] E/MediaCodec(27008): Codec reported err 0x80001009, actionCode 0, while in state 6
[        ] D/SurfaceUtils(27008): disconnecting from surface 0x7dbb80f010, reason disconnectFromSurface
[        ] E/MediaCodec(27008): getBufferAndFormat - not executing
[        ] E/cr_MediaCodecBridge(27008): Failed to get input buffer
[        ] E/cr_MediaCodecBridge(27008): java.lang.IllegalStateException
[        ] E/cr_MediaCodecBridge(27008):        at android.media.MediaCodec.getBuffer(Native Method)
[        ] E/cr_MediaCodecBridge(27008):        at android.media.MediaCodec.getInputBuffer(MediaCodec.java:3044)
[        ] E/cr_MediaCodecBridge(27008):        at org.chromium.media.MediaCodecBridge.getInputBuffer(PG:152)
[        ] E/chromium(27008): [ERROR:media_codec_bridge_impl.cc(626)] GetInputBuffer failed
[        ] W/cr_MediaCodecBridge(27008): Releasing: OMX.qcom.video.decoder.avc
[        ] D/AudioTrack(27008): stop() called with 19204 frames delivered
[        ] E/cr_MediaCodecBridge(27008): MediaCodec.onError: android.media.MediaCodec.error_neg_2147479543
[        ] D/        (27008): PlayerBase::stop() from IPlayer
[   +3 ms] E/Surface (27008): getSlotFromBufferLocked: unknown buffer: 0x7db6cbc080
[        ] W/ACodec  (27008): [OMX.qcom.video.decoder.avc] can not return buffer 27 to native window
[        ] E/Surface (27008): getSlotFromBufferLocked: unknown buffer: 0x7db6cbc200
[        ] W/ACodec  (27008): [OMX.qcom.video.decoder.avc] can not return buffer 26 to native window
[        ] E/Surface (27008): getSlotFromBufferLocked: unknown buffer: 0x7db6cbc280
[        ] W/ACodec  (27008): [OMX.qcom.video.decoder.avc] can not return buffer 25 to native window
[        ] E/Surface (27008): getSlotFromBufferLocked: unknown buffer: 0x7db6cbc300
[        ] W/ACodec  (27008): [OMX.qcom.video.decoder.avc] can not return buffer 24 to native window
[  +33 ms] W/cr_MediaCodecBridge(27008): Codec released

**Comment by ZCHUANGJie** [comment]
[        ] [   +9 ms] Done persisting file store
[        ] [   +2 ms] build succeeded.
[        ] [  +23 ms] "flutter assemble" took 5,518ms.
[  +96 ms] > Task :app:packLibsflutterBuildDebug
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :webview_flutter:preBuild UP-TO-DATE
[        ] > Task :webview_flutter:preDebugBuild UP-TO-DATE
[        ] > Task :webview_flutter:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :webview_flutter:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[  +94 ms] > Task :app:checkDebugManifest
[        ] > Task :app:generateDebugBuildConfig
[        ] > Task :webview_flutter:checkDebugManifest
[        ] > Task :webview_flutter:compileDebugRenderscript NO-SOURCE
[        ] > Task :webview_flutter:generateDebugBuildConfig
[        ] > Task :webview_flutter:generateDebugResValues
[        ] > Task :webview_flutter:generateDebugResources
[        ] > Task :webview_flutter:packageDebugResources
[ +197 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[   +1 ms] > Task :webview_flutter:javaPreCompileDebug
[        ] > Task :app:mergeDebugShaders
[        ] > Task :app:compileDebugShaders
[        ] > Task :app:generateDebugAssets
[        ] > Task :webview_flutter:mergeDebugShaders
[        ] > Task :webview_flutter:compileDebugShaders
[        ] > Task :webview_flutter:generateDebugAssets
[        ] > Task :webview_flutter:packageDebugAssets
[        ] > Task :app:mergeDebugAssets
[ +199 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:mainApkListPersistenceDebug
[   +1 ms] > Task :webview_flutter:processDebugManifest
[   +2 ms] > Task :webview_flutter:parseDebugLibraryResources
[  +89 ms] > Task :app:generateDebugResValues
[        ] > Task :app:generateDebugResources
[ +306 ms] > Task :app:createDebugCompatibleScreenManifests
[ +106 ms] > Task :app:processDebugManifest
[  +92 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +2 ms] > Task :webview_flutter:processDebugJavaRes NO-SOURCE
[        ] > Task :webview_flutter:generateDebugRFile
[ +790 ms] > Task :webview_flutter:compileDebugJavaWithJavac
[   +8 ms] ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
[   +2 ms] ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
[        ] ע: C:\ewhale\common\flutter\.pub-cache\hosted\pub.flutter-io.cn\webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.javaʹ����δ�������ȫ�Ĳ�����
[        ] ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
[        ] > Task :app:mergeDebugResources

**Comment by pedromassangocode** [comment]
Hi @ZCHUANGJie 
Please provide a code that does not contains any third-party plugin and that I can just copy/paste and reproduce the issue and the steps to reproduce.
Thank you

**Comment by iapicca** [comment]
@ZCHUANGJie you may want to run `flutter upgrade -f`
