### ISSUE TITLE
Flaky problem with zip files in gradle task on Windows

### ISSUE THREAD

**Issue by flar** [flutter/flutter#65277]
We keep seeing the following error on Windows bots where it tries to download a gradle zip and gets an error opening it. Here is a recent case from the following run:

https://github.com/flutter/flutter/runs/1074453958

```
"C:\Windows\Temp\flutter sdk\bin\flutter" exit code: 0

Telling Gradle to shut down (JAVA_HOME=C:\Program Files\Java\jdk1.8.0_211)

Executing: C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.60b904cd\gradlew.bat --stop in C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.60b904cd with environment {JAVA_HOME: C:\Program Files\Java\jdk1.8.0_211}
stdout: Unzipping C:\Users\ContainerAdministrator\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip to C:\Users\ContainerAdministrator\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb
stderr: Exception in thread "main" java.util.zip.ZipException: error in opening zip file
stderr: 	at java.util.zip.ZipFile.open(Native Method)
stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
stderr: 	at org.gradle.wrapper.Install.unzip(Install.java:214)
stderr: 	at org.gradle.wrapper.Install.access$600(Install.java:27)
stderr: 	at org.gradle.wrapper.Install$1.call(Install.java:74)
stderr: 	at org.gradle.wrapper.Install$1.call(Install.java:48)
stderr: 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
stderr: 	at org.gradle.wrapper.Install.createDist(Install.java:48)
stderr: 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
stderr: 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
"C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.60b904cd\gradlew.bat" exit code: 1


Task result:
{
  "success": false,
  "reason": "Gradle exited with error"
}
```

On successful runs this zip file is not downloaded or unzipped. Is this a configuration error on some of the bots?

Here is the successful run that immediately preceded the one above: https://cirrus-ci.com/task/6210012252995584

**Comment by digiter** [comment]
In the [successful build](https://api.cirrus-ci.com/v1/task/6210012252995584/logs/main.log), `dev/devicelab/lib/framework/runner.dart` ran a command for "Telling Gradle to shut down":

```
Telling Gradle to shut down (JAVA_HOME=C:\Program Files\Java\jdk1.8.0_211)

Executing: C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.cf78968b\gradlew.bat --stop in C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.cf78968b with environment {JAVA_HOME: C:\Program Files\Java\jdk1.8.0_211}
stdout: Downloading https://services.gradle.org/distributions/gradle-5.6.2-all.zip
stdout: ......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
stdout: Unzipping C:\Users\ContainerAdministrator\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip to C:\Users\ContainerAdministrator\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb
stdout: 
stdout: Welcome to Gradle 5.6.2!
stdout: 
stdout: Here are the highlights of this release:
stdout:  - Incremental Groovy compilation
stdout:  - Groovy compile avoidance
stdout:  - Test fixtures for Java projects
stdout:  - Manage plugin versions via settings script
stdout: 
stdout: For more details see https://docs.gradle.org/5.6.2/release-notes.html
stdout: 
stdout: No Gradle daemons are running.
"C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.cf78968b\gradlew.bat" exit code: 0


Task result:
{
  "success": true,
  "data": null,
  "benchmarkScoreKeys": []
}

```

While [the failed build](https://api.cirrus-ci.com/v1/task/6382433446658048/logs/main.log) can not download gradle:
```
Telling Gradle to shut down (JAVA_HOME=C:\Program Files\Java\jdk1.8.0_211)

Executing: C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.c8e7377f\gradlew.bat --stop in C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.c8e7377f with environment {JAVA_HOME: C:\Program Files\Java\jdk1.8.0_211}
stdout: Downloading https://services.gradle.org/distributions/gradle-5.6.2-all.zip
stdout: ........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
stdout: Unzipping C:\Users\ContainerAdministrator\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip to C:\Users\ContainerAdministrator\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb
stderr: Exception in thread "main" java.util.zip.ZipException: error in opening zip file
stderr: 	at java.util.zip.ZipFile.open(Native Method)
stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
stderr: 	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
stderr: 	at org.gradle.wrapper.Install.unzip(Install.java:214)
stderr: 	at org.gradle.wrapper.Install.access$600(Install.java:27)
stderr: 	at org.gradle.wrapper.Install$1.call(Install.java:74)
stderr: 	at org.gradle.wrapper.Install$1.call(Install.java:48)
stderr: 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
stderr: 	at org.gradle.wrapper.Install.createDist(Install.java:48)
stderr: 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
stderr: 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
"C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_shutdown_gradle.c8e7377f\gradlew.bat" exit code: 1


Task result:
{
  "success": true,
  "data": null,
  "benchmarkScoreKeys": []
}
```

So the failure looks like a network hiccup, can we make `dev/devicelab/lib/framework/runner.dart` more resilient to failed gradle downloads? /cc @zanderso @xster @jonahwilliams

**Comment by jonahwilliams** [comment]
I believe we do retry on failed zip downloads from gradle, however it seems that if it fails once it will most likely fail again.

**Comment by Hixie** [comment]
Do we need more aggressive retry? e.g. just keep trying with truncated exponential backoff?

It's presumably some sort of connectivity issue either with the CI datacenter or with the gradle host?

**Comment by digiter** [comment]
In the failed build, as we are running multiple devicelab tasks, the cleanup step of one task caused a corrupted gradle, then a follow up task failed due to using the corrupted zip archive. To fix this, we could remove .gradle after each task run.

**Comment by digiter** [comment]
I guess the fix works, there's no new windows failure yet after https://github.com/flutter/flutter/pull/65434.

**Comment by blasten** [comment]
I just saw this issue. The issue appears to be that the test is calling the gradlew script directly.  The Flutter tool already has a mechanism for retrying these builds see: https://github.com/flutter/flutter/blob/1510865fb45513124601a587229543c488103b14/packages/flutter_tools/lib/src/android/gradle_errors.dart#L107

Most certainly, removing the gradle cache in every run will result in more latency and flakiness.
