### ISSUE TITLE
App crashes due to simple class extend mistake without any code error without stricter analyzer

### ISSUE THREAD

**Issue by luis901101** [flutter/flutter#65278]
## Steps to Reproduce

From a basic increment number flutter app run the code below.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends ContentTabsWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends ContentTabsState<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

abstract class IBase {}

abstract class ContentTabsWidget
    extends BaseStatefulWidget<ContentTabsState, dynamic> {
  ContentTabsWidget({Key key}) : super(key: key);
}

abstract class ContentTabsState<W extends ContentTabsWidget>
    extends BaseState<W, dynamic> {}

abstract class BaseStatefulWidget<ST extends SuperState, T>
    extends SuperStatefulWidget<ST, T, IBase> {
  BaseStatefulWidget({Key key}) : super(key: key);
}

abstract class BaseState<W extends StatefulWidget, T>
    extends SuperState<W, T, IBase> {}

abstract class SuperStatefulWidget<S extends SuperState, T, B>
    extends StatefulWidget {
  SuperStatefulWidget({Key key}) : super(key: key);
}

abstract class SuperState<W extends StatefulWidget, T, B> extends State<W>
    with WidgetsBindingObserver {}

```

**Expected results:** 

The app running normally

**Actual results:**

App crashes

In iOS this is the log output: 
`io.flutter.1.ui (9): EXC_BAD_ACCESS (code=1, address=0x0)`

In Android this is the log output:
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 14803 (1.ui), pid 14773`

### Fix:
Just replace the ContentTabsWidget definition with this:

```
abstract class ContentTabsWidget
    extends BaseStatefulWidget/*<ContentTabsState, dynamic>*/ {
  ContentTabsWidget({Key key}) : super(key: key);
}
```

This situation should never have happened, but the project in which I was working is big and several classes extending other were changed and there was the moment in which that `<ContentTabsState, dynamic>` took place… it took me several hours to find  the mistake… I was hoping that the dart-analyzer had warned me of such an error… or at least an error during building… 

## So my question

Why the dart analyzer allows that code and the build process completes successfully and then when the app starts a crash occurs?

<details>

```
```

[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.0-7.2.pre at /Users/user/Flutter/SDK
    • Framework revision a2bde82fbd (7 weeks ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/user/Android/SDK
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = /Users/user/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

```
```

</details>

**Comment by iapicca** [comment]
you can [customize](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks) your analyzer

**Comment by TahaTesser** [comment]
Hi @luis901101 
Please try @iapicca 's suggestion, it does show errors when using the code sample, you just need to analyze more strict here

[analysis_options.yaml.zip](https://github.com/flutter/flutter/files/5182038/analysis_options.yaml.zip)


```

  error • Missing type arguments for generic type 'SuperState<StatefulWidget, dynamic, dynamic>' • lib/main.dart:77:46 •
         implicit_dynamic_type
  error • Missing type arguments for generic type 'SuperState<StatefulWidget, dynamic, dynamic>' • lib/main.dart:85:46 •
         implicit_dynamic_type

2 issues found. (ran in 2.4s)
```

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 81a45ec2e5 (10 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 73130414-6DF8-4E37-B9AF-F81FA0F9068B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.83

• No issues found!

```

</details>

**Comment by luis901101** [comment]
Thank you both for your answers.
Yes with a customized analysis_options as you propose there are messages indicating the error... but the code loses a bit of flexibility.

I just think that the app crash is a result too excesive for the source of the error. I mean Ok, I did a mistake with the type management but that should be notified in some way… maybe at runtime in a red screen or something… but an app crash at start is somthing that makes me think of a native code error or something else… but not a type management error…

**Comment by luis901101** [comment]
For instance if I update the _incrmenetCounter function with the following:

```
void _incrementCounter() {

    dynamic number = 1.5;
    String myNumber = number;

    setState(() {
      _counter++;
    });
  }
```


that will generate an error of type management when user press the increment button.

```
════════ (2) Exception caught by gesture ═══════════════════════════════════════════════════════════
type 'double' is not a subtype of type 'String'

```

Something similar is what I would expect to happen for the error that I mention at the beginning of the post

**Comment by TahaTesser** [comment]
I agree, it would be too much hassle to go and find what went wrong

**Comment by jason-simmons** [comment]
This is reproducible on the current engine master.  The crash happens during `Dart_FinalizeLoading`

Stack trace:
```
#0  0x00000000 in ?? ()
#1  0x90343e04 in dart::ClassFinalizer::CheckRecursiveType (cls=..., type=..., 
    pending_types=0x8d26b2d0)
    at ../../third_party/dart/runtime/vm/class_finalizer.cc:341
#2  0x90344dc4 in dart::ClassFinalizer::FinalizeTypeArguments (cls=..., 
    arguments=..., num_uninitialized_arguments=<optimized out>, 
    pending_types=<optimized out>, trail=<optimized out>)
    at ../../third_party/dart/runtime/vm/class_finalizer.cc:637
#3  0x90344e2e in dart::ClassFinalizer::FinalizeTypeArguments (cls=..., 
    arguments=..., num_uninitialized_arguments=<optimized out>, 
    pending_types=<optimized out>, trail=<optimized out>)
    at ../../third_party/dart/runtime/vm/class_finalizer.cc:650
#4  0x9034437c in dart::ClassFinalizer::ExpandAndFinalizeTypeArguments (
    cls=..., type=..., pending_types=<optimized out>)
    at ../../third_party/dart/runtime/vm/class_finalizer.cc:501
#5  0x903445fa in dart::ClassFinalizer::FinalizeType (cls=..., type=..., 
    finalization=<optimized out>, pending_types=0x8d26b2d0)
    at ../../third_party/dart/runtime/vm/class_finalizer.cc:750
#6  0x90344284 in dart::ClassFinalizer::ExpandAndFinalizeTypeArguments (
    cls=..., type=..., pending_types=<optimized out>)
    at ../../third_party/dart/runtime/vm/class_finalizer.cc:481
#7  0x903445fa in dart::ClassFinalizer::FinalizeType (cls=..., type=..., 
    finalization=<optimized out>, pending_types=0x8d26b2d0)
    at ../../third_party/dart/runtime/vm/class_finalizer.cc:750
#8  0x90344284 in dart::ClassFinalizer::ExpandAndFinalizeTypeArguments (cls=..., type=..., pending_types=<optimized out>) at ../../third_party/dart/runtime/vm/class_finalizer.cc:481
#9  0x903445fa in dart::ClassFinalizer::FinalizeType (cls=..., type=..., finalization=<optimized out>, pending_types=0x8d26b2d0) at ../../third_party/dart/runtime/vm/class_finalizer.cc:750
#10 0x90343a00 in dart::ClassFinalizer::FinalizeTypesInClass (cls=...) at ../../third_party/dart/runtime/vm/class_finalizer.cc:1040
#11 0x903439be in dart::ClassFinalizer::FinalizeTypesInClass (cls=...) at ../../third_party/dart/runtime/vm/class_finalizer.cc:1030
#12 0x90343838 in dart::ClassFinalizer::ProcessPendingClasses () at ../../third_party/dart/runtime/vm/class_finalizer.cc:212
#13 0x9063ac32 in dart::Api::CheckAndFinalizePendingClasses (thread=0x8d2f7400) at ../../third_party/dart/runtime/vm/dart_api_impl.cc:411
#14 0x9065b0a2 in Dart_FinalizeLoading (complete_futures=<optimized out>) at ../../third_party/dart/runtime/vm/dart_api_impl.cc:5976
#15 0x8f99e476 in flutter::DartIsolate::LoadKernel (this=0xa8bb99c0, mapping=..., last_piece=true) at ../../flutter/runtime/dart_isolate.cc:344
#16 0x8f99e550 in flutter::DartIsolate::PrepareForRunningFromKernel (this=0xa8bb99c0, mapping=..., last_piece=true) at ../../flutter/runtime/dart_isolate.cc:371
#17 0x8f9b576c in flutter::KernelIsolateConfiguration::DoPrepareIsolate (this=0xa077ce98, isolate=...) at ../../flutter/shell/common/isolate_configuration.cc:50
#18 0x8f9b41fc in flutter::IsolateConfiguration::PrepareIsolate (this=0xa077ce98, isolate=...) at ../../flutter/shell/common/isolate_configuration.cc:24
```

**Comment by crelier** [comment]
Thanks for the report.
I am able to reproduce this crash outside of the flutter framework with this standalone dart snippet:
```
void main() {
  ContentTabsWidget();
}

class StatefulWidget {}
class State<T> {}
class WidgetsBindingObserver {}
class IBase {}

class ContentTabsWidget
    extends BaseStatefulWidget<ContentTabsState, dynamic> {}

class ContentTabsState<W extends ContentTabsWidget>
    extends BaseState<W, dynamic> {}

class BaseStatefulWidget<ST extends SuperState, T>
    extends SuperStatefulWidget<ST, T, IBase> {}

class BaseState<W extends StatefulWidget, T>
    extends SuperState<W, T, IBase> {}

class SuperStatefulWidget<S extends SuperState, T, B>
    extends StatefulWidget {}

class SuperState<W extends StatefulWidget, T, B> extends State<W>
    with WidgetsBindingObserver {}
```
However, the stack trace of the crash is slightly different (I suspect finalization reaches the problematic recursive type graph at a different point):

```
../../runtime/vm/class_finalizer.cc: 629: error: expected: super_type_arg.IsTypeRef()
version=2.10.0-edge.4e9a98bb4502bb561ee4a1c7d7a32cbeb0e9acfb (be) (Thu Sep 10 22:32:11 2020 +0000) on "linux_x64"
pid=2197832, thread=2197832, isolate_group=main(0x55ef5ec96580), isolate=main(0x55ef5eca2900)
isolate_instructions=55ef5d4745c0, vm_instructions=55ef5d4745c0
  pc 0x000055ef5d8d9be6 fp 0x00007ffe20396620 dart::Profiler::DumpStackTrace(bool)+0x26
  pc 0x000055ef5d8d9b24 fp 0x00007ffe20396760 dart::Profiler::DumpStackTrace(void*)+0x24
  pc 0x000055ef5df06f45 fp 0x00007ffe20396780 Dart_DumpNativeStackTrace+0x15
  pc 0x000055ef5d474877 fp 0x00007ffe20396940 dart::Assert::Fail(char const*, ...)+0x187
  pc 0x000055ef5d66a46b fp 0x00007ffe20396b60 dart::ClassFinalizer::FinalizeTypeArguments(dart::Class const&, dart::TypeArguments const&, long, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x72b
  pc 0x000055ef5d66a625 fp 0x00007ffe20396d80 dart::ClassFinalizer::FinalizeTypeArguments(dart::Class const&, dart::TypeArguments const&, long, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x8e5
  pc 0x000055ef5d66a707 fp 0x00007ffe20396fa0 dart::ClassFinalizer::FinalizeTypeArguments(dart::Class const&, dart::TypeArguments const&, long, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x9c7
  pc 0x000055ef5d668f22 fp 0x00007ffe20397140 dart::ClassFinalizer::ExpandAndFinalizeTypeArguments(dart::Class const&, dart::AbstractType const&, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x5d2
  pc 0x000055ef5d6696b0 fp 0x00007ffe203973f0 dart::ClassFinalizer::FinalizeType(dart::Class const&, dart::AbstractType const&, dart::ClassFinalizer::FinalizationKind, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x5c0
  pc 0x000055ef5d668cfa fp 0x00007ffe20397590 dart::ClassFinalizer::ExpandAndFinalizeTypeArguments(dart::Class const&, dart::AbstractType const&, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x3aa
  pc 0x000055ef5d6696b0 fp 0x00007ffe20397840 dart::ClassFinalizer::FinalizeType(dart::Class const&, dart::AbstractType const&, dart::ClassFinalizer::FinalizationKind, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x5c0
  pc 0x000055ef5d668cfa fp 0x00007ffe203979e0 dart::ClassFinalizer::ExpandAndFinalizeTypeArguments(dart::Class const&, dart::AbstractType const&, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x3aa
  pc 0x000055ef5d6696b0 fp 0x00007ffe20397c90 dart::ClassFinalizer::FinalizeType(dart::Class const&, dart::AbstractType const&, dart::ClassFinalizer::FinalizationKind, dart::ZoneGrowableHandlePtrArray<dart::AbstractType const>*)+0x5c0
  pc 0x000055ef5d666624 fp 0x00007ffe20397e50 dart::ClassFinalizer::FinalizeTypesInClass(dart::Class const&)+0x1a4
  pc 0x000055ef5d6662fe fp 0x00007ffe203980a0 dart::ClassFinalizer::ProcessPendingClasses()+0x3ce
  pc 0x000055ef5d7bf506 fp 0x00007ffe203982a0 dart::kernel::KernelLoader::LoadProgram(bool)+0x1a6
  pc 0x000055ef5d7beb49 fp 0x00007ffe20398d00 dart::kernel::KernelLoader::LoadEntireProgram(dart::kernel::Program*, bool)+0x89
  pc 0x000055ef5deff3d0 fp 0x00007ffe20398ed0 Dart_LoadScriptFromKernel+0x350
  pc 0x000055ef5d44ed0e fp 0x00007ffe20399000 out/DebugX64/dart+0x1bb4d0e
  pc 0x000055ef5d44ccfa fp 0x00007ffe203991b0 out/DebugX64/dart+0x1bb2cfa
  pc 0x000055ef5d44bf30 fp 0x00007ffe20399350 dart::bin::RunMainIsolate(char const*, dart::bin::CommandLineOptions*)+0x70
  pc 0x000055ef5d44d87b fp 0x00007ffe20399500 dart::bin::main(int, char**)+0x6bb
  pc 0x000055ef5d44e3e2 fp 0x00007ffe20399530 main+0x22
-- End of DumpStackTrace
```

I'll dig deeper to try to understand what is going on and whether the type graph should actually be rejected.

**Comment by crelier** [comment]
A fix is under review: https://dart-review.googlesource.com/c/sdk/+/162583
I was able to verify it under flutter and the x86 emulator.
