### ISSUE TITLE
"Invalid argument(s)" error on Android when building the app

### ISSUE THREAD

**Issue by OmarYehiaDev** [flutter/flutter#65294]
## Steps to Reproduce

I was working on my project normally yesterday but today when I tried to build it it throws me the error in the logs. So I ran `flutter create` and it didn't help me and this is my Question on StackOverflow [link](https://stackoverflow.com/questions/63759770/another-exception-was-thrown-invalid-arguments-error-when-building-app)

**Expected results:** 

I expect to see my app working normally!

**Actual results:** 

I saw a big red screen with error `Invalid argument(s)`

<details>
  <summary>Logs</summary>

My app logs :-

```
Launching lib\main.dart on M2003J15SC in debug mode...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
I/ActivityThread(22567): Removing dead content provider:android.content.ContentProviderProxy@f3a84ba
I/ActivityThread(22567): Removing dead content provider:android.content.ContentProviderProxy@2375f6b
I/ActivityThread(22567): com.facebook.katana.provider.AttributionIdProvider acquiringCount 2
I/System.out(22567): [okhttp]:check permission begin!
W/System  (22567): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(22567): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(22567): [OkHttp] sendRequest<<
W/om.extreme.hel(22567): Long monitor contention with owner AsyncTask #2 (22654) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(BinderProxy.java:-2) waiters=0 in android.content.IContentProvider android.app.ActivityThread.acquireProvider(android.content.Context, java.lang.String, int, boolean) for 572ms
Connecting to VM Service at ws://127.0.0.1:57229/zt3wuNqkdzc=/ws
I/om.extreme.hel(22567): ProcessProfilingInfo new_methods=3495 is saved saved_to_disk=1 resolve_classes_delay=8000
D/Surface (22567): Surface::disconnect(this=0x7db102c000,api=1)
D/Surface (22567): Surface::connect(this=0x7db102c000,api=1)
D/mali_winsys(22567): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (22567): Surface::setBufferCount(this=0x7db102c000,bufferCount=3)
I/GED     (22567): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 31, oppidx_max 31, oppidx_min 0
D/Surface (22567): Surface::disconnect(this=0x7db102e000,api=1)
D/Surface (22567): Surface::connect(this=0x7db102e000,api=1)
D/mali_winsys(22567): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following ArgumentError was thrown building MediaQuery(MediaQueryData(size: Size(392.7, 834.9), devicePixelRatio: 2.8, textScaleFactor: 1.0, platformBrightness: Brightness.dark, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional)):[39;49m
Invalid argument(s)

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mSafeArea[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      _StringBase.+  (dart:core-patch/string_patch.dart:267:57)[39;49m
[38;5;248m#1      new ApiService[39;49m
[38;5;248m#2      new _SplashScreenPageState[39;49m
[38;5;248m#3      SplashScreenPage.createState[39;49m
[38;5;244m#4      new StatefulElement[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ArgumentError was thrown building MediaQuery(MediaQueryData(size: Size(392.7, 834.9),
devicePixelRatio: 2.8, textScaleFactor: 1.0, platformBrightness: Brightness.dark, padding:
EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat:
false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors:
false, boldText: false, navigationMode: traditional)):
Invalid argument(s)
The relevant error-causing widget was:
  [38;5;248mSafeArea[39;49m
When the exception was thrown, this was the stack:
[38;5;244m#0      _StringBase.+  (dart:core-patch/string_patch.dart:267:57)[39;49m
[38;5;248m#1      new ApiService[39;49m
[38;5;248m#2      new _SplashScreenPageState[39;49m
[38;5;248m#3      SplashScreenPage.createState[39;49m
[38;5;244m#4      new StatefulElement[39;49m
[38;5;244m#5      StatefulWidget.createElement[39;49m
...     Normal element mounting (147 frames)
[38;5;244m#152    Element.inflateWidget[39;49m
[38;5;244m#153    MultiChildRenderObjectElement.mount[39;49m
...     Normal element mounting (273 frames)
[38;5;244m#426    Element.inflateWidget[39;49m
[38;5;244m#427    Element.updateChild[39;49m
[38;5;244m#428    RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244m#429    RenderObjectToWidgetElement.mount[39;49m
[38;5;244m#430    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244m#431    BuildOwner.buildScope[39;49m
[38;5;244m#432    RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244m#433    WidgetsBinding.attachRootWidget[39;49m
[38;5;244m#434    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Invalid argument(s)

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
Invalid argument(s)
[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mSafeArea[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

```

My project analysis :-

```
Analyzing findhelpapp...

   info - The value of the field '_googleSignIn' isn't used - lib\pages\loginScreen.dart:84:22 - unused_field
   info - The declaration '_loginWithFB' isn't referenced - lib\pages\loginScreen.dart:93:3 - unused_element
   info - The declaration '_logout' isn't referenced - lib\pages\loginScreen.dart:128:3 - unused_element
   info - The value of the field '_password' isn't used - lib\pages\loginScreen.dart:173:10 - unused_field
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\pages\tabs\requestsPage.dart:49:12 - missing_return      
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\pages\tabs\requestsPage.dart:171:12 - missing_return     

6 issues found. (ran in 31.4s)
```

My `flutter doctor` logs :-

```
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18362.1016], locale en-US)
    • Flutter version 1.20.3 at C:\Native\flutter
    • Framework revision 216dee60c0 (4 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Omar\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\Omar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[√] Connected device (1 available)
    • M2003J15SC (mobile) • 192.168.1.7:5555 • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

**Comment by iapicca** [comment]
@OmarYehiaDev the error likely depends from your app implementation rather than flutter
can you provide a minimal reproducible code sample

**Comment by MkamaAFM** [comment]
I see you have some functions that should return widgets, but they don't return anything.

**Comment by OmarYehiaDev** [comment]
> @OmarYehiaDev the error likely depends from your app implementation rather than flutter
> can you provide a minimal reproducible code sample

Sure, This is the ApiService class 
```
import 'dart:async';
import 'dart:convert';
import 'package:findhelpapp/models/service_model.dart';
import 'package:findhelpapp/utils/constants.dart';
import 'package:flutter/cupertino.dart';
import 'package:http/http.dart' as http;

class ApiService {
  String basicAuth = "Basic" + kUserToken;
  Future<Map<String, dynamic>> getAppConfigData() async {
    final response = await http.get(
      kBaseURL + kBaseConfig,
      headers: {
        "app_id": kAppID,
        "app_secret": kAppSecret,
      },
    );
    final Map<String, dynamic> jsonData = json.decode(response.body);
    return jsonData;
  }

  Future<Map<String, dynamic>> getUpdatesData() async {
    final response = await http.get(
      kBaseURL + kUpdatesData,
      headers: {
        "app_id": kAppID,
        "app_secret": kAppSecret,
        'authorization': basicAuth,
      },
    );
    final Map<String, dynamic> jsonData = json.decode(response.body);
    return jsonData;
  }

  Future<Map<String, dynamic>> getProfileData() async {
    final response = await http.get(
      kBaseURL + kUserProfile,
      headers: {
        "app_id": kAppID,
        "app_secret": kAppSecret,
        'authorization': basicAuth,
      },
    );
    final Map<String, dynamic> jsonData = json.decode(response.body);
    return jsonData;
  }

  Future<Map<String, dynamic>> getSavedData() async {
    final response = await http.get(
      kBaseURL + kUserBookmarks,
      headers: {
        "app_id": kAppID,
        "app_secret": kAppSecret,
        'authorization': basicAuth,
      },
    );
    final Map<String, dynamic> jsonData = json.decode(response.body);
    return jsonData;
  }

  Future<Map<String, dynamic>> getRequestsData() async {
    final response = await http.get(
      kBaseURL + kUserRequests,
      headers: {
        "app_id": kAppID,
        "app_secret": kAppSecret,
        'authorization': basicAuth,
      },
    );
    final Map<String, dynamic> jsonData = json.decode(response.body);
    return jsonData;
  }

  Future<List<Service>> getServicesData() async {
    final response = await http.get(
      kBaseURL + kAppServices,
      headers: {
        "app_id": kAppID,
        "app_secret": kAppSecret,
        'authorization': basicAuth,
      },
    );
    final jsonData = json.decode(response.body);
    print(basicAuth);

    final List<Service> data = jsonData
        .map(
          (e) => Service.fromJson(e),
        )
        .toList();
    return data;
  }

  Future<List<Map<String, dynamic>>> getServicesProviders({
    @required double lat,
    @required double lng,
    @required double distance,
    String query,
    String sid,
  }) async {
    var queryParams = {
      "sid": sid,
      "query": query,
      "lat": lat,
      "lng": lng,
      "distance": distance,
    };
    var uri = Uri.https(kBaseURL, kServiceProvidersSearch, queryParams);
    final response = await http.get(
      uri,
      headers: {
        "app_id": kAppID,
        "app_secret": kAppSecret,
        'authorization': basicAuth,
      },
    );
    final List<Map<String, dynamic>> jsonData = json.decode(response.body);
    return jsonData;
  }

  Future callProvider(pId, type) async {
    var queryParams = {
      "pid": pId,
      "type": type,
    };
    var uri = Uri.https(kBaseURL, kProviderCall, queryParams);
    final response = await http.get(
      uri,
      headers: {
        "app_id": kAppID,
        "app_secret": kAppSecret,
        'authorization': basicAuth,
      },
    );
    final jsonData = json.decode(response.body);
    return jsonData;
  }
}

```

**Comment by OmarYehiaDev** [comment]
> I see you have some functions that should return widgets, but they don't return anything.

the app was working normally with this info existing so it's not from them

**Comment by myunghun0423** [comment]
Can I get OWA OWA
