### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by AbdulmalekAlshugaa** [flutter/flutter#65292]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:95:62)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:95:62)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:333:59)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:651:16)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:670:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:636:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:657:12)
#10     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:795:13)
<asynchronous suspension>
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:592:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:458:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:831:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _runZoned (dart:async/zone.dart:1630:10)
#20     runZoned (dart:async/zone.dart:1550:10)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
```
```
[✓] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.3 at C:\Program Files\flutter_windows_1.17.5-stable\flutter
    • Framework revision 216dee60c0 (4 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Eng_A\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.1
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Eng_A\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6

**Comment by iapicca** [comment]
duplicate https://github.com/flutter/flutter/issues/60272

**Comment by darshankawar** [comment]
Hi @AbdulmalekAlshugaa,
Please follow-up in [60272](https://github.com/flutter/flutter/issues/60272) for updates and any questions.
Closing this as duplicate.
