### ISSUE TITLE
[tool_crash] IndexError: RangeError (index): Index out of range: index should be less than 48990797: 3220127023

### ISSUE THREAD

**Issue by karshan96** [flutter/flutter#65325]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
IndexError: RangeError (index): Index out of range: index should be less than 48990797: 3220127023
```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:3946:7)
#1      InputStream.readUint32 (package:archive/src/util/input_stream.dart:229:22)
#2      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:49:34)
#3      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:20:30)
#4      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
#5      _WindowsUtils.verifyZip (package:flutter_tools/src/base/os.dart:341:20)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:634:20)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:667:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:633:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:654:12)
#10     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:792:13)
<asynchronous suspension>
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:589:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:455:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:877:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:787:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _runZoned (dart:async/zone.dart:1630:10)
#20     runZoned (dart:async/zone.dart:1550:10)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:776:20)
```
```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-9.2.pre at C:\flutter
    • Framework revision 81a45ec2e5 (10 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_SDK_ROOT = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\Rasa Karshanguna\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
Hi @karshan96,
Is this on web ? Please provide a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
