### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by coduy96** [flutter/flutter#65326]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      _updateGeneratedXcodePropertiesFile (package:flutter_tools/src/ios/xcodeproj.dart:95:32)
#6      updateGeneratedXcodeProperties (package:flutter_tools/src/ios/xcodeproj.dart:65:3)
#7      IosProject._updateGeneratedXcodeConfigIfNeeded (package:flutter_tools/src/project.dart:594:13)
#8      IosProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:570:11)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:246:17)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:843:21)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZoned (dart:async/zone.dart:1550:10)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.20.2 at /Users/dver/flutter
    • Framework revision bbfbf1770c (4 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/dver/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Mi Note 10 Lite (mobile) • a3e46c14 • android-arm64 • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b041144f833e05cf463b8887fa12efdec9493488
### Plugins
flutter_plugin_android_lifecycle-1.0.8
image_picker-0.6.7+2
keyboard_visibility-0.5.6

**Comment by darshankawar** [comment]
Hi @coduy96,
There was a [fix](https://github.com/flutter/flutter/pull/63540) made recently and merged in Master. Please switch to latest master and try again to see if it works for you.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
