### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument (URI scheme not allowed): "file:///C:/...cranesScreenWeb.dart"

### ISSUE THREAD

**Issue by xOldeVx** [flutter/flutter#65376]
My application can't to run on Web anymore for some reason

## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument (URI scheme not allowed): "file:///C:/...cranesScreenWeb.dart"
```
#0      DartUri._recordAbsoluteUri (package:dwds/src/utilities/dart_uri.dart:86:7)
#1      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:60:9)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:88:19)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:184:37)
<asynchronous suspension>
#5      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:151:23)
#6      DebugService.start (package:dwds/src/services/debug_service.dart:143:55)
#7      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:190:25)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.18362.1016], locale he-IL)
    • Flutter version 1.21.0-9.2.pre at C:\src\flutter
    • Framework revision 81a45ec2e5 (12 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\...sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\...Microsoft VS Code
    • Flutter extension version 3.14.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.83
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.1+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-0.12.11
firebase_analytics-5.0.16
firebase_analytics_web-0.1.1
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-5.1.8
flutter_inappwebview-4.0.0+4
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
uni_links-0.2.0

**Comment by berrylawchingman** [comment]
「xOldeVx <notifications@github.com>」在 2020年9月8日 週二，下午5:13 寫道：

**Comment by pedromassangocode** [comment]
Hi @xOldeVx 
Can you please try [this solution](https://github.com/flutter/flutter/issues/59924#issuecomment-678287123) and see if it works for you?

**Comment by berrylawchingman** [comment]
👉🏻

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
