### ISSUE TITLE
`flutter config` can be flaky in the devicelab

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#65413]
Here's the error info in a [flaky test log][1]
```
Task failed with the following reason:
ERROR: Command "/Users/flutter/.cocoon/flutter/bin/flutter config --no-analytics" failed with exit code 1.
#0      fail (package:cocoon_agent/src/utils.dart:139:3)
#1      exec (package:cocoon_agent/src/utils.dart:321:5)
<asynchronous suspension>
#2      flutter (package:cocoon_agent/src/utils.dart:346:10)
#3      getFlutter (package:cocoon_agent/src/utils.dart:513:9)
<asynchronous suspension>
#4      getFlutterAt (package:cocoon_agent/src/utils.dart:255:9)
<asynchronous suspension>
#5      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:21)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1500:12)
#10     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#11     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

[1]: https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJfCxIJQ2hlY2tsaXN0Ij9mbHV0dGVyL2ZsdXR0ZXIvbWFzdGVyLzE0YWY1YmJlMWU4NjAxNjJmYjk2NDE3YmUxNzdjMzdmY2NiOTU3ZmEMCxIEVGFzaxiAgOiqpOmPCAw

**Comment by liyuqian** [comment]
CC @godofredoc @tvolkert @zanderso @jonahwilliams as I found this while investigating https://github.com/flutter/flutter/issues/60559

**Comment by zanderso** [comment]
The link to the logs isn't working for me. Could you fix that, or just paste more of them here? I'd have expected there to be more log output from `flutter config`.

**Comment by liyuqian** [comment]
Here's the full log (the 1st half is a failure and the 2nd half is a successful rerun).
<details>

```
------------ TASK ------------
Task(id: 4573187851026432, parentKey: flutter/flutter/master/14af5bbe1e860162fb96417be177c37fccb957fa, key: 4573187851026432, commitKey: flutter/flutter/master/14af5bbe1e860162fb96417be177c37fccb957fa, createTimestamp: 1599264121687, startTimestamp: 1599265785814, endTimestamp: 1599266062904, name: flutter_gallery__transition_perf_e2e_ios32, attempts: 2, isFlaky: false, timeoutInMinutes: 0, reason: , requiredCapabilities: [mac/ios32], reservedForAgentId: flutter-devicelab-mac-11, stageName: devicelab_ios, status: Succeeded, buildNumber: null, buildNumberList: null, builderName: null, luciBucket: null)

------------ LOG ------------


Task failed with the following reason:
ERROR: Command "/Users/flutter/.cocoon/flutter/bin/flutter config --no-analytics" failed with exit code 1.
#0      fail (package:cocoon_agent/src/utils.dart:139:3)
#1      exec (package:cocoon_agent/src/utils.dart:321:5)
<asynchronous suspension>
#2      flutter (package:cocoon_agent/src/utils.dart:346:10)
#3      getFlutter (package:cocoon_agent/src/utils.dart:513:9)
<asynchronous suspension>
#4      getFlutterAt (package:cocoon_agent/src/utils.dart:255:9)
<asynchronous suspension>
#5      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:21)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1500:12)
#10     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#11     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Deleting build/ directories, if any.
Deleting /Users/flutter/.cocoon/flutter/dev/integration_tests/flutter_gallery/build
2020-09-04T17:29:57.536436: Agent ID: flutter-devicelab-mac-112020-09-04T17:29:57.986224: Observatory listening on http://127.0.0.1:20000/
2020-09-04T17:29:58.202186: Running task with a timeout of null.
2020-09-04T17:29:58.202939: 

══════════════════╡ ••• Checking running Dart processes ••• ╞═══════════════════

2020-09-04T17:29:58.296228: RunningProcesses{pid: 57946, commandLine: /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --enable-vm-service=20000 --no-pause-isolates-on-exit --disable-service-auth-codes bin/tasks/flutter_gallery__transition_perf_e2e_ios32.dart --cloud-auth-token=ya29.c.Ko8B2wee39PfhqU_lEA9wdI1R-qrcbaQPBDFfZwHHxCiMHSaJ71v8lMWEl1HnADhrUypf40rgIoIv3ak3oEyjULOuEOApsH_GkrnJe_nuE23xJi1k6xEkigb-9T2IbO4o46Png4cNXlki2eshbjPOd-uy4tChMJmyhnr6WY2aG50LHHfBqVzCqF7HT7qqYm4z4k, creationDate: 2020-09-04 17:29:57.000}
RunningProcesses{pid: 59298, commandLine: dart bin/agent.dart ci -c config.yaml, creationDate: 2020-08-27 17:07:57.000}
enabling configs for macOS, Linux, Windows, and Web...
2020-09-04T17:29:58.299405: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter config --enable-macos-desktop --enable-windows-desktop --enable-linux-desktop --enable-web in /Users/flutter/.cocoon/flutter/dev/devicelab
2020-09-04T17:29:58.772070: stdout: Setting "enable-web" value to "true".
2020-09-04T17:29:58.772164: stdout: Setting "enable-linux-desktop" value to "true".
stdout: Setting "enable-macos-desktop" value to "true".
stdout: Setting "enable-windows-desktop" value to "true".
2020-09-04T17:29:58.772455: stdout: 
stdout: You may need to restart any open editors for them to read new settings.
2020-09-04T17:29:58.799030: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-09-04T17:29:58.815620: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter devices --machine --suppress-analytics in /Users/flutter/.cocoon/flutter/dev/devicelab
2020-09-04T17:30:02.078274: stdout: [
2020-09-04T17:30:02.078379: stdout:   {
stdout:     "name": "iPhone",
stdout:     "id": "822ef7958bba573829d85eef4df6cbdd86593730",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "ios",
stdout:     "emulator": false,
stdout:     "sdk": "iOS 9.3.6",
stdout:     "capabilities": {
2020-09-04T17:30:02.078430: stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": true,
stdout:       "fastStart": false,
stdout:       "flutterExit": true,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": false
stdout:     }
stdout:   },
stdout:   {
2020-09-04T17:30:02.078478: stdout:     "name": "macOS",
stdout:     "id": "macos",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "darwin-x64",
stdout:     "emulator": false,
stdout:     "sdk": "Mac OS X 10.14.6 18G6020",
stdout:     "capabilities": {
stdout:       "hotReload": true,
2020-09-04T17:30:02.078524: stdout:       "hotRestart": true,
stdout:       "screenshot": false,
stdout:       "fastStart": false,
stdout:       "flutterExit": true,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": true
stdout:     }
stdout:   },
2020-09-04T17:30:02.078578: stdout:   {
stdout:     "name": "Web Server",
stdout:     "id": "web-server",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "web-javascript",
stdout:     "emulator": false,
stdout:     "sdk": "Flutter Tools",
stdout:     "capabilities": {
2020-09-04T17:30:02.078625: stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": false,
stdout:       "fastStart": false,
stdout:       "flutterExit": false,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": true
stdout:     }
2020-09-04T17:30:02.078671: stdout:   },
stdout:   {
stdout:     "name": "Chrome",
stdout:     "id": "chrome",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "web-javascript",
stdout:     "emulator": false,
stdout:     "sdk": "Google Chrome 77.0.3865.90",
2020-09-04T17:30:02.078714: stdout:     "capabilities": {
stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": false,
stdout:       "fastStart": false,
2020-09-04T17:30:02.079014: stdout:       "flutterExit": false,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": true
stdout:     }
stdout:   }
stdout: ]
2020-09-04T17:30:02.101893: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-09-04T17:30:02.106838: Device chosen: device: 822ef7958bba573829d85eef4df6cbdd86593730
2020-09-04T17:30:02.109302: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter packages get in /Users/flutter/.cocoon/flutter/dev/integration_tests/flutter_gallery
2020-09-04T17:30:03.348076: stdout: Running "flutter pub get" in flutter_gallery...                     0.6s
2020-09-04T17:30:03.659481: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-09-04T17:30:03.659913: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter drive --profile -t test_driver/transitions_perf_e2e.dart --driver test_driver/transitions_perf_e2e_test.dart -d 822ef7958bba573829d85eef4df6cbdd86593730 in /Users/flutter/.cocoon/flutter/dev/integration_tests/flutter_gallery
2020-09-04T17:30:07.084265: stdout: Starting application: test_driver/transitions_perf_e2e.dart
2020-09-04T17:30:12.388911: stderr: Could not find application bundle at build/ios/iphoneos/Flutter Gallery.app; have you run "flutter build ios"?
2020-09-04T17:30:12.550061: stdout: Warning: Missing build name (CFBundleShortVersionString).
2020-09-04T17:30:12.550655: stdout: Warning: Missing build number (CFBundleVersion).
2020-09-04T17:30:12.550907: stderr: Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
2020-09-04T17:30:12.552916: stdout: Automatically signing iOS for device deployment using specified development team in Xcode project: S8QB4VV633
2020-09-04T17:30:14.175332: stdout: Running pod install...                                          
2020-09-04T17:30:14.175433: stdout: Received memory warning.
2020-09-04T17:30:14.289392: stdout: Running pod install...                                              1.1s
2020-09-04T17:30:15.525486: stdout: Running Xcode build...                                          
2020-09-04T17:30:15.525582: stdout: flutter: Observatory listening on http://127.0.0.1:63131/
2020-09-04T17:30:15.696391: stdout: 
stdout: [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
2020-09-04T17:30:15.743464: stdout: 
stdout: Received memory warning.
2020-09-04T17:30:15.792101: stdout: 
stdout: flutter: > VideoDemo initController "butterfly" 
2020-09-04T17:30:15.798345: stdout: 
stdout: flutter: > VideoDemo initController "bee" 
2020-09-04T17:30:15.804114: stdout: 
stdout: flutter: > VideoDemo dispose
2020-09-04T17:30:15.809914: stdout: 
stdout: flutter: < VideoDemo dispose
2020-09-04T17:30:15.818683: stdout: 
2020-09-04T17:30:15.818764: stdout: flutter: > VideoDemo initController "butterfly" 
2020-09-04T17:30:15.826625: stdout: 
stdout: flutter: > VideoDemo initController "bee" 
2020-09-04T17:30:15.835814: stdout: 
stdout: flutter: > VideoDemo dispose
2020-09-04T17:30:15.843651: stdout: 
stdout: flutter: < VideoDemo dispose
2020-09-04T17:30:15.850895: stdout: 
2020-09-04T17:30:15.851041: stdout: TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
2020-09-04T17:30:15.863375: stdout: 
stdout: TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
2020-09-04T17:30:15.963369: stdout: 
stdout: Received memory warning.
2020-09-04T17:31:25.916313: stdout: Xcode build done.                                           71.6s
2020-09-04T17:31:43.376174: stdout: Installing and launching...                                     
stdout: flutter: Observatory listening on http://127.0.0.1:63131/
2020-09-04T17:31:59.026943: stdout: Installing and launching...                                        31.6s
2020-09-04T17:32:00.540083: stderr: VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:62024/
2020-09-04T17:32:00.697632: stderr: VMServiceFlutterDriver: Isolate found with number: 4377815424660499
2020-09-04T17:32:00.742167: stderr: VMServiceFlutterDriver: Isolate is paused at start.
2020-09-04T17:32:00.742337: stderr: VMServiceFlutterDriver: Attempting to resume isolate
2020-09-04T17:32:01.532066: stdout: flutter: 00:00 +0: flutter gallery transitions on e2e find.bySemanticsLabel
2020-09-04T17:32:01.532409: stdout: flutter: 00:00 +0 ~1: flutter gallery transitions on e2e all demos
2020-09-04T17:32:01.599301: stderr: VMServiceFlutterDriver: Connected to Flutter application.
2020-09-04T17:32:04.625342: stdout: flutter: > Shrine@Studies
2020-09-04T17:32:07.325859: stdout: flutter: < Success
2020-09-04T17:32:07.326054: stdout: flutter: > Contact profile@Studies
2020-09-04T17:32:09.326332: stdout: flutter: < Success
2020-09-04T17:32:09.327217: stdout: flutter: > Animation@Studies
2020-09-04T17:32:11.294412: stdout: flutter: < Success
2020-09-04T17:32:11.294665: stdout: flutter: > Bottom navigation@Material
2020-09-04T17:32:15.226031: stdout: flutter: < Success
2020-09-04T17:32:15.227004: stdout: flutter: > Buttons@Material
2020-09-04T17:32:17.344370: stdout: flutter: < Success
2020-09-04T17:32:17.345421: stdout: flutter: > Cards@Material
2020-09-04T17:32:19.241850: stdout: flutter: < Success
2020-09-04T17:32:19.246808: stdout: flutter: > Chips@Material
2020-09-04T17:32:21.208874: stdout: flutter: < Success
2020-09-04T17:32:21.208967: stdout: flutter: > Dialogs@Material
2020-09-04T17:32:23.107325: stdout: flutter: < Success
2020-09-04T17:32:23.108169: stdout: flutter: > Pickers@Material
2020-09-04T17:32:26.176356: stdout: flutter: < Success
2020-09-04T17:32:28.595854: stdout: flutter: > Fortnightly@Studies
2020-09-04T17:32:31.059172: stdout: flutter: < Success
2020-09-04T17:32:31.059420: stdout: flutter: > 2D Transformations@Studies
2020-09-04T17:32:33.040715: stdout: flutter: < Success
2020-09-04T17:32:33.041489: stdout: flutter: > Pesto@Studies
2020-09-04T17:32:34.978552: stdout: flutter: < Success
2020-09-04T17:32:34.979046: stdout: flutter: > Colors@Style
2020-09-04T17:32:38.790393: stdout: flutter: < Success
2020-09-04T17:32:38.790666: stdout: flutter: > Typography@Style
2020-09-04T17:32:40.673570: stdout: flutter: < Success
2020-09-04T17:32:40.673667: stdout: flutter: > Backdrop@Material
2020-09-04T17:32:43.016811: stdout: [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
2020-09-04T17:32:44.689237: stdout: flutter: < Success
2020-09-04T17:32:44.689347: stdout: flutter: > Banner@Material
2020-09-04T17:32:46.590351: stdout: flutter: < Success
2020-09-04T17:32:46.590585: stdout: flutter: > Bottom app bar@Material
2020-09-04T17:32:49.911524: stdout: flutter: < Success
2020-09-04T17:32:49.911745: stdout: flutter: > Bottom sheet: Modal@Material
2020-09-04T17:32:51.821370: stdout: flutter: < Success
2020-09-04T17:32:51.821596: stdout: flutter: > Bottom sheet: Persistent@Material
2020-09-04T17:32:53.706916: stdout: flutter: < Success
2020-09-04T17:32:53.707150: stdout: flutter: > Buttons: Floating Action Button@Material
2020-09-04T17:32:55.657187: stdout: flutter: < Success
2020-09-04T17:32:55.657288: stdout: flutter: > Data tables@Material
2020-09-04T17:32:57.840388: stdout: flutter: < Success
2020-09-04T17:32:57.840629: stdout: flutter: > Elevations@Material
2020-09-04T17:32:59.757363: stdout: flutter: < Success
2020-09-04T17:32:59.758602: stdout: flutter: > Expand/collapse list control@Material
2020-09-04T17:33:01.656728: stdout: flutter: < Success
2020-09-04T17:33:01.656865: stdout: flutter: > Expansion panels@Material
2020-09-04T17:33:04.606357: stdout: flutter: < Success
2020-09-04T17:33:04.606533: stdout: flutter: > Grid@Material
2020-09-04T17:33:06.554895: stdout: flutter: < Success
2020-09-04T17:33:06.555798: stdout: flutter: > Icons@Material
2020-09-04T17:33:08.522681: stdout: flutter: < Success
2020-09-04T17:33:08.523491: stdout: flutter: > Lists@Material
2020-09-04T17:33:10.438888: stdout: flutter: < Success
2020-09-04T17:33:10.440475: stdout: flutter: > Lists: leave-behind list items@Material
2020-09-04T17:33:12.421906: stdout: flutter: < Success
2020-09-04T17:33:12.422869: stdout: flutter: > Lists: reorderable@Material
2020-09-04T17:33:14.388280: stdout: flutter: < Success
2020-09-04T17:33:14.388504: stdout: flutter: > Menus@Material
2020-09-04T17:33:16.356072: stdout: flutter: < Success
2020-09-04T17:33:16.356689: stdout: flutter: > Navigation drawer@Material
2020-09-04T17:33:18.304890: stdout: flutter: < Success
2020-09-04T17:33:18.306104: stdout: flutter: > Pagination@Material
2020-09-04T17:33:20.256692: stdout: flutter: < Success
2020-09-04T17:33:20.257434: stdout: flutter: > Progress indicators@Material
2020-09-04T17:33:22.355092: stdout: flutter: < Success
2020-09-04T17:33:22.355332: stdout: flutter: > Pull to refresh@Material
2020-09-04T17:33:24.338841: stdout: flutter: < Success
2020-09-04T17:33:24.339094: stdout: flutter: > Search@Material
2020-09-04T17:33:26.337722: stdout: flutter: < Success
2020-09-04T17:33:26.337949: stdout: flutter: > Selection controls@Material
2020-09-04T17:33:28.371613: stdout: flutter: < Success
2020-09-04T17:33:28.371833: stdout: flutter: > Sliders@Material
2020-09-04T17:33:30.420966: stdout: flutter: < Success
2020-09-04T17:33:30.421909: stdout: flutter: > Snackbar@Material
2020-09-04T17:33:32.453959: stdout: flutter: < Success
2020-09-04T17:33:32.455849: stdout: flutter: > Tabs@Material
2020-09-04T17:33:34.504900: stdout: flutter: < Success
2020-09-04T17:33:34.505058: stdout: flutter: > Tabs: Scrolling@Material
2020-09-04T17:33:36.533190: stdout: flutter: < Success
2020-09-04T17:33:36.539934: stdout: flutter: > Text fields@Material
2020-09-04T17:33:38.570623: stdout: flutter: < Success
2020-09-04T17:33:38.570849: stdout: flutter: > Tooltips@Material
2020-09-04T17:33:40.586953: stdout: flutter: < Success
2020-09-04T17:33:40.587251: stdout: flutter: > Activity Indicator@Cupertino
2020-09-04T17:33:47.353973: stdout: flutter: < Success
2020-09-04T17:33:47.354548: stdout: flutter: > Alerts@Cupertino
2020-09-04T17:33:49.394617: stdout: flutter: < Success
2020-09-04T17:33:49.396635: stdout: flutter: > Buttons@Cupertino
2020-09-04T17:33:51.419414: stdout: flutter: < Success
2020-09-04T17:33:51.419520: stdout: flutter: > Navigation@Cupertino
2020-09-04T17:33:53.551543: stdout: flutter: < Success
2020-09-04T17:33:53.552503: stdout: flutter: > Pickers@Cupertino
2020-09-04T17:33:55.587086: stdout: flutter: < Success
2020-09-04T17:33:55.591065: stdout: flutter: > Pull to refresh@Cupertino
2020-09-04T17:33:57.700137: stdout: flutter: < Success
2020-09-04T17:33:57.701265: stdout: flutter: > Segmented Control@Cupertino
2020-09-04T17:33:59.875304: stdout: flutter: < Success
2020-09-04T17:33:59.875570: stdout: flutter: > Sliders@Cupertino
2020-09-04T17:34:01.919250: stdout: flutter: < Success
2020-09-04T17:34:01.920410: stdout: flutter: > Switches@Cupertino
2020-09-04T17:34:04.002394: stdout: flutter: < Success
2020-09-04T17:34:04.006413: stdout: flutter: > Text Fields@Cupertino
2020-09-04T17:34:06.051955: stdout: flutter: < Success
2020-09-04T17:34:06.052171: stdout: flutter: > Animated images@Media
2020-09-04T17:34:10.004976: stdout: flutter: < Success
2020-09-04T17:34:10.009816: stdout: flutter: > Video@Media
2020-09-04T17:34:10.454609: stdout: flutter: > VideoDemo initController "butterfly" 
2020-09-04T17:34:10.469673: stdout: flutter: > VideoDemo initController "bee" 
2020-09-04T17:34:11.288953: stdout: flutter: > VideoDemo dispose
2020-09-04T17:34:11.293168: stdout: flutter: < VideoDemo dispose
2020-09-04T17:34:11.384063: stdout: flutter: > VideoDemo initController "butterfly" 
2020-09-04T17:34:11.414441: stdout: flutter: > VideoDemo initController "bee" 
2020-09-04T17:34:11.802375: stdout: TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
2020-09-04T17:34:11.876714: stdout: TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
2020-09-04T17:34:12.274024: stdout: flutter: < VideoDemo initController "butterfly" done 
2020-09-04T17:34:12.341178: stdout: flutter: > VideoDemo dispose
2020-09-04T17:34:12.342694: stdout: flutter: < VideoDemo dispose
2020-09-04T17:34:12.375426: stdout: flutter: < Success
2020-09-04T17:34:13.053788: stdout: flutter: 02:11 +1 ~1: (tearDownAll)
2020-09-04T17:34:13.625296: stdout: TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
stdout: TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
2020-09-04T17:34:13.625548: stdout: flutter: Warning: E2E test plugin was not detected.
stdout: flutter: 02:12 +2 ~1: All tests passed!
2020-09-04T17:34:13.628456: stdout: All tests passed.
2020-09-04T17:34:13.655702: stdout: Stopping application instance.
2020-09-04T17:34:13.672173: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-09-04T17:34:13.684091: 

═══════════╡ ••• Checking running Dart processes after task... ••• ╞════════════

2020-09-04T17:34:13.707676: Cleaning up after task...
2020-09-04T17:34:13.803814: Task execution finished
```

</details>

**Comment by jonahwilliams** [comment]
Perhaps we should be running that command with --verbose?

**Comment by jmagman** [comment]
Added the verbose flag in https://github.com/flutter/cocoon/pull/958. If it flakes again, we'll have more logging.

**Comment by jmagman** [comment]
https://github.com/flutter/cocoon/pull/958 didn't help, now it looks like:
```
Task failed with the following reason:
ERROR: Command "/Users/flutter/.cocoon/flutter/bin/flutter config --no-analytics --verbose" failed with exit code 1.
#0      fail (package:cocoon_agent/src/utils.dart:139:3)
#1      exec (package:cocoon_agent/src/utils.dart:327:5)
<asynchronous suspension>
#2      flutter (package:cocoon_agent/src/utils.dart:352:10)
#3      getFlutter (package:cocoon_agent/src/utils.dart:519:9)
<asynchronous suspension>
#4      getFlutterAt (package:cocoon_agent/src/utils.dart:255:9)
<asynchronous suspension>
#5      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:21)
<asynchronous suspension>
#6      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart)
#7      _rootRun (dart:async/zone.dart:1190:13)
#8      _CustomZone.run (dart:async/zone.dart:1093:19)
#9      _runZoned (dart:async/zone.dart:1630:10)
#10     runZonedGuarded (dart:async/zone.dart:1618:12)
#11     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#12     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
so I guess stdout isn't being output there.

**Comment by jmagman** [comment]
> [flutter/cocoon#958](https://github.com/flutter/cocoon/pull/958) didn't help, now it looks like:
> 
> ```
> Task failed with the following reason:
> ERROR: Command "/Users/flutter/.cocoon/flutter/bin/flutter config --no-analytics --verbose" failed with exit code 1.
> #0      fail (package:cocoon_agent/src/utils.dart:139:3)
> #1      exec (package:cocoon_agent/src/utils.dart:327:5)
> <asynchronous suspension>
> #2      flutter (package:cocoon_agent/src/utils.dart:352:10)
> #3      getFlutter (package:cocoon_agent/src/utils.dart:519:9)
> <asynchronous suspension>
> #4      getFlutterAt (package:cocoon_agent/src/utils.dart:255:9)
> <asynchronous suspension>
> #5      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:21)
> <asynchronous suspension>
> #6      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart)
> #7      _rootRun (dart:async/zone.dart:1190:13)
> #8      _CustomZone.run (dart:async/zone.dart:1093:19)
> #9      _runZoned (dart:async/zone.dart:1630:10)
> #10     runZonedGuarded (dart:async/zone.dart:1618:12)
> #11     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
> <asynchronous suspension>
> #12     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
> #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> ```
> 
> so I guess stdout isn't being output there.

Although it should be https://github.com/flutter/cocoon/pull/659

**Comment by jmagman** [comment]
Somehow after https://github.com/flutter/cocoon/pull/1059 tasks are still failing on `config`.
[platform_channel_sample_test_ios_5642bed_2.log](https://github.com/flutter/flutter/files/6024558/platform_channel_sample_test_ios_5642bed_2.log)

https://github.com/flutter/cocoon/blob/f19791ecfa6bd449c608f04cf5642a7c96a9a5b7/agent/lib/src/utils.dart#L519
```dart
await flutter('config', options: ['--no-analytics', '--verbose'], canFail: true);
```
https://github.com/flutter/cocoon/blob/f19791ecfa6bd449c608f04cf5642a7c96a9a5b7/agent/lib/src/utils.dart#L325-L328
```dart
  if (exitCode != 0 && !canFail) {
    final List<String> command = [executable]..addAll(arguments);
    fail('Command "${command.join(' ')}" failed with exit code $exitCode.');
  }
```
```
ERROR: Command "/Users/flutter/.cocoon/flutter/bin/flutter config --no-analytics --verbose" failed with exit code 1.
#0      fail (package:cocoon_agent/src/utils.dart:139:3)
#1      exec (package:cocoon_agent/src/utils.dart:327:5)
```
@CaseyHillers do you know why setting `canFail=true` wasn't sufficient?  Is https://github.com/flutter/cocoon/pull/1059 not deployed?

**Comment by CaseyHillers** [comment]
That sounds right to me. Whenever changing cocoon agent, we need to manually update the machines. Feel free to file an infra ticket to get the machines updated with the change.

With LUCI, the various dependencies like this are explicitly versioned in the builder.

**Comment by jmagman** [comment]
@CaseyHillers ah that makes sense.

>  Feel free to file an infra ticket to get the machines updated with the change.  With LUCI, the various dependencies like this are explicitly versioned in the builder.

The imminent devicelab switch over will make that unnecessary, right?

**Comment by CaseyHillers** [comment]
IIRC there's still some mac agents and windows agents not migrated. The ETA last week was another month for all Cocoon agents to be turned down. Is that soon enough, or should we patch the fleet?

**Comment by jmagman** [comment]
> IIRC there's still some mac agents and windows agents not migrated. The ETA last week was another month for all Cocoon agents to be turned down. Is that soon enough, or should we patch the fleet?

Filed https://github.com/flutter/flutter/issues/76557.  It's not really urgent, but if it's relatively easy to patch, that would be great!

**Comment by godofredoc** [comment]
obsolete.
