### ISSUE TITLE
flutter doctor Android SDK update advice should direct users to Android Studio, or fix sdkmanager advice

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#65414]
The sdkmanager can fail to run if JAVA_HOME is pointed outside the Android Studio bundled JDK. Either the suggestion should first point to Android Studio (which we recommend on flutter.dev docs anyway), or the command should be updated to include the correct overrides to grab the right Java.

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.89, on Mac OS X 10.15.6 19G73, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "<...>/Android/sdk/tools/bin/sdkmanager" "platforms;android-29" "build-tools;28.0.3"
      or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
```

But then running that command gives:

```
"<...>/Library/Android/sdk/tools/bin/sdkmanager" --list
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

Which I believe is due to it using a separate install of JDK 11

**Comment by dnfield** [comment]
For anyone who gets here via a Google search and is looking for the magic:

$JAVA_HOME _must_ be pointing to a JDK8 installation. 

On macOS, you can do this via something like `JAVA_HOME=$(/usr/libexec/java_home -v 1.8) && sdkmanager ...`.

But I agree we should just link to the official docs, since all of this is subject to bitrot and requires other fiddling on different platforms (and may not even work if your versionof macOS doesn't already have the JDK8 installed).
