### ISSUE TITLE
pushing or popping routes during build should assert

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6543]
indeed, during any part of a frame, probably.

probably also manipulating overlays during a frame should assert.

**Comment by zoechi** [comment]
This currently throws 
```
I/flutter (14163): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14163): The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#cc55f):
I/flutter (14163): setState() or markNeedsBuild() called during build.
I/flutter (14163): This Overlay widget cannot be marked as needing to build because the framework is already in the
I/flutter (14163): process of building widgets. A widget can be marked as needing to be built during the build phase
I/flutter (14163): only if one of its ancestors is currently building. This exception is allowed because the framework
I/flutter (14163): builds parent widgets before children, which means a dirty descendant will always be built.
I/flutter (14163): Otherwise, the framework might not visit this widget during this build phase.
I/flutter (14163): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (14163):   Overlay-[LabeledGlobalKey<OverlayState>#a0480](state: OverlayState#f0dc1(entries:
I/flutter (14163):   [OverlayEntry#1c886(opaque: false; maintainState: false), OverlayEntry#963e8(opaque: false;
I/flutter (14163):   maintainState: true), OverlayEntry#eae62(opaque: false; maintainState: false),
I/flutter (14163):   OverlayEntry#9f1ea(opaque: false; maintainState: true)]))
I/flutter (14163): The widget which was currently being built when the offending call was made was:
I/flutter (14163):   MyHomePage(dirty, state: _MyHomePageState#cc55f)
I/flutter (14163): 
I/flutter (14163): When the exception was thrown, this was the stack:
I/flutter (14163): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3485:11)
I/flutter (14163): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3511:6)
I/flutter (14163): #2      State.setState (package:flutter/src/widgets/framework.dart:1146:14)
I/flutter (14163): #3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:301:5)
I/flutter (14163): #4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
I/flutter (14163): #5      TransitionRoute.install (package:flutter/src/widgets/routes.dart:185:11)
I/flutter (14163): #6      ModalRoute.install (package:flutter/src/widgets/routes.dart:861:11)
I/flutter (14163): #7      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1560:11)
I/flutter (14163): #8      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:1473:12)
I/flutter (14163): #9      _MyHomePageState.build (package:flutter_0_generic/main.dart:33:27)
```

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      routes: {
        '/': (context) => MyHomePage(title: 'Home Page'),
        '/other': (context) => MyHomePage(title: 'Other Page'),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    Navigator.of(context).pushNamed('/other');
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'current page: ${widget.title}',
            ),
            FlatButton(
              child: Text('Go to Other Page'),
              onPressed: () => Navigator.of(context).pushNamed('/other'),
            ),
          ],
        ),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-AT)
```

**Comment by goderbauer** [comment]
Closing as per comment above.
