### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.Receiver: nullTried calling: cancel()

### ISSUE THREAD

**Issue by zibolwx** [flutter/flutter#65449]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:969:11)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:750:5)
#3      AnsiStatus.stop (package:flutter_tools/src/base/logger.dart:1051:11)
#4      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1506:16)
<asynchronous suspension>
#5      ArtifactUpdater.downloadZipArchive (package:flutter_tools/src/cache.dart:1442:12)
#6      MaterialFonts.updateInner (package:flutter_tools/src/cache.dart:607:28)
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:573:11)
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:923:27)
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:831:33)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.87, on Mac OS X 10.15.5 19F101,
    locale zh-Hans-CN)
    • Flutter version 1.22.0-10.0.pre.87 at /Users/apple/Library/flutter
    • Framework revision 4732a214a7 (4 days ago), 2020-09-04 21:05:02 -0400
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by softmarshmallow** [comment]
Please submit your dart code raising this error.

**Comment by darshankawar** [comment]
Hi @zibolwx,
Please provide a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by markusaksli-nc** [comment]
As mentioned this is just an issue with the tool since it occurs during

```
#4      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1473:16)
```

Can't reproduce this either but since there have already been 2 duplicates with the same stack I feel safe labeling this issue for now.
