### ISSUE TITLE
TextField in PageView causes UnsupportedError Exception

### ISSUE THREAD

**Issue by ndhbr** [flutter/flutter#65459]
## Steps to Reproduce

1. create a PageView (no matter if vertical or horizontal)
2. add several widgets, which all look something like this:
```
    return SingleChildScrollView(
      child: Column(
        children: [
          TextField(),
          _buildCancelButtons(),
          _buildSubmitPageButton()
        ],
      ),
    );
```
3. create Next and Back buttons with .animateToPage(...), or .jumpToPage(...) to jump between pages

**Expected results:** 
That the pages jump back and forth perfectly.

**Actual results:** 
If no TextField() is on any page, everything works just fine.
If a page contains a TextField() this exception will be thrown in most cases:

<details> 
<summary>logs</summary> 

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following UnsupportedError was thrown during paint():
Unsupported operation: Infinity or NaN toInt
The relevant error-causing widget was:
  TextField
  
lib/…/ride/comment.dart:36
When the exception was thrown, this was the stack:
#0      double.toInt  (dart:core-patch/double.dart:192:36)
#1      double.round  (dart:core-patch/double.dart:160:34)
#2      RenderEditable._getPixelPerfectCursorOffset 
package:flutter/…/rendering/editable.dart:1926
#3      RenderEditable._paintCaret 
package:flutter/…/rendering/editable.dart:1978
#4      RenderEditable._paintContents 
package:flutter/…/rendering/editable.dart:2164
#5      RenderEditable.paint 
package:flutter/…/rendering/editable.dart:2206
#6      RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#7      PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:186
#8      RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:133
#9      RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#10     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:186
#11     RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:133
#12     PaintingContext.pushLayer 
package:flutter/…/rendering/object.dart:393
#13     RenderLeaderLayer.paint 
package:flutter/…/rendering/proxy_box.dart:4858
#14     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#15     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:186
#16     RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:133
#17     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#18     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:186
#19     RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:133
#20     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#21     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:186
#22     RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:133
#23     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#24     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:186
#25     RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:133
#26     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#27     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:186
#28     RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:133
#29     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#30     PaintingContext.paintChild 
package:flutter/…/rendering/object.dart:186
#31     RenderProxyBoxMixin.paint 
package:flutter/…/rendering/proxy_box.dart:133
#32     RenderObject._paintWithContext 
package:flutter/…/rendering/object.dart:2266
#33     PaintingContext._repaintCompositedChild 
package:flutter/…/rendering/object.dart:137
#34     PaintingContext.repaintCompositedChild 
package:flutter/…/rendering/object.dart:97
#35     PipelineOwner.flushPaint 
package:flutter/…/rendering/object.dart:982
#36     RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:406
#37     WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:867
#38     RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
#39     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1117
#40     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1056
#41     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:972
#45     _invoke  (dart:ui/hooks.dart:253:10)
#46     _drawFrame  (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderEditable#a541d relayoutBoundary=up15:
  creator: _Editable-[GlobalKey#7d3cf] ← Semantics ← CompositedTransformTarget ←
    IgnorePointer-[GlobalKey#f4c1f] ← Semantics ← _PointerListener ← Listener ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#d7ace] ← _PointerListener ← Listener
    ← _ScrollableScope ← Scrollable ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
  size: Size(414.0, 22.0)
  cursorColor: Color(0xbd2196f3)
  showCursor: ValueNotifier<bool>#83947(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xffbdbdbd)
  textScaleFactor: 1.0
  locale: en
  selection: TextSelection(baseOffset: 7, extentOffset: 7, affinity: TextAffinity.downstream,
    isDirectional: false)
  offset: ScrollPositionWithSingleContext#449a8(offset: 0.0, range: 0.0..0.0, viewport: 414.0,
    ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#ac684,
    ScrollDirection.idle)
This RenderObject had the following child:
    text: TextSpan
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details> 

<details>
  <summary>doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C39d, locale de-DE)
    • Flutter version 1.20.2 at /Users/andreashuber/Flutter/flutter
    • Framework revision bbfbf1770c (4 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andreashuber/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • B0654A22-E7AD-4AC9-8F6C-5664B2C120E3 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
````

</details>

**Comment by hamdikahloun** [comment]
Hi @ndhbr 

Can you upgrade your flutter version please and try again : `flutter upgrade`.

i just try it and no issue found.

```
flutter doctor -v
[√] Flutter (Channel master, 1.22.0-10.0.pre.37, on Microsoft Windows [version 10.0.19041.508], locale fr-FR)
    • Flutter version 1.22.0-10.0.pre.37 at D:\flutter
    • Framework revision cf15bb33c7 (25 hours ago), 2020-09-08 08:12:30 +0100
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\hamdi\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\hamdi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30225.117
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\hamdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.0

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.83
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```

```
import 'package:flutter/material.dart';

void main() {
  runApp(PageViewDemo());
}

class PageViewDemo extends StatefulWidget {
  @override
  _PageViewDemoState createState() => _PageViewDemoState();
}

class _PageViewDemoState extends State<PageViewDemo> {
  PageController _controller = PageController(
    initialPage: 0,
  );

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: PageView(
          controller: _controller,
          children: [
            SingleChildScrollView(
              child: Column(
                children: [
                  TextField(),
                  FlatButton( onPressed: () { _controller.animateToPage(1, duration: Duration(seconds: 2), curve: Curves.bounceIn) ;},
                  child: Text("text")),
                  FlatButton(onPressed: null, child: Text("text"))
                ],
              ),
            ),
            SingleChildScrollView(
              child: Column(
                children: [
                  TextField(),
                ],
              ),
            ),
            SingleChildScrollView(
              child: Column(
                children: [
                  TextField(),
                  FlatButton(onPressed: null, child: Text("text")),
                  FlatButton(onPressed: null, child: Text("text"))
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by ndhbr** [comment]
@hamdikahloun
Thanks for the answer.

I did that shortly after the thread was created. Unfortunately it is still not working.

On each page I have a back button which calls previousPage(...), a cancel button which calls animateToPage(0 or the initial page) and a button for the next page. If I now switch from page 1 (without TextField) to page 2, then type something into the TextField and then switch to page 3, I get the error. It also happens often when I type something into the TextField on page 2 and then press the cancel button on page 3 and it animates back to the first page.

The error does not always occur, only sporadically, but sometimes very often.

**Comment by TahaTesser** [comment]
Hi @ndhbr 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by ayumakesit** [comment]
I faced this error with the TextFormField.
There is a problem with the cursor.

If you set "showCursor: false" in the TextFormField, the error no longer occurs.

Steps to repo:



1. Select TextField/TextFormField in Page 1


Simple code sample:
`    return PageView(
      children: [
        Container(
          height: 50,
          child: Column(
            children: [
              Text('Page 1'),
              TextFormField(),
            ],
          ),
        ),
        Container(
          width: 50,
          child: Column(
            children: [
              Text('Page 2'),
              TextFormField(),
            ],
          ),
        ),
      ],
    );`

**Comment by ayumakesit** [comment]
I faced this error with the TextFormField.
There is a problem with the cursor.

If you set "showCursor: false" in the TextFormField, the error no longer occurs.

**Steps to repo:**
1. Select TextField/TextFormField in Page 1
2. Swipe to Page 2 -> Error occurs
3. Set "showCursor: false" in first TextField/TextFormField in Page 1
4. Swipe to Page 3 -> Error doesn't occur



Simple code sample:
```   
 return PageView(
      children: [
        Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('Page 1'),
            Container(
              width: 200,
              child: TextFormField(),
            ),
          ],
        ),
        Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('Page 2'),
            Container(
              width: 200,
              child: TextFormField(),
            ),
          ],
        ),
      ],
    );
```

**Comment by ndhbr** [comment]
@TahaTesser
As soon as I work on it again I will deliver a code snippet. Thanks!

@ayumakesit 
Thank you, I will try this.

**Comment by LongCatIsLooong** [comment]
I believe this is fixed in https://github.com/flutter/flutter/pull/61940. Closing. Please feel free to reopen if this is still reproducible on master.

**Comment by ayumakesit** [comment]
I face this issue with flutter 1.20.4 also

**Comment by ayumakesit** [comment]
@LongCatIsLooong this is not fixed

**Comment by TahaTesser** [comment]
Hi @ayumakesit
Can you please upgrade to the latest `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by ayumakesit** [comment]
seem to be fixed. 
Thanks!
