### ISSUE TITLE
Exception NoSuchMethodError: The method 'callMethod' was called on null, callMethod("_flutter.listViews") in FlutterVmService.getFlutterViews

### ISSUE THREAD

**Issue by woutervanwijk** [flutter/flutter#65477]
Flutter crashed while building and I found this crash report in my code. I'm on the beta channel

----
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --release -d iphone

## exception

NoSuchMethodError: NoSuchMethodError: The method 'callMethod' was called on null.
Receiver: null
Tried calling: callMethod("_flutter.listViews")

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FlutterVmService.getFlutterViews (package:flutter_tools/src/vmservice.dart:770:50)
#2      FlutterDevice.toggleBrightness (package:flutter_tools/src/resident_runner.dart:449:53)
#3      ResidentRunner.debugToggleBrightness (package:flutter_tools/src/resident_runner.dart:1019:62)
#4      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1427:30)
#5      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1584:13)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#13     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#21     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#22     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#23     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#24     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:256:17)
#25     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:242:5)
#26     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#28     _rootRunUnary (dart:async/zone.dart:1198:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#34     _StreamController._add (dart:async/stream_controller.dart:682:7)
#35     _StreamController.add (dart:async/stream_controller.dart:624:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#37     _rootRunUnary (dart:async/zone.dart:1206:13)
#38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#43     _StreamController._add (dart:async/stream_controller.dart:682:7)
#44     _StreamController.add (dart:async/stream_controller.dart:624:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.20.0-7.4.pre, on Mac OS X 10.15.6 19G73, locale nl-NL)
    • Flutter version 1.20.0-7.4.pre at /Users/wouter/Library/flutter
    • Framework revision 916c3ac648 (9 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wouter/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/wouter/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Touwer (mobile)    • 00008020-001A2C183A60802E            • ios            • iOS 13.6
    • iPhone 11 (mobile) • A60126EC-021E-4E7A-BFE1-2860A264F766 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

**Comment by TahaTesser** [comment]
Related to https://github.com/flutter/flutter/issues/59608

**Comment by jmagman** [comment]
\cc @jonahwilliams
