### ISSUE TITLE
app crash on android api 16

### ISSUE THREAD

**Issue by mrugendra** [flutter/flutter#6548]
## Steps to Reproduce
API 16 (4.1.2) device, HTC  Desire 300 
cd to flutter-gallery
run comment ```flutter run --release```

## Logs
```
10-27 11:16:11.459 8717-8717/? E/FlutterMain: Unable to load Sky Engine binary.
org.chromium.base.library_loader.ProcessInitException
  at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:262)
  at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123)
  at io.flutter.view.FlutterMain.initNative(FlutterMain.java:233)
  at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:128)
  at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4922)
  at android.app.ActivityThread.access$1300(ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:155)
  at android.app.ActivityThread.main(ActivityThread.java:5559)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:511)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841)
  at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:   133 cannot locate '__strlen_chk'...
  at java.lang.Runtime.loadLibrary(Runtime.java:370)
  at java.lang.System.loadLibrary(System.java:535)
  at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:250)
  at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123) 
  at io.flutter.view.FlutterMain.initNative(FlutterMain.java:233) 
  at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:128) 
  at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19) 
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4922) 
  at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419) 
  at android.os.Handler.dispatchMessage(Handler.java:99) 
  at android.os.Looper.loop(Looper.java:155) 
  at android.app.ActivityThread.main(ActivityThread.java:5559) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:511) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841) 
  at dalvik.system.NativeStart.main(Native Method) 
10-27 11:16:11.469 338-361/? E/EmbeddedLogger: App crashed! Process: io.flutter.examples.gallery
10-27 11:16:11.469 338-361/? E/EmbeddedLogger: App crashed! Package: io.flutter.examples.gallery v1 (0.0.1)
10-27 11:16:11.469 338-361/? E/EmbeddedLogger: App crashed! Application Label: Gallery
10-27 11:16:11.469 8717-8717/? E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to create application org.domokit.sky.shell.SkyApplication: java.lang.RuntimeException: org.chromium.base.library_loader.ProcessInitException
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4925)
   at android.app.ActivityThread.access$1300(ActivityThread.java:151)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:155)
   at android.app.ActivityThread.main(ActivityThread.java:5559)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: org.chromium.base.library_loader.ProcessInitException
   at io.flutter.view.FlutterMain.initNative(FlutterMain.java:237)
   at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:128)
   at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19)
   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4922)
   at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:155) 
   at android.app.ActivityThread.main(ActivityThread.java:5559) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:511) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841) 
   at dalvik.system.NativeStart.main(Native Method) 
Caused by: org.chromium.base.library_loader.ProcessInitException
   at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:262)
   at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123)
   at io.flutter.view.FlutterMain.initNative(FlutterMain.java:233)
   at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:128) 
   at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19) 
   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4922) 
   at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:155) 
   at android.app.ActivityThread.main(ActivityThread.java:5559) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:511) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841) 
   at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:   133 cannot locate '__strlen_chk'...
   at java.lang.Runtime.loadLibrary(Runtime.java:370)
   at java.lang.System.loadLibrary(System.java:535)
   at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:250)
   at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123) 
   at io.flutter.view.FlutterMain.initNative(FlutterMain.java:233) 
   at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:128) 
   at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19) 
   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4922) 
   at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1419) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:155) 
   at android.app.ActivityThread.main(ActivityThread.java:5559) 
   at java.lang.reflect.Method.invokeNative(Native Method) 
   at java.lang.reflect.Method.invoke(Method.java:511) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1074) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:841) 
   at dalvik.system.NativeStart.main(Native Method) 

```

## Flutter Doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/mrugendrathattle/Research/Flutter/flutter
    • Framework revision edbe034847 (7 days ago), 2016-10-19 16:10:46
    • Engine revision 525c947ece
    • Tools Dart version 1.21.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/mrugendrathattle/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[-] iOS toolchain - develop for iOS devices (Xcode 8.0)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.0, Build version 8A218a
    x Brew not installed; use this to install tools for iOS device development.
      Download brew at http://brew.sh/.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.6
    • dartlang plugin version 0.6.42

[✓] Connected devices
    • HT46AWL00712 • HT46AWL00712 • android-arm

**Comment by chinmaygarde** [comment]
If memory serves, `__strlen_chk` should only be emitted when using `FORTIFY_SOURCE`. But we are already using NDK platform API level 16 https://github.com/flutter/buildroot/commit/57745f9c4ce6d88132ff42f67f13ed324790ecb9 this issue should have been caught at build time.

@jason-simmons Any thoughts on what is going on? The simple workaround would be to get rid of FORTIFY_SOURCE but that seem wrong.

**Comment by chinmaygarde** [comment]
On further investigation, the engine revision pointed at in the logs points to buildroot revision https://github.com/flutter/buildroot/tree/9dcb5b06fe497f1bfd563e2c9293161070d5340c which does not have @jason-simmons fix. The latest engine.version on flutter/flutter does. So the fix has been pushed out.

@mrugendra: Please update your Flutter checkout for the fix. Thanks.

Closing.

**Comment by mrugendra** [comment]
@chinmaygarde thank you, seems all good after checkout
