### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for G:\flutter_app\flutter_app\android\gradlew.bat.

### ISSUE THREAD

**Issue by devappbirds** [flutter/flutter#65531]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=d50cd3977d15 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for G:\flutter_app\flutter_app\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:466:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:484:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:388:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:103:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:587:28)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.20.3 at G:\flutter
    • Framework revision 216dee60c0 (9 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at G:/Android-SDK
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = G:/Android-SDK
    • Java binary at: G:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at G:\android-studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (1 available)
    • Redmi 5A (mobile) • d50cd3977d15 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 216dee60c0cc9449f0b29bcf922974d612263e24

**Comment by darshankawar** [comment]
Hi @devappbirds,
There's similar open issue describing your case, [56975](https://github.com/flutter/flutter/issues/56975).
Please follow-up there for updates and any questions.
Closing this as duplicate.
Thanks.
