### ISSUE TITLE
I got this error after running "flutter clean": java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by Collins01-max** [flutter/flutter#65543]
Launching lib\main.dart on Nokia 3 1 in debug mode...
Running Gradle task 'assembleDebug'...
java.nio.file.NoSuchFileException: C:\Users\Collins\Documents\Flutter Projects\wear_off_covid19\build\app\intermediates\external_file_lib_dex_archives\debug\out
Running Gradle task 'assembleDebug'...
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
Running Gradle task 'assembleDebug'...
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
Running Gradle task 'assembleDebug'...
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
Running Gradle task 'assembleDebug'...
        at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
Running Gradle task 'assembleDebug'...
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
Running Gradle task 'assembleDebug'...
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
Running Gradle task 'assembleDebug'...
        at java.nio.file.Files.list(Files.java:3451)
Running Gradle task 'assembleDebug'...
        at com.android.build.gradle.internal.tasks.DexMergingParams.getAllDexFiles(DexMergingTask.kt:502)
Running Gradle task 'assembleDebug'...
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:423)
Running Gradle task 'assembleDebug'...
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
Running Gradle task 'assembleDebug'...
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
Running Gradle task 'assembleDebug'...
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
Running Gradle task 'assembleDebug'...
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Running Gradle task 'assembleDebug'...
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Running Gradle task 'assembleDebug'...
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Running Gradle task 'assembleDebug'...
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Running Gradle task 'assembleDebug'...
        at java.lang.Thread.run(Thread.java:748)
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
FAILURE: Build failed with an exception.
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* What went wrong:
Running Gradle task 'assembleDebug'...
Execution failed for task ':app:mergeExtDexDebug'.
Running Gradle task 'assembleDebug'...
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
Running Gradle task 'assembleDebug'...
   > java.nio.file.NoSuchFileException: C:\Users\Collins\Documents\Flutter Projects\wear_off_covid19\build\app\intermediates\external_file_lib_dex_archives\debug\out
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* Try:
Running Gradle task 'assembleDebug'...
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get
more log output. Run with --scan to get full insights.
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* Get more help at https://help.gradle.org
Running Gradle task 'assembleDebug'...

**Comment by pedromassangocode** [comment]
Hi @Collins01-max 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by Collins01-max** [comment]
Thanks guys...
I solved it by adding "multidexenabled " to true ,inside the android folder

**Comment by AbdOoSaed** [comment]
Solved this issue by deleting the .gradle folder

**Comment by Virenvkj** [comment]
> Solved this issue by deleting the .gradle folder
Thanks, Man.
