### ISSUE TITLE
error when navigating back to the previous page from a Chewie Video player page 

### ISSUE THREAD

**Issue by Rstream-app** [flutter/flutter#65542]
I have a page that shows video. But when I complete the video and pop back to the previous page I get the bellow error. My app works all fine and good with no breaks, but this below error bothers me.

I need help to fix this error.

**Here is my error:**

<details>
<summary>error log</summary>

```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for VideoPlayerController:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4182 pos 12:
'_debugLifecycleState != _ElementLifecycle.defunct': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4182:12)
#3      State.setState (package:flutter/src/widgets/framework.dart:1260:14)
#4      _VideoState.initState.<anonymous closure> (package:/widget/page/video.dart:79:9)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:209:21)
#6      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:276:5)
#7      VideoPlayerController.pause (package:video_player/video_player.dart:360:5)
#8      _VideoState.dispose (package:/widget/page/video.dart:120:34)
#9      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4773:12)
#10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1935:13)
#11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#12     _Closure.call (dart:core-patch/function.dart)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#19     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#22     _Closure.call (dart:core-patch/function.dart)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#26     _Closure.call (dart:core-patch/function.dart)
#27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#30     _Closure.call (dart:core-patch/function.dart)
#31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#34     _Closure.call (dart:core-patch/function.dart)
#35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#38     List.forEach (dart:core-patch/growable_array.dart:302:8)
#39     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:1312:36)
#40     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#41     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#42     _Closure.call (dart:core-patch/function.dart)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#49     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#55     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#58     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#61     _Closure.call (dart:core-patch/function.dart)
#62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#68     _Closure.call (dart:core-patch/function.dart)
#69     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#70     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#71     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#72     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#73     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#74     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#75     _Closure.call (dart:core-patch/function.dart)
#76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#79     _Closure.call (dart:core-patch/function.dart)
#80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#83     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#86     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#89     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#92     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#95     _Closure.call (dart:core-patch/function.dart)
#96     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#97     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#98     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#99     _Closure.call (dart:core-patch/function.dart)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#103    _Closure.call (dart:core-patch/function.dart)
#104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#107    _Closure.call (dart:core-patch/function.dart)
#108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#109    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#110    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#111    _Closure.call (dart:core-patch/function.dart)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#115    _Closure.call (dart:core-patch/function.dart)
#116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#118    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#119    _Closure.call (dart:core-patch/function.dart)
#120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#121    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#122    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#123    _Closure.call (dart:core-patch/function.dart)
#124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#127    _Closure.call (dart:core-patch/function.dart)
#128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#129    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#130    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#131    _Closure.call (dart:core-patch/function.dart)
#132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#133    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#134    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#135    _Closure.call (dart:core-patch/function.dart)
#136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#139    _Closure.call (dart:core-patch/function.dart)
#140    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#141    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#142    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#143    _Closure.call (dart:core-patch/function.dart)
#144    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#145    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#146    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#147    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5973:16)
#148    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#149    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#150    _Closure.call (dart:core-patch/function.dart)
#151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#153    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#154    _Closure.call (dart:core-patch/function.dart)
#155    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#156    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#157    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#158    _Closure.call (dart:core-patch/function.dart)
#159    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#160    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#161    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#162    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#163    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#164    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#165    _Closure.call (dart:core-patch/function.dart)
#166    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#167    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#168    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#169    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#170    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#171    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#172    _Closure.call (dart:core-patch/function.dart)
#173    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#174    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#175    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#176    _Closure.call (dart:core-patch/function.dart)
#177    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#178    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#179    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#180    _Closure.call (dart:core-patch/function.dart)
#181    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#182    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#183    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#184    _Closure.call (dart:core-patch/function.dart)
#185    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#186    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#187    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#188    _Closure.call (dart:core-patch/function.dart)
#189    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#190    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#191    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#192    _Closure.call (dart:core-patch/function.dart)
#193    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#194    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#195    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#196    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#197    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#198    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#199    _Closure.call (dart:core-patch/function.dart)
#200    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#201    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#202    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#203    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#204    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#205    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#206    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#207    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#208    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#209    _Closure.call (dart:core-patch/function.dart)
#210    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#211    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#212    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#213    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#214    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#215    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#216    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#217    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#218    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#219    _Closure.call (dart:core-patch/function.dart)
#220    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#221    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#222    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#223    _Closure.call (dart:core-patch/function.dart)
#224    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#225    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#226    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#227    _Closure.call (dart:core-patch/function.dart)
#228    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#229    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#230    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#231    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#232    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#233    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#234    _Closure.call (dart:core-patch/function.dart)
#235    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#236    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#237    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#238    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#239    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#240    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#241    _Closure.call (dart:core-patch/function.dart)
#242    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#243    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#244    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#245    _Closure.call (dart:core-patch/function.dart)
#246    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#247    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#248    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#249    _Closure.call (dart:core-patch/function.dart)
#250    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#251    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#252    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#253    _Closure.call (dart:core-patch/function.dart)
#254    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#255    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#256    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#257    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#258    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#259    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#260    _Closure.call (dart:core-patch/function.dart)
#261    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#262    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#263    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#264    _Closure.call (dart:core-patch/function.dart)
#265    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#266    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#267    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#268    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5861:14)
#269    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#270    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#271    _Closure.call (dart:core-patch/function.dart)
#272    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#273    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#274    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#275    _Closure.call (dart:core-patch/function.dart)
#276    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#277    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#278    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1933:7)
#279    _Closure.call (dart:core-patch/function.dart)
#280    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4600:14)
#281    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1931:13)
#282    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#283    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1944:25)
#284    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2754:27)
#285    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2558:15)
#286    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2753:7)
#287    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:868:18)
#288    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#289    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#290    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#291    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#295    _invoke (dart:ui/hooks.dart:253:10)
#296    _drawFrame (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)

The VideoPlayerController sending notification was:
  VideoPlayerController#90b88(VideoPlayerValue(duration: 0:10:55.430000, size: Size(1920.0, 1080.0),
  position: 0:10:55.430000, caption: Instance of 'Caption', buffered: [DurationRange(start:
  0:00:00.000000, end: 0:10:55.430000)], isPlaying: false, isLooping: false, isBuffering:
  falsevolume: 1.0, errorDescription: null))
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by foundation library ════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for VideoPlayerController:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4182 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4182:12)
#3      State.setState (package:flutter/src/widgets/framework.dart:1260:14)
#4      _VideoState.initState.<anonymous closure> (package:/widget/page/video.dart:79:9)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:209:21)
#6      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:276:5)
...
The VideoPlayerController sending notification was: VideoPlayerController#90b88(VideoPlayerValue(duration: 0:10:55.430000, size: Size(1920.0, 1080.0), position: 0:10:55.430000, caption: Instance of 'Caption', buffered: [DurationRange(start: 0:00:00.000000, end: 0:10:55.430000)], isPlaying: false, isLooping: false, isBuffering: falsevolume: 1.0, errorDescription: null))

```

</details>

**Comment by darshankawar** [comment]
Hi @Rstream-app,
This seems to be an issue with the video player plugin you are using, chewie, which is 3rd party.
Please consider opening this issue in their repo : https://github.com/brianegan/chewie/issues.
Closing this as it doesn't seem to be an issue with Flutter. If you disagree, write in comments and I'll reopen.
Thanks.
