### ISSUE TITLE
platform_views_scroll_perf_ios__timeline_summary is flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#65556]
The current flakes appear to be losing the connection to the device.

Adding to the infra queue as a P0 since this is blocking an engine roll needed for the branch cut.

**Comment by cyanglaz** [comment]
For future debugging: the flakiness started somewhere earlier than 127e67902e8bbb0dcbfb3351b8fd00f7cbdf0178

**Comment by cyanglaz** [comment]
Log:
```
2020-09-09T20:53:39.468483: stdout: [   +1 ms]   DriverError: Failed to fulfill SetFrameSync due to remote error
stdout: [        ]   Original error: Bad state: The client is closed.
stdout: [        ]   Original stack trace:
2020-09-09T20:53:39.468735: stdout: [        ]   #0      Client._send (package:json_rpc_2/src/client.dart:139:19)
stdout: [        ]   #1      Client.sendRequest (package:json_rpc_2/src/client.dart:107:5)
2020-09-09T20:53:39.468871: stdout: [        ]   #2      Peer.sendRequest (package:json_rpc_2/src/peer.dart:99:15)
2020-09-09T20:53:39.468931: stdout: [        ]   #3      Scope.sendRequestRaw (package:vm_service_client/src/scope.dart:64:23)
2020-09-09T20:53:39.468990: stdout: [        ]   #4      VMIsolateRef.invokeExtension (package:vm_service_client/src/isolate.dart:361:19)
2020-09-09T20:53:39.469090: stdout: [        ]   #5      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:334:63)
2020-09-09T20:53:39.469186: stdout: [        ]   #6      VMServiceFlutterDriver.runUnsynchronized (package:flutter_driver/src/driver/vmservice_driver.dart:531:13)
2020-09-09T20:53:39.469244: stdout: [        ]   <asynchronous suspension>
2020-09-09T20:53:39.469327: stdout: [        ]   #7      main.<anonymous closure>.<anonymous closure> (file:///Users/flutter/.cocoon/flutter/dev/benchmarks/platform_views_layout/test_driver/scroll_perf_test.dart:59:20)
2020-09-09T20:53:39.469405: stdout: [        ]   #8      Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
2020-09-09T20:53:39.469478: stdout: [        ]   <asynchronous suspension>
2020-09-09T20:53:39.469577: stdout: [        ]   #9      Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
2020-09-09T20:53:39.469649: stdout: [        ]   #10     _rootRun (dart:async/zone.dart:1190:13)
2020-09-09T20:53:39.469743: stdout: [        ]   #11     _CustomZone.run (dart:async/zone.dart:1093:19)
2020-09-09T20:53:39.469824: stdout: [        ]   #12     _runZoned (dart:async/zone.dart:1630:10)
2020-09-09T20:53:39.469889: stdout: [        ]   #13     runZoned (dart:async/zone.dart:1550:10)
2020-09-09T20:53:39.470004: stdout: [        ]   #14     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
2020-09-09T20:53:39.470073: stdout: [        ]   #15     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
2020-09-09T20:53:39.470177: stdout: [        ]   #16     _rootRun (dart:async/zone.dart:1190:13)
2020-09-09T20:53:39.470264: stdout: [        ]   #17     _CustomZone.run (dart:async/zone.dart:1093:19)
2020-09-09T20:53:39.470349: stdout: [        ]   #18     _runZoned (dart:async/zone.dart:1630:10)
2020-09-09T20:53:39.470433: stdout: [        ]   #19     runZoned (dart:async/zone.dart:1550:10)
2020-09-09T20:53:39.470511: stdout: [        ]   #20     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
2020-09-09T20:53:39.470581: stdout: [        ]   #21     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
2020-09-09T20:53:39.470669: stdout: [        ]   <asynchronous suspension>
2020-09-09T20:53:39.470750: stdout: [        ]   #22     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
2020-09-09T20:53:39.470830: stdout: [        ]   #23     _rootRun (dart:async/zone.dart:1190:13)
2020-09-09T20:53:39.470907: stdout: [        ]   #24     _CustomZone.run (dart:async/zone.dart:1093:19)
2020-09-09T20:53:39.470976: stdout: [        ]   #25     _runZoned (dart:async/zone.dart:1630:10)
2020-09-09T20:53:39.471067: stdout: [        ]   #26     runZoned (dart:async/zone.dart:1550:10)
2020-09-09T20:53:39.471151: stdout: [        ]   #27     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
2020-09-09T20:53:39.471235: stdout: [        ]   #28     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
2020-09-09T20:53:39.471312: stdout: [        ]   #29     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
2020-09-09T20:53:39.471384: stdout: [        ]   #30     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:104:24)
2020-09-09T20:53:39.471475: stdout: [        ]   #31     _rootRun (dart:async/zone.dart:1190:13)
2020-09-09T20:53:39.471542: stdout: [        ]   #32     _CustomZone.run (dart:async/zone.dart:1093:19)
2020-09-09T20:53:39.471614: stdout: [        ]   #33     _runZoned (dart:async/zone.dart:1630:10)
2020-09-09T20:53:39.471705: stdout: [        ]   #34     runZoned (dart:async/zone.dart:1550:10)
2020-09-09T20:53:39.471787: stdout: [        ]   #35     Chain.capture (package:stack_trace/src/chain.dart:102:12)
2020-09-09T20:53:39.471864: stdout: [        ]   #36     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
2020-09-09T20:53:39.472007: stdout: [        ]   #37     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
stdout: [        ]   #38     new Future.microtask.<anonymous closure> (dart:async/future.dart:201:37)
2020-09-09T20:53:39.472144: stdout: [        ]   #39     _rootRun (dart:async/zone.dart:1182:47)
2020-09-09T20:53:39.472275: stdout: [        ]   #40     _CustomZone.run (dart:async/zone.dart:1093:19)
stdout: [        ]   #41     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
2020-09-09T20:53:39.472408: stdout: [        ]   #42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
stdout: [        ]   #43     _rootRun (dart:async/zone.dart:1190:13)
2020-09-09T20:53:39.472588: stdout: [        ]   #44     _CustomZone.run (dart:async/zone.dart:1093:19)
stdout: [        ]   #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
2020-09-09T20:53:39.472749: stdout: [        ]   #46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
stdout: [        ]   #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
2020-09-09T20:53:39.472901: stdout: [        ]   #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
stdout: [        ]   #49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
2020-09-09T20:53:39.473064: stdout: [        ]   #50     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
2020-09-09T20:53:39.473159: stdout: [        ]   #51     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
2020-09-09T20:53:39.473309: stdout: [        ]   #52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
2020-09-09T20:53:39.485391: stdout: [  +11 ms]   package:flutter_driver/src/driver/vmservice_driver.dart 345:7  VMServiceFlutterDriver.sendCommand
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
2020-09-09T20:53:39.485779: stdout: [        ]   dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
2020-09-09T20:53:39.485975: stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
2020-09-09T20:53:39.486131: stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
2020-09-09T20:53:39.486260: stdout: [        ]   dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
2020-09-09T20:53:39.486515: stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
2020-09-09T20:53:39.486620: stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
2020-09-09T20:53:39.486680: stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
2020-09-09T20:53:39.486751: stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
2020-09-09T20:53:39.486835: stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                Invoker._onRun.<fn>.<fn>
2020-09-09T20:53:39.486893: stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15               Invoker._guardIfGuarded
2020-09-09T20:53:39.487173: stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                Invoker._onRun.<fn>
stdout: [        ]   package:stack_trace/src/chain.dart 104:24                      Chain.capture.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
2020-09-09T20:53:39.487227: stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
2020-09-09T20:53:39.487275: stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
2020-09-09T20:53:39.487389: stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
2020-09-09T20:53:39.487685: stdout: [        ]   package:stack_trace/src/chain.dart 102:12                      Chain.capture
stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11               Invoker._onRun
stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11  LiveTestController.run
2020-09-09T20:53:39.487795: stdout: [        ]   dart:async/future.dart 201:37                                  new Future.microtask.<fn>
2020-09-09T20:53:39.487865: stdout: [        ]   dart:async/zone.dart 1182:47                                   _rootRun
2020-09-09T20:53:39.487953: stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
2020-09-09T20:53:39.488054: stdout: [        ]   dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
2020-09-09T20:53:39.488128: stdout: [        ]   dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
2020-09-09T20:53:39.488208: stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
2020-09-09T20:53:39.488290: stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
2020-09-09T20:53:39.488363: stdout: [        ]   dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
2020-09-09T20:53:39.488425: stdout: [        ]   dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
2020-09-09T20:53:39.488516: stdout: [        ]   dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
2020-09-09T20:53:39.488593: stdout: [        ]   dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
2020-09-09T20:53:39.488684: stdout: [        ]   dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
2020-09-09T20:53:39.488756: stdout: [        ]   dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
2020-09-09T20:53:39.488839: stdout: [        ]   dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
2020-09-09T20:53:39.488944: stdout: [        ]   dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
2020-09-09T20:53:39.490432: stderr: [   +1 ms] VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
2020-09-09T20:53:39.507890: stdout: [  +17 ms] 00:03 [32m+0[0m[31m -1[0m: scrolling performance test (tearDownAll)[0m
2020-09-09T20:53:39.517733: stdout: [   +9 ms] 00:03 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
2020-09-09T20:53:39.519351: stderr: [   +1 ms] Unhandled exception:
stderr: [        ] Dummy exception to set exit code.
```

**Comment by cyanglaz** [comment]
Lower the issue to P1 as we marked the test as flaky to un-block the tree.

**Comment by cyanglaz** [comment]
Updates: the crash is caused by enabling thread merger: https://github.com/flutter/engine/commit/e7136c3f5960f34b27579e893454886db105e88b
I'm going to debug the root cause and work on a fix.

**Comment by blasten** [comment]
@cyanglaz is this fixed by https://github.com/flutter/engine/pull/21059?

**Comment by cyanglaz** [comment]
Updated:
It is not fixed by flutter/engine#21059
Looks like engine log is not printing for me so it is hard to debug. One thing I find is if I remove the animating overlay widget, the crash doesn't happen.
So looks like it might be related to how the overlay works with thread merging while app is starting up.
It might also be related to constant submitting frames when the threads are merged.

**Comment by blasten** [comment]
If you manually run the app multiple times (without `flutter drive`), does it still happen?  If it does, what about launching it with Xcode until it crashes?  This way you can jump right to the code that caused the crash.

**Comment by cyanglaz** [comment]
@blasten The crash didn't happen for me on `flutter run`, only drive.

**Comment by cyanglaz** [comment]
@blasten Tried with `flutter drive` while disabling the scrolling, no crashes.

**Comment by blasten** [comment]
It sounds like it would get a crash if you are able to simulate a user scrolling while the app is launched from Xcode.

**Comment by cyanglaz** [comment]
Able to get some logs and it looks like the it crashed on https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L616
```
Runner(2362,0x100fa1880) malloc: Incorrect checksum for freed object 0x15980ec00: probably modified after being freed.
Corrupt value: 0x5424b4797b
Runner(2362,0x100fa1880) malloc: *** set a breakpoint in malloc_error_break to debug
Process 2362 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x000000018f77cdf0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x18f77cdf0 <+8>:  b.lo   0x18f77ce0c               ; <+36>
    0x18f77cdf4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x18f77cdf8 <+16>: mov    x29, sp
    0x18f77cdfc <+20>: bl     0x18f75b0e8               ; cerror_nocancel
Target 0: (Runner) stopped.
```

The crash happened several frames after the thread merging.

**Comment by chinmaygarde** [comment]
@cyanglaz: Are you still working on this? I don't think this is blocking an engine roll as indicated in the original comment. I am lowering the priority of this issue but feel to update your assignment too if you are not working on this.

**Comment by cyanglaz** [comment]
Yes I'm still working on this. This is not blocking engine-roll so I lowered it from P0 to P1. However, this is still high priority as we want to fix the underlining issue and revive the test as early as possible. Maybe P2?

**Comment by jmagman** [comment]
The devicelab logs include crashes now:
```
2020-09-21T12:38:06.084210: stdout: [ +320 ms] Process 55277 stopped
2020-09-21T12:38:06.084316: stdout: [        ] * thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xbf80000000000009)
2020-09-21T12:38:06.084408: stdout: [        ]     frame #0: 0x0000000103034484 Flutter`dart::TimelineEvent::Init(dart::TimelineEvent::EventType, char const*) + 148
2020-09-21T12:38:06.084573: stdout: [        ] Flutter`dart::TimelineEvent::Init:
2020-09-21T12:38:06.084837: stdout: [        ] ->  0x103034484 <+148>: ldr    x0, [x0, #0x8]
stdout: [        ]     0x103034488 <+152>: bl     0x10309923c               ; symbol stub for: free
2020-09-21T12:38:06.085012: stdout: [        ]     0x10303448c <+156>: ldr    x8, [x19, #0x28]
stdout: [        ]     0x103034490 <+160>: cmp    x8, #0x2                  ; =0x2 
2020-09-21T12:38:06.085225: stdout: [        ] Target 0: (Runner) stopped.
```

[platform_views_scroll_perf_ios__timeline_summary_a029e17_1.log](https://github.com/flutter/flutter/files/5258268/platform_views_scroll_perf_ios__timeline_summary_a029e17_1.log)

**Comment by cyanglaz** [comment]
Thanks @jmagman 

The logs says it crashed on `Flutter`dart::TimelineEvent::Init(dart::TimelineEvent::EventType, char const*)`?
I couldn't find this method in either framework or engine code.

**Comment by jmagman** [comment]
It's in the VM: https://github.com/dart-lang/sdk/blob/d33e51df3cda1d8caa0a4a6c006adb7c6aa331ee/runtime/vm/timeline.cc#L565

**Comment by cyanglaz** [comment]
Run `flutter drive` without `--trace-startup` actually fixed the crash.

**Comment by Hixie** [comment]
Since the flake itself is mitigated, moving this to P3 to get it off the weekly checkin list.

**Comment by cyanglaz** [comment]
The test has been re-enabled. I am actively working on some other p1 issues these days and will not be able to investigate the root cause of this crash any further these days. I will un-assign myself for now and might pick it up later when other p1 issues are fixed.

**Comment by cyanglaz** [comment]
Note that re-enable the `--trace-startup` flag will reproduce the crash in about once per 20 runs.

**Comment by cyanglaz** [comment]
Another instance of a similar crash for non-platform view tests. https://github.com/flutter/flutter/issues/129258

**Comment by zanderso** [comment]
Closing as presumed stale.
