### ISSUE TITLE
Tap on dropdown button in tests does not work

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6562]
Reported by customer:Leafy...

We have a test that tries to change the value of a dropdown button by tapping on it. However, we are getting exceptions regarding the theme.

code:
await tester.tap(find.text('Flighted'));

result:
```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while dispatching a pointer event:
The null object does not have a getter 'isMaterialAppTheme'.

NoSuchMethodError: method not found: 'isMaterialAppTheme'
Receiver: null
Arguments: []

When the exception was thrown, this was the stack:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      Theme.of (package:flutter/src/material/theme.dart:65:37)
#3      _DropdownButtonState._handleTap (package:flutter/src/material/drop_down.dart:494:20)
#4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:148:14)
#5      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:119:7)
#6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:119:27)
#7      BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:126:20)
#8      BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:100:22)
#9      TestWidgetsFlutterBinding.dispatchEvent (package:flutter_test/src/binding.dart:181:24)
#10     WidgetTester.sendEventToBinding.<anonymous closure>.<<anonymous closure>_async_body> (package:flutter_test/src/widget_tester.dart:236:15)
#20     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:520:16)
#21     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:366:5)
#22     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:506:24)
#28     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:504:16)
#29     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:54:50)
#30     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:106:19)
#42     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:183:3)
(elided 61 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)

Event:
  PointerUpEvent(Point(77.0, 268.0))
Target:
  <AutomatedTestWidgetsFlutterBinding>
```

**Comment by abarth** [comment]
The bug is one line 105 of theme.dart.  It needs to handle the case of `theme` being null.
