### ISSUE TITLE
Exception caught by animation library: Failed assertion: line 4138 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

### ISSUE THREAD

**Issue by WouterVandenputte** [flutter/flutter#65629]
The framework threw an error and advised it to report it, so here it is

```
════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4138 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4138:12)
#3      State.setState (package:flutter/src/widgets/framework.dart:1253:14)
#4      _SomeState.someFunc.<anonymous closure> (package:some_package/widgets/some_class.dart:274:9)
#5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:135:19)
#6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:792:5)
...
The AnimationController notifying listeners was: AnimationController#63dbe(▶ 0.997)
```

**Comment by TahaTesser** [comment]
Hi @WouterVandenputte 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you
