### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.Receiver: nullTried calling: cancel()

### ISSUE THREAD

**Issue by ujjawa1** [flutter/flutter#65647]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:969:11)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:750:5)
#3      AnsiStatus.stop (package:flutter_tools/src/base/logger.dart:1051:11)
#4      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1506:16)
<asynchronous suspension>
#5      ArtifactUpdater.downloadZipArchive (package:flutter_tools/src/cache.dart:1442:12)
#6      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:717:29)
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:573:11)
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:925:27)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:831:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZoned (dart:async/zone.dart:1550:10)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:820:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.82 at /home/ujjawal/flutter
    • Framework revision 9248fda410 (8 days ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/ujjawal/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/ujjawal/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 4.0)
    • Android Studio at /home/ujjawal/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 9248fda41005ce0af2e522fabd0e9fedf2b3c863
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
file_picker-1.13.3
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_database-3.1.6
firebase_storage-3.1.6
flutter_plugin_android_lifecycle-1.0.8
fluttertoast-7.0.2
google_sign_in-4.5.1
google_sign_in_web-0.9.1+1
path_provider_linux-0.0.1+2
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2+1

**Comment by iapicca** [comment]
@ujjawa1 
`NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.`
this seems to point at a problem with the implementation
can you provide a minimal code sample (w/o 3rd party plugins)

**Comment by markusaksli-nc** [comment]
Hi @ujjawa1 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/65449.
Please follow up on that issue, since your stack is pretty much identical I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
