### ISSUE TITLE
Throwing in didChangeDependencies after establishing dependencies causes failures during test teardown

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#65655]
```dart
// @dart = 2.8

import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('example', (WidgetTester tester) async {
    await tester.pumpWidget(Foo(child: Bar()));
    expect(tester.takeException(), isFlutterError);

// Work around:
//    await tester.pumpWidget(Container());
//    expect(tester.takeException(), isAssertionError);
  });
}

class Foo extends InheritedWidget {
  const Foo({Widget child}) : super(child: child);

  static Foo of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<Foo>();
  }

  @override
  bool updateShouldNotify(covariant InheritedWidget oldWidget) => false;
}

class Bar extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => BarState();
}

class BarState extends State<Bar> {
  Foo currentFoo;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    currentFoo = Foo.of(context);
    throw FlutterError('something went wrong');
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown attaching to the render tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5100 pos 14:
'_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5100:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5102:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2022:6)
#6      _InactiveElements.add (package:flutter/src/widgets/framework.dart:2030:7)
#7      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3605:29)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3322:9)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
#10     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1230:5)
#11     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1244:7)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#14     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1088:18)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#18     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1036:5)
#19     runApp (package:flutter/src/widgets/binding.dart:1063:7)
#20     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:791:7)
<asynchronous suspension>
#23     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#24     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#25     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#30     withClock (package:clock/src/default.dart:48:10)
#31     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#36     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#37     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#38     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#39     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#40     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#45     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#46     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#51     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#52     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#53     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#58     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#59     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#60     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#67     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#68     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#69     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#74     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#75     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#93     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#94     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#98     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#132    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#140    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#141    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#151    _Socket._onData (dart:io-patch/socket_patch.dart:2150:41)
#160    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1686:33)
#161    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1182:14)
(elided 113 frames from class _AssertionError, dart:async, and package:stack_trace)
```

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('example', (WidgetTester tester) async {
    await tester.pumpWidget(Foo(child: Bar()));
    expect(tester.takeException(), isFlutterError);

// Work around:
//    await tester.pumpWidget(Container());
//    expect(tester.takeException(), isAssertionError);
  });
}

class Foo extends InheritedWidget {
  const Foo({Widget child}) : super(child: child);

  static Foo of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<Foo>();
  }

  @override
  bool updateShouldNotify(covariant InheritedWidget oldWidget) => false;
}

class Bar extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => BarState();
}

class BarState extends State<Bar> {
  Foo currentFoo;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    currentFoo = Foo.of(context);
    throw FlutterError('something went wrong');
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```

</details> 

<details> 
<summary>logs</summary> 

```bash
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown attaching to the render tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5098 pos 14:
'_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5098:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5100:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2022:6)
#6      _InactiveElements.add (package:flutter/src/widgets/framework.dart:2030:7)
#7      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3605:29)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3322:9)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
#10     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1230:5)
#11     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1244:7)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#14     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1088:18)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#18     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1036:5)
#19     runApp (package:flutter/src/widgets/binding.dart:1063:7)
#20     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:791:7)
<asynchronous suspension>
#23     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#24     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#25     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#30     withClock (package:clock/src/default.dart:48:10)
#31     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#36     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#37     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#38     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#39     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#40     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#45     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#46     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#51     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#52     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#53     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#58     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#59     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#60     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#67     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#68     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#69     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#74     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#75     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#93     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#94     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#98     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#132    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#140    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#141    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#151    _Socket._onData (dart:io-patch/socket_patch.dart:2150:41)
#160    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1686:33)
#161    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1182:14)
(elided 113 frames from class _AssertionError, dart:async, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: example

✖ example
Exited (1)

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.138, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.138 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 620cd16cf0 (3 days ago), 2020-09-11 10:35:03 -0400
    • Engine revision a0bd862cc0
    • Dart version 2.10.0 (build 2.10.0-115.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details>
