### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.Receiver: nullTried calling: cancel()

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#65709]
## Command
```
flutter build windows --obfuscate --split-debug-info .\build\windows_debug_info
```

## Steps to Reproduce
1. Upgrade flutter to latest master
2. Run the above command
3. Flutter exits

## Logs

<details>

<summary>Logs</summary>

NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:969:11)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:750:5)
#3      AnsiStatus.stop (package:flutter_tools/src/base/logger.dart:1051:11)
#4      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1506:16)
<asynchronous suspension>
#5      ArtifactUpdater.downloadZipArchive (package:flutter_tools/src/cache.dart:1442:12)
#6      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:717:29)
<asynchronous suspension>
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:573:11)
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:923:27)
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:831:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZoned (dart:async/zone.dart:1550:10)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:820:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 1.22.0-10.0.pre.156, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.156 at C:\Users\Aneesh\Documents\GitHub\flutter
    • Framework revision 54495ff89e (2 hours ago), 2020-09-12 22:02:03 -0400
    • Engine revision 4a5e29ac64
    • Dart version 2.10.0 (build 2.10.0-119.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Aneesh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.0)
    • VS Code at C:\Users\Aneesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.41

• No issues found!

```
</details>

## Flutter Application Metadata
**Type**: null
**Version**: 0.0.1+5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-0.14.0+2
cloud_firestore_web-0.2.0+1
firebase_analytics-6.0.0
firebase_analytics_web-0.1.1
firebase_auth-0.18.0+1
firebase_auth_web-0.3.0+1
firebase_core-0.5.0
firebase_core_web-0.2.0
firebase_crashlytics-0.1.4+1
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1+1

**Comment by markusaksli-nc** [comment]
Hi @sidrao2006
I see there's an open issue addressing the case you described #65449.
Please follow up on that issue, since your stack is pretty much identical I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
