### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for D:\apps\flutter_app\android\gradlew.bat.

### ISSUE THREAD

**Issue by Hatem43** [flutter/flutter#65710]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for D:\apps\flutter_app\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:496:35)
#7      buildGradleApp (package:flutter_tools/src/android/gradle.dart:393:35)
#8      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:103:13)
#9      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:587:28)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.156, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.22.0-10.0.pre.156 at C:\src\flutter
    • Framework revision 54495ff89e (3 hours ago), 2020-09-12 22:02:03 -0400
    • Engine revision 4a5e29ac64
    • Dart version 2.10.0 (build 2.10.0-119.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\MENSHAWY\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 216dee60c0cc9449f0b29bcf922974d612263e24

**Comment by hamdikahloun** [comment]
Hi @Hatem43 

Duplicated issue https://github.com/flutter/flutter/issues/56975

**Comment by pedromassangocode** [comment]
Hi @Hatem43 
I see there's an open issue [here](https://github.com/flutter/flutter/issues/56975) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
