### ISSUE TITLE
run flutter project on my iPhone6 device Error

### ISSUE THREAD

**Issue by monkeyer** [flutter/flutter#65728]
This is project files: ... 
[bug_cant_run_on_myiphone_device.zip](https://github.com/flutter/flutter/files/5214944/bug_cant_run_on_myiphone_device.zip)

<details>
  <summary>Logs</summary>

```
sent 98810250 bytes  received 120 bytes  65873580.00 bytes/sec
               total size is 98797795  speedup is 1.00
               ♦ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip
               /Users/fan/Documents/works/flutter/githubio/flutter_ci_cd/ios/Flutter/Flutter.framework/Flutter -r -o
               /Users/fan/Documents/works/flutter/githubio/flutter_ci_cd/build/ios/Debug-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter
               ♦ codesign --force --verbose --sign 3FF40FFDEBCB12FD2283B14F82D07D964BD95D9C --
               /Users/fan/Documents/works/flutter/githubio/flutter_ci_cd/build/ios/Debug-iphoneos/Runner.app/Frameworks/App.framework/App
               /Users/fan/Documents/flutter/packages/flutter_tools/bin/xcode_backend.sh: line 9: 37301 Illegal instruction: 4  "$@"
               Command /bin/sh failed with exit code 132
           
           
[ +538 ms] Could not build the precompiled application for the device.
[  +29 ms] Error launching application on Fans iPhone.
[   +9 ms] "flutter run" took 49,776ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +368 ms] ensureAnalyticsSent: 235ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
> flutter analyze
Analyzing flutter_ci_cd...                                              
No issues found! (ran in 5.2s)
```

```
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.20.0 at /Users/fan/Documents/flutter
    • Framework revision 840c9205b3 (6 weeks ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/fan/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Fans iPhone (mobile) • 9b83b68e7b1b6f46d953a42277236538bdc66b02 • ios            • iOS 12.1.2
    • Web Server (web)     • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

</details>

xcode build info:

```
building file list ... done
App.framework/App
App.framework/flutter_assets/AssetManifest.json
App.framework/flutter_assets/FontManifest.json
App.framework/flutter_assets/NOTICES
App.framework/flutter_assets/kernel_blob.bin

sent 29849173 bytes  received 130 bytes  59698606.00 bytes/sec
total size is 34043111  speedup is 1.14
building file list ... done
Flutter.framework/
Flutter.framework/Flutter
Flutter.framework/Info.plist
Flutter.framework/icudtl.dat
Flutter.framework/_CodeSignature/
Flutter.framework/_CodeSignature/CodeResources

sent 98810250 bytes  received 120 bytes  65873580.00 bytes/sec
total size is 98797795  speedup is 1.00
/Users/fan/Documents/flutter/packages/flutter_tools/bin/xcode_backend.sh: line 9: 37963 Illegal instruction: 4  "$@"
Command /bin/sh failed with exit code 132
```

**Comment by monkeyer** [comment]
```
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.20.0 at /Users/fan/Documents/flutter
    • Framework revision 840c9205b3 (6 weeks ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/fan/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • Fans iPhone (mobile) • 9b83b68e7b1b6f46d953a42277281238bdc66b02 • ios            • iOS 12.1.2
    • Web Server (web)     • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

**Comment by monkeyer** [comment]
It works. 
```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -runFirstLaunch
```
