### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by dahmaular** [flutter/flutter#65850]
<details>
<summary>log</summary>

```
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
I/flutter ( 7300): _WidgetsAppState#3d26f](dirty, dependencies: [_EffectiveTickerMode, HeroControllerScope], state:
I/flutter ( 7300): NavigatorState#38847(tickers: tracking 0 tickers)):
I/flutter ( 7300): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4013 pos 12:
I/flutter ( 7300): '_history.isNotEmpty': is not true.
I/flutter ( 7300):
The relevant error-causing widget was:
I/flutter ( 7300):   MaterialApp
I/flutter ( 7300):   file:///C:/Users/user/Desktop/git_demo/ask_anything_gynaecology/lib/src/new/src/app.dart:26:20
I/flutter ( 7300):
I/flutter ( 7300): When the exception was thrown, this was the stack:
I/flutter ( 7300): #2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:4013:12)
I/flutter ( 7300): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
I/flutter ( 7300): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
I/flutter ( 7300): #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
       \I/flutter ( 7300): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #23     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #31     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #40     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #44     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #48     StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #52     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #56     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #61     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #67     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #72     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #76     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #77     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
I/flutter ( 7300): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #80     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #82     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #86     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #95     ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #100    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #104    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #105    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
I/flutter ( 7300): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #111    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #112    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
I/flutter ( 7300): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #115    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #120    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #125    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #127    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #131    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #135    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #140    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #142    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #143    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #145    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #146    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #147    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #148    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #151    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #152    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #153    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #156    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #157    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #160    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #161    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #162    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #165    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:397:11)     
I/flutter ( 7300): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #167    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #168    _InheritedProviderScopeElement.update (package:provider/src/inherited_provider.dart:417:11)
I/flutter ( 7300): #169    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #171    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #172    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #175    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #176    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #179    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #180    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #181    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #182    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #186    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #187    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #188    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #190    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #193    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #194    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #195    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #197    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #198    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #199    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #200    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #201    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #202    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #204    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #205    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #207    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #208    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #211    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #212    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #213    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #214    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #215    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #216    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #218    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #219    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #220    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
I/flutter ( 7300): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #222    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #223    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #225    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #226    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #227    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #228    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #229    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #230    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #231    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #232    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #234    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #235    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #236    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
I/flutter ( 7300): #237    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #238    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #239    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #240    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
I/flutter ( 7300): #241    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #242    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
I/flutter ( 7300): #243    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #245    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #246    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
I/flutter ( 7300): #247    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter ( 7300): #248    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter ( 7300): #249    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter ( 7300): #250    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter ( 7300): #251    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
I/flutter ( 7300): #252    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
I/flutter ( 7300): #253    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)       
I/flutter ( 7300): #254    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1115:15)
I/flutter ( 7300): #255    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1054:9)
I/flutter ( 7300): #256    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
```

</details>

**Comment by darshankawar** [comment]
@dahmaular,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.
