### ISSUE TITLE
Segfault in ui_unittests ImageDecoderFixtureTest.ValidImageResultsInSuccess

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#65913]
## Description

I've seen this flake a couple times, most recently in the host_release build on our Linux Host Engine builder. I don't recall whether I've seen it on other platforms/modes as well.

## Logs
Build: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Host%20Engine/6839
Logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8869029216637469536/+/steps/Host_Tests_for_host_release/0/stdout

```
[----------] 4 tests from ShellTest
[ RUN      ] ShellTest.PlatformConfigurationWindowMetricsUpdate
[       OK ] ShellTest.PlatformConfigurationWindowMetricsUpdate (33 ms)
[ RUN      ] ShellTest.EncodeImageGivesExternalTypedData
[       OK ] ShellTest.EncodeImageGivesExternalTypedData (21 ms)
[ RUN      ] ShellTest.VerticesAccuratelyReportsSize
[       OK ] ShellTest.VerticesAccuratelyReportsSize (23 ms)
[ RUN      ] ShellTest.PlatformConfigurationInitialization
[       OK ] ShellTest.PlatformConfigurationInitialization (21 ms)
[----------] 4 tests from ShellTest (99 ms total)

[----------] 8 tests from ImageDecoderFixtureTest
[ RUN      ] ImageDecoderFixtureTest.ValidImageResultsInSuccess


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 498, in <module>
    sys.exit(main())
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 468, in main
    RunCCTests(build_dir, engine_filter)
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 143, in RunCCTests
    RunEngineExecutable(build_dir, 'ui_unittests', filter, shuffle_flags + ['--timeout=90'])
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 94, in RunEngineExecutable
    RunCmd(test_command, cwd=cwd)
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 47, in RunCmd
    raise Exception('Command "%s" exited with code %d' % (command_string, process.returncode))
Exception: Command "/b/s/w/ir/cache/builder/src/out/host_release/ui_unittests --gtest_shuffle --gtest_repeat=2 --timeout=90" exited with code -11
```

**Comment by cbracken** [comment]
Closing as dupe of #64475.
