### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/mac/development/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.

### ISSUE THREAD

**Issue by ihsh** [flutter/flutter#65924]
## Command
```
flutter assemble --output=/Users/mac/flutter_dapp_ltl/.ios/Flutter/ -dTargetPlatform=ios -dTargetFile=/Users/mac/flutter_dapp_ltl/lib/main.dart -dBuildMode=release -dIosArchs=x86_64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --DartDefines=flutter.inspector.structuredErrors=true -dExtraFrontEndOptions= release_ios_bundle_flutter_assets
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/mac/development/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_x86_64.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:69:31)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
#12     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/mac/development/flutter
    • Framework revision e6b34c2b5c (5 months ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • sdk gphone x86 arm • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 11          • 50B2D250-5DAE-4B4B-B6BA-0AE1B9B0540B • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.lalamove.huolala.driver.dappflutter
**iOS bundle identifier**: com.lalamove.huolala.driver.dappflutter
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe
### Plugins
flutter_boost-6867d8b6336cc3f12e64612eb0d5ea998e8acf53
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
sqflite-1.3.1

**Comment by darshankawar** [comment]
Hi @ihsh,
Please see [this](https://github.com/flutter/flutter/issues/57929) related issue. You seem to be on old version of Flutter. I'd suggest you to upgrade to latest stable or master and try again. This issue was [fixed](https://github.com/flutter/flutter/pull/57874) and merged.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
