### ISSUE TITLE
[Flutter doctor] crash on connected devices when web support is enabled running on WSL, FormatException: Missing extension byte

### ISSUE THREAD

**Issue by Fchacha** [flutter/flutter#65932]
Hi, I need to work on a web app, howerver flutter crashes during flutter doctor at the connected device steps.

I work on Wsl - Debian.
Chrome installed on Windows 10

## Steps to Reproduce

1. install flutter following every step for linux starting from: git clone https://github.com/flutter/flutter.git
2. export PATH="$PATH:`pwd`/flutter/bin" in .zshrc
3. flutter precache
4. flutter doctor

5. follow the web tutorial: https://flutter.dev/docs/get-started/web
6. flutter channel beta
7. flutter upgrade
8. flutter config --enable-web
9. flutter doctor

## Logs

$> flutter doctor -v ( before $> flutter config --enable-web )
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.200, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.200 at /home/fchavagnieux/Teknos/flutter
    • Framework revision 25b8c095cd (5 hours ago), 2020-09-16 01:27:03 -0400
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /mnt/c/Users/flori/AppData/Local/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /mnt/c/Users/flori/AppData/Local/Android/Sdk/
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

$> flutter doctor -v ( after $> flutter config --enable-web )
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.200, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.200 at /home/fchavagnieux/Teknos/flutter
    • Framework revision 25b8c095cd (5 hours ago), 2020-09-16 01:27:03 -0400
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /mnt/c/Users/flori/AppData/Local/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /mnt/c/Users/flori/AppData/Local/Android/Sdk/
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 87)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1887:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
      #5      _rootRunUnary (dart:async/zone.dart:1198:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:682:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:624:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2150:41)
      #14     _rootRunUnary (dart:async/zone.dart:1206:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:682:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:624:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1686:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1182:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 3 categories.
```

I have no issues running mobile apps when web service is not enabled.

**Comment by darshankawar** [comment]
Hi @Fchacha,
What happens if you run `flutter devices` ? Can you share output of it ?
Thanks.

**Comment by Fchacha** [comment]
it oppens 2 instances of chrome on default window

$> flutter devices
```
2 connected devices:


Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 87)".
A crash report has been written to /mnt/c/Users/flori/flutter_04.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FormatException%3A+Missing+extension+byte+%28at+offset+87%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JUBQ1
```
---

and the log:

## command

flutter devices

## exception

FormatException: FormatException: Missing extension byte (at offset 87)

```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1887:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#11     _StreamController._add (dart:async/stream_controller.dart:682:7)
#12     _StreamController.add (dart:async/stream_controller.dart:624:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2150:41)
#14     _rootRunUnary (dart:async/zone.dart:1206:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#20     _StreamController._add (dart:async/stream_controller.dart:682:7)
#21     _StreamController.add (dart:async/stream_controller.dart:624:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1686:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1182:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.200, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.200 at /home/fchavagnieux/Teknos/flutter
    • Framework revision 25b8c095cd (8 hours ago), 2020-09-16 01:27:03 -0400
    • Engine revision 1ef10b240e
    • Dart version 2.10.0 (build 2.10.0-124.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /mnt/c/Users/flori/AppData/Local/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /mnt/c/Users/flori/AppData/Local/Android/Sdk/
    ✗ Android SDK file not found: adb.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 88)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1887:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
      #5      _rootRunUnary (dart:async/zone.dart:1198:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:682:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:624:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2150:41)
      #14     _rootRunUnary (dart:async/zone.dart:1206:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:682:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:624:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1686:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1182:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 3 categories.
```

Thanks for helping.

**Comment by jonahwilliams** [comment]
The contents of flutter_04 should have more of the stacktrace too

**Comment by Fchacha** [comment]
Sadly this is the full content of flutter_04

**Comment by jonahwilliams** [comment]
No worries, thanks @Fchacha !

**Comment by jonahwilliams** [comment]
Does this happen only if web is enabled? that would help us narrow it down to one of the web devices

**Comment by Fchacha** [comment]
When I disable web with $>flutter config --no-enable-web
flutter doctor and device don't crash. 
I just get no device connected, since I didn't connect any device.

**Comment by GiacomoZheng** [comment]
I have nearly the same problem with the error: `Unexpected extension byte (at offset 84)` with
`Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale en_US.UTF-8)` on WSL - Debian and chrome.exe on win 10.

If I don't set the env `CHROME_EXECUTABLE` the system cannot find the chrome but as long as I set it, the error would occur.

**Comment by kknddandy** [comment]
same issue, I just changed the system language from Chinese to English and the problem is still there.

**Comment by kknddandy** [comment]
I just found a walkaround to let me debug web through WSL. 

1. remove chrome path
2. in vs code, choose webserver (web-javascript) mode. 

so you don't need flutter to open chrome, the host windows will open it, and connect to the web-server which runs in your WSL.

**Comment by marciojg** [comment]
@kknddandy it worked for me

thanks

**Comment by alectogeek** [comment]
Same here on Master branch on Mac


## command

flutter build ios --bundle-sksl-path flutter_02.sksl.json

## exception

FormatException: FormatException: Missing extension byte (at offset 14)

```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1892:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1362:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#14     _rootRunUnary (dart:async/zone.dart:1370:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#20     _StreamController._add (dart:async/stream_controller.dart:607:7)
#21     _StreamController.add (dart:async/stream_controller.dart:554:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.180, on macOS 11.2.3 20D91 darwin-x64, locale en-DE)
    • Flutter version 2.2.0-11.0.pre.180 at /Users/alectogeek/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71cb40f46a (3 hours ago), 2021-04-20 14:19:02 -0400
    • Engine revision 79c5ebe835
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/alectogeek/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Starlink (mobile)  • 00008030-00114DE60CD9802E            • ios • iOS 14.4.2
    • iPhone 11 (mobile) • 9C29A4E2-67A2-4A79-9454-6E6F5690F1C9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    ! Error: Starlink is not connected. Xcode will continue when Starlink is connected. (code -13)

• No issues found!
```

**Comment by tenhobi** [comment]
I have the same issue in WSL2 with web flutter, see below. I am setting the `CHROME_EXECUTABLE` to `'/mnt/c/Program Files/Google/Chrome/Application/chrome.exe'`. When I try to run `flutter run -d chrome`, `flutter doctor` or `flutter devices`, it instantly opens a new Chrome tab (empty), the terminal doesn't print anything and waits until I close the tab, then it completes with the error (`Oops; flutter has exited unexpectedly: "FormatException: Missing extension byte (at offset 5)".`). When I ran `flutter clean`, it suddenly stopped giving this error but still doesn't work.

When I close the tab, it tries to complete the `flutter run -d chrome` and after a while (15 s) it gives me this alert: 
![image](https://user-images.githubusercontent.com/5287596/122125838-38682200-ce31-11eb-82a5-d4c77bfc2eb9.png)

Whole log:

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run -d chrome

## exception

FormatException: FormatException: Missing extension byte (at offset 5)

```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1892:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1436:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2165:41)
#14     _rootRunUnary (dart:async/zone.dart:1444:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#20     _StreamController._add (dart:async/stream_controller.dart:607:7)
#21     _StreamController.add (dart:async/stream_controller.dart:554:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1701:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.372, on Ubuntu 20.04.2 LTS 4.19.128-microsoft-standard, locale C.UTF-8)
    • Flutter version 2.3.0-17.0.pre.372 at /home/tenhobi/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a2336e9ac7 (2 hours ago), 2021-06-15 14:59:04 -0400
    • Engine revision e0011fa561
    • Dart version 2.14.0 (build 2.14.0-211.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /mnt/c/Program Files/Google/Chrome/Application/chrome.exe

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Missing extension byte (at offset 5)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1892:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1436:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:607:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:554:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2165:41)
      #14     _rootRunUnary (dart:async/zone.dart:1444:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:607:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:554:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1701:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
      #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


! Doctor found issues in 3 categories.
```

**Comment by mdebbar** [comment]
Can someone confirm if this is still an issue that we need to keep open?
