### ISSUE TITLE
crash on emulator when running demo app from MDC-102 codelab

### ISSUE THREAD

**Issue by heroqin** [flutter/flutter#65989]
crash happened when I rolled down and rolled back contents in APP for several times。

<details>
<summary>log</summary>

```
Reload already in progress, ignoring request
Restarted application in 1,525ms.
W/mdc_101_flutte( 4352): Reducing the number of considered missed Gc histogram windows from 3047 to 100

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during paint():[39;49m
'package:flutter/src/rendering/sliver_padding.dart': Failed assertion: line 299 pos 18: 'innerRect.bottom <= outerRect.bottom': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mGridView[39;49m 
 lib\home.dart
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      RenderSliverEdgeInsetsPadding.debugPaint.<anonymous closure>[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#3      RenderSliverEdgeInsetsPadding.debugPaint[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#4      RenderObject._paintWithContext.<anonymous closure>[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#5      RenderObject._paintWithContext[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#6      PaintingContext.paintChild[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: RenderViewport#aafe2[39;49m
[38;5;244mRenderObject: RenderViewport#aafe2[39;49m
    [38;5;244mneeds compositing[39;49m
    [38;5;244mparentData: <none> (can use size)[39;49m
    [38;5;244mconstraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=603.4)[39;49m
    [38;5;244mlayer: OffsetLayer#b8020[39;49m
        [38;5;244mengine layer: OffsetEngineLayer#92a70[39;49m
        [38;5;244moffset: Offset(0.0, 0.0)[39;49m
    [38;5;244msize: Size(411.4, 603.4)[39;49m
    [38;5;244maxisDirection: down[39;49m
    [38;5;244mcrossAxisDirection: right[39;49m
    [38;5;244moffset: ScrollPositionWithSingleContext#c08bb(offset: 0.8, range: 0.0..495.7, viewport: 603.4, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, DragScrollActivity#9661a(ScrollDragController#3bab4), ScrollDirection.reverse)[39;49m
    [38;5;244manchor: 0.0[39;49m
    [38;5;244mcenter child: RenderSliverPadding#2a515 relayoutBoundary=up1[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: paintOffset=Offset(0.0, 0.0) (can use size)[39;49m
        [38;5;244mconstraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse, scrollOffset: 0.8, remainingPaintExtent: 603.4, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 854.3, cacheOrigin: -0.8)[39;49m
        [38;5;244mgeometry: SliverGeometry(scrollExtent: 1099.1, paintExtent: 603.4, maxPaintExtent: 1099.1, hitTestExtent: 603.4, hasVisualOverflow: true, cacheExtent: 854.3)[39;49m
            [38;5;244mscrollExtent: 1099.1[39;49m
            [38;5;244mpaintExtent: 603.4[39;49m
            [38;5;244mmaxPaintExtent: 1099.1[39;49m
            [38;5;244mhitTestExtent: 603.4[39;49m
            [38;5;244mhasVisualOverflow: true[39;49m
            [38;5;244mcacheExtent: 854.3[39;49m
        [38;5;244mpadding: EdgeInsets.all(16.0)[39;49m
        [38;5;244mtextDirection: ltr[39;49m
        [38;5;244mchild: RenderSliverGrid#121b6 relayoutBoundary=up2[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: paintOffset=Offset(16.0, 15.2) (can use size)[39;49m
            [38;5;244mconstraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse, scrollOffset: 0.0, remainingPaintExtent: 588.3, crossAxisExtent: 379.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 603.4, remainingCacheExtent: 838.3, cacheOrigin: 0.0)[39;49m
            [38;5;244mgeometry: SliverGeometry(scrollExtent: 1067.1, paintExtent: 588.3, maxPaintExtent: 1067.1, hasVisualOverflow: true, cacheExtent: 838.3)[39;49m
                [38;5;244mscrollExtent: 1067.1[39;49m
                [38;5;244mpaintExtent: 588.3[39;49m
                [38;5;244mmaxPaintExtent: 1067.1[39;49m
                [38;5;244mhasVisualOverflow: true[39;49m
                [38;5;244mcacheExtent: 838.3[39;49m
            [38;5;244mcurrently live children: 0 to 7[39;49m
            [38;5;244mchild with index 0: RenderIndexedSemantics#c1495[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: crossAxisOffset=0.0; index=0; layoutOffset=0.0[39;49m
                [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(189.7, 213.4)[39;49m
                [38;5;244mindex: 0[39;49m
                [38;5;244mchild: RenderRepaintBoundary#1765c[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                    [38;5;244mlayer: OffsetLayer#d1b62[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#8de72[39;49m
                        [38;5;244moffset: Offset(16.0, 15.2)[39;49m
                    [38;5;244msize: Size(189.7, 213.4)[39;49m
                    [38;5;244mmetrics: 96.0% useful (1 bad vs 24 good)[39;49m
                    [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild with index 1: RenderIndexedSemantics#b34fc[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: crossAxisOffset=189.71428571428572; index=1; layoutOffset=0.0[39;49m
                [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(189.7, 213.4)[39;49m
                [38;5;244mindex: 1[39;49m
                [38;5;244mchild: RenderRepaintBoundary#23bab[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                    [38;5;244mlayer: OffsetLayer#dae3d[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#fb78b[39;49m
                        [38;5;244moffset: Offset(205.7, 15.2)[39;49m
                    [38;5;244msize: Size(189.7, 213.4)[39;49m
                    [38;5;244mmetrics: 96.0% useful (1 bad vs 24 good)[39;49m
                    [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild with index 2: RenderIndexedSemantics#32b32[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: crossAxisOffset=0.0; index=2; layoutOffset=213.4[39;49m
                [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(189.7, 213.4)[39;49m
                [38;5;244mindex: 2[39;49m
                [38;5;244mchild: RenderRepaintBoundary#addc9[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                    [38;5;244mlayer: OffsetLayer#196a3[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#ee3c9[39;49m
                        [38;5;244moffset: Offset(16.0, 228.6)[39;49m
                    [38;5;244msize: Size(189.7, 213.4)[39;49m
                    [38;5;244mmetrics: 98.9% useful (1 bad vs 93 good)[39;49m
                    [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild with index 3: RenderIndexedSemantics#68834[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: crossAxisOffset=189.71428571428572; index=3; layoutOffset=213.4[39;49m
                [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(189.7, 213.4)[39;49m
                [38;5;244mindex: 3[39;49m
                [38;5;244mchild: RenderRepaintBoundary#bbdf9[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                    [38;5;244mlayer: OffsetLayer#a39d0[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#9cfa0[39;49m
                        [38;5;244moffset: Offset(205.7, 228.6)[39;49m
                    [38;5;244msize: Size(189.7, 213.4)[39;49m
                    [38;5;244mmetrics: 98.9% useful (1 bad vs 93 good)[39;49m
                    [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild with index 4: RenderIndexedSemantics#1c7c7[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: crossAxisOffset=0.0; index=4; layoutOffset=426.9[39;49m
                [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(189.7, 213.4)[39;49m
                [38;5;244mindex: 4[39;49m
                [38;5;244mchild: RenderRepaintBoundary#8ce76[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                    [38;5;244mlayer: OffsetLayer#5e531[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#3dde9[39;49m
                        [38;5;244moffset: Offset(16.0, 442.0)[39;49m
                    [38;5;244msize: Size(189.7, 213.4)[39;49m
                    [38;5;244mmetrics: 99.0% useful (1 bad vs 98 good)[39;49m
                    [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild with index 5: RenderIndexedSemantics#91a01[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: crossAxisOffset=189.71428571428572; index=5; layoutOffset=426.9[39;49m
                [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(189.7, 213.4)[39;49m
                [38;5;244mindex: 5[39;49m
                [38;5;244mchild: RenderRepaintBoundary#38af9[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                    [38;5;244mlayer: OffsetLayer#8b746[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#0dd9d[39;49m
                        [38;5;244moffset: Offset(205.7, 442.0)[39;49m
                    [38;5;244msize: Size(189.7, 213.4)[39;49m
                    [38;5;244mmetrics: 99.0% useful (1 bad vs 98 good)[39;49m
                    [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild with index 6: RenderIndexedSemantics#50929[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: crossAxisOffset=0.0; index=6; layoutOffset=640.3[39;49m
                [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(189.7, 213.4)[39;49m
                [38;5;244mindex: 6[39;49m
                [38;5;244mchild: RenderRepaintBoundary#a4410[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                    [38;5;244mlayer: OffsetLayer#35f29 DETACHED[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#ebd9e[39;49m
                        [38;5;244moffset: Offset(16.0, 583.6)[39;49m
                    [38;5;244msize: Size(189.7, 213.4)[39;49m
                    [38;5;244mmetrics: 98.8% useful (1 bad vs 84 good)[39;49m
                    [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild with index 7: RenderIndexedSemantics#66a07[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: crossAxisOffset=189.71428571428572; index=7; layoutOffset=640.3[39;49m
                [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(189.7, 213.4)[39;49m
                [38;5;244mindex: 7[39;49m
                [38;5;244mchild: RenderRepaintBoundary#713fc[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=189.7, h=213.4)[39;49m
                    [38;5;244mlayer: OffsetLayer#1777b DETACHED[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#0806d[39;49m
                        [38;5;244moffset: Offset(205.7, 583.6)[39;49m
                    [38;5;244msize: Size(189.7, 213.4)[39;49m
                    [38;5;244mmetrics: 98.8% useful (1 bad vs 84 good)[39;49m
                    [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:flutter/src/rendering/sliver_padding.dart': Failed assertion: line 299 pos 18:
'innerRect.bottom <= outerRect.bottom': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
The relevant error-causing widget was:
  GridView
[38;5;248m  [39;49m
 lib\home.dart
When the exception was thrown, this was the stack:
[38;5;244m#2      RenderSliverEdgeInsetsPadding.debugPaint.<anonymous closure>[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#3      RenderSliverEdgeInsetsPadding.debugPaint[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#4      RenderObject._paintWithContext.<anonymous closure>[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#5      RenderObject._paintWithContext[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#6      PaintingContext.paintChild[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#7      RenderViewportBase._paintContents[39;49m 
 package:flutter/…/rendering/viewport.dart
[38;5;244m#8      PaintingContext.pushLayer[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#9      PaintingContext.pushClipRect[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#10     RenderViewportBase.paint[39;49m 
 package:flutter/…/rendering/viewport.dart
[38;5;244m#11     RenderObject._paintWithContext[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#12     PaintingContext._repaintCompositedChild[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#13     PaintingContext.repaintCompositedChild[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#14     PipelineOwner.flushPaint[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#15     RendererBinding.drawFrame[39;49m 
 package:flutter/…/rendering/binding.dart
[38;5;244m#16     WidgetsBinding.drawFrame[39;49m 
 package:flutter/…/widgets/binding.dart
[38;5;244m#17     RendererBinding._handlePersistentFrameCallback[39;49m 
 package:flutter/…/rendering/binding.dart
[38;5;244m#18     SchedulerBinding._invokeFrameCallback[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#19     SchedulerBinding.handleDrawFrame[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#20     SchedulerBinding._handleDrawFrame[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#24     _invoke  (dart:ui/hooks.dart:253:10)[39;49m
[38;5;244m#25     _drawFrame  (dart:ui/hooks.dart:211:3)[39;49m
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderViewport#aafe2:
  needs compositing
  creator: Viewport ← IgnorePointer-[GlobalKey#6c143] ← Semantics ← _PointerListener ← Listener ←
    _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#31eda] ←
    _PointerListener ← Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#dab8e] ←
    RepaintBoundary ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=603.4)
  layer: OffsetLayer#b8020
  size: Size(411.4, 603.4)
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#c08bb(offset: 0.8, range: 0.0..495.7, viewport: 603.4,
    ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics ->
    RangeMaintainingScrollPhysics, DragScrollActivity#9661a(ScrollDragController#3bab4),
    ScrollDirection.reverse)
  anchor: 0.0
This RenderObject had the following descendants (showing up to depth 5):
    center child: RenderSliverPadding#2a515 relayoutBoundary=up1
      child: RenderSliverGrid#121b6 relayoutBoundary=up2
        child with index 0: RenderIndexedSemantics#c1495
          child: RenderRepaintBoundary#1765c
            child: RenderSemanticsAnnotations#4893d
        child with index 1: RenderIndexedSemantics#b34fc
          child: RenderRepaintBoundary#23bab
            child: RenderSemanticsAnnotations#483a1
        child with index 2: RenderIndexedSemantics#32b32
          child: RenderRepaintBoundary#addc9
            child: RenderSemanticsAnnotations#9824d
        child with index 3: RenderIndexedSemantics#68834
          child: RenderRepaintBoundary#bbdf9
            child: RenderSemanticsAnnotations#c43d4
        child with index 4: RenderIndexedSemantics#1c7c7
          child: RenderRepaintBoundary#8ce76
            child: RenderSemanticsAnnotations#2b84f
        child with index 5: RenderIndexedSemantics#91a01
          child: RenderRepaintBoundary#38af9
            child: RenderSemanticsAnnotations#7ad4a
        child with index 6: RenderIndexedSemantics#50929
          child: RenderRepaintBoundary#a4410
            child: RenderSemanticsAnnotations#5c1e8
        child with index 7: RenderIndexedSemantics#66a07
          child: RenderRepaintBoundary#713fc
            child: RenderSemanticsAnnotations#a7e6f
════════════════════════════════════════════════════════════════════════════════════════════════════
F/libc    ( 4352): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18 in tid 4380 (1.ui), pid 4352 (mdc_101_flutter)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/sdk_phone_x86_64/generic_x86_64:10/QPP6.190730.005.B1/5775370:userdebug/test-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2020-09-17 03:28:12+0000
pid: 4352, tid: 4380, name: 1.ui  >>> com.example.mdc_101_flutter <<<
uid: 10103
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
Cause: null pointer dereference
    rax 000079fc3f95f800  rbx 0000000000000000  rcx 000079fbf22864b8  rdx 0000000000000000
    r8  000079fbf3680bc2  r9  0000000000000003  r10 0000000001000005  r11 000079fbf0d80061
    r12 000079fbf3e26888  r13 000079fbda9ed168  r14 000079fc3f95f800  r15 000079fbf3680bc2
    rdi 000079fc3f95f800  rsi 0000000000000000
    rbp 0000000000000000  rsp 000079fbf22863e0  rip 000079fbf3680be7
backtrace:
      #00 pc 00000000012eabe7  /data/app/com.example.mdc_101_flutter-OkyR6q7cIjPNwzxRzwBsrw==/lib/x86_64/libflutter.so (BuildId: 8d7059558a6faf42b5a51608ea115b8c7532885b)
      #01 pc 00000000000f544f  <anonymous:79fbf2191000>
Lost connection to device.
Exited (sigterm)
```

</details>

**Comment by darshankawar** [comment]
Hi @heroqin,
Can you please translate the codelab in English ?
Which one among the following are you looking at ?

https://codelabs.developers.google.com/codelabs/mdc-101-flutter/#0
https://codelabs.developers.google.com/codelabs/mdc-102-flutter/#0

Also, provide `flutter doctor -v`.
Thanks.

**Comment by heroqin** [comment]
Hi @darshankawar,
This one: https://codelabs.developers.google.com/codelabs/mdc-102-flutter/#5
 when I rolled down and rolled back APP contents for several times, APP crashed.

device which I got crash is an android emualtor:
Nexus_6_API_29.avd 
AvdId=Nexus_6_API_29
PlayStore.enabled=false
abi.type=x86_64
avd.ini.displayname=Nexus 6 API 29
avd.ini.encoding=UTF-8

C:\Users\lixs>flutter doctor -v
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 6.1.7601],
    locale zh-CN)
    • Flutter version 1.20.3 at C:\flutter
    • Framework revision 216dee60c0 (2 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)

    • Android SDK at C:\Users\lixs\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\lixs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 •
      Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

C:\Users\lixs>

**Comment by darshankawar** [comment]
Hi @heroqin,
I tried all the steps mentioned in the said codelab on Android device (8.1.0) on latest master, but didn't see the crash. I scrolled down and up the content several times and saw no issues.

[65989.mp4.zip](https://github.com/flutter/flutter/files/5239600/65989.mp4.zip)

Can you try that on a physical device and see if you get the same crash there ?
Thanks.

**Comment by heroqin** [comment]
Hi @darshankawar,
  when I tried it on my MI phone, I didn't see the crash. So it seems it only happen on my virtual device.

Thanks.

**Comment by darshankawar** [comment]
@heroqin thanks for confirming. Since it's only happening on emulator and not on physical device as we noticed, I am going ahead and closing it, since it doesn't seem to be related to Flutter. 
If you again see the same crash on a physical device, feel free to open a new issue mentioning all required details. If you disagree, write in comments and I'll reopen this ticket.
Thanks.
