### ISSUE TITLE
Cannot build flutter app for iOS

### ISSUE THREAD

**Issue by ikarelin** [flutter/flutter#66000]
## Steps to Reproduce

1. Run `flutter clean'.
2. Run 'flutter build iOS --release'

**Expected results:**

Application builded

**Actual results:** 

flutter build ios --release
Changing current working directory to: /Users/ikarelin/Documents/Flutter/commex
Running "flutter pub get" in commex...                              1.2s
 
Building com.appsfactories.commex for device (ios-release)...
Signing iOS app for device deployment using developer identity: "Apple Development: Svetlana Epikhina (C6Q7ZHSY87)"
Running pod install...                                             28.6s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           68.2s

<details>
<summary>log</summary>

```
Oops; flutter has exited unexpectedly: "ProcessException: Process timed out:

  Command: /usr/bin/env xcrun xcodebuild -configuration Release -quiet DEVELOPMENT_TEAM=5CQMRZJ3CD -workspace Runner.xcworkspace -scheme Runner
  BUILD_DIR=/Users/ikarelin/Documents/Flutter/commex/build/ios -sdk iphoneos
  SCRIPT_OUTPUT_STREAM_FILE=/var/folders/ny/0rfdddk125x8hmvycdf4330r0000gn/T/flutter_tools.mI0spN/flutter_build_log_pipe.lBDPu0/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true
  COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings".
 
A crash report has been written to /Users/ikarelin/Documents/Flutter/commex/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+Process+timed+out%3A%0A%0A++Command%3A+%2Fusr%2Fbin%2Fenv+xcrun+xcodebuild+-configuration+Release+-quiet+DEVELOPMENT_TEAM%3D5CQMRZJ3CD+-workspace+Runner.xcworkspace+-scheme+Runner+BUILD_DIR%3D%2FUsers%2Fikarelin%2FDocuments%2FFlutter%2Fcommex%2Fbuild%2Fios+-sdk+iphoneos+SCRIPT_OUTPUT_STREAM_FILE%3D%2Fvar%2Ffolders%2Fny%2F0rfdddk125x8hmvycdf4330r0000gn%2FT%2Fflutter_tools.mI0spN%2Fflutter_build_log_pipe.lBDPu0%2Fpipe_to_stdout+FLUTTER_SUPPRESS_ANALYTICS%3Dtrue+COMPILER_INDEX_STORE_ENABLE%3DNO+-showBuildSettings

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JUR4L


/Users/ikarelin/Documents/Flutter/commex/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Views/TOCropView.h (in target
                        'TOCropViewController' from project 'Pods')
                        warning: Skipping duplicate build file in Copy Headers build phase:

/Users/ikarelin/Documents/Flutter/commex/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/TOCropViewController.h (in
                        target 'TOCropViewController' from project 'Pods')
                        warning: Skipping duplicate build file in Copy Headers build phase:

/Users/ikarelin/Documents/Flutter/commex/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Models/TOCropViewControllerTrans
                        itioning.h (in target 'TOCropViewController' from project 'Pods')
                    
[ +697 ms] Could not build the application for the simulator.
[   +6 ms] Error launching application on iPhone 11 Pro Max.
[   +8 ms] "flutter run" took 113,693ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +120 ms] ensureAnalyticsSent: 118ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

flutter analyse

```
flutter analyze
Analyzing commex...                                                     

   info • The value of the field '_deviceHeight' isn't used • lib/pages/invite_user_page.dart:18:10 • unused_field
   info • Cancel instances of dart.async.StreamSubscription • lib/pages/main_page.dart:33:22 • cancel_subscriptions
   info • The value of the field '_deviceHeight' isn't used • lib/pages/new_contact_page.dart:23:10 • unused_field
   info • The value of the field '_initialized' isn't used • lib/pages/splash_screen.dart:18:8 • unused_field
   info • The value of the field '_error' isn't used • lib/pages/splash_screen.dart:19:8 • unused_field
   info • Use valid regular expression syntax • lib/services/contact_service.dart:43:62 • valid_regexps
   info • Use valid regular expression syntax • lib/services/contact_service.dart:44:59 • valid_regexps
   info • Unused import: 'package:flutter/material.dart' • lib/services/fb_service.dart:6:8 • unused_import

8 issues found. (ran in 5.5s)
```

```
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /Users/ikarelin/Developer/flutter
    • Framework revision fba99f6cf9 (2 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ikarelin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • B78A8DB1-FE50-4D81-BD07-8201765BD0F9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
```

```
```

</details>

**Comment by darshankawar** [comment]
Hi @ikarelin,
I am able to build a `release` build without any issues. I am latest master.

```
dhs@Dhss-MacBook-Pro newdemo % flutter build ios
Running "flutter pub get" in newdemo...                             1.4s
Building com.example.newdemo for device (ios-release)...
Signing iOS app for device deployment using developer identity: "Apple Development: Darshan Kawar (HJWLFNL782)"
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        15.4s
Xcode build done.                                           46.2s
Built /Users/dhs/Documents/NCFlutter/newdemo/build/ios/iphoneos/Runner.app.

```

`flutter build ios` is same as `flutter build ios --release`, as the first command defaults to release mode.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.221, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.22.0-10.0.pre.221 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision fa646339d6 (8 hours ago), 2020-09-16 17:47:04 -0700
    • Engine revision 933f811d94
    • Dart version 2.10.0 (build 2.10.0-135.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM G975F (mobile)                   • RZ8M802WY0X
      • android-arm64  • Android 10 (API 29)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

</details>

Can you share the crash log `A crash report has been written to /Users/ikarelin/Documents/Flutter/commex/flutter_01.log`

**Comment by ikarelin** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios --release

## exception

ProcessException: ProcessException: Process timed out:

  Command: /usr/bin/env xcrun xcodebuild -configuration Release -quiet DEVELOPMENT_TEAM=5CQMRZJ3CD -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/ikarelin/Documents/Flutter/commex/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/ny/0rfdddk125x8hmvycdf4330r0000gn/T/flutter_tools.mI0spN/flutter_build_log_pipe.lBDPu0/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:394:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:358:66)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#11     _runBuildWithRetries (package:flutter_tools/src/ios/mac.dart)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#27     Future.wait.<anonymous closure> (dart:async/future.dart:410:22)
#28     _rootRunUnary (dart:async/zone.dart:1198:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#33     Future._complete (dart:async/future_impl.dart:519:7)
#34     Stream.fold.<anonymous closure> (dart:async/stream.dart:847:14)
#35     _rootRun (dart:async/zone.dart:1182:47)
#36     _CustomZone.run (dart:async/zone.dart:1093:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#38     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#39     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#40     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#41     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
#42     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#43     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#44     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#45     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#46     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
#47     _rootRun (dart:async/zone.dart:1182:47)
#48     _CustomZone.run (dart:async/zone.dart:1093:19)
#49     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#50     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#51     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#52     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#53     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
#54     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
#55     _StreamController.close (dart:async/stream_controller.dart:664:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:2027:21)
#57     _rootRunUnary (dart:async/zone.dart:1206:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#62     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#63     _StreamController._add (dart:async/stream_controller.dart:682:7)
#64     _StreamController.add (dart:async/stream_controller.dart:624:5)
#65     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1563:35)
#66     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1045:18)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#69     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /Users/ikarelin/Developer/flutter
    • Framework revision fba99f6cf9 (2 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ikarelin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • B78A8DB1-FE50-4D81-BD07-8201765BD0F9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
```

**Comment by darshankawar** [comment]
@ikarelin thanks for the log.
There's similar open issue describing your case, [47633](https://github.com/flutter/flutter/issues/47633).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
