### ISSUE TITLE
Test always returning passed.....when using @TestOn('browser')

### ISSUE THREAD

**Issue by wer-mathurin** [flutter/flutter#66045]
## Steps to Reproduce
@TestOn('browser')
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('I must failed', () async {
    expect(1, 2);
  });
}

I'm expecting the code to failed....but for some reason, when using the @TestOn('browser') it didn't.
The above code return passed !!!!!!!

**_flutter-doctor_**
[√] Flutter (Channel beta, 1.22.0-12.1.pre, on Microsoft Windows [version 10.0.18363.1016], locale fr-CA)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.0)
[√] Connected device (4 available)

<details>

flutter test -v
[  +97 ms] executing: [C:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8b3760638a189741cd9ca881aa2dd237c1df1be5
[        ] executing: [C:\dev\flutter/] git tag --points-at HEAD
[  +49 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.0-12.1.pre
[  +11 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\dev\flutter/] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +62 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +51 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[  +17 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +32 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[  +28 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +40 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +5 ms] Changing current working directory to: C:\dev\git\flutter-webrtc
[ +113 ms] switching to directory LocalDirectory: 'test' to run tests
[   +1 ms] running test package with arguments: [-r, compact, --concurrency=10, --,
C:\dev\git\flutter-webrtc\test\unit\rct_peerconnection_test.dart, C:\dev\git\flutter-webrtc\test\unit\web\rtc_videw_view_test.dart]
00:00 +0: loading C:\dev\git\flutter-webrtc\test\unit\rct_peerconnection_test.dart                                                             [ +222 ms] test 0: starting test C:\dev\git\flutter-webrtc\test\unit\rct_peerconnection_test.dart
[   +9 ms] test 0: starting shell process
[  +28 ms] Stopping scan for flutter_test_config.dart; found project root at C:\dev\git\flutter-webrtc
[   +5 ms] Compiler will use the following file as its incremental dill file:
C:\Users\mathu\AppData\Local\Temp\flutter_tools.9dda751e\flutter_test_compiler.b31be359\output.dill
[  +22 ms] Listening to compiler controller...
[  +35 ms] Compiling file:///C:/Users/mathu/AppData/Local/Temp/flutter_tools.9dda751e/flutter_test_listener.dbff04a6/listener.dart
[  +25 ms] C:\dev\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\dev\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\dev\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\mathu\AppData\Local\Temp\flutter_tools.9dda751e\flutter_test_compiler.b31be359\output.dill --packages
C:\dev\git\flutter-webrtc\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill C:\dev\git\flutter-webrtc\build\testfile.dill.track.dill
[  +94 ms] <- compile file:///C:/Users/mathu/AppData/Local/Temp/flutter_tools.9dda751e/flutter_test_listener.dbff04a6/listener.dart
00:01 +0: loading C:\dev\git\flutter-webrtc\test\unit\rct_peerconnection_test.dart                                                             [+1008 ms] <- accept
[   +1 ms] <- reset
[  +21 ms] Compiling C:\Users\mathu\AppData\Local\Temp\flutter_tools.9dda751e\flutter_test_listener.dbff04a6\listener.dart took 1136ms
[   +3 ms] C:\dev\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe --disable-observatory --enable-checked-mode
--verify-entry-points --enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts     
--packages=C:\dev\git\flutter-webrtc\.packages
C:\Users\mathu\AppData\Local\Temp\flutter_tools.9dda751e\flutter_test_listener.dbff04a6\listener.dart.dill
[   +4 ms] Using this directory for fonts configuration: C:\Users\mathu\AppData\Local\Temp\flutter_tools.9dda751e\flutter_test_fonts.4a8408ef   
[  +32 ms] test 0: awaiting initial result for pid 8640
[ +315 ms] test 0: process with pid 8640 connected to test harness
[   +2 ms] test 0: awaiting test result for pid 8640
00:01 +1: C:\dev\git\flutter-webrtc\test\unit\rct_peerconnection_test.dart: ... delegate this will not break the implementation by throwing NPE[ +173 ms] test 0: process with pid 8640 no longer needed by test harness
[   +2 ms] test 0: cleaning up...
[   +2 ms] test 0: ensuring end-of-process for shell
[  +15 ms] test 0: deleting temporary directory
[  +24 ms] test 0: shutting down test harness socket server
[  +23 ms] test 0: finished
00:01 +1: All tests passed!
[  +53 ms] Deleting C:\Users\mathu\AppData\Local\Temp\flutter_tools.9dda751e\flutter_test_compiler.b31be359...
[  +21 ms] killing pid 17696
[  +68 ms] Deleting C:\Users\mathu\AppData\Local\Temp\flutter_tools.9dda751e\flutter_test_fonts.4a8408ef...
[   +5 ms] test package returned with exit code 0
[   +8 ms] "flutter test" took 2 597ms.
[ +287 ms] ensureAnalyticsSent: 252ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

</details>

**Comment by darshankawar** [comment]
Hi @wer-mathurin,
Please provide more information on the issue. Are you trying to run the test on web ? Can you provide minimal complete reproducible code sample that shows the issue ?
Thanks

**Comment by wer-mathurin** [comment]
My understanding is that the annotations will tell Flutter to run it with the web.

The first section of the bug is a complete reproducible code.  If you create a file something_test.dart and copy paste the code.

Go in the directory where you created the test.  Run the following commamd: flutter test

I copied pasted the command line executed in the detail section with the -v flag added to provide more detail about the execution.

If you want the test to fail...as expected, you can just remove the annotation and run the test again.

**Comment by darshankawar** [comment]
@wer-mathurin,
Thanks for the details.
I tried to run the test on latest stable (1.20.4) and it failed with below:

<img width="883" alt="Screenshot 2020-09-18 at 7 08 54 PM" src="https://user-images.githubusercontent.com/67046386/93604078-86571300-f9e2-11ea-9f5a-be2838830d3b.png">

Is this what is expected from the test ?
Thanks.

**Comment by wer-mathurin** [comment]
I'm running it against the beta channel as you can see on the
flutter doctor provided in the test.

**Comment by wer-mathurin** [comment]
The problem was that the annotation was place on top of the imports !!! 
You can close this ticket!

**Comment by wer-mathurin** [comment]
First of all, sorry about closing and re-opening.  I just wanted to be sure I was doing the right thing.

1) Create a new flutter project.
2) Add this dependency to the pubspec.yaml
2.1)  flutter_test:
    sdk: flutter
3) Go the the default test created by the template
4) replace with the following code
`@TestOn('chrome') // Uses web-only Flutter SDK

import 'package:flutter_test/flutter_test.dart';

@TestOn('browser')
void main() {
  test('I MUST FAILD', () async {
    // Build our app and trigger a frame.
    expect(1, 2);
  });
}`
5) Execute the following command:  flutter test
6) You will have the following output:
**No tests ran.**

If you remove the annotation: the test will fail as expected !

**Comment by darshankawar** [comment]
@wer-mathurin 
Can you try by running `flutter test --platform chrome` and see if you get same failure as you get if you remove the tag and run ?
Thanks,

**Comment by wer-mathurin** [comment]
I our case, we need to use the annotation because we need to test a package, not an app.

But I still did your test and it failed (see bellow).  And this is not because of the expect function.  This juts faild to load the test itself.  I added the -v flag to give you more input.  

That's very scary that testing are not working, since all google own projects are using the annotation for package that support web!!!! 


**flutter test --platform chrome -v**

flutter test --platform chrome -v
[ +116 ms] executing: [C:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +76 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +18 ms] 8b3760638a189741cd9ca881aa2dd237c1df1be5
[   +1 ms] executing: [C:\dev\flutter/] git tag --points-at HEAD
[  +76 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.0-12.1.pre
[  +22 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] origin/beta
[        ] executing: [C:\dev\flutter/] git ls-remote --get-url origin
[  +61 ms] Exit code 0 from: git ls-remote --get-url origin
[  +12 ms] https://github.com/flutter/flutter.git
[  +88 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[  +85 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +50 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +25 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +32 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +95 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +52 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +30 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +77 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +76 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +280 ms] Generating C:\dev\git\hello_world\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[+7621 ms] Starting daemon...
[ +175 ms] Initializing inputs
[  +10 ms] Reading cached asset graph...
[ +146 ms] Reading cached asset graph completed, took 145ms

[ +200 ms] Checking for updates since last build...
[ +390 ms] Checking for updates since last build completed, took 390ms

[   +8 ms] Initializing inputs
[  +17 ms] Reading cached asset graph...
[   +1 ms] Reading cached asset graph completed, took 145ms
[   +1 ms] Checking for updates since last build...
[   +1 ms] Checking for updates since last build completed, took 390ms
[ +787 ms] About to build [web, test]...
[   +5 ms] Running build...
[  +15 ms] Running build completed, took 64ms

[   +1 ms] Caching finalized dependency graph...
[   +2 ms] Caching finalized dependency graph completed, took 85ms

[  +28 ms] Succeeded after 156ms with 0 outputs (0 actions)

00:00 +0: loading C:\dev\git\hello_world\test\widget_test.dart                                                                                 [+12075 ms] Serving tests at http://localhost:59773/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A59773%2F0&debug=false
[ +169 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:59775/devtools/browser/c8b0ae8c-de4b-4591-acf1-50b6150438d8
[ +254 ms] Did not find anything for request: widget_test.dart.browser_test.dart.js
00:00 +0 -1: loading C:\dev\git\hello_world\test\widget_test.dart [E]
  Failed to load "C:\dev\git\hello_world\test\widget_test.dart": Failed to load script at http://localhost:59773/widget_test.dart.browser_test.dart.js.
00:00 +0 -1: Some tests failed.
[  +70 ms] "flutter test" took 22 831ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:303:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #10     _rootRun (dart:async/zone.dart:1190:13)
           #11     _CustomZone.run (dart:async/zone.dart:1093:19)
           #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +157 ms] ensureAnalyticsSent: 144ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[ +181 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by wer-mathurin** [comment]
I tested it on my mac.  And here the result.
When using the annotation, I have the same result that on windows....no tests ran

When removeing the annotation and using the command:
flutter test --platform chrome

I ran as expected.  But this is still not an option for package project !

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.4 19E2269, locale
    en-IN)
    • Flutter version 1.22.0-12.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8b3760638a (6 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

• No issues found!

```

</details>

**Comment by yjbanov** [comment]
@jonahwilliams `@TestOn('browser')` isn't something we want to support, right? This implies usage of `flutter test --platform=chrome`. Instead, we want users to use `package:integration_test` when access to browser functionality and/or plugins is required. It seems in this case the desired result is an error asking the developer to remove `@TestOn('browser')`?

**Comment by ditman** [comment]
Here's an example where I migrated tests from flutter test to the integration_test package (with flutter drive), it might be helpful:

https://github.com/flutter/plugins/commit/56410f5d2caf3fa0cd1d416f1fae126f70d24954

**Comment by wer-mathurin** [comment]
Basically we are looking for the recommended way of testing a **package** that support web.

Maybe we were just not lucky because we ended up looking the way the flutter team plugins [shared_preferences](https://github.com/flutter/plugins/blob/master/packages/shared_preferences/shared_preferences_web/test/shared_preferences_web_test.dart) were doing it !

But, if this something that can be documented as well, it will reduce the friction of doing well tested packages.  This means the quality of community maintained package will be better.  

BTW, not related to this bug, but can be another metric to add to the pub points on pub.dev !  Code coverage by tests.

**Comment by ditman** [comment]
> But, if this something that can be documented as well, it will reduce the friction of doing well tested packages.

So, is this a matter of documentation then?

**Comment by wer-mathurin** [comment]
I think there is two issues.
1) If @TestOn is not supported or will not be supported that can be
documented and throw an exception that is not supported otherwise it
silently not execute the tests.  This is a problem for couple of flutter
plugins supported but the flutter team.  Eg: shared_preferences_web


2) I didn't find any relevant documentation about testing a package that
support web.  I know this is still in beta that's why we need up looking on
how the flutter team did it.

**Comment by ditman** [comment]
That's fair, I'll look at what's required to write a blog post about testing for packages that support web.

**Comment by ditman** [comment]
`@TestOn('browser')` style tests are going away: https://github.com/flutter/flutter/issues/50594

**Comment by kevmoo** [comment]
Should this issue be closed @ditman ? What's the current best practice for writing web-specific tests?

**Comment by ditman** [comment]
I've migrated all the plugin tests to use integration_test, so they rely on chromedriver. [See docs for `url_launcher_web`](https://github.com/flutter/plugins/blob/main/packages/url_launcher/url_launcher_web/example/README.md). I'd recommend doing it like this, because you can run unit-tests in the browser (not vm) but also if you need to render a more complex app, and use locators and things like that, you'd be set too.

However `@TestOn('browser')` tests are still used extensively across the framework. IIRC they need to be run by specifying `-d chrome` in the command line, for them to be running in the right environment (browser). [See the `cross_file` package tests](https://github.com/flutter/packages/tree/main/packages/cross_file) for example.

@kevmoo to close this, I think that we need a good documentation page of "running tests on the Web", if it doesn't exist already?

**Comment by natebosch** [comment]
So does `flutter test -d chrome` behave effectively like `--platform chrome` in that cas?

**Comment by natebosch** [comment]
Ah, I missed that the resolution to https://github.com/flutter/flutter/issues/50594 was to _not_ do as the title suggests.
Sorry for the confusion!

**Comment by darshankawar** [comment]
Current status as I verified:

With [code sample](https://github.com/flutter/flutter/issues/66045#issue-703760231) running as-is using `flutter test`, we get:

```
dhs@Dhss-MacBook-Pro issue_bug % flutter test
No tests ran.
No tests were found.

```

Using `flutter test --platform chrome`:  we get:

```
dhs@Dhss-MacBook-Pro issue_bug % flutter test --platform chrome
00:02 +0 -1: I MUST FAIL [E]                                                                                                                                  
  Expected: <2>
    Actual: <1>

```



> I think that we need a good documentation page of "running tests on the Web", if it doesn't exist already?

@ditman Hello, I am wondering if [this](https://github.com/flutter/flutter/wiki/Running-Flutter-Driver-tests-with-Web) documentation is sufficient and to close this issue ?

**Comment by ditman** [comment]
> @ditman Hello, I am wondering if [this](https://github.com/flutter/flutter/wiki/Running-Flutter-Driver-tests-with-Web) documentation is sufficient and to close this issue ?

@darshankawar no, that documentation is only describing how to run integration_test type of tests. I think we should add a "Testing on the Web" section, and then have:

* Unit tests, and \@TestOn (a new page that describes the behavior that you found on your last [comment](https://github.com/flutter/flutter/issues/66045#issuecomment-1621556187)), and links to maybe package:test docs about selecting platforms, etc...
* Integration tests (the page you linked)
