### ISSUE TITLE
Xcode 12  flutter1.17.6 run error 

### ISSUE THREAD

**Issue by pomegra** [flutter/flutter#66093]
Traceback (most recent call last):

  File "/tmp/335CE85D-266F-482A-B25F-547573B649E6/fruitstrap_9484ebdff2bbd7a0e436ebfbcd74ff33a2465d62.py", line 25, in connect_command

    process = lldb.target.ConnectRemote(listener, connect_url, None, error)

AttributeError: 'NoneType' object has no attribute 'ConnectRemote'

Traceback (most recent call last):

  File "/tmp/335CE85D-266F-482A-B25F-547573B649E6/fruitstrap_9484ebdff2bbd7a0e436ebfbcd74ff33a2465d62.py", line 45, in run_command

    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))

AttributeError: 'NoneType' object has no attribute 'modules'

Traceback (most recent call last):

  File "/tmp/335CE85D-266F-482A-B25F-547573B649E6/fruitstrap_9484ebdff2bbd7a0e436ebfbcd74ff33a2465d62.py", line 74, in safequit_command

    process = lldb.target.process

AttributeError: 'NoneType' object has no attribute 'process'

**Comment by pedromassangocode** [comment]
Hi @pomegra 
Can you please upgrade to latest  `stable` channel and try again:
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persist, please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by tban** [comment]
Flutter update. The new versión 1.20.4 stable resolve this issue.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by binzi56** [comment]
> `flutter upgrade `
> The new versión 1.20.4 stable resolve this issue for me

me too, thank for your answer😝
