### ISSUE TITLE
flutter run crash: 'columnWidth >= 0': is not true

### ISSUE THREAD

**Issue by HChong3210** [flutter/flutter#66096]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d 11405E12-1BF3-4CFF-A44A-DFF6D05781ED --verbose

## exception

_AssertionError: 'package:flutter_tools/src/base/utils.dart': Failed assertion: line 403 pos 10: 'columnWidth >= 0': is not true.

```
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      _wrapTextAsLines (package:flutter_tools/src/base/utils.dart:403:10)
#3      wrapText (package:flutter_tools/src/base/utils.dart:345:21)
#4      StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:199:15)
#5      VerboseLogger._emit (package:flutter_tools/src/base/logger.dart:465:14)
#6      VerboseLogger.printTrace (package:flutter_tools/src/base/logger.dart:402:5)
#7      printTrace (package:flutter_tools/src/globals.dart:74:43)
#8      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:272:7)
<asynchronous suspension>
#9      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:467:52)
<asynchronous suspension>
#10     IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:436:48)
<asynchronous suspension>
#11     IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:354:15)
#12     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:451:54)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#32     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#41     _rootRun (dart:async/zone.dart:1126:13)
#42     _CustomZone.run (dart:async/zone.dart:1023:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/hc/OpenSource/flutter
    • Framework revision 0b8abb4724 (7 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/hc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/hc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • XXX的 iPhone • f85285b8952c7c164148b1271ca080cb29046a54 • ios • iOS 13.5.1
    • iPhone 11   • 11405E12-1BF3-4CFF-A44A-DFF6D05781ED     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @HChong3210 
Can you please upgrade to latest  `stable` channel and try again:
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persist, please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
