### ISSUE TITLE
TextFormField.onFieldSubmitted with TextInputAction.next fails inside a GestureDetector which requestFocus

### ISSUE THREAD

**Issue by erf** [flutter/flutter#66106]
## Steps to Reproduce

1. Create a `TextFormField` with a `onFieldSubmitted` and `textInputAction: TextInputAction.next`
2. Wrap the textField inside a `GestureDetector` which calls `requestFocus(FocusNode())` on a `panDowEvent`
3. Now if you tap the field, type something and press *next* on the keyboard, `onFieldSubmitted` is called
4. If you then swipe the page and try to focus on the text field again and press *next* on the keyboard, `onFieldSubmitted` is not called again

**Expected results:** 

I would expect `onFieldSubmitted` to always be called.

**Actual results:** 

`onFieldSubmitted` is not called after `requestFocus` on gesture event. Note this only seem to happen on `textInputAction: TextInputAction.next`.

### Example

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'onSubmitted test',
      home: Page1(),
    );
  }
}

class Page1 extends StatefulWidget {
  @override
  _Page1State createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page 1'),
      ),
      body: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onPanDown: (_) {
          FocusScope.of(context).requestFocus(FocusNode());
        },
        child: Center(
          child: ListTile(
            title: TextFormField(
              onFieldSubmitted: (text) {
                debugPrint('onFieldSubmitted');
              },
              textInputAction: TextInputAction.next,
            ),
          ),
        ),
      ),
    );
  }
}
```

Notice how *onFieldSubmitted* is not printed after you swipe the page.

<details>
  <summary>Logs</summary>

[log.txt](https://github.com/flutter/flutter/files/5244821/log.txt)

```
Analyzing test_on_submitted...
No issues found! (ran in 2.0s)
```

```
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-12.0.pre at /Users/erlend/flutter
    • Framework revision a27c242b0e (7 days ago), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/erlend/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • Erlend (mobile) • 76dfa318a18803240a229805dd90bcb18d07fef1 • ios        • iOS 13.7
    • macOS (desktop) • macos                                    • darwin-x64 • Mac OS X 10.15.6 19G2021

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment]
Hi @erf 
The docs says: 
![Screen Shot 2020-09-18 at 12 43 12](https://user-images.githubusercontent.com/67424416/93593764-92c07900-f9ac-11ea-8f22-b594b65c2f0a.png)

So this is an expected behavior.

Your code is not working because of `FocusScope.of(context).requestFocus(FocusNode());` on this line you are requesting focus for a node that is not attached to any widget.

I modified your code to work as you expected.

<details><summary>working sample code</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'onSubmitted test',
      home: Page1(),
    );
  }
}

class Page1 extends StatefulWidget {
  @override
  _Page1State createState() => _Page1State();
}

class _Page1State extends State<Page1> {

  FocusNode node = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page 1'),
      ),
      body: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onPanDown: (_) {
          FocusScope.of(context).requestFocus(node);
        },
        child: Center(
          child: ListTile(
            title: TextFormField(
              focusNode: node,
              onFieldSubmitted: (text) {
                debugPrint('onFieldSubmitted');
              },
              textInputAction: TextInputAction.next,
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

I'm closing this as working as expected. 
Thank you

**Comment by erf** [comment]
@pedromassangocode my intention with my code was to clear focus, which it did, but it also somehow made the `onFieldSubmitted` not work. With your code change i'm not solving my problem anymore. Please reopen.

**Comment by pedromassangocode** [comment]
Hi @erf 
Thanks for clarifying. I was able to reproduce this on latest `dev` and `master` channel.

From the logs looks like the input connection is being lost after the swipe gesture.

<details><summary>Logs</summary>

```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
I/flutter_exampl( 6452): Not late-enabling -Xcheck:jni (already on)
I/flutter_exampl( 6452): Unquickening 12 vdex files!
W/flutter_exampl( 6452): Unexpected CPU variant for X86 using defaults: x86
W/flutter_exampl( 6452): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
W/flutter_exampl( 6452): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_exampl( 6452): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
W/flutter_exampl( 6452): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
Waiting for sdk gphone x86 arm to report its views...
Debug service listening on ws://127.0.0.1:51211/A5S021Gk3dI=/ws
Syncing files to device sdk gphone x86 arm...
W/IInputConnectionWrapper( 6452): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6452): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6452): endBatchEdit on inactive InputConnection
I/flutter ( 6452): onFieldSubmitted
W/IInputConnectionWrapper( 6452): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6452): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6452): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6452): setComposingRegion on inactive InputConnection
W/IInputConnectionWrapper( 6452): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6452): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6452): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6452): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 6452): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 6452): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 6452): endBatchEdit on inactive InputConnection
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.251, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.251 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision d26268bb9e (14 hours ago), 2020-09-18 09:06:26 +0900
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by maheshmnj** [comment]
I tried the above reproducible steps,`onFieldSubmitted` is executed for the first time, and while submitting after regaining focus for the second time exception occurs. This issue is reproducible on both the latest stable and the master channel.

<details>
<summary>logs</summary>

```dart
Performing hot restart...                                               
Restarted application in 367ms.
flutter: onFieldSubmitted

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during method call TextInputClient.performAction:
Tried to get the bounds of a focus node that didn't have its context set yet.
The context needs to be set before trying to evaluate traversal policies. Setting the context is
typically done with the attach method.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 790 pos 7: 'context != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      FocusNode.rect (package:flutter/src/widgets/focus_manager.dart:790:7)
#3      new _ReadingOrderSortData (package:flutter/src/widgets/focus_traversal.dart:856:21)
#4      ReadingOrderTraversalPolicy.sortDescendants
(package:flutter/src/widgets/focus_traversal.dart:1099:49)
#5      FocusTraversalPolicy._sortAllDescendants
(package:flutter/src/widgets/focus_traversal.dart:317:65)
#6      FocusTraversalPolicy._moveFocus (package:flutter/src/widgets/focus_traversal.dart:390:41)
#7      FocusTraversalPolicy.next (package:flutter/src/widgets/focus_traversal.dart:222:39)
#8      FocusNode.nextFocus (package:flutter/src/widgets/focus_manager.dart:1136:56)
#9      EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:2272:30)
#10     EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:2138:9)
#11     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1817:37)
#12     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1701:20)
#13     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:536:55)
#14     MethodChannel.setMethodCallHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:529:34)
#15     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:387:35)
#16     _invoke2 (dart:ui/hooks.dart:186:13)
#17     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#18     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#19     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#20     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#21     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 2 frames from class _AssertionError)

call:
  MethodCall(TextInputClient.performAction, [3, TextInputAction.next])
════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
