### ISSUE TITLE
Cannot build and run app after updating to Xcode 12 (iOS 14): Target debug_universal_framework failed: Exception: Unsupported iOS arch name

### ISSUE THREAD

**Issue by tizianogioe8** [flutter/flutter#66104]
## Steps to Reproduce

Before updating yesterday to Xcode 12, everything was running perfectly. When I updated to the newest version of Xcode my iOS app won't build or run on physical device and simulator. Xcode build ends with an error saying "module cloud_firestore not found". I'm using Runner.xcworkspace and I already updated cloud_firestore to the latest version. However every module of my application has this problem (even deleting the import of cloud_firestore, the build ends with another "module xxx not found". 
This is the output of flutter doctor -v:

```
[✓] Flutter (Channel dev, 1.22.0-12.0.pre, on Mac OS X 10.15.4 19E287, locale
    it-IT)
    • Flutter version 1.22.0-12.0.pre at /Users/tiziano/Desktop/Sviluppo/flutter
    • Framework revision a27c242b0e (6 giorni fa), 2020-09-11 17:46:57 -0400
    • Engine revision fee6f9e533
    • Dart version 2.10.0 (build 2.10.0-110.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tiziano/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • AUM L29 (mobile)  • QDG9X18827W03119                     • android-arm64 •
      Android 8.0.0 (API 26)
    • iPhone 8 (mobile) • 702B0408-7B1E-4176-BCD3-89500F520FE7 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

This is the output from flutter run --verbose:
[Terminal Output.txt](https://github.com/flutter/flutter/files/5244668/Terminal.Output.txt)

This is the output from Xcode:
![Schermata 2020-09-18 alle 11 18 44](https://user-images.githubusercontent.com/36270604/93581116-fc3a8a80-f9a0-11ea-8b3f-75fe3cb21766.png)

I also tried deleting Podfile, Pods, and then pod install, still didn't work. I Also tried pod deintegrate and then pod install, didn't work neither. I also tried to switch from stable channel to dev channel, still didn't work.

**Comment by pedromassangocode** [comment]
Hi @tizianogioe8 
Can you please provide your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by tizianogioe8** [comment]
The output from flutter run --verbose is in the txt file attached to the issue, here is the pubspec.yaml:
[pubspec.yaml.zip](https://github.com/flutter/flutter/files/5245213/pubspec.yaml.zip)

**Comment by pedromassangocode** [comment]
I see a lot of this line in the logs:

```
                     [  +40 ms] Target debug_universal_framework failed:
                     Exception: Unsupported iOS arch name ""
```

Just to make sure, are you able to run your project if you comment cloud_firestore package in your pubspec.yaml?

**Comment by tizianogioe8** [comment]
Same error unfortunately

**Comment by carson-katri** [comment]
I am experiencing this issue as well, with:

```objectivec
...
#if __has_include(<firebase_analytics/FLTFirebaseAnalyticsPlugin.h>)
#import <firebase_analytics/FLTFirebaseAnalyticsPlugin.h>
#else
@import firebase_analytics;
#endif

#if __has_include(<flutter_email_sender/FlutterEmailSenderPlugin.h>)
#import <flutter_email_sender/FlutterEmailSenderPlugin.h>
#else
@import flutter_email_sender;
#endif

#if __has_include(<image_cropper/FLTImageCropperPlugin.h>)
#import <image_cropper/FLTImageCropperPlugin.h>
#else
@import image_cropper;
#endif

#if __has_include(<image_picker/FLTImagePickerPlugin.h>)
#import <image_picker/FLTImagePickerPlugin.h>
#else
@import image_picker;
#endif

#if __has_include(<shared_preferences/FLTSharedPreferencesPlugin.h>)
#import <shared_preferences/FLTSharedPreferencesPlugin.h>
#else
@import shared_preferences;
#endif

#if __has_include(<url_launcher/FLTURLLauncherPlugin.h>)
#import <url_launcher/FLTURLLauncherPlugin.h>
#else
@import url_launcher;
#endif

#if __has_include(<firebase_messaging/FirebaseMessagingPlugin.h>)
#import <firebase_messaging/FirebaseMessagingPlugin.h>
#else
@import firebase_messaging;
#endif
...
```
If I disable `firebase_analytics`, `flutter_email_sender` has the error, and so on.

**Comment by danisandoval** [comment]
Same thing happend here, but i see that the script being called is using an empty _dIosArchs_ arch param

Example: 

/Applications/flutter/bin/flutter --verbose assemble --output=/Users/dani/Documents/FlutterDev/flutter-driver/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=/Users/dani/Documents/FlutterDev/flutter-driver/lib/main.dart -dBuildMode=debug **-dIosArchs=** -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= debug_ios_bundle_flutter_assets

**Comment by jmagman** [comment]
@danisandoval good call on the empty `dIosArchs`.  That's really weird, `ARCHS` is coming from the build setting.
https://github.com/flutter/flutter/blob/7e27b140f0e8ee42819bd2d69e7a13eaaa095979/packages/flutter_tools/bin/xcode_backend.sh#L187

**Comment by SpencerLindemuth** [comment]
I am having this issue as well. Cannot build on simulator ios14, xcode 12.04, flutter 1.22.

flutter run --verbose yields:

```
Target debug_universal_framework failed: Exception: Unsupported iOS arch name ""
    #0      getIOSArchForName (package:flutter_tools/src/build_info.dart:481:3)
    #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
    #2      ListIterable.toSet (dart:_internal/iterable.dart:216:18)
    #3      DebugUniveralFramework.build (package:flutter_tools/src/build_system/targets/ios.dart:217:9)
    #4      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
    #5      _rootRunUnary (dart:async/zone.dart:1198:47)
    #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
    #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
    #13     Node.computeChanges (package:flutter_tools/src/build_system/build_system.dart)
    #14     _rootRunUnary (dart:async/zone.dart:1198:47)
    #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
    #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
    #22     FileStore.diffFileList (package:flutter_tools/src/build_system/file_store.dart)
    #23     _rootRunUnary (dart:async/zone.dart:1198:47)
    #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #29     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
    #30     _rootRunUnary (dart:async/zone.dart:1198:47)
    #31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #32     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #34     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #35     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #36     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
    #37     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
    #38     FileStore._hashFile (package:flutter_tools/src/build_system/file_store.dart)
    #39     _rootRunUnary (dart:async/zone.dart:1198:47)
    #40     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #41     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
    #42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
    #43     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
    #44     Future._completeWithValue (dart:async/future_impl.dart:529:5)
    #45     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
    #46     _rootRun (dart:async/zone.dart:1190:13)
    #47     _CustomZone.run (dart:async/zone.dart:1093:19)
    #48     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #49     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
    #50     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #51     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
    #52     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
    #53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by jmagman** [comment]
```
                     warning: None of the architectures in ARCHS (x86_64) are
                     valid. Consider setting ARCHS to $(ARCHS_STANDARD) or
                     updating it to include at least one value from VALID_ARCHS
                     (arm64, arm64e, armv7, armv7s). (in target 'Runner' from
                     project 'Runner')
```
@tizianogioe8 @SpencerLindemuth @danisandoval  are you running on a macOS ARM (Apple Silicon) machine, like a DTK?

**Comment by jmagman** [comment]
Probably not, I think you need macOS 11 or whatever they are calling big sur to run on a DTK.

**Comment by tizianogioe8** [comment]
I’m developing on a iMac 2017 with Catalina. On these days, I found that there is probably a problem in the xcode project, specially in architectures section, because xcode keeps saying what you’re writing. This is a known issue with xcode 12 if you google it, but I couldn’t find any solution that fits for me. I know that some users managed to solve it by the way

**Comment by jmagman** [comment]
Yeah definitely not: `-target x86_64-apple-ios8.0-simulator`, nevermind.

Weird, this is coming from the same build settings export:
```
export NATIVE_ARCH_ACTUAL\=x86_64
export VALID_ARCHS\=arm64\ arm64e\ armv7\ armv7s
```

**Comment by SpencerLindemuth** [comment]
I got mine to build by changing the VALID_ARCHS in Targets -> Runner -> User Defined from 
```
armv7 armv7s arm64e arm64
```

To 
```
armv7 armv7s arm64e arm64 x86_64
```
And now it runs on simulator and builds release as well!

**Comment by tizianogioe8** [comment]
> I got mine to build by changing the VALID_ARCHS in Targets -> Runner -> User Defined from
> 
> ```
> armv7 armv7s arm64e arm64
> ```
> 
> To
> 
> ```
> armv7 armv7s arm64e arm64 x86_64
> ```
> 
> And now it runs on simulator and builds release as well!

Could you please provide a screenshot of your configuration? So that I can try too

**Comment by jmagman** [comment]
You definitely shouldn't need to do that, and it may mess up your app submission... mess with that at your own discretion.

**Comment by tizianogioe8** [comment]
> Yeah definitely not: `-target x86_64-apple-ios8.0-simulator`, nevermind.
> 
> Weird, this is coming from the same build settings export:
> 
> ```
> export NATIVE_ARCH_ACTUAL\=x86_64
> export VALID_ARCHS\=arm64\ arm64e\ armv7\ armv7s
> ```

As you can tell from this output: 
[Build target Runner_2020-10-09T01-40-54.txt](https://github.com/flutter/flutter/files/5351779/Build.target.Runner_2020-10-09T01-40-54.txt)

It seems like it's trying to build on x86_64, but that's not in Valid Archs, I don't really know how to change that value, and I don't know either if it's something that I can do without ruining a thing

**Comment by SpencerLindemuth** [comment]
<img width="1128" alt="Screen Shot 2020-10-09 at 8 00 39 AM" src="https://user-images.githubusercontent.com/47793873/95599705-434af700-0a06-11eb-8dc5-649db92e3a42.png">

**Comment by tizianogioe8** [comment]
Thanks, changing this value made me build on simulator!

**Comment by danisandoval** [comment]
> ```
>                      warning: None of the architectures in ARCHS (x86_64) are
>                      valid. Consider setting ARCHS to $(ARCHS_STANDARD) or
>                      updating it to include at least one value from VALID_ARCHS
>                      (arm64, arm64e, armv7, armv7s). (in target 'Runner' from
>                      project 'Runner')
> ```
> 
> 
> @tizianogioe8 @SpencerLindemuth @danisandoval  are you running on a macOS ARM (Apple Silicon) machine, like a DTK?

Nope, Intel Mac here, Mac OS Catalina 10.15.7 with a Intel Core i7 CPU

**Comment by jmagman** [comment]
>  it's trying to build on x86_64, but that's not in Valid Archs

I don't think x86_64 ever shows up in the UI, but you can see it if you run:
```
xcrun xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme Runner -configuration Debug 
VALID_ARCHS = arm64 arm64e armv7 armv7s
```
vs
```
xcrun xcodebuild -sdk iphonesimulator -showBuildSettings -workspace Runner.xcworkspace -scheme Runner -configuration Debug 
VALID_ARCHS = arm64 arm64e i386 x86_64
```
I'm on Xcode 12 so there's ARM simulators in play for Apple Silicon.

**Comment by jmagman** [comment]
Just spotted this from @tizianogioe8 's log:
```
    export arch\=undefined_arch
```
And there isn't even an ARCHS build setting, where did that go?

For anyone else seeing this, can you attach the output of `flutter run -v` (it will be large, so attach it)?  Looking for what `ARCHS` is.

**Comment by evripidesk** [comment]
Any news with this issue?

**Comment by jmagman** [comment]
@evripidesk 

> For anyone else seeing this, can you attach the output of `flutter run -v` (it will be large, so attach it)? Looking for what `ARCHS` is.

**Comment by evripidesk** [comment]
you can find the logs on below link
[https://file.io/hInmsXijGdo0](https://file.io/hInmsXijGdo0)

**Comment by jmagman** [comment]
@evripidesk Can you attach the logs to this issue instead?

**Comment by evripidesk** [comment]
Its so big and is not accepted max 65536 characters
you can download from wetransfer
[https://we.tl/t-BNgET1HWAC](https://we.tl/t-BNgET1HWAC)

**Comment by evripidesk** [comment]
[flutter run -v.txt](https://github.com/flutter/flutter/files/5516090/flutter.run.-v.txt)
attached is the logs if you didnt open them from wetransfer

**Comment by jmagman** [comment]
@evripidesk Your error is different and your logs don't contain `Unsupported iOS arch name`, please file a new issue:
```
\cf4                error: module 'assets_audio_player' not found\cf2 \
\cf4                @import assets_audio_player;\cf2 \
\cf4                 ~~~~~~~^~~~~~~~~~~~~~~~~~~\cf2 \
\cf4                1 error generated.\cf2 \
```

**Comment by evripidesk** [comment]
If I remove this package then I get the same error for the next package, any workaround to solve this issue so I can build the app on iOS

**Comment by jmagman** [comment]
@evripidesk You need to file a new issue so it can be triaged and the right people can look at it.  This issue is unrelated.

**Comment by Abdullah-Shamhan** [comment]
Any solution? Facing the same exact issue..

**Comment by jmagman** [comment]
I'm not sure why this was closed.

**Comment by ferhatb** [comment]
@jmagman happy to help repro, I have same problem on IntelliJ. command line works fine.

**Comment by jmagman** [comment]
> @jmagman happy to help repro, I have same problem on IntelliJ. command line works fine.

I took a look, @ferhatb had a stray `--local-engine=host_debug_unopt` flag in the configuration.

**Comment by jmagman** [comment]
Is anyone still seeing this on Flutter 2.5?  I fixed various arm64 bugs that may have been causing this.

**Comment by crawford-jake** [comment]
I am seeing it now on the latest flutter master channel

**Comment by crawford-jake** [comment]
I fixed this by going to Target > Build Settings > Architectures > Excluded Architectures and replacing all arm64 with i386

**Comment by jmagman** [comment]
> I fixed this by going to Target > Build Settings > Architectures > Excluded Architectures and replacing all arm64 with i386

@crawford-jake  I'm concerned, on master you shouldn't have to touch `EXCLUDED_ARCHS`, the tool should be setting that correctly for you.  Are you saying `arm64` was previously excluded for the simulator in your Xcode project?  Did you previously manually add that?  As of https://github.com/flutter/flutter/pull/85059 the generated build settings Flutter sets shouldn't include `arm64`, unless you have a plugin that doesn't support the arm64 simulator, in which case the entire app falls back to excluding it as of https://github.com/flutter/flutter/pull/87244.  Can I get a before and after of your Xcode project from when it didn't work to when it did?  `ios/Runner.xcodeproj/project.pbxproj`.

@F-anleo you also shouldn't need to set this for your pods, unless you have a plugin that doesn't support an arm simulator, but isn't properly declaring it, like https://github.com/flutter/flutter/issues/90382#issuecomment-935231471.  Can you file a new issue and include `--verbose` logging from when it wasn't working?

**Comment by crawford-jake** [comment]
arm64 was not listed as an excluded architecture prior to finding this bug. We had to manually add that line. I found a commit in our own project where a developer was changing build settings related to the app architecture. I think if anyone encounters this error, the cause is from manually editing the build architectures at some point in time. @jmagman  If you would still like the project.pbxproj before and after files I can send them, but I think this is probably a non issue.

**Comment by jmagman** [comment]
> If you would still like the project.pbxproj before and after files I can send them, but I think this is probably a non issue.

I would still like it.

**Comment by vashworth** [comment]
This issue is pretty old, so it'll be difficult to debug at this point. To summarize, it appears that Xcode resolved the ARCHS build setting to `arm64` but the host computer was `x86_64`. It's unclear why `x86_64` wasn't found as a valid arch when targeting a physical device, but was when targeting a simulator:

> > it's trying to build on x86_64, but that's not in Valid Archs
> 
> I don't think x86_64 ever shows up in the UI, but I can see it when I run:
> 
> ```
> xcrun xcodebuild -showBuildSettings -workspace Runner.xcworkspace -scheme Runner -configuration Debug 
> VALID_ARCHS = arm64 arm64e armv7 armv7s
> ```
> 
> vs
> 
> ```
> xcrun xcodebuild -sdk iphonesimulator -showBuildSettings -workspace Runner.xcworkspace -scheme Runner -configuration Debug 
> VALID_ARCHS = arm64 arm64e i386 x86_64
> ```
> 
> I'm on Xcode 12 so there's ARM simulators in play for Apple Silicon.

It's possible that a plugin dependency or transitive dependency was excluding arm64 in their podspec.

At this point, this issue likely isn't actionable for us to debug further.

If you see this in the future, please include the `-v` (verbose) run logs and the `Podfile.lock`.

Closing.
