### ISSUE TITLE
Removing children from a ListView that has a zero-height child with a Key throws Exception

### ISSUE THREAD

**Issue by knaeckeKami** [flutter/flutter#66198]
## Steps to Reproduce

1. run main.dart:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: Test())));

class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  bool showing = true;

  @override
  Widget build(BuildContext context) {
    return ListView(children: [
      if (showing)
        for (int i = 0; i < 20; i++)
          Container(
            height: 100,
            child: const Placeholder(),
          ),
      Container(
        height: 400,
        alignment: Alignment.bottomCenter,
        color: Colors.red,
        child: RaisedButton(
          onPressed: () => setState(() => showing = !showing),
          child: Text(showing ? 'hide' : 'show'),
        ),
      ),
      // a zero-sized widget with a key will cause an exception
      // to be thrown when the user clicks "hide"
      const SizedBox.shrink(key: Key('break')),
    ]);
  }
}
```

2. Scroll down and click the button

**Expected results:** 

These placeholder items should disappear and no exceptions should be thrown.

**Actual results:** 

This exceptions is thrown:

<details>
  <summary>Exception</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 580 pos 12:
flutter: 'child != null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   ListView file:///Users/kami/development/sliver_list_test/lib/main.dart:15:12
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderSliverMultiBoxAdaptor.childScrollOffset (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:580:12)
flutter: #3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:106:14)
flutter: #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #5      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:11)
flutter: #6      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:377:11)
flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #8      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
flutter: #9      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
flutter: #10     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
flutter: #11     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
flutter: #12     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
flutter: #13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
flutter: #15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #22     _invoke (dart:ui/hooks.dart:253:10)
flutter: #23     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderSliverList#9928a relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   needs compositing
flutter:   creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#42b87] ←
flutter:     Semantics ← _PointerListener ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#9a69b] ← _PointerListener ← Listener
flutter:     ← ⋯
flutter:   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
flutter:     scrollOffset: 433.0, remainingPaintExtent: 667.0, crossAxisExtent: 375.0, crossAxisDirection:
flutter:     AxisDirection.right, viewportMainAxisExtent: 667.0, remainingCacheExtent: 1167.0, cacheOrigin:
flutter:     -230.0)
flutter:   geometry: SliverGeometry(scrollExtent: 1100.0, paintExtent: 667.0, maxPaintExtent: 1100.0,
flutter:     hasVisualOverflow: true, cacheExtent: 897.0)
flutter:   currently live children: 1 to 1
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child with index 1: RenderIndexedSemantics#605d2 relayoutBoundary=up3
flutter:       child: RenderRepaintBoundary#3f1b0 relayoutBoundary=up4
flutter:         child: RenderConstrainedBox#6e57a relayoutBoundary=up5
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The method '-' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The method '-' was called on null.
```
</details>

```
flutter analyze
Analyzing lib...
No issues found! (ran in 1.6s)
```

This happens on all current versions of Flutter, from stable to master (with slightly different exceptions due to NNBD).
Here's my doctor output from stable:
<details>

```
flutter doctor -v
Downloading android-arm-profile/darwin-x64 tools...                 1.5s
Downloading android-arm-release/darwin-x64 tools...                 1.0s
Downloading android-arm64-profile/darwin-x64 tools...               1.4s
Downloading android-arm64-release/darwin-x64 tools...               1.3s
Downloading android-x64-profile/darwin-x64 tools...                 1.4s
Downloading android-x64-release/darwin-x64 tools...                 1.4s
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.4 at /Users/kami/development/flutter
    • Framework revision fba99f6cf9 (5 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kami/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/kami/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 82B6CB8E-818C-4556-A5FB-087F35387B7B • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 1 category.
```

</details>

Removing the key from the `SizedBox.shrink()` widget will stop the exception from being thrown, as does removing the SizedBox.shrink() widget altogether. 

Thanks to @Kavantix for helping me to create a reproducible version of this issue.

I stumbled upon this while adding a new feature to my app, and this manifested itself in the app completely locking up without throwing an exception, also hot-reload and hot-restart stopped working, it was like Flutter was stuck in an endless loop or something.

I'm not able to reproduce this behaviour (of completely locking up) outside of my app, though.

**Comment by PixelToast** [comment]
This file was migrated so here's the exception on master:

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was: 
  ListView file:///C:/Users/pix/IdeaProjects/ftest7/lib/main2.dart:15:12
When the exception was thrown, this was the stack: 
#0      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:104:51)
#1      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#2      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:132:12)
#3      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
...
The following RenderObject was being processed when the exception was fired: RenderSliverList#6ecae relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 1528.4, remainingPaintExtent: 850.9, crossAxisExtent: 392.7, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 850.9, remainingCacheExtent: 1350.9, cacheOrigin: -215.1)
...  geometry: SliverGeometry(scrollExtent: 2400.0, paintExtent: 850.9, maxPaintExtent: 2400.0, hasVisualOverflow: true, cacheExtent: 1086.7)
...    scrollExtent: 2400.0
...    paintExtent: 850.9
...    maxPaintExtent: 2400.0
...    hasVisualOverflow: true
...    cacheExtent: 1086.7
...  currently live children: 1 to 1
RenderObject: RenderSliverList#6ecae relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 1528.4, remainingPaintExtent: 850.9, crossAxisExtent: 392.7, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 850.9, remainingCacheExtent: 1350.9, cacheOrigin: -215.1)
  geometry: SliverGeometry(scrollExtent: 2400.0, paintExtent: 850.9, maxPaintExtent: 2400.0, hasVisualOverflow: true, cacheExtent: 1086.7)
    scrollExtent: 2400.0
    paintExtent: 850.9
    maxPaintExtent: 2400.0
    hasVisualOverflow: true
    cacheExtent: 1086.7
  currently live children: 1 to 1
...  child with index 1: RenderIndexedSemantics#3a1a5 relayoutBoundary=up3 NEEDS-PAINT
...    needs compositing
...    parentData: index=1; layoutOffset=None (can use size)
...    constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(392.7, 0.0)
...    index: 1
...    child: RenderRepaintBoundary#c0eeb relayoutBoundary=up4 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
...      size: Size(392.7, 0.0)
...      usefulness ratio: no metrics collected yet (never painted)
...      child: RenderConstrainedBox#16d57 relayoutBoundary=up5 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
...        size: Size(392.7, 0.0)
...        additionalConstraints: BoxConstraints(w=0.0, h=0.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by iapicca** [comment]
consider this
<details>
<summary>workaround</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp() : super(key: const Key('MyApp'));

  @override
  Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
  const MyHomePage() : super(key: const Key('MyHomePage'));

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _showing = false;

  @override
  Widget build(BuildContext context) => Scaffold(
        body: ListView(children: [
          ..._showing
              ? [
                  for (int i = 0; i < 20; i++)
                    Container(
                      height: 100,
                      child: const Placeholder(),
                    )
                ]
              : [],
          Container(
            height: 400,
            alignment: Alignment.bottomCenter,
            color: Colors.red,
            child: RaisedButton(
              onPressed: () => setState(() => _showing = !_showing),
              child: Text(_showing ? 'hide' : 'show'),
            ),
          ),
        ]),
      );
}
```

</details>

**Comment by Kavantix** [comment]
@iapicca I think you misunderstood the issue here
We made a small as possible sample that can reproduce the crash.
Your example is equivalent except for the widget with the key which causes the crash. In the real app simply removing the widget (or the key for that matter) is not an option

**Comment by iapicca** [comment]
@Kavantix yep!
you are right, I didn't get it
thanks for the explanation

**Comment by Hixie** [comment]
cc @Piinks who has some experience in this code.

**Comment by knaeckeKami** [comment]
FWIW it's the same Widget that also caused https://github.com/flutter/flutter/issues/62198 :D

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Scaffold(body: Test())));

class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  bool showing = true;

  @override
  Widget build(BuildContext context) {
    return ListView(children: [
      if (showing)
        for (int i = 0; i < 20; i++)
          Container(
            height: 100,
            child: const Placeholder(),
          ),
      Container(
        height: 400,
        alignment: Alignment.bottomCenter,
        color: Colors.red,
        child: RaisedButton(
          onPressed: () => setState(() => showing = !showing),
          child: Text(showing ? 'hide' : 'show'),
        ),
      ),
      // a zero-sized widget with a key will cause an exception
      // to be thrown when the user clicks "hide"
      const SizedBox.shrink(key: Key('break')),
    ]);
  }
}

```

</details> 

<details> 
<summary>logs</summary> 

```bash
Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           22.1s
Connecting to VM Service at ws://127.0.0.1:57772/ZqxvlXceioQ=/ws

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during performLayout():[39;49m
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 580 pos 12: 'child != null': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mListView[39;49m 
 lib/main.dart
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      RenderSliverMultiBoxAdaptor.childScrollOffset[39;49m 
 package:flutter/…/rendering/sliver_multi_box_adaptor.dart
[38;5;244m#3      RenderSliverList.performLayout[39;49m 
 package:flutter/…/rendering/sliver_list.dart
[38;5;244m#4      RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#5      RenderSliverEdgeInsetsPadding.performLayout[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#6      RenderSliverPadding.performLayout[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: RenderSliverList#12c61 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
[38;5;244mRenderObject: RenderSliverList#12c61 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE[39;49m
    [38;5;244mneeds compositing[39;49m
    [38;5;244mparentData: paintOffset=Offset(0.0, 0.0) (can use size)[39;49m
    [38;5;244mconstraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 1538.0, remainingPaintExtent: 896.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 896.0, remainingCacheExtent: 1396.0, cacheOrigin: -202.0)[39;49m
    [38;5;244mgeometry: SliverGeometry(scrollExtent: 2400.0, paintExtent: 862.0, maxPaintExtent: 2400.0, hasVisualOverflow: true, cacheExtent: 1064.0)[39;49m
        [38;5;244mscrollExtent: 2400.0[39;49m
        [38;5;244mpaintExtent: 862.0[39;49m
        [38;5;244mmaxPaintExtent: 2400.0[39;49m
        [38;5;244mhasVisualOverflow: true[39;49m
        [38;5;244mcacheExtent: 1064.0[39;49m
    [38;5;244mcurrently live children: 1 to 1[39;49m
    [38;5;244mchild with index 1: RenderIndexedSemantics#ed858 relayoutBoundary=up3[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: index=1; layoutOffset=None (can use size)[39;49m
        [38;5;244mconstraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)[39;49m
        [38;5;244msemantic boundary[39;49m
        [38;5;244msize: Size(414.0, 0.0)[39;49m
        [38;5;244mindex: 1[39;49m
        [38;5;244mchild: RenderRepaintBoundary#d1896 relayoutBoundary=up4[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: <none> (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)[39;49m
            [38;5;244mlayer: OffsetLayer#d392e[39;49m
                [38;5;244mengine layer: OffsetEngineLayer#b56be[39;49m
                [38;5;244moffset: Offset(0.0, 862.0)[39;49m
            [38;5;244msize: Size(414.0, 0.0)[39;49m
            [38;5;244mmetrics: 97.3% useful (1 bad vs 36 good)[39;49m
            [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild: RenderConstrainedBox#c1d80 relayoutBoundary=up5[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)[39;49m
                [38;5;244msize: Size(414.0, 0.0)[39;49m
                [38;5;244madditionalConstraints: BoxConstraints(w=0.0, h=0.0)[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 580 pos 12:
'child != null': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
The relevant error-causing widget was:
  [38;5;248mListView[39;49m 
 lib/main.dart
When the exception was thrown, this was the stack:
[38;5;244m#2      RenderSliverMultiBoxAdaptor.childScrollOffset[39;49m 
 package:flutter/…/rendering/sliver_multi_box_adaptor.dart
[38;5;244m#3      RenderSliverList.performLayout[39;49m 
 package:flutter/…/rendering/sliver_list.dart
[38;5;244m#4      RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#5      RenderSliverEdgeInsetsPadding.performLayout[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#6      RenderSliverPadding.performLayout[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#7      RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#8      RenderViewportBase.layoutChildSequence[39;49m 
 package:flutter/…/rendering/viewport.dart
[38;5;244m#9      RenderViewport._attemptLayout[39;49m 
 package:flutter/…/rendering/viewport.dart
[38;5;244m#10     RenderViewport.performLayout[39;49m 
 package:flutter/…/rendering/viewport.dart
[38;5;244m#11     RenderObject._layoutWithoutResize[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#12     PipelineOwner.flushLayout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#13     RendererBinding.drawFrame[39;49m 
 package:flutter/…/rendering/binding.dart
[38;5;244m#14     WidgetsBinding.drawFrame[39;49m 
 package:flutter/…/widgets/binding.dart
[38;5;244m#15     RendererBinding._handlePersistentFrameCallback[39;49m 
 package:flutter/…/rendering/binding.dart
[38;5;244m#16     SchedulerBinding._invokeFrameCallback[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#17     SchedulerBinding.handleDrawFrame[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#18     SchedulerBinding._handleDrawFrame[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#22     _invoke  (dart:ui/hooks.dart:253:10)[39;49m
[38;5;244m#23     _drawFrame  (dart:ui/hooks.dart:211:3)[39;49m
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: RenderSliverList#12c61 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#9b035] ←
    Semantics ← _PointerListener ← Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#92784] ← _PointerListener ← Listener
    ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 1538.0, remainingPaintExtent: 896.0, crossAxisExtent: 414.0, crossAxisDirection:
    AxisDirection.right, viewportMainAxisExtent: 896.0, remainingCacheExtent: 1396.0, cacheOrigin:
    -202.0)
  geometry: SliverGeometry(scrollExtent: 2400.0, paintExtent: 862.0, maxPaintExtent: 2400.0,
    hasVisualOverflow: true, cacheExtent: 1064.0)
  currently live children: 1 to 1
This RenderObject had the following descendants (showing up to depth 5):
    child with index 1: RenderIndexedSemantics#ed858 relayoutBoundary=up3
      child: RenderRepaintBoundary#d1896 relayoutBoundary=up4
        child: RenderConstrainedBox#c1d80 relayoutBoundary=up5
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: NoSuchMethodError: The method '-' was called on null.

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
The method '-' was called on null.
Receiver: null
Tried calling: -(1538.0)
[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mListView[39;49m 
 lib/main.dart
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: NoSuchMethodError: The method '-' was called on null.

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
The method '-' was called on null.
Receiver: null
Tried calling: -(1538.0)
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (1 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.0

• No issues found!

```

</details>

**Comment by Kavantix** [comment]
[These lines](https://github.com/flutter/flutter/blob/51fa704642774c6b6ae64c91642b62801e233e1b/packages/flutter/lib/src/rendering/sliver_list.dart#L96-L112) (especially the migrated version) shows clearly why this might happen.
`childAfter` will return `null` when there is no next child so if no child has a layoutOffset the `while` will always crash since it is assuming `earliestUsefulChild` cannot be `null`.
And when this happens it will also mean that `firstChild` will be `null` so the assert at the end of the block will also fail.

However, in the case of this example it does not really make sense that there would be no child with a layoutOffset (since the child with the key should be kept), indicating there might be an underlying bug in the childmanager perhaps

**Comment by xu-baolin** [comment]
I have posted a PR to fix this issue and I will add the test cases as soon as possible.

**Comment by Piinks** [comment]
Thanks @xu-baolin! @chunhtai may also have some thoughts here as well. :)
