### ISSUE TITLE
flutter tool crashes on 'flutter upgrade'; NoSuchMethodError: method not found: 'length'

### ISSUE THREAD

**Issue by joeblew99** [flutter/flutter#6621]
## Steps to Reproduce
flutter upgrade

## command

flutter upgrade

## exception

The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []

```
dart:core                                                         Object.noSuchMethod
package:flutter_tools/src/version.dart 110                        _shortGitRevision
package:flutter_tools/src/version.dart 56                         FlutterVersion.engineRevisionShort
package:flutter_tools/src/version.dart 64                         FlutterVersion.toString
package:flutter_tools/src/commands/upgrade.dart 70                UpgradeCommand.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 83                    runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/commands/upgrade.dart 86                UpgradeCommand.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 83                    runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/upgrade.dart                   UpgradeCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 150         FlutterCommand.verifyThenRunCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 184                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 117         FlutterCommand.run
package:args/command_runner.dart 177                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 130                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 186  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 71                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 104                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 104                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 132  FlutterCommandRunner.run
package:flutter_tools/executable.dart 97                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 91                          main.<async>
```

## flutter doctor

```
encountered exception: The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []

#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _shortGitRevision (package:flutter_tools/src/version.dart:110)
#3      FlutterVersion.engineRevisionShort (package:flutter_tools/src/version.dart:56)
#4      _FlutterValidator.validate.<validate_async_body> (package:flutter_tools/src/doctor.dart:212)
#5      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#6      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#7      StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125)
#8      _rootRun (dart:async/zone.dart:1146)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#12     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:206)
#13     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```
x-MacBook-Pro:md apple$

**Comment by eseidelGoogle** [comment]
@danrubel 

To work around this, you can go to your flutter sdk location and run `git pull --rebase` to update it manually.

**Comment by joeblew99** [comment]
I tried your technique now and it also worked. I usually just punch the "flutter upgrade" twice when it breaks.


````

x-MacBook-Pro:md apple$ cd /usr/local/flutter/flutter/bin
x-MacBook-Pro:bin apple$ ls
cache		flutter		flutter.bat	flutter.ps1	internal
x-MacBook-Pro:bin apple$ git status
On branch alpha
Your branch is up-to-date with 'origin/alpha'.
nothing to commit, working tree clean
x-MacBook-Pro:bin apple$ git pull --rebase
remote: Counting objects: 114, done.
remote: Total 114 (delta 82), reused 82 (delta 82), pack-reused 31
Receiving objects: 100% (114/114), 15.06 KiB | 0 bytes/s, done.
Resolving deltas: 100% (90/90), completed with 51 local objects.
From https://github.com/flutter/flutter
   bed0300..438f4df  alpha      -> origin/alpha
   5f57d87..16ce090  master     -> origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded alpha to 438f4df00c64c304d037b7cf3d6678199816ab18.
x-MacBook-Pro:bin apple$ flutter doctor
Downloading Dart SDK 1.21.0-dev.2.0...
######################################################################## 100.0%
Building flutter tool...
Downloading package sky_engine...                    1230ms
Running 'pub get' in sky_engine...                   422ms
Building Dart SDK summary...                         1894ms
Downloading engine artifacts android-arm...          13947ms
Downloading engine artifacts android-arm-profile...  13190ms
Downloading engine artifacts android-arm-release...  10703ms
Downloading engine artifacts android-x64...          8100ms
Downloading engine artifacts android-x86...          8542ms
Downloading engine artifacts ios...                  16286ms
Downloading engine artifacts ios-profile...          15370ms
Downloading engine artifacts ios-release...          14291ms
Downloading darwin-x64 tools...                      33436ms
Downloading android-arm-profile/darwin-x64 tools...  3120ms
Downloading android-arm-release/darwin-x64 tools...  7900ms
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /usr/local/flutter/flutter
    • Framework revision 438f4df00c (15 hours ago), 2016-11-01 09:20:52
    • Engine revision 63e71803de
    • Tools Dart version 1.21.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38

[✓] Connected devices
    • None
x-MacBook-Pro:bin apple$ flutter doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /usr/local/flutter/flutter
    • Framework revision 438f4df00c (15 hours ago), 2016-11-01 09:20:52
    • Engine revision 63e71803de
    • Tools Dart version 1.21.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38

[✓] Connected devices
    • None
x-MacBook-Pro:bin apple$ flutter upgrade
Switching to from alpha to master...
Upgrading Flutter from /usr/local/flutter/flutter...
Updating 438f4df..16ce090
 25 files changed, 103 insertions(+), 246 deletions(-)
Running 'pub get' in flutter...                      953ms
Building unlinked bundles for flutter...             2538ms
Running 'pub get' in flutter_driver...               825ms
Building unlinked bundles for flutter_driver...      115ms
Running 'pub get' in flutter_markdown...             829ms
Building unlinked bundles for flutter_markdown...    54ms
Running 'pub get' in flutter_test...                 830ms
Building unlinked bundles for flutter_test...        104ms
Building unlinked bundles for flutter_tools...       445ms
Running 'pub get' in flutter_services...             532ms
Building unlinked bundles for flutter_services...    54ms
Building unlinked bundles for sky_engine...          29ms
Running 'pub get' in sky_services...                 462ms
Building unlinked bundles for sky_services...        287ms

Upgrading engine...
Building flutter tool...
Already up-to-date.

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 16ce090fde (4 hours ago) • 2016-11-01 20:34:36
Engine • revision 63e71803de
Tools • Dart 1.21.0-dev.2.0

Running flutter doctor...
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /usr/local/flutter/flutter
    • Framework revision 16ce090fde (4 hours ago), 2016-11-01 20:34:36
    • Engine revision 63e71803de
    • Tools Dart version 1.21.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-24, build-tools 24.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.38

[✓] Connected devices
    • None


`````

**Comment by eseidelGoogle** [comment]
Still a bug in `flutter upgrade` we need to fix.  Thanks again for the report!  We'll hold this open for a bit yet.

**Comment by joeblew99** [comment]
ok. sweet ...

**Comment by Hixie** [comment]
Leaving this in current milestone since this could affect all our users? I don't understand what the trigger for this crash is.

**Comment by Hixie** [comment]
By inspection, we determined this crash is no longer possible.
