### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by Wasth** [flutter/flutter#66249]
## Command
```
flutter update-packages
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: Permission denied, errno = 13
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#2      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#3      PubDependencies.isUpToDate (package:flutter_tools/src/cache.dart:654:58)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:466:26)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:936:27)
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:844:33)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _runZoned (dart:async/zone.dart:1630:10)
#12     runZoned (dart:async/zone.dart:1550:10)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:833:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:333:21)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.269 at /opt/flutter
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /opt/android-sdk
      but Android SDK not found at this location.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by pedromassangocode** [comment]
Cc @DanTup I think this may be related to https://github.com/flutter/flutter/issues/15198

**Comment by Wasth** [comment]
I don't think so. Problem is that flutter dart uses /root/.pub_cache folder instead of current user's pub_cache folder. I run `flutter doctor` as non-root user.

**Comment by DanTup** [comment]
In #15198, the VS Code validator was blindly calling `existsSync()` on folders to see if they have VS Code which could result in permissions errors and it was valid/correct to ignore them if there is no access.

Here, it seems like there's no access to the pub cache - so I don't think silently ignoring the failure is the right fix - the question is where is the cache and why is there no access to it.

@Wasth 

> flutter dart uses /root/.pub_cache folder instead of current user's pub_cache folder

My expectation would be that if you use the zip file version, it would use a pub cache inside Flutter's own `cache` folder, but otherwise fall back to Pub's standard default. Where are you seeing `/root/` being used?

**Comment by Wasth** [comment]
In exception output. I installed flutter-git package from AUR(I'm using Manjaro). I changed all permissons in dart-sdk folder, flutter folder but anyway it tries to get access in root pub cache folder. I think I should close this issue because I reinstalled flutter through IDEA(with Flutter plugin) and it's worked

Thanks for helping!
