### ISSUE TITLE
[File_Picker] I am trying to upload files on flutter web.Found these errors.

### ISSUE THREAD

**Issue by asknishant** [flutter/flutter#66248]
**Issue**
I made an iconbutton and inside onpressed i called pickandLoadFile() method.The windows file explorer opens but when i select a file[doc,pdf,jpg] i get these errors.

Error: Unsupported operation: Unsupported on Web
    at Object.throw_ [as throw] (http://localhost:59763/dart_sdk.js:4328:11)
    at MappedListIterable.new.<anonymous> (http://localhost:59763/packages/file_picker/src/file_picker_result.dart.lib.js:31:75)
    at MappedListIterable.new.elementAt (http://localhost:59763/dart_sdk.js:21541:25)
    at ListIterator.new.moveNext (http://localhost:59763/dart_sdk.js:21335:55)
    at JsIterator.next (http://localhost:59763/dart_sdk.js:5997:21)
    at Function.from (http://localhost:59763/dart_sdk.js:43902:20)
    at Function.of (http://localhost:59763/dart_sdk.js:43917:30)
    at MappedListIterable.new.toList (http://localhost:59763/dart_sdk.js:21141:26)
    at file_picker_result.FilePickerResult.new.get paths [as paths] (http://localhost:59763/packages/file_picker/src/file_picker_result.dart.lib.js:31:177)
    at upload_file._FileUploadState.new.pickandLoadFile (http://localhost:59763/packages/aztlan/components/file_upload/upload_file.dart.lib.js:178:54)
    at pickandLoadFile.next (<anonymous>)
    at http://localhost:59763/dart_sdk.js:37593:33
    at _RootZone.runUnary (http://localhost:59763/dart_sdk.js:37447:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:59763/dart_sdk.js:32424:29)
    at handleValueCallback (http://localhost:59763/dart_sdk.js:32971:49)
    at Function._propagateToListeners (http://localhost:59763/dart_sdk.js:33009:17)
    at _Future.new.[_completeWithValue] (http://localhost:59763/dart_sdk.js:32852:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:59763/dart_sdk.js:32874:35)
    at Object._microtaskLoop (http://localhost:59763/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:59763/dart_sdk.js:37714:13)
    at http://localhost:59763/dart_sdk.js:33226:9

**Here is the minimal code**

`List<File> files;
  PlatformFile file;
  FilePickerResult result;

 
  
  Future pickandLoadFile() async { 
    result = await FilePicker.platform.pickFiles(
      allowMultiple: true,
      type: FileType.custom,
      allowedExtensions: ['jpg', 'pdf', 'doc'],
    );`
`

    if(result != null) {
     files = result.paths.map((path) => File(path));
    } else {
      print("Pick a file");
    }`

    if(result != null) {
      file = result.files.first;
      
      print(file.name);
      print(file.bytes);
      print(file.size);
      print(file.extension);
      print(file.path);
    }
  }'

**Comment by darshankawar** [comment]
Hi @asknishant,
`file_picker` is a 3rd party plugin. Please consider opening this issue in plugin owner's repo : https://github.com/miguelpruivo/flutter_file_picker/issues
Closing this, as it doesn't seem to be an issue with Flutter, since the error says `Error: Unsupported operation: Unsupported on Web`.
If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by asknishant** [comment]
Thanks for answering @darshankawar.
