### ISSUE TITLE
[NNBD] Null check operator used on a null value in scroll_position.dart

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#66250]
## Description

When using `flutter_swiper` after upgrading Flutter to latest master, I'm seeing the following error in the logs:

<details>
<summary>Error logs</summary>

```
I/flutter (14190): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14190): The following _CastError was thrown building PageIndicator(dirty, state: _PageIndicatorState#8072d):
I/flutter (14190): Null check operator used on a null value
I/flutter (14190): 
I/flutter (14190): The relevant error-causing widget was:
I/flutter (14190):   PageIndicator
I/flutter (14190):   file:///<elided>/pub.dartlang.org/flutter_swiper-1.1.6/lib/src/swiper_pagination.dart:188:18
I/flutter (14190): 
I/flutter (14190): When the exception was thrown, this was the stack:
I/flutter (14190): #0      ScrollPosition.maxScrollExtent (package:flutter/src/widgets/scroll_position.dart:141:49)
I/flutter (14190): #1      TransformerPageController.realPage (package:transformer_page_view/transformer_page_view.dart:149:20)
I/flutter (14190): #2      TransformerPageController.page (package:transformer_page_view/transformer_page_view.dart:182:11)
I/flutter (14190): #3      _PageIndicatorState._createPainer (package:flutter_page_indicator/flutter_page_indicator.dart:235:39)
I/flutter (14190): #4      _PageIndicatorState.build (package:flutter_page_indicator/flutter_page_indicator.dart:259:18)
I/flutter (14190): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4758:27)
I/flutter (14190): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4641:15)
I/flutter (14190): #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4813:11)
I/flutter (14190): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4335:5)
I/flutter (14190): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4620:5)
I/flutter (14190): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4804:11)
I/flutter (14190): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4615:5)
I/flutter (14190): ...     Normal element mounting (13 frames)
I/flutter (14190): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (14190): #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6248:32)
I/flutter (14190): ...     Normal element mounting (15 frames)
I/flutter (14190): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (14190): #41     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6248:32)
I/flutter (14190): ...     Normal element mounting (31 frames)
I/flutter (14190): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (14190): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:3346:18)
I/flutter (14190): #74     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:138:18)
I/flutter (14190): #75     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2696:19)
I/flutter (14190): #76     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:118:12)
I/flutter (14190): #77     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1883:59)
I/flutter (14190): #78     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
I/flutter (14190): #79     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1883:14)
I/flutter (14190): #80     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:227:7)
I/flutter (14190): #81     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:353:5)
I/flutter (14190): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #83     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
I/flutter (14190): #84     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498:7)
I/flutter (14190): #85     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
I/flutter (14190): #86     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
I/flutter (14190): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #91     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1306:11)
I/flutter (14190): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #106    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #122    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #123    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #124    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3220:13)
I/flutter (14190): #125    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #126    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #127    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #128    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:714:15)
I/flutter (14190): #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #130    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #132    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #133    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #134    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #135    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #137    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #138    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #139    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #140    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (14190): #141    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (14190): #142    RenderView.performLayout (package:flutter/src/rendering/view.dart:167:14)
I/flutter (14190): #143    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (14190): #144    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter (14190): #145    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:435:19)
I/flutter (14190): #146    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:907:13)
I/flutter (14190): #147    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:301:5)
I/flutter (14190): #148    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (14190): #149    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (14190): #150    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (14190): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (14190): 
I/flutter (14190): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

https://github.com/best-flutter/flutter_swiper/issues/227
https://github.com/flutter/flutter/pull/65528
https://github.com/flutter/flutter/pull/65861

Found that the culprit of that exception is the [following function](https://github.com/best-flutter/transformer_page_view/blob/8d44c4df6f0375bd2ac59bc1e8084a42e1cdb704/lib/transformer_page_view.dart#L146-L155) from the plugin:

```dart
  double get realPage {
    double page;
    if (position.maxScrollExtent == null || position.minScrollExtent == null) {
      page = 0.0;
    } else {
      page = super.page;
    }

    return page;
  }
```

https://github.com/flutter/flutter/blob/51fa704642774c6b6ae64c91642b62801e233e1b/packages/flutter/lib/src/widgets/scroll_position.dart#L141

More specifically, the exception happens when `position` is `null`. Not really sure on how that `position` can be `null`, but after re-building the same widget, the exception is gone (maybe the controller/scroll is now attached?).

## Sample code

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_page_indicator/flutter_page_indicator.dart';
import 'package:flutter_swiper/flutter_swiper.dart';

void main() => runApp(const ErrorScreen());

class ErrorScreen extends StatefulWidget {
  const ErrorScreen();

  @override
  _ErrorScreenState createState() => _ErrorScreenState();
}

class _ErrorScreenState extends State<ErrorScreen> {
  SwiperController _swiperController;

  @override
  void initState() {
    super.initState();
    _swiperController = SwiperController();
  }

  @override
  void dispose() {
    _swiperController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Swiper(
        controller: _swiperController,
        indicatorLayout: PageIndicatorLayout.SLIDE,
        loop: false,
        pagination: const SwiperPagination(
          builder: DotSwiperPaginationBuilder(),
        ),
        itemCount: 3,
        itemBuilder: (BuildContext context, int index) {
          return const Placeholder();
        },
      ),
    );
  }
}
```

Also, add the following line to `pubspec.yaml`:
```yaml
  flutter_swiper: ^1.1.6
```

</details>

### Flutter doctor

```
Flutter 1.22.0-10.0.pre.269 • channel master • https://github.com/flutter/flutter.git
Framework • revision 51fa704642 (2 days ago) • 2020-09-19 11:27:04 -0700
Engine • revision 4b8477d115
Tools • Dart 2.10.0 (build 2.10.0-142.0.dev)
```

cc/ @a14n for nnbd migration

**Comment by a14n** [comment]
Sorry about that.

During the widget migration we decided to make `maxScrollExtent` and `minScrollExtent` non-nullable because it is almost always non-null. Code that rely on checking the nullity of those properties should now relies on the new getter `hasContentDimensions`. The above function should be updated as:

```dart
  double get realPage {
    double page;
    if (!position.hasContentDimensions) {
      page = 0.0;
    } else {
      page = super.page;
    }

    return page;
  }
```

Let me know if it fixes the issue.

**Comment by Zazo032** [comment]
Thanks @a14n, that change fixed the issue. I opened a PR to fix it in the plugin.

**Comment by samariotorres** [comment]
Is this also the case for some firebase methods?

For example, the following stream also throws errors,
`
Stream<String> get authStateChanges => firebaseAuth.authStateChanges().map(
        (User user) => user?.uid,
      );
`

**Comment by viciainc** [comment]
So I edited scrollposition.dart package

from line 133
@override
  //double get minScrollExtent => _minScrollExtent!;
  // double? _minScrollExtent;
  double get minScrollExtent {
    if (_minScrollExtent == null) {
      _minScrollExtent = 0.0;
    }
    return double.parse(_minScrollExtent.toString());
  }

  double? _minScrollExtent;

  @override
  // double get maxScrollExtent => _maxScrollExtent!;
  // double? _maxScrollExtent;
  double get maxScrollExtent {
    if (_maxScrollExtent == null) {
      _maxScrollExtent = 0.0;
    }
    return double.parse(_maxScrollExtent.toString());
  }

  double? _maxScrollExtent;

**Comment by exeptionerror** [comment]
[[Solved] Null check operator used on a null value](https://fluttercorner.com/null-check-operator-used-on-a-null-value/)
