### ISSUE TITLE
Flaky crash in ShellTest.OnPlatformViewDestroyDisablesThreadMerger on Mac Host Engine

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#66265]
See https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/6905

```
[ RUN      ] ShellTest.OnPlatformViewDestroyDisablesThreadMerger


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Traceback (most recent call last):
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 498, in <module>
    sys.exit(main())
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 468, in main
    RunCCTests(build_dir, engine_filter)
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 136, in RunCCTests
    RunEngineExecutable(build_dir, 'shell_unittests', filter, shuffle_flags)
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 94, in RunEngineExecutable
    RunCmd(test_command, cwd=cwd)
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 47, in RunCmd
    raise Exception('Command "%s" exited with code %d' % (command_string, process.returncode))
Exception: Command "/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/shell_unittests --gtest_shuffle --gtest_repeat=2" exited with code -11
```

P0 because the tree is closed on this flake.

**Comment by zanderso** [comment]
@blasten

**Comment by chinmaygarde** [comment]
Build 6907 should address the tree closure.

**Comment by blasten** [comment]
The tree should be green now. https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/6907?

I will decrease the priority and keep this bug open until there's more cases like this.

**Comment by zanderso** [comment]
I think we haven't seen this one in a while, so I'm going to close it as stale.

**Comment by dnfield** [comment]
I am able to reproduce this locally with `cpulimit` FWIW. e.g.

```
cpulimit -l 20 out/host_debug_unopt/shell_unittests --gtest_filter=ShellTest.OnPlatformViewDestroyDisablesThreadMerger
[INFO:test_timeout_listener.cc(76)] Test timeout of 30 seconds per test case will be enforced.
Note: Google Test filter = ShellTest.OnPlatformViewDestroyDisablesThreadMerger
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ShellTest
[ RUN      ] ShellTest.OnPlatformViewDestroyDisablesThreadMerger
../../flutter/shell/common/shell_unittests.cc:793: Failure
Value of: result.ok()
  Actual: false
Expected: true
[ERROR:flutter/fml/memory/thread_checker.h(61)] IsCreationThreadCurrent expected thread: '????' actual thread:''
[FATAL:flutter/fml/memory/weak_ptr.h(262)] Check failed: (checker_.checker).IsCreationThreadCurrent(). 
[ERROR:flutter/fml/backtrace.cc(118)] Caught signal SIGABRT during program execution.
Frame 0: 0x7fff205ad411 abort
Frame 1: 0x10c253fc9 fml::KillProcess()
Frame 2: 0x10c253f86 fml::LogMessage::~LogMessage()
Frame 3: 0x10c253ff3 fml::LogMessage::~LogMessage()
Frame 4: 0x10c0ababd fml::WeakPtrFactory<flutter::Shell>::CheckThreadSafety() const
Frame 5: 0x10c0ab9b7 fml::WeakPtrFactory<flutter::Shell>::~WeakPtrFactory()
Frame 6: 0x10c06d643 fml::WeakPtrFactory<flutter::Shell>::~WeakPtrFactory()
Frame 7: 0x10c06cbc7 flutter::Shell::~Shell()
Frame 8: 0x10c06d783 flutter::Shell::~Shell()
Frame 9: 0x10bb8cfa9 std::__1::default_delete<flutter::Shell>::operator()(flutter::Shell*) const
Frame 10: 0x10bb8ceaa std::__1::unique_ptr<flutter::Shell, std::__1::default_delete<flutter::Shell> >::reset(flutter::Shell*)
Frame 11: 0x10bb8ce17 std::__1::unique_ptr<flutter::Shell, std::__1::default_delete<flutter::Shell> >::~unique_ptr()
Frame 12: 0x10bb842a3 std::__1::unique_ptr<flutter::Shell, std::__1::default_delete<flutter::Shell> >::~unique_ptr()
Frame 13: 0x10bd961c5 flutter::testing::ShellTest_OnPlatformViewDestroyDisablesThreadMerger_Test::TestBody()
Frame 14: 0x10e66a609 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
Frame 15: 0x10e642715 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
Frame 16: 0x10e642631 testing::Test::Run()
Frame 17: 0x10e6433c2 testing::TestInfo::Run()
Frame 18: 0x10e6444c9 testing::TestSuite::Run()
Frame 19: 0x10e64f6eb testing::internal::UnitTestImpl::RunAllTests()
Frame 20: 0x10e6710d9 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
Frame 21: 0x10e64f295 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)
Frame 22: 0x10e64f12a testing::UnitTest::Run()
Frame 23: 0x10e49cad3 RUN_ALL_TESTS()
Frame 24: 0x10e49c9e3 main
Frame 25: 0x7fff20673f3d start
Frame 26: 0x2 Unknown
```
consistently repros for me.

**Comment by dnfield** [comment]
Re-opening while I investigate...

**Comment by dnfield** [comment]
(I need to use a lower value than 20 to make it repro more consistently, sometimes at 20% it doesn't quite repro)

**Comment by dnfield** [comment]
Problem seems to be that we wait for 1 second and assert that that was enough time to complete the first frame, which is not true if the CPU is sufficiently bogged down.

**Comment by zanderso** [comment]
Thanks, Dan. Timeouts like that are usually not allowed by our style guide, and we should figure out how to remove them.
