### ISSUE TITLE
Local network permission issue on iPad, crash on launch

### ISSUE THREAD

**Issue by SteveAlexander** [flutter/flutter#66280]
@jmagman, following up from https://github.com/flutter/flutter/issues/57225

Steps to reproduce:

1. `flutter create testproject3`
2. `cd testproject 3`
3. `flutter run -v > output_1.txt`

The app runs on the iPad, and presents the "testproject3 would like to find and connect to devices on your local network" dialog. The app then crashes (disappears from screen), leaving the dialog still there.

stderr output:

```text
testproject3$ flutter run -v > output_1.txt
[        ] Failed to attach to the observatory.
[   +2 ms] Try accepting the local network permissions popup, or enable "Settings > Privacy > Local Network" for your app.
[        ] For more information, see https://flutter.dev/docs/development/ios-14#debugging-flutter
[        ] Error launching application on Stephen’s iPad.
[   +5 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:606:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:985:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

stdout output attached as `output_1.txt`
[output_1.txt](https://github.com/flutter/flutter/files/5257450/output_1.txt)

Other things happen if I run again, or if I erase the app from the iPad, and run again. But maybe this is enough for now?

Please let me know if I can provide anything else useful.

```text
$ flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.270, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.270 at /Users/steve/code/flutter
    • Framework revision 36a6ef6486 (10 minutes ago), 2020-09-21 11:02:30 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1


[✓] Connected device (1 available)
    • Stephen’s iPad (mobile) • b0975f3aa3ebe98c71462a866b0356a629fc6aa3 • ios • iOS 14.0
    ! Error: Stephen’s iPad is busy: Copying cache files from device. Xcode will continue when Stephen’s iPad is finished. (code -10)

• No issues found!
```

**Comment by Calamity210** [comment]
> Try accepting the local network permissions popup, or enable "Settings > Privacy > Local Network" for your app.

Have you tried this at all?

**Comment by jmagman** [comment]
Oh the app is crashing, that's why the observatory isn't found.  The `Try accepting the local network permissions popup` comment is just confusing in this spot.

Can you attach the crash log from the device?

**Comment by SteveAlexander** [comment]
It doesn't look like a crash log was produced. I'm looking in Xcode under "view device logs" in "devices and simulators". There are other crash logs here (e.g. one from Skype, looks like it was terminated for using too much CPU when backgrounded).

I tried reproducing the behaviour while viewing the console to see what's going on there. This time (starting by creating a new test project with a different name) the app launched. However, the observatory never attached.

I tried a couple more times, and I have not been able to reproduce the crash on launch.

**Comment by jmagman** [comment]
@SteveAlexander Now that the app doesn't crash on launch (weird there's no log), do you see `Settings > Privacy > Local Network` now?  Is it checked?

**Comment by SteveAlexander** [comment]
@jmagman I appreciate you following up on this. Here's what I see with the latest master (1.22.0-10.0.pre.318).

Summary: default app crashes, permission setting is available but doesn't seem to do anything useful.

First, I create a new project. I'm using new names for each project to ensure there is no interference from previous state on my iPad.

```text
$ flutter create testproject8
...
All done!
[✓] Flutter: is fully installed. (Channel master, 1.22.0-10.0.pre.318, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 12.0)
[✓] Android Studio: is fully installed. (version 4.0)
[✓] VS Code: is fully installed. (version 1.49.1)
[✓] Connected device: is fully installed. (1 available)
```

`$ cd testproject8/`

`flutter run -v > >(tee -a stdout.log) 2> >(tee -a stderr.log >&2)`

The usual stuff happens. The app appears on the iPad homescreen. The app launches. The app displays the "In iOS14+, ..." message. Meanwhile the `flutter run` command has exited.

[stdout.log](https://github.com/flutter/flutter/files/5268463/stdout.log)
[stderr.log](https://github.com/flutter/flutter/files/5268465/stderr.log)

I open the Settings app on the iPad and look under Privacy, Local Network. No app is visible for me to allow local network access. There is no crash log for this app available via Xcode.


```text
$ flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.318, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.318 at /Users/steve/code/flutter
    • Framework revision 6b39acdc53 (62 minutes ago), 2020-09-23 08:27:04 -0400
    • Engine revision 3e7ca5b869
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Stephen’s iPad (mobile) • b0975f3aa3ebe98c71462a866b0356a629fc6aa3 • ios • iOS 14.0
    ! Error: Stephen’s iPad is busy: Copying cache files from device. Xcode will continue when Stephen’s iPad is finished. (code -10)

• No issues found!
```

**Comment by TahaTesser** [comment]
Looks like it's just not iPad, happens on iPhone as well https://github.com/flutter/flutter/issues/66408

**Comment by tatsuyuki25** [comment]
This error message may be the cause.
`Error: Stephen’s iPad is busy: Copying cache files from device. Xcode will continue when Stephen’s iPad is finished. (code -10)`

**Comment by jmagman** [comment]
You see a `In iOS 14+, Flutter application in debug mode can only be launched from Flutter tooling` message from `flutter run`?  That's definitely unexpected, it should only show up when you launch it manually on the device from the home screen or a notification.

Your original report says 
> The app runs on the iPad, and presents the "testproject3 would like to find and connect to devices on your local network" dialog. The app then crashes (disappears from screen), leaving the dialog still there.

So it's not crashing anymore, it just sits on the error message?  I wouldn't expect the permissions pop up to happen when it's sitting on that message.

What happens when you run `ios/Runner.xcworkspace` from Xcode?

**Comment by SteveAlexander** [comment]
Running from Xcode, the app launches with a blank white screen, and the iOS dialog "testproject9 would like to find and connect to devices on your local network"

I press "OK" and then the app fully launches.

In the output window of Xcode is the following:

```text
2020-09-24 12:20:41.808173+0200 Runner[4478:1907931] Metal API Validation Enabled
2020-09-24 12:20:42.338640+0200 Runner[4478:1908359] flutter: Observatory listening on http://127.0.0.1:49305/u3r3W6zN1P8=/
2020-09-24 12:21:33.790822+0200 Runner[4478:1908352] fopen failed for data file: errno = 2 (No such file or directory)
2020-09-24 12:21:33.790937+0200 Runner[4478:1908352] Errors found! Invalidating cache...
2020-09-24 12:21:33.918937+0200 Runner[4478:1908352] fopen failed for data file: errno = 2 (No such file or directory)
2020-09-24 12:21:33.919056+0200 Runner[4478:1908352] Errors found! Invalidating cache...
```

**Comment by SteveAlexander** [comment]
Immediately after this, I stopped the app from Xcode, closed Xcode, and tried again with `flutter run`

I got the following terminal output, and the app launches with the "In iOS 14+, Flutter application in debug mode..." message.

```text
$ flutter run
Launching lib/main.dart on Stephen’s iPad in debug mode...

Automatically signing iOS for device deployment using specified development team in Xcode project: RPX9H7TNPD
Running Xcode build...
 └─Compiling, linking and signing...                         9.2s
Xcode build done.                                           14.7s
Failed to attach to the observatory.
Try accepting the local network permissions popup, or enable "Settings > Privacy > Local Network" for your app.
For more information, see https://flutter.dev/docs/development/ios-14#debugging-flutter
Installing and launching...                                        28.3s
Error launching application on Stephen’s iPad.
```

**Comment by jmagman** [comment]
That's really odd.
```
[  +23 ms] (lldb)     run
[  +85 ms] success
[        ] Application launched on the device. Waiting for observatory port.
```
`flutter` attached the debugger, so it should never show that "In iOS 14+" error message.  It's not surprising the observatory isn't connecting at that point though.

Would you mind opening the Console app, selecting your app, and reproducing the problem, and attaching any `Runner` logs?  Not sure why the engine thinks it can't run ptrace.
<img width="945" alt="Screen Shot 2020-09-24 at 7 08 08 PM" src="https://user-images.githubusercontent.com/682784/94218407-4936c900-fe99-11ea-9cc5-2f5939c41f93.png">

**Comment by robwafle-scripd** [comment]
Hi All.  I am having this problem too.   FYI, my iPad has been busy copying files for 7 days now....  I've tried flutter clean multiple times.  Anyone have any solutions or workarounds?

flutter doctor --verbose
[✓] Flutter (Channel master, 1.22.0-10.0.pre.380, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.22.0-10.0.pre.380 at /Users/rob/dev/flutter
    • Framework revision ec40df9576 (17 hours ago), 2020-09-25 21:27:22 -0700
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rob/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    ! Error: CM2 is not connected. Xcode will continue when CM2 is connected. (code -13)

**Comment by jmagman** [comment]
`Try accepting the local network permissions popup` was just suggesting that it could possibly be a possible reason for a failure to connect to the observatory, but people took it literally.  I removed it here https://github.com/flutter/flutter/pull/66621.

**Comment by SteveAlexander** [comment]
I can no longer reproduce this problem with the latest Master, using a fresh project created with `flutter create`.

I first experienced problems when I was using packages that had native parts, using cocoapods. I'll try that again, and check.

```text
$ flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.428, on Mac OS X 10.15.6 19G2021 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.428 at /Users/steve/code/flutter
    • Framework revision a06f385145 (12 hours ago), 2020-09-29 21:37:04 -0400
    • Engine revision d18c3ea75c
    • Dart version 2.11.0 (build 2.11.0-178.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Stephen’s iPad (mobile) • b0975f3aa3ebe98c71462a866b0356a629fc6aa3 • ios • iOS 14.0.1

• No issues found!
```

**Comment by KoStard** [comment]
Hello, are there any updates for this? :)
