### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException "Existing VM service clients prevent DDS from taking control"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#66300]
flutter_gallery_sksl_warmup_ios32__transition_perf is marked flaky and failing 100% of the time in the devicelab, but I don't see an open issue.

## Command
```
flutter run --verbose --verbose-system-logs --profile --cache-sksl -d 822ef7958bba573829d85eef4df6cbdd86593730 -t test_driver/transitions_perf.dart --endless-trace-buffer --vmservice-out-file /Users/flutter/.cocoon/flutter/dev/integration_tests/flutter_gallery/vmservice.out
```

## Steps to Reproduce
flutter_gallery_sksl_warmup_ios32__transition_perf
 or flutter_gallery_sksl_warmup__transition_perf_e2e_ios32 in the devicelab

## Logs
[flutter_gallery_sksl_warmup__transition_perf_e2e_ios32_511367a_1.log](https://github.com/flutter/flutter/files/5258661/flutter_gallery_sksl_warmup__transition_perf_e2e_ios32_511367a_1.log)
[flutter_gallery_sksl_warmup_ios32__transition_perf_511367a_1.log](https://github.com/flutter/flutter/files/5258662/flutter_gallery_sksl_warmup_ios32__transition_perf_511367a_1.log)

DartDevelopmentServiceException
```
#0      _DartDevelopmentService._startDDSServer (package:dds/src/dds_impl.dart:68:7)
<asynchronous suspension>
#1      _DartDevelopmentService.startService (package:dds/src/dds_impl.dart:33:11)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:108:19)
<asynchronous suspension>
#3      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:40:55)
#4      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:227:26)
#5      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:221:43)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#13     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#18     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#19     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#21     _rootRun (dart:async/zone.dart:1182:47)
```
```
2020-09-21T15:45:02.260230: run stdout: [ +674 ms] [VERBOSE0:shell_io_manager.cc(24)] Cache SkSL
2020-09-21T15:45:02.549696: run stdout: [ +289 ms] [VERBOSE0:callback_cache.cc(134)] Could not parse callback cache, aborting restore
2020-09-21T15:45:02.717735: run stdout: [ +168 ms] [VERBOSE0:gpu_surface_gl.cc(53)] Cache SkSL
2020-09-21T15:45:02.754507: run stdout: [  +36 ms] [VERBOSE0:persistent_cache.cc(206)] No sksl asset found.
2020-09-21T15:45:02.951204: run stdout: [ +196 ms] [VERBOSE0:gpu_surface_gl.cc(90)] Found 14 SkSL shaders; precompiled 14
2020-09-21T15:45:03.426193: run stdout: [ +475 ms] [VERBOSE0:FlutterViewController.mm(951)] Timeout waiting for the first frame to render.  This may happen in unoptimized builds.  If this is a release build, you should load a less complex frame to avoid the timeout.
2020-09-21T15:45:11.912908: run stdout: [+8486 ms] Failed to connect directly, falling back to mDNS
...
2020-09-21T15:45:12.939855: run stdout: [   +1 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:55505/.
2020-09-21T15:45:13.032097: run stderr: [  +92 ms] Warning: Failed to start DDS: Existing VM service clients prevent DDS from taking control.
2020-09-21T15:45:13.034240: run stderr: 
2020-09-21T15:45:13.036859: run stderr: [   +4 ms] Oops; flutter has exited unexpectedly: "DartDevelopmentServiceException: Existing VM service clients prevent DDS from taking control.".
```
```
[✓] Flutter (Channel unknown, 1.22.0-10.0.pre.281, on Mac OS X 10.14.6 18G6020 x86_64, locale en-US)
    • Flutter version 1.22.0-10.0.pre.281 at /Users/flutter/.cocoon/flutter
    • Framework revision 511367aa5a (12 minutes ago), 2020-09-21 15:33:32 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/share/android-sdk
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    • ANDROID_HOME = /usr/local/share/android-sdk
    ✗ No valid Android SDK platforms found in /usr/local/share/android-sdk/platforms. Candidates were:
        - android-28
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode-11.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone (mobile)  • 822ef7958bba573829d85eef4df6cbdd86593730 • ios            • iOS 9.3.6
    • macOS (desktop)  • macos                                    • darwin-x64     • Mac OS X 10.14.6 18G6020 x86_64
    • Web Server (web) • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 77.0.3865.90

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: null
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-0.4.9+2
connectivity_for_web-0.3.1+2
connectivity_macos-0.1.0+5
device_info-0.4.2+7
e2e-0.7.0
url_launcher-5.7.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.3+2
url_launcher_windows-0.0.1+1
video_player-0.10.6
video_player_web-0.1.2+3

**Comment by jmagman** [comment]
@liyuqian did I miss an open issue for this?

**Comment by liyuqian** [comment]
https://github.com/flutter/flutter/issues/65258 was the old issue that had those tests marked as flaky. That issue got fixed, but unfortunately new types of failures as described in https://github.com/flutter/flutter/pull/65873#issuecomment-694657423 happened soon after to prevent me to unmark the flakiness.

I believe https://github.com/flutter/flutter/pull/65873#issuecomment-694657423 is the exact same failure that you noticed here. AFAIK, there's no issue filed for that specific failure but @bkonyi had a fix https://github.com/flutter/flutter/pull/66123 landed but soon reverted due to other issues. I think we can track the reland of that fix using this issue?

**Comment by bkonyi** [comment]
Fixed by https://github.com/flutter/flutter/pull/66377.
