### ISSUE TITLE
Widget Test Error: Unable to load asset: AssetManifest.json

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#66315]
I have `FlutterPackageA`, which contains a Widget that displays an asset image.

`FlutterPackageA` is used by `FlutterPackageB`, which utilizes the Widget with the asset image.

When I run a Widget test in `FlutterPackageB`, I get the following error related to the loading of that image. If I comment out that image Widget in `FlutterPackageA`, this error goes away.

I don't think this error occurs when running the app on a platform.

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following assertion was thrown while resolving an image:
Unable to load asset: AssetManifest.json

When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:225:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:68:33)
#2      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:167:18)
#3      CachingAssetBundle.loadStructuredData (package:flutter/src/services/asset_bundle.dart:188:5)
#4      AssetImage.obtainKey (package:flutter/src/painting/image_resolution.dart:176:18)
#5      ScrollAwareImageProvider.obtainKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:115:74)
#6      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:455:15)
#10     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:452:16)
#11     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:330:5)
#12     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1155:16)
#13     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1108:5)
#14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4729:12)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4544:5)
...     Normal element mounting (68 frames)
#83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3512:14)
#84     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6179:32)
...     Normal element mounting (45 frames)
#129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3512:14)
#130    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6179:32)
...     Normal element mounting (262 frames)
#392    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3512:14)
#393    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6179:32)
...     Normal element mounting (267 frames)
#660    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3512:14)
#661    Element.updateChild (package:flutter/src/widgets/framework.dart:3267:20)
#662    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
#663    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1230:5)
#664    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1244:7)
#665    Element.rebuild (package:flutter/src/widgets/framework.dart:4286:5)
#666    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2673:33)
#667    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1088:18)
#668    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#669    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#670    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#671    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:961:9)
#674    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#675    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:948:27)
#676    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:524:22)
#679    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#680    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:521:27)
#681    main.<anonymous closure>.<anonymous closure> (file:///Volumes/G-RAID/SuperDeclarative/SuperDeclarative_tools/superdeclarative_app_base/superdeclarative_app_base/test/gated_screens/gated_screens_test.dart:47:20)
#682    main.<anonymous closure>.<anonymous closure> (file:///Volumes/G-RAID/SuperDeclarative/SuperDeclarative_tools/superdeclarative_app_base/superdeclarative_app_base/test/gated_screens/gated_screens_test.dart:42:9)
#683    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
#694    FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:193:32)
#695    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1189:17)
#696    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1177:35)
(elided 32 frames from dart:async and package:stack_trace)

Image provider: ScrollAwareImageProvider<dynamic>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#29b1f(), devicePixelRatio: 3.0,
  locale: en_US, textDirection: TextDirection.ltr, platform: android)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter version:
```
Flutter 1.22.0-10.0.pre.9 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8fa5c55e54 (3 weeks ago) • 2020-08-30 19:05:20 -0700
Engine • revision 1e302a111d
Tools • Dart 2.10.0 (build 2.10.0-76.0.dev)
```

**Comment by matthew-carroll** [comment]
@chunhtai this looks like it might be related to some asset loading issues that you solved previously.

**Comment by matthew-carroll** [comment]
This was my fault.

The image only ever worked because the path of the image in `PackageA` happened to be exactly the same as an image in `PackageB`. The `Image.asset()` declaration was never correct.

I think what I was missing was an explicit package value in the `Image.asset()` constructor to specify that the image comes from `PackageA`.
