### ISSUE TITLE
iOS UiKitView Bug When a flutterView need to  be added above two Overlapped UiKitView

### ISSUE THREAD

**Issue by ahgdwang** [flutter/flutter#66333]
hi developer:

   I use two Overlapped uikitView to show a special animation, but when i use showModalBottomSheet to show BottomSheet, 
there are black blanks in the uikitView.
  I find When a flutterView need to  be added above two Overlapped UiKitView, the flutterView will be drawed twice, so the black blanks are made by drawing twice.Detail in the UI Capture.
  How Can i avoid this ? thanks
![企业微信截图_69c5be1a-17cd-4cd8-adfe-792c245d1ad7](https://user-images.githubusercontent.com/30438280/93864703-da6e3a00-fcf7-11ea-9c72-ac6efb630949.png)
![企业微信截图_5491c5bf-17e4-4a1b-9908-f37280177d39](https://user-images.githubusercontent.com/30438280/93864712-dd692a80-fcf7-11ea-91be-fb196d93a48c.png)

**Comment by darshankawar** [comment]
Hi @ahgdwang,
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by ahgdwang** [comment]
> Hi @ahgdwang,
> Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
> Thanks.

ok. flutter doctor - v
[✓] Flutter (Channel unknown, v1.17.2, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/onewang/Desktop/flutter/flutter
    • Framework revision 5f21edf8b6 (4 months ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3
simple code project is a zip can you give me a email?

**Comment by darshankawar** [comment]
@ahgdwang you seem to be on older version of Flutter. I'd suggest you upgrade to latest stable version (1.20.4) and try again to see if you still get the same issue ?
If issue persists, please create a minimal complete reproducible code sample, you may create a repo, upload all required code there and share the link here.
Thanks.

**Comment by ahgdwang** [comment]
> @ahgdwang you seem to be on older version of Flutter. I'd suggest you upgrade to latest stable version (1.20.4) and try again to see if you still get the same issue ?
> If issue persists, please create a minimal complete reproducible code sample, you may create a repo, upload all required code there and share the link here.
> Thanks.

hi darshankawar  i have upgrade the latest vesion, the problem  still exsists. 
this is flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)

the demo git : git@github.com:ahgdwang/flutterIssueTest.git 
you can directly open flutterAniTest.xcworkspace to run, and do like the picture
![企业微信截图_2c5bbb6d-6f54-498a-8115-ad9428ad4236](https://user-images.githubusercontent.com/30438280/93976684-e9162900-fdab-11ea-91d7-dcc6ee04e51e.png)

**Comment by darshankawar** [comment]
@ahgdwang I am unable to access the code link you shared above, seems incomplete. Please provide a full repo link that we can clone and run directly.

**Comment by ahgdwang** [comment]
> @ahgdwang I am unable to access the code link you shared above, seems incomplete. Please provide a full repo link that we can clone and run directly.

oh sorry . please try this git. 

the demo in a zip
 
 https://github.com/ahgdwang/flutterIssueTest

**Comment by darshankawar** [comment]
@ahgdwang I am trying to understand what's the actual  behavior ?
Are you trying to put a FlutterView on top of `UiKitView`, but the `UiKitView` seem to be always on top of FlutterView ?

**Comment by ahgdwang** [comment]
> @ahgdwang I am trying to understand what's the actual behavior ?
> Are you trying to put a FlutterView on top of `UiKitView`, but the `UiKitView` seem to be always on top of FlutterView ?

NO。There are two UIKitViews are overlaped, when i showModalBottomSheet ,the 
transparent part in the UIKitViews become black.
You can click the + button in demo to see the bug.

**Comment by darshankawar** [comment]
@ahgdwang The repo you provided isn't working. I tried to run the workspace, but getting below error:

<img width="867" alt="Screenshot 2020-09-24 at 11 23 19 AM" src="https://user-images.githubusercontent.com/67046386/94106150-6d25ea80-fe58-11ea-9d08-97fb719a3df4.png">

As requested, we need a complete reproducible code sample that we can simply copy paste and run in IDE which won't need to add any 3rd party plugins. You seem to have lottie plugin in your code. Please provide a complete code sample without 3rd party plugin that we can run directly without any additional setup / configuration.
Thanks. See [this](https://stackoverflow.com/help/minimal-reproducible-example) for how to provide a code sample.

**Comment by ahgdwang** [comment]
> @ahgdwang The repo you provided isn't working. I tried to run the workspace, but getting below error:
> 
> <img alt="Screenshot 2020-09-24 at 11 23 19 AM" width="867" src="https://user-images.githubusercontent.com/67046386/94106150-6d25ea80-fe58-11ea-9d08-97fb719a3df4.png">
> 
> As requested, we need a complete reproducible code sample that we can simply copy paste and run in IDE which won't need to add any 3rd party plugins. You seem to have lottie plugin in your code. Please provide a complete code sample without 3rd party plugin that we can run directly without any additional setup / configuration.
> Thanks. See [this](https://stackoverflow.com/help/minimal-reproducible-example) for how to provide a code sample.

e...you need cd to this directory and flutter pub get. Could you please? 3q
![企业微信截图_d0396fca-0589-42cb-a048-25c0010770b4](https://user-images.githubusercontent.com/30438280/94107633-77ec7980-fe70-11ea-892c-f847652c32e4.png)
![企业微信截图_e192f14d-2456-4ff2-9ea5-29a3dd4cf736](https://user-images.githubusercontent.com/30438280/94107639-7a4ed380-fe70-11ea-8fef-63a37958496e.png)

**Comment by darshankawar** [comment]
@ahgdwang getting below compile errors while trying to run:

```
   - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `flutter_lottie` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the
    `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:

```

**Comment by ahgdwang** [comment]
> @ahgdwang getting below compile errors while trying to run:
> 
> ```
>    - Running pre install hooks
>     [!] Unable to determine Swift version for the following pods:
> 
>     - `flutter_lottie` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the
>     `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
> 
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:590:in `validate_targets'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:158:in `install!'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
>     /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
>     /usr/local/bin/pod:23:in `load'
>     /usr/local/bin/pod:23:in `<main>'
> 
> Error output from CocoaPods:
> ```

oh, You need to add a user-define for swift as the pic shows.
![企业微信截图_cbe5ee2c-c867-4a2e-a56b-8d2a9f197207](https://user-images.githubusercontent.com/30438280/94222520-2e5b6780-ff20-11ea-9849-3b5a0688e62a.png)

**Comment by darshankawar** [comment]
@ahgdwang 
I've the setting already.

<img width="873" alt="Screenshot 2020-09-25 at 11 25 09 AM" src="https://user-images.githubusercontent.com/67046386/94231566-e3daea80-ff21-11ea-947f-9fc5d23cade5.png">

I'd suggest you provide a minimal code sample without any 3rd party plugins that we can re-use and run to see the issue.
Thanks.

**Comment by ahgdwang** [comment]
> @ahgdwang
> I've the setting already.
> 
> <img alt="Screenshot 2020-09-25 at 11 25 09 AM" width="873" src="https://user-images.githubusercontent.com/67046386/94231566-e3daea80-ff21-11ea-947f-9fc5d23cade5.png">
> 
> I'd suggest you provide a minimal code sample without any 3rd party plugins that we can re-use and run to see the issue.
> Thanks.

hi darshankawar, i have finished a simplest demo without any 3rd. 
you can get it in the git path : https://github.com/ahgdwang/flutterUIkitViewIssue
it still has the problem as the two pics show, you can do it in the demo to see it.
wait for your reply, 3Q

![351AA13AFEE844696790BB6F50AC7A34](https://user-images.githubusercontent.com/30438280/95488892-ad44ab80-09c8-11eb-9c2c-62a2f68259e7.png)
![AD8E2480CCA31813BEC84260D284A9FC](https://user-images.githubusercontent.com/30438280/95488905-b0d83280-09c8-11eb-988c-f835ccafa7a0.png)

**Comment by darshankawar** [comment]
@ahgdwang 
I cloned your repo and getting below exception while running:

`Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'com.flutter_to_native_test_imageview', null)`

**Comment by ahgdwang** [comment]
> @ahgdwang
> I cloned your repo and getting below exception while running:
> 
> `Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'com.flutter_to_native_test_imageview', null)`

oh sorry , i forget a file. you can git pull now to get the newest code.

do not forget flutter pub get in the Root directory, and open the ios/Runner.xcworkspace to run. 3q

**Comment by darshankawar** [comment]
@ahgdwang 
So I was finally able to run your project properly and see black area after tapping +. My question is, what should be the expected behavior in this case ?
Thanks.

**Comment by ahgdwang** [comment]
> @ahgdwang
> So I was finally able to run your project properly and see black area after tapping +. My question is, what should be the expected behavior in this case ?
> Thanks.

The expected behavior is: the black area should not exsit. 
I find When a flutterView need to be added above two Overlapped UiKitView, the flutterView will be drawed twice, so the black blanks are made by drawing twice modal bottom view on the two Uikitviews.

**Comment by darshankawar** [comment]
Per OP, I do see black area upon tapping `+`. Tested on latest master and on iPhone SE simulator.

<img width="366" alt="Screenshot 2020-10-09 at 7 14 36 PM" src="https://user-images.githubusercontent.com/67046386/95590523-c9e1f180-0a63-11eb-80a6-6fc19455a3d0.png">

<img width="373" alt="Screenshot 2020-10-09 at 7 14 46 PM" src="https://user-images.githubusercontent.com/67046386/95590534-ce0e0f00-0a63-11eb-827e-9ba70b44d79c.png">

Keeping this open for further analysis.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.221, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.23.0-8.0.pre.221 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 0d8d4f77aa (29 hours ago), 2020-10-08 09:26:30 +0200
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 4.4.2 (API 19) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac
      OS X 10.15.4 19E2269 x86_64
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 86.0.4240.75

• No issues found!

```

</details>

**Comment by ahgdwang** [comment]
> Per OP, I do see black area upon tapping `+`. Tested on latest master and on iPhone SE simulator.
> 
> <img alt="Screenshot 2020-10-09 at 7 14 36 PM" width="366" src="https://user-images.githubusercontent.com/67046386/95590523-c9e1f180-0a63-11eb-80a6-6fc19455a3d0.png">
> 
> <img alt="Screenshot 2020-10-09 at 7 14 46 PM" width="373" src="https://user-images.githubusercontent.com/67046386/95590534-ce0e0f00-0a63-11eb-827e-9ba70b44d79c.png">
> 
> Keeping this open for further analysis.
> 
> flutter doctor -v
> ```
> [✓] Flutter (Channel master, 1.23.0-8.0.pre.221, on Mac OS X 10.15.4 19E2269
>     x86_64, locale en-IN)
>     • Flutter version 1.23.0-8.0.pre.221 at
>       /Users/dhs/documents/Fluttersdk/flutter
>     • Framework revision 0d8d4f77aa (29 hours ago), 2020-10-08 09:26:30 +0200
>     • Engine revision 2eac514f26
>     • Dart version 2.11.0 (build 2.11.0-186.0.dev)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
>     • Android SDK at /Users/dhs/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.0
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.0.1, Build version 12A7300
>     • CocoaPods version 1.9.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 46.0.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.49.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.11.0
> 
> [✓] Connected device (4 available)
>     • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
>       Android 4.4.2 (API 19) (emulator)
>     • macOS (desktop)                    • macos         • darwin-x64     • Mac
>       OS X 10.15.4 19E2269 x86_64
>     • Web Server (web)                   • web-server    • web-javascript •
>       Flutter Tools
>     • Chrome (web)                       • chrome        • web-javascript •
>       Google Chrome 86.0.4240.75
> 
> • No issues found!
> ```

ok, look forward to your solution

**Comment by danagbemava-nc** [comment]
I can reproduce the issue on the latest versions of flutter using the code sample in https://github.com/ahgdwang/flutterUIkitViewIssue updated for the latest versions of flutter. 
Code sample zipped below


[first_flutter.zip](https://github.com/flutter/flutter/files/11321774/first_flutter.zip)

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/234257382-aadac24e-5c9e-4a85-828b-7534f12b1f30.mp4
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale en-GB)
    • Flutter version 3.7.12 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (7 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)    • adb-28291FDH2001SA-5Lv71w._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • M2007J20CG (mobile) • adb-5dd3be00-17AYzd._adb-tls-connect._tcp.       • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E                        • ios            • iOS 16.4.1 20E252
    • macOS (desktop)     • macos                                            • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)        • chrome                                           • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.10.0-12.0.pre.29, on macOS 13.3.1 22E261 darwin-arm64, locale en-GB)
    • Flutter version 3.10.0-12.0.pre.29 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 60077ff979 (2 days ago), 2023-04-23 07:09:16 -0400
    • Engine revision fcf46af2d3
    • Dart version 3.1.0 (build 3.1.0-35.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)    • adb-28291FDH2001SA-5Lv71w._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • M2007J20CG (mobile) • adb-5dd3be00-17AYzd._adb-tls-connect._tcp.       • android-arm64  • Android 12 (API 31)
    • Nexus (mobile)      • 00008020-001875E83A38002E                        • ios            • iOS 16.4.1 20E252
    • macOS (desktop)     • macos                                            • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)        • chrome                                           • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by vaHeidi** [comment]
I am experiencing the same Problem when showing AdBanners in my Flutter App.

Using an UiKitView which is implemented as a Swift FlutterPlatformView. 
To this PlatformViews View I ad the AdBanner as a SubView.
This results in the View and the SubView being the 2 UIViews similar to OPs example.

imo this is a pretty common usecase .

I also found that for the purpose of analyzing and reproducing this issue, using a CupertinoPopupSurface with an empty Container as a child illustrates the Problem much clearer than using a Dialog.

```
showCupertinoDialog(
      context: context,
      barrierDismissible: true,
      builder: (BuildContext context) => Theme(
        data: Theme.of(context).copyWith(dialogBackgroundColor: Colors.red),
        child: CupertinoPopupSurface(
          child: Container(),
        ),
      ),
    );
```
