### ISSUE TITLE
 Failed assertion: line 1697 pos 12: '!_debugDoingThisLayout': is not true.

### ISSUE THREAD

**Issue by adhyatmika-chintana** [flutter/flutter#66369]
filing a new bug

Performing hot reload...
Syncing files to device iPad Pro (9.7-inch)...
Reloaded 4 of 619 libraries in 820ms.

<details>
<summary>error log</summary>

```
 ════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/object.dart': Failed assertion: line 1697 pos 12: '!_debugDoingThisLayout': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Scaffold file:///Users/tonystark/AndroidStudioProjects/yperochi/lib/Screens/Home/home_screen.dart:26:18
When the exception was thrown, this was the stack: 
#2      RenderObject.layout (package:flutter/src/rendering/object.dart:1697:12)
#3      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
#4      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
#5      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
...
The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#307e2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=1024.0, h=768.0)
...  size: Size(1024.0, 768.0)
RenderObject: RenderCustomMultiChildLayoutBox#307e2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1024.0, h=768.0)
  size: Size(1024.0, 768.0)
...  child 1: RenderSemanticsAnnotations#796e3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...    constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=692.0)
...    semantic boundary
...    size: MISSING
...    child: RenderPadding#08e52 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=692.0)
...      size: MISSING
...      padding: EdgeInsets.all(20.0)
...      textDirection: ltr
...      child: RenderPhysicalShape#f0c02 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: offset=Offset(20.0, 20.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=652.0)
...        size: MISSING
...        elevation: 4.0
...        color: Color(0xffffffff)
...        shadowColor: Color(0xffffffff)
...        clipper: ShapeBorderClipper
...        child: RenderCustomPaint#4571a relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=652.0)
...          size: MISSING
...  child 2: RenderConstrainedBox#7f004 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar (can use size)
...    constraints: BoxConstraints(w=1024.0, 0.0<=h<=768.0)
...    size: Size(1024.0, 76.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=76.0)
...    child: RenderSemanticsAnnotations#8d9f3 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=1024.0, 0.0<=h<=76.0)
...      semantics node: SemanticsNode#11
...        Rect.fromLTRB(0.0, 0.0, 1024.0, 76.0)
...      semantic boundary
...      size: Size(1024.0, 76.0)
...      child: RenderAnnotatedRegion<SystemUiOverlayStyle>#db47a relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=1024.0, 0.0<=h<=76.0)
...        size: Size(1024.0, 76.0)
...        child: RenderPhysicalModel#6cd46 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=1024.0, 0.0<=h<=76.0)
...          layer: PhysicalModelLayer#ae56f
...            engine layer: PhysicalShapeEngineLayer#0af47
...            elevation: 0.0
...            color: Color(0xffffffff)
...          size: Size(1024.0, 76.0)
...          elevation: 0.0
...          color: Color(0xffffffff)
...          shadowColor: Color(0xffffffff)
...          shape: BoxShape.rectangle
...          borderRadius: BorderRadius.zero
...  child 3: RenderStack#99687 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(933.0, 677.0); id=_ScaffoldSlot.floatingActionButton (can use size)
...    constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=768.0)
...    size: Size(75.0, 75.0)
...    alignment: centerRight
...    textDirection: ltr
...    fit: loose
...    overflow: clip
...    child 1: RenderTransform#875dd relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=768.0)
...      size: Size(75.0, 75.0)
...      transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...      origin: null
...      alignment: center
...      textDirection: ltr
...      transformHitTests: true
...      child: RenderTransform#76dcd relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=768.0)
...        size: Size(75.0, 75.0)
...        transform matrix: [0] 1.0,0.0,0.0,0.0
[1] -0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderSemanticsAnnotations#2a90b relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=768.0)
...          size: Size(75.0, 75.0)
...  child 4: RenderPointerListener#77c4b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.statusBar (can use size)
...    constraints: BoxConstraints(w=1024.0, h=20.0)
...    size: Size(1024.0, 20.0)
...    behavior: opaque
...    listeners: down
...  child 5: RenderConstrainedBox#6d016 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.drawer (can use size)
...    constraints: BoxConstraints(w=1024.0, h=768.0)
...    size: Size(1024.0, 768.0)
...    additionalConstraints: BoxConstraints(w=0.0, h=0.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/object.dart': Failed assertion: line 1697 pos 12: '!_debugDoingThisLayout': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Scaffold file:///Users/tonystark/AndroidStudioProjects/yperochi/lib/Screens/Home/home_screen.dart:26:18
When the exception was thrown, this was the stack: 
#2      RenderObject.layout (package:flutter/src/rendering/object.dart:1697:12)
#3      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
#4      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)
#5      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
...
The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#307e2 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=1024.0, h=768.0)
...  size: Size(1024.0, 768.0)
RenderObject: RenderCustomMultiChildLayoutBox#307e2 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1024.0, h=768.0)
  size: Size(1024.0, 768.0)
...  child 1: RenderSemanticsAnnotations#796e3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...    constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=692.0)
...    semantic boundary
...    size: MISSING
...    child: RenderPadding#08e52 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=692.0)
...      size: MISSING
...      padding: EdgeInsets.all(20.0)
...      textDirection: ltr
...      child: RenderPhysicalShape#f0c02 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT
...        needs compositing
...        parentData: offset=Offset(20.0, 20.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=652.0)
...        size: MISSING
...        elevation: 4.0
...        color: Color(0xffffffff)
...        shadowColor: Color(0xffffffff)
...        clipper: ShapeBorderClipper
...        child: RenderCustomPaint#4571a relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=984.0, 0.0<=h<=652.0)
...          size: MISSING
...  child 2: RenderConstrainedBox#7f004 relayoutBoundary=up1 NEEDS-PAINT
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar (can use size)
...    constraints: BoxConstraints(w=1024.0, 0.0<=h<=768.0)
...    size: Size(1024.0, 76.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=76.0)
...    child: RenderSemanticsAnnotations#8d9f3 relayoutBoundary=up2 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=1024.0, 0.0<=h<=76.0)
...      semantics node: SemanticsNode#11
...        Rect.fromLTRB(0.0, 0.0, 1024.0, 76.0)
...      semantic boundary
...      size: Size(1024.0, 76.0)
...      child: RenderAnnotatedRegion<SystemUiOverlayStyle>#db47a relayoutBoundary=up3 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=1024.0, 0.0<=h<=76.0)
...        size: Size(1024.0, 76.0)
...        child: RenderPhysicalModel#6cd46 relayoutBoundary=up4 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=1024.0, 0.0<=h<=76.0)
...          layer: PhysicalModelLayer#ae56f
...            engine layer: PhysicalShapeEngineLayer#e4471
...            elevation: 0.0
...            color: Color(0xffffffff)
...          size: Size(1024.0, 76.0)
...          elevation: 0.0
...          color: Color(0xffffffff)
...          shadowColor: Color(0xffffffff)
...          shape: BoxShape.rectangle
...          borderRadius: BorderRadius.zero
...  child 3: RenderStack#99687 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(933.0, 677.0); id=_ScaffoldSlot.floatingActionButton (can use size)
...    constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=768.0)
...    size: Size(75.0, 75.0)
...    alignment: centerRight
...    textDirection: ltr
...    fit: loose
...    overflow: clip
...    child 1: RenderTransform#875dd relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
...      parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=768.0)
...      size: Size(75.0, 75.0)
...      transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...      origin: null
...      alignment: center
...      textDirection: ltr
...      transformHitTests: true
...      child: RenderTransform#76dcd relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=768.0)
...        size: Size(75.0, 75.0)
...        transform matrix: [0] 1.0,0.0,0.0,0.0
[1] -0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderSemanticsAnnotations#2a90b relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=768.0)
...          size: Size(75.0, 75.0)
...  child 4: RenderPointerListener#77c4b
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.statusBar (can use size)
...    constraints: BoxConstraints(w=1024.0, h=20.0)
...    size: Size(1024.0, 20.0)
...    behavior: opaque
...    listeners: down
...  child 5: RenderConstrainedBox#6d016
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.drawer (can use size)
...    constraints: BoxConstraints(w=1024.0, h=768.0)
...    size: Size(1024.0, 768.0)
...    additionalConstraints: BoxConstraints(w=0.0, h=0.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox: RenderSemanticsAnnotations#796e3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT:
  needs compositing
  creator: Semantics ← Card ← UserCheckList ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#5a9a3 ink renderer] ← NotificationListener<LayoutChangedNotification> ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
  constraints: BoxConstraints(0.0<=w<=1024.0, 0.0<=h<=692.0)
  semantic boundary
  size: MISSING
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
If you are trying to perform a hit test during the layout phase itself, make sure you only hit test<…>



```

</details>

**Comment by Abhishek01039** [comment]
Hi @adhyatmika-chintana 
can you please send `flutter doctor -v` and, minimal reproduction code?
Thanks

**Comment by darshankawar** [comment]
@adhyatmika-chintana 
Please provide above details.

**Comment by adhyatmika-chintana** [comment]
here is the flutter doctor result

<img width="638" alt="Screen Shot 2020-09-23 at 10 12 48 AM" src="https://user-images.githubusercontent.com/70528353/94024410-61b5bf00-fd85-11ea-9596-7bc06c2c72bc.png">

**Comment by darshankawar** [comment]
@adhyatmika-chintana 
You seem to be on old version of Flutter. Can you upgrade to latest stable (1.20.4) and try again to see if you get same error ?
Also, we would need a minimal reproducible code sample that we can copy paste and run to see the issue.
Thanks.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
