### ISSUE TITLE
Web: hot restart crashes in CanvasKit mode

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#66361]
## Steps to Reproduce

1. `cd dev/integration_tests/flutter_gallery`
2. `flutter run --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome`
3. Wait for the app to launch
4. Hit 'r' for hot restart.

**Expected results:**

The web page should reload. No errors should be seen anywhere.

**Actual results:**

You see the following error in the console:

```
Performing hot restart...                                           64ms
Restarted application in 64ms.
Error: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
```

I stepped through the code and couldn't find anything the web engine code is doing wrong. It's assigning a `SkPaint` to `rawSkiaObject` the same way it does before hot restart. However, the cast is rejecting the assignment after hot restart.

<details>
  <summary>Full stack trace</summary>

```
Error: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
    at Object.throw_ [as throw] (http://localhost:35749/dart_sdk.js:4332:11)
    at Object.castError (http://localhost:35749/dart_sdk.js:4303:15)
    at Object.cast [as as] (http://localhost:35749/dart_sdk.js:4619:17)
    at dart.NullableType.new.as (http://localhost:35749/dart_sdk.js:6137:60)
    at _engine.CkPaint.new.set rawSkiaObject [as rawSkiaObject] (http://localhost:35749/dart_sdk.js:136154:36)
    at _engine.CkPaint.new.ManagedSkiaObject.new (http://localhost:35749/dart_sdk.js:136183:26)
    at new _engine.CkPaint.new (http://localhost:35749/dart_sdk.js:139306:35)
    at Function.new (http://localhost:35749/dart_sdk.js:130218:21)
    at DefaultShaderWarmUp.warmUpOnCanvas (http://localhost:35749/packages/flutter/src/painting/shader_warm_up.dart.lib.js:198:63)
    at warmUpOnCanvas.next (<anonymous>)
    at runBody (http://localhost:35749/dart_sdk.js:37628:34)
    at Object._async [as async] (http://localhost:35749/dart_sdk.js:37659:7)
    at DefaultShaderWarmUp.warmUpOnCanvas (http://localhost:35749/packages/flutter/src/painting/shader_warm_up.dart.lib.js:173:20)
    at DefaultShaderWarmUp.execute (http://localhost:35749/packages/flutter/src/painting/shader_warm_up.dart.lib.js:100:20)
    at execute.next (<anonymous>)
    at runBody (http://localhost:35749/dart_sdk.js:37628:34)
    at Object._async [as async] (http://localhost:35749/dart_sdk.js:37659:7)
    at DefaultShaderWarmUp.execute (http://localhost:35749/packages/flutter/src/painting/shader_warm_up.dart.lib.js:97:20)
    at binding$5.WidgetsFlutterBinding.new.initInstances (http://localhost:35749/packages/flutter/src/painting/binding.dart.lib.js:60:30)
    at binding$5.WidgetsFlutterBinding.new.initInstances (http://localhost:35749/packages/flutter/src/semantics/binding.dart.lib.js:24:13)
    at binding$5.WidgetsFlutterBinding.new.initInstances (http://localhost:35749/packages/flutter/src/rendering/layer.dart.lib.js:5811:13)
    at binding$5.WidgetsFlutterBinding.new.initInstances (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:49368:13)
    at binding$5.WidgetsFlutterBinding.new.binding.BindingBase.new (http://localhost:35749/packages/flutter/src/foundation/binding.dart.lib.js:329:10)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_GestureBinding$36.new
    (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:49976:49)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_SchedulerBinding$36.new
    (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:49982:51)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_ServicesBinding$36.new
    (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:49988:50)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_PaintingBinding$36.new
    (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:49994:50)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_SemanticsBinding$36.new
    (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:50000:51)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_RendererBinding$36.new
    (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:50006:50)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_WidgetsBinding$36.new
    (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:50012:49)
    at new binding$5.WidgetsFlutterBinding.new (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:50022:51)
    at Function.ensureInitialized (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:50017:54)
    at Object.runApp (http://localhost:35749/packages/flutter/src/widgets/widget_span.dart.lib.js:50031:43)
    at main$ (http://localhost:35749/packages/flutter_gallery/main.dart.lib.js:58:20)
    at main (http://localhost:35749/web_entrypoint.dart.lib.js:34:27)
    at main.next (<anonymous>)
    at http://localhost:35749/dart_sdk.js:37608:33
    at _RootZone.runUnary (http://localhost:35749/dart_sdk.js:37462:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:35749/dart_sdk.js:32439:29)
    at handleValueCallback (http://localhost:35749/dart_sdk.js:32986:49)
    at Function._propagateToListeners (http://localhost:35749/dart_sdk.js:33024:17)
    at _Future.new.[_completeWithValue] (http://localhost:35749/dart_sdk.js:32867:23)
    at http://localhost:35749/dart_sdk.js:32095:46
    at _RootZone.runUnary (http://localhost:35749/dart_sdk.js:37462:58)
    at _FutureListener.then.handleValue (http://localhost:35749/dart_sdk.js:32439:29)
    at handleValueCallback (http://localhost:35749/dart_sdk.js:32986:49)
    at Function._propagateToListeners (http://localhost:35749/dart_sdk.js:33024:17)
    at _Future.new.[_completeWithValue] (http://localhost:35749/dart_sdk.js:32867:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:35749/dart_sdk.js:32889:35)
    at Object._microtaskLoop (http://localhost:35749/dart_sdk.js:37723:13)
    at _startMicrotaskLoop (http://localhost:35749/dart_sdk.js:37729:13)
    at http://localhost:35749/dart_sdk.js:33241:9
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown during paint():
Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'

The relevant error-causing widget was:
  AnimatedIcon
  file:///home/yjbanov/code/flutter/flutter/dev/integration_tests/flutter_gallery/lib/gallery/backdrop.dart:288:23

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 64:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 442:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 383:9        as
lib/_engine/engine/canvaskit/skia_object_cache.dart 174:6                         set rawSkiaObject
lib/_engine/engine/canvaskit/skia_object_cache.dart 129:5                         new
lib/_engine/engine/canvaskit/painting.dart 13:3                                   new
lib/ui/src/ui/painting.dart 233:58                                                new
packages/flutter/src/material/animated_icons/animated_icons.dart 204:20           paint
packages/flutter/src/material/animated_icons/animated_icons.dart 168:11           paint
packages/flutter/src/rendering/custom_paint.dart 531:12                           [_paintWithPainter]
packages/flutter/src/rendering/custom_paint.dart 572:7                            paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/shifted_box.dart 70:14                             paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/shifted_box.dart 70:14                             paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/shifted_box.dart 70:14                             paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/box.dart 2616:14                                   defaultPaint
packages/flutter/src/rendering/flex.dart 971:7                                    paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/box.dart 2616:14                                   defaultPaint
packages/flutter/src/rendering/flex.dart 971:7                                    paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/box.dart 2616:14                                   defaultPaint
packages/flutter/src/rendering/stack.dart 592:5                                   paintStack
packages/flutter/src/rendering/stack.dart 600:7                                   paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/widgets/layout_builder.dart 377:14                           paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/shifted_box.dart 70:14                             paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/box.dart 2616:14                                   defaultPaint
packages/flutter/src/rendering/custom_layout.dart 407:5                           paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/material/material.dart 555:11                                paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 396:12                                 pushLayer
packages/flutter/src/rendering/proxy_box.dart 1860:14                             paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 396:12                                 pushLayer
packages/flutter/src/rendering/proxy_box.dart 5091:12                             paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 140:10                                 _repaintCompositedChild
packages/flutter/src/rendering/object.dart 100:5                                  repaintCompositedChild
packages/flutter/src/rendering/object.dart 206:7                                  [_compositeChild]
packages/flutter/src/rendering/object.dart 187:7                                  paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 953:16                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/proxy_box.dart 2614:13                             paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 140:10                                 _repaintCompositedChild
packages/flutter/src/rendering/object.dart 100:5                                  repaintCompositedChild
packages/flutter/src/rendering/object.dart 206:7                                  [_compositeChild]
packages/flutter/src/rendering/object.dart 187:7                                  paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/proxy_box.dart 3233:11                             paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/widgets/overlay.dart 751:14                                  paintStack
packages/flutter/src/widgets/overlay.dart 761:7                                   paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/custom_paint.dart 575:11                           paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 129:14                              paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                                 paintChild
packages/flutter/src/rendering/view.dart 214:14                                   paint
packages/flutter/src/rendering/object.dart 2311:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 140:10                                 _repaintCompositedChild
packages/flutter/src/rendering/object.dart 100:5                                  repaintCompositedChild
packages/flutter/src/rendering/object.dart 978:29                                 flushPaint
packages/flutter/src/rendering/binding.dart 437:19                                drawFrame
packages/flutter/src/widgets/binding.dart 907:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 301:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1117:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1055:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 864:7                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19           internalCallback

The following RenderObject was being processed when the exception was fired: RenderCustomPaint#35000 relayoutBoundary=up2:
  creator: CustomPaint ← Semantics ← AnimatedIcon ← IconTheme ← Builder ← Align ← SizedBox ← Padding ←
    ConstrainedBox ← Semantics ← _PointerListener ← Listener ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=32.0, 0.0<=h<=32.0)
  size: Size(24.0, 24.0)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
Another exception was thrown: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
Another exception was thrown: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
Another exception was thrown: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
Another exception was thrown: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
Another exception was thrown: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
Another exception was thrown: Expected a value of type 'JSObject<SkPaint>?', but got one of type 'NativeJavaScriptObject'
```

</details>

/cc @sigmundch @vsmenon

**Comment by vsmenon** [comment]
@yjbanov - same exact type check is passing on initial load and failing after hot restart?

@Markzipan - type cache reset issue if the above is right?

**Comment by yjbanov** [comment]
> @yjbanov - same exact type check is passing on initial load and failing after hot restart?

That's correct.

**Comment by yjbanov** [comment]
The line of code in question: https://github.com/flutter/engine/blob/ddd3d016e1e76a86f961627dc930943eeb7f9324/lib/web_ui/lib/src/engine/canvaskit/skia_object_cache.dart#L129

**Comment by Markzipan** [comment]
@vsmenon Currently investigating. Seems like something with type caches + lazy JS type caches for sure.
