### ISSUE TITLE
Local Network enabled is't working  on iOS 14

### ISSUE THREAD

**Issue by tatsuyuki25** [flutter/flutter#66408]
## Steps to Reproduce

1. `flutter create test_ios14`
2. `flutter run`
3. blank screen

## Logs
first run
```
Running Xcode build...
 └─Compiling, linking and signing...                        25.7s
Xcode build done.                                           58.8s
Failed to attach to the observatory.
Try accepting the local network permissions popup, or enable "Settings > Privacy > Local Network" for your app.
For more information, see https://flutter.dev/docs/development/ios-14#debugging-flutter
```

after set Local Network permission enabled.
```
Running Xcode build...
 └─Compiling, linking and signing...                        14.1s
Xcode build done.                                           25.8s
Failed to attach to the observatory.
Try accepting the local network permissions popup, or enable "Settings > Privacy > Local Network" for your app.
For more information, see https://flutter.dev/docs/development/ios-14#debugging-flutter
Installing and launching...                                        33.7s
```

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.309, on Mac OS X 10.15.6 19G2021 x86_64, locale zh-Hant-TW)
    • Flutter version 1.22.0-10.0.pre.309 at /Users/liaojianxun/flutter
    • Framework revision 78e54dd46b (61 minutes ago), 2020-09-22 17:50:27 -0700
    • Engine revision c62d665299
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/liaojianxun/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1
```

**Comment by TahaTesser** [comment]
Hi @tatsuyuki25 
It would be enabled by default, I cannot reproduce it using the new project `flutter create master_flutter` on the latest `master` on iOS 14

![IMG_0274](https://user-images.githubusercontent.com/48603081/93986973-9ab15c00-fda4-11ea-82a5-b5832d11416e.jpg)


```
Running "flutter pub get" in master_flutter...                      1.5s
Launching lib/main.dart on Taha’s iPhone in debug mode...
 
Automatically signing iOS for device deployment using specified development team
in Xcode project: X8NNQ9CYL2
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         7.6s
Xcode build done.                                           21.8s
Installing and launching...                                        21.8s
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)       
Errors found! Invalidating cache...                                     
Waiting for Taha’s iPhone to report its views...                    58ms
Syncing files to device Taha’s iPhone...                           237ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Taha’s iPhone is available at:
http://127.0.0.1:56916/mrggdXpT4a8=/


```


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.317, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.317 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 10febea877 (3 hours ago), 2020-09-23 07:22:10 +0200
    • Engine revision 57ee3d4b32
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.102

• No issues found!
```

</details> 

Can you please try a new project on the latest `master` and If the problem persists, can you please provide device details Thank you

**Comment by tatsuyuki25** [comment]
Hi @TahaTesser 
I thank this is problem. but i don't know to fix it.

IPhone XR ios 14.
flutter devices:
```
3 connected devices:

Mei's iPhone (mobile) • 00008020-000C61D90AD1002E            • ios        • iOS 14.0
iPhone 11 (mobile)    • 4A859D2E-A500-47CF-9C68-93F4A4D958CC • ios        • com.apple.CoreSimulator.SimRuntime.iOS-14-0
(simulator)
macOS (desktop)       • macos                                • darwin-x64 • Mac OS X 10.15.6 19G2021 x86_64

• Error: Mei's iPhone is busy: Copying cache files from device. Xcode will continue when Mei's iPhone is finished.
  (code -10)
```

**Comment by tatsuyuki25** [comment]
other ios devices same error.

**Comment by TahaTesser** [comment]
It doesn't reproduce for me, the local network is already enabled by default 
Related https://github.com/flutter/flutter/issues/61047

**Comment by TahaTesser** [comment]
Hi @tatsuyuki25 
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/66280
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by jmagman** [comment]
@tatsuyuki25 Can you update to latest on the master channel and attach the output of `flutter run -v`?

**Comment by tatsuyuki25** [comment]
HI @jmagman 
[flutter run -v](https://gist.github.com/tatsuyuki25/3f4730541b00ec74e73b809049a7387d)

**Comment by jmagman** [comment]
`Try accepting the local network permissions popup` was just suggesting that it could possibly be a possible reason for a failure to connect to the observatory, but people took it literally.  I removed it here https://github.com/flutter/flutter/pull/66621.

Is your app actually launching?

**Comment by tatsuyuki25** [comment]
HI @jmagman 
same error
```
[        ] Application launched on the device. Waiting for observatory port.
[  +33 ms] Attempting to forward device port 64300 to host port 60885
[   +1 ms] executing: /Users/liaojianxun/flutter/bin/cache/artifacts/usbmuxd/iproxy 60885:64300 --udid 00008020-000C61D90AD1002E
[+1079 ms] Forwarded port ForwardedPort HOST:60885 to DEVICE:64300
[  +44 ms] HttpException: Connection closed before full header was received, uri = http://localhost:60885/ws
[+2014 ms] HttpException: , uri = http://localhost:60885/ws
[+2018 ms] HttpException: , uri = http://localhost:60885/ws
[+2013 ms] HttpException: , uri = http://localhost:60885/ws
[+2019 ms] HttpException: , uri = http://localhost:60885/ws
[+2004 ms] Failed to connect directly, falling back to mDNS
[+5018 ms] Failed to connect with log scanning, falling back to mDNS
[   +6 ms] Checking for advertised Dart observatories...
[+5028 ms] No pointer records found.
[   +3 ms] mDNS query failed. Checking for an interface with a ipv4 link local address.
[   +3 ms] Found interface "en0":
[        ] 	Bound address: "172.16.101.81"
[        ] Found interface "en9":
[        ] 	Bound address: "169.254.213.228" link local
[        ] An interface with an ipv4 link local address was found.
[        ] Failed to connect with mDNS
[   +1 ms] Installing and launching... (completed in 47.3s)
[   +2 ms] Error launching application on Mei's iPhone.
[  +12 ms] "flutter run" took 145,200ms.
[   +8 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:612:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:985:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +263 ms] ensureAnalyticsSent: 258ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +5 ms] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by jmagman** [comment]
> Is your app actually launching?

**Comment by tatsuyuki25** [comment]
Yes, my app launch with blank screen.

**Comment by tatsuyuki25** [comment]
HI,
Any update for this issue?
same error on flutter latest version.

```
[ +241 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+30017 ms] Installing and launching... (completed in 47.0s)
[   +1 ms] Error launching application on Mei's iPhone.
[   +4 ms] "flutter run" took 101,141ms.
[   +8 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:608:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1074:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

**Comment by quetool** [comment]
I think I have the very same issue, this is the last part of the logs
```
[ +119 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +111 ms] ------ Debug phase ------
[        ] Starting debug of 00008020-001A03CE1161002E (N841AP, iPhone XR, iphoneos, arm64e) a.k.a. 'iPhone' connected through USB...
[ +112 ms] [  0%] Looking up developer disk image
[  +12 ms] [ 95%] Developer disk image mounted successfully
[ +577 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[ +551 ms] (lldb) command source -s 0 '/tmp/FA5B5C91-6B62-4553-976F-7FCAC3AE9AE2/fruitstrap-lldb-prep-cmds-00008020_001A03CE1161002E'
[        ] Executing commands in '/tmp/FA5B5C91-6B62-4553-976F-7FCAC3AE9AE2/fruitstrap-lldb-prep-cmds-00008020_001A03CE1161002E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/alfredorinaudo/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92) arm64e/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/alfredorinaudo/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92) arm64e/Symbols"
[        ] (lldb)     target create "/Users/alfredorinaudo/Development/Projects/Flutter/eulerian_magnification_frontend/build/ios/iphoneos/Runner.app"
[+13126 ms] Current executable set to '/Users/alfredorinaudo/Development/Projects/Flutter/eulerian_magnification_frontend/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/6A01993A-0363-4811-9798-5C2E81DB7D14/Runner.app"
[ +502 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:50231"
[        ] (lldb)     script fruitstrap_output_path=""
[   +1 ms] (lldb)     script fruitstrap_error_path=""
[   +1 ms] (lldb)     target modules search-paths add /usr "/Users/alfredorinaudo/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92) arm64e/Symbols/usr" /System
"/Users/alfredorinaudo/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92) arm64e/Symbols/System" "/private/var/containers/Bundle/Application/6A01993A-0363-4811-9798-5C2E81DB7D14"
"/Users/alfredorinaudo/Development/Projects/Flutter/eulerian_magnification_frontend/build/ios/iphoneos" "/var/containers/Bundle/Application/6A01993A-0363-4811-9798-5C2E81DB7D14"
"/Users/alfredorinaudo/Development/Projects/Flutter/eulerian_magnification_frontend/build/ios/iphoneos" /Developer "/Users/alfredorinaudo/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)
arm64e/Symbols/Developer"
[  +55 ms] (lldb)     command script import "/tmp/FA5B5C91-6B62-4553-976F-7FCAC3AE9AE2/fruitstrap_00008020_001A03CE1161002E.py"
[   +9 ms] (lldb)     command script add -f fruitstrap_00008020_001A03CE1161002E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001A03CE1161002E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001A03CE1161002E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_001A03CE1161002E.safequit_command safequit
[        ] (lldb)     connect
[  +46 ms] (lldb)     run
[ +282 ms] success
[        ] (lldb)     safequit
[ +122 ms] Process 376 detached
[ +103 ms] Application launched on the device. Waiting for observatory port.
[  +19 ms] Attempting to forward device port 60720 to host port 50244
[        ] executing: /Users/alfredorinaudo/Development/SDKs/flutter/bin/cache/artifacts/usbmuxd/iproxy 50244:60720 --udid 00008020-001A03CE1161002E
[+1063 ms] Forwarded port ForwardedPort HOST:50244 to DEVICE:60720
[  +19 ms] HttpException: Connection closed before full header was received, uri = http://localhost:50244/ws
[+2008 ms] HttpException: , uri = http://localhost:50244/ws
[+2009 ms] HttpException: , uri = http://localhost:50244/ws
[+2007 ms] HttpException: , uri = http://localhost:50244/ws
[+2006 ms] HttpException: , uri = http://localhost:50244/ws
[+2005 ms] Failed to connect directly, falling back to mDNS
[   +9 ms] Checking for advertised Dart observatories...
[+5039 ms] No pointer records found.
[   +3 ms] mDNS query failed. Checking for an interface with a ipv4 link local address.
[   +5 ms] Found interface "en1":
[        ]      Bound address: "192.168.0.155" 
[        ] Found interface "en5":
[        ]      Bound address: "169.254.3.46" link local
[        ] An interface with an ipv4 link local address was found.
[        ] Failed to connect with mDNS, falling back to log scanning
```
after that, it just stucks there.... But I can see the app is opened and closed inmediatly after.

**Comment by jmagman** [comment]
> But I can see the app is opened and closed inmediatly after.

That means your app crashed.  Please file another issue and completely fill out the issue.  Include the symbolicated crash log from Xcode > Window > Devices and Simulators > your device > Device Logs > the Runner crash that matches the timestamp.

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/58676

**Comment by xizhengmeng** [comment]
I have the very same issue

[+5020 ms] No pointer records found.
[   +1 ms] mDNS query failed. Checking for an interface with a ipv4 link local address.
[   +1 ms] Found interface "en0":
[        ] 	Bound address: "30.29.164.72"
[   +2 ms] The mDNS query for an attached iOS device failed. It may be necessary to disable the "Personal Hotspot" on the
device,
           and to ensure that the "Disable unless needed" setting is unchecked under System Preferences > Network >
iPhone USB. See
           https://github.com/flutter/flutter/issues/46698 for details.
[   +5 ms] Waiting for a connection from Flutter on iPhone...

can we replace mDNS for publish the listening port and authCode
