### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Cannot extract a file path from a org-dartlang-app URI

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#66404]
## Command
```
flutter run --hot -d web-server --verbose --resident --target=lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Cannot extract a file path from a org-dartlang-app URI
```
#0      _Uri.toFilePath (dart:core/uri.dart:2710:7)
#1      toMultiRootPath (package:flutter_tools/src/compile.dart:884:35)
#2      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:603:7)
#3      _RecompileRequest._run (package:flutter_tools/src/compile.dart:337:16)
#4      _CompilationRequest.run (package:flutter_tools/src/compile.dart:315:30)
#5      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:635:23)
#6      _rootRunUnary (dart:async/zone.dart:1206:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#13     _rootRun (dart:async/zone.dart:1182:47)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel unknown, 1.22.0-10.0.pre.307, on Mac OS X 10.14.6 18G103 x86_64, locale en-US)
    • Flutter version 1.22.0-10.0.pre.307 at /Users/flutter/.cocoon/flutter
    • Framework revision fce475bd0f (23 minutes ago), 2020-09-22 20:22:03 -0400
    • Engine revision c62d665299
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/share/android-sdk
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    • ANDROID_HOME = /usr/local/share/android-sdk
    ✗ No valid Android SDK platforms found in /usr/local/share/android-sdk/platforms. Candidates were:
        - android-28
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone (mobile)  • b4873f14ffb248dfcb00c8cb7fdd4cdcff87f1f0 • ios            • iOS 12.4
    • macOS (desktop)  • macos                                    • darwin-x64     • Mac OS X 10.14.6 18G103 x86_64
    • Web Server (web) • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 77.0.3865.90

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: null
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-0.4.9+2
connectivity_for_web-0.3.1+2
connectivity_macos-0.1.0+5
device_info-0.4.2+7
e2e-0.7.0
url_launcher-5.7.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.3+2
url_launcher_windows-0.0.1+1
video_player-0.10.6
video_player_web-0.1.2+3

**Comment by jonahwilliams** [comment]
Looks like we're missing a test case with an org-dartlang-app URI scheme, perhaps should switch to using URIs instead, but that would be a bigger change
