### ISSUE TITLE
DateRangePicker crash when input an invalid date in input entry mode

### ISSUE THREAD

**Issue by b1acKr0se** [flutter/flutter#66416]
## Steps to Reproduce

1. Create an application using DateRangePicker:

```
final picked = await showDateRangePicker(
          context: context,
          firstDate: DateTime(DateTime.now().year - 1),
          lastDate: DateTime(DateTime.now().year + 1),
        );
```
 
2. Press the toggle to switch to input mode.
3. Enter a date outside of the firstDate and lastDate, for example 2050/02/02.
4. Press the toggle to switch to calendar mode.

**Expected results:** I think we should disable the entry mode toggle in case the input date is invalid.

**Actual results:** 

Enter an invalid end date (which is not between first and last date), the input dialog shows proper error message:

<img width="360" alt="Screen Shot 2020-09-23 at 11 02 15" src="https://user-images.githubusercontent.com/8596158/93965418-4c905e80-fd8c-11ea-9adb-d26dbb2fe978.png">

But when switching to calendar mode, the picker crashes:

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-23 at 11 02 23](https://user-images.githubusercontent.com/8596158/93965506-7ba6d000-fd8c-11ea-8e13-e5e030d654fd.png)

<details>
  <summary>Logs</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building:
flutter: 'package:flutter/src/material/pickers/calendar_date_range_picker.dart': Failed assertion: line 593
flutter: pos 15: 'selectedDateEnd == null || !selectedDateEnd.isAfter(lastDate)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new _MonthItem (package:flutter/src/material/pickers/calendar_date_range_picker.dart:593:15)
flutter: #3      _CalendarDateRangePickerState._buildMonthItem (package:flutter/src/material/pickers/calendar_date_range_picker.dart:182:12)
flutter: #4      _CalendarDateRangePickerState.build.<anonymous closure> (package:flutter/src/material/pickers/calendar_date_range_picker.dart:217:58)
flutter: #5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:448:22)
flutter: #6      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1136:67)
flutter: #7      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:140:29)
flutter: #8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1136:26)
flutter: #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1149:55)
flutter: #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
flutter: #11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1142:11)
flutter: #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:356:23)
flutter: #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1868:58)
flutter: #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:920:15)
flutter: #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1868:13)
flutter: #16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:345:5)
flutter: #17     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:429:5)
flutter: #18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:81:12)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #20     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
flutter: #21     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1447:29)
flutter: #22     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #42     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:827:17)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #44     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
flutter: #45     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:495:7)
flutter: #46     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
flutter: #47     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
flutter: #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #52     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #54     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #56     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
flutter: #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #63     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #65     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #67     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:396:13)
flutter: #68     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
flutter: #69     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
flutter: #70     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #71     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
flutter: #72     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #73     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #74     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #75     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #79     _invoke (dart:ui/hooks.dart:253:10)
flutter: #80     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Flutter error caught by Crashlytics plugin:
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building:
flutter: 'package:flutter/src/material/pickers/calendar_date_range_picker.dart': Failed assertion: line 593
flutter: pos 15: 'selectedDateEnd == null || !selectedDateEnd.isAfter(lastDate)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new _MonthItem (package:flutter/src/material/pickers/calendar_date_range_picker.dart:593:15)
flutter: #3      _CalendarDateRangePickerState._buildMonthItem (package:flutter/src/material/pickers/calendar_date_range_picker.dart:182:12)
flutter: #4      _CalendarDateRangePickerState.build.<anonymous closure> (package:flutter/src/material/pickers/calendar_date_range_picker.dart:224:58)
flutter: #5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:448:22)
flutter: #6      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1136:67)
flutter: #7      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:140:29)
flutter: #8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1136:26)
flutter: #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1149:55)
flutter: #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
flutter: #11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1142:11)
flutter: #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:356:23)
flutter: #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1868:58)
flutter: #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:920:15)
flutter: #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1868:13)
flutter: #16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:345:5)
flutter: #17     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:429:5)
flutter: #18     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:81:12)
flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #20     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
flutter: #21     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
flutter: #22     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: firebase_crashlytics: Error reported to Crashlytics.
flutter: firebase_crashlytics: Error reported to Crashlytics.
flutter: #42     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:827:17)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #44     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:11)
flutter: #45     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:495:7)
flutter: #46     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:242:7)
flutter: #47     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:401:14)
flutter: #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #52     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #54     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:209:11)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #56     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
flutter: #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #63     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1269:11)
flutter: #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #65     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:270:13)
flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #67     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:396:13)
flutter: #68     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
flutter: #69     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
flutter: #70     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #71     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
flutter: #72     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #73     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #74     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #75     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #79     _invoke (dart:ui/hooks.dart:253:10)
flutter: #80     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E2265, locale en)
    • Flutter version 1.20.4 at /Users/haint/Workspace/flutter
    • Framework revision fba99f6cf9 (8 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/haint/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • C39A077E-BC88-4E8F-9CB4-9DD66ECBE2E3 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Currently the issue (red screen) occurs in latest stable (1.20.4). 

Although the error says that the assert fails because the `selectedDateStart == null || !selectedDateStart.isAfter(lastDate)': is not true.` which is expected. But I think per OP, this error message could be avoided if the `calendar mode` could be disabled if such dates are selected.

<img width="340" alt="Screenshot 2020-09-23 at 12 46 13 PM" src="https://user-images.githubusercontent.com/67046386/93979693-4bb2f900-fd9b-11ea-98b6-bb55511396dc.png">
<img width="332" alt="Screenshot 2020-09-23 at 12 46 58 PM" src="https://user-images.githubusercontent.com/67046386/93979707-4f468000-fd9b-11ea-9551-be43b709e5bc.png">
