### ISSUE TITLE
[Textfield] assertion was thrown during paint(): RRect argument contained a NaN value.

### ISSUE THREAD

**Issue by MaruQuarky** [flutter/flutter#66457]
**Steps to reproduce the issue:**

1. Run the the code below in either "beta" or "master" channel in an iOS device or emulator:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Login(),
    );
  }
}

class Login extends StatefulWidget {
  const Login({Key key}) : super(key: key);

  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> with TickerProviderStateMixin {
  FocusNode emailFocusNode;
  FocusNode passwordFocusNode;
  TextEditingController emailTextController;
  TextEditingController passwordTextController;
  final PageController pageController = PageController();

  Duration duration = Duration(milliseconds: 200);
  Curve tonalCurve = Curves.easeIn;

  @override
  void initState() {
    super.initState();

    emailTextController = TextEditingController();
    emailFocusNode = FocusNode()..requestFocus();
    passwordTextController = TextEditingController();
    passwordFocusNode = FocusNode();
  }

  @override
  void dispose() {
    emailTextController.dispose();
    emailFocusNode.dispose();
    passwordTextController.dispose();
    passwordFocusNode.dispose();
    super.dispose();
  }

  Widget fieldLabel({String label}) {
    return Container(
      width: MediaQuery.of(context).size.width,
      padding: const EdgeInsets.only(
        top: 15,
        left: 24,
        right: 24,
      ),
      child: Text(
        label,
        textAlign: TextAlign.center,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;

    final emailScreen = Scaffold(
      appBar: AppBar(),
      body: SizedBox(
        width: screenSize.width,
        child: Column(
          children: [
            fieldLabel(
              label: 'email',
            ),
            TextField(
              controller: emailTextController,
              keyboardType: TextInputType.emailAddress,
              autofocus: true,
            ),
          ],
        ),
      ),
    );

    final passwordScreen = Scaffold(
      appBar: AppBar(),
      body: SizedBox(
        width: screenSize.width,
        child: Column(
          children: [
            fieldLabel(
              label: 'password',
            ),
            TextField(
              obscureText: true,
              controller: passwordTextController,
              textInputAction: TextInputAction.go,
              autofocus: true,
            ),
          ],
        ),
      ),
    );

    return Container(
      child: PageView(
        controller: pageController,
        children: [
          emailScreen,
          passwordScreen,
        ],
      ),
    );
  }
}
```
2. Type some text in the `TextField`.
3. Swipe between the 1st and 2nd page.
4. An error will be thrown, but the app doesn’t crash. This happens regardless if the `TextField` has a text or not.

**Expected results:** 
iOS Flutter app shouldn’t throw errors. The errors thrown are similar with https://github.com/flutter/flutter/issues/64785 - per thread, the issue should be fixed by using master channel. However, using the master channel on the repro above still throws errors.

**Actual results:** 
The errors are only reproducible in iOS. Android build works fine.

<details>
  <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: '<optimized out>'
 
 
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
 
The relevant error-causing widget was: 
  TextField file:///Users/{USER}/Downloads/dev/flutter/flutter_app2/lib/main.dart:105:13
When the exception was thrown, this was the stack: 
#2      _rrectIsValid (dart:ui/painting.dart:37:10)
#3      Canvas.drawRRect (dart:ui/painting.dart:3742:12)
#4      RenderEditable._paintCaret (package:flutter/src/rendering/editable.dart:2042:14)
#5      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:2224:7)
#6      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2267:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#17f71 relayoutBoundary=up16
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
...  size: Size(375.0, 19.0)
...  cursorColor: Color(0x022196f3)
...  showCursor: ValueNotifier<bool>#0898c(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0x662196f3)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#f9c4d(offset: 0.0, range: 0.0..0.0, viewport: 375.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#be3c8, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: .SF UI Text
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
RenderObject: RenderEditable#17f71 relayoutBoundary=up16
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
  size: Size(375.0, 19.0)
  cursorColor: Color(0x022196f3)
  showCursor: ValueNotifier<bool>#0898c(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0x662196f3)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false)
  offset: ScrollPositionWithSingleContext#f9c4d(offset: 0.0, range: 0.0..0.0, viewport: 375.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#be3c8, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackCupertino subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: .SF UI Text
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    ""
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter analyze on both flutter master and beta channels
```
Analyzing flutter_app...                                                
No issues found! (ran in 2.2s)
````

Flutter beta channel, flutter doctor -v
```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-PH)
    • Flutter version 1.22.0-12.1.pre at /Users/{USER}/Downloads/flutter
    • Framework revision 8b3760638a (7 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/{USER}/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Flutter master channel flutter doctor -v
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.317, on Mac OS X 10.15.6 19G2021 x86_64, locale en-PH)
    • Flutter version 1.22.0-10.0.pre.317 at /Users/{USER}/Downloads/flutter
    • Framework revision 10febea877 (4 hours ago), 2020-09-23 07:22:10 +0200
    • Engine revision 57ee3d4b32
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/{USER}/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.


```

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Login(),
    );
  }
}

class Login extends StatefulWidget {
  const Login({Key key}) : super(key: key);

  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> with TickerProviderStateMixin {
  FocusNode emailFocusNode;
  FocusNode passwordFocusNode;
  TextEditingController emailTextController;
  TextEditingController passwordTextController;
  final PageController pageController = PageController();

  Duration duration = Duration(milliseconds: 200);
  Curve tonalCurve = Curves.easeIn;

  @override
  void initState() {
    super.initState();

    emailTextController = TextEditingController();
    emailFocusNode = FocusNode()..requestFocus();
    passwordTextController = TextEditingController();
    passwordFocusNode = FocusNode();
  }

  @override
  void dispose() {
    emailTextController.dispose();
    emailFocusNode.dispose();
    passwordTextController.dispose();
    passwordFocusNode.dispose();
    super.dispose();
  }

  Widget fieldLabel({String label}) {
    return Container(
      width: MediaQuery.of(context).size.width,
      padding: const EdgeInsets.only(
        top: 15,
        left: 24,
        right: 24,
      ),
      child: Text(
        label,
        textAlign: TextAlign.center,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;

    final emailScreen = Scaffold(
      appBar: AppBar(),
      body: SizedBox(
        width: screenSize.width,
        child: Column(
          children: [
            fieldLabel(
              label: 'email',
            ),
            TextField(
              controller: emailTextController,
              keyboardType: TextInputType.emailAddress,
              autofocus: true,
            ),
          ],
        ),
      ),
    );

    final passwordScreen = Scaffold(
      appBar: AppBar(),
      body: SizedBox(
        width: screenSize.width,
        child: Column(
          children: [
            fieldLabel(
              label: 'password',
            ),
            TextField(
              obscureText: true,
              controller: passwordTextController,
              textInputAction: TextInputAction.go,
              autofocus: true,
            ),
          ],
        ),
      ),
    );

    return Container(
      child: PageView(
        controller: pageController,
        children: [
          emailScreen,
          passwordScreen,
        ],
      ),
    );
  }
}

```

</details> 



<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-12.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 8b3760638a (8 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (4 available)            
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.102

• No issues found!


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.23.0-4.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.23.0-4.0.pre at /home/taha/Code/flutter_dev
    • Framework revision 83dd176777 (2 days ago), 2020-09-22 12:04:44 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.340 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 1fef5912cf (3 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (5 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.102

• No issues found!


```

</details>

**Comment by justinmc** [comment]
@LongCatIsLooong Your PR https://github.com/flutter/flutter/pull/61940 fixed similar errors in https://github.com/flutter/flutter/issues/64785, but I guess it's still possible to get errors in this case.  Any opinions on how we should handle this one?

**Comment by LongCatIsLooong** [comment]
It looks like we should stop `RenderFollowerLayer` from painting it content if its current transform transforms points to infinity?

**Comment by LongCatIsLooong** [comment]
Oh sorry `_getPixelPerfectCursorOffset` should return 0 if `isFinite` is false, instead of `caretPosition`.

**Comment by jesper372** [comment]
Not sure if it makes any difference to the solution, but in the example provided by MaruQuarky, the issue **does** occur in Android as well. It's just much less frequent. I've run that example many times, and occasionally (say, one in 30 runs or so), the same exception (see the trace below) is thrown as that observed in iOS. This is consistent with the behaviour I'm seeing in my own app: Android throws occasionally, iOS frequently.

> ════════ Exception caught by rendering library ═════════════════════════════════════════════════════
Rect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 31: '<optimized out>'
The relevant error-causing widget was: 
  TextField file:///flutter_app/lib/main.dart:105:13
The following RenderObject was being processed when the exception was fired: RenderEditable#02e04 relayoutBoundary=up19
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
  size: Size(411.4, 19.0)
  cursorColor: Color(0xff4285f4)
  showCursor: ValueNotifier<bool>#b7919(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 8, extentOffset: 8, affinity: TextAffinity.downstream, isDirectional: false)
  offset: ScrollPositionWithSingleContext#b819b(offset: 0.0, range: 0.0..0.0, viewport: 411.4, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e6615, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackMountainView subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: Roboto
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "••••••••"
RenderObject: RenderEditable#02e04 relayoutBoundary=up19
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
  size: Size(411.4, 19.0)
  cursorColor: Color(0xff4285f4)
  showCursor: ValueNotifier<bool>#b7919(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 8, extentOffset: 8, affinity: TextAffinity.downstream, isDirectional: false)
  offset: ScrollPositionWithSingleContext#b819b(offset: 0.0, range: 0.0..0.0, viewport: 411.4, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e6615, ScrollDirection.idle)
  text: TextSpan
    debugLabel: (englishLike subhead 2014).merge(blackMountainView subtitle1)
    inherit: false
    color: Color(0xdd000000)
    family: Roboto
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "••••••••"
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by TahaTesser** [comment]
Hi @jesper372 
Please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`

**Comment by ahuruConnect** [comment]
Is this fixed? Im getting the same errors on v1.22.3

**Comment by LongCatIsLooong** [comment]
@jesper372 it would be difficult to investigate without a repro or a stacktrace with the call path. The call path that threw in the original issue should be fixed. Could you open a new issue with repro steps or a complete stacktrace?

**Comment by jesper372** [comment]
@LongCatIsLooong @TahaTesser 
I've opened a new issue for this - see #70610
