### ISSUE TITLE
Problem with built application (appbundle)

### ISSUE THREAD

**Issue by BastienFerbu** [flutter/flutter#66451]
Hello,
The problem is that when I [build](https://flutter.dev/docs/deployment/android) the application, I have a white screen and nothing happen. However, when I run the application with the flag release (`flutter run --release`), it works.

1. Run `flutter build appbundle --release --tree-shake-icons --shrink --split-debug-info=./debug-info/0.0.1+1/android/ --obfuscate`
2. Use bundletool (or Play Store) to install the apk on device

**Expected results:** Same result as with `flutter run --release`

**Actual results:** White screen and the application doesn't crash (for bundletool and Play Store)

<details>
  <summary>Logs</summary>
This is the logcat when I run the app with the built apk.

```
2020-09-23 15:19:09.041 31934-31934/? E/example.appli: Not starting debugger since process cannot load the jdwp agent.
2020-09-23 15:19:10.149 31934-31974/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
2020-09-23 15:19:10.279 31934-31934/? E/FlutterFcmService: Fatal: failed to find callback
2020-09-23 15:19:10.860 30166-30376/? E/SCSLibrary: Unable to fetch remote configuration: java.net.SocketTimeoutException: failed to connect to sdk.sascdn.com/95.100.86.64 (port 443) from /192.0.0.4 (port 34442) after 10000ms
2020-09-23 15:19:10.860 30166-30399/? E/SCSLibrary: Unable to fetch remote configuration: java.net.SocketTimeoutException: failed to connect to sdk.sascdn.com/95.100.86.64 (port 443) from /192.0.0.4 (port 34443) after 10000ms
2020-09-23 15:19:40.040 1006-1137/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2020-09-23 15:19:41.871 29597-30740/? E/CrashlyticsCore: Error occurred sending report com.crashlytics.android.core.SessionReport@5021126
    io.fabric.sdk.android.services.network.HttpRequest$HttpRequestException: java.net.SocketTimeoutException: failed to connect to reports.crashlytics.com/184.73.210.72 (port 443) from /192.0.0.4 (port 32969) after 10000ms
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:6)
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2)
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:1)
        at com.crashlytics.android.core.DefaultCreateReportSpiCall.applyMultipartDataTo(DefaultCreateReportSpiCall.java:1)
        at com.crashlytics.android.core.DefaultCreateReportSpiCall.invoke(DefaultCreateReportSpiCall.java:3)
        at com.crashlytics.android.core.CompositeCreateReportSpiCall.invoke(CompositeCreateReportSpiCall.java:3)
        at com.crashlytics.android.core.ReportUploader.forceUpload(ReportUploader.java:3)
        at com.crashlytics.android.core.ReportUploader$Worker.attemptUploadWithRetry(ReportUploader.java:17)
        at com.crashlytics.android.core.ReportUploader$Worker.onRun(ReportUploader.java:1)
        at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.SocketTimeoutException: failed to connect to reports.crashlytics.com/184.73.210.72 (port 443) from /192.0.0.4 (port 32969) after 10000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
        at libcore.io.IoBridge.connect(IoBridge.java:129)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
        at io.fabric.sdk.android.services.network.HttpRequest.openOutput(HttpRequest.java:4)
        at io.fabric.sdk.android.services.network.HttpRequest.startPart(HttpRequest.java:3)
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:3)
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2) 
        at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:1) 
        at com.crashlytics.android.core.DefaultCreateReportSpiCall.applyMultipartDataTo(DefaultCreateReportSpiCall.java:1) 
        at com.crashlytics.android.core.DefaultCreateReportSpiCall.invoke(DefaultCreateReportSpiCall.java:3) 
        at com.crashlytics.android.core.CompositeCreateReportSpiCall.invoke(CompositeCreateReportSpiCall.java:3) 
        at com.crashlytics.android.core.ReportUploader.forceUpload(ReportUploader.java:3) 
        at com.crashlytics.android.core.ReportUploader$Worker.attemptUploadWithRetry(ReportUploader.java:17) 
        at com.crashlytics.android.core.ReportUploader$Worker.onRun(ReportUploader.java:1) 
        at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2) 
        at java.lang.Thread.run(Thread.java:764) 
```

```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [version 10.0.18362.1082], locale fr-FR)
    • Flutter version 1.20.4 at D:\flutter
    • Framework revision fba99f6cf9 (9 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\basti\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\basti\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\basti\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • LG H870 (mobile) • LGH870f69e7722 • android-arm64 • Android 9 (API 28)

• No issues found!
Process finished with exit code 0
```

```
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  firebase_core:
  firebase_auth: 
  qr_flutter: 
  flutter_svg:
  qr_code_scanner:
  shared_preferences: 
  flutter_rating_bar:
  file_picker: 
  firebase_storage: 
  screen: 
  firebase_messaging:
  url_launcher:
  cloud_functions:
  package_info:
  font_awesome_flutter:
  darango:
  flutter_pagewise:
  flutter_staggered_animations:
  auto_size_text:
  provider:
  searchable_dropdown:
  google_sign_in:
  flutter_platform_widgets:
  connectivity:
```

</details>

**Comment by pedromassangocode** [comment]
Hi @BastienFerbu 
I see there's an open issue (https://github.com/flutter/flutter/issues/65334) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
