### ISSUE TITLE
unable to fetch android licenses

### ISSUE THREAD

**Issue by byteshiva** [flutter/flutter#66458]
```$flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

```

I've installed android studio(https://www.flathub.org/apps/details/com.google.AndroidStudio) and its dependencies using flatpak, i don't know why its not a able to fetch the license information from it

**Comment by jonahwilliams** [comment]
The Android SDK tools require Java 8 (1.8) in order to be run. Normally if you download android studio this comes with a 1.8 JDK, but if you've installed these on your own you'll need to also download a 1.8 JDK and set JAVA_HOME to the sdk dir

**Comment by byteshiva** [comment]
> The Android SDK tools require Java 8 (1.8) in order to be run. Normally if you download android studio this comes with a 1.8 JDK, but if you've installed these on your own you'll need to also download a 1.8 JDK and set JAVA_HOME to the sdk dir

@jonahwilliams ,
 I've installed Android Studio on my ubuntu 20.04 using flatpak, details available at (https://www.flathub.org/apps/details/com.google.AndroidStudio) (`flatpak - building and distribution of application on linux`)

and if I check the project setting it shows the Jdk details, My question is why flutter doctor not able to identify the android studio.


![image](https://user-images.githubusercontent.com/10637299/94032008-2515b200-fddd-11ea-9cf1-a0ce914467e6.png)


```
java --version 
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
```

**Comment by hamdikahloun** [comment]
Hi @byteshiva you can install it with snap : 
https://snapcraft.io/android-studio

**Comment by jonahwilliams** [comment]
@hamdikahloun that is not necessary

**Comment by jonahwilliams** [comment]
@byteshiva looks like we're expecting the JDK to be adjacent to the download android SDK. You can work around this by setting JAVA_HOME to `/app/extra/android-stduio/jre`

**Comment by byteshiva** [comment]
> @byteshiva looks like we're expecting the JDK to be adjacent to the download android SDK. You can work around this by setting JAVA_HOME to `/app/extra/android-stduio/jre`

I'm not sure if this will work or not. I think I can not access flatpak builds and its application file access outside of its environment(container). I think it uses container technology. just similar to docker container, now flatpak is for application build and installation

I can not access /app/extra/android-stduio path from ubuntu base filesystem. so settings JAVA_HOME would not work.
```
cd /app/extra/android-stduio/jre
bash: cd: /app/extra/android-stduio/jre: No such file or directory
$ cd /app/extra/android-stduio
bash: cd: /app/extra/android-stduio: No such file or directory
$ cd /app/extra
bash: cd: /app/extra: No such file or directory
$ cd /app/extra
bash: cd: /app/extra: No such file or directory
$ 

```

**Comment by hamdikahloun** [comment]
@jonahwilliams I just think flatpak doesn't use the default path maybe.

**Comment by hamdikahloun** [comment]
Duplicated issue https://github.com/flutter/flutter/issues/18970

**Comment by jonahwilliams** [comment]
@byteshiva interesting! that means that flutter can't use that downloaded JDK to run the android tools. This means you will need to accept the licenses through android studio

**Comment by byteshiva** [comment]
> @byteshiva interesting! that means that flutter can't use that downloaded JDK to run the android tools. This means you will need to accept the licenses through android studio

The basic architecture of flatpak prevents any access to host system `"Flatpak’s main goals is to increase the security of desktop systems by isolating applications from one another. This is achieved using sandboxing and means that, by default, applications that are run with Flatpak have extremely limited access to the host environment"` ( details - https://docs.flatpak.org/en/latest/sandbox-permissions.html). As discussed in above mentioned issue, `flatpak extension for flutter` should make it work.

**Comment by gauthamkrishna9991** [comment]
It would be best if Flutter SDK is also packaged as a Flatpak Runtime (which I think would be easier than for snap), then be added as an "Add-on" to the Android Studio App. It could look something like this, but with `Flutter` as an Add-on/Extension Flatpak like, for example, `Proton (community build)` for Steam in GNOME Store:

![steam-flatpak-add-on-screenshot](https://user-images.githubusercontent.com/32835351/137527998-00d2add1-d822-4c50-aec3-971303be3a8e.png)

This has a good side-effect of users not needing to worry about going through the hoops to install Flutter, yet give the users an option to install `Flutter` easily, if they so choose.

It would also make installing Android Studio **much easier** for anyone **not** using Ubuntu, along with Ubuntu, and would give for a much more accessible experience for Systems that does use Flathub, and it only need be done once, rather than worry about multiple builds of the same software.
