### ISSUE TITLE
[tool_crash] FileSystemException: Creation of temporary directory failed, OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123

### ISSUE THREAD

**Issue by thiruraaja** [flutter/flutter#66466]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation of temporary directory failed, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _Directory.createTempSync (dart:io/directory_impl.dart:181:7)
#1      ForwardingDirectory.createTempSync (package:file/src/forwarding/forwarding_directory.dart:30:21)
#2      LocalFileSystem.systemTempDirectory (package:flutter_tools/src/base/file_system.dart:212:47)
#3      ForwardingFileSystem.systemTempDirectory (package:file/src/forwarding/forwarding_file_system.dart:35:49)
#4      new ResidentRunner (package:flutter_tools/src/resident_runner.dart:712:24)
#5      new HotRunner (package:flutter_tools/src/run_hot.dart:77:8)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:530:16)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
```
```
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.20.4 at C:\flutter
    • Framework revision fba99f6cf9 (9 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\fivestarxerox\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\fivestarxerox\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Redmi Note 8 Pro (mobile) • 6d7xgm85amjn49b6 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: fba99f6cf9a14512e461e3122c8ddfaa25394e89

**Comment by darshankawar** [comment]
Although, it look similar to [56824](https://github.com/flutter/flutter/issues/56824) along with the stack trace, the error message is different, `The filename, directory name, or volume label syntax is incorrect., errno = 123`.
Keeping this open for further analysis.

**Comment by jmagman** [comment]
@thiruraaja  Can you attach the log that was written out, it would be something like `flutter_01.log`?  We strip out paths for privacy when for this crash report, but in your case it would be helpful to see what was wrong about the path.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
