### ISSUE TITLE
Base app won't start on latest iOS/XCode version

### ISSUE THREAD

**Issue by mayhew3** [flutter/flutter#66501]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: N/A
3. Go through the iOS Setup steps, and try running the app on my MacBook Air (XCode 12.0, iOS 14.0).

**Expected results:** The example app starting on my device.

**Actual results:** The app failed to start, with a bunch of seemingly unrelated build errors, both on my connected iPhone and on the Simulator. The app runs successfully in Android Studio on my PC.

<details>
  <summary>Logs</summary>

```
(I can't attach the --verbose run, because if I try, I get this error: "There was an error creating your Issue: body is too long (maximum is 65536 characters)." So this is the regular 'flutter run' log.)

mayhews-air:bug01 mayhew3$ flutter run
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running Xcode build...                                                  
                                                   
Xcode build done.                                           26.7s
Failed to build iOS app
Error output from Xcode build:
â†³
    ** BUILD FAILED **


Xcode's output:
â†³
    Invalid depfile:
    /Users/mayhew3/Documents/Projects/flutter/bug01/.dart_tool/flutter_build/ffb
    8fe3791e612bf566f997345bf0cd5/kernel_snapshot.d
    Invalid depfile:
    /Users/mayhew3/Documents/Projects/flutter/bug01/.dart_tool/flutter_build/ffb
    8fe3791e612bf566f997345bf0cd5/kernel_snapshot.d
    Invalid depfile:
    /Users/mayhew3/Documents/Projects/flutter/bug01/.dart_tool/flutter_build/ffb
    8fe3791e612bf566f997345bf0cd5/kernel_snapshot.d
    Invalid depfile:
    /Users/mayhew3/Documents/Projects/flutter/bug01/.dart_tool/flutter_build/ffb
    8fe3791e612bf566f997345bf0cd5/kernel_snapshot.d
    Error: Could not resolve the package 'characters' in
    'package:characters/characters.dart'.
    ../../../../dev/flutter/packages/flutter/lib/src/material/text_field.dart:9:
    8: Error: Not found: 'package:characters/characters.dart'
    import 'package:characters/characters.dart';
           ^
    ../../../../dev/flutter/packages/flutter/lib/widgets.dart:18:1: Error: Not
    found: 'package:characters/characters.dart'
    export 'package:characters/characters.dart';
    ^
    ../../../../dev/flutter/packages/flutter/lib/src/rendering/editable.dart:10:
    8: Error: Not found: 'package:characters/characters.dart'
    import 'package:characters/characters.dart';
           ^
    ../../../../dev/flutter/packages/flutter/lib/src/services/text_formatter.dar
    t:9:8: Error: Not found: 'package:characters/characters.dart'
    import 'package:characters/characters.dart';
           ^
    ../../../../dev/flutter/packages/flutter/lib/src/material/text_field.dart:82
    2:61: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
      int get _currentLength =>
      _effectiveController.value.text.characters.length;
                                                                ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/material/text_field.dart:82
    4:118: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
      bool get _hasIntrinsicError => widget.maxLength != null &&
      widget.maxLength > 0 && _effectiveController.value.text.characters.length
      > widget.maxLength;
                                                                                                                         ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/rendering/editable.dart:244
    :64: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
           assert(obscuringCharacter != null &&
           obscuringCharacter.characters.length == 1),
                                                                   ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/rendering/editable.dart:361
    :35: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
        assert(value != null && value.characters.length == 1);
                                      ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/rendering/editable.dart:567
    :11: Error: 'Characters' isn't a type.
        final Characters remaining = string.characters.skipWhile((String
        currentString) {
              ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/rendering/editable.dart:567
    :41: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
        final Characters remaining = string.characters.skipWhile((String
        currentString) {
                                            ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/rendering/editable.dart:600
    :47: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
        for (final String currentString in string.characters) {
                                                  ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/rendering/editable.dart:602
    :40: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
              !_isWhitespace(currentString.characters.first.toString().codeUnitA
              t(0))) {
                                           ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/services/text_formatter.dar
    t:355:11: Error: 'CharacterRange' isn't a type.
        final CharacterRange iterator = CharacterRange(value.text);
              ^^^^^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/services/text_formatter.dar
    t:355:37: Error: Method not found: 'CharacterRange'.
        final CharacterRange iterator = CharacterRange(value.text);
                                        ^^^^^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/services/text_formatter.dar
    t:356:20: Error: The getter 'characters' isn't defined for the class
    'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
        if (value.text.characters.length > maxLength) {
                       ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/services/text_formatter.dar
    t:375:61: Error: The getter 'characters' isn't defined for the class
    'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
        if (maxLength != null && maxLength > 0 &&
        newValue.text.characters.length > maxLength) {
                                                                ^^^^^^^^^^
    ../../../../dev/flutter/packages/flutter/lib/src/services/text_formatter.dar
    t:378:25: Error: The getter 'characters' isn't defined for the class
    'String'.
    Try correcting the name to the name of an existing getter, or defining a
    getter or field named 'characters'.
          if (oldValue.text.characters.length == maxLength) {
                            ^^^^^^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Acharacters
    %2Fcharacters.dart; message=StandardFileSystem only supports file:* and
    data:* URIs)
    #0      StandardFileSystem.entityForUri
    (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:659:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:853:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile
    (package:frontend_server/frontend_server.dart:574:15)
    <asynchronous suspension>
    #4      _FlutterFrontendCompiler.compile
    (package:flutter_frontend_server/server.dart:43:22)
    #5      starter (package:flutter_frontend_server/server.dart:182:27)
    #6      main
    (file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/star
    ter.dart:9:30)
    #7      _startIsolate.<anonymous closure>
    (dart:isolate-patch/isolate_patch.dart:299:32)
    #8      _RawReceivePortImpl._handleMessage
    (dart:isolate-patch/isolate_patch.dart:168:12)


    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is
    set to 8.0, but the range of supported deployment target versions is 9.0 to
    14.0.99. (in target 'Runner' from project 'Runner')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.
mayhews-air:bug01 mayhew3$ 
```

```
No issues found! (ran in 18.5s)
```

```
mayhews-air:bug01 mayhew3$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.4 at /Users/mayhew3/dev/flutter
    • Framework revision fba99f6cf9 (9 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
 
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3
[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
[✓] Connected device (1 available)
    • iXavier (mobile) • 00008030-0006499A0188802E • ios • iOS 14.0
! Doctor found issues in 2 categories.
```

</details>

**Comment by mayhew3** [comment]
Here is the log for flutter run --verbose:
[iOS_fail.log](https://github.com/flutter/flutter/files/5272452/iOS_fail.log)

**Comment by TahaTesser** [comment]
Hi @mayhew3 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/65723
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
