### ISSUE TITLE
Flutter iOS - Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by nicemanis** [flutter/flutter#66543]
After upgrading from Flutter 1.12.13+hotfix.5 to 1.20.4, the iOS application crashes on initialization:
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

Error occurs in AppDelegate.swift:
```
import UIKit
import Flutter
import flutter_downloader
import CoreBluetooth

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}
```

Console output:
```
2020-09-24 14:04:05.432065+0300 Runner[87839:14013925] flutter: Observatory listening on http://127.0.0.1:53040/zeoO769HNeg=/
2020-09-24 14:04:05.436166+0300 Runner[87839:14013489] Configuring the default Firebase app...
2020-09-24 14:04:05.436279+0300 Runner[87839:14013837] 6.30.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
2020-09-24 14:04:05.475371+0300 Runner[87839:14013489] [Crashlytics] Version 3.14.0 (144)
2020-09-24 14:04:05.479315+0300 Runner[87839:14013850] 6.30.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60702000 started
2020-09-24 14:04:05.479873+0300 Runner[87839:14013843] 6.30.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-09-24 14:04:05.480549+0300 Runner[87839:14013937] 6.30.0 - [Firebase/Analytics][I-ACS025036] App Delegate Proxy is disabled
2020-09-24 14:04:05.516935+0300 Runner[87839:14013489] Configured the default Firebase app __FIRAPP_DEFAULT.
2020-09-24 14:04:05.517122+0300 Runner[87839:14013489] [Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
2020-09-24 14:04:05.532516+0300 Runner[87839:14013489] database path: {some_db_path}
2020-09-24 14:04:05.532766+0300 Runner[87839:14013489] MAXIMUM_CONCURRENT_TASKS = 3
2020-09-24 14:04:05.543060+0300 Runner[87839:14013489] init NSURLSession with id: {some_if}
2020-09-24 14:04:05.543242+0300 Runner[87839:14013489] AllFilesDownloadedMessage: All files have been downloaded
Engine creation error: nilError
2020-09-24 14:04:05.624470+0300 Runner[87839:14013837] 6.30.0 - [Firebase/Analytics][I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
(lldb) 
```

The console output looks the same as with the previous Flutter version, where the app was running successfully; therefore, it's difficult to determine what is the cause of the problem.

Flutter doctor:
```
flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-LV)
    • Flutter version 1.20.4 at {hidden}
    • Framework revision fba99f6cf9 (10 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at {hidden}
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = {hidden}
    • Java binary at: {hidden}
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at {hidden}
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at {hidden}
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 63EC7412-64D1-49C8-B580-57B30BA8A62A • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

Please share any ideas for what could be the problem and let me know if you need any more information.

**Comment by TahaTesser** [comment]
Hi @nicemanis 
Did you update firebase packages too? 
This might a problem firebase core initialization 
Please https://flutter-firebase-docs.web.app/docs/core/usage#default-firebase-app

```
2020-09-24 14:04:05.436166+0300 Runner[87839:14013489] Configuring the default Firebase app...
2020-09-24 14:04:05.436279+0300 Runner[87839:14013837] 6.30.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
2020-09-24 14:04:05.475371+0300 Runner[87839:14013489] [Crashlytics] Version 3.14.0 (144)
```

Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample without firebase
Thank you

**Comment by nicemanis** [comment]
The same output was present with previous Flutter version, where the app was working. Anyway, I will try to update Firebase dependencies and I will let you know if the problem persists.

**Comment by nicemanis** [comment]
I updated the Firebase dependencies. The Android app is working, but for the iOS the same issue still persists.

Here is the console output:
```
2020-09-24 17:59:49.808853+0300 Runner[44381:14382132] 6.26.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
2020-09-24 17:59:49.850784+0300 Runner[44381:14381404] [Firebase/Crashlytics] Version 4.1.1
2020-09-24 17:59:49.874147+0300 Runner[44381:14381404] database path: {hidden}
2020-09-24 17:59:49.874487+0300 Runner[44381:14381404] MAXIMUM_CONCURRENT_TASKS = 3
2020-09-24 17:59:49.890173+0300 Runner[44381:14381404] init NSURLSession with id: {hidden}
2020-09-24 17:59:49.890344+0300 Runner[44381:14381404] AllFilesDownloadedMessage: All files have been downloaded
2020-09-24 17:59:49.914916+0300 Runner[44381:14382160] flutter: Observatory listening on http://127.0.0.1:57039/tm6vGbsi8uM=/
Engine creation error: nilError
(lldb) 
```
`flutter run --verbose` results in a 13K line output, so I don't think I can add it here in comments.
Here are some outputs:
```
[  +28 ms] Warning: Podfile is out of date
             This can cause issues if your application depends on plugins that do not support iOS.
             See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
             If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
           To regenerate the Podfile, run:
             rm ios/Podfile

[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:58928/rTNMzODpb9k=/
[   +8 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

I noticed a message, which said that I need to migrate project to support Xcode 11.4 - https://flutter.dev/docs/development/ios-project-migration

During that, I noticed that my Build Phases have:
- [CP] Check Pods Manifest.lock
- [CP] Embed Pods Frameworks
And I have `Pods_Runner.framework` and `libsqlite3.tbd` in Link Binary With Libraries phase.
I'm not sure if they are necessary after the upgrade.

**Comment by TahaTesser** [comment]
Hi @nicemanis 
Execute `flutter run  --verbose ` from the terminal, copy all the logs paste in a plain text file `.txt` and attach in the comments here 
Also please provide  a complete reproducible minimal code sample without third party packages 
Thank you

**Comment by nicemanis** [comment]
Here is the output of the `flutter run --verbose`:
[tmp2.txt](https://github.com/flutter/flutter/files/5281100/tmp2.txt)

**Comment by nicemanis** [comment]
I found the cause of the issue:

It seems like the problem was caused by an old `libsqlite3.tbd`. I removed the old one and added it again from the iOS 13.6 libraries and now the app is running.

I was using this library because of the `flutter_downloader` package requirements - https://pub.dev/packages/flutter_downloader

**Comment by nicemanis** [comment]
The exception was caused by this code in `AppDelegate.swift`:
```
extension FlutterViewController {
    open override func viewDidLoad() {
        super.viewDidLoad()
        setNeedsStatusBarAppearanceUpdate()
    }

    override open var preferredStatusBarStyle: UIStatusBarStyle {
        if #available(iOS 13.0, *) {
            return .darkContent
        } else {
            return .default
        }
    }
}
```

**Comment by TahaTesser** [comment]
Hi @nicemanis 
Can you please provide your flutter run --verbose and a **complete reproducible code sample without firebase in a GitHub repository** 
Thank you

**Comment by nicemanis** [comment]
1. Create a new project with `flutter create my_app`;
2. Open `my_app/ios/Runner/AppDelegate.swift` and add modify it, so that it looks like this:
```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

extension FlutterViewController {
    open override func viewDidLoad() {
        super.viewDidLoad()
        setNeedsStatusBarAppearanceUpdate()
    }

    override open var preferredStatusBarStyle: UIStatusBarStyle {
        if #available(iOS 13.0, *) {
            return .darkContent
        } else {
            return .default
        }
    }
}

```
3. Run the app and you should get an error:
```
Flutter`flutter::Rasterizer::Setup:
    0x105e215dc <+0>:   pushq  %rbp
    0x105e215dd <+1>:   movq   %rsp, %rbp
    0x105e215e0 <+4>:   pushq  %r15
    0x105e215e2 <+6>:   pushq  %r14
    0x105e215e4 <+8>:   pushq  %r12
    0x105e215e6 <+10>:  pushq  %rbx
    0x105e215e7 <+11>:  subq   $0x10, %rsp
    0x105e215eb <+15>:  movq   %rdi, %rbx
    0x105e215ee <+18>:  movq   (%rsi), %rax
    0x105e215f1 <+21>:  movq   $0x0, (%rsi)
    0x105e215f8 <+28>:  movq   0x48(%rdi), %rdi
    0x105e215fc <+32>:  movq   %rax, 0x48(%rbx)
    0x105e21600 <+36>:  testq  %rdi, %rdi
    0x105e21603 <+39>:  je     0x105e2160b               ; <+47>
    0x105e21605 <+41>:  movq   (%rdi), %rax
    0x105e21608 <+44>:  callq  *0x8(%rax)
    0x105e2160b <+47>:  cmpb   $0x0, 0xb0(%rbx)
    0x105e21612 <+54>:  je     0x105e2162a               ; <+78>
    0x105e21614 <+56>:  movq   0xa8(%rbx), %rsi
    0x105e2161b <+63>:  movzbl 0xa0(%rbx), %edx
    0x105e21622 <+70>:  movq   %rbx, %rdi
    0x105e21625 <+73>:  callq  0x105e216fe               ; flutter::Rasterizer::SetResourceCacheMaxBytes(unsigned long, bool)
    0x105e2162a <+78>:  movq   0x50(%rbx), %rdi
    0x105e2162e <+82>:  callq  0x105e0be14               ; flutter::CompositorContext::OnGrContextCreated()
    0x105e21633 <+87>:  movq   0x48(%rbx), %rdi
->  0x105e21637 <+91>:  movq   (%rdi), %rax
    0x105e2163a <+94>:  callq  *0x30(%rax)
    0x105e2163d <+97>:  testq  %rax, %rax
    0x105e21640 <+100>: je     0x105e216f1               ; <+277>
    0x105e21646 <+106>: leaq   0x10(%rbx), %r15
    0x105e2164a <+110>: leaq   -0x28(%rbp), %r12
    0x105e2164e <+114>: movq   %r12, %rdi
    0x105e21651 <+117>: movq   %r15, %rsi
    0x105e21654 <+120>: callq  0x105afcee4               ; flutter::TaskRunners::GetPlatformTaskRunner() const
    0x105e21659 <+125>: movq   (%r12), %rdi
    0x105e2165d <+129>: movq   (%rdi), %rax
    0x105e21660 <+132>: callq  *0x30(%rax)
    0x105e21663 <+135>: movq   %rax, %r14
    0x105e21666 <+138>: movq   (%r12), %rdi
    0x105e2166a <+142>: testq  %rdi, %rdi
    0x105e2166d <+145>: je     0x105e21684               ; <+168>
    0x105e2166f <+147>: lock   
    0x105e21670 <+148>: decl   0x8(%rdi)
    0x105e21673 <+151>: jne    0x105e21684               ; <+168>
    0x105e21675 <+153>: addq   $0x8, %rdi
    0x105e21679 <+157>: movq   -0x8(%rdi), %rax
    0x105e2167d <+161>: addq   $-0x8, %rdi
    0x105e21681 <+165>: callq  *0x8(%rax)
    0x105e21684 <+168>: leaq   -0x28(%rbp), %r12
    0x105e21688 <+172>: movq   %r12, %rdi
    0x105e2168b <+175>: movq   %r15, %rsi
    0x105e2168e <+178>: callq  0x105afcf32               ; flutter::TaskRunners::GetRasterTaskRunner() const
    0x105e21693 <+183>: movq   (%r12), %rdi
    0x105e21697 <+187>: movq   (%rdi), %rax
    0x105e2169a <+190>: callq  *0x30(%rax)
    0x105e2169d <+193>: movq   %rax, %r15
    0x105e216a0 <+196>: movq   (%r12), %rdi
    0x105e216a4 <+200>: testq  %rdi, %rdi
    0x105e216a7 <+203>: je     0x105e216be               ; <+226>
    0x105e216a9 <+205>: lock   
    0x105e216aa <+206>: decl   0x8(%rdi)
    0x105e216ad <+209>: jne    0x105e216be               ; <+226>
    0x105e216af <+211>: addq   $0x8, %rdi
    0x105e216b3 <+215>: movq   -0x8(%rdi), %rax
    0x105e216b7 <+219>: addq   $-0x8, %rdi
    0x105e216bb <+223>: callq  *0x8(%rax)
    0x105e216be <+226>: movl   $0x28, %edi
    0x105e216c3 <+231>: callq  0x106338f4c               ; symbol stub for: operator new(unsigned long)
    0x105e216c8 <+236>: movq   %rax, %r12
    0x105e216cb <+239>: movq   %rax, %rdi
    0x105e216ce <+242>: movq   %r14, %rsi
    0x105e216d1 <+245>: movq   %r15, %rdx
    0x105e216d4 <+248>: callq  0x105b05558               ; fml::RasterThreadMerger::RasterThreadMerger(fml::TaskQueueId, fml::TaskQueueId)
    0x105e216d9 <+253>: movq   0xd0(%rbx), %rdi
    0x105e216e0 <+260>: movq   %r12, 0xd0(%rbx)
    0x105e216e7 <+267>: testq  %rdi, %rdi
    0x105e216ea <+270>: je     0x105e216f1               ; <+277>
    0x105e216ec <+272>: callq  0x105af952a               ; fml::RefCountedThreadSafe<fml::RasterThreadMerger>::Release() const
    0x105e216f1 <+277>: addq   $0x10, %rsp
    0x105e216f5 <+281>: popq   %rbx
    0x105e216f6 <+282>: popq   %r12
    0x105e216f8 <+284>: popq   %r14
    0x105e216fa <+286>: popq   %r15
    0x105e216fc <+288>: popq   %rbp
    0x105e216fd <+289>: retq   
```

The app crashes on `0x105e21637 <+91>:  movq   (%rdi), %rax` with `io.flutter.1.raster (10): EXC_BAD_ACCESS (code=1, address=0x0)`

The app doesn't seem to be running from terminal due to #65349 issue.
See the `flutter run --verbose` log in attachments. 
[log.txt](https://github.com/flutter/flutter/files/5291256/log.txt)

**Comment by TahaTesser** [comment]
Hi @nicemanis 
I can reproduce the issue
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/56622
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by hsnbsst** [comment]
I have the same problem. I couldn't get rid of this problem. Can you help me?

`Thread 1: EXC_BAD_ACCESS (code=50, address=0x102ec7000)`
```
dyld_sim`memcmp:
    0x1026a3231 <+0>:  pushq  %rbp
    0x1026a3232 <+1>:  movq   %rsp, %rbp
    0x1026a3235 <+4>:  testq  %rdx, %rdx
    0x1026a3238 <+7>:  je     0x1026a3252               ; <+33>
    0x1026a323a <+9>:  xorl   %ecx, %ecx
->  0x1026a323c <+11>: movzbl (%rdi,%rcx), %eax
    0x1026a3240 <+15>: movzbl (%rsi,%rcx), %r8d
    0x1026a3245 <+20>: cmpb   %r8b, %al
    0x1026a3248 <+23>: jne    0x1026a3256               ; <+37>
    0x1026a324a <+25>: incq   %rcx
    0x1026a324d <+28>: cmpq   %rcx, %rdx
    0x1026a3250 <+31>: jne    0x1026a323c               ; <+11>
    0x1026a3252 <+33>: xorl   %eax, %eax
    0x1026a3254 <+35>: jmp    0x1026a3259               ; <+40>
    0x1026a3256 <+37>: subl   %r8d, %eax
    0x1026a3259 <+40>: popq   %rbp
    0x1026a325a <+41>: retq   

```

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by aliazimoshan** [comment]
I have the same problem. I fix it by switching to the stable channel.
```
flutter channel stable
flutter update
flutter clean
```
and build it again,
Hope it works.

**Comment by augustocadini** [comment]
@aliazimoshan when I tried use `flutter update` a error is triggered:

```
$ flutter update
Could not find a command named "update".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

```

**Comment by aliazimoshan** [comment]
> @aliazimoshan when I tried use `flutter update` a error is triggered:
> 
> ```
> $ flutter update
> Could not find a command named "update".
> 
> 
> Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
> ```

It was my fault,
you should use 
```flutter upgrade```

**Comment by rogervdf** [comment]
> I have the same problem. I fix it by switching to the stable channel.
> 
> ```
> flutter channel stable
> flutter upgrade
> flutter clean
> ```
> 
> and build it again,
> Hope it works.

That worked for me: moving from master to stable.

Strangely enough this bug only appeared in the simulator, no issues on physical iOS devices.
