### ISSUE TITLE
crash in gestures

### ISSUE THREAD

**Issue by nydlmaster** [flutter/flutter#66549]
<details> 
<summary>logs</summary> 

```bash
Restarted application in 2,377ms.
D/PhoneWindow( 7595): setNavigationBarColor: fffafafa
D/PhoneWindow( 7595): setNavigationBarColor: fffafafa
W/DynamiteModule( 7595): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 7595): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 7595): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null':
is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
[38;5;244m#2      ScrollableState._handleDragDown[39;49m 
 package:flutter/…/widgets/scrollable.dart
[38;5;244m#3      DragGestureRecognizer._checkDown.<anonymous closure>[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#4      GestureRecognizer.invokeCallback[39;49m 
 package:flutter/…/gestures/recognizer.dart
[38;5;244m#5      DragGestureRecognizer._checkDown[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#6      DragGestureRecognizer.addAllowedPointer[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#7      GestureRecognizer.addPointer[39;49m 
 package:flutter/…/gestures/recognizer.dart
[38;5;244m#8      RawGestureDetectorState._handlePointerDown[39;49m 
 package:flutter/…/widgets/gesture_detector.dart
[38;5;244m#9      RenderPointerListener.handleEvent[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#10     GestureBinding.dispatchEvent[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#11     GestureBinding._handlePointerEvent[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#12     GestureBinding._flushPointerEventQueue[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#13     GestureBinding._handlePointerDataPacket[39;49m 
 package:flutter/…/gestures/binding.dart
[38;5;244m#17     _invoke1  (dart:ui/hooks.dart:267:10)[39;49m
[38;5;244m#18     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)[39;49m
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onDown"
Recognizer:
  VerticalDragGestureRecognizer#0539a
════════════════════════════════════════════════════════════════════════════════════════════════════

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while handling a gesture:[39;49m
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      ScrollableState._handleDragDown[39;49m 
 package:flutter/…/widgets/scrollable.dart
[38;5;244m#3      DragGestureRecognizer._checkDown.<anonymous closure>[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#4      GestureRecognizer.invokeCallback[39;49m 
 package:flutter/…/gestures/recognizer.dart
[38;5;244m#5      DragGestureRecognizer._checkDown[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m#6      DragGestureRecognizer.addAllowedPointer[39;49m 
 package:flutter/…/gestures/monodrag.dart
[38;5;244m...[39;49m
[38;5;244mHandler: "onDown"[39;49m
[38;5;244mRecognizer: VerticalDragGestureRecognizer#0539a[39;49m
    [38;5;244mstart behavior: down[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
I/Surface ( 7595): opservice is null false
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null': is not true.

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null': is not true.

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 527 pos 12: '_drag == null': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 536 pos 12: '_drag == null': is not true.

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 536 pos 12: '_drag == null': is not true.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
Another exception was thrown: Build scheduled during frame.

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
Build scheduled during frame.
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
```

</details>

**Comment by TahaTesser** [comment]
Hi @nydlmaster 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/65020
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
