### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.

### ISSUE THREAD

**Issue by SandeshGitHub2077** [flutter/flutter#66579]
![issue](https://user-images.githubusercontent.com/63229947/94191409-160d2d80-fecb-11ea-9fa4-b04cdad12295.PNG)
Launching lib\main.dart on XT1033 in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:111)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: No build receipt resource found.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:97)
	... 1 more
Exception: Gradle task assembleDebug failed with exit code 1

How to fix this??

**Comment by darshankawar** [comment]
@SandeshGitHub2077 You seem to already have opened same issue yesterday, [66523](https://github.com/flutter/flutter/issues/66523).
Please don't open multiple issues for same reason.
Closing this as duplicate.

**Comment by SandeshGitHub2077** [comment]
> 
> 
> @SandeshGitHub2077 You seem to already have opened same issue yesterday, [66523](https://github.com/flutter/flutter/issues/66523).
> Please don't open multiple issues for same reason.
> Closing this as duplicate.

Sorry sir...still new to github :)
