### ISSUE TITLE
flutter build apk stuck after android asset bundle complete

### ISSUE THREAD

**Issue by dsr2812** [flutter/flutter#66732]
Whenever i am running `flutter build apk` with verbose the process get stuck after showing flutter "android asset bundle complete" . This process gets in something infinite loop and taking up all the 30-40GB of memory on my MAC. I don't know what is wrong with it. I have tried every solution provided over here  but still no luck. flutter run is running successfully with no errors. The only problem is with the flutter build apk for the release version.

<details><summary>flutter doctor -v result</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.4 at /Users/divyanshutiwari/flutter
    • Framework revision fba99f6cf9 (12 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/divyanshutiwari/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/divyanshutiwari/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
</details>

After i kill the process from Activity Monitor it shows this in log:

<details><summary>Logs</summary>

```
[+263451 ms] [  +95 ms] Persisting file store
[ +140 ms] [+263186 ms] Dart snapshot generator failed with exit code -15
[ +128 ms] [ +167 ms] Done persisting file store
[        ] [  +49 ms] "flutter assemble" took 345,989ms.
[        ] [  +15 ms] ensureAnalyticsSent: 12ms
[        ] [   +4 ms] Running shutdown hooks
[        ] [   +1 ms] Shutdown hooks complete
[        ] [        ] exiting with code 1
[   +3 ms] [  +34 ms] Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -15
[        ]            #0      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:247:7)
[        ]            <asynchronous suspension>
[   +1 ms]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:795:27)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[  +21 ms]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +4 ms]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +6 ms]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #10     Node.computeChanges (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +2 ms]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[ +218 ms]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #19     FileStore.diffFileList (package:flutter_tools/src/build_system/file_store.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +2 ms]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:410:22)
[  +34 ms]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #35     FileStore._hashFile (package:flutter_tools/src/build_system/file_store.dart)
[ +382 ms]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #42     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #43     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #44     _CustomZone.run (dart:async/zone.dart:1093:19)
[  +93 ms]            #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[  +18 ms]            #49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[        ] [  +27 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:238:7)
[  +37 ms]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[  +15 ms]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[  +11 ms]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[  +36 ms]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +5 ms]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:410:22)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[  +28 ms]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[   +3 ms]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #35     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[   +1 ms]            #36     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ]            #37     _rootRunBinary (dart:async/zone.dart:1214:47)
[   +6 ms]            #38     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ]            #39     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[        ]            #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[        ]            #41     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ]            #42     Future._completeError (dart:async/future_impl.dart:537:5)
[        ]            #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ]            #44     AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart)
[        ]            #45     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #46     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[  +16 ms]            #47     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #49     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #50     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +2 ms]            #51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #53     AOTSnapshotter.build (package:flutter_tools/src/base/build.dart)
[        ]            #54     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #55     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[  +21 ms]            #56     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #58     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #59     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #60     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #61     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #62     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
[        ]            #63     _rootRunUnary (dart:async/zone.dart:1198:47)
[  +33 ms]            #64     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #65     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #66     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #67     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #68     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #69     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #70     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #71     _CustomZone.run (dart:async/zone.dart:1093:19)
[   +3 ms]            #72     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #73     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[  +28 ms]            #74     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #75     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #76     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[ +104 ms] > Task :app:compileFlutterBuildRelease FAILED
[ +989 ms] 1 actionable task: 1 executed
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/divyanshutiwari/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 896
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/Users/divyanshutiwari/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 6m 2s
[+1215 ms] Running Gradle task 'assembleRelease'... (completed in 364.0s, longer than expected)
[  +45 ms] "flutter apk" took 367,849ms.
[  +35 ms] Gradle task assembleRelease failed with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:411:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +260 ms] ensureAnalyticsSent: 254ms
[   +9 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
</details>

**Comment by pedromassangocode** [comment]
Hi @dsr2812 
Are you having the sample problem while running `flutter build apk` in the default Flutter sample app?
Please provide your `flutter build appbundle --verbose` and `pubspec.yaml`.
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
