### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: Отказано в доступе., errno = 5

### ISSUE THREAD

**Issue by Okladnoj** [flutter/flutter#66733]
## Command
```
flutter --quiet assemble --depfile C:\Work\radoi\bitbucket\example\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Work\radoi\bitbucket\example\build\app\intermediates\flutter\debug -dTargetFile=C:\Work\radoi\bitbucket\example\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=flutter.inspector.structuredErrors%3Dtrue debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: Отказано в доступе.
, errno = 5
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:126:11)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:536:26)
#4      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _runZoned (dart:async/zone.dart:1630:10)
#12     runZoned (dart:async/zone.dart:1550:10)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _runZoned (dart:async/zone.dart:1630:10)
```
```
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale ru-RU)
    • Flutter version 1.20.4 at C:\fluttersdk\flutter
    • Framework revision fba99f6cf9 (12 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\OKJI\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\OKJI\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\OKJI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Redmi Note 8 Pro (mobile) • gubexwivz5e6eyt8 • android-arm64 • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1+11
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b041144f833e05cf463b8887fa12efdec9493488
### Plugins
bitbucket
sqflite
audio_service-0.11.2
connectivity-0.4.9+3
connectivity_for_web-0.3.1+2
connectivity_macos-0.1.0+5
flutter_isolate-1.0.0+14
in_app_purchase-0.3.4+9
in_app_review-0.2.0+4
just_audio-0.1.10
package_info-0.4.3
path_provider-1.6.18
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
phone_state_i-0.0.3
shared_preferences-0.5.12
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+1
url_launcher-5.7.2
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+1

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/19fbe98df3672fdf636a59e57a1dcbeb09e7fc2e
