### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for C:\Users\JAI\Desktop\CarieMe\android\gradlew.bat.

### ISSUE THREAD

**Issue by appa204544** [flutter/flutter#66803]
## Command
```
flutter run --machine --target lib\main.dart -d 157ccc1d --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\JAI\Desktop\CarieMe\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:384:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:102:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:513:28)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```
```
[✓] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.17.3 at E:\flutter android content\softwares\flutter SDK\flutter
    • Framework revision b041144f83 (4 months ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\flutter android content\softwares\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\flutter android content\softwares\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\JAI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Redmi Note 7 • 157ccc1d • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
cloud_firestore-0.13.7
cloud_firestore_web-0.1.1+2
connectivity-0.4.8+5
connectivity_macos-0.1.0+3
firebase_auth-0.16.1
firebase_auth_web-0.1.3+1
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_storage-3.1.6
flutter_facebook_login-3.0.0
flutter_plugin_android_lifecycle-1.0.8
flutter_ringtone_player-2.0.0
flutter_web_browser-0.11.0
fluttertoast-7.0.4
geocoder-0.2.1
geolocator-5.3.2+2
google_api_availability-2.0.4
google_maps_flutter-0.5.28+1
image_picker-0.6.7+6
location-3.0.2
location_permissions-3.0.0+1
location_web-1.0.0
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
permission_handler-5.0.1+1
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1

**Comment by pedromassangocode** [comment]
Hi @appa204544 
I see there's an open issue (https://github.com/flutter/flutter/issues/56975) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
