### ISSUE TITLE
Scaffold's showBottomSheet cannot receive data from Navigator.pop

### ISSUE THREAD

**Issue by daniel-mf** [flutter/flutter#66837]
The `result` passed to `Navigator.pop(context, result)` never reaches the `PersistentBottomSheetController.closed`.

I think maybe the problem is [here](https://github.com/flutter/flutter/blob/fba99f6cf9a14512e461e3122c8ddfaa25394e89/packages/flutter/lib/src/material/scaffold.dart#L1855), it seems that `value` is never passed to `completer.complete();`

Here is a reproduction at [dartpad](https://dartpad.dev/3af34ab9a4c5c6d8ea14b224d5d03141)

**Expected results:**
"Lorem ipsum" should be printed to the console after clicking the button that lays inside the bottom sheet.

**Actual results:**
`null` is printed instead.

<details>
  <summary>Flutter doctor output</summary>

```

[✓] Flutter (Channel master, 1.22.0-10.0.pre.327, on Mac OS X 10.15.6 19G2021 x86_64, locale pt-BR)
    • Flutter version 1.22.0-10.0.pre.327 at /Users/daniel/flutter
    • Framework revision fb8163260c (5 days ago), 2020-09-23 12:34:00 -0700
    • Engine revision 3e7ca5b869
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Platform android-29, build-tools 30.0.0-rc4
    • ANDROID_HOME = /Users/daniel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2018.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.405, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.22.0-10.0.pre.405 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9d7bdb5903 (2 hours ago), 2020-09-28 22:46:21 -0700
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server  • web-javascript • Flutter Tools
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!
```

</details>

**Comment by Peng-Qian** [comment]
Same issue, any updates?

**Comment by Dancovich** [comment]
This issue still happens in Flutter 2.2.2. Below is some test code that can be pasted in the default template and the result flutter doctor.

As @daniel-mf said, in `scaffold.dart` line 2518 the method calls `completer.complete()` without a value. In Flutter 2.2.2 and null safety, this has the added issue of throwing an exception.

`type 'Null' is not a subtype of type 'FutureOr<int>'`

The only way to avoid this issue is to either not pass a generic type to `PersistentBottomSheetController<T>` or pass `<dynamic>,` but this only solves the exception, it doesn't solve the issue of values passed to pop never reaching `PersistentBottomSheetController.closed`

Code and flutter doctor below

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  // This throws an exception when closing the bottom sheet
  //PersistentBottomSheetController<int>? _bsController;

  // This fixes the exception but values passed to pop still don't reach PersistentBottomSheetController.closed
  PersistentBottomSheetController<dynamic>? _bsController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Press the FAB to test this bug',
            ),
          ],
        ),
      ),
      floatingActionButton: Builder(
        builder: (context) => FloatingActionButton(
          onPressed: () => _switchBottomSheet(context),
          tooltip: 'Increment',
          child: Icon(Icons.add),
        ),
      ),
    );
  }

  void _switchBottomSheet(BuildContext context) {
    if (_bsController == null) {
      _bsController = Scaffold.of(context).showBottomSheet(
        (context) => _TestBottomSheet(),
        backgroundColor: Colors.green[100],
      );
      _bsController?.closed.then((value) => debugPrint(
          'Pressing the button inside the bottom sheet returned $value'));
    } else {
      _bsController?.close();
      _bsController = null;
    }
  }
}

class _TestBottomSheet extends StatefulWidget {
  _TestBottomSheet({Key? key}) : super(key: key);

  @override
  __TestBottomSheetState createState() => __TestBottomSheetState();
}

class __TestBottomSheetState extends State<_TestBottomSheet> {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      height: 300,
      child: Center(
        child: TextButton(
          child: Text('Press me'),
          onPressed: () => Navigator.of(context).pop(100),
        ),
      ),
    );
  }
}
```

flutter doctor
```
flutter doctor -v                         
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [versÃ£o 10.0.19042.1052], locale pt-BR)
    • Flutter version 2.2.2 at D:\dcvia\Desenvolvimento\Android\flutter2
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\dcvia\Desenvolvimento\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\dcvia\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\dcvia\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.8
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • SM G950F (mobile) • ce11182b72a0ba3a02 • android-arm64  • Android 9 (API 28)
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 1 category.
```

**Comment by darieloper** [comment]
The issue still happens in 2.0.6, any udate?

**Comment by meg4cyberc4t** [comment]
The issue still happens in 3.0.2, any update?

**Comment by ksanbormukhim** [comment]
is there any update on this issue or a work arround

**Comment by umairali4433** [comment]
same issue from my side any solution??

**Comment by maheshmnj** [comment]
Reproducible on stable 3.3 and master 3.7, The value returned is null

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(debugShowCheckedModeBanner: false, home: Home());
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Bottom Sheet Test')),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          MyWidget(),
          ElevatedButton(
              onPressed: () async {
                final result = await Navigator.push(context,
                    MaterialPageRoute(builder: (context) {
                  return const NewPage();
                }));
                print(result);
              },
              child: const Text('Navigate Route'))
        ],
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        child: const Text('Open Bottom Sheet'),
        onPressed: () async {
          final controller = showBottomSheet<String>(
            context: context,
            builder: (context) {
              return Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text(
                        'The following button pops the sheet with data.\n'
                        'But the data cannot be received by the controller.'),
                    ElevatedButton(
                      child: const Text('Pop the sheet'),
                      onPressed: () {
                        Navigator.of(context).pop('Lorem ipsum');
                      },
                    ),
                  ],
                ),
              );
            },
          );

          /// result is a Future<String>
          final result = await controller.closed;
          print(result); // This should print 'Lorem ipsum'.
        },
      ),
    );
  }
}

class NewPage extends StatefulWidget {
  const NewPage({Key? key}) : super(key: key);

  @override
  State<NewPage> createState() => _NewPageState();
}

class _NewPageState extends State<NewPage> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Container(
        color: Colors.red,
        child: ElevatedButton(
            onPressed: () {
              Navigator.of(context).pop("Lorem ipsum");
            },
            child: const Text('Pop Route')),
      ),
    );
  }
}

```
</details> 


<details>
<summary>logs</summary>

```
Restarted application in 345ms.
Reloaded 1 of 832 libraries in 118ms (compile: 18 ms, reload: 41 ms, reassemble: 51 ms).
Reloaded 1 of 832 libraries in 114ms (compile: 19 ms, reload: 49 ms, reassemble: 36 ms).
flutter: Lorem ipsum
Reloaded 1 of 832 libraries in 112ms (compile: 15 ms, reload: 44 ms, reassemble: 42 ms).

════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'Null' is not a subtype of type 'FutureOr<String>'

When the exception was thrown, this was the stack
#1      ScaffoldState._buildBottomSheet.removeCurrentBottomSheet
#2      ScaffoldState._buildBottomSheet.<anonymous closure>
#3      LocalHistoryEntry._notifyRemoved
#4      LocalHistoryRoute.didPop
#5      _RouteEntry.handlePop
#6      NavigatorState._flushHistoryUpdates
#7      NavigatorState.pop
#8      MyWidget.build.<anonymous closure>.<anonymous closure>.<anonymous closure>
#9      _InkResponseState.handleTap
#10     GestureRecognizer.invokeCallback
#11     TapGestureRecognizer.handleTapUp
#12     BaseTapGestureRecognizer._checkUp
#13     BaseTapGestureRecognizer.acceptGesture
#14     GestureArenaManager.sweep
#15     GestureBinding.handleEvent
#16     GestureBinding.dispatchEvent
#17     RendererBinding.dispatchEvent
#18     GestureBinding._handlePointerEventImmediately
#19     GestureBinding.handlePointerEvent
#20     GestureBinding._flushPointerEventQueue
#21     GestureBinding._handlePointerDataPacket
#22     _invoke1 (dart:ui/hooks.dart:167:13)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided one frame from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#82b05
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(179.7, 480.3)
    finalLocalPosition: Offset(44.7, 8.8)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by jcho0216** [comment]
any updates? still having this problem

**Comment by vinodlee** [comment]
I got this error

Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dev/navigation_builder-0.0.3/lib/src/rm_scaffold.dart:102:3: Error: Expected 0 type arguments.
  PersistentBottomSheetController<T> showBottomSheet<T>(
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/navigation_builder-0.0.3/lib/src/rm_scaffold.dart:124:29: Error: Expected 0 type arguments.
    final r = scaffoldState.showBottomSheet<T>(
                            ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

Need help for this.

**Comment by omarfarukdev** [comment]
Having the same problem

**Comment by mfurkanyuceal** [comment]
Same Problem
