### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/cvdtc/Library/Android/sdk/build-tools/30.0.2/aapt.

### ISSUE THREAD

**Issue by msaprojects** [flutter/flutter#66875]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=9585865a --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/cvdtc/Library/Android/sdk/build-tools/30.0.2/aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:419:51)
#3      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:520:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:368:31)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
```
```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-ID)
    • Flutter version 1.20.3 at /Users/cvdtc/Developer/flutter
    • Framework revision 216dee60c0 (4 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/cvdtc/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    ✗ Android SDK file not found: /Users/cvdtc/Library/Android/sdk/build-tools/30.0.2/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Redmi Note 9 Pro (mobile) • 9585865a • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 216dee60c0cc9449f0b29bcf922974d612263e24
### Plugins
firebase_core-0.5.0
firebase_core_web-0.2.0
firebase_messaging-7.0.0
flutter_plugin_android_lifecycle-1.0.8
local_auth-0.6.3+1
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7

**Comment by darshankawar** [comment]
@msaprojects 
There's similar open issue describing your case, [54418](https://github.com/flutter/flutter/issues/54418).
Please follow-up there for updates.
Closing this as duplicate.
