### ISSUE TITLE
[Windows]: Exception: Build process failed.

### ISSUE THREAD

**Issue by Kassan424kh** [flutter/flutter#66882]
Cannot start Windows Application

```LOG
[        ]   flutter_window.obj : error LNK2019: unresolved external symbol "public: struct tagRECT __cdecl Win32Window::GetClientArea(void)" (?GetClientArea@Win32Window@@QEAA?AUtagRECT@@XZ) referenced in
function "protected: virtual bool __cdecl FlutterWindow::OnCreate(void)" (?OnCreate@FlutterWindow@@MEAA_NXZ)
[C:\Users\khali\Desktop\projects\bh_app\flutter_berichtsheft_app\build\windows\runner\flutter_berichtsheft_app.vcxproj]
[        ]   flutter_window.obj : error LNK2019: unresolved external symbol "protected: virtual bool __cdecl Win32Window::OnCreate(void)" (?OnCreate@Win32Window@@MEAA_NXZ) referenced in function "protected:
virtual bool __cdecl FlutterWindow::OnCreate(void)" (?OnCreate@FlutterWindow@@MEAA_NXZ) [C:\Users\khali\Desktop\projects\bh_app\flutter_berichtsheft_app\build\windows\runner\flutter_berichtsheft_app.vcxproj]
[        ]   C:\Users\khali\Desktop\projects\bh_app\flutter_berichtsheft_app\build\windows\runner\Debug\flutter_berichtsheft_app.exe : fatal error LNK1120: 2 unresolved externals
[C:\Users\khali\Desktop\projects\bh_app\flutter_berichtsheft_app\build\windows\runner\flutter_berichtsheft_app.vcxproj]
[        ]     0 Warning(s)
[        ]     3 Error(s)
[        ] Time Elapsed 00:00:07.81
[  +17 ms] Building Windows application... (completed in 8.3s)
[        ] Exception: Build process failed.
[   +1 ms] "flutter run" took 8,820ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:612:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:985:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```LOG
-> flutter doctor -v
[√] Flutter (Channel master, 1.22.0-10.0.pre.403, on Microsoft Windows [Version 10.0.19041.508], locale en-DE)
    • Flutter version 1.22.0-10.0.pre.403 at C:\src\flutter
    • Framework revision 975cf9af59 (3 hours ago), 2020-09-28 23:42:03 -0400
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\\Users\\khali\\AppData\\Local\\Android\\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\\Users\\khali\\AppData\\Local\\Android\\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 85.0.564.63

• No issues found!

```

**Comment by Kassan424kh** [comment]
it work's after I used 
```CMD
flutter upgrade --force
```

**Comment by TahaTesser** [comment]
Hi @Kassan424kh 
`flutter upgrade --force` updates your flutter channel to the latest version, if you're not experiencing this issue on the latest `master`, I feel safe to close the issue,  If you disagree, please write in the comments and I will reopen it.
Thank you
