### ISSUE TITLE
Accepting Android SDK licenses by running flutter doctor --android-licenses crashes

### ISSUE THREAD

**Issue by Andrewngabriel** [flutter/flutter#66907]
Running `flutter doctor --android-licenses` throws the following error message:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

**Environment:**

- OS: Mac OS High Sierra
- Flutter channel: master
- Flutter version: 1.22.0-10.0.pre.406
- Dart: 2.11.0 (build 2.11.0-176.0.dev)

**Steps to reproduce:**

1. Install Flutter v1.22.0-10.0.pre.406 
2. Run `flutter doctor` and ensure that there are Android SDK licenses that are not accepted.
3. Run `flutter doctor --android-licenses`

**Comment by darshankawar** [comment]
@Andrewngabriel 
Can you try [this](https://github.com/flutter/flutter/issues/56778#issuecomment-628926864) solution and see if it works for you?
Thanks.

**Comment by liudonghua123** [comment]
I have the same issue. The following is the console log.

```cmd
C:\Users\Liu.D.H>flutter upgrade                                                                                        Upgrading Flutter from D:\apps\flutter...                                                                               Checking Dart SDK version...                                                                                            Downloading Dart SDK from Flutter engine 3a73d073c8bedb678d82ee78daf05037b3a7a85e...                                    Building flutter tool...
Running pub upgrade...

Upgrading engine...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading Material fonts...                                       1.2s
Downloading Android Maven dependencies...                         104.1s
Downloading android-arm-profile/windows-x64 tools...                1.1s
Downloading android-arm-release/windows-x64 tools...                1.0s
Downloading android-arm64-profile/windows-x64 tools...              1.0s
Downloading android-arm64-release/windows-x64 tools...              0.8s
Downloading android-x64-profile/windows-x64 tools...                0.8s
Downloading android-x64-release/windows-x64 tools...                0.8s
Downloading android-x86 tools...                                   11.5s
Downloading android-x64 tools...                                   14.0s
Downloading android-arm tools...                                    5.5s
Downloading android-arm-profile tools...                            3.8s
Downloading android-arm-release tools...                            2.7s
Downloading android-arm64 tools...                                  5.4s
Downloading android-arm64-profile tools...                          3.4s
Downloading android-arm64-release tools...                          2.1s
Downloading android-x64-profile tools...                            2.6s
Downloading android-x64-release tools...                            1.8s
Downloading android-x86-jit-release tools...                        3.5s
Downloading package sky_engine...                                   0.9s
Downloading flutter_patched_sdk tools...                            6.2s
Downloading flutter_patched_sdk_product tools...                    5.7s
Downloading windows-x64 tools...                                   10.6s
Downloading windows-x64/font-subset tools...                        1.2s

Flutter 1.23.0-7.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision db6e2d8aa5 (9 days ago) • 2020-09-25 06:47:03 -0400
Engine • revision 3a73d073c8
Tools • Dart 2.11.0 (build 2.11.0-161.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
[✓] Android Studio (version 4.0)
[✓] VS Code, 64-bit edition (version 1.49.2)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝


C:\Users\Liu.D.H>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

C:\Users\Liu.D.H>java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

C:\Users\Liu.D.H>where java
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe

C:\Users\Liu.D.H>set PATH=C:\Program Files\Java\jdk1.8.0_191\bin\;%PATH%

C:\Users\Liu.D.H>where java
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe

C:\Users\Liu.D.H>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

C:\Users\Liu.D.H>java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

C:\Users\Liu.D.H>
```

**Comment by liudonghua123** [comment]
I can fix it via change the `JAVA_HOME` environment.

```cmd
C:\Users\Liu.D.H>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

C:\Users\Liu.D.H>java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

C:\Users\Liu.D.H>where java
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe

C:\Users\Liu.D.H>set PATH=C:\Program Files\Java\jdk1.8.0_191\bin\;%PATH%

C:\Users\Liu.D.H>where java
C:\Program Files\Java\jdk1.8.0_191\bin\java.exe
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe

C:\Users\Liu.D.H>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

C:\Users\Liu.D.H>java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

C:\Users\Liu.D.H>echo %JAVA_HOME%
C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\

C:\Users\Liu.D.H>set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_191\

C:\Users\Liu.D.H>flutter doctor --android-licenses
All SDK package licenses accepted.======] 100% Computing updates...


C:\Users\Liu.D.H>
```

see https://github.com/flutter/flutter/issues/62924#issuecomment-668958881.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by shlovee** [comment]
Hello,
I also faced this issue but [this](https://github.com/flutter/flutter/issues/57017) note helped me to resolve the issue.
In short, JDK 1.8 needs to be installed if the advanced JDK version is being used.

**Comment by joaomantovani** [comment]
This helped to me on linux:

```
sudo apt-get install libc6-dev-i386 lib32z1 openjdk-8-jdk
```

And check this option on Android Studio

![image](https://user-images.githubusercontent.com/5152197/101801337-f4e0d400-3aec-11eb-8f09-7be39b85dbac.png)

**Comment by YouChuantong** [comment]
> 这在Linux上对我有所帮助：
> 
> ```
> sudo apt-get install libc6-dev-i386 lib32z1 openjdk-8-jdk
> ```
> 
> 并在Android Studio上选中此选项
> 
> ![图像](https://user-images.githubusercontent.com/5152197/101801337-f4e0d400-3aec-11eb-8f09-7be39b85dbac.png)

wow！Thank!!!!!!!1

**Comment by d3v0m4r** [comment]
> This helped to me on linux:
> 
> ```
> sudo apt-get install libc6-dev-i386 lib32z1 openjdk-8-jdk
> ```
> 
> And check this option on Android Studio
> 
> ![image](https://user-images.githubusercontent.com/5152197/101801337-f4e0d400-3aec-11eb-8f09-7be39b85dbac.png)

Thanks, works for me in Ubuntu 20.04 and use open-jdk-11
regards from Bolivia
