### ISSUE TITLE
Flash of red exception on App Bar when returning to home screen in Gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6690]
I've seen this on iOS hardware and simulator. Have not tested on Android.

open gallery, go into Shrine, then tap back.

Notice the flash of red exception where the app bar is. The app bar will replace the red exception quickly.

**Comment by sethladd** [comment]
cc @cbracken saw this, too

**Comment by cbracken** [comment]
Trace I get:
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during _updateSemantics():
'package:flutter/src/rendering/node.dart': Failed assertion: line 131 pos 12: 'child.attached ==
attached' is not true.
When the exception was thrown, this was the stack:
#2      AbstractNode.dropChild (package:flutter/src/rendering/node.dart:131:12)
#3      SemanticsNode.finalizeChildren (package:flutter/src/rendering/semantics.dart:390:13)
#4      _InterestingSemanticsFragment.compile.<compile_sync_body> (package:flutter/src/rendering/object.dart:620:12)
#5      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:66)
#6      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:59)
#7      List.addAll (dart:core-patch/growable_array.dart:206)
#8      SemanticsNode.addChildren (package:flutter/src/rendering/semantics.dart:324:18)
#9      _InterestingSemanticsFragment.compile.<compile_sync_body> (package:flutter/src/rendering/object.dart:613:12)
#10     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:66)
#11     Iterable.single (dart:core/iterable.dart:503)
#12     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2126:82)
#13     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1030:16)
#14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:221:19)
#15     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:314:23)
#16     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:162:5)
#17     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:648:15)
#18     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:583:9)
#19     _beginFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:83)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired:
  RenderSemanticsAnnotations
This RenderObject had the following creator information:
  Semantics ← Focus-[GlobalKey 180744683] ← AbsorbPointer ← Listener ←
  Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState(343388630)] ← Title ← LocaleQuery ←
  MediaQuery ← DefaultTextStyle ← CustomPaint ← ⋯
This RenderObject had the following descendants (showing up to depth 5):
  _RenderTheatre
    RenderStack
      RenderIgnorePointer
        RenderSemanticsAnnotations
          RenderSemanticsGestureHandler
      RenderSemanticsAnnotations
        RenderOffstage
          RenderIgnorePointer
      RenderIgnorePointer
        RenderSemanticsAnnotations
          RenderSemanticsGestureHandler
      RenderSemanticsAnnotations
        RenderOffstage
          RenderIgnorePointer
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Scaffold.of() called with a context that does not contain a Scaffold.
Another exception was thrown: 'package:flutter/src/rendering/node.dart': Failed assertion: line 131 pos 12: 'child.attached == attached' is not true.
Another exception was thrown: 'package:flutter/src/rendering/semantics.dart': Failed assertion: line 341 pos 16: 'seenChildren.add(child)' is not true.
```

**Comment by jason-simmons** [comment]
Work in progress: https://github.com/flutter/flutter/pull/6639

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/pull/6639

**Comment by jason-simmons** [comment]
This is different from the issue seen in #6639

This exception happens while updating the semantics tree, and it can be reproduced if you enable accessibility on an Android device

**Comment by sethladd** [comment]
Oddly, this also happens in "release" mode. @eseidelGoogle was wondering if release-mode should ever display a red error?  (cc @Hixie)

**Comment by sethladd** [comment]
I think @jason-simmons might have fixed this?
