### ISSUE TITLE
Flutter Driver instance doesn't stop after tests are completed

### ISSUE THREAD

**Issue by benja8151** [flutter/flutter#66917]
I'm having an issue when running integration tests with Flutter Driver. If there's an error while testing, the application instance correctly exits with exit code 255, however, if all tests pass, it doesn't stop on it's own.

For example here are last lines of the console output:
<details>
<summary>when tests fail</summary>

```
...
intentional timeout error
...

00:32 +1 -1: Login/Logout (tearDownAll)

Tearing down...

00:32 +1 -1: Login/Logout Login/logout with Email Address [E]

  DriverError: Failed to fulfill SetFrameSync due to remote error
  Original error: Bad state: The client is closed.
  Original stack trace:
  #0      Client._send (package:json_rpc_2/src/client.dart:139:19)
  #1      Client.sendRequest (package:json_rpc_2/src/client.dart:107:5)
  #2      Peer.sendRequest (package:json_rpc_2/src/peer.dart:99:15)
  #3      Scope.sendRequestRaw (package:vm_service_client/src/scope.dart:64:23)
  #4      VMIsolateRef.invokeExtension (package:vm_service_client/src/isolate.dart:361:19)
  #5      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:325:63)
  #6      VMServiceFlutterDriver.runUnsynchronized (package:flutter_driver/src/driver/vmservice_driver.dart:522:13)
  <asynchronous suspension>
  #7      main.<anonymous closure>.<anonymous closure> (file:///home/bsmrdelj/Dokumenti/AMZS/Flutter/amzs_mobility/test_driver/app_test.dart:61:20)
  <asynchronous suspension>
  #8      main.<anonymous closure>.<anonymous closure> (file:///home/bsmrdelj/Dokumenti/AMZS/Flutter/amzs_mobility/test_driver/app_test.dart)
  #9      Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:19)
  <asynchronous suspension>
  #10     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
  #11     _rootRun (dart:async/zone.dart:1190:13)
  #12     _CustomZone.run (dart:async/zone.dart:1093:19)
  #13     _runZoned (dart:async/zone.dart:1630:10)
  #14     runZoned (dart:async/zone.dart:1550:10)
  #15     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
  #16     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:235:15)
  #17     _rootRun (dart:async/zone.dart:1190:13)
  #18     _CustomZone.run (dart:async/zone.dart:1093:19)
  #19     _runZoned (dart:async/zone.dart:1630:10)
  #20     runZoned (dart:async/zone.dart:1550:10)
  #21     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:232:5)
  #22     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:388:17)
  <asynchronous suspension>
  #23     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
  #24     _rootRun (dart:async/zone.dart:1190:13)
  #25     _CustomZone.run (dart:async/zone.dart:1093:19)
  #26     _runZoned (dart:async/zone.dart:1630:10)
  #27     runZoned (dart:async/zone.dart:1550:10)
  #28     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:374:9)
  #29     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:420:15)
  #30     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:373:7)
  #31     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:102:24)
  #32     _rootRun (dart:async/zone.dart:1190:13)
  #33     _CustomZone.run (dart:async/zone.dart:1093:19)
  #34     _runZoned (dart:async/zone.dart:1630:10)
  #35     runZoned (dart:async/zone.dart:1550:10)
  #36     Chain.capture (package:stack_trace/src/chain.dart:100:12)
  #37     Invoker._onRun (package:test_api/src/backend/invoker.dart:372:11)
  #38     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:152:11)
  #39     new Future.microtask.<anonymous closure> (dart:async/future.dart:201:37)
  #40     _rootRun (dart:async/zone.dart:1182:47)
  #41     _CustomZone.run (dart:async/zone.dart:1093:19)
  #42     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
  #44     _rootRun (dart:async/zone.dart:1190:13)
  #45     _CustomZone.run (dart:async/zone.dart:1093:19)
  #46     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #47     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
  #48     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #49     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #50     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #51     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
  #52     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
  #53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

  package:flutter_driver/src/driver/vmservice_driver.dart 336:7  VMServiceFlutterDriver.sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 232:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 388:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 374:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 420:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 373:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 100:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 372:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 152:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage

00:32 +1 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
Stopping application instance.
Driver tests failed: 255
```
</details>

<details>
<summary>when tests pass (notice the lack of "Stopping application instance." message)</summary>

```
$ flutter drive --target=test_driver/app.dart
Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Installing build/app/outputs/flutter-apk/app.apk...                 2,3s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        14,4s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 2,2s
I/flutter ( 9761): Observatory listening on http://127.0.0.1:39699/sJGrGdPaQvI=/
00:00 +0: Login/Logout check flutter driver health

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:46733/sJGrGdPaQvI=/
VMServiceFlutterDriver: Isolate found with number: 1020355068050007
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
HealthStatus.ok

00:05 +1: Login/Logout Login/logout with Email Address

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:46733/sJGrGdPaQvI=/
VMServiceFlutterDriver: Isolate found with number: 1020355068050007
VMServiceFlutterDriver: Isolate is not paused. Assuming application is ready.
VMServiceFlutterDriver: Connected to Flutter application.
00:17 +2: Login/Logout (tearDownAll)

Tearing down...

00:17 +2: All tests passed!
```
</details>

**Why this is an issue**

I'm trying to setup CI/CD for my app using Fastlane and Gitlab, following [this tutorial](https://medium.com/appditto/automate-your-flutter-workflow-using-gitlab-ci-cd-and-fastlane-5872e758165a). The problem is that if application instance is never stopped, my test stage and further ones (build and deploy) are never completed. As I am a beginner when it comes to CI/CD and if this issue can't be fixed, is there an alternate/better way to automate integration testing? I apologize if I've formulated this issue too much as a question rather than a report.

**Additional info**
<details>
<summary>app_test.dart (not full)</summary>

```
void main(){
  group('Login/Logout', (){
    FlutterDriver driver;
    final emailLoginTextField = find.byValueKey(Keys.emailLoginTextField);
    final passwordLoginTextField = find.byValueKey(Keys.passwordLoginTextField);
    final loginModeEmail = find.byValueKey(Keys.loginModeEmail);
    final loginButton = find.byValueKey(Keys.loginButton);
    final profileSettingsButton = find.byValueKey(Keys.profileSettingsButton);
    final logoutButton = find.byValueKey(Keys.logoutButton);

    setUp(() async {
      driver = await FlutterDriver.connect();
    });

    tearDownAll(() async {
      print("Tearing down...");
      await driver?.close();
    }); 

    test('check flutter driver health', () async {
      Health health = await driver.checkHealth();
      print(health.status);
    });

    test("Login/logout with Email Address", () async {
      await driver.waitFor(loginModeEmail);
      await driver.tap(emailLoginTextField);
      await driver.enterText(test.email@test.com');
      await driver.tap(passwordLoginTextField);
      await driver.enterText('123456789');
      await delay(1000);
      await driver.tap(loginButton);
      
      // Runninng Unsynchronized because of animation loops, same issue even without this portion
      await driver.runUnsynchronized(() async {
        await driver.waitFor(profileSettingsButton);  
        await driver.tap(profileSettingsButton);
        await driver.waitFor(logoutButton);
        await driver.tap(logoutButton);
      });
    });
  })
}
```
</details>

<details>
<summary>flutter doctor output</summary>

```
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale sl_SI.UTF-8)
    • Flutter version 1.20.2 at /home/bsmrdelj/Dokumenti/AMZS/Flutter/flutter
    • Framework revision bbfbf1770c (7 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/bsmrdelj/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /home/bsmrdelj/Prejemi/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/bsmrdelj/Prejemi/android-studio
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android
      10 (API 29) (emulator)

• No issues found!
```
</details>

**Comment by darshankawar** [comment]
@benja8151 
Can you also provide `app.dart` where you are enabling FlutterDriverExtension ?
Thanks.

**Comment by benja8151** [comment]
@darshankawar 
`app.dart` is standard: 
```
import 'package:flutter_driver/driver_extension.dart';
import 'package:my_app/main_test.dart' as app; 

void main(){
  enableFlutterDriverExtension();
  app.main();
}
```

I've noticed that if I run tests on [cookbook example](https://flutter.dev/docs/cookbook/testing/integration/introduction), this issue is not present. This makes me think it could be the way I'm running my app. For testing purposes I'm using `main_test.dart` file which is a duplicate of `main.dart`. I've tried to remove all of the unnecessary code from it (not  necessary for testing) and really bring it as close to the standard Counter App example as possible, but there's no difference.

<details>
<summary>main_test.dart completely dumbed down</summary>

```
void main() {
  setupServiceLocator();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return I18n(
      initialLocale: Locale('sl'),
      child: MaterialApp(
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate, 
        ],
        supportedLocales: [
          const Locale('en'),
          const Locale('sl')
        ],
        title: 'My App',
        home: SplashScreen(),
        routes: {
          "LoginScreen": (BuildContext context) => LoginScreen(),
          "MainScreen": (BuildContext context) => MainScreen()
        },
      ),
    );
  }
}
```
</details>

**Comment by benja8151** [comment]
After a few more hours of testing I have finally identified the cause - I was simply using `setUp()` instead of `setUpAll()` in my tests. After changing it to 

```
setUpAll(() async {
    driver = await FlutterDriver.connect();
});
```
tests are completed successfully and application instance is closed.

**Comment by knyghtryda** [comment]
I am still seeing this issue for iOS builds.  I am using `setupAll()`.  For android builds the instance is stopping as expected.
