### ISSUE TITLE
Having trouble documenting flutter project.

### ISSUE THREAD

**Issue by Vbbab** [flutter/flutter#66915]
Trying to document a flutter project.

## Steps to Reproduce
1. Navigate into a flutter project
2. Run `dartdoc`

**Expected results:** 
`dartdoc` successfully documents the project
**Actual results:** 
An error dump complaining about invalid arguments.

<details>
  <summary>Logs</summary>

```
dartdoc failed: Invalid argument(s): join(null, "bin", "cache", "dart-sdk"): part 0 was null, but part 1 was not.
#0      _validateArgList (package:path/src/context.dart:1103:5)
#1      Context.join (package:path/src/context.dart:242:5)
#2      join (package:path/path.dart:265:13)
#3      createDartdocOptions.<anonymous closure> (package:dartdoc/src/dartdoc_options.dart:1587:16)
#4      DartdocSyntheticOption._valueAtFromSynthetic (package:dartdoc/src/dartdoc_options.dart:798:44)
#5      DartdocOptionArgSynth.valueAt (package:dartdoc/src/dartdoc_options.dart:756:12)
#6      DartdocOptionContext.sdkDir (package:dartdoc/src/dartdoc_options.dart:1405:44)
#7      PubPackageBuilder.sdk (package:dartdoc/src/model/package_builder.dart:81:60)
#8      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:67:7)
#9      Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:175:41)
#10     Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:216:34)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZonedGuarded (dart:async/zone.dart:1618:12)
#15     Dartdoc.executeGuarded (package:dartdoc/dartdoc.dart:475:5)
#16     main (file:///C:/b/s/w/ir/cache/builder/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:24:11)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

`flutter analyze` results:
```
Analyzing my_test_flutter_app...
No issues found! (ran in 3.7s)
```

`flutter doctor` output (I'm running Android Studio)
```
Downloading android-arm-profile/windows-x64 tools...                1.3s
Downloading android-arm-release/windows-x64 tools...                0.7s
Downloading android-arm64-profile/windows-x64 tools...              1.4s
Downloading android-arm64-release/windows-x64 tools...              0.7s
Downloading android-x64-profile/windows-x64 tools...                0.9s
Downloading android-x64-release/windows-x64 tools...                0.7s
[√] Flutter (Channel beta, 1.20.0-7.3.pre, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.20.0-7.3.pre at C:\Users\kangj\Documents\flutter
    • Framework revision e606910f28 (9 weeks ago), 2020-07-28 16:06:37 -0700
    • Engine revision ac95267aef
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\kangj\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.63

! Doctor found issues in 1 category.
```

</details>

**Comment by Vbbab** [comment]
Actually, figured this out. Turns out, I needed to set `FLUTTER_ROOT` env. variable.
