### ISSUE TITLE
[Flutter for macOS] "FileSystemException: Cannot open file" while trying to access a file

### ISSUE THREAD

**Issue by ganeshrvel** [flutter/flutter#66920]
I am building a Flutter Desktop application which needs to access a file on my Desktop directory. When I try to read or write a file it throws an `FileSystemException` error. 

It works fine when the `com.apple.security.app-sandbox` is set as `false`. 

Is there a way to read or write a file in macOS after enabling `com.apple.security.app-sandbox`?

## Steps to Reproduce
DebugProfile.entitlements:
```xml
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.cs.allow-jit</key>
	<true/>
        <key>com.apple.security.files.user-selected.read-write</key>
        <true/>
</dict>

```

```dart
    final file = File('/Users/username/Desktop/mock.txt');
    file.writeAsStringSync('qwerty', mode: FileMode.append);
```

**Expected results:**
```shell
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot open file, path = '/Users/username/Desktop/mock.txt' (OS Error: Operation not permitted, errno = 1)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
```

**Actual results:**
Read or write file.

**flutter doctor -v**
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.406, on Mac OS X 10.15.6 19G73
    x86_64, locale en-IN)
    • Flutter version 1.22.0-10.0.pre.406 at /Users/username/Library/Application
      Support/fvm/versions/master
    • Framework revision 5872b70b8c (9 hours ago), 2020-09-29 05:47:04 -0400
    • Engine revision 1c462e28a2
    • Dart version 2.11.0 (build 2.11.0-176.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.6 19G73 x86_64

• No issues found!

```

**Comment by stuartmorgan** [comment]
> Is there a way to read or write a file in macOS after enabling `com.apple.security.app-sandbox`?

The Flutter issue tracker is not the right place to ask general questions about macOS sandbox behavior. The fact that you are using Flutter is not related to the issue you are having.

Apple's documentation, and general programming Q&A resources like StackOverflow, would be the place for questions about the details of sandbox restrictions and entitlements.

**Comment by SteveCruise** [comment]
Thank you for your helpful answer! @stuartmorgan
