### ISSUE TITLE
Windows symlink instructions are incorrect for older versions of Windows

### ISSUE THREAD

**Issue by ayalma** [flutter/flutter#66973]
Hi
I'm using flutter dev channel for build app for windows
and i got this error 
```

Launching lib\main.dart on Windows in debug mode...
Exception: Building with plugins requires symlink support. Please enable Developer Mode in your system settings.

FileSystemException: Cannot create link, path = 'D:\Workspace\hello_win\windows\flutter\ephemeral\.plugin_symlinks\url_launcher_windows' (OS Error: A required privilege is not held by the client.
, errno = 1314)

```

I also enabled the developer mode in system setting , but there is no result .
my run command output with -v option

```
flutter run -d windows -v


[ +121 ms] executing: [D:\flutter\flutter-dev/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 83dd176777cd04bd2aaca050f6bb6cb9edbf56a1
[        ] executing: [D:\flutter\flutter-dev/] git tag --points-at HEAD
[  +45 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.23.0-4.0.pre
[   +9 ms] executing: [D:\flutter\flutter-dev/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [D:\flutter\flutter-dev/] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +218 ms] executing: [D:\flutter\flutter-dev/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +44 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] executing: D:\Android\Sdk\Win\platform-tools\adb.exe devices -l
[  +15 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +107 ms] executing: D:\Android\Sdk\Win\platform-tools\adb.exe devices -l
[  +52 ms] Found plugin url_launcher at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.2\
[   +5 ms] Found plugin url_launcher_linux at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+1\
[   +2 ms] Found plugin url_launcher_macos at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+8\
[   +4 ms] Found plugin url_launcher_web at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.4+1\
[   +4 ms] Found plugin url_launcher_windows at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+1\
[ +263 ms] Found plugin url_launcher at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.2\
[   +2 ms] Found plugin url_launcher_linux at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+1\
[   +2 ms] Found plugin url_launcher_macos at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+8\
[   +3 ms] Found plugin url_launcher_web at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.4+1\
[   +2 ms] Found plugin url_launcher_windows at D:\flutter\flutter-dev\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+1\
[  +13 ms] Generating D:\Workspace\hello_win\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +84 ms] Starting incremental build...
[   +2 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +5 ms] Launching lib\main.dart on Windows in debug mode...
[   +6 ms] D:\flutter\flutter-dev\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\flutter\flutter-dev\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot
--sdk-root D:\flutter\flutter-dev\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\MOHAMM~1\AppData\Local\Temp\flutter_tools.3f66b276\flutter_tool.e3f6852f\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +60 ms] <- compile package:hello_win/main.dart
[  +14 ms] List of devices attached
[   +4 ms] List of devices attached
[+7173 ms] Exception: Building with plugins requires symlink support. Please enable Developer Mode in your system settings.
                    
                    FileSystemException: Cannot create link, path = 'D:\Workspace\hello_win\windows\flutter\ephemeral\.plugin_symlinks\url_launcher_windows' (OS Error: A required
privilege is not held
                    by the client.
                    , errno = 1314)
[  +12 ms] "flutter run" took 7,950ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:608:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:985:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +255 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +6 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1


```

And my envirment output is 
```
flutter doctor -v

[√] Flutter (Channel dev, 1.23.0-4.0.pre, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 1.23.0-4.0.pre at D:\flutter\flutter-dev
    • Framework revision 83dd176777 (8 days ago), 2020-09-22 12:04:44 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Android\Sdk\Win
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Android\Sdk\Win\platform-tools
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.17763.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\mohammadi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (3 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.14393]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.121

• No issues found!

```

**Comment by felipecastrosales** [comment]
I assume you tried flutter clean?

**Comment by ayalma** [comment]
Yes I do

**Comment by darshankawar** [comment]
@ayalma 
The exception log says:
`OS Error: A required privilege is not held by the client, errno = 1314)`.
Can you check if you have all the required permissions to run the app ?
Thanks.

**Comment by stuartmorgan** [comment]
The current instructions only apply to [newer versions of Windows](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/) than you are running. I need to conditionalize the instructions in that message.

You'll need to either update Windows, or build using a terminal running in administrator mode.

**Comment by ayalma** [comment]
Yes , I gave full control access to project folder  for `everyone` user and 
and I'm using `win 10 version 1607 (OS build 14393.3144)`

**Comment by ayalma** [comment]
``

> The current instructions only apply to [newer versions of Windows](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/) than you are running. I need to conditionalize the instructions in that message.
> 
> You'll need to either update Windows, or build using a terminal running in administrator mode.

I ran project from admin cmd and  problem is solved,
I'll try to update my win, to check if it work without admin cmd or not
Thank you for your response

**Comment by asbn223** [comment]
To solve this problem, Go to settings then go to Update & Security then go to For developers. After that enable Developer Mode. I hope this will solve your problem.

**Comment by stuartmorgan** [comment]
> To solve this problem, Go to settings then go to Update & Security then go to For developers. After that enable Developer Mode. I hope this will solve your problem.

Please see my comment above.

**Comment by ayalma** [comment]
@stuartmorgan okay thanks

**Comment by ayalma** [comment]
I updated my Win to version 2004(OS Build 19041.508)
But nothing changed

**Comment by malzariey** [comment]
I am using Android Studio, and after running it with administrator right, it worked fluently.

**Comment by rajathpi** [comment]
Run android studio as administrator, it'll work

**Comment by JCKodel** [comment]
Since when run as administrator is a solution???????
