### ISSUE TITLE
I downloaded the flutter zip file did a git pull also and added path to environment variable did a restart still when i try to check the flutter doctor command in cmd getting this issue

### ISSUE THREAD

**Issue by Sabya-07** [flutter/flutter#67042]
```
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable for where.
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for where.".
Unable to generate crash report due to secondary error: Invalid argument(s): Cannot find executable for where.
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:176:7)
#1      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#2      _rootRunBinary (dart:async/zone.dart:1214:47)
#3      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#7      Future._completeError (dart:async/future_impl.dart:537:5)
#8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#9      _doctorText (package:flutter_tools/runner.dart)
#10     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#11     _rootRunBinary (dart:async/zone.dart:1214:47)
#12     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#13     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#14     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#15     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#16     Future._completeError (dart:async/future_impl.dart:537:5)
#17     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by TahaTesser** [comment]
Hi @Sabya-07 
This is more like a setup issue, please see https://github.com/flutter/flutter/issues/62802#issuecomment-668436165
Please make sure you're following https://flutter.dev/docs/get-started/install/windows#update-your-path 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
