### ISSUE TITLE
The Draggable widget throws the exception on Windows and Web

### ISSUE THREAD

**Issue by cjng96** [flutter/flutter#67044]
## Steps to Reproduce
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(brightness: Brightness.light),
      home: Scaffold(
        appBar: AppBar(title: Text('test')),
        body: Center(child: Main()),
      ),
    );
  }
}

class Main extends StatefulWidget {
  @override
  _MainState createState() => _MainState();
}

class _MainState extends State<Main> {
  @override
  void dispose() {
    super.dispose();
  }
  void _handleBtn() {}
  @override
  Widget build(BuildContext context) {
    Widget body = RaisedButton(child: Text('TEST BTN'), onPressed: _handleBtn);
    body = Draggable(
      child: body,
      feedback: Container(width: 20, height: 20, color: Colors.blue),
      childWhenDragging: Container(width: 20, height: 20, color: Colors.yellow),
    );
    return body;
  }
}

```
1. Run `flutter run -d windows`.
2. Begin to drag [TEST BTN].
3. The following error message is repeated.

`Unhandled Exception: 'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 312 pos 12: '!_debugDuringDeviceUpdate': is not true.`

Maybe Draggble is not working on Windows platform.

**Expected results:** 
Draggable works as well as mobule platform. **It's working well on Android**.

**Actual results:** 
The error message repeats.

<details>
  <summary>Logs</summary>

```
[        ] [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracking.dart':
Failed assertion: line 312 pos 12: '!_debugDuringDeviceUpdate': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] #2      BaseMouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracking.dart:312:12)
[        ] #3      BaseMouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracking.dart:419:7)
[        ] #4      BaseMouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracking.dart:301:9)
[        ] #5      BaseMouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracking.dart:418:5)
[        ] #6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:266:22)
[        ] #7      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:305:7)
[        ] #8      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] #9      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] #10     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] #13     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracking.dart':
Failed assertion: line 312 pos 12: '!_debugDuringDeviceUpdate': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] #2      BaseMouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracking.dart:312:12)
[        ] #3      BaseMouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracking.dart:419:7)
[        ] #4      BaseMouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracking.dart:301:9)
[        ] #5      BaseMouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracking.dart:418:5)
[        ] #6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:266:22)
[        ] #7      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:305:7)
[        ] #8      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] #9      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] #10     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] #13     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[+2151 ms] Application finished.
```

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.430, on Microsoft Windows [Version 10.0.19041.508], locale ko-KR)
    • Flutter version 1.22.0-10.0.pre.430 at C:\flutter
    • Framework revision 94e836711e (20 hours ago), 2020-09-30 07:29:25 -0700
    • Engine revision a6a6fd163b
    • Dart version 2.11.0 (build 2.11.0-177.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\android-sdk
    • Java binary at: C:\Program Files (x86)\java\jdk8u202-b08\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30503.244
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\cjng96\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] VS Code, 32-bit edition
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 85.0.564.51

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(brightness: Brightness.light),
      home: Scaffold(
        appBar: AppBar(title: Text('test')),
        body: Center(child: Main()),
      ),
    );
  }
}

class Main extends StatefulWidget {
  @override
  _MainState createState() => _MainState();
}

class _MainState extends State<Main> {
  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    Widget body = RaisedButton(child: Text('TEST BTN'), onPressed: () {});
    body = Draggable(
      child: body,
      feedback: Container(width: 20, height: 20, color: Colors.blue),
      childWhenDragging: Container(width: 20, height: 20, color: Colors.yellow),
    );
    return body;
  }
}

```

</details> 

<details> 
<summary>logs</summary> 

```bash
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracking.dart': Failed assertion: line 312 pos 12: '!_debugDuringDeviceUpdate': is not true.
#0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:46:39))
#1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5))
#2      BaseMouseTracker._deviceUpdatePhase 
package:flutter/…/rendering/mouse_tracking.dart:312
#3      BaseMouseTracker.updateWithEvent.<anonymous closure> 
package:flutter/…/rendering/mouse_tracking.dart:419
#4      BaseMouseTracker._monitorMouseConnection 
package:flutter/…/rendering/mouse_tracking.dart:301
#5      BaseMouseTracker.updateWithEvent 
package:flutter/…/rendering/mouse_tracking.dart:418
#6      RendererBinding.dispatchEvent 

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.451, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.451 at C:\Code\flutter_master
    • Framework revision 79400b2462 (2 hours ago), 2020-10-01 09:06:46 -0400
    • Engine revision 612acf349e
    • Dart version 2.11.0 (build 2.11.0-180.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version
      10.0.19041.508]
    • Web Server (web)                      • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

**Comment by gspencergoog** [comment]
Has this been testing on another platform? This might just be a general framework bug.

**Comment by gspencergoog** [comment]
Looks like it also might fail on other platforms (at least web). Removing a:desktop.

**Comment by cjng96** [comment]
As you said, this issue is being reproduced on the Web and the Windows. there is no problem with Android.

**Comment by philip-brink** [comment]
I'm facing the same issue only on web when a widget with an onTap method is a child of a draggable.

I added my bug report info to what seems to be a duplicate issue #66887.

**Comment by xu-baolin** [comment]
I have posted a PR to fix this.

**Comment by eerbee** [comment]
i  got same issue on windows platform

**Comment by piecubed** [comment]
I had this issue as well on windows, with no draggable widget.

**Comment by felixchoi** [comment]
My original issue is solved with the master channel including the xu-baolin's patch.
@piecubed if your problem is reproduced on the master channel. it's better to create the new issue with how to reproduce the problem.

**Comment by cjng96** [comment]
My original issue is solved with the master channel including the xu-baolin's patch.
@piecubed if your problem is reproduced on the master channel. it's better to create the new issue with how to reproduce the problem.

**Comment by kokocooler2020** [comment]
> Looks like it also might fail on other platforms (at least web). Removing a:desktop.

I encountered the same problem, and I don't know how to reproduce this exception. It may happen when the mouse pointer moves from another window to the app window, but I am not sure.
I used go-flutter to compile an app to run in macOS (MacOS Catalina 10.15.7)
The same exceptions are thrown from time to time.

**Comment by xu-baolin** [comment]
> > Looks like it also might fail on other platforms (at least web). Removing a:desktop.
> 
> I encountered the same problem, and I don't know how to reproduce this exception. It may happen when the mouse pointer moves from another window to the app window, but I am not sure.
> I used go-flutter to compile an app to run in macOS (MacOS Catalina 10.15.7)
> The same exceptions are thrown from time to time.

Please update the latest code on the master channel, if your problem is reproduced on the master channel. it's better to create a new issue with how to reproduce the problem.
