### ISSUE TITLE
Can not run a web project

### ISSUE THREAD

**Issue by quetool** [flutter/flutter#67050]
I get this error in a flutter web project recently created

```
ERROR - 2020-10-01 11:01:56.591197
GET /dwds/src/injected/client.js
Error thrown by handler.
FileSystemException: Cannot open file, path = '/Users/alfredo.rinaudo/Development/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/dwds-6.0.0/lib/src/injected/client.js' (OS Error: No such file or directory, errno = 2)
dart:isolate  _RawReceivePortImpl._handleMessage
```

This is my `flutter doctor -v`
```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0-12.1.pre at /Users/alfredo.rinaudo/Development/sdk/flutter
    • Framework revision 8b3760638a (2 weeks ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/alfredo.rinaudo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • iPhone Alfredo (mobile) • 00008020-001A03CE1161002E            • ios            • iOS 14.0
    • iPhone 11 (mobile)      • 04D14EF7-B024-4FEF-9A07-F5ABFAE7E3E0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)        • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
```

Also, I cannot accept android licenses with `flutter doctor --android-licenses` because it get me this error
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

**Comment by quetool** [comment]
Sorry, I think first part is answered here https://github.com/flutter/flutter/issues/66415

**Comment by TahaTesser** [comment]
Hi @quetool 
For license issue, make sure you've added SDK location in your SDK manager and make sure these are installed 
<img width="505" alt="Screenshot 2020-10-01 at 8 39 40 PM" src="https://user-images.githubusercontent.com/48603081/94827871-8c0f1880-0426-11eb-84c4-881c216cecc7.png">

https://stackoverflow.com/a/61993804
Duplicate of https://github.com/flutter/flutter/issues/66907
