### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\user\Documents\prog\eğitim\dart\test1\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by efeArdaYildirim** [flutter/flutter#67093]
## Command
```
flutter create test1
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot copy file to 'C:\Users\user\Documents\prog\eğitim\dart\test1\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', OS Error: Access is denied.
, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:267:18)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      Template.render (package:flutter_tools/src/template.dart:190:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:799:21)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
```
```
[✓] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.19041.508], locale tr-TR)
    • Flutter version 1.22.0 at C:\Users\user\Documents\androidSDKs\flutter
    • Framework revision d408d302e2 (2 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jonahwilliams** [comment]
We need to add this one to our exception list.

**Comment by DarioJr13** [comment]
I get this and not why. emulating in visual studio code is a big roll I installed Genymotion with virtual box with a genexus 5 from google and when I put Flutter doctor the emulator did not recognize me.
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to
'C:\Users\USUARIO\Desktop\POO\Flutter\Prueba_Emulator\example\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path =
'C:\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png'(OS Error: Acceso denegado.
, errno = 5)".
A crash report has been written to C:\Users\USUARIO\Desktop\POO\Flutter\Prueba_Emulator\flutter_01.log.

**Comment by jonahwilliams** [comment]
You're getting this because you installed to `C:/` instead of somewhere like `Documents`

**Comment by jonahwilliams** [comment]
To be clear: this is not a tool bug, besides the fact that we crashed without showing an error message.

**Comment by efeArdaYildirim** [comment]
not works. still same  error.
```Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to
'C:\Users\user\Documents\test1\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path =
'C:\src\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS
Error: Access is denied.
, errno = 5)".
A crash report has been written to C:\Users\user\Documents\flutter_01.log.```

**Comment by efeArdaYildirim** [comment]
I write 
`flutter create --platforms web test` 
it's make pug download. after run this command `flutter create --platforms web,android test`  and it's works.
now this command working `flutter create test1`.
maybe pug download be was incorrect.

my install commands as windows 10
```
cd \src
git clone https://github.com/flutter/flutter.git -b stable
// I added fluter to  path 
flutter doctor
//• No issues found!
```
