### ISSUE TITLE
video_player plugin: VideoPlayerController.asset() fails to load videos in Android

### ISSUE THREAD

**Issue by Zfinix** [flutter/flutter#67118]
## Steps to Reproduce
Video player fails to load video from assets in Android after updating my flutter to `Flutter (Channel dev, 1.23.0-4.0.pre, on Mac OS X 10.15.4 19E287 `.

Sequence of events:
 - Add the latest version to `pubspec.yaml` -> `video_player: 0.11.0`

Video player from assets code:

```dart
class TutorialUI extends StatefulWidget {
  @override
  _TutorialUIState createState() => _TutorialUIState();
}

class _TutorialUIState extends State<TutorialUI> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    try {
      _controller =
                    VideoPlayerController.asset('assets/video/mana_tutorial.mp4')
            ..initialize().then((_) {
              // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
              setState(() {
                _controller.play();
              });
            });
    } catch (e) {
      print(e.toString());
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Center(
            child: _controller.value.initialized
                ? GestureDetector(
                    onTap: () {
                      _controller.value.isPlaying
                          ? _controller.pause()
                          : _controller.play();
                    },
                    child: AspectRatio(
                      aspectRatio: _controller.value.aspectRatio,
                      child: VideoPlayer(_controller),
                    ),
                  )
                : LoadingWidget(),
          ),
          Positioned(
            right: 5,
            top: 20,
            child: Material(
              color: Colors.transparent,
              child: IconButton(
                icon: Icon(Icons.close, color: white),
                onPressed: () {
                  Navigator.pop(context);
                },
              ),
            ),
          )
        ],
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```

## Logs

Error: 
```
E/flutter (30264): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled
Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111
pos 15: 'code != null': is not true.
[        ] E/flutter (30264): #0      _AssertionError._doThrowNew
(dart:core-patch/errors_patch.dart:46:39)
[        ] E/flutter (30264): #1      _AssertionError._throwNew
(dart:core-patch/errors_patch.dart:36:5)
[        ] E/flutter (30264): #2      new PlatformException
(package:flutter/src/services/message_codec.dart:111:15)
[   +5 ms] E/flutter (30264): #3      VideoPlayerApi.create
(package:video_player_platform_interface/messages.dart:205:13)
[        ] E/flutter (30264): <asynchronous suspension>
[        ] E/flutter (30264): #4      MethodChannelVideoPlayer.create
(package:video_player_platform_interface/method_channel_video_player.dart:46:42)
[        ] E/flutter (30264): #5      VideoPlayerController.initialize
(package:video_player/video_player.dart:282:45)
[        ] E/flutter (30264): #6      _TutorialUIState.initState
(package:mana_app/layers/presentation/pages/tutorial/tutorial_ui.dart:20:15)
[        ] E/flutter (30264): #7      StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:4778:57)
[        ] E/flutter (30264): #8      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:4615:5)
[        ] E/flutter (30264): #9      Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3581:14)
[        ] E/flutter (30264): #10     Element.updateChild
(package:flutter/src/widgets/framework.dart:3343:20)
[        ] E/flutter (30264): #11     SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6137:14)
[        ] E/flutter (30264): #12     Element.updateChild
(package:flutter/src/widgets/framework.dart:3333:15)
[        ] E/flutter (30264): #13     SingleChildRenderObjectElement.update
(package:flutter/src/widgets/framework.dart:6137:14)
[        ] E/flutter (30264): #14     Element.updateChild
(package:flutter/src/widgets/framework.dart:3333:15)
[        ] E/flutter (30264): #15     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4666:16)
[        ] E/flutter (30264): #16     Element.rebuild
(package:flutter/src/widgets/framework.dart:4335:5)
[        ] E/flutter (30264): #17     StatelessElement.update
(package:flutter/src/widgets/framework.dart:4722:5)
[        ] E/flutter (30264): #18     Element.updateChild
(package:flutter/src/widgets/framework.dart:3333:15)
[        ] E/flutter (30264): #19     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4666:16)
[        ] E/flutter (30264): #20     StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4813:11)
[        ] E/flutter (30264): #21     Element.rebuild
(package:flutter/src/widgets/framework.dart:4335:5)
[        ] E/flutter (30264): #22     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2743:33)
[        ] E/flutter (30264): #23     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:911:21)
[        ] E/flutter (30264): #24     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:301:5)
[        ] E/flutter (30264): #25     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1117:15)
[        ] E/flutter (30264): #26     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1055:9)
[        ] E/flutter (30264): #27     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:971:5)
[        ] E/flutter (30264): #28     _rootRun (dart:async/zone.dart:1190:13)
[        ] E/flutter (30264): #29     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] E/flutter (30264): #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] E/flutter (30264): #31     _invoke (dart:ui/hooks.dart:251:10)
[        ] E/flutter (30264): #32     _drawFrame (dart:ui/hooks.dart:209:3)
[        ] E/flutter (30264): 

```

flutter doctor -v

```
[✓] Flutter (Channel dev, 1.23.0-4.0.pre, on Mac OS X 10.15.4 19E287 x86_64, locale en-NG)
    • Flutter version 1.23.0-4.0.pre at /Users/chiziaruhoma/flutter
    • Framework revision 83dd176777 (10 days ago), 2020-09-22 12:04:44 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/chiziaruhoma/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 4.2
      Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.10.0.beta.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Brave
    Browser.app)
    ! /Applications/Brave Browser.app is not executable.

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (3 available)            
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30)
      (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.4
      19E287 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    ! Error: Chizi’s iPhone is not connected. Xcode will continue when Chizi’s iPhone is
      connected. (code -13)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code
      -13)

! Doctor found issues in 3 categories.
```

**Comment by darshankawar** [comment]
@Zfinix 
There's similar open issue describing your case, [66627](https://github.com/flutter/flutter/issues/66627).
Please follow-up there for updates and any questions.
Closing this as duplicate.
Thanks.
