### ISSUE TITLE
Exception thrown on macOS when switching to tab with insertion point in text field

### ISSUE THREAD

**Issue by ryanknauer** [flutter/flutter#67142]
## Steps to Reproduce
Note: App is internal so reach out if demo app is needed. 

1. Launch Flutter App on macOS with a TextField inside of a TabView
3. Click in the textfield where you type search terms
4. Click to new tab

**Expected results:** No exception/crash

**Actual results:** 
In release mode: Crash
In debug mode: The below exception

<details>
  <summary>Logs</summary>

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during paint():
flutter: Rect argument contained a NaN value.
flutter: 'dart:ui/painting.dart':
flutter: Failed assertion: line 31: '<optimized out>'
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: The relevant error-causing widget was:
flutter:   _Editable-[GlobalKey#59c1a]
flutter:   google3:///third_party/dart/flutter/lib/src/widgets/editable_text.dart:2319:22
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      _rectIsValid (dart:ui/painting.dart:31:10)
flutter: #3      Canvas.drawRect (dart:ui/painting.dart:3727:12)
flutter: #4      RenderEditable._paintCaret (package:flutter/src/rendering/editable.dart:1996:14)
flutter: #5      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:2179:7)
flutter: #6      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2221:7)
flutter: #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2307:7)
flutter: #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:191:13)
flutter: #9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
flutter: #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2307:7)
flutter: #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:191:13)
flutter: #12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
flutter: #13     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:398:12)
flutter: #14     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4901:13)
flutter: #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2307:7)
flutter: #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:191:13)
flutter: #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
flutter: #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2307:7)
flutter: #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:191:13)
flutter: #20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
flutter: #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2307:7)
flutter: #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:191:13)
flutter: #23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
flutter: #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2307:7)
flutter: #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:191:13)
flutter: #26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
flutter: #27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2307:7)
flutter: #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:191:13)
flutter: #29     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:133:15)
flutter: #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2307:7)
flutter: #31     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:142:11)
flutter: #32     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:102:5)
flutter: #33     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:989:29)
flutter: #34     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:405:19)
flutter: #35     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
flutter: #36     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #37     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1116:15)
flutter: #38     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
flutter: #39     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
flutter: #43     _invoke (dart:ui/hooks.dart:253:10)
flutter: #44     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: 
flutter: The following RenderObject was being processed when the exception was fired: RenderEditable#cbd9b relayoutBoundary=up21:
flutter:   creator: _Editable-[GlobalKey#59c1a] ← Semantics ← CompositedTransformTarget ←
flutter:     IgnorePointer-[GlobalKey#61af2] ← Semantics ← _PointerListener ← Listener ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#9d648] ← _PointerListener ← Listener
flutter:     ← _ScrollableScope ← RepaintBoundary ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=455.3, 0.0<=h<=12.0)
flutter:   size: Size(455.3, 12.0)
flutter:   cursorColor: Color(0xff4285f4)
flutter:   showCursor: ValueNotifier<bool>#2a08a(true)
flutter:   maxLines: 1
flutter:   minLines: null
flutter:   selectionColor: Color(0xff6cb9e4)
flutter:   textScaleFactor: 1.0
flutter:   locale: en_US
flutter:   selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream,
flutter:     isDirectional: false)
flutter:   offset: ScrollPositionWithSingleContext#e5f18(offset: 0.0, range: 0.0..0.0, viewport: 455.3,
flutter:     ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#4f734,
flutter:     ScrollDirection.idle)
flutter: This RenderObject had the following child:
flutter:     text: TextSpan
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```
```

Running from binary

```
```

Running from binary. Flutter doctor from build location:

[✓] Flutter (Channel google3, on Linux, locale en_US.UTF-8)
    • Framework revision 473358d93d (1 days ago), 2020-10-01T00:00:00.000
    • Engine revision 0522ff22cc
    • Dart version ddbeaabe8b

[✓] Android toolchain - develop for Android devices (Android SDK version Stable)
    • Android SDK at google3
    • Platform Stable, build-tools Stable
    • Java binary at: /usr/local/buildtools/java/jdk/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-google-release-330023116)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

[✓] Google3 (on linux)
    • KVM enabled

! Doctor found issues in 1 category.



```
```

</details>

**Comment by TahaTesser** [comment]
Hi @ryanknauer 
Your title seems to indicate an issue with MacOS app but logs say Linux `[✓] Flutter (Channel google3, on Linux, locale en_US.UTF-8)` and not sure which channel/flutter version you're experiencing this issue 


The issue isn't reproducible on the latest `master` channel using the code sample below 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
                Tab(icon: Icon(Icons.directions_bike)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              Container(child: Center(child: TextField())),
              Icon(Icons.directions_transit),
              Icon(Icons.directions_bike),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.132, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.132 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 5e97eed895 (71 minutes ago), 2020-10-05 00:42:50 -0700
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2
      x86_64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!
```

</details> 

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by ryanknauer** [comment]
It looks like this has been resolved in a recent Flutter roll actually. Thanks!

**Comment by drriguz** [comment]
Hi @ryanknauer

I got the same issue and I reproduced using the code above, pls take a look, and I created a new issue (https://github.com/flutter/flutter/issues/70096) since this one is already closed.
