### ISSUE TITLE
[in_app_purchase] queryProductDetails crash

### ISSUE THREAD

**Issue by stefanoromanello** [flutter/flutter#67216]
Hi, when I try to run the following command:
```
const Set<String> _kIds = {'premium_features_developer', 'premium_features'};
final ProductDetailsResponse response = await InAppPurchaseConnection.instance.queryProductDetails(_kIds);
```
I get the following error:

```
E/AndroidRuntime(22787): java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in /data/app/~~eZHtGHA0VPbvIenjsiKmUA==/xyz.romanello.SpotifyTools-zi7YUz_E-P7hzyFM9Cq2wA==/base.apk)
E/AndroidRuntime(22787): 	at io.flutter.plugins.inapppurchase.Translator.fromSkuDetail(Translator.java:27)
E/AndroidRuntime(22787): 	at io.flutter.plugins.inapppurchase.Translator.fromSkuDetailsList(Translator.java:49)
E/AndroidRuntime(22787): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl$1.onSkuDetailsResponse(MethodCallHandlerImpl.java:185)
E/AndroidRuntime(22787): 	at com.android.billingclient.api.zzj.run(com.android.billingclient:billing@@3.0.0:8)
E/AndroidRuntime(22787): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(22787): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22787): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(22787): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(22787): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22787): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(22787): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (22787): Sending signal. PID: 22787 SIG: 9
Lost connection to device.
Exited (sigterm)
```

Does anyone know how to solve?

**Comment by stefanoromanello** [comment]
Had to remove the RevenueCat package from pubspec.yaml
