### ISSUE TITLE
Text selection index was clamped (-1->0) to remain in bounds. editable.dart': Failed assertion: line 561 pos 12: 'index >= 0 && index <= string.length': is not true.

### ISSUE THREAD

**Issue by talhakhan1297** [flutter/flutter#67257]
`
D/flutter (29113): Text selection index was clamped (-1->0) to remain in bounds. This may not be your fault, as some keyboards may select outside of bounds.
D/flutter (29113): Text selection index was clamped (-1->0) to remain in bounds. This may not be your fault, as some keyboards may select outside of bounds.
D/flutter (29113): Text selection index was clamped (-1->0) to remain in bounds. This may not be your fault, as some keyboards may select outside of bounds.
D/flutter (29113): Text selection index was clamped (-1->0) to remain in bounds. This may not be your fault, as some keyboards may select outside of bounds.
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
'package:flutter/src/rendering/editable.dart': Failed assertion: line 561 pos 12: 'index >= 0 &&
index <= string.length': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
#2      RenderEditable.nextCharacter 
package:flutter/…/rendering/editable.dart:561
#3      RenderEditable._handleMovement 
package:flutter/…/rendering/editable.dart:675
#4      RenderEditable._handleKeyEvent 
package:flutter/…/rendering/editable.dart:538
#5      RawKeyboard._handleKeyEvent 
package:flutter/…/services/raw_keyboard.dart:591
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> 
package:flutter/…/services/platform_channel.dart:76
#7      _DefaultBinaryMessenger.handlePlatformMessage 
package:flutter/…/services/binding.dart:267
#8      _invoke3.<anonymous closure>  (dart:ui/hooks.dart:282:15))
#12     _invoke3  (dart:ui/hooks.dart:281:10))
#13     _dispatchPlatformMessage  (dart:ui/hooks.dart:156:5))
(elided 5 frames from class _AssertionError and dart:async)
`

**Comment by talhakhan1297** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/50271102/95012662-e2ad6a00-0653-11eb-8c8e-1964fd1adc84.gif)

**Comment by talhakhan1297** [comment]
Was solved by calling `notesController = TextEditingController(text: widget.kClass.courseDescription);` in initial state
