### ISSUE TITLE
Issues on Android with google_sign_in

### ISSUE THREAD

**Issue by jeremyw24** [flutter/flutter#67308]
I have an app using the google_sign_in package with Firebase.

I have absolutely no issues with iOS Devices in simulation or test flight, they work as expected and sign the user in.

I am having very inconsistent experiences with android devices though.

Debugging the app either in the android simulator OR using a connected device works as expected. User is presented with a list of Google accounts, selects and is signed in.

However, on real devices when deployed via PlayStore Internal Testing some users are able to login while majority are not. I have downloaded the app via PlayStore to the same device I was using for testing and it does not work.

Where login fails, the screen flashes then just reloads the app login screen.

I have noticed it seems to be pretty widespread but Google Pixel devices seem to work fine.

Given it works on simulators, debugging and iOS devices I am not really sure where to look anymore. I have Sentry running on the release candidate but am not getting any errors come back so its not error-ring out.

## Steps to Reproduce

1. Run app on Android device from PlayStore.
2. Tap sign in with Google
3. App returns to login screen after brief flash.

**Expected results:** 
User should be logged in or asked to select Google account.

**Actual results:** 
App returns to login screen.

<details>
  <summary>Logs</summary>

No errors are produced during build and run, have included the log output below from Android simulator device successfully logging into the app. 

```
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:56748/o_i4Ao9nB8U=/
[ +301 ms] I/Choreographer(24790): Skipped 353 frames!  The application may be doing too much work on its main thread.
[+1847 ms] I/flutter (24790): [2020-10-06 00:13:28.064415 | Catcher | FINE] Using debug config
[  +69 ms] I/flutter (24790): [2020-10-06 00:13:28.160129 | Catcher | FINE] Catcher configured successfully.
[+16929 ms] I/BiChannelGoogleApi(24790): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms:
com.google.firebase.auth.api.internal.zzaq@749d90
[+1910 ms] D/FirebaseAuth(24790): Notifying id token listeners about user ( Vl867wYCQ9fF194M7eDCqNjwpXK2 ).
[  +54 ms] I/flutter (24790): signInWithGoogle succeeded: User(displayName: User Name, email: ***********@*********.com.au,
emailVerified: true, isAnonymous: false, metadata: UserMetadata(creationTime: 2020-09-21 23:15:40.558, lastSignInTime: 2020-10-06
00:13:46.660), phoneNumber: null, photoURL: https://lh3.googleusercontent.com/a-/AOh14GhuawMIsSccmMHlspKKFs4bah8xUHcl8hu6aeMY=s96-c,
providerData, [UserInfo(displayName: User Name, email: **********@*******.com.au, phoneNumber: null, photoURL:
https://lh3.googleusercontent.com/a-/AOh14GhuawMIsSccmMHlspKKFs4bah8xUHcl8hu6aeMY=s96-c, providerId: google.com, uid:
113989377345629527269)], refreshToken: , tenantId: null, uid: Vl867wYCQ9fF194M7eDCqNjwpXK2)
[ +310 ms] W/DynamiteModule(24790): Local module descriptor class for providerinstaller not found.
[  +12 ms] I/TetheringManager(24790): registerTetheringEventCallback:com.avcga.avcgacontentapp
[  +63 ms] I/DynamiteModule(24790): Considering local module providerinstaller:0 and remote module providerinstaller:0
[   +8 ms] W/ProviderInstaller(24790): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and
remote version is 0.
[ +315 ms] I/avcgacontentap(24790): The ClassLoaderContext is a special shared library.
[ +136 ms] I/avcgacontentap(24790): The ClassLoaderContext is a special shared library.
[ +228 ms] V/NativeCrypto(24790): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
[  +53 ms] W/avcgacontentap(24790): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String;
(greylist, reflection, allowed)
[  +49 ms] I/ProviderInstaller(24790): Installed default security provider GmsCore_OpenSSL
[ +897 ms] W/avcgacontentap(24790): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection,
allowed)
[  +19 ms] W/avcgacontentap(24790): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard;
(greylist,core-platform-api, linking, allowed)
[  +17 ms] W/avcgacontentap(24790): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V
(greylist,core-platform-api, linking, allowed)
[   +7 ms] W/avcgacontentap(24790): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
[ +223 ms] W/avcgacontentap(24790): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V
(greylist, reflection, allowed)
[ +104 ms] W/avcgacontentap(24790): Accessing hidden method
Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
[        ] W/avcgacontentap(24790): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking,
allowed)
[  +15 ms] I/avcgacontentap(24790): Background concurrent copying GC freed 75668(4190KB) AllocSpace objects, 54(2356KB) LOS objects,
49% free, 4162KB/8324KB, paused 2.176ms total 202.189ms
[+133824 ms] D/CompatibilityChangeReporter(24790): Compat change id reported: 150939131; UID 10152; state: ENABLED

```

```
No issues found! (ran in 5.5s)
```

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.7 19H2, locale en-AU)
    • Flutter version 1.20.2 at /Users/jeremywest/Documents/Code/sdk/flutter
    • Framework revision bbfbf1770c (8 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jeremywest/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.10.0.beta.2

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Hi @jeremyw24 
Can you provide a complete minimal reproducible code sample using `google_sign_in` and `firebase_auth` packages that could possibly help to replicate the issue ?
Thanks.

**Comment by jeremyw24** [comment]
@darshankawar sure, here is some bits of code from their corresponding files that would enable you to likely reproduce the problem.

In main.dart I just initialize Firebase as expected, everything else is pretty standard `await Firebase.initializeApp();` 

login_page.dart - the below code calls the sign in, there is also a scaffold to build the page with the sign in widget.

```
class OpeningView extends StatefulWidget {
  @override
  _OpeningViewState createState() => _OpeningViewState();
}

class _OpeningViewState extends State<OpeningView> {
  GoogleSignInAccount _currentUser;
  final firestoreInstance = FirebaseFirestore.instance;

  void initState() {
    super.initState();
  }

  Widget _signInButton() {
    return OutlineButton(
      splashColor: Colors.grey,
      onPressed: () {
        signInWithGoogle().then((result) {
          if (result != null) {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) {
                  return HomeView();
                },
              ),
            );
          }
        });
      },
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(40)),
      highlightElevation: 0,
      borderSide: BorderSide(color: Colors.grey),
      child: Padding(
        padding: const EdgeInsets.fromLTRB(0, 10, 0, 10),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image(image: AssetImage("assets/google_logo.png"), height: 35.0),
            Padding(
              padding: const EdgeInsets.only(left: 10),
              child: Text(
                'Sign in with Google',
                style: TextStyle(
                  fontSize: 20,
                  color: Colors.grey,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
```

sign_in.dart - does all the sign in function:
```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_sign_in/google_sign_in.dart';

final FirebaseAuth _auth = FirebaseAuth.instance;
final GoogleSignIn googleSignIn = GoogleSignIn();
final firestoreInstance = FirebaseFirestore.instance;

String name;
String firstName;
String email;
//String imageUrl;
String uid;

var dateTime = DateTime.now();

void writeData() {
  firestoreInstance.collection("login").add({
    "user": "$name",
    "dateTime": "$dateTime",
    "email": "$email",
    "uid": "$uid",
  });
}

Future<String> signInWithGoogle() async {
  await Firebase.initializeApp();

  final GoogleSignInAccount googleSignInAccount = await googleSignIn.signIn();
  final GoogleSignInAuthentication googleSignInAuthentication =
      await googleSignInAccount.authentication;

  final AuthCredential credential = GoogleAuthProvider.credential(
    accessToken: googleSignInAuthentication.accessToken,
    idToken: googleSignInAuthentication.idToken,
  );

  final UserCredential authResult =
      await _auth.signInWithCredential(credential);
  final User user = authResult.user;

  if (user != null) {
    // Checking if email and name is null
    assert(user.email != null);
    assert(user.displayName != null);
    //assert(user.photoURL != null);
    assert(user.uid != null);

    name = user.displayName;
    email = user.email;
    //imageUrl = user.photoURL;
    uid = user.uid;

    // Only taking the first part of the name, i.e., First Name
    if (name.contains(" ")) {
      firstName = name.substring(0, name.indexOf(" "));
    }

    assert(!user.isAnonymous);
    assert(await user.getIdToken() != null);

    final User currentUser = _auth.currentUser;
    assert(user.uid == currentUser.uid);

    print('signInWithGoogle succeeded: $user');

    writeData();

    return '$user';
  }

  return null;
}

Future<void> signOutGoogle() async {
  await googleSignIn.signOut();

  print("User Signed Out");
}
```

then back to login_page.dart to decide what to do after user logs in:
```
@override
  Widget build(BuildContext context) {
    if (_currentUser != null) {
      return HomeView();
    } else {
      return buildSignInScreen();
    }
  }
```

**Comment by juliocruz83** [comment]
I am having the same problem. Running on a Samsung device while debugging works, but when installing the app on the same device from Play Store (Closed Testing) it prompts for the selection of the account but then it doesn't do anything.

Using -> google_sign_in: ^4.5.1

This is what I get from Logcat:

2020-10-05 22:12:44.944 1379-11507/? E/Parcel: Class not found when unmarshalling: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
    java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8552)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:847)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2068)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1717)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1613)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1566)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1737)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.signin.internal.SignInConfiguration
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031) 
        at android.os.Parcel.readParcelable(Parcel.java:2981) 
        at android.os.Parcel.readValue(Parcel.java:2883) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getString(BaseBundle.java:1160) 
        at android.content.Intent.getStringExtra(Intent.java:8552) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:847) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732) 
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2068) 
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1717) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1613) 
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1566) 
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1737) 
        at android.os.Binder.execTransactInternal(Binder.java:1056) 
        at android.os.Binder.execTransact(Binder.java:1029) 
2020-10-05 22:12:45.126 1379-10552/? E/Parcel: Class not found when unmarshalling: com.google.android.gms.common.api.Scope
    java.lang.ClassNotFoundException: com.google.android.gms.common.api.Scope
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readParcelableArray(Parcel.java:3094)
        at android.os.Parcel.readValue(Parcel.java:2937)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8552)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:847)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2068)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646)
        at com.android.server.wm.ActivityStartController.startActivityInPackage(ActivityStartController.java:346)
        at com.android.server.wm.ActivityTaskManagerService$LocalService.startActivityInPackage(ActivityTaskManagerService.java:7897)
        at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:457)
        at com.android.server.wm.ActivityTaskManagerService.startActivityIntentSender(ActivityTaskManagerService.java:1746)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1873)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.common.api.Scope
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031) 
        at android.os.Parcel.readParcelable(Parcel.java:2981) 
        at android.os.Parcel.readParcelableArray(Parcel.java:3094) 
        at android.os.Parcel.readValue(Parcel.java:2937) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getString(BaseBundle.java:1160) 
        at android.content.Intent.getStringExtra(Intent.java:8552) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:847) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732) 
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2068) 
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646) 
        at com.android.server.wm.ActivityStartController.startActivityInPackage(ActivityStartController.java:346) 
        at com.android.server.wm.ActivityTaskManagerService$LocalService.startActivityInPackage(ActivityTaskManagerService.java:7897) 
        at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:457) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityIntentSender(ActivityTaskManagerService.java:1746) 
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1873) 
        at android.os.Binder.execTransactInternal(Binder.java:1056) 
        at android.os.Binder.execTransact(Binder.java:1029) 
2020-10-05 22:12:45.186 30444-18492/? E/cmgq: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at cmgp.<init>(:com.google.android.gms@203615039@20.36.15 (120408-333172415):3)
        at cmgq.<init>(:com.google.android.gms@203615039@20.36.15 (120408-333172415):2)
        at cmaf.b(:com.google.android.gms@203615039@20.36.15 (120408-333172415):22)
        at sqe.a(:com.google.android.gms@203615039@20.36.15 (120408-333172415):31)
        at sqe.a(:com.google.android.gms@203615039@20.36.15 (120408-333172415):38)
        at asxy.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at svu.b(:com.google.android.gms@203615039@20.36.15 (120408-333172415):12)
        at svu.run(:com.google.android.gms@203615039@20.36.15 (120408-333172415):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at tbu.run(:com.google.android.gms@203615039@20.36.15 (120408-333172415):0)
        at java.lang.Thread.run(Thread.java:919)
2020-10-05 22:12:45.187 824-1285/? E/Netd: getNetworkForDns: getNetId from enterpriseCtrl is netid 0
2020-10-05 22:12:48.642 1379-12145/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2020-10-05 22:13:10.282 1379-1479/? E/Watchdog: !@Sync 4787 [2020-10-05 22:13:10.282] FD count : 674, wdog_way : pwdt

**Comment by darshankawar** [comment]
Tried to replicate this by installing an app from play store that has Google Sign in, but I was able to see the account selection dialog and was able to directly login as required. Tested on Samsung 8.1.0 and S10+ device, but since @jeremyw24 is consistently seeing the issue, keeping this open for further analysis.

**Comment by jeremyw24** [comment]
@darshankawar I can invite you to my internal testers list if you want to download my app and see the issue?

**Comment by AggroFront** [comment]
i had the same problem.

I solved that problem by putting "App signing Key" to OAuth 2.0 Client ID SHA-1 finger print instead of signed key which was generated by using keytool. If you have checked "Google Play App Signing" in Google Play Console, the usual signed key will not work. 
Check out your App signing Key in Google Play Console>App signing>App signing certificate and then copy SHA-1 certificate fingerprint and paste to Google API console OAuth 2.0 Client ID. 

It worked for me! 🥰

**Comment by jeremyw24** [comment]
@AggroFront I owe you a beer - what a legend!

This is now working as expected.

**Comment by ZahraVe** [comment]
@jeremyw24 and @AggroFront 
Hi, I am having an issue with only S23Ultra, and getting PlafrmExeption. I am going to try what has worked for you but I am not sure about "Google API console OAuth 2.0 Client ID". So I found the SHA-1 key you mentioned, and I am using Firebase. Not sure where to paste it? there is "Safelist client IDs from external projects (optional)" in the Sign-in method of the Authentication in Firebase. Is it the same as "Google API console OAuth 2.0 Client ID"?

**Comment by ZahraVe** [comment]
Managed to fix my issue by following [this answer](https://stackoverflow.com/a/77087868/14187647).
Adding scopes like so:

`final googleUser = await GoogleSignIn(scopes: ['profile', 'email']).signIn();`

But I would appreciate any explanation from anyone who can explain why adding scope solves the issue!? and why it was happening only on S23 Ultra and working fine on S22 Ultra with the same Android version!?
