### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by oldner** [flutter/flutter#67312]
Hey

Trying to create an app but it showed an error. Here it says:

Thought I should tell you about that. 

<details> 
<summary>logs</summary> 

```bash
Restarted application in 4,542ms.

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown building:[39;49m
'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 26 pos 14: 'url != null': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      new NetworkImage[39;49m 
 package:flutter/…/painting/_network_image_io.dart
[38;5;244m#3      new Image.network[39;49m 
 package:flutter/…/widgets/image.dart
[38;5;248m#4      _NewsState.build.<anonymous closure>[39;49m 
 package:haberler_api/pages/news.dart
[38;5;244m#5      SliverChildBuilderDelegate.build[39;49m 
 package:flutter/…/widgets/sliver.dart
[38;5;244m#6      SliverMultiBoxAdaptorElement._build.<anonymous closure>[39;49m 
 package:flutter/…/widgets/sliver.dart
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building:
'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 26 pos 14: 'url !=
null': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
[38;5;244m#2      new NetworkImage[39;49m 
 package:flutter/…/painting/_network_image_io.dart
[38;5;244m#3      new Image.network[39;49m 
 package:flutter/…/widgets/image.dart
[38;5;248m#4      _NewsState.build.<anonymous closure>[39;49m 
 package:haberler_api/pages/news.dart
[38;5;244m#5      SliverChildBuilderDelegate.build[39;49m 
 package:flutter/…/widgets/sliver.dart
[38;5;244m#6      SliverMultiBoxAdaptorElement._build.<anonymous closure>[39;49m 
 package:flutter/…/widgets/sliver.dart
[38;5;244m#7      _HashMap.putIfAbsent  (dart:collection-patch/collection_patch.dart:140:29))[39;49m
[38;5;244m#8      SliverMultiBoxAdaptorElement._build[39;49m 
 package:flutter/…/widgets/sliver.dart
[38;5;244m#9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure>[39;49m 
 package:flutter/…/widgets/sliver.dart
[38;5;244m#10     BuildOwner.buildScope[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244m#11     SliverMultiBoxAdaptorElement.createChild[39;49m 
 package:flutter/…/widgets/sliver.dart
[38;5;244m#12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>[39;49m 
 package:flutter/…/rendering/sliver_multi_box_adaptor.dart
[38;5;244m#13     RenderObject.invokeLayoutCallback.<anonymous closure>[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#14     PipelineOwner._enableMutationsToDirtySubtrees[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#15     RenderObject.invokeLayoutCallback[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#16     RenderSliverMultiBoxAdaptor._createOrObtainChild[39;49m 
 package:flutter/…/rendering/sliver_multi_box_adaptor.dart
[38;5;244m#17     RenderSliverMultiBoxAdaptor.insertAndLayoutChild[39;49m 
 package:flutter/…/rendering/sliver_multi_box_adaptor.dart
[38;5;244m#18     RenderSliverList.performLayout.advance[39;49m 
 package:flutter/…/rendering/sliver_list.dart
[38;5;244m#19     RenderSliverList.performLayout[39;49m 
 package:flutter/…/rendering/sliver_list.dart
[38;5;244m#20     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#21     RenderSliverEdgeInsetsPadding.performLayout[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#22     RenderSliverPadding.performLayout[39;49m 
 package:flutter/…/rendering/sliver_padding.dart
[38;5;244m#23     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#24     RenderViewportBase.layoutChildSequence[39;49m 
 package:flutter/…/rendering/viewport.dart
[38;5;244m#25     RenderViewport._attemptLayout[39;49m 
 package:flutter/…/rendering/viewport.dart
[38;5;244m#26     RenderViewport.performLayout[39;49m 
 package:flutter/…/rendering/viewport.dart
[38;5;244m#27     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#28     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#29     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#30     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#31     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#32     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#33     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#34     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#35     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#36     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#37     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#38     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#39     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#40     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#41     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#42     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#43     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#44     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#45     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#46     MultiChildLayoutDelegate.layoutChild[39;49m 
 package:flutter/…/rendering/custom_layout.dart
[38;5;244m#47     _ScaffoldLayout.performLayout[39;49m 
 package:flutter/…/material/scaffold.dart
[38;5;244m#48     MultiChildLayoutDelegate._callPerformLayout[39;49m 
 package:flutter/…/rendering/custom_layout.dart
[38;5;244m#49     RenderCustomMultiChildLayoutBox.performLayout[39;49m 
 package:flutter/…/rendering/custom_layout.dart
[38;5;244m#50     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#51     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#52     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#53     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#54     _RenderCustomClip.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#55     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#56     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#57     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#58     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#59     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#60     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#61     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#62     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#63     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#64     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#65     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#66     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#67     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#68     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#69     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#70     RenderOffstage.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#71     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#72     RenderProxyBoxMixin.performLayout[39;49m 
 package:flutter/…/rendering/proxy_box.dart
[38;5;244m#73     RenderObject.layout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#74     _RenderTheatre.performLayout[39;49m 
 package:flutter/…/widgets/overlay.dart
[38;5;244m#75     RenderObject._layoutWithoutResize[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#76     PipelineOwner.flushLayout[39;49m 
 package:flutter/…/rendering/object.dart
[38;5;244m#77     RendererBinding.drawFrame[39;49m 
 package:flutter/…/rendering/binding.dart
[38;5;244m#78     WidgetsBinding.drawFrame[39;49m 
 package:flutter/…/widgets/binding.dart
[38;5;244m#79     RendererBinding._handlePersistentFrameCallback[39;49m 
 package:flutter/…/rendering/binding.dart
[38;5;244m#80     SchedulerBinding._invokeFrameCallback[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#81     SchedulerBinding.handleDrawFrame[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#82     SchedulerBinding._handleDrawFrame[39;49m 
 package:flutter/…/scheduler/binding.dart
[38;5;244m#86     _invoke  (dart:ui/hooks.dart:253:10))[39;49m
[38;5;244m#87     _drawFrame  (dart:ui/hooks.dart:211:3))[39;49m
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details> 

And here is my code. Good luck

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

class News extends StatefulWidget {
  @override
  _NewsState createState() => _NewsState();
}

class _NewsState extends State<News> {
  List data;

  @override
  Widget build(BuildContext context) {
    data = ModalRoute.of(context).settings.arguments;
    return Scaffold(
      body: ListView.builder(
        itemCount: data.length,
        itemBuilder: (context, int index) {
          return Padding(
            padding: EdgeInsets.fromLTRB(20, 20, 20, 10),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                GestureDetector(
                    onTap: () {
                      Navigator.pushReplacementNamed(context, '/readnew',
                          arguments: {
                            'title': data[index]['title'],
                            'urlToImage': data[index]['urlToImage'],
                            'description': data[index]['description']
                          });
                    },
                    child: Image.network(data[index]['urlToImage'])),
                Padding(
                  padding: const EdgeInsets.fromLTRB(0, 10, 0, 0),
                  child: GestureDetector(
                    onTap: () {
                      Navigator.pushReplacementNamed(context, '/readnew',
                          arguments: {
                            'title': data[index]['title'],
                            'urlToImage': data[index]['urlToImage'],
                            'description': data[index]['description']
                          });
                    },
                    child: Text(
                      data[index]['title'],
                      style: TextStyle(
                        fontSize: 15,
                      ),
                    ),
                  ),
                )
              ],
            ),
          );
        },
      ),
    );
  }
}
```

</details>

**Comment by oldner** [comment]
What doctor says : 
`flutter\projects\haberler_api> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.49.3)
[√] Connected device (1 available)

• No issues found!`

**Comment by TahaTesser** [comment]
Hi @oldner 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Your code sample incomplete, Can you please provide  a complete reproducible minimal code sample
Thank you

**Comment by oldner** [comment]
Hi, thanks for your response. I upgraded flutter to 1.22 stable version. Well nothing changed actually but app works fine. Here is the rest of the code: (news.dart is already in the main topic.) 

Sorry, idk if there is any other website that i can share all files with you. 

main.dart
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:haberler_api/pages/home.dart';
import './pages/loading.dart';
import './pages/news.dart';
import './pages/readnew.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      routes: {
        '/': (context) => Home(),
        '/loading': (context) => Loading(),
        '/news': (context) => News(),
        '/readnew': (context) => ReadNew(),
      },
    );
  }
}
`

home.dart
`import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
              begin: Alignment.topRight,
              end: Alignment.bottomLeft,
              colors: [Colors.blue[300], Colors.blue[900]]),
        ),
          child: Center(
            child: SafeArea(
              child: Column(
                children: [
                  Image.asset('assets/logo.png', width: 150, height: 250,),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(15, 0, 15, 0),
                    child: Text('Haberler API uygulamasina hosgeldiniz.', 
                    style: TextStyle(fontSize: 30, color: Colors.white),),
                  ),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(15, 0, 15, 100),
                    child: Text('Haberleri gormek icin lutfen butona tiklayin.', style: TextStyle(color: Colors.red[200], fontWeight: FontWeight.bold),),
                  ),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(0, 0, 0, 0),
                    child: Container(
                      width: 400,
                      height: 50,
                      child: FlatButton(
                        color: Colors.blue[200],
                        onPressed: () {
                          Navigator.pushNamed(context, '/loading');
                        },
                        child: Text('Devam et')),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(0, 30, 0, 0),
                    child: Text('By HSP', style: TextStyle(color: Colors.white),),
                  ),
                ],
              ),
            ),
          ),
      ),
    );
  }
}
`

readnew.dart

`import 'package:flutter/material.dart';

class ReadNew extends StatefulWidget {
  @override
  _ReadNewState createState() => _ReadNewState();
}

class _ReadNewState extends State<ReadNew> {
  Map data;

  void deneme(title) {
    print(title);
  }

  @override
  Widget build(BuildContext context) {
    data = ModalRoute.of(context).settings.arguments;
    return Scaffold(
      appBar: AppBar(
        leading: GestureDetector(
          onTap: () {
            Navigator.popAndPushNamed(context, '/loading');
          },
          child: Icon(
            Icons.arrow_back,
          ),
        ),
        title: Text('Haber icerigi'),
      ),
      body: Column(
        children: [
          Image.network(data['urlToImage']),
          GestureDetector(
            onTap: () {
              deneme(data['title']);
            },
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(data['description'], style: TextStyle(fontSize: 15)),
            ),
          )
        ],
      ),
    );
  }
}
`

loading.dart

`import 'package:flutter/material.dart';
import '../services/newsapi.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';

class Loading extends StatefulWidget {
  @override
  _LoadingState createState() => _LoadingState();
}

class _LoadingState extends State<Loading> {
  List data;

  void getNews() async {
    NewsApi apiData = NewsApi();
    await apiData.getNews();
    if (apiData.data != null) {
      this.data = apiData.data['articles'];
      Navigator.pushNamed(context, '/news', arguments: data);
    }
  }

  @override
  void initState() {
    super.initState();
    getNews();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.blue[900],
        body: Center(
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
            SpinKitSquareCircle(
              color: Colors.white,
              size: 66.0,
            ),
            Padding(
              padding: const EdgeInsets.only(top: 30),
              child: Text(
                'Loading..',
                style: TextStyle(color: Colors.white, fontSize: 24),
              ),
            )
          ]),
        ));
  }
}
`

newsapi.dart

`import 'package:http/http.dart';
import 'dart:convert';

class NewsApi {
  String url =
      'http://newsapi.org/v2/top-headlines?country=tr&apiKey=b987528965b84f99ada2bb070dd556ba';
  Map data;

  Future<void> getNews() async {
    try {
      final response = await get(url);
      data = json.decode(response.body);
      
    } catch (e) {}
  }
}
`

**Comment by oldner** [comment]
Update: Okey. I restarted VSCode again. Now it looks fine. There is no any errors

**Comment by Abhishek01039** [comment]
Hi @oldner 
`Image.network(data['urlToImage']),` maybe this data['urlToImage'] is null
please use null safety like if data['urlToImage'] != null ? show image : any logo image.
Thanks
