### ISSUE TITLE
iOS builds but unable to install to device

### ISSUE THREAD

**Issue by idaWHALE** [flutter/flutter#67355]
I have been having some this issue for some time. Android builds and installs work just fine as well as `flutter build ios` with no errors. I have tried reinstalling pods, cleaning project, etc. When I try to run on iOS device with Android Studio I get:
```
Could not run build/ios/iphoneos/Runner.app on 2d**********************8.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on iPhone.
```

When I try to run in xcode I get:
```
Unable to install "Runner"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
--
Could not inspect the application package.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
User Info: {
    DVTRadarComponentKey = 282703;
    MobileDeviceErrorCode = "(0xE8000051)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011eab993f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000011eaf8124 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x0000000101d1fb43 DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000011eaf7e65 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000011e968d28 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000101e4e2aa __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000101e4fecc __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff6a1416c4 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff6a142658 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff6a147c44 _dispatch_lane_serial_drain + 597
	10  libdispatch.dylib                   0x00007fff6a1485d6 _dispatch_lane_invoke + 363
	11  libdispatch.dylib                   0x00007fff6a151c09 _dispatch_workloop_worker_thread + 596
	12  libsystem_pthread.dylib             0x00007fff6a39ca3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff6a39bb77 start_wqthread + 15
);
}
--


System Information

macOS Version 10.15.7 (Build 19H2)
Xcode 12.0.1 (17220)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.23.0-8.0.pre.94, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!
```

Any ideas where to start looking?

**Comment by TahaTesser** [comment]
Hi @idaWHALE 
Can you please provide  your `flutter run --verbose` with a device attached, paste logs in a plain text file `.txt`  and drop in the comments below   and a complete reproducible minimal code sample
Thank you

**Comment by illukinati** [comment]
@TahaTesser 
```
 Error launching application on Luki’s iPhone.
[   +7 ms] "flutter run" took 84,176ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:612:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:990:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by stemberamichal** [comment]
Hi @idaWHALE  

I had the exact same problem. 
I am not using flutter though but I think it is not flutter related issue. 
What helped me was restarting my Mac and iPhone and then cleaning and deleting Derived data (both done in Xcode).
I guess the restarts were not necessary but I can only guess now.

Good look

**Comment by kathan2511** [comment]
@idaWHALE How did you solve this exactly, I am too getting the exact same error as you are

**Comment by maks** [comment]
I'm seeing exactly the same issue on a M1 macmini with flutter 2.2.1 (stable channel).
Clearing derived data does not help.
Infact I only see this after adding the Firebase (`firebase_core: ^1.2.1`) package as a dependency to an existing app which already has dependecies on Firebase cocoapods in its existing swift code. As soon as I remove the firebase core package dependency and do `flutter clean` and `flutter run` the app installs again without any error.
@pedromassango perhaps this can be re-opened, at least to determine if this is an issue with Firebase plugin, Flutter SDK, using Firebase xcframeworks with Flutter Fire packages or any/none of the above.

**Comment by TahaTesser** [comment]
@maks 

> Infact I only see this after adding the Firebase (firebase_core: ^1.2.1) package as a dependency to an existing app which already has dependecies on Firebase cocoapods in its existing swift code. As soon as I remove the firebase core package dependency and do flutter clean and flutter run the app installs again without any error.

If it reproduces with firebase, the issue goes sway if remove it then it is not likely a Flutter issue. Please file an issue on the Fluttefire repo
