### ISSUE TITLE
Error while installing pods after upgraded Flutter to Flutter 1.20 

### ISSUE THREAD

**Issue by DhavalRKansara** [flutter/flutter#67385]
I have upgraded flutter to version 1.20. After this updated when I run my application getting below error while installing the pods.

```
Running pod install...
CocoaPods' output:
↳
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

Fetching external sources
-> Fetching podspec for `Flutter` from `Flutter`
-> Pre-downloading: `RSMasterTableView` from `https://github.com/DhavalRKansara/RSMasterTableView.git`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/DhavalRKansara/RSMasterTableView.git /var/folders/97/2fvk3h3x14j_l_8dws1pfl0w0000gn/T/d20201006-18021-1f2gksw --template= --single-branch --depth 1
  $ /usr/bin/git -C /var/folders/97/2fvk3h3x14j_l_8dws1pfl0w0000gn/T/d20201006-18021-1f2gksw rev-parse HEAD
  cdd7589104bea14a4edde2e2aa51d3d9fbe25895
  > Copying RSMasterTableView from `/Users/dhavalkansara/Library/Caches/CocoaPods/Pods/External/RSMasterTableView/68e9c9321b21272c083d847c792cb1d1` to `Pods/RSMasterTableView`
-> Pre-downloading: `SwiftR` from `https://github.com/DhavalRKansara/SwiftR.git`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/DhavalRKansara/SwiftR.git /var/folders/97/2fvk3h3x14j_l_8dws1pfl0w0000gn/T/d20201006-18021-i8xn7w --template= --single-branch --depth 1
  $ /usr/bin/git -C /var/folders/97/2fvk3h3x14j_l_8dws1pfl0w0000gn/T/d20201006-18021-i8xn7w rev-parse HEAD
  13af9e0849953f0a46a8a50056e12149056564cb
  > Copying SwiftR from `/Users/dhavalkansara/Library/Caches/CocoaPods/Pods/External/SwiftR/0defc76c8ae4b7e310c95e599f71436a` to `Pods/SwiftR`
-> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
-> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
firebase_analytics: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_analytics_web` from `.symlinks/plugins/firebase_analytics_web/ios`
-> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
firebase_core: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios`
-> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
firebase_crashlytics: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
firebase_messaging: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
-> Fetching podspec for `firebase_remote_config` from `.symlinks/plugins/firebase_remote_config/ios`
firebase_remote_config: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
-> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
-> Fetching podspec for `flutter_plugin_android_lifecycle` from `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`
-> Fetching podspec for `flutter_secure_storage` from `.symlinks/plugins/flutter_secure_storage/ios`
-> Fetching podspec for `flutter_udid` from `.symlinks/plugins/flutter_udid/ios`
-> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
-> Fetching podspec for `local_auth` from `.symlinks/plugins/local_auth/ios`
-> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
-> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
-> Fetching podspec for `path_provider_linux` from `.symlinks/plugins/path_provider_linux/ios`
-> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`
-> Fetching podspec for `path_provider_windows` from `.symlinks/plugins/path_provider_windows/ios`
-> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
-> Fetching podspec for `qr_code_scanner` from `.symlinks/plugins/qr_code_scanner/ios`
-> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
-> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
-> Fetching podspec for `shared_preferences_linux` from `.symlinks/plugins/shared_preferences_linux/ios`
-> Fetching podspec for `shared_preferences_macos` from `.symlinks/plugins/shared_preferences_macos/ios`
-> Fetching podspec for `shared_preferences_web` from `.symlinks/plugins/shared_preferences_web/ios`
-> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
-> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
-> Fetching podspec for `url_launcher_linux` from `.symlinks/plugins/url_launcher_linux/ios`
-> Fetching podspec for `url_launcher_macos` from `.symlinks/plugins/url_launcher_macos/ios`
-> Fetching podspec for `url_launcher_web` from `.symlinks/plugins/url_launcher_web/ios`
-> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios`
-> Fetching podspec for `vibration_web` from `.symlinks/plugins/vibration_web/ios`
[!] No podspec found for `vibration_web` in `.symlinks/plugins/vibration_web/ios`

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:980:in `fetch_external_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:959:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:958:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:958:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:957:in `fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/dhavalkansara/flutter in PATH, mode 040777
     Cloning into '/var/folders/97/2fvk3h3x14j_l_8dws1pfl0w0000gn/T/d20201006-18021-1f2gksw'...
     Cloning into '/var/folders/97/2fvk3h3x14j_l_8dws1pfl0w0000gn/T/d20201006-18021-i8xn7w'...

Error running pod install
Error launching application on iPhone 11 Pro Max.
```

**Flutter Doctor:**

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.20.3 at /Users/dhavalkansara/flutter 1.20/flutter
    • Framework revision 216dee60c0 (5 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dhavalkansara/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
```
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 5A2C9360-628E-44E8-A5A1-3EC3EA2342EE • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
Process finished with exit code 0

**PodFile**:

```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
      else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods
    
    pod 'Firebase/Core'
    pod 'NVActivityIndicatorView', '~> 4.8.0'
    pod 'SwiftyUserDefaults', '~> 3.0.0'
    pod 'RSMasterTableView', :git => 'https://github.com/DhavalRKansara/RSMasterTableView.git'
    pod 'CryptoSwift'
    pod 'SwiftR' , :git => 'https://github.com/DhavalRKansara/SwiftR.git'
    pod 'SKPhotoBrowser'
    pod 'RSSelectionMenu'
    pod 'JJFloatingActionButton'
    pod 'MaterialComponents/TextFields'
    pod 'MarqueeLabel'
    pod 'Firebase/Analytics'

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',

      ## dart: PermissionGroup.calendar
      'PERMISSION_EVENTS=0',

      ## dart: PermissionGroup.reminders
      'PERMISSION_REMINDERS=0',

      ## dart: PermissionGroup.contacts
      # 'PERMISSION_CONTACTS=0',

      ## dart: PermissionGroup.camera
      # 'PERMISSION_CAMERA=0',

      ## dart: PermissionGroup.microphone
      'PERMISSION_MICROPHONE=0',

      ## dart: PermissionGroup.speech
      'PERMISSION_SPEECH_RECOGNIZER=0',

      ## dart: PermissionGroup.photos
      # 'PERMISSION_PHOTOS=0',

      ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
      'PERMISSION_LOCATION=0',

      ## dart: PermissionGroup.notification
      # 'PERMISSION_NOTIFICATIONS=0',

      ## dart: PermissionGroup.mediaLibrary
      'PERMISSION_MEDIA_LIBRARY=0',

      ## dart: PermissionGroup.sensors
      'PERMISSION_SENSORS=0'
      ]

    end
  end
end

```

- I have also tried [Github's answer](https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482) but not working for me.

**Comment by darshankawar** [comment]
@DhavalRKansara 
The current stable version is 1.22.0. Please try to upgrade to latest stable along with cocoapods and see if it works for you.
Also, from your logs, I see below:

`No podspec found for vibration_web in .symlinks/plugins/vibration_web/ios`.

It seems the podfile for above plugin wasn't created for some reason. Please check the plugins you are using in `pubspec.yaml` and see if `vibration` plugin is supported properly on iOS. 

Also, I see that the current `vibration_web` plugin is 1.6.2 and seems to have fix for iOS. Please upgrade this plugin to latest and see if it works.

https://pub.dev/packages/vibration_web/changelog

**Comment by DhavalRKansara** [comment]
@darshankawar Thank you for your reference... I was using [vibration](https://pub.dev/packages/vibration) in my pubspec.yaml. By updating it to the latest version above issue fixed but now I am getting a below error.

```
ld: warning: directory not found for option '-F/Users/dhavalkansara/Flutter Development/my-doses/ios/Frameworks'
Undefined symbols for architecture x86_64:
  "___gxx_personality_v0", referenced from:
      +[FIRCLSDemangleOperation demangleBlockInvokeCppSymbol:] in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
      +[FIRCLSDemangleOperation demangleCppSymbol:] in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
      -[FIRCLSDemangleOperation main] in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
      ___31-[FIRCLSDemangleOperation main]_block_invoke in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
  "vtable for __cxxabiv1::__vmi_class_type_info", referenced from:
      typeinfo for std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > in FirebaseCrashlytics(FIRCLSException.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for std::__1::__basic_string_common<true> in FirebaseCrashlytics(FIRCLSException.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "typeinfo for std::bad_alloc", referenced from:
      GCC_except_table18 in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_end_catch", referenced from:
      FIRCLSCatchAndRecordActiveException(std::type_info*) in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_begin_catch", referenced from:
      FIRCLSCatchAndRecordActiveException(std::type_info*) in FirebaseCrashlytics(FIRCLSException.o)
      ___clang_call_terminate in FirebaseCrashlytics(FIRCLSException.o)
  "typeinfo for char const*", referenced from:
      _FIRCLSExceptionRaiseTestCppException in FirebaseCrashlytics(FIRCLSException.o)
      GCC_except_table18 in FirebaseCrashlytics(FIRCLSException.o)
  "std::get_terminate()", referenced from:
      _FIRCLSExceptionCheckHandlers in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_allocate_exception", referenced from:
      _FIRCLSExceptionRaiseTestCppException in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_rethrow", referenced from:
      FIRCLSCatchAndRecordActiveException(std::type_info*) in FirebaseCrashlytics(FIRCLSException.o)
  "vtable for __cxxabiv1::__pointer_type_info", referenced from:
      typeinfo for std::exception const* in FirebaseCrashlytics(FIRCLSException.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "___cxa_throw", referenced from:
      _FIRCLSExceptionRaiseTestCppException in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_current_exception_type", referenced from:
      FIRCLSTerminateHandler() in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_demangle", referenced from:
      +[FIRCLSDemangleOperation demangleCppSymbol:] in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in FirebaseCrashlytics(FIRCLSException.o)
  "std::set_terminate(void (*)())", referenced from:
      _FIRCLSExceptionInitialize in FirebaseCrashlytics(FIRCLSException.o)
      FIRCLSTerminateHandler() in FirebaseCrashlytics(FIRCLSException.o)
  "typeinfo for std::exception", referenced from:
      GCC_except_table18 in FirebaseCrashlytics(FIRCLSException.o)
      typeinfo for std::exception const* in FirebaseCrashlytics(FIRCLSException.o)
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in FirebaseAnalytics.o
      objc-class-ref in firebase_analytics(FLTFirebaseAnalyticsPlugin.o)
     (maybe you meant: _OBJC_CLASS_$_FIRAnalyticsConfiguration)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by darshankawar** [comment]
@DhavalRKansara 
Think it could be related to [56567](https://github.com/flutter/flutter/issues/56567).
Please try the solutions mentioned in above issue and see if they work for you.
Thanks.

**Comment by DhavalRKansara** [comment]
@darshankawar 
I have already tried the solutions mentioned in the [56567](https://github.com/flutter/flutter/issues/56567) but still getting the same error.

**Comment by darshankawar** [comment]
@DhavalRKansara 
Please try to delete `ios/Flutter/Flutter.framework` and then run `pod install` inside `ios` folder and then try `flutter run` from root to see if it works.
Thanks.

**Comment by DhavalRKansara** [comment]
@darshankawar 
Yes, I have already removed the `App.framework `and `Flutter.framework` as per [Xcode 11.4 migration](https://flutter.dev/docs/development/ios-project-migration) guidelines. Also after these steps removed pods and profiles and regenerated and reinstalled it but it's not working.

**Comment by darshankawar** [comment]
If you upgrade to latest Flutter, try to create a new project and check if you get same error. Could be related to some configs didn't come over properly after upgrading maybe. If you are able to build with new project, you may try to copy the related folders in your existing project and check.
Thanks.
