### ISSUE TITLE
Flutter cannot see my Android Emulator in version 1.22

### ISSUE THREAD

**Issue by UnicornsOnLSD** [flutter/flutter#67424]
## Steps to Reproduce

When I upgraded to version 1.22, Flutter became unable to see the Android emulator that I use for development. In version 1.20.4, Flutter can see the emulator fine. I have put my system info in the logs section.

1. Download Flutter 1.22 (I used git clone https://github.com/flutter/flutter.git -b stable --depth 1)
2. Start an Android Emulator in Android Studio
3. Run `flutter devices`. Nothing should show up.

## Logs

`flutter devices -vv` on 1.22:
```
[  +96 ms] executing: [/home/james/Android/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +28 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d408d302e22179d598f467e11da5dd968dbdc9ec
[        ] executing: [/home/james/Android/flutter/] git tag --points-at HEAD
[   +4 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.0
           1.22.0-12.3.pre
[   +6 ms] executing: [/home/james/Android/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/james/Android/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +31 ms] executing: [/home/james/Android/flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +18 ms] "flutter devices" took 35ms.
[   +4 ms] Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      DevicesCommand.runCommand (package:flutter_tools/src/commands/devices.dart:59:7)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:831:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:820:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 1
```
`flutter devices -v` on 1.20.4 (doing -vv didn't output any verbose output):
```
[ +108 ms] executing: [/home/james/Android/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fba99f6cf9a14512e461e3122c8ddfaa25394e89
[        ] executing: [/home/james/Android/flutter/] git tag --contains HEAD
[   +4 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.20.4
[   +7 ms] executing: [/home/james/Android/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +16 ms] executing: [/home/james/Android/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +23 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +9 ms] executing: /home/james/Android/Sdk/platform-tools/adb devices -l
[  +27 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64_arm64 model:sdk_gphone_x86_64_arm64 device:generic_x86_64_arm64 transport_id:1
[   +5 ms] 2 connected devices:
           
[   +4 ms] /home/james/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +24 ms] ro.hardware = ranchu
[   +4 ms] sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
[        ] Web Server (web)                 • web-server    • web-javascript • Flutter Tools
[   +1 ms] executing: /home/james/Android/Sdk/platform-tools/adb devices -l
[   +4 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64_arm64 model:sdk_gphone_x86_64_arm64 device:generic_x86_64_arm64 transport_id:1
[   +8 ms] "flutter devices" took 104ms.
[   +3 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

`flutter doctor -v` on 1.22:
```
[✓] Flutter (Channel stable, 1.22.0, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.0 at /home/james/Android/flutter
    • Framework revision d408d302e2 (7 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[!] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version openjdk version "1.8.0_242-release"

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

`flutter doctor -v` on 1.20.4:
```
[✓] Flutter (Channel unknown, 1.20.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.20.4 at /home/james/Android/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/james/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_242-release"
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Chrome - develop for the web (Cannot find Chrome executable at chromium)
    ! chromium is not executable.

[!] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version openjdk version "1.8.0_242-release"

[✓] Connected device (2 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Web Server (web)                 • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```
System info (`inxi -Fxxxza`):
```
System:    Kernel: 5.8.12-arch1-1 x86_64 bits: 64 compiler: N/A 
           parameters: root=UUID=7b99f218-4f62-4a1c-8437-beebdad06ec7 rootflags=subvol=@ initrd=intel-ucode.img 
           initrd=initramfs-linux.img 
           Desktop: KDE Plasma 5.19.5 tk: Qt 5.15.1 info: latte-dock wm: kwin_x11 dm: SDDM Distro: Arch Linux 
Machine:   Type: Desktop Mobo: ASUSTeK model: Z170M-PLUS v: Rev X.0x serial: <filter> UEFI: American Megatrends v: 3805 
           date: 05/16/2018 
CPU:       Info: Quad Core model: Intel Core i5-6600K bits: 64 type: MCP arch: Skylake-S family: 6 model-id: 5E (94) 
           stepping: 3 microcode: D6 L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 28009 
           Speed: 3658 MHz min/max: 800/3900 MHz Core speeds (MHz): 1: 3670 2: 3685 3: 3739 4: 3673 
           Vulnerabilities: Type: itlb_multihit status: KVM: Split huge pages 
           Type: l1tf mitigation: PTE Inversion; VMX: conditional cache flushes, SMT disabled 
           Type: mds mitigation: Clear CPU buffers; SMT disabled 
           Type: meltdown mitigation: PTI 
           Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via prctl and seccomp 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 mitigation: Full generic retpoline, IBPB: conditional, IBRS_FW, STIBP: disabled, RSB filling 
           Type: srbds status: Vulnerable: No microcode 
           Type: tsx_async_abort mitigation: Clear CPU buffers; SMT disabled 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] driver: amdgpu 
           v: kernel bus ID: 03:00.0 chip ID: 1002:731f 
           Display: x11 server: X.Org 1.20.9 compositor: kwin_x11 driver: amdgpu display ID: :0 screens: 1 
           Screen-1: 0 s-res: 2560x1440 s-dpi: 96 s-size: 677x381mm (26.7x15.0") s-diag: 777mm (30.6") 
           Monitor-1: DisplayPort-1 res: 2560x1440 hz: 144 dpi: 109 size: 597x336mm (23.5x13.2") diag: 685mm (27") 
           OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.38.0 5.8.12-arch1-1 LLVM 10.0.1) v: 4.6 Mesa 20.1.8 
           direct render: Yes 
Audio:     Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 chip ID: 8086:a170 
           Device-2: Advanced Micro Devices [AMD/ATI] Navi 10 HDMI Audio driver: snd_hda_intel v: kernel bus ID: 03:00.1 
           chip ID: 1002:ab38 
           Device-3: Sennheiser Sennheiser Main Audio type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-12:7 
           chip ID: 1395:005d serial: <filter> 
           Sound Server: ALSA v: k5.8.12-arch1-1 
Network:   Device-1: Intel Ethernet I219-V vendor: ASUSTeK driver: e1000e v: 3.2.6-k port: f000 bus ID: 00:1f.6 
           chip ID: 8086:15b8 
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 2.39 TiB used: 218.92 GiB (8.9%) 
           SMART Message: Required tool smartctl not installed. Check --recommends 
           ID-1: /dev/sda vendor: Seagate model: ST2000DM001-1ER164 size: 1.82 TiB block size: physical: 4096 B logical: 512 B 
           speed: 6.0 Gb/s rotation: 7200 rpm serial: <filter> rev: CC26 scheme: MBR 
           ID-2: /dev/sdb vendor: Crucial model: CT500MX500SSD1 size: 465.76 GiB block size: physical: 4096 B logical: 512 B 
           speed: 6.0 Gb/s serial: <filter> rev: 023 scheme: GPT 
           ID-3: /dev/sdc vendor: Samsung model: MZHPV128HDGM-00000 size: 119.24 GiB block size: physical: 512 B 
           logical: 512 B speed: 6.0 Gb/s serial: <filter> rev: 500Q scheme: GPT 
Partition: ID-1: / raw size: 465.51 GiB size: 465.51 GiB (100.00%) used: 218.84 GiB (47.0%) fs: btrfs dev: /dev/sdb2 
           ID-2: /boot raw size: 260.0 MiB size: 256.0 MiB (98.46%) used: 86.7 MiB (33.9%) fs: vfat dev: /dev/sdb1 
           ID-3: /home raw size: 465.51 GiB size: 465.51 GiB (100.00%) used: 218.84 GiB (47.0%) fs: btrfs dev: /dev/sdb2 
           ID-4: /var raw size: 465.51 GiB size: 465.51 GiB (100.00%) used: 218.84 GiB (47.0%) fs: btrfs dev: /dev/sdb2 
Swap:      Kernel: swappiness: 60 (default) cache pressure: 100 (default) 
           ID-1: swap-1 type: file size: 8.00 GiB used: 9.1 MiB (0.1%) priority: -2 file: /swapfile/swapfile 
Sensors:   System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: amdgpu temp: 52.0 C mem: 58.0 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 1164 
Info:      Processes: 253 Uptime: 1h 28m Memory: 15.58 GiB used: 5.14 GiB (33.0%) Init: systemd v: 246 Compilers: gcc: 10.2.0 
           Packages: pacman: 1077 lib: 362 Shell: Zsh v: 5.8 running in: konsole inxi: 3.1.06 
```

**Comment by jonahwilliams** [comment]
@UnicornsOnLSD  what is the output of `flutter config` ?

**Comment by jonahwilliams** [comment]
(The reason I ask is that it looks like you disabled android support with flutter config --no-android or similar)

**Comment by UnicornsOnLSD** [comment]
> @UnicornsOnLSD what is the output of `flutter config` ?

Here's the output:
```
Configure Flutter settings.

To remove a setting, configure it to an empty string.

The Flutter tool anonymously reports feature usage statistics and basic crash reports to help improve Flutter tools over time. See Google's privacy policy: https://www.google.com/intl/en/policies/privacy/

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with --help, shows hidden options.
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.
    --packages              Path to your ".packages" file.
                            (required, since the current directory does not contain a ".packages" file)

Usage: flutter config [arguments]
-h, --help                                      Print this usage information.
    --[no-]analytics                            Enable or disable reporting anonymously tool usage statistics and crash reports.
    --clear-ios-signing-cert                    Clear the saved development certificate choice used to sign apps for iOS device deployment.
    --android-sdk                               The Android SDK directory.
    --android-studio-dir                        The Android Studio install directory.
    --build-dir=<out/>                          The relative path to override a projects build directory
    --[no-]enable-web                           Enable or disable Flutter for web. This setting will take effect on the master, dev, and beta channels.
    --[no-]enable-linux-desktop                 Enable or disable Flutter for desktop on Linux. This setting will take effect on the master and dev channels.
    --[no-]enable-macos-desktop                 Enable or disable Flutter for desktop on macOS. This setting will take effect on the master and dev channels.
    --[no-]enable-windows-desktop               Enable or disable Flutter for desktop on Windows. This setting will take effect on the master channel.
    --[no-]single-widget-reload-optimization    Enable or disable Hot reload optimization for changes to class body of a single widget. This setting will take effect on the master, dev, beta, and stable channels.
    --[no-]enable-android                       Enable or disable Flutter for Android. This setting will take effect on the master, dev, beta, and stable channels.
    --[no-]enable-ios                           Enable or disable Flutter for iOS. This setting will take effect on the master, dev, beta, and stable channels.
    --[no-]enable-fuchsia                       Enable or disable Flutter for Fuchsia. This setting will take effect on the master channel.
    --clear-features                            Remove all configured features and restore them to the default values.

Run "flutter help" to see global options.

Settings:
  enable-android: false
  enable-ios: false
  android-sdk: /home/james/Android/Sdk

Analytics reporting is currently disabled.
```

Looks like it is disabled. Running `flutter config --enable-android` fixed the issue, thanks!
