### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:Stderr:warning [/Users/mac/Developer/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip]:  950342 extra bytes at beginning or within zipfile  

### ISSUE THREAD

**Issue by naman-jn** [flutter/flutter#67512]
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed
Stdout:

Stderr:
warning [/Users/mac/Developer/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip]:  950342 extra bytes at beginning or within zipfile
  (attempting to process anyway)
 Command: unzip, OS error code: 1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:463:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:237:21)
#3      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1638:18)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     ArtifactUpdater._download (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._complete (dart:async/future_impl.dart:519:7)
#19     Stream.forEach.<anonymous closure> (dart:async/stream.dart:943:14)
#20     _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:446:15)
#21     _rootRun (dart:async/zone.dart:1182:47)
#22     _CustomZone.run (dart:async/zone.dart:1093:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#24     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
```
```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.185, on Mac OS X 10.15.6 19G2021 x86_64, locale en-IN)
    • Flutter version 1.23.0-8.0.pre.185 at /Users/mac/Developer/flutter
    • Framework revision 6620f831e9 (8 hours ago), 2020-10-06 18:15:15 -0700
    • Engine revision 7e6191de07
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
May be related to [52437](https://github.com/flutter/flutter/issues/52437)

**Comment by darshankawar** [comment]
@naman-jn Can you switch to latest dev and see if you get same error or works ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
