### ISSUE TITLE
When InkWell has a GlobalKey and changes position, splash should not stop

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#6751]

**Comment by YeungKC** [comment]
Reproducible on master

example code:
https://github.com/flutter/flutter/issues/5456#issuecomment-454058948

flutter doctor:
[✓] Flutter (Channel master, 1.22.0-10.0.pre.88, on macOS 11.0.1 20B29, locale zh-Hans)

**Comment by Hixie** [comment]
Sorry I never added a test for this! What I was referring to is actually the opposite problem: when the key _doesn't_ change, but the widget moves (e.g. a new widget is added between the Material and the InkWell), then currently the splash gets canceled, but it should not, it should persist.

**Comment by YeungKC** [comment]
I have updated the reproducible code, please let me know if I have misunderstood it.

**Comment by Hixie** [comment]
(minor nit, but it's good practice to put the state changing inside the setState; that's why it's a closure. As in, `setState(() { wrap = !wrap; });`.)

**Comment by YeungKC** [comment]
Reproducible code has been updated.
I believe that this issue will be closed soon.

**Comment by dkwingsmt** [comment]
Reopening this issue because the PR that resolved it was reverted. 

I spent dozens of hours to reland it, but there's one error in Google's internal repo that I can't resolve. I've decided not to move on, but I'll write my progress here in case anyone wishes to pick up.

The PR is https://github.com/flutter/flutter/pull/99183. It passes all unit tests. In Google's internal repo, there are some golden tests changes, but (as of right now) they can all be accepted. The only problem left is an e2e test that results in the following error:

```
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5318 pos 12: 'newWidget.debugCanApplyOutOfTurn()': is not true.
#0 _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1 _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2 ParentDataElement.applyWidgetOutOfTurn (package:flutter/src/widgets/framework.dart:5318:12)
#3 _AutomaticKeepAliveState._updateParentDataOfChild (package:flutter/src/widgets/automatic_keep_alive.dart:143:18)
#4 _AutomaticKeepAliveState._addClient.<anonymous closure> (package:flutter/src/widgets/automatic_keep_alive.dart:101:11)
#5 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#6 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
#7 LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1612:13)
#8 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#9 _rootRun (dart:async/zone.dart:1398:13)
#10 _CustomZone.run (dart:async/zone.dart:1300:19)
#11 _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
#12 _invoke (dart:ui/hooks.dart:147:10)
#13 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:320:5)
#14 _drawFrame (dart:ui/hooks.dart:112:31)
```


But, for the record, @.Hixie speculated that, somehow _keepingAlive changes between when _addClient is called and the post-frame callback being invoked, which could be caused by both adding a client and removing a client in the same frame, hitting [automatic_keep_alive.dart line 215](https://github.com/flutter/flutter/blob/fe309e341544bfe4bc95491ce1f6ae78b66e9971/packages/flutter/lib/src/widgets/automatic_keep_alive.dart#L215). The code is bubbling a notification up to enable keepalive in the subtree, and then immediately notifying clients of the object handle passed to the KeepAliveNotification, which tells the keepalive to both add and remove the client in the same frame, and the add gets deferred to after the remove, at which point it complains that the client can't be removed asynchronously.

@.Hixie suggested that, an easy fix is to change _addClient in automatic_keep_alive to early return in the postframe callback when _keepingAlive is false, as in if (!mounted || !_keepingAlive) { return; }). The worst part is that I can't build a unit test for it, even if I managed to find some "cheap" fix.

**Comment by darshankawar** [comment]
I tried verifying this issue using the code sample provided [here](https://github.com/flutter/flutter/issues/6751#issuecomment-727621925) and running with latest master version, but I am not completely sure what to make of this. There's no error log triggered.


https://github.com/flutter/flutter/assets/67046386/e92bc4d2-3032-4c02-8453-ec813523d5a7

/cc @Hixie @dkwingsmt or @YeungKC for any thoughts on state of this issue.

**Comment by dkwingsmt** [comment]
@darshankawar Change `onTap` to `onTapDown`. For some reason `onTap` only takes effect after releasing the tap. (This can be made obvious by change the wrapping `Container` to a `ColoredBox`.

**Comment by darshankawar** [comment]
Revisited this issue and used code sample on latest stable version (3.24.1) and tried tapping shows below behavior. The splash seems to flicker upon tapping.


https://github.com/user-attachments/assets/4be35292-8931-4d96-96ca-a6f416441076

Will keep it open for team's further feedback.
