### ISSUE TITLE
Post method serialised Json body - Error- [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception:

### ISSUE THREAD

**Issue by azeemjmatics** [flutter/flutter#67535]
I have been stucked for last 2 days regarding flutter post method with JSON row body, the codes which I have tried as follows,

Code 1:
```
void send() async {

    userModel = UserModel(userName: "appuser", password: "Pass12345");

       var response = await http.post(
           "https://stagingapi.icert.....",
           headers: {"Content-Type": "application/json"},
           body: json.encode(userModel.toJson()));
       print(response.body);
       print(response.statusCode);
}

```
I have created serialised body Model like,
```
import 'package:json_annotation/json_annotation.dart';

part 'UserModel.g.dart';

@JsonSerializable()
class UserModel {
  String userName;
  String password;
  // String xyz;
  UserModel({this.userName, this.password});
  factory UserModel.fromJson(Map<String, dynamic> json) => _$UserModelFromJson(json);
  Map<String, dynamic> toJson() => _$UserModelToJson(this);
}
```
Code 2:-
```
Future<User> createUser(String username, String password) async{
  final String apiUrl = "https://stagingapi.icert....";
  Map<String,String> headers = {'Content-Type':'application/json'};
  final body = jsonEncode({ "userName": username,
    "password": password});
  try {
    var response = await http.post(apiUrl, headers: headers, body: body);
    print(response.statusCode);
    if(response.statusCode == 201){
      final String responseString = response.body;

      return userFromJson(responseString);
    }else{
      return null;
    }
  } catch (error) {
    print('error- $error');
   
    }
  }
}
```
In both cases or if I try any post code method it throws the following error,
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: 
#0      IOClient.send (package:http/src/io_client.dart:65:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:176:38)
#2      BaseClient.post (package:http/src/base_client.dart:58:7)
#3      post.<anonymous closure> (package:http/http.dart:70:16)
#4      _withClient (package:http/http.dart:166:20)
#5      post (package:http/http.dart:69:5)
#6      _SelectDOBState.send (package:kash_app/SelectDOB.dart:99:29)
#7      _SelectDOBState.initState (package:kash_app/SelectDOB.dart:92:6)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4812:57)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3380:18)
#12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:616<…>
```

**Comment by darshankawar** [comment]
@azeemjmatics 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by azeemjmatics** [comment]
@darshankawar 
```
azeemmacbook@Mohammeds-MacBook-Air kash_app % flutter doctor -v
[✓] Flutter (Channel beta, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0 at /Applications/iOS Projects/FlutterDeveloper/flutter
    • Framework revision d408d302e2 (9 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/azeemmacbook/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Users/azeemmacbook/Downloads/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone XR (mobile) • C8549C2A-2DCE-4576-968E-97052C65096E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    ! Error: Azeem’s iPhone 11 is not connected. Xcode will continue when Azeem’s iPhone 11 is connected. (code -13)

• No issues found!
```

**Comment by darshankawar** [comment]
@azeemjmatics 
Is it the complete log ? If not, please provide a complete stacktrace along with `flutter run --verbose`.
Thanks.

**Comment by azeemjmatics** [comment]
@darshankawar 
[flutter run --verbose.zip](https://github.com/flutter/flutter/files/5348078/flutter.run.--verbose.zip)

**Comment by darshankawar** [comment]
@azeemjmatics 
The Exception message doesn't seem to be complete : `[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception:`
Is there more to the exception ?
Can you try to switch to latest Master and see if you get same error ?
thanks.

**Comment by azeemjmatics** [comment]
@darshankawar, The above code is working in other urls...I have resolved this issue, it was from our backend team made some changes to domain url by adding some configuration in `IIS. OR secure certificate related`
