### ISSUE TITLE
Widget build error using Streambuilder.md

### ISSUE THREAD

**Issue by asongkai** [flutter/flutter#67602]
Dear Expert,

Please help me figure out is happening to my streambuilder 
this is the code:
```
                         StreamBuilder<QuerySnapshot>(
                              stream: FirebaseFirestore.instance
                                  .collection(USERS)
                                  .doc(G.loggedInId.toString())
                                  .collection('chatlist')
                                  .snapshots(),
                              builder: (context, snapshot) {
                                if (snapshot.connectionState == ConnectionState.done) {
                                  if (!snapshot.hasData) return Container();
                                  return FutureBuilder(
                                      future: countUnreadMessage(snapshot),
                                      builder: (context, countSnapshot) {
                                        if (!countSnapshot.hasData ||
                                            countSnapshot.data == 0)
                                          return Container();
                                        return FadeTransition(
                                          opacity: unreadChatsBadgeAnimation,
                                          child: Container(
                                            margin:
                                            const EdgeInsets.only(left: 4.0),
                                            decoration: BoxDecoration(
                                                color: Colors.white,
                                                borderRadius: BorderRadius.all(
                                                    Radius.circular(9.0))),
                                            alignment: Alignment.center,
                                            height: 18.0,
                                            width: 18.0,
                                            child: Text(
                                              '${countSnapshot.data}',
                                              style: TextStyle(
                                                fontSize: 12.0,
                                                fontWeight: FontWeight.bold,
                                                color: Colors.red,
                                              ),
                                            ),
                                          ),
                                        );
                                      });
                                }else {
                                  return Container();
                                }
                              },
                            ),
```

the streambuilder is inside at Tabbar

```
           TabBar(
                  controller: _tabController,
                  tabs: <Widget>[
                    Tab(
                      child: Container(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            Text(
                              "ສົນທະນາ",
                              style: _textBold,
                            ),
                            StreamBuilder<QuerySnapshot>(
                              stream: FirebaseFirestore.instance
                                  .collection(USERS)
                                  .doc(G.loggedInId.toString())
                                  .collection('chatlist')
                                  .snapshots(),
                              builder: (context, snapshot) {
                                  if (!snapshot.hasData) return Container();
                                  return FutureBuilder(
                                      future: countUnreadMessage(snapshot),
                                      builder: (context, countSnapshot) {
                                        if (!countSnapshot.hasData ||
                                            countSnapshot.data == 0)
                                          return Container();
                                        return FadeTransition(
                                          opacity: unreadChatsBadgeAnimation,
                                          child: Container(
                                            margin:
                                            const EdgeInsets.only(left: 4.0),
                                            decoration: BoxDecoration(
                                                color: Colors.white,
                                                borderRadius: BorderRadius.all(
                                                    Radius.circular(9.0))),
                                            alignment: Alignment.center,
                                            height: 18.0,
                                            width: 18.0,
                                            child: Text(
                                              '${countSnapshot.data}',
                                              style: TextStyle(
                                                fontSize: 12.0,
                                                fontWeight: FontWeight.bold,
                                                color: Colors.red,
                                              ),
                                            ),
                                          ),
                                        );
                                      });
                              },
                            ),
                          ],
                        ),
                      ),
                    ),
                    Tab(
                      child: Container(
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            Text(
                              "ເພື່ອນອອນລາຍ",
                              style: _textBold,
                            ),
                          ],
                        ),
                      ),
                    ),
                    Tab(
                      child: Text(
                        "ເພື່ອນທັງໝົດ",
                        style: _textBold,
                      ),
                    ),
                  ],
                  labelPadding: EdgeInsets.fromLTRB(0, 0, 0, 0),
                )
```

but when I run the app sometime the error not show but sometime the error show then continue showing the error 

```
E/flutter ( 7926): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(firebase_firestore, length=191; index=191, {}, null)
E/flutter ( 7926): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 7926): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 7926): <asynchronous suspension>
E/flutter ( 7926): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 7926): #3      MethodChannelQuery.snapshots.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:134:54)
E/flutter ( 7926): #4      _runGuarded (dart:async/stream_controller.dart:847:24)
E/flutter ( 7926): #5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
E/flutter ( 7926): #6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
E/flutter ( 7926): #7      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
E/flutter ( 7926): #8      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
E/flutter ( 7926): #9      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
E/flutter ( 7926): #10     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
E/flutter ( 7926): #11     _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:139:37)
E/flutter ( 7926): #12     _StreamBuilderBaseState.didUpdateWidget (package:flutter/src/widgets/async.dart:124:7)
E/flutter ( 7926): #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 7926): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 7926): #16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 7926): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #32     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 7926): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #44     StatelessElement.update (package:flutter/src/widgets
E/flutter ( 7926): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(firebase_firestore, length=191; index=191, {}, null)
E/flutter ( 7926): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 7926): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 7926): <asynchronous suspension>
E/flutter ( 7926): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 7926): #3      MethodChannelQuery.snapshots.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:134:54)
E/flutter ( 7926): #4      _runGuarded (dart:async/stream_controller.dart:847:24)
E/flutter ( 7926): #5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
E/flutter ( 7926): #6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
E/flutter ( 7926): #7      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
E/flutter ( 7926): #8      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
E/flutter ( 7926): #9      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
E/flutter ( 7926): #10     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
E/flutter ( 7926): #11     _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:139:37)
E/flutter ( 7926): #12     _StreamBuilderBaseState.didUpdateWidget (package:flutter/src/widgets/async.dart:124:7)
E/flutter ( 7926): #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 7926): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 7926): #16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 7926): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #32     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 7926): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #44     StatelessElement.update (package:flutter/src/widgets
E/flutter ( 7926): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(firebase_firestore, length=191; index=191, {}, null)
E/flutter ( 7926): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 7926): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 7926): <asynchronous suspension>
E/flutter ( 7926): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 7926): #3      MethodChannelQuery.snapshots.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:134:54)
E/flutter ( 7926): #4      _runGuarded (dart:async/stream_controller.dart:847:24)
E/flutter ( 7926): #5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
E/flutter ( 7926): #6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
E/flutter ( 7926): #7      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
E/flutter ( 7926): #8      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
E/flutter ( 7926): #9      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
E/flutter ( 7926): #10     _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
E/flutter ( 7926): #11     _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:139:37)
E/flutter ( 7926): #12     _StreamBuilderBaseState.didUpdateWidget (package:flutter/src/widgets/async.dart:124:7)
E/flutter ( 7926): #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 7926): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 7926): #16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 7926): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #32     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 7926): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 7926): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #40     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 7926): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 7926): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 7926): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 7926): #44     StatelessElement.update (package:flutter/src/widgets
```

**Comment by darshankawar** [comment]
@asongkai 
Your question is better suited for StackOver flow. Please consider asking support questions there. If you need help with your code, please see https://www.reddit.com/r/flutterhelp/
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
