### ISSUE TITLE
  ld: library not found for -lFMDB

### ISSUE THREAD

**Issue by mahbobyosf** [flutter/flutter#67627]
I am unable to build and run the iOS app on emulator or on physical device.
The terminal shows the following errors when I try to run the app in the emulator or physical device. 

<details> 
<summary>logs</summary> 

```bash
/Users/alhoussen/Library/Developer/Xcode/DerivedData/Runner-ajxjljkcfncrzqepzwhbwsvavpbz/Build/Intermediates.noindex/Runner.bu
                            ild/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat -o
                            /Users/mhbobalhoussen/Development/cross-word/build/ios/Debug-iphonesimulator/Runner.app/Runner
                        ld: library not found for -lFMDB
                        clang: error: linker command failed with exit code 1 (use -v to see invocation)
                    
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'FirebaseCoreDiagnosticsInterop' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'FirebaseAuthInterop' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'Flutter' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'GoogleAppMeasurement' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'Firebase' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'FirebaseAnalytics' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'BoringSSL-GRPC' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'leveldb-library' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'path_provider' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'abseil' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'GoogleUtilities' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'GoogleDataTransport' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'gRPC-Core' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'FirebaseCoreDiagnostics' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'gRPC-C++' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'FirebaseInstallations' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'FirebaseFirestore' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'firebase_core' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'firebase_analytics' from project 'Pods')
                        warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
deployment target
                        versions is 9.0 to 14.0.99. (in target 'cloud_firestore' from project 'Pods')
                    
[+10052 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 11.
[   +4 ms] "flutter run" took 125.489ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[  +94 ms] ensureAnalyticsSent: 89ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[        ] exiting with code 1`
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
alhoussen@ alhoussen s-Mac-mini cross-word % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale de-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (not installed)
 
[✓] Connected device (1 available)            

! Doctor found issues in 2 categories.`
```

</details>

**Comment by TahaTesser** [comment]
Hi @mahbobyosf
Did you modify the target in Xcode? Does this reproduce in a new project with the default code sample? 

Can you please provide your `flutter run --verbose` (copy complete logs in plain text file .txt` and paste in the comments below)  and a complete reproducible minimal code sample
Thank you

**Comment by mahbobyosf** [comment]
There are no problems with new projects

But with my current project I deleted the pods and the podfile.lock and tried to restart the app and now I have this problem:

 `ld: library not found for -lBoringSSL-GRPC`

[logs.txt](https://github.com/flutter/flutter/files/5348894/logs.txt)

**Comment by mahbobyosf** [comment]
I have found the solution to this problem by deleting all FrameWorks in "Other Linker Flags" except this
$(inherited)
-framwork
Flutter

![Bildschirmfoto 2020-10-08 um 17 35 48](https://user-images.githubusercontent.com/20616392/95481727-99c81f00-098d-11eb-9919-f72f3863cbac.png)
