### ISSUE TITLE
Hot Reload stop working after some refresh

### ISSUE THREAD

**Issue by apoleo88** [flutter/flutter#67635]
This happens in Debug and Run mode.
At first it seems to work fine but in 2-3 hot reload (where there are some changes) it doesn't respond anymore loading indefinitely , so I am forced to stop and run again.

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.222, on Microsoft Windows [Versione 10.0.19041.508], locale it-IT)
    • Flutter version 1.23.0-8.0.pre.222 at C:\src\flutter
    • Framework revision d2858f00dd (6 hours ago), 2020-10-08 09:39:13 +0200
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Apoleo88\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\Apoleo88\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\193.6821437\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Apoleo88\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\193.6821437
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

```
<img width="158" alt="Immagine 2020-10-08 160854" src="https://user-images.githubusercontent.com/7873856/95470072-a3975580-0980-11eb-9485-63a4aca76570.png">

**Comment by bernaferrari** [comment]
I can't hot reload or hot restart in this project:
https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login
Just download, open, change something like "sign up" and try to hot restart.

**Comment by darshankawar** [comment]
@apoleo88 
Tried a sample code on Android 8.1.0 device using latest master version and was able to hot reload and hot restart every time. Tried 6 to 7 times.

<img width="687" alt="Screenshot 2020-10-09 at 1 45 28 PM" src="https://user-images.githubusercontent.com/67046386/95559722-d7808280-0a35-11eb-9dbb-bec8c4752e2e.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.221, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.23.0-8.0.pre.221 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 0d8d4f77aa (23 hours ago), 2020-10-08 09:26:30 +0200
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 x86_64
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.75

• No issues found!


```

</details>

```
RaisedButton(
              child: Text('now'),
              onPressed: () {}
```
Can you provide more details and any pattern to it which causes the issue at your end ?
Thanks.

**Comment by bernaferrari** [comment]
@darshankawar could you try the one I sent on Flutter Web? Just change "sign out" to "sign outt" and it should trigger the issue.

**Comment by apoleo88** [comment]
I can't give you a sample, but after I downgraded flutter, switching to beta channel, the hot reload is working fine.

**Comment by darshankawar** [comment]
@bernaferrari 
Tried `Flutter_timer` from bloc examples link you shared on web using latest master. Was able to restart, reload everytime I made minor changes.

```
For a more detailed help message, press "h". To quit, press "q".

Performing hot restart...                                          219ms
Restarted application in 220ms.

Performing hot restart...                                           69ms
Restarted application in 69ms.

Performing hot restart...                                           90ms
Restarted application in 91ms.

Performing hot restart...                                           62ms
Restarted application in 63ms.


Performing hot restart...                                           62ms
Restarted application in 63ms.

Performing hot restart...                                           77ms
Restarted application in 77ms.

Performing hot restart...                                           79ms
Restarted application in 79ms.

Performing hot restart...                                          174ms
Restarted application in 174ms.

Performing hot restart...                                           66ms
Restarted application in 66ms.


```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.221, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.23.0-8.0.pre.221 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 0d8d4f77aa (4 days ago), 2020-10-08 09:26:30 +0200
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios            • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 x86_64
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 86.0.4240.75

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@apoleo88 
If possible, please provide video of the issue you are facing along with `flutter run --verbose`.
thanks.

**Comment by fourman-alex** [comment]
Adding reproducable steps. 
This might be a different issue but I think there is an underlying common problem. The issue I'm seeing has to do with hot reload during debug when breakpoints are present and changes are introduced in between hot reloads.
This happens with DevTools debugger/Android Studio/Visual Code
Happens **only on web**

<details>
  <summary>Reproducable code</summary>
  
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
      print('hello');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

1. Run `flutter run`
2. Connect a debugger
3. Add two breakpoints. at line 35 `_counter++;` and at line 36 `print('hello');`
4. Hot reload
5. Add new line between lines 35 and 36
6. Hot reload

### Expected:
Everything sould work

### Actual: 
<details>
  <summary>Exception stacktrace</summary>
  
```
Error from backend:

Error: addBreakpoint: (102) The VM is unable to add a breakpoint at the
specified line or function

Stack Trace:
#0      _Breakpoints.add (package:dwds/src/debugging/debugger.dart:702:7)
<asynchronous suspension>
#1      Debugger.addBreakpoint (package:dwds/src/debugging/debugger.dart:273:43)
#2      Debugger.reestablishBreakpoints
(package:dwds/src/debugging/debugger.dart:304:13)
<asynchronous suspension>
#3      ChromeProxyService.createIsolate
(package:dwds/src/services/chrome_proxy_service.dart:183:10)
<asynchronous suspension>
#4      DevHandler._handleIsolateStart
(package:dwds/src/handlers/dev_handler.dart:410:11)
#5      DevHandler._handleConnection.<anonymous closure>
(package:dwds/src/handlers/dev_handler.dart:272:19)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _BufferingStreamSubscription._sendData
(dart:async/stream_impl.dart:357:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#12     _PendingEvents.schedule.<anonymous closure>
(dart:async/stream_impl.dart:687:7)
#13     _rootRun (dart:async/zone.dart:1182:47)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1037:23)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
```
</details>

<details>
  <summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.23.0-18.1.pre at /home/alex/dev/flutter
    • Framework revision 198df796aa (2 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/alex/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /home/alex/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/alex/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /home/alex/idea-IC-201.7223.91
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.99

[✓] VS Code (version 1.50.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.75

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by bernaferrari** [comment]
https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login
Just download, open, change something like "sign up" and try to hot restart.

This still affects me, hot reload and hot restart are completely broken.

**Comment by apoleo88** [comment]
The bug persists to me too, unfortunately, I don't know how to make you reproduce it. 
I guess is related somehow with firebase or play-services-* libraries.

Let me know if and how I can report a more detailed debug log.

**Comment by apoleo88** [comment]
I found out that creating a new Device will fix the problem for a little while, but it will present again sooner or later.

**Comment by yuensunn** [comment]
> The bug persists to me too, unfortunately, I don't know how to make you reproduce it.
> If I have to guess, I would say it is related with `firebase` or `play-services-*` libraries.
> 
> To be more clear the reload hang indefinitely here:
> 
> ```
> Performing hot reload...
> Syncing files to device sdk gphone x86 arm...
> ```
> 
> Let me know if and how I can report a more detailed debug log.

I second this. Hot reload was working fine before firebase was integrated.

**Comment by ashish141199** [comment]
Same issue with me. Can someone from the team please guide on this!
