### ISSUE TITLE
cocoon build fails in recipe led runs, but succeeded in cocoon pre-submit runs

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#67659]
From the recipe led side, hit below error in `app_flutter` tests, which succeeded in cocoon repo pre-submit builds.

```
00:23 +159 -1: /b/s/w/ir/x/w/cocoon/app_flutter/test/build_dashboard_page_test.dart: TaskGridContainer with default Settings property sheet                                                            
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: one widget whose rasterized image matches golden image
"goldens/build_dashboard.defaultPropertySheet.png"
  Actual: _WidgetTypeFinder:<exactly one widget with type "BuildDashboardPage" (ignoring offstage
widgets): BuildDashboardPage(dependencies: [_LocalizationsScope-[GlobalKey#63142],
_InheritedProviderScope<BuildState>, _InheritedTheme], state: BuildDashboardPageState#953e4)>
   Which: Golden "goldens/build_dashboard.defaultPropertySheet.png": Pixel test failed, 40.03% diff
detected.
          Failure feedback can be found at /b/s/w/ir/x/w/cocoon/app_flutter/test/failures

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:155:31)
#1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:130:9)
#13     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
<asynchronous suspension>
#14     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
#15     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:1003:22)
#18     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:1001:26)
#19     MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#20     _expect (package:test_api/src/frontend/expect.dart:119:26)
#21     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#22     expectLater (package:flutter_test/src/widget_tester.dart:468:10)
#23     expectGoldenMatches (file:///b/s/w/ir/x/w/cocoon/app_flutter/test/utils/golden.dart:20:10)
#24     main.<anonymous closure> (file:///b/s/w/ir/x/w/cocoon/app_flutter/test/build_dashboard_page_test.dart:303:11)
#35     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:193:32)
#36     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1192:19)
(elided 35 frames from dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  TaskGridContainer with default Settings property sheet
```

**Comment by keyonghan** [comment]
Per discussion with @CaseyHillers this may be due to `led` is relying on flutter `beta`, whereas cocoon repo pre-submit builds are based on `dev`.

**Comment by keyonghan** [comment]
@godofredoc marked as p1, since this is blocking the recipe cl merge.

**Comment by godofredoc** [comment]
Can you please add links to builder?

**Comment by keyonghan** [comment]
Here is the test: https://ci.chromium.org/p/flutter/builders/try/recipes-with-led/b8866991503071606064?

**Comment by godofredoc** [comment]
I don't think there is a way around it,  the led tests use the last passing builder for cocoon whit was commit ```d408d302e22179d598f467e11da5dd968dbdc9ec```.  What I think is that cocoon is already broken the new version of flutter and needs to get fixed for those tests to pass.
