### ISSUE TITLE
cocoon build_dashboard_page_test is flaky

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#67681]
Below two builds are based on the same version of flutter and cocoon, but one succeeded whereas the other failed.
https://ci.chromium.org/p/flutter/builders/try/Cocoon/1368
https://ci.chromium.org/p/flutter/builders/try/Cocoon/1365

Failed log:
```
00:23 +160 -1: /b/s/w/ir/k/cocoon/app_flutter/test/build_dashboard_page_test.dart: TaskGridContainer with default Settings property sheet                                                              
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: one widget whose rasterized image matches golden image
"goldens/build_dashboard.defaultPropertySheet.png"
  Actual: _WidgetTypeFinder:<exactly one widget with type "BuildDashboardPage" (ignoring offstage
widgets): BuildDashboardPage(dependencies: [_LocalizationsScope-[GlobalKey#a9590],
_InheritedProviderScope<BuildState>, _InheritedTheme], state: BuildDashboardPageState#833ca)>
   Which: Golden "goldens/build_dashboard.defaultPropertySheet.png": Pixel test failed, 40.03% diff
detected.
          Failure feedback can be found at /b/s/w/ir/k/cocoon/app_flutter/test/failures

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:155:31)
#1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:130:9)
#13     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
<asynchronous suspension>
#14     MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart)
#15     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:1003:22)
#18     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:1001:26)
#19     MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#20     _expect (package:test_api/src/frontend/expect.dart:119:26)
#21     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#22     expectLater (package:flutter_test/src/widget_tester.dart:468:10)
#23     expectGoldenMatches (file:///b/s/w/ir/k/cocoon/app_flutter/test/utils/golden.dart:20:10)
#24     main.<anonymous closure> (file:///b/s/w/ir/k/cocoon/app_flutter/test/build_dashboard_page_test.dart:303:11)
#35     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:193:32)
#36     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1192:19)
(elided 35 frames from dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  TaskGridContainer with default Settings property sheet
```

**Comment by CaseyHillers** [comment]
I can't reproduce this. Looking at the linked consoles, the git ref changed. I assume this was with a `git fetch upstream && git rebase upstream/master`. Duplicating as part of https://github.com/flutter/flutter/issues/68668
