### ISSUE TITLE
GeneratedPluginRegistrant.java:14: error: annotations are not supported in -source 1.3

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#67704]
Hello,

My build started to fail with the following error message, please help!
I am using Windows 10 and a Kotlin based Flutter app, my Kotlin version is the latest, 1.4

```
[+168746 ms] Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
[   +2 ms] Note: Recompile with -Xlint:deprecation for details.
[+7163 ms] Note: Some input files use unchecked or unsafe operations.
[        ] Note: Recompile with -Xlint:unchecked for details.
[+14500 ms] warning: [options] source value 1.3 is obsolete and will be removed in a future release
[   +1 ms] warning: [options] target value 1.3 is obsolete and will be removed in a future release
[        ] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
[ +403 ms] C:\Users\....\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:14: error: annotations are not supported in -source 1.3
```

Possibly an issue with Kotlin? https://stackoverflow.com/questions/52567791/use-annotation-processor-in-kotlin

line 14 in GeneratedPluginRegistrant.java is a simple "@ Keep" comment

```
...
/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
```
Stack trace:
```

[ +404 ms] C:\Users\...\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:14: error: annotations are not supported in -source 1.4
[        ] @Keep
[        ]  ^
[        ]   (use -source 5 or higher to enable annotations)
[        ] 1 error
[        ] 3 warnings
[+2190 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 7m 32s
[{"event":"app.progress","params":{"appId":"3666dfa9-c5cf-470c-9c7d-80336f6b445a","id":"0","progressId":null,"finished":true}}]
[+3066 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:474:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by giorgio79** [comment]
And the solution https://stackoverflow.com/questions/56621169/android-error-annotations-are-not-supported-in-source-1-3

**Comment by darshankawar** [comment]
@giorgio79 Glad to know you found the solution.
Does that mean your issue is resolved ? Can this be closed ?
Thanks.

**Comment by giorgio79** [comment]
Yes :)
