### ISSUE TITLE
Flutter doctor --android-licenses : Error 

### ISSUE THREAD

**Issue by csyahya** [flutter/flutter#67720]
**When I run "flutter doctor --android-licenses" to accept license the following error appears :
C:\WINDOWS\system32>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more**

**Comment by csyahya** [comment]
**Guys I will leave the problem but I have found the solution (To Make People get benefit ) :-** 
![Solution](https://user-images.githubusercontent.com/50404142/95572193-465bdc80-0a32-11eb-827c-c25592271a92.png)

**I have attached picture that indicates the Solution.**
