### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument (URI scheme not allowed): "file:///E:/code/androidstudio/flutter_app_2/lib/abandoned/online_videos.dart"

### ISSUE THREAD

**Issue by kuro7766** [flutter/flutter#67731]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument (URI scheme not allowed): "file:///E:/code/androidstudio/flutter_app_2/lib/abandoned/online_videos.dart"
```
#0      DartUri._recordAbsoluteUri (package:dwds/src/utilities/dart_uri.dart:86:7)
#1      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:60:9)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:88:19)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:171:37)
<asynchronous suspension>
#5      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:138:23)
#6      DebugService.start (package:dwds/src/services/debug_service.dart:142:55)
#7      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:184:25)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel beta, 1.22.0-12.3.pre, on Microsoft Windows [Version 10.0.18363.1082], locale zh-CN)
    • Flutter version 1.22.0-12.3.pre at D:\flutter
    • Framework revision d408d302e2 (10 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:/androidSDK
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:/androidSDK
    • ANDROID_SDK_ROOT = C:\Users\1\.android
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 85.0.564.70

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6
### Plugins
advance_pdf_viewer-1.2.0
device_info-0.4.2+7
flutter_full_pdf_viewer-1.0.6
flutter_pdfview-1.0.3+3
fluttertoast-7.0.4
package_info-0.4.3
path_provider-1.6.14
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
pdf_render-0.66.2
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1+1
url_launcher-5.5.2
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.3+1
video_player-0.10.12+2
video_player_web-0.1.3+2
webview_flutter-0.3.22+1

**Comment by TahaTesser** [comment]
Hi @kuro7766 
Based on the error, it looks like an issue in your code in `online_videos.dart` 
```
ArgumentError: Invalid argument (URI scheme not allowed): "file:///E:/code/androidstudio/flutter_app_2/lib/abandoned/online_videos.dart"
```

Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by kuro7766** [comment]
I searched in my project , cleared all imports related to online_videos.dart , then run pub get again and it works.

Before this , here is one line of code in my source code 
> import 'file:///E:/code/androidstudio/flutter_app_2/lib/abandoned/online_videos.dart';

But my project directory is `E:\code\flutter\flutter_app_2`

This is a project I copied directly in file expolorer , it seems some files are still referencing my previous project.
