### ISSUE TITLE
USB tethered iOS devices sometimes not found with `flutter drive`

### ISSUE THREAD

**Issue by liyuqian** [flutter/flutter#67753]
This has caused flakiness of `flutter_gallery_sksl_warmup__transition_perf_e2e_ios32` test with the following error logs. There was a similar issue https://github.com/flutter/flutter/issues/53182 that was fixed by extending the timeout, so a similar extension might be needed for `flutter drive`.
```
2020-10-09T07:51:35.926885: stdout: [  +55 ms] No devices found with name or id matching '822ef7958bba573829d85eef4df6cbdd86593730'
2020-10-09T07:51:35.938448: stdout: [  +11 ms] "flutter drive" took 3,591ms.
2020-10-09T07:51:35.944294: stderr: [   +4 ms] 
stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
stderr:            #1      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:174:7)
stderr:            <asynchronous suspension>
stderr:            #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1001:18)
stderr:            <asynchronous suspension>
stderr:            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:860:33)
stderr:            <asynchronous suspension>
stderr:            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
stderr:            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
stderr:            #6      _rootRun (dart:async/zone.dart:1190:13)
stderr:            #7      _CustomZone.run (dart:async/zone.dart:1093:19)
stderr:            #8      _runZoned (dart:async/zone.dart:1630:10)
stderr:            #9      runZoned (dart:async/zone.dart:1550:10)
stderr:            #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
stderr:            #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:849:20)
stderr:            #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
stderr:            #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
...
```

For more details, please check https://flutter-dashboard.appspot.com/#/build?taskFilter=flutter_gallery_sksl_warmup__transition_perf_e2e_ios32 after commit https://github.com/flutter/flutter/commit/98d1ad01959cfc0e7351170c0b1a8d205ae729a4.

**Comment by liyuqian** [comment]
CC @jmagman

**Comment by jmagman** [comment]
Let's reopen this if we see again post-https://github.com/flutter/flutter/pull/69260
