### ISSUE TITLE
I can't build the default Flutter app/ Gradle task 'assembleDebug' is taking forever. 

### ISSUE THREAD

**Issue by Jebrano** [flutter/flutter#67774]
## Steps to Reproduce

1. I just downloaded Flutter and run it in VS code. I also run it in Android studio and the same problem occurs.
2. I typed the command Flutter run in the PowerShell inside VS code.

## Logs

This what it shows in the Powershell
```
 D:\Prog\once_flutter\once_flutter>flutter run
Launching lib\main.dart on SM A705FN in debug mode...
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\ASUS\AppData\Local\Android\sdk\licenses
License for package Android SDK Build-Tools 28.0.3 accepted.
Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
Running Gradle task 'assembleDebug'...                                 -

```
and this is the output of Flutter doctor -v

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.257, on Microsoft Windows [Version 10.0.18363.1016], locale en-US)
    • Flutter version 1.23.0-8.0.pre.257 at D:\Flutter\flutter
    • Framework revision 8d80592d46 (7 hours ago), 2020-10-09 16:33:39 +0200
    • Engine revision 349889833c
    • Dart version 2.11.0 (build 2.11.0-203.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • SM A705FN (mobile) • R58M568NWYK • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by yankai-victor** [comment]
I had the same problem.
Try to change the value "distributionUrl=https\://downloads.gradle-dn.com/distributions/gradle-6.1.1-all.zip" in your_project_path/android/gradle/wrapper/gradle-wrapper.properties and build again.

**Comment by Jebrano** [comment]
I changed the gradle-wrapper.properties and run it again. still getting the same message 
```(This is taking an unexpectedly long time.)```

**Comment by yankai-victor** [comment]
Download gradle-6.1.1-all-zip from "https://downloads.gradle-dn.com/distributions/gradle-6.1.1-all.zip" and put it in your_path/.gradle/wrapper/dists/gradle-6.1.1-all/3imyvenb724qye48jp5w94wo4.

**Comment by TahaTesser** [comment]
Hi @Jebrano 
Please try `classpath 'com.android.tools.build:gradle:3.5.0` and delete your existing cache gradle cache and run again
If the problem persists,  Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Jebrano** [comment]
how can I delete everything related to Gradle and start again?
and also I'm very new to Flutter so where is I can find ```classpath 'com.android.tools.build:gradle:3.5.0``` ?

**Comment by TahaTesser** [comment]
Hi @Jebrano 
```
[  +32 ms] "flutter run" took 288ms.
[  +16 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
```
1. Please execute `flutter run --verbose` from the root of your project in the terminal  and paste complete logshere 
2. VS Code shouldn't throw error there but can you please new project  and try again

**Comment by Jebrano** [comment]
Hey @TahaTesser.
I have created a new project and run ```flutter run --verbose``` here is my output
```
[ +101 ms] executing: [D:\Flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8d80592d46db57628ed71e2727b86427a944595b
[        ] executing: [D:\Flutter\flutter/] git tag --points-at HEAD
[  +47 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] executing: [D:\Flutter\flutter/] git describe --match *.*.* --first-parent --long --tags
[  +59 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.23.0-13.0.pre-82-g8d80592d46
[   +9 ms] executing: [D:\Flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\Flutter\flutter/] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +58 ms] executing: [D:\Flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +48 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update. 
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +69 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +29 ms] List of devices attached
           R58M568NWYK            device product:a70qxx model:SM_A705FN device:a70q transport_id:2
[   +8 ms] C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s R58M568NWYK shell getprop
[ +109 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +229 ms] Generating D:\Prog\hello_flutter\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +23 ms] ro.hardware = qcom
[  +53 ms] Starting incremental build...
[   +4 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[  +19 ms] complete
[  +18 ms] Launching lib\main.dart on SM A705FN in debug mode...
[   +5 ms] D:\Flutter\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\Flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata  
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\ASUS\AppData\Local\Temp\flutter_tools.ebdcfe7b\flutter_tool.27b38c03\app.dill --packages .packages  
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts 
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\01094840f26094a3fe371d8be6b9cb48.cache.dill.track.dill
--flutter-widget-cache
[  +67 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe -s R58M568NWYK shell -x logcat -v time -t 1
[  +45 ms] <- compile package:hello_flutter/main.dart
[ +180 ms] --------- beginning of main
                    10-15 03:25:20.978 D/ISG_Wakeup_Verify_Algo(20083): kwd_score: 0.2088, kwd_score-OOV: 0.2088, flag(0), peakCount(0), TimeElapsed(201855)
[  +31 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +79 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\ASUS\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +67 ms] Building APK
[  +18 ms] Running Gradle task 'assembleDebug'...
[  +27 ms] gradle.properties already sets `android.enableR8`
[  +36 ms] Using gradle from D:\Prog\hello_flutter\android\gradlew.bat.
[  +21 ms] D:\Prog\hello_flutter\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +15 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +122 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +28 ms] executing: [D:\Prog\hello_flutter\android/] D:\Prog\hello_flutter\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=D:\Prog\hello_flutter\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+7339 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[  +63 ms] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[   +2 ms] > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
[   +5 ms]    > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[  +91 ms]      Required by:
[        ]          project :app
[        ]       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/flutter_embedding_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +2 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/flutter_embedding_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +9 ms]       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[  +62 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/flutter_embedding_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[  +64 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/flutter_embedding_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[  +26 ms]       > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[   +2 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/flutter_embedding_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +2 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/flutter_embedding_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[  +34 ms]    > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[  +32 ms]      Required by:
[   +1 ms]          project :app
[  +26 ms]       > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/arm64_v8a_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +2 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/arm64_v8a_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +1 ms]       > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[        ]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/arm64_v8a_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[  +29 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/arm64_v8a_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +4 ms]       > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[  +26 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/arm64_v8a_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +3 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/arm64_v8a_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +2 ms]    > Could not resolve io.flutter:x86_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[  +42 ms]      Required by:
[   +7 ms]          project :app
[   +3 ms]       > Could not resolve io.flutter:x86_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[  +50 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +2 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +1 ms]       > Could not resolve io.flutter:x86_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +1 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +1 ms]       > Could not resolve io.flutter:x86_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +1 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +1 ms]    > Could not resolve io.flutter:x86_64_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[        ]      Required by:
[  +24 ms]          project :app
[   +3 ms]       > Could not resolve io.flutter:x86_64_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[   +1 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_64_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +1 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_64_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +1 ms]       > Could not resolve io.flutter:x86_64_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[        ]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_64_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +1 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_64_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[  +21 ms]       > Could not resolve io.flutter:x86_64_debug:1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.
[   +3 ms]          > Could not get resource
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_64_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'.
[   +1 ms]             > Could not GET
'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-349889833c6f66586d775b7d0978a870b48ebd57/x86_64_debug-1.0.0-349889833c6f66586d775b7d0978a870b48ebd57.pom'. Received status code 403 from server: Forbidden
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.      
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 7s
[ +296 ms] Running Gradle task 'assembleDebug'... (completed in 8.5s)
[   +4 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +19 ms] "flutter run" took 9,725ms.
[  +23 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:618:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1001:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +278 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +22 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1```

**Comment by TahaTesser** [comment]
Hi @Jebrano 
You getting ` Received status code 403 from server: Forbidden`
Are you using any private network or VPN?  Are you on a stable connection?

**Comment by Jebrano** [comment]
That was it. I feel bad for not reading all the logs, I just had to turn on VPN bc I'm in a restricted country.
Thanks Very much @TahaTesser .
