### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/user/Library/Android/sdk/build-tools/30.0.2/aapt.

### ISSUE THREAD

**Issue by naseema** [flutter/flutter#67844]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=99171FFAZ009GK --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/user/Library/Android/sdk/build-tools/30.0.2/aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:92:30)
#2      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:481:37)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:380:14)
#4      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:481:12)
#5      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:425:51)
#6      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:530:56)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:339:31)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#19     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart)
#20     _rootRunUnary (dart:async/zone.dart:1198:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.22.0 at /Users/user/flutter
    • Framework revision d408d302e2 (11 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    ✗ Android SDK file not found: /Users/user/Library/Android/sdk/build-tools/30.0.2/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.1 RC)
    • IntelliJ at /Users/user/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel 4 (mobile)                    • 99171FFAZ009GK                       • android-arm64 • Android 11 (API 30)
    • iPhone SE (2nd generation) (mobile) • 1E70E484-184F-48BF-9A07-16EC832E4CF5 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 6 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: dd88b20435c1eb9b837bb4aa8b0a84aa0825530d
### Plugins
barcode_scan-3.0.1

**Comment by hamdikahloun** [comment]
Hi @naseema 
There's similar [open](https://github.com/flutter/flutter/issues/67818)  issue in which you can follow-up for updates and any questions.
Thank you

**Comment by pedromassangocode** [comment]
Hi @naseema 
I see there's an open issue (https://github.com/flutter/flutter/issues/54418) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
