### ISSUE TITLE
[Beta] FocusScope.of(context).nextFocus() not working correctly

### ISSUE THREAD

**Issue by Rayv1** [flutter/flutter#67867]
Hi,

for me it seems the FocusScope.of(context).nextFocus() is not working correctly.

Code to reproduce:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
            // visualDensity: VisualDensity.adaptivePlatformDensity,
            ),
        home: MyHomePage());
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          TextField(
            decoration: InputDecoration(hintText: "TextField A"),
            textInputAction: TextInputAction.next,
            onSubmitted: (_) =>
                FocusScope.of(context).nextFocus(), // move focus to next
          ),
          TextField(
            decoration: InputDecoration(hintText: "TextField B"),
            textInputAction: TextInputAction.next,
            onSubmitted: (_) =>
                FocusScope.of(context).nextFocus(), // move focus to next
          ),
          TextField(
            decoration: InputDecoration(hintText: "TextField C"),
            textInputAction: TextInputAction.done,
            onSubmitted: (_) =>
                FocusScope.of(context).unfocus(), // submit and hide keyboard
          ),
        ],
      ),
    );
  }
}
```
Expected behaviour: When submitting Textfield A, focus TextField B
What happened: After submitting TextField A, focus on TextField C (TextField B is fully ignored)

Its working when i remove MyHomePage Widget and put all in the MyApp Widget
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
            // visualDensity: VisualDensity.adaptivePlatformDensity,
            ),
        home: Scaffold(
          body: Column(
            children: <Widget>[
              TextField(
                decoration: InputDecoration(hintText: "TextField A"),
                textInputAction: TextInputAction.next,
                onSubmitted: (_) =>
                    FocusScope.of(context).nextFocus(), // move focus to next
              ),
              TextField(
                decoration: InputDecoration(hintText: "TextField B"),
                textInputAction: TextInputAction.next,
                onSubmitted: (_) =>
                    FocusScope.of(context).nextFocus(), // move focus to next
              ),
              TextField(
                decoration: InputDecoration(hintText: "TextField C"),
                textInputAction: TextInputAction.done,
                onSubmitted: (_) => FocusScope.of(context)
                    .unfocus(), // submit and hide keyboard
              ),
            ],
          ),
        ));
  }
}
```

```
Flutter doctor -v:
[√] Flutter (Channel beta, 1.22.1, on Microsoft Windows [Version 10.0.18362.1082], locale de-DE)
    • Flutter version 1.22.1 at Z:\workspace\flutter
    • Framework revision f30b7f4db9 (3 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Platform android-30, build-tools 29.0.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at Z:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
```

**Comment by xu-baolin** [comment]
@Rayv1 Hi, Thank you for reporting the issue, although this is not a bug.
The action `TextInputAction.next` means that `The user is done with the current input source and wants to move to the next one.`.
So when you click submit, the focus will automatically switch to the next one, and you don't need to request the next node in the `onSubmitted` callback, just remove it!

Additionally, why it working at the second sample code?
An exception was reported because the context does not in a `FocusScope`:
```dart
════════ Exception caught by widgets ═══════════════════════════════════════════════════════════════
The following _CastError was thrown while calling onSubmitted for TextInputAction.next:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      FocusNode.nextFocus (package:flutter/src/widgets/focus_manager.dart:1127:53)
#1      MyApp.build.<anonymous closure> (package:flutter_app_demo/main.dart:29:44)
#2      EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:1864:28)
#3      EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:1723:9)
#4      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1200:37)
```

**Comment by darshankawar** [comment]
@Rayv1 
Please see above detailed explanation and check if it answers your question and why it isn't working.

**Comment by Rayv1** [comment]
Thanks, yes TextInputAction.next without FocusScope.of(context).nextFocus() works like a charm.
