### ISSUE TITLE
ArgumentError: Invalid argument (URI scheme not allowed)

### ISSUE THREAD

**Issue by Yusufathi** [flutter/flutter#67877]
`Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --target lib\main.dart -d web-server --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url

## exception

ArgumentError: Invalid argument (URI scheme not allowed): "file:///E:/codes/flutter/yusufathi_cv/lib/consts/images_paths.dart"

```
#0      DartUri._recordAbsoluteUri (package:dwds/src/utilities/dart_uri.dart:86:7)
#1      DartUri.recordAbsoluteUris (package:dwds/src/utilities/dart_uri.dart:60:9)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:88:19)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:171:37)
<asynchronous suspension>
#5      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:138:23)
#6      DebugService.start (package:dwds/src/services/debug_service.dart:142:55)
#7      DevHandler._startExtensionDebugService.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:463:47)
#8      DevHandler._startExtensionDebugService.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:450:52)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#16     _rootRun (dart:async/zone.dart:1182:47)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.22.1, on Microsoft Windows [Version 10.0.17763.107], locale en-US)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (3 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\LastWarriorX\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\LastWarriorX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75

• No issues found!
```
`

**Comment by darshankawar** [comment]
@Yusufathi 
Please try below solutions and see if they work for you.

https://github.com/flutter/flutter/issues/59924#issuecomment-678287123

https://github.com/flutter/flutter/issues/64492#issuecomment-680100884

https://github.com/flutter/flutter/issues/66964#issuecomment-701297913

**Comment by Yusufathi** [comment]
@darshankawar
 so i did try to solve it with [this ](https://github.com/flutter/flutter/issues/59924#issuecomment-678287123)solution but it caused other error . i may got it wrong . i've done like so
 `const String kSiteLogoImagePath = 'package:res/logo/mylogo.png';` 
instead of 
`const String kSiteLogoImagePath = 'res/logo/mylogo.png';` 
 did i get it wrong ? . [this](https://github.com/flutter/flutter/issues/64492#issuecomment-680100884) one i didnt understand tbh .  i did try to reimport the packages and that did nothing . whats weird is it works fine with andrioid emulaters .

**Comment by darshankawar** [comment]
@Yusufathi 
Please provide a complete minimal reproducible code sample that shows the issue.

**Comment by Yusufathi** [comment]
@darshankawar  

i found some others soluions and applied them and it solved the issue of `URI scheme not allowed` and now im having this issue : 
```
Unhandled exception:
NoSuchMethodError: The getter 'scheme' was called on null.
Receiver: null
Tried calling: scheme
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      urlForComponentUri (package:frontend_server/src/javascript_bundle.dart:202:61)
#2      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:119:27)
<asynchronous suspension>
#3      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:659:20)
<asynchronous suspension>
#4      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:559:15)
<asynchronous suspension>
#5      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
#6      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1200:26)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#12     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#13     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#14     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#15     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#16     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#23     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#24     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#25     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#26     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#32     _StreamController._add (dart:async/stream_controller.dart:682:7)
#33     _StreamController.add (dart:async/stream_controller.dart:624:5)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#39     _StreamController._add (dart:async/stream_controller.dart:682:7)
#40     _StreamController.add (dart:async/stream_controller.dart:624:5)
#41     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#42     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.
```

**Comment by Yusufathi** [comment]
so both issues where solved . 

issue #1 solution :  created a new project . got all the files from the old one and put  them in the new one .
issue #2 solution :  `provider package` and `shared prefences` czused the app to not work so replaced them with 2 other packages and it went well .
