### ISSUE TITLE
[web]Unhandled error detected in the injected client.js script

### ISSUE THREAD

**Issue by nttd-baozhenwang** [flutter/flutter#67896]
**nothing update! i can run successfully last friday.however, this monday ,error has happened. 
how do i can resolve this problem?**

```
Unhandled error detected in the injected client.js script.

You can disable this script in webdev by passing --no-injected-client if it
is preventing your app from loading, but note that this will also prevent
all debugging and hot reload/restart functionality from working.

The original error is below, please file an issue at

https://github.com/dart-lang/webdev/issues/new and attach this output:
NoSuchMethodError: method not found: 'get$digestsPath' (J.getInterceptor$x(...).get$digestsPath is not a function)
TypeError: J.getInterceptor$x(...).get$digestsPath is not a function
    at Object.get$digestsPath$x (http://127.0.0.1:8080/dwds/src/injected/client.js:3495:43)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:22811:60
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:3757:20)
    at RequireRestarter._getDigests$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:22823:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:22838:48
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:3757:20)
    at RequireRestarter._initialize$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:22846:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:8578:45
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://127.0.0.1:8080/dwds/src/injected/client.js:3757:20)
    at Object.RequireRestarter_create (http://127.0.0.1:8080/dwds/src/injected/client.js:8590:16)
    at http://127.0.0.1:8080/dwds/src/injected/client.js:22398:38
    at _wrapJsFunctionForAsync_closure.$protected (http://127.0.0.1:8080/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:11010:12)
    at _awaitOnObject_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:10996:32)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:8080/dwds/src/injected/client.js:4118:18)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12315:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://127.0.0.1:8080/dwds/src/injected/client.js:11376:51)
    at Object._Future__propagateToListeners (http://127.0.0.1:8080/dwds/src/injected/client.js:3905:93)
    at _Future._complete$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:11200:11)
    at Object._cancelAndValue (http://127.0.0.1:8080/dwds/src/injected/client.js:4060:16)
    at Stream_first_closure0.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:11468:9)
    at _EventStreamSubscription_onData_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:17396:30)
    at StaticClosure._rootRunUnary [as call$2$5] (http://127.0.0.1:8080/dwds/src/injected/client.js:4124:16)
    at _CustomZone.runUnary$2$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12315:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://127.0.0.1:8080/dwds/src/injected/client.js:12247:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://127.0.0.1:8080/dwds/src/injected/client.js:12450:25)
    at invokeClosure (http://127.0.0.1:8080/dwds/src/injected/client.js:1204:26)
    at EventSource.<anonymous> (http://127.0.0.1:8080/dwds/src/injected/client.js:1223:18)
```

**Comment by Fox32** [comment]
Might be related to a chrome update: https://github.com/dart-lang/sdk/issues/43193#issuecomment-681010826

**Comment by nttd-baozhenwang** [comment]
@Fox32 
Thank you for recovering so quickly, it works now!
