### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'type' was called on null.Receiver: nullTried calling: type

### ISSUE THREAD

**Issue by Lanch92** [flutter/flutter#67894]
## Command
```
flutter build ios --analyze-size
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'type' was called on null.
Receiver: null
Tried calling: type
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:415:29)
#2      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:350:14)
#3      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:398:54)
#4      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:350:14)
#5      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#6      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:314:16)
#7      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:258:8)
#8      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:157:16)
#9      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#10     SizeAnalyzer.analyzeAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:57:59)
#11     BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:143:61)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20     buildXcodeProject (package:flutter_tools/src/ios/mac.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
```
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/monkey/Desktop/Flutter/SDK/flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/monkey/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 85F3A5E8-4639-4447-AF38-EAF4D75F2C0F • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0
      (simulator)
    ! Error: lacz is not connected. Xcode will continue when lacz is connected. (code -13)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
amap_core_fluttify-0.9.5
amap_location_fluttify-0.13.2
auto_orientation-1.0.6
core_location_fluttify-0.2.4
device_info-0.4.2+8
file_picker-1.13.3
flutter_custom_dialog-1.0.20
flutter_inappwebview-4.0.0+4
flutter_plugin_android_lifecycle-1.0.11
flutter_sound-4.0.6
fluwx-2.3.0
foundation_fluttify-0.8.12
gallery_saver-2.0.1
huawei_push-4.0.4+300
image_gallery_saver-1.6.0
image_picker-0.6.7+11
jpush_flutter-0.5.9
multi_image_picker-4.7.14
path_provider-1.6.18
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
permission_handler-5.0.1+1
r_scan-0.1.4+1
screen-0.0.5
shared_preferences-0.5.12
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+1
sign_in_with_apple-2.5.2
sqflite-1.3.1+1
tobias-1.7.1+1
url_launcher-5.7.2
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+1
video_player-0.10.12+5
video_player_web-0.1.4
video_thumbnail-0.2.2
wakelock-0.1.4+2
webview_flutter-0.3.24
FlutterXiaoMiPushPlugin
flutter_plugin
oppo_pushs_plugin
vivo_pushs_plugin

**Comment by pedromassangocode** [comment]
This seems a duplicate of https://github.com/flutter/flutter/issues/66962 however it does not contains the `--split-debug-info` and it happened after https://github.com/flutter/flutter/pull/66983 has landed and cherrypicked at https://github.com/flutter/flutter/pull/67552.

Cc @jonahwilliams

**Comment by jonahwilliams** [comment]
@Lanch92 do you have some example code that reproduces this crash? It looks another bug in `package:vm_snapshot_analysis`
