### ISSUE TITLE
Getting the following error when i run this command "flutter doctor --android-licenses" to accept this sdk licenses

### ISSUE THREAD

**Issue by Sabya-07** [flutter/flutter#67901]
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

**Comment by darshankawar** [comment]
@Sabya-07 
Please try [this](https://github.com/flutter/flutter/issues/66907#issuecomment-703184800) solution and see if it works for you.
Thanks.

**Comment by Arax20** [comment]
I have the same issue and I tried the suggested solution of setting a $JAVA_HOME variable but it has't worked:
```
[arax@device ~]λ where java
/usr/bin/java
/bin/java
/usr/lib/jvm/default/bin/java
[arax@device ~]λ JAVA_HOME=/usr/lib/jvm/java-14-openjdk/
[arax@device ~]λ flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

**Comment by M0Sharif** [comment]
I had Java-10.0.2 for work so I thought I was set
I kept getting the same error here so I downloaded jre-1.8 https://www.oracle.com/uk/java/technologies/javase/javase-jdk8-downloads.html

set the JAVA_HOME and PATH to the jre

this worked for me 🤷‍♂️ new to java so I have no idea what I'm doing
