### ISSUE TITLE
[flutter_tools] doctor can't find Intellij 2020 plugin after upgrading flutter on channel master

### ISSUE THREAD

**Issue by wverdese** [flutter/flutter#67918]
**What steps will reproduce the issue?**
1. install and use IDEA Community 2020.2, with Flutter and Dart plugins up to date
2. install flutter and set it to channel `stable` 
3. verify that `$ flutter doctor -v` shows no issue
3. switch to `$ flutter channel master`
4. `$ flutter upgrade`
5. `$ flutter doctor -v`

**What is the expected result?**
flutter doctor shows no issue

**What happens instead?**
flutter doctor reports that the flutter plugins cannot be found.

```
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FileSystemException: Cannot open file, path = '/Users/walt/Library/Application
      Support/JetBrains/IdeaIC2020.2/plugins/flutter-intellij/lib/flutter-intellij.jar' (OS Error: No such file or directory, errno = 2)
    • #0      _File.throwIfError (dart:io/file_impl.dart:635:7)
      #1      _File.openSync (dart:io/file_impl.dart:479:5)
      #2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
      #3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:89:43)
      #4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:89:43)
      #5      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:78:62)
      #6      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:45:34)
      #7      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:78:15)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1190:13)
      #10     _CustomZone.run (dart:async/zone.dart:1093:19)
      #11     _runZoned (dart:async/zone.dart:1630:10)
      #12     runZonedGuarded (dart:async/zone.dart:1618:12)
      #13     runZoned (dart:async/zone.dart:1547:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:202:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:54:47)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1001:18)
      #19     _rootRunUnary (dart:async/zone.dart:1198:47)
      #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
      #23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #24     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #25     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
      #26     _rootRun (dart:async/zone.dart:1190:13)
      #27     _CustomZone.run (dart:async/zone.dart:1093:19)
      #28     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
      #30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Additional notes**
It seems flutter is looking for a file named `flutter-intellij.jar`. However, in the specified path, the file is named `flutter-intellij-50.0.jar`, so that might explain the issue.

I have used `channel master` until last Friday and everything was working. I've upgraded flutter this morning and this happened. Must have been a recent change.

**Comment by pedromassangocode** [comment]
Yes, I just ran into this same issue few minutes ago. It is happing on the latest `master` channel.

It is reproducible by just running `flutter doctor -v` in Terminal.

<details><summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.284, on Mac OS X 10.15.7 19H2 x86_64,
    locale en)
    • Flutter version 1.23.0-8.0.pre.284 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision eefcff900c (2 days ago), 2020-10-10 23:42:02 +0200
    • Engine revision 11d756a62e
    • Dart version 2.11.0 (build 2.11.0-207.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is
      not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ FileSystemException: Cannot open file, path =
      '/Users/pedromassango/Library/Application
      Support/JetBrains/IdeaIC2020.2/plugins/flutter-intellij/lib/flutter-intellij.jar'
      (OS Error: No such file or directory, errno = 2)
    • #0      _File.throwIfError (dart:io/file_impl.dart:635:7)
      #1      _File.openSync (dart:io/file_impl.dart:479:5)
      #2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
      #3      ForwardingFile.readAsBytesSync
      (package:file/src/forwarding/forwarding_file.dart:89:43)
      #4      ForwardingFile.readAsBytesSync
      (package:file/src/forwarding/forwarding_file.dart:89:43)
      #5      IntelliJPlugins._readPackageVersion
      (package:flutter_tools/src/intellij/intellij.dart:78:62)
      #6      IntelliJPlugins.validatePackage
      (package:flutter_tools/src/intellij/intellij.dart:45:34)
      #7      IntelliJValidator.validate
      (package:flutter_tools/src/intellij/intellij_validator.dart:78:15)
      #8      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1190:13)
      #10     _CustomZone.run (dart:async/zone.dart:1093:19)
      #11     _runZoned (dart:async/zone.dart:1630:10)
      #12     runZonedGuarded (dart:async/zone.dart:1618:12)
      #13     runZoned (dart:async/zone.dart:1547:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:202:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #17     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:54:47)
      #18     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:1001:18)
      #19     _rootRunUnary (dart:async/zone.dart:1198:47)
      #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #22     Future._propagateToListeners.handleValueCallback
      (dart:async/future_impl.dart:696:45)
      #23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #24     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #25     Future._asyncCompleteWithValue.<anonymous closure>
      (dart:async/future_impl.dart:567:7)
      #26     _rootRun (dart:async/zone.dart:1190:13)
      #27     _CustomZone.run (dart:async/zone.dart:1093:19)
      #28     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #29     _CustomZone.bindCallbackGuarded.<anonymous closure>
      (dart:async/zone.dart:1037:23)
      #30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #32     _runPendingImmediateCallback
      (dart:isolate-patch/isolate_patch.dart:118:13)
      #33     _RawReceivePortImpl._handleMessage
      (dart:isolate-patch/isolate_patch.dart:169:5)


[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X
      10.15.7 19H2 x86_64
    • Web Server (web)                   • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                       • chrome        • web-javascript • Google
      Chrome 85.0.4183.121

! Doctor found issues in 1 category.

```
</details>
