### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:Stderr:warning [/Users/muhammadelsayed/Documents/PRO/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/11d756a62ed0ddf87a9ce20b219b55300ec6b67d/flutter_patched_sdk.zip]:  5676885 extra bytes at beginning or within zipfile  (attempting to process anyway)file #1:  bad zipfile offset (local header sig):  5676885  (attempting to re-compensate)file #1:  bad zipfile offset (local header sig):  5676885file #2:  bad zipfile offset (local header sig):  78  (attempting to re-compensate)file #2:  bad zipfile offset (local header sig):  78file #3:  bad zipfile offset (local header sig):  6226837file #4:  bad zipfile offset (local header sig):  8909885 Command: unzip, OS error code: 2

### ISSUE THREAD

**Issue by xSuperMu** [flutter/flutter#67911]
## Command
```
flutter --no-color --no-version-check precache
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed
Stdout:

Stderr:
warning [/Users/muhammadelsayed/Documents/PRO/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/11d756a62ed0ddf87a9ce20b219b55300ec6b67d/flutter_patched_sdk.zip]:  5676885 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  5676885
  (attempting to re-compensate)
file #1:  bad zipfile offset (local header sig):  5676885
file #2:  bad zipfile offset (local header sig):  78
  (attempting to re-compensate)
file #2:  bad zipfile offset (local header sig):  78
file #3:  bad zipfile offset (local header sig):  6226837
file #4:  bad zipfile offset (local header sig):  8909885
 Command: unzip, OS error code: 2
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:463:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:211:21)
#3      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1638:18)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     ArtifactUpdater._download (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._complete (dart:async/future_impl.dart:519:7)
#19     Stream.forEach.<anonymous closure> (dart:async/stream.dart:945:14)
#20     _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:446:15)
#21     _rootRun (dart:async/zone.dart:1182:47)
#22     _CustomZone.run (dart:async/zone.dart:1093:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#24     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
```
```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.286, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
    • Flutter version 1.23.0-8.0.pre.286 at /Users/muhammadelsayed/Documents/PRO/flutter
    • Framework revision 8211aaa2ae (2 hours ago), 2020-10-12 17:25:38 +0800
    • Engine revision 11d756a62e
    • Dart version 2.11.0 (build 2.11.0-207.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/muhammadelsayed/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPad Air (3rd generation) (mobile) • DA149215-9553-4C5B-B99E-F047C3A5F447 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by pedromassangocode** [comment]
Hi @xSuperMu 
I see there's an open issue (https://github.com/flutter/flutter/issues/67512) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
