### ISSUE TITLE
[tool_crash] StateError: Bad state: The client closed with pending request "streamListen".

### ISSUE THREAD

**Issue by Angelos98** [flutter/flutter#67945]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=e67e34e9f8a7f9cb49a975c88b4754fed2685a39 lib/main.dart
```

## Steps to Reproduce
1. Install TestFlight App of your App on your Device
2. Connect your App again with Android Studio and Run your App on Debug Mode
3. App Crashes

## Logs
StateError: Bad state: The client closed with pending request "streamListen".
```
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _rootRun (dart:async/zone.dart:1182:47)
#2      _CustomZone.run (dart:async/zone.dart:1093:19)
#3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
#4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
#5      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
#6      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale de-DE)
    • Flutter version 1.23.0-7.0.pre at /Users/angelos/Developer/flutter
    • Framework revision db6e2d8aa5 (2 weeks ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/angelos/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Angelos iPhone (mobile) • e67e34e9f8a7f9cb49a975c88b4754fed2685a39 • ios • iOS 14.0.1
    • iPhone 11 (mobile)      • F870862B-98F3-47C8-9E16-0A2BEB0DEA68     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    ! Error: Angelos iPhone is busy: Copying cache files from device. Xcode will continue when Angelos iPhone is finished. (code -10)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f
### Plugins
flutter_custom_dialog-1.0.20
spear_menu-0.0.2
sqflite-1.3.1

**Comment by darshankawar** [comment]
@Angelos98 
A similar issue was fixed and [merged](https://github.com/flutter/flutter/issues/66514) in Master. Can you switch to latest Master and try again to see if it works ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
