### ISSUE TITLE
Text widget with foreground Paint in TextStyle is not working

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#67993]
Migrating https://github.com/dart-lang/dart-pad/issues/1647

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows, replace `lib/main.dart` with the following content:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Stack(
            children: <Widget>[
              // Stroked text as border.
              Text(
                'Greetings, planet!',
                style: TextStyle(
                  fontSize: 40,
                  foreground: Paint()
                    ..style = PaintingStyle.stroke
                    ..strokeWidth = 6
                    ..color = Colors.blue[700],
                ),
              ),
              // Solid text as fill.
              Text(
                'Greetings, planet!',
                style: TextStyle(
                  fontSize: 40,
                  color: Colors.grey[300],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

3. Run under either Chrome or Chrome with CanvasKit backend.

**Expected results:** 
Here is the results of running `flutter run -d macos`:

<img width="657" alt="Screen Shot 2020-10-13 at 5 19 22 pm" src="https://user-images.githubusercontent.com/30503/95822769-446a8400-0d78-11eb-8f06-ba70f9d1adbe.png">

**Actual results:** 

`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`:

<img width="712" alt="Screen Shot 2020-10-13 at 5 21 26 pm" src="https://user-images.githubusercontent.com/30503/95822946-8abfe300-0d78-11eb-8537-88594a22ad36.png">

And, finally `flutter run -d chrome`:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text/paragraph.dart:795:13
color == null || foreground == null
"Cannot provide both a color and a foreground\nThe color argument is just a shorthand for
\"foreground: new Paint()..color = color\"."

The relevant error-causing widget was:
  Text file:///Users/brettmorgan/flutter-projects/issue_1647/lib/main.dart:16:15

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
lib/_engine/engine/text/paragraph.dart 795:44                                 new
lib/_engine/engine/text/paragraph.dart 1224:45                                [_tryBuildPlainText]
lib/_engine/engine/text/paragraph.dart 1128:12                                build
packages/flutter/src/painting/text_painter.dart 571:27                        layout
packages/flutter/src/rendering/paragraph.dart 497:18                          [_layoutText]
packages/flutter/src/rendering/paragraph.dart 520:5                           [_layoutTextWithConstraints]
packages/flutter/src/rendering/paragraph.dart 592:5                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/stack.dart 565:14                              performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/shifted_box.dart 395:7                         performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/custom_layout.dart 171:10                      layoutChild
packages/flutter/src/material/scaffold.dart 893:7                             performLayout
packages/flutter/src/rendering/custom_layout.dart 243:7                       [_callPerformLayout]
packages/flutter/src/rendering/custom_layout.dart 402:14                      performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/proxy_box.dart 1306:11                         performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/stack.dart 565:14                              performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/proxy_box.dart 3230:13                         performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/widgets/overlay.dart 714:14                              performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/proxy_box.dart 111:7                           performLayout
packages/flutter/src/rendering/object.dart 1777:7                             layout
packages/flutter/src/rendering/view.dart 167:7                                performLayout
packages/flutter/src/rendering/object.dart 1634:7                             [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 884:17                             flushLayout
packages/flutter/src/rendering/binding.dart 443:19                            drawFrame
packages/flutter/src/widgets/binding.dart 907:13                              drawFrame
packages/flutter/src/rendering/binding.dart 309:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1117:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1055:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 864:7                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback

The following RenderObject was being processed when the exception was fired: RenderParagraph#7bf0f
relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT:
  creator: RichText ← Text ← Stack ← Center ← _BodyBuilder ← MediaQuery ←
    LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
    AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#ae94c ink renderer] ← ⋯
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=600.0, 0.0<=h<=390.0)
  size: MISSING
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
This RenderObject had the following child:
    text: TextSpan
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Assertion failed:
file:///Users/brettmorgan/flutter/packages/flutter/lib/src/rendering/box.dart:1785:12
Another exception was thrown: Assertion failed:
file:///Users/brettmorgan/flutter/packages/flutter/lib/src/rendering/shifted_box.dart:323:12
Another exception was thrown: Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/text/paragraph.dart:795:13
Error: Cannot hit test a render box with no size.
The hitTest() method was called on this RenderBox: RenderStack#ff165 relayoutBoundary=up2:
  creator: Stack ← Center ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout
  ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#ae94c ink renderer]
  ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=600.0, 0.0<=h<=390.0)
  size: MISSING
  alignment: AlignmentDirectional.topStart
  textDirection: ltr
  fit: loose
Although this node is not marked as needing layout, its size is not set.
A RenderBox object must have an explicit size before it can be hit-tested. Make sure that the RenderBox in
question sets its size during layout.
    at Object.throw_ [as throw] (http://localhost:49797/dart_sdk.js:4339:11)
    at http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4520:21
    at stack.RenderStack.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4523:23)
    at http://localhost:49797/packages/flutter/src/rendering/shifted_box.dart.lib.js:141:47
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8447:19)
    at shifted_box.RenderPositionedBox.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/shifted_box.dart.lib.js:138:23)
    at shifted_box.RenderPositionedBox.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8713:44
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8447:19)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.defaultHitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8710:30)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/custom_layout.dart.lib.js:284:19)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at material._RenderInkFeatures.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at material._RenderInkFeatures.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderPhysicalModel.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderPhysicalModel.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderPhysicalModel.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:2080:20)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderRepaintBoundary.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderRepaintBoundary.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderIgnorePointer.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderIgnorePointer.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderIgnorePointer.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:3341:59)
    at http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8713:44
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8447:19)
    at stack.RenderStack.new.defaultHitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8710:30)
    at stack.RenderStack.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/stack.dart.lib.js:673:19)
    at stack.RenderStack.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderDecoratedBox.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderDecoratedBox.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderFractionalTranslation.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:2931:24
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8447:19)
    at proxy_box.RenderFractionalTranslation.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:2929:21)
    at proxy_box.RenderFractionalTranslation.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:2922:19)
    at proxy_box.RenderFractionalTranslation.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:2931:24
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8447:19)
    at proxy_box.RenderFractionalTranslation.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:2929:21)
    at proxy_box.RenderFractionalTranslation.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:2922:19)
    at proxy_box.RenderRepaintBoundary.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderRepaintBoundary.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderOffstage.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderOffstage.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderOffstage.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:3440:59)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at http://localhost:49797/packages/flutter/src/widgets/widget_span.dart.lib.js:28072:42
    at box.BoxHitTestResult.wrap.addWithPaintOffset
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:8447:19)
    at overlay$._RenderTheatre.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/widgets/widget_span.dart.lib.js:28069:28)
    at overlay$._RenderTheatre.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderAbsorbPointer.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderAbsorbPointer.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderAbsorbPointer.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:3516:79)
    at proxy_box.RenderPointerListener.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderPointerListener.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:473:36)
    at custom_paint.RenderCustomPaint.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at custom_paint.RenderCustomPaint.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/custom_paint.dart.lib.js:294:20)
    at custom_paint.RenderCustomPaint.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at proxy_box.RenderSemanticsAnnotations.new.hitTestChildren
    (http://localhost:49797/packages/flutter/src/rendering/proxy_box.dart.lib.js:374:56)
    at proxy_box.RenderSemanticsAnnotations.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4525:28)
    at view.RenderView.new.hitTest
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4810:58)
    at view.RenderView.new.hitTestMouseTrackers
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:4818:12)
    at http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:5970:48
    at mouse_tracking.MouseTracker.new.updateWithEvent
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:5024:94)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:49797/packages/flutter/src/rendering/layer.dart.lib.js:5967:45)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately]
    (http://localhost:49797/packages/flutter/src/gestures/binding.dart.lib.js:260:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
    (http://localhost:49797/packages/flutter/src/gestures/binding.dart.lib.js:233:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
    (http://localhost:49797/packages/flutter/src/gestures/binding.dart.lib.js:222:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
    (http://localhost:49797/packages/flutter/src/gestures/binding.dart.lib.js:212:65)
    at Object._invoke1 (http://localhost:49797/dart_sdk.js:176547:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:49797/dart_sdk.js:172276:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:49797/dart_sdk.js:159053:24)
    at http://localhost:49797/dart_sdk.js:159429:26
    at http://localhost:49797/dart_sdk.js:159401:16
    at http://localhost:49797/dart_sdk.js:159154:11
```

<details>
  <summary>Logs</summary>

```
```

```
$ flutter analyze
Analyzing issue_1647...                                                 
No issues found! (ran in 2.2s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, 1.23.0-14.0.pre.151, on Mac OS X 10.15.7 19H2 x86_64, locale en)
    • Flutter version 1.23.0-14.0.pre.151 at /Users/brettmorgan/flutter
    • Framework revision 625ffcaaa6 (78 minutes ago), 2020-10-13 01:07:02 -0400
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Stack(
            children: <Widget>[
              // Stroked text as border.
              Text(
                'Greetings, planet!',
                style: TextStyle(
                  fontSize: 40,
                  foreground: Paint()
                    ..style = PaintingStyle.stroke
                    ..strokeWidth = 6
                    ..color = Colors.blue[700],
                ),
              ),
              // Solid text as fill.
              Text(
                'Greetings, planet!',
                style: TextStyle(
                  fontSize: 40,
                  color: Colors.grey[300],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-19.0.pre.48, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en-GB)
    • Flutter version 1.23.0-19.0.pre.48 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1133c2e85c (8 hours ago), 2020-10-15 01:57:04 -0400
    • Engine revision d2ea378be4
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.7 19H2
      darwin-x64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 86.0.4240.80

• No issues found!

```

</details>
