### ISSUE TITLE
Flutter crash when run command:flutter --no-color pub upgrade 

### ISSUE THREAD

**Issue by ouxiaoyong** [flutter/flutter#67994]
## command

flutter --no-color pub upgrade

## exception

ProcessException: ProcessException: The command failed
  Command: unzip -o -q /Users/domobile/Documents/flutter_sdk/flutter/bin/cache/downloads/storage.flutter-io.cn/flutter_infra/flutter/9d5b21729ff53dbf8eadd8bc97e0e30d77abec95/sky_engine.zip -d /Users/domobile/Documents/flutter_sdk/flutter/bin/cache/pkg

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:448:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:218:19)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:619:16)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#12     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1192:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#21     Net.fetchUrl (package:flutter_tools/src/base/net.dart)
#22     _rootRunUnary (dart:async/zone.dart:1192:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#28     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#29     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#30     Net._attempt (package:flutter_tools/src/base/net.dart)
#31     _rootRunUnary (dart:async/zone.dart:1192:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#37     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#38     _rootRun (dart:async/zone.dart:1184:13)
#39     _CustomZone.run (dart:async/zone.dart:1077:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
1
1
1
1
[!] Flutter (Channel 1, v0.0.0-unknown, on Mac OS, locale zh-Hans-CN)
    • Flutter version 0.0.0-unknown at /Users/domobile/Documents/flutter_sdk/flutter
    • Framework revision 1 (1), 1970-01-01 08:00:00.000
    • Engine revision 9d5b21729f
    • Dart version 2.8.2
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/domobile/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java
    ✗ Could not determine java version

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Community Edition (version unknown)
    ✗ Invalid IntelliJ version number.

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: /Users/domobile/Library/Android/sdk/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:62:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:321:52)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:311:12)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:152:20)
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:926:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1184:13)
      #8      _CustomZone.run (dart:async/zone.dart:1077:19)
      #9      _runZoned (dart:async/zone.dart:1619:10)
      #10     runZonedGuarded (dart:async/zone.dart:1608:12)
      #11     runZoned (dart:async/zone.dart:1536:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:172:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:271:47)
      #15     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:247:26)
      #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
      #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
      #18     _rootRun (dart:async/zone.dart:1184:13)
      #19     _CustomZone.run (dart:async/zone.dart:1077:19)
      #20     _runZoned (dart:async/zone.dart:1619:10)
      #21     runZoned (dart:async/zone.dart:1539:10)
      #22     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
      #23     _doctorText (package:flutter_tools/runner.dart:246:19)
      #24     _informUserOfCrash (package:flutter_tools/runner.dart:155:35)
      #25     _handleToolError (package:flutter_tools/runner.dart:136:13)
      #26     _rootRunUnary (dart:async/zone.dart:1192:38)
      #27     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
      #28     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
      #29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
      #30     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
      #31     Future._completeWithValue (dart:async/future_impl.dart:526:5)
      #32     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
      #33     _rootRun (dart:async/zone.dart:1184:13)
      #34     _CustomZone.run (dart:async/zone.dart:1077:19)
      #35     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
      #36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
      #37     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 6 categories.
```

**Comment by pedromassangocode** [comment]
Hi @ouxiaoyong 
It looks like you are not using a valid Flutter channel.
Can you please upgrade to the latest  `stable` version and try again? Please run the following commands:
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
