### ISSUE TITLE
Devicelab failure: timed out waiting for app to launch

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68035]
For example:

```
2020-10-13T09:43:33.468252: stdout: [ +268 ms] [100%] Connecting to remote debug server
stdout: [        ] -------------------------
2020-10-13T09:43:33.505865: stdout: [  +37 ms] (lldb) command source -s 0 '/tmp/0F665124-2212-4DE0-A65A-3A5A8324DC71/fruitstrap-lldb-prep-cmds-87b7be763fbf79fb324179b431f26198d2338da2'
stdout: [        ] Executing commands in '/tmp/0F665124-2212-4DE0-A65A-3A5A8324DC71/fruitstrap-lldb-prep-cmds-87b7be763fbf79fb324179b431f26198d2338da2'.
2020-10-13T09:43:33.505961: stdout: [        ] (lldb)     platform select remote-ios --sysroot '/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols'
2020-10-13T09:43:33.506096: stdout: [        ]   Platform: remote-ios
stdout: [        ]  Connected: no
2020-10-13T09:43:33.506262: stdout: [        ]   SDK Path: "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols"
2020-10-13T09:43:33.506327: stdout: [        ] (lldb)     target create "/Users/flutter/.cocoon/flutter/dev/integration_tests/platform_interaction/build/ios/iphoneos/Runner.app"
2020-10-13T09:43:36.760753: stdout: [+3254 ms] Current executable set to '/Users/flutter/.cocoon/flutter/dev/integration_tests/platform_interaction/build/ios/iphoneos/Runner.app' (arm64).
stdout: [        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/AEF078C8-955B-4FD2-9ED4-CE7B28F7CC9B/Runner.app"
2020-10-13T09:43:36.974998: stdout: [ +214 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:62737"
2020-10-13T09:43:36.975311: stdout: [        ] (lldb)     script fruitstrap_output_path=""
2020-10-13T09:43:36.975794: stdout: [        ] (lldb)     script fruitstrap_error_path=""
2020-10-13T09:43:36.976224: stdout: [        ] (lldb)     target modules search-paths add /usr "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/usr" /System "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/System" "/private/var/containers/Bundle/Application/AEF078C8-955B-4FD2-9ED4-CE7B28F7CC9B" "/Users/flutter/.cocoon/flutter/dev/integration_tests/platform_interaction/build/ios/iphoneos" "/var/containers/Bundle/Application/AEF078C8-955B-4FD2-9ED4-CE7B28F7CC9B" "/Users/flutter/.cocoon/flutter/dev/integration_tests/platform_interaction/build/ios/iphoneos" /Developer "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/Developer"
2020-10-13T09:43:36.990976: stdout: [  +14 ms] (lldb)     command script import "/tmp/0F665124-2212-4DE0-A65A-3A5A8324DC71/fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.py"
2020-10-13T09:43:36.995190: stdout: [   +4 ms] (lldb)     command script add -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.connect_command connect
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.run_command run
2020-10-13T09:43:36.995296: stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.autoexit_command autoexit
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.safequit_command safequit
2020-10-13T09:43:36.995347: stdout: [        ] (lldb)     connect
2020-10-13T09:43:37.025240: stdout: [  +29 ms] (lldb)     run
2020-10-13T09:44:07.054785: stdout: [+30030 ms] error: process launch failed: timed out waiting for app to launch
2020-10-13T09:44:07.054899: stderr: [        ] Could not run build/ios/iphoneos/Runner.app on 87b7be763fbf79fb324179b431f26198d2338da2.
2020-10-13T09:44:07.054953: stderr: [        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
2020-10-13T09:44:07.055108: stderr: [        ]   open ios/Runner.xcworkspace
2020-10-13T09:44:07.055470: stdout: [        ] Installing and launching... (completed in 38.5s)
2020-10-13T09:44:07.059515: stdout: [   +4 ms] "flutter drive" took 54,621ms.
2020-10-13T09:44:07.064924: stderr: [   +5 ms] Application failed to start. Will not run test. Quitting.
2020-10-13T09:44:07.065435: stderr: [        ] 
stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
stderr:            #1      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:244:9)
```

Many questions:

- What actual process here is failing?
- do we know some possible reasons?
- Would retrying work, or is this a "phone in a bad state" problem?

@xster @jmagman

**Comment by zanderso** [comment]
The tree is closed on this, and repeated re-runs, and reverts probably won't get it open again, so I'm marking this P0, and adding to the infra ticket queue.

**Comment by xster** [comment]
Haven't seen this issue before. Seems like an Xcode error surfacing through ios-deploy. Did we create a devicelab specific provisioning profile that may have expired? 

@godofredoc

**Comment by xster** [comment]
Do we have access to the machine? Worth trying the ios-deploy command directly (seen in the logs just above where you copy pasted).

**Comment by jonahwilliams** [comment]
Lowering to P1, I reverted the last commit which was causing the tree-blocking failures. Though the number of iOS failures this week is still quite large

**Comment by jmagman** [comment]
I bet `lldb` didn't exit and is still attached, so the second attempt can never attach and it times out.

**Comment by jmagman** [comment]
The first failure is the old `Connection closed before full header was received` chestnut, THEN it times out trying to attach the second time.
```
2020-10-13T11:10:58.049126: stdout: [  +26 ms] (lldb)     run
2020-10-13T11:10:58.176178: stdout: [ +127 ms] success
2020-10-13T11:10:58.176327: stdout: [        ] Application launched on the device. Waiting for observatory port.
2020-10-13T11:10:58.188815: stdout: [  +12 ms] Attempting to forward device port 64291 to host port 61344
2020-10-13T11:10:58.189274: stdout: [        ] executing: /Users/flutter/.cocoon/flutter/bin/cache/artifacts/usbmuxd/iproxy 61344:64291 --udid 43ad2fda7991b34fe1acbda82f9e2fd3d6ddc9f7
2020-10-13T11:10:59.203876: stdout: [+1014 ms] Forwarded port ForwardedPort HOST:61344 to DEVICE:64291
2020-10-13T11:10:59.254275: stdout: [  +50 ms] HttpException: Connection closed before full header was received, uri = http://localhost:61344/ws
2020-10-13T11:11:01.271949: stdout: [+2017 ms] HttpException: , uri = http://localhost:61344/ws
2020-10-13T11:11:03.287616: stdout: [+2015 ms] HttpException: , uri = http://localhost:61344/ws
2020-10-13T11:11:05.303009: stdout: [+2015 ms] HttpException: , uri = http://localhost:61344/ws
2020-10-13T11:11:07.318346: stdout: [+2015 ms] HttpException: , uri = http://localhost:61344/ws
2020-10-13T11:11:09.329968: stdout: [+2011 ms] Failed to connect directly, falling back to log scanning
2020-10-13T11:11:14.348626: stdout: [+5018 ms] Failed to connect with log scanning
2020-10-13T11:11:14.348830: stdout: [        ] Installing and launching... (completed in 22.6s)
2020-10-13T11:11:14.349157: stderr: [        ] Error running application on iPhone.
2020-10-13T11:11:14.351664: stdout: [   +2 ms] "flutter run" took 32,784ms.
```
and the next try times out:
```
2020-10-13T11:18:07.019349: stdout: [        ] (lldb)     connect
2020-10-13T11:18:07.048593: stdout: [  +29 ms] (lldb)     run
2020-10-13T11:18:37.078992: stdout: [+30031 ms] error: process launch failed: timed out waiting for app to launch
```
[platform_view_ios__start_up_37ebe3d_3.log](https://github.com/flutter/flutter/files/5373440/platform_view_ios__start_up_37ebe3d_3.log)

**Comment by xster** [comment]
Good find. That's what @DanielEdrisian noticed as well in https://github.com/flutter/flutter/issues/67333. Our agent code should probably look for orphaned debuggers and explicitly kill them before trying each time.

**Comment by jonahwilliams** [comment]
I think it would be better if this could be handled by the tool, since this presumably would affect everyone developing flutter on iOS?

**Comment by jmagman** [comment]
The simulator codepath is different, it doesn't attach with `lldb`, it can log scan directly from the host.

**Comment by xster** [comment]
How would you handle it on the tool? I don't think it would be right to actually do anything besides surfacing a better warning? Having an existing run through CLI/ios-deploy/lldb or through Xcode/lldb isn't really telling what the intentions are. Might be leftovers, might be user actually debugging native code/plugins/custom engines.

**Comment by jmagman** [comment]
The debugger is missing a detach when the attach succeeds, but the VM service connection fails.  I have the fix, I just need to spend 10x the time to unit test it.

**Comment by jmagman** [comment]
This fix won't actually make the tests pass since something is causing it to not connect to the VM service--it will just prevent the timeout on retry.
