### ISSUE TITLE
Android studio crashing with upgrade in flutter on 4.1 latest

### ISSUE THREAD

**Issue by galanteria01** [flutter/flutter#68076]
Everything works good until upgrade of flutter is done by marketplace and restarting IDE ends up with
<code>
Internal error. Please refer to https://code.google.com/p/android/issues

java.lang.NoSuchMethodError: com.intellij.ide.plugins.PluginManagerCore.loadDescriptors()[Lcom/intellij/ide/plugins/IdeaPluginDescriptorImpl;
    at com.a.a.b.b.ar.a(ar.java:121)
    at com.a.a.b.b.ar.a(ar.java:71)
    at com.intellij.idea.MainImpl.start(MainImpl.java:19)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:303)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
    at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
    at java.lang.Thread.run(Thread.java:748)
-----
JRE 1.8.0_242-release-1644-b3-6222593 amd64 by JetBrains s.r.o
/snap/android-studio/94/android-studio/jre/jre
</code>
Reinstalling everything makes it work.

**Comment by TahaTesser** [comment]
Hi @galanteria01 
This isn't an issue with Flutter itself 
Please see https://stackoverflow.com/questions/63487696/android-studio-4-1-rc-facing-start-failed-error-after-upgrade 
https://youtrack.jetbrains.com/issue/TBX-5051

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
