### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict

### ISSUE THREAD

**Issue by ravindravala** [flutter/flutter#68104]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:425:20)
#2      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:504:5)
<asynchronous suspension>
#3      HotRunner._fullRestartHelper.<anonymous closure> (package:flutter_tools/src/run_hot.dart:741:39)
#4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
<asynchronous suspension>
#5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZonedGuarded (dart:async/zone.dart:1618:12)
#10     runZoned (dart:async/zone.dart:1547:12)
#11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#12     HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:741:22)
<asynchronous suspension>
#13     HotRunner.restart (package:flutter_tools/src/run_hot.dart:683:44)
<asynchronous suspension>
#14     TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1591:61)
#15     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1635:13)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
```
```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.110, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.23.0-8.0.pre.110 at C:\flutter
    • Framework revision 5d6321b509 (12 days ago), 2020-10-02 11:02:03 -0700
    • Engine revision 87a10f240f
    • Dart version 2.11.0 (build 2.11.0-181.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • Redmi Y2 (mobile) • 192.168.1.2:5555 • android-arm    • Android 9 (API 28)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 86.0.622.38

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: c748f1a7aa17b45e48ac3b3861424df6a3672c79
### Plugins
fluttertoast-7.1.1
path_provider_linux-0.0.1+2
path_provider_windows-0.0.4+1
shared_preferences-0.5.12
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+1

**Comment by jonahwilliams** [comment]
@ravindravala  are you able to reproduce this crash consistently? Do you have more detailed instructions on how to do so?

**Comment by ravindravala** [comment]
No , it's solved now.
