### ISSUE TITLE
Flutter iOS devicelab is having problems connecting to the VM Service

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68119]
![2020-10-14](https://user-images.githubusercontent.com/8975114/96022371-9d342e00-0e05-11eb-9dfa-16a53ee6fe30.png)

The errors is frequently something like:

```
stdout: [        ] -------------------------
2020-10-14T09:46:53.200480: stdout: [  +35 ms] (lldb) command source -s 0 '/tmp/C40623FC-2F57-4304-9C72-98815F7DF0E2/fruitstrap-lldb-prep-cmds-87b7be763fbf79fb324179b431f26198d2338da2'
stdout: [        ] Executing commands in '/tmp/C40623FC-2F57-4304-9C72-98815F7DF0E2/fruitstrap-lldb-prep-cmds-87b7be763fbf79fb324179b431f26198d2338da2'.
2020-10-14T09:46:53.200583: stdout: [        ] (lldb)     platform select remote-ios --sysroot '/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols'
stdout: [        ]   Platform: remote-ios
2020-10-14T09:46:53.200629: stdout: [        ]  Connected: no
2020-10-14T09:46:53.200729: stdout: [        ]   SDK Path: "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols"
2020-10-14T09:46:53.200859: stdout: [        ] (lldb)     target create "/Users/flutter/.cocoon/flutter/examples/platform_channel_swift/build/ios/iphoneos/Runner.app"
2020-10-14T09:46:56.730765: stdout: [+3529 ms] Current executable set to '/Users/flutter/.cocoon/flutter/examples/platform_channel_swift/build/ios/iphoneos/Runner.app' (arm64).
stdout: [        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/14392490-48D3-4D81-9C43-1CC3D678EB12/Runner.app"
2020-10-14T09:46:56.946620: stdout: [ +215 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:51549"
2020-10-14T09:46:56.946825: stdout: [        ] (lldb)     script fruitstrap_output_path=""
2020-10-14T09:46:56.947269: stdout: [        ] (lldb)     script fruitstrap_error_path=""
2020-10-14T09:46:56.947757: stdout: [        ] (lldb)     target modules search-paths add /usr "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/usr" /System "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/System" "/private/var/containers/Bundle/Application/14392490-48D3-4D81-9C43-1CC3D678EB12" "/Users/flutter/.cocoon/flutter/examples/platform_channel_swift/build/ios/iphoneos" "/var/containers/Bundle/Application/14392490-48D3-4D81-9C43-1CC3D678EB12" "/Users/flutter/.cocoon/flutter/examples/platform_channel_swift/build/ios/iphoneos" /Developer "/Users/flutter/Library/Developer/Xcode/iOS DeviceSupport/13.1.3 (17A878)/Symbols/Developer"
2020-10-14T09:46:56.962849: stdout: [  +15 ms] (lldb)     command script import "/tmp/C40623FC-2F57-4304-9C72-98815F7DF0E2/fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.py"
2020-10-14T09:46:56.966346: stdout: [   +3 ms] (lldb)     command script add -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.connect_command connect
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.run_command run
stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.autoexit_command autoexit
2020-10-14T09:46:56.966442: stdout: [        ] (lldb)     command script add -s asynchronous -f fruitstrap_87b7be763fbf79fb324179b431f26198d2338da2.safequit_command safequit
2020-10-14T09:46:56.966531: stdout: [        ] (lldb)     connect
2020-10-14T09:46:56.996352: stdout: [  +29 ms] (lldb)     run
2020-10-14T09:47:27.023630: stderr: [+30028 ms] ═══════════════════════════════════════════════════════════════════════════════════
stderr:             Could not attach the debugger.
stderr:             Try uninstalling the app from your device and retrying.
stderr:             ═══════════════════════════════════════════════════════════════════════════════════
stdout: [        ] error: process launch failed: timed out waiting for app to launch
2020-10-14T09:47:27.023788: stderr: [        ] Could not run build/ios/iphoneos/Runner.app on 87b7be763fbf79fb324179b431f26198d2338da2.
2020-10-14T09:47:27.023865: stderr: [        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
2020-10-14T09:47:27.024057: stderr: [        ]   open ios/Runner.xcworkspace
2020-10-14T09:47:27.024351: stdout: [        ] Installing and launching... (completed in 40.4s)
2020-10-14T09:47:27.027169: stdout: [   +2 ms] "flutter drive" took 82,711ms.
2020-10-14T09:47:27.030723: stderr: [   +3 ms] Application failed to start. Will not run test. Quitting.
2020-10-14T09:47:27.031185: stderr: [        ] 
stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
stderr:            #1      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:244:9)
stderr:            <asynchronous suspension>
stderr:            #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1016:18)
stderr:            <asynchronous suspension>
stderr:            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:875:33)
stderr:            <asynchronous suspension>
stderr:            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
stderr:            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
stderr:            #6      _rootRun (dart:async/zone.dart:1190:13)
stderr:            #7      _CustomZone.run (dart:async/zone.dart:1093:19)
stderr:            #8      _runZoned (dart:async/zone.dart:1630:10)
stderr:            #9      runZoned (dart:async/zone.dart:1550:10)
stderr:            #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
stderr:            #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:864:20)
2020-10-14T09:47:27.031268: stderr:            #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
stderr:            #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
stderr:            #14     _rootRunUnary (dart:async/zone.dart:1198:47)
stderr:            #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
stderr:            #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
stderr:            #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
stderr:            #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
stderr:            #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
stderr:            #20     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
stderr:            #21     _rootRun (dart:async/zone.dart:1190:13)
stderr:            #22     _CustomZone.run (dart:async/zone.dart:1093:19)
stderr:            #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
stderr:            #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
stderr:            #25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
stderr:            #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
stderr:            #27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
stderr:            #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by jmagman** [comment]
@jonahwilliams `Could not attach the debugger.`  isn't the failure, it's always the one running right before it failing in some way, then not detaching the debugger.  Which is a bug, but it's not the cause of the underlying failure.

**Comment by jmagman** [comment]
You're right though, a lot of the flakes are showing that as the first error.  Seems like `lldb` is getting leaked on the phone, and the app isn't being reinstalled between runs?  How would that be possible?

**Comment by jmagman** [comment]
I see this pattern in a few places:
```
2020-10-14T15:06:59.012188: stdout: [        ] [ 18%] Copying /Users/flutter/.cocoon/flutter/dev/integration_tests/ios_platform_view_tests/build/ios/iphoneos/Runner.app/Frameworks/ to device
stdout: [        ] [ 18%] Copying /Users/flutter/.cocoon/flutter/dev/integration_tests/ios_platform_view_tests/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/ to device
2020-10-14T15:06:59.012746: stdout: [        ] [ 19%] Copying /Users/flutter/.cocoon/flutter/dev/integration_tests/ios_platform_view_tests/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/ to device
stdout: [        ] [ 19%] Copying /Users/flutter/.cocoon/flutter/dev/integration_tests/ios_platform_view_tests/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources to device
2020-10-14T15:07:37.199546: stderr: [        ] Could not run build/ios/iphoneos/Runner.app on 87b7be763fbf79fb324179b431f26198d2338da2.
stderr: [        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
stderr: [        ]   open ios/Runner.xcworkspace
2020-10-14T15:07:37.199823: stdout: [        ] Installing and launching... (completed in 38.4s)
2020-10-14T15:07:37.203315: stdout: [   +3 ms] "flutter drive" took 63,803ms.
2020-10-14T15:07:37.207332: stderr: [   +4 ms] Application failed to start. Will not run test. Quitting.
```
[ios_platform_view_tests_83e99f7_3.log](https://github.com/flutter/flutter/files/5381349/ios_platform_view_tests_83e99f7_3.log)

It's taking a long time/getting stuck copying the framework to the device, and it times out.

**Comment by jonahwilliams** [comment]
We don't get any more specific logging for that? I wonder if its a sort of transient issue that we should retry, or if it indicates that device is stuck somehow (storage?)

**Comment by jonahwilliams** [comment]
We're definitely sure it was the engine roll 11d756a62ed0ddf87a9ce20b219b55300ec6b67d

Not definitely sure what commit, but the root isolate change seems the most suspicious

**Comment by jmagman** [comment]
We thought it was that engine roll, but reverting didn't make it go away.  Rebooting all the host agents did make it go away.
I see many leaked iproxy processes on these agents.  Locally, I am also reproducing a iproxy leak on `drive`
```
$ cd examples/platform_channel_swift
$ flutter drive --no-android-gradle-daemon -v -t test_driver/button_tap.dart
<succeeds>
$ $ ps -ef | grep iproxy
670434 66127     1   0  1:56PM ttys000    0:00.02 /Users/m/Projects/flutter/bin/cache/artifacts/usbmuxd/iproxy 61379:54675 --udid d83d5bc53967baa0ee186234a87b6254b2ab5418

**Comment by jonahwilliams** [comment]
We think this is fixed by the iproxy disposal PR above.
