### ISSUE TITLE
Video Player not working on android after flutter upgrade

### ISSUE THREAD

**Issue by tienthai0205** [flutter/flutter#68121]
After flutter run, I ran into this error
```
E/flutter (30800): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true.
E/flutter (30800): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (30800): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (30800): #2      new PlatformException (package:flutter/src/services/message_codec.dart:111:15)
E/flutter (30800): #3      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:205:13)
E/flutter (30800): <asynchronous suspension>
E/flutter (30800): #4      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46:42)
E/flutter (30800): #5      VideoPlayerController.initialize (package:video_player/video_player.dart:282:45)
E/flutter (30800): #6      _HomeScreenState.initState (package:wahey/screens/home_screen/home_screen.dart:21:9)
E/flutter (30800): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (30800): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (30800): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (30800): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (30800): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (30800): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (30800): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (30800): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (30800): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (30800): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (30800): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (30800): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (30800): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (30800): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (30800): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (30800): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (30800): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (30800): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (30800): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (30800): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (30800): #27     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (30800): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (30800): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (30800): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (30800): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (30800): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (30800): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (30800): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (30800): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (30800): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (30800): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (30800): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (30800): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (30800): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (30800): #41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (30800): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (30800): #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
```
It doesn't crash the app, but the video does not show up. This happens only on android and after upgrading to flutter 1.22.0

**Comment by hamdikahloun** [comment]
Hi @tienthai0205 
Can you please provide your `flutter doctor -v,` your `flutter run --verbose` ?
Thank you

**Comment by tienthai0205** [comment]
Hi @hamdikahloun 
I have just updated the description. This is flutter docker -v, 
```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/thaithuytien/flutter
    • Framework revision f30b7f4db9 (6 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/thaithuytien/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by hamdikahloun** [comment]
Possible duplicated issue https://github.com/flutter/flutter/issues/66627

**Comment by TahaTesser** [comment]
Hi @tienthai0205 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/66627
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
