### ISSUE TITLE
context != null is not true when switching language in System Settings (l10n localization)

### ISSUE THREAD

**Issue by tomvanlieshout** [flutter/flutter#68204]
I implemented the new way of setting up localization ([described here](https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit#)). It all works well, generating the localized values during build and translating labels accordingly.

However, when I change the language of Android while the app is running and return to the app, an exception is thrown after triggering an action:

```
E/flutter (13075): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/localizations.dart': Failed assertion: line 453 pos 12: 'context != null': is not true.
E/flutter (13075): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:46:39))
E/flutter (13075): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5))
E/flutter (13075): #2      Localizations.of 
package:flutter/…/widgets/localizations.dart:453
E/flutter (13075): #3      AppLocalizations.of 
package:flutter_gen/gen_l10n/app_localizations.dart:71
E/flutter (13075): #4      EventDialogState.initState.<anonymous closure> 
package:monteurapp/widgets/event_dialog.dart:31
E/flutter (13075): #5      _rootRunUnary  (dart:async/zone.dart:1198:47))
E/flutter (13075): #6      _CustomZone.runUnary  (dart:async/zone.dart:1100:19))
E/flutter (13075): #7      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7))
E/flutter (13075): #8      CastStreamSubscription._onData  (dart:_internal/async_cast.dart:85:11))
E/flutter (13075): #9      _rootRunUnary  (dart:async/zone.dart:1198:47))
E/flutter (13075): #10     _CustomZone.runUnary  (dart:async/zone.dart:1100:19))
E/flutter (13075): #11     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7))
E/flutter (13075): #12     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11))
E/flutter (13075): #13     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:285:7))
E/flutter (13075): #14     _ForwardingStreamSubscription._add  (dart:async/stream_pipe.dart:127:11))
E/flutter (13075): #15     _WhereStream._handleData  (dart:async/stream_pipe.dart:199:12))
E/flutter (13075): #16     _ForwardingStreamSubscription._handleData  (dart:async/stream_pipe.dart:157:13))
E/flutter (13075): #17     _rootRunUnary  (dart:async/zone.dart:1198:47))
E/flutter (13075): #18     _CustomZone.runUnary  (dart:async/zone.dart:1100:19))
E/flutter (13075): #19     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7))
E/flutter (13075): #20     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11))
E/flutter (13075): #21     _DelayedData.perform  (dart:async/stream_impl.dart:611:14))
E/flutter (13075): #22     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:730:11))
E/flutter (13075): #23     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:687:7))
E/flutter (13075): #24     _rootRun  (dart:async/zone.dart:1182:47))
E/flutter (13075): #25     _CustomZone.run  (dart:async/zone.dart:1093:19))
E/flutter (13075): #26     _CustomZone.runGuarded  (dart:async/zone.dart:997:7))
E/flutter (13075): #27     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23))
E/flutter (13075): #28     _rootRun  (dart:async/zone.dart:1190:13))
E/flutter (13075): #29     _CustomZone.run  (dart:async/zone.dart:1093:19))
E/flutter (13075): #30     _CustomZone.runGuarded  (dart:async/zone.dart:997:7))
E/flutter (13075): #31     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23))
E/flutter (13075): #32     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21))
E/flutter (13075): #33     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5))
```

It is thrown three times (presumably because there are three UI elements using localized values in the screen that I am currently in).

Steps to recreate:
* Open a view that contains localized values
* Go into Android settings > system > languages and change the primary language
* Go back into the app and trigger an action (in my case: displaying a Snackbar with a localized value)

Note: The values are actually translated properly and switch as soon as I get back into the app.

Here's the output of `flutter doctor`:
```
tom@tom monteurapp % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15 19A603, locale en-GB)
    • Flutter version 1.22.1 at /Users/tom/dev/flutter
    • Framework revision f30b7f4db9 (7 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @tomvanlieshout 
Can you please provide  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by tomvanlieshout** [comment]
Hi @TahaTesser 
I created a helloWorld app with a button that shows a Snackbar, but couldn't reproduce the bug that way. 
Then, I went back to the app that caused it in the first place, but now I am not able to reproduce it in that app either... Even though I had tried different emulators before creating this issue. It somehow disappeared.

I guess this issue can be closed then.
