### ISSUE TITLE
Error launching application on iPhone

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter#68215]
## Steps to Reproduce

Just run `flutter run --verbose`

**Expected results:** 

The app would start on my phone

**Actual results:** 

An error on the terminal and on the phone after it errors out I see a screen that says 
```
In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode. Alternatively, build in profile or release modes to enable launching from the home screen
```

Interestingly enough, if I instead run `flutter build ios` and then hit play directly from Xcode, it works fine. But I can't debug my app with breakpoints doing that...

<details>
  <summary>Logs</summary>

```
[ +611 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +356 ms] ------ Debug phase ------
[        ] Starting debug of d167f1a8b5eed7cd0312f630a2da37135e6788f3 (D11AP, iPhone 7 Plus, iphoneos, arm64) a.k.a. 'iPhone de Jan Lubeck' connected through
USB...
[+1530 ms] [  0%] Looking up developer disk image
[  +14 ms] [ 95%] Developer disk image mounted successfully
[+1976 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[  +29 ms] (lldb) command source -s 0 '/tmp/43EAB877-B245-4381-81F3-E5FF7A64EE92/fruitstrap-lldb-prep-cmds-d167f1a8b5eed7cd0312f630a2da37135e6788f3'
[        ] Executing commands in '/tmp/43EAB877-B245-4381-81F3-E5FF7A64EE92/fruitstrap-lldb-prep-cmds-d167f1a8b5eed7cd0312f630a2da37135e6788f3'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/jan/Library/Developer/Xcode/iOS DeviceSupport/14.0.1 (18A393)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/jan/Library/Developer/Xcode/iOS DeviceSupport/14.0.1 (18A393)/Symbols"
[        ] (lldb)     target create "/Users/jan/Projects/flutter/safepass/source/build/ios/iphoneos/Runner.app"
[+1409 ms] Current executable set to '/Users/jan/Projects/flutter/safepass/source/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/55D7041A-82BC-428F-8BD1-883183388AB4/Runner.app"
[        ] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:63737"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/jan/Library/Developer/Xcode/iOS DeviceSupport/14.0.1 (18A393)/Symbols/usr" /System
"/Users/jan/Library/Developer/Xcode/iOS DeviceSupport/14.0.1 (18A393)/Symbols/System"
"/private/var/containers/Bundle/Application/55D7041A-82BC-428F-8BD1-883183388AB4" "/Users/jan/Projects/flutter/safepass/source/build/ios/iphoneos"
"/var/containers/Bundle/Application/55D7041A-82BC-428F-8BD1-883183388AB4" "/Users/jan/Projects/flutter/safepass/source/build/ios/iphoneos" /Developer
"/Users/jan/Library/Developer/Xcode/iOS DeviceSupport/14.0.1 (18A393)/Symbols/Developer"
[  +22 ms] (lldb)     command script import "/tmp/43EAB877-B245-4381-81F3-E5FF7A64EE92/fruitstrap_d167f1a8b5eed7cd0312f630a2da37135e6788f3.py"
[   +3 ms] (lldb)     command script add -f fruitstrap_d167f1a8b5eed7cd0312f630a2da37135e6788f3.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_d167f1a8b5eed7cd0312f630a2da37135e6788f3.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_d167f1a8b5eed7cd0312f630a2da37135e6788f3.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_d167f1a8b5eed7cd0312f630a2da37135e6788f3.safequit_command safequit
[        ] (lldb)     connect
[  +26 ms] (lldb)     run
[ +238 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[   +9 ms] Attempting to forward device port 56985 to host port 63749
[        ] executing: /Users/jan/flutter/bin/cache/artifacts/usbmuxd/iproxy 63749:56985 --udid d167f1a8b5eed7cd0312f630a2da37135e6788f3
[+1008 ms] Forwarded port ForwardedPort HOST:63749 to DEVICE:56985
[  +11 ms] HttpException: Connection closed before full header was received, uri = http://localhost:63749/ws
[+2007 ms] HttpException: , uri = http://localhost:63749/ws
[+2004 ms] HttpException: , uri = http://localhost:63749/ws
[+2009 ms] HttpException: , uri = http://localhost:63749/ws
[+2003 ms] HttpException: , uri = http://localhost:63749/ws
[+2003 ms] Failed to connect directly, falling back to log scanning
[+5012 ms] Failed to connect with log scanning
[        ] Installing and launching... (completed in 37.9s)
[        ] Error launching application on iPhone de Jan Lubeck.
[   +4 ms] "flutter run" took 142,160ms.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:618:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1005:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +161 ms] ensureAnalyticsSent: 160ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
```

```
```

```
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.23.0-18.0.pre at /Users/jan/flutter
    • Framework revision 37ebe3d82a (2 days ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jan/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • iPhone de Jan Lubeck (mobile) • d167f1a8b5eed7cd0312f630a2da37135e6788f3 • ios            • iOS 14.0.1
    • iPhone 11 Pro (mobile)        • 5D827B35-CC5F-4BD3-A451-5EB38B6ACF87     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)               • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)              • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                  • chrome                                   • web-javascript • Google Chrome 86.0.4240.80
    ! Error: iPhone de Jan Lubeck is busy: Copying cache files from device. Xcode will continue when iPhone de Jan Lubeck is finished. (code -10)

• No issues found!
```

</details>

**Comment by jlubeck** [comment]
Mmm, might be related to this? 
https://github.com/flutter/flutter/issues/66862

**Comment by jlubeck** [comment]
Unlike #66862 restarting my computer didn't fix the issue.

Also, Xcode Devices doesn't show that the device is busy...

<img width="1010" alt="Screen Shot 2020-10-15 at 12 38 32 PM" src="https://user-images.githubusercontent.com/3067603/96160067-75b39300-0ee3-11eb-9acd-42d1aacbb299.png">

**Comment by TahaTesser** [comment]
Hi @jlubeck 
Can you please provide complete Xcode crash logs?

**Comment by jlubeck** [comment]
hey @TahaTesser what I mentioned is that by building on Xcode it does not crash. So I'm not sure what crash logs you are asking for?

**Comment by TahaTesser** [comment]
> Interestingly enough, if I instead run `flutter build ios` and then hit play directly from Xcode, it works fine. But I can't debug my app with breakpoints doing that...

You mentioned you had to first build then play from Xcode, that would mean without the build command you getting crash Xcode run? Are you? 

Generally, if your app crashing from` flutter run --verbose`, it would crash from Xcode run too, can you please provide those logs  without executing `flutter build ios`(since it's solving the based on your words but you can't debug )

**Comment by jlubeck** [comment]
@TahaTesser  Mmm, actually I didn't even try running without building before creating the ticket. I just tried it and it works fine even without building first. So no, no crash when using Xcode. Only using `flutter run`

**Comment by jlubeck** [comment]
If you check my logs, the build itself is finishing fine. It's AFTER it finishes building, and trying to connect to the device that `flutter run` crashes

**Comment by erf** [comment]
I get the same error message when running `flutter run --verbose` now on iOS.

**Comment by erf** [comment]
It works on stable!

**Comment by TahaTesser** [comment]
hI @jlubeck  @erf 
Just tried on the beta channel and dev channel 
Created new project and execute `flutter run -d <device_name> -v`
```.
[        ] [VERBOSE-2:FlutterObservatoryPublisher.mm(117)] On iOS 14+, local network broadcast in apps need to be declared in the
app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features
such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value
to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see
https://flutter.dev/docs/development/add-to-app/ios/project-setup
[+1091 ms] HttpException: , uri = http://localhost:58991/ws
[+2009 ms] HttpException: , uri = http://localhost:58991/ws
[+2010 ms] HttpException: , uri = http://localhost:58991/ws
[+2001 ms] Failed to connect directly, falling back to log scanning
[   +9 ms] Observatory URL on device: http://127.0.0.1:61497/
[   +1 ms] Attempting to forward device port 61497 to host port 59006
[        ] executing: /Users/tahatesser/Code/flutter_beta/bin/cache/artifacts/usbmuxd/iproxy 59006:61497 --udid
00008020-001059882212002E
[+1006 ms] Forwarded port ForwardedPort HOST:59006 to DEVICE:61497
[        ] Forwarded host port 59006 to device port 61497 for Observatory
[   +3 ms] Installing and launching... (completed in 32.8s)
[   +3 ms] Caching compiled dill
[  +50 ms] Connecting to service protocol: http://127.0.0.1:59006/
[   +2 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:59006/.
[ +213 ms] DDS is listening at http://127.0.0.1:59009/ONiZOxoreNo=/.
[  +40 ms] [VERBOSE-2:FlutterObservatoryPublisher.mm(115)] Failed to register observatory port with mDNS with error -65555.
[        ] [VERBOSE-2:FlutterObservatoryPublisher.mm(117)] On iOS 14+, local network broadcast in apps need to be declared in the
app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features
such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value
to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see
https://flutter.dev/docs/development/add-to-app/ios/project-setup
[  +33 ms] Successfully connected to service protocol: http://127.0.0.1:59006/
[   +1 ms] Waiting for Taha’s iPhone to report its views...
[  +11 ms] Waiting for Taha’s iPhone to report its views... (completed in 10ms)
[   +9 ms] DevFS: Creating new filesystem on the device (null)
[  +29 ms] DevFS: Created new filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/61002BA6-D6DA-4767-888A-999840A25007/tmp/beta_flutterSEIA9F/beta_flutter/)
[   +4 ms] Updating assets
[ +119 ms] Syncing files to device Taha’s iPhone...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:beta_flutter/main.dart a2bba8e1-25d2-4441-b576-ed587faca7d4
[        ] <- a2bba8e1-25d2-4441-b576-ed587faca7d4
[ +165 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Taha’s iPhone... (completed in 171ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +6 ms] Connected to _flutterView/0x10901f220.
[   +3 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Taha’s iPhone is available at: http://127.0.0.1:59009/ONiZOxoreNo=/

```

Please make sure you've provided full disk to IDE, if you getting install dialogs, enter a password and accept. See https://github.com/flutter/flutter/issues/66862#issuecomment-711111238

**Comment by erf** [comment]
hi @TahaTesser @jlubeck i did some testing now with a new Flutter project and various plugins and it seems that `cloud_firestore: ^0.14.1+3` is what is causing the error mentioned in the log file.

However, i did managed to get it working by upgrading the pods by doing:

```
pod repo update
sudo gem install cocoapods --pre
```

I then deleted `ios/Podfile.lock` and `ios/Pods`,  did a `flutter clean` and `flutter pub get`, before doing a `pod install` inside the `ios` folder. This seems to work.

I created an issue on FlutterFire here: https://github.com/FirebaseExtended/flutterfire/issues/3909

**Comment by jlubeck** [comment]
@TahaTesser I saw that issue that you mentioned, but I'm not getting any popups to install anything...
@erf I'm not even using Firestore

**Comment by erf** [comment]
@jlubeck did you try to remove various plugins and make a minimal failing example?

**Comment by jlubeck** [comment]
but what would the project have to do with having the phone display as busy when running `flutter devices` ?

**Comment by erf** [comment]
Not sure what you mean by "phone display as busy" .. but i had the same log output as you when i did a `flutter run --verbose`, and i managed to fix it by upgrading Cocoapods and reinstalling the pods.

**Comment by jlubeck** [comment]
> Not sure what you mean by "phone display as busy" .. but i had the same log output as you when i did a `flutter run --verbose`, and i managed to fix it by upgrading Cocoapods and reinstalling the pods.

Sorry, I mentioned on my second comment that my issue might be related to #66862, since it is also showing that same error when running `flutter devices`

Does your phone show an error there as well?

**Comment by erf** [comment]
My phone also show that it's busy, but that seem like a different issue. Your issue is you could not launch your app right? I also had that issue, with the same log error, and now i managed to fix it by updating Cocoapod/pods, so i suggest you try that.

**Comment by jlubeck** [comment]
Ok, was just making sure. If you still have that busy error and it is now working for you, they are definitely unrelated.

Doing your Cocoapods thing is not fixing it for me unfortunately. At least on an initial try.

I'm going to try to update every single package and try again.

Thank you

**Comment by erf** [comment]
Hmmm.. I tried to run it from Android Studio now and then it failed on startup with the message: `Error launching application on ...`. Then i ran it from the terminal and now it shows the same log message again..!

**Comment by erf** [comment]
My test app also fails now when trying to run it from Android Studio. 

And now it also fails when running from the terminal.. with the message: 

```
In iOS14+, debug mode Flutter apps can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode.

Alternatively, build in profile or release modes to enable launching from the home screen.
```

I've added the full log file from `flutter run --verbose` as a file attachment.

[log.txt](https://github.com/flutter/flutter/files/5403095/log.txt)

**Comment by erf** [comment]
@jlubeck which channel are you on? You could add a `flutter doctor`. When i'm back on **stable** everything works.

**Comment by jlubeck** [comment]
@erf my `flutter doctor` is on my first message. I'm on `Channel dev, 1.23.0-18.0.pre`

**Comment by erf** [comment]
@jlubeck ok. you could give stable a try

**Comment by alvinthen** [comment]
Can confirm it works on the stable channel, not beta, both reporting my device as busy copying cache files from device.

Tested on iPhone X (iOS14.0.1)

<details><summary>Log</summary>
<pre>
[        ] Application launched on the device. Waiting for observatory port.
[  +10 ms] Attempting to forward device port 57084 to host port 55408
[        ] executing: /Users/usenamer/flutter/bin/cache/artifacts/usbmuxd/iproxy 55408:57084 --udid
<redacted>
[+1006 ms] Forwarded port ForwardedPort HOST:55408 to DEVICE:57084
[  +12 ms] HttpException: Connection closed before full header was received, uri = http://localhost:55408/ws
[+2009 ms] HttpException: , uri = http://localhost:55408/ws
[+2006 ms] HttpException: , uri = http://localhost:55408/ws
[+2004 ms] HttpException: , uri = http://localhost:55408/ws
[+2004 ms] HttpException: , uri = http://localhost:55408/ws
[+2003 ms] Failed to connect directly, falling back to log scanning
[+5013 ms] Failed to connect with log scanning
[        ] Installing and launching... (completed in 33.8s)
[        ] Error launching application on iPhone.
[   +5 ms] "flutter run" took 50,244ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:618:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1005:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
</pre>
</details>

**Comment by TahaTesser** [comment]
I’m unable to reproduce the issue to pinpoint the cause, but there are reports from several users. The issue needs further investigation.

**Comment by erf** [comment]
@TahaTesser try to create a new app in the Beta channel, add `firebase_cloud` support, then run from Android Studio.

**Comment by TahaTesser** [comment]
@erf  Ths doesn't seem to be related to any package, please check this duplicate https://github.com/flutter/flutter/issues/68486

**Comment by kf6gpe** [comment]
The stack trace here points to the flutter tool, so let's start there. I'm not sure what's actually happening, though.

**Comment by jmagman** [comment]
This should never be happening with the debugger attached as it is in these logs.
Maybe there's a race and `flutter::GetTracingResult() == flutter::TracingResult::kDisabled` is checked too early?
https://github.com/flutter/engine/blob/a82e917dc2bc68a20efca846b8261f65b7d1dd95/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L345

**Comment by jmagman** [comment]
\cc @chinmaygarde

**Comment by jmagman** [comment]
The debugger logs don't show the "Cannot create a FlutterEngine instance in debug mode without Flutter tooling" error so that UI overlay is unnecessarily generated?
https://github.com/flutter/engine/blob/0c7c477245041d02220ae322b3d601eb3cc05bf9/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm#L119

**Comment by jmagman** [comment]
@erf's full log at [log.txt](https://github.com/flutter/flutter/files/5403095/log.txt) shows `--enable-checked-mode` is being passed in, so `EnableTracingManually` shouldn't even be exercised, which actually does the `ptrace` check.
```
executing: script -t 0 /dev/null /Users/erlend/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --id 76dfa318a18803240a229805dd90bcb18d07fef1 --bundle build/ios/iphoneos/Runner.app --debug --no-wifi --args --enable-dart-profiling --enable-service-port-fallback --disable-service-auth-codes --observatory-port=54813 --enable-checked-mode --verify-entry-points
```

**Comment by jlubeck** [comment]
Is there anyway to maybe extend the time out for connecting to the phone or something? I noticed that when I launch from Xcode, the app DOES stay quite a long time with the white screen before getting any kind of logs in the console... 

When I run from Flutter, it gives out this error waaay sooner than it takes Xcode to finish launching the app.

**Comment by TheKashe** [comment]
This was going on with some past versions, I asked the same thing about extending timeout but I don't recall getting an answer. It's ridiculous that such major show-stopper is not properly addressed. I guess it shows that's Google/Android product after all.

**Comment by stx** [comment]
Same problem, logs, stack trace. Started out of nowhere while on beta channel (1.23.0-18.1.pre) with no discernible trigger, but once it started, all builds fail through VS Code and terminal. Works through Xcode.

pod redo, flutter clean, Mac restart, iPhone restart, nothing helps.

**Comment by jmagman** [comment]
> Same problem, logs, stack trace. 

@stx You mean you are also seeing the "In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode." message from `flutter run`?  That's the issue that's being tracked here.  The "Failed to connect directly, falling back to log scanning" message is because the engine isn't starting because it thinks it's being launched without an attached debugger.

If you are NOT seeing that message on your app, please file a new issue and completely fill out the issue template.

**Comment by stx** [comment]
@jmagman No error displayed, same behavior, logs and stack trace. The original issue title is what I'm experiencing on beta. Is that what https://github.com/flutter/flutter/pull/68756 aims to fix, so it's a non-issue moving forward? Or is there no open issue for the original title?

**Comment by jmagman** [comment]
> @jmagman No error displayed, same behavior, logs and stack trace. The original issue title is what I'm experiencing on beta.

You should file a new issue and completely fill out the template.  The "falling back to log scanning" used to indicate the engine hasn't started, which can be for many different reasons, including that your app crashed.  This particular issue is tracking one of those many reasons, and you are hitting a different one.

But first, try #68756 on the master channel, that may clear it up for you, or you may get a more descriptive error.

**Comment by sanekyy** [comment]
Can't run my app in debug mode with `flutter run`.

After start there is empty white screen. Then `Error launching application ` error apears.

After ~10-20 sec app starts.

It looks like Flutter show error after timeout.

**Comment by SCaptainCAP** [comment]
@sanekyy I fixed this by doing the next thing:
Open xCode, click Window -> Devices and Simulators. My IPhone was there with the notice: `IPhone is busy: Copying cache files from device`. I just waited around 2~3 minutes till that text went away, then the flutter error was also fixed. So, it's just some apple's dark magic.

My Iphone: IOS 14.2, My Flutter: channel beta, 1.24.0-10.2.pre

**Comment by sanekyy** [comment]
I fixed this issue via [this](https://developer.apple.com/forums/thread/651012).

It looks like Xcode problem.

**Comment by jmagman** [comment]
@sanekyy @SCaptainCAP I think you are hitting https://github.com/flutter/flutter/issues/67188.  This issue is tracking `In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling` showing up unexpectedly in Debug mode.

**Comment by scaraux** [comment]
I'm having exactly the same issue however it seems to be device specific: all my devices run ios 14 but only one device gives me this issue. I can run debug on every other device I have...

**Comment by glennarixxi** [comment]
I am having the exact same problem, installs from xcode without issue. From VSCode build completes, goes to white screen on install, sits there, then exits with "Error launching application..." Ios 14.3 flutter beta 1.25.0-8.3.pre

**Comment by scaraux** [comment]
If that helps anyone I got that issue and for me the fix was in Xcode:

Product > Scheme > Edit Scheme > Check `Debug Executable`

**Comment by mzafer** [comment]
@glennarixxi, I am having the same issue. Where you able to fix it ?

**Comment by glennarixxi** [comment]
I was able to resolve it, but unfortunately, I cant remember exactly how. I believe it was a combination of running pod install again and completely closing xcode and reopening it. Sorry I don't recall exactly what I did.

**Comment by ch-muhammad-adil** [comment]
Happening with me at flutter 2.0.4,

**Comment by minh-dai** [comment]
+1

**Comment by Garciconx** [comment]
same here with flutter sdk 2.2.3, and show blank screen at launch

**Comment by archi7** [comment]
@Garciconx 

Try running the app from Xcode first. It might show the same blank screen. However, now if you try to run the app using the command "flutter run" your app should work fine.

**Comment by nick92** [comment]
Having the same issue using flutter 2.8.1-stable on iOS 15.2.1

**Comment by riccardocescon** [comment]
Having same issue using flutter 3.3.10 dart 2.18.6 on IOS 16.1, 16.2

**Comment by jmagman** [comment]
This issue is _not_ tracking a blank screen on launch, or anything with copying cache files, or your device being "busy".  It is ONLY tracking that `flutter run` successfully launches the app, but shows a screen "In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling...", which it shouldn't do.  If you are seeing any other problem, please file a new and completely fill out the template.  I'm going to hide any comments that are not about this specific report to avoid confusion.

If you are seeing this issue, please do not respond "me too", give the issue a 👍 reaction and you will be subscribed to updates.

**Comment by sk92129** [comment]
I see this same problem with the current flutter netflix test app.  https://github.com/angjelkom/flutter_netflix.

**Comment by vashworth** [comment]
If you're using iOS 17, you could be experiencing https://github.com/flutter/flutter/issues/136197 which can be fixed ensuring your Xcode settings have Debugging enabled. See instructions here: https://github.com/flutter/flutter/issues/136197#issuecomment-1766566185

**Comment by jmagman** [comment]
@vashworth should this be "fixed" as of your migration https://github.com/flutter/flutter/pull/136977 available in 3.16.0-19.0.pre?

**Comment by vashworth** [comment]
> @vashworth should this be "fixed" as of your migration #136977 available in 3.16.0-19.0.pre?

This issue predated iOS 17, which https://github.com/flutter/flutter/pull/136977 was aimed at fixing. 

Although looking through the comments (see https://github.com/flutter/flutter/issues/68215#issuecomment-767774225) on this issue, perhaps my fix could also work for this - it would need to be updated because currently it only runs the scheme check for iOS 17+ devices.

**Comment by quicksilver812** [comment]
try `flutter run --release`, worked for me.

**Comment by hpelitebook745G2** [comment]
This is still happening with `iOS 17.5.1` and:
```
Flutter 3.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5dcb86f68f (3 weeks ago) • 2024-05-09 07:39:20 -0500
Engine • revision f6344b75dc
Tools • Dart 3.4.0 • DevTools 2.34.3
```

**Comment by wanjm** [comment]
I am interested in how can iOS knows that it is a debug mode flutter app and stop it running?
why does it add such block;
