### ISSUE TITLE
Devicelab agent should retry to upload on failures

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68240]
```

Task failed with the following reason:
ERROR: AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/update-task-status
  HTTP Status: 502
  Response body:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

#0      AuthenticatedClient.send (package:cocoon_agent/src/agent.dart:28:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:176:38)
<asynchronous suspension>
#2      BaseClient.post (package:http/src/base_client.dart:58:7)
#3      Agent._cocoon (package:cocoon_agent/src/agent.dart:84:31)
<asynchronous suspension>
#4      Agent.reportSuccess (package:cocoon_agent/src/agent.dart:149:11)
<asynchronous suspension>
#5      ContinuousIntegrationCommand._runTask (package:cocoon_agent/src/commands/ci.dart:195:19)
<asynchronous suspension>
#6      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:128:21)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1500:12)
#11     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#12     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Deleting build/ directories, if any.
```

**Comment by CaseyHillers** [comment]
When the devicelab is running on LUCI, this will be fixed.
