### ISSUE TITLE
MissingPluginException (No implementation found for method getApplicationDocumentsDirectory)

### ISSUE THREAD

**Issue by yarmel** [flutter/flutter#68286]
When I try to build & install my app on Android I am getting an exception. IOS works.
When I create a new Flutter App & use default options it works, but when I get all my dependencies from pubspec.yaml & then try to build I get an Exception. Already tried different solutions from similar reports but have no luck.

## main.dart
```
import 'dart:io';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  var dir = await getApplicationDocumentsDirectory();
  print(dir);
  
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(body: Center(child: Text('Flutter'),)),
    );
  }
}
```
## Exception
```
E/flutter (19371): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (19371): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (19371): <asynchronous suspension>
E/flutter (19371): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (19371): #2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
E/flutter (19371): #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:104:39)
E/flutter (19371): #4      main (package:octopoos/main.dart:8:19)
E/flutter (19371): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (19371): #6      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (19371): #7      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (19371): #8      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (19371): #9      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (19371): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (19371): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (19371): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (19371): 
```

#### 2. pubspec.yml
```
name: MyApp
description: My test app.

version: 2.1.0+48

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # -> Flutter SDK
  flutter:
    sdk: flutter

  # -> State managment & dependency injection
  provider: ^4.3.2
  get_it: ^5.0.0

  # -> Firebase packages
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  firebase_image: ^0.2.0
  firebase_messaging: ^7.0.2
  cloud_functions: ^0.6.0
  cloud_firestore: ^0.14.0

  # -> Network & connectivity
  http: ^0.12.2
  dio: ^3.0.10
  connectivity: ^0.4.9
  cross_connectivity: ^1.0.1

  # -> Hive local storage
  hive: ^1.4.3
  hive_flutter: ^0.3.1

  # -> Auth packages
  http_auth: ^0.3.0
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  apple_sign_in: ^0.1.0

  # -> UI
  pull_to_refresh: ^1.6.1
  grouped_list: ^3.3.0
  flutter_staggered_grid_view: ^0.3.2
  flutter_sticky_header: ^0.5.0
  loading_indicator: ^1.2.0
  percent_indicator: ^2.1.5
  step_progress_indicator: ^0.2.3+6
  smooth_page_indicator: ^0.2.0

  # -> Forms fields & buttons
  flutter_emoji: ^2.2.1+1
  flutter_form_builder: ^3.14.0
  flutter_progress_button: ^1.0.0
  flutter_webview_plugin: ^0.3.11
  flutter_range_slider: ^1.4.0
  flutter_rating_bar: ^3.0.1+1
  flutter_markdown: ^0.4.4
  smart_select: 3.0.3
  mask_text_input_formatter: ^1.0.7
  place_picker: ^0.9.14
  image_picker: ^0.6.7+7
  share: ^0.6.4+3
  keyboard_dismisser: ^1.0.2
  launch_review: ^2.0.0

  # QR codes
  #  qr_flutter: ^3.2.0
  #  qr_code_scanner: ^0.0.13

  # -> Audio & Video
  youtube_player_flutter: ^7.0.0+7
  wave: ^0.1.0

  # -> Charts
  fl_chart: ^0.12.0
  charts_flutter: ^0.9.0

  # ->  Calendars
  device_calendar: ^3.1.0
  table_calendar: ^2.2.3

  # -> Notifications
  flutter_local_notifications: ^2.0.0

  # -> Images, flare, icons
  cached_network_image: ^2.3.1
  carousel_slider: ^2.2.1
  flutter_svg: ^0.19.0
  flare_flutter: ^2.0.6
  flare_splash_screen: ^3.0.1
  line_icons: ^0.2.0

  # -> Tools
  intl: ^0.16.1
  animate_do: ^1.7.3
  after_layout: ^1.0.7+2
  after_init: ^0.1.2
  flutter_app_badger: ^1.1.2
  permission_handler: ^5.0.1+1
  notification_permissions: ^0.4.7
  faker: ^1.2.1
  path_provider: ^1.6.18
  sortedmap: ^0.4.2+1
  url_launcher: ^5.5.2
  uuid: ^2.2.0
  reorderables: ^0.3.2

  # -> Other packages
  dash_chat: ^1.1.14

  # -> I18n & localizations
  i18n_extension: ^1.4.5
  flutter_localizations:
    sdk: flutter

  # -> Logs
  logs:
    git: https://github.com/pq/logs

# -> Development dependencies
#dev_dependencies:
#  flutter_test:
#    sdk: flutter

# -> Assets
flutter:
  uses-material-design: true
```
#### 3. app/build.grandle
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "app.flutter.education"
        minSdkVersion 17
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            shrinkResources false
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    def multidex_version = "2.0.1"
    implementation "androidx.multidex:multidex:$multidex_version"
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

apply plugin: 'com.google.gms.google-services'

```
#### 4. android/build.grandle
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
#### 5. MainActivity.kt
```
package app.flutter.education

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {}

/// THIS NOT WORK
//import android.os.Bundle
//import android.os.PersistableBundle
//import io.flutter.embedding.android.FlutterActivity
//import io.flutter.embedding.engine.FlutterEngine
//import io.flutter.plugins.GeneratedPluginRegistrant
//
//class MainActivity : FlutterActivity() {
//    override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
//        super.onCreate(savedInstanceState, persistentState)
//        GeneratedPluginRegistrant.registerWith(FlutterEngine(this))
//    }
//}
```
#### 6. AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="app.flutter.education">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.INTERNET"/>

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="education"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

#### flutter doctor 

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale en-UA)
    • Flutter version 1.22.1 at /Users/mayvas/fvm/versions/stable
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mayvas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/mayvas/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
Process finished with exit code 0
```

Thanks

**Comment by darshankawar** [comment]
@yarmel 
Followed your steps to replicate and was able to compile and run your sample code without any issues. I am on latest Stable and used Android 8.1.0 device.

![68286](https://user-images.githubusercontent.com/67046386/96245664-2e9dce80-0fc5-11eb-8a6d-dee8a00772df.png)

One thing I noticed in your steps is that, you have lots of 3rd party plugins in `pubspec.yaml`. I just included `path_provider`. 
Can you try to remove all those plugins, try again to see if you get same error ? If not, then issue could be due to some of the plugins and it's conflict.

**Comment by yarmel** [comment]
> @yarmel
> Followed your steps to replicate and was able to compile and run your sample code without any issues. I am on latest Stable and used Android 8.1.0 device.
> 
> ![68286](https://user-images.githubusercontent.com/67046386/96245664-2e9dce80-0fc5-11eb-8a6d-dee8a00772df.png)
> 
> One thing I noticed in your steps is that, you have lots of 3rd party plugins in `pubspec.yaml`. I just included `path_provider`.
> Can you try to remove all those plugins, try again to see if you get same error ? If not, then issue could be due to some of the plugins and it's conflict.

When I create a new Flutter App & use default options with only path_provider it works. You are completely right! But my app use more than just path_provider & when I upgrade minSdk, grandle ... get an exception

**Comment by darshankawar** [comment]
@yarmel 
That means some of the plugins you are using, may not be compatible. I'd suggest you to keep first party plugins (including all firebase) and try again to see if due to anything of them, is causing the exception. If not, then you might need to check one by one all the 3rd party plugins to know which ones is causing it.

**Comment by yarmel** [comment]
Problem with Facebook Auth & Geolocation picker. When disabled all work fine. One issue resolved & 2 new received :)

**Comment by bm2ilabs** [comment]
Thank you @yarmel

**Comment by Dhi13man** [comment]
For me the issue seems to occur only when I'm trying to combine Hive and Firebase for giving the choice between Local Database (Hive in my case) or Cloud Database (Firestore) to the user, and doesn't occur if I am only using the local Database.

Setting the following in app level `build.gradle` is another viable workaround for anyone facing this with `Gradle version 6+` with `path_provider` and Firebase.

```
android {
    ...

    buildTypes {
        release {
            ...
            minifyEnabled false
            shrinkResources false
        }
    }
}
```

Opinion: I'd guess, the bulkiness of Firebase is messing up the code shrinking in release builds. That is breaking Path Provider, which in my case is breaking Hive.

**Comment by TomeksGitRepo** [comment]
@Dhi13man  fixed my issue with webview_flutter plugin:

Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview

Thank u so much
