### ISSUE TITLE
Unhandled Exception: Bad state: Insecure HTTP is not allowed by platform

### ISSUE THREAD

**Issue by ishaileshmishra** [flutter/flutter#68294]
Unhandled Exception: Bad state: Insecure HTTP is not allowed by the platform 

When making an HTTP request using the iPhone simulator getting the above error.

**To Reproduce:**.  _Error Log_

```
[ VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Bad state: Insecure HTTP is not allowed by platform: http://asralokkalyan.in/user/login
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2435:7)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2342:7)
#2      IOClient.send
package:http/src/io_client.dart:31
#3      BaseClient._sendUnstreamed
package:http/src/base_client.dart:91
#4      BaseClient.post
package:http/src/base_client.dart:32
#5      post.<anonymous closure>
package:http/http.dart:70
#6      _withClient
package:http/http.dart:166
#7      post
package:http/http.dart:69
#8      _LoginPageState._validateCredentials
package:alok/…/login/LoginPage.dart:36
#9      _LoginPageState._onBtnPressed
package:alok/…/login/LoginPage.dart:164
#10     _LoginPageState._btnSignIn.<anonymous closure>
package:alok/…/login/LoginPage.dart:250
#11     _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:985
#12    <…>

```

**Comment by darshankawar** [comment]
@ishaileshmishra 
This is an expected behavior. Android and iOS now don't allow insecure http connections and have been disabled by default.
See [this](https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android) link for more details.
Closing as non-issue.
