### ISSUE TITLE
AppBar: The getter 'height' was called on null.

### ISSUE THREAD

**Issue by jpeiffer** [flutter/flutter#68308]
This appears to be a regression.  It worked with `1.23.0-4.0.pre` and is now failing on `1.23.0-18.0.pre`.  The relevant line appears to be missing a `?` after `preferredSize`.

I grabbed the line from both versions and can confirm this is the issue:

**1.23.0-4.0.pre**
```dart
preferredSize = Size.fromHeight(toolbarHeight ?? kToolbarHeight + (bottom?.preferredSize?.height ?? 0.0)),

```

**1.23.0-18.0.pre**
```dart
preferredSize = Size.fromHeight(toolbarHeight ?? kToolbarHeight + (bottom?.preferredSize.height ?? 0.0)),
//                                                                                   ---^
```

## Steps to Reproduce

Include a `PreferredSize` widget at the bottom of an App Bar with a `null` preferred size.  Example:

```dart
AppBar(
  title: Text(title),
  bottom: PreferredSize(
    preferredSize: null,
    child: Text(subTitle),
  ),
),
```

**Expected results:**

The subtitle to appear under the title

**Actual results:** 

Red screen of death with the message:
```
flutter: The getter 'height' was called on null.
flutter: Receiver: null
flutter: Tried calling: height
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
flutter: #1      new AppBar (package:flutter/src/material/app_bar.dart:216:97)
```

```
```
<details>

```
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.23.0-18.0.pre at /Users/jpeiffer/flutter
    • Framework revision 37ebe3d82a (3 days ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jpeiffer/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/jpeiffer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1
```

</details>

**Comment by sidrao2006** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
Why are you setting `preferredSize` to null in the first place? As far as I can tell that's not a legal value for preferredSize?

**Comment by jpeiffer** [comment]
It's one of the recommended answers in this SO question:
https://stackoverflow.com/questions/53880293/flutter-how-to-get-subtext-aligned-under-title-in-appbar/53880971

Prior to this issue, it works to show a subtitle underneath a centered title.

**Comment by pedromassangocode** [comment]
Hi @jpeiffer 
As said above, null is not a valid value for the preferredSize parameter and with NNBD you will not be allowed to pass null in it and that is why you are getting this message.

You can set the size zero to fix this.

```dart
    return Scaffold(
      appBar: AppBar(
        title: Text("Title"),
        bottom: PreferredSize(
          preferredSize: Size.fromHeight(0),
          child: Text("ahahhaa"),
        ),
      ),
    );
```

I'm closing this as this is working as expected.

**Comment by jpeiffer** [comment]
Thanks for adding that.  I went ahead and fixed my stuff based on your feedback.

Do you think this should be an `assert` rather than a NPE?  At least from my perspective, that would have made it more clear it was intentional rather than a breaking change.

**Comment by pedromassangocode** [comment]
> Do you think this should be an `assert` rather than a NPE? At least from my perspective, that would have made it more clear it was intentional rather than a breaking change.

This will get fixed with Null Safety. Basically null safety will prevent users to pass null as value for this parameter.
