### ISSUE TITLE
Exception while opening Alert dialog from list item selection in second page.

### ISSUE THREAD

**Issue by nareshkatta99** [flutter/flutter#68300]
Error log:
```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons ==
kPrimaryButton': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:379:12)
#3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:310:7)
#4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#5      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#7      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#8      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#9      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#13     _invoke1 (dart:ui/hooks.dart:267:10)
#14     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 5 frames from class _AssertionError and dart:async)

Event:
  PointerUpEvent#2632a(position: Offset(0.0, 736.0))
Target:
  <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
```

Sample code:
```
    import 'dart:math';
    import 'package:flutter/gestures.dart';
    import 'package:flutter/material.dart';
    import 'package:intl/intl.dart';
    
    void main() {
      runApp(MyApp());
    }
    
    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.blue,
            visualDensity: VisualDensity.adaptivePlatformDensity,
          ),
          home: MyFirstPage(title: 'List Bug Check'),
        );
      }
    }
    
    class MyFirstPage extends StatelessWidget {
      MyFirstPage({Key key, this.title}) : super(key: key);
    
      final String title;
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          appBar: AppBar(
            title: Text(title),
          ),
          body: Container(
            child: Center(
              child: RaisedButton(
                child: Text("Press here"),
                onPressed: () {
                  Navigator.push(
                      context, MaterialPageRoute(
                      builder: (_) => MySecondPage(title: title,)));
                },
              ),
            ),
          ),
        );
      }
    }
    
    class MySecondPage extends StatefulWidget {
      MySecondPage({Key key, this.title}) : super(key: key);
    
      final String title;
    
      @override
      _MySecondPageState createState() => _MySecondPageState();
    }
    
    class _MySecondPageState extends State<MySecondPage> {
      DateTime dateTime;
    
      @override
      Widget build(BuildContext context) {
        dateTime = DateTime.now();
        return Scaffold(
          appBar: AppBar(
            title: Text(widget.title),
          ),
          body: ListView.builder(
              itemCount: 20,
              itemBuilder: (context, index) {
                return MyCard(
                  dateTime: dateTime.add(Duration(days: 1)),
                );
              }),
        );
      }
    }
    
    class MyCard extends StatelessWidget {
      final DateTime dateTime;
      final number = Random.secure().nextInt(10) + 5;
    
      MyCard({Key key, this.dateTime}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return Column(
          children: [
            SizedBox(
              height: 10,
            ),
            Card(
              elevation: 5,
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Row(
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                            "${DateFormat("dd MMM yyyy hh:mm a").format(
                                dateTime)}"),
                        SizedBox(height: 5),
                        RichText(
                            text: TextSpan(
                              style: Theme
                                  .of(context)
                                  .textTheme
                                  .subtitle2
                                  .copyWith(
                                decoration: TextDecoration.underline,
                              ),
                              children: [
                                TextSpan(
                                    text: "$number members",
                                    recognizer: TapGestureRecognizer()
                                      ..onTap = () => _membersDialog(context)),
                                TextSpan(
                                    text: " Attended",
                                    style: Theme
                                        .of(context)
                                        .textTheme
                                        .subtitle2),
                              ],
                            ))
                      ],
                    ),
                  ],
                ),
              ),
            )
          ],
        );
      }
    
      _membersDialog(BuildContext context) {
        showDialog<void>(
          context: context,
          builder: (context) {
            return AlertDialog(
              title: Text("${DateFormat("dd MMM yyyy hh:mm a").format(dateTime)}"),
              content: _participantList(number, context),
              actions: [
                FlatButton(
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                  child: Text("Close"),
                )
              ],
            );
          },
        );
      }
    
      Widget _participantList(int count, context) {
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: List.generate(
              count * 2,
                  (index) =>
              index % 2 == 0
                  ? Row(
                children: [
                  SizedBox(
                    width: 12,
                  ),
                  Text("User ${(index / 2).floor() + 1}"),
                ],
              )
                  : SizedBox(
                height: 12,
              )),
        );
      }
    }
```

**Comment by darshankawar** [comment]
@nareshkatta99 
Tried your code sample on latest dev using Android Samsung Galaxy 8.1.0 device. I don't see the exception while opening any of the alert dialog from list items. I just see below overflow exception on few alert dialogs but that is implementation issue, not thrown by framework.

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 69 pixels on the bottom.

The relevant error-causing widget was: 
  Column file:///Users/dhs/Documents/NCFlutter/newweb/lib/main.dart:161:12
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

```
[68300.mp4.zip](https://github.com/flutter/flutter/files/5391806/68300.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Mac OS X 10.15.4 19E2269 x86_64,
    locale en-IN)
    • Flutter version 1.23.0-7.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision db6e2d8aa5 (3 weeks ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 x86_64
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.80

• No issues found!

```

</details>

Please provide concrete steps to replicate as when do you see the original exception you are getting, along with `flutter doctor -v` output and devices on which you are seeing the issue. Otherwise, it doesn't seem to be related to framework, but with your code implementation.
Thanks.

**Comment by sidrao2006** [comment]
Possible duplicate of #68296

**Comment by nareshkatta99** [comment]
> @nareshkatta99
> Tried your code sample on latest dev using Android Samsung Galaxy 8.1.0 device. I don't see the exception while opening any of the alert dialog from list items. I just see below overflow exception on few alert dialogs but that is implementation issue, not thrown by framework.
> 
> ```
> ════════ Exception caught by rendering library ═════════════════════════════════════════════════════
> The following assertion was thrown during layout:
> A RenderFlex overflowed by 69 pixels on the bottom.
> 
> The relevant error-causing widget was: 
>   Column file:///Users/dhs/Documents/NCFlutter/newweb/lib/main.dart:161:12
> The overflowing RenderFlex has an orientation of Axis.vertical.
> The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

The issue coming while using iOS.

**Comment by nareshkatta99** [comment]
I ran the code using Xcode, the issue is not coming in that way. 
I really don't know what causing the issue, but closing the issue for now.

<details>
  <summary>flutter doctor -v:</summary>

[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.1 at /Users/Shared/flutter
    • Framework revision f30b7f4db9 (8 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/nareshkatta/Android/SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/nareshkatta/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone 8 Plus (mobile) • C34CA149-89A0-4B8C-99C9-40C89AC21FD0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

! Doctor found issues in 1 category.
</details>

In case if needed.
