### ISSUE TITLE
Unable to run flutter run --profile on iOS device

### ISSUE THREAD

**Issue by JagandeepBrar** [flutter/flutter#68375]
I am unable to run `flutter run --profile` for my application, although `flutter run` and `flutter run --release` both work as expected.

Some details on my machine/device/installation:
- MacOS 11.0 Beta (20A5395g, latest)
- iOS 14.2 (Developer beta 3, latest)

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on macOS 11.0 20A5395g x86_64, locale en-CA)
    • Flutter version 1.23.0-18.1.pre at /Users/jagandeepbrar/Development/flutter
    • Framework revision 198df796aa (31 hours ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5018i
    • CocoaPods version 1.8.4
```

It builds the application without issue, but fails after the installation. I can see the application's splash screen on the phone for 5-10 seconds before Flutter eventually exits with an error. After Flutter exits, the application actually finishes launching and appears to work without issue.

Running `flutter run --profile --verbose` results in this final error:

```
[   +1 ms] Installing and launching... (completed in 29.3s)
[        ] Error running application on Jagandeep’s iPhone.
[   +5 ms] "flutter run" took 161,093ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:618:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1005:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +217 ms] ensureAnalyticsSent: 215ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 2
```

**Comment by JagandeepBrar** [comment]
Closing this issue and linking it in #67840 which appears to be the same issue.
