### ISSUE TITLE
Flutter and android-studio snaps update on Ubuntu Java >= 11 or gradle > 5

### ISSUE THREAD

**Issue by lapisdecor** [flutter/flutter#68387]
## Steps to Reproduce

1. I had flutter and android studio running well before the last update, flutter doctor was all green. (snaps)
2. Ubuntu 20.04 updated the snaps
2a) Android studio didn't reset (it assumed prior configurations)
3. I updated the dart and flutter plugins on android studio
4. Flutter didn't run anymore on android-studio.
5. After a lot of setting/unseting $JAVA_HOME, and changing Gradle and JAVA versions I came to the following conclusions:
- new version of flutter only worked with open-jdk, not oracle java
- it worked with java 11 but not with java 14
- or it worked with 14 if I set gradle manually to version > 6
- now it's working but even now flutter doctor says I don't have the licenses accepted. 

## Logs

```flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Linux, locale pt_PT.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

`flutter doctor --android-licenses`
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

```
Current configuration with android studio working and flutter working but no licenses:

```flutter doctor -v
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Linux, locale pt_PT.UTF-8)
    • Flutter version 1.23.0-18.0.pre at /home/luis/snap/flutter/common/flutter
    • Framework revision 37ebe3d82a (4 days ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/luis/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-post-Ubuntu-0ubuntu120.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.

```

**Comment by BerlinLion** [comment]
I have exactly the same issue

**Comment by hamdikahloun** [comment]
Hi @lapisdecor 

Can you try with JDK 8 please : 

- `sudo apt install openjdk-8-jre-headless`

-  Update your `$JAVA_HOME`

- `flutter doctor --android-licenses`

**Comment by lapisdecor** [comment]
```
luis@u18:~$ sudo apt install openjdk-8-jre-headless 
[sudo] senha para luis: 
A ler as listas de pacotes... Pronto
A construir árvore de dependências       
A ler a informação de estado... Pronto
Pacotes sugeridos:
  fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho
  fonts-wqy-microhei fonts-wqy-zenhei
Serão instalados os seguintes NOVOS pacotes:
  openjdk-8-jre-headless
0 pacotes actualizados, 1 pacotes novos instalados, 0 a remover e 3 não actualizados.
É necessário obter 27,5 MB de arquivos.
Após esta operação, serão utilizados 101 MB adicionais de espaço em disco.
Obter:1 http://pt.archive.ubuntu.com/ubuntu focal-updates/universe amd64 openjdk-8-jre-headless amd64 8u265-b01-0ubuntu2~20.04 [27,5 MB]
Obtidos 27,5 MB em 14s (1944 kB/s)                                             
A seleccionar pacote anteriormente não seleccionado openjdk-8-jre-headless:amd64
.
(A ler a base de dados ... 250354 ficheiros e directórios actualmente instalados
.)
A preparar para desempacotar .../openjdk-8-jre-headless_8u265-b01-0ubuntu2~20.04
_amd64.deb ...
A descompactar openjdk-8-jre-headless:amd64 (8u265-b01-0ubuntu2~20.04) ...
A instalar openjdk-8-jre-headless:amd64 (8u265-b01-0ubuntu2~20.04) ...
update-alternatives: a usar /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/orbd para 
disponibilizar /usr/bin/orbd (orbd) em modo auto
update-alternatives: a usar /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/servertool
 para disponibilizar /usr/bin/servertool (servertool) em modo auto
update-alternatives: a usar /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/tnameserv 
para disponibilizar /usr/bin/tnameserv (tnameserv) em modo auto
update-binfmts: warning: current package is openjdk-11, but binary format alread
y installed by openjdk-14
luis@u18:~$ which java
/usr/bin/java
luis@u18:~$ echo $JAVA_HOME

luis@u18:~$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
luis@u18:~$ flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
luis@u18:~$ whereis java
java: /usr/bin/java /usr/share/java /usr/share/man/man1/java.1.gz
luis@u18:~$ micro .basrc
luis@u18:~$ cd
luis@u18:~$ micro .bashrc
luis@u18:~$ source .bashrc
luis@u18:~$ whereis java
java: /usr/bin/java /usr/share/java /usr/share/man/man1/java.1.gz
luis@u18:~$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64

luis@u18:~$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

luis@u18:~$ sudo apt remove openjdk-11-jre-headless 
[sudo] senha para luis: 
A ler as listas de pacotes... Pronto
A construir árvore de dependências       
A ler a informação de estado... Pronto
Serão REMOVIDOS os seguintes pacotes:
  default-jre-headless openjdk-11-jre-headless
0 pacotes actualizados, 0 pacotes novos instalados, 2 a remover e 3 não actualizados.
Após esta operação, será libertado 171 MB de espaço em disco.
Deseja continuar? [S/n] 
(A ler a base de dados ... 250585 ficheiros e directórios actualmente instalados
.)
...

uis@u18:~$ java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
luis@u18:~$ which java
/usr/bin/java
luis@u18:~$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
luis@u18:~$ flutter doctor --android-licenses
Warning: File /home/luis/.android/repositories.cfg could not be loaded.         
4 of 6 SDK package licenses not accepted. 100% Computing updates...             
Review licenses that have not been accepted (y/N)? y

1/4: License android-googletv-license:
---------------------------------------
Terms and Conditions

This is the Google TV Add-on for the Android Software Development Kit License Agreement.

1. Introduction

1.1 The Google TV Add-on for the Android Software Development Kit (referred to in this License Agreement as the "Google TV Add-on" and specifically including the Android system files, packaged APIs, and Google APIs add-ons) is licensed to you subject to the terms of this License Agreement. This License Agreement forms a legally binding contract between you and Google in relation to your use of the Google TV Add-on.
(...)
---------------------------------------
Accept? (y/N): y
All SDK package licenses accepted

luis@u18:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Linux, locale pt_PT.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by lapisdecor** [comment]
on the other side of the road, what happens now on android-studio:

```
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Kotlin could not find the required JDK tools in the Java installation '/usr/lib/jvm/java-8-openjdk-amd64/jre' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by hamdikahloun** [comment]
Hi @lapisdecor 
Can you try : 
```
sudo apt install openjdk-8-jdk

To switch between version execute the following two commands while selecting the Java version you require:
sudo update-alternatives --config java
sudo update-alternatives --config javac
```

**Comment by lapisdecor** [comment]
but on the desktop side:
```

luis@u18:~/AndroidStudioProjects/flutter_app6527$ flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Waiting for Linux to report its views...                             3ms
Syncing files to device Linux...                                   159ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Linux is available at:
http://127.0.0.1:34945/IToY4Tl0Eg8=/
Lost connection to device.
```
it works ok

**Comment by lapisdecor** [comment]
```
luis@u18:~$ sudo apt install openjdk-8-jdk
[sudo] senha para luis: 
A ler as listas de pacotes... Pronto
A construir árvore de dependências       
A ler a informação de estado... Pronto
The following additional packages will be installed:
  fonts-dejavu-extra libatk-wrapper-java libatk-wrapper-java-jni libxt-dev
( ....)
luis@u18:~$ flutter doctor -v
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Linux, locale pt_PT.UTF-8)
    • Flutter version 1.23.0-18.0.pre at /home/luis/snap/flutter/common/flutter
    • Framework revision 37ebe3d82a (4 days ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/luis/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.
luis@u18:~$ sudo update alternatives --config java
sudo: update: comando não encontrado
luis@u18:~$ sudo update-alternatives --config java
Existe apenas uma alternativa no grupo de ligação java (que disponibiliza /usr/bin/java: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
Nada para configurar.

luis@u18:~$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
```

Same result. I wonder why it worked on android-studio with no JAVA_HOME exported when using the java 11 I had by 'default'.

Now android-studio just says:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Kotlin could not find the required JDK tools in the Java installation '/usr/lib/jvm/java-8-openjdk-amd64/jre' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

NOTE: When I say I test android studio, I'm testing it on the emulator, not desktop.

**Comment by lapisdecor** [comment]
Removing the export JAVA_HOME everithing works, except flutter doctor doesn't recognize Android Studio is installed

```
luis@u18:~$ echo $JAVA_HOME

luis@u18:~$ which java
/usr/bin/java
luis@u18:~$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
luis@u18:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Linux, locale pt_PT.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.


```

**Comment by hamdikahloun** [comment]
If you have Android Studio 4.1 ,This was reported in #67986, should be fixed soon in the stable channel with cherry-pick release.
You can try this too : https://github.com/flutter/flutter/issues/67986#issuecomment-709598076

**Comment by lapisdecor** [comment]
Nice one, I think I'll wait for the fix thow. Thank you.

**Comment by pedromassangocode** [comment]
Hi @lapisdecor 
Given your last comment I feel safe to close this issue.
Thank you

**Comment by vladaman** [comment]
I must agree that installing flutter from snap on fresh Ubuntu 20.04 has several issues. Getting it up and running requires quite a few steps. My list of issues:

- Android Studio has no Android CLI tools SDK installed by default (needed to accept licenses, otherwise you get XmlSchema exception
- Had to manually locate dart-sdk folder and configure Project settings in Android Studio
- flutter doctor was reporting the Android studio is not installed. Had to run flutter config --android-studio-dir=/home/user/Software/android-studio/ (my installation folder)
- Android Studio is missing Menu option "Open for editing in Android Studio"
