### ISSUE TITLE
flutter run -d edge   ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#68417]
## Steps to Reproduce
1) **flutter run -d edge** 
-d edge does not work, (-d chrome and  -d web-server do work)

C:\XXXX>flutter run
Multiple devices found:
Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.19041.572]
Web Server (web)  • web-server • web-javascript • Flutter Tools
Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.75
Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.43
[0]: Windows (windows)
[1]: Web Server (web-server)
[2]: Chrome (chrome)
[3]: Edge (edge)
Please choose one (To quit, press "q/Q"): 3
Launching lib\main.dart on Edge in debug mode...
Syncing files to device Edge...                                     8,4s
Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using
-d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.

## **Logs**

```
C:\Users\XXXX>flutter run -d edge --verbose
[ +109 ms] executing: [C:\XXXX\flutter/] git -c log.showSignature=false log -n
1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4aa1154b09bb39bf8d2c8240f1a83a161ed851b8
[        ] executing: [C:\XXXXflutter/] git tag --points-at HEAD
[  +44 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [C:\XXXX\flutter/] git describe --match *.*.*
--first-parent --long --tags
[  +63 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.23.0-18.0.pre-90-g4aa1154b09
[   +8 ms] executing: [C:\XXXX\flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\XXXX\flutter/] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +63 ms] executing: [C:\XXXXfsdk\flutter/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] executing: C:\Users\bened\Desktop\bmcmob\asdk\platform-tools\adb.exe devices -l
[  +47 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +62 ms] executing: C:\XXXX\platform-tools\adb.exe devices -l
[ +136 ms] Generating
C:\Users\XXXX\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRe
gistrant.java
[  +93 ms] Launching lib\main.dart on Edge in debug mode...
[  +28 ms] List of devices attached
[  +67 ms] List of devices attached
[  +14 ms] Updating assets
[  +81 ms] Syncing files to device Edge...
[  +37 ms] Generating
C:\Users\XXXX\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRe
gistrant.java
[  +80 ms] <- reset
[   +6 ms] C:\XXXX\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\XXXX\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.sn
apshot --sdk-root C:\XXXX\flutter\bin\cache\flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\XXXXAppData\Local\Temp\flutter_tools.4e14d35c\flutter_tool.709f372\app.dill --libraries-spec
file:///C:/XXXXflutter/bin/cache/flutter_web_sdk/libraries.json --packages
.packages -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root C:\XXXX\AppData\Local\Temp\flutter_tools.4e14d35c\flutter_tools.d74257c6
--filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill.track.dill --platform
file:///C:/XXXX/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +10 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+8484 ms] Syncing files to device Edge... (completed in 8,6s)
[   +1 ms] Synced 27.7MB.
[   +1 ms] <- accept
[        ] Caching compiled dill
[ +544 ms] Using
[ +532 ms] Failed to launch browser. Command used to launch it: C:\Program Files
(x86)\Microsoft\Edge\Application\msedge.exe
--user-data-dir=C:\XXXX\AppData\Local\Temp\flutter_tools.4e14d35c\flutter_tools_chrome_device.e8bd
b8d4 --remote-debugging-port=56017 --disable-background-timer-throttling --disable-extensions
--disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps
--disable-translate http://localhost:56001
[   +9 ms] "flutter run" took 10 332ms.
[  +10 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise,
consider using
           -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.
[   +6 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure>
           (package:flutter_tools/src/web/chrome.dart:278:11)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1414:9)
           #3      _rootRun (dart:async/zone.dart:1182:47)
           #4      _CustomZone.run (dart:async/zone.dart:1093:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:101:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:165:13)
           #11     _rootRun (dart:async/zone.dart:1182:47)
           #12     _CustomZone.run (dart:async/zone.dart:1093:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #21     _SinkTransformerStreamSubscription._handleDone
(dart:async/stream_transformers.dart:142:24)
           #22     _rootRun (dart:async/zone.dart:1182:47)
           #23     _CustomZone.run (dart:async/zone.dart:1093:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
           #33     _SinkTransformerStreamSubscription._handleDone
(dart:async/stream_transformers.dart:142:24)
           #34     _rootRun (dart:async/zone.dart:1182:47)
           #35     _CustomZone.run (dart:async/zone.dart:1093:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:664:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:1976:21)
           #44     _rootRunUnary (dart:async/zone.dart:1206:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:682:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:624:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1512:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1010:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[  +81 ms] ensureAnalyticsSent: 74ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[ +366 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
C:\XXXX>
```

```
C:\xxxx>flutter doctor -v
[√] Flutter (Channel master, 1.23.0-19.0.pre.90, on Microsoft Windows [version 10.0.19041.572], locale fr-FR)
    • Flutter version 1.23.0-19.0.pre.90 at C:\xxxxk\flutter
    • Framework revision 4aa1154b09 (24 hours ago), 2020-10-16 19:17:05 -0400
    • Engine revision d03b759d04
    • Dart version 2.11.0 (build 2.11.0-229.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\xxxx\asdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\xxxx
    • Java binary at: C:\xxxx\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\xxxx\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\xxxxCommunity
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\xxxx
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\xxxx\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.19041.572]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 86.0.622.43

• No issues found!
```

**Comment by Abhishek01039** [comment]
Hi @benedicte69 
```
 "flutter run" took 10 332ms.
[  +10 ms] Failed to launch the browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise,
consider using
```
please update your edge then try 
Thanks

**Comment by darshankawar** [comment]
@benedicte69 
Per error log as above, please check if you are using uptodate Edge browser. If not, try to upgrade to latest and run again to see if it works.

**Comment by darshankawar** [comment]
May be related to https://github.com/flutter/flutter/issues/45162, https://github.com/flutter/flutter/issues/54607

**Comment by benedicte69** [comment]
Sorry but my Edge Chromium is up to date:
Microsoft Edge est à jour.
Version 86.0.622.43 (Version officielle) (64 bits)

**Comment by darshankawar** [comment]
@benedicte69 This looks similar to [54607](https://github.com/flutter/flutter/issues/54607) where devs are saying it's not working in New Edge as well as Legacy Edge browser.
Are you using New Edge or Legacy ?
Thanks.

**Comment by benedicte69** [comment]
@darshankawar I am using the new Microsoft Edge based on Chromium. I have downloaded it a few months ago. Microsoft in a future update is going to settle it 'everywhere. 
I did download it because if I copied the local 'URL' it could display the app which was not the case with the legacy one. So it can read a flutter app. 
The problem is the command line flutter run -d edge which does not work. Edge chromium is totally able to read now a flutter app but it is impossible to launch it with -d edge.

**Comment by benedicte69** [comment]
Hope it helps

**Comment by darshankawar** [comment]
@benedicte69 
@TahaTesser just tried on latest master and dev and he was able to run on Edge browser without any issues.

![image](https://user-images.githubusercontent.com/67046386/96597038-fc64d780-130a-11eb-8aff-f6b52cfff608.png)

Can you try to debug it more from your side and see why it may not be running ?

**Comment by benedicte69** [comment]
You dit it with the cmd: flutter run -d edge?
    Le mardi 20 octobre 2020 à 16:06:35 UTC+2, darshankawar <notifications@github.com> a écrit :  
 
 


@benedicte69
@TahaTesser just tried on latest master and dev and he was able to run on Edge browser without any issues.



Can you try to debug it more from your side and see why it may not be running ?

**Comment by darshankawar** [comment]
@benedicte69 That is correct.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by benedicte69** [comment]
I am the one who is waiting for additional information
    Le mercredi 11 novembre 2020 à 11:23:31 UTC+1, Pedro Massango <notifications@github.com> a écrit :  
 
 


Without additional information, we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of flutter doctor -v.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
