### ISSUE TITLE
 Failed assertion: line 582 pos 12: '_pendingDimensions': is not true.

### ISSUE THREAD

**Issue by karmelcorn** [flutter/flutter#68415]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialClassicHeader file:///Users/chui/Developer/FlutterApps/asp/lib/widgets/product/product_list.dart:183:17
When the exception was thrown, this was the stack: 
#2      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:582:12)
#3      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:108:11)
#4      RenderSliverRefresh.performLayout (package:pull_to_refresh/src/internals/slivers.dart:165:39)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#6      RenderSliverRefresh.layout (package:pull_to_refresh/src/internals/slivers.dart:147:13)
...
The following RenderObject was being processed when the exception was fired: RenderSliverRefresh#841e2 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 477.0, crossAxisExtent: 327.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 477.0, remainingCacheExtent: 977.0, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
...    scrollExtent: 0.0
...    hidden
...    maxPaintExtent: 0.0
RenderObject: RenderSliverRefresh#841e2 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 477.0, crossAxisExtent: 327.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 477.0, remainingCacheExtent: 977.0, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
    scrollExtent: 0.0
    hidden
    maxPaintExtent: 0.0
...  child: RenderRotatedBox#c9891 relayoutBoundary=up2 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=327.0, 0.0<=h<=Infinity)
...    size: Size(327.0, 48.0)
...    child: RenderFractionalTranslation#d48f4 relayoutBoundary=up3 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=327.0, 0.0<=h<=Infinity)
...      size: Size(327.0, 48.0)
...      translation: Offset(0.0, -1.0)
...      transformHitTests: true
...      child: RenderTransform#692f2 relayoutBoundary=up4 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=327.0, 0.0<=h<=Infinity)
...        size: Size(327.0, 48.0)
...        transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderPositionedBox#a149b relayoutBoundary=up5 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=327.0, 0.0<=h<=Infinity)
...          size: Size(327.0, 48.0)
...          alignment: topCenter
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: product.type external
flutter: [talon, restraints, tri-fold-restraints, products, available-for-discount, new-products, bundles, ws-batons, ws-restraints, kits]
flutter: 1
flutter: 0
flutter: 10

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12: '_pendingDimensions': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialClassicHeader file:///Users/chui/Developer/FlutterApps/asp/lib/widgets/product/product_list.dart:183:17
When the exception was thrown, this was the stack: 
#2      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:582:12)
#3      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:108:11)
#4      RenderSliverRefresh.performLayout (package:pull_to_refresh/src/internals/slivers.dart:165:39)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#6      RenderSliverRefresh.layout (package:pull_to_refresh/src/internals/slivers.dart:147:13)
...
The following RenderObject was being processed when the exception was fired: RenderSliverRefresh#841e2 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 477.0, crossAxisExtent: 327.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 477.0, remainingCacheExtent: 977.0, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
...    scrollExtent: 0.0
...    hidden
...    maxPaintExtent: 0.0
RenderObject: RenderSliverRefresh#841e2 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 477.0, crossAxisExtent: 327.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 477.0, remainingCacheExtent: 977.0, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
    scrollExtent: 0.0
    hidden
    maxPaintExtent: 0.0
...  child: RenderRotatedBox#c9891 relayoutBoundary=up2 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=327.0, 0.0<=h<=Infinity)
...    size: Size(327.0, 48.0)
...    child: RenderFractionalTranslation#d48f4 relayoutBoundary=up3 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=327.0, 0.0<=h<=Infinity)
...      size: Size(327.0, 48.0)
...      translation: Offset(0.0, -1.0)
...      transformHitTests: true
...      child: RenderTransform#692f2 relayoutBoundary=up4 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=327.0, 0.0<=h<=Infinity)
...        size: Size(327.0, 48.0)
...        transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderPositionedBox#a149b relayoutBoundary=up5 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=327.0, 0.0<=h<=Infinity)
...          size: Size(327.0, 48.0)
...          alignment: topCenter
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

**Comment by karmelcorn** [comment]
got the above error after upgrading to Flutter version 1.22.2 

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.22.2 at /Users/Developer/flutter
    • Framework revision 84f3d28555 (2 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • iPhone (mobile) • d023e150d07d2cf5ac85e62df210f2f9585264cc • ios • iOS 13.5
    • iPhone 8 (mobile)      • 79225A3E-D2A9-4D7A-AE8D-BB54930E1AE1     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

**Comment by karmelcorn** [comment]
Error was due to third party plugin pull_to_refresh. fixed after updating to the latest version.
