### ISSUE TITLE
When the exception was thrown, this was the stack:

### ISSUE THREAD

**Issue by alin25730** [flutter/flutter#68425]
May I ask how to solve this 
```
: #0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:100:9)
I/flutter ( 5079): <asynchronous suspension>
I/flutter ( 5079): #1      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:51:14)
I/flutter ( 5079): #2      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:505:13)
I/flutter ( 5079): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:360:22)
I/flutter ( 5079): #4      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:503:80)
I/flutter ( 5079): #5      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:108:19)
I/flutter ( 5079): #6      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:334:9)
I/flutter ( 5079): #7      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:464:26)
I/flutter ( 5079): #8      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43:29)
I/flutter ( 5079): #9      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:461:11)
I/flutter ( 5079): #13     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:453:16)
I/flutter ( 5079): #14     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:331:5)
I/flutter ( 5079): #15     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1116:16)
I/flutter ( 5079): #16     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1069:5)
I/flutter ( 5079): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4738:12)
I/flutter ( 5079): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4553:5)
I/flutter ( 5079): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3524:14)
I/flutter ( 5079): #20     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6069:32)
I/flutter ( 5079): ...     Normal element mounting (71 frames)
I/flutter ( 5079): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3524:14)
I/flutter ( 5079): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3283:18)
I/flutter ( 5079): #93     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1164:36)
I/flutter ( 5079): #94     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1082:34)
I/flutter ( 5079): #95     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1127:23)
I/flutter ( 5079): #96     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1052:7)
I/flutter ( 5079): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #100    ProxyElement.update (package:flutter/src/widgets/framework.dart:4937:5)
I/flutter ( 5079): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #104    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5613:32)
I/flutter ( 5079): #105    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6080:17)
I/flutter ( 5079): #106    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:213:11)
I/flutter ( 5079): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #115    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #116    StatelessElement.update (package:flutter/src/widgets/framework.dart:4659:5)
I/flutter ( 5079): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #123    StatefulElement.update (package:flutter/src/widgets/framework.dart:4786:5)
I/flutter ( 5079): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #129    StatelessElement.update (package:flutter/src/widgets/framework.dart:4659:5)
I/flutter ( 5079): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #133    ProxyElement.update (package:flutter/src/widgets/framework.dart:4937:5)
I/flutter ( 5079): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #135    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #137    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #141    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #144    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #145    StatelessElement.update (package:flutter/src/widgets/framework.dart:4659:5)
I/flutter ( 5079): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #148    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #149    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #150    StatefulElement.update (package:flutter/src/widgets/framework.dart:4786:5)
I/flutter ( 5079): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #153    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #155    StatefulElement.update (package:flutter/src/widgets/framework.dart:4786:5)
I/flutter ( 5079): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #159    ProxyElement.update (package:flutter/src/widgets/framework.dart:4937:5)
I/flutter ( 5079): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #163    StatelessElement.update (package:flutter/src/widgets/framework.dart:4659:5)
I/flutter ( 5079): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #167    StatelessElement.update (package:flutter/src/widgets/framework.dart:4659:5)
I/flutter ( 5079): #168    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #169    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #170    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #171    ProxyElement.update (package:flutter/src/widgets/framework.dart:4937:5)
I/flutter ( 5079): #172    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #174    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #175    ProxyElement.update (package:flutter/src/widgets/framework.dart:4937:5)
I/flutter ( 5079): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #177    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5613:32)
I/flutter ( 5079): #178    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6080:17)
I/flutter ( 5079): #179    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #181    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #182    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #183    StatefulElement.update (package:flutter/src/widgets/framework.dart:4786:5)
I/flutter ( 5079): #184    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #186    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #187    ProxyElement.update (package:flutter/src/widgets/framework.dart:4937:5)
I/flutter ( 5079): #188    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #190    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #192    StatefulElement.update (package:flutter/src/widgets/framework.dart:4786:5)
I/flutter ( 5079): #193    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #194    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #198    StatelessElement.update (package:flutter/src/widgets/framework.dart:4659:5)
I/flutter ( 5079): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #200    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5950:14)
I/flutter ( 5079): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #203    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #204    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #205    StatefulElement.update (package:flutter/src/widgets/framework.dart:4786:5)
I/flutter ( 5079): #206    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #208    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #209    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #210    StatefulElement.update (package:flutter/src/widgets/framework.dart:4786:5)
I/flutter ( 5079): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #213    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #214    ProxyElement.update (package:flutter/src/widgets/framework.dart:4937:5)
I/flutter ( 5079): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #216    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #217    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #218    ProxyElement.update (package:flutter/src/widgets/framework.dart:4937:5)
I/flutter ( 5079): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #221    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #222    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #223    StatefulElement.update (package:flutter/src/widgets/framework.dart:4786:5)
I/flutter ( 5079): #224    Element.updateChild (package:flutter/src/widgets/framework.dart:3270:15)
I/flutter ( 5079): #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4605:16)
I/flutter ( 5079): #226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4752:11)
I/flutter ( 5079): #227    Element.rebuild (package:flutter/src/widgets/framework.dart:4291:5)
I/flutter ( 5079): #228    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2665:33)
I/flutter ( 5079): #229    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
I/flutter ( 5079): #230    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 5079): #231    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter ( 5079): #232    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
I/flutter ( 5079): #233    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
I/flutter ( 5079): #237    _invoke (dart:ui/hooks.dart:253:10)
I/flutter ( 5079): #238    _drawFrame (dart:ui/hooks.dart:211:3)
I/flutter ( 5079): (elided 6 frames from dart:async)
```

**Comment by sidrao2006** [comment]
Hello @,
Could you please post the output of `flutter doctor -v`
Thank you!

**Comment by alin25730** [comment]
> 您好@ alin25730，
> 请发表`flutter doctor -v`
> 您的感谢信息！

Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.20.2 at D:\常用应用\Flutter\flutter_windows_1.20.2-stable\flutter
    • Framework revision bbfbf1770c (9 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\sdk
    • Java binary at: D:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at D:\src\IDEA\IntelliJ IDEA 2019.2.2
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Niko'C'\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.

**Comment by alin25730** [comment]
Hello @sidrao2006 
Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
• Flutter version 1.20.2 at D:\常用应用\Flutter\flutter_windows_1.20.2-stable\flutter
• Framework revision bbfbf17 (9 weeks ago), 2020-08-13 08:33:09 -0700
• Engine revision 9d5b21729f
• Dart version 2.9.1
• Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
• Android SDK at D:\sdk
• Platform android-30, build-tools 30.0.2
• ANDROID_HOME = D:\sdk
• Java binary at: D:\Android\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
X Android license status unknown.
Try re-installing or updating your Android SDK Manager.
See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
instructions.

[√] Android Studio (version 3.5)
• Android Studio at D:\Android
• Flutter plugin version 44.0.1
• Dart plugin version 191.8593
• Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
• IntelliJ at D:\src\IDEA\IntelliJ IDEA 2019.2.2
• Flutter plugin version 43.0.2
• Dart plugin version 192.8052

[√] VS Code (version 1.50.1)
• VS Code at C:\Users\Niko'C'\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.15.1

[√] Connected device (1 available)
• Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.

**Comment by iapicca** [comment]
@alin25730 
can you provide your full `flutter run -v` and most importantly a minimal reproducible code sample

**Comment by darshankawar** [comment]
@alin25730 
Please do as suggested above and provide a minimal code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
