### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: /usr/bin/xcodebuild, OS error code: 74

### ISSUE THREAD

**Issue by tinuscubensis** [flutter/flutter#68527]
## Command
```
flutter build ios
```

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: /usr/bin/xcodebuild, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:328:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:390:50)
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:540:67)
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:522:41)
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:464:56)
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:441:47)
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart:364:50)
#8      IOSApp.fromIosProject (package:flutter_tools/src/application_package.dart:347:28)
#9      ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart:432:30)
#10     BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:91:59)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:985:18)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
```
```
[✓] Flutter (Channel master, 1.23.0-4.0.pre.93, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.23.0-4.0.pre.93 at /Users/fausto/Documents/flutter/flutter
    • Framework revision 67f51e8ec2 (4 weeks ago), 2020-09-24 10:02:03 -0400
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fausto/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 3.6 RC1.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 3.6 RC1.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5.3.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6494.35

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile)  • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone SE (2nd generation) (mobile) • 4D5F3131-BEE6-4A5C-BCED-E6B2F664C82C • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • iPhone SE (mobile)                  • 4B43FC13-36EA-4C42-988C-5EB76588891A • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    • iPhone 7 (mobile)                   • 22C0AD31-0B11-4D47-AB73-E2FC4F8BE91E • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+39
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
### Plugins
android_intent-0.3.7+3
background_fetch-0.6.0
connectivity-0.4.9+2
connectivity_for_web-0.3.1+2
connectivity_macos-0.1.0+4
firebase_analytics-5.0.16
firebase_analytics_web-0.1.1
firebase_crashlytics-0.1.4+1
firebase_messaging-6.0.16
flutter_background_geolocation-1.10.0+1
flutter_keyboard_visibility-0.7.0
flutter_plugin_android_lifecycle-1.0.8
geolocator-5.3.0
google_api_availability-2.0.3+hotfix.1
google_maps_flutter-0.5.27+2
location_permissions-2.0.5
path_provider_linux-0.0.1+2
shared_preferences-0.5.10
shared_preferences_linux-0.0.2+2
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2+1

**Comment by hamdikahloun** [comment]
Hi @tinuscubensis 

 Fixed with this PR https://github.com/flutter/flutter/pull/68361 and will be available soon.
You can try this https://github.com/flutter/flutter/issues/57083#issuecomment-637193729 .

Thank you

**Comment by jmagman** [comment]
What @hamdikahloun said 😄
