### ISSUE TITLE
widgetspan does not work with ellipsis in text widget

### ISSUE THREAD

**Issue by bayun2** [flutter/flutter#68559]
```
RichText(
                    overflow: TextOverflow.ellipsis,
                    maxLines: 1,
                    text: TextSpan(
                      style: TextStyle(
                        fontSize: 16.0,
                        height: 22.0 / 16.0,
                      ),
                      children: [
                        TextSpan(
                          text:
                              '12334512334512334512334512334511233451233451233451233451233451123345123345123345123345123345112334512334512334512334512334511233451233451233451233451233451',
                          style: TextStyle(color: Colors.red),
                        ),
                        WidgetSpan(
                          alignment: PlaceholderAlignment.middle,
                          child: GestureDetector(
                              behavior: HitTestBehavior.translucent,
                              onTap: () {
                                print('1234')
                              },
                              child: Padding(
                                padding: EdgeInsets.only(right: 2),
                                child: Icon(
                                  Iconfont.stock,
                                  size: 16,
                                ),
                              )),
                        ),
                        TextSpan(
                          text: '123345',
                          style: TextStyle(color: Colors.red),
                        )
                      ],
                    ),
                  )
```
If WidgetSpan overflow will cause the error at 1.22.1

error log 
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: UnimplementedError
#0      Matrix4.scale 
package:vector_math/…/vector_math_64/matrix4.dart:886
#1      RenderParagraph.hitTestChildren 
package:flutter/…/rendering/paragraph.dart:443
#2      RenderBox.hitTest 
package:flutter/…/rendering/box.dart:2235
#3      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> 
package:flutter/…/rendering/box.dart:2596
#4      BoxHitTestResult.addWithPaintOffset 
package:flutter/…/rendering/box.dart:787
#5      RenderBoxContainerDefaultsMixin.defaultHitTestChildren 
package:flutter/…/rendering/box.dart:2591
#6      RenderFlex.hitTestChildren 
package:flutter/…/rendering/flex.dart:965
#7      RenderBox.hitTest 
package:flutter/…/rendering/box.dart:2235
#8      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> 
package:flutter/…/rendering/box.dart:2596
#9      BoxHitTestResult.addWithPaintOffset (package:flutter/sr<…>

```

**Comment by darshankawar** [comment]
Issue replicable on latest Master. Tapping on the text throws below error log:

<details>
<summary>log</summary>

```
E/flutter (  386): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: UnimplementedError
E/flutter (  386): #0      Matrix4.scale (package:vector_math/src/vector_math_64/matrix4.dart:886:7)
E/flutter (  386): #1      RenderParagraph.hitTestChildren (package:flutter/src/rendering/paragraph.dart:443:10)
E/flutter (  386): #2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #3      RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:84:25)
E/flutter (  386): #4      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (  386): #5      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:79:21)
E/flutter (  386): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #7      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2596:25)
E/flutter (  386): #8      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (  386): #9      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2591:33)
E/flutter (  386): #10     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:412:12)
E/flutter (  386): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #14     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #16     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1827:18)
E/flutter (  386): #17     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #19     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #23     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3126:31)
E/flutter (  386): #24     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #27     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2605:22)
E/flutter (  386): #28     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (  386): #29     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2599:19)
E/flutter (  386): #30     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2585:12)
E/flutter (  386): #31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #37     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3236:31)
E/flutter (  386): #38     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #40     _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:736:25)
E/flutter (  386): #41     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (  386): #42     _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:731:33)
E/flutter (  386): #43    
E/flutter (  386): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: UnimplementedError
E/flutter (  386): #0      Matrix4.scale (package:vector_math/src/vector_math_64/matrix4.dart:886:7)
E/flutter (  386): #1      RenderParagraph.hitTestChildren (package:flutter/src/rendering/paragraph.dart:443:10)
E/flutter (  386): #2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #3      RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:84:25)
E/flutter (  386): #4      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (  386): #5      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:79:21)
E/flutter (  386): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #7      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2596:25)
E/flutter (  386): #8      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (  386): #9      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2591:33)
E/flutter (  386): #10     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:412:12)
E/flutter (  386): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #14     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #16     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1827:18)
E/flutter (  386): #17     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #19     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #23     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3126:31)
E/flutter (  386): #24     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #27     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2605:22)
E/flutter (  386): #28     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (  386): #29     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2599:19)
E/flutter (  386): #30     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2585:12)
E/flutter (  386): #31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #36     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #37     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3236:31)
E/flutter (  386): #38     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:120:19)
E/flutter (  386): #39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2235:11)
E/flutter (  386): #40     _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:736:25)
E/flutter (  386): #41     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (  386): #42     _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:731:33)
E/flutter (  386): #43    

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-2.0.pre.55, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-2.0.pre.55 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a837557634 (2 days ago), 2020-10-18 06:12:02 -0400
    • Engine revision 499a70f5e2
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.80

• No issues found!
```

</details>

**Comment by xu-baolin** [comment]
I am currently working on this issue.
