### ISSUE TITLE
Additional type errors surfaced by enabling --sound-null-safety on framework unit tests

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68562]
There are about 370 failures in the framework unit tests when enabling sound null safety, probably drastically fewer unique failures. The PR is https://github.com/flutter/flutter/pull/68536

The failures are: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865951167182274320/+/steps/download_dependencies/0/stdout?format=raw

One fix is: https://github.com/flutter/engine/pull/21983

**Comment by jonahwilliams** [comment]
Actual link is: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8865951167182274320/+/steps/run_test.dart_for_framework_tests_shard_and_subshard_widgets/0/stdout

**Comment by jonahwilliams** [comment]
One is in restoration bucket:

```
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building UnmanagedRestorationScope:
type 'Null' is not a subtype of type 'RestorationBucket' of 'value'

When the exception was thrown, this was the stack:
#0      List.add (dart:core-patch/growable_array.dart)
#1      _TestRestorableWidgetState.restoreState (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/restoration_mixin_test.dart:668:21)
#2      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:980:5)
#3      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:966:7)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4833:11)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
...     Normal element mounting (7 frames)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3377:20)
#14     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1215:16)
#15     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1193:5)
#16     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1207:7)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4369:5)
#18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2777:33)
#19     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1104:19)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:309:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#23     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:974:9)
#26     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#27     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:961:27)
#28     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#31     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#32     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#33     main.<anonymous closure> (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/restoration_mixin_test.dart:107:18)
#34     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
```

```
The following _TypeError was thrown running a test:
type 'Null' is not a subtype of type 'FutureOr<RestorationBucket>'

When the exception was thrown, this was the stack:
#1      main.<anonymous closure> (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/root_restoration_scope_test.dart:323:15)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/root_restoration_scope_test.dart)
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
```

@goderbauer

**Comment by jonahwilliams** [comment]
dart:ui
```
The following _TypeError was thrown during performLayout():
type 'Null' is not a subtype of type 'String' of 'function result'

When the exception was thrown, this was the stack:
#0      ParagraphBuilder._addPlaceholder (dart:ui/text.dart)
#1      ParagraphBuilder.addPlaceholder (dart:ui/text.dart:2241:5)
#2      WidgetSpan.build (package:flutter/src/widgets/widget_span.dart:110:13)
``

**Comment by jonahwilliams** [comment]
router:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown while finalizing the widget tree:
type 'Null' is not a subtype of type 'FutureOr<int>'

When the exception was thrown, this was the stack:
#1      TransitionRoute.dispose (package:flutter/src/widgets/routes.dart:421:26)
#2      _RouteEntry.dispose (package:flutter/src/widgets/navigator.dart:3044:11)
#3      NavigatorState.dispose (package:flutter/src/widgets/navigator.dart:3435:13)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4901:11)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2026:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2024:7)
```

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _TypeError was thrown running a test:
type 'Null' is not a subtype of type 'int' of 'result'

When the exception was thrown, this was the stack:
#0      Route.didComplete (package:flutter/src/widgets/navigator.dart)
#1      _RouteEntry.complete (package:flutter/src/widgets/navigator.dart:3032:11)
#2      NavigatorState._pushReplacementEntry (package:flutter/src/widgets/navigator.dart:4484:56)
#3      NavigatorState.restorablePushReplacementNamed (package:flutter/src/widgets/navigator.dart:4113:5)
#4      main.<anonymous closure> (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/navigator_restoration_test.dart:77:58)
<asynchronous suspension>
```

```
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _TypeError was thrown running a test:
type 'Null' is not a subtype of type 'int' of 'result'

When the exception was thrown, this was the stack:
#0      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
#1      _RouteEntry.pop (package:flutter/src/widgets/navigator.dart:2999:15)
#2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4840:13)
#3      NavigatorState.restorablePopAndPushNamed (package:flutter/src/widgets/navigator.dart:4176:5)
#4      main.<anonymous closure> (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/navigator_restoration_test.dart:110:58)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/navigator_restoration_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
```

**Comment by jonahwilliams** [comment]
widget inspector

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _TypeError was thrown running a test:
type '_InternalLinkedHashMap<String, Object?>' is not a subtype of type 'Map<Object, Object>' of
'value'

When the exception was thrown, this was the stack:
#0      List.add (dart:core-patch/growable_array.dart)
#1      TestWidgetInspectorService.postEvent (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test_utils.dart:29:36)
#2      WidgetInspectorService._postExtensionStateChangedEvent (package:flutter/src/widgets/widget_inspector.dart:845:5)
#3      WidgetInspectorService._registerBoolServiceExtension.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:827:11)
<asynchronous suspension>
#4      WidgetInspectorService._registerBoolServiceExtension.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart)
#5      TestWidgetInspectorService.testBoolExtension (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test_utils.dart:52:59)
#6      _TestWidgetInspectorService.runTests.<anonymous closure> (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart:2009:28)
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
```

**Comment by jonahwilliams** [comment]
Custom painter test

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following _TypeError was thrown during paint():
type 'Null' is not a subtype of type 'String' of 'value'

When the exception was thrown, this was the stack:
#0      List.add (dart:core-patch/growable_array.dart)
#1      TestCustomPainter.paint (file:///b/s/w/ir/k/flutter/packages/flutter/test/widgets/custom_paint_test.dart:19:9)
#2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:531:13)
#3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:572:7)
```

**Comment by goderbauer** [comment]
To reproduce locally: `flutter test --null-assertions --sound-null-safety --enable-experiment=non-nullable`
