### ISSUE TITLE
flutter package iOS error

### ISSUE THREAD

**Issue by ly410726** [flutter/flutter#68570]
```
flutter debug运行ios正常，但是如果打包报错
Failed to build iOS app
Error output from Xcode build:
↳
    2020-10-20 14:25:14.544 xcodebuild[53280:681775] WARNING: Failed to load plugin at path: "/Users/housongtao/Library/Application
    Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587
    "dlopen_preflight(/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor): no suitable
    image found.  Did find:
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor: code signature in
        (/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor) not valid for use in process
        using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor: stat() failed with errno=1"
        UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle.,
        NSFilePath=/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor,
        NSDebugDescription=dlopen_preflight(/Users/housongtao/Library/Application
        Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor): no suitable image found.  Did find:
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor: code signature in
        (/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor) not valid for use in process
        using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin/Contents/MacOS/XFunnyEditor: stat() failed with errno=1,
        NSBundlePath=/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin, NSLocalizedDescription=The bundle “XFunnyEditor”
        couldn’t be loaded because it is damaged or missing necessary resources.}
    2020-10-20 14:25:14.558 xcodebuild[53280:681775] WARNING: Failed to load plugin at path: "/Users/housongtao/Library/Application
    Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587
    "dlopen_preflight(/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator): no
    suitable image found.  Did find:
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator: code signature in
        (/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator) not valid for use in
        process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator: stat() failed with
        errno=1" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle.,
        NSFilePath=/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator,
        NSDebugDescription=dlopen_preflight(/Users/housongtao/Library/Application
        Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator): no suitable image found.  Did find:
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator: code signature in
        (/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator) not valid for use in
        process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin/Contents/MacOS/KitModelGenerator: stat() failed with
        errno=1, NSBundlePath=/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KitModelGenerator.xcplugin, NSLocalizedDescription=The bundle
        “KitModelGenerator” couldn’t be loaded because it is damaged or missing necessary resources.}
    2020-10-20 14:25:14.577 xcodebuild[53280:681775] WARNING: Failed to load plugin at path: "/Users/housongtao/Library/Application
    Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587
    "dlopen_preflight(/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat): no suitable
    image found.  Did find:
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat: code signature in
        (/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat) not valid for use in process
        using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat: stat() failed with errno=1"
        UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle.,
        NSFilePath=/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat,
        NSDebugDescription=dlopen_preflight(/Users/housongtao/Library/Application
        Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat): no suitable image found.  Did find:
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat: code signature in
        (/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat) not valid for use in process
        using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
        /Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin/Contents/MacOS/ESJsonFormat: stat() failed with errno=1,
        NSBundlePath=/Users/housongtao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin, NSLocalizedDescription=The bundle “ESJsonFormat”
        couldn’t be loaded because it is damaged or missing necessary resources.}
    2020-10-20 14:25:16.907 xcodebuild[53280:682151]  DTDeviceKit: deviceType from 00008020-001D51D42E08002E was NULL
    2020-10-20 14:25:17.174 xcodebuild[53280:682151]  DTDeviceKit: deviceType from 00008020-001D51D42E08002E was NULL
    2020-10-20 14:25:17.175 xcodebuild[53280:682151]  DTDeviceKit: deviceType from 00008020-001D51D42E08002E was NULL
    ** BUILD FAILED **
```
```
✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/housongtao/flutter
    • Framework revision f30b7f4db9 (12 天前), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/housongtao/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/housongtao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • 侯嵩涛的iPhone (mobile) • 00008020-001D51D42E08002E • ios • iOS 14.0.1

! Doctor found issues in 1 category.
Process finished with exit code 0
```

**Comment by TahaTesser** [comment]
Hi @ly410726 
Can you please provide your complete `flutter run --verbose` in. a plain text file & attach it here in the comments and a complete reproducible minimal code sample
Thank you

**Comment by mohamedsamirmohamedsalem** [comment]
it is a flutter issue , and flutter team  didn't solve it yet.
for temporary solve this issue , downgrade your flutter version to 1.17.5 or less.
- flutter version 1.17.5
- flutter doctor
- flutter clean 
- invalidate cache and restart 
- flutter run

**Comment by ly410726** [comment]
版本推到1.17.5之后运行报错
Traceback (most recent call last):                                      
  File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 25, in connect_command
    process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'      
Traceback (most recent call last):                                      
  File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 45, in run_command
    lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'            
Traceback (most recent call last):                                      
  File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 74, in safequit_command
    process = lldb.target.process                                       
AttributeError: 'NoneType' object has no attribute 'process'            
Installing and launching...         
然后打包也报错，这行程死循环了啊，没办法解决了吗，体验相当差啊

**Comment by ly410726** [comment]
> 这是一个扑扑的问题，扑扑团队尚未解决。
> 为了暂时解决此问题，请将您的Flutter版本降级至1.17.5或更低。
> 
> * 颤振版本1.17.5
> * 扑医生
> * 扑扑干净
> * 使缓存无效并重新启动
> * 扑动

版本推到1.17.5之后运行报错
Traceback (most recent call last):
File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 25, in connect_command
process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError: 'NoneType' object has no attribute 'ConnectRemote'
Traceback (most recent call last):
File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 45, in run_command
lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError: 'NoneType' object has no attribute 'modules'
Traceback (most recent call last):
File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 74, in safequit_command
process = lldb.target.process
AttributeError: 'NoneType' object has no attribute 'process'
Installing and launching...
然后打包也报错，这行程死循环了啊，没办法解决了吗，体验相当差啊

**Comment by TahaTesser** [comment]
Hi @ly410726 
Sorry,  I don't the speak Chinese, it's hard to understand the issue
### Uisng Google Trnaslate 
```
Run an error after the version is pushed to 1.17.5
Traceback (most recent call last):
File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 25, in connect_command
process = lldb.target.ConnectRemote(listener, connect_url, None, error)
AttributeError:'NoneType' object has no attribute'ConnectRemote'
Traceback (most recent call last):
File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 45, in run_command
lldb.target.modules[0].SetPlatformFileSpec(lldb.SBFileSpec(device_app))
AttributeError:'NoneType' object has no attribute'modules'
Traceback (most recent call last):
File "/tmp/D3B5FF15-60C6-4F10-8BC8-18F8236B8048/fruitstrap_00008030_001E31660A82802E.py", line 74, in safequit_command
process = lldb.target.process
AttributeError:'NoneType' object has no attribute'process'
Installing and launching...
Then the package also reported an error, this itinerary is endless, can't it be solved, the experience is quite bad?
```

@ly410726  @mohamedsamirmohamedsalem 
Can you please provide your complete `flutter run --verbose` in. a plain text file & attach it here in the comments and a complete reproducible minimal code sample and reproducible steps 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
