### ISSUE TITLE
Use TabBar in Dialog to report an error, LateInitializationError: _currentTabOffsets@1725014024

### ISSUE THREAD

**Issue by changleibox** [flutter/flutter#68586]
## Steps to Reproduce

1. 在一个Dialog上使用TabBar.
2. 调用```showGeneralDialog```；
3. 页面提示```Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.```异常；

**Expected results:** 
页面正常显示；

**Actual results:** 
页面提示```Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.```异常；

<details>
  <summary>Logs</summary>

```
[+1540 ms] flutter: Another exception was thrown: LateInitializationError: _currentTabOffsets@595014024
[   +2 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +3 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] flutter: Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
[   +1 ms] flutter: Another exception was thrown: LateInitializationError: _currentTabOffsets@595014024
[   +7 ms] flutter: Another exception was thrown: buildScope missed some dirty elements.
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Mac OS X 10.15.7 19H2 x86_64, locale zh-Hans-CN)
    • Flutter version 1.23.0-18.0.pre at /Users/changlei/Downloads/flutter
    • Framework revision 37ebe3d82a (7 days ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/changlei/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/changlei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • iPad Pro (11-inch) (2nd generation) (mobile) • 84E523B2-614D-4645-9B55-546BF61B0A30 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                              • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)                             • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by sidrao2006** [comment]
## Use TabBar in Dialog to report errors

### Steps to reproduce

1. Use TabBar on a Dialog
2. Call `showGeneralDialog`
3. The page prompts `Failed assertion: line 4371 pos 14:'owner!._debugCurrentBuildTarget == this': is not true`.

**Expected results:**
The page is displayed normally;

**Actual results:**
The page prompts `Failed assertion: line 4371 pos 14:'owner!._debugCurrentBuildTarget == this': is not true`.

**Comment by pedromassangocode** [comment]
Hi @changleibox 
Can you please provide your `flutter doctor -v` a minimal complete reproducible code sample?
Thank you

**Comment by changleibox** [comment]
以下是我的代码的一个示例，我经过多次测试，发现用异步加载，就会出现这种问题
```dart
class DialogTabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 300,
      child: OutlineButton(
        onPressed: () {
          showGeneralDialog<void>(
            context: context,
            pageBuilder: (context, animation, secondaryAnimation) {
              return const _DialogContent();
            },
          );
        },
        child: const Text('打开'),
      ),
    );
  }
}

class _DialogContent extends StatefulWidget {
  const _DialogContent({Key key}) : super(key: key);

  @override
  __DialogContentState createState() => __DialogContentState();
}

class __DialogContentState extends State<_DialogContent> {
  final _tabs = <Widget>[];

  @override
  void initState() {
    _loadTabs();
    super.initState();
  }

  Future<void> _loadTabs() async {
    await Future<void>.delayed(const Duration(milliseconds: 200));
    _tabs.addAll(List.generate(20, (index) {
      return Text(
        'tab$index',
        style: _tabTextStyle,
      );
    }));
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    final themeData = Theme.of(context);
    return Dialog(
      child: Container(
        padding: const EdgeInsets.all(10),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            DefaultTabController(
              length: _tabs.length,
              initialIndex: 0,
              child: AnimatedSwitcher(
                duration: const Duration(milliseconds: 300),
                child: TabBar(
                  isScrollable: true,
                  indicatorColor: Colors.transparent,
                  indicatorSize: TabBarIndicatorSize.tab,
                  labelColor: themeData.primaryColor,
                  unselectedLabelColor: themeData.textTheme.subtitle1.color,
                  tabs: List.generate(_tabs.length, (index) {
                    return Tab(
                      child: _tabs[index],
                    );
                  }),
                ),
              ),
            ),
            Container(
              height: 100,
              margin: const EdgeInsets.symmetric(
                vertical: 20,
              ),
              color: Colors.redAccent,
            ),
            OutlineButton(
              child: const Text('close'),
              onPressed: () {
                Navigator.pop(context);
              },
            ),
          ],
        ),
      ),
    );
  }
}
````

**Comment by pedromassangocode** [comment]
Hi @changleibox 
I was able to reproduce the issue however there is a lot going on in your code and I'm not really sure if this is an issue with the code or an issue in Flutter.

I'm leaving this issue opened because of the first error in the logs for a better investigation of the issue:

```
LateInitializationError: _currentTabOffsets@224014024
The relevant error-causing widget was: 
  AnimatedSwitcher file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:78:22
```

<details><summary>Logs</summary>

```
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 480ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
LateInitializationError: _currentTabOffsets@224014024
The relevant error-causing widget was: 
  AnimatedSwitcher file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:78:22
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  AnimatedSwitcher file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:78:22
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  DefaultTabController file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:75:13
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  DefaultTabController file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:75:13
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Container file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:70:14
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  Dialog file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:69:12
════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Null check operator used on a null value
#0      RenderObject.sendSemanticsEvent (package:flutter/src/rendering/object.dart:2503:14)
#1      Feedback.forTap (package:flutter/src/material/feedback.dart:95:33)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:984:18)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1101:38)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:<…>

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  _DialogContent file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:26:28
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4371 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was: 
  _DialogContent file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:26:28
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
LateInitializationError: _currentTabOffsets@224014024
The relevant error-causing widget was: 
  TabBar file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:80:24
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
buildScope missed some dirty elements.
The list of dirty elements at the end of the buildScope call was: 
  : _DialogContent
    dependencies: [_LocalizationsScope-[GlobalKey#dab13], _InheritedTheme]
    state: __DialogContentState#445d9
  : AnimatedBuilder
    animation: AnimationController#fa8ff(▶ 0.111)
    state: _AnimatedState#962a9
  : TabBar
    dirty
    dependencies: [_LocalizationsScope-[GlobalKey#dab13], _TabControllerScope, _InheritedTheme]
    state: _TabBarState#29365
  : _MaterialInterior
    duration: 75ms
    shape: _OutlineBorder()
    elevation: 0.0
    color: Color(0x00000000)
    shadowColor: Color(0xff000000)
    dependencies: [_EffectiveTickerMode, _LocalizationsScope-[GlobalKey#dab13], Directionality, _InheritedTheme]
    state: _MaterialInteriorState#79d97(ticker active)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5144 pos 14: '_dependents.isEmpty': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:10:12
════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details>

<details><summary>complete code sample</summary>

```
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(body: Center(child: SizedBox(
        width: 300,
        child: OutlineButton(
          onPressed: () {
            showGeneralDialog<void>(
              context: context,
              pageBuilder: (context, animation, secondaryAnimation) {
                return const _DialogContent();
              },
            );
          },
          child: const Text('打开'),
        ),
      )))
    );
  }
}

class _DialogContent extends StatefulWidget {
  const _DialogContent({Key? key}) : super(key: key);

  @override
  __DialogContentState createState() => __DialogContentState();
}

class __DialogContentState extends State<_DialogContent> {
  final _tabs = <Widget>[];

  @override
  void initState() {
    _loadTabs();
    super.initState();
  }

  Future<void> _loadTabs() async {
    await Future<void>.delayed(const Duration(milliseconds: 200));
    _tabs.addAll(List.generate(20, (index) {
      return Text(
        'tab$index',
        style: TextStyle(color: Colors.yellow),
      );
    }));

    WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    final themeData = Theme.of(context)!;
    return Dialog(
      child: Container(
        padding: const EdgeInsets.all(10),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            DefaultTabController(
              length: _tabs.length,
              initialIndex: 0,
              child: AnimatedSwitcher(
                duration: const Duration(milliseconds: 300),
                child: TabBar(
                  isScrollable: true,
                  indicatorColor: Colors.transparent,
                  indicatorSize: TabBarIndicatorSize.tab,
                  labelColor: themeData.primaryColor,
                  unselectedLabelColor: themeData.textTheme.subtitle1!.color,
                  tabs: List.generate(_tabs.length, (index) {
                    return Tab(
                      child: _tabs[index],
                    );
                  }),
                ),
              ),
            ),
            Container(
              height: 100,
              margin: const EdgeInsets.symmetric(
                vertical: 20,
              ),
              color: Colors.redAccent,
            ),
            OutlineButton(
              child: const Text('close'),
              onPressed: () {
                Navigator.pop(context);
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by changleibox** [comment]
你好，我把示例代码简化了一下，依然能够重现此问题，你可以再看一下
<details><summary>Code</summary>

```dart
class DialogTabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 300,
      child: OutlineButton(
        onPressed: () {
          showDialog<void>(
            context: context,
            barrierDismissible: true,
            builder: (context) {
              return const _DialogContent();
            },
          );
        },
        child: const Text('打开'),
      ),
    );
  }
}

class _DialogContent extends StatefulWidget {
  const _DialogContent({Key key}) : super(key: key);

  @override
  __DialogContentState createState() => __DialogContentState();
}

class __DialogContentState extends State<_DialogContent> {
  final _tabs = <Widget>[];

  @override
  void initState() {
    _loadTabs();
    super.initState();
  }

  Future<void> _loadTabs() async {
    await Future<void>.delayed(const Duration(milliseconds: 200));
    _tabs.addAll(List.generate(20, (index) {
      return Text(
        'tab$index',
        style: _tabTextStyle,
      );
    }));
    if (!mounted) {
      return;
    }
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: DefaultTabController(
        length: _tabs.length,
        initialIndex: 0,
        child: TabBar(
          isScrollable: true,
          tabs: List.generate(_tabs.length, (index) {
            return Tab(
              child: _tabs[index],
            );
          }),
        ),
      ),
    );
  }
}
```
</details>

**Comment by goderbauer** [comment]
@shihaohong Does https://github.com/flutter/flutter/pull/69005 also fix this? The errors seem related.

**Comment by shihaohong** [comment]
Yeah, I just tested this against the branch in #69005 and the error goes away

**Comment by maskletter** [comment]
当我将版本更新成beta，并且-enable-web之后，也出现了这个问题
