### ISSUE TITLE
Failed assertion: line 93: '_pointers.containsKey(datum.pointer)' is not true

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#6862]
## Steps to Reproduce

Running a flutter app under qemu. When I try and interact with the app with the mouse, I get this:

```
[00240.406] 03135.03217> [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[00240.406] 03135.03217> 'package:flutter/src/gestures/converter.dart': Failed assertion: line 93: '_pointers.containsKey(datum.pointer)' is not true.
[00240.406] 03135.03217> #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:24)
[00240.407] 03135.03217> #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:31)
[00240.407] 03135.03217> #2      PointerEventConverter.expand.<expand_sync_body> (package:flutter/src/gestures/converter.dart:93)
[00240.407] 03135.03217> #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:66)
[00240.407] 03135.03217> #4      ListQueue.addAll (dart:collection/queue.dart:580)
[00240.407] 03135.03217> #5      BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:32)
[00240.407] 03135.03217> #6      _dispatchPointerDataPacket (file:///media/jimbe/mojossd/fuchsia/flutter/lib/ui/hooks.dart:73)
```

## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/xyz/fuchsia/lib/flutter
    • Framework revision fd5a08941e (14 hours ago), 2016-11-14 16:54:24
    • Engine revision a3a13f4a94
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0_102-google-v7-137518472-137512069)

[x] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • None
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by zoechi** [comment]
I assume this issue is stale. Please add a comment to have it reopened if you disagree.
