### ISSUE TITLE
run profile crash: ArgumentError - Cannot find executable gen_snapshot_arm64

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#68643]
## command

flutter --local-engine-src-path=/Users/aaclarke/dev/engine/src --local-engine=ios_profile assemble --output=/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine/.ios/Flutter/ -dTargetPlatform=ios -dTargetFile=/Users/aaclarke/dev/DoubleEngine/DoubleEngine/double_engine/lib/main.dart -dBuildMode=profile -dIosArchs=arm64 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= profile_ios_bundle_flutter_assets

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/aaclarke/dev/engine/src/out/ios_profile/clang_x64/gen_snapshot_arm64.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:568:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:462:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:568:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:473:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:492:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:197:56)
#9      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:86:31)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:739:35)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:739:21)
<asynchronous suspension>
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:36)
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:58)
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1033:18)
#18     _rootRunUnary (dart:async/zone.dart:1198:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#24     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#25     _rootRun (dart:async/zone.dart:1190:13)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, 1.24.0-2.0.pre.91, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
    • Flutter version 1.24.0-2.0.pre.91 at /Users/aaclarke/dev/flutter
    • Framework revision cb5865d86c (2 hours ago), 2020-10-20 09:50:31 -0700
    • Engine revision ea2aea1c61
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aaclarke/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • iPhone (2) (mobile) • 9f7f1435a54bb826cdca696461217ecc2dabda05 • ios            • iOS 13.5.1
    • macOS (desktop)     • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G2021 darwin-x64
    • Web Server (web)    • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)        • chrome                                   • web-javascript • Google Chrome 86.0.4240.80

• No issues found!
```

## notes
I do have a `out/ios_profile/clang_x64/gen_snapshot` but not a `out/ios_profile//clang_x64/gen_snapshot_arm64`

**Comment by gaaclarke** [comment]
cc @jmagman, let me know if there is anything else I can do to help.

**Comment by jonahwilliams** [comment]
@gaaclarke See https://github.com/flutter/flutter/issues/38933

**Comment by gaaclarke** [comment]
Yep, this is a dup of https://github.com/flutter/flutter/issues/38933
