### ISSUE TITLE
[Web] Unstable Path in CustomPainter

### ISSUE THREAD

**Issue by Grooviz** [flutter/flutter#68702]
Basic operations on a dart:ui Path compromise the Path.

## Steps to Reproduce on DartPad

1. **Open** a new Flutter Project on [https://dartpad.dartlang.org/flutter](https://dartpad.dartlang.org/flutter).
2. **Replace** the source code with the following:

```
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: CustomPaint(
            size: Size(300, 300),
            painter: _Painter(),
          ),
        ),
      ),
    );
  }
}

class _Painter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) async {
    Path p = Path()
      ..moveTo(100, 100) 
      ..lineTo(200, 100)
      ..lineTo(150, 200)
      ..close();
    /* 1 */ //print(p.getBounds().longestSide);
    /* 2 */ //canvas.drawPath(p, Paint()..color = Colors.amber);
    /* 3 */ canvas.drawPath(p.transform(Matrix4.identity().storage), Paint()..color = Colors.amber);
    p = p.transform((Matrix4.identity()..rotateZ(.29)..scale(1.5)).storage);
    canvas.drawPath(p, Paint()..color = Colors.red);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;

}
```

3. **Run** the DartPad, two triangles are painted on the canvas.

4. **Uncomment** line `/* 1 */ print(p.getBounds().longestSide);`

5. **Run** the DartPad, only the first triangle is painted on the canvas.
In the console, you will also see an Uncaught Error:
`Assertion failed: isValid is not true`
at `flutter_web_sdk/lib/_engine/engine/html/path/path_ref.dart:831:12`

6. **Comment** line `/* 1 */ print(p.getBounds().longestSide);`

7. **Comment** line `/* 3 */ canvas.drawPath(p.transform(Matrix4.identity().storage), Paint()..color = Colors.amber);`

8. **Uncomment** line `/* 2 */ canvas.drawPath(p, Paint()..color = Colors.amber);`
    
9. **Run** the DartPad, only the first triangle is painted on the canvas.
In the console, you will see the same Uncaught Error:
`Assertion failed: isValid is not true`
at `flutter_web_sdk/lib/_engine/engine/html/path/path_ref.dart:831:12`

## Expected behavior

Operations on Paths should be immutable and not interfere with further drawing of the Path.

**Comment by darshankawar** [comment]
Although, I am able to replicate the assertion failed based on above details, if we compile app using below command, the assertion is not thrown and the triangles are rendered properly:

` flutter run -d chrome --debug --dart-define=FLUTTER_WEB_USE_SKIA=true`

This seem to indicate, an issue with the way skia is rendering the path in customPainter. Keeping this issue open for further analysis.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.24.0-1.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-1.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 12bea61c29 (6 days ago), 2020-10-14 15:57:04 -0700
    • Engine revision 069b3cf8f0
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.80

• No issues found!

```

</details>

<details>
<summary>error log</summary>

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/path/path_ref.dart:831:12
isValid
is not true
    at Object.throw_ [as throw] (http://localhost:50203/dart_sdk.js:4344:11)
    at Object.assertFailed (http://localhost:50203/dart_sdk.js:4287:15)
    at _engine.PathRef._shallowCopy.debugValidate (http://localhost:50203/dart_sdk.js:150883:42)
    at new _engine.PathRef._shallowCopy (http://localhost:50203/dart_sdk.js:150981:10)
    at new _engine.SurfacePath._shallowCopy (http://localhost:50203/dart_sdk.js:149208:21)
    at _engine.RecordingCanvas.new.drawPath (http://localhost:50203/dart_sdk.js:153571:21)
    at _engine.SurfaceCanvas.__.[_drawPath] (http://localhost:50203/dart_sdk.js:145607:22)
    at _engine.SurfaceCanvas.__.drawPath (http://localhost:50203/dart_sdk.js:145602:22)
    at paint (http://localhost:50203/packages/newweb/main.dart.lib.js:217:16)
    at paint.next (<anonymous>)
    at runBody (http://localhost:50203/dart_sdk.js:37704:34)
    at Object._async [as async] (http://localhost:50203/dart_sdk.js:37735:7)
    at main._Painter.new.paint (http://localhost:50203/packages/newweb/main.dart.lib.js:199:20)
    at custom_paint.RenderCustomPaint.new.[_paintWithPainter] (http://localhost:50203/packages/flutter/src/rendering/custom_paint.dart.lib.js:327:15)
    at custom_paint.RenderCustomPaint.new.paint (http://localhost:50203/packages/flutter/src/rendering/custom_paint.dart.lib.js:344:32)
    at custom_paint.RenderCustomPaint.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at shifted_box.RenderPositionedBox.new.paint (http://localhost:50203/packages/flutter/src/rendering/shifted_box.dart.lib.js:129:17)
    at shifted_box.RenderPositionedBox.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.defaultPaint (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:8726:19)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.paint (http://localhost:50203/packages/flutter/src/rendering/custom_layout.dart.lib.js:278:12)
    at custom_layout.RenderCustomMultiChildLayoutBox.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at material._RenderInkFeatures.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at material._RenderInkFeatures.new.paint (http://localhost:50203/packages/flutter/src/material/icon_button.dart.lib.js:60364:13)
    at material._RenderInkFeatures.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderPhysicalModel.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at object$.PaintingContext.new.pushLayer (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6447:7)
    at proxy_box.RenderPhysicalModel.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:2120:17)
    at proxy_box.RenderPhysicalModel.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderSemanticsAnnotations.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderSemanticsAnnotations.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderRepaintBoundary.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderRepaintBoundary.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at Function._repaintCompositedChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6302:31)
    at Function.repaintCompositedChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6273:31)
    at object$.PaintingContext.new.[_compositeChild] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6343:33)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6327:30)
    at proxy_box.RenderIgnorePointer.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderIgnorePointer.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at stack.RenderStack.new.defaultPaint (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:8726:19)
    at stack.RenderStack.new.paintStack (http://localhost:50203/packages/flutter/src/rendering/stack.dart.lib.js:678:12)
    at stack.RenderStack.new.paint (http://localhost:50203/packages/flutter/src/rendering/stack.dart.lib.js:687:14)
    at stack.RenderStack.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderDecoratedBox.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderDecoratedBox.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:2388:13)
    at proxy_box.RenderDecoratedBox.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderFractionalTranslation.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderFractionalTranslation.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:2939:15)
    at proxy_box.RenderFractionalTranslation.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderFractionalTranslation.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderFractionalTranslation.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:2939:15)
    at proxy_box.RenderFractionalTranslation.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderRepaintBoundary.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderRepaintBoundary.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at Function._repaintCompositedChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6302:31)
    at Function.repaintCompositedChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6273:31)
    at object$.PaintingContext.new.[_compositeChild] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6343:33)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6327:30)
    at proxy_box.RenderSemanticsAnnotations.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderSemanticsAnnotations.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderOffstage.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderOffstage.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:3446:13)
    at proxy_box.RenderOffstage.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderSemanticsAnnotations.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderSemanticsAnnotations.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at overlay$._RenderTheatre.new.paintStack (http://localhost:50203/packages/flutter/src/widgets/widget_span.dart.lib.js:28083:17)
    at overlay$._RenderTheatre.new.paint (http://localhost:50203/packages/flutter/src/widgets/widget_span.dart.lib.js:28094:14)
    at overlay$._RenderTheatre.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderSemanticsAnnotations.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderSemanticsAnnotations.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderAbsorbPointer.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderAbsorbPointer.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderPointerListener.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderPointerListener.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderSemanticsAnnotations.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderSemanticsAnnotations.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at proxy_box.RenderSemanticsAnnotations.new.paint (http://localhost:50203/packages/flutter/src/rendering/proxy_box.dart.lib.js:385:41)
    at proxy_box.RenderSemanticsAnnotations.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at object$.PaintingContext.new.paintChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6329:33)
    at view.RenderView.new.paint (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:4827:39)
    at view.RenderView.new.[_paintWithContext] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:3645:14)
    at Function._repaintCompositedChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6302:31)
    at Function.repaintCompositedChild (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6273:31)
    at object$.PipelineOwner.new.flushPaint (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6835:39)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6048:26)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:50203/packages/flutter/src/widgets/widget_span.dart.lib.js:50918:15)
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:50203/packages/flutter/src/rendering/layer.dart.lib.js:6010:12)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:50203/packages/flutter/src/scheduler/binding.dart.lib.js:767:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:50203/packages/flutter/src/scheduler/binding.dart.lib.js:735:37)
    at http://localhost:50203/packages/flutter/src/scheduler/binding.dart.lib.js:649:14
    at internalCallback (http://localhost:50203/dart_sdk.js:23840:11)

```

</details>

**Comment by ferhatb** [comment]
@Grooviz thank you for reporting bug. We will have a fix landing shortly.
