### ISSUE TITLE
Regression: Apps can no longer be run/debugged from VSCode and Android Studio

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#68705]
## Repro steps

1. Create a new app:
   ```
   flutter create repro
   cd nulltest
   flutter pub get
   ```
1. Open in VSCode or Android Studio
1. Hit F5 / start running or debugging

=>

```
When the exception was thrown, this was the stack
#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:894
#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:882
#4      BindingBase.registerServiceExtension.<anonymous closure>
package:flutter/…/foundation/binding.dart:546
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
Error handling 'serviceExtension' custom request: ext.flutter.inspector.setPubRootDirectories: (-32000) Server error
{
  "exception":"'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.",
  "stack":"#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:894:16)
#3      WidgetInspectorService._registerServiceExtensionVarArgs.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:882:17)
#4      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:546:32)
<asynchronous suspension>",
  "method":"ext.flutter.inspector.setPubRootDirectories"
}```

**Comment by mit-mit** [comment]
This is potentially a regression introduced as part of resolving https://github.com/flutter/flutter/issues/68627, cc @jacob314 @goderbauer ?

**Comment by pedromassangocode** [comment]
I'm seeing lots of waring after upgrade `master` channel as well.

In my specific case I'm able to debug/run my projects without problem but the message keeps showing every time I do Hot-Reload or run my project for the first time.

Note: I don't have NNBD enabled on the projects I'm running!

![Screen Shot 2020-10-21 at 13 05 47](https://user-images.githubusercontent.com/67424416/96717331-3337fd80-139e-11eb-8174-569242916ea9.png)


<details><summary>Logs</summary>

```
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 444ms.

════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 894 pos 16: 'index == parameters.length': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details>

**Comment by DanTup** [comment]
From my comment in the other issue - I tweaked it to print the arguments out and got this:

```
flutter: Exception: Index: 1, Params: {arg0: file:///Users/danny/Dev/TestStuff/foo, isolateId:
flutter: isolates/1397158588675607}
```

It seems like the code assumes that the number of arguments exactly matches the `argX` count, but there's also an `isolateId` in there.

I don't know whether the `isolateId` is intended to be passed here, but VS Code is definitely passing it:

```ts
params: {
	arg0: this.formatPathForPubRootDirectories(e.session.configuration.cwd),
	arg1: e.session.configuration.cwd,
	isolateId: e.body.isolateId,
},
```

If it shouldn't be there, VS Code is probably doing the wrong thing. If it is supposed to be there, I think the `assert` is incorrect.

**Comment by pedromassangocode** [comment]
I think the assertion is right. What may be wrong is the break block, the while loop is being broken before the index is incremented and this causes disparity between the amount of parameters iterated and the amount of index iterated.

https://github.com/flutter/flutter/blob/a4ac7cce827cce7fe8d11166d3ad3f20f6262f60/packages/flutter/lib/src/widgets/widget_inspector.dart#L882-L893

**Comment by jacob314** [comment]
vscode shouldn't be passing an isolateId but we can ignore that field.

**Comment by DanTup** [comment]
@jacob314 if it's not required, I can remove it - though DevTools is doing the same so I wonder if it might be needed?

https://github.com/flutter/devtools/blob/59e338106eae195718385840a3149f6287e0c354/packages/devtools_app/lib/src/inspector/inspector_service.dart#L389
