### ISSUE TITLE
possible bug or lack of documentation on page view 

### ISSUE THREAD

**Issue by Suryapratap-R** [flutter/flutter#68710]
I was trying to build a simple UI after using pageview it gave me an error and asked to report, hence doing

file attached

with pubspec.yaml
in as textfile
[main.txt](https://github.com/flutter/flutter/files/5416293/main.txt)
[pubspec.txt](https://github.com/flutter/flutter/files/5416306/pubspec.txt)

<details>
<summary>stack trace</summary>

```
The following assertion was thrown during a service extension callback for "ext.flutter.reassemble":
'package:flutter/src/rendering/object.dart': Failed assertion: line 1530 pos 12: '_debugCanPerformMutations': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      RenderObject.markNeedsLayout
package:flutter/…/rendering/object.dart:1530
#3      RenderBox.markNeedsLayout
package:flutter/…/rendering/box.dart:2147
#4      RenderObject.reassemble
package:flutter/…/rendering/object.dart:1229
#5      RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
#6      RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042

Reassembling main.dart$main-3030906725914639 failed: ext.flutter.reassemble: (-32000) Server error
{"exception":"'package:flutter/src/rendering/object.dart': Failed assertion: line 1530 pos 12: '_debugCanPerformMutations': is not true.","stack":"#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)\n#2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1530:12)\n#3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2147:11)\n#4      RenderObject.reassemble (package:flutter/src/rendering/object.dart:1229:5)\n#5      RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#6      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#7      RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#8      RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#9      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#10     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#11     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#12     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#13     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#14     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#15     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#16     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#17     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#18     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#19     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#20     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#21     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3325:14)\n#22     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#23     DebugOverflowIndicatorMixin.reassemble (package:flutter/src/rendering/debug_overflow_indicator.dart:314:11)\n#24     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#25     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#26     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#27     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#28     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#29     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#30     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#31     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3325:14)\n#32     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#33     DebugOverflowIndicatorMixin.reassemble (package:flutter/src/rendering/debug_overflow_indicator.dart:314:11)\n#34     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#35     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3325:14)\n#36     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#37     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#38     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#39     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#40     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#41     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#42     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#43     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#44     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#45     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#46     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#47     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#48     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#49     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#50     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#51     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#52     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#53     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#54     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#55     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#56     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#57     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#58     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#59     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#60     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#61     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#62     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#63     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#64     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#65     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#66     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#67     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#68     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#69     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#70     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#71     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3325:14)\n#72     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#73     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#74     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#75     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#76     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#77     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#78     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#79     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#80     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#81     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#82     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#83     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#84     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#85     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#86     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#87     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#88     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#89     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#90     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#91     RenderObject.reassemble.<anonymous closure> (package:flutter/src/rendering/object.dart:1234:13)\n#92     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)\n#93     RenderObject.reassemble (package:flutter/src/rendering/object.dart:1233:5)\n#94     RendererBinding.performReassemble (package:flutter/src/rendering/binding.dart:451:18)\n<asynchronous suspension>\n#95     WidgetsBinding.performReassemble (package:flutter/src/widgets/binding.dart:992:18)\n#96     BindingBase.lockEvents (package:flutter/src/foundation/binding.dart:248:41)\n#97     BindingBase.reassembleApplication (package:flutter/src/foundation/binding.dart:288:12)\n#98     BindingBase.registerSignalServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:325:23)\n#99     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:547:32)\n<asynchronous suspension>\n#100    BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart)\n#101    _runExtension (dart:developer-patch/developer.dart:84:23)\n","method":"ext.flutter.reassemble"}
E/flutter (16212): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1530 pos 12: '_debugCanPerformMutations': is not true., stack trace: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (16212): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (16212): #2      RenderObject.markNeedsLayout
package:flutter/…/rendering/object.dart:1530
E/flutter (16212): #3      RenderBox.markNeedsLayout
package:flutter/…/rendering/box.dart:2147
E/flutter (16212): #4      RenderObject.reassemble
package:flutter/…/rendering/object.dart:1229
E/flutter (16212): #5      RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #6      RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042
E/flutter (16212): #7      RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #8      RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #9      RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042
E/flutter (16212): #10     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #11     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #12     RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042
E/flutter (16212): #13     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #14     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #15     RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042
E/flutter (16212): #16     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #17     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #18     RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042
E/flutter (16212): #19     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #20     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #21     ContainerRenderObjectMixin.visitChildren
package:flutter/…/rendering/object.dart:3325
E/flutter (16212): #22     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #23     DebugOverflowIndicatorMixin.reassemble
package:flutter/…/rendering/debug_overflow_indicator.dart:314
E/flutter (16212): #24     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #25     RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042
E/flutter (16212): #26     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #27     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #28     RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042
E/flutter (16212): #29     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #30     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #31     ContainerRenderObjectMixin.visitChildren
package:flutter/…/rendering/object.dart:3325
E/flutter (16212): #32     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #33     DebugOverflowIndicatorMixin.reassemble
package:flutter/…/rendering/debug_overflow_indicator.dart:314
E/flutter (16212): #34     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #35     ContainerRenderObjectMixin.visitChildren
package:flutter/…/rendering/object.dart:3325
E/flutter (16212): #36     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #37     RenderObject.reassemble.<anonymous closure>
package:flutter/…/rendering/object.dart:1234
E/flutter (16212): #38     RenderObjectWithChildMixin.visitChildren
package:flutter/…/rendering/object.dart:3042
E/flutter (16212): #39     RenderObject.reassemble
package:flutter/…/rendering/object.dart:1233
E/flutter (16212): #40     RenderObject.reassemble.<anonymous c
Reloaded 1 of 743 libraries in 882ms.
```

</details>

**Comment by darshankawar** [comment]
@Suryapratap-R 
Tried your code sample on latest stable, but didn't see any issue. The UI rendered properly for me.

![68710](https://user-images.githubusercontent.com/67046386/96838459-89bc3f00-1465-11eb-8607-47535648a0b2.png)

Provide your `flutter doctor -v`, device on which you are seeing the error.

**Comment by Suryapratap-R** [comment]
It crashes when you swite it to rightmost and few times

**Comment by Suryapratap-R** [comment]
It said that possible bug or lacking documentation, report so I did.

**Comment by darshankawar** [comment]
Closing this as non-issue.
