### ISSUE TITLE
Assertion during performLayout() when running layout_bench.dart

### ISSUE THREAD

**Issue by fsc8000** [flutter/flutter#6880]
## Steps to Reproduce

```
flutter run -t lib/stocks/layout_bench.dart
```

## Logs
```
$ flutter run -t lib/stocks/layout_bench.dart
Building APK in debug mode (android-arm)...         5863ms
Installing build/app.apk...                         5517ms
Syncing files to device...                          7052ms
Running lib/stocks/layout_bench.dart on Nexus 4...
I/flutter ( 6902): ┏╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍┓
I/flutter ( 6902): ┇ ⚠ THIS BENCHMARK IS BEING RUN WITH ASSERTS ENABLED ⚠  ┇
I/flutter ( 6902): ┡╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍╍┦
I/flutter ( 6902): │                                                       │
I/flutter ( 6902): │  Numbers obtained from a benchmark while asserts are  │
I/flutter ( 6902): │  enabled will not accurately reflect the performance  │
I/flutter ( 6902): │  that will be experienced by end users using release  ╎
I/flutter ( 6902): │  builds. Benchmarks should be run using this command  ┆
I/flutter ( 6902): │  line:  flutter run --release benchmark.dart          ┊
I/flutter ( 6902): │                                                        
I/flutter ( 6902): └─────────────────────────────────────────────────╌┄┈  🐢

🔥  To hot reload your app on the fly, press "r" or F5. To restart the app entirely, press "R".
The Observatory debugger and profiler is available at: http://127.0.0.1:37561/
For a more detailed help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
Syncing files to device...                           86ms
I/flutter ( 6902): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 6902): The following assertion was thrown during performLayout():
I/flutter ( 6902): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1761 pos 16:
I/flutter ( 6902): '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)' is not true.
I/flutter ( 6902): When the exception was thrown, this was the stack:
I/flutter ( 6902): #2      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1761:16)
I/flutter ( 6902): #3      VirtualViewportElement.layout (package:flutter/src/widgets/virtual_viewport.dart:193:11)
I/flutter ( 6902): #4      _VirtualPageViewportElement.layout (package:flutter/src/widgets/pageable_list.dart:521:17)
I/flutter ( 6902): #5      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1831:58)
I/flutter ( 6902): #6      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:972:15)
I/flutter ( 6902): #7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1831:13)
I/flutter ( 6902): #8      RenderList.performLayout (package:flutter/src/rendering/list.dart:156:7)
I/flutter ( 6902): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #10     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #12     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #14     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #16     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:74:11)
I/flutter ( 6902): #17     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:115:7)
I/flutter ( 6902): #18     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:144:7)
I/flutter ( 6902): #19     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:283:14)
I/flutter ( 6902): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #21     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #33     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #34     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2336:26)
I/flutter ( 6902): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #38     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:354:15)
I/flutter ( 6902): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #40     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #42     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #44     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #46     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #48     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:92:13)
I/flutter ( 6902): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1733:21)
I/flutter ( 6902): #50     RenderView.performLayout (package:flutter/src/rendering/view.dart:113:13)
I/flutter ( 6902): #51     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1609:21)
I/flutter ( 6902): #52     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:950:18)
I/flutter ( 6902): #53     main.<main_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (/data/data/com.yourcompany.microbenchmarks/cache/microbenchmarksvuaivg/lib/stocks/layout_bench.dart:34:46)
```

## Flutter Doctor
```
$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/fschneider/flutter
    • Framework revision 856fef876b (2 hours ago), 2016-11-15 14:42:52
    • Engine revision ce8b187914
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /usr/local/google/home/fschneider/Android/Sdk
    • Platform android-24, build-tools 24.0.1
    • OpenJDK Runtime Environment (build 1.8.0_102-google-v7-137518472-137512069)

[x] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • Nexus 4 • 00a422c28d51adf9 • android-arm • Android 5.1.1 (API 22)
```

**Comment by fsc8000** [comment]
@Hixie

**Comment by Hixie** [comment]
I think this is fixed now, right? The benchmark runs regularly. I'm marking this as closed. Please reopen if I'm wrong.

**Comment by Hixie** [comment]
Never mind, very much not fixed...

**Comment by Hixie** [comment]
I looked into this. It's happening because we're ending up in a build phase from layout without ever setting up a build scope. It's not unexpected. The only layout builder I saw saw for an appbar, so this might resolve itself when we port appbars.

**Comment by Hixie** [comment]
This is obsolete. I fixed the benchmark.
