### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by shindekalpesharun** [flutter/flutter#68810]
## Command
```
flutter run -d web-server
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: Permission denied, errno = 13
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:621:77)
#5      _parseAssetFromFile (package:flutter_tools/src/asset.dart:794:35)
#6      _parseAssetsFromFolder (package:flutter_tools/src/asset.dart:761:7)
#7      _parseAssets (package:flutter_tools/src/asset.dart:687:7)
#8      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:161:53)
<asynchronous suspension>
#9      _ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:718:44)
#10     _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:518:47)
<asynchronous suspension>
#11     _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart)
#12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZonedGuarded (dart:async/zone.dart:1618:12)
#17     runZoned (dart:async/zone.dart:1547:12)
#18     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#19     _ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:496:20)
<asynchronous suspension>
#20     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:616:37)
<asynchronous suspension>
```
```
[✓] Flutter (Channel dev, 1.24.0-1.0.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.24.0-1.0.pre at /home/hp/snap/flutter/common/flutter
    • Framework revision 12bea61c29 (8 days ago), 2020-10-14 15:57:04 -0700
    • Engine revision 069b3cf8f0
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/hp/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 12bea61c2902784fec73b7f5f2ff3415f873fead

**Comment by jonahwilliams** [comment]
This failure means you have an asset file in a directory that you do not have any permissions for

**Comment by jonahwilliams** [comment]
The tool shouldn't crash and should give you a better error message, but you will have to fix this yourself.

**Comment by darshankawar** [comment]
@shindekalpesharun 
This looks like file permission issue per above comment. Please verify if you have all required permission and access and then try again to see if it works.
Thanks.
