### ISSUE TITLE
warning: 'dispatch_queue_set_specific' is only available on macOS 10.7 or newer

### ISSUE THREAD

**Issue by bsr203** [flutter/flutter#68830]
After adding mac osx desktop support to my existing app, and trying out, I get below warning. It opens up a blank window after that. I am not an osx developer, but looking through xcode, I see the Deployment target is 10.11. What is the cause of this warning and not sure it causing the app is not loaded.

Thanks.
bsr.

Please see the logs and version info below

```
$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             45.5s
/Users/bsr/testprj/macos/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on macOS 10.7 or newer [-Wunguarded-availability]
        dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~                                     
In module 'Foundation' imported from /Users/bsr/testprj/macos/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/dispatch/queue.h:1498:1: note: 'dispatch_queue_set_specific' has been marked as being introduced in macOS 10.7 here, but the deployment target is macOS 10.6.0
dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,    
^                                                                       
/Users/bsr/testprj/macos/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
        dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~                                     
/Users/bsr/testprj/macos/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning: 'dispatch_get_specific' is only available on macOS 10.7 or newer [-Wunguarded-availability]
    FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                     ^~~~~~~~~~~~~~~~~~~~~
In module 'Foundation' imported from /Users/bsr/testprj/macos/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/dispatch/queue.h:1554:1: note: 'dispatch_get_specific' has been marked as being introduced in macOS 10.7 here, but the deployment target is macOS 10.6.0
dispatch_get_specific(const void *key);                                 
^                                                                       
/Users/bsr/testprj/macos/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose 'dispatch_get_specific' in an @available check to silence this warning
    FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                     ^~~~~~~~~~~~~~~~~~~~~
2 warnings generated.                                                   
error: the following command failed with exit code 0 but produced no further output
CompileC /Users/bsr/testprj/build/macos/Build/Intermediates.noindex/Pods.build/Debug/FMDB.build/Objects-normal/x86_64/FMDatabase.o /Users/bsr/testprj/macos/Pods/FMDB/src/fmdb/FMDatabase.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
note: Using new build system                                            
note: Building targets in parallel                                      
note: Planning build                                                    
note: Constructing build description                                    
Building macOS application...                                           
flutter: MissingPluginException(No implementation found for method conf on channel urcle.us/json)
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.
Receiver: null
Tried calling: host
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      main (package:beat/main.dart:75:13)
<asynchronous suspension>

Waiting for macOS to report its views...                            12ms
Syncing files to device macOS...                                   160ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on macOS is available at:
http://127.0.0.1:61281/XGOPesA_Jm0=/

Application finished.

~/testprj on master [!?]
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.1)
[✓] Connected device (4 available)

• No issues found!

~/testprj on master [!?]
$ ```

**Comment by stuartmorgan** [comment]
> /Users/bsr/testprj/macos/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning:

Issues with third-party code, such as the FMDB Pod this warning is coming from, need to be directed to the developer of that code.

Closing as this is not an issue with Flutter.
