### ISSUE TITLE
[MacOS] Error when running pod install

### ISSUE THREAD

**Issue by Nash0x7E2** [flutter/flutter#68834]
## Steps to Reproduce
This issue occurs when adding MacOS to an existing project.

1. Execute `flutter create .`
2. Run `flutter run -d macos`

## Logs
```
➜ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                           1,287ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral/.symlinks/flutter/darwin-x64`
    -> Fetching podspec for `<project_name>` from `Flutter/ephemeral/.symlinks/plugins/<project_name>/macos`
    [!] No podspec found for `<project_name>` in `Flutter/ephemeral/.symlinks/plugins/<project_name>/macos`

    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:989:in `fetch_external_source'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:968:in `block (2 levels) in fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:967:in `each'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:967:in `block in fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:966:in `fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod:23:in `load'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
```

## Flutter Doctor 
```
➜ flutter doctor -v
[✓] Flutter (Channel dev, 1.24.0-1.0.pre, on macOS 11.0 20A5395g darwin-x64, locale en-TT)
    • Flutter version 1.24.0-1.0.pre at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision 12bea61c29 (8 days ago), 2020-10-14 15:57:04 -0700
    • Engine revision 069b3cf8f0
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/nash/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/nash/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/nash/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • macOS 11.0 20A5395g darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```

**Comment by stuartmorgan** [comment]
>     -> Fetching podspec for `<project_name>` from `Flutter/ephemeral/.symlinks/plugins/<project_name>/macos`
>    [!] No podspec found for `<project_name>` in `Flutter/ephemeral/.symlinks/plugins/<project_name>/macos`

That's a very unusual name for a plugin. Did you accidentally put in a placeholder somewhere in place of a real plugin name?

Please provide your `pubspec.yaml`, and if that's a real plugin, its podspec (because if it is a plugin, it appears to be malformed).

**Comment by Nash0x7E2** [comment]
No, the project name is under NDA so I replaced the name with <project_name> as a placeholder :)

**Comment by darshankawar** [comment]
Hey @Nash0x7E2 
I was able to add, compile and run macos support for an existing project without any issues. I am on latest dev.

<img width="802" alt="Screenshot 2020-10-23 at 2 08 34 PM" src="https://user-images.githubusercontent.com/67046386/96976258-4206e780-1539-11eb-9239-a31872a0ae63.png">


<details>
<summary>log</summary>

```
dhs@Dhss-MacBook-Pro macdesk % flutter create .
Recreating project ....
Running "flutter pub get" in macdesk...                            989ms
Wrote 3 files.

All done!
[✓] Flutter: is fully installed. (Channel dev, 1.24.0-1.0.pre, on Mac OS X
    10.15.4 19E2269 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices: is fully installed.
    (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 12.0.1)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 4.0)
[✓] VS Code: is fully installed. (version 1.50.1)
[✓] Connected device: is fully installed. (4 available)

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.

dhs@Dhss-MacBook-Pro macdesk % flutter run -d macos
Downloading darwin-x64/FlutterMacOS.framework tools...              3.4s
Downloading darwin-x64-profile/FlutterMacOS.framework tools...      2,063ms
Downloading darwin-x64-profile tools...                          2,035ms
Downloading darwin-x64-release/FlutterMacOS.framework tools...      2,260ms
Downloading darwin-x64-release tools...                          1,039ms
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
Waiting for macOS to report its views...                             6ms
Syncing files to device macOS...                                    61ms



```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.24.0-1.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-1.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 12bea61c29 (8 days ago), 2020-10-14 15:57:04 -0700
    • Engine revision 069b3cf8f0
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.111

• No issues found!

```

</details>

Can you provide `pubspec.yaml` and a minimal code sample of your existing project for which you are trying to add macos support ?

**Comment by stuartmorgan** [comment]
> No, the project name is under NDA so I replaced the name with <project_name> as a placeholder :)

Well, as I said, the error message is telling you that the plugin is malformed; the podspec is either missing or invalid (e.g., named incorrectly). It's impossible for anyone without access to the plugin to figure out what exactly is wrong with it.

Closing since this is an issue in a third-party plugin, not in Flutter.

**Comment by Nash0x7E2** [comment]
Thank you for the point in the right direction! I was able to fix this after modifying the podspec.

**Comment by liudonghua123** [comment]
I write a plugin and faced the same issue, and I found that I need to create `macos` directory in main plugin directory of federated plugin using `flutter create .`

Maybe other platform like linux, windows need too.

**Comment by stuartmorgan** [comment]
> I need to create macos directory in main plugin directory of federated plugin

If your plugin is federated, only the macOS implementation package needs a `macos` directory. If you found that you had to add one to the app-facing plugin, even though that's not where the macOS implementation lives, something was wrong with your plugin metadata.

That doesn't sound related to this issue though.

**Comment by liudonghua123** [comment]
@stuartmorgan Thanks 👍, my mistake, I create both `macos` in main plugin directory and macOS implementation plugin directory, and I mixed them. 

You are right, I should delete `macos` in main plugin directory.
