### ISSUE TITLE
Updating webivew in Project but still webview blinking on clicking input text field

### ISSUE THREAD

**Issue by ycv005** [flutter/flutter#68876]
Flutter Version- 1.22.2
Testing Device- Redmi K20 Pro
Android Version- 10
Miui version- 12
Fluter webview plugin- ([official webview plugin](https://pub.dev/packages/webview_flutter) && [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)) 

## Cause (I think)

I am facing this issue either using ([official webview plugin](https://pub.dev/packages/webview_flutter) && [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)). I think either it is both plugin's issues or Hyrbid composition's issue or Lack of documentation on updating the plugin.

## Steps to Reproduce 

**Note-** When I am testing the same in the newly created project, this issue is not occuring. But when I am updating webview in the existing project, I am facing the issues. This blinking issues I was also facing before `Hybrid Compositon` arrival.

The Project is big, so I am including main files + other relevant files (If I missed any file let me know)

```
Navigator.of(context).push(MaterialPageRoute(
      builder: (context) => WebviewOfficial("https://topbestof.com/"), // "https://www.flipkart.com/" // you could use any. 
    ));
```

```
import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebviewOfficial extends StatefulWidget {
  final String url;
  const WebviewOfficial(this.url);
  @override
  _WebviewOfficialState createState() => _WebviewOfficialState();
}

class _WebviewOfficialState extends State<WebviewOfficial> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();
  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        top: true,
        child: WebView(
          initialUrl: widget.url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            _controller.complete(webViewController);
          },
        ),
      ),
    );
  }
}

```
Android Manifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.com">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.AUDIO_CAPTURE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.VIDEO_CAPTURE" />
    <uses-feature android:name="android.hardware.camera"
                  android:required="true" />


    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="example"
        android:usesCleartextTraffic="true"
        android:icon="@mipmap/logo"
        android:allowBackup="false"
        android:fullBackupContent="@xml/my_backup_rules">
        <provider
            android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
            android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
               android:name="android.support.FILE_PROVIDER_PATHS"
               android:resource="@xml/provider_paths" />
         </provider>
        <meta-data android:name="asset_statements" android:resource="@string/asset_statements" />
        <meta-data android:name="com.facebook.sdk.ApplicationId" 
            android:value="@string/facebook_app_id"/>
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@mipmap/logo" />
        
        <activity android:name="com.facebook.FacebookActivity"
            android:label="@string/app_name" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

```

## Error/Info Logs
When Clicking on the Text field input on the webview, I am getting following logs-
```
W/ContentCatcher(30220): Failed to notify a WebView
E/InputMethodManager(30220): b/117267690: Failed to get fallback IMM with expected displayId=25 actual IMM#displayId=0 
E/InputAwareWebView(30220): Can't create a proxy view because there's no container view. Text input may not work.
W/ContentCatcher(30220): Failed to notify a WebView
```

Video of the error- [Link1](https://drive.google.com/file/d/1V0qbm-7cfsFj0bb_9k8RbkGwTVNngq6g/view?usp=drivesdk), [Link2](https://drive.google.com/file/d/1UwMXC7AAoM8wwxzy9Q-nCU3ab-ziGeGt/view?usp=drivesdk)

1. Run `flutter run`.
2. Use the above code to generate.

**Expected results:** 
- Webview shouldn't repaint or blink when clicking on the text input field.

**Actual results:** 
- Webview should work normally either clicking on the text input field or not.

<details>
  <summary>Logs</summary>

```
[  +86 ms] executing: [/home/yash/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 84f3d28555368a70270e9ac8390a9441df95e752
[        ] executing: [/home/yash/snap/flutter/common/flutter/] git tag --points-at HEAD
[  +10 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.2
[   +7 ms] executing: [/home/yash/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/yash/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +34 ms] executing: [/home/yash/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +38 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +12 ms] executing: /home/yash/Android/Sdk/platform-tools/adb devices -l
[  +31 ms] List of devices attached
[   +3 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +86 ms] No supported devices connected.
[  +10 ms] "flutter run" took 156ms.
[  +15 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:353:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:933:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +256 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
Analyzing example...                                                  
No issues found! (ran in 2.4s)
```

```
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.2 at /home/yash/snap/flutter/common/flutter
    • Framework revision 84f3d28555 (8 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/yash/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
   • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /usr/local/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.1

[!] Connected device
    ! No devices available
```
</details>

**Comment by darshankawar** [comment]
@ycv005 Tried your code sample on latest dev, but didn't see the issue. The webview didn't blink or shake while tapping on any input field. I tested on Android Samsung Galaxy A2Core 8.1.0 device.

[68876.mp4.zip](https://github.com/flutter/flutter/files/5429715/68876.mp4.zip)

Could be, I am not sure, related to miui version. Can you try on any other device and see if you see similar behavior ? may be on an emulator ?

**Comment by ycv005** [comment]
@darshankawar Thanks for the quick response. As I have said above that this issue is not showing when I am creating new project, and working fine even in Redmi k20 pro (miui 12 version).

**BUT** this issue is only showing in my exisiting project where I have upgraded the plugin. Note- After upgrading the plugin the some keyboard issue has solved using with Hyrbid composition, but this blinking issue persist. Could you give me more guidance, from where does it is happening? 

Also, when I searched the Error log that is - `Can't create a proxy view because there's no container view. Text input may not work.` then I found that this was introduced in the one of the commit of the Hybrid compositoin- [One line -101](https://github.com/flutter/plugins/commit/f31d16a6ca0c4bd6849cff925a00b6823973696b) (Please do, Ctrl+F to search it). Thanks in advance.

**Comment by darshankawar** [comment]
@ycv005 
Can you try the same on latest master and see if you experience similar behavior ?

**Comment by ycv005** [comment]
How to do that? ok, I will search and implement and then tell you.

**Comment by ycv005** [comment]
I have release my app, and its automatically solved. Thanks for help
