### ISSUE TITLE
video_player is not initialize

### ISSUE THREAD

**Issue by vkpdeveloper** [flutter/flutter#68896]
### Flutter SDK Details
```
[✓] Flutter (Channel master, 1.24.0-2.0.pre.66, on Linux, locale en_IN)
    • Flutter version 1.24.0-2.0.pre.66 at /home/vkpdeveloper/snap/flutter/common/flutter
    • Framework revision 8c03ff8c1d (4 days ago), 2020-10-19 11:26:50 -0700
    • Engine revision d03b759d04
    • Dart version 2.11.0 (build 2.11.0-229.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/vkpdeveloper/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/vkpdeveloper/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/vkpdeveloper/Documents/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • LLD AL10 (mobile) • P8B4C18130005059 • android-arm64  • Android 9 (API 28)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

### Issue
```
W/MediaCodecRenderer(15272): Failed to initialize decoder: OMX.IMG.MSVDX.Decoder.AVC
W/MediaCodecRenderer(15272): android.media.MediaCodec$CodecException: start failed
W/MediaCodecRenderer(15272): 	at android.media.MediaCodec.native_start(Native Method)
W/MediaCodecRenderer(15272): 	at android.media.MediaCodec.start(MediaCodec.java:2075)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(15272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(15272): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/MediaCodecRenderer(15272): 	at android.os.Looper.loop(Looper.java:216)
W/MediaCodecRenderer(15272): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(15272): Playback error.
E/ExoPlayerImplInternal(15272): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.IMG.MSVDX.Decoder.AVC, Format(0, null, null, video/avc, avc1.42C01E, -1, null, [480, 640, -1.0], [-1, -1])
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(15272): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/ExoPlayerImplInternal(15272): 	at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(15272): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(15272): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.IMG.MSVDX.Decoder.AVC, Format(0, null, null, video/avc, avc1.42C01E, -1, null, [480, 640, -1.0], [-1, -1])
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(15272): 	... 9 more
E/ExoPlayerImplInternal(15272): Caused by: android.media.MediaCodec$CodecException: start failed
E/ExoPlayerImplInternal(15272): 	at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(15272): 	at android.media.MediaCodec.start(MediaCodec.java:2075)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
E/ExoPlayerImplInternal(15272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(15272): 	... 10 more
I/flutter (15272): Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.IMG.MSVDX.Decoder.AVC, Format(0, null, null, video/avc, avc1.42C01E, -1, null, [480, 640, -1.0], [-1, -1])

```
### What I am doing in the code
So whenever the user opens the app it will fetch data from API for feeds and then after getting it will add in provider and open the home screen and then in initState() call a new isolate with an event to initialize all the fetched API feeds video URL with the help of there model classes controller instance and then those controllers help to play and pause and work with the whole video function

```
class HomeFeed {
   ...
  VideoPlayerController controller;

```
```
try {
      controller = VideoPlayerController.network(video);
      await controller.initialize();
      controller.setLooping(false);
    } on PlatformException catch (e) {
      print(e.message);
    }
    return;
```

**Comment by darshankawar** [comment]
@vkpdeveloper 
Please provide complete minimal reproducible code sample that we can copy paste and run in IDE to see the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
