### ISSUE TITLE
Devicelab tests occasionally fail on `flutter config`

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68909]
```

------------ LOG ------------


Task failed with the following reason:
ERROR: Command "/Users/flutter/.cocoon/flutter/bin/flutter config --no-analytics --verbose" failed with exit code 1.
#0      fail (package:cocoon_agent/src/utils.dart:139:3)
#1      exec (package:cocoon_agent/src/utils.dart:321:5)
<asynchronous suspension>
#2      flutter (package:cocoon_agent/src/utils.dart:346:10)
#3      getFlutter (package:cocoon_agent/src/utils.dart:513:9)
<asynchronous suspension>
#4      getFlutterAt (package:cocoon_agent/src/utils.dart:255:9)
<asynchronous suspension>
#5      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:21)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1500:12)
#10     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#11     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
<asynchronous suspension>
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Deleting build/ directories, if any.
Deleting /Users/flutter/.cocoon/flutter/dev/benchmarks/macrobenchmarks/build
2020-10-23T11:45:23.545871: Agent ID: flutter-devicelab-mac-22020-10-23T11:45:24.141934: Observatory listening on http://127.0.0.1:20000/
2020-10-23T11:45:24.584758: Running task with a timeout of null.
2020-10-23T11:45:24.585310: 
```

I think this is different than the config call that enables analytics. Maybe this should be retried at least once?

**Comment by jonahwilliams** [comment]
@CaseyHillers could you take a look at this when you have the chance?

**Comment by godofredoc** [comment]
This is to add retries which will be handled in the migration to LUCI

**Comment by CaseyHillers** [comment]
Closing out as part of the broader cleanup with the DeviceLab migration to LUCI. Feel free to reopen is this still occurs on LUCI.
