### ISSUE TITLE
Pointer events fail

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#6891]
As of this morning, tapping the gallery home page produces this:
```
E/flutter (12563): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (12563): 'package:flutter/src/gestures/converter.dart': Failed assertion: line 195 pos 18: 'state.down' is not true.
E/flutter (12563): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:24)
E/flutter (12563): #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:31)
E/flutter (12563): #2      PointerEventConverter.expand.<expand_sync_body> (package:flutter/src/gestures/converter.dart:195:18)
E/flutter (12563): #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:66)
E/flutter (12563): #4      ListQueue.addAll (dart:collection/queue.dart:580)
E/flutter (12563): #5      BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:32:27)
E/flutter (12563): #6      _dispatchPointerDataPacket (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:73)
```

**Comment by HansMuller** [comment]
@abarth maybe this is related to https://github.com/flutter/engine/pull/3227?
