### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by ragingwind** [flutter/flutter#68958]
## Command
```
flutter --local-engine-src-path /Users/ragingwind/Workspace/_flutter/flutter/engine/src --local-engine=host_debug_unopt run -d chrome
```

## Steps to Reproduce
1. Clone flutter and engine
2. Build engine flowing this [instruction](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-macos-or-linux)
3. flutter --local-engine-src-path ~/Workspace/_flutter/flutter/engine/src --local-engine=host_debug_unopt run -d Chrome

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:89:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:89:43)
#5      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:833:57)
#6      _ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:736:54)
<asynchronous suspension>
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:518:47)
<asynchronous suspension>
#8      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart)
#9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#10     _rootRun (dart:async/zone.dart:1190:13)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _runZoned (dart:async/zone.dart:1630:10)
#13     runZonedGuarded (dart:async/zone.dart:1618:12)
#14     runZoned (dart:async/zone.dart:1547:12)
#15     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#16     _ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:496:20)
<asynchronous suspension>
#17     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:613:37)
<asynchronous suspension>
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1005:18)
#19     _rootRunUnary (dart:async/zone.dart:1198:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
```
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/ragingwind/Workspace/_flutter/flutter
    • Framework revision 198df796aa (9 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ragingwind/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /Users/ragingwind/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 198df796aa80073ef22bdf249e614e2ff33c6895

**Comment by marcfrohnhofen** [comment]
Same Problem... Can anyone help?

**Comment by Purvik** [comment]
Facing same issue. Does anyone has fixed this one?

**Comment by wechulimaven** [comment]
FileSystemException: Cannot open file, path = '/data/user/0/com.example.myPlayer/app_flutter/filesmetadata.json' (OS Error: No such file or directory, errno = 2)
 any fix

**Comment by wechulimaven** [comment]
FileSystemException: Cannot open file, path = '/data/user/0/com.example.myPlayer/app_flutter/filesmetadata.json' (OS Error: No such file or directory, errno = 2)
E/flutter (32363): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Directory listing failed, path = '/storage/emulated/0/' (OS Error: Permission denied, errno = 13)


Any help is appreciated

**Comment by kabirnayeem99** [comment]
Facing the same issue. The error is -
`Could not update files on device: FileSystemException: Cannot open file, path = '/opt/flutter/.pub-cache/hosted/pub.dartlang.org/cupertino_icons-1.0.3/assets/CupertinoIcons.ttf' (OS Error: No such file or directory, errno = 2)`.


The result of `flutter doctor -v`. 

```[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /opt/flutter
    • Framework revision f4abaa0735 (10 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alex/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/alex/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (1 available)
    • Redmi Note 7 Pro (mobile) • abcdefgh • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

My system information-

```Operating System: Arch
KDE Plasma Version: 5.22.3
KDE Frameworks Version: 5.83.0
Qt Version: 5.15.2
Kernel Version: 5.12.15-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-4200M CPU @ 2.50GHz
Memory: 11.6 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600
```

**Comment by the-thirteenth-fox** [comment]
+1

**Comment by the-thirteenth-fox** [comment]
`I/flutter ( 6539): FileSystemException: Cannot open file, path = '/data/user/0/com.example.todo_learning/app_flutter/todos.json' (OS Error: No such file or directory, errno = 2)`

**Comment by ShahanAhmedDev** [comment]
Facing the same issue seems to be Shared Preferences plugin, when I comment it out in the pubspec.yaml it works fine!

**Comment by ShahanAhmedDev** [comment]
Yea, the best thing after a whole day that worked for me, was to delete the Ios folder and then use the "flutter create ." command to re-create all the missing files. after that just do flutter clean and pub get and you should be all good to go.

**Comment by Rohit19060** [comment]
F/crash_dump64(30629): crash_dump.cpp:443] failed to get process threads: No such file or directory
Got this issue when app is running in release mode, working fine in Developer Mode

**Comment by bshanoj** [comment]
![Screenshot 2023-04-02 093246](https://user-images.githubusercontent.com/5244284/229336933-c276caab-5114-4e19-b294-565b735db468.png)

This issue is not related to Flutter. Switch off "Controlled Folder Access" under Settings > Windows Security > Virus & threat protection > Virus & Threat Protection Settings -> Manage Settings > Controlled folder access -> Manage controlled folder access.

**Comment by carpentierchloe** [comment]
Updating shared_preferences to 2.3.2 is working for me
