### ISSUE TITLE
Firebase ' The caller does not have permission to execute the specified operation'

### ISSUE THREAD

**Issue by iNeedHelpX** [flutter/flutter#68977]
Hey wondering why I'm getting this error?
The GoogleService-Info.plist is in the correct area. Also I think my code is logically wrong, but I'm not seeing it...logical errors are the best aren't they?! Basically the concept is I want to tap on the screen and have marker stored to database. This is a social app where users tap a map to indicate where something is. 

## Here's the error
```

[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation.
#0      MethodChannelQuery.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:105:7)
<asynchronous suspension>
#1      Query.get (package:cloud_firestore/src/query.dart:178:25)
#2      _HomeViewState.populateClients (package:myttcmap/screen/home_screen/home_screen.dart:58:54)
#3      _HomeViewState.initState.<anonymous closure>.<anonymous closure> (package:myttcmap/screen/home_screen/home_screen.dart:49:13)
#4      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
#5      _HomeViewState.initState.<anonymous closure> (package:myttcmap/screen/home_screen/home_screen.dart:45:9)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagat<…>
```

## Here's the section I think it wrong
```
Widget build(BuildContext context) {
    return StreamBuilder(
        stream: FirebaseFirestore.instance.collection('markers').snapshots(),
        builder: (context, snapshot) {
          if (!snapshot.hasData) return Text('loading... please wait');
          for (int i = 0; i < snapshot.data.docs.length; i++) {
            allMarkers.add(new Marker(
              markerId: snapshot.data,
              visible: true,
              position: new LatLng(snapshot.data.document[i]['loc'].latitude,
                  snapshot.data.document[i]['loc'].longitude),
              icon: createMarker(context),
            ));
          }
          // return StreamBuilder();
          // return populateClients();
          return Scaffold(
            appBar: AppBar(
              title: Text("Report fare Inspections"),
              backgroundColor: Color.fromARGB(255, 39, 104, 100),
            ),
            body: Container(
              child: mapToggle
                  ? GoogleMap(
                      markers: Set.from(allMarkers),
                      minMaxZoomPreference: MinMaxZoomPreference(15, 17),
                      initialCameraPosition: CameraPosition(
                          target: LatLng(currentLocation.latitude,
                              currentLocation.longitude),
                          zoom: 15),
                      onTap: _handleTap,
                    )
                  : LoadingPage(),
            ),
          );
        });
  }

  _handleTap(LatLng point) {
    setState(
      () {
        allMarkers.add(Marker(
          markerId: MarkerId(point.toString()),
          position: point,
          infoWindow: InfoWindow(
            title: 'INSPECTION IN PAST 10 MIN!',
          ),
          icon: custom,
        ));
        // ignore: unnecessary_statements
      },
    );
  }
}
```

**Comment by iNeedHelpX** [comment]
figured it out partially- security rules.Had to change them to allow read, write,

but still not sure about the other part of my question

**Comment by iNeedHelpX** [comment]
whoop tried and got this error 
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _TypeError was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
flutter: _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#c1c0d):
flutter: type 'QuerySnapshot' is not a subtype of type 'MarkerId'
flutter:
flutter: The relevant error-causing widget was:
flutter:   StreamBuilder<QuerySnapshot>
flutter:   file:///Users/juliapak/Documents/myttcmap/lib/screen/home_screen/home_screen.dart:88:12
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _HomeViewState.build.<anonymous closure> (package:myttcmap/screen/home_screen/home_screen.dart:94:34)
flutter: #1      StreamBuilder.build (package:flutter/src/widgets/async.dart:525:81)
flutter: #2      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:129:48)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
flutter: #13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
flutter: #14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
flutter: #15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
flutter: #17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
flutter: #21     _invoke (dart:ui/hooks.dart:251:10)
flutter: #22     _drawFrame (dart:ui/hooks.dart:209:3)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: type 'QuerySnapshot' is not a subtype of type 'MarkerId'

```

**Comment by melwinlobo18** [comment]
> markerId: snapshot.data

The `markerId` takes the value of type **MarkerId**. You can refer this [example](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/example/lib/place_marker.dart)

**Comment by melwinlobo18** [comment]
@iNeedHelpX This is not an error with the framework itself. So, please ask such questions in Stackoverflow. We have a really great community there who'll help you out 🙂

**Comment by iNeedHelpX** [comment]
i  figure :)
