### ISSUE TITLE
new gallery transition perf can run OOM on devicelab

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#68996]
The bad state/unexpected exit code from WebSocket is indicative of the VM Service crashing, which is most frequently caused by using too much memory and getting killed by the OS. This seems to be a likely cause due to the large number of demos visited and the use of an endless trace buffer.

```
stdout: [        ] > cupertino-picker@cupertino
2020-10-25T08:39:10.501112: stdout: [        ] scrolling to demo
2020-10-25T08:39:11.136617: stdout: [ +635 ms] tapping demo
2020-10-25T08:39:11.666896: stdout: [ +530 ms] tapping demo
2020-10-25T08:39:12.494416: stdout: [ +827 ms] < Success
stdout: [        ] > cupertino-pull-to-refresh@cupertino
2020-10-25T08:39:12.494612: stdout: [        ] scrolling to demo
2020-10-25T08:39:13.119969: stdout: [ +625 ms] tapping demo
2020-10-25T08:39:13.644201: stdout: [ +524 ms] tapping demo
2020-10-25T08:39:14.477860: stdout: [ +833 ms] < Success
stdout: [        ] > cupertino-segmented-control@cupertino
2020-10-25T08:39:14.477959: stdout: [        ] scrolling to demo
2020-10-25T08:39:15.119818: stdout: [ +641 ms] tapping demo
2020-10-25T08:39:15.650327: stdout: [ +530 ms] tapping demo
2020-10-25T08:39:16.484105: stdout: [ +833 ms] < Success
stdout: [        ] > cupertino-slider@cupertino
2020-10-25T08:39:16.484230: stdout: [        ] scrolling to demo
2020-10-25T08:39:17.117257: stdout: [ +630 ms] 01:53 [32m+2[0m[31m -1[0m: Flutter Gallery transitions all demos [1m[31m[E][0m[0m
2020-10-25T08:39:17.136122: stdout: [  +19 ms]   DriverError: Failed to fulfill WaitFor due to remote error
stdout: [        ]   Original error: JSON-RPC error -32000: Bad state: The client closed with pending request "ext.flutter.driver".
stdout: [        ]   Original stack trace:
stdout: [        ]   package:json_rpc_2/src/client.dart 123:62                       Client.sendRequest
stdout: [        ]   package:json_rpc_2/src/peer.dart 98:15                          Peer.sendRequest
stdout: [        ]   package:vm_service_client/src/scope.dart 64:23                  Scope.sendRequestRaw
stdout: [        ]   package:vm_service_client/src/isolate.dart 361:19               VMIsolateRef.invokeExtension
stdout: [        ]   package:flutter_driver/src/driver/vmservice_driver.dart 366:63  VMServiceFlutterDriver.sendCommand
stdout: [        ]   package:flutter_driver/src/driver/driver.dart 213:11            FlutterDriver.waitFor
stdout: [        ]   package:flutter_driver/src/driver/driver.dart 429:5             FlutterDriver.scrollUntilVisible
stdout: [        ]   test_driver/transitions_perf_test.dart 170:18                   runDemos
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   test_driver/transitions_perf_test.dart 333:13                   main.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   test_driver/transitions_perf_test.dart                          main.<fn>.<fn>
2020-10-25T08:39:17.137297: stdout: [        ]   package:test_api/src/backend/declarer.dart 175:19               Declarer.test.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   package:test_api/src/backend/declarer.dart                      Declarer.test.<fn>.<fn>
2020-10-25T08:39:17.144869: stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                    _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                    runZoned
stdout: [        ]   package:test_api/src/backend/declarer.dart 173:13               Declarer.test.<fn>
stdout: [        ]   package:test_api/src/backend/invoker.dart 231:15                Invoker.waitForOutstandingCallbacks.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                    _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                    runZoned
stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                 Invoker.waitForOutstandingCallbacks
stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17                Invoker._onRun.<fn>.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   package:test_api/src/backend/invoker.dart                       Invoker._onRun.<fn>.<fn>.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                    _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                    runZoned
stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                 Invoker._onRun.<fn>.<fn>
stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15                Invoker._guardIfGuarded
stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                 Invoker._onRun.<fn>
stdout: [        ]   package:stack_trace/src/chain.dart 104:24                       Chain.capture.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                    _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                    runZoned
stdout: [        ]   package:stack_trace/src/chain.dart 102:12                       Chain.capture
stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11                Invoker._onRun
stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11   LiveTestController.run
stdout: [        ]   dart:async/future.dart 201:37                                   new Future.microtask.<fn>
stdout: [        ]   dart:async/zone.dart 1182:47                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 997:7                                      _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 1037:23                                    _CustomZone.bindCallbackGuarded.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 997:7                                      _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 1037:23                                    _CustomZone.bindCallbackGuarded.<fn>
stdout: [        ]   dart:async/schedule_microtask.dart 41:21                        _microtaskLoop
stdout: [        ]   dart:async/schedule_microtask.dart 50:5                         _startMicrotaskLoop
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 118:13                    _runPendingImmediateCallback
stdout: [        ]   dart:isolate-patch/timer_impl.dart 404:11                       _Timer._runTimers
stdout: [        ]   dart:isolate-patch/timer_impl.dart 428:5                        _Timer._handleMessage
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 168:12                    _RawReceivePortImpl._handleMessage
stdout: [        ]   package:flutter_driver/src/driver/vmservice_driver.dart 377:7  VMServiceFlutterDriver.sendCommand
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
stdout: [        ]   package:flutter_driver/src/driver/driver.dart 429:5            FlutterDriver.scrollUntilVisible
stdout: [        ]   test_driver/transitions_perf_test.dart 170:18                  runDemos
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
stdout: [        ]   test_driver/transitions_perf_test.dart 333:13                  main.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
stdout: [        ]   test_driver/transitions_perf_test.dart                         main.<fn>.<fn>
stdout: [        ]   package:test_api/src/backend/declarer.dart 175:19              Declarer.test.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
stdout: [        ]   package:test_api/src/backend/declarer.dart                     Declarer.test.<fn>.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
stdout: [        ]   package:test_api/src/backend/declarer.dart 173:13              Declarer.test.<fn>
stdout: [        ]   package:test_api/src/backend/invoker.dart 231:15               Invoker.waitForOutstandingCallbacks.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                Invoker._onRun.<fn>.<fn>
stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15               Invoker._guardIfGuarded
stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                Invoker._onRun.<fn>
stdout: [        ]   package:stack_trace/src/chain.dart 104:24                      Chain.capture.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
stdout: [        ]   package:stack_trace/src/chain.dart 102:12                      Chain.capture
stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11               Invoker._onRun
stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11  LiveTestController.run
stdout: [        ]   dart:async/future.dart 201:37                                  new Future.microtask.<fn>
stdout: [        ]   dart:async/zone.dart 1182:47                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
stdout: [        ]   dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
stdout: [        ]   dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
stdout: [        ]   dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
stdout: [        ]   dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
2020-10-25T08:39:17.146214: stdout: [        ]   DriverError: Failed to fulfill Scroll due to remote error
stdout: [        ]   Original error: JSON-RPC error -32000: Bad state: The client closed with pending request "ext.flutter.driver".
stdout: [        ]   Original stack trace:
stdout: [        ]   package:json_rpc_2/src/client.dart 123:62                       Client.sendRequest
stdout: [        ]   package:json_rpc_2/src/peer.dart 98:15                          Peer.sendRequest
stdout: [        ]   package:vm_service_client/src/scope.dart 64:23                  Scope.sendRequestRaw
stdout: [        ]   package:vm_service_client/src/isolate.dart 361:19               VMIsolateRef.invokeExtension
stdout: [        ]   package:flutter_driver/src/driver/vmservice_driver.dart 366:63  VMServiceFlutterDriver.sendCommand
stdout: [        ]   package:flutter_driver/src/driver/driver.dart 373:11            FlutterDriver.scroll
stdout: [        ]   package:flutter_driver/src/driver/driver.dart 432:13            FlutterDriver.scrollUntilVisible
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   test_driver/transitions_perf_test.dart 170:18                   runDemos
2020-10-25T08:39:17.146610: stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   test_driver/transitions_perf_test.dart 333:13                   main.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
2020-10-25T08:39:17.147565: stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   test_driver/transitions_perf_test.dart                          main.<fn>.<fn>
stdout: [        ]   package:test_api/src/backend/declarer.dart 175:19               Declarer.test.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   package:test_api/src/backend/declarer.dart                      Declarer.test.<fn>.<fn>
2020-10-25T08:39:17.147942: stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                    _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                    runZoned
stdout: [        ]   package:test_api/src/backend/declarer.dart 173:13               Declarer.test.<fn>
2020-10-25T08:39:17.148159: stdout: [        ]   package:test_api/src/backend/invoker.dart 231:15                Invoker.waitForOutstandingCallbacks.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                    _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                    runZoned
2020-10-25T08:39:17.148397: stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                 Invoker.waitForOutstandingCallbacks
stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17                Invoker._onRun.<fn>.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                    _CustomZone.registerUnaryCallback
2020-10-25T08:39:17.155544: stdout: [        ]   dart:async-patch/async_patch.dart 83:23                         _asyncThenWrapperHelper
stdout: [        ]   package:test_api/src/backend/invoker.dart                       Invoker._onRun.<fn>.<fn>.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                    _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                    runZoned
stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                 Invoker._onRun.<fn>.<fn>
stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15                Invoker._guardIfGuarded
stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                 Invoker._onRun.<fn>
stdout: [        ]   package:stack_trace/src/chain.dart 104:24                       Chain.capture.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                    _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                    runZoned
stdout: [        ]   package:stack_trace/src/chain.dart 102:12                       Chain.capture
stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11                Invoker._onRun
stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11   LiveTestController.run
stdout: [        ]   dart:async/future.dart 201:37                                   new Future.microtask.<fn>
stdout: [        ]   dart:async/zone.dart 1182:47                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 997:7                                      _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 1037:23                                    _CustomZone.bindCallbackGuarded.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                    _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                    _CustomZone.run
stdout: [        ]   dart:async/zone.dart 997:7                                      _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 1037:23                                    _CustomZone.bindCallbackGuarded.<fn>
stdout: [        ]   dart:async/schedule_microtask.dart 41:21                        _microtaskLoop
stdout: [        ]   dart:async/schedule_microtask.dart 50:5                         _startMicrotaskLoop
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 118:13                    _runPendingImmediateCallback
stdout: [        ]   dart:isolate-patch/timer_impl.dart 404:11                       _Timer._runTimers
stdout: [        ]   dart:isolate-patch/timer_impl.dart 428:5                        _Timer._handleMessage
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 168:12                    _RawReceivePortImpl._handleMessage
stdout: [        ]   package:flutter_driver/src/driver/vmservice_driver.dart 377:7  VMServiceFlutterDriver.sendCommand
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
stdout: [        ]   ===== asynchronous gap ===========================
stdout: [        ]   dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
stdout: [        ]   dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                Invoker._onRun.<fn>.<fn>
stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15               Invoker._guardIfGuarded
stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                Invoker._onRun.<fn>
stdout: [        ]   package:stack_trace/src/chain.dart 104:24                      Chain.capture.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 1630:10                                   _runZoned
stdout: [        ]   dart:async/zone.dart 1550:10                                   runZoned
stdout: [        ]   package:stack_trace/src/chain.dart 102:12                      Chain.capture
stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11               Invoker._onRun
stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11  LiveTestController.run
stdout: [        ]   dart:async/future.dart 201:37                                  new Future.microtask.<fn>
stdout: [        ]   dart:async/zone.dart 1182:47                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                                   _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                                   _CustomZone.run
stdout: [        ]   dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
stdout: [        ]   dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
stdout: [        ]   dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
stdout: [        ]   dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
stdout: [        ]   dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
stdout: [        ]   dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
2020-10-25T08:39:17.156579: stderr: [   +2 ms] VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
stderr: [        ] VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005
stdout: [        ] 01:53 [32m+2[0m[31m -1[0m: Flutter Gallery transitions (tearDownAll)[0m
2020-10-25T08:39:17.166849: stdout: [  +11 ms] 01:53 [32m+2[0m[31m -1[0m: [31mSome tests failed.[0m
2020-10-25T08:39:17.167992: stderr: [   +1 ms] Unhandled exception:
stderr: [        ] Dummy exception to set exit code.
2020-10-25T08:39:17.265258: stdout: [  +97 ms] Stopping application instance.
stdout: [        ] Stopping application.
2020-10-25T08:39:17.265366: stdout: [        ] executing: /Users/flutter/.cocoon/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --id b579ee2d16e30f86651249dc51e4ebef46d36ac0 --uninstall_only --bundle_id io.flutter.demo.gallery
2020-10-25T08:39:17.275327: stdout: [   +9 ms] [....] Waiting for iOS device to be connected
2020-10-25T08:39:39.282839: stdout: [+22007 ms] [....] Using b579ee2d16e30f86651249dc51e4ebef46d36ac0 (N71AP, iPhone 6s, iphoneos, arm64) a.k.a. 'iPhone'.
stdout: [        ] ------ Uninstall phase ------
2020-10-25T08:39:43.994922: stdout: [+4712 ms] [ OK ] Uninstalled package with bundle id io.flutter.demo.gallery
2020-10-25T08:39:44.005269: stdout: [  +10 ms] "flutter drive" took 298,559ms.
2020-10-25T08:39:44.008427: stderr: [   +3 ms] Driver tests failed: 255
2020-10-25T08:39:44.008873: stderr: [        ] 
stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
stderr:            #1      _runTests (package:flutter_tools/src/commands/drive.dart:563:5)
stderr:            <asynchronous suspension>
stderr:            #2      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:352:23)
stderr:            <asynchronous suspension>
stderr:            #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1029:18)
stderr:            <asynchronous suspension>
stderr:            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:892:33)
stderr:            <asynchronous suspension>
stderr:            #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
stderr:            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
stderr:            #7      _rootRun (dart:async/zone.dart:1190:13)
stderr:            #8      _CustomZone.run (dart:async/zone.dart:1093:19)
stderr:            #9      _runZoned (dart:async/zone.dart:1630:10)
stderr:            #10     runZoned (dart:async/zone.dart:1550:10)
stderr:            #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
stderr:            #12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:881:20)
stderr:            #13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
stderr:            #14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
stderr:            #15     _rootRunUnary (dart:async/zone.dart:1198:47)
stderr:            #16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
stderr:            #17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
stderr:            #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
stderr:            #19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
stderr:            #20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
stderr:            #21     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
stderr:            #22     _rootRun (dart:async/zone.dart:1190:13)
stderr:            #23     _CustomZone.run (dart:async/zone.dart:1093:19)
stderr:            #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
stderr:            #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
stderr:            #26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
stderr:            #27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
stderr:            #28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
stderr:            #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
stderr: 
stderr: 
2020-10-25T08:39:44.010029: stdout: [   +1 ms] ensureAnalyticsSent: 0ms
2020-10-25T08:39:44.011209: stdout: [   +1 ms] Running shutdown hooks
2020-10-25T08:39:44.011355: stdout: [        ] Shutdown hooks complete
2020-10-25T08:39:44.013317: stdout: [   +1 ms] exiting with code 255
2020-10-25T08:39:44.028441: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 255
2020-10-25T08:39:44.035956: Task failed: Executable "/Users/flutter/.cocoon/flutter/bin/flutter" failed with exit code 255.2020-10-25T08:39:44.036224: 

Stack trace:
```

**Comment by chinmaygarde** [comment]
This seems to be the expected side-effect of using an endless trace buffer? Are there alternatives?

**Comment by jonahwilliams** [comment]
One alternative is to not run this test, or to break it into smaller test cases

**Comment by pcsosinski** [comment]
what needs to happen to get this closed?

**Comment by zanderso** [comment]
These benchmarks seem to be doing okay except on ios32 where there have been no runs in a long time. I am dropping this to P3, and maybe @liyuqian or @CareF can shed some light about what is happening on ios32.

**Comment by liyuqian** [comment]
According to go/flutter-devicelab-hardware, mac11 is the only bot with the ios32 device. However, mac11 is missing from https://flutter-dashboard.appspot.com/#/agents at the moment, and I believe it's probably missing for months...

I remember there was a discussion about marking ios32 tests as flaky and just have go/flutter-gardener monitor those tests manually. I'm not sure if the recent gardener has reacted to this incidence already? CC @jmagman 

Also, I'm curious if the infra metrics should track the worst queue time in addition to 90th percentile queue time. The worst queue time would catch this incidence early on. CC @keyonghan @godofredoc

**Comment by godofredoc** [comment]
obsolete
