### ISSUE TITLE
flutter and firebase duo wow! wow ! wo jus will be throwing annoying errors! poor loosely coupled firebase API i observed many times fail to response mongodb is mongodb i was mad to choose firebase.

### ISSUE THREAD

**Issue by unfoldedRoses** [flutter/flutter#68993]
body: CustomScrollView(slivers: [
          StreamBuilder<QuerySnapshot>(
              stream: Firestore.instance
                  .collection("items")
                  .limit(15)
                  .orderBy("publishedDate", descending: true)
                  .snapshots(),
              builder: (context, dataSnapshot) {
                return !dataSnapshot.hasData
                    ? SliverToBoxAdapter(
                        child: Center(
                          child: circularProgress(),
                        ),
                      )
                    : SliverStaggeredGrid.countBuilder(
                        crossAxisCount: 1,
                        staggeredTileBuilder: (c) => StaggeredTile.fit(1),
                        itemBuilder: (context, index) {
                          ItemModel model = ItemModel.fromJson(
                              dataSnapshot.data.documents[index].data);
                          return sourceInfo(model, context);
                        },
                        itemCount: dataSnapshot.data.documents.length,
                      );
              })
        ]),

///////////////////////////////////STACK TRACES/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
+37 ms] I/flutter (23538): When the exception was thrown, this was the stack:
[   +5 ms] I/flutter (23538): #2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1683:12)
[  +20 ms] I/flutter (23538): #3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:955:17)
[   +6 ms] I/flutter (23538): #4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2994:48)
[   +1 ms] I/flutter (23538): #5      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1191:43)
[  +41 ms] I/flutter (23538): #6      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1126:14)
[   +1 ms] I/flutter (23538): #7      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1317:39)
[   +1 ms] I/flutter (23538): #8      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1126:14)
[        ] I/flutter (23538): #9      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:960:11)
[   +2 ms] I/flutter (23538): #10     FlutterError.onError.<anonymous closure> (package:flutter/src/foundation/assertions.dart:877:90)       
[   +3 ms] I/flutter (23538): #11     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1092:15)
[  +24 ms] I/flutter (23538): #12     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1311:18)
[   +4 ms] I/flutter (23538): #13     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1637:7)
[   +2 ms] I/flutter (23538): #14     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
[  +32 ms] I/flutter (23538): #15     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:436:19)
[  +32 ms] I/flutter (23538): #16     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
[   +1 ms] I/flutter (23538): #17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)      
[   +4 ms] I/flutter (23538): #18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
[  +26 ms] I/flutter (23538): #19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
[  +43 ms] I/flutter (23538): #20     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
[   +3 ms] I/flutter (23538): #24     _invoke (dart:ui/hooks.dart:251:10)
[   +1 ms] I/flutter (23538): #25     _drawFrame (dart:ui/hooks.dart:209:3)
[   +2 ms] I/flutter (23538): (elided 5 frames from class _AssertionError and dart:async)
[   +7 ms] I/flutter (23538): ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +38 ms] W/m.praveen.esho(23538): Verification of java.lang.String
io.grpc.internal.AbstractManagedChannelImplBuilder.checkAuthority(java.lang.String) took 116.166ms
[   +9 ms] I/flutter (23538): Another exception was thrown: RenderBox.size accessed beyond the scope of resize, layout, or permitted parent
access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they   
have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout().
[ +417 ms] W/m.praveen.esho(23538): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
[   +1 ms] W/m.praveen.esho(23538): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard;
(greylist,core-platform-api, linking, allowed)
[  +24 ms] W/m.praveen.esho(23538): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V
(greylist,core-platform-api, linking, allowed)
[   +3 ms] W/m.praveen.esho(23538): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
[ +185 ms] W/m.praveen.esho(23538): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V
(greylist, reflection, allowed)
[  +68 ms] W/m.praveen.esho(23538): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy;
(greylist,core-platform-api, linking, allowed)
[  +15 ms] W/m.praveen.esho(23538): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)

**Comment by TahaTesser** [comment]
Hi @unfoldedRoses 
This seems like an issue from your code, can you reproduce this without using Firebase

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample

If not, please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
