### ISSUE TITLE
type 'RenderPointerListener' is not a subtype of type 'RenderRepaintBoundary'

### ISSUE THREAD

**Issue by noteScript** [flutter/flutter#69030]
Dart version:

```bash
Dart SDK version: 2.10.2 (stable) (Tue Oct 13 15:50:27 2020 +0200) on "macos_x64"
```
Flutter version:

```bash
Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (11 天前) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
```

Flutter doctor:
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
 
[✓] Connected device (1 available)            

! Doctor found issues in 1 category.

```
Code:
```dart
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'dart:math' as math;
import 'package:flutter/rendering.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';

import '../utils/dialog.dart';
import '../setup/config.dart';
// AppConfig.navigatorKey = new GlobalKey();
class SaveImages{

  static Future<bool> get permission{
    return Permission.storage.status.then((status){
    if (status.isUndetermined) {
      openAppSettings();// 没有权限打开设置页面
      return false;
    }

    return status.isUndetermined;
    });
  }

  static Future<void> saveScreen({ String name, hasToast = true }) async{ // 保存截图

    RenderRepaintBoundary boundary = AppConfig.navigatorKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);

    if (!await permission){
      return hasToast? Talk.toast('尚未获取到相册权限') : false;
    }

    return ImageGallerySaver.saveImage(
        Uint8List.fromList(byteData.buffer.asUint8List()),
        quality: 60,
        name: name ?? math.Random().nextInt(1000).toString()
    ).catchError((error) => hasToast ? Talk.toast('sucess') : false)
    .then((value) => hasToast ? Talk.toast('failed') : true);
  }
}
```

Error:
```bash
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'RenderPointerListener' is not a subtype of type 'RenderRepaintBoundary'
#0      SaveImages.saveScreen (package:nio/plugins/saveImages.dart:26:27)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#9      PointerRouter._dispatchEventToRoutes.<ano<…>
```

**Comment by darshankawar** [comment]
@noteScript 
`permission_handler` and `image_gallery_saver` are 3rd party plugins. Please recheck your code without using these plugins and see if you get same exception. If not, then the issue could be with the plugins and you may need to open this issue in their repos. 
If you still get the same error after removing 3rd party plugin code, please provide the updated code sample that doesn't contain the plugin code that shows the issue.
Thanks.

**Comment by noteScript** [comment]
hello,@darshankawar 
```dart
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'dart:math' as math;
import 'package:flutter/rendering.dart';
// import 'package:permission_handler/permission_handler.dart';
// import 'package:image_gallery_saver/image_gallery_saver.dart';

import '../utils/dialog.dart';
import '../setup/config.dart';

class SaveImages{

  /*static Future<bool> get permission{
    return Permission.storage.status.then((status){
    if (status.isUndetermined) {
      openAppSettings();// 没有权限打开设置页面
      return false;
    }

    return status.isUndetermined;
    });
  }*/

  static Future<void> saveScreen({ String name, hasToast = true }) async{ // 保存截图

    RenderRepaintBoundary boundary = AppConfig.navigatorKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);

    /*if (!await permission){
      return hasToast? Talk.toast('尚未获取到相册权限') : false;
    }*/

    /*return ImageGallerySaver.saveImage(
        Uint8List.fromList(byteData.buffer.asUint8List()),
        quality: 60,
        name: name ?? math.Random().nextInt(1000).toString()
    ).catchError((error) => hasToast ? Talk.toast('failed') : false)
    .then((value) => hasToast ? Talk.toast('sucess') : true);*/
  }
}
```

The above code still reports an error：
```bash
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'RenderPointerListener' is not a subtype of type 'RenderRepaintBoundary'
#0      SaveImages.saveScreen (package:nio/plugins/saveImages.dart:26:27)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
#2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
#6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
#9      PointerRouter._dispatchEventToRoutes.<ano<…>

```

**Comment by darshankawar** [comment]
@noteScript Still it doesn't seem to be a complete code sample. Getting compile error on `AppConfig`.
I'd suggest you ask this question on StackOverflow, because it seems to be a code implementation issue.
I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.
