### ISSUE TITLE
[firebase-cloud-firestore] FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by chauhannaman98** [flutter/flutter#69130]
## Steps to Reproduce

1. Clone the repository from [here](https://github.com/chauhannaman98/flash-chat).
2. Add your `google-services.json` for firebase project.
3. Run `flutter run -v`. You'll get an exception while Gradle build.

I made [this](https://github.com/chauhannaman98/flash-chat/commit/908675d035aba64a0399594867fcf6c3a5ffaab8) commit for adding the dependencies in my android project.

**Expected results:** I expected the application build successful and app running normally on my emulator.

**Actual results:** The command `flutter run` failed after it showed up an error.

<details>
  <summary>Error on running app</summary>

```
[ +109 ms] executing: [/home/techmirtz/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 84f3d28555368a70270e9ac8390a9441df95e752
[        ] executing: [/home/techmirtz/snap/flutter/common/flutter/] git tag --points-at HEAD
[  +12 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.2
[   +7 ms] executing: [/home/techmirtz/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/techmirtz/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +36 ms] executing: [/home/techmirtz/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb devices -l
[  +37 ms] List of devices attached
           J7AAGF06T826H7Z        device usb:1-1 product:WW_X00TD model:ASUS_X00TD device:ASUS_X00T_2 transport_id:2
[  +13 ms] /home/techmirtz/Android/Sdk/platform-tools/adb -s J7AAGF06T826H7Z shell getprop
[ +127 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +28 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +182 ms] Found plugin cloud_firestore at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.1+3/
[   +9 ms] Found plugin cloud_firestore_web at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+4/
[  +15 ms] Found plugin firebase_auth at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.1+2/
[   +9 ms] Found plugin firebase_auth_web at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.1+1/
[   +2 ms] Found plugin firebase_core at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0+1/
[  +13 ms] Found plugin firebase_core_web at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[ +333 ms] Found plugin cloud_firestore at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.14.1+3/
[   +2 ms] Found plugin cloud_firestore_web at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.2.0+4/
[   +4 ms] Found plugin firebase_auth at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.1+2/
[   +3 ms] Found plugin firebase_auth_web at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.1+1/
[   +2 ms] Found plugin firebase_core at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0+1/
[   +3 ms] Found plugin firebase_core_web at /home/techmirtz/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[  +59 ms] Generating /home/techmirtz/projects/Flutter/flutter_apps/flash_chat/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +25 ms] ro.hardware = qcom
[  +30 ms] Starting incremental build...
[   +3 ms] Initializing file store
[  +23 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +4 ms] Launching lib/main.dart on ASUS X00TD in debug mode...
[   +5 ms] /home/techmirtz/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/techmirtz/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/techmirtz/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tools.UBSYHM/flutter_tool.NRVHTX/app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +16 ms] executing: /home/techmirtz/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /home/techmirtz/projects/Flutter/flutter_apps/flash_chat/build/app/outputs/flutter-apk/app.apk
AndroidManifest.xml
[  +97 ms] Exit code 0 from: /home/techmirtz/Android/Sdk/build-tools/29.0.2/aapt dump xmltree
/home/techmirtz/projects/Flutter/flutter_apps/flash_chat/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="com.techmirtz.flash_chat" (Raw: "com.techmirtz.flash_chat")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="flash_chat" (Raw: "flash_chat")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.techmirtz.flash_chat.MainActivity" (Raw: "com.techmirtz.flash_chat.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +11 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb -s J7AAGF06T826H7Z shell -x logcat -v time -t 1
[  +89 ms] Exit code 0 from: /home/techmirtz/Android/Sdk/platform-tools/adb -s J7AAGF06T826H7Z shell -x logcat -v time -t 1
[        ] --------- beginning of main
           10-28 00:15:57.052 W/Bugle   (13674): BuglePhoneNumberUtils: canonicalizeMccMnc: invalid mccmnc. mcc: null, mnc: null
[   +4 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb -s J7AAGF06T826H7Z shell -x logcat -v time -t 1
[  +83 ms] Exit code 0 from: /home/techmirtz/Android/Sdk/platform-tools/adb -s J7AAGF06T826H7Z shell -x logcat -v time -t 1
[        ] --------- beginning of main
           10-28 00:15:57.137 I/BugleRcsEngine(13674): [8934] zvx.b: Reinitialize CSLib Flags: com.google.android.ims.library
[  +30 ms] <- compile package:flash_chat/main.dart
[  +45 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb version
[  +22 ms] Android Debug Bridge version 1.0.41
           Version 30.0.4-6686687
           Installed as /home/techmirtz/Android/Sdk/platform-tools/adb
[   +8 ms] executing: /home/techmirtz/Android/Sdk/platform-tools/adb start-server
[  +31 ms] Building APK
[  +33 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from /home/techmirtz/projects/Flutter/flutter_apps/flash_chat/android/gradlew.
[   +1 ms] /home/techmirtz/projects/Flutter/flutter_apps/flash_chat/android/gradlew mode: 33277 rwxrwxr-x.
[  +12 ms] executing: /home/techmirtz/android-studio/jre/bin/java -version
[ +105 ms] Exit code 0 from: /home/techmirtz/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +1 ms] executing: [/home/techmirtz/projects/Flutter/flutter_apps/flash_chat/android/] /home/techmirtz/projects/Flutter/flutter_apps/flash_chat/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=/home/techmirtz/projects/Flutter/flutter_apps/flash_chat/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
assembleDebug
[+21948 ms] FAILURE: Build failed with an exception.
[  +41 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':firebase_core:compileDebugAidl'.
[        ] > Could not resolve all task dependencies for configuration ':firebase_core:debugCompileClasspath'.
[        ]    > Could not resolve com.google.auto.value:auto-value-annotations:1.6.5.
[        ]      Required by:
[        ]          project :firebase_core > com.google.firebase:firebase-common:19.3.0
[        ]       > Could not resolve com.google.auto.value:auto-value-annotations:1.6.5.
[        ]          > Could not parse POM https://jcenter.bintray.com/com/google/auto/value/auto-value-annotations/1.6.5/auto-value-annotations-1.6.5.pom
[        ]             > Could not resolve com.google.auto.value:auto-value-parent:1.6.5.
[        ]                > Could not resolve com.google.auto.value:auto-value-parent:1.6.5.
[        ]                   > Could not parse POM https://jcenter.bintray.com/com/google/auto/value/auto-value-parent/1.6.5/auto-value-parent-1.6.5.pom
[        ]                      > Could not resolve com.google.auto:auto-parent:7.
[        ]                         > Could not resolve com.google.auto:auto-parent:7.
[        ]                            > Could not load module metadata from
/home/techmirtz/.gradle/caches/modules-2/metadata-2.71/descriptors/com.google.auto/auto-parent/7/475b59a03ea03e6388c8f34eee6a9d08/descriptor.bin
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 21s
[+2062 ms] Running Gradle task 'assembleDebug'... (completed in 24.2s)
[   +9 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 25,666ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #23     _rootRunUnary (dart:async/zone.dart:1198:47)
           #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #30     _rootRun (dart:async/zone.dart:1190:13)
           #31     _CustomZone.run (dart:async/zone.dart:1093:19)
           #32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +3 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +16 ms] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

<details>
  <summary>`flutter analyze`</summary>

```
Analyzing flash_chat...                                                 
No issues found! (ran in 42.2s)
```
</details>

<details>
  <summary>`flutter doctor -v`</summary>

```
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.2 at /home/techmirtz/snap/flutter/common/flutter
    • Framework revision 84f3d28555 (12 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/techmirtz/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/techmirtz/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /home/techmirtz/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • ASUS X00TD (mobile) • <Serial Number> • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```
</details>

**Comment by darshankawar** [comment]
@chauhannaman98 
Firebase related issues are tracked in separate repo. Please consider opening this issue here : https://github.com/FirebaseExtended/flutterfire/issues

Closing this from here.
