### ISSUE TITLE
Flake on docs shard during upload

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69131]
```
No unresolved dartdoc directives detected.

Creating a custom index.html in dev/docs/doc/index.html

Docs ready to go!
Unhandled exception:
Connection closed while receiving data
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:50:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:16:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:282:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:441:16)
#5      _RootZone.runBinaryGuarded (dart:async/zone.dart:1396:10)
#6      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#7      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#8      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#9      _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:132:11)
#10     _addErrorWithReplacement (dart:async/stream_pipe.dart:180:8)
#11     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:287:11)
#12     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#13     _RootZone.runBinaryGuarded (dart:async/zone.dart:1396:10)
#14     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#15     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#16     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#17     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:812:19)
#18     _StreamController._addError (dart:async/stream_controller.dart:690:7)
#19     _StreamController.addError (dart:async/stream_controller.dart:642:5)
#20     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1158:22)
#21     _HttpParser._onDone (dart:_http/http_parser.dart:865:9)
#22     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#23     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#24     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#25     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#26     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
#27     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
#28     _StreamController.close (dart:async/stream_controller.dart:664:5)
#29     _Socket._onData (dart:io-patch/socket_patch.dart:1976:21)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#34     _StreamController._add (dart:async/stream_controller.dart:682:7)
#35     _StreamController.add (dart:async/stream_controller.dart:624:5)
#36     _RawSecureSocket._closeHandler (dart:io/secure_socket.dart:794:21)
#37     _RawSecureSocket._tryFilter.<anonymous closure> (dart:io/secure_socket.dart:924:11)
#38     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#39     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#41     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#42     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#43     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by jonahwilliams** [comment]
This looks like package:http crashed in a way that can't be caught. FYI @kevmoo ?

**Comment by kevmoo** [comment]
https://github.com/dart-lang/http/blob/a8efbef05a58919dc7aa2dab42198334f2459ffb/lib/src/io_client.dart#L48-L51

A good bug to file. I'm guessing `response.handleError` has a stack param that's not used and that could be used for debugging...

**Comment by godofredoc** [comment]
@jonahwilliams can you please add a link to the failing task?

**Comment by pcsosinski** [comment]
what needs to happen to get this closed?

**Comment by godofredoc** [comment]
We don't have a link to the builder or task to be able to triage further this bug. Closing as obsolete, please reopen if this is still an issue and please provide links to logs.
