### ISSUE TITLE
Fuchsia devices not discovered after installing a new build

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#69140]
Run1: https://ci.chromium.org/p/flutter/builders/try/Linux%20Fuchsia/16807?
Run2: https://ci.chromium.org/p/flutter/builders/try/Linux%20Fuchsia/16810?

The 3rd run passed (https://ci.chromium.org/p/flutter/builders/try/Linux%20Fuchsia/16829?).

**Comment by keyonghan** [comment]
Recipe crashed at point 'Uncaught exception'

```
Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 555, in run_steps
    raw_result = recipe_obj.run_steps(api, engine)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/recipe_deps.py", line 751, in run_steps
    recipe_result = self.global_symbols['RunSteps'](*args)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/engine.py", line 1571, in RunSteps
    BuildFuchsia(api)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/engine.py", line 939, in BuildFuchsia
    BuildAndTestFuchsia(api, build_script, git_rev)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/engine.py", line 181, in BuildAndTestFuchsia
    TestFuchsia(api)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/engine.py", line 812, in TestFuchsia
    raise_on_failure=True
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 597, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/fuchsia/recipe_modules/display_util/api.py", line 59, in display_tasks
    metadata=metadata,
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 597, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/fuchsia/recipe_modules/display_util/api.py", line 144, in _display
    process_func(**args)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 597, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/fuchsia/recipe_modules/display_util/api.py", line 96, in _process_task
    with self.m.step.nest(result.name) as display_step:
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_modules/step/api.py", line 279, in nest
    with self.step_client.parent_step(name) as (pres, children_presentations):
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 340, in parent_step
    _log_crash(self._stream_engine, "parent_step(%r)" % (name_tokens))
TypeError: not all arguments converted during string formatting
```

Do you have any idea about this crash? @godofredoc

**Comment by godofredoc** [comment]
This is because the fuchsia devices are not coming back after installing the new version. https://chromium-swarm.appspot.com/task?id=4f83cb6ea10deb10

If this is failing consistently I'd suggest reverting the last fuchsia_sdk roll

**Comment by keyonghan** [comment]
Reran the builder on tot, and got a pass. Now engine tree is open.
Will keep monitoring before closing.
 (some context, all fuchsia bots were down until around 11:30 this morning.)

**Comment by iskakaushik** [comment]
@keyonghan still seeing it: https://ci.chromium.org/p/flutter/builders/try/Linux%20Fuchsia/16918?

**Comment by keyonghan** [comment]
Also noticed failure on post-commit builds:
[build 6038](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/6038), and it failed on step: [`Trigger Fuchsia Tests`](https://chromium-swarm.appspot.com/task?id=4f8ac32553514110)
```
+ for i in {1..10}
+ fuchsia_ctl ssh --identity-file /etc/botanist/keys/id_rsa_infra -c 'echo up'
+ ./fuchsia_ctl -d nanny-iron-shiny-widen ssh --identity-file /etc/botanist/keys/id_rsa_infra -c 'echo up'
Unhandled exception:
Failed to get target IP for nanny-iron-shiny-widen
#0      DevFinder._runDevFinderWithRetries (package:fuchsia_ctl/src/dev_finder.dart:60)
#1      _RootZone.runUnary (dart:async/zone.dart:1381)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:139)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680)
#4      Future._propagateToListeners (dart:async/future_impl.dart:709)
#5      Future._complete (dart:async/future_impl.dart:514)
#6      new Future.delayed.<anonymous closure> (dart:async/future.dart:313)
#7      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23)
#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384)
#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174)
```

Checked the same bot `nanny-iron-shiny-widen`, and it also has successful build run:
[build 6041](https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/6041), where the same step gives:
```
+ ./fuchsia_ctl -d nanny-iron-shiny-widen ssh --identity-file /etc/botanist/keys/id_rsa_infra -c 'echo up'
2020-10-29T02:19:26.483052Z: INFO up
==================================== STDOUT ====================================
up
```

Seems the ip is not stable over time.

**Comment by godofredoc** [comment]
This is most likely an issue that engine/fuchsia needs to follow up. From the infra point of view devices are in a correct state before installing the build under test.

After installing the new build the device is not able to discover the device.

**Comment by zanderso** [comment]
The autoroller just landed a new Fuchsia SDK https://github.com/flutter/engine/pull/22197. Let's keep an eye on it.

**Comment by iskakaushik** [comment]
Will become obsolete with https://flutter-review.googlesource.com/c/recipes/+/8081. Will likely take sometime to propagate. Please re-open if you continue seeing this in an hour or so.
