### ISSUE TITLE
Can't build flutter project on android

### ISSUE THREAD

**Issue by AdelKanso** [flutter/flutter#69151]
```
E/AndroidRuntime(11391): FATAL EXCEPTION: main
E/AndroidRuntime(11391): Process: com.example.flutter_apps, PID: 11391
E/AndroidRuntime(11391): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.flutter_apps/com.example.flutter_apps.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(11391): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
E/AndroidRuntime(11391): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
E/AndroidRuntime(11391): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
E/AndroidRuntime(11391): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
E/AndroidRuntime(11391): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11391): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(11391): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
E/AndroidRuntime(11391): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11391): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11391): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
E/AndroidRuntime(11391): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
E/AndroidRuntime(11391): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/launch_background.xml from drawable resource ID #0x7f040000
E/AndroidRuntime(11391): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3752)
E/AndroidRuntime(11391): 	at android.content.res.Resources.loadDrawable(Resources.java:3620)
E/AndroidRuntime(11391): 	at android.content.res.Resources.getDrawable(Resources.java:1852)
E/AndroidRuntime(11391): 	at android.content.res.Resources.getDrawable(Resources.java:1818)
E/AndroidRuntime(11391): 	at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:495)
E/AndroidRuntime(11391): 	at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:469)
E/AndroidRuntime(11391): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:301)
E/AndroidRuntime(11391): 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:520)
E/AndroidRuntime(11391): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:414)
E/AndroidRuntime(11391): 	at android.app.Activity.performCreate(Activity.java:6283)
E/AndroidRuntime(11391): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime(11391): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
E/AndroidRuntime(11391): 	... 10 more
E/AndroidRuntime(11391): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
E/AndroidRuntime(11391): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:202)
E/AndroidRuntime(11391): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
E/AndroidRuntime(11391): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1150)
E/AndroidRuntime(11391): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1063)
E/AndroidRuntime(11391): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3736)
E/AndroidRuntime(11391): 	... 21 more
```

**Comment by AdelKanso** [comment]
I wasn't on the stable channel

**Comment by behong1999** [comment]
> 
> 
> I wasn't on the stable channel
> problem solved
What do you mean by stable channel?
