### ISSUE TITLE
Allow IP addresses in Network Policy

### ISSUE THREAD

**Issue by nimi0112** [flutter/flutter#69168]
After the recent changes Landed in version: 1.23 now Insecure HTTP connections are disabled by default on iOS and Android.

After adding this snippet in `Manifest.xml`

``` xml
<application ...>
  ...
  <meta-data android:name="io.flutter.network-policy"
             android:resource="@xml/network_security_config"/>
</application>

```

This is my `network_security_config.xml`

``` xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">15.535.243.8</domain>
    </domain-config>
</network-security-config>
```

After this, if I run my Android app I still get an exception.

```
 [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: Invalid argument (domain): Invalid domain name: "15.535.243.8", stack trace: #0      new _DomainNetworkPolicy (dart:io/network_policy.dart:85:7)
E/flutter (12820): #1      _constructDomainPolicies (dart:io/network_policy.dart:181:22)
E/flutter (12820): #2      _EmbedderConfig._setDomainPolicies (dart:io/embedder_config.dart:44:23)
E/flutter (12820): 
F/flutter (12820): [FATAL:flutter/lib/io/dart_io.cc(38)] Check failed: !LogIfError(set_domain_network_policy_result). 
E/flutter (12820): [ERROR:flutter/shell/common/shell.cc(210)] Dart Unhandled Exception: Invalid argument (domain): Invalid domain name: "15.535.243.8", stack trace: #0      new _DomainNetworkPolicy (dart:io/network_policy.dart:85:7)
E/flutter (12820): #1      _constructDomainPolicies (dart:io/network_policy.dart:181:22)
E/flutter (12820): #2      _EmbedderConfig._setDomainPolicies (dart:io/embedder_config.dart:44:23)
E/flutter (12820): 
F/flutter (12820): [FATAL:flutter/lib/io/dart_io.cc(38)] Check failed: !LogIfError(set_domain_network_policy_result). 
Application finished.
```

After I click on the source of exception, this is the check being put

``` dart
_DomainNetworkPolicy(this.domain,
      {this.includesSubDomains = false,
      this.allowInsecureConnections = false}) {
    if (domain.length > 255 || !_domainMatcher.hasMatch(domain)) {
      throw ArgumentError.value(domain, "domain", "Invalid domain name");
    }
  }
```

and this is the _domainMatcher regex

``` dart
/// We specifically do not allow IP addresses.
  static final _domainMatcher = RegExp(
      r"^(?:[a-z\d-]{1,63}\.)+[a-z][a-z\d-]{0,62}$",
      caseSensitive: false);
``` 

Right now our project is under development and we are working on a private IP address for which SSL cannot be issued right now. 

So does these above conditions mean that I cannot make a network call without a domain name or with a private IP address?

**Comment by PixelToast** [comment]
Unfortunately this is not something we control as manifests and network_security_config are handled by native android and not Flutter.

See #65841
