### ISSUE TITLE
"settings getter is not implemented" Flutter Web

### ISSUE THREAD

**Issue by harshlohia** [flutter/flutter#69199]
I have just enabled flutter web in my existing flutter web, and since then i am getting this error, and flutter web showing blank Screen.
Here is the Stack trace:-
```
at Object.throw_ [as throw] (http://localhost:50883/dart_sdk.js:4347:11)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.get settings (http://localhost:50883/packages/cloud_firestore_platform_interface/src/platform_interface/platform_interface_write_batch.dart.lib.js:1713:17)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.get settings [as settings] (http://localhost:50883/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:737:20)
    at cloud_firestore.FirebaseFirestore.__.get settings [as settings] (http://localhost:50883/packages/cloud_firestore/cloud_firestore.dart.lib.js:880:31)
    at main$ (http://localhost:50883/packages/check/main.dart.lib.js:487:50)
    at main$.next (<anonymous>)
    at http://localhost:50883/dart_sdk.js:37899:33
    at _RootZone.runUnary (http://localhost:50883/dart_sdk.js:37753:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:50883/dart_sdk.js:32714:29)
    at handleValueCallback (http://localhost:50883/dart_sdk.js:33262:49)
    at Function._propagateToListeners (http://localhost:50883/dart_sdk.js:33300:17)
    at _Future.new.[_completeWithValue] (http://localhost:50883/dart_sdk.js:33142:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50883/dart_sdk.js:33165:35)
    at Object._microtaskLoop (http://localhost:50883/dart_sdk.js:38014:13)
    at _startMicrotaskLoop (http://localhost:50883/dart_sdk.js:38020:13)
    at http://localhost:50883/dart_sdk.js:33517:9
```
Photo for the same:-
![a](https://user-images.githubusercontent.com/57151106/97455017-614cad00-195d-11eb-8bde-026dfd386b0e.jpg)

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by DavidFontenova** [comment]
Hi! I've got the same issue "settings getter is not implemented" when trying to configure firestore emulator on my Flutter Web project.
![image](https://user-images.githubusercontent.com/9645688/124358664-38ca3080-dc19-11eb-98fe-f9ca9e21fb3d.png)
![image](https://user-images.githubusercontent.com/9645688/124358684-53040e80-dc19-11eb-9b2d-96ff0fa594b3.png)
![image](https://user-images.githubusercontent.com/9645688/124358714-6ca55600-dc19-11eb-9cca-df2046856839.png)

Here is my  flutter doctor -v
![image](https://user-images.githubusercontent.com/9645688/124358798-d45ba100-dc19-11eb-81fc-274f2904adc1.png)

It's not a big problem for me as it works properly on the Android Virtual Device. Whenever I need to test firestore I do it on Android.

**Comment by rsenthilkumar6** [comment]
I am also facing the same issue? any luck with any one on this?

**Comment by asimbo** [comment]
Try
FirebaseFirestore.instance.useFirestoreEmulator("local", 8080);
