### ISSUE TITLE
flutter_gallery__transition_perf_e2e_ios32 has been stuck for 90 minutes

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69218]
This is currently keeping the tree red

**Comment by keyonghan** [comment]
Tree is open.

**Comment by keyonghan** [comment]
The hang is due to cocoon switching versions and task being in a ghost state: task status is `in progress`, whereas the devicelab agent shows no tasks available.

Reopen to track this issue.

**Comment by godofredoc** [comment]
Would you mind adding some logs to take a look?

**Comment by keyonghan** [comment]
Seems before updating task status to datastore, it hit 502 error (when the cocoon is switching versions).
```
Cleaning up after task...

2020-10-28T09:09:11.123739: INFO [task runner] [flutter_gallery__transition_perf_e2e_ios32] Task execution finished
2020-10-28T09:09:11.215370: ERROR ERROR: AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/append-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJfCxIJQ2hlY2tsaXN0Ij9mbHV0dGVyL2ZsdXR0ZXIvbWFzdGVyLzdiODZiZTIyOGU0MDU0YWUwZWNkMGMzODk2YjljYzI2NDE1NjRiYTkMCxIEVGFzaxiAgJjMpJW7CQw
  HTTP Status: 502
  Response body:
<html>^M
<head><title>502 Bad Gateway</title></head>^M
<body>^M
<center><h1>502 Bad Gateway</h1></center>^M
<hr><center>nginx</center>^M
</body>^M
</html>^M

#0      AuthenticatedClient.send (package:cocoon_agent/src/agent.dart:28:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:176:38)
<asynchronous suspension>
#2      BaseClient.post (package:http/src/base_client.dart:58:7)
#3      Agent.uploadLogChunk (package:cocoon_agent/src/agent.dart:94:38)
<asynchronous suspension>
#4      runTask.sendLog (package:cocoon_agent/src/runner.dart:130:19)
<asynchronous suspension>
#5      runTask (package:cocoon_agent/src/runner.dart:175:18)
<asynchronous suspension>
#6      ContinuousIntegrationCommand._runTask (package:cocoon_agent/src/commands/ci.dart:193:31)
```

**Comment by CaseyHillers** [comment]
Root issue is https://github.com/flutter/flutter/issues/68240

Do we know how long the Cocoon version switches result in 502's?

When this moves to be uploaded from the test runner, we'll get retry functionality.

**Comment by godofredoc** [comment]
This is actually for uploading the log, once we move to LUCI this won't happen anymore.

**Comment by godofredoc** [comment]
This is a no resource problem: https://chromium-swarm.appspot.com/task?id=4f86ca6c72bfff10&o=true&w=true

**Comment by zanderso** [comment]
Guessing this is stale?
