### ISSUE TITLE
[web] CanvasKit Hot Restart does not work

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#69263]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Run `cd bug`.
3. Run `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`.
4. See the application in Chrome.
5. Change some text in the code.
6. Press hot reload / hot restart (does not matter because of https://github.com/flutter/flutter/issues/53041).

**Expected results:** the text should change because of hot restart (the page would normally refresh without the `FLUTTER_WEB_USE_SKIA` flag).

**Actual results:** I need to press F5 / reload the Chrome tab in order for the hot restart to finish. `flutter run` will be stuck on `Performing hot restart...` until I reload the Chrome tab.

<details>
  <summary>Click to expand versions</summary>

```
Flutter 1.24.0-3.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 2783f8e2e1 (6 days ago) • 2020-10-22 09:36:06 -0700
Engine • revision defa8be2b1
Tools • Dart 2.11.0 (build 2.11.0-242.0.dev)
```

</details>

## CanvasKit

**Removing** `--dart-define=FLUTTER_WEB_USE_SKIA=true` makes hot restart work without refreshing the tab.

**Comment by pedromassangocode** [comment]
Reproducible on the latest `master`, `dev` and `beta` channels.

Bellow is the logs from the moment you do Hot Restart/Reload. It is just stuck until you refresh the webpage manually.

<details><summary>Logs</summary>

```
Performing hot restart...
[+82261 ms] Skipping target: gen_localizations
[   +3 ms] complete
[  +11 ms] Scanned through 506 files in 10ms
Syncing files to device Chrome...
[   +1 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 715c4e1f-525a-4a62-82a0-cf15db0ce2c1
[        ] package:flutter_example/main.dart
[        ] <- 715c4e1f-525a-4a62-82a0-cf15db0ce2c1
[ +225 ms] Synced 0.0MB.
[        ] <- accept
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-4.0.pre.138, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-4.0.pre.138 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 13896b3bd1 (6 hours ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```
</details>

**Comment by jonahwilliams** [comment]
@yjbanov are all the fixes in for this?

**Comment by kubaprzetakiewicz** [comment]
Additionally, manual restart in the browser doesn't always work anyway.

Every now and then the server crashes with the following message:

```
Performing hot restart...                                        2,000ms
hotRestart: (-32603) No context with the running Dart application.
Application finished.
```

**Comment by jonahwilliams** [comment]
```
[   +7 ms] Debug service listening on ws://127.0.0.1:52419/rKit4YLpgsk=/ws
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+3617 ms] Performing hot restart...
[   +5 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +7 ms] complete
[   +7 ms] Scanned through 311 files in 6ms
[        ] Syncing files to device Chrome...
[   +2 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 91f2e7b1-f27a-4979-a5fd-27e26a48a3a3
[        ] package:hello_world/main.dart
[        ] <- 91f2e7b1-f27a-4979-a5fd-27e26a48a3a3
[  +60 ms] Syncing files to device Chrome... (completed in 62ms)
[        ] Synced 0.0MB.
[        ] <- accept
[   +2 ms] DwdsVmClient: Attempting a hot restart
[   +1 ms] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[   +8 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate

```

**Comment by grouma** [comment]
I'm able to reproduce this easily. I added some additional logs and it appears we are correctly issuing a request for `$dartHotRestart()`. However, we never get a corresponding isolate start [event](https://github.com/dart-lang/webdev/blob/0036f4480dc069e041696452a04bd6e7528613f2/dwds/lib/src/dwds_vm_client.dart#L99). It appears that `$dartHotRestart` isn't actually doing anything. If I manually call the method, I see a flash but there aren't corresponding changes.

I'm going to keep digging but the issue may be outside of `package:dwds` and actually inside DDC.

cc @nshahan

**Comment by nshahan** [comment]
Keep me posted, I can pick this up if it's clear this is on the ddc/sdk side.

**Comment by kubaprzetakiewicz** [comment]
> Additionally, manual restart in the browser doesn't always work anyway.
> 
> Every now and then the server crashes with the following message:
> 
> ```
> Performing hot restart...                                        2,000ms
> hotRestart: (-32603) No context with the running Dart application.
> Application finished.
> ```

This does not seem to be happening anymore as of `Flutter 1.24.0-8.0.pre.209 • channel master`

**Comment by grouma** [comment]
Ok I dug into this more. It looks like we are throw an error on hot restart but for some reason it isn't captured.

This is the error:

```
Error: Mismatched anonymous define() module: function() { return CanvasKitInit; }
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:168)
    at intakeDefines (require.js:1254)
    at Object.localRequire [as require] (require.js:1446)
    at requirejs (require.js:1797)
    at Object.forceLoadModule (main_module.bootstrap.js:806)
    at JavaScriptObject.forceLoadModule$3 (client.js:8762)
    at Object.forceLoadModule$3$x (client.js:3658)
    at RequireRestarter._reloadModule$1 (client.js:22508)
    at client.js:22443
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3826)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:10878)
    at Object._asyncStartSync (client.js:3790)
    at RequireRestarter._reload$body$RequireRestarter (client.js:22502)
    at RequireRestarter._reload$1 (client.js:22366)
    at client.js:22263
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3826)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:10878)
    at _awaitOnObject_closure.call$1 (client.js:10864)
    at _RootZone.runUnary$2$2 (client.js:12387)
    at _Future__propagateToListeners_handleValueCallback.call$0 (client.js:11248)
    at Object._Future__propagateToListeners (client.js:3931)
    at _Future._completeWithValue$1 (client.js:11081)
    at _AsyncAwaitCompleter.complete$1 (client.js:10847)
    at Object._asyncReturn (client.js:3798)
    at client.js:22318
    at _wrapJsFunctionForAsync_closure.$protected (client.js:3826)
    at _wrapJsFunctionForAsync_closure.call$2 (client.js:10878)
    at _awaitOnObject_closure.call$1 (client.js:10864)
    at _RootZone.runUnary$2$2 (client.js:12387)
    at _Future__propagateToListeners_handleValueCallback.call$0 (client.js:11248)
    at Object._Future__propagateToListeners (client.js:3931)
    at _Future._completeWithValue$1 (client.js:11081)
    at _Future__asyncCompleteWithValue_closure.call$0 (client.js:11170)
    at Object._microtaskLoop (client.js:3986)
    at StaticClosure._startMicrotaskLoop (client.js:3992)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (client.js:10747)
    at invokeClosure (client.js:1241)
    at MutationObserver.<anonymous> (client.js:1260)
```

It's thrown [here](https://github.com/dart-lang/webdev/blob/844ec3422d99334979cdaeb025049e40a473bd9a/dwds/lib/src/loaders/require.dart#L233).

It's clear that we are holding `requireJS` wrong when using canvas kit but the documentation at https://requirejs.org/docs/errors.html#mismatch is a little cryptic. I'm not super familiar with it. Adding @jakemac53 as he may know how to resolve the issue.

**Comment by grouma** [comment]
Seems like the root cause is this: https://github.com/flutter/flutter/issues/58428

Bouncing to @yjbanov to triage and resolve.

**Comment by yjbanov** [comment]
Thanks for finding the root cause. I put https://github.com/flutter/flutter/issues/58428 back in the triage queue.

**Comment by kubaprzetakiewicz** [comment]
```
Performing hot restart...                                          365ms
hotRestart: (-32000) Bad state: No active isolate to resume.
#0      _disableBreakpointsAndResume (package:dwds/src/dwds_vm_client.dart:152:28)
<asynchronous suspension>
#1      DwdsVmClient.create.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:61:7)
<asynchronous suspension>
#2      VmService._routeRequest (package:vm_service/src/vm_service.dart:2121:14)
<asynchronous suspension>
#3      VmService._processRequest (package:vm_service/src/vm_service.dart:2092:19)
<asynchronous suspension>
```

Error message is way more informative as of newest `master`.

**Comment by kubaprzetakiewicz** [comment]
Hot Restart still occasionally fails from time to time and manual restart sometimes kills the process.

```
Performing hot restart...                                           3.7s
hotRestart: (-32603) No context with the running Dart application.
Application finished.
```

**Comment by kubaprzetakiewicz** [comment]
As of today and the latest `master` Hot Restart does not work at all w/ CanvasKit (unless there were no changes in the project).

## Environment:
```
➜ flutter doctor -v
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on macOS 11.0 20A5364e darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.374 at /Users/jprzetakiewi/flutter
    • Framework revision 183f0e797a (4 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jprzetakiewi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.0, Build version 12A8189n
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • iPhone 11 Pro (mobile) • 2A1554C1-CEDE-49D1-AD8B-91D6B16ED09C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.0 20A5364e darwin-x64
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 87.0.4280.67

• No issues found!
```

## Steps to reproduce:
1. `flutter create hot_restart_skia_test`
2. `cd hot_restart_skia_test`
3. `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`
4. Press `r` in terminal to trigger Hot Restart - works properly
5. Make any changes in lib/main.dart
6. Press `r` in terminal again - process gets stuck on `Performing hot restart...`

After step 6 manually refreshing the browser can crash the process, this is the output to the console when it happens:
```
Performing hot restart...                                           3.7s
hotRestart: (-32603) No context with the running Dart application.
Application finished.
```

**Comment by hterkelsen** [comment]
It looks like it hasn't rolled into Flutter master yet. If this PR lands you should try again: https://github.com/flutter/flutter/pull/71498

**Comment by kubaprzetakiewicz** [comment]
The issue still persists.

### Console output:
```
Performing hot restart...                                        1,820ms
hotRestart: (-32000) Bad state: No active isolate to resume.
#0      _disableBreakpointsAndResume (package:dwds/src/dwds_vm_client.dart:158:28)
<asynchronous suspension>
#1      DwdsVmClient.create.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:61:7)
<asynchronous suspension>
#2      VmService._routeRequest (package:vm_service/src/vm_service.dart:2121:14)
<asynchronous suspension>
#3      VmService._processRequest (package:vm_service/src/vm_service.dart:2092:19)
<asynchronous suspension>
```

### How to reproduce:
Unknown, the feature works properly until it suddenly stops and crashes the app with every restart (assuming there were file changes since last restart)

### Environment:
```
➜ flutter doctor -v
[✓] Flutter (Channel master, 1.25.0-9.0.pre.43, on macOS 11.0.1 20B50 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-9.0.pre.43 at /Users/kubcio/.flutter
    • Framework revision 63062a6443 (26 hours ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kubcio/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
