### ISSUE TITLE
Build for ios fails in Xcode 12 : Undefined symbols for architecture armv7:   "_OBJC_CLASS_$_FlutterExifRotationPlugin", referenced from:       objc-class-ref in GeneratedPluginRegistrant.o

### ISSUE THREAD

**Issue by abaturyna** [flutter/flutter#69283]
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_FlutterExifRotationPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o

**Comment by pedromassangocode** [comment]
Hi @abaturyna 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by abaturyna** [comment]
HI @pedromassangocode 

PFA in file : 

[SQFLITE_BUILD_ERROR_UNRECOGNIZED_SYMBOLS.txt](https://github.com/flutter/flutter/files/5459062/SQFLITE_BUILD_ERROR_UNRECOGNIZED_SYMBOLS.txt)

**Comment by abaturyna** [comment]
Hi @pedromassangocode 

Please refer to attached file 
[SQFLITE_BUILD_ERROR_UNDEFINED_SYMBOLS.txt](https://github.com/flutter/flutter/files/5459318/SQFLITE_BUILD_ERROR_UNDEFINED_SYMBOLS.txt)

**Comment by abaturyna** [comment]
@pedromassangocode  Xcode version is Version 12.1 (12A7403)

**Comment by pedromassangocode** [comment]
Hi @abaturyna 
I cannot find any error message similar to the one you shared in the title, where did you get this message?
Can you please share your Podfile?

Found this in the logs:
```     
Specs satisfying the 'flutter_exif_rotation (from '.symlinks/plugins/flutter_exif_rotation/ios')' dependency were found, but they required a higher minimum deployment target. 
```

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale ru-BY)
 • Flutter version 1.24.0-3.0.pre at /Users/nastya/Dropbox/BUSINESS/Soft/flutter
 • Framework revision 2783f8e2e1 (6 дней назад), 2020-10-22 09:36:06 -0700
 • Engine revision defa8be2b1
 • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
 • Android SDK at /Users/nastya/Library/Android/sdk
 • Platform android-29, build-tools 29.0.3
 • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
 • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
 • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
 • Xcode at /Applications/Xcode.app/Contents/Developer
 • Xcode 12.1, Build version 12A7403
 • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
 • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
 • Android Studio at /Applications/Android Studio.app/Contents
 • Flutter plugin version 47.1.2
 • Dart plugin version 193.7361
 • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
 • IntelliJ at /Applications/IntelliJ IDEA.app
 • Flutter plugin version 45.1.3
 • Dart plugin version 201.7223.97

[✓] Connected device (2 available)
 • Web Server (web) • web-server • web-javascript • Flutter Tools
 • Chrome (web)  • chrome  • web-javascript • Google Chrome 86.0.4240.111

• No issues found!
```
</details>

<details><summary>Important parts of the logs</summary>

```
    [!] CocoaPods could not find compatible versions for pod "flutter_exif_rotation":
     In Podfile:
     flutter_exif_rotation (from `.symlinks/plugins/flutter_exif_rotation/ios`)
    
    Specs satisfying the `flutter_exif_rotation (from `.symlinks/plugins/flutter_exif_rotation/ios`)` dependency were found, but they required a higher minimum deployment target.
    
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    
[ +94 ms] Exception: Error running pod install
[  ] "flutter run" took 89 404ms.
[ +6 ms] 
   #0  throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
   #1  RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:622:7)
   <asynchronous suspension>
   #2  FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1033:18)
   #3  _rootRunUnary (dart:async/zone.dart:1198:47)
   #4  _CustomZone.runUnary (dart:async/zone.dart:1100:19)
   #5  _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
   #6  Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
   #7  Future._propagateToListeners (dart:async/future_impl.dart:725:32)
   #8  Future._completeWithValue (dart:async/future_impl.dart:529:5)
   #9  _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
   #10  _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
   #11  RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
   #12  _rootRunUnary (dart:async/zone.dart:1198:47)
   #13  _CustomZone.runUnary (dart:async/zone.dart:1100:19)
   #14  _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
   #15  Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
   #16  Future._propagateToListeners (dart:async/future_impl.dart:725:32)
   #17  Future._completeWithValue (dart:async/future_impl.dart:529:5)
   #18  Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
   #19  _rootRun (dart:async/zone.dart:1190:13)
   #20  _CustomZone.run (dart:async/zone.dart:1093:19)
   #21  _CustomZone.runGuarded (dart:async/zone.dart:997:7)
   #22  _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
   #23  _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
   #24  _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
   #25  _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
   #26  _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
    
    
[ +244 ms] ensureAnalyticsSent: 133ms
[  ] Running shutdown hooks
[  ] Shutdown hook priority 4
[ +2 ms] Shutdown hooks complete
[  ] exiting with code 1
```
</details>

**Comment by abaturyna** [comment]
Hi @pedromassangocode 

Please find my Podfile below : 

# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

  pod 'Flutter', :path => 'Flutter'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionLabelModel'
  pod 'Firebase/MLVisionTextModel'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end


Yes, this error with flutter_exif_rotation appeared so I was forced to increase platform version to 14.0 and change in XCode workspace settings as well for Runner and Target

**Comment by pedromassangocode** [comment]
Hi @abaturyna 
Thanks for providing your podfile, I will need your `pubspec.yaml` as well.

**Comment by abaturyna** [comment]
Hi @pedromassangocode  I have fixed the issue . Thank you very much that you tried to help me!!!! so, in order to prevent this issue for flutter_exif_rotation plugin i put 14.0 version to Podfile and to XCode workspace settings for Runner and Target . 

Also, i have talked to sqflite team - they released update where version of FMDB was increased. Which is cause of this problem. So i downgraded temporarily sqflite package to 1.3.0 version - error dissapeared. 

Thank you again and have a nice day !

**Comment by pedromassangocode** [comment]
Hi @abaturyna 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
