### ISSUE TITLE
[web]: SocketServer error after calling HTTP server bind method

### ISSUE THREAD

**Issue by AliaksandrBadretdzinau** [flutter/flutter#69308]
I am developing a Flutter web application that uses an HTTP server to respond with static site content to requests sent by the WebView.

When I tried to run the application I got an error related to the HTTP Server _bind()_ method that uses the _ServerSocket.bind()_ method from the _dart:io_ library, which does not work on Flutter Web.

Is there a way to get the http server to work on the Flutter Web?

<details>
  <summary>flutter doctor</summary>
  
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.24.0-3.0.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.50.1)
[√] Connected device (4 available)

• No issues found!

```
</details>

<details>
  <summary>The runtime error</summary>
Execution command: flutter run -d chrome
  
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                  11.0s
Debug service listening on ws://127.0.0.1:56154/yKtYCjJtJGo=

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
Error: UnimplementedError
    at Object.throw_ [as throw] (http://localhost:56119/dart_sdk.js:4347:11)
    at Function.bind (http://localhost:56119/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:2978:19)
    at bind (http://localhost:56119/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:3362:62)
    at bind.next (<anonymous>)
    at runBody (http://localhost:56119/dart_sdk.js:37919:34)
    at Object._async [as async] (http://localhost:56119/dart_sdk.js:37950:7)
    at Function.bind (http://localhost:56119/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:3361:20)
    at bind (http://localhost:56119/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:3154:47)
    at bind.next (<anonymous>)
    at runBody (http://localhost:56119/dart_sdk.js:37919:34)
    at Object._async [as async] (http://localhost:56119/dart_sdk.js:37950:7)
    at Function.bind (http://localhost:56119/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:3151:20)
    at Function.bind (http://localhost:56119/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:14101:35)
    at Function.bind (http://localhost:56119/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:8250:33)
    at serve (http://localhost:56119/packages/flutter_webview/ui/dialogs/create_course.dart.lib.js:3353:78)
    at serve.next (<anonymous>)
    at runBody (http://localhost:56119/dart_sdk.js:37919:34)
    at Object._async [as async] (http://localhost:56119/dart_sdk.js:37950:7)
    at Function.serve (http://localhost:56119/packages/flutter_webview/ui/dialogs/create_course.dart.lib.js:3350:20)
    at _onTapListItem (http://localhost:56119/packages/flutter_webview/ui/dialogs/create_course.dart.lib.js:3484:51)
    at _onTapListItem.next (<anonymous>)
    at runBody (http://localhost:56119/dart_sdk.js:37919:34)
    at Object._async [as async] (http://localhost:56119/dart_sdk.js:37950:7)
    at category_item.CategoryItem.new.[_onTapListItem] (http://localhost:56119/packages/flutter_webview/ui/dialogs/create_course.dart.lib.js:3483:20)    at http://localhost:56119/packages/flutter_webview/ui/dialogs/create_course.dart.lib.js:3480:725
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:56119/packages/flutter/src/material/icon_button.dart.lib.js:50758:42)
    at http://localhost:56119/packages/flutter/src/material/icon_button.dart.lib.js:50867:668
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:56119/packages/flutter/src/gestures/recognizer.dart.lib.js:189:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:56119/packages/flutter/src/gestures/tap.dart.lib.js:395:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:56119/packages/flutter/src/gestures/tap.dart.lib.js:201:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:56119/packages/flutter/src/gestures/tap.dart.lib.js:178:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:56119/packages/flutter/src/gestures/arena.dart.lib.js:208:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:56119/packages/flutter/src/gestures/binding.dart.lib.js:310:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:56119/packages/flutter/src/gestures/binding.dart.lib.js:289:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:56119/packages/flutter/src/rendering/layer.dart.lib.js:5973:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately]
    (http://localhost:56119/packages/flutter/src/gestures/binding.dart.lib.js:260:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:56119/packages/flutter/src/gestures/binding.dart.lib.js:233:43)      
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
    (http://localhost:56119/packages/flutter/src/gestures/binding.dart.lib.js:222:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
    (http://localhost:56119/packages/flutter/src/gestures/binding.dart.lib.js:212:65)
    at Object._invoke1 (http://localhost:56119/dart_sdk.js:177715:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:56119/dart_sdk.js:173269:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:56119/dart_sdk.js:160051:24)
    at http://localhost:56119/dart_sdk.js:160440:26
    at http://localhost:56119/dart_sdk.js:160399:16
    at http://localhost:56119/dart_sdk.js:160152:11
```
</details>

**Comment by darshankawar** [comment]
@AliaksandrBadretdzinau 
Please check [this](https://dart.dev/tutorials/server/httpserver) document and see if it answers your quesiton.

**Comment by AliaksandrBadretdzinau** [comment]
> 
> 
> @AliaksandrBadretdzinau
> Please check [this](https://dart.dev/tutorials/server/httpserver) document and see if it answers your quesiton.

No, this is not the answer to my question
I'm looking for a way to set up an http server on Flutter Web: bind a hostname and listen for new requests

**Comment by ferhatb** [comment]
@AliaksandrBadretdzinau could you provide a code sample to repro.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
