### ISSUE TITLE
Crash in FlutterDriverExtension on integration_ui_ios_driver

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69314]
```
2020-10-29T10:26:30.538313: stdout: [ +103 ms] 00:02 [32m+2[0m: FlutterDriver waitForAbsent should resolve when text "present" disappears[0m
2020-10-29T10:26:31.101132: stdout: [ +562 ms] [VERBOSE-2:shell.cc(209)] Dart Unhandled Exception: FileSystemException: writeFrom failed, path = '' (OS Error: Input/output error, errno = 5), stack trace: #0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
stdout: [        ] #1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:309:15)
2020-10-29T10:26:31.101281: stdout: [        ] #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
2020-10-29T10:26:31.101338: stdout: [        ] #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
2020-10-29T10:26:31.101556: stdout: [        ] #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
2020-10-29T10:26:31.101639: stdout: [        ] #5      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
2020-10-29T10:26:31.101702: stdout: [        ] #6      _StreamController._add (dart:async/stream_controller.dart:682:7)
2020-10-29T10:26:31.101839: stdout: [        ] #7      _StreamController.add (dart:async/stream_controller.dart:624:5)
2020-10-29T10:26:31.102007: stdout: [        ] #8      _StreamSinkImpl.add (dart:io/io_sink.dart:156:17)
2020-10-29T10:26:31.102110: stdout: [        ] #9      _IOSinkImpl.write (dart:io/io_sink.dart:289:5)
2020-10-29T10:26:31.102273: stdout: [        ] #10     _IOSinkImpl.writeln (dart:io/io_sink.dart:309:5)
2020-10-29T10:26:31.102343: stdout: [        ] #11     _StdSink.writeln (dart:io/stdio.dart:342:11)
2020-10-29T10:26:31.102491: stdout: [        ] #12     driverLog.<anonymous closure> (package:flutter_driver/src/common/error.dart:54:10)
2020-10-29T10:26:31.102565: stdout: [        ] #13     FlutterDriverExtension._log (package:flutter_driver/src/extension/extension.dart:340:14)
2020-10-29T10:26:31.102633: stdout: [        ] #14     FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:370:7)
2020-10-29T10:26:31.102751: stdout: [        ] <asynchronous suspension>
2020-10-29T10:26:31.102881: stdout: [        ] #15     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:546:18)
2020-10-29T10:26:31.103112: stdout: [        ] <asynchronous suspension>
2020-10-29T10:26:32.189843: stdout: [+1086 ms] 00:04 [32m+3[0m: FlutterDriver waitFor times out waiting for "present" to reappear[0m
```

[integration_ui_ios_driver_470346f_2 (1).log](https://github.com/flutter/flutter/files/5460227/integration_ui_ios_driver_470346f_2.1.log)

**Comment by jonahwilliams** [comment]
Looks like this is caused by stderr or similar closing?
