### ISSUE TITLE
flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.

### ISSUE THREAD

**Issue by Jiangshan2015** [flutter/flutter#69356]
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown while dispatching notifications for SwiperController:
flutter: The method 'toDouble' was called on null.
flutter: Receiver: null
flutter: Tried calling: toDouble()
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
flutter: #1      double.* (dart:core-patch/double.dart:36:23)
flutter: #2      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:367:17)
flutter: #3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:205:16)
flutter: #4      _TransformerPageViewState.onChangeNotifier (package:transformer_page_view/transformer_page_view.dart:606:12)
flutter: #5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
flutter: #6      IndexController.next (package:transformer_page_view/index_controller.dart:30:5)
flutter: #7      _SwiperTimerMixin._onTimer (package:flutter_swiper/src/swiper.dart:370:17)
flutter: (elided 10 frames from class _RawReceivePortImpl, class _Timer, and dart:async)
flutter:
flutter: The SwiperController sending notification was:
flutter:   Instance of 'SwiperController'
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.

**Comment by swebreza** [comment]
can you please explain more.. Show us some code and  `flutter doctor`

**Comment by Jiangshan2015** [comment]
Thank you. It's OK to recompile the code, but you only need to report an error once. After the modification, the error will be reported when reload

**Comment by darshankawar** [comment]
@Jiangshan2015 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.

**Comment by iapicca** [comment]
> flutter: The following NoSuchMethodError was thrown while dispatching notifications for SwiperController:

Since the error is from [SwiperController](https://pub.dev/documentation/flutter_swiper/latest/flutter_swiper/SwiperController-class.html) I suspect you are using the 3rd party package [flutter_swiper](https://pub.dev/packages/flutter_swiper)
you may want to open an issue in the dedicated [github](https://github.com/best-flutter/flutter_swiper/issues)

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by hermozo** [comment]
dgfdgf

**Comment by IsaacEduardo** [comment]
Unfortunately, I'm stuck on that mistake and I don't see how to overcome it.

**Comment by iapicca** [comment]
> Unfortunately, I'm stuck on that mistake and I don't see how to overcome it.

@IsaacEduardo please follow the indication [above](https://github.com/flutter/flutter/issues/69356#issuecomment-732794260)

> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.
