### ISSUE TITLE
Exception: operation failed after calling recorder.endRecording()

### ISSUE THREAD

**Issue by JDNew** [flutter/flutter#69363]
I use canvas to draw a ui.Image list , it should be general a vertical long image.
In some devices , it can work .  However in some other devices , if the canvas draw over 5 images (the total height is over 4460) , and call ``` recorder.endRecording()``` finally , it will throw the error : operation failed.

It seems that the canvas has maxHeight in some devices , or those devices can not support  such big canvas data.

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.17.5 at /Users/wecut1260/develop_tool/flutter
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wecut1260/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/wecut1260/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
```

</details>

**Comment by darshankawar** [comment]
@JDNew 
You seem to be on older version of Flutter. Current stable version is 1.22.2. I'd recommend to upgrade to latest and try again to see if it works.
If problem persists, provide a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.

**Comment by JDNew** [comment]
Hello , @darshankawar , Thanks for your reply . I have followed your advice to upgrade flutter latest version , but the problem persists .

Below is the code sample :

```
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final canvasRect = new Rect.fromLTRB(0, 0, 1080.0, 4460);
  final recorder = ui.PictureRecorder();

  Future drawCanvas() async {
    final canvas = Canvas(recorder, canvasRect);
    Paint paint = new Paint()
      ..color = Color(0xff585D66)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 11
      ..isAntiAlias = true
      ..filterQuality = FilterQuality.high;
    Rect rect = Rect.fromLTRB(0, 0, 1080.0, 9000);
    canvas.drawRect(rect, paint);
    final picture = recorder.endRecording();
    ui.Image finalPicture = await picture.toImage(1080, 4460);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          drawCanvas();
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

And by the way , this problem occurs in these devices which I have known:

> vivo Y91 & Android 8.1
   vivo Y93S & Android 8.1
   Honor 8A & Android 9.0
   Honor 9A & Android 10

**Comment by darshankawar** [comment]
@JDNew 
Although I don't have the devices you mentioned, I tried your code sample on Samsung A260G (8.1.0) and after tapping FAB, I get below exception:

```
I/Choreographer(22801): Skipped 154 frames!  The application may be doing too much work on its main thread.
E/flutter (22801): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Canvas constructor called with non-genuine PictureRecorder.
E/flutter (22801): #0      Canvas._constructor (dart:ui/painting.dart:3436:63)
E/flutter (22801): #1      new Canvas (dart:ui/painting.dart:3430:5)
E/flutter (22801): #2      _MyHomePageState.drawCanvas (package:webtest/main.dart:38:20)
E/flutter (22801): #3      _MyHomePageState.build.<anonymous closure> (package:webtest/main.dart:73:11)
E/flutter (22801): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (22801): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (22801): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (22801): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (22801): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (22801): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (22801): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (22801): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (22801): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (22801): #13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (22801): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (22801): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (22801): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (22801): #17     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (22801): #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (22801): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (22801): #20     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (22801): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (22801): 
W/libEGL  (22801): EGLNativeWindowType 0xc0420008 disconnect failed
W/libEGL  (22801): EGLNativeWindowType 0xc80b4808 disconnect failed
I/zygote  (22801): Do partial code cache collection, code=26KB, data=30KB
I/zygote  (22801): After code cache collection, code=26KB, data=30KB
I/zygote  (22801): Increasing code cache capacity to 128KB

```

Is this a correct interpretation of the issue you are facing ?

**Comment by JDNew** [comment]
@darshankawar  It seems that you found a new problem in other device with the same code . My problem is happend when the code run into ``` final picture = recorder.endRecording();``` ,and it just throws the error message :
>  Unhandled Exception: Exception: operation failed .

**Comment by TahaTesser** [comment]
Hi @JDNew 
I get to an exception exactly as https://github.com/flutter/flutter/issues/69363#issuecomment-726000705  and I don't this is device-specific `Unhandled Exception: Canvas constructor called with non-genuine PictureRecorder.` 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

Can you please run your own code sample and try again on the latest `stable` channel 
Please provide a reproducible code sample 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
