### ISSUE TITLE
previousOwner._heroControllerFromScope != newHeroController': is not true

### ISSUE THREAD

**Issue by whatscoder** [flutter/flutter#69392]
My error is the following:
```
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2785 pos 24: 'previousOwner._heroControllerFromScope != newHeroController': is not true.
```

**_updateHeroController(null)** only be called in the **dispose** method,so I think **previousOwner._heroControllerFromScope** may be equal to **newHeroController**

My simple demo is: https://github.com/whatscoder/navigator_test, branch is master

flutter doctor is:
```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4
    19E287, locale zh-Hans-CN)
    • Flutter version 1.22.2 at
      /Users/mj/Documents/flutter1220
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15
      16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android     SDK version 30.0.0)
    • Android SDK at /Users/mj/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/mj/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
```

**Comment by TahaTesser** [comment]
Hi @whatscoder 
Can you please isolate the code causes and create a minimal code sample and provide steps to reproduce 
Can you please provide `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by whatscoder** [comment]
Hi @TahaTesser 
Let me give you a brief account of my operation:
I have a **StatefulWidget** ，**Overlay**  is his child，and then I package a **navigator** as an **OverlayEntry** and insert into **OverlayState**。When over one **OverlayEntry** that packaged **navigator** are inserted into **OverlayState**, there is an error: `package:flutter/src/widgets/navigator.dart': Failed assertion: line 2785 pos 24: 'previousOwner._heroControllerFromScope != newHeroController': is not true.`

`flutter run --verbose` logs:

```
[+604284 ms] flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[        ] flutter: The following assertion was thrown during a scheduler callback:
[   +7 ms] flutter: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2785 pos 24:
[        ] flutter: 'previousOwner._heroControllerFromScope != newHeroController': is not true.
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      NavigatorState._updateHeroController.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2785:24)
[        ] flutter: #3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
[  +19 ms] flutter: #4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1063:9)
[        ] flutter: #5      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
[        ] flutter: #9      _invoke (dart:ui/hooks.dart:251:10)
[        ] flutter: #10     _drawFrame (dart:ui/hooks.dart:209:3)
[        ] flutter: (elided 5 frames from class _AssertionError and dart:async)
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[+20133 ms] flutter: Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2785 pos 24: 'previousOwner._heroControllerFromScope != newHeroController': is not true.
```



**If the description is not clear, please indicate, Thank you**

**Comment by TahaTesser** [comment]
Hi @whatscoder 
Thanks for describing the issue, to better address the issue, please provide a minimal code sample
Thank you

**Comment by whatscoder** [comment]
Hi @TahaTesser 
I have simplified my code sample. https://github.com/whatscoder/navigator_test/    branch is master 
The exception is the same as the above.
please check again, Thank you.

**Comment by TahaTesser** [comment]
Hi @whatscoder 
I put all your code in a single `main.dart`
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

final GlobalKey<ContainerManagerState> containerManagerKey =
    GlobalKey<ContainerManagerState>();

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      builder: (BuildContext context, Widget child) {
        assert(child is Navigator, 'child must be Navigator, what is wrong?');

        return ContainerManager(
          key: containerManagerKey,
          initNavigator: child as Navigator,
        );
      },
      home: Container(
        color: Colors.white,
      ),
    );
  }
}

class ContainerManager extends StatefulWidget {
  const ContainerManager({
    Key key,
    this.initNavigator,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => ContainerManagerState();

  final Navigator initNavigator;
}

class ContainerManagerState extends State<ContainerManager> {
  final GlobalKey<OverlayState> _overlayKey = GlobalKey<OverlayState>();
  final List<Navigator> _offstage = <Navigator>[];
  List<OverlayEntry> _leastEntries;
  Navigator _onstage;

  @override
  void initState() {
    super.initState();

    _onstage = Navigator(
      key: GlobalKey<NavigatorState>(),
      onGenerateRoute: (RouteSettings routeSettings) {
        return MaterialPageRoute(builder: (BuildContext context) {
          return FirstWidget();
        });
      },
    );

    WidgetsBinding.instance.addPostFrameCallback((_) {
      setState(() {});
    });
  }

  @override
  void setState(VoidCallback fn) {
    if (SchedulerBinding.instance.schedulerPhase ==
        SchedulerPhase.persistentCallbacks) {
      SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
        _refreshOverlayEntries();
      });
    } else {
      _refreshOverlayEntries();
    }

    fn();
  }

  @override
  Widget build(BuildContext context) {
    return Overlay(
      key: _overlayKey,
      initialEntries: const <OverlayEntry>[],
    );
  }

  void pushContainer(WidgetBuilder builder) {
    _offstage.add(_onstage);

    _onstage = Navigator(
      key: GlobalKey<NavigatorState>(),
      onGenerateRoute: (RouteSettings routeSettings) {
        return MaterialPageRoute(builder: builder);
      },
    );

    setState(() {});
  }

  void _refreshOverlayEntries() {
    final OverlayState overlayState = _overlayKey.currentState;

    if (overlayState == null) return;

    if (_leastEntries != null && _leastEntries.isNotEmpty) {
      for (final OverlayEntry entry in _leastEntries) {
        entry.remove();
      }
    }

    final List<Navigator> containers = <Navigator>[];
    containers.addAll(_offstage);
    containers.add(_onstage);

    _leastEntries = containers
        .map<OverlayEntry>((Navigator container) =>
            OverlayEntry(builder: (BuildContext context) => container))
        .toList(growable: false);

    overlayState.insertAll(_leastEntries);
  }
}

class FirstWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('first'),
      ),
      body: Center(
          child: RaisedButton(
              child: const Text('click'),
              onPressed: () {
                ContainerManagerState state =
                    context.findAncestorStateOfType<ContainerManagerState>();
                state.pushContainer((context) => SecondWidget());
              })),
    );
  }
}

class SecondWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('second'),
      ),
      body: Center(
        child: Text('hello'),
      ),
    );
  }
}

```

</details>

<details> 
<summary>logs</summary> 

```bash
Running "flutter pub get" in master_flutter...
Launching lib/main.dart on iPhone 12 in debug mode...
 lib/main.dart
Xcode build done.                                           26.0s
Connecting to VM Service at ws://127.0.0.1:53074/Ck3KIERTjPI=/ws

[38;5;248m════════ Exception caught by scheduler library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during a scheduler callback:[39;49m
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3389 pos 24: '<optimized out>': is not true.


[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
[39;49m

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      NavigatorState._updateHeroController.<anonymous closure>.<anonymous closure>[39;49m
 package:flutter/…/widgets/navigator.dart
[38;5;244m#3      SchedulerBinding._invokeFrameCallback[39;49m
 package:flutter/…/scheduler/binding.dart
[38;5;244m#4      SchedulerBinding.handleDrawFrame[39;49m
 package:flutter/…/scheduler/binding.dart
[38;5;244m#5      SchedulerBinding._handleDrawFrame[39;49m
 package:flutter/…/scheduler/binding.dart
[38;5;244m#9      _invoke (dart:ui/hooks.dart:157:10)[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8874f21e79 (4 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 572593A3-647B-413C-9188-B91DD07DEAF0 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (3 available)            
    • iPhone 12 (mobile) • 572593A3-647B-413C-9188-B91DD07DEAF0 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      86.0.4240.183

• No issues found!

```

```bash
[✓] Flutter (Channel master, 1.24.0-7.0.pre.73, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-7.0.pre.73 at /Users/tahatesser/Code/flutter_master
    • Framework revision fb90544cab (2 hours ago), 2020-11-02 22:48:03 -0800
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • iPhone 12 (mobile) • 572593A3-647B-413C-9188-B91DD07DEAF0 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • Mac OS X 10.15.7 19H2
      darwin-x64
    • Web Server (web)   • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      86.0.4240.183

• No issues found!
```

</details>

**Comment by whatscoder** [comment]
Hi @TahaTesser 
I got it, after running, you need to click the button named 'click' of the **FirstWidget**, push to the **SecondWidget**,  and then the exception log is shown in the console.
I have put all my code in a single `main.dart`, https://github.com/whatscoder/navigator_test.git, branch is `master`

exception logs: 
```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2785 pos 24: 'previousOwner._heroControllerFromScope != newHeroController': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      NavigatorState._updateHeroController.<anonymous closure>.<anonymous closure>
package:flutter/…/widgets/navigator.dart:2785
#3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1117
#4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1063
#5      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:971
#9      _invoke (dart:ui/hooks.dart:251:10)
```

**Comment by chunhtai** [comment]
The hero controller cannot be shared across the multiple navigator,  you can fix this by wrapping each container with their own herocontrollerscope
```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

final GlobalKey<ContainerManagerState> containerManagerKey =
GlobalKey<ContainerManagerState>();

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      builder: (BuildContext context, Widget child) {
        assert(child is Navigator, 'child must be Navigator, what is wrong?');

        return ContainerManager(
          key: containerManagerKey,
          initNavigator: child as Navigator,
        );
      },
      home: Container(
        color: Colors.white,
      ),
    );
  }
}

class ContainerManager extends StatefulWidget {
  const ContainerManager({
    Key key,
    this.initNavigator,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => ContainerManagerState();

  final Navigator initNavigator;
}

class ContainerManagerState extends State<ContainerManager> {
  final GlobalKey<OverlayState> _overlayKey = GlobalKey<OverlayState>();
  final List<Widget> _offstage = <Widget>[];
  List<OverlayEntry> _leastEntries;
  Widget _onstage;

  @override
  void initState() {
    super.initState();

    _onstage = HeroControllerScope(controller: HeroController(), child: Navigator(
      key: GlobalKey<NavigatorState>(),
      onGenerateRoute: (RouteSettings routeSettings) {
        return MaterialPageRoute(builder: (BuildContext context) {
          return FirstWidget();
        });
      },
    ));

    WidgetsBinding.instance.addPostFrameCallback((_) {
      setState(() {});
    });
  }

  @override
  void setState(VoidCallback fn) {
    if (SchedulerBinding.instance.schedulerPhase ==
        SchedulerPhase.persistentCallbacks) {
      SchedulerBinding.instance.addPostFrameCallback((Duration duration) {
        _refreshOverlayEntries();
      });
    } else {
      _refreshOverlayEntries();
    }

    fn();
  }

  @override
  Widget build(BuildContext context) {
    return Overlay(
      key: _overlayKey,
      initialEntries: const <OverlayEntry>[],
    );
  }

  void pushContainer(WidgetBuilder builder) {
    _offstage.add(_onstage);

    _onstage = Navigator(
      key: GlobalKey<NavigatorState>(),
      onGenerateRoute: (RouteSettings routeSettings) {
        return MaterialPageRoute(builder: builder);
      },
    );

    setState(() {});
  }

  void _refreshOverlayEntries() {
    final OverlayState overlayState = _overlayKey.currentState;

    if (overlayState == null) return;

    if (_leastEntries != null && _leastEntries.isNotEmpty) {
      for (final OverlayEntry entry in _leastEntries) {
        entry.remove();
      }
    }

    final List<Widget> containers = <Widget>[];
    containers.addAll(_offstage);
    containers.add(_onstage);

    _leastEntries = containers
        .map<OverlayEntry>((Widget container) =>
        OverlayEntry(builder: (BuildContext context) => container))
        .toList(growable: false);

    overlayState.insertAll(_leastEntries);
  }
}

class FirstWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('first'),
      ),
      body: Center(
          child: RaisedButton(
              child: const Text('click'),
              onPressed: () {
                ContainerManagerState state =
                context.findAncestorStateOfType<ContainerManagerState>();
                state.pushContainer((context) => SecondWidget());
              })),
    );
  }
}

class SecondWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('second'),
      ),
      body: Center(
        child: Text('hello'),
      ),
    );
  }
}
```

**Comment by chunhtai** [comment]
I will put up a pr to improve the error message
