### ISSUE TITLE
flutter run "Device creation failed (device == nil)" using Xcode Version 12.1

### ISSUE THREAD

**Issue by ghenry** [flutter/flutter#69400]
## Steps to Reproduce

I'm build an existing app on Xcode 12.1 after a `flutter clean`. Obviously some file is out of date, but I've not seen this before. This is already working on iOS 14 and Xcode 12, but that didn't have the new iPhone 12 devices in the list.

## Logs

```
flutter run --verbose

                       <IBScaleFactorDeviceTypeDescription: 0x7fc8c5540ca0> scaleFactor=2x, renderMode.identifier=(null)'.
                        Device type: IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x)
                        Sim runtime: iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1
                        Device: (null)
                        ** Please also include the output of `xcrun simctl list` and `xcode-select -p`.
                            Failure Reason: Invalid argument
                            Underlying Errors:
                                Description: Failed to find a suitable device for the type IBSimDeviceTypeiPad2x
(com.apple.dt.Xcode.IBSimDeviceType.iPad-2x)
                                with runtime iOS 14.1 (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1
                                Failure Reason: Failed to create new simulator device in set SimDeviceSet :
/Users/ghenry/Library/Developer/Xcode/UserData/IB
                                Support/Simulator Devices that matches IBSimDeviceTypeiPad2x (com.apple.dt.Xcode.IBSimDeviceType.iPad-2x)
for runtime iOS 14.1
                                (14.1 - 18A8394) - com.apple.CoreSimulator.SimRuntime.iOS-14-1 (The operation couldn’t be completed. Device
creation failed
                                (device == nil)). Available devices: (
                            "iPhone 5s (6D1FE719-E66D-4AA2-9F8D-7C17A2368122, iOS 12.1, Shutdown)",
                            "iPhone 6 Plus (1AB38F46-3CD8-4BD3-8D96-7E534D51561B, iOS 12.1, Shutdown)",
                            "iPhone 6 (D495FDF0-085E-44B3-828E-A4CB8AC89C9B, iOS 12.1, Shutdown)",
                            "iPhone 6s (6030CB48-696C-4046-B7AE-F942DEDFF69B, iOS 12.1, Shutdown)",
                            "iPhone 6s Plus (2D962784-4B48-42BE-BA64-CE1A965B1FCB, iOS 12.1, Shutdown)",
                            "iPhone SE (1st generation) (9935F7BE-A5C0-4A66-B26C-C676EF0754F7, iOS 12.1, Shutdown)",
                            "iPhone 7 (6CCE6269-FDEB-44CD-A74C-5FF73E7507B9, iOS 12.1, Shutdown)",
                            "iPhone 7 Plus (14F6F2DA-0098-4C55-87E3-FEE572F5DAA8, iOS 12.1, Shutdown)",
                            "iPhone 8 (B1A45AFD-F2DC-47CA-92CD-43AF39D9F6BE, iOS 12.1, Shutdown)",
                            "iPhone 8 Plus (9D43CE14-BC43-43D2-B6EC-DA87B56497C7, iOS 12.1, Shutdown)",
                            "iPhone X (2520758A-521F-4497-A121-984CED8A37D6, iOS 12.1, Shutdown)",
                            "iPhone Xs (896E0585-CAFA-4041-A42A-B54DAC37D481, iOS 12.1, Shutdown)",
                            "iPhone Xs Max (B81BA29D-32DC-48CE-BD5F-D5D9E733B19D, iOS 12.1, Shutdown)",
                            "iPhone X\U0280 (A54D0473-106B-49E7-9A3A-9B6EE70A6E5B, iOS 12.1, Shutdown)",
                            "iPad Air (C83FED56-6002-4195-9DFB-FADFA2817F73, iOS 12.1, Shutdown)",
                            "iPad Air 2 (ED8A4424-F52E-4418-B7C8-B282DAD16EC7, iOS 12.1, Shutdown)",
                            "iPad Pro (9.7-inch) (9D03CFBD-85F8-40AE-BD1F-30C38379AC31, iOS 12.1, Shutdown)",
                            "iPad Pro (12.9-inch) (4CAB14F9-312B-45F1-8D54-A7E80096AFA7, iOS 12.1, Shutdown)",
                            "iPad (5th generation) (7B51411B-08AA-4C24-AEE0-AE7354A25FD5, iOS 12.1, Shutdown)",
                            "iPad Pro (12.9-inch) (2nd generation) (D186B756-CB22-414C-A60A-4F2A69E89116, iOS 12.1, Shutdown)",
                            "iPad Pro (10.5-inch) (CF16AD34-CFDA-41A5-AAC9-4758A9AF586B, iOS 12.1, Shutdown)",
                            "iPad (6th generation) (ADC4F7C2-0F9D-4323-99C5-416070BCBCAD, iOS 12.1, Shutdown)",
                            "iPad Pro (11-inch) (1st generation) (127C8D52-22DB-4111-AC2D-7817A020DA91, iOS 12.1, Shutdown)",
                            "iPad Pro (12.9-inch) (3rd generation) (45908723-6B37-4742-A343-825BA5EB1DEF, iOS 12.1, Shutdown)"
                        )
                                Underlying Errors:
                                    Description: The operation couldn’t be completed. Device creation failed (device == nil)
                                    Failure Reason: Device creation failed (device == nil)

                        CompileAssetCatalog /Users/ghenry/StudioProjects/SureVoIP-Talk/build/ios/Debug-iphonesimulator/Runner.app
                        /Users/ghenry/StudioProjects/SureVoIP-Talk/ios/Runner/Assets.xcassets (in target 'Runner' from project 'Runner')
                            cd /Users/ghenry/StudioProjects/SureVoIP-Talk/ios
                            /Applications/Xcode.app/Contents/Developer/usr/bin/actool --output-format human-readable-text --notices
--warnings
                            --export-dependency-info

/Users/ghenry/Library/Developer/Xcode/DerivedData/Runner-ghevsdaxamdwakdmgzmmhbxuphwj/Build/Intermediates.noindex/Runner.build/Debug
                            -iphonesimulator/Runner.build/assetcatalog_dependencies --output-partial-info-plist

/Users/ghenry/Library/Developer/Xcode/DerivedData/Runner-ghevsdaxamdwakdmgzmmhbxuphwj/Build/Intermediates.noindex/Runner.build/Debug
                            -iphonesimulator/Runner.build/assetcatalog_generated_info.plist --app-icon AppIcon --compress-pngs
--enable-on-demand-resources YES
                            --development-region en --target-device iphone --target-device ipad --minimum-deployment-target 12.0 --platform
iphonesimulator
                            --compile /Users/ghenry/StudioProjects/SureVoIP-Talk/build/ios/Debug-iphonesimulator/Runner.app
                            /Users/ghenry/StudioProjects/SureVoIP-Talk/ios/Runner/Assets.xcassets


[+1519 ms] Could not build the application for the simulator.
[   +3 ms] Error launching application on iPhone 12 Pro.
[  +26 ms] "flutter run" took 86,388ms.
[  +14 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/ghenry/development/flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ghenry/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Users/ghenry/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Users/ghenry/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6858069/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 12 Pro (mobile) • F25CD050-68D9-46A1-8972-F76E03ECEFBF • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by ghenry** [comment]
These helped me resolve this:

 https://stackoverflow.com/questions/44418905/images-xcassets-error-failed-to-find-a-suitable-device-for-the-type-simdevicet
 https://github.com/flutter/flutter/issues/60030

basically a reboot or:

`sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService`

and opening the simulator again.

Very embarrassed, but leaving this here for Google foo.
