### ISSUE TITLE
flutter doctor --android-licenses error: Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema

### ISSUE THREAD

**Issue by ErtanOzdemir** [flutter/flutter#69495]
Hi, today when I try to execute "flutter doctor --android-licenses" command on terminal I got this error massage 

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema 
How can I fix it?

By the way I use Ubuntu.

## Logs

Here is the full log of error message.
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

```

### flutter doctor -v
I installed Android Studio but it couldn't find it.

```
[✓] Flutter (Channel beta, 1.22.1, on Linux, locale tr_TR.UTF-8)
    • Flutter version 1.22.1 at /home/user/snap/flutter/common/flutter
    • Framework revision f30b7f4db9 (3 hafta önce), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.9+11-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (3 available)
    • F3111 (mobile)   • RQ3003VQHF • android-arm64  • Android 7.0 (API 24)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

```

**Comment by hamdikahloun** [comment]
Hi @ErtanOzdemir 

I see there's an open issue addressing the case you described : https://github.com/flutter/flutter/issues/57372
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.

For now, you can try this https://github.com/flutter/flutter/issues/68387#issuecomment-711048764 / https://github.com/flutter/flutter/issues/68387#issuecomment-711054711 .

Thank you

**Comment by flutterq** [comment]
All Possible Working Solution Added Here [[Solved] Exception in thread “main” java.lang.NoClassDefFoundError in flutter](https://fluttercorner.com/exception-in-thread-main-java-lang-noclassdeffounderror-in-flutter/)
