### ISSUE TITLE
Couldn't build Android APK after upgrading Flutter 1.22.3 and Android Studio 4.1

### ISSUE THREAD

**Issue by dustincatap** [flutter/flutter#69516]
`flutter build apk -v` output:

```
[ +160 ms] executing: [/Library/Developer/Flutter/sdk/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8874f21e79d7ec66d0457c7ab338348e31b17f1d
[        ] executing: [/Library/Developer/Flutter/sdk/] git tag --points-at HEAD
[  +21 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.3
[  +11 ms] executing: [/Library/Developer/Flutter/sdk/] git rev-parse --abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Library/Developer/Flutter/sdk/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [/Library/Developer/Flutter/sdk/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +17 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H2
[  +60 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +177 ms] Found plugin app_review at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/app_review-2.0.1/
[   +8 ms] Found plugin app_settings at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/app_settings-4.0.4/
[  +43 ms] Found plugin contacts_service at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.4.6/
[  +21 ms] Found plugin firebase_auth at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.1+2/
[   +5 ms] Found plugin firebase_auth_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.1+1/
[   +2 ms] Found plugin firebase_core at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0+1/
[   +2 ms] Found plugin firebase_core_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[   +6 ms] Found plugin flutter_facebook_auth at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-0.2.4/
[   +3 ms] Found plugin flutter_secure_storage at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.5/
[   +4 ms] Found plugin get_ip at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/get_ip-0.4.0/
[   +4 ms] Found plugin google_sign_in at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.5/
[   +2 ms] Found plugin google_sign_in_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.2/
[   +5 ms] Found plugin in_app_update at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.13/
[   +9 ms] Found plugin libphonenumber at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/libphonenumber-1.0.2/
[   +9 ms] Found plugin package_info at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.3/
[   +4 ms] Found plugin path_provider at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.22/
[   +1 ms] Found plugin path_provider_linux at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+4/
[   +2 ms] Found plugin path_provider_windows at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+1/
[   +2 ms] Found plugin permission_handler at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/
[  +10 ms] Found plugin screen at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/screen-0.0.5/
[   +2 ms] Found plugin share at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/share-0.6.5+3/
[   +1 ms] Found plugin shared_preferences at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+2/
[   +1 ms] Found plugin shared_preferences_linux at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+2/
[   +1 ms] Found plugin shared_preferences_macos at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+10/
[   +1 ms] Found plugin shared_preferences_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[   +1 ms] Found plugin shared_preferences_windows at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.1+1/
[   +2 ms] Found plugin smartlook at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/smartlook-1.0.5/
[   +3 ms] Found plugin sqflite at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+2/
[  +15 ms] Found plugin url_launcher at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.8/
[   +1 ms] Found plugin url_launcher_linux at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+3/
[   +1 ms] Found plugin url_launcher_macos at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+8/
[   +2 ms] Found plugin url_launcher_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5/
[   +1 ms] Found plugin url_launcher_windows at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+1/
[   +5 ms] Found plugin video_player at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.12+5/
[   +3 ms] Found plugin video_player_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.4/
[   +1 ms] Found plugin wakelock at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/
[   +4 ms] Found plugin webview_flutter at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.22+1/
[ +139 ms] Found plugin app_review at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/app_review-2.0.1/
[   +1 ms] Found plugin app_settings at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/app_settings-4.0.4/
[  +18 ms] Found plugin contacts_service at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.4.6/
[   +8 ms] Found plugin firebase_auth at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.18.1+2/
[   +1 ms] Found plugin firebase_auth_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.3.1+1/
[        ] Found plugin firebase_core at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0+1/
[   +1 ms] Found plugin firebase_core_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.2.0/
[   +3 ms] Found plugin flutter_facebook_auth at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-0.2.4/
[   +1 ms] Found plugin flutter_secure_storage at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-3.3.5/
[   +2 ms] Found plugin get_ip at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/get_ip-0.4.0/
[   +2 ms] Found plugin google_sign_in at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.5/
[   +1 ms] Found plugin google_sign_in_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.2/
[   +4 ms] Found plugin in_app_update at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/in_app_update-1.1.13/
[   +5 ms] Found plugin libphonenumber at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/libphonenumber-1.0.2/
[   +5 ms] Found plugin package_info at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.3/
[   +2 ms] Found plugin path_provider at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.22/
[        ] Found plugin path_provider_linux at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[        ] Found plugin path_provider_macos at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+4/
[   +1 ms] Found plugin path_provider_windows at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+1/
[   +1 ms] Found plugin permission_handler at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/permission_handler-5.0.1+1/
[   +6 ms] Found plugin screen at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/screen-0.0.5/
[   +1 ms] Found plugin share at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/share-0.6.5+3/
[   +1 ms] Found plugin shared_preferences at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+2/
[        ] Found plugin shared_preferences_linux at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+2/
[        ] Found plugin shared_preferences_macos at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+10/
[   +1 ms] Found plugin shared_preferences_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[        ] Found plugin shared_preferences_windows at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.1+1/
[   +1 ms] Found plugin smartlook at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/smartlook-1.0.5/
[   +3 ms] Found plugin sqflite at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.1+2/
[   +6 ms] Found plugin url_launcher at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.8/
[        ] Found plugin url_launcher_linux at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+3/
[        ] Found plugin url_launcher_macos at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+8/
[   +1 ms] Found plugin url_launcher_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5/
[        ] Found plugin url_launcher_windows at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+1/
[   +2 ms] Found plugin video_player at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.12+5/
[   +1 ms] Found plugin video_player_web at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.4/
[   +1 ms] Found plugin wakelock at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/
[   +1 ms] Found plugin webview_flutter at /Library/Developer/Flutter/sdk/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.22+1/
[  +27 ms] Generating /Users/dustincatap/Source/tasonic-top-up/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +30 ms] executing: /usr/bin/xcodebuild -version
[ +117 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 12.0
           Build version 12A7209
[  +31 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[        ] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
[        ]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +24 ms] Running Gradle task 'assembleRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Users/dustincatap/Source/tasonic-top-up/android/gradlew.
[        ] /Users/dustincatap/Source/tasonic-top-up/android/gradlew mode: 33261 rwxr-xr-x.
[   +8 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[   +8 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\
/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio4.1","idea.exe
cutable":"studio","idea.platform.prefix":"AndroidStudio","idea.vendor.name":"Google","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests access to the
user's Desktop folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-201.8743.12.41.6858069","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in Android Studio requests access
to the device's camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"s
tudio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"4.1","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicati
onCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android Studio requests access to the user's
Documents folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests
access to files on a network volume.","CFBundleGetInfoString":"Android Studio 4.1, build AI-201.8743.12.41.6858069. Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An application in
Android Studio requests access to files on a removable volume."}
[  +23 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +77 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +2 ms] executing: [/Users/dustincatap/Source/tasonic-top-up/android/] /Users/dustincatap/Source/tasonic-top-up/android/gradlew -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64
-Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true -Ptree-shake-icons=true assembleRelease
[ +761 ms] > Configure project :app
[        ] Signing with provided keystore
[        ] WARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..
[ +685 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
[        ] > Failed to notify dependency resolution listener.
[        ]    > tried to access method sun.security.util.ECUtil.getECParameters(Ljava/security/Provider;)Ljava/security/AlgorithmParameters; from class sun.security.ec.ECKeyPairGenerator
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[ +414 ms] Running Gradle task 'assembleRelease'... (completed in 2.0s)
[   +9 ms] "flutter apk" took 2,910ms.
[   +5 ms] Gradle task assembleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +255 ms] ensureAnalyticsSent: 253ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

`flutter doctor -v` output
```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-PH)
    • Flutter version 1.22.3 at /Library/Developer/Flutter/sdk
    • Framework revision 8874f21e79 (2 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dustincatap/Library/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/dustincatap/Library/Android/Sdk
    • ANDROID_SDK_ROOT = /Users/dustincatap/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 8+ (mobile) • ######################### • ios • iOS 13.3
    ! Error: iPhone 8+ is busy: Processing cache files from device. Xcode will continue when iPhone 8+ is finished. (code -10)
```

**Comment by dustincatap** [comment]
Solved it by restarting computer
