### ISSUE TITLE
LUCI tasks queued for multiple hours

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69589]
For example: https://github.com/flutter/flutter/pull/69547 . They don't seem to be running at all.

**Comment by godofredoc** [comment]
This is not related to capacity there are many bot available:

![image](https://user-images.githubusercontent.com/54371434/97904091-dc62ea00-1cf4-11eb-991b-8ddcc1738c61.png)

**Comment by godofredoc** [comment]
Seems like builbucket is failing:

```
BuildBucketException: [500]: 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

#0      BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:86:5)
<asynchronous suspension>
#1      BuildBucketClient.batch (package:cocoon_service/src/service/buildbucket.dart:113:42)
#2      LuciBuildService.scheduleTryBuilds (package:cocoon_service/src/service/luci_build_service.dart:207:29)
<asynchronous suspension>
#3      GithubWebhook._scheduleIfMergeable (package:cocoon_service/src/request_handlers/github_webhook.dart:155:28)
<asynchronous suspension>
#4      GithubWebhook._handlePullRequest (package:cocoon_service/src/request_handlers/github_webhook.dart:118:15)
<asynchronous suspension>
#5      GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:64:17)
<asynchronous suspension>
#6      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
<asynchronous suspension>
#7      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _runZoned (dart:async/zone.dart:1630:10)
#11     runZoned (dart:async/zone.dart:1550:10)
#12     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#13     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:133:23)
<asynchronous suspension>
#14     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart)
#15     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#16     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#17     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _runZoned (dart:async/zone.dart:1630:10)
#21     runZonedGuarded (dart:async/zone.dart:1618:12)
#22     runZoned (dart:async/zone.dart:1547:12)
#23     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#24     fork (package:gcloud/service_scope.dart:104:30)
#25     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#26     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#27     _rootRunUnary (dart:async/zone.dart:1198:47)
#28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#33     _StreamController._add (dart:async/stream_controller.dart:682:7)
#34     _StreamController.add (dart:async/stream_controller.dart:624:5)
#35     _HttpServer._handleRequest (dart:_http/http_impl.dart:2977:19)
#36     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2732:19)
#37     _rootRunUnary (dart:async/zone.dart:1198:47)
#38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#43     _StreamController._add (dart:async/stream_controller.dart:682:7)
#44     _StreamController.add (dart:async/stream_controller.dart:624:5)
#45     _HttpParser._headersEnd (dart:_http/http_parser.dart:408:17)
#46     _HttpParser._doParse (dart:_http/http_parser.dart:740:15)
#47     _HttpParser._parse (dart:_http/http_parser.dart:324:7)
#48     _rootRunUnary (dart:async/zone.dart:1198:47)
#49     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#54     _StreamController._add (dart:async/stream_controller.dart:682:7)
#55     _StreamController.add (dart:async/stream_controller.dart:624:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#57     _rootRunUnary (dart:async/zone.dart:1206:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#62     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#63     _StreamController._add (dart:async/stream_controller.dart:682:7)
#64     _StreamController.add (dart:async/stream_controller.dart:624:5)
#65     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#66     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#69     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by godofredoc** [comment]
This is happening approximately 15 times per day.
