### ISSUE TITLE
Error when using an ObjectKey("withANotNullStringHere") with a TextFormField

### ISSUE THREAD

**Issue by aflongo85** [flutter/flutter#69667]
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MediaQuery(MediaQueryData(size: Size(392.7, 737.5), devicePixelRatio: 2.8, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional)):
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 259 pos 16: 'child == null || indexOf(child) > index': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ListView file:///Users/Andrea/Documents/Kalendit_flutter/kalendit/lib/screens/bank_info_screen.dart:116:17
When the exception was thrown, this was the stack: 
#2      RenderSliverMultiBoxAdaptor._debugVerifyChildOrder (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:259:16)
#3      RenderSliverMultiBoxAdaptor.debugChildIntegrityEnabled=.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:234:14)
#4      RenderSliverMultiBoxAdaptor.debugChildIntegrityEnabled= (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:236:6)
#5      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1125:20)
#6      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1055:7)
...
════════════════════════════════════════════════════════════════════════════════════════════════════




Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  LoadingOverlay file:/// **** /screens/bank_info_screen.dart:103:14
When the exception was thrown, this was the stack: 
#2      SingleChildRenderObjectElement.removeRenderObjectChild (package:flutter/src/widgets/framework.dart:6146:12)
#3      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:5814:36)
#4      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3604:11)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3322:9)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by darshankawar** [comment]
@aflongo85 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by aflongo85** [comment]
It was a mistake from my end. Closing this
