### ISSUE TITLE
LUCI tasks failing with 401 AuthenticatedClientError URI: https://flutter-dashboard.appspot.com/api/update-task-status 

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#69739]
All the LUCI tests on [my PR](https://github.com/flutter/flutter/pull/69720) are failing
```

Unhandled exception:
AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/update-task-status
  HTTP Status: 401
  Response body:
User is not signed in
#0      AuthenticatedCocoonClient.send (package:flutter_devicelab/framework/cocoon.dart:168:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
#2      BaseClient.post (package:http/src/base_client.dart:32:7)
#3      Cocoon._sendCocoonRequest.<anonymous closure> (package:flutter_devicelab/framework/cocoon.dart:125:25)
#4      retry (package:flutter_devicelab/framework/utils.dart:773:22)
<asynchronous suspension>
#5      Cocoon._sendCocoonRequest (package:flutter_devicelab/framework/cocoon.dart:124:37)
#6      Cocoon.sendTaskResult (package:flutter_devicelab/framework/cocoon.dart:109:49)
#7      _runTasks (file:///b/s/w/ir/k/flutter/dev/devicelab/bin/run.dart:114:20)
<asynchronous suspension>
#8      main (file:///b/s/w/ir/k/flutter/dev/devicelab/bin/run.dart:93:11)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:309:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8864599270237813584/+/steps/run_build_aar_module_test/0/stdout

**Comment by CaseyHillers** [comment]
Thanks Jenn for filing.

This looks related to a CL I had. I created a revert at  https://flutter-review.googlesource.com/c/recipes/+/8241. Once that lands and propagates these should go back.

I'll add this builder to our presubmit testing for recipes to prevent future breakages.

**Comment by CaseyHillers** [comment]
Fix landed: https://ci.chromium.org/p/flutter/builders/try/Linux%20build_aar_module_test

Created https://github.com/flutter/flutter/issues/69778 to track the fix to prevent future breakages.
