### ISSUE TITLE
java.lang.Exception at IOClient.send(io_client.dart:62)

### ISSUE THREAD

**Issue by Legolaszstudio** [flutter/flutter#69777]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
```
import 'package:http/http.dart' as http;
String agent = "myApplication";
String code = "MySecretApiToken";
String username = "Username";
String password = "Password";

var headers = {
    'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
    'User-Agent': '$agent',
};

var data = 'institute_code=$code&userName=$user&password=$pass&grant_type=password&client_id=xxxxxxxxx';
var response = await http.post(
              'https://$code.website.hu/idp/api/v1/Token',
              headers: headers,
              body: data);
```
Also add these to AndroidManifest:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<service
    android:name="io.flutter.plugins.androidalarmmanager.AlarmService"
    android:permission="android.permission.BIND_JOB_SERVICE"
    android:exported="false"/>
<receiver
    android:name="io.flutter.plugins.androidalarmmanager.AlarmBroadcastReceiver"
    android:exported="false"/>
<receiver
    android:name="io.flutter.plugins.androidalarmmanager.RebootBroadcastReceiver"
    android:enabled="false">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"></action>
    </intent-filter>
</receiver>
```

3. Running this code works exactly as expected every time I run it, but fails to run when used in a background isolate with android_alarm manager nearly every time.
```
//Used in a background isolate like this
await AndroidAlarmManager.periodic(
        Duration(minutes: 60),
        0, //Id
        backgroundFetchHelper.backgroundFetch, //The function being called
        wakeup: true,
        rescheduleOnReboot: true,
 );
```

**Expected results:**
Get the data I'm trying to HTTP post.

**Actual results:**
Get the following error stack traces or similar ones:
```
Non-fatal Exception: java.lang.Exception
       at IOClient.send(io_client.dart:62)
       at BaseClient._sendUnstreamed(base_client.dart:176)
       at ._withClient(http.dart:166)
       at NetworkHelper.getToken(networkHelper.dart:45)
       at .backgroundFetch(backgroundFetchHelper.dart:113)
```
Error seen in crashlytics:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: . Error thrown getToken.
       at IOClient.send(io_client.dart:62)
       at BaseClient._sendUnstreamed(base_client.dart:91)
       at NetworkHelper.getToken(networkHelper.dart:45)
       at .backgroundFetch(backgroundFetchHelper.dart:113)
       at .suspension>(<asynchronous)
```
Or sometimes with a call to _.withClient
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: . Error thrown getToken.
       at IOClient.send(io_client.dart:62)
       at BaseClient._sendUnstreamed(base_client.dart:91)
       at ._withClient(http.dart:166)
       at NetworkHelper.getToken(networkHelper.dart:45)
       at .backgroundFetch(backgroundFetchHelper.dart:113)
       at .suspension>(<asynchronous)
```

<details>
  <summary>Logs</summary>

```
Couldn't reproduce the error in the emulator
```

```
D:\novyNaplo>flutter analyze
Analyzing novyNaplo...
No issues found! (ran in 5.1s)
```

```
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19041.572], locale hu-HU)
    • Flutter version 1.22.2 at E:\FLUTTER\flutter
    • Framework revision 84f3d28555 (3 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Novot\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Novot\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Novot\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Novot\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@Legolaszstudio 
Please provide a complete code sample that we can copy paste and run in IDE to see the issue. I used your code sample, but its complaining on `$user`

**Comment by Legolaszstudio** [comment]
Sorry, I was in a hurry yesterday when I wrote the issue ticket.
So this is how the updated code should look like:
```
import 'package:http/http.dart' as http;
import 'package:android_alarm_manager/android_alarm_manager.dart';

String agent = "myApplication";
String code = "MySecretApiToken";
String user = "Username";
String pass = "Password";

void backgroundFetch() async {
  //this same as NetworkHelper.getToken
  var headers = {
    'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
    'User-Agent': '$agent',
  };

  var data =
      'institute_code=$code&userName=$user&password=$pass&grant_type=password&client_id=xxxxxxxxx';
  //Error occours on the next line
  var response = await http.post('https://$code.website.hu/idp/api/v1/Token',
      headers: headers, body: data);
}

//How it looks when used with android_alarm_manager
void main() async {
  await AndroidAlarmManager.periodic(
    Duration(minutes: 60),
    0, //Id
    backgroundFetch, //The function being called
    wakeup: true,
    rescheduleOnReboot: true,
  );
}

```
I changed the API link because I do not want to expose my credentials if it is maybe a server-side error I can find a way to share it with you, if needed.
Also, these dependencies need to be added to pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  http: any
  android_alarm_manager: any
```
And as I already mentioned this needs to be added to AndroidManifest.xml:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<service
    android:name="io.flutter.plugins.androidalarmmanager.AlarmService"
    android:permission="android.permission.BIND_JOB_SERVICE"
    android:exported="false"/>
<receiver
    android:name="io.flutter.plugins.androidalarmmanager.AlarmBroadcastReceiver"
    android:exported="false"/>
<receiver
    android:name="io.flutter.plugins.androidalarmmanager.RebootBroadcastReceiver"
    android:enabled="false">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"></action>
    </intent-filter>
</receiver>
```

I already reported the bug on the HTTP package site, but got redirected here: 
[https://github.com/dart-lang/http/issues/421](https://github.com/dart-lang/http/issues/421)

**Comment by darshankawar** [comment]
@Legolaszstudio 
I ran the updated code sample but see a blank screen and nothing in the logs. How to replicate the issue ? Are there any specific steps ?

**Comment by Legolaszstudio** [comment]
Strange, yes the code has no UI elements. But for me running my included code snippet is enough to occur every 60 minutes as I set it in the alarm manager, just simply rewrite the duration:
```
void main() async {
  await AndroidAlarmManager.periodic(
    Duration(minutes: 1), //Change this number to a lower value, for the code to run more frequently.....
    0, //Id
    backgroundFetch, //The function being called
    wakeup: true,
    rescheduleOnReboot: true,
  );
}
```

**Comment by darshankawar** [comment]
@Legolaszstudio 
After 1 minute, I am getting below exception which is different from what you mentioned (although a crash still):

```
I/FlutterBackgroundExecutor(31914): Starting AlarmService...
I/AndroidAlarmManagerPlugin(31914): onAttachedToEngine
D/AndroidRuntime(31914): Shutting down VM
E/AndroidRuntime(31914): FATAL EXCEPTION: main
E/AndroidRuntime(31914): Process: com.example.webtest, PID: 31914
E/AndroidRuntime(31914): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(31914): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3365)
E/AndroidRuntime(31914): 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(31914): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
E/AndroidRuntime(31914): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31914): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(31914): 	at android.app.ActivityThread.main(ActivityThread.java:6543)
E/AndroidRuntime(31914): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31914): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E/AndroidRuntime(31914): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
E/AndroidRuntime(31914): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(31914): 	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:336)
E/AndroidRuntime(31914): 	at java.lang.String.valueOf(String.java:2827)
E/AndroidRuntime(31914): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
E/AndroidRuntime(31914): 	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:142)
E/AndroidRuntime(31914): 	at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:173)
E/AndroidRuntime(31914): 	at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:126)
E/AndroidRuntime(31914): 	at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:349)
E/AndroidRuntime(31914): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3355)
E/AndroidRuntime(31914): 	... 8 more

```

**Comment by Legolaszstudio** [comment]
This is an error regarding the embedding engine which is in the native kotlin/java code. If I remember correctly flutter already solved this issue, but for me, I had to change MainActivity.kt kotlin (android\app\src\main\kotlin) file to resolve the issue you are experiencing:
```
package YOURPACKAGENAME //Change it accordingly
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

//MainActivity automatically run by flutter
class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
```

**Comment by Legolaszstudio** [comment]
Also yo should have a android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java file if everything works normally

**Comment by Legolaszstudio** [comment]
Also, I updated main.dart as it contained some mistakes:
```
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:android_alarm_manager/android_alarm_manager.dart';

String agent = "myApplication";
String code = "MySecretApiToken";
String user = "Username";
String pass = "Password";

void backgroundFetch() async {
  //this same as NetworkHelper.getToken
  var headers = {
    'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
    'User-Agent': '$agent',
  };

  var data =
      'institute_code=$code&userName=$user&password=$pass&grant_type=password&client_id=xxxxxxxxx';
  //Error occours on the next line
  var response = await http.post('https://$code.website.hu/idp/api/v1/Token',
      headers: headers, body: data);
}

//How it looks when used with android_alarm_manager
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await AndroidAlarmManager.initialize();
  await AndroidAlarmManager.periodic(
    Duration(seconds: 15),
    0, //Id
    backgroundFetch, //The function being called
    wakeup: true,
    rescheduleOnReboot: true,
  );
}
```

But you need to change the API link to something working.

**Comment by darshankawar** [comment]
@Legolaszstudio 
What api link should I use to replicate the issue ?

**Comment by Legolaszstudio** [comment]
I was able to replicate the issue with any API link, like http://icanhazip.com/ which should just return your IP address.

**Comment by darshankawar** [comment]
With above link as-is, I am getting below:

```
[+11291 ms] E/flutter (12769): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Insecure HTTP is not allowed by platform: http://icanhazip.com/
[        ] E/flutter (12769): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2435:7)
```

with `https://icanhazip.com/`, I get following:

```
[ +138 ms] I/AlarmService(10617): AlarmService started!
[+13702 ms] D/ViewRootImpl@100ae37[MainActivity](10617): ViewPostIme pointer 0
[  +93 ms] D/ViewRootImpl@100ae37[MainActivity](10617): ViewPostIme pointer 1
[+2691 ms] Service protocol connection closed.
[        ] Lost connection to device.
```

**Comment by Legolaszstudio** [comment]
Strange, why would you lose connection to your device?
For me like 1 out of 10 times, it throws the exception, I'm trying to figure out

**Comment by darshankawar** [comment]
Tested on latest master with another device, and this time I see below:

```
Running "flutter pub get" in webtest...
Launching lib/main.dart on SM A260G in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for SM A260G to report its views...
Debug service listening on ws://127.0.0.1:55082/Lmk5bIdeMvw=/ws
Syncing files to device SM A260G...
I/FlutterBackgroundExecutor(24643): Starting AlarmService...
I/AndroidAlarmManagerPlugin(24643): onAttachedToEngine
I/AlarmService(24643): AlarmService started!
```

**Comment by Legolaszstudio** [comment]
After waiting a bit you should get an exception after `AlarmService started!`, when the alarm-manager runs

**Comment by darshankawar** [comment]
Waited for 10 mins after `AlarmService started`, but didn't notice the exception you mentioned originally. I'd suggest you to revisit your implementation and see where and how does it throw the exception, whereas using same implementation, we were unable to replicate it.

```
I/FlutterBackgroundExecutor(26021): Starting AlarmService...
I/AndroidAlarmManagerPlugin(26021): onAttachedToEngine
I/AlarmService(26021): AlarmService started!
W/libEGL  (26021): EGLNativeWindowType 0xc7073808 disconnect failed
W/libEGL  (26021): EGLNativeWindowType 0xc7066008 disconnect failed
I/zygote  (26021): Do partial code cache collection, code=27KB, data=30KB
I/zygote  (26021): After code cache collection, code=27KB, data=30KB
I/zygote  (26021): Increasing code cache capacity to 128KB
D/mali_winsys(26021): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
D/mali_winsys(26021): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
E/BpSurfaceComposerClient(26021): Failed to transact (-1)
E/BpSurfaceComposerClient(26021): Failed to transact (-1)

```

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (11 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!

```

</details>



```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
