### ISSUE TITLE
[cocoon][app_dart] 500's on task endpoints with FormatException

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#69821]
These started to appear when migrating the backend to the new version from commit https://github.com/flutter/cocoon/tree/356ac653eebee4daeaf02f7fcbd708a0127e6f4e

```
FormatException: Unexpected character (at line 139, character 7)
      },
      ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:928:13)
#2      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#3      JsonDecoder.convert (dart:convert/json.dart:505:36)
#4      JsonCodec.decode (dart:convert/json.dart:156:41)
#5      getLuciBuilders (package:cocoon_service/src/foundation/utils.dart:112:21)
<asynchronous suspension>
#6      Config.luciBuilders (package:cocoon_service/src/datastore/cocoon_config.dart:80:18)
<asynchronous suspension>
#7      LuciBuilder.getProdBuilders (package:cocoon_service/src/service/luci.dart:225:25)
#8      RefreshGithubCommits._createTasks (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:210:62)
#9      RefreshGithubCommits._saveData (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:120:38)
<asynchronous suspension>
#10     RefreshGithubCommits.get (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:87:13)
<asynchronous suspension>
#11     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
<asynchronous suspension>
#12     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _runZoned (dart:async/zone.dart:1630:10)
#16     runZoned (dart:async/zone.dart:1550:10)
#17     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#18     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:144:19)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _runZoned (dart:async/zone.dart:1630:10)
#22     runZoned (dart:async/zone.dart:1550:10)
#23     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:143:11)
<asynchronous suspension>
#24     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:134:23)
#25     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#26     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#27     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#28     _rootRun (dart:async/zone.dart:1190:13)
#29     _CustomZone.run (dart:async/zone.dart:1093:19)
#30     _runZoned (dart:async/zone.dart:1630:10)
#31     runZonedGuarded (dart:async/zone.dart:1618:12)
#32     runZoned (dart:async/zone.dart:1547:12)
#33     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#34     fork (package:gcloud/service_scope.dart:104:30)
#35     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#36     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#37     _rootRunUnary (dart:async/zone.dart:1198:47)
#38     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#43     _StreamController._add (dart:async/stream_controller.dart:682:7)
#44     _StreamController.add (dart:async/stream_controller.dart:624:5)
#45     _HttpServer._handleRequest (dart:_http/http_impl.dart:2977:19)
#46     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2732:19)
#47     _rootRunUnary (dart:async/zone.dart:1198:47)
#48     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#53     _StreamController._add (dart:async/stream_controller.dart:682:7)
#54     _StreamController.add (dart:async/stream_controller.dart:624:5)
#55     _HttpParser._headersEnd (dart:_http/http_parser.dart:394:19)
#56     _HttpParser._doParse (dart:_http/http_parser.dart:740:15)
#57     _HttpParser._parse (dart:_http/http_parser.dart:324:7)
#58     _rootRunUnary (dart:async/zone.dart:1198:47)
#59     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#63     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#64     _StreamController._add (dart:async/stream_controller.dart:682:7)
#65     _StreamController.add (dart:async/stream_controller.dart:624:5)
#66     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#67     _rootRunUnary (dart:async/zone.dart:1206:13)
#68     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#69     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#70     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#71     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#72     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#73     _StreamController._add (dart:async/stream_controller.dart:682:7)
#74     _StreamController.add (dart:async/stream_controller.dart:624:5)
#75     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#76     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#77     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#78     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#79     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#80     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by CaseyHillers** [comment]
\cc @godofredoc 

The issue seems to be on `getLuciBuilders`

**Comment by CaseyHillers** [comment]
Dupe of https://github.com/flutter/flutter/issues/69818#issuecomment-721993580
