### ISSUE TITLE
Document how to use routing

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#6982]
## Steps to Reproduce

I want to show different content in the body of a material scaffold 
and update the body from user actions from everywhere (the drawer, top bar, bottom bar, ...)

A simple example with some explanation about the design decisions made in this example would be great.

**Comment by zoechi** [comment]
I added a `Navigator` to the body of scaffold with a `GlobalKey` and tried 
```dart
  Future<dynamic> _tapHandler(BuildContext context, String resourceName) {
    return Navigator.pushNamed(
        AppLayout.bodyNavigatorKey.currentContext, '/search/$resourceName');
  }
```
and got
```
I/flutter (17537): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17537): The following assertion was thrown building LayoutId(['_ScaffoldSlot.body']; id:
I/flutter (17537): _ScaffoldSlot.body):
I/flutter (17537): scheduleBuildFor() called for a widget for which a build was already scheduled.
I/flutter (17537): The method was called for the following element:
I/flutter (17537):   Focus([GlobalKey 1023923269]; dirty; state: _FocusState(33041742))
I/flutter (17537): The current dirty list consists of:
I/flutter (17537):   [SemanticsDebugger(state: _SemanticsDebuggerState(216700771)),
I/flutter (17537):   Navigator([GlobalObjectKey<NavigatorState> _WidgetsAppState(972069794)]; state:
I/flutter (17537):   NavigatorState(458771600; tracking 2 tickers)), Focus([GlobalKey 108993699]; state:
I/flutter (17537):   _FocusState(342019615)), Overlay([GlobalKey 24953361]; state: OverlayState(465697029; entries:
I/flutter (17537):   [OverlayEntry@233531397(opaque: false; maintainState: false), OverlayEntry@813925534(opaque:
I/flutter (17537):   false; maintainState: true), OverlayEntry@705765128(opaque: false; maintainState: false),
I/flutter (17537):   OverlayEntry@375717045(opaque: false; maintainState: true)])), _ModalScope([GlobalKey 1019844046];
I/flutter (17537):   state: _ModalScopeState(684842807)), Focus([GlobalObjectKey MaterialPageRoute<Null>(426142108)];
I/flutter (17537):   state: _FocusState(650659595)), Focus([GlobalObjectKey
I/flutter (17537):   LabeledGlobalKey<DrawerControllerState>(827736459)]; state: _FocusState(539566691)),
I/flutter (17537):   Focus([GlobalKey 1023923269]; dirty; state: _FocusState(33041742)), DrawerController([GlobalKey
I/flutter (17537):   827736459]; state: DrawerControllerState(868676881; ticker inactive)), Navigator([GlobalKey
I/flutter (17537):   85683158]; dirty; state: NavigatorState(994285275))]
I/flutter (17537): This usually indicates that a widget was rebuilt outside the build phase (thus marking the element
I/flutter (17537): as clean even though it is still in the dirty list). This should not be possible and is probably
I/flutter (17537): caused by a bug in the widgets framework. Please report it:
I/flutter (17537): https://github.com/flutter/flutter/issues/new
I/flutter (17537): To debug this issue, consider setting the debugPrintScheduleBuildForStacks and
I/flutter (17537): debugPrintBuildDirtyElements flags to true and looking for a call to scheduleBuildFor for a widget
I/flutter (17537): that is labeled "ALREADY IN LIST".
I/flutter (17537): 
I/flutter (17537): When the exception was thrown, this was the stack:
I/flutter (17537): #0      BuildOwner.scheduleBuildFor.<anonymous closure> (package:flutter/src/widgets/framework.dart:1632:9)
I/flutter (17537): #2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:1628:12)
I/flutter (17537): #3      BuildableElement.markNeedsBuild (package:flutter/src/widgets/framework.dart:2755:11)
I/flutter (17537): #4      BuildableElement.dependenciesChanged (package:flutter/src/widgets/framework.dart:2801:5)
I/flutter (17537): #5      StatefulElement.dependenciesChanged (package:flutter/src/widgets/framework.dart:3111:30)
I/flutter (17537): #6      BuildableElement.activate (package:flutter/src/widgets/framework.dart:2816:7)
I/flutter (17537): #7      StatefulElement.activate (package:flutter/src/widgets/framework.dart:3037:19)
I/flutter (17537): #8      Element._activateRecursively (package:flutter/src/widgets/framework.dart:2321:13)
I/flutter (17537): #9      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:3831:14)
I/flutter (17537): #10     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2323:13)
I/flutter (17537): #11     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:3831:14)
I/flutter (17537): #12     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2323:13)
I/flutter (17537): #13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:2925:14)
I/flutter (17537): #14     Element._activateRecursively (package:flutter/src/widgets/framework.dart:2323:13)
I/flutter (17537): #15     Element._activateWithParent (package:flutter/src/widgets/framework.dart:2314:5)
I/flutter (17537): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2240:18)
I/flutter (17537): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #19     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #22     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3196:16)
I/flutter (17537): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #24     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3939:32)
I/flutter (17537): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #28     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #34     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3843:14)
I/flutter (17537): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #44     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3843:14)
I/flutter (17537): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #53     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3843:14)
I/flutter (17537): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #62     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #68     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #70     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #75     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #82     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #89     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #96     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #102    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #107    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3843:14)
I/flutter (17537): #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3843:14)
I/flutter (17537): #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #114    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #115    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #116    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #121    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #123    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3843:14)
I/flutter (17537): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3843:14)
I/flutter (17537): #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #134    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #136    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #139    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3843:14)
I/flutter (17537): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #143    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #145    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #146    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #150    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #151    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #152    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #155    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #157    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #158    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2875:5)
I/flutter (17537): #159    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3013:22)
I/flutter (17537): #160    ComponentElement.mount (package:flutter/src/widgets/framework.dart:2870:5)
I/flutter (17537): #161    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2248:14)
I/flutter (17537): #162    Element.updateChild (package:flutter/src/widgets/framework.dart:2076:12)
I/flutter (17537): #163    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3634:26)
I/flutter (17537): #164    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3949:17)
I/flutter (17537): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:2069:15)
I/flutter (17537): #166    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:505:16)
I/flutter (17537): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2069:15)
I/flutter (17537): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #169    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #170    StatefulElement.update (package:flutter/src/widgets/framework.dart:3032:5)
I/flutter (17537): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2069:15)
I/flutter (17537): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #173    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #174    ProxyElement.update (package:flutter/src/widgets/framework.dart:3150:5)
I/flutter (17537): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2069:15)
I/flutter (17537): #176    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3850:14)
I/flutter (17537): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2069:15)
I/flutter (17537): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #179    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #180    StatefulElement.update (package:flutter/src/widgets/framework.dart:3032:5)
I/flutter (17537): #181    Element.updateChild (package:flutter/src/widgets/framework.dart:2069:15)
I/flutter (17537): #182    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3850:14)
I/flutter (17537): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2069:15)
I/flutter (17537): #184    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3850:14)
I/flutter (17537): #185    Element.updateChild (package:flutter/src/widgets/framework.dart:2069:15)
I/flutter (17537): #186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2907:16)
I/flutter (17537): #187    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2784:5)
I/flutter (17537): #188    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1769:33)
I/flutter (17537): #189    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:313:20)
I/flutter (17537): #190    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:165:5)
I/flutter (17537): #191    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:652:15)
I/flutter (17537): #192    BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:587:9)
I/flutter (17537): #193    _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (17537): (elided one frame from class _AssertionError)
I/flutter (17537): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17537): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2120 pos 12: '_debugLifecycleState == _ElementLifecycle.active' is not true.
I/flutter (17537): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2930 pos 12: 'child == _child' is not true.
I/flutter (17537): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2930 pos 12: 'child == _child' is not true.
I/flutter (17537): Another exception was thrown: 'package:flutter/src/rendering/semantics.dart': Failed assertion: line 674 pos 14: 'node.parent?._dirty != true' is not true.
```

**Comment by eseidelGoogle** [comment]
Is there an example of the effect you're seeking to achieve somewhere we can reference to?

**Comment by zoechi** [comment]
The idea was to have a list of menu items in the drawer and update the body part of the material `Scaffold`. I have seen examples where `MaterialPageRoute` is used but that replaces the whole view.

It seems `Navigator` can be inserted into the body (perhaps also nested).
I tried that and passed a `GlobalKey` to this navigator but when I push to this `Navigator` I get above exception.

Is `MaterialPageRoute` the way to go or is my approach also meaningful?

**Comment by eseidelGoogle** [comment]
@Hixie is the right person to comment.  I'm not sure we have a widget today which does the navigation you describe.

**Comment by Hixie** [comment]
You don't have to use a Navigator to change the contents of the body. You can just provide a new set of widgets when you rebuild the MaterialApp.

**Comment by zoechi** [comment]
@Hixie I thought about that. 
Not sure yet how to best communicate to that widget that it should build its children differently.
What is `Navigator` for then?

**Comment by zoechi** [comment]
I could reproduce the exception above with the stocks example
https://github.com/bwu-dart-playground/flutter_app2
I just copied the examples files to a new project created with `flutter create` because the example code wasn't included when I checked out the flutter repo.

**Comment by Hixie** [comment]
Navigator is for changing to new pages entirely (replacing the toolbar and everything), especially with animated transitions between them.

Navigator is actually just a widget like any other. You can use it or not use it as you wish. :-)

**Comment by zoechi** [comment]
I didn't understand it because whatever I tried I only got that exception. Now that I saw the exception is also thrown in your example, I'm more confident that I actually understood what the `Navigator` class is doing.

**Comment by sethladd** [comment]
I'd like to close this in favor of https://github.com/flutter/flutter/issues/1429 but if that issue isn't sufficient, we can reopen.

**Comment by zoechi** [comment]
I'm not sure. I get the exception above also with the Stock demo application. So it seems like a real bug.
If only the API has changed and this is what causes the exception, then closing is fine of course.

**Comment by sethladd** [comment]
Ah, can you re-title this issue to be clear it's not about documentation, but about a framework bug? (or, open a new issue) Thanks!

**Comment by zoechi** [comment]
Will do.

**Comment by zoechi** [comment]
@sethladd I updated Flutter and dependencies and now the Stock demo is working, so I don't think there is anything to do.

**Comment by sethladd** [comment]
Thanks, I'll close for now.

**Comment by eseidel** [comment]
For anyone ending up here from Google, here is an example of routing:
https://github.com/flutter/flutter/blob/master/examples/stocks/lib/main.dart#L126

**Comment by stevenroose** [comment]
There seems to be lacking documentation for nested routing of any kind. Or seems unsupported.

Imagine scenario: the global App has a navigator with different full-screen views. Inside the `/home` view, the scaffold body should be able to route `/home/mapview` and `/home/listview` for example. In my case, I'd prefer even routes with parameters: `/wallet/:walletid/balance` f.e., where the scaffold fills the body with a wallet view, with the given `:walletid` as a parameter and as a subroute of the walllet view, the `/balance` route.

I think something like this could work, by having the body of the scaffold be a navigator, but most of the routing must then be manually implemented. Would be nice to have a widget that is a navigator where you can pass relative routes with different builders that automatically gets triggered when the super-route changes.

**Comment by johnpryan** [comment]
The stock example has routing, but it's example uses `popAndPushNamed` from a ListItem in a Drawer. This causes the drawer to close, and the settings page to slide in from the right. Ideally, it would work similar to Inbox (for example) where the current page is replaced by the new page that was selected. I can't seem to find a Flutter app that does this without avoiding Navigator altogether.
