### ISSUE TITLE
Crash while running `flutter` commands

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#69863]
## Steps to Reproduce

Ran `flutter upgrade --force`

## Logs

```
$ flutter upgrade --force
Upgrading Flutter from /Users/mit/dev/flutter...
Downloading Dart SDK from Flutter engine e66a720137d9e9c5f0d78439a025fea74f40b46b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  177M    0 12564    0     0  20630      0  2:29:59 --:--:--  2:29:59 20596
  9  177M    9 16.6M    0     0  11.1M      0  0:00:15  0:00:01  0:00:14 11.1M
 22  177M   22 39.9M    0     0  16.0M      0  0:00:11  0:00:02  0:00:09 16.0M
 37  177M   37 66.3M    0     0  18.8M      0  0:00:09  0:00:03  0:00:06 18.8M
 51  177M   51 92.0M    0     0  20.4M      0  0:00:08  0:00:04  0:00:04 20.4M
 66  177M   66  117M    0     0  21.3M      0  0:00:08  0:00:05  0:00:03 23.9M
 81  177M   81  144M    0     0  22.1M      0  0:00:07  0:00:06  0:00:01 25.4M
 96  177M   96  170M    0     0  22.8M      0  0:00:07  0:00:07 --:--:-- 26.2M
100  177M  100  177M    0     0  22.9M      0  0:00:07  0:00:07 --:--:-- 26.3M
Building flutter tool...

Upgrading engine...
Downloading Android Maven dependencies...                          749ms

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)".
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)".
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:170:7)
#1      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#2      _rootRunBinary (dart:async/zone.dart:1214:47)
#3      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#7      Future._completeError (dart:async/future_impl.dart:537:5)
#8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#9      _doctorText (package:flutter_tools/runner.dart)
#10     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#11     _rootRunBinary (dart:async/zone.dart:1214:47)
#12     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#13     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#14     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#15     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#16     Future._completeError (dart:async/future_impl.dart:537:5)
#17     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
| ~/tmp/repro21 @ mit-macbookpro3 (mit)
$
```

After running it a second time I get:

```
$ flutter upgrade --force
Flutter is already up to date on channel master
Flutter 1.24.0-8.0.pre.96 • channel master • https://github.com/flutter/flutter.git
Framework • revision 4bd89b399e (8 minutes ago) • 2020-11-05 03:29:04 -0500
Engine • revision e66a720137
Tools • Dart 2.12.0 (build 2.12.0-21.0.dev)
| ~/tmp/repro21 @ mit-macbookpro3 (mit)
```

**Comment by mit-mit** [comment]
Hmm, this same error also appears post-upgrade when creating projects:

```
$ flutter create a2
Creating project a2...
  a2/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
...
  a2/.idea/modules.xml (created)
  a2/.idea/workspace.xml (created)
Running "flutter pub get" in a2...                               1,574ms
Wrote 73 files.

All done!

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)".
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)".
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:170:7)
#1      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#2      _rootRunBinary (dart:async/zone.dart:1214:47)
#3      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#6      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#7      Future._completeError (dart:async/future_impl.dart:537:5)
#8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#9      _doctorText (package:flutter_tools/runner.dart)
#10     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#11     _rootRunBinary (dart:async/zone.dart:1214:47)
#12     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#13     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#14     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#15     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#16     Future._completeError (dart:async/future_impl.dart:537:5)
#17     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#24     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#25     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
| ~/tmp @ mit-macbookpro3 (mit)
$
```

**Comment by mit-mit** [comment]
And I just reproed with a new flutter checkout:

```
cd ~/tmp
git clone https://github.com/flutter/flutter.git
$ ./flutter/bin/flutter
$ ./flutter/bin/flutter create a2
```

=>

```
Wrote 3 files.

All done!

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)".
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)
Please report a bug at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)".
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)
Please report a bug at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:170:7)
#1      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
#2      _rootRunBinary (dart:async/zone.dart:1214:47)
#3      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#4      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#5      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
```

**Comment by pedromassangocode** [comment]
I just tried the steps in https://github.com/flutter/flutter/issues/69863#issuecomment-722258008 and was not able to reproduce the issue, every command ran as expected.

<details><summary>Logs</summary>

```
pedromassango@MacBook-Pro-de-MacBook Desktop % git clone https://github.com/flutter/flutter.git && ./flutter/bin/flutter create a2
Cloning into 'flutter'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 274722 (delta 6), reused 4 (delta 1), pack-reused 274701
Receiving objects: 100% (274722/274722), 119.09 MiB | 1.78 MiB/s, done.
Resolving deltas: 100% (212705/212705), done.
Updating files: 100% (4994/4994), done.
Downloading Dart SDK from Flutter engine e66a720137d9e9c5f0d78439a025fea74f40b46b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  177M  100  177M    0     0  1969k      0  0:01:32  0:01:32 --:--:-- 2455k
Building flutter tool...
Downloading Material fonts...                                    2,071ms
Downloading Gradle Wrapper...                                      101ms
Downloading package sky_engine...                                  855ms
Downloading flutter_patched_sdk tools...                            5.5s
Downloading flutter_patched_sdk_product tools...                    5.0s
Downloading darwin-x64 tools...                                    14.4s
Downloading libimobiledevice...                                  1,411ms
Downloading usbmuxd...                                             382ms
Downloading libplist...                                            117ms
Downloading openssl...                                             799ms
Downloading ios-deploy...                                          427ms
Downloading darwin-x64/font-subset tools...                      1,900ms
Creating project a2...
  a2/windows/runner/flutter_window.cpp (created)
  a2/windows/runner/utils.h (created)
  a2/windows/runner/run_loop.h (created)
  a2/windows/runner/utils.cpp (created)
  a2/windows/runner/runner.exe.manifest (created)
  a2/windows/runner/CMakeLists.txt (created)
  a2/windows/runner/win32_window.h (created)
  a2/windows/runner/Runner.rc (created)
  a2/windows/runner/win32_window.cpp (created)
  a2/windows/runner/resources/app_icon.ico (created)
  a2/windows/runner/main.cpp (created)
  a2/windows/runner/resource.h (created)
  a2/windows/runner/run_loop.cpp (created)
  a2/windows/runner/flutter_window.h (created)
  a2/windows/flutter/CMakeLists.txt (created)
  a2/windows/.gitignore (created)
  a2/windows/CMakeLists.txt (created)
  a2/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  a2/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  a2/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  a2/ios/Runner/Info.plist (created)
  a2/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  a2/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  a2/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  a2/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  a2/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  a2/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  a2/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  a2/ios/Runner/Base.lproj/Main.storyboard (created)
  a2/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  a2/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  (created)
  a2/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  (created)
  a2/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  a2/ios/Flutter/Debug.xcconfig (created)
  a2/ios/Flutter/Release.xcconfig (created)
  a2/ios/Flutter/AppFrameworkInfo.plist (created)
  a2/ios/.gitignore (created)
  a2/test/widget_test.dart (created)
  a2/a2.iml (created)
  a2/.gitignore (created)
  a2/web/favicon.png (created)
  a2/web/index.html (created)
  a2/web/manifest.json (created)
  a2/web/icons/Icon-192.png (created)
  a2/web/icons/Icon-512.png (created)
  a2/.metadata (created)
  a2/macos/Runner.xcworkspace/contents.xcworkspacedata (created)
  a2/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  a2/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png (created)
  a2/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png (created)
  a2/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png (created)
  a2/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png (created)
  a2/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png (created)
  a2/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png (created)
  a2/macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  a2/macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png (created)
  a2/macos/Runner/DebugProfile.entitlements (created)
  a2/macos/Runner/Base.lproj/MainMenu.xib (created)
  a2/macos/Runner/MainFlutterWindow.swift (created)
  a2/macos/Runner/Configs/Debug.xcconfig (created)
  a2/macos/Runner/Configs/Release.xcconfig (created)
  a2/macos/Runner/Configs/Warnings.xcconfig (created)
  a2/macos/Runner/Configs/AppInfo.xcconfig (created)
  a2/macos/Runner/AppDelegate.swift (created)
  a2/macos/Runner/Info.plist (created)
  a2/macos/Runner/Release.entitlements (created)
  a2/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  (created)
  a2/macos/Runner.xcodeproj/project.pbxproj (created)
  a2/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  a2/macos/Flutter/Flutter-Debug.xcconfig (created)
  a2/macos/Flutter/Flutter-Release.xcconfig (created)
  a2/macos/.gitignore (created)
  a2/android/app/src/profile/AndroidManifest.xml (created)
  a2/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  a2/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  a2/android/app/src/main/res/drawable/launch_background.xml (created)
  a2/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  a2/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  a2/android/app/src/main/res/values-night/styles.xml (created)
  a2/android/app/src/main/res/values/styles.xml (created)
  a2/android/app/src/main/res/drawable-v21/launch_background.xml (created)
  a2/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  a2/android/app/src/main/AndroidManifest.xml (created)
  a2/android/app/src/debug/AndroidManifest.xml (created)
  a2/android/gradle/wrapper/gradle-wrapper.properties (created)
  a2/android/gradle.properties (created)
  a2/android/.gitignore (created)
  a2/android/settings.gradle (created)
  a2/android/app/build.gradle (created)
  a2/android/app/src/main/kotlin/com/example/a2/MainActivity.kt (created)
  a2/android/build.gradle (created)
  a2/android/a2_android.iml (created)
  a2/pubspec.yaml (created)
  a2/README.md (created)
  a2/ios/Runner/Runner-Bridging-Header.h (created)
  a2/ios/Runner/AppDelegate.swift (created)
  a2/ios/Runner.xcodeproj/project.pbxproj (created)
  a2/lib/main.dart (created)
  a2/.idea/runConfigurations/main_dart.xml (created)
  a2/.idea/libraries/Dart_SDK.xml (created)
  a2/.idea/libraries/KotlinJavaRuntime.xml (created)
  a2/.idea/modules.xml (created)
  a2/.idea/workspace.xml (created)
Running "flutter pub get" in a2...                                  4.5s
Wrote 121 files.

All done!
[✓] Flutter: is fully installed. (Channel master, 1.24.0-8.0.pre.96, on Mac OS X
    10.15.7 19H2 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK
    version 30.0.1)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 12.1)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 4.0)
[✓] IntelliJ IDEA Community Edition: is fully installed. (version 2020.2.3)
[✓] VS Code: is fully installed. (version 1.50.1)
[✓] Connected device: is fully installed. (4 available)

In order to run your application, type:

  $ cd a2
  $ flutter run

Your application code is in a2/lib/main.dart.

pedromassango@MacBook-Pro-de-MacBook Desktop % 

```
</details>

**Comment by mraleph** [comment]
I suspect 422a97d1e58 based on timing and exception text. It has the following code: 

```dart
    final int major = version?.major;
    final int minor = version?.minor;
    if (globals.platform.isMacOS) {
      /// plugin path of Android Studio has been changed after version 4.1.
      if (major >= 4 && minor >= 1) {
```

Here `major` can obviously be `null` but this is not accounted for. Waiting on @mit-mit to confirm with some additional debugging stack traces.

**Comment by mit-mit** [comment]
Dropping to P1 as this only affects some machine configs (likely those with Android Studio 4.1)

**Comment by mraleph** [comment]
@mit-mit produced the following additional information using the following patch from me

```
diff --git a/packages/flutter_tools/lib/runner.dart b/packages/flutter_tools/lib/runner.dart
index 7d41db41bf..9d878bf079 100644
--- a/packages/flutter_tools/lib/runner.dart
+++ b/packages/flutter_tools/lib/runner.dart
@@ -159,9 +159,9 @@ Future<int> _handleToolError(

       return _exit(1);
     // This catch catches all exceptions to ensure the message below is printed.
-    } catch (error) { // ignore: avoid_catches_without_on_clauses
+    } catch (error, stack) { // ignore: avoid_catches_without_on_clauses
       globals.stdio.stderrWrite(
-        'Unable to generate crash report due to secondary error: $error\n'
+        'Unable to generate crash report due to secondary error: $error\n$stack\n'
         '${globals.userMessages.flutterToolBugInstructions}\n');
       // Any exception thrown here (including one thrown by `_exit()`) will
       // get caught by our zone's `onError` handler. In order to avoid an
```

```
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(4)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:74:17)
#2      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:252:67)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#5      WhereIterator.moveNext (dart:_internal/iterable.dart:441:22)
#6      new List.from (dart:core-patch/array_patch.dart:50:19)
#7      new List.of (dart:core-patch/array_patch.dart:68:17)
```

This confirms my hunch I will simply revert the offending change.

**Comment by mraleph** [comment]
Offending change was reverted.

**Comment by mit-mit** [comment]
Confirmed working now :-), thanks @mraleph 🥇
