### ISSUE TITLE
after updating to iOS 14: " Connection closed before full header was received"

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#69885]
I have no way to reproduce this with an MVCE. I updated to iOS 14 on my iPhone 8+ which is plugged directly into my 27" iMac running `10.15.7`. I can run it from XCode but when I try to do `flutter run` I get this error. This issue exists on `beta`, `dev`, and `master`. I haven't tested others.

```
[        ] Application launched on the device. Waiting for observatory port.
[  +16 ms] Attempting to forward device port 56605 to host port 59669
[        ] executing:
/Users/lukepighetti/development/flutter/bin/cache/artifacts/usbmuxd/iproxy
59669:56605 --udid 0bc0c4864d8e08aac4456893cded68bf0b6767d5
[+1010 ms] Forwarded port ForwardedPort HOST:59669 to DEVICE:56605
[  +13 ms] HttpException: Connection closed before full header was received,
uri = http://localhost:59669/ws
[+2008 ms] HttpException: , uri = http://localhost:59669/ws
[+2004 ms] HttpException: , uri = http://localhost:59669/ws
[+2005 ms] HttpException: , uri = http://localhost:59669/ws
[+2006 ms] HttpException: , uri = http://localhost:59669/ws
[+2005 ms] Failed to connect directly, falling back to log scanning
[+5012 ms] Failed to connect with log scanning
[   +1 ms] Installing and launching... (completed in 48.5s)
[        ] Error launching application on Luke's iPhone.
[   +5 ms] "flutter run" took 109,772ms.
[   +5 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:618:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1005:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue
(dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete
           (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn
(dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues
(package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue
(dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback
           (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners
(dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue
(dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure>
           (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure>
           (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback
           (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage
           (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +235 ms] ensureAnalyticsSent: 233ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
```

If I run Flutter doctor I get this error. I have restarted, re-paired device, flutter cleaned, reinstalled Xcode, reinstalled Flutter with no relief.

```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)
    ! Error: Luke's iPhone is busy: Copying cache files from device. Xcode
      will continue when Luke's iPhone is finished. (code -10)

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @lukepighetti 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`?

Isn’t this message related?

> [✓] Connected device (3 available)
>     ! Error: Luke's iPhone is busy: Copying cache files from device. Xcode
>       will continue when Luke's iPhone is finished. (code -10)
> 

Thank you

**Comment by lukepighetti** [comment]
<details>
  <summary>flutter doctor -v</summary>

```
% flutter doctor -v
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/lukepighetti/development/flutter
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/lukepighetti/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/lukepighetti/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Luke's iPhone (mobile) • 0bc0c4864d8e08aac4456893cded68bf0b6767d5 • ios            • iOS 14.1
    • Web Server (web)       • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 86.0.4240.183
    ! Error: Luke's iPhone is busy: Copying cache files from device. Xcode will continue when Luke's iPhone is finished. (code -10)

• No issues found!
```
</details>

`flutter run --flavor sandbox -v`

https://gist.github.com/lukepighetti/6bc81f81d4fa264d33391ffe5c7c8b22

**Comment by pedromassangocode** [comment]
Looks like the device is somehow unavailable at the moment based on the logs.

```bash
             {
               "modelCode" : "iPhone10,2",
               "simulator" : false,
               "modelName" : "iPhone 8 Plus (Model A1864, A1897, A1898, A1899)",
               "error" : {
                 "code" : -10,
                 "failureReason" : "",
                 "underlyingErrors" : [
                   {
                     "code" : 5,
                     "failureReason" : "allowsSecureServices: 1. isConnected: 0. Platform: <DVTPlatform:0x7fd6c070e000:'com.apple.platform.iphoneos':<DVTFilePath:0x7fd6c070df80:'\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform'>>. DTDKDeviceIdentifierIsIDID: 0",
                     "description" : "Failed _shouldMakeReadyForDevelopment check even though device is not locked by passcode.",
                     "recoverySuggestion" : "",
                     "domain" : "com.apple.platform.iphoneos"
                   }
                 ],
                 "description" : "Luke's iPhone is busy: Copying cache files from device",
                 "recoverySuggestion" : "Xcode will continue when Luke's iPhone is finished.",
                 "domain" : "com.apple.platform.iphoneos"
               },
               "operatingSystemVersion" : "14.1 (18A8395)",
               "identifier" : "0bc0c4864d8e08aac4456893cded68bf0b6767d5",
               "platform" : "com.apple.platform.iphoneos",
               "architecture" : "arm64",
               "interface" : "usb",
               "available" : false,
               "name" : "Luke's iPhone",
               "modelUTI" : "com.apple.iphone-8-plus-2"
             }
```

**Comment by lukepighetti** [comment]
As a note this issue doesn't exist within XCode. I can build and run from XCode just fine. It's when I run from the command line that I get this issue.

**Comment by lukepighetti** [comment]
I have:

- updated my iPhone / iMac to latest production release
- updated flutter to latest `beta` release
- reinstalled XCode, cleared out prefs files, updated to latest
- flutter clean
- erased & restored iPhone from backup

No relief

**Comment by lukepighetti** [comment]
When I run on XCode it works perfectly. When I run from Flutter CLI I get the network popup and it detaches and errors.

**Comment by lukepighetti** [comment]
`flutter run --release` works fine, `flutter run` does not.

**Comment by lukepighetti** [comment]
Finally got this resolved using an XCode uninstall script I found on Stack. Going to close this and leave this here in case someone else runs into this issue.

Might want to

-  put this in a script file like `xcode-uninstall.sh`
- make executable with `chmod +x xcode-uninstall.sh` 
- run as admin `sudo ./xcode-uninstall.sh`

```
killall Xcode
killall Simulator
xcrun -k
xcodebuild -alltargets clean
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache"
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang.$(whoami)/ModuleCache"
rm -rf /Applications/Xcode.app
rm -rf ~/Library/Caches/com.apple.dt.Xcode
rm -rf ~/Library/Developer
rm -rf ~/Library/MobileDevice
rm -rf ~/Library/Preferences/com.apple.dt.Xcode.plist
rm -rf ~/Library/Preferences/com.apple.dt.xcodebuild.plist
rm -rf /Library/Preferences/com.apple.dt.Xcode.plist
rm -rf /System/Library/Receipts/com.apple.pkg.XcodeExtensionSupport.bom
rm -rf /System/Library/Receipts/com.apple.pkg.XcodeExtensionSupport.plist
rm -rf /System/Library/Receipts/com.apple.pkg.XcodeSystemResources.bom
rm -rf /System/Library/Receipts/com.apple.pkg.XcodeSystemResources.plist
rm -rf /private/var/db/receipts/com.apple.pkg.Xcode.bom
```
