### ISSUE TITLE
Form: Multiple widgets used the same GlobalKey error

### ISSUE THREAD

**Issue by lablnet** [flutter/flutter#69955]
Form: Multiple widgets used the same GlobalKey error

Here is my CustomForm class
`CustomForm.dart`
```dart

import 'package:flutter/material.dart';

class CustomForm extends StatelessWidget {
  CustomForm({this.children, this.imagePath, this.loading, this.key});
  List<Widget> children;
  String imagePath;
  bool loading;
  Key key;
  @override
  Widget build(BuildContext context) {
    if (imagePath == null) imagePath = "assets/images/logo.png";
    return Form(
      key: key,
      child: ListView(
        children: <Widget>[
          loading ? LinearProgressIndicator() : SizedBox(height: 2),
          SizedBox(height: 30),
          Image.asset(
            imagePath,
            height: 230,
          ),
          SizedBox(height: 10),
          ...children,
        ],
      ),
    );
  }
}
```
i have change the constructor like this
```dart
  CustomForm({this.children, this.imagePath, this.loading, Key key})
      : super(key: GlobalKey<FormState>());
  List<Widget> children;
  String imagePath;
  bool loading;
  // Key key;
```

i use my class as follow
```dart
  Widget _buildBody(BuildContext context) {
    print("Login");
    return CustomForm(
      key: _formKey,
      imagePath: "assets/images/Login.png",
      loading: isLoading,
      children: <Widget>[...]
    );
}
...
i generated the key as follow
```dart
final _formKey = GlobalKey<FormState>();
```

## Steps to Reproduce

I try in a bit more different way but nothing were works for me. and i do not find any useful resources to understand how i can get rid even i do not know after passing different key to parent class why it is showing the error.

**Expected results:** It should not show the error.

**Actual results:** even i am passing the separate key to parent class it is showing same error .

Project: https://github.com/resourcesr/app

<details>
  <summary>Logs</summary>

```
[   +2 ms] An Observatory debugger and profiler on sdk gphone x86 arm is available at:
           http://127.0.0.1:46437/6As6GXuTMVg=/
[+8974 ms] I/flutter ( 5951): Login
[+1096 ms] I/flutter ( 5951): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
[   +6 ms] I/flutter ( 5951): The following assertion was thrown while finalizing the widget tree:
[   +3 ms] I/flutter ( 5951): Multiple widgets used the same GlobalKey.
[   +1 ms] I/flutter ( 5951): The key [LabeledGlobalKey<FormState>#a5974] was used by multiple
widgets. The parents of those
[   +8 ms] I/flutter ( 5951): widgets were:
[   +2 ms] I/flutter ( 5951): - CustomForm-[LabeledGlobalKey<FormState>#a5974]
[   +1 ms] I/flutter ( 5951): - _BodyBuilder
[        ] I/flutter ( 5951): A GlobalKey can only be specified on one widget at a time in the
widget tree.
[   +4 ms] I/flutter ( 5951): 
[        ] I/flutter ( 5951): When the exception was thrown, this was the stack:
[        ] I/flutter ( 5951): #0      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous
closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:267:13)
[  +39 ms] I/flutter ( 5951): #1      _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:377:8)
[   +1 ms] I/flutter ( 5951): #2      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous
closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:214:20)
[   +6 ms] I/flutter ( 5951): #3      _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:377:8)
[   +1 ms] I/flutter ( 5951): #4      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>
(package:flutter/src/widgets/framework.dart:210:26)
[        ] I/flutter ( 5951): #5      GlobalKey._debugVerifyGlobalKeyReservation
(package:flutter/src/widgets/framework.dart:275:6)
[        ] I/flutter ( 5951): #6      BuildOwner.finalizeTree.<anonymous closure>
(package:flutter/src/widgets/framework.dart:2872:21)
[   +1 ms] I/flutter ( 5951): #7      BuildOwner.finalizeTree
(package:flutter/src/widgets/framework.dart:2953:8)
[        ] I/flutter ( 5951): #8      WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:908:19)
[   +2 ms] I/flutter ( 5951): #9      RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:309:5)
[        ] I/flutter ( 5951): #10     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1117:15)
[        ] I/flutter ( 5951): #11     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1055:9)
[        ] I/flutter ( 5951): #12     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:971:5)
[        ] I/flutter ( 5951): #16     _invoke (dart:ui/hooks.dart:251:10)
[        ] I/flutter ( 5951): #17     _drawFrame (dart:ui/hooks.dart:209:3)
[        ] I/flutter ( 5951): (elided 3 frames from dart:async)
[        ] I/flutter ( 5951):
════════════════════════════════════════════════════════════════════════════════════════════════════
[+1364 ms] I/flutter ( 5951): Another exception was thrown: Multiple widgets used the same
GlobalKey.
[ +469 ms] I/flutter ( 5951): Another exception was thrown: Multiple widgets used the same
GlobalKey.

```

```
Analyzing riphahwebresources...                                         

   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: TextAvatar.text •
          lib/components/avatars.dart:6:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: FileIconAvatar.fileType •
          lib/components/avatars.dart:22:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: ImageAvatar.url •
          lib/components/avatars.dart:53:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: StretchableButton.onPressed •
          lib/components/buttons.dart:11:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: CustomForm.children, CustomForm.imagePath,
          CustomForm.loading • lib/components/custom_form.dart:4:7 • must_be_immutable
   info • Avoid using braces in interpolation when not needed • lib/data/Downloader.dart:83:27 •
          unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/data/Downloader.dart:83:36 •
          unnecessary_brace_in_string_interps
   info • Name non-constant identifiers using lowerCamelCase • lib/data/User.dart:94:35 •
          non_constant_identifier_names
   info • This function has a return type of 'FutureOr<User>', but doesn't end with a return
          statement • lib/data/User.dart:108:16 • missing_return
   info • This function has a return type of 'FutureOr<User>', but doesn't end with a return
          statement • lib/data/User.dart:123:16 • missing_return
   info • This function has a return type of 'FutureOr<User>', but doesn't end with a return
          statement • lib/data/User.dart:135:16 • missing_return
   info • The declaration '_openUrl' isn't referenced • lib/pages/Courses/resources_ui.dart:81:3 •
          unused_element
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: EventDetailUi.title, EventDetailUi.start,
          EventDetailUi.end, EventDetailUi.room, EventDetailUi.duration •
          lib/pages/Event/event_detail_ui.dart:5:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: Home.code • lib/pages/Event/home.dart:13:7 •
          must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: TimetableUi.code •
          lib/pages/Event/timetable_ui.dart:14:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: ProfileUi.user •
          lib/pages/auth/profile_ui.dart:10:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: SelectKlassUi.user •
          lib/pages/auth/select_klass_ui.dart:8:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: DashboardSplashUi.user •
          lib/pages/dashboard_splash_ui.dart:8:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: DashboardUi.user •
          lib/pages/dashboard_ui.dart:9:7 • must_be_immutable
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/dashboard_ui.dart:24:9 •
          non_constant_identifier_names
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: DownloadUi.children •
          lib/pages/downlaod_ui.dart:13:7 • must_be_immutable
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one
          or more of its instance fields aren't final: MenuUi.user • lib/pages/menu_ui.dart:9:7 •
          must_be_immutable

22 issues found. (ran in 18.3s)

```

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.23.0-18.1.pre at /etc/flutter
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/lablnet/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at:
      /home/lablnet/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at
      /home/lablnet/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /home/lablnet/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/202.6948.69
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /home/lablnet/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.48.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @lablnet 
Can you please provide, a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) not  a complete project 
Thank you

**Comment by lablnet** [comment]
> Can you please provide, a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) not a complete project

Yes sure, here we go.
`main.dart` complete one page app.
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final _formKey = GlobalKey<FormState>();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        child: CustomForm(
          key: _formKey,
          imagePath: null,
          loading: false,
          children: [
            TextFormField(
              validator: (value) {
                if (value.isEmpty) return "Field is required";
                return null;
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class CustomForm extends StatelessWidget {
  CustomForm({this.children, this.imagePath, this.loading, this.key});
  List<Widget> children;
  String imagePath;
  bool loading;
  Key key;
  @override
  Widget build(BuildContext context) {
    if (imagePath == null) imagePath = "assets/images/logo.png";
    return Form(
      key: key,
      child: ListView(
        shrinkWrap: true,
        children: <Widget>[
          loading ? LinearProgressIndicator() : SizedBox(height: 2),
          SizedBox(height: 30),
          /*Image.asset(
            imagePath,
            height: 230,
          ),*/
          SizedBox(height: 10),
          ...children,
        ],
      ),
    );
  }
}
```


#### Update
i have try to modify the class behavior like that as suggested by [stack-overflow](https://stackoverflow.com/questions/64716666/flutter-form-multiple-widgets-used-the-same-globalkey-error/64720220#64720220) answer but showing the same result to me.

```dart
  const CustomForm({this.children, this.imagePath, this.loading, this.formKey, Key key}) : super(key: key);
  List<Widget> children;
  String imagePath;
  bool loading;
  GlobalKey<FormState> formKey;
```

**Comment by TahaTesser** [comment]
Hi @lablnet 
Your overwriting default key by using `key` as a variable, causing this error. Please try these code samples  below  and check out https://github.com/flutter/flutter/issues/16630#issuecomment-701320704

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  final _formKey = GlobalKey<FormState>();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        child: CustomForm(
          formKey: _formKey,
          imagePath: null,
          loading: false,
          children: [
            TextFormField(
              validator: (value) {
                if (value.isEmpty) return "Field is required";
                return null;
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

class CustomForm extends StatelessWidget {
  CustomForm({this.children, this.imagePath, this.loading, this.formKey});
  List<Widget> children;
  String imagePath;
  bool loading;
  Key formKey;
  @override
  Widget build(BuildContext context) {
    if (imagePath == null) imagePath = "assets/images/logo.png";
    return Form(
      key: formKey,
      child: ListView(
        shrinkWrap: true,
        children: <Widget>[
          loading ? LinearProgressIndicator() : SizedBox(height: 2),
          SizedBox(height: 30),
          /*Image.asset(
            imagePath,
            height: 230,
          ),*/
          SizedBox(height: 10),
          ...children,
        ],
      ),
    );
  }
}
```

</details>

Minimal sample
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(
        formkey: _formKey,
        title: 'Appbar',
      ),
    );
  }
}

class Home extends StatelessWidget {
  final String title;
  final Key formkey;
  const Home({Key key, this.title, this.formkey}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Form(
          key: key,
          child: TextField(),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H15, locale en-GB)
    • Flutter version 1.22.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8874f21e79 (10 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/SanDisk/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile)       • 00008020-000255113EE8402E            • ios •
      iOS 14.2
    • iPhone 12 Pro Max (mobile) • 0A159C14-BF48-4DD7-8D91-F45A387EE4B2 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

! Doctor found issues in 1 category.
```

</details>

**Comment by lablnet** [comment]
> Hi @lablnet
> Your overwriting default key by using `key` as a variable, causing this error. Please try these code samples below and check out [#16630 (comment)

Hi thanks, that works fine, the issue fixed. As issue fixed i am going to close this issue.
