### ISSUE TITLE
[tool_crash] StateError: Bad state: No element

### ISSUE THREAD

**Issue by akospwc** [flutter/flutter#69964]
## Command
```
flutter run -d chrome --verbose
```

## Steps to Reproduce
1. Create a new flutter web project with flutter beta
2. Change the base href in index.html from "/" to "/bo/" 
3. Run flutter run -d chrome
4. Flutter opens localhost:<randomport> but fails to load anything because of the wrong href
5. Append /bo/ to the URL in chrome and reload
6. Crash

Note: the same flutter web project works flawlessly with the default "/" base href.

## Logs
StateError: Bad state: No element
```
#0      List.last (dart:core-patch/growable_array.dart:255:5)
#1      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:95:35)
<asynchronous suspension>
#2      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:152:24)
#3      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:171:37)
<asynchronous suspension>
#4      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:138:23)
#5      DebugService.start (package:dwds/src/services/debug_service.dart:142:55)
#6      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:184:25)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.23.0-18.1.pre at /home/akos/bin/flutter_beta
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/akos/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin//java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 2 XL (mobile) • 803KPQJ1660092 • android-arm64  • Android 11 (API 30)
    • Web Server (web)    • web-server     • web-javascript • Flutter Tools
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 86.0.4240.183

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 198df796aa80073ef22bdf249e614e2ff33c6895

**Comment by darshankawar** [comment]
Issue occurs on latest beta and master.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E2269 x86_64,
    locale en-IN)
    • Flutter version 1.23.0-18.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.183

• No issues found!


```

</details>

[flutter_01.log](https://github.com/flutter/flutter/files/5509118/flutter_01.log)
[flutter_02.log](https://github.com/flutter/flutter/files/5509119/flutter_02.log)

**Comment by jonahwilliams** [comment]
@grouma this one is particularly reproducible. I can fix the tool side (To work around this, manually navigate to the URL), but the dwds crash also needs to be fixed.

**Comment by grouma** [comment]
I looked into this a bit. The issue we are running into is that we request for the DDC metadata contents in the wrong location. The base href is a part of the serverpath [here](https://github.com/dart-lang/webdev/blob/9b66ccd3073031001ff9cd61f64462e92d46013f/dwds/lib/src/debugging/metadata/provider.dart#L123).

This issue is similar to a problem we have resolved in `webdev` where each `webdev` application is actually nested under some top level path. `webdev` makes use of the [`ProxyServerAssetReader`](https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/readers/proxy_server_asset_reader.dart) which has a `root` configuration. This allows the [`readMetadataContents`](https://github.com/dart-lang/webdev/blob/9b66ccd3073031001ff9cd61f64462e92d46013f/dwds/lib/src/readers/proxy_server_asset_reader.dart#L69) to resolve properly under the nested path.

I think the infrastructure is in place for Flutter Tools to solve this itself assuming you can read the `base href`. @jonahwilliams thoughts?

**Comment by jonahwilliams** [comment]
I understood some of those words.

**Comment by grouma** [comment]
I'll set up a sync so I can walk you through the issue.
