### ISSUE TITLE
Flutter web dart:html and html.window.navigator.getGamepads()

### ISSUE THREAD

**Issue by rpaat** [flutter/flutter#70032]
Using Flutter web.

import 'dart:html' as html;
and calling 
html.window.navigator.getGamepads() 
causes error in asynchronous event handler. This was working fine in older beta channel and is happening in beta and dev at least now.

## Command
```
flutter run --machine --target lib\main.dart -d chrome --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      ChromeProxyService._setUpChromeConsoleListeners.<anonymous closure> (package:dwds/src/services/chrome_proxy_service.dart:719:63))
```
#0      ChromeProxyService._setUpChromeConsoleListeners.<anonymous closure> (package:dwds/src/services/chrome_proxy_service.dart:719:63)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#4      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#12     WipDomain.eventStream.<anonymous closure>.<anonymous closure> (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:311:22)
#13     _HandlerEventSink.add (dart:async/stream_transformers.dart:225:17)
#14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#19     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#20     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#21     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#22     _rootRun (dart:async/zone.dart:1182:47)
#23     _CustomZone.run (dart:async/zone.dart:1093:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
```
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale et-EE)
    • Flutter version 1.23.0-18.1.pre at C:\flutter
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Android\SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Android\SDK
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Rainer Paat\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.183
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.58

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: a0860f6e87ba4f9031bee4d6f56c08b970606bee

**Comment by rpaat** [comment]
Found the same report from Dart-lang SDK repo https://github.com/dart-lang/sdk/issues/43750
