### ISSUE TITLE
DateTime not working with localizationsDelegates

### ISSUE THREAD

**Issue by IAmJulianAcosta** [flutter/flutter#70040]
## Steps to Reproduce

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('es', 'CO')
      ],
      locale: Locale('es', 'CO'),
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    DateTime day = DateTime(2020, 11, 7);
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              DateFormat('EEEE, d').format(day),
              style: Theme.of(context).textTheme.headline6,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Expected results:** 
The text contains 'Sábado' (spanish for Saturday)

**Actual results:** 
Saturday

What I think that should be happening if that I set `locale: Locale('es', 'CO'),`, that will set the default locale for DateFormat too, but it is defaulting to `static String systemLocale = 'en_US';`.

I placed a debugger in the app and found this method:
```
  static String get defaultLocale {
    var zoneLocale = Zone.current[#Intl.locale] as String;
    return zoneLocale == null ? _defaultLocale : zoneLocale;
  }
```

I expect that this method will resolve to `locale` set in `MaterialApp()` constructor, but `zoneLocale` is `null` in this case

On the other hand if I run:
```
initializeDateFormatting();
Intl.defaultLocale = "es";
```

I get this error:
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following UnsupportedError was thrown building MediaQuery(MediaQueryData(size: Size(392.7, 759.3), devicePixelRatio: 2.8, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional)):
Unsupported operation: Cannot set value in unmodifiable Map

The relevant error-causing widget was: 
  MaterialApp file:///Users/julian/dev/bug/lib/main.dart:16:12
When the exception was thrown, this was the stack: 
#0      _ImmutableMap.[]= (dart:core-patch/immutable_map.dart:74:5)
#1      initializeDateFormattingCustom (package:intl/date_symbol_data_custom.dart:35:19)
#2      loadDateIntlDataIfNotLoaded.<anonymous closure> (package:flutter_localizations/src/utils/date_localizations.dart:43:9)
#3      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:8)
#4      _ImmutableMap.forEach (dart:core-patch/immutable_map.dart:43:8)
```

<details>
  <summary>Logs</summary>

```
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 0.9s)
[   +3 ms] executing: /Users/julian/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell echo -n
b7976f0d88c427d8e71587aaa3245da38440ae2f > /data/local/tmp/sky.com.example.bug.sha1
[  +81 ms] sdk gphone x86 arm startApp
[   +7 ms] executing: /Users/julian/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true
--ez enable-checked-mode true --ez verify-entry-points true com.example.bug/com.example.bug.MainActivity
[ +123 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has
extras) }
[   +1 ms] Waiting for observatory port to be available...
[+1517 ms] Observatory URL on device: http://127.0.0.1:35693/1JAfBsyqAx4=/
[   +1 ms] executing: /Users/julian/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:35693
[   +9 ms] 63761
[        ] Forwarded host port 63761 to device port 35693 for Observatory
[   +5 ms] Caching compiled dill
[  +33 ms] Connecting to service protocol: http://127.0.0.1:63761/1JAfBsyqAx4=/
[   +1 ms] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[ +358 ms] Successfully connected to service protocol: http://127.0.0.1:63761/1JAfBsyqAx4=/
[        ] Waiting for sdk gphone x86 arm to report its views...
[   +7 ms] Waiting for sdk gphone x86 arm to report its views... (completed in 6ms)
[  +11 ms] DevFS: Creating new filesystem on the device (null)
[  +27 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.example.bug/code_cache/bugQVYTJD/bug/)
[   +2 ms] Updating assets
[  +90 ms] Syncing files to device sdk gphone x86 arm...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:bug/main.dart c23465ab-da43-4b5a-9298-52854cd7672b
[        ] <- c23465ab-da43-4b5a-9298-52854cd7672b
[  +66 ms] Updating files
[ +174 ms] DevFS: Sync finished
[        ] Syncing files to device sdk gphone x86 arm... (completed in 247ms)
[        ] Synced 1.6MB.
[   +1 ms] <- accept
[   +4 ms] Connected to _flutterView/0xee3c3680.
[   +1 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on sdk gphone x86 arm is available at:
http://127.0.0.1:63761/1JAfBsyqAx4=/

```

```
Analyzing bug...
No issues found! (ran in 5.0s)
```

```
flutter doctor -v                                                                                            ─╯
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-CO)
    • Flutter version 1.22.3 at /Users/julian/dev/flutter
    • Framework revision 8874f21e79 (9 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/julian/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)


[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```
(I have plugins installed, not sure what's going on)

</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (10 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

![70040](https://user-images.githubusercontent.com/67046386/98521065-f5414180-2298-11eb-8e5a-fca85ea26dac.png)

**Comment by HansMuller** [comment]
CC @shihaohong
