### ISSUE TITLE
Hello, I had created a flutter project but am not able to run the sample flutter app. on executing flutter run am running into the following error something related to gradle. Please let me know whats wrong.

### ISSUE THREAD

**Issue by MeenuBabu** [flutter/flutter#70048]
On executing flutter run I am encountering the below issue.

<details> 
<summary>logs</summary> 

```bash
[+8931 ms] Exception in thread "main" java.io.FileNotFoundException:
C:\Users\meenu.babu\.gradle\wrapper\dists\gradle-6.0.1-all\99d3u8wxs16ndehh90lbbir67\gradle-6.0.1\src\diagnostics\org\gradle\api\tasks\diagnostics\htmldependencyreport\d.gif (Access is
denied)
[   +5 ms]      at java.io.FileOutputStream.open0(Native Method)
[   +2 ms]      at java.io.FileOutputStream.open(FileOutputStream.java:270)
[        ]      at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[        ]      at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[        ]      at org.gradle.wrapper.Install.unzip(Install.java:227)
[   +2 ms]      at org.gradle.wrapper.Install.access$600(Install.java:27)
[   +1 ms]      at org.gradle.wrapper.Install$1.call(Install.java:74)
[   +1 ms]      at org.gradle.wrapper.Install$1.call(Install.java:48)
[   +1 ms]      at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[   +1 ms]      at org.gradle.wrapper.Install.createDist(Install.java:48)
[   +1 ms]      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[   +1 ms]      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[  +25 ms] Running Gradle task 'assembleDebug'... (completed in 9.6s)
[   +3 ms] [!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
[+1322 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 21,451ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

</details>

**Comment by iapicca** [comment]
@MeenuBabu 
can you provide your `flutter doctor -v`
your `flutter run -v`
and a minimal reproducible code sample

**Comment by TahaTesser** [comment]
Hi @MeenuBabu 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by MeenuBabu** [comment]
Hi this seem to have sorted out. Please close this. Thank you
