### ISSUE TITLE
 Oops; flutter has exited unexpectedly: "FileSystemException: Cannot copy file to 'C:\Users\Yondaime      A crash report has been written to C:\Users\Yondaime Minato\Desktop\Me_Files\flutter-proj\prac\flutter_01.log.  utter-proj\prac\flutter_01.log.

### ISSUE THREAD

**Issue by Umar100** [flutter/flutter#70064]
my log
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter create .

## exception

FileSystemException: FileSystemException: Cannot copy file to 'C:\Users\Yondaime Minato\Desktop\Me_Files\flutter-proj\prac\web\favicon.png', path = 'C:\flutter\packages\flutter_tools\templates\app\web\favicon.png.copy.tmpl' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:239:20)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      Template.render (package:flutter_tools/src/template.dart:195:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:791:21)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#25     _templateImageDirectory (package:flutter_tools/src/template.dart)
#26     _rootRunUnary (dart:async/zone.dart:1198:47)
#27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#34     loadPackageConfigWithLogging (package:flutter_tools/src/dart/package_map.dart)
#35     _rootRunUnary (dart:async/zone.dart:1198:47)
#36     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#40     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#43     readAnyConfigFileUri (package:package_config/src/package_config_io.dart)
#44     _rootRunUnary (dart:async/zone.dart:1198:47)
#45     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#50     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#51     _rootRun (dart:async/zone.dart:1190:13)
#52     _CustomZone.run (dart:async/zone.dart:1093:19)
#53     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#54     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#55     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#56     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#57     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\flutter
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[!] Android toolchain - develop for Android devices
    • Android SDK at C:\Android\sdk
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

    • ANDROID_HOME = C:\Android\sdk
    ✗ No valid Android SDK platforms found in C:\Android\sdk\platforms. Candidates were:
        - android-23
        - android-29
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 1.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\Yondaime Minato\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.183

! Doctor found issues in 2 categories.
```

**Comment by pedromassangocode** [comment]
Hi @Umar100 
I see there's an open issue (https://github.com/flutter/flutter/issues/69116) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
