### ISSUE TITLE
[tool_crash] WebSocketChannelException while running automation testing

### ISSUE THREAD

**Issue by SujathaBabu** [flutter/flutter#70083]
## Command
```
flutter drive --target=test_driver/main.dart
```

## Steps to Reproduce
1. Run the above command. 
2. The expected output is, the sample needs to be launched. But this issue is thrown.

## Logs
WebSocketChannelException
```
#0      new IOWebSocketChannel._withoutSocket.<anonymous closure> (package:web_socket_channel/io.dart:84:24)
#1      _invokeErrorHandler (dart:async/async_error.dart:16:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:282:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#4      _rootRunBinary (dart:async/zone.dart:1214:47)
#5      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
#7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#9      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#10     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:812:19)
#11     _StreamController._addError (dart:async/stream_controller.dart:690:7)
#12     _rootRunBinary (dart:async/zone.dart:1214:47)
#13     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
#15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#18     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:812:19)
#19     _StreamController._addError (dart:async/stream_controller.dart:690:7)
#20     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:178:18)
#21     _rootRunBinary (dart:async/zone.dart:1214:47)
#22     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
#23     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#24     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
```
```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.149, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.24.0-8.0.pre.149 at C:\src\flutter
    • Framework revision 8e7748e74c (4 hours ago), 2020-11-08 20:32:04 -0800
    • Engine revision 0f7cdca65f
    • Dart version 2.12.0 (build 2.12.0-27.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM J700F (mobile) • 3300ea835939b387 • android-arm    • Android 6.0.1 (API 23)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 86.0.4240.183

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 4019956fc8d8d057427c77b99ebc6ac54defa6f1

**Comment by pedromassangocode** [comment]
Hi @SujathaBabu 
I see there's an open issue (https://github.com/flutter/flutter/issues/69433)  addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by SujathaBabu** [comment]
We are still facing the same issue even after taking update for master branch.

**Comment by pedromassangocode** [comment]
Please follow up on the issue mentioned in https://github.com/flutter/flutter/issues/70083#issuecomment-723918416
