### ISSUE TITLE
PID: 4828 11-10 16:56:48.082 4828 4828 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference 

### ISSUE THREAD

**Issue by Malloumabba1** [flutter/flutter#70194]
<details>
<summary>Error log</summary>

```

FATAL EXCEPTION: main
11-10 06:25:52.002 13278 13278 E AndroidRuntime: Process: com.google.android.videos, PID: 13278
11-10 06:25:52.002 13278 13278 E AndroidRuntime: java.lang.IllegalArgumentException: There is no GcmTaskService component registered within this package. Have you extended GcmTaskService correctly?
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.gms.common.internal.zzac.zzb(Unknown Source)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.gms.gcm.GcmNetworkManager.zzeu(Unknown Source)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.gms.gcm.GcmNetworkManager.schedule(Unknown Source)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.apps.play.movies.common.service.drm.RefreshLicenseTaskService.forceLicenseRefreshNow(SourceFile:36)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.apps.play.movies.common.service.drm.LicenseRefresherImpl.refreshLicensesWithScheduleCheck(SourceFile:31)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.apps.play.movies.common.service.pinning.PinBroadcastReceiver.startTransferServiceToResumeDownloads(SourceFile:28)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.apps.play.movies.common.VideosGlobals.postStartup(SourceFile:208)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.apps.play.movies.common.VideosGlobals.bridge$lambda$0$VideosGlobals(SourceFile)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.google.android.apps.play.movies.common.VideosGlobals$$Lambda$9.run(Unknown Source)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6293)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
11-10 06:25:52.002 13278 13278 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: FATAL EXCEPTION: main
11-10 16:44:38.381 2852 2852 E AndroidRuntime: Process: com.example.newapp, PID: 2852
11-10 16:44:38.381 2852 2852 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchModule.onAttachedToEngine(BackgroundFetchModule.java:70)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.registerWith(BackgroundFetchPlugin.java:18)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at com.jrshopping.voixtachadi.Application.registerWith(Application.java:21)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:150)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:101)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java:95)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6293)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
11-10 16:44:38.381 2852 2852 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: FATAL EXCEPTION: main
11-10 16:45:23.664 3231 3231 E AndroidRuntime: Process: com.example.newapp, PID: 3231
11-10 16:45:23.664 3231 3231 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchModule.onAttachedToEngine(BackgroundFetchModule.java:70)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.registerWith(BackgroundFetchPlugin.java:18)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at com.jrshopping.voixtachadi.Application.registerWith(Application.java:21)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:150)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:101)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java:95)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6293)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
11-10 16:45:23.664 3231 3231 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: FATAL EXCEPTION: main
11-10 16:46:44.075 3466 3466 E AndroidRuntime: Process: com.example.newapp, PID: 3466
11-10 16:46:44.075 3466 3466 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchModule.onAttachedToEngine(BackgroundFetchModule.java:70)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.registerWith(BackgroundFetchPlugin.java:18)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at com.jrshopping.voixtachadi.Application.registerWith(Application.java:21)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:150)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:101)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java:95)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6293)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
11-10 16:46:44.075 3466 3466 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: FATAL EXCEPTION: main
11-10 16:48:22.998 4086 4086 E AndroidRuntime: Process: com.example.newapp, PID: 4086
11-10 16:48:22.998 4086 4086 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchModule.onAttachedToEngine(BackgroundFetchModule.java:70)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.registerWith(BackgroundFetchPlugin.java:18)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at com.jrshopping.voixtachadi.Application.registerWith(Application.java:21)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:150)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:101)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java:95)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6293)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
11-10 16:48:22.998 4086 4086 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: FATAL EXCEPTION: main
11-10 16:48:39.409 4140 4140 E AndroidRuntime: Process: com.example.newapp, PID: 4140
11-10 16:48:39.409 4140 4140 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchModule.onAttachedToEngine(BackgroundFetchModule.java:70)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.registerWith(BackgroundFetchPlugin.java:18)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at com.jrshopping.voixtachadi.Application.registerWith(Application.java:21)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:150)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:101)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java:95)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6293)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
11-10 16:48:39.409 4140 4140 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: FATAL EXCEPTION: main
11-10 16:56:48.082 4828 4828 E AndroidRuntime: Process: com.example.newapp, PID: 4828
11-10 16:56:48.082 4828 4828 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchModule.onAttachedToEngine(BackgroundFetchModule.java:70)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.registerWith(BackgroundFetchPlugin.java:18)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at com.jrshopping.voixtachadi.Application.registerWith(Application.java:21)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:150)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:101)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java:95)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6293)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
11-10 16:56:48.082 4828 4828 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)

```

</details>

**Comment by darshankawar** [comment]
@Malloumabba1 
Just providing the exception won't help to analyze the issue. Please provide more details such as `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue you are facing.
Thanks.
