### ISSUE TITLE
Flutter build bundle does not work with symlinks on Windows when a directory is listed.

### ISSUE THREAD

**Issue by matthewblain** [flutter/flutter#70269]
## Steps to Reproduce

1. Create (or use) a Flutter application with these attributes:
  - Has an asset in the pubspec specified as a directory.
  - The asset in the specified directory is a symlink to a file elsewhere.
2. On Windows, run *flutter build bundle*.

Result:
 The bundle will fail to build, *Target copy_flutter_bundle failed: FileSystemException: Cannot copy file* ... *(OS Error: The system cannot find the file specified.*
 Note that the same error will occur with *flutter run* or similar.
 The error **does not** occur with *flutter test*.

Example:
 I have created https://github.com/matthewblain/flutter_test_symlink_asset_10nov2020 which reproduces this error. If you look at the commit history (currently at 6 commits), you can see the steps where the tool goes from working to (at the final step) broken.

Important note:
 To have symlinks on Windows, you must enable them in the G
[buildbundlefailure.txt](https://github.com/flutter/flutter/files/5522064/buildbundlefailure.txt)
roup Policy Editor. When using a Git repository, ensure that the Windows policy is set and the Git core.symlinks configuration is true.

## Logs

Here is the output of *flutter build bundle*. I have attached the verbose version as a text file.
```
Font subetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.
Target copy_flutter_bundle failed: FileSystemException: Cannot copy file to
'build\flutter_assets\assets/page_title.txt', path =
'C:\Users\mblain\src\flutter_test_symlink_asset_10nov2020\test_symlink_asset_10nov2020\assets\page_title.txt' (OS Error:
The system cannot find the file specified.
, errno = 2)
Failed to build bundle.
```

```
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18362.1139], locale en-US)
    • Flutter version 1.22.3 at C:\Users\mblain\src\flutter
    • Framework revision 8874f21e79 (12 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\mblain\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available
```

**Comment by matthewblain** [comment]
Update: I tried to set it back to an explicit filename, and it breaks there too! That just means it fails in more scenarios. The repro case should still work as a simple test case.

**Comment by TahaTesser** [comment]
Hi @matthewblain 
Thanks for creating the issue, labelling since I am running Windows 10 home, Will reproduce it tomorrow with Windows 10 pro
Thank you

**Comment by TahaTesser** [comment]
I can finally reproduce it 
<details> 
<summary>logs</summary> 

```bash
PS C:\Users\taha\AndroidStudioProjects\flutter_test_symlink_asset_10nov2020\test_symlink_asset_10nov2020> flutters build bundle -v
[ +108 ms] executing: [C:\Code\flutter_stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8874f21e79d7ec66d0457c7ab338348e31b17f1d
[        ] executing: [C:\Code\flutter_stable/] git tag --points-at HEAD
[  +34 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.3
[   +8 ms] executing: [C:\Code\flutter_stable/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Code\flutter_stable/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +175 ms] executing: [C:\Code\flutter_stable/] git rev-parse --abbrev-ref HEAD
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +166 ms] Generating
C:\Users\taha\AndroidStudioProjects\flutter_test_symlink_asset_10nov2020\test_symlink_asset_10nov2020\android\app\src\ma
in\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +42 ms] Initializing file store
[  +10 ms] Done initializing file store
[  +29 ms] Skipping target: gen_localizations
[ +633 ms] Skipping target: kernel_snapshot
[   +3 ms] copy_flutter_bundle: Starting due to {}
[ +103 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more
information see #56466.
[   +2 ms] Font subetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.
[  +15 ms] Persisting file store
[  +22 ms] Done persisting file store
[   +6 ms] Target copy_flutter_bundle failed: FileSystemException: Cannot copy file to
           'build\flutter_assets\assets/page_title.txt', path =

'C:\Users\taha\AndroidStudioProjects\flutter_test_symlink_asset_10nov2020\test_symlink_asset_10nov2020\assets\page_title
           .txt' (OS Error: The system cannot find the file specified.
           , errno = 2)
[   +8 ms] "flutter bundle" took 1,073ms.
[   +4 ms] Failed to build bundle.
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildWithAssemble (package:flutter_tools/src/bundle.dart:177:5)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #19     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
           #20     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #21     _rootRunBinary (dart:async/zone.dart:1214:47)
           #22     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #23     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #24     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #26     Future._completeError (dart:async/future_impl.dart:537:5)
           #27     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
           #28     CopyFlutterBundle.build (package:flutter_tools/src/build_system/targets/common.dart)
           #29     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #30     _rootRunBinary (dart:async/zone.dart:1214:47)
           #31     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #32     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #33     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #34     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #35     Future._completeError (dart:async/future_impl.dart:537:5)
           #36     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
           #37     copyAssets (package:flutter_tools/src/build_system/targets/assets.dart)
           #38     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #39     _rootRunBinary (dart:async/zone.dart:1214:47)
           #40     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #41     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #42     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #43     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #44     Future._completeError (dart:async/future_impl.dart:537:5)
           #45     Future.wait.<anonymous closure> (dart:async/future.dart:426:23)
           #46     _rootRunUnary (dart:async/zone.dart:1198:47)
           #47     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #48     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #50     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #51     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #52     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #53     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #54     copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart)
           #55     _rootRunUnary (dart:async/zone.dart:1198:47)
           #56     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #57     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #58     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #59     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #60     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #61     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #62     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #63     _run (package:flutter_tools/src/base/error_handling_io.dart)
           #64     _rootRunUnary (dart:async/zone.dart:1198:47)
           #65     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #66     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #67     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #68     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #69     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #70     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #71     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #72     ErrorHandlingFile.writeAsBytes.<anonymous closure>
(package:flutter_tools/src/base/error_handling_io.dart)
           #73     _rootRunUnary (dart:async/zone.dart:1198:47)
           #74     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #75     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #76     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #77     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #78     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #79     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #80     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #81     ForwardingFile.writeAsBytes (package:file/src/forwarding/forwarding_file.dart)
           #82     _rootRunUnary (dart:async/zone.dart:1198:47)
           #83     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #84     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #85     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #86     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #87     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #88     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #89     _rootRun (dart:async/zone.dart:1190:13)
           #90     _CustomZone.run (dart:async/zone.dart:1093:19)
           #91     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #92     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #93     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #94     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #95     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #96     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +205 ms] ensureAnalyticsSent: 199ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
PS C:\Users\taha\AndroidStudioProjects\flutter_test_symlink_asset_10nov2020\test_symlink_asset_10nov2020>
```

</details>


<details> 
<summary> multiple flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.22.3 at C:\Code\flutter_stable
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\Code\flutter_beta
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!
```
```bash
[✓] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.24.0-7.0.pre at C:\Code\flutter_dev
    • Framework revision a0860f6e87 (13 days ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.610]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!
```

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.208, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.24.0-8.0.pre.208 at C:\Code\flutter_master
    • Framework revision 15d2d8a875 (12 hours ago), 2020-11-11 20:04:03 -0500
    • Engine revision d97a81c889
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.610]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!
```

</details>

**Comment by brunobowden** [comment]
FYI @mit-mit, though please note that @TahaTesser is already looking at this. Matthew is a former Google staff engineer and good friend. This reminds me of the earlier symlink issue that @mit-mit was kind enough to fix for us: https://github.com/WorldHealthOrganization/app/issues/779

**Comment by exaby73** [comment]
This issue is still reproducible with `Master (3.9.0-12.0.pre.20)`. Updating labels accordingly

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.9.0-12.0.pre.20, on Microsoft Windows [Version 10.0.22621.1413], locale en-US)
    • Flutter version 3.9.0-12.0.pre.20 on channel master at C:\Users\Nabeel\fvm\versions\master
    ! The flutter binary is not on your path. Consider adding C:\Users\Nabeel\fvm\versions\master\bin to your path.
    ! Warning: `dart` on your path resolves to C:\tools\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at C:\Users\Nabeel\fvm\versions\master. Consider adding C:\Users\Nabeel\fvm\versions\master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e88acfb0e (74 minutes ago), 2023-03-20 22:23:23 -0700
    • Engine revision 2c342a8af9
    • Dart version 3.0.0 (build 3.0.0-348.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Users\Nabeel\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9514443\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33414.496
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Users\Nabeel\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Users\Nabeel\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9514443
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.76.2)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.78

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by JamesHancockAtteria** [comment]
Note that this is also an issue for anyone using Dev Drives on Windows 11 trying to build Windows Flutter projects.  ReFS doesn't support hard links (and never will) so as a result, Windows builds fail.

Given that this is an increasingly standard configuration on Windows for developers because of the significant speed increases, I'd suggest this is a pretty big deal.
