### ISSUE TITLE
[webview_flutter] serving content over HTTPS

### ISSUE THREAD

**Issue by praharshbhatt** [flutter/flutter#70284]
I am trying to implement Stripe checkout in webview, but it throws an error saying the content must be served over https.
This is occurring because Stripe does not allow HTTP servings in the Live keys.
What additional steps do I need to take to make these requests over HTTPS?

## Steps to Reproduce

1. fork the code at https://github.com/MarcinusX/flutter_stripe_demo
2. replace the "stripePublishableKey" with a live stripe publishable key
3. flutter run

## Code:
```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:kinderpass_app/common/common.dart';
import 'package:webview_flutter/webview_flutter.dart';

class StripeCheckoutSession extends StatefulWidget {
  final String listingId, sessionId;

  StripeCheckoutSession(this.listingId, this.sessionId);

  @override
  StripeCheckoutSessionState createState() => StripeCheckoutSessionState();
}

class StripeCheckoutSessionState extends State<StripeCheckoutSession> {
  WebViewController _webViewController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: WebView(
        initialUrl: initialUrl,
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (webViewController) => _webViewController = webViewController,
        onPageFinished: (String url) {
          if (url == initialUrl) {
            _redirectToStripe(widget.sessionId);
          }
        },
        navigationDelegate: (NavigationRequest request) {
          print(request);
          print(request.url);
          if (request.url.startsWith('http://mykinderpass.com') ||
              request.url.startsWith('http://staging.mykinderpass.com') ||
              request.url.startsWith('https://mykinderpass.com') ||
              request.url.startsWith('https://staging.mykinderpass.com')) {
            Navigator.of(context).pop();
            //Navigator.of(context).pushReplacementNamed('/success');
          } else if (request.url.startsWith('http://mykinderpass/cancel')) {
            Navigator.of(context).pop();
            //Navigator.of(context).pushReplacementNamed('/cancel');
          }
          return NavigationDecision.navigate;
        },
      ),
    );
  }

  String get initialUrl => 'data:text/html;base64,${base64Encode(Utf8Encoder().convert(kStripeHtmlPage))}';

  Future<void> _redirectToStripe(String sessionId) async {
    final redirectToCheckoutJs = '''
var stripe = Stripe(\'${AppConfig.stripePublishableKey}\');
    
stripe.redirectToCheckout({
  sessionId: '$sessionId'
}).then(function (result) {
  result.error.message = 'Error'
});
''';

    try {
      await _webViewController.evaluateJavascript(redirectToCheckoutJs);
    } on PlatformException catch (e) {
      if (!e.details.contains('JavaScript execution returned a result of an unsupported type')) {
        rethrow;
      }
    }
  }
}

const String kStripeHtmlPage = '''
<!DOCTYPE html>
<html>
<script src="https://js.stripe.com/v3/"></script>
<head><title>Stripe checkout</title></head>
<body>
Loading, please wait...
</body>
</html>
''';
```

<details>
  <summary>Logs</summary>

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'var stripe = Stripe('<Stripe key>');

stripe.redirectToCheckout({
  sessionId: 'cs_live_a0tCIGOAnW9bEG4L0gNpHHwEvN9Rg22CrV21lYQIvSvn2l7SlhzvBgTKiq'
}).then(function (result) {
  result.error.message = 'Error'
});
'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=IntegrationError: Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/security/guide#tls, WKJavaScriptExceptionColumnNumber=184970, WKJavaScriptExceptionSourceURL=https://js.stripe.com/v3/, NSLocalizedDescription=A JavaScript exception occurred}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:1<…>

This same code works fine in a test key (the error is still thrown, but the payment works), only the live key gives this problem.
```

</details>

**Comment by TahaTesser** [comment]
Hi @praharshbhatt 
Do you have mixed HTTP links? 
Please check https://github.com/flutter/flutter/issues/24975 & https://github.com/flutter/flutter/issues/43595
Unable to test your code sample due to miss code and steps to reproduce e
Thank you

**Comment by praharshbhatt** [comment]
Hi Sorry, I've updated the OP to make my question more clear.
I do not think  #24975 & #43595 are related.

**Comment by TahaTesser** [comment]
Hi @praharshbhatt 
Just tried that example with the latest `webview_flutter: ^1.0.7` and replaced the existing key with my own test API key, not the live key (I don't have access to it yet).

Checkout is working fine  on Android  and iOS 
![Simulator Screen Shot - iPhone 11 - 2020-11-12 at 13 10 31](https://user-images.githubusercontent.com/48603081/98910995-ee5d3d80-24e9-11eb-83f2-41a4641b3d35.png)



Can you please reproduce the issue with the test key instead of the live key with complete `flutter run --verbose` logs? 

Thank you

**Comment by praharshbhatt** [comment]
Hi @TahaTesser 
Thanks for reaching back.

The issue will not be replicated in the test key, since Stripe allows HTTP calls in the test key.

Anyways, this is the output of flutter run --verbose with the test key:

```
] I/flutter (22675): {listing: 1596, quantity: 1, slot_id: 13571, user_id: 1272, listing_type: 1, success_path: http://mykinderpass.com/success}
[+3287 ms] I/flutter (22675): Created order: {
[   +1 ms] I/flutter (22675):     "message": "Operation Successful", 
[        ] I/flutter (22675):     "responseData": {
[        ] I/flutter (22675):         "isIndian": false, 
[        ] I/flutter (22675):         "order_id": "cs_test_a0q6oiA3OiBv4WfF8AWOb52uncVoLTsEzRMgujx6FYzF28Kb9CeKc9vHUi"
[        ] I/flutter (22675):     }, 
[        ] I/flutter (22675):     "success": true
[        ] I/flutter (22675): }
[ +104 ms] E/eglCodecCommon(22675): glUtilsParamSize: unknow param 0x000088ef
[   +1 ms] E/eglCodecCommon(22675): glUtilsParamSize: unknow param 0x000088ef
[        ] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 8 (8) 0 0
[  +91 ms] D/EGL_emulation(22675): eglMakeCurrent: 0xe451ba40: ver 3 0 (tinfo 0xca780b80)
[+2172 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 1 (1) 0 0
[+1882 ms] E/eglCodecCommon(22675): glUtilsParamSize: unknow param 0x000088ef
[        ] E/eglCodecCommon(22675): glUtilsParamSize: unknow param 0x000088ef
[        ] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 9 (9) 0 0
[  +72 ms] I/chromium(22675): [INFO:CONSOLE(1)] "You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS.", source:
https://js.stripe.com/v3/ (1)
[  +27 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 1 (1) 0 0
[ +869 ms] I/flutter (22675): NavigationRequest(url:
https://checkout.stripe.com/pay/cs_test_a0q6oiA3OiBv4WfF8AWOb52uncVoLTsEzRMgujx6FYzF28Kb9CeKc9vHUi#fidkdWxOYHwnPyd1blpxYHZxWmNUf2JgbUppMV80Vk5oYXNXVFJSZ3w1UicpJ2hs
YXYnP34nYnBsYSc%2FJ0tEJyknaHBsYSc%2FJ0tEJykndmxhJz8nS0QneCknZ2BxZHYnP15YKSdpZHxqcHFRfHVgJz8ndmxrYmlgWmxxYGgnKSdga2RnaWBVaWRmYG1qaWFgd3YnP2NkaXZgKSd3YGNgd3dgd0p3bGJ
sayc%2Fa3BpaXgl, isForMainFrame: true)
[   +1 ms] I/flutter (22675):
https://checkout.stripe.com/pay/cs_test_a0q6oiA3OiBv4WfF8AWOb52uncVoLTsEzRMgujx6FYzF28Kb9CeKc9vHUi#fidkdWxOYHwnPyd1blpxYHZxWmNUf2JgbUppMV80Vk5oYXNXVFJSZ3w1UicpJ2hs
YXYnP34nYnBsYSc%2FJ0tEJyknaHBsYSc%2FJ0tEJykndmxhJz8nS0QneCknZ2BxZHYnP15YKSdpZHxqcHFRfHVgJz8ndmxrYmlgWmxxYGgnKSdga2RnaWBVaWRmYG1qaWFgd3YnP2NkaXZgKSd3YGNgd3dgd0p3bGJ
sayc%2Fa3BpaXgl
[+1528 ms] E/eglCodecCommon(22675): glUtilsParamSize: unknow param 0x000088ef
[   +4 ms] E/eglCodecCommon(22675): glUtilsParamSize: unknow param 0x000088ef
[   +1 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 10 (10) 0 0
[  +28 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 8 (8) 0 0
[  +48 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 0 (0) 0 0
[+4596 ms] D/EGL_emulation(22675): eglMakeCurrent: 0xb7344b20: ver 3 0 (tinfo 0xc9170df0)
[   +1 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 1 (1) 0 0
[ +654 ms] I/Choreographer(22675): Skipped 33 frames!  The application may be doing too much work on its main thread.
[+2332 ms] I/chromium(22675): [INFO:CONSOLE(240)] "Uncaught ReferenceError: PaymentRequest is not defined", source: https://pay.google.com/gp/p/js/pay.js (240)
[  +76 ms] I/chromium(22675): [INFO:CONSOLE(1)] "Unrecognized payment-request-google-pay-inner.html parameter: betas is not a recognized parameter. This may cause
issues with your integration in the future.", source: https://js.stripe.com/v3/fingerprinted/js/controller-49cd88218d0923c5dd3141dda2e18b9f.js (1)
[   +9 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 0 (0) 16 2
[        ] E/InputMethodManager(22675): b/117267690: Failed to get fallback IMM with expected displayId=628 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{f5dcbd8 VFEDHVC.. .F...... 0,0-1080,1794}
[  +26 ms] I/flutter (22675): NavigationRequest(url: https://staging.mykinderpass.comhttp//mykinderpass.com/success?payment_success=false, isForMainFrame: true)
[   +1 ms] I/flutter (22675): https://staging.mykinderpass.comhttp//mykinderpass.com/success?payment_success=false
[   +4 ms] D/EGL_emulation(22675): eglMakeCurrent: 0xe451ba40: ver 3 0 (tinfo 0xca780b80)
[   +8 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 2 (2) 16 13
[   +4 ms] W/FA      (22675): setCurrentScreen cannot be called with the same class and name
[+1115 ms] E/InputMethodManager(22675): b/117267690: Failed to get fallback IMM with expected displayId=628 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{f5dcbd8 VFEDHVC.. ........ 0,0-1080,1794}
[   +7 ms] D/EGL_emulation(22675): eglMakeCurrent: 0xe451ba40: ver 3 0 (tinfo 0xca780b80)
[        ] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 10 (10) 24 0
[   +4 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 1 (1) 0 20
[  +51 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 10 (10) 24 0
[  +27 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 0 (0) 0 0
[+1741 ms] D/EGL_emulation(22675): eglMakeCurrent: 0xb7344b20: ver 3 0 (tinfo 0xc9170df0)
[   +1 ms] D/eglCodecCommon(22675): setVertexArrayObject: set vao to 1 (1) 0 20
[+1346 ms] I/flutter (22675): unhandled element metadata; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#96ccf(), name:
"assets/rewards_cover_green.svg", colorFilter: null)

```

**Comment by TahaTesser** [comment]
Hi @praharshbhatt 

> The issue will not be replicated in the test key, since Stripe allows HTTP calls in the test key.

So this is different issue with the test key?

```
[+2643 ms] W/ConnectionTracker(23746): Exception thrown while unbinding
[   +2 ms] W/ConnectionTracker(23746): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzji@b16e696
[   +2 ms] W/ConnectionTracker(23746):  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)
[   +1 ms] W/ConnectionTracker(23746):  at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
[   +2 ms] W/ConnectionTracker(23746):  at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
[   +5 ms] W/ConnectionTracker(23746):  at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
[   +1 ms] W/ConnectionTracker(23746):  at
com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
[   +2 ms] W/ConnectionTracker(23746):  at com.google.android.gms.measurement.internal.zzio.zzag(com.google.android.gms:play-services-measurement-impl@@17.6.0:245)
[   +2 ms] W/ConnectionTracker(23746):  at com.google.android.gms.measurement.internal.zzio.zzal(com.google.android.gms:play-services-measurement-impl@@17.6.0:262)
[   +4 ms] W/ConnectionTracker(23746):  at com.google.android.gms.measurement.internal.zzio.zzc(com.google.android.gms:play-services-measurement-impl@@17.6.0:336)
[   +2 ms] W/ConnectionTracker(23746):  at com.google.android.gms.measurement.internal.zzir.zza(com.google.android.gms:play-services-measurement-impl@@17.6.0:2)
[   +2 ms] W/ConnectionTracker(23746):  at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.6.0:7)
[   +2 ms] W/ConnectionTracker(23746):  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
[   +2 ms] W/ConnectionTracker(23746):  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[   +3 ms] W/ConnectionTracker(23746):  at com.google.android.gms.measurement.internal.zzfs.run(com.google.android.gms:play-services-measurement-impl@@17.6.0:21)
[+16862 ms] I/flutter (23746): {listing: 15897, quantity: 1, slot_id: 61193, user_id: 12741, listing_type: 1, success_path: http://mykinderpass.com/success}
[+4337 ms] I/flutter (23746): Created order: {"responseData": {"order_id": "cs_live_a0tu6pYXxmelgAjsSDHVI1Skx4WX4xbSxLNulexpLs1ftcLfZGoDHmzxLD", "isIndian":
false}, "message": "Operation Successful", "success": true}
```
I had no issues with the test key as mentioned https://github.com/flutter/flutter/issues/70284#issuecomment-725904762 with the latest  webview and I used this https://github.com/MarcinusX/flutter_stripe_demo 

Can you please clarify these issues with test key and live key
Thank yu

**Comment by praharshbhatt** [comment]
With the test key, the webpage loads since Stripe allows you to load HTTP / mixed content when working with test keys. While using a live key, it needs an https connection or it'll throw an error. In the test key, it throws the error, but also loads the webpage. whereas if it is a live key, it does not load the webpage while throwing the error.
While contacting the stripe support, the team asked me to make sure the webview that I am using connects over https rather than HTTP, which I'm not very sure how to do. That's my question.

**Comment by TahaTesser** [comment]
Hi @praharshbhatt 
Have tried hybrid composition? https://pub.dev/packages/webview_flutter#using-hybrid-composition.

**Comment by praharshbhatt** [comment]
Yes, Still face the same issue.

**Comment by praharshbhatt** [comment]
Any updates

**Comment by praharshbhatt** [comment]
I hosted the HTML on GitHub pages and passed the URL in the initialUrl field, Now everything works fine.

**Comment by kamleshwebtech** [comment]
I am facing the same issue. It was working well in Stripe's testing mode but when I changed it to live by using LIVE credentials. It returns me error in vs code console panel like '"Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/ " any suggestion, what is the issue and how can we fix it? Thanks a lot.

**Comment by praharshbhatt** [comment]
@kamleshwebtech I finally hosted the html page in github pages. This way, I am getting response from a https source, instead of serving the HTML locally.
