### ISSUE TITLE
Google maps plugin error, Failed to handle method call

### ISSUE THREAD

**Issue by giorgi-abashidze** [flutter/flutter#70296]
App crashing on google map load

release apk only debug is working well 

`2020-11-11 20:44:58.995 25431-25431/? E/MethodChannel#flutter/platform_views: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at io.flutter.plugins.googlemaps.e.s(Unknown Source:10)
        at io.flutter.plugins.googlemaps.g.a(Unknown Source:28)
        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(Unknown Source:116)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:423)
        at android.app.Dialog.show(Dialog.java:317)
        at android.app.Presentation.show(Presentation.java:259)
        at io.flutter.plugin.platform.l.<init>(Unknown Source:55)
        at io.flutter.plugin.platform.l.a(Unknown Source:65)
        at io.flutter.plugin.platform.k$a.g(Unknown Source:110)
        at io.flutter.embedding.engine.i.i$a.b(Unknown Source:152)
        at io.flutter.embedding.engine.i.i$a.G(Unknown Source:144)
        at g.a.d.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.d(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:182)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-11-11 20:44:58.997 25431-25491/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at io.flutter.plugins.googlemaps.e.s(Unknown Source:10)
        at io.flutter.plugins.googlemaps.g.a(Unknown Source:28)
        at io.flutter.plugin.platform.SingleViewPresentation.onCreate(Unknown Source:116)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:423)
        at android.app.Dialog.show(Dialog.java:317)
        at android.app.Presentation.show(Presentation.java:259)
        at io.flutter.plugin.platform.l.<init>(Unknown Source:55)
        at io.flutter.plugin.platform.l.a(Unknown Source:65)
        at io.flutter.plugin.platform.k$a.g(Unknown Source:110)
        at io.flutter.embedding.engine.i.i$a.b(Unknown Source:152)
        at io.flutter.embedding.engine.i.i$a.G(Unknown Source:144)
        at g.a.d.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.d(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:182)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
    )
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
    <asynchronous suspension>
    #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039)
    <asynchronous suspension>
    #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:749)
    <asynchronous suspension>
    #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174)`

**Comment by GamalSebaee** [comment]
@giorgi-abashidze  Are you solved this bug ?
this happened with me and I can't solve it.
