### ISSUE TITLE
App crashes on s9+ after release to app store with  dlopen: failed: permission denied

### ISSUE THREAD

**Issue by jameshp** [flutter/flutter#70307]
My app in the app store fails to start on Samsung S9+ devices with following error, i have not (yet) seen this on other devices. 

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{{{my.custom.bundle.id}}/{{my.custom.bundle.id}}.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/{{my.custom.bundle.id}}-1/split_config.arm64_v8a.apk!/lib/arm64-v8a/libflutter.so" segment 2: Permission denied
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)`
```

I shipped the app through a app bundle, where everything looks good, libflutter is available.  
<img width="1440" alt="Screenshot 2020-11-11 at 19 04 27" src="https://user-images.githubusercontent.com/3824083/98847778-1056b180-2451-11eb-8b84-85f931abac98.png">

Further i checked on google play and downloaded the apk that is generated for S9+ devices, which is a Signed, Universal APK. 
Looking into the content of the apk, also this looks fine from a lib folder perspective. 
<img width="1440" alt="Screenshot 2020-11-11 at 19 04 27" src="https://user-images.githubusercontent.com/3824083/98850053-785ac700-2454-11eb-9810-3ab52a68f2f5.png">

Now, this might all also be related to the workaround described here: 
https://flutter.dev/docs/deployment/android#building-the-app-for-release ([issuetracker
](https://issuetracker.google.com/issues/147096055)
But as it was specifically mentioned for android 6 (and the S9 crashed on Android 9) i wanted to bring this up. 

Also, this discussion on the AndroidNDK section seems to go in the direction, that android.bundle.enableUncompressedNativeLibs=false could fix the problem. 

As I have no S9+ to test it's hard to reproduced controlled. 
Not sure, if this is a flutter related bug or more on bundle build settings. 
Any hints are welcome. 

And here my flutter doctor of the machine where i built the .aab file

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/michaelpolt/development/flutter
    • Framework revision 84f3d28555 (4 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/michaelpolt/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/michaelpolt/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone (mobile) • b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7 • ios • iOS
      14.1
    ! Error: iPhone 6s dev is not connected. Xcode will continue when iPhone 6s
      dev is connected. (code -13)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will
      continue when iPhone is finished. (code -10)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @jameshp 
Can you please provide, your `pubspec.yaml`, the list of affected devices, and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by jameshp** [comment]
Hi, 
here is my pubspec.yaml (as txt) file
[pubspec.txt](https://github.com/flutter/flutter/files/5533078/pubspec.txt)

Affected devices: 
Samsung S9+ (star2qltesq) 
Interestingly it seems only one or 2 users are affected... out of 60installs
<img width="1440" alt="Screenshot 2020-11-12 at 21 20 20" src="https://user-images.githubusercontent.com/3824083/98992030-f38fac00-252c-11eb-9aaf-19385a0567e1.png">

Pixel 3a (sargo)
<img width="1440" alt="Screenshot 2020-11-12 at 21 42 33" src="https://user-images.githubusercontent.com/3824083/98994604-59316780-2530-11eb-864e-d362bfd06ca6.png">

Here a bit more detailes stacktrace, maybe of help (from google play console)
```java 
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3086)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3229)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1926)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
Caused by: java.lang.RuntimeException: 
  at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java:284)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:160)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:16)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine (FlutterActivityAndFragmentDelegate.java:110)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:7)
  at io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:22)
  at android.app.Activity.performCreate (Activity.java:7326)
  at android.app.Activity.performCreate (Activity.java:7317)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1271)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3066)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3229)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1926)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
Caused by: java.util.concurrent.ExecutionException: 
  at java.util.concurrent.FutureTask.report (FutureTask.java:123)
  at java.util.concurrent.FutureTask.get (FutureTask.java:193)
  at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java:23)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:160)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java:16)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine (FlutterActivityAndFragmentDelegate.java:110)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:7)
  at io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:22)
  at android.app.Activity.performCreate (Activity.java:7326)
  at android.app.Activity.performCreate (Activity.java:7317)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1271)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3066)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3229)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1926)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6981)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
Caused by: java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1016)
  at java.lang.System.loadLibrary (System.java:1669)
  at io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java:20)
  at io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
```


I just see the issue on customer apps, could not yet reproduce it on my devices. 
I'll try with a simulator to reproduce and let you know on updates. 

Otherwise I have also seen a few other crashes with 
tgkill on SamsungS7 devices: 
Samsung S7 Edge (hero2qltevzw)
Samsung S7 Edge (hero2qlteatt)
Samsung S7 (heroqltevzw)

with a very limited stack trace (bundle id anonymised) 
`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> {{my.bundle.id}} <<<

backtrace:
  #00  pc 000000000006b97c  /system/lib64/libc.so (tgkill+8)
  #00  pc 000000000001e060  /system/lib64/libc.so (abort+88)
  #00  pc 000000000001f350  /data/app/{{my.bundle.id}}-**X-_D-FAHavoURkmrBMg2Yw**==/split_config.arm64_v8a.apk (offset 0x1069000)
`
The stack trace is exactly the same for all three devices, besides the **hash**(or whatever, outlined bold) after the {{my.bunlde.id}}

<img width="1440" alt="Screenshot 2020-11-12 at 21 57 32" src="https://user-images.githubusercontent.com/3824083/98995750-18d2e900-2532-11eb-8987-993324dce6fd.png">

**Comment by jameshp** [comment]
ok, can't reproduce as release builds are not for simulators, and on my other testdevices the app works fine.

**Comment by TahaTesser** [comment]
Hi @jameshp 
This is one of the common crashes from the google play console. please look at these https://github.com/flutter/flutter/issues/68484 https://github.com/flutter/flutter/issues/23055.
I don't think this is specific to Flutter itself, please check this comment https://github.com/flutter/flutter/issues/64697#issuecomment-683007555
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you
