### ISSUE TITLE
Using absolute URI for web crashes dart compiler if it is a linux style path

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#70305]
example code:
```
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/widgets.dart';
import '/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart';

void main() =>
  runApp(
    const Center(
      child:
        Text('Hello, world!',
          key: Key('title'),
          textDirection: TextDirection.ltr
        )
      )
    );
```

```
Error: Invalid package URI 'package:/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart':
  Invalid argument (packageUri): Package URIs must not start with a '/': Instance of '_Uri'.
lib/main.dart:6:8: Error: Not found: 'package:/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart'
import '/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart';
       ^                                                                
Unhandled exception:                                                    
Invalid argument (packageUri): Package URIs must not start with a '/': Instance of '_Uri'
#0      checkValidPackageUri (package:package_config/src/util.dart:71:5)
#1      SimplePackageConfig.resolve (package:package_config/src/package_config_impl.dart:131:23)
#2      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:159:45)
<asynchronous suspension>                                               
#3      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:628:5)
<asynchronous suspension>                                               
#4      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:541:9)
<asynchronous suspension>                                               
#5      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1100:11)
<asynchronous suspension>                                               
the Dart compiler exited unexpectedly.      
```

**Comment by jonahwilliams** [comment]
@annagrin

**Comment by annagrin** [comment]
hmm it looks like `strongComponents.moduleAssignment` contains a malformed moduleUri `package:/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart`. I am not sure what causes it, need to investigate.

**Comment by darshankawar** [comment]
@annagrin @jonahwilliams Hi,

I ran the use case mentioned in original description as-is using latest stable which compiled and built properly without any issues on mobile and web:

```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           25.4s
Debug service listening on ws://127.0.0.1:53218/G0NHFOLcBEg=/ws
Syncing files to device iPhone 12 Pro...
```

<img width="200" alt="Screenshot 2022-03-02 at 6 23 16 PM" src="https://user-images.githubusercontent.com/67046386/156365280-9dd97496-333b-4b21-94df-5ba6b35b2d7e.png">

Can this be closed or need to be kept open ?

`Channel stable, 2.10.2`
