### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY - something with title

### ISSUE THREAD

**Issue by Horum-dev** [flutter/flutter#70339]
```
I/flutter (12288): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12288): The following assertion was thrown building WidgetsApp-[GlobalObjectKey
I/flutter (12288): _MaterialAppState#bf807](dirty, state: _WidgetsAppState#4c30d):
I/flutter (12288): 'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null &&
I/flutter (12288): color.alpha == 0xFF': is not true.
I/flutter (12288): 
I/flutter (12288): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12288): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12288): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12288):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12288): 
I/flutter (12288): The relevant error-causing widget was:
I/flutter (12288):   MaterialApp file:///Users/roman/Desktop/Roman/Clouded%20projects/NewApp/new_app/lib/main.dart:124:12
I/flutter (12288): 
I/flutter (12288): When the exception was thrown, this was the stack:
I/flutter (12288): #2      new Title (package:flutter/src/widgets/title.dart:24:15)
I/flutter (12288): #3      _WidgetsAppState.build (package:flutter/src/widgets/app.dart:1606:15)
I/flutter (12288): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4792:27)
I/flutter (12288): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:15)
I/flutter (12288): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4847:11)
I/flutter (12288): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4369:5)
I/flutter (12288): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4654:5)
I/flutter (12288): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4838:11)
I/flutter (12288): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
I/flutter (12288): ...     Normal element mounting (27 frames)
I/flutter (12288): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
I/flutter (12288): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3380:18)
I/flutter (12288): #39     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1215:16)
I/flutter (12288): #40     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1186:5)
I/flutter (12288): #41     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1128:18)
I/flutter (12288): #42     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:19)
I/flutter (12288): #43     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1127:13)
I/flutter (12288): #44     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:967:7)
I/flutter (12288): #45     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:948:7)
I/flutter (12288): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (12288): 
I/flutter (12288): ════════════════════════════════════════════════════════════════════════════════════════════════════


<img width="340" alt="Снимок экрана 2020-11-12 в 04 09 24" src="https://user-images.githubusercontent.com/67152395/98882225-dc08e280-249c-11eb-995b-57ac19e564d3.png">

```

**Comment by darshankawar** [comment]
@Horum-dev 
Check if [this](https://stackoverflow.com/questions/61813780/failed-assertion-line-24-pos-15-color-null-color-alpha-0xff-is-not) solves your issue.
If issue persists, please provide `flutter doctor -v` and minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by Horum-dev** [comment]
Unfortunately the problem still appears...

code
`class MyAppi extends StatelessWidget {
  Color backColor = new Color.fromRGBO(36, 37, 54,1);
  Color buttonColor = new Color.fromRGBO(207, 128, 0,1);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'main one',
      theme: ThemeData(
        primaryColor: buttonColor,
        backgroundColor: backColor,
        textTheme: Theme.of(context)
            .textTheme
            .apply(bodyColor: new Color.fromRGBO(0, 0, 0,1)),
      ),
      home: Scaffold(
        appBar: AppBar(

            //title: Text('lol'),

            ),
        body: Center(
          child: Container(
            child: Image.asset('images/smog.png'),
          ),
        ),
      ),
    );
    // TODO: implement build
    throw UnimplementedError();
  }
}`

`flutter doctor -v
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale ru-RU)
    • Flutter version 1.23.0-18.1.pre at /Users/roman/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/roman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)`

**Comment by TahaTesser** [comment]
Hi @Horum-dev 
Using your code sample has no issues on the beta channel

<img width="849" alt="Screenshot 2020-11-17 at 5 35 46 PM" src="https://user-images.githubusercontent.com/48603081/99388417-8e0c3880-28fb-11eb-988a-7b0b9358a093.png">


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  Color backColor = new Color.fromRGBO(36, 37, 54, 1);
  Color buttonColor = new Color.fromRGBO(207, 128, 0, 1);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'main one',
      theme: ThemeData(
        primaryColor: buttonColor,
        backgroundColor: backColor,
        textTheme: Theme.of(context)
            .textTheme
            .apply(bodyColor: new Color.fromRGBO(0, 0, 0, 1)),
      ),
      home: Scaffold(
        appBar: AppBar(
            // title: Text('lol'),
            ),
        body: Center(
          child: Container(
            child: Image.network('https://i.imgur.com/QCNbOAo.png'),
          ),
        ),
      ),
    );
    // TODO: implement build
    throw UnimplementedError();
  }
}

```

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on macOS 11.0.1 20B29 x86_64, locale
    en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 198df796aa (5 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)        • EUYTFEUSQSRGDA6D • android-arm64  • Android 10
      (API 29)
    • sdk gphone x86 (mobile) • emulator-5554    • android-x86    • Android 11
      (API 30) (emulator)
    • Web Server (web)        • web-server       • web-javascript • Flutter Tools
    • Chrome (web)            • chrome           • web-javascript • Google Chrome
      86.0.4240.198

• No issues found!

```

</details>
