### ISSUE TITLE
[Web] fail to export image from canvas that drawed Image

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#70352]
## Steps to Reproduce
run this at web
```
import 'dart:ui' as ui;

Uint8List createImage(){
    final recorder = new ui.PictureRecorder();
    final canvas = new Canvas(
        recorder,
        new Rect.fromPoints(
            new Offset(0.0, 0.0), new Offset(400, 400)));

    canvas.drawImage(await decodeImageFromList((await rootBundle.load("sample.png")).buffer.asUint8List()), Offset(0,0), Paint());

    final picture = recorder.endRecording();

    print("start to Image");
    final img = await picture.toImage(canvasSize.width.toInt(), canvasSize.height.toInt());
    print("end to Image");
    final pngBytes = await img.toByteData(format: ImageByteFormat.png);
    return Uint8List.view(pngBytes.buffer);
}
```

**Expected results:**
funtion will be success and return Uint8List Image

**Actual results:**
`final img = await picture.toImage(canvasSize.width.toInt(), canvasSize.height.toInt());`
will be crashed

output
```
start to Image
Error: Expected a value of type 'String', but got one of type 'TypeErrorImpl'
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:4339:11)
    at Object.castError (http://localhost:5000/dart_sdk.js:4310:15)
    at Object.cast [as as] (http://localhost:5000/dart_sdk.js:4626:17)
    at dart.LegacyType.new.as (http://localhost:5000/dart_sdk.js:6195:60)
    at http://localhost:5000/packages/mangaplotter/main.dart.lib.js:685:36
    at Object._rootRunBinary (http://localhost:5000/dart_sdk.js:38007:14)
    at _RootZone.runBinary (http://localhost:5000/dart_sdk.js:37539:20)
    at http://localhost:5000/dart_sdk.js:38144:20
    at async._CustomZone.new.handleUncaughtError (http://localhost:5000/dart_sdk.js:37134:14)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:32992:30)
    at _Future.new.[_completeError] (http://localhost:5000/dart_sdk.js:32943:23)
    at http://localhost:5000/dart_sdk.js:32981:31
    at _rootRun (http://localhost:5000/dart_sdk.js:37979:14)
    at async._CustomZone.new.run (http://localhost:5000/dart_sdk.js:37149:14)
    at async._CustomZone.new.runGuarded (http://localhost:5000/dart_sdk.js:37049:14)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:37103:33)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37794:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37800:13)
    at http://localhost:5000/dart_sdk.js:33309:9
```

$ flutter doctor -v
```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.18363.1198], locale ja-JP)
    • Flutter version 1.23.0-18.1.pre at C:\src\flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\hatadev\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\hatadev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.193
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!
```

**Comment by darshankawar** [comment]
@hatano0x06 
There are below similar issues that describes your case:

https://github.com/flutter/flutter/issues/42767
https://github.com/flutter/flutter/issues/49857

See [this](https://github.com/flutter/flutter/issues/57853) original issue that was closed in favor of above issues.
Closing this as duplicate.
