### ISSUE TITLE
EXCEPTION CAUGHT BY GESTURE LIBRARY

### ISSUE THREAD

**Issue by Karambir-Sheoran** [flutter/flutter#70371]
```
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons ==
kPrimaryButton': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:379:12)
#3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:310:7)
#4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#5      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#7      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#8      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#9      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#13     _invoke1 (dart:ui/hooks.dart:267:10)
#14     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
(elided 5 frames from class _AssertionError and dart:async)

Event:
  PointerUpEvent#9257e(position: Offset(266.6, 363.2))
Target:
  <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons == kPrimaryButton': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:379:12)
#3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:310:7)
#4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#5      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
...
Event: PointerUpEvent#9257e(position: Offset(266.6, 363.2))
  position: Offset(266.6, 363.2)
Target: <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 409 pos 12: '_initialButtons == kPrimaryButton': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
```

**Comment by darshankawar** [comment]
@Karambir-Sheoran 
Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows this issue ?

**Comment by darshankawar** [comment]
Similar to [36350](https://github.com/flutter/flutter/issues/36350)

**Comment by wanderingGuy** [comment]
Similar issue here,
Flutter version: 1.12.13+hotfix.7

```
11-16 15:10:36.539 I/flutter (24124): -'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 415 pos 12: '_initialButtons == kPrimaryButton': is not true.
11-16 15:10:36.539 I/flutter (24124): -#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
11-16 15:10:36.539 I/flutter (24124): -#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
11-16 15:10:36.539 I/flutter (24124): -#2      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:415:12)
11-16 15:10:36.539 I/flutter (24124): -#3      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:356:9)
11-16 15:10:36.539 I/flutter (24124): -#4      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:336:9)
11-16 15:10:36.539 I/flutter (24124): -#5      DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:365:5)
11-16 15:10:36.539 I/flutter (24124): -#6      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:7)
11-16 15:10:36.539 I/flutter (24124): -#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
11-16 15:10:36.539 I/flutter (24124): -#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
11-16 15:10:36.539 I/flutter (24124): -#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
11-16 15:10:36.539 I/flutter (24124): -#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
11-16 15:10:36.539 I/flutter (24124): -#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
11-16 15:10:36.539 I/flutter (24124): -#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
11-16 15:10:36.539 I/flutter (24124): -#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
11-16 15:10:36.539 I/flutter (24124): -#14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
11-16 15:10:36.539 I/flutter (24124): -#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
11-16 15:10:36.539 I/flutter (24124): -#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
11-16 15:10:36.539 I/flutter (24124): -#17     _rootRunUnary (dart:async/zone.dart:1138:13)
11-16 15:10:36.539 I/flutter (24124): -#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
11-16 15:10:36.539 I/flutter (24124): -#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
11-16 15:10:36.539 I/flutter (24124): -#20     _invoke1 (dart:ui/hooks.dart:287:10)
11-16 15:10:36.539 I/flutter (24124): -#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
11-16 15:10:36.539 I/flutter (24124): -
```

**Comment by marcellocamara** [comment]
I face this problem here. Flutter (Channel stable, 1.22.4, on Microsoft Windows [versão 10.0.18363.1198], locale pt-BR)

```
════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
The following _CastError was thrown while dispatching a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:321:60)
#1      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#2      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
#3      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
#4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
...
Event: PointerUpEvent#8ccd7(position: Offset(190.5, 166.8))
  position: Offset(190.5, 166.8)
Target: <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@6393b6f[MainActivity]( 2551): ViewPostIme pointer 0

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@6393b6f[MainActivity]( 2551): ViewPostIme pointer 1
D/ViewRootImpl@6393b6f[MainActivity]( 2551): ViewPostIme pointer 0

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@6393b6f[MainActivity]( 2551): ViewPostIme pointer 1
```

**Comment by TahaTesser** [comment]
@wanderingGuy 
`Flutter version: 1.12.13+hotfix.7` is too old, please upgrade to latest stable, if the problem persists, please file a new issue 

Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
