### ISSUE TITLE
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#70399]
i see this issue repeating for some of the devices using latest flutter version

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{kw.ltd.barcodeproapp/kw.ltd.barcodeproapp.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/base.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/base.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.en.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.mdpi.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.x86.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/lib/x86, /data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/base.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/base.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.en.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.mdpi.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.x86.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Caused by java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/base.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/base.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.en.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.mdpi.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.x86.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/lib/x86, /data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/base.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/base.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.en.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.mdpi.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.x86.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"

Caused by java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/base.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/base.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.en.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.mdpi.apk", zip file "/data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.x86.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/lib/x86, /data/app/androidx.test.tools.crawler-222PoK5dVtOFMVleJEO2cw==/base.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/base.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.en.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.mdpi.apk!/lib/x86, /data/app/kw.ltd.barcodeproapp-N8i1mKue9FBtr_8qbyUZXg==/split_config.x86.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libflutter.so"
       at java.util.concurrent.FutureTask.report(FutureTask.java:123)
       at java.util.concurrent.FutureTask.get(FutureTask.java:193)
       at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:178)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:289)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:192)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:234)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:154)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
       at android.app.Activity.performCreate(Activity.java:7136)
       at android.app.Activity.performCreate(Activity.java:7127)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

![image](https://user-images.githubusercontent.com/47334522/98983864-166c9100-252a-11eb-9c9a-5d254bcff119.png)

**Comment by TahaTesser** [comment]
Hi @kw2019ltd 
This is not specific to Flutter
Please check these issue  https://github.com/flutter/flutter/issues/64697 
Explanation https://github.com/flutter/flutter/issues/64697#issuecomment-683007555
Closing. If you disagree, please write in the comments and I will reopen it.
Thank you
