### ISSUE TITLE
Mac external_ui_integration_test_ios failing to get a numeric value during speed test

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#70416]
https://ci.chromium.org/p/flutter/builders/prod/Mac%20external_ui_integration_test_ios/6

```
[external_ui_integration_test_ios] [STDOUT] stdout: [+8077 ms] flutter: Stopping .5x speed test...
[external_ui_integration_test_ios] [STDOUT] stdout: [ +280 ms] 00:22 [32m+0[0m[31m -1[0m: texture suite texture rendering [1m[31m[E][0m[0m
[external_ui_integration_test_ios] [STDOUT] stdout: [   +1 ms]   Expected: a numeric value within <5.0> of <29.85>
[external_ui_integration_test_ios] [STDOUT] stdout: [        ]     Actual: <0.0>
[external_ui_integration_test_ios] [STDOUT] stdout: [        ]      Which:  differs by <29.85>
[external_ui_integration_test_ios] [STDOUT] stdout: [   +6 ms]   package:test_api                 expect
[external_ui_integration_test_ios] [STDOUT] stdout: [        ]   test_driver/main_test.dart 48:7  main.<fn>.<fn>
[external_ui_integration_test_ios] [STDOUT] stdout: [        ] 00:22 [32m+0[0m[31m -1[0m: texture suite (tearDownAll)[0m
[external_ui_integration_test_ios] [STDOUT] stdout: [  +23 ms] 00:22 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
[external_ui_integration_test_ios] [STDOUT] stdout: [  +82 ms] executing: /opt/s/w/ir/k/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --id 4e131215b69d6679703d698c2418e1e3ddcdf8c6 --uninstall_only --bundle_id io.flutter.externalUi
[external_ui_integration_test_ios] [STDOUT] stdout: [        ] ios-deploy exited with code 0
[external_ui_integration_test_ios] [STDOUT] stdout: [  +45 ms] [....] Waiting for iOS device to be connected
[external_ui_integration_test_ios] [STDOUT] stdout: [  +36 ms] [....] Using 4e131215b69d6679703d698c2418e1e3ddcdf8c6 (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'iPhone'.
[external_ui_integration_test_ios] [STDOUT] stdout: [        ] ------ Uninstall phase ------
[external_ui_integration_test_ios] [STDOUT] stdout: [ +304 ms] [ OK ] Uninstalled package with bundle id io.flutter.externalUi
[external_ui_integration_test_ios] [STDOUT] stdout: [  +95 ms] "flutter drive" took 114,775ms.
[external_ui_integration_test_ios] [STDOUT] stderr: [   +3 ms] 
[external_ui_integration_test_ios] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[external_ui_integration_test_ios] [STDOUT] stderr:            #1      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:258:7)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1079:12)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:934:27)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:270:9)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:220:5)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr:            #16     main (package:flutter_tools/executable.dart:90:3)
[external_ui_integration_test_ios] [STDOUT] stderr:            <asynchronous suspension>
[external_ui_integration_test_ios] [STDOUT] stderr: 
[external_ui_integration_test_ios] [STDOUT] stderr: 
[external_ui_integration_test_ios] [STDOUT] stdout: [   +1 ms] ensureAnalyticsSent: 0ms
[external_ui_integration_test_ios] [STDOUT] stdout: [   +1 ms] Running shutdown hooks
[external_ui_integration_test_ios] [STDOUT] stdout: [        ] Shutdown hooks complete
[external_ui_integration_test_ios] [STDOUT] stdout: [        ] exiting with code 1
[external_ui_integration_test_ios] [STDOUT] "/opt/s/w/ir/k/flutter/bin/flutter" exit code: 1
[external_ui_integration_test_ios] [STDERR] Task failed: Executable "/opt/s/w/ir/k/flutter/bin/flutter" failed with exit code 1.
```

**Comment by jmagman** [comment]
There's a flake reported at https://github.com/flutter/flutter/issues/66150 with the same `<29.85>` difference, hmm.

**Comment by godofredoc** [comment]
This is not happening anymore. Closing this issue.
