### ISSUE TITLE
Mac flutter_view_ios__start_up error building for device, Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#70422]
https://ci.chromium.org/p/flutter/builders/prod/Mac%20flutter_view_ios__start_up/5

```
[flutter_view_ios__start_up] [STDOUT] stdout: [  +17 ms] "flutter ios" took 53,396ms.
[flutter_view_ios__start_up] [STDOUT] stdout: [   +1 ms] ensureAnalyticsSent: 0ms
[flutter_view_ios__start_up] [STDOUT] stdout: [   +1 ms] Running shutdown hooks
[flutter_view_ios__start_up] [STDOUT] stdout: [        ] Shutdown hooks complete
[flutter_view_ios__start_up] [STDOUT] stdout: [        ] exiting with code 1
[flutter_view_ios__start_up] [STDOUT] stderr: [   +3 ms] Encountered error while building for device.
[flutter_view_ios__start_up] [STDOUT] stderr: [        ] 
[flutter_view_ios__start_up] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[flutter_view_ios__start_up] [STDOUT] stderr:            #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:255:7)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1079:12)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:934:27)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:264:9)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:220:5)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr:            #16     main (package:flutter_tools/executable.dart:90:3)
[flutter_view_ios__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_view_ios__start_up] [STDOUT] stderr: 
[flutter_view_ios__start_up] [STDOUT] stderr: 
[flutter_view_ios__start_up] [STDOUT] "/opt/s/w/ir/k/flutter/bin/flutter" exit code: 1
```

**Comment by jmagman** [comment]
```
♦ codesign --force --verbose --sign A5CFF7959BD4B17F97127C518E8504F2D9562490 -- /opt/s/w/ir/k/flutter/examples/flutter_view/build/ios/Profile-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter
[flutter_view_ios__start_up] [STDOUT] stdout:                /opt/s/w/ir/k/flutter/examples/flutter_view/build/ios/Profile-iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter: signed bundle with Mach-O universal (armv7 x86_64 arm64) [io.flutter.flutter]
[flutter_view_ios__start_up] [STDOUT] stdout:                error: Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".
```

**Comment by jmagman** [comment]
There was an issue for this but I can't find it now.

**Comment by pedromassangocode** [comment]
I found similar log messages while triaging https://github.com/flutter/flutter/issues/71366!

**Comment by Hesamedin** [comment]
This helped me: https://stackoverflow.com/a/64951775/513413

**Comment by godofredoc** [comment]
This is not happening anymore. Closing this issue.

**Comment by jmagman** [comment]
Reopening, this is still being observed.

**Comment by LRNZ09** [comment]
Cleaning the build folder from Xcode resolved the issue for me.

**Comment by pedromassangocode** [comment]
Facing this today. Deleting /ios folder and running `flutter create .` didn't worked around.

```console
               sent 638 bytes  received 20 bytes  1316.00 bytes/sec
               total size is 38734939  speedup is 58867.69
               error: Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".


[  +13 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 11 Pro Max.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:559:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>


[  +14 ms] "flutter run" took 31,039ms.

```

**Comment by jmagman** [comment]
I've seen this occasionally, too, it's really annoying.  My guess is that Xcode is parallelizing the steps and this runs right before its Info.plist processing.  PR at https://github.com/flutter/flutter/pull/78085.

**Comment by jmagman** [comment]
The fix for this is currently available in the master channel.  You can work around this on other channels:
1. Navigate to your Runner target Build Phases in Xcode
2. Expand `Thin Binary`.  Comment out the script:
```bash
# /bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
```
3. Build your app in Xcode
4. Restore the script.
```bash
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" embed_and_thin
```
Note, if you don't restore the script then Flutter won't be embedded in your app.

**Comment by wmingcr** [comment]
> I found similar log message (shared in [#70422 (comment)](https://github.com/flutter/flutter/issues/70422#issuecomment-726434999)) while triaging #71366!

Thanks, it also worked for me

**Comment by abayomiAkanji** [comment]
https://github.com/flutter/flutter/issues/70422#issuecomment-814336760

In my case, checking `For install builds only` fixed the issue.

**Comment by jmagman** [comment]
> In my case, checking `For install builds only` fixed the issue.

That "fix" turns off embedding the Flutter framework and your compiled dart code into your app.  So don't do that.
