### ISSUE TITLE
Problems with Samsung J4, J6

### ISSUE THREAD

**Issue by ElaineSchwner** [flutter/flutter#70468]
Hello,

I have some Flutter applications, everything works fine in every device, but Samsung
Users have complained about the app not getting any data when connected on wifi. 

I bought a Samsung J6, just for testing, and I installed one of my apps from the play Store and it was completely blank. After 3 minutes, just staring the screen, the data showed.

I think the problem is it takes a long time to get wi-fi connection from Samsung.

One detail: this device only connects in wi-fi 2.4ghz

With the debub app and completely connected in wi-fi,  we get this:

```
W/Firestore(32621): (21.3.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore(32621): 
W/Firestore(32621): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```

After 3 minutes, it finally shows data.

I put the installed apk for debugger and I think this verbose may be important:

<details> 
<summary>logs</summary> 

```bash
2020-11-13 13:59:38.721 28883-25297/? W/NetworkScheduler: Error inserting flex_time=3534000 job_id=-1 period=7069000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=203915000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1605286778713 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067]) [CONTEXT service_id=218 ]
```

</details

I get the following erros from the published app:

<details> 
<summary>logs</summary> 

```bash
2020-11-13 13:54:09.753 3300-3534/? E/NetdEventListenerService: handleMessage: { when=0 what=10001 obj=com.android.server.connectivity.NetdEventListenerService$DnsResultParams@c36a3bb target=com.android.server.connectivity.NetdEventListenerService$DnsEventHandler }
2020-11-13 13:54:12.569 3816-5647/? E/#IMSCR: 11-13 13:54:12 0x12060000:N,REFR:0
2020-11-13 13:54:12.605 3816-5647/? E/#IMSCR: 11-13 13:54:12 0x12060001:N,REFR:FOUND:0
2020-11-13 13:54:12.898 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:12.898 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0  mTagName : SurfaceFlinger 
2020-11-13 13:54:12.900 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:12.901 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:13.414 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:13.414 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1  mTagName : SurfaceFlinger 
2020-11-13 13:54:13.414 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:13.414 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:14.415 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:14.415 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU  , mTagName : SurfaceFlinger 
2020-11-13 13:54:14.416 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU() 
2020-11-13 13:54:14.417 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:14.577 22613-22613/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-11-13 13:54:14.578 22613-22613/? E/Zygote: accessInfo : 1
2020-11-13 13:54:14.595 22613-22613/? E/d.mobileservic: Not starting debugger since process cannot load the jdwp agent.
2020-11-13 13:54:14.817 22632-22632/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-11-13 13:54:14.818 22632-22632/? E/Zygote: accessInfo : 1
2020-11-13 13:54:14.827 22632-22632/? E/android:drmSer: Not starting debugger since process cannot load the jdwp agent.
2020-11-13 13:54:14.989 22613-22613/? E/SEMS:DataAdapterLog_11.1.0: [SEMS][2][GroupDBHelper] Instance null
2020-11-13 13:54:17.905 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:17.905 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0  mTagName : SurfaceFlinger 
2020-11-13 13:54:17.908 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:17.908 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:18.420 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:18.421 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1  mTagName : SurfaceFlinger 
2020-11-13 13:54:18.422 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:18.422 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:19.423 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:19.423 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU  , mTagName : SurfaceFlinger 
2020-11-13 13:54:19.425 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU() 
2020-11-13 13:54:19.425 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:22.894 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:22.894 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0  mTagName : SurfaceFlinger 
2020-11-13 13:54:22.896 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:22.896 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:23.410 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:23.410 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1  mTagName : SurfaceFlinger 
2020-11-13 13:54:23.411 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:23.411 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:24.412 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:24.412 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU  , mTagName : SurfaceFlinger 
2020-11-13 13:54:24.414 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU() 
2020-11-13 13:54:24.414 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:27.901 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:27.901 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0  mTagName : SurfaceFlinger 
2020-11-13 13:54:27.903 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:27.903 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:28.417 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:28.417 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1  mTagName : SurfaceFlinger 
2020-11-13 13:54:28.417 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:28.417 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:29.418 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:29.418 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU  , mTagName : SurfaceFlinger 
2020-11-13 13:54:29.420 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU() 
2020-11-13 13:54:29.420 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:30.855 3300-3324/? E/Watchdog: !@Sync 198 [2020-11-13 13:54:30.855] FD count : 520, wdog_way : softdog
2020-11-13 13:54:32.907 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:32.907 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0  mTagName : SurfaceFlinger 
2020-11-13 13:54:32.910 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:32.910 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:33.423 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:33.423 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1  mTagName : SurfaceFlinger 
2020-11-13 13:54:33.425 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:33.425 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:34.426 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:34.426 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU  , mTagName : SurfaceFlinger 
2020-11-13 13:54:34.428 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU() 
2020-11-13 13:54:34.428 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:34.729 7825-22606/? E/InternalPeopleServiceGrpcClient: Error making Grpc request.
    clxm: DEADLINE_EXCEEDED: deadline exceeded after 24.969990846s. [buffered_nanos=24970205597, waiting_for_connection]
        at clxl.c(:com.google.android.gms@203915035@20.39.15 (120306-335085812):3)
        at snn.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):65)
        at apeo.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):34)
        at apeq.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):18)
        at aper.run(:com.google.android.gms@203915035@20.39.15 (120306-335085812):2)
        at java.lang.Thread.run(Thread.java:919)
2020-11-13 13:54:34.729 7825-22606/? E/FSA2_GroupSyncGrpc: getGroups() failed
    clxm: DEADLINE_EXCEEDED: deadline exceeded after 24.969990846s. [buffered_nanos=24970205597, waiting_for_connection]
        at clxl.c(:com.google.android.gms@203915035@20.39.15 (120306-335085812):3)
        at snn.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):65)
        at apeo.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):34)
        at apeq.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):18)
        at aper.run(:com.google.android.gms@203915035@20.39.15 (120306-335085812):2)
        at java.lang.Thread.run(Thread.java:919)
2020-11-13 13:54:37.897 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:37.897 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0  mTagName : SurfaceFlinger 
2020-11-13 13:54:37.899 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2020-11-13 13:54:37.899 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:38.413 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
```

</details>

After 3 minutes blank, finally the content appears from nothing.

**Comment by ElaineSchwner** [comment]
I oppened the same code but instead of app - Flutter web - with the same device - and it opens instanstly.

So the problem is with the app.

**Comment by ElaineSchwner** [comment]
There is this error:

2020-11-13 14:57:22.263 14098-14115/com.oneplanet.historiasparadormir E/MediaHTTPConnection: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.URLConnection java.net.URL.openConnection()' on a null object reference
        at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:256)
        at android.media.MediaHTTPConnection.getMIMEType(MediaHTTPConnection.java:475)
        at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:159)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
2020-11-13 14:57:22.265 14098-14115/com.oneplanet.historiasparadormir E/MediaHTTPConnection: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.URLConnection java.net.URL.openConnection()' on a null object reference
        at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:256)
        at android.media.MediaHTTPConnection.getSize(MediaHTTPConnection.java:461)
        at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:151)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)

**Comment by ElaineSchwner** [comment]
I found it is something related to Firebase, because I installed other app that uses SQL database, and it worked.

**Comment by iapicca** [comment]
@ElaineSchwner 
if it's a firebase related problem I recommend to open an issue [here](https://github.com/FirebaseExtended/flutterfire/issues)
otherwise could you provide your `flutter doctor -v`, 
your `pubspec.yaml` 
and a minimal reproducible code sample (w/o 3rd party plugins)

**Comment by TahaTesser** [comment]
Hi @ElaineSchwner 
This seems an issue related to Firebase, I see you've opened an issue there as well  https://github.com/FirebaseExtended/flutterfire/issues/4121
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you
