### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, path = '/Users/winninggreat/.pub-cache/hosted/pub.dartlang.org/flutter_template_images-1.0.0/lib/' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by JohnOyekanmi** [flutter/flutter#70483]
## Command
```
flutter create app
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Exists failed, path = '/Users/winninggreat/.pub-cache/hosted/pub.dartlang.org/flutter_template_images-1.0.0/lib/' (OS Error: Permission denied, errno = 13)
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:101:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#2      _templateImageDirectory (package:flutter_tools/src/template.dart:253:79)
#3      Template.fromName (package:flutter_tools/src/template.dart:63:38)
#4      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:629:46)
#5      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:543:29)
#6      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:380:37)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#15     FlutterProject.organizationNames (package:flutter_tools/src/project.dart)
#16     _rootRunUnary (dart:async/zone.dart:1192:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G103, locale en-NG)
    • Flutter version 1.17.5 at /Users/Jbraz/dev/flutter
    • Framework revision 8af6b2f038 (5 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Jbraz/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ! CocoaPods 1.5.2 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment]
@JohnOyekanmi 
your flutter version is super outdated
the issue should have been already fixed [here](https://github.com/flutter/flutter/pull/63540)

**Comment by pedromassangocode** [comment]
See https://github.com/flutter/flutter/issues/70483#issuecomment-727223758 and make sure you update Flutter by running the commands bellow:
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persist plea write a comment bellow and I will reopen this issue.
Thank you
