### ISSUE TITLE
Ubuntu AndroidStudio flutter: JAVA_HOME is not set

### ISSUE THREAD

**Issue by moneer-muntazah** [flutter/flutter#70497]
I'm having a problem running my flutter application in android studio. 

It gives me the following message 

```
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Exception: Gradle task assembleDebug failed with exit code 1
```

Here is `echo $JAVA_HOME` and I have added the bin to my PATH

```
/usr/lib/jvm/openjdk-14.0.2_linux-x64_bin/jdk-14.0.2

```

I can run flutter from terminal via `flutter run` after upgrading gradle from `gradle-5.6.2-all.zip` to `gradle-6.3-all.zip` 

I think the problem lies in android/gradlew in the following script

```sh
# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi
```

I tried copying it and running it and it runs with no problems with `#!/usr/bin/env bash` which is the shebang in gradlew

I tried reinstalling android studio, but it didn't work. My `flutter doctor --verbose` is a mess. At first it couldn't find android studio- said it is not installed. so I ran `flutter config --android-studio-dir="/snap/bin"` but now I get this output even though I have the plugins installed

```
:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = /snap/bin
    ✗ Unable to find bundled Java version.
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
:~$ flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

```

Thank you all hopefully I'm missing something simple!

**Comment by moneer-muntazah** [comment]
Here is `flutter doctor` with the `--verbose` flag

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /opt/flutter_linux_1.20.4-stable/flutter
    • Framework revision 1aafb3a8b9 (5 hours ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/moneer/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at:
      /usr/lib/jvm/openjdk-14.0.2_linux-x64_bin/jdk-14.0.2/bin/java
    • Java version OpenJDK Runtime Environment (build 14.0.2+12-46)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[!] Android Studio
    • Android Studio at /snap/bin
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = /snap/bin
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by iapicca** [comment]
@moneer-muntazah   seems like you are using open 14 instead of 8

here is the easy part
```bash
sudo apt-get remove --auto-remove openjdk*
sudo apt-get install openjdk-8-jre
gedit ~/bashrc
```
make sure that your path looks like this

```console
export PATH="$PATH:/snap/bin/flutter/bin"
export PATH="$PATH:/usr/bin/java"
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
export ANDROID_SDK_ROOT=/home/<YOUR USER NAME>/Android/Sdk
```

then run 
```bash
source ~/bashrc
flutter docrtor -v
```

here comes the bad news...

you might have trouble to get android studio recognized 
https://github.com/canonical/flutter-snap/issues/16

**Comment by iapicca** [comment]
@moneer-muntazah 

sorry... my bad

to fix android studio just run 
`flutter config --android-studio-dir=/snap/android-studio/current/android-studio`

**Comment by omidraha** [comment]
After upgrading to Android studio 4.1.1, I had a couple of  [issues](https://github.com/aissat/easy_localization/issues/275) and fixed by:

```bash

$ flutter upgrade
$ flutter config --android-studio-dir="/path/to/android/studio/"

$ vim ~/.bashrc
export JAVA_HOME="/path/to/android/studio/jre/"

$ vim pubspec.yaml
dependency_overrides:
   intl: ^0.17.0-nullsafety.2

```

**Comment by flutterq** [comment]
All Possible Working Solution Added Here [[Solved] ERROR: JAVA_HOME is not set and no ‘java’ command could be found in your flutter PATH. in flutter](https://fluttercorner.com/solved-error-java_home-is-not-set-and-no-java-command-could-be-found-in-your-flutter-path-in-flutter/)
