### ISSUE TITLE
Intl.select "other" case requirement inconsistency

### ISSUE THREAD

**Issue by koral--** [flutter/flutter#70556]
Docs at https://api.flutter.dev/flutter/intl/Intl/select.html says:
> We look up the value of choice in cases and return the result, or an empty string if it is not found.

However in fact the following exception is thrown when value not matching any case is passed:

```
Invalid argument(s): The 'other' case must be specified
When the exception was thrown, this was the stack: 
#0      Intl.selectLogic (package:intl/intl.dart:552:7)
#1      Intl._select (package:intl/intl.dart:533:26)
#2      Intl.select (package:intl/intl.dart:517:12)
```

Code reproducing this issue:
```dart
print(Intl.select(
      'foo',
      {
        'bar': 'bar',
        'baz': 'baz',
      },
      args: ['foo'],
    ));
```

```
$ flutter --version
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (2 weeks ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3
```

**Comment by TahaTesser** [comment]
Hi @koral-- 
This ist just documentation in flutter docs, for errors, please file a new issue on `intl` [repository](https://github.com/dart-lang/intl/issues)
I will label this for documentation 
Thank you

**Comment by koral--** [comment]
My intent was to first try here to determine where exactly the problem is located:

**Comment by koral--** [comment]
According to the https://github.com/dart-lang/intl/issues/343#issuecomment-1284998469 it's a bug in the documentation.

**Comment by AbdeMohlbi** [comment]
The linked issue and the PR that contains the fix have been merged so this is considered fixed, feel free to open a new issue with more details if you think that's not the case
