### ISSUE TITLE
[tool_crash] FileSystemException: writeFrom failed, OS Error: Illegal byte sequence, errno = 92

### ISSUE THREAD

**Issue by johnareid54** [flutter/flutter#70570]
Not sure if it is FLutter or my MacBook causing the problem!
flutter create nov15
```
MacUsers-iMac:~ john$ cd desktop
MacUsers-iMac:desktop john$ flutter create nov15
Creating project nov15...
  nov15/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  nov15/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  nov15/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  (created)
  nov15/ios/Runner/Info.plist (created)

Oops; flutter has exited unexpectedly: "FileSystemException: writeFrom failed,
path = '/Users/john/Desktop/nov15/ios/Runner/Info.plist' (OS Error: Illegal byte
sequence, errno = 92)".
 
Could not write crash report to disk: FileSystemException: writeFrom failed,
path =
'/var/folders/l5/2wxcdwsx6w31rq_vxz09gtv40000gp/T/flutter_tools.uzUg27/flutter_0
1.log' (OS Error: Illegal byte sequence, errno = 92)

## Logs
FileSystemException: writeFrom failed, OS Error: Illegal byte sequence, errno = 92
```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:606:14)
#2      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#3      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:148:16)
#4      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:253:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_io.dart:486:14)
#6      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:252:5)
#7      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:264:30)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#9      Template.render (package:flutter_tools/src/template.dart:195:24)
#10     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:791:21)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#19     Template.fromName (package:flutter_tools/src/template.dart)
#20     _rootRunUnary (dart:async/zone.dart:1198:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
```
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.6 19G73 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-18.1.pre at
      /Users/john/Documents/flutterCode/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/john/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /Users/john/Library/Android/sdk/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Users/john/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      86.0.4240.193

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by johnareid54** [comment]
I think it is my Macbook, the SSD needed repairing!

It just did not seems like a drive fault.
