### ISSUE TITLE
[tool_crash] when passing /? as positional argument to flutter create

### ISSUE THREAD

**Issue by raminrahimzada** [flutter/flutter#70616]
## Command
I think this is not a big issue<br/>

```
flutter create /?
```

## Steps to Reproduce
As usually i do with other cli apps ,  gave flutter create  /? command  to see the parameters of new project creation and then , i think flutter accepted /? as project name and tried to create files/folders with that name, so this crash occured. Would be great if you fix it, 
thanks

## Logs
FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#2      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#3      CreateCommand._getProjectType (package:flutter_tools/src/commands/create.dart:260:22)
#4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:359:41)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#12     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
```
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
    • Flutter version 1.20.4 at D:\FLUTTER\flutter
    • Framework revision fba99f6cf9 (9 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\ANDROID_SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = D:\ANDROID_SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jonahwilliams** [comment]
I actually added some work arounds to support -? as a help command, we could add support for /? easily enough. c.f. https://github.com/flutter/flutter/blob/ce318b7b539e228b806f81b3fa7b33793c2a2685/packages/flutter_tools/lib/executable.dart#L68

PRs welcome!
