### ISSUE TITLE
BottomSheet has nullable animationController but uses it as non-null

### ISSUE THREAD

**Issue by rami-a** [flutter/flutter#70614]
Created from b/173042655, the bottom sheet widget throws exceptions if used without an animationController, even though this property is nullable.

## Steps to Reproduce

1. Create an app with a `BottomSheet` as the child, something like:

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: BottomSheet(
          onClosing: (){},
          builder: (context) {
            return Container(
              color: Colors.orange,
              height: 100,
              width: 100,
            );
          },
        ),
      ),
    );
  }
```

2. Perform drag gesture on the bottom sheet
3. See exception thrown:

```
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _BottomSheetState._dismissUnderway (package:flutter/src/material/bottom_sheet.dart:194:58)
#1      _BottomSheetState._handleDragUpdate (package:flutter/src/material/bottom_sheet.dart:204:9)
#2      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:431:55)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#4      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:431:7)
```

**Expected results:** No exception or enforce a non-null animation controller

**Actual results:** Exception occurs

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.252, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-US)
    • Flutter version 1.24.0-8.0.pre.252 at /Users/<user>/Development/flutter
    • Framework revision bf2c9dfc05 (35 hours ago), 2020-11-14 22:38:02 -0500
    • Engine revision 3e77d854a7
    • Dart version 2.12.0 (build 2.12.0-45.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/raboughanem/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 8 (mobile) • 1CDE6067-6A37-4B9F-861F-D3316A9AB34B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS (desktop)   • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101 darwin-x64
    • Web Server (web)  • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```

</details>

**Comment by pedromassango** [comment]
Working on this!

**Comment by jhass** [comment]
Seeing this a lot in production too.

**Comment by emri99** [comment]
I experiment the same issue using DraggableScrollable widget when closing the bottom sheet with a quick swipe down.

I haven't succeeded to catch this error to avoid reporting false positive crash logs 😕 

If anyone has a hint to catch this error while this issue is resolved, it would be greatly appreciated 🙏 


<details>
<summary><b>Stacktrace</b></summary>
<p>

````
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while finalizing the widget tree:
flutter: ScrollableState#4dd03(tickers: tracking 3 tickers, position:
flutter: _DraggableScrollableSheetScrollPosition#4d3bb(offset: -61.9, range: -1.0..453.4, viewport: 79.6,
flutter: ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, null,
flutter: ScrollDirection.forward), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics)
flutter: was disposed with an active Ticker.
flutter: ScrollableState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was
flutter: called on the mixin, that Ticker was still active. All Tickers must be disposed before calling
flutter: super.dispose().
flutter: Tickers used by AnimationControllers should be disposed by calling dispose() on the
flutter: AnimationController itself. Otherwise, the ticker will leak.
flutter: The offending ticker was:
flutter:   _WidgetTicker(created by ScrollableState#4dd03(tickers: tracking 1 ticker, position:

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
ScrollableState#4dd03(tickers: tracking 3 tickers, position: _DraggableScrollableSheetScrollPosition#4d3bb(offset: -61.9, range: -1.0..453.4, viewport: 79.6, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, null, ScrollDirection.forward), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics) was disposed with an active Ticker.

ScrollableState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by ScrollableState#4dd03(tickers: tracking 1 ticker, position: _DraggableScrollableSheetScrollPosition#4d3bb(offset: -81.2, range: 0.0..464.3, viewport: 68.7, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, BallisticScrollActivity#6034d(AnimationController#ee085(▶ -81.244; for BallisticScrollActivity)), ScrollDirection.forward), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics))
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:271:81)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:202:34)
#4      new AnimationController.unbounded (package:flutter/src/animation/animation_controller.dart:280:21)
#5      _DraggableScrollableSheetScrollPosition.goBallistic (package:flutter/src/widgets/draggable_scrollable_sheet.dart:480:73)
#6      BallisticScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:549:14)
#7      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:593:15)
#8      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:104:11)
#9      ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:533:7)
#10     _DraggableScrollableSheetScrollPosition.applyContentDimensions (package:flutter/src/widgets/draggable_scrollable_sheet.dart:442:18)
#11     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1487:20)
#12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636:7)
#13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
#14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#23     _invoke (dart:ui/hooks.dart:163:10)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#25     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)

When the exception was thrown, this was the stack: 
#0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:219:13)
#1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:237:6)
#2      RestorationMixin.dispose (package:flutter/src/widgets/restoration.dart:1080:11)
#3      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:512:11)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4800:11)
...
====================================================================================================
flutter:   _DraggableScrollableSheetScrollPosition#4d3bb(offset: -81.2, range: 0.0..464.3, viewport: 68.7,
flutter:   ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics,
flutter:   BallisticScrollActivity#6034d(AnimationController#ee085(▶ -81.244; for BallisticScrollActivity)),
flutter:   ScrollDirection.forward), effective physics: BouncingScrollPhysics ->
flutter:   RangeMaintainingScrollPhysics))
flutter:   The stack trace when the _WidgetTicker was actually created was:
flutter:   #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
flutter:   #1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
flutter:   #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:271:81)
flutter:   #3      TickerProviderStateMixin.createTicker
flutter:   (package:flutter/src/widgets/ticker_provider.dart:202:34)
flutter:   #4      new AnimationController.unbounded
flutter:   (package:flutter/src/animation/animation_controller.dart:280:21)
flutter:   #5      _DraggableScrollableSheetScrollPosition.goBallistic
flutter:   (package:flutter/src/widgets/draggable_scrollable_sheet.dart:480:73)
flutter:   #6      BallisticScrollActivity.applyNewDimensions
flutter:   (package:flutter/src/widgets/scroll_activity.dart:549:14)
flutter:   #7      ScrollPosition.applyNewDimensions
flutter:   (package:flutter/src/widgets/scroll_position.dart:593:15)
flutter:   #8      ScrollPositionWithSingleContext.applyNewDimensions
flutter:   (package:flutter/src/widgets/scroll_position_with_single_context.dart:104:11)
flutter:   #9      ScrollPosition.applyContentDimensions
flutter:   (package:flutter/src/widgets/scroll_position.dart:533:7)
flutter:   #10     _DraggableScrollableSheetScrollPosition.applyContentDimensions
flutter:   (package:flutter/src/widgets/draggable_scrollable_sheet.dart:442:18)
flutter:   #11     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1487:20)
flutter:   #12     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636:7)
flutter:   #13     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
flutter:   #14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
flutter:   #15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
flutter:   #16     RendererBinding._handlePersistentFrameCallback
flutter:   (package:flutter/src/rendering/binding.dart:328:5)
flutter:   #17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter:   #18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
flutter:   #19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
flutter:   #23     _invoke (dart:ui/hooks.dart:163:10)
flutter:   #24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
flutter:   #25     _drawFrame (dart:ui/hooks.dart:126:31)
flutter:   (elided 3 frames from dart:async)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:219:13)
flutter: #1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:237:6)
flutter: #2      RestorationMixin.dispose (package:flutter/src/widgets/restoration.dart:1080:11)
flutter: #3      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:512:11)
flutter: #4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1847:13)
flutter: #6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #19     _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:71:14)
flutter: #20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #25     _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:71:14)
flutter: #26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #61     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #73     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #76     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #79     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
flutter: #80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
flutter: #86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
flutter: #87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
flutter: #88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
````

</p>
</details>

<details>
<summary><b>Flutter doctor</b></summary>
<p>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.3 20E232 darwin-x64, locale fr-FR)
    • Flutter version 2.2.3 at /Users/emri/fvm/versions/2.2.3
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/emri/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/emri/Library/Android/sdk
    • Java binary at: /Users/emri/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/emri/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554                        • android-x64 • Android 5.0.2 (API 21) (emulator)
    • iPhone 8 (mobile)                     • 8B8431FD-913A-4194-9BF6-DF392A862789 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)

• No issues found!
```
</p>
</details>

**Comment by markusaksli-nc** [comment]
@goderbauer Is this still relevant with the updated assert messages? Maybe this should assert in the constructor as well to make sure `animationController != null || !enableDrag`

**Comment by nate-thegrate** [comment]
I ran the above snippet on [DartPad](https://dartpad.dev/?id=0d85dbe5ad5a3b43a4ae2a95434b1b6c) recently, and the error message looks to be much more descriptive now:

```
Assertion failed:
file:///opt/flutter/packages/flutter/lib/src/material/bottom_sheet.dart:278:7
(widget.enableDrag || (widget.showDragHandle ?? false)) && widget.animationController != null
"'BottomSheet.animationController' cannot be null when
'BottomSheet.enableDrag' or 'BottomSheet.showDragHandle' is true.
Use 'BottomSheet.createAnimationController' to create one, or
provide another AnimationController."
```
