### ISSUE TITLE
Big Sur - ios not Installing and Launching... Could not run build/ios/iphoneos/Runner.app

### ISSUE THREAD

**Issue by edwinludik** [flutter/flutter#70660]
## Steps to Reproduce

1. install macOS Big Sur (Version 11.0.1 (20B29))
2. Terminal: `flutter create bigsur`
3. open with VS Code and create blank Launch Config
4. Launch: Android (Physical Device) -> **Works** 
5. Launch: iOS (Physical Device- iPhone 6-64Gb, OS: 12.4.8) -> **Fails**
```
Launching lib/main.dart on Dev iPhone in debug mode...
lib/main.dart:1
Signing iOS app for device deployment using developer identity: "Apple Development: Ed (xxxxxx)"
Xcode build done.                                           60.5s
Could not run build/ios/iphoneos/Runner.app on xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Dev iPhone.
Exited (sigterm)
```

6. Terminal: `open ios/Runner.xcworkspace`  (xCode Version 12.2 (12B45b))
7. "Build and then run the current schema" -> **Fails**
Requires a development Team, Set development Team and run again. -> **Works** 
8. Close xCode and return to VS Code and Launch -> **Fails**
```
Launching lib/main.dart on Dev iPhone in debug mode...
lib/main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxxx
Xcode build done.                                           25.4s
Could not run build/ios/iphoneos/Runner.app on 82863c379c7c3eb86e4a5d5c2efcbb72998e56e6.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Dev iPhone.
Exited (sigterm)
```

9.  Open in Android Studio, and test Android Build. -> **Works** 
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: com.intellij.marketplace, org.jetbrains.kotlin, Dart, io.flutter

10. Build for iOS in Android Studio -> **Fails**
```
Launching lib/main.dart on Dev iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxx
Running Xcode build...
Xcode build done.                                           37.4s
Installing and launching...
Could not run build/ios/iphoneos/Runner.app on 82863c379c7c3eb86e4a5d5c2efcbb72998e56e6.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Dev iPhone.
``` 

**Expected results:** 
The same result as Android, and when Building the app from xCode.
The ios App should build and launch on the iPhone (With Hot Reload)

**Actual results:** 
I am not able to deploy to my iOS device.
```
Launching lib/main.dart on Dev iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxx
Running Xcode build...
Xcode build done.                                           37.4s
Installing and launching...
Could not run build/ios/iphoneos/Runner.app on 82863c379c7c3eb86e4a5d5c2efcbb72998e56e6.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Dev iPhone.
```
** What I have tried **
- `flutter clean`
- Unpairing iPhone, and re-trusting the device
- Uninstalling and re-installing cocoapods
- flutter main and flutter dev channels, same result
- Building over the Network (in xClode)

<details>
  <summary>Logs</summary>

```
bigsur % flutter analyze
Analyzing bigsur...                                                     
No issues found! (ran in 11.6s)
```

Note: The flutter and dart plugins are installed on Android Studio. 
```
 % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/ed/development/flutter
    • Framework revision 1aafb3a8b9 (3 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ed/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM T535 (mobile)    • 9fe912e2                                 •
      android-arm • Android 9 (API 28)
    • Dev iPhone (mobile) • 82863c379c7c3eb86e4a5d5c2efcbb72998e56e6 • ios
      • iOS 12.4.8

! Doctor found issues in 1 category.
```

```

[   +5 ms] [ 70%] VerifyingApplication
[  +69 ms] [ 75%] CreatingContainer
[  +12 ms] [ 80%] InstallingApplication
[  +16 ms] [ 85%] PostflightingApplication
[   +3 ms] [ 90%] SandboxingApplication
[  +22 ms] [ 95%] GeneratingApplicationMap
[ +114 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +318 ms] ------ Debug phase ------
[        ] Starting debug of 82863c379c7c3eb86e4a5d5c2efcbb72998e56e6 (N61AP, iPhone 6 (GSM), iphoneos, arm64) a.k.a. 'Dev iPhone' connected through USB...
[+1987 ms] [  0%] Looking up developer disk image
[  +28 ms] [ 95%] Developer disk image mounted successfully
[ +334 ms] Could not run build/ios/iphoneos/Runner.app on 82863c379c7c3eb86e4a5d5c2efcbb72998e56e6.
[   +2 ms] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 6.5s)
[        ] Error launching application on Dev iPhone.
[   +4 ms] "flutter run" took 57,843ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +100 ms] ensureAnalyticsSent: 99ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

**Comment by TahaTesser** [comment]
Hi @edwinludik 
Following all the steps, have no such issues on iOS 14.2
To confirm, it is OS version-specific, can you please try another iPhone if possible with a different version of iOS ex 13 or 14 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (4 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (2 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios • iOS
      14.2
    • iPhone 12 (mobile)     • B46BCEDD-9601-4CD0-8D0B-CE4EF96ACD93 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by edwinludik** [comment]
Good day @TahaTesser ,

I doubt the Target phone is the problem since it is working in XCode. It was working before I upgraded to Big Sur.

I just tried with an iPhone 7 Plus (Model 1661, 1784, 1785, 1786), (iOS 13.7 (17H35))

1. I first did an XCode build -> **Works**
2. But when using VSCode -> **Fails**

```
Launching lib/main.dart on Wife’s iPhone in debug mode...
lib/main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxxxxxxx
Xcode build done.                                           21.5s
Could not run build/ios/iphoneos/Runner.app on 9e80dde88a3417ff67ef85d79905b7429bad693b.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Wife’s iPhone.
Exited (sigterm)
```

**Comment by TahaTesser** [comment]
I’m unable to reproduce the issue to pinpoint the cause by running the same OS. The issue needs further investigation.

**Comment by edwinludik** [comment]
@TahaTesser thank you for checking. I also had problems updating some other software. 
I then decided to reinstall macOS, and it is **working** now!

Followed the instructions here:
[How to reinstall macOS](https://support.apple.com/en-us/HT204904)
