### ISSUE TITLE
Adding survicate.js library causes random crashes in flutter web

### ISSUE THREAD

**Issue by miszmaniac** [flutter/flutter#70688]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update file index.html as follows: 
```
  <script>
    (function (w) {
      var s = document.createElement('script');
      s.src = 'https://survey.survicate.com/workspaces/TOKEN_FOR_SURVEY/web_surveys.js';
      s.async = true;
      var e = document.getElementsByTagName('script')[0];
      e.parentNode.insertBefore(s, e);
    })(window);

    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
```
I can share this survey token privately (but anyone can create free trial there).
3. After running `flutter run -d Chrome` and refreshing page in this new instance of Chrome sometimes flutter app doesn't load. For me it looks like a race condition between loading this new script that I've attached and some flutter callback for initial loading of new script. This happens only with 'run command'.

```══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown building Theme(ThemeData#0a1bf, dirty):
TypeError: Cannot read property 'IconTheme' of undefined

The relevant error-causing widget was:
  MaterialApp
  file:///Users/gmiszewski/Workspace/FLutterAppCheckCrash/flutter_app_check_crash/bug/lib/main.dart:11:12

When the exception was thrown, this was the stack:
packages/flutter/src/material/theme.dart 152:16                          build
```

Please don't look into this crash report as it's random. The error here is that random part of app isn't yet loaded when needed. 

I'm not sure if this error is reproducible in any other JS library, but maybe someone who knows how engine works has better inside on that. 

**Expected results:** App runs all the time

**Actual results:** App isn't loaded correctly every time.

 All other details are irrelevant, as I've tried all stable/beta/master version of flutter, doctor says everything is fine, and I have no code changes inside bug app - the only difference is in index.html.

**Comment by pedromassangocode** [comment]
Hi @miszmaniac 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by miszmaniac** [comment]
```
[+11995 ms] Syncing files to device Chrome... (completed in 13,309ms, longer than expected)
[        ] Synced 27.0MB.
[        ] <- accept
[        ] Caching compiled dill
[ +773 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:63131/devtools/browser/a2293e28-d3d5-4775-89f5-1ccd6138d7d6
[+2704 ms] Debug service listening on ws://127.0.0.1:63157/pK9p91kTA5w=

[ +221 ms] Debug service listening on ws://127.0.0.1:63157/pK9p91kTA5w=
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+115484 ms] TypeError: Cannot read property 'Symbol(_privateNames)' of undefined
                          at Object.dart.privateName (http://localhost:63106/dart_sdk.js:40:24)
                          at load__packages__flutter__src__painting__gradient_dart (http://localhost:63106/packages/flutter/src/painting/gradient.dart.lib.js:217:26)
                          at Object.execCb (http://localhost:63106/require.js:1696:33)
                          at Module.check (http://localhost:63106/require.js:883:51)
                          at Module.enable (http://localhost:63106/require.js:1176:22)
                          at Module.init (http://localhost:63106/require.js:788:26)
                          at callGetModule (http://localhost:63106/require.js:1203:63)
                          at Object.completeLoad (http://localhost:63106/require.js:1590:21)
                          at HTMLScriptElement.onScriptLoad (http://localhost:63106/require.js:1717:29)
[  +61 ms] TypeError: Cannot read property 'Symbol(_privateNames)' of undefined
               at Object.dart.privateName (http://localhost:63106/dart_sdk.js:40:24)
               at load__packages__flutter__src__painting__fractional_offset_dart (http://localhost:63106/packages/flutter/src/painting/fractional_offset.dart.lib.js:81:26)
               at Object.execCb (http://localhost:63106/require.js:1696:33)
               at Module.check (http://localhost:63106/require.js:883:51)
               at Module.enable (http://localhost:63106/require.js:1176:22)
               at Module.init (http://localhost:63106/require.js:788:26)
               at callGetModule (http://localhost:63106/require.js:1203:63)
               at Object.completeLoad (http://localhost:63106/require.js:1590:21)
               at HTMLScriptElement.onScriptLoad (http://localhost:63106/require.js:1717:29)
[  +12 ms] TypeError: Cannot read property 'Symbol(_privateNames)' of undefined
               at Object.dart.privateName (http://localhost:63106/dart_sdk.js:40:24)
               at load__packages__flutter__src__painting__decoration_image_dart (http://localhost:63106/packages/flutter/src/painting/decoration_image.dart.lib.js:141:26)
               at Object.execCb (http://localhost:63106/require.js:1696:33)
               at Module.check (http://localhost:63106/require.js:883:51)
               at Module.<anonymous> (http://localhost:63106/require.js:1139:34)
               at http://localhost:63106/require.js:134:23
               at http://localhost:63106/require.js:1189:21
               at each (http://localhost:63106/require.js:59:31)
               at Module.emit (http://localhost:63106/require.js:1188:17)
               at Module.check (http://localhost:63106/require.js:938:30)
               at Module.<anonymous> (http://localhost:63106/require.js:1139:34)
               at http://localhost:63106/require.js:134:23
               at http://localhost:63106/require.js:1189:21
               at each (http://localhost:63106/require.js:59:31)
               at Module.emit (http://localhost:63106/require.js:1188:17)
               at Module.check (http://localhost:63106/require.js:938:30)
               at Module.<anonymous> (http://localhost:63106/require.js:1139:34)
               at http://localhost:63106/require.js:134:23
               at http://localhost:63106/require.js:1189:21
               at each (http://localhost:63106/require.js:59:31)
               at Module.emit (http://localhost:63106/require.js:1188:17)
               at Module.check (http://localhost:63106/require.js:938:30)
               at Module.<anonymous> (http://localhost:63106/require.js:1139:34)
               at http://localhost:63106/require.js:134:23
               at http://localhost:63106/require.js:1189:21
               at each (http://localhost:63106/require.js:59:31)
               at Module.emit (http://localhost:63106/require.js:1188:17)
               at Module.check (http://localhost:63106/require.js:938:30)
               at Module.enable (http://localhost:63106/require.js:1176:22)
               at Module.init (http://localhost:63106/require.js:788:26)
               at callGetModule (http://localhost:63106/require.js:1203:63)
               at Object.completeLoad (http://localhost:63106/require.js:1590:21)
               at HTMLScriptElement.onScriptLoad (http://localhost:63106/require.js:1717:29)
```

```
[✓] Flutter (Channel beta, 1.22.1, on Mac OS X 10.15.7 19H15, locale en-PL)
    • Flutter version 1.22.1 at /Users/gmiszewski/Workspace/FlutterSdk/flutter
    • Framework revision f30b7f4db9 (6 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gmiszewski/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/gmiszewski/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.1)
    • Android Studio at /Users/gmiszewski/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio (version 4.1)
    • Android Studio at /Users/gmiszewski/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198
```

**Comment by miszmaniac** [comment]
And as I wrote, I can send you token to this survicate script, because it will not happen if it's not loading.

**Comment by pedromassangocode** [comment]
Hi @miszmaniac 
I cannot reproduce this issue on the latest `beta` and `master` channels.

![gif](https://user-images.githubusercontent.com/67424416/99497902-dcaae880-2976-11eb-9763-35df6aeeb4d5.gif)

Can you please upgrade to the latest  `beta` and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

<details><summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="flutter_example">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>flutter_example</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    (function (w) {
      var s = document.createElement('script');
      s.src = 'https://survey.survicate.com/workspaces/TOKEN/web_surveys.js';
      s.async = true;
      var e = document.getElementsByTagName('script')[0];
      e.parentNode.insertBefore(s, e);
    })(window);

    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <script src="main.dart.js" type="application/javascript"></script>

</body>
</html>
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en)
    • Flutter version 1.23.0-18.1.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 198df796aa (5 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

**Comment by miszmaniac** [comment]
I have 100% repro on this. (I get around 1/4 of refreshes with errors)
I've created some random account in this service and here is script that you have to copy.
It won't happen if you use some fake one. 
```
<!-- Start of Survicate (www.survicate.com) code -->
      <script type='text/javascript'>
        (function(w) {
          var s = document.createElement('script');
          s.src = 'https://survey.survicate.com/workspaces/6735e5103a545b43dba3b5cba886b0c8/web_surveys.js';
          s.async = true;
          var e = document.getElementsByTagName('script')[0];
          e.parentNode.insertBefore(s, e);
        })(window);
      </script>
    <!-- End of Survicate code -->
```
![flutterBug](https://user-images.githubusercontent.com/1630300/99501898-ae300c00-297c-11eb-8e53-b7b95b1d5bb6.gif)

**Comment by miszmaniac** [comment]
side note... we managed to bypass this error. 
We've wrapped this code into function and start it from flutter app using js interop, after app boot.

**Comment by pedromassangocode** [comment]
> It won't happen if you use some fake one.

For your information, I have not used a fake TOKEN, I created a free account to try to reproduce the issue.

As said in https://github.com/flutter/flutter/issues/70688#issuecomment-729488563 please upgrade and provide your `flutter doctor -v`.

**Comment by miszmaniac** [comment]
I've tried multiple times today, and problem is gone... both on stable and beta version of flutter. It must have been issue with survicate script, as it started to happen last Thursday for all members of our team (6 different machines).
Anyway thanks for really quick response, sorry to bother you!

**Comment by wtfiwtz** [comment]
I had the same issue with `Firestore`, with random crashes on a clean Flutter/Firestore project. I had to put the firestore javascript in `index.html` *above* the `main.dart.js` script tag...

```html
  <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-app.js"></script>
  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      apiKey: "<key>",
      authDomain: "<app>.firebaseapp.com",
      projectId: "<app>",
      storageBucket: "<app>.appspot.com",
      messagingSenderId: "<id>",
      appId: "<app-id>"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>

<script src="main.dart.js" type="application/javascript"></script>
```

Then run:
```
% flutter build web --verbose
% flutter run -d chrome
```

Cheers,
Nigel
