### ISSUE TITLE
Unsupported operation: Type RichText is currently not supported by getText

### ISSUE THREAD

**Issue by nandhini0761** [flutter/flutter#70750]
Exception: DriverError: Error in Flutter application: Uncaught extension error while executing get_text: Unsupported operation: Type RichText is currently not supported by getText.

flutter version : Flutter 1.24.0-1.0.pre
flutter channel : dev.

Please Help as soon possible

**Comment by pedromassangocode** [comment]
Hi @nandhini0761 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample and the steps to reproduce?
Thank you

**Comment by nandhini0761** [comment]
Hi @pedromassangocode .

Please find the attached flutter doctor -v attached screen shot.
<img width="946" alt="Screenshot 2020-11-19 at 2 55 13 PM" src="https://user-images.githubusercontent.com/72952849/99631834-3c88b880-2a77-11eb-9f26-4971e4935343.png">


sample code : 
_driver.getText(find.descendant(
        of: find.byValueKey('key'),
        matching: find.byType('RichText'),
        firstMatchOnly: true));

Thanks,
Nandhini.

**Comment by pedromassangocode** [comment]
Hi @nandhini0761 
I need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the steps to reproduce? This means the complete test code and the code you are testing as well. You need to create a sample code that reproduce the issue to avoid sharing a production code.

Thank you

**Comment by nandhini0761** [comment]
**### Developer code** 
<img width="570" alt="Screenshot 2020-11-24 at 4 16 47 PM" src="https://user-images.githubusercontent.com/72952849/100067182-ea79d580-2e70-11eb-953a-7424ebe8912d.png">
`
my test code :

await _driver.runUnsynchronized(() async {
     final val = find.descendant(
          of: find.byValueKey('__wallet_screen_currency_total_balance_label__'),
          matching: find.byValueKey('RichText'));
      final data = await _driver.getText(val);
      print('###########$data');
    });

I can not provide the company source code. please help with the above-mentioned issue.

**Comment by pedromassangocode** [comment]
> Hi @nandhini0761
> I need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the steps to reproduce? This means the complete test code and the code you are testing as well. You need to create a sample code that reproduce the issue to avoid sharing private code.
> 


Please share the code as .txt file so that I can copy/paste it, and avoid sharing image when it is not necessary.
Thank you

**Comment by nandhini0761** [comment]
Hi @pedromassangocode ,

Please refer the attached main.dart file and my automation code.
[mani.txt](https://github.com/flutter/flutter/files/5600363/mani.txt)
[test_driver.zip](https://github.com/flutter/flutter/files/5600362/test_driver.zip)

run cmd : flutter driver --target=test_driver/e2e.dart

Thanks,
Nandhini.

**Comment by pedromassangocode** [comment]
Hi @nandhini0761 
can you please shared the logs as well?
Thanks

**Comment by nandhini0761** [comment]
Hi @pedromassangocode 

Please find the attached log.txt file.
[log.txt](https://github.com/flutter/flutter/files/5601609/log.txt)

Thanks,
Nandhini.

**Comment by pedromassangocode** [comment]
<details><summary>Logs</summary>

```
Target file "test_driver/e2e.dart" not found.
MacBook-Pro-de-MacBook:flutter_example pedromassango$ flutter driver --target=test_driver/app.dart 
Using device sdk gphone x86 arm.
Starting application: test_driver/app.dart
Installing build/app/outputs/flutter-apk/app.apk...                 6.3s
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        30.1s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 3.1s
I/flutter_exampl( 6716): Not late-enabling -Xcheck:jni (already on)
I/flutter_exampl( 6716): Unquickening 12 vdex files!
W/flutter_exampl( 6716): Unexpected CPU variant for X86 using defaults: x86
I/flutter ( 6716): Observatory listening on http://127.0.0.1:41607/gK75dQjLGsU=/
W/flutter_exampl( 6716): Accessing hidden method
Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection,
allowed)
W/flutter_exampl( 6716): Accessing hidden method
Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
W/flutter_exampl( 6716): Accessing hidden field
Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist,
reflection, allowed)
W/flutter_exampl( 6716): Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist,
reflection, allowed)
00:00 +0: flutter automation (setUpAll)

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:55498/gK75dQjLGsU=/
VMServiceFlutterDriver: Isolate found with number: 1221985163255395
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
00:02 +0: flutter automation test hellow world

00:03 +0 -1: flutter automation test hellow world [E]

  DriverError: Error in Flutter application: Uncaught extension error while executing get_text: Unsupported operation: Type RichText is currently not supported by getText
  #0      FlutterDriverExtension._getText (package:flutter_driver/src/extension/extension.dart:644:7)
  <asynchronous suspension>
  #1      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:270:53)
  #2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:547:32)
  <asynchronous suspension>
  #3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart)
  #4      _runExtension (dart:developer-patch/developer.dart:84:23)



  package:flutter_driver/src/driver/vmservice_driver.dart 352:7  VMServiceFlutterDriver.sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1129:19                                   _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 94:8                         _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1121:19                                   _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 83:23                        _asyncThenWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:test_api/src/backend/invoker.dart 370:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 415:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 369:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 104:24                      Chain.capture.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 1630:10                                   _runZoned
  dart:async/zone.dart 1550:10                                   runZoned
  package:stack_trace/src/chain.dart 102:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 368:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 153:11  LiveTestController.run
  dart:async/future.dart 201:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1182:47                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1190:13                                   _rootRun
  dart:async/zone.dart 1093:19                                   _CustomZone.run
  dart:async/zone.dart 997:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1037:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 404:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 428:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage


00:03 +0 -1: flutter automation increment the counter

00:04 +1 -1: flutter automation test alert window

00:05 +2 -1: flutter automation (tearDownAll)

00:05 +2 -1: Some tests failed.


Unhandled exception:
Dummy exception to set exit code.
Stopping application instance.
Driver tests failed: 255
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```
</details>

**Comment by nandhini0761** [comment]
@irundaia ,
Any idea when it will merge with a stable branch?

**Comment by irundaia** [comment]
@nandhini0761, I personally am not a member of the flutter team, so I cannot comment on when this will be merged.

I’ve heard that the stable channel gets an update once a quarter, so this could still take several months. 

I’m sorry, I cannot be of more help.
