### ISSUE TITLE
Work around ffi "symbol not found" error from CocoaPods on ARM Macs with x86_64 ffi gem

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#70796]
Running CocoaPods in Rosetta on an ARM mac to embed plugins  (`arch -x86_64 pod install`) [fails](https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-729940217):
```
LoadError - dlsym(0x7fbbeb6837d0, Init_ffi_c): symbol not found - /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
```

The [workaround](https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-729980327) is to install the `ffi` gem in x86:
```
arch -x86_64 sudo gem install ffi
```

Figure out how to install this from `flutter` (prompt `sudo`) without making bundler people mad, or at least add a doctor check similar to the one where CocoaPods isn't installed and prompt them to run that command.

**Comment by jmagman** [comment]
[The tool now detects this issue and suggests how to fix it.](https://github.com/flutter/flutter/pull/70801)  That's probably the best we can do until it's fixed on CocoaPod's side.

Also mentioned in https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon.
