### ISSUE TITLE
Unhandled exception in long running web tests shard

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#70805]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863244671269097552/+/steps/run_test.dart_for_web_long_running_tests_shard_and_subshard_0/0/stdout

```
[INFO]: http://localhost:37465/dart_sdk.js 26815:14 "00:00 +0 ~1: flutter gallery transitions on e2e all demos"
[1605748739.718][SEVERE]: Timed out receiving message from renderer: 30.000
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("message")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      RequestDataResult.fromJson (package:flutter_driver/src/common/request_data.dart:44:34)
#2      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:502:30)
<asynchronous suspension>
#3      integrationDriver (package:integration_test/integration_test_driver.dart:71:29)
<asynchronous suspension>
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
Command: ../../../bin/flutter drive --driver=test_driver/transitions_perf_e2e_test.dart --target=test_driver/transitions_perf_e2e.dart --browser-name=chrome --no-sound-null-safety -d web-server --debug
Relative working directory: dev/integration_tests/flutter_gallery
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by yjbanov** [comment]
This looks like a double error. The first error was a time out. But then `integrationDriver` seems to have kept on truckin' and failed to parse the results. I'm wondering if the keep on truckin' behavior is related to the "All tests passed" case in https://github.com/flutter/flutter/issues/70400.

**Comment by yjbanov** [comment]
The two may be related in that in both cases the test fails, but `integrationDriver` doesn't register the failure and attempts to go on as if the test succeeded.

**Comment by yjbanov** [comment]
Many fixes went into integration tests, including fixing flakes. Assuming this is fixed.
