### ISSUE TITLE
ArgumentError: Invalid argument(s): Cannot find executable for G:\bin\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot.

### ISSUE THREAD

**Issue by qinrunhao** [flutter/flutter#70825]
Earlier today, the packaged APK was successful.But now all flutter projects have this error.

Error Info:
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for G:\bin\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot.".
A crash report has been written to E:\lsrj\flutter_01.log.

flutter_01.log:

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --quiet assemble --depfile E:\lsrj\build\app\intermediates\flutter\release/flutter_build.d --output E:\lsrj\build\app\intermediates\flutter\release -dTargetFile=lib\main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64

## exception

ArgumentError: Invalid argument(s): Cannot find executable for G:\bin\flutter\bin\cache\artifacts\engine\android-arm64-release\windows-x64\gen_snapshot.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:496:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:248:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension>
#11     _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:744:35)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension>
<asynchronous suspension>
#15     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#16     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#17     Future.wait (dart:async/future.dart:406:26)
#18     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:739:45)
#19     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#20     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)
    • Flutter version 1.22.4 at G:\bin\flutter
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at G:\bin\android-sdk-windows
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = G:\bin\android-sdk-windows
    • Java binary at: D:\soft\soft\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at D:\soft\soft\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\soft\soft\IDEA
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[✓] Connected device (1 available)
    • COL AL10 (mobile) • VBJDU18519015303 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @qinrunhao 
I see there's an open issue (https://github.com/flutter/flutter/issues/68475) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
