### ISSUE TITLE
devicelab linux builder failures: problem occurred configuring root project 'android'

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#70844]
The issue happened on multiple builders:
[Linux new_gallery__crane_perf](https://ci.chromium.org/p/flutter/builders/prod/Linux%20new_gallery__crane_perf/15)
[Linux complex_layout_scroll_perf__devtools_memory](https://ci.chromium.org/p/flutter/builders/prod/Linux%20complex_layout_scroll_perf__devtools_memory/13)
[Linux textfield_perf__e2e_summary](https://ci.chromium.org/p/flutter/builders/prod/Linux%20textfield_perf__e2e_summary/14)

Error message:
```
[textfield_perf__e2e_summary] [STDOUT] stdout: [ +270 ms] Welcome to Gradle 5.6.2!
 [textfield_perf__e2e_summary] [STDOUT] stdout: [        ] Here are the highlights of this release:
 [textfield_perf__e2e_summary] [STDOUT] stdout: [        ]  - Incremental Groovy compilation
 [textfield_perf__e2e_summary] [STDOUT] stdout: [        ]  - Groovy compile avoidance
 [textfield_perf__e2e_summary] [STDOUT] stdout: [        ]  - Test fixtures for Java projects
 [textfield_perf__e2e_summary] [STDOUT] stdout: [        ]  - Manage plugin versions via settings script
 [textfield_perf__e2e_summary] [STDOUT] stdout: [        ] For more details see https://docs.gradle.org/5.6.2/release-notes.html
 [textfield_perf__e2e_summary] [STDOUT] stdout: [        ] To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.2/userguide/gradle_daemon.html.
 [textfield_perf__e2e_summary] [STDOUT] stdout: [ +697 ms] Daemon will be stopped at the end of the build stopping after processing
 [textfield_perf__e2e_summary] [STDOUT] stderr: [+406999 ms] FAILURE: Build failed with an exception.
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ] * What went wrong:
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ] A problem occurred configuring root project 'android'.
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ] > Could not resolve all artifacts for configuration ':classpath'.
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ]    > Could not download gson.jar (com.google.code.gson:gson:2.8.5)
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ]       > Could not get resource 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar'.
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ]          > Could not GET 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar'.
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ]             > Read timed out
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ] * Try:
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ] * Get more help at https://help.gradle.org
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ] BUILD FAILED in 6m 51s
 [textfield_perf__e2e_summary] [STDOUT] stdout: [ +392 ms] Running Gradle task 'assembleProfile'... (completed in 412.1s)
 [textfield_perf__e2e_summary] [STDOUT] stdout: [   +5 ms] "flutter drive" took 416,343ms.
 [textfield_perf__e2e_summary] [STDOUT] stderr: [   +5 ms] Gradle task assembleProfile failed with exit code 1
 [textfield_perf__e2e_summary] [STDOUT] stderr: [        ] 
 [textfield_perf__e2e_summary] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
 [textfield_perf__e2e_summary] [STDOUT] stderr:            #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:414:7)
 [textfield_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
 [textfield_perf__e2e_summary] [STDOUT] stderr:            #2      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:101:7)
 [textfield_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
 [textfield_perf__e2e_summary] [STDOUT] stderr:            #3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:567:7)
 [textfield_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
 [textfield_perf__e2e_summary] [STDOUT] stderr:            #4      FlutterDriverService.start (package:flutter_tools/src/drive/drive_service.dart:161:16)
 [textfield_perf__e2e_summary] [STDOUT] stderr:            <asynchronous suspension>
 [textfield_perf__e2e_summary] [STDOUT] stderr:            #5      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:205:7)
```

**Comment by godofredoc** [comment]
Seems like a transient gradle problem. Please reopen if necessary.
