### ISSUE TITLE
Windows widget inspector flake

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#70879]
Text:

```
020-11-19T13:32:49.897167: stdout: Performing hot reload...                                        
2020-11-19T13:32:49.897167: stderr: Unhandled exception:
2020-11-19T13:32:49.897167: stdout: 
2020-11-19T13:32:49.897167: stdout: 
stdout: 
stderr: root::package:flutter/src/widgets/framework.dart::Widget::@=fields::package:flutter/src/widgets/widget_inspector.dart::_location is already bound
stderr: #0      CanonicalName.bindTo (package:kernel/canonical_name.dart:192:7)
stderr: #1      Class.computeCanonicalNames (package:kernel/ast.dart:1197:12)
stderr: #2      Library.computeCanonicalNames (package:kernel/ast.dart:559:14)
stdout: 
stdout: 
stdout: 
stderr: #3      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:9674:13)
stderr: #4      Component.computeCanonicalNames (package:kernel/ast.dart:9636:7)
stderr: #5      sortComponent (package:vm/kernel_front_end.dart:679:13)
stdout: 
stdout: 
stderr: #6      FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:656:5)
stdout: 
stderr: #7      FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:766:13)
stdout: 
stderr: <asynchronous suspension>
```

This appears to be a bug in Dart. Failure was on a windows but but the change was a mac/iOS specific change that doesn't run on Windows.

/cc @jacob314 - do you know who might be able to look into this?
/cc @jonasfj maybe?

**Comment by dnfield** [comment]
Ahh I may be speaking too quickly here - @jonahwilliams has a couple PRs that might be contributing to this that just haven't run yet.

**Comment by jonahwilliams** [comment]
Not a flake! Fixed by https://github.com/flutter/flutter/pull/70884
