### ISSUE TITLE
RenderObjectElement.renderObject can trigger _LateInitializationError

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#70957]
### Steps to reproduce

Save the following app:

```dart
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';

void doNothing() {}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  PipelineOwner pipelineOwner = PipelineOwner(
    onNeedVisualUpdate: doNothing,
    onSemanticsOwnerCreated: doNothing,
    onSemanticsOwnerDisposed: doNothing,
  )..rootNode = DummyView();
  RenderObjectToWidgetAdapter<RenderBox>(
    container: pipelineOwner.rootNode as RenderObjectWithChildMixin<RenderBox>,
    debugShortDescription: '[root]',
    child: Text(''),
  )..attachToRenderTree(BuildOwner(onBuildScheduled: doNothing));
}

class DummyView extends RenderObject with RenderObjectWithChildMixin<RenderBox> {
  @override
  void performLayout() {
    assert(false);
  }

  @override
  void debugAssertDoesMeetConstraints() {
    assert(false);
  }

  @override
  void performResize() {
    assert(false);
  }

  @override
  Rect get paintBounds => Rect.zero;

  @override
  Rect get semanticBounds => Rect.zero;
}
```

... then run the app either from within Android Studio debugger, or at the command line using:

```
$ flutter run -d macos -t lib/main.dart --dart-define=flutter.inspector.structuredErrors=true
```

### Expected behavior

You expect an exception to be thrown and reported (e.g. about `Text` needing a directionality).  But that should be the only exception.

### Actual behavior

In catching the above exception and trying to build an error widget with semantic error info, we end up calling `debugFillProperties()` on `RenderObjectElement` before the element was mounted, [thus causing us to reference `RenderObjectElement.renderObject` before it's been initialized.](https://github.com/flutter/flutter/blob/e51183763b95548bfe02d3052ad9809c99e21fe2/packages/flutter/lib/src/widgets/framework.dart#L6065):

```
The following _LateInitializationError was thrown attaching to the render tree:
LateInitializationError: _renderObject@249042623

When the exception was thrown, this was the stack:
#0      RenderObjectElement._renderObject (package:flutter/src/widgets/framework.dart)
#1      RenderObjectElement.renderObject (package:flutter/src/widgets/framework.dart:5470:36)
#2      RenderObjectElement.debugFillProperties (package:flutter/src/widgets/framework.dart:6065:70)
#3      DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2945:17)
#4      DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2948:8)
#5      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2962:105)
#6      DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:2689:57)
#7      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1631:19)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#10     new List.from (dart:core-patch/array_patch.dart:39:29)
#11     new List.of (dart:core-patch/array_patch.dart:69:17)
#12     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#13     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1632:8)
#14     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1594:25)
#15     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1607:6)
#16     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1454:18)
#17     WidgetInspectorService._reportError (package:flutter/src/widgets/widget_inspector.dart:922:44)
#18     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1103:15)
#19     _debugReportException (package:flutter/src/widgets/framework.dart:6326:16)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4704:9)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:4369:5)
#22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4654:5)
#23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3380:18)
#26     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1208:16)
#27     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1179:5)
#28     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1121:18)
#29     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:19)
#30     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1120:13)
#31     main (package:payouts/bug_report.dart:17:6)
#32     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:136:25)
#37     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:132:5)
#38     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
(elided 5 frames from class _RawReceivePortImpl and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

### User impact

This obfuscates the error messages that are reported, causing developer confusion.  It's also worrying that there may be other code paths where we try to access the late-bound non-null property before it's been initialized.

### Misc info

Related: when this happens under certain circumstances, it also triggers https://github.com/dart-lang/sdk/issues/44266
Related: this was introduced by the null safety migration, as `RenderObjectElement.renderObject` is now a late-bound non-null property.

FYI @goderbauer @a14n @Hixie

**Comment by pedromassangocode** [comment]
<details><summary>Logs</summary>

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Pro-de-MacBook:flutter_example pedromassango$ flutter run -d macos -t lib/main.dart --dart-define=flutter.inspector.structuredErrors=true
No devices found with name or id matching 'macos'
MacBook-Pro-de-MacBook:flutter_example pedromassango$ flutterm run -d macos -t lib/main.dart --dart-define=flutter.inspector.structuredErrors=true
Downloading darwin-x64/FlutterMacOS.framework tools...              8.0s
Downloading darwin-x64-profile/FlutterMacOS.framework tools...         4.4s
Downloading darwin-x64-profile tools...                          2,591ms
Downloading darwin-x64-release/FlutterMacOS.framework tools...        11.8s
Downloading darwin-x64-release tools...                             4.5s
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2734 pos 20: '_debugCurrentBuildTarget == context': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2734:20)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2738:12)
#4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1120:13)
#5      main (package:flutter_example/main.dart:17:6)                   
#6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:136:25)
#7      _rootRun (dart:async/zone.dart:1186:13)                         
#8      _CustomZone.run (dart:async/zone.dart:1090:19)                  
#9      _runZoned (dart:async/zone.dart:1626:10)                        
#10     runZonedGuarded (dart:async/zone.dart:1614:12)                  
#11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:132:5)    
#12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
                                                                        
                                                                        
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _LateInitializationError was thrown attaching to the render tree:
LateInitializationError: _renderObject@250042623

When the exception was thrown, this was the stack:
#0      RenderObjectElement._renderObject (package:flutter/src/widgets/framework.dart)
#1      RenderObjectElement.renderObject (package:flutter/src/widgets/framework.dart:5479:36)
#2      RenderObjectElement.debugFillProperties (package:flutter/src/widgets/framework.dart:6074:70)
#3      DiagnosticableNode.builder.<anonymous closure>
(package:flutter/src/foundation/diagnostics.dart:2945:17)
#4      DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2948:8)
#5      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2962:105)
#6      DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:2689:57)
#7      DiagnosticsNode.toJsonList.<anonymous closure>
(package:flutter/src/foundation/diagnostics.dart:1631:19)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
#10     new List.from (dart:core-patch/array_patch.dart:39:29)
#11     new List.of (dart:core-patch/array_patch.dart:69:17)
#12     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#13     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1632:8)
#14     DiagnosticsNode.toJsonMap.<anonymous closure>
(package:flutter/src/foundation/diagnostics.dart:1594:25)
#15     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1607:6)
#16     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1454:18)
#17     WidgetInspectorService._reportError (package:flutter/src/widgets/widget_inspector.dart:922:44)
#18     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1103:15)
#19     _debugReportException (package:flutter/src/widgets/framework.dart:6335:16)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4713:9)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:4378:5)
#22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4663:5)
#23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4658:5)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3624:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3389:18)
#26     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1208:16)
#27     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1179:5)
#28     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
(package:flutter/src/widgets/binding.dart:1121:18)
#29     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:19)
#30     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1120:13)
#31     main (package:flutter_example/main.dart:17:6)
#32     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:136:25)
#37     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:132:5)
#38     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
(elided 5 frames from class _RawReceivePortImpl and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device macOS...                                   192ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:63776/WGMxcVxoZVk=/

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.365, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.365 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 2ceb371d21 (8 hours ago), 2020-11-24 17:18:06 -0800
    • Engine revision 6ed357c8b3
    • Dart version 2.12.0 (build 2.12.0-74.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>
