### ISSUE TITLE
Crashing When Creating New Project

### ISSUE THREAD

**Issue by suryatmodulus** [flutter/flutter#71040]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter create --ios-language swift --android-language kotlin .

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\flutter\packages\flutter_tools\templates\template_manifest.json' (OS Error: The system cannot find the path specified.
, errno = 3)

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#5      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#6      CreateCommand._computeTemplateManifest (package:flutter_tools/src/commands/create.dart:296:37)
#7      CreateCommand.templateManifest (package:flutter_tools/src/commands/create.dart:282:58)
#8      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:796:25)
#9      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:671:29)
#10     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:436:37)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (9 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Me\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\Me\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Samsung (mobile) • 342343243243 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by suryatmodulus** [comment]
Sorry Installation Error

**Comment by ddonsola** [comment]
how did you solve this problem?
