### ISSUE TITLE
android_alarm_manager / App is getting crashed for callback

### ISSUE THREAD

**Issue by srinikande** [flutter/flutter#71059]
```
I/FlutterBackgroundExecutor(15037): Starting AlarmService...
D/EGL_emulation(15037): eglCreateContext: 0xf3ba4580: maj 2 min 0 rcv 2
D/EGL_emulation(15037): eglCreateContext: 0xf3b924c0: maj 2 min 0 rcv 2
D/HostConnection(15037): HostConnection::get() New Host Connection established 0xf3b91490, tid 15084
D/HostConnection(15037): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
D/EGL_emulation(15037): eglMakeCurrent: 0xf3b924c0: ver 2 0 (tinfo 0xf3eef910) (first time)
I/AndroidAlarmManagerPlugin(15037): onAttachedToEngine
E/TTS     (15037): Failed to initialize TextToSpeech
D/AndroidRuntime(15037): Shutting down VM
E/AndroidRuntime(15037): FATAL EXCEPTION: main
E/AndroidRuntime(15037): Process: com.zeev.remainder, PID: 15037
E/AndroidRuntime(15037): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(15037): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4204)
E/AndroidRuntime(15037): 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
E/AndroidRuntime(15037): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
E/AndroidRuntime(15037): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15037): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(15037): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(15037): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(15037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(15037): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(15037): 	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:336)
E/AndroidRuntime(15037): 	at java.lang.String.valueOf(String.java:2924)
E/AndroidRuntime(15037): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
E/AndroidRuntime(15037): 	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:142)
E/AndroidRuntime(15037): 	at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:173)
E/AndroidRuntime(15037): 	at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:126)
E/AndroidRuntime(15037): 	at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:349)
E/AndroidRuntime(15037): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4192)
E/AndroidRuntime(15037): 	... 8 more
I/Process (15037): Sending signal. PID: 15037 SIG: 9
Lost connection to device.

```

**Comment by sidrao2006** [comment]
Hello @srinikande ,
Could you please post the output of  `flutter doctor -v` and a complete minimal reproducible code sample?
Thank you!

**Comment by srinikande** [comment]
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 6.3.9600], locale en-IN)
    • Flutter version 1.22.4 at C:\src\flutter
    • Framework revision 1aafb3a8b9 (10 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\srinivas\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@srinikande 
Please provide a minimal reproducible code sample that we can use to replicate the issue you are facing.
Thanks.
