### ISSUE TITLE
Flutter: Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized

### ISSUE THREAD

**Issue by fluttercorner1** [flutter/flutter#71088]
Any solution to solve this problem?

here is error
```

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
<asynchronous suspension>
#4      MethodChannel.invokeMapMethod (package:f<…>
```

**Comment by fluttercorner1** [comment]
hello this issue is Solved by helping of [https://fluttercorner.com/flutter-unhandled-exception-servicesbinding-defaultbinarymessenger-was-accesse/](https://fluttercorner.com/flutter-unhandled-exception-servicesbinding-defaultbinarymessenger-was-accesse/)

**Comment by darshankawar** [comment]
@fluttercorner1 Given your last message, I am assuming your issue is solved. Closing this. If you disagree, write in comments and I'll reopen it.
thanks.
