### ISSUE TITLE
`flutter_view__start_up` failing with timeout in agent code

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#71109]
Commit: https://github.com/flutter/flutter/issues/71109 (seems unrelated)

Log: https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahFmbHV0dGVyLWRhc2hib2FyZHJfCxIJQ2hlY2tsaXN0Ij9mbHV0dGVyL2ZsdXR0ZXIvbWFzdGVyLzJiNGEyMzU4NmRiYWYwMDliZDNmODM3YmMyYWQ3MGY4NzNmZmY2MTEMCxIEVGFzaxiAgJj5ua2tCww

Log dump:

```


------------ TASK ------------
Task(id: 6391923323830272, parentKey: flutter/flutter/master/2b4a23586dbaf009bd3f837bc2ad70f873fff611, key: 6391923323830272, commitKey: flutter/flutter/master/2b4a23586dbaf009bd3f837bc2ad70f873fff611, createTimestamp: 1606163342240, startTimestamp: 1606166193885, endTimestamp: 1606167394860, name: flutter_view__start_up, attempts: 2, isFlaky: false, timeoutInMinutes: 0, reason: Task failed on agent, requiredCapabilities: [mac/android], reservedForAgentId: flutter-devicelab-mac-18, stageName: devicelab, status: Failed, buildNumber: null, buildNumberList: null, builderName: null, luciBucket: null)

------------ LOG ------------
Task failed with the following reason:
ERROR: TimeoutException after 0:20:00.000000: Future not completed
#0      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:15)
<asynchronous suspension>
#1      _rootRun (dart:async/zone.dart:1126:13)
#2      _CustomZone.run (dart:async/zone.dart:1023:19)
#3      _runZoned (dart:async/zone.dart:1518:10)
#4      runZoned (dart:async/zone.dart:1502:12)
#5      ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#6      main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)



Task failed with the following reason:
ERROR: TimeoutException after 0:20:00.000000: Future not completed
#0      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:121:15)
<asynchronous suspension>
#1      _rootRun (dart:async/zone.dart:1126:13)
#2      _CustomZone.run (dart:async/zone.dart:1023:19)
#3      _runZoned (dart:async/zone.dart:1518:10)
#4      runZoned (dart:async/zone.dart:1502:12)
#5      ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#6      main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by keyonghan** [comment]
@CaseyHillers anything related to what you are testing?

**Comment by CaseyHillers** [comment]
I don't think so. This is a test runner error which would not show. My roll out will cause a few tasks to stall as in progress, but they will be fixed within the hour by vacuum clean.

**Comment by CaseyHillers** [comment]
@christopherfujino can you link the commit?

**Comment by keyonghan** [comment]
https://github.com/flutter/flutter/commit/2b4a23586dbaf009bd3f837bc2ad70f873fff611

**Comment by keyonghan** [comment]
Same bot picked up the failed task, and it succeeded on the third run.

**Comment by CaseyHillers** [comment]
Thanks Keyong, I haven't touched the mac agents today. This looks to be an issue somewhere else.

**Comment by godofredoc** [comment]
Can you please verify if it is reproducible?

**Comment by keyonghan** [comment]
Closing as not reproducible.
