### ISSUE TITLE
Dropdown opens on top of the page under certain circumstances (with exception)

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#7112]
Sample code to reproduce the problem:

```Dart
import 'package:flutter/material.dart';

class InputContainerDemo extends StatefulWidget {
  @override
  _InputContainerDemoState createState() => new _InputContainerDemoState();
}

class _InputContainerDemoState extends State<InputContainerDemo> {
  static final List<String> _dropdownItems = <String>[
    'One',
    'Two',
    'Free',
    'Four'
  ];
  String _dropdownValue = 'One';

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text('InputContainer Demo')),
        body: new DropdownButtonHideUnderline(
          child: new Padding(
            padding: const EdgeInsets.all(16.0),
            child: new Block(
              children: <Widget>[
                new SizedBox(height: 500.0),
                new InputContainer(
                  labelText: 'Test',
                  child: new DropdownButton<String>(
                    value: _dropdownValue,
                    isDense: true,
                    onChanged: (String newValue) {
                      setState(() {
                        _dropdownValue = newValue;
                      });
                    },
                    items: _dropdownItems.map((String value) {
                      return new DropdownMenuItem<String>(
                        value: value,
                        child: new Text(value),
                      );
                    }).toList(),
                  ),
                ),
              ],
            ),
          ),
        ));
  }
}

void main() {
  runApp(new MaterialApp(home: new InputContainerDemo()));
}
```

Steps:
1. Scroll until you can see the dropdown (but not the underline of the dropdown).
2. Tap.
3. Observe the following:

![image](https://cloud.githubusercontent.com/assets/6687929/20774550/ac92dd10-b70b-11e6-8bf7-657bf84255e6.png)

and the following error:

```
I/flutter ( 2643): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 2643): The following assertion was thrown during performLayout():
I/flutter ( 2643): 'package:flutter/src/material/drop_down.dart': Failed assertion: line 248 pos 16: 'top +
I/flutter ( 2643): childSize.height <= size.height' is not true.
I/flutter ( 2643): When the exception was thrown, this was the stack:
I/flutter ( 2643): #2      _DropdownMenuRouteLayout.getPositionForChild.<anonymous closure> (package:flutter/src/material/drop_down.dart:248:16)
I/flutter ( 2643): #4      _DropdownMenuRouteLayout.getPositionForChild (package:flutter/src/material/drop_down.dart:241:12)
I/flutter ( 2643): #5      RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:837:41)
I/flutter ( 2643): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1736:21)
```

Note that this problem does not happen if the scaffold body has no padding.

**Comment by eseidelGoogle** [comment]
@HansMuller or @Hixie would know.

**Comment by eseidelGoogle** [comment]
We need to verify if this is still happening. :D

**Comment by eseidelGoogle** [comment]
Assigning to @Hixie for triage.

**Comment by eseidelGoogle** [comment]
This relies on InputContainer which is gone.  There should be a flutter-dev thread on what to update it to.  Possibly InputDecoration?

**Comment by jason-simmons** [comment]
Tried this and verified that it works as expected on the current framework.  Closing.
