### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for F:\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.

### ISSUE THREAD

**Issue by dufei816** [flutter/flutter#71126]
## Command
```
flutter --quiet assemble --depfile F:\AndroidStudioProjects\loxen\build\app\intermediates\flutter\release/flutter_build.d --output F:\AndroidStudioProjects\loxen\build\app\intermediates\flutter\release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for F:\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:496:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:248:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension>
#11     _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:744:35)
#12     new Future.sync (dart:async/future.dart:223:31)
#13     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#18     _rootRunUnary (dart:async/zone.dart:1198:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)
    • Flutter version 1.22.1 at F:\flutter
    • Framework revision f30b7f4db9 (7 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at F:\SKD
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = F:\SKD
    • Java binary at: C:\Program Files\Java\jdk1.8.0_171\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at F:\Program Files\JetBrains\IntelliJ IDEA 2018.2
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • MIX 3 (mobile) • ba357f29 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
barcode_scan-3.0.1
catcher-0.3.22
device_info-0.4.2+10
flutter_bmfbase-1.0.2
flutter_bmflocation-1.0.3
flutter_bmfmap-1.0.2
flutter_bmfutils-1.0.2
flutter_ijkplayer-0.3.5+1
flutter_mailer-1.0.1
flutter_plugin_android_lifecycle-1.0.11
fluttertoast-7.1.4
gallery_saver-2.0.1
image_picker-0.6.7+14
jpush_flutter-0.1.0
open_file-3.0.3
package_info-0.4.3+2
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
permission_handler-5.0.1+1
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3
sharesdk_plugin-1.2.8
sqflite-1.3.1+2
uni_links-0.4.0
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+1
url_launcher_windows-0.0.1+3

**Comment by dufei816** [comment]
Problem solving
