### ISSUE TITLE
Could not un-tar (exit code -1073741819). Error:  , path = '' pub get failed (66; , path = '')

### ISSUE THREAD

**Issue by GOGJIAN** [flutter/flutter#71132]
```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1198], locale zh-CN)
    • Flutter version 1.22.4 at C:\work\flutter
    • Framework revision 1aafb3a8b9 (11 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:/Users/Jian/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:/Users/Jian/AppData/Local/Android/Sdk
    • ANDROID_SDK_ROOT = C:\Users\Jian\AppData\Local\Android\Sdk
    • Java binary at: C:\work\Android\AS\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\work\Android\AS3.5
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\work\Android\AS
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: C:/Users/Jian/AppData/Local/Android/Sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:71:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:467:60)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:457:12)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:171:20)
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:975:55)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1190:13)
      #8      _CustomZone.run (dart:async/zone.dart:1093:19)
      #9      _runZoned (dart:async/zone.dart:1630:10)
      #10     runZonedGuarded (dart:async/zone.dart:1618:12)
      #11     runZoned (dart:async/zone.dart:1547:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:191:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:290:47)
      #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:47)
      #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
      #17     _rootRunUnary (dart:async/zone.dart:1198:47)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #23     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
      #24     _rootRun (dart:async/zone.dart:1190:13)
      #25     _CustomZone.run (dart:async/zone.dart:1093:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 2 categories.
```

im already set the envirment value,dont let me try this

**Comment by iapicca** [comment]
possible duplicate of https://github.com/flutter/flutter/issues/70924

**Comment by pedromassangocode** [comment]
Hello @GOGJIAN  ,
Could you please run `echo $ANDROID_SDK_ROOT` and check if the output is a valid path to the Android SDK?
Provide the output of `adb devices` as well.
Thanks

**Comment by GOGJIAN** [comment]
I have no idea to solved this bug ， I try every way every thing，finally ， I must reinstall my windows

**Comment by GOGJIAN** [comment]
> Hello @GOGJIAN ,
> Could you please run `echo $ANDROID_SDK_ROOT` and check if the output is a valid path to the Android SDK?
> Provide the output of `adb devices` as well.
> 
> Can you share more about the issue title as well? it does not match with the issue description provided.
> Thanks

I try to install the “grep console” plugin，then ，become this
