### ISSUE TITLE
AnimatedCrossFade triggers animation exception with duration of zero milliseconds

### ISSUE THREAD

**Issue by benPesso** [flutter/flutter#71227]
## Main issue
As was also reported [elsewhere](#28434), when using the `AnimatedCrossFade` widget with a duration of `milliseconds: 0`, Flutter throws an exception:
```
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1530 pos 12: '_debugCanPerformMutations': is not true.
```

Additionally, documentation in the error itself is severely lacking! It doesn't provide any relevant stack trace, or a thread of information about the offending code line. It is only by trial and error that a developer can figure out that this is caused by an offending `AnimatedCrossFade` widget.

<details>
<summary>Debug Console</summary>

```
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1530 pos 12: '_debugCanPerformMutations': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      RenderObject.markNeedsLayout
package:flutter/…/rendering/object.dart:1530
#3      RenderBox.markNeedsLayout
package:flutter/…/rendering/box.dart:2147
#4      new RenderAnimatedSize.<anonymous closure>
package:flutter/…/rendering/animated_size.dart:95
#5      AnimationLocalListenersMixin.notifyListeners
package:flutter/…/animation/listener_helpers.dart:136
#6      AnimationController._animateToInternal
package:flutter/…/animation/animation_controller.dart:585
...
The AnimationController notifying listeners was: AnimationController#34c52(⏮ 1.000; paused)
════════════════════════════════════════════════════════════════════════════════
```
</details>

## Sample app
When the widget is first rendered, no exceptions are thrown. It is only once you trigger a cross-fade that the exceptions are thrown on each consecutive call.

One can prevent this exception by increasing the duration, but the amount depends on system resources and complexity of code. For example, in the sample app below, setting the duration to `millisecond: 1` is enough. However, in a more complex app, even `milliseconds: 60` might not be enough.

<details>
<summary>main.dart</summary>

```dart
// main.dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  CrossFadeState _crossFadeState = CrossFadeState.showFirst;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            RaisedButton(
              child: Text('Toggle'),
              onPressed: _crossFadeNext,
            ),
            AnimatedCrossFade(
              firstChild: Text('First'),
              secondChild: Text('Second'),
              crossFadeState: _crossFadeState,
              duration: Duration(milliseconds: 0),
            ),
          ],
        ),
      ),
    );
  }

  void _crossFadeNext() {
    setState(() => _crossFadeState =
        (_crossFadeState == CrossFadeState.showFirst)
            ? CrossFadeState.showSecond
            : CrossFadeState.showFirst);
  }
}
```
</details>

### Flutter Doctor
<details>
<summary>Blissfully ignorant, as always. 😐</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-US)
    • Flutter version 1.22.4 at /Users/benPesso/Projects/flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/benPesso/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (1 available)            
    • iPhone SE (2nd generation) (mobile) • ED880130-98FA-4356-8F56-B89E9888798E • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!
```
</details>

**Comment by pedromassangocode** [comment]
Reproducible on stable channel.

@benPesso can you elaborate why do you want an animation with zero `milliseconds`? I can't understand how Flutter can animate without a duration. If you want to switch widgets you can just use a `Visibility` widget or similars.

<details><summary>Logs</summary>

```
Performing hot restart...
Syncing files to device sdk gphone x86 arm...
Restarted application in 3,234ms.

════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1530 pos 12: '_debugCanPerformMutations': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1530:12)
#3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2147:11)
#4      new RenderAnimatedSize.<anonymous closure> (package:flutter/src/rendering/animated_size.dart:95:9)
#5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:136:19)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:585:9)
...
The AnimationController notifying listeners was: AnimationController#c7f81(⏮ 1.000; paused)
════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```
</details>

**Comment by benPesso** [comment]
@pedromassangocode You don't necessarily want to set it to zero. As I wrote, it can also happen if the duration is set to something other than zero, like 60 milliseconds. It depends on how fast the code is processed on the given device, I guess. I ran into this issue in one of my projects where I used a `60ms` duration. While researching it, I came across #28434 and decided to make a proper report for it. Hence this post. 

One use case is in a preference-based interface; a user might prefer to have a "fast" interface, and the easiest way to achieve that is by setting the duration to zero (or something low, like the above 60ms) when the user switches on "Fast Mode". Especially if you have the same duration configured globally for multiple widgets.

**Comment by HansMuller** [comment]
CC @shihaohong @goderbauer

**Comment by shihaohong** [comment]
@dnfield This is a case where the stack trace is truncated (originally brought up in https://github.com/flutter/flutter/issues/52732). I'm not sure how to get more of the stack trace showing, which might help me with figuring out what's wrong here.

**Comment by shihaohong** [comment]
I took some time looking at the code, it might be the result of an interaction between the `AnimatedSize` and `AnimatedCrossFade`'s default layout builder, which uses a `Stack`. When I modify the code to use a `layoutBuilder` using a Column, it no longer happens:
```dart
            AnimatedCrossFade(
              layoutBuilder: (one, oneKey, two, twoKey) {
                return Column(
                  children: [
                    Container(
                      key: oneKey,
                      child: one,
                    ),
                    Container(
                      key: twoKey,
                      child: two,
                    ),
                  ],
                );
              },
              // ....
```

I'm not exactly sure why this is happening, but since the assertion is happening while attempting to lay out `AnimatedSize`, `AnimatedCrossFade` may not have the chance to lay out its `Stack` before `AnimatedSize` wants to lay out.

**Comment by benPesso** [comment]
Any progress on this issue? Seems to be stale for quite a while now. 😐
