### ISSUE TITLE
Building flutter tool is broken after switching lanes

### ISSUE THREAD

**Issue by lcsvcn** [flutter/flutter#71274]
## How it started
After switching lanes from stable to beta, it started crash my flutter tool when it was being build.
(I was at latest stable version and switched lanes)

I have reinstalled it from scratch, but that doesn't fix anything.

I am unable to use flutter in the meanwhile.

## Steps to Reproduce

1. ... Be on Linux (My distro is: Ubuntu 20.04 LTS)
2. ... Download flutter from git - stable version (git clone and export PATH)
3. ... Update to latest version of stable
4. ... Switch to beta and try to run upgrade

## Logs
```
 flutter precache                      ✔  38s    09:41:07   
Downloading Dart SDK from Flutter engine 20caf549695193a9920ca37752eca4f141bbef31...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  176M  100  176M    0     0  12.2M      0  0:00:14  0:00:14 --:--:-- 13.9M
Building flutter tool...
kernel-service: Error: Unhandled exception:
Invalid argument(s): Exception when reading 'file://home/venturus/flutter/packages/flutter_tools/.dart_tool/package_config.json': Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:569:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:583:26)
<asynchronous suspension>
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:648:11)
<asynchronous suspension>
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:517:26)
<asynchronous suspension>
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:471:32)
<asynchronous suspension>
#5      languageVersionForUri.<anonymous closure> (package:front_end/src/api_prototype/language_version.dart:58:35)
<asynchronous suspension>
#6      languageVersionForUri (package:front_end/src/api_prototype/language_version.dart:38:10)
<asynchronous suspension>
#7      uriUsesLegacyLanguageVersion (package:front_end/src/api_prototype/language_version.dart:147:7)
<asynchronous suspension>
#8      autoDetectNullSafetyMode (package:vm/kernel_front_end.dart:557:18)
<asynchronous suspension>
#9      _processLoadRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:801:5)
<asynchronous suspension>

Unhandled exception:
Invalid argument(s): Exception when reading 'file://home/venturus/flutter/packages/flutter_tools/.dart_tool/package_config.json': Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:569:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:583:26)
<asynchronous suspension>
#2      ProcessedOptions.createPackagesFromFile (package:front_end/src/base/processed_options.dart:648:11)
<asynchronous suspension>
#3      ProcessedOptions._getPackages (package:front_end/src/base/processed_options.dart:517:26)
<asynchronous suspension>
#4      ProcessedOptions.getUriTranslator (package:front_end/src/base/processed_options.dart:471:32)
<asynchronous suspension>
#5      languageVersionForUri.<anonymous closure> (package:front_end/src/api_prototype/language_version.dart:58:35)
<asynchronous suspension>
#6      languageVersionForUri (package:front_end/src/api_prototype/language_version.dart:38:10)
<asynchronous suspension>
#7      uriUsesLegacyLanguageVersion (package:front_end/src/api_prototype/language_version.dart:147:7)
<asynchronous suspension>
#8      autoDetectNullSafetyMode (package:vm/kernel_front_end.dart:557:18)
<asynchronous suspension>
#9      _processLoadRequest (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/kernel_service.dart:801:5)
<asynchronous suspension>

```

```
```

**Comment by jensjoha** [comment]
Could you provide us with the content of `file://home/venturus/flutter/packages/flutter_tools/.dart_tool/package_config.json`?

**Comment by johnniwinther** [comment]
This is likely related to https://github.com/flutter/flutter/issues/63579

**Comment by jensjoha** [comment]
From that issue --- an interesting point would be what `which flutter dart` returns.

**Comment by jensjoha** [comment]
Yup --- I think that's the reproduction:
```
$ which flutter
# (empty output --- there's no flutter)

$ git clone https://github.com/flutter/flutter.git
# (...)

$ export PATH="//usr/local/google/home/jensj/code/nobackup/flutter/issue71274/flutter/bin:$PATH"
# (notice that the path is basically correct except that it starts with two slashes instead of one!)

$ which flutter
//usr/local/google/home/jensj/code/nobackup/flutter/issue71274/flutter/bin/flutter

$ flutter channel beta
Building flutter tool...
kernel-service: Error: Unhandled exception:
Invalid argument(s): Exception when reading 'file://usr/local/google/home/jensj/code/nobackup/flutter/issue71274/flutter/packages/flutter_tools/.dart_tool/package_config.json': Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
#0      ProcessedOptions._readFile (package:front_end/src/base/processed_options.dart:569:7)
<asynchronous suspension>
#1      ProcessedOptions._createPackagesFromFile (package:front_end/src/base/processed_options.dart:583:26)
<asynchronous suspension>
[...]
```

**Comment by jensjoha** [comment]
Which means that the workaround here is probably to fix the path. Change the path to flutter to only include one slash and it seems to build just fine.

**Comment by lcsvcn** [comment]
> Could you provide us with the content of `file://home/venturus/flutter/packages/flutter_tools/.dart_tool/package_config.json`?

Sure, Here it is:

https://paste.ofcode.org/3bwB62dEfaVtS54HYstfMzS

**Comment by lcsvcn** [comment]
> which flutter dart

Result:
```
//home/venturus/flutter/bin/flutter
//home/venturus/flutter/bin/dart
```

**Comment by lcsvcn** [comment]
Solved this issue reseting my $PATH

**Step By Step Fix:**

**1)** _Check your Path_
> echo $PATH                                  # Check the double slash in the flutter import


**2)** _Clear your Path Variable_
> export PATH=""                             # Clear PATH variable


**3)** _Restore environments config_
> source /etc/environment              # Restore Environments PATH


**3)** _Restore your bash config_
> source ~/.zshrc                            # use  your bash here: here are some .bashrc or .zshrc

Then just run flutter again.

For some strange reason it was added when I switch to the Beta lane. Really odd.

**Comment by lcsvcn** [comment]
After my reseting my $PATH:
which flutter dart
```
/home/venturus/flutter/bin/flutter
/home/venturus/flutter/bin/dart

```

**Comment by darshankawar** [comment]
@lcsvcn 
Is this safe to close or still need more investigation ?

**Comment by lcsvcn** [comment]
We can close this issue
