### ISSUE TITLE
Flutter installation - ******  B A T C H   R E C U R S I O N  exceeds STACK limits ******

### ISSUE THREAD

**Issue by thomaslc66** [flutter/flutter#71285]
```
			******  B A T C H   R E C U R S I O N  exceeds STACK limits ******
			Recursion Count=317, Stack Usage=90 percent
			******       B A T C H   PROCESSING IS   A B O R T E D      ******
			pub get failed (255; ******       B A T C H   PROCESSING IS   A B O R T E D 
```

## Steps to Reproduce

1. git clone https://github.com/flutter/flutter.git -b stable in c:/src/flutter
2. open visual studio/ android studio install dart/flutter plugin
3. run flutter doctor -v

## Logs

All commands are producing the same result

```
$ flutter channel dev
Page de codes active : 65001
DESKTOP-8U21R64\Thomas
Building flutter tool...
Running pub upgrade...
***  La récursivité de la commande dépasse les limites de la pile ***
Nombre de récursions=317, Utilisation de la pile=90 pour-cent
***       Le traitement  est abandonné       ***
```

```
$ flutter doctor -v
Page de codes active : 65001
DESKTOP-8U21R64\Thomas
Building flutter tool...
Running pub upgrade...
***  La récursivité de la commande dépasse les limites de la pile ***
Nombre de récursions=317, Utilisation de la pile=90 pour-cent
***       Le traitement  est abandonné       ***
```

I've the last flutter from the zip here: https://flutter.dev/docs/get-started/install/windows
Tried also the git command line, using master branch, dev branch and stable branch. 
Always getting the same result.

Same error mentioned here : https://github.com/flutter/flutter/issues/46654, https://github.com/flutter/flutter/issues/57646
But I really don't want to reimage my all host, so if somebody has a better solution?

thank you in advance

**Comment by thomaslc66** [comment]
This what the android studio give me in the flutter sdk version:
![image](https://user-images.githubusercontent.com/9827392/100388900-302ecd80-302c-11eb-8fa7-91326db2677c.png)

**Comment by thomaslc66** [comment]
Deleted android studio, updated BIOS and Windows.
Deleted flutter.

Rebooted, downloaded Flutter old version 1.20.0
Reinstalled android studio
Run again thoses commands...

```
Thomas@DESKTOP-8U21R64 MINGW64 ~
$ flutter doctor -v
Page de codes active▒: 65001
DESKTOP-8U21R64\Thomas
[√] Flutter (Channel stable, 1.20.0, on Page de codes activeÿ: 65001
DESKTOP-8U21R64\Thomas

Microsoft Windows [version 10.0.18363.1198], locale fr-CH)
    • Flutter version 1.20.0 at C:\sdk\flutter
    • Framework revision 840c9205b3 (4 months ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Thomas\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Users\Thomas\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_241\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

Thomas@DESKTOP-8U21R64 MINGW64 ~
$ flutter upgrade
Page de codes active▒: 65001
DESKTOP-8U21R64\Thomas
Upgrading Flutter from C:\sdk\flutter...
Page de codes active�: 65001
DESKTOP-8U21R64\Thomas
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 2c956a31c0a3d350827aee6c56bb63337c5b4e6e...
WARNING: Module BitsTransfer is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
***  La récursivité de la commande dépasse les limites de la pile ***
Nombre de récursions=317, Utilisation de la pile=90 pour-cent
***       Le traitement  est abandonné       ***

Thomas@DESKTOP-8U21R64 MINGW64 ~
```

**Comment by darshankawar** [comment]
@thomaslc66 
Can you probably try to install not in `C:`, but some other drive or inside `Documents` and try again ?

**Comment by thomaslc66** [comment]
Not working in Documents:
![image](https://user-images.githubusercontent.com/9827392/100447132-5302c580-30b0-11eb-8176-97793a0e89b8.png)

I've run a flutter upgrade -v also to have more info.
![image](https://user-images.githubusercontent.com/9827392/100448923-59467100-30b3-11eb-8091-c8da92ce0d97.png)

**Comment by darshankawar** [comment]
@thomaslc66 
Are you able to run `flutter run --verbose` ? If so, can you provide the entire log in text format instead of screenshot ?

**Comment by thomaslc66** [comment]
Not able any more as the last command wasn't able to complete, now everytime I run a command there this : "Running pub upgrade" that try to run again.
In order to run `flutter run --verbose` I need to delete all flutter install and reinstall it.

**Comment by thomaslc66** [comment]
flutter run --verbose:

````
$ flutter run --verbose
Page de codes active▒: 65001
DESKTOP-8U21R64\Thomas
[ +253 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +105 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1aafb3a8b9b0c36241c5f5b34ee914770f015818
[   +1 ms] executing: [C:\tools\flutter/] git tag --points-at HEAD
[  +65 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.4
[  +18 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +34 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +106 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +349 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] executing: C:\Users\Thomas\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +127 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:1
[  +13 ms] C:\Users\Thomas\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +274 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +204 ms] Running "flutter pub get" in flutter_mobidoc...
[   +6 ms] Using C:\tools\flutter\.pub-cache for the pub cache.
[   +2 ms] executing: [C:\Users\Thomas\Documents\flutter_mobidoc/] C:\tools\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose get --no-precompile
[  +76 ms] Page de codes active�: 65001
[   +1 ms] DESKTOP-8U21R64\Thomas
[+120448 ms] ***  La récursivité de la commande dépasse les limites de la pile ***
[   +3 ms] Nombre de récursions=317, Utilisation de la pile=90 pour-cent
[        ] ***       Le traitement  est abandonné       ***
[ +189 ms] Running "flutter pub get" in flutter_mobidoc... (completed in 120,7s, longer than expected)
[   +3 ms] "flutter run" took 121 463ms.
[   +9 ms] pub get failed (255; ***       Le traitement  est abandonné       ***)
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:335:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +246 ms] ensureAnalyticsSent: 242ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 255
````

**Comment by darshankawar** [comment]
@thomaslc66 
Since you mentioned, you used `[chocolatery](https://chocolatey.org/packages/flutter)` package to install Flutter, which is a 3rd party plugin and you may need to follow-up in that package's repo for this issue. 
Are you able to install and run directly using the [official](https://flutter.dev/docs/get-started/install/windows) documentation steps ?

**Comment by thomaslc66** [comment]
No, if you read my first post, I've told that I've been trying with the official zip, the master, dev, stable repo also and for my last try I've tested the chocolatey. But the problem is the same no matter which of those flutters I take.

**Comment by darshankawar** [comment]
@thomaslc66 
In the Windows installation guide, I see that the command `git clone https://github.com/flutter/flutter.git -b stable` need to run from `C:\src>`. 

From your original issue description, you seem to be running like from `c:/src/flutter`.  Can you check and confirm if this makes any difference ?

**Comment by thomaslc66** [comment]
No, this makes no difference.
It's been a week now and I've tested all installation in all folder. Rebooted 25 times, installed flutter 26 times in more than 5 different location and everytime I get the same error. I've tried using android studio, then visual studio code to see if there was any difference. I've uninstall android studio, android SDK reinstalled all but nothing is changing when `flutter pub get` is launched flutter bug and give me the same recursion error.

**Comment by darshankawar** [comment]
@thomaslc66 
I think this could be an issue with the `pub` package from dart lang. See [this](https://github.com/flutter/flutter/issues/52645) similar issue and corresponding [comment](https://github.com/flutter/flutter/issues/52645#issuecomment-602840321) for reference.

**Comment by thomaslc66** [comment]
Yes, I've seen those issues but the solution was reinstall OS, and this is not a viable solution for me.

**Comment by darshankawar** [comment]
I see that you've rightly opened an issue there. Keeping this issue open until you get updates from it.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
