### ISSUE TITLE
app wont run after migration

### ISSUE THREAD

**Issue by kelechiude** [flutter/flutter#71329]
## Steps to Reproduce

1. I had cloned a project off of github and tried to open it
2. on running flutter packages get, i was told to migrate using some instructions which i have managed to do,
3. but after migration and sucessfully running flutter packages get, when i run my app, it still throws an exception in run console

## Logs

```
[ +186 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +91 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f30b7f4db93ee747cd727df747941a28ead25ff5
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at HEAD
[  +65 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.0-12.4.pre
           1.22.1
[  +16 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +125 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +98 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +67 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +117 ms] List of devices attached
                    043911194R100252       device product:H624 model:Infinix_X627 device:Infinix-X627STU transport_id:1
[  +13 ms] C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 043911194R100252 shell getprop
[ +159 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +409 ms] Generating C:\Users\HP\AndroidStudioProjects\Clima-Flutter\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +36 ms] ro.hardware = mt6761
[        ] ro.build.characteristics = default
[  +88 ms] Starting incremental build...
[   +4 ms] Initializing file store
[  +21 ms] Skipping target: gen_localizations
[  +14 ms] complete
[  +10 ms] Launching lib\main.dart on Infinix X627 in debug mode...
[   +8 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\HP\AppData\Local\Temp\flutter_tools.d409d577\flutter_tool.dff591f1\app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +40 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 043911194R100252 shell -x logcat -v time -t 1
[ +126 ms] Exit code 0 from: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 043911194R100252 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           11-28 00:25:19.556 D/pnpmgr  ( 1623): wl = 1,rt_time = 0,rt_data = 0,wt_time = 0,wt_data = 0,pid = 0,data = 0
[   +3 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 043911194R100252 shell -x logcat -v time -t 1
[ +134 ms] Exit code 0 from: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 043911194R100252 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           11-28 00:25:19.866 I/MWN     (  974): write the value:0 to node successfully.
[  +25 ms] <- compile package:clima/main.dart
[ +142 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +275 ms] Android Debug Bridge version 1.0.41
                    Version 30.0.4-6686687
                    Installed as C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +26 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +201 ms] Building APK
[  +77 ms] Running Gradle task 'assembleDebug'...
[  +22 ms] gradle.properties already sets `android.enableR8`
[  +17 ms] Using gradle from C:\Users\HP\AndroidStudioProjects\Clima-Flutter\android\gradlew.bat.
[   +2 ms] C:\Users\HP\AndroidStudioProjects\Clima-Flutter\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +14 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +299 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +6 ms] executing: [C:\Users\HP\AndroidStudioProjects\Clima-Flutter\android/] C:\Users\HP\AndroidStudioProjects\Clima-Flutter\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm -Ptarget=C:\Users\HP\AndroidStudioProjects\Clima-Flutter\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+5622 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [ +215 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +13 ms] [ +118 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] f30b7f4db93ee747cd727df747941a28ead25ff5
[   +1 ms] [   +4 ms] executing: [C:\src\flutter/] git tag --points-at HEAD
[ +111 ms] [ +104 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] [        ] 1.22.0-12.4.pre
[   +1 ms]            1.22.1
[   +1 ms] [  +72 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +85 ms] [ +115 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +103 ms] [  +67 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] [        ] https://github.com/flutter/flutter.git
[ +215 ms] [ +149 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +83 ms] [ +131 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[  +95 ms] [  +74 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] [   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +42 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ +124 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[  +34 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +94 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +18 ms] [ +217 ms] Initializing file store
[   +9 ms] [  +45 ms] Done initializing file store
[  +73 ms] [  +91 ms] Skipping target: gen_localizations
[+1771 ms] [+1852 ms] Skipping target: kernel_snapshot
[   +2 ms] [  +10 ms] invalidated build due to missing files: C:\Users\HP\AndroidStudioProjects\Clima-Flutter\DOES_NOT_EXIST_RERUN_FOR_WILDCARD969988945
[ +697 ms] [ +624 ms] debug_android_application: Starting due to {InvalidatedReason.inputMissing}
[ +499 ms] [ +511 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +1 ms] [  +48 ms] debug_android_application: Complete
[ +599 ms] [ +606 ms] Persisting file store
[  +99 ms] [  +17 ms] Done persisting file store
[   +2 ms] [   +7 ms] build succeeded.
[   +1 ms] [  +22 ms] "flutter assemble" took 4,135ms.
[        ] [   +7 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +5 ms] exiting with code 0
[ +398 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +91 ms] > Task :app:cleanMergeDebugAssets
[   +5 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[  +94 ms] > Task :app:mergeDebugAssets
[ +404 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[  +92 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +2 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +110 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +2 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[+1178 ms] > Task :app:processDebugResources FAILED
[   +3 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] Execution failed for task ':app:processDebugResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[   +1 ms]      C:\Users\HP\AndroidStudioProjects\Clima-Flutter\android\app\src\main\AndroidManifest.xml:25:13-28:19: AAPT: error: resource style/NormalTheme (aka
co.appbrewery.clima:style/NormalTheme) not found.
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 12s
[   +1 ms] 16 actionable tasks: 5 executed, 11 up-to-date
[ +495 ms] Running Gradle task 'assembleDebug'... (completed in 13.7s)
[  +59 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 15,843ms.
[  +11 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +259 ms] ensureAnalyticsSent: 255ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +6 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

```

```
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by Abhishek01039** [comment]
Hello @kelechiude 
you can refer to this https://stackoverflow.com/questions/58084850/how-to-fix-this-error-a-failure-occurred-while-executing-com-android-build-grad and this https://stackoverflow.com/questions/52043792/resource-style-launchtheme-not-found
Thanks.

**Comment by TahaTesser** [comment]
Hi @kelechiude 

> [   +1 ms]      C:\Users\HP\AndroidStudioProjects\Clima-Flutter\android\app\src\main\AndroidManifest.xml:25:13-28:19: AAPT: error: resource style/NormalTheme (aka
> co.appbrewery.clima:style/NormalTheme) not found.

Looks like this some resources is missing, please open the android folder of the project in Android Studio, make sure it has no missing resources or error. 
Also, it's a good idea to check if gradle is  `classpath 'com.android.tools.build:gradle:3.5.0'` cuz when loading old projects, it usually an outdated Gradle version in `build.gradle`. Create a new project in flutter then compared dependencies from cloned project with a new project, update whatever is needed

Hope this helps

**Comment by kelechiude** [comment]
@TahaTesser thanks, This worked perfectly
