### ISSUE TITLE
[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by fabribit** [flutter/flutter#71327]
I'm having problems trying to integrate a SDK in Android Native side.
For some weird reason, Flutter build is removing many classes of this SDK from runtime classpath and as a result the app crashes at runtime.

Flutter gradle:
```
group 'com.djisdk'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.4.10'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 28
    useLibrary 'org.apache.http.legacy'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        // minSdkVersion is set to 21 because of the multidex support (https://developer.android.com/studio/build/multidex)
        minSdkVersion 21
        targetSdkVersion 28

        ndk {
            // On x86 devices that run Android API 23 or above, if the application is targeted with API 23 or
            // above, FFmpeg lib might lead to runtime crashes or warnings.
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions{
        doNotStrip "*/*/*.so"
        exclude 'META-INF/rxjava.properties'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // ---- DJI ----
    implementation ('com.dji:dji-sdk:4.13.1', {
        /**
         * Uncomment the "library-anti-distortion" if your app does not need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom.
         * Uncomment the "fly-safe-database" if you need database for release, or we will download it when DJISDKManager.getInstance().registerApp
         * is called.
         * Both will greatly reducing the size of the APK.
         */
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'

        /**
         * Uncomment the following line to exclude amap from the app.
         * Note that Google Play Store does not allow APKs that include this library.
         */
        // exclude group: 'com.amap.api'
    })
    compileOnly 'com.dji:dji-sdk-provided:4.13.1'

    implementation ('com.dji:dji-uxsdk:4.13', {
        /**
         * Comment the "library-anti-distortion" if your app does need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom.
         * Comment the "fly-safe-database" if you do not need database for release, or we will download it when DJISDKManager.getInstance().registerApp
         * is called.
         * Both will greatly reducing the size of the APK.
         */
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'

        /**
         * Uncomment the following line to exclude amap from the app.
         * Note that Google Play Store does not allow APKs that include this library.
         */
        // exclude group: 'com.amap.api'
    })

    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    // ---- DJI ----
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

I already tried the same implementation and dependencies of gradle in stand alone Android project (without Flutter) and the app compiles and runs correctly.

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

repositories {
    mavenLocal()
}

android {
    compileSdkVersion 28
    useLibrary 'org.apache.http.legacy'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28

        ndk {
            // On x86 devices that run Android API 23 or above, if the application is targeted with API 23 or
            // above, FFmpeg lib might lead to runtime crashes or warnings.
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        doNotStrip "*/*/*.so"
        exclude 'META-INF/rxjava.properties'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}


dependencies {
    // ---- DJI ----
    implementation('com.dji:dji-sdk:4.13.1', {
        /**
         * Uncomment the "library-anti-distortion" if your app does not need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom.
         * Uncomment the "fly-safe-database" if you need database for release, or we will download it when DJISDKManager.getInstance().registerApp
         * is called.
         * Both will greatly reducing the size of the APK.
         */
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'
    })
    compileOnly 'com.dji:dji-sdk-provided:4.13.1'

    implementation ('com.dji:dji-uxsdk:4.13', {
        /**
         * Comment the "library-anti-distortion" if your app does need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom.
         * Comment the "fly-safe-database" if you do not need database for release, or we will download it when DJISDKManager.getInstance().registerApp
         * is called.
         * Both will greatly reducing the size of the APK.
         */
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'

        /**
         * Uncomment the following line to exclude amap from the app.
         * Note that Google Play Store does not allow APKs that include this library.
         */
        // exclude group: 'com.amap.api'
    })

    androidTestCompile('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testImplementation 'junit:junit:4.12'

    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    // ---- DJI ----
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

// Please uncomment the following code if you use your own sdk version.
//apply from : "https://terra-1-g.djicdn.com/71a7d383e71a4fb8887a310eb746b47f/msdk/Android-CommonConfig/config_sample_all.gradle"
```

This is the output log of Flutter

```
11-27 01:24:29.350 8568-8568/? I/art: Late-enabling -Xcheck:jni
11-27 01:24:29.460 8568-8568/com.djisdk_example I/System.out: should load native is true
11-27 01:24:29.470 8568-8598/com.djisdk_example I/ResourceExtractor: Found extracted resources res_timestamp-1-1606451035390
11-27 01:24:29.540 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/os/LocaleList;
11-27 01:24:29.540 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/os/LocaleList;
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/mission/waypoint/WaypointMissionOperatorListener;
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Can not find class: Lcom/djisdk/controller/MissionController;
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/sdkmanager/DJISDKManager;
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.750 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:29.840 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/ViewStructure;
11-27 01:24:29.850 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.860 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.860 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.860 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.860 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.860 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.870 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.870 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillValue;
11-27 01:24:29.870 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.870 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.870 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.870 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.880 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.880 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillManager;
11-27 01:24:29.880 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillValue;
11-27 01:24:29.890 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/WindowInsetsAnimation$Callback;
11-27 01:24:29.890 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugin.editing.ImeSyncDeferringInsetsCallback>
11-27 01:24:29.890 8568-8568/com.djisdk_example I/art: Can not find class: Lio/flutter/plugin/editing/ImeSyncDeferringInsetsCallback;
11-27 01:24:29.890 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugin.editing.ImeSyncDeferringInsetsCallback>
11-27 01:24:29.890 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugin.editing.ImeSyncDeferringInsetsCallback>
11-27 01:24:29.890 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugin.editing.ImeSyncDeferringInsetsCallback>
11-27 01:24:29.890 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugin.editing.ImeSyncDeferringInsetsCallback>
11-27 01:24:29.890 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<io.flutter.plugin.editing.ImeSyncDeferringInsetsCallback>
11-27 01:24:29.900 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/ViewStructure;
11-27 01:24:29.900 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillId;
11-27 01:24:29.900 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/view/autofill/AutofillValue;
11-27 01:24:30.010 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/widget/ViewStub;
11-27 01:24:30.010 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/webkit/ViewStub;
11-27 01:24:30.010 8568-8568/com.djisdk_example I/art: Can not find class: Landroid/app/ViewStub;
11-27 01:24:30.090 8568-8617/com.djisdk_example I/OpenGLRenderer: Initialized EGL, version 1.4
11-27 01:24:30.130 8568-8612/com.djisdk_example I/flutter: Observatory listening on http://127.0.0.1:42516/Hs9MeeIfNto=/
11-27 01:24:30.660 8568-8568/com.djisdk_example I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
11-27 01:24:31.630 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/products/Aircraft;
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/products/Aircraft;
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/common/util/CommonCallbacks$CompletionCallback;
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.FlightController$flightControl$callback$1>
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Can not find class: Lcom/djisdk/controller/FlightController$flightControl$callback$1;
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.FlightController$flightControl$callback$1>
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/sdkmanager/DJISDKManager;
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/base/BaseProduct;
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/products/Aircraft;
11-27 01:24:31.640 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/products/Aircraft;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/products/Aircraft;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/products/Aircraft;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/flightcontroller/FlightController;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/common/flightcontroller/FlightControllerState$Callback;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.FlightController$initialize$1>
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Lcom/djisdk/controller/FlightController$initialize$1;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.FlightController$initialize$1>
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/products/Aircraft;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/products/Aircraft;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/flightcontroller/FlightController;
11-27 01:24:31.650 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/sdk/flightcontroller/Simulator;
11-27 01:24:31.660 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/common/flightcontroller/simulator/SimulatorState$Callback;
11-27 01:24:31.660 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.FlightController$simulator$1>
11-27 01:24:31.660 8568-8568/com.djisdk_example I/art: Can not find class: Lcom/djisdk/controller/FlightController$simulator$1;
11-27 01:24:31.660 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.FlightController$simulator$1>
11-27 01:24:31.660 8568-8568/com.djisdk_example I/art: Can not find class: Ldji/common/flightcontroller/simulator/SimulatorState$Callback;
11-27 01:24:31.660 8568-8568/com.djisdk_example I/art: Rejecting re-init on previously-failed class java.lang.Class<com.djisdk.controller.MissionController>
11-27 01:24:31.660 8568-8568/com.djisdk_example E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NoClassDefFoundError: com.djisdk.controller.MissionController
        at com.djisdk.Sdk.onListen(Sdk.kt:63)
        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:188)
        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5538)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
11-27 01:24:31.660 8568-8568/com.djisdk_example A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
11-27 01:24:31.660 8568-8568/com.djisdk_example A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 8568 (.djisdk_example)
```

**Comment by TahaTesser** [comment]
Hi @fabribit 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by fabribit** [comment]
I solve this bug initializing the SDK in main.dart insted of the splash.dart file.

I think the problem is in the initialization

Thanks for your reply!

**Comment by Jimmuy** [comment]
> I solve this bug initializing the SDK in main.dart insted of the splash.dart file.
> 
> I think the problem is in the initialization
> 
> Thanks for your reply!

I have the same issue in my project ,can you show me how to initializing the SDK in main.dart? tks

**Comment by fabribit** [comment]
Sorry the problem persist, I am preparing a repository with both test cases so they can reproduce the flutter error.

**Comment by TahaTesser** [comment]
@fabribit  @Jimmuy 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
