### ISSUE TITLE
'_elements.contains(element)': is not true while making builder of Form

### ISSUE THREAD

**Issue by pranimation** [flutter/flutter#71339]
<details> 
<summary>flutter doctor -v</summary> 

```bash
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Builder:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2036 pos 12: '_elements.contains(element)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

The relevant error-causing widget was: 
  Builder file:///C:/data/projects/flutter/flutter_widget/lib/home.dart:19:16
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:2036:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3526:29)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3551:32)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 2 of 531 libraries in 3,686ms.
```

</details>

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'user_data.dart';

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

final _formKey=GlobalKey<FormState>();
final _user=UserData();
class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('Profile')),
        body: Container(
        padding:
        const EdgeInsets.symmetric(vertical: 16.0, horizontal: 16.0),
        child: Builder(
        builder: (context) =>
          Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                decoration: InputDecoration(
                  labelText: "First Name"
                ),
                validator: (value)=>(value.isEmpty) ?"can not empty" : null,
                onSaved: (value)=>{
                  setState(()=>_user.firstName=value),
                },
              ),
              TextFormField(
                decoration: InputDecoration(
                  labelText: "Last Name"
                ),
                onSaved: (value)=>{
                  setState(()=>_user.lastName=value),
                },
                validator: (value)=>(value.isEmpty)? "write your name":null,
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Radio(
                    value: 0,
                    groupValue: _user.gender,
                    onChanged: (value)=>{setState(()=>_user.gender=value)},
                  ),
                  Text("Male"),
                  Radio(
                    value: 1,
                    groupValue: _user.gender,
                    onChanged: (value)=>{setState(()=>{_user.gender=value})},
                  ),
                  Text("Female"),
                  Radio(
                    value: 2,
                    groupValue: _user.gender,
                    onChanged: (value)=>{setState(()=>{_user.gender=value})},
                  ),
                  Text("Rather not to say")
                ],
              ),
              Card(
                child: CalendarDatePicker(initialDate: DateTime(2020), firstDate: DateTime(1990), lastDate: DateTime(2100),
                    onDateChanged:( value)=>{setState(()=>{_user.dob=value})}
                ),
              ),
              Container(
                padding: const EdgeInsets.fromLTRB(0, 50, 0, 20),
                  child: Card(
                    child: Column(
                    children: [
                      CheckboxListTile(title:Text("Comedy"),value: false, onChanged:(value)=>{setState(()=>{_user.prefrenaces=value})}),
                      CheckboxListTile(title:Text("Horrer"),value: false, onChanged:(value)=>{setState(()=>{_user.prefrenaces=value})}),
                      CheckboxListTile(title:Text("Sci-fi"),value: true, onChanged:(value)=>{setState(()=>{_user.prefrenaces=value})}),
                      CheckboxListTile(title:Text("Romantic"),value: false, onChanged:(value)=>{setState(()=>{_user.prefrenaces=value})}),
                      CheckboxListTile(title:Text("Thriller"),value: false, onChanged:(value)=>{setState(()=>{_user.prefrenaces=value})}),
                  ]
                  ),
                  ),
              ),
              RaisedButton(onPressed:() {
                final form=_formKey.currentState;
                if(form.validate()){
                  form.save();
                  print("alex: "+_user.toString());
                  _showDialog(context,_user.toString());
                }
              },
              )
            ],
          ),
        ))));
  }

  @override
  void initState() {
    super.initState();
  }
}

void _showDialog(BuildContext context,String string) {
  Scaffold.of(context).showSnackBar(SnackBar(content: Text(string)));
}
``` 

</details>

**Comment by iapicca** [comment]
@pranimation 
can you provide your `flutter doctor -v` and a **_complete runnable minimal_** code sample (not production code snippet)

**Comment by TahaTesser** [comment]
Hi @pranimation 
Added basic missing class in your code, have no isues when runnig on latest `stable `lfutter
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

final _formKey = GlobalKey<FormState>();
final _user = UserData();

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('Profile')),
        body: Container(
            padding:
                const EdgeInsets.symmetric(vertical: 16.0, horizontal: 16.0),
            child: Builder(
                builder: (context) => Form(
                      key: _formKey,
                      child: SingleChildScrollView(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: [
                            TextFormField(
                              decoration:
                                  InputDecoration(labelText: "First Name"),
                              validator: (value) =>
                                  (value.isEmpty) ? "can not empty" : null,
                              onSaved: (value) => {
                                setState(() => _user.firstName = value),
                              },
                            ),
                            TextFormField(
                              decoration:
                                  InputDecoration(labelText: "Last Name"),
                              onSaved: (value) => {
                                setState(() => _user.lastName = value),
                              },
                              validator: (value) =>
                                  (value.isEmpty) ? "write your name" : null,
                            ),
                            Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Radio(
                                  value: 0,
                                  groupValue: _user.gender,
                                  onChanged: (value) =>
                                      {setState(() => _user.gender = value)},
                                ),
                                Text("Male"),
                                Radio(
                                  value: 1,
                                  groupValue: _user.gender,
                                  onChanged: (value) => {
                                    setState(() => {_user.gender = value})
                                  },
                                ),
                                Text("Female"),
                                Radio(
                                  value: 2,
                                  groupValue: _user.gender,
                                  onChanged: (value) => {
                                    setState(() => {_user.gender = value})
                                  },
                                ),
                                Text("Rather not to say")
                              ],
                            ),
                            Card(
                              child: CalendarDatePicker(
                                  initialDate: DateTime(2020),
                                  firstDate: DateTime(1990),
                                  lastDate: DateTime(2100),
                                  onDateChanged: (value) => {
                                        setState(() => {_user.dob = value})
                                      }),
                            ),
                            Container(
                              padding: const EdgeInsets.fromLTRB(0, 50, 0, 20),
                              child: Card(
                                child: Column(children: [
                                  CheckboxListTile(
                                      title: Text("Comedy"),
                                      value: false,
                                      onChanged: (value) => {
                                            setState(() =>
                                                {_user.prefrenaces = value})
                                          }),
                                  CheckboxListTile(
                                      title: Text("Horrer"),
                                      value: false,
                                      onChanged: (value) => {
                                            setState(() =>
                                                {_user.prefrenaces = value})
                                          }),
                                  CheckboxListTile(
                                      title: Text("Sci-fi"),
                                      value: true,
                                      onChanged: (value) => {
                                            setState(() =>
                                                {_user.prefrenaces = value})
                                          }),
                                  CheckboxListTile(
                                      title: Text("Romantic"),
                                      value: false,
                                      onChanged: (value) => {
                                            setState(() =>
                                                {_user.prefrenaces = value})
                                          }),
                                  CheckboxListTile(
                                      title: Text("Thriller"),
                                      value: false,
                                      onChanged: (value) => {
                                            setState(() =>
                                                {_user.prefrenaces = value})
                                          }),
                                ]),
                              ),
                            ),
                            RaisedButton(
                              onPressed: () {
                                final form = _formKey.currentState;
                                if (form.validate()) {
                                  form.save();
                                  print("alex: " + _user.toString());
                                  _showDialog(context, _user.toString());
                                }
                              },
                            )
                          ],
                        ),
                      ),
                    ))));
  }

  @override
  void initState() {
    super.initState();
  }
}

void _showDialog(BuildContext context, String string) {
  Scaffold.of(context).showSnackBar(SnackBar(content: Text(string)));
}

class UserData {
  String firstName;
  String lastName;
  int gender;
  DateTime dob;
  bool prefrenaces;
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS
      14.2
    • iPhone 12 (mobile)   • BBCEDCF6-A80B-49DC-86EE-C9B542A9AD1B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.

```

</details>

Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
