### ISSUE TITLE
flutter pub get gallery_localizations have error

### ISSUE THREAD

**Issue by liu-jia-hao** [flutter/flutter#71358]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter pub get gallery_localizations

## exception

PackageConfigArgumentError: Invalid argument (root): In package flutter_gen: Not an absolute URI with no query or fragment with a path ending in /: ".dart_tool/flutter_gen/"

```
#0      throwError (package:package_config/src/errors.dart:33:44)
#1      SimplePackage.validate (package:package_config/src/package_config_impl.dart:204:14)
#2      new Package (package:package_config/src/package_config.dart:233:21)
#3      _DefaultPub._updatePackageConfig (package:flutter_tools/src/dart/pub.dart:431:32)
<asynchronous suspension>
#4      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:210:5)
<asynchronous suspension>
#5      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:117:7)
<asynchronous suspension>
#6      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:150:5)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1080:12)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:931:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-TW)
    • Flutter version 1.24.0-10.2.pre at /Users/jiahao/desktop/flutter
    • Framework revision 022b333a08 (10 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jiahao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```

**Comment by Abhishek01039** [comment]
Hello @liu-jia-hao 
There is not any package of this name `gallery_localizations`

**Comment by darshankawar** [comment]
@liu-jia-hao 
As the exception says `PackageConfigArgumentError: Invalid argument (root): In package flutter_gen:`
The issue could be related to the `flutter_gen` plugin you are using, which is 3rd party (https://github.com/FlutterGen/flutter_gen/issues)
Please check your `pubspec.yaml` and the way you are using `flutter_gen` plugin.  
closing from here, as it doesn't seem to be an issue with Flutter. If you disagree, write in comments and I'll reopen it.
