### ISSUE TITLE
CupertinoNavigationBar crashes when setting border to null

### ISSUE THREAD

**Issue by lamtx** [flutter/flutter#71389]
Example main.dart:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: Page1(),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Page 1"),
        border: null,
      ),
      child: Center(
        child: TextButton(
          child: Text("Next"),
          onPressed: () {
            Navigator.of(context)!.push<void>(CupertinoPageRoute(
              builder: (_) => Page2(),
              title: "Page 2",
            ));
          },
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Page 2"),
        border: null,
      ),
      child: Center(
        child: Text("Page 2"),
      ),
    );
  }
}
```

## Steps to Reproduce

1. Connect to iOS simulator and run app.
2. In the first screen, tap "Next"
3. In the second screen, tab "Back"

**Expected results:** No issues and animation works.

**Actual results:** App crashes, related to nnbd.

<details>
  <summary>Logs</summary>

```
The relevant error-causing widget was: 
  CupertinoApp file:///Users/may/Documents/project/me/test_navi/test_navi/lib/main.dart:11:12
When the exception was thrown, this was the stack: 
#0      BorderTween.lerp (package:flutter/src/widgets/implicit_animations.dart:157:54)
#1      Tween.transform (package:flutter/src/animation/tween.dart:281:12)
#2      Animatable.evaluate (package:flutter/src/animation/tween.dart:54:46)
#3      _NavigationBarTransition.build.<anonymous closure> (package:flutter/src/cupertino/nav_bar.dart:1604:33)
#4      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1528:19)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was: 
  CupertinoApp file:///Users/may/Documents/project/me/test_navi/test_navi/lib/main.dart:11:12

```
```
may@Tue test_navi % flutter analyze
Running "flutter pub get" in test_navi...                          490ms
Analyzing test_navi...                                                  
No issues found! (ran in 2.7s)
```
```
may@Tue ~ % flutter doctor -v
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B50 darwin-x64,
    locale en-VN)
    • Flutter version 1.24.0-10.2.pre at /Users/may/Library/Android/flutter
    • Framework revision 022b333a08 (11 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/may/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 6F6715B1-7A64-4D3E-A9C7-12CF410E119F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment]
Reproducible on latest `beta` and `master` channel.

```
Performing hot reload...
Syncing files to device sdk gphone x86 arm...
Reloaded 1 of 536 libraries in 923ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _CastError was thrown building AnimatedBuilder(animation: AnimationController#7cb73(▶ 0.750; for CupertinoPageRoute<void>(null))➩ProxyAnimation➩Cubic(0.40, 0.00, 0.20, 1.00)ₒₙ/FlippedCurve(Cubic(0.40, 0.00, 0.20, 1.00)), dirty, state: _AnimatedState#6be3b):
Null check operator used on a null value


The relevant error-causing widget was: 
  CupertinoApp file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:11:12
When the exception was thrown, this was the stack: 
#0      BorderTween.lerp (package:flutter/src/widgets/implicit_animations.dart:157:54)
#1      Tween.transform (package:flutter/src/animation/tween.dart:281:12)
#2      Animatable.evaluate (package:flutter/src/animation/tween.dart:54:46)
#3      _NavigationBarTransition.build.<anonymous closure> (package:flutter/src/cupertino/nav_bar.dart:1604:33)
#4      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1528:19)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

<details><summary>flutter doctor -v (master)</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-8.0.pre.374 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 183f0e797a (4 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.24.0-10.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 022b333a08 (12 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```
</details>

**Comment by adarsh-technocrat** [comment]
Hi, @lamtx   I'm new to open source contribution and I really want to work on this issue can you please guide me to this issue so that I can land my first PR.

**Comment by lamtx** [comment]
> Hi, @lamtx I'm new to open source contribution and I really want to work on this issue can you please guide me to this issue so that I can land my first PR.

@adarsh-technocrat, I'm new to that too, I hope someone can help you.

**Comment by Plegizplegiz** [comment]
su 6.12.2020 klo 13.13 lamtx <notifications@github.com> kirjoitti:

**Comment by DanielEdrisian** [comment]
Hi @adarsh-technocrat! Here are some steps:

1. Fork the Flutter repository
2. Create a branch for the fix (something like `cupertino-nav-bar-border-fix`)
3. Make the necessary changes
4. Push to your branch
5. Open a PR to merge into flutter/flutter/master
6. Follow some of the steps in the PR to make sure you're able to merge (like signing the CLA)
7. Request reviews from one of us (@xster @LongCatIsLooong just to name a few)

Thanks for contributing :)

**Comment by adarsh-technocrat** [comment]
Thanks, @DanielEdrisian  for guiding me just have one doubt to clear does it make any difference to the cloned repo if I will be using the stable flutter channel or I have to use another channel to do so.

Thanks for helping :)

**Comment by DanielEdrisian** [comment]
Just use `master` @adarsh-technocrat

**Comment by adarsh-technocrat** [comment]
Thank you @DanielEdrisian

**Comment by chachaxw** [comment]
I have the same issue, please fix it, thanks!

**Comment by MrBirb** [comment]
You can use `const Border()` instead of `null`.

**Comment by Hixie** [comment]
cc @xster

**Comment by HansMuller** [comment]
I believe that https://github.com/flutter/flutter/pull/73992 fixes the problem reported here. However, the sample app runs into another bug https://github.com/flutter/flutter/issues/73956. Fortunately a separate fix for that should be ready shortly: https://github.com/flutter/flutter/pull/73993.
