### ISSUE TITLE
flutter screenshot --type=skia[no work]

### ISSUE THREAD

**Issue by azhansy** [flutter/flutter#71398]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter screenshot --type=skia --observatory-uri= http://127.0.0.1:49257/phC5T1gWW5E=/

## exception

ArgumentError: Invalid argument(s): No host specified in URI http://:0/ws

```
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2407:9)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2323:7)
#2      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1025:24)
#3      WebSocket.connect (dart:_http/websocket.dart:379:22)
#4      _defaultOpenChannel (package:flutter_tools/src/vmservice.dart:136:33)
#5      _connect (package:flutter_tools/src/vmservice.dart:354:50)
#6      connectToVmService (package:flutter_tools/src/vmservice.dart:330:19)
#7      ScreenshotCommand.runSkia (package:flutter_tools/src/commands/screenshot.dart:130:50)
#8      ScreenshotCommand.runCommand (package:flutter_tools/src/commands/screenshot.dart:104:15)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale zh-Hans-KH)
    • Flutter version 1.22.2 at /Users/shu/company/flutter/flutter
    • Framework revision 84f3d28555 (6 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/shu/company/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/shu/company/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • SM T835 (mobile) • ce041824a273448b0d7e • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```
----------
I have install Flutter plugin and Dart plugin

**Comment by jmagman** [comment]
The flag should be `--observatory-uri=http://127.0.0.1:49257/phC5T1gWW5E=/` without the space in between or `--observatory-uri http://127.0.0.1:49257/phC5T1gWW5E=/` without the `=`.

**Comment by azhansy** [comment]
When I removed the space, another exception occurred.

**Comment by azhansy** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter screenshot --type=skia --observatory-uri=http://127.0.0.1:50688/4ACueuOhA04=/

## exception

RPCError: _flutter.screenshotSkp: (-32000) Could not capture SKP screenshot.

```
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale zh-Hans-KH)
    • Flutter version 1.22.2 at /Users/shu/company/flutter/flutter
    • Framework revision 84f3d28555 (7 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/shu/company/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/shu/company/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • SM T835 (mobile) • ce041824a273448b0d7e • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by jmagman** [comment]
@azhansy Can you file a new issue for that?  I'm about to close the original report with https://github.com/flutter/flutter/pull/71451 but I'd like someone on the engine team to take a look at the second error.

**Comment by azhansy** [comment]
> @azhansy Can you file a new issue for that? I'm about to close the original report with #71451 but I'd like someone on the engine team to take a look at the second error.

OK thanks
