### ISSUE TITLE
[video_player] Remove iOS simulator support warning from documentation

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#71403]
Remove the following warning from https://pub.dev/packages/video_player#installation when the fix lands in flutter's stable channel.  Currently, this is only working on `master` for me. 
```bash
iOS 
Warning: The video player is not functional on iOS simulators. An iOS device must be used during development/testing.
```

Reference -> https://github.com/flutter/flutter/issues/14647#issuecomment-706323442

**Comment by Sunbreak** [comment]
> Currently, this is only working on `master` for me.

According to https://github.com/flutter/flutter/issues/14647#issuecomment-706323442, it is available since flutter-1.23.0-18.1.pre. It should be working on `dev` and `beta` now

**Comment by TahaTesser** [comment]
@Sunbreak 
You're probably, what I meant was I am running into another issue when trying on dev and beta https://github.com/flutter/flutter/issues/70895#issuecomment-735754545

**Comment by jeremiahlukus** [comment]
I am unable to get a video to to on android simulator now. 
i copy pasted the video_player example 
on android i get 


```
I/ExoPlayerImpl( 3419): Init 268247d [ExoPlayerLib/2.12.1] [generic_x86_arm, AOSP on IA Emulator, Google, 28]
E/ExoPlayerImplInternal( 3419): Playback error
E/ExoPlayerImplInternal( 3419):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal( 3419):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 3419):       at android.os.Looper.loop(Looper.java:193)
E/ExoPlayerImplInternal( 3419):       at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal( 3419):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:309)
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 3419):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 3419):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 3419):       at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal( 3419):   Caused by: java.io.IOException: Cleartext HTTP traffic to www.sample-videos.com not permitted
E/ExoPlayerImplInternal( 3419):       at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
E/ExoPlayerImplInternal( 3419):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
E/ExoPlayerImplInternal( 3419):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:589)
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:493)
E/ExoPlayerImplInternal( 3419):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:307)
E/ExoPlayerImplInternal( 3419):       ... 6 more
E/flutter ( 3419): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter ( 3419): 
```


```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
[✓] VS Code (version 1.49.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by ventr1x** [comment]
Should it actually work though? I just tested it with 1.26.beta and it is clearly just showing black screen (working on device).

**Comment by jeremiahlukus** [comment]
Its working on my simulator iPhone 12 max

**Comment by jeremiahlukus** [comment]
its no longer working for me ha

**Comment by nt4f04uNd** [comment]
it is not the case for me on latest master

**Comment by balvinderz** [comment]
@TahaTesser  this can be closed now as https://github.com/flutter/plugins/pull/4241 is merged
