### ISSUE TITLE
[cocoon] Benchmarks are not loading on the dashboard

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#71427]
https://flutter-dashboard.appspot.com/benchmarks.html

After about an hour now, the benchmarks are not loading. Checked on two machines.

Console logged an error:

```
Uncaught Invalid argument(s): No provider found for minified:Gs
    at Object.a (https://flutter-dashboard.appspot.com/benchmarks.dart.js:387:3)
    at Object.FJ (https://flutter-dashboard.appspot.com/benchmarks.dart.js:4542:26)
    at jM.bt (https://flutter-dashboard.appspot.com/benchmarks.dart.js:11045:21)
    at jM.b3 (https://flutter-dashboard.appspot.com/benchmarks.dart.js:11047:30)
    at uY.$0 (https://flutter-dashboard.appspot.com/benchmarks.dart.js:10283:19)
    at qy.$0 (https://flutter-dashboard.appspot.com/benchmarks.dart.js:10989:14)
    at kH.uH [as $1$4] (https://flutter-dashboard.appspot.com/benchmarks.dart.js:1937:9)
    at dN.iX (https://flutter-dashboard.appspot.com/benchmarks.dart.js:10951:12)
    at Object.eval (eval at x8 (https://flutter-dashboard.appspot.com/benchmarks.dart.js:524:8), <anonymous>:3:43)
    at ly.al (https://flutter-dashboard.appspot.com/benchmarks.dart.js:7596:12)
```

**Comment by CaseyHillers** [comment]
I'm not familiar with the Angular dashboard. Do we know when this regression started to occur?

We tend to have to lock pub dependencies in `app/pubspec.yaml` when there are updates to the pub packages used.

**Comment by keyonghan** [comment]
The benchmark page failed to load starting from Nov. 18. Searched around surrounding PRs, and this one might be related: https://github.com/flutter/cocoon/pull/1005?

**Comment by CaseyHillers** [comment]
Thanks Keyong! This looks to be with changes to the dart model files. I'll reland those changes.

**Comment by CaseyHillers** [comment]
The issue is with the entry point to the Angular Components. There was some modifications for NNBD in app/web/benchmarks.dart that need to be fixed. I'm testing the changes now and will see if they can pass Cocoon CI.
