### ISSUE TITLE
Several infra agents are red

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#71426]
12 infra agents are red and not running tasks. 

https://flutter-dashboard.appspot.com/#/agents

The build dashboard shows tasks have been queued on these devices for 6+ hours.

**Comment by yusufm** [comment]
```
cocoon-authentication: succeeded
cocoon-connection: succeeded
remove-xcode-derived-data: succeeded
remove-cached-data: succeeded
close-ios-dialog: failed
    ERROR: Command "xcrun xcodebuild -project infra-dialog..." failed with exit code 65.
    #0      fail (package:cocoon_agent/src/utils.dart:139:3)
    #1      closeIosDialog.<anonymous closure> (package:cocoon_agent/src/health.dart:189:9)
    <asynchronous suspension>
    #2      closeIosDialog.<anonymous closure> (package:cocoon_agent/src/health.dart)
    #3      inDirectory (package:cocoon_agent/src/utils.dart:366:24)
    <asynchronous suspension>
    #4      closeIosDialog (package:cocoon_agent/src/health.dart:170:11)
    <asynchronous suspension>
    #5      _captureErrors (package:cocoon_agent/src/health.dart:68:47)
    <asynchronous suspension>
    #6      performHealthChecks.<anonymous closure> (package:cocoon_agent/src/health.dart:49:41)
    <asynchronous suspension>
    #7      performHealthChecks.<anonymous closure> (package:cocoon_agent/src/health.dart)
    #8      _captureErrors (package:cocoon_agent/src/health.dart:68:47)
    <asynchronous suspension>
    #9      performHealthChecks (package:cocoon_agent/src/health.dart:25:51)
    <asynchronous suspension>
    #10     ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:78:26)
    <asynchronous suspension>
    #11     ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart)
    #12     _rootRun (dart:async/zone.dart:1190:13)
    #13     _CustomZone.run (dart:async/zone.dart:1093:19)
    #14     _runZoned (dart:async/zone.dart:1630:10)
    #15     runZonedGuarded (dart:async/zone.dart:1618:12)
    #16     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
    <asynchronous suspension>
    #17     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:61:19)
    #18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
    #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by yusufm** [comment]
Likely related to #71414

**Comment by Piinks** [comment]
This has been resolved.
