### ISSUE TITLE
Problem with Cached Image Network

### ISSUE THREAD

**Issue by bachtiyar93** [flutter/flutter#71461]
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building FadeWidget(dependencies: [_EffectiveTickerMode], state: _FadeWidgetState#4cd24(ticker inactive)):
'package:flutter/src/rendering/object.dart': Failed assertion: line 1288 pos 12: '_debugCanPerformMutations': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  FadeWidget file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/octo_image-0.3.0/lib/src/image.dart:369:9
When the exception was thrown, this was the stack: 
#2      RenderObject.dropChild (package:flutter/src/rendering/object.dart:1288:12)
#3      ContainerRenderObjectMixin.remove (package:flutter/src/rendering/object.dart:3250:5)
#4      MultiChildRenderObjectElement.removeRenderObjectChild (package:flutter/src/widgets/framework.dart:6210:18)
#5      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:5814:36)
#6      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3604:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Object has been disposed.
The relevant error-causing widget was: 
  OctoImage file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.4.0/lib/src/cached_image_widget.dart:256:12
```

**Comment by darshankawar** [comment]
@bachtiyar93 
From the log you shared, I see below:

`octo_image-0.3.0/lib/src/image.dart:369:9` and

`OctoImage file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.4.0/lib/src/cached_image_widget.dart:256:12` 

Both these plugins are 3rd party. I'd recommend you to open this issue in respective plugin owner's repo:

https://github.com/Baseflow/flutter_cached_network_image/issues
https://pub.dev/packages/octo_image

Closing from here, as it doesn't seem to be an issue with Flutter framework, but with the plugins you are using as stated above. If you disagree or think the exception is causing due to core Flutter framework, write in comments and I'll reopen it.
Thanks.
