### ISSUE TITLE
ArgumentError: Invalid argument(s): Cannot find executable for C:\flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by isabelSoares** [flutter/flutter#71471]
## Command
```
flutter run --machine --target lib\main.dart -d emulator-5554 --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. control + F5

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\flutter\bin\cache\dart-sdk\bin\pub.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:496:35)
#7      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:295:34)
<asynchronous suspension>
#8      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:219:15)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:954:17)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.662], locale pt-PT)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\isabe\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\isabe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 84f3d28555368a70270e9ac8390a9441df95e752

**Comment by hello-addweb** [comment]
As i see in the above flutter and dart plugin is not installed properly, so please install it first.
Below the steps of the both plugin installation : 

1. Just install plugins.
2. Studio>>File>Settings>Plugins>Browse Repositories
3. Search for flutter.
4. Tap on Install (a dialog will pop regarding dart dependency. click Yes).
5. Once the installation is finished restart android studio.
6. Now run flutter doctor.

**Comment by darshankawar** [comment]
@isabelSoares 
There's similar open issue describing your case, [60880](https://github.com/flutter/flutter/issues/60880).
Please follow-up there for updates.
Closing this as duplicate.

**Comment by isabelSoares** [comment]
> As i see in the above flutter and dart plugin is not installed properly, so please install it first.
> 
> Below the steps of the both plugin installation : 
> 
> 
> 
> 1. Just install plugins.
> 
> 2. Studio>>File>Settings>Plugins>Browse Repositories
> 
> 3. Search for flutter.
> 
> 4. Tap on Install (a dialog will pop regarding dart dependency. click Yes).
> 
> 5. Once the installation is finished restart android studio.
> 
> 6. Now run flutter doctor.

I made this but I continue to have the same error! I tried to uninstall and install Dart-sdk and it didn't work

**Comment by isabelSoares** [comment]
> @isabelSoares 
> 
> There's similar open issue describing your case, [60880](https://github.com/flutter/flutter/issues/60880).
> 
> Please follow-up there for updates.
> 
> Closing this as duplicate.
> 
> 

I saw this but I continue with the error !
