### ISSUE TITLE
plugin - video_player task error in Android when use network url.

### ISSUE THREAD

**Issue by yukilzw** [flutter/flutter#71485]
flutter version: 1.22
 video_player version: 1.0.1

the network video is working on IOS platform.
but when i build android, It shows error.
```
E/ExoPlayerImplInternal( 8027): Playback error
E/ExoPlayerImplInternal( 8027):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 8027):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal( 8027):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 8027):       at android.os.Looper.loop(Looper.java:237)
E/ExoPlayerImplInternal( 8027):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 8027):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal( 8027):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:309)
E/ExoPlayerImplInternal( 8027):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 8027):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
E/ExoPlayerImplInternal( 8027):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 8027):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 8027):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 8027):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal( 8027):   Caused by: java.io.IOException: Cleartext HTTP traffic to 192.168.97.142 not permitted
E/ExoPlayerImplInternal( 8027):       at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
E/ExoPlayerImplInternal( 8027):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:480)
E/ExoPlayerImplInternal( 8027):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:135)
E/ExoPlayerImplInternal( 8027):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:589)
E/ExoPlayerImplInternal( 8027):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:493)
E/ExoPlayerImplInternal( 8027):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:307)
E/ExoPlayerImplInternal( 8027):       ... 6 more
I/flutter ( 8027): PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
I/ViewRootImpl@9c30e0d[MainActivity]( 8027): ViewPostIme key 0
I/ViewRootImpl@9c30e0d[MainActivity]( 8027): ViewPostIme key 1
```
I try to change another network video, but it's all the same.
And when i bundle local video by`VideoPlayerController.asset` rather than VideoPlayerController.`network`, it will be usefull.

**Comment by trantrongkim98** [comment]
go to AndroidManifest xml, it will help you

**Comment by yukilzw** [comment]
it is resolved, thanks
