### ISSUE TITLE
Exception caught by rendering library 

### ISSUE THREAD

**Issue by maxZhou7** [flutter/flutter#71530]
使用CachedNetworkImage的时候出现以下异常信息。
相关代码：
```
```
CachedNetworkImage(
                                    key: ValueKey<String>(dataList[index]['id'].toString()),
                                    imageUrl: dataList[index]['picUrl'],
                                    // width: 40,
                                    // height: 40,
                                    fit: BoxFit.cover,
                                    placeholder: (context, url) =>
                                        CircularProgressIndicator(),
                                    errorWidget: (context, url, error) =>
                                        Icon(Icons.error),
                                  ),
                                  // Image(
                                  //   image:
                                  //       NetworkImage(dataList[index]['picUrl']),
                                  //   width: 40,
                                  //   fit: BoxFit.contain,
                                  // ),
```
直接用Image就没有问题 换成CachedNetworkImage就出错了。求解~

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following message was thrown during performLayout():
Object has been disposed.

The relevant error-causing widget was: 
  ClipRRect file:///D:/flutterworkplace/sxt_music/lib/routes/Songlist.dart:66:33
When the exception was thrown, this was the stack: 
#0      Image.width (dart:ui/painting.dart:1586:37)
#1      Image.toString (dart:ui/painting.dart:1614:27)
#2      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2741:60)
#3      DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2755:21)
#4      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1567:24)
...
The following RenderObject was being processed when the exception was fired: RenderClipRRect#b031e relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.1, 0.1) (can use size)
...  constraints: BoxConstraints(0.0<=w<=Infinity, h=39.8)
...  size: Size(36.0, 39.8)
RenderObject: RenderClipRRect#b031e relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.1, 0.1) (can use size)
  constraints: BoxConstraints(0.0<=w<=Infinity, h=39.8)
  size: Size(36.0, 39.8)
...  child: RenderConstrainedBox#cff0d relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=39.8)
...    size: Size(36.0, 39.8)
...    additionalConstraints: BoxConstraints(unconstrained)
...    child: RenderStack#dadfd relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=Infinity, h=39.8)
...      size: MISSING
...      alignment: center
...      textDirection: ltr
...      fit: passthrough
...      child 1: RenderAnimatedOpacity#c014e relayoutBoundary=up19 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, h=39.8)
...        size: MISSING
...        opacity: AnimationController#68aff(▶ 0.000)➩Cubic(0.42, 0.00, 1.00, 1.00)➩Tween<double>(0.0 → 1.0)➩0.0
...        child: RenderSemanticsAnnotations#2ec60 relayoutBoundary=up20 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, h=39.8)
...          size: MISSING
...      child 2: RenderAnimatedOpacity#de187 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: not positioned; offset=Offset(0.0, 0.0)
...        constraints: MISSING
...        size: MISSING
...        opacity: AnimationController#35a31(▶ 0.000)➩Cubic(0.00, 0.00, 0.58, 1.00)➩Tween<double>(1.0 → 0.0)➩1.0
...        child: RenderSemanticsAnnotations#769ba NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
The following message was thrown during a service extension callback for "ext.flutter.inspector.getChildrenDetailsSubtree":
Object has been disposed.

When the exception was thrown, this was the stack: 
#0      Image.width (dart:ui/painting.dart:1586:37)
#1      Image.toString (dart:ui/painting.dart:1614:27)
#2      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2741:60)
#3      DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2755:21)
#4      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1567:24)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building FadeWidget(dependencies: [_EffectiveTickerMode], state: _FadeWidgetState#9e456(ticker inactive)):
'package:flutter/src/rendering/object.dart': Failed assertion: line 1288 pos 12: '_debugCanPerformMutations': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CachedNetworkImage-[<'1498342485'>] file:///D:/flutterworkplace/sxt_music/lib/routes/Songlist.dart:79:35
When the exception was thrown, this was the stack: 
#2      RenderObject.dropChild (package:flutter/src/rendering/object.dart:1288:12)
#3      ContainerRenderObjectMixin.remove (package:flutter/src/rendering/object.dart:3250:5)
#4      MultiChildRenderObjectElement.removeRenderObjectChild (package:flutter/src/widgets/framework.dart:6210:18)
#5      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:5814:36)
#6      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3604:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by darshankawar** [comment]
@maxZhou7 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
