### ISSUE TITLE
"The relevant error-causing widget" misleads when the exception is thrown from user code

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#71593]
Steps to reproduce:
1. `flutter create dummy`
2. `cd dummy`
3. `nano lib/main.dart`
4. add a `throw 'hello';` statement on line 64, the first line of the `_MyHomePageState.build` method.
5. save and quit the editor
6. `flutter test`

Expected results:
Exception is reported, pointing clearly to line 64.

Actual results:
Exception is reported, but before the stack trace it first points you to line 25, where the MyHomePage widget is instantiated.

**Comment by Hixie** [comment]
cc @jacob314 @InMatrix

**Comment by pedromassangocode** [comment]
<details><summary>Logs</summary>

```
00:12 +0: Counter increments smoke test                                        
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following message was thrown building MyHomePage(dirty, state: _MyHomePageState#4c0f7):
hello

The relevant error-causing widget was:
  MyHomePage file:///Users/pedromassango/Desktop/appx/lib/main.dart:29:13

When the exception was thrown, this was the stack:
#0      _MyHomePageState.build (package:appx/main.dart:68:5)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
...     Normal element mounting (132 frames)
#139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#140    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
...     Normal element mounting (273 frames)
#413    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#414    Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
#415    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1252:16)
#416    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1230:5)
#417    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1244:7)
#418    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#419    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#420    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1088:18)
#421    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#422    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#423    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#424    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:961:9)
#427    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#428    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:948:27)
#429    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:524:22)
#432    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#433    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:521:27)
#434    main.<anonymous closure> (file:///Users/pedromassango/Desktop/appx/test/widget_test.dart:16:18)
#435    main.<anonymous closure> (file:///Users/pedromassango/Desktop/appx/test/widget_test.dart:14:48)
#436    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
#447    FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:193:32)
#448    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1189:17)
#449    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1177:35)
(elided 29 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "0" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/pedromassango/Desktop/appx/test/widget_test.dart:19:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///Users/pedromassango/Desktop/appx/test/widget_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#18     withClock (package:clock/src/default.dart:48:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#34     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#39     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#47     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#48     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#55     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#56     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#57     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#62     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#63     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#81     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#82     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#86     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#120    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#128    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#129    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#139    _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#148    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#149    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
(elided 111 frames from dart:async and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/pedromassango/Desktop/appx/test/widget_test.dart line 19
The test description was:
  Counter increments smoke test
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:12 +0 -1: Counter increments smoke test [E]                                 
  Test failed. See exception logs above.
  The test description was: Counter increments smoke test
  
00:12 +0 -1: Some tests failed.          
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    en)
    • Flutter version 1.22.4 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
</details>

**Comment by Hixie** [comment]
Another example would be when you have an exception thrown by a CustomPainter -- it points to the CustomPaint widget in the build method of the widget that is using the custom painter as the "error-causing widget".

I don't know what the solution is. Consider this error message and stack trace:

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during paint():
flutter: 'dart:ui/painting.dart': Failed assertion: line 1147: '<optimized out>': is not true.
flutter: 
flutter: The relevant error-causing widget was:
flutter:   CustomPaint file:///home/ianh/dev/house-of-rooves/laundry_room_console/lib/main.dart:552:12
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      Paint.color= (dart:ui/painting.dart:1147:12)
flutter: #3      WasherPainter.paint (package:laundry_room_console/main.dart:636:11)
flutter: #4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:531:13)
flutter: #5      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:572:7)
flutter: #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #8      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
flutter: #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
flutter: #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
...
```

The first stack frame isn't user code, the third stack frame isn't user code, none of the stack frames are widget-related... and yet the programming error is in user code.

**Comment by InMatrix** [comment]
> Exception is reported, but before the stack trace it first points you to line 25, where the MyHomePage widget is instantiated.

This isn't very useful but it's not wrong though. The error causing widget is `MyHomePage`, since the error was originated from its `build` method. The fact that the `build` method is on the widget's `State` object certainly made the message less useful. FWIW, the separation of `StatefulWidget` from its `build` method is a common point of confusion documented [elsewhere](https://github.com/flutter/flutter/issues/8794). 

In this specific case, calling out Line 64 is certainly better, but I suspect this is actually less helpful in real world encounters with Flutter errors where the point of breakdown (e.g., a violation of layout constraints) is rarely where the original cause of the problem is (e.g., user didn't wrap things in an Expanded).

**Comment by Hixie** [comment]
Both examples here came from "real world encounters". The first caused severe confusion in a developer with a few months of experience, the second caused mild confusion for me until I studied the stack trace carefully.

**Comment by jacob314** [comment]
This is related to work @devoncarew is looking at to enable pausing on some caught exceptions in Flutter as if they were uncaught exceptions. For both the examples given, what you would ideally want is to pause in a debugger on the first stack frame from user code when the exception occurred so you could use a debugger to fix the logic error in the code you wrote.

We should also fix the error message to emphasize the stack trace before the "error-causing widget" when we detect the exception was thrown from user code.  We should also revisit whether "error-causing widget" is ever the best terminology as we really only mean we have the location of the local widget that is directly or indirectly experiencing a problem. Even for cases where the "error-experiencing-widget" location is highly relevant like forgetting to wrap a widget with `Expanded` the fix is often not to change the `error-causing-widget` but to wrap it with another widget to resolve the problem. 

If the exception was not thrown by user code (either directly or indirectly) then emphasizing the "error experiencing widget" is preferable to emphasizing the stack trace as it gives users a breadcrumb of where to go in their code to resolve the error instead of directing them to code deep within the framework that is bug free.

### How to determine if the exception was thrown from user code or in the framework.

Proposed heuristic:
Walk the stack trace stopping if we reach a frame from the local project or reach a stack frame that suggest the stack trace is now dealing with a different widget. If none of the first N (maybe 20) stack frames are from the local project assume the stack trace if from the framework even if we have not found a stack trace frame that indicates we are dealing with a different widget.

Advanced version (probably not needed): use the Dart VM Service apis to inspect what the `this` object is at each frame in the stacktrace to stop walking the stack trace if we ever reach a `this` object that does not have the same widget from the local project as the `error experiencing widget`.

**Comment by InMatrix** [comment]
I agree it's useful to make a distinction between exceptions thrown by user code and exceptions thrown by the framework.

**Comment by danagbemava-nc** [comment]
Reproducible on the latest versions of flutter using the steps outlined in https://github.com/flutter/flutter/issues/71593#issue-755548757. 

<details>
<summary>logs</summary>

```
00:07 +0: Counter increments smoke test
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following message was thrown building MyHomePage(dirty, state: _MyHomePageState#f3c82):
hello

The relevant error-causing widget was:
  MyHomePage MyHomePage:file:///Users/nexus/projects/nevercode/dummy/lib/main.dart:34:19

When the exception was thrown, this was the stack:
#0      _MyHomePageState.build (package:dummy/main.dart:73:2)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:5094:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4982:15)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5147:11)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4964:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5138:11)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4958:5)
...     Normal element mounting (220 frames)
#227    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
#228    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6520:36)
#229    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6532:32)
...     Normal element mounting (441 frames)
#670    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3964:16)
#671    Element.updateChild (package:flutter/src/widgets/framework.dart:3695:20)
#672    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5007:16)
#673    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
#674    ProxyElement.update (package:flutter/src/widgets/framework.dart:5313:5)
#675    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
#676    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5007:16)
#677    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5147:11)
#678    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
#679    StatefulElement.update (package:flutter/src/widgets/framework.dart:5170:5)
#680    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
#681    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5007:16)
#682    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
#683    ProxyElement.update (package:flutter/src/widgets/framework.dart:5313:5)
#684    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
#685    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5007:16)
#686    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
#687    StatelessElement.update (package:flutter/src/widgets/framework.dart:5058:5)
#688    Element.updateChild (package:flutter/src/widgets/framework.dart:3679:15)
#689    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1194:16)
#690    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1171:5)
#691    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1185:7)
#692    Element.rebuild (package:flutter/src/widgets/framework.dart:4701:7)
#693    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2773:19)
#694    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1349:19)
#695    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#696    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1286:15)
#697    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1216:9)
#698    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1199:9)
#701    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#702    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1185:27)
#703    WidgetTester._pumpWidget (package:flutter_test/src/widget_tester.dart:592:20)
#704    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:577:14)
#707    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#708    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:576:27)
#709    main.<anonymous closure> (file:///Users/nexus/projects/nevercode/dummy/test/widget_test.dart:16:18)
#710    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "0" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/nexus/projects/nevercode/dummy/test/widget_test.dart:19:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/nexus/projects/nevercode/dummy/test/widget_test.dart line 19
The test description was:
  Counter increments smoke test
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:07 +0 -1: Counter increments smoke test [E]
  Test failed. See exception logs above.
  The test description was: Counter increments smoke test


To run this test again: /Users/nexus/dev/sdks/flutters/bin/cache/dart-sdk/bin/dart test /Users/nexus/projects/nevercode/dummy/test/widget_test.dart -p vm --plain-name 'Counter increments smoke test'
00:07 +0 -1: Some tests failed.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.7 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.9.0-9.0.pre.32, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.9.0-9.0.pre.32 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 53dfd23b04 (5 hours ago), 2023-03-17 01:59:19 -0400
    • Engine revision d9e65441ea
    • Dart version 3.0.0 (build 3.0.0-339.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>
