### ISSUE TITLE
[pigeon] crash  when trying to use a List type 

### ISSUE THREAD

**Issue by fccaikai** [flutter/flutter#71649]
## Steps to Reproduce

when use pigeon generator platform code .  pigeon code like :

```

class App {
  int appId; 
  String icon; 
  String name;
}

class Apps{
// is supported ???
 List App;
}

class AppResult{
  int code;
  String errorMsg;
}

@FlutterApi()
abstract class FlutterAppApi{
  void editFavouriteApps(Apps apps);
}

@HostApi()
abstract class HostApi{
  AppResult addFavouriteApp(App app);
}
```

when I call dart method from Anroid platform , the app carsh

```
class EditAppActivity : FlutterActivity() {
       //....

     override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        val apps = Apps()
        apps.apps = ArrayList<App>().apply {
            add(App(1,"title","icon"))
        }

        AppApi.HostApi.setup(flutterEngine.dartExecutor, HostApiHandler())
        //crash by this 
        AppApi.FlutterAppApi(flutterEngine.dartExecutor).editFavouriteApps(app){

        }
    }
}
```

#### question

Whether pigeon only supports basic data types （when usage List type）？

#### Logs

```

 Caused by: java.lang.IllegalArgumentException: Unsupported value: com.demo.test.flutter_oa.$App@97a58e8
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:278)
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:267)
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:275)
        at io.flutter.plugin.common.StandardMessageCodec.encodeMessage(StandardMessageCodec.java:72)
        at io.flutter.plugin.common.BasicMessageChannel.send(BasicMessageChannel.java:87)
        atcom.demo.test..flutter.test.AppApi$FlutterAppApi.editFavouriteApps(AppApi.java:161)
        at com.demo.flutteradd.EditAppActivity.configureFlutterEngine(EditAppActivity.kt:44)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:181)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)

```

------

#### Pigeon

version 0.1.16

#### flutter doctor

```
➜  AndroidStudioProjects flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G73 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 1.22.4 at /Users/caikai/caikai/dev/flutter
    • Framework revision 1aafb3a8b9 (3 周前), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/caikai/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • M2003J15SC (mobile) • 0300a2960404 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

</details>

**Comment by iapicca** [comment]
as requested in [pigeon feedback](https://pub.dev/packages/pigeon#feedback) cc @gaaclarke

**Comment by gaaclarke** [comment]
Yep, all the rules that apply to [Platform Channels](https://flutter.dev/docs/development/platform-integration/platform-channels) applies here.  The encoder for Lists and Maps is recursive so it can only contain datatypes that themselves are supported.  Otherwise, there is no defined way to serialize the data when sending it between the host and Flutter.
