### ISSUE TITLE
Unable to run Flutter app with local engine. 

### ISSUE THREAD

**Issue by sohanjg** [flutter/flutter#71672]
This is on ToT, trying to build a local engine and run simple Hello app.

I am following steps here, https://github.com/flutter/flutter/wiki/Compiling-the-engine and https://github.com/flutter/flutter/wiki/Debugging-the-engine 

$ flutter run --verbose --local-engine-src-path <path> --local-engine=android_debug_unopt_arm64

Error snippet : 
Following are the verbose error logging,

```
[ +901 ms] [+2749 ms] "flutter bundle" took 3,111ms.
[        ] Compiler failed on /home/sohan/Flutter_Eng_OS/hello/lib/main.dart
[        ] #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
[        ] #1      BundleBuilder.build (package:flutter_tools/src/bundle.dart:98:9)
[        ] <asynchronous suspension>
[        ] #2      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:119:25)
[        ] <asynchronous suspension>
[        ] #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
[        ] <asynchronous suspension>
[        ] #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
[        ] <asynchronous suspension>
[        ] #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
[        ] <asynchronous suspension>
[        ] #6      _rootRun (dart:async/zone.dart:1124:13)
[        ] #7      _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #8      _runZoned (dart:async/zone.dart:1516:10)
[        ] #9      runZoned (dart:async/zone.dart:1463:12)
[        ] #10     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
[        ] <asynchronous suspension>
[        ] #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
[        ] #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
[        ] <asynchronous suspension>
[        ] #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
[        ] <asynchronous suspension>
[        ] #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
[        ] <asynchronous suspension>
[        ] #15     _rootRun (dart:async/zone.dart:1124:13)
[        ] #16     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #17     _runZoned (dart:async/zone.dart:1516:10)
[        ] #18     runZoned (dart:async/zone.dart:1463:12)
[        ] #19     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
[        ] <asynchronous suspension>
[        ] #20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
[        ] <asynchronous suspension>
[        ] #21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
[        ] #22     new Future.sync (dart:async/future.dart:224:31)
[        ] #23     CommandRunner.run (package:args/command_runner.dart:112:14)
[        ] #24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
[        ] #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
[        ] <asynchronous suspension>
[        ] #26     _rootRun (dart:async/zone.dart:1124:13)
[        ] #27     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #28     _runZoned (dart:async/zone.dart:1516:10)
[        ] #29     runZoned (dart:async/zone.dart:1500:12)
[        ] #30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
[        ] <asynchronous suspension>
[        ] #31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
[        ] <asynchronous suspension>
[        ] #32     _rootRun (dart:async/zone.dart:1124:13)
[        ] #33     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #34     _runZoned (dart:async/zone.dart:1516:10)
[        ] #35     runZoned (dart:async/zone.dart:1463:12)
[        ] #36     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
[        ] <asynchronous suspension>
[        ] #37     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
[        ] <asynchronous suspension>
[        ] #38     run (package:flutter_tools/runner.dart:50:10)
[        ] #39     main (package:flutter_tools/executable.dart:65:9)
[        ] <asynchronous suspension>
[        ] #40     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
[        ] #41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
[        ] #42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[+2689 ms] > Task :app:compileFlutterBuildDebugArm64 FAILED
[        ] 1 actionable task: 1 executed
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/home/sohan/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 765
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebugArm64'.
[        ] > Process 'command '/home/sohan/Flutter/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 6s
[ +345 ms] Running Gradle task 'assembleDebug'... (completed in 7.2s)
[   +2 ms] "flutter run" took 9,611ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:494:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:486:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#28     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```
The engine build goes fine and generates all the out/ primitives. But the Hello App doesnt run with the above error.

Is this broken now ? Or I am missing something ?

**Comment by TahaTesser** [comment]
Hi @sohanjg 
What device are you trying on the local engine? Can you please provide device details and make sure it matches the architecture you're compiling the engine for?
Thank you

**Comment by sohanjg** [comment]
Hi Tahaesser@, I am trying on a Pixel 3 XL device, and building arm 64 binaries corresponding to it. Saying that I did try building and trying `android_debug_unopt` too, but that fails as well. I have tried in other devices too (Samsung Galaxy S9, Huawei Mate 20 etc.)
I also had to build the target, `host_debug_unopt`, seems that is needed as well for the dart things (wasn't very clear in the documentation, though). 
Also if i do not give the ` --local-engine-src-path` to my src/ folder it seems to disregard the `--local-engine` flag, and picks up the sdk version.

**Comment by TahaTesser** [comment]
Hi @sohanjg 

I did just to reproduced to run physical 64-bit devices, just like Pixel. 
No issues when running on Android
Clean all your changes in `engine>src>flutter`, execute `git reset --hard`, I recommend it if you don't make any code changes
Please make sure your engine fork is updated,  make sure to pull the latest `upstream`, update your Flutter setup as well.
Documentaton is clear IMO .

If you're running on a physical device
`./flutter/tools/gn --android --unoptimized`
`./flutter/tools/gn --android --unoptimized --android-cpu=arm64`
`./flutter/tools/gn --unoptimized`
`flutter run --local-engine-src-path /Volumes/Extreme/engine/src  --local-engine=android_debug_unopt`
If you're not specifying FLUTTER_ENGINE environment, use `-local-engine-src`,  (I prefer)

**Comment by sohanjg** [comment]
Thanks TahaTesser@, I tried the clean branch, and cleaning `src/out` folder. But the same error persists, maybe I am missing some steps.
So, after setting up the GN file with the commands you mentioned (and in the doc), I run the ninja command for `android_debug_unopt` , `android_debug_unopt_arm64`, `host_debug_unopt`. They all succeed.
Then from the app folder `hello`, i run  `flutter run --verbose --local-engine-src-path <path to src> --local-engine=android_debug_unopt` or `android_debug_unopt_arm64`. But then its the same error `Execution failed for task ':app:compileFlutterBuildDebugArm64'`.
Is there something more to be done ?

**Comment by TahaTesser** [comment]
Hi @sohanjg 
Sounds about right, did you update your to latest `master` as well? 
Can you please provide complete logs for `flutter run --verbose --local-engine-src-path <path to src> --local-engine=android_debug_unopt --verbose` with verbose

**Comment by sohanjg** [comment]
hey @TahaTesser , thanks for helping out here. Yes the branch is updated too, my git log is 
`└─ $ ▶ git log
commit f72c5c1111212a344a19b4954b1f74ce67f75c59 (HEAD -> master, upstream/master, upstream/HEAD, origin/master)
Author: Dan Field <dnfield@google.com>
Date:   Wed Dec 2 10:33:42 2020 -0800

    Revert "Add build file for benchmark (#415)" (#416)
    
    This reverts commit 084f0d394f5b8fab6ddc2edb4837e20209a726a0.

commit 084f0d394f5b8fab6ddc2edb4837e20209a726a0
Author: Dan Field <dnfield@google.com>
`
I am attaching the verbose run as error.txt file.
[error.txt](https://github.com/flutter/flutter/files/5651691/error.txt)

**Comment by TahaTesser** [comment]
Hi @sohanjg 
I tried again to reproduce it from scratch, still no issues, your fork looks outdated, can you please try again by deleting your gradle cacahe? 
delete `.gradle`, go to /Users/Your_User//.gradle and try again
Thanks

**Comment by sohanjg** [comment]
Thanks @TahaTesser for following this up. 
I can confirm this works now, problem was not with the engine/ code, but my flutter/ repo.
