### ISSUE TITLE
Crash at SliverGridRegularTileLayout.getMinChildIndexForScrollOffset

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#71693]
Internal: b/174428685

```
UnsupportedError at _Double._trunc_div at dart:core-patch/double.dart-1bfc89bb
Stack Trace:
at _Double._trunc_div (double.dart:47 )
at _Double.~/ (double.dart:43 )
at SliverGridRegularTileLayout.getMinChildIndexForScrollOffset (sliver_grid.dart:197 )
at RenderSliverGrid.performLayout (sliver_grid.dart:529 )
at RenderObject.layout (object.dart:1777 )
at RenderSliverEdgeInsetsPadding.performLayout (sliver_padding.dart:139 )
at RenderSliverPadding.performLayout (sliver_padding.dart:374 )
at RenderObject.layout (object.dart:1777 )
at RenderViewportBase.layoutChildSequence (viewport.dart:507 )
at RenderViewport._attemptLayout (viewport.dart:1561 )
at RenderViewport.performLayout (viewport.dart:1470 )
at RenderObject._layoutWithoutResize (object.dart:1634 )
at PipelineOwner.flushLayout (object.dart:884 )
at RendererBinding.drawFrame (binding.dart:443 )
at WidgetsBinding.drawFrame (binding.dart:907 )
at RendererBinding._handlePersistentFrameCallback (binding.dart:309 )
at SchedulerBinding._invokeFrameCallback (binding.dart:1117 )
at SchedulerBinding.handleDrawFrame (binding.dart:1055 )
at SchedulerBinding._handleDrawFrame (binding.dart:971 )
at _rootRun (zone.dart:1190 )
at _CustomZone.run (zone.dart:1093 )
at _CustomZone.runGuarded (zone.dart:997 )
at _invoke (hooks.dart:251 )
at _drawFrame (hooks.dart:209 )
```

Unfortunately, there's no repro but this is happening quite frequently across multiple releases of customer:money. ~160 instances of this crash were reported.

**Comment by alexmarkov** [comment]
`double.~/` throws `UnsupportedError` if result of the division is infinity or NaN.

For example, 
```dart
  print(1.0 ~/ 0.0);
```
results in
```
Unsupported operation: Result of truncating division is Infinity or NaN
#0      double._trunc_div (dart:core-patch/double.dart:56:57)
#1      double.~/ (dart:core-patch/double.dart:52:12)
```

**Comment by mehmetf** [comment]
That's weird because the line that's generating this reads as:

```dart
return mainAxisStride > 0.0 ? crossAxisCount * (scrollOffset ~/ mainAxisStride) : 0;
```

Is this platform dependent? I tried on Linux to crash with various extreme values but no dice. Perhaps on Android it is different?

**Comment by mehmetf** [comment]
Unless scrollOffset itself is nan..

**Comment by alexmarkov** [comment]
I don't see anything platform dependent in the implementation of `double.~/`.

Result of that division could be NaN or infinity if `scrollOffset` is NaN or infitiny, or `mainAxisStride` is too close to zero and/or `scrollOffset` is too large (for example `1e200 ~/ 1e-200` results in infinity and exception is thrown).

**Comment by chunhtai** [comment]
I think it can only happen when mainAxisStride is very close to zero with reasonably big scroll offsets. This may be due to very big child size and/or precision error. I will put up a pr to fix it
