### ISSUE TITLE
Exception suddenly thrown on default counter app: Gradle task assembleDebug failed with exit code 1. Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Failed to find Build Tools revision 29.0.2

### ISSUE THREAD

**Issue by perilousGourd** [flutter/flutter#71768]
Seemingly spontaneously, any new application I create with flutter throws the exception:
> Gradle task assembleDebug failed with exit code 1
> \* What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Failed to find Build Tools revision 29.0.2

Any application I created prior to the first time this exception was thrown (a few hours ago*) compiles without this exception.

From browsing similar issues on SO and this repository, I would have expected this to be due to having the compileSdkVersion or targetSdkVersion in app/build.gradle set to 29.0.2 without 29.0.2 being installed.

- Both of these are set to 30, however, with Android API 30 Platform selected in Project Structure > Project SDK.
- Searching the entire project for 20.0.2 returns no results.
- In Tools > SDK Manager > SDK Tools, Android SDK Build Tools, Android SDK command-line tools (latest) and Android SDK Platform Tools are all installed and updated, shown with checkmarks.
  - Android SDK Platform Tools are of version 30.0.5.

My best guesses as to cause of error:
- Flutter doctor returns that my connected device is of Android API 29. All apps I have been working on prior to this issue appearing that use Android SDK 30 compile and run on it, however.
- Flutter doctor also returns that Android Studio is not installed. I'm not sure what to make of this, as I have Android Studio installed, open and running while I run flutter doctor from the terminal inside it. Flutter doctor has been returning this issue for weeks, and it has not previously had any noticable effects.

\* the first time this exception was thrown recently. I have seen this exception thrown before, a few weeks ago. It resolved as apparently spontaneously as it began within several days. It was during my attempts to fix it, which included reinstalling Android Studio, that flutter doctor began returning that Android Studio was not installed.

## Steps to Reproduce

1. Create a new flutter application using Android SDK 30 (with Android Studio UI in Ubuntu 20.04.01 LTS, and my Android API 29 Samsung Galaxy Note 10+ connected) .
2. Attempt to run the default template app.
3. This error occurs.

**Expected results:** 
I expected the default counter app to run.

**Actual results:** 
The app did not run, and the exception '* What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Failed to find Build Tools revision 29.0.2' was thrown.

<details>
  <summary>Logs</summary>

```
[  +48 ms] executing: [/home/perilousgourd/0/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +29 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 89ef88c64f4d4b4fe81d44174de0e0abb442817f
[        ] executing: [/home/perilousgourd/0/flutter/] git tag --points-at
89ef88c64f4d4b4fe81d44174de0e0abb442817f
[  +10 ms] Exit code 0 from: git tag --points-at 89ef88c64f4d4b4fe81d44174de0e0abb442817f
[   +1 ms] executing: [/home/perilousgourd/0/flutter/] git describe --match *.*.* --long --tags
89ef88c64f4d4b4fe81d44174de0e0abb442817f
[  +22 ms] Exit code 0 from: git describe --match *.*.* --long --tags
89ef88c64f4d4b4fe81d44174de0e0abb442817f
[        ] 1.25.0-4.0.pre-83-g89ef88c64f
[  +29 ms] executing: [/home/perilousgourd/0/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/perilousgourd/0/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +27 ms] executing: [/home/perilousgourd/0/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +28 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] executing: /home/perilousgourd/Android/Sdk/platform-tools/adb devices -l
[  +26 ms] List of devices attached
           RFCM90D8DMA            device usb:3-8 product:d2xxx model:SM_N976B device:d2x
           transport_id:1
[   +4 ms] /home/perilousgourd/Android/Sdk/platform-tools/adb -s RFCM90D8DMA shell getprop
[  +44 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] Skipping pub get: version match.
[  +80 ms] Generating
/home/perilousgourd/0/projects/apps/wtf2/android/app/src/main/java/io/flutter/plugins/GeneratedPl
uginRegistrant.java
[  +34 ms] ro.hardware = exynos9825
[        ] ro.build.characteristics = phone
[  +26 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +3 ms] Launching lib/main.dart on SM N976B in debug mode...
[   +4 ms] /home/perilousgourd/0/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/perilousgourd/0/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/perilousgourd/0/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
--output-dill /tmp/flutter_tools.UZLSYP/flutter_tool.YZOUPJ/app.dill --packages
/home/perilousgourd/0/projects/apps/wtf2/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill
build/152a2ce78bff4a6f74a44ed554717a64.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +13 ms] executing: /home/perilousgourd/Android/Sdk/platform-tools/adb -s RFCM90D8DMA shell -x
logcat -v time -t 1
[  +10 ms] <- compile package:wtf2/main.dart
[ +125 ms] --------- beginning of system
                    12-05 15:20:09.723 I/io_stats( 2406): !@   8,0 r 816058 45930244 w 359502
                    5646304 d 463701 84267384 f 157675 195125 iot 370164 287059 th 102400 0 0 pt
                    0 inp 0 0 25796.275
[  +10 ms] executing: /home/perilousgourd/Android/Sdk/platform-tools/adb version
[  +13 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as /home/perilousgourd/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/perilousgourd/Android/Sdk/platform-tools/adb start-server
[   +4 ms] Building APK
[  +14 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] Using gradle from /home/perilousgourd/0/projects/apps/wtf2/android/gradlew.
[        ] /home/perilousgourd/0/projects/apps/wtf2/android/gradlew mode: 33277 rwxrwxr-x.
[   +6 ms] executing: [/home/perilousgourd/0/projects/apps/wtf2/android/]
/home/perilousgourd/0/projects/apps/wtf2/android/gradlew -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=/home/perilousgourd/0/projects/apps/wtf2/lib/main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +846 ms] IOException: https://dl.google.com/android/repository/addons_list-3.xml
[        ] java.net.ConnectException: Connection refused (Connection refused)
[        ] IOException: https://dl.google.com/android/repository/addons_list-2.xml
[        ] java.net.ConnectException: Connection refused (Connection refused)
[        ] IOException: https://dl.google.com/android/repository/addons_list-1.xml
[        ] java.net.ConnectException: Connection refused (Connection refused)
[        ] Failed to download any source lists!
[        ] IO exception while downloading manifest:
[        ] java.net.ConnectException: Connection refused (Connection refused)
[        ]      at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[        ]      at
java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
[        ]      at
java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
[        ]      at
java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
[        ]      at java.base/java.net.Socket.connect(Socket.java:609)
[        ]      at java.base/java.net.Socket.connect(Socket.java:558)
[        ]      at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[        ]      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[        ]      at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:526)
[        ]      at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:524)
[        ]      at java.base/java.security.AccessController.doPrivileged(Native Method)
[        ]      at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:523)
[        ]      at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:564)
[        ]      at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[        ]      at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[        ]      at
java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Abstract
DelegateHttpsURLConnection.java:191)
[        ]      at
java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
[        ]      at
java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[        ]      at
java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateH
ttpsURLConnection.java:177)
[        ]      at
java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:1
68)
[        ]      at
com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openUrl(DownloadCache.java:247
)
[        ]      at
com.android.sdklib.repository.legacy.remote.internal.DownloadCache.downloadAndCache(DownloadCache
.java:624)
[        ]      at
com.android.sdklib.repository.legacy.remote.internal.DownloadCache.openCachedUrl(DownloadCache.ja
va:455)
[        ]      at
com.android.sdklib.repository.legacy.LegacyDownloader.downloadAndStream(LegacyDownloader.java:61)
[        ]      at
com.android.repository.impl.downloader.LocalFileAwareDownloader.downloadAndStream(LocalFileAwareD
ownloader.java:51)
[        ]      at
com.android.repository.impl.manager.RemoteRepoLoaderImpl.lambda$fetchPackages$0(RemoteRepoLoaderI
mpl.java:139)
[        ]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[        ]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[        ]      at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[        ]      at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[        ]      at java.base/java.lang.Thread.run(Thread.java:834)
[ +935 ms] Still waiting for package manifests to be fetched remotely.
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle
7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[        ] > Failed to find Build Tools revision 29.0.2
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option
to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[        ] See
https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[ +320 ms] Running Gradle task 'assembleDebug'... (completed in 2,121ms)
[+2904 ms] Exception: Gradle task assembleDebug failed with exit code 1
[        ] "flutter run" took 5,576ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[ +243 ms] ensureAnalyticsSent: 241ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1

```

```
No issues found! (ran in 0.9s)
```

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.83, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.25.0-5.0.pre.83 at /home/perilousgourd/0/flutter
    • Framework revision 89ef88c64f (4 hours ago), 2020-12-04 17:16:30 -0800
    • Engine revision 59b4baea51
    • Dart version 2.12.0 (build 2.12.0-113.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/perilousgourd/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • SM N976B (mobile) • RFCM90D8DMA • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

```

</details>

**Comment by perilousGourd** [comment]
I have at least temporarily fixed this, somewhat unsatisfyingly:
Comparing the android/build.gradle file in a new, exception-throwing app to that of an app that did not throw this exception, I noticed that the classpath line differed.
Exception throwing:
`classpath 'com.android.tools.build:gradle:4.1.0'`
Non exception throwing:
`classpath 'com.android.tools.build:gradle:3.5.0'`

I changed the version in the exception throwing app to 3.5.0, and it compiled without exception and is now running on my device, with no other issues having yet occurred in consequence.

I don't know anything about how the gradle files are generated, or particularly what might result in their generation with a version that results in an exception.

**Comment by iapicca** [comment]
> ## Steps to Reproduce
> 1. Create a new flutter application using Android SDK 30 (with Android Studio UI in Ubuntu 20.04.01 LTS, and my Android API 29 Samsung Galaxy Note 10+ connected) .
> 2. Attempt to run the default template app.
> 3. This error occurs.
> [...] 
> ```
> [✓] Flutter (Channel master, 1.25.0-5.0.pre.83, on Linux, locale en_AU.UTF-8)
>     • Flutter version 1.25.0-5.0.pre.83 at /home/perilousgourd/0/flutter
>     • Framework revision 89ef88c64f (4 hours ago), 2020-12-04 17:16:30 -0800
>     • Engine revision 59b4baea51
>     • Dart version 2.12.0 (build 2.12.0-113.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /home/perilousgourd/Android/Sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: /usr/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
>     • All Android licenses accepted.
> 
> [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
>       instructions).
> 
> [✓] Connected device (1 available)
>     • SM N976B (mobile) • RFCM90D8DMA • android-arm64 • Android 10 (API 29)
> 
> ! Doctor found issues in 2 categories.
> ```

@perilousGourd 
from your doctor seems that android studio setup isn't complete, could you please double check,
what is the output of `which android-studio` ?
are you experiencing the same issue from terminal?

**Comment by perilousGourd** [comment]
`which android-studio` returns `/snap/bin/android-studio`

If I try to run `flutter run` from Linux terminal in the directory of an app that has the automatically generated 4.1.0 classpath, the same error occurs. If I run `flutter run` from terminal, or via Android Studio GUI, in an app that has 3.5.0 classpath, it runs without issue.

This exception was first thrown at a time before flutter doctor returned that Android Studio was not installed (and I messed with the install repeatedly trying to fix it, quite possibly creating the 'not installed' issue then), so this could be unrelated?

**Comment by iapicca** [comment]
@perilousGourd 
please run `flutter config --android-studio-dir=/snap/android-studio/current/android-studio`
https://github.com/flutter/flutter/issues/70547

**Comment by perilousGourd** [comment]
Flutter doctor now detects Android Studio! Thank you! :+1: 
Original issue remains.

**Comment by TahaTesser** [comment]
Hi @perilousGourd 
Looks like you're running JDK 11, please use java 1.8, you can use JDK that comes with Android SDK itself. Uninstall 11 and add `export JAVA_HOME=/home/your_user/Code/android-studio/jre`. 

if the problem persists, please your updated `flutter doctor -v` 1.8 and complete `flutter run --verbose`


If the problem persists with 1.8

No issues for me on Ubuntu with API 30
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.91, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-5.0.pre.91 at /home/taha/Code/flutter_master
    • Framework revision 7dade22f25 (17 hours ago), 2020-12-06 21:34:04 +0530
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by perilousGourd** [comment]
@TahaTesser
I've now uninstalled openjdk 11, and set `JAVA_HOME` to 1.8, using the path I found in Project Settings > Platform Settings > SDKs > 1.8. `java -version` now returns `openjdk version "1.8.0_242-release"`.

The problem persists.

> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > Failed to find Build Tools revision 29.0.2
> ```

`flutter doctor -v` now returns

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.106, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.25.0-5.0.pre.106 at /home/perilousgourd/0/flutter
    • Framework revision bd68225598 (84 minutes ago), 2020-12-07 19:58:04 -0500
    • Engine revision a26e80c931
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/perilousgourd/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • SM N976B (mobile) • RFCM90D8DMA • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Chromium 87.0.4280.88
      snap

• No issues found!
```


There are two problems under Project Settings > Problems that I think are new:
> 1. Module new_java_test_android: invalid item '< Android API 29 Platform >' in the dependencies list.
> 2. Module new_java_test_android: invalid item 'Flutter for Android' in the dependencies list

Thank you for assisting me.

**Comment by TahaTesser** [comment]
Hi @perilousGourd 
Can you please take a screenshiot of the build tools you've installed in the SDK directory? Go to Android SDK -> build-tools and check if you have missing build_tools, even if they are delete them and go to SDK manager and install them again 

Mine looks like this on mac
<img width="520" alt="Screenshot 2020-12-08 at 1 02 45 PM" src="https://user-images.githubusercontent.com/48603081/101453784-e318f880-3955-11eb-80b9-ab8f0a8d966b.png">

**Comment by perilousGourd** [comment]
This is what was at first in my Android/Sdk/build-tools directory:
![image](https://user-images.githubusercontent.com/75515586/101963406-596d7180-3c5a-11eb-904a-1012e4829559.png)

This is what I uninstalled and reinstalled
![image](https://user-images.githubusercontent.com/75515586/101964460-309aab80-3c5d-11eb-8a4d-106e82d8f011.png)

This is what is now in my Android/Sdk/build-tools directory:
![image](https://user-images.githubusercontent.com/75515586/101964532-76f00a80-3c5d-11eb-99e8-6adcdf9f1ace.png)

The 29.0.2 directory is empty but for an .installer file
![image](https://user-images.githubusercontent.com/75515586/101965363-2201c380-3c60-11eb-8682-18ff18f797e7.png)


My makeshift fix of setting the default generated 4.1.0 version to 3.5.0 now results in failed builds with
```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to find Build Tools revision 28.0.3
```
4.1.0 still fails with error `Failed to find Build Tools revision 29.0.2`.

---

How does the 4.1.0 etc gradle build version number correspond to the API-level-esque version number 29.0.2 etc? What should I set this to
![image](https://user-images.githubusercontent.com/75515586/101965405-43fb4600-3c60-11eb-87cb-e7de88647e5e.png)
so that 30.0.3 should in theory be used?

**Comment by perilousGourd** [comment]
I downloaded Build Tools 29.2.0 revision 29.0.2 from https://androidsdkmanager.azurewebsites.net/Buildtools, put them in my Android/Sdk/build-tools/20.0.2 directory, and apps with classpath 4.1.0 and 4.1.1 now compile and run as expected.

Strange that installing via SDK Manager results in an empty 29.0.2 directory?

**Comment by TahaTesser** [comment]
Hi @perilousGourd 

> Strange that installing via SDK Manager results in an empty 29.0.2 directory?

I notice it sometimes too but it's not a Flutter issue, more of an IntelliJ issue

Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
