### ISSUE TITLE
Hot Reload takes for ever [WEB]

### ISSUE THREAD

**Issue by migalv** [flutter/flutter#71844]
The issue I'm experiencing happens when developing for Flutter Web, when I make some changes in certain files of my app and I hot reload, the hot reload literally takes ages, it never ends. This is very frustrating when trying to develop user interfaces and making small changes.

I have been developing in Flutter Web for quite some time now, around (5 to 6 months) and this has never happened to me. Sometimes the hot-reload got stuck or took a long time, but it never got stuck every time I made a small change in a specific file.

It's very strange because it depends on which file I make a change.

I started noticing this problem this morning, but I'm not sure what could have produced it. The days before, I don't think I had this problem. This also only happens in this project. I have tried running hot reload in other projects and it doesn't get stuck.

I'm using VSCode

> Version: 1.51.1 (user setup)
> Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
> Date: 2020-11-10T23:34:32.027Z
> Electron: 9.3.3
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.19041

I thought it could be the flutter version, so did `flutter upgrade`, but it didn't solve the issue.

I have also run several times the `flutter clean` command, but nothing.

Here is the output of flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.25.0-4.0.pre, on Microsoft Windows [VersiÃ³n 10.0.19041.630], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.51.1)
[√] Connected device (3 available)

```

I ran `flutter run -v` to get the verbose output, and here is the output I got:

```
[+11736 ms] Performing hot restart...
[   +4 ms] Initializing file store
[  +27 ms] Skipping target: gen_localizations
[   +7 ms] complete
[  +83 ms] Scanned through 525 files in 63ms
[   +1 ms] Waiting for connection from debug service on Chrome...
[   +3 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 5cc34edb-b89d-446d-84a1-aa2dbd3e1961
[   +6 ms] package:fake_app_v1/pages/order_confirmation_page.dart
[   +1 ms] <- 5cc34edb-b89d-446d-84a1-aa2dbd3e1961
[ +531 ms] Waiting for connection from debug service on Chrome... (completed in 541ms)
[   +1 ms] Synced 0.9MB.
[        ] <- accept
[   +2 ms] DwdsVmClient: Attempting a hot restart
[  +10 ms] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[  +12 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[ +194 ms] DwdsInjector: Received request for entrypoint at http://localhost:50622/main_module.bootstrap.js
[  +36 ms] MetadataProvider: Loading debug metadata...
[  +25 ms] MetadataProvider: Loaded debug metadata
[  +20 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:50622/main_module.bootstrap.js
[+2250 ms] DwdsVmClient: Successful hot restart
[   +2 ms] Performing hot restart... (completed in 3,2s)
[   +1 ms] Restarted application in 3.227ms.
[+7700 ms] Performing hot restart...
[   +3 ms] Skipping target: gen_localizations
[  +11 ms] complete
[  +72 ms] Scanned through 525 files in 48ms
[   +1 ms] Waiting for connection from debug service on Chrome...
[   +2 ms] <- recompile org-dartlang-app:/web_entrypoint.dart 207909b0-8cfa-4fe2-afaa-0a4932de5907
[   +1 ms] package:fake_app_v1/pages/faqs_page.dart
[   +1 ms] <- 207909b0-8cfa-4fe2-afaa-0a4932de5907
[ +126 ms] Waiting for connection from debug service on Chrome... (completed in 130ms)
[   +1 ms] Synced 0.2MB.
[   +1 ms] <- accept
[  +11 ms] DwdsVmClient: Attempting a hot restart
[   +2 ms] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[   +5 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[+741580 ms] Performing hot restart... (completed in 741,8s)
[  +10 ms] DevHandler: Stopped debug service on ws://127.0.0.1:50707

[  +17 ms] "flutter run" took 824.331ms.
[   +3 ms] the Dart compiler exited unexpectedly.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:720:9)
           #2      _rootRunUnary (dart:async/zone.dart:1194:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:150:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:703:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:732:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:536:5)
           #8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:574:7)
           #9      _rootRun (dart:async/zone.dart:1186:13)
           #10     _CustomZone.run (dart:async/zone.dart:1090:19)
           #11     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)
           #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[+13436 ms] Failed to clean up temp directory: C:\Users\migal\AppData\Local\Temp\flutter_tools.4fb3715e\flutter_tools.db837aa0
[   +1 ms] Failed to clean up temp directory: C:\Users\migal\AppData\Local\Temp\flutter_tools.4fb3715e\flutter_tools.db837aa0
[   +1 ms] the Dart compiler exited unexpectedly.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:720:9)
           #2      _rootRunUnary (dart:async/zone.dart:1194:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:150:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:703:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:732:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:536:5)
           #8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:574:7)
           #9      _rootRun (dart:async/zone.dart:1186:13)
           #10     _CustomZone.run (dart:async/zone.dart:1090:19)
           #11     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)
           #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[   +7 ms] Failed to clean up temp directory: C:\Users\migal\AppData\Local\Temp\flutter_tools.4fb3715e\flutter_tools.db837aa0
[  +10 ms] Failed to clean up temp directory: C:\Users\migal\AppData\Local\Temp\flutter_tools.4fb3715e\flutter_tools.db837aa0
```

It's interesting because you can see that I made a first hot-restart at the beginning but then on the second one it just gets stuck forever.

**Comment by TahaTesser** [comment]
Hi @migalv 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by migalv** [comment]
The issue is that I'm not completely sure where the issue is happening.

**Update:**
I have solved the issue. Because Flutter Web does not offer Hot reload, sometimes I change the child of the Material App. This helps me create the UI much quicker since I don't have to go through the whole app flow to arrive at the screen I'm developing. This usually doesn't result in many problems, but for some reason this time it did. 

If I'm not mistaken it's not a good practice to do changes on the child of a MaterialApp and then Hot reload right?

I changed the widget I was working on to be the child of another widget (not MaterialApp) and the issue stopped.

**Comment by TahaTesser** [comment]
Hi @migalv 
Oh yes, that's true, hot-restart is better in this case.
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by JakeHadley** [comment]
I'm getting a similar issue, not sure if I should create a new one or not, but figured I should check here first. I'm also using chrome and vs code, and upgraded, cleaned, no dice. I ran `flutter run -d chrome --verbose`, here's come output:
```
[  +16 ms] Debug service listening on ws://127.0.0.1:61332/88J-lCIMgpk=/ws
[   +2 ms]  Running with sound null safety 
[   +6 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+54003 ms] Performing hot restart...
[   +9 ms] Initializing file store
[  +13 ms] Skipping target: gen_localizations
[   +4 ms] complete
[  +60 ms] Scanned through 537 files in 58ms
[   +1 ms] Waiting for connection from debug service on Chrome...
[   +2 ms] <- recompile org-dartlang-app:/web_entrypoint.dart ad7cac75-a502-4104-b9d0-8f93abab2cbd
[   +1 ms] package:memorize_flutter/pages/login_page.dart
[   +1 ms] <- ad7cac75-a502-4104-b9d0-8f93abab2cbd
[  +82 ms] Waiting for connection from debug service on Chrome... (completed in 86ms)
[   +1 ms] Synced 0.1MB.
[        ] <- accept
[   +2 ms] DwdsVmClient: Attempting a hot restart
[   +2 ms] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[  +12 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[  +10 ms] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[ +107 ms] DwdsVmClient: $dartHotRestart request complete.
[   +1 ms] DwdsVmClient: Waiting for Isolate Start event.
```
And it gets stuck there.
