### ISSUE TITLE
[tool_crash] RangeError: RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by Stinox22** [flutter/flutter#71847]
## Command
```
flutter --no-color pub get
```

## Steps to Reproduce
1. Create a basic app
2. Edit pubspec.yaml as below

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line

flutter:
  generate: true

3. Build

## Logs
RangeError: RangeError (index): Invalid value: Valid value range is empty: 0
```
#0      _StringBase.[] (dart:core-patch/string_patch.dart:252:55)
#1      LocalizationsGenerator._isValidGetterAndMethodName (package:flutter_tools/src/localizations/gen_l10n.dart:766:13)
#2      LocalizationsGenerator.loadResources (package:flutter_tools/src/localizations/gen_l10n.dart:791:12)
#3      generateLocalizations (package:flutter_tools/src/build_system/targets/localizations.dart:65:9)
#4      GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:123:5)
#5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension>
#6      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:744:35)
#7      new Future.sync (dart:async/future.dart:223:31)
#8      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension>
#10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#11     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:64:30)
#12     PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:109:13)
#13     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:151:11)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#22     _rootRun (dart:async/zone.dart:1190:13)
```
```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-IN)
    • Flutter version 1.22.4 at C:\flutter-sdk\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:/Users/sagar/AppData/Local/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:/Users/sagar/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.1)
    • VS Code at C:\Users\sagar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d

**Comment by Stinox22** [comment]
Fixed it by prepending @ to the key for .arb key.
{
"@mykey":"somevalue"
}

**Comment by jdr1** [comment]
I got this error too by a typo of the arb file similar to this, while the fix worked for me too it would be useful to improve the flutter error output here to output the arb file name where the issue is, as it stands it doesnt really give much clues.
