### ISSUE TITLE
Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for build\windows\runner\Debug\${COMPILER_NAME}.exe.".

### ISSUE THREAD

**Issue by eduardo-cervantes** [flutter/flutter#71867]
I am trying to compile a project and it is not running.

My CMakeList.txt file:
```
cmake_minimum_required(VERSION 3.15)

file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/runner/resources/EnvironmentConfig.h" CONFIG_FILE)
string(REGEX MATCH "#define COMPILER_NAME \"([A-z]*)\"" _ ${CONFIG_FILE})

set(COMPILER_NAME ${CMAKE_MATCH_1})

project(${COMPILER_NAME} LANGUAGES CXX)
set(BINARY_NAME "${COMPILER_NAME}")
[...]
```
Yes, I changed the file "CMakeList.txt" because I want to get the name of the executable from another configuration file.
**It creates the file perfectly in the "build\windows\runner\Debug" path and the executable works. However, it does not open directly from Android Studio.**

Flutter crash report.

## command

flutter --no-color run --machine --track-widget-creation --device-id=windows --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart

## exception

ArgumentError: Invalid argument(s): Cannot find executable for build\windows\runner\Debug\${COMPILER_NAME}.exe.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:630:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:524:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:630:12)
#5      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:139:51)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:555:54)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:339:31)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
#16     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
#25     FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart)
#26     _rootRunUnary (dart:async/zone.dart:1198:47)
#27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
#34     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
#35     _rootRunUnary (dart:async/zone.dart:1198:47)
#36     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#40     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#41     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#42     _rootRun (dart:async/zone.dart:1190:13)
#43     _CustomZone.run (dart:async/zone.dart:1093:19)
#44     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#45     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel unknown, 1.24.0-7.0.pre, on Microsoft Windows [versÃ£o 10.0.19042.662], locale pt-BR)
    • Flutter version 1.24.0-7.0.pre at C:\Users\edums\fvm\default
    • Framework revision a0860f6e87 (6 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:/Users/edums/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:/Users/edums/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.51.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.662]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.55

• No issues found!
```

**Comment by darshankawar** [comment]
@eduardo-cervantes 
There's a similar open issue describing your case, [56975](https://github.com/flutter/flutter/issues/56975).
Please follow-up there for updates.
Closing this as duplicate.
