### ISSUE TITLE
package:flutter/src/widgets/scrollable.dart': Failed assertion: line 525 pos 12: '_drag == null':

### ISSUE THREAD

**Issue by lhjandroid** [flutter/flutter#71914]
```
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 525 pos 12: '_drag == null':
 I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
 I/flutter: In either case, please report this assertion by filing a bug on GitHub:
/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
 I/flutter: When the exception was thrown, this was the stack:
I/flutter: #2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:525:12)
I/flutter: #3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:373:50)
 I/flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
 I/flutter: #5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:373:7)
 I/flutter: #6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:236:7)
 I/flutter: #7      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:102:7)
 I/flutter: #8      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1017:18)
 I/flutter: #9      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2616:27)
 I/flutter: #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
 I/flutter: #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
 I/flutter: #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
 I/flutter: #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
 I/flutter: #17     _invoke1 (dart:ui/hooks.dart:275:10)
 I/flutter: #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
I/flutter: (elided 5 frames from class _AssertionError and dart:async)
 I/flutter: Handler: "onDown"
 I/flutter: Recognizer:
 I/flutter:   VerticalDragGestureRecognizer#74a4b
 I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
here is my code
`Selector(
      builder: (context,Tuple2 data,_) {
        return Transform.translate(
          offset: Offset(0, data.item1),
          child: Listener(
            onPointerMove: (PointerMoveEvent event) {
              handleMove(event);
            },
            onPointerCancel: (PointerCancelEvent event) {
              handleCancel(event);
            },
            onPointerUp: (PointerUpEvent event) {
              handleUp(event);
            },
            onPointerDown: (PointerDownEvent event) {

            },
            child: CustomScrollView(
              physics: data.item2 ? AlwaysScrollableScrollPhysics() : NeverScrollableScrollPhysics(),
              controller: _controller,
              slivers: <Widget>[
                SliverToBoxAdapter(
                  child: Column(
                    children: <Widget>[
                      ItemOrderMapReflush(),
                      ItemOrderTip(),
                      ItemOrderStatus(),
                      OrderItemMarketAddress(),
                      ItemOderDelivery(),
                      ItemOrderAddress(),
                      ItemOderControl(),
                    ],
                  ),
                ),
                ItemOrderProduct(),
                SliverToBoxAdapter(
                  child: ItemOrderInfoMation(),
                ),`

```

**Comment by darshankawar** [comment]
@lhjandroid 
Please provide above requested details to properly address the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
