### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'callMethod' was called on null.Receiver: nullTried calling: callMethod("_flutter.listViews")

### ISSUE THREAD

**Issue by garent111** [flutter/flutter#71910]
## Command
```
flutter run --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'callMethod' was called on null.
Receiver: null
Tried calling: callMethod("_flutter.listViews")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      FlutterVmService.getFlutterViews (package:flutter_tools/src/vmservice.dart:770:50)
#2      ResidentRunner.screenshot (package:flutter_tools/src/resident_runner.dart:1048:18)
#3      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1505:34)
#4      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1584:13)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#10     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
#11     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#12     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:484:11)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#20     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#21     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#22     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#23     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:256:17)
#24     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:242:5)
```
```
[✓] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.19041.508], locale en-IN)
    • Flutter version 1.20.4 at C:\src\flutter\flutter
    • Framework revision fba99f6cf9 (9 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\nikhi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.49.1)
    • VS Code at C:\Users\nikhi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • POCO F1 (mobile) • d918fb0 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 216dee60c0cc9449f0b29bcf922974d612263e24
### Plugins
cloud_firestore-0.14.0+2
cloud_firestore_web-0.2.0+1
firebase_auth-0.18.0+1
firebase_auth_web-0.3.0+1
firebase_core-0.5.0
firebase_core_web-0.2.0
firebase_storage-4.0.0
flutter_plugin_android_lifecycle-1.0.9
image_picker-0.6.7+10
url_launcher-5.7.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+8
url_launcher_web-0.1.3+2
url_launcher_windows-0.0.1+1

**Comment by darshankawar** [comment]
@garent111 
You seem to be on older version of Flutter. Current stable is 1.22.4. I'd recommend to upgrade to latest and try again to see if it works.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
