### ISSUE TITLE
Failed assertion in pointerScroll() on scroll extent changes

### ISSUE THREAD

**Issue by tgucio** [flutter/flutter#71949]
## Description
This was found with a somewhat complex widget inside a Scrollable where the user scroll input is used to hide/show the AppBar so that the scroll extent changes. The input was from MacBook touchpad, not sure if this is desktop-touchpad/mouse specific problem though.

I've reproduced this using a simple test app with a bunch of Chip()s inside a Wrap() to slow down rendering.

## Steps to Reproduce

1. Run `flutter create scrolltest`.
2. Update the files as follows: main.dart in Code below.
3. ... 

**Results:**
After scrolling up and down multiple times the following exception happens:
```
════════ Exception caught by gesture library ═══════════════════════════════════
The following assertion was thrown while resolving a PointerSignalEvent:
'package:flutter/src/widgets/scroll_position_with_single_context.dart': Failed assertion: line 209 pos 12: 'delta != 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      ScrollPositionWithSingleContext.pointerScroll
package:flutter/…/widgets/scroll_position_with_single_context.dart:209
#3      ScrollableState._handlePointerScroll
package:flutter/…/widgets/scrollable.dart:670
#4      PointerSignalResolver.resolve
package:flutter/…/gestures/pointer_signal_resolver.dart:57
#5      GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:387
#6      GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:361
...
Event: _TransformedPointerScrollEvent#14c56(position: Offset(401.8, 276.0), scrollDelta: Offset(-0.0, -0.0))
    position: Offset(401.8, 276.0)
    scrollDelta: Offset(-0.0, -0.0)
```

## Analysis
The assertion is hit when user input results in (-)0.0 offset scroll after the scrollExtent has changes and position hasn't been updated yet.

### Stack backtrace
```
_AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46)
_AssertionError._throwNew (dart:core-patch/errors_patch.dart:36)
ScrollPositionWithSingleContext.pointerScroll (/Library/Frameworks/flutter/packages/flutter/lib/src/widgets/scroll_position_with_single_context.dart:209)
ScrollableState._handlePointerScroll (/Library/Frameworks/flutter/packages/flutter/lib/src/widgets/scrollable.dart:670)
PointerSignalResolver.resolve (/Library/Frameworks/flutter/packages/flutter/lib/src/gestures/pointer_signal_resolver.dart:57)
GestureBinding.handleEvent (/Library/Frameworks/flutter/packages/flutter/lib/src/gestures/binding.dart:387)
GestureBinding.dispatchEvent (/Library/Frameworks/flutter/packages/flutter/lib/src/gestures/binding.dart:361)
RendererBinding.dispatchEvent (/Library/Frameworks/flutter/packages/flutter/lib/src/rendering/binding.dart:279)
GestureBinding._handlePointerEventImmediately (/Library/Frameworks/flutter/packages/flutter/lib/src/gestures/binding.dart:316)
GestureBinding.handlePointerEvent (/Library/Frameworks/flutter/packages/flutter/lib/src/gestures/binding.dart:280)
GestureBinding._flushPointerEventQueue (/Library/Frameworks/flutter/packages/flutter/lib/src/gestures/binding.dart:238)
GestureBinding._handlePointerDataPacket (/Library/Frameworks/flutter/packages/flutter/lib/src/gestures/binding.dart:221)
_rootRunUnary (dart:async/zone.dart:1202)
_CustomZone.runUnary (dart:async/zone.dart:1097)
_CustomZone.runUnaryGuarded (dart:async/zone.dart:1002)
_invoke1 (dart:ui/hooks.dart:176)
PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276)
_dispatchPointerDataPacket (dart:ui/hooks.dart:96)
```

### Call sequence

1. Framework input is decoded as a pointer event (touchpad in this case) with zero offset:
```
binding.dart::handlePointerEvent(PointerEvent event)
  PointerScrollEvent (PointerScrollEvent#f50ee(position: Offset(380.7, 332.3), scrollDelta: Offset(-0.0, -0.0)))
```

2. This is passed on to handleEvent():
```
binding.dart::handleEvent(PointerEvent event, HitTestEntry entry)
  _TransformedPointerScrollEvent (_TransformedPointerScrollEvent#3e667(position: Offset(380.7, 332.3), scrollDelta: Offset(-0.0, -0.0)))
```

3. The key part happens here. _targetScrollOffsetForPointerScroll() returns a value different from position.pixels:
```
scrollable.dart::_handlePointerScroll(PointerEvent event)
  _TransformedPointerScrollEvent (_TransformedPointerScrollEvent#98aae(position: Offset(380.7, 332.3), scrollDelta: Offset(-0.0, -0.0)))
    final double targetScrollOffset = _targetScrollOffsetForPointerScroll(event as PointerScrollEvent);
    if (targetScrollOffset != position.pixels) {
      position.pointerScroll(_pointerSignalEventDelta(event));
    }
    // targetScrollOffset = 82, position.pixels = 86.19519110579398
    // _pointerSignalEventDelta() returns -0.0
```

4. This is how _targetScrollOffsetForPointerScroll() does the math: offset is larger than maxExtent:
``` 
scrollable.dart::_targetScrollOffsetForPointerScroll(PointerScrollEvent event) {
  final double delta = _pointerSignalEventDelta(event);
  return math.min(math.max(position.pixels + delta, position.minScrollExtent),
    position.maxScrollExtent);
  // position = ScrollPositionWithSingleContext (ScrollPositionWithSingleContext#c205a(offset: 86.2, range: 0.0..82.0, viewport: 540.0, ...)
```

5. pointerScroll() is called with delta = -0.0:
```
scroll_position_with_single_context.dart::pointerScroll(double delta)
    assert(delta != 0.0);
    // delta = -0.0
```

<details>
  <summary>Code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/foundation.dart';


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  ScrollController _scrollController;
  bool _appBarVisible = true;

  @override
  void initState() {
    super.initState();
    _scrollController = ScrollController()
      ..addListener(() {
        if (_scrollController.position.userScrollDirection
            == ScrollDirection.reverse) {
          setState(()=> _appBarVisible = false);
        } else if (_scrollController.position.userScrollDirection
            == ScrollDirection.forward) {
          setState(()=> _appBarVisible = true);
        }
      });
  }
 
  @override
  Widget build(BuildContext context) {
    final appBar = PreferredSize(
      preferredSize: Size.fromHeight(kToolbarHeight),
      child: AnimatedContainer(
        height: _appBarVisible ? 55.0 : 0.0,
        duration: Duration(milliseconds: 150),
        child: AppBar(title: Text(widget.title),
      ),
      ),
    );

    List<Widget> children = [];
    for (int i = 0; i < 100; i++) {
      children.add(InputChip(label: Text('Lorem ipsum $i'), padding: EdgeInsets.all(10.0)));
    }
    return Scaffold(
      appBar: appBar,
      body: Center(
        child: SingleChildScrollView(
          controller: _scrollController,
          physics: ScrollPhysics(),
          child: Wrap(children: children),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _scrollController.jumpTo(0.0),
        tooltip: 'Jump',
        child: Icon(Icons.arrow_upward),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
% flutter doctor -v
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-4.0.pre at /Library/Frameworks/flutter
    • Framework revision a7f5fd5360 (8 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tgucio/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.7 19H15 darwin-x64

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment]
Hi @tgucio 
I cannot reproduce this issue on latest master and dev channel. Tried scrolling up and down using MacBook touchpad and Mouse scroll wheel on an Android emulator.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-4.0.pre at /Users/pedromassango/dev/SDKs/flutter_dev
    • Framework revision a7f5fd5360 (9 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.4
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by tgucio** [comment]
Olá Pedro,

Sometimes it takes a bit of constant quick scrolling up/down while the app bar is shown/removed. Attaching the output of "flutter run --verbose" with the assertion hit a few times.

[flutter_run_verbose.txt](https://github.com/flutter/flutter/files/5667157/flutter_run_verbose.txt)

**Comment by pedromassangocode** [comment]
Tried for few minutes and still cannot reproduce the issue on latest `master` channel.

Can you please provide your `flutter run --verbose` ?
Thank you

**Comment by tgucio** [comment]
Also reproduced on today's master channel. Log attached.
Since as per my analysis, the issue happens when there's a "-0.0" scroll offset input from the platform, I guess chances are this happens on specific versions of HW or SW.

[flutter_run_verbose_master_20201218.txt](https://github.com/flutter/flutter/files/5713039/flutter_run_verbose_master_20201218.txt)

**Comment by tgucio** [comment]
Possibly introduced in https://github.com/flutter/flutter/pull/70953

**Comment by pedromassangocode** [comment]
I was able to easily reproduce this issue on latest `master` channel on a MacOS Flutter app after trying on Android for several times.

<details><summary>Logs</summary>

```
Building macOS application...
Debug service listening on ws://127.0.0.1:51451/Fa0ZqLCYtdk=/ws
Syncing files to device macOS...

======== Exception caught by gesture library =======================================================
The following assertion was thrown while resolving a PointerSignalEvent:
'package:flutter/src/widgets/scroll_position_with_single_context.dart': Failed assertion: line 209 pos 12: 'delta != 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollPositionWithSingleContext.pointerScroll (package:flutter/src/widgets/scroll_position_with_single_context.dart:209:12)
#3      ScrollableState._handlePointerScroll (package:flutter/src/widgets/scrollable.dart:670:16)
#4      PointerSignalResolver.resolve (package:flutter/src/gestures/pointer_signal_resolver.dart:57:32)
#5      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:387:29)
#6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
...
Event: _TransformedPointerScrollEvent#1f5f9(position: Offset(411.6, 389.2), scrollDelta: Offset(-0.0, -0.0))
  position: Offset(411.6, 389.2)
  scrollDelta: Offset(-0.0, -0.0)
====================================================================================================
```
</details>

<details><summary>flutter doctor -v</summary>

```
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 1.26.0-2.0.pre.82, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.82 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision b84d8ee2df (70 minutes ago), 2020-12-18 11:59:01 +0530
    • Engine revision fd6b409f95
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>
