### ISSUE TITLE
Null check operator error in RenderFlex. _hasOverflow

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#71972]
### Steps to reproduce

Write the following into `test/bug_report.dart`, then test via `flutter test test/bug_report.dart`:

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('bug report', (WidgetTester tester) async {
    await tester.pumpWidget(Row(children: []));
  });
}
```

### Expected behavior

You expect the test to fail because [`Row` requires a text direction](https://github.com/flutter/flutter/blob/bf1091b80db83a2d41d14252b71a3eab06dc7b75/packages/flutter/lib/src/rendering/flex.dart#L464).  But you expect the failure to look something like:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Horizontal RenderFlex with MainAxisAlignment.start has a null textDirection, so the alignment cannot
be resolved.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 464 pos 18: 'textDirection != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Row file:///Users/tvolkert/project/sci/apps/payouts/test/pivot/table_pane.test.dart:7:29

When the exception was thrown, this was the stack:
#2      RenderFlex._debugHasNecessaryDirections (package:flutter/src/rendering/flex.dart:464:18)
#3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:919:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
...
```

### Actual behavior

In addition to the expected error, you get an ancillary null safety error:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was:
  Row file:///Users/tvolkert/project/sci/apps/payouts/test/pivot/table_pane.test.dart:7:29

When the exception was thrown, this was the stack:
#0      RenderFlex._hasOverflow (package:flutter/src/rendering/flex.dart:489:37)
#1      RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:10)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
#3      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#4      RenderView.paint (package:flutter/src/rendering/view.dart:214:15)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
#6      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#7      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#8      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
#9      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1117:27)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1119:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1057:9)
#13     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:977:9)
#16     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#17     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:964:27)
#18     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#21     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#22     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#23     main.<anonymous closure> (file:///Users/tvolkert/project/sci/apps/payouts/test/pivot/table_pane.test.dart:7:18)
#24     main.<anonymous closure> (file:///Users/tvolkert/project/sci/apps/payouts/test/pivot/table_pane.test.dart:6:22)
#25     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderFlex#12e7b:
  creator: Row ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=800.0, h=600.0)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Version info

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.123, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
    • Flutter version 1.25.0-5.0.pre.123 at /Users/tvolkert/project/flutter/flutter
    • Framework revision c8f07aad56 (2 hours ago), 2020-12-08 17:58:28 -0800
    • Engine revision de341faa4d
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)
```

**Comment by pedromassangocode** [comment]
Reproduces in 1.25.0-5.0.pre.141.

<details><summary>Logs</summary>

```
Testing started at 11:03 ...
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter --no-color test --machine --start-paused --plain-name "bug report" test/widget_test.dart

══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Horizontal RenderFlex with MainAxisAlignment.start has a null textDirection, so the alignment cannot
be resolved.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 464 pos 18: 'textDirection != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Row file:///Users/pedromassango/dev/Projects/flutter_example/test/widget_test.dart:6:29

When the exception was thrown, this was the stack:
#2      RenderFlex._debugHasNecessaryDirections (package:flutter/src/rendering/flex.dart:464:18)
#3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:919:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#5      RenderView.performLayout (package:flutter/src/rendering/view.dart:167:14)
#6      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
#7      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
#8      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1113:23)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1119:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1057:9)
#12     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:977:9)
#15     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#16     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:964:27)
#17     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#20     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#21     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#22     main.<anonymous closure> (file:///Users/pedromassango/dev/Projects/flutter_example/test/widget_test.dart:6:18)
#23     main.<anonymous closure> (file:///Users/pedromassango/dev/Projects/flutter_example/test/widget_test.dart:5:29)
#24     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderFlex#04c2f:
  creator: Row ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=800.0, h=600.0)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was:
  Row file:///Users/pedromassango/dev/Projects/flutter_example/test/widget_test.dart:6:29

When the exception was thrown, this was the stack:
#0      RenderFlex._hasOverflow (package:flutter/src/rendering/flex.dart:489:37)
#1      RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:10)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
#3      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#4      RenderView.paint (package:flutter/src/rendering/view.dart:214:15)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
#6      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#7      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#8      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
#9      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1117:27)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1119:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1057:9)
#13     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:977:9)
#16     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#17     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:964:27)
#18     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#21     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#22     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#23     main.<anonymous closure> (file:///Users/pedromassango/dev/Projects/flutter_example/test/widget_test.dart:6:18)
#24     main.<anonymous closure> (file:///Users/pedromassango/dev/Projects/flutter_example/test/widget_test.dart:5:29)
#25     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

The following RenderObject was being processed when the exception was fired: RenderFlex#04c2f:
  creator: Row ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=800.0, h=600.0)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: bug report


```
</details>

<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel master, 1.25.0-5.0.pre.141, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-5.0.pre.141 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 36bed2b4c3 (9 hours ago), 2020-12-09 20:13:04 -0500
    • Engine revision 8518a5bbe6
    • Dart version 2.12.0 (build 2.12.0-135.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.4
    • Dart plugin version 202.8070

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>
