### ISSUE TITLE
[devicelab] Retrying LUCI devicelab tasks results in an infra failure

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#72007]
Example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_benchmarks_canvaskit/45/overview

This is related to passing the git branch via recipe properties. Cocoon is not setting the branch when rescheduling prod builders.

**Comment by CaseyHillers** [comment]
```
BuildBucketException: [400]: properties: property path ['branch'] is reserved
#0      BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:86:5)
<asynchronous suspension>
#1      BuildBucketClient.scheduleBuild (package:cocoon_service/src/service/buildbucket.dart:91:12)
#2      LuciBuildService.rescheduleProdBuild (package:cocoon_service/src/service/luci_build_service.dart:400:29)
#3      ResetProdTask.post (package:cocoon_service/src/request_handlers/reset_prod_task.dart:69:28)
<asynchronous suspension>
#4      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart)
```

Tasks are failing to be rescheduled. I have rolled Cocoon back to a previous version.

**Comment by CaseyHillers** [comment]
The recipe should be pulling from gitiles instead of the properties for branch.

**Comment by CaseyHillers** [comment]
Recipe change: https://flutter-review.googlesource.com/c/recipes/+/9180

**Comment by CaseyHillers** [comment]
Fixed with the recipe CL
