### ISSUE TITLE
Navigator _debugLocked error

### ISSUE THREAD

**Issue by Jparrgam** [flutter/flutter#72077]
Hello everyone, I have an error when opening a new page using the `Navigator.pushNamed` method of flutter, I share the trace of the error: 

this error only happens to me on ios devices

```
The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3352 pos 12: '!_debugLocked':
flutter: is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:3352:12)
flutter: #3      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:3425:20)
flutter: #4      Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:1587:34)
flutter: #5      AppNavigator.pushNamed (package:picap/src/res/pi_navigator.dart:446:22)
flutter: #6      AppNavigator.pushResumeTravel (package:picap/src/res/pi_navigator.dart:374:7)
flutter: #7      _ResumeTravelWidgetState.build.<anonymous closure> (package:picap/src/transport/driver/ui/widgets/resume_travel_widget.dart:71:14)
flutter: #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
flutter: #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
flutter: #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
flutter: #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
flutter: #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
flutter: #13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
flutter: #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
flutter: #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
flutter: #16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
flutter: #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
flutter: #18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
flutter: #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
flutter: #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
flutter: #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
flutter: #22     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
flutter: #23     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
flutter: #24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
flutter: #25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
flutter: #29     _invoke1 (dart:ui/hooks.dart:265:10)
flutter: #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: Handler: "onTap"
flutter: Recognizer:
flutter:   TapGestureRecognizer#b8695
```

method call  `return Navigator.pushNamed(context, route, arguments: arguments);` on `onTap: ()` from InkWell

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B50 darwin-x64, locale en-CO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by darshankawar** [comment]
@Jparrgam 
Please provide a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
