### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /opt/homebrew/Caskroom/flutter/1.22.4/flutter/bin/cache/artifacts/usbmuxd/iproxy.

### ISSUE THREAD

**Issue by Alexlink2004** [flutter/flutter#72182]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /opt/homebrew/Caskroom/flutter/1.22.4/flutter/bin/cache/artifacts/usbmuxd/iproxy.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:462:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:356:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:462:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:477:28)
#6      IProxy.forward (package:flutter_tools/src/ios/iproxy.dart:51:26)
#7      IOSDevicePortForwarder.forward (package:flutter_tools/src/ios/devices.dart:827:31)
<asynchronous suspension>
#8      buildObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:243:20)
#9      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:158:18)
<asynchronous suspension>
#10     FallbackDiscovery.discover (package:flutter_tools/src/ios/fallback_discovery.dart:85:58)
<asynchronous suspension>
#11     IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:436:52)
<asynchronous suspension>
#12     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:551:54)
<asynchronous suspension>
#13     HotRunner.run (package:flutter_tools/src/run_hot.dart:339:31)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
```
```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-arm, locale en-AF)
    • Flutter version 1.22.5 at /opt/homebrew/Caskroom/flutter/1.22.4/flutter
    • Framework revision 7891006299 (33 hours ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/alexapodaca/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • ALEJANDRO’s iPhone (mobile) • 00008030-000935E82213802E • ios • iOS 14.2
    ! Error: ALEJANDRO’s iPhone is busy: Copying cache files from device. Xcode will continue when ALEJANDRO’s
      iPhone is finished. (code -10)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.2.2+3
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 916c3ac648aa0498a70f32b5fc4f6c51447628e3
### Plugins
audioplayers-0.17.0
cloud_firestore-0.14.0+2
cloud_firestore_web-0.2.0+1
firebase_core-0.5.0
firebase_core_web-0.2.0
flutter_statusbar_manager-2.0.0
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+3

**Comment by darshankawar** [comment]
@Alexlink2004 
Can you try [this](https://github.com/flutter/flutter/issues/59544#issuecomment-644707425) solution and see if it works ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
