### ISSUE TITLE
Flutter crash report

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#72224]
## command

flutter --quiet assemble --depfile /home/aliyazdi75/Documents/AndroidStudioProjects/mate_machine_app/build/app/intermediates/flutter/release/flutter_build.d --output /home/aliyazdi75/Documents/AndroidStudioProjects/mate_machine_app/build/app/intermediates/flutter/release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /home/aliyazdi75/snap/flutter/common/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:627:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:521:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:627:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:196:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:232:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1119:12)
<asynchronous suspension>
#18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:974:27)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:264:9)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#24     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:220:5)
<asynchronous suspension>
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
<asynchronous suspension>
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#29     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#30     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
<asynchronous suspension>
#31     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-8.0.pre.374 at /home/aliyazdi75/snap/flutter/common/flutter
    • Framework revision 183f0e797a (3 days ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/aliyazdi75/Android/Sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /home/aliyazdi75/Application/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /home/aliyazdi75/Application/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/aliyazdi75/Application/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.66

• No issues found!
```

**Comment by YazeedAlKhalaf** [comment]
Thanks for your report @aliyazdi75 

Please provide us with a simple reproducible code sample, so we can reproduce the error and try to fix it.

**Comment by aliyazdi75** [comment]
@YazeedAlKhalaf 
Hi, it didn't reproduce by code. As you can see, it's been generated by a Flutter command and stored automatically in the Flutter log.

**Comment by YazeedAlKhalaf** [comment]
> ArgumentError: Invalid argument(s): Cannot find executable for

Here I can't see what arguments you used so it is hard right now to solve the issue without more info.

**Comment by iapicca** [comment]
@aliyazdi75 
please run `flutter upgrade -f` and provide your updated `flutter doctor -v` and logs

> [✓] Flutter (Channel master, 1.24.0-8.0.pre.374, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.24.0-8.0.pre.374 at /home/aliyazdi75/snap/flutter/common/flutter
>     • Framework revision 183f0e797a (3 days ago), 2020-11-26 19:12:28 +0100
>     • Engine revision 20caf54969
>     • Dart version 2.12.0 (build 2.12.0-76.0.dev)

possible duplicate of https://github.com/flutter/flutter/issues/71896

**Comment by aliyazdi75** [comment]
@iapicca 
The log was for the previous version.
Yes, it's duplicated.
Sorry I didn't check duplication out.

**Comment by iapicca** [comment]
> @iapicca
> The log was for the previous version.
> Yes, it's duplicated.
> Sorry I didn't check duplication out.

no worries, better twice than none :)
