### ISSUE TITLE
Issue while using NestedScrollView as Page-based route.

### ISSUE THREAD

**Issue by sarbagyastha** [flutter/flutter#72257]
## Description
Using `NestedScrollView` as pages throws assertion error.
```
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 805 pos 14: 'position.hasContentDimensions && position.hasPixels': is not true.
```

## Steps to Reproduce
Code snippet to reproduce the issue.

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Navigator(
        pages: [
          MaterialPage(
            key: ValueKey(1),
            child: SampleWidget(number: 1),
          ),
          MaterialPage(
            key: ValueKey(2),
            child: SampleWidget(number: 2),
          ),
        ],
        onPopPage: (route, result) => route.didPop(result),
      ),
    );
  }
}

class SampleWidget extends StatelessWidget {
  final int number;

  const SampleWidget({Key key, this.number}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return NestedScrollView(
      headerSliverBuilder: (context, _) => [
        SliverAppBar(
          title: Text('Sample $number'),
        ),
      ],
      body: Scaffold(
        body: ListView(
          children: [
            Center(child: Text('Body $number')),
          ],
        ),
      ),
    );
  }
}
```
**Expected results:** 
Navigates to **Page 2** without any issue.

**Actual results:** 
Page 2 is in the top of the navigation stack but Page 1 will have assertion error.
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 805 pos 14: 'position.hasContentDimensions && position.hasPixels': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      _NestedScrollCoordinator.hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:805:14)
#3      NestedScrollViewState._handleHasScrolledBodyChanged (package:flutter/src/widgets/nested_scroll_view.dart:609:51)
#4      _NestedScrollCoordinator.updateShadow (package:flutter/src/widgets/nested_scroll_view.dart:813:50)
#5      _NestedScrollController._scheduleUpdateShadow.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:1310:21)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1119:15)
...
====================================================================================================
```

<details>
  <summary>flutter doctor output</summary>

```
[✓] Flutter (Channel dev, 1.25.0-8.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.0.pre at ...
    • Framework revision a12e2a473a (5 days ago), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at ...
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Linux
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 87.0.4280.88
```

</details>

**Comment by pedromassangocode** [comment]
Reproducible on master channel as well.

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.43, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.25.0-9.0.pre.43 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 63062a6443 (22 hours ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by hello-addweb** [comment]
Please check with the `extendBody : true`.

**Comment by darshankawar** [comment]
@sarbagyastha 
I was able to resolve the assertion failure by simply passing `controller` to `ListView`. 

```
body: Scaffold(
        body: ListView(
          controller: _scrollController,
          children: [
            Center(child: Text('Body $number')),
          ],
        ),
      ),
```

`var _scrollController = ScrollController();`

With this, the app navigates from Sample 2 to Sample 1 without any issues.
