### ISSUE TITLE
Cocoon failed to re-run post-submit luci builder

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#72289]
It failed with error:

```
BuildBucketException: [400]: properties: property path ['branch'] is reserved
#0      BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:86:5)
<asynchronous suspension>
#1      BuildBucketClient.scheduleBuild (package:cocoon_service/src/service/buildbucket.dart:91:12)
#2      LuciBuildService.rescheduleProdBuild (package:cocoon_service/src/service/luci_build_service.dart:400:29)
#3      ResetProdTask.post (package:cocoon_service/src/request_handlers/reset_prod_task.dart:69:28)
<asynchronous suspension>
#4      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
```

**Comment by keyonghan** [comment]
Marked as P0, as it blocking the tree.

**Comment by keyonghan** [comment]
Cocoon is now running on a test version, causing the failures.
Now switched it back to latest version, and re-run works.
