### ISSUE TITLE
ScrollController not attached to any scroll views.

### ISSUE THREAD

**Issue by osmanrami** [flutter/flutter#72302]
Hello Flutter ! 
I'm having troubles dealing with this issue, I'm using a Page controller to switch between my application pages, I'm using NeverScrollableScrollPhysics physics for my page view and my application is throwing this error: 

```bash
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: ScrollController not attached to any scroll views.
flutter: 'package:flutter/src/widgets/scroll_controller.dart':
flutter: Failed assertion: line 112 pos 12: '_positions.isNotEmpty'`

`flutter: When the exception was thrown, this was the stack:
flutter: #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:112:12)
flutter: #3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:203:41)
flutter: #4      MainScreenState._incrementTab.<anonymous closure> (package:havatar/Screens/MainScreen.dart:44:23)
flutter: #5      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
flutter: #6      MainScreenState._incrementTab (package:havatar/Screens/MainScreen.dart:42:5)
flutter: #7      MainScreenState.build.<anonymous closure> (package:havatar/Screens/MainScreen.dart:131:13)
flutter: #8      _BottomNavigationBarState._createTiles.<anonymous closure> (package:flutter/src/material/bottom_navigation_bar.dart:896:25)
flutter: #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
flutter: #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
flutter: #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
flutter: #12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
flutter: #13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
flutter: #14     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
flutter: #15     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
flutter: #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
flutter: #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
flutter: #18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
flutter: #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
flutter: #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
flutter: #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
flutter: #25     _invoke1 (dart:ui/hooks.dart:265:10)
flutter: #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
flutter: (elided 5 frames from class _AssertionError and dart:async)
 ```

I'm using FutureBuilder to get my data from Firebase, the PageView is shown after all data are loaded, if they are not a loading  Indicator BallPulseIndicator is shown. 

I'm not using any scrollview.

**Comment by osmanrami** [comment]
If you need more information please let me know ! Thank you for your help.

**Comment by TahaTesser** [comment]
Hi @osmanrami 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by osmanrami** [comment]
Hello @TahaTesser, thank you for your answer, I found a solution for my problem, instead of initialising my ScrollController in the initState, I did it in my build function for the future, and it solved the problem.
Thank you for your help.
