### ISSUE TITLE
Error in running in profile mode iOS

### ISSUE THREAD

**Issue by tapizquent** [flutter/flutter#72326]
## Steps to Reproduce

Ever since upgrading Flutter, when I try to run the app in profile mode, the app quit after Xcode Build Done. I have included the last few lines of the logs when running in verbose mode

<details>
  <summary>Logs</summary>

```
[        ] Application launched on the device. Waiting for observatory port.
[+30017 ms] Installing and launching... (completed in 53.0s)
[   +1 ms] Error running application on TapPhone.
[   +4 ms] "flutter run" took 622,320ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:617:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1080:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:931:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +10 ms] (lldb) process detach
[  +97 ms] ensureAnalyticsSent: 100ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 2
```

```
Running "flutter pub get" in icay...                             1,311ms
Analyzing icay...                                                       
No issues found! (ran in 8.3s)
```

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/josetapizquent/Projects/Tools/flutter
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/josetapizquent/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • TapPhone (mobile) • 00008020-000E58220E99002E • ios            • iOS 14.2
    • Web Server (web)  • web-server                • web-javascript • Flutter Tools
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome
      87.0.4280.88
    ! Error: TapPhone is busy: Copying cache files from device. Xcode will continue when
      TapPhone is finished. (code -10)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @tapizquent 
Tried to reproduce using it on a physical device in profile mode, no issues on beta or stable. 

Can you please provide your complete `flutter run  --profile --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by tapizquent** [comment]
Hi @TahaTesser 

The full terminal output is here:

https://gist.github.com/tapizquent/c021355916b4c494851381570be927cb

I do not have a reproducible project, as I have no way of identifying why this is not working. It only happens when I run it as Profile mode. It runs correctly when running it from Xcode.

Note that everything runs fine until it tries to open the observatory port. It even launches the app in the phone but then quits.

**Comment by tapizquent** [comment]
Closing as this seems to be a duplicate of #72161.

I will add that this happens only on v1.24, I went back to the stable channel, which is currently v1.22 and the launch error is no longer present.
