### ISSUE TITLE
Exception caught by scheduler library

### ISSUE THREAD

**Issue by misici234** [flutter/flutter#72355]
```bash
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Child SemanticsNode#154(STALE, owner: null, Rect.fromLTRB(50.0, 950.0, 374.0, 949.0), invisible, label: "Walton, Charlotte: H0015-IOP MH  with Misic, Boris11 45 PM-11 45 PM 14/December/2020", textDirection: ltr) is invisible and should not be added as a child of SemanticsNode#113(Rect.fromLTRB(0.0, 350.0, 375.0, 841.0)).
'package:flutter/src/semantics/semantics.dart':
Failed assertion: line 1417 pos 16: '!child.isInvisible'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      SemanticsNode._replaceChildren (package:flutter/src/semantics/semantics.dart:1417:16)
#3      SemanticsNode.updateWith (package:flutter/src/semantics/semantics.dart:1878:5)
#4      RenderObject.assembleSemanticsNode (package:flutter/src/rendering/object.dart:2778:10)
#5      RenderCustomPaint.assembleSemanticsNode (package:flutter/src/rendering/custom_paint.dart:644:11)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3717:13)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

flutter doctor

```bash
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-CA)
    • Flutter version 1.22.3 at ...
    • Framework revision 8874f21e79 (7 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
```

**Comment by TahaTesser** [comment]
Hi @misici234 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
