### ISSUE TITLE
[tool_crash] StateError: Bad state: Unable to start build daemon.

### ISSUE THREAD

**Issue by lockerfish** [flutter/flutter#72362]
## Command
```
flutter test --platform chrome
```

## Steps to Reproduce
1. **Test Code**
final config = AppConfig.init();

AppConfig is a plugin that relies on **dart:html** when running in the web and **dart:io** when running on mobile or desktop.
 
2. Error

It fails to find the correct library. 

../../../../Development/flutter/packages/_flutter_web_build_script/lib/build_script.dart:8:8: Error: Error when reading
'../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/**build-1.3.0**/lib/build.dart': No such file or directory
import 'package:build/build.dart';

Not sure if related but the '.pub-cache' directory is NOT in the .../Development/flutter/ directory. It is located in the user root ~/.pub-cache

flutter pub cache repair reinstalls all packages successfully in the root folder ~/.pub-cache

The **build-1.3.0** folder is not located in ~/.pub-cache/hosted/pub.dartlang.org/ directory

## Logs
StateError: Bad state: Unable to start build daemon.
```
#0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:5)
<asynchronous suspension>
#2      BuildDaemonCreator.startBuildDaemon (package:flutter_tools/src/isolated/web_compilation_delegate.dart:139:40)
<asynchronous suspension>
#3      BuildRunnerWebCompilationProxy.initialize (package:flutter_tools/src/isolated/web_compilation_delegate.dart:44:38)
<asynchronous suspension>
#4      _FlutterTestRunnerImpl.runTests (package:flutter_tools/src/test/runner.dart:122:27)
<asynchronous suspension>
#5      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:241:24)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1080:12)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:931:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B50 darwin-x64, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/hendrix/Development/flutter
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hendrix/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 94BAY0M38B • android-arm64  • Android 11 (API 30)
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 198df796aa80073ef22bdf249e614e2ff33c6895
### Plugins
integration_test-1.0.1

**Comment by lockerfish** [comment]
I fixed the issue by running `flutter update-packages --force-upgrade`. It upgraded all the packages to the correct version.  I am wondering if it possible to clear pub-cache and do a force-upgrade on the tools to avoid this issue.
