### ISSUE TITLE
I design it custom and add row and text Field in row but error

### ISSUE THREAD

**Issue by muhammadasif146** [flutter/flutter#72361]
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:w_store/Utils/CustombottomBar.dart';

class DarkSearch extends StatefulWidget {
  @override
  _DarkSearchState createState() => _DarkSearchState();
}

class _DarkSearchState extends State<DarkSearch> {

  @override
  Widget build(BuildContext context) {
    int _currentIndex = 0;

    var screensize = MediaQuery.of(context).size;
    return SafeArea(
child: Scaffold(
  backgroundColor: Color.fromRGBO(36,52,65,1),
            bottomNavigationBar: CustomNavigation(),
  body:Container(
    width: screensize.width,
    height: screensize.height,
    color: Color.fromRGBO(36,52,65,1),
                   child: SingleChildScrollView(
                     child: Column(
                       children: [
                         Padding(
                           padding: const EdgeInsets.only(top: 30),
                           child: Container(
                             width: 193,
                             height: 38,
                             child: Image.asset('assets/images/light/logoonSearch.png'),
                           ),
                         ),
                         SizedBox(height: 10,),
                         Container(
                           width: 304,
                           height: 220,
                           child: Image.asset('assets/images/light/home1.png'),
                         ),
    SizedBox(height: 25,),
    Container(
      width: 300,
      height: 58,
      decoration: BoxDecoration(

        color: Color.fromRGBO(36,52,65,1),
        // color: Colors.white.withOpacity(0.07),
        borderRadius: BorderRadius.all(Radius.circular(20)),

        boxShadow: [
          BoxShadow(
            color: Color.fromRGBO(36,52,65,1.0),
            blurRadius: 5,
            offset: Offset(-10, -10),
            spreadRadius: 5,
          ),
          BoxShadow(
            color: Colors.grey.withOpacity(0.04),
            blurRadius: 5,
            offset: Offset(0, 0),
            spreadRadius: 5,
          ),

        ],

      ),
      child:  Container(
          width:295 ,
          height: 58,
          decoration: BoxDecoration(
            //color: Color.fromRGBO(36,52,65,1),
            borderRadius: BorderRadius.all(Radius.circular(20)),
            boxShadow: [
              BoxShadow(
                color: Color.fromRGBO(36,52,65,1.0),
                blurRadius: 5,
                offset: Offset(-10, -10),
                spreadRadius: 5,
              ),
              BoxShadow(
                color: Colors.grey.withOpacity(0.01),
                blurRadius: 5,
                offset: Offset(5, 5),
                spreadRadius: 5,
              ),

            ],

          ),
        child: Row(
children: [
  Padding(
    padding: const EdgeInsets.only(left: 15),
    child: ImageIcon(
      AssetImage('assets/images/drak/search.png'),
      size: 25,
      color: Color.fromRGBO(10,255,239,0.5),
    ),
  ),
  TextField(

    keyboardType: TextInputType.text,
    style: TextStyle(
        color: Colors.grey[800], fontSize: 17),
    decoration: InputDecoration(
      alignLabelWithHint: true,
      border: InputBorder.none,
      hintText: 'What are you ',
      hintStyle: TextStyle(
        fontSize: 5,
        color: Color.fromRGBO(10,255,239,0.5),
      ),
      // labelStyle: TextStyle(color: Colors.black26),
      //   hoverColor: Colors.black26,
    ),

  )
],
        ),
      ),
    ),


                       ],
                     ),
                   ),
  )


),
    );
  }
}
```

**Comment by muhammadasif146** [comment]
please help me

**Comment by muhammadasif146** [comment]
Performing hot reload...
Syncing files to device SM J400F...

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 885 pos 12: '!debugBuildingDirtyElements': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:885:12)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 2 of 538 libraries in 966ms.

**Comment by muhammadasif146** [comment]
error is that

**Comment by pedromassangocode** [comment]
Hi @muhammadasif146 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample that does not uses any third-party package?
Thank you

**Comment by YazeedAlKhalaf** [comment]
@muhammadasif146 Try wrapping the `TextField` inside the row with an `Expanded` widget.
```dart
Row(
  children: <Widget>[
    Padding(
      padding: const EdgeInsets.only(left: 15),
      // child: ImageIcon(
      //   AssetImage('assets/images/drak/search.png'),
      //   size: 25,
      //   color: Color.fromRGBO(10, 255, 239, 0.5),
      // ),
      child: Icon(
        Icons.search,
        size: 25,
        color: Color.fromRGBO(10, 255, 239, 0.5),
      ),
    ),
    Expanded(
      child: TextField(
        keyboardType: TextInputType.text,
        style: TextStyle(color: Colors.grey[800], fontSize: 17),
        decoration: InputDecoration(
          alignLabelWithHint: true,
          border: InputBorder.none,
          hintText: 'What are you searching for?',
          hintStyle: TextStyle(
            fontSize: 15,
            color: Color.fromRGBO(10, 255, 239, 0.5),
          ),
          // labelStyle: TextStyle(color: Colors.black26),
          // hoverColor: Colors.black26,
        ),
      ),
    )
  ],
),
```

This should solve the problem

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
