### ISSUE TITLE
Android license status unknown

### ISSUE THREAD

**Issue by palguy** [flutter/flutter#72419]
```
E:\flutterProjects\flutter_app>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (6 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Lenovo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.0)
    • VS Code at C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```
**When** I run [ flutter doctor --android-licenses ]

```
E:\flutterProjects\flutter_app>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

**Comment by ritvij14** [comment]
Did you try installing `Android SDK Command-line tools` from `Android SDK Manager`? This solved the problem for me which I had in the past.
More details here:- https://stackoverflow.com/questions/61993738/flutter-doctor-android-licenses-gives-a-java-error

**Comment by pedromassangocode** [comment]
Hi @palguy 
See if https://github.com/flutter/flutter/issues/72419#issuecomment-745931644 works for you.

**Comment by palguy** [comment]
> Did you try installing `Android SDK Command-line tools` from `Android SDK Manager`? This solved the problem for me which I had in the past.
> More details here:- https://stackoverflow.com/questions/61993738/flutter-doctor-android-licenses-gives-a-java-error

you saved my day, 
Thank you 👌
