### ISSUE TITLE
Observatory Timeout on iOS (physical device)

### ISSUE THREAD

**Issue by jameshp** [flutter/flutter#72421]
Hi, 
on current master version (Flutter 1.25.0-9.0.pre.69) observatory times out before the iOS 14 "accept debug session dialog" is shown on pysical device. 

Steps to reproduce
1. Creating a default counter app
2. flutter run -d <yourIOsDevice)  (using a physical iPhone 14.2)

Logs at the end for observatory issue: 

```
[ +301 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[        ] [ 60%] InspectingPackage
[  +15 ms] [ 60%] TakingInstallLock
[  +57 ms] [ 65%] PreflightingApplication
[  +44 ms] [ 65%] InstallingEmbeddedProfile
[  +23 ms] [ 70%] VerifyingApplication
[  +93 ms] [ 75%] CreatingContainer
[   +2 ms] [ 80%] InstallingApplication
[  +12 ms] [ 85%] PostflightingApplication
[   +2 ms] [ 90%] SandboxingApplication
[  +11 ms] [ 95%] GeneratingApplicationMap
[  +55 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[ +153 ms] ------ Debug phase ------
[        ] Starting debug of b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7 (D221AP, iPhone X, iphoneos, arm64) a.k.a. 'iPhone' connected through USB...
[ +108 ms] [  0%] Looking up developer disk image
[  +10 ms] [ 95%] Developer disk image mounted successfully
[ +420 ms] [100%] Connecting to remote debug server
[        ] -------------------------
[  +84 ms] (lldb) command source -s 0 '/tmp/F461D48B-A6A2-47EF-BCFB-BF1DD7490F33/fruitstrap-lldb-prep-cmds-b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7'
[        ] Executing commands in '/tmp/F461D48B-A6A2-47EF-BCFB-BF1DD7490F33/fruitstrap-lldb-prep-cmds-b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols"
[        ] (lldb)     target create "/Users/michaelpolt/Documents/autocompleteTest2/build/ios/iphoneos/Runner.app"
[ +297 ms] Current executable set to '/Users/michaelpolt/Documents/autocompleteTest2/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/0C4BA6F1-C5F5-4D2A-8C66-734447242F57/Runner.app"
[ +406 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:56371"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols/usr" /System "/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols/System" "/private/var/containers/Bundle/Application/0C4BA6F1-C5F5-4D2A-8C66-734447242F57" "/Users/michaelpolt/Documents/autocompleteTest2/build/ios/iphoneos" "/var/containers/Bundle/Application/0C4BA6F1-C5F5-4D2A-8C66-734447242F57" "/Users/michaelpolt/Documents/autocompleteTest2/build/ios/iphoneos" /Developer "/Users/michaelpolt/Library/Developer/Xcode/iOS DeviceSupport/14.2 (18B92)/Symbols/Developer"
[  +10 ms] (lldb)     command script import "/tmp/F461D48B-A6A2-47EF-BCFB-BF1DD7490F33/fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.py"
[   +4 ms] (lldb)     command script add -f fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7.safequit_command safequit
[        ] (lldb)     connect
[  +32 ms] (lldb)     run
[ +198 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+30019 ms] Installing and launching... (completed in 46.3s)
[        ] Error launching application on iPhone.
[   +3 ms] "flutter run" took 73,844ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:72:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:89:3)
           <asynchronous suspension>


[   +1 ms] (lldb) process detach
[ +254 ms] ensureAnalyticsSent: 255ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

Other Notes:
this is not an issue when building for a simulator

running the app through command line as above, even if the timeout happens, the dialog shows (sometimes, or till the first time accepted?) up after the timeout to accept the local network permission. the app is then useable but not debuggable. 
Also after first acceptance (app has local network permissions) and the app is run again, observatory times out. 

running the app directly in Xcode results in following logs. 
Here i see also very long a white screen before anything is shown, but it seems the timeout here is longer. But here i don't get a dialog, instead some warning that some config fro add-to-app scenarios should be added, which should not be the case here i guess. 

Logs when running the app through Xcode (if the app is installed new and was deleted before, no dialog appeared): 
```2020-12-16 03:14:06.139509-0500 Runner[573:113711] Metal API Validation Enabled
2020-12-16 03:14:06.820984-0500 Runner[573:114313] flutter: Observatory listening on http://127.0.0.1:51858/83pFhGqS6ng=/
2020-12-16 03:14:07.316068-0500 Runner[573:113711] [VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
2020-12-16 03:14:07.316261-0500 Runner[573:113711] [VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
2020-12-16 03:14:07.362651-0500 Runner[573:114303] fopen failed for data file: errno = 2 (No such file or directory)
2020-12-16 03:14:07.362759-0500 Runner[573:114303] Errors found! Invalidating cache...
2020-12-16 03:14:07.450956-0500 Runner[573:114303] fopen failed for data file: errno = 2 (No such file or directory)
2020-12-16 03:14:07.451046-0500 Runner[573:114303] Errors found! Invalidating cache...
```

my flutter doctor 
```
fvm flutter doctor -v
[✓] Flutter (Channel master, 1.25.0-9.0.pre.69, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-9.0.pre.69 at /Users/michaelpolt/fvm/versions/master
    • Framework revision 10bc7db652 (12 hours ago), 2020-12-15 16:08:02 -0500
    • Engine revision fead6dc01f
    • Dart version 2.12.0 (build 2.12.0-154.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/michaelpolt/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/michaelpolt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • iPhone (mobile)                                • b7e07e1a4193ad6bc077834936ea5fdcf8b80cf7 • ios            • iOS 14.2
    • iPad Pro (12.9-inch) (4th generation) (mobile) • 854827D3-BF66-4DDC-929A-B4EF5F7EFAFA     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Chrome (web)                                   • chrome                                   • web-javascript • Google Chrome 87.0.4280.88
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)
    ! Error: iPhone 6s dev is not connected. Xcode will continue when iPhone 6s dev is connected. (code -13)

```

**Comment by TahaTesser** [comment]
Hi @jameshp 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/72161
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
