### ISSUE TITLE
Support for English fallback even when an unsupported language is selected

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#72422]
By @brickpop in https://github.com/flutter/flutter/issues/72284:

```
The point is that we have the strings, but the material widgets throw an error when the (unsupported) language is selected.

If some language is unsupported, would it be possible to at least bypass the error on the Material boundaries and use a fallback there? This would allow us to display our localized strings, even if the widget tooltips remain in English.
```

I'll try to come up with a reproducible sample in a small app, but if you get the chance before I do, could you share one @brickpop? It helps with confirming that the issue is fixed and provides a good template for a test to prevent regressions.

**Comment by brickpop** [comment]
The closest I can get to a working example now, is a branch of the app itself:

- Git clone https://gitlab.com/vocdoni/client-mobile.git
- Switch to the `gh/esperanto` branch
- Run `make init` and `make run` to launch the app on an Android device
- Enter whatever name and a lock pattern to skip the initial screen
- On the Identity tab, tap Settings > Select language > Esperanto

Any language will work, but selecting Esperanto will fail.

- Locale declarations: https://gitlab.com/vocdoni/client-mobile/-/blob/gh/esperanto/lib/main.dart#L60-66
- Locale switch handlers: 
  - https://gitlab.com/vocdoni/client-mobile/-/blob/gh/esperanto/lib/data-models/app-state.dart#L56
  - https://gitlab.com/vocdoni/client-mobile/-/blob/gh/esperanto/lib/lib/i18n.dart#L68
- In the next render,  the UI is broken

```
I/flutter (32211): ════════
I/flutter (32211): Warning: This application's locale, eo, is not supported by all of its
I/flutter (32211): localization delegates.
I/flutter (32211): > A MaterialLocalizations delegate that supports the eo locale was not found.
I/flutter (32211): See https://flutter.dev/tutorials/internationalization/ for more
I/flutter (32211): information about configuring an app's locale, supportedLocales,
I/flutter (32211): and localizationsDelegates parameters.
I/flutter (32211): ════════

...

I/flutter (32211): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (32211): The following assertion was thrown building AppBar(dirty, dependencies: [_ModalScopeStatus,
I/flutter (32211): _InheritedTheme, _LocalizationsScope-[GlobalKey#a2916], MediaQuery], state: _AppBarState#a1efc):
I/flutter (32211): No MaterialLocalizations found.
I/flutter (32211): AppBar widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
I/flutter (32211): The material library uses Localizations to generate messages, labels, and abbreviations.
I/flutter (32211): To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to
I/flutter (32211): include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
I/flutter (32211): The specific widget that could not find a MaterialLocalizations ancestor was:
I/flutter (32211):   AppBar
I/flutter (32211): The ancestors of this widget were:
I/flutter (32211):   ...
I/flutter (32211):   TopNavigation
I/flutter (32211):   FlexibleSpaceBarSettings
I/flutter (32211):   ConstrainedBox
I/flutter (32211):   MediaQuery
I/flutter (32211):   LayoutId-[<_ScaffoldSlot.appBar>]
I/flutter (32211):   ...
I/flutter (32211): 
I/flutter (32211): The relevant error-causing widget was:
I/flutter (32211):   AppBar
I/flutter (32211):   file:///Users/user/dev/flutter/.pub-cache/git/dvote-flutter-common-1d5231bd70c05560c07bbde83b93ca6feb2d0844/lib/widgets/topNavigation.dart:14:12
I/flutter (32211): 
I/flutter (32211): When the exception was thrown, this was the stack:
I/flutter (32211): #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:74:7)
I/flutter (32211): #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:94:4)
I/flutter (32211): #2      _AppBarState.build (package:flutter/src/material/app_bar.dart:509:12)
I/flutter (32211): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
I/flutter (32211): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter (32211): #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (32211): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter (32211): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
I/flutter (32211): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #15     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter (32211): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter (32211): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter (32211): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #25     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter (32211): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #27     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
I/flutter (32211): #28     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
I/flutter (32211): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (32211): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter (32211): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #37     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter (32211): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (32211): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter (32211): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter (32211): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #48     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
I/flutter (32211): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter (32211): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #53     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (32211): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #55     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter (32211): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (32211): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter (32211): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #64     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter (32211): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #68     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter (32211): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (32211): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter (32211): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (32211): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (32211): #76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (32211): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (32211): #78     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter (32211): #79     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter (32211): #80     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (32211): #81     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (32211): #82     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (32211): #83     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (32211): #87     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (32211): #88     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (32211): (elided 3 frames from dart:async)
I/flutter (32211): 
I/flutter (32211): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Thank you @shihaohong
