### ISSUE TITLE
gn host cannot generate --enable-vulkan

### ISSUE THREAD

**Issue by tongweizhou** [flutter/flutter#72426]
I'm trying to use the enable-vulkan engine in android.
1.gn host
    ./flutter/tools/gn --unopt --runtime-mode=profile --android-cpu=arm64 
2.gn android
  ./flutter/tools/gn --unopt --runtime-mode=profile --android --android-cpu=arm64  --enable-vulkan
3.ninja build
ninja -C out/host_profile_unopt_arm64
ninja -C out/android_profile_unopt_arm64_vulkan

4.flutter run demo use local engine
flutter run --local-engine-src-path=/Users/bytedance/workspace/engine_1.22/src --local-engine=android_profile_unopt_arm64
<img width="1511" alt="截屏2020-12-16 下午7 50 42" src="https://user-images.githubusercontent.com/74553848/102346723-494aee80-3fda-11eb-8ac0-d394a6857d14.png">

5.try to gn --enable-vulkan
<img width="1321" alt="截屏2020-12-16 下午7 50 04" src="https://user-images.githubusercontent.com/74553848/102346804-6ed7f800-3fda-11eb-8840-b96f49abf533.png">

SO,flutter tools or gn may need to be modified?

**Comment by tongweizhou** [comment]
bytedance@MacBook-Pro flutter % git diff tools/gn
diff --git a/tools/gn b/tools/gn
index 4e83447dd1..1197d9251e 100755
--- a/tools/gn
+++ b/tools/gn
@@ -82,8 +82,8 @@ def to_gn_args(args):
         if args.target_os == 'android':
             raise Exception('--simulator is not supported on Android')
 
-    if args.target_os != 'android' and args.enable_vulkan:
-      raise Exception('--enable-vulkan is only supported on Android')
+    #if args.target_os != 'android' and args.enable_vulkan:
+    #  raise Exception('--enable-vulkan is only supported on Android')
 
     runtime_mode = args.runtime_mode


work fine

**Comment by tongweizhou** [comment]
<img width="1177" alt="截屏2020-12-16 下午8 33 42" src="https://user-images.githubusercontent.com/74553848/102349523-6aadd980-3fde-11eb-8358-834160f1c057.png">


ninja -C out/host_profile_unopt_arm64_vulkan failed

**Comment by tongweizhou** [comment]
//#if SKIA_IMPLEMENTATION || !defined(SK_VULKAN)
#include "include/third_party/vulkan/vulkan/vulkan_core.h"
//#else
// For google3 builds we don't set SKIA_IMPLEMENTATION so we need to make sure that the vulkan
// headers stay up to date for our needs
//#include <vulkan/vulkan_core.h>
//#endif
 
tmp  fix

**Comment by tongweizhou** [comment]
run helloword failed

bytedance@MacBook-Pro helloword % flutter run --local-engine-src-path=/Users/bytedance/workspace/engine_1.22/src --local-engine=android_profile_unopt_arm64
current cmd: flutter  run --local-engine-src-path=/Users/bytedance/workspace/engine_1.22/src --local-engine=android_profile_unopt_arm64
Launching lib/main.dart on Mi 10 in debug mode...
Unhandled exception:                                                    
Crash when compiling file:///Users/bytedance/workspace/toutiao/1.22_flutter/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart,
at character offset 26694:                                              
Bad state: No element                                                   
#0      List.single (dart:core-patch/growable_array.dart:260:22)        
#1      ClassBuilderImpl.buildTypesWithBuiltArguments (package:front_end/src/fasta/builder/class_builder.dart:568:43)
#2      ClassBuilderImpl.buildType (package:front_end/src/fasta/builder/class_builder.dart:623:12)
#3      NamedTypeBuilder.build (package:front_end/src/fasta/builder/named_type_builder.dart:275:24)
#4      FunctionTypeBuilder.build (package:front_end/src/fasta/builder/function_type_builder.dart:81:21)
#5      BodyBuilder.buildDartType (package:front_end/src/fasta/kernel/body_builder.dart:6285:11)
#6      BodyBuilder.endFormalParameter (package:front_end/src/fasta/kernel/body_builder.dart:3480:7)
#7      Parser.parseFormalParameter (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1632:14)
#8      Parser.parseOptionalNamedParameters (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1704:11)
#9      Parser.parseFormalParametersRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1342:17)
#10     Parser.parseFormalParameters (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1316:12)
#11     Parser.parseFormalParametersOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1276:15)
#12     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:976:22)
#13     DietListener._endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:714:5)
#14     DietListener.endMixinMethod (package:front_end/src/fasta/source/diet_listener.dart:679:5)
#15     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3809:20)
#16     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3546:15)
#17     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3220:15)
#18     Parser.parseMixin (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2100:13)
#19     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:619:18)
#20     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:476:14)
#21     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:356:15)
#22     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:427:14)

**Comment by tongweizhou** [comment]
**flutter run helloword**  

 flutter run --local-engine-src-path=/Users/bytedance/workspace/engine_1.22/src --local-engine=android_profile_unopt_arm64_vulkan --profile

works fine

**Comment by TahaTesser** [comment]
Hi @tongweizhou 
Please avoid posting screenshots when not needed, it's always better to copy/paste logs instead 
Can you please provide your `flutter doctor  -v` and step by step to reproduce the issue
Thank you

**Comment by tongweizhou** [comment]
@TahaTesser 
Above is the step-by-step. 
I was able to compile and run the demo with the above modifications .
I'm trying to run benchmark locally using the vulkan engine.
Have you tested the vulkan version of the engine?

----------------------------------------------------
current cmd: flutter  doctor -v
[✓] Flutter (Channel bd_1.22, v1.22.3-0.0.pre.58, bd1.22.3-2, changelog https://code.byted.org/tech_client/flutter/blob/bd_1.22/CHANGELOG.md, on Mac OS X 10.15.5 19F101
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.3-0.0.pre.58 bd1.22.3-2 at /Users/bytedance/workspace/toutiao/1.22_flutter/flutter
    • Changelog https://code.byted.org/tech_client/flutter/blob/bd_1.22/CHANGELOG.md
    • Framework revision a32f132acb (3 weeks ago), 2020-11-26 19:56:09 +0800
    • Engine revision 3a0afa2ace
    • Dart version 2.10.4
    • Pub download mirror https://dart-pub.byted.org
    • Flutter download mirror https://storage.flutter-io.cn

-------------------
step-by-step. 
----------------------------------------------------
1.gn host ./flutter/tools/gn --unopt --runtime-mode=profile --android-cpu=arm64
2. gn android ./flutter/tools/gn --unopt --runtime-mode=profile --android --android-cpu=arm64 --enable-vulkan
3. ninja build ninja -C out/host_profile_unopt_arm64 ninja -C out/android_profile_unopt_arm64_vulkan

4.flutter run demo use local engine
flutter run --local-engine-src-path=/Users/bytedance/workspace/engine_1.22/src --local-engine=android_profile_unopt_arm64
5.try to gn --enable-vulkan

**Comment by TahaTesser** [comment]
Hi @tongweizhou 
```bash
tahatesser@Tahas-MacBook-Pro src % ./flutter/tools/gn --unopt --runtime-mode=profile --android-cpu=arm64

GOMA usage was specified but can't be found, falling back to local builds. Set the GOMA_DIR environment variable to fix GOMA.
Generating GN files in: out/host_profile_unopt_arm64
Generating Xcode projects took 334ms
Done. Made 726 targets from 220 files in 1803ms
tahatesser@Tahas-MacBook-Pro src % ./flutter/tools/gn --unopt --runtime-mode=profile --android --android-cpu=arm64 --enable-vulkan
GOMA usage was specified but can't be found, falling back to local builds. Set the GOMA_DIR environment variable to fix GOMA.
Generating GN files in: out/android_profile_unopt_arm64_vulkan
Generating Xcode projects took 127ms
Done. Made 437 targets from 191 files in 2775ms
tahatesser@Tahas-MacBook-Pro src % ninja build ninja -C out/host_profile_unopt_arm64 ninja -C out/android_profile_unopt_arm64_vulkan
ninja: Entering directory `out/android_profile_unopt_arm64_vulkan'
ninja: error: unknown target 'build', did you mean 'ui'?
tahatesser@Tahas-MacBook-Pro src % 
```

Following your steps, I'm getting the following output.

**Comment by tongweizhou** [comment]
@TahaTesser    Reproduction is just one step：

./flutter/tools/gn --enable-vulkan

**Comment by TahaTesser** [comment]
Hi  @tongweizhou 
`./flutter/tools/gn --enable-vulkan` is incorrect, it needs to android platform.
So here I what did to reproduce and run the app

```bash
./flutter/tools/gn --android --unoptimized
./flutter/tools/gn --android --unoptimized --android-cpu=arm64 --enable-vulkan
./flutter/tools/gn --unoptimized
```
then built with 

```bash
ninja -C out/android_debug_unopt
ninja -C out/android_debug_unopt_arm64_vulkan
ninja -C out/host_debug_unopt
```

Not sure how to confirm if the render is running in vulkan, no errors and issues in the app 

<details> 
<summary>logs</summary> 

```bash
tahatesser@Tahas-MacBook-Pro master_flutter % flutterm run --local-engine-src-path /Volumes/Extreme/engine/src  --local-engine=android_debug_unopt
Launching lib/main.dart on RMX2001 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        36.5s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 5.4s
E/flutter (19385): [ERROR:flutter/shell/common/shell.cc(838)] Embedding reported invalid ViewportMetrics, ignoring update.
E/flutter (19385): physical_width: 0
E/flutter (19385): physical_height: 0
E/flutter (19385): device_pixel_ratio: 3
E/flutter (19385): [ERROR:flutter/shell/common/shell.cc(838)] Embedding reported invalid ViewportMetrics, ignoring update.
E/flutter (19385): physical_width: 0
E/flutter (19385): physical_height: 0
E/flutter (19385): device_pixel_ratio: 3
I/flutter (19385): A message on the flutter/lifecycle channel was discarded before it could be handled.
I/flutter (19385): This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get discarded:
I/flutter (19385):   https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
Syncing files to device RMX2001...                                 184ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on RMX2001 is available at: http://127.0.0.1:60895/doa0pVOqiXk=/

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.86, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.86 at /Users/tahatesser/Code/flutter_master
    • Framework revision b793285329 (3 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

**Comment by tongweizhou** [comment]
@TahaTesser  please use 
flutter run --local-engine-src-path /Volumes/Extreme/engine/src  --local-engine=android_debug_unopt_arm64_vulkan

**Comment by TahaTesser** [comment]
Hi @tongweizhou 
I see the same output 
```bash
tahatesser@Tahas-MacBook-Pro master_flutter % flutterm run --local-engine-src-path /Volumes/Extreme/engine/src --local-engine=android_debug_unopt_arm64_vulkan
No Flutter engine build found at /Volumes/Extreme/engine/src/out/host_debug_unopt_arm64_vulkan.
tahatesser@Tahas-MacBook-Pro master_flutter % 
```

**Comment by jason-simmons** [comment]
You may need to create a symlink that maps the `host_profile_unopt_arm64` output directory to the `host_profile_unopt` name expected by the Flutter tools

**Comment by tongweizhou** [comment]
@jason-simmons  It's a good idea.   But I'm curious to know if you  have tested the vulkan-related features specifically now.
