### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.Receiver: nullTried calling: cancel()

### ISSUE THREAD

**Issue by yanghua0726** [flutter/flutter#72499]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:969:11)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:750:5)
#3      AnsiStatus.stop (package:flutter_tools/src/base/logger.dart:1051:11)
#4      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1506:16)
<asynchronous suspension>
#5      ArtifactUpdater.downloadZipArchive (package:flutter_tools/src/cache.dart:1442:12)
#6      MaterialFonts.updateInner (package:flutter_tools/src/cache.dart:607:28)
#7      CachedArtifact.update (package:flutter_tools/src/cache.dart:573:11)
#8      Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:882:27)
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:790:33)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.159, on Microsoft Windows [Version 10.0.18362.1139], locale zh-CN)
    • Flutter version 1.22.0-2.0.pre.159 at D:\flutter
    • Framework revision 8f33383699 (4 months ago), 2020-08-31 20:28:04 -0400
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://pub.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Android\SDK
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Android Studio (version 4.0)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • LIO AN00 (mobile) • emulator-5554 • android-x86 • Android 5.1.1 (API 22)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by pedromassangocode** [comment]
Hi @yanghua0726 
Looks like you are using a four months old Flutter version. This issue may already been fixed.
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by yanghua0726** [comment]
Great! It solved the problem perfectly, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 下午4:57
收件人:&nbsp;"flutter/flutter"<flutter@noreply.github.com&gt;;
抄送:&nbsp;"华"<1277231541@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [flutter/flutter] [tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'cancel' was called on null.Receiver: nullTried calling: cancel() (#72499)





 
Hi @yanghua0726
 Looks like you are using a four months old Flutter version. This issue may already been fixed.
 Can you please upgrade to the latest  master and try again
 flutter channel master
 flutter upgrade --force
 flutter doctor -v

**Comment by pedromassangocode** [comment]
Hi @yanghua0726 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
