### ISSUE TITLE
cocoon authentication error not reported as infra failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#72520]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20basic_material_app_android__compile/146/overview

```
â•â•â•â•â•â•â•â•â•¡ â€¢â€¢â€¢ Finished task "basic_material_app_android__compile" â€¢â€¢â€¢ â•žâ•â•â•â•â•â•â•â•â•

Unhandled exception:
AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/update-task-status
  HTTP Status: 401
  Response body:
Invalid access token
#0      AuthenticatedCocoonClient.send (package:flutter_devicelab/framework/cocoon.dart:159:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:32)
<asynchronous suspension>
#2      retry (package:flutter_devicelab/framework/utils.dart:773:14)
<asynchronous suspension>
#3      Cocoon._sendCocoonRequest (package:flutter_devicelab/framework/cocoon.dart:115:31)
<asynchronous suspension>
#4      Cocoon.sendTaskResult (package:flutter_devicelab/framework/cocoon.dart:100:43)
<asynchronous suspension>
#5      _runTasks (file:///opt/s/w/ir/k/flutter/dev/devicelab/bin/run.dart:126:7)
<asynchronous suspension>
#6      main (file:///opt/s/w/ir/k/flutter/dev/devicelab/bin/run.dart:104:5)
<asynchronous suspension>
```

@godofredoc

**Comment by keyonghan** [comment]
Here is the issue: https://github.com/flutter/flutter/issues/72457
Marked as duplicate.
