### ISSUE TITLE
Crash on first run on beta channel: NDK at C:\Users\SPeller\AppData\Local\Android\sdk\ndk-bundle did not have a source.properties file

### ISSUE THREAD

**Issue by speller** [flutter/flutter#72639]
On the beta channel, I can't build a default empty app.

## Steps to Reproduce

1. `flutter create myapp`
2. `cd myapp`
3. `flutter run`

**Expected results:** 

The default app is built successfully.

**Actual results:** 

<details><summary>Logs</summary>

```
flutter run --verbose
[  +77 ms] executing: [c:\develop\soft\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +91 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 8f89f6505b941329a864fef1527243a72800bf4d
[  +19 ms] executing: [c:\develop\soft\flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[ +158 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[   +5 ms] 1.25.0-8.1.pre
[  +41 ms] executing: [c:\develop\soft\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +84 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/beta
[  +15 ms] executing: [c:\develop\soft\flutter/] git ls-remote --get-url origin
[  +74 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[  +96 ms] executing: [c:\develop\soft\flutter/] git rev-parse --abbrev-ref HEAD
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +18 ms] beta
[  +65 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +20 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +100 ms] executing: C:\Users\SPeller\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +62 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64
           device:generic_x86_64 transport_id:1
[  +21 ms] C:\Users\SPeller\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +57 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +123 ms] Skipping pub get: version match.
[  +97 ms] Found plugin integration_test at c:\develop\soft\flutter\packages\integration_test\
[ +133 ms] Found plugin integration_test at c:\develop\soft\flutter\packages\integration_test\
[   +9 ms] Generating
C:\develop\projects\helpdesk\app\test-test\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.ja
va
[  +72 ms] ro.hardware = ranchu
[  +22 ms] Using hardware rendering with device Android SDK built for x86 64. If you notice graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +28 ms] Initializing file store
[  +46 ms] Skipping target: gen_localizations
[   +8 ms] complete
[  +24 ms] Launching lib\main.dart on Android SDK built for x86 64 in debug mode...
[  +22 ms] c:\develop\soft\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
c:\develop\soft\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
c:\develop\soft\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\SPeller\AppData\Local\Temp\flutter_tools.b570c180\flutter_tool.a2e458bb\app.dill --packages
C:\develop\projects\helpdesk\app\test-test\myapp\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[  +26 ms] executing: C:\Users\SPeller\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat
-v time -t 1
[  +35 ms] <- compile package:myapp/main.dart
[  +58 ms] --------- beginning of main
           12-19 07:07:56.734 I/GnssLocationProvider( 1873): WakeLock released by handleMessage(REPORT_SV_STATUS, 0,
           com.android.server.location.GnssLocationProvider$SvStatusInfo@c0875a)
[  +24 ms] executing: C:\Users\SPeller\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +34 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Users\SPeller\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +32 ms] executing: C:\Users\SPeller\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +71 ms] Building APK
[  +49 ms] Running Gradle task 'assembleDebug'...
[  +15 ms] Using gradle from C:\develop\projects\helpdesk\app\test-test\myapp\android\gradlew.bat.
[   +6 ms] C:\develop\projects\helpdesk\app\test-test\myapp\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +29 ms] executing: C:\Users\SPeller\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
-version
[ +149 ms] Exit code 0 from:
C:\Users\SPeller\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java -version
[   +4 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +16 ms] executing: [C:\develop\projects\helpdesk\app\test-test\myapp\android/]
C:\develop\projects\helpdesk\app\test-test\myapp\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x64
-Ptarget=C:\develop\projects\helpdesk\app\test-test\myapp\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1033 ms] Welcome to Gradle 6.7!
[  +20 ms] Here are the highlights of this release:
[   +1 ms]  - File system watching is ready for production use
[   +2 ms]  - Declare the version of Java your build requires
[   +1 ms]  - Java 15 support
[   +1 ms] For more details see https://docs.gradle.org/6.7/release-notes.html
[+2450 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +4 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[  +17 ms] > Task :app:preBuild UP-TO-DATE
[   +3 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +8 ms] > Task :integration_test:preBuild UP-TO-DATE
[  +36 ms] > Task :integration_test:preDebugBuild UP-TO-DATE
[   +9 ms] > Task :integration_test:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[  +22 ms] > Task :integration_test:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +23 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
[  +23 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[  +47 ms] > Task :app:cleanMergeDebugAssets
[   +4 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[  +23 ms] > Task :app:compileDebugShaders NO-SOURCE
[  +14 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +2 ms] > Task :integration_test:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :integration_test:compileDebugShaders NO-SOURCE
[   +5 ms] > Task :integration_test:generateDebugAssets UP-TO-DATE
[  +23 ms] > Task :integration_test:packageDebugAssets UP-TO-DATE
[  +14 ms] > Task :app:mergeDebugAssets
[ +309 ms] > Task :app:copyFlutterAssetsDebug
[   +5 ms] > Task :app:generateDebugResValues UP-TO-DATE
[  +20 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +14 ms] > Task :integration_test:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :integration_test:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :integration_test:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :integration_test:packageDebugResources UP-TO-DATE
[  +48 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +5 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +20 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[  +27 ms] > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
[   +4 ms] > Task :integration_test:processDebugManifest UP-TO-DATE
[  +22 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[  +27 ms] > Task :app:processDebugManifest UP-TO-DATE
[  +27 ms] > Task :app:processDebugManifestForPackage UP-TO-DATE
[  +13 ms] > Task :integration_test:compileDebugLibraryResources UP-TO-DATE
[   +1 ms] > Task :integration_test:parseDebugLocalResources UP-TO-DATE
[   +2 ms] > Task :integration_test:generateDebugRFile UP-TO-DATE
[  +55 ms] > Task :app:processDebugResources UP-TO-DATE
[   +7 ms] > Task :integration_test:generateDebugBuildConfig UP-TO-DATE
[  +23 ms] > Task :integration_test:javaPreCompileDebug UP-TO-DATE
[  +58 ms] > Task :integration_test:compileDebugJavaWithJavac UP-TO-DATE
[   +5 ms] > Task :integration_test:bundleLibCompileToJarDebug UP-TO-DATE
[ +108 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[  +10 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +13 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[   +6 ms] > Task :app:compressDebugAssets UP-TO-DATE
[  +19 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :integration_test:processDebugJavaRes NO-SOURCE
[  +18 ms] > Task :integration_test:bundleLibResDebug NO-SOURCE
[   +1 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[   +7 ms] > Task :integration_test:bundleLibRuntimeToJarDebug UP-TO-DATE
[  +22 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +1 ms] > Task :app:dexBuilderDebug UP-TO-DATE
[  +80 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[   +5 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[  +19 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +18 ms] > Task :integration_test:mergeDebugJniLibFolders UP-TO-DATE
[  +66 ms] > Task :integration_test:mergeDebugNativeLibs NO-SOURCE
[   +4 ms] > Task :integration_test:stripDebugDebugSymbols NO-SOURCE
[  +17 ms] > Task :integration_test:copyDebugJniLibsProjectOnly UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[  +21 ms] > Task :app:stripDebugDebugSymbols FAILED
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[  +19 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[  +20 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[  +15 ms] 46 actionable tasks: 4 executed, 42 up-to-date
[   +3 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +4 ms] Execution failed for task ':app:stripDebugDebugSymbols'.
[  +21 ms] > NDK at C:\Users\SPeller\AppData\Local\Android\sdk\ndk-bundle did not have a source.properties file
[  +18 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
[   +4 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 4s
[ +423 ms] Running Gradle task 'assembleDebug'... (completed in 5,7s)
[+1677 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +5 ms] "flutter run" took 8 733ms.
[  +19 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>


[  +96 ms] ensureAnalyticsSent: 73ms
[   +4 ms] Running shutdown hooks
[  +14 ms] Shutdown hook priority 4
[   +7 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
</details>

```
flutter analyze
Analyzing myapp...
No issues found! (ran in 25.5s)
```

<details><summary>flutter doctor -v</summary>

```
flutter doctor -v
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19042.685], locale ru-RU)
    • Flutter version 1.25.0-8.1.pre at c:\develop\soft\flutter
    • Framework revision 8f89f6505b (3 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\SPeller\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\SPeller\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\SPeller\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```
</details>

**Comment by iapicca** [comment]
possibly related to https://github.com/gradle/gradle/issues/12440#issuecomment-606188282

**Comment by pedromassangocode** [comment]
Hi @speller 
I cannot reproduce the issue. Doe any of the workarounds mentioned in the comment above solves the issue for you?

<details><summary>Logs</summary>

```
pedromassango@MacBook-Pro-de-MacBook Desktop % flutterb create xyz && cd xyz && flutterb run
Creating project xyz...
  xyz/integration_test/driver.dart (created)
  xyz/integration_test/app_test.dart (created)
  xyz/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  xyz/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  xyz/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  xyz/ios/Runner/Info.plist (created)
  xyz/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  xyz/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  xyz/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  (created)
  xyz/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  (created)
  xyz/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  xyz/ios/Runner/Base.lproj/Main.storyboard (created)
  xyz/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  (created)
  xyz/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.p
  list (created)
  xyz/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xc
  settings (created)
  xyz/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  xyz/ios/Flutter/Debug.xcconfig (created)
  xyz/ios/Flutter/Release.xcconfig (created)
  xyz/ios/Flutter/AppFrameworkInfo.plist (created)
  xyz/ios/.gitignore (created)
  xyz/test/widget_test.dart (created)
  xyz/xyz.iml (created)
  xyz/.gitignore (created)
  xyz/web/favicon.png (created)
  xyz/web/index.html (created)
  xyz/web/manifest.json (created)
  xyz/web/icons/Icon-192.png (created)
  xyz/web/icons/Icon-512.png (created)
  xyz/.metadata (created)
  xyz/android/app/src/profile/AndroidManifest.xml (created)
  xyz/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  xyz/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  xyz/android/app/src/main/res/drawable/launch_background.xml (created)
  xyz/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  xyz/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  xyz/android/app/src/main/res/values-night/styles.xml (created)
  xyz/android/app/src/main/res/values/styles.xml (created)
  xyz/android/app/src/main/res/drawable-v21/launch_background.xml (created)
  xyz/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  xyz/android/app/src/main/AndroidManifest.xml (created)
  xyz/android/app/src/debug/AndroidManifest.xml (created)
  xyz/android/gradle/wrapper/gradle-wrapper.properties (created)
  xyz/android/gradle.properties (created)
  xyz/android/.gitignore (created)
  xyz/android/settings.gradle (created)
  xyz/android/app/build.gradle (created)
  xyz/android/app/src/main/kotlin/com/example/xyz/MainActivity.kt (created)
  xyz/android/build.gradle (created)
  xyz/android/xyz_android.iml (created)
  xyz/pubspec.yaml (created)
  xyz/README.md (created)
  xyz/ios/Runner/Runner-Bridging-Header.h (created)
  xyz/ios/Runner/AppDelegate.swift (created)
  xyz/ios/Runner.xcodeproj/project.pbxproj (created)
  xyz/lib/main.dart (created)
  xyz/.idea/runConfigurations/main_dart.xml (created)
  xyz/.idea/libraries/Dart_SDK.xml (created)
  xyz/.idea/libraries/KotlinJavaRuntime.xml (created)
  xyz/.idea/modules.xml (created)
  xyz/.idea/workspace.xml (created)
Running "flutter pub get" in xyz...                                 6.3s
Wrote 80 files.

All done!
In order to run your application, type:

  $ cd xyz
  $ flutter run

Your application code is in xyz/lib/main.dart.

Downloading Web SDK...                                             16.5s
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Running pod install...                                           1,604ms
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        11.1s
Xcode build done.                                           32.6s
Syncing files to device iPhone 12 Pro...                           366ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro is available at:
http://127.0.0.1:53752/BqOk1f9bXao=/

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.7 19H2 darwin-x64,
    locale en)
    • Flutter version 1.25.0-8.1.pre at
      /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 8f89f6505b (5 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Redmi 5 Plus (mobile)  • 0258ff700005                         •
      android-arm64  • Android 8.1.0 (API 27)
    • iPhone 12 Pro (mobile) • 1EEFA5B2-DA95-49CC-AA0B-968BB248B8F3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```
</details>

**Comment by speller** [comment]
@pedromassangocode I had read the related issue but I don't understand what to fix. I tried a few suggestions but nothing helped. I didn't install or uninstall NDK, I even don't know what is it. It just happened after the Flutter upgrade.

**Comment by speller** [comment]
The stable channel works well on the same machine.

**Comment by iamabs2001** [comment]
Any Solution ?

**Comment by kherld-hussein** [comment]
> Any Solution ?

None still trying to solve it though ...when it will be ready will share

**Comment by kherld-hussein** [comment]
Hi @speller 
I have just found some solution about the issue ...
I deleted the android folder at the root of the system i.e {/home/user_name/**Android** } in Ubuntu  Linux or  C:\Users\<CurrentUserName>AppData/local/**Android** in Windows OS
and reinstalled it through android studio

Hope this will help

**Comment by GaryQian** [comment]
Is anyone still seeing this happen with modern versions of the Android Gradle Plugin?
