### ISSUE TITLE
[video_player] Blank screen SSL SecurityContext

### ISSUE THREAD

**Issue by dubbelpunt** [flutter/flutter#72663]
Hi,

## Steps to Reproduce

I have a SSL connection with client certificate authentication. This is set up via HtpOverrides as follows:
```
class MyHtpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext context) {
	String cacert '''...''';
	String certificate '''...''';
	String privkey '''...''';

    context = new SecurityContext(withTrustedRoots: true);
    context.setTrustedCertificatesBytes(cacert.codeUnits);
    context.useCertificateChainBytes(certificate.codeUnits);
    context.usePrivateKeyBytes(privkey.codeUnits);

    return super.createHttpClient(context);
  }
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runZonedGuarded(() {
    HttpOverrides.global = new MyHtpOverrides();
    runApp(MyApp());
  }, (Object error, StackTrace stack) {
    FirebaseCrashlytics.instance.recordError(error, stack);
  });
}
```

When I try to open a video file with video_player, I get a blank screen. Code:
```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class TestVideo extends StatefulWidget {
  @override
  _VideoPlayer createState() => _VideoPlayer();
}

class _VideoPlayer extends State<TestVideo> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network('https://ww.example.org/example.mp4')
      ..initialize().then((_){
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: _controller.value.initialized
                ? AspectRatio(
                    aspectRatio: _controller.value.aspectRatio,
                    child: VideoPlayer(_controller),
                  )
                : Container()
        )
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
```

The SSL authentication works because requests with the default http client are handled correctly.
Backend webserver is Apache2. I have tried to set SSLProtocol all, but same result.

<details>
  <summary>Logs</summary>

```
I/System.out(10294): [okhttp]:check permission begin!
W/System  (10294): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(10294): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(10294): [socket]:check permission begin!
W/System  (10294): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(10294): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(10294): [OkHttp] sendRequest>>
I/System.out(10294): [OkHttp] sendRequest<<
I/System.out(10294): [okhttp]:check permission begin!
W/System  (10294): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(10294): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(10294): [socket]:check permission begin!
W/System  (10294): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(10294): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(10294): [OkHttp] sendRequest>>
I/System.out(10294): [OkHttp] sendRequest<<
I/System.out(10294): [okhttp]:check permission begin!
W/System  (10294): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(10294): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(10294): [socket]:check permission begin!
W/System  (10294): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(10294): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(10294): [OkHttp] sendRequest>>
I/System.out(10294): [OkHttp] sendRequest<<
I/System.out(10294): [okhttp]:check permission begin!
W/System  (10294): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(10294): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(10294): [socket]:check permission begin!
W/System  (10294): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out(10294): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out(10294): [OkHttp] sendRequest>>
I/System.out(10294): [OkHttp] sendRequest<<
E/ExoPlayerImplInternal(10294): Playback error
E/ExoPlayerImplInternal(10294):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(10294):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(10294):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(10294):       at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal(10294):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(10294):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal(10294):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:309)
E/ExoPlayerImplInternal(10294):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(10294):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
E/ExoPlayerImplInternal(10294):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(10294):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(10294):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(10294):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(10294):   Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0x7c8e6a9b48: Failure in SSL library, usually a protocol error
E/ExoPlayerImplInternal(10294):   error:1000045c:SSL routines:OPENSSL_internal:TLSV1_CERTIFICATE_REQUIRED (external/boringssl/src/ssl/tls_record.cc:587 0x7c471050c8:0x00000001)
E/ExoPlayerImplInternal(10294):       at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
E/ExoPlayerImplInternal(10294):       at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
E/ExoPlayerImplInternal(10294):       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:770)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:642)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
E/ExoPlayerImplInternal(10294):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
E/ExoPlayerImplInternal(10294):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:502)
E/ExoPlayerImplInternal(10294):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:307)
E/ExoPlayerImplInternal(10294):       ... 6 more
E/flutter (10294): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter (10294): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:118:5)
E/flutter (10294): #1      Firebase.app (package:firebase_core/src/firebase.dart:52:41)
E/flutter (10294): #2      FirebaseCrashlytics.instance (package:firebase_crashlytics/src/firebase_crashlytics.dart:31:62)
E/flutter (10294): #3      main.<anonymous closure> (file:///c:/Users/andri/AndroidStudioProjects/aadomo/lib/main.dart:146:25)
E/flutter (10294): #4      _rootRunBinary (dart:async/zone.dart:1222:13)
E/flutter (10294): #5      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (10294): #6      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1601:18)
E/flutter (10294): #7      _CustomZone.handleUncaughtError (dart:async/zone.dart:1076:19)
E/flutter (10294): #8      Future._propagateToListeners (dart:async/future_impl.dart:610:16)
E/flutter (10294): #9      Future._completeError (dart:async/future_impl.dart:537:5)
E/flutter (10294): #10     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
E/flutter (10294): #11     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10294): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10294): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (10294): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (10294): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (10294): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (10294):
```

```
flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale nl-BE)
    • Flutter version 1.22.5 at C:\src\flutter
    • Framework revision 7891006299 (9 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\andri\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
```

Dependencies:
video_player: ^1.0.0
</details>

**Comment by dubbelpunt** [comment]
Forgot to mention: video_player ^1.0.0

Thanks.

**Comment by darshankawar** [comment]
@dubbelpunt 
From your error log, I see:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()`

Can you confirm if you are initializing Firebase that should resolve above error and then try again ?

**Comment by dubbelpunt** [comment]
@darshankawar 
Firebase is initializing now but the problem remains. I don't think Firebase is the problem. It has something to do with the SSL authentication. I only have this when the client certificate needs to be used for the SSL authentication. Other https-urls are working.
The log shows this error also:
```
E/ExoPlayerImplInternal( 5713):   Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0x7d7cb5bd08: Failure in SSL library, usually a protocol error
E/ExoPlayerImplInternal( 5713):   error:1000045c:SSL routines:OPENSSL_internal:TLSV1_CERTIFICATE_REQUIRED (external/boringssl/src/ssl/tls_record.cc:587 0x7c8c89d6c8:0x00000001)
```

The complete log:
```
I/System.out( 5713): [okhttp]:check permission begin!
W/System  ( 5713): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 5713): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 5713): [socket]:check permission begin!
W/System  ( 5713): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 5713): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 5713): [OkHttp] sendRequest>>
I/System.out( 5713): [OkHttp] sendRequest<<
I/System.out( 5713): [okhttp]:check permission begin!
W/System  ( 5713): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 5713): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 5713): [socket]:check permission begin!
W/System  ( 5713): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 5713): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 5713): [OkHttp] sendRequest>>
I/System.out( 5713): [OkHttp] sendRequest<<
I/System.out( 5713): [okhttp]:check permission begin!
W/System  ( 5713): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 5713): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 5713): [socket]:check permission begin!
W/System  ( 5713): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 5713): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 5713): [OkHttp] sendRequest>>
I/System.out( 5713): [OkHttp] sendRequest<<
W/ConnectionTracker( 5713): Exception thrown while unbinding
W/ConnectionTracker( 5713): java.lang.IllegalArgumentException: Service not registered: lu@2e6526d
W/ConnectionTracker( 5713):     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
W/ConnectionTracker( 5713):     at android.app.ContextImpl.unbindService(ContextImpl.java:1787)
W/ConnectionTracker( 5713):     at android.content.ContextWrapper.unbindService(ContextWrapper.java:751)
W/ConnectionTracker( 5713):     at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):1)
W/ConnectionTracker( 5713):     at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):2)
W/ConnectionTracker( 5713):     at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):9)
W/ConnectionTracker( 5713):     at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):3)
W/ConnectionTracker( 5713):     at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):3)
W/ConnectionTracker( 5713):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker( 5713):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 5713):     at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):5)
I/System.out( 5713): [okhttp]:check permission begin!
W/System  ( 5713): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 5713): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 5713): [socket]:check permission begin!
W/System  ( 5713): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out( 5713): [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out( 5713): [OkHttp] sendRequest>>
I/System.out( 5713): [OkHttp] sendRequest<<
E/ExoPlayerImplInternal( 5713): Playback error
E/ExoPlayerImplInternal( 5713):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 5713):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal( 5713):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 5713):       at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal( 5713):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 5713):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal( 5713):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:309)
E/ExoPlayerImplInternal( 5713):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 5713):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
E/ExoPlayerImplInternal( 5713):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 5713):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 5713):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 5713):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal( 5713):   Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0x7d7cb5bd08: Failure in SSL library, usually a protocol error
E/ExoPlayerImplInternal( 5713):   error:1000045c:SSL routines:OPENSSL_internal:TLSV1_CERTIFICATE_REQUIRED (external/boringssl/src/ssl/tls_record.cc:587 0x7c8c89d6c8:0x00000001)
E/ExoPlayerImplInternal( 5713):       at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
E/ExoPlayerImplInternal( 5713):       at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
E/ExoPlayerImplInternal( 5713):       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:770)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:642)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
E/ExoPlayerImplInternal( 5713):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
E/ExoPlayerImplInternal( 5713):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:502)
E/ExoPlayerImplInternal( 5713):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:307)
E/ExoPlayerImplInternal( 5713):       ... 6 more
```

**Comment by darshankawar** [comment]
@dubbelpunt 
What device and OS version are you using for this ?
From the log, I see okhttp which supports Api level 21+. Also Exoplayer doesn't use okhttp unless it is explicitly allowed. I am not sure if video player uses okhttp anywhere. Would you know how okhttp is coming from in your logs ?

**Comment by darshankawar** [comment]
may be similar to and related : https://github.com/flutter/flutter/issues/62748

**Comment by dubbelpunt** [comment]
@darshankawar 

I am using API30.
The device is Redmi Note 8 pro; version Android 10.

The public CA is letsencrypt. However, the CA where the client certificate is authenticating against is self-signed.

**Comment by darshankawar** [comment]
@dubbelpunt 
Can you try the same on api 29. Trying to check if this has something to do with api 30. Also what are you `compilesdk` and `targetsdk` versions ?

**Comment by dubbelpunt** [comment]
@darshankawar 
I have the same result wit api 29. The compilesdk and targetsdk are 29.
minsdk was 19. I have changed this to 29 also, but no luck.

**Comment by darshankawar** [comment]
Keeping this issue open for further analysis.

<details>
<summary>flutter doctor -v</summary>

```

Flutter 1.26.0-2.0.pre.137 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8f5d0371af (2 days ago) • 2020-12-26 11:07:36 +0330
Engine • revision f5364860ab
Tools • Dart 2.12.0 (build 2.12.0-179.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.137, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

</details>

**Comment by dubbelpunt** [comment]
@darshankawar
The problem is that the custom SecurityContext isn't passed to the videoplayer plugin.

**Comment by stuartmorgan** [comment]
The video player implementations are using native code, so networking isn't using the Dart stack; overriding Dart's networking behaviors is not going to have any impact on networking done by plugins.

As described, this is expected behavior, so closing. You'll need to either vote for an issue for adding `video_player`-specific  ways of authenticating, or filing such an issue if there isn't already one.
