### ISSUE TITLE
[Web] Mouse up event is sometimes missed - button gets "stuck" (Assertion failed: flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18)

### ISSUE THREAD

**Issue by vidklopcic** [flutter/flutter#72675]
## Steps to Reproduce
Minimal example which reproduces the issue:
```Dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(builder: (ctx, child) => MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          width: 200,
          height: 60,
          child: MaterialButton(
            color: Colors.blue,
            onPressed: () => print('tap'),
            child: Text('material button'),
          ),
        ),
      ),
    );
  }
}
```

**Expected results:** 
When repeatedly clicking and moving mouse I expect the button (and other widgets that depend on mouse events) to continue functioning as intended.
**Actual results:** 
Button gets "frozen" - further clicks aren't registered and it seems to remain in `pressed` state.
![](https://media.giphy.com/media/01QXpm9N7fv4wjUgGW/giphy.gif)

This started happening somewhere between commits `fdac8a9d1f321388d71e35f825b40c05901e74f0` and `32741c0ec822599c17abd8d80ebeb53c143cc818 `.
<details>
  <summary>Logs</summary>

```
[  +74 ms] executing: [/Users/vidklopcic/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] dc80d499f3355874ea0fd1871f7a3012a7b7b9d4
[        ] executing: [/Users/vidklopcic/development/flutter/] git tag --points-at dc80d499f3355874ea0fd1871f7a3012a7b7b9d4
[  +14 ms] Exit code 0 from: git tag --points-at dc80d499f3355874ea0fd1871f7a3012a7b7b9d4
[   +2 ms] executing: [/Users/vidklopcic/development/flutter/] git describe --match *.*.* --long --tags dc80d499f3355874ea0fd1871f7a3012a7b7b9d4
[  +29 ms] Exit code 0 from: git describe --match *.*.* --long --tags dc80d499f3355874ea0fd1871f7a3012a7b7b9d4
[        ] 1.26.0-1.0.pre-69-gdc80d49
[  +40 ms] executing: [/Users/vidklopcic/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/vidklopcic/development/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[  +39 ms] executing: [/Users/vidklopcic/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[   +4 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H2
[   +5 ms] executing: sysctl hw.optional.arm64
[   +4 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +44 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +43 ms] executing: /Users/vidklopcic/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] executing: /usr/bin/xcode-select --print-path
[   +5 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +4 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[  +90 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 12.0.1
           Build version 12A7300
[   +2 ms] executing: xcrun xcdevice list --timeout 2
[   +3 ms] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +53 ms] executing: /Users/vidklopcic/Library/Android/sdk/platform-tools/adb devices -l
[        ] executing: xcrun xcdevice list --timeout 2
[        ] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[  +15 ms] Skipping pub get: version match.
[  +74 ms] Found plugin integration_test at /Users/vidklopcic/development/flutter/packages/integration_test/
[ +101 ms] Found plugin integration_test at /Users/vidklopcic/development/flutter/packages/integration_test/
[   +5 ms] Generating /Users/vidklopcic/StudioProjects/pointer_bug_reproduce/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +94 ms] List of devices attached
[   +3 ms] List of devices attached
[  +57 ms] Launching lib/main.dart on Chrome in debug mode...
[  +67 ms] Updating assets
[  +93 ms] Waiting for connection from debug service on Chrome...
[  +39 ms] Found plugin integration_test at /Users/vidklopcic/development/flutter/packages/integration_test/
[  +33 ms] Found plugin integration_test at /Users/vidklopcic/development/flutter/packages/integration_test/
[  +33 ms] <- reset
[   +5 ms] /Users/vidklopcic/development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/vidklopcic/development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/vidklopcic/development/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata --output-dill /var/folders/zs/f__g3g2s4p3dg7_y6mdhmj6r0000gn/T/flutter_tools.kxN2h5/flutter_tool.qwl0wZ/app.dill --libraries-spec file:///Users/vidklopcic/development/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /Users/vidklopcic/StudioProjects/pointer_bug_reproduce/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /var/folders/zs/f__g3g2s4p3dg7_y6mdhmj6r0000gn/T/flutter_tools.kxN2h5/flutter_tools.MeAKeN --filesystem-scheme org-dartlang-app --initialize-from-dill build/fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform
file:///Users/vidklopcic/development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +14 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+10940 ms] Waiting for connection from debug service on Chrome... (completed in 13.1s)
[        ] Synced 28.6MB.
[        ] <- accept
[        ] Caching compiled dill
[  +60 ms] Using Google Chrome 87.0.4280.88 

[ +614 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:57139/devtools/browser/fb2a624f-268b-4bda-b421-80960bd77289
[ +512 ms] DwdsInjector: Received request for entrypoint at http://localhost:57113/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[   +8 ms] MetadataProvider: Loaded debug metadata
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:57113/main_module.bootstrap.js
[+1639 ms] DevHandler: Debug service listening on ws://127.0.0.1:57162/HXJj16GlwiQ=/ws

[   +8 ms] Debug service listening on ws://127.0.0.1:57162/HXJj16GlwiQ=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+2700 ms] tap
[ +190 ms] tap
[ +603 ms] tap
[+2200 ms] tap
[ +364 ms] tap
[+1716 ms] tap
[+3642 ms] tap
[ +311 ms] tap
[+3993 ms] tap
[+2366 ms] tap
[+2882 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
                    !state.down
                    is not true
                        at Object.throw_ [as throw] (http://localhost:57113/dart_sdk.js:5294:11)
                        at Object.assertFailed (http://localhost:57113/dart_sdk.js:5230:15)
                        at _engine.PointerDataConverter.new.convert (http://localhost:57113/dart_sdk.js:164367:47)
                        at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:57113/dart_sdk.js:163816:36)
                        at http://localhost:57113/dart_sdk.js:163751:44
                        at http://localhost:57113/dart_sdk.js:163720:16
                        at http://localhost:57113/dart_sdk.js:163419:11
[   +6 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
           !state.down
           is not true
               at Object.throw_ [as throw] (http://localhost:57113/dart_sdk.js:5294:11)
               at Object.assertFailed (http://localhost:57113/dart_sdk.js:5230:15)
               at _engine.PointerDataConverter.new.convert (http://localhost:57113/dart_sdk.js:164367:47)
               at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:57113/dart_sdk.js:163816:36)
               at http://localhost:57113/dart_sdk.js:163751:44
               at http://localhost:57113/dart_sdk.js:163720:16
               at http://localhost:57113/dart_sdk.js:163419:11
[  +17 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
           !state.down
           is not true
               at Object.throw_ [as throw] (http://localhost:57113/dart_sdk.js:5294:11)
               at Object.assertFailed (http://localhost:57113/dart_sdk.js:5230:15)
               at _engine.PointerDataConverter.new.convert (http://localhost:57113/dart_sdk.js:164367:47)
               at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:57113/dart_sdk.js:163816:36)
               at http://localhost:57113/dart_sdk.js:163751:44
               at http://localhost:57113/dart_sdk.js:163720:16
               at http://localhost:57113/dart_sdk.js:163419:11
[  +14 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
           !state.down
           is not true
               at Object.throw_ [as throw] (http://localhost:57113/dart_sdk.js:5294:11)
               at Object.assertFailed (http://localhost:57113/dart_sdk.js:5230:15)
               at _engine.PointerDataConverter.new.convert (http://localhost:57113/dart_sdk.js:164367:47)
               at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:57113/dart_sdk.js:163816:36)
               at http://localhost:57113/dart_sdk.js:163751:44
               at http://localhost:57113/dart_sdk.js:163720:16
               at http://localhost:57113/dart_sdk.js:163419:11
[        ] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:351:18
           !state.down
           is not true
               at Object.throw_ [as throw] (http://localhost:57113/dart_sdk.js:5294:11)
               at Object.assertFailed (http://localhost:57113/dart_sdk.js:5230:15)
               at _engine.PointerDataConverter.new.convert (http://localhost:57113/dart_sdk.js:164379:47)
               at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:57113/dart_sdk.js:163816:36)
               at http://localhost:57113/dart_sdk.js:163734:42
               at http://localhost:57113/dart_sdk.js:163720:16
               at http://localhost:57113/dart_sdk.js:163419:11
```

```
Analyzing pointer_bug_reproduce...                                      
No issues found! (ran in 1.3s)
```

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.69, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-SI)
    • Flutter version 1.26.0-2.0.pre.69 at /Users/vidklopcic/development/flutter
    • Framework revision dc80d499f3 (3 days ago), 2020-12-17 10:39:03 -0800
    • Engine revision fd6b409f95
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vidklopcic/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.25

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    ! Error: Vid’s iPad is not connected. Xcode will continue when Vid’s iPad is connected. (code -13)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@vidklopcic 
Tried your code sample on latest master and beta, but didn't notice the issue you mentioned. I repeatedly clicked on the button and other buttons on the browser which worked as expected and didn't throw any errors in the terminal.


https://user-images.githubusercontent.com/67046386/102770839-cd222380-43aa-11eb-9cb7-b5616846a73c.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.86, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.86 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision b793285329 (3 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>

<details>
<summary>console log</summary>

```
For a more detailed help message, press "h". To quit, press "q".
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap
tap


```

</details>

Are you on M1 machine by any chance ? If not, are there any specific steps to replicate the issue ?

**Comment by vidklopcic** [comment]
@darshankawar  
Yes, this doesn't happen frequently - I was recording for approx 5 min till I managed to capture the problem. I wouldn't even notice if the customer wouldn't complain.

Also, the only way to reproduce it is to **click while moving the cursor** - that's why my cursor is jumping all over the place on the animation above.

**Comment by chunhtai** [comment]
cc @cbracken does your pointer PR fix this issue?

**Comment by darshankawar** [comment]
@vidklopcic 
Okay, I was finally able to replicate this after clicking continously while moving the mouse for about 5 mins.

<details>
<summary>error log</summary>

```

tap
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50357/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:50357/dart_sdk.js:5232:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50357/dart_sdk.js:164362:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50357/dart_sdk.js:163811:36)
    at http://localhost:50357/dart_sdk.js:163746:44
    at http://localhost:50357/dart_sdk.js:163715:16
    at http://localhost:50357/dart_sdk.js:163414:11
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50357/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:50357/dart_sdk.js:5232:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50357/dart_sdk.js:164362:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50357/dart_sdk.js:163811:36)
    at http://localhost:50357/dart_sdk.js:163746:44
    at http://localhost:50357/dart_sdk.js:163715:16
    at http://localhost:50357/dart_sdk.js:163414:11
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50357/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:50357/dart_sdk.js:5232:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50357/dart_sdk.js:164362:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50357/dart_sdk.js:163811:36)
    at http://localhost:50357/dart_sdk.js:163746:44
    at http://localhost:50357/dart_sdk.js:163715:16
    at http://localhost:50357/dart_sdk.js:163414:11
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50357/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:50357/dart_sdk.js:5232:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50357/dart_sdk.js:164362:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50357/dart_sdk.js:163811:36)
    at http://localhost:50357/dart_sdk.js:163746:44
    at http://localhost:50357/dart_sdk.js:163715:16
    at http://localhost:50357/dart_sdk.js:163414:11
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50357/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:50357/dart_sdk.js:5232:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50357/dart_sdk.js:164362:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50357/dart_sdk.js:163811:36)
    at http://localhost:50357/dart_sdk.js:163746:44
    at http://localhost:50357/dart_sdk.js:163715:16
    at http://localhost:50357/dart_sdk.js:163414:11
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50357/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:50357/dart_sdk.js:5232:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50357/dart_sdk.js:164362:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50357/dart_sdk.js:163811:36)
    at http://localhost:50357/dart_sdk.js:163746:44
    at http://localhost:50357/dart_sdk.js:163715:16
    at http://localhost:50357/dart_sdk.js:163414:11
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50357/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:50357/dart_sdk.js:5232:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50357/dart_sdk.js:164362:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50357/dart_sdk.js:163811:36)
    at http://localhost:50357/dart_sdk.js:163746:44
    at http://localhost:50357/dart_sdk.js:163715:16
    at http://localhost:50357/dart_sdk.js:163414:11
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:351:18
!state.down
is not true
    at Object.throw_ [as throw] (http://localhost:50357/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:50357/dart_sdk.js:5232:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:50357/dart_sdk.js:164374:47)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:50357/dart_sdk.js:163811:36)
    at http://localhost:50357/dart_sdk.js:163729:42
    at http://localhost:50357/dart_sdk.js:163715:16
    at http://localhost:50357/dart_sdk.js:163414:11



```

</details>

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.26.0-2.0.pre.103, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.103 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 32741c0ec8 (6 hours ago), 2020-12-21 18:34:02 -0600
    • Engine revision af6889a600
    • Dart version 2.12.0 (build 2.12.0-169.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```

</details>

**Comment by vidklopcic** [comment]
Great! I noticed that it happens much frequently if the inkwell is put inside a scrollable widget. 

I also noticed that there is a whole host of (probably) related issues with mouse event handling. The list scroll can also get stuck, then after using a wheel it jumps to offset 0, and then everything becomes unresponsive to clicks (this happens in Firefox).

https://user-images.githubusercontent.com/8578790/102875146-b2e85400-4443-11eb-9241-2ae28be6eff4.mov

**Comment by nrutledge** [comment]
Any update or workarounds for this? I'm experiencing the same issue/error (using Flutter 1.26.0-17.4.pre). 

It happens very frequently by accident. However, it can be easily reproduced by rapidly clicking while dragging the mouse on an Inkwell. It also affects dialogs (rapidly click and drag in the outside area while trying to close the dialog) and likely other widgets.

I'll try to investigate further and add more details later.

I'm using the latest versions of Chrome and Safari on macOS 11.2.1 (have yet to test on Windows).

**Comment by slavap** [comment]
I'm getting this bug (or something similar) on Android Chrome with Flutter 1.26.0-17.6.pre
For me it is kind of critical/showstopper, because buttons are getting suddenly irresponsible to clicks. The only way to make them working - pressing menu button on the header (it is the only button which always works), after that other buttons are working again.

**Comment by ferhatb** [comment]
@mdebbar , is this one resolved too with your fix?

**Comment by mdebbar** [comment]
@vidklopcic @nrutledge the `!state.down` assertion issue has been fixed recently in the master channel. If you are seeing a different error now, please open a new issue.

**Comment by luisdemarchi** [comment]
@mdebbar falls into the same error, even on the same line. It seems that depending on the plugin I use, it gives more or less times. But I always end up needing to restart debug

> Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:286:18
> !state.down
> is not true
>     at Object.throw_ [as throw] (http://localhost:4200/dart_sdk.js:5334:11)
>     at Object.assertFailed (http://localhost:4200/dart_sdk.js:5270:15)
>     at _engine.PointerDataConverter.new.convert (http://localhost:4200/dart_sdk.js:165955:47)
>     at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:4200/dart_sdk.js:165404:36)
>     at http://localhost:4200/dart_sdk.js:165339:44
>     at http://localhost:4200/dart_sdk.js:165308:16
>     at http://localhost:4200/dart_sdk.js:165007:11

Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (12 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

Chrome: Version 89.0.4389.90 (Official Build) (x86_64)

**Comment by mac-spinks** [comment]
I can confirm I get the same error as @luisdemarchi. It happens randomly in the debug and deployed versions of my flutter web app. The only way to get it to stop is to reload/restart the application.

Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (4 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
