### ISSUE TITLE
NetworkImage is an empty file error!

### ISSUE THREAD

**Issue by benyaminbeyzaie** [flutter/flutter#72683]
Hey there
I use NetworkImage widget to show my images from the internet in the app the image url is correct and I can see the image from my browser also when my VPN is on the image is perfectly works but without VPN and on the debug version I get this error:
```
Exception: NetworkImage is an empty file: http://45.82.136.244/media/images/1ff9a03d-02f.jpg
```
Also the release version of the app is working great!
This is my ``flutter doctor``: (I don't use android studio for coding)
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)
```
And this is my code for showing an image using ``NetworkImage`` (example):
```
CircleAvatar(
     backgroundColor: Colors.grey.withAlpha(200),
     backgroundImage:  NetworkImage(ApiProvider.DADYAR_PROJECT +
          sessionModel.personInformationModel.avatar
          .toString(),),)
```

**Comment by iapicca** [comment]
I **_can not_** reproduce the issue

[screenshot](https://user-images.githubusercontent.com/45637986/102720591-f46ee700-42fd-11eb-9dc7-44c83535172a.png)

<details>
<summary>codesampel</summary>


```dart
import 'package:flutter/material.dart';

const _image =
    NetworkImage('http://45.82.136.244/media/images/1ff9a03d-02f.jpg');

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Image(image: _image),
        ),
      ),
    );

```

</details>

<details>
<summary>logs</summary>

```bash
[  +54 ms] Launching lib/main.dart on Chrome in debug mode...
[  +91 ms] Updating assets
[ +109 ms] Waiting for connection from debug service on Chrome...
[  +51 ms] Found plugin integration_test at /home/francesco/snap/flutter/common/flutter/packages/integration_test/
[  +38 ms] Found plugin integration_test at /home/francesco/snap/flutter/common/flutter/packages/integration_test/
[  +37 ms] <- reset
[   +7 ms] /home/francesco/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.ZBUVKI/flutter_tool.IBUVTI/app.dill --libraries-spec
file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/francesco/projects/issue/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.ZBUVKI/flutter_tools.VLKEJE --filesystem-scheme org-dartlang-app --initialize-from-dill
build/fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +16 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+20043 ms] Waiting for connection from debug service on Chrome... (completed in 20.2s)
[   +1 ms] Synced 28.6MB.
[        ] <- accept
[        ] Caching compiled dill
[ +136 ms] Using Google Chrome 87.0.4280.88 

[ +520 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:39305/devtools/browser/4aeb5b5f-3c63-4753-941a-0791b6992497
[ +490 ms] DwdsInjector: Received request for entrypoint at http://localhost:43535/main_module.bootstrap.js
[  +23 ms] MetadataProvider: Loading debug metadata...
[  +19 ms] MetadataProvider: Loaded debug metadata
[  +20 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:43535/main_module.bootstrap.js
[+2896 ms] DevHandler: Debug service listening on ws://127.0.0.1:42363/H-XYMrgXJ1Y=/ws

[   +8 ms] Debug service listening on ws://127.0.0.1:42363/H-XYMrgXJ1Y=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+53574 ms] DevHandler: Stopped debug service on ws://127.0.0.1:40143

[ +484 ms] Application finished.
[   +5 ms] "flutter run" took 79,152ms.
[ +255 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[ +193 ms] Shutdown hooks complete
[        ] exiting with code 0

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.86, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.86 at /home/francesco/snap/flutter/common/flutter
    • Framework revision b793285329 (2 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.

```

</details>

**Comment by pedromassangocode** [comment]
Reproducible with the code in https://github.com/flutter/flutter/issues/72683#issuecomment-748640388.


<details><summary>Logs</summary>

```
Launching lib/main.dart on Redmi 5 Plus in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
W/flutter_example(31766): type=1400 audit(0.0:28731): avc: denied { read } for name="max_map_count" dev="proc" ino=17124778 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
Debug service listening on ws://127.0.0.1:49398/wTCYnqoGCmQ=/ws
Syncing files to device Redmi 5 Plus...
D/skia    (31766): WARNING: failed to attach a stencil buffer. Rendering will be skipped.

======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: NetworkImage is an empty file: http://45.82.136.244/media/images/1ff9a03d-02f.jpg

When the exception was thrown, this was the stack: 
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:112:9)
<asynchronous suspension>
Image provider: NetworkImage("http://45.82.136.244/media/images/1ff9a03d-02f.jpg", scale: 1.0)
Image key: NetworkImage("http://45.82.136.244/media/images/1ff9a03d-02f.jpg", scale: 1.0)
====================================================================================================
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.86, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.86 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision b793285329 (3 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.0.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by iapicca** [comment]
@pedromassangocode 
does it show on ios? 
since it [works fine on web](https://github.com/flutter/flutter/issues/72683#issuecomment-748640388), maybe is android only

**Comment by benyaminbeyzaie** [comment]
I have not tried ios. how can I find where the problem is?

**Comment by benyaminbeyzaie** [comment]
![image](https://user-images.githubusercontent.com/29250042/102760690-22e6d380-438b-11eb-849c-0c4cfa28cffd.png)

**Comment by pedromassangocode** [comment]
Does not work on iOS simulator as well (debug mode).

**Comment by benyaminbeyzaie** [comment]
hmmmm... as I mentioned earlier on release mode I don't have any problem but on debug mode it bothers me! there was an idea that if I could catch that exception I could show a default image if there is any problem... but I can't catch that exception.

**Comment by iapicca** [comment]
I tried to get more info with `flutter run -vv`
and wrapping with `try  catch`, but not much

<details>
<summary>new code sample</summary>

```dart
import 'package:flutter/material.dart';

ImageProvider _imageProvider() {
  ImageProvider _p;
  try {
    _p = NetworkImage('http://45.82.136.244/media/images/1ff9a03d-02f.jpg');
  } catch (e, s) {
    print('error caught from `ImageProvider` \n ####\n $e\n $s\n ####');
  }
  return _p;
}

Image _image() {
  Image _i;
  try {
    final _p = _imageProvider();
    if (_p != null) {
      _i = Image(image: _p);
    }
  } catch (e, s) {
    print('error caught from `Image` \n ####\n $e\n $s\n ####');
  }
  return _i;
}

void main() => runApp(
      MaterialApp(
        home: Material(
          child: _image() ?? Placeholder(),
        ),
      ),
    );

```

</details>

<details>
<summary>logs</summary>

```bash
[ +161 ms] Syncing files to device Pixel 3a...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:issue_72683/main.dart 3827c10c-8df3-402b-8c3a-100bfa7b96b3
[        ] <- 3827c10c-8df3-402b-8c3a-100bfa7b96b3
[  +89 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Pixel 3a... (completed in 94ms)
[        ] Synced 0.0MB.
[        ] <- accept
[  +18 ms] Connected to _flutterView/0x77fe160f80.
[   +6 ms] Flutter run key commands.
[   +6 ms] r Hot reload. 🔥🔥🔥
[   +5 ms] R Hot restart.
[   +2 ms] h Repeat this help message.
[   +2 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[   +2 ms] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:46603/pHZFZxmc1pc=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[ +617 ms] I/flutter (12863): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[  +33 ms] I/flutter (12863): The following StateError was thrown resolving an image codec:
[   +1 ms] I/flutter (12863): Bad state: Insecure HTTP is not allowed by platform:
[   +1 ms] I/flutter (12863): http://45.82.136.244/media/images/1ff9a03d-02f.jpg
[   +1 ms] I/flutter (12863): 
[   +1 ms] I/flutter (12863): When the exception was thrown, this was the stack:
[   +1 ms] I/flutter (12863): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2435:7)
[        ] I/flutter (12863): #1      _HttpClient.getUrl (dart:_http/http_impl.dart:2347:48)
[        ] I/flutter (12863): #2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:89:59)
[        ] I/flutter (12863): #3      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
[        ] I/flutter (12863): #4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:503:13)
[        ] I/flutter (12863): #5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:375:22)
[        ] I/flutter (12863): #6      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:501:83)
[   +1 ms] I/flutter (12863): #7      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
[        ] I/flutter (12863): #8      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:332:9)
[        ] I/flutter (12863): #9      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:462:26)
[        ] I/flutter (12863): #10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:35)
[        ] I/flutter (12863): #11     ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:459:11)
[        ] I/flutter (12863): #15     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:451:16)
[   +1 ms] I/flutter (12863): #16     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:329:5)
[   +1 ms] I/flutter (12863): #17     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1166:16)
[   +1 ms] I/flutter (12863): #18     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1118:5)
[   +1 ms] I/flutter (12863): #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4839:11)
[   +1 ms] I/flutter (12863): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4655:5)
[   +1 ms] I/flutter (12863): ...     Normal element mounting (208 frames)
[        ] I/flutter (12863): #228    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3621:14)
[   +1 ms] I/flutter (12863): #229    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6290:32)
[        ] I/flutter (12863): ...     Normal element mounting (309 frames)
[        ] I/flutter (12863): #538    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3621:14)
[        ] I/flutter (12863): #539    Element.updateChild (package:flutter/src/widgets/framework.dart:3386:18)
[        ] I/flutter (12863): #540    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1211:16)
[        ] I/flutter (12863): #541    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1182:5)
[        ] I/flutter (12863): #542    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1124:18)
[        ] I/flutter (12863): #543    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2727:19)
[        ] I/flutter (12863): #544    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1123:13)
[        ] I/flutter (12863): #545    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:963:7)
[        ] I/flutter (12863): #546    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:944:7)
[        ] I/flutter (12863): (elided 14 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
[        ] I/flutter (12863): 
[        ] I/flutter (12863): Image provider: NetworkImage("http://45.82.136.244/media/images/1ff9a03d-02f.jpg", scale: 1.0)
[        ] I/flutter (12863): Image key: NetworkImage("http://45.82.136.244/media/images/1ff9a03d-02f.jpg", scale: 1.0)
[        ] I/flutter (12863): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.86, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.86 at /home/francesco/snap/flutter/common/flutter
    • Framework revision b793285329 (3 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.

```

</details>

@pedromassangocode this looks like a regression to me

**Comment by chunhtai** [comment]
cc @dnfield

**Comment by dnfield** [comment]
I'm having trouble reproducing this locally because I need to set up an application that allows non-https connections :)

This is likely either a bug in `consolidateHttpRequestBytes` or `dart:io`. It'd help to know if anyone experiencing this is using a proxy, although it's strange that this is occuring in debug mode but not release.

**Comment by benyaminbeyzaie** [comment]
I edit the widget but not exactly sure which part of code solve the issue for me. So for now I think I'm gonna close the issue. Thanks!
