### ISSUE TITLE
flutter install apk fails with INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by safield** [flutter/flutter#72730]
I have been developing and installing my apk on the android emulator, and on a physical device with no issues.

Then all of a sudden, I am getting an error when installing. The only thing I can think of that changed was I deleted and regenerated my pubspec.lock.

I build and install with the commands...
```
flutter build apk --debug
flutter instal apk
```

When install on a physical device I get...

```
Package install error: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
Install failed
```

When install on the emulator I get...

```
adb: failed to install /home/user/src/MobileApp/build/app/outputs/flutter-apk/app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Package
/data/app/vmdl770003105.tmp/base.apk has no certificates at entry AndroidManifest.xml]
Install failed
```

I have noticed when I build, in ~/.android folder, a debug.keystore.lock file is created, but never deleted. I can manually delete it, but every subsequent build process creates this build file and does not delete it.

Flutter doctor...

```
✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_CA.UTF-8)
    • Flutter version 1.22.5 at /usr/local/flutter-sdk
    • Framework revision 7891006299 (11 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/local/android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/local/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Lenovo TB3 X70F (mobile) • *JHD874JBNA73B • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 1 category.
```

**Comment by chunhtai** [comment]
cc @christopherfujino

**Comment by realrk69** [comment]
I think this has got to do with your Android or JDK version. Check online since a lot of people seem to having similar issues in Android Studio (but mostly with release versions of apps). Make sure you have not made any mistakes in the Android manifest files.

Also, try this:
1. Uninstall apk from device
2. flutter clean
3. build again
4. If this doesn't work, create a new project and import all your dart files along with the custom platform files/settings carefully. Works 99% of the time for most errors.

**Comment by safield** [comment]
Create a new project seems like a pretty heavy hammer for this problem.

**Comment by jmagman** [comment]
> If this doesn't work, create a new project and import all your dart files along with the custom platform files/settings carefully. Works 99% of the time for most errors.

Please don't recommend users recreate their project files in GitHub issues.  We need to track down underlying bugs to solve the problem for all Flutter users, not provide workarounds.  When the project files are recreated it's really hard to make these issues actionable for engineers.

**Comment by jmagman** [comment]
I see a few related issues that were closed because they were tracked down to environment issues, like full emulator storage https://github.com/flutter/flutter/issues/9638 and https://github.com/flutter/flutter/issues/9849.  Any change that's your issue?

If that's the problem, the tool could detect this error and suggest a workaround.

**Comment by heinzan** [comment]
same me too.I restarted my physical device it is fine and run again error occur.How solve that i tested a lot way but no way.I can run on emulator.

**Comment by heinzan** [comment]
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /.../base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by budlight** [comment]
I started getting this issue as my app with assets approached 500mb.  Didn't seem to be running out of space on emulator or OS drive.

**Comment by justkawal** [comment]
@jmagman I am also experiencing this issue, I'm running it on real device and have enough space available.

Error: 
```
Error: ADB exited with exit code 1
[  +11 ms] Performing Streamed Install
           
           adb: failed to install /Users/kawal/Desktop/blue_banyan/lalluram/build/app/outputs/flutter-apk/app.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES:
Package
           /data/app/vmdl29650915.tmp/base.apk has no certificates at entry AndroidManifest.xml]
[   +1 ms] Warning: Failed to install APK.
[   +2 ms] Error running application on SM A920F.
[  +25 ms] "flutter run" took 54,210ms.
[  +11 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #21     _rootRun (dart:async/zone.dart:1190:13)
           #22     _CustomZone.run (dart:async/zone.dart:1093:19)
           #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +3 ms] ensureAnalyticsSent: 1ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 2
```

flutter doctor: 
```
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.3 20D91 darwin-arm, locale en-IN)
    • Flutter version 1.22.6 at /Users/kawal/flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/kawal/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • SM A920F (mobile) • 2b6484b5191d7ece • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

I have tried this out both on Flutter 2.0.4 and also on 1.22.6, but on both versions of flutter it is causing this issue.

**Comment by justkawal** [comment]
@jmagman 

Seeking for an update on this, it is still causing some issues.

**Comment by jmagman** [comment]
@justkawal I don't have an update.  Just looking around StackOverflow it seems to be an Android signing issue https://stackoverflow.com/questions/2914105/what-is-install-parse-failed-no-certificates-error.  Try getting the same signing config you set up in Flutter working on a totally vanilla non-Flutter Android project.  That may help narrow down the problem.

**Comment by justkawal** [comment]
@jmagman It is now resolved, You can close this issue, Thanks for faster follow up and help.

**Comment by mpoapostolis** [comment]
I don't know if it's a coincidence,
But after spending hours trying to fix this.
I changed the USB port and magically the error disappears.

**Comment by Thanasak-Sompong** [comment]
INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.netflix.mediaclient

**Comment by martin-braun** [comment]
@justkawal Instead of just saying that it is resolved, you should always share what you did to solve the issue, so others can find solutions. I have to deal with an old app, so I cannot jump to the latest Flutter version and I'm pretty sure this version fails to sign my app with V1 **and** V2 sigs.

**Comment by FatimaHassan6** [comment]
Can you plz share with us how you solved the problem?

I search it on google and all of them suggest to:
1- un-check instant run (I can't find it in my settings)
2- Wipe data of the emulator (Not working)
3- Clean project (Not working)

it all happens after I update java to last version and restart my laptop

**Comment by mathiasgodwin** [comment]
I had same problem and it was caused by my phone low memory space (800mb) so I freed up some space about (1.8Gb) and re-run. It's working fine now after many search

**Comment by saadMalik789** [comment]
> 

worked for me. thanks

**Comment by blasten** [comment]
Please update the Android Gradle plugin and Gradle to the latest version, and share if that fixed the INSTALL_PARSE_FAILED_NO_CERTIFICATES issue.
