### ISSUE TITLE
FileSystemException: FileSystemException: Creation failed, path = '/projects' (OS Error: Read-only file system, errno = 30)

### ISSUE THREAD

**Issue by zhanfengkuang** [flutter/flutter#72770]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter assemble -dTargetPlatform=android -dBuildMode=profile --output /projects/ctrip_flutter/release/android -dTrackWidgetCreation=true android_aot_bundle_profile_android-arm64 android_aot_bundle_profile_android-arm android_aot_bundle_profile_android-x64 -o /projects/ctrip_flutter/release -i info

## exception

FileSystemException: FileSystemException: Creation failed, path = '/projects' (OS Error: Read-only file system, errno = 30)

```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#2      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#3      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#4      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#5      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:273:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:380:14)
#7      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:272:12)
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:543:27)
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.7 19H2, locale zh-Hans-CN)
    • Flutter version 1.22.1 at /Users/ctrip/Development/flutter
    • Framework revision f30b7f4db9 (2 months ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ctrip/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Jarmon XS (mobile) • 00008020-00090DE03A81002E • ios • iOS 14.2

• No issues found!
```

**Comment by pedromassangocode** [comment]
Hi @zhanfengkuang 
Your Flutter version is two months old and if I remember right this issue was fixed recently (can't find the old issue now).
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
