### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.Receiver: nullTried calling: length

### ISSUE THREAD

**Issue by wang1048076313** [flutter/flutter#72843]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Utf8Encoder.convert (dart:convert/utf.dart:88:31)
#2      Codec.encode (dart:convert/codec.dart:21:32)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:31)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:148:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:187:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:380:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:186:5)
#8      Cache.setStampFor (package:flutter_tools/src/cache.dart:419:35)
#9      CachedArtifact.update (package:flutter_tools/src/cache.dart:575:13)
<asynchronous suspension>
#10     Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:928:27)
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _runZoned (dart:async/zone.dart:1630:10)
#18     runZoned (dart:async/zone.dart:1550:10)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
```
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/wangchong/Downloads/flutter
    • Framework revision 7891006299 (), 1970-01-01 08:00:00.000
    • Engine revision 
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/wangchong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by deveshgarg-max** [comment]
Hey, @wang1048076313 please provide complete steps which is providing this error.
Generally, this error comes up you try to use any function at null conditions.
For example:
List myList = null;
print(myList.length); ---> this line cause an error which you are facing above.
Check whether you doing something which is making your list null and Make sure **null list != empty list**
Thanks.

**Comment by jonahwilliams** [comment]
@wang1048076313 can you confirm whether the `flutter/bin/engine.version`file exists? If that file has been modified that might cause problems here

**Comment by christopherfujino** [comment]
Going to close this as stale
