### ISSUE TITLE
i have error in create flutter first_app in command prompt

### ISSUE THREAD

**Issue by mernaem** [flutter/flutter#72852]
## Steps to Reproduce

1. ... Oops; flutter has exited unexpectedly: "FileSystemException: Exists failed, path = 'D:\Computer
Science\Programs\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_template_images-1.0.1\lib\' (OS Error: The
device is not ready.
, errno = 21)".

A crash report has been written to F:\development\flutter_01.log.
2. ... Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --verbose create foo

## exception

FileSystemException: FileSystemException: Exists failed, path = 'D:\Computer Science\Programs\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_template_images-1.0.1\lib\' (OS Error: The device is not ready.
, errno = 21)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#2      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:304:79)
<asynchronous suspension>
#4      Template.fromName (package:flutter_tools/src/template.dart:77:38)
#5      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:791:46)
#6      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:671:29)
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:436:37)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.17133.73], locale en-US)
    • Flutter version 1.22.5 at F:\development\flutter
    • Framework revision 7891006299 (12 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\Development\android-sdk
    • Platform android-29, build-tools 30.0.3
    • ANDROID_SDK_ROOT = F:\Development\android-sdk
    • Java binary at: F:\program files\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at F:\program files\Android
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.17133.73], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

```
```

</details>

**Comment by deveshgarg-max** [comment]
It is the clearly visible connected device is zero you mush have to connect a physical device or any virtual machine to create your first project
to solve this
Android: go to android studio > avd manager > create new virtual machine
iOS: on the terminal type "open -a simulator".

**Comment by pedromassangocode** [comment]
Hi @mernaem 

> A crash report has been written to F:\development\flutter_01.log

Can you provide this file?
Thank you

**Comment by mernaem** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter create fstapp

## exception

FileSystemException: FileSystemException: Exists failed, path = 'D:\Computer Science\Programs\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_template_images-1.0.1\lib\' (OS Error: The device is not ready.
, errno = 21)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#2      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:304:79)
<asynchronous suspension>
#4      Template.fromName (package:flutter_tools/src/template.dart:77:38)
#5      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:791:46)
#6      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:671:29)
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:436:37)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.17133.73], locale en-US)
    • Flutter version 1.22.5 at F:\development\flutter
    • Framework revision 7891006299 (12 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\Development\android-sdk
    • Platform android-29, build-tools 30.0.3
    • ANDROID_SDK_ROOT = F:\Development\android-sdk
    • Java binary at: F:\program files\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at F:\program files\Android
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```


________________________________

**Comment by pedromassangocode** [comment]
Hi @mernaem 
Please try running `flutter pub cache repair` to see if that solve your issue and let me know.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
