### ISSUE TITLE
StateError: Bad state: No element

### ISSUE THREAD

**Issue by darshankhadse** [flutter/flutter#72855]
[flutter_01.log](https://github.com/flutter/flutter/files/5733405/flutter_01.log)

**Comment by pedromassangocode** [comment]
[Taken from the file above]

Crash Logs:


```
#0      Stream.first.<anonymous closure> (dart:async/stream.dart:1294:9)
#1      _rootRun (dart:async/zone.dart:1182:47)
#2      _CustomZone.run (dart:async/zone.dart:1093:19)
#3      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:407:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:330:15)
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:406:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:276:5)
#11     _AsBroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:515:27)
#12     _rootRun (dart:async/zone.dart:1182:47)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#15     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#16     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#17     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#18     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
#19     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#20     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#21     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#22     _ErrorHandlingAsciiDecoderSink.close (dart:convert/ascii.dart:238:15)
#23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
#25     _rootRun (dart:async/zone.dart:1182:47)
#26     _CustomZone.run (dart:async/zone.dart:1093:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
#32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
#33     _StreamController.close (dart:async/stream_controller.dart:664:5)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:2051:21)
#35     _rootRunUnary (dart:async/zone.dart:1206:13)
#36     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#41     _StreamController._add (dart:async/stream_controller.dart:682:7)
#42     _StreamController.add (dart:async/stream_controller.dart:624:5)
#43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1587:35)
#44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1069:18)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.64, on Microsoft Windows [Version 10.0.18363.1139], locale en-IN)
    • Flutter version 1.22.0-2.0.pre.64 at C:\src\flutter
    • Framework revision 23032d772d (4 months ago), 2020-08-25 10:06:04 -0700
    • Engine revision 8107b36c7b
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Darshan\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.1139]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.55

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
This is a four month old version of master - I believe this bug has otherwise been fixed
