### ISSUE TITLE
ScrollController not attached to any scroll views. Failed assertion '_positions.isNotEmpty'

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter#72900]
This seems to be a recurrance of #33648.

## Steps to Reproduce

I have a very simple widget like this:

```dart
import 'package:flutter/material.dart';

class TestWidget extends StatefulWidget {
  const TestWidget({
    @required this.items,
    Key key,
  }) : super(key: key);

  final List<String> items;

  @override
  _TestWidgetState createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {
  final ScrollController _controller = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
      controller: _controller,
      isAlwaysShown: false,
      child: ListView.builder(
        itemCount: widget.items.length,
        itemBuilder: (context, index) {
          return ListTile(
            title: Text('${widget.items[index]}'),
            onTap: () {},
            dense: true,
          );
        },
      ),
    );
  }
}
```

And it is used as the only widget in a `Scaffold`:

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
      ),
      body: TestWidget(items: [
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p'
      ]),
    );
  }
```

The above code works perfectly fine. However if you change `isAlwaysShown` to `true` then on MacOS I get the following error.

<details>
  <summary>Logs</summary>

```dart
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: ScrollController not attached to any scroll views.
flutter: 'package:flutter/src/widgets/scroll_controller.dart':
flutter: Failed assertion: line 108 pos 12: '_positions.isNotEmpty'
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
flutter: #3      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:848:27)
flutter: #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
flutter: #6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
flutter: (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.118, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.118 at /Users/timh/local/flutter
    • Framework revision 5eabfc2447 (2 hours ago), 2020-12-23 12:09:02 -0800
    • Engine revision b7cd3f8e70
    • Dart version 2.12.0 (build 2.12.0-173.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.6 19G2021 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 3 categories.
```

</details>

**Comment by nt4f04uNd** [comment]
you didn't pass the controller to listview

**Comment by Timmmm** [comment]
Ahhh yeah that worked. Oops! Bit of a confusing API IMO - would be nice if this error message explained that the controller has to be attached to something else as well as the `ScrollBar`, something like:

    ScrollController not attached to any scroll views. It must be attached to a widget that implements ScrollView (this does not include Scrollbar).

Is that message correct?

**Comment by darshankawar** [comment]
@Timmmm 
Seems your original issue is resolved based on comment above. For the message you are getting above, you may check out [this](https://flutteragency.com/how-to-solve-scroll-controller-could-not-attached-to-any-scroll-views-in-flutter/) link and see if it helps.
Closing this as resolved.

**Comment by kevin4dhd** [comment]
The same error happens when you are using isAlwaysShown but it is in a scaffold drawer

**Comment by ronytesler** [comment]
@darshankawar @kevin4dhd also happens to me with this code on web:
 return Scaffold(
  resizeToAvoidBottomInset: false,
  body: Scrollbar(
    isAlwaysShown: true,
    controller: controller,
    child: ListView(
      controller: controller,
      children: <Widget>[
        Container(
          height: 600,
        )
      ],
    ),
  ),
);
