### ISSUE TITLE
Flutter cokdu calismiyor

### ISSUE THREAD

**Issue by Sako0003** [flutter/flutter#72995]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by iapicca** [comment]
@Sako0003 
please describe the bug and provide your `flutter doctor -v`

**Comment by Sako0003** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter clean

## exception

FileSystemException: FileSystemException: Creation failed, path = 'C:\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\@lt@@lt@@lt@@lt@@lt@@lt@@lt@ HEAD
d1bc06f032f9d6c148ea6b96b48261d6f545004f
=======
ae90085a8437c0ae94d6b5ad2741739ebc742cb4
@gt@@gt@@gt@@gt@@gt@@gt@@gt@ 78910062997c3a836feee883712c241a5fd22983' (OS Error: The system cannot find the path specified.
, errno = 3)

```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      _ensureExists (package:flutter_tools/src/cache.dart:1413:15)
#4      Cache.downloadFile (package:flutter_tools/src/cache.dart:491:5)
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:640:23)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:636:55)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:670:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:636:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:657:12)
#10     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:785:13)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:592:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:458:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:831:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#22     _rootRun (dart:async/zone.dart:1190:13)
#23     _CustomZone.run (dart:async/zone.dart:1093:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.20.5-0.0.pre.1, on Microsoft Windows [Version 10.0.19041.685], locale en-AS)
    • Flutter version 1.20.5-0.0.pre.1 at C:\flutter
    • Framework revision 98e61fe059 (3 hours ago), 2020-12-27 08:31:30 +0400
    • Engine revision <<<<<<< HE
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for
      detailed instructions.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by Sako0003** [comment]
package com.example.foodapp

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}

**Comment by darshankawar** [comment]
@Sako0003 
You seem to be on older version of Flutter.
This is already [fixed](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004) and available on latest master. Switch to latest master and try again to see if it works.
Closing this as already fixed. If you disagree, write in comments and I'll reopen it.
