### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by bhtri** [flutter/flutter#73022]
## Command
```
flutter run
```

## Steps to Reproduce
I want to show image in images/ onto ListView and get an error

## Logs
FileSystemException: Directory listing failed, OS Error: Permission denied, errno = 13
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:623:77)
#5      _parseAssetFromFile (package:flutter_tools/src/asset.dart:796:35)
#6      _parseAssets (package:flutter_tools/src/asset.dart:701:7)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:163:53)
<asynchronous suspension>
#8      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:380:44)
#9      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:494:47)
#10     HotRunner._fullRestartHelper.<anonymous closure> (package:flutter_tools/src/run_hot.dart:727:39)
#11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _runZoned (dart:async/zone.dart:1630:10)
#15     runZonedGuarded (dart:async/zone.dart:1618:12)
#16     runZoned (dart:async/zone.dart:1547:12)
#17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#18     HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:727:22)
<asynchronous suspension>
#19     HotRunner.restart (package:flutter_tools/src/run_hot.dart:669:44)
<asynchronous suspension>
#20     TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1578:61)
#21     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1643:13)
```
```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale ja-JP)
    • Flutter version 1.22.5 at $HOME/Development/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 54F1C9CB-95D1-480E-A906-CCB366AB705D • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3
      (simulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983

**Comment by pedromassangocode** [comment]
Same as https://github.com/flutter/flutter/issues/68810. Leaving this opened because the other one was closed by the author.

@bhtri  see https://github.com/flutter/flutter/issues/68810#issuecomment-714699148 to learn what caused this issue and how to fix it by yourself.

**Comment by hello-addweb** [comment]
it'll happen if you're on Android Q | 10.

And it will be solved by adding the following on the manifest file.

```
<application
        android:requestLegacyExternalStorage="true"
```

**Comment by jmagman** [comment]
@bhtri does your user have expected permissions to `images/` and the files in that directory?

**Comment by bhtri** [comment]
@jmagman @pedromassangocode 
I have checked permissions to `images/ `and the file in that directory, it pretty good

```
ls -la
drwxr-xr-x   4 usr  staff   128 12 29 18:30 images
....
-rw-r--r--@  1 usr  staff  128507 12 29 18:30 1.jpg
-rw-r--r--@  1 usr  staff  565653 12 29 18:30 2.png
```

I tried deleting the project and recreating it using `flutter create` it worked fine again.
I don't fully understand why deleting and re-creating the project works smoothly. (◎-◎;)!!

**Comment by bhtri** [comment]
i am using ios simulator but very thanks for your suggestion @hello-addweb  ( v^-ﾟ)Thanks♪

**Comment by pedromassangocode** [comment]
Hi @bhtri 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
