### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by trojancode** [flutter/flutter#73025]
## Command
```
flutter run --machine --target lib\main.dart -d 192.168.1.33:5555 --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url --dart-define environment=dev
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#4      _pluginFromPackage (package:flutter_tools/src/plugins.dart:317:53)
#5      findPlugins (package:flutter_tools/src/plugins.dart:352:27)
<asynchronous suspension>
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:1136:38)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:242:11)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:960:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _runZoned (dart:async/zone.dart:1630:10)
#15     runZoned (dart:async/zone.dart:1550:10)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.685], locale en-IN)
    • Flutter version 1.22.4 at C:\flutter
    • Framework revision 1aafb3a8b9 (6 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ajmal\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code
    • VS Code at C:\Users\ajmal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • SM A505F (mobile) • 192.168.1.33:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
geolocator-5.3.2+2
google_api_availability-2.0.4
import_js_library-1.0.2
location-3.1.0
location_permissions-3.0.0+1
location_web-1.0.0
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
video_player-1.0.1
video_player_web-0.1.4+1
wakelock-0.2.1+1
wakelock_web-0.1.0+3
webview_flutter-1.0.7

**Comment by pedromassangocode** [comment]
Hi @trojancode 
I see there's an open issue (https://github.com/flutter/flutter/issues/65021) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
