### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for F:\GitHubDesktopProject\PayTrak.app\android\gradlew.bat.

### ISSUE THREAD

**Issue by karthickchinnasamy33357** [flutter/flutter#73029]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=ZY223GCXDN --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for F:\GitHubDesktopProject\PayTrak.app\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:630:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:524:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:630:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      buildGradleApp (package:flutter_tools/src/android/gradle.dart:391:43)
#8      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:101:13)
#9      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:567:28)
<asynchronous suspension>
#10     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:591:33)
<asynchronous suspension>
#11     HotRunner.run.<anonymous closure> (package:flutter_tools/src/run_hot.dart)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.24.0-10.2.pre at C:\flutter
    • Framework revision 022b333a08 (6 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pc3\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\pc3\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\pc3\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (4 available)
    • Moto G 4 (mobile) • ZY223GCXDN • android-arm    • Android 7.0 (API 24)
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
clipboard_manager-0.0.4
cloud_firestore-0.14.2
cloud_firestore_web-0.2.0+5
contacts_service-0.3.10
firebase_analytics-6.0.2
firebase_analytics_web-0.1.1
firebase_auth-0.18.1+2
firebase_auth_web-0.3.1+1
firebase_core-0.5.1
firebase_core_web-0.2.0
firebase_database-4.1.1
fluttertoast-7.1.1
get_version-0.2.2
package_info-0.4.3
path_provider-1.6.22
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+4
path_provider_windows-0.0.4+1
permission-0.1.7
sms-0.2.4
sms_autofill-1.2.5
sms_receiver-0.3.1+1
sqflite-1.3.2+1
vibration-1.7.1
vibration_web-1.6.2

**Comment by pedromassangocode** [comment]
hi @karthickchinnasamy33357 
I see there's an open issue (https://github.com/flutter/flutter/issues/56975) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
