### ISSUE TITLE
Connected device (the doctor check crashed)

### ISSUE THREAD

**Issue by ad-on-is** [flutter/flutter#73031]
I just started getting a weird error message in VS Code saying `Cannot call write after a stream was destroyed` with an additional `The Flutter Daemon has terminated.`

I did not update nor change anything. It just started happening out of the blue.

After inspecting `flutter doctor -v` there seems to be an issue with ANDROID_SDK_ROOT. I've never had to set or change that variable, since Flutter uses the default SDK locations.

I tried adding the SDK-location to the `PATH` variable, but this didn't solve the issue.

``` 
PS C:\Users\adonis> flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.21277.1000], locale en-AT)
    • Flutter version 1.22.5 at D:\Projects\Development\Flutter\flutter-sdk-win
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\adonis\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\adonis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us
      know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment
      variable: C:\Users\adonis\AppData\Local\Android\sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
      #1      AndroidDevices.pollingGetDevices
      (package:flutter_tools/src/android/android_device_discovery.dart:71:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:467:60)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:457:12)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:171:20)
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:975:55)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1190:13)
      #8      _CustomZone.run (dart:async/zone.dart:1093:19)
      #9      _runZoned (dart:async/zone.dart:1630:10)
      #10     runZonedGuarded (dart:async/zone.dart:1618:12)
      #11     runZoned (dart:async/zone.dart:1547:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:191:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:290:47)
      #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:47)
      #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
      #17     _rootRunUnary (dart:async/zone.dart:1198:47)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
      #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
      #23     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
      #24     _rootRun (dart:async/zone.dart:1190:13)
      #25     _CustomZone.run (dart:async/zone.dart:1093:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 2 categories.
```

**Comment by ad-on-is** [comment]
A PC reboot fixed the issue
