### ISSUE TITLE
while i can show chat message in listview show this error

### ISSUE THREAD

**Issue by hadiuzzaman524** [flutter/flutter#73097]
```
`======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_list.dart': Failed assertion: line 178 pos 16: 'earliestUsefulChild != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  ListView file:///G:/Education%20Area/FLUTTER/flutter%20project/chat_application/chat/lib/messages.dart:40:31
When the exception was thrown, this was the stack: 
#2      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:178:16)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:132:12)
#5      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
...
The following RenderObject was being processed when the exception was fired: RenderSliverList#302d4 relayoutBoundary=up15 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.up, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 366.2, crossAxisExtent: 372.7, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 366.2, remainingCacheExtent: 616.2, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 305.0, paintExtent: 305.0, maxPaintExtent: 305.0, cacheExtent: 305.0)
...    scrollExtent: 305.0
...    paintExtent: 305.0
...    maxPaintExtent: 305.0
...    cacheExtent: 305.0
...  currently live children: 1 to 5
RenderObject: RenderSliverList#302d4 relayoutBoundary=up15 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.up, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 366.2, crossAxisExtent: 372.7, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 366.2, remainingCacheExtent: 616.2, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 305.0, paintExtent: 305.0, maxPaintExtent: 305.0, cacheExtent: 305.0)
    scrollExtent: 305.0
    paintExtent: 305.0
    maxPaintExtent: 305.0
    cacheExtent: 305.0
  currently live children: 1 to 5
...  child with index 1: RenderIndexedSemantics#a2efe relayoutBoundary=up16 NEEDS-PAINT
...    needs compositing
...    parentData: index=1; layoutOffset=0.0 (can use size)
...    constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(372.7, 61.0)
...    index: 1
...    child: RenderRepaintBoundary#bcd5f relayoutBoundary=up17 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...      layer: OffsetLayer#4b404
...        engine layer: OffsetEngineLayer#25a9f
...        offset: Offset(0.0, 244.2)
...      size: Size(372.7, 61.0)
...      metrics: 87.5% useful (1 bad vs 7 good)
...      diagnosis: this is a useful repaint boundary and should be kept
...      child: RenderPadding#ceb23 relayoutBoundary=up18 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...        size: Size(372.7, 61.0)
...        padding: EdgeInsets(0.0, 5.0, 0.0, 5.0)
...        textDirection: ltr
...        child: RenderFlex#a1970 relayoutBoundary=up19 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 5.0) (can use size)
...          constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...          size: Size(372.7, 51.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...          textBaseline: alphabetic
...  child with index 2: RenderIndexedSemantics#cd3f8 relayoutBoundary=up16 NEEDS-LAYOUT
...    needs compositing
...    parentData: index=2; layoutOffset=122.0 (can use size)
...    constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(372.7, 61.0)
...    index: 2
...    child: RenderRepaintBoundary#0ece3 relayoutBoundary=up17 NEEDS-LAYOUT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...      layer: OffsetLayer#f1fa4
...        engine layer: OffsetEngineLayer#bf55e
...        offset: Offset(0.0, 183.2)
...      size: Size(372.7, 61.0)
...      metrics: 80.0% useful (1 bad vs 4 good)
...      diagnosis: this is a useful repaint boundary and should be kept
...      child: RenderPadding#ace0d relayoutBoundary=up18 NEEDS-LAYOUT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...        size: Size(372.7, 61.0)
...        padding: EdgeInsets(0.0, 5.0, 0.0, 5.0)
...        textDirection: ltr
...        child: RenderFlex#17477 relayoutBoundary=up19 NEEDS-LAYOUT
...          parentData: offset=Offset(0.0, 5.0) (can use size)
...          constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...          size: Size(372.7, 51.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...          textBaseline: alphabetic
...  child with index 3: RenderIndexedSemantics#e38ed relayoutBoundary=up16 NEEDS-LAYOUT
...    needs compositing
...    parentData: index=3; layoutOffset=183.0 (can use size)
...    constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(372.7, 61.0)
...    index: 3
...    child: RenderRepaintBoundary#fe1a0 relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...      layer: OffsetLayer#3174b
...        engine layer: OffsetEngineLayer#c0636
...        offset: Offset(0.0, 122.2)
...      size: Size(372.7, 61.0)
...      metrics: 50.0% useful (1 bad vs 1 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderPadding#1a92a relayoutBoundary=up18 NEEDS-LAYOUT NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...        size: Size(372.7, 61.0)
...        padding: EdgeInsets(0.0, 5.0, 0.0, 5.0)
...        textDirection: ltr
...        child: RenderFlex#e1855 relayoutBoundary=up19 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: offset=Offset(0.0, 5.0) (can use size)
...          constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...          size: Size(372.7, 51.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...          textBaseline: alphabetic
...  child with index 4: RenderIndexedSemantics#37be0 relayoutBoundary=up16
...    needs compositing
...    parentData: index=4; layoutOffset=244.0 (can use size)
...    constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...    semantic boundary
...    size: Size(372.7, 61.0)
...    index: 4
...    child: RenderRepaintBoundary#bd38b relayoutBoundary=up17
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...      layer: OffsetLayer#1c91f
...        engine layer: OffsetEngineLayer#b96f1
...        offset: Offset(0.0, 61.2)
...      size: Size(372.7, 61.0)
...      metrics: 0.0% useful (1 bad vs 0 good)
...      diagnosis: insufficient data to draw conclusion (less than five repaints)
...      child: RenderPadding#1142a relayoutBoundary=up18
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...        size: Size(372.7, 61.0)
...        padding: EdgeInsets(0.0, 5.0, 0.0, 5.0)
...        textDirection: ltr
...        child: RenderFlex#d33d2 relayoutBoundary=up19
...          parentData: offset=Offset(0.0, 5.0) (can use size)
...          constraints: BoxConstraints(w=372.7, 0.0<=h<=Infinity)
...          size: Size(372.7, 51.0)
...          direction: horizontal
...          mainAxisAlignment: end
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...          textBaseline: alphabetic
...  child with index 5: RenderIndexedSemantics#8e69b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: index=5; layoutOffset=None
...    constraints: MISSING
...    semantic boundary
...    size: MISSING
...    index: 5
...    child: RenderRepaintBoundary#a21f0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      usefulness ratio: no metrics collected yet (never painted)
...      child: RenderPadding#fa59b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets(0.0, 5.0, 0.0, 5.0)
...        textDirection: ltr
...        child: RenderFlex#20c5f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0)
...          constraints: MISSING
...          size: MISSING
...          direction: horizontal
...          mainAxisAlignment: end
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...          textBaseline: alphabetic
====================================================================================================

======== Exception caught by rendering library =====================================================
Null check operator used on a null value
The relevant error-causing widget was: 
  ListView file:///G:/Education%20Area/FLUTTER/flutter%20project/chat_application/chat/lib/messages.dart:40:31
====================================================================================================`
```

**Comment by darshankawar** [comment]
@hadiuzzaman524 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Thanks.

**Comment by GaspardMerten** [comment]
You seem to have an overflow error caused by an unbounded height (maybe your message widget?). 

Please provide use with a code reproducing the error, otherwise it will be hard to help you.

**Comment by hadiuzzaman524** [comment]
Thanks, everyone! I fixed it. Unfortunately, I can return null in ListView.Builder that's why show this error!
