### ISSUE TITLE
android_alarm_manager not working and error

### ISSUE THREAD

**Issue by ariona** [flutter/flutter#73152]
I am trying to add `android_alarm_manager` but got the error, see the error log detail below. I have tried the example project too the error does not exist but the alarm is not triggered (nothing happened).

## Step to reproduce
1. Create new flutter project
2. Add `android_alarm_manager`
3. Copy example script from pub.dev
4. The app is running but nothing happened when alarm is triggered.

The error below is error from my app, i have created `application.java` as instructed, and changed the android:name attribute on application tag to `.Application`. But this error appeared.

### Error Log

```
PlatformException (PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
	at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:119)
	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onAttachedToEngine(AndroidAlarmManagerPlugin.java:90)
	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.registerWith(AndroidAlarmManagerPlugin.java:61)
	at com.example.muslimapp.Application.registerWith(Application.java:19)
	at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:178)
	at io.flutter.plugins.androidalarmmanager.AlarmService.startBackgroundIsolate(AlarmService.java:62)
	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:120)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:181)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
))
```
<details>
<summary>Flutter Doctor</summary>

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-ID)
    • Flutter version 1.22.5 at /Users/arionarian/Development/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/arionarian/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • POCOPHONE F1 (mobile) • 192.168.43.1:5555 • android-arm64 • Android 10 (API 29)
    ! Device 192.168.1.100:5555 is offline.

• No issues found!
</details>

**Comment by darshankawar** [comment]
@ariona 
Tried the [example](https://pub.dev/packages/android_alarm_manager/example) code sample from plugin page on latest stable and was able to see the alarm service starting and alarm being fired properly without any issues.

<img width="546" alt="Screenshot 2020-12-31 at 12 30 37 PM" src="https://user-images.githubusercontent.com/67046386/103398772-26851200-4b64-11eb-8ce0-c71721f0685c.png">


I/FlutterBackgroundExecutor( 4003): Starting AlarmService...
I/AndroidAlarmManagerPlugin( 4003): onAttachedToEngine
I/AlarmService( 4003): AlarmService started!
I/flutter ( 4003): Alarm fired!
I/flutter ( 4003): Increment counter!
I/flutter ( 4003): Alarm fired!
I/flutter ( 4003): Increment counter!

<details>
<summary>flutter doctor -v</summary>

```


[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM A260G (mobile)           • 5200763ebcfa861f • android-arm • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86 • Android 11
      (API 30) (emulator)

! Doctor found issues in 1 category.

```

</details>

Can you try to `flutter clean` and then `flutter run` to see if it helps ?

**Comment by ariona** [comment]
after `flutter clean` and `flutter run`

```
I/FlutterBackgroundExecutor(22888): Starting AlarmService...            
I/AndroidAlarmManagerPlugin(22888): onAttachedToEngine                  
W/FlutterEnginePluginRegistry(22888): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@617b908) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@6aa68a1).
I/AndroidAlarmManagerPlugin(22888): onAttachedToEngine                  
E/MethodChannel#(22888): Parameter messenger must not be null.          
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:119)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onAttachedToEngine(AndroidAlarmManagerPlugin.java:90)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.registerWith(AndroidAlarmManagerPlugin.java:61)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at com.example.muslimapp.Application.registerWith(Application.java:19)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:178)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.plugins.androidalarmmanager.AlarmService.startBackgroundIsolate(AlarmService.java:62)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:120)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at android.app.ActivityThread.main(ActivityThread.java:7562)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(22888):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/AlarmService(22888): AlarmService started!                            
I/flutter (22888): null                                                 
Syncing files to device POCOPHONE F1...                                 
E/flutter (22888): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/flutter (22888):      at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:119)     
E/flutter (22888):      at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onAttachedToEngine(AndroidAlarmManagerPlugin.java:90)
E/flutter (22888):      at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.registerWith(AndroidAlarmManagerPlugin.java:61)
E/flutter (22888):      at com.example.muslimapp.Application.registerWith(Application.java:19)                     
E/flutter (22888):      at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:178)
E/flutter (22888):      at io.flutter.plugins.androidalarmmanager.AlarmService.startBackgroundIsolate(AlarmService.java:62)
E/flutter (22888):      at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:120)
E/flutter (22888):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (22888):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (22888):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)       
E/flutter (22888):      at android.os.MessageQueue.nativePollOnce(Native Method)                                   
E/flutter (22888):      at android.os.MessageQueue.next(MessageQueue.java:336)                                     
E/flutter (22888):      at android.os.Looper.loop(Looper.java:181)                                                 
E/flutter (22888):      at android.app.ActivityThread.main(ActivityThread.java:7562)                               
E/flutter (22888):      at java.lang.reflect.Method.invoke(Native Method)                                          
E/flutter (22888):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)       
E/flutter (22888):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)                            
E/flutter (22888): )                                                                                               
E/flutter (22888): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:159:7) 
E/flutter (22888): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18) 
E/flutter (22888): <asynchronous suspension>                                                                       
E/flutter (22888): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)  
E/flutter (22888): #3      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:96:35)
E/flutter (22888): #4      _HomeScreenState.initAlarm (package:muslimapp/screens/home.dart:54:31)                  
E/flutter (22888): #5      _HomeScreenState.initState (package:muslimapp/screens/home.dart:49:5)                   
E/flutter (22888): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)        
E/flutter (22888): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)              
E/flutter (22888): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)              
E/flutter (22888): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)                
E/flutter (22888): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (22888): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)              
E/flutter (22888): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)                
E/flutter (22888): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)    
E/flutter (22888): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)                     
E/flutter (22888): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)        
E/flutter (22888): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)              
E/flutter (22888): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)              
E/flutter (22888): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)                
E/flutter (22888): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (22888): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)              
E/flutter (22888): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)                
E/flutter (22888): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (22888): #23     Element.i                                                                               
I/ample.muslimap(22888): Waiting for a blocking GC ProfileSaver                                                    
I/ample.muslimap(22888): Background young concurrent copying GC freed 5594(623KB) AllocSpace objects, 4(80KB) LOS objects, 15% free, 3036KB/3601KB, paused 80us total 100.956ms
I/ample.muslimap(22888): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 14.510ms                         
I/ample.muslimap(22888): ProcessProfilingInfo new_methods=807 is saved saved_to_disk=1 resolve_classes_delay=8000  
```

**Comment by ariona** [comment]
here is my `androidmanifest.xml`

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.muslimapp">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <!-- android:name="io.flutter.app.FlutterApplication"  -->
    <application
        android:name=".Application"
        android:label="muslimapp"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:showWhenLocked="true"
            android:turnScreenOn="true"
            >
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <service
            android:name="io.flutter.plugins.androidalarmmanager.AlarmService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="false"/>
        <receiver
            android:name="io.flutter.plugins.androidalarmmanager.AlarmBroadcastReceiver"
            android:exported="false"/>
        <receiver
            android:name="io.flutter.plugins.androidalarmmanager.RebootBroadcastReceiver"
            android:enabled="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>

    </application>
</manifest>
```

and here is the content of `Application.java` same with the example:

```
package com.example.muslimapp;

import io.flutter.app.FlutterApplication;
import io.flutter.plugins.androidalarmmanager.AlarmService;
import io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin;

@SuppressWarnings("deprecation")
public class Application extends FlutterApplication
    implements io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    AlarmService.setPluginRegistrant(this);
  }

  @Override
  @SuppressWarnings("deprecation")
  public void registerWith(io.flutter.plugin.common.PluginRegistry registry) {
    AndroidAlarmManagerPlugin.registerWith(
        registry.registrarFor("io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin"));
  }
}
```

**Comment by darshankawar** [comment]
@ariona 
Can you provide a complete minimal reproducible code sample that we can copy paste and run to see the issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
