### ISSUE TITLE
TextInputFormatter silently fails when invalid index access of newValue.text

### ISSUE THREAD

**Issue by droidery** [flutter/flutter#73179]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(50.0),
          child: TextField(
            controller: TextEditingController()..text = 'initial value',
            inputFormatters: [DoNothingFormatter()],
          ),
        ),
      ),
    );
  }
}

class DoNothingFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    final char = newValue.text[2];
    return newValue;
  }
}
```

3. Run with `flutter run --no-sound-null-safety --verbose`
4. Backspace until invalid access of character from `newValue.text`:

**Expected results:** 

1. This creates a formatter that invalidly accesses `newValue.text[2]` (sometimes it can be null).
2. There should be an exception or error message on out of bounds access

**Actual results:** 

1. No indication that something has failed in the logs

![backspace](https://user-images.githubusercontent.com/34681083/103431663-f737d900-4c27-11eb-88c7-92c2a956d321.gif)

Pressing backspace does not do anything when there is no index `2` (accessed in `newValue.text[2]`), the text just remains in TextInputFormatter and no error is thrown in the console.

<details>
  <summary>Logs</summary>

```
No logs after running app.
```

```
Analyzing text_formatter_issue...                                       

   info • The value of the local variable 'char' isn't used •
          lib/main.dart:31:11 • unused_local_variable

1 issue found. (ran in 7.6s)
```

```
→ flutter doctor -v
[✓] Flutter (Channel master, 1.26.0-2.0.pre.167, on macOS 11.1 20C69
    darwin-x64, locale en-US)
    • Flutter version 1.26.0-2.0.pre.167 at /Users/droidery/flutter
    • Framework revision d3a2259541 (5 hours ago), 2020-12-31 15:14:03 -0500
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/droidery/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6803

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
```

</details>

**Comment by iapicca** [comment]
@droidery 
running the provided [code sample](https://github.com/flutter/flutter/issues/73179#issue-777169240)
with the latest master and `Backspace until invalid access of character from newValue.text:`
I experience the described behavior, **however**
when I back space 3 more times it throws the following error

```bash
                   ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following RangeError was thrown during a platform message callback:
                    RangeError (index): Invalid value: Not in inclusive range 0..1: 2
                    
                    When the exception was thrown, this was the stack:
                    #0      _StringBase.[] (dart:core-patch/string_patch.dart:255:55)
                    #1      DoNothingFormatter.formatEditUpdate (package:issue/main.dart:29:31)
                    #2      EditableTextState._formatAndSetValue.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:2246:80)
                    #3      ListMixin.fold (dart:collection/list.dart:237:22)
                    #4      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:2244:39)
                    #5      EditableTextState.textEditingValue= (package:flutter/src/widgets/editable_text.dart:2462:5)
                    #6      RenderEditable._handleDelete (package:flutter/src/rendering/editable.dart:853:27)
                    #7      RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:550:7)
                    #8      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:634:17)
                    #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
                    #10     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:47)
                    #11     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
                    #12     _invoke3.<anonymous closure> (dart:ui/hooks.dart:217:15)
                    #16     _invoke3 (dart:ui/hooks.dart:216:10)
                    #17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457:7)
                    #18     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
                    (elided 3 frames from dart:async)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════

```
and the [cursor misbehave](https://user-images.githubusercontent.com/45637986/103437672-cdd07a80-4c32-11eb-99d5-09d1019ac23f.png)

<details>
<summary>logs</summary>

```bash
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:39515/O0KbIuRqjTg=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+5875 ms] W/IInputConnectionWrapper(12632): getExtractedText on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(12632): getTextBeforeCursor on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(12632): getExtractedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(12632): getTextBeforeCursor on inactive InputConnection
[  +26 ms] W/IInputConnectionWrapper(12632): getExtractedText on inactive InputConnection
[   +1 ms] W/IInputConnectionWrapper(12632): getTextBeforeCursor on inactive InputConnection
[+1536 ms] E/SpannableStringBuilder(12632): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[ +992 ms] I/chatty  (12632): uid=10410(com.example.issue) identical 6 lines
[        ] E/SpannableStringBuilder(12632): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[+1235 ms] E/SpannableStringBuilder(12632): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[ +285 ms] 
                    ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
                    The following RangeError was thrown during a platform message callback:
                    RangeError (index): Invalid value: Not in inclusive range 0..1: 2
                    
                    When the exception was thrown, this was the stack:
                    #0      _StringBase.[] (dart:core-patch/string_patch.dart:255:55)
                    #1      DoNothingFormatter.formatEditUpdate (package:issue/main.dart:29:31)
                    #2      EditableTextState._formatAndSetValue.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:2246:80)
                    #3      ListMixin.fold (dart:collection/list.dart:237:22)
                    #4      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:2244:39)
                    #5      EditableTextState.textEditingValue= (package:flutter/src/widgets/editable_text.dart:2462:5)
                    #6      RenderEditable._handleDelete (package:flutter/src/rendering/editable.dart:853:27)
                    #7      RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:550:7)
                    #8      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:634:17)
                    #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
                    #10     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:47)
                    #11     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
                    #12     _invoke3.<anonymous closure> (dart:ui/hooks.dart:217:15)
                    #16     _invoke3 (dart:ui/hooks.dart:216:10)
                    #17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457:7)
                    #18     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
                    (elided 3 frames from dart:async)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +337 ms] I/chatty  (12632): uid=10410(com.example.issue) identical 2 lines
[        ] E/SpannableStringBuilder(12632): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
[+30165 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueQXFBEB/issue/)
[  +34 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.example.issue/code_cache/issueQXFBEB/issue/)
[ +473 ms] Failure in ext.flutter.exit: ext.flutter.exit: (-32000) Bad state: The client closed with pending request "ext.flutter.exit".

[  +10 ms] Service protocol connection closed.
[        ] Application finished.
[   +5 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +8 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[        ] 965AY0WP5C tcp:43647 tcp:37945
[   +1 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --remove tcp:43647
[  +10 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +9 ms] Exit code 0 from: /home/francesco/Android/Sdk/platform-tools/adb -s 965AY0WP5C forward --list
[   +1 ms] "flutter run" took 165,828ms.
[ +257 ms] ensureAnalyticsSent: 253ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```
</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.167, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.167 at /home/francesco/snap/flutter/common/flutter
    • Framework revision d3a2259541 (14 hours ago), 2020-12-31 15:14:03 -0500
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.

```

</details>

**Comment by droidery** [comment]
@iapicca Thanks for running the example, I've now run the example on two emulators: Android and iOS.

The iOS emulator doesn't have any logging, but the Android emulator has the same error output as you get.

Not sure why iOS does not show the error messages.

**Comment by iapicca** [comment]
@droidery 
please note that it fails silently on web (just tried on [dartpad](https://dartpad.dartlang.org/?)),
anyhow, even with party with android behavior **the issue seems valid** to me,
it should throw immediately, not at the fourth attempt

**Comment by pedromassangocode** [comment]
I was able to reproduce the issue on iOS simulator. On Android, as said above it throws exception but it requires some additional attempts.

<details><summary>flutter doctor</summary>

```
/Users/pedromassango/dev/SDKs/flutter_master/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 1.26.0-2.0.pre.168, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.168 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 299e017e41 (20 hours ago), 2021-01-03 06:29:01 -0500
    • Engine revision 121b67fb85
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>
