### ISSUE TITLE
run app with chrome: Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge..

### ISSUE THREAD

**Issue by gnassro** [flutter/flutter#73188]
i've just start a new project using VS-code with flutter beta version (1.25.0-8.1.pre), when i  run the app with chrome debug, this error is show up:

> Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.
> Exited (sigterm)

**Comment by iapicca** [comment]
@gnassro 
can you provider your `flutter doctor -v `and your `flutter run -d chrome -v`

**Comment by gnassro** [comment]
> @gnassro
> can you provider your `flutter doctor -v `and your `flutter run -d chrome -v`

`# flutter doctor -v` 

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.25.0-8.1.pre at /opt/flutter
    • Framework revision 8f89f6505b (2 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /root/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /root/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_242-release"
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "1.8.0_242-release"

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • SM A107F (mobile) • R9WMA058R9J • android-arm    • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 88.0.4324.50 beta

• No issues found!
```

`flutter run -d chrome -v`

```
[ +262 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +119 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8f89f6505b941329a864fef1527243a72800bf4d
[   +2 ms] executing: [/opt/flutter/] git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[  +48 ms] Exit code 0 from: git tag --points-at 8f89f6505b941329a864fef1527243a72800bf4d
[        ] 1.25.0-8.1.pre
[ +144 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[   +1 ms] executing: [/opt/flutter/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +156 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +154 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +167 ms] executing: /root/Android/Sdk/platform-tools/adb devices -l
[  +45 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +287 ms] executing: /root/Android/Sdk/platform-tools/adb devices -l
[  +64 ms] Skipping pub get: version match.
[ +188 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/
[  +26 ms] Found plugin path_provider_linux at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +7 ms] Found plugin path_provider_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/
[  +12 ms] Found plugin path_provider_windows at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +75 ms] Found plugin webview_flutter at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/
[  +83 ms] Found plugin integration_test at /opt/flutter/packages/integration_test/
[ +467 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/
[   +4 ms] Found plugin path_provider_linux at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +3 ms] Found plugin path_provider_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/
[   +6 ms] Found plugin path_provider_windows at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +48 ms] Found plugin webview_flutter at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/
[  +73 ms] Found plugin integration_test at /opt/flutter/packages/integration_test/
[  +22 ms] Generating /root/projects/my_pckage/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +302 ms] List of devices attached
           R9WMA058R9J            device usb:1-1.2 product:a10sxx model:SM_A107F device:a10s transport_id:6
[  +19 ms] List of devices attached
           R9WMA058R9J            device usb:1-1.2 product:a10sxx model:SM_A107F device:a10s transport_id:6
[ +314 ms] Launching lib/main.dart on Chrome in debug mode...
[ +366 ms] Updating assets
[ +863 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +18 ms] Waiting for connection from debug service on Chrome...
[  +66 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/
[   +2 ms] Found plugin path_provider_linux at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +2 ms] Found plugin path_provider_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/
[   +4 ms] Found plugin path_provider_windows at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +37 ms] Found plugin webview_flutter at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/
[  +52 ms] Found plugin integration_test at /opt/flutter/packages/integration_test/
[  +52 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/
[   +2 ms] Found plugin path_provider_linux at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+6/
[   +3 ms] Found plugin path_provider_windows at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +30 ms] Found plugin webview_flutter at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/
[  +44 ms] Found plugin integration_test at /opt/flutter/packages/integration_test/
[+1394 ms] <- reset
[  +21 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /opt/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.NLEHPC/flutter_tool.LMLDYL/app.dill --libraries-spec file:///opt/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /root/projects/my_pckage/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.NLEHPC/flutter_tools.BHGFHC --filesystem-scheme org-dartlang-app --initialize-from-dill build/fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform file:///opt/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +20 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+81613 ms] Waiting for connection from debug service on Chrome... (completed in 83.3s)
[   +1 ms] Synced 34.8MB.
[   +1 ms] <- accept
[        ] Caching compiled dill
[+1732 ms] Using Google Chrome 88.0.4324.50 beta

[+1744 ms] [CHROME]: Opening in existing browser session.
[  +28 ms] [CHROME]:[0101/223715.982386:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!
[   +1 ms] [CHROME]:Most likely you need to configure your SUID sandbox correctly
[   +2 ms] Failed to launch browser. Command used to launch it: google-chrome --user-data-dir=/tmp/flutter_tools.NLEHPC/flutter_tools_chrome_device.GJBWHR --remote-debugging-port=44315 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:35553
[  +11 ms] "flutter run" took 90,422ms.
[  +18 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.
[  +10 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:278:11)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1414:9)
           #3      _rootRun (dart:async/zone.dart:1178:47)
           #4      _CustomZone.run (dart:async/zone.dart:1090:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:101:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:165:13)
           #11     _rootRun (dart:async/zone.dart:1178:47)
           #12     _CustomZone.run (dart:async/zone.dart:1090:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #21     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
           #22     _rootRun (dart:async/zone.dart:1178:47)
           #23     _CustomZone.run (dart:async/zone.dart:1090:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
           #34     _rootRun (dart:async/zone.dart:1178:47)
           #35     _CustomZone.run (dart:async/zone.dart:1090:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:815:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:670:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:663:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2027:21)
           #44     _rootRunUnary (dart:async/zone.dart:1202:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1097:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1002:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:807:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:681:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:624:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1563:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1061:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[ +229 ms] DwdsInjector: Received request for entrypoint at http://localhost:35553/main_module.bootstrap.js
[  +20 ms] MetadataProvider: Loading debug metadata...
[  +38 ms] MetadataProvider: Loaded debug metadata
[  +22 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:35553/main_module.bootstrap.js
[  +36 ms] ensureAnalyticsSent: 341ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[  +26 ms] Shutdown hooks complete
[  +16 ms] exiting with code 1
```

**Comment by wzslr321** [comment]
You can see in your erorr log "Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues." and version of google chrome " Using Google Chrome 88.0.4324.50 beta".  You should just easily be able to run a web server with `flutter run -d web-server --web-port 8000` and open it in the browser on localhost:8000 or try to install different google chrome version .

**Comment by gnassro** [comment]
by run `#flutter run -d web-server `   i can now test my app in any browser by access to `http://localhost:39207` (the port may be changed)

**Comment by deCardenas** [comment]
I think that is something related with antiviruses. When I have active the payment and online bank protection's I have the same error

**Comment by simon-zhangmuye** [comment]
I am facing the same issue. How do you solve this problem?

> by run `#flutter run -d web-server ` i can now test my app in any browser by access to `http://localhost:39207` (the port may be changed)

**Comment by simon-zhangmuye** [comment]
> i've just start a new project using VS-code with flutter beta version (1.25.0-8.1.pre), when i run the app with chrome debug, this error is show up:
> 
> > Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.
> > Exited (sigterm)
How do solve this problem. Thanks.

**Comment by gnassro** [comment]
> I am facing the same issue. How do you solve this problem?

as i said, i find another solution by running `#flutter run -d web-server` instead of `#flutter run -d chrome`.

NB: it worked with flutter 1.25.0-8.1.pre (beta), i didn't test it with another virsion
