### ISSUE TITLE
[file_selector] Desktop (Windows) app - getSavePath() - Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by jeremy-giles** [flutter/flutter#73189]
Creating a basic application with a button that executes the `getSavePath()` method.
When the button is clicked the exeption is thrown :
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(184)] Unhandled Exception: MissingPluginException(No implementation found for method getSavePath on channel plugins.flutter.io/file_selector)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      _MyAppState._saveFile (package:barcode_generator/main.dart:25:18)
<asynchronous suspension>
```

**Flutter Channel**
`Master`

**App Version**
```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  qr_flutter: ^3.2.0
  file_selector: ^0.7.0
```

**App Code**
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  _saveFile() async {
    final path = await getSavePath();
    final name = "hello_file_selector.txt";
    final data = Uint8List.fromList("Hello World!".codeUnits);
    final mimeType = "text/plain";
    final file = XFile.fromData(data, name: name, mimeType: mimeType);
    await file.saveTo(path);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text('Download'),
            onPressed: () {
              _saveFile();
            },
          ),
        ),
      ),
    );
  }
}
```

**Flutter Analyze**
```
info - 'await' applied to 'void', which is not a 'Future' - lib\main.dart:30:5 - await_only_futures
```

**Flutter Config**
```
Settings:
  enable-web: true
  enable-windows-desktop: true

Analytics reporting is currently enabled.
```

**Flutter Doctor**
```
[√] Flutter (Channel master, 1.26.0-2.0.pre.165, on Microsoft Windows [version 10.0.18363.1256], locale fr-CH)
    • Flutter version 1.26.0-2.0.pre.165 at C:\Users\***\Documents\Flutter\SDK\flutter\flutter
    • Framework revision efc84ab1ec (2 days ago), 2020-12-31 10:00:55 +0800
    • Engine revision 82b4ae86d6
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\***\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\***\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.18363.1256]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 87.0.664.66
```

**Comment by iapicca** [comment]
@jeremy-giles 
[file_selector](https://pub.dev/packages/file_selector) doesn't support windows just yet 

![image](https://user-images.githubusercontent.com/45637986/103444468-1c046e80-4c71-11eb-9428-075d0e2ffc88.png)

**Comment by jeremy-giles** [comment]
Thx for this answer @iapicca.
I found another solution with this package : https://pub.dev/packages/filepicker_windows
But, I will test it to compare the uses.

**Comment by stuartmorgan** [comment]
There are implementations of file_selector for the desktop platforms, they just aren't officially hosted yet:
https://github.com/google/flutter-desktop-embedding/tree/master/plugins/file_selector

Adding the Windows implementation package will allow using file_selector on Windows now (and will be harmless when it's eventually moved and endorsed by the main package).

**Comment by stuartmorgan** [comment]
> ![image](https://user-images.githubusercontent.com/45637986/103444468-1c046e80-4c71-11eb-9428-075d0e2ffc88.png)

Note that Windows will not currently be listed on any package. The pubspec.yaml, not the banner, is how the determine desktop support for a plugin at the moment.

> consider using [file_selector_windows](https://pub.dev/packages/file_selector_windows) instead

In addition, not instead, per the README.
