### ISSUE TITLE
[tool_crash] ProcessException: The command failedStdout:Stderr:/Users/kartikey/Desktop/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter:  write error (disk full?).  Continue? (y/n/^C) warning:  /Users/kartikey/Desktop/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter is probably truncated Command: unzip, OS error code: 50

### ISSUE THREAD

**Issue by detkartik** [flutter/flutter#73202]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed
Stdout:

Stderr:
/Users/kartikey/Desktop/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter:  write error (disk full?).  Continue? (y/n/^C) 
warning:  /Users/kartikey/Desktop/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter is probably truncated
 Command: unzip, OS error code: 50
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:463:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:231:19)
#3      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:727:22)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
```
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.14.6 18G1012 darwin-x64, locale en-IN)
    • Flutter version 1.22.5 at /Users/kartikey/Desktop/flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/kartikey/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/kartikey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 8410F07F-7BFA-4EF1-ABA7-B3C602E8C4CE • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2
      (simulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/72789

**Comment by pedromassangocode** [comment]
Hi @detkartik 
As said in https://github.com/flutter/flutter/issues/72789#issuecomment-749482804 this issue (or similar) was fixed but eventually was not merged on stable. Can you please try the `dev` channel and see if the issue reproduces?

Thank you

**Comment by detkartik** [comment]
@pedromassango thanks I will try and update you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
