### ISSUE TITLE
Getting exception when try to build apk

### ISSUE THREAD

**Issue by jaydip-pawar** [flutter/flutter#73211]
I am implementing a app in which i have added fingerprint authentication so that's why I have changed "FlutterActivity" with "FlutterFragmentActivity" and changed theme with "Theme.AppCompat.Light.NoActionBar" but after that authentication works properly but when try to build apk i am getting following exception.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:profileRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\nobit\AndroidStudioProjects\Production\secret_keeper\build\app\intermediates\flutter\profile\libs.jar.
         > Transform's input file does not exist: C:\Users\nobit\AndroidStudioProjects\Production\secret_keeper\build\app\intermediates\flutter\profile\libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:




Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


BUILD FAILED in 8m 58s
Running Gradle task 'assembleRelease'...                          542.8s (!)
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
```

**Comment by iapicca** [comment]
@jaydip-pawar 
the issue could have been solved in this [PR](https://github.com/flutter/flutter/pull/71446)

please consider the possible solutions proposed [here](https://github.com/flutter/flutter/issues/58247)
if the problem persists please provide your `flutter doctor -v` and you complete `flutter build apk -v`

**Comment by jaydip-pawar** [comment]
> @jaydip-pawar
> the issue could have been solved in this [PR](https://github.com/flutter/flutter/pull/71446)
> 
> please consider the possible solutions proposed [here](https://github.com/flutter/flutter/issues/58247)
> if the problem persists please provide your `flutter doctor -v` and you complete `flutter build apk -v`

After seeing some solutions, I have builded apk but it's crashing. When I run my app from emulator or by connecting physical device it's work properly but when I release the apk it's crashesh and throwing following exception:

```
E/flutter (29267): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.IllegalAccessError: io.flutter.plugins.localauth.AuthenticationHelper
E/flutter (29267): 	at io.flutter.plugins.localauth.a.g()
E/flutter (29267): 	at e.a.c.a.i$a.a()
E/flutter (29267): 	at io.flutter.embedding.engine.e.b.c()
E/flutter (29267): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage()
E/flutter (29267): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (29267): 	at android.os.MessageQueue.next(MessageQueue.java:328)
E/flutter (29267): 	at android.os.Looper.loop(Looper.java:191)
E/flutter (29267): 	at android.app.ActivityThread.main(ActivityThread.java:6016)
E/flutter (29267): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (29267): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
E/flutter (29267): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)
E/flutter (29267): 
F/flutter (29267): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env). 
```

**Comment by pedromassangocode** [comment]
This seems to be a different issue, please open a new issue and fill the issue template. Closing as solved.
Thank you
