### ISSUE TITLE
a failure in downloading fonts.zip (windows desktop enabled)

### ISSUE THREAD

**Issue by justwrite99** [flutter/flutter#73254]
## Steps to Reproduce

1. unzip the latest flutter stable 
2. run `flutter` and 'flutter config --enable-windows-desktop`
3. with my env, I saw below logs

## Logs

<details>
<summary>Logs</summary>

```
C:\Windows\System32>flutter doctor -vv
[ +110 ms] executing: [D:\work\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+1099 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 78910062997c3a836feee883712c241a5fd22983
[        ] executing: [D:\work\flutter/] git tag --points-at HEAD
[+1130 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.5
[   +7 ms] executing: [D:\work\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[+1109 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\work\flutter/] git ls-remote --get-url origin
[+1113 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[+2464 ms] Unable to locate an Android SDK.
[   +5 ms] executing: [D:\work\flutter/] git rev-parse --abbrev-ref HEAD
[+1084 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +28 ms] Downloading Material fonts...
[ +466 ms] HandshakeException: Handshake error in client (OS Error:
                        CERTIFICATE_VERIFY_FAILED: unable to get local issuer
                        certificate(../../third_party/boringssl/src/ssl/handshake.cc:354))
[   +9 ms] Downloading Material fonts... (completed in 0.5s)
[   +2 ms] Downloading Material fonts...
[ +355 ms] HandshakeException: Handshake error in client (OS Error:
                        CERTIFICATE_VERIFY_FAILED: unable to get local issuer
                        certificate(../../third_party/boringssl/src/ssl/handshake.cc:354))
[   +2 ms] Downloading Material fonts... (completed in 0.4s)
[   +1 ms] "flutter doctor" took 852ms.
[   +3 ms] Failed to download

https://storage.googleapis.com/flutter_infra/flutter/fonts/1363603dd17dd609018e53cdbd5fef6791814337/fonts.zip. Ensure
           you have network connectivity and then try again.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1486:11)
           #2      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #3      _rootRunBinary (dart:async/zone.dart:1214:47)
           #4      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #5      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #8      Future._completeError (dart:async/future_impl.dart:537:5)
           #9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
           #10     ArtifactUpdater._download (package:flutter_tools/src/cache.dart)
           #11     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #12     _rootRunBinary (dart:async/zone.dart:1214:47)
           #13     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #14     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #15     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #17     Future._completeError (dart:async/future_impl.dart:537:5)
           #18     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:593:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[   +2 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

```
```

</details>

## Request 

Is there a way to set my certificate file to flutter env?
Please give me some advices.

Thanks.

**Comment by justwrite99** [comment]
Fixed with the changed flutter.bat as below.

```shell
"%dart%" --root-certs-file="xxx.crt" --disable-dart-dev --packages="%flutter_tools_dir%\.packages" %FLUTTER_TOOL_ARGS% "%snapshot_path%" %* & exit /B !ERRORLEVEL!

```
