### ISSUE TITLE
scrollable.dart  ine 571 pos 12: ‘_drag == null': is not true.

### ISSUE THREAD

**Issue by kim-king-rong** [flutter/flutter#73288]
```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 571 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:571:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:401:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:401:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:264:7)
...
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#7de8b
  start behavior: start
====================================================================================================

======== Exception caught by gesture ===============================================================
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 580 pos 12: '_drag == null': is not true.
====================================================================================================
```

**Comment by darshankawar** [comment]
@kim-king-rong 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the issue.
Also check out [this](https://github.com/flutter/flutter/issues/65020) similar issue and see if the underlying issue comments resolves your issue too.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
