### ISSUE TITLE
Image Picker package is crashing 

### ISSUE THREAD

**Issue by azamsharp** [flutter/flutter#73280]
The package "  image_picker: ^0.6.7+17" is crashing when calling the getImage method. 

```dart
void _selectPhotoFromPhotoLibrary() async {
    final imagePicker = ImagePicker();
    final pickedFile = await imagePicker.getImage(source: ImageSource.gallery);

    setState(() {
      _image = File(pickedFile.path);
    });

  }
```

The error is shown below: 
```bash
36): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter ( 8636): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:157
E/flutter ( 8636): <asynchronous suspension>
E/flutter ( 8636): #1      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter ( 8636): #2      MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
E/flutter ( 8636): #3      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
E/flutter ( 8636): #4      ImagePicker.getImage (package:image_picker/image_picker.dart:106:21)
E/flutter ( 8636): #5      _AddIncidentsPage._selectPhotoFromPhotoLibrary
package:city_care/pages/add_incidents_page.dart:24
E/flutter ( 8636): #6      _AddIncidentsPage._optionSelected
```

**Comment by hauketoenjes** [comment]
This is a package specific question which is not directly related to flutter. If you have a bug/problem with the package, please file an issue over at the package's GitHub.

**Comment by TahaTesser** [comment]
Hi @azamsharp 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/72898
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
