### ISSUE TITLE
StateError: Bad state: No element

### ISSUE THREAD

**Issue by phil-zZ** [flutter/flutter#73313]
## command

flutter attach --app-id cc.read.ios.dev

## exception

StateError: Bad state: No element

```
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:63:32)
<asynchronous suspension>
#2      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:249:11)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-CN)
    • Flutter version 1.25.0-8.1.pre at /Users/ccdoky/Documents/Tools/flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (2 available)
    • phil的iPhone (mobile)       • 4deebe45d908b561043223206b95912182da444d • ios • iOS 14.2
    • iPhone 12 Pro Max (mobile) • C58EE33F-3A41-434A-96AB-110FAFFD5B1A     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by darshankawar** [comment]
@phil-zZ 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/73158
Please follow the link mentioned in underlying issue comment and see if it resolves your issue.
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by phil-zZ** [comment]
@darshankawar Thank you.
This is a bug with flutter_tools:
https://github.com/flutter/flutter/blob/b0a22998593fc605c723dee8ff4d9315c32cfe2c/packages/flutter_tools/lib/src/base/dds.dart#L63

duplicate of #72385.

**Comment by bkonyi** [comment]
@phil-zZ are you able to reproduce this consistently? If so, can you please follow up on #72385 with more details about your development environment and when exactly you encounter this error?

**Comment by aliasgarlabs** [comment]
You need to implement `orElse` for the `firstWhere` function.

Eg. 

```
list.firstWhere(
                  (element) => element.isDeleted,
                  orElse: () => null);


```
