### ISSUE TITLE
camera plugin crashes app on Huawei devices with "Request has already been finished"

### ISSUE THREAD

**Issue by Anudin** [flutter/flutter#73336]
## Steps to Reproduce

I build a quick [demo project](https://github.com/Anudin/flutter-camera-crash-demo), just run that and press the floating action button.
Note that this project uses the git version, which was suggested [here](https://github.com/flutter/flutter/issues/72961#issuecomment-751462864), but the crash was also reproducible with 0.6.3+2.

**Results:** 

It crashes reliably on two tested Huawei phones when `controller.takePicture()` is called.
No issues on a moto g7 plus and OnePlus 6 device.

<details>
  <summary>Logs</summary>
I added logs and device info to https://github.com/Anudin/flutter-camera-crash-demo/tree/master/logs

- - -

**flutter analyze**
```
Analyzing demo...
   info • Unused import: 'package:demo/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function
2 issues found. (ran in 1.4s)
```
</details>

**Comment by TahaTesser** [comment]
Hi @Anudin 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` including crash logs
Thank you

**Comment by Anudin** [comment]
Sorry, I missed the `--verbose` flag when submitting. Here they are:

<details>
  <summary>Logs</summary>

**flutter run --verbose**
```
[        ] An Observatory debugger and profiler on ANE LX1 is available at:
http://127.0.0.1:40023/3bOQMRv7NTQ=/
[+1677 ms] I/PermissionManager(21981): camera remind result:true
[        ] I/CameraManager(21981): open camera: 0, package name: com.example.demo
[        ] I/BackgroundPermManager(21981): pkgName: com.example.demo,pid: 21981 ,uidOf3RdApk: 10218
,permType: 0 ,permCfg: 1
[   +3 ms] I/HwCameraUtil(21981): notifySurfaceFlingerCameraStatus : isFront = false , isOpend = true
[ +511 ms] I/ViewRootImpl(21981): jank_removeInvalidNode all the node in jank list is out of time
[  +23 ms] D/AwareBitmapCacher(21981): handleInit switch not opened pid=21981
[+1959 ms] I/om.example.dem(21981): Starting profile saver IsSaveProfileNow end.
[+2163 ms] E/        (21981): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[+1953 ms] W/Settings(21981): Setting device_provisioned has moved from
android.provider.Settings.Secure to android.provider.Settings.Global.
[   +1 ms] V/HiTouch_HiTouchSensor(21981): User setup is finished.
[ +347 ms] V/AudioManager(21981): playSoundEffect   effectType: 0
[        ] V/AudioManager(21981): querySoundEffectsEnabled...
[ +526 ms] E/flutter (21981): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception:
CameraException(captureFailure, An error happened in the framework)
[   +1 ms] E/flutter (21981): #0      CameraController.takePicture
(package:camera/src/camera_controller.dart:279:7)
[        ] E/flutter (21981): <asynchronous suspension>
[        ] E/flutter (21981): #1      _CameraAppState.build.<anonymous closure>
(package:demo/main.dart:57:28)
[        ] E/flutter (21981): #2      _InkResponseState._handleTap
(package:flutter/src/material/ink_well.dart:993:19)
[        ] E/flutter (21981): #3      _InkResponseState.build.<anonymous closure>
(package:flutter/src/material/ink_well.dart:1111:38)
[   +1 ms] E/flutter (21981): #4      GestureRecognizer.invokeCallback
(package:flutter/src/gestures/recognizer.dart:183:24)
[   +1 ms] E/flutter (21981): #5      TapGestureRecognizer.handleTapUp
(package:flutter/src/gestures/tap.dart:598:11)
[   +1 ms] E/flutter (21981): #6      BaseTapGestureRecognizer._checkUp
(package:flutter/src/gestures/tap.dart:287:5)
[   +1 ms] E/flutter (21981): #7      BaseTapGestureRecognizer.handlePrimaryPointer
(package:flutter/src/gestures/tap.dart:222:7)
[   +1 ms] E/flutter (21981): #8      PrimaryPointerGestureRecognizer.handleEvent
(package:flutter/src/gestures/recognizer.dart:476:9)
[   +1 ms] E/flutter (21981): #9      PointerRouter._dispatch
(package:flutter/src/gestures/pointer_router.dart:77:12)
[   +1 ms] E/flutter (21981): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
[   +1 ms] E/flutter (21981): #11     _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:377:8)
[   +1 ms] E/flutter (21981): #12     PointerRouter._dispatchEventToRoutes
(package:flutter/src/gestures/pointer_router.dart:120:18)
[   +1 ms] E/flutter (21981): #13     PointerRouter.route
(package:flutter/src/gestures/pointer_router.dart:106:7)
[   +1 ms] E/flutter (21981): #14     GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:358:19)
[   +1 ms] E/flutter (21981): #15     GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:338:22)
[   +1 ms] E/flutter (21981): #16     RendererBinding.dispatchEvent
(package:flutter/src/rendering/binding.dart:267:11)
[   +1 ms] E/flutter (21981): #17     GestureBinding._handlePointerEvent
(package:flutter/src/gestures/binding.dart:295:7)
[        ] E/flutter (21981): #18     GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:240:7)
[   +2 ms] E/flutter (21981): #19     GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:213:7)
[   +1 ms] E/flutter (21981): #20     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] E/flutter (21981): #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter (21981): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] E/flutter (21981): #23     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] E/flutter (21981): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] E/flutter (21981):
[ +327 ms] E/ion     (21981): ioctl c0044901 failed with code -1: Invalid argument
[        ] D/AndroidRuntime(21981): Shutting down VM
[        ] W/om.example.dem(21981): Accessing hidden method
Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
[        ] E/om.example.dem(21981): [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile
method fail.
[  +11 ms] E/AndroidRuntime(21981): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(21981): Process: com.example.demo, PID: 21981
[        ] E/AndroidRuntime(21981): java.lang.IllegalStateException: Request has already been
finished
[        ] E/AndroidRuntime(21981): 	at
io.flutter.plugins.camera.PictureCaptureRequest.finish(PictureCaptureRequest.java:40)
[   +1 ms] E/AndroidRuntime(21981): 	at
io.flutter.plugins.camera.Camera.lambda$takePicture$0$Camera(Camera.java:257)
[        ] E/AndroidRuntime(21981): 	at
io.flutter.plugins.camera.-$$Lambda$Camera$kpdf-S9lnD9lSxBgWhomOdHv80s.onImageAvailable(Unknown
Source:4)
[        ] E/AndroidRuntime(21981): 	at
android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800)
[        ] E/AndroidRuntime(21981): 	at android.os.Handler.dispatchMessage(Handler.java:112)
[        ] E/AndroidRuntime(21981): 	at android.os.Looper.loop(Looper.java:216)
[        ] E/AndroidRuntime(21981): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
[        ] E/AndroidRuntime(21981): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(21981): 	at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
[        ] E/AndroidRuntime(21981): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
[  +37 ms] I/Process (21981): Sending signal. PID: 21981 SIG: 9
[ +123 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +7 ms] executing: /home/bastianb/Android/Sdk/platform-tools/adb -s 9WV7N18423001660 forward
--list
[  +16 ms] Exit code 0 from: /home/bastianb/Android/Sdk/platform-tools/adb -s 9WV7N18423001660
forward --list
[        ] 9WV7N18423001660 tcp:40023 tcp:33807
[   +3 ms] executing: /home/bastianb/Android/Sdk/platform-tools/adb -s 9WV7N18423001660 forward
--remove tcp:40023
[  +21 ms] DevFS: Deleting filesystem on the device
(file:///data/user/0/com.example.demo/code_cache/demoTSMOFC/demo/)
[ +258 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not
completed
[   +3 ms] executing: /home/bastianb/Android/Sdk/platform-tools/adb -s 9WV7N18423001660 forward
--list
[  +17 ms] Exit code 0 from: /home/bastianb/Android/Sdk/platform-tools/adb -s 9WV7N18423001660
forward --list
[   +3 ms] "flutter run" took 38,664ms.
[ +148 ms] ensureAnalyticsSent: 140ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +10 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /home/bastianb/.local/opt/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/bastianb/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • ANE LX1 (mobile) • 9WV7N18423001660 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**flutter analyze**
```
Analyzing demo...
   info • Unused import: 'package:demo/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function
2 issues found. (ran in 1.4s)
```
</details>

I found no crash report besides what `flutter run --verbose` reported.

**Comment by Anudin** [comment]
This crash does not occur on version 0.5.8+17

**Comment by mvanbeusekom** [comment]
Hi @Anudin, could you test if this problem still persists in version 0.6.4+5 of the camera plugin?

**Comment by BeMacized** [comment]
I was able to reproduce this problem on a Huawei P20 Lite.

@Anudin I submitted a fix for this here: flutter/plugins#3414. Would you be able to check if this solved your issue?

**Comment by antoninobajeli** [comment]
Thanks to @TahaTesser for merging my issue into this one!
I didn't search in the best way. I stay tuned to test any new release of the CAMERA Plugin.

Cheers, Tony

**Comment by Anudin** [comment]
@mvanbeusekom Yes, it persists in 0.6.4+5

@BeMacized Yes, the fix works! I was able to successfully capture a picture on the Huawei device which crashed before, everything worked as expected. However, the following lines still appeared in the log:

```
W/Camera  (21971): pictureCaptureCallback.onCaptureFailed(): An error happened in the framework
W/Camera  (21971): pictureCaptureCallback.onCaptureFailed(): An error happened in the framework
W/Camera  (21971): pictureCaptureCallback.onCaptureFailed(): An error happened in the framework
W/Camera  (21971): pictureCaptureCallback.onCaptureFailed(): An error happened in the framework
W/Camera  (21971): pictureCaptureCallback.onCaptureFailed(): An error happened in the framework
W/Camera  (21971): pictureCaptureCallback.onCaptureFailed(): An error happened in the framework
```

**Comment by BeMacized** [comment]
@Anudin Glad to hear! 

The log lines are there on purpose. For now we've opted to ignore the error given by Huawei devices, but we still log it. This shouldn't affect use of the plugin, but might help us later when running into similar issues with other devices.

**Comment by TahaTesser** [comment]
hI @Anudin 
it should be landed in the `camera` release, thanks for the confirmation. 
Closing as https://github.com/flutter/plugins/pull/3414 is merged!
Thank you
