### ISSUE TITLE
[tool_crash] ClientException

### ISSUE THREAD

**Issue by MohamedMohamedMostafa** [flutter/flutter#73356]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ClientException
```
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:50:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:16:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:282:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:441:16)
#5      _rootRunBinary (dart:async/zone.dart:1210:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1104:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1010:7)
#8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:132:11)
#12     _addErrorWithReplacement (dart:async/stream_pipe.dart:180:8)
#13     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:287:11)
#14     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
#15     _rootRunBinary (dart:async/zone.dart:1210:47)
#16     _CustomZone.runBinary (dart:async/zone.dart:1104:19)
#17     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1010:7)
#18     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
#19     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
#20     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
#21     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:811:19)
#22     _StreamController._addError (dart:async/stream_controller.dart:689:7)
#23     _StreamController.addError (dart:async/stream_controller.dart:641:5)
#24     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1158:22)
```
```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\src\flutter
    • Framework revision 8f89f6505b (3 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Mohamed\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.2
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
sqflite-1.3.2+1
video_player-1.0.1
video_player_web-0.1.4+1

**Comment by jmagman** [comment]
There's a lot of info stripped out of this autogenerated crash report (to protect your PII), can you attach the log that was generated at the same time?  Something like `flutter_01.log` in your project directory.
