### ISSUE TITLE
_RenderSegmentedControl's computeDryLayout function uses wrong constraints

### ISSUE THREAD

**Issue by jamesblasco** [flutter/flutter#73362]
<img width="867" alt="Captura de pantalla 2021-01-05 a las 22 47 46" src="https://user-images.githubusercontent.com/19904063/103703737-660a8e80-4fa8-11eb-8450-ccd61345f7a4.png">

Related PR https://github.com/flutter/flutter/pull/70656

CODE WHERE THE PROBLEM IS
https://github.com/flutter/flutter/blob/542084d08830a6d7d64c70e4a367eaed4ca3c74a/packages/flutter/lib/src/cupertino/sliding_segmented_control.dart#L850-L858

Inside `computeDryLayout` method, `_computeOverallSizeFromChildSize` is called. This method uses the constraints from the RendexBox and it will through an error as computeDryLayout is expected to be called before the renderbox has been laid out. In computeDryLayout it should use the constraints passed as param. 

I think the fix is an easy change 
```dart
  Size _computeOverallSizeFromChildSize(Size childSize, BoxConstraints constraints) {
    return constraints.constrain(Size(childSize.width * childCount + totalSeparatorWidth, childSize.height));
  }

  @override
  Size computeDryLayout(BoxConstraints constraints) {
    final Size childSize = _calculateChildSize(constraints);
    return _computeOverallSizeFromChildSize(childSize, constraints);
  }

```

VERSION:  Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale es-ES)

**Comment by darshankawar** [comment]
@jamesblasco 
Can you provide a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by jamesblasco** [comment]
```dart

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            DryLayoutWidget(
              child: Padding(
                padding: EdgeInsets.all(20),
                child: Text('Hey'),
              ),
            ),
            DryLayoutWidget(
              child: CupertinoSlidingSegmentedControl<bool>(
                groupValue: true,
                children: {true: Text('Active'), false: Text('Filtered')},
                onValueChanged: (value) {},
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class DryLayoutWidget extends SingleChildRenderObjectWidget {
  final Widget child;

  DryLayoutWidget({required this.child}) : super(child: child);
  @override
  RenderObject createRenderObject(BuildContext context) {
    return DryLayoutRenderBox();
  }
}

class DryLayoutRenderBox extends RenderProxyBox {
  @override
  void performLayout() {
    final child = this.child;
    if (child != null) {
      final childSize = child.computeDryLayout(constraints);
      child.layout(BoxConstraints.tight(childSize));
      size = childSize;
    } else {
      size = Size.zero;
    }
  }
}

```

**Comment by jamesblasco** [comment]
@goderbauer might have something to say about this error

**Comment by darshankawar** [comment]
@jamesblasco 
The code sample seem to be incomplete. I am getting compile errors on `computeDryLayout` and `DryLayoutWidget({required this.child}) : super(child: child);`

**Comment by jamesblasco** [comment]
It should work the Flutter master version with null safety activated. On dartpad for example there is no method `computeDryLayout` yet. I tried on  1.26.0-1.0.pre

**Comment by darshankawar** [comment]
<details>
<summary>error log</summary>

```
======== Exception caught by rendering library =====================================================
The following StateError was thrown during performLayout():
Bad state: A RenderObject does not have any constraints before it has been laid out.

The relevant error-causing widget was: 
  DryLayoutWidget file:///Users/dhs/Documents/NCFlutter/webtest/lib/main.dart:21:13
When the exception was thrown, this was the stack: 
#0      RenderObject.constraints (package:flutter/src/rendering/object.dart:1453:7)
#1      RenderBox.constraints (package:flutter/src/rendering/box.dart:2152:43)
#2      _RenderSegmentedControl._computeOverallSizeFromChildSize (package:flutter/src/cupertino/sliding_segmented_control.dart:851:12)
#3      _RenderSegmentedControl.computeDryLayout (package:flutter/src/cupertino/sliding_segmented_control.dart:857:12)
#4      RenderBox._computeDryLayout (package:flutter/src/rendering/box.dart:1815:26)
...
The following RenderObject was being processed when the exception was fired: DryLayoutRenderBox#54995 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...  size: MISSING
RenderObject: DryLayoutRenderBox#54995 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  size: MISSING
...  child: RenderUnconstrainedBox#2dfd2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none>
...    constraints: MISSING
...    size: MISSING
...    alignment: Alignment.center
...    textDirection: ltr
...    child: RenderDecoratedBox#ae58c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0)
...      constraints: MISSING
...      size: MISSING
...      decoration: BoxDecoration
...        color: tertiarySystemFill(*color = Color(0x1e767680)*, darkColor = Color(0x3d767680), highContrastColor = Color(0x33767680), darkHighContrastColor = Color(0x51767680), resolved by: AnimatedBuilder(animation: Listenable.merge([AnimationController#c3078(⏭ 1.000; paused), AnimationController#90430(⏮ 0.000; paused), AnimationController#3acac(⏮ 0.000; paused), AnimationController#fb8a8(⏮ 0.000; paused)])))
...          debugLabel: tertiarySystemFill
...          color: Color(0x1e767680)
...          darkColor: Color(0x3d767680)
...          highContrastColor: Color(0x33767680)
...          darkHighContrastColor: Color(0x51767680)
...          last resolved: AnimatedBuilder
...        borderRadius: BorderRadius.circular(8.0)
...      configuration: ImageConfiguration(bundle: PlatformAssetBundle#e4ea1(), devicePixelRatio: 3.5, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...      child: RenderPadding#42c34 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets(3.0, 2.0, 3.0, 2.0)
...        textDirection: ltr
...        child: _RenderSegmentedControl<bool>#20c5b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0)
...          constraints: MISSING
...          size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: DryLayoutRenderBox#54995 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1920 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Column file:///Users/dhs/Documents/NCFlutter/webtest/lib/main.dart:12:15
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderFlex#46676 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1920 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Scaffold file:///Users/dhs/Documents/NCFlutter/webtest/lib/main.dart:11:13
====================================================================================================


```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.179, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.179 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a293c82251 (28 hours ago), 2021-01-05 04:04:03 -0500
    • Engine revision b7352132cd
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 6.0 (API 23) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac
      OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>
