### ISSUE TITLE
the flutter plugin when setting ndk { abiFilters "armeabi-v7a" },it's failed with couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by gitdogogo** [flutter/flutter#73396]
## Steps to Reproduce

1. Run `flutter create -i swift -a java --platforms=ios,android --template=plugin test_flutter_plugin`.
2. `cd test_flutter_plugin` and `code .` to open it in vscode,You can open it any way you like
3. Expand the example and find the android folder，then Right click on it --> open in Android studio
4. click in Grade Scripts -> build.gradle(Module : android.app), add setting `ndk {
            abiFilters "armeabi-v7a"
        }` in defaultConfig, save and Click Sync Now on android studio the upper right
5. now back to vscode or cd in `test_flutter_plugin\example` and run `flutter run`

**Expected results:** I want it to work，and Launch a simple app

**Actual results:** the app crashes

<details>
  <summary>Logs</summary>

```
Launching lib\main.dart on PACM00 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         6.8s
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                16.1s
E/FlutterLoader(28197): Flutter initialization failed.
E/FlutterLoader(28197): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/FlutterLoader(28197):         at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader(28197):         at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader(28197):         at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:178)
E/FlutterLoader(28197):         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:289)     
E/FlutterLoader(28197):         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:192)     
E/FlutterLoader(28197):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:234)
E/FlutterLoader(28197):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:154)
E/FlutterLoader(28197):         at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
E/FlutterLoader(28197):         at android.app.Activity.performCreate(Activity.java:7976)
E/FlutterLoader(28197):         at android.app.Activity.performCreate(Activity.java:7965)
E/FlutterLoader(28197):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)  
E/FlutterLoader(28197):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)   
E/FlutterLoader(28197):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)    
E/FlutterLoader(28197):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/FlutterLoader(28197):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
E/FlutterLoader(28197):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
E/FlutterLoader(28197):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
E/FlutterLoader(28197):         at android.os.Handler.dispatchMessage(Handler.java:107)
E/FlutterLoader(28197):         at android.os.Looper.loop(Looper.java:237)
E/FlutterLoader(28197):         at android.app.ActivityThread.main(ActivityThread.java:7830)
E/FlutterLoader(28197):         at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(28197):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/FlutterLoader(28197):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
E/FlutterLoader(28197): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/FlutterLoader(28197):         at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/FlutterLoader(28197):         at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/FlutterLoader(28197):         at java.lang.System.loadLibrary(System.java:1667)
E/FlutterLoader(28197):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:129)
E/FlutterLoader(28197):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:123)
E/FlutterLoader(28197):         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader(28197):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader(28197):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader(28197):         at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(28197): FATAL EXCEPTION: main
E/AndroidRuntime(28197): Process: com.example.test_flutter_plugin_example, PID: 28197
E/AndroidRuntime(28197): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test_flutter_plugin_example/com.example.test_flutter_plugin_example.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/AndroidRuntime(28197):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3534)   
E/AndroidRuntime(28197):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)
E/AndroidRuntime(28197):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(28197):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
E/AndroidRuntime(28197):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
E/AndroidRuntime(28197):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
E/AndroidRuntime(28197):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(28197):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(28197):        at android.app.ActivityThread.main(ActivityThread.java:7830)
E/AndroidRuntime(28197):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28197):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(28197):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
E/AndroidRuntime(28197): Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/AndroidRuntime(28197):        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:243)
E/AndroidRuntime(28197):        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:289)     
E/AndroidRuntime(28197):        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:192)     
E/AndroidRuntime(28197):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:234)
E/AndroidRuntime(28197):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:154)
E/AndroidRuntime(28197):        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
E/AndroidRuntime(28197):        at android.app.Activity.performCreate(Activity.java:7976)
E/AndroidRuntime(28197):        at android.app.Activity.performCreate(Activity.java:7965)
E/AndroidRuntime(28197):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)  
E/AndroidRuntime(28197):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)   
E/AndroidRuntime(28197):        ... 11 more
E/AndroidRuntime(28197): Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/AndroidRuntime(28197):        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/AndroidRuntime(28197):        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/AndroidRuntime(28197):        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:178)
E/AndroidRuntime(28197):        ... 20 more
E/AndroidRuntime(28197): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/AndroidRuntime(28197):        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/AndroidRuntime(28197):        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime(28197):        at java.lang.System.loadLibrary(System.java:1667)
E/AndroidRuntime(28197):        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:129)
E/AndroidRuntime(28197):        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:123)
E/AndroidRuntime(28197):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(28197):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(28197):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(28197):        at java.lang.Thread.run(Thread.java:919)
E/FlutterLoader(28567): Flutter initialization failed.
E/FlutterLoader(28567): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/FlutterLoader(28567):         at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader(28567):         at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader(28567):         at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:178)
E/FlutterLoader(28567):         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:289)     
E/FlutterLoader(28567):         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:192)
E/FlutterLoader(28567):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:234)
E/FlutterLoader(28567):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:154)
E/FlutterLoader(28567):         at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
E/FlutterLoader(28567):         at android.app.Activity.performCreate(Activity.java:7976)
E/FlutterLoader(28567):         at android.app.Activity.performCreate(Activity.java:7965)
E/FlutterLoader(28567):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)  
E/FlutterLoader(28567):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)   
E/FlutterLoader(28567):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)    
E/FlutterLoader(28567):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/FlutterLoader(28567):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
E/FlutterLoader(28567):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
E/FlutterLoader(28567):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
E/FlutterLoader(28567):         at android.os.Handler.dispatchMessage(Handler.java:107)
E/FlutterLoader(28567):         at android.os.Looper.loop(Looper.java:237)
E/FlutterLoader(28567):         at android.app.ActivityThread.main(ActivityThread.java:7830)
E/FlutterLoader(28567):         at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader(28567):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/FlutterLoader(28567):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
E/FlutterLoader(28567): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/FlutterLoader(28567):         at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/FlutterLoader(28567):         at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/FlutterLoader(28567):         at java.lang.System.loadLibrary(System.java:1667)
E/FlutterLoader(28567):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:129)
E/FlutterLoader(28567):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:123)
E/FlutterLoader(28567):         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader(28567):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader(28567):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader(28567):         at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(28567): FATAL EXCEPTION: main
E/AndroidRuntime(28567): Process: com.example.test_flutter_plugin_example, PID: 28567
E/AndroidRuntime(28567): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test_flutter_plugin_example/com.example.test_flutter_plugin_example.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/AndroidRuntime(28567):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3534)   
E/AndroidRuntime(28567):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)    
E/AndroidRuntime(28567):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(28567):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
E/AndroidRuntime(28567):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
E/AndroidRuntime(28567):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
E/AndroidRuntime(28567):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(28567):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(28567):        at android.app.ActivityThread.main(ActivityThread.java:7830)
E/AndroidRuntime(28567):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28567):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(28567):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
E/AndroidRuntime(28567): Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/AndroidRuntime(28567):        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:243)
E/AndroidRuntime(28567):        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:289)     
E/AndroidRuntime(28567):        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:192)     
E/AndroidRuntime(28567):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:234)
E/AndroidRuntime(28567):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:154)
E/AndroidRuntime(28567):        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
E/AndroidRuntime(28567):        at android.app.Activity.performCreate(Activity.java:7976)
E/AndroidRuntime(28567):        at android.app.Activity.performCreate(Activity.java:7965)
E/AndroidRuntime(28567):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)  
E/AndroidRuntime(28567):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)   
E/AndroidRuntime(28567):        ... 11 more
E/AndroidRuntime(28567): Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/AndroidRuntime(28567):        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/AndroidRuntime(28567):        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/AndroidRuntime(28567):        at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:178)
E/AndroidRuntime(28567):        ... 20 more
E/AndroidRuntime(28567): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test_flutter_plugin_example--hdSpa0bRBlvP0Djl5SWXQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
E/AndroidRuntime(28567):        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/AndroidRuntime(28567):        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime(28567):        at java.lang.System.loadLibrary(System.java:1667)
E/AndroidRuntime(28567):        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:129)
E/AndroidRuntime(28567):        at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:123)
E/AndroidRuntime(28567):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(28567):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(28567):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(28567):        at java.lang.Thread.run(Thread.java:919)
```

```
Analyzing example...
No issues found! (ran in 2.5s)
```

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale zh-CN)
    • Flutter version 1.22.5 at D:\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • PACM00 (mobile) • ONQ8TKSORO4L5DEM • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@gitdogogo 
I believe this is a same issue as https://github.com/flutter/flutter/issues/73307, just with a different abiFilter. It's better to track this issue in original as we discussed before.
Closing this as duplicate.
