### ISSUE TITLE
FlutterError: Unsupported operation: Infinity or NaN toInt in RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#73498]
**Problem:**
We received via crashlytics several dozens reports of FlutterError: Unsupported operation: Infinity or NaN toInt in the `getMinChildIndexForScrollOffset` method of the `RenderSliverFixedExtentBoxAdaptor` class on our production app.

**Stack traces:**

<details>
<summary>logs</summary>

```bash
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unsupported operation: Infinity or NaN toInt. Error thrown Instance of 'yx'.
       at .#0      _Double.toInt (dart:core-patch/double.dart:192)
       at .#1      _Double.round (dart:core-patch/double.dart:160)
       at .#2      RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset (package:flutter/src/rendering/sliver_fixed_extent_list.dart:108)
       at .#3      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:184)
       at .#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#5      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:132)
       at .#6      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:170)
       at .#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#8      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:507)
       at .#9      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1561)
       at .#10     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1470)
       at .#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#30     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
       at .#31     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498)
       at .#32     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243)
       at .#33     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402)
       at .#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#38     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1308)
       at .#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#42     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:830)
       at .#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#44     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207)
       at .#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#51     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#57     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#61     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3222)
       at .#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#65     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:685)
       at .#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113)
       at .#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1777)
       at .#77     RenderView.performLayout (package:flutter/src/rendering/view.dart:167)
       at .#78     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634)
       at .#79     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884)
       at .#80     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:436)
       at .#81     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914)
       at .#82     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302)
       at .#83     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117)
       at .#84     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055)
       at .#85     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971)
       at .#86     _rootRun (dart:async/zone.dart:1190)
       at .#87     _CustomZone.run (dart:async/zone.dart:1093)
       at .#88     _CustomZone.runGuarded (dart:async/zone.dart:997)
       at .#89     _invoke (dart:ui/hooks.dart:251)
       at .#90     _drawFrame (dart:ui/hooks.dart:209)
```
</details>

**Comment by talent-apps** [comment]
Output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1) 
    • Android SDK at C:\Users\XXX\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\XXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • Pixel 3a (mobile) • 94AAY0LLBG • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @talent-apps 
Can you please provide your complete `crash logs`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by talent-apps** [comment]
@TahaTesser 
These crash reports come from crashlytics. That's all the info that is present in these reports.
This issue occurs on **multiple devices** (44% Xiaomi, 44% Huawei, 6% realme, 4% Lenovo, 2% Other) all of which have **Android version 10**.

**Comment by TahaTesser** [comment]
Hi @talent-apps 
Can you please provide your `pubspec.yaml` of this production and `flutter run --release --verbose` logs connected to a physical device
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
