### ISSUE TITLE
NoSuchMethodError in _HeroFlight._handleAnimationUpdate

### ISSUE THREAD

**Issue by talent-apps** [flutter/flutter#73496]
**Problem:**
We received via crashlytics several dozens reports of `NoSuchMethodError` in the `_handleAnimationUpdate` method of the `_HeroFlight` class on our production app.

**Stack traces:**
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: NoSuchMethodError: The method '<optimized out>' was called on null.
Receiver: null
Tried calling: <optimized out>(). Error thrown Instance of 'yx'.
       at .#0      _HeroFlight._handleAnimationUpdate (package:flutter/src/widgets/heroes.dart:550)
       at .#1      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199)
       at .#2      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199)
       at .#3      ReverseAnimation._statusChangeHandler (package:flutter/src/animation/animations.dart:292)
       at .#4      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199)
       at .#5      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:199)
       at .#6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:782)
       at .#7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:798)
       at .#8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238)
       at .#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117)
       at .#10     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1031)
       at .#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377)
       at .#12     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1029)
       at .#13     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:963)
       at .#14     _rootRunUnary (dart:async/zone.dart:1206)
       at .#15     _CustomZone.runUnary (dart:async/zone.dart:1100)
       at .#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005)
       at .#17     _invoke1 (dart:ui/hooks.dart:265)
       at .#18     _beginFrame (dart:ui/hooks.dart:192)
```

**Comment by talent-apps** [comment]
Output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1) 
    • Android SDK at C:\Users\XXX\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\XXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • Pixel 3a (mobile) • 94AAY0LLBG • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
```

**Comment by pedromassangocode** [comment]
Hi @talent-apps 
Can you please provide your `flutter doctor -v`, your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.

Are you able to share a reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Hi @talent-apps 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by talent-apps** [comment]
These reports come from crashlytics.
This is the way the `Hero` widget is used in the app:

**Source screen:**
```
ListTile(
  onTap: () => {...},
  leading: Hero(
    tag:.docId,
    child: ...,
  ),
  contentPadding: const EdgeInsets.symmetric(horizontal: 4.0),
  title: Text(...),
  trailing: Tooltip(
    message: ...,
    child: IconButton(
      icon: Icon(Icons.delete),
      onPressed: () => {...},
    ),
  ),
);
``` 
**Target screen:**
```
StreamBuilder<...>(
  stream: ...,
  initialData: ...,
  builder: (context, snapshot) {
    return GestureDetector(
      onTap: () => {...},
      child: Hero(
        tag: docId,
        child: ...,
      ),
    );
  },
);
```

**Comment by pedromassangocode** [comment]
Hi @talent-apps 
Can you please provide a code sample that I can copy/paste and run it?
The code above is not complete as it misses some part of code that where replaced with `...`.

Thank you

**Comment by friebetill** [comment]
I have seen the error several times now on Crashlytics. Unfortunately I don't have a code sample for the error yet, but I have at least the unobscured Firebase report. I know it doesn't help much yet, but at least it's a start.
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove(). Error thrown Instance of 'ErrorDescription'.
       at _HeroFlight._handleAnimationUpdate(_HeroFlight.java:550)
       at AnimationLocalStatusListenersMixin.notifyStatusListeners(AnimationLocalStatusListenersMixin.java:199)
       at AnimationLocalStatusListenersMixin.notifyStatusListeners(AnimationLocalStatusListenersMixin.java:199)
       at ReverseAnimation._statusChangeHandler(ReverseAnimation.java:292)
       at AnimationLocalStatusListenersMixin.notifyStatusListeners(AnimationLocalStatusListenersMixin.java:199)
       at AnimationLocalStatusListenersMixin.notifyStatusListeners(AnimationLocalStatusListenersMixin.java:199)
       at AnimationController._checkStatusChanged(AnimationController.java:782)
       at AnimationController._tick(AnimationController.java:798)
       at Ticker._tick(Ticker.java:238)
       at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1117)
       at SchedulerBinding.<fn>(SchedulerBinding.java:1031)
       at _LinkedHashMapMixin.forEach(_LinkedHashMapMixin.java)
       at SchedulerBinding.handleBeginFrame(SchedulerBinding.java:1029)
       at SchedulerBinding._handleBeginFrame(SchedulerBinding.java:963)
```

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
