### ISSUE TITLE
Running `flutter test` in checked mode causes assertion failures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#7351]
Specifically, the assertion failure [is here](https://github.com/flutter/flutter/blob/1fa8a254a308f517ec133fbba5cc9fdb39698a72/packages/flutter_tools/lib/src/test/flutter_platform.dart#L166). We should also be running the tests in checked mode.

```
unhandled error during test:
'package:flutter_tools/src/test/flutter_platform.dart': Failed assertion: line 166 pos 18: '!controllerSinkClosed' is not true.
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:24)
#1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:31)
#2      FlutterPlatform._startTest.<_startTest_async_body> (package:flutter_tools/src/test/flutter_platform.dart:166:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107:26)
#5      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185:15)
#6      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107:14)
#7      StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107:26)
#8      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185:15)
#9      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107:14)
#10     _rootRunUnary (dart:async/zone.dart:1158)
#11     _CustomZone.runUnary (dart:async/zone.dart:1037)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#15     _Future._complete (dart:async/future_impl.dart:467)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#17     Future.any.<anonymous closure> (dart:async/future.dart:356)
#18     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107:26)
#19     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185:15)
#20     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107:14)
#21     StackZoneSpecification._registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107:26)
#22     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185:15)
#23     StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:107:14)
#24     _rootRunUnary (dart:async/zone.dart:1158)
#25     _CustomZone.runUnary (dart:async/zone.dart:1037)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#27     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#28     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#29     _Future._completeWithValue (dart:async/future_impl.dart:477)
#30     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#31     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185:15)
#32     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97:48)
#33     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185:15)
#34     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97:48)
#35     _rootRun (dart:async/zone.dart:1150)
#36     _CustomZone.run (dart:async/zone.dart:1026)
#37     _CustomZone.runGuarded (dart:async/zone.dart:924)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#41     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#42     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

**Comment by eseidelGoogle** [comment]
How do I run `flutter test` in checked mode?

**Comment by Hixie** [comment]
We should always run `flutter` in checked mode.

**Comment by chinmaygarde** [comment]
> How do I run `flutter test` in checked mode?

I was running the file containing `main` of Flutter tools directly using the Dart binary. Then you can toggle the checked mode flag to run into this issue. You can also do this by launching the Flutter tools target from the IDE (you will have to edit the configuration from IntelliJ to set the working directory and extra flags).

**Comment by eseidelGoogle** [comment]
```
diff --git a/bin/flutter b/bin/flutter
index c34db6b..afc88f9 100755
--- a/bin/flutter
+++ b/bin/flutter
@@ -67,4 +67,4 @@ fi
 
 set -e
 "$DART" --snapshot="$SNAPSHOT_PATH" --packages="$FLUTTER_TOOLS_DIR/.packages" "$SCRIPT_PATH"
-"$DART" "$SNAPSHOT_PATH" "$@"
+"$DART" --checked "$SNAPSHOT_PATH" "$@"
```
Presumably the above would turn checked mode always on for `flutter`?

**Comment by Hixie** [comment]
We presumably have to pass it to the snapshotter? Dunno, try it. :-)

You can tell which mode you're in by putting in an `assert(false);`, it'll throw in checked mode and not otherwise.
