### ISSUE TITLE
Firebase tests are failing with Android permission problem

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#73581]
Starting with https://github.com/flutter/flutter/commit/c243d834ce41bc5d279b0264efbc6b3c9e0df53d the firebase tests are failing with the following exception:

```
java.lang.SecurityException: getActiveSubscriptionInfoList: Neither user 10076 nor current process has android.permission.READ_PHONE_STATE.
     FATAL EXCEPTION: main
Process: com.google.android.apps.messaging, PID: 8286
java.lang.SecurityException: getActiveSubscriptionInfoList: Neither user 10076 nor current process has android.permission.READ_PHONE_STATE.
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at com.android.internal.telephony.ISub$Stub$Proxy.getActiveSubscriptionInfoList(ISub.java:564)
	at android.telephony.SubscriptionManager.getActiveSubscriptionInfoList(SubscriptionManager.java:591)
	at pmc.l(PG:62)
	at nwm.b(PG:88)
	at com.google.android.apps.messaging.shared.datamodel.BugleContentProviderInternal.dump(PG:21)
	at android.app.ActivityThread.handleDumpProvider(ActivityThread.java:2991)
	at android.app.ActivityThread.-wrap8(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

https://firebase.corp.google.com/project/flutter-infra/testlab/histories/bh.1b29258e8f97b976/matrices/7356799314703214256/executions/bs.308b1395c436db0

To rule out the change in question, I have reverted it in https://github.com/flutter/flutter/commit/edfb6305d803fb0aaed0def47d355a2d3e48232d. However, firebase continues to fail making me believe that this is problem with the firebase test lab.

**Comment by jmagman** [comment]
Also failing in presubmit.
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20firebase_abstract_method_smoke_test/5794/overview

**Comment by keyonghan** [comment]
affected recipe seems have been reverted: https://flutter-review.googlesource.com/c/recipes/+/9660
\cc @dnfield

**Comment by dnfield** [comment]
This was my recipe change. I'll retest before relanding
