### ISSUE TITLE
Intermittent "Failed to create server socket" when running tests on Travis

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7362]
I'm guessing what triggered this is our random port selection when running the tests with coverage.

```dart
Shell: Could not start Observatory HTTP server:
Shell: SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 5432
Shell: #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:524)
Shell: #1      _RootZone.runUnary (dart:async/zone.dart:1404)
Shell: #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
Shell: #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
Shell: #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
Shell: #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
Shell: #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
Shell: #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
Shell: #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
Shell: #9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
Shell: #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Full log: [log.txt](https://github.com/flutter/flutter/files/688631/log.txt)

**Comment by eseidelGoogle** [comment]
Seems like we need some way to re-roll when the port is in use.  That will at least reduce the incidence of these failures.

**Comment by Hixie** [comment]
We don't randomly pick ports anymore.
