### ISSUE TITLE
Exception: null. The flutter tool cannot access the file or directory.

### ISSUE THREAD

**Issue by KhalidWar** [flutter/flutter#73674]
I'm getting the following error when I try to run flutter run:

```
khalid@linux:~/Software/Development/FlutterProjects/yaanyo$ flutter run
Launching lib/main.dart on KB2007 in debug mode...
Exception: null. The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
```
## Steps to Reproduce

1. Installed Android Studio from official site.
2. downloaded flutter using terminal 'git clone' into desired directory.
3. Run a flutter app.

System: 
```khalid@linux:~$ neofetch
           `.:/ossyyyysso/:.               khalid@linux 
        .:oyyyyyyyyyyyyyyyyyyo:`           ------------ 
      -oyyyyyyyodMMyyyyyyyysyyyyo-         OS: Kubuntu 20.10 x86_64 
    -syyyyyyyyyydMMyoyyyydmMMyyyyys-       Host: Inspiron 7559 1.3.1 
   oyyysdMysyyyydMMMMMMMMMMMMMyyyyyyyo     Kernel: 5.8.0-36-generic 
 `oyyyydMMMMysyysoooooodMMMMyyyyyyyyyo`    Uptime: 17 mins 
 oyyyyyydMMMMyyyyyyyyyyyysdMMysssssyyyo    Packages: 2303 (dpkg), 3 (snap) 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Shell: bash 5.0.17 
oyyyysoodMyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Resolution: 1920x1080 
yyysdMMMMMyyyyyyyyyyyyyyyyyyysosyyyyyyyy   DE: Plasma 5.19.5 
yyysdMMMMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy   WM: KWin 
oyyyyysosdyyyyyyyyyyyyyyyyyyydMMMMysyyyo   WM Theme: Breeze 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Theme: Breeze [Plasma], Breeze [GTK2/3] 
 oyyyyyydMMMysyyyyyyyyyyysdMMyoyyyoyyyo    Icons: breeze [Plasma], breeze [GTK2/3] 
 `oyyyydMMMysyyyoooooodMMMMyoyyyyyyyyo     Terminal: konsole 
   oyyysyyoyyyysdMMMMMMMMMMMyyyyyyyyo      CPU: Intel i7-6700HQ (8) @ 3.500GHz 
    -syyyyyyyyydMMMysyyydMMMysyyyys-       GPU: Intel HD Graphics 530 
      -oyyyyyyydMMyyyyyyysosyyyyo-         GPU: NVIDIA GeForce GTX 960M 
        ./oyyyyyyyyyyyyyyyyyyo/.           Memory: 5750MiB / 15876MiB 
           `.:/oosyyyysso/:.
```

## Logs

<details>
<summary>Logs</summary>

```
khalid@linux:~$ flutter doctor -v
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.275 at /home/khalid/Software/Development/flutter
    • Framework revision d9044a8a61 (32 hours ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/khalid/Software/Development/Sdk/
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/khalid/Software/Development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: null. The flutter tool cannot access the file or directory.
      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:738:3)
      #2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:686:3)
      #3      _run (package:flutter_tools/src/base/error_handling_io.dart:533:7)
      <asynchronous suspension>
      #4      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:375:31)
      <asynchronous suspension>
      #5      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:302:13)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>


[✓] Android Studio
    • Android Studio at /home/khalid/Software/Development/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/khalid/Software/Development/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • KB2007 (mobile) • 13d42e3f • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.
```
</details>

Here's which flutter output:
```
khalid@linux:~$ which flutter dart
/home/khalid/Software/Development/flutter/bin/flutter
/home/khalid/Software/Development/flutter/bin/dart
```

I've PATH added to ```~./bashrc```:
```
export PATH="$PATH:/home/khalid/Software/Development/flutter/bin"
```

I always thought that current user, in linux systems, had all read and write privileges inside home directory.

**Comment by iapicca** [comment]
@KhalidWar 
do you have this stuff in your `~/.bashrc`?

```bash
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
```

**Comment by KhalidWar** [comment]
> @KhalidWar
> do you have this stuff in your `~/.bashrc`?
> 
> ```shell
> export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre
> export ANDROID_SDK_ROOT=$HOME/Android/Sdk
> ```
No. 

I added those two lines as they are. 
Ran ```source ~/.bashrc```

Still same problem.

Updated Sdk path to my Sdk directory like:
```export ANDROID_SDK_ROOT=/home/khalid/Software/Development/Sdk```

Still same problem.

```/usr/lib/jvm/``` doesn't exist. Do I have to manually install jvm?

**Comment by TahaTesser** [comment]
Hi @KhalidWar 
You can use Android Studio's JVM
`export JAVA_HOME=/home/taha/Code/android-studio/jre`
Can you please `ls -l` permissions output of the Flutter SDK, Android SDK?
Thank you

**Comment by KhalidWar** [comment]
Hey @TahaTesser  Thanks for helping me out here. I appreciate it.

```
khalid@linux:~/Software/Development/Sdk$ ls -l
total 44
drwxrwxr-x  6 khalid khalid 4096 Jan  9 19:13 build-tools
drwxrwxr-x  7 khalid khalid 4096 Jan  9 19:14 emulator
drwxrwxr-x  3 khalid khalid 4096 Jan  9 19:13 fonts
drwxrwxr-x  2 khalid khalid 4096 Jan  9 18:57 licenses
drwxrwxr-x  3 khalid khalid 4096 Jan  9 19:13 patcher
drwxrwxr-x  6 khalid khalid 4096 Jan  9 19:13 platforms
drwxrwxr-x  5 khalid khalid 4096 Jan 10 10:48 platform-tools
drwxrwxr-x 32 khalid khalid 4096 Jan 10 09:09 skins
drwxrwxr-x  3 khalid khalid 4096 Jan  9 19:13 sources
drwxrwxr-x  4 khalid khalid 4096 Jan  9 19:12 system-images
drwxrwxr-x  6 khalid khalid 4096 Jan  9 19:14 tools
```

```
khalid@linux:~/Software/Development/flutter$ ls -l
total 76
-rw-rw-r--  1 khalid khalid 10620 Jan 10 13:30 analysis_options.yaml
-rw-rw-r--  1 khalid khalid  2773 Jan 10 13:30 AUTHORS
drwxrwxr-x  4 khalid khalid  4096 Jan 10 13:30 bin
-rw-rw-r--  1 khalid khalid  2723 Jan 10 11:07 CODE_OF_CONDUCT.md
-rw-rw-r--  1 khalid khalid   711 Jan 10 11:07 CODEOWNERS
-rw-rw-r--  1 khalid khalid  5184 Jan 10 13:30 CONTRIBUTING.md
-rw-rw-r--  1 khalid khalid  1591 Jan 10 13:30 dartdoc_options.yaml
drwxrwxr-x 15 khalid khalid  4096 Jan 10 13:30 dev
drwxrwxr-x 10 khalid khalid  4096 Jan 10 13:30 examples
-rw-rw-r--  1 khalid khalid  1731 Jan 10 11:07 flutter_console.bat
-rw-rw-r--  1 khalid khalid  1519 Jan 10 11:07 LICENSE
drwxrwxr-x 12 khalid khalid  4096 Jan 10 13:30 packages
-rw-rw-r--  1 khalid khalid  1107 Jan 10 11:07 PATENT_GRANT
-rw-rw-r--  1 khalid khalid  4687 Jan 10 13:30 README.md
-rw-rw-r--  1 khalid khalid    18 Jan 11 08:02 version
```

**Comment by KhalidWar** [comment]
Okay.

After a full day of uninstalling and reinstalling flutter, android-studio, changing channels, rebasing gits, the problem has been solved. 

**Solution:**
- Closed android-studio and all related processes, then DELETED Sdk folder. 
- Reopening android-studio shows an error stating that Sdk isn't installed and prompts to install it.
- Let android-studio install it and BAM! Back in business.

Please feel free to close this issue.

**Comment by TahaTesser** [comment]
Hi @KhalidWar 
Glad you resolved the issue, happy coding
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by EurikaProg201** [comment]
In the directory in which `Android/Sdk` directory is, you type this command `chmod -R 777 Android
` . I was facing the same problem  but I was able to fix it with that command.
