### ISSUE TITLE
"@getters::package:flutter/src/ widgets/widget_inspector.dart::_location is already bound"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#73678]
I got a crash when hot restarting, as shown below. I've no idea how to reproduce, but I suspect the (legitimate) compilation error I got in the previous hot restart may be related?

Here's the logs with commentary:

```
ianh@burmese:~/dev/house-of-rooves/dashboard$ flutter run -d linux --pid-file /tmp/flutter.pid
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
```

The above is just the regular `flutter run` output. Then there's some dbus issue:

```
(house_of_rooves_dashboard:14187): GLib-GIO-CRITICAL **: 15:09:55.897: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

Then there's some logs from my code which we can ignore:
```
flutter: requesting records...
flutter: receiving records...
```
The sync finishes:
```
Syncing files to device Linux...                                   119ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Linux is available at:
http://127.0.0.1:33651/SVCyHnI9l6w=/

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
```
Then there's some more logs from my code and an exception because I'm using a plugin for sound that doesn't have a Linux port yet; we can ignore all that:
```
flutter: 720 records received in 1s
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method initSoundpool on channel pl.ukaszapps/soundpool)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      Soundpool._connect (package:soundpool/soundpool.dart:290:20)
<asynchronous suspension>
```

At this point I hit `R` to hot restart, but I had a typo in my code so that failed. Weirdly, the logs are all out of order here, with the "Performing hot restart" being printed _after_ the compilation error message:
```
lib/main.dart:47:57: Error: The getter 'inMillieconds' isn't defined for the class
'Duration'.
 - 'Duration' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'inMillieconds'.
  print('$count records received in ${stopwatch.elapsed.inMillieconds}ms');
                                                        ^^^^^^^^^^^^^   
Performing hot restart...                                               
Restarted application in 259ms.
Try again after fixing the above error(s).
```

I then fixed the typo and hit `R` again, and that's when the exception that this bug is about happened:

```
Unhandled exception:                                                    
root::package:house_of_rooves_dashboard/main.dart::Dashboard::@getters::package:flutter/src/
widgets/widget_inspector.dart::_location is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:200:7) 
#1      Class.computeCanonicalNames (package:kernel/ast.dart:1205:51)   
#2      Library.computeCanonicalNames (package:kernel/ast.dart:561:14)  
#3      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:10800:13)
#4      Component.computeCanonicalNames (package:kernel/ast.dart:10762:7)
#5      sortComponent (package:vm/kernel_front_end.dart:679:13)         
#6      FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:656:5)
#7      FrontendCompiler.recompileDelta                                 
(package:frontend_server/frontend_server.dart:766:13)
<asynchronous suspension>                                               
the Dart compiler exited unexpectedly.                                  
Performing hot restart...                                              ⣟the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
ianh@burmese:~/dev/house-of-rooves/dashboard$ 
```

<details><summary>Full unedited logs</summary>

```
ianh@burmese:~/dev/house-of-rooves/dashboard$ flutter run -d linux --pid-file /tmp/flutter.pid
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

(house_of_rooves_dashboard:14187): GLib-GIO-CRITICAL **: 15:09:55.897: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
flutter: requesting records...
flutter: receiving records...
Syncing files to device Linux...                                   119ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Linux is available at:
http://127.0.0.1:33651/SVCyHnI9l6w=/

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
flutter: 720 records received in 1s
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method initSoundpool on channel pl.ukaszapps/soundpool)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      Soundpool._connect (package:soundpool/soundpool.dart:290:20)
<asynchronous suspension>


lib/main.dart:47:57: Error: The getter 'inMillieconds' isn't defined for the class
'Duration'.
 - 'Duration' is from 'dart:core'.                                      
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'inMillieconds'.
  print('$count records received in ${stopwatch.elapsed.inMillieconds}ms');
                                                        ^^^^^^^^^^^^^   
Performing hot restart...                                               
Restarted application in 259ms.
Try again after fixing the above error(s).

Unhandled exception:                                                    
root::package:house_of_rooves_dashboard/main.dart::Dashboard::@getters::package:flutter/src/
widgets/widget_inspector.dart::_location is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:200:7) 
#1      Class.computeCanonicalNames (package:kernel/ast.dart:1205:51)   
#2      Library.computeCanonicalNames (package:kernel/ast.dart:561:14)  
#3      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:10800:13)
#4      Component.computeCanonicalNames (package:kernel/ast.dart:10762:7)
#5      sortComponent (package:vm/kernel_front_end.dart:679:13)         
#6      FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:656:5)
#7      FrontendCompiler.recompileDelta                                 
(package:frontend_server/frontend_server.dart:766:13)
<asynchronous suspension>                                               
the Dart compiler exited unexpectedly.                                  
Performing hot restart...                                              ⣟the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
ianh@burmese:~/dev/house-of-rooves/dashboard$ 
```
</details>

**Comment by jonahwilliams** [comment]
I believe the issue with linux builds will be fixed by https://github.com/flutter/flutter/pull/72196

The actual compilation error should already be fixed, but it is waiting on a dart roll. You can work around this by running `flutter config --no-experimental-invalidation-strategy`

**Comment by jonahwilliams** [comment]
The underlying dart issues has been fixed (though after looking I can't find the commit :(   )
