### ISSUE TITLE
Error: The method 'isDuplicateColumnError' isn't defined for the class 'DatabaseException'.

### ISSUE THREAD

**Issue by guit4eva** [flutter/flutter#73698]
I suddenly can't run my Flutter application after reloading it. Tried the following:

1) Switching to beta channel and upgrading
2) Pub cache repair
3) Flutter clean
4) Flutter doctor - no issues
5) Reset simulator

It keeps failing with:

**"Error: The method 'isDuplicateColumnError' isn't defined for the class 'DatabaseException'."**

Is there anything else I could try? I haven't done anything obvious that would have broken it, so not sure why it suddenly won't work after stopping and restarting the app.

Stacktrace:

```../../../.pub-cache/hosted/pub.dartlang.org/clock-1.1.0-nullsafety.1/lib/src/utils.dart:59:9: Error: A value
                         of type 'num' can't be assigned to a variable of type 'int'.
                         [        ]     day.clamp(1, daysInMonth(year, month));
                         [        ]         ^
                         [+5473 ms] Persisting file store
                         [  +14 ms] Done persisting file store
                         [ +460 ms] Target kernel_snapshot failed: Exception
                                    #0      KernelSnapshot.build
(package:flutter_tools/src/build_system/targets/common.dart:262:7)
                                    <asynchronous suspension>
                                    #1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:795:27)
                                    #2      _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #5      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                                    #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                                    #10     Node.computeChanges (package:flutter_tools/src/build_system/build_system.dart)
                                    #11     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #14     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                                    #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                                    #19     FileStore.diffFileList (package:flutter_tools/src/build_system/file_store.dart)
                                    #20     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #23     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #26     Future.wait.<anonymous closure> (dart:async/future.dart:410:22)
                                    #27     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #30     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                                    #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                                    #35     FileStore._hashFile (package:flutter_tools/src/build_system/file_store.dart)
                                    #36     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #39     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #42     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
                                    #43     _rootRun (dart:async/zone.dart:1190:13)
                                    #44     _CustomZone.run (dart:async/zone.dart:1093:19)
                                    #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
                                    #46     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1037:23)
                                    #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
                                    #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
                                    #49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
                                    #50     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
                     
                         [ +124 ms] "flutter assemble" took 20 461ms.
                         [  +12 ms] 
                                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
                                    #1      AssembleCommand.runCommand
(package:flutter_tools/src/commands/assemble.dart:238:7)
                                    #2      _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #5      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                                    #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                                    #10     FlutterBuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart)
                                    #11     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #14     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                                    #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                                    #19     _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart)
                                    #20     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #23     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #26     Future.wait.<anonymous closure> (dart:async/future.dart:410:22)
                                    #27     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #30     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                                    #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                                    #35     _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart)
                                    #36     _asyncErrorWrapperHelper.errorCallback
(dart:async-patch/async_patch.dart:91:64)
                                    #37     _rootRunBinary (dart:async/zone.dart:1214:47)
                                    #38     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
                                    #39     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
                                    #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
                                    #41     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
                                    #42     Future._completeError (dart:async/future_impl.dart:537:5)
                                    #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
                                    #44     KernelSnapshot.build
(package:flutter_tools/src/build_system/targets/common.dart)
                                    #45     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #46     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #47     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #48     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #49     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #50     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                                    #52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                                    #53     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
                                    #54     _rootRunUnary (dart:async/zone.dart:1198:47)
                                    #55     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                                    #56     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                                    #57     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:696:45)
                                    #58     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                                    #59     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                                    #60     Future._asyncCompleteWithValue.<anonymous closure>
(dart:async/future_impl.dart:567:7)
                                    #61     _rootRun (dart:async/zone.dart:1190:13)
                                    #62     _CustomZone.run (dart:async/zone.dart:1093:19)
                                    #63     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
                                    #64     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:1037:23)
                                    #65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
                                    #66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
                                    #67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
                                    #68     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)
                     
                     
                         [   +5 ms] ensureAnalyticsSent: 3ms
                         [   +8 ms] Running shutdown hooks
                         [   +8 ms] Shutdown hooks complete
                         [   +2 ms] exiting with code 1
                         Command PhaseScriptExecution failed with a nonzero exit code
                     
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'Firebase' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'Flutter' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'firebase_auth' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'cloud_functions' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'cloud_firestore' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'SDWebImageWebPCoder' from project
'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'SDWebImage' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'gRPC-Core' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'gRPC-C++' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'abseil' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'Runner' from project 'Runner')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'Protobuf' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'PromisesObjC' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'Pods-Runner' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'Mantle' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'GoogleUtilities' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'GoogleDataTransport' from project
'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'GTMSessionFetcher' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseStorage' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseMessaging' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseInstanceID' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseInstallations' from project
'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseFunctions' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseFirestore' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCoreDiagnostics' from project
'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCore' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseAuth' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'FMDB' from project 'Pods')
                         warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the
range of supported
                         deployment target versions is 9.0 to 14.0.99. (in target 'BoringSSL-GRPC' from project 'Pods')
                     
[+323809 ms] Could not build the application for the simulator.
[  +56 ms] Error launching application on iPhone 11.
[  +22 ms] "flutter run" took 1 639 451ms.
[ +175 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
                    #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
                    <asynchronous suspension>
                    #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:860:18)
                    #3      _rootRunUnary (dart:async/zone.dart:1198:47)
                    #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
                    #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
                    #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
                    #12     _rootRunUnary (dart:async/zone.dart:1198:47)
                    #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
                    #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
                    #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
                    #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
                    #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
                    #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
                    #19     _rootRun (dart:async/zone.dart:1190:13)
                    #20     _CustomZone.run (dart:async/zone.dart:1093:19)
                    #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
                    #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
                    #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
                    #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
                    #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
                    #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
                    
                    
[ +404 ms] ensureAnalyticsSent: 254ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +38 ms] Shutdown hooks complete
[        ] exiting with code 1```

**Comment by darshankawar** [comment]
@guit4eva 
Please provide `flutter doctor -v`, `pubspec.yaml` and a complete minimal reproducible code sample that we can use to replicate this issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
