### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by catmaomao** [flutter/flutter#73696]
<details>
<summary>logs</summary>

```bash
I/flutter (24579): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (24579): The following assertion was thrown during paint():
I/flutter (24579): Rect argument contained a NaN value.
I/flutter (24579): 'dart:ui/painting.dart':
I/flutter (24579): Failed assertion: line 31: '<optimized out>'
I/flutter (24579): 
I/flutter (24579): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24579): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24579): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24579):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24579): 
I/flutter (24579): The relevant error-causing widget was:
I/flutter (24579):   TextField file:///Users/mamark/connec/connect-flutter/lib/ui/login_with_password.dart:91:22
I/flutter (24579): 
I/flutter (24579): When the exception was thrown, this was the stack:
I/flutter (24579): #2      _rectIsValid (dart:ui/painting.dart:31:10)
I/flutter (24579): #3      Canvas.drawRect (dart:ui/painting.dart:3727:12)
I/flutter (24579): #4      RenderEditable._paintCaret (package:flutter/src/rendering/editable.dart:2039:14)
I/flutter (24579): #5      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:2224:7)
I/flutter (24579): #6      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2267:7)
I/flutter (24579): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (24579): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (24579): #9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (24579): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (24579): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (24579): #12     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (24579): #13     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
I/flutter (24579): #14     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4861:13)
I/flutter (24579): #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (24579): #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (24579): #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (24579): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (24579): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (24579): #20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (24579): #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (24579): #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (24579): #23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (24579): #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (24579): #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (24579): #26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (24579): #27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (24579): #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (24579): #29     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
I/flutter (24579): #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (24579): #31     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
I/flutter (24579): #32     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
I/flutter (24579): #33     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
I/flutter (24579): #34     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:438:19)
I/flutter (24579): #35     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
I/flutter (24579): #36     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (24579): #37     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (24579): #38     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (24579): #39     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (24579): #43     _invoke (dart:ui/hooks.dart:251:10)
I/flutter (24579): #44     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (24579): (elided 5 frames from class _AssertionError and dart:async)
I/flutter (24579): 
I/flutter (24579): The following RenderObject was being processed when the exception was fired: RenderEditable#cb862 relayoutBoundary=up20:
I/flutter (24579):   creator: _Editable-[GlobalKey#d85f8] ← Semantics ← CompositedTransformTarget ←
I/flutter (24579):     IgnorePointer-[GlobalKey#1323a] ← Semantics ← _PointerListener ← Listener ←
I/flutter (24579):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e3a23] ← _PointerListener ← Listener
I/flutter (24579):     ← _ScrollableScope ← RepaintBoundary ← ⋯
I/flutter (24579):   parentData: <none> (can use size)
I/flutter (24579):   constraints: BoxConstraints(w=280.4, 0.0<=h<=46.0)
I/flutter (24579):   size: Size(280.4, 19.0)
I/flutter (24579):   cursorColor: Color(0xff4285f4)
I/flutter (24579):   showCursor: ValueNotifier<bool>#3c129(true)
I/flutter (24579):   maxLines: 1
I/flutter (24579):   minLines: null
I/flutter (24579):   selectionColor: Color(0xff90caf9)
I/flutter (24579):   textScaleFactor: 1.0
I/flutter (24579):   locale: en_US
I/flutter (24579):   selection: TextSelection(baseOffset: 6, extentOffset: 6, affinity: TextAffinity.downstream,
I/flutter (24579):     isDirectional: false)
I/flutter (24579):   offset: ScrollPositionWithSingleContext#79b29(offset: 0.0, range: 0.0..0.0, viewport: 280.4,
I/flutter (24579):     ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#699a8,
I/flutter (24579):     ScrollDirection.idle)
I/flutter (24579): This RenderObject had the following child:
```
</details>

**Comment by pedromassangocode** [comment]
Hi @catmaomao 

> I/flutter (24579): Rect argument contained a NaN value.

It seems you provided an invalid value in Rect. Can you provide a reproducible code sample and your `flutter doctor -v`?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
