### ISSUE TITLE
Hot restart using named routes breaks browser back button

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#73793]
This is similar to https://github.com/flutter/flutter/issues/73792, but also displays the error in #70299

## Steps to Reproduce

1. Run an app using named routes ([example](https://github.com/flutter/samples/blob/master/navigation_and_routing/lib/nav_1/named_routes.dart))
2. Press the "view details" button to invoke a Navigator.push()
3. Invoke a hot restart
4. Press the back button
5. See error below:

```
_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:55697/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:55697/dart_sdk.js:5232:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:55697/dart_sdk.js:147135:59)
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:239:12
_isOriginEntry(state)
is not true
    at Object.throw_ [as throw] (http://localhost:55697/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:55697/dart_sdk.js:5232:15)
    at _engine.SingleEntryBrowserHistory.new.[_unwrapOriginState] (http://localhost:55697/dart_sdk.js:147111:57)
    at _engine.SingleEntryBrowserHistory.new.tearDown (http://localhost:55697/dart_sdk.js:147171:79)
    at tearDown.next (<anonymous>)
    at http://localhost:55697/dart_sdk.js:38561:33
    at _RootZone.runUnary (http://localhost:55697/dart_sdk.js:38418:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:55697/dart_sdk.js:33395:29)
    at handleValueCallback (http://localhost:55697/dart_sdk.js:33955:49)
    at Function._propagateToListeners (http://localhost:55697/dart_sdk.js:33993:17)
    at _Future.new.[_completeWithValue] (http://localhost:55697/dart_sdk.js:33835:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55697/dart_sdk.js:33858:35)
    at Object._microtaskLoop (http://localhost:55697/dart_sdk.js:38676:13)
    at _startMicrotaskLoop (http://localhost:55697/dart_sdk.js:38682:13)
    at http://localhost:55697/dart_sdk.js:34209:9
```

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.251, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.251 at /Users/ryjohn/code/github/flutter/flutter
    • Framework revision 5bc725bea8 (4 days ago), 2021-01-08 08:12:36 +0100
    • Engine revision 2e5833b7c5
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/ryjohn/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8346

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.

```
</details>

**Comment by darshankawar** [comment]
<details>
<summary>Error log</summary>

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14
_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:53300/dart_sdk.js:5304:11)
    at Object.assertFailed (http://localhost:53300/dart_sdk.js:5240:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:53300/dart_sdk.js:147599:59)
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14
_userProvidedRouteName != null
is not true
    at Object.throw_ [as throw] (http://localhost:53300/dart_sdk.js:5304:11)
    at Object.assertFailed (http://localhost:53300/dart_sdk.js:5240:15)
    at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:53300/dart_sdk.js:147599:59)
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:239:12
_isOriginEntry(state)
is not true
    at Object.throw_ [as throw] (http://localhost:53300/dart_sdk.js:5304:11)
    at Object.assertFailed (http://localhost:53300/dart_sdk.js:5240:15)
    at _engine.SingleEntryBrowserHistory.new.[_unwrapOriginState] (http://localhost:53300/dart_sdk.js:147575:57)
    at _engine.SingleEntryBrowserHistory.new.tearDown (http://localhost:53300/dart_sdk.js:147635:79)
    at tearDown.next (<anonymous>)
    at http://localhost:53300/dart_sdk.js:38979:33
    at _RootZone.runUnary (http://localhost:53300/dart_sdk.js:38836:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:53300/dart_sdk.js:33777:29)
    at handleValueCallback (http://localhost:53300/dart_sdk.js:34337:49)
    at Function._propagateToListeners (http://localhost:53300/dart_sdk.js:34375:17)
    at _Future.new.[_completeWithValue] (http://localhost:53300/dart_sdk.js:34217:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53300/dart_sdk.js:34240:35)
    at Object._microtaskLoop (http://localhost:53300/dart_sdk.js:39094:13)
    at _startMicrotaskLoop (http://localhost:53300/dart_sdk.js:39100:13)
    at http://localhost:53300/dart_sdk.js:34591:9

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.312, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.312 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7c75c01fc3 (3 hours ago), 2021-01-12 19:01:18 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Deepti 's iPhone (mobile) • 0554e90e563e81fd41bfd2ff9a2c6960595b9825 • ios
      • iOS 12.4.9
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 87.0.4280.141
    ! Error: Deepti 's iPhone is busy: Copying cache files from device. Xcode
      will continue when Deepti 's iPhone is finished. (code -10)

! Doctor found issues in 1 category.


```

</details>

**Comment by chunhtai** [comment]
<details>
<summary> code </summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: <String, WidgetBuilder>{
        '/': (_) => FirstPage(),
        '/d': (_) => SecondPage(),
      }
    );
  }
}

class FirstPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(body:Center(
      child: RaisedButton(onPressed: () => Navigator.of(context).pushNamed('/d')),
    ));
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(body:Center(
      child: Text('second page'),
    ));
  }
}
```

</details>

**Comment by nashihu** [comment]
hello @chunhtai , can you plase check for second page using arguments? it's causing same error when pressing back button _after doing hot restart._ 

this is the code:
<details close>
<summary>Code</summary>

```import 'package:flutter/material.dart';

 void main() => runApp(App());

 class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: <String, WidgetBuilder>{
        '/': (_) => FirstPage(),
        '/d': (_) => SecondPage(),
      }
    );
  }
 }

 class FirstPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(body:Center(
      child: RaisedButton(onPressed: () => Navigator.of(context).pushNamed('/d', arguments: {"value": 1000})),
    ));
  }
 }

 class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(body:Center(
      child: Text('second page'),
    ));
  }
 }
```
</details>

thanks..

**Comment by sofienbradai2019** [comment]
me too I have the same BUG

**Comment by chunhtai** [comment]
hi @nashihu @sofienbradai2019, sorry this had gone under my radar. Can you create a new issue for the crash you are seeing, The original issue has been fix, it is likely a different cause

**Comment by nashihu** [comment]
okay @chunhtai i have created the issue at #82237
