### ISSUE TITLE
Hot restart using anonymous routes breaks browser back button 

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#73792]
Invoking a hot restart breaks browser back button functionality for apps using anonymous routes.

This is related to https://github.com/flutter/flutter/issues/73793 and might be related to https://github.com/flutter/flutter/issues/70299
## Steps to Reproduce

1. Run an app using anonymous routes ([example](https://github.com/flutter/samples/blob/master/navigation_and_routing/lib/nav_1/anonymous_routes.dart))
2. Press the "view details" button to invoke a `Navigator.push()`
3. Invoke a hot restart
4. Press the back button
5. See error below:

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:239:12
_isOriginEntry(state)
is not true
    at Object.throw_ [as throw] (http://localhost:53091/dart_sdk.js:5296:11)
    at Object.assertFailed (http://localhost:53091/dart_sdk.js:5232:15)
    at _engine.SingleEntryBrowserHistory.new.[_unwrapOriginState] (http://localhost:53091/dart_sdk.js:147111:57)
    at _engine.SingleEntryBrowserHistory.new.tearDown (http://localhost:53091/dart_sdk.js:147171:79)
    at tearDown.next (<anonymous>)
    at http://localhost:53091/dart_sdk.js:38561:33
    at _RootZone.runUnary (http://localhost:53091/dart_sdk.js:38418:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:53091/dart_sdk.js:33395:29)
    at handleValueCallback (http://localhost:53091/dart_sdk.js:33955:49)
    at Function._propagateToListeners (http://localhost:53091/dart_sdk.js:33993:17)
    at _Future.new.[_completeWithValue] (http://localhost:53091/dart_sdk.js:33835:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53091/dart_sdk.js:33858:35)
    at Object._microtaskLoop (http://localhost:53091/dart_sdk.js:38676:13)
    at _startMicrotaskLoop (http://localhost:53091/dart_sdk.js:38682:13)
    at http://localhost:53091/dart_sdk.js:34209:9
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.251, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.251 at /Users/ryjohn/code/github/flutter/flutter
    • Framework revision 5bc725bea8 (4 days ago), 2021-01-08 08:12:36 +0100
    • Engine revision 2e5833b7c5
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/ryjohn/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.3
    • Dart plugin version 202.8346

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.

```

</details>

**Comment by pedromassangocode** [comment]
<details>
<summary>logs</summary>

```bash
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:239:12
            _isOriginEntry(state)
            is not true
                at Object.throw_ [as throw] (http://localhost:61163/dart_sdk.js:5306:11)
                at Object.assertFailed (http://localhost:61163/dart_sdk.js:5242:15)
                at _engine.SingleEntryBrowserHistory.new.[_unwrapOriginState] (http://localhost:61163/dart_sdk.js:147586:57)
                at _engine.SingleEntryBrowserHistory.new.tearDown (http://localhost:61163/dart_sdk.js:147646:79)
                at tearDown.next (<anonymous>)
                at http://localhost:61163/dart_sdk.js:38980:33
                at _RootZone.runUnary (http://localhost:61163/dart_sdk.js:38837:58)
                at _FutureListener.thenAwait.handleValue (http://localhost:61163/dart_sdk.js:33778:29)
                at handleValueCallback (http://localhost:61163/dart_sdk.js:34338:49)
                at Function._propagateToListeners (http://localhost:61163/dart_sdk.js:34376:17)
                at _Future.new.[_completeWithValue] (http://localhost:61163/dart_sdk.js:34218:23)
                at async._AsyncCallbackEntry.new.callback (http://localhost:61163/dart_sdk.js:34241:35)
                at Object._microtaskLoop (http://localhost:61163/dart_sdk.js:39095:13)
                at _startMicrotaskLoop (http://localhost:61163/dart_sdk.js:39101:13)
                at http://localhost:61163/dart_sdk.js:34592:9
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.334, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.334 at /Users/pedromassango/Code/flutter_master
    • Framework revision 333dc5d88a (5 hours ago), 2021-01-14 06:56:54 +0100
    • Engine revision 1b5e16cda2
    • Dart version 2.12.0 (build 2.12.0-223.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by exaby73** [comment]
@johnpryan Hello. The example link you provided seems to not be working anymore. Could you either provide a working minimal sample that reproduces the issue or confirm if it's been fixed?

**Comment by darshankawar** [comment]
Verified this issue by using anonymous routes code sample from https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade. Followed steps to replicate using latest master version and observed that the reported error doesn't occur.


https://user-images.githubusercontent.com/67046386/223400659-2b7315af-348a-43b6-a07c-fb6eced83221.mov


<details>
<summary> anonymous routes runnable code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(Nav2App());
}

class Nav2App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: ElevatedButton(
          child: Text('View Details'),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) {
                return DetailScreen();
              }),
            );
          },
        ),
      ),
    );
  }
}

class DetailScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: ElevatedButton(
          child: Text('Pop!'),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
    );
  }
}


```

</details>

I am going ahead and optimistically closing this as fixed in latest versions.

`Channel master, 3.9.0-1.0.pre.72`
