### ISSUE TITLE
UnsupportedError: Unsupported operation: Illegal character in path: assets\google_fonts

### ISSUE THREAD

**Issue by LebToki** [flutter/flutter#73837]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --quiet assemble --depfile D:\__Projects\__Mobile\ecommerce\build\app\intermediates\flutter\debug/flutter_build.d --output D:\__Projects\__Mobile\ecommerce\build\app\intermediates\flutter\debug -dTargetFile=D:\__Projects\__Mobile\ecommerce\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=flutter.inspector.structuredErrors%3Dtrue debug_android_application

## exception

UnsupportedError: Unsupported operation: Illegal character in path: assets\google_fonts

```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1734:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2748:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2720:38)
#3      _parseAssetsFromFolder (package:flutter_tools/src/asset.dart:749:27)
#4      _parseAssets (package:flutter_tools/src/asset.dart:689:7)
#5      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:163:53)
<asynchronous suspension>
#6      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:48:44)
#7      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:65:42)
#8      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
<asynchronous suspension>
#9      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:744:35)
#10     new Future.sync (dart:async/future.dart:223:31)
#11     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:744:21)
<asynchronous suspension>
#13     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:566:36)
#14     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#17     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _runZoned (dart:async/zone.dart:1630:10)
#22     runZoned (dart:async/zone.dart:1550:10)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#24     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#25     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#26     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#29     _rootRun (dart:async/zone.dart:1190:13)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _runZoned (dart:async/zone.dart:1630:10)
#32     runZoned (dart:async/zone.dart:1550:10)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#34     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:281:19)
<asynchronous suspension>
#35     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#36     new Future.sync (dart:async/future.dart:223:31)
#37     CommandRunner.run (package:args/command_runner.dart:112:14)
#38     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:230:18)
#39     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#40     _rootRun (dart:async/zone.dart:1190:13)
#41     _CustomZone.run (dart:async/zone.dart:1093:19)
#42     _runZoned (dart:async/zone.dart:1630:10)
#43     runZonedGuarded (dart:async/zone.dart:1618:12)
#44     runZoned (dart:async/zone.dart:1547:12)
#45     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#46     run.<anonymous closure> (package:flutter_tools/runner.dart)
#47     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:67:18)
<asynchronous suspension>
#48     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#49     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#50     _rootRun (dart:async/zone.dart:1190:13)
#51     _CustomZone.run (dart:async/zone.dart:1093:19)
#52     _runZoned (dart:async/zone.dart:1630:10)
#53     runZoned (dart:async/zone.dart:1550:10)
#54     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#55     runInContext (package:flutter_tools/src/context_runner.dart:70:24)
#56     run (package:flutter_tools/runner.dart:46:10)
#57     main (package:flutter_tools/executable.dart:77:9)
#58     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#59     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.5 at D:\flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\tarek\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\tarek\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
@LebToki  can you include the pubspec.yaml for the project that crashed this way?

**Comment by LebToki** [comment]
sorry for deleting the project and starting afresh with a standard font waiting for a resolution to switch :-)
