### ISSUE TITLE
[camera 0.6.4+5] [plugin] [crash] during taking photo

### ISSUE THREAD

**Issue by antoninobajeli** [flutter/flutter#73856]
## Steps to Reproduce
- init the camera plugin on Huawai p10 lite ( WAS LX1A (mobile) • H3XDU17930023946 • android-arm64  • Android 8.0.0 (API 26))
- taking the foto te app crash
This is the log

```bash
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
V/AudioManager(30773): playSoundEffect   effectType: 0
W/GrallocMapperPassthrough(30773): buffer descriptor with invalid usage bits 0x2080000
I/flutter (30773): CameraException(captureFailure, An error happened in the framework)
D/AndroidRuntime(30773): Shutting down VM
E/AndroidRuntime(30773): FATAL EXCEPTION: main
E/AndroidRuntime(30773): Process: com.bajeli.flutter.grani_antichi, PID: 30773
E/AndroidRuntime(30773): java.lang.IllegalStateException: Request has already been finished
E/AndroidRuntime(30773): 	at io.flutter.plugins.camera.PictureCaptureRequest.finish(PictureCaptureRequest.java:40)
E/AndroidRuntime(30773): 	at io.flutter.plugins.camera.Camera.lambda$takePicture$0$Camera(Camera.java:402)
E/AndroidRuntime(30773): 	at io.flutter.plugins.camera.-$$Lambda$Camera$kpdf-S9lnD9lSxBgWhomOdHv80s.onImageAvailable(Unknown Source:4)
E/AndroidRuntime(30773): 	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
E/AndroidRuntime(30773): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(30773): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(30773): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/AndroidRuntime(30773): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30773): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(30773): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
I/Process (30773): Sending signal. PID: 30773 SIG: 9
Lost connection to device.
```

<details>
<summary>flutter doctor -v</summary>

```bash
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Versione 10.0.19041.685], locale it-IT)
    • Flutter version 1.25.0-8.2.pre at C:\flutter
    • Framework revision b0a2299859 (8 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\abajeli\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\abajeli\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (4 available)
    • Nokia 9 (mobile)  • AOPGA1I911400377 • android-arm64  • Android 10 (API 29)
    • WAS LX1A (mobile) • H3XDU17930023946 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.66
```
</details>

**Comment by TahaTesser** [comment]
Hi @antoninobajeli 
```bash
E/AndroidRuntime(30773): Process: com.bajeli.flutter.grani_antichi, PID: 30773
E/AndroidRuntime(30773): java.lang.IllegalStateException: Request has already been finished
E/AndroidRuntime(30773): 	at io.flutter.plugins.camera.PictureCaptureRequest.finish(PictureCaptureRequest.java:40)
```
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/73336
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
