### ISSUE TITLE
[web] TypeError: Instance of 'FlexParentData': type 'FlexParentData' is not a subtype of type 'StackParentData'

### ISSUE THREAD

**Issue by ziyadalrasbi** [flutter/flutter#73866]
I am currently trying to deploy my app for web hosting using firebase. When running the app in localhost, it runs perfectly with no errors and it has a stable connection to the firebase database for signing up/ logging in users.

I am now trying to deploy it for web hosting. However, after setting it up and deploying it and going on the link, it just displays a completely blank page when it should display the app. The error is shown in the console. I am confused as to why it's not working, even though it works perfectly fine in localhost.
## Steps to Reproduce

1. Run `firebase deploy`.
2. Click the hosting link.
3. Now, the screen is shown as blank even after following all the steps in `firebase init` and setting it up correctly.

**Expected results:** 
The page is expected to run correctly through web hosting just as it does in localhost.
**Actual results:** 
Instead, a blank page is shown, with an error. Please refer to code section below for it.

<details>
  <summary>Code</summary>
The error log:

```
DevTools failed to load SourceMap: Could not load content for chrome-extension://pgjjikdiikihdfpoppgaidccahalehjh/webspeed.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
js_primitives.dart:47 TypeError: Instance of 'FlexParentData': type 'FlexParentData' is not a subtype of type 'StackParentData'
js_primitives.dart:47     at Object.wrapException (https://social-io-102b4.firebaseapp.com/main.dart.js:5787:17)
js_primitives.dart:47     at Object._failedAsCheck (https://social-io-102b4.firebaseapp.com/main.dart.js:7136:15)
js_primitives.dart:47     at Rti._generalNullableAsCheckImplementation [as _as] (https://social-io-102b4.firebaseapp.com/main.dart.js:7133:9)
js_primitives.dart:47     at Positioned.applyParentData$1 (https://social-io-102b4.firebaseapp.com/main.dart.js:90741:29)
js_primitives.dart:47     at SingleChildRenderObjectElement.attachRenderObject$1 (https://social-io-102b4.firebaseapp.com/main.dart.js:96272:127)
js_primitives.dart:47     at SingleChildRenderObjectElement.mount$2 (https://social-io-102b4.firebaseapp.com/main.dart.js:96114:13)
js_primitives.dart:47     at SingleChildRenderObjectElement.mount$2 (https://social-io-102b4.firebaseapp.com/main.dart.js:96332:13)
js_primitives.dart:47     at StatefulElement.inflateWidget$2 (https://social-io-102b4.firebaseapp.com/main.dart.js:95585:16)
js_primitives.dart:47     at StatefulElement.updateChild$3 (https://social-io-102b4.firebaseapp.com/main.dart.js:95506:26)
js_primitives.dart:47     at StatefulElement.performRebuild$0 (https://social-io-102b4.firebaseapp.com/main.dart.js:95840:41)
js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'

```
I have attached my `main.dart` code, as I think this is where the issue could be:

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:login_page/form_authentication.dart';
import 'package:login_page/pages/home/home_page.dart';
import 'package:login_page/constants.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:login_page/pages/login/login_screen.dart';
import 'package:login_page/pages/signup/sign_up_first.dart';
import 'package:provider/provider.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<AuthService>(
          create: (_) => AuthService(FirebaseAuth.instance),
        ),
        StreamProvider(
          create: (context) => context.read<AuthService>().authStateChanges,
        )
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Home Page',
        theme: ThemeData(
          primaryColor: primaryLightColour,
          scaffoldBackgroundColor: Colors.white,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: AuthWrapper(),
      ),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final firebaseuser = context.watch<User>();
    
    Future.delayed(Duration.zero, () {
    if (firebaseuser != null) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) {
            return SignUpFirst();
          }
        ),
      );
    } 
    });
  return HomePage();
  }
}

```

**Comment by TahaTesser** [comment]
Hi @ziyadalrasbi 
Does it reproduce when using flutterfire in your project? 
Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample? without using third-party packages
Thank you

**Comment by ziyadalrasbi** [comment]
> Hi @ziyadalrasbi
> Does it reproduce it without using third-party packages?
> Can you please provide your `flutter doctor -v` and a complete reproducible minimal code sample? without using third-party packages
> Thank you

Thanks for your reply,

I managed to fix it myself. It was just a small issue in my code which is fixed now.

Thanks!

**Comment by tharindu-nw** [comment]
Hi @ziyadalrasbi I am getting the same error in my app. Could you please let me know what the issue was in your code and how you fixed it.

**Comment by michael-timi** [comment]
hi @ziyadalrasbi kindly provide how you are able to figure it out, I'm facing the same issue here
@tharindu-nw have you been able to fix yours? if yes kindly assist me with the solution
