### ISSUE TITLE
flutter_immediately_exit_test fails, Expected: contains 'Error connecting to the service protocol:', Actual: 'Unhandled exception: SocketException'

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#73915]
First seen on https://github.com/flutter/flutter/commit/392c237daddb070f84cc7c3f18f8d4aed0afa2cd
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858169488377725536/+/steps/run_test.dart_for_tool_tests_shard_and_subshard_integration/0/stdout
```
16:39 +36 ~2 -1: test\integration.shard\flutter_immediately_exit_test.dart: flutter_tools gracefully handles quick app shutdown [E]                                                                    
  Expected: contains 'Error connecting to the service protocol:'
    Actual: 'Unhandled exception:\n'
              'SocketException: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.\n'
              ', errno = 10048), address = 127.0.0.1, port = 9109\n'
              '#0      serveDevTools (package:devtools_server/src/server.dart:199:5)\n'
              '<asynchronous suspension>\n'
              '#1      serveDevToolsWithArgs (package:devtools_server/src/server.dart:72:10)\n'
              '<asynchronous suspension>\n'
              'Failed to launch DevTools: TimeoutException after 0:00:10.000000: Future not completed\n'
              '\n'
              ''
  
  package:test_api                                                expect
  test\integration.shard\flutter_immediately_exit_test.dart 32:7  main.<fn>
  
Failed to delete C:\b\s\w\ir\tmp\t\flutter_run_test.fb59021a: FileSystemException: Deletion failed, path = 'C:\b\s\w\ir\tmp\t\flutter_run_test.fb59021a' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)
```

**Comment by jmagman** [comment]
Passed on re-run.

**Comment by jmagman** [comment]
Forward duping to https://github.com/flutter/flutter/issues/74052, more context there.
