### ISSUE TITLE
change 'app' to ${project.archivesBaseName}

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#73919]
https://github.com/flutter/flutter/blob/e0dcb787dc13014faddc296345ae003385a80dc9/packages/flutter_tools/lib/src/android/gradle.dart#L905

[android-gradle-build-renaming-the-apk](https://stackoverflow.com/questions/16787493/android-gradle-build-renaming-the-apk)

**Comment by pedromassangocode** [comment]
Hi @v7lin 
Can you please elaborate the motivation of this proposal?
Why this is important?
Thank you

**Comment by v7lin** [comment]
> Hi @v7lin
> Can you please elaborate the motivation of this proposal?
> Why this is important?
> Thank you

it is not important. but it is useful.

**Comment by pedromassangocode** [comment]
It is important to know why a  change should be made, considering that this may be a breaking change.
Ca you elaborate why this is useful?

**Comment by v7lin** [comment]
> It is important to know why a change should be made.
> Ca you elaborate why this is useful?

the ${project.archivesBaseName} default value is 'app', it will not cause break change.

**Comment by jmagman** [comment]
I think this is a request to build the APK to known location based on app name instead of hardcoding "app-" prefix?  The referenced referenced is in dart, `project.archivesBaseName` is a Gradle property.

See also https://github.com/flutter/flutter/pull/54328

**Comment by PerLycke** [comment]
@jmagman I think he wants to be able to rename the apk / bundle without getting errors.

For example if you perform

`flutter build appbundle`

with the following defaultConfig:

```
defaultConfig {
    applicationId "some.app"
    minSdkVersion 24
    targetSdkVersion 30
    versionCode flutterVersionCode.toInteger()
    versionName flutterVersionName
    **archivesBaseName = "app-${builtType}-${versionName}-${versionCode}.apk"**
}
```

It will eventually throw the following error stating an unsupported Android Plugin:

> [   +4 ms] Unsupported Android Plugin version: 7.0.0.
> [   +1 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            #1      getGradleVersionFor (package:flutter_tools/src/android/gradle_utils.dart:181:3)
>            #2      getGradleVersionForAndroidPlugin (package:flutter_tools/src/android/gradle_utils.dart:124:10)
>            #3      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:1031:3)
>            #4      findBundleFile (package:flutter_tools/src/android/gradle.dart:1011:3)
>            #5      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:516:31)

**Comment by mboetger** [comment]
Closing this one as a duplicate of 159044 as that issue is a more general - but both are asking for archiveBaseName support.
