### ISSUE TITLE
Downloading packages fails although the URL is reachable via curl

### ISSUE THREAD

**Issue by timozander** [flutter/flutter#73928]
## Steps to Reproduce

I am behind corporate proxy and configured everything according to the docs and provided our root certificate via `DART_VM_OPTIONS`. Thus, the first steps of the flutter installation worked.

However, when it comes to downloading packages, dart fails to reach Google`s servers. I double checked my configuration but I can easily reach the given address - either via browser or curl (see below).

I downloaded the first packages manually by reproducing the CLI behaviour with Flutter's source code to manually create the stamp files. However, this is no realistic way of working.

I am located in Europe, so it's probably not connected to my ISP as other issues were. 

When I remove my configured proxy, the package download takes significantly longer and has a timeout. So, I am not sure how exactly this error is caused

## Logs

<details>
<summary>Logs</summary>

```
$ flutter doctor -v
Downloading package sky_engine...                                   0,3s
Downloading package sky_engine...                                   0,1s
Failed to download https://storage.googleapis.com/flutter_infra/flutter/ae90085a8437c0ae94d6b5ad2741739ebc742cb4/sky_engine.zip. Ensure you have network connectivity and then try again.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1486:11)
<asynchronous suspension>
#2      ArtifactUpdater.downloadZipArchive (package:flutter_tools/src/cache.dart:1442:12)
#3      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:707:29)
#4      CachedArtifact.update (package:flutter_tools/src/cache.dart:573:11)
#5      Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:928:27)
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#10     _rootRun (dart:async/zone.dart:1190:13)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _runZoned (dart:async/zone.dart:1630:10)
#13     runZoned (dart:async/zone.dart:1550:10)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _runZoned (dart:async/zone.dart:1630:10)
#23     runZoned (dart:async/zone.dart:1550:10)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:281:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:223:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:230:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#31     _rootRun (dart:async/zone.dart:1190:13)
#32     _CustomZone.run (dart:async/zone.dart:1093:19)
#33     _runZoned (dart:async/zone.dart:1630:10)
#34     runZonedGuarded (dart:async/zone.dart:1618:12)
#35     runZoned (dart:async/zone.dart:1547:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     run.<anonymous closure> (package:flutter_tools/runner.dart)
#38     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:67:18)
<asynchronous suspension>
#39     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#41     _rootRun (dart:async/zone.dart:1190:13)
#42     _CustomZone.run (dart:async/zone.dart:1093:19)
#43     _runZoned (dart:async/zone.dart:1630:10)
#44     runZoned (dart:async/zone.dart:1550:10)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#46     runInContext (package:flutter_tools/src/context_runner.dart:70:24)
#47     run (package:flutter_tools/runner.dart:46:10)
#48     main (package:flutter_tools/executable.dart:77:9)
#49     main (file:///C:/Gothaer/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


$ curl -I https://storage.googleapis.com/flutter_infra/flutter/ae90085a8437c0ae94d6b5ad2741739ebc742cb4/sky_engine.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 1153k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
X-GUploader-UploadID: ABg5-UzEG4PDg8RcjLytCuKDzARTyUnU-81SS7NF2VrMwKf9sjcbg25S16aMR3bC8CXFPeAQaCigQl1018XRyCJATL0
Expires: Thu, 14 Jan 2021 08:33:39 GMT
Date: Thu, 14 Jan 2021 07:33:39 GMT
Last-Modified: Thu, 10 Dec 2020 01:34:24 GMT
ETag: "a1fea3a63d49edb53842fd3f2250de61"
x-goog-generation: 1607564064054176
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 1181062
Content-Type: application/zip
x-goog-hash: crc32c=ZJHhoA==
x-goog-hash: md5=of6jpj1J7bU4Qv0/IlDeYQ==
x-goog-storage-class: STANDARD
Accept-Ranges: bytes
Content-Length: 1181062
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type
Server: UploadServer
Age: 982
Cache-Control: public, max-age=3600
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
```

</details>

**Comment by darshankawar** [comment]
@timozander 
Are you able to switch between Flutter channels ? Can you try to disable antivirus / firewall and check if it helps ?
Also if you haven't done so already, Add flutter SDK path and project path to whitelist.

**Comment by timozander** [comment]
Does not working on `beta` or `dev` either. 
I'll try getting the firewall whitelist, however, this will take some time. Do you see any other possible workarrounds or error sources? I will report back

**Comment by darshankawar** [comment]
@timozander 
Not that I am aware of. You may possibly try to move Flutter SDK folder to another location or try to install a fresh copy of Flutter to see if it helps.
I see there's a related open issue for whitelisting Flutter SDK, https://github.com/flutter/flutter/issues/61997

**Comment by timozander** [comment]
The latest `dev` branch now gives me a more detailed error messaging, complaining about my self-signed certificate:

<details>
<summary>Logs</summary>

```
Downloading package sky_engine...                                  247ms
Downloading package sky_engine...                                  161ms
Failed to download https://storage.googleapis.com/flutter_infra/flutter/effb529ecec86cbcad2ced2a567cb14ab20b10d5/sky_engine.zip. Ensure you have network connectivity and then try again.
HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(../../third_party/boringssl/src/ssl/handshake.cc:354))

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1769:11)
<asynchronous suspension>
#2      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:913:7)
<asynchronous suspension>
#3      CachedArtifact.update (package:flutter_tools/src/cache.dart:692:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1108:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1008:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#18     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
</details>

I follow every posible solution mentioned here (https://github.com/dart-lang/sdk/issues/32131), except for the change in antivirus that is still work in progress. Is there any possibility to get even more detailed debug output in order to find possible solutions?

**Comment by darshankawar** [comment]
@timozander 
Looking at the error in the log:

`HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(../../third_party/boringssl/src/ssl/handshake.cc:354))`

I see there's a similar open issue that talks about it, https://github.com/flutter/flutter/issues/50699

Is there a way for you to allow / accept all certificates ? because since it looks like a self signed certificate, it may not work, because Dart doesn't allow self-signed certs.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
