### ISSUE TITLE
Sky shell doesn't build with openjdk javac 1.8.

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#74]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:26 GMT_
_Originally opened as https://github.com/flutter/engine/issues/31_

----

_From @ppiet on July 8, 2015 16:38_

The error I get is:

```
[193/2246] ACTION //sky/shell:java__compile_java__javac(//build/toolchain/android:arm)
FAILED: python ../../build/android/gyp/javac.py --depfile=gen/sky/shell/java__compile_java__javac.d --classpath=\[\"../../third_party/android_tools/sdk/platforms/android-22/android.jar\"\] --classpath=@FileArg\(gen/sky/shell/java.build_config:javac:classpath\) --jar-path=gen/sky/shell/java__compile_java.initial.jar --java-srcjars=\[\] --java-srcjars=@FileArg\(gen/sky/shell/java.build_config:javac:srcjars\) --jar-excluded-classes=\[\"\*/R.class\",\ \"\*/R\#\#\*.class\",\ \"\*/Manifest.class\",\ \"\*/Manifest\#\#\*.class\"\] --chromium-code=1 ../../sky/shell/android/org/domokit/sky/shell/GestureProvider.java ../../sky/shell/android/org/domokit/sky/shell/PlatformServiceProvider.java ../../sky/shell/android/org/domokit/sky/shell/PlatformViewAndroid.java ../../sky/shell/android/org/domokit/sky/shell/ResourceExtractor.java ../../sky/shell/android/org/domokit/sky/shell/ServiceFactory.java ../../sky/shell/android/org/domokit/sky/shell/ServiceRegistry.java ../../sky/shell/android/org/domokit/sky/shell/SkyActivity.java ../../sky/shell/android/org/domokit/sky/shell/SkyApplication.java ../../sky/shell/android/org/domokit/sky/shell/SkyMain.java ../../sky/shell/android/org/domokit/sky/shell/TracingController.java
Traceback (most recent call last):
  File "../../build/android/gyp/javac.py", line 280, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../build/android/gyp/javac.py", line 244, in main
    java_files)
  File "../../build/android/gyp/javac.py", line 104, in DoJavac
    input_strings=javac_cmd)
  File "/usr/local/work/mojo/src/build/android/gyp/util/md5_check.py", line 30, in CallAndRecordIfStale
    function()
  File "../../build/android/gyp/javac.py", line 97, in Compile
    stderr_filter=ColorJavacOutput)
  File "/usr/local/work/mojo/src/build/android/gyp/util/build_utils.py", line 158, in CheckOutput
    raise CalledProcessError(cwd, args, stdout + stderr)
util.build_utils.CalledProcessError: Command failed: ( cd /usr/local/work/mojo/src/out/android_Debug; javac -g -encoding UTF-8 -source 1.7 -target 1.7 -classpath ../../third_party/android_tools/sdk/platforms/android-22/android.jar:gen/base/base_java.jar:gen/mojo/android/system_java.jar:gen/mojo/public/interfaces/application/application_java.jar:gen/mojo/public/java/bindings.jar:gen/mojo/public/java/system.jar:gen/mojo/services/network/public/interfaces/interfaces_java.jar:gen/services/keyboard/keyboard.jar:gen/sky/services/engine/engine_java.jar:gen/sky/services/oknet/oknet.jar:gen/sky/services/intents/intents_lib.jar -d /tmp/tmpZoxfmr/classes -Xlint:unchecked ../../sky/shell/android/org/domokit/sky/shell/GestureProvider.java ../../sky/shell/android/org/domokit/sky/shell/PlatformServiceProvider.java ../../sky/shell/android/org/domokit/sky/shell/PlatformViewAndroid.java ../../sky/shell/android/org/domokit/sky/shell/ResourceExtractor.java ../../sky/shell/android/org/domokit/sky/shell/ServiceFactory.java ../../sky/shell/android/org/domokit/sky/shell/ServiceRegistry.java ../../sky/shell/android/org/domokit/sky/shell/SkyActivity.java ../../sky/shell/android/org/domokit/sky/shell/SkyApplication.java ../../sky/shell/android/org/domokit/sky/shell/SkyMain.java ../../sky/shell/android/org/domokit/sky/shell/TracingController.java )
warning: [options] bootstrap class path not set in conjunction with -source 1.7
../../sky/shell/android/org/domokit/sky/shell/PlatformViewAndroid.java:97: error: cannot access KeyboardService
        KeyboardServiceImpl.setActiveView(this);
                           ^
  class file for org.chromium.mojom.keyboard.KeyboardService not found
../../sky/shell/android/org/domokit/sky/shell/SkyActivity.java:47: error: cannot access ActivityManager
        ActivityManagerImpl.setCurrentActivity(this);
                           ^
  class file for org.chromium.mojom.intents.ActivityManager not found
2 errors
1 warning
```

Setting the PATH to use openjdk javac 1.7 instead makes the error go away.

_Copied from original issue: domokit/mojo#308_

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:26 GMT_

----

_From @alhaad on July 8, 2015 16:40_

The error I got:

```
util.build_utils.CalledProcessError: Command failed: ( cd /work/mojo/src/out/android_Debug; ../../third_party/android_tools/sdk/build-tools/22.0.1/dx --dex --force-jumbo -
-output gen/base/base_java.dex.jar --no-locals gen/base/base_java.jar )
F0100 00:00:00.000000 20314 percpu.cc:126] RAW: Check *backing_ == 0 failed: percpu-allocator: object backing not allocated
    @     0x7f83b2223dde  base_raw_logging::RawLog()
    @     0x7f83b22209e7  GoogleOnceInternalInit()
    @     0x7f83b2240ced  base::subtle::percpu::StaticAllocHandle()
    @     0x7f83b213bff8  _GLOBAL__sub_I_percpu_types.cc
    @     0x7f83b2240fd6  (unknown)
    @     0x7f83b2134ac3  (unknown)
    @     0x7f83b3f6e35c  _dl_init
    @     0x7f83b3f73895  dl_open_worker
    @     0x7f83b3f6e095  _dl_catch_error
    @     0x7f83b3f72cae  _dl_open
    @     0x7f83b3b3911e  dlopen_doit
    @     0x7f83b3f6e095  _dl_catch_error
    @     0x7f83b3b3983a  _dlerror_run
    @     0x7f83b3b3922b  dlopen@@GLIBC_2.2.5
    @     0x7f83b2f5d4c3  os::dll_load()
    @     0x7f83b30aa095  lookup_on_load()
    @     0x7f83b30b1ea3  Threads::create_vm()
    @     0x7f83b2d0e9c4  JNI_CreateJavaVM
    @     0x7f83b4168a3a  JavaMain
    @     0x7f83b3d42800  start_thread
    @     0x7f83b37a22ed  clone
```
Updating PATH made the error go away.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:26 GMT_

----

_From @viettrungluu-cr on July 10, 2015 17:53_

But probably we should fix things so that it does build with 1.8.

Incidentally, monet currently doesn't build with 1.8 either, but for entirely different reasons (but it's easy enough to work around).

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 16, 2015 at 22:26 GMT_

----

_From @abarth on July 12, 2015 15:20_

Does this still not work?  I think I fixed the errors in the original description.  The one with GoogleOnceInternalInit in the stack trace is new for me.

**Comment by Hixie** [comment]
@ppiet is this still an issue for you?

**Comment by sethladd** [comment]
Going to close for now. Please let us know if we need to reopen.
