### ISSUE TITLE
[tool_crash] FileSystemException: FileSystemException: Creation of temporary directory failed

### ISSUE THREAD

**Issue by 39499740** [flutter/flutter#74042]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios

## exception

FileSystemException: FileSystemException: Creation of temporary directory failed, path = '/private/private/var/folders/vp/9ql29gzx1nl993vfpp8wjpxc0000gn/T/flutter_tools.' (OS Error: No such file or directory, errno = 2)

```
#0      _Directory.createTempSync (dart:io/directory_impl.dart:181:7)
#1      ForwardingDirectory.createTempSync (package:file/src/forwarding/forwarding_directory.dart:30:21)
#2      LocalFileSystem.systemTempDirectory (package:flutter_tools/src/base/file_system.dart:228:47)
#3      ForwardingFileSystem.systemTempDirectory (package:file/src/forwarding/forwarding_file_system.dart:35:49)
#4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:286:26)
<asynchronous suspension>
#5      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:105:43)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#14     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#23     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#32     IosProject.hostAppBundleName (package:flutter_tools/src/project.dart)
#33     _rootRunUnary (dart:async/zone.dart:1198:47)
#34     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#39     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#40     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#41     IosProject._parseHostAppBundleName (package:flutter_tools/src/project.dart)
#42     _rootRunUnary (dart:async/zone.dart:1198:47)
#43     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#44     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#45     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#46     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#47     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#48     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#49     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#50     IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart)
#51     _rootRunUnary (dart:async/zone.dart:1198:47)
#52     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#53     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#54     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#55     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#56     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#57     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#58     _rootRun (dart:async/zone.dart:1190:13)
#59     _CustomZone.run (dart:async/zone.dart:1093:19)
#60     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#61     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#64     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/haoyi/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/haoyi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/haoyi/Library/Android/sdk
    • Java binary at: /Users/haoyi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Users/haoyi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Users/haoyi/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment]
Hi @39499740 
 Can you attach the log that was written out, it would be something like flutter_01.log? https://github.com/flutter/flutter/issues/66466

**Comment by 39499740** [comment]
> Hi @39499740
> Can you attach the log that was written out, it would be something like `flutter_01.log`? #66466

The problem description is the log

**Comment by TahaTesser** [comment]
Hi @39499740 
There would be a file generated in the same project that ends with `.log`. Can you please provide it
Thank you

**Comment by 39499740** [comment]
> Hi @39499740
> There would be a file generated in the same project that ends with `.log`. Can you please provide it
> Thank you

[flutter_01.log](https://github.com/flutter/flutter/files/5821169/flutter_01.log)

**Comment by 39499740** [comment]
Is there any temporary solution? Now the project can't be packaged at all

**Comment by Gabsop** [comment]
Is there a solution for this? I have the same problem.

**Comment by iapicca** [comment]
dupe?  https://github.com/flutter/flutter/issues/68958

**Comment by cbracken** [comment]
@iapicca I don't think this is a dupe.

It looks like this happens if you run with the `$TMPDIR` environment variable set to a directory that doesn't exist. I'll see if I can patch the tool to defend against this by attempting to create the directory if it doesn't exist and failing with a reasonable error message otherwise.

**Comment by christopherfujino** [comment]
Chatted with cbracken offline, and I think probably the best solution for this would be to add a doctor validator for this (we could update all existing calls to `systemTempDirectory` with a check for its existence, but it would be difficult to prevent new ones from being added, and this seems like an edge case.

**Comment by Jasguerrero** [comment]
After chatting offline with @christopherfujino we agree that a new validator is not needed since we can add a toolThrowExit on https://github.com/flutter/flutter/blob/3.1.0/packages/flutter_tools/lib/src/base/file_system.dart#L221 

When `!super().systemTempDirectory.existsSync()`

**Comment by christopherfujino** [comment]
> Doing a quick `grep 'systemTempDirectory.createTemp'` over the tool, it looks like there are a fair number of these calls. It might be useful for us to create a method that does this, then replace those calls with that.

To follow up on this, all of those cases of `systemTempDirectory.createTemp` are actually going through the tool managed getter in `base/file_system.dart` that we are adding the tool exit to. In retrospect, overriding `systemTempDirectory` with our own `flutter_tools` directory was misleading...
