### ISSUE TITLE
--host-vmservice-port no longer works in 1.25.X

### ISSUE THREAD

**Issue by Destreyf** [flutter/flutter#74084]
I am using --host-vmservice-port in order to use WSL2, this works great under 1.22, however upon upgrading to 1.25 it no longer respects the --host-vmservice-port option.

## Steps to Reproduce

1. Open project under WSL2
2. flutter run --host-vmservice-port=43550
3. socat tcp-listen:43550,reuseaddr,bind=127.0.0.1,fork tcp:$(cat /etc/resolv.conf | tail -n1 | cut -d " " -f 2):43550 #this is to proxy the 43550 to windows
3. Receive error "Error connecting to the service protocol: failed to connect to http://127.0.0.1:59157/poK_muvCGU8=/" obviously ignoring the --host-vmservice-port

## Logs

<details>
<summary>

```bash
[        ] Waiting for observatory port to be available...
[+1426 ms] Observatory URL on device: http://127.0.0.1:41567/JVOFPWlEg48=/
[   +1 ms] executing: /home/destreyf/.android/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:41567
[   +5 ms] 62548
[        ] Forwarded host port 62548 to device port 41567 for Observatory
[   +5 ms] Caching compiled dill
[  +34 ms] Connecting to service protocol: http://127.0.0.1:62548/JVOFPWlEg48=/
[   +2 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:43550, connecting to VM service at http://127.0.0.1:62548/JVOFPWlEg48=/.
[  +45 ms] Warning: Failed to start DDS: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 43228
[        ] Fail to connect to service protocol: http://127.0.0.1:62548/JVOFPWlEg48=/: DartDevelopmentServiceException: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 43228
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:62548/JVOFPWlEg48=/
[   +2 ms] "flutter run" took 18,184ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[  +40 ms] ensureAnalyticsSent: 39ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 2

```

</summary>

## flutter doctor -v

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale C.UTF-8)
    • Flutter version 1.25.0-8.3.pre at /opt/flutter
    • Framework revision 5d36f2e7f5 (24 hours ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/destreyf/.android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /home/destreyf/.android
    • ANDROID_SDK_ROOT = /home/destreyf/.android
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by Destreyf** [comment]
I was able to make this work by specifically adding a --dds-port option as well.

So i'm now running the following command
```bash
flutter run --verbose --host-vmservice-port=43550 --dds-port=43552
```

And this ends up working, it looks like the --host-vmservice-port is setting the dds-port at the same time.  I'm not sure if this is a bug or an intended behavior.

**Comment by TahaTesser** [comment]
Hi @Destreyf 
Glad you resolved the issue, I think it's best if you specify both https://github.com/flutter/flutter/pull/70336

It is enabling and setting if dds omitted 
> If only --host-vmservice-port is specified and dds is enabled, use that for the dds port

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
