### ISSUE TITLE
fast_scroll_large_images__memory flakes, NoSuchMethodError: The method 'group' was called on null.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#74085]
Process has died:
```
-01-07T20:05:00.412932: adb logcat: 01-07 20:00:09.122  1524  4562 E ActivityManager: Sending non-protected broadcast com.motorola.motocare.INTENT_TRIGGER from system 3886:com.motorola.process.system/1000 pkg com.motorola.motgeofencesvc
2021-01-07T20:05:00.413169: adb logcat: 01-07 20:00:09.122  1524  4562 E ActivityManager: java.lang.Throwable
adb logcat: 01-07 20:00:09.122  1524  4562 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18226)
adb logcat: 01-07 20:00:09.122  1524  4562 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:18826)
adb logcat: 01-07 20:00:09.122  1524  4562 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:512)
adb logcat: 01-07 20:00:09.122  1524  4562 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2906)
adb logcat: 01-07 20:00:09.122  1524  4562 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
2021-01-07T20:05:00.454811: adb logcat: 01-07 20:00:09.159  1524  4562 I ActivityManager: Process com.example.macrobenchmarks (pid 9582) has died
```

`shell dumpsys meminfo` stdout is `No process found for: com.example.macrobenchmarks` and the test is expecting `TOTAL`
https://github.com/flutter/flutter/blob/c985fd35cd94a04371d70b91a38db54a3a7d7ee6/dev/devicelab/lib/framework/adb.dart#L499

```
Executing: /usr/local/share/android-sdk/platform-tools/adb -s ZY223J893R shell dumpsys meminfo com.example.macrobenchmarks in /Users/flutter/.cocoon/flutter/dev/benchmarks/macrobenchmarks
2021-01-08T17:05:52.729098: stdout: No process found for: com.example.macrobenchmarks
2021-01-08T17:05:52.731365: "/usr/local/share/android-sdk/platform-tools/adb" exit code: 0
2021-01-08T17:05:52.759834: Task failed: NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group(1)2021-01-08T17:05:52.760374: 

Stack trace:
2021-01-08T17:05:52.802826: dart:core                                                  Object.noSuchMethod
package:flutter_devicelab/framework/adb.dart 502:35        AndroidDevice.getMemoryStats
===== asynchronous gap ===========================
dart:async                                                 _asyncErrorWrapperHelper
package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 217:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 120:41  _TaskRunner.run
```

[fast_scroll_large_images__memory_0c80a31_2.log](https://github.com/flutter/flutter/files/5823384/fast_scroll_large_images__memory_0c80a31_2.log)

This is third flakiest test in the last two months.

**Comment by chinmaygarde** [comment]
@jmagman Looks like the process is crashing but we only have three stack frames. Are there runs from which we have collected more frames? Also, when you paste logs, can you also attach the doctor output so the symbolizer can do its thing?

```
adb logcat: 01-07 20:00:08.028  9630  9630 F DEBUG   :     #02 pc 0001d535  /system/lib/libc.so (raise+10)
adb logcat: 01-07 20:00:08.028  9630  9630 F DEBUG   :     #03 pc 00019081  /system/lib/libc.so (__libc_android_abort+34)
adb logcat: 01-07 20:00:08.028  9630  9630 F DEBUG   :     #04 pc 000170e4  /system/lib/libc.so (abort+4)
adb logcat: 01-07 20:00:08.028  9630  9630 F DEBUG   :     #05 pc 002b48f3  /data/app/com.example.macrobenchmarks-1/lib/arm/libflutter.so (offset 0x139000)
```

**Comment by jmagman** [comment]
I attached the full devicelab log, I didn't reproduce this locally.
[fast_scroll_large_images__memory_29e2cfe_2.log](https://github.com/flutter/flutter/files/5823596/fast_scroll_large_images__memory_29e2cfe_2.log)

**Comment by chinmaygarde** [comment]
We saw that log. Unfortunately, it only contains the frames listed.

**Comment by jmagman** [comment]
Then I guess part of the work here is to make the test actionable.
