### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method '[]' was called on null.Receiver: nullTried calling: []("type")

### ISSUE THREAD

**Issue by Gorniv** [flutter/flutter#74119]
## Command
```
flutter run --profile --cache-sksl
```

## Steps to Reproduce
1. select Gorniv iphone (mobile) 
2. cmd+c

## Logs
NoSuchMethodError: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("type")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      VmService._processResponse (package:vm_service/src/vm_service.dart:2080:27)
#2      VmService._processMessageStr (package:vm_service/src/vm_service.dart:2064:7)
#3      VmService._processMessage (package:vm_service/src/vm_service.dart:2015:7)
#4      _rootRunUnary (dart:async/zone.dart:1362:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:735:19)
#10     _StreamController._add (dart:async/stream_controller.dart:609:7)
#11     _StreamController.add (dart:async/stream_controller.dart:556:5)
#12     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#13     _rootRunUnary (dart:async/zone.dart:1362:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#20     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#21     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#22     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#23     _rootRunUnary (dart:async/zone.dart:1362:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
```
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.396, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.396 at /Users/gorniv/github/flutter
    • Framework revision 319d3a511c (8 hours ago), 2021-01-16 01:14:04 -0500
    • Engine revision a243f4df07
    • Dart version 2.12.0 (build 2.12.0-229.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/gorniv/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/gorniv/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/gorniv/Library/Android/sdk
    • Java binary at: /Users/gorniv/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/gorniv/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Gorniv iphone (mobile) • 00008030-001058E402D0802E            • ios            • iOS 14.3
    • iPhone 5s (mobile)     • 38764932-F08C-4E40-B3C1-2294015713B9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 87.0.4280.141

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.9+304
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: f0871deb3e5847d95eb1ce1a070c82bebcbe453e
### Plugins
app_review-2.0.1
appmetrica_sdk-0.0.5+2
device_info-1.0.0
firebase_analytics-6.3.0
firebase_analytics_web-0.1.1
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_messaging-7.0.3
flutter_crashlytics-1.0.0
flutter_isolate-1.0.0+14
flutter_udid-1.0.1
flutter_vibrate-1.0.0
package_info-0.4.3+2
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
share-0.6.5+4
sqflite-1.3.2+2
uni_links-db29c16e6a1bff54010883958db67d0bd2738067
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+1
url_launcher_windows-0.0.1+3

**Comment by iapicca** [comment]
@Gorniv 
`NoSuchMethodError: NoSuchMethodError: The method '[]' was called on null`
the issue might depend from your implementation,
can you provide  your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by zanderso** [comment]
This is https://github.com/flutter/flutter/issues/74051. @bkonyi Please see the repro instructions above. @Gorniv Could you clarify what you mean by "cmd+c"? Were you attempting to exit the tool? Why did you not use 'q'?

**Comment by Gorniv** [comment]
@zanderso because I didn't know about 'q' :D 
for people:
m - for save file,
q - for quit,
thank you!
