### ISSUE TITLE
#7345 broke hot_mode_dev_cycle__benchmark

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7412]
https://github.com/flutter/flutter/commit/6a63af4081c3a79d334178c5ef54064f814fd9b2 (#7345) broke `hot_mode_dev_cycle__benchmark`.

## Steps to Reproduce

```
cd dev/devicelab
dart bin/run.dart -t bin/tasks/hot_mode_dev_cycle__benchmark.dart
```

## Logs

[Log file](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci82YTYzYWY0MDgxYzNhNzlkMzM0MTc4YzVlZjU0MDY0ZjgxNGZkOWIyDAsSBFRhc2sYgICAgIDkiQkM)

[Build history](https://flutter-dashboard.appspot.com/build.html)

/cc @johnmccutchan

**Comment by johnmccutchan** [comment]
I cannot access the log file.

**Comment by yjbanov** [comment]
Open the [build history page](https://flutter-dashboard.appspot.com/build.html) and click on "Sign in with Google" at the bottom. You should be able to download the log file after that.

**Comment by johnmccutchan** [comment]
Got it. Thanks!

**Comment by johnmccutchan** [comment]
@tvolkert This seems related to the file system changes:


```
[hot_mode_dev_cycle__benchmark] [STDOUT] Running 'flutter packages get' in flutter_gallery... 777ms
[hot_mode_dev_cycle__benchmark] [STDOUT] NoSuchMethodError
[hot_mode_dev_cycle__benchmark] [STDOUT] #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
[hot_mode_dev_cycle__benchmark] [STDOUT] #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
[hot_mode_dev_cycle__benchmark] [STDOUT] #2      PosixStyle.rootLength (package:path/src/style/posix.dart:32)
[hot_mode_dev_cycle__benchmark] [STDOUT] #3      Context.isAbsolute (package:path/src/context.dart:177)
[hot_mode_dev_cycle__benchmark] [STDOUT] #4      Context.absolute (package:path/src/context.dart:82)
[hot_mode_dev_cycle__benchmark] [STDOUT] #5      Context.relative (package:path/src/context.dart:444)
[hot_mode_dev_cycle__benchmark] [STDOUT] #6      relative (package:path/path.dart:339)
[hot_mode_dev_cycle__benchmark] [STDOUT] #7      DartDependencySetBuilder.build (package:flutter_tools/src/dart/dependencies.dart:40)
[hot_mode_dev_cycle__benchmark] [STDOUT] #8      HotRunner._refreshDartDependencies (package:flutter_tools/src/hot.dart:100)
[hot_mode_dev_cycle__benchmark] [STDOUT] #9      HotRunner._run.<_run_async_body> (package:flutter_tools/src/hot.dart:147)
[hot_mode_dev_cycle__benchmark] [STDOUT] #10     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
[hot_mode_dev_cycle__benchmark] [STDOUT] #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
[hot_mode_dev_cycle__benchmark] [STDOUT] #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
[hot_mode_dev_cycle__benchmark] [STDOUT] #13     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
[hot_mode_dev_cycle__benchmark] [STDOUT] #14     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
[hot_mode_dev_cycle__benchmark] [STDOUT] #15     _rootRun (dart:async/zone.dart:1146)
[hot_mode_dev_cycle__benchmark] [STDOUT] #16     _CustomZone.run (dart:async/zone.dart:1026)
[hot_mode_dev_cycle__benchmark] [STDOUT] #17     _CustomZone.runGuarded (dart:async/zone.dart:924)
[hot_mode_dev_cycle__benchmark] [STDOUT] #18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
[hot_mode_dev_cycle__benchmark] [STDOUT] #19     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
[hot_mode_dev_cycle__benchmark] [STDOUT] #20     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
[hot_mode_dev_cycle__benchmark] [STDOUT] #21     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:185)
[hot_mode_dev_cycle__benchmark] [STDOUT] #22     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:97)
[hot_mode_dev_cycle__benchmark] [STDOUT] #23     _rootRun (dart:async/zone.dart:1150)
[hot_mode_dev_cycle__benchmark] [STDOUT] #24     _CustomZone.run (dart:async/zone.dart:1026)
[hot_mode_dev_cycle__benchmark] [STDOUT] #25     _CustomZone.runGuarded (dart:async/zone.dart:924)
[hot_mode_dev_cycle__benchmark] [STDOUT] #26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
[hot_mode_dev_cycle__benchmark] [STDOUT] #27     _microtaskLoop (dart:async/schedule_microtask.dart:41)
[hot_mode_dev_cycle__benchmark] [STDOUT] #28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[hot_mode_dev_cycle__benchmark] [STDOUT] #29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[hot_mode_dev_cycle__benchmark] [STDOUT] #30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[hot_mode_dev_cycle__benchmark] [STDOUT] 
```

**Comment by johnmccutchan** [comment]
Specifically it looks like a call to `isNotEmpty` is failing on a `_LocalDirectory`.

**Comment by johnmccutchan** [comment]
```
[hot_mode_dev_cycle__benchmark] [STDOUT] Instance of '_LocalDirectory'
[hot_mode_dev_cycle__benchmark] [STDOUT] /usr/local/google/home/johnmccutchan/workspace/flutter/flutter/examples/flutter_gallery/lib/demo/all.dart
```

```
[hot_mode_dev_cycle__benchmark] [STDERR] NoSuchMethodError: Class '_LocalDirectory' has no instance getter 'isNotEmpty'.
[hot_mode_dev_cycle__benchmark] [STDERR] Receiver: Instance of '_LocalDirectory'
[hot_mode_dev_cycle__benchmark] [STDERR] Tried calling: isNotEmpty
```

**Comment by tvolkert** [comment]
https://api.dartlang.org/stable/1.20.1/dart-io/Directory-class.html

`isNotEmpty` isn't a method on Directory.

**Comment by johnmccutchan** [comment]
https://github.com/flutter/flutter/pull/7423

**Comment by jason-simmons** [comment]
Just landed this: https://github.com/flutter/flutter/pull/7422

**Comment by yjbanov** [comment]
I think Jason's fix is more correct.

**Comment by johnmccutchan** [comment]
Yes.
