### ISSUE TITLE
hot_mode_dev_cycle_macos_target__benchmark timing out when user not logged in

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#74201]
hot_mode_dev_cycle_macos_target__benchmark consistently times out when using xcode 12.3 and mac catalina 12.3

```
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [  +19 ms] Building macOS application... (completed in 33.8s)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [   +3 ms] executing: /usr/bin/plutil -convert json -o - /opt/s/w/ir/tmp/t/edited_flutter_gallery/build/macos/Build/Products/Debug/flutter_gallery.app/Contents/Info.plist
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [  +10 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /opt/s/w/ir/tmp/t/edited_flutter_gallery/build/macos/Build/Products/Debug/flutter_gallery.app/Contents/Info.plist
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] {"CFBundleName":"flutter_gallery","DTXcode":"1230","DTSDKName":"macosx11.1","NSHumanReadableCopyright":"Copyright © 2019 com.example. All rights reserved.","DTSDKBuild":"20C63","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"19H15","NSPrincipalClass":"NSApplication","CFBundleIconName":"AppIcon","CFBundlePackageType":"APPL","CFBundleIconFile":"AppIcon","CFBundleSupportedPlatforms":["MacOSX"],"DTPlatformName":"macosx","CFBundleShortVersionString":"1.0.0","NSMainNibFile":"MainMenu","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"flutter_gallery","DTCompiler":"com.apple.compilers.llvm.clang.1_0","CFBundleIdentifier":"com.example.flutterGallery","DTPlatformVersion":"11.1","DTXcodeBuild":"12C33","LSMinimumSystemVersion":"10.11","DTPlatformBuild":"12C33"}
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [ +177 ms] 2021-01-17 20:06:11.251 flutter_gallery[6922:39985] Unable to create FlutterView; no GL context available.
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [  +49 ms] 2021-01-17 20:06:11.302 flutter_gallery[6922:40001] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted

```

**Comment by godofredoc** [comment]
List of builds:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20hot_mode_dev_cycle_macos_target__benchmark

One example:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20hot_mode_dev_cycle_macos_target__benchmark/213

**Comment by godofredoc** [comment]
\cc @xster @jmagman

**Comment by jmagman** [comment]
@godofredoc Can you confirm this Xcode install has the full macOS SDK and isn't being pruned in any way for size?  I don't see how it could get that far and build without the macOS SDK, but I don't see any user reports of this (yet).

@iskakaushik First failures look close to https://github.com/flutter/engine/pull/22607

**Comment by godofredoc** [comment]
Confirmed that Xcode has the full macOS SDK.

Seems like the subprocess running ```flutter run --hot -d macos --benchmark --resident --no-android-gradle-daemon --no-publish-port --verbose``` is not completing  and blocking until the entire task times out.

**Comment by godofredoc** [comment]
Running manually outside of LUCI returns the following error:

```
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] {"CFBundleName":"flutter_gallery","DTXcode":"1230","DTSDKName":"macosx11.1","NSHumanReadableCopyright":"Copyright © 2019 com.example. All rights reserved.","DTSDKBuild":"20C63","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"19H114","NSPrincipalClass":"NSApplication","CFBundleIconName":"AppIcon","CFBundlePackageType":"APPL","CFBundleIconFile":"AppIcon","CFBundleSupportedPlatforms":["MacOSX"],"DTPlatformName":"macosx","CFBundleShortVersionString":"1.0.0","NSMainNibFile":"MainMenu","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"flutter_gallery","DTCompiler":"com.apple.compilers.llvm.clang.1_0","CFBundleIdentifier":"com.example.flutterGallery","DTPlatformVersion":"11.1","DTXcodeBuild":"12C33","LSMinimumSystemVersion":"10.11","DTPlatformBuild":"12C33"}
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: [  +32 ms] Error waiting for a debug connection: The log reader stopped unexpectedly.
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: [        ] Error launching application on macOS.
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [   +1 ms] "flutter run" took 36,221ms.
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: [   +3 ms] 
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:657:9)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1174:12)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1026:27)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #5      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:280:9)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #9      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:66:9)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #12     run.<anonymous closure> (package:flutter_tools/runner.dart:64:12)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #14     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #15     runInContext (package:flutter_tools/src/context_runner.dart:75:10)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #16     main (package:flutter_tools/executable.dart:92:3)
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: 
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: 
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [   +1 ms] ensureAnalyticsSent: 0ms
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] Running shutdown hooks
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] Shutdown hook priority 4
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [   +1 ms] Shutdown hooks complete
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] exiting with code 1
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] "/Users/swarming/xcode_test/flutter/bin/flutter" exit code: 1
[hot_mode_dev_cycle_macos_target__benchmark] [STDERR] Task failed: FileSystemException: Cannot open file, path = '/tmp/edited_flutter_gallery/hot_benchmark.json' (OS Error: No such file or directory, errno = 2)
```

This error is blocking the task from completing.

**Comment by godofredoc** [comment]
The problem with this test is that it requires the swarming user to be auto logged in to ensure the application can be opened.

**Comment by godofredoc** [comment]
This is fixed, all the devicelab luci machines have the swarming user auto logged in.
