### ISSUE TITLE
error signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by stoppiNeobiz** [flutter/flutter#74200]
Hi, ive a problem with android application in release mode. The app crash and android vitals return this error:

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
void art::mirror::Object::VisitReferences<true, (art::VerifyObjectFlags)0, (art::ReadBarrierOption)1, art::gc::collector::ConcurrentCopying::RefFieldsVisitor<false>, art::gc::collector::ConcurrentCopying::RefFieldsVisitor<false> >(art::gc::collector::ConcurrentCopying::RefFieldsVisitor<false> const&, art::gc::collector::ConcurrentCopying::RefFieldsVisitor<false> const&)

```

i've try to remove the pluginand the application work correctly, i use the version 0.6.7+21

**Comment by iapicca** [comment]
@stoppiNeobiz 
can you provide your `flutter doctor -v`, your `pubspec.yaml` and your `flutter run --release -v`

**Comment by stoppiNeobiz** [comment]
@iapicca
yes, the problem is the plugin  mage_picker: ^0.6.7+21 if i remove this the app work:

my pubspec.yaml:

```
http: ^0.12.2
  cupertino_icons: ^1.0.2
  provider: ^4.3.2+3
  syncfusion_flutter_charts: ^18.4.31
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  intl: ^0.16.1
  fluttertoast: ^7.1.6
  equatable: ^1.2.5
  email_validator: ^1.0.6
  google_sign_in: ^4.5.6
  flutter_picker: ^1.1.5
  lottie: ^0.7.0+1
  rflutter_alert: ^1.1.0
  cached_network_image: ^2.4.1
  flutter_secure_storage: ^3.3.5
  firebase_admob: ^0.10.3
  mediation_test: ^0.0.1
  flutter_facebook_auth: ^1.0.2+2
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.2
  purchases_flutter: ^2.0.0
  flutter_easyloading: ^2.2.2
  flutter_phoenix: ^0.1.0
  flutter_launcher_icons: ^0.8.1
  firebase_analytics: ^6.0.0
  smart_select: ^4.3.2
  collection: ^1.14.13
  image_picker: ^0.6.7+21
```

flutter doctor -v:

```
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64, locale it-IT)
    • Flutter version 1.25.0-8.1.pre at /Users/stefanotoppi/flutter
    • Framework revision 8f89f6505b (5 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/stefanotoppi/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • LYA L09 (mobile) • F3R7N18C21007210 • android-arm64 • Android 10 (API 29)
```
The open and close immediately

```
[  +50 ms] Stopping app 'app.apk' on LYA L09.
[        ] executing: /Users/stefanotoppi/Library/Android/sdk/platform-tools/adb -s F3R7N18C21007210 shell am force-stop com.xx.xx
[  +70 ms] executing: /Users/stefanotoppi/Library/Android/sdk/platform-tools/adb -s F3R7N18C21007210 shell pm list packages com.xx.xx
[  +56 ms] package:com.xx.xx
[   +3 ms] executing: /Users/stefanotoppi/Library/Android/sdk/platform-tools/adb -s F3R7N18C21007210 shell cat /data/local/tmp/sky.com.xx.xx.sha1
[  +34 ms] 21f8b1926ac099cdb61393550e2964b7eb6a8f90
[   +1 ms] Latest build already installed.

```

**Comment by iapicca** [comment]
@stoppiNeobiz 
can you provide the full logs of `flutter run --release -v`
if those are too lengthy please attach it as `.txt` file

**Comment by stoppiNeobiz** [comment]
@iapicca 
this is the log:
[log.txt](https://github.com/flutter/flutter/files/5832218/log.txt)

**Comment by stoppiNeobiz** [comment]
@iapicca 
I receive this error:
```
java.lang.IllegalAccessError: Interface androidx.lifecycle.c implemented by class io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'io.flutter.plugins.imagepicker.ImagePickerPlugin$LifeCycleObserver' appears in /data/app/com.myse.myse-Z8ibxJnufKDVhyo79FM_eQ==/base.apk!classes2.dex)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:13)
        at com.myse.myse.MainActivity.o(MainActivity.kt:1)
        at io.flutter.embedding.android.f.k(FlutterActivityAndFragmentDelegate.java:8)
        at io.flutter.embedding.android.e.onCreate(FlutterActivity.java:4)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3868)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4074)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by darshankawar** [comment]
@stoppiNeobiz 
Can you provide a minimal complete reproducible code sample or a repo of your project that we can clone and verify the issue ?

**Comment by stoppiNeobiz** [comment]
@darshankawar 
hi, the repository is private and I cannot share it at the behest of the customer, what can we do?

**Comment by darshankawar** [comment]
@stoppiNeobiz 
I understand and we are not asking for your private repo. A clone of your project that will have a minimal reproducible code sample along with all required plugins that'll help us to replicate and verify the issue.

**Comment by stoppiNeobiz** [comment]
@darshankawar @iapicca 
I've found the problem, its this code in mainActivity:

 ```
class MainActivity: FlutterActivity() {
-    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
-        GeneratedPluginRegistrant.registerWith(flutterEngine);
-        var appOptions = AdColonyMediationAdapter.getAppOptions();
-        appOptions.setPrivacyFrameworkRequired(AdColonyAppOptions.GDPR, true);
-        appOptions.setPrivacyConsentString(AdColonyAppOptions.GDPR, "1");
-        AdColonyBundleBuilder.setShowPrePopup(true);
-        AdColonyBundleBuilder.setShowPostPopup(true);
-        var consentObject = JSONObject();
-        consentObject.put(InMobiSdk.IM_GDPR_CONSENT_AVAILABLE, true);
-        consentObject.put("gdpr", "1");
-        InMobiConsent.updateGDPRConsent(consentObject);
-    } 
 }
```

I've add this part for the mediation ads

**Comment by stoppiNeobiz** [comment]
now the app work in release mode but in android the plugin not pick the image, i receive the error
PlatformException(already_active, Image picker is already active, null, null). In debug mode work correctly.
