### ISSUE TITLE
Device doctor needs to fail gracefully on error conditions

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#74254]
Device doctor is being called from the bot_config and if there are exceptions or unexpected behavior the bot is killed, the machine is restarted, and chrome ops is being alerted.

In this case the host is not trusted in the phone and the get dimensions command is generating a bad json that can't be parsed by the bot_config.

The expected behavior is for the bot to generate a valid json and get the test bed quarantined if it can not get the expected dimensions.

```
117 2021-01-19 07:16:14.665 I: ts_mon hook_name='on_bot_idle' pool=u'cores:12|cpu:x86-64-i7-8700B|gce:0|gpu:8086:3e9b|hidpi:0|mac_model:Macmini8,1|machine_type:n1-standard-8|os:Mac-10.15.7-19H15|pool:luci.flutter.staging|python:2.7.16|ssd:1'
117 2021-01-19 07:16:14.665 I: on_bot_idle(): 0s
117 2021-01-19 07:16:31.827 I: ts_mon hook_name='on_before_poll' pool=u'cores:12|cpu:x86-64-i7-8700B|gce:0|gpu:8086:3e9b|hidpi:0|mac_model:Macmini8,1|machine_type:n1-standard-8|os:Mac-10.15.7-19H15|pool:luci.flutter.staging|python:2.7.16|ssd:1'
117 2021-01-19 07:16:31.827 I: on_before_poll(): 0s
117 2021-01-19 07:16:31.966 E: Failed to parse properties json output: No JSON object could be decoded; output: 
Traceback (most recent call last):
  File "injected.py", line 95, in get_dimensions
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
117 2021-01-19 07:16:31.967 I: ts_mon hook_name='get_dimensions' pool=u'cores:12|cpu:x86-64-i7-8700B|gce:0|gpu:8086:3e9b|hidpi:0|mac_model:Macmini8,1|machine_type:n1-standard-8|os:Mac-10.15.7-19H15|pool:luci.flutter.staging|python:2.7.16|ssd:1'
```

**Comment by keyonghan** [comment]
Those error messages are expected by logging errors.

The bot will be quarantined on such exceptions once we submit: https://chrome-internal-review.git.corp.google.com/c/infradata/config/+/3522400

**Comment by keyonghan** [comment]
CL merged.
