### ISSUE TITLE
Wrong full snapshot version, expected '71bf58bdfe725ab5d8df46cf4b929e51' found 'aec2861b8a7fb93059cdbfbaf230c8a4' the Dart compiler exited unexpectedly. 

### ISSUE THREAD

**Issue by MobileAppGwt** [flutter/flutter#74297]
`flutter run --verbose`

<details>
<summary>logs</summary>

```bash
[+1229 ms] executing: [/home/rpi4/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +237 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] b9d06fffb2db263ab7021fc39adde7f2bf988a4a
[   +4 ms] executing: [/home/rpi4/flutter/] git tag --points-at b9d06fffb2db263ab7021fc39adde7f2bf988a4a
[ +491 ms] Exit code 0 from: git tag --points-at b9d06fffb2db263ab7021fc39adde7f2bf988a4a
[   +1 ms] 1.26.0-8.0.pre
[ +265 ms] executing: [/home/rpi4/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/dev
[   +4 ms] executing: [/home/rpi4/flutter/] git ls-remote --get-url origin
[  +72 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +390 ms] Unable to locate an Android SDK.
[  +62 ms] executing: [/home/rpi4/flutter/] git rev-parse --abbrev-ref HEAD
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[+1075 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +27 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +869 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +816 ms] Skipping pub get: version match.
[ +143 ms] Found plugin menubar at /home/rpi4/Desktop/flutter-desktop-embedding/plugins/menubar/
[ +270 ms] Found plugin menubar at /home/rpi4/Desktop/flutter-desktop-embedding/plugins/menubar/
[ +737 ms] Initializing file store
[  +63 ms] Skipping target: gen_localizations
[  +27 ms] complete
[  +34 ms] Launching lib/main.dart on Linux in debug mode...
[  +27 ms] /home/rpi4/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/rpi4/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/rpi4/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.NEIKYA/flutter_tool.XNVUMM/app.dill --packages
/home/rpi4/Desktop/flutter-desktop-embedding/plugins/menubar/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[ +236 ms] CMake project not found, skipping add_custom_command() VERBATIM migration
[  +48 ms] Building Linux application...
[ +204 ms] <- compile package:menubar/main.dart
[  +32 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/rpi4/Desktop/flutter-desktop-embedding/plugins/menubar/linux
[+1009 ms] Wrong full snapshot version, expected '71bf58bdfe725ab5d8df46cf4b929e51' found 'aec2861b8a7fb93059cdbfbaf230c8a4'
[ +434 ms] the Dart compiler exited unexpectedly.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:710:13)
           #2      _rootRun (dart:async/zone.dart:1346:47)
           #3      _CustomZone.run (dart:async/zone.dart:1258:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1346:47)
           #14     _CustomZone.run (dart:async/zone.dart:1258:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1346:47)
           #26     _CustomZone.run (dart:async/zone.dart:1258:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:743:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:598:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:591:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2147:21)
           #35     _rootRunUnary (dart:async/zone.dart:1370:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:735:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:609:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:556:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1683:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1181:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[  +63 ms] ensureAnalyticsSent: 42ms
[  +13 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[  +12 ms] Shutdown hooks complete
[  +14 ms] the Dart compiler exited unexpectedly.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:710:13)
           #2      _rootRun (dart:async/zone.dart:1346:47)
           #3      _CustomZone.run (dart:async/zone.dart:1258:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1346:47)
           #14     _CustomZone.run (dart:async/zone.dart:1258:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1346:47)
           #26     _CustomZone.run (dart:async/zone.dart:1258:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:743:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:598:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:591:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2147:21)
           #35     _rootRunUnary (dart:async/zone.dart:1370:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:735:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:609:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:556:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1683:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1181:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[   +4 ms] ensureAnalyticsSent: 1ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[  +18 ms] CMake Error at CMakeLists.txt:10 (apply_standard_settings):
[   +2 ms]   Unknown CMake command "apply_standard_settings".
[   +5 ms] -- Configuring incomplete, errors occurred!
[   +2 ms] See also "/home/rpi4/Desktop/flutter-desktop-embedding/plugins/menubar/build/linux/debug/CMakeFiles/CMakeOutput.log".
[  +71 ms] Building Linux application... (completed in 1,834ms)
[   +2 ms] Exception: Unable to generate build files
[   +2 ms] "flutter run" took 6,059ms.
[  +20 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:89:3)
           <asynchronous suspension>
           
           
[  +14 ms] exiting with code 1
```
</details>

I'm using Ubuntu 20 with ARM v8 64
Help me to resolve this
Thanks in advance

**Comment by TahaTesser** [comment]
Hi @MobileAppGwt 
This could be an issue with your setup, please this possible [solutin](https://stackoverflow.com/a/59871539)  
If the problem persists, Can you please provide your `flutter doctor -v` 
Thank you

**Comment by MobileAppGwt** [comment]
I have getting the same error

Flutter doctor log 

`flutter doctor -v
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on Linux, locale en_IN)
    • Flutter version 1.26.0-8.0.pre at /home/rpi4/flutter
    • Framework revision b9d06fffb2 (12 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-237.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.
`

**Comment by TahaTesser** [comment]
Hi @MobileAppGwt 
Can you please go to the flutter directory on your computer and execute the following commands
`git clean -xffd`
`flutter channel dev`
`flutter upgrade  -f`
`flutter doctor -v`
and then running the app again  
Thank you

**Comment by stuartmorgan** [comment]
> ARM v8 64

This is a duplicate of https://github.com/flutter/flutter/issues/56992

**Comment by TahaTesser** [comment]
@stuartmorgan 
Added `platform-host-arm` label In the duplicate issue, I thought the Linux support was there just like Mac, I should've double-checked, thanks
