### ISSUE TITLE
[NPE] io.flutter.util.PathUtils.getCacheDirectory() 

### ISSUE THREAD

**Issue by gzjaychen** [flutter/flutter#74294]
Our app received some crash report:
```bash
W/ContextImpl( 2303): Unable to create files subdir /data/user/0/myappname/code_cache
E/FlutterLoader( 2303): Flutter initialization failed.
E/FlutterLoader(2303): java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
E/FlutterLoader( 2303): at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:193)
E/FlutterLoader( 2303): at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:85)
...
E/FlutterLoader( 2303): at io.flutter.util.PathUtils.getCacheDirectory(PathUtils.java:21)
E/FlutterLoader( 2303): at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:164)
E/FlutterLoader( 2303): at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:140)
```

io.flutter.util.PathUtils.java
```java    
public static String getCacheDirectory(Context applicationContext) {
    return VERSION.SDK_INT >= 21 ? applicationContext.getCodeCacheDir().getPath() : applicationContext.getCacheDir().getPath();
}
```

NPE on Android 6.x and below, because Context.getCodeCacheDir() will return null.
http://androidxref.com/6.0.1_r10/xref/frameworks/base/core/java/android/app/ContextImpl.java#508

     * The system will delete any files stored in this location both when your
     * specific application is upgraded, and when the entire platform is
     * upgraded.
```java     
getCodeCacheDir() {
    //...some code
    return createFilesDirLocked(mCodeCacheDir); // Return null **_if no space left on device._**
}

```
All flutter versions have this problem.

**Comment by TahaTesser** [comment]
Hi @gzjaychen 
Can you still be more specific? Which versions are you referring to and could you please provide your `flutter doctor -v?
> All flutter versions have this problem.

Thank you

**Comment by gzjaychen** [comment]
Hi @TahaTesser 
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 1.22.4 at
      /Users/chenjiangfeng/.terra/caches/sdk/v1.22.4-stable/flutter
    • Framework revision 1aafb3a8b9 (10 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chenjiangfeng/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/chenjiangfeng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio
      4.1.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 4.1.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
</details>

Thank you

**Comment by gzjaychen** [comment]
Hi @TahaTesser ,
I think there is an obvious NPE here, applicationContext.getCodeCacheDir() could be null, we should fix it ?

io.flutter.util.PathUtils.java
```java    
public static String getCacheDirectory(Context applicationContext) {
    return VERSION.SDK_INT >= 21 ? applicationContext.getCodeCacheDir().getPath() : applicationContext.getCacheDir().getPath();
}
```

**Comment by jmagman** [comment]
https://github.com/flutter/engine/blob/fff415d517d641a9e750d4a2c7e643262e130068/shell/platform/android/io/flutter/util/PathUtils.java#L21

**Comment by chinmaygarde** [comment]
It seems reasonable to defensively check if the code cache dir null even on level 21 and above and fallback to the regular cache directory. This seems like an easy fix.

**Comment by eggfly** [comment]
Let me pick up

**Comment by eggfly** [comment]
But I see the regular cache directory may also fails and returns null.. @chinmaygarde 
```java


    @Override
    public File getCacheDir() {
        synchronized (mSync) {
            if (mCacheDir == null) {
                mCacheDir = new File(getDataDirFile(), "cache");
            }
            return createFilesDirLocked(mCacheDir);
        }
    }

    @Override
    public File getCodeCacheDir() {
        synchronized (mSync) {
            if (mCodeCacheDir == null) {
                mCodeCacheDir = new File(getDataDirFile(), "code_cache");
            }
            return createFilesDirLocked(mCodeCacheDir);
        }
    }


    // Common-path handling of app data dir creation
    private static File createFilesDirLocked(File file) {
        if (!file.exists()) {
            if (!file.mkdirs()) {
                if (file.exists()) {
                    // spurious failure; probably racing with another process for this app
                    return file;
                }
                Log.w(TAG, "Unable to create files subdir " + file.getPath());
                return null;
            }
            FileUtils.setPermissions(
                    file.getPath(),
                    FileUtils.S_IRWXU|FileUtils.S_IRWXG|FileUtils.S_IXOTH,
                    -1, -1);
        }
        return file;
    }



```

**Comment by dnfield** [comment]
I'm concerned about using the external cache dir, since that is publicly readable/writable and may expose security vulnerabilities. We should definitely try to fall back to getCacheDir, and we should definitely throw something better than an NPE.  If we just fail to set this at all, `dart:io` will fall back to [/data/local/tmp](https://github.com/dart-lang/sdk/blob/master/runtime/bin/directory_android.cc#L432), which isn't ideal but at least would throw the exception only if the application actually tried to create something there. The application could then catch that in Dart code and choose to try to use external storage if it wanted.

**Comment by eggfly** [comment]
https://github.com/flutter/flutter/issues/74294 can solved this, issue closed.
