### ISSUE TITLE
"Null check operator used on a null value" in RenderObject.getTransformTo()

### ISSUE THREAD

**Issue by etiennelenhart** [flutter/flutter#74304]
We're seeing some non-fatal errors in Crashlytics from our users that seem to be coming from Flutter's recent migration to null-safety. I'm unfortunately not able to reproduce this, but here are my findings:
 - We're using `RenderBox.localToGlobal()` to position a widget relative to another one without passing an `ancestor`.
 - `getTransformTo()` seems to throw with "Null check operator used on a null value", which looks like it's coming from the `owner!` call.

Do we have to check, whether the node is still attached before calling `RenderBox.localToGlobal()`?

This should be the relevant piece of code (object.dart:2375):
```dart
Matrix4 getTransformTo(RenderObject? ancestor) {
  final bool ancestorSpecified = ancestor != null;
  assert(attached);
  if (ancestor == null) {
    final AbstractNode? rootNode = owner!.rootNode;
    if (rootNode is RenderObject)
      ancestor = rootNode;
  }
  final List<RenderObject> renderers = <RenderObject>[];
  for (RenderObject renderer = this; renderer != ancestor; renderer = renderer.parent as RenderObject) {
    assert(renderer != null); // Failed to find ancestor in parent chain.
    renderers.add(renderer);
  }
  if (ancestorSpecified)
    renderers.add(ancestor!);
  final Matrix4 transform = Matrix4.identity();
  for (int index = renderers.length - 1; index > 0; index -= 1) {
    renderers[index].applyPaintTransform(renderers[index - 1], transform);
  }
  return transform;
}
```

The error is happening on both iOS and Android:
 - iOS: 100% background
 - Android: 0% background but 96% proximity on

I'm posting the stack trace here for completion, but unfortunately it only goes up to our own method:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at _SuccessLayerState._nextButtonTopPosition(_SuccessLayerState.java:430)
       at _SuccessLayerState.build(_SuccessLayerState.java:350)
       at StatefulElement.build(StatefulElement.java:4744)
       at ComponentElement.performRebuild(ComponentElement.java:4627)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at StatefulElement.update(StatefulElement.java:4832)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at ProxyElement.update(ProxyElement.java:4987)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at StatefulElement.update(StatefulElement.java:4832)
       at Element.updateChild(Element.java:3314)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6125)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at StatelessElement.update(StatelessElement.java:4708)
       at Element.updateChild(Element.java:3314)
       at SingleChildRenderObjectElement.update(SingleChildRenderObjectElement.java:6125)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at Element.rebuild(Element.java:4343)
       at StatelessElement.update(StatelessElement.java:4708)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at StatefulElement.update(StatefulElement.java:4832)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at StatefulElement.update(StatefulElement.java:4832)
       at Element.updateChild(Element.java:3314)
       at RenderObjectElement.updateChildren(RenderObjectElement.java:5647)
       at MultiChildRenderObjectElement.update(MultiChildRenderObjectElement.java:6246)
       at Element.updateChild(Element.java:3314)
       at ComponentElement.performRebuild(ComponentElement.java:4652)
       at StatefulElement.performRebuild(StatefulElement.java:4800)
       at Element.rebuild(Element.java:4343)
       at BuildOwner.buildScope(BuildOwner.java:2730)
       at WidgetsBinding.drawFrame(WidgetsBinding.java:913)
       at RendererBinding._handlePersistentFrameCallback(RendererBinding.java:302)
       at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1117)
       at SchedulerBinding.handleDrawFrame(SchedulerBinding.java:1055)
       at SchedulerBinding._handleDrawFrame(SchedulerBinding.java:971)
```

Output of `flutter doctor -v`:
```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale de-DE)
    • Flutter version 1.22.5 at /Users/etiennelenhart/Documents/Tools/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/etiennelenhart/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by nt4f04uNd** [comment]
@etiennelenhart how does your stack trace contains dart log exception that maps to .java files? i'm just curious

**Comment by etiennelenhart** [comment]
@nt4f04uNd I'm honestly not 100% sure. I always thought this just happens because of Dart getting compiled down to native (in this case Java) code.

**Comment by etiennelenhart** [comment]
If anyone stumbles on this later: I'm pretty sure we were able to fix this by checking whether the `RenderBox` is still `attached` before calling `localToGlobal()`.
