### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list2021-01-20 11:58:26.841 xcodebuild[4707:9663393] Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}xcodebuild: error: Unable to read project 'Runner.xcodeproj'.	Reason: The project ‘Runner’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.Path: /Users/zeevgrim/Downloads/E-commerce-App-UI-Flutter-master/ios/Runner.xcodeproj Command: xcrun, OS error code: 74

### ISSUE THREAD

**Issue by zeevgrim** [flutter/flutter#74310]
## Command
```
flutter build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

2021-01-20 11:58:26.841 xcodebuild[4707:9663393] Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}
xcodebuild: error: Unable to read project 'Runner.xcodeproj'.
	Reason: The project ‘Runner’ is damaged and cannot be opened due to a parse error. Examine the project file for invalid edits or unresolved source control conflicts.

Path: /Users/zeevgrim/Downloads/E-commerce-App-UI-Flutter-master/ios/Runner.xcodeproj Command: xcrun, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:171:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:323:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:404:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:568:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:550:35)
<asynchronous suspension>
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:492:50)
<asynchronous suspension>
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:469:41)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart:423:36)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:88:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp (package:flutter_tools/src/commands/build_ios.dart:200:26)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:230:33)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
<asynchronous suspension>
```
```
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-IL)
    • Flutter version 1.26.0-8.0.pre at /users/zeevgrim/development/flutter
    • Framework revision b9d06fffb2 (12 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/zeevgrim/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile)     • 9083EFAE-B059-47FF-88A0-40F0B28065FC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPhone 12 Pro Max (mobile) • 6B849B51-5A3F-48B1-8A60-44C9BEB331EA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.141

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1ad9baa8b99a2897c20f9e6e54d3b9b359ade314
### Plugins
cloud_firestore-0.14.4
cloud_firestore_web-0.2.1+2
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
path_provider_linux-0.0.1+2
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3

**Comment by zeevgrim** [comment]
x
