### ISSUE TITLE
[integration_test] IntegrationTestWidgetsFlutterBinding reportData won't allow for "Array of Objects" JSON because it is Map

### ISSUE THREAD

**Issue by vrnvorona** [flutter/flutter#74324]
## Steps to Reproduce

1. Add this test to example test in master branch of plugins repo:
```
testWidgets('failure 2', (WidgetTester tester) async {
    (tester.binding as IntegrationTestWidgetsFlutterBinding).reportData = {'1': 1};
    expect(1 + 1, 2);
  });
```
and integration_test.dart:
```
import 'package:integration_test/integration_test_driver.dart' as integration_test_driver;

Future<void> main() {
  integration_test_driver.testOutputsDirectory = 'integration_test/gherkin/reports';

  return integration_test_driver.integrationDriver();
}
```
2. Run tests
3. Change `(tester.binding as IntegrationTestWidgetsFlutterBinding).reportData = {'1': 1};` to `(tester.binding as IntegrationTestWidgetsFlutterBinding).reportData = [{'1': 1}];`
4. Run tests again. 

**Expected results:** On step 2 there is File created in folder integration_test/gherkin/reports with JSON parsed contents of reportData. On step 4 - same result.

**Actual results:** On step 2 everything is fine, but on step 4 tests will fail - not surprisingly, because static analysis showed us that reportData is typed as Map<String, dynamic>, while JSON allows for Arrays too.

Why it is important: cucumber JSON format is actually an Array of Objects, so you can't use testing framework to generate correct JSON.
By the way, I have a fix for this in this commit: https://github.com/vrnvorona/plugins/commit/efa7dfa1877c2dec36d12df6becc1a4c589696d3 

<details>
  <summary>Logs</summary>

```
Using device iPhone 8 Plus.
Starting application: test_driver/failure.dart
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         4.0s
Xcode build done.                                           16.8s
flutter: Observatory listening on http://127.0.0.1:65352/PO6CDn3uFuo=/
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:65352/PO6CDn3uFuo=/
VMServiceFlutterDriver: Isolate found with number: 3927553815740579
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
flutter: find_me
flutter: tearing_down_real
flutter: 00:00 +0: failure 2
flutter: ---<outerCallbackCall>---
flutter: ---<outerCallbackCall>---
VMServiceFlutterDriver: Connected to Flutter application.
---<serialize_request_data>---
flutter: ---<outerCallbackCall>---
flutter: ---<testCompletionHandler>---
flutter: ---<testCompletionHandler>---
flutter: 00:00 +1: (tearDownAll)
flutter: invoked allTestsFinished
flutter: Warning: integration_test test plugin was not detected.
flutter: ---<outerCallbackCall>---
flutter: 00:00 +2: All tests passed!
----<fromJson>----
message: {"result":"true","failureDetails":[],"data":{"1":1}}
----<fromJson>----
All tests passed.
Stopping application instance.
➜  example git:(json_type_fix) ✗ flutter drive --driver=test_driver/integration_test_driver.dart --target=test_driver/failure.dart
Using device iPhone 8 Plus.
Starting application: test_driver/failure.dart
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running Xcode build...                                                  
Xcode build done.                                           12.7s
Failed to build iOS app
Error output from Xcode build:
↳
    2021-01-20 18:09:48.170 xcodebuild[16146:17122929]  DVTProvisioningProfileManager: Failed to load profile "/Users/voronin/Library/MobileDevice/Provisioning Profiles/match_Development_rusbiiosstage.mobileprovision" (Error
    Domain=DVTProvisioningProfileProviderErrorDomain Code=1 "Failed to load profile." UserInfo={NSLocalizedDescription=Failed to load profile., NSLocalizedRecoverySuggestion=Profile is missing the required UUID property.})
    ** BUILD FAILED **


Xcode's output:
↳
    test_driver/failure.dart:25:75: Error: A value of type 'List<Map<String, int>>' can't be assigned to a variable of type 'Map<String, dynamic>'.
     - 'List' is from 'dart:core'.
     - 'Map' is from 'dart:core'.
        (tester.binding as IntegrationTestWidgetsFlutterBinding).reportData = [{'1': 1}];
                                                                              ^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'integration_test' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'Runner' from project 'Runner')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'Flutter' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'Pods-Runner' from project 'Pods')

Could not build the application for the simulator.
Application failed to start. Will not run test. Quitting.

```

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-RU)
    • Flutter version 1.22.5 at /usr/local/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/voronin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/voronin/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode-12.1.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7223.43

[!] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 8 Plus (mobile) • AD6DDB6C-44AB-4655-81C4-AAC5C241F4A2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.448, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.448 at /Users/dhs/Code/flutter_master
    • Framework revision eeb7c261f2 (3 hours ago), 2021-01-20 23:04:03 -0500
    • Engine revision dde6b7e8ea
    • Dart version 2.12.0 (build 2.12.0-246.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos       • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.


```

</details>

**Comment by maheshmnj** [comment]
Reproducible as of latest master 3.7 also fails when running without flutter driver `flutter test integration_test`
Heres the [sample](https://github.com/flutter/flutter/files/10311543/example.zip)  project from the plugins repo.

<details>
<summary>logs</summary>

```console
mahesh@Maheshs-MacBook-Air-M1 example % flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/example_test.dart --no-dds
Could not load custom device from config index 0: Expected enabled to be a boolean.
Running "flutter pub get" in example...
Resolving dependencies... 
  archive 3.3.2 (3.3.5 available)
  pedantic 1.11.1 (discontinued replaced by lints)
Got dependencies!
Multiple devices found:
sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
iPhone 12 Pro (mobile)    • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
macOS (desktop)           • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
Chrome (web)              • chrome                               • web-javascript • Google Chrome 108.0.5359.124
[1]: sdk gphone arm64 (emulator-5554)
[2]: iPhone 12 Pro (026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4)
[3]: macOS (macos)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Running Gradle task 'assembleDebug'...                              7.7s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...        1,037ms
I/on_test_exampl( 6901): Background young concurrent copying GC freed 90844(4838KB) AllocSpace objects, 3(60KB) LOS
objects, 92% free, 2013KB/25MB, paused 9.851ms total 49.400ms
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:64683/6URaWa8n2zU=/
VMServiceFlutterDriver: Isolate found with number: 693438423231835
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter ( 6901): 00:00 +0: verify text
VMServiceFlutterDriver: Connected to Flutter application.
I/flutter ( 6901): 00:01 +1: failure 2
I/flutter ( 6901): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter ( 6901): The following _TypeError was thrown running a test:
I/flutter ( 6901): type 'List<Map<String, int>>' is not a subtype of type 'Map<String, dynamic>?' of ' in type cast'
I/flutter ( 6901): 
I/flutter ( 6901): When the exception was thrown, this was the stack:
I/flutter ( 6901): #0      main.<anonymous closure>
(file:///Users/mahesh/Development/flutter_master/packages/integration_test/example/integration_test/_example_test_io.dar
t:48:7)
I/flutter ( 6901): #1      testWidgets.<anonymous closure>.<anonymous closure>
(package:flutter_test/src/widget_tester.dart:171:29)
I/flutter ( 6901): <asynchronous suspension>
I/flutter ( 6901): #2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:935:5)
I/flutter ( 6901): <asynchronous suspension>
I/flutter ( 6901): 
I/flutter ( 6901): The test description was:
I/flutter ( 6901):   failure 2
I/flutter ( 6901): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6901): 00:01 +1: failure 2 [E]
I/flutter ( 6901):   Test failed. See exception logs above.
I/flutter ( 6901):   The test description was: failure 2
I/flutter ( 6901):   
I/flutter ( 6901): 00:01 +1 -1: (tearDownAll)
I/flutter ( 6901): 00:02 +2 -1: Some tests failed.
Failure Details:
Failure in method: failure 2
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following _TypeError was thrown running a test:
type 'List<Map<String, int>>' is not a subtype of type
'Map<String, dynamic>?' of ' in type cast'

When the exception was thrown, this was the stack:
#0      main.<anonymous closure> (file:///Users/mahesh/Development/flutter_master/packages/integration_test/example/integration_test/_example_test_io.dart:48:7)
#1      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
#2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:935:5)
<asynchronous suspension>

The test description was:
  failure 2
═════════════════════════════════════════════════════════════════

end of failure 1

mahesh@Maheshs-MacBook-Air-M1 example % 
```
</details>

<details>
<summary>logs `flutter test integration_test`</summary>

```console
mahesh@Maheshs-MacBook-Air-M1 example % flutterm test integration_test
Could not load custom device from config index 0: Expected enabled to be a boolean.
Running "flutter pub get" in example...
Resolving dependencies... 
  archive 3.3.2 (3.3.5 available)
  pedantic 1.11.1 (discontinued replaced by lints)
Got dependencies!
Multiple devices found:
sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
iPhone 12 Pro (mobile)    • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
Chrome (web)              • chrome                               • web-javascript • Google Chrome 108.0.5359.124
[1]: sdk gphone arm64 (emulator-5554)
[2]: iPhone 12 Pro (026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4)
[3]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
00:00 +0: ...hesh/Development/flutter_master/packages/integration_test/example/integration_test/extended_test.dart     R
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
00:16 +0: ...hesh/Development/flutter_master/packages/integration_test/example/integration_test/extended_test.d   16.5s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
00:17 +0: ...hesh/Development/flutter_master/packages/integration_test/example/integration_test/extended_test.dart     Installing build/app/outputs/flutter-apk/app-debug.apk...          645ms
00:21 +2: ...ahesh/Development/flutter_master/packages/integration_test/example/integration_test/example_test.dart     R
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: Errors limit exceeded. To receive all errors set com.sun.xml.bind logger to FINEST level.
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
00:33 +2: ...ahesh/Development/flutter_master/packages/integration_test/example/integration_test/example_test.d   11.7s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
00:34 +2: ...ahesh/Development/flutter_master/packages/integration_test/example/integration_test/example_test.dart     I00:35 +2: ...ahesh/Development/flutter_master/packages/integration_test/example/integration_test/example_test.d 1,382ms
00:38 +3: /Users/mahesh/Development/flutter_master/packages/integration_test/example/integration_test/example_test.dart: failure 2
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _TypeError was thrown running a test:
type 'List<Map<String, int>>' is not a subtype of type 'Map<String, dynamic>?' of ' in type cast'

When the exception was thrown, this was the stack:
#0      main.<anonymous closure> (file:///Users/mahesh/Development/flutter_master/packages/integration_test/example/integration_test/_example_test_io.dart:48:7)
#1      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  failure 2
════════════════════════════════════════════════════════════════════════════════════════════════════
00:38 +3 -1: /Users/mahesh/Development/flutter_master/packages/integration_test/example/integration_test/example_test.dart: failure 2 [E]
  Test failed. See exception logs above.
  The test description was: failure 2
  

To run this test again: /Users/mahesh/Development/flutter_master/bin/cache/dart-sdk/bin/dart test /Users/mahesh/Development/flutter_master/packages/integration_test/example/integration_test/example_test.dart -p vm --plain-name 'failure 2'
00:39 +3 -1: Some tests failed.                                                                                        
mahesh@Maheshs-MacBook-Air-M1 example % 
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
