### ISSUE TITLE
InputDecorator assertions failed: baseline != null && baseline >= 0.0

### ISSUE THREAD

**Issue by prascuna** [flutter/flutter#74326]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          body: InputDecorator(
            decoration: const InputDecoration().copyWith(
              border: const OutlineInputBorder(),
            ),
            child: Stack(
              children: [
                // Uncommenting this will fix it
                // Text('yo'),
                Image.network('https://dummyimage.com/200/09f/fff.png'),
                // Commenting this out will fix it
                Positioned(
                  right: 5,
                  bottom: 5,
                  child: Text('ok'),
                ),
              ],
            ),
          ),
        ));
  }
}
```
3. ... Just launch the app an you'll get the exception.
I noticed that either uncommenting the Text inside the Stack or Commenting out the Positioned will fix the problem

The issue happens on both Web and Android. I haven't tested it on iOS

**Expected results:** 

No exception

**Actual results:** 

<details>
<summary>logs</summary>

```bash
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
Assertion failed: file:///Users/prascuna/Documents/workspace/flutter/packages/flutter/lib/src/material/input_decorator.dart:939:12
baseline != null && baseline >= 0.0
is not true

The relevant error-causing widget was: 
  InputDecorator file:///Users/prascuna/Documents/workspace/bug_inputdecorator_2/lib/main.dart:16:17
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 24:3    assertFailed
packages/flutter/src/material/input_decorator.dart 939:44                     [_layoutLineBox]
packages/flutter/src/material/input_decorator.dart 1033:28                    [_layout]
packages/flutter/src/material/input_decorator.dart 1294:44                    performLayout
...
The following RenderObject was being processed when the exception was fired: _RenderDecoration#24114 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...  constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=776.0)
...  size: MISSING
RenderObject: _RenderDecoration#24114 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
  constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=776.0)
  size: MISSING
...  input: RenderStack#d9487 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(w=1176.0, 0.0<=h<=744.0)
...    size: Size(1176.0, 0.0)
...    alignment: AlignmentDirectional.topStart
...    textDirection: ltr
...    fit: loose
...    child 1: RenderSemanticsAnnotations#5ff28 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=1176.0, 0.0<=h<=744.0)
...      size: Size(0.0, 0.0)
...      child: RenderImage#bed8a relayoutBoundary=up4 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=1176.0, 0.0<=h<=744.0)
...        size: Size(0.0, 0.0)
...        image: null
...        alignment: Alignment.center
...        invertColors: false
...        filterQuality: low
...    child 2: RenderParagraph#69309 relayoutBoundary=up3 NEEDS-PAINT
...      parentData: right=5.0; bottom=5.0; offset=Offset(1155.0, -22.0) (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(16.0, 17.0)
...      textAlign: start
...      textDirection: ltr
...      softWrap: wrapping at box width
...      overflow: clip
...      locale: en_US
...      maxLines: unlimited
...      text: TextSpan
...        debugLabel: (englishLike body1 2014).merge(blackCupertino bodyText2)
...        inherit: false
...        color: Color(0xdd000000)
...        family: .SF UI Text
...        size: 14.0
...        weight: 400
...        baseline: alphabetic
...        decoration: TextDecoration.none
...        "ok"
...  helperError: RenderConstrainedBox#9ea52 relayoutBoundary=up2 NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(0.0<=w<=1176.0, 0.0<=h<=776.0)
...    size: Size(0.0, 0.0)
...    additionalConstraints: BoxConstraints(unconstrained)
...  container: RenderCustomPaint#4d7a3 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
Assertion failed: file:///Users/prascuna/Documents/workspace/flutter/packages/flutter/lib/src/rendering/box.dart:1920:12
hasSize
"RenderBox was not laid out: _RenderDecoration#24114 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE"
The relevant error-causing widget was: 
  Scaffold file:///Users/prascuna/Documents/workspace/bug_inputdecorator_2/lib/main.dart:15:15
====================================================================================================
```
</details>

<details>
  <summary>Logs</summary>

```
https://gist.github.com/prascuna/735897f120a1a252cfd2b8803ea3e56a


```

```
Analyzing bug_inputdecorator_2...                               
No issues found! (ran in 2.5s)

```

```
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-8.0.pre at /Users/prascuna/Documents/workspace/flutter
    • Framework revision b9d06fffb2 (13 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/prascuna/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Users/prascuna/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_262-b10)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 2 categories.

```

</details>

**Comment by pedromassangocode** [comment]
<details>
<summary>logs</summary>

```bash
[+2830 ms] I/flutter ( 3227): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[        ] I/flutter ( 3227): The following assertion was thrown during performLayout():
[        ] I/flutter ( 3227): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 946 pos 12: 'baseline !=
[        ] I/flutter ( 3227): null && baseline >= 0.0': is not true.
[        ] I/flutter ( 3227): 
[        ] I/flutter ( 3227): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 3227): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 3227): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 3227):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter ( 3227): 
[        ] I/flutter ( 3227): The relevant error-causing widget was:
[        ] I/flutter ( 3227):   InputDecorator file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:16:17
[        ] I/flutter ( 3227): 
[        ] I/flutter ( 3227): When the exception was thrown, this was the stack:
[        ] I/flutter ( 3227): #2      _RenderDecoration._layoutLineBox (package:flutter/src/material/input_decorator.dart:946:12)
[        ] I/flutter ( 3227): #3      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:1035:28)
[        ] I/flutter ( 3227): #4      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1285:44)
[        ] I/flutter ( 3227): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #6      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
[        ] I/flutter ( 3227): #7      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498:7)
[        ] I/flutter ( 3227): #8      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
[        ] I/flutter ( 3227): #9      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
[        ] I/flutter ( 3227): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[   +1 ms] I/flutter ( 3227): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #14     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1308:11)
[        ] I/flutter ( 3227): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[   +1 ms] I/flutter ( 3227): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #31     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3222:13)
[        ] I/flutter ( 3227): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #35     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:685:15)
[        ] I/flutter ( 3227): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
[        ] I/flutter ( 3227): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
[        ] I/flutter ( 3227): #49     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:14)
[        ] I/flutter ( 3227): #50     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3227): #51     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
[        ] I/flutter ( 3227): #52     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:436:19)
[        ] I/flutter ( 3227): #53     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
[        ] I/flutter ( 3227): #54     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
[        ] I/flutter ( 3227): #55     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
[        ] I/flutter ( 3227): #56     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
[        ] I/flutter ( 3227): #57     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
[        ] I/flutter ( 3227): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
[        ] I/flutter ( 3227): 
[        ] I/flutter ( 3227): The following RenderObject was being processed when the exception was fired: _RenderDecoration#464ca relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
[        ] I/flutter ( 3227):   creator: _Decorator ← InputDecorator ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
[        ] I/flutter ( 3227):     CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
[        ] I/flutter ( 3227):     _InkFeatures-[GlobalKey#55288 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
[        ] I/flutter ( 3227):     PhysicalModel ← ⋯
[        ] I/flutter ( 3227):   parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
[        ] I/flutter ( 3227):   constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=759.3)
[        ] I/flutter ( 3227):   size: MISSING
[        ] I/flutter ( 3227): This RenderObject had the following descendants (showing up to depth 5):
[        ] I/flutter ( 3227):     input: RenderStack#ce12b relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 3227):       child 1: RenderSemanticsAnnotations#7db53 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter ( 3227):         child: RenderImage#8e73f relayoutBoundary=up4 NEEDS-PAINT
[        ] I/flutter ( 3227):       child 2: RenderParagraph#15373 relayoutBoundary=up3 NEEDS-PAINT
[        ] I/flutter ( 3227):         text: TextSpan
[        ] I/flutter ( 3227):     helperError: RenderConstrainedBox#87dcd relayoutBoundary=up2 NEEDS-PAINT
[        ] I/flutter ( 3227):     container: RenderCustomPaint#1ca49 NEEDS-LAYOUT NEEDS-PAINT
[        ] I/flutter ( 3227): ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] I/flutter ( 3227): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#464ca relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
```
</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.448, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.448 at /Users/pedromassango/Code/flutter_master
    • Framework revision eeb7c261f2 (3 hours ago), 2021-01-20 23:04:03 -0500
    • Engine revision dde6b7e8ea
    • Dart version 2.12.0 (build 2.12.0-246.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by LongCatIsLooong** [comment]
This seems to be expected. `InputDecorator` expects its child to have a non-negative baseline.

**Comment by prascuna** [comment]
Thanks @LongCatIsLooong . So I assume that the right way to fix this, assuming that we know the size of the image in advance, is to wrap it into a `SizedBox` ?
Anyway, thanks for the `d: api docs` label, that would be helpful is somebody else experiences a similar issue.

**Comment by LongCatIsLooong** [comment]
@prascuna that's correct. In case the size of the image is not known you can try positioning it using a `Container` instead of `Positioned` to make sure the height of the `Stack` widget >= the height of the `Text` widget.

**Comment by pedromassangocode** [comment]
So @LongCatIsLooong what needs to be done in the API docs? Looks like we need to update the title of this issue... and the labels as well.

**Comment by LongCatIsLooong** [comment]
@pedromassango I added to the docs that the baseline of the child must not be negative.
