### ISSUE TITLE
App throws LateInitializationError when re-focusing text field

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#74347]
<details>
  <summary>Sample App</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```
</details>

Steps to repro:
1. Run the sample app

2. Focus the text field by tapping on it.
3. Press <kbd>R</kbd> to hot restart the app. The software keyboard stays.
4. Type a few characters using the software keyboard without re-focusing the text field.
5. Focus the text field. The app throws the following exception:

```
Performing hot restart...                                               
Restarted application in 849ms.

══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following LateError was thrown while dispatching notifications for FocusNode:
LateInitializationError: Field '_instance@393206165' has been assigned during initialization.

When the exception was thrown, this was the stack:
#0      TextInput._instance (package:flutter/src/services/text_input.dart)
#1      TextInput.attach (package:flutter/src/services/text_input.dart:1348:5)
#2      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:2014:21)
#3      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:2049:7)
#4      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:2386:5)
#5      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
#6      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1052:5)
#7      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1771:12)
(elided 10 frames from dart:async)

The FocusNode sending notification was:
  FocusNode#1b534([PRIMARY FOCUS])
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by LongCatIsLooong** [comment]
This seems to have to do with https://github.com/flutter/flutter/pull/72803. @jpnurmi could you take a look?

/cc @justinmc

**Comment by jpnurmi** [comment]
Thanks! I will check.

**Comment by justinmc** [comment]
Good catch figuring out how to repro this!  I was at a loss.

**Comment by pedromassangocode** [comment]
I was unable to reproduce this as well on all channels.

**Comment by jpnurmi** [comment]
@pedromassango The issue was caused by #72803 which got already reverted. I'm still unsure if this issue will be relevant because we found some severe short-comings and the whole feature may end up being rewritten from scratch. We can keep this open for now, nevertheless. It's a good test case for the future.
