### ISSUE TITLE
flutter build ios --flavor prod --analyze-size produces NoSuchMethodError: NoSuchMethodError: The getter 'isNotEmpty' was called on null.

### ISSUE THREAD

**Issue by vemarav** [flutter/flutter#74394]
## command

flutter build ios --flavor prod --analyze-size

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'isNotEmpty' was called on null.
Receiver: null
Tried calling: isNotEmpty

<details>
<summary>
stacktrace
</summary>

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SizeAnalyzer._addAotSnapshotDataToAnalysis (package:flutter_tools/src/base/analyze_size.dart:282:17)
#2      SizeAnalyzer.analyzeAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:80:23)
#3      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:143:61)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     buildXcodeProject (package:flutter_tools/src/ios/mac.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#28     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
#29     _rootRunUnary (dart:async/zone.dart:1198:47)
#30     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#34     Future._complete (dart:async/future_impl.dart:519:7)
#35     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:228:14)
#36     _rootRun (dart:async/zone.dart:1182:47)
#37     _CustomZone.run (dart:async/zone.dart:1093:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#39     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#40     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#41     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#42     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
#43     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#44     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#45     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#46     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#47     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
#48     _rootRun (dart:async/zone.dart:1182:47)
#49     _CustomZone.run (dart:async/zone.dart:1093:19)
#50     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#51     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#52     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#53     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#54     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
#55     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
#56     _StreamController.close (dart:async/stream_controller.dart:664:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:2051:21)
#58     _rootRunUnary (dart:async/zone.dart:1206:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#63     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#64     _StreamController._add (dart:async/stream_controller.dart:682:7)
#65     _StreamController.add (dart:async/stream_controller.dart:624:5)
#66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1587:35)
#67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1069:18)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#70     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

</details>

## flutter doctor

<details>
<summary>
flutter doctor
</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-IN)
    • Flutter version 1.22.5 at /Users/vemarav/.flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vemarav/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/vemarav/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • CE628EC3-20A1-4B08-B337-DBE539FC1594 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by jmagman** [comment]
#63610 `_locatedAotFilePath` is null.
https://github.com/flutter/flutter/blob/345188d40e576ffb6c97fee60446af58b8c9965a/packages/flutter_tools/lib/src/base/analyze_size.dart#L80-L85

**Comment by jmagman** [comment]
Please leave this open so we can keep track of this crash.

**Comment by darshankawar** [comment]
@jmagman Hi,
I verified this issue using a sample flavors app on latest stable (3.3.3) and running `flutter build ios --flavor dev -t lib/main_dev.dart --analyze-size` which generated proper output in console as below without throwing the reported crash:

<details>
<summary> console log </summary>

```

dhs@Dhss-MacBook-Pro flavors_example % flutter build ios --flavor dev -t lib/main_dev.dart --analyze-size
Building com.nevercode.triage for device (ios-release)...
Updating minimum iOS deployment target to 11.0.
Upgrading project.pbxproj
Upgrading AppFrameworkInfo.plist
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        21.5s
Xcode build done.                                           67.4s
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Runner.app                                                               53 MB
  Runner.app/
    _CodeSignature/
      CodeResources                                                        17 KB
    AppIcon60x60@2x.png                                                     3 KB
    Runner                                                                 95 KB
    Base.lproj/
      Main.storyboardc                                                      3 KB
      LaunchScreen.storyboardc                                              3 KB
    Assets.car                                                             95 KB
    AppIcon76x76@2x~ipad.png                                                4 KB
    Frameworks/
      libswiftCoreImage.dylib                                             327 KB
      libswiftObjectiveC.dylib                                            391 KB
      libswiftCore.dylib                                                   22 MB
      libswiftCoreGraphics.dylib                                          838 KB
      libswiftUIKit.dylib                                                 640 KB
      libswiftMetal.dylib                                                 386 KB
      libswiftDispatch.dylib                                                1 MB
      libswiftos.dylib                                                    388 KB
      libswiftCoreFoundation.dylib                                        327 KB
      Flutter.framework                                                    10 MB
      App.framework                                                         4 MB
      Dart AOT symbols accounted decompressed size                          3 MB
        package:flutter                                                     2 MB
        dart:core                                                         278 KB
        dart:typed_data                                                   203 KB
        dart:ui                                                           181 KB
        dart:collection                                                   103 KB
        dart:async                                                         89 KB
        dart:convert                                                       55 KB
        dart:io                                                            47 KB
        dart:isolate                                                       29 KB
        package:vector_math/
          vector_math_64.dart                                              24 KB
        dart:ffi                                                           15 KB
        dart:developer                                                      9 KB
        package:collection/
          src/
            priority_queue.dart                                             4 KB
        package:triage/
          main_dev.dart                                                     1 KB
        dart:vmservice_io                                                  947 B
        dart:mirrors                                                       625 B
        dart:nativewrappers                                                259 B
        dart:math                                                          250 B
        Never                                                               59 B
        void/
          <optimized out>                                                   44 B
      libswiftDarwin.dylib                                                488 KB
      libswiftQuartzCore.dylib                                            330 KB
      libswiftCoreAudio.dylib                                             399 KB
      libswiftFoundation.dylib                                             11 MB
      libswiftCoreMedia.dylib                                             391 KB
    embedded.mobileprovision                                               93 KB
    Info.plist                                                              1 KB
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
A summary of your iOS bundle analysis can be found at: /Users/dhs/.flutter-devtools/ios-code-size-analysis_01.json

To analyze your app size in Dart DevTools, run the following command:
flutter pub global activate devtools; flutter pub global run devtools --appSizeBase=ios-code-size-analysis_01.json
Built /Users/dhs/Documents/NCFlutter/triage-examples/flutter_examples/flavors_example/build/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro flavors_example % 

```

</details>

Also attached is the json generated:
[ios-code-size-analysis_01.json.zip](https://github.com/flutter/flutter/files/9715076/ios-code-size-analysis_01.json.zip)

With this, is it safe to close this issue as resolved ?

**Comment by jmagman** [comment]
We've since migrated to null safety, so this has likely been resolved.  If anyone else sees this crash, please file a new issue with the updated stack trace.  Thanks!
