### ISSUE TITLE
Failed assertion: line 481 pos 16: '_displacementTickerLastElapsed == null': is not true. overscroll_indicator.dart

### ISSUE THREAD

**Issue by GilbertoGmobil** [flutter/flutter#74405]
In my flutter App i'm implementing FCM and local Notifications for some users. But now i'm facing an error which throws every time I go to phone's main screen ( When I put the app in background) :

```dart
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 481 pos 16: '_displacementTickerLastElapsed == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      _GlowController.pull (package:flutter/src/widgets/overscroll_indicator.dart:481:16)
#3      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:304:28)
#4      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:133:41)
#5      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:49:20)
#6      ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:33:18)
...
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#a057b
  start behavior: start
```

This is my main function:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SharedPreferences.setMockInitialValues({});
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  await Hive.initFlutter();

  await Firebase.initializeApp();
  await PushNotificationsManager().init();

  runApp(MyApp());
}
```

I'm using firebase_messaging 8.0.0 dev-14.
How to handle that? Why is this happening?

**Comment by darshankawar** [comment]
@GilbertoGmobil 
Firebase related issues are tracked here. https://github.com/FirebaseExtended/flutterfire/issues. Consider opening this issue in above repo.
Closing from here.
