### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe.

### ISSUE THREAD

**Issue by hammasali** [flutter/flutter#74435]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=K7TSTG8LPZ4TSOSW --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:627:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:521:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:627:12)
#5      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:699:37)
#6      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:597:14)
#7      _RecompileRequest._run (package:flutter_tools/src/compile.dart:336:16)
#8      _CompilationRequest.run (package:flutter_tools/src/compile.dart:314:30)
#9      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:631:23)
#10     _rootRunUnary (dart:async/zone.dart:1194:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1097:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1002:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#14     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#15     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#16     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#17     _rootRun (dart:async/zone.dart:1178:47)
#18     _CustomZone.run (dart:async/zone.dart:1090:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)
#21     _rootRun (dart:async/zone.dart:1186:13)
#22     _CustomZone.run (dart:async/zone.dart:1090:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)
```
```
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on Microsoft Windows [Version 10.0.19041.746], locale en-GB)
    • Flutter version 1.26.0-8.0.pre at C:\src\flutter
    • Framework revision b9d06fffb2 (7 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Hammas\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • CPH2001 (mobile) • K7TSTG8LPZ4TSOSW • android-arm64 • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: a12e2a473a3214b4556ca589d2d9bd311ac7c6f1
### Plugins
integration_test

**Comment by iapicca** [comment]
possible relate to
https://github.com/flutter/flutter/issues/54418
https://github.com/flutter/flutter/issues/56975
https://github.com/flutter/flutter/issues/60880

**Comment by jonahwilliams** [comment]
@hammasali does the file `C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe` exist on your computer?

**Comment by darshankawar** [comment]
@hammasali 
Can you confirm if you see `dart.exe` in your FlutterSdk path:

<img width="501" alt="Screenshot 2021-01-22 at 1 53 44 PM" src="https://user-images.githubusercontent.com/67046386/105465755-5930af00-5cb9-11eb-8920-f45ad62c6e37.png">

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
