### ISSUE TITLE
Material buttons with radius of infinity is a rectangle shape instead of a pill shape

### ISSUE THREAD

**Issue by zengraf** [flutter/flutter#74498]
## Steps to Reproduce

This bug occurred on `1.26.0-1.0.pre-dev` as well as on `1.22.5-stable`

1. Run `flutter create bug`.
2. Replace MyHomePage class with this code:
```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: OutlineButton(
          onPressed: () {},
          child: Text('Test'),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(double.infinity),
          ),
        ),
      ),
    );
  }
}
```
**Expected results:** 

<img width="150" alt="Screenshot 2020-12-18 at 15 28 45" src="https://user-images.githubusercontent.com/23504276/105505055-c7c93900-5cc8-11eb-9bfa-b4006efc0792.png">

**Actual results:** 

<img width="143" alt="image" src="https://user-images.githubusercontent.com/23504276/105509880-483e6880-5cce-11eb-8d8c-b5bb6ba17116.png">

<details>
  <summary>Logs</summary>

When the button is clicked program generates this output

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 46: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  OutlineButton file:///Users/zengraf/Projects/uj-software-testing/test_apps/bug/lib/main.dart:26:16
When the exception was thrown, this was the stack: 
#2      _rrectIsValid (dart:ui/painting.dart:46:10)
#3      Path.addRRect (dart:ui/painting.dart:2419:12)
#4      RoundedRectangleBorder.getOuterPath (package:flutter/src/painting/rounded_rectangle_border.dart:112:9)
#5      _OutlineBorder.getOuterPath (package:flutter/src/material/outline_button.dart:589:18)
#6      ShapeBorderClipper.getClip (package:flutter/src/rendering/proxy_box.dart:1300:18)
...
The following RenderObject was being processed when the exception was fired: RenderPhysicalShape#f40ba relayoutBoundary=up5
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...  layer: PhysicalModelLayer#17aaa DETACHED
...    engine layer: PhysicalShapeEngineLayer#05a08
...    elevation: 0.0
...    color: Color(0x00000000)
...  size: Size(88.0, 36.0)
...  elevation: 0.0
...  color: Color(0x00000000)
...  shadowColor: Color(0x00000000)
...  clipper: ShapeBorderClipper
RenderObject: RenderPhysicalShape#f40ba relayoutBoundary=up5
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
  layer: PhysicalModelLayer#17aaa DETACHED
    engine layer: PhysicalShapeEngineLayer#05a08
    elevation: 0.0
    color: Color(0x00000000)
  size: Size(88.0, 36.0)
  elevation: 0.0
  color: Color(0x00000000)
  shadowColor: Color(0x00000000)
  clipper: ShapeBorderClipper
...  child: RenderCustomPaint#79922 relayoutBoundary=up6 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...    size: Size(88.0, 36.0)
...    child: _RenderInkFeatures#87f3e relayoutBoundary=up7 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...      size: Size(88.0, 36.0)
...      child: RenderSemanticsAnnotations#535da relayoutBoundary=up8
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...        size: Size(88.0, 36.0)
...        child: RenderMouseRegion#421ce relayoutBoundary=up9
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...          size: Size(88.0, 36.0)
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 46: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  OutlineButton file:///Users/zengraf/Projects/uj-software-testing/test_apps/bug/lib/main.dart:26:16
When the exception was thrown, this was the stack: 
#2      _rrectIsValid (dart:ui/painting.dart:46:10)
#3      Path.addRRect (dart:ui/painting.dart:2419:12)
#4      RoundedRectangleBorder.getOuterPath (package:flutter/src/painting/rounded_rectangle_border.dart:112:9)
#5      _OutlineBorder.getOuterPath (package:flutter/src/material/outline_button.dart:589:18)
#6      ShapeBorderClipper.getClip (package:flutter/src/rendering/proxy_box.dart:1300:18)
...
The following RenderObject was being processed when the exception was fired: RenderPhysicalShape#f40ba relayoutBoundary=up5
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...  layer: PhysicalModelLayer#17aaa DETACHED
...    engine layer: PhysicalShapeEngineLayer#faf3a
...    elevation: 0.0
...    color: Color(0x00000000)
...  size: Size(88.0, 36.0)
...  elevation: 0.0
...  color: Color(0x00000000)
...  shadowColor: Color(0x00000000)
...  clipper: ShapeBorderClipper
RenderObject: RenderPhysicalShape#f40ba relayoutBoundary=up5
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
  layer: PhysicalModelLayer#17aaa DETACHED
    engine layer: PhysicalShapeEngineLayer#faf3a
    elevation: 0.0
    color: Color(0x00000000)
  size: Size(88.0, 36.0)
  elevation: 0.0
  color: Color(0x00000000)
  shadowColor: Color(0x00000000)
  clipper: ShapeBorderClipper
...  child: RenderCustomPaint#79922 relayoutBoundary=up6 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...    size: Size(88.0, 36.0)
...    child: _RenderInkFeatures#87f3e relayoutBoundary=up7 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...      size: Size(88.0, 36.0)
...      child: RenderSemanticsAnnotations#535da relayoutBoundary=up8
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...        size: Size(88.0, 36.0)
...        child: RenderMouseRegion#421ce relayoutBoundary=up9
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(88.0<=w<=428.0, 36.0<=h<=926.0)
...          size: Size(88.0, 36.0)
...          listeners: enter, exit
...          cursor: SystemMouseCursor(click)
====================================================================================================

======== Exception caught by rendering library =====================================================
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 46: '<optimized out>'
The relevant error-causing widget was: 
  OutlineButton file:///Users/zengraf/Projects/uj-software-testing/test_apps/bug/lib/main.dart:26:16
====================================================================================================

======== Exception caught by rendering library =====================================================
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 46: '<optimized out>'
The relevant error-causing widget was: 
  OutlineButton file:///Users/zengraf/Projects/uj-software-testing/test_apps/bug/lib/main.dart:26:16
====================================================================================================

======== Exception caught by rendering library =====================================================
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 46: '<optimized out>'
The relevant error-causing widget was: 
  OutlineButton file:///Users/zengraf/Projects/uj-software-testing/test_apps/bug/lib/main.dart:26:16
====================================================================================================
```

```
Analyzing bug...
No issues found! (ran in 1.9s)
```

```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
    • Flutter version 1.26.0-1.0.pre at
      /Users/zengraf/.asdf/installs/flutter/1.26.0-1.0.pre-dev
    • Framework revision 63062a6443 (6 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zengraf/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/zengraf/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/zengraf/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @zengraf 
OutlineButton is [deprecated](https://api.flutter.dev/flutter/material/OutlineButton-class.html) and it shouldn't be used.

Use `OutlinedButton` instead, it has no animation glitch but no pill shape either. Tapping on throws no error but using the same style for `ElevatedButton`, ti does throw the error.

As far as the pill shape,  I didn't know `double.infinity` is expected to create a rounded corner to make a pill, using it on Card also doesn't work. Can you please provide me an example where using `double.infinity` is expected to make pill shape in when used in border radius.?

Try this code sample below

<details>
<summary>complete runnable code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Card(
              color: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(double.infinity),
              ),
              child: FlutterLogo(
                size: 100,
              ),
            ),
            OutlinedButton(
              onPressed: () {},
              child: Text('Test'),
              style: ButtonStyle(
                  shape: MaterialStateProperty.all(RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(double.infinity),
              ))),
            ),
            ElevatedButton(
              onPressed: () {},
              child: Text('Test'),
              style: ButtonStyle(
                  shape: MaterialStateProperty.all(RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(double.infinity),
              ))),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (10 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.144, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.144 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2007186d2e (10 hours ago), 2021-01-24 12:54:00 -0800
    • Engine revision fdddf87080
    • Dart version 2.12.0 (build 2.12.0-253.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thank you

**Comment by zengraf** [comment]
Hi @TahaTesser 
I have tried running your code and everything works as you described. I went a bit further and tried putting `double.maxFinite` instead of `double.infinity`. The `ElevatedButton` stopped throwing exceptions, but there was no pill shape on any widget.

Later I found out that there is some threshold for each device past which widgets become squares, here is a demonstration on iPhone 12 Pro Max simulator:


https://user-images.githubusercontent.com/23504276/105709515-1c152880-5f16-11eb-8386-330a9b473dc0.mp4


If I am not mistaken, any radius value bigger than width or height of the widget should produce the pill shape.

Here is the code I used:
<details>
  <summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  double value = 3.40e+38;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(value.toString()),
            Card(
              color: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(value),
              ),
              child: FlutterLogo(
                size: 100,
              ),
            ),
            OutlinedButton(
              onPressed: () {},
              child: Text('Test'),
              style: ButtonStyle(
                  shape: MaterialStateProperty.all(RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(value),
              ))),
            ),
            ElevatedButton(
              onPressed: () {},
              child: Text('Test'),
              style: ButtonStyle(
                  shape: MaterialStateProperty.all(RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(value),
              ))),
            ),
            Slider(
              value: value,
              onChanged: (v) => setState(() => value = v),
              min: 3.4028e+38,
              max: 3.4029e+38,
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>

**Comment by HansMuller** [comment]
To get a pill shaped border you can use [StadiumBorder](https://api.flutter.dev/flutter/painting/StadiumBorder-class.html). 

> If I am not mistaken, any radius value bigger than width or height of the widget should produce the pill shape.

As far as I can tell, this was never documented behavior for the rounded rectangle shapes. Your test app is pretty interesting in that it shows that there's a very large rounded rectangle border radius threshold, below which a stadium border is drawn, however I don't think it's a good idea to depend on that. 

Although I'm sorry that the observed behavior seems to have regressed, I'm going to close this issue because I don't believe we ever intended to support it.

If StadiumBorder doesn't work for you application, please open an issue that explains why, and we'll look into it.
