### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'activeDevToolsServer' was called on null.Receiver: nullTried calling: activeDevToolsServer

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#74537]
## Command
```
flutter run --disable-service-auth-codes --machine -d flutter-tester --devtools-server-address http://127.0.0.1:9110 --start-paused
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'activeDevToolsServer' was called on null.
Receiver: null
Tried calling: activeDevToolsServer
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ResidentRunner._callDevToolsUriExtension (package:flutter_tools/src/resident_runner.dart:1302:38)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#3      ResidentRunner.maybeCallDevToolsUriServiceExtension (package:flutter_tools/src/resident_runner.dart:1289:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 1.26.0-13.0.pre.113, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.26.0-13.0.pre.113 at /Users/kenzieschmoll/develop/flutter
    • Framework revision 6975e1d38e (35 minutes ago), 2021-01-22 15:12:08 -0800
    • Engine revision 30486859d1
    • Dart version 2.12.0 (build 2.12.0-248.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kenzieschmoll/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    ! Xcode 11.2.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.1
    • Dart plugin version 201.9317

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (5 available)
    • Pixel 3 (mobile)           • 8BWX1GAAE                            • android-arm64  • Android 11 (API 30)
    • iPhone 11 Pro (mobile)     • 7FE41F1E-01FD-4E35-9B46-3759DB526FE0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • Flutter test device (null) • flutter-tester                       • flutter-tester • Flutter 6975e1d38e
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: null
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null

**Comment by kenzieschmoll** [comment]
Not a real crash - Working on this with @jonahwilliams

**Comment by jonahwilliams** [comment]
Closing as resolved
