### ISSUE TITLE
[tool_crash] StateError: Bad state: Existing VM service clients prevent DDS from taking control.

### ISSUE THREAD

**Issue by sfmsakib** [flutter/flutter#74580]
## Command
```
flutter --no-color run --machine --verbose --track-widget-creation --device-id=BVK6R19426005588 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Existing VM service clients prevent DDS from taking control.
```
#0      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:83:11)
<asynchronous suspension>
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:249:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-8.0.pre at C:\src\flutter
    • Framework revision b9d06fffb2 (2 weeks ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • DUB LX1 (mobile)        • BVK6R19426005588 • android-arm64 • Android 8.1.0 (API 27)
    • sdk gphone x86 (mobile) • emulator-5554    • android-x86   • Android 11 (API 30) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
flutter_keyboard_visibility-4.0.2
flutter_keyboard_visibility_web-1.0.1

**Comment by pedromassangocode** [comment]
Similar (maybe duplicate) to https://github.com/flutter/flutter/issues/74033?!

**Comment by jmagman** [comment]
@bkonyi this looks like https://github.com/flutter/flutter/issues/66557 again?

**Comment by bkonyi** [comment]
Yes, that's the same failure, but should be resolved by [this CL](https://dart-review.googlesource.com/c/sdk/+/178725) which landed in the framework a week or two ago. We shouldn't be seeing this once we release the next beta.
