### ISSUE TITLE
Unhandled Exception: FileSystemException: Cannot open file, path

### ISSUE THREAD

**Issue by mealinux** [flutter/flutter#74595]
Works API 30 but doesn't work level 23 (Android 6.0) -sqlite/sqflite

//settings
```
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  path: ^1.7.0
  sqflite: ^1.3.2+2

```

//my code
```
final String pathDB = "db.sqlite";

  Future<Database> accessDb() async {
    WidgetsFlutterBinding.ensureInitialized();

    String dbPath = join(await getDatabasesPath(), pathDB);

    if (await databaseExists(dbPath)) {
    } else {
      ByteData data = await rootBundle.load('databases/${pathDB}');

      List<int> bytes =
          data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      await Directory(dbPath).create(recursive: true);
      await File(dbPath).writeAsBytes(bytes, flush: true);

    }
    var database = await openDatabase(dbPath, version: 1);
    return database;
  }
```

//pubspec.yaml asset
```
  assets:
    - databases/db.sqlite
```

//error
```
E/flutter ( 5841): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot open file, path = '/data/user/0/com.example.first_app/databases/db.sqlite' (OS Error: Is a directory, errno = 21)
E/flutter ( 5841): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 5841): #1      _rootRunUnary (dart:async/zone.dart:1194:47)
E/flutter ( 5841): #2      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
E/flutter ( 5841): #3      _FutureListener.handleValue (dart:async/future_impl.dart:150:18)
E/flutter ( 5841): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:703:45)
E/flutter ( 5841): #5      Future._propagateToListeners (dart:async/future_impl.dart:732:32)
E/flutter ( 5841): #6      Future._completeWithValue (dart:async/future_impl.dart:536:5)
E/flutter ( 5841): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:574:7)
E/flutter ( 5841): #8      _rootRun (dart:async/zone.dart:1186:13)
E/flutter ( 5841): #9      _CustomZone.run (dart:async/zone.dart:1090:19)
E/flutter ( 5841): #10     _CustomZone.runGuarded (dart:async/zone.dart:994:7)
E/flutter ( 5841): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)
E/flutter ( 5841): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 5841): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by iapicca** [comment]
@mealinux 
[sqflite](https://pub.dev/packages/sqflite) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/tekartik/sqflite/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**
