### ISSUE TITLE
Web app execution pauses in developer_patch.js on startup

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#74600]
Steps to reproduce:

1. `flutter channel dev` and `flutter upgrade`
2. Run app from IntelliJ in debug mode
3. The app pauses at the following breakpoint in `developer_patch.js`:

<img width="591" alt="Screen Shot 2021-01-24 at 9 49 40 AM" src="https://user-images.githubusercontent.com/1145719/105638808-a7fd5680-5e29-11eb-9f14-f2801f318c3e.png">

**Comment by pedromassangocode** [comment]
I cannot reproduce this issue on dev channel.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-12.0.pre at /Users/pedromassango/Code/flutter_dev
    • Framework revision a706cd2112 (10 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
```

</details>

**Comment by jmagman** [comment]
What's the error being caught?

**Comment by johnpryan** [comment]
"Unexpected null value"

<img width="870" alt="Screen Shot 2021-01-26 at 3 12 03 PM" src="https://user-images.githubusercontent.com/1145719/105918493-dc6b4100-5fe8-11eb-9ff4-6699594d8e10.png">

**Comment by johnpryan** [comment]
```
"Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:56471/dart_sdk.js:5306:11)
    at Object.nullCheck (http://localhost:56471/dart_sdk.js:5639:30)
    at http://localhost:56471/dart_sdk.js:50378:29
    at Generator.next (<anonymous>)
    at runBody (http://localhost:56471/dart_sdk.js:39000:34)
    at Object._async [as async] (http://localhost:56471/dart_sdk.js:39031:7)
    at http://localhost:56471/dart_sdk.js:50376:20
    at new Promise (<anonymous>)
    at Object._invokeExtension [as invokeExtension] (http://localhost:56471/dart_sdk.js:50373:12)
    at <anonymous>:1:31"
```

**Comment by danagbemava-nc** [comment]
@johnpryan, since the dev channel no longer exists and this issue is quite old, can you confirm if this is still valid on the latest flutter versions?

**Comment by johnpryan** [comment]
I'm going to close since this is a very old issue. If this comes up again I'll file a new one.
