### ISSUE TITLE
Unable to run app on iOS device and simulator in debug mode

### ISSUE THREAD

**Issue by yogikorke** [flutter/flutter#74640]
I am able to run my Flutter app on both Android and Web in debug mode but unable to run on iOS device and simulator in debug mode. When I run app from Xcode then it run properly every time. But as Xcode don't have hot reload and hot restart options it is becomes very difficult to test and debug app from Xcode. I am also able to build ipa file and xcode archive and submit it in App Store Connect. 

Step to reproduce : 
flutter run --debug

When I start my app in debug mode for testing during development then my app launches on iPhone and then get detached automatically with below message : 

```
[        ] Application launched on the device. Waiting for observatory port.
[+30021 ms] Installing and launching... (completed in 43.9s)
[   +1 ms] Error launching application on iPhone.
[  +28 ms] "flutter run" took 3,79,069ms.
[  +20 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:623:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:88:3)
           <asynchronous suspension>
           
           
[  +17 ms] (lldb) process detach
[ +238 ms] ensureAnalyticsSent: 241ms
[   +9 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +9 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

```
**NOTE :** 
When I run app as "flutter run --release" then it works properly and don't get detached automatically.
I face this issue only when I run it as "flutter run --debug"

**Flutter doctors output :** 

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.3.pre at /Users/yogeshkorke/Work/FlutterSDK/flutter
    • Framework revision 5d36f2e7f5 (11 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/yogeshkorke/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/yogeshkorke/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Redmi Note 5 Pro (mobile) • 44472eda                                 • android-arm64  • Android 9 (API 28)
    • Redmi Note 5 Pro (mobile) • 192.168.2.201:5555                       • android-arm64  • Android 9 (API 28)
    • iPhone (mobile)           • aaa765fdb9d3a02ecc0773f21ab8552a89b53b48 • ios            • iOS 14.3
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 87.0.4280.141
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)
```

• No issues found!

**Comment by darshankawar** [comment]
@yogikorke 
Can you try [this](https://github.com/flutter/flutter/issues/69885#issuecomment-723643780) solution and see if it works for you ?

**Comment by yogikorke** [comment]
@darshankawar , I tried that solution but it was giving me some errors.  From that solution, I understood that problem might be related to Xcode data and its cache, so I manually uninstalled Xcode and Re-installed, and now I am able to run app on iOS device and simulator in debug mode successfully.
Thanks for sharing that solution link. It gave me hint.
