### ISSUE TITLE
[google_maps_flutter_web] Widget not disappearing after route change

### ISSUE THREAD

**Issue by davidjan3** [flutter/flutter#74676]
## Steps to Reproduce

1. Have a fullscreen-sized GMap widget in a Stack with a toolbar and stuff
2. Have a button launching pushNamed to change routes
3. (Have a custom onGenerateRoute giving normal MaterialPageRoutes, and use flutter_web_plugins to get rid of the hash in the url)
4. Open page with GMap in Chrome or Firefox on Windows
5. Click button

## Expected results:
The new page opens, and the GMap on the old page disappears with the old page.

## Actual results:
The new page opens, and the GMap quickly reappears on top of the new page after it's done animating its appearance. It will not resize with the browser window anymore, but it will react to dragging etc.

**Detailed information:**
This does not happen on mobile webbrowsers, and also not on emulated mobile in Chrome after refreshing the page. If I emulate mobile in Chrome, refresh the page, and then quit emulating mobile without refreshing, it does also not occur. I didn't have this issue using flutter_google_maps, so I doubt it's a common iframe issue. This happens on the latest dev and master build (probably others too, can't test my full application there without major adaptations), and my Flutter doctor is all good.

**Comment by davidjan3** [comment]
_my pizza burned while I wrote this, so please make it worth it._

**Comment by pedromassangocode** [comment]
Hi @davidjan3 
I cannot reproduce the issue.
Can you please provide your `flutter doctor -v` your `pubspec.yaml` and a minimal reproducible code sample.
Thank you

**Comment by davidjan3** [comment]
main.dart:
```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: "/",
      routes: {
        "/": (context) => HomePage(),
        "/sub": (context) => SubPage(),
      },
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: new LatLng(52.5208271, 13.4093387),
              zoom: 14.0,
            ),
            minMaxZoomPreference: MinMaxZoomPreference(4.0, 20.0),
            zoomControlsEnabled: false,
            rotateGesturesEnabled: false,
          ),
          FloatingActionButton(onPressed: () {
            Navigator.pushNamed(context, "/sub");
          }),
        ],
      ),
    );
  }
}

class SubPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text("Sub page"),
      ),
    );
  }
}
```

pubspec.yaml:
```
name: gmap_test
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.1.1
  google_maps_flutter_web: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

flutter doctor -v:
```
[√] Flutter (Channel dev, 1.26.0-12.0.pre, on Microsoft Windows [Version 10.0.19042.782], locale de-DE)
    • Flutter version 1.26.0-12.0.pre at C:\WebCode\Tools\Flutter
    • Framework revision a706cd2112 (12 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\David\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\David\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • SM G973F (mobile) • RF8M21NL7DH • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!
```

**Comment by davidjan3** [comment]
Appears the issue is only happening on dev and master channels, beta works as expected. So unless I'm mistaken and this package fails to adapt to some incoming changes, you might close this issue.

**Comment by davidjan3** [comment]
Moving from dev to beta channel actually has an influence on the bug. Now the map is *behind* the freshly opened page - due to iframe pointer passthrough, one can still drag around the map through the background. I've now figured out, that this only happens using CanvasKit, which explains the absence of the bug on mobile browsers.

**Comment by pedromassangocode** [comment]
The issue seems to be that the navigator is showing the next in only some portion of the screen. In my example I've added a backgroundColor in the Scaffold of the page being pushed so you can see that it is being added in the right side of the web-page only. The issue disappear if you reload the page.

I can confirm that this only happens with CanvasKit renderer.

### Found in: Master, Dev, Beta channel

![gif](https://user-images.githubusercontent.com/67424416/105954084-7a581d80-6074-11eb-8d75-59888d2c4cc4.gif)

### On Beta channel, I'm able to interact with the Google Maps from the first page route, as mentioned by the OP, but the original is still reproducible, the second route does not cover the entire web-area.

Important: Notice the onTap callback being called while touching the scaffold oof the second page.

![gif](https://user-images.githubusercontent.com/67424416/105954709-5fd27400-6075-11eb-884f-0ed6aed0007e.gif)


#### While reproducing on Master channel, I found this crash logs while you press the back button in the second route. 
<details>
<summary>crash logs</summary>

```bash
[+5384 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14
           _userProvidedRouteName != null
           is not true
               at Object.throw_ [as throw] (http://localhost:52564/dart_sdk.js:5336:11)
               at Object.assertFailed (http://localhost:52564/dart_sdk.js:5272:15)
               at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:52564/dart_sdk.js:148292:59)
[  +83 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:239:12
           _isOriginEntry(state)
           is not true
               at Object.throw_ [as throw] (http://localhost:52564/dart_sdk.js:5336:11)
               at Object.assertFailed (http://localhost:52564/dart_sdk.js:5272:15)
               at _engine.SingleEntryBrowserHistory.new.[_unwrapOriginState] (http://localhost:52564/dart_sdk.js:148268:57)
               at _engine.SingleEntryBrowserHistory.new.tearDown (http://localhost:52564/dart_sdk.js:148328:79)
               at tearDown.next (<anonymous>)
               at http://localhost:52564/dart_sdk.js:39034:33
               at _RootZone.runUnary (http://localhost:52564/dart_sdk.js:38891:58)
               at _FutureListener.thenAwait.handleValue (http://localhost:52564/dart_sdk.js:33877:29)
               at handleValueCallback (http://localhost:52564/dart_sdk.js:34437:49)
               at Function._propagateToListeners (http://localhost:52564/dart_sdk.js:34475:17)
               at _Future.new.[_completeWithValue] (http://localhost:52564/dart_sdk.js:34317:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:52564/dart_sdk.js:34340:35)
               at Object._microtaskLoop (http://localhost:52564/dart_sdk.js:39178:13)
               at _startMicrotaskLoop (http://localhost:52564/dart_sdk.js:39184:13)
               at http://localhost:52564/dart_sdk.js:34691:9
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-13.0.pre.194 at /Users/pedromassango/Code/flutter_master
    • Framework revision 71aec53acb (30 minutes ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.26.0-12.0.pre at /Users/pedromassango/Code/flutter_dev
    • Framework revision a706cd2112 (12 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en)
    • Flutter version 1.25.0-8.3.pre at /Users/pedromassango/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (12 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by ditman** [comment]
@ferhatb: @yjbanov is taking a look, this might be related to some CK optimizations pushed recently.
