### ISSUE TITLE
App crash at start-up

### ISSUE THREAD

**Issue by Kleak** [flutter/flutter#74800]
## Steps to Reproduce

create an emulator with android API 21
clone https://github.com/Kleak/fail_api_16
update minSdkVersion to 21
run the application with flutter run 

<details>
<summary>logs</summary>

```bash
[  +52 ms] executing: [/home/kleak/fvm/versions/dev/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] a706cd211240f27be3b61f06d70f958c7a4156fe
[        ] executing: [/home/kleak/fvm/versions/dev/] git tag --points-at a706cd211240f27be3b61f06d70f958c7a4156fe
[  +11 ms] Exit code 0 from: git tag --points-at a706cd211240f27be3b61f06d70f958c7a4156fe
[        ] 1.26.0-12.0.pre
[  +28 ms] executing: [/home/kleak/fvm/versions/dev/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/kleak/fvm/versions/dev/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +27 ms] executing: [/home/kleak/fvm/versions/dev/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +30 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] executing: /home/kleak/Android/Sdk/platform-tools/adb devices -l
[  +33 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:3
[   +5 ms] /home/kleak/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +14 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] Skipping pub get: version match.
[  +62 ms] Found plugin integration_test at /home/kleak/fvm/versions/dev/packages/integration_test/
[  +90 ms] Found plugin integration_test at /home/kleak/fvm/versions/dev/packages/integration_test/
[   +3 ms] Generating /home/kleak/Work/github.com/Kleak/fail_api_16/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +42 ms] ro.hardware = ranchu
[  +13 ms] Using software rendering with device Android SDK built for x86. You may get better performance with hardware mode by configuring hardware rendering for your device.
[  +15 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +2 ms] complete
[   +2 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +3 ms] /home/kleak/fvm/versions/dev/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/kleak/fvm/versions/dev/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/kleak/fvm/versions/dev/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.HSDRMJ/flutter_tool.YRWPZH/app.dill --packages /home/kleak/Work/github.com/Kleak/fail_api_16/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
[   +5 ms] executing: /home/kleak/Android/Sdk/build-tools/30.0.2/aapt dump xmltree /home/kleak/Work/github.com/Kleak/fail_api_16/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +4 ms] Exit code 0 from: /home/kleak/Android/Sdk/build-tools/30.0.2/aapt dump xmltree /home/kleak/Work/github.com/Kleak/fail_api_16/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.fail_api_16" (Raw: "com.example.fail_api_16")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="fail_api_16" (Raw: "fail_api_16")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.fail_api_16.MainActivity" (Raw: "com.example.fail_api_16.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +4 ms] executing: /home/kleak/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[   +9 ms] <- compile package:fail_api_16/main.dart
[   +9 ms] --------- beginning of system
           01-27 11:24:24.804 W/ActivityManager( 1534): Activity pause timeout for ActivityRecord{2f5b4a20 u0 com.example.fail_api_16/.MainActivity t12 f}
[  +17 ms] executing: /home/kleak/Android/Sdk/platform-tools/adb version
[  +10 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as /home/kleak/Android/Sdk/platform-tools/adb
[   +1 ms] executing: /home/kleak/Android/Sdk/platform-tools/adb start-server
[   +5 ms] Building APK
[  +11 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] Using gradle from /home/kleak/Work/github.com/Kleak/fail_api_16/android/gradlew.
[        ] /home/kleak/Work/github.com/Kleak/fail_api_16/android/gradlew mode: 33277 rwxrwxr-x.
[   +2 ms] executing: /home/kleak/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/jre/bin/java -version
[  +38 ms] Exit code 0 from: /home/kleak/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +1 ms] executing: [/home/kleak/Work/github.com/Kleak/fail_api_16/android/] /home/kleak/Work/github.com/Kleak/fail_api_16/android/gradlew -Pverbose=true -Ptarget-platform=android-x86 -Ptarget=/home/kleak/Work/github.com/Kleak/fail_api_16/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Pdart-defines=FLUTTER_WEB_AUTO_DETECT%3Dtrue assembleDebug
[ +622 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :integration_test:preBuild UP-TO-DATE
[        ] > Task :integration_test:preDebugBuild UP-TO-DATE
[        ] > Task :integration_test:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :integration_test:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
[  +86 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :integration_test:mergeDebugShaders UP-TO-DATE
[        ] > Task :integration_test:compileDebugShaders NO-SOURCE
[        ] > Task :integration_test:generateDebugAssets UP-TO-DATE
[        ] > Task :integration_test:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[  +99 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :integration_test:compileDebugRenderscript NO-SOURCE
[        ] > Task :integration_test:generateDebugResValues UP-TO-DATE
[        ] > Task :integration_test:generateDebugResources UP-TO-DATE
[        ] > Task :integration_test:packageDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :integration_test:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :integration_test:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :integration_test:parseDebugLocalResources UP-TO-DATE
[        ] > Task :integration_test:generateDebugRFile UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :integration_test:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :integration_test:javaPreCompileDebug UP-TO-DATE
[        ] > Task :integration_test:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :integration_test:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[ +101 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :integration_test:processDebugJavaRes NO-SOURCE
[        ] > Task :integration_test:bundleLibResDebug NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :integration_test:bundleLibRuntimeToJarDebug UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :integration_test:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :integration_test:mergeDebugNativeLibs NO-SOURCE
[        ] > Task :integration_test:stripDebugDebugSymbols NO-SOURCE
[        ] > Task :integration_test:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[  +92 ms] > Task :app:assembleDebug
[        ] > Task :integration_test:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :integration_test:extractDebugAnnotations UP-TO-DATE
[        ] > Task :integration_test:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :integration_test:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :integration_test:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :integration_test:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :integration_test:syncDebugLibJars UP-TO-DATE
[        ] > Task :integration_test:bundleDebugAar UP-TO-DATE
[        ] > Task :integration_test:compileDebugSources UP-TO-DATE
[        ] > Task :integration_test:assembleDebug UP-TO-DATE
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 889ms
[        ] 57 actionable tasks: 4 executed, 53 up-to-date
[+1932 ms] Running Gradle task 'assembleDebug'... (completed in 2,985ms)
[  +32 ms] calculateSha: LocalDirectory: '/home/kleak/Work/github.com/Kleak/fail_api_16/build/app/outputs/flutter-apk'/app.apk
[  +15 ms] calculateSha: reading file took 15us
[ +441 ms] calculateSha: computing sha took 441us
[   +1 ms] ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[   +3 ms] executing: /home/kleak/Android/Sdk/build-tools/30.0.2/aapt dump xmltree /home/kleak/Work/github.com/Kleak/fail_api_16/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +6 ms] Exit code 0 from: /home/kleak/Android/Sdk/build-tools/30.0.2/aapt dump xmltree /home/kleak/Work/github.com/Kleak/fail_api_16/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.fail_api_16" (Raw: "com.example.fail_api_16")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="fail_api_16" (Raw: "fail_api_16")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.fail_api_16.MainActivity" (Raw: "com.example.fail_api_16.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[        ] Stopping app 'app.apk' on Android SDK built for x86.
[        ] executing: /home/kleak/Android/Sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.example.fail_api_16
[ +285 ms] executing: /home/kleak/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.fail_api_16
[ +301 ms] package:com.example.fail_api_16
[   +3 ms] executing: /home/kleak/Android/Sdk/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.fail_api_16.sha1
[  +14 ms] 10bb9a1748584ad6f146f12a18b0c4e2df517c0b
[        ] Latest build already installed.
[        ] executing: /home/kleak/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +21 ms] --------- beginning of main
           01-27 11:24:34.840 I/art     ( 4832): Debugger is no longer active
[  +13 ms] executing: /home/kleak/Android/Sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-software-rendering true --ez enable-checked-mode true --ez verify-entry-points true com.example.fail_api_16/com.example.fail_api_16.MainActivity
[ +289 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.fail_api_16/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[   +3 ms] Observatory URL on device: http://127.0.0.1:42144/LQfofNFDs9o=/
[        ] executing: /home/kleak/Android/Sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:42144
[   +6 ms] 32785
[        ] Forwarded host port 32785 to device port 42144 for Observatory
[   +4 ms] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:32785/LQfofNFDs9o=/
[   +1 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:32785/LQfofNFDs9o=/.
[ +142 ms] DDS is listening at http://127.0.0.1:39379/WsSaG2GSl8Q=/.
[  +47 ms] Successfully connected to service protocol: http://127.0.0.1:32785/LQfofNFDs9o=/
[+75721 ms] Error connecting to the service protocol: _flutter.listViews: (-32000) Bad state: The client closed with pending request "_flutter.listViews".
[   +1 ms] "flutter run" took 80,867ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:625:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1156:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1008:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +134 ms] ensureAnalyticsSent: 133ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 2
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-12.0.pre at /home/kleak/fvm/versions/dev
    • Framework revision a706cd2112 (12 days ago), 2021-01-14 18:20:26 -0500
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/kleak/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/kleak/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio
    • Android Studio at /home/kleak/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/kleak/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/kleak/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.5981.155
    • Flutter plugin version 51.0.4
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 5.0.2 (API 21) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Linux
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
</details>

**Comment by TahaTesser** [comment]
Hi @Kleak 
This is a duplicate  of https://github.com/flutter/flutter/issues/73118
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
