### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: Input/output error, errno = 5

### ISSUE THREAD

**Issue by EmmanuelKD** [flutter/flutter#74846]
## Command
```
flutter --quiet assemble --depfile /Users/emmanuelkofi/Desktop/zipzapApi flutter/ZipZap/build/app/intermediates/flutter/debug/flutter_build.d --output /Users/emmanuelkofi/Desktop/zipzapApi flutter/ZipZap/build/app/intermediates/flutter/debug -dTargetFile=/Users/emmanuelkofi/Desktop/zipzapApi flutter/ZipZap/lib/main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=flutter.inspector.structuredErrors%3Dtrue debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readSync failed, OS Error: Input/output error, errno = 5
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:760:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#4      new Node (package:flutter_tools/src/build_system/build_system.dart:944:34)
#5      Target._toNode (package:flutter_tools/src/build_system/build_system.dart:150:12)
#6      Target._toNode (package:flutter_tools/src/build_system/build_system.dart:155:58)
#7      Target._toNode (package:flutter_tools/src/build_system/build_system.dart:155:58)
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:555:30)
#9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:221:58)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZoned (dart:async/zone.dart:1550:10)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.5 19F96 darwin-x64, locale en-SL)
    • Flutter version 1.22.5 at /Users/emmanuelkofi/Desktop/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/emmanuelkofi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Users/emmanuelkofi/Desktop/_igetintopc.com_Xcode_11_Stable_for_macOS/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • TECNO LA6 (mobile) • 031601181P002519 • android-arm • Android 7.0 (API 24)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aafb3a8b9b0c36241c5f5b34ee914770f015818
### Plugins
flutter-phone-direct-caller-d910fe25dcf9219a6934f9c934139c56d52eff0c
cloud_firestore-0.16.0
cloud_firestore_web-0.3.0+1
firebase_auth-0.20.0+1
firebase_auth_web-0.3.2+6
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_storage-7.0.0
firebase_storage_web-0.1.1+3
fluttertoast-7.1.6
location-3.2.4
location_web-1.0.1
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
permission_handler-5.0.1+1
qrscan-0.2.21
sms-0.2.4
sms_receiver-0.3.1+1
sqflite-1.3.2+2
ussd-0.0.2+1

**Comment by EmmanuelKD** [comment]
found this after i force restart my mac

**Comment by pedromassangocode** [comment]
This may be related to https://github.com/flutter/flutter/issues/61264#issuecomment-656898218.

**Comment by darshankawar** [comment]
Considering the age of the issue and lack of activity, I am going ahead and closing this as stale.

@EmmanuelKD  If you are still experiencing this issue using latest stable version, please open a new issue using template so that we can address it.
If anybody disagrees, please write in comments and I'll reopen it.
