### ISSUE TITLE
flutter web, slow rendering when decoding images and using single picture on every frame

### ISSUE THREAD

**Issue by ta9ki** [flutter/flutter#74897]
less than 30 sprites = 60 fps
more than 300 sprites = 2 fps

<details>
<summary>code sample</summary>

```dart
import 'dart:typed_data';
import 'dart:ui';
import 'package:flutter/material.dart' hide Image;

var sprite = {};
int spriteint = 300;

Picture backgroundPicture;
int lastLoop;
Paint red = Paint()..color = const Color(0xFFFF0000);
Paint orange = Paint()..color = const Color(0xFFFF8000);
Paint yellow = Paint()..color = const Color(0xFFFFFF05);

main() {
  WidgetsFlutterBinding.ensureInitialized();
  backgroundPicture = createBackgroundPicture();
  WidgetsBinding.instance.window.onBeginFrame = gameLoop;
  WidgetsBinding.instance.window.scheduleFrame();
  for (var i = 0; i < spriteint; i++) {
    sprite[i] = Sprite();
  }
}

Picture createBackgroundPicture() {
  final PictureRecorder pictureRecorder = PictureRecorder();
  final Canvas canvas = Canvas(
      pictureRecorder,
      Rect.fromLTWH(0.0, 0.0, WidgetsBinding.instance.window.physicalSize.width,
          WidgetsBinding.instance.window.physicalSize.height));
  canvas.drawPaint(red);
  canvas.drawCircle(Offset(200, 300), 150, yellow);
  canvas.drawCircle(Offset(500, 500), 250, orange);
  return pictureRecorder.endRecording();
}

void gameLoop(Duration d) {
  final loop = d.inMicroseconds;
  final loopDelta = loop - (lastLoop ?? loop);
  lastLoop = loop;
  for (var i = 0; i < spriteint; i++) {
    sprite[i].update(loopDelta);
  }

  final SceneBuilder builder = SceneBuilder();
  builder.addPicture(Offset.zero, backgroundPicture);
  for (var i = 0; i < spriteint; i++) {
    sprite[i].render(builder);
  }

  WidgetsBinding.instance.window.render(builder.build());
  WidgetsBinding.instance.window.scheduleFrame();
}

class Sprite {
  double x = 0, y = 100, dx = 8, dy = 0;
  Picture picture;

  void update(int loopDelta) {
    x += dx * loopDelta / 16000;
    y += dy * loopDelta / 16000;
    if ((x < 0 && dx < 0) || (x > 1000 && dx > 0)) dx = -dx;
    if ((y < 0 && dy < 0) || (y > 1000 && dy > 0)) dy = -dy;
  }

  void render(SceneBuilder builder) {
    if (picture != null) {
      builder.addPicture(Offset(x, y), picture);
    }
  }

  Sprite() {
    createSpriteFrame();
  }

  void createSpriteFrame() {
      Uint8List lst = Uint8List.fromList([
      137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 60,
      0, 0, 0, 72, 8, 6, 0, 0, 0, 170, 79, 150, 165, 0, 0, 0, 4, 103, 65, 77,
      65, 0, 0, 177, 142, 124, 251, 81, 147, 0, 0, 2, 94, 73, 68, 65, 84, 120,
      156, 237, 155, 61, 78, 195, 64, 16, 133, 199, 40, 161, 160, 74, 132, 92,
      80, 82, 70, 66, 17, 13, 13, 23, 160, 132, 130, 43, 32, 174, 225, 35, 208,
      162, 92, 129, 130, 156, 131, 46, 68, 226, 8, 41, 172, 40, 169, 168, 34,
      133, 110, 61, 94, 237, 120, 102, 227, 117, 136, 244, 252, 42, 139, 108,
      118, 231, 105, 62, 15, 251, 151, 140, 152, 246, 197, 158, 52, 101, 69,
      166, 182, 33, 34, 189, 163, 116, 10, 6, 36, 121, 57, 235, 52, 148, 19, 20,
      156, 225, 26, 14, 18, 6, 13, 24, 171, 232, 254, 188, 92, 170, 65, 76, 102,
      107, 181, 13, 239, 167, 161, 189, 138, 55, 92, 134, 225, 12, 15, 164, 15,
      98, 49, 182, 160, 203, 37, 97, 249, 187, 88, 184, 231, 139, 233, 52, 216,
      94, 106, 227, 197, 22, 52, 0, 151, 97, 56, 195, 34, 210, 158, 146, 99,
      204, 177, 148, 20, 219, 198, 195, 59, 40, 184, 12, 195, 25, 174, 33, 109,
      153, 39, 167, 170, 198, 22, 73, 136, 198, 98, 204, 5, 151, 97, 56, 195,
      77, 85, 58, 249, 18, 207, 82, 117, 185, 222, 63, 164, 16, 190, 131, 109,
      94, 159, 245, 87, 18, 46, 195, 112, 134, 155, 24, 112, 172, 196, 86, 102,
      46, 203, 156, 57, 149, 188, 138, 237, 188, 245, 203, 67, 36, 137, 85, 250,
      225, 250, 220, 33, 49, 153, 173, 15, 198, 219, 184, 83, 17, 37, 142, 110,
      236, 171, 1, 151, 97, 56, 195, 53, 164, 121, 53, 227, 243, 234, 187, 171,
      65, 18, 188, 83, 169, 77, 133, 135, 203, 48, 156, 97, 211, 142, 199, 215,
      106, 151, 100, 48, 254, 10, 88, 150, 117, 93, 76, 78, 224, 50, 12, 103,
      216, 116, 20, 72, 29, 159, 6, 74, 203, 64, 203, 114, 175, 65, 253, 92,
      154, 8, 208, 176, 105, 121, 200, 37, 239, 66, 28, 79, 30, 234, 42, 247,
      61, 210, 72, 242, 39, 30, 73, 48, 182, 84, 215, 46, 94, 13, 203, 29, 21,
      184, 12, 195, 25, 246, 217, 115, 76, 164, 194, 216, 114, 44, 210, 114,
      172, 254, 218, 82, 147, 224, 12, 91, 15, 196, 131, 178, 96, 44, 253, 157,
      227, 205, 251, 57, 160, 122, 171, 247, 58, 184, 224, 50, 12, 103, 88, 68,
      154, 99, 86, 20, 71, 137, 133, 136, 136, 86, 75, 125, 210, 194, 227, 137,
      141, 13, 46, 195, 112, 134, 125, 164, 57, 79, 106, 185, 148, 208, 146,
      142, 66, 164, 137, 199, 49, 95, 25, 184, 12, 195, 25, 54, 77, 60, 218, 84,
      197, 83, 192, 152, 11, 46, 195, 112, 134, 77, 27, 191, 121, 94, 61, 151,
      101, 85, 189, 255, 11, 75, 62, 110, 158, 87, 30, 202, 82, 255, 46, 92,
      134, 225, 12, 155, 14, 196, 57, 198, 167, 38, 75, 108, 247, 195, 161, 51,
      3, 151, 97, 56, 195, 173, 118, 60, 110, 223, 70, 169, 226, 112, 122, 218,
      110, 213, 54, 159, 163, 240, 184, 143, 155, 141, 123, 158, 143, 199, 188,
      79, 135, 61, 92, 134, 225, 12, 71, 35, 45, 225, 20, 43, 9, 191, 54, 99,
      73, 253, 112, 193, 101, 24, 206, 176, 248, 115, 90, 239, 23, 46, 193, 127,
      238, 169, 240, 110, 83, 153, 99, 251, 132, 203, 48, 156, 97, 107, 149, 14,
      110, 238, 89, 80, 60, 64, 73, 198, 186, 25, 84, 23, 98, 151, 187, 234, 38,
      33, 92, 134, 225, 12, 255, 1, 102, 172, 210, 13, 246, 211, 202, 107, 0, 0,
      0, 0, 73, 69, 78, 68, 174, 66, 96, 130]);
    instantiateImageCodec(lst).then((codec) {
      codec.getNextFrame().then((frameInfo) {
        final Image image = frameInfo.image;
        final PictureRecorder pictureRecorder = PictureRecorder();
        final Canvas canvas = Canvas(
            pictureRecorder,
            Rect.fromLTWH(
                0.0, 0.0, image.width.toDouble(), image.height.toDouble()));
        canvas.drawImage(image, Offset.zero, Paint());
        picture = pictureRecorder.endRecording();
      });
    });
  }
}
```
</details>

for comparison  dart+webgl
http://www.stagexl.org/samples/performance/index.html
more than 120000 sprites = 60fps

**Comment by iapicca** [comment]
@ta9ki 
[your code sample](https://github.com/flutter/flutter/issues/74897#issue-796112065) returns error for me

<details>
<summary>code sample</summary>

```dart
import 'dart:typed_data';
import 'dart:ui';
import 'package:flutter/material.dart' hide Image;

var sprite = {};
int spriteint = 300;

Picture backgroundPicture;
int lastLoop;
Paint red = Paint()..color = const Color(0xFFFF0000);
Paint orange = Paint()..color = const Color(0xFFFF8000);
Paint yellow = Paint()..color = const Color(0xFFFFFF05);

main() {
  WidgetsFlutterBinding.ensureInitialized();
  backgroundPicture = createBackgroundPicture();
  WidgetsBinding.instance.window.onBeginFrame = gameLoop;
  WidgetsBinding.instance.window.scheduleFrame();
  for (var i = 0; i < spriteint; i++) {
    sprite[i] = Sprite();
  }
}

Picture createBackgroundPicture() {
  final PictureRecorder pictureRecorder = PictureRecorder();
  final Canvas canvas = Canvas(
      pictureRecorder,
      Rect.fromLTWH(0.0, 0.0, WidgetsBinding.instance.window.physicalSize.width,
          WidgetsBinding.instance.window.physicalSize.height));
  canvas.drawPaint(red);
  canvas.drawCircle(Offset(200, 300), 150, yellow);
  canvas.drawCircle(Offset(500, 500), 250, orange);
  return pictureRecorder.endRecording();
}

void gameLoop(Duration d) {
  final loop = d.inMicroseconds;
  final loopDelta = loop - (lastLoop ?? loop);
  lastLoop = loop;
  for (var i = 0; i < spriteint; i++) {
    sprite[i].update(loopDelta);
  }

  final SceneBuilder builder = SceneBuilder();
  builder.addPicture(Offset.zero, backgroundPicture);
  for (var i = 0; i < spriteint; i++) {
    sprite[i].render(builder);
  }

  WidgetsBinding.instance.window.render(builder.build());
  WidgetsBinding.instance.window.scheduleFrame();
}

class Sprite {
  double x = 0, y = 100, dx = 8, dy = 0;
  Picture picture;

  void update(int loopDelta) {
    x += dx * loopDelta / 16000;
    y += dy * loopDelta / 16000;
    if ((x < 0 && dx < 0) || (x > 1000 && dx > 0)) dx = -dx;
    if ((y < 0 && dy < 0) || (y > 1000 && dy > 0)) dy = -dy;
  }

  void render(SceneBuilder builder) {
    if (picture != null) {
      builder.addPicture(Offset(x, y), picture);
    }
  }

  Sprite() {
    createSpriteFrame();
  }

  void createSpriteFrame() {
      Uint8List lst = Uint8List.fromList([
      137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 60,
      0, 0, 0, 72, 8, 6, 0, 0, 0, 170, 79, 150, 165, 0, 0, 0, 4, 103, 65, 77,
      65, 0, 0, 177, 142, 124, 251, 81, 147, 0, 0, 2, 94, 73, 68, 65, 84, 120,
      156, 237, 155, 61, 78, 195, 64, 16, 133, 199, 40, 161, 160, 74, 132, 92,
      80, 82, 70, 66, 17, 13, 13, 23, 160, 132, 130, 43, 32, 174, 225, 35, 208,
      162, 92, 129, 130, 156, 131, 46, 68, 226, 8, 41, 172, 40, 169, 168, 34,
      133, 110, 61, 94, 237, 120, 102, 227, 117, 136, 244, 252, 42, 139, 108,
      118, 231, 105, 62, 15, 251, 151, 140, 152, 246, 197, 158, 52, 101, 69,
      166, 182, 33, 34, 189, 163, 116, 10, 6, 36, 121, 57, 235, 52, 148, 19, 20,
      156, 225, 26, 14, 18, 6, 13, 24, 171, 232, 254, 188, 92, 170, 65, 76, 102,
      107, 181, 13, 239, 167, 161, 189, 138, 55, 92, 134, 225, 12, 15, 164, 15,
      98, 49, 182, 160, 203, 37, 97, 249, 187, 88, 184, 231, 139, 233, 52, 216,
      94, 106, 227, 197, 22, 52, 0, 151, 97, 56, 195, 34, 210, 158, 146, 99,
      204, 177, 148, 20, 219, 198, 195, 59, 40, 184, 12, 195, 25, 174, 33, 109,
      153, 39, 167, 170, 198, 22, 73, 136, 198, 98, 204, 5, 151, 97, 56, 195,
      77, 85, 58, 249, 18, 207, 82, 117, 185, 222, 63, 164, 16, 190, 131, 109,
      94, 159, 245, 87, 18, 46, 195, 112, 134, 155, 24, 112, 172, 196, 86, 102,
      46, 203, 156, 57, 149, 188, 138, 237, 188, 245, 203, 67, 36, 137, 85, 250,
      225, 250, 220, 33, 49, 153, 173, 15, 198, 219, 184, 83, 17, 37, 142, 110,
      236, 171, 1, 151, 97, 56, 195, 53, 164, 121, 53, 227, 243, 234, 187, 171,
      65, 18, 188, 83, 169, 77, 133, 135, 203, 48, 156, 97, 211, 142, 199, 215,
      106, 151, 100, 48, 254, 10, 88, 150, 117, 93, 76, 78, 224, 50, 12, 103,
      216, 116, 20, 72, 29, 159, 6, 74, 203, 64, 203, 114, 175, 65, 253, 92,
      154, 8, 208, 176, 105, 121, 200, 37, 239, 66, 28, 79, 30, 234, 42, 247,
      61, 210, 72, 242, 39, 30, 73, 48, 182, 84, 215, 46, 94, 13, 203, 29, 21,
      184, 12, 195, 25, 246, 217, 115, 76, 164, 194, 216, 114, 44, 210, 114,
      172, 254, 218, 82, 147, 224, 12, 91, 15, 196, 131, 178, 96, 44, 253, 157,
      227, 205, 251, 57, 160, 122, 171, 247, 58, 184, 224, 50, 12, 103, 88, 68,
      154, 99, 86, 20, 71, 137, 133, 136, 136, 86, 75, 125, 210, 194, 227, 137,
      141, 13, 46, 195, 112, 134, 125, 164, 57, 79, 106, 185, 148, 208, 146,
      142, 66, 164, 137, 199, 49, 95, 25, 184, 12, 195, 25, 54, 77, 60, 218, 84,
      197, 83, 192, 152, 11, 46, 195, 112, 134, 77, 27, 191, 121, 94, 61, 151,
      101, 85, 189, 255, 11, 75, 62, 110, 158, 87, 30, 202, 82, 255, 46, 92,
      134, 225, 12, 155, 14, 196, 57, 198, 167, 38, 75, 108, 247, 195, 161, 51,
      3, 151, 97, 56, 195, 173, 118, 60, 110, 223, 70, 169, 226, 112, 122, 218,
      110, 213, 54, 159, 163, 240, 184, 143, 155, 141, 123, 158, 143, 199, 188,
      79, 135, 61, 92, 134, 225, 12, 71, 35, 45, 225, 20, 43, 9, 191, 54, 99,
      73, 253, 112, 193, 101, 24, 206, 176, 248, 115, 90, 239, 23, 46, 193, 127,
      238, 169, 240, 110, 83, 153, 99, 251, 132, 203, 48, 156, 97, 107, 149, 14,
      110, 238, 89, 80, 60, 64, 73, 198, 186, 25, 84, 23, 98, 151, 187, 234, 38,
      33, 92, 134, 225, 12, 255, 1, 102, 172, 210, 13, 246, 211, 202, 107, 0, 0,
      0, 0, 73, 69, 78, 68, 174, 66, 96, 130]);
    instantiateImageCodec(lst).then((codec) {
      codec.getNextFrame().then((frameInfo) {
        final Image image = frameInfo.image;
        final PictureRecorder pictureRecorder = PictureRecorder();
        final Canvas canvas = Canvas(
            pictureRecorder,
            Rect.fromLTWH(
                0.0, 0.0, image.width.toDouble(), image.height.toDouble()));
        canvas.drawImage(image, Offset.zero, Paint());
        picture = pictureRecorder.endRecording();
      });
    });
  }
}
```

</details>

<details>
<summary>logs</summary>

```bash
[ +298 ms] Launching lib/main.dart on Chrome in debug mode...
[ +119 ms] Updating assets
[  +88 ms] Waiting for connection from debug service on Chrome...
[  +90 ms] <- reset
[   +6 ms] /home/francesco/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.JAIBCU/flutter_tool.DEHCJE/app.dill
--libraries-spec file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/francesco/projects/issue/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.JAIBCU/flutter_tools.KGEFNF --filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +19 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+24084 ms] Waiting for connection from debug service on Chrome... (completed in 24.2s)
[        ] Synced 29.2MB.
[        ] <- accept
[        ] Caching compiled dill
[ +314 ms] Using Chromium 88.0.4324.96 snap

[ +286 ms] [CHROME]:
[   +1 ms] [CHROME]:(chrome:395056): Gtk-WARNING **: 18:00:48.350: Theme parsing error: gtk.css:1555:23: 'font-feature-settings' is not a valid property name
[   +4 ms] [CHROME]:
[        ] [CHROME]:(chrome:395056): Gtk-WARNING **: 18:00:48.356: Theme parsing error: gtk.css:3591:25: 'font-feature-settings' is not a valid property name
[   +1 ms] [CHROME]:
[        ] [CHROME]:(chrome:395056): Gtk-WARNING **: 18:00:48.357: Theme parsing error: gtk.css:4053:23: 'font-feature-settings' is not a valid property name
[ +111 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:46031/devtools/browser/ce154f0a-ab04-4da3-8b15-c5f12efe5e57
[ +900 ms] DwdsInjector: Received request for entrypoint at http://localhost:45213/main_module.bootstrap.js
[   +7 ms] MetadataProvider: Loading debug metadata...
[  +41 ms] MetadataProvider: Loaded debug metadata
[  +30 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:45213/main_module.bootstrap.js
[+2656 ms] DevHandler: Debug service listening on ws://127.0.0.1:41751/VDcg5WNyfyI=/ws

[  +11 ms] Debug service listening on ws://127.0.0.1:41751/VDcg5WNyfyI=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+7831 ms] Error: Unexpected null value.
                        at Object.throw_ [as throw] (http://localhost:45213/dart_sdk.js:5337:11)
                        at Object.nullCheck (http://localhost:45213/dart_sdk.js:5670:30)
                        at _engine.LayerSceneBuilder.new.addPicture (http://localhost:45213/dart_sdk.js:141801:12)
                        at gameLoop (http://localhost:45213/packages/issue/main.dart.lib.js:174:13)
                        at Object.invoke1 (http://localhost:45213/dart_sdk.js:183585:7)
                        at _engine.EnginePlatformDispatcher.__.invokeOnBeginFrame (http://localhost:45213/dart_sdk.js:164059:15)
                        at http://localhost:45213/dart_sdk.js:180846:55
[+3328 ms] DevHandler: Stopped debug service on ws://127.0.0.1:36121

[   +3 ms] Application finished.
[   +5 ms] "flutter run" took 40,779ms.
[ +256 ms] ensureAnalyticsSent: 253ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-13.0.pre.231, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-13.0.pre.231 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 29e604e241 (8 hours ago), 2021-01-28 00:04:03 -0800
    • Engine revision 68cd4c42b5
    • Dart version 2.12.0 (build 2.12.0-267.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.96 snap

! Doctor found issues in 1 category.
```

</details>

**Comment by ta9ki** [comment]
> [your code sample](https://github.com/flutter/flutter/issues/74897#issue-796112065) returns error for me

try running with null safety disabled, for example here - https://dartpad.dev/

**Comment by ta9ki** [comment]
> [your code sample](https://github.com/flutter/flutter/issues/74897#issue-796112065) returns error for me

you can also check on this example:

```
import 'package:flutter/material.dart';
import 'dart:math';

class DiscData {
  static final _rng = Random();

  final double size;
  final Color color;
  final Alignment alignment;

  DiscData()
      : size = _rng.nextDouble() * 40 + 10,
        color = Color.fromARGB(
          _rng.nextInt(200),
          _rng.nextInt(255),
          _rng.nextInt(255),
          _rng.nextInt(255),
        ),
        alignment = Alignment(
          _rng.nextDouble() * 2 - 1,
          _rng.nextDouble() * 2 - 1,
        );
}

void main() async {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Container(
          color: Color(0xFF15202D),
          child: SizedBox.expand(
            child: VariousDiscs(300),
          ),
        ),
      ),
    ),
  );
}

class VariousDiscs extends StatefulWidget {
  final numberOfDiscs;

  VariousDiscs(this.numberOfDiscs);

  @override
  _VariousDiscsState createState() => _VariousDiscsState();
}

class _VariousDiscsState extends State<VariousDiscs> {
  final _discs = <DiscData>[];
  

  @override
  void initState() {
    super.initState();
    _makeDiscs();
  }

  void _makeDiscs() {
    _discs.clear();
    for (int i = 0; i < widget.numberOfDiscs; i++) {
      _discs.add(DiscData());
      print("1");
    }
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => setState(() {
        _makeDiscs();
      }),
      child: Stack(
        children: [
          Center(
            child: Text(
              'Click a disc!',
              style: TextStyle(color: Colors.white, fontSize: 50),
            ),
          ),
          for (final disc in _discs)
            Positioned.fill(
              child: AnimatedAlign(
                duration: Duration(milliseconds: 5500),
                curve: Curves.easeInOut,
                alignment: disc.alignment,
                child: AnimatedContainer(
                  duration: Duration(milliseconds: 5500),
                  decoration: BoxDecoration(
                    color: disc.color,
                   // shape: BoxShape.circle,
                  ),
                  height: disc.size,
                  width: disc.size,
                ),
              ),
            ),
        ],
      ),
    );
  }
}

```

**Comment by pedromassangocode** [comment]
Hi @ta9ki 
Can you please  elaborate what tools are you using for performance measurements and what are the actual vs expected results?
Thank you

**Comment by ta9ki** [comment]
I didn't use any performance tools, just visual control. Expectations-flutter web should not be slower than other engines, such as cocos2d, defold, gideros. I tested flutter web for about a year, but I didn't notice any performance improvements during this time. Actual flutter results are 50-70 sprites at 60 fps. Other engines are hundreds of times faster. 

Flutter is good on Android, Ios,Windows. 
In the web, a clumsy bear.

**Comment by yjbanov** [comment]
The error is because of a bug that doesn't allow you to add a picture without a container layer to the `SceneBuilder`. I'm fixing that, but in the meantime if you `pushOffset(0, 0);` on the `SceneBuilder` prior to calling `addPicture` you won't see the error.

In my test I have to go above 2000 to see jank, when building using the defaults, which on desktop uses `--web-renderer=canvaskit`. That's significantly more that 300. `--web-renderer=html` is much slower.

Of course, it would be great to handle 120k sprites at 60fps, so I'll keep this issue open as an optimization opportunity.

**Comment by yjbanov** [comment]
Also, something tells me that StageXL isn't decoding 120k images every frame. It probably creates a limited number of images and then renders multiple instances of them. Hard to say without seeing the source code. If I apply this to the Flutter sample, I can go up to 5000 sprites at 60fps.

**Comment by yjbanov** [comment]
@ta9ki what are the hardware specs of the machine you are using for benchmarking? I can confirm that on a GTX 1070 (a fairly powerful discrete GPU) I can go up to 100k before I start losing frames in the stagexl sample. However, on a macbook with Intel Iris embedded GPU I start losing frames at around 10k.

**Comment by yjbanov** [comment]
The Skia team just taught me how to do this with high performance. The trick is to batch all sprites into a single `drawAtlas` call. With that I was able to get almost to the stagexl level.

Code: https://gist.github.com/yjbanov/1d239dbf0aebf34f7784660b1bdc6d38
Example: https://yjbanov.web.app/sprites/ ([profile build](https://yjbanov.web.app/sprites-profile/))

I'm going to consider this issue as fixed.
