### ISSUE TITLE
[google_maps_flutter] Release Build Crash in Google Play Pre-Launch Test 

### ISSUE THREAD

**Issue by stumcdonald70** [flutter/flutter#74902]
## Steps to Reproduce

1. Create new Project
2. Copy google_maps_flutter example main.dart and minimum configuration requirements
3. Build Release and test on Google Play Console Pre-Launch Test

**Expected results:**
Sample google map displayed with onPressed FAB cameraUpdate success.

**Actual results:**
Map and Floating action button loads as expected on all devices, however, 4 of 6 devices immediately crash.

<details>
  <summary>java.lang.StackOverflowError: stack size 1041KB</summary>

Crash log for Device 1
```
FATAL EXCEPTION: Thread-2
Process: androidx.test.tools.crawler.stubapp, PID: 15380
java.lang.StackOverflowError: stack size 1041KB
	at android.view.accessibility.AccessibilityNodeInfo.canPerformRequestOverConnection(AccessibilityNodeInfo.java:3769)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:971)
	at android.support.test.uiautomator.e.f(ByMatcher.java:7)
	at android.support.test.uiautomator.e.f(ByMatcher.java:10)
```

Crash log for Device 2
```
FATAL EXCEPTION: Thread-5
Process: androidx.test.tools.crawler.stubapp, PID: 7643
java.lang.StackOverflowError: stack size 1037KB
	at android.support.test.uiautomator.b.<init>(Unknown Source:5)
	at android.support.test.uiautomator.d.iterator(ByMatcher.java:1)
	at android.support.test.uiautomator.e.f(ByMatcher.java:2)
	at android.support.test.uiautomator.e.f(ByMatcher.java:10)
```

Crash log for Device 3
```
FATAL EXCEPTION: Thread-2
Process: androidx.test.tools.crawler.stubapp, PID: 17454
java.lang.StackOverflowError: stack size 1038KB
	at android.util.SparseArray.get(SparseArray.java:104)
	at android.view.accessibility.AccessibilityInteractionClient.getConnection(AccessibilityInteractionClient.java:748)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:269)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:965)
	at android.support.test.uiautomator.e.f(ByMatcher.java:7)
	at android.support.test.uiautomator.e.f(ByMatcher.java:10)
```

Crash log for Device 4
```
FATAL EXCEPTION: Thread-1870
Process: androidx.test.tools.crawler.stubapp, PID: 30136
java.lang.StackOverflowError: stack size 1036KB
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:2411)
	at android.view.accessibility.AccessibilityNodeInfo.obtain(AccessibilityNodeInfo.java:2424)
	at android.view.accessibility.AccessibilityCache.getNode(AccessibilityCache.java:154)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:276)
	at android.view.accessibility.AccessibilityNodeInfo.getChild(AccessibilityNodeInfo.java:781)
	at android.support.test.uiautomator.e.f(ByMatcher.java:7)
	at android.support.test.uiautomator.e.f(ByMatcher.java:10)
```

While only able to test on Google Play Console, this is the flutter doctor -v on local.
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/Company/Development/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/Company/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

 
[✓] Connected device (1 available)            
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@stumcdonald70 
After doing a bit of research on Google Play Pre-Launch test tool, I came to know few things and they are:

1. Google Play Pre-Launch test is powered by Firebase Test Lab which uses RoboTesting to test apps. The Robotesting framework doesn't yet support Flutter apps since it uses OpenGL that is incompatible with RoboTests.

2. The devices on which the tests are run during Pre-Launch test may not have `accessibility` enabled or even not support `UIAutomator`, and hence when the RoboTests run, it may be looking for these aspects and since it couldn't find them, leads to test failure or even crash. Hence, you could be seeing the crashes related to `UiAutomator` and `AccessibilityNodes`  and `AccessibilityInteraction`.

In short, the tool you are using `Google Play Pre-Launch` isn't fully supported for Flutter apps and hence crashes like these are expected.  See this issue for example, https://github.com/flutter/flutter/issues/32062 and https://github.com/flutter/flutter/issues/35341

There's also a similar crash using `google_maps_flutter` and `UiAutomator` which could be related https://github.com/flutter/flutter/issues/74197 that matches one of your crash listed.

I am going ahead and closing this, since the crashes you reported are not an issue from Flutter framework or plugin side, but due to limited or no support for Flutter apps on Google Play Pre-Launch tool. I'd suggest you to open or check if there's relevant issue reported in the tool repo and follow-up there for updates.
