### ISSUE TITLE
didChangeAppLifecycleState no longer works

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#74900]
## Steps to Reproduce

Implement `didChangeAppLifecycleState` as shown in the [documentation](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html).

For example
```
class DashboardScreenState extends State<DashboardScreen> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print('TEST');
  }
}
```

**Expected results:** 
`didChangeAppLifecycleState` should be called when the app goes in the background or foreground.

**Actual results:**
`didChangeAppLifecycleState` is not called

This was tested on both Android and iOS. Nothing happens, except on iOS it throws errors when going into background.
These errors do not occur on Android.

```
NoSuchMethodError: The method 'didHaveMemoryPressure' was called on null.
Receiver: null
Tried calling: didHaveMemoryPressure()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      WidgetsBinding.handleMemoryPressure (package:flutter/src/widgets/binding.dart:697:16)
#2      ServicesBinding.handleSystemMessage (package:flutter/src/services/binding.dart:78:9)
#3      PaintingBinding.handleSystemMessage (package:flutter/src/painting/binding.dart:132:17)
#4      ServicesBinding.initInstances.<anonymous closure> (package:flutter/src/services/binding.dart:33:66)
#5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:47)
#7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
#8      <…>
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'didChangePlatformBrightness' was called on null.
Receiver: null
Tried calling: didChangePlatformBrightness()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      WidgetsBinding.handlePlatformBrightnessChanged (package:flutter/src/widgets/binding.dart:571:16)
#2      _rootRun (dart:async/zone.dart:1186:13)
#3      _CustomZone.run (dart:async/zone.dart:1090:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:994:7)
#5      _invoke (dart:ui/hooks.dart:157:10)
#6      PlatformDispatcher._updateUserSettingsData (dart:ui/platform_dispatcher.dart:765:7)
#7      _updateUserSettingsData (dart:ui/hooks.dart:66:31)
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'didChangeMetrics' was called on null.
Receiver: null
Tried calling: didChangeMetrics()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      WidgetsBinding.handleMetricsChanged (package:flutter/src/widgets/binding.dart:557:16)
#2      _rootRun (dart:async/zone.dart:1186:13)
#3      _CustomZone.run (dart:async/zone.dart:1090:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:994:7)
#5      _invoke (dart:ui/hooks.dart:157:10)
#6      PlatformDispatcher._updateWindowMetrics (dart:ui/platform_dispatcher.dart:208:5)
#7      _updateWindowMetrics (dart:ui/hooks.dart:31:31)
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'didChangeMetrics' was called on null.
Receiver: null
Tried calling: didChangeMetrics()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      WidgetsBinding.handleMetricsChanged (package:flutter/src/widgets/binding.dart:557:16)
#2      _rootRun (dart:async/zone.dart:1186:13)
#3      _CustomZone.run (dart:async/zone.dart:1090:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:994:7)
#5      _invoke (dart:ui/hooks.dart:157:10)
#6      PlatformDispatcher._updateWindowMetrics (dart:ui/platform_dispatcher.dart:208:5)
#7      _updateWindowMetrics (dart:ui/hooks.dart:31:31)
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'didChangePlatformBrightness' was called on null.
Receiver: null
Tried calling: didChangePlatformBrightness()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      WidgetsBinding.handlePlatformBrightnessChanged (package:flutter/src/widgets/binding.dart:571:16)
#2      _rootRun (dart:async/zone.dart:1186:13)
#3      _CustomZone.run (dart:async/zone.dart:1090:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:994:7)
#5      _invoke (dart:ui/hooks.dart:157:10)
#6      PlatformDispatcher._updateUserSettingsData (dart:ui/platform_dispatcher.dart:765:7)
#7      _updateUserSettingsData (dart:ui/hooks.dart:66:31)
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'didChangeMetrics' was called on null.
Receiver: null
Tried calling: didChangeMetrics()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      WidgetsBinding.handleMetricsChanged (package:flutter/src/widgets/binding.dart:557:16)
#2      _rootRun (dart:async/zone.dart:1186:13)
#3      _CustomZone.run (dart:async/zone.dart:1090:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:994:7)
#5      _invoke (dart:ui/hooks.dart:157:10)
#6      PlatformDispatcher._updateWindowMetrics (dart:ui/platform_dispatcher.dart:208:5)
#7      _updateWindowMetrics (dart:ui/hooks.dart:31:31)
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'didChangeMetrics' was called on null.
Receiver: null
Tried calling: didChangeMetrics()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      WidgetsBinding.handleMetricsChanged (package:flutter/src/widgets/binding.dart:557:16)
#2      _rootRun (dart:async/zone.dart:1186:13)
#3      _CustomZone.run (dart:async/zone.dart:1090:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:994:7)
#5      _invoke (dart:ui/hooks.dart:157:10)
#6      PlatformDispatcher._updateWindowMetrics (dart:ui/platform_dispatcher.dart:208:5)
#7      _updateWindowMetrics (dart:ui/hooks.dart:31:31)
flutter: Another exception was thrown: NoSuchMethodError: The method 'didHaveMemoryPressure' was called on null.

```

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.0.1 20B50 darwin-x64,
    locale en-GB)
    • Flutter version 1.25.0-8.3.pre at
      /Users/glennruysschaert/development/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86    • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 9D7FA474-C506-4BBB-AB84-AC77E6662FCB
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

**Comment by nt4f04uNd** [comment]
you don't need to WidgetsBinding.instance.addObserver(this) on state

**Comment by darshankawar** [comment]
@vixez 
Can you check out [this](https://github.com/flutter/flutter/issues/73947) issue and see if it resemble yours ?

**Comment by vixez** [comment]
@darshankawar It is similar, but there it seems it sometimes works and the iOS version doesn't throw those errors.
So it looks like mine is a worse version of that issue.

Thing is, it used to work fine, I didn't change any code relating to that. So I think in one of the beta builds it broke.

**Comment by darshankawar** [comment]
@vixez 
Tried your code sample on latest beta, master and stable and was able to see `TEST` being printed upon sending app to background or calling it to foreground.  (Verified on Pixel 3XL emulator and iPhone 12 pro max simulator).  Below are the logs for each version:

```
Stable : Android

D/eglCodecCommon(24139): setVertexArrayObject: set vao to 0 (0) 20 0
I/flutter (24139): TEST
D/EGL_emulation(24139): eglMakeCurrent: 0xde205760: ver 3 0 (tinfo 0xcd0ffa00)
I/flutter (24139): TEST


Stable: iOS

Waiting for iPhone 12 Pro Max to report its views...
Debug service listening on ws://127.0.0.1:63701/NOFY5BoPmOM=/ws
Syncing files to device iPhone 12 Pro Max...
flutter: TEST
flutter: TEST
flutter: TEST
flutter: TEST

Master: Android

I/flutter (25928): TEST
D/EGL_emulation(25928): eglMakeCurrent: 0xde205dc0: ver 3 0 (tinfo 0xde1aeaf0)
I/flutter (25928): TEST
I/flutter (25928): TEST
D/EGL_emulation(25928): eglMakeCurrent: 0xde205760: ver 3 0 (tinfo 0xde1ae460)
D/EGL_emulation(25928): eglMakeCurrent: 0xde205dc0: ver 3 0 (tinfo 0xde1aeaf0)
D/EGL_emulation(25928): eglMakeCurrent: 0xde205760: ver 3 0 (tinfo 0xde1ae460)



Master: iOS

Syncing files to device iPhone 12 Pro Max...
flutter: TEST
flutter: TEST
flutter: TEST
flutter: TEST


Beta: Android:

I/flutter (26574): TEST
D/EGL_emulation(26574): eglMakeCurrent: 0xdfc05780: ver 3 0 (tinfo 0xca12a020)
I/flutter (26574): TEST
I/flutter (26574): TEST

Beta: iOS:

Syncing files to device iPhone 12 Pro Max...
flutter: TEST
flutter: TEST
flutter: TEST
flutter: TEST


```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.3.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • AOSP on IA Emulator (mobile) • emulator-5554    • android-x86    • Android
      9 (API 28) (emulator)
    • Chrome (web)                 • chrome           • web-javascript • Google
      Chrome 88.0.4324.96

• No issues found!


```

</details>

**Comment by vixez** [comment]
Hello,

I've did some more tests and it seems it's a third party SDK (Notificare) that's causing the issues.
So it's not a Flutter issue.

Thank you anyway
