### ISSUE TITLE
[tool_crash] StateError: Bad state: Existing VM service clients prevent DDS from taking control.

### ISSUE THREAD

**Issue by Rajkumar07793** [flutter/flutter#75008]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=32004423b8d27511 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Existing VM service clients prevent DDS from taking control.
```
#0      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:83:11)
<asynchronous suspension>
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:249:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.296, on Microsoft Windows [Version 10.0.19042.746], locale en-IN)
    • Flutter version 1.26.0-2.0.pre.296 at D:\flutter
    • Framework revision 737496e8db (2 weeks ago), 2021-01-12 02:54:03 -0500
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Rajkumar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at D:\ideaIC-2020.2.2.win
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] Connected device (3 available)
    • SM J600G (mobile) • 32004423b8d27511 • android-arm    • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 876c313784b9e2cedb9069b908c85f68abceb5a1
### Plugins
file_picker-2.1.5+1
flutter_plugin_android_lifecycle-1.0.11
fluttertoast-7.1.6
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
sqflite-1.3.2+2
webview_flutter-1.0.7

**Comment by bkonyi** [comment]
This has been resolved in the next Flutter release. Thanks for reporting!
