### ISSUE TITLE
Webview app crash on clicking links that open in newtab ( HTML target="_blank")

### ISSUE THREAD

**Issue by maheshmnj** [flutter/flutter#75066]
Hello Flutter devs,

I am trying to click on links in the webview which basically open in new tab and I see the app crashes on clicking such links.
I see similar issues being reported  
- https://github.com/flutter/flutter/issues/58229 [Closed]
- https://github.com/flutter/flutter/issues/62022 [Closed]
- https://github.com/flutter/flutter/issues/74412 [Open]

 the issue seems to be there still with latest version of the [webview_flutter](https://pub.dev/packages/webview_flutter) 
Here is a piece of sample code to try

## Sample code 
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class Webview extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WebView(
      initialUrl: 'https://www.w3schools.com/tags/att_a_target.asp',
    );
  }
}
```
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add latest  version of ``` webview_flutter: ^1.0.7```
3. Add the piece of code to the widget tree
4. Render the webview widget 
5. Click on the green button in the webview which says ```Try it yourself``` (Which basically opens the link in new tab)
6. You will see the app crashing.

## Console Logs
```
mplat(21473): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_LibraryLoader(21473): Loaded native library version number "88.0.4324.93"
I/cr_CachingUmaRecorder(21473): Flushed 4 samples from 4 histograms.
W/chromium(21473): [WARNING:dns_config_service_posix.cc(342)] Failed to read DnsConfig.
D/EgretLoader(21473): EgretLoader(Context context)
D/EgretLoader(21473): The context is not activity
W/lutter_templat(21473): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(21473): Requires BLUETOOTH permission
W/ContentCatcher(21473): Failed to notify a WebView
D/EgretLoader(21473): EgretLoader(Context context)
D/EgretLoader(21473): The context is not activity
E/InputMethodManager(21473): b/117267690: Failed to get fallback IMM with expected displayId=56 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{f0f387e VFEDHVC.. .F...... 0,0-1080,2340}
D/AndroidRuntime(21473): Shutting down VM
E/AndroidRuntime(21473): FATAL EXCEPTION: main
E/AndroidRuntime(21473): Process: com.example.flutter_template, PID: 21473
E/AndroidRuntime(21473): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime(21473): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1625)
E/AndroidRuntime(21473): 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1869)
E/AndroidRuntime(21473): 	at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1183)
E/AndroidRuntime(21473): 	at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:188)
E/AndroidRuntime(21473): 	at android.os.Handler.handleCallback(Handler.java:914)
E/AndroidRuntime(21473): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(21473): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(21473): 	at android.app.ActivityThread.main(ActivityThread.java:7560)
E/AndroidRuntime(21473): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21473): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(21473): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process (21473): Sending signal. PID: 21473 SIG: 9
Lost connection to device.

```

I tried this on the stable channel 1.22.5 as well as the master channel.
Heres the output of ```flutter doctor -v``` on the  master channel
```
 [✓] Flutter (Channel master, 1.26.0-13.0.pre.14, on macOS 11.1 20C69 darwin-arm, locale en-IN)
    • Flutter version 1.26.0-13.0.pre.14 at /Users/mahesh/Documents/flutter
    • Framework revision b7f6d9bcb2 (2 weeks ago), 2021-01-15 07:44:03 -0500
    • Engine revision 69a7538a90
    • Dart version 2.12.0 (build 2.12.0-227.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.1xx.xxx.xxxx• android-arm64  • Android 10 (API 29)
    • macOS (desktop)        • macos               • darwin-arm64   • macOS 11.1 20C69 darwin-arm
    • Chrome (web)           • chrome              • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

Let me know in case you need any additional info.

**Comment by TahaTesser** [comment]
Hi @maheshmnj 
You need to use [hybrid composition](https://pub.dev/packages/webview_flutter#using-hybrid-composition) to make this work 

Add the following in your code
```dart
  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }
```

Closing, as this isn't an issue with `webview` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by ksatoudeveloper** [comment]
Would you please write `You need to use hybrid composition to make this work` in the README.md ?

https://github.com/flutter/plugins/blob/master/packages/webview_flutter/README.md#android-platform-views

**Comment by maheshmnj** [comment]
I am  just trying to understand should'nt this hybrid composition thing enabled by default in webview, considering there's a high chance that every webpage has links that open in newtab.

**Comment by TahaTesser** [comment]
@ksatoudeveloper 
For this case, it makes sense to use hybrid composition,  you should have no problem following the README and test official sample, which has hybrid enabled 
Thank you

**Comment by ksatoudeveloper** [comment]
@TahaTesser 

It works but it is not documented properly.
Would you please insert "When blank link is required we recommend to use the Hybrid Composition" in the README?
The README only mentions the keyboard.
