### ISSUE TITLE
Problem with installing flutter on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by ahmeddrawy** [flutter/flutter#75084]
## Steps to Reproduce

I have an issue when running 
`flutter doctor`, 
I get

>     ✗ Android license status unknown.
### when I run 
` flutter doctor --android-licenses
`
I get
> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

### when I run 

`java -version` I get 
>openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

<details>
<summary>Logs</summary>

### running `flutter --verbose create foo`
```
[ +110 ms] executing: [/home/tw3/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[        ] executing: [/home/tw3/snap/flutter/common/flutter/] git tag --points-at HEAD
[  +10 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.6
[   +6 ms] executing: [/home/tw3/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/tw3/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +34 ms] executing: [/home/tw3/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +54 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +64 ms] Creating project foo...
[  +85 ms]   foo/foo.iml (created)
[   +8 ms]   foo/.idea/modules.xml (created)
[   +7 ms]   foo/.idea/libraries/KotlinJavaRuntime.xml (created)
[   +1 ms]   foo/.idea/libraries/Dart_SDK.xml (created)
[   +1 ms]   foo/.idea/runConfigurations/main_dart.xml (created)
[        ]   foo/.idea/workspace.xml (created)
[   +1 ms]   foo/ios/Runner.xcodeproj/project.pbxproj (created)
[   +9 ms]   foo/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
[   +1 ms]   foo/ios/Runner/AppDelegate.swift (created)
[        ]   foo/ios/Runner/Runner-Bridging-Header.h (created)
[        ]   foo/.metadata (created)
[        ]   foo/README.md (created)
[   +1 ms]   foo/.gitignore (created)
[        ]   foo/ios/Flutter/Release.xcconfig (created)
[   +1 ms]   foo/ios/Flutter/AppFrameworkInfo.plist (created)
[        ]   foo/ios/Flutter/Debug.xcconfig (created)
[        ]   foo/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
[        ]   foo/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
[        ]   foo/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
[        ]   foo/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (existing - skipped)
[        ]   foo/ios/.gitignore (created)
[        ]   foo/ios/Runner/Info.plist (created)
[        ]   foo/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
[        ]   foo/ios/Runner/Base.lproj/Main.storyboard (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
[        ]   foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
[        ]   foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
[        ]   foo/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
[        ]   foo/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
[        ]   foo/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
[        ]   foo/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
[        ]   foo/android/foo_android.iml (created)
[        ]   foo/android/build.gradle (created)
[        ]   foo/android/app/src/main/kotlin/com/example/foo/MainActivity.kt (created)
[        ]   foo/android/app/build.gradle (created)
[        ]   foo/android/gradle/wrapper/gradle-wrapper.properties (created)
[        ]   foo/android/gradle.properties (created)
[        ]   foo/android/.gitignore (created)
[        ]   foo/android/settings.gradle (created)
[        ]   foo/android/app/src/profile/AndroidManifest.xml (created)
[        ]   foo/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
[        ]   foo/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
[        ]   foo/android/app/src/main/res/values/styles.xml (created)
[        ]   foo/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
[        ]   foo/android/app/src/main/res/drawable/launch_background.xml (created)
[        ]   foo/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
[        ]   foo/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
[        ]   foo/android/app/src/main/AndroidManifest.xml (created)
[        ]   foo/android/app/src/debug/AndroidManifest.xml (created)
[        ]   foo/lib/main.dart (created)
[   +3 ms]   foo/pubspec.yaml (created)
[   +1 ms]   foo/test/widget_test.dart (created)
[  +42 ms] Running "flutter pub get" in foo...
[   +3 ms] Using /home/tw3/snap/flutter/common/flutter/.pub-cache for the pub cache.
[   +1 ms] executing: [/home/tw3/Desktop/side-projects/flutter/foo/] /home/tw3/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +71 ms] MSG : Resolving dependencies...
[   +7 ms] MSG : + async 2.5.0-nullsafety.1 (2.5.0-nullsafety.3 available)
[        ]     | + boolean_selector 2.1.0-nullsafety.1 (2.1.0-nullsafety.3 available)
[        ]     | + characters 1.1.0-nullsafety.3 (1.1.0-nullsafety.5 available)
[        ]     | + charcode 1.2.0-nullsafety.1 (1.2.0-nullsafety.3 available)
[        ]     | + clock 1.1.0-nullsafety.1 (1.1.0-nullsafety.3 available)
[        ]     | + collection 1.15.0-nullsafety.3 (1.15.0-nullsafety.5 available)
[        ]     | + cupertino_icons 1.0.0 (1.0.2 available)
[        ]     | + fake_async 1.2.0-nullsafety.1 (1.2.0-nullsafety.3 available)
[        ]     | + flutter 0.0.0 from sdk flutter
[        ]     | + flutter_test 0.0.0 from sdk flutter
[        ]     | + matcher 0.12.10-nullsafety.1 (0.12.10-nullsafety.3 available)
[        ]     | + meta 1.3.0-nullsafety.3 (1.3.0-nullsafety.6 available)
[        ]     | + path 1.8.0-nullsafety.1 (1.8.0-nullsafety.3 available)
[        ]     | + sky_engine 0.0.99 from sdk flutter
[        ]     | + source_span 1.8.0-nullsafety.2 (1.8.0-nullsafety.4 available)
[        ]     | + stack_trace 1.10.0-nullsafety.1 (1.10.0-nullsafety.6 available)
[        ]     | + stream_channel 2.1.0-nullsafety.1 (2.1.0-nullsafety.3 available)
[        ]     | + string_scanner 1.1.0-nullsafety.1 (1.1.0-nullsafety.3 available)
[        ]     | + term_glyph 1.2.0-nullsafety.1 (1.2.0-nullsafety.3 available)
[        ]     | + test_api 0.2.19-nullsafety.2 (0.2.19-nullsafety.6 available)
[        ]     | + typed_data 1.3.0-nullsafety.3 (1.3.0-nullsafety.5 available)
[        ]     | + vector_math 2.1.0-nullsafety.3 (2.1.0-nullsafety.5 available)
[   +1 ms] MSG : Changed 22 dependencies!
[  +15 ms] Running "flutter pub get" in foo... (completed in 2.9s)
[ +162 ms] Generating /home/tw3/Desktop/side-projects/flutter/foo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +5 ms] Wrote 71 files.
[        ] 
           All done!
[  +20 ms] executing: [/home/tw3/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 8 days ago
[   +9 ms] executing: /home/tw3/snap/flutter/common/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[   +4 ms] Exit code 255 from: /home/tw3/snap/flutter/common/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[        ] At least one input is required
           Usage: gen_snapshot [<vm-flags>] [<options>] <dart-kernel-file>             

           Common options:                                                             
           --help                                                                      
             Display this message (add --verbose for information about all VM options).
           --version                                                                   
             Print the SDK version.                                                    

           To create a core snapshot:                                                  
           --snapshot_kind=core                                                        
           --vm_snapshot_data=<output-file>                                            
           --isolate_snapshot_data=<output-file>                                       
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as assembly suitable for compilation  
           as a static or dynamic library:                                             
           --snapshot_kind=app-aot-assembly                                            
           --assembly=<output-file>                                                    
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-debugging-info=<debug-filename>]                                    
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as an ELF shared library:             
           --snapshot_kind=app-aot-elf                                                 
           --elf=<output-file>                                                         
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-debugging-info=<debug-filename>]                                    
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           AOT snapshots can be obfuscated: that is all identifiers will be renamed    
           during compilation. This mode is enabled with --obfuscate flag. Mapping     
           between original and obfuscated names can be serialized as a JSON array     
           using --save-obfuscation-map=<filename> option. See dartbug.com/30524       
           for implementation details and limitations of the obfuscation pass.
[  +11 ms] java -version
[  +77 ms] executing: /home/tw3/Android/Sdk/tools/bin/sdkmanager --licenses
[ +116 ms] executing: /home/tw3/Android/Sdk/platform-tools/adb devices -l
[   +9 ms] List of devices attached
[   +6 ms] executing: /home/tw3/Android/Sdk/platform-tools/adb devices -l
[   +5 ms] List of devices attached
[   +1 ms] [✓] Flutter: is fully installed. (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
           [!] Android toolchain - develop for Android devices: is partially installed; more components are available. (Android SDK version 30.0.3)
           [!] Android Studio: is not available. (not installed)
           [!] Connected device: is not available.

           Run "flutter doctor" for information about installing additional components.

[        ] In order to run your application, type:

             $ cd foo
             $ flutter run

           Your application code is in foo/lib/main.dart.

[   +1 ms] "flutter create" took 3,662ms.
[ +257 ms] ensureAnalyticsSent: 254ms
[   +6 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

### running `flutter doctor -v`
```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /home/tw3/snap/flutter/common/flutter
    • Framework revision 9b2d32b605 (8 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/tw3/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

</details>

**Comment by qwert2603** [comment]
Hello! You can try to set `ANDROID_HOME` to `~/Android/Sdk` (or other location where you have Android SDK installed).

**Comment by ahmeddrawy** [comment]
> Hello! You can try to set `ANDROID_HOME` to `~/Android/Sdk` (or other location where you have Android SDK installed).

I set `export ANDROID_HOME="~/Andriod/Sdk"` in my `.bashrc`, but I have the same error @qwert2603

**Comment by qwert2603** [comment]
So, do you have `JAVA_HOME` settled correctly?
I've checked on my machine now -- `java -version` gives correct output, thougt `echo $JAVA_HOME` prints nothing.

**Comment by ahmeddrawy** [comment]
My bad I use **zsh** so I had to set the ANDROID_HOME in `.zshenv`, now I set it and  I have this ouput from 'flutter doctor -v'

> [✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.22.6 at /home/tw3/snap/flutter/common/flutter
>     • Framework revision 9b2d32b605 (9 days ago), 2021-01-22 14:36:39 -0800
>     • Engine revision 2f0af37152
>     • Dart version 2.10.5
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ ANDROID_HOME = ~/Android/Sdk/
>       but Android SDK not found at this location.
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from
>       https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
>       for detailed instructions).
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 3 categories.
>

**Comment by ahmeddrawy** [comment]
I update the path to be absolute and I ran `flutter doctor -v`

> [✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.22.6 at /home/tw3/snap/flutter/common/flutter
>     • Framework revision 9b2d32b605 (9 days ago), 2021-01-22 14:36:39 -0800
>     • Engine revision 2f0af37152
>     • Dart version 2.10.5
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /home/tw3/Android/Sdk
>     • Platform android-30, build-tools 30.0.3
>     • ANDROID_HOME = /home/tw3/Android/Sdk
>     • Java binary at: /usr/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
> 
> [!] Connected device
>     ! No devices available


### when I run `flutter doctor --android-licenses`

I get the same output as 

> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

**Comment by ahmeddrawy** [comment]
I fixed this problem by changing my java to java 8 using this command

>`~$ sudo update-alternatives --config java`

and choosing `java 8`, If you don't have it on your machine you can install it by 

> `sudo apt-get install openjdk-8-jre`

then running 

> `flutter doctor --android-licenses`
it will prompt to 
>`to accept press y/N?`
it's obvious that `No` is the default, so you have to explicitly write 'y' in the terminal and hit `enter`
