### ISSUE TITLE
Spaces in Asset Paths are double encoded in Flutter Web and result in 404

### ISSUE THREAD

**Issue by jonaird** [flutter/flutter#75220]
## Steps to Reproduce

I found this on the latest Beta release 

1. Run `flutter create bug`.
2. Create assets folder with a test file that includes a space in the name.
3. Try to load the assets in Flutter Web.

```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: Scaffold(body: EmptyWidget())));
}

class EmptyWidget extends StatefulWidget {
  @override
  _EmptyWidgetState createState() => _EmptyWidgetState();
}

class _EmptyWidgetState extends State<EmptyWidget> {
  String str = 'waiting...';
  @override
  Widget build(BuildContext context) {
    DefaultAssetBundle.of(context)
        .loadString('test file.txt')
        .then((value) => setState(() => str = value));
    return Text(str);
  }
}
```

**Expected results:** 

Expected to be able to load the asset.

**Actual results:** 
Throws an error when there is a space in the name of the asset. The error shows that the space has been double encoded as `%2520` rather than what it should be `%20`:

```
Error while trying to load an asset: Failed to load asset at "assets/test%2520file.txt" (404)
```

<details>
  <summary>Logs</summary>

```
flutter run --verbose
[  +97 ms] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +86 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[   +1 ms] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git tag --points-at
5d36f2e7f5387b6c751449258ade8e4e6edf99be
[  +86 ms] Exit code 0 from: git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] 1.25.0-8.3.pre
[  +77 ms] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git ls-remote --get-url
origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +76 ms] Unable to locate an Android SDK.
[   +9 ms] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git rev-parse
--abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] beta
[  +15 ms] executing: sw_vers -productName
[  +66 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +23 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 11.1
[        ] executing: sw_vers -buildVersion
[  +43 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20C69
[  +17 ms] executing: sysctl hw.optional.arm64
[  +38 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +150 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +140 ms] executing: /usr/bin/xcode-select --print-path
[  +11 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[  +16 ms] executing: sysctl hw.optional.arm64
[  +11 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[  +15 ms] Exit code 72 from: xcrun xcodebuild -version
[   +2 ms] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[   +2 ms] Xcode not found. Run 'flutter doctor' for more information.
[   +4 ms] executing: xcrun xcodebuild -version
[   +9 ms] Exit code 72 from: xcrun xcodebuild -version
[   +3 ms] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[  +28 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] executing: xcrun xcodebuild -version
[  +10 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[ +110 ms] Skipping pub get: version match.
[ +143 ms] Found plugin integration_test at /Users/jonathanaird/Developer/Flutter
sdk/flutter/packages/integration_test/
[ +185 ms] Found plugin integration_test at /Users/jonathanaird/Developer/Flutter
sdk/flutter/packages/integration_test/
[  +10 ms] Generating
/Users/jonathanaird/Developer/temp/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPlugin
Registrant.java
[  +27 ms] executing: xcrun xcodebuild -version
[  +11 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[ +771 ms] Launching lib/main.dart on Chrome in debug mode...
[ +129 ms] Updating assets
[ +261 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force
rerun. for more information see #56466.
[   +8 ms] Waiting for connection from debug service on Chrome...
[  +83 ms] Found plugin integration_test at /Users/jonathanaird/Developer/Flutter
sdk/flutter/packages/integration_test/
[  +62 ms] Found plugin integration_test at /Users/jonathanaird/Developer/Flutter
sdk/flutter/packages/integration_test/
[+1089 ms] <- reset
[  +23 ms] /Users/jonathanaird/developer/flutter sdk/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev /Users/jonathanaird/developer/flutter
sdk/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/jonathanaird/developer/flutter sdk/flutter/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata --output-dill
/var/folders/6h/ch5qgxw90r99kmpgcvpvlc8h0000gn/T/flutter_tools.7jnc0E/flutter_tool.bmiRAR/app.dill
--libraries-spec
file:///Users/jonathanaird/developer/flutter%20sdk/flutter/bin/cache/flutter_web_sdk/libraries.json
--packages /Users/jonathanaird/Developer/temp/bug/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root
/var/folders/6h/ch5qgxw90r99kmpgcvpvlc8h0000gn/T/flutter_tools.7jnc0E/flutter_tools.JOz7N5
--filesystem-scheme org-dartlang-app --initialize-from-dill
build/fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform
file:///Users/jonathanaird/developer/flutter%20sdk/flutter/bin/cache/flutter_web_sdk/kernel/flutter
_ddc_sdk.dill --no-sound-null-safety
[  +33 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+23038 ms] Waiting for connection from debug service on Chrome... (completed in 24.3s)
[   +1 ms] Synced 28.7MB.
[        ] <- accept
[        ] Caching compiled dill
[ +334 ms] Using Google Chrome 88.0.4324.96 

[+3089 ms] [CHROME]:
[   +5 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:59947/devtools/browser/7ddecc27-0a73-40aa-9b8b-2b8f9b898ff0
[+1445 ms] DwdsInjector: Received request for entrypoint at
http://localhost:59943/main_module.bootstrap.js
[  +12 ms] MetadataProvider: Loading debug metadata...
[  +15 ms] MetadataProvider: Loaded debug metadata
[  +10 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:59943/main_module.bootstrap.js
[+4029 ms] DevHandler: Debug service listening on ws://127.0.0.1:59965/OhPPmqNkH2Q=/ws

[  +19 ms] Debug service listening on ws://127.0.0.1:59965/OhPPmqNkH2Q=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[  +18 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[  +20 ms] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +2 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +9 ms] For a more detailed help message, press "h". To quit, press "q".
[+1245 ms] Error while trying to load an asset: Failed to load asset at "assets/test%2520file.txt"
(404)
[  +11 ms] Error: Unable to load asset: test file.txt
               at Object.throw_ [as throw] (http://localhost:59943/dart_sdk.js:4361:11)
               at load

(http://localhost:59943/packages/flutter/src/services/system_channels.dart.lib.js:2446:38)
               at load.next (<anonymous>)
               at http://localhost:59943/dart_sdk.js:38007:33
               at _RootZone.runUnary (http://localhost:59943/dart_sdk.js:37861:58)
               at _FutureListener.thenAwait.handleValue
(http://localhost:59943/dart_sdk.js:32822:29)
               at handleValueCallback (http://localhost:59943/dart_sdk.js:33370:49)
               at Function._propagateToListeners (http://localhost:59943/dart_sdk.js:33408:17)
               at _Future.new.[_completeWithValue] (http://localhost:59943/dart_sdk.js:33250:23)
               at async._AsyncCallbackEntry.new.callback
(http://localhost:59943/dart_sdk.js:33273:35)
               at Object._microtaskLoop (http://localhost:59943/dart_sdk.js:38122:13)
               at _startMicrotaskLoop (http://localhost:59943/dart_sdk.js:38128:13)
               at http://localhost:59943/dart_sdk.js:33625:9
```

</details>

**Comment by darshankawar** [comment]
Issue replicable on latest master as well.

<details>
<summary> Console error log </summary>

```
Error while trying to load an asset: Failed to load asset at "assets/triage%2520test.txt" (404)
Error: Unable to load asset: triage test.txt
    at Object.throw_ [as throw] (http://localhost:52490/dart_sdk.js:5348:11)
    at load (http://localhost:52490/packages/flutter/src/services/system_channels.dart.lib.js:2468:38)
    at load.next (<anonymous>)
    at http://localhost:52490/dart_sdk.js:39163:33
    at _RootZone.runUnary (http://localhost:52490/dart_sdk.js:39020:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:52490/dart_sdk.js:34006:29)
    at handleValueCallback (http://localhost:52490/dart_sdk.js:34566:49)
    at Function._propagateToListeners (http://localhost:52490/dart_sdk.js:34604:17)
    at _Future.new.[_completeWithValue] (http://localhost:52490/dart_sdk.js:34446:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52490/dart_sdk.js:34469:35)
    at Object._microtaskLoop (http://localhost:52490/dart_sdk.js:39307:13)
    at _startMicrotaskLoop (http://localhost:52490/dart_sdk.js:39313:13)
    at http://localhost:52490/dart_sdk.js:34820:9



```

</details>

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.26.0-18.0.pre.121, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-18.0.pre.121 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 225e408d4f (7 hours ago), 2021-02-01 22:26:03 -0500
    • Engine revision e59457b818
    • Dart version 2.12.0 (build 2.12.0-279.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • AOSP on IA Emulator (mobile) • emulator-5554    • android-x86    • Android
      9 (API 28) (emulator)
    • macOS (desktop)              • macos            • darwin-x64     • Mac OS
      X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                 • chrome           • web-javascript • Google
      Chrome 88.0.4324.96

! Doctor found issues in 1 category.


```

</details>

**Comment by jonahwilliams** [comment]
I'm unaware of any recent changes

**Comment by hterkelsen** [comment]
We double-encode the asset URLs on purpose. This comment in the engine explains why:

```
  /// Returns the URL to load the asset from, given the asset key.
  ///
  /// We URL-encode the asset URL in order to correctly issue the right
  /// HTTP request to the server.
  ///
  /// For example, if you have an asset in the file "assets/hello world.png",
  /// two things will happen. When the app is built, the asset will be copied
  /// to an asset directory with the file name URL-encoded. So our asset will
  /// be copied to something like "assets/hello%20world.png". To account for
  /// the assets being copied over with a URL-encoded name, the Flutter
  /// framework URL-encodes the asset key  so when it sends a request to the
  /// engine to load "assets/hello world.png", it actually sends a request to
  /// load "assets/hello%20world.png". However, on the web, if we try to load
  /// "assets/hello%20world.png", the request will be URL-decoded, we will
  /// request "assets/hello world.png", and the request will 404. Therefore, we
  /// must URL-encode the asset key *again* so when it is decoded, it is
  /// requesting the once-URL-encoded asset key.
  ```

When I try to repro your issue, it works correctly when I declare the asset in my pubspec.yaml (see [this](https://flutter.dev/docs/development/ui/assets-and-images)). However, if I pass the wrong name for the asset then it actually loads the contents of `index.html`, which I'm pretty sure is due to how we serve the app.

@jonaird Do you still see this issue? Can you try declaring your asset in your pubspec file?

**Comment by jonaird** [comment]
I did some more testing. What seems to matter is if you include the asset path in the asset key (or maybe this is specific to the case of having assets in a folder called 'assets').

If you have an asset with no spaces in the name:
`assets/some-asset.json`
you can use either `some-asset.json` as the asset key OR `assets/some-asset.json`. 
 
On the other hand if your asset has a space:
`assets/some asset.json`
This key works: `assets/some asset.json` but this one doesn't: `some asset.json`. 
 
The docs specify that you should provide the relative path to the assets but it was confusing that I could sometimes just use the file name of the asset and it worked.

**Comment by huycozy** [comment]
I also see the same as the investigation at https://github.com/flutter/flutter/issues/75220#issuecomment-791904820 when verifying on the latest `stable` and `master` channels. 

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-13.0.pre.138, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-13.0.pre.138 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b938dc13df (16 hours ago), 2023-01-02 05:47:23 -0500
    • Engine revision 472e34cbbc
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by yjbanov** [comment]
Haven't heard anything about this recently. Closing as it's likely obsolete.
