### ISSUE TITLE
Notification.visitAncestor fails assertion: boolean expression must not be null 

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7522]
```
09:50:45.563: I/flutter (25389): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
09:50:45.568: I/flutter (25389): The following assertion was thrown during performLayout():
09:50:45.571: I/flutter (25389): Failed assertion: boolean expression must not be null
09:50:45.595: I/flutter (25389):
09:50:45.598: I/flutter (25389): Either the assertion indicates an error in the framework itself, or we should provide substantially
09:50:45.600: I/flutter (25389): more information in this error message to help you determine and fix the underlying cause.
09:50:45.603: I/flutter (25389): In either case, please report this assertion by filing a bug on GitHub:
09:50:45.605: I/flutter (25389):   https://github.com/flutter/flutter/issues/new
09:50:45.608: I/flutter (25389):
09:50:45.610: I/flutter (25389): When the exception was thrown, this was the stack:
09:50:45.613: I/flutter (25389): #0      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:22:18)
09:50:45.616: I/flutter (25389): #1      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:2561:39)
09:50:45.618: I/flutter (25389): #2      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:31:12)
09:50:45.621: I/flutter (25389): #3      SizeChangedLayoutNotifier.createRenderObject.<anonymous closure> (package:flutter/src/widgets/size_changed_layout_notifier.dart:36:45)
09:50:45.623: I/flutter (25389): #4      _RenderSizeChangedWithCallback.performLayout (package:flutter/src/widgets/size_changed_layout_notifier.dart:63:30)

```

**Comment by apwilson** [comment]
Looks like the issue is I wasn't returning anything in my onNotification callback.  Maybe the message should indicate that as a likely cause...  or assume a null means false.

**Comment by Hixie** [comment]
Ideally the analyzer would catch this, but yes, we should make the error message better in the meantime.

**Comment by zoechi** [comment]
Closing as dup of #16631 because there is more documentation.
