### ISSUE TITLE
[web]: Dragging the "draggable" widget causes widget to freeze in the overlay layer

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#75280]
**Steps to reproduce** by spamming right click during drag (one of two ways to see bug appear):
 - try to drag a widget with the left button but also tapping the right mouse button at the same time If the drag works as expected, reattempt the same drag until it the freeze happens, typically within about 10-20 attempts
 - When the widget freezes, and it’s in debug mode, an assert gets printed that comes from the flutter engine and gets printed in the console (see assert exception thrown below)

**Here is exception that throws in the flutter/dart engine:**
 
<details>
<summary>logs</summary>

```bash
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:449:18 
 
state.down
 
 
is not true
 
 
    at Object.throw_ [as throw] (http://localhost:59758/dart_sdk.js:5330:11)
 
 
    at Object.assertFailed (http://localhost:59758/dart_sdk.js:5266:15)
 
 
    at _engine.PointerDataConverter.new.convert (http://localhost:59758/dart_sdk.js:165537:46)
 
 
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:59758/dart_sdk.js:164956:36)
 
 
    at http://localhost:59758/dart_sdk.js:164891:44
 
 
    at http://localhost:59758/dart_sdk.js:164860:16
 
 
    at http://localhost:59758/dart_sdk.js:164559:11
 
 
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:449:18
 
 
state.down
 
 
is not true
 
 
    at Object.throw_ [as throw] (http://localhost:59758/dart_sdk.js:5330:11)
 
 
    at Object.assertFailed (http://localhost:59758/dart_sdk.js:5266:15)
 
 
    at _engine.PointerDataConverter.new.convert (http://localhost:59758/dart_sdk.js:165537:46)
 
 
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:59758/dart_sdk.js:164956:36)
 
 
    at http://localhost:59758/dart_sdk.js:164891:44
 
 
    at http://localhost:59758/dart_sdk.js:164860:16
 
 
    at http://localhost:59758/dart_sdk.js:164559:11
 
 
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:484:18
 
 
state.down
 
 
is not true
 
 
    at Object.throw_ [as throw] (http://localhost:59758/dart_sdk.js:5330:11)
 
 
    at Object.assertFailed (http://localhost:59758/dart_sdk.js:5266:15)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.156, on macOS 11.1 20C69
    darwin-x64, locale en-US)
    • Flutter version 1.26.0-13.0.pre.156 at
      /Users/halvorsen/Development/flutter
    • Framework revision 92427f260a (6 days ago), 2021-01-25 12:29:05 -0800
    • Engine revision 05b4bec8b3
    • Dart version 2.12.0 (build 2.12.0-253.0.dev)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/halvorsen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
 
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
 
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
 
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      
￼
 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      
￼
 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
 
[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
 
[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96
```
</details>

**Comment by pedromassangocode** [comment]
Hmm, this seems to be a regression. The issue is reproducible on master channel but not on Beta.

## Master channel

**To easily reproduce the issue press the right mouse button two times (it must show and hide a context-menu) then try to keep dragging, you will notice the crash.**

![gif](https://user-images.githubusercontent.com/67424416/106747661-80c23880-6624-11eb-80f9-0abf5c13b748.gif)


```console
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:449:18
state.down
is not true
    at Object.throw_ [as throw] (http://localhost:64421/dart_sdk.js:5342:11)
    at Object.assertFailed (http://localhost:64421/dart_sdk.js:5278:15)
    at _engine.PointerDataConverter.new.convert (http://localhost:64421/dart_sdk.js:166557:46)
    at _engine._PointerAdapter.new.[_convertEventsToPointerData] (http://localhost:64421/dart_sdk.js:165976:36)
    at http://localhost:64421/dart_sdk.js:165911:44
    at http://localhost:64421/dart_sdk.js:165880:16
    at http://localhost:64421/dart_sdk.js:165579:11
```

## Beta channel

![gif](https://user-images.githubusercontent.com/67424416/106748304-58870980-6625-11eb-83cc-add7b19ec0b2.gif)


## Issue building with HTML renderer - Building with HTML render the flying object disappear with no crash logs!

![gif](https://user-images.githubusercontent.com/67424416/106749416-c41da680-6626-11eb-9848-086933a789e3.gif)


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.156, on macOS 11.2 20D64 darwin-x64, locale en)
    • Flutter version 1.26.0-18.0.pre.156 at /Users/pedromassango/Code/flutter_master
    • Framework revision 45508985b1 (9 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2 20D64 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>


<details>
<summary>flutter doctor -v (beta)</summary>

```bash
/Users/pedromassango/Code/flutter_beta/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.2 20D64 darwin-x64, locale en)
    • Flutter version 1.25.0-8.3.pre at /Users/pedromassango/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
Process finished with exit code 0
```
</details>

**Comment by halvorsen** [comment]
I was the one who reported this to @mariamhas. Let me know if you have any questions, it also happens in 1 of 5 devices, occasionally, only in release mode, with normal drags (no right click spam). don't have logs for that yet, but I know it's also the state.down property that is failing at an assert in pointer_convert at line 283.
