### ISSUE TITLE
 Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onStart()' on a null object reference

### ISSUE THREAD

**Issue by Alexufo** [flutter/flutter#75314]
1. run in android studio 
2.  press openCamera
3. press back button

` java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onStart()' on a null object reference
        at io.flutter.embedding.android.FlutterActivity.onStart(FlutterActivity.java:535)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
        at android.app.Activity.performStart(Activity.java:7986)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3558)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:226)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:206)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:178)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7822)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
`

<details>[√] Flutter (Channel master, 1.26.0-13.0.pre.3, on Microsoft Windows [Version 10.0.19041.746], locale ru-RU)
    • Flutter version 1.26.0-13.0.pre.3 at C:\flutter
    • Framework revision 2a64fdbc43 (3 weeks ago), 2021-01-14 17:39:03 -0600
    • Engine revision effb529ece
    • Dart version 2.12.0 (build 2.12.0-224.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Salo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Salo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • RMX2001 (mobile) • LFYTVKTC4HRG6PPZ • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 88.0.705.56

• No issues found!

</details>

example [worked.zip](https://github.com/flutter/flutter/files/5916096/worked.zip)

**Comment by hammyofmha** [comment]
https://github.com/rlee287/pyautoupdate/tree/develop

**Comment by pedromassangocode** [comment]
Hi @Alexufo 
I cannot run your your project due to the error bellow.

![Screen Shot 2021-02-03 at 08 58 12](https://user-images.githubusercontent.com/67424416/106715894-f9fa6500-65fd-11eb-88ca-84c347d0017d.png)

**Comment by Alexufo** [comment]
Please do "flutter run" in folder with flutter code. I did flutter clean before upload. After it will possible to start

**Comment by pedromassangocode** [comment]
Hi @Alexufo 
Your code is throwing a error while pressing the openCamera button.

```console
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: biz.smartengines.smartid.sample, PID: 20565
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/biz.smartengines.smartid.sample-A3L7H_VfWu8It20ei3sGBg==/base.apk"],nativeLibraryDirectories=[/data/app/biz.smartengines.smartid.sample-A3L7H_VfWu8It20ei3sGBg==/lib/x86, /data/app/biz.smartengines.smartid.sample-A3L7H_VfWu8It20ei3sGBg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libjniSmartIdEngine.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at biz.smartengines.smartid.sample.SmartIDView.configureEngine(SmartIDView.java:429)
        at biz.smartengines.smartid.sample.SmartIDView.access$400(SmartIDView.java:64)
        at biz.smartengines.smartid.sample.SmartIDView$initEngineTask.doInBackground(SmartIDView.java:377)
        at biz.smartengines.smartid.sample.SmartIDView$initEngineTask.doInBackground(SmartIDView.java:368)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by Alexufo** [comment]
I did not include x86 libs for emulator. Can you test it in smartphone directly?

**Comment by pedromassangocode** [comment]
Hi @Alexufo 
I can reproduce the issue on latest Master channel but not on Stable channel. While running on Stable channel and doing the steps mentioned in the OP, the app turns black after the last step. O master channel it crashes.



<details>
<summary>logs (master channel)</summary>

```bash

02/04 12:04:10: Launching 'app' on Physical Device.
Install successfully finished in 18 s 525 ms.
$ adb shell am start -n "biz.smartengines.smartid.sample/biz.smartengines.smartid.sample.FlutterMainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: biz.smartengines.smartid.sample.test | biz.smartengines.smartid.sample
Waiting for application to come online: biz.smartengines.smartid.sample.test | biz.smartengines.smartid.sample
Connected to process 13691 on device 'xiaomi-redmi_5_plus-0258ff700005'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application biz.smartengines.smartid.sample is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
Waiting for application to come online: biz.smartengines.smartid.sample.test | biz.smartengines.smartid.sample
Connecting to biz.smartengines.smartid.sample
Connected to the target VM, address: 'localhost:56176', transport: 'socket'
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/zygote64: Late-enabling -Xcheck:jni
W/zygote64: miui_dex2oat: DeoptimizeBootImage: patch entry points of methods in boot image to interpreter bridge
W/ActivityThread: Application biz.smartengines.smartid.sample is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/zygote64: Debugger is active
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1364)
W/zygote64: miui_dex2oat:　OatFile: /data/app/biz.smartengines.smartid.sample-6o2YnRy2QTW47k3VTlu0fQ==/oat/arm64/base.odex Compiler-Filter = quicken
W/ResourceType: No package identifier when getting name for resource number 0x00000000
W/ResourceType: No package identifier when getting name for resource number 0x00000000
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/ResourceExtractor: Found extracted resources res_timestamp-1-1612435951847
    Resource version mismatch res_timestamp-1-1612436665513
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
W/.smartid.sample: type=1400 audit(0.0:3698): avc: denied { read } for name="max_map_count" dev="proc" ino=2050177 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
I/Adreno: QUALCOMM build                   : 8e3df98, Ie4790512f3
    Build Date                       : 04/11/18
    OpenGL ES Shader Compiler Version: EV031.22.00.01
    Local Branch                     : 
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r36-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
D/FLUTTER ENGINE: FLUTTER ENGINE
D/AccessibilityManager: AccessibilityManager status: mPackageName = biz.smartengines.smartid.sample, mOptimizeEnabled = true, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
I/zygote64: Do partial code cache collection, code=29KB, data=19KB
I/zygote64: After code cache collection, code=29KB, data=19KB
    Increasing code cache capacity to 128KB
D/OpenGLRenderer: HWUI GL Pipeline
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
I/flutter: Observatory listening on http://127.0.0.1:41350/1wXWrSGacJM=/
W/Looper: Slow Frame: doFrame is 446ms late
D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
E/libc: Access denied finding property "camera.hal1.packagelist"
W/.smartid.sample: type=1400 audit(0.0:3700): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=5211 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
I/Choreographer: Skipped 63 frames!  The application may be doing too much work on its main thread.
W/Looper: Slow Frame: doFrame is 1052ms late
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: biz.smartengines.smartid.sample, PID: 13691
    java.lang.RuntimeException: Unable to resume activity {biz.smartengines.smartid.sample/biz.smartengines.smartid.sample.FlutterMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onStart()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3627)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onStart()' on a null object reference
        at io.flutter.embedding.android.FlutterActivity.onStart(FlutterActivity.java:535)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
        at android.app.Activity.performStart(Activity.java:7108)
        at android.app.Activity.performRestart(Activity.java:7183)
        at android.app.Activity.performResume(Activity.java:7188)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
I/Process: Sending signal. PID: 13691 SIG: 9
Disconnected from the target VM, address: 'localhost:56176', transport: 'socket'
```
</details>



<details>
<summary>logs (stable channel)</summary>

```bash

02/04 11:56:11: Launching 'app' on Physical Device.
App restart successful without requiring a re-install.
$ adb shell am start -n "biz.smartengines.smartid.sample/biz.smartengines.smartid.sample.FlutterMainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: biz.smartengines.smartid.sample.test | biz.smartengines.smartid.sample
Waiting for application to come online: biz.smartengines.smartid.sample.test | biz.smartengines.smartid.sample
Waiting for application to come online: biz.smartengines.smartid.sample.test | biz.smartengines.smartid.sample
Connecting to biz.smartengines.smartid.sample
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application biz.smartengines.smartid.sample is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/zygote64: Debugger is active
I/System.out: Debugger has connected
    waiting for debugger to settle...
Connected to the target VM, address: 'localhost:55529', transport: 'socket'
I/chatty: uid=10174(biz.smartengines.smartid.sample) identical 3 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1349)
W/zygote64: miui_dex2oat:　OatFile: /data/app/biz.smartengines.smartid.sample-HXMhJNYg3GsqcugfASRKCA==/oat/arm64/base.odex Compiler-Filter = quicken
W/ResourceType: No package identifier when getting name for resource number 0x00000000
W/ResourceType: No package identifier when getting name for resource number 0x00000000
I/System.out: should load native is true
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/ResourceExtractor: Found extracted resources res_timestamp-1-1612435951847
I/Adreno: QUALCOMM build                   : 8e3df98, Ie4790512f3
    Build Date                       : 04/11/18
    OpenGL ES Shader Compiler Version: EV031.22.00.01
    Local Branch                     : 
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r36-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
D/FLUTTER ENGINE: FLUTTER ENGINE
D/AccessibilityManager: AccessibilityManager status: mPackageName = biz.smartengines.smartid.sample, mOptimizeEnabled = true, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
D/OpenGLRenderer: HWUI GL Pipeline
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
I/zygote64: Do partial code cache collection, code=30KB, data=20KB
    After code cache collection, code=30KB, data=20KB
    Increasing code cache capacity to 128KB
I/flutter: Observatory listening on http://127.0.0.1:44008/xDx1JmIbZ0M=/
W/Looper: Slow Frame: doFrame is 442ms late
D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
E/libc: Access denied finding property "camera.hal1.packagelist"
W/.smartid.sample: type=1400 audit(0.0:3694): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=5211 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
W/Looper: Slow Frame: doFrame is 315ms late
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.185, on macOS 11.2 20D64
    darwin-x64, locale en)
    • Flutter version 1.26.0-18.0.pre.185 at
      /Users/pedromassango/Code/flutter_master
    • Framework revision 89d45baa9b (6 hours ago), 2021-02-04 00:11:03 -0500
    • Engine revision b7c672a372
    • Dart version 2.12.0 (build 2.12.0-284.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)              • 0258ff700005  • android-arm64  •
      Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     •
      macOS 11.2 20D64 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 88.0.4324.146

! Doctor found issues in 1 category.
```
</details>

**Comment by chinmaygarde** [comment]
cc @xster

**Comment by jason-simmons** [comment]
A workaround for this landed in the engine a few days ago (see https://github.com/flutter/engine/commit/5e50f4bad3d5f39997b43e69d176e0abc3f668d9)

It should be available now on the master channel.
