### ISSUE TITLE
On horizontal scroll on touchpad in [Windows app] cause: RenderBox was not laid out. 

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#75330]
Hi flutter team,

In the current version of the Flutter, windows app build. When I do horizontal scroll on the touchpad. It gives this error.

```
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
RenderBox was not laid out: RenderSemanticsAnnotations#2951d NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1940:12)
#3      RenderBox.semanticBounds (package:flutter/src/rendering/box.dart:2074:44)
#4      FocusNode.rect (package:flutter/src/widgets/focus_manager.dart:753:91)
#5      DirectionalFocusTraversalPolicyMixin._sortAndFilterHorizontally.<anonymous closure> (package:flutter/src/widgets/focus_traversal.dart:532:75)
#6      _movingInsertionSort (package:flutter/src/foundation/collections.dart:253:18)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

I think it might be related to `Textfield` widget focus.

In the latest build, it crashes the Windows app so I have downgraded it to `Channel dev, 1.26.0-12.0.pre`.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.26.0-12.0.pre, on Microsoft Windows [Version 10.0.18362.1082], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.3)
[√] Android Studio (version 3.1)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.48.0)
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

Now, it doesn't crash the app but still gives this error. And there is no clear indication of where it is coming from.

**Comment by TahaTesser** [comment]
Hi @SahajRana 
I just tried horizontal scroll on TextField on both `dev` and `master` channels, no exceptions on Windows 

<details>
<summary>flutter doctor -v</summary>

```bash
[âˆš] Flutter (Channel dev, 1.26.0-17.1.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    â€¢ Flutter version 1.26.0-17.1.pre at C:\Users\Taha\Code\flutter_dev
    â€¢ Framework revision c40e5294dd (6 days ago), 2021-01-29 08:44:18 -0800
    â€¢ Engine revision 5d3477eab4
    â€¢ Dart version 2.12.0 (build 2.12.0-259.0.dev)
[âˆš] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    â€¢ Android SDK at C:\Users\Taha\Code\SDK
    â€¢ Platform android-30, build-tools 30.0.3
    â€¢ ANDROID_HOME = C:\Users\Taha\Code\SDK
    â€¢ Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    â€¢ All Android licenses accepted.
[âˆš] Chrome - develop for the web
    â€¢ Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
[âˆš] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    â€¢ Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    â€¢ Visual Studio Community 2019 version 16.8.30804.86
    â€¢ Windows 10 SDK version 10.0.18362.0
[âˆš] Android Studio (version 4.1.0)
    â€¢ Android Studio at C:\Users\Taha\Code\android-studio
    â€¢ Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    â€¢ Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[âˆš] VS Code (version 1.52.1)
    â€¢ VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    â€¢ Flutter extension version 3.19.0
[âˆš] Connected device (3 available)
    â€¢ Windows (desktop) â€¢ windows â€¢ windows-x64    â€¢ Microsoft Windows [Version 10.0.19042.746]
    â€¢ Chrome (web)      â€¢ chrome  â€¢ web-javascript â€¢ Google Chrome 88.0.4324.104
    â€¢ Edge (web)        â€¢ edge    â€¢ web-javascript â€¢ Microsoft Edge 88.0.705.53
â€¢ No issues found!
```
```bash
[âˆš] Flutter (Channel master, 1.26.0-18.0.pre.186, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    â€¢ Flutter version 1.26.0-18.0.pre.186 at C:\Users\Taha\Code\flutter_master
    â€¢ Framework revision 39114251af (2 hours ago), 2021-02-04 01:16:04 -0500
    â€¢ Engine revision 1c2c78398c
    â€¢ Dart version 2.12.0 (build 2.12.0-284.0.dev)
[âˆš] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    â€¢ Android SDK at C:\Users\Taha\Code\SDK
    â€¢ Platform android-30, build-tools 30.0.3
    â€¢ ANDROID_HOME = C:\Users\Taha\Code\SDK
    â€¢ Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    â€¢ All Android licenses accepted.
[âˆš] Chrome - develop for the web
    â€¢ Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
[âˆš] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    â€¢ Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    â€¢ Visual Studio Community 2019 version 16.8.30804.86
    â€¢ Windows 10 SDK version 10.0.18362.0
[âˆš] Android Studio (version 4.1.0)
    â€¢ Android Studio at C:\Users\Taha\Code\android-studio
    â€¢ Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    â€¢ Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    â€¢ Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[âˆš] VS Code (version 1.52.1)
    â€¢ VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    â€¢ Flutter extension version 3.19.0
[âˆš] Connected device (3 available)
    â€¢ Windows (desktop) â€¢ windows â€¢ windows-x64    â€¢ Microsoft Windows [Version 10.0.19042.746]
    â€¢ Chrome (web)      â€¢ chrome  â€¢ web-javascript â€¢ Google Chrome 88.0.4324.104
    â€¢ Edge (web)        â€¢ edge    â€¢ web-javascript â€¢ Microsoft Edge 88.0.705.53
â€¢ No issues found!
```

</details>

Can you please provide  `flutter run -d windows --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
