### ISSUE TITLE
Failed assertion: line 7121 pos 15: 'child != null': is not true.

### ISSUE THREAD

**Issue by mahtoBabu** [flutter/flutter#75468]
W/IInputConnectionWrapper( 4648): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4648): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4648): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4648): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4648): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4648): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4648): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4648): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4648): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4648): endBatchEdit on inactive InputConnection

======== Exception caught by widgets library =======================================================
The following assertion was thrown building _SearchPage<Elements>(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#87a29]], state: _SearchPageState<Elements>#67c9e):
'package:flutter/src/widgets/basic.dart': Failed assertion: line 7121 pos 15: 'child != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/kidsLAB/AndroidStudioProjects/search/lib/main.dart:11:12
When the exception was thrown, this was the stack: 
#2      new KeyedSubtree (package:flutter/src/widgets/basic.dart:7121:15)
#3      _SearchPageState.build (package:flutter/src/material/search.dart:498:16)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)

logcat

2021-02-05 07:32:44.021 1434-1641/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 3053490 , only wrote 2900160
2021-02-05 07:32:49.187 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:32:52.580 1434-4738/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2900510 , only wrote 2900160
2021-02-05 07:32:52.758 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:32:52.951 4648-4648/widget.search W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-02-05 07:32:52.951 4648-4648/widget.search W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2021-02-05 07:32:52.952 4648-4648/widget.search W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2021-02-05 07:32:52.956 4648-4648/widget.search W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2021-02-05 07:32:52.958 4648-4648/widget.search W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-02-05 07:32:52.986 4648-4648/widget.search W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-02-05 07:32:52.986 4648-4648/widget.search W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2021-02-05 07:32:52.992 4648-4648/widget.search W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2021-02-05 07:32:52.995 4648-4648/widget.search W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2021-02-05 07:32:53.000 4648-4648/widget.search W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-02-05 07:32:53.022 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:32:53.043 1442-1442/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 14262272
2021-02-05 07:32:53.071 1442-1442/? I/chatty: uid=1000(system) allocator@2.0-s identical 1 line
2021-02-05 07:32:53.090 1442-1442/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 14262272
2021-02-05 07:32:53.153 1826-1826/com.google.android.inputmethod.latin I/native: input-context-store.cc:113 Using roll back input context operation: [AbortComposing] reason: client [44] vs decoder [45]
2021-02-05 07:32:53.207 1826-1826/com.google.android.inputmethod.latin W/GInputConnectionWrapper: Fixing selection indices to 0, 0
2021-02-05 07:32:53.298 1826-4741/com.google.android.inputmethod.latin D/EGL_emulation: eglMakeCurrent: 0xe6f47260: ver 2 0 (tinfo 0xdc740f70)
2021-02-05 07:32:54.195 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:32:54.847 1450-1450/? I/boot-pipe: done populating /dev/random
2021-02-05 07:32:55.808 1434-1641/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 3208223 , only wrote 3054960
2021-02-05 07:33:00.055 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:33:00.190 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:33:01.315 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:33:01.328 1826-4741/com.google.android.inputmethod.latin D/EGL_emulation: eglMakeCurrent: 0xe6f47260: ver 2 0 (tinfo 0xdc740f70)
2021-02-05 07:33:01.577 1443-1443/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:01.579 1443-1443/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:01.586 1443-1443/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:01.588 1443-1443/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:01.590 1443-1443/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:01.592 1443-1443/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:05.188 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:33:06.326 1826-1826/com.google.android.inputmethod.latin I/zygote: Deoptimizing java.lang.Object ji.put(java.lang.Object, java.lang.Object) due to JIT inline cache
2021-02-05 07:33:06.478 1698-1718/system_process I/WifiService: requestActivityInfo uid=1000
2021-02-05 07:33:06.478 1698-1718/system_process I/WifiService: reportActivityInfo uid=1000
2021-02-05 07:33:06.479 1698-1718/system_process I/WifiService: getSupportedFeatures uid=1000
2021-02-05 07:33:10.192 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:33:15.189 2291-5457/com.google.android.gms.persistent I/chatty: uid=10014(com.google.android.gms) lowpool[20] identical 1 line
2021-02-05 07:33:20.188 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:33:22.725 1698-1718/system_process I/WifiService: requestActivityInfo uid=1000
2021-02-05 07:33:22.725 1698-1718/system_process I/WifiService: reportActivityInfo uid=1000
2021-02-05 07:33:22.725 1698-1718/system_process I/WifiService: getSupportedFeatures uid=1000
2021-02-05 07:33:25.193 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:33:41.196 2291-5457/com.google.android.gms.persistent I/chatty: uid=10014(com.google.android.gms) lowpool[20] identical 3 lines
2021-02-05 07:33:46.192 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:33:46.455 1443-1467/? D/hwcomposer: hw_composer sent 24 syncs in 107s
2021-02-05 07:33:46.461 1434-4738/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 3055385 , only wrote 3054960
2021-02-05 07:33:46.713 1698-1716/system_process D/AutofillManagerService: onBackKeyPressed()
2021-02-05 07:33:47.120 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:33:49.424 1843-2082/com.android.systemui I/chatty: uid=10030(com.android.systemui) RenderThread identical 13 lines
2021-02-05 07:33:49.457 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:33:49.484 4648-4648/widget.search W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-02-05 07:33:49.486 4648-4648/widget.search W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2021-02-05 07:33:49.486 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:33:49.489 4648-4648/widget.search W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2021-02-05 07:33:49.495 4648-4648/widget.search W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2021-02-05 07:33:49.499 4648-4648/widget.search W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-02-05 07:33:49.507 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:33:49.532 4648-4648/widget.search W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-02-05 07:33:49.533 4648-4648/widget.search W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2021-02-05 07:33:49.539 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:33:49.542 4648-4648/widget.search W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2021-02-05 07:33:49.546 4648-4648/widget.search W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2021-02-05 07:33:49.549 4648-4648/widget.search W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-02-05 07:33:49.617 1442-1442/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 14262272
2021-02-05 07:33:49.656 1442-1442/? I/chatty: uid=1000(system) allocator@2.0-s identical 1 line
2021-02-05 07:33:49.714 1442-1442/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 14262272
2021-02-05 07:33:49.749 1826-1826/com.google.android.inputmethod.latin I/native: input-context-store.cc:113 Using roll back input context operation: [AbortComposing] reason: client [51] vs decoder [52]
2021-02-05 07:33:49.814 1826-1826/com.google.android.inputmethod.latin W/GInputConnectionWrapper: Fixing selection indices to 0, 0
2021-02-05 07:33:49.874 1826-4741/com.google.android.inputmethod.latin D/EGL_emulation: eglMakeCurrent: 0xe6f47260: ver 2 0 (tinfo 0xdc740f70)
2021-02-05 07:33:51.194 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:33:51.957 1826-4741/com.google.android.inputmethod.latin D/EGL_emulation: eglMakeCurrent: 0xe6f47260: ver 2 0 (tinfo 0xdc740f70)
2021-02-05 07:33:52.223 1443-1528/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:52.226 1443-1528/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:52.229 1443-1528/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:52.233 1443-1528/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:52.236 1443-1528/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:52.238 1443-1528/? D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
2021-02-05 07:33:52.267 1434-1641/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 3610947 , only wrote 3333600
2021-02-05 07:33:54.849 1450-1450/? I/boot-pipe: done populating /dev/random
2021-02-05 07:33:55.958 1698-1707/system_process I/zygote: Background concurrent copying GC freed 105336(3MB) AllocSpace objects, 10(520KB) LOS objects, 38% free, 9MB/15MB, paused 5.786ms total 103.234ms
2021-02-05 07:33:57.192 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:00.010 1698-1714/system_process E/memtrack: Couldn't load memtrack module
2021-02-05 07:34:00.010 1698-1714/system_process W/android.os.Debug: failed to get memory consumption info: -1
2021-02-05 07:34:00.062 1843-2082/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0xcde78ce0: ver 2 0 (tinfo 0xcea187a0)
2021-02-05 07:34:02.197 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:08.196 2291-4533/com.google.android.gms.persistent I/chatty: uid=10014(com.google.android.gms) lowpool[15] identical 1 line
2021-02-05 07:34:14.196 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:19.198 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:24.200 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:29.206 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:35.194 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:40.199 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:46.191 2291-5457/com.google.android.gms.persistent I/chatty: uid=10014(com.google.android.gms) lowpool[20] identical 1 line
2021-02-05 07:34:51.197 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:54.851 1450-1450/? I/boot-pipe: done populating /dev/random
2021-02-05 07:34:56.198 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:34:57.922 1698-2345/system_process D/WificondControl: Scan result ready event
2021-02-05 07:35:00.030 1443-1467/? D/hwcomposer: hw_composer sent 18 syncs in 73s
2021-02-05 07:35:01.202 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:35:38.209 2291-4533/com.google.android.gms.persistent I/chatty: uid=10014(com.google.android.gms) lowpool[15] identical 7 lines
2021-02-05 07:35:43.206 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:35:47.658 1698-2345/system_process I/WifiService: getConnectionInfo uid=10014
2021-02-05 07:35:47.670 2291-5663/com.google.android.gms.persistent E/WakeLock: GCM_HB_ALARM release without a matched acquire!
2021-02-05 07:35:47.687 1698-1718/system_process I/WifiService: requestActivityInfo uid=1000
2021-02-05 07:35:47.687 1698-1718/system_process I/WifiService: reportActivityInfo uid=1000
2021-02-05 07:35:47.687 1698-1718/system_process I/WifiService: getSupportedFeatures uid=1000
2021-02-05 07:35:47.926 1698-2345/system_process I/WifiService: getConnectionInfo uid=10014
2021-02-05 07:35:49.207 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:35:54.853 1450-1450/? I/boot-pipe: done populating /dev/random
2021-02-05 07:35:55.204 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:36:00.015 1698-1714/system_process E/memtrack: Couldn't load memtrack module
2021-02-05 07:36:00.015 1698-1714/system_process W/android.os.Debug: failed to get memory consumption info: -1
2021-02-05 07:36:00.046 1443-1467/? D/hwcomposer: hw_composer sent 6 syncs in 60s
2021-02-05 07:36:01.206 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:36:04.700 1698-1718/system_process E/BatteryExternalStatsWorker: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
2021-02-05 07:36:07.202 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:36:10.724 1698-1718/system_process I/WifiService: requestActivityInfo uid=1000
2021-02-05 07:36:10.724 1698-1718/system_process I/WifiService: reportActivityInfo uid=1000
2021-02-05 07:36:10.724 1698-1718/system_process I/WifiService: getSupportedFeatures uid=1000
2021-02-05 07:36:12.210 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:36:23.206 2291-5457/com.google.android.gms.persistent I/chatty: uid=10014(com.google.android.gms) lowpool[20] identical 2 lines
2021-02-05 07:36:28.209 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:36:33.210 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:36:39.211 2291-4533/com.google.android.gms.persistent I/chatty: uid=10014(com.google.android.gms) lowpool[15] identical 1 line
2021-02-05 07:36:45.209 2291-4533/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:36:51.210 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:36:54.855 1450-1450/? I/boot-pipe: done populating /dev/random
2021-02-05 07:36:54.954 1698-1714/system_process E/memtrack: Couldn't load memtrack module
2021-02-05 07:36:54.954 1698-1714/system_process W/android.os.Debug: failed to get memory consumption info: -1
2021-02-05 07:36:57.209 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:37:00.033 1443-1467/? D/hwcomposer: hw_composer sent 6 syncs in 60s
2021-02-05 07:37:02.214 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#
2021-02-05 07:37:07.258 1698-1718/system_process I/WifiService: requestActivityInfo uid=1000
2021-02-05 07:37:07.259 1698-1718/system_process I/WifiService: reportActivityInfo uid=1000
2021-02-05 07:37:07.259 1698-1718/system_process I/WifiService: getSupportedFeatures uid=1000
2021-02-05 07:37:07.302 1698-1718/system_process E/BluetoothAdapter: Bluetooth binder is null
2021-02-05 07:37:07.330 1698-1718/system_process E/KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
2021-02-05 07:37:07.341 1698-1718/system_process E/BatteryExternalStatsWorker: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
2021-02-05 07:37:07.565 1698-1718/system_process I/WifiService: requestActivityInfo uid=1000
2021-02-05 07:37:07.566 1698-1718/system_process I/WifiService: reportActivityInfo uid=1000
2021-02-05 07:37:07.566 1698-1718/system_process I/WifiService: getSupportedFeatures uid=1000
2021-02-05 07:37:08.215 2291-5457/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10014):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2291). Was: 3 for 57, account#-517948760#

**Comment by pedromassangocode** [comment]
Hi @mahtoBabu 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
