### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'streamListen' was called on null.Receiver: nullTried calling: streamListen("Extension")

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#75466]
## Command
```
flutter --no-color run --machine --device-id=linux --profile --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart
```

## Steps to Reproduce
1. run the app in profile mode on Linux.
2. watch it crash

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'streamListen' was called on null.
Receiver: null
Tried calling: streamListen("Extension")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      waitForExtension (package:flutter_tools/src/resident_runner.dart:1513:21)
#2      ResidentRunner._callDevToolsUriExtension (package:flutter_tools/src/resident_runner.dart:1318:11)
#3      ResidentRunner.maybeCallDevToolsUriServiceExtension (package:flutter_tools/src/resident_runner.dart:1309:11)
#4      ResidentRunner.serveAndAnnounceDevTools (package:flutter_tools/src/resident_runner.dart:1301:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 1.26.0-18.0.pre.140, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-18.0.pre.140 at /home/gspencer/code/flutter
    • Framework revision 2dfc86ea0b (2 days ago), 2021-02-02 12:27:41 -0800
    • Engine revision e4c4a2f205
    • Dart version 2.12.0 (build 2.12.0-281.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/gspencer/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /opt/my-intellij-ce-latest
    • Flutter plugin version 53.0.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.146

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: 87b043658bc3eb16cf1032cbc9b0ba6484271cea

## App main.dart

(Can't include the assets here, but you can use any image)

```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      routes: {
        '/privacy': (BuildContext context) => PrivacyPage(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

enum DrawingType {
  svg,
  png,
  container,
}

DrawingType drawingType = DrawingType.svg;

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            TextButton(
              child: Text('PRIVACY PAGE - SVG'),
              onPressed: () {
                drawingType = DrawingType.svg;
                Navigator.pushNamed(context, '/privacy');
              },
            ),
            TextButton(
              child: Text('PRIVACY PAGE - PNG'),
              onPressed: () {
                drawingType = DrawingType.png;
                Navigator.pushNamed(context, '/privacy');
              },
            ),
            TextButton(
              child: Text('PRIVACY PAGE - CONTAINER'),
              onPressed: () {
                drawingType = DrawingType.container;
                Navigator.pushNamed(context, '/privacy');
              },
            ),
          ],
        ),
      ),
    );
  }
}

class PrivacyPage extends StatelessWidget {
  const PrivacyPage();

  Widget _getDrawing() {
    switch (drawingType) {
      case DrawingType.svg:
        return SvgPicture.asset('assets/oobe_privacy.svg');
      case DrawingType.png:
        return Image.asset('assets/oobe_privacy.png');
      case DrawingType.container:
        return Container(color: Colors.red, width: 100, height: 100);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.arrow_back),
            onPressed: () {
              Navigator.pop(context);
            },
          ),
        ],
      ),
      body: Center(
        child: _getDrawing(),
      ),
    );
  }
}

```

**Comment by TimWhiting** [comment]
Also seeing this on Linux profile mode.

**Comment by jonahwilliams** [comment]
This was fixed via https://github.com/flutter/flutter/commit/7ab8517f7e6a81b84ef7c8c1a5a2bf717f00df74
