### ISSUE TITLE
AccessibilityViewEmbedder java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by wangbo4020** [flutter/flutter#75499]
```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.746], locale zh-CN)
    • Flutter version 1.22.6 at D:\Development\Flutter\flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Development\Android\android-sdk-windows
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Development\Android\android-sdk-windows
    • Java binary at: D:\Development\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Development\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
```

Device
Brand: HUAWEI
Model: LIO-AL00
CPU ARM: arm64-v8a,armeabi-v7a,armeabi
Orientation: Portrait
RAM free: 4.77 GB
Disk free: 37.88 GB

Operating System
Version: Android 10
Orientation: Portrait
Rooted: No

log
```
--logversion:utracea
Process Name: 'com.myapp'
Thread Name: 'main'
Back traces starts.
java.lang.StackOverflowError: stack size 8MB
       at java.lang.reflect.Method.invoke(Method.java)
       at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.getChildId(AccessibilityViewEmbedder.java:532)
       at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.access$500(AccessibilityViewEmbedder.java:429)
       at io.flutter.view.AccessibilityViewEmbedder.addChildrenToFlutterNode(AccessibilityViewEmbedder.java:171)
       at io.flutter.view.AccessibilityViewEmbedder.convertToFlutterNode(AccessibilityViewEmbedder.java:145)
       at io.flutter.view.AccessibilityViewEmbedder.getRootNode(AccessibilityViewEmbedder.java:94)
       at io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo(AccessibilityBridge.java:549)
       at android.view.View.populateVirtualStructure(View.java:8649)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.populateVirtualStructure(View.java:8652)
       at android.view.View.onProvideVirtualStructureCompat(View.java:8070)
       at android.view.View.onProvideVirtualStructure(View.java:8051)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8719)
       at android.view.View.dispatchProvideStructure(View.java:8666)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3484)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3557)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:519)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3794)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by Sammius** [comment]
Why did you close this question? Have you found a solution?

**Comment by tesla0939** [comment]
My app had the same problem also on some android 9 devices. Could you share if any solution?
