### ISSUE TITLE
Fonts not being rendered correctly

### ISSUE THREAD

**Issue by mzdm** [flutter/flutter#75583]
## Steps to Reproduce

I don't have a reproducible sample code but it is happening on my repository: https://github.com/mzdm/czech_fonts_validator

1. Click on reload in Floating Action Button and then Play button
2. The app stops responding when the validation counter hits ~175
3. This happens crash happens only on the web on **1.26.0-17.2.pre**, on **1.26.0-8.0.pre** it works fine

**Expected results:** 
A web app that does some font rendering and validating. Has some issues on the latest Flutter channel dev. Note: the rendering crash occurs only on the web version, on mobile it works fine.

**Actual results:** 
App crashes on **Channel dev, 1.26.0-17.2.pre** but it works fine on **1.26.0-8.0.pre • channel dev**

<details>
  <summary>Logs</summary>

```
Ibarra Real Nova:   Δw = 0  |  Δh: = 0  IbarraRealNova_regular
> Confidence.HIGHEST
172

Quintessential:   Δw = 0  |  Δh: = 0  Quintessential_regular
> Confidence.HIGHEST
173

Baloo Bhaina:   Δw = 0  |  Δh: = 0  BalooBhaina_regular
> Confidence.HIGHEST
174
Error: SkiaObjectCollectionError: RuntimeError: table index is out of bounds
https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js 157:166                                                      pc
https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js 196:352                                                      delete
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/canvaskit_api.dart 1858:18  collectSkiaObjectsNow
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/canvaskit_api.dart 1826:7   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19  internalCallback

    at Object.throw_ [as throw] (http://localhost:52970/dart_sdk.js:5331:11)
    at _engine.ProductionCollector.new.collectSkiaObjectsNow (http://localhost:52970/dart_sdk.js:138486:19)
    at http://localhost:52970/dart_sdk.js:138452:14
    at internalCallback (http://localhost:52970/dart_sdk.js:25101:11)

======== Exception caught by rendering library =====================================================
The following NativeJavaScriptObject object was thrown during performLayout():
  RuntimeError: table index is out of bounds

The relevant error-causing widget was: 
  Text file:///C:/Users/matej/FlutterProjects/apps/czech_fonts_validator/lib/pages/result_page.dart:82:18
When the exception was thrown, this was the stack: 
https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js 1:1                                                     ParagraphBuilder$_MakeFromFontProvider
https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js 73:236                                                  MakeFromFontProvider
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/text.dart 608:56       new
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/text.dart 589:21                      new
packages/flutter/src/painting/text_painter.dart 568:46                                                           layout
...
The following RenderObject was being processed when the exception was fired: RenderParagraph#7b68f relayoutBoundary=up19 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: offset=Offset(7.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=56.0)
...  size: Size(93.0, 16.0)
...  textAlign: start
...  textDirection: ltr
...  softWrap: wrapping at box width
...  overflow: clip
...  locale: en_US
...  maxLines: unlimited
  text: TextSpan
    debugLabel: ((englishLike body1 2014).merge(whiteRedmond bodyText2)).merge(unknown)
    inherit: false
    color: Color(0xffffffff)
    family: Segoe UI
    size: 14.0
    weight: 500
    baseline: alphabetic
    decoration: TextDecoration.none
    "SOURCE CODE"
RenderObject: RenderParagraph#7b68f relayoutBoundary=up19 NEEDS-LAYOUT NEEDS-PAINT
  parentData: offset=Offset(7.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=56.0)
  size: Size(93.0, 16.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    debugLabel: ((englishLike body1 2014).merge(whiteRedmond bodyText2)).merge(unknown)
    inherit: false
    color: Color(0xffffffff)
    family: Segoe UI
    size: 14.0
    weight: 500
    baseline: alphabetic
    decoration: TextDecoration.none
    "SOURCE CODE"
====================================================================================================
```

```
[√] Flutter (Channel dev, 1.26.0-17.2.pre, on Microsoft Windows [Version 10.0.19041.746], locale cs-CZ)
    • Flutter version 1.26.0-17.2.pre at C:\Programy\flutter
    • Framework revision 79b49b9e10 (4 days ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\matej\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\matej\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.7319.5

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 203.6912

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!

```

</details>

**Comment by mzdm** [comment]
<details>
  <summary>More logs</summary>

```

RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at La (https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:149:56)
    at d (https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:220:329)
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[350]:0xec64
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[336]:0xe5cd
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[12676]:0x4565fa
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[434]:0x127ed
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[753]:0x26e83
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[12338]:0x433a03
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[12351]:0x434e89
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[12276]:0x42d29b
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[3168]:0x121bb1
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[4997]:0x1e9849
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[3166]:0x121276
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[3172]:0x1220bb
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[12695]:0x45748b
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[4147]:0x19266a
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[12696]:0x457810
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[4148]:0x1926da
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[12697]:0x4578a9
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[9238]:0x338689
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[7162]:0x29aa97
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[9972]:0x3670df
    at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.wasm:wasm-function[7152]:0x29a7cc
    at FontMgr$_makeTypefaceFromData [as _makeTypefaceFromData] (eval at Yc (https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:1:1), <anonymous>:10:10)
    at FontMgr.a.FontMgr.MakeTypefaceFromData (https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:78:129)
    at TypefaceFontProvider.f.TypefaceFontProvider.registerFont (https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:68:408)
    at _engine.SkiaFontCollection.new.ensureFontsLoaded (http://localhost:55593/dart_sdk.js:140045:45)
    at ensureFontsLoaded.next (<anonymous>)
    at http://localhost:55593/dart_sdk.js:39157:33
    at _RootZone.runUnary (http://localhost:55593/dart_sdk.js:39014:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:55593/dart_sdk.js:34000:29)
    at handleValueCallback (http://localhost:55593/dart_sdk.js:34560:49)
    at Function._propagateToListeners (http://localhost:55593/dart_sdk.js:34598:17)
    at _Future.new.[_completeWithValue] (http://localhost:55593/dart_sdk.js:34440:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55593/dart_sdk.js:34463:35)
    at Object._microtaskLoop (http://localhost:55593/dart_sdk.js:39301:13)
    at _startMicrotaskLoop (http://localhost:55593/dart_sdk.js:39307:13)
    at http://localhost:55593/dart_sdk.js:34814:9

Itim:   Δw = 0  |  Δh: = 0  Itim_regular
> Confidence.HIGHEST
171
CanvasKit threw an exception while laying out the paragraph. The font was "Segoe UI". Exception:
RuntimeError: function signature mismatch
CanvasKit threw an exception while laying out the paragraph. The font was "Jaldi_regular". Exception:
RuntimeError: function signature mismatch

======== Exception caught by rendering library =====================================================
The following NativeJavaScriptObject object was thrown during performLayout():
  RuntimeError: function signature mismatch

The relevant error-causing widget was: 
  Text file:///C:/Users/matej/FlutterProjects/apps/czech_fonts_validator/lib/pages/font_validation_page.dart:179:18
When the exception was thrown, this was the stack: 
https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js 1:1                                                     Paragraph$layout
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/text.dart 573:18       layout
packages/flutter/src/painting/text_painter.dart 578:5                                                            layout
packages/flutter/src/rendering/paragraph.dart 515:18                                                             [_layoutText]
packages/flutter/src/rendering/paragraph.dart 538:5                                                              [_layoutTextWithConstraints]
...
The following RenderObject was being processed when the exception was fired: RenderParagraph#2ab9c relayoutBoundary=up3 NEEDS-LAYOUT
...  parentData: offset=Offset(87.5, 100.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=1366.0, 0.0<=h<=Infinity)
...  size: Size(53.0, 16.0)
...  textAlign: start
...  textDirection: ltr
...  softWrap: wrapping at box width
...  overflow: clip
...  locale: en_US
...  maxLines: unlimited
  text: TextSpan
    debugLabel: (englishLike body1 2014).merge(blackRedmond bodyText2)
    inherit: false
    color: Color(0xdd000000)
    family: Segoe UI
    size: 14.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "171/599"
RenderObject: RenderParagraph#2ab9c relayoutBoundary=up3 NEEDS-LAYOUT
  parentData: offset=Offset(87.5, 100.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=1366.0, 0.0<=h<=Infinity)
  size: Size(53.0, 16.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    debugLabel: (englishLike body1 2014).merge(blackRedmond bodyText2)
    inherit: false
    color: Color(0xdd000000)
    family: Segoe UI
    size: 14.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "171/599"
====================================================================================================
CanvasKit threw an exception while laying out the paragraph. The font was "Jaldi_regular". Exception:
RuntimeError: function signature mismatch

Jaldi:   Δw = 0  |  Δh: = 0  Jaldi_regular
> Confidence.HIGHEST
172

Purple Purse:   Δw = 0  |  Δh: = 0  PurplePurse_regular
> Confidence.HIGHEST
173

Bahiana:   Δw = 0  |  Δh: = 0  Bahiana_regular
> Confidence.HIGHEST
174
CanvasKit threw an exception while laying out the paragraph. The font was "Segoe UI". Exception:
RuntimeError: function signature mismatch
CanvasKit threw an exception while laying out the paragraph. The font was "Bahianita_regular". Exception:
RuntimeError: function signature mismatch

======== Exception caught by rendering library =====================================================
  RuntimeError: function signature mismatch
The relevant error-causing widget was: 
  Text-[GlobalKey#44601 latinTextKey2] file:///C:/Users/matej/FlutterProjects/apps/czech_fonts_validator/lib/pages/font_validation_page.dart:201:15
The following RenderObject was being processed when the exception was fired: RenderParagraph#685cf relayoutBoundary=up5 NEEDS-LAYOUT
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=1366.0, 0.0<=h<=Infinity)
  size: Size(221.0, 16.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    debugLabel: ((englishLike body1 2014).merge(blackRedmond bodyText2)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Jaldi_regular
    familyFallback: Jaldi
    size: 14.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "Prilis zlutoucky kun upel dabelske o"
RenderObject: RenderParagraph#685cf relayoutBoundary=up5 NEEDS-LAYOUT
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=1366.0, 0.0<=h<=Infinity)
  size: Size(221.0, 16.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    debugLabel: ((englishLike body1 2014).merge(blackRedmond bodyText2)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Jaldi_regular
    familyFallback: Jaldi
    size: 14.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "Prilis zlutoucky kun upel dabelske o"
====================================================================================================

======== Exception caught by rendering library =====================================================
  RuntimeError: function signature mismatch
The relevant error-causing widget was: 
  Text-[GlobalKey#198a2 czechTextKey2] file:///C:/Users/matej/FlutterProjects/apps/czech_fonts_validator/lib/pages/font_validation_page.dart:210:15
The following RenderObject was being processed when the exception was fired: RenderParagraph#5bb6a relayoutBoundary=up5 NEEDS-LAYOUT
  parentData: offset=Offset(0.0, 36.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=1366.0, 0.0<=h<=Infinity)
  size: Size(221.0, 16.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    debugLabel: ((englishLike body1 2014).merge(blackRedmond bodyText2)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Jaldi_regular
    familyFallback: Jaldi
    size: 14.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "Příliš žlutoučký kůň úpěl dábelské ó"
RenderObject: RenderParagraph#5bb6a relayoutBoundary=up5 NEEDS-LAYOUT
  parentData: offset=Offset(0.0, 36.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=1366.0, 0.0<=h<=Infinity)
  size: Size(221.0, 16.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    debugLabel: ((englishLike body1 2014).merge(blackRedmond bodyText2)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Jaldi_regular
    familyFallback: Jaldi
    size: 14.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "Příliš žlutoučký kůň úpěl dábelské ó"
====================================================================================================
CanvasKit threw an exception while laying out the paragraph. The font was "Bahianita_regular". Exception:
RuntimeError: function signature mismatch

```

</details>

**Comment by iapicca** [comment]
@mzdm 
for the issue to be workable need to be reproducible,
either with a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
or providing the clear steps to reproduce it
both without involving 3rd party plugins (including your own in this case)

**Comment by mzdm** [comment]
I'm unable to find a reproducible way because it occurs quite randomly without much context. I'm going to close it for now and if I find something more I will reopen it. 

I will either have a downgraded version or run it with `--web-renderer=html` argument for this specific project until then.
