### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by pratt8084** [flutter/flutter#75594]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
DartDevelopmentServiceException
```
#0      new IOWebSocketChannel._withoutSocket.<anonymous closure> (package:web_socket_channel/io.dart:87:24)
#1      _invokeErrorHandler (dart:async/async_error.dart:45:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:272:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _rootRunBinary (dart:async/zone.dart:1378:47)
#5      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#9      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#10     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#11     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#12     _rootRunBinary (dart:async/zone.dart:1378:47)
#13     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#14     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#15     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#16     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#17     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#18     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#19     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#20     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:166:18)
#21     _rootRunBinary (dart:async/zone.dart:1378:47)
#22     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#23     _FutureListener.handleError (dart:async/future_impl.dart:166:20)
#24     Future._propagateToListeners.handleError (dart:async/future_impl.dart:716:47)
```
```
[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.19041.746], locale en-IN)
    • Flutter version 1.26.0-17.3.pre at C:\flutter
    • Framework revision 4b50ca7f7f (3 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.53.0)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost
    ! NO_PROXY does not contain 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.146
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.63

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 4b50ca7f7fbf56be72e54cd200825b760416a356

**Comment by pratt8084** [comment]
issue resolved Thanks
