### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code -1

### ISSUE THREAD

**Issue by FiroshV** [flutter/flutter#75610]
## flutter run -v
```
[ +141 ms] executing: [C:\Android\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +86 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[   +2 ms] executing: [C:\Android\flutter/] git tag --points-at HEAD
[  +64 ms] Exit code 0 from: git tag --points-at HEAD
[   +2 ms] 1.22.6
[  +12 ms] executing: [C:\Android\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Android\flutter/] git ls-remote --get-url origin
[  +47 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +84 ms] executing: [C:\Android\flutter/] git rev-parse --abbrev-ref HEAD
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +78 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +29 ms] executing: C:\Android\sdk\platform-tools\adb.exe devices -l
[  +65 ms] List of devices attached
           cbc2fa10               device product:c9ltedd model:SM_C900F device:c9lte transport_id:1
[   +9 ms] C:\Android\sdk\platform-tools\adb.exe -s cbc2fa10 shell getprop
[ +134 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +267 ms] Generating
C:\Users\steff\OneDrive\Desktop\Flutter\dummy_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant
.java
[  +38 ms] ro.hardware = qcom
[  +57 ms] Starting incremental build...
[   +6 ms] Initializing file store
[  +21 ms] Skipping target: gen_localizations
[  +16 ms] complete
[   +9 ms] Launching lib\main.dart on SM C900F in debug mode...
[  +10 ms] C:\Android\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Android\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Android\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\steff\AppData\Local\Temp\flutter_tools.653106d4\flutter_tool.44259e07\app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[  +25 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s cbc2fa10 shell -x logcat -v time -t 1
[ +141 ms] Exit code 0 from: C:\Android\sdk\platform-tools\adb.exe -s cbc2fa10 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           02-08 12:37:23.395 E/propClient(19116): PropClient failed to load
[   +3 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s cbc2fa10 shell -x logcat -v time -t 1
[ +135 ms] Exit code 0 from: C:\Android\sdk\platform-tools\adb.exe -s cbc2fa10 shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           02-08 12:37:23.537 E/propClient(19119): PropClient failed to load
[  +22 ms] <- compile package:dummy_app/main.dart
[  +16 ms] executing: C:\Android\sdk\platform-tools\adb.exe version
[  +67 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Android\sdk\platform-tools\adb.exe start-server
[  +37 ms] Building APK
[  +27 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[  +44 ms] C:\Android\flutter\bin\cache\artifacts\gradle_wrapper\gradlew.bat mode: 33279 rwxrwxrwx.
[   +3 ms] C:\Users\steff\OneDrive\Desktop\Flutter\dummy_app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +2 ms] Using gradle from C:\Users\steff\OneDrive\Desktop\Flutter\dummy_app\android\gradlew.bat.
[   +1 ms] C:\Users\steff\OneDrive\Desktop\Flutter\dummy_app\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +15 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +111 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +4 ms] executing: [C:\Users\steff\OneDrive\Desktop\Flutter\dummy_app\android/]
C:\Users\steff\OneDrive\Desktop\Flutter\dummy_app\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\steff\OneDrive\Desktop\Flutter\dummy_app\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +881 ms] Welcome to Gradle 5.6.2!
[   +3 ms] Here are the highlights of this release:
[   +3 ms]  - Incremental Groovy compilation
[   +1 ms]  - Groovy compile avoidance
[   +2 ms]  - Test fixtures for Java projects
[   +1 ms]  - Manage plugin versions via settings script
[   +1 ms] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[+3576 ms] > Task :app:compileFlutterBuildDebug
[   +3 ms] [ +156 ms] executing: [C:\Android\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [ +106 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[   +3 ms] [   +1 ms] executing: [C:\Android\flutter/] git tag --points-at HEAD
[   +1 ms] [  +67 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] [        ] 1.22.6
[   +2 ms] [  +13 ms] executing: [C:\Android\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] [        ] origin/stable
[   +2 ms] [        ] executing: [C:\Android\flutter/] git ls-remote --get-url origin
[   +2 ms] [  +51 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[   +1 ms] [  +93 ms] executing: [C:\Android\flutter/] git rev-parse --abbrev-ref HEAD
[   +1 ms] [  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[   +1 ms] [  +59 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [  +27 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +7 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] [ +114 ms] Initializing file store
[   +1 ms] [  +26 ms] Done initializing file store
[  +89 ms] [  +69 ms] Skipping target: gen_localizations
[ +898 ms] [ +853 ms] Skipping target: kernel_snapshot
[ +301 ms] [ +338 ms] Skipping target: debug_android_application
[   +2 ms] [   +1 ms] Persisting file store
[   +2 ms] [  +22 ms] Done persisting file store
[   +1 ms] [  +10 ms] build succeeded.
[  +92 ms] [  +31 ms] "flutter assemble" took 1,531ms.
[   +2 ms] [   +7 ms] ensureAnalyticsSent: 0ms
[   +1 ms] [   +3 ms] Running shutdown hooks
[   +1 ms] [        ] Shutdown hooks complete
[   +1 ms] [   +4 ms] exiting with code 0
[  +94 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +3 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :app:cleanMergeDebugAssets
[  +86 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +2 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugAssets
[ +395 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +9 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +5 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +83 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +2 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugResources UP-TO-DATE
[  +92 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +9 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +2 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +1 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[   +1 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[  +83 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[   +2 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[   +1 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +1 ms] > Task :app:mergeDexDebug UP-TO-DATE
[   +1 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +1 ms] > Task :app:signingConfigWriterDebug UP-TO-DATE
[   +3 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +86 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +2 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[   +2 ms] Compatible side by side NDK version was not found.
[   +1 ms] > Task :app:packageDebug UP-TO-DATE
[ +194 ms] > Task :app:assembleDebug
[   +2 ms] BUILD SUCCESSFUL in 7s
[   +2 ms] 31 actionable tasks: 5 executed, 26 up-to-date
[  +26 ms] Running Gradle task 'assembleDebug'... (completed in 7.4s)
[+2222 ms] Exception: Gradle task assembleDebug failed with exit code -1
[   +5 ms] "flutter run" took 10,843ms.
[   +8 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[ +206 ms] ensureAnalyticsSent: 202ms
[   +4 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[   +7 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

## flutter doctor -v
```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-IN)
    • Flutter version 1.22.6 at C:\Android\flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android
    • ANDROID_SDK_ROOT = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.0)
    • VS Code at C:\Users\steff\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • SM C900F (mobile) • cbc2fa10 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by FiroshV** [comment]
Duplicate of #60465

**Comment by pedromassangocode** [comment]
This seems related to https://github.com/flutter/flutter/issues/60465 but I'm not 100% sure if it is a duplicate.

**Comment by FiroshV** [comment]
@pedromassangocode I have tried reinstalling the whole setup but still am getting this issue

**Comment by darshankawar** [comment]
@FiroshV 
Circling back on this issue to know if you are still facing this issue or not using latest stable version.

**Comment by FiroshV** [comment]
This issue was solved by installing the latest stable version

**Comment by darshankawar** [comment]
Forgot to close. Doing so now based on above comment.
