### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by BhagirathGadhesariya** [flutter/flutter#75626]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#5      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#6      _pluginFromPackage (package:flutter_tools/src/plugins.dart:317:53)
#7      findPlugins (package:flutter_tools/src/plugins.dart:352:27)
<asynchronous suspension>
#8      refreshPluginsList (package:flutter_tools/src/plugins.dart:1136:38)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:242:11)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:960:21)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1190:13)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _runZoned (dart:async/zone.dart:1630:10)
#17     runZoned (dart:async/zone.dart:1550:10)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
```
```
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_IN)
    • Flutter version 1.22.5 at /home/erp/sdks/flutter
    • Framework revision 7891006299 (9 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/erp/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/erp/Android/Sdk
    • Java binary at: /home/erp/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[!] Android Studio
    • Android Studio at /home/erp/Downloads/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • android-studio-dir = /home/erp/Downloads/android-studio
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Moto G 5 Plus (mobile) • ZY223Z83JW • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
flutter_inappwebview-4.0.0+4
flutter_webview_plugin-0.3.11
fluttertoast-7.1.6
path_provider_linux-0.0.1+2
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
webview_flutter-1.0.7

**Comment by TahaTesser** [comment]
Hi @BhagirathGadhesariya 
There was a [fix](https://github.com/flutter/flutter/pull/63540) made recently and merged in Master. Please switch to latest master and try again to see if it works for you.
Thanks.

**Comment by BhagirathGadhesariya** [comment]
@TahaTesser thank you for your replay 
i am update my flutter plugin and not its working proper
