### ISSUE TITLE
flutter_gallery__transition_perf_e2e_ios fails when device is rotated in landscape

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#75647]
List of builds:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20flutter_gallery__transition_perf_e2e_ios

```
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:04.876848-0800 Flutter Gallery[7467:1671670] flutter: > Tooltips@Material
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:06.710099-0800 Flutter Gallery[7467:1671670] flutter: < Success
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:06.710241-0800 Flutter Gallery[7467:1671670] flutter: > Activity Indicator@Cupertino
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.330152-0800 Flutter Gallery[7467:1671670] flutter:
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.330484-0800 Flutter Gallery[7467:1671670] flutter: Warning: A call to tap() with finder "exactly one widget with text "Cupertino" (ignoring offstage widgets): Widget" derived an Offset (Offset(111.2, 427.3)) that would not hit test on the specified widget.
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.330717-0800 Flutter Gallery[7467:1671670] flutter: Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.331394-0800 Flutter Gallery[7467:1671670] flutter: Indeed, Offset(111.2, 427.3) is outside the bounds of the root of the render tree, Size(667.0, 375.0).
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.331853-0800 Flutter Gallery[7467:1671670] flutter: The finder corresponds to this RenderBox: <optimized out>#0ecbd relayoutBoundary=up4
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.332054-0800 Flutter Gallery[7467:1671670] flutter: The hit test result at that offset is: HitTestResult(<optimized out>#dbf7e(<optimized out>#964dc), <optimized out>#bfd78(<BindingBase>))
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.332255-0800 Flutter Gallery[7467:1671670] flutter: #0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:953)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.332443-0800 Flutter Gallery[7467:1671670] flutter: #1      WidgetController.getCenter (package:flutter_test/src/controller.dart:836)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.335142-0800 Flutter Gallery[7467:1671670] flutter: #2      WidgetController.tap (package:flutter_test/src/controller.dart:271)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.335799-0800 Flutter Gallery[7467:1671670] flutter: #3      runDemos (file:///opt/s/w/ir/cache/flutter%20sdk/dev/integration_tests/flutter_gallery/test_driver/run_demos.dart:42)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.336907-0800 Flutter Gallery[7467:1671670] flutter: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.337087-0800 Flutter Gallery[7467:1671670] flutter: #4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.337356-0800 Flutter Gallery[7467:1671670] flutter: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.337544-0800 Flutter Gallery[7467:1671670] flutter: To silence this warning, pass "warnIfMissed: false" to "tap()".
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.337642-0800 Flutter Gallery[7467:1671670] flutter: To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:07.337857-0800 Flutter Gallery[7467:1671670] flutter:
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.112587-0800 Flutter Gallery[7467:1671670] flutter: (The following exception is now available via WidgetTester.takeException:)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.112846-0800 Flutter Gallery[7467:1671670] flutter: Bad state: No element
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.114986-0800 Flutter Gallery[7467:1671670] flutter: #0      Iterable.single (dart:core/iterable.dart:498)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.116315-0800 Flutter Gallery[7467:1671670] flutter: #1      WidgetController.element (package:flutter_test/src/controller.dart:112)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.117304-0800 Flutter Gallery[7467:1671670] flutter: #2      WidgetController.dragUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1181)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.118310-0800 Flutter Gallery[7467:1671670] flutter: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.119109-0800 Flutter Gallery[7467:1671670] flutter: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.119518-0800 Flutter Gallery[7467:1671670] flutter: (elided one frame from package:stack_trace)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.119913-0800 Flutter Gallery[7467:1671670] flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.121391-0800 Flutter Gallery[7467:1671670] flutter: Bad state: No element
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.122725-0800 Flutter Gallery[7467:1671670] flutter: #0      Iterable.single (dart:core/iterable.dart:498)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.123074-0800 Flutter Gallery[7467:1671670] flutter: #1      WidgetController.element (package:flutter_test/src/controller.dart:112)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.123396-0800 Flutter Gallery[7467:1671670] flutter: #2      WidgetController.dragUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1181)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.124027-0800 Flutter Gallery[7467:1671670] flutter: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.124327-0800 Flutter Gallery[7467:1671670] flutter: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.124476-0800 Flutter Gallery[7467:1671670] flutter: (elided one frame from package:stack_trace)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.124946-0800 Flutter Gallery[7467:1671670] flutter: 01:36 +0 ~1: flutter gallery transitions on e2e all demos [E]
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.125413-0800 Flutter Gallery[7467:1671670] flutter:   Test failed. See exception logs above.
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout:   The test description was: all demos
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.125862-0800 Flutter Gallery[7467:1671670] flutter:
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.133191-0800 Flutter Gallery[7467:1671670] flutter: 01:36 +0 ~1 -1: (tearDownAll)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.136105-0800 Flutter Gallery[7467:1671670] flutter: Warning: integration_test test plugin was not detected.
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-05 19:07:12.137126-0800 Flutter Gallery[7467:1671670] flutter: 01:36 +1 ~1 -1: Some tests failed.
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: Failure Details:
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: Failure in method: all demos
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: end of failure 1
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] "/opt/s/w/ir/cache/flutter sdk/bin/flutter" exit code: 1
[flutter_gallery__transition_perf_e2e_ios] [STDERR] Task failed: Executable "/opt/s/w/ir/cache/flutter sdk/bin/flutter" failed with exit code 1.
```

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by godofredoc** [comment]
flutter_gallery_ios__transition_perf is also failing consistently with the same error:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20flutter_gallery_ios__transition_perf

**Comment by jmagman** [comment]
This is another case where the tests are failing because the device is rotated.

**Comment by jmagman** [comment]
Hotfix request to get `flutter_gallery__transition_perf_e2e_ios` passing on the stable branch.

**Comment by christopherfujino** [comment]
> Hotfix request to get `flutter_gallery__transition_perf_e2e_ios` passing on the stable branch.

This would be a test-only hotfix.
