### ISSUE TITLE
Widgets built twice before layout phase in the same frame

### ISSUE THREAD

**Issue by xu-baolin** [flutter/flutter#75680]
This issue is separated from #75308 
How does it happens and repro steps please refer to the original issue.
CC @chunhtai

**Comment by darshankawar** [comment]
@xu-baolin Hi,
Per the PR discussion, I assume you opened this issue to track https://github.com/flutter/flutter/pull/75308#pullrequestreview-585737136
The original issue / PR talks about fixing 2 issues. Which one among them indicates / replicates the `focus manager` issue ?
Could you provide steps to replicate ?

**Comment by xu-baolin** [comment]
https://github.com/flutter/flutter/pull/75308#pullrequestreview-584562834

```dart
  // Regression test for https://github.com/flutter/flutter/issues/72257
  testWidgets('NestedScrollView works well when rebuilding during scheduleWarmUpFrame', (WidgetTester tester) async {
    bool? isScrolled;
   int buildCnt = 0;
    final Widget myApp = MaterialApp(
      home: Scaffold(
        body: StatefulBuilder(
          builder: (BuildContext context, StateSetter setState) {
            return Focus(
              onFocusChange: (_) => setState( (){} ),
              child: NestedScrollView(
                headerSliverBuilder: (BuildContext context, bool boxIsScrolled) {
                  buildCnt++;
                  isScrolled = boxIsScrolled;
                  return <Widget>[
                    const SliverAppBar(
                      expandedHeight: 200,
                      title: Text('Test'),
                    )
                  ];
                },
                body: CustomScrollView(
                  slivers: <Widget>[
                    SliverList(
                      delegate: SliverChildBuilderDelegate(
                        (BuildContext context, int index) {
                          return const Text('');
                        },
                        childCount: 10,
                      ),
                    )
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );

    await tester.pumpWidget(myApp, Duration.zero, EnginePhase.build);
    expect(isScrolled, false);
    expect(buildCnt, 2);
    expect(tester.takeException(), isNull);
  });
```

**Comment by darshankawar** [comment]
@xu-baolin 
Running above test leads to below:

<details>
<summary> test result log </summary>

```
Testing started at 3:45 PM ...
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter --no-color test --machine --start-paused --plain-name "NestedScrollView works well when rebuilding during scheduleWarmUpFrame" test/widget_test.dart

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 798 pos 14:
'position.hasContentDimensions && position.hasPixels': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      _NestedScrollCoordinator.hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:798:14)
#3      NestedScrollViewState._handleHasScrolledBodyChanged (package:flutter/src/widgets/nested_scroll_view.dart:602:51)
#4      _NestedScrollCoordinator.updateShadow (package:flutter/src/widgets/nested_scroll_view.dart:806:50)
#5      _NestedScrollController._scheduleUpdateShadow.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:1303:21)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#8      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:969:9)
#11     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#12     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:956:27)
#13     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#16     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#17     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#18     main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/webtest/test/widget_test.dart:82:18)
#19     main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/webtest/test/widget_test.dart:43:89)
#20     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 798 pos 14:
'position.hasContentDimensions && position.hasPixels': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      _NestedScrollCoordinator.hasScrolledBody (package:flutter/src/widgets/nested_scroll_view.dart:798:14)
#3      NestedScrollViewState._handleHasScrolledBodyChanged (package:flutter/src/widgets/nested_scroll_view.dart:602:51)
#4      _NestedScrollCoordinator.updateShadow (package:flutter/src/widgets/nested_scroll_view.dart:806:50)
#5      _NestedScrollController._scheduleUpdateShadow.<anonymous closure> (package:flutter/src/widgets/nested_scroll_view.dart:1303:21)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#8      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:969:9)
#11     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#12     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:956:27)
#13     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:522:22)
#16     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#17     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:519:27)
#18     main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/webtest/test/widget_test.dart:82:18)
#19     main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/webtest/test/widget_test.dart:43:89)
#20     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: <2>
  Actual: <1>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/webtest/test/widget_test.dart:84:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...

This was caught by the test expectation on the following line:
  file:///Users/dhs/Documents/NCFlutter/webtest/test/widget_test.dart line 84
The test description was:
  NestedScrollView works well when rebuilding during scheduleWarmUpFrame
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (3) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: NestedScrollView works well when rebuilding during scheduleWarmUpFrame



```

</details>

mainly, throws below exception:

`══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 798 pos 14:
'position.hasContentDimensions && position.hasPixels': is not true.`

Is this the correct interpretation of the the issue logged ?

**Comment by xu-baolin** [comment]
This will be fixed by the original issue.

**Comment by xu-baolin** [comment]
After the original issue fixed, it will build twice still.

**Comment by Piinks** [comment]
Just came across this during triage, could https://github.com/flutter/flutter/issues/11599 be related?

**Comment by maheshmnj** [comment]
Hello @xu-baolin,  I verified this issue on the latest master channel and it seems that this is fixed. the test fails with actualy `buildCnt = 1`, So I believe that this is fixed.


### Logs
```
mahesh@Maheshs-MacBook-Air-M1 flutter_issue % flutter test
00:01 +0: NestedScrollView works well when rebuilding during scheduleWarmUpFrame                                           
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <2>
  Actual: <1>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/mahesh/Desktop/flutter_issue/test/widget_test.dart:56:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/mahesh/Desktop/flutter_issue/test/widget_test.dart line 56
The test description was:
  NestedScrollView works well when rebuilding during scheduleWarmUpFrame
════════════════════════════════════════════════════════════════════════════════════════════════════
00:01 +0 -1: NestedScrollView works well when rebuilding during scheduleWarmUpFrame [E]                                    
  Test failed. See exception logs above.
  The test description was: NestedScrollView works well when rebuilding during scheduleWarmUpFrame
  

To run this test again: /Users/mahesh/Development/flutter_master/bin/cache/dart-sdk/bin/dart test /Users/mahesh/Desktop/flutter_issue/test/widget_test.dart -p vm --plain-name 'NestedScrollView works well when rebuilding during scheduleWarmUpFrame'
00:01 +0 -1: Some tests failed. 
```

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel feat-39118, 3.7.0-10.0.pre.68, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-10.0.pre.68 on channel feat-39118 at /Users/mahesh/Development/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/mahesh/Development/flutter/bin/flutter, which is not inside your
      current Flutter SDK checkout at /Users/mahesh/Development/flutter_master. Consider adding
      /Users/mahesh/Development/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/mahesh/Development/flutter/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/mahesh/Development/flutter_master. Consider adding
      /Users/mahesh/Development/flutter_master/bin to the front of your path.
    ! Upstream repository https://github.com/maheshmnj/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/maheshmnj/flutter.git to dismiss this error.
    • Framework revision 34679a7c65 (4 weeks ago), 2022-12-20 14:16:43 -0500
    • Engine revision 3330cce605
    • Dart version 3.0.0 (build 3.0.0-35.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details> 


Closing as fixed. Incase you still encounter the issue, then please feel free to write in the comments and we will reopen it.
