### ISSUE TITLE
Windows agents are stuck

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#75706]
Starting with https://github.com/flutter/flutter/commit/68c96f100e42ab3dbf43e61e9e2fc875a2d50cb8, it looks like some or all of the Windows agents on the framework dashboard are not running jobs. The tree is now reopened, so this is now the cause of the tree closure.

**Comment by godofredoc** [comment]
The agents are failing because of a backend authentication error:

```
ERROR: AuthenticatedClientError:
  URI: https://flutter-dashboard.appspot.com/api/reserve-task
  HTTP Status: 502
  Response body:
<html>^M
<head><title>502 Bad Gateway</title></head>^M
<body>^M
<center><h1>502 Bad Gateway</h1></center>^M
<hr><center>nginx</center>^M
</body>^M
</html>^M

#0      AuthenticatedClient.send (package:cocoon_agent/src/agent.dart:28:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91:38)
<asynchronous suspension>
#2      BaseClient.post (package:http/src/base_client.dart:32:7)
#3      Agent._cocoon (package:cocoon_agent/src/agent.dart:84:31)
<asynchronous suspension>
#4      Agent.reserveTask (package:cocoon_agent/src/agent.dart:105:46)
<asynchronous suspension>
#5      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart:97:41)
<asynchronous suspension>
#6      ContinuousIntegrationCommand.run.<anonymous closure> (package:cocoon_agent/src/commands/ci.dart)
#7      _rootRun (dart:async/zone.dart:1190:13)
#8      _CustomZone.run (dart:async/zone.dart:1093:19)
#9      _runZoned (dart:async/zone.dart:1630:10)
#10     runZonedGuarded (dart:async/zone.dart:1618:12)
#11     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:66:13)
<asynchronous suspension>
#12     main (file:///C:/Users/flutter/cocoon/agent/bin/agent.dart:61:19)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

../../runtime/vm/thread_pool.cc: 299: error: Could not start worker thread: result = 22.
version=2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"
pid=2104, thread=2928, isolate_group=(nil)(0000000000000000), isolate=(nil)(0000000000000000)
isolate_instructions=0, vm_instructions=7ff67ce2dde0
  pc 0x00007ff67d0569c2 fp 0x000000d2298ff5f0 Dart_IsPrecompiledRuntime+0x23cd52
-- End of DumpStackTrace
```

**Comment by godofredoc** [comment]
Logs from backend:

```
gRPC Error (code: 14, codeName: UNAVAILABLE, message: The service is temporarily unavailable., details: [])
```

This is a transient error happening once approximately every three hours. The agent should be updated to be resilient to this type of errors.

**Comment by godofredoc** [comment]
Agents were restarted, we'll keep this bug open for reference until we complete the migration of devicelab to luci.

**Comment by godofredoc** [comment]
Depending on the ETA to get luci windows test beds we should reprioritize this bug.

**Comment by CaseyHillers** [comment]
Windows devicelab bots are now running on LUCI
