### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException: 

### ISSUE THREAD

**Issue by witte-genie** [flutter/flutter#75741]
```
C:\Users\kamra\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe\gradle-6.7-all.zip.lck (Access is denied)         at java.io.RandomAccessFile.open0(Native Method)         at java.io.RandomAccessFile.open(RandomAccessFile.java:316)         at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)         at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)         at org.gradle.wrapper.Install.createDist(Install.java:48)         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61) Running Gradle task 'assembleDebug'... Running Gradle task 'assembleDebug'... Done                      1,500ms [!] Gradle threw an error while downloading artifacts from the network. Retrying to download... Exception in thread "main" java.io.FileNotFoundException: C:\Users\kamra\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe\gradle-6.7-all.zip.lck (Access is denied)         at java.io.RandomAccessFile.open0(Native Method)         at java.io.RandomAccessFile.open(RandomAccessFile.java:316)         at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)         at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)         at org.gradle.wrapper.Install.createDist(Install.java:48)         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61) Running Gradle task 'assembleDebug'... Running Gradle task 'assembleDebug'... Done                        560ms [!] Gradle threw an error while downloading artifacts from the network. Retrying to download... Exception: Gradle task assembleDebug failed with exit code 1

```
Everything is installed correctly but this issue is not being resilved anyone please help me with it

**Comment by darshankawar** [comment]
@witte-genie 
The error log shows:

`] Gradle threw an error while downloading artifacts from the network. Retrying to download... Exception:`

That may indicate it could be network issue from your end. Can you try to switch network and see if it helps ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
