### ISSUE TITLE
App Crashes when using CameraController takePicture Method

### ISSUE THREAD

**Issue by ZiiwareJordanc** [flutter/flutter#75803]
Device: Cipherlabs RS31
Android Api: 21

If the device is laid flat on a table and CameraControllers take picture method is run, my device crashes and feeds back:

```
E/AndroidRuntime(18352): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
E/AndroidRuntime(18352): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:58)
E/AndroidRuntime(18352): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:53)
E/AndroidRuntime(18352): 	at io.flutter.plugins.camera.Camera.runPictureCapture(Camera.java:552)
E/AndroidRuntime(18352): 	at io.flutter.plugins.camera.Camera.access$1500(Camera.java:73)
E/AndroidRuntime(18352): 	at io.flutter.plugins.camera.Camera$3.processCapture(Camera.java:493)
E/AndroidRuntime(18352): 	at io.flutter.plugins.camera.Camera$3.onCaptureCompleted(Camera.java:442)
E/AndroidRuntime(18352): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18352): 	at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
E/AndroidRuntime(18352): 	at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
E/AndroidRuntime(18352): 	at android.os.Handler.handleCallback(Handler.java:836)
E/AndroidRuntime(18352): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(18352): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime(18352): 	at android.app.ActivityThread.main(ActivityThread.java:6251)
E/AndroidRuntime(18352): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18352): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
E/AndroidRuntime(18352): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)`
Into my console.
```

As for simple setup to this:
takePicture Wrapper:

```dart
Future<File> takePicture(CameraController controller, String fileName) async {
    final localImagePath = await _pathBuilder.retrieveLocalImagePath(fileName);
    File image = File(localImagePath);

    if (await image.exists()) await image.delete();

    try {
      var imageFile = await controller.takePicture();
      await imageFile.saveTo(localImagePath);
    } on CameraException catch (e) {
      /// An image already exists at this path (likely a re-taken picture)
      /// This should never happen because we delete the image before re-taking
      print(e);
    }
    return image;
  }
```

Retrieve camera description:
```dart
static Future<CameraDescription> getCamera() async {
    WidgetsFlutterBinding.ensureInitialized();
    final cameras = await availableCameras();
    final firstCamera = cameras.first;
    return firstCamera;
  }
```
  Build camera controller
```
CameraController controller = CameraController(
                      _cameraDescription, ResolutionPreset.max)`
```

Flutter Doctor:

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-CA)
    • Flutter version 1.22.6 at /Users/jordanc/Flutter/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jordanc/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

```

</details>

Even though studio says plugins are not installed my plugins tab says otherwise

**Comment by TahaTesser** [comment]
Hi @ZiiwareJordanc 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/75133
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
