### ISSUE TITLE
flutter_gallery__transition_perf_e2e_ios failing consistently on mac 10.15.7 and ios 14

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#75800]

**Comment by godofredoc** [comment]
flutter_gallery__transition_perf_e2e_ios has been failing consistently since https://chromium.googlesource.com/external/github.com/flutter/flutter/+/d031a61a623894f1cda552e1561ee67ca3f69144

Logs:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20flutter_gallery__transition_perf_e2e_ios


```
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-10 05:13:53.692071-0800 Flutter Gallery[1844:324893] flutter: < VideoDemo initController "butterfly" done
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-02-10 05:13:53.809060-0800 Flutter Gallery[1844:324893] flutter: < VideoDemo initController "bee" done
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: * thread #12, name = 'io.flutter.1.raster', stop reason = EXC_BAD_ACCESS (code=1, address=0xc31ef8dd0)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout:     frame #0: 0x00000001b10d2474 libobjc.A.dylib`objc_msgSend + 20
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: libobjc.A.dylib`objc_msgSend:
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: ->  0x1b10d2474 <+20>: ldr    x11, [x16, #0x10]
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout:     0x1b10d2478 <+24>: and    x10, x11, #0xfffffffffffe
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout:     0x1b10d247c <+28>: tbnz   w11, #0x0, 0x1b10d24d0    ; <+112>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout:     0x1b10d2480 <+32>: eor    x12, x1, x1, lsr #7
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: Target 0: (Flutter Gallery) stopped.
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: Unhandled exception:
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: DriverError: Failed to fulfill RequestData due to remote error
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: Original error: ext.flutter.driver: (112) Service has disappeared
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: Original stack trace:
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: 
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: 
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: #0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:323:7)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: #1      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:508:39)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: #2      integrationDriver (package:integration_test/integration_test_driver.dart:71:29)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: <asynchronous suspension>
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stderr: Failed to stop app
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] "/opt/s/w/ir/k/flutter sdk/bin/flutter" exit code: 1
[flutter_gallery__transition_perf_e2e_ios] [STDERR] Task failed: Executable "/opt/s/w/ir/k/flutter sdk/bin/flutter" failed with exit code 1.
[flutter_gallery__transition_perf_e2e_ios] [STDERR] ```

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by jmagman** [comment]
@justinmc just filed this, forward duplicating since he already posted that link in discord https://github.com/flutter/flutter/issues/75802
