### ISSUE TITLE
flutter_gallery_ios32__start_up fails connecting to service protocol, HttpException: Connection closed before full header was received

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#75831]
List of builds:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20flutter_gallery_ios32__start_up

```
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [ +263 ms] Process 3138 detached
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [   +6 ms] Application launched on the device. Waiting for observatory port.
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [   +6 ms] Observatory URL on device: http://127.0.0.1:56239/
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [   +7 ms] Attempting to forward device port 56239 to host port 50146
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [        ] executing: /opt/s/w/ir/k/recipe_cleanup/tmpnFrVuE/flutter sdk/bin/cache/artifacts/usbmuxd/iproxy 50146:56239 --udid 822ef7958bba573829d85eef4df6cbdd86593730
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [+1013 ms] Forwarded port ForwardedPort HOST:50146 to DEVICE:56239
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [        ] Forwarded host port 50146 to device port 56239 for Observatory
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [  +14 ms] Installing and launching... (completed in 11.8s)
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [   +7 ms] Connecting to service protocol: http://127.0.0.1:50146/
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [  +25 ms] Warning: Unable to create restoration in progress marker file
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [  +42 ms] Fail to connect to service protocol: http://127.0.0.1:50146/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:50146/ws
[flutter_gallery_ios32__start_up] [STDOUT] stderr: [        ] failed to connect to http://127.0.0.1:50146/
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [   +3 ms] "flutter run" took 20,650ms.
[flutter_gallery_ios32__start_up] [STDOUT] stderr: [   +4 ms] 
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:657:9)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1174:12)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1026:27)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #5      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:280:9)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #9      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:66:9)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #12     run.<anonymous closure> (package:flutter_tools/runner.dart:64:12)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #14     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #15     runInContext (package:flutter_tools/src/context_runner.dart:75:10)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            #16     main (package:flutter_tools/executable.dart:92:3)
[flutter_gallery_ios32__start_up] [STDOUT] stderr:            <asynchronous suspension>
[flutter_gallery_ios32__start_up] [STDOUT] stderr: 
[flutter_gallery_ios32__start_up] [STDOUT] stderr: 
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [   +2 ms] ensureAnalyticsSent: 0ms
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [        ] Running shutdown hooks
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [        ] Shutdown hook priority 4
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [        ] Shutdown hooks complete
[flutter_gallery_ios32__start_up] [STDOUT] stdout: [        ] exiting with code 2
[flutter_gallery_ios32__start_up] [STDOUT] "/opt/s/w/ir/k/recipe_cleanup/tmpnFrVuE/flutter sdk/bin/flutter" exit code: 2
```

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by godofredoc** [comment]
flutter_gallery__transition_perf_e2e_ios32 is failing with the same error.

Link to logs:

https://ci.chromium.org/p/flutter/builders/prod/Mac_staging%20flutter_gallery__transition_perf_e2e_ios32

**Comment by godofredoc** [comment]
Removing team:infra to get this prioritized on critical bug triage.

**Comment by jmagman** [comment]
I'm able to reproduce on my iPhone 4s.  `flutter run --device-timeout 5 --no-android-gradle-daemon --no-publish-port --verbose --profile --trace-startup` works (what the test is eventually failing on), but that test always fails...

**Comment by jmagman** [comment]
Building and then running with `use-application-binary` reproduces.
```
$ flutter build ios -v --profile  
$ flutter run --device-timeout 5 --no-android-gradle-daemon --verbose --profile --trace-startup -d <device-id> --use-application-binary="..."
```

**Comment by jmagman** [comment]
There's a few of these open like https://github.com/flutter/flutter/issues/58676.  The app is running, the tool is just not connecting to the VM.

**Comment by jmagman** [comment]
I think the way forward with these broken 32-bit iOS tests is to replace ones that rely on `flutter` developer workflows like `flutter drive` with tests that only rely on native iOS testing workflows.  So continue to test that the app works correctly on a customer device, but less so that debug/profiling developer workflows work.

The following is a Devicelab integration test that demonstrates this pattern.  Note flutter build is called, but not flutter drive or flutter run.  Installation, app launch, and testing the release version of the app is outsourced to Xcode tooling (`xcodebuild test`). 
```dart
final String projectDirectory = '${flutterDirectory.path}/dev/integration_tests/flutter_gallery';

await inDirectory(projectDirectory, () async {
  await flutter(
    'build',
    options: <String>[
      'ios',
      '-v',
      '--release',
      '--config-only',
    ],
  );
});

final Device device = await devices.workingDevice;

await exec(
  'xcodebuild',
  <String>[
    '-workspace',
    'Runner.xcworkspace',
    '-scheme',
    'Runner',
    '-configuration',
    'Release',
    '-destination',
    'id=${device.deviceId}',
    'test',
    'COMPILER_INDEX_STORE_ENABLE=NO',
  ],
  workingDirectory: path.join(projectDirectory, 'ios'),
);

return TaskResult.success(null);
```
This example would run any new Flutter Gallery XCUITest integration tests, such as the following:
```obj-c
@implementation GalleryUITests
...
- (void)testLaunch {
    XCUIApplication *app = [[XCUIApplication alloc] init];
    [app launch];

    // Basic smoke test that the app launched and any UI element was loaded.
    XCTAssertTrue([app.otherElements.firstMatch waitForExistenceWithTimeout:60.0]);
}
```
