### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'dependencies' was called on null.Receiver: nullTried calling: dependencies

### ISSUE THREAD

**Issue by BreezyD06** [flutter/flutter#75902]
## Command
```
flutter update-packages --force-upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'dependencies' was called on null.
Receiver: null
Tried calling: dependencies
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      createTemporaryFlutterSdk (package:flutter_tools/src/commands/update_packages.dart:1454:60)
#2      UpdatePackagesCommand.runCommand (package:flutter_tools/src/commands/update_packages.dart:319:33)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [version 10.0.18363.1316], locale fr-BJ)
    • Flutter version 1.22.6 at C:\Users\danst\OneDrive\Documents\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\danst\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.1)
    • VS Code at C:\Users\danst\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[!] Connected device
    ! Device 05157119CH101055 is offline.

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6
### Plugins
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_database-6.0.0

**Comment by pedromassangocode** [comment]
Hi @BreezyD06 
I see there's an open issue (https://github.com/flutter/flutter/issues/75777) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
