### ISSUE TITLE
I am receiving this exception when calling Navigator.push or Navigator.pop in a page that contains Google Maps

### ISSUE THREAD

**Issue by josechagas** [flutter/flutter#75910]
<details>
<summary>logs</summary>

```bash
/flutter ( 6210): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method map#update on channel plugins.flutter.io/google_maps_0)
E/flutter ( 6210): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6210):
E/flutter ( 6210): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6210): #2 MethodChannelGoogleMapsFlutter.updateMapOptions (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:225:27)
E/flutter ( 6210): #3 GoogleMapController._updateMapOptions (package:google_maps_flutter/src/controller.dart:103:39)
E/flutter ( 6210): #4 _GoogleMapState._updateOptions (package:google_maps_flutter/src/google_map.dart:286:16)
E/flutter ( 6210):
E/flutter ( 6210): #5 _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:269:5)
E/flutter ( 6210): #6 StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 6210): #7 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #8 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #9 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #10 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #11 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #12 RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 6210): #13 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 6210): #14 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #15 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #16 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #17 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #18 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #19 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #20 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #21 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #22 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #23 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #24 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #25 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #28 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #29 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #30 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #31 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #32 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #33 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #34 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #35 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #36 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #37 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #38 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #40 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #41 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #42 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #43 Sliv
E/flutter ( 6210): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method markers#update on channel plugins.flutter.io/google_maps_0)
E/flutter ( 6210): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6210):
E/flutter ( 6210): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6210): #2 MethodChannelGoogleMapsFlutter.updateMarkers (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:245:27)
E/flutter ( 6210): #3 GoogleMapController._updateMarkers (package:google_maps_flutter/src/controller.dart:115:39)
E/flutter ( 6210): #4 _GoogleMapState._updateMarkers (package:google_maps_flutter/src/google_map.dart:293:16)
E/flutter ( 6210):
E/flutter ( 6210): #5 _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:270:5)
E/flutter ( 6210): #6 StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 6210): #7 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #8 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #9 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #10 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #11 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #12 RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 6210): #13 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 6210): #14 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #15 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #16 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #17 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #18 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #19 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #20 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #21 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #22 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #23 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #24 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #25 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #28 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #29 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #30 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #31 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #32 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #33 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #34 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #35 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #36 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #37 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #38 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #40 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #41 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #42 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #43 Sliver
E/flutter ( 6210): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method polygons#update on channel plugins.flutter.io/google_maps_0)
E/flutter ( 6210): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6210):
E/flutter ( 6210): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6210): #2 MethodChannelGoogleMapsFlutter.updatePolygons (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:263:27)
E/flutter ( 6210): #3 GoogleMapController._updatePolygons (package:google_maps_flutter/src/controller.dart:127:39)
E/flutter ( 6210): #4 _GoogleMapState._updatePolygons (package:google_maps_flutter/src/google_map.dart:301:16)
E/flutter ( 6210):
E/flutter ( 6210): #5 _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:271:5)
E/flutter ( 6210): #6 StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 6210): #7 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #8 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #9 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #10 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #11 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #12 RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 6210): #13 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 6210): #14 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #15 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #16 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #17 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #18 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #19 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #20 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #21 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #22 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #23 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #24 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #25 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #28 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #29 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #30 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #31 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #32 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #33 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #34 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #35 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #36 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #37 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #38 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #40 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #41 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #42 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #43 Sl
E/flutter ( 6210): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method polylines#update on channel plugins.flutter.io/google_maps_0)
E/flutter ( 6210): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6210):
E/flutter ( 6210): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6210): #2 MethodChannelGoogleMapsFlutter.updatePolylines (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:281:27)
E/flutter ( 6210): #3 GoogleMapController._updatePolylines (package:google_maps_flutter/src/controller.dart:139:39)
E/flutter ( 6210): #4 _GoogleMapState._updatePolylines (package:google_maps_flutter/src/google_map.dart:309:16)
E/flutter ( 6210):
E/flutter ( 6210): #5 _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:272:5)
E/flutter ( 6210): #6 StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 6210): #7 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #8 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #9 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #10 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #11 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #12 RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 6210): #13 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 6210): #14 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #15 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #16 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #17 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #18 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #19 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #20 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #21 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #22 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #23 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #24 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #25 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #28 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #29 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #30 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #31 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #32 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #33 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #34 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #35 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #36 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #37 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #38 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #40 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #41 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #42 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #43
E/flutter ( 6210): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method circles#update on channel plugins.flutter.io/google_maps_0)
E/flutter ( 6210): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6210):
E/flutter ( 6210): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6210): #2 MethodChannelGoogleMapsFlutter.updateCircles (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:299:27)
E/flutter ( 6210): #3 GoogleMapController._updateCircles (package:google_maps_flutter/src/controller.dart:151:39)
E/flutter ( 6210): #4 _GoogleMapState._updateCircles (package:google_maps_flutter/src/google_map.dart:317:16)
E/flutter ( 6210):
E/flutter ( 6210): #5 _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:273:5)
E/flutter ( 6210): #6 StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 6210): #7 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #8 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #9 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #10 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #11 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #12 RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 6210): #13 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 6210): #14 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #15 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #16 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #17 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #18 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #19 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #20 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #21 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #22 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #23 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #24 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #25 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #28 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #29 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #30 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #31 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #32 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #33 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #34 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #35 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #36 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #37 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #38 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #40 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #41 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #42 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #43 Sliver
E/flutter ( 6210): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method tileOverlays#update on channel plugins.flutter.io/google_maps_0)
E/flutter ( 6210): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 6210):
E/flutter ( 6210): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 6210): #2 MethodChannelGoogleMapsFlutter.updateTileOverlays (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:325:27)
E/flutter ( 6210): #3 GoogleMapController._updateTileOverlays (package:google_maps_flutter/src/controller.dart:162:39)
E/flutter ( 6210): #4 _GoogleMapState._updateTileOverlays (package:google_maps_flutter/src/google_map.dart:325:16)
E/flutter ( 6210):
E/flutter ( 6210): #5 _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:274:5)
E/flutter ( 6210): #6 StatefulElement.update (package:flutter/src/widgets/framework.dart:4815:58)
E/flutter ( 6210): #7 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #8 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #9 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #10 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #11 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #12 RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
E/flutter ( 6210): #13 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
E/flutter ( 6210): #14 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #15 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #16 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #17 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #18 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #19 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #20 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #21 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #22 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #23 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #24 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
E/flutter ( 6210): #25 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #28 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #29 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #30 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #31 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #32 ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
E/flutter ( 6210): #33 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #34 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #35 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6210): #36 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #37 StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
E/flutter ( 6210): #38 Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
E/flutter ( 6210): #39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6210): #40 Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6210): #41 StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
E/flutter ( 6210): #42 Element.updateChild (package:flutter/src/widgets/framework.dart:331
```

</details>

**Comment by TahaTesser** [comment]
Hi @josechagas 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by josechagas** [comment]
I am sorry I did not answered you. It is not happening on new versions.

by the way, thank you
