### ISSUE TITLE
Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4334 pos 12: '<optimized out>': is not true. while switching between screens

### ISSUE THREAD

**Issue by mytja** [flutter/flutter#75928]
## Code

1. dashboard.dart
```
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'constants/constants.dart';
import 'orders.dart';
import 'package:http/http.dart' as http;

class Dashboard extends StatefulWidget {
  Dashboard({Key key, this.username, this.password}) : super(key: key);

  final String username;
  final String password;

  @override
  DashboardMain createState() => DashboardMain();
}

class DashboardMain extends State<Dashboard> {
  Future<String> getOrders(String password, String username) async {
    if (password == "" || username == "") {
      print("None!");
      return "None";
    } else {
      var response = await http.get(SERVER_URL_ORDERS +
          "?username=" +
          username +
          "&password=" +
          password);
      return response.body.toString();
    }
  }

  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;

    String username = widget.username;

    return MaterialApp(
      routes: {
        'orders': (context) => Orders(
              username: widget.username,
              password: widget.password,
            ),
      },
      home: Scaffold(
        body: Column(children: <Widget>[
          Container(
            height: 25,
          ),
          Text(
            "Hello, " + username,
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 30),
          ),
          Text(
            "Welcome to the Dashboard",
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
          )
        ]),
        appBar: AppBar(title: Text("Dashboard")),
        drawer: Drawer(
          child: ListView(
            padding: EdgeInsets.zero,
            children: <Widget>[
              DrawerHeader(
                child: Text("Dashboard"),
                decoration: BoxDecoration(
                  color: Colors.blue,
                ),
              ),
              ListTile(
                title: Text("Dashboard"),
              ),
              ListTile(
                title: Text('Orders'),
                onTap: () async {
                  var json = await getOrders(widget.password, widget.username);
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => Orders(
                            username: widget.username,
                            password: widget.password,
                            json: json)),
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

2. orders.dart
```
import 'package:flutter/material.dart';
import 'package:onlineprinterapp/dashboard.dart';

class Orders extends StatefulWidget {
  Orders({Key key, this.title, this.username, this.password, this.json})
      : super(key: key);

  final String title;
  final String username;
  final String password;
  final String json;

  @override
  OrdersMain createState() => OrdersMain();
}

class OrdersMain extends State<Orders> {
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;

    print(widget.json);

    return MaterialApp(
        home: Scaffold(
      body: Column(
        children: <Widget>[Text("OK")],
      ),
      appBar: AppBar(title: Text("App")),
      drawer: Drawer(
        child: ListView(
          padding: EdgeInsets.zero,
          children: <Widget>[
            DrawerHeader(
              child: Text("App"),
              decoration: BoxDecoration(
                color: Colors.blue,
              ),
            ),
            ListTile(
              title: Text("Dashboard"),
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (context) => Dashboard(
                            username: widget.username,
                            password: widget.password,
                          )),
                );
              },
            ),
            ListTile(
              title: Text('Orders'),
            ),
          ],
        ),
      ),
    ));
  }
}
```

**Expected results:**
Go to screen called Orders without problem

**Actual results:** 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4334 pos 12: '<optimized out>': is not true.
```

<details>
  <summary>Logs</summary>

```
[        ] D/ViewRootImpl@ae397bc[MainActivity](20836): MSG_RESIZED: frame=(0,0,720,1600) ci=(0,68,0,84) vi=(0,68,0,84) or=1
[  +26 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)0 dur=11 res=0x1 s={true 492524150784} ch=false
[ +321 ms] I/flutter (20836): {body: OK, info: Authorized, loginType: 1, responseCode: 200, userId: 2}
[   +8 ms] I/flutter (20836): Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4334 pos 12: '<optimized out>': is not true.
[ +408 ms] I/flutter (20836): {body: OK, info: Authorized, loginType: 1, responseCode: 200, userId: 2}
[  +11 ms] I/flutter (20836): Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4334 pos 12: '<optimized out>': is not true.
[+1508 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): ViewPostIme pointer 0
[ +138 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): ViewPostIme pointer 1
[+4491 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): ViewPostIme pointer 0
[ +104 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): ViewPostIme pointer 1
[+4291 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): ViewPostIme pointer 0
[  +96 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): ViewPostIme pointer 1
[+3517 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): ViewPostIme pointer 0
[  +60 ms] D/ViewRootImpl@ae397bc[MainActivity](20836): ViewPostIme pointer 1
[ +314 ms] E/flutter (20836): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4334 pos 12: '<optimized out>': is not true.
[        ] E/flutter (20836): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
[        ] E/flutter (20836): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] E/flutter (20836): #2      NavigatorState._pushEntry (package:flutter/src/widgets/navigator.dart:4334:12)
[        ] E/flutter (20836): #3      NavigatorState.push (package:flutter/src/widgets/navigator.dart:4270:5)
[        ] E/flutter (20836): #4      Navigator.push (package:flutter/src/widgets/navigator.dart:2091:35)
[        ] E/flutter (20836): #5      DashboardMain.build.<anonymous closure> (package:onlineprinterapp/dashboard.dart:83:29)
[        ] E/flutter (20836): <asynchronous suspension>
[        ] E/flutter (20836): #6      DashboardMain.build.<anonymous closure> (package:onlineprinterapp/dashboard.dart)
[        ] E/flutter (20836): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:985:20)
[        ] E/flutter (20836): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1101:38)
[        ] E/flutter (20836): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[        ] E/flutter (20836): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
[        ] E/flutter (20836): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
[        ] E/flutter (20836): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
[        ] E/flutter (20836): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
[        ] E/flutter (20836): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:372:20)
[        ] E/flutter (20836): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:348:22)
[        ] E/flutter (20836): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:268:11)
[        ] E/flutter (20836): #17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:303:7)
[        ] E/flutter (20836): #18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:267:5)
[        ] E/flutter (20836): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:225:7)
[        ] E/flutter (20836): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:208:7)
[        ] E/flutter (20836): #21     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] E/flutter (20836): #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter (20836): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] E/flutter (20836): #24     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] E/flutter (20836): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
```

```
   info - Unused import: 'package:fluttertoast/fluttertoast.dart' - lib\dashboard.dart:3:8 - unused_import
   info - This function has a return type of 'FutureOr<String>', but doesn't end with a return statement - lib\dashboard.dart:19:18 - missing_return
   info - The value of the local variable 'prefs' isn't used - lib\dashboard.dart:20:23 - unused_local_variable
   info - The value of the local variable 'width' isn't used - lib\dashboard.dart:38:12 - unused_local_variable
   info - The value of the local variable 'height' isn't used - lib\dashboard.dart:39:12 - unused_local_variable
   info - The value of the local variable 'usertext' isn't used - lib\dashboard.dart:42:12 - unused_local_variable
   info - The value of the local variable 'width' isn't used - lib\login.dart:38:12 - unused_local_variable
   info - The value of the local variable 'height' isn't used - lib\login.dart:39:12 - unused_local_variable
   info - Unused import: 'dart:convert' - lib\old\error_login.dart:1:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\old\error_login.dart:7:24 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\old\error_login.dart:7:41 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\old\error_login.dart:7:58 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\old\error_login.dart:10:16 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\old\error_login.dart:11:16 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\old\error_login.dart:12:16 - non_constant_identifier_names
   info - The value of the local variable 'width' isn't used - lib\old\error_login.dart:20:12 - unused_local_variable
   info - The value of the local variable 'height' isn't used - lib\old\error_login.dart:21:12 - unused_local_variable
   info - The value of the local variable 'width' isn't used - lib\orders.dart:19:12 - unused_local_variable
   info - The value of the local variable 'height' isn't used - lib\orders.dart:20:12 - unused_local_variable
   info - The value of the local variable 'pref' isn't used - lib\wrappers\preferences.dart:36:11 - unused_local_variable
   info - The value of the local variable 'pref' isn't used - lib\wrappers\preferences.dart:38:11 - unused_local_variable
   info - The value of the local variable 'pref' isn't used - lib\wrappers\preferences.dart:40:11 - unused_local_variable
```

```
[√] Flutter (Channel dev, 1.23.0-18.0.pre, on Microsoft Windows 7 [Version 6.1.7601])
    • Flutter version 1.23.0-18.0.pre at D:\flutter2\flutter
    • Framework revision 37ebe3d82a (4 months ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (4 available)
    • SM A217F (mobile) • R58N70B39YW • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 6.1.7601]
    • Web Server (web)  • web-server  • web-javascript • Flutter Tools
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

</details>

I'm really desperate, since I 1 week ago had a same issue on other screen, and I had to rewrote it, but, even though I rewrote this one, it still doesn't work.

I tried everything, I could find on web, but I just couldn't solve this problem... :cry:

**Comment by mytja** [comment]
Figured it out, I had a setState() during build...
