### ISSUE TITLE
Hot restart causes exception: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by easeccy** [flutter/flutter#75976]
Hot restart randomly crashes the app on web debugging. 

## Steps to Reproduce

1. Debug Flutter app in Chrome with VSCode
2. Perform hot reload a few times

## Logs

<details>
<summary>flutter run --verbose</summary>

```
[ +489 ms] wasm streaming compile failed: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
[   +2 ms] falling back to ArrayBuffer instantiation
[ +654 ms] failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
[   +1 ms] null
[   +3 ms] RuntimeError: abort(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.
               at La (https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:149:56)
               at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:251:379

```

</details>
<details>
<summary>flutter doctor --verbose</summary>

```
[√] Flutter (Channel beta, 1.26.0-17.3.pre, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.26.0-17.3.pre at C:\flutter
    • Framework revision 4b50ca7f7f (9 days ago), 2021-02-04 19:44:27 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\enes\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\enes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Redmi Note 8 Pro (mobile) • 7lx48pbalvvctg45 • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @easeccy 
Thanks for filing the issue, looks like you're running an older `beta` channel.
When trying multiple hot-restart/hot-reload on the latest `beta`, I get https://github.com/flutter/flutter/issues/75630

Can you please upgrade to the latest  `beta` and try again if you can reproduce the same issue as mentioned here
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.26.0-17.5.pre at C:\Users\Taha\Code\flutter_beta
    • Framework revision 1fe38dcb5f (4 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 84.0.522.52

• No issues found!
```

</details>

Thank you

**Comment by easeccy** [comment]
Upgraded but still having the issue.

<details>

<summary>flutter doctor --verbose</summary>

```
[√] Flutter (Channel beta, 1.26.0-17.5.pre, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.26.0-17.5.pre at C:\flutter
    • Framework revision 1fe38dcb5f (5 days ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\enes\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\enes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Redmi Note 8 Pro (mobile) • 7lx48pbalvvctg45 • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```
</details>

**Comment by TahaTesser** [comment]
Hi @easeccy 
Thanks for confirming, are you getting this `WebAssembly.instantiate(): Out of memory: wasm memory` or https://github.com/flutter/flutter/issues/75630
can you please provide complete logs with the latest `beta`
Thank you

**Comment by easeccy** [comment]
Error is the same.

```
[ +489 ms] wasm streaming compile failed: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
[   +2 ms] falling back to ArrayBuffer instantiation
[ +654 ms] failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
[   +1 ms] null
[   +3 ms] RuntimeError: abort(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.
               at La (https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:149:56)
               at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:251:379
```

**Comment by pedromassangocode** [comment]
Hi @easeccy 
We need you to provide the complete logs. Please run `flutter run -d chrome --verbose` and once the issue reproduces provide the complete logs.
Thank you

**Comment by easeccy** [comment]
It doesn't happen in a certain condition. I get this error 5-10 times in a day. This is the logs starting from the moment the last hot restart is requested. Logs above that are thousands of regular debug logs.
<details>
<summary>flutter run -d chrome --verbose</summary>

```
[        ] DwdsVmClient: Attempting a hot restart
[        ] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[   +3 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[ +235 ms] DwdsVmClient: $dartHotRestart request complete.
[   +2 ms] DwdsVmClient: Waiting for Isolate Start event.
[   +5 ms] DwdsVmClient: Successful hot restart
[   +1 ms] Restarted application in 924ms.
[ +803 ms] wasm streaming compile failed: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
[   +1 ms] falling back to ArrayBuffer instantiation
[+1262 ms] failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
[        ] null
[        ] RuntimeError: abort(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.
               at La (https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:149:56)
               at https://unpkg.com/canvaskit-wasm@0.22.0/bin/canvaskit.js:251:379
```
</details>

**Comment by pedromassangocode** [comment]
This seems to be an Chrome issue and not related to Flutter: https://bugs.chromium.org/p/chromium/issues/detail?id=935169

It is confirmed to be fixed already. Maybe try to update Chrome? My Chrome version is: `Version 88.0.4324.182 (Official Build) (x86_64)`.

I'm not sure if there is something to be done from the Flutter side.

**Comment by easeccy** [comment]
I haven't encountered this bug for about a week. It was popping up 5-10 times in a day before.
<details>

<summary>flutter doctor --verbose</summary>

```
[√] Flutter (Channel beta, 1.26.0-17.6.pre, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.26.0-17.6.pre at C:\flutter
    • Framework revision a29104a69b (8 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\enes\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\enes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```
</details>
