### ISSUE TITLE
what is the issue?how to solve it ?

### ISSUE THREAD

**Issue by lianchengtong** [flutter/flutter#75972]
flutter doctor
Unhandled exception:
```
FileSystemException: writeFrom failed, path = '' (OS Error: 핸들이 잘못되었습니
다.
, errno = 6)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:309:15)
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:
11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.da
rt:808:19)
#8      _StreamController._add (dart:async/stream_controller.dart:682:7)
#9      _StreamController.add (dart:async/stream_controller.dart:624:5)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:156:17)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:289:5)
#12     _StdSink.write (dart:io/stdio.dart:338:11)
#13     Stdio._stdioWrite.<anonymous closure> (package:flutter_tools/src/base/io
.dart:348:12)
#14     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_gua
rd.dart:111:32)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _runZoned (dart:async/zone.dart:1630:10)
#18     runZonedGuarded (dart:async/zone.dart:1618:12)
#19     runZoned (dart:async/zone.dart:1547:12)
#20     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#21     Stdio._stdioWrite (package:flutter_tools/src/base/io.dart:347:5)
#22     Stdio.stdoutWrite (package:flutter_tools/src/base/io.dart:333:7)
#23     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger
.dart:371:12)
#24     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:266
:5)
#25     Cache._maybeWarnAboutStorageOverride (package:flutter_tools/src/cache.da
rt:310:13)
#26     Cache.storageBaseUrl (package:flutter_tools/src/cache.dart:300:5)
#27     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:7
03:33)
#28     CachedArtifact.update (package:flutter_tools/src/cache.dart:573:11)
#29     Cache.updateAll (package:flutter_tools/src/cache.dart:452:24)
#30     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/fl
utter_command.dart:930:27)
<asynchronous suspension>
#31     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner
/flutter_command.dart:836:33)
<asynchronous suspension>
#32     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner
/flutter_command.dart)
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/conte
xt.dart:150:29)
#34     _rootRun (dart:async/zone.dart:1190:13)
#35     _CustomZone.run (dart:async/zone.dart:1093:19)
#36     _runZoned (dart:async/zone.dart:1630:10)
#37     runZoned (dart:async/zone.dart:1550:10)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#39     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dar
t:825:20)
#40     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#41     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_too
ls/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#42     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_too
ls/src/runner/flutter_command_runner.dart)
#43     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/conte
xt.dart:150:29)
#44     _rootRun (dart:async/zone.dart:1190:13)
#45     _CustomZone.run (dart:async/zone.dart:1093:19)
#46     _runZoned (dart:async/zone.dart:1630:10)
#47     runZoned (dart:async/zone.dart:1550:10)
#48     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#49     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutte
r_command_runner.dart:281:19)
<asynchronous suspension>
#50     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:
112:25)
#51     new Future.sync (dart:async/future.dart:223:31)
#52     CommandRunner.run (package:args/command_runner.dart:112:14)
#53     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_comma
nd_runner.dart:230:18)
#54     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runne
r.dart:63:22)
#55     _rootRun (dart:async/zone.dart:1190:13)
#56     _CustomZone.run (dart:async/zone.dart:1093:19)
#57     _runZoned (dart:async/zone.dart:1630:10)
#58     runZonedGuarded (dart:async/zone.dart:1618:12)
#59     runZoned (dart:async/zone.dart:1547:12)
#60     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#61     run.<anonymous closure> (package:flutter_tools/runner.dart)
#62     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dar
t:67:18)
<asynchronous suspension>
#63     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dar
t)
#64     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/conte
xt.dart:150:29)
#65     _rootRun (dart:async/zone.dart:1190:13)
#66     _CustomZone.run (dart:async/zone.dart:1093:19)
#67     _runZoned (dart:async/zone.dart:1630:10)
#68     runZoned (dart:async/zone.dart:1550:10)
#69     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#70     runInContext (package:flutter_tools/src/context_runner.dart:70:24)
#71     run (package:flutter_tools/runner.dart:46:10)
#72     main (package:flutter_tools/executable.dart:77:9)
#73     main (file:///D:/android-dev/flutter/packages/flutter_tools/bin/flutter_
tools.dart:8:3)
#74     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:299:32)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:168:12)

and my AS tip like below
![图片](https://user-images.githubusercontent.com/10555518/107853973-d0d6a180-6e53-11eb-88ad-1f29d3a01716.png)
![图片](https://user-images.githubusercontent.com/10555518/107853988-f9f73200-6e53-11eb-8c53-b37b35235f9b.png)

i dont know how to do it
```

**Comment by Abhishek01039** [comment]
Please update your flutter @lianchengtong

**Comment by darshankawar** [comment]
@lianchengtong 
Can you try [this](https://github.com/flutter/flutter/issues/42072#issuecomment-654960907) solution and see if it works ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
