### ISSUE TITLE
VideoPlayer doesn't accept self signed SSL certificates on HTTPS URLs

### ISSUE THREAD

**Issue by dantheman213** [flutter/flutter#75995]
## Steps to Reproduce

1. Use VideoPlayer to load a HTTPS media asset that has a self signed certificate.

**Expected results:** 
1. https://localhost:8080/my/test/playlist.m3u8 would work in VideoPlayer

**Actual results:**

1. https://localhost:8080/my/test/playlist.m3u8 causes exception because it is self signed.

```
PlatformException: Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error
```

**Comment by dantheman213** [comment]
Stuff that's been tried:

1. HTTP does work but HTTPS does not in Flutter app.
2. HTTPS self-signed works in VLC player and  browsers

**Comment by darshankawar** [comment]
@dantheman213 
Can you provide `flutter doctor -v` ? Are you on Android or iOS ?

**Comment by dantheman213** [comment]
Hi @darshankawar, thanks for reviewing. The error that I am currently receiving is when I'm testing in Android emulator or on a real device. Here's the error again for visibility:

```
PlatformException: Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error
```

This is an Android error with the underlying Flutter VideoPlayer's native asset. Looks like ExoPlayer is being used for Android. I imagine iOS will have the same problem as it's typical for default HTTPS to give off a warning or have its default config to reject self signed certificates.

Here is a summary from `flutter doctor -v`.

```
> flutter doctor -v

[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 1.22.6 at D:\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\danie\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\danie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks @dantheman213 for the details. I am able to replicate the issue which seems to occur on Android. iOS plays the video properly.

1. Android:

<img width="546" alt="Screenshot 2021-02-16 at 11 55 43 AM" src="https://user-images.githubusercontent.com/67046386/108026386-46a65d00-704e-11eb-83e4-ea84176c3e78.png">

```
Launching lib/main.dart on SM A260G in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:52228/CsgS6FaEwDI=/ws
Syncing files to device SM A260G...
I/ExoPlayerImpl(11022): Init 1cfa707 [ExoPlayerLib/2.12.1] [a2corelte, SM-A260G, samsung, 27]
E/ExoPlayerImplInternal(11022): Playback error
E/ExoPlayerImplInternal(11022):   UnknownHostException (no network)
E/flutter (11022): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (11022): 
```

2. iOS:

<img width="1356" alt="Screenshot 2021-02-16 at 11 53 11 AM" src="https://user-images.githubusercontent.com/67046386/108026424-5625a600-704e-11eb-9e6a-503962f6162c.png">


Recent related but closed issues:

https://github.com/flutter/flutter/issues/68094
https://github.com/flutter/flutter/issues/72696


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-2.0.pre.102, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-2.0.pre.102 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision b2e05062b6 (22 hours ago), 2021-02-15 03:56:03 -0500
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)          • 5200763ebcfa861f                     •
      android-arm    • Android 8.1.0 (API 27)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.150

! Doctor found issues in 1 category.
```

</details>

**Comment by dantheman213** [comment]
Thanks for the quick reply and your review @darshankawar. What would be the next step? Any ballpark ETA for resolution available?

**Comment by hamdikahloun** [comment]
[CustomSSLSocketFactory.java](https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/CustomSSLSocketFactory.java) used only for enable `TLSv1.1` & `TLSv1.2` for `API 19` and below. 

For more information about security SSL: [UnknownCa](https://developer.android.com/training/articles/security-ssl#UnknownCa)  & [SelfSigned](https://developer.android.com/training/articles/security-ssl#SelfSigned)
> Caution: Many web sites describe a poor alternative solution which is to install a TrustManager that does nothing. If you do this you might as well not be encrypting your communication, because anyone can attack your users at a public Wi-Fi hotspot by using DNS tricks to send your users' traffic through a proxy of their own that pretends to be your server. The attacker can then record passwords and other personal data. This works because the attacker can generate a certificate and—without a TrustManager that actually validates that the certificate comes from a trusted source—your app could be talking to anyone. So don't do this, not even temporarily. You can always make your app trust the issuer of the server's certificate, so just do it.

**Comment by dheerajbred** [comment]
Same issue here also. 
Trying to play
https://www04.cloud9xx.com/videos/hls/PPiRAsdEQIc0l0gNOAkZCA/1613693393/137943/0d2d81bdc13b93efd22f3583a4b9c0f0/ep.37.1604050682.360.m3u8

**Comment by dantheman213** [comment]
Any idea when this issue would be resolved?

**Comment by pratikbaid3** [comment]
I am getting the same issue. Any solution yet?

**Comment by patthipati** [comment]
hi @pratikbaid3 I also have the same issue, we resolved it by getting the proper CA Certificate and doing some **Network security configuration** in android folder, please check below link for Network security configuration
https://developer.android.com/training/articles/security-config#CustomTrust

**Comment by dantheman213** [comment]
The VideoPlayer widget should support self signed SSL. There's plenty of use cases for not having a CA signed certificate.

**Comment by pratikbaid3** [comment]
@patthipati Thank you got the help, but wouldn't this mean that for each URL that we access, there would have to be a manual CA Certificate and Network Config?

**Comment by francochau** [comment]
Same error, couldn't play any video from network

**Comment by ronytesler** [comment]
Any other package to play videos?

**Comment by dantheman213** [comment]
Nope, but it'd be great if the maintainers of this repo would fix this issue. hard to consider this a mature video plugin if it can't accept videos from self signed HTTPS URLs.

**Comment by dantheman213** [comment]
Hi Flutter team, any idea when this issue will be resolved? It's an issue on both iOS and Android and there's been no activity on this ticket for months now. Thanks.

**Comment by SalahAdDin** [comment]
I am having the same problem.

**Comment by stcojo** [comment]
Issue persists. Any ETA?

**Comment by uropsm** [comment]
Is there any workaround? any other package?

**Comment by huycozy** [comment]
Hi, I can reproduce this issue with my own self-signed certificates on the latest `stable` and `master` channel. 

<details>
<summary>Tested environments:</summary>

- Android Emulator (Pixel 4 API 30)
- iOS Emulator (iPhone 13, iOS 15.2)

</details>

<details>
<summary>Sample code</summary>

Official sample from: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player#example with your own https media file urls that have self-signed certificate.

For eg: 
- Android: https://10.0.2.2:8080/files/Butterfly-209.mp4
- iOS: https://127.0.0.1:8080/files/Butterfly-209.mp4

</details>


<details>
<summary>Exception log:</summary>

- Android:

```bash
I/TetheringManager(18295): registerTetheringEventCallback:io.flutter.plugins.videoplayerexample
E/ExoPlayerImplInternal(18295): Playback error
E/ExoPlayerImplInternal(18295):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:640)
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:612)
E/ExoPlayerImplInternal(18295):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(18295):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(18295):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(18295):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:365)
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(18295):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(18295):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(18295):       at java.lang.Thread.run(Thread.java:923)
E/ExoPlayerImplInternal(18295):   Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
E/ExoPlayerImplInternal(18295):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:636)
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:533)
E/ExoPlayerImplInternal(18295):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:359)
E/ExoPlayerImplInternal(18295):       ... 6 more
E/ExoPlayerImplInternal(18295):   Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:677)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
E/ExoPlayerImplInternal(18295):       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
E/ExoPlayerImplInternal(18295):       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
E/ExoPlayerImplInternal(18295):       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
E/ExoPlayerImplInternal(18295):       ... 28 more
E/ExoPlayerImplInternal(18295):   Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
E/ExoPlayerImplInternal(18295):       ... 42 more
E/flutter (18295): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter (18295): 
```
- iOS:

```bash
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Failed to load video: Could not connect to the server., null, null)
```

</details>

<details>
<summary>Demo</summary>

- Android:

https://user-images.githubusercontent.com/104349824/166424746-06e7d62d-eee8-46e7-9503-cf13383f1e38.mp4


- iOS:

https://user-images.githubusercontent.com/104349824/166425237-078b4f89-95a5-4d02-8f95-25115eb369d7.mp4


</details>

<details>
<summary>Build a local server with self-signed certificate:</summary>

https://github.com/huycozy/local-server-self-signed-nodejs

</details>

**Comment by kairan77** [comment]
There are three different scenarios to consider:

1. the server's SSL certificate is signed by a proper CA
2. the video server is owned by yourself and the server's SSL certificate is signed by yourself
3. the video server is owned by a third party and the server's SSL certificate is self signed by that third party which you have no control

for case 1, you don't need to do anything, it will just work.

for case 3, I highly doubt it would affect anyone, since I don't think anyone would develop an APP that stream videos from a thirdparty server with self-signed certificate. If you think about it, that third party if having a proper business model which allows third party streaming videos off its api, it would probably already have a proper CA signed certificate, if that third party can't even get a proper CA signed certificate, that server owner would probably be quite pissed if someone is streaming off heavy traffic long term, such a scenario won't last very long.

However if this is indeed the case, you can take a look at mrnicegaius's pull request which applies an override resolving third party self signed certificate. Actually his pull request can be simplified to just 10 lines of code if you just want to entirely bypass the protection against bad certificate.

for case 2, if the server and the certificate are both in your control, you can install your server's certificate inside your flutter app, so that it behave just like case 1 transparently, and you don't need to do any custom coding with or without videoplayer plugin.

To install your own self signed certificate, you can look at https://developer.android.com/training/articles/security-config, on the section regarding installing self signed certificate to your app.

In all three cases I don't think any changes should be made to the videoplayer plugin itself. My certifcate was self signed and I was able to make it work by following the steps from developer guidelines on android site.

**Comment by Gradergage** [comment]
Any progress in this issue?

**Comment by SalahAdDin** [comment]
Up!

**Comment by lorki0052** [comment]
Up!

**Comment by fuz12** [comment]
I still have this problem on ios. I tried using NSAppTransportSecurity in ios (https://developer.apple.com/news/?id=g9ejcf8y) similar to network-security-config in android (https://developer.android.com/privacy-and-security/security-config#TrustingAdditionalCas), but it didn't work.
Is it possible to find a similar solution for ios which @patthipati suggested for android? Or can we set certificates in the ios native for all app and packages? In flutter, this can be achieved as follows:
```
final certificates = await rootBundle.load('public/assets/openssl/certificate.crt');
HttpOverrides.global = _AppHttpOverrides(certificates);

class _AppHttpOverrides extends HttpOverrides {
  _AppHttpOverrides(this.certificates);
  
  ByteData certificates;

  @OverRide
  HttpClient createHttpClient(SecurityContext? context) {
    final securityContext = SecurityContext();
    securityContext.setTrustedCertificatesBytes(certificates.buffer.asUint8List());
    
    return super.createHttpClient(securityContext);
  }
}
```
