### ISSUE TITLE
Flutter doctor fails with NoSuchMethodError 

### ISSUE THREAD

**Issue by sureshg** [flutter/flutter#7610]
## Steps to Reproduce

Cloned the latest flutter repo and ran `flutter doctor`. It fails with `Class 'LocalProcessManager' has no instance method 'runSync' with matching arguments` error.

## Flutter Doctor

```
🍻 Flutter doctor...
Unhandled exception:
NoSuchMethodError: Class 'LocalProcessManager' has no instance method 'runSync' with matching arguments.
Receiver: Instance of 'LocalProcessManager'
Tried calling: runSync("git", Instance(length:2) of '_GrowableList', workingDirectory: null)
Found: runSync(command, workingDirectory, environment, includeParentEnvironment, runInShell, stdoutEncoding, stderrEncoding)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _runSync (package:flutter_tools/src/version.dart:105)
#3      FlutterVersion.getVersionString (package:flutter_tools/src/version.dart:88)
#4      Usage.Usage (package:flutter_tools/src/usage.dart:24)
#5      main.<main_async_body>.<anonymous closure>.<anonymous closure> (package:flutter_tools/executable.dart:119)
#6      AppContext.putIfAbsent (package:flutter_tools/src/base/context.dart:46)
#7      main.<main_async_body>.<anonymous closure> (package:flutter_tools/executable.dart:119)
#8      AppContext._run.<_run_async_body> (package:flutter_tools/src/base/context.dart:76)
#9      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#10     _rootRun (dart:async/zone.dart:1150)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:953)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by abarth** [comment]
Should be fixed now.  You can get the new version by running `git pull` in your clone of flutter.git.

Thanks for the report.
