### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/randiandrio/Library/Android/sdk/build-tools/30.0.3/aapt.

### ISSUE THREAD

**Issue by randiandrio** [flutter/flutter#76139]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=R9CN7021HBJ --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/randiandrio/Library/Android/sdk/build-tools/30.0.3/aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:125:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:92:30)
#2      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:481:37)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:380:14)
#4      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:481:12)
#5      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:425:51)
#6      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:120:33)
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#8      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:598:34)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:551:54)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:339:31)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#19     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart)
#20     _rootRunUnary (dart:async/zone.dart:1198:47)
#21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-ID)
    • Flutter version 1.22.6 at /Users/randiandrio/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/randiandrio/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    ✗ Android SDK file not found: /Users/randiandrio/Library/Android/sdk/build-tools/30.0.3/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.8.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • SM A107F (mobile) • R9CN7021HBJ • android-arm • Android 10 (API 29)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.4.2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 4732a214a7362a3781989977429f14202143b4f5
### Plugins
android_intent-0.3.7+7
audioplayers-0.16.2
firebase_auth-0.14.0+9
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
firebase_storage-3.1.6
flutter_plugin_android_lifecycle-1.0.11
geolocator-6.2.0
geolocator_web-1.0.0
google_maps_flutter-0.5.33
image_picker-0.6.7+22
import_js_library-1.0.2
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
video_player-1.0.1
video_player_web-0.1.4+1
wakelock-0.2.1+1
wakelock_web-0.1.0+3
webview_flutter-1.0.7

**Comment by pedromassangocode** [comment]
Hi @randiandrio 
I see there's an open issue (https://github.com/flutter/flutter/issues/54418) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
