### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by Osama7Star** [flutter/flutter#76207]
## Command
```
flutter create bug
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:226:28)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#6      Template.render (package:flutter_tools/src/template.dart:190:24)
#7      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:799:21)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#16     Template.fromName (package:flutter_tools/src/template.dart)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-FI)
    • Flutter version 1.22.6 at C:\Flutter\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\dell\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM J320H (mobile) • 92012381c872544a • android-arm • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
agora_rtc_engine-1.0.5
apple_sign_in-0.1.0
cloud_firestore-0.13.4+2
cloud_firestore_web-0.1.1+1
firebase_admob-0.9.3+4
firebase_auth-0.15.5+2
firebase_auth_web-0.1.2
firebase_core-0.4.4+2
firebase_core_web-0.1.1+2
firebase_messaging-6.0.13
firebase_storage-3.1.3
flutter_plugin_android_lifecycle-1.0.6
flutter_ringtone_player-2.0.0
flutter_webview_plugin-0.3.11
geocoder-0.2.1
image_cropper-1.2.1
image_picker-0.6.3+4
in_app_purchase-0.3.4
location-3.1.0
location_web-1.0.0
path_provider-1.6.5
path_provider_macos-0.0.4
permission_handler-3.3.0
share-0.6.3+6
sqflite-1.3.0
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2

**Comment by darshankawar** [comment]
@Osama7Star 
This issue is already fixed and merged into master and is only available in master. See [this](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004) comment. Please switch to latest master and try again to see if it works. 

I am closing this is already fixed. If you disagree or think issue persists on latest master, write in comments and I'll reopen it.
