### ISSUE TITLE
linux_backdrop_filter_perf__e2e failing after engine roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76216]
From: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20backdrop_filter_perf__e2e_summary/574/overview

```
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [   +2 ms] I/flutter (10517): Bad state: No element
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [  +15 ms] I/flutter (10517): #0      ListMixin.reduce (dart:collection/list.dart:222)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [   +2 ms] I/flutter (10517): #1      new FrameTimingSummarizer (package:flutter_test/src/frame_timing_summarizer.dart:46)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] I/flutter (10517): #2      IntegrationTestWidgetsFlutterBinding.watchPerformance (package:integration_test/integration_test.dart:318)
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] I/flutter (10517): <asynchronous suspension>
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] I/flutter (10517): <asynchronous suspension>
[backdrop_filter_perf__e2e_summary] [STDOUT] stdout: [        ] I/flutter (10517): (elided one frame from package:stack_trace)
```

Interesting PRs in that roll are https://github.com/flutter/engine/pull/24387 and https://github.com/flutter/engine/pull/24264 /cc @iskakaushik @knopp

**Comment by zanderso** [comment]
This is still waiting on a successful engine -> framework roll to confirm that it is fixed.

**Comment by chinmaygarde** [comment]
The roll went through. Closing.
