### ISSUE TITLE
video_player OOM crash

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#76237]
* video_player version: 2.0.0-nullsafety.8
* device: Galaxy Note10 Lite
* available ram: 1.74 GB

for more context it looks like samsung devices in general behave really abnormally for my application, they crash, throw exceptions, glitch, etc.

i don't have an actual samsung device on hands and this crash is taken from crashlytics

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 2912 byte allocation with 166400 free bytes and 162KB until OOM, target footprint 201326592, growth limit 201326592; failed due to fragmentation (largest possible contiguous allocation 2097152 bytes)
       at java.util.Arrays.copyOf(Arrays.java:3257)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
       at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:541)
       at java.lang.StringBuilder.append(StringBuilder.java:176)
       at java.lang.String.replace(String.java:2381)
       at com.google.android.exoplayer2.util.Log.a(Log.java:18)
       at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:117)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel nt4f04und, 1.24.0-8.0.pre.374, on Microsoft Windows [Version 10.0.19041.804], locale ru-RU)
    • Flutter version 1.24.0-8.0.pre.374 at c:\dev\src\flutter
    • Framework revision 183f0e797a (3 months ago), 2020-11-26 19:12:28 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 88.0.705.68

! Doctor found issues in 1 category.
```
</details>

**Comment by nt4f04uNd** [comment]
can this be related? https://github.com/flutter/flutter/issues/72643

in my app i have only one video playing at once, thus i'm not sure

**Comment by TahaTesser** [comment]
Hi @nt4f04uNd 
Looks like you'e using 3 months old Flutter, which Gradle version are you using? Since you're using null-safety, you might wanna upgrade to null-safety flutter try again?
Also, the issue could depend on the length and format of the video, can you please provide a sample video? 

If the problem persists, Can you please provide your `flutter doctor -v`.
Thank you

**Comment by nt4f04uNd** [comment]
gradle `com.android.tools.build:gradle:3.6.3` (i could't build with `com.android.tools.build:gradle:4.0.1` and above)

i updated to https://github.com/flutter/flutter/commit/dce8f712288e7ebea55b0af37bb2affdcc21f349, gonna see if i will ever get this crash again

there's no chance video is too heavy, there are quite easy - 1920x1080p max res, and max size about 10mb.
one of the videos you can see in https://github.com/flutter/flutter/issues/72508

**Comment by cyanglaz** [comment]
This is likely either a device issue or exoplayer issue.

**Comment by nt4f04uNd** [comment]
i got similar stack trace once more since then

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 3688 free bytes and 3KB until OOM
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:203)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

![image](https://user-images.githubusercontent.com/39104740/111857738-aa20f480-8944-11eb-9835-e6da782f3f5e.png)

> This is likely either a device issue or exoplayer issue.

yeah, perhaps it is

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel texture_buildable, 1.27.0-2.0.pre.100, on Microsoft Windows [Version 10.0.19041.804], locale ru-RU)
    • Flutter version 1.27.0-2.0.pre.100 at c:\dev\src\flutter
    • Framework revision 76080cd46c (2 days ago), 2021-02-21 18:22:32 +0300
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (4 available)
    • Redmi Note 5 (mobile) • 40c9f14 • android-arm64  • Android 9 (API 28)
    • Windows (desktop)     • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)          • chrome  • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)            • edge    • web-javascript • Microsoft Edge 88.0.705.68

! Doctor found issues in 1 category.
```
</details>

**Comment by nt4f04uNd** [comment]
and another one

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 3GB until OOM, max allowed footprint 134218448, growth limit 134217728
       at android.util.Log.getStackTraceString(Log.java:468)
       at com.google.android.exoplayer2.util.Log.a(Log.java:22)
       at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java)
       at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java)
       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:117)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

![image](https://user-images.githubusercontent.com/39104740/111857804-14399980-8945-11eb-8884-8d4da4f120cd.png)

**Comment by nt4f04uNd** [comment]
> This is likely either a device issue or exoplayer issue.

yeah, perhaps it is

**Comment by rikai-trongpq** [comment]
@TahaTesser   Do you have a plan to solve this problem? I have the same problem.

**Comment by zhihongzhang123** [comment]
me too

**Comment by darshankawar** [comment]
@nt4f04uNd 
Revisiting this issue, I tried the video_player plugin example on S10+ device with latest stable version but didn't face the reported crash or any error while performing various actions.
Can you check at your end if the reported crash persists ?
