### ISSUE TITLE
Error With Library Flutter_Geofire

### ISSUE THREAD

**Issue by Jesus180Reyes** [flutter/flutter#76240]
I was creating a taxi app with flutter and dart and implemented the "flutter_geofire" library so that the client can see the drivers in real time, their current position, but when I run my application the connected drivers do not appear and I also get an error in console that I will show you help please

```
======== Exception caught by services library ====================================================== The following MissingPluginException was thrown while activating platform stream on channel geofireStream: MissingPluginException(No implementation found for method listen on channel geofireStream)

When the exception was thrown, this was the stack: #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7) #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12) #2 EventChannel.receiveBroadcastStream. (package:flutter/src/services/platform_channel.dart:540:29) #3 EventChannel.receiveBroadcastStream. (package:flutter/src/services/platform_channel.dart:526:64)

```
flutter

**Comment by darshankawar** [comment]
@Jesus180Reyes 
`flutter_geofire` is a 3rd party plugin. Please open this issue in dedicated repo : https://github.com/mrdishant/flutter_geofire/issues

Closing from here.
