### ISSUE TITLE
[local_auth] `Fatal Exception: java.lang.IllegalStateException: Reply already submitted`

### ISSUE THREAD

**Issue by GnafGnaf** [flutter/flutter#76299]
## Steps to Reproduce

Sorry, we are having problems reproducing this issue. We only have our testers that tell us, that it crashes sometimes and we have the Crashlytics logs to back it up. As I understood it, the app crashes, after the user used their biometric authentification method. Here is the stack trace: 

```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.a(MethodChannel.java:14)
       at io.flutter.plugins.localauth.LocalAuthPlugin$1.a(LocalAuthPlugin.java:20)
       at io.flutter.plugins.localauth.AuthenticationHelper.a(AuthenticationHelper.java:30)
       at androidx.biometric.BiometricPrompt$1.lambda$onClick$0(BiometricPrompt.java:29)
       at androidx.biometric.-$$Lambda$BiometricPrompt$1$P30oSr_4In3G9QZQRdzDDZj8niU.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

And another one (A tiny bit different):

```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.a(MethodChannel.java:14)
       at io.flutter.plugins.localauth.LocalAuthPlugin$1.onSuccess(LocalAuthPlugin.java:20)
       at io.flutter.plugins.localauth.AuthenticationHelper.a(AuthenticationHelper.java:2)
       at androidx.biometric.BiometricFragment$1.a(BiometricFragment.java:17)
       at androidx.biometric.-$$Lambda$BiometricFragment$1$5yETAGvseQK65JiDb9XeeUnfaZA.run(-.java:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /[...]/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /[...]/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /[...]/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /[...]/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

 
[✓] Connected device (2 available)            
    • iPhone (mobile)            • [...] • ios • iOS 14.4
    • iPhone 12 Pro Max (mobile) • 55CBAC7D-BEF8-44D7-9F18-0CBA985B8D3C     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
```
 (Plugins are actually installed. No idea, why it says they aren't.)

**Comment by GnafGnaf** [comment]
Same issue as #59318

**Comment by darshankawar** [comment]
@GnafGnaf 
Tried the official `local_auth` plugin example on latest stable (1.22.6) using iOS 14.3 device, played around the biometrics and authentication, but as expected, didn't see the said crash.
Is there a way to find a pattern for this crash ? Because, with only the crash logs, it'll be tough to investigate and identify the root-cause of the issue.
Does it occur locally in non-prod environment ?

**Comment by GnafGnaf** [comment]
I know, the bug report sucks... Sorry for that, but we can not reproduce it either. I had the issue myself, but it only happens once or twice a day without me being able to understand what I did different this time to trigger this behavior. 

The crashes happen on debug builds, as well as on prod builds.

**Comment by julio-coelho** [comment]
Same here. Our Crashlytics points that 91% of crashes happens in Android 8 devices.

`[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-BR)
    • Flutter version 1.22.6 at /Users/juliocoelho/Tools/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/juliocoelho/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/juliocoelho/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.`

![image](https://user-images.githubusercontent.com/13860548/108410327-0be72500-7206-11eb-8c07-67defb70e501.png)

**Comment by darshankawar** [comment]
Since there's no concrete reproducible use case, I am unable to verify this issue and pin-point root-cause for it. Also tried on Android 8 device on which didn't see any errors apart from `I/flutter (  413): PlatformException(NotAvailable, Biometrics is not available on this device., null, null)` which is expected.
Keeping this issue open for further investigation. 

@GnafGnaf Please write in comments if you find a pattern to replicate.

**Comment by cyanglaz** [comment]
If the original description in https://github.com/flutter/flutter/issues/29092 is true, it might be related.
We should also audit all the calls in local_auth is protected by `authInProgress`.

**Comment by GnafGnaf** [comment]
It is very well possible, that it is related. I realized that we call authenticateByBiometrics multiple times, if the user has multiple routes on the route stack. I added a check for ModalRoute.of(context).isCurrent before the call and could reduce the amount of crashes we see in crashlytics. We still get those crashes, but less often.

**Comment by haihai1993** [comment]
Change 
 <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
 
 To
 
 <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">

it's work perfectly.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/3272 describes a case where this happens, which means we now have at least one known path that leads to the crash.

**Comment by ollydixon** [comment]
If you want to reproduce this use the ```camera: ^0.9.2+2``` example. I'm also seeing this fail on multiple packages on multiple real devices OnePlus for example. It's a very critical bug for us since customers cannot upload photos or take photos from the gallery.

**Comment by melWiss** [comment]
where are we in this bug? it crashes the whole app and it would be nice if there's a way not to :(
