### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by pritish1990** [flutter/flutter#76317]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: Permission denied, errno = 13
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:615:26)
#3      ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:928:44)
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:322:13)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:602:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#15     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#16     _rootRunUnary (dart:async/zone.dart:1198:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.6 at /home/pritish/snap/flutter/common/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /usr/lib/android-sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/lib/jvm/java-15-oracle/bin/java
    • Java version Java(TM) SE Runtime Environment (build 15.0.1+9-18)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[!] Android Studio
    • Android Studio at /path/to/android/studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = /path/to/android/studio
    ✗ Android Studio not found at /path/to/android/studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] Connected device (1 available)
    • SM A260G (mobile) • 52006d2442475623 • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6
### Plugins
cloud_firestore-0.16.0
cloud_firestore_web-0.3.0+1
firebase_auth-0.20.0+1
firebase_auth_web-0.3.2+6
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_storage-7.0.0
firebase_storage_web-0.1.1+3

**Comment by darshankawar** [comment]
@pritish1990 
Check [this](https://github.com/flutter/flutter/issues/68810#issuecomment-714699148) comment and confirm if you have proper permissions and access and then try again to see if it works.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
