### ISSUE TITLE
Assertion failure in package:vm_snapshot_analysis/v8_profile.dart

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76313]
On the engine roll here: https://github.com/flutter/flutter/pull/76307

Under `packages/flutter_tools` running:

```
$ ../../bin/cache/dart-sdk/bin/pub run test -rcompact -j1 --no-color test/integration.shard/analyze_size_test.dart
```

```
'package:vm_snapshot_analysis/v8_profile.dart': Failed assertion: line 460 pos 12: 'parent != null': Trying to create node of type NodeType.functionNode with <optimized out> and no parent.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _ProgramInfoBuilder.makeInfoNode (package:vm_snapshot_analysis/v8_profile.dart:460:12)
#3      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:418:18)
#4      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:350:14)
#5      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#6      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:314:16)
#7      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:258:8)
#8      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:157:16)
#9      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#10     SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:119:59)
#11     AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:611:59)
#12     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:593:13)
<asynchronous suspension>
#13     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:276:7)
<asynchronous suspension>
#14     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1185:12)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#22     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
<asynchronous suspension>
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:60:12)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#27     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:77:10)
<asynchronous suspension>
#29     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

Full logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8854945268342366032/+/steps/run_test.dart_for_tool_integration_tests_shard_and_subshard_2_3/0/stdout?format=raw

@a-siva

**Comment by zanderso** [comment]
Reading the Dart commit logs in the roll, I'm not able to identify any related commits.

**Comment by zanderso** [comment]
From chat, this was bisected to https://github.com/dart-lang/sdk/commit/b6dc4dad4dae73fe5f8500653de61a76fa5d6ce6 @alexmarkov

**Comment by a-siva** [comment]
who should own the forward fix for this ?

**Comment by a-siva** [comment]
Dropping priority from P0 to P1 as the revert has landed and we need to work on a forward fix for the issue.

**Comment by mraleph** [comment]
I have fixed the underlying issue in `vm_snapshot_analysis`, published new version and rolled it into flutter. I have verified that the test now passes even with reland of dart-lang/sdk@b6dc4da

**Comment by zanderso** [comment]
Thanks!
