### ISSUE TITLE
"getVM: (112) Service has disappeared" on ios_app_with_extensions_test

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#76357]
```
2021-02-18T17:43:14.687604: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter run -d 1A03BE03-0AF1-41BD-84C1-AE661358E509 in /var/folders/ws/_c0c34n960l1xc2scwr9m56r0000gn/T/ios_app_with_extensions_testQksKMr/app_with_extensions
2021-02-18T17:43:16.670206: stdout: Running "flutter pub get" in app_with_extensions...                803ms
2021-02-18T17:43:16.969888: stdout: Launching lib/main.dart on TestFlutteriPhoneWithWatch in debug mode...
2021-02-18T17:43:23.900646: stdout: Running pod install...                                           1,403ms
2021-02-18T17:43:23.930932: stdout: Watch companion app found. Adjusting build settings.
2021-02-18T17:44:01.307507: stdout: Running Xcode build...                                          
2021-02-18T17:44:01.310081: stdout: Xcode build done.                                           37.4s
2021-02-18T17:44:06.189278: stdout: Syncing files to device TestFlutteriPhoneWithWatch...               73ms
2021-02-18T17:44:06.200204: stdout: 
2021-02-18T17:44:06.200608: stdout: Flutter run key commands.
2021-02-18T17:44:06.202957: stdout: r Hot reload. 🔥🔥🔥
2021-02-18T17:44:06.203571: stdout: R Hot restart.
2021-02-18T17:44:06.203824: stdout: h Repeat this help message.
2021-02-18T17:44:06.204130: stdout: d Detach (terminate "flutter run" but leave application running).
2021-02-18T17:44:06.204387: stdout: c Clear the screen
2021-02-18T17:44:06.204780: stdout: q Quit (terminate the application on the device).
stdout: 
2021-02-18T17:44:06.204909: stdout: Running with unsound null safety
2021-02-18T17:44:06.205026: stdout: For more information see https://dart.dev/null-safety/unsound-null-safety
2021-02-18T17:44:06.205113: stdout: 
2021-02-18T17:44:06.205770: stdout: An Observatory debugger and profiler on TestFlutteriPhoneWithWatch is available at: http://127.0.0.1:63498/tYlmyx1mSDE=/
2021-02-18T17:44:06.212093: stdout: 
2021-02-18T17:44:06.893041: stdout: The Flutter DevTools debugger and profiler on TestFlutteriPhoneWithWatch is available at: http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A63498%2FtYlmyx1mSDE%3D%2F
2021-02-18T17:44:06.909282: stderr: 
2021-02-18T17:44:06.913210: stderr: Oops; flutter has exited unexpectedly: "getVM: (112) Service has disappeared".
2021-02-18T17:44:07.177933: stdout: Application finished.
2021-02-18T17:44:07.195663: stderr: A crash report has been written to /private/var/folders/ws/_c0c34n960l1xc2scwr9m56r0000gn/T/ios_app_with_extensions_testQksKMr/app_with_extensions/flutter_01.log.
stdout: This crash may already be reported. Check GitHub for similar crashes.
2021-02-18T17:44:07.195977: stdout: https://github.com/flutter/flutter/issues?q=is%3Aissue+getVM%3A+%28112%29+Service+has+disappeared
stdout: 
2021-02-18T17:44:07.196045: stdout: To report your crash to the Flutter team, first read the guide to filing a bug.
2021-02-18T17:44:07.196186: stdout: https://flutter.dev/docs/resources/bug-reports
stdout: 
2021-02-18T17:44:07.196301: stdout: Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
2021-02-18T17:44:07.640040: stdout: https://git.io/Jty3I
stdout: 
2021-02-18T17:44:07.664701: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 1
2021-02-18T17:44:07.720153: 
Executing: xcrun simctl shutdown 1DA9072A-CD8B-4053-B76C-7D99FCB0895E in /Users/flutter/.cocoon/flutter
2021-02-18T17:44:13.847764: "xcrun" exit code: 0
```

happened on https://github.com/flutter/flutter/commit/69775c5d0a64e92b5dc24fd4f5ca7d8fadd034a7.
Looks similar to https://github.com/flutter/flutter/issues/75097

**Comment by LongCatIsLooong** [comment]
@jmagman according to the git history it looks like I should assign this to you?

**Comment by jmagman** [comment]
It's an `RPCError` but the stack is missing.

@jonahwilliams says "its probably a case where the user is performing some RPC, and the device goes away due to cord/crash" but the tool isn't handling it.  If the app is crashing at startup I would expect to see some logging from the attached debugger.

**Comment by Swepilot** [comment]
Having this issue as well. Contents from my crash report (doesn't say that much):

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

RPCError: getVM: (112) Service has disappeared

```
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/xxxxxx/development/flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxxxxx/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /applications/xcode.app/contents/developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • xxxxxx iPad (mobile) • 0000XXXX-00010CDE0E22XXXX • ios            • iOS 14.4
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

**Comment by kjawadDeveloper** [comment]
@jmagman i am also getting this error when running unit test.  This is the crash log.


`C:\Users\DELL\Documents\cashero_3.0\test\widget_testing\features\signup\freelancer\business_profile_screen\show_freelancer_profile_image_test.dart
getObject: (112) Service has disappeared
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2109:21)
#2      VmService.getObject (package:vm_service/src/vm_service.dart:1891:7)
#3      _getAllCoverage (package:flutter_tools/src/test/coverage_collector.dart:264:10)
<asynchronous suspension>
#4      collect (package:flutter_tools/src/test/coverage_collector.dart:216:39)
<asynchronous suspension>
#5      Future.any.onValue (dart:async/future.dart)
<asynchronous suspension>`

**Comment by Nasrallahelfarra** [comment]
same erorr

**Comment by Nasrallahelfarra** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter drive --target=test_driver/app_start.dart --flavor Staging

## exception

RPCError: getVersion: (112) Service has disappeared

```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1637:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2122:21)
#2      VmService.getVersion (package:vm_service/src/vm_service.dart:1954:35)
#3      _connect (package:flutter_tools/src/vmservice.dart:370:25)
<asynchronous suspension>
#4      FlutterDriverService.reuseApplication (package:flutter_tools/src/drive/drive_service.dart:240:18)
<asynchronous suspension>
#5      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:241:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\alags\AppData\Local\Android\SDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\alags\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] Connected device (3 available)
    • SM A515F (mobile) • RR8NC021DMB • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 98.0.4758.81
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 98.0.1108.43

• No issues found!
```

**Comment by Ricardev** [comment]
I am also getting the same error with unit tests.

### **flutter test --coverage**
```
getSourceReport: (112) Service has disappeared
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.getSourceReport (package:vm_service/src/vm_service.dart:2040:7)
#3      _getAllCoverage (package:flutter_tools/src/test/coverage_collector.dart:254:52)
<asynchronous suspension>
#4      collect (package:flutter_tools/src/test/coverage_collector.dart:217:39)
<asynchronous suspension>
#5      Future.any.onValue (dart:async/future.dart:611:5)
<asynchronous suspension>
```

All my tests are passing when i don't put the --coverga flag,

**Comment by elenacrst** [comment]
Getting this error when running an integration test on any device, not necessarily iOS. Is there any fix?

**Comment by AdamBridges** [comment]
I have also been experiencing this error on and off with iOS devices. My only guess in my case is that the VM service is timing out before my tests are done setting up. I'm still working on fixing the issue and will try a less demanding setup so that the service can bind as soon as possible, and then continue with the demanding setup once it's bound. 

Here's hoping.

**Comment by Peter-K-Joseph** [comment]
Happened to me too. I fixed it by removing relative imports from the test and using package:name/file kind one
