### ISSUE TITLE
Linux animated_placeholder_perf failing consistently

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#76359]
Logs:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20animated_placeholder_perf

```
Unhandled exception:
Executable Dart file not found: bin/tasks/animated_placeholder_perf.dart
#0      runTask (package:flutter_devicelab/framework/runner.dart:34:5)
#1      _runTasks (file:///opt/s/w/ir/k/recipe_cleanup/tmp11no5H/flutter%20sdk/dev/devicelab/bin/run.dart:115:37)
#2      main (file:///opt/s/w/ir/k/recipe_cleanup/tmp11no5H/flutter%20sdk/dev/devicelab/bin/run.dart:108:11)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by godofredoc** [comment]
Seems like the test was deleted but the infra configuration was not. @jonahwilliams @jmagman should we delete the infra config too?

**Comment by godofredoc** [comment]
Linux multi_widget_construction_perf__timeline_summary seems that was also removed. Logs:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20multi_widget_construction_perf__timeline_summary

```
Unhandled exception:
Executable Dart file not found: bin/tasks/multi_widget_construction_perf__timeline_summary.dart
#0      runTask (package:flutter_devicelab/framework/runner.dart:34:5)
#1      _runTasks (file:///opt/s/w/ir/k/recipe_cleanup/tmprhOGMX/flutter%20sdk/dev/devicelab/bin/run.dart:115:37)
#2      main (file:///opt/s/w/ir/k/recipe_cleanup/tmprhOGMX/flutter%20sdk/dev/devicelab/bin/run.dart:108:11)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by jmagman** [comment]
`animated_placeholder_perf` was removed in #74062 and `multi_widget_construction_perf__timeline_summary` was removed in #73986.  The infra config should be removed.
