### ISSUE TITLE
[tool_crash] _Exception

### ISSUE THREAD

**Issue by gunasekharravilla** [flutter/flutter#76364]
## Command
```
flutter gen-l10n
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_Exception
```
#0      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:43:5)
#1      GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:190:7)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1174:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1026:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#5      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:280:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#9      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:66:9)
<asynchronous suspension>
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:64:12)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
```
```
[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-IN)
    • Flutter version 1.27.0-1.0.pre at C:\src\flutter
    • Framework revision 68c96f100e (10 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Hp\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • motorola one power (mobile) • ZF6223SDMV • android-arm64  • Android 10 (API 29)
    • Chrome (web)                • chrome     • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)                  • edge       • web-javascript • Microsoft Edge 88.0.705.74

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: d9637ed78468ee0e65af509fafb71f792de6d09a
### Plugins
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_messaging-7.0.3
firebase_remote_config-0.4.3
firebase_storage-5.2.0
firebase_storage_web-0.1.1+1
flutter_facebook_login-3.0.0
flutter_local_notifications-3.0.3
flutter_plugin_android_lifecycle-1.0.11
google_sign_in-4.5.9
google_sign_in_web-0.9.2
image_picker-0.6.7+22
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+3
stripe_payment-1.0.10
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by jmagman** [comment]
@gunasekharravilla Unfortunately the exception message is missing (to protect uploading any personally identifiable info to GitHub).  Did it generate a log at the same time it crashed?  If so, can you upload it?

**Comment by christopherfujino** [comment]
@shihaohong can you take a look at this one?
