### ISSUE TITLE
Provide clear failure message when attempting to use Isolate.spawnURI.

### ISSUE THREAD

**Issue by iulian0512** [flutter/flutter#76371]
i am trying run a remote dart file hosted on my local iis instance, i get a crash  UI actions are only available on root isolate. 

<details>
<summary>code sample</summary>

```dart
import 'dart:isolate';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());

  var response = ReceivePort();
  var remote = Isolate.spawnUri(
      Uri.parse('http://192.168.0.100/echo.dart'), ['foo'], response.sendPort);
  remote.then((_) => response.first).then((msg) {
    print("received: $msg");
  });
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Text("aaaa"),
      ),
    );
  }
}
```

</details>

Remote dart file:
http://192.168.0.100/echo.dart (is accessible from emulator checked)

```
import 'dart:isolate';

void main(List<String> args, SendPort replyTo) {
  replyTo.send(args[0] + 'iis');
}

```
error log

<details>
<summary>logs</summary>

```bash
E/flutter (11766): [ERROR:flutter/runtime/dart_isolate.cc(882)] Unhandled exception:
E/flutter (11766): UI actions are only available on root isolate.
E/flutter (11766): #0      Window._nativeSetNeedsReportTimings (dart:ui/window.dart:1019:101)
E/flutter (11766): #1      Window.onReportTimings= (dart:ui/window.dart:1012:29)
E/flutter (11766): #2      SchedulerBinding.addTimingsCallback
package:flutter/…/scheduler/binding.dart:269
E/flutter (11766): #3      SchedulerBinding.initInstances
package:flutter/…/scheduler/binding.dart:206
E/flutter (11766): #4      ServicesBinding.initInstances
package:flutter/…/services/binding.dart:27
E/flutter (11766): #5      PaintingBinding.initInstances
package:flutter/…/painting/binding.dart:22
E/flutter (11766): #6      SemanticsBinding.initInstances
package:flutter/…/semantics/binding.dart:23
E/flutter (11766): #7      RendererBinding.initInstances
package:flutter/…/rendering/binding.dart:30
```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
PS C:\temp\flutter\dartconsole\dartconsole> flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-GB)
    • Flutter version 1.22.6 at C:\fluttersdk
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
    • Android SDK at C:\AndroidSDK\androidSDK
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\csman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @iulian0512 
Thanks for filing the issue,   I reproduce by running `echo.dart` from localhost using python server `python3 -m http.server` 




<details>
<summary>code sample</summary>

```dart
import 'dart:isolate';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());

  var response = ReceivePort();
  var remote = Isolate.spawnUri(
      Uri.parse('http://localhost:8000/echo.dart'), ['foo'], response.sendPort);
  remote.then((_) => response.first).then((msg) {
    print("received: $msg");
  });
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(child: Text("aaaa")),
      ),
    );
  }
}

```

</details>



<details>
<summary>logs</summary>

```bash
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on Android SDK built for x86.
[   +1 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb -s emulator-5554 shell am force-stop com.nevercode.triage
[ +191 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb -s emulator-5554 shell pm list packages
com.nevercode.triage
[ +455 ms] package:com.nevercode.triage
[  +10 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb -s emulator-5554 shell cat
/data/local/tmp/sky.com.nevercode.triage.sha1
[ +115 ms] 57e046fd403ba7f0c5f99275dcf21131bf787f4e
[   +1 ms] Installing APK.
[   +2 ms] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /Volumes/Extreme/SDK/platform-tools/adb -s emulator-5554 install -t -r
/Users/tahatesser/AndroidStudioProjects/stable_flutter/build/app/outputs/flutter-apk/app.apk
[+1863 ms] Performing Streamed Install
                    Success
[   +2 ms] Installing build/app/outputs/flutter-apk/app.apk... (completed in 1,864ms)
[   +2 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb -s emulator-5554 shell echo -n
eefed9b72b785d68535b45037d11546464e13ba4 > /data/local/tmp/sky.com.nevercode.triage.sha1
[ +102 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[ +197 ms] --------- beginning of main
                    02-19 16:46:51.922 I/Finsky  (13438): [1782] qbr.run(16): Wrote row to frosting DB: 336
[  +20 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb -s emulator-5554 shell am start -a
android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true com.nevercode.triage/com.nevercode.triage.MainActivity
[ +150 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.nevercode.triage/.MainActivity (has
extras) }
[   +1 ms] Waiting for observatory port to be available...
[+2348 ms] Observatory URL on device: http://127.0.0.1:34963/gJYtLUs4dNE=/
[   +1 ms] executing: /Volumes/Extreme/SDK/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:34963
[  +29 ms] 62992
[   +1 ms] Forwarded host port 62992 to device port 34963 for Observatory
[  +11 ms] Caching compiled dill
[ +199 ms] Connecting to service protocol: http://127.0.0.1:62992/gJYtLUs4dNE=/
[ +779 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:62992/gJYtLUs4dNE=/.
[ +301 ms] DDS is listening at http://127.0.0.1:62999/Xo5ICiO1Koo=/.
[ +133 ms] Successfully connected to service protocol: http://127.0.0.1:62992/gJYtLUs4dNE=/
[ +594 ms] DevFS: Creating new filesystem on the device (null)
[  +63 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.nevercode.triage/code_cache/stable_flutterGJBBYK/stable_flutter/)
[   +7 ms] Updating assets
[ +141 ms] Syncing files to device Android SDK built for x86...
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +5 ms] <- recompile package:triage/main.dart eca6d508-5f67-43b7-890d-2fd3e265e3cc
[        ] <- eca6d508-5f67-43b7-890d-2fd3e265e3cc
[ +288 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86... (completed in 298ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +13 ms] Connected to _flutterView/0xc2b09c10.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:62999/Xo5ICiO1Koo=/
[   +1 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on Android SDK built for x86 is available at:
           http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A62999%2FXo5ICiO1Koo%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[  +46 ms] E/flutter (16512): [ERROR:flutter/runtime/dart_isolate.cc(1137)] Unhandled exception:
[        ] E/flutter (16512): UI actions are only available on root isolate.
[        ] E/flutter (16512): #0      PlatformDispatcher._nativeSetNeedsReportTimings
(dart:ui/platform_dispatcher.dart:369:59)
[        ] E/flutter (16512): #1      PlatformDispatcher.onReportTimings= (dart:ui/platform_dispatcher.dart:361:29)
[        ] E/flutter (16512): #2      SingletonFlutterWindow.onReportTimings= (dart:ui/window.dart:540:24)
[        ] E/flutter (16512): #3      SchedulerBinding.addTimingsCallback
(package:flutter/src/scheduler/binding.dart:269:14)
[        ] E/flutter (16512): #4      SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:206:7)
[        ] E/flutter (16512): #5      ServicesBinding.initInstances (package:flutter/src/services/binding.dart:27:11)
[        ] E/flutter (16512): #6      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:22:11)
[   +6 ms] E/flutter (16512): #7      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
[        ] E/flutter (16512): #8      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:28:11)
[        ] E/flutter (16512): #9      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:277:11)
[        ] E/flutter (16512): #10     new BindingBase (package:flutter/src/foundation/binding.dart:56:5)
[        ] E/flutter (16512): #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding
(package:flutter/src/widgets/binding.dart)
[        ] E/flutter (16512): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding
(package:flutter/src/widgets/binding.dart)
[        ] E/flutter (16512): #13     new
_WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding
(package:flutter/src/widgets/binding.dart)
[  +23 ms] E/flutter (16512): #14     new
_WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding
(package:flutter/src/widgets/binding.dart)
[   +1 ms] E/flutter (16512): #15     new
_WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding
(package:flutter/src/widgets/binding.dart)
[        ] E/flutter (16512): #16     new
_WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&Rende
rerBinding (package:flutter/src/widgets/binding.dart)
[        ] E/flutter (16512): #17     new
_WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&Rende
rerBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
[        ] E/flutter (16512): #18     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
[        ] E/flutter (16512): #19     WidgetsFlutterBinding.ensureInitialized
(package:flutter/src/widgets/binding.dart:1237:7)
[        ] E/flutter (16512): #20     runApp (package:flutter/src/widgets/binding.dart:1021:25)
[        ] E/flutter (16512): #21     main (package:triage/main.dart:5:3)
[   +1 ms] E/flutter (16512): #22     _delayEntrypointInvocation.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:283:19)
[        ] E/flutter (16512): #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[!] Connected device
    ! No devices available
! Doctor found issues in 4 categories.
```
```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.72, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-5.0.pre.72 at /Users/tahatesser/Code/flutter_master
    • Framework revision bb3e64dae6 (6 hours ago), 2021-02-19 00:36:03 -0500
    • Engine revision c217d9d06e
    • Dart version 2.13.0 (build 2.13.0-46.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 2 categories.
```

</details>


Thank you

**Comment by chinmaygarde** [comment]
Flutter does not support `Isolate.spawnURI` as it cannot be implement in AOT modes. However, the failure mode today is very confusing as "an" isolate does launch. However, this is just the snapshot of the root isolate. @iulian0512: Are you trying to achieve dynamic code push perhaps? The discussion around that is in this issue https://github.com/flutter/flutter/issues/14330.

Separately, the issue does mention that UI actions cannot be accessed from the non-root isolate. This is working as intended as secondary isolate cannot schedule frames and such.

I am going retitle this issue to track making the error easier understand.

**Comment by iulian0512** [comment]
> Are you trying to achieve dynamic code push perhaps? The discussion around that is in this issue #14330.
I am trying to load some simple functionality dynamically, can you point me in the right direction? For example i provide to the isolate/dynamic code some strings then process them then return a value.
