### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Не удается найти указанный файл., errno = 2

### ISSUE THREAD

**Issue by markbrutx** [flutter/flutter#76479]
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Не удается найти указанный файл.
, errno = 2
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#5      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:97:16)
#6      CreateCommand._computeTemplateManifest (package:flutter_tools/src/commands/create.dart:296:37)
#7      CreateCommand.templateManifest (package:flutter_tools/src/commands/create.dart:282:58)
#8      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:796:25)
#9      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:671:29)
#10     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:436:37)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale ru-RU)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Mark\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\Mark\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by hamdikahloun** [comment]
Hi @markbrutx 
There's similar open [issue](https://github.com/flutter/flutter/issues/76470) in which you can follow-up for updates and any questions.
Thank you

**Comment by iapicca** [comment]
> There's similar open [issue](https://github.com/flutter/flutter/issues/76470) in which you can follow-up for updates and any questions.
> Thank you

@hamdikahloun 
the issue you mentioned is not (yet) workable as it refer to an obsolete flutter version while this issue points at the latest stable
I'd consider reopening

**Comment by pedromassangocode** [comment]
Somehow similar to https://github.com/flutter/flutter/issues/68958.

**Comment by jmagman** [comment]
> > There's similar open [issue](https://github.com/flutter/flutter/issues/76470) in which you can follow-up for updates and any questions.
> > Thank you
> 
> @hamdikahloun
> the issue you mentioned is not (yet) workable as it refer to an obsolete flutter version while this issue points at the latest stable
> I'd consider reopening

The important part isn't the Flutter version, it's that the stack traces are totally different.  This is in `CreateCommand._computeTemplateManifest`

**Comment by pedromassangocode** [comment]
@jmagman can this be closed?

**Comment by iapicca** [comment]
dupe https://github.com/flutter/flutter/issues/68958

**Comment by darshankawar** [comment]
> dupe? #68958

Doesn't look like it.  The linked issue has stacktrace from `web`:

```
WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:833:57)
#6      _ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:736:54)
<asynchronous suspension>
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:518:47)
<asynchronous suspension>
#8      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart)
```

**Comment by iapicca** [comment]
> > dupe? #68958
> 
> Doesn't look like it. The linked issue has stacktrace from `web`:
> 
> ```
> WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:833:57)
> #6      _ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:736:54)
> <asynchronous suspension>
> #7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:518:47)
> <asynchronous suspension>
> #8      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart)
> ```

@darshankawar 
I didn't notice,
actually flutter web didn't even have [stable support](https://medium.com/flutter/web-post-d6b84e83b425) when the issue was open, so maybe isn't valid

> [✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale ru-RU)
>     • Flutter version 1.22.6 at C:\flutter
>     • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
>     • Engine revision 2f0af37152
>     • Dart version 2.10.5

**Comment by matanlurey** [comment]
If there is a reproduction case with a modern version of Flutter, we'd be happy to take a look.

Closing as stale for now.
