### ISSUE TITLE
[Linux] Failed to load bundled dynamic library

### ISSUE THREAD

**Issue by Sunbreak** [flutter/flutter#76499]
Ref: https://github.com/woodemi/quick_usb/issues/9

Code below results in `Failed to load dynamic library (libusb-1.0.23.so: cannot open shared object file: No such file or directory)`

https://github.com/woodemi/quick_usb/blob/0.1.0+2/lib/src/quick_usb_desktop.dart#L26-L28

```dart
  QuickUsbLinux() {
    _libusb = Libusb(DynamicLibrary.open('libusb-1.0.23.so'));
  }
```

Code below works however

https://github.com/woodemi/libusb.dart/blob/0.2.23+1/example/listdevs.dart#L14

```dart
    return DynamicLibrary.open('${Directory.current.path}/libusb-1.0/libusb-1.0.so');
```

## Steps to Reproduce

1. git clone https://github.com/woodemi/quick_usb -b 0.1.0+2
2. cd example && flutter run
3. Click `init` button

**Expected results:** 

Dynamic library loaded properly

**Actual results:** 

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (libusb-1.0.23.so: cannot open shared object file: No such file or directory)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      new QuickUsbLinux (package:quick_usb/src/quick_usb_desktop.dart:27:37)
#3      _platform (package:quick_usb/quick_usb.dart:27:35)
#4      QuickUsb.init (package:quick_usb/quick_usb.dart:36:33)
#5      _MyAppState._init_exit.<anonymous closure> (package:quick_usb_example/main.dart:51:39)
#6      _MyAppState._init_exit.<anonymous closure> (package:quick_usb_example/main.dart:50:22)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
#22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
#23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
#24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
#25     _rootRunUnary (dart:async/zone.dart:1370:13)
#26     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#28     _invoke1 (dart:ui/hooks.dart:180:10)
#29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
#30     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

<details>
  <summary>Logs</summary>

- flutter doctor -v

```
[✓] Flutter (Channel beta, 1.26.0-17.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-17.2.pre at /home/sunbreak/flutter/flutter-1.26.x-beta
    • Framework revision 79b49b9e10 (3 weeks ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/sunbreak/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your PATH. You can download the JDK from
      https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.
```

</details>

**Comment by stuartmorgan** [comment]
I'm not sure why you believe that `DynamicLibrary.open` is expected to assume that a library with no path is relative to the application being run, but that function is part of Dart, not Flutter, so this isn't the place to report issues with it.

**Comment by Sunbreak** [comment]
Forgot to mention CMakeList for both Windows and Linux

## Windows works

https://github.com/woodemi/quick_usb/blob/0.1.0+2/lib/src/quick_usb_desktop.dart#L26-L28

```dart
class QuickUsbWindows extends _QuickUsbDesktop {
  QuickUsbWindows() {
    _libusb = Libusb(DynamicLibrary.open('libusb-1.0.23.dll'));
  }
}
```

https://github.com/woodemi/quick_usb/blob/0.1.0+2/windows/CMakeLists.txt#L21-L24

```cmake
set(quick_usb_bundled_libraries
  "${CMAKE_CURRENT_SOURCE_DIR}/libusb-1.0.23.dll"
  PARENT_SCOPE
)
```

## Linux doesn't work

https://github.com/woodemi/quick_usb/blob/0.1.0+2/lib/src/quick_usb_desktop.dart#L26-L28

```dart
  QuickUsbLinux() {
    _libusb = Libusb(DynamicLibrary.open('libusb-1.0.23.so'));
  }
```

https://github.com/woodemi/quick_usb/blob/0.1.0+2/linux/CMakeLists.txt#L22-L25

```cmake
set(quick_usb_bundled_libraries
  "${CMAKE_CURRENT_SOURCE_DIR}/libusb-1.0.23.so"
  PARENT_SCOPE
)
```

**Comment by Sunbreak** [comment]
It turns out that Flutter APP on Linux makes the process working directory as the DynamicLibrary.open search path

On the other hand, Flutter APP on Windows use the location of executable file as the DynamicLibrary.open search path, wherever it is called (PROJECT_ROOT, C:\, etc) in CMD prompt

https://github.com/woodemi/quick_usb/issues/9#issuecomment-783138442

**Comment by xuelongqy** [comment]
DynamicLibrary.open('${File(Platform.resolvedExecutable).parent.path}/lib/libusb-1.0.23.so')

**Comment by Sunbreak** [comment]
> DynamicLibrary.open('${File(Platform.resolvedExecutable).parent.path}/lib/libusb-1.0.23.so')

[It works](https://github.com/woodemi/quick_usb/pull/22). Thanks a lot
