### ISSUE TITLE
When i run an app  in smasung m21 android 11 as soon as i click in textfield app crashed.

### ISSUE THREAD

**Issue by ashut08** [flutter/flutter#76503]
Providing LogCat ouput

```
E/AndroidRuntime(13422): FATAL EXCEPTION: main
E/AndroidRuntime(13422): Process: com.regalmojo.silaikhata, PID: 13422
E/AndroidRuntime(13422): java.lang.AbstractMethodError: abstract method "android.view.WindowInsets android.view.WindowInsetsAni
mation$Callback.onProgress(android.view.WindowInsets, java.util.List)"
E/AndroidRuntime(13422):        at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12131)
E/AndroidRuntime(13422):        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8457)
E/AndroidRuntime(13422):        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
E/AndroidRuntime(13422):        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
E/AndroidRuntime(13422):        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
E/AndroidRuntime(13422):        at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:8463)
E/AndroidRuntime(13422):        at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInse
tsControllerHost.java:111)
E/AndroidRuntime(13422):        at android.view.InsetsController.lambda$new$2$InsetsController(InsetsController.java:626)
E/AndroidRuntime(13422):        at android.view.-$$Lambda$InsetsController$zpmOxHfTFV_3me2u3C8YaXSUauQ.run(Unknown Source:2)
E/AndroidRuntime(13422):        at android.view.InsetsController.scheduleApplyChangeInsets(InsetsController.java:1488)
E/AndroidRuntime(13422):        at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:18
8)
E/AndroidRuntime(13422):        at android.view.InsetsAnimationControlImpl.setInsetsAndAlpha(InsetsAnimationControlImpl.java:17
2)
E/AndroidRuntime(13422):        at android.view.InsetsController$InternalAnimationControlListener.lambda$onReady$0$InsetsContro
ller$InternalAnimationControlListener(InsetsController.java:364)
E/AndroidRuntime(13422):        at android.view.-$$Lambda$InsetsController$InternalAnimationControlListener$SInf91MjJKDQFXwrp7C
-HBi0xaQ.onAnimationUpdate(Unknown Source:13)
E/AndroidRuntime(13422):        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
E/AndroidRuntime(13422):        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
E/AndroidRuntime(13422):        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
E/AndroidRuntime(13422):        at android.animation.ValueAnimator.start(ValueAnimator.java:1087)
E/AndroidRuntime(13422):        at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
E/AndroidRuntime(13422):        at android.view.InsetsController$InternalAnimationControlListener.onReady(InsetsController.java
:381)
E/AndroidRuntime(13422):        at android.view.InsetsController.lambda$startAnimation$6$InsetsController(InsetsController.java
:1471)
E/AndroidRuntime(13422):        at android.view.-$$Lambda$InsetsController$VzAUS17blucBK1u6-37NlEpdYqI.run(Unknown Source:12)
E/AndroidRuntime(13422):        at android.view.ViewRootInsetsControllerHost$1.onPreDraw(ViewRootInsetsControllerHost.java:72)
E/AndroidRuntime(13422):        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1124)
E/AndroidRuntime(13422):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3742)
E/AndroidRuntime(13422):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2519)
E/AndroidRuntime(13422):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9775)
E/AndroidRuntime(13422):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
E/AndroidRuntime(13422):        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
E/AndroidRuntime(13422):        at android.view.Choreographer.doFrame(Choreographer.java:744)
E/AndroidRuntime(13422):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
E/AndroidRuntime(13422):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(13422):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13422):        at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(13422):        at android.app.ActivityThread.main(ActivityThread.java:8443)
E/AndroidRuntime(13422):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13422):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
E/AndroidRuntime(13422):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Here is my output of **Flutter doctor -v**
```
`[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 1.26.0-1.0.pre at C:\flutter
    • Framework revision 63062a6443 (2 months ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Dinesh Sheoran\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Dinesh Sheoran\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0
[√] Connected device (3 available)
    • SM M215F (mobile)                  • RZ8NC0F620F   • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.150`
```

**Comment by darshankawar** [comment]
@ashut08 
You seem to be on older version of dev. Current version is `1.27.0-4.0.pre`. Can you try to upgrade and run again to see if issue persists or not ?
If yes, can you provide a minimal complete reproducible code sample that shows the crash ?

**Comment by ashut08** [comment]
Thanks @darshankawar after swiching stable channel error gone.
