### ISSUE TITLE
frontend_server failing on compiling engine test fixtures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76541]
First noted on the roll here https://github.com/flutter/engine/pull/24552
```
Command failed: ./dart /b/s/w/ir/cache/builder/src/out/host_profile_unopt/frontend_server.dart.snapshot --sdk-root /b/s/w/ir/cache/builder/src/out/host_profile_unopt/flutter_patched_sdk --target flutter --enable-experiment=non-nullable --output-dill gen/flutter/third_party/tonic/tests/assets/kernel_blob.bin --depfile /b/s/w/ir/cache/builder/src/out/host_profile_unopt/gen/flutter/third_party/tonic/tests/snapshot__dsk__ds_tonic_fixtures.depfile.d --aot --tfa /b/s/w/ir/cache/builder/src/flutter/third_party/tonic/tests/fixtures/tonic_test.dart
output: result 550bbaf2-1bed-4f58-ae1f-89449c693516
Unhandled exception:
root::dart:ui::TileMode::@getters::index is already bound
#0      CanonicalName.bindTo (package:kernel/canonical_name.dart:210:7)
#1      Class.computeCanonicalNames (package:kernel/ast.dart:1280:51)
#2      Library.computeCanonicalNames (package:kernel/ast.dart:563:14)
#3      Component.computeCanonicalNamesForLibrary (package:kernel/ast.dart:12654:13)
#4      Component.computeCanonicalNames (package:kernel/ast.dart:12616:7)
#5      sortComponent (package:vm/kernel_front_end.dart:679:13)
#6      FrontendCompiler.writeDillFile (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/frontend_server/lib/frontend_server.dart:660:5)
#7      FrontendCompiler.compile (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/frontend_server/lib/frontend_server.dart:548:13)
<asynchronous suspension>
#8      starter (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/frontend_server/lib/frontend_server.dart:1334:12)
<asynchronous suspension>
#9      main (file:///b/s/w/ir/cache/builder/src/third_party/dart/pkg/frontend_server/bin/frontend_server_starter.dart:9:14)
<asynchronous suspension>
```

Sheriff: @gw280 
frontend_server: @aam

**Comment by aam** [comment]
Should be resolved via https://dart.googlesource.com/sdk/+/79de274398064e96b5fe9c7a5fc715e6c82d1c5c
