### ISSUE TITLE
Camera plugin crashes the app on takePicture

### ISSUE THREAD

**Issue by eliaweiss** [flutter/flutter#76586]
Tested on android:

The following code causes the app to crash with the following error

This happen on android after upgrading camera plugin from "0.5.8+7" to "0.7.0+2"

<details>
<summary>code sample</summary>

```dart
  import 'dart:async';
  import 'dart:io';
  
  import 'package:camera/camera.dart';
  import 'package:flutter/material.dart';
  import 'package:flutter_bloc/flutter_bloc.dart';
  import 'package:flutter_image_compress/flutter_image_compress.dart';
  import 'package:image_picker/image_picker.dart';
  import 'package:zapit/bloc/receipt_bloc.dart';
  import 'package:zapit/bloc/receipt_event.dart';
  import 'package:zapit/bloc/receipt_state.dart';
  import 'package:zapit/classes/AppLocalization.dart';
  import 'package:zapit/globals.dart';
  import 'package:zapit/models/Receipt.dart';
  import 'package:zapit/models/ReceiptDao.dart';
  import 'package:zapit/models/appState.dart';
  import 'package:zapit/receipt/ReceiptDetails.dart';
  
  // A screen that allows users to take a picture using a given camera.
  class TakePictureScreen extends StatefulWidget {
    const TakePictureScreen({
      Key key,
    }) : super(key: key);
  
    @override
    TakePictureScreenState createState() => TakePictureScreenState();
  }
  
  class TakePictureScreenState extends State<TakePictureScreen> {
    ReceiptDao _receiptDao = ReceiptDao();
    ReceiptBloc _receiptBloc;
  
    CameraController _controller;
    Future<void> _initializeControllerFuture;
  
    AppState appState;
  
    get getCameraWidget {
      bool showCamera = AppState.params['showCamera'] ?? true;
      if (!showCamera) {
        return Container(key: Key("NoCameraTstContainer"));
      }
  
      return FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.
  
            return CameraPreview(_controller);
          } else {
            // Otherwise, display a loading indicator.
            return Center(child: CircularProgressIndicator());
          }
        },
      );
    }
  
    @override
    void initState() {
      super.initState();
      _receiptBloc = BlocProvider.of<ReceiptBloc>(context);
    }
  
    @override
    void dispose() {
      // Dispose of the controller when the widget is disposed.
      _controller.dispose();
      super.dispose();
    }
  
    @override
    Widget build(BuildContext context) {
      // var container = AppStateContainer.of(context);
      // For example, get grab its property called state!
      appState = AppState.state;
  
      // To display the current output from the Camera,
      // create a CameraController.
      _controller = CameraController(
        // Get a specific camera from the list of available cameras.
        appState.camera,
        // Define the resolution to use.
        ResolutionPreset.ultraHigh,
      );
  
      // Next, initialize the controller. This returns a Future.
      _initializeControllerFuture = _controller.initialize();
      return BlocBuilder<ReceiptBloc, ReceiptState>(
  
          // Whenever there is a new state emitted from the bloc, builder runs.
          builder: (context, state) {
  
  
            return Scaffold(
              appBar: AppBar(
                  title: Text(AppLocalizations.of(context).newReceiptTitle)),
              // Wait until the controller is initialized before displaying the
              // camera preview. Use a FutureBuilder to display a loading spinner
              // until the controller has finished initializing.
              body: getCameraWidget,
              floatingActionButton: Row(children: <Widget>[
  
                SizedBox(
                  width: 15,
                ),
                FloatingActionButton(
  
                  heroTag: "add_a_photo",
                  child: Icon(Icons.add_a_photo,key: Key("add_a_photo"),),
                  // Provide an onPressed callback.
                  onPressed: () async {
                    // Take the Picture in a try / catch block. If anything goes wrong,
                    // catch the error.
                    try {
                      // Ensure that the camera is initialized.
                      await _initializeControllerFuture;
  
  
                      // Attempt to take a picture and log where it's been saved.
                      XFile file = await _controller.takePicture();
  
                      await rotateIfNeed(file.path);
  
                      createReceiptWithPath(context, file.path);
                    } catch (e) {
                      // If an error occurs, log the error to the console.
                      print(e);
                    }
                  },
                ),
              ]),
              floatingActionButtonLocation:
                  FloatingActionButtonLocation.centerFloat,
            );
          });
    }
  
  
  
    void createReceiptWithPath(context, String path) async {
      Receipt newReceipt = await ReceiptDao().createEmptyReceipt();
  
      newReceipt['receiptData']['imagePath'] = path;
      if (AppState.state.identifier != null) {
        var appUserId = AppState.state.identifier;
        if (AppState.state.isLoggedIn() != null) {
          appUserId = AppState.state.isLoggedIn();
        }
        newReceipt['appUserId'] = appUserId;
      } else {
        newReceipt['appUserId'] = UNKNOWN;
      }
  
      // newReceipt.name = AppLocalizations.of(context).newReceiptTitle;
      _receiptBloc.add(UpdateReceipt(newReceipt));
      Navigator.of(context)
          .pop({'status': 'newReceipt', 'newReceipt': newReceipt});
    }
  
    rotateIfNeed(String path) async {
      if (path == '') return false;
  
      try {
        File image = File(path);
        List<int> imageBytes = await image.readAsBytes();
  
        var decodedImage = await decodeImageFromList(image.readAsBytesSync());
  
        if (decodedImage.width > decodedImage.height) {
          int rotate = -90;
  
          List<int> result = await FlutterImageCompress.compressWithList(
              imageBytes,
              quality: 100,
              rotate: rotate);
  
          await image.writeAsBytes(result);
  //        print(">>>" + image.path);
        }
      } catch (e) {
        print(e);
        return false;
      }
    }
  }

```

</details>

<details>
<summary>logs</summary>

```bash
W/Camera  ( 7996): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
W/com.zapit.zapit( 7996): type=1400 audit(0.0:145824): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=18684 scontext=u:r:untrusted_app:s0:c171,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
E/libc    ( 7996): Access denied finding property "persist.vendor.camera.privapp.list"
W/Gralloc3( 7996): allocator 3.x is not supported
D/AndroidRuntime( 7996): Shutting down VM
E/AndroidRuntime( 7996): FATAL EXCEPTION: main
E/AndroidRuntime( 7996): Process: com.zapit.zapit, PID: 7996
E/AndroidRuntime( 7996): java.lang.NullPointerException: Attempt to invoke virtual method 'int io.flutter.embedding.engine.systemchannels.PlatformChannel$DeviceOrientation.ordinal()' on a null object reference
E/AndroidRuntime( 7996): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:58)
E/AndroidRuntime( 7996): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:53)
E/AndroidRuntime( 7996): 	at io.flutter.plugins.camera.Camera.runPictureCapture(Camera.java:552)
E/AndroidRuntime( 7996): 	at io.flutter.plugins.camera.Camera.access$1500(Camera.java:73)
E/AndroidRuntime( 7996): 	at io.flutter.plugins.camera.Camera$3.processCapture(Camera.java:493)
E/AndroidRuntime( 7996): 	at io.flutter.plugins.camera.Camera$3.onCaptureProgressed(Camera.java:450)
E/AndroidRuntime( 7996): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureProgressed$2$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:627)
E/AndroidRuntime( 7996): 	at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$7mSdNTTAoYA0D3ITDxzDJKGykz0.run(Unknown Source:8)
E/AndroidRuntime( 7996): 	at android.os.Handler.handleCallback(Handler.java:914)
E/AndroidRuntime( 7996): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 7996): 	at android.os.Looper.loop(Looper.java:225)
E/AndroidRuntime( 7996): 	at android.app.ActivityThread.main(ActivityThread.java:7564)
E/AndroidRuntime( 7996): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7996): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime( 7996): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
D/OOMEventManagerFK( 7996): checkEventAndDumpForJE: 0
I/Process ( 7996): Sending signal. PID: 7996 SIG: 9
```

</details>

**Comment by TahaTesser** [comment]
Hi @eliaweiss 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/46952
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
