### ISSUE TITLE
New web project throws an error using CanvasKit only

### ISSUE THREAD

**Issue by jlubeck** [flutter/flutter#76581]
## Steps to Reproduce

Start a new project on Android Studio and debug on Chrome (web)

**Expected results:** 

App should work fine

**Actual results:** 

Getting this error inside Android Studio: 

```
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:56433/dart_sdk.js:5342:11)
    at Object.nullCheck (http://localhost:56433/dart_sdk.js:5675:30)
    at _engine._PointerAdapter.new.[_getSanitizer] (http://localhost:56433/dart_sdk.js:165972:28)
    at http://localhost:56433/dart_sdk.js:166031:42
    at http://localhost:56433/dart_sdk.js:165990:16
    at http://localhost:56433/dart_sdk.js:165689:11
    at <anonymous>
    at http://localhost:56433/dart_sdk.js:50591:13
    at Generator.next (<anonymous>)
    at runBody (http://localhost:56433/dart_sdk.js:39177:34)
    at Object._async [as async] (http://localhost:56433/dart_sdk.js:39208:7)
    at http://localhost:56433/dart_sdk.js:50582:20
    at new Promise (<anonymous>)
    at Object._invokeExtension [as invokeExtension] (http://localhost:56433/dart_sdk.js:50579:12)
    at <anonymous>:1:31
```

And this one on Google Chrome's console

```
errors.dart:187 Uncaught Error: Unexpected null value.
    at Object.throw_ [as throw] (errors.dart:236)
    at Object.nullCheck (operations.dart:518)
    at _engine._PointerAdapter.new.[_getSanitizer] (pointer_binding.dart:487)
    at pointer_binding.dart:557
    at pointer_binding.dart:505
    at pointer_binding.dart:214
    at <anonymous>
    at developer_patch.dart:88
    at Generator.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at developer_patch.dart:80
    at new Promise (<anonymous>)
    at Object._invokeExtension [as invokeExtension] (developer_patch.dart:79)
    at <anonymous>:1:31
```

If I change the web renderer it works fine
<img width="742" alt="Screen Shot 2021-02-22 at 10 54 44 PM" src="https://user-images.githubusercontent.com/3067603/108800388-f739c280-7560-11eb-9c84-677dbc2352d2.png">

Interestingly enough, if I run `flutter run --verbose` it also works fine

So I'm not sure if Android Studio runs something different?

<details>
  <summary>Logs</summary>

```
[  +79 ms] executing: sysctl hw.optional.arm64
[  +14 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +12 ms] executing: [/Users/jan/flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[  +18 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[        ] executing: [/Users/jan/flutter/] git tag --points-at
f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[  +21 ms] Exit code 0 from: git tag --points-at
f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[        ] 1.27.0-4.0.pre
[  +42 ms] executing: [/Users/jan/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/jan/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +48 ms] executing: [/Users/jan/flutter/] git rev-parse --abbrev-ref HEAD
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +6 ms] executing: sw_vers -productName
[  +12 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.2.1
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20D74
[  +58 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +40 ms] executing: /Users/jan/Library/Android/sdk/platform-tools/adb devices
-l
[  +12 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +100 ms] Exit code 0 from: xcrun xcodebuild -version
[   +1 ms] Xcode 12.4
           Build version 12D4e
[   +2 ms] executing: xcrun xcdevice list --timeout 2
[   +3 ms] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[  +39 ms] List of devices attached
[  +88 ms] {
             "devices" : {
               "com.apple.CoreSimulator.SimRuntime.iOS-14-4" : [
                 {
                   "dataPath" :
                   "\/Users\/jan\/Library\/Developer\/CoreSimulator\/Devices\/6A
                   C26487-617B-438C-B82E-89FE9A2CC071\/data",
                   "logPath" :
                   "\/Users\/jan\/Library\/Logs\/CoreSimulator\/6AC26487-617B-43
                   8C-B82E-89FE9A2CC071",
                   "udid" : "6AC26487-617B-438C-B82E-89FE9A2CC071",
                   "isAvailable" : true,
                   "deviceTypeIdentifier" :
                   "com.apple.CoreSimulator.SimDeviceType.iPhone-12",
                   "state" : "Shutdown",
                   "name" : "iPhone 12"
                 },
                 {
                   "dataPath" :
                   "\/Users\/jan\/Library\/Developer\/CoreSimulator\/Devices\/AF
                   BBE4FB-B202-406D-AE89-2D770B3D00A2\/data",
                   "logPath" :
                   "\/Users\/jan\/Library\/Logs\/CoreSimulator\/AFBBE4FB-B202-40
                   6D-AE89-2D770B3D00A2",
                   "udid" : "AFBBE4FB-B202-406D-AE89-2D770B3D00A2",
                   "isAvailable" : true,
                   "deviceTypeIdentifier" :
                   "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-",
                   "state" : "Shutdown",
                   "name" : "iPad Pro (9.7-inch)"
                 }
               ],
               "com.apple.CoreSimulator.SimRuntime.iOS-13-5" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.watchOS-7-2" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.tvOS-14-3" : [

               ]
             }
           }
[+2717 ms] [
                      {
                        "modelCode" : "iPhone9,2",
                        "simulator" : false,
                        "modelName" : "iPhone 7 Plus (Model 1661, 1784, 1785,
                        1786)",
                        "error" : {
                          "code" : -13,
                          "failureReason" : "",
                          "underlyingErrors" : [
                            {
                              "code" : 3,
                              "failureReason" : "",
                              "description" : "iPhone de Jan Lubeck is locked.",
                              "recoverySuggestion" : "To use iPhone de Jan
                              Lubeck with Xcode, unlock it.",
                              "domain" : "DVTDeviceIneligibilityErrorDomain"
                            }
                          ],
                          "description" : "iPhone de Jan Lubeck is not
                          connected",
                          "recoverySuggestion" : "Xcode will continue when
                          iPhone de Jan Lubeck is connected.",
                          "domain" : "com.apple.platform.iphoneos"
                        },
                        "operatingSystemVersion" : "14.0.1 (18A393)",
                        "identifier" :
                        "d167f1a8b5eed7cd0312f630a2da37135e6788f3",
                        "platform" : "com.apple.platform.iphoneos",
                        "architecture" : "arm64",
                        "interface" : "usb",
                        "available" : false,
                        "name" : "iPhone de Jan Lubeck",
                        "modelUTI" : "com.apple.iphone-7-plus-2"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.4 (18D46)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone13,2",
                        "identifier" : "6AC26487-617B-438C-B82E-89FE9A2CC071",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-12-1",
                        "modelName" : "iPhone 12",
                        "name" : "iPhone 12"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.4 (18D46)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,4",
                        "identifier" : "AFBBE4FB-B202-406D-AE89-2D770B3D00A2",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-9point7-a1674-b9b7ba",
                        "modelName" : "iPad Pro (9.7-inch)",
                        "name" : "iPad Pro (9.7-inch)"
                      }
                    ]
[   +2 ms] Error: iPhone de Jan Lubeck is not connected. Xcode will continue
when iPhone de Jan Lubeck is connected. (code -13)
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +70 ms] Multiple devices found:
[  +50 ms] macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74
darwin-x64
[   +1 ms] Chrome (web)    • chrome • web-javascript • Google Chrome
88.0.4324.182
[   +1 ms] [1]: macOS (macos)
[        ] [2]: Chrome (chrome)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] :
[+2792 ms] 2
[  +14 ms] Skipping pub get: version match.
[ +110 ms] Generating
/Users/jan/Projects/flutter/flutter_html_test/android/app/src/main/java/io/flutt
er/plugins/GeneratedPluginRegistrant.java
[  +84 ms] Launching lib/main.dart on Chrome in debug mode...
[ +111 ms] Updating assets
[  +59 ms] Waiting for connection from debug service on Chrome...
[  +54 ms] <- reset
[   +5 ms] /Users/jan/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/jan/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.sn
apshot --sdk-root /Users/jan/flutter/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/6d/7fb8q3_576358cs38040dm8h0000gn/T/flutter_tools.O6TeKI/flutter_to
ol.6ccp15/app.dill --libraries-spec
file:///Users/jan/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/jan/Projects/flutter/flutter_html_test/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
/var/folders/6d/7fb8q3_576358cs38040dm8h0000gn/T/flutter_tools.O6TeKI/flutter_to
ols.0kluNe --filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///Users/jan/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13456 ms] Waiting for connection from debug service on Chrome... (completed in
13.5s)
[        ] Synced 29.2MB.
[        ] <- accept
[        ] Caching compiled dill
[  +62 ms] Using Google Chrome 88.0.4324.182

[ +377 ms] [CHROME]:2021-02-22 22:52:45.210 Google Chrome[15962:167418] Error
loading
/Library/CoreMediaIO/Plug-Ins/DAL/ImmersedCamera.plugin/Contents/MacOS/ImmersedC
amera:
dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/ImmersedCamera.plugin/Contents/MacOS/Im
mersedCamera, 262): no suitable image found.  Did find:
[   +1 ms] [CHROME]:
/Library/CoreMediaIO/Plug-Ins/DAL/ImmersedCamera.plugin/Contents/MacOS/ImmersedC
amera: code signature in
(/Library/CoreMediaIO/Plug-Ins/DAL/ImmersedCamera.plugin/Contents/MacOS/Immersed
Camera) not valid for use in process using Library Validation: mapping process
and mapped file (non-platform) have different Team IDs
[        ] [CHROME]:
/Library/CoreMediaIO/Plug-Ins/DAL/ImmersedCamera.plugin/Contents/MacOS/ImmersedC
amera: stat() failed with errno=9
[ +118 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on
ws://127.0.0.1:58633/devtools/browser/21bff92b-f9cc-456e-8e3a-745ba56ece10
[ +750 ms] DwdsInjector: Received request for entrypoint at
http://localhost:58620/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[   +8 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[   +6 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:58620/main_module.bootstrap.js
[+1267 ms] ChromeProxyService: Initializing expression compiler for
main_module.bootstrap.js with sound null safety: false
[ +315 ms] DevHandler: Debug service listening on
ws://127.0.0.1:58652/de-Gpxl3WD4=/ws

[   +8 ms] Debug service listening on ws://127.0.0.1:58652/de-Gpxl3WD4=/ws
[        ] Running with unsound null safety
[        ] For more information see
https://dart.dev/null-safety/unsound-null-safety
[   +2 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".

```

```
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.2.1 20D74 darwin-x64,
    locale en-US)
    • Flutter version 1.27.0-4.0.pre at /Users/jan/flutter
    • Framework revision f8cd24de95 (6 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jan/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
```

</details>

**Comment by pedromassangocode** [comment]
Hi @jlubeck 
Can you please provide a minimal complete reproducible code sample?
Thank you

**Comment by jlubeck** [comment]
@pedromassangocode it happens with the default template when starting a new project on Android Studio:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by pedromassangocode** [comment]
I just had this same issue yesterday (https://github.com/flutter/flutter/issues/76690). @yjbanov can you please confirm that https://github.com/flutter/flutter/issues/76680 is the same as this one and it was fixed by https://github.com/flutter/flutter-intellij/pull/5286?

Thank you

**Comment by pedromassangocode** [comment]
Hi @jlubeck 
Based on my message above, this seems to be currently fixed on master.
Can you please confirm?
Thank you

**Comment by jlubeck** [comment]
Yup! Fixed on my side! Thanks
