### ISSUE TITLE
[maps] android_google_map_test shows `No tests ran.`

### ISSUE THREAD

**Issue by mohammaduvez** [flutter/flutter#76606]
[android_google_map_test](packages/google_maps_flutter/google_maps_flutter/test/android_google_map_test.dart) does not run because of [`@TestOn('android')`](https://github.com/flutter/plugins/blob/f47dbdf372feefea9268f3c03d9b2b4cd3ae2626/packages/google_maps_flutter/google_maps_flutter/test/android_google_map_test.dart#L5) annotation.
On removing the annotation the test runs and fails, because of the assertion [`Platform.isAndroid`](https://github.com/flutter/plugins/blob/f47dbdf372feefea9268f3c03d9b2b4cd3ae2626/packages/google_maps_flutter/google_maps_flutter/lib/src/google_map.dart#L469) which is false as the test is not integration test and not running on android.

I think the test is unnecessary as there is already integration test [`testLiteModeEnabled`](https://github.com/flutter/plugins/blob/f47dbdf372feefea9268f3c03d9b2b4cd3ae2626/packages/google_maps_flutter/google_maps_flutter/example/integration_test/google_maps_test.dart#L268).

## Steps to Reproduce
1. `flutter test .\packages\google_maps_flutter\google_maps_flutter\test\android_google_map_test.dart`

**Comment by TahaTesser** [comment]
Hi @mohammaduvez 
Thanks for filing the issue


### With @TestOn('android') annotation.
```dart
@TestOn('android')
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
```

```
tahatesser@Tahas-MacBook-Pro google_maps_flutter % flutterm test test/android_google_map_test.dart
No tests ran.
tahatesser@Tahas-MacBook-Pro google_maps_flutter % 
```

### Without @TestOn('android') annotation.
```dart
// @TestOn('android')
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
```


<details>
<summary>logs</summary>

```bash
tahatesser@Tahas-MacBook-Pro google_maps_flutter % flutterm test test/android_google_map_test.dart
00:02 +0: Can update liteModeEnabled                                                              
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
'package:google_maps_flutter/src/google_map.dart': Failed assertion: line 469 pos 16:
'!map.liteModeEnabled || Platform.isAndroid': is not true.

When the exception was thrown, this was the stack:
#2      new _GoogleMapOptions.fromWidget (package:google_maps_flutter/src/google_map.dart:469:16)
#3      _GoogleMapState._updateOptions (package:google_maps_flutter/src/google_map.dart:295:60)
#4      _GoogleMapState.didUpdateWidget (package:google_maps_flutter/src/google_map.dart:286:5)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:4774:57)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3365:15)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4281:5)
#9      ProxyElement.update (package:flutter/src/widgets/framework.dart:4935:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3365:15)
#11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1189:16)
#12     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1167:5)
#13     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1181:7)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4281:5)
#15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2599:33)
#16     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1106:19)
#17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#20     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:973:9)
#23     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#24     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:960:27)
#25     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:521:22)
#28     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#29     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:518:27)
#30     main.<anonymous closure> (file:///Users/tahatesser/AndroidStudioProjects/plugins/packages/google_maps_flutter/google_maps_flutter/test/android_google_map_test.dart:44:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 7 frames from class _AssertionError, dart:async, and package:stack_trace)

The test description was:
  Can update liteModeEnabled
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: Can update liteModeEnabled [E]                                                       
  Test failed. See exception logs above.
  The test description was: Can update liteModeEnabled
  
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test (but after the test had completed):
  Expected: <true>
  Actual: <false>

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:155:31)
#1      _expect (package:test_api/src/frontend/expect.dart:150:3)
#2      expect (package:test_api/src/frontend/expect.dart:59:3)
#3      expect (package:flutter_test/src/widget_tester.dart:428:3)
#4      main.<anonymous closure> (file:///Users/tahatesser/AndroidStudioProjects/plugins/packages/google_maps_flutter/google_maps_flutter/test/android_google_map_test.dart:54:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: Some tests failed.                                                                   
tahatesser@Tahas-MacBook-Pro google_maps_flutter % 
```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.132, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-5.0.pre.132 at /Users/tahatesser/Code/flutter_master
    • Framework revision 65e94f51c0 (3 hours ago), 2021-02-23 19:56:02 -0800
    • Engine revision f925e560de
    • Dart version 2.13.0 (build 2.13.0-68.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 948EC106-78EE-4A69-8D31-83C00E6419DE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 88.0.4324.192
! Doctor found issues in 2 categories.
```

</details>

**Comment by cyanglaz** [comment]
Looks like a simple solution would just be remove the test.
