### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The device is not ready., errno = 21

### ISSUE THREAD

**Issue by CoolBa98** [flutter/flutter#76617]
## Command
```
flutter create learn
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: Le périphérique n’est pas prêt.
, errno = 21
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#2      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45:33)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:304:79)
<asynchronous suspension>
#4      Template.fromName (package:flutter_tools/src/template.dart:77:38)
#5      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:791:46)
#6      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:671:29)
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:436:37)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [version 10.0.18363.1379], locale fr-FR)
    • Flutter version 1.22.6 at F:\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\hp\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.44.1)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • SM A217F (mobile) • 192.168.43.1:5555 • android-arm64 • Android 10 (API 29)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment]
@CoolBa98 
given https://github.com/flutter/flutter/issues/69154 I assume that the error translates in 
`[tool_crash] FileSystemException: Exists failed, OS Error: The device is not ready., errno = 21`

> ## Flutter Application Metadata
> No pubspec in working directory.

can you provide your full `flutter run -v` making sure you are in your app folder

**Comment by TahaTesser** [comment]
Hi @CoolBa98 
From which directory you're executing `flutter create learn`?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
