### ISSUE TITLE
Suddenly some main plugins like image_picker, google_sign_in, flutter_facebook_auth etc. are giving MissingPluginException 

### ISSUE THREAD

**Issue by aradhya32psp** [flutter/flutter#76669]
Some features, those were finely working, are suddenly giving **`MissingPluginException`**

```
E/flutter (12054): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
E/flutter (12054): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (12054): <asynchronous suspension>
E/flutter (12054): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (12054): #2      MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
E/flutter (12054): #3      ImagePicker.pickImage (package:image_picker/image_picker.dart:61:34)
E/flutter (12054): #4      _ImagesState.handleTakePhoto (package:gutargoo_talent_user/pages/imagesPosts.dart:19:35)
E/flutter (12054): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (12054): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (12054): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (12054): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (12054): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (12054): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (12054): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (12054): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (12054): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (12054): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (12054): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (12054): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (12054): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (12054): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (12054): #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (12054): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (12054): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (12054): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (12054): #23     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (12054): #24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12054): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (12054): #26     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (12054): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (12054): 
```

**Comment by iapicca** [comment]
@aradhya32psp 
can you provide your `flutter doctor -v`, your complete `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugin_**

**Comment by TahaTesser** [comment]
Hi @aradhya32psp 
This could be caused by third-party packages or an older Gradle version 

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, your `build.gradle` from the android folder, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example without 3rd party packages?
Thank you

**Comment by aradhya32psp** [comment]
Hi all... I solved it but I don't know the actual reason of this issue... It is happening by flutter_facebook_auth... When I removed it.. google_sign_in and image_picker are working fine.. So if any one know about how to use flutter_facebook_auth with firebase.. please comment

**Comment by iapicca** [comment]
> [...] So if any one know about how to use flutter_facebook_auth with firebase.. please comment

@aradhya32psp 
flutter's repo is meant for reporting bugs with flutter or its first party plugins or propose new features
since both [flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth) and [firebase](https://firebase.flutter.dev/)
are 3rd party plugin this isn't the place for this topic

I recommend to address the issue you are experiencing either on [firebase repo](https://github.com/FirebaseExtended/flutterfire/issues) or [flutter-facebook-auth repo](https://github.com/darwin-morocho/flutter-facebook-auth/issues)

without the [information](https://github.com/flutter/flutter/issues/76669#issuecomment-784937443) mentioned above this issue will not be workable
