### ISSUE TITLE
Error: Unexpected null value.

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#76690]
## Steps to Reproduce

1. run any Flutter project on Chrome in Master channel
2. See the null crash

Note: you may not see the error, it is probably that Chrome paused the debugger because of that error, go to Developer options and resume the debugger and see the crash on the console of your IDE.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cashex',
      routes: {
        '/': (_) => Scaffold(body: Center(child: Text('Hello Flutter'),),)
      }
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-5.0.pre.134, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-5.0.pre.134 at /Users/pedromassango/Code/flutter_master
    • Framework revision 354bd53f62 (2 hours ago), 2021-02-24 02:36:05 -0500
    • Engine revision 9061823775
    • Dart version 2.13.0 (build 2.13.0-68.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

<details>
<summary>logs</summary>

```bash
Running "flutter pub get" in cashex_landing...
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:56126/1tWXqmQvm-Q=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:56126/1tWXqmQvm-Q=/ws
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:56000/dart_sdk.js:5347:11)
    at Object.nullCheck (http://localhost:56000/dart_sdk.js:5680:30)
    at _engine._PointerAdapter.new.[_getSanitizer] (http://localhost:56000/dart_sdk.js:166679:28)
    at http://localhost:56000/dart_sdk.js:166739:42
    at http://localhost:56000/dart_sdk.js:166697:16
    at http://localhost:56000/dart_sdk.js:166391:11
    at <anonymous>
    at http://localhost:56000/dart_sdk.js:50601:13
    at Generator.next (<anonymous>)
    at runBody (http://localhost:56000/dart_sdk.js:39187:34)
    at Object._async [as async] (http://localhost:56000/dart_sdk.js:39218:7)
    at http://localhost:56000/dart_sdk.js:50592:20
    at new Promise (<anonymous>)
    at Object._invokeExtension [as invokeExtension] (http://localhost:56000/dart_sdk.js:50589:12)
    at <anonymous>:1:31
```
</details>

**Comment by pedromassango** [comment]
Current workaroud is to reload the webpage, but it is tedious.

![Screen Shot 2021-02-24 at 11 40 00](https://user-images.githubusercontent.com/33294549/108988689-0b7edc00-7695-11eb-8ba9-84d3aada52b9.png)

**Comment by TahaTesser** [comment]
Hi @pedromassango 
I can only see a white blank screen in Android Studio when running in debug mode on macOS and Windows, doesn't reproduce in VS Code or Terminal, reproducible on the `beta`,` dev`, and `master`, app launches in Android if you run without debug

I just reopened to be sure https://github.com/flutter/flutter/issues/76680 from earlier today
I see there's an open issue addressing the case you described. 
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
