### ISSUE TITLE
Platform view crash on stable

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#76728]
A user reported this crash on Flutter stable.  
## Logs

<details>
<summary>Logs</summary>

```
F/libc    (25410): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 25410 (iyaffle.womenly), pid 25410 (iyaffle.womenly)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/violet/violet:10/QKQ1.190915.002/V12.0.4.0.QFHINXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-02-02 00:16:43+0530
pid: 25410, tid: 25410, name: iyaffle.womenly  >>> com.iyaffle.womenly <<<
uid: 10431
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1196)] Check failed: CheckException(env). 
'
    x0  0000000000000000  x1  0000000000006342  x2  0000000000000006  x3  0000007fc9c117d0
    x4  0000000000008000  x5  0000000000008000  x6  0000000000008000  x7  0080000000000000
    x8  00000000000000f0  x9  321acdc509f4a52e  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 0000000000000003  x14 0000000000000001  x15 00004d2fedaa2c34
    x16 00000071c58a08c0  x17 00000071c587c900  x18 00000071ca804000  x19 0000000000006342
    x20 0000000000006342  x21 00000000ffffffff  x22 00000071c9aadb80  x23 0000000000000000
    x24 0000000000000437  x25 0000000000000113  x26 0000000000000001  x27 0000007fc9c11ad0
    x28 0000000000000099  x29 0000007fc9c11870
    sp  0000007fc9c117b0  lr  00000071c582e0c4  pc  00000071c582e0f0
backtrace:
      #00 pc 00000000000830f0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 328a3518945f3e056fc055f1eea1cc35)
      #01 pc 0000000001287244  /data/app/com.iyaffle.womenly-7hJo7WZ0C_h0cz4AOUPkSg==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #02 pc 0000000000000099  <unknown>
```

</details>

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.746], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by blasten** [comment]
@flutter-symbolizer-bot engine#2f0af3715217a0c2ada72c717d4ed9178d68f6ed

**Comment by mraleph** [comment]
@flutter-symbolizer-bot

**Comment by blasten** [comment]
The exception originated in Java:


```log
E/flutter ( 7844): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.IllegalStateException: The Android view returned from PlatformView#getView() was already added to a parent view.
E/flutter ( 7844): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:721)
E/flutter ( 7844): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:746)
E/flutter ( 7844): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1195)
E/flutter ( 7844): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 7844): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 7844): 	at android.os.Looper.loop(Looper.java:160)
E/flutter ( 7844): 	at android.app.ActivityThread.main(ActivityThread.java:6923)
E/flutter ( 7844): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7844): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 7844): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
E/flutter ( 7844):
F/flutter ( 7844): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1395)] Check failed: CheckException(env).
```

**Comment by wishinlife** [comment]
I have tested many times that if  the Dart Exception Breakpoint is Enbaled , there is a high probability that APP will crash when an exception occurs. If the Dart Exception Breakpoint is disabled, no crash problems occur.

**Comment by wishinlife** [comment]
I have tested many times that if  the Dart Exception Breakpoint is Enbaled , there is a high probability that APP will crash when an exception occurs. If the Dart Exception Breakpoint is disabled, no crash problems occur.
