### ISSUE TITLE
[tool_crash] ArchiveException

### ISSUE THREAD

**Issue by pretech86** [flutter/flutter#76862]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArchiveException
```
#0      Inflate._parseBlock (package:archive/src/zlib/inflate.dart:121:9)
#1      Inflate._inflate (package:archive/src/zlib/inflate.dart:87:20)
#2      new Inflate.buffer (package:archive/src/zlib/inflate.dart:19:5)
#3      ArchiveFile.decompress (package:archive/src/archive_file.dart:71:28)
#4      ArchiveFile.content (package:archive/src/archive_file.dart:62:7)
#5      _WindowsUtils._unpackArchive (package:flutter_tools/src/base/os.dart:405:45)
#6      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:380:5)
#7      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1512:18)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\kareem\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\kareem\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\kareem\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile)        • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86 • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment]
Considering the age of the issue and lack of activity, I am going ahead and closing this as stale.

@pretech86 If you are still experiencing this issue using latest stable version, please open a new issue using template so that we can address it.
