### ISSUE TITLE
Android Alarm manager not works properly in background

### ISSUE THREAD

**Issue by sidharathjain2** [flutter/flutter#76872]
I am facing an 
![error](https://user-images.githubusercontent.com/63875151/109336291-2c0f8780-7889-11eb-96cc-16492ce553a6.jpeg)
issue with the example app (https://pub.dev/packages/android_alarm_manager). Once killed off
It shows an error in the console

```
I/FlutterBackgroundExecutor(24917): Starting AlarmService...
E/AndroidRuntime(24917): FATAL EXCEPTION: main
E/AndroidRuntime(24917): Process: com.dexterous.flutter_local_notifications_example, PID: 24917
E/AndroidRuntime(24917): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(24917): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3613)
E/AndroidRuntime(24917): at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(24917): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
E/AndroidRuntime(24917): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24917): at android.os.Looper.loop(Looper.java:210)
E/AndroidRuntime(24917): at android.app.ActivityThread.main(ActivityThread.java:7080)
E/AndroidRuntime(24917): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24917): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
E/AndroidRuntime(24917): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
E/AndroidRuntime(24917): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(24917): at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:324)
E/AndroidRuntime(24917): at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:97)
E/AndroidRuntime(24917): at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:158)
E/AndroidRuntime(24917): at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:126)
E/AndroidRuntime(24917): at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:349)
E/AndroidRuntime(24917): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3603)
E/AndroidRuntime(24917): ... 8 more
I/FlutterBackgroundExecutor(25150): Starting AlarmService...
E/AndroidRuntime(25150): FATAL EXCEPTION: main
E/AndroidRuntime(25150): Process: com.dexterous.flutter_local_notifications_example, PID: 25150
E/AndroidRuntime(25150): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(25150): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3613)
E/AndroidRuntime(25150): at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(25150): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
E/AndroidRuntime(25150): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(25150): at android.os.Looper.loop(Looper.java:210)
E/AndroidRuntime(25150): at android.app.ActivityThread.main(ActivityThread.java:7080)
E/AndroidRuntime(25150): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25150): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
E/AndroidRuntime(25150): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
E/AndroidRuntime(25150): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
E/AndroidRuntime(25150): at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:324)
E/AndroidRuntime(25150): at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:97)
E/AndroidRuntime(25150): at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:158)
E/AndroidRuntime(25150): at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:126)
E/AndroidRuntime(25150): at io.flutter.plugins.androidalarmmanager.AlarmService.onCreate(AlarmService.java:349)
E/AndroidRuntime(25150): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3603)
E/AndroidRuntime(25150): ... 8 more
```
-------------------------------------------------------------------------------------------------------
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

• No issues found!

And after some time my android shows a message  Filed to start several times . Restore it by clearing history?
---------------------------------------------------------------------------------------------------

My main.dart file 

<details>
<summary> code sample </summary>

```
import 'dart:isolate';
import 'dart:math';
import 'dart:ui';

import 'package:android_alarm_manager/android_alarm_manager.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/material.dart';

/// The [SharedPreferences] key to access the alarm fire count.
const String countKey = 'count';

/// The name associated with the UI isolate's [SendPort].
const String isolateName = 'isolate';

/// A port used to communicate from a background isolate to the UI isolate.
final ReceivePort port = ReceivePort();

/// Global [SharedPreferences] object.
SharedPreferences prefs;

Future<void> main() async {
  // TODO(bkonyi): uncomment
  WidgetsFlutterBinding.ensureInitialized();

  // Register the UI isolate's SendPort to allow for communication from the
  // background isolate.
  IsolateNameServer.registerPortWithName(
    port.sendPort,
    isolateName,
  );
  prefs = await SharedPreferences.getInstance();
  if (!prefs.containsKey(countKey)) {
    await prefs.setInt(countKey, 0);
  }
  runApp(AlarmManagerExampleApp());
}

/// Example app for Espresso plugin.
class AlarmManagerExampleApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: _AlarmHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class _AlarmHomePage extends StatefulWidget {
  _AlarmHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _AlarmHomePageState createState() => _AlarmHomePageState();
}

class _AlarmHomePageState extends State<_AlarmHomePage> {
  int _counter = 0;

  @override
  void initState() {
    super.initState();
    AndroidAlarmManager.initialize();

    // Register for events from the background isolate. These messages will
    // always coincide with an alarm firing.
    port.listen((_) async => await _incrementCounter());
  }

  Future<void> _incrementCounter() async {
    print('Increment counter!');

    // Ensure we've loaded the updated count from the background isolate.
    await prefs.reload();

    setState(() {
      _counter++;
    });
  }

  // The background
  static SendPort uiSendPort;

  // The callback for our alarm
  static Future<void> callback() async {
    print('Alarm fired!');

    // Get the previous cached count and increment it.
    final prefs = await SharedPreferences.getInstance();
    int currentCount = prefs.getInt(countKey);
    await prefs.setInt(countKey, currentCount + 1);

    // This will be null if we're running in the background.
    uiSendPort ??= IsolateNameServer.lookupPortByName(isolateName);
    uiSendPort?.send(null);
  }

  @override
  Widget build(BuildContext context) {
    final textStyle = Theme.of(context).textTheme.headline4;
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Alarm fired $_counter times',
              style: textStyle,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'Total alarms fired: ',
                  style: textStyle,
                ),
                Text(
                  prefs.getInt(countKey).toString(),
                  key: ValueKey('BackgroundCountText'),
                  style: textStyle,
                ),
              ],
            ),
            ElevatedButton(
              child: Text(
                'Schedule periodic Alarm',
              ),
              key: ValueKey('RegisterOneShotAlarm'),
              onPressed: () async {
                await AndroidAlarmManager.periodic(
                  const Duration(seconds: 5),
                  // Ensure we have a unique alarm ID.
                  Random().nextInt(pow(2, 31)),
                  callback,
                  exact: true,
                  wakeup: true,
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

**Comment by darshankawar** [comment]
@sidharathjain2 
Tried your code sample on latest stable using Android 8.1.0 device and saw no issues. Ran the app, tapped on the button and put it in background for few mins. The alarm manager worked properly, as below:

```
Syncing files to device SM A260G...
I/FlutterBackgroundExecutor(13912): Starting AlarmService...
I/AndroidAlarmManagerPlugin(13912): onAttachedToEngine
I/AlarmService(13912): AlarmService started!
W/libEGL  (13912): EGLNativeWindowType 0xcfaea808 disconnect failed
W/libEGL  (13912): EGLNativeWindowType 0xd0cda008 disconnect failed
I/flutter (13912): Alarm fired!
I/flutter (13912): Increment counter!
I/flutter (13912): Alarm fired!
I/flutter (13912): Increment counter!
I/flutter (13912): Alarm fired!
I/zygote  (13912): Waiting for a blocking GC ProfileSaver
I/flutter (13912): Increment counter!
I/zygote  (13912): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 19.129ms
D/mali_winsys(13912): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x960]-format:1
D/mali_winsys(13912): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
E/BpSurfaceComposerClient(13912): Failed to transact (-1)
E/BpSurfaceComposerClient(13912): Failed to transact (-1)
W/libEGL  (13912): EGLNativeWindowType 0xc9452008 disconnect failed
W/libEGL  (13912): EGLNativeWindowType 0xd0cda008 disconnect failed
I/flutter (13912): Alarm fired!
I/flutter (13912): Increment counter!
I/flutter (13912): Alarm fired!
I/flutter (13912): Increment counter!
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

! Doctor found issues in 1 category.

```

</details>

Is this a correct replication of the issue ? If not, can you provide detailed steps to replicate ?

**Comment by cienijr** [comment]
I have a fresh new project (Flutter 2) and it also happened to me. 

Adding `android:name="io.flutter.app.FlutterApplication"` to `application` as suggested at
https://github.com/transistorsoft/flutter_background_fetch/issues/160#issuecomment-764770550 solved the issue.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
