### ISSUE TITLE
Oops; flutter has exited unexpectedly: "Value was missing for section tag: withDriverTest. (2:1) {{#withDriverTest}}

### ISSUE THREAD

**Issue by mdb2301** [flutter/flutter#76936]
## Terminal Output:
```
E:\Work\FlutterProjects>flutter create locationtest
Creating project locationtest...
  locationtest\.gitignore (created)
  locationtest\.idea\libraries\Dart_SDK.xml (created)
  locationtest\.idea\libraries\KotlinJavaRuntime.xml (created)
  locationtest\.idea\modules.xml (created)
  locationtest\.idea\runConfigurations\main_dart.xml (created)
  locationtest\.idea\workspace.xml (created)
  locationtest\.metadata (created)
  locationtest\android\app\build.gradle (created)
  locationtest\android\app\src\main\kotlin\com\example\locationtest\MainActivity.kt
  (created)
  locationtest\android\build.gradle (created)
  locationtest\android\locationtest_android.iml (created)
  locationtest\android\.gitignore (created)
  locationtest\android\app\src\debug\AndroidManifest.xml (created)
  locationtest\android\app\src\main\AndroidManifest.xml (created)
  locationtest\android\app\src\main\res\drawable\launch_background.xml (created)
  locationtest\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  locationtest\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  locationtest\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  locationtest\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  locationtest\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  locationtest\android\app\src\profile\AndroidManifest.xml (created)
  locationtest\android\gradle\wrapper\gradle-wrapper.properties (created)
  locationtest\android\gradle.properties (created)
  locationtest\android\settings.gradle (created)
  locationtest\ios\Runner\AppDelegate.swift (created)
  locationtest\ios\Runner\Runner-Bridging-Header.h (created)
  locationtest\ios\Runner.xcodeproj\project.pbxproj (created)
  locationtest\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  locationtest\ios\.gitignore (created)
  locationtest\ios\Flutter\AppFrameworkInfo.plist (created)
  locationtest\ios\Flutter\Debug.xcconfig (created)
  locationtest\ios\Flutter\Release.xcconfig (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.p
  ng (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.p
  ng (created)
  locationtest\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json
  (created)
  locationtest\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png
  (created)
  locationtest\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  locationtest\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  locationtest\ios\Runner\Base.lproj\Main.storyboard (created)
  locationtest\ios\Runner\Info.plist (created)
  locationtest\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata
  (created)
  locationtest\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChe
  cks.plist (created)
  locationtest\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettin
  gs.xcsettings (created)
  locationtest\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  locationtest\ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist
  (created)
  locationtest\ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings
  (created)
  locationtest\lib\main.dart (created)

Oops; flutter has exited unexpectedly: "Value was missing for section tag:
withDriverTest. (2:1)
{{#withDriverTest}}
^
".
A crash report has been written to E:\Work\FlutterProjects\flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+Value+was+missing+for+section+tag%3A+withDriverTest.+%282%3A1%29%0A%7B%7B%23withDriverTest%7D%7D%0A%5E%0A

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the
issue template. Thank you!
https://git.io/JtAQV
```

Also, a log file has been created in the folder as:

## command

flutter create locationtest

## exception

TemplateException: Value was missing for section tag: withDriverTest. (2:1)
{{#withDriverTest}}
^

```
#0      Renderer._renderSection (package:mustache_template/src/renderer.dart:135:9)
#1      Renderer.visitSection (package:mustache_template/src/renderer.dart:113:7)
#2      SectionNode.accept (package:mustache_template/src/node.dart:66:43)
#3      Renderer.render.<anonymous closure> (package:mustache_template/src/renderer.dart:52:30)
#4      List.forEach (dart:core-patch/growable_array.dart:403:8)
#5      Renderer.render (package:mustache_template/src/renderer.dart:52:13)
#6      Template.render (package:mustache_template/src/template.dart:42:14)
#7      Template.renderString (package:mustache_template/src/template.dart:34:5)
#8      MustacheTemplateRenderer.renderString (package:flutter_tools/src/isolated/mustache_template.dart:15:67)
#9      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:257:59)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#11     Template.render (package:flutter_tools/src/template.dart:193:24)
#12     CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:387:21)
<asynchronous suspension>
#13     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:23)
<asynchronous suspension>
#14     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:31)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#27     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#29     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1316],
    locale en-IN)
    • Flutter version 1.22.5 at E:\Work\flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Manda\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (1 available)
    • SM A605G (mobile) • 9da2976b • android-arm • Android 10 (API 29)

• No issues found!
```

PLEASE HELP!

**Comment by mdb2301** [comment]
Things are good after ```flutter downgrade```

**Comment by darshankawar** [comment]
@mdb2301 
So you got this error while creating a new Flutter project from Stable 1.22.5 version correct ? And when you downgraded, it worked.
Can you try to upgrade to latest (1.22.6) and see if issue persists or not ?
If so, please provide the generated crash log.

**Comment by mdb2301** [comment]
> @mdb2301
> So you got this error while creating a new Flutter project from Stable 1.22.5 version correct ? And when you downgraded, it worked.
> Can you try to upgrade to latest (1.22.6) and see if issue persists or not ?
> If so, please provide the generated crash log.

This one worked! 👍👍👍
