### ISSUE TITLE
Exception raised with custom keyboard buttons into the TextField (Windows)

### ISSUE THREAD

**Issue by carmas123** [flutter/flutter#76940]
I try to insert into an obscured textfield the @ char but with AltGr+ò that in italian keyboard is @ something strange happens.
The TextField widget remain in a custom state and all key pressed after that are interpreted as custom chars.
After that I try to use the direct ASCII 64 char press Alt and on numeric pad type 64 and than this exception is raised.

<details>
<summary>logs</summary>

```bash
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#672ba(logicalKey: LogicalKeyboardKey#7005c(keyId: "0x10007005c", keyLabel: "4",
debugName: "Numpad 4"), physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName:
"Alt Left")) and its data: Instance of 'RawKeyEventDataWindows'
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 624 pos 12: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:624:12)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:227:15)
#10     _invoke3 (dart:ui/hooks.dart:226:10)
#11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:520:7)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

**Comment by nt4f04uNd** [comment]
please provide minimal reproducible code sample, flutter doctor -v and details on which platform you experience this

**Comment by TahaTesser** [comment]
Hi @carmas123 
Are you experiencing this [issue](https://github.com/flutter/flutter/issues/75768)
If not, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample, including steps to test the issue
Thank you

**Comment by carmas123** [comment]
Hi @TahaTesser I make a simple flutter project to test this problem:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Container(),
          Container(
            constraints: BoxConstraints(maxWidth: 500),
            child: TextField(
              decoration: InputDecoration(hintText: "Simple"),
            ),
          ),
          SizedBox(height: 20),
          Container(
            constraints: BoxConstraints(maxWidth: 500),
            child: TextField(
              obscureText: true,
              decoration: InputDecoration(hintText: "Password"),
            ),
          ),
        ],
      ),
    );
  }
}

```

I've found the problem!!
The problem become when the user press the AltGr to create the @ char. On the italian keyboard the "@" is done with AltGr+ò .
After that the field does not restore the status, or better, after taht any char pressed on keyboard is modified like if the button remain pressed. To solve that if I press on the Ctrl key all return normal.

Sorry for my english, but if you need more information ask me again.

**Comment by TahaTesser** [comment]
Hi @carmas123 
I just reproduced using on-screen Italian, this is the same as https://github.com/flutter/flutter/issues/75768, which also returns to normal after pressing the control key

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
