### ISSUE TITLE
Install Flutter on Ubuntu 20.04

### ISSUE THREAD

**Issue by KingStoffen** [flutter/flutter#76951]
## Steps to Reproduce

1. Use Ubuntu, Install Flutter stable (1.22.6) from zip
2. Install the whole rest. (android, Java 8, android command line tools)
3. Add Paths: 
4. 

## Logs

Downloading Gradle Wrapper...                                       0.1s
/bin/tar: gradle/wrapper/gradle-wrapper.properties: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradle/wrapper/gradle-wrapper.jar: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradle/wrapper: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradle: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradlew: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradlew.bat: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: NOTICE: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: Exiting with failure status due to previous errors
Downloading Gradle Wrapper...                                       0.0s
/bin/tar: gradle/wrapper/gradle-wrapper.properties: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradle/wrapper/gradle-wrapper.jar: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradle/wrapper: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradle: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradlew: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: gradlew.bat: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: NOTICE: Cannot change ownership to uid 397546, gid 5000: Invalid argument
/bin/tar: Exiting with failure status due to previous errors

Oops; flutter has exited unexpectedly: "ProcessException: The command failed
  Command: tar -xzf /srv/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/gradle-wrapper/fd5c1f2c013565a3bea56ada6df9d2b8e96d56aa/gradle-wrapper.tgz -C
  /srv/flutter/bin/cache/artifacts/gradle_wrapper".
A crash report has been written to /srv/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/gradle-wrapper/flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+The+command+failed%0A++Command%3A+tar+-xzf+%2Fsrv%2Fflutter%2Fbin%2Fcache%2Fdownloads%2Fstorage.googleapis.com%2Fflutter_infra%2Fgradle-wrapper%2Ffd5c1f2c013565a3bea56ada6df9d2b8e96d56aa%2Fgradle-wrapper.tgz+-C+%2Fsrv%2Fflutter%2Fbin%2Fcache%2Fartifacts%2Fgradle_wrapper

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JtxBN

```
```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: The command failed
  Command: tar -xzf /srv/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/gradle-wrapper/fd5c1f2c013565a3bea56ada6df9d2b8e96d56aa/gradle-wrapper.tgz -C /srv/flutter/bin/cache/artifacts/gradle_wrapper

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:463:17)
#2      _PosixUtils.unpack (package:flutter_tools/src/base/os.dart:241:19)
#3      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1512:18)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale C)
    • Flutter version 1.22.6 at /srv/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by TahaTesser** [comment]
### From report

## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The command failed Command: tar, OS error code: 2
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:463:17)
#2      _PosixUtils.unpack (package:flutter_tools/src/base/os.dart:241:19)
#3      ArtifactUpdater._downloadArchive (package:flutter_tools/src/cache.dart:1512:18)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale C)
    • Flutter version 1.22.6 at /srv/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by budde377** [comment]
I've also encountered this on a CircleCI docker image. In my case, setting the environment variable 

```sh
TAR_OPTIONS=--no-same-owner
```

"solved" the problem.

This post lead me to the solution: https://discuss.circleci.com/t/tar-cannot-change-ownership/28766.

**Comment by christopherfujino** [comment]
> I've also encountered this on a CircleCI docker image. In my case, setting the environment variable
> 
> ```shell
> TAR_OPTIONS=--no-same-owner
> ```
> 
> "solved" the problem.
> 
> This post lead me to the solution: https://discuss.circleci.com/t/tar-cannot-change-ownership/28766.

Interesting. Per the manpage for gnu tar, `--no-same-owner` is the default for regular users, while `--same-owner` is the default for root. Explicitly providing `--no-same-owner` to the tool's invocation should be easy and safe.

@KingStoffen can you try providing the env var `TAR_OPTIONS=--no-same-owner` to confirm your particular use case is solved?

**Comment by KingStoffen** [comment]
Hello, sorry for my late response. It's a lot time and a lot of changes ago. I think the issue relates to my fault of installing and running flutter as root. I've solved this problem with a fresh Ubuntu installation and a dedicated flutter user. 
If nobody else ran into this problem I am going to close this ticket.
