### ISSUE TITLE
Cannot resolve AlignmentDirectional without a TextDirection

### ISSUE THREAD

**Issue by execmd** [flutter/flutter#76967]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              decoration: ShapeDecoration(
                gradient: RadialGradient(
                  focal: AlignmentDirectional(0, 1),
                  focalRadius: 5,
                  radius: 2,
                  colors: [Colors.red, Colors.black],
                  stops: [0.0, 0.4],
                ),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.all(Radius.circular(8.0)),
                ),
              ),
              child: Text(
                'BUG',
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
3. Create ShapeDecoration with RadialGradient. As I see, _ShapeDecorationPainter._precache method calling createShader without textDirection argument `      _interiorPaint!.shader = _decoration.gradient!.createShader(rect);` even when it is available. Looks like a bug, because other 2 places calls the same createShader method with textDirection argument:
route.dart `      ..shader = gradient.createShader(rect, textDirection: textDirection);`
box_decoration.dart `paint.shader = _decoration.gradient!.createShader(rect, textDirection: textDirection);`

For anyone who looking for immediate solution - create 
```dart
class FixedRadialGradient extends RadialGradient {
  const FixedRadialGradient({
    Alignment center = Alignment.center,
    double radius = 0.5,
    List<Color> colors,
    List<double> stops,
    TileMode tileMode = TileMode.clamp,
    focal,
    double focalRadius = 0.0,
    GradientTransform transform,
  }) : super(
            center: center,
            radius: radius,
            colors: colors,
            stops: stops,
            tileMode: tileMode,
            focal: focal,
            focalRadius: focalRadius);

  @override
  createShader(Rect rect, {TextDirection textDirection}) {
    return super
        .createShader(rect, textDirection: textDirection ?? TextDirection.ltr);
  }
}
```
and use FixedRadialGradient instead of RadialGradient.

**Expected results:** No exception.

**Actual results:** Exception (below)

<details>
  <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
Cannot resolve AlignmentDirectional without a TextDirection.
'package:flutter/src/painting/alignment.dart':
Failed assertion: line 529 pos 12: 'direction != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Container file:///Users/execmd/workplace/gradient-bug/bug/lib/main.dart:68:13
When the exception was thrown, this was the stack: 
#2      AlignmentDirectional.resolve (package:flutter/src/painting/alignment.dart:529:12)
#3      RadialGradient.createShader (package:flutter/src/painting/gradient.dart:678:38)
#4      _ShapeDecorationPainter._precache (package:flutter/src/painting/shape_decoration.dart:332:54)
#5      _ShapeDecorationPainter.paint (package:flutter/src/painting/shape_decoration.dart:387:5)
#6      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2083:17)
...
The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#0a648 relayoutBoundary=up3
...  parentData: offset=Offset(0.0, 389.5); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=Infinity)
...  size: Size(60.0, 33.0)
...  decoration: ShapeDecoration
...    gradient: RadialGradient(center, 1.0, [MaterialColor(primary value: Color(0xfff44336)), Color(0xff000000)], [0.0, 0.4], TileMode.clamp, AlignmentDirectional.bottomCenter, 0.2)
...    shape: RoundedRectangleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none), BorderRadius.circular(8.0))
...  configuration: ImageConfiguration(bundle: PlatformAssetBundle#f82af(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
RenderObject: RenderDecoratedBox#0a648 relayoutBoundary=up3
  parentData: offset=Offset(0.0, 389.5); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=Infinity)
  size: Size(60.0, 33.0)
  decoration: ShapeDecoration
    gradient: RadialGradient(center, 1.0, [MaterialColor(primary value: Color(0xfff44336)), Color(0xff000000)], [0.0, 0.4], TileMode.clamp, AlignmentDirectional.bottomCenter, 0.2)
    shape: RoundedRectangleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none), BorderRadius.circular(8.0))
  configuration: ImageConfiguration(bundle: PlatformAssetBundle#f82af(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...  child: RenderPadding#83cba relayoutBoundary=up4 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=Infinity)
...    size: Size(60.0, 33.0)
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderParagraph#73ad5 relayoutBoundary=up5 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=Infinity)
...      size: Size(60.0, 33.0)
...      textAlign: start
...      textDirection: ltr
...      softWrap: wrapping at box width
...      overflow: clip
...      textScaleFactor: 0.8
...      locale: en_US
...      maxLines: unlimited
...      text: TextSpan
...        debugLabel: (englishLike display1 2014).merge(blackCupertino headline4)
...        inherit: false
...        color: Color(0x8a000000)
...        family: .SF UI Display
...        size: 34.0
...        weight: 400
...        baseline: alphabetic
...        decoration: TextDecoration.none
...        "BUG"
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing bug...                                                        
No issues found! (ran in 8.5s)
```

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-LV)
    • Flutter version 1.22.6 at /Users/execmd/devtools/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/execmd/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[!] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • XXX (mobile) • 00000000-000910221E28002E • ios • iOS 14.4

! Doctor found issues in 1 category.

```

</details>

**Comment by pedromassangocode** [comment]
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
  home: MyHomePage(),
));

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              decoration: ShapeDecoration(
                gradient: RadialGradient(
                  focal: AlignmentDirectional(0, 1),
                  focalRadius: 5,
                  radius: 2,
                  colors: [Colors.red, Colors.black],
                  stops: [0.0, 0.4],
                ),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.all(Radius.circular(8.0)),
                ),
              ),
              child: Text('BUG',
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>


<details>
<summary>logs</summary>

```bash
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
Cannot resolve AlignmentDirectional without a TextDirection.
'package:flutter/src/painting/alignment.dart':
Failed assertion: line 529 pos 12: 'direction != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Container file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:15:13
When the exception was thrown, this was the stack: 
#2      AlignmentDirectional.resolve (package:flutter/src/painting/alignment.dart:529:12)
#3      RadialGradient.createShader (package:flutter/src/painting/gradient.dart:679:38)
#4      _ShapeDecorationPainter._precache (package:flutter/src/painting/shape_decoration.dart:332:54)
#5      _ShapeDecorationPainter.paint (package:flutter/src/painting/shape_decoration.dart:387:5)
#6      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2145:17)
...
The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#33e0b relayoutBoundary=up3
...  parentData: offset=Offset(0.0, 390.3); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...  size: Size(67.0, 40.0)
...  decoration: ShapeDecoration
...    gradient: RadialGradient(Alignment.center, 2.0, [MaterialColor(primary value: Color(0xfff44336)), Color(0xff000000)], [0.0, 0.4], TileMode.clamp, AlignmentDirectional.bottomCenter, 5.0)
...    shape: RoundedRectangleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none), BorderRadius.circular(8.0))
...  configuration: ImageConfiguration(bundle: PlatformAssetBundle#01418(), devicePixelRatio: 3.5, locale: en_US, textDirection: TextDirection.ltr, platform: android)
RenderObject: RenderDecoratedBox#33e0b relayoutBoundary=up3
  parentData: offset=Offset(0.0, 390.3); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
  size: Size(67.0, 40.0)
  decoration: ShapeDecoration
    gradient: RadialGradient(Alignment.center, 2.0, [MaterialColor(primary value: Color(0xfff44336)), Color(0xff000000)], [0.0, 0.4], TileMode.clamp, AlignmentDirectional.bottomCenter, 5.0)
    shape: RoundedRectangleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none), BorderRadius.circular(8.0))
  configuration: ImageConfiguration(bundle: PlatformAssetBundle#01418(), devicePixelRatio: 3.5, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...  child: RenderPadding#dc0a8 relayoutBoundary=up4 NEEDS-PAINT
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...    size: Size(67.0, 40.0)
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderParagraph#9212f relayoutBoundary=up5 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
...      size: Size(67.0, 40.0)
...      textAlign: start
...      textDirection: ltr
...      softWrap: wrapping at box width
...      overflow: clip
...      locale: en_US
...      maxLines: unlimited
...      text: TextSpan
...        debugLabel: (englishLike display1 2014).merge(blackMountainView headline4)
...        inherit: false
...        color: Color(0x8a000000)
...        family: Roboto
...        size: 34.0
...        weight: 400
...        baseline: alphabetic
...        decoration: TextDecoration.none
...        "BUG"
====================================================================================================
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.22.6 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.128, on macOS 11.2.1 20D74 darwin-x64, locale en-AO)
    • Flutter version 1.27.0-9.0.pre.128 at /Users/pedromassango/Code/flutter_master
    • Framework revision 199d5dc086 (8 hours ago), 2021-02-28 14:36:02 -0800
    • Engine revision 34236c9837
    • Dart version 2.13.0 (build 2.13.0-81.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>
