### ISSUE TITLE
got error while practicing

### ISSUE THREAD

**Issue by likhith117** [flutter/flutter#76975]
<details>
<summary>logs</summary>

```bash
Launching lib\main.dart on Android SDK built for x86 in debug mode...
 lib\main.dart
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:51274/_7hrERWIuG0=/ws
D/EGL_emulation( 7173): eglMakeCurrent: 0xe111a0c0: ver 3 0 (tinfo 0xe110f770)
D/eglCodecCommon( 7173): setVertexArrayObject: set vao to 0 (0) 1 0
I/OpenGLRenderer( 7173): Davey! duration=3460ms; Flags=1, IntendedVsync=5161766896483, Vsync=5161766896483, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=5161769630940, AnimationStart=5161769712040, PerformTraversalsStart=5161769761240, DrawStart=5163739425540, SyncQueued=5163744518640, SyncStart=5164092337240, IssueDrawCommandsStart=5164092649440, SwapBuffers=5165060726340, FrameCompleted=5165575205140, DequeueBufferDuration=381181000, QueueBufferDuration=14040000,
I/Choreographer( 7173): Skipped 228 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 7173): eglMakeCurrent: 0xf437ea40: ver 3 0 (tinfo 0xe119f440)
D/eglCodecCommon( 7173): setVertexArrayObject: set vao to 0 (0) 1 0

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown building IconTheme(color: Color(0xdd000000)):[39;49m
Could not find a generator for route RouteSettings("/", null) in the _WidgetsAppState.

[38;5;244mMake sure your root app widget has provided a way to generate[39;49m
[38;5;244mthis route.[39;49m
[38;5;244mGenerators for routes are searched for in the following order:[39;49m
 [38;5;244m1. For the "/" route, the "home" property, if non-null, is used.[39;49m
 [38;5;244m2. Otherwise, the "routes" table is used, if it has an entry for the route.[39;49m
 [38;5;244m3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not handled by "home" and "routes".[39;49m
 [38;5;244m4. Finally if all else fails onUnknownRoute is called.[39;49m
[38;5;244mUnfortunately, onUnknownRoute was not set.[39;49m
[38;5;244mThe relevant error-causing widget was[39;49m
[38;5;248mMaterialApp[39;49m
 lib\main.dart
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      _WidgetsAppState._onUnknownRoute.<anonymous closure>[39;49m
 package:flutter/…/widgets/app.dart
[38;5;244m#1      _WidgetsAppState._onUnknownRoute[39;49m
 package:flutter/…/widgets/app.dart
[38;5;244m#2      NavigatorState._routeNamed[39;49m
 package:flutter/…/widgets/navigator.dart
[38;5;244m#3      Navigator.defaultGenerateInitialRoutes[39;49m
 package:flutter/…/widgets/navigator.dart
[38;5;244m#4      NavigatorState.initState[39;49m
 package:flutter/…/widgets/navigator.dart
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4686 pos 12: 'child == _child': is not true.
[38;5;244mThe relevant error-causing widget was[39;49m
[38;5;248mMaterialApp[39;49m
 lib\main.dart
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
null: <inspected variable>
_active: true
_ancestorRenderObjectElement: null
_cachedHash: 2
_child: StatelessElement (MyApp)
_debugAllowIgnoredCallsToMarkNeedsBuild: false
_debugBuiltOnce: false
_debugDoingBuild: false
_debugForgottenChildrenWithGlobalKey: _HashSet ({})
_debugLifecycleState: _ElementLifecycle (_ElementLifecycle.active)
_dependencies: null
_depth: 1
_dirty: false
_hadUnsatisfiedDependencies: false
_inDirtyList: false
_inheritedWidgets: null
_newWidget: null
_owner: BuildOwner
_parent: null
_renderObject: RenderView (RenderView#aa726)
_slot: null
_widget: RenderObjectToWidgetAdapter ([root])
debugDoingBuild: false
depth: 1
dirty: false
hashCode: 2
owner: BuildOwner
renderObject: RenderView (RenderView#aa726)
runtimeType: Type (RenderObjectToWidgetElement<RenderBox>)
size: Unhandled exception:
Cannot get size from a render object that is not a RenderBox.
Instead of being a subtype of RenderBox, the render object associated with this element is a RenderView. If this type of render object does have a size, consider calling findRenderObject and extracting its size manually.
The size getter was called for the following element:
  [root]
The associated render object was: RenderView#aa726:
  debug mode enabled - android
  window size: Size(1080.0, 2148.0) (in physical pixels)
  device pixel ratio: 2.8 (physical pixels per logical pixel)
  configuration: Size(392.7, 781.1) at 2.8x (in logical pixels)
#0      Element.size.<anonymous closure> (package:flutter/src/widgets/framework.dart:3847:9)
#1      Element.size (package:flutter/src/widgets/framework.dart:3893:6)
#2      RenderObjectToWidgetElement.Eval (:0:1)
slot: null
widget: RenderObjectToWidgetAdapter ([root])
_location: _Location (file:///C:/Users/likhith/Downloads/flutter_windows_1.22.6-stable/flutter/packages/flutter/lib/src/widgets/binding.dart:970:26)
child: MyApp
container: RenderView (RenderView#aa726)
debugShortDescription: "[root]"
key: GlobalObjectKey ([GlobalObjectKey RenderView#aa726])
hashCode: 75950207
runtimeType: Type (RenderObjectToWidgetAdapter<RenderBox>)


```

</details>

**Comment by TahaTesser** [comment]
Hi @likhith117 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
