### ISSUE TITLE
TextField(s) in SingleChildScrollView cause 'too many elements' exception in integration tests

### ISSUE THREAD

**Issue by RomanKapshuk** [flutter/flutter#76981]
Assume we have a simple UI 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

/// SingleChildScrollView with TextField issue
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        key: Key('singleChildScrollView'),
        child: Column(
          children: [
            SizedBox(height: 20),
            Container(
              height: 200,
              width: double.infinity,
              color: Colors.red,
            ),
            SizedBox(height: 20),
            Container(
              height: 200,
              width: double.infinity,
              color: Colors.red,
            ),
            SizedBox(height: 20),
            Container(
              height: 100,
              width: double.infinity,
              color: Colors.red,
            ),
            SizedBox(height: 20),
            Container(
              key: Key('desiredContainer'),
              height: 100,
              width: double.infinity,
              color: Colors.yellow,
            ),
            TextField(),
          ],
        ),
      ),
    );
  }
}
```

We are trying to scroll to Container with key 'desiredContainer'. First of all, I tried to scrollUntilVisible like this

```
  testWidgets('Scroll until visible in SingleChildScrollView', (tester) async {
    app.main();
    await tester.pumpAndSettle();
    await tester.scrollUntilVisible(
      find.byKey(Key('desiredContainer')),
      50,
      scrollable: find.byKey(Key('singleChildScrollView')),
    );
  });
```

But I got:

```
The following _CastError was thrown running a test:
type 'SingleChildScrollView' is not a subtype of type
'Scrollable' in type cast

```

Then I looked "under the hood" of SingleChildScrollView, and changed scrollable finder to this 

```
  testWidgets('Scroll until visible in SingleChildScrollView', (tester) async {
    app.main();
    await tester.pumpAndSettle();
    await tester.scrollUntilVisible(
      find.byKey(Key('desiredContainer')),
      50,
      scrollable: find.descendant(
        of: find.byKey(Key('singleChildScrollView')),
        matching: find.byType(Scrollable),
      ),
    );
  });
```

Then I got 

```
I/flutter (27109): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (27109): The following StateError was thrown running a test:
I/flutter (27109): Bad state: Too many elements
I/flutter (27109): 
I/flutter (27109): When the exception was thrown, this was the stack:
I/flutter (27109): #0      Iterable.single (dart:core/iterable.dart:560:24)
I/flutter (27109): #1      WidgetController.widget (package:flutter_test/src/controller.dart:68:30)
I/flutter (27109): #2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:991:14)
I/flutter (27109): #5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
I/flutter (27109): #6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:989:27)
I/flutter (27109): #7      main.<anonymous closure> (file:///Users/r.kapshuk/AndroidStudioProjects/integration_test_issue/integration_test/foo_test.dart:22:18)
I/flutter (27109): <asynchronous suspension>
I/flutter (27109): #8      main.<anonymous closure> (file:///Users/r.kapshuk/AndroidStudioProjects/integration_test_issue/integration_test/foo_test.dart)
I/flutter (27109): #9      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
I/flutter (27109): <asynchronous suspension>
I/flutter (27109): #10     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
I/flutter (27109): #11     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
I/flutter (27109): <asynchronous suspension>
I/flutter (27109): #14     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
I/flutter (27109): #15     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1592:12)
I/flutter (27109): #16     IntegrationTestWidgetsFlutterBinding.runTest (package:integration_test/integration_test.dart:194:17)
I/flutter (27109): #17     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
I/flutter (27109): #18     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
I/flutter (27109): <asynchronous suspension>
I/flutter (27109): #19     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
I/flutter (27109): #24     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
I/flutter (27109): #25     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
I/flutter (27109): #30     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
I/flutter (27109): #31     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
I/flutter (27109): <asynchronous suspension>
I/flutter (27109): #32     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
I/flutter (27109): #37     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
I/flutter (27109): #38     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
I/flutter (27109): #39     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
I/flutter (27109): #46     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
I/flutter (27109): #47     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
I/flutter (27109): (elided 33 frames from dart:async and package:stack_trace)
I/flutter (27109): 
I/flutter (27109): The test description was:
I/flutter (27109):   Scroll until visible in SingleChildScrollView

```

But if I remove TextField all become fine. After a small investigation, I understood that "too many elements" exception caused because TextField uses Scrollable to achieve text scrolling.

So I had to change scrollable finder to this one:

```
  testWidgets('Scroll until visible in SingleChildScrollView', (tester) async {
    app.main();
    await tester.pumpAndSettle();
    await tester.scrollUntilVisible(
      find.byKey(Key('desiredContainer')),
      50,
      scrollable: find.descendant(
        of: find.byKey(Key('singleChildScrollView')),
        matching: find.byWidgetPredicate((widget) {

          if (widget is Scrollable) {
            return widget.restorationId == null;
        // return widget.axis == Axis.vertical; // We can do this only if TextField is not expandable (expand != true)
          }
          return false;
        }),
      ),
    );
  });

```

I don't really think this is correct way to find root scrollable. 

My flutter doctor -v:

![image](https://user-images.githubusercontent.com/16819254/109491539-57b18e00-7a92-11eb-8c85-3a621d0e2b7c.png)

**Comment by TahaTesser** [comment]
Hi @RomanKapshuk 
Thanks for filing the issue, I can reproduce it using `integration_test: ^1.0.2+2`


<details>
<summary>logs</summary>

```bash
tahatesser@Tahas-MacBook-Pro stable_flutter % flutterm drive  --driver=test_driver/integration_test.dart  --target=integration_test/example_test.dart
Running "flutter pub get" in stable_flutter...                   2,937ms
Multiple devices found:
SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.192
[1]: SM M025F (R9ZR205XX0A)
[2]: Taha’s iPad (00008020-000255113EE8402E)
[3]: macOS (macos)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        25.4s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4.8s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:53131/RoaSqDf1dcM=/
VMServiceFlutterDriver: Isolate found with number: 4258103973799523
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (27062): 00:00 +0: Scroll until visible in SingleChildScrollView
VMServiceFlutterDriver: Connected to Flutter application.
I/ViewRootImpl@eaa03a9[MainActivity](27062): Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)0
dur=11 res=0x1 s={true 3355961344} ch=false
I/flutter (27062): (The following exception is now available via WidgetTester.takeException:)
I/flutter (27062): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (27062): The following _CastError was thrown running a test:
I/flutter (27062): type 'SingleChildScrollView' is not a subtype of type 'Scrollable' in type cast
I/flutter (27062): 
I/flutter (27062): When the exception was thrown, this was the stack:
I/flutter (27062): #0      WidgetController.widget (package:flutter_test/src/controller.dart:67:44)
I/flutter (27062): #1      WidgetController.scrollUntilVisible.<anonymous closure>
(package:flutter_test/src/controller.dart:1139:15)
I/flutter (27062): #2      WidgetController.scrollUntilVisible.<anonymous closure>
(package:flutter_test/src/controller.dart:1137:39)
I/flutter (27062): #5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
I/flutter (27062): #6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
I/flutter (27062): #7      main.<anonymous closure>
(file:///Users/tahatesser/AndroidStudioProjects/stable_flutter/integration_test/sample_test.dart:10:18)
I/flutter (27062): <asynchronous suspension>
I/flutter (27062): <asynchronous suspension>
I/flutter (27062): (elided 3 frames from dart:async and package:stack_trace)
I/flutter (27062): 
I/flutter (27062): The test description was:
I/flutter (27062):   Scroll until visible in SingleChildScrollView
I/flutter (27062): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (27062): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the
above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens
first, and then the test will fail due to having not caught or expected the exception.)
I/flutter (27062): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (27062): The following _CastError was thrown running a test:
I/flutter (27062): type 'SingleChildScrollView' is not a subtype of type 'Scrollable' in type cast
I/flutter (27062): 
I/flutter (27062): When the exception was thrown, this was the stack:
I/flutter (27062): #0      WidgetController.widget (package:flutter_test/src/controller.dart:67:44)
I/flutter (27062): #1      WidgetController.scrollUntilVisible.<anonymous closure>
(package:flutter_test/src/controller.dart:1139:15)
I/flutter (27062): #2      WidgetController.scrollUntilVisible.<anonymous closure>
(package:flutter_test/src/controller.dart:1137:39)
I/flutter (27062): #5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
I/flutter (27062): #6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
I/flutter (27062): #7      main.<anonymous closure>
(file:///Users/tahatesser/AndroidStudioProjects/stable_flutter/integration_test/sample_test.dart:10:18)
I/flutter (27062): <asynchronous suspension>
I/flutter (27062): <asynchronous suspension>
I/flutter (27062): (elided 3 frames from dart:async and package:stack_trace)
I/flutter (27062): 
I/flutter (27062): The test description was:
I/flutter (27062):   Scroll until visible in SingleChildScrollView
I/flutter (27062): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (27062): 00:05 +0: Scroll until visible in SingleChildScrollView [E]
I/flutter (27062):   Test failed. See exception logs above.
I/flutter (27062):   The test description was: Scroll until visible in SingleChildScrollView
I/flutter (27062):   
I/flutter (27062): 00:05 +0 -1: (tearDownAll)
Failure Details:
Failure in method: Scroll until visible in SingleChildScrollView
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following _CastError was thrown running a test:
type 'SingleChildScrollView' is not a subtype of type
'Scrollable' in type cast

When the exception was thrown, this was the stack:
#0      WidgetController.widget (package:flutter_test/src/controller.dart:67:44)
#1      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
#5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
#7      main.<anonymous closure> (file:///Users/tahatesser/AndroidStudioProjects/stable_flutter/integration_test/sample_test.dart:10:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The test description was:
  Scroll until visible in SingleChildScrollView
═════════════════════════════════════════════════════════════════

end of failure 1



I/flutter (27062): 00:05 +1 -1: Some tests failed.
tahatesser@Tahas-MacBook-Pro stable_flutter % 
```

</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios         • iOS 14.4

! Doctor found issues in 1 category.

```

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.129, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-9.0.pre.129 at /Users/tahatesser/Code/flutter_master
    • Framework revision fc77610dd6 (6 hours ago), 2021-03-01 14:06:03 +0530
    • Engine revision 34236c9837
    • Dart version 2.13.0 (build 2.13.0-81.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

</details>

**Comment by huycozy** [comment]
This issue can produce on latest `stable` and `master` channel. Without `TextField`, the **test case 2** is passed

<details>
<summary>Sample code - test case 1</summary>

```dart
testWidgets('Scroll until visible in SingleChildScrollView', (tester) async {
    await tester.pumpWidget(const MyApp());
    await tester.pumpAndSettle();
    await tester.scrollUntilVisible(
      find.byKey(Key('desiredContainer')),
      50,
      scrollable: find.byKey(Key('singleChildScrollView')),
    );
  });
```

</details>

<details>
<summary>Log test case 1</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _CastError was thrown running a test:
type 'SingleChildScrollView' is not a subtype of type 'Scrollable' in type cast

When the exception was thrown, this was the stack:
#0      WidgetController.widget (package:flutter_test/src/controller.dart:69:44)
#1      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1237:15)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1235:39)
#5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1235:27)
#7      main.<anonymous closure> (file:///Users/huynq/Documents/WIP/reproduce_issues/test/widget_test.dart:35:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)
```

</details>


<details>
<summary>Sample code - test case 2</summary>

```dart
testWidgets('Scroll until visible in SingleChildScrollView', (tester) async {
    await tester.pumpWidget(const MyApp());
    await tester.pumpAndSettle();
    await tester.scrollUntilVisible(
      find.byKey(Key('desiredContainer')),
      50,
      scrollable: find.descendant(
        of: find.byKey(Key('singleChildScrollView')),
        matching: find.byType(Scrollable),
      ),
    );
  });
```

</details>

<details>
<summary>Log test case 2</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: Too many elements

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:656:24)
#1      WidgetController.widget (package:flutter_test/src/controller.dart:69:30)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1237:15)
#3      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1235:39)
#6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#7      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1235:27)
#8      main.<anonymous closure> (file:///Users/huynq/Documents/WIP/reproduce_issues/test/widget_test.dart:41:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.10.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (2 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 2.13.0-0.0.pre.908, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.13.0-0.0.pre.908 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 666a5c9078 (13 minutes ago), 2022-05-05 01:44:08 -0400
    • Engine revision 327be3c357
    • Dart version 2.18.0 (build 2.18.0-84.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 5F5D609C-3B0B-4C48-872C-961928157361 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by semsturgut** [comment]
Same here ✌️

**Comment by Merrit** [comment]
Excellent, thank you @Ahmed-Omar-Hommir.

Had to give my SingleChildScrollView that key (`Key('singleChildScrollView')`) and this worked perfectly. 💙
