### ISSUE TITLE
All Engine roll LUCI presubmit jobs queuing for 19+ hours

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#76991]
https://github.com/flutter/flutter/pull/76956

**Comment by christopherfujino** [comment]
Looks to me like these never got scheduled https://ci.chromium.org/p/flutter/builders/try/Linux%20analyze

**Comment by godofredoc** [comment]
Starting on 02/27 at 08:16 PST the handler to update the build status started failing with:

```

2021-02-27 08:16:48.526 PST
Available tags: [build_address:luci.flutter.try/Linux Arm Host Engine/1943, builder:Linux Arm Host Engine, buildset:pr/git/24683, buildset:sha/git/97446127fb8a36b49597945839863e215ed533a7, github_link:https://github.com/flutter/engine/pull/24683, swarming_hostname:chromium-swarm.appspot.com, swarming_tag:log_location:logdog://logs.chromium.org/flutter/buildbucket/cr-buildbucket.appspot.com/8854127956672830000/+/annotations, swarming_tag:luci_project:flutter, swarming_tag:os:Debian, swarming_tag:recipe_name:engine/engine_arm, swarming_tag:recipe_package:flutter/recipe_bundles/flutter.googlesource.com/recipes, swarming_task_id:51fd18996cd33410, user_agent:flutter-cocoon]
2021-02-27 08:16:48.526 PST
Setting status: {build: Instance of 'Build', hostname: cr-buildbucket.appspot.com, user_data: {"repo_owner":"flutter","repo_name":"engine","user_agent":"flutter-cocoon","check_run_id":1994602313}} for Linux Arm Host Engine
2021-02-27 08:16:48.781 PST
GitHub Error: Requested Resource was Not Found
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:400:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      GitHub.requestJson (package:github/src/common/github.dart:268:22)
<asynchronous suspension>
#3      GithubChecksService.updateCheckStatus (package:cocoon_service/src/service/github_checks_service.dart:116:38)
<asynchronous suspension>
#4      LuciStatusHandler.post (package:cocoon_service/src/request_handlers/luci_status.dart:99:7)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#6      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:134:9)
<asynchronous suspension>
```

**Comment by godofredoc** [comment]
It seems to have been resolved at 02/28 at 19:53 PST. This was a problem with the github APIs.

Do we have rolls started today with the same issue?

**Comment by zanderso** [comment]
I have not checked. Should we close the current roll and kick off a new one?

**Comment by zanderso** [comment]
I closed the current roll, and will keep an eye on the new one.

**Comment by godofredoc** [comment]
Perfect, I'll take a look too.

**Comment by zanderso** [comment]
New roll is here https://github.com/flutter/flutter/pull/76995

**Comment by yusufm** [comment]
Leaving this issue open to track possible solutions to handling github api outages, which would produce these symptoms. Possible solution is to have us retry with backoff.

**Comment by CaseyHillers** [comment]
Duplicating this against https://github.com/flutter/flutter/issues/86383. We've enabled the ci.yaml check to ensure builds are scheduled.
