### ISSUE TITLE
Semantics crash - !owner._nodes.containsKey(id)': is not true.

### ISSUE THREAD

**Issue by Sasikumar3595** [flutter/flutter#77036]
## Steps to Reproduce

I was created the custom widget to arrange children based on row and column count and also i was handled the semantics on custom render object. Semantics makes crash while place the custom widget inside the list view.

```

class _CustomContainer extends Stack {
  _CustomContainer({List<Widget> children, this.width, this.height})
      : super(children: children);
  final double width;
  final double height;

  @override
  RenderStack createRenderObject(BuildContext context) {
    final Directionality widget =
        context.dependOnInheritedWidgetOfExactType<Directionality>();
    return _CustomContainerRenderObject(width, height,
        direction: widget != null ? widget.textDirection : null);
  }

  @override
  void updateRenderObject(BuildContext context, RenderStack renderObject) {
    super.updateRenderObject(context, renderObject);
    if (renderObject is _CustomContainerRenderObject) {
      final Directionality widget =
          context.dependOnInheritedWidgetOfExactType<Directionality>();
      renderObject
        ..width = width
        ..height = height
        ..textDirection = widget != null ? widget.textDirection : null;
    }
  }
}

class _CustomContainerRenderObject extends RenderStack {
  _CustomContainerRenderObject(this._width, this._height,
      {TextDirection direction})
      : super(textDirection: direction);

  double get width => _width;

  set width(double value) {
    if (_width == value) {
      return;
    }

    _width = value;
    markNeedsLayout();
  }

  double _width;
  double _height;

  double get height => _height;

  set height(double value) {
    if (_height == value) {
      return;
    }

    _height = value;
    markNeedsLayout();
  }

  @override
  void performLayout() {
    super.performLayout();
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    paintStack(context, offset);
  }

  @override
  void describeSemanticsConfiguration(SemanticsConfiguration config) {
    super.describeSemanticsConfiguration(config);
    config.isSemanticBoundary = true;
  }

  @override
  void assembleSemanticsNode(
    SemanticsNode node,
    SemanticsConfiguration config,
    Iterable<SemanticsNode> children,
  ) {
    final List<CustomPainterSemantics> semantics = _semanticsBuilder(size);
    final List<SemanticsNode> semanticsNodes = <SemanticsNode>[];
    for (int i = 0; i < semantics.length; i++) {
      final CustomPainterSemantics currentSemantics = semantics[i];
      final SemanticsNode newChild = SemanticsNode(key: currentSemantics.key);

      final SemanticsProperties properties = currentSemantics.properties;
      final SemanticsConfiguration config = SemanticsConfiguration();
      if (properties.label != null) {
        config.label = properties.label;
      }
      if (properties.textDirection != null) {
        config.textDirection = properties.textDirection;
      }

      newChild.updateWith(
        config: config,
        childrenInInversePaintOrder: const <SemanticsNode>[],
      );

      newChild
        ..rect = currentSemantics.rect
        ..transform = currentSemantics.transform
        ..tags = currentSemantics.tags;

      semanticsNodes.add(newChild);
    }

    final List<SemanticsNode> finalChildren = <SemanticsNode>[];
    finalChildren.addAll(semanticsNodes);
    finalChildren.addAll(children);
    super.assembleSemanticsNode(node, config, finalChildren);
  }

  SemanticsBuilderCallback get _semanticsBuilder {
    final List<CustomPainterSemantics> semanticsBuilder =
        <CustomPainterSemantics>[];
    double left = 0, top = 0;
    final double cellWidth = size.width / 10;
    final double cellHeight = size.height / 10;
    for (int i = 0; i < 100; i++) {
      semanticsBuilder.add(CustomPainterSemantics(
        rect: Rect.fromLTWH(left, top, cellWidth, cellHeight),
        properties: SemanticsProperties(
          label: i.toString(),
          textDirection: TextDirection.ltr,
        ),
      ));

      left += cellWidth;
      if (left + 1 >= size.width) {
        top += cellHeight;
        left = 0;
      }
    }

    return (Size size) {
      return semanticsBuilder;
    };
  }
}

```

**Sample:**

```

@override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return Scaffold(
        appBar: AppBar(),
        body: SafeArea(
            child: ListView(shrinkWrap: true, children: [
          Container(
              child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                Container(
                  child: ListView.builder(
                    itemCount: 100,
                    itemBuilder: (BuildContext context, int index) {
                      List<Widget> children = <Widget>[];
                      double left = 0, top = 20;
                      final double cellWidth = constraints.maxWidth / 10;
                      final double cellHeight = 20;
                      children.add(Positioned(
                          left: 0,
                          top: 0,
                          right: 0,
                          height: cellHeight,
                          child: Text(
                            'Item Header' + index.toString(),
                            style: TextStyle(fontWeight: FontWeight.w700),
                          )));
                      for (int i = 0; i < 100; i++) {
                        children.add(Positioned(
                            left: left,
                            top: top,
                            width: cellWidth,
                            height: cellHeight,
                            child: Text(i.toString())));
                        left += cellWidth;
                        if (left + 1 >= constraints.maxWidth) {
                          top += cellHeight;
                          left = 0;
                        }
                      }

                      return Container(
                          height: 220,
                          child: _CustomContainer(
                            height: 220,
                            width: constraints.maxWidth,
                            children: children,
                          )
                        );
                    },
                  ),
                  height: 600,
                )
              ]))
        ])),
      );
    });
  }

```

1. Run the above added code on sample.
2. Enable accessibility in your android device.
3. Swipe to scroll continuously items from 1 - 50 and again scroll from 50 - 1 and again scroll to 1 -50.
4. Issue was reproduced due to '_maxFrameworkAccessibilityIdentifier' in semantics class because _generateNewId method generate the id value is 0, 1, 2 ... after _maxFrameworkAccessibilityIdentifier value so the nodes containsKey(id) assert return exception.

**Replication Video:**  

https://user-images.githubusercontent.com/44917578/109600989-20031e80-7b44-11eb-9630-6703d1955f25.mov

**Expected results:** 

Run the sample without exception when accessibility enabled.

**Actual results:** 

Sample makes exception when accessibility enabled.

<details>
  <summary>Crash</summary>

```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1532 pos 12: '!owner._nodes.containsKey(id)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsNode.attach (package:flutter/src/semantics/semantics.dart:1532:12)
#3      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:132:13)
#4      SemanticsNode._replaceChildren (package:flutter/src/semantics/semantics.dart:1460:9)
#5      SemanticsNode.updateWith (package:flutter/src/semantics/semantics.dart:1891:5)
#6      RenderObject.assembleSemanticsNode (package:flutter/src/rendering/object.dart:2782:10)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

**Comment by darshankawar** [comment]
Verified and replicable on latest master.

<details>
<summary>crash log</summary>

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1530 pos 12: '!owner._nodes.containsKey(id)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsNode.attach (package:flutter/src/semantics/semantics.dart:1530:12)
#3      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:138:13)
#4      SemanticsNode._replaceChildren (package:flutter/src/semantics/semantics.dart:1458:9)
#5      SemanticsNode.updateWith (package:flutter/src/semantics/semantics.dart:1889:5)
#6      RenderObject.assembleSemanticsNode (package:flutter/src/rendering/object.dart:2789:10)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 1530 pos 12: '!owner._nodes.containsKey(id)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsNode.attach (package:flutter/src/semantics/semantics.dart:1530:12)
#3      SemanticsNode.attach (package:flutter/src/semantics/semantics.dart:1539:15)
#4      SemanticsNode.attach (package:flutter/src/semantics/semantics.dart:1539:15)
#5      AbstractNode.adoptChild (package:flutter/src/foundation/node.dart:138:13)
#6      SemanticsNode._replaceChildren (package:flutter/src/semantics/semantics.dart:1458:9)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
'package:flutter/src/foundation/node.dart': Failed assertion: line 150 pos 12: 'child.attached == attached': is not true.
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2641 pos 14: 'node.parent?._dirty != true': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2641:14)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:468:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2641 pos 14: 'node.parent?._dirty != true': is not true.
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2641 pos 14: 'node.parent?._dirty != true': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2641:14)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:468:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2641 pos 14: 'node.parent?._dirty != true': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2641:14)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:468:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2641 pos 14: 'node.parent?._dirty != true': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2641:14)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:468:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2641 pos 14: 'node.parent?._dirty != true': is not true.
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2641 pos 14: 'node.parent?._dirty != true': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2641:14)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:468:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
...
====================================================================================================

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-9.0.pre.149, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 1.27.0-9.0.pre.149 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9964e8fe38 (5 hours ago), 2021-03-01 23:00:02 -0500
    • Engine revision 17f6bfc480
    • Dart version 2.13.0 (build 2.13.0-90.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.


```

</details>

**Comment by chunhtai** [comment]
The Semantics node id overflows, you can try to cache the semantics node so that the id will not grow so fast.

For example something like this should delay the overflow quite a bit
<details>
<summary> code </summary>
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Expansion Tile Splash'),
          centerTitle: true,
        ),
        body: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
              return Scaffold(
                appBar: AppBar(),
                body: SafeArea(
                    child: ListView(shrinkWrap: true, children: [
                      Container(
                          child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  child: ListView.builder(
                                    itemCount: 100,
                                    itemBuilder: (BuildContext context, int index) {
                                      List<Widget> children = <Widget>[];
                                      double left = 0, top = 20;
                                      final double cellWidth = constraints.maxWidth / 10;
                                      final double cellHeight = 20;
                                      children.add(Positioned(
                                          left: 0,
                                          top: 0,
                                          right: 0,
                                          height: cellHeight,
                                          child: Text(
                                            'Item Header' + index.toString(),
                                            style: TextStyle(fontWeight: FontWeight.w700),
                                          )));
                                      for (int i = 0; i < 100; i++) {
                                        children.add(Positioned(
                                            left: left,
                                            top: top,
                                            width: cellWidth,
                                            height: cellHeight,
                                            child: Text(i.toString())));
                                        left += cellWidth;
                                        if (left + 1 >= constraints.maxWidth) {
                                          top += cellHeight;
                                          left = 0;
                                        }
                                      }

                                      return Container(
                                          height: 220,
                                          child: _CustomContainer(
                                            height: 220,
                                            width: constraints.maxWidth,
                                            children: children,
                                          )
                                      );
                                    },
                                  ),
                                  height: 600,
                                )
                              ]))
                    ])),
              );
            }),
      ),
    ),
  );
}

class _CustomContainer extends Stack {
  _CustomContainer({List<Widget> children, this.width, this.height})
      : super(children: children);
  final double width;
  final double height;

  @override
  RenderStack createRenderObject(BuildContext context) {
    final Directionality widget =
    context.dependOnInheritedWidgetOfExactType<Directionality>();
    return _CustomContainerRenderObject(width, height,
        direction: widget != null ? widget.textDirection : null);
  }

  @override
  void updateRenderObject(BuildContext context, RenderStack renderObject) {
    super.updateRenderObject(context, renderObject);
    if (renderObject is _CustomContainerRenderObject) {
      final Directionality widget =
      context.dependOnInheritedWidgetOfExactType<Directionality>();
      renderObject
        ..width = width
        ..height = height
        ..textDirection = widget != null ? widget.textDirection : null;
    }
  }
}

class _CustomContainerRenderObject extends RenderStack {
  _CustomContainerRenderObject(this._width, this._height,
      {TextDirection direction})
      : super(textDirection: direction);

  double get width => _width;

  set width(double value) {
    if (_width == value) {
      return;
    }

    _width = value;
    markNeedsLayout();
  }

  double _width;
  double _height;

  double get height => _height;

  set height(double value) {
    if (_height == value) {
      return;
    }

    _height = value;
    markNeedsLayout();
  }

  @override
  void performLayout() {
    super.performLayout();
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    paintStack(context, offset);
  }

  @override
  void describeSemanticsConfiguration(SemanticsConfiguration config) {
    super.describeSemanticsConfiguration(config);
    config.isSemanticBoundary = true;
  }

  List<SemanticsNode> caches = <SemanticsNode>[];
  @override
  void assembleSemanticsNode(
      SemanticsNode node,
      SemanticsConfiguration config,
      Iterable<SemanticsNode> children,
      ) {
    final List<CustomPainterSemantics> semantics = _semanticsBuilder(size);
    final List<SemanticsNode> semanticsNodes = <SemanticsNode>[];
    for (int i = 0; i < semantics.length; i++) {
      final CustomPainterSemantics currentSemantics = semantics[i];
      final SemanticsNode newChild = i < caches.length? caches[i] : SemanticsNode(key: currentSemantics.key);
      final SemanticsProperties properties = currentSemantics.properties;
      final SemanticsConfiguration config = SemanticsConfiguration();
      if (properties.label != null) {
        config.label = properties.label;
      }
      if (properties.textDirection != null) {
        config.textDirection = properties.textDirection;
      }

      newChild.updateWith(
        config: config,
        childrenInInversePaintOrder: const <SemanticsNode>[],
      );

      newChild
        ..rect = currentSemantics.rect
        ..transform = currentSemantics.transform
        ..tags = currentSemantics.tags;

      semanticsNodes.add(newChild);
    }

    final List<SemanticsNode> finalChildren = <SemanticsNode>[];
    finalChildren.addAll(semanticsNodes);
    finalChildren.addAll(children);
    caches = semanticsNodes.toList();
    super.assembleSemanticsNode(node, config, finalChildren);
  }

  SemanticsBuilderCallback get _semanticsBuilder {
    final List<CustomPainterSemantics> semanticsBuilder =
    <CustomPainterSemantics>[];
    double left = 0, top = 0;
    final double cellWidth = size.width / 10;
    final double cellHeight = size.height / 10;
    for (int i = 0; i < 100; i++) {
      semanticsBuilder.add(CustomPainterSemantics(
        rect: Rect.fromLTWH(left, top, cellWidth, cellHeight),
        properties: SemanticsProperties(
          label: i.toString(),
          textDirection: TextDirection.ltr,
        ),
      ));

      left += cellWidth;
      if (left + 1 >= size.width) {
        top += cellHeight;
        left = 0;
      }
    }

    return (Size size) {
      return semanticsBuilder;
    };
  }
}

```
</details>
