### ISSUE TITLE
[shared_preferences] 2.0.3 throws a lot of Java Tracebacks on Android

### ISSUE THREAD

**Issue by kaladron** [flutter/flutter#77155]
The Shared Prefs package works for a little bit and then starts throwing errors.  I did not see these errors in 2.0.1.  From the trace it looks like the new Threadpool implementation is the likely cause.

```
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): java.util.concurrent.RejectedExecutionException: Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@7526d87 rejected from java.util.concurrent.ThreadPoolExecutor@6da90b2[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 25]
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.commitAsync(MethodCallHandlerImpl.java:137)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:100)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at android.os.Looper.loopOnce(Looper.java:161)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at android.app.ActivityThread.main(ActivityThread.java:7892)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#plugins.flutter.io/shared_preferences(18687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991)
E/flutter (18687): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@7526d87 rejected from java.util.concurrent.ThreadPoolExecutor@6da90b2[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 25], null, java.util.concurrent.RejectedExecutionException: Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@7526d87 rejected from java.util.concurrent.ThreadPoolExecutor@6da90b2[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 25]
E/flutter (18687): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/flutter (18687): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/flutter (18687): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/flutter (18687): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.commitAsync(MethodCallHandlerImpl.java:137)
E/flutter (18687): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:100)
E/flutter (18687): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (18687): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (18687): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (18687): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (18687): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (18687): 	at android.os.Looper.loopOnce(Looper.java:161)
E/flutter (18687): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (18687): 	at android.app.ActivityThread.main(ActivityThread.java:7892)
E/flutter (18687): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18687): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (18687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991)
E/flutter (18687): )
E/flutter (18687): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:581
E/flutter (18687): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter (18687): <asynchronous suspension>
E/flutter (18687): #2      MethodChannelSharedPreferencesStore.setValue
package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:30
E/flutter (18687): <asynchronous suspension>
E/flutter (18687):
```

**Comment by kaladron** [comment]
It worked several times in a row and then stopped after a bit.  I'm out of time this morning for debugging, but I think this is a cumulative failure rather than one you'll see right away.

**Comment by cranst0n** [comment]
Can confirm what you're seeing. Downgrading to 2.0.1 resolves for me as well.

**Comment by darshankawar** [comment]
@kaladron 
Tried the official plugin [example](https://pub.dev/packages/shared_preferences/example) on latest stable (2.0.0) and played around a bit, but didn't come across the issue.
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 60bd88df91 (14 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

**Comment by kaladron** [comment]
I'll try, but like the rest of us, it's perf time :). Might be a few days.

**Comment by impure** [comment]
I also had this issue. It happens when you try to save two things at the same time like this:
```
void saveStuff() {
  prefs.setInt("a", 1);
  prefs.setInt("b", 2);
}
```
You can fix it by awaiting each task so they don't run at the same time:
```
Future<void> saveStuff() async {
  await prefs.setInt("a", 1);
  await prefs.setInt("b", 2);
}
```

**Comment by kaladron** [comment]
Ah, that would make sense.  I'm almost always bouncing values between two StringLists, so doing two of these at once (and doing them every few seconds, if rate limiting is important)

**Comment by cranst0n** [comment]
@impure suggestion seems to have resolved this for me as well. Thanks!

**Comment by AhmedNourJamalElDin** [comment]
+1

**Comment by KDCinfo** [comment]
> You can fix it by awaiting each task so they don't run at the same time:
> 
> ```
> Future<void> saveStuff() async {
>   await prefs.setInt("a", 1);
>   await prefs.setInt("b", 2);
> }
> ```

All my calls already have `await`, and downgrading to `2.0.1` or `2.0.0` didn't help. 

**However, I could not recreate the issue after a dozen attempts after downgrading back to `0.5.12+4`.**

- I then went back up to `2.0.3` and it errored on the 4th try.
- Went back down to `0.5.12+4`, tried it two dozen times with no issues.
- I went back up to `2.0.3` and tested a dozen more times---it errors mostly after 2nd round, but sometimes after 1, and every few times after 4.
- Also, mentioned at the bottom, it also (appears to) intermittently crash the app (or something else does, and it's coincidental).
- Per my code below, when it does error, it almost always errors on the first `await` (is_ascending), but I've seen it error once on the 3rd (column_order).

To recreate my issue, I log out of my app, log back in, log out, and when I log back in the second time (or anywhere from 1-4 times), it starts throwing the Exceptions. After logging in, my app is setting some preferences from a web API call.
```
// List<dynamic> prefRow
try {
  bool test1 = prefRow[0]["is_ascending"] == "1" ? true : false;
  int test2 = int.parse(prefRow[0]["sort_column"]);
  String test3 = prefRow[0]["column_order"];
  bool test4 = prefRow[0]["show_price"] == "1" ? true : false;
  bool test5 = prefRow[0]["show_volume"] == "1" ? true : false;

  await prefsSetBool(key: 'isAscending', value: test1); // After login, it will Throw one or more of these.
  await prefsSetInt(key: 'sortColumn', value: test2);  // I'm uncertain how many (maybe just one?) 
  await prefsSetString(key: 'columnOrder', value: test3); // because although I put a stop on each line,
  await prefsSetBool(key: 'showPrice', value: test4); // the debugger jumps through 3 errors, and the key 
  await prefsSetBool(key: 'showVolume', value: test5); // and values are only populated on the third jump.
} catch (err) {
  print("Error...");
}
```
Example method call:
```
SharedPreferences servicePrefs = await SharedPreferences.getInstance();

  Future<void> prefsSetBool({@required String key, @required bool value}) async {
    try {
      await servicePrefs.setBool(key, value);
    } catch (err) {
      print("Error... [prefsSetBool]");
    }
  }
```
Error:
```
E/MethodChannel#plugins.flutter.io/shared_preferences(19935): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(19935): java.util.concurrent.RejectedExecutionException: Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@2bb7047 rejected from java.util.concurrent.ThreadPoolExecutor@836c581[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 42]
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.commitAsync(MethodCallHandlerImpl.java:137)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:66)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/shared_preferences(19935):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
Also, sometimes it recovers, and other times it kills/terminates the entire app (`Exited (sigterm)`). But I'm not 100% sure that it is related to the above error, although it didn't happen when I downgraded. The termination error, below, however, gives me no clues in the debugger or via `print()`s. It also happened once on log out, which is also why I'm not sure if it's related. 
```
F/libc    (15034): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 15062 (1.ui), pid 15034 (app_name)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: '...'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-03-08 17:49:44-0800
pid: 15034, tid: 15062, name: 1.ui  >>> com.xxx.app_name <<<
uid: 10234
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  000000717bee3730  x3  000000717bee3740
    x4  000000717bee3700  x5  000000717bee3650  x6  000000717bee36d0  x7  77636c6b6a62ff77
    x8  0000000000000000  x9  000000718d4fb618  x10 000000718d61a668  x11 000000000000001a
    x12 00000000004b0304  x13 0000000000000001  x14 0000007277b8b40a  x15 0000000000000000
    x16 000000718d54c000  x17 0000007277b83ee8  x18 00000071888a8000  x19 0000007189994538
    x20 0000007189994188  x21 0000000000000000  x22 0000000000000000  x23 00000071899941a8
    x24 0000007189994190  x25 000000717bee3550  x26 000000717d562800  x27 00000071e4370940
    x28 0000000000000000  x29 000000000000003d
    sp  0000007189994120  lr  000000718d1e5a38  pc  000000718d1e5a3c
backtrace:
      #00 pc 000000000174ca3c  /data/app/com.domain.app_name-QQXq_ELpC5_Qw2sSdj2bGf==/lib/arm64/libflutter.so (BuildId: 4f453a1bb64d1244a9dd8bd68e926b4779043b43)
      #01 pc 00000000004e36fc  [anon:libc_malloc]
Lost connection to device.
Exited (sigterm)
```
I'm still a Flutter/mobile noob just trying to finish my first architected app, so usually find these things were something I did or didn't do in my flow.

**Comment by olerich** [comment]
The fix by @impure works for me but if i.e. multiple callbacks from api requests access sharedpreferences there is no way to await calls between the callbacks. 

The problem seems to be introduced in [this commit](https://github.com/flutter/plugins/commit/73aefe620202349b56a9c4e7487580657b299596#diff-a892bd15f83c87d6cb8d90316c453d9e210deda49bd7d5375d68869fd82790e3) which uses a Thread pool of size 1, so posting to this thread pool if a thread is already running will cause the exception. A possible solution would be to queue the calls on the android side, since it has to be a single thread pool because multiple threads accessing shared preferences in android will lead to shared preferences being dropped completely.

**Comment by darshankawar** [comment]
@olerich @KDCinfo Can anyone of you provide a reproducible use case that shows this stacktrace ?

**Comment by KDCinfo** [comment]
@darshankawar I should be able to if you can provide me the steps (just copy the entire stacktrace verbatim from VSC?), and let me know which version you'd like the trace on.

**Comment by KDCinfo** [comment]
For the version, I'm going to assume you'd want the latest version, (or any version that helps you track down what's happening). Poor question. Sorry. I went with `2.0.3`.

For the stack trace, VS Code doesn't tell very much (I was expecting a mountain of data). Pasting it below. Is there a way to gain a larger trace when the Exception is caught?

Thanks!
```
StandardMethodCodec.decodeEnvelope (d:\src\flutter\packages\flutter\lib\src\services\message_codecs.dart:581)
MethodChannel._invokeMethod (d:\src\flutter\packages\flutter\lib\src\services\platform_channel.dart:158)
<asynchronous gap> (Unknown Source:0)
MethodChannelSharedPreferencesStore.setValue (d:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_platform_interface-2.0.0\lib\method_channel_shared_preferences.dart:30)
<asynchronous gap> (Unknown Source:0)
StorageServiceImpl.prefsSetBool (d:\src\projects\kdrecall\hungry\lib\services\storage\storage_service_implementation.dart:52)
<asynchronous gap> (Unknown Source:0)
StorageServiceImpl.corePrefsArrayToStorage (d:\src\projects\kdrecall\hungry\lib\services\storage\storage_service_implementation.dart:176)
<asynchronous gap> (Unknown Source:0)
```

**Comment by stuartmorgan** [comment]
Taking since @blasten won't be able to look at this for a while.

**Comment by zaidrix** [comment]
> * Went back down to `0.5.12+4`, tried it two dozen times with no issues.

I have the same issue and I can't switch back to (0.5.12+4) because it not compatible with a lot of the other updated dependancies.

-   firebase_auth: ^1.0.0
-   cloud_firestore: ^1.0.0
-   firebase_storage: ^8.0.0
-   firebase_messaging: ^9.0.0
-   permission_handler: ^6.0.0
-   image_picker: ^0.7.2
-   cached_network_image: ^3.0.0-nullsafety
-   **shared_preferences: ^2.0.3**
-   font_awesome_flutter: ^8.11.0
-   google_maps_flutter: ^2.0.1
-   clipboard: ^0.1.2+8
-   timeago: ^3.0.1
-   url_launcher: ^6.0.2
-   shimmer: ^1.1.2
-   flutter_rating_bar: ^4.0.0
-   package_info: ^2.0.0
-   flutter_email_sender: ^5.0.0
-   geolocator: ^7.0.1

**Comment by KDCinfo** [comment]
My bad on testing. I neglected to remove the caret `^`. :o Can confirm `shared_preferences: 2.0.2` breaks, but I cannot now break `shared_preferences: 2.0.1` (without the caret). Have tried two dozen times. `2.0.1` appears to work for me, as it does others.

**Comment by s3ppo** [comment]
i have the same issue... 2.0.3 crashes everything..

but i also can confirm that ```shared_preferences: ^2.0.1``` is not working, but ```shared_preferences: 2.0.1``` is working
