### ISSUE TITLE
Retain navigation stack between tests in integration_test

### ISSUE THREAD

**Issue by RomanKapshuk** [flutter/flutter#77151]
How to retain navigation state between testWidgets? After navigation to my second screen and pump/run in tests all screens that have been opened in previous tests just close

Example

main.dart:
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          child: FlatButton(
        key: Key('button_navigate_to_second_screen'),
        child: Text('Navigate to second screen'),
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (context) => SecondScreen()),
          );
        },
      )),
    );
  }
}


class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          'Second screen text',
          key: Key('desired_key'),
        ),
      ),
    );
  }
}
```

foo_test.dart
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:integration_test_issue/main.dart' as app;

main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  Widget appWidget;
  testWidgets('Navigate to second screen', (tester) async {
    app.main();
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(Key('button_navigate_to_second_screen')));
    await tester.pumpAndSettle();
  });

  testWidgets('Find text', (tester) async {
    app.main();
    await tester.pumpAndSettle(); // <-- After this pump we returns to MyHomePage
    await Future.delayed(Duration(seconds: 5));
    expect(
      find.byKey(Key('desired_key')),
      findsOneWidget,
    );
  });

}
```

Is there a way to separate tests between several testWidget?

**Comment by darshankawar** [comment]
Verified and replicable on latest stable (2.0.0).

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.0, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 60bd88df91 (14 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.


```

</details>

<details>
<summary>error log</summary>

```
VMServiceFlutterDriver: Connected to Flutter application.
I/flutter (24813): 00:04 +1: Find text
I/flutter (24813): (The following exception is now available via WidgetTester.takeException:)
I/flutter (24813): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (24813): The following TestFailure object was thrown running a test:
I/flutter (24813):   Expected: exactly one matching node in the widget tree
I/flutter (24813):   Actual: _KeyFinder:<zero widgets with key [<'desired_key'>] (ignoring offstage widgets)>
I/flutter (24813):    Which: means none were found but one was expected
I/flutter (24813): 
I/flutter (24813): When the exception was thrown, this was the stack:
I/flutter (24813): #4      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/webtest/integration_test/app_test.dart:21:5)
I/flutter (24813): <asynchronous suspension>
I/flutter (24813): <asynchronous suspension>
I/flutter (24813): (elided one frame from package:stack_trace)
I/flutter (24813): ...
I/flutter (24813): 
I/flutter (24813): This was caught by the test expectation on the following line:
I/flutter (24813):   file:///Users/dhs/Documents/NCFlutter/webtest/integration_test/app_test.dart line 21
I/flutter (24813): The test description was:
I/flutter (24813):   Find text
I/flutter (24813): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (24813): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the
framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
I/flutter (24813): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (24813): The following TestFailure object was thrown running a test:
I/flutter (24813):   Expected: exactly one matching node in the widget tree
I/flutter (24813):   Actual: _KeyFinder:<zero widgets with key [<'desired_key'>] (ignoring offstage widgets)>
I/flutter (24813):    Which: means none were found but one was expected
I/flutter (24813): 
I/flutter (24813): When the exception was thrown, this was the stack:
I/flutter (24813): #4      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/webtest/integration_test/app_test.dart:21:5)
I/flutter (24813): <asynchronous suspension>
I/flutter (24813): <asynchronous suspension>
I/flutter (24813): (elided one frame from package:stack_trace)
I/flutter (24813): ...
I/flutter (24813): 
I/flutter (24813): This was caught by the test expectation on the following line:
I/flutter (24813):   file:///Users/dhs/Documents/NCFlutter/webtest/integration_test/app_test.dart line 21
I/flutter (24813): The test description was:
I/flutter (24813):   Find text
I/flutter (24813): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (24813): 00:10 +1: Find text [E]
I/flutter (24813):   Test failed. See exception logs above.
I/flutter (24813):   The test description was: Find text
I/flutter (24813):   
I/flutter (24813): 00:11 +1 -1: (tearDownAll)
Failure Details:
Failure in method: Find text
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _KeyFinder:<zero widgets with key [<'desired_key'>]
(ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/webtest/integration_test/app_test.dart:21:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/dhs/Documents/NCFlutter/webtest/integration_test/app_test.dart line 21
The test description was:
  Find text
═════════════════════════════════════════════════════════════════

end of failure 1



I/flutter (24813): 00:11 +2 -1: Some tests failed.
dhs@Dhss-MacBook-Pro webtest % 

```

</details>

**Comment by dam-ease** [comment]
I am able to reproduce this issue on the latest `master` and `stable` channels. 
[Code Sample](https://github.com/flutter/flutter/issues/77151#issue-821242891)
<details><summary>Log</summary>
<p>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _KeyFinder:<zero widgets with key [<'desired_key'>] (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/dammya/triage/flutter_master/test/widget_test.dart:21:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/dammya/triage/flutter_master/test/widget_test.dart line 21
The test description was:
  Find text
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Find text



``` 

</p>
</details> 

<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (6 days ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • TECNO LC6a (mobile)        • 044882598G014637                     • android-arm    • Android 9 (API 28)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.10.0 on channel stable at /Users/dammya/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • TECNO LC6a (mobile)        • 044882598G014637                     • android-arm    • Android
      9 (API 28)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android
      11 (API 30) (emulator)
    • iPhone 14 Pro Max (mobile) • D7F3302D-D66F-4B89-B8CF-DBEE1CDB5449 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS
      13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```
</details>
