### ISSUE TITLE
[tool] Building flutter tool...  ===== CRASH ===== si_signo=Segmentation fault: 11(11)

### ISSUE THREAD

**Issue by newPersonKing** [flutter/flutter#77203]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
===== CRASH =====                                                       
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7fd07560cc0   
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64" 
pid=2480, thread=6915, isolate_group=(nil)(0x0), isolate=(nil)(0x0)     
isolate_instructions=0, vm_instructions=1048115a0                       
  pc 0x00007fffc5cda05d fp 0x0000700006662eb0 objc_msgSend+0x1d         
  pc 0x00007fffb714c51f fp 0x0000700006662ee0 SecTrustValidateInput+0x2d
  pc 0x00007fffb714cd46 fp 0x0000700006662f30 __SecTrustEvaluateIfNecessary_block_invoke_2+0x15
  pc 0x00007fffc68543a7 fp 0x0000700006662f60 _os_activity_initiate_impl+0x35
  pc 0x00007fffb714cd2a fp 0x0000700006662fb0 __SecTrustEvaluateIfNecessary_block_invoke+0x115
  pc 0x00007fffc65ec8fc fp 0x0000700006662fd0 _dispatch_client_callout+0x8
  pc 0x00007fffc65ed536 fp 0x0000700006663000 _dispatch_barrier_sync_f_invoke+0x53
  pc 0x00007fffb714a1b9 fp 0x0000700006663100 SecTrustEvaluateIfNecessary+0x199
  pc 0x00007fffb70d4b6e fp 0x0000700006663290 SecTrustEvaluate+0x3e     
                                                                        
===== CRASH =====                                                       
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x18            
Aborting re-entrant request for stack trace.                            
Running "flutter pub get" in flutter_tools...                           
pub get failed (-6; Aborting re-entrant request for stack trace.)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7fc826d11d0
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
pid=2468, thread=3843, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=106ca35a0
  pc 0x00007fffc5cda05d fp 0x0000700007823eb0 objc_msgSend+0x1d
  pc 0x00007fffb714c51f fp 0x0000700007823ee0 SecTrustValidateInput+0x2d
  pc 0x00007fffb714cd46 fp 0x0000700007823f30 __SecTrustEvaluateIfNecessary_block_invoke_2+0x15
  pc 0x00007fffc68543a7 fp 0x0000700007823f60 _os_activity_initiate_impl+0x35
  pc 0x00007fffb714cd2a fp 0x0000700007823fb0 __SecTrustEvaluateIfNecessary_block_invoke+0x115
  pc 0x00007fffc65ec8fc fp 0x0000700007823fd0 _dispatch_client_callout+0x8
  pc 0x00007fffc65ed536 fp 0x0000700007824000 _dispatch_barrier_sync_f_invoke+0x53
  pc 0x00007fffb714a1b9 fp 0x0000700007824100 SecTrustEvaluateIfNecessary+0x199
  pc 0x00007fffb70d4b6e fp 0x0000700007824290 SecTrustEvaluate+0x3e
  pc 0x0000000106c99939 fp 0x0000700007824380 dart::bin::TrustEvaluateHandler(long long, _Dart_CObject*)+0xb9
  pc 0x0000000106eac5ff fp 0x0000700007824cf0 dart::NativeMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)+0xbf
  pc 0x0000000106ea9853 fp 0x0000700007824d70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x133
  pc 0x0000000106ea9e64 fp 0x0000700007824dd0 dart::MessageHandler::TaskCallback()+0x1e4
  pc 0x0000000106fdc398 fp 0x0000700007824e60 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x158
  pc 0x0000000106fdc65f fp 0x0000700007824e90 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
  pc 0x0000000106f40ce5 fp 0x0000700007824ef0 dart::ThreadStart(void*)+0xb5
  pc 0x00007fffc683b93b fp 0x0000700007824f10 _pthread_body+0xb4
  pc 0x00007fffc683b887 fp 0x0000700007824f50 _pthread_body+0x0
  pc 0x00007fffc683b08d fp 0x0000700007824f78 thread_start+0xd
-- End of DumpStackTrace
/Users/guoyong/flutter/flutter/bin/internal/shared.sh: line 224:  2468 Abort trap: 6           "$DART" --disable-dart-dev --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
zhangtiongdeMBP:~ guoyong$ flutter pub get
/Users/guoyong/flutter/flutter/bin/internal/shared.sh: line 237: syntax error near unexpected token `esac'
zhangtiongdeMBP:~ guoyong$ flutter pub get
zhangtiongdeMBP:~ guoyong$ flutter precache
Running "flutter pub get" in flutter_tools...                          ⣻
===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7f8996e09d0
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
pid=2677, thread=4355, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=1020835a0
  pc 0x00007fffc5cda05d fp 0x0000700006696eb0 objc_msgSend+0x1d
  pc 0x00007fffb714c51f fp 0x0000700006696ee0 SecTrustValidateInput+0x2d
  pc 0x00007fffb714cd46 fp 0x0000700006696f30 __SecTrustEvaluateIfNecessary_block_invoke_2+0x15
  pc 0x00007fffc68543a7 fp 0x0000700006696f60 _os_activity_initiate_impl+0x35
  pc 0x00007fffb714cd2a fp 0x0000700006696fb0 __SecTrustEvaluateIfNecessary_block_invoke+0x115
  pc 0x00007fffc65ec8fc fp 0x0000700006696fd0 _dispatch_client_callout+0x8
  pc 0x00007fffc65ed536 fp 0x0000700006697000 _dispatch_barrier_sync_f_invoke+0x53
  pc 0x00007fffb714a1b9 fp 0x0000700006697100 SecTrustEvaluateIfNecessary+0x199
  pc 0x00007fffb70d4b6e fp 0x0000700006697290 SecTrustEvaluate+0x3e
  pc 0x0000000102079939 fp 0x0000700006697380 dart::bin::TrustEvaluateHandler(long long, _Dart_CObject*)+0xb9
  pc 0x000000010228c5ff fp 0x0000700006697cf0 dart::NativeMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)+0xbf
  pc 0x0000000102289853 fp 0x0000700006697d70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x133
  pc 0x0000000102289e64 fp 0x0000700006697dd0 dart::MessageHandler::TaskCallback()+0x1e4
  pc 0x00000001023bc398 fp 0x0000700006697e60 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x158
  pc 0x00000001023bc65f fp 0x0000700006697e90 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
  pc 0x0000000102320ce5 fp 0x0000700006697ef0 dart::ThreadStart(void*)+0xb5
  pc 0x00007fffc683b93b fp 0x0000700006697f10 _pthread_body+0xb4
  pc 0x00007fffc683b887 fp 0x0000700006697f50 _pthread_body+0x0
  pc 0x00007fffc683b08d fp 0x0000700006697f78 thread_start+0xd
-- End of DumpStackTrace
/Users/guoyong/flutter/flutter/bin/internal/shared.sh: line 224:  2677 Abort trap: 6           "$DART" --disable-dart-dev --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
zhangtiongdeMBP:~ guoyong$ clear

zhangtiongdeMBP:~ guoyong$ flutter doctor -v
                                                                        
===== CRASH =====                                                       
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7f982d50ff8   
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64" 
pid=3053, thread=6659, isolate_group=(nil)(0x0), isolate=(nil)(0x0)     
isolate_instructions=0, vm_instructions=1088885a0                       
  pc 0x00007fffc5cda05d fp 0x000070000b2b5eb0 objc_msgSend+0x1d         
  pc 0x00007fffb714c51f fp 0x000070000b2b5ee0 SecTrustValidateInput+0x2d
  pc 0x00007fffb714cd46 fp 0x000070000b2b5f30 __SecTrustEvaluateIfNecessary_block_invoke_2+0x15
  pc 0x00007fffc68543a7 fp 0x000070000b2b5f60 _os_activity_initiate_impl+0x35
  pc 0x00007fffb714cd2a fp 0x000070000b2b5fb0 __SecTrustEvaluateIfNecessary_block_invoke+0x115
  pc 0x00007fffc65ec8fc fp 0x000070000b2b5fd0 _dispatch_client_callout+0x8
  pc 0x00007fffc65ed536 fp 0x000070000b2b6000 _dispatch_barrier_sync_f_invoke+0x53
  pc 0x00007fffb714a1b9 fp 0x000070000b2b6100 SecTrustEvaluateIfNecessary+0x199
  pc 0x00007fffb70d4b6e fp 0x000070000b2b6290 SecTrustEvaluate+0x3e     
  pc 0x000000010887e939 fp 0x000070000b2b6380 dart::bin::TrustEvaluateHandler(long long, _Dart_CObject*)+0xb9
  pc 0x0000000108a915ff fp 0x000070000b2b6cf0 dart::NativeMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)+0xbf
  pc 0x0000000108a8e853 fp 0x000070000b2b6d70 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x133
  pc 0x0000000108a8ee64 fp 0x000070000b2b6dd0 dart::MessageHandler::TaskCallback()+0x1e4
  pc 0x0000000108bc1398 fp 0x000070000b2b6e60 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x158
                                                                        
===== CRASH =====                                                       
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x18            
Aborting re-entrant request for stack trace.                            
Running "flutter pub get" in flutter_tools...                           
pub get failed (-6; Aborting re-entrant request for stack trace.)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:322:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:222:7)
<asynchronous suspension>
#3      PubDependencies.update (package:flutter_tools/src/cache.dart:774:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#18     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>



zhangtiongdeMBP:~ guoyong$ clear

zhangtiongdeMBP:~ guoyong$ flutter doctor -v
                                                                        
===== CRASH =====                                                       
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7fe5f3e13a8   
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64" 
pid=3120, thread=6915, isolate_group=(nil)(0x0), isolate=(nil)(0x0)     
isolate_instructions=0, vm_instructions=102e3e5a0                       
  pc 0x00007fffc5cda05d fp 0x0000700003c7beb0 objc_msgSend+0x1d         
  pc 0x00007fffb714c51f fp 0x0000700003c7bee0 SecTrustValidateInput+0x2d
  pc 0x00007fffb714cd46 fp 0x0000700003c7bf30 __SecTrustEvaluateIfNecessary_block_invoke_2+0x15
  pc 0x00007fffc68543a7 fp 0x0000700003c7bf60 _os_activity_initiate_impl+0x35
  pc 0x00007fffb714cd2a fp 0x0000700003c7bfb0 __SecTrustEvaluateIfNecessary_block_invoke+0x115
  pc 0x00007fffc65ec8fc fp 0x0000700003c7bfd0 _dispatch_client_callout+0x8
  pc 0x00007fffc65ed536 fp 0x0000700003c7c000 _dispatch_barrier_sync_f_invoke+0x53
  pc 0x00007fffb714a1b9 fp 0x0000700003c7c100 SecTrustEvaluateIfNecessary+0x199
  pc 0x00007fffb70d4b6e fp 0x0000700003c7c290 SecTrustEvaluate+0x3e     
                                                                        
===== CRASH =====                                                       
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x18            
Aborting re-entrant request for stack trace.                            
Running "flutter pub get" in flutter_tools...                           
pub get failed (-6; Aborting re-entrant request for stack trace.)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:322:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:222:7)
<asynchronous suspension>
#3      PubDependencies.update (package:flutter_tools/src/cache.dart:774:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#15     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#18     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>




===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7fb55190e40
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
pid=3108, thread=8203, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=1052565a0
  pc 0x00007fffc5cda05d fp 0x000070000f17aeb0 objc_msgSend+0x1d
  pc 0x00007fffb714c51f fp 0x000070000f17aee0 SecTrustValidateInput+0x2d
  pc 0x00007fffb714cd46 fp 0x000070000f17af30 __SecTrustEvaluateIfNecessary_block_invoke_2+0x15
  pc 0x00007fffc68543a7 fp 0x000070000f17af60 _os_activity_initiate_impl+0x35
  pc 0x00007fffb714cd2a fp 0x000070000f17afb0 __SecTrustEvaluateIfNecessary_block_invoke+0x115
  pc 0x00007fffc65ec8fc fp 0x000070000f17afd0 _dispatch_client_callout+0x8
  pc 0x00007fffc65ed536 fp 0x000070000f17b000 _dispatch_barrier_sync_f_invoke+0x53
  pc 0x00007fffb714a1b9 fp 0x000070000f17b100 SecTrustEvaluateIfNecessary+0x199

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x18
Aborting re-entrant request for stack trace.
  pc 0x00007fffb70d4b6e fp 0x000070000f17b290 SecTrustEvaluate+0x3e
/Users/guoyong/flutter/flutter/bin/internal/shared.sh: line 224:  3108 Abort trap: 6           "$DART" --disable-dart-dev --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
zhangtiongdeMBP:~ guoyong$ 

```

</details>

**Comment by Bohirjon** [comment]
![Screen Shot 2021-03-04 at 10 18 14](https://user-images.githubusercontent.com/17494227/109915024-ef9dba80-7cd2-11eb-9dc8-f995dc8efcfe.png)
I just upgraded to latest 2.0.0 version and it's working fine for me.

**Comment by newPersonKing** [comment]
> ![Screen Shot 2021-03-04 at 10 18 14](https://user-images.githubusercontent.com/17494227/109915024-ef9dba80-7cd2-11eb-9dc8-f995dc8efcfe.png)
> I just upgraded to latest 2.0.0 version and it's working fine for me.

how upgraded?? I download the zip and  replace the path，the old version is ok

**Comment by reza-ebrahimi** [comment]
```bash
$ flutter channel stable
$ flutter upgrade
```

**Comment by TahaTesser** [comment]
Hi @newPersonKing 
Please execute the following commands
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`
Thank you

**Comment by mraleph** [comment]
@newPersonKing are you in China? are you using any Pub mirrors? (e.g. as described in https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site). 

I would guess that this issue might be uniquely China specific.

**Comment by newPersonKing** [comment]
> Hi @newPersonKing
> Are you upgrading or this is a fresh install?
> If upgrade, please execute the following commands
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> Thank you

run flutter upgrade --force

```
Building flutter tool...

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7fc6b070d38
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
pid=8951, thread=4867, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=1041b35a0
  pc 0x00007fffd445105d fp 0x000070000abc4eb0 objc_msgSend+0x1d
  pc 0x00007fffc58c351f fp 0x000070000abc4ee0 SecTrustValidateInput+0x2d
  pc 0x00007fffc58c3d46 fp 0x000070000abc4f30 __SecTrustEvaluateIfNecessary_block_invoke_2+0x15
  pc 0x00007fffd4fcb3a7 fp 0x000070000abc4f60 _os_activity_initiate_impl+0x35
  pc 0x00007fffc58c3d2a fp 0x000070000abc4fb0 __SecTrustEvaluateIfNecessary_block_invoke+0x115
  pc 0x00007fffd4d638fc fp 0x000070000abc4fd0 _dispatch_client_callout+0x8
  pc 0x00007fffd4d64536 fp 0x000070000abc5000 _dispatch_barrier_sync_f_invoke+0x53
  pc 0x00007fffc58c11b9 fp 0x000070000abc5100 SecTrustEvaluateIfNecessary+0x199
  pc 0x00007fffc584bb6e fp 0x000070000abc5290 SecTrustEvaluate+0x3e

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x18
Aborting re-entrant request for stack trace.
/Users/guoyong/flutter/flutter/bin/internal/shared.sh: line 20:  8951 Abort trap: 6           "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x7fe3b470d28
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
pid=8962, thread=3843, isolate_group=(nil)(0x0), isolate=(nil)(0x0)
isolate_instructions=0, vm_instructions=1020c95a0
  pc 0x00007fffd445105d fp 0x0000700002fb3eb0 objc_msgSend+0x1d
  pc 0x00007fffc58c351f fp 0x0000700002fb3ee0 SecTrustValidateInput+0x2d
  pc 0x00007fffc58c3d46 fp 0x0000700002fb3f30 __SecTrustEvaluateIfNecessary_block_invoke_2+0x15
  pc 0x00007fffd4fcb3a7 fp 0x0000700002fb3f60 _os_activity_initiate_impl+0x35
  pc 0x00007fffc58c3d2a fp 0x0000700002fb3fb0 __SecTrustEvaluateIfNecessary_block_invoke+0x115
  pc 0x00007fffd4d638fc fp 0x0000700002fb3fd0 _dispatch_client_callout+0x8
  pc 0x00007fffd4d64536 fp 0x0000700002fb4000 _dispatch_barrier_sync_f_invoke+0x53
  pc 0x00007fffc58c11b9 fp 0x0000700002fb4100 SecTrustEvaluateIfNecessary+0x199
  pc 0x00007fffc584bb6e fp 0x0000700002fb4290 SecTrustEvaluate+0x3e

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x18
Aborting re-entrant request for stack trace.
/Users/guoyong/flutter/flutter/bin/internal/shared.sh: line 20:  8962 Abort trap: 6           "$PUB" upgrade "$VERBOSITY" --no-precompile
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
```

**Comment by newPersonKing** [comment]
> @newPersonKing are you in China? are you using any Pub mirrors? (e.g. as described in https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site).
> 
> I would guess that this issue might be uniquely China specific.

export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

this is my setting

**Comment by Russiarain** [comment]
> > @newPersonKing are you in China? are you using any Pub mirrors? (e.g. as described in https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site).
> > I would guess that this issue might be uniquely China specific.
> 
> export PUB_HOSTED_URL=https://pub.flutter-io.cn
> export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
> 
> this is my setting

不是这个的问题，你下一个新版本的zip然后在环境变量里指向这个新路径的升级方式是不对的。把环境变量改回去，然后运行`flutter upgrade`试一试，应该没问题

**Comment by newPersonKing** [comment]
> > > @newPersonKing are you in China? are you using any Pub mirrors? (e.g. as described in https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site).
> > > I would guess that this issue might be uniquely China specific.
> > 
> > 
> > export PUB_HOSTED_URL=https://pub.flutter-io.cn
> > export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
> > this is my setting
> 
> 不是这个的问题，你下一个新版本的zip然后在环境变量里指向这个新路径的升级方式是不对的。把环境变量改回去，然后运行`flutter upgrade`试一试，应该没问题

我第一次是直接 下载zip 然后解压 直接把环境变量的路径 以及AS的依赖路径 都改成2.0的 然后 执行 pub get 报上面的错误
之后 我又切换到1.22.6 环境变量也改了 也能正常执行upgradle  只是执行到最后 build flutter tool 就又报错了

**Comment by Russiarain** [comment]
> > > > @newPersonKing are you in China? are you using any Pub mirrors? (e.g. as described in https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site).
> > > > I would guess that this issue might be uniquely China specific.
> > > 
> > > 
> > > export PUB_HOSTED_URL=https://pub.flutter-io.cn
> > > export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
> > > this is my setting
> > 
> > 
> > 不是这个的问题，你下一个新版本的zip然后在环境变量里指向这个新路径的升级方式是不对的。把环境变量改回去，然后运行`flutter upgrade`试一试，应该没问题
> 
> 我第一次是直接 下载zip 然后解压 直接把环境变量的路径 以及AS的依赖路径 都改成2.0的 然后 执行 pub get 报上面的错误
> 之后 我又切换到1.22.6 环境变量也改了 也能正常执行upgradle 只是执行到最后 build flutter tool 就又报错了

那就很奇怪了，你可以试试把flutter\bin下面的cache文件夹整个删掉，然后直接双击flutter.bat让它把dart还有其他依赖都更新一下，这个过程会重新build flutter_tool

**Comment by newPersonKing** [comment]
> > > > > @newPersonKing are you in China? are you using any Pub mirrors? (e.g. as described in https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site).
> > > > > I would guess that this issue might be uniquely China specific.
> > > > 
> > > > 
> > > > export PUB_HOSTED_URL=https://pub.flutter-io.cn
> > > > export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
> > > > this is my setting
> > > 
> > > 
> > > 不是这个的问题，你下一个新版本的zip然后在环境变量里指向这个新路径的升级方式是不对的。把环境变量改回去，然后运行`flutter upgrade`试一试，应该没问题
> > 
> > 
> > 我第一次是直接 下载zip 然后解压 直接把环境变量的路径 以及AS的依赖路径 都改成2.0的 然后 执行 pub get 报上面的错误
> > 之后 我又切换到1.22.6 环境变量也改了 也能正常执行upgradle 只是执行到最后 build flutter tool 就又报错了
> 
> 那就很奇怪了，你可以试试把flutter\bin下面的cache文件夹整个删掉，然后直接双击flutter.bat让它把dart还有其他依赖都更新一下，这个过程会重新build flutter_tool

还是一样的问题 我删除 执行 uogradle 跟执行 bat 都是报上面的错误 谢了 实在不行 就还是用旧版本

**Comment by newPersonKing** [comment]
> Hi @newPersonKing
> Are you upgrading or this is a fresh install?
> If upgrade, please execute the following commands
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> Thank you

1.22.6 与 2.1.0-10.0.pre 都可以正常使用 就是2.0 不可以

**Comment by newPersonKing** [comment]
It's solved，
the MAC version  is too low, 10.12.6
upgrade to latest version
