### ISSUE TITLE
'FlutterTask': property 'fastStart' doesn't have a configured value

### ISSUE THREAD

**Issue by GiovanniSM20** [flutter/flutter#77210]
## Steps to Reproduce

1. Run `flutter create some-app`.
2. ```cd ${app-name}```
3. ```flutter pub get```
4. ```flutter run```

Things that I've tested:
```flutter run --fast-start```
```flutter run --no-fast-start```
I also tried to find other ways to update the properties of my ```flutter devices --machine``` cause one of the atributes on output is ```fastStart: true```

**Expected results:**
The app works

**Actual results:**
Output ```flutter run```                                      
```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
A problem was found with the configuration of task ':app:compileFlutterBuildDebug' (type 'FlutterTask').
  - Type 'FlutterTask': property 'fastStart' doesn't have a configured value. This property isn't marked as optional and no value has been configured. Possible solutions: Assign a value to 'fastStart' or mark property 'fastStart' as optional. Please refer to https://docs.gradle.org/7.0-milestone-2/userguide/validation_problems.html#value_not_set for more details about this problem.
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 821ms                                                   
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                      1,282ms
Exception: Gradle task assembleDebug failed with exit code 1
```

<details>
  <summary>Logs</summary>

```
[  +56 ms] executing: [/home/gmartins/fvm/versions/stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[        ] executing: [/home/gmartins/fvm/versions/stable/] git tag --points-at 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[  +12 ms] Exit code 0 from: git tag --points-at 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[        ] 2.0.0
[  +29 ms] executing: [/home/gmartins/fvm/versions/stable/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/gmartins/fvm/versions/stable/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +32 ms] executing: [/home/gmartins/fvm/versions/stable/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +37 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] executing: /home/gmartins/Android/Sdk/platform-tools/adb devices -l
[  +37 ms] List of devices attached
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +49 ms] No supported devices connected.
[  +46 ms] The following devices were found, but are not supported by this project:
           Linux (desktop) • linux  • linux-x64      • Linux
           Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
           If you would like your app to run on linux or web, consider running `flutter create .` to generate projects for these platforms.
           
[  +10 ms] "flutter run" took 200ms.
[  +13 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:442:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +254 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```
Analyzing app...                                                        

   info • The value of the local variable 'db' isn't used • lib/app/shared/helpers/produto_helper.dart:25:9 • unused_local_variable
   info • The value of the local variable 'produto' isn't used • lib/app/shared/helpers/produto_helper.dart:27:14 • unused_local_variable
   info • 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. •
          lib/app/shared/widgets/custom_button.dart:34:16 • deprecated_member_use

3 issues found. (ran in 3.7s)
```

```
[✓] Flutter (Channel stable, 2.0.0, on Linux, locale en_US.utf8)
    • Flutter version 2.0.0 at /home/gmartins/fvm/versions/stable
    • Framework revision 60bd88df91 (11 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/gmartins/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.5
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-community/273
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 203.6912

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
Can you include the logs of `flutter run -v` where you target an Android device?

**Comment by shatanikmahanty** [comment]
Can you try flutter run `—fast-start -d <your Android device>`? You can get list of devices available using `flutter devices`.

**Comment by GiovanniSM20** [comment]
I also just found out that this only happens in version 2.0 I've tested same process with 1.22.6 and everything works

@shatanikmahanty I've test this but still with the same problem
```
flutter —fast-start -d emulator-5554
Could not find a command named "—fast-start".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

flutter -d emulator-5554 —fast-start
Could not find a command named "—fast-start".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

@jonahwilliams The ```flutter run -v``` 
<details>
```
[  +55 ms] executing: [/home/gmartins/fvm/versions/stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +23 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[   +1 ms] executing: [/home/gmartins/fvm/versions/stable/] git tag --points-at 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[  +10 ms] Exit code 0 from: git tag --points-at 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[        ] 2.0.0
[  +26 ms] executing: [/home/gmartins/fvm/versions/stable/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/gmartins/fvm/versions/stable/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +29 ms] executing: [/home/gmartins/fvm/versions/stable/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +34 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] executing: /home/gmartins/Android/Sdk/platform-tools/adb devices -l
[  +34 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:sdk_gphone_x86_arm device:generic_x86_arm transport_id:3
[   +5 ms] /home/gmartins/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +28 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Skipping pub get: version match.
[  +60 ms] Found plugin path_provider at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[   +4 ms] Found plugin path_provider_linux at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[   +1 ms] Found plugin path_provider_macos at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +1 ms] Found plugin path_provider_windows at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
[   +4 ms] Found plugin shared_preferences at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/
[        ] Found plugin shared_preferences_linux at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+4/
[        ] Found plugin shared_preferences_macos at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/
[   +1 ms] Found plugin shared_preferences_web at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[        ] Found plugin shared_preferences_windows at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.2+3/
[   +2 ms] Found plugin sqflite at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+3/
[ +416 ms] Found plugin path_provider at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[   +1 ms] Found plugin path_provider_linux at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[        ] Found plugin path_provider_macos at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +1 ms] Found plugin path_provider_windows at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.5/
[   +3 ms] Found plugin shared_preferences at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.12+4/
[        ] Found plugin shared_preferences_linux at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-0.0.2+4/
[        ] Found plugin shared_preferences_macos at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+11/
[   +1 ms] Found plugin shared_preferences_web at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+7/
[        ] Found plugin shared_preferences_windows at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-0.0.2+3/
[   +1 ms] Found plugin sqflite at /home/gmartins/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+3/
[  +14 ms] Generating
/media/catapimpas/gmartins/CoffeeStudio/si-informatica/app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +43 ms] ro.hardware = ranchu
[  +13 ms] Using hardware rendering with device sdk gphone x86 arm. If you notice graphics artifacts, consider enabling software rendering
with
           "--enable-software-rendering".
[  +20 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +2 ms] complete
[   +2 ms] Launching lib/main.dart on sdk gphone x86 arm in debug mode...
[   +3 ms] /home/gmartins/fvm/versions/stable/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/gmartins/fvm/versions/stable/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/gmartins/fvm/versions/stable/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.KOISRT/flutter_tool.FDLKZR/app.dill --packages
/media/catapimpas/gmartins/CoffeeStudio/si-informatica/app/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +11 ms] executing: /home/gmartins/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +10 ms] <- compile package:sivendas/main.dart
[  +31 ms] --------- beginning of main
           03-04 02:25:00.014 D/KeyguardClockSwitch(  849): Updating clock: 225
[  +13 ms] executing: /home/gmartins/Android/Sdk/platform-tools/adb version
[   +7 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as /home/gmartins/Android/Sdk/platform-tools/adb
[   +4 ms] executing: /home/gmartins/Android/Sdk/platform-tools/adb start-server
[  +15 ms] Building APK
[  +17 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from /media/catapimpas/gmartins/CoffeeStudio/si-informatica/app/android/gradlew.
[        ] /media/catapimpas/gmartins/CoffeeStudio/si-informatica/app/android/gradlew mode: 33261 rwxr-xr-x.
[   +4 ms] executing: /opt/android-studio/jre/bin/java -version
[  +48 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
           OpenJDK 64-Bit Server VM (build 25.242-b3-6222593, mixed mode)
[   +1 ms] executing: [/media/catapimpas/gmartins/CoffeeStudio/si-informatica/app/android/]
/media/catapimpas/gmartins/CoffeeStudio/si-informatica/app/android/gradlew -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=/media/catapimpas/gmartins/CoffeeStudio/si-informatica/app/lib/main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +839 ms] > Task :app:compileFlutterBuildDebug FAILED
[        ] Execution optimizations have been disabled for task ':app:compileFlutterBuildDebug' to ensure correctness due to the following
reasons:
[        ]   - Type 'FlutterTask': property 'assets' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'assetsDirectory' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'buildMode' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'flutterExecutable' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'flutterRoot' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'intermediateDir' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'performanceMeasurementFile' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'snapshots' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'sourceDir' is not annotated with an input or output annotation.
[        ]   - Type 'FlutterTask': property 'verbose' is not annotated with an input or output annotation.
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/7.0-milestone-2/userguide/command_line_interface.html#sec:command_line_warnings
[        ] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[        ] Please consult deprecation warnings for more details.
[        ] 1 actionable task: 1 executed
[   +1 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] A problem was found with the configuration of task ':app:compileFlutterBuildDebug' (type 'FlutterTask').
[        ]   - Type 'FlutterTask': property 'fastStart' doesn't have a configured value. This property isn't marked as optional and no value
has been configured. Possible solutions: Assign a value to 'fastStart' or mark property 'fastStart' as optional. Please refer to
https://docs.gradle.org/7.0-milestone-2/userguide/validation_problems.html#value_not_set for more details about this problem.
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to
get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 740ms
[ +310 ms] Running Gradle task 'assembleDebug'... (completed in 1,214ms)
[+4145 ms] /home/gmartins/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/overlay.dart:156:19: Error: The method
'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.
[        ]  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
('/home/gmartins/fvm/versions/stable/packages/flutter/lib/src/widgets/framework.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
[        ]       if (context.ancestorWidgetOfExactType(OverlaySupport) != null) {
[        ]                   ^^^^^^^^^^^^^^^^^^^^^^^^^
[   +6 ms] /home/gmartins/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/overlay_entry.dart:17:37: Error: The method
'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.
[        ]  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
('/home/gmartins/fvm/versions/stable/packages/flutter/lib/src/widgets/framework.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'ancestorWidgetOfExactType'.
[        ]     final animatedOverlay = context.ancestorWidgetOfExactType(_AnimatedOverlay);
[        ]                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
[   +3 ms] /home/gmartins/.pub-cache/hosted/pub.dartlang.org/overlay_support-1.0.5/lib/src/theme.dart:53:20: Error: The method
'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
[        ]  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
('/home/gmartins/fvm/versions/stable/packages/flutter/lib/src/widgets/framework.dart').
[        ] Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
[        ]     return context.inheritFromWidgetOfExactType(OverlaySupportTheme) as OverlaySupportTheme;
[        ]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+3378 ms] Exception: Gradle task assembleDebug failed with exit code 1
[        ] "flutter run" took 9,669ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +72 ms] ensureAnalyticsSent: 71ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +13 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```
</details>

**Comment by jonahwilliams** [comment]
What version of gradle are you using? You can find this in android/gradle/wrapper/gradle-wrapper.properties

**Comment by GiovanniSM20** [comment]
7.0-milestone-2-all cause the app forced me saying that I would need to run version 7

**Comment by jonahwilliams** [comment]
6.7 is the highest version supported by flutter - there are breaking changes in 7.0 that we haven't accounted for yet

**Comment by TahaTesser** [comment]
Hi @GiovanniSM20 
App runs fine on the latest `stable` with `flutter run --fast-start` with Gradle 6.7 (default)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 60bd88df91 (18 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80
      darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

</details>

Can you please try with a supported Gradle versionsl 6.7?
Thank you

**Comment by GiovanniSM20** [comment]
I just modified my distributionUrl
```distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip```

after changing the version of my gradle and running the ```flutter run --fast-start``` the app returns "This app is only meant to be run under the flutter debugger" and when I run just the ```flutter run``` it gives a problem in a package in which I'll open an issue to understand the problem. Just out of curiosity this was tested in version 2.0 but testing in 1.22.6 everything works - including the most recent gradle - but now I think there is a problem with the version package.

**Comment by TahaTesser** [comment]
Hi @GiovanniSM20 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
