### ISSUE TITLE
[Integration Test] Found some error when run integration_testing in Flutter.

### ISSUE THREAD

**Issue by TBoonkwan** [flutter/flutter#77225]
I have implement Get It as dependency injection and Stacked as a State Management.
My problem is when i run this test case then i got some error something like this.
I would like to know how to fix that.

Here is my screen--> 
```
class LoginScreen extends BaseScreen<LoginViewModel> {
  @override
  Widget onCreateView(BuildContext context, LoginViewModel model) {
    return Scaffold(
      appBar: AppBar(
        title: Text(localizations.appName),
      ),
      body: Container(
        child: SingleChildScrollView(
          child: Column(
            children: [
              Container(
                margin: EdgeInsets.only(left: 16, right: 16, top: 16),
                child: TextField(
                  key: Key('username_text'),
                  style: AppTextStyles.textFieldStyle,
                  decoration: InputDecoration(
                      labelText: localizations.usernameLabel,
                      labelStyle: AppTextStyles.labelTextFieldStyle,
                      enabledBorder: AppTextStyles.enableTextFieldBorder,
                      focusedBorder: AppTextStyles.focusTextFieldBorder,
                      errorBorder: AppTextStyles.errorTextFieldBorder),
                ),
              ),
              Container(
                margin: EdgeInsets.only(left: 16, right: 16, top: 16),
                child: TextField(
                  key: Key('password_text'),
                  style: AppTextStyles.textFieldStyle,
                  decoration: InputDecoration(
                      labelText: localizations.passwordLabel,
                      labelStyle: AppTextStyles.labelTextFieldStyle,
                      enabledBorder: AppTextStyles.enableTextFieldBorder,
                      focusedBorder: AppTextStyles.focusTextFieldBorder,
                      errorBorder: AppTextStyles.errorTextFieldBorder),
                ),
              ),
              Container(
                margin: EdgeInsets.only(left: 16, right: 16, top: 16),
                child: AppButton(
                  valueKey: 'login_button',
                  label: localizations.loginLabel,
                  onClick: () {
                    Get.to(HomeScreen());
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  void onViewModelCreated(LoginViewModel model) {
  }
}
```
Here is my test case
```
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('login_test', (WidgetTester tester) async {
      app.main();
      await tester.pumpWidget(LoginScreen());
      await tester.pumpAndSettle();

      final Finder username = find.byKey(Key('username_text'));
      await tester.enterText(username, 'username');
      await tester.pumpAndSettle();

      final Finder pass = find.byKey(Key('password_text'));
      await tester.enterText(pass, 'pass');
      await tester.pumpAndSettle();

      final Finder nextButton = find.byKey(Key('login_button'));
      await tester.tap(nextButton);
      await tester.pumpAndSettle();

      final Finder backButton = find.byKey(Key('back_button'));
      await tester.tap(backButton);
      await tester.pumpAndSettle();

      await tester.idle();
    });
  });
}

```
══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════
The following assertion was thrown while executing callbacks for
FrameTiming:
'package:flutter/src/widgets/binding.dart': Failed assertion:
line 896 pos 16: '**sendFramesToEngine**': is not true.

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      WidgetsBinding.drawFrame.<anonymous closure> (package:flutter/src/widgets/binding.dart:896:16)
#3      SchedulerBinding._executeTimingsCallbacks (package:flutter/src/scheduler/binding.dart:289:19)
#7      _invoke1 (dart:ui/hooks.dart:265:10)
#8      _reportTimings (dart:ui/hooks.dart:203:3)
(elided 5 frames from class _AssertionError and dart:async)

**The TimingsCallback that gets executed was:
  Closure: (List<FrameTiming>) => Null**
═════════════════════════════════════════════════════════════════

end of failure 1
```

**Comment by TBoonkwan** [comment]
```
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('login_test', (WidgetTester tester) async {
      app.main();

      await tester.pumpWidget(LoginScreen());
      await tester.pumpAndSettle();

      final Finder username = find.byKey(Key('username_text'));
      await tester.enterText(username, 'username');
      await tester.pump(Duration(seconds: 2));

      final Finder pass = find.byKey(Key('password_text'));
      await tester.enterText(pass, 'pass');
      await tester.pump(Duration(seconds: 2));

      final Finder nextButton = find.byKey(Key('login_button'));
      await tester.tap(nextButton);
      await tester.pump(Duration(seconds: 3));

      final Finder backButton = find.byKey(Key('back_button'));
      await tester.tap(backButton);
      await tester.pump(Duration(seconds: 3));
    });
  });
```

**Comment by TBoonkwan** [comment]
```
Future<void> main() => integrationDriver();
```

**Comment by TBoonkwan** [comment]
```
class LoginScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    AppLocalizations localizations = AppLocalizations.of(context);
    return Scaffold(
      appBar: AppBar(
        title: Text(localizations.get.appName),
      ),
      body: Container(
        child: SingleChildScrollView(
          child: Column(
            children: [
              Container(
                margin: EdgeInsets.only(left: 16, right: 16, top: 16),
                child: TextField(
                  key: Key('username_text'),
                  style: AppTextStyles.textFieldStyle,
                  decoration: InputDecoration(
                      labelText: localizations.get.usernameLabel,
                      labelStyle: AppTextStyles.labelTextFieldStyle,
                      enabledBorder: AppTextStyles.enableTextFieldBorder,
                      focusedBorder: AppTextStyles.focusTextFieldBorder,
                      errorBorder: AppTextStyles.errorTextFieldBorder),
                ),
              ),
              Container(
                margin: EdgeInsets.only(left: 16, right: 16, top: 16),
                child: TextField(
                  key: Key('password_text'),
                  style: AppTextStyles.textFieldStyle,
                  decoration: InputDecoration(
                      labelText: localizations.get.passwordLabel,
                      labelStyle: AppTextStyles.labelTextFieldStyle,
                      enabledBorder: AppTextStyles.enableTextFieldBorder,
                      focusedBorder: AppTextStyles.focusTextFieldBorder,
                      errorBorder: AppTextStyles.errorTextFieldBorder),
                ),
              ),
              Container(
                margin: EdgeInsets.only(left: 16, right: 16, top: 16),
                child: AppButton(
                  valueKey: 'login_button',
                  label: localizations.get.loginLabel,
                  onClick: () {
                    Get.to(HomeScreen());
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by darshankawar** [comment]
@TBoonkwan 
Please provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) preferably in single file (main.dart) and your integration test files also in respective files, instead of providing your code in different comments.

**Comment by TBoonkwan** [comment]
@darshankawar  am so sorry about that and thanks.

**Comment by TBoonkwan** [comment]
Uploading Screen Recording 2564-03-04 at 17.37.01.mov…

**Comment by Ahmadre** [comment]
@darshankawar I got the same problem which occurs just **sometimes**. Here's my flutter -v:

```bash
❯ flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-13.0.pre.192, on macOS 11.2.3 20D91 darwin-x64, locale de-DE)
    • Flutter version 2.1.0-13.0.pre.192 at /Users/rebar/flutter
    • Framework revision c0bcb4fc16 (vor 2 Tagen), 2021-03-19 16:34:57 -0700
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rebar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

Including the error from Firebase Test Lab:

```bash
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════
The following assertion was thrown while executing callbacks for
FrameTiming:
'package:flutter/src/widgets/binding.dart': Failed assertion:
line 858 pos 16: 'sendFramesToEngine': is not true.

Either the assertion indicates an error in the framework itself,
or we should provide substantially more information in this error
message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on
GitHub:
https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      WidgetsBinding.drawFrame.<anonymous closure> (package:flutter/src/widgets/binding.dart:858:16)
#3      SchedulerBinding._executeTimingsCallbacks (package:flutter/src/scheduler/binding.dart:289:19)
#7      _invoke1 (dart:ui/hooks.dart:186:10)
#8      PlatformDispatcher._reportTimings (dart:ui/platform_dispatcher.dart:441:5)
#9      _reportTimings (dart:ui/hooks.dart:120:31)
(elided 5 frames from class _AssertionError and dart:async)

The TimingsCallback that gets executed was:
Closure: (List<FrameTiming>) => void
═════════════════════════════════════════════════════════════════

at dev.flutter.plugins.integration_test.FlutterTestRunner.run(FlutterTestRunner.java:81)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

**Comment by Ahmadre** [comment]
@TBoonkwan I solved it by using:

```dart

final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized()
        as IntegrationTestWidgetsFlutterBinding;

    binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;
```

**Comment by TBoonkwan** [comment]
Ok Thanks, I will try this solutions.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
