### ISSUE TITLE
libgcrypt.so 1.9.2 doesn't support

### ISSUE THREAD

**Issue by qwxxx** [flutter/flutter#77236]
## Steps to Reproduce

1. Update libgcrypt.so to v. 1.9.2
2. Run `flutter build linux`.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[  +49 ms] executing: uname -m
[  +23 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +11 ms] executing: [/home/user/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] executing: [/home/user/snap/flutter/common/flutter/] git tag --points-at cc9b78fc5c4a4d2d51316d9626523336230a89a9
[  +11 ms] Exit code 0 from: git tag --points-at cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] 2.1.0-10.0.pre
[  +33 ms] executing: [/home/user/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/user/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +34 ms] executing: [/home/user/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +40 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +40 ms] Skipping pub get: version match.
[  +27 ms] Found plugin path_provider_linux at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +7 ms] Found plugin path_provider_windows at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[   +6 ms] Found plugin shared_preferences at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.3/
[   +2 ms] Found plugin shared_preferences_linux at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +1 ms] Found plugin shared_preferences_macos at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +2 ms] Found plugin shared_preferences_web at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +2 ms] Found plugin shared_preferences_windows at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +79 ms] Found plugin path_provider_linux at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +1 ms] Found plugin path_provider_windows at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[   +3 ms] Found plugin shared_preferences at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.3/
[        ] Found plugin shared_preferences_linux at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[        ] Found plugin shared_preferences_macos at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +1 ms] Found plugin shared_preferences_web at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[        ] Found plugin shared_preferences_windows at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +13 ms] Generating /home/user/VsFlutter/FlutterTemplates/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +52 ms] 💪 Building with sound null safety 💪
[   +9 ms] Building Linux application...
[  +13 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /home/user/VsFlutter/FlutterTemplates/linux
[ +128 ms] -- The CXX compiler identification is Clang 6.0.0
[   +1 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[  +72 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- works
[        ] -- Detecting CXX compiler ABI info
[  +63 ms] -- Detecting CXX compiler ABI info - done
[   +5 ms] -- Detecting CXX compile features
[ +273 ms] -- Detecting CXX compile features - done
[   +4 ms] -- Found PkgConfig: /snap/flutter/current/usr/bin/pkg-config (found version "0.29.1") 
[        ] -- Checking for module 'gtk+-3.0'
[  +23 ms] --   Found gtk+-3.0, version 3.22.30
[  +74 ms] -- Checking for module 'glib-2.0'
[  +21 ms] --   Found glib-2.0, version 2.56.4
[  +57 ms] -- Checking for module 'gio-2.0'
[  +22 ms] --   Found gio-2.0, version 2.56.4
[  +62 ms] -- Checking for module 'blkid'
[  +20 ms] --   Found blkid, version 2.31.1
[  +57 ms] -- Checking for module 'liblzma'
[  +21 ms] --   Found liblzma, version 5.2.2
[  +60 ms] -- Configuring done
[   +8 ms] -- Generating done
[        ] -- Build files have been written to: /home/user/VsFlutter/FlutterTemplates/build/linux/x64/release
[   +6 ms] executing: ninja -C build/linux/x64/release install
[   +6 ms] ninja: Entering directory `build/linux/x64/release'
[+23532 ms] [1/6] Generating /home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +5 ms] [  +46 ms] executing: uname -m
[        ] [  +23 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +9 ms] executing: [/home/user/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] [        ] executing: [/home/user/snap/flutter/common/flutter/] git tag --points-at cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] [   +8 ms] Exit code 0 from: git tag --points-at cc9b78fc5c4a4d2d51316d9626523336230a89a9
[        ] [        ] 2.1.0-10.0.pre
[        ] [  +38 ms] executing: [/home/user/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [  +35 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +28 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +49 ms] Initializing file store
[        ] [  +16 ms] Skipping target: gen_localizations
[        ] [   +4 ms] unpack_linux: Starting due to {}
[        ] [  +57 ms] kernel_snapshot: Starting due to {}
[        ] [   +2 ms] unpack_linux: Complete
[        ] [ +640 ms] Found plugin path_provider_linux at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[        ] [   +4 ms] Found plugin path_provider_windows at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.0/
[        ] [   +5 ms] Found plugin shared_preferences at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.3/
[        ] [   +1 ms] Found plugin shared_preferences_linux at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[        ] [        ] Found plugin shared_preferences_macos at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[        ] [   +1 ms] Found plugin shared_preferences_web at /home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[        ] [   +1 ms] Found plugin shared_preferences_windows at
/home/user/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[   +2 ms] [  +14 ms] /home/user/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/user/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/user/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies
-Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages /home/user/VsFlutter/FlutterTemplates/.dart_tool/package_config.json --output-dill
/home/user/VsFlutter/FlutterTemplates/.dart_tool/flutter_build/6eb3b549261714550f5ef75b4c127865/app.dill --depfile
/home/user/VsFlutter/FlutterTemplates/.dart_tool/flutter_build/6eb3b549261714550f5ef75b4c127865/kernel_snapshot.d package:vsbfood/main.dart
[   +1 ms] [+13880 ms] kernel_snapshot: Complete
[        ] [ +302 ms] aot_elf_release: Starting due to {InvalidatedReason.inputChanged}
[        ] [   +3 ms] executing: /home/user/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot --deterministic
--snapshot_kind=app-aot-elf --elf=/home/user/VsFlutter/FlutterTemplates/.dart_tool/flutter_build/6eb3b549261714550f5ef75b4c127865/app.so --strip
/home/user/VsFlutter/FlutterTemplates/.dart_tool/flutter_build/6eb3b549261714550f5ef75b4c127865/app.dill
[        ] [+7587 ms] aot_elf_release: Complete
[        ] [  +34 ms] linux_aot_bundle: Starting due to {InvalidatedReason.inputChanged}
[        ] [   +9 ms] linux_aot_bundle: Complete
[        ] [  +33 ms] release_bundle_linux-x64_assets: Starting due to {}
[        ] [  +81 ms] release_bundle_linux-x64_assets: Complete
[        ] [  +23 ms] Persisting file store
[        ] [   +6 ms] Done persisting file store
[        ] [  +11 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 22 826ms.
[        ] [  +87 ms] ensureAnalyticsSent: 85ms
[        ] [   +4 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +1 ms] exiting with code 0
[ +277 ms] [2/6] Building CXX object CMakeFiles/test_flutter_2021.dir/main.cc.o
[   +8 ms] [3/6] Building CXX object CMakeFiles/test_flutter_2021.dir/flutter/generated_plugin_registrant.cc.o
[  +29 ms] [4/6] Building CXX object CMakeFiles/test_flutter_2021.dir/my_application.cc.o
[  +74 ms] [5/6] Linking CXX executable intermediates_do_not_run/test_flutter_2021
[        ] FAILED: intermediates_do_not_run/test_flutter_2021 
[   +4 ms] : && /snap/flutter/current/usr/bin/clang++  -O3 -DNDEBUG  -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/  -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/  -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8
-L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/ CMakeFiles/test_flutter_2021.dir/main.cc.o
CMakeFiles/test_flutter_2021.dir/my_application.cc.o CMakeFiles/test_flutter_2021.dir/flutter/generated_plugin_registrant.cc.o  -o
intermediates_do_not_run/test_flutter_2021  -Wl,-rpath,/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral:
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so
/home/user/VsFlutter/FlutterTemplates/linux/flutter/ephemeral/libflutter_linux_gtk.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libblkid.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/liblzma.so && :
[   +1 ms] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0008002
[   +1 ms] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crti.o: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crti.o: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/crtbegin.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/crtbegin.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/libgcc_s.so.1: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/crtend.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/crtend.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crtn.o: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib64/crtn.o: unsupported GNU_PROPERTY_TYPE (5) type:
0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: //usr/lib32/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
[        ] /snap/flutter/current/usr/bin/ld: warning: //usr/lib32/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: //usr/lib32/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: //lib64/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
[        ] /snap/flutter/current/usr/bin/ld: warning: //lib64/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: //lib64/libdl.so.2: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: //usr/lib32/libgcrypt.so.20: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: //usr/lib32/libgcrypt.so.20: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
[        ] /snap/flutter/current/usr/bin/ld: warning: //lib64/libgcrypt.so.20: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
[        ] /snap/flutter/current/usr/bin/ld: warning: //lib64/libgcrypt.so.20: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
[        ] //lib64/libgcrypt.so.20: undefined reference to `fstat@GLIBC_2.33'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] ninja: build stopped: subcommand failed.
[   +8 ms] Building Linux application... (completed in 25,0s)
[        ] "flutter linux" took 25 292ms.
[   +4 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:186:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:78:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:88:5)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1186:12)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #7      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #14     run.<anonymous closure> (package:flutter_tools/runner.dart:60:12)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #16     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #17     runInContext (package:flutter_tools/src/context_runner.dart:77:10)
           <asynchronous suspension>
           #18     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[  +80 ms] ensureAnalyticsSent: 79ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.97, on Linux, locale ru_RU.UTF-8)
    • Flutter version 2.1.0-11.0.pre.97 at /home/user/snap/flutter/common/flutter
    • Framework revision c14c8d8177 (5 часов назад), 2021-03-03 21:40:34 -0800
    • Engine revision 72bbc5d92c
    • Dart version 2.13.0 (build 2.13.0-93.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /var/lib/snapd/snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /var/lib/snapd/snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /var/lib/snapd/snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /usr/share/idea
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.
```

</details>

**Comment by qwxxx** [comment]
Working properly on libgcrypt v.1.9.1

**Comment by TahaTesser** [comment]
Hi @qwxxx 
This doesn't look related to Flutter, please file an issue on their `libgcrypt` forum if possible
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Comment by qwxxx** [comment]
> Hi @qwxxx 
> This doesn't look related to Flutter, please file an issue on their `libgcrypt` forum if possible
> Closing, as this isn't an issue with Flutter itself.  
> If you disagree, please write in the comments,  
> providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
> a minimal reproducible code sample that does not use 3rd party plugins,  
> and I will reopen it.
> Thank you

This problem reproduces in any project, that I'm trying to run on linux desktop. Also, I provided flutter doctor -v and flutter run -v in my first message.

**Comment by TahaTesser** [comment]
@qwxxx 
This doesn't look related to Flutter, please file an issue on their libgcrypt forum if possible
If you disagree, please write in the comments,
please provide logs with code sample without using a third-party package and logs running this sample
