### ISSUE TITLE
[file_selector] Android support

### ISSUE THREAD

**Issue by marchellodev** [flutter/flutter#77255]
When calling `await openFile()` on Android:

```
E/flutter (20736): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method openFile on channel plugins.flutter.io/file_selector)
E/flutter (20736): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (20736): <asynchronous suspension>
E/flutter (20736): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344:35)
E/flutter (20736): <asynchronous suspension>
E/flutter (20736): #2      MethodChannelFileSelector.openFile (package:file_selector_platform_interface/src/method_channel/method_channel_file_selector.dart:27:32)
E/flutter (20736): <asynchronous suspension>
E/flutter (20736): #3      _HomeScreenState.build.<anonymous closure> (package:sharik/screens/home.dart:72:27)
E/flutter (20736): <asynchronous suspension>
```

**Comment by TahaTesser** [comment]
Hi @marchellodev 
`file_selector` is targetted for opening file dialogs and saving files
For Android, you can use [file_picker](https://pub.dev/packages/file_picker), which works very well
Closing, If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by marchellodev** [comment]
Ok, got it, thanks!
