### ISSUE TITLE
Type error in widget inspector

### ISSUE THREAD

**Issue by Timmmm** [flutter/flutter#77270]
## Steps to Reproduce

All I did was run my app and then open the Flutter Inspector tab in Android Studio

**Expected results:** 

The dev tools.

**Actual results:** 

I get this exception in the console.

```
======== Exception caught by Flutter framework =====================================================
The following _TypeError was thrown during a service extension callback for "ext.flutter.inspector.getRootWidgetSummaryTree":
type 'Null' is not a subtype of type 'String' of 'function result'

When the exception was thrown, this was the stack: 
#0      _Location.file (package:flutter/src/widgets/widget_inspector.dart)
#1      _Location.toJsonMap (package:flutter/src/widgets/widget_inspector.dart:2842:15)
#2      _Location.toJsonMap.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:2851:44)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
...
```

The dev tools do open and show the UI (hilariously badly scaled) but have no data.

<details>
  <summary>Logs</summary>

```
Analyzing kindle_map...

   info - Unused import: 'package:location/location.dart' - lib\render.dart:3:8 - unused_import
   info - The value of the field '_location' isn't used - lib\server.dart:32:13 - unused_field
   info - Cancel instances of dart.async.StreamSubscription - lib\server.dart:33:37 - cancel_subscriptions
   info - The value of the field '_renderer' isn't used - lib\server.dart:34:16 - unused_field

4 issues found. (ran in 13.6s)
```

```
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.18363.1379], locale en-GB)
    • Flutter version 2.0.0 at C:\Users\Tim\local\flutter
    • Framework revision 60bd88df91 (25 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Tim\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Tim\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.55

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Timmmm 
Ran a sample app and opened Flutter inspector which showed the layout properly without any issues.  I am latest stable.

<img width="1421" alt="Screenshot 2021-03-05 at 12 49 50 PM" src="https://user-images.githubusercontent.com/67046386/110081093-6c06cb00-7db1-11eb-88b1-f1fcd99cbda5.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.1 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision c5a4b4029c (14 hours ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)          • 5200763ebcfa861f                     •
      android-arm    • Android 8.1.0 (API 27)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

Can you provide a sample reproducible code that shows this issue ?

**Comment by Timmmm** [comment]
Ok I tried it a second time with the exact same code and this time it worked. I'll close this for now - at least the error message is googleable if other people come across it.
