### ISSUE TITLE
Webview doesn't open in release with PlatformException

### ISSUE THREAD

**Issue by Daniel-linko** [flutter/flutter#77290]
## Steps to Reproduce
1. Our application works in simulator or physical device in debug mode.
2. We copied this code in manifest:
<uses-permission android:name="android.permission.INTERNET" />
3. when uploading the bundle to the google playstore, and then installing from the store (internal test) and executing, the webview is not loaded and we capture this exception:

```
## Exception
2021-03-04 13:42:20.915 19696-19788/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
        at io.flutter.plugin.platform.j$a.d(Unknown Source:229)
        at io.flutter.embedding.engine.i.i$a.b(Unknown Source:152)
        at io.flutter.embedding.engine.i.i$a.h(Unknown Source:144)
        at f.a.c.a.i$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.d(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    , null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
    <asynchronous suspension>
    #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039)
    <asynchronous suspension>
    #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:749)
    <asynchronous suspension>
    #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174)
    <asynchronous suspension>
```

relevant versions:
      flutter: 1.22.6
      webview_flutter: 1.0.7

We tryed many solutions found on the web but without success.
Can you please help?

**Comment by darshankawar** [comment]
@Daniel-linko 
Can you try upgrading the plugin version to latest along with the stable version and check if issue persists ?
Does the app work in release mode locally ? ie, `flutter run --release` 
If issue persists, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue.

**Comment by Daniel-linko** [comment]
Hello @darshankawar , thanks for your answer.
Unfortunately, the last version requires dart 2.12, flutter 2.01. 
Which causes lots of issues related to null safety.
Lots of packages we use are not null safe resolvables. As I understant it's not advidesd to pass to null safety untill all packages are ready, right?

as for the flutter run --release, it does not work and we haven't been able to solve it: 

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
 Could not resolve all artifacts for configuration ':app:profileRuntimeClasspath'.
    Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
       Execution failed for JetifyTransform: C:\Users\...\build\app\intermediates\flutter\profile\libs.jar.
          Transform's input file does not exist: C:\Users\...\build\app\intermediates\flutter\profile\libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

so currently, to test the release version, I have to build (using below command) and upload to the store using the internal test.
`flutter build appbundle --target-platform android-arm,android-arm64,android-x64`

So I'm not sure what to do ..

**Comment by darshankawar** [comment]
@Daniel-linko For plugins that are not null safe yet, you may try to run `flutter run --no-sound-null-safety` to disable null safety.

I tried the plugin example on latest master in release mode and was able to see the webview running properly without any issues.

![device-2021-03-08-111416](https://user-images.githubusercontent.com/67046386/110279784-b2ea0000-7fff-11eb-80c3-09dce72c16a7.png)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-11.0.pre.145, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.145 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a0ba646408 (2 days ago), 2021-03-05 22:09:03 -0500
    • Engine revision f751d04fa0
    • Dart version 2.13.0 (build 2.13.0-107.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
