### ISSUE TITLE
flutter create with flavors fails on existing apps

### ISSUE THREAD

**Issue by rymesaint** [flutter/flutter#77317]
## Steps to Reproduce

I cannot use this command `flutter create --platforms=macos .` on my existing apps because having flavors. Refer to https://github.com/flutter/flutter/issues/72329#issue-767134989

1. flutter config --enable-macos-desktop
2. flutter create --platforms=macos .

## Logs

<details>

<summary>Logs</summary>

```
$ flutter create --platforms=macos . --verbose

[  +83 ms] executing: [/Users/ridwanfauzan/Documents/flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[        ] executing: [/Users/ridwanfauzan/Documents/flutter/] git tag --points-at
60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[  +28 ms] Exit code 0 from: git tag --points-at 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[        ] 2.0.0
[  +50 ms] executing: [/Users/ridwanfauzan/Documents/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/ridwanfauzan/Documents/flutter/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +55 ms] executing: [/Users/ridwanfauzan/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +6 ms] executing: sw_vers -productName
[  +19 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.2.1
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20D74
[   +9 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +77 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +44 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +47 ms] "flutter create" took 125ms.
[   +6 ms] Multiple output directories specified.
           Try moving --verbose to be immediately following create
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      CreateBase.validateOutputDirectoryArg
           (package:flutter_tools/src/commands/create_base.dart:147:7)
           #2      CreateCommand.runCommand
(package:flutter_tools/src/commands/create.dart:181:5)
           #3      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1157:18)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +196 ms] ensureAnalyticsSent: 190ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 2
```

```
$ flutter doctor -v
Flutter (Channel stable, 2.0.0, on macOS 11.2.1 20D74 darwin-x64, locale en-ID)
    • Flutter version 2.0.0 at /Users/ridwanfauzan/Documents/flutter
    • Framework revision 60bd88df91 (34 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ridwanfauzan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Redmi Note 8 (mobile) • 11fd960b                             • android-arm64  • Android 10
      (API 29)
    • iPhone 8 (mobile)     • 2330019C-2299-450D-9420-959574B00FAD • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)       • macos                                • darwin-x64     • macOS
      11.2.1 20D74 darwin-x64
    • Chrome (web)          • chrome                               • web-javascript • Google
      Chrome 88.0.4324.192

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@rymesaint 
So you have an existing app with flavors probably creating with 1.22 stable version and you upgraded to 2.0.0 and trying to add desktop macOS support to it with the command `flutter create --platforms=macos .` which is failing, is that correct interpretation of the issue ?
When are you using the `flutter config --enable-macos-desktop` command ?

**Comment by rymesaint** [comment]
> @rymesaint
> So you have an existing app with flavors probably creating with 1.22 stable version and you upgraded to 2.0.0 and trying to add desktop macOS support to it with the command `flutter create --platforms=macos .` which is failing, is that correct interpretation of the issue ?
> When are you using the `flutter config --enable-macos-desktop` command ?

i'm upgrading from 1.26 latest-stable version and upgrade to 2.0.0, and yes trying to add desktop macOS support but it fails.

i'm using `flutter config --enable-macos-desktop` after upgrade to 2.0.0 then tried to the command `flutter create --platforms=macos .`

**Comment by darshankawar** [comment]
@rymesaint 
You may not need to run `flutter config --enable-macos-desktop in 2.0.0 version since it now by default supports desktop, so you don't need to explicitly enable it. Can you directly driectly running `flutter create --platforms=macos .` and see if issue persists or not ?

**Comment by rymesaint** [comment]
@darshankawar still an error

```
% flutter create --verbose --platforms=macos .
[  +87 ms] executing: [/Users/ridwanfauzan/Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +1 ms] executing: [/Users/ridwanfauzan/Documents/flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +90 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +55 ms] executing: [/Users/ridwanfauzan/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/ridwanfauzan/Documents/flutter/] git ls-remote --get-url origin
[  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [/Users/ridwanfauzan/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] macOS
[        ] executing: sw_vers -productVersion
[  +19 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.2.1
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20D74
[   +8 ms] executing: sysctl hw.optional.arm64
[   +8 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +70 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +88 ms] executing: /usr/bin/plutil -convert json -o - /Users/ridwanfauzan/Documents/apps/wss_mobile/./ios/Runner/Info.plist
[  +11 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/ridwanfauzan/Documents/apps/wss_mobile/./ios/Runner/Info.plist
[   +1 ms]
{"CFBundleInfoDictionaryVersion":"6.0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown",
"UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"CFBundleName":"$(APP_NAME)","UIViewControllerBasedStatusBarAppearance":false,
"NSPhotoLibraryUsageDescription":"App need permission to use gallery for getting photo and upload the image to server for photo
profile.","LSRequiresIPhoneOS":true,"CFBundleDisplayName":"$(APP_NAME)","NSLocationWhenInUseUsageDescription":"The location tracking for getting the range
radius of the user from the
school","GOOGLE_SERVICE_FOLDER_PATH":"${GOOGLE_SERVICE_INFO_PATH}","UIBackgroundModes":["fetch","remote-notification"],"CFBundleDocumentTypes":[],"NSCameraU
sageDescription":"App need permission to use camera for taking a photo and upload the image to server for photo
profile.","CFBundleShortVersionString":"$(FLUTTER_BUILD_NAME)","NSLocationAlwaysUsageDescription":"App need the location tracking for getting the range
radius of the user from the
school","UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"
io.flutter.embedded_views_preview":true,"CFBundlePackageType":"APPL","CFBundleDevelopmentRegion":"en","CFBundleVersion":"$(FLUTTER_BUILD_NUMBER)","NSPhotoLi
braryAddUsageDescription":"App need permission to save the screenshot and put it into gallery.","NSSpeechRecognitionUsageDescription":"Allow to use speech
recognition","UILaunchStoryboardName":"LaunchScreen","NSMotionUsageDescription":"Used for detecting
motion","CFBundleIdentifier":"$(PRODUCT_BUNDLE_IDENTIFIER)","NSAppleMusicUsageDescription":"Used for an audio at exam","NSCalendarsUsageDescription":"Allow
to use the calendar for status
attendance","GMAP_API_KEY":"${GMAP_API_KEY}","NSAppTransportSecurity":{"NSAllowsArbitraryLoads":true},"CFBundleExecutable":"$(EXECUTABLE_NAME)","UIMainStory
boardFile":"Main","CFBundleSignature":"????","ITSAppUsesNonExemptEncryption":false,"NSContactsUsageDescription":"Allow contact access"}
[  +22 ms] executing: sysctl hw.optional.arm64
[   +6 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +728 ms] Exit code 0 from: xcrun xcodebuild -version
[   +1 ms] Xcode 12.4
           Build version 12D4e
[   +4 ms] executing: [./ios/] xcrun xcodebuild -list
[+2023 ms] Command line invocation:
                        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

                    Information about project "Runner":
                        Targets:
                            Runner

                        Build Configurations:
                            Debug Dev
                            Debug SMPITADZKIA
                            Debug Local
                            Debug Staging
                            Debug SMPTULUSBAKTI
                            Debug SMATULUSBAKTI
                            Debug SMKALWAFA
                            Debug ALAMPANGRANGO
                            Debug MTSALINAYAH
                            Debug SMAN2BEKASI
                            Debug SMAN6BEKASI
                            Debug SMAN17BEKASI
                            Debug SMKBINAPRESTASI
                            Debug SMKPESAT
                            Debug SMAPESAT
                            Debug SMPPESAT
                            Debug SAQNURMADANI
                            Debug SDITALIYA
                            Debug SMKITNURULQOLBI
                            Debug SMKHSAGUNG
                            Release Dev
                            Release SMPITADZKIA
                            Release Local
                            Release Staging
                            Release SMPTULUSBAKTI
                            Release SMATULUSBAKTI
                            Release SMKALWAFA
                            Release ALAMPANGRANGO
                            Release MTSALINAYAH
                            Release SMAN2BEKASI
                            Release SMAN6BEKASI
                            Release SMAN17BEKASI
                            Release SMKBINAPRESTASI
                            Release SMKPESAT
                            Release SMAPESAT
                            Release SMPPESAT
                            Release SDITALIYA
                            Release SAQNURMADANI
                            Release SMKITNURULQOLBI
                            Release SMKHSAGUNG

                        If no build configuration is specified and -scheme is not passed then "Debug Staging" is used.

                        Schemes:
                            ALAMPANGRANGO
                            dev
                            SDITALIYA
                            SMAN2BEKASI
                            SMAN6BEKASI
                            SMAPESAT
                            SMATULUSBAKTI
                            SMKALWAFA
                            SMKBINAPRESTASI
                            SMKHSAGUNG
                            SMKITNURULQOLBI
                            SMKPESAT
                            SMPITADZKIA
                            SMPPESAT
                            SMPTULUSBAKTI
[   +3 ms] The Xcode project defines schemes: ALAMPANGRANGO, dev, SDITALIYA, SMAN2BEKASI, SMAN6BEKASI, SMAPESAT, SMATULUSBAKTI, SMKALWAFA, SMKBINAPRESTASI,
SMKHSAGUNG,
           SMKITNURULQOLBI, SMKPESAT, SMPITADZKIA, SMPPESAT, SMPTULUSBAKTI
[  +20 ms] "flutter create" took 2,995ms.
[   +8 ms] You must specify a --flavor option to select one of the available schemes.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      XcodeProjectInfo.reportFlavorNotFoundAndExit (package:flutter_tools/src/ios/xcodeproj.dart:555:7)
           #2      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:574:12)
           <asynchronous suspension>
           #3      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:509:50)
           <asynchronous suspension>
           #4      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:486:41)
           <asynchronous suspension>
           #5      FlutterProject.organizationNames (package:flutter_tools/src/project.dart:109:9)
           <asynchronous suspension>
           #6      CreateBase.getOrganization (package:flutter_tools/src/commands/create_base.dart:234:49)
           <asynchronous suspension>
           #7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:212:33)
           <asynchronous suspension>
           #8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #18     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #20     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #21     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #22     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +130 ms] ensureAnalyticsSent: 127ms
[   +5 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

```
% flutter doctor -v 
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale en-ID)
    • Flutter version 2.0.1 at /Users/ridwanfauzan/Documents/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ridwanfauzan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

**Comment by darshankawar** [comment]
@rymesaint 
I tried to recreate the scenario using below steps:

1. Created new project in 1.22.6 stable and added demo flavors:

<img width="510" alt="Screenshot 2021-03-09 at 12 44 35 PM" src="https://user-images.githubusercontent.com/67046386/110432504-39244600-80d5-11eb-80d2-f85fc72ad4ff.png">

2. Ran `flutter upgrade` to stable 2.0.1
3. Ran `flutter create --verbose --platforms=macos .` which executed successfully without any issues. See `macos` folder generated.

<img width="441" alt="Screenshot 2021-03-09 at 12 46 09 PM" src="https://user-images.githubusercontent.com/67046386/110432677-712b8900-80d5-11eb-8803-0152b0d65470.png">

4. Ran `flutter run -d macos` which compiled and ran properly:

<img width="800" alt="Screenshot 2021-03-09 at 12 43 41 PM" src="https://user-images.githubusercontent.com/67046386/110432747-856f8600-80d5-11eb-9e2c-ad6a5060a6cf.png">

With this, I don't think there's any issue if you have flavors in the app and after upgrading, adding support for macos and web should work. Can you provide a demo app that shows this issue ?

**Comment by rymesaint** [comment]
@darshankawar i've found the solution that, i need to move the folder ios first before running command `flutter create --platforms=macos .` it's seem that ios folder is the problem when trying to add the new platform

**Comment by rymesaint** [comment]
@darshankawar yes i'm moving it manually and it was on the root project then i move it outside the root project then i tried the command and it created maybe something wrong with ios Scheme on Podfile

**Comment by darshankawar** [comment]
@rymesaint 
That doesn't sound like an intended behavior to move flutter project folders around. Since the issue isn't reproducible per my earlier comment, I am going ahead and closing this as non-issue. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by RicardoGSGraca** [comment]
I have also encountered this error. It happens when schemas are added to the iOS build. Nothing to do with flavours on the Android side.

**Comment by sososdk** [comment]
> @rymesaint
> I tried to recreate the scenario using below steps:
> 
> 1. Created new project in 1.22.6 stable and added demo flavors:
> 
> <img alt="Screenshot 2021-03-09 at 12 44 35 PM" width="510" src="https://user-images.githubusercontent.com/67046386/110432504-39244600-80d5-11eb-80d2-f85fc72ad4ff.png">
> 
> 1. Ran `flutter upgrade` to stable 2.0.1
> 2. Ran `flutter create --verbose --platforms=macos .` which executed successfully without any issues. See `macos` folder generated.
> 
> <img alt="Screenshot 2021-03-09 at 12 46 09 PM" width="441" src="https://user-images.githubusercontent.com/67046386/110432677-712b8900-80d5-11eb-8803-0152b0d65470.png">
> 
> 1. Ran `flutter run -d macos` which compiled and ran properly:
> 
> <img alt="Screenshot 2021-03-09 at 12 43 41 PM" width="800" src="https://user-images.githubusercontent.com/67046386/110432747-856f8600-80d5-11eb-9e2c-ad6a5060a6cf.png">
> 
> With this, I don't think there's any issue if you have flavors in the app and after upgrading, adding support for macos and web should work. Can you provide a demo app that shows this issue ?

@darshankawar It's not about Android, it's about iOS.

**Comment by long1eu** [comment]
@darshankawar why is this issue closed?
