### ISSUE TITLE
Flaky libsky_shell.so crash in microbenchmarks on Android

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#7735]
## Steps to Reproduce

```
cd dev/devicelab
dart bin/run.dart -t bin/tasks/microbenchmarks.dart
```

## Logs

From `adb logcat`:

```
01-30 10:36:18.520  9958  9958 D AndroidRuntime: Calling main entry com.android.commands.am.Am
01-30 10:36:18.523   802  1027 I ActivityManager: START u0 {act=android.intent.action.RUN flg=0x30000000 cmp=com.yourcompany.microbenchmarks/io.flutter.app.FlutterActivity (has extras)} from uid 2000 on display 0
01-30 10:36:18.539  9958  9958 D AndroidRuntime: Shutting down VM
01-30 10:36:18.549   802   813 I ActivityManager: Start proc 9984:com.yourcompany.microbenchmarks/u0a248 for activity com.yourcompany.microbenchmarks/io.flutter.app.FlutterActivity
01-30 10:36:18.613  9984  9984 I cr.library_loader: Time to load native libraries: 24 ms (timestamps 3772-3796)
01-30 10:36:18.613  9984  9984 I cr.library_loader: Expected native library version number "", actual native library version number ""
01-30 10:36:18.864  9984  9984 E ApkAssets: Error while loading asset assets/icudtl.dat: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
01-30 10:36:18.868  9984  9984 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
01-30 10:36:18.924  9984 10004 I flutter : Observatory listening on http://127.0.0.1:53247/
01-30 10:36:19.042 23047 24854 I Icing   : Indexing 80633029A36435F33AF8425331CF97285CA3068A from com.google.android.googlequicksearchbox
01-30 10:36:19.089  9984  9999 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 9999 (ui_thread)
01-30 10:36:19.190   194   194 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-30 10:36:19.190   194   194 F DEBUG   : Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB30Y/3067468:user/release-keys'
01-30 10:36:19.190   194   194 F DEBUG   : Revision: '11'
01-30 10:36:19.190   194   194 F DEBUG   : ABI: 'arm'
01-30 10:36:19.179   194   194 W debuggerd: type=1400 audit(0.0:58678): avc: denied { search } for name="com.yourcompany.microbenchmarks" dev="mmcblk0p28" ino=1499160 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
01-30 10:36:19.190   194   194 F DEBUG   : pid: 9984, tid: 9999, name: ui_thread  >>> com.yourcompany.microbenchmarks <<<
01-30 10:36:19.190   194   194 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
01-30 10:36:19.179   194   194 W debuggerd: type=1400 audit(0.0:58679): avc: denied { search } for name="com.yourcompany.microbenchmarks" dev="mmcblk0p28" ino=1499160 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
01-30 10:36:19.201   194   194 F DEBUG   :     r0 00000000  r1 00000001  r2 00000000  r3 00000000
01-30 10:36:19.201   194   194 F DEBUG   :     r4 b3faa1c0  r5 9f2fdc34  r6 00000000  r7 af0e9650
01-30 10:36:19.201   194   194 F DEBUG   :     r8 aebcc4c0  r9 af0e9630  sl af0e9640  fp af0e9648
01-30 10:36:19.201   194   194 F DEBUG   :     ip b3af0000  sp af0e9628  lr a16881bd  pc a1683dfc  cpsr a00f0030
01-30 10:36:19.207   194   194 F DEBUG   : 
01-30 10:36:19.207   194   194 F DEBUG   : backtrace:
01-30 10:36:19.207   194   194 F DEBUG   :     #00 pc 00098dfc  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #01 pc 0009d1b9  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #02 pc 0021b87b  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #03 pc 0021b865  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #04 pc 0020d8b9  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #05 pc 0006ef21  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #06 pc 0006f261  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #07 pc 0006fe17  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #08 pc 00071979  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #09 pc 0006ec0b  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #10 pc 00078aa7  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.207   194   194 F DEBUG   :     #11 pc 000783c1  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libsky_shell.so
01-30 10:36:19.208   194   194 F DEBUG   :     #12 pc 0003f45f  /system/lib/libc.so (_ZL15__pthread_startPv+30)
01-30 10:36:19.208   194   194 F DEBUG   :     #13 pc 00019b43  /system/lib/libc.so (__start_thread+6)
01-30 10:36:19.382 23047 24854 I Icing   : Indexing done 80633029A36435F33AF8425331CF97285CA3068A
01-30 10:36:19.514   802 10005 W ActivityManager:   Force finishing activity com.yourcompany.microbenchmarks/io.flutter.app.FlutterActivity
01-30 10:36:19.514   194   194 F DEBUG   : 
01-30 10:36:19.514   194   194 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_06
01-30 10:36:19.514   194   194 E DEBUG   : AM write failed: Broken pipe
01-30 10:36:19.514   802   818 I BootReceiver: Copying /data/tombstones/tombstone_06 to DropBox (SYSTEM_TOMBSTONE)
01-30 10:36:19.546   209   209 I Zygote  : Process 9984 exited due to signal (11)
01-30 10:36:19.821   802 10005 I WindowManager: Screenshot max retries 4 of Token{1ae2461 ActivityRecord{9aa0bc8 u0 com.yourcompany.microbenchmarks/io.flutter.app.FlutterActivity t4453 f}} appWin=Window{a658a12 u0 Starting com.yourcompany.microbenchmarks} drawState=4
01-30 10:36:19.822   802 10005 W ActivityManager: Exception thrown during pause
01-30 10:36:19.822   802 10005 W ActivityManager: android.os.DeadObjectException
01-30 10:36:19.822   802 10005 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12042)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11938)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12627)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12134)
01-30 10:36:19.822   802 10005 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
01-30 10:36:19.823   188   188 E lowmemorykiller: Error opening /proc/9984/oom_score_adj; errno=2
01-30 10:36:19.846   802  1752 I ActivityManager: Process com.yourcompany.microbenchmarks (pid 9984) has died
01-30 10:36:19.898   802  2156 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@740442f attribute=null, token = android.os.BinderProxy@afda201
01-30 10:36:19.936   802   902 I OpenGLRenderer: Initialized EGL, version 1.4
01-30 10:36:26.707   802 15759 D NetlinkSocketObserver: NeighborEvent{elapsedMs=14253596297, fe80::200:5eff:fe01:265, [00005E000265], RTM_NEWNEIGH, NUD_STALE}
01-30 10:36:27.950 23047  9963 V ConfigFetchTask: ConfigFetchTask getDeviceDataVersionInfo(): ABFEt1W27g2TWs3kMsVOFknbKBPVQKyHLthZw7KmsHfs4773f7dGV3JKRM-WB88Ee_6gWZnfT-0Bill0xj7uXW7Re6n9P8OUlw0jOK3AumZ392T0OncY2FVwRRnO0y1etKTNf_-AlzdzwGaWv-nz-LmmfeCn8rKmHNC0WYSHaBsqqR_LF5hAUSzVFYt-Eq4xYfBrgEMqpbQF
01-30 10:36:27.961 23047  9963 I GoogleURLConnFactory: Using platform SSLCertificateSocketFactory
01-30 10:36:28.073   802   895 I InputReader: Reconfiguring input devices.  changes=0x00000010
01-30 10:36:28.131  1970  1970 V GmsNetworkLocationProvi: DISABLE
01-30 10:36:28.171 23047 10057 D PackageBroadcastService: Received broadcast action=android.intent.action.PACKAGE_CHANGED and uri=com.google.android.gms
01-30 10:36:28.174 23047 10057 I PackageBroadcastService: Null package name or gms related package.  Ignoreing.
01-30 10:36:28.180  7661 10060 I UpdateIcingCorporaServi: Updating corpora: APPS=com.google.android.gms, CONTACTS=MAYBE
01-30 10:36:28.202 23047 24854 I Icing   : updateResources: need to parse f{com.google.android.gms}
01-30 10:36:28.210 23047 23047 I ConfigFetchService: fetch service done; releasing wakelock
01-30 10:36:28.211 23047 23047 I ConfigFetchService: stopping self
01-30 10:36:28.220  7661 10060 I UpdateIcingCorporaServi: UpdateCorporaTask done [took 39 ms] updated apps [took 39 ms] 
01-30 10:36:28.244  1970  1970 V GmsNetworkLocationProvi: ENABLE
01-30 10:36:28.244  1970 10111 V GmsNetworkLocationProvi: onSetRequest: ProviderRequestUnbundled, reportLocation is true and interval is 86400000
01-30 10:36:28.246  1970  1970 V GmsNetworkLocationProvi: SET-REQUEST
01-30 10:36:28.246  1970  1970 V GmsNetworkLocationProvi: in Handler: ProviderRequestUnbundled, reportLocation is true and interval is 86400000
01-30 10:36:28.251   802   814 D ActivityRecognitionProxy: AR HW instance not available, binding will be a no-op.
01-30 10:36:28.254   802  1099 D WifiService: acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@fbb22e8}
01-30 10:36:28.256   802  1008 D wifi    : Initialized common fields 10000, 16, 100, 10
01-30 10:36:28.256   802  1008 D wifi    : bucket[0] = 2:3:10000:2
01-30 10:36:28.907   802  1760 D WifiService: releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@fbb22e8}
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/emilyfortuna/.cocoon/flutter
    • Framework revision 098af18393 (10 hours ago), 2017-01-30 00:40:50
    • Engine revision 9de4d1530b
    • Tools Dart version 1.22.0-dev.9.1

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /Users/emilyfortuna/Library/Android/sdk
    • Platform android-24, build-tools 24.0.1
    • ANDROID_HOME = /Users/emilyfortuna/Library/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_102-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/

[✓] Connected devices
    • Nexus 5 • 0393c2d0216a0ec5 • android-arm • Android 6.0.1 (API 23)
```

/cc @jason-simmons @chinmaygarde

**Comment by eseidelGoogle** [comment]
That's in our code.  @jason-simmons is your man.  https://github.com/flutter/engine/wiki/Symbolicating-production-crash-stacks can also be used to get you symbols.

**Comment by jason-simmons** [comment]
The microbenchmarks should be working now
