### ISSUE TITLE
 [!] Invalid `Podfile` file: no implicit conversion of nil into String.

### ISSUE THREAD

**Issue by Nader2004** [flutter/flutter#77363]
Hello everyone. I am facing an issue when building on ios : 

```
 [!] Invalid `Podfile` file: no implicit conversion of nil into String.

     #  from /Users/builder/clone/ios/Podfile:57
     #  -------------------------------------------
     #      unless File.exist?(copied_framework_path)
     >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
     #      end
     #  -------------------------------------------

```
Here is my flutter doctor : 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.53.2)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

```

Here are my firebase packages : 

```
  firebase_storage: ^8.0.0
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_auth: ^1.0.0
  firebase_ml_vision: ^0.11.0

```

Here is the Podfile : 

```
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join('.', 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

```

**Comment by developerflutter** [comment]
Try this,
- Delete "Pod file"
- flutter pub get
- flutter clean
- Restart VS code
- Run the app

**Comment by TahaTesser** [comment]
Hi @Nader2004 
Please delete `Podspec` from `ios/Flutter/Flutter.podspec` and `flutter clean`,`flutter pub get`  run the app with `flutter run -v`
Hope that helps
Thank you

**Comment by Nader2004** [comment]
Hello @TahaTesser . I don't have the `Flutter.podspec` file at `ios/Flutter`.

**Comment by Nader2004** [comment]
@developerflutter  I tried this but it couldn't generate one because I have a windows machine. I am building using codemagic

**Comment by Nader2004** [comment]
Any help on that please ?

**Comment by harshapulikollu** [comment]
> Hi @Nader2004
> Please delete `Podspec` from `ios/Flutter/Flutter.podspec` and `flutter clean`,`flutter pub get` run the app with `flutter run -v`
> Hope that helps
> Thank you

Hi @TahaTesser 
I have followed the steps you suggested but also I'm facing issue with iOS. I'm pasting here the error.

```
           
[   +6 ms] Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
           To update the CocoaPods specs, run:
             pod repo update
           
[   +5 ms] Error running pod install
[        ] Error launching application on iPhone 12 Pro Max.
[+8819 ms] "flutter run" took 19,660ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +14 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +13 ms] Shutdown hooks complete
[        ] exiting with code 1

```

I have tired to update cocoapods with `sudo gem install cocoapods` and also did `pod repo update` as said in error. Then also I'm getting same error.

Here is my `flutter doctor -v`
```

[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.0 at /Users/harshapulikollu/Documents/development/flutter
    • Framework revision 60bd88df91 (5 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/harshapulikollu/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 7DCDC739-A9E8-4CF1-B2CA-D19E12D5BA7D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

```

**Comment by LichKing-2234** [comment]
I add `FLUTTER_FRAMEWORK_DIR=[YourFlutterLocation]/bin/cache/artifacts/engine/ios` to `ios/Flutter/Generated.xcconfig` in your project. then it works, but I have no idea why `FLUTTER_FRAMEWORK_DIR` not be generated.

**Comment by LichKing-2234** [comment]
> I add `FLUTTER_FRAMEWORK_DIR=[YourFlutterLocation]/bin/cache/artifacts/engine/ios` to `ios/Flutter/Generated.xcconfig` in your project. then it works, but I have no idea why `FLUTTER_FRAMEWORK_DIR` not be generated.

only success if I run pod install by myself. not work for flutter run.

**Comment by TahaTesser** [comment]
Hi @Nader2004  @harshapulikollu  @LichKing-2234 
Along with `Podspec` (ios/Flutter/Flutter.podspec), please also delete `Podfile` and `Podfile.lock` files too and then followed `pub get get `and `flutter run`
I had this issue with an old project and this solved it

**Comment by LichKing-2234** [comment]
@TahaTesser It works after I delete the `Podfile`, thanks.

**Comment by harshapulikollu** [comment]
@TahaTesser Yeah it was working. Thankyou.

**Comment by Nader2004** [comment]
> Hi @Nader2004 @harshapulikollu @LichKing-2234
> Along with `Podspec` (ios/Flutter/Flutter.podspec), please also delete `Podfile` and `Podfile.lock` files too and then followed `pub get get `and `flutter run`
> I had this issue with an old project and this solved it


@TahaTesser  Thanks for your answer , but how can I do this in codemagic , (in case you have experience with) . I mean if I deleted these 2 files would codemagic do this automatically : `pub get` and then `flutter run`  .

**Comment by TahaTesser** [comment]
@Nader2004 
You answered your question, just make sure these files are deleted, when Codemagic runs your build, it should take care of itself.

Thanks for confirming everyone,  I feel safe to close the issue
