### ISSUE TITLE
Illegal cast to non-nullable type in NavigationRail

### ISSUE THREAD

**Issue by HeavenOSK** [flutter/flutter#77368]
## Steps to Reproduce
1. Use `NavigationRail`
2. Pass `NavigationRailDestination` without `label` to `NavigationRail#destinations`
 
I've created a project to reproduce it, if you'd like to take a look.
https://github.com/HeavenOSK/navigation_rail_error_sample/blob/main/lib/main.dart

**Expected results:** 
No error.

I think the expected behaviors are likely to be one of the following:

- Works fine even if label is null
- label should be a non-nullable type
 
**Actual results:** 
The following line gives an error when trying to cast the `null` to a non-nullable type.
 https://github.com/flutter/flutter/blob/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/packages/flutter/lib/src/material/navigation_rail.dart#L494
 
<details>
  <summary>Logs</summary>
 
```
                    ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following _CastError was thrown building NavigationRail(dirty, dependencies:
                    [_EffectiveTickerMode, _LocalizationsScope-[GlobalKey#89f95], _InheritedTheme], state:
                    _NavigationRailState#4adbe(tickers: tracking 3 tickers)):
                    Null check operator used on a null value
                    
                    The relevant error-causing widget was:
                      NavigationRail
                      file:///Users/heavenosk/heavenosk/experiment/flutter/navigation_rail_sample/lib/main.dart:12:13
                    
                    When the exception was thrown, this was the stack:
                    #0      _NavigationRailState.build (package:flutter/src/material/navigation_rail.dart:494:62)
                    #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
                    #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
                    #3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
                    #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
                    #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4474:5)
                    #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4658:11)
                    #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4469:5)
                    #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
                    #9      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (19 frames)
                    #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
                    #29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (88 frames)
                    #117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
                    #118    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (170 frames)
                    #288    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
                    #289    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
                    ...     Normal element mounting (315 frames)
                    #604    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
                    #605    Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
                    #606    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1182:16)
                    #607    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1153:5)
                    #608    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1095:18)
                    #609    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2647:19)
                    #610    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1094:13)
                    #611    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:934:7)
                    #612    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:7)
                    (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
                    
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
navigation_rail_sample % flutter analyze
Analyzing navigation_rail_sample...                                     
No issues found! (ran in 1.8s)
```

```
navigation_rail_sample % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.0.1 20B29 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] Connected device (3 available)
• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @HeavenOSK 
I came this few days back, I can still reproduce in latest `stable` and `master`

<details> 
<summary>flutter doctor -v</summary> 

```bash
PS C:\Users\Taha\AndroidStudioProjects> flutterm doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.122, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.1.0-11.0.pre.122 at C:\Users\Taha\Code\flutter_master
    • Framework revision 8a1204f0b6 (11 hours ago), 2021-03-04 23:34:03 -0500
    • Engine revision 299eb3e710
    • Dart version 2.13.0 (build 2.13.0-104.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0
[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.72
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.81
• No issues found!
PS C:\Users\Taha\AndroidStudioProjects>
```

```bash
PS C:\Users\Taha\AndroidStudioProjects> flutterm doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.122, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.1.0-11.0.pre.122 at C:\Users\Taha\Code\flutter_master
    • Framework revision 8a1204f0b6 (11 hours ago), 2021-03-04 23:34:03 -0500
    • Engine revision 299eb3e710
    • Dart version 2.13.0 (build 2.13.0-104.0.dev)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0
[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.72
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.81
• No issues found!
PS C:\Users\Taha\AndroidStudioProjects>
```

</details>

Thanks for filing the issue!

**Comment by HeavenOSK** [comment]
You're welcome. Thank you for confirming the reproduction in latest🙏
