### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Invalid type for "path": null

### ISSUE THREAD

**Issue by Anukul59** [flutter/flutter#77372]
## Command
```
flutter create newapp
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Invalid type for "path": null
```
#0      FileSystem.getPath (package:file/src/interface/file_system.dart:160:7)
#1      LocalFileSystem.directory (package:file/src/backends/local/local_file_system.dart:23:41)
#2      ErrorHandlingFileSystem.directory (package:flutter_tools/src/base/error_handling_io.dart:118:24)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:290:21)
<asynchronous suspension>
#4      Template.fromName (package:flutter_tools/src/template.dart:75:32)
<asynchronous suspension>
#5      CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:380:31)
<asynchronous suspension>
#6      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:23)
<asynchronous suspension>
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:31)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 2.0.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.1 at /home/orion/snap/flutter/common/flutter
    • Framework revision c5a4b4029c (21 hours ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/orion/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/orion/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/orion/Desktop/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.72

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
@Anukul59 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/56811
Follow-up there for updates. Closing this as duplicate.
