### ISSUE TITLE
[WEB] Finished with error: Unable to connect to Chrome debug port #5305

### ISSUE THREAD

**Issue by kuro7766** [flutter/flutter#77450]
I have not changed any thing of this project for nearly a month and now it can't run any more.

Here is error message
```
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Finished with error: Unable to connect to Chrome debug port: 50318
 FormatException: Unexpected character (at character 1)
<html>
^
```

flutter doctor
 ```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.27.0-4.0.pre, on Microsoft Windows [Version 10.0.18363.1379], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
[√] Proxy Configuration
[√] Connected device (3 available)

! Doctor found issues in 1 category.
```

**Comment by kuro7766** [comment]
flutter run --verbose
```
E:\code\flutter\flutter_app_km2>flutter run --verbose
[  +67 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +54 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[   +1 ms] executing: [D:\flutter/] git tag --points-at f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[  +38 ms] Exit code 0 from: git tag --points-at f8cd24de95b16b5a1ce6ebc0716154271fbf6252
[        ] 1.27.0-4.0.pre
[  +36 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [D:\flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git://github.com/flutter/flutter.git
[  +59 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +57 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] executing: D:\androidSDK\platform-tools\adb.exe devices -l
[  +34 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Multiple devices found:
[  +17 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1379]
[   +1 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.190
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.81
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+3715 ms] 2
[  +14 ms] Skipping pub get: version match.
[  +96 ms] Generating E:\code\flutter\flutter_app_km2\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +88 ms] Launching lib\main.dart on Chrome in debug mode...
[ +147 ms] Updating assets
[  +59 ms] Waiting for connection from debug service on Chrome...
[  +76 ms] <- reset
[   +5 ms] D:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
D:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\flutter\bin\cache\flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\1\AppData\Local\Temp\flutter_tools.927b8e5b\flutter_tool.db0bdd7d\app.dill --libraries-spec
file:///D:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages E:\code\flutter\flutter_app_km2\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\1\AppData\Local\Temp\flutter_tools.927b8e5b\flutter_tools.5ab5e9e7 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///D:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+13099 ms] Waiting for connection from debug service on Chrome... (completed in 13.2s)
[   +1 ms] Synced 29.2MB.
[        ] <- accept
[        ] Caching compiled dill
[ +171 ms] Using 正在现有的浏览器会话中打开。

[+2506 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:52866/devtools/browser/43b77190-4a2f-4f0d-99a2-980bfcd35e88
[ +208 ms] DwdsInjector: Received request for entrypoint at http://localhost:52825/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[   +8 ms] MetadataProvider: Loaded debug metadata (no sound null safety)
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:52825/main_module.bootstrap.js
[+3340 ms] "flutter run" took 23,765ms.
[   +4 ms] Unable to connect to Chrome debug port: 52866
            FormatException: Unexpected character (at character 1)
           <html>
           ^
           
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:365:9)
           <asynchronous suspension>
           #2      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:135:17)
           <asynchronous suspension>
           #3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:524:9)
           <asynchronous suspension>
           #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:113:24)
           <asynchronous suspension>
           
           
[ +252 ms] ensureAnalyticsSent: 251ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +51 ms] Shutdown hooks complete
[        ] exiting with code 1

```

**Comment by kuro7766** [comment]
I'm in China.
I find this problem is because I have set HTTP_PROXY=127.0.0.1:10809(v2ray) in my system path. I have deleted them and it works.
But by doing this, I can't use HTTP_PROXY for unity now. Is there a better solution?

**Comment by kuro7766** [comment]
What's more, I have tested that flutter will do networking before debugging web app , and I have to turn my vpn on .Otherwise it will just stuck showing a white page. Many Chinese developers have met this problem.
I have already put FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn in my system path ,it doesn't work.

**Comment by TerryFunggg** [comment]
Hi @kuro7766. Did you also put the `PUB_HOSTED_URL` in your path ? 
```shell
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```
Both setting work well in my machine, whatever ss/v2ray active or not

And I also face the same proxy problem before. Although I'm using Linux now, but I hope this solution  may help you:

what I did is that I don't put `HTTP_PROXY` in my `.bashrc/.zshrc` (or Windows is system path). Instead using alias:

```shell
alias socks="http_proxy=http://128.0.0.1:8001 \
        https_proxy=http://127.0.0.1:8001"
```
Usage:
for example if you want to gain speed of git push command:
```shell
socks git push
```
It will not affect global env setting, and you can decide which command you want to send by vpn or v2ray,etc

**Comment by kuro7766** [comment]
No , I didn't.
I put PUB_HOSTED_URL in my path and it seems working well now .just like you said.
Thank you for your reply !
