### ISSUE TITLE
Constantly failed to debug for web using VS Code

### ISSUE THREAD

**Issue by nekoto-kun** [flutter/flutter#77520]
I'm having difficulties to run a debug session for web from VS Code. Surprisingly, I can't get to debug session in a very default Flutter project. Every time I tried to run a debug session for web by using F5 directly in VS Code or through pre-configured debug mode JSON file, it fails and throwing same error to console like below:

```
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...            145,2s
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
```

Even if I run ```flutter run -d chrome``` in the integrated terminal inside VS Code, it throws the same error after waiting some time.  The Chrome instance always did come up after some time waiting, opening localhost and random port generated. But it only shows blank until the console process stops and throws above error.

I have tried to search similar issue and solution for this, but only found from past year discussion, which is need to run ```flutter clean``` then ```flutter pub cache repair```. But that didn't work for my case.

However, the command did work sometimes from Windows Terminal, but I don't prefer it since it's pretty inefficient to do hot restart in separated terminal.

## Steps to Reproduce

1. Open project in VS Code
2. Run a debug session through VS Code feature or run ```flutter run -d chrome``` through its integrated terminal.
3. Wait for 2 minutes approx., Chrome instance opened and blank until process stopped.

## Logs

<details>
<summary>Logs</summary>

```
[ +487 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +411 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +4 ms] executing: [C:\flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[ +372 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +5 ms] 2.0.1
[ +247 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +192 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[  +58 ms] stable
[ +690 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +43 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +104 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ +175 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ +102 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +34 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1050 ms] executing: C:\Android\Sdk\platform-tools\adb.exe devices -l
[ +662 ms] List of devices attached
[ +231 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ +173 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ +175 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ +199 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.     
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.     
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update. 
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update. 
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1425 ms] Skipping pub get: version match.
[ +625 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-3.0.2\
[ +223 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.2.0\
[ +398 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[ +208 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[ +208 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.3\
[  +44 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[  +89 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[ +172 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[  +30 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[ +694 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-3.0.2\
[   +8 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.2.0\
[ +165 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[  +12 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[  +79 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.3\
[  +27 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +7 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[  +11 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[  +16 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[ +158 ms] Generating D:\Github\personal_web\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +922 ms] Launching lib\main.dart on Chrome in debug mode...
[ +787 ms] Updating assets
[+1759 ms] Waiting for connection from debug service on Chrome...
[ +291 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-3.0.2\
[ +198 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.2.0\
[ +347 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[  +74 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[ +199 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.3\
[ +262 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[ +262 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[ +218 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[ +275 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[ +217 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-3.0.2\
[  +10 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.2.0\
[ +144 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[  +12 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[  +26 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.3\
[   +8 ms] Found plugin shared_preferences_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +6 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[  +37 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +7 ms] Found plugin shared_preferences_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[+1215 ms] <- reset
[  +82 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental  
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\AN~1\AppData\Local\Temp\flutter_tools.ae4e0302\flutter_tool.7db778d6\app.dill --libraries-spec
file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\Github\personal_web\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\AN~1\AppData\Local\Temp\flutter_tools.ae4e0302\flutter_tools.3570ba80 --filesystem-scheme org-dartlang-app --initialize-from-dill  
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +87 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+115746 ms] Waiting for connection from debug service on Chrome... (completed in 119,5s)
[  +84 ms] Synced 28.9MB.
[  +70 ms] <- accept
[  +29 ms] Caching compiled dill
[+7229 ms] Using Opening in existing browser session.

[+132068 ms] [CHROME]:
[+1586 ms] [CHROME]:DevTools listening on ws://127.0.0.1:50695/devtools/browser/5f2da1fa-554e-4395-923d-ce8115027a4a
[+6761 ms] DwdsInjector: Received request for entrypoint at http://localhost:50552/main_module.bootstrap.js
[ +179 ms] MetadataProvider: Loading debug metadata...
[ +193 ms] MetadataProvider: Loaded debug metadata
[ +159 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:50552/main_module.bootstrap.js
[+74397 ms] "flutter run" took 353.820ms.
[  +50 ms] Failed to establish connection with the application instance in Chrome.
           This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due toa
           firewall.
[  +69 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:542:7)
           <asynchronous suspension>
           #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:639:26)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)     
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +312 ms] ensureAnalyticsSent: 257ms
[  +18 ms] Running shutdown hooks
[   +5 ms] Shutdown hook priority 4
[  +28 ms] Shutdown hooks complete
[  +16 ms] exiting with code 1

```

```
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.844], locale id-ID)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (3 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Andre Kho\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.844]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```

VS Code Details

```
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

</details>

**Comment by TahaTesser** [comment]
Hi @nekoto-kun 
I have seen this issue few times, it doesn't happen constantly, it sometimes shows, now for the issue it doesn't reproduce again. 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-US)
    • Flutter version 2.0.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0
[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[✓] VS Code (version 1.54.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0
[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.45
• No issues found!
```

</details>

Can you constantly reproduce this?  Please try a new project `flutter create foo`

**Comment by nekoto-kun** [comment]
Have create new foo project, same result. Did twice, the first one being stuck and never opened a Chrome window.

<details><summary>Logs</summary>

```
[ +544 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +364 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +11 ms] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +6 ms] executing: [C:\flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[ +237 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +2 ms] 2.0.1
[ +296 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +190 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[   +2 ms] executing: [C:\flutter/] git ls-remote --get-url origin
[ +166 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +396 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[ +256 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +4 ms] stable
[ +544 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +19 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +388 ms] executing: C:\Android\Sdk\platform-tools\adb.exe devices -l
[ +373 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ +185 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +25 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +909 ms] executing: C:\Android\Sdk\platform-tools\adb.exe devices -l
[  +73 ms] Skipping pub get: version match.
[ +879 ms] Generating D:\Github\foo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +471 ms] List of devices attached
[ +356 ms] Launching lib\main.dart on Chrome in debug mode...
[  +69 ms] List of devices attached
[ +706 ms] Updating assets
[ +550 ms] Waiting for connection from debug service on Chrome...
[ +709 ms] <- reset
[  +78 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\ANDREK~1\AppData\Local\Temp\flutter_tools.7f2ad0ce\flutter_tool.d6a32d85\app.dill --libraries-spec
file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages D:\Github\foo\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\ANDREK~1\AppData\Local\Temp\flutter_tools.7f2ad0ce\flutter_tools.b9ecb166 --filesystem-scheme org-dartlang-app
--initialize-from-dill build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +88 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+125847 ms] Waiting for connection from debug service on Chrome... (completed in 126,6s)
[   +6 ms] Synced 29.1MB.
[   +3 ms] <- accept
[  +16 ms] Caching compiled dill
[+9397 ms] Using Opening in existing browser session.

[+1133 ms] [CHROME]:
[+2793 ms] [CHROME]:DevTools listening on ws://127.0.0.1:58474/devtools/browser/f59b6f48-94ab-4d08-8965-bba91ab73adc
[+4279 ms] DwdsInjector: Received request for entrypoint at http://localhost:58455/main_module.bootstrap.js
[ +180 ms] MetadataProvider: Loading debug metadata...
[ +118 ms] MetadataProvider: Loaded debug metadata
[  +75 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:58455/main_module.bootstrap.js
[+34613 ms] "flutter run" took 184.770ms.
[  +43 ms] Failed to establish connection with the application instance in Chrome.
           This can happen if the websocket connection used by the web tooling is unable to correctly establish a
connection, for
           example due to a firewall.
[  +19 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:542:7)
           <asynchronous suspension>
           #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:639:26)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +285 ms] ensureAnalyticsSent: 265ms
[   +7 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[  +31 ms] Shutdown hooks complete
[   +3 ms] exiting with code 1
```

</details>

**Comment by TahaTesser** [comment]
Hi @nekoto-kun 
Can you please make sure you don't have Antivirus/Firewall interfering, please make sure to whitelist/allow/disable Flutter SDK and related files and try again. https://github.com/flutter/flutter/issues/61997
Thank you

**Comment by nekoto-kun** [comment]
Hi @TahaTesser 
I think this is happened only on my own laptop. I have tried debug using an office PC and found no problem (the exception only shown once at first run). The PC anyway, is more current and performant in specs than my laptop. Both running Windows 10 with only Windows Security as the sole antivirus and no altered configuration/firewall/anything that might interfere Flutter SDK. Both also have latest Chrome browser, latest Flutter SDK, but only in the PC I can get the web debug session up and running relatively fast (less than a minute) and works well.
I have tried days to debug web in my laptop, with and without protection at all, and still no luck after waiting hours unless I debug for other platform (mobile and Windows).

**Comment by TahaTesser** [comment]
@nekoto-kun 
Could be Windows NT,  what Windows your PC has? Can you please switch the network connection?

**Comment by nekoto-kun** [comment]
It's running Windows 10 Pro build 20H2 64-bit. I have tried debug as Windows app and Android (VS Code debug and Terminal), up and running without problem.

**Comment by TahaTesser** [comment]
Hi @nekoto-kun 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`
Also make sure you've updated VS Code Flutter plugin
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
