### ISSUE TITLE
Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.

### ISSUE THREAD

**Issue by Wizzel1** [flutter/flutter#77542]
I am getting this error when running a Tweensequence as staggered animation: 

**Another exception was thrown: 'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.**

## Steps to Reproduce

Create a new project and copy this to your main.dart file : 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: ExampleScreen(),
    );
  }
}

class ExampleScreen extends StatefulWidget {
  const ExampleScreen({Key key}) : super(key: key);

  @override
  _ExampleScreenState createState() => _ExampleScreenState();
}

class _ExampleScreenState extends State<ExampleScreen>
    with TickerProviderStateMixin {
  Animation<Offset> titleOffset;
  AnimationController _editAnimController;

  @override
  void initState() {
    super.initState();
    _editAnimController = AnimationController(
        duration: const Duration(milliseconds: 2000), vsync: this)
      ..repeat(reverse: false);

    titleOffset = TweenSequence<Offset>([
      TweenSequenceItem(
          tween: Tween<Offset>(begin: Offset(0, 0), end: Offset(0.02, 0.0)),
          weight: 50.0),
      TweenSequenceItem(
          tween: Tween<Offset>(begin: Offset(0.02, 0.0), end: Offset(0, 0)),
          weight: 50.0)
    ]).animate(
      CurvedAnimation(
        parent: _editAnimController,
        curve: Interval(
          0.1,
          0.5,
          curve: Curves.elasticInOut,
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _editAnimController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AnimatedBuilder(
          animation: titleOffset,
          builder: (context, child) {
            return SlideTransition(position: titleOffset, child: TextField());
          }),
    );
  }
}
```

**Expected results:** 
A working animation (I want to use the same animationController for multiple tweensequences, I only included one for testing purpose)

**Actual results:** 
Another exception was thrown: 'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale de-DE)
    • Flutter version 2.0.1 at C:\src\flutter\flutter
    • Framework revision c5a4b4029c (3 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Christian\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.1)
    • VS Code at C:\Users\Christian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • HUAWEI VNS L31 (mobile)     • FUH7N17213001418 • android-arm64  • Android 7.0 (API 24)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome           • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)                  • edge             • web-javascript • Microsoft Edge 88.0.705.81

```

</details>

**Comment by darshankawar** [comment]
Thanks for reporting this @Wizzel1. The error seems to be coming from `tween_sequence.dart`:

```
@override
  T transform(double t) {
    assert(t >= 0.0 && t <= 1.0);
```

<details>
<summary>crash log</summary>

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================
I/zygote  (28565): Do partial code cache collection, code=29KB, data=30KB
I/zygote  (28565): After code cache collection, code=29KB, data=30KB
I/zygote  (28565): Increasing code cache capacity to 128KB

======== Exception caught by scheduler library =====================================================
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/tween_sequence.dart': Failed assertion: line 82 pos 12: 't >= 0.0 && t <= 1.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      TweenSequence.transform (package:flutter/src/animation/tween_sequence.dart:82:12)
#3      Animatable.evaluate (package:flutter/src/animation/tween.dart:53:46)
#4      _AnimatedEvaluation.value (package:flutter/src/animation/tween.dart:87:31)
#5      _AnimatedEvaluation.toString (package:flutter/src/animation/tween.dart:91:46)
#6      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2740:60)
...
====================================================================================================

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-10.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision cc9b78fc5c (11 days ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.


```

</details>

**Comment by Wizzel1** [comment]
Thanks for taking care of this @darshankawar 
Can you give me a rough estimation of when I can expect this to get fixed? During March maybe?

**Comment by Wizzel1** [comment]
Any updates on this?

**Comment by Wizzel1** [comment]
Ok so I figured out that the Problem was the elasticInOut Animationcurve which animates out of the range 0..1 at some point.
