### ISSUE TITLE
[shared_preferences] Exception whenever i try to write to sharedpreferences

### ISSUE THREAD

**Issue by KzumO36** [flutter/flutter#77550]
I have upgraded to flutter 2, upgraded all packages to null safety, got to upgrade gradle to 3.5.0 in order to make the app working again. I migrated to the new embedding as well. Its all working now, excepts the shared preferences package. 

Whenever my app is trying to set a value, it throws an exception:

```
E/flutter (12224): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@a3c3344 rejected from java.util.concurrent.ThreadPoolExecutor@dd8bc2d[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0], null, java.util.concurrent.RejectedExecutionException: Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@a3c3344 rejected from java.util.concurrent.ThreadPoolExecutor@dd8bc2d[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
E/flutter (12224): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/flutter (12224): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/flutter (12224): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/flutter (12224): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.commitAsync(:137)
E/flutter (12224): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.onMethodCall(:96)
E/flutter (12224): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:233)
E/flutter (12224): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:85)
 
E/flutter (12224): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:818)
E/flutter (12224): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (12224): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (12224): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (12224): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/flutter (12224): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12224): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/flutter (12224): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (12224): )
E/flutter (12224): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:581
E/flutter (12224): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter (12224): <asynchronous suspension>
E/flutter (12224): #2      MethodChannelSharedPreferencesStore.setValue
package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:30
E/flutter (12224): <asynchronous suspension>
E/flutter (12224):
```

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19041.804], locale de-DE)
    • Flutter version 2.0.0 at C:\src\flutter
    • Framework revision 60bd88df91 (4 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Fuhrberg\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.0)
    • VS Code at C:\Users\xx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • ONEPLUS A6013 (mobile) • 95a75628 • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 88.0.705.81
```

</details>

**Comment by nt4f04uNd** [comment]
looks like there's already an issue that tracks this bug https://github.com/flutter/flutter/issues/77155

**Comment by darshankawar** [comment]
@KzumO36 
This certainly looks similar to https://github.com/flutter/flutter/issues/77155. There's a [solution](https://github.com/flutter/flutter/issues/77155#issuecomment-790422002) mentioned in it that you may try and see if it works for you. If not, please follow-up in that issue.
Closing from here as duplicate. If you disagree, write in comments and I'll reopen it.
