### ISSUE TITLE
[tool_crash] flutter build ipa fails with FileSystemException

### ISSUE THREAD

**Issue by eliabieri** [flutter/flutter#77571]
## command

flutter build ipa --analyze-size --build-number=24

## exception

FileSystemException: FileSystemException: Directory listing failed, path = 'build/ios/Release-iphoneos/' (OS Error: No such file or directory, errno = 2)

```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:278:57)
<asynchronous suspension>
#5      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:111:50)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#19     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.2 20D80 darwin-arm, locale en-CH)
    • Flutter version 2.0.1 at /Users/eliabieri/git/flutter/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eliabieri/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • B336ECD5-6A6D-4924-922F-5DA468C09897 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 88.0.4324.192
    ! Error: WG is not connected. Xcode will continue when WG is connected. (code -13)

• No issues found!
```

**Comment by pedromassangocode** [comment]
Similar to https://github.com/flutter/flutter/issues/48859. Please see https://github.com/flutter/flutter/issues/48859#issuecomment-588393937 for a workaround.

**Comment by eliabieri** [comment]
@pedromassango `flutter build ipa` does not support providing a custom path.

**Comment by jmagman** [comment]
@eliabieri Can you attach logs from `flutter build ipa --analyze-size --build-number=24 --verbose`?  It's large so you'll need to attach it.

**Comment by eliabieri** [comment]
[flutter_01.log](https://github.com/flutter/flutter/files/6134367/flutter_01.log)
[flutter_build_ipa.log](https://github.com/flutter/flutter/files/6134368/flutter_bild_ipa.log)

**Comment by jmagman** [comment]
@eliabieri you attached logs for a different crash, which I filed for you separately at https://github.com/flutter/flutter/issues/78231.

Are you able to reproduce the originally reported `Directory listing failed` crash?

**Comment by eliabieri** [comment]
I currently have a broken Ruby setup, which I have to fix first (M1 Mac). As soon as my setup is back up I will try to reproduce the exact crash described initially and upload new logs.

**Comment by jmagman** [comment]
@eliabieri It's okay, I was able to reproduce locally, so you don't need to attach the logs again.
