### ISSUE TITLE
Input asserts while keyboard is dismissed

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#776]
Stocks:
1. Tap search icon.
2. Tap floating action button.

Input field goes red, asserts appear in console.

**Comment by abarth** [comment]
I can repro this issue.

**Comment by abarth** [comment]
```
01-22 17:21:54.115  9515  9544 I flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
01-22 17:21:54.115  9515  9544 I flutter : Exception caught while building Input-[GlobalKey ringtone field]
01-22 17:21:54.116  9515  9544 I flutter : 'packages/flutter/src/widgets/focus.dart': Failed assertion: line 110: '"If you have more than one focusable widget, then you should put them inside a Focus." == true' is not true.
01-22 17:21:54.116  9515  9544 I flutter : Stack trace:
01-22 17:21:54.155  9515  9544 I flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
01-22 17:21:54.155  9515  9544 I flutter : #1      Focus.at.<anonymous closure> (packages/flutter/src/widgets/focus.dart:110)
01-22 17:21:54.155  9515  9544 I flutter : #2      Focus.at (packages/flutter/src/widgets/focus.dart:105)
01-22 17:21:54.155  9515  9544 I flutter : #3      InputState.buildContent (packages/flutter/src/material/input.dart:101)
01-22 17:21:54.155  9515  9544 I flutter : #4      ScrollableState.build (packages/flutter/src/widgets/scrollable.dart:199)
01-22 17:21:54.155  9515  9544 I flutter : #5      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1159)
01-22 17:21:54.155  9515  9544 I flutter : #6      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1100)
```

Looks like we're missing a `Focus` widget somewhere.

**Comment by Hixie** [comment]
That's disconcerting. Pretty sure PageRoute introduces a Focus.

**Comment by abarth** [comment]
I think it's related to the juggling page route does with offstage and ignorepointer, etc.  It could also be that my test was flawed because I was re-using global keys or something.

**Comment by abarth** [comment]
```
01-26 12:54:54.187 15931 15960 I flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
01-26 12:54:54.189 15931 15960 I flutter : Exception caught while building Input-[GlobalKey 873196590]
01-26 12:54:54.190 15931 15960 I flutter : 'packages/mojo/src/codec.dart': Failed assertion: line 221: '!interface.isBound' is not true.
01-26 12:54:54.190 15931 15960 I flutter : Stack trace:
01-26 12:54:54.221 15931 15960 I flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
01-26 12:54:54.221 15931 15960 I flutter : #1      Encoder.encodeInterface (packages/mojo/src/codec.dart:221)
01-26 12:54:54.221 15931 15960 I flutter : #2      _KeyboardServiceShowParams.encode (packages/mojo_services/keyboard/keyboard.mojom.dart:948)
01-26 12:54:54.221 15931 15960 I flutter : #3      Struct.serializeWithHeader (packages/mojo/src/struct.dart:23)
01-26 12:54:54.221 15931 15960 I flutter : #4      Proxy.sendMessage (packages/mojo/src/proxy.dart:86)
01-26 12:54:54.221 15931 15960 I flutter : #5      _KeyboardServiceProxyCalls.show (packages/mojo_services/keyboard/keyboard.mojom.dart:1642)
01-26 12:54:54.221 15931 15960 I flutter : #6      KeyboardHandle.KeyboardHandle._show (packages/flutter/src/services/keyboard.dart:71)
01-26 12:54:54.221 15931 15960 I flutter : #7      Keyboard.show (packages/flutter/src/services/keyboard.dart:48)
01-26 12:54:54.222 15931 15960 I flutter : #8      _InputState._attachOrDetachKeyboard (packages/flutter/src/material/input.dart:106)
01-26 12:54:54.222 15931 15960 I flutter : #9      _InputState.build (packages/flutter/src/material/input.dart:137)
```
