### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /home/anjali/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub, OS error code: 2

### ISSUE THREAD

**Issue by vcse59** [flutter/flutter#77641]
## Steps to Reproduce
1. Execute flutter doctor (steps are mentioned here : https://flutter.dev/docs/get-started/install/linux)

## Logs

```bash
Running "flutter pub get" in flutter_tools...                           

Oops; flutter has exited unexpectedly: "ProcessException: No such file or
directory
  Command: /home/anjali/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub
  --verbosity=warning get --no-precompile".
A crash report has been written to
/home/anjali/workspace/carwash/ui/flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+No+such+file+or+directory%0A++Command%3A+%2Fhome%2Fanjali%2Fsnap%2Fflutter%2Fcommon%2Fflutter%2Fbin%2Fcache%2Fdart-sdk%2Fbin%2Fpub+--verbosity%3Dwarning+get+--no-precompile

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing
the issue template. Thank you!
https://git.io/JqLWv

<details>
Ubuntu 18.04

<!-- If possible, paste the output of running `flutter doctor -v` here. -->

flutter doctor -v
Running "flutter pub get" in flutter_tools...                           

Oops; flutter has exited unexpectedly: "ProcessException: No such file or
directory
  Command: /home/anjali/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub
  --verbosity=warning get --no-precompile".
A crash report has been written to
/home/anjali/workspace/carwash/ui/flutter_04.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+No+such+file+or+directory%0A++Command%3A+%2Fhome%2Fanjali%2Fsnap%2Fflutter%2Fcommon%2Fflutter%2Fbin%2Fcache%2Fdart-sdk%2Fbin%2Fpub+--verbosity%3Dwarning+get+--no-precompile

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing
the issue template. Thank you!
https://git.io/JqLWv
```

</details>

**Comment by TahaTesser** [comment]
### Output from report

## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /home/anjali/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:39:20)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:282:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:222:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/cache.dart:774:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
```
```
[✓] Flutter (Channel beta, 2.0.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.1 at /home/anjali/snap/flutter/common/flutter
    • Framework revision c5a4b4029c (4 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc1)
    • Android SDK at /home/anjali/Android/Sdk
    • Platform android-30, build-tools 31.0.0-rc1
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 8.1.0 (API 27) (emulator)
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 89.0.4389.82

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.
