### ISSUE TITLE
`flutter run --release` stuck when building for iOS: "library not found for -lPods-Runner"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7766]
My `flutter run --release` for my iPhone is stuck at:

```
~/Code/hello_cupertino[master*] $ flutter run --release
Launching lib/main.dart on flutter 6s in release mode...
Traceback (most recent call last):
  File "/tmp/fruitstrap_d83d5bc53967baa0ee18626ba87b6254b2ab5418.py", line 35, in run_command
    lldb.target.Launch(lldb.SBLaunchInfo(shlex.split(args[1] and args[1] or '--enable-dart-profiling')), error)
IndexError: list index out of range
```

Any ideas?

```
~/Code/hello_cupertino[master*] $ flutter --version
Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision a0f0c42fe3 (64 minutes ago) • 2017-01-31 14:48:48
Engine • revision 2d54edf0f9
Tools • Dart 1.22.0-dev.9.1
```

and

```
~/Code/hello_cupertino[master*] $ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/sethladd/Code/flutter
    • Framework revision a0f0c42fe3 (64 minutes ago), 2017-01-31 14:48:48
    • Engine revision 2d54edf0f9
    • Tools Dart version 1.22.0-dev.9.1

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/sethladd/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.9166.22
    • Flutter plugin version 0.1.4

[✓] Connected devices
    • flutter 6s • d83d5bc53967baa0ee18626ba87b6254b2ab5418 • ios • iOS 10.1.1 (14B100)
```

**Comment by sethladd** [comment]
Hm, apparently when you don't have all the necessary signing mumbo jumbo under the General tab of the Project build settings, you can hang `flutter run` like this.

For those folks also running into this:

* I somehow opened up the project settings for my app.
* Then I selected "Runner" under "TARGETS".
* Then I selected "General" from the horizontal list of options (general, capabilities, etc)
* Then I found "Signing" and ensured I unchecked "automatically manage signing"
* Then I found "signing (debug)" and ensured my "provisioning profile" was correct.
* I did the same for "Signing (Release)"

Now I get this error:

```
Ld /Users/sethladd/Code/hello_cupertino/build/ios/Debug-iphoneos/Runner.app/Runner normal arm64
    cd /Users/sethladd/Code/hello_cupertino/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH=""
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -L/Users/sethladd/Code/hello_cupertino/build/ios/Debug-iphoneos -L/Users/sethladd/Code/hello_cupertino/ios/Flutter -F/Users/sethladd/Code/hello_cupertino/build/ios/Debug-iphoneos -F/Users/sethladd/Code/hello_cupertino/ios/Flutter -filelist /Users/sethladd/Code/hello_cupertino/build/ios/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/sethladd/Code/hello_cupertino/build/ios/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -framework Flutter -lPods-Runner -Xlinker -dependency_info -Xlinker /Users/sethladd/Code/hello_cupertino/build/ios/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat -o /Users/sethladd/Code/hello_cupertino/build/ios/Debug-iphoneos/Runner.app/Runner

ld: library not found for -lPods-Runner
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sethladd** [comment]
cc @cbracken have you heard of this issue?

**Comment by sethladd** [comment]
Update:

I create a new Flutter project (via flutter create), and when I try to run that on my iPhone, I see this error:

```
~/tmp/foobar $ flutter run
Launching lib/main.dart on flutter 6s in debug mode...
Traceback (most recent call last):
  File "/tmp/fruitstrap_d83d5bc53967baa0ee18626ba87b6254b2ab5418.py", line 35, in run_command
    lldb.target.Launch(lldb.SBLaunchInfo(shlex.split(args[1] and args[1] or '--enable-dart-profiling --enable-checked-mode')), error)
IndexError: list index out of range
Exception from flutter run: Exception: Timeout while attempting to retrieve Uri for Observatory
package:flutter_tools/src/base/common.dart 30         throwToolExit
package:flutter_tools/src/protocol_discovery.dart 55  ProtocolDiscovery.nextUri.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                            _Future.timeout
package:flutter_tools/src/protocol_discovery.dart 53  ProtocolDiscovery.nextUri.<async>
===== asynchronous gap ===========================
dart:async                                            Future.Future.microtask
package:flutter_tools/src/protocol_discovery.dart     ProtocolDiscovery.nextUri
package:flutter_tools/src/ios/devices.dart 271        IOSDevice.startApp.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/ios/mac.dart 180            buildXcodeProject.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 145       runAsync.<async>
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter_tools/src/ios/devices.dart            IOSDevice.startApp
package:flutter_tools/src/run_hot.dart 161            HotRunner._run.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 156    ResidentRunner.startEchoingDeviceLog.<async>
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                HotRunner._run
package:flutter_tools/src/run_hot.dart 78             HotRunner.run.<fn>
package:stack_trace                                   Chain.capture
package:flutter_tools/src/run_hot.dart 77             HotRunner.run
package:flutter_tools/src/commands/run.dart 278       RunCommand.runCommand.<async>

Exception from flutter run: Exception: Timeout while attempting to retrieve Uri for Diagnostic server
package:flutter_tools/src/base/common.dart 30         throwToolExit
package:flutter_tools/src/protocol_discovery.dart 55  ProtocolDiscovery.nextUri.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                            _Future.timeout
package:flutter_tools/src/protocol_discovery.dart 53  ProtocolDiscovery.nextUri.<async>
===== asynchronous gap ===========================
dart:async                                            Future.Future.microtask
package:flutter_tools/src/protocol_discovery.dart     ProtocolDiscovery.nextUri
package:flutter_tools/src/ios/devices.dart 274        IOSDevice.startApp.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/ios/mac.dart 180            buildXcodeProject.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 145       runAsync.<async>
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter_tools/src/ios/devices.dart            IOSDevice.startApp
package:flutter_tools/src/run_hot.dart 161            HotRunner._run.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 156    ResidentRunner.startEchoingDeviceLog.<async>
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                HotRunner._run
package:flutter_tools/src/run_hot.dart 78             HotRunner.run.<fn>
package:stack_trace                                   Chain.capture
package:flutter_tools/src/run_hot.dart 77             HotRunner.run
package:flutter_tools/src/commands/run.dart 278       RunCommand.runCommand.<async>
```

**Comment by cbracken** [comment]
I haven't seen it but neither of those are helpful error messages and the first one should be relatively straightforward to catch.

Some ref material in case someone gets to it before me:
For signing, the settings Xcode (8.1) cares about in the .pbxproj are `DEVELOPMENT_TEAM` and `PROVISIONING_PROFILE`. There's some checking on `PRODUCT_BUNDLE_IDENTIFIER` as well though I'll have to look up the details.

The second error appears to be a separate issue. A quick search of our issues looks turns up #6576 and #5398, which suggests that opening the `.xcworkspace` and building from there seems to help, though obviously that shouldn't be a required part of our workflow.

**Comment by sethladd** [comment]
Closing this, because even a brand-new Flutter app doesn't run. I might reopen this, but for now: one thing at a time.

Closing as "not fixed, but there may be a bigger issue"

See https://github.com/flutter/flutter/issues/7767 for the "a brand-new flutter app doesn't run on my ios device"

**Comment by Elatech** [comment]
Doh... sorry guys. Restarted Xcode and reopened my project by .workspace (not .project) file. Everything started to archive again. :-/
