### ISSUE TITLE
New flutter app fails to run on iOS device, "Timeout while attempting to retrieve Uri for Observatory"

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7767]
Created a new flutter app via `flutter create`. Attempted to run it on my iOS device with `flutter run`. App never started on my device. Saw this error on the console:

```
~/tmp/foobar $ flutter run
Launching lib/main.dart on flutter 6s in debug mode...
Traceback (most recent call last):
  File "/tmp/fruitstrap_d83d5bc53967baa0ee18626ba87b6254b2ab5418.py", line 35, in run_command
    lldb.target.Launch(lldb.SBLaunchInfo(shlex.split(args[1] and args[1] or '--enable-dart-profiling --enable-checked-mode')), error)
IndexError: list index out of range
Exception from flutter run: Exception: Timeout while attempting to retrieve Uri for Observatory
package:flutter_tools/src/base/common.dart 30         throwToolExit
package:flutter_tools/src/protocol_discovery.dart 55  ProtocolDiscovery.nextUri.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                            _Future.timeout
package:flutter_tools/src/protocol_discovery.dart 53  ProtocolDiscovery.nextUri.<async>
===== asynchronous gap ===========================
dart:async                                            Future.Future.microtask
package:flutter_tools/src/protocol_discovery.dart     ProtocolDiscovery.nextUri
package:flutter_tools/src/ios/devices.dart 271        IOSDevice.startApp.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/ios/mac.dart 180            buildXcodeProject.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 145       runAsync.<async>
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter_tools/src/ios/devices.dart            IOSDevice.startApp
package:flutter_tools/src/run_hot.dart 161            HotRunner._run.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 156    ResidentRunner.startEchoingDeviceLog.<async>
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                HotRunner._run
package:flutter_tools/src/run_hot.dart 78             HotRunner.run.<fn>
package:stack_trace                                   Chain.capture
package:flutter_tools/src/run_hot.dart 77             HotRunner.run
package:flutter_tools/src/commands/run.dart 278       RunCommand.runCommand.<async>

Exception from flutter run: Exception: Timeout while attempting to retrieve Uri for Diagnostic server
package:flutter_tools/src/base/common.dart 30         throwToolExit
package:flutter_tools/src/protocol_discovery.dart 55  ProtocolDiscovery.nextUri.<async>.<fn>
===== asynchronous gap ===========================
dart:async                                            _Future.timeout
package:flutter_tools/src/protocol_discovery.dart 53  ProtocolDiscovery.nextUri.<async>
===== asynchronous gap ===========================
dart:async                                            Future.Future.microtask
package:flutter_tools/src/protocol_discovery.dart     ProtocolDiscovery.nextUri
package:flutter_tools/src/ios/devices.dart 274        IOSDevice.startApp.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/ios/mac.dart 180            buildXcodeProject.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 145       runAsync.<async>
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter_tools/src/ios/devices.dart            IOSDevice.startApp
package:flutter_tools/src/run_hot.dart 161            HotRunner._run.<async>
dart:async                                            _SyncCompleter.complete
package:flutter_tools/src/resident_runner.dart 156    ResidentRunner.startEchoingDeviceLog.<async>
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter_tools/src/run_hot.dart                HotRunner._run
package:flutter_tools/src/run_hot.dart 78             HotRunner.run.<fn>
package:stack_trace                                   Chain.capture
package:flutter_tools/src/run_hot.dart 77             HotRunner.run
package:flutter_tools/src/commands/run.dart 278       RunCommand.runCommand.<async>
```

Version:

```
~/tmp/foobar $ flutter --version
Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision a0f0c42fe3 (2 hours ago) • 2017-01-31 14:48:48
Engine • revision 2d54edf0f9
Tools • Dart 1.22.0-dev.9.1
```

**Comment by sethladd** [comment]
Bumped to "today". I feel like this is a regression that we want to address? @cbracken can repro this, too.

**Comment by eseidelGoogle** [comment]
That looks like a CocoaPods error?  @collinjackson?

I was able to run flutter_gallery on a Google-dev-cert-using iPod Touch from XCode just now.  I'm also not able to run from `flutter run` due to some (likely different and possibly google-mac specific) python error.

**Comment by eseidelGoogle** [comment]
@cbracken @xster and @chinmaygarde are our iOS ninjas.

**Comment by eseidelGoogle** [comment]
I could be wrong. I don't know what fruitstrap is.  I assumed it was part of cocoapods?

**Comment by sethladd** [comment]
TIL about Fruitstrap: https://github.com/ghughes/fruitstrap

Also, and here's a weird thing. No matter what flutter project I try to run for iOS device, it always fails with the same tmp file /tmp/fruitstrap_d83d5bc53967baa0ee18626ba87b6254b2ab5418.py

I find it weird that all my flutter projects try to run what looks to be a generated tmp file. Maybe that's a clue?

**Comment by eseidelGoogle** [comment]
This is my error https://gist.github.com/eseidelGoogle/66ac11d769945730c40f16d7ccde4cd2

**Comment by cbracken** [comment]
Taking a look at this right now.

**Comment by eseidelGoogle** [comment]
My error looks like this: https://forum.ionicframework.com/t/ionic-run-ios-python-error/58760

**Comment by cbracken** [comment]
Just to clarify, the error I was able to repro yesterday was from #7766. Having trouble repro-ing this one.

Can you confirm the repro steps you took were:
1. `flutter create foobar`
2. `cd foobar`
3. `flutter run` (no simulator open and an iOS device connected)

When I run those I get a code signing error:
  https://gist.github.com/cbracken/57513b082d9f0915ccbf091439b96c5b
which is expected, but which we should definitely follow up with more useful instructions on how to remedy.

If I then `open ios/Runner.xcodeproj`, select the project manager in the sidebar, click `Runner`, then set a team under `General` in the project settings, followed by another `flutter run`, I get a correct launch.

Can you provide the output of a `flutter doctor` run?

In my case:
```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 3a43fc88b6 (10 hours ago), 2017-01-31 23:32:10
    • Engine revision 2d54edf0f9
    • Tools Dart version 1.22.0-dev.9.1

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/cbracken/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002

[-] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • the Doom Melon • 956919950000126a7f5aaf03cbd5fbc18ac75e65 • ios • iOS 10.2.1 (14D27)
```

**Comment by sethladd** [comment]
@cbracken so, you don't see something like

```
Launching lib/main.dart on flutter 6s in debug mode...
Traceback (most recent call last):
  File "/tmp/fruitstrap_d83d5bc53967baa0ee18626ba87b6254b2ab5418.py", line 35, in run_command
    lldb.target.Launch(lldb.SBLaunchInfo(shlex.split(args[1] and args[1] or '--enable-dart-profiling --enable-checked-mode')), error)
IndexError: list index out of range
```

?

Do we know who/what creates that `/tmp/fruitstrap_d83d5bc53967baa0ee18626ba87b6254b2ab5418.py` file? I'm wondering if that's stale for some reason.

**Comment by sethladd** [comment]
```
~/tmp/foobar $ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/sethladd/Code/flutter
    • Framework revision a0f0c42fe3 (19 hours ago), 2017-01-31 14:48:48
    • Engine revision 2d54edf0f9
    • Tools Dart version 1.22.0-dev.9.1

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/sethladd/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.9166.22
    • Flutter plugin version 0.1.4

[✓] Connected devices
    • flutter 6s • d83d5bc53967baa0ee18626ba87b6254b2ab5418 • ios • iOS 10.2.1 (14D27)
```

**Comment by eseidelGoogle** [comment]
Looks like the hash in the `/tmp/fruitstrap_HASH.py` name is your device id.  Hence why it's shared between projects.

**Comment by cbracken** [comment]
@sethladd correct; not seeing the fruitstrap error.

Looks like this is created by `ios-deploy`:

```
% strings ios-deploy|grep fruit
    connect_url = internal_dict['fruitstrap_connect_url']
    device_app = internal_dict['fruitstrap_device_app']
    script fruitstrap_device_app="{device_app}"
    script fruitstrap_connect_url="connect://127.0.0.1:{device_port}"
/tmp/%@/fruitstrap_
fruitstrap_
/tmp/%@/fruitstrap-lldb-prep-cmds-
```

**Comment by sethladd** [comment]
```
~/Code/hello_cupertino[master*] $ ios-deploy --version
1.7.0
```

Do we need to add this check to `flutter doctor` ?

**Comment by cbracken** [comment]
Can you run a `brew update` brew `upgrade` and let me know if moving to 1.9.1 fixes it for you? And yet, a min version check in `doctor` sounds in order.

**Comment by sethladd** [comment]
No problem. (/me is now recompiling ffmpeg, so stand by... :)

**Comment by xster** [comment]
I had ios-deploy 1.9.0 and also can't reproduce this fruitstrap error

**Comment by eseidelGoogle** [comment]
My ios-deploy is 1.7.0.  I'm seeing a fruitstrap error, not sure if we have more than one. :)

**Comment by sethladd** [comment]
With @cbracken 's help, we upgraded my ios-deploy to 1.9.1 and I can launch apps now! woohoo!

My ios-deploy was in some stuck state, and brew was telling me a very weird message:

```
~/Code/hello_cupertino[master*] $ brew upgrade ios-deploy
Error: flutter/flutter/ios-deploy 888621 already installed
```

So, I did this:

```
brew uninstall ios-deploy
brew install ios-deploy
ios-deploy --version   # 1.9.1
```

If both @eseidelGoogle and I were seeing errors with 1.7.0, I suggest we update `flutter doctor` to inform our users to go grab 1.9.0+ of ios-deploy.

**Comment by cbracken** [comment]
@eseidelGoogle can you dump the info of `brew info ios-deploy` for the record?

**Comment by sethladd** [comment]
I'm going to close this with a resolution of: "Please upgrade your ios-deploy to 1.9.0+" and I'll open a new issue to ask `flutter doctor` to error if you have < 1.9.0 installed.

Thank you all for your help!!

**Comment by eseidelGoogle** [comment]
We used to have our own brew for ios deploy: https://github.com/flutter/homebrew-flutter/blob/master/ios-deploy.rb  I wonder if I installed that and that's related to this in any way?

**Comment by eseidelGoogle** [comment]
Yeah, looks like I have ios-deploy installed in `/usr/local/bin/ios-deploy` but not via brew.  I wonder if I got it in some funny way.  Updating via brew now.

**Comment by eseidelGoogle** [comment]
Mine is still busted, (likely due to missing python's six module), but it's probably a separate bug.

**Comment by eseidelGoogle** [comment]
Yup, `sudo easy_install six` fixed my issue.  Unclear if that's needed for `flutter doctor` too.

**Comment by sethladd** [comment]
Did you not have "six" installed, or was it out of date?

(if "six" is a direct dependency from our tools, we probably do want to prompt users to upgrade it via flutter doctor)

**Comment by eseidelGoogle** [comment]
I did not have python's `six` installed it seems.  I've definitely installed it before, so it may have been some quirk of Google macs.  Unclear if we'll need to check for that dependency ourselves.

**Comment by cbracken** [comment]
It just so happens I've got a non-Google mac sitting right beside me. Will take a quick look.

**Comment by eseidelGoogle** [comment]
I suspect I hit this: https://bugs.swift.org/browse/SR-1061 by accidentally installing a custom python at some point (or maybe my Google mac did).  Six is presumably a slightly non-standard package which apple ships as part of their llvm dependencies and their tools assume are installed, but for my flavor of python it wasn't.  This could be command-line only if my PATH is set to include my local python but my Xcode environment isn't.  At least that's my theory.

**Comment by xster** [comment]
For record I hit this today on a non-Google machine with a non-Google physical phone. 

ios-deploy and six were both up to date.

Doing `flutter upgrade` gave

```
[✓] Flutter (on Mac OS X 10.12.3 16D32, channel mountainview)
    • Flutter at /Users/xiao/Development/flutter
    • Framework revision 8306afb797 (56 minutes ago), 2017-03-30 11:24:10
    • Engine revision 61fc1d6e31
    • Tools Dart version 1.23.0-dev.9.0

[✓] Host Executable Compatibility
    • Downloaded executables execute on host

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/xiao/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Users/xiao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    ✗ libimobiledevice is incompatible with the installed Xcode version. To update, run:
      brew update
      brew uninstall --ignore-dependencies libimobiledevice
      brew install --HEAD libimobiledevice
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.8651
    • Flutter plugin version 0.1.5

[✓] Connected devices
    •  • ca81e3fe859531cba8c9c769947d269ce48dcae7 • ios • iOS  ()
```

Running the given instructions got things working again. Yay for the doctor.

**Comment by bestK** [comment]
```
sudo easy_install six 
```
Work for me .lol
