### ISSUE TITLE
Error with SliverList

### ISSUE THREAD

**Issue by ctkcoding** [flutter/flutter#77675]
1. My code:
https://github.com/BlueBubblesApp/BlueBubbles-Android-App/compare/master...ctkcoding:feature/pinnedConvoGrid?expand=1#diff-dec882f1ace622d201133b9342fd655be0675790ca9fca0756cc21964d80cc8e

2. The error thrown in AndroidStudio which asks me to create a bug report:

======== Exception caught by widgets library =======================================================
The following assertion was thrown building StreamBuilder<List<Chat>>(state: _StreamBuilderBaseState<List<Chat>, AsyncSnapshot<List<Chat>>>#138fd):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3602 pos 12: 'child._parent == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  StreamBuilder<List<Chat>> file:///Users/theodore/code/vscode/BlueBubbles-Android-App/lib/layouts/conversation_list/conversation_list.dart:416:13
When the exception was thrown, this was the stack: 
#2      Element.deactivateChild (package:flutter/src/widgets/framework.dart:3602:12)
#3      Element.updateChild (package:flutter/src/widgets/framework.dart:3322:9)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
The relevant error-causing widget was: 
  StreamBuilder<List<Chat>> file:///Users/theodore/code/vscode/BlueBubbles-Android-App/lib/layouts/conversation_list/conversation_list.dart:416:13

**Comment by ctkcoding** [comment]
let me copy the error here again, but the error log specifically says that either there should be better documentation from the creators if it isn’t a framework issue and specifically says to raise it here on GitHub:

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md
