### ISSUE TITLE
CrossAxisAlignment.stretch an exception was thrown

### ISSUE THREAD

**Issue by HaceraI** [flutter/flutter#77686]
I'm following [https://flutter.dev/docs/codelabs/layout-basics#crossaxisalignment-property](https://flutter.dev/docs/codelabs/layout-basics#crossaxisalignment-property) learned flutter, but I encountered a problem. I used 'crossaxisalignment: in my ide CrossAxisAlignment.stretch `An exception was thrown.

Source code is very simple, you can directly copy to any dart class:
<details>
  <summary>source code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(LayoutLearPage());

class LayoutLearPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Basic Flutter layout concepts',
      theme: ThemeData.from(colorScheme: ColorScheme.light()),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Basic Flutter layout concepts'),
          leading: IconButton(
            icon: const Icon(Icons.arrow_back),
            onPressed: () {
              print('clicked Arrow Back');
            },
          ),
        ),
        body: LayoutLear(),
      ),
    );
  }
}

class LayoutLear extends StatefulWidget {
  @override
  _LayoutLearState createState() => _LayoutLearState();
}

class _LayoutLearState extends State<LayoutLear> {
  bool _isRow = true;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextButton(
          style: ButtonStyle(
            foregroundColor: MaterialStateProperty.all<Color>(Colors.blue),
          ),
          onPressed: () {
            setState(() {
              this._isRow = !this._isRow;
            });
          },
          child: Text('switch to${_isRow ? 'Column' : 'Row'}'),
        ),
        _isRow ? Row(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          // Try to change.
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            BlueBox(50, 50),
            BlueBox(100, 100),
            BlueBox(50, 50),
          ],
        ) : Column(
          mainAxisSize: MainAxisSize.max,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            BlueBox(50, 50),
            BlueBox(100,100),
            BlueBox(50, 50),
          ],
        )
      ],
    );
  }
}

class BlueBox extends StatelessWidget {
  final double width;
  final double height;

  BlueBox(this.width, this.height);

  @override
  Widget build(BuildContext context) {
    return Container(
      width: width,
      height: height,
      // margin: EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: Colors.blue,
        border: Border.all()
      ),
    );
  }
}
```

</details>
<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18363.1411], locale zh-CN)
    • Flutter version 2.0.1 at U:\flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\12631\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\12631\AppData\Local\Android\Sdk
    • Java binary at: U:\JetBrains\Tools\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at U:\JetBrains\Tools\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at U:\IntelliJ IDEA 2019.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at U:\IntelliJ IDEA 202.6109.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at U:\JetBrains\Tools\apps\IDEA-U\ch-0\211.6222.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\12631\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!


```

</details>
<details>
  <summary>error logs</summary>

```
Performing hot reload...
Syncing files to device Android SDK built for x86...

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
BoxConstraints forces an infinite height.

These invalid constraints were provided to RenderConstrainedBox's layout() function by the following function, which probably computed the invalid constraints in question:
  ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
The offending constraints were: BoxConstraints(0.0<=w<=Infinity, h=Infinity)
The relevant error-causing widget was: 
  Row file:///U:/MyStudyDirectory/AndroidStudioProjects/flutter_app/lib/flutter_dev_lear/layout_lear.dart:51:18
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:517:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:561:21)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:565:6)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1684:24)
#4      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
...
The following RenderObject was being processed when the exception was fired: RenderFlex#087d5 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...  size: MISSING
...  direction: horizontal
...  mainAxisAlignment: spaceAround
...  mainAxisSize: max
...  crossAxisAlignment: stretch
...  textDirection: ltr
...  verticalDirection: down
RenderObject: RenderFlex#087d5 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: spaceAround
  mainAxisSize: max
  crossAxisAlignment: stretch
  textDirection: ltr
  verticalDirection: down
...  child 1: RenderConstrainedBox#6e147 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...    constraints: MISSING
...    size: MISSING
...    additionalConstraints: BoxConstraints(w=50.0, h=50.0)
...    child: RenderDecoratedBox#7c123 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      decoration: BoxDecoration
...        color: MaterialColor(primary value: Color(0xff2196f3))
...        border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...      configuration: ImageConfiguration(bundle: PlatformAssetBundle#12850(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...      child: RenderPadding#4c8d8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets.all(1.0)
...        textDirection: ltr
...  child 2: RenderConstrainedBox#6e1df NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...    constraints: MISSING
...    size: MISSING
...    additionalConstraints: BoxConstraints(w=100.0, h=100.0)
...    child: RenderDecoratedBox#e7ee9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      decoration: BoxDecoration
...        color: MaterialColor(primary value: Color(0xff2196f3))
...        border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...      configuration: ImageConfiguration(bundle: PlatformAssetBundle#12850(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...      child: RenderPadding#293a3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets.all(1.0)
...        textDirection: ltr
...  child 3: RenderConstrainedBox#c6d7e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...    constraints: MISSING
...    size: MISSING
...    additionalConstraints: BoxConstraints(w=50.0, h=50.0)
...    child: RenderDecoratedBox#0f0af NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      decoration: BoxDecoration
...        color: MaterialColor(primary value: Color(0xff2196f3))
...        border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...      configuration: ImageConfiguration(bundle: PlatformAssetBundle#12850(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...      child: RenderPadding#a9746 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        padding: EdgeInsets.all(1.0)
...        textDirection: ltr
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderFlex#087d5 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Column file:///U:/MyStudyDirectory/AndroidStudioProjects/flutter_app/lib/flutter_dev_lear/layout_lear.dart:38:12
====================================================================================================
Reloaded 1 of 548 libraries in 1,555ms.

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderFlex#24221 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Scaffold file:///U:/MyStudyDirectory/AndroidStudioProjects/flutter_app/lib/flutter_dev_lear/layout_lear.dart:12:13
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1940:12)
#3      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:172:18)
#4      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:925:7)
#5      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
#6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:407:14)
...
The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#51e02 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, h=781.1)
...  size: Size(392.7, 781.1)
RenderObject: RenderCustomMultiChildLayoutBox#51e02 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=392.7, h=781.1)
  size: Size(392.7, 781.1)
...  child 1: RenderFlex#24221 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...    constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=662.9)
...    size: MISSING
...    direction: vertical
...    mainAxisAlignment: start
...    mainAxisSize: max
...    crossAxisAlignment: center
...    verticalDirection: down
...    child 1: RenderSemanticsAnnotations#2ebf5 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...      semantic boundary
...      size: Size(122.0, 48.0)
...      child: _RenderInputPadding#99f8c relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...        size: Size(122.0, 48.0)
...        child: RenderConstrainedBox#42094 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: offset=Offset(0.0, 6.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...          size: Size(122.0, 36.0)
...          additionalConstraints: BoxConstraints(64.0<=w<=Infinity, 36.0<=h<=Infinity)
...    child 2: RenderFlex#087d5 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...      size: MISSING
...      direction: horizontal
...      mainAxisAlignment: spaceAround
...      mainAxisSize: max
...      crossAxisAlignment: stretch
...      textDirection: ltr
...      verticalDirection: down
...      child 1: RenderConstrainedBox#6e147 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        additionalConstraints: BoxConstraints(w=50.0, h=50.0)
...        child: RenderDecoratedBox#7c123 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          decoration: BoxDecoration
...            color: MaterialColor(primary value: Color(0xff2196f3))
...            border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#12850(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...      child 2: RenderConstrainedBox#6e1df NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        additionalConstraints: BoxConstraints(w=100.0, h=100.0)
...        child: RenderDecoratedBox#e7ee9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          decoration: BoxDecoration
...            color: MaterialColor(primary value: Color(0xff2196f3))
...            border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#12850(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...      child 3: RenderConstrainedBox#c6d7e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        additionalConstraints: BoxConstraints(w=50.0, h=50.0)
...        child: RenderDecoratedBox#0f0af NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          decoration: BoxDecoration
...            color: MaterialColor(primary value: Color(0xff2196f3))
...            border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#12850(), devicePixelRatio: 2.8, locale: en_US, textDirection: TextDirection.ltr, platform: android)
...  child 2: RenderConstrainedBox#0f155 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar (can use size)
...    constraints: BoxConstraints(w=392.7, 0.0<=h<=781.1)
...    size: Size(392.7, 118.2)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=118.2)
...    child: RenderSemanticsAnnotations#c3bd4 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=392.7, 0.0<=h<=118.2)
...      semantic boundary
...      size: Size(392.7, 118.2)
...      child: RenderAnnotatedRegion<SystemUiOverlayStyle>#e6029 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=392.7, 0.0<=h<=118.2)
...        size: Size(392.7, 118.2)
...        child: RenderPhysicalModel#b49a7 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=392.7, 0.0<=h<=118.2)
...          layer: PhysicalModelLayer#a0ab2
...            engine layer: PhysicalShapeEngineLayer#8dab6
...            elevation: 4.0
...            color: Color(0xff6200ee)
...          size: Size(392.7, 118.2)
...          elevation: 4.0
...          color: Color(0xff6200ee)
...          shadowColor: Color(0xff6200ee)
...          shape: BoxShape.rectangle
...          borderRadius: BorderRadius.zero
...  child 3: RenderStack#a7797 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(376.7, 765.1); id=_ScaffoldSlot.floatingActionButton (can use size)
...    constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=781.1)
...    size: Size(0.0, 0.0)
...    alignment: Alignment.centerRight
...    textDirection: ltr
...    fit: loose
...    child 1: RenderTransform#59d22 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=781.1)
...      size: Size(0.0, 0.0)
...      transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...      origin: null
...      alignment: Alignment.center
...      textDirection: ltr
...      transformHitTests: true
...      child: RenderTransform#0dd0a relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=781.1)
...        size: Size(0.0, 0.0)
...        transform matrix: [0] 0.7,0.7,0.0,0.0
[1] -0.7,0.7,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: Alignment.center
...        textDirection: ltr
...        transformHitTests: true
====================================================================================================

```

```

```

```
```

</details>

**Comment by HaceraI** [comment]
My problem is that I didn't check the log output carefully.

`BoxConstraints forces an infinite height.`
