### ISSUE TITLE
I have a problem with shared_preferences 

### ISSUE THREAD

**Issue by barangungor** [flutter/flutter#77711]
Hey i'm using shared_preferences in my app but i get errors after upgrade to 2.0 and migrate null safety. 

> **E/MethodChannel#plugins.flutter.io/shared_preferences(27469): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(27469): java.util.concurrent.RejectedExecutionException: Task io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl$1@c703561 rejected from java.util.concurrent.ThreadPoolExecutor@6107886[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
E/MethodChannel#plugins.flutter.io/shared_preferences(27469): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/MethodChannel#plugins.flutter.io/shared_preferences(27469): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/MethodChannel#plugins.flutter.io/shared_preferences(27469): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/MethodChannel#plugins.flutter.io/shared_preferences(27469): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.commitAsync(MethodCallHandlerImpl.java:137)
E/MethodChannel#plugins.flutter.io/shared_preferences(27469): 	at io.flutter.plugins.sharedpreferences.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:96)
E/MethodChannel#plugins.flutter.io/shared_preferences(27469): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)**

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/77155
