### ISSUE TITLE
Support for Cygwin

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#77725]
## Use case

I'm using Cygwin to be able to use zsh on Windows (I don't want to use WSL).

Everything works fine, except flutter, because the `flutter` script doesn't recognize Cygwin (looking at the source, it detects `MINGW.*`)

When running `flutter` on this configuration, I get an error. Running `flutter.bat` works fine, so an alias of `flutter` to `flutter.bat` also works fine:

![image](https://user-images.githubusercontent.com/379339/110516984-05531b80-80e9-11eb-95ff-c54e7942fb7d.png)

This is Windows Terminal 1.6 (the new fancy terminal) with cygwin (latest) and zsh, on a Windows 10 machine.

## Proposal

Add suport to detect Cygwin in addition to Mingw. I don't know bash script syntax to do it myself, but `$(uname -s)` returns `CYGWIN_NT-10.0`.

**Comment by jonahwilliams** [comment]
I was able to get it to run by adding the following change to bin/flutter:

```
+# If we're on Windows, invoke the batch script instead, to get proper locking.
 if [[ $OS =~ MINGW.* ]]; then
-  # If we're on Windows, invoke the batch script instead, to get proper locking.
+  exec "${BIN_DIR}/flutter.bat" "$@"
+fi
+
+if [[ $OS =~ CYGWIN.* ]]; then
   exec "${BIN_DIR}/flutter.bat" "$@"
 fi
 ```
 
 However, the tool immediately crashes when trying to read a file:
 
 ```
 $ flutter
Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: The handle is invalid.
, errno = 6)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:286:15)
#2      _rootRunUnary (dart:async/zone.dart:1362:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#8      _StreamController._add (dart:async/stream_controller.dart:607:7)
#9      _StreamController.add (dart:async/stream_controller.dart:554:5)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:136:17)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:269:5)
#12     _StdSink.write (dart:io/stdio.dart:315:11)
#13     Stdio._stdioWrite.<anonymous closure> (package:flutter_tools/src/base/io.dart:351:12)
#14     Stdio._stdioWrite.<anonymous closure> (package:flutter_tools/src/base/io.dart:350:22)
#15     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#16     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
#17     _rootRun (dart:async/zone.dart:1354:13)
#18     _CustomZone.run (dart:async/zone.dart:1258:19)
#19     _runZoned (dart:async/zone.dart:1789:10)
#20     runZonedGuarded (dart:async/zone.dart:1777:12)
#21     runZoned (dart:async/zone.dart:1708:12)
#22     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#23     Stdio._stdioWrite (package:flutter_tools/src/base/io.dart:350:5)
#24     Stdio.stdoutWrite (package:flutter_tools/src/base/io.dart:336:7)
#25     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:424:12)
#26     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:327:5)
#27     printStatus (package:flutter_tools/src/globals.dart:169:10)
#28     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:423
:7)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/f
lutter_command_runner.dart:257:11)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#31     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runne
r.dart:239:5)
<asynchronous suspension>
#32     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

**Comment by JCKodel** [comment]
> I was able to get it to run by adding the following change to bin/flutter:
> ...

After copying your change, I had only one issue running flutter:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel @u, 2.0.1, on Microsoft Windows [Version 10.0.19042.844], locale pt-BR)
```

Notice that cygwin git.exe can't run some required flutter commands (hence, the current channel is displayed as `@u`).

To fix that, you need to install Windows git (from git scm site) and then delete the git.exe on the `C:\cygwin64\bin` folder.

After that, with your fix on `flutter`, it works fine:

```
 jckod@SGC  /  flutter doctor                                                                                                                                                                                              ✔  13:16:14
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.844], locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1.0)
[✓] VS Code (version 1.54.2)
[✓] Connected device (2 available)

• No issues found!
```

Not sure why you are getting that error.

**Comment by jonahwilliams** [comment]
Interesting,  taking suggestions on an easy way to detect cygwin git :)
