### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by cymok** [flutter/flutter#77759]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Expanded(flex: 1):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5022 pos 16: 'child is! ParentDataElement<ParentData>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Expanded file:///C:/Workspaces/mypj/xx_page.dart:89:23
When the exception was thrown, this was the stack: 
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5022:16)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4681:14)
#4      ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:5026:5)
#5      ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:5070:5)
#6      ProxyElement.updated (package:flutter/src/widgets/framework.dart:4997:5)
...
====================================================================================================
```

Code:
```
    var listWidget = _model.list
        .map((item) => Container(
              width: double.infinity,
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(10),
              ),
              padding: EdgeInsets.all(12),
              margin: EdgeInsets.only(top: 10, left: 10, right: 10),
              child: Column(
                mainAxisSize: MainAxisSize.max,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('锁库:${item.lockSumNum}件/${item.applyDay}小时'),
                            Text('创建时间:${item.createTime}'),
                          ],
                        ),
                      ),
                      Text('${item.auditStatusName}'),
                    ],
                  ),
                  Row(
                    children: [
                      Image.network(
                        '${item.headImage.first}',
                        width: 80,
                        height: 80,
                        fit: BoxFit.cover,
                      ),
                      SizedBox(width: 10),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Expanded(child: Text('${item.goodName}')),
                              ],
                            ),
                            SizedBox(height: 20),
                            Text('锁库下单件数: ${item.placeNum}件'),
                            SizedBox(height: 20),
                            Row(
                              children: [
                                Text('￥${item.price.toStringCutDecimal(2)}'),
                                Expanded(child: getButtonsWidget(item)),
                              ],
                            )
                          ],
                        ),
                      )
                    ],
                  )
                ],
              ),
            ))
        .toList();
```

**Comment by darshankawar** [comment]
@cymok 
See this similar issue comment and check if helps to resolve your issue.
If not, provide `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the exception.

**Comment by cymok** [comment]
```
Expanded(child: Expanded(xxx))
```
Should be caused by this problem.
