### ISSUE TITLE
cloud_firestore package not working in Flutter 2 web

### ISSUE THREAD

**Issue by jerryhamby** [flutter/flutter#77823]
I building a very simple web app and I tried to add the cloud_firestore package and I'm getting this error.
BTW, firebase_core package is working in the app. I tried both 1.0.0 and 1.0.1 cloud_firestore.

Need some advice, I really need to connect to firestore.

The breakpoint stops here:
Future<void> main() async {
  registerPlugins(webPluginRegistrar);
  await ui.webOnlyInitializePlatform();
  if (entrypoint.main is _UnaryFunction) {
    return (entrypoint.main as _UnaryFunction)(<String>[]);
  }
  return (entrypoint.main as _NullaryFunction)();
}

TypeError: Cannot read property 'app' of undefined
at Object.app$ [as app] (http://localhost:51831/packages/firebase_core_web/src/interop/core.dart.lib.js:42:101)
at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:51831/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:988:64)
at Function.registerWith (http://localhost:51831/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:842:73)
at Object.registerPlugins (http://localhost:51831/packages/gentelella_flutter/generated_plugin_registrant.dart.lib.js:28:46)

**Comment by jerryhamby** [comment]
Just tried cloud_firestore_web 1.0.1 and got the same error:
I have also included the GoogleService-info.plist file.

TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:54320/packages/firebase_core_web/src/interop/core.dart.lib.js:42:101)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:54320/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:988:64)
    at Function.registerWith (http://localhost:54320/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:842:73)
    at Object.registerPlugins (http://localhost:54320/packages/gentelella_flutter/generated_plugin_registrant.dart.lib.js:28:46)

**Comment by iapicca** [comment]
@jerryhamby 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by jerryhamby** [comment]
I posted the problem here:
(flutterfire) cloud_firestore_web package not working in Flutter 2 web #5301

**Comment by darshankawar** [comment]
Closing from here. Please follow-up in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues/5301
