### ISSUE TITLE
Flutter app crash with 'io.flutter.embedding.engine.loader.FlutterLoader$1.call' error.

### ISSUE THREAD

**Issue by Naografix** [flutter/flutter#77821]
Hello hello!

Well, this post is going to be complicated to write because I really have no idea how it happened. I just have a return of Crashlytics. I don’t know where it comes from, or why... so I’m writing this message to find a solution.
On 1500 users, just one got this error on LGE Nexus 5X Android 8.1.0 no-rooted.

# Flutter Doctor
<details>
  <summary>Click to expand</summary>

> [√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [version 10.0.19041.804], locale fr-FR)
>     • Flutter version 1.22.5 at C:\Users\Naografix\Documents\Flutter
>     • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
>     • Engine revision ae90085a84
>     • Dart version 2.10.4
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Users\Naografix\AppData\Local\Android\Sdk
>     • Platform android-30, build-tools 29.0.2
>     • ANDROID_HOME = C:\Users\Naografix\AppData\Local\Android\Sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     X Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
> 
> [√] Android Studio (version 3.4)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 39.0.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [√] VS Code (version 1.54.1)
>     • VS Code at C:\Users\Naografix\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.20.0
> 
> [√] Connected device (1 available)
>     • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
> 
> ! Doctor found issues in 1 category.
</details>

Well, this is all errors I got (4 categories):

# FlutterLoader.java – line 20
<details>
  <summary>Click to expand</summary>
  
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.REPLACED_NAME/com.REPLACED_NAME.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.MYAPP_REPLACED_NAME-Cb_wehgXY-n3GRvQ_9a_RQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.MYAPP_REPLACED_NAME-Cb_wehgXY-n3GRvQ_9a_RQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

-------------

Caused by java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.REPLACED_NAME-Cb_wehgXY-n3GRvQ_9a_RQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.REPLACED_NAME-Cb_wehgXY-n3GRvQ_9a_RQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
       at io.flutter.embedding.engine.loader.FlutterLoader.a(FlutterLoader.java:284)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:160)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:16)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:110)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.a(FlutterActivityAndFragmentDelegate.java:7)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:22)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

-------------

Caused by java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.REPLACED_NAME-Cb_wehgXY-n3GRvQ_9a_RQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.REPLACED_NAME-Cb_wehgXY-n3GRvQ_9a_RQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
       at java.util.concurrent.FutureTask.report(FutureTask.java:123)
       at java.util.concurrent.FutureTask.get(FutureTask.java:193)
       at io.flutter.embedding.engine.loader.FlutterLoader.a(FlutterLoader.java:23)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:160)
       at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:16)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:110)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.a(FlutterActivityAndFragmentDelegate.java:7)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:22)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

-------------

Caused by java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.REPLACED_NAME-Cb_wehgXY-n3GRvQ_9a_RQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.REPLACED_NAME-Cb_wehgXY-n3GRvQ_9a_RQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:20)
       at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

+34 threads...
</details>

# ActivityThread.java – line 2731
<details>
  <summary>Click to expand</summary>

```
    Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.REPLACED_NAME/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

-------------

    Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(SignInHubActivity.java:27)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
+32 threads...
</details>

# InAppBrowserActivity.java line 16
<details>
  <summary>Click to expand</summary>

```
    Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.REPLACED_NAME/com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

-------------

    Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity.onCreate(InAppBrowserActivity.java:16)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

+32 threads...
</details>

# ChromeCustomTabsActivity.java line 18
<details>
  <summary>Click to expand</summary>
```
    Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.REPLACED_NAME/com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

-------------

    Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
       at com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity.onCreate(ChromeCustomTabsActivity.java:18)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

+32 threads...
</details>

As you can see, excepted the first 'category', others have a similar problem

**Comment by darshankawar** [comment]
@Naografix 
Looking at the logs you shared:

`FlutterLoader.java:` has this exception common: 

`java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError:`.  Refer [this](https://github.com/flutter/flutter/issues/64697#issuecomment-683007555) issue comment for further reference which explains how this is not an issue in Flutter.

`ActivityThread.java:` has this exception common:

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.REPLACED_NAME/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference`. which indicates it could be a code implementation issue as you are trying to pass object to a null 

`InAppBrowserActivity.java:`

`com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference`


`ChromeCustomTabsActivity.java`

`com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference at`

points to the 3rd party plugin `in_appwebview`. So I'd suggest you to follow-up in plugin owner's repo:

I am going ahead and closing this as not an issue in Flutter.  Also `On 1500 users, just one got this error `, makes it very very less percentage of occurence. If you get this issue frequently, write in comments and I'll reopen to address it.

**Comment by Naografix** [comment]
> @Naografix
> Looking at the logs you shared:
> 
> `FlutterLoader.java:` has this exception common:
> 
> `java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError:`. Refer [this](https://github.com/flutter/flutter/issues/64697#issuecomment-683007555) issue comment for further reference which explains how this is not an issue in Flutter.
> 
> `ActivityThread.java:` has this exception common:
> 
> `Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.REPLACED_NAME/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference`. which indicates it could be a code implementation issue as you are trying to pass object to a null
> 
> `InAppBrowserActivity.java:`
> 
> `com.pichillilorenzo.flutter_inappwebview.InAppBrowser.InAppBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference`
> 
> `ChromeCustomTabsActivity.java`
> 
> `com.pichillilorenzo.flutter_inappwebview.ChromeCustomTabs.ChromeCustomTabsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference at`
> 
> points to the 3rd party plugin `in_appwebview`. So I'd suggest you to follow-up in plugin owner's repo:
> 
> I am going ahead and closing this as not an issue in Flutter. Also `On 1500 users, just one got this error `, makes it very very less percentage of occurence. If you get this issue frequently, write in comments and I'll reopen to address it.

Thank you for your reply. I don't use this plugin so... It will be complicated :/
I think it's a sub référence.
