### ISSUE TITLE
google_maps_flutter OutOfMemoryError when locking the phone with the map view opened

### ISSUE THREAD

**Issue by oligazar** [flutter/flutter#77938]
## Steps to Reproduce

1. Open the map screen
2. Polylines on the map are updating in real time (from Firebase)
3. Lock the phone
4. Reopen the app after approx. 15 mins
5. App is crashing

<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 216 byte allocation with 20520 free bytes and 18KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 105644032 bytes)
       at java.util.ArrayList.<init>(ArrayList.java:166)
       at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:398)
       at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
       at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:410)
       at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
       at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:400)
       at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
       at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:410)
       at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
       at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:48)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:197)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
[✓] Flutter (Channel master, 1.26.0-13.0.pre.50, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
    • Flutter version 1.26.0-13.0.pre.50 at /Users/Admin/flutter
    • Framework revision 2a188eeca3 (8 weeks ago), 2021-01-17 19:27:00 -0800
    • Engine revision 609036f2bf
    • Dart version 2.12.0 (build 2.12.0-236.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/Admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/Admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • F8ADCD40-2C76-460B-B9B2-D40CD756460B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 80.0.3987.163

• No issues found!

```

</details>

It only happens if I lock the phone's screen with the map screen is opened. If any additional info is required please let me know

**Comment by darshankawar** [comment]
@oligazar 
You seem to be on older version of Master. Please upgrade to latest (2.1.0) and try again to see if issue still persists or not.
If yes, provide updated `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), without 3rd party plugins (ex: Firebase) that we can directly use and verify this issue.
Thanks.

**Comment by oligazar** [comment]
@darshankawar After updating to ` Flutter (Channel master, 2.1.0-13.0.pre.86, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)` the map screen stopped crashing for most of the devices. But there's still a problem for subset of Samsung devices (Galaxy Tab A, Galaxy Tab A 7). For them map always crashing. It still `OutOfMemoryError`. 

Any ideas?

**Comment by darshankawar** [comment]
> @oligazar
> You seem to be on older version of Master. Please upgrade to latest (2.1.0) and try again to see if issue still persists or not.
> If yes, provide updated `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), without 3rd party plugins (ex: Firebase) that we can directly use and verify this issue.
> Thanks.

Would need above details to properly address this issue. @oligazar

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
