### ISSUE TITLE
'flutter test' fails on docker image but succeeds locally

### ISSUE THREAD

**Issue by BassamxMednini** [flutter/flutter#77971]
I've a couple of test files in my flutter project and running this files with `flutter test` locally works without any error messages. But running the same tests on a docker image ending with the following error message:

    The following StateError was thrown running a test:
    Bad state: No element

I'm not sure whether the cause of this error message is in the project itself or maybe something is wrong with my `Dockerfile`

    FROM ubuntu:16.04
    
    ENV FLUTTER_VERSION="1.22.6"
    
    RUN apt update -y
    RUN apt install -y \ 
      git \ 
      wget \ 
      curl \ 
      unzip \ 
      lcov \ 
      lib32stdc++6
    
    ENV FLUTTER_ROOT="/opt/flutter"
    RUN git clone --branch $FLUTTER_VERSION --depth=1 https://github.com/flutter/flutter "${FLUTTER_ROOT}"
    ENV PATH="${FLUTTER_ROOT}/bin:${PATH}"
    
    RUN flutter config  --no-analytics
    RUN flutter precache
    RUN yes "y" | flutter doctor --android-licenses
    RUN flutter doctor -v
    ENV PATH $PATH:/flutter/bin/cache/dart-sdk/bin:/flutter/bin
    
    WORKDIR /opt/app
    COPY . .
    
    RUN flutter pub get
    RUN flutter test

**Comment by christopherfujino** [comment]
Not sure if this is the cause, but you should definitely NOT do a shallow clone of Flutter, the tooling depends on a full git history being present.

I would need to see a stacktrace to be able to diagnose the StateError. Was there a stacktrace and/or any other logs?

**Comment by BassamxMednini** [comment]
<details>
  <summary>Stacktrace</summary>

```
#14 34.63 ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
#14 34.63 The following StateError was thrown running a test:
#14 34.63 Bad state: No element
#14 34.63 
#14 34.63 When the exception was thrown, this was the stack:
#14 34.63 #0      Iterable.first (dart:core/iterable.dart:524:7)
#14 34.63 #1      _FirstFinder.filter.<anonymous closure> (package:flutter_test/src/finders.dart:463:28)
#14 34.63 #2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:165:25)
#14 34.63 #3      Iterable.length (dart:core/iterable.dart:429:15)
#14 34.63 #4      _FindsWidgetMatcher.describeMismatch (package:flutter_test/src/matchers.dart:667:41)
#14 34.63 #5      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:85:13)
#14 34.63 #6      _expect (package:test_api/src/frontend/expect.dart:150:17)
#14 34.63 #7      expect (package:test_api/src/frontend/expect.dart:59:3)
#14 34.63 #8      expect (package:flutter_test/src/widget_tester.dart:431:3)
#14 34.63 #9      main.<anonymous closure> (file:///opt/app/test/habit_add_test.dart:61:5)
#14 34.63 <asynchronous suspension>
#14 34.63 #10     main.<anonymous closure> (file:///opt/app/test/habit_add_test.dart)
#14 34.63 #11     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
#14 34.63 <asynchronous suspension>
#14 34.63 #12     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#14 34.63 #13     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
#14 34.63 <asynchronous suspension>
#14 34.63 #16     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#14 34.63 #17     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#14 34.63 #18     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#14 34.63 #23     withClock (package:clock/src/default.dart:48:10)
#14 34.63 #24     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#14 34.63 #29     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#14 34.63 #30     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#14 34.63 #31     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#14 34.63 #32     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
#14 34.63 <asynchronous suspension>
#14 34.63 #33     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#14 34.63 #38     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#14 34.63 #39     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#14 34.63 #44     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#14 34.63 #45     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
#14 34.63 <asynchronous suspension>
#14 34.63 #46     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#14 34.63 #51     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#14 34.63 #52     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#14 34.63 #53     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#14 34.63 #60     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#14 34.63 #61     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#14 34.63 #62     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#14 34.63 #67     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#14 34.63 #68     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#14 34.63 #86     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#14 34.63 #87     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#14 34.63 #91     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#14 34.63 #125    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#14 34.63 #133    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#14 34.63 #134    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#14 34.63 #144    _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#14 34.63 #153    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#14 34.63 #154    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#14 34.63 (elided 111 frames from dart:async and package:stack_trace)
```
</details>

`but you should definitely NOT do a shallow clone of Flutter, the tooling depends on a full git history being present.`

Alright, but even running the test files with [cirrusci/flutter](https://hub.docker.com/r/cirrusci/flutter/tags?page=1&ordering=last_updated) on GitLab CI/CD results with the same error message.

**Comment by christopherfujino** [comment]
@BassamxMednini when you say that the test passes locally, is that the same linux host as the docker container is running in? If so, could you provide a minimal reproducible test that I can try locally?

**Comment by TahaTesser** [comment]
Hi @BassamxMednini 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by TahaTesser** [comment]
Hi @BassamxMednini 
Please just.a create sample test for the issue to reproduce, it doesn't have to the all the tests
Thank you

**Comment by christopherfujino** [comment]
@BassamxMednini it seems like you're using docker on mac. We would definitely need a minimal reproduction of this to verify if the problem is a) running from linux, b) running on docker on mac, c) something else, such as timing dependent, and docker on mac is just slower.

**Comment by BassamxMednini** [comment]
I'll close it for now. Creating a reproduction test file seems to be (curiously) really hard. I'll reopen the issue once I've something.
