### ISSUE TITLE
`Mac_ios stable flutter_gallery__transition_perf_e2e_ios` failing with exception "Bad state: No element"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#78047]
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20stable%20flutter_gallery__transition_perf_e2e_ios/3

```
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-03-11 14:06:35.574133-0800 Flutter Gallery[465:35682] flutter: (The following exception is now available via WidgetTester.takeException:)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-03-11 14:06:35.574622-0800 Flutter Gallery[465:35682] flutter: Bad state: No element
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-03-11 14:06:35.577772-0800 Flutter Gallery[465:35682] flutter: #0      ListMixin.reduce (dart:collection/list.dart:222)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-03-11 14:06:35.579933-0800 Flutter Gallery[465:35682] flutter: #1      new FrameTimingSummarizer (package:flutter_test/src/frame_timing_summarizer.dart:46)
[flutter_gallery__transition_perf_e2e_ios] [STDOUT] stdout: 2021-03-11 14:06:35.580363-0800 Flutter Gallery[465:35682] flutter: #2      IntegrationTestWidgetsFlutterBinding.watchPerformance (package:integration_test/integration_test.dart:318)
```

**Comment by christopherfujino** [comment]
Re-run pending [here](https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20stable%20flutter_gallery__transition_perf_e2e_ios/4)

**Comment by jmagman** [comment]
Similar to https://github.com/flutter/flutter/issues/76216.

**Comment by jonahwilliams** [comment]
This might be a bug in the FrameTimingSummarizer, I'll take a look

**Comment by chinmaygarde** [comment]
@jonahwilliams Does the linked PR fix this issue?

**Comment by jonahwilliams** [comment]
Hopefully, I can close optimistically and we'll re-open if that isn't the case
