### ISSUE TITLE
[video_player] Crashing while trying to play network video.

### ISSUE THREAD

**Issue by pratikbaid3** [flutter/flutter#78052]
Demo video working fine but custom url giving the following error:

```
I/ExoPlayerImpl( 4381): Release f9a86bb [ExoPlayerLib/2.12.1] [Nord, AC2001, OnePlus, 29] [goog.exo.core]
I/ExoPlayerImpl( 4381): Init 986ee23 [ExoPlayerLib/2.12.1] [Nord, AC2001, OnePlus, 29]
E/ExoPlayerImplInternal( 4381): Playback error
E/ExoPlayerImplInternal( 4381):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 4381):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal( 4381):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 4381):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal( 4381):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 4381):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 401
E/ExoPlayerImplInternal( 4381):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
E/ExoPlayerImplInternal( 4381):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 4381):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
E/ExoPlayerImplInternal( 4381):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 4381):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 4381):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 4381):       at java.lang.Thread.run(Thread.java:919)
E/flutter ( 4381): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)
E/flutter ( 4381): 
```

Any help would be greatly appreciated

**Comment by Lafannn** [comment]
Firstly I should ask questions about player in the video player repository.
Secondary You can’t download video because you need to do authorization. How you can notice server returns 401(Unauthorized)

**Comment by nt4f04uNd** [comment]
@Lafannn official plugin issues are submitted in this repository

**Comment by pratikbaid3** [comment]
@Lafannn I guess this is the repository where we are supposed to post issues related to the video player since the package on pub.dev directs to this page. Also, the link for the video is working fine on a browser, not sure why I am getting 401 with the pluggin.

**Comment by Lafannn** [comment]
@pratikbaid3 ok, sorry I didn’t know that issues to official plugins now is submitting to this repository.

Can you provide link to the video?

**Comment by darshankawar** [comment]
@pratikbaid3 
Main error is `Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, null, null)`

Please follow-up in https://github.com/flutter/flutter/issues/75995.
Closing this as duplicate.
