### ISSUE TITLE
Expect() does not detect failures inside of testWidgets calls

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#7806]
I'd like to make sure that a widget doesn't, for example, throw an out of bounds error when it is built. With expect() from flutter_test, this doesn't appear to be possible.

For example, when I set up the following:
```
testWidgets('can handle updates to the number of tabs',
    (WidgetTester tester) async {
  var bad =
      new BadWidget();
  expect(() async {
    await tester.pumpWidget(bad);
  }, throws);
});

class BadWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    assert(false);
  }
}
```

the test fails with the result:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: throws
  Actual: <Closure: () => dynamic>
   Which: did not throw


When the exception was thrown, this was the stack:
#3      main.<anonymous closure>.<anonymous closure>.<<anonymous closure>_async_body> (///build/work/6cd116f1eb920c43bd7f2decf46f870c/exception_test.dart:38:7)
#13     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:533:16)
#14     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:370:5)
#15     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:519:24)
#21     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:517:16)
#22     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:53:50)
#23     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:121:19)
#35     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:218:3)
(elided 61 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)
```

Is some separation between the widget tester and the test runner causing the async-await to not be honored properly?

**Comment by eseidelGoogle** [comment]
@yjbanov or @Hixie would know.

**Comment by Hixie** [comment]
You want `takeException`: https://docs.flutter.io/flutter/flutter_test/TestWidgetsFlutterBinding/takeException.html
