### ISSUE TITLE
Flutter app not working when running in release/archive mode.

### ISSUE THREAD

**Issue by masonhorder** [flutter/flutter#78074]
Hello, 
So when i use my app in debug mode everything works completely fine, no errors and my tflite model runs properly. Then one day I get a support request from a user on the AppStore saying they can't get it to work even though i knew it worked for me. So then I realized it has to do with release mode:

Here is the code that is causing the issue:

```
  Future recognize(List imageList) async {
    print("recognize");
    debugString += "\nrunning model";
    final interpreter = await tfl.Interpreter.fromAsset('v3-model.tflite');
    debugString += "\n1";
    var input = imageList.reshape([1,224,224,3]);
    debugString += "\n2";
    List output = List(1*4).reshape([1,4]);
    debugString += "\n3";
    interpreter.run(input, output);
    debugString += "\n4";
    _recognition = output;
    debugString += "\n5";
    interpreter.close();
    debugString += "\nmodel done";
    // debugString += "Error: $error";
    
  }

```
Here is the output(release and debug respectively):

Release Mode:
```

flutter: scan
2021-03-12 10:55:59.159778-0800 Runner[54121:3778134] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, TfLiteModelCreate): symbol not found)
#0      DynamicLibrary.lookup (dart:ffi-patch ffi_dynamic_library_patch.dart:31)
#1      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart:11)
#2      new Model.fromBuffer (package:tflite_flutter/src/model.dart)
#3      new Interpreter.fromBuffer (package:tflite_flutter/src/interpreter.dart:90)
#4      Interpreter.fromAsset (package:tflite_flutter/src/interpreter.dart:114)
<asynchronous suspension>
#5      CameraState.recognize (package:filament_left/Screens/camera.dart:125)
<asynchronous suspension>
#6      CameraState.scanImage (package:filament_left/Screens/camera.dart:111)
<asynchronous suspension>
2021-03-12 10:55:59.739733-0800 Runner[54121:3778134] flutter: File Uploaded
2021-03-12 10:55:59.743840-0800 Runner[54121:3778214] BackgroundSession <2C5183FE-9D06-46CD-BC99-57D9C1492583> connection to background transfer daemon invalidated


Debug Mode:

flutter: scan
2021-03-12 11:36:48.821404-0800 Runner[54390:3792113] Initialized TensorFlow Lite runtime.
2021-03-12 11:36:49.571281-0800 Runner[54390:3792126] BackgroundSession <E3929BAC-B73F-4BEA-89BD-F6036AB28708> connection to background transfer daemon invalidated
2021-03-12 11:36:51.313935-0800 Runner[54390:3792113] flutter: postconvert
2021-03-12 11:36:51.314804-0800 Runner[54390:3792113] flutter: coordinate(mainly height) - height than width
2021-03-12 11:36:51.315632-0800 Runner[54390:3792113] flutter: 275.81599473953247
2021-03-12 11:36:51.316580-0800 Runner[54390:3792113] flutter: 490.3395462036133
2021-03-12 11:36:51.316995-0800 Runner[54390:3792113] flutter: coordinate(mainly width) - height than width
2021-03-12 11:36:51.317061-0800 Runner[54390:3792113] flutter: 228.4491491317749
2021-03-12 11:36:51.317102-0800 Runner[54390:3792113] flutter: 406.13182067871094
2021-03-12 11:36:51.317653-0800 Runner[54390:3792113] flutter: coordinate(mainly height) - height than width
2021-03-12 11:36:51.317861-0800 Runner[54390:3792113] flutter: 564.8450231552124
2021-03-12 11:36:51.317916-0800 Runner[54390:3792113] flutter: 1004.1689300537109
2021-03-12 11:36:51.317954-0800 Runner[54390:3792113] flutter: coordinate(mainly width) - height than width
2021-03-12 11:36:51.317989-0800 Runner[54390:3792113] flutter: 514.749641418457
2021-03-12 11:36:51.318323-0800 Runner[54390:3792113] flutter: 915.1104736328125
2021-03-12 11:36:51.318956-0800 Runner[54390:3792113] flutter: 1.76099492754787
2021-03-12 11:36:51.336338-0800 Runner[54390:3792113] flutter: File Uploaded



I believe that the error is coming from this line: Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, TfLiteModelCreate): symbol not found)


Flutter doctor:

[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en)
    • Flutter version 2.0.1 at /Users/masonhorder/flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
```

Thanks so much, Mason

**Comment by darshankawar** [comment]
@masonhorder 
What plugin are you using for tflite ? is it https://pub.dev/packages/tflite/install ?

**Comment by masonhorder** [comment]
@darshankawar it is tflite_flutter

**Comment by masonhorder** [comment]
Issue resolved by just recreating the app, just copy over the lib file and pubspec
