### ISSUE TITLE
Failed assertion: line x pos y: '!_needsLayout': is not true.

### ISSUE THREAD

**Issue by Octofoxy** [flutter/flutter#78172]
I got an error message, which asks me to file a bug report. You can find the lib folder and pubspec.yaml in the zip.

```
[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown during paint():


[39;49m
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 488 pos 12: '!_needsLayout': is not true.

[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mThe relevant error-causing widget was[39;49m
[38;5;248mSlider[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      TextPainter.width[39;49m
[38;5;244m#3      _PaddleSliderValueIndicatorPathPainter.paint[39;49m
[38;5;244m#4      PaddleSliderValueIndicatorShape.paint[39;49m
[38;5;248m#5      ThumbShape.paint[39;49m
[38;5;244m#6      _RenderSlider.paint[39;49m
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: _RenderSlider#dc1b6[39;49m
[38;5;244mRenderObject: _RenderSlider#dc1b6[39;49m
    [38;5;244mparentData: <none> (can use size)[39;49m
    [38;5;244mconstraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)[39;49m
    [38;5;244msize: Size(411.4, 48.0)[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 488 pos 12: '!_needsLayout': is not true.
[38;5;244mThe relevant error-causing widget was[39;49m
[38;5;248mSlider[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 488 pos 12: '!_needsLayout': is not true.
[38;5;244mThe relevant error-causing widget was[39;49m
[38;5;248mSlider[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 488 pos 12: '!_needsLayout': is not true.
[38;5;244mThe relevant error-causing widget was[39;49m
[38;5;248mSlider[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 488 pos 12: '!_needsLayout': is not true.
[38;5;244mThe relevant error-causing widget was[39;49m
[38;5;248mSlider[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
```

Short explanation of what you will find in the zip:
I built a slider widget, "MultiSlider", which uses the standard Flutter sliders. The widgets returns a master slider and a number of subsliders. The sum of the subsliders values can never exceed the value of the masterslider. The widget itself works fine without errors.

I also have a custom thumb button, which itself works fine and without errors on the example slider from the Flutter documentation. However, when I introduced SliderTheme() to use the custom thumb button with the Sliders contained in my MultiSlider widget, I got those errors.
[lib.zip](https://github.com/flutter/flutter/files/6137425/lib.zip)

**Comment by darshankawar** [comment]
@Octofoxy 
What version do you get this error on ? Can you provide `flutter doctor -v` ?

**Comment by Octofoxy** [comment]
@darshankawar flutter doctor -v console output below:

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.867], locale de-DE)
    • Flutter version 1.22.5 at C:\Users\Overfox\Code\flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Overfox\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\Overfox\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)`

**Comment by darshankawar** [comment]
@Octofoxy 
I see that you are on older version of Stable. Latest is 2.0.2. I suggest you to upgrade to latest and try again to see if issue persists or not.
Thanks.

**Comment by Octofoxy** [comment]
@darshankawar 
I have updated to 2.0.2 (see below). The problem still persists.

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale de-DE)`

**Comment by Octofoxy** [comment]
@darshankawar Are there any updates on this issue? It's stalling our project at the moment.

**Comment by Octofoxy** [comment]
@darshankawar It has been almost two weeks since I last heard from you. Would you please give me a quick confirmation that this bug is being actively worked on?

**Comment by darshankawar** [comment]
@Octofoxy 
Sorry for getting late to this. I was able to replicate this issue, which seems to be pointing to `Slider` widgt which somehow isn't getting the width it needs and hence throwing the render exception as below:

<details>
<summary>console error log</summary>

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:141:20
When the exception was thrown, this was the stack: 
#2      TextPainter.width (package:flutter/src/painting/text_painter.dart:497:12)
#3      _PaddleSliderValueIndicatorPathPainter.paint (package:flutter/src/material/slider_theme.dart:3094:48)
#4      PaddleSliderValueIndicatorShape.paint (package:flutter/src/material/slider_theme.dart:2853:18)
#5      ThumbShape.paint (package:int_test_demo/main.dart:220:21)
#6      _RenderSlider.paint (package:flutter/src/material/slider.dart:1446:30)
...
The following RenderObject was being processed when the exception was fired: _RenderSlider#73ee8
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
...  size: Size(428.0, 48.0)
RenderObject: _RenderSlider#73ee8
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
  size: Size(428.0, 48.0)
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.
The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:169:26
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.
The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:169:26
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.
The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:169:26
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.
The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:169:26
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:141:20
When the exception was thrown, this was the stack: 
#2      TextPainter.width (package:flutter/src/painting/text_painter.dart:497:12)
#3      _PaddleSliderValueIndicatorPathPainter.paint (package:flutter/src/material/slider_theme.dart:3094:48)
#4      PaddleSliderValueIndicatorShape.paint (package:flutter/src/material/slider_theme.dart:2853:18)
#5      ThumbShape.paint (package:int_test_demo/main.dart:220:21)
#6      _RenderSlider.paint (package:flutter/src/material/slider.dart:1446:30)
...
The following RenderObject was being processed when the exception was fired: _RenderSlider#73ee8
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
...  size: Size(428.0, 48.0)
RenderObject: _RenderSlider#73ee8
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=428.0, 0.0<=h<=Infinity)
  size: Size(428.0, 48.0)
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.
The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:169:26
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.
The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:169:26
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.
The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:169:26
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 497 pos 12: '!_needsLayout': is not true.
The relevant error-causing widget was: 
  Slider file:///Users/dhs/Documents/NCFlutter/int_test_demo/lib/main.dart:169:26
====================================================================================================

```

</details>

<details>
<summary>full code sample </summary>

```
import 'package:flutter/material.dart';
//import 'multiSlider.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatefulWidget(),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
// Example settings for the multiSlider
  var masterSlider = {
    "showMasterSlider": true,
    "masterSliderText": "Dies ist der Master Slider Text",
    "sliderMin": 0.0,
    "sliderMax": 100.0,
    "sliderDivisions": 100,
    "currentMasterSliderValue": 100.0,
  };

  List subSlider = [
    {
      "sliderText": "Erster Subslider Text",
      "currentSliderValue": 0.0,
    },
    {
      "sliderText": "Zweiter Subslider Text",
      "currentSliderValue": 0.0,
    },
    {
      "sliderText": "Dritter Subslider Text",
      "currentSliderValue": 0.0,
    },
    {
      "sliderText": "Vierter Subslider Text",
      "currentSliderValue": 0.0,
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        MultiSlider(masterSlider, subSlider),
      ],
    );
  }
}

class MultiSlider extends StatefulWidget {
  final Map masterSlider;
  final List subSlider;

  MultiSlider(this.masterSlider, this.subSlider);

  @override
  _MultiSliderState createState() => _MultiSliderState();
}

class _MultiSliderState extends State<MultiSlider> {
  //sums all subSliders EXCEPT the one given as an argument.
  //sums ALL subSliders if given null as an argument
  double sumOfAllSubSlidersExcept(currentSubSlider) {
    if (currentSubSlider != null) {
      return ((widget.subSlider.map((m) => m['currentSliderValue']).toList())
          .reduce((value, element) => value + element)) -
          currentSubSlider["currentSliderValue"];
    } else {
      return ((widget.subSlider.map((m) => m['currentSliderValue']).toList())
          .reduce((value, element) => value + element));
    }
  }

// required for subSlider-generation
  dontBeZero(valueToCheck) {
    if (valueToCheck == 0) {
      return 1;
    } else {
      return valueToCheck;
    }
  }

// Used by the subSliders
  dontOverstep(valueToCheck, checkAgainst) {
    if (valueToCheck > checkAgainst) {
      return checkAgainst;
    } else {
      return valueToCheck;
    }
  }

// Used by the masterSlider
  dontUnderstep(valueToCheck, checkAgainst) {
    if (valueToCheck < checkAgainst) {
      return checkAgainst;
    } else {
      return valueToCheck;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        // Those Texts are for debug only.
        // Text("Value of masterSlider:" +
        //    widget.masterSlider["currentMasterSliderValue"].toString()),
        // Text("Sum of all subSliders:" +
        //    (sumOfAllSubSlidersExcept(null)).toString()),

        // This builds the Title of the masterSlider
        Text(widget.masterSlider["masterSliderText"]),
        // This builds the masterSlider, if "showMasterSlider = true"
        if (widget.masterSlider["showMasterSlider"])
          SliderTheme(
            data: SliderThemeData(
              showValueIndicator: ShowValueIndicator.never,
              thumbShape: ThumbShape(),
            ),
            child: Slider(
              min: widget.masterSlider["sliderMin"],
              max: widget.masterSlider["sliderMax"],
              divisions: widget.masterSlider["sliderDivisions"],
              value: widget.masterSlider["currentMasterSliderValue"],
              onChanged: (double value) {
                setState(() {
                  widget.masterSlider["currentMasterSliderValue"] =
                      dontUnderstep(value, sumOfAllSubSlidersExcept(null));
                });
              },
            ),
          )
        else
          Container(),

        // This builds one subSlider for each item in the subSlider-List.
        ...widget.subSlider.map((item) {
          return Padding(
            padding: EdgeInsets.all(10.0),
            child: Column(
              children: [
                Text(item["sliderText"]),
                SliderTheme(
                  data: SliderThemeData(
                    showValueIndicator: ShowValueIndicator.never,
                    thumbShape: ThumbShape(),
                  ),
                  child: Slider(
                    // Subsliders inherit their layout from the masterSlider
                    min: widget.masterSlider["sliderMin"],
                    max: widget.masterSlider["sliderMax"],
                    divisions: widget.masterSlider["sliderDivisions"],
                    value: item["currentSliderValue"],
                    onChanged: (double value) {
                      setState(() {
                        // This makes sure that any subSlider can't be increased beyond
                        // the value of the masterSlider minus the sum of all other subSliders.
                        item["currentSliderValue"] = dontOverstep(
                            value,
                            (widget.masterSlider["currentMasterSliderValue"] -
                                sumOfAllSubSlidersExcept(item)));
                      });
                    },
                  ),
                ),
              ],
            ),
          );
        })
      ],
    );
  }
}

class ThumbShape extends RoundSliderThumbShape {
  final _indicatorShape = const PaddleSliderValueIndicatorShape();

  const ThumbShape();

  @override
  void paint(PaintingContext context, Offset center,
      {Animation<double> activationAnimation,
        Animation<double> enableAnimation,
        bool isDiscrete,
        TextPainter labelPainter,
        RenderBox parentBox,
        SliderThemeData sliderTheme,
        TextDirection textDirection,
        double textScaleFactor,
        double value,
        Size sizeWithOverflow}) {
    super.paint(context, center,
        activationAnimation: activationAnimation,
        enableAnimation: enableAnimation,
        sliderTheme: sliderTheme,
        value: value,
        textScaleFactor: textScaleFactor,
        sizeWithOverflow: sizeWithOverflow);
    _indicatorShape.paint(
      context,
      center,
      activationAnimation: const AlwaysStoppedAnimation(1),
      enableAnimation: enableAnimation,
      labelPainter: labelPainter,
      parentBox: parentBox,
      sliderTheme: sliderTheme,
      value: value,
// der TextScaleFactor verändert die Größe der "Tooltip"-Blase
      textScaleFactor: 0.6,
      sizeWithOverflow: sizeWithOverflow,
    );
  }
}




```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.319, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.319 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 430626d0f3 (48 minutes ago), 2021-03-29 21:44:03 -0700
    • Engine revision 4c6abc1e06
    • Dart version 2.13.0 (build 2.13.0-172.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

Keeping this open for further analysis.

**Comment by bernaferrari** [comment]
I'm getting the same with Text.

```
'package:flutter/src/painting/text_painter.dart': Failed assertion: line 881 pos 12: '!_needsLayout': is not true.
      #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
      #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
      #2      TextPainter.getPositionForOffset (package:flutter/src/painting/text_painter.dart:881:12)
      #3      RenderParagraph.hitTestChildren (package:flutter/src/rendering/paragraph.dart:456:52)
      #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #5      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2775:25)
      #6      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #7      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2770:33)
      #8      RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:1072:12)
      #9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #10     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #12     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
      #13     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #14     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
      #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #16     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #18     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
      #19     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #20     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
      #21     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #22     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:92:25)
      #23     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #24     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:87:21)
      #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #26     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2775:25)
      #27     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #28     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2770:33)
      #29     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:414:12)
      #30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #31     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #32     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #35     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1889:18)
      #36     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #37     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #38     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #39     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #40     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #41     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #42     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3257:31)
      #43     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2775:25)
      #44     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #45     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2770:33)
      #46     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:620:12)
      #47     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #48     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #49     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #50     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #51     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2714:22)
      #52     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #53     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2708:19)
      #54     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2694:12)
      #55     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #56     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2714:22)
      #57     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #58     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2708:19)
      #59     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2694:12)
      #60     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #61     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #62     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #63     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #64     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #65     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #66     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3376:31)
      #67     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #68     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #69     _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:765:25)
      #70     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
      #71     _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:760:33)
      #72     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #73     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #74     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #75     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #76     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #77     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3474:17)
      #78     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #79     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:178:19)
      #80     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #81     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:535:18)
      #82     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #83     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #84     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #85     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #86     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #87     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:131:19)
      #88     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2414:11)
      #89     RenderView.hitTest (package:flutter/src/rendering/view.dart:173:14)
      #90     RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:490:16)
      #91     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:346:7)
      #92     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
      #93     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
      #94     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
      #95     _rootRunUnary (dart:async/zone.dart:1370:13)
      #96     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
      #97     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
      #98     _invoke1 (dart:ui/hooks.dart:182:10)
      #99     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
      #100    _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

**Comment by 94wogus** [comment]
same problem here

**Comment by 94wogus** [comment]
When I clear the PageStorageKey the bug doesn't appear.

**Comment by BrunoLuigiOO** [comment]
The error occurs if you have a BottomNavigationBar with showUnselectedLabels set to false and try to click on where the label should be if showUnselectedLabels were true.

To fix this, as a workaround, simply set unselectedFontSize: 0.0

**Comment by Piinks** [comment]
We're not able to reproduce this right now, but sliders have been largely changed over the years. If someone is able to reproduce this with a fresh code sample on a more recent version of Flutter, please file a new issue with details. Thank you!
