### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by FatmaZehraSolak** [flutter/flutter#78214]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=434ca82e --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SentinelException
```

```
```
[✓] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale tr-TR)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.2)
    • VS Code at C:\Users\Enelsis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM J610F (mobile)       • 434ca82e      • android-arm    • Android 10 (API 29)
    • sdk gphone x86 (mobile) • emulator-5554 • android-arm    • Android null (API null)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: a29104a69b102a7485cd00d358eaeab219d258ab
### Plugins
connectivity-3.0.2
connectivity_macos-0.2.0
path_provider_linux-0.2.0-nullsafety
path_provider_windows-0.1.0-nullsafety.3
shared_preferences
shared_preferences_linux-0.0.4-nullsafety
shared_preferences_macos-0.0.2-nullsafety
shared_preferences_web-0.2.0-nullsafety
shared_preferences_windows-0.0.3-nullsafety
video_player-2.0.2
video_player_web-2.0.0
wakelock-0.4.0
wakelock_macos-0.1.0
wakelock_web-0.2.0
webview_flutter-2.0.2
wifi-0.1.5
wifi_info_flutter-2.0.0
wifi_iot-0.2.2

**Comment by darshankawar** [comment]
@FatmaZehraSolak 
Does it generate any log file, like `flutter_01.log` ?
If so, can you provide the same ?

**Comment by FatmaZehraSolak** [comment]
[flutter_06.log](https://github.com/flutter/flutter/files/6147756/flutter_06.log)

**Comment by pulstar** [comment]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=ZY223DPJLM --start-paused --web-port=5000 --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9102 lib\main.dart

## exception

SentinelException: [Sentinel type: Sentinel, kind: Collected, valueAsString: <collected>] from ext.flutter.activeDevToolsServerAddress()


## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19042.1083], locale pt-BR)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (3 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/pulst/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/pulst/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (5 available)
    • Vivo XI (mobile)     • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)
    • Moto X Play (mobile) • ZY223DPJLM       • android-arm    • Android 7.1.1 (API 25)
    • Windows (desktop)    • windows          • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.1083]
    • Chrome (web)         • chrome           • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)           • edge             • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.
```

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=ZY223DPJLM --start-paused --web-port=5000 --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9102 lib\main.dart

## exception

SentinelException: [Sentinel type: Sentinel, kind: Collected, valueAsString: <collected>] from ext.flutter.activeDevToolsServerAddress()


## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [versÃ£o 10.0.19042.1083], locale pt-BR)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (3 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/pulst/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/pulst/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (5 available)
    • Vivo XI (mobile)     • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)
    • Moto X Play (mobile) • ZY223DPJLM       • android-arm    • Android 7.1.1 (API 25)
    • Windows (desktop)    • windows          • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.1083]
    • Chrome (web)         • chrome           • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)           • edge             • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment]
There are some logs in #96746

**Comment by christopherfujino** [comment]
Stacktrace from https://github.com/flutter/flutter/issues/96746

```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1626:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2109:21)
#2      VmService.reloadSources (package:vm_service/src/vm_service.dart:1980:7)
#3      _reloadDeviceSources (package:flutter_tools/src/run_hot.dart:1176:32)
<asynchronous suspension>
#4      _defaultReloadSourcesHelper (package:flutter_tools/src/run_hot.dart:1115:65)
<asynchronous suspension>
#5      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:897:38)
<asynchronous suspension>
#6      HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:809:16)
<asynchronous suspension>
#7      HotRunner.restart (package:flutter_tools/src/run_hot.dart:711:36)
<asynchronous suspension>
#8      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1606:40)
<asynchronous suspension>
#9      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1659:7)
<asynchronous suspension>
```

```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [versÃ£o 10.0.22000.434], locale pt-BR)
    • Flutter version 2.5.3 at C:\Users\bruno\Documents\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\bruno\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at C:\Users\bruno\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • SM A325M (mobile) • RQ8RC0519KV • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [versÃ£o 10.0.22000.434]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 97.0.1072.62

• No issues found!
```
