### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: The cloud file provider is not running., errno = 362

### ISSUE THREAD

**Issue by kimoduor** [flutter/flutter#78236]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readSync failed, OS Error: The cloud file provider is not running.
, errno = 362
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:760:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#3      _File.readAsLinesSync (dart:io/file_impl.dart:590:36)
#4      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:105:16)
#5      ForwardingFile.readAsLinesSync (package:file/src/forwarding/forwarding_file.dart:105:16)
#6      PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart:84:67)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:970:21)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _runZoned (dart:async/zone.dart:1630:10)
#14     runZoned (dart:async/zone.dart:1550:10)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#21     _rootRun (dart:async/zone.dart:1190:13)
```
```
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hc\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.2)
    • VS Code at C:\Users\hc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • SM J415F (mobile) • 7232f28c • android-arm • Android 9 (API 28)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
FileSystemException: readSync failed, path = 'C:\Users\hc\OneDrive\uobapp\.flutter-plugins' (OS Error: The cloud file provider is not running.
, errno = 362)

**Comment by darshankawar** [comment]
Considering the age of the issue and lack of any activity after it was filed, I am going ahead and closing this as stale.

@kimoduor If you by any chance, see same error on latest stable version of the framework, which is now 3.3.3, please write in comments and I'll reopen it.
