### ISSUE TITLE
_BuildIOSSubCommand.runCommand StateError: Bad state: No element

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#78231]
Reported by @eliabieri in https://github.com/flutter/flutter/issues/77571#issuecomment-797898707

## command

flutter build ipa --analyze-size --build-number=24 --verbose

## exception

StateError: Bad state: No element

```
#0      Iterable.firstWhere (dart:core/iterable.dart:516:5)
#1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:280:10)
<asynchronous suspension>
#2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:111:50)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.3 20D91 darwin-arm, locale en-CH)
    • Flutter version 2.0.1 at /Users/eliabieri/git/flutter/flutter
    • Framework revision c5a4b4029c (9 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eliabieri/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • B336ECD5-6A6D-4924-922F-5DA468C09897 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.82
    ! Error: WG is not connected. Xcode will continue when WG is connected. (code -13)

• No issues found!
```

**Comment by jonahwilliams** [comment]
We should probably disable --analyze-size for build ipa for now.

**Comment by eliabieri** [comment]
[flutter_01.log](https://github.com/flutter/flutter/files/6143373/flutter_01.log)
[flutter_bild_ipa.log](https://github.com/flutter/flutter/files/6143374/flutter_bild_ipa.log)

**Comment by jmagman** [comment]
@jonahwilliams why (other than this crash)?  It worked when I tested it.

**Comment by jonahwilliams** [comment]
Oh, I assumed it didn't work at all - but I think it might be assuming that you ran `build ios` before. Does it work if you run clean first @jmagman ?

**Comment by jmagman** [comment]
@jmagman `flutter build ipa` is almost the same as `flutter build ios` except it assumes some defaults arg values and tells Xcode to `archive`, which builds and then creates an `xcarchive` from the result.  It will optionally then create an IPA from the resulting `.app` if you pass in `export-options-plist`, which this user didn't do.  This crash would probably happen with `flutter build ios --analyze-size`, too.
https://github.com/flutter/flutter/blob/c5a4b4029c0798f37c4a39b479d7cb75daa7b05c/packages/flutter_tools/lib/src/commands/build_ios.dart#L278-L282

**Comment by jmagman** [comment]
The unit test is passing:
https://github.com/flutter/flutter/blob/021311ed8a2c182d3237330e5d8ae4c4937b3d76/packages/flutter_tools/test/commands.shard/hermetic/build_ipa_test.dart#L245-L247

I'll try this again.

**Comment by jmagman** [comment]
@jonahwilliams is right as always, this totally fails after a `flutter clean`, although I see https://github.com/flutter/flutter/issues/77571 and not this one.
