### ISSUE TITLE
flutter has exited unexpectedly: "Invalid argument(s): Invalid type for "path": null".

### ISSUE THREAD

**Issue by dexterdatul** [flutter/flutter#78234]
## command

flutter --no-color create --template app --description A new Flutter application. --org com.example --platforms android,ios flutter_app

## exception

ArgumentError: Invalid argument(s): Invalid type for "path": null

```
#0      FileSystem.getPath (package:file/src/interface/file_system.dart:160:7)
#1      LocalFileSystem.directory (package:file/src/backends/local/local_file_system.dart:23:41)
#2      ErrorHandlingFileSystem.directory (package:flutter_tools/src/base/error_handling_io.dart:118:24)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:290:21)
<asynchronous suspension>
#4      Template.fromName (package:flutter_tools/src/template.dart:75:32)
<asynchronous suspension>
#5      CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:380:31)
<asynchronous suspension>
#6      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:23)
<asynchronous suspension>
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:31)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#18     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#21     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • SM A505F (mobile) • R58M63CPXSD • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 89.0.774.50

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
Considering age of the issue and lack of any activity after issue was filed, I am going ahead and closing this as stale.

@dexterdatul If by any chance, you see the same error using latest stable version of the framework, please write in comments and I'll reopen it.
