### ISSUE TITLE
[tool_crash] ProcessException: The requested operation requires elevation. Command: "C:\Program Files\Google\Chrome\Application\chrome.exe", OS error code: 740

### ISSUE THREAD

**Issue by datemasolutions** [flutter/flutter#78240]
Hello,

I've created a Flutter project. It works if I run it on Android. But on Chrome it does not start (same on Edge), see details below.
I'm using VSCode (in Admin mode).
If I create a new Flutter project (the default one), it works.

Any suggestions?
## Command
```
flutter run -d Chrome --web-port 5000 --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The requested operation requires elevation.
 Command: "C:\Program Files\Google\Chrome\Application\chrome.exe", OS error code: 740
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:39:20)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:247:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:225:35)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:133:17)
<asynchronous suspension>
#9      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:521:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-NL)
    • Flutter version 2.0.1 at C:\src\flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\jeroe\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 044f2cf5607a26f8818dab0f766400e85c52bdff
### Plugins
cloud_firestore-1.0.1
cloud_firestore_web-1.0.1
firebase_analytics-7.1.1
firebase_analytics_web-0.2.0+1
firebase_auth-1.0.1
firebase_auth_web-1.0.2
firebase_core-1.0.1
firebase_core_web-1.0.1
google_sign_in-5.0.0
google_sign_in_web-0.10.0
path_provider-2.0.1
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.0
shared_preferences-2.0.4
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+2

**Comment by yacinegithub** [comment]
same here

**Comment by danagbemava-nc** [comment]
I attempted to reproduce this on the latest stable version but I was not able to reproduce this. 
Given that this issue has not had any activity in quite some time, I will be closing this as stale. 

If anyone faces this issue, kindly file a new issue and provide detailed information as to how to reproduce.

Thank you

<details>
<summary>flutter doctor -v</summary>
```
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19043.2006], locale en-GH)
    • Flutter version 3.3.4 on channel stable at c:\src\sdks\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (7 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Deana\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5921.22     
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\Deana\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5921.22     
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.72.1)
    • VS Code at C:\Users\Deana\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (4 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version
      10.0.19043.2006]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 106.0.5249.103
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 106.0.1370.37

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
