### ISSUE TITLE
Exception java.net.NoRouteToHostException: No route to host (Host unreachable)

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#78246]
This exception occurred twice and made the flutter tree red:

* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20drive_perf_debug_warning/537/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_gallery__image_cache_memory/810/overview

```
[drive_perf_debug_warning] [STDOUT] stdout: Running "flutter pub get" in flutter_gallery...                  1,390ms
[drive_perf_debug_warning] [STDOUT] stdout: Running Gradle task 'assembleDebug'...                          
[drive_perf_debug_warning] [STDOUT] stderr: Exception in thread "main" java.net.NoRouteToHostException: No route to host (Host unreachable)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[drive_perf_debug_warning] [STDOUT] stderr: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at java.net.Socket.connect(Socket.java:589)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at org.gradle.wrapper.Download.download(Download.java:44)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at org.gradle.wrapper.Install$1.call(Install.java:61)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at org.gradle.wrapper.Install$1.call(Install.java:48)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at org.gradle.wrapper.Install.createDist(Install.java:48)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[drive_perf_debug_warning] [STDOUT] stdout: 
[drive_perf_debug_warning] [STDOUT] stderr: 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by mdebbar** [comment]
Re-running both the failures passed:
* https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20drive_perf_debug_warning/539/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_gallery__image_cache_memory/811/overview

**Comment by Hixie** [comment]
That error message indicates a transient network failure. Since it's been years since the failure, I'm going to close this issue.
