### ISSUE TITLE
Flaky: Invalid argument(s): remoteVmServiceUri must have an HTTP scheme

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#78261]
This flaky failure occurred and made the flutter tree red:

* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_gallery_sksl_warmup__transition_perf/793/overview

```
Invalid argument(s): remoteVmServiceUri must have an HTTP scheme. Actual: 
#0      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:50:7)
#1      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:57:47)
#2      FlutterDriverService.reuseApplication (package:flutter_tools/src/drive/drive_service.dart:207:24)
#3      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:234:27)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

After re-running it, the task passed.

**Comment by bkonyi** [comment]
This is likely no longer relevant since DDS is now launched via `dart development-service`.
