### ISSUE TITLE
FileSystemException: FileSystemException: Deletion failed, path = 'somepath/build/ios/Debug' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by ligui-iOS** [flutter/flutter#78275]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios-framework --xcframework --no-universal --output=somepath/build/ios

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'somepath/build/ios/Debug' (OS Error: Permission denied, errno = 13)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:455:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#4      BuildIOSFrameworkCommand.runCommand (package:flutter_tools/src/commands/build_ios_framework.dart:188:23)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#13     IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#22     IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart)
#23     _rootRunUnary (dart:async/zone.dart:1198:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#31     IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart)
#32     _rootRunUnary (dart:async/zone.dart:1198:47)
#33     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#37     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#38     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#39     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#40     IosProject._xcodeProjectBuildSettings (package:flutter_tools/src/project.dart)
#41     _rootRunUnary (dart:async/zone.dart:1198:47)
#42     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#45     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#46     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#47     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#48     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#49     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#50     _rootRunUnary (dart:async/zone.dart:1198:47)
#51     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#54     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#55     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#56     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#57     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#58     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#59     _rootRunUnary (dart:async/zone.dart:1198:47)
#60     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#61     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#62     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#63     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#64     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#65     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
#66     _rootRunUnary (dart:async/zone.dart:1198:47)
#67     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#68     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#69     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#70     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#71     Future._complete (dart:async/future_impl.dart:519:7)
#72     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:228:14)
#73     _rootRun (dart:async/zone.dart:1182:47)
#74     _CustomZone.run (dart:async/zone.dart:1093:19)
#75     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#76     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#77     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#78     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#79     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
#80     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#81     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#82     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#83     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#84     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
#85     _rootRun (dart:async/zone.dart:1182:47)
#86     _CustomZone.run (dart:async/zone.dart:1093:19)
#87     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#88     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#89     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#90     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#91     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
#92     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
#93     _StreamController.close (dart:async/stream_controller.dart:664:5)
#94     _Socket._onData (dart:io-patch/socket_patch.dart:2051:21)
#95     _rootRunUnary (dart:async/zone.dart:1206:13)
#96     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#97     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#98     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#99     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#100    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#101    _StreamController._add (dart:async/stream_controller.dart:682:7)
#102    _StreamController.add (dart:async/stream_controller.dart:624:5)
#103    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1587:35)
#104    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1069:18)
#105    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#106    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#107    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#108    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/devin/development/flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/devin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/devin/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • vt100-iphone6plus (mobile) • c6533d5967e7397b4e025a95ea9ee079a8d4fd8b •
      ios • iOS 11.4.1

• No issues found!
```

**Comment by h2jw** [comment]
卸载原来的程序就可以了
