### ISSUE TITLE
"flutter build apk" failed

### ISSUE THREAD

**Issue by thealteria** [flutter/flutter#78293]
Can't generate release apk with `flutter build apk`.
`flutter clean` and then `flutter pub get` isn't working for me. Everything is up-to-date too.

```
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

                                                                        
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.flutter:armeabi_v7a_debug:1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.
     Required by:
         project :app
      > Could not resolve io.flutter:armeabi_v7a_debug:1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/armeabi_v7a_debug/1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4/armeabi_v7a_debug-1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/io/flutter/armeabi_v7a_debug/1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4/armeabi_v7a_debug-1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.pom'. Received status code 502 from server: Bad Gateway    
   > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.
     Required by:
         project :app
      > Could not resolve io.flutter:arm64_v8a_debug:1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4/arm64_v8a_debug-1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/io/flutter/arm64_v8a_debug/1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4/arm64_v8a_debug-1.0.0-5d8bf811b3072390933d69f3e289a4bb673636c4.pom'. Received status code 502 from server: Bad Gateway        

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       7.3s
Gradle task assembleRelease failed with exit code 1
```

### My `flutter doctor -v`

```
Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale en-IN)
    • Flutter version 2.0.2 at C:\Users\hp\flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\hp\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\hp\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!
```

**Comment by thealteria** [comment]
### UPDATE

the apk is generated now but it's only showing and stuck on white screen on the launch and doesn't showing anything. 
I generated the apk again using `flutter build apk` command but it's still stuck on the white screen.
Here's the screenshot:

![tempFileForShare_20210316-105454](https://user-images.githubusercontent.com/32410402/111260075-303bf300-8646-11eb-9a76-c053239cadf2.jpg)

**Comment by pedromassangocode** [comment]
Hi @thealteria 
Can you please provide your `flutter run --release --verbose` (running on same Android device) and your `pubspec.yaml`. 
Thank you

**Comment by thealteria** [comment]
Yup. Here's my `flutter run --release --verbose`

```
[  +85 ms] executing: [C:\Users\hp\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[   +1 ms] executing: [C:\Users\hp\flutter/] git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[  +44 ms] Exit code 0 from: git tag --points-at 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[   +1 ms] 2.0.2
[  +40 ms] executing: [C:\Users\hp\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Users\hp\flutter/] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +64 ms] executing: [C:\Users\hp\flutter/] git rev-parse --abbrev-ref HEAD
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +88 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +58 ms] executing: C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +39 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:sdk_gphone_x86_arm device:generic_x86_arm
           transport_id:1
[  +10 ms] C:\Users\hp\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +53 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +36 ms] "flutter run" took 255ms.
[  +18 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +3 ms]
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1274:11)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:437:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +287 ms] ensureAnalyticsSent: 283ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by pedromassangocode** [comment]
> [  +36 ms] "flutter run" took 255ms.
> [  +18 ms] Error: No pubspec.yaml file found.
>            This command should be run from the root of your Flutter project.
> [   +3 ms]

Hi @thealteria please make sure you run this in the root of your Flutter project.

**Comment by thealteria** [comment]
Yup I did and found the problem. It's occurring because one of the dependency I'm using in my project, `get_storage`.
The `get_storage` package is using `path_provider` dependency internally which is giving the **missing plugin exception** when I'm building the release apk.
