### ISSUE TITLE
Flutter Web : Cannot read property 'Symbol(dartx.postMessage)' of null.

### ISSUE THREAD

**Issue by ThalapathySiva** [flutter/flutter#78294]
I am having a HtmlElementView which will have Html content to render it, so when i open it first time its works fine as expected when i go back and open again its showing error.Here i have attached the reproducing example repo https://github.com/ThalapathySiva/flutter_html_reproducing_repo which will have two buttons on home page first click any one of those it will open the html render screen and it will work first time just go back and click the button again it will throw error without rendering and if you go back and refresh the whole window and tapped the button again it works this is the scenario by the way the contentwindow is getting null thats the issue.How can we handle this case. Thank you

Error : 

TypeError: Cannot read property 'Symbol(dartx.postMessage)' of null
    at http://localhost:55601/dart_sdk.js:33443:33
    at internalCallback (http://localhost:55601/dart_sdk.js:25104:11)

**Comment by pedromassangocode** [comment]
I can reproduce this on latest stable channel.


<details>
<summary>logs</summary>

```bash
Running "flutter pub get" in flutter_html_reproducing_repo...
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Debug service listening on ws://127.0.0.1:60866/jbnq1PkMUck=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:60866/jbnq1PkMUck=/ws
[object Window]Content
[object Window]Content
TypeError: Cannot read property 'Symbol(dartx.postMessage)' of null
    at http://localhost:60754/packages/flutter_application_1/main.dart.lib.js:434:39
    at http://localhost:60754/dart_sdk.js:33443:33
    at internalCallback (http://localhost:60754/dart_sdk.js:25104:11)
[object Window]Content
[object Window]Content
[object Window]Content
[object Window]Content
TypeError: Cannot read property 'Symbol(dartx.postMessage)' of null
    at http://localhost:60754/packages/flutter_application_1/main.dart.lib.js:434:39
    at http://localhost:60754/dart_sdk.js:33443:33
    at internalCallback (http://localhost:60754/dart_sdk.js:25104:11)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.2 20D80 darwin-x64, locale en-AO)
    • Flutter version 2.0.2 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.
```

</details>

**Comment by ThalapathySiva** [comment]
Any update on this ?

**Comment by ditman** [comment]
This is next in my queue after https://github.com/flutter/flutter/issues/80524

**Comment by ThalapathySiva** [comment]
Thanks for your reply @ditman  Cool

**Comment by vineeshvk** [comment]
+1 Any update on this?

**Comment by ditman** [comment]
Currently working on this, I'll update this ticket tomorrow with more info!

**Comment by ditman** [comment]
The non-minified error is not much more helpful:

```
Uncaught TypeError: Cannot read property 'postMessage' of null
    at _DOMWindowCrossFrame.postMessage$2 (html_dart2js.dart:40346)
    at Object.postMessage$2$x (main.dart.js:15080)
    at _HtmlDisplayState_showView_closure.call$0 (main.dart:60)
    at Future_Future$delayed_closure.call$0 (future.dart:315)
    at _TimerImpl_internalCallback.call$0 (async_patch.dart:131)
    at invokeClosure (js_helper.dart:1805)
    at js_helper.dart:1839
```

Diving deeper.

**Comment by ditman** [comment]
OK, so this issue is caused by a combination of two factors:

1. `ui.platformViewRegistry.registerViewFactory` "silently" rejecting to register new view factories that already exist ([code](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/platform_views/content_manager.dart#L71-L73)), and
2. The app is caching the "element" that gets injected (assuming that `registerViewFactory` *does* override the factory)

## Problem

The error comes from this line:

```dart
        element.contentWindow.postMessage({
          'id': 'question',
          'msg': widget.htmlText,
        }, "*");
```

inside of a `Future.delayed` (hence the very short stack trace), and it makes total sense.

The first time that the widget renders, the initState creates and caches `"instance1"` of the iframe element, and registers a view factory that returns `"instance1"` for HtmlElementViews with name `"map_element"`. The build method, returns an HtmlElementView that eventually renders the `"instance1"` in the DOM, and 2 seconds later a future interacts with the cached instance of the element, which is `"instance1"`.

The second time that the widget renders, the initState creates and caches `"instance2"` of the iframe element, and attempts to register a view factory that returns `"instance2"` for views with the name `"map_element"`. **Registering this second view silently fails.** The build method returns an HtmlElementView that **will render `"instance1"`** of the iframe. After two seconds, the timeout will attempt to modify `"instance2"` of the iframe (the cached "element"), which has never been injected in the DOM (and as a side effect of this, lacks a `contentWindow`). This causes the error.

You can verify the above behavior by printing the `hashCode` of the iframe element that is in your app and the DOM inside of the Future.delayed, by adding this at the beginning of the method there:

```dart
        print('Attempting to postMessage to: ${element.hashCode}');
        final actualElement = html.document.querySelector('iframe');
        print('Actual element: ${actualElement.hashCode}');
```

First time you get:

```
Attempting to postMessage to: 870652679
Actual element: 870652679
```

Second time you get:

```
Attempting to postMessage to: 355009417
Actual element: 870652679   <--  SAME AS FIRST TIME!
```

## Possible solutions

All the possible solutions hinge 

1. Do **not** call `registerViewFactory` more than once for the same `viewId`. You can easily achieve this by appending an int to the end of the viewId (this is a solution similar to what we use in the [google_maps_flutter_web plugin](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter_web/lib/src/google_maps_controller.dart#L27)): 
    ```dart
    // define int viewCounter = 0; at the top of your file
    String createdViewId = 'map_element_${viewCounter++}';
    ```
2. You can also achieve the same by ensuring that you **don't call `registerViewFactory` inside of lifecycle methods of your Widgets**, and as close as you can to the `main` method of your app. We do this in the `url_launcher_web` plugin to register the [factory to render Link widgets](https://github.com/flutter/plugins/blob/b548ae18646d1725a8e1f004c26bf42e4d362aa8/packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart#L49) (that method gets called **before** the main of the flutter application!)
3. Another simple solution is to **not cache the elements that you inject in the DOM from the factory**; instead give them a unique `id` attribute and use DOM selectors to access what you've rendered later. This used to be difficult (hence why people started "caching the rendered element" in older examples), but it should be much easier now that all platform views are rendered in a consistent location of the DOM. We used this above, to find the `actualElement`.

After looking at our own code, I'd say that we use the above solutions in the order I described them, but all should work. Pick your favorite one.

I hope this helps!

**Comment by ditman** [comment]
I'll bring this up with the team next week to see what we do about that "silent failure" of the `registerViewFactory` method; the API may be more usable if we allowed overriding the factory (every time you call registerFactory it changes the value), or we fail with a more explicit assertion error. 

(In any case, this'd be a breaking change on the current API and would take a while to release.)

**Comment by ditman** [comment]
@ThalapathySiva what flutter channel are you using? I think the issue you're describing should be resolved in `master`.

**Comment by ThalapathySiva** [comment]
@ditman I haven't checked the master channel yet, I am using the latest stable channel.

**Comment by ditman** [comment]
@ThalapathySiva the fixes haven't been published to Stable definitely, but they might be available in `beta`. Please try a newer channel (or wait for the next stable release!)

**Comment by ThalapathySiva** [comment]
@ditman Sure man thank you.
