### ISSUE TITLE
Error: XMLHttpRequest error. - Flutter Web 

### ISSUE THREAD

**Issue by viralvaghela** [flutter/flutter#78319]
I am trying to use http package in my flutter web application but I am getting this error 
```dart
Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 84:22                                       <fn>
dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 704:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 733:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>


    at Object.createErrorWithStack (http://localhost:32961/dart_sdk.js:5348:12)
    at Object._rethrow (http://localhost:32961/dart_sdk.js:39350:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:32961/dart_sdk.js:39344:13)
    at Object._microtaskLoop (http://localhost:32961/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:32961/dart_sdk.js:39182:13)
    at http://localhost:32961/dart_sdk.js:34689:9

```

I have also tried adding headers 
```
headers: {
          "Accept": "application/json",
          "Access-Control_Allow_Origin": "*"
        });
```
but still getting the same error

here is ``` flutter run --verbose ```
```
[ +199 ms] executing: [/home/viral/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +99 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +1 ms] executing: [/home/viral/snap/flutter/common/flutter/] git tag --points-at
c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +33 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +98 ms] executing: [/home/viral/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/viral/snap/flutter/common/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +98 ms] executing: [/home/viral/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +144 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +189 ms] executing: /home/viral/Android/Sdk/platform-tools/adb devices -l
[  +83 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +183 ms] Skipping pub get: version match.
[  +74 ms] Found plugin flutter_downloader at
/home/viral/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.5.2/
[ +553 ms] Found plugin flutter_downloader at
/home/viral/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.5.2/
[  +78 ms] Generating
/home/viral/work/github/instafy/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +707 ms] Launching lib/main.dart on Chrome in debug mode...
[ +321 ms] Updating assets
[ +220 ms] Waiting for connection from debug service on Chrome...
[  +28 ms] Found plugin flutter_downloader at
/home/viral/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.5.2/
[  +66 ms] Found plugin flutter_downloader at
/home/viral/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_downloader-1.5.2/
[ +150 ms] <- reset
[  +14 ms] /home/viral/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/viral/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/viral/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.MEXTZS/flutter_tool.CGSCEK/app.dill --libraries-spec
file:///home/viral/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/home/viral/work/github/instafy/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.MEXTZS/flutter_tools.IBTMJF
--filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///home/viral/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--no-sound-null-safety
[  +24 ms] <- compile org-dartlang-app:/web_entrypoint.dart


[+49014 ms] Waiting for connection from debug service on Chrome... (completed in 49.3s)
[   +1 ms] Synced 29.8MB.
[        ] <- accept
[        ] Caching compiled dill
[ +208 ms] Using Google Chrome 89.0.4389.90 

[ +760 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:33683/devtools/browser/c7a1708a-1d3e-4132-b815-50c558a9aea7
[ +610 ms] DwdsInjector: Received request for entrypoint at http://localhost:41555/main_module.bootstrap.js
[  +14 ms] MetadataProvider: Loading debug metadata...
[  +30 ms] MetadataProvider: Loaded debug metadata
[  +16 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:41555/main_module.bootstrap.js
[+5286 ms] DevHandler: Debug service listening on ws://127.0.0.1:45929/0Ik9Iep1NY4=/ws

[  +22 ms] Debug service listening on ws://127.0.0.1:45929/0Ik9Iep1NY4=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +5 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +3 ms] For a more detailed help message, press "h". To quit, press "q".
[+12541 ms] Error: XMLHttpRequest error.
                         dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get
current
                     packages/http/src/browser_client.dart 84:22                                       <fn>
                     dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
                     dart-sdk/lib/async/future_impl.dart 152:18                                        handleValue
                     dart-sdk/lib/async/future_impl.dart 704:44
handleValueCallback
                     dart-sdk/lib/async/future_impl.dart 733:13
_propagateToListeners
                     dart-sdk/lib/async/future_impl.dart 530:7                                         [_complete]
                     dart-sdk/lib/async/stream_pipe.dart 61:11
_cancelAndValue
                     dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
                     dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
                     dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
                     dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>
                     
                     
                         at Object.createErrorWithStack (http://localhost:41555/dart_sdk.js:5348:12)
                         at Object._rethrow (http://localhost:41555/dart_sdk.js:39350:16)
                         at async._AsyncCallbackEntry.new.callback (http://localhost:41555/dart_sdk.js:39344:13)
                         at Object._microtaskLoop (http://localhost:41555/dart_sdk.js:39176:13)
                         at _startMicrotaskLoop (http://localhost:41555/dart_sdk.js:39182:13)
                         at http://localhost:41555/dart_sdk.js:34689:9



```

**Comment by darshankawar** [comment]
@viralvaghela 
This seems to be a CORS issue over which Flutter has no control. You may need to enable it in your backend. 
See [this](https://github.com/flutter/flutter/issues/57421#issuecomment-638843037) similar resolved issue.

Closing from here.

**Comment by brunodmn** [comment]
this worked for me:
[https://stackoverflow.com/a/66879350/9914638](https://stackoverflow.com/a/66879350/9914638)
