### ISSUE TITLE
iOS app launches and waits for observatory port, but never connects, times out, and the app gets sigtermed

### ISSUE THREAD

**Issue by lukaszciastko** [flutter/flutter#78333]
I can launch my app from Xcode, but I cannot launch it using `flutter run`.

Same as here: https://github.com/flutter/flutter/issues/69632

I tried all possible options: cleaning the report, removing files, pub get, update - you name it. Nothing works. The app launches and hangs on the launch screen.

I only have this issues on my 12 Pro Max. I also tried on a 6s, but the app works on the 6s without problems.
My 12 Pro Max is on iOS 14.4.1 and 6s on 14.4 (updating to see if this breaks it).

I see this in the logs:
```
[        ] Application launched on the device. Waiting for observatory port.
[+30015 ms] Error launching application on iPhone.
Exited (sigterm)
[   +6 ms] 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:550:9)
           <asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
#6      CommandRunner.runCommand
package:args/command_runner.dart:197
           <asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
```

This is what `flutter doctor` shows when the app hangs:

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] VS Code (version 1.54.3)
[✓] Connected device (4 available)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will
      continue when iPhone is finished. (code -10)

• No issues found!
```

**Comment by darshankawar** [comment]
@lukaszciastko 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/78193
Please follow-up there for updates. Closing this as duplicate.

**Comment by jmagman** [comment]
This is unlikely to be a duplicate, this is a crash after installation (`Exited (sigterm)`) and #78193 is the app never installing.  @darshankawar Can you re-triage?  We need verbose logging.

**Comment by darshankawar** [comment]
That's my bad @jmagman. Thanks for notifying.

@lukaszciastko Can you provide `flutter run --verbose` ? If the log is huge, put that in a text file and share it here.
Are you running that command from AS or VScode ?

Does the same error occur if you create a new Project and execute `flutter run` ?

**Comment by lukaszciastko-spica** [comment]
I don't get this error when I try to run a new project. I was running the app using VS Code. I just noticed, when I try to run it from the command, everything is almost the same, but, after about 10 seconds, the app displays the main screen and the logs end different. I attached the logs from VS Code. And this is what I see when I try to launch the app from the terminal:

```
[ +212 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+30014 ms] Installing and launching... (completed in 58.8s)
[        ] Error launching application on iPhone.
[   +4 ms] "flutter run" took 361,828ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[   +3 ms] (lldb) process detach
[  +96 ms] ensureAnalyticsSent: 98ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```

[flutter-run-vs-code-logs.txt](https://github.com/flutter/flutter/files/6164418/flutter-run-vs-code-logs.txt)

I wonder, is there any timeouts that could cause this? It takes a few seconds for the last step where it says it's waiting for observatory port and the app actually launching.

**Comment by moesaid** [comment]
I have the same exact issue, I have been searching/trying for days now and nothing seems to work, the odd thing that my head can't get around it is when I create a new project that runs as supposed to with Vscode or flutters run command.

this problem only occurs on old projects.

**Comment by moesaid** [comment]
My terminal output.

```
[        ] Application launched on the device. Waiting for observatory port.
[+30013 ms] Installing and launching... (completed in 52.7s)
[        ] Error launching application on mohamed’s iPhone.
[   +4 ms] "flutter run" took 127,874ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[   +2 ms] (lldb) process detach
[ +255 ms] ensureAnalyticsSent: 256ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1


```

**Comment by ziyuw** [comment]
I have exactly the same issue and have been struggling all day to solve it.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by darshankawar** [comment]
@ziyuw @moesaid Can either of you provide `flutter run --verbose` along with `flutter doctor -v` ?
