### ISSUE TITLE
Dart compilation errors do not fail macOS build, fails at app runtime with "Failed to find path for "flutter_assets" embedder.cc (869): 'FlutterEngineInitialize' returned 'kInvalidArguments'. The assets path in the Flutter project arguments was missing."

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#78348]
First reported at https://github.com/flutter/flutter/issues/33582#issuecomment-724366814 by @tvolkert 

Dart compilation issue is causing `flutter assemble` to correctly exit 1, but that's not failing the overall macOS build Xcode compilation.  
```
[        ]            <asynchronous suspension>
[  +11 ms] [  +13 ms] "flutter assemble" took 10,707ms.
[   +6 ms] [   +6 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:307:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:92:3)
[        ]            <asynchronous suspension>
[ +253 ms] [ +255 ms] ensureAnalyticsSent: 254ms
[   +1 ms] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[  +28 ms] ProcessProductPackaging ""
/Users/tvolkert/project/sci/apps/payouts/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/payouts.app.xcent (in target 'Runner' from
project 'Runner')
...
```
The build just carries then eventually fails AT RUNTIME on the device because App.framework isn't found.
```
2021-03-16 09:57:56.097 payouts[18368:30361478] Failed to find path for "flutter_assets"
embedder.cc (869): 'FlutterEngineInitialize' returned 'kInvalidArguments'. The assets path in the Flutter project arguments was missing.
2021-03-16 09:57:56.098 payouts[18368:30361478] Failed to initialize Flutter engine: error 2
embedder.cc (1423): 'FlutterEngineSendPointerEvent' returned 'kInvalidArguments'. Engine handle was invalid.
```

**Comment by jonahwilliams** [comment]
I think this was happening on older projects because I did a `macos_assemble.sh || do_something_else` in the xcode project, making it always pass if the secont command passed. I thought it was fixed in newly generated projects though

**Comment by jmagman** [comment]
@jonahwilliams `macos_assemble.sh && touch Flutter/ephemeral/tripwire`.  We can still handle this in the script so we don't need a project file migration.
Finally found the duplicate.  https://github.com/flutter/flutter/issues/72608
