### ISSUE TITLE
Android 7 & 8 App Crashed

### ISSUE THREAD

**Issue by maheshmaersk** [flutter/flutter#78396]
Case Study is When we go with lower version of Android 
When there is no Fingerprint Registered we have an option of gotosettings when we click on that we get the app crashed and throws an exception
```
E/AndroidRuntime(10196): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(10196): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(10196): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(10196): 	at io.flutter.plugins.localauth.LocalAuthPlugin$1.onFailure(LocalAuthPlugin.java:109)
E/AndroidRuntime(10196): 	at io.flutter.plugins.localauth.AuthenticationHelper$2.onClick(AuthenticationHelper.java:229)
E/AndroidRuntime(10196): 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
E/AndroidRuntime(10196): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(10196): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(10196): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/AndroidRuntime(10196): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10196): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(10196): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
I/zygote64(10196): Do partial code cache collection, code=502KB, data=300KB
I/zygote64(10196): After code cache collection, code=502KB, data=300KB
I/zygote64(10196): Increasing code cache capacity to 2MB


One more issue is 

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:494)
	at android.app.Dialog.show(Dialog.java:342)
	at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:529)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2731)
	
```
	where i have modified/changed the Style but even though issue still persists

## Steps to Reproduce

1. Login To android 7 or 8 Device remove all the fingerprint and then try to login
2. Gototsettings would be shown and immediately crash occurs
3. Theme option is once more

## Logs

```
<details>
<summary>java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:494)
	at android.app.Dialog.show(Dialog.java:342)
	at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:529)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2731)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1206)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)</summary>

E/AndroidRuntime(10196): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(10196): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(10196): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(10196): 	at io.flutter.plugins.localauth.LocalAuthPlugin$1.onFailure(LocalAuthPlugin.java:109)
E/AndroidRuntime(10196): 	at io.flutter.plugins.localauth.AuthenticationHelper$2.onClick(AuthenticationHelper.java:229)
E/AndroidRuntime(10196): 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
E/AndroidRuntime(10196): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(10196): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(10196): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/AndroidRuntime(10196): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10196): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@maheshmaersk 
I am assuming this is related to `local_auth` plugin. If so, the two exceptions you listed:

`java.lang.IllegalStateException: Reply already submitted` is similar to https://github.com/flutter/flutter/issues/76299.

`java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.` is similar to https://github.com/flutter/flutter/issues/55638.

Please follow-up in respective issues for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
