### ISSUE TITLE
Timing out launching application on iPad after 70 seconds after successful install

### ISSUE THREAD

**Issue by DjordjeDelivero** [flutter/flutter#78412]
I get an error when trying to run my Flutter app on physical iOS device while it works on emulators and it works in Xcode but in VS Code fails. I tried flutter clean and also tried manually deleting all the pods configurations etc but no luck.

This is the error:

<details>
<summary>logs</summary>

```bash
[        ] Application launched on the device. Waiting for observatory port.
[+30012 ms] Installing and launching... (completed in 70.4s)
[        ] Error launching application on Djordje’s iPad.
[   +5 ms] "flutter run" took 137,226ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[   +5 ms] (lldb) process detach
[ +184 ms] ensureAnalyticsSent: 188ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1
```
</details>

Here is my flutter doctor output:

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.0.2 at /Users/djordje/Documents/flutter
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/djordje/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/djordje/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
```
</details>

**Comment by pedromassangocode** [comment]
Hi @DjordjeDelivero 
Can you please provide your `flutter run --verbose` (running on the same project and device)?
Thank you

**Comment by DjordjeDelivero** [comment]
Hello @pedromassangocode, thanks for replying.

Here is some of the `flutter run --verbose` output..

**Comment by pedromassangocode** [comment]
Piece of crash logs taken from https://github.com/flutter/flutter/issues/78412#issuecomment-801003870.

```console
[        ] Application launched on the device. Waiting for observatory port.
[+30015 ms] Installing and launching... (completed in 72.6s)
[        ] Error launching application on Djordje’s iPad.
[   +5 ms] "flutter run" took 127,257ms.
[  +18 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <
```

**Comment by nt4f04uNd** [comment]
i cannot see ipad in list of devices in `flutter doctor -v` you provided. i suspect this might be caused by #78134

**Comment by DjordjeDelivero** [comment]
@nt4f04uNd hmm. Weird, but that's not the case. Could be that it wasn't connected at the time, sorry I am doing lots of stuff at the moment. Anyway, here is another `flutter doctor -v` and it does appear. 

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.0.2 at /Users/djordje/Documents/flutter
    • Framework revision 8962f6dc68 (6 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/djordje/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/djordje/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Djordje’s iPad (mobile)      • 00008020-001C0CAE2280402E            • ios            • iOS 14.4
    • iPad Pro (9.7-inch) (mobile) • CCD9DB05-2039-48CD-AB23-D050BEA7D602 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

Also I think it's somewhat important to say that my app does start on the iPad after 'installing and launching' but it crashes right there... app continues to work as intended so I don't think it's the problem on my side.

**Comment by nt4f04uNd** [comment]
did you just try launching it? could it be that it was busy and now it's not and you can launch?

**Comment by DjordjeDelivero** [comment]
@nt4f04uNd yes I did, same thing happens. Also tested with iPhone 12 Pro Max and iPhone 6S and the tablet is iPad 8th Gen

**Comment by nt4f04uNd** [comment]
do these devices have ios 14.4? i have iphone 14.3 that is running just fine, it seems that build on 14.4 devices is broken

https://github.com/flutter/flutter/issues/78394

**Comment by nt4f04uNd** [comment]
oops, i meant https://github.com/flutter/flutter/issues/78193

**Comment by DjordjeDelivero** [comment]
Any news on this? It's still happening, pretty much impossible to develop for iOS devices

**Comment by nt4f04uNd** [comment]
did you to update to 14.4.1? this solved the issue in #78193

**Comment by DjordjeDelivero** [comment]
Yep, no difference.

**Comment by nt4f04uNd** [comment]
are you able to run a hello world app (from the `flutter create app`)?

**Comment by DjordjeDelivero** [comment]
Hi @nt4f04uNd,

Sorry for late response. I actually tried running the starter project and it worked just fine. After that I tried running my project again and it also worked. Really strange stuff, however I will close this issue for now.
