### ISSUE TITLE
picture.toImage exception if height or width > 8192 on Flutter 2.01

### ISSUE THREAD

**Issue by BoHellgren** [flutter/flutter#78429]
The following code works if resolution <= 8192:
```
Future<Uint8List> getPng(List<Sphere> spheres, ConfigData configData) async {
  int resolution = configData.resolution;
  Size size = Size.square(resolution.toDouble());
  ui.PictureRecorder pictureRecorder = ui.PictureRecorder();
  Canvas canvas = Canvas(pictureRecorder, Rect.fromLTWH(0, 0, size.width, size.height));
  canvas.drawColor(configData.backgroundColor, BlendMode.src);
  drawStuff(spheres, configData, canvas, size);
  final Picture picture = pictureRecorder.endRecording();
  final img = await picture.toImage(resolution, resolution);
  final byteData = await img.toByteData(format: ImageByteFormat.png);
  Uint8List pngBytes = byteData.buffer.asUint8List();
  return pngBytes;
}
```

But if resolution = 8193 or bigger, I get this exception:

```
E/flutter (15166): [ERROR:flutter/shell/common/shell.cc(242)] Dart Unhandled Exception: NoSuchMethodError: The getter '_handles' was called on null.
E/flutter (15166): Receiver: null
E/flutter (15166): Tried calling: _handles, stack trace: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (15166): #1      new Image._ (dart:ui/painting.dart:1601:12)
E/flutter (15166): #2      Picture.toImage.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:4849:24)
E/flutter (15166): 
```

Flutter doctor -v:

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version
    10.0.18363.1440], locale sv-SE)
    • Flutter version 2.0.1 at D:\flutter_windows\flutter
    • Framework revision c5a4b4029c (13 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (3 available)
    • SM G970F (mobile) • RF8M3164L6B • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      89.0.4389.82
    • Edge (web)        • edge        • web-javascript • Microsoft Edge
      89.0.774.50

• No issues found!
```

**Comment by jason-simmons** [comment]
The image size limit is due to the maximum supported texture size on the GPU (see https://github.com/flutter/flutter/issues/28705)

However, the future returned by `picture.toImage` should complete with an exception instead of dereferencing a null.

**Comment by BoHellgren** [comment]
This limit should be documented! I found the value 8192 by trial-and-error on a Samsung S10e. Could it be different on other devices? The limit in https://github.com/flutter/flutter/issues/28705 is 4196 with Flutter 1.2. Do I have to test this by trial-and-error on a lot of devices to find a "safe" limit? Or is there a way to calculate the current limit with dart code before calling Picture.toImage?

**Comment by BoHellgren** [comment]
Maybe there are no answers to my two questions. Maybe this is not the right place to ask, but they are caused by a bug/limitation in Picture.toImage and I am trying to find a workaround.

The only solution I can think of is this: Start with a high resolution. Then decrease it in a loop with try-catch until there no longer is an exception.

**Comment by chinmaygarde** [comment]
We are failing when we try to create an offscreen framebuffer that exceeds the capabilities of the GPU. We don't have this limitation when we attempt to decompress large images because we clamp to the maximum size supported by the GPU. We can do the same here. This fix should be easy. A more ideal fix might be to support tiling of texture.
