### ISSUE TITLE
[cocoon] /api/github-webhook-pullrequest keeps hitting `Bad state: Client is closed`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#78479]
`/api/github-webhook-pullrequest` has been hitting error `Bad state: Client is closed`.

Detailed error message:
```
Bad state: Client is closed
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2414:7)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2346:48)
#2      Scheduler.loadDevicelabManifest (package:cocoon_service/src/service/scheduler.dart:207:66)
#3      Scheduler._getTasks (package:cocoon_service/src/service/scheduler.dart:182:32)
<asynchronous suspension>
#4      Scheduler._addCommit (package:cocoon_service/src/service/scheduler.dart:108:30)
<asynchronous suspension>
#5      Scheduler.addPullRequest (package:cocoon_service/src/service/scheduler.dart:104:5)
<asynchronous suspension>
#6      GithubWebhook._handlePullRequest (package:cocoon_service/src/request_handlers/github_webhook.dart:124:11)
<asynchronous suspension>
#7      GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:80:11)
<asynchronous suspension>
```

/cc @CaseyHillers

**Comment by CaseyHillers** [comment]
Thank you for filing this!
