### ISSUE TITLE
Flutter desktop not working on windows

### ISSUE THREAD

**Issue by vikram0230** [flutter/flutter#78545]
**Flutter doesn't work on desktop(Windows 10), but works fine on mobile & web.**

## Steps to Reproduce

1. Enabled the Windows feature by `flutter config --enable-windows-desktop`
2. Debug the app using VS Code 1.49.0-insider's terminal. (CMD) `flutter run -d windows`
3. Issue appeared.

## Actual results: 

Launching lib\main.dart on Windows in debug mode...
Building Windows application...
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: F:/Flutter/desktop_sample/build/windows/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_e66b8.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

      Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      testCXXCompiler.cxx
      cl /c /ZI /JMC /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_e66b8.dir\Debug\\" /Fd"cmTC_e66b8.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue F:\Flutter\desktop_sample\build\windows\CMakeFiles\CMakeTmp\testCXXCompiler.cxx
    cmTC_e66b8.dir\Debug\testCXXCompiler.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86' [F:\Flutter\desktop_sample\build\windows\CMakeFiles\CMakeTmp\cmTC_e66b8.vcxproj]

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

Exception: Unable to generate build files

<details>
  <summary>Logs</summary>

### On running `flutter run --verbose` 

```
[  +89 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +68 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8a1204f0b6d8b5a14f1b80e11d7019a12ea532c8
[   +1 ms] executing: [C:\flutter/] git tag --points-at 8a1204f0b6d8b5a14f1b80e11d7019a12ea532c8
[  +57 ms] Exit code 0 from: git tag --points-at 8a1204f0b6d8b5a14f1b80e11d7019a12ea532c8
[   +1 ms] executing: [C:\flutter/] git describe --match *.*.* --long --tags 8a1204f0b6d8b5a14f1b80e11d7019a12ea532c8
[  +63 ms] Exit code 0 from: git describe --match *.*.* --long --tags 8a1204f0b6d8b5a14f1b80e11d7019a12ea532c8
[        ] 2.1.0-10.0.pre-122-g8a1204f0b6
[  +45 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +94 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +82 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +67 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +53 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +101 ms] Skipping pub get: version match.
[ +141 ms] Generating F:\Flutter\desktop_sample\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +122 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[  +13 ms] complete
[   +4 ms] Launching lib\main.dart on Windows in debug mode...
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\user\AppData\Local\Temp\flutter_tools.87562c15\flutter_tool.41af4db2\app.dill --packages
F:\Flutter\desktop_sample\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +52 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +33 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] [
             {
               "instanceId": "1dd1e72f",
               "installDate": "2021-03-10T13:25:56Z",
               "installationName": "VisualStudio/16.9.2+31112.23",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.9.31112.23",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.9#16.9.2",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2021-03-18T14:46:21.4893743Z",
               "catalog": {
                 "buildBranch": "d16.9",
                 "buildVersion": "16.9.31112.23",
                 "id": "VisualStudio/16.9.2+31112.23",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.9.2",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "2",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.9.2+31112.23",
                 "requiredEngineVersion": "2.9.3365.38425"
               },
               "properties": {
                 "campaignId": "",
                 "channelManifestId": "VisualStudio.16.Release/16.9.2+31112.23",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
               }
             }
           ]
[   +3 ms] Building Windows application...
[  +18 ms] <- compile package:desktop_sample/main.dart
[   +3 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
F:\Flutter\desktop_sample\windows -B build\windows -G Visual Studio 16 2019
[+2387 ms] -- The CXX compiler identification is MSVC 19.28.29913.0
[  +97 ms] -- Detecting CXX compiler ABI info
[+1310 ms] -- Detecting CXX compiler ABI info - failed
[  +11 ms] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe
[+1325 ms] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - broken
[   +4 ms] CMake Error at C:/Program Files (x86)/Microsoft Visual
Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
[   +4 ms]   The C++ compiler
[        ]     "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"
[        ]   is not able to compile a simple test program.
[        ]   It fails with the following output:
[        ]     Change Dir: F:/Flutter/desktop_sample/build/windows/CMakeFiles/CMakeTmp
[        ]     Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_6b404.vcxproj /p:Configuration=Debug
/p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework
[   +1 ms]     Copyright (C) Microsoft Corporation. All rights reserved.
[   +1 ms]       Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64
[        ]       Copyright (C) Microsoft Corporation.  All rights reserved.
[        ]       testCXXCompiler.cxx
[        ]       cl /c /ZI /JMC /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t
/Zc:forScope /Zc:inline /GR /Fo"cmTC_6b404.dir\Debug\\" /Fd"cmTC_6b404.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue
F:\Flutter\desktop_sample\build\windows\CMakeFiles\CMakeTmp\testCXXCompiler.cxx
[   +2 ms]     cmTC_6b404.dir\Debug\testCXXCompiler.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
[F:\Flutter\desktop_sample\build\windows\CMakeFiles\CMakeTmp\cmTC_6b404.vcxproj]
[   +1 ms]   CMake will not be able to correctly generate this project.
[        ] Call Stack (most recent call first):
[  +53 ms]   CMakeLists.txt:2 (project)
[  +12 ms] -- Configuring incomplete, errors occurred!
[        ] See also "F:/Flutter/desktop_sample/build/windows/CMakeFiles/CMakeOutput.log".
[        ] See also "F:/Flutter/desktop_sample/build/windows/CMakeFiles/CMakeError.log".
[  +30 ms] Building Windows application... (completed in 5.2s)
[+5455 ms] Exception: Unable to generate build files
[   +2 ms] "flutter run" took 11,410ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:655:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1187:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1038:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:60:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:151:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:77:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[  +86 ms] ensureAnalyticsSent: 84ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[+1334 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

```

### On running `flutter analyze`
```
Analyzing desktop_sample...                                             
No issues found! (ran in 2.6s)
```

### On running `flutter doctor -v`
```
[√] Flutter (Channel master, 2.1.0-11.0.pre.122, on Microsoft Windows [Version 10.0.19041.867], locale en-IN)
    • Flutter version 2.1.0-11.0.pre.122 at C:\flutter
    • Framework revision 8a1204f0b6 (13 days ago), 2021-03-04 23:34:03 -0500
    • Engine revision 299eb3e710
    • Dart version 2.13.0 (build 2.13.0-104.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```

</details>

I have tried reinstalling Visual Studio Community 2019 with Desktop developement with C++ toolset.

**Comment by darshankawar** [comment]
@vikram0230 
I tried a sample app using latest master version on Windows 10 machine and ran `flutter build windows` command which built it properly without any issues. I am too using VSCode 2019 and have updated the CMake version as applicable and required to make Flutter work on Windows platform.

<img width="881" alt="Screenshot 2021-03-19 at 1 16 13 PM" src="https://user-images.githubusercontent.com/67046386/111747707-a8f4b680-88b5-11eb-9aac-af4d930597c0.png">


You may need to re-visit your VScode setup and update the tools as applicable, as it seems to be your setup issue rather than a Flutter desktop on windows issue.

**Comment by vikram0230** [comment]
I couldn't understand why this issue is occuring.

```
fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86' [F:\Flutter\desktop_sample\build\windows\CMakeFiles\CMakeTmp\cmTC_b9cf7.vcxproj]
```

**Comment by darshankawar** [comment]
@vikram0230 
This doesn't sound like a Flutter framework related issue, but with Vscode setup. I suggest you to ask this question on support channels like StackOverflow to get more help on it.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.
