### ISSUE TITLE
[cocoon] /api/luci-status-handler hit `GitHub Error: Requested Resource was Not Found`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#78555]
Cocoon API `/api/luci-status-handler` starts hitting `GitHub Error: Requested Resource was Not Found` since 03/15/2021. This seems related to the recent change  (https://github.com/flutter/flutter/issues/77947) to separate consolidated shard builders into independent sub builders, which has increased the pre-submit check number by ~40. 

Detailed error message:
```
GitHub Error: Requested Resource was Not Found
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:400:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      GitHub.requestJson (package:github/src/common/github.dart:268:22)
<asynchronous suspension>
#3      GithubChecksService.updateCheckStatus (package:cocoon_service/src/service/github_checks_service.dart:116:38)
<asynchronous suspension>
#4      LuciStatusHandler.post (package:cocoon_service/src/request_handlers/luci_status.dart:99:7)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#6      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:125:9)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
We have seen this error before, and the fix is to add retry and move github client creation closer to the call.

**Comment by keyonghan** [comment]
Didn't hit the issue for couple of days. Closing.
