### ISSUE TITLE
Testing exceptions in onGenerateInitialRoutes throws unexpected "'_dependents.isEmpty': is not true"

### ISSUE THREAD

**Issue by raapperez** [flutter/flutter#78628]
We're migrating from Flutter 1.22.5 to 2.0.2 and a test that throws exception inside a `onGenerateInitialRoutes` doesn't pass anymore.

The following code reproduces the problem:
```dart
testWidgets('test argument error', (tester) async {
      await tester.pumpWidget(
        MaterialApp(
          initialRoute: '/',
          routes: <String, WidgetBuilder>{
            '/': (context) => Container(),
          },
          onGenerateInitialRoutes: (initialRoute) {
            throw ArgumentError('some error');
          },
        ),
      );

      expect(tester.takeException(), isA<ArgumentError>()); // this assert works fine
    });
  ```
The error:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown attaching to the render tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4954 pos 14:
'_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4954:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4956:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:2044:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2046:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2042:13)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2042:13)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2042:13)
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2042:13)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2042:13)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2042:13)
#18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2042:13)
#20     _InactiveElements.add (package:flutter/src/widgets/framework.dart:2054:7)
#21     Element.deactivateChild (package:flutter/src/widgets/framework.dart:3577:30)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3301:9)
#23     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1182:16)
#24     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1160:5)
#25     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1174:7)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694:33)
#28     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1102:19)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#32     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1048:5)
#33     runApp (package:flutter/src/widgets/binding.dart:1023:7)
#34     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:797:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: test with error
```

Adding some extra error handling like in this [PR](https://github.com/flutter/flutter/pull/73082/files#diff-220b5f283ca6e5d4af33a8d0afd875f407f050a438e320f0766f38e4edf1f8c2R1021) solves the problem but I believe something is wrong in this behavior. So I'm reporting it.

**Comment by darshankawar** [comment]
<details>
<summary>test error log</summary>

```
Testing started at 1:51 PM ...
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter --no-color test --machine --start-paused test/widget_test.dart

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown attaching to the render tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5031 pos 14:
'_dependents.isEmpty': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:5031:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:5033:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1871:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1873:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4626:14)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1869:13)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4626:14)
#9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1869:13)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4626:14)
#11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1869:13)
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4626:14)
#13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1869:13)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4626:14)
#15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1869:13)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4626:14)
#17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1869:13)
#18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4626:14)
#19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1869:13)
#20     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1881:7)
#21     Element.deactivateChild (package:flutter/src/widgets/framework.dart:3644:30)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3358:9)
#23     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1189:16)
#24     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1167:5)
#25     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1181:7)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
#27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2583:33)
#28     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1106:19)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#32     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1052:5)
#33     runApp (package:flutter/src/widgets/binding.dart:1029:7)
#34     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:800:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: test argument error

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.194, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.194 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision e58ee0fbc7 (2 hours ago), 2021-03-22 13:06:06 +0800
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>
