### ISSUE TITLE
【bug on Android】The position being added (Offset(xx)) has a smaller timestamp than its predecessor: _PointAtTime(Offset(xx) at _

### ISSUE THREAD

**Issue by dreamer2q** [flutter/flutter#78683]
When theme data of platform is set to `TargetPlatform.iOS` to gain iOS UI behavior,

Scrollable widgets will throw error, when you move it fast and randomly on Android.

## Steps to Reproduce

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        /// this is the cause of this error !
        /// when removed, everything works jut find !
        platform: TargetPlatform.iOS,
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Scroll Test'),
        ),
        body: ListView.builder(
          itemBuilder: (_, i) {
            return Container(
              color: i.isOdd ? Colors.red : Colors.black,
              height: 200,
            );
          },
        ),
      ),
    );
  }
}

```

**Expected results:** 

no errors thrown

**Actual results:** 

When you scroll fast and randomly,

an error will throw

```dart
======== Exception caught by gesture library =======================================================
The following assertion was thrown while routing a pointer event:
The position being added (Offset(225.0, 528.0)) has a smaller timestamp (131:17:15.075000)than its predecessor: _PointAtTime(Offset(225.7, 529.7) at 131:17:15.079000).

When the exception was thrown, this was the stack: 
#0      IOSScrollViewFlingVelocityTracker.addPosition.<anonymous closure> (package:flutter/src/gestures/velocity_tracker.dart:305:7)
#1      IOSScrollViewFlingVelocityTracker.addPosition (package:flutter/src/gestures/velocity_tracker.dart:309:6)
#2      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:280:15)
#3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
#4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
...
====================================================================================================
``` 

```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.868], locale zh-CN)
    • Flutter version 2.0.2 at D:\sdk\flutter
    • Framework revision 8962f6dc68 (8 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\11982\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.7759

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\11982\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • YAL AL00 (mobile) • STSDU19527006220 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!
```

**Comment by dreamer2q** [comment]
The reason why I set platform to TargetPlatform.iOS, is that I want to have iOS UI styles on Android phones.

**Comment by darshankawar** [comment]
@dreamer2q 
If you want to have iOS style UI on Android, have you looked at [Cupertino](https://flutter.dev/docs/development/ui/widgets/cupertino) widgets ?

**Comment by dreamer2q** [comment]
> @dreamer2q
> If you want to have iOS style UI on Android, have you looked at [Cupertino](https://flutter.dev/docs/development/ui/widgets/cupertino) widgets ?

not about UI style, but iOS scroll effect.

**Comment by darshankawar** [comment]
@dreamer2q 
Can you provide UI screenshots of what style / scroll effect are you trying to achieve ?
Have you looked at other support channels like StackOverflow, to see how iOS scroll effect can be achieved in Android ?

**Comment by dreamer2q** [comment]
@darshankawar 

technologily speaking, there is other means to achieve the same effect, but I am a little lazy to do that or do it later. 

But somehow, is this problem should be taken in consideration or at least a little note should be added ?

**Comment by darshankawar** [comment]
@dreamer2q 
Thanks for getting back. It'll be great to know what kind of iOS scroll effect are you looking to achieve in your use case, accordingly we will be in better position to address this issue.

**Comment by dreamer2q** [comment]
@darshankawar  Its about `ScrollConfig`, I want to have `AlwaysScrollPhysics` in a scrollable widget.

```dart
  GestureVelocityTrackerBuilder velocityTrackerBuilder(BuildContext context) {
    switch (getPlatform(context)) {
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return (PointerEvent event) => IOSScrollViewFlingVelocityTracker(event.kind);
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
        return (PointerEvent event) => VelocityTracker.withKind(event.kind);
    }
  }
```

**Comment by darshankawar** [comment]
@dreamer2q 
So If I understand correctly, you would like to have `AlwaysScrollPhysics` option for `physics` property of `ListView` ?

**Comment by dreamer2q** [comment]
@darshankawar  Yes, to be exactly, any scrollable widget,  such as `SingleChildScrollView` and so on.

**Comment by darshankawar** [comment]
@dreamer2q 
I already see `AlwaysScrollableScrollPhysics()` for `ListView` and `SingleChildScrollView`, unless I misinterpreted your last comment.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by zzterrozz** [comment]
I also have this error when I try to scroll when I launch the app.
This error doesn't show up if I "onTap" the screen first and then scroll....

I can't find out what widget is causing it


```
======== Exception caught by gesture library =======================================================
The following assertion was thrown while routing a pointer event:
The position being added (Offset(315.3, 278.7)) has a smaller timestamp (178:25:19.628615) than its predecessor: _PointAtTime(Offset(325.3, 337.3) at 451239:58:00.451334).

When the exception was thrown, this was the stack: 
#0      IOSScrollViewFlingVelocityTracker.addPosition.<anonymous closure> (package:flutter/src/gestures/velocity_tracker.dart:303:7)
#1      IOSScrollViewFlingVelocityTracker.addPosition (package:flutter/src/gestures/velocity_tracker.dart:307:6)
#2      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:15)
#3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#6      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:289:11)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#12     PointerEventResampler._samplePointerPosition (package:flutter/src/gestures/resampler.dart:273:15)
#13     PointerEventResampler.sample (package:flutter/src/gestures/resampler.dart:307:7)
#14     _Resampler.sample (package:flutter/src/gestures/binding.dart:136:17)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:331:18)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#21     _invoke1 (dart:ui/hooks.dart:182:10)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 3 frames from dart:async)
====================================================================================================
```

**Comment by jmagman** [comment]
Reopening, this had reproducible steps.

**Comment by jmagman** [comment]
Internal flaky test report b/210894831#comment1
cc @LongCatIsLooong #60501

**Comment by darshankawar** [comment]
I tried replicating this using code sample provided on Android Samsung device using latest master, but didn't get the said exception.

master version: `2.0.0-1.0.pre.319`

**Comment by wytesk133** [comment]
@darshankawar Seems like this can be reproduced on automated tests as well. Please see b/216348472#comment3

**Comment by FrankyLee-dev** [comment]
> > I also have this error when I try to scroll when I launch the app. This error doesn't show up if I "onTap" the screen first and then scroll....
> > I can't find out what widget is causing it
> > ```
> > ======== Exception caught by gesture library =======================================================
> > The following assertion was thrown while routing a pointer event:
> > The position being added (Offset(315.3, 278.7)) has a smaller timestamp (178:25:19.628615) than its predecessor: _PointAtTime(Offset(325.3, 337.3) at 451239:58:00.451334).
> > 
> > When the exception was thrown, this was the stack: 
> > #0      IOSScrollViewFlingVelocityTracker.addPosition.<anonymous closure> (package:flutter/src/gestures/velocity_tracker.dart:303:7)
> > #1      IOSScrollViewFlingVelocityTracker.addPosition (package:flutter/src/gestures/velocity_tracker.dart:307:6)
> > #2      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:15)
> > #3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
> > #4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
> > #5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
> > #6      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
> > #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
> > #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
> > #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
> > #10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:289:11)
> > #11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
> > #12     PointerEventResampler._samplePointerPosition (package:flutter/src/gestures/resampler.dart:273:15)
> > #13     PointerEventResampler.sample (package:flutter/src/gestures/resampler.dart:307:7)
> > #14     _Resampler.sample (package:flutter/src/gestures/binding.dart:136:17)
> > #15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:331:18)
> > #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
> > #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
> > #21     _invoke1 (dart:ui/hooks.dart:182:10)
> > #22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
> > #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
> > (elided 3 frames from dart:async)
> > ====================================================================================================
> > ```
> 
> In my case I fixed it by deleting in `main.dart` :
> 
> ```dart
> GestureBinding.instance!.resamplingEnabled = true;
> ```

This error will still occur even if deleted
```GestureBinding.instance!.resamplingEnabled = true;```

**Comment by shahmirzali49** [comment]
I have same exception. platform: MacOS

```
════════ Exception caught by gesture library ═══════════════════════════════════
The following assertion was thrown while routing a pointer event:
The position being added (Offset(17.0, -49.0)) has a smaller timestamp (101:16:30.789306) than its predecessor: _PointAtTime(Offset(0.0, 0.0) at 101:16:30.823732).

When the exception was thrown, this was the stack:
#0      IOSScrollViewFlingVelocityTracker.addPosition.<anonymous closure> (package:flutter/src/gestures/velocity_tracker.dart:316:7)
velocity_tracker.dart:316
#1      IOSScrollViewFlingVelocityTracker.addPosition (package:flutter/src/gestures/velocity_tracker.dart:320:6)
velocity_tracker.dart:320
#2      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:648:41)
monodrag.dart:648
#3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
pointer_router.dart:98
#4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
pointer_router.dart:143
#5      _LinkedHashMapMixin.forEach (dart:_compact_hash:726:13)
dart:_compact_hash:726
#6      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
pointer_router.dart:141
#7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
pointer_router.dart:127
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:502:19)
binding.dart:502
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:482:22)
binding.dart:482
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:457:11)
binding.dart:457
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:427:7)
binding.dart:427
#12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:390:5)
binding.dart:390
#13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:337:7)
binding.dart:337
#14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:306:9)
binding.dart:306
#15     _invoke1 (dart:ui/hooks.dart:328:13)
hooks.dart:328
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:450:7)
platform_dispatcher.dart:450
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
hooks.dart:262

════════════════════════════════════════════════════════════════════════════════ 
```
