### ISSUE TITLE
windows10 x64 couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by futureflsl** [flutter/flutter#78682]
I saw many about releated issue and I had a try,but it does not work.just helloworld cannot work well .enviroment:

windows 10 x64
android studio 4.1.3
fultter 2.0.3 stable
android 6.0.1

I just create a new flutter solution project.click run,but error occurred like this:

```
Launching lib\main.dart on DUK AL20 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
E/FlutterLoader( 4697): Flutter initialization failed.
E/FlutterLoader( 4697): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutter_app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_app-1/lib/arm, /data/app/com.example.flutter_app-1/base.apk!/lib/x86, /vendor/lib, /system/lib, /system/lib/arm]]] couldn't find "libflutter.so"
E/FlutterLoader( 4697): 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
E/FlutterLoader( 4697): 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
E/FlutterLoader( 4697): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:199)
E/FlutterLoader( 4697): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:317)
E/FlutterLoader( 4697): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:204)
E/FlutterLoader( 4697): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:244)
E/FlutterLoader( 4697): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:155)
E/FlutterLoader( 4697): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
E/FlutterLoader( 4697): 	at android.app.Activity.performCreate(Activity.java:6267)
E/FlutterLoader( 4697): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
E/FlutterLoader( 4697): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
E/FlutterLoader( 4697): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
E/FlutterLoader( 4697): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
E/FlutterLoader( 4697): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
E/FlutterLoader( 4697): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterLoader( 4697): 	at android.os.Looper.loop(Looper.java:148)
E/FlutterLoader( 4697): 	at android.app.ActivityThread.main(ActivityThread.java:5420)
E/FlutterLoader( 4697): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 4697): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
E/FlutterLoader( 4697): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:631)
E/FlutterLoader( 4697): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutter_app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_app-1/lib/arm, /data/app/com.example.flutter_app-1/base.apk!/lib/x86, /vendor/lib, /system/lib, /system/lib/arm]]] couldn't find "libflutter.so"
E/FlutterLoader( 4697): 	at java.lang.Runtime.loadLibrary(Runtime.java:370)
E/FlutterLoader( 4697): 	at java.lang.System.loadLibrary(System.java:1076)
E/FlutterLoader( 4697): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:116)
E/FlutterLoader( 4697): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:151)
E/FlutterLoader( 4697): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:146)
E/FlutterLoader( 4697): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/FlutterLoader( 4697): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/FlutterLoader( 4697): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/FlutterLoader( 4697): 	at java.lang.Thread.run(Thread.java:818)

```

**Comment by behzodfaiziev** [comment]
This is issue is similar to : [https://github.com/flutter/flutter/issues/18939](url)

**Comment by ProblematicDude** [comment]
@behzodfaiziev  Your link doesn't point anywhere. Unless someone copy paste it. May be formatting issue ?
[This is the correct url to the existing issue](https://github.com/flutter/flutter/issues/18939)

**Comment by behzodfaiziev** [comment]
@ProblematicDude  Thanks for correcting the link :) I'm new one in contributing in github, so that would be my lesson)

**Comment by behzodfaiziev** [comment]
[just chekingn](https://github.com/flutter/flutter/issues/18939)

**Comment by darshankawar** [comment]
@futureflsl 
The device / emulator you are using maybe is x64 abi, but the app could be looking for x86 abi. Can you try by creating an emulator which is x86_64` or simply x86 api and run `flutter run` again to see if it helps or issue still persists ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
