### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'simulatorBundlePath' was called on null.Receiver: nullTried calling: simulatorBundlePath

### ISSUE THREAD

**Issue by tp7309** [flutter/flutter#78716]
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/example_listview_test.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'simulatorBundlePath' was called on null.
Receiver: null
Tried calling: simulatorBundlePath
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      IOSSimulator.installApp (package:flutter_tools/src/ios/simulators.dart:370:44)
#2      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:439:18)
#3      FlutterDriverService.start (package:flutter_tools/src/drive/drive_service.dart:161:29)
<asynchronous suspension>
#4      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:205:7)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-CN)
    • Flutter version 2.0.2 at /Users/tp7309/SOFTWARE/flutter
    • Framework revision 8962f6dc68 (9 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/tp7309/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/tp7309/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7223.99

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • F91268C9-735C-4942-A757-C11BA296FCB6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```

## Flutter Application Metadata
**Type**: package
**Version**: 0.3.0
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff

**Comment by tp7309** [comment]
wrong configuration, close.
