### ISSUE TITLE
 Failed assertion: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by oligazar** [flutter/flutter#78719]
## Steps to Reproduce

After migrating my project to null-safety support I got following error:
```
: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +1 ms] I/flutter ( 5726): The following assertion was thrown building SlideTransition(animation: AnimationController#f3321(⏭
[        ] I/flutter ( 5726): 1.000; paused; for MaterialPageRoute<dynamic>(null))➩ProxyAnimation➩CurveTween(curve: Cubic(0.40,
[        ] I/flutter ( 5726): 0.00, 0.20, 1.00))➩Tween<Offset>(Offset(0.0, 0.3) → Offset(0.0, 0.0))➩Offset(0.0, 0.0), state:
[        ] I/flutter ( 5726): _AnimatedState#45bc4):
[        ] I/flutter ( 5726): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4267 pos 14:
[        ] I/flutter ( 5726): 'owner!._debugCurrentBuildTarget == this': is not true.
[        ] I/flutter ( 5726): 
[        ] I/flutter ( 5726): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 5726): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 5726): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 5726):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
[        ] I/flutter ( 5726): 
[        ] I/flutter ( 5726): The relevant error-causing widget was:
[   +2 ms] I/flutter ( 5726):   Navigator-[LabeledGlobalKey<NavigatorState>#5873d]
[        ] I/flutter ( 5726):   file:///Users/Admin/Development/flutter/AgForce/treckerflutter/lib/tracker_navigator/drawer_navigator.dart:20:10
[        ] I/flutter ( 5726): 
[        ] I/flutter ( 5726): When the exception was thrown, this was the stack:
[        ] I/flutter ( 5726): #2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4267:14)
[        ] I/flutter ( 5726): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:4270:6)
[        ] I/flutter ( 5726): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4551:5)
[        ] I/flutter ( 5726): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:11)
[        ] I/flutter ( 5726): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4546:5)
[        ] I/flutter ( 5726): ...     Normal element mounting (143 frames)
[        ] I/flutter ( 5726): #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3608:14)
[        ] I/flutter ( 5726): #150    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6175:32)
[   +1 ms] I/flutter ( 5726): ...     Normal element mounting (61 frames)
[        ] I/flutter ( 5726): #211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3608:14)
[   +1 ms] I/flutter ( 5726): #212    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6175:32)
[        ] I/flutter ( 5726): ...     Normal element mounting (19 frames)
[        ] I/flutter ( 5726): #231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3608:14)
[        ] I/flutter ( 5726): #232    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6175:32)
[        ] I/flutter ( 5726): ...     Normal element mounting (87 frames)
[   +1 ms] I/flutter ( 5726): #319    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3608:14)
[        ] I/flutter ( 5726): #320    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6175:32)
[        ] I/flutter ( 5726): #321    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3608:14)
[        ] I/flutter ( 5726): #322    Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
[        ] I/flutter ( 5726): #323    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #324    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:456:11)
[        ] I/flutter ( 5726): #325    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #326    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4551:5)
[        ] I/flutter ( 5726): #327    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4546:5)
[        ] I/flutter ( 5726): #328    _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:356:11)
[        ] I/flutter ( 5726): ...     Normal element mounting (7 frames)
[        ] I/flutter ( 5726): #335    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
[        ] I/flutter ( 5726): ...     Normal element mounting (7 frames)
[        ] I/flutter ( 5726): #342    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3608:14)
[        ] I/flutter ( 5726): #343    Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
[   +2 ms] I/flutter ( 5726): #344    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #345    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #346    ProxyElement.update (package:flutter/src/widgets/framework.dart:4920:5)
[        ] I/flutter ( 5726): #347    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #348    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062:14)
[        ] I/flutter ( 5726): #349    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #350    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #351    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #352    StatelessElement.update (package:flutter/src/widgets/framework.dart:4653:5)
[   +5 ms] I/flutter ( 5726): #353    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #354    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062:14)
[        ] I/flutter ( 5726): #355    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #356    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062:14)
[        ] I/flutter ( 5726): #357    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #358    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #359    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744:11)
[        ] I/flutter ( 5726): #360    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[   +4 ms] I/flutter ( 5726): #361    StatefulElement.update (package:flutter/src/widgets/framework.dart:4776:5)
[        ] I/flutter ( 5726): #362    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #363    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062:14)
[        ] I/flutter ( 5726): #364    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #365    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062:14)
[        ] I/flutter ( 5726): #366    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #367    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #368    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744:11)
[   +2 ms] I/flutter ( 5726): #369    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #370    StatefulElement.update (package:flutter/src/widgets/framework.dart:4776:5)
[        ] I/flutter ( 5726): #371    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #372    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #373    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #374    StatelessElement.update (package:flutter/src/widgets/framework.dart:4653:5)
[        ] I/flutter ( 5726): #375    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #376    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[   +2 ms] I/flutter ( 5726): #377    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744:11)
[        ] I/flutter ( 5726): #378    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #379    StatefulElement.update (package:flutter/src/widgets/framework.dart:4776:5)
[        ] I/flutter ( 5726): #380    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #381    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062:14)
[        ] I/flutter ( 5726): #382    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #383    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #384    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[   +2 ms] I/flutter ( 5726): #385    ProxyElement.update (package:flutter/src/widgets/framework.dart:4920:5)
[        ] I/flutter ( 5726): #386    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
[        ] I/flutter ( 5726): #387    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #388    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062:14)
[        ] I/flutter ( 5726): #389    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #390    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #391    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744:11)
[        ] I/flutter ( 5726): #392    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[   +3 ms] I/flutter ( 5726): #393    StatefulElement.update (package:flutter/src/widgets/framework.dart:4776:5)
[        ] I/flutter ( 5726): #394    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #395    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #396    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #397    ProxyElement.update (package:flutter/src/widgets/framework.dart:4920:5)
[        ] I/flutter ( 5726): #398    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #399    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #400    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[   +1 ms] I/flutter ( 5726): #401    ProxyElement.update (package:flutter/src/widgets/framework.dart:4920:5)
[        ] I/flutter ( 5726): #402    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #403    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #404    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744:11)
[        ] I/flutter ( 5726): #405    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #406    StatefulElement.update (package:flutter/src/widgets/framework.dart:4776:5)
[        ] I/flutter ( 5726): #407    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #408    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #409    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[   +1 ms] I/flutter ( 5726): #410    StatelessElement.update (package:flutter/src/widgets/framework.dart:4653:5)
[        ] I/flutter ( 5726): #411    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #412    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #413    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #414    StatelessElement.update (package:flutter/src/widgets/framework.dart:4653:5)
[   +4 ms] I/flutter ( 5726): #415    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #416    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062:14)
[        ] I/flutter ( 5726): #417    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[   +3 ms] I/flutter ( 5726): #418    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #419    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #420    ProxyElement.update (package:flutter/src/widgets/framework.dart:4920:5)
[        ] I/flutter ( 5726): #421    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #422    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #423    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #424    ProxyElement.update (package:flutter/src/widgets/framework.dart:4920:5)
[        ] I/flutter ( 5726): #425    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[   +3 ms] I/flutter ( 5726): #426    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #427    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744:11)
[        ] I/flutter ( 5726): #428    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #429    StatefulElement.update (package:flutter/src/widgets/framework.dart:4776:5)
[        ] I/flutter ( 5726): #430    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #431    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #432    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744:11)
[        ] I/flutter ( 5726): #433    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[   +1 ms] I/flutter ( 5726): #434    StatefulElement.update (package:flutter/src/widgets/framework.dart:4776:5)
[        ] I/flutter ( 5726): #435    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
[        ] I/flutter ( 5726): #436    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597:16)
[        ] I/flutter ( 5726): #437    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744:11)
[        ] I/flutter ( 5726): #438    Element.rebuild (package:flutter/src/widgets/framework.dart:4265:5)
[        ] I/flutter ( 5726): #439    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2583:33)
[        ] I/flutter ( 5726): #440    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
[        ] I/flutter ( 5726): #441    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
[   +1 ms] I/flutter ( 5726): #442    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
[        ] I/flutter ( 5726): #443    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
[        ] I/flutter ( 5726): #444    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
[        ] I/flutter ( 5726): #448    _invoke (dart:ui/hooks.dart:167:10)
[        ] I/flutter ( 5726): #449    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
[ +961 ms] I/flutter ( 5726): #450    _drawFrame (dart:ui/hooks.dart:126:31)
[        ] I/flutter ( 5726): (elided 5 frames from class _AssertionError and dart:async)
[        ] I/flutter ( 5726): 

```
Widget causing the issue was
```
Navigator(
    key: navigatorKey,
    initialRoute: '/',
    onGenerateRoute: (routeSettings) {
	    print("name: ${routeSettings.name}");
	    return MaterialPageRoute(
		    builder: (context) {
			    // call callback from
			    return routeBuilders[routeSettings.name!]!(context, routeSettings);
		    },
	    );
    });
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.1.0-13.0.pre.86, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@oligazar 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
