### ISSUE TITLE
 RadioListTile's leading property if not set, shows `Leading widget consumes entire tile width` with exception in rendering library.

### ISSUE THREAD

**Issue by tiloc** [flutter/flutter#78745]
## Steps to Reproduce

I am running an app on iOS which uses a RadioListTile that is constructed without specifying a Leading widget explicity:
```
RadioListTile<String?>(
          title: Text(
            '---',
            style: Theme.of(context).textTheme.bodyText2,
          ),
          value: null,
          groupValue: _choiceString(value),
          onChanged: (String? newValue) {
            value = _fillValue(newValue);
          })
```

**Expected results:**
A RadioListTile appears on the screen.

**Actual results:**
A stacktrace appears on the console

<details>
  <summary>Logs</summary>

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
Leading widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
'package:flutter/src/material/list_tile.dart':
Failed assertion: line 1721 pos 7: 'tileWidth != leadingSize.width || tileWidth == 0.0'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  RadioListTile<String?> file:///Users/tilo/Projects/fire_widgets/lib/questionnaires/view/choice_answer.dart:267:19
When the exception was thrown, this was the stack: 
#2      _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:1721:7)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:226:12)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#6      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:226:12)
...
The following RenderObject was being processed when the exception was fired: _RenderListTile#6b613 relayoutBoundary=up24 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=33.4, 0.0<=h<=Infinity)
...  size: MISSING
RenderObject: _RenderListTile#6b613 relayoutBoundary=up24 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=33.4, 0.0<=h<=Infinity)
  size: MISSING
...  leading: RenderSemanticsAnnotations#99979 relayoutBoundary=up25 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0) (can use size)
...    constraints: BoxConstraints(0.0<=w<=33.4, 0.0<=h<=56.0)
...    size: Size(33.4, 40.0)
...    child: RenderMouseRegion#63764 relayoutBoundary=up26 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=33.4, 0.0<=h<=56.0)
...      size: Size(33.4, 40.0)
...      listeners: enter, exit
...      cursor: SystemMouseCursor(click)
...      child: RenderSemanticsAnnotations#60f7c relayoutBoundary=up27 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=33.4, 0.0<=h<=56.0)
...        size: Size(33.4, 40.0)
...        child: RenderSemanticsGestureHandler#c04f3 relayoutBoundary=up28 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=33.4, 0.0<=h<=56.0)
...          size: Size(33.4, 40.0)
...          behavior: deferToChild
...          gestures: tap
...  title: RenderParagraph#db674 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
...    textAlign: start
...    textDirection: ltr
...    softWrap: wrapping at box width
...    overflow: clip
...    locale: en
...    maxLines: unlimited
...    text: TextSpan
...      debugLabel: (englishLike body1 2014).merge(blackCupertino bodyText2)
...      inherit: false
...      color: Color(0xdd000000)
...      family: .SF UI Text
...      size: 14.0
...      weight: 400
...      baseline: alphabetic
...      decoration: TextDecoration.none
...      "---"
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: _RenderListTile#6b613 relayoutBoundary=up24 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  RadioListTile<String?> file:///Users/tilo/Projects/fire_widgets/lib/questionnaires/view/choice_answer.dart:267:19
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderPadding#21062 relayoutBoundary=up23 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  RadioListTile<String?> file:///Users/tilo/Projects/fire_widgets/lib/questionnaires/view/choice_answer.dart:267:19
```

```
tilo@Tilos-Mac-mini fire_widgets % flutter analyze
Analyzing fire_widgets...                                               
No issues found! (ran in 4.3s)

```

```
 flutter doctor -v
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on macOS 11.2.3 20D91 darwin-arm, locale en-DE)
    • Flutter version 2.1.0-12.1.pre at /Users/tilo/development/flutter
    • Framework revision 8264cb3e8a (11 days ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tilo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/tilo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) • 3D3DFA39-E8A8-4D1E-8CB0-599049967D76 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@tiloc 
Tried your code sample on latest dev using iphone simulator, but didn't notice the issue you are seeing.

<img width="933" alt="Screenshot 2021-03-22 at 7 25 24 PM" src="https://user-images.githubusercontent.com/67046386/112000934-73b1c800-8b44-11eb-95dc-221bf554fea4.png">


```
return Column(
      children: <Widget>[
        RadioListTile<SingingCharacter?>(
          title: Text('----', style: Theme.of(context).textTheme.bodyText2,),
          value: null,
          groupValue: _character,
          onChanged: (SingingCharacter? value) {
            setState(() {
              _character = value;
            });
          },
        ),
      ],
    );
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-12.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8264cb3e8a (12 days ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

The observed same behavior on latest master and stable as well.

Used this document for reference: https://api.flutter.dev/flutter/material/RadioListTile-class.html

**Comment by tiloc** [comment]
In further digging into this I discovered that this only occurred because the RadioListTiles were wrapped into table cells.
Table(children: [TableRow(children: listtiles)]);

It only occurred on smartphone, not on macOS. It also went away when I specified the Table with FixedColumnWidth.

**Comment by darshankawar** [comment]
@tiloc 
Thanks for looking more into it. Can this be closed since you found the solution for it ?

**Comment by tiloc** [comment]
@darshankawar I think it would benefit Flutter if such research and searching for solutions weren't necessary. Why is the Radiobutton trying to expand to infinity just because I allow it to? There is no reason, it is a simple circle, it should know its size and behave accordingly. While I love Flutter, I am spending hours every week trying to research workarounds like this.
I can understand if you close this issue, but I would hope that this triggers a process to make Flutter layouting more benign.

**Comment by darshankawar** [comment]
@tiloc Thanks for getting back and I understand your concern and pain point.
I tried to replicate your scenario again by wrapping `RadioListTile` with `Table`, but still wasn't able to see the error you mentioned earlier. Can you check below code I ran and see what could it be missing to trigger that error ?

```
return Table(
      children: [
        TableRow(
          children: [
            RadioListTile<SingingCharacter?>(
              title: Text('Lafayette'),
              value: null,
              groupValue: _character,
              onChanged: (SingingCharacter? value) {
                setState(() {
                  _character = value;
                });
              },
            ),
            RadioListTile<SingingCharacter?>(
              title: const Text('Thomas Jefferson'),
              value: SingingCharacter.jefferson,
              groupValue: _character,
              onChanged: (SingingCharacter? value) {
                setState(() {
                  _character = value;
                });
              },
            ),
          ]
        )
      ],
    );
```

**Comment by tiloc** [comment]
I have rigged my GitHub project to hopefully allow you to reproduce. The project is at https://github.com/tiloc/fire_widgets

The file https://github.com/tiloc/fire_widgets/blob/main/lib/questionnaires/view/choice_answer.dart contains a comment for you (currently line 309). If you uncomment the code line directly below that and then run the app on iOS simulator for iPhone SE 2 it reliably bombs on my system.

I hope that helps to reproduce.

**Comment by darshankawar** [comment]
Thanks for the repo. I was able to see the exception. Although if I again look at the error:

`Leading widget consumes entire tile width. Please use a sized widget or consider replacing ListTile with a custom widget`

Which indicates that the ListTile's leading widget is something like a Row widget, a widget whose intrinsic width isn't bounded and hence the recommendation is to use something like `Sized` widget which gives us the required width.

Does that help to mitigate ?

**Comment by tiloc** [comment]
Since the ListTile is a RadioListTile, I assume that the "leading" widget - which I did not set explicitly - is the Radio Button. Since a radio button is a well-defined circular shape and the height of the ListTile is known, I think the radio button should be "self-bounding", in that its width should be identical to its height in order to form a circle.

**Comment by exaby73** [comment]
@tiloc Hello. The repository you provided as a code sample doesn't have the [file](https://github.com/tiloc/fire_widgets/blob/main/lib/questionnaires/view/choice_answer.dart) you mentioned. Can you please provide a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) or confirm if this is fixed?
