### ISSUE TITLE
ImageCodecException in Release Build Flutter Web + CanvasKit

### ISSUE THREAD

**Issue by felangel** [flutter/flutter#78795]
## Steps to Reproduce

1. Run code in https://gist.github.com/felangel/1596c10fc10ca36c00dcf0bff26abd61 in debug mode
  - `flutter run -d chrome`
2. Observe that when tapping "take photo",  the image is rendered properly in the preview page
3. Run code in https://gist.github.com/felangel/1596c10fc10ca36c00dcf0bff26abd61 in release mode
  - `flutter build web --web-renderer canvaskit`
4. Observe that when tapping "take photo", an ImageCodecException occurs.

**Expected results:** 

![Screen Shot 2021-03-22 at 11 57 04 AM](https://user-images.githubusercontent.com/8855632/112028013-c029e300-8b05-11eb-99bf-90c9f5d9e9c2.png)

**Actual results:** 
![Screen Shot 2021-03-22 at 11 58 02 AM](https://user-images.githubusercontent.com/8855632/112028141-dd5eb180-8b05-11eb-84c4-0c21b650688e.png)

<details>
  <summary>Logs</summary>

```
[+3201 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,3",
                        "identifier" : "868DC50A-054E-4CBA-AB3E-FA42E7B6B213",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-pro-1",
                        "modelName" : "iPhone 11 Pro",
                        "name" : "iPhone 11 Pro"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,4",
                        "identifier" : "F0554C85-991B-477F-B672-5FD666E90BDD",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-8-2",
                        "modelName" : "iPhone 8",
                        "name" : "iPhone 8"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone13,1",
                        "identifier" : "5DC773C4-7E37-42B0-8E93-A9827C7ED432",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-12-mini-1",
                        "modelName" : "iPhone 12 mini",
                        "name" : "iPhone 12 mini"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone13,4",
                        "identifier" : "52FBB3ED-29E2-4A38-AD2B-06F89C4371E7",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-12-pro-max-1",
                        "modelName" : "iPhone 12 Pro Max",
                        "name" : "iPhone 12 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,3",
                        "identifier" : "DEAA9CB8-F95F-4A04-B92B-F34DEB6B5CA2",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-pro-1",
                        "modelName" : "iPhone 11 Pro",
                        "name" : "iPhone 11 Pro"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.0 (18J383)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV6,2",
                        "identifier" : "5E80E7D3-3FC9-41CE-BC21-96081481676F",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.apple-tv-4k",
                        "modelName" : "Apple TV 4K",
                        "name" : "Apple TV 4K"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad11,3",
                        "identifier" : "6A66D6B4-9A3B-40FA-B160-6E3B8835CE13",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-air3-wifi-1",
                        "modelName" : "iPad Air (3rd generation)",
                        "name" : "iPad Air (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,1",
                        "identifier" : "88DE54C7-C3D1-4C13-882D-677E6172587A",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-1",
                        "modelName" : "iPhone 11",
                        "name" : "iPhone 11"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,5",
                        "identifier" : "B936186E-740A-4C81-B680-DC82AB907CC8",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-8-plus-2",
                        "modelName" : "iPhone 8 Plus",
                        "name" : "iPhone 8 Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad8,12",
                        "identifier" : "0603527B-3BB7-40DE-ACE3-DFBA878C67B3",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-12point9-4th-1",
                        "modelName" : "iPad Pro (12.9-inch) (4th generation)",
                        "name" : "iPad Pro (12.9-inch) (4th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,5",
                        "identifier" : "6D3A8711-D586-4049-A426-8CD6135BD4E0",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-8-plus-2",
                        "modelName" : "iPhone 8 Plus",
                        "name" : "iPhone 8 Plus"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,5",
                        "identifier" : "59F149F0-2008-4721-9D7D-77FCDDE21234",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-pro-max-1",
                        "modelName" : "iPhone 11 Pro Max",
                        "name" : "iPhone 11 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "7.0 (18R382)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch5,4",
                        "identifier" : "4F5CAF69-3BE4-434A-9B7C-51417B981A10",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.watch-series5-1",
                        "modelName" : "Apple Watch Series 5 - 44mm",
                        "name" : "Apple Watch Series 5 - 44mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad11,7",
                        "identifier" : "B7876594-9FDD-4DB8-8D38-F3DEEFB3F434",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-8-wwan-1",
                        "modelName" : "iPad (8th generation)",
                        "name" : "iPad (8th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,1",
                        "identifier" : "E90C1409-69DD-46E5-848B-9BAD317E477A",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-1",
                        "modelName" : "iPhone 11",
                        "name" : "iPhone 11"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad8,5",
                        "identifier" : "E0992F7E-7E77-4DDC-8145-AC8133F53889",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-12point9-1",
                        "modelName" : "iPad Pro (12.9-inch) (3rd generation)",
                        "name" : "iPad Pro (12.9-inch) (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "7.0 (18R382)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch5,3",
                        "identifier" : "2B79CA73-CE05-4709-983B-AA436F701845",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.watch-series5-1",
                        "modelName" : "Apple Watch Series 5 - 40mm",
                        "name" : "Apple Watch Series 5 - 40mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad8,9",
                        "identifier" : "CA10560A-71B7-4FE7-950E-05F5C1D74104",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-11-2nd-1",
                        "modelName" : "iPad Pro (11-inch) (2nd generation)",
                        "name" : "iPad Pro (11-inch) (2nd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.0 (18J383)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV6,2",
                        "identifier" : "16374370-4502-4790-BBFE-B19CB2BD7C7F",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.apple-tv-4k",
                        "modelName" : "Apple TV 4K (at 1080p)",
                        "name" : "Apple TV 4K (at 1080p)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,5",
                        "identifier" : "088C5C7A-0431-4D80-BDED-A4A901ECB53D",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-pro-max-1",
                        "modelName" : "iPhone 11 Pro Max",
                        "name" : "iPhone 11 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,8",
                        "identifier" : "7ADA640B-78DB-40D1-9D44-8019A843EC33",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-se-1",
                        "modelName" : "iPhone SE (2nd generation)",
                        "name" : "iPhone SE (2nd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.0 (18J383)",
                        "available" : true,
                        "platform" : "com.apple.platform.appletvsimulator",
                        "modelCode" : "AppleTV5,3",
                        "identifier" : "6C781936-B73E-4565-9209-73AA4176A57B",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.apple-tv-4",
                        "modelName" : "Apple TV",
                        "name" : "Apple TV"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad8,1",
                        "identifier" : "DF261734-3D25-4A38-8F1A-45B647457C5B",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-11-1",
                        "modelName" : "iPad Pro (11-inch) (1st generation)",
                        "name" : "iPad Pro (11-inch)"
                      },
                      {
                        "modelCode" : "iPhone10,3",
                        "simulator" : false,
                        "modelName" : "iPhone X (Model A1865, A1901, A1902, A1903)",
                        "error" : {
                          "code" : -13,
                          "failureReason" : "",
                          "underlyingErrors" : [
                            {
                              "code" : 5,
                              "failureReason" : "allowsSecureServices: 1. isConnected: 0. Platform:
                              <DVTPlatform:0x7f9ae8208940:'com.apple.platform.iphoneos':<DVTFilePath:0x7f9ae82088c0:'\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform'>>.
                              DTDKDeviceIdentifierIsIDID: 0",
                              "description" : "Failed _shouldMakeReadyForDevelopment check even though device is not locked by passcode.",
                              "recoverySuggestion" : "",
                              "domain" : "com.apple.platform.iphoneos"
                            }
                          ],
                          "description" : "Felix’s iPhone is not connected",
                          "recoverySuggestion" : "Xcode will continue when Felix’s iPhone is connected.",
                          "domain" : "com.apple.platform.iphoneos"
                        },
                        "operatingSystemVersion" : "14.4 (18D52)",
                        "identifier" : "82b15a4a69ad47c74fe3e71b62a6a6e2842efe25",
                        "platform" : "com.apple.platform.iphoneos",
                        "architecture" : "arm64",
                        "interface" : "usb",
                        "available" : false,
                        "name" : "Felix’s iPhone",
                        "modelUTI" : "com.apple.iphone-x-1"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,4",
                        "identifier" : "5891C2BD-8FC9-41FD-9781-18FE88C3EDD1",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-8-2",
                        "modelName" : "iPhone 8",
                        "name" : "iPhone 8"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPod9,1",
                        "identifier" : "33D3D206-FF3B-4138-9829-5C966569D07A",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipod-touch-7-2",
                        "modelName" : "iPod touch (7th generation)",
                        "name" : "iPod touch (7th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "7.0 (18R382)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch6,1",
                        "identifier" : "79065A5E-DC30-4EBB-8A01-E1D366398CE1",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.watch-series6-1",
                        "modelName" : "Apple Watch Series 6 - 40mm",
                        "name" : "Apple Watch Series 6 - 40mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "7.0 (18R382)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch6,2",
                        "identifier" : "BF049CAA-9380-47B0-8875-D830B1ED1FB1",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.watch-series6-1",
                        "modelName" : "Apple Watch Series 6 - 44mm",
                        "name" : "Apple Watch Series 6 - 44mm"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone13,3",
                        "identifier" : "B75CF24B-9D7D-4E62-BFFC-6990137D5131",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-12-pro-1",
                        "modelName" : "iPhone 12 Pro",
                        "name" : "iPhone 12 Pro"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone13,2",
                        "identifier" : "509DC9DE-34D4-49BC-8DBF-1B731A9B6FDE",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-12-1",
                        "modelName" : "iPhone 12",
                        "name" : "iPhone 12"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,4",
                        "identifier" : "E4525F15-6694-43D5-B66E-A49210CB112E",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-9point7-a1674-b9b7ba",
                        "modelName" : "iPad Pro (9.7-inch)",
                        "name" : "iPad Pro (9.7-inch)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.1 (18A8394)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,2",
                        "identifier" : "D630837F-DA86-40D6-8F63-1609A89F6B46",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-air4-1",
                        "modelName" : "iPad Air (4th generation)",
                        "name" : "iPad Air (4th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad7,12",
                        "identifier" : "1D27A225-8B58-4380-9BAE-1C952052DA61",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-7-wwan-1",
                        "modelName" : "iPad (7th generation)",
                        "name" : "iPad (7th generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.2.2 (17B102)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad6,4",
                        "identifier" : "AA99FD8D-0EBF-4E80-BC21-15B4BBE7A9F1",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-9point7-a1674-b9b7ba",
                        "modelName" : "iPad Pro (9.7-inch)",
                        "name" : "iPad Pro (9.7-inch)"
                      }
                    ]
[  +11 ms] Error: Felix’s iPhone is not connected. Xcode will continue when Felix’s iPhone is connected. (code -13)
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +17 ms] Changing current working directory to: /Users/felix/Development/playgrounds/nnbd_flutter
[  +58 ms] Skipping pub get: version match.
[ +151 ms] Generating /Users/felix/Development/playgrounds/nnbd_flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +145 ms] Launching lib/main.dart on Chrome in debug mode...
[ +111 ms] Updating assets
[  +83 ms] Waiting for connection from debug service on Chrome...
[  +69 ms] <- reset
[   +6 ms] /Users/felix/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/felix/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/felix/Development/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/xn/py5pmlm51q39j8pgx_m9f8zc0000gn/T/flutter_tools.5G4d6M/flutter_tool.jYixdD/app.dill --libraries-spec file:///Users/felix/Development/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/felix/Development/playgrounds/nnbd_flutter/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/var/folders/xn/py5pmlm51q39j8pgx_m9f8zc0000gn/T/flutter_tools.5G4d6M/flutter_tools.ROh2Wu --filesystem-scheme org-dartlang-app --initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///Users/felix/Development/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+15202 ms] Waiting for connection from debug service on Chrome... (completed in 15.3s)
[        ] Synced 29.1MB.
[        ] <- accept
[        ] Caching compiled dill
[  +69 ms] Using Google Chrome 89.0.4389.90 

[ +711 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:58011/devtools/browser/0b61b777-995a-4d71-9b8b-b380283e940f
[ +671 ms] DwdsInjector: Received request for entrypoint at http://localhost:52112/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[  +10 ms] MetadataProvider: Loaded debug metadata
[   +7 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:52112/main_module.bootstrap.js
[+1646 ms] DevHandler: Debug service listening on ws://127.0.0.1:61157/7fU_BvzvkGc=/ws

[  +10 ms] Debug service listening on ws://127.0.0.1:61157/7fU_BvzvkGc=/ws
[        ] 💪 Running with sound null safety 💪
[   +3 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+6754 ms] "flutter run" took 30,085ms.
```

```
No issues found! (ran in 2.0s)
```

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.2 20D80 darwin-x64, locale en-US)
    • Flutter version 2.0.3 at /Users/felix/Development/flutter
    • Framework revision 4d7946a68d (4 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/felix/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90
    ! Error: Felix’s iPhone is not connected. Xcode will continue when Felix’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.
```

</details>

**Comment by ditman** [comment]
Running this as `flutter run -d chrome --profile` lets us get an un-minified exception:

```
ImageCodecException: Failed to decode image data.
Image source: encoded image bytes, ImageCodecException: Failed to decode image data.
Image source: encoded image bytes
    at Object.wrapException (http://localhost:41643/main.dart.js:7169:17)
    at CkAnimatedImage.createDefault$0 (http://localhost:41643/main.dart.js:33881:17)
    at CkAnimatedImage.ManagedSkiaObject$1 (http://localhost:41643/main.dart.js:34852:50)
    at http://localhost:41643/main.dart.js:14941:20
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:41643/main.dart.js:10894:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:41643/main.dart.js:52908:12)
    at Object._asyncStartSync (http://localhost:41643/main.dart.js:10858:20)
    at Object.instantiateImageCodec (http://localhost:41643/main.dart.js:14957:16)
    at WidgetsFlutterBinding.instantiateImageCodec$4$allowUpscaling$cacheHeight$cacheWidth (http://localhost:41643/main.dart.js:74385:16)
    at WidgetsFlutterBinding.instantiateImageCodec$1 (http://localhost:41643/main.dart.js:74388:19)
```

**Comment by ditman** [comment]
This seems to be related to the `._bytes` getter of the `cross_file` package, which returns this:

```dart
    if (_data != null) {
      return Future<Uint8List>.value(UnmodifiableUint8ListView(_data!));
    }
```

There's something about the `UnmodifiableUint8ListView` that the image codec doesn't understand.

A quick workaround for this is to pass the following to the `PreviewPage`, in the `_onSnapPressed` method: 

```dart
    final previewPageRoute = PreviewPage.route(image: Uint8List.fromList(image.toList()));
```

**Comment by balvinderz** [comment]
I think this can be closed now since https://github.com/flutter/flutter/issues/89014 is merged .

**Comment by hterkelsen** [comment]
Verified fixed
