### ISSUE TITLE
[Gallery] Crane demo shows blank screen when changing to another tab

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#78813]
Changing to tabs `sleep` or `eat` causes the screen to go purple (blank) when it finishes springing after initially displaying the proper contents only while scrolling.

High level logs:

```
flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

Specifically, tested with using bundletool to build-apks and install-apks on a release aab built with `flutter build appbundle`. Will try to repo using other builds.

**Comment by GaryQian** [comment]
More detailed logs:

```
03-22 14:44:46.616 16432 16460 I flutter : LateInitializationError: Local 'firstIndex' has not been initialized.
03-22 14:44:46.633 16432 16460 I flutter : #0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:208)
03-22 14:44:46.633 16432 16460 I flutter : #1      SliverVariableSizeBoxAdaptorElement.performRebuild (package:flutter_staggered_grid_view/src/widgets/sliver.dart:133)
03-22 14:44:46.633 16432 16460 I flutter : #2      SliverVariableSizeBoxAdaptorElement.update (package:flutter_staggered_grid_view/src/widgets/sliver.dart:103)
03-22 14:44:46.633 16432 16460 I flutter : #3      Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #4      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #5      Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #6      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5584)
03-22 14:44:46.633 16432 16460 I flutter : #7      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6186)
03-22 14:44:46.633 16432 16460 I flutter : #8      _ViewportElement.update (package:flutter/src/widgets/viewport.dart:228)
03-22 14:44:46.633 16432 16460 I flutter : #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744)
03-22 14:44:46.633 16432 16460 I flutter : #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:4776)
03-22 14:44:46.633 16432 16460 I flutter : #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4920)
03-22 14:44:46.633 16432 16460 I flutter : #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #39     StatelessElement.update (package:flutter/src/widgets/framework.dart:4653)
03-22 14:44:46.633 16432 16460 I flutter : #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744)
03-22 14:44:46.633 16432 16460 I flutter : #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #44     StatefulElement.update (package:flutter/src/widgets/framework.dart:4776)
03-22 14:44:46.633 16432 16460 I flutter : #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744)
03-22 14:44:46.633 16432 16460 I flutter : #48     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #49     StatefulElement.update (package:flutter/src/widgets/framework.dart:4776)
03-22 14:44:46.633 16432 16460 I flutter : #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #52     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:4920)
03-22 14:44:46.633 16432 16460 I flutter : #54     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #56     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #57     StatelessElement.update (package:flutter/src/widgets/framework.dart:4653)
03-22 14:44:46.633 16432 16460 I flutter : #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #64     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #65     ProxyElement.update (package:flutter/src/widgets/framework.dart:4920)
03-22 14:44:46.633 16432 16460 I flutter : #66     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181)
03-22 14:44:46.633 16432 16460 I flutter : #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744)
03-22 14:44:46.633 16432 16460 I flutter : #70     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:4776)
03-22 14:44:46.633 16432 16460 I flutter : #72     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #74     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #75     ProxyElement.update (package:flutter/src/widgets/framework.dart:4920)
03-22 14:44:46.633 16432 16460 I flutter : #76     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744)
03-22 14:44:46.633 16432 16460 I flutter : #79     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #80     StatefulElement.update (package:flutter/src/widgets/framework.dart:4776)
03-22 14:44:46.633 16432 16460 I flutter : #81     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744)
03-22 14:44:46.633 16432 16460 I flutter : #84     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #85     StatefulElement.update (package:flutter/src/widgets/framework.dart:4776)
03-22 14:44:46.633 16432 16460 I flutter : #86     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #87     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #88     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4744)
03-22 14:44:46.633 16432 16460 I flutter : #91     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:4776)
03-22 14:44:46.633 16432 16460 I flutter : #93     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4597)
03-22 14:44:46.633 16432 16460 I flutter : #95     Element.rebuild (package:flutter/src/widgets/framework.dart:4265)
03-22 14:44:46.633 16432 16460 I flutter : #96     StatelessElement.update (package:flutter/src/widgets/framework.dart:4653)
03-22 14:44:46.633 16432 16460 I flutter : #97     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.633 16432 16460 I flutter : #98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6062)
03-22 14:44:46.633 16432 16460 I flutter : #99     Element.updateChild (package:flutter/src/widgets/framework.dart:3350)
03-22 14:44:46.634 16432 16460 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

```

**Comment by guidezpl** [comment]
This will be fixed by https://github.com/flutter/gallery/pull/451, which itself is blocked on fixing an issue with integration tests
