### ISSUE TITLE
[tool_crash] ProcessException: The directory app/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj)

### ISSUE THREAD

**Issue by ImanMousavi** [flutter/flutter#78839]
## Command
```
flutter build ipa
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: The directory /Users/iman/work/royanex/app/ios contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option. Command: xcrun, OS error code: 78
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:171:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:323:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:414:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:585:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:567:35)
<asynchronous suspension>
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:509:50)
<asynchronous suspension>
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:486:41)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart:423:36)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:88:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp (package:flutter_tools/src/commands/build_ios.dart:201:26)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:231:33)
<asynchronous suspension>
#11     BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:111:50)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.3 20E5186d darwin-x64, locale
    en)
    • Flutter version 2.0.3 at /Users/iman/development/flutter
    • Framework revision 4d7946a68d (4 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 84f3d28555368a70270e9ac8390a9441df95e752
### Plugins
connectivity-3.0.3
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_messaging-7.0.3
flutter_local_notifications-3.0.3
flutter_plugin_android_lifecycle-2.0.0
image_cropper-1.3.1
image_picker-0.6.2+3
local_auth-1.1.0
package_info-0.4.3+2
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
share-0.6.5+4
sqflite-1.3.1+2
url_launcher-5.7.6
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.4+1
url_launcher_windows-0.0.1+3
webview_flutter-1.0.7

**Comment by pedromassangocode** [comment]
Similar closed issues: https://github.com/flutter/flutter/issues?q=is%3Aissue+%5Btool_crash%5D+ProcessException%3A+Process+exited+abnormally%3ACommand+line+invocation%3A+is%3Aclosed

**Comment by jmagman** [comment]
What's the output of 
```
$ ls -la /Users/iman/work/royanex/app/ios
```
Are there two `.xcodeproj` directories in there?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
