### ISSUE TITLE
StreamBuilder not updating during testWidget

### ISSUE THREAD

**Issue by lachiejames** [flutter/flutter#78832]
## Steps to Reproduce

`main.dart`:
```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key key}) : super(key: UniqueKey());

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'My App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Tasks'),
          actions: [
            PopupMenuButton<String>(
              onSelected: (String value) async {
                if (value == 'Add Tasks') {
                  print('adding tasks');
                  for (Task task in mockTaskList) {
                    await globalFirestoreInstance.collection('tasks').doc(task.id).set(task.toJson());
                  }
                  print('tasks added');
                } else {
                  print('deleting tasks');
                  await globalFirestoreInstance.collection('tasks').get().then((snapshot) async {
                    for (DocumentSnapshot documentSnapshot in snapshot.docs) {
                      await documentSnapshot.reference.delete();
                    }
                  });
                  print('tasks deleted');
                }
              },
              itemBuilder: (BuildContext context) {
                return ['Add Tasks', 'Delete All Tasks'].map(
                  (String choice) {
                    return PopupMenuItem<String>(
                      value: choice,
                      child: Text(choice),
                    );
                  },
                ).toList();
              },
            ),
          ],
        ),
        body: Container(
          child: Directionality(
            textDirection: TextDirection.ltr,
            child: StreamBuilder<QuerySnapshot>(
              stream: globalFirestoreInstance.collection('tasks').snapshots(),
              builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) => (!snapshot.hasData)
                  ? Center(
                      child: CircularProgressIndicator(),
                    )
                  : ListView(
                      children: snapshot.data.docs
                          .map(
                            (DocumentSnapshot doc) => Directionality(
                              textDirection: TextDirection.ltr,
                              child: Card(
                                child: ListTile(
                                  title: Text(doc['name']),
                                ),
                              ),
                            ),
                          )
                          .toList(),
                    ),
            ),
          ),
        ),
      ),
    );
  }
}

final List<Task> mockTaskList = [
  Task(
    id: '0',
    dateCreated: Timestamp(1, 2),
    name: 'task 0',
    isComplete: false,
  ),
  Task(
    id: '1',
    dateCreated: Timestamp(3, 4),
    name: 'task 1',
    isComplete: false,
  ),
];

class Task {
  final String id;
  final String name;
  final Timestamp dateCreated;
  final bool isComplete;

  Task({@required this.id, @required this.name, @required this.dateCreated, @required this.isComplete});

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'name': name,
      'dateCreated': dateCreated,
      'isComplete': isComplete,
    };
  }
}

FirebaseFirestore globalFirestoreInstance = FirebaseFirestore.instance;
```

`pubspec.yaml`:
```
name: my_app
description: Github testing
version: 0.2.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: "1.0.1"
  firebase_core: "1.0.1"
  modal_bottom_sheet: "2.0.0"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  cloud_firestore_mocks: "0.7.0"
  pedantic: "1.11.0"
  screenshots: "0.2.1"
  test: "1.16.5"

flutter:
  uses-material-design: true
```

`main_test.dart`:
```
import 'package:cloud_firestore_mocks/cloud_firestore_mocks.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lachies_life_planner/main.dart';

void main() {
  const String emptyFirestoreDump = '{\n'
      '  "tasks": {}\n'
      '}';

  const String populatedFirestoreDump = '{\n'
      '  "tasks": {\n'
      '    "0": {\n'
      '      "id": "0",\n'
      '      "name": "task 0",\n'
      '      "dateCreated": "1970-01-01T11:00:01.000",\n'
      '      "isComplete": false\n'
      '    },\n'
      '    "1": {\n'
      '      "id": "1",\n'
      '      "name": "task 1",\n'
      '      "dateCreated": "1970-01-01T11:00:03.000",\n'
      '      "isComplete": false\n'
      '    }\n'
      '  }\n'
      '}';

  Future<void> longPumpUntilSettle(WidgetTester tester) async {
    await tester.pump();
    await tester.pump();
    await tester.pump(const Duration(seconds: 1));
  }

  setUp(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    globalFirestoreInstance = MockFirestoreInstance();
  });

  testWidgets('adding tasks to firestore will populate ListView', (WidgetTester tester) async {
    await tester.runAsync(() async {
      await tester.pumpWidget(MyApp());

      // initially no tasks in firestore
      expect((globalFirestoreInstance as MockFirestoreInstance).dump(), emptyFirestoreDump);
      expect(find.byType(Card), findsNothing);

      // Adding 2 mock tasks to firestore
      await tester.tap(find.byIcon(Icons.more_vert));
      await longPumpUntilSettle(tester);
      await tester.tap(find.text('Add Tasks'));
      await longPumpUntilSettle(tester);

      // should have added 2 widgets to ListView
      expect((globalFirestoreInstance as MockFirestoreInstance).dump(), populatedFirestoreDump);

      // this will fail
      expect(find.byType(Card), findsNWidgets(2));

      // but this would have passed
      // await tester.pumpWidget(MyApp());
      // expect(find.byType(Card), findsNWidgets(2));
    });
  });
}

```

**Expected results:** 
2 `Card` widgets should have been added to the `WidgetTester` 'screen'

**Actual results:** 
0 `Card` widgets are added to the `WidgetTester` 'screen', unless I completely rebuild the UI with `await tester.pumpWidget(MyApp());` first

<details>
  <summary>Logs</summary>

```
PS C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner> flutter test --verbose  
[  +77 ms] executing: [C:\Users\Lachie\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +68 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +1 ms] executing: [C:\Users\Lachie\flutter/] git tag --points-at
c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +77 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +38 ms] executing: [C:\Users\Lachie\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\Lachie\flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +68 ms] executing: [C:\Users\Lachie\flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.      
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping       
update.
[  +46 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping     
update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping   
update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.      
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping       
update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +42 ms] Skipping pub get: version match.
[  +29 ms] Found plugin cloud_firestore at
C:\Users\Lachie\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-1.0.1\    
[   +9 ms] Found plugin cloud_firestore_web at
C:\Users\Lachie\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.1\[  +12 ms] Found plugin firebase_core at
C:\Users\Lachie\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.0.1\      
[   +3 ms] Found plugin firebase_core_web at
C:\Users\Lachie\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.0.1\  
[ +135 ms] Found plugin cloud_firestore at
C:\Users\Lachie\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-1.0.1\    
[   +4 ms] Found plugin cloud_firestore_web at
C:\Users\Lachie\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-1.0.1\[   +7 ms] Found plugin firebase_core at
C:\Users\Lachie\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.0.1\      
[   +6 ms] Found plugin firebase_core_web at
C:\Users\Lachie\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-1.0.1\  
[  +55 ms] Generating
C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +59 ms] running test package with arguments: [-r, compact, --timeout, 30s,
--concurrency=10, --,
C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner\test\main_test.dart]        
00:00 +0: ...achie\MyProjects\FlutterProjects\lachies_life_planner\test\main_test.dart     [ +191 ms] test 0: starting test
C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner\test\main_test.dart
[  +18 ms] test 0: starting shell process
[   +7 ms] Stopping scan for flutter_test_config.dart; found project root at
C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner
[   +5 ms] Compiler will use the following file as its incremental dill file:
C:\Users\Lachie\AppData\Local\Temp\flutter_tools.e0dd7f72\flutter_test_compiler.ddfbb02c\output.dill
[   +1 ms] Listening to compiler controller...
[   +2 ms] Compiling
file:///C:/Users/Lachie/AppData/Local/Temp/flutter_tools.e0dd7f72/flutter_test_listener.e585d63c/listener.dart
[   +9 ms] C:\Users\Lachie\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\Lachie\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot--sdk-root C:\Users\Lachie\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/   
--incremental --no-print-incremental-dependencies --target=flutter --debugger-module-names  
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Lachie\AppData\Local\Temp\flutter_tools.e0dd7f72\flutter_test_compiler.ddfbb02c\output.dill --packages
C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation 
--initialize-from-dill
C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner\build\test_cache\build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
[  +31 ms] <- compile
file:///C:/Users/Lachie/AppData/Local/Temp/flutter_tools.e0dd7f72/flutter_test_listener.e585d63c/listener.dart
00:01 +0: ...achie\MyProjects\FlutterProjects\lachies_life_planner\test\main_test.dart     [+1423 ms] <- accept
[   +3 ms] <- reset
[   +1 ms] Compiling
C:\Users\Lachie\AppData\Local\Temp\flutter_tools.e0dd7f72\flutter_test_listener.e585d63c\listener.dart took 1468ms
[   +6 ms] C:\Users\Lachie\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe--disable-observatory --enable-checked-mode --verify-entry-points
--enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling
--non-interactive --use-test-fonts
--packages=C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner\.dart_tool\package_config.json
C:\Users\Lachie\AppData\Local\Temp\flutter_tools.e0dd7f72\flutter_test_listener.e585d63c\listener.dart.dill
[  +11 ms] Using this directory for fonts configuration:
C:\Users\Lachie\AppData\Local\Temp\flutter_tools.e0dd7f72\flutter_test_fonts.6214a3b9       
[  +10 ms] test 0: awaiting initial result for pid 5444
[ +293 ms] test 0: process with pid 5444 connected to test harness
[   +1 ms] test 0: awaiting test result for pid 5444
00:02 +0: adding tasks to firestore will populate ListView
adding tasks
tasks added
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown while running async test code:
  Expected: exactly 2 matching nodes in the widget tree
  Actual: _WidgetTypeFinder:<zero widgets with type "Card" (ignoring offstage widgets)>     
   Which: means none were found but some were expected

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:155:31)
#1      _expect (package:test_api/src/frontend/expect.dart:150:3)
#2      expect (package:test_api/src/frontend/expect.dart:59:3)
#3      expect (package:flutter_test/src/widget_tester.dart:429:3)
#4      main.<anonymous closure>.<anonymous closure> (file:///C:/Users/Lachie/MyProjects/FlutterProjects/lachies_life_planner/test/main_test.dart:57:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: adding tasks to firestore will populate ListView [E]
  Test failed. See exception logs above.
  The test description was: adding tasks to firestore will populate ListView

[ +833 ms] test 0: process with pid 5444 no longer needed by test harness
[   +1 ms] test 0: cleaning up...
[   +1 ms] test 0: ensuring end-of-process for shell
[  +18 ms] test 0: deleting temporary directory
[   +4 ms] test 0: shutting down test harness socket server
[   +2 ms] test 0: finished
00:02 +0 -1: Some tests failed.
[   +9 ms] Deleting
C:\Users\Lachie\AppData\Local\Temp\flutter_tools.e0dd7f72\flutter_test_compiler.ddfbb02c... 
[   +4 ms] killing pid 7496
[  +40 ms] Deleting
C:\Users\Lachie\AppData\Local\Temp\flutter_tools.e0dd7f72\flutter_test_fonts.6214a3b9...    
[   +4 ms] test package returned with exit code 1
[   +9 ms] "flutter test" took 3,416ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      TestCommand.runCommand
(package:flutter_tools/src/commands/test.dart:305:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)      
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)       
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)      
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)        
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)      
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)       
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +262 ms] ensureAnalyticsSent: 251ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

```
 flutter analyze
Analyzing lachies_life_planner...
No issues found! (ran in 5.6s)
```

```
PS C:\Users\Lachie\MyProjects\FlutterProjects\lachies_life_planner> flutter doctor -v       
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.18363.1440], locale
    en-AU)
    • Flutter version 2.0.1 at C:\Users\Lachie\flutter
    • Framework revision c5a4b4029c (3 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Lachie\Android\AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Lachie\Android\AndroidSDK
    • ANDROID_SDK_ROOT = C:\Users\Lachie\Android\AndroidSDK
    • Java binary at: C:\Users\Lachie\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Lachie\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30)        
      (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90 

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@lachiejames 
Your code sample contains Firebase plugin which is 3rd party. Can you remove the relevant plugin code and try again to see if issue still persists or not ?
If so, please provide updated code sample that we can directly use to verify the issue.
Thanks.

**Comment by lachiejames** [comment]
I am unable to recreate the bug while using something other than `FirebaseFirestore.instance.collection('tasks').snapshots()` for the Stream source.  I tried using a different stream source, and the tests do not have the same issue.  Perhaps this needs to be raised on https://github.com/FirebaseExtended/flutterfire


For reference, this code (which does not use `FirebaseFirestore`) does not produce the same issue

`main.dart`:
```
import 'dart:async';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  StreamController<int> _events = StreamController<int>();

  @override
  initState() {
    super.initState();
    _events.add(0);
  }

  void _incrementCounter() {
    _counter++;
    _events.add(_counter);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("StreamBuilder test"),
        actions: [
          PopupMenuButton<String>(
            onSelected: (String value) => _events.add(0),
            itemBuilder: (BuildContext context) {
              return ['Reset'].map(
                (String option) {
                  return PopupMenuItem<String>(
                    value: option,
                    child: Text(option),
                  );
                },
              ).toList();
            },
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            StreamBuilder(
              stream: _events.stream,
              builder: (BuildContext context, snapshot) {
                return Text(
                  snapshot.data.toString(),
                  style: Theme.of(context).textTheme.headline3,
                );
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

`widget_test.dart`:
```
import 'package:flutter/material.dart';
import 'package:stream_test_bug/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('adding tasks to firestore will populate ListView', (WidgetTester tester) async {
    TestWidgetsFlutterBinding.ensureInitialized();
    await tester.runAsync(() async {
      // Create MyApp
      await tester.pumpWidget(MyApp());
      await tester.pumpAndSettle();

      // Should initially be 0
      expect(find.text('0'), findsOneWidget);

      // Should go to 1 after tapping FloatingActionButton
      await tester.tap(find.byType(FloatingActionButton));
      await tester.pumpAndSettle();
      expect(find.text('1'), findsOneWidget);

      // Should reset to 0 after tapping 'Reset' on drop down menu
      await tester.tap(find.byIcon(Icons.more_vert));
      await tester.pumpAndSettle();
      await tester.tap(find.text('Reset'));
      await tester.pumpAndSettle();
      expect(find.text('0'), findsOneWidget);
    });
  });
}

```

**Comment by darshankawar** [comment]
Thanks for proactively filing in Flutterfire repo. Closing it from here based on your comment above.
