### ISSUE TITLE
[Google_maps_flutter] GoogleMapController.getZoomLevel fails with castError

### ISSUE THREAD

**Issue by hlavki** [flutter/flutter#78856]
## Steps to Reproduce

This error occurs in `google_maps_flutter: 2.0.1` package

1. Install flutter 2.0.3
1. Download official google flutter maps example from [repo](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example)
1. Add `print('Zoom: ${mapController?.getZoomLevel()}');` somewhere in code e.g. move_camera.dart line 131
   ```dart
                TextButton(
                  onPressed: () {
                    print('Zoom: ${mapController?.getZoomLevel()}');
                    mapController?.moveCamera(
                      CameraUpdate.zoomBy(-0.5),
                    );
                  },
                  child: const Text('zoomBy'),
                ),
    ```
1. Run example application in android emulator
1. Open `Camera Control` example and press `zoomBy` button
1. Error occurs `type 'Future<double?>' is not a subtype of type 'Future<double>' in type cast`

<details>
  <summary>Logs</summary>

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
type 'Future<double?>' is not a subtype of type 'Future<double>' in type cast

When the exception was thrown, this was the stack: 
#0      MethodChannelGoogleMapsFlutter.getZoomLevel (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:428:9)
#1      GoogleMapController.getZoomLevel (package:google_maps_flutter/src/controller.dart:281:47)
#2      MoveCameraState.build.<anonymous closure> (package:google_maps_flutter_example/move_camera.dart:131:51)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#31387
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(301.4, 498.9)
  finalLocalPosition: Offset(48.1, 19.9)
  button: 1
  sent tap down
====================================================================================================
```

```
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale sk_SK.UTF-8)
    • Flutter version 2.0.3 at /data/home/hlavki/Programs/flutter
    • Framework revision 4d7946a68d (4 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /data/home/hlavki/Programs/Android/Sdk/
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /data/home/hlavki/Programs/Android/Sdk/
    • Java binary at: /usr/lib64/jvm/java/bin/java
    • Java version OpenJDK Runtime Environment (build 15.0.2+7-suse-1.3-x8664)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by readyiman** [comment]
I have same issue
```
Completer<GoogleMapController> _completer = Completer();

Future<double> zoomLevel() async {
    GoogleMapController controller = await _completer.future;
    return await controller.getZoomLevel();
  }
```
Exception happens at controller.getZoomLevel()
```
Exception has occurred.
_CastError (type 'Future<double?>' is not a subtype of type 'Future<double>' in type cast)
```
It looks like null safety exception.

**Comment by darshankawar** [comment]
Thanks @hlavki for reporting with steps to replicate and sorry for getting back to this a bit late.

I was able to replicate this on latest stable.

repro code: https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by PaoloP98** [comment]
I'm using google_maps_flutter: ^2.0.3 and the problem persists

**Comment by PaoloP98** [comment]
> I'm using google_maps_flutter: ^2.0.3 and the problem persists

I solved. Initially I had run the `flutter clean` command and re-downloaded the dependencies, but didn't work.
Subsequently I deleted the `pubspec.lock` file, ran `flutter clean` and it seems to be fixed.

**Comment by dca123** [comment]
Can confirm that deleting the pubspec.lock and running flutter clean fixes this issue.
