### ISSUE TITLE
[camera] App crashes on CameraController.takePicture() on Android

### ISSUE THREAD

**Issue by ManuLpz4** [flutter/flutter#78903]
Hi guys, hope you are doing well :)

I'm facing problems initializing a CameraController and also taking a picture only on Android (iOS working well even with 2 controller in parallel). Please let me know if you need more info or what you need.

## Code to reproduce
```dart
import 'package:flutter/material.dart';

import 'package:camera/camera.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:belo/enums/kyc_media_type.dart';
import 'package:belo/pages/verification/widgets/back_page.dart';
import 'package:belo/pages/verification/widgets/front_page.dart';
import 'package:belo/pages/verification/widgets/post_verification_page.dart';
import 'package:belo/pages/verification/widgets/pre_verification_page.dart';
import 'package:belo/pages/verification/widgets/selfie_page.dart';
import 'package:belo/widgets/belo_app_bar.dart';
import 'package:belo/widgets/belo_scaffold.dart';

final pageControllerProvider = Provider.autoDispose<PageController>((_) {
  return PageController();
});

final camerasProvider = ScopedProvider<List<CameraDescription>>((_) {
  throw UnimplementedError('List<CameraDescription> not provided.');
});

final cameraControllerProvider = ScopedProvider<CameraController>((_) {
  throw UnimplementedError('CameraController not provided.');
});

final kycMediaTypeProvider = ScopedProvider<KycMediaType>((_) {
  throw UnimplementedError('KycMediaType not provided.');
});

class VerificationPage extends StatefulWidget {
  const VerificationPage();

  @override
  _VerificationPageState createState() => _VerificationPageState();
}

class _VerificationPageState extends State<VerificationPage> {
  List<CameraDescription> _cameras;
  CameraController _cameraController;

  @override
  void initState() {
    super.initState();
    _initializeCameraController();
  }

  Future<void> _initializeCameraController() async {
    _cameras = await availableCameras();
    _cameraController = CameraController(_cameras.first, ResolutionPreset.max);

    await _cameraController.initialize();
  }

  @override
  Widget build(BuildContext context) {
    return BeloScaffold(
      appBar: const BeloAppBar(),
      body: FutureBuilder(
        future: _initializeCameraController(),
        builder: (__, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            return ProviderScope(
              overrides: [
                camerasProvider.overrideWithValue(_cameras),
                cameraControllerProvider.overrideWithValue(_cameraController),
              ],
              child: Consumer(
                builder: (_, ScopedReader watch, __) {
                  for (final KycMediaType type in KycMediaType.values) {
                    watch(fileProvider(type));
                  }

                  return PageView(
                    controller: watch(pageControllerProvider),
                    physics: const NeverScrollableScrollPhysics(),
                    children: const [
                      PreVerificationPage(),
                      FrontPage(),
                      BackPage(),
                      SelfiePage(),
                      PostVerificationPage(),
                    ],
                  );
                },
              ),
            );
          }

          return const Center(child: CircularProgressIndicator.adaptive());
        },
      ),
    );
  }
}
```

**Expected results:**
- CameraController initializing without unexpected consoling.
- CameraPreview working well and showing the preview.
- CameraController taking the picture.

**Actual results:**
- Unexpected consoling when CameraController.initialize() (logged below).
- CameraPreview frozen in black.
- App crash when attempting to take a picture (logged below).

<details>
  <summary>Logs</summary>

CameraController.initialize()
```
[+9673 ms] I/CameraManagerGlobal(25378): Connecting to camera service
[  +10 ms] W/CameraManagerGlobal(25378): [soar.cts] ignore the status update of camera: 2
[        ] W/CameraManagerGlobal(25378): [soar.cts] ignore the status update of camera: 3
[        ] W/CameraManagerGlobal(25378): [soar.cts] ignore the status update of camera: 4
[        ] W/CameraManagerGlobal(25378): [soar.cts] ignore the status update of camera: 5
[  +29 ms] I/Camera  (25378): [FPS Range Available] is:[15, 15]
[        ] I/Camera  (25378): [FPS Range Available] is:[7, 30]
[        ] I/Camera  (25378): [FPS Range Available] is:[30, 30]
[        ] I/Camera  (25378): [FPS Range] is:[7, 30]
[  +12 ms] I/Camera  (25378): [FPS Range Available] is:[15, 15]
[        ] I/Camera  (25378): [FPS Range Available] is:[7, 30]
[        ] I/Camera  (25378): [FPS Range Available] is:[30, 30]
[        ] I/Camera  (25378): [FPS Range] is:[7, 30]
[   +7 ms] W/Camera  (25378): The selected imageFormatGroup is not supported by Android. Defaulting to
yuv420
[   +2 ms] E/libc    (25378): Access denied finding property "persist.vendor.camera.privapp.list"
[        ] W/com.belo.app(25378): type=1400 audit(0.0:7989): avc: denied { read } for
name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=13982
scontext=u:r:untrusted_app:s0:c253,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0
tclass=file permissive=0
[ +261 ms] W/Camera  (25378): The selected imageFormatGroup is not supported by Android. Defaulting to
yuv420
[   +1 ms] W/Gralloc3(25378): allocator 3.x is not supported
[        ] E/libc    (25378): Access denied finding property "persist.vendor.camera.privapp.list"
[        ] W/com.belo.app(25378): type=1400 audit(0.0:7991): avc: denied { read } for
name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=13982
scontext=u:r:untrusted_app:s0:c253,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0
tclass=file permissive=0
[        ] I/Gralloc2(25378): Adding additional valid usage bits: 0x8202400
[ +279 ms] E/CameraCaptureSession(25378): Session 0: Exception while stopping repeating: 
[   +1 ms] E/CameraCaptureSession(25378): android.hardware.camera2.CameraAccessException:
CAMERA_DISCONNECTED (2): checkPidStatus:2047: The camera device has been disconnected
[   +1 ms] E/CameraCaptureSession(25378):       at
android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:827)
[   +1 ms] E/CameraCaptureSession(25378):       at
android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
[        ] E/CameraCaptureSession(25378):       at
android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1151)
[        ] E/CameraCaptureSession(25378):       at
android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:527)
[        ] E/CameraCaptureSession(25378):       at
android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:7
38)
[        ] E/CameraCaptureSession(25378):       at
android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:245)
[        ] E/CameraCaptureSession(25378):       at android.os.Handler.handleCallback(Handler.java:883)
[        ] E/CameraCaptureSession(25378):       at android.os.Handler.dispatchMessage(Handler.java:100)
[        ] E/CameraCaptureSession(25378):       at android.os.Looper.loop(Looper.java:214)
[        ] E/CameraCaptureSession(25378):       at android.app.ActivityThread.main(ActivityThread.java:7356)
[        ] E/CameraCaptureSession(25378):       at java.lang.reflect.Method.invoke(Native Method)
[        ] E/CameraCaptureSession(25378):       at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
[        ] E/CameraCaptureSession(25378):       at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[        ] E/CameraCaptureSession(25378): Caused by: android.os.ServiceSpecificException:
checkPidStatus:2047: The camera device has been disconnected (code 4)
[        ] E/CameraCaptureSession(25378):       at android.os.Parcel.createException(Parcel.java:2085)
[        ] E/CameraCaptureSession(25378):       at android.os.Parcel.readException(Parcel.java:2039)
[        ] E/CameraCaptureSession(25378):       at android.os.Parcel.readException(Parcel.java:1987)
[        ] E/CameraCaptureSession(25378):       at
android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:658)
[        ] E/CameraCaptureSession(25378):       at
android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
[        ] E/CameraCaptureSession(25378):       ... 11 more
```

CameraController.takePicture()
```
[+36145 ms] E/MethodChannel#plugins.flutter.io/camera(25378): Failed to handle method call
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera(25378): java.lang.NullPointerException: Attempt to
invoke virtual method 'void
android.media.ImageReader.setOnImageAvailableListener(android.media.ImageReader$OnImageAvailableListene
r, android.os.Handler)' on a null object reference
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
io.flutter.plugins.camera.Camera.takePicture(Camera.java:421)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:104)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera(25378):    at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera(25378):    at
android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
android.os.Looper.loop(Looper.java:174)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
android.app.ActivityThread.main(ActivityThread.java:7356)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at java.lang.reflect.Method.invoke(Native
Method)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
[        ] E/MethodChannel#plugins.flutter.io/camera(25378):    at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[   +3 ms] E/flutter (25378): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception:
CameraException(error, Attempt to invoke virtual method 'void
android.media.ImageReader.setOnImageAvailableListener(android.media.ImageReader$OnImageAvailableListene
r, android.os.Handler)' on a null object reference)
[        ] E/flutter (25378): #0      CameraController.takePicture
(package:camera/src/camera_controller.dart:346:7)
[        ] E/flutter (25378): <asynchronous suspension>
[        ] E/flutter (25378): #1      _CameraShutterState._takePicture
(package:belo/pages/verification/widgets/camera_shutter.dart:69:9)
[        ] E/flutter (25378): <asynchronous suspension>
[        ] E/flutter (25378): 
```

flutter analyze
```
Analyzing belo-app...                                                   
No issues found! (ran in 8.0s)
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.0 20A2411 darwin-arm, locale es-419)
    • Flutter version 2.0.3 at /Users/manu/development/flutter
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/manu/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • POCO F1 (mobile)        • e9ff6970                  • android-arm64 • Android 10 (API 29)
    • iPhone de Manu (mobile) • 00008101-001418913EE9003A • ios           • iOS 14.3

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@ManuLpz4 

1. Does the same crash occur if you don't use any of the 3rd party plugins like `riverpod` and `provider` ?
2. Looking at the error log:

`+36145 ms] E/MethodChannel#plugins.flutter.io/camera(25378): Failed to handle method call
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera(25378): java.lang.NullPointerException: Attempt to
invoke virtual method 'void
android.media.ImageReader.setOnImageAvailableListener(android.media.ImageReader$OnImageAvailableListene
r, android.os.Handler)' on a null object reference`

Can you confirm that you are not trying to access the camera controller before checking if it's null ? or  try to use `stopImageStream()` before disposing the controller, since it's an async operation.

3. If above still throws same exception, please provide a complete minimal reproducible code sample without any 3rd party plugins that we can directly use to verify the issue.

Thanks.

**Comment by ManuLpz4** [comment]
I tried it on a new app and realize that the error was calling _initializeCameraController in the initState and also with the FutureBuilder.

Thank you so much for your help 💙
