### ISSUE TITLE
Clear text crashed in android

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#78918]
b/183372823

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

final textEditingController = TextEditingController();

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(
            autofocus: true,
            controller: textEditingController,
            decoration: InputDecoration(
              suffixIcon: IconButton(
                icon: const Icon(Icons.cancel),
                onPressed: () => textEditingController.clear(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

1. run app in android
2. type something and tap clear

## Logs

<details>
<summary>Logs</summary>

```
I/flutter (14849): setSelection on TextSelection(baseOffset: 5, extentOffset: 5, affinity: TextAffinity.upstream, isDirectional: false) on value TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
E/MethodChannel#flutter/textinput(14849): Failed to handle method call
E/MethodChannel#flutter/textinput(14849): java.lang.IndexOutOfBoundsException: invalid selection start: 5
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:724)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput(14849): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput(14849): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput(14849): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter/textinput(14849): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter/textinput(14849): 	at android.app.ActivityThread.main(ActivityThread.java:6334)
E/MethodChannel#flutter/textinput(14849): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput(14849): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#flutter/textinput(14849): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

```
```

</details>

**Comment by chunhtai** [comment]
related https://github.com/flutter/flutter/issues/39376

**Comment by chunhtai** [comment]
close as duplicated
