### ISSUE TITLE
tutorial for Writing custom platform-specific code on android part does not work

### ISSUE THREAD

**Issue by matthewchung74** [flutter/flutter#78916]
## Steps to Reproduce

1. go through this tutorial https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-kotlin-tab#step-3-add-an-android-platform-specific-implementation and complete step 3
2. after all the kotlin code is pasted in, run the app in android simulator
3. see crash
4. note ios works fine

## Logs

<details>
<summary>Logs</summary>

```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(14616): FATAL EXCEPTION: main
E/AndroidRuntime(14616): Process: com.example.flutter_native, PID: 14616
E/AndroidRuntime(14616): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.flutter_native/com.example.flutter_native.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~l4zI0B2P-yy75yfw-1Ek3Q==/com.example.flutter_native-kmkYvukT8SeC0Lq6d-0YxA==/base.apk"],nativeLibraryDirectories=[/data/app/~~l4zI0B2P-yy75yfw-1Ek3Q==/com.example.flutter_native-kmkYvukT8SeC0Lq6d-0YxA==/lib/x86, /data/app/~~l4zI0B2P-yy75yfw-1Ek3Q==/com.example.flutter_native-kmkYvukT8SeC0Lq6d-0YxA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14616): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
E/AndroidRuntime(14616): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(14616): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(14616): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14616): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14616): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(14616): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14616): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14616): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(14616): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14616): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14616): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(14616): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~l4zI0B2P-yy75yfw-1Ek3Q==/com.example.flutter_native-kmkYvukT8SeC0Lq6d-0YxA==/base.apk"],nativeLibraryDirectories=[/data/app/~~l4zI0B2P-yy75yfw-1Ek3Q==/com.example.flutter_native-kmkYvukT8SeC0Lq6d-0YxA==/lib/x86, /data/app/~~l4zI0B2P-yy75yfw-1Ek3Q==/com.example.flutter_native-kmkYvukT8SeC0Lq6d-0YxA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14616): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(14616): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(14616): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(14616): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(14616): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
E/AndroidRuntime(14616): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(14616): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
E/AndroidRuntime(14616): 	... 11 more
E/AndroidRuntime(14738): FATAL EXCEPTION: main
E/AndroidRuntime(14738): Process: com.example.flutter_native, PID: 14738
E/AndroidRuntime(14738): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.flutter_native/com.example.flutter_native.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/base.apk"],nativeLibraryDirectories=[/data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/lib/x86, /data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14738): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
E/AndroidRuntime(14738): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(14738): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(14738): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14738): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14738): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(14738): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14738): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14738): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(14738): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14738): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(14738): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/base.apk"],nativeLibraryDirectories=[/data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/lib/x86, /data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14738): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(14738): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(14738): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(14738): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(14738): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
E/AndroidRuntime(14738): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(14738): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
E/AndroidRuntime(14738): 	... 11 more
E/AndroidRuntime(14809): FATAL EXCEPTION: main
E/AndroidRuntime(14809): Process: com.example.flutter_native, PID: 14809
E/AndroidRuntime(14809): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.flutter_native/com.example.flutter_native.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/base.apk"],nativeLibraryDirectories=[/data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/lib/x86, /data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14809): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
E/AndroidRuntime(14809): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(14809): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(14809): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14809): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14809): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(14809): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14809): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14809): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(14809): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14809): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14809): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(14809): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/base.apk"],nativeLibraryDirectories=[/data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/lib/x86, /data/app/~~7GuRHllzvxrfMRdep0nbLg==/com.example.flutter_native-e_IZvAuAOZqlnsnt2HGbKA==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14809): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(14809): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(14809): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(14809): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(14809): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
E/AndroidRuntime(14809): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(14809): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
E/AndroidRuntime(14809): 	... 11 more
E/AndroidRuntime(14905): FATAL EXCEPTION: main
E/AndroidRuntime(14905): Process: com.example.flutter_native, PID: 14905
E/AndroidRuntime(14905): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.flutter_native/com.example.flutter_native.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~06dGa3dAywLIxJweymz1zw==/com.example.flutter_native-MgzQXJdJerFUKGtDTIIijw==/base.apk"],nativeLibraryDirectories=[/data/app/~~06dGa3dAywLIxJweymz1zw==/com.example.flutter_native-MgzQXJdJerFUKGtDTIIijw==/lib/x86, /data/app/~~06dGa3dAywLIxJweymz1zw==/com.example.flutter_native-MgzQXJdJerFUKGtDTIIijw==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14905): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
E/AndroidRuntime(14905): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(14905): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(14905): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14905): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14905): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(14905): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14905): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14905): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(14905): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14905): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14905): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(14905): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~06dGa3dAywLIxJweymz1zw==/com.example.flutter_native-MgzQXJdJerFUKGtDTIIijw==/base.apk"],nativeLibraryDirectories=[/data/app/~~06dGa3dAywLIxJweymz1zw==/com.example.flutter_native-MgzQXJdJerFUKGtDTIIijw==/lib/x86, /data/app/~~06dGa3dAywLIxJweymz1zw==/com.example.flutter_native-MgzQXJdJerFUKGtDTIIijw==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14905): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(14905): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(14905): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(14905): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(14905): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
E/AndroidRuntime(14905): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(14905): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
E/AndroidRuntime(14905): 	... 11 more
E/AndroidRuntime(14991): FATAL EXCEPTION: main
E/AndroidRuntime(14991): Process: com.example.flutter_native, PID: 14991
E/AndroidRuntime(14991): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.flutter_native/com.example.flutter_native.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~o8DlrZHfOUPIyrgCWEmi3w==/com.example.flutter_native-KnaEeVIUJejrc2bRGTEQsg==/base.apk"],nativeLibraryDirectories=[/data/app/~~o8DlrZHfOUPIyrgCWEmi3w==/com.example.flutter_native-KnaEeVIUJejrc2bRGTEQsg==/lib/x86, /data/app/~~o8DlrZHfOUPIyrgCWEmi3w==/com.example.flutter_native-KnaEeVIUJejrc2bRGTEQsg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14991): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
E/AndroidRuntime(14991): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(14991): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(14991): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14991): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14991): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(14991): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14991): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14991): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(14991): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14991): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14991): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(14991): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~o8DlrZHfOUPIyrgCWEmi3w==/com.example.flutter_native-KnaEeVIUJejrc2bRGTEQsg==/base.apk"],nativeLibraryDirectories=[/data/app/~~o8DlrZHfOUPIyrgCWEmi3w==/com.example.flutter_native-KnaEeVIUJejrc2bRGTEQsg==/lib/x86, /data/app/~~o8DlrZHfOUPIyrgCWEmi3w==/com.example.flutter_native-KnaEeVIUJejrc2bRGTEQsg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(14991): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(14991): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(14991): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(14991): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(14991): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
E/AndroidRuntime(14991): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(14991): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
E/AndroidRuntime(14991): 	... 11 more
E/AndroidRuntime(15128): FATAL EXCEPTION: main
E/AndroidRuntime(15128): Process: com.example.flutter_native, PID: 15128
E/AndroidRuntime(15128): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.flutter_native/com.example.flutter_native.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~DAXlAJPcWvAtXtZh4jaosQ==/com.example.flutter_native-Bc_IOu2WWlNvL2mAvr8JHQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~DAXlAJPcWvAtXtZh4jaosQ==/com.example.flutter_native-Bc_IOu2WWlNvL2mAvr8JHQ==/lib/x86, /data/app/~~DAXlAJPcWvAtXtZh4jaosQ==/com.example.flutter_native-Bc_IOu2WWlNvL2mAvr8JHQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(15128): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
E/AndroidRuntime(15128): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(15128): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(15128): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(15128): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(15128): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(15128): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15128): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(15128): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(15128): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15128): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(15128): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(15128): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity" on path: DexPathList[[zip file "/data/app/~~DAXlAJPcWvAtXtZh4jaosQ==/com.example.flutter_native-Bc_IOu2WWlNvL2mAvr8JHQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~DAXlAJPcWvAtXtZh4jaosQ==/com.example.flutter_native-Bc_IOu2WWlNvL2mAvr8JHQ==/lib/x86, /data/app/~~DAXlAJPcWvAtXtZh4jaosQ==/com.example.flutter_native-Bc_IOu2WWlNvL2mAvr8JHQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(15128): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(15128): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(15128): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(15128): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(15128): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
E/AndroidRuntime(15128): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
E/AndroidRuntime(15128): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
E/AndroidRuntime(15128): 	... 11 more

```

</details>

**Comment by inceptusp** [comment]
Your log says : `Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.flutter_native.MainActivity"` which says that your kotlin file is missing the `package` name or your AndroidManifest is misconfigured, and the system is not finding the `MainActivity` class...

**Comment by matthewchung74** [comment]
apologies, i removed the package decaration at the top of file.

**Comment by matthewchung74** [comment]
@inceptusp I was hoping to ask a follow up question, is it possible to process the native code in a background thread, then go back to the main thread to finish execution of the channel method?

```
batteryChannel.setMethodCallHandler({
  [weak self] (call: FlutterMethodCall, result: FlutterResult) -> Void in
  // Note: this method is invoked on the UI thread.
  guard call.method == "getBatteryLevel" else {
    result(FlutterMethodNotImplemented)
    return
  }
  let dispatchQueue = DispatchQueue(label: "QueueIdentification", qos: .background)
    dispatchQueue.async{
      self?.receiveBatteryLevel(result: result)
    }
})
```
or does not a good practice?

**Comment by inceptusp** [comment]
@matthewchung74 it is possible but, I think, you should only do this if you're going to process a **synchronous, very expensive**, task which may block you're UI/main thread, otherwise, stick with doing things on the main thread...

If you're going to process a task on background native thread, then you should do as you said: call the methodChannel -> process your task on background -> pass the result to main thread and -> return it to Dart, finishing your methodChannel execution...
