### ISSUE TITLE
`flutter update-packages --force-upgrade` not working due to FileSystemException

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#78921]
I am trying to run `flutter update-packages --force-upgrade` to update the stocks app's dependencies for null safety, but am running into a FileSystemException about `${FLUTTER}/version`, even though I've checked and it's there.

cc/ @jonahwilliams Any ideas for this one?

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/shihaohong/dev/flutter/version' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:224:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:571:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:223:12)
#8      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:242:50)
<asynchronous suspension>
#9      UpdatePackagesCommand.runCommand (package:flutter_tools/src/commands/update_packages.dart:419:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
<asynchronous suspension>
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel unknown, 2.1.0-13.0.pre.224, on macOS 11.2.1 20D74
    darwin-x64, locale en)
    • Flutter version 2.1.0-13.0.pre.224 at /Users/shihaohong/dev/flutter
    • Framework revision 5029be0b9f (40 minutes ago), 2021-03-23 16:42:20 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/shihaohong/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8369
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

**Comment by jonahwilliams** [comment]
I'm not sure what causes this, but I've seen it happen when there are IDEs open

**Comment by shihaohong** [comment]
Wow, closing VSCode actually got it to work :) Should we keep the issue open?

**Comment by darshankawar** [comment]
Ran `flutter update-packages --force-upgrade` on latest stable version (3.3.4) of framework and didn't see the reported error.

<details>
<summary> console log </summary>

```
dhs@Dhss-MacBook-Pro test_app % flutter update-packages --force-upgrade
Upgrading packages...
WARNING: the following packages use hard-coded version constraints:
  - flutter_gallery_assets: 1.0.2
  - flutter_template_images: 4.1.0
  - video_player: 2.2.11
  - material_color_utilities: 0.1.5
Running "flutter pub upgrade" in flutter_update_packages.ZhXAcl...         6.6s
Ran pub get in dev/tools/vitool in 2.7s...
Ran pub get in dev/tools/gen_defaults in 3.8s...
Ran pub get in dev/tools/gen_keycodes in 3.8s...
Ran pub get in dev/integration_tests/deferred_components_test in 4.1s...
Ran pub get in dev/bots in 4.3s...
Ran pub get in dev/integration_tests/web in 1.0s...
Ran pub get in dev/integration_tests/web_compile_tests in 1.0s...
Ran pub get in dev/integration_tests/android_views in 4.8s...
Ran pub get in dev/integration_tests/ui in 5.3s...
Ran pub get in dev/tools in 5.9s...
Ran pub get in dev/integration_tests/ios_platform_view_tests in 3.3s...
Ran pub get in dev/integration_tests/release_smoke_test in 2.0s...
Ran pub get in dev/integration_tests/ios_add2app_life_cycle/flutterapp in 1.6s...
Ran pub get in dev/integration_tests/ios_app_with_extensions in 2.7s...
Ran pub get in dev/integration_tests/android_embedding_v2_smoke_test in 1.8s...
Ran pub get in dev/integration_tests/gradle_deprecated_settings in 2.0s...
Ran pub get in dev/integration_tests/external_ui in 3.6s...
Ran pub get in dev/integration_tests/non_nullable in 1.6s...
Ran pub get in dev/integration_tests/abstract_method_smoke_test in 0.9s...
Ran pub get in dev/integration_tests/flavors in 4.5s...
Ran pub get in dev/integration_tests/android_semantics_testing in 3.4s...
Ran pub get in dev/integration_tests/web_e2e_tests in 3.6s...
Ran pub get in dev/manual_tests in 1.7s...
Ran pub get in dev/integration_tests/flutter_gallery in 4.9s...
Ran pub get in dev/integration_tests/platform_interaction in 3.4s...
Ran pub get in dev/forbidden_from_release_tests in 0.9s...
Ran pub get in dev/customer_testing in 2.7s...
Ran pub get in dev/integration_tests/hybrid_android_views in 5.2s...
Ran pub get in dev/integration_tests/channels in 4.3s...
Ran pub get in dev/benchmarks/multiple_flutters/module in 1.8s...
Ran pub get in dev/tracing_tests in 3.6s...
Ran pub get in dev/devicelab in 4.3s...
Ran pub get in dev/benchmarks/complex_layout in 3.4s...
Ran pub get in dev/benchmarks/platform_views_layout_hybrid_composition in 3.8s...
Ran pub get in dev/benchmarks/microbenchmarks in 3.6s...
Ran pub get in dev/conductor/core in 3.2s...
Ran pub get in dev/benchmarks/platform_channels_benchmarks in 3.5s...
Ran pub get in dev/benchmarks/macrobenchmarks in 5.3s...
Ran pub get in dev/benchmarks/test_apps/stocks in 4.9s...
Ran pub get in examples/splash in 1.3s...
Ran pub get in dev/benchmarks/platform_views_layout in 4.7s...
Ran pub get in examples/platform_view in 1.2s...
Ran pub get in examples/flutter_view in 1.2s...
Ran pub get in examples/layers in 1.9s...
Ran pub get in dev/automated_tests in 4.5s...
Ran pub get in examples/image_list in 1.9s...
Ran pub get in packages/flutter_web_plugins in 1.9s...
Ran pub get in packages/integration_test/integration_test_macos in 1.1s...
Ran pub get in packages/flutter_goldens_client in 1.0s...
Ran pub get in packages/integration_test in 1.9s...
Ran pub get in examples/hello_world in 4.8s...
Ran pub get in examples/platform_channel_swift in 5.1s...
Ran pub get in packages/integration_test/example in 3.4s...
Ran pub get in packages/flutter/test_private in 1.0s...
Ran pub get in packages/flutter_tools/test/data/asset_test/main in 0.5s...
Ran pub get in examples/api in 4.6s...
Ran pub get in packages/flutter_goldens in 2.6s...
Ran pub get in packages/flutter/test_private/test in 1.7s...
Ran pub get in examples/platform_channel in 5.9s...
Ran pub get in packages/flutter in 1.7s...
Downloaded lcov data for package:flutter in 0.0s...
Ran pub get in packages/flutter_localizations in 1.6s...
Ran pub get in packages/flutter_test/test/test_config/project_root in 1.5s...
Ran pub get in packages/flutter_test in 1.4s...
Ran pub get in packages/fuchsia_remote_debug_protocol in 2.3s...
Ran pub get in packages/flutter_driver in 2.4s...
Ran pub get in packages/flutter_tools in 3.3s...
Running "flutter pub get" in affected packages...                  25.5s

Ran 'pub get' 66 times and fetched coverage data in 25.5s.
dhs@Dhss-MacBook-Pro test_app % 

```

</details>

Most probably migrating the tool to null safety might have fixed this error. Based on these findings, I am closing this issue.
If anybody disagrees, write in comments and I'll reopen it.
