### ISSUE TITLE
[tool_crash] SocketException: Failed to create datagram socket, OS Error: Address already in use, errno = 48

### ISSUE THREAD

**Issue by oncealong** [flutter/flutter#78937]
## Command
```
flutter attach
```

## Steps to Reproduce
1. run XCode and install app in iphone
2. flutter attach iphone
3. report crash

## Logs
SocketException: Failed to create datagram socket, OS Error: Address already in use, errno = 48
```
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:964:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-CN)
    • Flutter version 2.0.3 at /Users/along/flutter/flutter_stable
    • Framework revision 4d7946a68d (5 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/along/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/along/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio3.5.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Canary.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Users/along/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Along iPhone (mobile) • 00008030-000E24320AE3802E • ios            • iOS 14.3
    • macOS (desktop)       • macos                     • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 89.0.4389.90
    ! Error: Along iPhone is busy: Copying cache files from device. Xcode will continue when Along的iPhone is finished. (code -10)

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.edu.flutter
**iOS bundle identifier**: com.edu.flutter
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
flutter_ex
flutter_seekbar-96e16c007f0d9ce02aff90aa8a1a3667ab933dd7
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
sqflite-1.3.1+2

**Comment by darshankawar** [comment]
@oncealong 
Can you provide `flutter run --verbose` and `flutter attach --verbose` to get entire log ? If the log is too big, put that in a text file and share the file here.

**Comment by darshankawar** [comment]
Similar but closed due to inactivyt, https://github.com/flutter/flutter/issues/59748

May be [this](https://github.com/flutter/flutter/issues/59748#issuecomment-703796931) still holds true.

**Comment by oncealong** [comment]
flutter run --verbose:
[flutter_run_verbose.log](https://github.com/flutter/flutter/files/6211522/flutter_run_verbose.log)

flutter attach --verbose:
[flutter_attach_verbose.log](https://github.com/flutter/flutter/files/6211523/flutter_attach_verbose.log)

![image](https://user-images.githubusercontent.com/5340073/112626837-bb4d9200-8e6b-11eb-8635-a598858b8217.png)

**Comment by darshankawar** [comment]
> Similar but closed due to inactivity, #59748
> 
> May be [this](https://github.com/flutter/flutter/issues/59748#issuecomment-703796931) still holds true.
> 
> https://github.com/flutter/packages/blob/master/packages/multicast_dns/lib/multicast_dns.dart

Cc: @jmagman

**Comment by jmagman** [comment]
> May be [this](https://github.com/flutter/flutter/issues/59748#issuecomment-703796931) still holds true.

@darshankawar You're right, probably the same. It looks like the author closed #59748 but it should have been left open.

**Comment by percival888** [comment]
Encountered the same problem
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter attach

## exception

SocketException: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353

```
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:131:40)
<asynchronous suspension>
#2      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:63:7)
<asynchronous suspension>
#3      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:52)
<asynchronous suspension>
#4      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:277:11)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:224:5)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/shurui/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/shurui/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    ***
    • Chrome (web)        • chrome                                   •
      web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by percival888** [comment]
Encountered the same problem



## command

flutter attach

## exception

SocketException: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353

```
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:131:40)
<asynchronous suspension>
#2      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:63:7)
<asynchronous suspension>
#3      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:52)
<asynchronous suspension>
#4      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:277:11)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:224:5)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/shurui/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/shurui/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    •***的iPhone (mobile) • *** • ios
      • iOS 14.3 18C66
    • *** (2) (mobile)    • ***                • ios
      • iOS 15.3.1 19D52
    • Chrome (web)        • chrome                                   •
      web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by AlexeySpiridonov** [comment]
2022-09-08 12:40:17.024024+0700 Runner[7318:530985] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = 0.0.0.0, port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:110:40)
<asynchronous suspension>
#2      MDNSProvider.scan (package:wifi_extender2/modules/mdns/mdns_provider.dart:26:5)


the same error

**Comment by hmx-ltlam** [comment]
Hi guys, any update on this issue. 
I've got same error

**Comment by eleminer** [comment]
same error here

**Comment by SylberG** [comment]
any update?

**Comment by SasLuca** [comment]
If anyone is dealing with this problem, here is what worked for me.

I realized that some other process on my computer is using the port in the error message. For me the error messages looked like `SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353` so the problematic port was `5353`.

What I did was that I used `sudo lsof -t -i :5353` to find the pid of the processes using the port. Then used `ps -p [THE PID OF THE PROCESS] command` to see what the executables of those pids were, and just killed them with `sudo kill -9 [THE PID OF THE PROCESS]` and made sure they wont auto restart.

In my case I had 2 such processes, only one of which was actually causing the problem, they were `mDNSResponder` and `nxserver`.

`mDNSResponder` is a process from macos, and killing it doesn't work on its own as it will just restart, but it also doesn't seem to be causing this issue so you can leave it alone (at least this was the case for me).

`nxserver` was from a program called NoMachine that I use, and killing it plus making sure it wouldn't restart and take the port again (as at first it just restarted itself so I had to go into it's gui to fully stop it), solved my problem and now I can compile and debug the app from vscode again.

I wrote this response detailing my exact situation in hopes that anyone with a similar issue that ends up here may find this of use.

**Comment by berkaycatak** [comment]
> If anyone is dealing with this problem, here is what worked for me.
> 
> I realized that some other process on my computer is using the port in the error message. For me the error messages looked like `SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = , port = 5353` so the problematic port was `5353`.
> 
> What I did was that I used `sudo lsof -t -i :5353` to find the pid of the processes using the port. Then used `ps -p [THE PID OF THE PROCESS] command` to see what the executables of those pids were, and just killed them with `sudo kill -9 [THE PID OF THE PROCESS]` and made sure they wont auto restart.
> 
> In my case I had 2 such processes, only one of which was actually causing the problem, they were `mDNSResponder` and `nxserver`.
> 
> `mDNSResponder` is a process from macos, and killing it doesn't work on its own as it will just restart, but it also doesn't seem to be causing this issue so you can leave it alone (at least this was the case for me).
> 
> `nxserver` was from a program called NoMachine that I use, and killing it plus making sure it wouldn't restart and take the port again (as at first it just restarted itself so I had to go into it's gui to fully stop it), solved my problem and now I can compile and debug the app from vscode again.
> 
> I wrote this response detailing my exact situation in hopes that anyone with a similar issue that ends up here may find this of use.


Hello @SasLuca,  I've been dealing with this for days. When the "flutter run" command runs, the following three numbers are listed. When xcode is opened, "26973" is added. Should I run "sudo kill -9 26973" in this scenario?

```
250
385
4898
```

```
250
385
4898
26973
```

**Comment by SasLuca** [comment]
Are you running your flutter app from vscode? I am running from vscode right now and I only have 2 other processes using that port and xcode isnt one of them funnily enough. Maybe xcode is only using it when vscode builds the app and launches it?

I would use `ps -p [PID] command` to see what all those processes are and experiment with killing them, seeing if any restart, and then building the app from vscode. Cold restarting your mac to minimize the amount of processes could also help.

This sadly wasted a whole day for me as well.

**Comment by SasLuca** [comment]
Another tip, in case it is of use. On [another forum](https://github.com/docker/for-mac/issues/5335) I found references to this being an issue with "Internet Sharing" on macos and they advice disabling that in the settings.

This was already disabled for me but after some more investigations, I realized that what NoMachine was doing on my mac that was causing this issue was in fact a related feature, where it broadcasts it's availability on the network, which is probably similar to what the macos "Internet Sharing" feature does too.

Therefore I advise making sure "Internet Sharing" in macos settings is turned off (just type "internet sharing" in the search bar in the macos settings app to find it) and also checking if any of the processes using the problematic port are doing something like this.

**Comment by manylittlestorms** [comment]
> sudo lsof -t -i :5353

Thank you for your suggestion. In my case, the softwares which are using such port are Spotify and Kaspersky Antivirus. Hope this help more devs.

**Comment by Silfalion** [comment]
can confirm that forming it was noMachine causing the issue, I just quit the server(top right on the toolbar) and it worked

**Comment by KranthiBandla** [comment]
@SasLuca  

i am facing the same issue - OS Error: Address already in use, errno = 48

i totally tested in 6 phones it working fine in 4 phones but not in 2 phones

Working Phones

13 mini - osVersion: iOS 18.2, osVersionCode: 18.2
iphone SE - osVersion: iOS 16.6, osVersionCode: 16.6
iphone 12 - osVersion: iOS 18.1.1, osVersionCode: 18.1
iphone 11 - osVersion: iOS 17.5.1, osVersionCode: 17.5
 
Issue Facing Phones 
iphone 12 - osVersion: iOS 17.6.1, osVersionCode: 17.6
iphone 12 - osVersion: iOS 18.2.1, osVersionCode: 18.2


If anyone faced the same issue or has a solution please do share

**Comment by berkaycatak** [comment]
@KranthiBandla 

Hello, in my scenario I was getting this error due to the antivirus program. Close all programs open in the background and try again. This error occurs because a program is using the same port.

**Comment by KranthiBandla** [comment]
@berkaycatak  

Hi, but in my case for majority of iPhones its working, only for the few iPhones its not working. So i dont think something is wrong with laptop.
