### ISSUE TITLE
Calling clear() on TextEditingController causes an exception on Android

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#78978]
https://b.corp.google.com/issues/183372823.

Sample code
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

final textEditingController = TextEditingController();

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextFormField(
            autofocus: true,
            controller: textEditingController,
            decoration: InputDecoration(
              suffixIcon: IconButton(
                icon: const Icon(Icons.cancel),
                onPressed: () => textEditingController.clear(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

Stack trace
```
E/MethodChannel#flutter/textinput( 9823): Failed to handle method call
E/MethodChannel#flutter/textinput( 9823): java.lang.IndexOutOfBoundsException: invalid selection start: 4
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:724)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/textinput( 9823): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/textinput( 9823): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput( 9823): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/textinput( 9823): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutter/textinput( 9823): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#flutter/textinput( 9823): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 9823): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter/textinput( 9823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 9823): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, invalid selection start: 4, null, java.lang.IndexOutOfBoundsException: invalid selection start: 4
E/flutter ( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:724)
E/flutter ( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:680)
E/flutter ( 9823): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:91)
E/flutter ( 9823): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 9823): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 9823): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter ( 9823): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 9823): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 9823): 	at android.os.Looper.loop(Looper.java:174)
E/flutter ( 9823): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter ( 9823): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9823): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 9823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 9823): )
E/flutter ( 9823): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:164:7)
E/flutter ( 9823): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 9823): <asynchronous suspension>
E/flutter ( 9823): 
```

@jason-simmons notes that
"I had started looking at this and saw that it began with https://github.com/flutter/flutter/commit/a46139a2cef8144444a3e13a3970e9a267304b91

RenderEditable._setSelection is calling _setTextEditingValue with a value containing empty text, but with a selection offset based on the old text value before it was cleared."

**Comment by kf6gpe** [comment]
@HansMuller Mind having someone take a look, please? This is a high priority issue for both `customer: fun (g3)` and `customer: money (g3)`.

Thanks!

**Comment by justinmc** [comment]
This is also tracked here: https://github.com/flutter/flutter/issues/78918

@chunhtai has a fix open here: https://github.com/flutter/flutter/pull/78919

Let me take a look at why the tests are failing.  Otherwise it should be good to merge.
