### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Cannot build for windows_uwp_x64

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter#78979]
## Command
```
flutter run -d windows-uwp
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
UnsupportedError: Unsupported operation: Cannot build for windows_uwp_x64
```
#0      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:115:9)
#1      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:576:56)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#3      HotRunner.run (package:flutter_tools/src/run_hot.dart:350:34)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:651:26)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.234, on Microsoft Windows [version 10.0.19042.870], locale
    fr-FR)
    • Flutter version 2.1.0-13.0.pre.234 at C:\xxxxx\flutter
    • Framework revision 515ef91ba1 (4 hours ago), 2021-03-24 04:59:57 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\xxxxx
    • Platform android-S, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\xxxxx
    • Java binary at: C:\xxxxx
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\xxxxx

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\xxxxx
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\xxxxx
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86     • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64     • Microsoft Windows [version
      10.0.19042.870]
    • Windows (UWP) (desktop) • windows-uwp   • windows-uwp-x64 • Microsoft Windows [version
      10.0.19042.870] (unsupported)
    • Chrome (web)            • chrome        • web-javascript  • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript  • Microsoft Edge 89.0.774.57

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 2f05751973f3ddfb5462f5ff4136c573ba4f39c9

**Comment by jonahwilliams** [comment]
Did you specifically enabled UWP? Note that this work is not finished yet see https://github.com/flutter/flutter/issues/70211

**Comment by benedicte69** [comment]
Thank you @Jonah. Yes I did enable it. I understand the work is on the study.

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., mars 24, 2021 à 17:31, Jonah ***@***.***> a écrit :   


Did you specifically enabled UWP? Note that this work is not finished yet see #70211

**Comment by jonahwilliams** [comment]
OK, we're still not quite ready here - I'm going to close the issue as this feature is still a work in progress
