### ISSUE TITLE
ClipRRect intrinsic protocol violation

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7900]
If I remove the ClipRRect from my tree this assert goes away.

```
10:14:49.170: I/flutter ( 2553): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
10:14:49.174: I/flutter ( 2553): The following assertion was thrown during performLayout():
10:14:49.183: I/flutter ( 2553): The intrinsic dimension methods of the RenderFlex class returned values that violate the intrinsic
10:14:49.185: I/flutter ( 2553): protocol contract.
10:14:49.188: I/flutter ( 2553): The following failures was detected:
10:14:49.190: I/flutter ( 2553):  * getMinIntrinsicHeight(Infinity) returned a non-finite value: Infinity
10:14:49.192: I/flutter ( 2553):  * getMaxIntrinsicHeight(Infinity) returned a non-finite value: Infinity
10:14:49.195: I/flutter ( 2553):  * getMinIntrinsicHeight(48.0) returned a non-finite value: Infinity
10:14:49.197: I/flutter ( 2553):  * getMaxIntrinsicHeight(48.0) returned a non-finite value: Infinity
10:14:49.200: I/flutter ( 2553): If you are not writing your own RenderBox subclass, then this is not
10:14:49.202: I/flutter ( 2553): your fault. Contact support: https://github.com/flutter/flutter/issues/new
10:14:49.211: I/flutter ( 2553):
10:14:49.214: I/flutter ( 2553): When the exception was thrown, this was the stack:
10:14:49.220: I/flutter ( 2553): #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1639:11)
10:14:49.222: I/flutter ( 2553): #2      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1524:12)
10:14:49.225: I/flutter ( 2553): #3      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1424:7)
10:14:49.227: I/flutter ( 2553): #5      RenderBox.size= (package:flutter/src/rendering/box.dart:1423:12)
10:14:49.229: I/flutter ( 2553): #6      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:595:11)
10:14:49.232: I/flutter ( 2553): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1748:7)
10:14:49.234: I/flutter ( 2553): #8      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
10:14:49.237: I/flutter ( 2553): #9      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:974:24)
10:14:49.239: I/flutter ( 2553): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1748:7)
10:14:49.242: I/flutter ( 2553): #11     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:394:15)
10:14:49.244: I/flutter ( 2553): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1748:7)
10:14:49.247: I/flutter ( 2553): #13     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:209:13)
10:14:49.249: I/flutter ( 2553): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1748:7)
10:14:49.252: I/flutter ( 2553): #15     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:354:15)
10:14:49.254: I/flutter ( 2553): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1748:7)
10:14:49.257: I/flutter ( 2553): #17     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:556:17)
10:14:49.259: I/flutter ( 2553): #18     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1624:7)
10:14:49.261: I/flutter ( 2553): #19     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953:18)
10:14:49.264: I/flutter ( 2553): #20     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:224:19)
10:14:49.266: I/flutter ( 2553): #21     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:327:23)
10:14:49.269: I/flutter ( 2553): #22     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:169:5)
10:14:49.271: I/flutter ( 2553): #23     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676:15)
10:14:49.273: I/flutter ( 2553): #24     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611:9)
10:14:49.276: I/flutter ( 2553): #25     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
10:14:49.278: I/flutter ( 2553): (elided 2 frames from class _AssertionError)
10:14:49.281: I/flutter ( 2553):
10:14:49.283: I/flutter ( 2553): The following RenderObject was being processed when the exception was fired:
10:14:49.286: I/flutter ( 2553):   RenderFlex NEEDS-LAYOUT
10:14:49.288: I/flutter ( 2553):   creator: Column ← ClipRRect ← Positioned ← SimulatedFractional-[GlobalKey 792284277] ←
10:14:49.290: I/flutter ( 2553):   StoryPositioned ← Stack ← LayoutBuilder ← StoryPanels-[GlobalKey 313441056] ← Stack ← Expanded ←
10:14:49.293: I/flutter ( 2553):   Column ← SizedBox ← ⋯
10:14:49.295: I/flutter ( 2553):   parentData: <none>
10:14:49.297: I/flutter ( 2553):   constraints: BoxConstraints(w=80.0, h=48.0)
10:14:49.300: I/flutter ( 2553):   size: Size(80.0, 48.0)
10:14:49.302: I/flutter ( 2553):   direction: Axis.vertical
10:14:49.304: I/flutter ( 2553):   mainAxisAlignment: MainAxisAlignment.start
10:14:49.307: I/flutter ( 2553):   mainAxisSize: MainAxisSize.max
10:14:49.309: I/flutter ( 2553):   crossAxisAlignment: CrossAxisAlignment.stretch
10:14:49.312: I/flutter ( 2553):   textBaseline: null
10:14:49.314: I/flutter ( 2553): This RenderObject had the following descendants (showing up to depth 5):
10:14:49.316: I/flutter ( 2553):   RenderPadding relayoutBoundary=up1
10:14:49.319: I/flutter ( 2553):     RenderSemanticsGestureHandler relayoutBoundary=up2
10:14:49.321: I/flutter ( 2553):       RenderPointerListener relayoutBoundary=up3
10:14:49.324: I/flutter ( 2553):         RenderPadding relayoutBoundary=up4
10:14:49.326: I/flutter ( 2553):           RenderConstrainedBox relayoutBoundary=up5
10:14:49.328: I/flutter ( 2553):   RenderFractionallySizedOverflowBox
10:14:49.331: I/flutter ( 2553):     RenderDecoratedBox
10:14:49.333: I/flutter ( 2553):       RenderFittedBox
10:14:49.335: I/flutter ( 2553):         RenderConstrainedBox relayoutBoundary=up1
10:14:49.338: I/flutter ( 2553):           _RenderLayoutBuilder
10:14:49.340: I/flutter ( 2553): ════════════════════════════════════════════════════════════════════════════════════════════════════
10:14:49.342: I/flutter ( 2553): Another exception was thrown: The intrinsic dimension methods of the RenderClipRRect class returned values that violate the intrinsic protocol contract.
```

**Comment by apwilson** [comment]
Here's code to reproduce a similar issue:

```
  runApp(
    new FractionallySizedBox(
      widthFactor: 1.0,
      heightFactor: 0.0,
      child: new ClipRRect(
        borderRadius: new BorderRadius.all(new Radius.circular(4.0)),
        child: new SizedBox(
          width: 100.0,
          height: 100.0,
        ),
      ),
    ),
  );
```

**Comment by apwilson** [comment]
Note that setting the above code sample's hieghtFactor to 0.000001 eliminates the assert.

**Comment by jonahwilliams** [comment]
The above code no longer produces an assert, but I'm not able to pinpoint what was causing it in the first place. It's possible we've fixed the underlying problem, or that it could only be reproduced in different circumstances. I think that it is best closed for now, since we have little to no information on it, but if anyone disagrees feel free to reopen.
