### ISSUE TITLE
[web] time picker internal error by haptic feedback

### ISSUE THREAD

**Issue by leoshusar** [flutter/flutter#79013]
Time picker on web throws an error when it tries to trigger haptic feedback.

Happens by:
- clicking on dial
- selecting hours / minutes by those controls next to the dial
- switching am / pm in both dial mode and keyboard mode

Android doesn't have any issues.

I am using Flutter 2.1.0-12.2.pre, but I've also tried to downgrade to 2.0.1 and the problem was still there.

EDIT: I'm using null-safety

<details>
  <summary>Exception</summary>

```
Error: Expected a value of type 'String', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:58347/dart_sdk.js:5041:11)
    at Object.castError (http://localhost:58347/dart_sdk.js:5014:15)
    at Object.cast [as as] (http://localhost:58347/dart_sdk.js:5323:17)
    at Function.as (http://localhost:58347/dart_sdk.js:42554:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:58347/dart_sdk.js:156660:38)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:58347/dart_sdk.js:156576:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:58347/packages/flutter/src/services/system_channels.dart.lib.js:2197:38)
    at _DefaultBinaryMessenger.send (http://localhost:58347/packages/flutter/src/services/system_channels.dart.lib.js:2241:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:58347/packages/flutter/src/services/system_channels.dart.lib.js:965:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:58347/dart_sdk.js:37383:34)
    at Object._async [as async] (http://localhost:58347/dart_sdk.js:37414:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:58347/packages/flutter/src/services/system_channels.dart.lib.js:963:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:58347/packages/flutter/src/services/system_channels.dart.lib.js:1095:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:58347/packages/flutter/src/services/system_channels.dart.lib.js:1073:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:58347/dart_sdk.js:37383:34)
    at Object._async [as async] (http://localhost:58347/dart_sdk.js:37414:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:58347/packages/flutter/src/services/system_channels.dart.lib.js:1072:20)
    at vibrate (http://localhost:58347/packages/flutter/src/services/haptic_feedback.dart.lib.js:30:55)
    at vibrate.next (<anonymous>)
    at runBody (http://localhost:58347/dart_sdk.js:37383:34)
    at Object._async [as async] (http://localhost:58347/dart_sdk.js:37414:7)
    at Function.vibrate (http://localhost:58347/packages/flutter/src/services/haptic_feedback.dart.lib.js:29:20)
    at http://localhost:58347/packages/flutter/src/material/time_picker.dart.lib.js:8273:44
    at internalCallback (http://localhost:58347/dart_sdk.js:24214:11)
```
</details>

<details>
  <summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: () async {
        var a = await showTimePicker(
          context: context,
          initialTime: TimeOfDay(hour: 0, minute: 0),
        );
      },
      child: Text('test'),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

**flutter doctor -v**
```
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.867], locale cs-CZ)
    • Flutter version 2.1.0-12.2.pre at C:\Users\husar\AppData\Local\Flutter\SDK\flutter
    • Framework revision 5bedb7b1d5 (7 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\husar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.54.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @leoshusar 
Thanks for filing the issue, error isn't thrown running in non-null-safety, 

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      onPressed: () async {
        var a = await showTimePicker(
          context: context,
          initialTime: TimeOfDay(hour: 0, minute: 0),
        );
      },
      child: Text('test'),
    );
  }
}

``` 

</details>

<details> 
<summary>logs</summary> 

```bash
Launching lib\main.dart on Chrome in debug mode...
Debug service listening on ws://127.0.0.1:57288/jWiaQFOuYOM=/ws
 Running with sound null safety
Connecting to VM Service at ws://127.0.0.1:57288/jWiaQFOuYOM=/ws
Error: Expected a value of type 'String', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:57243/dart_sdk.js:5033:11)
    at Object.castError (http://localhost:57243/dart_sdk.js:5006:15)
    at Object.cast [as as] (http://localhost:57243/dart_sdk.js:5315:17)
    at Function.as (http://localhost:57243/dart_sdk.js:42547:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:57243/dart_sdk.js:156720:38)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:57243/dart_sdk.js:156633:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
    at _DefaultBinaryMessenger.send (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
    at vibrate (http://localhost:57243/packages/flutter/src/services/haptic_feedback.dart.lib.js:17:55)
    at vibrate.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at Function.vibrate (http://localhost:57243/packages/flutter/src/services/haptic_feedback.dart.lib.js:16:20)
    at http://localhost:57243/packages/flutter/src/material/time_picker.dart.lib.js:8110:44
    at internalCallback (http://localhost:57243/dart_sdk.js:24207:11)
Error: Expected a value of type 'String', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:57243/dart_sdk.js:5033:11)
    at Object.castError (http://localhost:57243/dart_sdk.js:5006:15)
    at Object.cast [as as] (http://localhost:57243/dart_sdk.js:5315:17)
    at Function.as (http://localhost:57243/dart_sdk.js:42547:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:57243/dart_sdk.js:156720:38)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:57243/dart_sdk.js:156633:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
    at _DefaultBinaryMessenger.send (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
    at vibrate (http://localhost:57243/packages/flutter/src/services/haptic_feedback.dart.lib.js:17:55)
    at vibrate.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at Function.vibrate (http://localhost:57243/packages/flutter/src/services/haptic_feedback.dart.lib.js:16:20)
    at http://localhost:57243/packages/flutter/src/material/time_picker.dart.lib.js:8110:44
    at internalCallback (http://localhost:57243/dart_sdk.js:24207:11)
Error: Expected a value of type 'String', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:57243/dart_sdk.js:5033:11)
    at Object.castError (http://localhost:57243/dart_sdk.js:5006:15)
    at Object.cast [as as] (http://localhost:57243/dart_sdk.js:5315:17)
    at Function.as (http://localhost:57243/dart_sdk.js:42547:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:57243/dart_sdk.js:156720:38)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:57243/dart_sdk.js:156633:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
    at _DefaultBinaryMessenger.send (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:57243/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
    at vibrate (http://localhost:57243/packages/flutter/src/services/haptic_feedback.dart.lib.js:17:55)
    at vibrate.next (<anonymous>)
    at runBody (http://localhost:57243/dart_sdk.js:37376:34)
    at Object._async [as async] (http://localhost:57243/dart_sdk.js:37407:7)
    at Function.vibrate (http://localhost:57243/packages/flutter/src/services/haptic_feedback.dart.lib.js:16:20)
    at http://localhost:57243/packages/flutter/src/material/time_picker.dart.lib.js:8110:44
    at internalCallback (http://localhost:57243/dart_sdk.js:24207:11)

```

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```


```bash
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.1.0-12.2.pre at C:\Users\Taha\Code\flutter_beta
    • Framework revision 5bedb7b1d5 (8 days ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```


```bash
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.1.0-12.1.pre at C:\Users\Taha\Code\flutter_dev
    • Framework revision 8264cb3e8a (2 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```


```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.261, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.1.0-13.0.pre.261 at C:\Users\Taha\Code\flutter_master
    • Framework revision b44e536c62 (6 hours ago), 2021-03-24 23:09:02 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Taha\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
```
	
</details>

Thank you

**Comment by enri90** [comment]
How long do we have to wait for this update? 
do i need to look for another plugin?

**Comment by leoshusar** [comment]
I don't know about stable, but in beta it's already fixed.
