### ISSUE TITLE
Custom widget makes crash while enable accessibility

### ISSUE THREAD

**Issue by Sasikumar3595** [flutter/flutter#79029]
I was created the custom widget used to show the children based on row and column count and the widget is interact-able. It makes exception while place the widget inside the popup menu item when accessibility enabled.

## Steps to Reproduce

1. Run the below sample with accessibility enabled
2. Exception will show

<details>
  <summary>Exception</summary>

```
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2651 pos 16: 'node.parent == null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2651:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1082:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:468:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)

```
</details>

<details>
  <summary>Sample Code</summary>

```dart

import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(PickerSample());

class PickerSample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: PickerSampleWidget(),
    );
  }
}

class PickerSampleWidget extends StatefulWidget {
  @override
  _PickerSampleWidgetState createState() => _PickerSampleWidgetState();
}

class _PickerSampleWidgetState extends State<PickerSampleWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: PopupMenuButton<int>(
            icon: Icon(Icons.calendar_today),
            itemBuilder: (BuildContext context) {
              return List.generate(1, (index) {
                return PopupMenuItem<int>(
                  value: index,
                  child: Container(
                    width: 250,
                    height: 250,
                    child: CustomWidget(),
                  ),
                );
              });
            }),
      ),
      body: Container(
          alignment: Alignment.center, child: Text('Popup menu button')),
    );
  }
}

class CustomWidget extends StatefulWidget {
  @override
  _CustomWidgetState createState() => _CustomWidgetState();
}

class _CustomWidgetState extends State<CustomWidget> {
  int _selectedIndex = -1;

  @override
  Widget build(BuildContext context) {
    final double width = MediaQuery.of(context).size.width;
    final double height = MediaQuery.of(context).size.height;
    return GestureDetector(
        behavior: HitTestBehavior.translucent,
        onTapUp: (TapUpDetails details) {
          final double xPosition = details.localPosition.dx;
          final double yPosition = details.localPosition.dy;
          final double viewWidth = width / 10;
          final double viewHeight = height / 5;
          final int row = yPosition ~/ viewHeight;
          final int column = xPosition ~/ viewWidth;
          setState(() {
            _selectedIndex = (row * 10) + column;
          });
        },
        child: Container(
          child: _MultiChildRenderObjectWidget(
            rowCount: 5,
            columnCount: 10,
            children: List.generate(50, (index) {
              return Container(
                color: _selectedIndex == index ? Colors.red : null,
                child: Center(
                    child: Text(
                  '$index',
                  style: Theme.of(context).textTheme.subtitle1,
                )),
              );
            }),
          ),
        ));
  }
}

class _MultiChildRenderObjectWidget extends MultiChildRenderObjectWidget {
  _MultiChildRenderObjectWidget(
      {this.rowCount,
      this.columnCount,
      List<Widget> children = const <Widget>[]})
      : super(children: children);

  final int rowCount;
  final int columnCount;

  @override
  _MultiChildRenderObject createRenderObject(BuildContext context) {
    return _MultiChildRenderObject(rowCount, columnCount);
  }

  @override
  void updateRenderObject(
      BuildContext context, _MultiChildRenderObject renderObject) {
    renderObject
      ..rowCount = rowCount
      ..columnCount = columnCount;
  }
}

class _ParentData extends ContainerBoxParentData<RenderBox> {}

class _MultiChildRenderObject extends RenderBox
    with ContainerRenderObjectMixin<RenderBox, _ParentData> {
  _MultiChildRenderObject(this._rowCount, this._columnCount);

  int _rowCount;

  int get rowCount => _rowCount;

  set rowCount(int value) {
    if (_rowCount == value) {
      return;
    }

    _rowCount = value;
    markNeedsLayout();
  }

  int _columnCount;

  int get columnCount => _columnCount;

  set columnCount(int value) {
    if (_columnCount == value) {
      return;
    }

    _columnCount = value;
    markNeedsLayout();
  }

  @override
  void setupParentData(covariant RenderObject child) {
    if (child.parentData is! _ParentData) {
      child.parentData = _ParentData();
    }
  }

  @override
  void performLayout() {
    final Size widgetSize = constraints.biggest;
    size = Size(widgetSize.width, widgetSize.height);
    RenderBox child = firstChild;
    if (child == null) {
      return;
    }

    final double cellWidth = size.width / _columnCount;
    final double cellHeight = size.height / _rowCount;
    while (child != null) {
      child.layout(constraints.copyWith(
          minHeight: cellHeight,
          maxHeight: cellHeight,
          minWidth: cellWidth,
          maxWidth: cellWidth));
      child = childAfter(child);
    }
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    final double cellWidth = size.width / _columnCount;
    final double cellHeight = size.height / _rowCount;
    RenderBox child = firstChild;
    if (child == null) {
      return;
    }

    double xPosition = offset.dx, yPosition = offset.dy;
    while (child != null) {
      if (xPosition + 1 >= size.width) {
        xPosition = offset.dx;
        yPosition += cellHeight;
      }

      child.paint(context, Offset(xPosition, yPosition));
      child = childAfter(child);
      xPosition += cellWidth;
    }
  }

  @override
  void describeSemanticsConfiguration(SemanticsConfiguration config) {
    super.describeSemanticsConfiguration(config);
    config.isSemanticBoundary = true;
  }

  @override
  void assembleSemanticsNode(
    SemanticsNode node,
    SemanticsConfiguration config,
    Iterable<SemanticsNode> children,
  ) {
    final List<CustomPainterSemantics> semantics = <CustomPainterSemantics>[];
    final double cellWidth = size.width / _columnCount;
    final double cellHeight = size.height / _rowCount;
    RenderBox child = firstChild;
    if (child == null) {
      return;
    }

    double xPosition = 0, yPosition = 0;
    int index = 0;
    while (child != null) {
      if (xPosition + 1 >= size.width) {
        xPosition = 0;
        yPosition += cellHeight;
      }

      semantics.add(CustomPainterSemantics(
        rect: Rect.fromLTWH(xPosition, yPosition, cellWidth, cellHeight),
        properties: SemanticsProperties(
          label: index.toString(),
          textDirection: TextDirection.ltr,
        ),
      ));
      child = childAfter(child);
      index++;
      xPosition += cellWidth;
    }

    final List<SemanticsNode> semanticsNodes = <SemanticsNode>[];
    for (int i = 0; i < semantics.length; i++) {
      final CustomPainterSemantics currentSemantics = semantics[i];
      final SemanticsNode newChild = SemanticsNode(key: currentSemantics.key);

      final SemanticsProperties properties = currentSemantics.properties;
      final SemanticsConfiguration config = SemanticsConfiguration();
      if (properties.label != null) {
        config.label = properties.label;
      }
      if (properties.textDirection != null) {
        config.textDirection = properties.textDirection;
      }

      newChild.updateWith(
        config: config,
        // As of now CustomPainter does not support multiple tree levels.
        childrenInInversePaintOrder: const <SemanticsNode>[],
      );

      newChild
        ..rect = currentSemantics.rect
        ..transform = currentSemantics.transform
        ..tags = currentSemantics.tags;

      semanticsNodes.add(newChild);
    }

    final List<SemanticsNode> finalChildren = <SemanticsNode>[];
    finalChildren.addAll(semanticsNodes);
    finalChildren.addAll(children);
    super.assembleSemanticsNode(node, config, finalChildren);
  }
}

```

</details>

**Expected results:** 

- Sample will run without making crash.

**Actual results:** 

- Sample makes crash.

**Comment by darshankawar** [comment]
Although it's not a crash, but throws below exception when trying to open `PopUpMenu` with accessibility ON. The widget is custom made. If we replace `CustomWidget()` with `Container()`, the exception doesn't occur.

<details>
<summary>console log</summary>

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2627 pos 16: 'node.parent == null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2627:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:458:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2641 pos 14: 'node.parent?._dirty != true': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2641:14)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:458:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
...
====================================================================================================

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by Indumathi1195R** [comment]
Hi Team,

Any update regarding this?

Regards,
Indumathi R

**Comment by exaby73** [comment]
Issue still persists on latest stable and master channels.

<details><summary>Exception</summary>

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3014 pos 16: 'node.parent ==
null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:3014:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1098:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:509:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#13     _invoke (dart:ui/hooks.dart:151:10)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#15     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(const PickerSample());

class PickerSample extends StatelessWidget {
  const PickerSample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: PickerSampleWidget(),
    );
  }
}

class PickerSampleWidget extends StatefulWidget {
  const PickerSampleWidget({Key? key}) : super(key: key);

  @override
  State<PickerSampleWidget> createState() => _PickerSampleWidgetState();
}

class _PickerSampleWidgetState extends State<PickerSampleWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: PopupMenuButton<int>(
            icon: const Icon(Icons.calendar_today),
            itemBuilder: (BuildContext context) {
              return List.generate(1, (index) {
                return PopupMenuItem<int>(
                  value: index,
                  child: const SizedBox(
                    width: 250,
                    height: 250,
                    child: CustomWidget(),
                  ),
                );
              });
            }),
      ),
      body: Container(
          alignment: Alignment.center, child: const Text('Popup menu button')),
    );
  }
}

class CustomWidget extends StatefulWidget {
  const CustomWidget({Key? key}) : super(key: key);

  @override
  State<CustomWidget> createState() => _CustomWidgetState();
}

class _CustomWidgetState extends State<CustomWidget> {
  int _selectedIndex = -1;

  @override
  Widget build(BuildContext context) {
    final double width = MediaQuery.of(context).size.width;
    final double height = MediaQuery.of(context).size.height;
    return GestureDetector(
      behavior: HitTestBehavior.translucent,
      onTapUp: (TapUpDetails details) {
        final double xPosition = details.localPosition.dx;
        final double yPosition = details.localPosition.dy;
        final double viewWidth = width / 10;
        final double viewHeight = height / 5;
        final int row = yPosition ~/ viewHeight;
        final int column = xPosition ~/ viewWidth;
        setState(() {
          _selectedIndex = (row * 10) + column;
        });
      },
      child: _MultiChildRenderObjectWidget(
        rowCount: 5,
        columnCount: 10,
        children: List.generate(
          50,
          (index) {
            return Container(
              color: _selectedIndex == index ? Colors.red : null,
              child: Center(
                child: Text(
                  '$index',
                  style: Theme.of(context).textTheme.subtitle1,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

class _MultiChildRenderObjectWidget extends MultiChildRenderObjectWidget {
  _MultiChildRenderObjectWidget({
    required this.rowCount,
    required this.columnCount,
    List<Widget> children = const <Widget>[],
  }) : super(children: children);

  final int rowCount;
  final int columnCount;

  @override
  _MultiChildRenderObject createRenderObject(BuildContext context) {
    return _MultiChildRenderObject(rowCount, columnCount);
  }

  @override
  void updateRenderObject(
      BuildContext context, _MultiChildRenderObject renderObject) {
    renderObject
      ..rowCount = rowCount
      ..columnCount = columnCount;
  }
}

class _ParentData extends ContainerBoxParentData<RenderBox> {}

class _MultiChildRenderObject extends RenderBox
    with ContainerRenderObjectMixin<RenderBox, _ParentData> {
  _MultiChildRenderObject(this._rowCount, this._columnCount);

  int _rowCount;

  int get rowCount => _rowCount;

  set rowCount(int value) {
    if (_rowCount == value) {
      return;
    }

    _rowCount = value;
    markNeedsLayout();
  }

  int _columnCount;

  int get columnCount => _columnCount;

  set columnCount(int value) {
    if (_columnCount == value) {
      return;
    }

    _columnCount = value;
    markNeedsLayout();
  }

  @override
  void setupParentData(covariant RenderObject child) {
    if (child.parentData is! _ParentData) {
      child.parentData = _ParentData();
    }
  }

  @override
  void performLayout() {
    final Size widgetSize = constraints.biggest;
    size = Size(widgetSize.width, widgetSize.height);
    RenderBox? child = firstChild;
    if (child == null) {
      return;
    }

    final double cellWidth = size.width / _columnCount;
    final double cellHeight = size.height / _rowCount;
    while (child != null) {
      child.layout(
        constraints.copyWith(
          minHeight: cellHeight,
          maxHeight: cellHeight,
          minWidth: cellWidth,
          maxWidth: cellWidth,
        ),
      );
      child = childAfter(child);
    }
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    final double cellWidth = size.width / _columnCount;
    final double cellHeight = size.height / _rowCount;
    RenderBox? child = firstChild;
    if (child == null) {
      return;
    }

    double xPosition = offset.dx, yPosition = offset.dy;
    while (child != null) {
      if (xPosition + 1 >= size.width) {
        xPosition = offset.dx;
        yPosition += cellHeight;
      }

      child.paint(context, Offset(xPosition, yPosition));
      child = childAfter(child);
      xPosition += cellWidth;
    }
  }

  @override
  void describeSemanticsConfiguration(SemanticsConfiguration config) {
    super.describeSemanticsConfiguration(config);
    config.isSemanticBoundary = true;
  }

  @override
  void assembleSemanticsNode(
    SemanticsNode node,
    SemanticsConfiguration config,
    Iterable<SemanticsNode> children,
  ) {
    final List<CustomPainterSemantics> semantics = <CustomPainterSemantics>[];
    final double cellWidth = size.width / _columnCount;
    final double cellHeight = size.height / _rowCount;
    RenderBox? child = firstChild;
    if (child == null) {
      return;
    }

    double xPosition = 0, yPosition = 0;
    int index = 0;
    while (child != null) {
      if (xPosition + 1 >= size.width) {
        xPosition = 0;
        yPosition += cellHeight;
      }

      semantics.add(
        CustomPainterSemantics(
          rect: Rect.fromLTWH(xPosition, yPosition, cellWidth, cellHeight),
          properties: SemanticsProperties(
            label: index.toString(),
            textDirection: TextDirection.ltr,
          ),
        ),
      );
      child = childAfter(child);
      index++;
      xPosition += cellWidth;
    }

    final List<SemanticsNode> semanticsNodes = <SemanticsNode>[];
    for (int i = 0; i < semantics.length; i++) {
      final CustomPainterSemantics currentSemantics = semantics[i];
      final SemanticsNode newChild = SemanticsNode(key: currentSemantics.key);

      final SemanticsProperties properties = currentSemantics.properties;
      final SemanticsConfiguration config = SemanticsConfiguration();
      if (properties.label != null) {
        config.label = properties.label ?? '';
      }
      if (properties.textDirection != null) {
        config.textDirection = properties.textDirection;
      }

      newChild.updateWith(
        config: config,
        // As of now CustomPainter does not support multiple tree levels.
        childrenInInversePaintOrder: const <SemanticsNode>[],
      );

      newChild
        ..rect = currentSemantics.rect
        ..transform = currentSemantics.transform
        ..tags = currentSemantics.tags;

      semanticsNodes.add(newChild);
    }

    final List<SemanticsNode> finalChildren = <SemanticsNode>[];
    finalChildren.addAll(semanticsNodes);
    finalChildren.addAll(children);
    super.assembleSemanticsNode(node, config, finalChildren);
  }
}
```

</details>

**Comment by chunhtai** [comment]
Can you try to cache the semantics node you created in the assemblesemanticsnode? I suspect this is because some information dropped when you recreate the node everytime the method is called.

**Comment by chunhtai** [comment]
also cc @hannah-hyj can you take a look if you have time?
