### ISSUE TITLE
Bad state exception occurs with widget tests that focus on or try to enter text for offstage input text fields

### ISSUE THREAD

**Issue by MaikuB** [flutter/flutter#79033]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update `lib/main.dart` to have the following code so that the app has an offstage `TextFormField`

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
            home: Material(
              child: Offstage(
                child: TextFormField(),
              ),
            ),
          );
  }
}
```

Update `test/widget_test.dart` to execute a widget test that can focus on the offstage `TextFormField`

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:bug/main.dart';

void main() {
  testWidgets('Focus on offstage text form field', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp());

    final offstageTextFormFieldFinder =
        find.byType(TextFormField, skipOffstage: false);
    expect(offstageTextFormFieldFinder, findsOneWidget);

    await tester.showKeyboard(offstageTextFormFieldFinder);
  });
}
```

3. Run `flutter test` to execute the widget test

**Expected results:** 

The widget test successfully passes

**Actual results:**

The widget test fails. It can find the offstage `TextFormField` (i.e. the part of the widget test code that says `expect(offstageTextFormFieldFinder, findsOneWidget);` passes) but an exception gets thrown upon calling `await tester.showKeyboard(offstageTextFormFieldFinder);`. Included the exception details as part of the logs. This exception also impacts the ability to write a widget test that enters text in an offstage text input field and can cause confusion since the input field can be located via the finder. I've created a PR with a proposed fix for this at https://github.com/flutter/flutter/pull/79034

<details>
  <summary>Logs</summary>

_Exception details_

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:498:25)
#1      WidgetController.state (package:flutter_test/src/controller.dart:154:42)
#2      WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1031:42)
#3      WidgetTester.showKeyboard.<anonymous closure> (package:flutter_test/src/widget_tester.dart:1030:39)
#6      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#7      WidgetTester.showKeyboard (package:flutter_test/src/widget_tester.dart:1030:27)
#8      main.<anonymous closure> (file:///Users/michaelbui/Projects/bug/test/widget_test.dart:15:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)
```

```
```

```
```

_Output of running `flutter doctor -v`_
```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.234, on macOS 11.2.3 20D91
    darwin-x64, locale en-AU)
    • Flutter version 2.1.0-13.0.pre.234 at /Users/michaelbui/flutter
    • Framework revision 515ef91ba1 (23 hours ago), 2021-03-24 04:59:57 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/michaelbui/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 11.2.3
      20D91 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome
      89.0.4389.90
```

</details>

**Comment by pedromassangocode** [comment]
<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.261, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.261 at /Users/pedromassango/Code/flutter_master
    • Framework revision b44e536c62 (24 minutes ago), 2021-03-24 23:09:02 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • AE2F4F51-880E-44FB-BB29-171B766D9B54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>
