### ISSUE TITLE
Help Want: Linux Build No flutter/generated_plugins.cmake File

### ISSUE THREAD

**Issue by MateusAmin** [flutter/flutter#79045]
Going to see if I can replicate this on a fresh project.

## Steps to Reproduce

1.  Have a working app running on Linux
2.  Add URL launcher. Have trouble loading the plugin.
3.  Delete and  attempt to recreate ./linux on Master using:
```sh
flutter create --platforms linux .
```
4. Get error because it does not like that you named the parent dir flutter  /project/flutter/<flutter-app>
5. Change parent to be  /project/project/<flutter-app>
6. Successfully run create command
7. 
 ```sh
flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
CMake Error at CMakeLists.txt:69 (include):                             
  include could not find load file:                                     
                                                                        
    flutter/generated_plugins.cmake                                     
                                                                        
                                                                        
Building Linux application...                                           
Exception: Unable to generate build files
```

## Logs

<details>
<summary>Logs</summary>

```
flutter run -d -v linux
[  +42 ms] executing: uname -m
[  +22 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: [/home/mea/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e34f3b013f3bd1aa8b00bab20a40f5a544560d60
[        ] executing: [/home/mea/snap/flutter/common/flutter/] git tag --points-at e34f3b013f3bd1aa8b00bab20a40f5a544560d60
[  +14 ms] Exit code 0 from: git tag --points-at e34f3b013f3bd1aa8b00bab20a40f5a544560d60
[   +1 ms] executing: [/home/mea/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags e34f3b013f3bd1aa8b00bab20a40f5a544560d60
[  +31 ms] Exit code 0 from: git describe --match *.*.* --long --tags e34f3b013f3bd1aa8b00bab20a40f5a544560d60
[        ] 2.1.0-12.0.pre-264-ge34f3b013f
[   +5 ms] executing: [/home/mea/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/mea/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +68 ms] executing: [/home/mea/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +35 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +40 ms] executing: /home/mea/Android/Sdk/platform-tools/adb devices -l
[  +25 ms] List of devices attached
[   +1 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[   +8 ms] "flutter run" took 89ms.
[  +11 ms] Target file "linux" not found.
[   +2 ms] 
           #0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:1322:9)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:445:19)
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1148:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +105 ms] ensureAnalyticsSent: 104ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

```
flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-13.0.pre.264, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.264 at /home/mea/snap/flutter/common/flutter
    • Framework revision e34f3b013f (6 hours ago), 2021-03-25 10:22:57 +0100
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/mea/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /snap/android-studio/100/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /snap/android-studio/100/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

</details>

**Comment by MateusAmin** [comment]
Huh, 

```sh
flutter create --platforms linux .
```

Creates a different set of files in the new project

**Comment by MateusAmin** [comment]
Mirror dependencies and SDK version. Still no reproduction.

**Comment by MateusAmin** [comment]
Is flutter clean missing something?

**Comment by MateusAmin** [comment]
So flutter pub get also fails to write the .flutter-plugins files

**Comment by MateusAmin** [comment]
Yes, flutter pub get and flutter create outputs are different between the projects. Even with a flutter clean and identical pub spec.

**Comment by MateusAmin** [comment]
I am just going to make a new project and move the code. Let me see

**Comment by MateusAmin** [comment]
I don't see errors in the -v output for flutter pub get and the like btw. Just lack of certain outputs

**Comment by MateusAmin** [comment]
and dirs have same permission

**Comment by MateusAmin** [comment]
Remaking the project worked. Really not sure what the diff was.
