### ISSUE TITLE
Flutter Driver Web (Chrome) error - Unable to open X display

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#79072]
Flutter driver possibly launches chrome in headful mode and throws `Unable to open X display` when run on CI.

## Steps to Reproduce

```
  chromedriver --port=4444 &
  
  flutter driver --driver test_driver/integration_test.dart \
  --target ./integration_test/<integration_test>.dart \
  --browser-name chrome \
  --release --headless --verbose
```

<details>

<summary>Logs (shortened) </summary>

```
[ +484 ms] [CHROME]:[1932:1932:0325/183944.043155:ERROR:browser_main_loop.cc(1390)] Unable to open X display.
[  +20 ms] Failed to launch browser. Command used to launch it: google-chrome --user-data-dir=/tmp/flutter_tools.WMPCNM/flutter_tools_chrome_device.TOXMYS --remote-debugging-port=37521 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:40439
[   +4 ms] "flutter drive" took 39,145ms.
[   +3 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.
[        ] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:270:11)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1325:9)
           #3      _rootRun (dart:async/zone.dart:1346:47)
           #4      _CustomZone.run (dart:async/zone.dart:1258:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
           #10     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
           #11     _rootRun (dart:async/zone.dart:1346:47)
           #12     _CustomZone.run (dart:async/zone.dart:1258:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
[   +2 ms] ensureAnalyticsSent: 0ms
           #17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #21     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #22     _rootRun (dart:async/zone.dart:1346:47)
           #23     _CustomZone.run (dart:async/zone.dart:1258:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #28     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #34     _rootRun (dart:async/zone.dart:1346:47)
           #35     _CustomZone.run (dart:async/zone.dart:1258:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #40     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:741:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:589:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2151:21)
           #44     _rootRunUnary (dart:async/zone.dart:1370:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:607:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:554:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1687:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1185:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

```
</details>

### Complete logs

[Run integration tests.txt](https://github.com/flutter/flutter/files/6207194/Run.integration.tests.txt)

**Comment by darshankawar** [comment]
@sidrao2006 

So even if we pass `--headless`, it treats it as `headful` mode ?

Could it be that the browser version isn't updated in CI which is why it could be throwing `Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge.` ?

Does the same scenario work locally on your machine ?

**Comment by sidrao2006** [comment]
> So even if we pass `--headless`, it treats it as `headful` mode ?
Yes. `Unable to open X display` is a headful chrome error

**Comment by sidrao2006** [comment]
> Does the same scenario work locally on your machine ?

Chrome 89 stable with matching chrome driver does work locally

**Comment by sidrao2006** [comment]
```shell
          echo 'Google Chrome Version -'
          google-chrome --version

          chromedriver --port=4444 --verbose &

          flutter driver --driver test_driver/integration_test.dart \
          --target ./integration_test/dynamic_cached_fonts_example_test.dart \
          --browser-name chrome \
          --dart-define FIREBASE_STORAGE_FONT_URL=$FIREBASE_STORAGE_FONT_URL \
          --release --headless --verbose
```

[Virtual environment info](https://github.com/actions/virtual-environments/blob/ubuntu20/20210318.0/images/linux/Ubuntu2004-README.md)

Flutter version - 2.1.0-12.2.pre-beta

[integration tests.log](https://github.com/flutter/flutter/files/6210241/integration.tests.log)

Also confirmed that there is no version mismatch between the browser and the driver.

Google Chrome | 89.0.4389.90 
-- | --
ChromeDriver | 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294})

**Comment by darshankawar** [comment]
@sidrao2006 
I am wondering if this is an issue at CI side or a chrome driver or chromium issue, since locally it works as you said. Look at below links, although not related to Flutter, but same issue `Unable to open X display`:

https://stackoverflow.com/questions/60304251/unable-to-open-x-display-when-trying-to-run-google-chrome-on-centos-rhel-7-5

https://github.com/puppeteer/puppeteer/issues/5429

**Comment by sidrao2006** [comment]
puppeteer/puppeteer#5429 is an issue related to Chrome not launching in headful mode. In that case again, is flutter launching chrome in headful mode?

**Comment by sidrao2006** [comment]
@darshankawar Thanks

https://stackoverflow.com/questions/60304251/unable-to-open-x-display-when-trying-to-run-google-chrome-on-centos-rhel-7-5 proved to be helpful
