### ISSUE TITLE
Playback error E/ExoPlayerImplInternal(12774):  MediaCodecVideoRenderer error using Video Player Apps freeze

### ISSUE THREAD

**Issue by ajosecueto** [flutter/flutter#79106]
## Details

1. I'm using video-player in a listview this videos are play and pause when has some visibilty in the screen, but some time the app freeze when that error happen. I'm calling videos from S3 with signed url

2.  A simple list that sometime can make this error....

3.  happen in master channel and real devices with flutter version <= 2

Occurs in Android emualtor api 30, in real devices any...
## Logs

<details>
<summary>Logs</summary>

```
I/MediaCodec(12774): (0x7c90e09a00) kWhatStartCompleted
E/ExoPlayerImplInternal(12774): Playback error
E/ExoPlayerImplInternal(12774):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [360, 644, 30.002842], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal(12774):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(12774):       at android.os.Looper.loop(Looper.java:241)
E/ExoPlayerImplInternal(12774):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(12774):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.Exynos.AVC.Decoder
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1377)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:872)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal(12774):       ... 3 more
E/ExoPlayerImplInternal(12774):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal(12774):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/ExoPlayerImplInternal(12774):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:58)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1774)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:857)
E/ExoPlayerImplInternal(12774):       ... 5 more
I/MediaCodec(12774): (0x7c92015a00) flush
E/ExoPlayerImplInternal(12774): Disable failed.
E/ExoPlayerImplInternal(12774):   java.lang.IllegalStateException
E/ExoPlayerImplInternal(12774):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal(12774):       at android.media.MediaCodec.flush(MediaCodec.java:2194)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:81)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:914)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:773)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:454)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:175)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1507)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1254)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1218)
E/ExoPlayerImplInternal(12774):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:546)
E/ExoPlayerImplInternal(12774):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(12774):       at android.os.Looper.loop(Looper.java:241)
E/ExoPlayerImplInternal(12774):       at android.os.HandlerThread.run(HandlerThread.java:67)
```

</details>

**Comment by TahaTesser** [comment]
Hi @ajosecueto 
Can you please provide your `flutter doctor -v`  and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
