### ISSUE TITLE
Attempted to send a key down event when no keys are in keysPressed

### ISSUE THREAD

**Issue by dwivedikunal100** [flutter/flutter#79125]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Run app in mac os 
3. click on app to focus

**Expected results:** 
No error
**Actual results:** 
Error

```
When the exception was thrown, this was the stack:
#2      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:626:12)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:221:15)
#10     _invoke3 (dart:ui/hooks.dart:220:10)
#11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457:7)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
(elided 5 frames from class _AssertionError and dart:async)
```

**Comment by darshankawar** [comment]
@dwivedikunal100 
Can you elaborate on point # 3 `click on app to focus`, like what exactly we need to do (steps) to replicate it ?
Also, can you provide `flutter doctor -v` ?

**Comment by dwivedikunal100** [comment]
Hi @darshankawar 
I am not able to reproduce the bug atm.
However, steps to reproduce were. 
1. Run flutter create bug
2. Run app on mac os
3. Click on the app or maximise the app

You can close the issue for now if its not easily reproducible. I will reopen it, if I see it again
Thanks

**Comment by dwivedikunal100** [comment]
Got this error again on maximising
```
════════ Exception caught by services library ══════════════════════════════════
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#65bc6(logicalKey: LogicalKeyboardKey#700e0(keyId: "0x1000700e0", keyLabel: "", debugName: "Control Left"), physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left")) and its data: RawKeyEventDataMacOs(keyLabel: , keyCode: 59, characters: , unmodifiedCharacters: , modifiers: 0, modifiers down: {})
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 626 pos 12: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'
```

**Comment by dwivedikunal100** [comment]
flutter doctor -v

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.3 at /Users/dwikunal/personal_workplace/mac_flutter
    • Framework revision 4d7946a68d (8 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dwikunal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90


• No issues found!
    
```


Repetitive Exceptions

```
When the exception was thrown, this was the stack:
#2      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:626:12)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:221:15)
#10     _invoke3 (dart:ui/hooks.dart:220:10)
#11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457:7)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags.
This was the event: RawKeyDownEvent#f3cfb(logicalKey: LogicalKeyboardKey#700e0(keyId: "0x1000700e0", keyLabel: "", debugName: "Control Left"), physicalKey:
PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left")) and its data: RawKeyEventDataMacOs(keyLabel: , keyCode: 59, characters: , unmodifiedCharacters: , modifiers:
0, modifiers down: {})
```

**Comment by darshankawar** [comment]
@dwivedikunal100 
Tried replicating following your steps you mentioned, but didn't see the said exception. The app maximizes without throwing any exception.

```
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
Activating Dart DevTools...                                      2,845ms
Syncing files to device macOS...                                    57ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on macOS is available at:
http://127.0.0.1:49805/UiTXVojtUAo=/

Flutter DevTools, a Flutter debugger and profiler, on macOS is available at:
http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A49805%2FUiTXVojtUAo%3D%2F

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Application finished.
dhs@Dhss-MacBook-Pro macbug % 
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (10 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by dwivedikunal100** [comment]
Hi @darshankawar  did you try on BigSur?
I created a sample project and was facing the same issue with this one also https://github.com/dwivedikunal100/pomodoro-todo

**Comment by darshankawar** [comment]
@dwivedikunal100 
Yes, @TahaTesser verified the same on BigSur and he didn't get the said exception.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0
[✓] Connected device (3 available)
    • Taha's iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 89.0.4389.90
• No issues found!

```

</details>

**Comment by dwivedikunal100** [comment]
Got it, yeah can't say since you are not able to reproduce it.
You can close the issue and someone can reopen if found again.

**Comment by darshankawar** [comment]
Closing this as not reproducible and based on your comment above.
