### ISSUE TITLE
path_provider for ios is not supported

### ISSUE THREAD

**Issue by coumarane** [flutter/flutter#79130]
When adding path_provider of any version in my flutter project, the ios version of my app raise error while running the command "flutter run".
I tried several solution proposed from different forum and blog but still the error is persist.

And I remove this package everything is working perfectly.

Find below the log error:

```
Launching lib/main.dart on iPhone 11 in debug mode...
Running pod install...                                           1,935ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A path_provider

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing path_provider (0.0.1)
      - Running pre install hooks

    Generating Pods project
      - Creating Pods project
      - Installing files into Pods project
        - Adding source files
        - Adding frameworks
        - Adding libraries
        - Adding resources
        - Adding development pod helper files
        - Linking headers
      - Installing Pod Targets
        - Installing target `Flutter` iOS 8.0
        - Installing target `path_provider` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/path_provider/path_provider.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/path_provider/path_provider-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/path_provider/path_provider-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/path_provider/path_provider-dummy.m`
      - Installing Aggregate Targets
        - Installing target `Pods-Runner` iOS 11.0
          - Generating Info.plist file at `Pods/Target Support Files/Pods-Runner/Pods-Runner-Info.plist`
          - Generating module map file at `Pods/Target Support Files/Pods-Runner/Pods-Runner.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/Pods-Runner/Pods-Runner-umbrella.h`
          - Generating dummy source at `Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m`
      - Generating deterministic UUIDs
      - Stabilizing target UUIDs
      - Running post install hooks
    [!] An error occurred while processing the post-install hook of the Podfile.

    undefined method `each_child' for #<Dir:0x007fd7c4178178>
    Did you mean?  each_slice

    /Users/coumar/flutter/packages/flutter_tools/bin/podhelper.rb:54:in `block in flutter_additional_ios_build_settings'
    /Users/coumar/flutter/packages/flutter_tools/bin/podhelper.rb:51:in `each'
    /Users/coumar/flutter/packages/flutter_tools/bin/podhelper.rb:51:in `flutter_additional_ios_build_settings'
    /Users/coumar/Documents/Dev/sawyouu/sawyouu-app-flutter/ios/Podfile:41:in `block (3 levels) in from_ruby'
    /Users/coumar/Documents/Dev/sawyouu/sawyouu-app-flutter/ios/Podfile:40:in `each'
    /Users/coumar/Documents/Dev/sawyouu/sawyouu-app-flutter/ios/Podfile:40:in `block (2 levels) in from_ruby'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Users/coumar/.rvm/gems/ruby-2.4.0@global/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /Users/coumar/.rvm/gems/ruby-2.4.0/bin/pod:22:in `load'
    /Users/coumar/.rvm/gems/ruby-2.4.0/bin/pod:22:in `<main>'
    /Users/coumar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
    /Users/coumar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:899:in `rescue in run_podfile_post_install_hook'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Users/coumar/.rvm/gems/ruby-2.4.0@global/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /Users/coumar/.rvm/gems/ruby-2.4.0/bin/pod:22:in `load'
    /Users/coumar/.rvm/gems/ruby-2.4.0/bin/pod:22:in `<main>'
    /Users/coumar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
    /Users/coumar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

Error running pod install
Error launching application on iPhone 11.
```

```
Analyzing dependencies
Downloading dependencies
Installing Flutter (1.0.0)
Installing path_provider (0.0.1)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `each_child' for #<Dir:0x007f9aff1b7b18>
Did you mean?  each_slice

/Users/coumar/flutter/packages/flutter_tools/bin/podhelper.rb:54:in `block in flutter_additional_ios_build_settings'
/Users/coumar/flutter/packages/flutter_tools/bin/podhelper.rb:51:in `each'
/Users/coumar/flutter/packages/flutter_tools/bin/podhelper.rb:51:in `flutter_additional_ios_build_settings'
/Users/coumar/Documents/Dev/sawyouu/sawyouu-app-flutter/ios/Podfile:40:in `block (3 levels) in from_ruby'
/Users/coumar/Documents/Dev/sawyouu/sawyouu-app-flutter/ios/Podfile:39:in `each'
/Users/coumar/Documents/Dev/sawyouu/sawyouu-app-flutter/ios/Podfile:39:in `block (2 levels) in from_ruby'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/coumar/.rvm/gems/ruby-2.4.0@global/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/coumar/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/coumar/.rvm/gems/ruby-2.4.0/bin/pod:22:in `load'
/Users/coumar/.rvm/gems/ruby-2.4.0/bin/pod:22:in `<main>'
/Users/coumar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/coumar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by darshankawar** [comment]
@coumarane 
You seem to be using an older version of `ruby-2.4.0` which doesn't support `each_child` method, that is causing your `pod install` to fail. 

You need to upgrade to latest ruby version which 2.6.0 that supports the said method. Once you upgrade it, run `flutter run` again and see if it resolves your issue.

**Comment by coumarane** [comment]
Changed the version of ruby and it works perfectly.
