### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by Arshdeep-ceo** [flutter/flutter#79198]
## Command
```
flutter create todoey
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      ErrorHandlingFile.writeAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:255:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#7      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:254:5)
#8      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:259:30)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#10     Template.render (package:flutter_tools/src/template.dart:193:24)
#11     CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:387:21)
<asynchronous suspension>
#12     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:23)
<asynchronous suspension>
#13     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:31)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.450], locale en-IN)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (3 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Arsh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.54.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.146
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment]
@Arshdeep-ceo 
does this possible [solution](https://github.com/flutter/flutter/issues/71043#issuecomment-732761331) fix the issue?

**Comment by darshankawar** [comment]
@Arshdeep-ceo 
Try [this](https://github.com/flutter/flutter/issues/69537#issuecomment-720322550) solution and see if it works for you.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
