### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/xarvis/Developer/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.

### ISSUE THREAD

**Issue by Ashraful11** [flutter/flutter#79207]
## Command
```
flutter --quiet assemble --depfile /Users/xarvis/AndroidStudioProjects/hangman/build/app/intermediates/flutter/release/flutter_build.d --output /Users/xarvis/AndroidStudioProjects/hangman/build/app/intermediates/flutter/release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/xarvis/Developer/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:232:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
```
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-IN)
    • Flutter version 2.0.3 at /Users/xarvis/Developer/flutter
    • Framework revision 4d7946a68d (9 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/xarvis/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • B7841DBB-CF3A-4983-ACF2-6A0440C6C325 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d7946a68d26794349189cf21b3f68cc6fe61dcb
### Plugins
audioplayers-0.16.2
firebase_admob-0.9.3+4
firebase_core-0.4.5
firebase_core_web-0.1.1+2
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
sqflite-1.3.2+4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by iapicca** [comment]
@Ashraful11 
could you try with the latest `master`
possibly fixed by https://github.com/flutter/flutter/pull/78272

**Comment by darshankawar** [comment]
Original issue, https://github.com/flutter/flutter/issues/68475, was fixed by above referred PR.
@Ashraful11 Try to switch to latest master and try again to see if issue persists or not.

```
flutter channel master
flutter upgrade

```

**Comment by Ashraful11** [comment]
Thanks! It Worked..

**Comment by yelkamel** [comment]
It's work for me too ! thanks for the help.

Someone know when that will be available in channel stable ?
