### ISSUE TITLE
FLUTTER WEB DOES NOT SUPPORTS MAP<> DATA STRUCTURE!

### ISSUE THREAD

**Issue by mohammedbabelly** [flutter/flutter#79205]
```void main() {
  Map<String, String> map;
  map['name'] = 'Name';
  map['age'] = 'age';
  print(map['name']);
  print(map['age']);
  runApp(MyApp());
}```

that's the main function
and this is the log:

```TypeError: Cannot read property 'Symbol(dartx._set)' of null
    at main$ (http://localhost:50740/packages/signalr_client/main.dart.lib.js:122:8)
    at main (http://localhost:50740/web_entrypoint.dart.lib.js:36:29)
    at main.next (<anonymous>)
    at http://localhost:50740/dart_sdk.js:39182:33
    at _RootZone.runUnary (http://localhost:50740/dart_sdk.js:39039:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:50740/dart_sdk.js:34025:29)
    at handleValueCallback (http://localhost:50740/dart_sdk.js:34585:49)
    at Function._propagateToListeners (http://localhost:50740/dart_sdk.js:34623:17)
    at _Future.new.[_completeWithValue] (http://localhost:50740/dart_sdk.js:34465:23)
    at http://localhost:50740/dart_sdk.js:33676:46
    at _RootZone.runUnary (http://localhost:50740/dart_sdk.js:39039:58)
    at _FutureListener.then.handleValue (http://localhost:50740/dart_sdk.js:34025:29)
    at handleValueCallback (http://localhost:50740/dart_sdk.js:34585:49)
    at Function._propagateToListeners (http://localhost:50740/dart_sdk.js:34623:17)
    at _Future.new.[_completeWithValue] (http://localhost:50740/dart_sdk.js:34465:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50740/dart_sdk.js:34488:35)
    at Object._microtaskLoop (http://localhost:50740/dart_sdk.js:39326:13)
    at _startMicrotaskLoop (http://localhost:50740/dart_sdk.js:39332:13)
    at http://localhost:50740/dart_sdk.js:34839:9
```

**Comment by mohammedbabelly** [comment]
= {};
//Shit

**Comment by pks050505** [comment]
map has initial value null and null don't have any  method to access
