### ISSUE TITLE
[BUG][Image_Picker] Image picker MissingPluginException for version 0.6.7+22 but not 0.7.0

### ISSUE THREAD

**Issue by sendwin** [flutter/flutter#79216]
I'm trying to use Image_picker: 0.6.7+22 because of multiple dependencies that prevent me updating to 0.7.0, but when trying to use getImage() I get:

```Error: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
    at Object.throw_ [as throw] (http://localhost:43121/dart_sdk.js:5334:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:43121/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:43121/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:43121/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:43121/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:43121/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:43121/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:43121/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:43121/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:43121/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:43121/dart_sdk.js:39182:13)
    at http://localhost:43121/dart_sdk.js:34689:9
```

Reproducible code:
**main.dart:**
```import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ImagePicker picker = ImagePicker();

  Future<void> getImage() async {
    final PickedFile pickedFile =
    await picker.getImage(source: ImageSource.gallery);
    print(pickedFile);
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: getImage,
        tooltip: 'image',
        child: Icon(Icons.add),
      ), 
    );
  }
}
```
Using`image_picker: ^0.6.7+22` in pubspec.yaml dependencies

**Expected Behaviour (which occurs using image_picker: ^0.7.0):**
Pressing the floating action button opens up gallery/ file explorer

**Actual Behaviour:**
Above message shown- MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)

**flutter doctor -v output:**

[✓] Flutter (Channel beta, 2.0.1, on Linux, locale en_AU.UTF-8)
    • Flutter version 2.0.1 at [...]
    • Framework revision c5a4b4029c (3 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at [...]
    • Platform android-30, build-tools 30.0.0
    • Java binary at: [...]
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at [...]
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /snap/intellij-idea-ultimate/285
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

Is image_picker <0.7.0 still supported?

Thanks in advance

**Comment by iapicca** [comment]
possible duplicate of https://github.com/flutter/flutter/issues/78625

**Comment by darshankawar** [comment]
@sendwin 
Tried your code sample using latest stable on iPhone which worked properly and didn't throw the error you mentioned.

```
Launching lib/main.dart on Darshan's iphone in debug mode...
Found saved certificate choice "Apple Development: Darshan Kawar (HJWLFNL782)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Darshan Kawar (HJWLFNL782)"
Running Xcode build...
Xcode build done.                                           10.6s
Installing and launching...
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
[VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
Debug service listening on ws://127.0.0.1:53139/kzlsAR0QcqM=/ws
Syncing files to device Darshan's iphone...
flutter: null
flutter: null
flutter: null
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (10 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by sendwin** [comment]
I think my problem was trying to run the app in Chrome simulator which required the image_picker_for_web additional package.
