### ISSUE TITLE
[tool_crash] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise,

### ISSUE THREAD

**Issue by occn8** [flutter/flutter#79225]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.3 at /usr/lib/flutter
    • Framework revision 4d7946a68d (10 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/occn8/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8962f6dc68ec8e2206ac2fa874da4a453856c7d3

**Comment by iapicca** [comment]
@occn8 
I'm surprised to see this [issue](https://github.com/flutter/flutter/issues/75565#issuecomment-774521089)  outside a `snap` ,
installation, maybe isn't even the same

can you please run 

```
flutter config --enable-web
flutter create issue
cd issue
flutter run -d chrome
```

and provide the output of the last command, 
if the logs are too verbose consider attaching it as `.txt` file

**Comment by occn8** [comment]
[verbose.txt](https://github.com/flutter/flutter/files/6220596/verbose.txt)

**Comment by pedromassangocode** [comment]
From the logs in the OP:


```bash
[   +4 ms] "flutter run" took 28,068ms.
[   +7 ms] Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge.
Otherwise,
           consider using -d web-server instead and filing an issue at
           https://github.com/flutter/flutter/issues.
[   +1 ms] 
           #0      ChromiumLauncher._spawnChromiumProcess.<anonymous closure>
           (package:flutter_tools/src/web/chrome.dart:278:11)
           #1      _runUserCode (dart:async/stream_pipe.dart:11:23)
           #2      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1325:9)
           #3      _rootRun (dart:async/zone.dart:1346:47)
           #4      _CustomZone.run (dart:async/zone.dart:1258:19)
           #5      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #6      _BufferingStreamSubscription._sendDone.sendDone
(dart:async/stream_impl.dart:394:13)
           #7      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #9      _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
           #10     _ForwardingStreamSubscription._handleDone
(dart:async/stream_pipe.dart:161:13)
           #11     _rootRun (dart:async/zone.dart:1346:47)
           #12     _CustomZone.run (dart:async/zone.dart:1258:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #14     _BufferingStreamSubscription._sendDone.sendDone
(dart:async/stream_impl.dart:394:13)
           #15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #17     _SinkTransformerStreamSubscription._close
(dart:async/stream_transformers.dart:87:11)
           #18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #19     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #20     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
           #21     _SinkTransformerStreamSubscription._handleDone
           (dart:async/stream_transformers.dart:132:24)
           #22     _rootRun (dart:async/zone.dart:1346:47)
           #23     _CustomZone.run (dart:async/zone.dart:1258:19)
           #24     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #25     _BufferingStreamSubscription._sendDone.sendDone
(dart:async/stream_impl.dart:394:13)
           #26     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #27     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #28     _SinkTransformerStreamSubscription._close
(dart:async/stream_transformers.dart:87:11)
           #29     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #30     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #31     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #32     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #33     _SinkTransformerStreamSubscription._handleDone
           (dart:async/stream_transformers.dart:132:24)
           #34     _rootRun (dart:async/zone.dart:1346:47)
           #35     _CustomZone.run (dart:async/zone.dart:1258:19)
           #36     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
           #37     _BufferingStreamSubscription._sendDone.sendDone
(dart:async/stream_impl.dart:394:13)
           #38     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
           #39     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #40     _SyncStreamControllerDispatch._sendDone
(dart:async/stream_controller.dart:741:19)
           #41     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
           #42     _StreamController.close (dart:async/stream_controller.dart:589:5)
           #43     _Socket._onData (dart:io-patch/socket_patch.dart:2151:21)
           #44     _rootRunUnary (dart:async/zone.dart:1370:13)
           #45     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
           #46     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
           #47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #49     _SyncStreamControllerDispatch._sendData
(dart:async/stream_controller.dart:733:19)
           #50     _StreamController._add (dart:async/stream_controller.dart:607:7)
           #51     _StreamController.add (dart:async/stream_controller.dart:554:5)
           #52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1687:35)
           #53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1185:18)
           #54     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
           #57     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:185:5)
           
           
[ +330 ms] ensureAnalyticsSent: 324ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +26 ms] Shutdown hooks complete
[ +128 ms] exiting with code 1
```

**Comment by jmagman** [comment]
```
[  +18 ms] [CHROME]:[0329/121456.962346:ERROR:nacl_helper_linux.cc(307)] NaCl helper process
running without a sandbox!
[        ] [CHROME]:Most likely you need to configure your SUID sandbox correctly
```
@occn8 How did you install Chrome? https://stackoverflow.com/questions/24237933/compile-execute-chromium-failed-due-to-suid-sandbox-issue

**Comment by jmagman** [comment]
Until chrome can be launched via
```
$ google-chrome
--user-data-dir=/tmp/flutter_tools.EFBDAK/flutter_tools_chrome_device.PHEILB
--remote-debugging-port=38019 --disable-background-timer-throttling --disable-extensions
--disable-popup-blocking --bwsi --no-first-run --no-default-browser-check
--disable-default-apps --disable-translate http://localhost:41571
```
Flutter isn't going to be able to launch it.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by occn8** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue.
> We are therefore reluctantly going to close this bug for now.
> Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.
> 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

Okay
