### ISSUE TITLE
Unable to build ios release build in production flavor

### ISSUE THREAD

**Issue by kjawadDeveloper** [flutter/flutter#79234]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios --flavor prod -t lib/main_prod.dart

## exception

_Exception: Exception: Source directory "/Users/jawad/Desktop/rns/cahero/build/ios/Release-iphoneos/Runner.app" does not exist, nothing to copy

```
#0      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:67:7)
#1      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:427:23)
<asynchronous suspension>
#2      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:105:43)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#11     ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#29     IosProject.hostAppBundleName (package:flutter_tools/src/project.dart)
#30     _rootRunUnary (dart:async/zone.dart:1198:47)
#31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#36     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#37     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#38     IosProject._parseHostAppBundleName (package:flutter_tools/src/project.dart)
#39     _rootRunUnary (dart:async/zone.dart:1198:47)
#40     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#44     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#45     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#46     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#47     IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart)
#48     _rootRunUnary (dart:async/zone.dart:1198:47)
#49     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#50     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#51     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#52     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#53     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#54     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#55     _rootRun (dart:async/zone.dart:1190:13)
#56     _CustomZone.run (dart:async/zone.dart:1093:19)
#57     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#58     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/jawad/fvm/versions/stable
    • Framework revision 9b2d32b605 (9 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jawad/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/jawad/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 202.8070

[✓] Connected device (1 available)
    • TECNO KC3 (mobile) • 04826259AN002250 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@kjawadDeveloper 
Does it generate crash log, something like `flutter_01.log` ? If so, can you attach it here ?
Also, what files are present in `cahero/build/ios/Release-iphoneos` ?

**Comment by kjawadDeveloper** [comment]
Here it is 
[flutter_01.log](https://github.com/flutter/flutter/files/6221459/flutter_01.log)

**Comment by darshankawar** [comment]
@kjawadDeveloper 

1. Can you upgrade to latest stable (2.0.3) and try again to see if issue persists or not ?
2. Can you provide the files that are present at `cahero/build/ios/Release-iphoneos ?`

**Comment by kjawadDeveloper1** [comment]
![Uploading Screenshot 2021-04-13 at 5.59.02 PM.png…]()

**Comment by kjawadDeveloper1** [comment]
Right now we cannot upgrade to 2.0.3 . It started happening after we introduced flavors to our app .

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
