### ISSUE TITLE
Null check operator used on a null value  sliver_multi_box_adaptor.dart

### ISSUE THREAD

**Issue by yy1300326388** [flutter/flutter#79256]
## Steps to Reproduce
The specific steps cannot be reproduced, but there are a lot of errors in the error statistics platform.

## Error logs

```
RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:568:36)
#1      RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:630:36)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#3      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#4      RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:273:15)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#7      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:641:17)
#8      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
#9      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:452:7)
#10     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:632:15)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
#12     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
#13     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#14     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
#15     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:438:19)
#16     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
#17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#20     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#21     _rootRun (dart:async/zone.dart:1190:13)
#22     _CustomZone.run (dart:async/zone.dart:1093:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#24     _invoke (dart:ui/hooks.dart:251:10)
#25     _drawFrame (dart:ui/hooks.dart:209:3)
```
- https://github.com/flutter/flutter/issues/66250

## Flutter version

```
Flutter (Channel unknown, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.6 at /Users/zero/sdk/flutter
    • Framework revision 9b2d32b605 (9 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

![image](https://user-images.githubusercontent.com/8764899/112814556-fe994200-90b1-11eb-92d4-15972ff53fa4.png)

**Comment by iapicca** [comment]
@yy1300326388 
does the issue persist upgrading to the latest stable?
```console
flutter channel stable
flutter upgrade -f
```

**Comment by pedromassangocode** [comment]
Hi @yy1300326388 
Please upgrade to the latest stable version and try again. If the issue persists, please try to provide a minimal reproducible code sample that reproduces the issue. The isn't much we can do without a reproducible code sample.
Thank you

**Comment by yy1300326388** [comment]
@pedromassangocode 
Ok, I’ll close it temporarily, because I cannot upgrade to the latest version for testing. If there are problems later, I will open a new problem and copy the available examples

**Comment by etienn01** [comment]
I'm having the exact same issue on Flutter 2.2.2 (and 2.3.0-24.0.pre as well), on an Android TV app.
I'm seeing it on Firebase Crashlytics but was unable to reproduce it myself. The app is [open-source](https://gitlab.com/etienn01/flauncher), if that's any help.

Here are two sample stacktraces when the crash is happening:
<details>
<summary>Stacktrace</summary>

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at RenderSliverMultiBoxAdaptor.childMainAxisPosition(RenderSliverMultiBoxAdaptor.java:567)
       at RenderSliverMultiBoxAdaptor.paint(RenderSliverMultiBoxAdaptor.java:635)
       at RenderObject._paintWithContext(RenderObject.java:2396)
       at PaintingContext.paintChild(PaintingContext.java:187)
       at RenderSliverEdgeInsetsPadding.paint(RenderSliverEdgeInsetsPadding.java:274)
       at RenderObject._paintWithContext(RenderObject.java:2396)
       at PaintingContext.paintChild(PaintingContext.java:187)
       at RenderViewportBase._paintContents(RenderViewportBase.java:654)
       at PaintingContext.pushLayer(PaintingContext.java:394)
       at PaintingContext.pushClipRect(PaintingContext.java:450)
       at RenderViewportBase.paint(RenderViewportBase.java:635)
       at RenderObject._paintWithContext(RenderObject.java:2396)
       at PaintingContext._repaintCompositedChild(PaintingContext.java:139)
       at PaintingContext.repaintCompositedChild(PaintingContext.java:100)
       at PipelineOwner.flushPaint(PipelineOwner.java:975)
       at RendererBinding.drawFrame(RendererBinding.java:464)
       at WidgetsBinding.drawFrame(WidgetsBinding.java:879)
       at RendererBinding._handlePersistentFrameCallback(RendererBinding.java:328)
       at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1143)
       at SchedulerBinding.handleDrawFrame(SchedulerBinding.java:1080)
       at SchedulerBinding._handleDrawFrame(SchedulerBinding.java:996)
```
</details>

<details>
<summary>Stacktrace</summary>

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at RenderSliverMultiBoxAdaptor.childMainAxisPosition(RenderSliverMultiBoxAdaptor.java:567)
       at RenderSliverHelpers.applyPaintTransformForBoxChild(RenderSliverHelpers.java:1684)
       at RenderSliverMultiBoxAdaptor.applyPaintTransform(RenderSliverMultiBoxAdaptor.java:593)
       at RenderObject.getTransformTo(RenderObject.java:2477)
       at FocusNode.rect(FocusNode.java:752)
       at DirectionalFocusTraversalPolicyMixin._sortAndFilterHorizontally.<fn>(_sortAndFilterHorizontally.java:546)
       at ._insertionSort(.java:218)
       at .mergeSort(.java:157)
       at DirectionalFocusTraversalPolicyMixin._sortAndFilterHorizontally(DirectionalFocusTraversalPolicyMixin.java:546)
       at DirectionalFocusTraversalPolicyMixin.inDirection(DirectionalFocusTraversalPolicyMixin.java:763)
       at FocusNode.focusInDirection(FocusNode.java:1161)
       at DirectionalFocusAction.invoke(DirectionalFocusAction.java:1950)
       at ActionDispatcher.invokeAction(ActionDispatcher.java:520)
       at ShortcutManager.handleKeypress(ShortcutManager.java:835)
       at _ShortcutsState._handleOnKey(_ShortcutsState.java:1174)
       at FocusManager._handleRawKeyEvent(FocusManager.java:1677)
       at RawKeyboard._handleKeyEvent(RawKeyboard.java:682)
       at BasicMessageChannel.setMessageHandler.<fn>(setMessageHandler.java:73)
       at BasicMessageChannel.setMessageHandler.<fn>(setMessageHandler.java:72)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(setMessageHandler.java:323)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(setMessageHandler.java:320)
```
</details>

@pedromassango Should I open a new issue?

@yy1300326388 did you find any solution?

**Comment by pedromassango** [comment]
I would recommend opening a new issue only if you have the steps to reproduce.

It won't help filling an issue like this is there is no steps to reproduce. At most it would get closed
