### ISSUE TITLE
FileSystemException: writeFrom failed, path = '' (OS Error: The handle is invalid. , errno = 6)

### ISSUE THREAD

**Issue by Tlotliso-Wiinc** [flutter/flutter#79260]
My flutter installation has been working perfectly all along, and I did not change anything apart from installing windows 10 updates recently. Now, a few months later (since I last worked on my flutter project) when I try to run `flutter run` in my flutter project, I get the following error:

```Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: The handle is invalid.
, errno = 6)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:870:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:309:15)
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:8
08:19)
#8      _StreamController._add (dart:async/stream_controller.dart:682:7)
#9      _StreamController.add (dart:async/stream_controller.dart:624:5)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:156:17)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:289:5)
#12     _StdSink.write (dart:io/stdio.dart:338:11)
#13     Stdio._stdioWrite.<anonymous closure> (package:flutter_tools/src/base/io.dar
t:348:12)
#14     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.d
art:111:32)
#15     _rootRun (dart:async/zone.dart:1190:13)
#16     _CustomZone.run (dart:async/zone.dart:1093:19)
#17     _runZoned (dart:async/zone.dart:1630:10)
#18     runZonedGuarded (dart:async/zone.dart:1618:12)
#19     runZoned (dart:async/zone.dart:1547:12)
#20     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#21     Stdio._stdioWrite (package:flutter_tools/src/base/io.dart:347:5)
#22     Stdio.stdoutWrite (package:flutter_tools/src/base/io.dart:333:7)
#23     StdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:271:4
8)
#24     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:266:5)
#25     VerboseLogger._emit (package:flutter_tools/src/base/logger.dart:644:14)
#26     VerboseLogger.printTrace (package:flutter_tools/src/base/logger.dart:578:5)
#27     _DefaultProcessUtils._traceCommand (package:flutter_tools/src/base/process.d
art:595:15)
#28     _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:41
8:5)
#29     _runGit (package:flutter_tools/src/version.dart:665:23)
#30     new FlutterVersion (package:flutter_tools/src/version.dart:54:26)
#31     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.d
art:138:29)
#32     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/s
rc/base/context.dart:104:41)
#33     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291
:23)
#34     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart
:92:20)
#35     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#36     AppContext.get (package:flutter_tools/src/base/context.dart:119:23)
#37     flutterVersion (package:flutter_tools/src/globals.dart:86:46)
#38     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/s
rc/runner/flutter_command_runner.dart:298:25)
<asynchronous suspension>
#39     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/s
rc/runner/flutter_command_runner.dart)
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.d
art:150:29)
#41     _rootRun (dart:async/zone.dart:1190:13)
#42     _CustomZone.run (dart:async/zone.dart:1093:19)
#43     _runZoned (dart:async/zone.dart:1630:10)
#44     runZoned (dart:async/zone.dart:1550:10)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#46     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_co
mmand_runner.dart:282:19)
<asynchronous suspension>
#47     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:
25)
#48     new Future.sync (dart:async/future.dart:223:31)
#49     CommandRunner.run (package:args/command_runner.dart:112:14)
#50     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_r
unner.dart:231:18)
#51     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.da
rt:69:22)
#52     _rootRun (dart:async/zone.dart:1190:13)
#53     _CustomZone.run (dart:async/zone.dart:1093:19)
#54     _runZoned (dart:async/zone.dart:1630:10)
#55     runZonedGuarded (dart:async/zone.dart:1618:12)
#56     runZoned (dart:async/zone.dart:1547:12)
#57     run.<anonymous closure> (package:flutter_tools/runner.dart:67:18)
<asynchronous suspension>
#58     run.<anonymous closure> (package:flutter_tools/runner.dart)
#59     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:62
:18)
<asynchronous suspension>
#60     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#61     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.d
art:150:29)
#62     _rootRun (dart:async/zone.dart:1190:13)
#63     _CustomZone.run (dart:async/zone.dart:1093:19)
#64     _runZoned (dart:async/zone.dart:1630:10)
#65     runZoned (dart:async/zone.dart:1550:10)
#66     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#67     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
#68     run (package:flutter_tools/runner.dart:52:10)
#69     main (package:flutter_tools/executable.dart:73:9)
#70     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutt
er_tools.dart:8:3)
#71     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299
:32)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:16
8:12)```

**Comment by pedromassangocode** [comment]
Hi @Tlotliso-Wiinc 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`?
Thank you

**Comment by Tlotliso-Wiinc** [comment]
When I run `flutter run --verbose`, I get the exact same error I posted above. Another thing, I seem to get that error when I run any kind of flutter command including `flutter doctor -v`

**Comment by pedromassangocode** [comment]
Hi @Tlotliso-Wiinc 
Are you sure that it does not print anything else?
Are you running from an IDE or Terminal? Can you please try on Terminal?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
