### ISSUE TITLE
[video_player] The getter for '_isDisposed' is not available

### ISSUE THREAD

**Issue by reverie-ss** [flutter/flutter#79275]
## Use case

I have a list of videos which **plays** whenever visible on screen and **pauses** if not on screen.
If visible: `videoPlayerController.play()`
else : `videoPlayerController.pause()`

The video is  **disposed**  whenever the widget disposes.

```@override
void dispose() {
    videoPlayerController.dispose();
    super.dispose();
}
```

I noticed sometimes the `videoPlayerController.pause()` is called after video is disposed, and it throws the following error:

>E/flutter (21016): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: A VideoPlayerController was used after being disposed.
E/flutter (21016): Once you have called dispose() on a VideoPlayerController, it can no longer be used.
E/flutter (21016): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
E/flutter (21016): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
E/flutter (21016): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:234:12)
E/flutter (21016): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:309:5)
E/flutter (21016): #4      VideoPlayerController.pause (package:video_player/video_player.dart:393:5)
E/flutter (21016): #5      _VideoWidgetState.build.<anonymous closure>.<anonymous closure> (package:XYZ/activities/posts_page.dart:738:41)
E/flutter (21016): #6      VisibilityDetectorLayer._fireCallback (package:visibility_detector/src/visibility_detector_layer.dart:268:24)
E/flutter (21016): #7      VisibilityDetectorLayer._processCallbacks (package:visibility_detector/src/visibility_detector_layer.dart:227:15)
E/flutter (21016): #8      _TaskEntry.run.<anonymous closure> (package:flutter/src/scheduler/binding.dart:80:34)
E/flutter (21016): #9      Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (21016): #10     _TaskEntry.run (package:flutter/src/scheduler/binding.dart:77:16)
E/flutter (21016): #11     SchedulerBinding.handleEventLoopCallback (package:flutter/src/scheduler/binding.dart:460:15)
E/flutter (21016): #12     SchedulerBinding._runTasks (package:flutter/src/scheduler/binding.dart:438:9)
E/flutter (21016): #13     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (21016): #14     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (21016): #15     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (21016): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (21016): #17     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (21016): #18     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (21016): #19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
E/flutter (21016): #20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (21016): #21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (21016): #22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (21016): #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

## Proposal

I noticed there's a `_isDisposed` value in the  **video_player** package (lib/video_player.dart). But it `_isDisposed` is not accessible. 
I added a getter to `_isDisposed` and now it works for me! (does not throws error)
```
bool get isDisposed => _isDisposed;
```
Why is `_isDisposed` not available? Can we add a getter and use it?

**Comment by darshankawar** [comment]
@reverie-ss 
Are you referring to https://github.com/flutter/plugins/blob/c631fa190b5865d7263c93adfa3706c4f0a0a6e9/packages/video_player/video_player/lib/video_player.dart#L410

**Comment by reverie-ss** [comment]
> @reverie-ss
> Are you referring to https://github.com/flutter/plugins/blob/c631fa190b5865d7263c93adfa3706c4f0a0a6e9/packages/video_player/video_player/lib/video_player.dart#L410

Kind of, am referring to a dedicated getter for `_isDisposed` 
Just like, https://github.com/flutter/plugins/blob/c631fa190b5865d7263c93adfa3706c4f0a0a6e9/packages/video_player/video_player/lib/video_player.dart#L270

**Comment by cyanglaz** [comment]
Looks like the `VideoPlayerController.pause()` is a no-op if `_isDisposed` is true: https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/lib/video_player.dart#L417

@reverie-ss could you elaborate more about your use case and how it failed?

**Comment by reverie-ss** [comment]
@cyanglaz 
I have two pages, **Page A** and **Page B**
Both the pages have list of videos which plays whenever visible on screen. `VideoPlayerController.pause()` is called whenever video is not visible.
Suppose I am in page A, video is playing fine. 
Then I go to page B, it also plays fine. The issue is when I hit the back button in page B; it disposes the video, and also tries to pause it (since it is no more visible). This throws error :

> E/flutter (21016): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: A VideoPlayerController was used after being disposed.

Solution:
I added a getter for `_isDisposed` and put the condition before calling `pause()`
```
if(!videoPlayerController.isDisposed)
     videoPlayerController.pause();
```

**Comment by stuartmorgan** [comment]
> Looks like the `VideoPlayerController.pause()` is a no-op if `_isDisposed` is true: https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/lib/video_player.dart#L417

Based on the stack, the issue is that the line just before the call to that internal method triggers the `throw`, so we're not correctly no-oping; we're checking too late.

Given that the code is trying to handle this internally already and just not working, the correct fix seems like it's to move the early returns, not expose new API.
