### ISSUE TITLE
[windows 7] Flutter Analyzer failed to start when Flutter folder is on Network folder, FileSystemException Cannot open file

### ISSUE THREAD

**Issue by mytja** [flutter/flutter#79283]
## Steps to Reproduce

1. Download latest Flutter release
2. Extract it in Network folder (folder on NAS (Network Attached Storage))
3. Add to path
4. Run `flutter analyze`

I'm using latest dev Flutter with VS Code on Windows 7 SP1 64-bit

## Logs

<details>
<summary>Logs</summary>

`flutter analyze` - LOG file
```
Dart Code extension: 3.20.1
Flutter extension: 3.20.0 (activated)

App: Visual Studio Code
Version: 1.52.1
Platform: win

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: Z:\CODE\flutter\bin\cache\dart-sdk
    Ver: 2.13.0-116.0.dev
Flutter SDK:
    Loc: Z:\CODE\flutter
    Ver: 2.1.0-12.1.pre

HTTP_PROXY: undefined
NO_PROXY: undefined
[18:27:41] [Analyzer] [Info] ==> {"id":"5","method":"edit.getFixes","params":{"file":"Z:\\CODE\\harmonoid\\lib\\main.dart","offset":569},"clientRequestTime":1617035261292}
[18:27:41] [Analyzer] [Info] ==> {"id":"6","method":"edit.getAssists","params":{"file":"Z:\\CODE\\harmonoid\\lib\\main.dart","length":0,"offset":569},"clientRequestTime":1617035261292}
[18:27:41] [Analyzer] [Info] ==> {"id":"7","method":"edit.getAvailableRefactorings","params":{"file":"Z:\\CODE\\harmonoid\\lib\\main.dart","length":0,"offset":569},"clientRequestTime":1617035261292}
[18:27:41] [Analyzer] [Info] <== [exception: FileSystemException(path=C:\Program Files\Microsoft VS Code\UNC\192.168.1.101\SERVER\CODE\flutter\bin\cache\dart-sdk\lib\_internal\sdk_library_metadata\lib\libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:184:7)
[18:27:41] [Analyzer] [Info] <== #1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:473:41)
[18:27:41] [Analyzer] [Info] <== #2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:371:18)
[18:27:41] [Analyzer] [Info] <== #3      Driver._createDefaultSdk (package:analysis_server/src/server/driver.dart:497:12)
[18:27:41] [Analyzer] [Info] <== #4      Driver.start (package:analysis_server/src/server/driver.dart:234:22)
[18:27:41] [Analyzer] [Info] <== #5      main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:11)
[18:27:41] [Analyzer] [Info] <== #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
[18:27:41] [Analyzer] [Info] <== #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[18:27:41] [Analyzer] [Info] <== ]
[18:27:41] [Analyzer] [Info] <== [exception: FileSystemException(path=C:\Program Files\Microsoft VS Code\UNC\192.168.1.101\SERVER\CODE\flutter\bin\cache\dart-sdk\lib\_internal\libraries.dart; message=Cannot open file)][stackTrace: #0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical_file_system.dart:184:7)
[18:27:41] [Analyzer] [Info] <== #1      FolderBasedDartSdk.initialLibraryMap (package:analyzer/src/dart/sdk/sdk.dart:473:41)
[18:27:41] [Analyzer] [Info] <== #2      new FolderBasedDartSdk (package:analyzer/src/dart/sdk/sdk.dart:371:18)
[18:27:41] [Analyzer] [Info] <== #3      Driver._createDefaultSdk (package:analysis_server/src/server/driver.dart:497:12)
[18:27:41] [Analyzer] [Info] <== #4      Driver.start (package:analysis_server/src/server/driver.dart:234:22)
[18:27:41] [Analyzer] [Info] <== #5      main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:11)
[18:27:41] [Analyzer] [Info] <== #6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
[18:27:41] [Analyzer] [Info] <== #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[18:27:41] [Analyzer] [Info] <== ]
[18:27:41] [Analyzer] [Error] Unhandled excepti
[18:27:41] [Analyzer] [Error] on:
FileSystemException(path=C:\Program Files\Microsoft VS Code\UNC\192.168.1.100\SERVER\CODE\flutter\bin\cache\dart-sdk\version; message=Cannot open file)
#0      _PhysicalFile.readAsStringSync (package:analyzer/file_system/physical
[18:27:41] [Analyzer] [Error] _file_system.dart:184:7)
#1      FolderBasedDartSdk.languageVersion (package:analyzer/s
[18:27:41] [Analyzer] [Error] rc/dart/sdk/sdk.dart:395:12)
#2      Driver.start (package:analysis_server/src/server/driver.dart:262:18)
#3      main (file:///C:/b/s/w/i
[18:27:41] [Analyzer] [Error] r/cache/builder/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:11)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-p
[18:27:41] [Analyzer] [Error] atch/isolate_patch.dart:281:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[18:27:41] [Analyzer] [Info] Process terminated! 255, null
```

`flutter doctor -v`
```
[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 6.1.7601], locale sl-SI)
    • Flutter version 2.1.0-12.1.pre at Z:\CODE\flutter
    • Framework revision 8264cb3e8a (3 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DOMA\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 6.1.7601]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.
```

</details>

**Comment by christopherfujino** [comment]
Thank you for filing this issue. However, unfortunately the Flutter CLI tool does not support being run from a NAS. I would recommend installing the Flutter SDK on your host device.

**Comment by mytja** [comment]
Ok, thank you so much for your time
