### ISSUE TITLE
 BindingError: Expected null or instance of Path, got an instance of Path - (just in - Flutter Web)

### ISSUE THREAD

**Issue by theiskaa** [flutter/flutter#79290]
While I'm working on Flutter web, I see this issue every day, and I couldn't found any solution. 
I'm making a package there I display widget and hide by overlay. 
**Issue logs:**
```

  BindingError: Expected null or instance of Path, got an instance of Path
════════════════════════════════════════════════════════════════════════════════
Restarted application in 203ms.
Restarted application in 392ms.
Restarted application in 174ms.
Restarted application in 1,427ms.
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:57955/dart_sdk.js:5334:11)
    at Object.nullCheck (http://localhost:57955/dart_sdk.js:5667:30)
    at Object.get skiaFontCollection [as skiaFontCollection] (http://localhost:57955/dart_sdk.js:185384:19)
    at new _engine.CkParagraphBuilder.new (http://localhost:57955/dart_sdk.js:145516:119)
    at Function.new (http://localhost:57955/dart_sdk.js:133647:16)
    at DefaultShaderWarmUp.warmUpOnCanvas (http://localhost:57955/packages/flutter/src/painting/shader_warm_up.dart.lib.js:242:63)
    at warmUpOnCanvas.next (<anonymous>)
    at runBody (http://localhost:57955/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:57955/dart_sdk.js:39083:7)
    at DefaultShaderWarmUp.warmUpOnCanvas (http://localhost:57955/packages/flutter/src/painting/shader_warm_up.dart.lib.js:182:20)
    at DefaultShaderWarmUp.execute (http://localhost:57955/packages/flutter/src/painting/shader_warm_up.dart.lib.js:116:20)
    at execute.next (<anonymous>)
    at runBody (http://localhost:57955/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:57955/dart_sdk.js:39083:7)
    at DefaultShaderWarmUp.execute (http://localhost:57955/packages/flutter/src/painting/shader_warm_up.dart.lib.js:113:20)
    at binding$5.WidgetsFlutterBinding.new.initInstances (http://localhost:57955/packages/flutter/src/painting/binding.dart.lib.js:75:30)
    at binding$5.WidgetsFlutterBinding.new.initInstances (http://localhost:57955/packages/flutter/src/semantics/binding.dart.lib.js:42:13)
    at binding$5.WidgetsFlutterBinding.new.initInstances (http://localhost:57955/packages/flutter/src/rendering/layer.dart.lib.js:5934:13)
    at binding$5.WidgetsFlutterBinding.new.initInstances (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:51407:13)
    at binding$5.WidgetsFlutterBinding.new.binding.BindingBase.new (http://localhost:57955/packages/flutter/src/foundation/binding.dart.lib.js:371:10)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_GestureBinding$36.new (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:51984:49)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_SchedulerBinding$36.new (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:51990:51)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_ServicesBinding$36.new (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:51996:50)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_PaintingBinding$36.new (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:52002:50)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_SemanticsBinding$36.new (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:52008:51)
   at binding$5.WidgetsFlutterBinding.new.BindingBase_RendererBinding$36.new (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:52014:50)
    at binding$5.WidgetsFlutterBinding.new.BindingBase_WidgetsBinding$36.new (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:52020:49)
    at new binding$5.WidgetsFlutterBinding.new (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:52030:51)
    at Function.ensureInitialized (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:52025:54)
    at Object.runApp (http://localhost:57955/packages/flutter/src/widgets/widget_span.dart.lib.js:52039:43)
    at main$ (http://localhost:57955/packages/suggestion_field/main.dart.lib.js:750:15)
    at main$.next (<anonymous>)
    at runBody (http://localhost:57955/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:57955/dart_sdk.js:39083:7)
    at main$ (http://localhost:57955/packages/suggestion_field/main.dart.lib.js:749:18)
    at main (http://localhost:57955/web_entrypoint.dart.lib.js:46:29)
    at main.next (<anonymous>)
    at http://localhost:57955/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:57955/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:57955/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:57955/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:57955/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:57955/dart_sdk.js:34315:23)
    at http://localhost:57955/dart_sdk.js:33526:46
    at _RootZone.runUnary (http://localhost:57955/dart_sdk.js:38889:58)
    at _FutureListener.then.handleValue (http://localhost:57955/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:57955/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:57955/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:57955/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57955/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:57955/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:57955/dart_sdk.js:39182:13)
    at http://localhost:57955/dart_sdk.js:34689:9
6
A fallback font was registered but we cannot retrieve the typeface for it.

════════ Exception caught by rendering library ═════════════════════════════════
The following NativeJavaScriptObject object was thrown during paint():
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph

The relevant error-causing widget was
TextField
lib/suggestion_overly.dart:548
When the exception was thrown, this was the stack
https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 154:76          <fn>
https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 153:335         new BindingError

https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 162:38          wc
https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 165:310         Bc
...
The following RenderObject was being processed when the exception was fired: RenderParagraph#066a8 relayoutBoundary=up13
RenderObject: RenderParagraph#066a8 relayoutBoundary=up13
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: ellipsis
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike subhead 2014).merge(blackRedwoodCity subtitle1)).copyWith
        inherit: false
        color: Color(0x99000000)
        family: .AppleSystemUIFont
        size: 16.0
        weight: 400
        baseline: alphabetic
        decoration: TextDecoration.none
        "Email"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
Text
lib/main.dart:90
The following RenderObject was being processed when the exception was fired: RenderParagraph#ad1ef relayoutBoundary=up16
RenderObject: RenderParagraph#ad1ef relayoutBoundary=up16
    parentData: offset=Offset(20.0, 14.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: clip
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike button 2014).merge(blackRedwoodCity button)).copyWith
    inherit: false
        color: MaterialColor(primary value: Color(0xff2196f3))
        family: .AppleSystemUIFont
        size: 14.0
        weight: 500
        baseline: alphabetic
        decoration: TextDecoration.none
        "Show dialog"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
Text
lib/main.dart:54
The following RenderObject was being processed when the exception was fired: RenderParagraph#8086f relayoutBoundary=up14
RenderObject: RenderParagraph#8086f relayoutBoundary=up14
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: no wrapping except at line break characters
    overflow: ellipsis
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: (englishLike title 2014).merge(whiteRedwoodCity headline6)
        inherit: false
        color: Color(0xffffffff)
        family: .AppleSystemUIFont
        size: 20.0
        weight: 500
        baseline: alphabetic
        decoration: TextDecoration.none
        "Flutter Demo Home Page"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
  BindingError: Expected null or instance of Path, got an instance of Path
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
  BindingError: Expected null or instance of Path, got an instance of Path
════════════════════════════════════════════════════════════════════════════════
ERROR - 2021-03-29 21:34:35.147344
GET /dart_sdk.js:39052:34
Error thrown by handler.
FormatException: Illegal scheme character (at character 5)
dart_sdk.js:39052:34
    ^

dart:core                                                 _Uri.resolve
package:flutter_tools/src/isolated/devfs_web.dart 503:57  WebAssetServer._resolveDartFile
package:flutter_tools/src/isolated/devfs_web.dart 395:17  WebAssetServer.handleRequest
package:dwds/src/handlers/injector.dart 110:32            DwdsInjector.middleware.<fn>.<fn>
2


════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
TextField
lib/suggestion_overly.dart:548
The following RenderObject was being processed when the exception was fired: RenderParagraph#066a8 relayoutBoundary=up13
RenderObject: RenderParagraph#066a8 relayoutBoundary=up13
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: ellipsis
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike subhead 2014).merge(blackRedwoodCity subtitle1)).copyWith
        debugLabel: ((englishLike subhead 2014).merge(blackRedwoodCity subtitle1)).copyWith
        inherit: false
        color: Color(0x99000000)
        family: .AppleSystemUIFont
        size: 16.0
        weight: 400
        baseline: alphabetic
        decoration: TextDecoration.none
        "Email"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
TextField
lib/suggestion_overly.dart:548
The following RenderObject was being processed when the exception was fired: RenderEditable#e3379 relayoutBoundary=up19
RenderObject: RenderEditable#e3379 relayoutBoundary=up19
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=368.0, 0.0<=h<=Infinity)
    size: Size(368.0, 0.0)
    cursorColor: Color(0x002196f3)
    showCursor: ValueNotifier<bool>#0bd98(true)
    maxLines: 1
    minLines: null
    selectionColor: Color(0x662196f3)
    textScaleFactor: 1.0
    locale: en_US
    selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false)
    offset: ScrollPositionWithSingleContext#e3c9f(offset: 0.0, range: 0.0..0.0, viewport: 368.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#a8935, ScrollDirection.idle)
    text: TextSpan
        debugLabel: (englishLike subhead 2014).merge(blackRedwoodCity subtitle1)
        inherit: false
        color: Color(0xdd000000)
        family: .AppleSystemUIFont
        size: 16.0
        weight: 400
        baseline: alphabetic
        decoration: TextDecoration.none
        ""
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
 BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
Text
lib/main.dart:90
The following RenderObject was being processed when the exception was fired: RenderParagraph#ad1ef relayoutBoundary=up16
RenderObject: RenderParagraph#ad1ef relayoutBoundary=up16
    parentData: offset=Offset(20.0, 14.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: clip
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike button 2014).merge(blackRedwoodCity button)).copyWith
        inherit: false
        color: MaterialColor(primary value: Color(0xff2196f3))
        family: .AppleSystemUIFont
        size: 14.0
        weight: 500
        baseline: alphabetic
        decoration: TextDecoration.none
        "Show dialog"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
Text
lib/main.dart:54
The following RenderObject was being processed when the exception was fired: RenderParagraph#8086f relayoutBoundary=up14
RenderObject: RenderParagraph#8086f relayoutBoundary=up14
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: no wrapping except at line break characters
    overflow: ellipsis
    locale: en_US
    maxLines: unlimited
    text: TextSpan
 debugLabel: (englishLike title 2014).merge(whiteRedwoodCity headline6)
        inherit: false
        color: Color(0xffffffff)
        family: .AppleSystemUIFont
        size: 20.0
        weight: 500
        baseline: alphabetic
        decoration: TextDecoration.none
        "Flutter Demo Home Page"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Typeface, got an instance of Typeface
The relevant error-causing widget was
MaterialApp
lib/main.dart:14
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
  BindingError: Expected null or instance of Picture, got an instance of Picture
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
TextField
lib/suggestion_overly.dart:548
The following RenderObject was being processed when the exception was fired: RenderParagraph#066a8 relayoutBoundary=up13
RenderObject: RenderParagraph#066a8 relayoutBoundary=up13
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: ellipsis
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike subhead 2014).merge(blackRedwoodCity subtitle1)).copyWith
        inherit: false
        color: Color(0x99000000)
        family: .AppleSystemUIFont
        size: 16.0
        weight: 400
        baseline: alphabetic
  decoration: TextDecoration.none
        "Email"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
TextField
lib/suggestion_overly.dart:548
The following RenderObject was being processed when the exception was fired: RenderEditable#e3379 relayoutBoundary=up19
RenderObject: RenderEditable#e3379 relayoutBoundary=up19
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=368.0, 0.0<=h<=Infinity)
    size: Size(368.0, 0.0)
    cursorColor: Color(0x002196f3)
    showCursor: ValueNotifier<bool>#0bd98(true)
    maxLines: 1
    minLines: null
    selectionColor: Color(0x662196f3)
    textScaleFactor: 1.0
    locale: en_US
    selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false)
    offset: ScrollPositionWithSingleContext#4df47(offset: 0.0, range: 0.0..0.0, viewport: 368.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#ead6a, ScrollDirection.idle)
    text: TextSpan
        debugLabel: (englishLike subhead 2014).merge(blackRedwoodCity subtitle1)
        inherit: false
        color: Color(0xdd000000)
        family: .AppleSystemUIFont
        size: 16.0
        weight: 400
        baseline: alphabetic
        decoration: TextDecoration.none
        ""
════════════════════════════════════════════════════════════════════════════════
═══════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
Text
lib/main.dart:90
The following RenderObject was being processed when the exception was fired: RenderParagraph#ad1ef relayoutBoundary=up16
RenderObject: RenderParagraph#ad1ef relayoutBoundary=up16
    parentData: offset=Offset(20.0, 14.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: clip
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike button 2014).merge(blackRedwoodCity button)).copyWith
        inherit: false
        color: MaterialColor(primary value: Color(0xff2196f3))
        family: .AppleSystemUIFont
        size: 14.0
        weight: 500
        baseline: alphabetic
        decoration: TextDecoration.none
        "Show dialog"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
Text
lib/main.dart:54
The following RenderObject was being processed when the exception was fired: RenderParagraph#8086f relayoutBoundary=up14
RenderObject: RenderParagraph#8086f relayoutBoundary=up14
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: no wrapping except at line break characters
    overflow: ellipsis
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: (englishLike title 2014).merge(whiteRedwoodCity headline6)
        inherit: false
     color: Color(0xffffffff)
        family: .AppleSystemUIFont
        size: 20.0
        weight: 500
        baseline: alphabetic
        decoration: TextDecoration.none
        "Flutter Demo Home Page"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Typeface, got an instance of Typeface
The relevant error-causing widget was
MaterialApp
lib/main.dart:14
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
  BindingError: Expected null or instance of Picture, got an instance of Picture
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
TextField
lib/suggestion_overly.dart:548
The following RenderObject was being processed when the exception was fired: RenderParagraph#066a8 relayoutBoundary=up13
RenderObject: RenderParagraph#066a8 relayoutBoundary=up13
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: ellipsis
locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike subhead 2014).merge(blackRedwoodCity subtitle1)).copyWith
        inherit: false
        color: Color(0x99000000)
        family: .AppleSystemUIFont
        size: 16.0
        weight: 400
        baseline: alphabetic
        decoration: TextDecoration.none
        "Email"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
TextField
lib/suggestion_overly.dart:548
The following RenderObject was being processed when the exception was fired: RenderEditable#e3379 relayoutBoundary=up19
RenderObject: RenderEditable#e3379 relayoutBoundary=up19
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=368.0, 0.0<=h<=Infinity)
    size: Size(368.0, 0.0)
    cursorColor: Color(0x002196f3)
    showCursor: ValueNotifier<bool>#0bd98(true)
    maxLines: 1
    minLines: null
    selectionColor: Color(0x662196f3)
    textScaleFactor: 1.0
    locale: en_US
    selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false)
    offset: ScrollPositionWithSingleContext#c1921(offset: 0.0, range: 0.0..0.0, viewport: 368.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#e61be, ScrollDirection.idle)
    text: TextSpan
        debugLabel: (englishLike subhead 2014).merge(blackRedwoodCity subtitle1)
        inherit: false
        color: Color(0xdd000000)
        family: .AppleSystemUIFont
        size: 16.0
        weight: 400
        baseline: alphabetic
        decoration: TextDecoration.none
        ""

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
Text
lib/main.dart:90
The following RenderObject was being processed when the exception was fired: RenderParagraph#ad1ef relayoutBoundary=up16
RenderObject: RenderParagraph#ad1ef relayoutBoundary=up16
    parentData: offset=Offset(20.0, 14.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=352.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: wrapping at box width
    overflow: clip
    locale: en_US
    maxLines: unlimited
    text: TextSpan
        debugLabel: ((englishLike button 2014).merge(blackRedwoodCity button)).copyWith
        inherit: false
        color: MaterialColor(primary value: Color(0xff2196f3))
        family: .AppleSystemUIFont
        size: 14.0
        weight: 500
        baseline: alphabetic
        decoration: TextDecoration.none
        "Show dialog"
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
The relevant error-causing widget was
Text
lib/main.dart:54
The following RenderObject was being processed when the exception was fired: RenderParagraph#8086f relayoutBoundary=up14
RenderObject: RenderParagraph#8086f relayoutBoundary=up14
    parentData: offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=368.0, 0.0<=h<=Infinity)
    size: Size(0.0, 0.0)
    textAlign: start
    textDirection: ltr
    softWrap: no wrapping except at line break characters
    overflow: ellipsis
    locale: en_US

════════ Exception caught by rendering library ═════════════════════════════════
  BindingError: Expected null or instance of Typeface, got an instance of Typeface
The relevant error-causing widget was
MaterialApp
lib/main.dart:14
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
  BindingError: Expected null or instance of Picture, got an instance of Picture
════════════════════════════════════════════════════════════════════════════════

```

**Comment by darshankawar** [comment]
@theiskaa 
Can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by theiskaa** [comment]
sure, I'll give me few min pls

**Comment by darshankawar** [comment]
> @theiskaa
> Can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

@theiskaa 
Will also need a complete minimal reproducible code sample that shows this issue.
Thanks.

**Comment by theiskaa** [comment]
> > @theiskaa
> > Can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
> 
> @theiskaa
> Will also need a complete minimal reproducible code sample that shows this issue.
> Thanks.

This issue appears while I'm using Overlay.

**Comment by darshankawar** [comment]
> > @theiskaa
> > Can you provide `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
> 
> @theiskaa
> Will also need a complete minimal reproducible code sample that shows this issue.
> Thanks.

@theiskaa 
It'll be great if you could provide a reproducible code sample to properly address this issue.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
