### ISSUE TITLE
TextField caret broken (Throws unsupported method call)

### ISSUE THREAD

**Issue by mat100payette** [flutter/flutter#79389]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Add a `TextField` anywhere in the app.
3. Run the app and click on the `TextField`.

**Expected results:**
A normal textfield behavior where the caret is animated and waiting for you to type stuff.

**Actual results:**
Throws on click with the following trace:

> Error: Bad state: Unsupported method call on the flutter/textinput channel: TextInput.setCaretRect
    at Object.throw_ [as throw] (http://localhost:54026/dart_sdk.js:5036:11)
    at _engine.TextEditingChannel.new.handleTextInput (http://localhost:54026/dart_sdk.js:170278:21)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:54026/dart_sdk.js:157000:39)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:54026/dart_sdk.js:156867:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:54026/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
    at _DefaultBinaryMessenger.send (http://localhost:54026/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:54026/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:54026/dart_sdk.js:37386:34)

<details>
  <summary>Logs</summary>

```
```

[√] Flutter (Channel master, 2.1.0-13.0.pre.326, on Microsoft Windows [version 10.0.18363.1440], locale fr-CA)
    • Flutter version 2.1.0-13.0.pre.326 at C:\Flutter\flutter
    • Framework revision 95e2cbb132 (41 minutes ago), 2021-03-30 21:59:02 +0530
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\matpa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 2 categories.

```
```

</details>

**Comment by mat100payette** [comment]
Here is the breaking commit:
[462ad79036401816afa83263f1a95f34c3194441](https://github.com/flutter/flutter/commit/462ad79036401816afa83263f1a95f34c3194441#diff-701a97b414026a5c87a06b546bb38ca70be2aa0ce44cbf170f4b43e8defcc91a)

**Comment by darshankawar** [comment]
<details>
<summary>console error log</summary>

```
For a more detailed help message, press "h". To quit, press "q".
Error: Bad state: Unsupported method call on the flutter/textinput channel: TextInput.setCaretRect
    at Object.throw_ [as throw] (http://localhost:50908/dart_sdk.js:5036:11)
    at _engine.TextEditingChannel.new.handleTextInput (http://localhost:50908/dart_sdk.js:170278:21)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:50908/dart_sdk.js:157000:39)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:50908/dart_sdk.js:156867:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:50908/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
    at _DefaultBinaryMessenger.send (http://localhost:50908/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:50908/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:50908/dart_sdk.js:37386:34)
    at Object._async [as async] (http://localhost:50908/dart_sdk.js:37417:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:50908/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:50908/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:50908/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:50908/dart_sdk.js:37386:34)
    at Object._async [as async] (http://localhost:50908/dart_sdk.js:37417:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:50908/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
    at text_input.TextInput.__.[_setCaretRect] (http://localhost:50908/packages/flutter/src/services/text_input.dart.lib.js:1324:22)
    at text_input.TextInputConnection.__.setCaretRect (http://localhost:50908/packages/flutter/src/services/text_input.dart.lib.js:1089:52)
    at editable_text.EditableTextState.new.[_updateCaretRectIfNeeded] (http://localhost:50908/packages/flutter/src/widgets/widget_span.dart.lib.js:43665:56)
    at http://localhost:50908/packages/flutter/src/widgets/widget_span.dart.lib.js:43667:126
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:50908/packages/flutter/src/scheduler/binding.dart.lib.js:717:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:50908/packages/flutter/src/scheduler/binding.dart.lib.js:694:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:50908/packages/flutter/src/scheduler/binding.dart.lib.js:646:12)
    at Object.invoke (http://localhost:50908/dart_sdk.js:175048:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnDrawFrame (http://localhost:50908/dart_sdk.js:156829:15)
    at http://localhost:50908/dart_sdk.js:172478:55

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.346, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.346 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8158b478d7 (2 hours ago), 2021-03-31 13:29:03 +0800
    • Engine revision dbcbf69a57
    • Dart version 2.13.0 (build 2.13.0-175.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

<details>
<summary> code sample </summary>

```
TextField(
              decoration: InputDecoration(
                hintText: 'enter here'
              ),
            )

```

</details>
