### ISSUE TITLE
Add mac m1 machines to the staging pool

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#79430]
This requires the following:

* Changes to salt states to install arm64 and x64 brew packages.
* Add the mac configurations to the staging pool.
* Fix any problems with the tests find

**Comment by godofredoc** [comment]
\cc @jmagman @xster

**Comment by godofredoc** [comment]
flutter-devicelab-mac-4 is ready but it seems to be failing tasks:

* https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-4
* https://chromium-swarm.appspot.com/task?id=52a769aecb65ec10

**Comment by jmagman** [comment]
```
arch: posix_spawnp: xcrun: Bad CPU type in executable mysterious
```

These might need Rosetta installed.  Can you add `softwareupdate --install-rosetta` to the setup?

**Comment by jmagman** [comment]
@godofredoc says "rosetta is installed as part of the provisioning. idevice requires the emulation"

Can we confirm whatever `xcrun` is on the `PATH` contains `arm64e`?
```
$ which xcrun
/usr/bin/xcrun
$ file /usr/bin/xcrun      
/usr/bin/xcrun: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/xcrun (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/xcrun (for architecture arm64e):	Mach-O 64-bit executable arm64e
```
(note the `arm64e` at the end).

**Comment by godofredoc** [comment]
This is from the one included in the bundle:

```
file /opt/flutter/xcode/12c33/XCode.app/Contents/Developer/usr/bin/xcrun
/opt/flutter/xcode/12c33/XCode.app/Contents/Developer/usr/bin/xcrun: Mach-O 64-bit executable x86_64
```

**Comment by godofredoc** [comment]
It was that removing `/opt/flutter/xcode/12c33/XCode.app/Contents/Developer/usr/bin/xcrun` and re-running:

https://luci-milo.appspot.com/p/flutter/builders/prod/Mac_ios_staging%20flutter_gallery_ios__start_up/135?

**Comment by jmagman** [comment]
So is the next step a recipe change, or is there more for me to investigate, @godofredoc?

**Comment by godofredoc** [comment]
Thanks for helping us identify the issue the next step is to create a new xcode bundle that does not include xcrun. I'll reassign the bug back to me.

**Comment by godofredoc** [comment]
Uploading a new xcode bundle to remove xcrun.

**Comment by godofredoc** [comment]
@jmagman we still have a couple of failures:

* https://ci.chromium.org/p/flutter/builders/prod/Mac_ios_staging%20hot_mode_dev_cycle_macos_target__benchmark/140
* https://ci.chromium.org/p/flutter/builders/prod/Mac_ios_staging%20ios_app_with_extensions_test/138

```
[hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [  +20 ms] Building macOS application... (completed in 30.4s)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [  +11 ms] executing: /usr/bin/plutil -convert json -o - /opt/s/w/ir/tmp/t/edited_flutter_gallery/build/macos/Build/Products/Debug/flutter_gallery.app/Contents/Info.plist
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [  +25 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /opt/s/w/ir/tmp/t/edited_flutter_gallery/build/macos/Build/Products/Debug/flutter_gallery.app/Contents/Info.plist
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] {"CFBundleName":"flutter_gallery","DTXcode":"1230","DTSDKName":"macosx11.1","NSHumanReadableCopyright":"Copyright © 2019 com.example. All rights reserved.","DTSDKBuild":"20C63","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"20C69","NSPrincipalClass":"NSApplication","CFBundleIconName":"AppIcon","CFBundlePackageType":"APPL","CFBundleIconFile":"AppIcon","CFBundleSupportedPlatforms":["MacOSX"],"DTPlatformName":"macosx","CFBundleShortVersionString":"1.0.0","NSMainNibFile":"MainMenu","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"flutter_gallery","DTCompiler":"com.apple.compilers.llvm.clang.1_0","CFBundleIdentifier":"com.example.flutterGallery","DTPlatformVersion":"11.1","DTXcodeBuild":"12C33","LSMinimumSystemVersion":"10.11","DTPlatformBuild":"12C33"}
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: [+1012 ms] Error waiting for a debug connection: The log reader stopped unexpectedly.
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: [   +2 ms] Error launching application on macOS.
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [   +2 ms] "flutter run" took 55,078ms.
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: [   +5 ms] 
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:290:9)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:238:5)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            #10     main (package:flutter_tools/executable.dart:91:3)
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr:            <asynchronous suspension>
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: 
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stderr: 
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [   +4 ms] ensureAnalyticsSent: 0ms
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [   +1 ms] Running shutdown hooks
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] Shutdown hooks complete
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] stdout: [        ] exiting with code 1
 [hot_mode_dev_cycle_macos_target__benchmark] [STDOUT] "/opt/s/w/ir/k/recipe_cleanup/tmp0obZOn/flutter sdk/bin/flutter" exit code: 1
```

**Comment by jmagman** [comment]
I was able to reproduce `ios_app_with_extensions_test` locally, investigating that now.

`hot_mode_dev_cycle_macos_target__benchmark` passed on my machine. @godofredoc Is there a user logged in when that test runs?

**Comment by jmagman** [comment]
I'm tracking the `ios_app_with_extensions_test` test failure in https://github.com/flutter/flutter/issues/82402

**Comment by jmagman** [comment]
@godofredoc I'm about to merge a fix for the last test failure with https://github.com/flutter/flutter/pull/85087.  I think getting an M1 set up for the devicelab will be the last thing blocking iOS arm64 simulator work https://github.com/flutter/flutter/pull/85059.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/85087 merged, though I can't see if the tests now pass because mac-4 is quarantined for lack of disk space https://github.com/flutter/flutter/issues/82492.

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/85654 to track down the `hot_mode_dev_cycle_macos_target__benchmark` failure.

**Comment by godofredoc** [comment]
@jmagman @keyonghan I believe we can close this issue, am I right?  I see tests running on the Mac M1 machines.

**Comment by jmagman** [comment]
I think so.  Once I track down https://github.com/flutter/flutter/issues/85654 I'll file an issue to move the machines to the prod pool.  Is that right, @godofredoc?

**Comment by godofredoc** [comment]
Sounds good, thanks Jenn.
