### ISSUE TITLE
The position being added (Offset(XX, XX)) has a smaller timestamp (XX)than its predecessor: _PointAtTime(Offset(XX, XX) at XX.

### ISSUE THREAD

**Issue by LeoFavor1562** [flutter/flutter#79445]
1. Run my App.
2. Go to a Flutter page.
3. Scroll the Flutter page.

**Expected results:** 
No errors occur.
**Actual results:** 
An error occurred while scrolling the page.
One error detail:The position being added (Offset(124.0, 236.0)) has a smaller timestamp (937:34:53.275485)than its predecessor: _PointAtTime(Offset(124.0, 236.5) at 449217:37:44.816003).
<details>
  <summary>Logs</summary>

```
#0      IOSScrollViewFlingVelocityTracker.addPosition.<anonymous closure> (package:flutter/src/gestures/velocity_tracker.dart:305:7)
#1      IOSScrollViewFlingVelocityTracker.addPosition (package:flutter/src/gestures/velocity_tracker.dart:309:6)
#2      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:280:15)
#3      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
#4      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#6      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
#7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:288:11)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#12     PointerEventResampler._samplePointerPosition (package:flutter/src/gestures/resampler.dart:264:15)
#13     PointerEventResampler.sample (package:flutter/src/gestures/resampler.dart:297:7)
#14     _Resampler.sample (package:flutter/src/gestures/binding.dart:136:17)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:331:18)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#18     _rootRunUnary (dart:async/zone.dart:1370:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#21     _invoke1 (dart:ui/hooks.dart:186:10)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.27.0-8.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @LeoFavor1562 

> Run my App.
> Go to a Flutter page.
> Scroll the Flutter page.

Your instructions are not clear

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run -v` running this code sample?
Also, make sure to provide step by steps to reproduce the issue
Thank you

**Comment by LeoFavor1562** [comment]
Hi @TahaTesser

**Comment by LeoFavor1562** [comment]
Hi @TahaTesser 
This should be flutter_swiper's problem.
Thanks for your answer.
