### ISSUE TITLE
Flutter Web: google map custom marker error: [NoSuchMethodError: invalid member on null: 'buffer']

### ISSUE THREAD

**Issue by arnaudelub** [flutter/flutter#79480]
Hi, i am experiencing the same issue when running flutter run web --web-renderer html but if i am using flutter run web it's working fine. So i am reoponing the issue #73130
So here you go:
## Flutter Doctor -v:
<details><summary>Flutter Doctor</summary>

```bash

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.3 at /home/idelub/Development/flutter
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/idelub/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /opt/idea-IU-202.6397.94
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.6397.47

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```
</details>

<details><summary>Error log</summary>

```bash

Error: Unhandled error NoSuchMethodError: invalid member on null: 'buffer' occurred in Instance of 'AnnouncementMarkersBloc'.
packages/hero/application/marker/announcement_markers_bloc.dart 200:66  getBytesFromAsset
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50      <fn>
dart-sdk/lib/async/zone.dart 1612:54                                    runUnary
dart-sdk/lib/async/future_impl.dart 152:18                              handleValue
dart-sdk/lib/async/future_impl.dart 704:44                              handleValueCallback
dart-sdk/lib/async/future_impl.dart 733:13                              _propagateToListeners
dart-sdk/lib/async/future_impl.dart 539:5                               [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 577:7                               callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                        _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                         _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15     <fn>

    at Object.throw_ [as throw] (http://localhost:46739/dart_sdk.js:5334:11)
    at http://localhost:46739/packages/bloc/src/cubit.dart.lib.js:122:21
    at announcement_markers_bloc.AnnouncementMarkersBloc.new.onError (http://localhost:46739/packages/bloc/src/cubit.dart.lib.js:123:27)
    at announcement_markers_bloc.AnnouncementMarkersBloc.new.onError (http://localhost:46739/packages/bloc/src/cubit.dart.lib.js:261:15)
    at _RootZone.runBinaryGuarded (http://localhost:46739/dart_sdk.js:38832:11)
    at sendError (http://localhost:46739/dart_sdk.js:32448:26)
    at _ControllerSubscription.new.[_sendError] (http://localhost:46739/dart_sdk.js:32465:11)
    at _ControllerSubscription.new.[_addError] (http://localhost:46739/dart_sdk.js:32388:27)
    at _SyncStreamController.new.[_sendError] (http://localhost:46739/dart_sdk.js:35345:39)
    at _SyncStreamController.new.[_sendError] (http://localhost:46739/dart_sdk.js:35455:33)
    at _SyncStreamController.new.[_addError] (http://localhost:46739/dart_sdk.js:35157:27)
    at _RootZone.runBinaryGuarded (http://localhost:46739/dart_sdk.js:38832:11)
    at sendError (http://localhost:46739/dart_sdk.js:32448:26)
    at _ForwardingStreamSubscription.new.[_sendError] (http://localhost:46739/dart_sdk.js:32465:11)
    at _ForwardingStreamSubscription.new.[_addError] (http://localhost:46739/dart_sdk.js:32388:27)
    at _ForwardingStreamSubscription.new.[_addError] (http://localhost:46739/dart_sdk.js:36613:25)
    at _MapStream.new.[_handleError] (http://localhost:46739/dart_sdk.js:36567:24)
    at _ForwardingStreamSubscription.new.[_handleError] (http://localhost:46739/dart_sdk.js:36639:38)
    at _RootZone.runBinaryGuarded (http://localhost:46739/dart_sdk.js:38832:11)
    at sendError (http://localhost:46739/dart_sdk.js:32448:26)
    at _ControllerSubscription.new.[_sendError] (http://localhost:46739/dart_sdk.js:32465:11)
    at async._DelayedError.new.perform (http://localhost:46739/dart_sdk.js:35875:27)
    at _StreamImplEvents.new.handleNext (http://localhost:46739/dart_sdk.js:35957:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:46739/dart_sdk.js:35709:16)
    at Object._microtaskLoop (http://localhost:46739/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:46739/dart_sdk.js:39182:13)
    at http://localhost:46739/dart_sdk.js:34689:9
```
</details>

Code Responsible for the Error:
<details><summary>CODE</summary>

```dart
if (getIt<CategoriesInjectable>().categories.isNotEmpty) {
               final Uint8List markerIcon = await getBytesFromAsset(
                   'assets/marker/${announce.icon}.png', 100);
               final sourceIcon = BitmapDescriptor.fromBytes(markerIcon);
               final pinInfo = AnnouncePinInformation(
                  pinPath: "assets/pin/${announce.icon}.png",
                   locationName: Categories.get(announce.type).title,
                   location:
                       LatLng(announce.point.latitude, announce.point.longitude),
                   announce: announce); // AnnouncePinInformation
               _markers.add(
                 Marker(
                   icon: sourceIcon,
                   markerId: MarkerId(announce.id.getOrCrash()),
                   position:
                      LatLng(announce.point.latitude, announce.point.longitude),
                  onTap: kIsWeb
                      ? null
                      : () => state.context
                       .bloc<MarkerSelectorBloc>()
                          .add(MarkerSelectorEvent.markerTapped(pinInfo)),
                ), // Marker
              );
    }
```
</details>

As mentionned earlier, when using the command line:
```bash
flutter run web
```
There is no error but i am using firebase storage, so to render the pictures from the storage i need the flag
```bash
--web-renderer html
```

p.s: Settings the cors with gsutil doesn't fix the error when trying to render the image stored in cloud storage

**Comment by TahaTesser** [comment]
Hi @arnaudelub 
Thanks for filing the issue

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?


Here I created a minimal runnable code sample to test the issue with the custom market on the web using the HTML renderer, there are no errors in the logs or chrome console

`flutter run --web-renderer html -d chrome -v`


<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Google Maps Demo',
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();
  List<Marker> _markers = <Marker>[];

  @override
  void initState() {
    super.initState();
    _markers.add(Marker(
        markerId: MarkerId('SomeId'),
        position: LatLng(38.123, 35.123),
        infoWindow: InfoWindow(title: 'The title of the marker')));
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(38.9647, 35.2233),
          zoom: 9.0,
        ),
        mapType: MapType.normal,
        markers: Set<Marker>.of(_markers),
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (2 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.4.2
    • iPhone 12 (mobile)     • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
	
</details>

Thank you

**Comment by arnaudelub** [comment]
Thank you @TahaTesser for the answer, i just saw that i were using google_map_flutter_web: ^0.1.0 i will try again with the updated version of the plugin.
Thank you for your time!

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
