### ISSUE TITLE
FileSystemException: FileSystemException: Cannot resolve symbolic links, path = '' (OS Error: The system cannot find the path specified. , errno = 3)

### ISSUE THREAD

**Issue by MrCo0oder** [flutter/flutter#79548]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot resolve symbolic links, path = '' (OS Error: The system cannot find the path specified.
, errno = 3)

```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:818:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:348:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:123:43)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:144:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:106:41)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:94:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:123:32)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:121:23)
#11     androidSdk (package:flutter_tools/src/globals.dart:97:38)
#12     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:178:29)
#13     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:106:41)
#14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#15     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:94:20)
#16     AppContext.get (package:flutter_tools/src/base/context.dart:123:32)
#17     AppContext.get (package:flutter_tools/src/base/context.dart:121:23)
#18     deviceManager (package:flutter_tools/src/globals.dart:59:44)
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:261:17)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
<asynchronous suspension>
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

## flutter doctor

```
encountered exception: FileSystemException: Cannot resolve symbolic links, path = '' (OS Error: The system cannot find the path specified.
, errno = 3)

#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:818:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:348:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:123:43)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:144:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:106:41)
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:94:20)
#9      AppContext.get (package:flutter_tools/src/base/context.dart:123:32)
#10     androidSdk (package:flutter_tools/src/globals.dart:97:38)
#11     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:114:29)
#12     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:106:41)
#13     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#14     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:94:20)
#15     AppContext.get (package:flutter_tools/src/base/context.dart:123:32)
#16     androidWorkflow (package:flutter_tools/src/android/android_workflow.dart:30:48)
#17     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:79:11)
#18     Doctor.validators (package:flutter_tools/src/doctor.dart:192:46)
#19     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:198:45)
#20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
#21     _doctorText (package:flutter_tools/runner.dart:232:18)
#22     _handleToolError (package:flutter_tools/runner.dart:157:27)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

**Comment by TahaTesser** [comment]
Hi @MrCo0oder 
Are you getting this crash on a fresh install? Can you please provide your flutter location path? and your platform details (windows, linux or macos) and `git version` 
Thank you

**Comment by MrCo0oder** [comment]
Hi, @TahaTesser
yes.. 
flutter location path 'C:/src/flutter' 
Os: Windows 10 OS
git version :2.31.1

**Comment by TahaTesser** [comment]
Hi @MrCo0oder 
Can you please move your fluter setup under C:\User\\<your_user>\flutter and try again. 
Thank you

**Comment by MrCo0oder** [comment]
I will try.
thank you Mr @TahaTesser

**Comment by MrCo0oder** [comment]
C:\Users\ae196>flutter doctor
usage: where [-h] filename
where: error: unrecognized arguments: git
Error: Unable to find git in your PATH.
I got this error.

**Comment by TahaTesser** [comment]
Hi @MrCo0oder 
You need to install `git` on your system,, if it is already installed, add it to your system path, follow these [instructions](https://stackoverflow.com/a/34767523)

**Comment by MrCo0oder** [comment]
@TahaTesser Thank you.
Solved
