### ISSUE TITLE
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4954 pos 14: '_dependents.isEmpty': is not true.

### ISSUE THREAD

**Issue by qq1903520389** [flutter/flutter#79628]
<details> 
<summary>logs</summary> 

```bash
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#08dbb](state: OverlayState#6c59b(entries: [OverlayEntry#f8b81(opaque: true; maintainState: false), OverlayEntry#505a6(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4954 pos 14: '_dependents.isEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/zhouliqiang/Desktop/catCatStarClient/lib/main.dart:87:22
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4954:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4956:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:2044:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2046:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
...
====================================================================================================

```

</details>

**Comment by iapicca** [comment]
@qq1903520389 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by TahaTesser** [comment]
Hi @qq1903520389 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and your `flutter run --verbose` running the minimal code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
