### ISSUE TITLE
Flutter creates errors after upgrading pre 1.12 Android project

### ISSUE THREAD

**Issue by philiposD** [flutter/flutter#79639]
I'm working on a Flutter app that has been created *prior to 1.12*, and while running the app or executing `flutter pub get`, I get a warning regarding this upgrade, which leads me to: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

I've followed all the steps under ***Add-to-app migration*** and when running the app, I get some errors for ***path_provider, shared_preferences, and flutter_secure_storage*** which doesn't allow the app to run.

Does someone else encounter a similar issue? or does someone know what would be done in this situation? <br>

One approach that I've read, would be to create a new project and copy the contents of the current one in the newly created one, but somehow I don't find it really good, I wanted to migrate the current one.

**Errors**:<br>
```java
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method readAll on channel plugins.it_nomads.com/flutter_secure_storage)
```

**Full stack trace error:**
```java
[ +414 ms] E/flutter ( 9811): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
[        ] E/flutter ( 9811): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
[        ] E/flutter ( 9811): <asynchronous suspension>
[        ] E/flutter ( 9811): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[        ] E/flutter ( 9811): #2      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:40:22)
[        ] E/flutter ( 9811): #3      FavoriteDbProvider.init (package:someapp/db/favorite_db_provider.dart:25:42)
[        ] E/flutter ( 9811): #4      new FavoriteDbProvider (package:someapp/db/favorite_db_provider.dart:16:5)
[        ] E/flutter ( 9811): #5      new FavoriteBloc (package:someapp/bloc/favorite_bloc.dart:13:49)
[        ] E/flutter ( 9811): #6      _BlocProvidersState._initBloc (package:someapp/app/app_bloc_providers.dart:126:20)
[        ] E/flutter ( 9811): #7      _BlocProvidersState.initState (package:someapp/app/app_bloc_providers.dart:104:5)
[        ] E/flutter ( 9811): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
[        ] E/flutter ( 9811): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
[        ] E/flutter ( 9811): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
[        ] E/flutter ( 9811): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
[        ] E/flutter ( 9811): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
[        ] E/flutter ( 9811): #13     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
[        ] E/flutter ( 9811): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
[        ] E/flutter ( 9811): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
[        ] E/flutter ( 9811): #16     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
[        ] E/flutter ( 9811): #17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
[        ] E/flutter ( 9811): #18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
[        ] E/flutter ( 9811): #19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
[        ] E/flutter ( 9811): #20     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
[        ] E/flutter ( 9811): #21     _rootRun (dart:async/zone.dart:1190:13)
[        ] E/flutter ( 9811): #22     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] E/flutter ( 9811): #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ] E/flutter ( 9811): #24     _invoke (dart:ui/hooks.dart:251:10)
[        ] E/flutter ( 9811): #25     _drawFrame (dart:ui/hooks.dart:209:3)
```

**Application.java**<br>
``` java
package com.someview.someapp;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.androidalarmmanager.AlarmService;
import io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin;

import com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin;
import com.tekartik.sqflite.SqflitePlugin;
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin;
import io.flutter.plugins.pathprovider.PathProviderPlugin;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;
public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    AlarmService.setPluginRegistrant(this);
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    // manually load each plugin required by the AlarmService isolate task!
    AndroidAlarmManagerPlugin.registerWith(registry.registrarFor("io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin"));

    // add FlutterNotifications plugin register
    FlutterLocalNotificationsPlugin.registerWith(registry.registrarFor("com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin"));

    //add PathProviderPlugin plugin register  if you work with Access Path Device
    PathProviderPlugin.registerWith(registry.registrarFor("io.flutter.plugins.pathprovider.PathProviderPlugin"));

    //add SqflitePlugin plugin register  if you work with sqflite
    SqflitePlugin.registerWith(registry.registrarFor("com.tekartik.sqflite.SqflitePlugin"));

    //add SharedPreferencesPlugin plugin register  if you work with share preferences
    SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));
    FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
  }
}
```

**MainActivity.java**<br>
```java
package com.someview.someapp;

import io.flutter.embedding.android.FlutterActivity;
//import android.os.Bundle;
//import io.flutter.app.FlutterActivity;
//import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity  {
//  @Override
//  protected void onCreate(Bundle savedInstanceState) {
//    super.onCreate(savedInstanceState);
//    GeneratedPluginRegistrant.registerWith(this);
//  }
}
```

**AndroidManifest.xml:**
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.someview.someapp">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- AlarmManager plugin permissions -->
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="false">
        <meta-data
          android:name="flutterEmbedding"
          android:value="2" />
        <meta-data
            android:name="CHANNEL"
            android:value="asdchannel" />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <!-- AlarmManager plugin requirements -->
        <service
            android:name="io.flutter.plugins.androidalarmmanager.AlarmService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="false"/>
        <receiver
            android:name="io.flutter.plugins.androidalarmmanager.AlarmBroadcastReceiver"
            android:exported="false"/>
        <receiver
            android:name="io.flutter.plugins.androidalarmmanager.RebootBroadcastReceiver"
            android:enabled="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>

        <!-- LocalNotifications plugin requirements -->
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
    </application>
</manifest>

```

**Flutter doctor output** (want to mention that **iOS support is not required**):
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-GI)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2020.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
```

Thanks!

**Comment by iapicca** [comment]
@pdrontzas 
#### flutter 1.22.6 is obsolete
can you run 
```console
flutter channel stable
flutter upgrade -f
```
and provide your **_updated_** `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) _**not a snippet from production code**_

**Comment by philiposD** [comment]
@iapicca 

The latest stable version is  1.27.0-9.0.pre.20 and from what I've seen there is nowhere saying that 1.22.6 is deprecated, actually, you can download directly from Flutter - [link](https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_1.22.6-stable.zip)

**Comment by iapicca** [comment]
@philiposD 
with **_obsolete_** I didn't mean _deprecated_
I meant that no "new" version or "patches" will be released for version < 2.0
so even if a bug is found it will inevitably fixed in a version superior to the latest stable

ultimately
**_for the issue to be workable needs to be reproducible in the latest stable_**

**Comment by philiposD** [comment]
@iapicca 

Thanks for the info, I know that we can migrate with the latest and don't include null aware by setting the SDK version margins. As you mention, maybe it would be a good idea to try like that and see how the build goes. 
I will post the response and see how it goes.

**Comment by TahaTesser** [comment]
Hi @philiposD 
This is quite an old version of Flutter, when upgrading, it is expected to run into issues. Unless there is a bug or an issue with documentation there is  nothing to do here
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by philiposD** [comment]
Hi @TahaTesser, sorry for the late response regarding this project. Later on, I've tried upgrading multiple libraries and the entire version and it was working ok afterward.
Thank you very much for your help.
