### ISSUE TITLE
Error: '!state.down': is not true

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#7966]
commit 06f879b57ed40a192e4fafd1b6031c65754fdc5e

I received the following assertion while running Flutter under qemu on Magenta. It's not clear exactly what I did. The qemu window lost and regained focus because I used Ctrl-Alt.

```
[00249.670] 05593.05621> [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[00249.670] 05593.05621> 'package:flutter/src/gestures/converter.dart': Failed assertion: line 122: '!state.down': is not true.
[00249.670] 05593.05621> #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:33)
[00249.670] 05593.05621> #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:29)
[00249.670] 05593.05621> #2      PointerEventConverter.expand.<expand_sync_body> (package:flutter/src/gestures/converter.dart:122)
[00249.670] 05593.05621> #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:66)
[00249.670] 05593.05621> #4      ListQueue.addAll (dart:collection/queue.dart:637)
[00249.670] 05593.05621> #5      BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:32)
[00249.670] 05593.05621> #6      _dispatchPointerDataPacket (file:///Users/jimbe/fuchsia/flutter/lib/ui/hooks.dart:73)
```

**Comment by abarth** [comment]
Looks like Mozart sent us two `down` events for a pointer without an intervening `up` or `cancel`.  Probably we're missing a `cancel` when you Ctrl-Alt QEMU.  /cc @j9brown

**Comment by eseidelGoogle** [comment]
Got clarity that this is a qemu-only crash.

**Comment by zoechi** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
