### ISSUE TITLE
url_launcher crash on Android if `forceWebView` is null

### ISSUE THREAD

**Issue by jovanovski** [flutter/flutter#79719]
## Steps to Reproduce

1. Call `launch(url, forceWebView: null, forceSafariVC: null)` on Android

**Expected results:** 
URL to be launched in default browser, disregarding the `forceWebView` parameter being null. If parameter has null value, the default value should be assumed.

**Actual results:** 
A `PlatformException` is thrown. This only happens on Android, on iOS this is handled gracefully and the url is opened in Safari.

<details>
  <summary>Logs</summary>

```
E/MethodChannel#plugins.flutter.io/url_launcher(24593): Failed to handle method call
E/MethodChannel#plugins.flutter.io/url_launcher(24593): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:88)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/url_launcher(24593): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (24593): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/flutter (24593): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onLaunch(MethodCallHandlerImpl.java:88)
E/flutter (24593): 	at io.flutter.plugins.urllauncher.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/flutter (24593): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (24593): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (24593): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (24593): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (24593): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (24593): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (24593): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter (24593): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (24593): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (24593): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (24593): )
E/flutter (24593): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter (24593): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (24593): <asynchronous suspension>
E/flutter (24593): #2      MethodChannelUrlLauncher.launch.<anonymous closure> (package:url_launcher_platform_interface/method_channel_url_launcher.dart)
E/flutter (24593): <asynchronous suspension>
```

</details>

**Comment by stuartmorgan** [comment]
`forceWebView` has a non-nullable type; calling it with a null value is a programming error.

iOS behaves differently because, for legacy reasons, it could not be made non-nullable (see https://github.com/flutter/flutter/issues/79043 for further discussion.)
