### ISSUE TITLE
showDatePicker throws null exception on date picked when running on sound null safety

### ISSUE THREAD

**Issue by mat100payette** [flutter/flutter#79745]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Insert the following code below the counter text ending at line 102 in `main.dart`:
```dart
MaterialButton(
              onPressed: () async {
                final DateTime date = await showDatePicker(
                      context: context,
                      initialDate: DateTime(2021),
                      firstDate: DateTime(2000),
                      lastDate: DateTime(2025),
                    ) ??
                    DateTime(2000);

                debugPrint(date.toString());
              },
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: const <Widget>[
                  Text(
                    'Select date',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                    ),
                  ),
                ],
              ),
            )
```

3. Run the app (should run in sound null-safety). Click on the button to open the datepicker. Click on any date; this throws.

**Expected results:**
The datepicker lets you select a date normally.

**Actual results:**
On selection of a date, the code throws.

<details>
  <summary>Logs</summary>

```
Error: Expected a value of type 'String', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:61806/dart_sdk.js:5037:11)
    at Object.castError (http://localhost:61806/dart_sdk.js:5010:15)
    at Object.cast [as as] (http://localhost:61806/dart_sdk.js:5319:17)
    at Function.as (http://localhost:61806/dart_sdk.js:42751:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:61806/dart_sdk.js:157043:38)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:61806/dart_sdk.js:156956:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:61806/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
    at _DefaultBinaryMessenger.send (http://localhost:61806/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:61806/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:61806/dart_sdk.js:37393:34)
    at Object._async [as async] (http://localhost:61806/dart_sdk.js:37424:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:61806/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:61806/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:61806/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:61806/dart_sdk.js:37393:34)
    at Object._async [as async] (http://localhost:61806/dart_sdk.js:37424:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:61806/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
    at vibrate (http://localhost:61806/packages/flutter/src/services/haptic_feedback.dart.lib.js:17:55)
    at vibrate.next (<anonymous>)
    at runBody (http://localhost:61806/dart_sdk.js:37393:34)
    at Object._async [as async] (http://localhost:61806/dart_sdk.js:37424:7)
    at Function.vibrate (http://localhost:61806/packages/flutter/src/services/haptic_feedback.dart.lib.js:16:20)
    at calendar_date_picker._CalendarDatePickerState.new.[_vibrate] (http://localhost:61806/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2634:42)
    at calendar_date_picker._CalendarDatePickerState.new.[_handleDayChanged] (http://localhost:61806/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2678:21)
    at calendar_date_picker._MonthPickerState.new.[_handleDateSelected] (http://localhost:61806/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3080:11)
    at http://localhost:61806/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3457:28
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:61806/packages/flutter/src/material/icon_button.dart.lib.js:48455:31)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:61806/packages/flutter/src/gestures/recognizer.dart.lib.js:183:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:61806/packages/flutter/src/gestures/tap.dart.lib.js:393:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:61806/packages/flutter/src/gestures/tap.dart.lib.js:205:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:61806/packages/flutter/src/gestures/tap.dart.lib.js:182:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:61806/packages/flutter/src/gestures/arena.dart.lib.js:201:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:61806/packages/flutter/src/gestures/binding.dart.lib.js:366:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:61806/packages/flutter/src/gestures/binding.dart.lib.js:347:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:61806/packages/flutter/src/rendering/layer.dart.lib.js:5022:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:61806/packages/flutter/src/gestures/binding.dart.lib.js:321:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:61806/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:61806/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:61806/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
    at Object.invoke1 (http://localhost:61806/dart_sdk.js:175153:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:61806/dart_sdk.js:156928:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:61806/dart_sdk.js:157567:49)
    at http://localhost:61806/dart_sdk.js:157985:28
    at http://localhost:61806/dart_sdk.js:157941:16
    at http://localhost:61806/dart_sdk.js:157660:11
```

```
No issues found! (ran in 6.2s)
```

```
[√] Flutter (Channel master, 2.1.0-13.0.pre.381, on Microsoft Windows [version 10.0.18363.1440], locale fr-CA)
    • Flutter version 2.1.0-13.0.pre.381 at C:\Flutter\flutter
    • Framework revision 5c57a80cf6 (3 days ago), 2021-04-01 05:54:03 -0400
    • Engine revision 4b52a9f148
    • Dart version 2.13.0 (build 2.13.0-188.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\matpa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 2 categories.
```

</details>

**Comment by pedromassangocode** [comment]
Hi @mat100payette 
I cannot reproduce this on latest master channel with the code bellow.

```console
[   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:53267/devtools/browser/c3b98bb9-db60-4d7e-8941-39a7f2b4f324
[+1477 ms] DwdsInjector: Received request for entrypoint at http://localhost:53236/main_module.bootstrap.js
[   +9 ms] MetadataProvider: Loading debug metadata...
[  +20 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[ +261 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:53236/main_module.bootstrap.js
[+4783 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +64 ms] DevHandler: Debug service listening on ws://127.0.0.1:53333/590V5hmYsaE=/ws

[  +35 ms] This app is linked to the debug service: ws://127.0.0.1:53333/590V5hmYsaE=/ws
[   +8 ms] Debug service listening on ws://127.0.0.1:53333/590V5hmYsaE=/ws
[        ] 💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:53333/590V5hmYsaE=/ws
[+165366 ms] 2021-01-20 00:00:00.000
[+17420 ms] 2019-02-18 00:00:00.000
[+12728 ms] 2021-01-27 00:00:00.000

```
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            MaterialButton(
              onPressed: () async {
                final DateTime date = await showDatePicker(
                  context: context,
                  initialDate: DateTime(2021),
                  firstDate: DateTime(2000),
                  lastDate: DateTime(2025),
                ) ??
                    DateTime(2000);

                debugPrint(date.toString());
              },
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: const <Widget>[
                  Text(
                    'Select date',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                    ),
                  ),
                ],
              ),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.444, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.1.0-13.0.pre.444 at /Users/pedromassango/Code/flutter_master
    • Framework revision 824b1ad3f8 (2 days ago), 2021-04-03 15:24:02 -0400
    • Engine revision e393800c63
    • Dart version 2.13.0 (build 2.13.0-196.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 54.1.4
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.
```

</details>

**Comment by mat100payette** [comment]
@pedromassango It seems to be fixed indeed. Must've been a recent roll between pre.381 and pre.444.
Didn't see a duplicate of this, maybe I missed it.

Anyway thanks for the update !
