### ISSUE TITLE
showDatePicker throws errors for haptic feedback on web

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#79834]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace `lib/main.dart` with the following: 
```dart
import "package:flutter/material.dart";

void main() => runApp(
  MaterialApp(
    home: Scaffold(
      floatingActionButton: Builder(
        builder: (BuildContext context) => FloatingActionButton(
          onPressed: () => showDatePicker(
            firstDate: DateTime(2020, 01, 01),
            lastDate: DateTime(2022, 01, 01),
            initialDate: DateTime.now(),
            context: context,
          )
        )
      )
    )
  )
);
```
3. Click on the FAB and select a date from the popup

## Error: 
```
Error: Expected a value of type 'String', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5032:11)
    at Object.castError (http://localhost:5000/dart_sdk.js:5005:15)
    at Object.cast [as as] (http://localhost:5000/dart_sdk.js:5314:17)
    at Function.as (http://localhost:5000/dart_sdk.js:42400:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:5000/dart_sdk.js:155298:38)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:5000/dart_sdk.js:155214:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.js:2180:38)
    at _DefaultBinaryMessenger.send (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.js:2224:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.js:948:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:37260:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.js:946:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.js:1078:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.js:1056:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:37260:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.js:1055:20)
    at vibrate (http://localhost:5000/packages/flutter/src/services/haptic_feedback.dart.lib.js:30:55)
    at vibrate.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:37260:7)
    at Function.vibrate (http://localhost:5000/packages/flutter/src/services/haptic_feedback.dart.lib.js:29:20)
    at calendar_date_picker._CalendarDatePickerState.new.[_vibrate] (http://localhost:5000/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2654:42)
    at calendar_date_picker._CalendarDatePickerState.new.[_handleDayChanged] (http://localhost:5000/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2702:21)
    at calendar_date_picker._MonthPickerState.new.[_handleDateSelected] (http://localhost:5000/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3130:11)
    at http://localhost:5000/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3539:28
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:5000/packages/flutter/src/material/icon_button.dart.lib.js:50084:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:5000/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:5000/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:5000/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:5000/packages/flutter/src/gestures/tap.dart.lib.js:199:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:5000/packages/flutter/src/gestures/arena.dart.lib.js:221:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:334:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:313:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:5000/packages/flutter/src/rendering/layer.dart.lib.js:6071:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:284:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:257:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:246:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:5000/packages/flutter/src/gestures/binding.dart.lib.js:236:65)
    at Object.invoke1 (http://localhost:5000/dart_sdk.js:173249:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:5000/dart_sdk.js:155201:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:5000/dart_sdk.js:155815:49)
    at http://localhost:5000/dart_sdk.js:156224:26
    at http://localhost:5000/dart_sdk.js:156183:16
    at http://localhost:5000/dart_sdk.js:155908:11
```

The error is coming from this function, which is called whenever a new date is selected (probably among other things): 
https://github.com/flutter/flutter/blob/98a9195dce154ca80347dadcfa9c31ce2b67316e/packages/flutter/lib/src/material/calendar_date_picker.dart#L199-L211
There's no case for the web, which I believe is causing the error. Calling `HaptickFeedback.vibrate()` manually (from, say, the FAB) brings the same error. 

<details>
  <summary>Flutter Doctor</summary>

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
    • Flutter version 2.0.3 at C:\Users\levi\flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\levi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!
```

</details>

**Comment by xu-baolin** [comment]
It is redundant with #79013 and should have been fixed on the latest `master` channel.
I will close this as resolved, feel free to leave a comment if you disagree.
