### ISSUE TITLE
Take a picture using the camera in linux desktop

### ISSUE THREAD

**Issue by 177shivam** [flutter/flutter#79854]
## Use case
I was trying to capture image from camera using link [Take a picture using the camera](https://flutter.dev/docs/cookbook/plugins/picture-using-camera#complete-example) but seems like it only supports android and ios.

## Workaround?
If there is any workaround to achieve the same please help me in achieving that.

### Log 
while using the above implementation i got the following error while running the app and camera.length is **NULL**.
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
<asynchronous suspension>
#1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344)
<asynchronous suspension>
#2      MethodChannelCamera.availableCameras (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:62)
<asynchronous suspension>
#3      main (package:sixt/main.dart:13)
<asynchronous suspension>
```

### flutter doctor -v
```
[✓] Flutter (Channel unknown, 2.0.3, on Linux, locale en_IN)
    • Flutter version 2.0.3 at /home/shivam/flut/flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/lib/android-sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.47.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90
```

**Comment by pedromassangocode** [comment]
camera plugin is not supported on Linux platform. See the feature request issue https://github.com/flutter/flutter/issues/79854. Follow up on that issue for updates.
Thank you

**Comment by 177shivam** [comment]
@pedromassangocode is this issue will be updated as a feature request or you have mentioned same issue link for feature update by mistake in above comment.

**Comment by pedromassangocode** [comment]
Hi @177shivam 
Sorry, the correct issue link is https://github.com/flutter/flutter/issues/41710.
Thank you
