### ISSUE TITLE
 Failed assertion: line 25 pos 14: 'url != null': is not true.

### ISSUE THREAD

**Issue by z7b** [flutter/flutter#79865]
```


======== Exception caught by widgets library =======================================================
The following assertion was thrown building:
'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 25 pos 14: 'url != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      new NetworkImage (package:flutter/src/painting/_network_image_io.dart:25:14)
#3      new Image.network (package:flutter/src/widgets/image.dart:406:68)
#4      _listViewCategory.<anonymous closure>.<anonymous closure> (file:///C:/Users/Administrator/Desktop/mjaaz%201/lib/view/Pages/Home-page/components/HomeBody.dart:187:32)
#5      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1277:34)
#6      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
...
====================================================================================================

======== Exception caught by image resource service ================================================
Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:354))
====================================================================================================

```

**Comment by TahaTesser** [comment]
Hi @z7b 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by z7b** [comment]
> Thank you

**Comment by z7b** [comment]
![image](https://user-images.githubusercontent.com/42646553/113730328-75f95200-9700-11eb-979a-b4c5884bea5b.png)

**Comment by z7b** [comment]
@TahaTesser 
![image](https://user-images.githubusercontent.com/42646553/113730531-a6d98700-9700-11eb-992f-3129174ede14.png)
