### ISSUE TITLE
Failed assertion: line 25 pos 14: 'url != null': is not true.

### ISSUE THREAD

**Issue by z7b** [flutter/flutter#79868]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building:
'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 25 pos 14: 'url != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      new NetworkImage (package:flutter/src/painting/_network_image_io.dart:25:14)
#3      new Image.network (package:flutter/src/widgets/image.dart:406:68)
#4      _listViewCategory.<anonymous closure>.<anonymous closure> (file:///C:/Users/Administrator/Desktop/mjaaz%201/lib/view/Pages/Home-page/components/HomeBody.dart:187:32)
#5      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1277:34)
#6      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
...
====================================================================================================

======== Exception caught by image resource service ================================================
Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:354))
====================================================================================================

```
![image](https://user-images.githubusercontent.com/42646553/113731378-6c241e80-9701-11eb-8e17-4db852117bae.png)

**Comment by z7b** [comment]
@TahaTesser

**Comment by TahaTesser** [comment]
Hi @z7b 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample? (please avoid screenshot of the logs, copy/paste complete logs in the comment)
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
