### ISSUE TITLE
[cocoon] /api/check-waiting-pull-requests failing on null exception

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#79974]
```
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("contexts")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      CheckForWaitingPullRequests._parseQueryData (package:cocoon_service/src/request_handlers/check_for_waiting_pull_requests.dart:207:28)
#2      CheckForWaitingPullRequests._checkPRs (package:cocoon_service/src/request_handlers/check_for_waiting_pull_requests.dart:68:60)
<asynchronous suspension>
#3      CheckForWaitingPullRequests.get (package:cocoon_service/src/request_handlers/check_for_waiting_pull_requests.dart:43:5)
<asynchronous suspension>
#4      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)
<asynchronous suspension>
#5      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:144:7)
<asynchronous suspension>
#6      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:143:5)
<asynchronous suspension>
#7      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:125:9)
<asynchronous suspension>
```

**Comment by CaseyHillers** [comment]
`commit['status']` appears to be null, which is causing this failure. The first issue is that a failure on anyone PR causes all PRs to fail, so we should wrap each parse in a try/catch.

**Comment by godofredoc** [comment]
We can add try-catch to prevent specific repo failures blocking the other repos.

**Comment by CaseyHillers** [comment]
https://github.com/flutter/cocoon/pull/1119 is an example Cocoon PR where waiting for tree to go green worked
