### ISSUE TITLE
Flutter Web TypeError: Cannot read property 'new' of undefined

### ISSUE THREAD

**Issue by wisnuwiry** [flutter/flutter#80004]
## Steps to Reproduce

1. Run `flutter create <project_name>`.
2. Create a multiple packages in project
    a. Create package `settings`
    b. Create package `home`
    c.  Create package `auth`
3. Package `settings` depend on `home`
4. Package `home` depend on `auth`

**Expected results:** 
Runs normally as when running on the mobile version

**Actual results:** 

When I run the web version of my app it never runs normally, it always gets stuck before the `runApp` function. When I run the project on the Web I get an issue like the one below, but when I run it on the mobile issue below it never happened.

<details>
  <summary>TypeError: Cannot read property 'new' of undefined</summary>

```
 at main (http://localhost:55319/packages/storefront/main_dev.dart.lib.js:147:133)
    at main.next (<anonymous>)
    at http://localhost:55319/dart_sdk.js:37209:33
    at _RootZone.runUnary (http://localhost:55319/dart_sdk.js:37080:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:55319/dart_sdk.js:32336:29)
    at handleValueCallback (http://localhost:55319/dart_sdk.js:32863:49)
    at Function._propagateToListeners (http://localhost:55319/dart_sdk.js:32901:17)
    at _Future.new.[_completeWithValue] (http://localhost:55319/dart_sdk.js:32749:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55319/dart_sdk.js:32770:35)
    at Object._microtaskLoop (http://localhost:55319/dart_sdk.js:37332:13)
    at _startMicrotaskLoop (http://localhost:55319/dart_sdk.js:37338:13)
    at http://localhost:55319/dart_sdk.js:33109:9
```

```
$ flutter analyze
Analyzing storefront...
No issues found! (ran in 29.5s)
```

```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.867], locale en-ID)
    • Flutter version 2.0.4 at C:\flutter
    • Framework revision b1395592de (6 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\wisnu\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter       
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\wisnu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @wisnuwiry 

> Create package settings


Do you mean a folder called `settings` inside `lib`?  Can you please explain what do you mean by `multiple packages in project`. 

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository and complete `flutter run -d --verbose` logs running the minimal code sample?
Thank you

**Comment by wisnuwiry** [comment]
After I tried it, it turned out that the problem was when in each package I installed the same dependency, and when I removed the dependency I installed in all the packages the error suddenly disappeared.

**Comment by TahaTesser** [comment]
@wisnuwiry 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
