### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Invalid type for "path": null

### ISSUE THREAD

**Issue by totalitdevelopers** [flutter/flutter#80046]
## Command
```
flutter create --ios-language swift --android-language kotlin .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Invalid type for "path": null
```
#0      FileSystem.getPath (package:file/src/interface/file_system.dart:160:7)
#1      LocalFileSystem.directory (package:file/src/backends/local/local_file_system.dart:23:41)
#2      ErrorHandlingFileSystem.directory (package:flutter_tools/src/base/error_handling_io.dart:118:24)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:290:21)
<asynchronous suspension>
#4      Template.fromName (package:flutter_tools/src/template.dart:75:32)
<asynchronous suspension>
#5      CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:380:31)
<asynchronous suspension>
#6      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:23)
<asynchronous suspension>
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:31)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /home/tasu/snap/flutter/common/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/tasu/Android/Sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /usr/lib/jvm/java-8-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /opt/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment]
Hi @totalitdevelopers 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/56811
Follow-up there for updates. Closing this as duplicate.
