### ISSUE TITLE
Cocoon failing to schedule new comits

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#80128]
NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      remoteFileContent (package:cocoon_service/src/foundation/utils.dart:41:53)
#2      Scheduler.loadDevicelabManifest (package:cocoon_service/src/service/scheduler.dart:213:34)
#3      Scheduler._getTasks (package:cocoon_service/src/service/scheduler.dart:191:32)
<asynchronous suspension>
#4      Scheduler._addCommit (package:cocoon_service/src/service/scheduler.dart:117:30)
<asynchronous suspension>
#5      Scheduler.addCommits (package:cocoon_service/src/service/scheduler.dart:68:7)
<asynchronous suspension>
#6      RefreshGithubCommits.get (package:cocoon_service/src/request_handlers/refresh_github_commits.dart:65:7)
<asynchronous suspension>
#7      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)
<asynchronous suspension>
#8      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:144:7)
<asynchronous suspension>
#9      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:143:5)
<asynchronous suspension>
#10     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:133:9)
<asynchronous suspension>

**Comment by CaseyHillers** [comment]
We rolled the dashboard back yesterday, but I'm not sure if any actions were taken. I rolled back the dashboard again, and will start investigating.

**Comment by CaseyHillers** [comment]
The issue is
```
Future<String> remoteFileContent(
  HttpClientProvider branchHttpClientProvider,
...
}) async {
  ....
  final HttpClient client = branchHttpClientProvider();
```

`branchHttpClientProvider` is null when passed from `Scheduler`. I'll send a cleanup PR
