### ISSUE TITLE
Unable to type in UITextView with physical keyboard

### ISSUE THREAD

**Issue by shimomiya-k** [flutter/flutter#80123]
There is a fatal [bug](https://github.com/flutter/flutter/issues/70267) in Flutter's Japanese text input.
Therefore, in my app, UITextView is displayed as PlatformView.
The app is now compatible with Flutter 2. Then, I couldn't input with the physical keyboard.

It can be reproduced with this [package.](https://pub.dev/packages/flutter_native_text_input) Is there a way to deal with it?

Run flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.1 20C69 darwin-x64, locale
    ja-JP)
    • Flutter version 2.0.3 at /Users/shimomiya_k/Develop/flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/shimomiya_k/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by iapicca** [comment]
@shimomiya-k 
[flutter_native_text_input](https://pub.dev/packages/flutter_native_text_input) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/henryleunghk/flutter-native-text-input/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by shimomiya-k** [comment]
@iapicca 
Because of [this bug](https://github.com/flutter/flutter/issues/70267), I'm using UITextView.
However, UITextView does not allow input with the physical keyboard.

I don't use [flutter_native_text_input](https://pub.dev/packages/flutter_native_text_input), but I have a similar implementation and the same phenomenon occurs. So I presented it as a sample.

It's a phenomenon that has happened since I updated to Flutter2, so I made an issue.

You can get the following error by typing the spacebar on physical keyboard.

```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following _CastError was thrown during a platform message callback:
flutter: Null check operator used on a null value
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ShortcutManager.handleKeypress
package:flutter/…/widgets/shortcuts.dart:363
flutter: #1      _ShortcutsState._handleOnKey
package:flutter/…/widgets/shortcuts.dart:710
flutter: #2      FocusManager._handleRawKeyEvent
package:flutter/…/widgets/focus_manager.dart:1651
flutter: #3      RawKeyboard._handleKeyEvent
package:flutter/…/services/raw_keyboard.dart:641
flutter: #4      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:73
flutter: #5      BasicMessageChannel.setMessageHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:72
flutter: #6      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:284
flutter: #7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:221:15)
flutter: #11     _invoke3 (dart:ui/hooks.dart:220:10)
flutter: #12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457:7)
flutter: #13     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by iapicca** [comment]
> I don't use [flutter_native_text_input](https://pub.dev/packages/flutter_native_text_input), but I have a similar implementation and the same phenomenon occurs. So I presented it as a sample.

@shimomiya-k 
can you providea [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) a full 3rd party package hardly qualify

**Comment by shimomiya-k** [comment]
@iapicca 

I created [a minimal project](https://github.com/shimomiya-k/native_textfield_sample) on GitHub.

I'm just displaying the UITextView, but the physical keyboard doesn't respond and the virtual keyboard does.

**Comment by TahaTesser** [comment]
Hi @shimomiya-k 
Thanks for filing the issue, I can verify the issue using a physical keyboard, works with the on-screen keyboard
<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b1395592de (10 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.574, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.574 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 02efffc134 (2 days ago), 2021-04-10 03:49:01 -0400
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
	
</details>

**Comment by shimomiya-k** [comment]
Hi @TahaTesser 

Thank you for your confirmation !

It does not occur in Flutter2 and earlier versions, so use version 1.22.6 until a solution is found.

**Comment by chinmaygarde** [comment]
cc @gspencergoog For the exception while using the keyboard.

**Comment by gspencergoog** [comment]
The exception is related to no focus being set. I suspect that if there were a widget that set the focus, then the exception wouldn't occur.

Created https://github.com/flutter/flutter/pull/80302 to be more tolerant of apps with no focus set.

**Comment by Robert-Hillary** [comment]
I'm seeing the same issue that @shimomiya-k is experiencing except via an embedded platform `WKWebView` instead of a `UITextField`. 

I'm using the [html_editor_enhanced](https://pub.dev/packages/html_editor_enhanced) package for rich html text editing which internally uses [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) (which I believe embeds a native `WKWebView` via a platform view).

This issue is effectively resulting in external/physical keyboards being unable to perform input for any site displayed via such web views within a flutter application.

If there's any information in addition to the `flutter doctor` output below that I can provide to help resolve this issue please let me know.

<details>
  <summary>flutter doctor -v</summary>
  
  ```
 [✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
     • Flutter version 2.0.4 at /Users/rohi/flutter
     • Framework revision b1395592de (13 days ago), 2021-04-01 14:25:01 -0700
     • Engine revision 2dce47073a
     • Dart version 2.12.2
 
 [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
     • Android SDK at /Users/rohi/Library/Android/sdk
     • Platform android-30, build-tools 30.0.3
     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
     • All Android licenses accepted.
 
 [✓] Xcode - develop for iOS and macOS
     • Xcode at /Applications/Xcode.app/Contents/Developer
     • Xcode 12.3, Build version 12C33
     • CocoaPods version 1.10.1
 
 [✓] Chrome - develop for the web
     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
 
 [✓] Android Studio (version 4.1)
     • Android Studio at /Applications/Android Studio.app/Contents
     • Flutter plugin can be installed from:
       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
     • Dart plugin can be installed from:
       🔨 https://plugins.jetbrains.com/plugin/6351-dart
     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
 
 [✓] VS Code (version 1.55.1)
     • VS Code at /Applications/Visual Studio Code.app/Contents
     • Flutter extension version 3.21.0
 
 [✓] Connected device (1 available)
     • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome 89.0.4389.128
 
 • No issues found!
```
</details>

**Comment by jjmean2** [comment]
I have the same experience with this when using [webview_flutter](https://github.com/flutter/plugins/tree/master/packages/webview_flutter) package with flutter 2.0.5

Any input html element in any site, rendered in `Webview` (webview_flutter) does not accept text input from physical keyboard. Software keyboard has no issue, but typing with physical keyboard connected to device, does no action. 
I found this issue in ios simulator, but it's the same in physical ios device.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale ko-KR)
    • Flutter version 2.0.5 at /Users/ljw/dev/env/flutter
    • Framework revision adc687823a (10일 전), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/ljw/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • ANDROID_HOME = /Users/ljw/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile)     • A8117EF2-B790-4609-9A12-5AD178747F8B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • iPhone 12 Pro Max (mobile) • C605EB11-AB44-459D-BE7C-59DE6E2C192D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.85
    ! Error: iPad-pasvi is not connected. Xcode will continue when iPad-pasvi is connected. (code -13)

• No issues found!
```
</details>

**Comment by brightknight08** [comment]
do you guys have any solution or workaround for this? we're implementing [dragon stt](https://www.nuance.com/dragon.html) in flutter 2.2.3 and it is not accepting input from physical keyboard. no issues found on flutter 1.22.6 though.

**Comment by shimomiya-k** [comment]
Hi.

Does Flutter2.5.3 (stable) fix this problem?

The bug cannot be reproduced with the [sample code](https://github.com/shimomiya-k/native_textfield_sample).

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.1 20G224 darwin-x64, locale ja-JP)
    • Flutter version 2.5.3 at /Users/shimomiya_k/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/shimomiya_k/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0
```
</details>
