### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for E:\development\flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by slabgames** [flutter/flutter#80181]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. fresh install flutter from 
2. run flutter doctor
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for E:\development\flutter\bin\cache\dart-sdk\bin\pub.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:282:34)
<asynchronous suspension>
#8      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:222:7)
<asynchronous suspension>
#9      PubDependencies.update (package:flutter_tools/src/cache.dart:774:5)
<asynchronous suspension>
#10     Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.1198], locale id-ID)
    • Flutter version 2.0.4 at E:\development\flutter
    • Framework revision b1395592de (8 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\development\android_sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\development\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.50.0)
    • VS Code at C:\Users\SLAB\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 86.0.622.58

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by slabgames** [comment]
it's the antivirus issue. closing this
