### ISSUE TITLE
Flutter Run failing when targeting android with Execution failed for task ':app:compressDebugAssets'.

### ISSUE THREAD

**Issue by gompocp** [flutter/flutter#80197]
Flutter run failing when running for android similarly to #74015

I'm not sure on what exactly I did but I created a new project (non flutter) in android studio and I remember it getting stuck on downloading something for gradle. I ended up having to pull up task manager and force closing android studio. Since then trying to run flutter for android on any project (even on newly created projects has resulted in the error). Apologies on not being able to give more exact info. I have tried reinstalling flutter and restarting my pc but that didn't help.
```
* What went wrong:
Execution failed for task ':app:compressDebugAssets'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CompressAssetsWorkAction
> E:\Windows\Documents\Coding\Flutter\bug\build\app\intermediates\merged_assets\debug\out
```

<details>
  <summary>Logs</summary>

`flutter run --verbose`
```
[  +62 ms] executing: [E:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[        ] executing: [E:\src\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +38 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +40 ms] executing: [E:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [E:\src\flutter/] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [E:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +41 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] executing: C:\Users\gompo\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +35 ms] List of devices attached
           R58N21V7LRZ            device product:a71naeea model:SM_A715F device:a71 transport_id:1
[   +4 ms] C:\Users\gompo\AppData\Local\Android\sdk\platform-tools\adb.exe -s R58N21V7LRZ shell getprop
[ +100 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +78 ms] Skipping pub get: version match.
[  +91 ms] Generating E:\Windows\Documents\Coding\Flutter\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +65 ms] ro.hardware = qcom
[  +28 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[  +11 ms] complete
[   +4 ms] Launching lib\main.dart on SM A715F in debug mode...
[   +4 ms] E:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev E:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root E:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill C:\Users\gompo\AppData\Local\Temp\flutter_tools.b22fa8a7\flutter_tool.4b33525\app.dill --packages E:\Windows\Documents\Coding\Flutter\bug\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +13 ms] executing: C:\Users\gompo\AppData\Local\Android\sdk\platform-tools\adb.exe -s R58N21V7LRZ shell -x logcat -v time -t 1
[   +5 ms] <- compile package:bug/main.dart
[ +198 ms] --------- beginning of main
                    04-10 18:37:44.226 D/TelephonyManager( 1374): getAllCellInfo : Caller (PID / UID / TID): 1374 / 1000 / 1902
[   +8 ms] executing: C:\Users\gompo\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +16 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Users\gompo\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\gompo\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +20 ms] Building APK
[  +14 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] Using gradle from E:\Windows\Documents\Coding\Flutter\bug\android\gradlew.bat.
[   +1 ms] E:\Windows\Documents\Coding\Flutter\bug\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +7 ms] executing: E:\Program Files\Android\Android Studio\jre\bin\java -version
[  +67 ms] Exit code 0 from: E:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +1 ms] executing: [E:\Windows\Documents\Coding\Flutter\bug\android/] E:\Windows\Documents\Coding\Flutter\bug\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=E:\Windows\Documents\Coding\Flutter\bug\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3488 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +64 ms] executing: [E:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] b1395592de68cc8ac4522094ae59956dd21a91db
[        ] [        ] executing: [E:\src\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] [  +38 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] [        ] 2.0.4
[        ] [  +37 ms] executing: [E:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [E:\src\flutter/] git ls-remote --get-url origin
[        ] [  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +54 ms] executing: [E:\src\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +30 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +54 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +52 ms] Initializing file store
[        ] [  +11 ms] Done initializing file store
[        ] [  +27 ms] Skipping target: gen_localizations
[        ] [ +376 ms] Skipping target: kernel_snapshot
[        ] [  +19 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +163 ms] [ +514 ms] debug_android_application: Complete
[ +296 ms] [ +242 ms] Persisting file store
[        ] [  +17 ms] Done persisting file store
[        ] [  +14 ms] build succeeded.
[        ] [  +17 ms] "flutter assemble" took 1,358ms.
[        ] [   +2 ms] ensureAnalyticsSent: 0ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +2 ms] exiting with code 0
[  +89 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +106 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[  +92 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets UP-TO-DATE
[+9299 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[+2593 ms] > Task :app:mergeDebugResources UP-TO-DATE
[ +110 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] A problem was found with the configuration of task ':app:processDebugManifest' (type 'ProcessMultiApkApplicationManifest').
[        ] > File 'E:\Windows\Documents\Coding\Flutter\bug\build\app\intermediates\merged_manifest\debug\out\AndroidManifest.xml' specified for property 'mainMergedManifest' does not exist.
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 16s
[        ] > Task :app:processDebugManifest FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 14 actionable tasks: 4 executed, 10 up-to-date
[ +527 ms] Running Gradle task 'assembleDebug'... (completed in 16.9s)
[   +4 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 17,705ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 1

```

`flutter analyze`
```
Analyzing bug...
No issues found! (ran in 1.2s)

```

`flutter doctor -v`
```
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale en-IE)
    • Flutter version 2.0.4 at E:\src\flutter
    • Framework revision b1395592de (9 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\gompo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31105.61
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM A715F (mobile) • R58N21V7LRZ • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 89.0.774.75

• No issues found!

```

</details>

**Comment by iapicca** [comment]
duplicate of https://github.com/flutter/flutter/issues/76668

**Comment by gompocp** [comment]
Seems like clearing out .gradle and creating a fresh project from scratch cleared it up
