### ISSUE TITLE
[Flutter 2]: Maybe there's something wrong with Flutter's accessibility code

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#80233]
## Logs

```
Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at java.lang.reflect.Method.invoke(Method.java)
       at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.getChildId(AccessibilityViewEmbedder.java:532)
       at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.access$500(AccessibilityViewEmbedder.java:429)
       at io.flutter.view.AccessibilityViewEmbedder.addChildrenToFlutterNode(AccessibilityViewEmbedder.java:171)
       at io.flutter.view.AccessibilityViewEmbedder.convertToFlutterNode(AccessibilityViewEmbedder.java:145)
       at io.flutter.view.AccessibilityViewEmbedder.getRootNode(AccessibilityViewEmbedder.java:94)
       at io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo(AccessibilityBridge.java:562)
       at android.view.View.populateVirtualStructure(View.java:9364)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.populateVirtualStructure(View.java:9367)
       at android.view.View.onProvideVirtualStructureCompat(View.java:8785)
       at android.view.View.onProvideVirtualStructure(View.java:8766)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:9432)
       at android.view.View.dispatchProvideStructure(View.java:9379)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3665)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3738)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3738)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:519)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3398)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1911)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.1)
[√] Connected device (4 available)

• No issues found!
```

Background:
On a app with ~500k installs, there are 311 crash events affecting 162 users in the last 30 days, after upgrading to Flutter 2.

![image](https://user-images.githubusercontent.com/379339/114319851-9ef75980-9ae9-11eb-8683-835b0c2b6930.png)

**Comment by darshankawar** [comment]
@JCKodel 
The stacktrace is very similar to another open issue, https://github.com/flutter/flutter/issues/38063
Please follow-up there for updates. Closing this as duplicate.
If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by JCKodel** [comment]
@darshankawar I don't use Google Maps in this project, but if you think is related, that's fine.

Nevertheless, here's my pubspec.yaml:

```yaml
name: meucronogramacapilar
description: Meu Cronograma Capilar
version: 20.2104.0613+2021040613
publish_to: 'none'

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  admob_flutter:
    path: ../plugins/admob_flutter-1.0.1
  firebase_auth:
    path: ../plugins/firebase_auth-0.20.1
  dash_chat:
    path: ../plugins/dash_chat-1.1.15
  flutter_foreground_plugin:
    path: ../plugins/flutter_foreground_service_plugin-master
  flutter_local_notifications:
    path: ../plugins/flutter_local_notifications-master/flutter_local_notifications
  zefyr:
    path: ../plugins/zefyr-0.12.0
  before_after: ^2.1.0
  cached_network_image: ^2.5.0
  connectivity: ^2.0.2
  datetime_picker_formfield: ^1.0.0
  device_info: ^1.0.0
  diacritic: ^0.1.1
  dio: ^3.0.10
  firebase_analytics: ^7.0.1
  firebase_auth_web: ^0.3.3
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  flutter_alert: ^0.4.0
  flutter_device_type: ^0.3.2
  flutter_email_sender: ^4.0.0
  flutter_facebook_login: ^3.0.0
  flutter_image_compress: ^0.7.0
  flutter_jailbreak_detection: ^1.4.0
  flutter_masked_text: ^0.8.0
  flutter_mobx: ^1.1.0+2
  flutter_speed_dial: ^1.2.5
  flutter_svg: ^0.19.1
  flutter_svprogresshud: ^0.0.6
  google_api_availability: ^2.0.4
  google_sign_in: ^4.5.9
  html: ^0.14.0+4
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  in_app_purchase: ^0.5.1
  intl: ^0.17.0
  jaguar_jwt: ^2.1.6
  json_table: ^1.4.0
  launch_review: ^2.0.0
  material_design_icons_flutter: ^4.0.5855
  mobx: ^1.2.1+4
  package_info: ^0.4.3+2
  path_provider: ^1.6.27
  photo_view: ^0.10.3
  sign_in_with_apple: ^2.5.4
  sqflite: ^1.3.2+2
  sticky_headers: ^0.1.8+1
  table_calendar: ^2.3.3
  timeago: ^2.0.29
  timeago_flutter: ^0.3.0
  timezone: ^0.5.6
  url_launcher: ^5.7.10
  uuid: ^2.2.2
  webview_flutter: ^2.0.2
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  build_runner: ^1.10.13
  mobx_codegen: ^1.1.2

dependency_overrides:
  intl: 0.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
```

**Comment by darshankawar** [comment]
@JCKodel 
The title of the original issue could be misleading, but if you look at the labels it has, `platform-views`, `accessibility`, it should suffice to be a related to yours.
