### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for D:\Desenvolvimento\flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by jpedrosouza** [flutter/flutter#80238]
## Command
```
flutter run -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for D:\Desenvolvimento\flutter\bin\cache\dart-sdk\bin\pub.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:65:30)
#2      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:618:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:618:12)
#5      DevtoolsServerLauncher._checkForActiveDevTools (package:flutter_tools/src/devtools_launcher.dart:120:74)
#6      DevtoolsServerLauncher.launch (package:flutter_tools/src/devtools_launcher.dart:72:43)
<asynchronous suspension>
#7      DevtoolsServerLauncher.serve (package:flutter_tools/src/devtools_launcher.dart:176:7)
<asynchronous suspension>
#8      ResidentRunner.serveDevToolsGracefully (package:flutter_tools/src/resident_runner.dart:1284:7)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#10     HotRunner.attach (package:flutter_tools/src/run_hot.dart:178:7)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:639:26)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
```
```
[✓] Flutter (Channel stable, 2.0.2, on Microsoft Windows [versÃ£o
    6.1.7601], locale pt-BR)
    • Flutter version 2.0.2 at D:\Desenvolvimento\flutter
    • Framework revision 8962f6dc68 (4 weeks ago), 2021-03-11 13:22:20
      -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at C:\Users\Pedro\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Pedro\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • moto g 7 play (mobile) • ZF52262RVK • android-arm    • Android 10
      (API 29)
    • Chrome (web)           • chrome     • web-javascript • Google
      Chrome 89.0.4389.114
    • Edge (web)             • edge       • web-javascript • Microsoft
      Edge 89.0.774.75

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aafb3a8b9b0c36241c5f5b34ee914770f015818
### Plugins
cloud_firestore-1.0.1
cloud_firestore_web-1.0.1
file_picker-3.0.0
firebase_analytics-7.1.1
firebase_analytics_web-0.2.0+1
firebase_auth-1.0.1
firebase_auth_web-1.0.2
firebase_core-1.0.1
firebase_core_web-1.0.1
firebase_crashlytics-1.0.0
firebase_performance-0.6.0
firebase_storage-8.0.0
firebase_storage_web-1.0.1
flutter_native_image-0.0.5+3
flutter_plugin_android_lifecycle-2.0.0
image_cropper-1.4.0
path_provider_linux-2.0.0
path_provider_windows-2.0.0
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0

**Comment by iapicca** [comment]
@jpedrosouza 
please double check that isn't a problem caused by your antivirus https://github.com/flutter/flutter/issues/80181#issuecomment-817090881

**Comment by jpedrosouza** [comment]
I managed to solve the problem just by running the `flutter upgrade` command.
