### ISSUE TITLE
Flutter 2.0 crash on Huawei (Android X) .

### ISSUE THREAD

**Issue by Oklahomawhore** [flutter/flutter#80245]
It's a fatal crash and every other phone is working fine.

```
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
E/AndroidRuntime(25835): FATAL EXCEPTION: main
E/AndroidRuntime(25835): Process: com.android.vending, PID: 25835
E/AndroidRuntime(25835): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.ulugames.app flg=0x4000010 (has extras) } in psx@d61e341
E/AndroidRuntime(25835): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1641)
E/AndroidRuntime(25835): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime(25835): 	at android.os.Handler.handleCallback(Handler.java:888)
E/AndroidRuntime(25835): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(25835): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(25835): 	at android.app.ActivityThread.main(ActivityThread.java:8201)
E/AndroidRuntime(25835): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25835): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(25835): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(25835): Caused by: java.lang.SecurityException: MATCH_ANY_USER flag requires INTERACT_ACROSS_USERS permission at com.android.server.pm.PackageManagerService.getPackageInfoInternal:7347472 com.android.server.pm.PackageManagerService.getPackageInfo:7347248 com.android.server.pm.HwPackageManagerService.getPackageInfo:4227924 android.content.pm.IPackageManager$Stub.onTransact:8151652 com.android.server.pm.PackageManagerService.onTransact:7440476 : Neither user 10396 nor current process has android.permission.INTERACT_ACROSS_USERS.
E/AndroidRuntime(25835): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(25835): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(25835): 	at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(25835): 	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4954)
E/AndroidRuntime(25835): 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:193)
E/AndroidRuntime(25835): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
E/AndroidRuntime(25835): 	at ptp.j(SourceFile:2)
E/AndroidRuntime(25835): 	at ptp.b(Unknown Source:0)
E/AndroidRuntime(25835): 	at psu.a(SourceFile:2)
E/AndroidRuntime(25835): 	at psq.a(SourceFile:2)
E/AndroidRuntime(25835): 	at psq.a(SourceFile:24)
E/AndroidRuntime(25835): 	at psx.onReceive(Unknown Source:2)
E/AndroidRuntime(25835): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1631)
E/AndroidRuntime(25835): 	... 8 more
E/AndroidRuntime(25835): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(25835): 	at android.app.ContextImpl.enforce(libmapleframework.so:8178376)
E/AndroidRuntime(25835): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(libmapleframework.so:8176060)
E/AndroidRuntime(25835): 	at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(libmapleservices.so:7472732)
E/AndroidRuntime(25835): 	at com.android.server.pm.PackageManagerService.updateFlagsForPackage(libmapleservices.so:7450660)
E/AndroidRuntime(25835): 	at com.android.server.pm.PackageManagerService.getPackageInfoInternal(libmapleservices.so:7347472)
E/AndroidRuntime(25835): 
E/AndroidRuntime(31807): FATAL EXCEPTION: main
E/AndroidRuntime(31807): Process: com.google.android.gms.persistent, PID: 31807
E/AndroidRuntime(31807): java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31807): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241)
E/AndroidRuntime(31807): 	at android.app.ActivityThread.access$2200(ActivityThread.java:298)
E/AndroidRuntime(31807): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2223)
E/AndroidRuntime(31807): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(31807): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(31807): 	at android.app.ActivityThread.main(ActivityThread.java:8201)
E/AndroidRuntime(31807): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31807): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(31807): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(31807): Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31807): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(31807): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(31807): 	at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(31807): 	at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
E/AndroidRuntime(31807): 	at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
E/AndroidRuntime(31807): 	at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
E/AndroidRuntime(31807): 	at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
E/AndroidRuntime(31807): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
E/AndroidRuntime(31807): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7225)
E/AndroidRuntime(31807): 	... 8 more
E/AndroidRuntime(31809): FATAL EXCEPTION: main
E/AndroidRuntime(31809): Process: com.google.android.gms.persistent, PID: 31809
E/AndroidRuntime(31809): java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31809): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241)
E/AndroidRuntime(31809): 	at android.app.ActivityThread.access$2200(ActivityThread.java:298)
E/AndroidRuntime(31809): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2223)
E/AndroidRuntime(31809): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(31809): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(31809): 	at android.app.ActivityThread.main(ActivityThread.java:8201)
E/AndroidRuntime(31809): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31809): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(31809): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(31809): Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31809): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(31809): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(31809): 	at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(31809): 	at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
E/AndroidRuntime(31809): 	at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
E/AndroidRuntime(31809): 	at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
E/AndroidRuntime(31809): 	at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
E/AndroidRuntime(31809): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
E/AndroidRuntime(31809): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7225)
E/AndroidRuntime(31809): 	... 8 more
E/AndroidRuntime(31811): FATAL EXCEPTION: main
E/AndroidRuntime(31811): Process: com.google.android.gms.persistent, PID: 31811
E/AndroidRuntime(31811): java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31811): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241)
E/AndroidRuntime(31811): 	at android.app.ActivityThread.access$2200(ActivityThread.java:298)
E/AndroidRuntime(31811): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2223)
E/AndroidRuntime(31811): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(31811): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(31811): 	at android.app.ActivityThread.main(ActivityThread.java:8201)
E/AndroidRuntime(31811): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31811): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(31811): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(31811): Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31811): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(31811): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(31811): 	at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(31811): 	at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
E/AndroidRuntime(31811): 	at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
E/AndroidRuntime(31811): 	at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
E/AndroidRuntime(31811): 	at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
E/AndroidRuntime(31811): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
E/AndroidRuntime(31811): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7225)
E/AndroidRuntime(31811): 	... 8 more
E/AndroidRuntime(31811): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(31811): 	at android.app.ContextImpl.enforce(libmapleframework.so:8178376)
E/AndroidRuntime(31811): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(libmapleframework.so:8176060)
E/AndroidRuntime(31811): 	at com.android.server.pm.PackageManagerService.addOnPermissionsChangeListener(libmapleservices.so:4416508)
E/AndroidRuntime(31811): 	at android.content.pm.IPackageManager$Stub.onTransact(libmapleframework.so:8117472)
E/AndroidRuntime(31811): 	at com.android.server.pm.PackageManagerService.onTransact(libmapleservices.so:7440476)
E/AndroidRuntime(31811): 
E/AndroidRuntime(31812): FATAL EXCEPTION: main
E/AndroidRuntime(31812): Process: com.google.android.gms.persistent, PID: 31812
E/AndroidRuntime(31812): java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31812): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241)
E/AndroidRuntime(31812): 	at android.app.ActivityThread.access$2200(ActivityThread.java:298)
E/AndroidRuntime(31812): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2223)
E/AndroidRuntime(31812): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(31812): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(31812): 	at android.app.ActivityThread.main(ActivityThread.java:8201)
E/AndroidRuntime(31812): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31812): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(31812): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(31812): Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31812): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(31812): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(31812): 	at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(31812): 	at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
E/AndroidRuntime(31812): 	at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
E/AndroidRuntime(31812): 	at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
E/AndroidRuntime(31812): 	at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
E/AndroidRuntime(31812): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
E/AndroidRuntime(31812): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7225)
E/AndroidRuntime(31812): 	... 8 more
E/AndroidRuntime(31814): FATAL EXCEPTION: main
E/AndroidRuntime(31814): Process: com.google.android.gms.persistent, PID: 31814
E/AndroidRuntime(31814): java.lang.RuntimeException: Unable to create application co.g.App: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31814): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7241)
E/AndroidRuntime(31814): 	at android.app.ActivityThread.access$2200(ActivityThread.java:298)
E/AndroidRuntime(31814): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2223)
E/AndroidRuntime(31814): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(31814): 	at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(31814): 	at android.app.ActivityThread.main(ActivityThread.java:8201)
E/AndroidRuntime(31814): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31814): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(31814): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(31814): Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10395 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
E/AndroidRuntime(31814): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(31814): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(31814): 	at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(31814): 	at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:9033)
E/AndroidRuntime(31814): 	at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1627)
E/AndroidRuntime(31814): 	at scq.a(:com.google.android.gms@19530042@19.5.30 (120300-275531062):12)
E/AndroidRuntime(31814): 	at rmb.onCreate(:com.google.android.gms@19530042@19.5.30 (120300-275531062):142)
E/AndroidRuntime(31814): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
E/AndroidRuntime(31814): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7225)
E/AndroidRuntime(31814): 	... 8 more
E/AndroidRuntime(31814): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(31814): 	at android.app.ContextImpl.enforce(libmapleframework.so:8178376)
E/AndroidRuntime(31814): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(libmapleframework.so:8176060)
E/AndroidRuntime(31814): 	at com.android.server.pm.PackageManagerService.addOnPermissionsChangeListener(libmapleservices.so:4416508)
E/AndroidRuntime(31814): 	at android.content.pm.IPackageManager$Stub.onTransact(libmapleframework.so:8117472)
E/AndroidRuntime(31814): 	at com.android.server.pm.PackageManagerService.onTransact(libmapleservices.so:7440476)
E/AndroidRuntime(31814): 
```

**Comment by darshankawar** [comment]
@Oklahomawhore 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can replicate locally ?
Thanks.
