### ISSUE TITLE
Connectivity package false WIFI detections on Android

### ISSUE THREAD

**Issue by matancohen365** [flutter/flutter#80241]
Hello ,

When I turn off the WIFI the connectivity package detects that I have an internet connection.

https://pub.dev/packages/connectivity

## Steps to Reproduce

```dart

import 'dart:async';

import 'package:connectivity/connectivity.dart'; /// Im using connectivity: ^3.0.3
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _internetState = 'unknown';

  final Connectivity _connectivity = Connectivity();

  StreamSubscription<ConnectivityResult> _connectivitySubscription;

  @override
  void initState() {
    _connectivitySubscription =
        _connectivity.onConnectivityChanged.listen(_handleResult);
    super.initState();
  }

  @override
  void dispose() {
    _connectivitySubscription?.cancel();
    super.dispose();
  }

  void _handleResult(ConnectivityResult result) {
    print(result);

    setState(() {
      _internetState = (result == ConnectivityResult.none ? 'none' : 'connected');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Text(_internetState)),
    );
  }
}


```

```
1. 
start the app with wifi on , mobile off

2.
turn wifi off

3.
turn wifi on
```

**Expected results:**

```
I/flutter (30308): ConnectivityResult.wifi
I/flutter (30308): ConnectivityResult.none
I/flutter (30308): ConnectivityResult.wifi
```

**Actual results:**

```
I/flutter (30308): ConnectivityResult.wifi
I/flutter (30308): ConnectivityResult.wifi
I/flutter (30308): ConnectivityResult.wifi
```

<details>
  <summary>Logs</summary>

```

[  +62 ms] executing: [C:\tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b1395592de68cc8ac4522094ae59956dd21a91db
[        ] executing: [C:\tools\flutter/] git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[  +32 ms] Exit code 0 from: git tag --points-at b1395592de68cc8ac4522094ae59956dd21a91db
[        ] 2.0.4
[  +31 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\tools\flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] executing: [C:\tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +51 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +29 ms] List of devices attached
           N9Q7N16929003861       device product:VIE-L09 model:VIE_L09 device:HWVIE transport_id:2
[   +5 ms] C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe -s N9Q7N16929003861 shell getprop
[  +64 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] Skipping pub get: version match.
[  +14 ms] Found plugin connectivity at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-3.0.3\
[   +5 ms] Found plugin connectivity_for_web at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_for_web-0.4.0\
[   +1 ms] Found plugin connectivity_macos at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.2.0\
[  +91 ms] Found plugin connectivity at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-3.0.3\
[   +2 ms] Found plugin connectivity_for_web at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_for_web-0.4.0\
[   +1 ms] Found plugin connectivity_macos at C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.2.0\
[  +19 ms] Generating C:\Users\Matan\Desktop\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +40 ms] ro.hardware = hi3650
[        ] ro.build.characteristics = default
[  +30 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +4 ms] Launching lib\main.dart on VIE L09 in debug mode...
[   +5 ms] C:\tools\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\tools\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\tools\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill C:\Users\Matan\AppData\Local\Temp\flutter_tools.a2fe02e7\flutter_tool.a48b35e9\app.dill --packages C:\Users\Matan\Desktop\bug\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill.track.dill
[  +10 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree C:\Users\Matan\Desktop\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +10 ms] Exit code 0 from: C:\Users\Matan\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree C:\Users\Matan\Desktop\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: application (line=17)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=36)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=46)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=50)
                     E: action (line=51)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=53)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=60)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +5 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe -s N9Q7N16929003861 shell -x logcat -v time -t 1
[  +10 ms] <- compile package:bug/main.dart
[  +81 ms] int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

           Note: log switch off, only log_main and log_events will have logs!
           --------- beginning of main
           04-12 03:02:46.778 I/MQoS    ( 1178): QOS_level:0(0),DataDisable;use level-0
[  +11 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +14 ms] Android Debug Bridge version 1.0.41
           Version 30.0.5-6877874
           Installed as C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +1 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +13 ms] Building APK
[  +15 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from C:\Users\Matan\Desktop\bug\android\gradlew.bat.
[   +1 ms] C:\Users\Matan\Desktop\bug\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +3 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +93 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +1 ms] executing: [C:\Users\Matan\Desktop\bug\android/] C:\Users\Matan\Desktop\bug\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=C:\Users\Matan\Desktop\bug\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1085 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :connectivity:preBuild UP-TO-DATE
[        ] > Task :connectivity:preDebugBuild UP-TO-DATE
[        ] > Task :connectivity:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :connectivity:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :connectivity:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :connectivity:mergeDebugShaders UP-TO-DATE
[        ] > Task :connectivity:compileDebugShaders NO-SOURCE
[        ] > Task :connectivity:generateDebugAssets UP-TO-DATE
[        ] > Task :connectivity:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +280 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :connectivity:compileDebugRenderscript NO-SOURCE
[        ] > Task :connectivity:generateDebugResValues UP-TO-DATE
[        ] > Task :connectivity:generateDebugResources UP-TO-DATE
[        ] > Task :connectivity:packageDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :connectivity:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :connectivity:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :connectivity:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :connectivity:parseDebugLocalResources UP-TO-DATE
[        ] > Task :connectivity:generateDebugRFile UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :connectivity:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :connectivity:javaPreCompileDebug UP-TO-DATE
[        ] > Task :connectivity:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :connectivity:bundleLibCompileToJarDebug UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :connectivity:processDebugJavaRes NO-SOURCE
[        ] > Task :connectivity:bundleLibResDebug NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :connectivity:bundleLibRuntimeToJarDebug UP-TO-DATE
[  +94 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[   +1 ms] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :connectivity:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :connectivity:mergeDebugNativeLibs NO-SOURCE
[        ] > Task :connectivity:stripDebugDebugSymbols NO-SOURCE
[        ] > Task :connectivity:copyDebugJniLibsProjectOnly UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[  +78 ms] > Task :app:assembleDebug
[   +1 ms] > Task :connectivity:copyDebugJniLibsProjectAndLocalJars UP-TO-DATE
[        ] > Task :connectivity:extractDebugAnnotations UP-TO-DATE
[        ] > Task :connectivity:mergeDebugGeneratedProguardFiles UP-TO-DATE
[        ] > Task :connectivity:mergeDebugConsumerProguardFiles UP-TO-DATE
[        ] > Task :connectivity:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :connectivity:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :connectivity:syncDebugLibJars UP-TO-DATE
[        ] > Task :connectivity:bundleDebugAar UP-TO-DATE
[        ] > Task :connectivity:compileDebugSources UP-TO-DATE
[        ] > Task :connectivity:assembleDebug UP-TO-DATE
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 1s
[        ] 57 actionable tasks: 4 executed, 53 up-to-date
[ +637 ms] Running Gradle task 'assembleDebug'... (completed in 2,307ms)
[  +35 ms] calculateSha: LocalDirectory: 'C:\Users\Matan\Desktop\bug\build\app\outputs\flutter-apk'/app.apk
[  +28 ms] calculateSha: reading file took 27us
[ +495 ms] calculateSha: computing sha took 494us
[   +5 ms] √ Built build\app\outputs\flutter-apk\app-debug.apk.
[   +4 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree C:\Users\Matan\Desktop\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +12 ms] Exit code 0 from: C:\Users\Matan\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree C:\Users\Matan\Desktop\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: application (line=17)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=22)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=36)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=46)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=50)
                     E: action (line=51)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=53)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=60)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +2 ms] Stopping app 'app.apk' on VIE L09.
[        ] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe -s N9Q7N16929003861 shell am force-stop com.example.bug
[ +471 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe -s N9Q7N16929003861 shell pm list packages com.example.bug
[ +356 ms] package:com.example.bug
[   +5 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe -s N9Q7N16929003861 shell cat /data/local/tmp/sky.com.example.bug.sha1
[  +20 ms] 1e1e828a8ffc1f29f7e9a8b7356659a6cd997a70
[   +1 ms] Latest build already installed.
[        ] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe -s N9Q7N16929003861 shell -x logcat -v time -t 1
[  +31 ms] int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

           Note: log switch off, only log_main and log_events will have logs!
           --------- beginning of main
           04-12 03:02:50.586 W/MessageQueue( 1082): Handler (android.os.Handler) {65b0124} sending message to a Handler on a dead thread
           04-12 03:02:50.586 W/MessageQueue( 1082): java.lang.IllegalStateException: Handler (android.os.Handler) {65b0124} sending message to a Handler on a dead thread
           04-12 03:02:50.586 W/MessageQueue( 1082):    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:616)
           04-12 03:02:50.586 W/MessageQueue( 1082):    at android.os.Handler.enqueueMessage(Handler.java:653)
           04-12 03:02:50.586 W/MessageQueue( 1082):    at android.os.Handler.sendMessageAtTime(Handler.java:622)
           04-12 03:02:50.586 W/MessageQueue( 1082):    at android.os.Handler.sendMessageDelayed(Handler.java:592)
           04-12 03:02:50.586 W/MessageQueue( 1082):    at android.os.Handler.post(Handler.java:345)
           04-12 03:02:50.586 W/MessageQueue( 1082):    at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
           04-12 03:02:50.586 W/MessageQueue( 1082):    at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
           04-12 03:02:50.586 W/MessageQueue( 1082):    at android.os.Binder.execTransact(Binder.java:565)
[   +6 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe -s N9Q7N16929003861 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true
--ez verify-entry-points true com.example.bug/com.example.bug.MainActivity
[ +352 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +303 ms] Observatory URL on device: http://127.0.0.1:59202/8mOR7OXmxV4=/
[   +1 ms] executing: C:\Users\Matan\AppData\Local\Android\sdk\platform-tools\adb.exe -s N9Q7N16929003861 forward tcp:0 tcp:59202
[  +14 ms] 62869
[        ] Forwarded host port 62869 to device port 59202 for Observatory
[   +3 ms] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:62869/8mOR7OXmxV4=/
[ +253 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:62869/8mOR7OXmxV4=/.
[  +89 ms] DDS is listening at http://127.0.0.1:62874/kb1-mkuM_Jk=/.
[  +38 ms] Successfully connected to service protocol: http://127.0.0.1:62869/8mOR7OXmxV4=/
[ +578 ms] DevFS: Creating new filesystem on the device (null)
[  +30 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugIURBHN/bug/)
[   +3 ms] Updating assets
[  +63 ms] Syncing files to device VIE L09...
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:bug/main.dart 8af5be41-e778-4a0c-8d5b-88d4d4f6b5c5
[        ] <- 8af5be41-e778-4a0c-8d5b-88d4d4f6b5c5
[ +107 ms] Updating files.
[   +1 ms] DevFS: Sync finished
[        ] Syncing files to device VIE L09... (completed in 114ms)
[        ] Synced 0.0MB.
[        ] <- accept
[  +12 ms] Connected to _flutterView/0x7c177ce820.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 
[        ] R Hot restart.
[   +1 ms] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on VIE L09 is available at: http://127.0.0.1:62874/kb1-mkuM_Jk=/
[        ]
           Flutter DevTools, a Flutter debugger and profiler, on VIE L09 is available at: http://127.0.0.1:9105?uri=http%3A%2F%2F127.0.0.1%3A62874%2Fkb1-mkuM_Jk%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[ +302 ms] I/flutter ( 1116): ConnectivityResult.wifi
[+4054 ms] I/flutter ( 1116): ConnectivityResult.wifi
[+6745 ms] I/flutter ( 1116): ConnectivityResult.wifi


```

```

Analyzing bug...
No issues found! (ran in 1.4s)

```

```

[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale en-IL)
    • Flutter version 2.0.4 at C:\tools\flutter
    • Framework revision b1395592de (10 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Matan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Matan\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • VIE L09 (mobile) • N9Q7N16929003861 • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 89.0.774.75

• No issues found!

```

</details>

**Comment by matancohen365** [comment]
Seems like android bug , not flutter.
