### ISSUE TITLE
Unable to build ios-framework for plugins which has no simulator arch support !!

### ISSUE THREAD

**Issue by chandarlee** [flutter/flutter#80274]
In add-to-app with ios, flutter build ios-framework always builds for iphonesimulator , but one of my flutter plugin does not support this arch and cause the following error,  how can I fix it ? Can flutter tool skip building for iphonesimulator arch?

```console
[   +2 ms]  ├─Building plugins... (completed in 39.3s)
[        ] "flutter ios-framework" took 49,280ms.
[   +5 ms] Unable to create foo.xcframework: error: unable to read the file at 'flutter_module/build/ios/framework/Debug/iphonesimulator/Debug-iphonesimulator/foo/foo.framework/foo'

[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      BuildIOSFrameworkCommand._produceXCFramework (package:flutter_tools/src/commands/build_ios_framework.dart:539:7)
           <asynchronous suspension>
           #2      BuildIOSFrameworkCommand._producePlugins (package:flutter_tools/src/commands/build_ios_framework.dart:508:11)
           <asynchronous suspension>
           #3      BuildIOSFrameworkCommand.runCommand (package:flutter_tools/src/commands/build_ios_framework.dart:208:9)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #14     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #16     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #17     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #18     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

**Comment by TahaTesser** [comment]
HI @chandarlee 
You can try modifying the plugin's Podspec file, might have to use the plugin locally with modified Podspec, Just file an issue on p;ugin's repository.
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by chandarlee** [comment]
I think this should be the problem of Flutter tools！Declare the valid arch in plugin Podspec file is useless. Flutter build frameworks for iphone simulator arch by default. It should provides build options to disable/enable building for archs，rather than enable always and let developers to fix it themselves. It is the common case where some Frameworks do not have simulator arch support!

**Comment by TahaTesser** [comment]
@chandarlee 
Each Flutter package defines its own architecture, it's not done by Futter

**Comment by chandarlee** [comment]
@TahaTesser 
As you say, 'Each Flutter package defines its own architecture, it's not done by Futter', that is right. The problem is that if iphonesimulator is exclude from one package's valid architectures, flutter build ios-framework CLI will fail because flutter try to generate framework for iphonesimulator architecture by default. As developer, I just need the ios architecture frameworks, I dont care iphonesimulator releated frameworks.
