### ISSUE TITLE
Two scrollable_fling_test.dart fail on OS X

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#8030]
```
$ flutter test test/widgets/scrollable_fling_test.dart
00:02 +1: - fling and tap to stop                                                                  
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: ['tap 18']
  Actual: ['tap 21']
   Which: was 'tap 21' instead of 'tap 18' at location [0]


When the exception was thrown, this was the stack:
#3      main.<anonymous closure>.<<anonymous closure>_async_body> (///Users/abarth/git/flutter/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart:63:5)
#17     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:563:16)
#18     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:394:5)
#19     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:549:24)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:547:16)
#26     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:54:50)
#27     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:106:19)
#39     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:183:3)
(elided 65 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)

This was caught by the test expectation on the following line:
  ///Users/abarth/git/flutter/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart line
  63


════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +1 -1: - fling and tap to stop                                                               
  Test failed. See exception logs above.
  
00:02 +1 -1: - fling and wait and tap                                                              
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: ['tap 18']
  Actual: ['tap 21']
   Which: was 'tap 21' instead of 'tap 18' at location [0]


When the exception was thrown, this was the stack:
#3      main.<anonymous closure>.<<anonymous closure>_async_body> (///Users/abarth/git/flutter/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart:86:5)
#17     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:563:16)
#18     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:394:5)
#19     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:549:24)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:547:16)
#26     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:54:50)
#27     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:106:19)
#39     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:183:3)
(elided 65 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)

This was caught by the test expectation on the following line:
  ///Users/abarth/git/flutter/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart line
  86


════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +1 -2: - fling and wait and tap                                                              
  Test failed. See exception logs above.
  
00:02 +1 -2: Some tests failed.                                                                    
```

**Comment by goderbauer** [comment]
The test is running fine on MacOS now. Closing.
