### ISSUE TITLE
Get html error in Android

### ISSUE THREAD

**Issue by tanh-miichi** [flutter/flutter#80328]
webview_flutter: ^ 2.0.4

**[Android]** 
When I use WebViewController to get html through String html = await _controller.evaluateJavascript (
         "window.document.getElementsByTagName ('html') [0] .outerHTML;");
The value in the other html is incomplete, it only contains part of the html of the page. I do not know why?
I have tried quite a few devices and the different websites fail?
And I can't parser string html to Document in html library?
 **[IOS]** 
Everything works fine, still fetching full html.

**Comment by TahaTesser** [comment]
Hi @tanh-miichi 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by tanh-miichi** [comment]
Hi @TahaTesser 
Thank you for reply, below is what you asked for
### 1. flutter doctor -v

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.294, on macOS 11.0.1 20B29
    darwin-x64, locale en)
    • Flutter version 2.1.0-13.0.pre.294 at
      /Users/openyoureyes/FlutterSDK/flutter
    • Framework revision a603714610 (2 weeks ago), 2021-03-28 03:54:02 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/openyoureyes/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 8.0.0 (API 26) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 89.0.4389.114
    ! Error: OpenYourEyes is not connected. Xcode will continue when OpenYourEyes is connected. (code -13)

! Doctor found issues in 1 category.
```
### 2. Code sample
```
class _RegisterState extends BaseState<RegisterScreen, RegisterBloc> {
  WebViewController _controller;

  @override
  String titleScreen() {
    return "Register";
  }

  @override
  void onListenerStream() {
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget createBodyWidget() {
    return Builder(builder: (BuildContext context) {
      return WebView(
        initialUrl: 'https://google.com',
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) {
          _controller = webViewController;
        },
        onPageStarted: (String url) {
          showLoading();
        },
        onPageFinished: (String url) {
          hideLoading();
          _parserHtml();
        },
        gestureNavigationEnabled: true,
      );
    });
  }

  void _parserHtml() async{
    String html = await _controller.evaluateJavascript(
        "window.document.getElementsByTagName('html')[0].outerHTML;");
    printLog("html $html");
  }
```
### 3. flutter run --verbose
```
[  +57 ms] I/flutter ( 8661): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[        ] I/flutter ( 8661): │ #0   printLog (package:face_image/utils/string_extenstion.dart:27:10)
[        ] I/flutter ( 8661): │ #1   _RegisterState._parserHtml (package:face_image/ui/register/register.dart:58:5)
[        ] I/flutter ( 8661): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[        ] I/flutter ( 8661): │ 🐛 Mii - [2021-04-13 18:18:30] [main] => html "\u003Chtml lang=\"vi\">\u003Chead>\u003Cmeta charset=\"UTF-8\">\u003Cmeta content=\"width=device-width,minimum-scale=1.0\"
name=\"viewport\">\u003Cmeta content=\"telephone=no\" name=\"format-detection\">\u003Cmeta content=\"address=no\" name=\"format-detection\">\u003Cmeta content=\"origin\" name=\"referrer\">\u003Cmeta
content=\"notranslate\" name=\"google\">\u003Clink href=\"/images/branding/product/1x/gsa_android_144dp.png\" rel=\"icon\">\u003Cmeta content=\"/images/branding/googleg/1x/googleg_standard_color_128dp.png\"
itemprop=\"image\">\u003Clink href=\"/manifest?pwa=webhp\" crossorigin=\"use-credentials\" rel=\"manifest\">\u003Cstyle data-iml=\"1618312708895\">@font-face{font-family:'Google
Sans';font-style:normal;font-weight:400;src:local('Google Sans
Regular'),local('GoogleSans-Regular'),url(//fonts.gstatic.com/s/googlesans/v14/4UaGrENHsxJlGDuGo1OIlL3Kwp5eKQtGBlc.woff2)format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116;}@font
[  +10 ms] I/flutter ( 8661): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by TahaTesser** [comment]
Hi @tanh-miichi 
Thanks for the code sample, here I made it into a runnable code sample

<details> 
<summary>code sample</summary> 

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  WebViewController _controller;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  void _parserHtml() async {
    String html = await _controller.evaluateJavascript(
        "window.document.getElementsByTagName('html')[0].outerHTML;");
    print("html $html");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: WebView(
        initialUrl: 'https://google.com',
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) {
          _controller = webViewController;
        },
        onPageStarted: (String url) {},
        onPageFinished: (String url) {
          _parserHtml();
        },
        gestureNavigationEnabled: true,
      ),
    );
  }
}

``` 

</details>

### Android
```console
[   +7 ms] W/Gralloc4(26363): allocator 3.x is not supported
[+1527 ms] I/flutter (26363): html "\u003Chtml lang=\"et\">\u003Chead>\u003Cmeta charset=\"UTF-8\">\u003Cmeta
content=\"width=device-width,minimum-scale=1.0\" name=\"viewport\">\u003Cmeta content=\"telephone=no\"
name=\"format-detection\">\u003Cmeta content=\"address=no\" name=\"format-detection\">\u003Cmeta content=\"origin\"
name=\"referrer\">\u003Cmeta content=\"notranslate\" name=\"google\">\u003Clink
href=\"/images/branding/product/1x/gsa_android_144dp.png\" rel=\"icon\">\u003Cmeta
content=\"/images/branding/googleg/1x/googleg_standard_color_128dp.png\" itemprop=\"image\">\u003Clink
href=\"/manifest?pwa=webhp\" crossorigin=\"use-credentials\" rel=\"manifest\">\u003Cstyle
data-iml=\"1618383558702\">@font-face{font-family:'Google
Sans';font-style:normal;font-weight:400;font-display:optional;src:local('Google Sans
Regular'),local('GoogleSans-Regular'),url(//fonts.gstatic.com/s/googlesans/v14/4UaGrENHsxJlGDuGo1OIlL3Kwp5eKQtGBlc.woff2
)format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116;}@font-face{font-family:'Google
[+1842 ms] I/flutter (26363): html "\u003Chtml lang=\"et\">\u003Chead>\u003Cmeta charset=\"UTF-8\">\u003Cmeta
content=\"width=device-width,minimum-scale=1.0\" name=\"viewport\">\u003Cmeta content=\"telephone=no\"
name=\"format-detection\">\u003Cmeta content=\"address=no\" name=\"format-detection\">\u003Cmeta content=\"origin\"
name=\"referrer\">\u003Cmeta content=\"notranslate\" name=\"google\">\u003Clink
href=\"/images/branding/product/1x/gsa_android_144dp.png\" rel=\"icon\">\u003Cmeta
content=\"/images/branding/googleg/1x/googleg_standard_color_128dp.png\" itemprop=\"image\">\u003Clink
href=\"/manifest?pwa=webhp\" crossorigin=\"use-credentials\" rel=\"manifest\">\u003Cstyle
data-iml=\"1618383558702\">@font-face{font-family:'Google
Sans';font-style:normal;font-weight:400;font-display:optional;src:local('Google Sans
Regular'),local('GoogleSans-Regular'),url(//fonts.gstatic.com/s/googlesans/v14/4UaGrENHsxJlGDuGo1OIlL3Kwp5eKQtGBlc.woff2
)format('woff2');unicode-range:U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116;}@font-face{font-family:'Google
[+175062 ms] F/crash_dump32(26524): crash_dump.cpp:474] failed to attach to thread 178: Permission denied
```

### iOS
```console
https://dart.dev/null-safety/unsound-null-safety
[ +820 ms] flutter: html <html lang="et" style="cursor: pointer;"><head><meta
charset="UTF-8"><meta content="width=device-width,initial-scale=1.0"
name="viewport"><meta content="telephone=no" name="format-detection"><meta
content="address=no" name="format-detection"><meta content="origin"
name="referrer"><link href="/images/branding/product_ios/3x/gsa_ios_60dp.png"
rel="apple-touch-icon" sizes="180x180"><link
href="/images/branding/product_ios/2x/gsa_ios_60dp.png" rel="apple-touch-icon"
sizes="120x120"><link href="/images/branding/product_ios/2x/gsa_ios_57dp.png"
rel="apple-touch-icon" sizes="114x114"><link
href="/images/branding/product_ios/1x/gsa_ios_57dp.png"
rel="apple-touch-icon"><meta
content="/images/branding/googleg/1x/googleg_standard_color_128dp.png"
itemprop="image"><link href="/manifest?pwa=webhp" crossorigin="use-credentials"
rel="manifest"><title>Google</title><script
src="https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.RrjSsKk8Szw.O/
m=gapi_iframes,googleapis_client/rt=j/sv=1/d=<…>
```


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b1395592de (12 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0
⣻[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 83060656-28E7-44CD-801E-B11EC3EC89BA • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 89.0.4389.114
• No issues found! 
```
	
</details>


@tanh-miichi 
Can you please confirm you see the same logs on iOS?

**Comment by tanh-miichi** [comment]
Hi @TahaTesser 
IOS side shows all html content including opening and closing <html> </html> tag, it's too long for me to show up here. But for Android, it doesn't display like the iOS side.
Why is Android showing unicode \ u003C in html?
Is this the cause of not displaying all html on Android?

**Comment by TahaTesser** [comment]
Hi @tanh-miichi 
I still see limited logs, can you please provide code for `printLog` (I'm just using `print()` and it doesn't print complete logs https://github.com/flutter/flutter/issues/80328#issuecomment-819283190)?

**Comment by tanh-miichi** [comment]
Hi @TahaTesser 
I detect if debug and check html variable, it contains full html
This is class container func printLog

```
import 'dart:isolate';

import 'package:intl/intl.dart';
import 'package:logger/logger.dart';

final DateFormat formatter = DateFormat('yyyy-MM-dd HH:mm:ss');
final Logger logger = Logger(
  printer: PrettyPrinter(
      methodCount: 2,
      // number of method calls to be displayed
      errorMethodCount: 8,
      // number of method calls if stacktrace is provided
      lineLength: 120,
      // width of the output
      colors: true,
      // Colorful log messages
      printEmojis: true,
      // Print an emoji for each log message
      printTime: false // Should each log print contain a timestamp
      ),
);

void printLog(Object message) {
  final DateTime now = DateTime.now();
  String formatted = formatter.format(now);
  logger.d('[$formatted] [${Isolate.current.debugName}] => $message');
}
```

**Comment by TahaTesser** [comment]
@tanh-miichi 
Here is the complete reproducible code sample, I can reproduce the difference 
<details> 
<summary>complete runnable code sample</summary> 

```dart
import 'dart:io';

import 'dart:isolate';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:intl/intl.dart';
import 'package:logger/logger.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  WebViewController _controller;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  void _parserHtml() async {
    String html = await _controller.evaluateJavascript(
        "window.document.getElementsByTagName('html')[0].outerHTML;");
    printLog("html $html");
  }

  final DateFormat formatter = DateFormat('yyyy-MM-dd HH:mm:ss');
  final Logger logger = Logger(
    printer: PrettyPrinter(
        methodCount: 2,
        // number of method calls to be displayed
        errorMethodCount: 8,
        // number of method calls if stacktrace is provided
        lineLength: 120,
        // width of the output
        colors: true,
        // Colorful log messages
        printEmojis: true,
        // Print an emoji for each log message
        printTime: false // Should each log print contain a timestamp
        ),
  );

  void printLog(Object message) {
    final DateTime now = DateTime.now();
    String formatted = formatter.format(now);
    logger.d('[$formatted] [${Isolate.current.debugName}] => $message');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: WebView(
        initialUrl: 'https://google.com',
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) {
          _controller = webViewController;
        },
        onPageStarted: (String url) {},
        onPageFinished: (String url) {
          _parserHtml();
        },
        gestureNavigationEnabled: true,
      ),
    );
  }
}

``` 

</details>

**Comment by zezo357** [comment]
so how to avoid the problem on android? I need the HTML like the one in ios to be able to parse it

**Comment by robert-virkus** [comment]
In my HTML editor project https://github.com/enough-Software/enough_html_editor I use the following code:
```dart
  final innerHtml = await _webViewController.runJavascriptReturningResult(
      'document.getElementById("editor").innerHTML;');
  return innerHtml
      .replaceAll(r'\u003C', '<')
      .replaceAll(r'\n', '\n')
      .replaceAll(r'\"', '&quot;');
```

But it's very likely, that I didn't get all cases.

**Comment by ycherniavskyi** [comment]
After some digging, as I understand, such a strange string returned exactly from Android WebView - it looks like some protecting/escaping, but not very clear from what exactly 🤷🏻‍♂️.

My solution for this strange string is the next extension:
```dart
import 'dart:convert';

import 'package:webview_flutter/webview_flutter.dart';
import 'package:webview_flutter_android/webview_flutter_android.dart';

extension WebViewControllerExtension on WebViewController {
  Future<String> getHtml() {
    return runJavaScriptReturningResult('document.documentElement.outerHTML').then((value) {
      if (platform is AndroidWebViewController) {
        return jsonDecode(value as String) as String;
      } else {
        return value as String;
      }
    });
  }
}
```

**Comment by swarajkumarsingh** [comment]
# The Solution 💕

## The Problem:
1. Don't know why but webview plugin just encodes the html and returns in a weird format, the reason for this is still a mystery.

## The Solution:
1. If the WebView is in Android the plugin just encodes it. so will jsonDecode the html, and this should do the job, the full code is below.

## Solution Code:
- Here we are adding an extension function to the webViewController, which jsonDecodes the html, only if it is in Android and returns it.

```
import 'dart:io';
import 'dart:convert';

import 'package:webview_flutter/webview_flutter.dart';

extension WebViewControllerExtension on WebViewController {
  Future<String> getHtml() {
    return runJavaScriptReturningResult('document.documentElement.outerHTML')
        .then((value) {
      if (Platform.isAndroid) {
        return jsonDecode(value as String) as String;
      } else {
        return value as String;
      }
    });
  }
}

```

Thank you.
Swaraj Kumar Singh.

**Comment by swarajkumarsingh** [comment]
> In my HTML editor project https://github.com/enough-Software/enough_html_editor I use the following code:
> 
> ```dart
>   Future<String> getText() async {
>     final innerHtml = await _webViewController.runJavascriptReturningResult(
>         'document.getElementById("editor").innerHTML;');
>     if (defaultTargetPlatform == TargetPlatform.android) {
>       // compare https://github.com/flutter/flutter/issues/80328
>       final cleanedHtml = innerHtml
>           .replaceAll(r'\u003C', '<')
>           .replaceAll(r'\n', '\n')
>           .replaceAll(r'\"', '&quot;');
>       if (cleanedHtml.startsWith('"') && cleanedHtml.endsWith('"')) {
>         final stripped =
>             cleanedHtml.substring(1, cleanedHtml.length - 1).trim();
>         return stripped;
>       }
>       return cleanedHtml;
>     }
>     return innerHtml;
>   }
> ```
> 
> But it's very likely, that I didn't get all cases.

# The Perfect Solution 💕

## The Problem:
1. Don't know why but webview plugin just encodes the html and returns in a weird format, the reason for this is still a mystery.

## The Solution:
1. If the WebView is in Android the plugin just encodes it. so will jsonDecode the html, and this should do the job, the full code is below.

## Solution Code:
- Here we are adding an extension function to the webViewController, which jsonDecodes the html, only if it is in Android and returns it.

```
import 'dart:io';
import 'dart:convert';

import 'package:webview_flutter/webview_flutter.dart';

extension WebViewControllerExtension on WebViewController {
  Future<String> getHtml() {
    return runJavaScriptReturningResult('document.documentElement.outerHTML')
        .then((value) {
      if (Platform.isAndroid) {
        return jsonDecode(value as String) as String;
      } else {
        return value as String;
      }
    });
  }
}

```

Thank you.
Swaraj Kumar Singh.

**Comment by swarajkumarsingh** [comment]
> 


> In my HTML editor project https://github.com/enough-Software/enough_html_editor I use the following code:
> 
> ```dart
>   Future<String> getText() async {
>     final innerHtml = await _webViewController.runJavascriptReturningResult(
>         'document.getElementById("editor").innerHTML;');
>     if (defaultTargetPlatform == TargetPlatform.android) {
>       // compare https://github.com/flutter/flutter/issues/80328
>       final cleanedHtml = innerHtml
>           .replaceAll(r'\u003C', '<')
>           .replaceAll(r'\n', '\n')
>           .replaceAll(r'\"', '&quot;');
>       if (cleanedHtml.startsWith('"') && cleanedHtml.endsWith('"')) {
>         final stripped =
>             cleanedHtml.substring(1, cleanedHtml.length - 1).trim();
>         return stripped;
>       }
>       return cleanedHtml;
>     }
>     return innerHtml;
>   }
> ```
> 
> But it's very likely, that I didn't get all cases.

# The Perfect Solution 💕

## The Problem:
1. Don't know why but webview plugin just encodes the html and returns in a weird format, the reason for this is still a mystery.

## The Solution:
1. If the WebView is in Android the plugin just encodes it. so will jsonDecode the html, and this should do the job, the full code is below.

## Solution Code:
- Here we are adding an extension function to the webViewController, which jsonDecodes the html, only if it is in Android and returns it.

```
import 'dart:io';
import 'dart:convert';

import 'package:webview_flutter/webview_flutter.dart';

extension WebViewControllerExtension on WebViewController {
  Future<String> getHtml() {
    return runJavaScriptReturningResult('document.documentElement.outerHTML')
        .then((value) {
      if (Platform.isAndroid) {
        return jsonDecode(value as String) as String;
      } else {
        return value as String;
      }
    });
  }
}

```

Thank you.
Swaraj Kumar Singh.

**Comment by swarajkumarsingh** [comment]
> 



> webview_flutter: ^ 2.0.4
> 
> **[Android]** When I use WebViewController to get html through String html = await _controller.evaluateJavascript ( "window.document.getElementsByTagName ('html') [0] .outerHTML;"); The value in the other html is incomplete, it only contains part of the html of the page. I do not know why? I have tried quite a few devices and the different websites fail? And I can't parser string html to Document in html library? **[IOS]** Everything works fine, still fetching full html.

# The Perfect Solution 💕

## The Problem:
1. Don't know why but webview plugin just encodes the html and returns in a weird format, the reason for this is still a mystery.

## The Solution:
1. If the WebView is in Android the plugin just encodes it. so will jsonDecode the html, and this should do the job, the full code is below.

## Solution Code:
- Here we are adding an extension function to the webViewController, which jsonDecodes the html, only if it is in Android and returns it.

```
import 'dart:io';
import 'dart:convert';

import 'package:webview_flutter/webview_flutter.dart';

extension WebViewControllerExtension on WebViewController {
  Future<String> getHtml() {
    return runJavaScriptReturningResult('document.documentElement.outerHTML')
        .then((value) {
      if (Platform.isAndroid) {
        return jsonDecode(value as String) as String;
      } else {
        return value as String;
      }
    });
  }
}

```

Thank you.
Swaraj Kumar Singh.

**Comment by CaviarChen** [comment]
Any update on fixing this? The behavior difference between ios/android is very annoying and weird.
