### ISSUE TITLE
[google_maps_flutter] Unhandled Exception: NoSuchMethodError: The getter 'mapsId' was called on null.

### ISSUE THREAD

**Issue by neoacevedo** [flutter/flutter#80381]
On re-launching recovering from a previous app closing, I am getting the following error:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()
The relevant error-causing widget was
GoogleMap
package:tuttocol_app_conductor/pages/job.dart:1183
════════════════════════════════════════════════════════════════════════════════
E/flutter (24093): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'mapsId' was called on null.
E/flutter (24093): Receiver: null
E/flutter (24093): Tried calling: mapsId
```
I sumarize: In the map, I have 3 markers. I do an app close/restart for simulating some events outside the app (OS restarting). I have stored in the preferences and in local db the markers positions, and also the time lapsed. When the app is re-launched, this issue appears and the map isn't rendered (in debug mode, the map is replaced by the error text in red background). This same code works perfect in Android Java, but in Flutter I get the problem.

<details>
<summary>JSON error</summary>

```
{
  "description": "Exception caught by widgets library",
  "type": "_FlutterErrorDetailsNode",
  "allowWrap": false,
  "objectId": "inspector-60",
  "valueId": "inspector-61",
  "properties": [
    {
      "description": "The following NoSuchMethodError was thrown building GoogleMap(dirty, state: _GoogleMapState#9a974):",
      "type": "ErrorDescription",
      "showSeparator": false,
      "showName": false,
      "style": "flat",
      "allowNameWrap": true,
      "objectId": "inspector-62",
      "valueId": "inspector-63",
      "properties": [],
      "children": [],
      "defaultValue": "null",
      "missingIfNull": false,
      "propertyType": "List<Object>",
      "defaultLevel": "info"
    },
    {
      "description": "The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()",
      "type": "ErrorSummary",
      "showSeparator": false,
      "level": "summary",
      "showName": false,
      "style": "flat",
      "allowNameWrap": true,
      "objectId": "inspector-64",
      "valueId": "inspector-65",
      "properties": [],
      "children": [],
      "defaultValue": "null",
      "missingIfNull": false,
      "propertyType": "List<Object>",
      "defaultLevel": "summary"
    },
    {
      "description": "",
      "type": "ErrorSpacer",
      "name": "",
      "showName": false,
      "style": "singleLine",
      "allowNameWrap": true,
      "objectId": "inspector-66",
      "valueId": null,
      "properties": [],
      "children": [],
      "missingIfNull": false,
      "propertyType": "void",
      "defaultLevel": "info",
      "value": null
    },
    {
      "description": null,
      "type": "DiagnosticsBlock",
      "name": "The relevant error-causing widget was",
      "style": "whitespace",
      "hasChildren": true,
      "allowWrap": false,
      "objectId": "inspector-67",
      "valueId": null,
      "properties": [],
      "children": [
        {
          "description": "GoogleMap file:///home/nestor/Flutter/myapp/lib/pages/job.dart:1183:30",
          "type": "ErrorDescription",
          "showSeparator": false,
          "showName": false,
          "style": "flat",
          "allowNameWrap": true,
          "objectId": "inspector-68",
          "valueId": "inspector-69",
          "properties": [],
          "children": [],
          "defaultValue": "null",
          "missingIfNull": false,
          "propertyType": "List<Object>",
          "defaultLevel": "info"
        }
      ]
    },
    {
      "description": "",
      "type": "ErrorSpacer",
      "name": "",
      "showName": false,
      "style": "singleLine",
      "allowNameWrap": true,
      "objectId": "inspector-70",
      "valueId": null,
      "properties": [],
      "children": [],
      "missingIfNull": false,
      "propertyType": "void",
      "defaultLevel": "info",
      "value": null
    },
    {
      "description": null,
      "type": "DiagnosticsStackTrace",
      "name": "When the exception was thrown, this was the stack",
      "style": "flat",
      "allowTruncate": true,
      "allowWrap": false,
      "objectId": "inspector-71",
      "valueId": "inspector-72",
      "properties": [
        {
          "description": "#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-73",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "#1      serializeMapsObjectSet.<anonymous closure> (package:google_maps_flutter_platform_interface/src/types/utils/maps_object.dart:17:54)",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-74",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "#2      MappedIterator.moveNext (dart:_internal/iterable.dart:389:20)",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-75",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-76",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-77",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "...",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowNameWrap": true,
          "objectId": "inspector-78",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null,
          "truncated": true
        }
      ],
      "children": []
    },
    {
      "description": "",
      "type": "ErrorSpacer",
      "name": "",
      "showName": false,
      "style": "singleLine",
      "allowNameWrap": true,
      "objectId": "inspector-79",
      "valueId": null,
      "properties": [],
      "children": [],
      "missingIfNull": false,
      "propertyType": "void",
      "defaultLevel": "info",
      "value": null
    }
  ],
  "children": [],
  "errorsSinceReload": 3,
  "renderedErrorText": "Another exception was thrown: NoSuchMethodError: The method 'toJson' was called on null."
}
```
</details>

**Comment by darshankawar** [comment]
@neoacevedo 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this issue ?
Thanks.

**Comment by neoacevedo** [comment]
Forget it, I found the issue, it's my mistake, I will close this issue.

**Comment by ealong** [comment]
@neoacevedo Echoing sagar^: please let us know what you did to fix this issue so that others like myself can resolve it as well! Thanks.
