### ISSUE TITLE
FutureBuilder not recognising  Future<JsonMap>

### ISSUE THREAD

**Issue by starzar** [flutter/flutter#80417]
On trying to pass a Future-Map (decoded from a JsonMap) to the Future Builder widget , it gives the error below.

`ERROR: Expected a value of type 'Future<Map<dynamic, dynamic>>?', but got one of type '_JsonMap'`

The JsonMap has been cast to a Future-Map using the `cast-as operator ` ,mapped to a normal Map and then this normal Map has been returned using` Future.value()`,but the  error still persists.  

<summary>Code:</summary>
<details>
```

      import 'dart:convert';
      import 'package:flutter/material.dart';
      void main() => runApp(MyApp());
      
      class MyApp extends StatelessWidget {
        @override
        Widget build(BuildContext context) {
      
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'Future - JsonMap not recognised by FutureBuilder',
            theme: ThemeData.dark(),
      
            home: Scaffold(
      
      
              appBar: AppBar(
                title: Text(
                  'Future - JsonMap not recognised by FutureBuilder',
                  style: TextStyle(),
                ),
              ),
              body: UserScreen1(),
              // body: UserScreen1( sessionDataScreen1 : _sessionDataMain ),
            ),
          );
        }
      }
      class UserScreen1 extends StatefulWidget {
        @override
        _UserScreen1State createState() => _UserScreen1State();
      }
      
      class _UserScreen1State extends State<UserScreen1> {
      
      
      
        var _mapGetJson;
      
      
        Future<Map<String, dynamic>> _getMap(_Json) async {

        var _map = await jsonDecode(_Json) as Future<Map<String, dynamic>>;
    
        Map<String, dynamic> _mapGetCopy;
        _map.then((_e){
          _mapGetCopy['name'] = _e["name"]; _mapGetCopy['age'] = _e["age"]; 
          return  Future.value(_mapGetCopy);
    
      });}
      
      
      
        void initState() {
        super.initState();
      
        var _jsonInitial = '''{
              "name" : "_mapGetJson",
              "age" : "20"
            }''';
      
        _mapGetJson = _getMap(_jsonInitial);
        _mapGetJson.then((_map) {
          print(
              '${_mapGetJson.runtimeType} _mapGet = $_map => ${_map['name']} , ${_map['age']}');
        });
      
        }
      
      
      
        @override
        Widget build(BuildContext context) {
        return Column(
        mainAxisAlignment: MainAxisAlignment.center ,
        children: [
        Container(child:FutureBuilder<Map>(
        future:  _mapGetJson,
        builder: (BuildContext context, AsyncSnapshot<Map> snapshot) {
        switch (snapshot.connectionState) {
        case ConnectionState.waiting:
        return const CircularProgressIndicator();
        default:
        if (snapshot.hasError) {
        return Text('Error: ${snapshot.error}');
        } else {
        // return  Text(' User (BuildContext) : name = ${snapshot.data.['name']}, age = ${snapshot.data['age']},subscribed = ${snapshot.data['subscribed']},');
        return  Text(' User (BuildContext) : nameMap = ${snapshot.data} ');
      
        }
        }
        })),
      
      
      
        ]
        );
        }}
```
</details>  
   

<summary>Stacktrace :</summary>
<details>
```
    Error: Expected a value of type 'Future<Map<String, dynamic>>', but got one of type '_JsonMap'
        at Object.throw_ [as throw] (http://localhost:63761/dart_sdk.js:5347:11)
        at Object.castError (http://localhost:63761/dart_sdk.js:5318:15)
        at Object.cast [as as] (http://localhost:63761/dart_sdk.js:5634:17)
        at dart.LegacyType.new.as (http://localhost:63761/dart_sdk.js:7232:60)
        at _getMap 
        (http://localhost:63761/packages/mental_math_unlimited/database/Sharedpreferences_IssueGithub.dart.lib.js:454:55)
        at _getMap.next (<anonymous>)
        at http://localhost:63761/dart_sdk.js:39167:33
        at _RootZone.runUnary (http://localhost:63761/dart_sdk.js:39024:58)
        at _FutureListener.thenAwait.handleValue (http://localhost:63761/dart_sdk.js:34010:29)
        at handleValueCallback (http://localhost:63761/dart_sdk.js:34570:49)
        at Function._propagateToListeners (http://localhost:63761/dart_sdk.js:34608:17)
        at async._AsyncCallbackEntry.new.callback (http://localhost:63761/dart_sdk.js:34326:27)
        at Object._microtaskLoop (http://localhost:63761/dart_sdk.js:39311:13)
        at _startMicrotaskLoop (http://localhost:63761/dart_sdk.js:39317:13)
        at http://localhost:63761/dart_sdk.js:34824:9
```

</details>  

<summary>Flutter Doctor :</summary>
<details>
```
      Doctor summary (to see all details, run flutter doctor -v):
      [√] Flutter (Channel dev, 2.1.0-10.0.pre, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
      [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
      [√] Chrome - develop for the web
      [X] Visual Studio - develop for Windows
          X Visual Studio not installed; this is necessary for Windows development.
            Download at https://visualstudio.microsoft.com/downloads/.
            Please install the "Desktop development with C++" workload, including all of its default components
      [√] Android Studio (version 4.1.0)
      [√] VS Code (version 1.55.1)
      [√] Connected device (3 available)
      
      ! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@starzar 
Is this on mobile or web ?

**Comment by starzar** [comment]
Both (Android)mobile and web.  

Android 
`Error : type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Future<Map<dynamic, dynamic>>?' `  

Web(Chrome)
`Error : Expected a value of type 'Future<Map<dynamic, dynamic>>?', but got one of type '_JsonMap'`

**Comment by darshankawar** [comment]
Thanks. I see the same behavior on both platforms.

Android
Error : type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Future<Map<dynamic, dynamic>>?'

Web(Chrome)
Error : Expected a value of type 'Future<Map<dynamic, dynamic>>?', but got one of type '_JsonMap'

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

Keeping this issue open for further insights.

**Comment by stuartmorgan** [comment]
This code is incorrect: `jsonDecode(_Json) as Future<Map<String, dynamic>>`

`jsonDecode` doesn't return a future, and you can't just cast an arbitrary object to a Future. The type error you are getting is giving you the correct information about why the code is wrong.

**Comment by starzar** [comment]
@darshankawar , @stuartmorgan  -Thanks for looking into the issue. 
The above code is part of a larger code, used to set and access locally stored data via SharedPreferences.
Since SharedPreferences return a Future Json ,it has to be decoded and sent as a Future-Map to the  Future Builder (which is not recognizing the Future-Map).

Additional Sample Code:

```
    Future<Map<String, dynamic>> _getSharedPreferences (_userDataKey)  async {
    
     // Set initial data if SharedPreferences not initialized
     var  _userJsonInitial = '''{
        "name" : "Mock",
         "age" : 20,
         "subscribed" : true}''';


      final prefs =   await SharedPreferences.getInstance();
    
      final rawJsonGet =  prefs.getString(_userDataKey) ?? _userJsonInitial;
      _mapGet = await jsonDecode(rawJsonGet) as Future<Map<String, dynamic>>;
      print('_mapGet = $_mapGet ');

      return Future.value(_mapGet);

   } 

FutureBuilder:
  // Error: Expected a value of type 'Future<Map<dynamic, dynamic>>', but got one of type '_JsonMap'
  future: _getSharedPreferences (_userDataKey) ,

```

**Comment by stuartmorgan** [comment]
> Since SharedPreferences return a Future Json

This statement is not correct. (And if it were, the code above would fail even earlier, because `jsonDecode` takes a `String`, not a `Future<String>`.)

I recommend adding explicit types to your local variable here to help you understand what the types are at each step. If you still have issues, try using a community resource like StackOverflow to get help with the code.
