### ISSUE TITLE
[tool_crash] ProcessException: The directory name is invalid. Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 267

### ISSUE THREAD

**Issue by Sarthak0810** [flutter/flutter#80418]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The directory name is invalid.
 Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 267
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:39:20)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:282:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:222:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/cache.dart:774:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
```
```
[✓] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.18362.239], locale en-US)
    • Flutter version 2.0.2 at C:\src\flutter
    • Framework revision 8962f6dc68 (5 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ADMIN\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    ✗ Android SDK file not found: C:\Users\ADMIN\AppData\Local\Android\sdk\platforms\android-30\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment]
Similar issues are reported but they are when executing `flutter create`
https://github.com/flutter/flutter/issues/78111
https://github.com/flutter/flutter/issues/72695

but this issue is when `flutter doctor`, which shouldn't crash

**Comment by jmagman** [comment]
Surprised we didn't have one open already.

**Comment by cloosli** [comment]
My solution was to install the dart sdk. I don't know why this is not mentioned in the installtion guide.
After I installed the dart sdk flutter doctor worked. So make sure you have dart.exe at the end of your path
$ where flutter dart
C:\opt\flutter\bin\flutter
C:\opt\flutter\bin\flutter.bat
C:\opt\flutter\bin\dart
C:\opt\flutter\bin\dart.bat
C:\opt\dart-sdk\bin\dart.exe

**Comment by jmagman** [comment]
@cloosli Interesting.  You should not need to install the Dart SDK separately, which is why it's not in the installation guide--Flutter ships with dart.  And this crash is in Flutter dart code, so dart itself is installed and compiling...

**Comment by softwareops-mayank-goyal** [comment]
Hi, did anyone find the solution of above issue, I am still getting this.

**Comment by cloosli** [comment]
@softwareops-mayank-goyal Yes: https://github.com/flutter/flutter/issues/80418#issuecomment-824707180

**Comment by zanderso** [comment]
This is the most frequent tool crasher on the stable channel.

@darshankawar @maheshmnj did any of the similar issues you closed give full logs for this? There should be some extra diagnostic messages from the tool for this crash if it was run with `--verbose`.

**Comment by darshankawar** [comment]
@zanderso Hi, this crash occurs while running various commands like `flutter pub get`, `flutter doctor -v` and so on and everytime throws same kind of logs as below:

<details>
<summary>console error log</summary>



```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:664:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:663:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:285:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:225:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:121:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:546:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1143:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)


```


</details>

I'll try to find out to see if we can get a verbose log for it.

**Comment by maheshmnj** [comment]
Unfortunately, none of the linked issues have any extra logs  than this https://github.com/flutter/flutter/issues/80418#issuecomment-917858164

**Comment by zanderso** [comment]
It may also be helpful if the folks reporting this issue could share the full path of their working directory and the full path of the Flutter project.

**Comment by christopherfujino** [comment]
investigating this currently, per zanderso this might be an issue with the working directory

**Comment by jmagman** [comment]
@softwareops-mayank-goyal @Yahiahm @pmuiga @LeDuyTuanVu or anyone else hitting this crash: can you run the same `flutter` command with the `-v` verbose flag, and paste or attach the full output of that command?

**Comment by christopherfujino** [comment]
stacktrace from beta `2.6.0-5.2.pre`:

```
Thread 0 main threadProcessException: ProcessException: The directory name is invalid.
  Command: C:\flutter\flutter\flutter\bin\cache\dart-sdk\bin\dart.EXE __deprecated_pub --verbosity=warning get --no-precompile
at _ProcessImpl._start(process_patch.dart:390)
at Process.start(process_patch.dart:36)
at LocalProcessManager.start(local_process_manager.dart:44)
at ErrorHandlingProcessManager.start.<anonymous closure>(error_handling_io.dart:691)
at _run(error_handling_io.dart:567)
at ErrorHandlingProcessManager.start(error_handling_io.dart:690)
at _DefaultProcessUtils.start(process.dart:425)
at _DefaultProcessUtils.stream(process.dart:444)
at _DefaultPub.batch(pub.dart:308)
at <asynchronous gap>(async)
at _DefaultPub.get(pub.dart:248)
at <asynchronous gap>(async)
at PubDependencies.update(flutter_cache.dart:119)
at <asynchronous gap>(async)
at Cache.updateAll(cache.dart:556)
at <asynchronous gap>(async)
at PrecacheCommand.runCommand(precache.dart:171)
at <asynchronous gap>(async)
at FlutterCommand.run.<anonymous closure>(flutter_command.dart:1125)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at CommandRunner.runCommand(command_runner.dart:209)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:288)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:236)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:62)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:92)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment]
Provides little additional information on this error code: https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

```
ERROR_DIRECTORY

267 (0x10B)

The directory name is invalid.
```

**Comment by christopherfujino** [comment]
Awaiting the next release to get more verbose crash logging

**Comment by christopherfujino** [comment]
I'm working on a "fix" for this that would involve detecting if `flutter_tools` doesn't exit and toolExiting with the website link.
