### ISSUE TITLE
./flutter/tools/gn --runtime-mode profile --android

### ISSUE THREAD

**Issue by asking1233** [flutter/flutter#80506]
```bask 
GOMA usage was specified but can't be found, falling back to local builds. Set the GOMA_DIR environment variable to fix GOMA.
Generating GN files in: out/android_profile_arm64
ERROR at //build/config/ios/ios_sdk.gni:54:27: Script returned non-zero exit code.
    _ios_sim_sdk_result = exec_script("ios_sdk.py", ios_sdk_args, "list lines")
                          ^----------
Current dir: /Users/linked_zl/Documents/sdk/flutter_engine/src/out/android_profile_arm64/
Command: python /Users/linked_zl/Documents/sdk/flutter_engine/src/build/config/ios/ios_sdk.py --sdk iphonesimulator
Returned 1.
stderr:

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Traceback (most recent call last):
  File "/Users/linked_zl/Documents/sdk/flutter_engine/src/build/config/ios/ios_sdk.py", line 50, in <module>
    sys.exit(main(sys.argv))
  File "/Users/linked_zl/Documents/sdk/flutter_engine/src/build/config/ios/ios_sdk.py", line 34, in main
    sdk_output = subprocess.check_output(command).strip()
  File "/usr/local/Cellar/python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['xcodebuild', '-version', '-sdk', 'iphonesimulator', 'Path']' returned non-zero exit status 1

See //build/toolchain/mac/BUILD.gn:9:1: whence it was imported.
import("//build/config/ios/ios_sdk.gni")
^--------------------------------------
See //third_party/dart/build/dart/dart_action.gni:77:14: which caused the file to be included.
    deps = [ host_tool ]
             ^--------
```

**Comment by TahaTesser** [comment]
Hi @asking1233 
Are you trying to run futter engine locally? 
Can you please provide complete reproducible steps and your `flutter doctor -v`

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
