### ISSUE TITLE
Segmentation fault when building flutter app

### ISSUE THREAD

**Issue by rbellens** [flutter/flutter#80509]
When building my flutter app (for android or ios or macos), I get the following error.

```
[   +8 ms] [   +8 ms] executing: /Users/rikbellens/tools/flutter/bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot --deterministic --snapshot_kind=app-aot-assembly
--assembly=/Users/rikbellens/CodeProjects/appsup-dart/firebase_dart/packages/firebase_dart_flutter/example/.dart_tool/flutter_build/c9b77e75829f765c2c4fdeaaae69a1d3/snapshot_assembly.S --strip
/Users/rikbellens/CodeProjects/appsup-dart/firebase_dart/packages/firebase_dart_flutter/example/.dart_tool/flutter_build/c9b77e75829f765c2c4fdeaaae69a1d3/app.dill
[ +562 ms] [ +560 ms] ===== CRASH =====
[        ] [   +2 ms] si_signo=Segmentation fault: 11(11), si_code=2, si_addr=0x10
[   +6 ms] [   +6 ms] Dart snapshot generator failed with exit code -6
[   +6 ms] [   +6 ms] Persisting file store
[  +13 ms] [  +12 ms] Done persisting file store
[   +8 ms] [   +9 ms] Target compile_macos_framework failed: Exception: gen shapshot failed.
[   +1 ms]            #0      CompileMacOSFramework.build (package:flutter_tools/src/build_system/targets/macos.dart:215:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
[        ]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
```

I'm on the stable channel, but the same happens on the dev channel. This is the output of `flutter doctor`:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale nl)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (3 available)

• No issues found!
```

Running the app in debug mode works fine, so I suspect it is an error in the aot compiler.

After a long search, I found the code that causes the problem. It seems something to do with a `late final` declaration, but I was not able to create a minimal example exhibiting the same problem. Possibly related to https://github.com/dart-lang/sdk/issues/45306.

The full example can be found in this repo https://github.com/appsup-dart/firebase_dart/tree/release/1.0.0/packages/firebase_dart_flutter/example. The following commit fixes the error: https://github.com/appsup-dart/firebase_dart/commit/aeb43e678c964474b1b91e5b440b1e41e1c014fc

**Comment by mraleph** [comment]
Based on the description and the commit that fixes it is exactly the same issue as  dart-lang/sdk#45306: compiler crashes when compiling field initializers which contain async/async* function expressions inside.
