### ISSUE TITLE
The method 'map' was called on null. Receiver: null Tried calling: map<Object>(Closure: (MapsObject<dynamic>) => Object) in google_maps_flutter

### ISSUE THREAD

**Issue by indrakumarprajapat** [flutter/flutter#80508]
I added google_maps_flutter and google_directions_api packages. Using google auto complete i am getting the direction api result and drawing path on google map, but the following error we are getting in ios but the same code is working fine in android.
Its specificly we are getting on ios.

here are the package, 
  google_directions_api: ^0.8.0
  google_maps_flutter: ^2.0.3

and i am using flutter 2.0

here is the error output,

```
======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building GoogleMap(dirty, state: _GoogleMapState#076c7):
The method 'map' was called on null.
Receiver: null
Tried calling: map<Object>(Closure: (MapsObject<dynamic>) => Object)

The relevant error-causing widget was: 

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      serializeMapsObjectSet (package:google_maps_flutter_platform_interface/src/types/utils/maps_object.dart:17:22)
#2      serializeMarkerSet (package:google_maps_flutter_platform_interface/src/types/utils/marker.dart:15:10)
#3      MethodChannelGoogleMapsFlutter.buildView (package:google_maps_flutter_platform_interface/src/method_channel/method_channel_google_maps_flutter.dart:454:23)
#4      _GoogleMapState.build (package:google_maps_flutter/src/google_map.dart:253:47)
...
====================================================================================================
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<MapEntry<MapsObjectId<Marker>, Marker>>(Closure: (Marker) => MapEntry<MapsObjectId<Marker>, Marker>)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      keyByMapsObjectId (package:google_maps_flutter_platform_interface/src/types/utils/maps_object.dart:10:54)
#2      new MapsObjectUpdates.from (package:google_maps_flutter_platform_interface/src/types/maps_object_updates.dart:25:52)
#3      new MarkerUpdates.from (package:google_maps_flutter_platform_interface/src/types/marker_updates.dart:14:15)
#4      _GoogleMapState._updateMarkers (package:google_maps_flutter/src/google_map.dart:311:23)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("text")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      new Time.fromMap (package:google_directions_api/src/directions.response.dart:1216:18)
#2      new Leg.fromMap (package:google_directions_api/src/directions.response.dart:606:27)
#3      new DirectionsRoute.fromMap.<anonymous closure> (package:google_directions_api/src/directions.response.dart:203:58)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#8      new List.of (dart:core-patch/array_patch.dart:50:28)
#9      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#10     IterableCommonExtension.mapList (pa<…>



```

**Comment by TahaTesser** [comment]
Hi @indrakumarprajapat 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with just `google_maps_flutter` and `flutter run --verbose` logs running the minimal code sample?


For issues related `google_directions_api`, please file an issue on their dedicated GitHub repositroy
Thank you

**Comment by stuartmorgan** [comment]
This means that you've set the `markers` property of `GoogleMap` to null. As of version 2.0 that property is non-nullable, so that's an error on your code.

**Comment by indrakumarprajapat** [comment]
@stuartmorgan  but its working on android the same code, not on iOS.

**Comment by TahaTesser** [comment]
@indrakumarprajapat 
If you think this is an issue with the package, please provide the details https://github.com/flutter/flutter/issues/80508#issuecomment-820432309
Thank you

**Comment by indrakumarprajapat** [comment]
Flutter doctor -v,  output, 

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/indras/flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/indras/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/indras/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.72

• No issues found!

```

Actually the code sample will take lot time, bcos there are lot more code.  Let me try to create that.

**Comment by stuartmorgan** [comment]
If you can provide a code sample that reproduces this without setting a non-nullable property to null, we can reopen.
