### ISSUE TITLE
pubspec.yaml assets can't use folder to import all file

### ISSUE THREAD

**Issue by plumhly** [flutter/flutter#80560]
## Steps to Reproduce

1. this is my folder structure
<img width="328" alt="截屏2021-04-16 上午11 29 10" src="https://user-images.githubusercontent.com/10388177/114967500-29073f80-9ea7-11eb-9811-880528c16f9d.png">

2. in pubspec.yaml:
<img width="353" alt="截屏2021-04-16 上午11 29 28" src="https://user-images.githubusercontent.com/10388177/114967534-37555b80-9ea7-11eb-8c8e-7a3ed228f4bd.png">

3. and then in code 
 ```
Image.asset("assets/images/ic_student.png"),
``` 

**Expected results:** 
load image

**Actual results:** 
print error in console

```
The following assertion was thrown resolving an image codec:
Unable to load asset: assets/images/ic_student.png

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:667:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "assets/images/ic_student.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#75994(), name: "assets/images/ic_student.png", scale: 1.0)
```

<details>
  <summary>flutter doctor -v` here</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.6 19G73 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.1 at /Users/plum/flutter
    • Framework revision c5a4b4029c (6 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/plum/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • BKK AL10 (mobile)          • FAJBB19430150772                         • android-arm64  • Android 8.1.0 (API 27)
    • “plum”的 iPhone (mobile)    • c6d9eb4f0bb5945f9bd07cee1df5213a62f4ab80 • ios            • iOS 14.2
    • iPhone 12 Pro Max (mobile) • 59656E00-C80E-46DE-B12D-FE51EDFA663F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 89.0.4389.128

• No issues found!

```

</details>

**Comment by SapinderSingh** [comment]
@plumhly, I think the file is in 3x folder, try using Image.asset("assets/images/3x/ic_student.png") and can also try adding both the folders in pubspec.yaml file as - 

assets/images/

assets/images/3x/


Hope it helps.

**Comment by darshankawar** [comment]
@plumhly 
Your said image is in `assets/images/3x/ic_student.png` path, but you seem to have provided only `assets/images/ic_student.png` which is wrong and hence the error.  

Update your image.asset path to include `assets/images/3x/ic_student.png` and your issue should be resolved.

Closing from here as this isn't a bug but code implementation issue.

**Comment by plumhly** [comment]
@SapinderSingh @darshankawar 
thanks for your help
