### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/admin/flutter/bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot.

### ISSUE THREAD

**Issue by NasirAbbasiWebHR** [flutter/flutter#80565]
## Command
```
flutter assemble -dTargetPlatform=darwin-x64 -dTargetFile=lib/main.dart -dBuildMode=release -dTreeShakeIcons=true -dDartObfuscation=false -dSplitDebugInfo= -dTrackWidgetCreation=true --DartDefines= --ExtraGenSnapshotOptions= --ExtraFrontEndOptions= --build-inputs=/Volumes/Data/Flutter/mobile_admin/macos/Flutter/ephemeral/FlutterInputs.xcfilelist --build-outputs=/Volumes/Data/Flutter/mobile_admin/macos/Flutter/ephemeral/FlutterOutputs.xcfilelist --output=/Volumes/Data/Flutter/mobile_admin/build/macos/Build/Products/Release release_macos_bundle_flutter_assets
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/admin/flutter/bin/cache/artifacts/engine/darwin-x64-release/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:56)
#9      CompileMacOSFramework.build (package:flutter_tools/src/build_system/targets/macos.dart:203:42)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#14     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale en-PK)
    • Flutter version 2.0.4 at /Users/admin/flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPad Pro (11-inch) (2nd generation) (mobile) • AA83703D-5C63-4831-AEC8-E31F6C17543C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)                              • macos                                • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)                                 • chrome                               • web-javascript • Google Chrome 89.0.4389.128

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 8264cb3e8a797eef39cbcd32bb56fd07790efb7f
### Plugins
hexcolor-2.0.3

**Comment by iapicca** [comment]
@NasirAbbasiWebHR 
could you try with the latest `master`
possibly fixed by https://github.com/flutter/flutter/pull/78272

**Comment by pedromassangocode** [comment]
Yes, this may have been fixed already. If the issue persists on latest master, please provide your `flutter doctor -v`.
