### ISSUE TITLE
Platform channel null safety errors could be clearer

### ISSUE THREAD

**Issue by xster** [flutter/flutter#80584]
(synthesizing feedback from google customer)
Given a platform channel call like

```dart
Future<List<String>> getFoo() async {
    return await _channel
        .invokeMethod<List<String>>(arg);
}
```

the error returned is

```
04-15 14:04:36.151 15279 15453 I flutter : [SEVERE] get foo type 'List<Object?>' is not a subtype of type 'List<String>?' in type cast #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:41)
04-15 14:04:36.151 15279 15453 I flutter : <asynchronous suspension>
04-15 14:04:36.151 15279 15453 I flutter : #1      SomeClass.getFoo (package:some.package/some_file.dart:17:12)
```

It's not immediately clear that it's the parametrization of the generic that has nullability differences. It's also not immediately clear what the solution is since https://dart.dev/codelabs/null-safety#exercise-nullable-type-parameters-for-generics points to the problem but not to the solution. 

Maybe this could be a linter caught in the IDE?

**Comment by jonahwilliams** [comment]
See also: ps://api.flutter.dev/flutter/services/MethodChannel/invokeListMethod.html

This isn't just a null safety error, its a reified generic error. `invokeMethod` can only return `dynamic` List/Map types, any other type requires casting. I don't think there is a way to express that in terms of a generic constraint, but you could use an assert and try to capture the runtime error to add more error details.
