### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

### ISSUE THREAD

**Issue by 15tariqj** [flutter/flutter#80586]
Hi, I've been working on a project for some time now, and recently began working on an iOS home screen widget for it. Upon attempting to run the project with Android Studio again on my physical iPhone 12 Pro, I receive the following issue:

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios -v

## exception

ProcessException: ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

2021-04-16 18:21:28.857 xcodebuild[62173:804987]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
Details:  (null) deviceType from 00008101-0003746126BA001E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7fefa1361e10>
Method:   -platform
Thread:   <NSThread: 0x7fefa13541c0>{number = 7, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2021-04-16 18:21:29.063 xcodebuild[62173:805056]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
Details:  (null) deviceType from 00008101-0003746126BA001E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7fefa1361e10>
Method:   -platform
Thread:   <NSThread: 0x7fefa1867150>{number = 8, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
2021-04-16 18:21:29.145 xcodebuild[62173:805056]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
Details:  (null) deviceType from 00008101-0003746126BA001E was NULL when -platform called.
Object:   <DTDKMobileDeviceToken: 0x7fefa1361e10>
Method:   -platform
Thread:   <NSThread: 0x7fefa1867150>{number = 8, name = (null)}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled.
  Command: xcrun xcodebuild -list

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:171:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:323:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:414:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:585:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:567:35)
<asynchronous suspension>
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:509:50)
<asynchronous suspension>
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:486:41)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart:423:36)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:88:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp (package:flutter_tools/src/commands/build_ios.dart:201:26)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:231:33)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#21     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#23     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 2.0.1 at /Users/tariqjamal/Desktop/Projects/flutter
    • Framework revision c5a4b4029c (6 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tariqjamal/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008101-0003746126BA001E • ios            • iOS 14.4.2
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

It's probably worth noting that I receive no issues when I run the app from xcode directly

**Comment by 15tariqj** [comment]
Nevermind, managed to solve this by changing the project settings from legacy to xcode default, sorry!
