### ISSUE TITLE
[tool_crash] _Exception

### ISSUE THREAD

**Issue by leashag23** [flutter/flutter#80593]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_Exception
```
#0      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:67:7)
#1      FileSystemUtils.copyDirectorySync (package:flutter_tools/src/base/file_system.dart:84:9)
#2      ChromiumLauncher._cacheUserSessionInformation (package:flutter_tools/src/web/chrome.dart:319:26)
#3      ChromiumLauncher.launch.<anonymous closure> (package:flutter_tools/src/web/chrome.dart:230:9)
#4      _rootRun (dart:async/zone.dart:1346:47)
#5      _CustomZone.run (dart:async/zone.dart:1258:19)
#6      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:176:18)
#7      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:674:39)
#8      Future._propagateToListeners (dart:async/future_impl.dart:730:37)
#9      Future._propagateToListeners (dart:async/future_impl.dart:629:9)
#10     Future._completeWithValue (dart:async/future_impl.dart:539:5)
#11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
#12     _rootRun (dart:async/zone.dart:1354:13)
#13     _CustomZone.run (dart:async/zone.dart:1258:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
    • Flutter version 2.0.4 at C:\Users\leash\Downloads\flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\leash\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\leash\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.39

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
### Plugins
firebase_core-0.2.5+1
firebase_database-0.4.6

**Comment by darshankawar** [comment]
@leashag23 
Can you provide `flutter run --verbose` ? 
Also, can you provide `flutter_01.log` that is generated after this crash.
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
