### ISSUE TITLE
google_sign_in - Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by Simonomer** [flutter/flutter#80636]
# google_sign_in - Unhandled Exception: PlatformException

Hey, I'm using google_sign_in plugin to authenticate with google. I'm not using firebase right now due architecture considirations.
I'm having a error (described below) and couldn't find proper documatations on this plug-in. I would love to get your help with this.

I'm unable to auth with google with this library with the error:

```
Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
```

What I have done in the process:
1. created a google project, consent screen and oauth api client id for android.
2. generated a jks key using the command:
``` bash
keytool -genkey -v -keystore c:\Users\USER_NAME\.android\key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key
```
3. Extracted the SHA1 from the key.jks and put it inside the google credentials client id
4. Created key.properties inside android dir
``` properties
storePassword=PASSWORD
keyPassword=PASSWORD
keyAlias=key
storeFile=C:/Users/USER_NAME/.android/key.jks
```
5. Added keystore to build.gradle
``` gradle
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

// Inside android section
signingConfigs {
    release {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
        storePassword keystoreProperties['storePassword']
    }

    debug {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
        storePassword keystoreProperties['storePassword']
    }
}
```
6. Add my google sign_in code in flutter:
```dart
var _googleSignIn = new GoogleSignIn(
    clientId: "my-client-id",
    scopes: ['email'],
);
```

Now when I tried to log in I recieved the exception: 
```
E/flutter (11339): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter (11339): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter (11339): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (11339): <asynchronous suspension>
E/flutter (11339): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
E/flutter (11339): <asynchronous suspension>
E/flutter (11339): 
```

## More information:
My dependencies:
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.3
  http: '>=0.12.0 <0.13.0'
  intl: '^0.17.0'
  meta: '^1.1.8'
  validators: ^2.0.0
  flutter_secure_storage: ^4.1.0
  google_sign_in: ^5.0.1
```

flutter doctor -v:
```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale he-IL)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\simon\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\simon\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\simon\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\simon\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.76

• No issues found!
```

**Comment by SapinderSingh** [comment]
@Simonomer I think you haven't added googleservices.json file to your project.
