### ISSUE TITLE
[local engine build] Getting "Unexpected Kernel Format Version" after updating flutter engine repo

### ISSUE THREAD

**Issue by kartik1225** [flutter/flutter#80645]
I am using a local engine

To compile the engine I am using following comands:
`./flutter/tools/gn --android --unoptimized --android-cpu=arm64 && ninja -C out/android_debug_unopt_arm64`

To run the app I run flutter with following flags:

`--local-engine-src-path /path/to/engine/src/ --local-engine=android_debug_unopt_arm64`

<details>
<summary>Logs</summary>

```
Launching lib/main.dart on Pixel 4a in debug mode...
Running Gradle task 'assembleDebug'...
Unhandled exception:
Unexpected Kernel Format Version 61 (expected 55)
#0      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:589:9)
#1      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#2      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:576:21)
#3      IncrementalCompiler.prepareSummary (package:front_end/src/fasta/incremental_compiler.dart:1660:12)
#4      IncrementalCompiler.ensurePlatformAndInitialize (package:front_end/src/fasta/incremental_compiler.dart:1151:23)
<asynchronous suspension>
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:11)
<asynchronous suspension>
#6      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:29)
<asynchronous suspension>
#7      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:509:11)
<asynchronous suspension>
#8      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1105:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.

```
</details>

<details>
<summary>flutter doctor -v</summary>

flutter doctor -v

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.1 20C69 darwin-x64, locale en-IN)
    • Flutter version 2.0.5 at /Users/kartik/ExternalLibs/flutter
    • Framework revision adc687823a (20 hours ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kartik/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel 4a (mobile) • 0B291JEC201996 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 89.0.4389.128
```

</details>

<details>
<summary>pubspec.yaml</summary>

```
version: 1.0.0+1

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
...
dependency_overrides:
  sky_engine:
    path: "/path/to/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_engine"
  sky_services:
    path: "/path/to/engine/src/out/host_debug_unopt/gen/dart-pkg/sky_services"
...
```
</details>

**Comment by jonahwilliams** [comment]
You need to rebuild the corresponding host engine as well (`host_debug_unopt`). This is where the tooling that the flutter tool uses to build your app is, and if its not in sync with the engine you'll get errors like the kernel binary format issue

**Comment by kartik1225** [comment]
Ohh that was very dumb of me.. It got resolved Thanks @jonahwilliams
