### ISSUE TITLE
Flutter failed to copy ic_launcher.png due to unknown error

### ISSUE THREAD

**Issue by Vanessa-Berazategui** [flutter/flutter#80687]
Hello, I'm having problems creating new projects with Flutter 2.0.5 and Android Studio 4.1.0. I'm always getting this same error:

`Flutter failed to copy C:\....\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png to C:\....\git-repo\flutter_dd_skeleton\android\app\src\main\res\mipmap-hdpi\ic_launcher.png due to unknown error. The flutter tool cannot access the file. Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.`

$ flutter doctor -v

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\usuario\Documents\FIng\flutter     
    • Framework revision adc687823a (2 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\usuario\Documents\FIng\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\usuario\Documents\FIng\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart   
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.39

• No issues found!
```

$ Environment variables (all directories with permissions):

ANDROID_SDK_ROOT C:\Users\usuario\Documents\FIng\Android\Sdk
FLUTTER_HOME C:\Users\usuario\Documents\FIng\flutter

What could be happening?
Thanks.

**Comment by TahaTesser** [comment]
Hi @Vanessa-Berazategui 
I cannot reproduce the issue,  can you please provide complete logs from the terminal?

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\Taha\Code\flutter_stable
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.77

! Doctor found issues in 1 category.
```
	
</details>

`flutter create my app -v`
`cd myapp`
`flutter run -v`

**Comment by TahaTesser** [comment]
I am getting a similar error when executing `flutter clean`
```console
PS C:\Users\Taha\AndroidStudioProjects\stable_flutter> flutterm clean
Deleting build...                                                   56ms
Flutter failed to delete a directory at "build". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
PS C:\Users\Taha\AndroidStudioProjects\stable_flutter> flutters clean
Deleting build...                                                    6ms
Flutter failed to delete a directory at "build". The flutter tool cannot access the file.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
PS C:\Users\Taha\AndroidStudioProjects\stable_flutter> 
```

**Comment by Vanessa-Berazategui** [comment]
Hi Taha, thanks for your replay, 

Here the logs for $flutter create flutter_app p -v

`$ flutter create flutter_app -v
[ +351 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +536 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] adc687823a831bbebe28bdccfac1a628ca621513
[   +3 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[+1117 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[   +3 ms] 2.0.5
[ +184 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +171 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[   +1 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git ls-remote --get-url origin
[ +148 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[+17145 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git rev-parse --abbrev-ref HEAD
[ +161 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[ +292 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +18 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +851 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +111 ms] "flutter create" took 1,070ms.
[  +27 ms] Multiple output directories specified.
           Try moving -v to be immediately following create
[ +120 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                    #1      CreateBase.validateOutputDirectoryArg (package:flutter_tools/src/commands/create_base.dart:147:7) 
                    #2      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:181:5)
                    #3      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1157:18)
                    <asynchronous suspension>
                    #4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
                    <asynchronous suspension>
                    #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
                    <asynchronous suspension>
                    #8      FlutterCommandRunner.runCommand.<anonymous closure>
                    (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
                    <asynchronous suspension>
                    #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #11     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
                    <asynchronous suspension>
                    #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
                    <asynchronous suspension>
                    #13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
                    <asynchronous suspension>
                    #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
                    <asynchronous suspension>
                    #17     main (package:flutter_tools/executable.dart:90:3)
                    <asynchronous suspension>


[  +39 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 2
`

**Comment by jmagman** [comment]
> The flutter tool cannot access the file. Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

Does your user have read/write permissions to the SDK and to where you're trying to create your project?

> flutter create flutter_app p -v

Sorry, the command should have been `flutter create -v myapp` with the `-v` before the name of the project.

**Comment by Vanessa-Berazategui** [comment]
Hi @jmagman  yes I have all permissions

Here the logs of  $ flutter create -v flutter_app

```
$ flutter create -v flutter_app
[ +355 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +321 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] adc687823a831bbebe28bdccfac1a628ca621513
[   +4 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513 
[ +193 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[   +3 ms] 2.0.5
[ +181 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +198 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[   +2 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git ls-remote --get-url origin
[ +132 ms] Exit code 0 from: git ls-remote --get-url origin
[  +28 ms] https://github.com/flutter/flutter.git
[ +278 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git rev-parse --abbrev-ref HEAD
[ +155 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[ +374 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +17 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +264 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +197 ms] Creating project flutter_app...
[ +708 ms]   flutter_app\.gitignore (created)
[  +51 ms]   flutter_app\.idea\libraries\Dart_SDK.xml (created)
[  +30 ms]   flutter_app\.idea\libraries\KotlinJavaRuntime.xml (created)
[  +10 ms]   flutter_app\.idea\modules.xml (created)
[  +14 ms]   flutter_app\.idea\runConfigurations\main_dart.xml (created)
[  +11 ms]   flutter_app\.idea\workspace.xml (created)
[  +14 ms]   flutter_app\.metadata (created)
[  +10 ms]   flutter_app\android\app\build.gradle (created)
[  +30 ms]   flutter_app\android\app\src\main\kotlin\com\example\flutter_app\MainActivity.kt (created)
[  +22 ms]   flutter_app\android\build.gradle (created)
[  +28 ms]   flutter_app\android\flutter_app_android.iml (created)
[  +11 ms]   flutter_app\android\.gitignore (created)
[  +18 ms]   flutter_app\android\app\src\debug\AndroidManifest.xml (created)
[  +11 ms]   flutter_app\android\app\src\main\AndroidManifest.xml (created)
[  +11 ms]   flutter_app\android\app\src\main\res\drawable\launch_background.xml (created)
[  +18 ms]   flutter_app\android\app\src\main\res\drawable-v21\launch_background.xml (created)
[  +18 ms]   flutter_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
[+5732 ms] "flutter create" took 7,325ms.
[  +25 ms] Flutter failed to copy

C:\Users\usuario\Documents\FIng\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_laun           cher.png to

C:\Users\usuario\Documents\FIng\git-repo\geopos2_alkosto_mobile\flutter_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.p           ng due to unknown error. The flutter tool cannot access the file.
           Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the       
current user.
[  +27 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
           #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:739:3)
           #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:559:7)
           #4      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:316:5)
           #5      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:266:18)
           #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
           #7      Template.render (package:flutter_tools/src/template.dart:193:24)
           #8      CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:387:21)
           <asynchronous suspension>
           #9      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:23)
           <asynchronous suspension>
           #10     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:31)
           <asynchronous suspension>
           #11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)        
           <asynchronous suspension>
           #12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)     
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #16     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)       
           <asynchronous suspension>
           #20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #21     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #23     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #24     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #25     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +67 ms] Running shutdown hooks
[   +6 ms] Shutdown hooks complete
[  +19 ms] exiting with code 1
```

**Comment by Vanessa-Berazategui** [comment]
Hi @jmagman yes I have all permissions

Here the logs of $ flutter create -v flutter_app

```
$ flutter create -v flutter_app
[ +358 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +313 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] adc687823a831bbebe28bdccfac1a628ca621513
[   +4 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513 
[ +192 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[   +3 ms] 2.0.5
[ +179 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +158 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[   +2 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git ls-remote --get-url origin
[ +126 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[ +274 ms] executing: [C:\Users\usuario\Documents\FIng\flutter/] git rev-parse --abbrev-ref HEAD
[ +139 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[ +349 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +18 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +281 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +149 ms] Creating project flutter_app...
[ +267 ms]   flutter_app\.gitignore (created)
[  +52 ms]   flutter_app\.idea\libraries\Dart_SDK.xml (created)
[  +31 ms]   flutter_app\.idea\libraries\KotlinJavaRuntime.xml (created)
[  +10 ms]   flutter_app\.idea\modules.xml (created)
[  +11 ms]   flutter_app\.idea\runConfigurations\main_dart.xml (created)
[  +11 ms]   flutter_app\.idea\workspace.xml (created)
[  +12 ms]   flutter_app\.metadata (created)
[  +12 ms]   flutter_app\android\app\build.gradle (created)
[  +16 ms]   flutter_app\android\app\src\main\kotlin\com\example\flutter_app\MainActivity.kt (created)
[  +22 ms]   flutter_app\android\build.gradle (created)
[  +27 ms]   flutter_app\android\flutter_app_android.iml (created)
[  +11 ms]   flutter_app\android\.gitignore (created)
[  +14 ms]   flutter_app\android\app\src\debug\AndroidManifest.xml (created)
[  +10 ms]   flutter_app\android\app\src\main\AndroidManifest.xml (created)
[  +11 ms]   flutter_app\android\app\src\main\res\drawable\launch_background.xml (created)
[  +16 ms]   flutter_app\android\app\src\main\res\drawable-v21\launch_background.xml (created)
[  +19 ms]   flutter_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
[+5399 ms] "flutter create" took 6,547ms.
[  +26 ms] Flutter failed to copy

C:\Users\usuario\Documents\FIng\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_laun           cher.png to
C:\Users\usuario\Documents\FIng\git-repo\flutter_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png due to
           unknown error. The flutter tool cannot access the file.
           Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the       
current user.
[  +26 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
           #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:739:3)
           #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:559:7)
           #4      ErrorHandlingFile.copySync (package:flutter_tools/src/base/error_handling_io.dart:316:5)
           #5      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:266:18)
           #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
           #7      Template.render (package:flutter_tools/src/template.dart:193:24)
           #8      CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:387:21)
           <asynchronous suspension>
           #9      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:23)
           <asynchronous suspension>
           #10     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:31)
           <asynchronous suspension>
           #11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)        
           <asynchronous suspension>
           #12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)     
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #16     FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)       
           <asynchronous suspension>
           #20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #21     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #23     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #24     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #25     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +68 ms] Running shutdown hooks
[   +4 ms] Shutdown hooks complete
[  +20 ms] exiting with code 1
```

**Comment by TahaTesser** [comment]
@jmagman 
Yes, it's just the regular `AndroidStudioProjects` folder created by Android Studio, which I use every day, this error appeared in the same folder

**Comment by eliasyishak** [comment]
@Vanessa-Berazategui is this still something you are encountering?
