### ISSUE TITLE
[webview_flutter] Crash on Android

### ISSUE THREAD

**Issue by wangbo4020** [flutter/flutter#80717]
## Steps to Reproduce
```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (5 available)

• No issues found!
````
`webview_flutter: 2.0.4`

**Expected results:** 

No crash

**Actual results:** 

<details>
  <summary>Logs</summary>
  
```console
2021-04-19 20:22:15.387 29815-29815/package.name E/AndroidRuntime: FATAL EXCEPTION: main
    Process: package.name, PID: 29815
    java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1664)
        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1933)
        at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1196)
        at io.flutter.plugins.webviewflutter.InputAwareWebView$1.run(InputAwareWebView.java:188)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

</details>

**Comment by TahaTesser** [comment]
Hi @wangbo4020 
Are you trying to open a new tab in the webview? https://github.com/flutter/flutter/issues/75760
Please use hybrid composition https://github.com/flutter/flutter/issues/75760#issuecomment-776633601

If that's not the issue, can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by wangbo4020** [comment]
```console
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
    • Flutter version 2.0.5 at D:\Development\Flutter\flutter
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Development\Android\android-sdk-windows
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Development\Android\android-sdk-windows
    • Java binary at: D:\Development\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at D:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Development\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at D:\Program Files (x86)\JetBrains\IntelliJ IDEA 2020.1.1
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

```

**Comment by wangbo4020** [comment]
I will find time to use [webview_flutter] example try it.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
