### ISSUE TITLE
Failed assertion: line 108 pos 12: '_positions.isNotEmpty'

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#80713]
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 108 pos 12: '_positions.isNotEmpty'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:108:12)
#3      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:908:27)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#6      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
...
====================================================================================================
```

```
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.21327.1010], locale en-US)
    • Flutter version 2.1.0-12.2.pre at C:\Users\cyberpwn\Documents\development\flutter
    • Framework revision 5bedb7b1d5 (5 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\cyberpwn\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\cyberpwn\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.1
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\cyberpwn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • IN2017 (mobile)   • 2e01d742 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.21327.1010]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 89.0.4389.72

• No issues found!
```

**Comment by cyberpwnn** [comment]
No I can't becasue this issue just started happening on a flutter update, codebase is very large. That's kind of why I submitted an issue, that exception is not helpful at all in finding it, I wouldnt be able to do a better job at finding it than that stack would.

**Comment by cyberpwnn** [comment]
I always check hasClients before using jumpTo but thats not the issue, as im not calling jumpTo or animateTo or even using .position where it's failing. My guess its the controller being attached to a widget that doesnt exist yet.

**Comment by TahaTesser** [comment]
Hi @cyberpwnn 
You can isolate the code in debug mode, locate which screen of your app prints this error, in such screen, which is a widget that might use scroll controller, comment out code if needed to isolate the issue further and run the app, I'm sure you can reach the code that might be causing the issue and then you can create code sample using similar that would help replicate this issue.

Code sample was provided here https://github.com/flutter/flutter/issues/74372#issue-790645978

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
