### ISSUE TITLE
android invokeMethod  error:Reply already submitted

### ISSUE THREAD

**Issue by xiaohua001** [flutter/flutter#80782]
## Steps to Reproduce

1. flutter doctor is ok.
2. if I slowly click the button is ok
3. double click   caused App crashed
4. It's seem that ,if I click quikly  it will happend  result.success("xxx")  、result.success("xxx"), I guess it's the reason caused app crased ,Hope U can help me, thanks a lot~
**dart Code**:
```
  void initState() {
    initBroad();
    super.initState();
  }
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("home"),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            ElevatedButton(
              child: Text("click me"),
              onPressed: getBatteryInfo,
            ),
          ],
        ),
      ),
    );
  }
  void getBatteryInfo() async {
    final result = await platform.invokeMethod("getBatteryInfo");
    setState(() {
       //  That  result is the barcode what I need from android codeScan    
      _level = result;
    });
    print(_level );
  }
  void initBroad() async {
    final res = await platform.invokeMethod("register");
  }
```
**MainActivity.java**
```
public class MainActivity extends FlutterActivity {
    private static final String CHANNEL = "test.com/native";
    private MethodChannel.Result ret;
    private MethodCall cal;
    String barcode = "";
    String  m_Broadcastname = "com.barcode.sendBroadcast";
    MyCodeReceiver receiver = new MyCodeReceiver();
    @Override
    public synchronized void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);
        MethodChannel methodChannel = new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL);
        methodChannel.setMethodCallHandler(
                (call, result)->{
                    ret = result;
                    cal=call;
                    switch(call.method)
                    {
                        case "getBatteryInfo" :
                            getBarcode();
                            // getAsyncData  however~ if I use this, and close Function "getBarcode()" it's ok~
                            break;
                        case "register" :
                            ret.success("register success");
                            registBroad();
                            break;
                        case "dispose" :
                            dispose();
                            break;
                        default :
                            ret.notImplemented();
                    }
                }
        );
    }
    private void registBroad(){
        final IntentFilter intentFilter = new IntentFilter();
        intentFilter.addAction(m_Broadcastname);
        registerReceiver(receiver, intentFilter);
    }
    public class MyCodeReceiver extends BroadcastReceiver
    {
        private static final String TAG = "MycodeReceiver";
        @Override
        public synchronized void onReceive(Context context, Intent intent) {
            if (intent.getAction().equals(m_Broadcastname)) {
                String str = intent.getStringExtra("BARCODE");
                if (!"".equals(str)) {
                    barcode = str;
                    // the barcode is what i need
                    ret.success(barcode);
                }
            }
        }
    }
    private void dispose(){
        unregisterReceiver(receiver);
    }
    private int getAsyncData() throws InterruptedException {
        Thread.sleep(2000);
        return 123;
    }
    private void getBarcode(){
        Intent intent = new Intent();
        intent.setAction("com.barcode.sendBroadcastScan");
        sendBroadcast(intent);
    }
}
```

<details>
  <summary>Logs</summary>
  

```
 Process: com.example.flutter_native, PID: 4870
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.barcode.sendBroadcast flg=0x10 (has extras) } in com.example.flutter_native.MainActivity$MyCodeReceiver@7dc841e
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1174)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6297)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
     Caused by: java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
        at com.example.flutter_native.MainActivity$MyCodeReceiver.onReceive(MainActivity.java:89)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1164)
        at android.os.Handler.handleCallback(Handler.java:836) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6297) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945) 
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@xiaohua001 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/29092
Please follow-up there and see underlying comments to get help on your issue.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
