### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s)

### ISSUE THREAD

**Issue by senthiljs** [flutter/flutter#80793]
## Command
```
flutter --no-color build ios
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s)
```
#0      _StringBase._interpolate (dart:core-patch/string_patch.dart:861:9)
#1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:240:72)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.3 at /Users/senthiljs/development/flutter
    • Framework revision 4d7946a68d (5 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/senthiljs/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • CPH2001 (mobile)                     • WGCMHEN7YH6STCVS                     • android-arm64  • Android 10 (API 29)
    • iPod touch (7th generation) (mobile) • 02A8115F-0DB9-445A-8DDF-1A11EB02A601 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 89.0.4389.128

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
flutter_plugin_android_lifecycle-1.0.11
geocoding-1.0.5
geolocator-6.2.1
geolocator_web-1.0.1
google_maps_flutter-0.5.33
image_picker-0.6.7+22
open_file-3.1.0
path_provider-1.2.0
path_provider_linux-2.0.0
path_provider_windows-2.0.0
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by darshankawar** [comment]
Similar issue was fixed, merged and cherry picked into Stable, https://github.com/flutter/flutter/issues/59029.
Not sure if it has come back.

Keeping this open for further insights.

Cc: @jmagman

**Comment by jmagman** [comment]
App ID should be more resilient. https://github.com/flutter/flutter/issues/59029#issuecomment-654492636
https://github.com/flutter/flutter/blob/4d7946a68d26794349189cf21b3f68cc6fe61dcb/packages/flutter_tools/lib/src/commands/build_ios.dart#L240

**Comment by darshankawar** [comment]
@jmagman Hi again :)
Coming back to this issue, I verified by running below commands on latest stable version of framework and didn't get the reported error. 

1. `flutter --no-color build ios`:

```
dhs@Dhss-MacBook-Pro flavors_example % flutter --no-color build ios
Building com.nevercode.triage for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         7.0s
Xcode build done.                                           41.4s
Built /Users/dhs/Documents/NCFlutter/triage-examples/flutter_examples/flavors_example/build/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro flavors_example % 
```

2. `flutter build ios --release -t lib/main_dev.dart --no-codesign --flavor dev --build-number=635`:
```

dhs@Dhss-MacBook-Pro flavors_example % flutter build ios --release -t lib/main_dev.dart --no-codesign --flavor dev --build-number=635
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.nevercode.triage for device (ios-release)...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3.1s
Xcode build done.                                           36.6s
Built /Users/dhs/Documents/NCFlutter/triage-examples/flutter_examples/flavors_example/build/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro flavors_example % 
```

With these updates, is it safe to close this issue ?

**Comment by stuartmorgan** [comment]
Given that we don't have reproducible steps here, closing.
