### ISSUE TITLE
fatal error: 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by desmeit** [flutter/flutter#80854]
I cannot build my App for IOS. I tried

flutter channel stable (master as well)
pod deintegrate
rm Flutter/Flutter.podspec
flutter clean
flutter pub get
pod install
flutter run

Nothing helps.

### Build IOS Error:
```
Error output from Xcode build:
↳
    2021-04-21 10:27:17.280 xcodebuild[6892:89934]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 00008101-000C042821B8001E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7ffa05353890>
    Method:   -platform
    Thread:   <NSThread: 0x7ffa0534a900>{number = 4, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-04-21 10:27:17.481 xcodebuild[6892:89896]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 00008101-000C042821B8001E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7ffa05353890>
    Method:   -platform
    Thread:   <NSThread: 0x7ffa051459d0>{number = 2, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-04-21 10:27:17.549 xcodebuild[6892:89896]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 00008101-000C042821B8001E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7ffa05353890>
    Method:   -platform
    Thread:   <NSThread: 0x7ffa051459d0>{number = 2, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/XXX/development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.2.1+1/ios/Classes/messages.m:4:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    In file included from /Users/XXXdevelopment/tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/ios/Classes/JavaScriptChannelHandler.m:5:
    /Users/XXX/development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-1.0.7/ios/Classes/JavaScriptChannelHandler.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
```

### flutter --verbose
```
 #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +111 ms] ensureAnalyticsSent: 109ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1

```

### flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H524 darwin-x64, locale de-DE)
    • Flutter version 2.0.5 at /Users/XXX/development/tools/flutter
    • Framework revision adc687823a (5 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/XXXLibrary/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/XXX/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

```

**Comment by darshankawar** [comment]
@desmeit 
Can you try :
```

$ rm ios/Flutter/Flutter.podspec
$ flutter clean
```

If above commands don't resolve the issue, can you provide `pubspec.yaml` and `ios/podfile` ?

Thanks.

**Comment by desmeit** [comment]
I tried that command as well.

### pubspec.yaml

```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1

  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  google_sign_in: ^5.0.2
  
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4

  provider: ^5.0.0
  
  flutter_spinkit: ^5.0.0
  auth_buttons: ^0.0.4

  
  google_fonts: 2.0.0
```

**Podfile**

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end

```

**Comment by adnanjpg** [comment]
can you try:
```
rm -rf build
rm -rf .dart_tool
rm -rf .flutter-plugins
rm -rf .flutter-plugins-dependencies
rm -rf .packages
rm -rf pubspec.lock

rm -rf ios/podfile.lock
rm -rf ios/.symlinks
rm -rf ios/pods
rm -rf ios/build
rm -rf ios/Runner.xcworkspace
rm -rf ios/Runner.xcodeproj/xcuserdata

```

they work for me most of the time

**Comment by darshankawar** [comment]
@desmeit 
Tried a sample app using the plugins you've, on latest master and was able to compile and build the app on simulator properly:

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Warning: CocoaPods recommended version 1.10.0 or greater not installed.
Pods handling may fail on some projects involving plugins.
To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

Running pod install...
Running Xcode build...
Xcode build done.                                           588.7s
Debug service listening on ws://127.0.0.1:52868/lsZHFLAZhw8=/ws
Syncing files to device iPhone 12 Pro Max...
Google Maps SDK for iOS version: 3.9.0.0
New version of Google Maps SDK for iOS available: 4.2.0.0
```

Can you provide your complete `flutter run --verbose` ? if the log is too big, put that in a file and share it here.

**Comment by desmeit** [comment]
[verbose.zip](https://github.com/flutter/flutter/files/6350181/verbose.zip)

**Comment by darshankawar** [comment]
Try [this](https://github.com/flutter/flutter/issues/44435#issuecomment-744662992) solution and see if it works for you.

**Comment by desmeit** [comment]
Yes I tried that before but it wasnt working.
Now i created an new project and copied all the files and it is working. Tomorrow I will test another thing and will let you know.

**Comment by AbhishekDoshi26** [comment]
Hey, did you check if the IOS version in your xcode is 11 or 9? It should be 11. Also, do check for all the packages that you are using from the pods tab.

**Comment by desmeit** [comment]
thanks, its the latest version.

**Comment by rostopira** [comment]
I have the same issue and I've noticed that `Flutter.framework` is missing from `ios/Flutter` directory.

How could I bring it back without recreating ios folder yet again? I'm quite tired of doing it and having a lot of iOS specific code there

**Comment by desmeit** [comment]
Okay, I solved the issue.

I changed the podfile from:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['ENABLE_BITCODE'] = 'NO'
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
```

to

```
post_install do |installer|
  installer.pods_project.targets.each do |target| 
    flutter_additional_ios_build_settings(target)
  end
end
```

like in this post described: 
https://stackoverflow.com/a/66986419/3037763

I tried this before, but always got an error message like this one:
`warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to`

It was probably due to the import of a faulty dart file. After I uncommented it and changed the podfile, it works.
