### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: File name too long, errno = 63

### ISSUE THREAD

**Issue by soramame-58** [flutter/flutter#80873]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=EFF23B07-8C7C-462C-BAA0-4823CE73705A --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Directory listing failed, OS Error: File name too long, errno = 63
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      RunCommand.usageValues (package:flutter_tools/src/commands/run.dart:392:14)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1151:15)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale ja-JP)
    • Flutter version 2.0.5 at /Users/kouchiryunosuke/development/flutter
    • Framework revision adc687823a (5 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kouchiryunosuke/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • EFF23B07-8C7C-462C-BAA0-4823CE73705A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.128

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6
### Plugins
cloud_firestore-1.0.6
cloud_firestore_web-1.0.6
firebase_core-1.0.4
firebase_core_web-1.0.2

**Comment by darshankawar** [comment]
Can't find a similar issue logged already with mentioned error, so labeling it and keeping open for further investigation.

**Comment by eliasjtg** [comment]
Related issue happening to me

I can't run app

```
[+12401 ms] [+12388 ms] Persisting file store
[        ] [  +14 ms] Done persisting file store
[        ] [  +19 ms] "flutter assemble" took 27,308ms.
[   +2 ms] [  +17 ms] Target debug_android_application failed: FileSystemException: Creation failed, path = '/Users/imac/development/projects/boraevolta-flutter/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets' (OS Error: File name too long, errno = 63)
[   +1 ms]            #0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
[        ]            #1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
[        ]            #2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:433:22)
[        ]            #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
[        ]            #4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
[        ]            #5      copyAssets.<anonymous closure> (package:flutter_tools/src/build_system/targets/assets.dart:99:21)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #7      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:87:3)
[        ]            <asynchronous suspension>
[        ]            #8      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:65:34)
[        ]            <asynchronous suspension>
[        ]            #9      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
[        ]            <asynchronous suspension>
[        ]            #11     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #20     main (package:flutter_tools/executable.dart:92:3)
[        ]            <asynchronous suspension>
[        ] [   +7 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:92:3)
[        ]            <asynchronous suspension>
[ +287 ms] [ +261 ms] ensureAnalyticsSent: 260ms
[        ] [   +3 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[+6101 ms] > Task :app:compileFlutterBuildDebug FAILED
[ +110 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/imac/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005
[        ] * What went wrong:
[  +87 ms] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/Users/imac/development/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 42s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 26 actionable tasks: 2 executed, 24 up-to-date
[{"event":"app.progress","params":{"appId":"ec178082-86d1-4d98-889a-fdc290166595","id":"0","progressId":null,"finished":true}}]
[+4360 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:571:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
```

**Comment by JeetSA** [comment]
@eliasjtg ,

I am getting the same error. Did you find any solution for the same?

Can you please guide me here? Thanks in advance.

**Comment by AlexV525** [comment]
> From the below screenshot, you can see folders repeat multiple times with `android/app/build/intermediates/flutter/debug/flutter_assets` under the project root path.

For this situation, I found the difference of `android/build.gradle` between my project with other normal projects, and the diff is (mine compare to others):

```diff
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
- }
- subprojects {
    project.evaluationDependsOn(':app')
}
```

After applying extra `} subprojects {`, the issues seem to be resolved since `android/app/build` will no longer be produced.

**Comment by abdulkazi-kellton** [comment]
I was facing ios/ios/ios/ios issue.
After I added Firebase File in Runner by directly dragging (copy pasting) in ios/Runner directory. 
There was one more ios/ios directory created in ios directory.
I had to manually remove it. After that it is working fine.
