### ISSUE TITLE
debugDumpRenderTree returning null crashes the tool

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#80883]
Looks like we need to make the tool more resilient to getting nulls from the framework.

For example, run Flutter in a way that doesn't hook the binding and try to dump the render tree, and you get a crash:
```
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("data")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      FlutterVmService.flutterDebugDumpRenderTree (package:flutter_tools/src/vmservice.dart:559:20)
<asynchronous suspension>
#2      ResidentHandlers.debugDumpRenderTree (package:flutter_tools/src/resident_runner.dart:713:29)
<asynchronous suspension>
#3      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1668:7)
<asynchronous suspension>

Application finished.

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("data")".
```

(Side note: am I doing something to see both the crash and the message saying I got a crash? Or did we start dumping that at some point? At some point I thought we were making sure to not show the actual stack trace to users.)

**Comment by jonahwilliams** [comment]
TIL if we return null from these methods the vm service client doesn't wrap them in anyway. I guess `null` is legal JSON 🤔

**Comment by jonahwilliams** [comment]
@Hixie how were you able to trigger this? If I update one of these methods to return `null`, I get a type error on the framework side, and then the tool exits:

```
ext.flutter.debugDumpApp: (-32000) Server error
{"exception":"type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast","stack":"#0      new
Future.value (dart:async/future.dart:256:59)\n#1      WidgetsBinding.initServiceExtensions.<anonymous closure>
(package:flutter/src/widgets/binding.dart:396:25)\n#2      WidgetsBinding.initServiceExtensions.<anonymous closure>
(package:flutter/src/widgets/binding.dart:395:19)\n#3      BindingBase.registerServiceExtension.<anonymous closure>
(package:flutter/src/foundation/binding.dart:597:32)\n<asynchronous suspension>\n","method":"ext.flutter.debugDumpApp"}
```

**Comment by Hixie** [comment]
```bash
flutter create dummy_null_crash
cd dummy_null_crash
echo 'void main() { }' > lib/main.dart
flutter run -d flutter-tester
```
...then press `t` when the help message is printed.

**Comment by jonahwilliams** [comment]
of course it is something simple like that lol 🤦‍♂️
