### ISSUE TITLE
ListView goes white when you scroll back to the top

### ISSUE THREAD

**Issue by DavidMihola** [flutter/flutter#8090]
## Steps to Reproduce

Given the following layout:

```dart
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("MissFeed"),
      ),
      body: new MissFeedView(articles),
    );
  }
```

```dart
class MissFeedView extends StatelessWidget {
  final List<FeedArticle> content;

  MissFeedView(this.content);

  @override
  Widget build(BuildContext context) {
    debugPrint("rebuilding MissFeedView");
    return content.isEmpty ?
    new Text("loading") :
    new ListView(
        children: content.map((FeedArticle feedArticle) {
          return new FeedArticleView(feedArticle, (FeedArticle feedArticle) {
            debugPrint("Should navigate to: " + feedArticle.link);
            Navigator.pushNamed(context, feedArticle.link);
          });
        }).toList()
    );
  }
}
```

```dart
class FeedArticleView extends StatelessWidget {

  FeedArticleView(this.feedArticle, this.clickListener);

  final FeedArticle feedArticle;
  final FeedArticleClickListener clickListener;

  @override
  Widget build(BuildContext context) {
    return new GestureDetector(
        onTap: () {
          clickListener(feedArticle);
        },
        child: new Column(
            children: [
              new Container(
                padding: new EdgeInsets.all(6.0),
                child: new Stack(
                    alignment: FractionalOffset.bottomLeft,
                    children: [
                      new AspectRatio(
                        aspectRatio: 1.777,
                        child: new Image.network(
                          feedArticle.imageUrl,
                          fit: ImageFit.fitWidth,
                        ),
                      ),
                      new Container(
                        padding: new EdgeInsets.all(6.0),
                        child: new Container(
                          decoration: new BoxDecoration(
                              backgroundColor: Colors.black54
                          ),
                          padding: new EdgeInsets.all(6.0),
                          child: new Text(feedArticle.titleShort.trim(),
                              style: new TextStyle(
                                  fontSize: 24.0,
                                  color: Colors.white,
                                  fontFamily: "Kabel"
                              )
                          ),
                        ),
                      ),
                    ]
                ),
              ),
              new Container(
                padding: new EdgeInsets.symmetric(horizontal: 18.0),
                child: new Text(feedArticle.title.trim(),
                    textAlign: TextAlign.left,
                    style: new TextStyle(
                        fontSize: 24.0,
                        color: Colors.black,
                        fontFamily: "Kabel"
                    )
                ),
              ),
            ]
        )
    );
  }
}
```

The rendering works fine initially and when scrolling - however, when I first scroll down some way and then up _all the way to the top_ the whole `ListView` is just white, nothing is rendered. If I scroll down again just a tiny bit, everything shows up just fine...

I am guessing that there's something wrong with my item layout, I also have the feeling that fast scrolling/flinging is somewhat "jumpy". I don't mean that in a low-framerate way, but: The list is quite long and even a fling should take a few seconds and maybe not even reach the bottom - instead, however, after a very short interval the list "bumps into" the bottom of the list... Could that be related to the item views not being measured correctly...?

I've uploaded a short video of the app to YouTube - I hope it's available soon: https://www.youtube.com/watch?v=09m3AHJpMJA

## Logs

This is the log output that correlates with the error:

```
I/flutter (20855): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (20855): The following assertion was thrown during performLayout():
I/flutter (20855): 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 484: 'scrollOffsetCorrection ==
I/flutter (20855): 0.0': is not true.
I/flutter (20855): 
I/flutter (20855): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20855): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20855): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20855):   https://github.com/flutter/flutter/issues/new
I/flutter (20855): 
I/flutter (20855): When the exception was thrown, this was the stack:
I/flutter (20855): #2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:484)
I/flutter (20855): #3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:693)
I/flutter (20855): #4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1750)
I/flutter (20855): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1750)
I/flutter (20855): #7      RenderViewportBase2.layoutOneSide (package:flutter/src/rendering/sliver.dart:1228)
I/flutter (20855): #8      RenderViewport2._attemptLayout (package:flutter/src/rendering/sliver.dart:1733)
I/flutter (20855): #9      RenderViewport2.performLayout (package:flutter/src/rendering/sliver.dart:1661)
I/flutter (20855): #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1624)
I/flutter (20855): #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953)
I/flutter (20855): #12     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:223)
I/flutter (20855): #13     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:333)
I/flutter (20855): #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:168)
I/flutter (20855): #15     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676)
I/flutter (20855): #16     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611)
I/flutter (20855): #17     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (20855): (elided 3 frames from class _AssertionError)
I/flutter (20855): 
I/flutter (20855): The following RenderObject was being processed when the exception was fired:
I/flutter (20855):   RenderSliverList relayoutBoundary=up1 NEEDS-LAYOUT
I/flutter (20855):   creator: SliverList ← Viewport2 ← IgnorePointer-[GlobalKey 818076468] ← Listener ←
I/flutter (20855):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState> 962693489] ←
I/flutter (20855):   RepaintBoundary ← CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification2> ←
I/flutter (20855):   GlowingOverscrollIndicator ← Scrollable2 ← ⋯
I/flutter (20855):   parentData: paintOffset=Offset(0.0, 0.0)
I/flutter (20855):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (20855):   scrollOffset: 0.0, remainingPaintExtent: 560.0, crossAxisExtent: 360.0viewportMainAxisExtent:
I/flutter (20855):   560.0)
I/flutter (20855):   geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0, scrollOffsetCorrection:
I/flutter (20855):   -0.0)
I/flutter (20855):   currently live children: 0 to 24
I/flutter (20855): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (20855):   RenderRepaintBoundary relayoutBoundary=up2
I/flutter (20855):     RenderSemanticsGestureHandler relayoutBoundary=up3
I/flutter (20855):       RenderPointerListener relayoutBoundary=up4
I/flutter (20855):         RenderFlex relayoutBoundary=up5
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):   RenderRepaintBoundary relayoutBoundary=up2
I/flutter (20855):     RenderSemanticsGestureHandler relayoutBoundary=up3
I/flutter (20855):       RenderPointerListener relayoutBoundary=up4
I/flutter (20855):         RenderFlex relayoutBoundary=up5
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):   RenderRepaintBoundary relayoutBoundary=up2
I/flutter (20855):     RenderSemanticsGestureHandler relayoutBoundary=up3
I/flutter (20855):       RenderPointerListener relayoutBoundary=up4
I/flutter (20855):         RenderFlex relayoutBoundary=up5
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):   RenderRepaintBoundary relayoutBoundary=up2
I/flutter (20855):     RenderSemanticsGestureHandler relayoutBoundary=up3
I/flutter (20855):       RenderPointerListener relayoutBoundary=up4
I/flutter (20855):         RenderFlex relayoutBoundary=up5
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):   RenderRepaintBoundary relayoutBoundary=up2
I/flutter (20855):     RenderSemanticsGestureHandler relayoutBoundary=up3
I/flutter (20855):       RenderPointerListener relayoutBoundary=up4
I/flutter (20855):         RenderFlex relayoutBoundary=up5
I/flutter (20855):           RenderPadding relayoutBoundary=up6
I/flutter (20855):   ...(descendants list truncated after 25 lines)
I/flutter (20855): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (20855): Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 484: 'scrollOffsetCorrection == 0.0': is not true.
```

Run `flutter analyze` and attach any output of that command also.

```
dmta@elite:~/flutter/neueApp$ flutter analyze
Analyzing lib/main.dart...
No analyzer warnings! (ran in 8.3s)
```

## Flutter Doctor

```
dmta@elite:~/flutter/neueApp$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/dmta/flutter/flutter
    • Framework revision 93c6dbb9f7 (4 hours ago), 2017-02-13 11:14:34
    • Engine revision f306a6f701
    • Tools Dart version 1.22.0-dev.10.6

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/dmta/development/android-sdk-linux
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /home/dmta/development/android-sdk-linux
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[-] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] IntelliJ IDEA Community Edition (version Flutter)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.9.1

[✓] Connected devices
    • ONEPLUS A3003 • 4653feec • android-arm • Android 7.0 (API 24)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by goderbauer** [comment]
I cannot seem to reproduce this anymore. Feel free to reopen with more details if this still occurs.

**Comment by Yacine-Benali** [comment]
I still have this issue, @Hixie have you solved it ?

**Comment by Hixie** [comment]
@Yacine-Benali This issue is closed; if you can still see it please file a new issue with source code demonstrating how to reproduce it. Thanks!
