### ISSUE TITLE
Form with a global key throwing giving `'package:flutter/src/widgets/framework.dart': Failed assertion: line 5062 pos 14: '_dependents.isEmpty': is not true.` error.

### ISSUE THREAD

**Issue by HadyMash** [flutter/flutter#80927]
## Steps to Reproduce

(I posted this in #80773 later on in the thread but then i found that the behaviour is different and gives different errors so I created a new issue)

1. Run `flutter create bug`.
2. Delete everything in main.dart and paste the following:
<details>
<summary>Sample Code</summary>
<br>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: Home()));
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Placeholder(), // TODO add rive background
          Center(
            child: Hero(
              tag: "Welcome Screen Center Box",
              child: Material(
                child: Container(
                  height: 350,
                  width: 350,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(25),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.8),
                        blurRadius: 30.0,
                        spreadRadius: 1.0,
                      )
                    ],
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.max,
                    // mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      SizedBox(height: 35),
                      Container(
                        color: Colors.lightGreen,
                        child: Text(
                          'TEXT',
                          style: TextStyle(fontSize: 40),
                        ),
                      ),
                      // SizedBox(height: 50),
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.max,
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            ElevatedButton.icon(
                              label: Text('Email & Password'),
                              icon: Icon(
                                Icons.email /* TODO Make Icon */,
                                color: Colors.white,
                                size: 28,
                              ),
                              onPressed: () {
                                print('Email & Password');
                                // Navigator.pushNamed(context, '/pageTwo');
                                Navigator.of(context).push(
                                  PageRouteBuilder(
                                    transitionDuration:
                                        Duration(milliseconds: 600),
                                    pageBuilder: (BuildContext context,
                                        Animation<double> animation,
                                        Animation<double> secondaryAnimation) {
                                      return LogInNew();
                                    },
                                    transitionsBuilder: (BuildContext context,
                                        Animation<double> animation,
                                        Animation<double> secondaryAnimation,
                                        Widget child) {
                                      return Align(
                                        child: FadeTransition(
                                          opacity: animation,
                                          child: child,
                                        ),
                                      );
                                    },
                                  ),
                                );
                              },
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class LogInNew extends StatefulWidget {
  String? email;
  String? password;

  LogInNew({this.email, this.password}) {
    email ?? '';
    password ?? '';
  }

  @override
  _LogInNewState createState() => _LogInNewState();
}

class _LogInNewState extends State<LogInNew> {
  // final AuthService _auth = AuthService();
  final _formKey = GlobalKey<FormState>(debugLabel: 'form key');
  FocusNode _emailFocusNode = new FocusNode();
  FocusNode _passwordFocusNode = new FocusNode();
  FocusNode _confirmPasswordFocusNode = new FocusNode();

  Color _getColor(Set<MaterialState> states) {
    const Set<MaterialState> interactiveStates = <MaterialState>{
      MaterialState.pressed,
      MaterialState.hovered,
      MaterialState.focused,
    };
    if (states.any(interactiveStates.contains)) {
      return Colors.white.withOpacity(0.3);
    }
    return Colors.white.withOpacity(0.3);
  }

  ModalRoute? _mountRoute;

  @override
  void didChangeDependencies() {
    _mountRoute ??= ModalRoute.of(context);
    super.didChangeDependencies();
  }

  @override
  void initState() {
    super.initState();

    _emailFocusNode.addListener(() {
      setState(() {});
    });
    _passwordFocusNode.addListener(() {
      setState(() {});
    });
    _confirmPasswordFocusNode.addListener(() {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _formKey.currentState?.dispose();
    _emailFocusNode.dispose();
    _passwordFocusNode.dispose();
    _confirmPasswordFocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Placeholder(), // TODO add rive background
          Center(
            child: Hero(
              tag: "Welcome Screen Center Box",
              child: Container(
                clipBehavior: Clip.antiAlias,
                height: 490,
                width: 380,
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(25),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.8),
                      blurRadius: 30.0,
                      spreadRadius: 1.0,
                    )
                  ],
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.max,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Material(
                      child: Container(
                        color: Theme.of(context).primaryColor,
                        child: Padding(
                          padding: const EdgeInsets.all(4.0),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Row(
                                children: [
                                  IconButton(
                                    icon: Icon(
                                      Icons.arrow_back_ios_rounded,
                                      color: Colors.white,
                                      size: 28.0,
                                    ),
                                    onPressed: () => Navigator.pop(context),
                                    splashColor: Colors.white,
                                  ),
                                  Text(
                                    'Log In',
                                  ),
                                ],
                              ),
                              Padding(
                                padding: const EdgeInsets.fromLTRB(0, 0, 8, 0),
                                child: TextButton.icon(
                                  icon: Icon(Icons.person, color: Colors.white),
                                  label: Text(
                                    'Register',
                                    style: TextStyle(color: Colors.white),
                                  ),
                                  onPressed: () {},
                                  style: ButtonStyle(
                                    overlayColor:
                                        MaterialStateProperty.resolveWith(
                                            _getColor),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                    SizedBox(height: 40),
                    Material(
                      child: Container(
                        color: Colors.lightGreen,
                        child: Text(
                          'TEXT',
                          style: TextStyle(fontSize: 40),
                        ),
                      ),
                    ),
                    // SizedBox(height: 50),
                    Expanded(
                      child: Padding(
                        padding:
                            EdgeInsets.symmetric(vertical: 10, horizontal: 15),
                        child: Form(
                          key: _formKey,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: <Widget>[
                              // * Email
                              Material(
                                child: TextFormField(
                                  // TODO make label change color on focus
                                  // onTap: () => _requestFocus(_emailFocusNode),
                                  focusNode: _emailFocusNode,
                                  onTap: () => setState(() {}),
                                  initialValue: widget.email,
                                  keyboardType: TextInputType.emailAddress,
                                  validator: (val) => val!.isEmpty
                                      ? 'Pleas enter an email'
                                      : null,
                                  autocorrect: false,
                                  onChanged: (val) {
                                    setState(() => widget.email = val);
                                  },
                                ),
                              ),
                              SizedBox(height: 20),
                              Material(
                                child: TextFormField(
                                  // TODO make label change color on focus
                                  // onTap: () => _requestFocus(_passwordFocusNode),
                                  focusNode: _passwordFocusNode,
                                  initialValue: widget.password,
                                  obscureText: true,
                                  validator: (val) => val!.isEmpty
                                      ? 'Password needs to be at least 8 characters'
                                      : null,
                                  autocorrect: false,
                                  onChanged: (val) {
                                    setState(() => widget.password = val);
                                  },
                                ),
                              ),
                              SizedBox(height: 35),
                              ElevatedButton(
                                child: Text('Log In'),
                                onPressed: () => print('log in'),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          )
        ],
      ),
    );
  }
}
```

</details>

3. Run the app
4. See the error when you click the button. (hot reloading seems to remove the red screen).
5. Comment out the `key: _formKey` line and then hot restart the application and then press the button (the error should no longer appear).

**Expected results:** 
The container should animate and and grow as normal. It should do the same behaviour whether the form has a key or not.

**Actual results:** 
When the container is animating, it shows a red box with an error then once the transition is over, the screen goes red. Hot reloading seems to fix the issue.

https://user-images.githubusercontent.com/63734405/115670463-7d546880-a35a-11eb-8afb-dc9b71fa0894.mp4

<details>
<summary>Debug Console Errors</summary>
<br>

```
Restarted application in 789ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Form-[LabeledGlobalKey<FormState>#e27fc form key](state: FormState#39ea6):
'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 135 pos 12: '_route == ModalRoute.of(context)': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
Form-[LabeledGlobalKey<FormState>#e27fc form key]
lib/…/authentication/log_in.dart:225
When the exception was thrown, this was the stack
#2      _WillPopScopeState.didUpdateWidget
package:flutter/…/widgets/will_pop_scope.dart:135
#3      StatefulElement.update
package:flutter/…/widgets/framework.dart:4787
#4      Element.updateChild
package:flutter/…/widgets/framework.dart:3368
#5      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4624
#6      StatefulElement.performRebuild
package:flutter/…/widgets/framework.dart:4772
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5062 pos 14: '_dependents.isEmpty': is not true.
The relevant error-causing widget was
MaterialApp
lib/main.dart:95
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.
════════════════════════════════════════════════════════════════════════════════
Reloaded 0 libraries in 1,202ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKeys detected in widget tree.

The following GlobalKeys were specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The keys were:
- [LabeledGlobalKey<_OverlayEntryWidgetState>#763d7]
  [LabeledGlobalKey<_OverlayEntryWidgetState>#cc240]
  [LabeledGlobalKey<_OverlayEntryWidgetState>#fe297]
This was determined by noticing that after widgets with the above global keys were moved out of their previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widgets were moved, in either case implying that it still thinks that it should have a child with those global keys.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- _Theatre(skipCount: 1, dependencies: [Directionality], renderObject: _RenderTheatre#60d85 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack
#0      BuildOwner.finalizeTree.<anonymous closure>
package:flutter/…/widgets/framework.dart:2905
#1      BuildOwner.finalizeTree
package:flutter/…/widgets/framework.dart:2930
#2      WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:880
#3      RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:328
#4      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1150
...
════════════════════════════════════════════════════════════════════════════════
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
info • Unused import: 'package:releaf/screens/authentication/log_in.dart' • lib/main.dart:5:8 •
          unused_import
   info • Unused import: 'package:releaf/screens/authentication/register.dart' • lib/main.dart:6:8 •
          unused_import
   info • Unused import: 'package:releaf/screens/authentication/veryify.dart' • lib/main.dart:7:8 •
          unused_import
   info • Unused import: 'package:releaf/wrapper.dart' • lib/main.dart:11:8 • unused_import
   info • Unused import: 'package:flutter/scheduler.dart' • lib/main.dart:12:8 • unused_import
   info • Unused import: 'package:firebase_auth/firebase_auth.dart' •
          lib/screens/authentication/log_in.dart:2:8 • unused_import
   info • Unused import: 'package:releaf/services/auth.dart' • lib/screens/authentication/log_in.dart:3:8 •
          unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of
          its instance fields aren't final: LogIn.email, LogIn.password, LogIn.animate •
          lib/screens/authentication/log_in.dart:9:7 • must_be_immutable
   info • Avoid using unnecessary statements • lib/screens/authentication/log_in.dart:15:14 •
          unnecessary_statements
   info • Avoid using unnecessary statements • lib/screens/authentication/log_in.dart:16:17 •
          unnecessary_statements
   info • Avoid using unnecessary statements • lib/screens/authentication/log_in.dart:17:16 •
          unnecessary_statements
   info • Unused import: 'package:firebase_auth/firebase_auth.dart' •
          lib/screens/authentication/register.dart:2:8 • unused_import
   info • Unused import: 'package:releaf/services/auth.dart' • lib/screens/authentication/register.dart:3:8 •
          unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of
          its instance fields aren't final: Register.email, Register.password, Register.animate •
          lib/screens/authentication/register.dart:9:7 • must_be_immutable
   info • Avoid using unnecessary statements • lib/screens/authentication/register.dart:15:14 •
          unnecessary_statements
   info • Avoid using unnecessary statements • lib/screens/authentication/register.dart:16:17 •
          unnecessary_statements
   info • Avoid using unnecessary statements • lib/screens/authentication/register.dart:17:16 •
          unnecessary_statements
   info • Unused import: 'package:provider/provider.dart' • lib/screens/authentication/welcome.dart:2:8 •
          unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/screens/home/dashboard.dart:1:8 •
          unused_import
   info • Unused import: 'package:provider/provider.dart' • lib/screens/home/dashboard.dart:2:8 •
          unused_import
   info • Unused import: 'package:releaf/shared/const/app_theme.dart' • lib/screens/home/dashboard.dart:3:8 •
          unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/screens/home/settings.dart:1:8 • unused_import
   info • Unused import: 'package:provider/provider.dart' • lib/screens/home/settings.dart:2:8 •
          unused_import
   info • Unused import: 'package:releaf/shared/const/app_theme.dart' • lib/screens/home/settings.dart:3:8 •
          unused_import
   info • Unused import: 'package:releaf/services/database.dart' • lib/services/auth.dart:2:8 • unused_import
   info • Unused import: 'package:provider/provider.dart' • lib/services/auth.dart:3:8 • unused_import
   info • Unused import: 'package:provider/provider.dart' • lib/shared/const/app_theme.dart:3:8 •
          unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/shared/const/app_theme.dart:138:19 •
          non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/shared/const/app_theme.dart:139:17 •
          non_constant_identifier_names
   info • Unused import: 'package:provider/provider.dart' • lib/wrapper.dart:2:8 • unused_import
   info • Unused import: 'package:releaf/screens/home/dashboard.dart' • lib/wrapper.dart:4:8 • unused_import

31 issues found. (ran in 3.6s)
```

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.161, on macOS 11.2.3 20D91 darwin-x64, locale en-AU)
    • Flutter version 2.2.0-11.0.pre.161 at /Users/hadymashhour/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ce18d702e9 (3 days ago), 2021-04-19 01:44:02 -0400
    • Engine revision 60f12daf85
    • Dart version 2.14.0 (build 2.14.0-8.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hadymashhour/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 97FDF0AD-EE58-41BA-B064-F1BF43B3CBFD • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      88.0.4324.182

• No issues found!
```

</details>

**Comment by HadyMash** [comment]
I also found out that when I hot reload, go back to the previous page (`navigator.pop(context)`) then route back without hot restarting, I get a different error.

**Comment by darshankawar** [comment]
I see the same behavior and keeping this open for further investigation.

<details>
<summary> console error log </summary>

```

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Form-[LabeledGlobalKey<FormState>#aab18 form key](state: FormState#b03dc):
'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 135 pos 12: '_route == ModalRoute.of(context)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Form-[LabeledGlobalKey<FormState>#aab18 form key] file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:247:32
When the exception was thrown, this was the stack: 
#2      _WillPopScopeState.didUpdateWidget (package:flutter/src/widgets/will_pop_scope.dart:135:12)
#3      StatefulElement.update (package:flutter/src/widgets/framework.dart:4682:57)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#31f39](state: OverlayState#b7952(entries: [OverlayEntry#fc782(opaque: true; maintainState: false), OverlayEntry#39617(opaque: false; maintainState: true), OverlayEntry#5d07c(opaque: true; maintainState: false), OverlayEntry#cbf02(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4954 pos 14: '_dependents.isEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:4:10
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4954:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4956:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:2044:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2046:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
Duplicate GlobalKey detected in widget tree.
====================================================================================================


```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.128

! Doctor found issues in 1 category.

```

</details>

**Comment by khangahs** [comment]
I have a suggestion that Flutter should have a multiple GlobalKey<FormState> or a type of FormState key that can be re-used.
