### ISSUE TITLE
Unable to pass Local Storage in Flutter Webview.

### ISSUE THREAD

**Issue by hussainhyder23** [flutter/flutter#80945]
## Steps to Reproduce

Add Local Storage code in your WebView :
```
 body: WebView(
          initialUrl: _url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (controller) async {

            await cookieManager.setCookies([
              Cookie(cookieName, cookieValue)
                ..domain = domain
                ..expires = DateTime.now().add(Duration(days: 10))
                ..httpOnly = false,
              Cookie(cookieName2, cookieValue2)
                ..domain = domain
                ..expires = DateTime.now().add(Duration(days: 10))
                ..httpOnly = false,
            ]);
            await controller.evaluateJavascript(
                'localStorage["tenant_auth_setting"] = $localStorageCookie2');
```

3. ... 
Running the above could would reproduce the problem.

**Expected results:** 
I want to successfully pass the local storage and have my page load in the WebView
**Actual results:** 

Error I am getting is :

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'localStorage["tenant_auth_setting"] = {
    "id": 1,
    
```

<details>
  <summary>I need to know where I am going wrong and if there is any documentation on how to pass local storage in WebView since I am unable to find one.</summary>

</details>

**Comment by hussainhyder23** [comment]
<img width="931" alt="Screenshot 2021-04-22 at 8 02 21 PM" src="https://user-images.githubusercontent.com/43246921/115732481-a817de80-a3a5-11eb-9621-c7ff1976e931.png">
Please find the screenshot of the error

**Comment by TahaTesser** [comment]
Hi @hussainhyder23 
Is this on Android or iOS? For Android, are using hybrid composition? 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by hussainhyder23** [comment]
Hey @TahaTesser,
This is on iOS.

Flutter doctor -v output :

```

[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.2 at /Users/hyder/Developer/flutter
    • Framework revision 8962f6dc68 (6 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hyder/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ! Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • iPhone 11 Pro Max (mobile) • 351F73C3-5129-4D4E-934C-8AD67C9E5C76 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 85.0.4183.121



```
So I realized that the error I was getting was if I use the evaluateJavascript inside my onWebViewCreated.
I replaced and put the evaluateJavascript inside onPageFinished 


Minimal Reproducible Code :

import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class CookieCheck extends StatefulWidget {
  @override
  _CookieCheckState createState() => _CookieCheckState();
}

class _CookieCheckState extends State<CookieCheck> {
  final Completer<WebViewController> _weBBcontroller =
      Completer<WebViewController>();
  WebViewController _myController;
  var json;
 
 final String localStorageCookie =
      '''{"id":119,"user_info":{"id":4}}''';
 
 var localStorageCookie2 = '''{
    "id": 1,
    "created_at": "2020-10-13T14:12:56.528000+05:30",
    "updated_at": "2021-04-20T13:07:44.277162+05:30",
    "display_name": "example",
    "custom_domain": "example",
    "communication_email": "example@example.com",
    "active": true
    }''';
    
    final String _url = 'https://www.cbit.ac.in';
    
    

Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
          actions: [
            IconButton(
              icon: Icon(Icons.ac_unit),
              onPressed: () async {
                // TEST CODE
                await cookieManager.getCookies(null);
              },
            )
          ],
        ),
        body: WebView(
          initialUrl: _url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (controller) async {
            _myController = controller;
          },
          onPageStarted: (String url) {
            print('Page started loading: $url');
          },
          onPageFinished: (_) async {
            await _myController.evaluateJavascript(
                "window.localStorage.setItem('tenant_auth_setting', $localStorageCookie2);");
             await _myController.evaluateJavascript(
                "window.localStorage.setItem('user_profile', $localStorageCookie1);");
            print('page finished');
          },
        ),
      ),
    );
  }
}

Flutter run--verbose log:

```
[        ] Reloaded 0 libraries in 262ms.
[+6244 ms] flutter: Page started loading: https://www.cbit.ac.in
[+5239 ms] flutter: page finished
[ +101 ms] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating
JavaScript, JavaScript string was: 'window.localStorage.setItem('user_profile',
{"id":119,"user_info":{"id":4,
```

The screenshot of the error :

<img width="896" alt="Screenshot 2021-04-23 at 9 09 24 PM" src="https://user-images.githubusercontent.com/43246921/115895557-3197e100-a478-11eb-8e55-6e54b602a04b.png">

I haven't found any documentation on how to set multiple local storage either.

**Comment by TahaTesser** [comment]
Hi @hussainhyder23 
Thanks for the details, I have edited the code sample so that it can run. 

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: CookieCheck(),
    );
  }
}

class CookieCheck extends StatefulWidget {
  @override
  _CookieCheckState createState() => _CookieCheckState();
}

class _CookieCheckState extends State<CookieCheck> {
  final Completer<WebViewController> _weBBcontroller =
      Completer<WebViewController>();
  WebViewController _myController;
  var json;

  final String localStorageCookie = '''{"id":119,"user_info":{"id":4}}''';

  var localStorageCookie2 = '''{
    "id": 1,
    "created_at": "2020-10-13T14:12:56.528000+05:30",
    "updated_at": "2021-04-20T13:07:44.277162+05:30",
    "display_name": "example",
    "custom_domain": "example",
    "communication_email": "example@example.com",
    "active": true
    }''';

  final String _url = 'https://www.cbit.ac.in';

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
        actions: [
          IconButton(
            icon: Icon(Icons.ac_unit),
            onPressed: () async {
              // TEST CODE
              // await cookieManager.getCookies(null);
            },
          )
        ],
      ),
      body: WebView(
        initialUrl: _url,
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (controller) async {
          _myController = controller;
        },
        onPageStarted: (String url) {
          print('Page started loading: $url');
        },
        onPageFinished: (_) async {
          await _myController.evaluateJavascript(
              "window.localStorage.setItem('tenant_auth_setting', $localStorageCookie2);");
          await _myController.evaluateJavascript(
              "window.localStorage.setItem('user_profile', $localStorageCookie2);");
          print('page finished');
        },
      ),
    );
  }
}
``` 

</details>

```console
flutter: Page started loading: https://www.cbit.ac.in/
flutter: page finished
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
2
Received memory pressure event 2 vm pressure 0
```

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.85

• No issues found!
```
	
</details>


Running the code sample, I don't see any exception with `webview_flutter: ^2.0.4` 
Can you please  try the code sample with latest `webview_flutter`
Thank you

**Comment by hussainhyder23** [comment]
Hi @TahaTesser , The code that you send works perfectly, However, If you replace the localStorageCookie2 with the following values, I get the following error :

change localStorageCookie2 to 

```
final String localStorageTenantAuthSettingsToken = '''
{
  "id": 1,
  "created_at": "2020-10-13T14:12:56.528000+05:30",
  "updated_at": "2021-04-21T15:28:18.597406+05:30",
  "info": {
    "font_family": "'Montserrat', sans-serif"
  },
}''';
```
Notice the Monsterrat is enclosed with ' '. 
This is the API response hence I cannot change it.

I get the following error :-
 
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was: 'window.localStorage.setItem('tenant_auth_settings','"{\n  \"id\": 1,\n  \"created_at\": \"2020-10-13T14:12:56.528000+05:30\",\n  \"updated_at\": \"2021-04-21T15:28:18.597406+05:30\",\n  \"info\": {\n    \"font_family\": \"'Montserrat', sans-serif\"\n  },\n}"');'
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=SyntaxError: Unexpected identifier 'Montserrat'. Expected ')' to end an argument list., WKJavaScriptExceptionColumnNumber=0, WKJavaScriptExceptionSourceURL=https://vercel-flutter-webview-demo.vercel.app/, NSLocalizedDescription=A JavaScript exception occurred}, null)

```
Notice the line number 6 of the above error : It says ```SyntaxError: Unexpected identifier 'Montserrat'. Expected ')' ```



How do I solve this? I tried using backslash as well, that didn't work

**Comment by hussainhyder23** [comment]
Hi @TahaTesser ,

It worked, But I found this to be failing saying an unexpected error has occurred if the json contains a \n.

Here is the JSON :

```
{
  "id": 1,
  "created_at": "2020-10-13T14:12:56.528000+05:30",
  "updated_at": "2021-04-21T15:28:18.597406+05:30",
  "info": {
    "font_family": "Test\n" sans-serif"
  },
}''';

```

**Comment by TahaTesser** [comment]
Hi @hussainhyder23 
Are you sure it `\n` is valid? I see a syntax error when syntax error on both iOS and Android when adding `\n` with `webview_flutter: ^2.0.4` 

**Updated code sample**

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: CookieCheck(),
    );
  }
}

class CookieCheck extends StatefulWidget {
  @override
  _CookieCheckState createState() => _CookieCheckState();
}

class _CookieCheckState extends State<CookieCheck> {
  final Completer<WebViewController> _weBBcontroller =
      Completer<WebViewController>();
  WebViewController _myController;
  var json;

  final String localStorageCookie = '''{"id":119,"user_info":{"id":4}}''';

  var localStorageCookie1 = '''{
    "id": 1,
    "created_at": "2020-10-13T14:12:56.528000+05:30",
    "updated_at": "2021-04-20T13:07:44.277162+05:30",
    "display_name": "example",
    "custom_domain": "example",
    "communication_email": "example@example.com\n",
    "active": true
    }''';

  final String localStorageCookie2 = '''{
    "id": 1,
    "created_at": "2020-10-13T14:12:56.528000+05:30",
    "updated_at": "2021-04-21T15:28:18.597406+05:30",
    "info": {
      "font_family": "Test\n"
    },
  }''';


  final String _url = 'https://www.cbit.ac.in';

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
        actions: [
          IconButton(
            icon: Icon(Icons.ac_unit),
            onPressed: () async {
              // TEST CODE
              // await cookieManager.getCookies(null);
            },
          )
        ],
      ),
      body: WebView(
        initialUrl: _url,
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (controller) async {
          _myController = controller;
        },
        onPageStarted: (String url) {
          print('Page started loading: $url');
        },
        onPageFinished: (_) async {
          await _myController.evaluateJavascript(
              "window.localStorage.setItem('tenant_auth_setting', $localStorageCookie1);");
          // await _myController.evaluateJavascript(
          //     "window.localStorage.setItem('user_profile', $localStorageCookie2);");
          print('page finished');
        },
      ),
    );
  }
}
``` 

</details>

### iOS

```comsole
                    Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred"
UserInfo={WKJavaScriptExceptionLineNumber=6, WKJavaScriptExceptionMessage=SyntaxError: Unexpected EOF,
WKJavaScriptExceptionColumnNumber=0, WKJavaScriptExceptionSourceURL=https://www.cbit.ac.in/, NSLocalizedDescription=A
JavaScript exception occurred}, null)
                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
                    <asynchronous suspension>
                    #2      MethodChannelWebViewPlatform.evaluateJavascript.<anonymous closure> (package:web<…>
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 12 is available at: http://127.0.0.1:53953/oz6Ur3Qrz9A=/
[   +1 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on iPhone 12 is available at:
           http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A53953%2Foz6Ur3Qrz9A%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+5299 ms] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(evaluateJavaScript_failed, Failed
evaluating JavaScript, JavaScript string was: 'window.localStorage.setItem('user_profile', {
                        "id": 1,
                        "created_at": "2020-10-13T14:12:56.528000+05:30",
                        "updated_at": "2021-04-21T15:28:18.597406+05:30",
                        "info": {
                          "font_family": "Test
                    "
                        },
                      });'
                    Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred"
UserInfo={WKJavaScriptExceptionLineNumber=6, WKJavaScriptExceptionMessage=SyntaxError: Unexpected EOF,
WKJavaScriptExceptionColumnNumber=0, WKJavaScriptExceptionSourceURL=https://www.cbit.ac.in/, NSLocalizedDescription=A
JavaScript exception occurred}, null)
                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
                    <asynchronous suspension>
                    #2      MethodChannelWebViewPlatform.evaluateJavascript.<anonymous closure> (package:web<…>
```

### Android
```console
[ +547 ms] I/chromium( 9787): [INFO:CONSOLE(7)] "Uncaught SyntaxError: Invalid or unexpected token", source:
https://www.cbit.ac.in/ (7)
[   +4 ms] I/flutter ( 9787): page finished
```

**Comment by hussainhyder23** [comment]
Thank you so much @TahaTesser
Yes, I noticed that. 
I am basically getting \n in the response from the API
I am replacing that \n with an empty string. 
I am not sure if that's the right way to go.

**Comment by TahaTesser** [comment]
@hussainhyder23 
I'm no expert when it comes to web\cookies, but if it is throwing syntax error, that means it's not valid
Please provide a valid reproducible code sample
Thank you

**Comment by hussainhyder23** [comment]
Hey
@TahaTesser .
No, It's not throwing any error after I remove the \n.
I am replacing that \n with an empty string after getting the response.

I was just wondering if that's the correct thing to do.

**Comment by TahaTesser** [comment]
Hi @hussainhyder23 
I am not sure but it clearly throws syntax error, if there is no issue without `\n`, I feel safe to close the issue
Thank you
