### ISSUE TITLE
Deploying test version of cocoon to flutter-dashboard-dev is not working

### ISSUE THREAD

**Issue by yusufm** [flutter/flutter#80988]
When deploying a test version of the dashboard to flutter-dashboard-dev, the deployed app fails to load test data.

Deployment was performed via:

```~/src/cocoon/app_dart$ dart dev/deploy.dart --project flutter-dashboard-dev --version test```

And the errors seen on the instance are of the type:

```GET /api/public/get-branches - 500.0```

and

```
Uncaught error in request handler: connect failed with timeout
#0      RedisCacheProvider._createContext (package:neat_cache/src/providers/redis.dart:68:7)
<asynchronous suspension>
#1      RedisCacheProvider._withRedis (package:neat_cache/src/providers/redis.dart:113:17)
<asynchronous suspension>
#2      _Entry.get (package:neat_cache/neat_cache.dart:163:15)
<asynchronous suspension>
#3      CacheService.getOrCreate (package:cocoon_service/src/service/cache_service.dart:60:15)
<asynchronous suspension>
#4      CacheRequestHandler.get (package:cocoon_service/src/request_handling/cache_request_handler.dart:57:38)
<asynchronous suspension>
#5      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:22)
<asynchronous suspension>
#6      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:136:9)
<asynchronous suspension>
```

**Comment by CaseyHillers** [comment]
I filed https://github.com/flutter/flutter/issues/80992 for the Cocoon fix

**Comment by godofredoc** [comment]
We need to enable redis on flutter-dashboard-dev

**Comment by CaseyHillers** [comment]
There's a redis instance available. Feel free to reopen if there are still issues.
