### ISSUE TITLE
git cl upload to  doesn't work for non-Googler email addresses

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#81097]
Trying to use `git cl upload` to googlesource repos with a non-Googler email address doesn't appear to be working.

Repro steps:
1. Visit https://flutter-review.googlesource.com/ with a non-googler email address and set up an account.
1. git clone https://flutter.googlesource.com/third_party/libpng
2. Edit README
3. Using a non-Googler email address: `git add README; git commit`
4. git cl upload

I get the following error:
```
remote: PERMISSION_DENIED: The caller does not have permission
remote: [type.googleapis.com/google.rpc.RequestInfo]
remote: request_id: "3385777a3183461aa8c7584a5293ad8f"
remote:
remote: [type.googleapis.com/google.rpc.RequestInfo]
remote: request_id: "9145ae71b74c42d0ae0f6d1d927d2a82"
fatal: unable to access 'https://flutter.googlesource.com/third_party/libpng/': The requested URL returned error: 403
```

Running `git cl creds-check` shows:
```
git is already configured to use your .gitcookies from /Users/cbracken/.gitcookies
Your .netrc and .gitcookies have credentials for these hosts:
                           Host	                   User	 Which file
===============================	=======================	===========
flutter-review.googlesource.com	   git-chris.bracken.jp	.gitcookies
       flutter.googlesource.com	   git-chris.bracken.jp	.gitcookies

No problems detected in your .gitcookies file.
```

**Comment by cbracken** [comment]
Just tried again now with the flutter infra repo and it still appears to be failing. Here's what I get:
```
% git cl upload
Credentials for the following hosts are required:
  flutter-review.googlesource.com
  flutter.googlesource.com
These are read from /Users/cbracken/.gitcookies (or legacy /Users/cbracken/.netrc)
You can (re)generate your credentials by visiting https://flutter-review.googlesource.com/new-password
```

I then follow the instructions and run the command posted at that URL after signing in. Next attempt:

```
% git cl upload
Running Python 2 presubmit upload checks ...
[E2022-03-22 14:51:15,200 41061 4498699776 auth.py] luci-auth token failed: Command 'luci-auth token -scopes https://www.googleapis.com/auth/userinfo.email -json-output -' returned non-zero exit status 1
Not logged in.

Login by running:
   $ luci-auth login

[E2022-03-22 14:51:15,201 41061 4498699776 auth.py] Failed to create access token
** Presubmit ERRORS **
Error in authenticating user.

***************
You are not logged in. Please login first by running:
  luci-auth login -scopes https://www.googleapis.com/auth/userinfo.email
***************

Presubmit checks took 2.7s to calculate.
```

I then run the `luci-auth` command and try again. Third attempt:

```
% git cl upload
Running Python 2 presubmit upload checks ...
Presubmit checks took 2.2s to calculate.
Python 2 presubmit checks passed.

Running Python 3 presubmit upload checks ...
Python 3 presubmit checks passed.

 config/devicelab_staging_config.star | 1 +
 1 file changed, 1 insertion(+)
Waiting for editor...

saving CL description to /Users/cbracken/Developer/depot_tools/.git_cl_description_backup

remote: PERMISSION_DENIED: The caller does not have permission
remote: [type.googleapis.com/google.rpc.RequestInfo]
remote: request_id: "097fc51645144c4f9b2f177b73023965"
remote:
remote: [type.googleapis.com/google.rpc.RequestInfo]
remote: request_id: "10e903ddffdc4f31b6bc2e8e1e33ca75"
fatal: unable to access 'https://flutter.googlesource.com/infra/': The requested URL returned error: 403

saving CL description to /Users/cbracken/Developer/depot_tools/.git_cl_description_backup


 ** Content of CL description **
========================================================================
[macOS][m1] Run run_release_test_macos on M1 Macs

In https://github.com/flutter/flutter/pull/100526 we added a release
mode launch test for macOS desktop Flutter apps. This was to verify that
universal binaries launch and run on both x86_64 Macs and arm64 Macs and
prevents a regression of an M1-specific release mode crasher we were
experiencing.

Issue: https://github.com/flutter/flutter/issues/97977
Issue: https://github.com/flutter/flutter/issues/100348
Change-Id: I802b29381b0e13160e7b840db7cf3da918e9aa9b
Umbrella issue: https://github.com/flutter/flutter/issues/60113
========================================================================

Failed to create a change. Please examine output above for the reason of the failure.
For emergencies, Googlers can escalate to go/gob-support or go/notify#gob
Hint: run command below to diagnose common Git/Gerrit credential problems:
  git cl creds-check

If git-cl is not working correctly, file a bug under the Infra>SDK component including the files below.
Review the files before upload, since they might contain sensitive information.
Set the Restrict-View-Google label so that they are not publicly accessible.

The traces of this git-cl execution have been recorded at:
  /Users/cbracken/Developer/depot_tools/traces/20220322T145549.847721-traces.zip
Copies of your gitcookies file and git config have been recorded at:
  /Users/cbracken/Developer/depot_tools/traces/20220322T145549.847721-git-info.zip
```

Running `git cl creds-check` gives:
```
% git cl creds-check
git is already configured to use your .gitcookies from /Users/cbracken/.gitcookies
Your .netrc and .gitcookies have credentials for these hosts:
                           Host	                User	 Which file
===============================	====================	===========
flutter-review.googlesource.com	git-chris.bracken.jp	.gitcookies
       flutter.googlesource.com	git-chris.bracken.jp	.gitcookies

No problems detected in your .gitcookies file.
```

**Comment by godofredoc** [comment]
@keyonghan can you please take a look?

**Comment by CaseyHillers** [comment]
Based on the status, the next best steps are to enable the 30 minute mirrors to these repos. @cbracken feel free to ping if you  want CL access to these repos.

**Comment by cbracken** [comment]
@CaseyHillers the issue is with making recipe/infra changes. My understanding is that everyone should be able to upload CLs for reviews, but perhaps only Googlers can approve them (I'd be fine with that). Currently, I can't actually upload changes unless it's under my @google.com account.

**Comment by godofredoc** [comment]
CL for providing the right permissions was sent for review.

**Comment by cbracken** [comment]
Looks like https://flutter-review.googlesource.com/c/Public-Projects/+/28908 has landed.

I tried again just now and am getting 403 error on CL upload to flutter/infra. Log:

<details>

```
% git cl upload
Running Python 2 presubmit upload checks ...
Presubmit checks took 1.3s to calculate.
Python 2 presubmit checks passed.

Running Python 3 presubmit upload checks ...
Python 3 presubmit checks passed.

 README.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
Waiting for editor...

saving CL description to /Users/chris/Developer/depot_tools/.git_cl_description_backup

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 350 bytes | 350.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2)
remote: Processing changes: refs: 1, done
To https://flutter.googlesource.com/infra
 ! [remote rejected] a92755f11ba79bf639489d44f7fe7ad6023db573 -> refs/for/refs/heads/main%wip,m=Initial_upload (prohibited by Gerrit: not permitted: read on refs/heads/main)
error: failed to push some refs to 'https://flutter.googlesource.com/infra'
Your Gerrit credentials might be misconfigured.
Try:
  git cl creds-check
Traceback (most recent call last):
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 2288, in _RunGitPushWithTraces
    push_stdout = gclient_utils.CheckCallAndFilter(
  File "/Users/chris/Developer/depot_tools/gclient_utils.py", line 682, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(
subprocess2.CalledProcessError: Command 'git push https://flutter.googlesource.com/infra a92755f11ba79bf639489d44f7fe7ad6023db573:refs/for/refs/heads/main%wip,m=Initial_upload' returned non-zero exit status 1
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 350 bytes | 350.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2)
remote: Processing changes: refs: 1, done
To https://flutter.googlesource.com/infra
 ! [remote rejected] a92755f11ba79bf639489d44f7fe7ad6023db573 -> refs/for/refs/heads/main%wip,m=Initial_upload (prohibited by Gerrit: not permitted: read on refs/heads/main)
error: failed to push some refs to 'https://flutter.googlesource.com/infra'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 2361, in CMDUploadChange
    return self._CMDUploadChange(options, git_diff_args, custom_cl_base,
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 2567, in _CMDUploadChange
    push_stdout = self._RunGitPushWithTraces(refspec, refspec_opts,
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 2320, in _RunGitPushWithTraces
    raise GitPushError(
GitPushError: Failed to create a change. Please examine output above for the reason of the failure.
For emergencies, Googlers can escalate to go/gob-support or go/notify#gob
Hint: run command below to diagnose common Git/Gerrit credential problems:
  git cl creds-check

If git-cl is not working correctly, file a bug under the Infra>SDK component including the files below.
Review the files before upload, since they might contain sensitive information.
Set the Restrict-View-Google label so that they are not publicly accessible.

The traces of this git-cl execution have been recorded at:
  /Users/chris/Developer/depot_tools/traces/20220411T104259.928553-traces.zip
Copies of your gitcookies file and git config have been recorded at:
  /Users/chris/Developer/depot_tools/traces/20220411T104259.928553-git-info.zip


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chris/Developer/depot_tools/metrics.py", line 291, in print_notice_and_exit
    yield
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 5623, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 5605, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/chris/Developer/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 4416, in CMDupload
    ret = cl.CMDUpload(options, args, orig_args)
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 1556, in CMDUpload
    ret = self.CMDUploadChange(
  File "/Users/chris/Developer/depot_tools/git_cl.py", line 2369, in CMDUploadChange
    project_head = gerrit_util.GetProjectHead(self._gerrit_host,
  File "/Users/chris/Developer/depot_tools/gerrit_util.py", line 1098, in GetProjectHead
    return ReadHttpJsonResponse(conn, accept_statuses=[200])
  File "/Users/chris/Developer/depot_tools/gerrit_util.py", line 494, in ReadHttpJsonResponse
    fh = ReadHttpResponse(conn, accept_statuses)
  File "/Users/chris/Developer/depot_tools/gerrit_util.py", line 489, in ReadHttpResponse
    raise GerritError(response.status, reason)
gerrit_util.GerritError: (403) Forbidden: not permitted: read on refs/heads/main

% git cl creds-check
git is already configured to use your .gitcookies from /Users/chris/.gitcookies
Your .netrc and .gitcookies have credentials for these hosts:
                           Host	                User	 Which file
===============================	====================	===========
flutter-review.googlesource.com	git-chris.bracken.jp	.gitcookies
       flutter.googlesource.com	git-chris.bracken.jp	.gitcookies

No problems detected in your .gitcookies file.

% luci-auth info
Logged in as chris@bracken.jp.

OAuth token details:
  Client ID: [elided].apps.googleusercontent.com
  Scopes:
    https://www.googleapis.com/auth/userinfo.email
    openid
```
</details>
