### ISSUE TITLE
I'm getting this error while running my flutter app even though I have 8 GB of Ram and most of it is being used by Open JDK Library

### ISSUE THREAD

**Issue by sanjitsarkar** [flutter/flutter#81113]
flutter run --verbose

<details>
<summary> flutter run --verbose </summary>

```

[  +70 ms] executing: [E:\Flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +39 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] adc687823a831bbebe28bdccfac1a628ca621513
[        ] executing: [E:\Flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +29 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +35 ms] executing: [E:\Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [E:\Flutter/] git ls-remote --get-url origin     
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [E:\Flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +54 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] executing: E:\Programs\Android\Android\Sdk\platform-tools\adb.exe devices -l
[  +34 ms] List of devices attached
           21db97f39906           device product:pine model:Redmi_7A device:pine transport_id:3
[   +5 ms] E:\Programs\Android\Android\Sdk\platform-tools\adb.exe -s 21db97f39906 shell getprop
[  +78 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +80 ms] Skipping pub get: version match.
[ +112 ms] Generating
C:\Users\Administrator\Desktop\ThisPC\sports\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +46 ms] ro.hardware = qcom
[  +32 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +6 ms] complete
[   +5 ms] Launching lib\main.dart on Redmi 7A in debug mode...
[   +5 ms] E:\Flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
E:\Flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
E:\Flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\ADMINI~1\AppData\Local\Temp\flutter_tools.da0f3712\flutter_tool.165af6ed\app.dill --packages
C:\Users\Administrator\Desktop\ThisPC\sports\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[  +17 ms] executing: E:\Programs\Android\Android\Sdk\platform-tools\adb.exe -s 21db97f39906 shell -x logcat -v time
-t 1
[  +17 ms] <- compile package:sports/main.dart
[ +177 ms] --------- beginning of main
                    04-24 13:35:47.413 I/TrafficManageService( 3584): mina mTrafficStatsReceiver onReceive
[   +9 ms] executing: E:\Programs\Android\Android\Sdk\platform-tools\adb.exe version
[  +14 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as E:\Programs\Android\Android\Sdk\platform-tools\adb.exe
[   +3 ms] executing: E:\Programs\Android\Android\Sdk\platform-tools\adb.exe start-server
[  +17 ms] Building APK
[  +19 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from C:\Users\Administrator\Desktop\ThisPC\sports\android\gradlew.bat.
[   +1 ms] C:\Users\Administrator\Desktop\ThisPC\sports\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +11 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +77 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +3 ms] executing: [C:\Users\Administrator\Desktop\ThisPC\sports\android/]
C:\Users\Administrator\Desktop\ThisPC\sports\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm        
-Ptarget=C:\Users\Administrator\Desktop\ThisPC\sports\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +570 ms] Welcome to Gradle 6.7!
[   +1 ms] Here are the highlights of this release:
[        ]  - File system watching is ready for production use
[        ]  - Declare the version of Java your build requires
[        ]  - Java 15 support
[        ] For more details see https://docs.gradle.org/6.7/release-notes.html
[+1540 ms] ../../third_party/dart/runtime/vm/zone.cc: 94: error: Out of memory.
[   +2 ms] version=2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "windows_x64"
[        ] pid=6868, thread=8332, isolate_group=main(0000017E2DA92260), isolate=main(0000017E29D1E450)
[        ] isolate_instructions=17e2cd10000, vm_instructions=7ff7da11f960
[        ]   pc 0x00007ff7da2a0fb2 fp 0x00000016218fe690 Unknown symbol
[        ] -- End of DumpStackTrace
[ +118 ms] The message received from the daemon indicates that the daemon has disappeared.
[   +1 ms] Build request sent: Build{id=9943723e-3409-4842-896f-3f811c290215,
currentDir=C:\Users\Administrator\Desktop\ThisPC\sports\android}
[   +1 ms] Attempting to read last messages from the daemon log...
[        ] Daemon pid: 11484
[        ]   log file: C:\Users\Administrator\.gradle\daemon\6.7\daemon-11484.out.log
[        ] ----- Last  20 lines from daemon log file - daemon-11484.out.log -----
[        ] 2021-04-24T13:35:51.514+0530 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquireexclusive lock on daemon addresses registry.
[   +1 ms] 2021-04-24T13:35:51.514+0530 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on  
daemon addresses registry.
[        ] 2021-04-24T13:35:51.515+0530 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on 
daemon addresses registry.
[   +1 ms] 2021-04-24T13:35:51.515+0530 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting 
idle timer
[   +1 ms] 2021-04-24T13:35:51.515+0530 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is 
running. Sleeping until state changes.
[   +1 ms] 2021-04-24T13:35:51.515+0530 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy]  
Daemon is about to start building Build{id=9943723e-3409-4842-896f-3f811c290215,
currentDir=C:\Users\Administrator\Desktop\ThisPC\sports\android}. Dispatching build started information...
[   +2 ms] 2021-04-24T13:35:51.515+0530 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection]
thread 400: dispatching org.gradle.launcher.daemon.protocol.BuildStarted@189b7c8d
[   +1 ms] 2021-04-24T13:35:51.516+0530 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment]   
Configuring env variables: [PATH, USERDOMAIN_ROAMINGPROFILE, PROCESSOR_LEVEL, SYSTEMDRIVE, SESSIONNAME,
ALLUSERSPROFILE, PROCESSOR_ARCHITECTURE, VSCODE_GIT_IPC_HANDLE, ANDROID_HOME, DRIVERDATA, PROGRAMFILES, COLORTERM,   
PSMODULEPATH, PROGRAMDATA, DIRNAME, USERNAME, VSCODE_GIT_ASKPASS_NODE, PWD, TERM_PROGRAM_VERSION, CMD_LINE_ARGS,     
GIT_ASKPASS, CHROME_CRASHPAD_PIPE_NAME, FPS_BROWSER_USER_PROFILE_STRING, ONEDRIVE, APP_HOME, MINGIT_PATH, PATHEXT,   
SNAPSHOT_PATH, SHARED_BIN, WINDIR, ORIGINAL_XDG_CURRENT_DESKTOP, HOMEPATH, PROCESSOR_IDENTIFIER, PUBLIC, CACHE_DIR,  
EXEPATH, SHLVL, _SKIP, LOCALAPPDATA, COMMONPROGRAMFILES(X86), USERDOMAIN, DART_SDK_PATH,
FPS_BROWSER_APP_PROFILE_STRING, LOGONSERVER, FLUTTER_TOOLS_DIR, JAVA_HOME, PLINK_PROTOCOL, PROMPT, PROGRAMFILES(X86),FLUTTER_ROOT, TERM, LANG, VSCODE_GIT_ASKPASS_MAIN, MSYSTEM, =C:, APPDATA, PROGRAMW6432, SYSTEMROOT, JAVA_EXE,        
VBOX_MSI_INSTALL_PATH, DART, FLUTTER_SUPPRESS_ANALYTICS, MSYS, OS, TERM_PROGRAM, COMPUTERNAME, COMMONPROGRAMW6432,   
COMMONPROGRAMFILES, COMSPEC, PROCESSOR_REVISION, CLASSPATH, APP_BASE_NAME, TEMP, FLUTTER_ALREADY_LOCKED, HOMEDRIVE,  
USERPROFILE, TMP, NUMBER_OF_PROCESSORS, HOME]
[   +6 ms] 2021-04-24T13:35:51.516+0530 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start  
relaying all logs to the client via the connection.
[   +1 ms] 2021-04-24T13:35:51.516+0530 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will  
now receive all logging from the daemon (pid: 11484). The daemon log file:
C:\Users\Administrator\.gradle\daemon\6.7\daemon-11484.out.log
[   +1 ms] 2021-04-24T13:35:51.517+0530 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting   
6th build in daemon [uptime: 9 mins 34.507 secs, performance: 100%]
[   +1 ms] 2021-04-24T13:35:51.517+0530 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has 
started executing the build.
[   +1 ms] 2021-04-24T13:35:51.517+0530 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing buildwith daemon context: DefaultDaemonContext[uid=fb558f48-0f7f-4919-b6d2-67b2cb6c4f0c,javaHome=C:\Program
Files\Android\Android
Studio\jre,daemonRegistryDir=C:\Users\Administrator\.gradle\daemon,pid=11484,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xmx1536M,-Dfile.encoding=windows-1252,-Duser.country=IN,-Duser.language=en,-Duser.variant]
[   +1 ms] Exhausted heap space, trying to allocate 618320 bytes.
[        ] ../../third_party/dart/runtime/vm/object.cc: 2585: error: Out of memory.
[        ] version=2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "windows_x64"
[        ] pid=12172, thread=9220, isolate_group=main(000002B106587840), isolate=main(000002B10656B720)
[        ] isolate_instructions=7ff7da11f950, vm_instructions=7ff7da11f960
[        ]   pc 0x00007ff7da2a0fb2 fp 0x000000e2e5afec10 Unknown symbol
[        ] -- End of DumpStackTrace
[        ] ----- End of the daemon log -----
[        ] JVM crash log found: file:///C:/Users/Administrator/Desktop/ThisPC/sports/android/hs_err_pid11484.log     
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Could not dispatch a message to the daemon.
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log    
output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] Exhausted heap space, trying to allocate 618320 bytes.
[        ] ../../third_party/dart/runtime/vm/object.cc: 2585: error: Out of memory.
[        ] version=2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "windows_x64"
[        ] pid=12172, thread=9220, isolate_group=main(000002B106587840), isolate=main(000002B10656B720)
[   +1 ms] isolate_instructions=7ff7da11f950, vm_instructions=7ff7da11f960
[        ]   pc 0x00007ff7da2a0fb2 fp 0x000000e2e5afec10 Unknown symbol
[        ] -- End of DumpStackTrace
[   +1 ms] > Task :app:compileFlutterBuildDebug
[ +512 ms] Running Gradle task 'assembleDebug'... (completed in 2,893ms)
[+14324 ms] the Dart compiler exited unexpectedly.
[ +384 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                    #1      DefaultResidentCompiler._compile.<anonymous closure>
(package:flutter_tools/src/compile.dart:710:13)
                    #2      _rootRun (dart:async/zone.dart:1346:47)
                    #3      _CustomZone.run (dart:async/zone.dart:1258:19)
                    #4      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
                    #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)     
                    #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
                    #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
                    #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)    
                    #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
                    #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
                    #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:139:11)
                    #12     _SinkTransformerStreamSubscription._handleDone
(dart:async/stream_transformers.dart:132:24)
                    #13     _rootRun (dart:async/zone.dart:1346:47)
                    #14     _CustomZone.run (dart:async/zone.dart:1258:19)
                    #15     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
                    #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)     
                    #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
                    #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
                    #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)    
                    #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
                    #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
                    #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
                    #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
                    #24     _SinkTransformerStreamSubscription._handleDone
(dart:async/stream_transformers.dart:132:24)
                    #25     _rootRun (dart:async/zone.dart:1346:47)
                    #26     _CustomZone.run (dart:async/zone.dart:1258:19)
                    #27     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
                    #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)     
                    #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
                    #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
                    #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:741:19)       
                    #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:596:7)
                    #33     _StreamController.close (dart:async/stream_controller.dart:589:5)
                    #34     _Socket._onData (dart:io-patch/socket_patch.dart:2151:21)
                    #35     _rootRunUnary (dart:async/zone.dart:1370:13)
                    #36     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
                    #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
                    #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
                    #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
                    #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)       
                    #41     _StreamController._add (dart:async/stream_controller.dart:607:7)
                    #42     _StreamController.add (dart:async/stream_controller.dart:554:5)
                    #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1687:35)
                    #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1185:18)
                    #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
                    #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
                    #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
                    #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[   +9 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 18,411ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[   +5 ms] Shutdown hooks complete
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[   +5 ms] exiting with code 1



```

</details>

**Comment by sanjitsarkar** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.264], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

C:\Users\Administrator>flutter doctor --android-licenses`
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.264], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@sanjitsarkar 
Do you have any other JDK applied in environment path ?
From your logs, I see below:

```
Could not dispatch a message to the daemon.
the Dart compiler exited unexpectedly.
```

Can you provide the crash log generated `JVM crash log found: file:///C:/Users/Administrator/Desktop/ThisPC/sports/android/hs_err_pid11484.log` ?
