### ISSUE TITLE
why an Unhandled Exception: type 'StackParentData' is not a subtype of type 'FlexParentData' in type cast  cause CPU usage exceeds 100% in AOT mode

### ISSUE THREAD

**Issue by Beyond-Chao** [flutter/flutter#81139]
<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 1.22.2, on macOS 11.1 20C69, locale zh-Hans-CN)
    • Flutter version 1.22.2 at /Users/beyondchao/flutter
    • Framework revision 84f3d28555 (6 months ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/beyondchao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
```
	
</details>

## exception code :

```dart
Widget _buildBody() {

    List<Widget> widgets = [
    Container(
      color: Colors.blue,
      height: 100,
    )
    ];

    return Stack(children: <Widget>[

      Expanded(
        child: ScrollConfiguration(
          behavior: TicketBehavior(),
          child: ListView(
              physics: AlwaysScrollableScrollPhysics(),
              padding: EdgeInsets.all(0),
              controller: _scrollController,
              children: widgets
          ),
        ),
      ),
    ]);
  }
```

I know Expanded widget only being makes a child of a [Row], [Column], or [Flex]，**But why in AOT mode this unhandled exception print log infinitely and cause CPU usage exceeds 100% as shown below.**

```shell
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'StackParentData' is not a subtype of type 'FlexParentData' in type cast
#0Flexible.applyParentData (package:flutter/src/widgets/basic.dart:4546)
#1RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5788)
#2RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5808)
#3RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5501)
#4SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6117)
#5Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569)
#6Element.updateChild (package:flutter/src/widgets/framework.dart:3327)
#7ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652)
#8StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800)
#9Element.rebuild (package:flutter/src/widgets/framework.dart:4343)
#10 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606)
#11 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791)
#12 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601)
#13 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569)

#393Element.updateChild (package:flutter/src/widgets/fra<…>
2021-04-23 13:25:54.433010+0800 Runner[2186:635828] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: type 'StackParentData' is not a subtype of type 'FlexParentData' in type cast
#0Flexible.applyParentData (package:flutter/src/widgets/basic.dart:4546)
```

![image](https://user-images.githubusercontent.com/14927052/115978902-2eeed600-a5b5-11eb-84f9-2ac86bac73cf.png)

the problem is triggered by this statement ```renderObject.parentData as FlexParentData;``` in basic.dart  file  Flexible class,   **I'm curious about what causes this kind of loop effect in AOP mode, thanks in advance !**

```dart
  void applyParentData(RenderObject renderObject) {
    assert(renderObject.parentData is FlexParentData);
    final FlexParentData parentData = renderObject.parentData as FlexParentData;
    bool needsLayout = false;



    if (needsLayout) {
      final AbstractNode targetParent = renderObject.parent;
      if (targetParent is RenderObject)
        targetParent.markNeedsLayout();
    }
  }
```

**Comment by TahaTesser** [comment]
Hi @Beyond-Chao 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
