### ISSUE TITLE
Unable to run and here are the detailed logs when trying to run a project

### ISSUE THREAD

**Issue by gavishgulati** [flutter/flutter#81136]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ArgumentError: Invalid argument(s): Cannot find executable for reg.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:65:30)
#2      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:618:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:618:12)
#5      MicrosoftEdgeDevice._getSdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:270:56)
#6      MicrosoftEdgeDevice.sdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:267:78)
#7      MicrosoftEdgeDevice._meetsVersionConstraint (package:flutter_tools/src/web/web_device.dart:258:38)
#8      WebDevices.pollingGetDevices (package:flutter_tools/src/web/web_device.dart:352:30)
#9      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:511:60)
#10     PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:501:12)
#11     DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:186:20)
#12     DeviceManager.getDevices (package:flutter_tools/src/device.dart:175:11)
#13     DeviceBasedDevelopmentArtifacts.requiredArtifacts (package:flutter_tools/src/runner/flutter_command.dart:1331:62)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1110:43)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#23     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#26     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#27     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#28     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.18363.1440], locale en-US)
    • Flutter version 2.0.0 at C:\Users\ggulati\flutter
    • Framework revision 60bd88df91 (7 weeks ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ggulati\AppData\Local\Android\android-sdk
    • Platform android-30, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\ggulati\AppData\Local\Android\android-sdk
    • Java binary at: C:\androidStudio\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] Android Studio (version 3.2)
    • Android Studio at C:\androidStudio\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\ggulati\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Invalid argument(s): Cannot find executable for reg.
    • #0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
      #1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:65:30)
      #2      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:618:33)
      #3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
      #4      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:618:12)
      #5      MicrosoftEdgeDevice._getSdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:270:56)
      #6      MicrosoftEdgeDevice.sdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:267:78)
      #7      MicrosoftEdgeDevice._meetsVersionConstraint (package:flutter_tools/src/web/web_device.dart:258:38)
      #8      WebDevices.pollingGetDevices (package:flutter_tools/src/web/web_device.dart:352:30)
      #9      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:511:60)
      #10     PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:501:12)
      #11     DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:186:20)
      #12     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:802:55)
      #13     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #14     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #15     _rootRun (dart:async/zone.dart:1354:13)
      #16     _CustomZone.run (dart:async/zone.dart:1258:19)
      #17     _runZoned (dart:async/zone.dart:1788:10)
      #18     runZonedGuarded (dart:async/zone.dart:1776:12)
      #19     runZoned (dart:async/zone.dart:1707:12)
      #20     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #21     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:203:9)
      #22     Doctor.diagnose (package:flutter_tools/src/doctor.dart:307:47)
      #23     _doctorText (package:flutter_tools/runner.dart:235:18)
      #24     _handleToolError (package:flutter_tools/runner.dart:160:27)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:79:16)
      <asynchronous suspension>
      #26     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
      <asynchronous suspension>
      #27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #28     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
      <asynchronous suspension>
      #29     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:90:3)
      <asynchronous suspension>


! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@gavishgulati 
Does `reg` exist ? What terminal are you using to run the command ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
