### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The device is not ready., errno = 21

### ISSUE THREAD

**Issue by UmairWarriach** [flutter/flutter#81146]
## Command
```
flutter downgrade v1.22.6
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: The device is not ready.
, errno = 21
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:479:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:478:12)
#5      PubDependencies.isUpToDate (package:flutter_tools/src/flutter_cache.dart:105:57)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:546:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1159:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1059:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.191, on Microsoft Windows [Version 10.0.19042.631], locale en-US)
    • Flutter version 2.2.0-11.0.pre.191 at D:\Android\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff54fc6da8 (4 days ago), 2021-04-21 20:09:02 +0530
    • Engine revision 610fd039ae
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\umair\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 84.0.522.52

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by kcibdev** [comment]
Is there any update on this cause all what is been happening is just redirecting us to this page without any solution @darshankawar @iapicca @pedromassangocode 
This is my issue https://github.com/flutter/flutter/issues/118165

**Comment by kcibdev** [comment]
> Is there any update on this cause all what is been happening is just redirecting us to this page without any solution @darshankawar @iapicca @pedromassangocode This is my issue #118165

for those that might be facing this i fixed mine here https://github.com/flutter/flutter/issues/118165

**Comment by matanlurey** [comment]
Closing in favor of more recent bugs that are reproducible (this one is neither).
