### ISSUE TITLE
Auto-generated ScrollController attached to multiple scroll views in TabBarView's keep-alive tabs

### ISSUE THREAD

**Issue by narumishi** [flutter/flutter#81152]
## Steps to Reproduce
Recently, scroll views will auto generate a scrollbar. (?) In `TabBarView`, if we set every tab **keep-alive**, then the auto generated scrollbar controller will attached to every tab. Then it will raise `ScrollController attached to multiple scroll views.` if we drag scrollbar **after switching tab once**.

<details>
  <summary>example code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        bottom: TabBar(
          tabs: [Tab(text: 'TAB A'), Tab(text: 'TAB B')],
          controller: _tabController,
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          KeepAliveBuilder(builder: (ctx) => ChildPage(name: 'Tab A')),
          KeepAliveBuilder(builder: (ctx) => ChildPage(name: 'Tab B')),
        ],
      ),
    );
  }
}

class ChildPage extends StatelessWidget {
  final String name;

  const ChildPage({Key? key, required this.name}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: List.generate(
        20,
        (index) => ListTile(
          title: Text('$name: $index'),
        ),
      ),
    );
  }
}

class KeepAliveBuilder extends StatefulWidget {
  final WidgetBuilder builder;
  final bool wantKeepAlive;

  const KeepAliveBuilder(
      {Key? key, required this.builder, this.wantKeepAlive = true})
      : super(key: key);

  @override
  _KeepAliveBuilderState createState() => _KeepAliveBuilderState(wantKeepAlive);
}

class _KeepAliveBuilderState extends State<KeepAliveBuilder>
    with AutomaticKeepAliveClientMixin {
  bool _wantKeepAlive;

  _KeepAliveBuilderState(this._wantKeepAlive);

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return widget.builder(context);
  }

  @override
  bool get wantKeepAlive => _wantKeepAlive;
}
```
</details>

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

error

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:109:12)
#3      RawScrollbarState.getScrollbarDirection (package:flutter/src/widgets/scrollbar.dart:1080:34)
#4      RawScrollbarState.handleThumbPressStart (package:flutter/src/widgets/scrollbar.dart:1103:29)
#5      _MaterialScrollbarState.handleThumbPressStart (package:flutter/src/material/scrollbar.dart:388:11)
#6      RawScrollbarState._gestures.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1239:74)
...
Handler: "onLongPressStart"
Recognizer: _ThumbPressGestureRecognizer#0c12c
  debugOwner: _MaterialScrollbarState#6eb61(tickers: tracking 2 tickers)
  state: possible
====================================================================================================

```

flutter doctor -v
```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.274, on macOS 11.2.2 20D80 darwin-x64, locale en-CN)
    • Flutter version 2.2.0-11.0.pre.274 at /Users/narumi/Library/flutter-master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1f73a1065 (33 hours ago), 2021-04-24 00:44:02 -0400
    • Engine revision eba9efd1c3
    • Dart version 2.14.0 (build 2.14.0-37.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/narumi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/narumi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Users/narumi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/202.7094744/Android Studio 4.2
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/narumi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

```

</details>

**Comment by pedromassangocode** [comment]
Hi @narumishi 
Can you please provide the steps to reproduce this issue? I cannot reproduce this on latest master/stable channel.
Thank you

**Comment by narumishi** [comment]
@pedromassango please use the example code and build on **desktop**(macOS/windows tested). It seems scrollbar is not auto implemented on mobile.

**Comment by pedromassangocode** [comment]
Hi @narumishi 
I just build on MacOS desktop but I was unable to reproduce this issue (I got no crash). Tested on master and stable channel.

**Comment by narumishi** [comment]
@pedromassangocode 
So strange, I have tested on both macOS and windows, debug/release mode, master channel. And they all raise such error.

Please check the detail steps:
1. Run with example code
2. There are two tabs, every tab is a `ListView` with an **auto-generated scrollbar** which will be visible when scrolling.
3. Don't switch tab.  In **Tab A**, drag **scrollbar**, it works.
4. Switch to **Tab B**, drag **scrollbar**, error raised.
5. Back to **Tab A**, drag again, error raised.

**Comment by pedromassangocode** [comment]
Thanks.

I was able to reproduce the issue following the steps in the comment above.

<details>
<summary>logs</summary>

```bash
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 109 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:109:12)
#3      RawScrollbarState.getScrollbarDirection (package:flutter/src/widgets/scrollbar.dart:1080:34)
#4      RawScrollbarState.handleThumbPressStart (package:flutter/src/widgets/scrollbar.dart:1103:29)
#5      _MaterialScrollbarState.handleThumbPressStart (package:flutter/src/material/scrollbar.dart:388:11)
#6      RawScrollbarState._gestures.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1239:74)
...
Handler: "onLongPressStart"
Recognizer: _ThumbPressGestureRecognizer#9cbee
  debugOwner: _MaterialScrollbarState#8e7ff(tickers: tracking 2 tickers)
  state: possible
====================================================================================================
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.3.0-1.0.pre.101, on macOS 11.2.3 20D91 darwin-x64, locale en-AO)
    • Flutter version 2.3.0-1.0.pre.101 at /Users/pedromassango/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff2dde2c7f (68 minutes ago), 2021-04-26 22:35:45 -0700
    • Engine revision afd9c397a5
    • Dart version 2.14.0 (build 2.14.0-43.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pedromassango/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7179

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```

</details>

**Comment by Piinks** [comment]
Hey there @narumishi thanks for filing this issue!

I don't think this has to do with the fallback `ScrollController` (the automatically generated one) in `Scrollable`, that would create a unique `ScrollController` for each `Scrollable`.

It looks like the issue may be that all three of your `Scrollable`s are using the `PrimaryScrollController`, since the `ListView`s are in the vertical axis and do not have an assigned `ScrollController`.

Looking to confirm this now..

**Comment by Piinks** [comment]
Confirmed, this is not caused by the auto-generated scroll controller, but it is the PrimaryScrollController that all three tabs are sharing. The scrollbar that has been applied on desktop exposes this configuration.

This would probably cause issues elsewhere, as all three ListViews are being kept alive and are attached to the ScrollController at the same time. There are a couple of ways to remedy this:

- provide a unique scroll controller to each ListView
- Or, if you would rather just remove the scrollbar that exposes this, see [this guide](https://flutter.dev/docs/release/breaking-changes/default-desktop-scrollbars) for multiple options to configure a scroll behavior

**Comment by narumishi** [comment]
@Piinks Thanks for your analysis. 

I tested something more. Just place two `ListView` inside one `Column`, without keep-alive code. It will also raise the same error. 

```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Column(
        children: [
          Expanded(
            child: ListView(
              children: List.generate(20, (index) => Text('UP: $index')),
            ),
          ),
          Expanded(
            child: ListView(
              children: List.generate(20, (index) => Text('DOWN: $index')),
            ),
          ),
        ],
      ),
    );
  }
}
```

Maybe keep-alive is not a frequently used case, but multiple scrollable widgets inside one simple page should always work with default scroll behavior. 

Although I know that assigning controller to every scrollable widget is always working, I think it's really annoying if I just want the default scroll behavior works, don't need any specific controls.

**Comment by Piinks** [comment]
> I tested something more. Just place two `ListView` inside one `Column`, without keep-alive code. It will also raise the same error.

Hi @narumishi this is an example of the same issue - more than one scrollable is using the same scroll controller at the same time, here it is the PrimaryScrollController. 

> Maybe keep-alive is not a frequently used case, but multiple scrollable widgets inside one simple page should always work with default scroll behavior.

I am not sure this is an issue with the scroll behavior though, as it cannot determine that there are multiple scroll views on the same page, or that they are currently all sharing the same scroll controller. This may be something we just need to document in more detail regarding PrimaryScrollControllers and how they are automatically assigned in the vertical axis. If none of these were using the PrimaryScrollController, then the auto-generated scroll controller in Scrollable would eliminate this issue all together since each would be unique.

> Although I know that assigning controller to every scrollable widget is always working, I think it's really annoying if I just want the default scroll behavior works, don't need any specific controls.

Fortunately not all of the scroll views need a unique scroll controller in your sample here, one can still use the PrimaryScrollController and the other can use a provided one.

**Comment by narumishi** [comment]
@Piinks I understand the reason, and there is one thing I'm not sure: 
- Does this issue should/will be fixed in future to make scroll controller unique in vertical axis? If so, I'm glad to wait for official fix.
- Or just document in more detail for `PrimaryScrollController`? If so, I need to migrate my code ASAP.

**Comment by Piinks** [comment]
Right now I do not think we'll be changing the default behavior of PrimaryScrollController, a lot of folks are probably depending on its current behavior. We can definitely explore it, but if your need is time sensitive I would say not to count on it very soon. :)

I have seen this error message somewhat regularly. I think in addition to documentation, we should definitely see about making the error message more specific when the PrimaryScrollController is at issue (rather than the same message for both primary and user-supplied scroll controllers). That would probably go a long way in helping people identify where the issue in their code is. If you search for the 'attached to multiple scroll views' error message, there are several different use cases where this pops up, especially on stackoverflow where there should be guidance on how to mitigate if the migration suggestions above are not suitable to your use case.

**Comment by narumishi** [comment]
Got it. Thanks for your explanation. That's a good idea to specific the detailed error message.

**Comment by narumishi** [comment]
@Piinks Hello, recently, I encountered the similar issue again. Even when I didn't make tabs keep-alive, `The provided ScrollController is currently attached to more than one ScrollPosition.` is still raised when switch between tabs and scroll at same time.

It is recommended to reproduce the problem on desktop(macOS for me). Scroll vertical and horizontal the same time, Try a few more times.

It seems when you switch tab while vertical scrolling is going on, the `PrimaryScrollController ` is assigned to new tab' listview before the previous tab dispose.

<details>
<summary>Error</summary>

```

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1315:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1339:6)
#2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1257:14)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:814:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:748:5)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:611:12)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:462:12)
#8      RawScrollbarState._handleScrollNotification (package:flutter/src/widgets/scrollbar.dart:1567:37)
#9      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:206:42)
#10     Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:122:20)
#11     ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
#12     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4133:39)
#13     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:138:13)
#14     ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:94:92)
#15     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:899:15)
#16     ScrollPositionWithSingleContext.pointerScroll (package:flutter/src/widgets/scroll_position_with_single_context.dart:221:7)
#17     ScrollableState._handlePointerScroll (package:flutter/src/widgets/scrollable.dart:718:16)
#18     PointerSignalResolver.resolve (package:flutter/src/gestures/pointer_signal_resolver.dart:199:32)
#19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:446:29)
#20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#22     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#23     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#29     _invoke1 (dart:ui/hooks.dart:185:10)
#30     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#31     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
The AnimationController notifying status listeners was: AnimationController#d7968(▶ 0.000)
====================================================================================================
```
</details>

<details>
<summary>example code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: HomePage());
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage>
    with SingleTickerProviderStateMixin {
  final int tabNum = 3;
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: tabNum, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test'),
        bottom: TabBar(
          controller: _tabController,
          tabs: List.generate(tabNum, (index) => Tab(text: 'Tab $index')),
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: List.generate(tabNum, (index) => OneTab(index: index)),
      ),
    );
  }
}

class OneTab extends StatefulWidget {
  final int index;

  const OneTab({Key? key, this.index = 0}) : super(key: key);

  @override
  _OneTabState createState() => _OneTabState();
}

class _OneTabState extends State<OneTab> {
  @override
  Widget build(BuildContext context) {
    return ListView(
      children: List.generate(
        50,
        (index) => ListTile(
          title: Text('Tab ${widget.index} Item $index'),
        ),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 2.5.0-5.1.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-CN)
    • Flutter version 2.5.0-5.1.pre at /Users/narumi/Library/flutter-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 65cf7de5f4 (3 days ago), 2021-08-11 15:48:01 -0700
    • Engine revision fbeb7e22bd
    • Dart version 2.14.0 (build 2.14.0-377.4.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/narumi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/narumi/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • Narumi's Phone (mobile) • 58677d0fc8984330404af9009f82e7795fc678d1 • ios            • iOS 14.1 18A8395
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 11.3.1 20E241
      darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```
</details>

**Comment by woutervanwijk** [comment]
I encounter this issue too

**Comment by topex-psy** [comment]
> @pedromassangocode So strange, I have tested on both macOS and windows, debug/release mode, master channel. And they all raise such error.
> 
> Please check the detail steps:
> 
> 1. Run with example code
> 2. There are two tabs, every tab is a `ListView` with an **auto-generated scrollbar** which will be visible when scrolling.
> 3. Don't switch tab.  In **Tab A**, drag **scrollbar**, it works.
> 4. Switch to **Tab B**, drag **scrollbar**, error raised.
> 5. Back to **Tab A**, drag again, error raised.

I have same issue in my flutter web exactly like this. It's `TabBarView` containing 3 `SingleChildScrollView`s which each one have their own scroll controller.

**Comment by SittiphanSittisak** [comment]
I face this issue with copying your example code in your [doc](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html).

https://github.com/flutter/flutter/assets/59549741/ff99a4b7-0ace-437e-8398-c0ebf48b6e5d

Is it dangerous?

**Comment by AhmedLSayed9** [comment]
This issue has been here for a long time and break other things.

@Piinks Is this related to https://github.com/flutter/flutter/issues/40740 ?

**Comment by DavidOrakpo** [comment]
Commenting to keep this issue alive. Also running into the same issue using Tab Views with lists that scroll vertically, while the tab is allowed to scroll horizontally

**Comment by qwezey** [comment]
same issue here

**Comment by Piinks** [comment]
Per our wiki on [issue hygiene](https://github.com/flutter/flutter/tree/master/docs/contributing/issue_hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-issues-or-prs):

> Do not add "me too" or "same" or "is there an update" comments to issues or PRs

Continued posts like this are not constructive and will result in restrictions to make further comments in this repository.

**Comment by AhmedLSayed9** [comment]
I can't reproduce this anymore at latest stable version.
I think this is fixed by #157756

**Comment by kobi666** [comment]
same behavior is replicated on v3.29.1

**Comment by AhmedLSayed9** [comment]
> same behavior is replicated on v3.29.1

I've testing this on Flutter v3.29.2, on both iOS & macOS (debug mode) and can't get any errors.

**Comment by jasminder** [comment]
There are deeper issues related to this:
I am trying to scroll to a position. I have a NestedScrollView, with a tabbarbview. So, if I am on the first tab. and scroll it using an action. It works on that tab. However, if I change the tabbar and come back to the main tab and then try to scroll again. It gives me the error that:
ScrollController attached to multiple scroll views.

So, I guess both tabbarviews have this controller. I am using the following code to access the scrollController inside the body of NestedScrollView:
final innerScrollController = PrimaryScrollController.of(context);

**Comment by jasminder** [comment]
The workaround isnt that good tbh. It works, but it completely changes the scroll behaviour. While scrolling back to top, headers starts appearing way before. Also, lets say, you have re ordering feature, while trying to drag the row o top or bottom, it only takes you to a certain limit and doesnt scroll body to show more of the scroll body to place that row.

**Comment by surajgju** [comment]
Hi @narumi147 and Flutter team 👋

I have identified the root cause of this issue and developed a fix with full test coverage.

### Root Cause
When `TabBarView` children use `AutomaticKeepAliveClientMixin`, inactive tabs remain mounted in the element tree. Previously, `TabBarView` passed down the ancestor `PrimaryScrollController` to all tabs without scoping. As a result, scroll views in both active and kept-alive inactive tabs attached to the ancestor `PrimaryScrollController` simultaneously. When any interaction accessed `PrimaryScrollController.position` (such as desktop scrollbar dragging or iOS status-bar tap), an assertion error was thrown: `ScrollController attached to multiple scroll views.`

### Solution
Scope `PrimaryScrollController` inside `_TabBarViewState._updateChildren()`:
- **Active tab (`tabIndex == _currentIndex`)**: Inherits and forwards the ancestor `PrimaryScrollController`.
- **Inactive tabs (`tabIndex != _currentIndex`)**: Wrapped in `PrimaryScrollController.none(child: child)`.

Wrapping both active and inactive tabs in `PrimaryScrollController` widgets keeps the widget tree depth (`KeyedSubtree -> Semantics -> PrimaryScrollController -> child`) identical across active and inactive states. Switching tabs updates the `PrimaryScrollController` properties in place without unmounting or disposing kept-alive tab states.

PR is being submitted shortly!

**Comment by surajgju** [comment]
similiar open issues those can be fixed with this pr
#148317 
#89864 
 #159123
