### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: O ficheiro ou diretório está danificado e ilegível., errno = 1392

### ISSUE THREAD

**Issue by Jacob-dvlp** [flutter/flutter#81151]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: O ficheiro ou diretório está danificado e ilegível.
, errno = 1392
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:469:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:468:12)
#5      PubDependencies.isUpToDate (package:flutter_tools/src/cache.dart:757:57)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:558:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.18362.30], locale pt-PT)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (9 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Developer\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in
      your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Developer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.72

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jonahwilliams** [comment]
Error code 1392 is  "The file or directory is damaged and unreadable"

Unfortunately the disk that flutter is trying to run from is damaged. This isn't something we can fix
