### ISSUE TITLE
Failed assertion: line 4954 pos 14: '_dependents.isEmpty': is not true.

### ISSUE THREAD

**Issue by fahmydiab** [flutter/flutter#81190]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Title(title: "Mobile Delivery App", color: MaterialColor(primary value: Color(0xffff5722))):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4954 pos 14: '_dependents.isEmpty': is not true.

The relevant error-causing widget was: 
  MaterialApp file:///C:/WorkSpace/mobileapps/flutter-apps/mob_delivery_app/lib/main.dart:22:12
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4954:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4956:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:2044:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2046:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
====================================================================================================
Reloaded 1 of 1004 libraries in 571ms.


```

**Comment by darshankawar** [comment]
@fahmydiab 
Can you provide `flutter doctor -v` and complete minimal reproducible code sample that replicates this issue ?
Thanks.
