### ISSUE TITLE
TabBarView doesn't update index when rebuilding with new controller

### ISSUE THREAD

**Issue by tomgilder** [flutter/flutter#81214]
When you have a `TabBar` and a `TabBarView` but switch the `TabController` they're using to a new controller with a different number of tabs, they can get our of sync.

This is due to the `TabBarView` not correctly updating when `didUpdateWidget` is called with a different controller.

## Steps to Reproduce

1. Run the sample app below
2. On the last tab, toggle the switch

Expected results: the tab bar and tab view both remain on the last page
Actual results: the tab bar displays correctly, but the tab view shows the middle page.

## Repro app

This app shows a variable number of tabs depending on if a toggle is enabled.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  TabController _controller;

  @override
  void initState() {
    super.initState();
    _toggle(false);
  }

  void _toggle(bool isVisible) {
    if (isVisible) {
      setState(
        () => _controller = TabController(
          length: 3,
          vsync: this,
          initialIndex: 2,
        ),
      );
    } else {
      setState(
        () => _controller = TabController(
          length: 2,
          vsync: this,
          initialIndex: 1,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        bottom: TabBar(
          controller: _controller,
          tabs: [
            Tab(text: 'First'),
            if (_controller.length == 3) Tab(text: 'Middle'),
            Tab(text: 'Last'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _controller,
        children: [
          Scaffold(body: Text('First page')),
          if (_controller.length == 3) Scaffold(body: Text('Middle page')),
          Scaffold(
            body: Column(
              children: [
                Text('Last page'),
                Row(
                  children: [
                    Switch(
                      value: _controller.length == 3,
                      onChanged: (value) => _toggle(value),
                    ),
                    Text('Show middle page')
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

<details>
  <summary>Logs</summary>

```
No issues found!
```

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-FI)
    • Flutter version 2.0.5 at /Users/tom/fvm/versions/stable
    • Framework revision adc687823a (10 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tom/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tom/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 mini (mobile) • 683303AC-CA81-42FE-880C-79C5FC0A41B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 90.0.4430.85

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report and code sample. I see the same behavior, ie, the tabview shows `middle page` instead of `last page`.

<img width="332" alt="Screenshot 2021-04-27 at 12 21 07 PM" src="https://user-images.githubusercontent.com/67046386/116198128-36e47c80-a753-11eb-9a53-ac764042b1f3.png">


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by Kavantix** [comment]
I also ran into this today.
To work around this I had to use `DefaultTabController` such that the animation got reused and then set the index manually on the controller when it changes:
```dart
// Animate to with a duration of 1 µs makes it instant
_tabController?.animateTo(initialTabIndex, duration: const Duration(microseconds: 1));

        return DefaultTabController(
          length: tabs.length,
          initialIndex: initialTabIndex,
          child: Builder(builder: (context) {
            _tabController = DefaultTabController.of(context);
```

**Comment by exaby73** [comment]
Hello. I have tested this on the current stable and master versions. The issue seems to be fixed in both version. There seems to be an error that shows up in stable but in master, the error is non-existant.

###### Error in question

```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
Build scheduled during frame.
While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild
the widget tree.
This might be because setState() was called from a layout or paint callback. If a change is needed
to the widget tree, it should be applied as the tree is being built. Scheduling a change for the
subsequent frame instead results in an interface that lags behind by one frame. If this was done to
make your build dependent on a size measured at layout time, consider using a LayoutBuilder,
CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is
the desired effect, for example because this is an animation, consider scheduling the frame in a
post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to
trigger the animation.

When the exception was thrown, this was the stack:
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:747:9)
#1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:770:6)
#2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2485:24)
#3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4443:12)
#4      State.setState (package:flutter/src/widgets/framework.dart:1141:15)
#5      _AnimatedState._handleChange (package:flutter/src/widgets/transitions.dart:128:5)
#6      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
#7      AnimationController.value= (package:flutter/src/animation/animation_controller.dart:365:5)
#8      TabController._changeIndex (package:flutter/src/material/tab_controller.dart:201:29)
#9      TabController.index= (package:flutter/src/material/tab_controller.dart:219:5)
#10     _TabBarViewState._handleScrollNotification (package:flutter/src/material/tabs.dart:1458:20)
#11     NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:151:42)
#12     Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:67:20)
#13     ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
#14     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4254:39)
#15     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:83:13)
#16     ScrollActivity.dispatchScrollEndNotification (package:flutter/src/widgets/scroll_activity.dart:104:63)
#17     ScrollPosition.didEndScroll (package:flutter/src/widgets/scroll_position.dart:907:15)
#18     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:876:9)
#19     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:114:11)
#20     ScrollPositionWithSingleContext.goIdle (package:flutter/src/widgets/scroll_position_with_single_context.dart:129:5)
#21     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:148:7)
#22     BallisticScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:549:14)
#23     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:623:15)
#24     ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:104:11)
#25     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:553:7)
#26     _PagePosition.applyContentDimensions (package:flutter/src/widgets/page_view.dart:473:18)
#27     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1493:20)
#28     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
#29     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#30     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#39     _invoke (dart:ui/hooks.dart:151:10)
#40     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#41     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
```

Since this is working as expected in both stable and master regardless of the error in stable on the console, I am closing this issue as fixed.

<details><summary><code>flutter doctor -v</code></summary>

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.914, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 2.13.0-0.0.pre.914 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ceea3a6175 (6 hours ago), 2022-05-05 03:04:06 -0400
    • Engine revision f14e879b94
    • Dart version 2.18.0 (build 2.18.0-85.0.dev)
    • DevTools version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.0.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /opt/homebrew/opt/openjdk@11/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.0.4
    • Dart plugin version 221.5588

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • F9E7F1F9-285A-4DE8-94CD-78FE97310572 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 101.1.38.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

<details><summary>Code sample used to verify</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyHomePage()));
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  late TabController _controller;

  @override
  void initState() {
    super.initState();
    _toggle(false);
  }

  void _toggle(bool isVisible) {
    if (isVisible) {
      setState(
        () => _controller = TabController(
          length: 3,
          vsync: this,
          initialIndex: 2,
        ),
      );
    } else {
      setState(
        () => _controller = TabController(
          length: 2,
          vsync: this,
          initialIndex: 1,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        bottom: TabBar(
          controller: _controller,
          tabs: [
            Tab(text: 'First'),
            if (_controller.length == 3) Tab(text: 'Middle'),
            Tab(text: 'Last'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _controller,
        children: [
          Scaffold(body: Text('First page')),
          if (_controller.length == 3) Scaffold(body: Text('Middle page')),
          Scaffold(
            body: Column(
              children: [
                Text('Last page'),
                Row(
                  children: [
                    Switch(
                      value: _controller.length == 3,
                      onChanged: (value) => _toggle(value),
                    ),
                    Text('Show middle page')
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>
