### ISSUE TITLE
sign_in_failed, com.google.android.gms.common.api.ApiException: 10

### ISSUE THREAD

**Issue by CZXBigBrother** [flutter/flutter#81268]
Update 5.0.2 keeps showing errors, and versions up to 5.0.0 work fine.

I am sure SHA1 and SHA256, as in 4.5.9 is working.

E/flutter ( 8950): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter ( 8950): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
E/flutter ( 8950): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 8950): <asynchronous suspension>
E/flutter ( 8950): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
E/flutter ( 8950): <asynchronous suspension>
E/flutter ( 8950):

**Comment by CZXBigBrother** [comment]
O! My! GOD!

Failure~
        classpath 'com.android.tools.build:gradle:3.5.4'
        classpath 'com.google.gms:google-services:4.3.5'

True~
        classpath 'com.android.tools.build:gradle:3.5.1'
        classpath 'com.google.gms:google-services:4.2.0'
