### ISSUE TITLE
LongPressGestureRecognizer can incorrectly reset its state

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#81339]
### Steps to reproduce

Run the following test:

```dart
testGesture('non-allowed pointer does not inadvertently reset the recognizer', (GestureTester tester) {
  longPress = LongPressGestureRecognizer(kind: PointerDeviceKind.touch)..onLongPress = () {};

  // Accept a long-press gesture
  longPress.addPointer(down);
  tester.closeArena(5);
  tester.route(down);
  tester.async.elapse(const Duration(milliseconds: 500));

  // Add a non-allowed pointer (doesn't match the kind filter)
  longPress.addPointer(const PointerDownEvent(
    pointer: 101,
    kind: PointerDeviceKind.mouse,
    position: Offset(10, 10),
  ));

  // Moving the primary pointer should result in a normal event
  tester.route(const PointerMoveEvent(
    pointer: 5,
    position: Offset(15, 15),
  ));
});
```

### Expected behavior

The test should pass.

### Actual behavior

The test fails with the following error:

```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
'package:flutter/src/gestures/long_press.dart': Failed assertion: line 383 pos 16: '_velocityTracker
!= null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      LongPressGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/long_press.dart:383:16)
#3      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
#4      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#5      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#7      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#9      GestureTester.route (file:///Users/tvolkert/project/flutter/flutter/packages/flutter/test/gestures/gesture_tester.dart:29:44)
#10     main.<anonymous closure>.<anonymous closure> (file:///Users/tvolkert/project/flutter/flutter/packages/flutter/test/gestures/long_press_test.dart:309:14)
#11     testGesture.<anonymous closure>.<anonymous closure> (file:///Users/tvolkert/project/flutter/flutter/packages/flutter/test/gestures/gesture_tester.dart:40:15)
#12     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#17     withClock (package:clock/src/default.dart:48:10)
#18     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#23     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#24     testGesture.<anonymous closure> (file:///Users/tvolkert/project/flutter/flutter/packages/flutter/test/gestures/gesture_tester.dart:39:17)
#25     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:200:19)
<asynchronous suspension>
<asynchronous suspension>
(elided 11 frames from class _AssertionError, dart:async, and package:stack_trace)

router: Instance of 'PointerRouter'
route: Closure: (PointerEvent) => void from Function 'handleEvent':.
event: PointerMoveEvent#b0d17(position: Offset(15.0, 15.0))
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by tvolkert** [comment]
The issue stems from the fact that the non-allowed pointer rejects the gesture:

https://github.com/flutter/flutter/blob/ea1b5e3f682bfc12663cc836085ec6df6200209d/packages/flutter/lib/src/gestures/recognizer.dart#L232-L234

... which in turn resets the state of the gesture if the long-press has already been accepted:

https://github.com/flutter/flutter/blob/ea1b5e3f682bfc12663cc836085ec6df6200209d/packages/flutter/lib/src/gestures/long_press.dart#L533-L540

... but the gesture is still tracking the primary pointer and handling events, and it needs that state in order to send those events (like `onLongPressMoveUpdate`).
