### ISSUE TITLE
Issue: I have a problem with my Flutter application.

### ISSUE THREAD

**Issue by realkimmy** [flutter/flutter#81356]
Click to enter a certain page and report an error

```
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
flutter: [debug] Capture from onError BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The offending constraints were:
  BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(bg: ShapeDecoration(shape: RoundedRectangleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none), BorderRadius.circular(8.0))), constraints: BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED), dirty):
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.

The offending constraints were: BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:517:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:541:19)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:565:6)
#3      new ConstrainedBox (package:flutter/src/widgets/basic.dart:2293:27)
#4      Container.build (package:flutter/src/widgets/container.dart:428:17)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
====================================================================================================

======== Exception caught by widgets library =======================================================
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
====================================================================================================

======== Exception caught by widgets library =======================================================
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
====================================================================================================

======== Exception caught by widgets library =======================================================
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
====================================================================================================

======== Exception caught by widgets library =======================================================
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
====================================================================================================

======== Exception caught by widgets library =======================================================
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
====================================================================================================

======== Exception caught by widgets library =======================================================
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
====================================================================================================

======== Exception caught by widgets library =======================================================
BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
The relevant error-causing widget was: 
  MaterialApp file:///Users/ying/workspace/FlutterProjects/gitter/lib/main.dart:243:20
====================================================================================================

```

my code

```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gitter/common/iconfonts/iconfonts.dart';
import 'package:gitter/common/utils/dark_mode_util.dart';
import 'package:gitter/common/utils/navigator_util.dart';
import 'package:gitter/common/utils/string_util.dart';
import 'package:gitter/ui/blocs/me/dark_mode/dark_mode_bloc.dart';
import 'package:gitter/ui/blocs/search/search_bloc.dart';
import 'package:gitter/ui/pages/search/search_history_page.dart';
import 'package:gitter/ui/pages/search/search_issues.dart';
import 'package:gitter/ui/pages/search/search_organizations.dart';
import 'package:gitter/ui/pages/search/search_people.dart';
import 'package:gitter/ui/pages/search/search_pulls.dart';
import 'package:gitter/ui/pages/search/search_repositories.dart';
import 'package:gitter/ui/pages/search/search_submit.dart';
import 'package:gitter/ui/widgets/profile_item.dart';
import 'package:gitter/ui/widgets/search.dart';

List<Function> _categories = [
  (BuildContext context) => 'Repositories With ',
  (BuildContext context) => 'Issues With ',
  (BuildContext context) => 'Pull Requests With ',
  (BuildContext context) => 'People With ',
  (BuildContext context) => 'Organizations With ',
  (BuildContext context) => 'Jump to ',
];

List<IconData> _leadingIcons = [
  IconFonts.repo,
  IconFonts.issue,
  IconFonts.pull,
  Icons.people,
  IconFonts.organization,
  Icons.arrow_forward
];

List<Function> _actions = [
  (BuildContext context, String searchText) {
    NavigatorUtil.push(
        context,
        SearchRepositoriesPage(
          searchText: searchText,
        ));
  },
  (BuildContext context, String searchText) {
    NavigatorUtil.push(
        context,
        SearchIssuesPage(
          searchText: searchText,
        ));
  },
  (BuildContext context, String searchText) {
    NavigatorUtil.push(
        context,
        SearchPullsPage(
          searchText: searchText,
        ));
  },
  (BuildContext context, String searchText) {
    NavigatorUtil.push(
        context,
        SearchPeoplePage(
          searchText: searchText,
        ));
  },
  (BuildContext context, String searchText) {
    NavigatorUtil.push(
        context,
        SearchOrganizationsPage(
          searchText: searchText,
        ));
  },
  (BuildContext context, String searchText) {},
];

class SearchPage extends StatefulWidget {
  @override
  _SearchPageState createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage>
    with AutomaticKeepAliveClientMixin {

  @override
  void dispose() {
    BlocProvider.of<SearchBloc>(context)
        .add(SearchInitEvent(text: StringUtil.STRING_EMPTY));
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Container();
    // return Scaffold(
    //   body: SafeArea(
    //     child: Column(
    //       children: <Widget>[
    //         Padding(
    //           padding: EdgeInsets.only(top: 4, bottom: 2),
    //           child: Search(
    //             autoFocus: false,
    //             hideLeft: true,
    //             hideRight: true,
    //             hideSpeak: true,
    //             hint: '搜索',
    //             defaultText: StringUtil.STRING_EMPTY,
    //             onChanged: (value) {
    //               BlocProvider.of<SearchBloc>(context)
    //                   .add(SearchInitEvent(text: value));
    //             },
    //             onSubmitted: (value) {
    //               if(StringUtil.isNotBlank(value)) {
    //                 NavigatorUtil.push(
    //                     context, SearchSubmitPage(searchText: value));
    //               }
    //             },
    //           ),
    //         ),
    //         BlocBuilder<SearchBloc, SearchState>(
    //           builder: (context, state) => Expanded(
    //             child: _content(state.text),
    //           ),
    //         )
    //       ],
    //     ),
    //   ),
    // );
  }

  Widget _content(String searchText) {
    return StringUtil.isBlank(searchText)
        ? SearchHistoryPage()
        : _searchPanel(searchText);
  }

  Widget _searchPanel(String searchText) {
    return ListView.separated(
      physics: NeverScrollableScrollPhysics(),
      itemBuilder: (context, index) => GestureDetector(
        onTap: () {
          _actions[index](context, searchText);
        },
        behavior: HitTestBehavior.opaque,
        child: Container(
          padding: EdgeInsets.only(left: 16, right: 12),
          child: BlocBuilder<DarkModeBloc, DarkModeState>(
            builder: (context, state) => ProfileItem(
              leading: Padding(
                padding: EdgeInsets.only(right: 16),
                child: Icon(
                  _leadingIcons[index],
                  size: 16,
                ),
              ),
              content: Text(
                '${_categories[index](context)}"$searchText"',
              ),
              action: Icon(
                Icons.arrow_forward_ios,
                size: 16,
                color: DarkModeUtil.isDarkMode(context, state.themeMode)
                    ? Colors.white24
                    : Colors.black26,
              ),
            ),
          ),
        ),
      ),
      itemCount: _categories.length,
      separatorBuilder: (BuildContext context, int index) => Padding(
        padding: EdgeInsets.only(left: 48),
        child: Divider(),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}

```

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
Analyzing XXX...                                                     

   info • The declaration '_loadWidgetData' isn't referenced • lib/main.dart:294:16 • unused_element
   info • The declaration '_startBackgroundUpdate' isn't referenced • lib/main.dart:328:8 • unused_element
   info • The declaration '_stopBackgroundUpdate' isn't referenced • lib/main.dart:334:8 • unused_element
   info • Unnecessary cast • lib/ui/pages/tab_navigator.dart:73:23 • unnecessary_cast
warning • Publishable packages can't have git dependencies • pubspec.yaml:42:5 • invalid_dependency
warning • Publishable packages can't have git dependencies • pubspec.yaml:58:5 • invalid_dependency
warning • Publishable packages can't have git dependencies • pubspec.yaml:77:5 • invalid_dependency
warning • Publishable packages can't have git dependencies • pubspec.yaml:81:5 • invalid_dependency

8 issues found. (ran in 18.9s)

```

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.5 at /Users/ying/flutter
    • Framework revision adc687823a (12 天前), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ying/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • WY's iPhone (mobile)       • 00008020-000A1D110A32002E            • ios            • iOS 14.5
    • iPhone 12 Pro Max (mobile) • EEEEEB90-613E-4D49-BCA5-F8EE7AD4A0F2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

```

</details>

**Comment by pedromassangocode** [comment]
Hi @realkimmy 
Can you please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample that does not use any third-party package/plugin?
Thank you

**Comment by realkimmy** [comment]
I found the reason, it is caused by a third-party [plugin](https://pub.dev/packages/showcaseview)

**Comment by pedromassangocode** [comment]
Thank you.
