### ISSUE TITLE
snapshot.data.length error when i upgrade my project to nullsefty version

### ISSUE THREAD

**Issue by lkrjangid1** [flutter/flutter#81370]
snapshot.data.length error when I upgrade my project to nullsefty version

```
environment:
  sdk: ">=2.7.0 <3.0.0"
```
to 

```
environment:
  sdk: ">=2.12.0 <3.0.0"
```

flutter doctor 

<details> 
<summary>flutter doctor -v</summary> 

```console
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.21359.1], locale en-IN)
    • Flutter version 2.0.5 at C:\Program Files\flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\lkrja\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\lkrja\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.21359.1]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!
```
		
</details>
flutter run --verbose

<details> 
<summary>logs</summary> 

```console

[ +111 ms] executing: [C:\Program Files\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +112 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] adc687823a831bbebe28bdccfac1a628ca621513
[   +2 ms] executing: [C:\Program Files\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +90 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +65 ms] executing: [C:\Program Files\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Program Files\flutter/] git ls-remote --get-url origin
[  +57 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +110 ms] executing: [C:\Program Files\flutter/] git rev-parse --abbrev-ref HEAD
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +128 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +97 ms] executing: C:\Users\lkrja\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +68 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +115 ms] No supported devices connected.
[  +35 ms] The following devices were found, but are not supported by this project:
           Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.21359.1]
           Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.93
           Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.46
           If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.
           
[  +14 ms] "flutter run" took 431ms.
[  +24 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:442:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +265 ms] ensureAnalyticsSent: 257ms
[   +7 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

</details>

**Comment by ruthvik-github** [comment]
Provide more details about the issue.

**Comment by TahaTesser** [comment]
Hi @lkrjangid1 

```console
[ +115 ms] No supported devices connected.
[  +35 ms] The following devices were found, but are not supported by this project:
           Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.21359.1]
           Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.93
           Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.46
           If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.
           
[  +14 ms] "flutter run" took 431ms.
[  +24 ms] 
           #0    
```

Please connect to device or emulator when executing `flutter run -v`


Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
