### ISSUE TITLE
Failed assertion: line 4954 pos 14: '_dependents.isEmpty': is not true.

### ISSUE THREAD

**Issue by sauravgpt** [flutter/flutter#81385]
<details> 
<summary>logs</summary> 

```console
E/flutter (27664):   parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body
E/flutter (27664):   constraints: MISSING
E/flutter (27664):   size: MISSING
E/flutter (27664):   additionalConstraints: BoxConstraints(w=411.4, h=876.6)
E/flutter (27664): Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
E/flutter (27664): If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
E/flutter (27664): #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:2391:11)
E/flutter (27664): #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2422:6)
E/flutter (27664): #2      RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2785:25)
E/flutter (27664): #3      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (27664): #4      RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2780:33)
E/flutter (27664): #5      RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:417:12)
E/flutter (27664): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #7      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #8      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #9      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #10     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #11     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:1892:18)
E/flutter (27664): #12     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #14     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #16     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #18     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3249:31)
E/flutter (27664): #19     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #21     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #22     RenderFractionalTranslation.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2706:22)
E/flutter (27664): #23     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (27664): #24     RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2700:19)
E/flutter (27664): #25     RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2686:12)
E/flutter (27664): #26     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #28     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #32     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3368:31)
E/flutter (27664): #33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #35     _RenderTheatre.hitTestChildren.<anonymous closure> (package:flutter/src/widgets/overlay.dart:765:25)
E/flutter (27664): #36     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:787:31)
E/flutter (27664): #37     _RenderTheatre.hitTestChildren (package:flutter/src/widgets/overlay.dart:760:33)
E/flutter (27664): #38     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #39     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #40     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #41     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #42     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #43     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3466:17)
E/flutter (27664): #44     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #45     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:180:19)
E/flutter (27664): #46     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #47     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #48     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:133:19)
E/flutter (27664): #49     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2424:11)
E/flutter (27664): #50     RenderView.hitTest (package:flutter/src/rendering/view.dart:173:14)
E/flutter (27664): #51     RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:481:16)
E/flutter (27664): #52     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:288:7)
E/flutter (27664): #53     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
E/flutter (27664): #54     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
E/flutter (27664): #55     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
E/flutter (27664): #56     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (27664): #57     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (27664): #58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (27664): #59     _invoke1 (dart:ui/hooks.dart:180:10)
E/flutter (27664): #60     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
E/flutter (27664): #61     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter (27664): 
I/ViewRootImpl@4f877bb[MainActivity](27664): ViewPostIme pointer 1
I/ViewRootImpl@4f877bb[MainActivity](27664): ViewPostIme pointer 0
I/ViewRootImpl@4f877bb[MainActivity](27664): ViewPostIme pointer 1

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#ab2ed](state: OverlayState#48678(entries: [OverlayEntry#a0153(opaque: true; maintainState: false), OverlayEntry#606da(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4954 pos 14: '_dependents.isEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///D:/Development/Intern/XP%20Cover/xpcover/lib/main.dart:23:14
When the exception was thrown, this was the stack: 
#2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4954:14)
#3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4956:6)
#4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:2044:15)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:2046:6)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)

```

</details>

**Comment by TahaTesser** [comment]
Hi @sauravgpt 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
Thank you

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
