### ISSUE TITLE
Investigate missing stdout/stderr on failed Engine unit tests on Windows

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#81416]
For example in the build here https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/9731/overview, the logs end with:
```
[ RUN      ] ImageDecoderFixtureTest.CanResizeWithoutDecode

Traceback (most recent call last):

  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 552, in <module>
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    sys.exit(main())
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 522, in main
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    RunCCTests(build_dir, engine_filter)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 170, in RunCCTests

    RunEngineExecutable(build_dir, 'ui_unittests', filter, shuffle_flags + ['--timeout=90'])

  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 115, in RunEngineExecutable
Failed Command:
    RunCmd(test_command, cwd=cwd, forbidden_output=forbidden_output)

  File "C:\b\s\w\ir\cache\builder\src\flutter\testing\run_tests.py", line 60, in RunCmd
C:\b\s\w\ir\cache\builder\src\out\host_debug\ui_unittests.exe --gtest_shuffle --gtest_repeat=2 --timeout=90
    raise Exception('Command "%s" exited with code %d.' % (command_string, process.returncode))

Exception: Command "C:\b\s\w\ir\cache\builder\src\out\host_debug\ui_unittests.exe --gtest_shuffle --gtest_repeat=2 --timeout=90" exited with code -1073741819.
Exit Code: -1073741819
```

/cc @chinmaygarde @jason-simmons

**Comment by chinmaygarde** [comment]
I'm going to take a stab at reproducing this on my Windows box.
