### ISSUE TITLE
 Full stack-trace for unhandled exceptions

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#81464]
## Steps to Reproduce

Write code that throws an exception from a lambda function passed to e.g. nested `showDialog()`, `List.map()`, etc

**Expected results:** 

Full or at least longer stack trace

**Actual results:**

```
Performing hot reload...
Syncing files to device LG H873...

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder(dirty):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  MaterialApp file:///C:/dev/pss-mobile-android/lib/app/app.dart:215:12
When the exception was thrown, this was the stack: 
#0      WhereIterator.moveNext (dart:_internal/iterable.dart)
#1      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#2      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#3      new List.of (dart:core-patch/array_patch.dart:50:28)
#4      Iterable.toList (dart:core/iterable.dart:366:12)
...
====================================================================================================
Reloaded 0 libraries in 876ms.
```

<details>
  <summary>Logs</summary>

```
C:\dev\pss-mobile-android>flutter doctor -v
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale ru-UA)
    • Flutter version 2.0.5 at C:\tools\flutter
    • Framework revision adc687823a (13 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at c:\tools\Android-SDK
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = c:\tools\Android-SDK
    • Java binary at: C:\tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\tools\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 32-bit edition (version 1.55.2)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • LG H873 (mobile) • LGH8736bb28167 • android-arm64  • Android 8.0.0 (API 26)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)       • edge           • web-javascript • Microsoft Edge 90.0.818.39

• No issues found!

```
</details>

**Comment by darshankawar** [comment]
@duzenko 
Can you provide a self contained code sample that we can use to verify this issue ? `Write code that throws an exception from a lambda function passed to e.g. nested showDialog(), List.map(), etc`

**Comment by duzenko** [comment]
> 
> 
> @duzenko
> Can you provide a self contained code sample that we can use to verify this issue ? `Write code that throws an exception from a lambda function passed to e.g. nested showDialog(), List.map(), etc`

Sure, but can you provide an ETA on the fix after the sample is provided?

**Comment by darshankawar** [comment]
@duzenko 


> Sure, but can you provide an ETA on the fix after the sample is provided?

That is not in my hand to provide. A priority will be assigned to this issue that will give you an idea as when will it be fixed.

**Comment by duzenko** [comment]
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: [0]
              .where((element) => null)
              .map(
                (e) => Text(
                  'You have pushed the button this many times:',
                ),
              )
              .toList(),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by darshankawar** [comment]
@duzenko 
Does it only occur during hot reload or hot restart ? Are there any specific steps to replicate this ?

**Comment by exaby73** [comment]
@duzenko Hello. I have tested this on the current stable version of Flutter (2.10.5). Below you can see the stack trace Flutter shows on the error. This stack trace was produced with the following code, which is a null-safety migrated version of your code you posted a while back.

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: [_counter]
              .where((element) => throw 'An error')
              .map(
                (e) => const Text(
                  'You have pushed the button this many times:',
                ),
              )
              .toList(),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

<details><summary>Stacktrace</summary>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following message was thrown building MyHomePage(dirty, state: _MyHomePageState#5fcfc):
An error

The relevant error-causing widget was:
  MyHomePage MyHomePage:file:///Users/nabeelparkar/dev/nevercode/issue_81464/lib/main.dart:31:19

When the exception was thrown, this was the stack:
#0      _MyHomePageState.build.<anonymous closure> (package:issue_81464/main.dart:102:35)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:439:13)
#2      MappedIterator.moveNext (dart:_internal/iterable.dart:390:19)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:219:26)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:155:26)
#5      new List.of (dart:core-patch/array_patch.dart:51:28)
#6      Iterable.toList (dart:core/iterable.dart:470:12)
#7      _MyHomePageState.build (package:issue_81464/main.dart:108:16)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919:11)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (24 frames)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#39     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#40     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (175 frames)
#215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#216    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#217    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (377 frames)
#594    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#595    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#596    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#597    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#598    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#599    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600:19)
#600    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#601    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#602    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

Please confirm if this is a suitable solution to your issue.

**Comment by duzenko** [comment]
Sorry, what is the "solution" exactly?

**Comment by exaby73** [comment]
If you see the stack trace Flutter currently shows, it's much more verbose. Is that the expected behavior currently? I have posted the stack trace I was able to produce in a collapsable section in my first comment.

**Comment by duzenko** [comment]
I can see what you test this with different code than me. 
What is it supposed to achieve?
Why not test the original case?

**Comment by exaby73** [comment]
The code is the same, migrated to null safety to match with current Flutter versions
