### ISSUE TITLE
LiveTestWidgetsFlutterBinding throws an assertion error after the test when there are async exceptions

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#81521]
## Steps to Reproduce

```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  LiveTestWidgetsFlutterBinding();
  testWidgets('foo', (tester) async {
    Future.error('some async error');
  });
}
```

The following assertion error is thrown:

```
<... stack trace here from the async exception>

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
'package:flutter_test/src/binding.dart': Failed assertion: line 1561 pos 12: 'inTest': is not true.

When the exception was thrown, this was the stack:
#2      LiveTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1561:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:801:13)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
00:05 +0 -1: Some tests failed.
```

This does not happen with `AutomatedTestWidgetsFlutterBinding`. The cause of this is https://github.com/dart-lang/test/issues/1512. 

<details>
  <summary>Doctor output</summary>

```
[✓] Flutter (Channel unknown, 2.3.0-1.0.pre.144, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.3.0-1.0.pre.144 at /Users/jiahaog/dev/flutter
    • Upstream repository unknown
    • Framework revision 9eb93e3485 (2 days ago), 2021-04-28 04:49:01 -0400
    • Engine revision 5b55f3ccb4
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jiahaog/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio with Blaze.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode_12.3.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ CE (stable).app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.8443

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ UE (stable).app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 202.8443

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H524 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
<details>
<summary> test error log </summary>

```

Testing started at 1:51 PM ...
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter --no-color test --machine --start-paused test/widget_test.dart

(The following exception is now available via WidgetTester.takeException:)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown running a test:
some async error

When the exception was thrown, this was the stack:
#2      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/macbug/test/widget_test.dart:38:12)
#3      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/macbug/test/widget_test.dart:37:22)
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:156:29)
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:0:0)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:793:19)
#13     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:771:14)
#14     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1627:12)
#15     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:148:24)
#16     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:200:19)
#19     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:0:0)
#24     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:198:13)
#25     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:181:48)
#26     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#27     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:228:14)
#32     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#33     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
#36     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:0:0)
#41     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#42     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#43     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#50     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#51     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#52     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:255:16)
#57     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:254:5)
#58     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:207:7)
#76     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#77     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#81     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#115    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#123    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#124    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#134    _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#143    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#144    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
(elided 112 frames from dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  foo
════════════════════════════════════════════════════════════════════════════════════════════════════
(If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown running a test:
some async error

When the exception was thrown, this was the stack:
#2      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/macbug/test/widget_test.dart:38:12)
#3      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/macbug/test/widget_test.dart:37:22)
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:156:29)
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:0:0)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:793:19)
#13     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:771:14)
#14     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1627:12)
#15     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:148:24)
#16     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:200:19)
#19     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:0:0)
#24     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:198:13)
#25     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:181:48)
#26     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#27     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:228:14)
#32     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#33     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
#36     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:0:0)
#41     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#42     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#43     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#50     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#51     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#52     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:255:16)
#57     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:254:5)
#58     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:207:7)
#76     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#77     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#81     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#115    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#123    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#124    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#134    _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#143    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#144    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
(elided 112 frames from dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  foo
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test (but after the test had completed):
'package:flutter_test/src/binding.dart': Failed assertion: line 1561 pos 12: 'inTest': is not true.

When the exception was thrown, this was the stack:
#2      LiveTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1561:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:801:13)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: foo




```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.143 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (2 days ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```

</details>

**Comment by djilet** [comment]
same error in 3.13.1
