### ISSUE TITLE
ListView scroll offset issue

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#8155]
## Steps to Reproduce

* With the new `ListView` add two or more children.
* Scroll down the list to the point where the first child is entirely off the screen.
* Make any changes to the contents, so that the first child reduces its height.
* Scroll all the way back up to the initial position. The `ListView` shows nothing on screen (just white empty space).

I was using this code to test this behavior:
https://gist.github.com/yyoon/8c0ef358de2d1b148ff1b2d0ffacc4db

FWIW, `Block` didn't have the same issue.

## Logs

The console shows the following error:

```
I/flutter (16187): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (16187): The following assertion was thrown during performLayout():
I/flutter (16187): 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 484 pos 12:
I/flutter (16187): 'scrollOffsetCorrection == 0.0': is not true.
I/flutter (16187): 
I/flutter (16187): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16187): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16187): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16187):   https://github.com/flutter/flutter/issues/new
I/flutter (16187): 
I/flutter (16187): When the exception was thrown, this was the stack:
I/flutter (16187): #2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:484:12)
I/flutter (16187): #3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:693:21)
I/flutter (16187): #4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1750:19)
I/flutter (16187): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1750:14)
I/flutter (16187): #7      RenderViewportBase2.layoutOneSide (package:flutter/src/rendering/sliver.dart:1223:13)
I/flutter (16187): #8      RenderViewport2._attemptLayout (package:flutter/src/rendering/sliver.dart:1712:12)
I/flutter (16187): #9      RenderViewport2.performLayout (package:flutter/src/rendering/sliver.dart:1641:20)
I/flutter (16187): #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1624:7)
I/flutter (16187): #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953:18)
I/flutter (16187): #12     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:223:19)
I/flutter (16187): #13     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:333:23)
I/flutter (16187): #14     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:168:5)
I/flutter (16187): #15     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676:15)
I/flutter (16187): #16     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611:9)
I/flutter (16187): #17     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (16187): (elided 3 frames from class _AssertionError)
I/flutter (16187): 
I/flutter (16187): The following RenderObject was being processed when the exception was fired:
I/flutter (16187):   RenderSliverList relayoutBoundary=up1
I/flutter (16187):   creator: SliverList ← Viewport2 ← IgnorePointer-[GlobalKey 671894551] ← Listener ←
I/flutter (16187):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState> 499236135] ←
I/flutter (16187):   RepaintBoundary ← CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification2> ←
I/flutter (16187):   GlowingOverscrollIndicator ← Scrollable2 ← ⋯
I/flutter (16187):   parentData: paintOffset=Offset(0.0, 0.0)
I/flutter (16187):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward,
I/flutter (16187):   ScrollDirection.forward, scrollOffset: 188.7, remainingPaintExtent: 764.0, crossAxisExtent:
I/flutter (16187):   1280.0viewportMainAxisExtent: 764.0)
I/flutter (16187):   geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0, scrollOffsetCorrection:
I/flutter (16187):   -200.0)
I/flutter (16187):   currently live children: 0 to 1
I/flutter (16187): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (16187):   RenderRepaintBoundary relayoutBoundary=up2
I/flutter (16187):     RenderConstrainedBox relayoutBoundary=up3
I/flutter (16187):       RenderDecoratedBox
I/flutter (16187):         RenderLimitedBox
I/flutter (16187):           RenderConstrainedBox
I/flutter (16187):   RenderRepaintBoundary relayoutBoundary=up2
I/flutter (16187):     RenderConstrainedBox relayoutBoundary=up3
I/flutter (16187):       RenderDecoratedBox
I/flutter (16187):         RenderLimitedBox
I/flutter (16187):           RenderConstrainedBox
I/flutter (16187): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (16187): Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 484 pos 12: 'scrollOffsetCorrection == 0.0': is not true.
I/flutter (16187): Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 484 pos 12: 'scrollOffsetCorrection == 0.0': is not true.
I/flutter (16187): Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 484 pos 12: 'scrollOffsetCorrection == 0.0': is not true.
```

## Flutter Doctor

```
youngseokyoon list_view$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/youngseokyoon/Programming/fuchsia/lib/flutter
    • Framework revision 36f6405179 (2 hours ago), 2017-02-14 10:58:33
    • Engine revision f306a6f701
    • Tools Dart version 1.22.0-dev.10.6

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /usr/local/google/home/youngseokyoon/Android/Sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /usr/local/google/home/youngseokyoon/Android/Sdk
    • OpenJDK Runtime Environment (build 1.8.0_112-google-v7-146844476-143772575)

[-] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • Pixel C • 5C08000423 • android-arm • Android 7.0 (API 24)
```

**Comment by abarth** [comment]
I can reproduce.

**Comment by praveengupta0895** [comment]
@abarth , again I'm getting the same issue with the new flutter upgrade.
"Scroll all the way back up to the initial position. The ListView shows nothing on screen (just white empty space)."
Someone else is also facing the same issue. Here's the case ID #63263 .
