### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods.

### ISSUE THREAD

**Issue by Duskley** [flutter/flutter#81572]
hello little question for a computer project in computer license I have to refactor an old application and make it modular. But here's when I build my generate signed bundle and I launch a feature on demand who use tensorflow on my android I have this error: 

FATAL EXCEPTION: Thread-9
Process: descartes.info.l3ak2.eyetrek, PID: 7275
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/androidx.test.tools.crawler-gvh38WebyoKL_IpGVoIEuw==/base.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/base.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_config.xxhdpi.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_moduleastronomie.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_moduleastronomie.config.xxhdpi.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_modulereconnaissancechantsoiseaux.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_modulereconnaissancechantsoiseaux.config.xxhdpi.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_modulereconnaissancefeuille.apk", zip file "/data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/split_modulereconnaissancefeuille.config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/androidx.test.tools.crawler-gvh38WebyoKL_IpGVoIEuw==/lib/arm64, /data/app/descartes.info.l3ak2.eyetrek-h1-hReoVf26OAguR-8QZHw==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libtensorflowlite_jni.so"
	at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:80)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:52)
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:277)
	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:262)
	at descartes.info.l3ak2.eyetrek.module_reconnaissance_feuille.tensorflow.ImageClassifierFpasF.<init>(ImageClassifierFpasF.java:102)
	at descartes.info.l3ak2.eyetrek.module_reconnaissance_feuille.fragment.FragmentScanFeuille$6.run(FragmentScanFeuille.java:1306)
	at java.lang.Thread.run(Thread.java:764)

how can I resolve this ?

**Comment by Duskley** [comment]
oops sorry
