### ISSUE TITLE
Invalid initialRoute fails ugly

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#8158]
If the MaterialApp `initialRoute` doesn't match a known route we should probably assert as much and do so early. Currently the failure mode is less obvious.

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Title(color: Color(0xff2196f3)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 797 pos 12: 'route != null': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:797:12)
...
```

**Comment by zoechi** [comment]
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      onGenerateRoute: (s) => MaterialPageRoute(
          builder: (b) => /*Container(child: Text('route'))*/ null,
          settings: s),
      initialRoute: 'foo/bar',
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'foo text',
            ),
          ],
        ),
      ),
    );
  }
}
```
results in 
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,696ms.
I/flutter ( 6366): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6366): The following assertion was thrown building Builder(dirty):
I/flutter ( 6366): The builder for route "foo/bar" returned null.
I/flutter ( 6366): Route builders must never return null.
I/flutter ( 6366): 
I/flutter ( 6366): When the exception was thrown, this was the stack:
I/flutter ( 6366): #0      MaterialPageRoute.buildPage.<anonymous closure> (package:flutter/src/material/page.dart:89:9)
I/flutter ( 6366): #1      MaterialPageRoute.buildPage (package:flutter/src/material/page.dart:95:6)
I/flutter ( 6366): #2      _ModalScopeState.build.<anonymous closure> (package:flutter/src/widgets/routes.dart:656:43)
I/flutter ( 6366): #3      Builder.build (package:flutter/src/widgets/basic.dart:5798:41)
```
```
[✓] Flutter (Channel dev, v1.1.7, on Mac OS X 10.14.1 18B75, locale en-AT)
```

**Comment by goderbauer** [comment]
We should add a more specific assert for this. /cc @chunhtai

**Comment by chunhtai** [comment]
This will likely be captured by this line https://github.com/flutter/flutter/blob/d390f4d9c66f0de42e32174cba64944d0079d9bd/packages/flutter/lib/src/widgets/navigator.dart#L2167 that has a lot better error message now.
