### ISSUE TITLE
Re-using a NavigatorObserver in Navigator.observers can throw

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#81591]
## Steps to reproduce

Run the following app:

```dart
import 'package:flutter/widgets.dart';

void main() {
  final NavigatorObserver observer = NavigatorObserver();
  runApp(BugReport(observer));
}

class BugReport extends StatelessWidget {
  const BugReport(this.observer);

  final NavigatorObserver observer;

  @override
  Widget build(BuildContext context) {
    Widget result = Directionality(
      textDirection: TextDirection.ltr,
      child: Navigator(
        observers: [observer],
        onGenerateRoute: (RouteSettings settings) {
          return PageRouteBuilder<void>(
            settings: settings,
            pageBuilder: (BuildContext _, Animation<double> __, Animation<double> ___) {
              return Container();
            },
          );
        },
      ),
    );

    if (false) // <---- change this to true and hot reload
      result = Container(child: result);

    return result;
  }
}
```

... then change the `false` to be `true` and hot reload.

## Expected behavior

You expect the updated tree to be rebuilt and rendered with no issues.

## Actual behavior

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Directionality(textDirection: ltr):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3385 pos 14:
'observer.navigator == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:3385:14)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4734:57)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4569:5)
...     Normal element mounting (13 frames)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3626:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3375:20)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4621:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4286:5)
#21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2583:33)
#22     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:878:21)
#23     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#24     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1147:15)
#25     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1084:9)
#26     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1000:5)
#30     _invoke (dart:ui/hooks.dart:163:10)
#31     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#32     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 5 frames from class _AssertionError and dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Version info

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.156, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.3.0-1.0.pre.156 at /Users/tvolkert/project/flutter/flutter
    • Upstream repository git@github.com:tvolkert/flutter.git
    • Framework revision 91de4bd3e3 (2 days ago), 2021-04-28 12:51:27 -0700
    • Engine revision d0688da4b1
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)
```

**Comment by tvolkert** [comment]
This can be reproduced in the following test case:

```dart
  testWidgets('Can reuse NavigatorObserver in updated tree', (WidgetTester tester) async {
    final NavigatorObserver observer = NavigatorObserver();
    final Widget widget = Directionality(
      textDirection: TextDirection.ltr,
      child: Navigator(
        observers: [observer],
        onGenerateRoute: (RouteSettings settings) {
          return PageRouteBuilder<void>(
            settings: settings,
            pageBuilder: (BuildContext _, Animation<double> __, Animation<double> ___) {
              return Container();
            },
          );
        },
      ),
    );

    await tester.pumpWidget(widget);
    await tester.pumpWidget(Container(child: widget));
  });
```

**Comment by tvolkert** [comment]
Incidentally, this is also triggered by creating a WidgetsApp with a builder property, then trying to turn on the performance overlay.
