### ISSUE TITLE
Flake in web expression evaluation test

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#81592]
Seems like we might have gotten some bad data?

From https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848480251042689344/+/u/run_test.dart_for_web_tool_tests_shard_and_subshard_web/stdout

```
▌00:28:07▐ STARTING ANALYSIS                                                                                       
01:05 +0: test/web.shard/debugger_stepping_web_test.dart: Web debugger can step over statements                                                                                                        
01:05 +0 -1: test/web.shard/debugger_stepping_web_test.dart: Web debugger can step over statements [E]                                                                                                 
  getStack: (-32603) getStack: NoSuchMethodError: The method 'toJson' was called on null.
  Receiver: null
  Tried calling: toJson()
  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
  #1      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1582:28)
  <asynchronous suspension>
  
  package:vm_service/src/vm_service.dart 1606:45        new _OutstandingRequest
  package:vm_service/src/vm_service.dart 2078:21        VmService._call
  package:vm_service/src/vm_service.dart 1890:61        VmService.getStack
  test/integration.shard/test_driver.dart 334:42        FlutterTestDriver.getTopStackFrame
  ===== asynchronous gap ===========================
  dart:async                                            _Completer.completeError
  package:vm_service/src/vm_service.dart 1613:18        _OutstandingRequest.completeError
  package:vm_service/src/vm_service.dart 2163:15        VmService._processResponse
  package:vm_service/src/vm_service.dart 2152:7         VmService._processMessageStr
  package:vm_service/src/vm_service.dart 2104:7         VmService._processMessage
  ===== asynchronous gap ===========================
  dart:async                                            _StreamImpl.listen
  package:vm_service/src/vm_service.dart 1648:27        new VmService
  package:vm_service/vm_service_io.dart 41:10           vmServiceConnectUri
  ===== asynchronous gap ===========================
  dart:async                                            _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart 139:24        FlutterTestDriver.connectToVmService
  test/integration.shard/test_driver.dart 576:17        FlutterRunTestDriver._setupProcess.<fn>
  ===== asynchronous gap ===========================
  dart:async                                            _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart               FlutterRunTestDriver._setupProcess.<fn>
  test/integration.shard/test_driver.dart 596:6         FlutterRunTestDriver._setupProcess
  ===== asynchronous gap ===========================
  dart:async                                            _asyncThenWrapperHelper
  test/integration.shard/test_driver.dart 471:11        FlutterRunTestDriver.run
  test/web.shard/debugger_stepping_web_test.dart 28:19  main.<fn>
  ===== asynchronous gap ===========================
  dart:async                                            _asyncThenWrapperHelper
  test/web.shard/debugger_stepping_web_test.dart        main.<fn>
  dart:async                                            runZoned
  test/src/common.dart 184:14                           testWithoutContext.<fn>
  test/src/common.dart 183:18                           testWithoutContext.<fn>
  test/src/common.dart 154:18                           test.<fn>
  test/src/common.dart 150:5                            test.<fn>
  

01:05 +0 -1: loading test/web.shard/vm_service_web_test.dart                                                                                                                                           
01:06 +0 -1: loading test/web.shard/vm_service_web_test.dart                                                                                                                                           
01:07 +0 -1: loading test/web.shard/vm_service_web_test.dart    
```

**Comment by jmagman** [comment]
Forward duping to https://github.com/flutter/flutter/issues/83260 since @bkonyi is already assigned to that one.
