### ISSUE TITLE
flutter doesn't accept android-sdk folder as android sdk location

### ISSUE THREAD

**Issue by roalli88** [flutter/flutter#81611]
flutter doesn't recognise my android-sdk folder. ANDROID_HOME points to the folder that contains android-sdk and i have used flutter config --android-sdk "/home/user/<location_of_android_sdk> and still it doesn't have any effect.

## Logs

<details>
<summary>Logs</summary>

[user$] flutter config --android-sdk /home/user/android-sdk/
```

 Setting "android-sdk" value to "/home/user/android-sdk/".

 You may need to restart any open editors for them to read new settings.

```
[user$] ls /home/user/android-sdk/

```
build-tools  licenses  patcher  platform-tools  platforms  sources  tools

```

[user$] flutter doctor 
```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale C)
[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /home/user/android-sdk/
      but Android SDK not found at this location.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

</details>

**Comment by roalli88** [comment]
For some reason, simply running "flutter run" from the project directory resolved most of the issues. It now recognises the android SDK location. 
The only issue left is the android licenses.

[user$] flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale C)
    • Flutter version 2.0.6 at /home/user/flutter
    • Framework revision 1d9032c7e1 (2 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/user/android-sdk/
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/user/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 15.0.2+7)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /opt/idea-IC-211.7142.45
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] Connected device (1 available)
    • TA 1012 (mobile) • NB1GAS3862407493 • android-arm64 • Android 9 (API 28)


```

[user$] flutter doctor --android-licenses 
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)


```

**Comment by roalli88** [comment]
It seems the licenses issue has no negative effect on using flutter.
