### ISSUE TITLE
Fetching error when archive for release iOS

### ISSUE THREAD

**Issue by jaydipgodhani** [flutter/flutter#81642]
Please check the below error which fetching every time when archive for release iOS

```console
Unhandled exception:
Invalid argument(s): Trying to serialize orphaned getter reference.
Orphaned named node NeumorphicProperties.bevel (Field:41631)
Linked node NeumorphicProperties.bevel (Procedure:2098332)
#0      BinaryPrinter.visitField (package:kernel/binary/ast_to_binary.dart:1293:7)
#1      Field.accept (package:kernel/ast.dart:1892:40)
#2      BinaryPrinter.writeFieldNode (package:kernel/binary/ast_to_binary.dart:426:10)
#3      BinaryPrinter.writeFieldNodeList (package:kernel/binary/ast_to_binary.dart:319:7)
#4      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1174:5)
#5      Class.accept (package:kernel/ast.dart:1317:38)
#6      BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:433:10)
#7      BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:328:7)
#8      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1015:5)
#9      Library.accept (package:kernel/ast.dart:506:38)
#10     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:412:10)
#11     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:721:9)
#12     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:564:7)
#13     Timeline.timeSync (dart:developer/timeline.dart:163:22)
#14     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:546:14)
#15     FrontendCompiler.writeDillFile (package:frontend_server/frontend_server.dart:676:13)
#16     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:552:13)
<asynchronous suspension>
#17     starter (package:flutter_frontend_server/server.dart:180:12)
<asynchronous suspension>
#18     main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>
```

**Comment by TahaTesser** [comment]
Hi @jaydipgodhani 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and `flutter build ios -v` ('archive" as in  `build ios`?) logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
