### ISSUE TITLE
'_inlines.isEmpty': is not true error when displaying markdown

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#81759]
The following example throws this error. 
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Container(bg: Color(0xff303030)):
'package:flutter_markdown/src/builder.dart': Failed assertion: line 155 pos 12: '_inlines.isEmpty': is not true.

The relevant error-causing widget was: 
  Container file:///Users/thinkdigital/IdeaProjects/fritter_for_reddit/lib/widgets/desktop/subreddit_side_panel.dart:54:12
When the exception was thrown, this was the stack: 
flutter/flutter_markdown#2      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:155:12)
flutter/flutter_markdown#3      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:175:25)
flutter/flutter_markdown#4      _MarkdownWidgetState.didUpdateWidget (package:flutter_markdown/src/widget.dart:144:7)
flutter/flutter_markdown#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:4690:58)
flutter/flutter_markdown#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```dart
class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MarkdownBody(
      data:
          '''###### [ [ SERIOUS ] ](http://www.reddit.com[/r/askreddit](/r/askreddit)/submit?selftext=true&amp;title=%5BSerious%5D)


##### [Rules](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_rules):
1. You must post a clear and direct question in the title. The title may contain two, short, necessary context sentences.
No text is allowed in the textbox. Your thoughts/responses to the question can go in the comments section. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_1-)

2. Any post asking for advice should be generic and not specific to your situation alone. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_2-)

3. Askreddit is for open-ended discussion questions. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_3-)

4. Posting, or seeking, any identifying personal information, real or fake, will result in a ban without a prior warning. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_4-)

5. Askreddit is not your soapbox, personal army, or advertising platform. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_5-)

6. [Serious] tagged posts are off-limits to jokes or irrelevant replies. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_6-)

7. Soliciting money, goods, services, or favours is not allowed. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_7-)

8. Mods reserve the right to remove content or restrict users' posting privileges as necessary if it is deemed detrimental to the subreddit or to the experience of others. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_8-)

9. Comment replies consisting solely of images will be removed. [more &gt;&gt;](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/index#wiki_-rule_9-)

##### If you think your post has disappeared, see spam or an inappropriate post, please do not hesitate to [contact the mods](https://www.reddit.com/message/compose?to=%2Fr%2FAskReddit), we're happy to help.

---

#### Tags to use:

&gt; ## [[Serious]](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/mod_announcements#wiki_.5Bserious.5D_post_tags)

### Use a **[Serious]** post tag to designate your post as a serious, on-topic-only thread.

-

#### Filter posts by subject:

[Mod posts](http://ud.reddit.com[/r/AskReddit](/r/AskReddit)/#ud)
[Serious posts](http://dg.reddit.com[/r/AskReddit](/r/AskReddit)/#dg)
[Megathread](http://bu.reddit.com[/r/AskReddit](/r/AskReddit)/#bu)
[Breaking news](http://nr.reddit.com[/r/AskReddit](/r/AskReddit)/#nr)
[Unfilter]([/r/AskReddit](/r/AskReddit))

-

### Do you have ideas or feedback for Askreddit? Submit to [/r/IdeasForAskReddit](/r/IdeasForAskReddit).

-

### Please use spoiler tags to hide spoilers. `&gt;!insert spoiler here!&lt;`

-

#### Other subreddits you might like:
some|header
:---|:---
[Ask Others](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/sidebarsubs#wiki_ask_others)|[Self &amp; Others](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/sidebarsubs#wiki_self_.26amp.3B_others)
[Find a subreddit](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/sidebarsubs#wiki_find_a_subreddit)|[Learn something](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/sidebarsubs#wiki_learn_something)
[Meta Subs](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/sidebarsubs#wiki_meta)|[What is this ___](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/sidebarsubs#wiki_what_is_this______)
[AskReddit Offshoots](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/sidebarsubs#wiki_askreddit_offshoots)|[Offers &amp; Assistance](https://www.reddit.com[/r/AskReddit](/r/AskReddit)/wiki/sidebarsubs#wiki_offers_.26amp.3B_assistance)


-

### Ever read the reddiquette? [Take a peek!](/wiki/reddiquette)

[](#/RES_SR_Config/NightModeCompatible)''',
    );
  }
}
```

**Comment by darshankawar** [comment]
Verified this using latest package version and on latest master and stable versions and don't see the exception anymore.

<img width="345" alt="Screenshot 2021-09-02 at 5 23 16 PM" src="https://user-images.githubusercontent.com/67046386/131839344-d8e8ebcd-4259-4f36-a69b-ff27e3c88f61.png">

The bottom overflow exception isn't related to the package but code implementation.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.159

• No issues found!



• No issues found!

[✓] Flutter (Channel master, 2.6.0-1.0.pre.160, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.160 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f77c453ab6 (2 hours ago), 2021-09-02 00:58:19 -0400
    • Engine revision d877a4bbcd
    • Dart version 2.15.0 (build 2.15.0-68.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.159

• No issues found!




```

</details>

Closing this as fixed, since the original issue `package:flutter_markdown/src/builder.dart': Failed assertion: line 155 pos 12: '_inlines.isEmpty': is not true.
` doesn't occur anymore.
