### ISSUE TITLE
WidgetFinder should look for Offstage elements and provide a meaningful error message

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#8181]
If it can't find an element because the element is offstage, it currently throws a StateError down the stack, like so:

```

Bad state: No element

#0      Iterable.single (dart:core/iterable.dart:501)
#1      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:424:41)
#2      WidgetController.getCenter (package:flutter_test/src/controller.dart:396:12)
#3      WidgetController.tap (package:flutter_test/src/controller.dart:255:18)
```

It'd be better if it detected that it wasn't finding the element because it was offstage and provided a better error message

**Comment by tvolkert** [comment]
@jacob314 do you know if this is relevant any more?
