### ISSUE TITLE
Flutter: app:compileDebugJacaWithJavac Error

### ISSUE THREAD

**Issue by madd-project** [flutter/flutter#81886]
> can you please provide your `flutter doctor -v` , 
> your `flutter run --verbose` 
> and your `pubspec.yaml` 
> or if possible a reproducible minimal code sample.
> Thank you
> 
> _Originally posted by @iapicca in https://github.com/flutter/flutter/issues/56861#issuecomment-626676884_

This is my Output when i ran, `flutter run --verbose`
Is there any Fix?

I tried changing SDK version, 
I tried running Flutter clean
I accepted all the Licenses 
and my Flutter doctor is also well and good.
still i am facing this issue,

<details> 
<summary>logs</summary> 
	
```console
F:\Apllications\toodo\toodo\android>flutter run --verbose
[  +82 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +112 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] adc687823a831bbebe28bdccfac1a628ca621513
[        ] executing: [C:\flutter/] git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[  +79 ms] Exit code 0 from: git tag --points-at adc687823a831bbebe28bdccfac1a628ca621513
[        ] 2.0.5
[  +42 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +79 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +103 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[+2344 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +82 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +69 ms] List of devices attached
           4200acb99791a43d       device product:j7maxlteins model:SM_G615F device:j7maxlte transport_id:2
[   +9 ms] C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4200acb99791a43d shell getprop
[ +114 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] Changing current working directory to: F:\Apllications\toodo\toodo
[  +68 ms] Skipping pub get: version match.
[  +80 ms] Found plugin emoji_picker at C:\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.1.0\
[  +19 ms] Found plugin flutter_local_notifications at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+1\
[   +8 ms] Found plugin gallery_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.1.0\
[  +27 ms] Found plugin image_gallery_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.6.9\
[  +20 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +3 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +3 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +7 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +24 ms] Found plugin share at C:\flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.1\
[   +3 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +4 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +5 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +31 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +3 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +1 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[ +248 ms] Found plugin emoji_picker at C:\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.1.0\
[  +13 ms] Found plugin flutter_local_notifications at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+1\
[   +9 ms] Found plugin gallery_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\gallery_saver-2.1.0\
[  +19 ms] Found plugin image_gallery_saver at C:\flutter\.pub-cache\hosted\pub.dartlang.org\image_gallery_saver-1.6.9\
[  +16 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.1\
[   +2 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.0\
[   +6 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +14 ms] Found plugin share at C:\flutter\.pub-cache\hosted\pub.dartlang.org\share-2.0.1\
[   +3 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +2 ms] Found plugin shared_preferences_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+11\
[   +4 ms] Found plugin shared_preferences_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +28 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +2 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +5 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[   +3 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +40 ms] Generating F:\Apllications\toodo\toodo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +93 ms] ro.hardware = mt6757
[        ] ro.build.characteristics = default
[  +53 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +7 ms] complete
[   +4 ms] Launching lib\main.dart on SM G615F in debug mode...
[   +5 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata --output-dill
C:\Users\ADMINI~1\AppData\Local\Temp\flutter_tools.e08cca47\flutter_tool.da588966\app.dill --packages F:\Apllications\toodo\toodo\.dart_tool\package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\cache.dill.track.dill
[  +28 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4200acb99791a43d shell -x logcat -v time -t 1
[ +860 ms] <- compile package:toodo/main.dart
[ +160 ms] --------- beginning of main
                    05-05 11:40:54.907 D/NetworkController.MobileSignalController(0/4)( 1522): getMobileIconGroup(): 13
[  +18 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +75 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: C:\Users\Administrator\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +76 ms] Building APK
[  +36 ms] Running Gradle task 'assembleDebug'...
[  +27 ms] Using gradle from F:\Apllications\toodo\toodo\android\gradlew.bat.
[  +54 ms] F:\Apllications\toodo\toodo\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +38 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +278 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +3 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +4 ms] executing: [F:\Apllications\toodo\toodo\android/] F:\Apllications\toodo\toodo\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm
-Ptarget=F:\Apllications\toodo\toodo\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2555 ms] > Configure project :emoji_picker
[ +127 ms] WARNING: The option setting 'android.enableR8=true' is deprecated.
[  +69 ms] It will be removed in version 5.0 of the Android Gradle plugin.
[   +9 ms] You will no longer be able to disable R8
[+1315 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:mergeDebugAssets'.
[        ] > Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
[        ]    > Could not create task ':app:minifyReleaseWithR8'.
[        ]       > Trailing char < > at index 48: C:\Users\Administrator\AppData\Local\Android\sdk \package.xml
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 3s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[ +593 ms] Running Gradle task 'assembleDebug'... (completed in 5.1s)
[+8166 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 15,844ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +175 ms] ensureAnalyticsSent: 172ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +14 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

</details>

**Comment by iapicca** [comment]
@madd-project 
can you provide your  `flutter doctor -v` and most importantly a [reproducible minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example)

> > can you please provide your `flutter doctor -v` ,
> > your `flutter run --verbose`
> > and your `pubspec.yaml`
> > or if possible a reproducible minimal code sample.
> > Thank you
> > _Originally posted by @iapicca in [#56861 (comment)](https://github.com/flutter/flutter/issues/56861#issuecomment-626676884)_

**Comment by madd-project** [comment]
``` 
F:\Apllications\toodo\toodo>flutter doctor -v
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.17134.1304], locale en-IN)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM G615F (mobile) • 4200acb99791a43d • android-arm    • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!```

**Comment by TahaTesser** [comment]
Hi @madd-project 
Thanks for filing the issue
```
[        ]       > Trailing char < > at index 48: C:\Users\Administrator\AppData\Local\Android\sdk \package.xml
```

The error is probably caused by space in your path, please remove the space and try again https://github.com/facebook/react-native/issues/20726
