### ISSUE TITLE
[CAMERA] Black screen 

### ISSUE THREAD

**Issue by II11II** [flutter/flutter#81893]
Code: #81816
BUG:
After Fast and many times changing camera from front to back, the black screen apears

https://user-images.githubusercontent.com/45257709/117115544-ad622980-ada6-11eb-9f4b-ecb6a55f458c.mp4

**LOGS**
```

I/flutter (26583): [A CameraController was used after being disposed.
I/flutter (26583): Once you have called dispose() on a CameraController, it can no longer be used., #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
I/flutter (26583): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
I/flutter (26583): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:234:12)
I/flutter (26583): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:309:5)
I/flutter (26583): #4      CameraController.initialize (package:camera/src/camera_controller.dart:290:7)
I/flutter (26583): <asynchronous suspension>
I/flutter (26583): #5      _AppCameraState.onNewCameraSelected (package:yool/app/presentation/page/camera/app_camera.dart:131:7)
I/flutter (26583): <asynchronous suspension>
I/flutter (26583): ]
I/ViewRootImpl@7622ea3[MainActivity](26583): ViewPostIme pointer 0
I/ViewRootImpl@7622ea3[MainActivity](26583): ViewPostIme pointer 1
I/CameraManagerGlobal(26583): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client uz.yim.yool API Level 2
D/SensorManager(26583): unregisterListener ::   
I/Camera  (26583): [FPS Range Available] is:[15, 15]
I/Camera  (26583): [FPS Range Available] is:[15, 20]
I/Camera  (26583): [FPS Range Available] is:[20, 20]
I/Camera  (26583): [FPS Range Available] is:[10, 24]
I/Camera  (26583): [FPS Range Available] is:[15, 24]
I/Camera  (26583): [FPS Range Available] is:[24, 24]
I/Camera  (26583): [FPS Range Available] is:[7, 30]
I/Camera  (26583): [FPS Range Available] is:[10, 30]
I/Camera  (26583): [FPS Range Available] is:[15, 30]
I/Camera  (26583): [FPS Range Available] is:[30, 30]
I/Camera  (26583): [FPS Range] is:[7, 30]
D/SensorManager(26583): registerListener :: 1, LSM6DSL Acceleration Sensor, 200000, 0,  
I/CameraManagerGlobal(26583): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client uz.yim.yool API Level 2
I/CameraManagerGlobal(26583): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client uz.yim.yool API Level 2
W/System  (26583): A resource failed to call release. 
I/chatty  (26583): uid=11124(uz.yim.yool) FinalizerDaemon identical 8 lines
W/System  (26583): A resource failed to call release. 
I/ViewRootImpl@7622ea3[MainActivity](26583): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(26583): prepareNavigationBarInfo() DecorView@1865321[MainActivity]
D/InputMethodManager(26583): getNavigationBarColor() -855310
I/ViewRootImpl@7622ea3[MainActivity](26583): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(26583): prepareNavigationBarInfo() DecorView@1865321[MainActivity]
D/InputMethodManager(26583): getNavigationBarColor() -855310
I/ViewRootImpl@7622ea3[MainActivity](26583): ViewPostIme pointer 0
I/SurfaceView(26583): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{4554559 V.E...... ........ 0,0-720,1450} of ViewRootImpl@7622ea3[MainActivity]
I/SurfaceView(26583): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{4554559 V.E...... ........ 0,0-720,1450}
I/mali_egl(26583): eglDestroySurface() in
I/mali_winsys(26583): delete_surface() [720x1450] return
I/mali_egl(26583): eglDestroySurface() out
W/libEGL  (26583): EGLNativeWindowType 0x7187faa010 disconnect failed
I/SurfaceView(26583): remove() io.flutter.embedding.android.FlutterSurfaceView{4554559 V.E...... ........ 0,0-720,1450} Surface(name=SurfaceView - uz.yim.yool/uz.yim.yool.MainActivity@4554559@0)/@0x7547ffc
I/mali_egl(26583): eglDestroySurface() in
I/mali_winsys(26583): delete_surface() [720x1480] return
I/mali_egl(26583): eglDestroySurface() out
W/libEGL  (26583): EGLNativeWindowType 0x71869dc550 disconnect failed
I/ViewRootImpl@7622ea3[MainActivity](26583): Relayout returned: old=(0,0,720,1480) new=(0,0,720,1480) req=(720,1480)8 dur=27 res=0x5 s={false 0} ch=true
I/CameraManagerGlobal(26583): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client uz.yim.yool API Level 2
I/CameraManagerGlobal(26583): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client uz.yim.yool API Level 2
D/SensorManager(26583): unregisterListener ::   
I/ViewRootImpl@7622ea3[MainActivity](26583): stopped(true) old=false
I/SurfaceView(26583): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{4554559 V.E...... ........ 0,0-720,1450} of ViewRootImpl@7622ea3[MainActivity]
I/ViewRootImpl@7622ea3[MainActivity](26583): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(26583): prepareNavigationBarInfo() DecorView@1865321[MainActivity]
D/InputMethodManager(26583): getNavigationBarColor() -855310
D/InputTransport(26583): Input channel destroyed: 'ClientS', fd=103
W/System  (26583): A resource failed to call release. 
W/System  (26583): A resource failed to call release. 
W/System  (26583): A resource failed to call release. 
W/System  (26583): A resource failed to call release. 
W/System  (26583): A resource failed to call release. 
W/System  (26583): A resource failed to call release. 
W/System  (26583): A resource failed to call release. 
```

**Comment by TahaTesser** [comment]
Hi @II11II 
Thanks for filing the issue,  I can reproduce a blank screen when switching the camera on `android` and `iOS`  using `camera: ^0.8.1`

### Preview
| `android` | `iOS` |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/117155186-3a1be000-adc5-11eb-9e56-772419c26fc5.gif" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/117155993-ed84d480-adc5-11eb-9229-88834edac6f2.gif" height="450" /> |

<details> 
<summary>code sample</summary> 

```dart
``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.6 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (5 available)
    • SM M025F (mobile)      • R9ZR205XX0A   • android-arm    • Android 10 (API 29)
    • emulator-5554 (mobile) • emulator-5554 • android-x86    • Android 4.1.2 (API 16) (emulator)
    • Windows (desktop)      • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)           • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)             • edge          • web-javascript • Microsoft Edge 90.0.818.51

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.227, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-1.0.pre.227 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f1d1414cc (25 hours ago), 2021-05-04 06:17:19 -0700
    • Engine revision 378e4dbc41
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (5 available)
    • SM M025F (mobile)      • R9ZR205XX0A   • android-arm    • Android 10 (API 29)
    • emulator-5554 (mobile) • emulator-5554 • android-x86    • Android 4.1.2 (API 16) (emulator)
    • Windows (desktop)      • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)           • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)             • edge          • web-javascript • Microsoft Edge 90.0.818.51

! Doctor found issues in 1 category.
```
		
</details>




Related to https://github.com/flutter/flutter/issues/78417, `camera` probably re-initializing hence the blank screen

**Comment by TahaTesser** [comment]
The issue is reproducible on the latest `camera: ^0.9.2+2` in release and debug modes on iOS & Android using official [sample](https://pub.dev/packages/camera/example)  just like previews in https://github.com/flutter/flutter/issues/81893#issuecomment-832727763 

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos    • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.6.0-1.0.pre.170, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.170 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4069c6355b (6 hours ago), 2021-09-03 02:11:05 -0400
    • Engine revision d6f6a0fe90
    • Dart version 2.15.0 (build 2.15.0-69.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7583922/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos    • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
		
</details>

✅: No Issue ❗️: Issue reproduced

**Comment by alperefesahin** [comment]
2022 December and the problem is continuing. At least for the temporary solution, how can we show a black screen instead of a white one? @TahaTesser

**Comment by thao-vu-0106** [comment]
> 2022 December and the problem is continuing. At least for the temporary solution, how can we show a black screen instead of a white one? @TahaTesser

i can show black screen by set backgroundColor of Scaffold into black

**Comment by ToyZ-95** [comment]
How to show flip effect using camera plugin?

**Comment by thao-vu-0106** [comment]
I don't know what is flip effect, but CameraPreview will so the color or the screen behind it.
```
Expanded(
                child: Container(
                  decoration: BoxDecoration(
                    color: Colors.red,
                    border: Border.all(
                      color:
                      controller != null && controller!.value.isRecordingVideo
                          ? Colors.redAccent
                          : Colors.grey,
                      width: 3.0,
                    ),
                  ),
                  child: Padding(
                    padding: const EdgeInsets.all(1.0),
                    child: Center(
                      child: _cameraPreviewWidget(),
                    ),
                  ),
                ),
              ),
```
Like in this sample which is the example of library camera in pub.dev, when change color BoxDecoration to red, it will show Red Screen to black Screen(Camera preview need time to init) then CameraPreview.
If you want to show a widget when flip camera you can work around with Stack like that:
```
Stack(
        children: [
          Expanded(child: Container(color: Colors.white,)),
          Expanded(
            child: Container(
              child: Padding(
                padding: const EdgeInsets.all(1.0),
                child: Center(
                  child: _cameraPreviewWidget(),
                ),
              ),
            ),
          ),
)
```
This code will show White screen then Black screen then CameraPreview. Hope this help


> How to show flip effect using camera plugin?

**Comment by ToyZ-95** [comment]
> I don't know what is flip effect, but CameraPreview will so the color or the screen behind it.
> 
> ```
> Expanded(
>                 child: Container(
>                   decoration: BoxDecoration(
>                     color: Colors.red,
>                     border: Border.all(
>                       color:
>                       controller != null && controller!.value.isRecordingVideo
>                           ? Colors.redAccent
>                           : Colors.grey,
>                       width: 3.0,
>                     ),
>                   ),
>                   child: Padding(
>                     padding: const EdgeInsets.all(1.0),
>                     child: Center(
>                       child: _cameraPreviewWidget(),
>                     ),
>                   ),
>                 ),
>               ),
> ```
> 
> Like in this sample which is the example of library camera in pub.dev, when change color BoxDecoration to red, it will show Red Screen to black Screen(Camera preview need time to init) then CameraPreview. If you want to show a widget when flip camera you can work around with Stack like that:
> 
> ```
> Stack(
>         children: [
>           Expanded(child: Container(color: Colors.white,)),
>           Expanded(
>             child: Container(
>               child: Padding(
>                 padding: const EdgeInsets.all(1.0),
>                 child: Center(
>                   child: _cameraPreviewWidget(),
>                 ),
>               ),
>             ),
>           ),
> )
> ```
> 
> This code will show White screen then Black screen then CameraPreview. Hope this help
> 
> > How to show flip effect using camera plugin?

Flip effect while switching camera from back to front and vice-versa

**Comment by tahaf22labs** [comment]
Or can we show blurred version of the last frame while we make a switch?

**Comment by ToyZ-95** [comment]
> Or can we show blurred version of the last frame while we make a switch?

Yeah same, How can we show that?
