### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for .\Microsoft\Edge\Application\msedge.exe.

### ISSUE THREAD

**Issue by Sushil787** [flutter/flutter#81892]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for .\Microsoft\Edge\Application\msedge.exe.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:247:53)
#6      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:225:35)
<asynchronous suspension>
#7      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:133:17)
<asynchronous suspension>
#8      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:521:9)
<asynchronous suspension>
#9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\flutter_windows_2.0.5-stable\flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 90.0.818.51 (unsupported)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: adc687823a831bbebe28bdccfac1a628ca621513

**Comment by pedromassangocode** [comment]
Hi @Sushil787 
It seems that you are trying to run Flutter on a unsupported device: `    • Edge (web) • edge • web-javascript • Microsoft Edge 90.0.818.51 (unsupported)`

Please install Chrome or any other supported device to test your Flutter app.
Thank you

**Comment by Sushil787** [comment]
hi @pedromassangocode  Thank you  !
