### ISSUE TITLE
Cant accept android license

### ISSUE THREAD

**Issue by Nollknolle** [flutter/flutter#81923]
## Steps to Reproduce

1. If I am doing "flutter doctor --android-licenses" I got this error. Java is installed correctly:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
    at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
    at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
    at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
    at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
    at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 5 more
```

**Comment by Nollknolle** [comment]
<img width="726" alt="Bildschirmfoto 2021-05-05 um 21 02 50" src="https://user-images.githubusercontent.com/62543404/117195196-4879f400-ade5-11eb-938a-69be118d726d.png">

**Comment by narumishi** [comment]
Try to download `Android SDK command-line Tool` in Android Studio's SDK Tool tab.

**Comment by Nollknolle** [comment]
> Try to download `Android SDK command-line Tool` in Android Studio's SDK Tool tab.

Thanks that helps :D
