### ISSUE TITLE
android studio  and flutter

### ISSUE THREAD

**Issue by Yinzeyu** [flutter/flutter#81946]
flutter sdk 2.0.6 
android studio 4.2 stable  jdk 11 

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

flutter sdk Not compatible  jdk 11

**Comment by darshankawar** [comment]
@Yinzeyu 
Can you try the solutions mentioned in [this](https://github.com/flutter/flutter/issues/56778) issue and see if any of them helps to resolve this ?

Also, there's similar open issue describing your case, https://github.com/flutter/flutter/issues/80966

Closing this as duplicate.
