### ISSUE TITLE
not able to install flutter android licence command not working flutter doctor --android-licenses

### ISSUE THREAD

**Issue by Roboromeo1** [flutter/flutter#81943]
```
(base) macbook@Macbooks-MacBook-Pro ~ % flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
(base) macbook@Macbooks-MacBook-Pro ~ % flutter channel 
Flutter channels:
  master
  dev
  beta
* stable
(base) macbook@Macbooks-MacBook-Pro ~ % 
```

**Comment by darshankawar** [comment]
@Roboromeo1 
Please check the comments / solutions mentioned in [this](https://github.com/flutter/flutter/issues/56778) similar issue and see if any of them helps to resolve the issue.

Also, there's similar open issue describing your case, https://github.com/flutter/flutter/issues/80966

Closing this as duplicate. If you still face the same issue after following the linked issue, write in comments in the original open issue (80966).
Thanks.
