### ISSUE TITLE
ListView throws '_drag == null': is not true exception

### ISSUE THREAD

**Issue by ModWU** [flutter/flutter#81952]
I had a problem with my demo of ListView sliders. I think it's a bug in the  flutter framework. Hopefully the Flutter team will fix it！

<details>
  <summary>Demo1</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'dart:math';
import 'dart:math' as math;

void main() => runApp(ListViewPortDemo());

class ListViewPortDemo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _ListViewPortDemoState();
}

class _ListViewPortDemoState extends State<ListViewPortDemo> {

  List<double>? _initHeights;

  late ScrollController _scrollController;
  double _listSize = 450;

  Axis _axis = Axis.vertical;
  bool _reverse = true;

  final Random rd = Random();

  void updateHeights() {
    final int count = _initHeights?.length ?? rd.nextInt(20) + 10000;
    _initHeights = List.generate(count, (index) => rd.nextDouble() * 100 + 40);
  }

  void _resetListSize() {
    _listSize = rd.nextDouble() * 350 + 100;
  }

  @override
  void initState() {
    super.initState();
    updateHeights();
    _scrollController = ScrollController();
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  Widget _buildText(int index) {
    final Widget child = Text("$index",
      style: TextStyle(
        fontSize: 16,
      ),
    );
    return RotatedBox(
      quarterTurns: _axis == Axis.horizontal ? 1 : 0,
      child: child,
    );
  }

  Widget _buildListView(context) {
    return Container(
      height: _axis == Axis.horizontal
          ? MediaQuery.of(context).size.height - 220
          : _listSize,
      width: _axis == Axis.horizontal ? _listSize : double.infinity,
      color: Colors.black12,
      child: ListView.builder(
        scrollDirection: _axis,
        physics: BouncingScrollPhysics(),
        controller: _scrollController,
        reverse: _reverse,
        itemBuilder: (context, index) {
          return Container(
            height: _axis == Axis.horizontal
                ? double.infinity
                : _initHeights![index],
            width: _axis == Axis.horizontal
                ? _initHeights![index]
                : double.infinity,
            color: Colors
                .primaries[index % Colors.primaries.length],
            alignment: Alignment.center,
            child: _buildText(index),
          );
        },
        itemCount: _initHeights!.length,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: SingleChildScrollView(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                Stack(
                  children: [
                    Builder(builder: (context) {
                      return _buildListView(context);
                    }),
                    Positioned(
                      child: Center(
                        child: Transform.rotate(
                          angle: _axis == Axis.horizontal ? math.pi / 2 : 0,
                          child: Text(
                            "center",
                            style: TextStyle(
                              color: Colors.redAccent,
                              fontStyle: FontStyle.italic,
                              fontWeight: FontWeight.bold,
                              fontSize: 10.5,
                              backgroundColor: Colors.white,
                            ),
                          ),
                        ),
                      ),
                      top: 0,
                      bottom: 0,
                      left: 0,
                      right: 0,
                    ),
                    Positioned(
                      child: Offstage(
                        offstage: _axis != Axis.horizontal,
                        child: VerticalDivider(
                          color: Colors.black,
                          width: 2.0,
                        ),
                      ),
                      top: 0,
                      bottom: 0,
                      left: 0,
                      right: 0,
                    ),
                    Positioned(
                      child: Offstage(
                        offstage: _axis != Axis.vertical,
                        child: Divider(
                          height: 2.0,
                          color: Colors.black,
                        ),
                      ),
                      top: 0,
                      bottom: 0,
                      left: 0,
                      right: 0,
                    ),
                  ],
                ),
                Wrap(
                  spacing: 24,
                  children: [
                    TextButton(
                      onPressed: () {
                        setState(() {
                          _resetListSize();
                        });
                      },
                      child: Text("Resize"),//the first step
                    ),
                    TextButton(
                      onPressed: () {
                        setState(() {
                          _axis = _axis == Axis.horizontal
                              ? Axis.vertical
                              : Axis.horizontal;
                        });
                      },
                      child: Text("Change Direction"),//the second step
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
  <summary>Demo2</summary>

```
import 'dart:math';
import 'package:flutter/material.dart';

void main() => runApp(SimpleScrollViewDemo());

class SimpleScrollViewDemo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _SimpleScrollViewDemoState();
}

class _SimpleScrollViewDemoState extends State<SimpleScrollViewDemo> {
  double _height = 360;
  Axis _axis = Axis.vertical;
  Random _random = Random();

  ScrollController _controller = ScrollController();
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            _buildListView(),
            _buildBtn(),
          ],
        ),
      ),
    );
  }

  Widget _buildBtn() {
    return Row(
      children: [
        TextButton(
          onPressed: () {
            setState(() {
              _height = _random.nextInt(100) + 120;
            });
          },
          child: Text("Resize"),
        ),
        TextButton(
          onPressed: () {
            setState(() {
              _axis =
                  _axis == Axis.horizontal ? Axis.vertical : Axis.horizontal;
            });
          },
          child: Text("Change Direction"),
        ),
      ],
    );
  }

  Widget _buildListView() {
    return Container(
      color: Colors.black12,
      height: _height,
      width: double.infinity,
      child: ListView.builder(
        scrollDirection: _axis,
        controller: _controller,
        itemBuilder: (_, index) {
          return Container(
            color: Colors.primaries[index % Colors.primaries.length],
            height: _axis == Axis.vertical ? (_random.nextDouble() * 80 + 20) : null,
            width: _axis == Axis.horizontal ? (_random.nextDouble() * 80 + 20) : null,
            alignment: Alignment.center,
            child: Text("$index"),
          );
        },
      ),
    );
  }
}

```
</details>

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. Steps to reproduce the problem: 
_Step 1: Click the **`Resize`** button.
Step 2: Click the **`Change Direction`** button.
Step 3: Swipe the screen freely._

**Expected results:** 
The `ListView` scrolls normally, and the program does not throw an exception.

**Actual results:** 
_Demo1:_
The `ListView` scrolls exception, and the program always throws an exception:
_**'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 582 pos 12: '_drag == null': is not true.**_

_Demo2:_
The `ListView` simply scrolls exception, but the program doesn't throw an error.

<details>
  <summary>Logs</summary>

```
Launching lib\main.dart on M6 Note in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:61159/scpcD28kbaI=/ws
Syncing files to device M6 Note...
I/art     (22028): IsDexFileNeededDisableVerify for /system/framework/QPerformance.jar
I/art     (22028): GetPkgNameFromDexFile return /system/framework/QPerformance.jar

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 582 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:582:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:403:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:403:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:267:7)
...
Handler: "onDown"
Recognizer: HorizontalDragGestureRecognizer#cef67
  start behavior: start
====================================================================================================

======== Exception caught by gesture ===============================================================
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 591 pos 12: '_drag == null': is not true.
====================================================================================================
```

```
Analyzing flutter_new_test...
No issues found! (ran in 3.0s)
```

```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.17763.1817], locale zh-CN)
    • Flutter version 2.0.2 at C:\wuchaochao\flutter\tools\flutter
    • Framework revision 8962f6dc68 (8 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\wuchaochao\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\wuchaochao\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Users\wuchaochao\AppData\Local\Chromium\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\wuchaochao\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • M6 Note (mobile) • 721QADRR45FUF • android-arm64  • Android 7.1.2 (API 25)
    • Chrome (web)     • chrome        • web-javascript • unknown

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@ModWU 
I tried your demo 1 code sample on latest stable (2.0.6) and followed the steps as mentioned, but didn't get the exception you mentioned.


https://user-images.githubusercontent.com/67046386/117273660-f7680f80-ae79-11eb-9faa-811281ad4073.mov



For Demo2, it seems to be using `getx` plugin which is 3rd party, can you try by removing it and relevant plugin code and check if you still get the same error ? Also, demo2 uses `scroll_manager.dart` which is missing from your code sample.

Also, can you try to upgrade to 2.0.6 and check if issue still persists with same code sample ?

<details>
<summary> flutter doctor -v </summary>

```


[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.

```

</details>

**Comment by xu-baolin** [comment]
@darshankawar hi, I can repro this with the latest master code.
Do not scroll before changing the direction.
After changing the direction, first, drag in the direction of the cross axis.

**Comment by ModWU** [comment]
> 
> 
> @ModWU
> I tried your demo 1 code sample on latest stable (2.0.6) and followed the steps as mentioned, but didn't get the exception you mentioned.
> 81952.mov
> 
> For Demo2, it seems to be using `getx` plugin which is 3rd party, can you try by removing it and relevant plugin code and check if you still get the same error ? Also, demo2 uses `scroll_manager.dart` which is missing from your code sample.
> 
> Also, can you try to upgrade to 2.0.6 and check if issue still persists with same code sample ?
> flutter doctor -v


> 
> 
> @ModWU
> I tried your demo 1 code sample on latest stable (2.0.6) and followed the steps as mentioned, but didn't get the exception you mentioned.
> 81952.mov
> 
> For Demo2, it seems to be using `getx` plugin which is 3rd party, can you try by removing it and relevant plugin code and check if you still get the same error ? Also, demo2 uses `scroll_manager.dart` which is missing from your code sample.
> 
> Also, can you try to upgrade to 2.0.6 and check if issue still persists with same code sample ?
> flutter doctor -v



> 
> 
> @ModWU
> I tried your demo 1 code sample on latest stable (2.0.6) and followed the steps as mentioned, but didn't get the exception you mentioned.
> 81952.mov
> 
> For Demo2, it seems to be using `getx` plugin which is 3rd party, can you try by removing it and relevant plugin code and check if you still get the same error ? Also, demo2 uses `scroll_manager.dart` which is missing from your code sample.
> 
> Also, can you try to upgrade to 2.0.6 and check if issue still persists with same code sample ?
> flutter doctor -v
> 
> ```
> 
> 
> [✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
>     locale en-GB)
>     • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
>     • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
>     • Engine revision 05e680e202
>     • Dart version 2.12.3
> 
> [!] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
>         CocoaPods is used to retrieve the iOS and macOS platform side's plugin
>         code that responds to your plugin usage on the Dart side.
>         Without CocoaPods, plugins will not work on iOS or macOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To upgrade see
>       https://guides.cocoapods.org/using/getting-started.html#installation for
>       instructions.
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] VS Code (version 1.55.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.21.0
> 
> [✓] Connected device (3 available)
>     • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
>       • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
>     • macOS (desktop)            • macos                                •
>       darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
>     • Chrome (web)               • chrome                               •
>       web-javascript • Google Chrome 90.0.4430.93
> 
> ! Doctor found issues in 1 category.
> ```



>  from your code sample.

Hi, **Demo2** has been updated, I've just run the test again and the problem is still there! 

https://user-images.githubusercontent.com/16234264/117283301-3dcc6700-ae98-11eb-911f-320012432422.mp4

**flutter doctor -v**

```
C:\wuchaochao\project\scrollview_manager>flutter doctor -v
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.17763.1817], locale zh-CN)
    • Flutter version 2.0.2 at C:\wuchaochao\flutter\tools\flutter
    • Framework revision 8962f6dc68 (8 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\wuchaochao\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\wuchaochao\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Users\wuchaochao\AppData\Local\Chromium\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\wuchaochao\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • M6 Note (mobile) • 721QADRR45FUF • android-arm64  • Android 7.1.2 (API 25)
    • Chrome (web)     • chrome        • web-javascript • unknown

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks. I was able to replicate this on latest master. I guess it is more frequent while using device rather than simulator / emulator.

<details>
<summary> console error log </summary>

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 630 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:630:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:412:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:412:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:276:7)
...
Handler: "onDown"
Recognizer: HorizontalDragGestureRecognizer#1532a
  start behavior: start
====================================================================================================

======== Exception caught by gesture ===============================================================
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 639 pos 12: '_drag == null': is not true.
====================================================================================================



```

</details>

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.229, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.229 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 14d5eab43c (5 hours ago), 2021-05-05 21:51:53 -0700
    • Engine revision 378e4dbc41
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.

```

</details>
