### ISSUE TITLE
Flutter unable to open the app on any device even after reinstalling flutter

### ISSUE THREAD

**Issue by Abhirajshriw** [flutter/flutter#81968]
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty>flutter emulators --launch Pixel_4

<details>
<summary> flutter run --verbose </summary>

```
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty>flutter run --verbose
[ +411 ms] executing: [H:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+8370 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +12 ms] executing: [H:\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[+65960 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +3 ms] 2.0.3
[+2396 ms] executing: [H:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[+1039 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] origin/stable
[   +4 ms] executing: [H:\flutter/] git ls-remote --get-url origin
[ +480 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[+3147 ms] executing: [H:\flutter/] git rev-parse --abbrev-ref HEAD
[ +178 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[+1435 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +15 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +24 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +24 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +32 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+2174 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[+3982 ms] List of devices attached
                    3300cad6a0626279       device product:j7eltexx model:SM_J700F device:j7elte transport_id:1
                    emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm
                    transport_id:2
[ +212 ms] C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe -s 3300cad6a0626279 shell getprop
[ +472 ms] C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +805 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +14 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +29 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1188 ms] Multiple devices found:
[ +107 ms] ro.hardware = samsungexynos7580
[  +31 ms] ro.hardware = ranchu
[ +332 ms] SM J700F (mobile)       • 3300cad6a0626279 • android-arm    • Android 6.0.1 (API 23)
[  +13 ms] sdk gphone x86 (mobile) • emulator-5554    • android-x86    • Android 11 (API 30) (emulator)
[   +2 ms] Chrome (web)            • chrome           • web-javascript • Google Chrome 90.0.4430.93
[   +2 ms] Edge (web)              • edge             • web-javascript • Microsoft Edge 90.0.818.51
[   +5 ms] [1]: SM J700F (3300cad6a0626279)
[   +1 ms] [2]: sdk gphone x86 (emulator-5554)
[   +2 ms] [3]: Chrome (chrome)
[   +3 ms] [4]: Edge (edge)
[  +11 ms] Please choose one (To quit, press "q/Q")
[   +8 ms] :
[+70345 ms] Please choose one (To quit, press "q/Q")
[   +8 ms] :
[+6232 ms] 2
[ +311 ms] Skipping pub get: version match.
[+1601 ms] Generating H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat
app\nifty\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[+1257 ms] Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling
software
                    rendering with "--enable-software-rendering".
[ +157 ms] Initializing file store
[  +64 ms] Skipping target: gen_localizations
[  +85 ms] complete
[  +65 ms] Launching lib\main.dart on sdk gphone x86 in debug mode...
[  +37 ms] H:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
H:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
H:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata --output-dill
C:\Users\VAIO\AppData\Local\Temp\flutter_tools.87c440d0\flutter_tool.c05e4e55\app.dill --packages
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\cache.dill.track.dill
[ +244 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[+42006 ms] Exit code 0 from: C:\Users\VAIO\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[   +7 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.nifty" (Raw: "com.example.nifty")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="nifty" (Raw: "nifty")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.nifty.MainActivity" (Raw: "com.example.nifty.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +34 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v
time -t 1
[ +101 ms] <- compile package:nifty/main.dart
[+15775 ms] --------- beginning of main
                     05-06 15:17:53.968 V/abkp    ( 7585): Is http uri, downloading (uri:
                     https://www.gstatic.com/webref-ondevice/am/20210411/076dab46f8c30d4026d80c4854dab6b155315793.zip)
[  +48 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +233 ms] Android Debug Bridge version 1.0.41
                    Version 31.0.1-7187441
                    Installed as C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe
[  +13 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +285 ms] Building APK
[  +82 ms] Running Gradle task 'assembleDebug'...
[ +107 ms] Using gradle from H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\android\gradlew.bat.
[  +15 ms] H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\android\gradlew.bat mode: 33279 rwxrwxrwx.
[ +258 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+7917 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +51 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +11 ms] executing: [H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\android/]
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+104923 ms] > Task :app:compileFlutterBuildDebug
[+9501 ms] [ +352 ms] executing: [H:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+5434 ms] [+5622 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] [        ] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +3 ms] [   +1 ms] executing: [H:\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[+24592 ms] [+24569 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +11 ms] [        ] 2.0.3
[   +4 ms] [  +91 ms] executing: [H:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +75 ms] [ +105 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] [        ] origin/stable
[   +3 ms] [        ] executing: [H:\flutter/] git ls-remote --get-url origin
[ +103 ms] [  +62 ms] Exit code 0 from: git ls-remote --get-url origin
[   +5 ms] [        ] https://github.com/flutter/flutter.git
[ +183 ms] [ +176 ms] executing: [H:\flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] [  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] [        ] stable
[ +101 ms] [  +96 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +84 ms] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +81 ms] [ +154 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +7 ms] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +150 ms] [ +162 ms] Initializing file store
[  +96 ms] [ +113 ms] Done initializing file store
[ +610 ms] [ +580 ms] Skipping target: gen_localizations
[+12208 ms] [+12207 ms] Skipping target: kernel_snapshot
[+5989 ms] [+6058 ms] Skipping target: debug_android_application
[   +4 ms] [   +1 ms] Persisting file store
[  +99 ms] [  +63 ms] Done persisting file store
[   +6 ms] [  +10 ms] build succeeded.
[ +490 ms] [ +444 ms] "flutter assemble" took 19,406ms.
[   +3 ms] [   +8 ms] ensureAnalyticsSent: 1ms
[   +3 ms] [   +5 ms] Running shutdown hooks
[   +1 ms] [   +1 ms] Shutdown hooks complete
[   +1 ms] [  +13 ms] exiting with code 0
[ +883 ms] Parameter format not correct -
[ +402 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +3 ms] > Task :app:preBuild UP-TO-DATE
[   +3 ms] > Task :app:preDebugBuild UP-TO-DATE
[ +100 ms] > Task :app:compileDebugAidl NO-SOURCE
[ +190 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +3 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[+2798 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[ +614 ms] > Task :app:cleanMergeDebugAssets
[   +4 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +3 ms] > Task :app:compileDebugShaders NO-SOURCE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[+5782 ms] > Task :app:mergeDebugAssets
[ +695 ms] > Task :app:copyFlutterAssetsDebug
[   +4 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +5 ms] > Task :app:generateDebugResources UP-TO-DATE
[+1194 ms] > Task :app:mergeDebugResources UP-TO-DATE
[  +92 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +4 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[ +195 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +3 ms] > Task :app:processDebugManifest UP-TO-DATE
[ +110 ms] > Task :app:processDebugManifestForPackage UP-TO-DATE
[ +997 ms] > Task :app:processDebugResources UP-TO-DATE
[+28999 ms] > Task :app:compileDebugKotlin
[   +3 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[ +685 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +9 ms] > Task :app:compileDebugSources UP-TO-DATE
[   +2 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[   +3 ms] > Task :app:compressDebugAssets UP-TO-DATE
[   +4 ms] > Task :app:processDebugJavaRes NO-SOURCE
[+2583 ms] > Task :app:checkDebugDuplicateClasses
[+5405 ms] > Task :app:dexBuilderDebug
[ +100 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[+1199 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +4 ms] > Task :app:desugarDebugFileDependencies
[ +196 ms] > Task :app:mergeDebugJavaResource
[ +401 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[   +5 ms] > Task :app:mergeDexDebug UP-TO-DATE
[  +89 ms] > Task :app:mergeDebugNativeLibs
[ +201 ms] > Task :app:stripDebugDebugSymbols
[+7605 ms] > Task :app:packageDebug
[ +294 ms] > Task :app:assembleDebug
[ +557 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +4 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +3 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] BUILD SUCCESSFUL in 3m 44s
[   +1 ms] 32 actionable tasks: 13 executed, 19 up-to-date
[ +731 ms] Running Gradle task 'assembleDebug'... (completed in 236.4s)
[+2889 ms] calculateSha: LocalDirectory: 'H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat
app\nifty\build\app\outputs\flutter-apk'/app.apk
[  +40 ms] calculateSha: reading file took 35us
[ +936 ms] calculateSha: computing sha took 932us
[   +9 ms] √ Built build\app\outputs\flutter-apk\app-debug.apk.
[ +567 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[+1004 ms] Exit code 0 from: C:\Users\VAIO\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\build\app\outputs\flutter-apk\app.apk
AndroidManifest.xml
[   +3 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.nifty" (Raw: "com.example.nifty")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="nifty" (Raw: "nifty")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.nifty.MainActivity" (Raw: "com.example.nifty.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +4 ms] Stopping app 'app.apk' on sdk gphone x86.
[   +2 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am
force-stop com.example.nifty
[ +597 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list
packages com.example.nifty
[ +243 ms] Installing APK.
[   +6 ms] Installing build\app\outputs\flutter-apk\app.apk...
[   +1 ms] executing: C:\Users\VAIO\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install -t -r
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty\build\app\outputs\flutter-apk\app.apk
[+12856 ms] Performing Streamed Install

                     adb: failed to install H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat
                     app\nifty\build\app\outputs\flutter-apk\app.apk:
[   +5 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 12.9s)
[   +3 ms] Error: ADB exited with exit code 1
[   +3 ms] Performing Streamed Install

           adb: failed to install H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat
           app\nifty\build\app\outputs\flutter-apk\app.apk:
[   +1 ms] Warning: Failed to install APK.
[   +2 ms] Error launching application on sdk gphone x86.
[  +34 ms] "flutter run" took 4,05,291ms.
[   +9 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +92 ms] ensureAnalyticsSent: 86ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1


```

</details>

```
## When I try "flutter doctor":
H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat app\nifty>flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
   • Flutter version 2.0.3 at H:\flutter
   • Framework revision 4d7946a68d (7 weeks ago), 2021-03-18 17:24:33 -0700
   • Engine revision 3459eb2436
   • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
   • Android SDK at C:\Users\VAIO\AppData\Local\Android\sdk
   • Platform android-S, build-tools 29.0.2
   • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
   • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
   • All Android licenses accepted.

[√] Chrome - develop for the web
   • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
   • Android Studio at C:\Program Files\Android\Android Studio
   • Flutter plugin can be installed from:
      https://plugins.jetbrains.com/plugin/9212-flutter
   • Dart plugin can be installed from:
      https://plugins.jetbrains.com/plugin/6351-dart
   • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
   • IntelliJ at H:\JetBrains\IntelliJ IDEA 2020.2.4
   • Flutter plugin can be installed from:
      https://plugins.jetbrains.com/plugin/9212-flutter
   • Dart plugin can be installed from:
      https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
   • SM J700F (mobile)       • 3300cad6a0626279 • android-arm    • Android 6.0.1 (API 23)
   • sdk gphone x86 (mobile) • emulator-5554    • android-x86    • Android 11 (API 30) (emulator)
   • Chrome (web)            • chrome           • web-javascript • Google Chrome 90.0.4430.93
   • Edge (web)              • edge             • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
```

**Comment by brianngeywo** [comment]
try flutter clean

**Comment by darshankawar** [comment]
@Abhirajshriw 
You seem to have spaces in the folder name, `The Ultimate Chat`.  Can you remove spaces and try again to see if it works ?

**Comment by Abhirajshriw** [comment]
All of my previous projects that I've done a few months ago are also not working even after flutter clean or reinstalling flutter itself. Hence, the issue doesn't have anything to do with the app itself, since the app is just has a default screen that you get when you create a new flutter app. Hence, the problem is not with the app or any other project. Please try to resolve this issue as soon as possible.

**Comment by darshankawar** [comment]
From you logs, it's failing because of:
```

Performing Streamed Install

                     adb: failed to install H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat
                     app\nifty\build\app\outputs\flutter-apk\app.apk:
[   +5 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 12.9s)
[   +3 ms] Error: ADB exited with exit code 1
[   +3 ms] Performing Streamed Install

           adb: failed to install H:\Abhinav\Flutter_Projects\Nifty - The Ultimate Chat
           app\nifty\build\app\outputs\flutter-apk\app.apk:
[   +1 ms] Warning: Failed to install APK.
```

Does the device you are trying on, has sufficient space ? Can you try by unplugging the usb cable and plug it in and see if it helps ?
Can you try that on any other device / emulator and see if it helps ?

Also, check out similar SO [link](https://stackoverflow.com/questions/56367108/adb-exited-with-exit-code-1) and see if any of the solutions works for you.
And check this similar open issue for further reference and solution. https://github.com/flutter/flutter/issues/52887

**Comment by Abhirajshriw** [comment]
I've changed my USB cable, tried on my Galaxy J7, a couple of emulators, web, on my Redmi Note 8, and Moto G4. The same output.

**Comment by Abhirajshriw** [comment]
I can neither create a new flutter app sometimes. Restarting has fixed for me though. This was my question on StackOverflow:

https://stackoverflow.com/questions/67163642/flutter-main-exception-timed-out

**Comment by Abhirajshriw** [comment]
And just a few days before the problem, I think I might have messed up with the SDK too:
https://stackoverflow.com/questions/66613632/flutter-run-error-error-occured-while-preparing-sdk-package

**Comment by darshankawar** [comment]
This doesn't seem to be a bug in framework, but with your setup and how adb is installed in your system. Please follow-up in similar original issue, https://github.com/flutter/flutter/issues/52887
Closing this as duplicate.
