### ISSUE TITLE
Flake in docs shard

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#81985]
https://cirrus-ci.com/task/4677842299518976?logs=main#L144

```
dartdoc:stderr: Stderr output was:
dartdoc:stderr: Unhandled exception:
dartdoc:stderr: git status exit with non-zero exit code: 1735001135
dartdoc:stderr: #0      getChannelName (package:snippets/main.dart:28:5)
dartdoc:stderr: #1      main (package:snippets/main.dart:185:18)
dartdoc:stderr: #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
dartdoc:stderr: #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
dartdoc:stderr:
dartdoc:stderr: , from widgets.Align: (file:///tmp/flutter%20sdk/packages/flutter/lib/src/widgets/basic.dart:1921:7)
```

**Comment by goderbauer** [comment]
Gonna close this since there haven't been any recent reports of this.
