### ISSUE TITLE
Provide suggestions when `flutter doctor --android-licenses` fails

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#82001]
## Steps to Reproduce

I'm not sure how to reproduce this, since I don't always have the problem when I install Flutter. What happened is that Flutter doctor told me that I need to run `flutter doctor --android-licenses`: 

```
✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
```

When I run the command, I got exception from the Java runtime:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

```

After Googling a lot, I found the answer on StackOverflow: https://stackoverflow.com/a/64162776

I wish Flutter doctor could give me suggestions to resolve the problem. 
 

## Logs

<details>
<summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
[✓] VS Code (version 1.56.0)
[✓] Connected device (3 available)
```

</details>

**Comment by cedvdb** [comment]
For me it was because I had version of java higher than idk 8. Check your java --version

**Comment by andesappal** [comment]
https://stackoverflow.com/a/64162776

**Comment by jwennesheimer** [comment]
> https://stackoverflow.com/a/64162776

These steps fixed my issue

**Comment by TahaTesser** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/80273
