### ISSUE TITLE
[camera] In Android take foto `unlockAutoFocus` error Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by wisnuwiry** [flutter/flutter#82031]
## Steps to Reproduce

This issue was experienced by some / many of my users when taking photos of the force close application. And to get this issue just take normal photos on one of the following devices:

1. vivo 1915
2. Oppo A1k
3. vivo 1724
4. realme C15
5. Oppo F7
6. vivo 1915
7. Galaxy A50s

**Expected results:** 

**Actual results:** 

![image](https://user-images.githubusercontent.com/44025097/117456575-8eb08e00-af72-11eb-84df-c5f7ea343353.png)

<details>
  <summary>Logs</summary>

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
       at io.flutter.plugins.camera.Camera.unlockAutoFocus(Camera.java:26)
       at io.flutter.plugins.camera.Camera.access$1900(Camera.java)
       at io.flutter.plugins.camera.Camera$4.onCaptureCompleted(Camera.java:2)
       at java.lang.reflect.Method.invoke(Method.java)
       at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
       at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6702)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @wisnuwiry 

>  many of my users when taking photos of the force close application

Can you please explain "n taking photos of the force close application"?  If you have reproducible steps of the issue, please provide complete steps  


Can you please provide your `flutter doctor -v`,your `pubspec.yaml`, if possible your `flutter run --release --verbose` running on the same OS version as the affected devices with the crash
Thank you

**Comment by wisnuwiry** [comment]
@TahaTesser I have updated it in the issue body above.

**Comment by billowapp** [comment]
We're seeing the same thing here.

Devices affected so far:

- Galaxy S21 5G
- Galaxy S10
- HUAWEI Y5 lite
- S55 Nova
- Oppo 15

Stack trace from Crashlytics

<img width="1116" alt="Screenshot 2021-05-21 at 07 25 02" src="https://user-images.githubusercontent.com/11815088/119086405-bb01eb00-ba05-11eb-977c-b65b910d3c55.png">

Output from flutter analyze

```
flutter analyze
Analyzing assetpool-flutter...                                          
No issues found! (ran in 10.4s)
```

We are unable to reproduce this locally as we don't have any of the devices mentioned above on hand.

**Comment by billowapp** [comment]
@wisnuwiry since we're not getting any responses, have you managed to solve this issue?

**Comment by slorop41314** [comment]
Any solving for this issue?
also got the error on 
Galaxy j1 Ace
Redmi 4A
Oppo A37F

**Comment by nguyen95** [comment]
Is there any solutions to this problem? It's been almost 3 months.

**Comment by torbenkeller** [comment]
We are also facing this Issue. 

We got 2 different StackTraces for it:
```text
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.camera2.CameraCaptureSession.capture(android.hardware.camera2.CaptureRequest, android.hardware.camera2.CameraCaptureSession$CaptureCallback, android.os.Handler)' on a null object reference
       at io.flutter.plugins.camera.Camera.unlockAutoFocus(Camera.java:648)
       at io.flutter.plugins.camera.Camera.access$700(Camera.java:83)
       at io.flutter.plugins.camera.Camera$3.onCaptureCompleted(Camera.java:559)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$3$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:693)
       at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$OA1Yz_YgzMO8qcV8esRjyt7ykp4.run(:8)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

and

```text
Fatal Exception: java.lang.IllegalStateException: Session has been closed; further changes are illegal.
       at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:886)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:179)
       at io.flutter.plugins.camera.Camera.unlockAutoFocus(Camera.java:648)
       at io.flutter.plugins.camera.Camera.access$700(Camera.java:83)
       at io.flutter.plugins.camera.Camera$3.onCaptureCompleted(Camera.java:559)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$3$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:692)
       at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$OA1Yz_YgzMO8qcV8esRjyt7ykp4.run(:8)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

In our case it failed on the devices:
* Samsung Galaxy A72 (Android 11)
* Samsung Galaxy A40 (Android 11)
* Samsung Galaxy S20 5G (Android 11)
* Samsung Galaxy S10e (Android 11)
* Samsung Galaxy S10 (Android 11)
* Samsung Galaxy S9+ (Android 10)
* Samsung Galaxy A71 (Android 11)
* Xiaomi Mi 11 Lite 5G (Android 11)

We also have none of the devices to reproduce it locally.

**Comment by TahaTesser** [comment]
Hi everyone
I have tried the following devices with autofocus, taken continuous pictures with the latest  `camera: ^0.9.2+2` and there is no such exception

-  Oneplus 8 (Android 11)
-  Xiaomi K20 Pro (Android 11)
-  Samsung M02s (Android 11)


Can you please upgrade to the latest  `stable` and importantly latest `camera: ^0.9.2+2` then try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by carman247** [comment]
Also getting this running a slightly modified camera 0.9.2+2 ... however, this picture below shows the only modification and it is essential for some Huawei devices.

![Screenshot 2021-09-22 at 09 08 29 (2)](https://user-images.githubusercontent.com/31341463/134298917-173ed150-9477-45f5-bf32-4153087a411d.png)

### Device
- Galaxy A10

### Stacktrace
```
io.flutter.plugins.camera.Camera.unlockAutoFocus (Camera.java:65)
io.flutter.plugins.camera.Camera.access$700 (Camera.java)
io.flutter.plugins.camera.Camera$3.onCaptureCompleted (Camera.java:2)
android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$3$CameraCaptureSessionImpl$1 (CameraCaptureSessionImpl.java:692)
android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$OA1Yz_YgzMO8qcV8esRjyt7ykp4.run (-.java:8)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:246)
android.os.HandlerThread.run (HandlerThread.java:67)
```
### Flutter doctor -v
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.1 20D75 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/chris/Developer/flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
```

**Comment by TahaTesser** [comment]
Removing wait label since this seems to be a legit issue that I can't reproduce with my devices using code samplehttps://github.com/flutter/flutter/issues/82031#issuecomment-912526674

**Comment by ukbaranwal31** [comment]
I am also facing the same issue.
Mostly happening on Android 11

**Comment by krispypen** [comment]
```
final file = await cameraController.takePicture();
await cameraController.dispose()
```
I found that the takePicture on Android starts doing stuff in the background after it receives the image, if you dispose after takePicture that background task could still be running and crash your application because of NullPointerExceptions or security exceptions, so a dirty workaround for now is waiting 500ms until you dispose the cameraController

**Comment by derng** [comment]
I am experiencing this issue on a Galaxy S9, and can consistently reproduce this calling `takePicture` and immediately disposing the controller at minimum of 2 cycles. @krispypen workaround helped in my case 👍

**Comment by rraayy** [comment]
I'm facing this issue on Galaxy S7 edge and randomly crash after calling  **takePicture**
The dirty workaround waiting 500ms helps me. Thank @krispypen !

**Comment by camsim99** [comment]
This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin, so please try it out!

If you find a similar issue with that implementation (or any other issues), please feel free to file a separate issue.

**Comment by kwikwag** [comment]
This issue will happen if you call something that recreates the `cameraSession` immediately after `takePicture()` is called. In my use-case I `stopImageStream()`, `takePicture()` and then `startImageStream()`.

Specifically, if there is no delay after `takePicture()` there is a race condition in the Java implementation.

Track 1: `CameraApiImpl.takePicture()` ->`takePictureAfterPrecapture()` -> `CaptureCallback` -> `unlockAutoFocus()`
Track 2: `CameraApiImpl.startImageStream()` -> `startPreview()` -> ... -> `createCaptureStream()`
Race: `unlockAutoFocus()` checks `cameraSession` is not null, `createCaptureStream()` sets it null, `unlockAutoFocus()` uses it.

Other such races can apparently cause `unlockAutoFocus()` to also act on a closed state, see #158878 .

A workaround I'm currently using it to set a future after calling `takePicture()`:

```dart
if (Platform.isAndroid) {
  waitAfterTakePicture = Future.delayed(Duration(milliseconds: msDelayBetweenTakePictureAndCameraSessionReplaceAndroidWorkaround));
}
```

And then performing any action that might be destructive to `cameraSession` (start/stop stream, dispose, etc.) *after* that future has elapsed, e.g. 

```
await waitAfterTakePicture;
await controller?.dispose();
```

This also makes it simple to skip this for iOS.

There are some fixes we can do in the Java end:
1. Handle IllegalStateException when using `cameraSession` by bubbling the exception to Flutter and allowing the user to handle it. This would effectively solve #158878
2. Assign `cameraSession` locally before checking for null and using that instance. This would essentially solve the race condition in this issue.
3. Marking `cameraSession` volatile, to indicate it might be updated from another thread.
4. Imposing `synchronized` blocks on all `cameraSession` uses. This is a bit more involved and might cause deadlocks.

I think I'll go ahead and submit a pull request for 1-3. @camsim99 I would appreciate your insight.

**Comment by kwikwag** [comment]
I just posted flutter/packages#12224 that should address points 1-3 above.
