### ISSUE TITLE
Loop Failure: DragTarget inside Draggable

### ISSUE THREAD

**Issue by AlexeyBukin** [flutter/flutter#82060]
## Steps to Reproduce

1. Run `flutter create test_loop`.
2. Copypaste https://gist.github.com/1c51a3883c56eaff913068c5a2a62cda to main.dart
3. Run `flutter run`
4. Tap green DragTarget (Do not move finger/mouse)

**Expected results:** Old drag target is not here anymore, it cannot accept Draggables

**Actual results:** Old drag target is still here until any mouse movement, it can accept Draggables, when Draggable and Target are in one widget Flutter fails with  ```'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true```

<details>
  <summary>Logs</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3552 pos 14: 'node != newChild': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Container file:///home/alex/Desktop/delta/delta/lib/runners/minimal_loop.dart:136:12
When the exception was thrown, this was the stack: 
#2      Element._debugCheckForCycles.<anonymous closure> (package:flutter/src/widgets/framework.dart:3552:14)
#3      Element._debugCheckForCycles (package:flutter/src/widgets/framework.dart:3554:6)
#4      Element.inflateWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:3527:11)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3529:10)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#66ec0](state: ChainHolderState#4a990):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3341 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#66ec0] file:///home/alex/Desktop/delta/delta/lib/runners/minimal_loop.dart:95:14
When the exception was thrown, this was the stack: 
#2      Element.mount (package:flutter/src/widgets/framework.dart:3341:12)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5342:11)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4533:16)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3341 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#66ec0] file:///home/alex/Desktop/delta/delta/lib/runners/minimal_loop.dart:95:14
When the exception was thrown, this was the stack: 
#2      Element.mount (package:flutter/src/widgets/framework.dart:3341:12)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5342:11)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4533:16)
...
The element being rebuilt at the time was index 2 of 5: ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#66ec0]
  state: ChainHolderState#4a990
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<BlockState<Block>>#3fbeb]
This was determined by noticing that after the widget with the above global key was moved out of its respective previous parents, those previous parents never updated during this frame, meaning that they either did not update at all or updated before the widget was moved, in either case implying that they still think that they should have a child with that global key.
The specific parents that did not update after having one or more children forcibly removed due to GlobalKey reparenting are:
- Column(direction: vertical, mainAxisAlignment: start, crossAxisAlignment: center, renderObject: RenderFlex#9c820 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
  _BodyBuilder
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2845:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2870:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
...
====================================================================================================

```

```
No issues found! (ran in 0.9s)
```

```
[✓] Flutter (Channel beta, 2.0.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.2 at /home/alex/snap/flutter/common/flutter
    • Framework revision 8962f6dc68 (8 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alex/dev/android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by AlexeyBukin** [comment]
Wrapping ```DragTarget``` with ```AbsorbPointer``` helps, but it just smells...

**Comment by darshankawar** [comment]
Thanks for the detailed report and code sample. I verified and is replicable using latest master. To replicate, tap on the green button and then release which throws below exception in the console:

<details>
<summary> console error log </summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3673 pos 14: 'node != newChild': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Container file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:135:12
When the exception was thrown, this was the stack: 
#2      Element._debugCheckForCycles.<anonymous closure> (package:flutter/src/widgets/framework.dart:3673:14)
#3      Element._debugCheckForCycles (package:flutter/src/widgets/framework.dart:3675:6)
#4      Element.inflateWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:3648:11)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3650:10)
#6      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6285:36)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3453 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
The relevant error-causing widget was: 
  ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#39b82] file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:94:14
====================================================================================================

======== Exception caught by widgets library =======================================================
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3453 pos 12: 'parent == null || parent._lifecycleState == _ElementLifecycle.active': is not true.
The relevant error-causing widget was: 
  ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#39b82] file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:94:14
====================================================================================================

======== Exception caught by widgets library =======================================================
Duplicate GlobalKey detected in widget tree.
====================================================================================================


```

</details>

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 2.3.0-1.0.pre.269, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.269 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d28737eedf (10 hours ago), 2021-05-09 14:24:19 -0700
    • Engine revision f5b97d0b23
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.

```

</details>

**Comment by Piinks** [comment]
<details><summary>Updated code sample since drag anchor does not exist anymore:</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(EditorRunnerApp());

class EditorRunnerApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Editor demo',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Loop demo'),
          elevation: 0,
        ),
        body: Chain(autofocus: true),
      ),
      theme: ThemeData(),
    );
  }
}

abstract class Block extends StatefulWidget {

  const Block({required this.key});

  @override
  final GlobalKey<BlockState> key;

  @override
  BlockState createState();

  static BlockState? of(BuildContext? context) {
    return context?.findAncestorStateOfType<BlockState>();
  }
}

abstract class BlockState<T extends Block> extends State<T> {
  @override
  BlockBase build(BuildContext context);

  void removeFromHolder() {
    Holder.of(context)?.removeChild(key: widget.key);
  }
}

/// [Widget] that holds one or more [Block]s
abstract class Holder extends StatefulWidget {

  const Holder({required this.key});

  @override
  final GlobalKey<HolderState> key;

  @override
  HolderState createState();

  static HolderState? of(BuildContext? context) {
    return context?.findAncestorStateOfType<HolderState>();
  }
}

/// The logic and internal state for a [Holder].
abstract class HolderState<T extends Holder> extends State<T> {
  void removeChild({required GlobalKey<BlockState> key});
}

class Chain extends Block {
  final Color color;
  final Color focusedColor;
  final bool autofocus;

  Chain({
    GlobalKey<BlockState>? key,
    this.color = Colors.blueGrey,
    this.focusedColor = Colors.yellow,
    this.autofocus = false,
  }) : super(key: key ?? GlobalKey());

  @override
  BlockState<Block> createState() => ChainState();

  static ChainState? of(BuildContext? context) {
    return context?.findAncestorStateOfType<ChainState>();
  }
}

class ChainState extends BlockState<Chain> {

  late ChainHolder holder;

  @override
  void initState() {
    super.initState();
    holder = ChainHolder();
  }

  @override
  BlockBase build(BuildContext context) {
    return BlockBase(
      autofocus: widget.autofocus,
      parentKey: widget.key,
      color: widget.color,
      focusedColor: widget.focusedColor,
      childBuilder: (BuildContext context) {
        return Column(
          children: [
            Text('Chain'),
            holder,
          ],
        );
      },
    );
  }
}

/// [Widget] that can hold list of [Block]s
class ChainHolder extends Holder {
  ChainHolder({GlobalKey<ChainHolderState>? key}) : super(key: key ?? GlobalKey());

  @override
  HolderState<Holder> createState() => ChainHolderState();

  static ChainHolderState? of(BuildContext? context) {
    return context?.findAncestorStateOfType<ChainHolderState>();
  }
}

class ChainHolderState extends HolderState<ChainHolder> {
  List<Block> blocks = List<Block>.empty(growable: true);
  List<Widget> body = <Widget>[];

  @override
  Widget build(BuildContext oldContext) {
    body = holderBody();
    return Container(
      child: Column(
        children: body,
      ),
    );
  }

  /// Generates widget list from [blocks]
  ///
  /// [o, o, o] -> [x, o, x, o, x, o, x]
  /// where o is [Block] and x is [DragTarget]
  List<Widget> holderBody() {
    List<Widget> body = <Widget>[];
    for (int i = 0; i < blocks.length; i++) {
      body.add(target(position: i * 2));
      body.add(blocks[i]);
    }
    body.add(target(position: blocks.length * 2));
    return (body);
  }

  Widget target({required int position}) {
    final valueKey = ValueKey<int>(position);
    return DragTarget<GlobalKey<BlockState>>(
      key: valueKey,
      builder: dragTargetBuilder,
      onAccept: (newKey) {
        setState(() {
          acceptBlockFromTarget(targetKey: valueKey, blockKey: newKey);
        });
      },
    );
  }

  Widget dragTargetBuilder(
      BuildContext context, List candidateData, List<dynamic> rejectedData) {
    bool isHovered = candidateData.isNotEmpty;
    if (isHovered) {
      return Container(
        color: Colors.pink,
        padding: EdgeInsets.all(20),
      );
    } else {
      return Container(
        color: Colors.green,
        padding: EdgeInsets.all(20),
      );
    }
  }

  /// TODO Avoid invalid keys!
  void acceptBlockFromTarget({
    required ValueKey<int> targetKey,
    required GlobalKey<BlockState> blockKey,
  }) {
    setState(() {
      blockKey.currentState!.removeFromHolder();
      blocks.add(blockKey.currentWidget as Block);
    });
  }

  @override
  void removeChild({required GlobalKey<BlockState<Block>> key}) {
    setState(() {
      key.currentState!.removeFromHolder();
      blocks.add(key.currentWidget as Block);
    });
  }
}

/// [Widget] that blocks rely on
///
/// Handles [Focus], tap events and drag events
class BlockBase extends StatefulWidget {
  final Color color;
  final Color focusedColor;
  final WidgetBuilder childBuilder;
  final bool isDraggable;
  final bool autofocus;
  final FocusNode focusNode = FocusNode();

  BlockBase({
    required this.childBuilder,
    required this.parentKey,
    this.isDraggable = true,
    this.color = Colors.white,
    this.focusedColor = Colors.yellow,
    this.autofocus = false,
  });

  final GlobalKey<BlockState>? parentKey;

  @override
  State<BlockBase> createState() => BlockBaseState();
}

class BlockBaseState extends State<BlockBase> {

  bool isFocused = false;

  @override
  Widget build(BuildContext oldContext) {
    return Focus(
      autofocus: widget.autofocus,
      onFocusChange: (bool focused) {
        setState(() {
          isFocused = focused;
          // color = focused ? widget.focusedColor : widget.color;
        });
      },
      child: Builder(
        builder: (BuildContext context) {
          final child = widget.childBuilder(context);
          var justBlock = GestureDetector(
            child: Container(
              decoration: BoxDecoration(
                color: Colors.white,
                border: Border.all(
                  color: isFocused ? Colors.blue : Colors.black,
                  width: 3,
                ),
                // borderRadius: BorderRadius.circular(12),
              ),
              padding: EdgeInsets.all(5),
              child: child,
            ),
          );
          return Draggable<Key>(
            dragAnchorStrategy: pointerDragAnchorStrategy,
            data: widget.parentKey,
            childWhenDragging: Divider(
              color: Colors.blue,
              thickness: 3.0,
            ),
            feedback: Center(
              child: Material(
                child: Center(
                  child: Container(
                    constraints: BoxConstraints(
                        minWidth: 100, maxWidth: 200, minHeight: 40),
                    child: justBlock,
                  ),
                ),
              ),
            ),
            child: justBlock,
          );
        },
      ),
    );
  }
}
```
</details>

<details><summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following assertion was thrown building Container:
Assertion failed:
file:///opt/flutter/packages/flutter/lib/src/widgets/framework.dart:4557:14
node != newChild
is not true

Widget creation tracking is currently disabled. Enabling it
enables improved error messages. It can be enabled by passing
`--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack

═════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following assertion was thrown building
ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#de99e](state:
ChainHolderState#5c7f2):
Assertion failed:
file:///opt/flutter/packages/flutter/lib/src/widgets/framework.dart:4277:7
parent == null || parent._lifecycleState ==
_ElementLifecycle.active
"Parent (Container) should be null or in the active state
(inactive)"

Widget creation tracking is currently disabled. Enabling it
enables improved error messages. It can be enabled by passing
`--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack

═════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following assertion was thrown while rebuilding dirty
elements:
Assertion failed:
file:///opt/flutter/packages/flutter/lib/src/widgets/framework.dart:4277:7
parent == null || parent._lifecycleState ==
_ElementLifecycle.active
"Parent
(ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#de99e](state:
ChainHolderState#5c7f2)) should be null or in the active state
(inactive)"

Widget creation tracking is currently disabled. Enabling it
enables improved error messages. It can be enabled by passing
`--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack

The element being rebuilt at the time was:
  ChainHolder-[LabeledGlobalKey<HolderState<Holder>>#de99e]
═════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following assertion was thrown while finalizing the widget
tree:
Duplicate GlobalKey detected in widget tree.
The following GlobalKey was specified multiple times in the
widget tree. This will lead to parts of the widget tree being
truncated unexpectedly, because the second time a key is seen,
the previous instance is moved to the new location. The key was:
- [LabeledGlobalKey<BlockState<Block>>#34a96]
This was determined by noticing that after the widget with the
above global key was moved out of its respective previous
parents, those previous parents never updated during this frame,
meaning that they either did not update at all or updated before
the widget was moved, in either case implying that they still
think that they should have a child with that global key.
The specific parents that did not update after having one or more
children forcibly removed due to GlobalKey reparenting are:
- MultiChildRenderObjectElement#60eeb(DEFUNCT)(no widget)
  KeyedSubtree-[GlobalKey#25386]
A GlobalKey can only be specified on one widget at a time in the
widget tree.

When the exception was thrown, this was the stack
═════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following assertion was thrown building
KeyedSubtree-[GlobalKey#25386]:
Assertion failed:
file:///opt/flutter/packages/flutter/lib/src/widgets/framework.dart:2114:12
_elements.contains(element)
is not true

Widget creation tracking is currently disabled. Enabling it
enables improved error messages. It can be enabled by passing
`--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack

═════════════════════════════════════════════════════════════════


```

</details>
