### ISSUE TITLE
Flutter web build - blank page and stops on web_entrypoint.dart file

### ISSUE THREAD

**Issue by mklepaczko** [flutter/flutter#82108]
I'm trying to build a Flutter web for my app project.

After passing "Flutter Create ." and trying to run in Chrome it shows a blank page and stops on the web_entrypoint.dart file.
Project was create about a year ago. Same problem on a second project I also create about 6 months ago.
 I created a new test project now and the problem does not appear.

✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale pl-PL)
    • Flutter version 2.0.6 at /users/michalklepaczko/flutter
    • Framework revision 1d9032c7e1 (9 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/michalklepaczko/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • SM T515 (mobile) • R52MB0NQSPD • android-arm    • Android 10 (API 29)
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

![Zrzut ekranu 2021-05-7 o 17 13 58](https://user-images.githubusercontent.com/52317336/117540305-f9afa280-b00e-11eb-8c2f-cc4bc2eb5100.png)

**Comment by Mahfa** [comment]
same problem here

**Comment by TahaTesser** [comment]
Hi @mklepaczko 
You probably need to update your project

Here I tried to reproduce the issue using an old example [repository](https://github.com/ericwindmill/flutter_by_example_apps), its examples are not updated from 3 years. 

- `git clone https://github.com/ericwindmill/flutter_by_example_apps.git`
- `cd flutter_by_example_apps\blank_flutter_app`

- This example is missing is sdk constraint so added this
```yaml
environment:
  sdk: '>=2.10.0 <3.0.0'
```
- `flutter create .`
- `flutter run -d chrome -v`


The app launches 

<details> 
<summary>preview</summary> 

![image](https://user-images.githubusercontent.com/48603081/117651119-3c51b600-b19a-11eb-86ee-6da333725656.png)


</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.6 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 1d9032c7e1 (10 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
```
		
</details>

**Comment by mklepaczko** [comment]
Hi @TahaTesser,

I have:
environment:
  sdk: '>=2.12.0 <3.0.0'

Already in my project. I recently updated all the project to null safety. Here is the info from the flutter run -d chrome -v

[+25506 ms] Waiting for connection from debug service on Chrome... (completed in 29,8s)
[        ] Synced 36.9MB.
[        ] <- accept
[        ] Caching compiled dill
[ +395 ms] Using Google Chrome 90.0.4430.93 

[+11840 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:53288/devtools/browser/dcdcb7ce-67c1-48dc-a6fc-7b36b9c67b2c
[+1219 ms] DwdsInjector: Received request for entrypoint at http://localhost:53259/main_module.bootstrap.js
[  +17 ms] MetadataProvider: Loading debug metadata...
[  +25 ms] MetadataProvider: Loaded debug metadata
[  +13 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:53259/main_module.bootstrap.js
[+4467 ms] DevHandler: Debug service listening on ws://127.0.0.1:53310/xxdkUe_Bg4M=/ws

[  +14 ms] Debug service listening on ws://127.0.0.1:53310/xxdkUe_Bg4M=/ws
[   +1 ms] 💪 Running with sound null safety 💪
[   +4 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[  +55 ms] TypeError: Cannot read property 'app' of undefined
               at Object.app$ [as app] (http://localhost:53259/packages/firebase_core_web/src/interop/core.dart.lib.js:42:101)
               at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:53259/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:865:64)
               at Function.registerWith (http://localhost:53259/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:788:73)
               at Object.registerPlugins (http://localhost:53259/packages/quiqer_service_provider/generated_plugin_registrant.dart.lib.js:37:46)
               at main (http://localhost:53259/web_entrypoint.dart.lib.js:41:35)
               at main.next (<anonymous>)
               at runBody (http://localhost:53259/dart_sdk.js:37228:34)
               at Object._async [as async] (http://localhost:53259/dart_sdk.js:37259:7)
               at main$ (http://localhost:53259/web_entrypoint.dart.lib.js:40:18)
               at http://localhost:53259/main_module.bootstrap.js:19:10
               at Array.forEach (<anonymous>)
               at window.$dartRunMain (http://localhost:53259/main_module.bootstrap.js:18:32)
               at <anonymous>:1:8
               at Object.runMain (http://localhost:53259/dwds/src/injected/client.js:8656:21)
               at http://localhost:53259/dwds/src/injected/client.js:22068:19
               at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53259/dwds/src/injected/client.js:3830:15)
               at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53259/dwds/src/injected/client.js:10905:12)
               at Object._asyncStartSync (http://localhost:53259/dwds/src/injected/client.js:3794:20)
               at main__closure1.$call$body$main__closure (http://localhost:53259/dwds/src/injected/client.js:22080:16)
               at main__closure1.call$1 (http://localhost:53259/dwds/src/injected/client.js:22007:19)
               at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:53259/dwds/src/injected/client.js:4153:16)
               at _CustomZone.runUnary$2$2 (http://localhost:53259/dwds/src/injected/client.js:12136:39)
               at _CustomZone.runUnaryGuarded$1$2 (http://localhost:53259/dwds/src/injected/client.js:12068:14)
               at _ControllerSubscription._sendData$1 (http://localhost:53259/dwds/src/injected/client.js:11697:19)
               at _DelayedData.perform$1 (http://localhost:53259/dwds/src/injected/client.js:11849:59)
               at _PendingEvents_schedule_closure.call$0 (http://localhost:53259/dwds/src/injected/client.js:11898:14)
               at Object._microtaskLoop (http://localhost:53259/dwds/src/injected/client.js:3990:24)
               at StaticClosure._startMicrotaskLoop (http://localhost:53259/dwds/src/injected/client.js:3996:11)
               at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:53259/dwds/src/injected/client.js:10774:9)
               at invokeClosure (http://localhost:53259/dwds/src/injected/client.js:1250:26)
               at MutationObserver.<anonymous> (http://localhost:53259/dwds/src/injected/client.js:1269:18)

**Comment by TahaTesser** [comment]
Hi @mklepaczko 
The error from your logs are from firebase, not flutter itself 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you
