### ISSUE TITLE
Agter update the flutter, Create a flutter project, get the problem "FileSystemException: FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\flutter\packages\flutter_tools\templates\template_manifest.json'"

### ISSUE THREAD

**Issue by lightwind** [flutter/flutter#82114]
**got the problem is** 

Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 57907
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\flutter\packages\flutter_tools\templates\template_manifest.json'".
A crash report has been written to E:\Project\flutter_03.log.

**and the log is** 

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --template app --description A new Flutter project. --org com.example --platforms android,ios untitled

## exception

FileSystemException: FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\flutter\packages\flutter_tools\templates\template_manifest.json'

```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:209:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:208:12)
#6      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:498:37)
#7      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:484:30)
#8      CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:385:25)
#9      CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:29)
#10     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#20     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#21     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#23     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
    • Flutter version 2.0.0 at D:\flutter
    • Framework revision 60bd88df91 (9 weeks ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin installed
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at D:\Program Files\IntelliJ IDEA 2020.2.3
    • Flutter plugin installed
    • Dart plugin installed

[✓] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/65021
