### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by radensoft** [flutter/flutter#82148]
Launching lib\main.dart on RMX1851 in debug mode...
Parameter format not correct -
√ Built build\app\outputs\flutter-apk\app-debug.apk.
<details>
<summary> error log </summary>

```
Connecting to VM Service at ws://127.0.0.1:13575/KU2rOBTpcno=/ws
I/om.radensmarke(16897): ProcessProfilingInfo new_methods=2173 is saved saved_to_disk=1 resolve_classes_delay=5000
I/FLTFireBGExecutor(16897): Creating background FlutterEngine instance, with args: [--start-paused, --enable-dart-profiling]
I/FLTFireMsgService(16897): FlutterFirebaseMessagingBackgroundService started!
W/om.radensmarke(16897): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/om.radensmarke(16897): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/om.radensmarke(16897): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/om.radensmarke(16897): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
V/OppoMediaPlayer(16897): system load
V/OppoMediaPlayer(16897): new OppoMediaPlayer
I/OppoMediaPlayer(16897): new mediaplayer ,packageName = com.radensmarket
I/OppoMediaPlayer(16897): isPlaying() isOppoCreate=false
I/OppoMediaPlayer(16897): setAudioAttributes() isOppoCreate = false
I/OppoMediaPlayer(16897): setDataSource(String) isOppoCreate=false
I/OppoMediaPlayer(16897): setDataSource(path, headers) isOppoCreate=false
I/OppoMediaPlayer(16897): setDataSource(FileDescriptor fd) isOppoCreate=false
I/OppoMediaPlayer(16897): setDataSource(FileDescriptor, long, long) isOppoCreate=false
D/OppoMediaPlayer(16897): closeFd()
I/OppoMediaPlayer(16897): prepareAsync() isOppoCreate=false
I/OppoMediaPlayer(16897): getMediaTimeProvider() isOppoCreate = false
D/MediaPlayer(16897): start()
I/OppoMediaPlayer(16897): getVideoWidth() isOppoCreate=false
I/OppoMediaPlayer(16897): getVideoHeight() isOppoCreate=false
I/OppoMediaPlayer(16897): start() isOppoCreate = false mCurrentState = 4
I/OppoMediaPlayer(16897): isPlaying() isOppoCreate=false
I/OppoMediaPlayer(16897): pause() isOppoCreate=false
D/MediaPlayer(16897): seekTo() msec = 0, seekMode = 0 isOppoCreate = false
I/OppoMediaPlayer(16897): isPlaying() isOppoCreate=false
I/OppoMediaPlayer(16897): isPlaying() isOppoCreate=false
I/flutter (16897): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (16897): The following assertion was thrown during a scheduler callback:
I/flutter (16897): Updated layout information required for RenderIndexedSemantics#684af NEEDS-LAYOUT to calculate
I/flutter (16897): semantics.
I/flutter (16897): 'package:flutter/src/rendering/object.dart':
I/flutter (16897): Failed assertion: line 2658 pos 12: '!_needsLayout'
I/flutter (16897):
I/flutter (16897): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16897): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16897): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16897):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
I/flutter (16897):
I/flutter (16897): When the exception was thrown, this was the stack:
[38;5;244mI/flutter (16897): #2      RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #3      RenderObject._getSemanticsForParent.<anonymous closure>[39;49m
[38;5;244mI/flutter (16897): #4      Iterable.forEach (dart:core/iterable.dart:257:30)[39;49m
[38;5;244mI/flutter (16897): #5      RenderSliverVariableSizeBoxAdaptor.visitChildren[39;49m
[38;5;244mI/flutter (16897): #6      RenderObject.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #7      RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #8      RenderObject._getSemanticsForParent.<anonymous closure>[39;49m
[38;5;244mI/flutter (16897): #9      Iterable.forEach (dart:core/iterable.dart:257:30)[39;49m
[38;5;244mI/flutter (16897): #10     RenderViewportBase.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #11     RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #12     RenderObject._getSemanticsForParent.<anonymous closure>[39;49m
[38;5;244mI/flutter (16897): #13     RenderIgnorePointer.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #14     RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #15     RenderObject._getSemanticsForParent.<anonymous closure>[39;49m
[38;5;244mI/flutter (16897): #16     RenderObjectWithChildMixin.visitChildren[39;49m
[38;5;244mI/flutter (16897): #17     RenderObject.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #18     RenderSemanticsAnnotations.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #19     RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #20     RenderObject._getSemanticsForParent.<anonymous closure>[39;49m
[38;5;244mI/flutter (16897): #21     RenderObjectWithChildMixin.visitChildren[39;49m
[38;5;244mI/flutter (16897): #22     RenderObject.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #23     RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #24     RenderObject._getSemanticsForParent.<anonymous closure>[39;49m
[38;5;244mI/flutter (16897): #25     RenderObjectWithChildMixin.visitChildren[39;49m
[38;5;244mI/flutter (16897): #26     RenderObject.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #27     RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #28     RenderObject._getSemanticsForParent.<anonymous closure>[39;49m
[38;5;244mI/flutter (16897): #29     RenderObjectWithChildMixin.visitChildren[39;49m
[38;5;244mI/flutter (16897): #30     RenderObject.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #31     RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #32     RenderObject._getSemanticsForParent.<anonymous closure>[39;49m
[38;5;244mI/flutter (16897): #33     RenderObjectWithChildMixin.visitChildren[39;49m
[38;5;244mI/flutter (16897): #34     RenderObject.visitChildrenForSemantics[39;49m
[38;5;244mI/flutter (16897): #35     RenderObject._getSemanticsForParent[39;49m
[38;5;244mI/flutter (16897): #36     RenderObject._updateSemantics[39;49m
[38;5;244mI/flutter (16897): #37     PipelineOwner.flushSemantics[39;49m
[38;5;244mI/flutter (16897): #38     RendererBinding.drawFrame[39;49m
[38;5;244mI/flutter (16897): #39     WidgetsBinding.drawFrame[39;49m
[38;5;244mI/flutter (16897): #40     RendererBinding._handlePersistentFrameCallback[39;49m
[38;5;244mI/flutter (16897): #41     SchedulerBinding._invokeFrameCallback[39;49m
[38;5;244mI/flutter (16897): #42     SchedulerBinding.handleDrawFrame[39;49m
[38;5;244mI/flutter (16897): #43     SchedulerBinding._handleDrawFrame[39;49m
[38;5;244mI/flutter (16897): #47     _invoke (dart:ui/hooks.dart:161:10)[39;49m
[38;5;244mI/flutter (16897): #48     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)[39;49m
[38;5;244mI/flutter (16897): #49     _drawFrame (dart:ui/hooks.dart:120:31)[39;49m
[38;5;244mI/flutter (16897): (elided 5 frames from class _AssertionError and dart:async)[39;49m
I/flutter (16897): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/ColorExSystemServiceHelper(16897): checkColorExSystemService className = com.google.android.gms.measurement.service.MeasurementBrokerService
V/ActivityThread(16897): scheduleReceiver info = ActivityInfo{42bcb41 com.google.firebase.iid.FirebaseInstanceIdReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1080010 pkg=com.radensmarket cmp=com.radensmarket/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) } sync = true hasCode = 68946159
D/ColorExSystemServiceHelper(16897): checkColorExSystemService className = com.google.android.gms.gcm.PushMessagingRegistrarProxy
W/ColorExSystemServiceHelper(16897): checkColorExSystemService intent getComponent is null
D/ColorExSystemServiceHelper(16897): checkColorExSystemService className = io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingService
V/ActivityThread(16897): scheduleReceiver info = ActivityInfo{b081b1f io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver} intent = Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1080010 pkg=com.radensmarket cmp=com.radensmarket/io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver (has extras) } sync = true hasCode = 80366898
D/FLTFireMsgReceiver(16897): broadcast received for message
E/BitmapFactory(16897): Unable to decode stream: java.io.FileNotFoundException: app_icon: open failed: ENOENT (No such file or directory)
E/AndroidRuntime(16495): FATAL EXCEPTION: EnCodeFileHandlerThread
E/AndroidRuntime(16495): Process: com.oppo.lfeh, PID: 16495
E/AndroidRuntime(16495): java.lang.IllegalArgumentException: Comparison method violates its general contract!
E/AndroidRuntime(16495):  at java.util.TimSort.mergeHi(TimSort.java:899)
E/AndroidRuntime(16495):  at java.util.TimSort.mergeAt(TimSort.java:516)
E/AndroidRuntime(16495):  at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
E/AndroidRuntime(16495):  at java.util.TimSort.sort(TimSort.java:254)
E/AndroidRuntime(16495):  at java.util.Arrays.sort(Arrays.java:1424)
E/AndroidRuntime(16495):  at com.oppo.lfeh.core.OppoFileEncodeHelper.getFileList(OppoFileEncodeHelper.java:631)
E/AndroidRuntime(16495):  at com.oppo.lfeh.core.OppoFileEncodeHelper.removeTempFileAndKeepDirSmall(OppoFileEncodeHelper.java:1461)
E/AndroidRuntime(16495):  at com.oppo.lfeh.core.OppoFileEncodeHelper.startScanAndEncodeFileReady(OppoFileEncodeHelper.java:1729)
E/AndroidRuntime(16495):  at com.oppo.lfeh.core.OppoFileEncodeHelper.access$1200(OppoFileEncodeHelper.java:67)
E/AndroidRuntime(16495):  at com.oppo.lfeh.core.OppoFileEncodeHelper$EnCodeFileHandler.handleMessage(OppoFileEncodeHelper.java:2147)
E/AndroidRuntime(16495):  at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(16495):  at android.os.Looper.loop(Looper.java:228)
E/AndroidRuntime(16495):  at android.os.HandlerThread.run(HandlerThread.java:67)



```

</details>

**Comment by darshankawar** [comment]
@radensoft 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
