### ISSUE TITLE
Windows build_tests_2_3 presubmit failing on finding visual studio

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#82225]
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20build_tests_2_3/3155/overview

Marking P0 since this is blocking PRs needed to get the framework tree open.

/cc @keyonghan 

```
[   +5 ms] Unable to find suitable Visual Studio toolchain. Please run `flutter doctor` for more details.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:67:5)
           #2      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:55:11)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1091:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by keyonghan** [comment]
Windows build_tests_2_3 was disabled in https://github.com/flutter/flutter/pull/81955/files for pre-submit tests. Could you please try rebasing?

**Comment by keyonghan** [comment]
For the issue `Unable to find suitable Visual Studio toolchain`, do we have a tracking issue? /cc @godofredoc

**Comment by godofredoc** [comment]
We'll need to disable the test. Context is here https://github.com/flutter/flutter/issues/82006
