### ISSUE TITLE
[Web] : Hot restart using named routes with arguments shows error when pressing back button

### ISSUE THREAD

**Issue by nashihu** [flutter/flutter#82237]
continuing issue from #73793 due to (probably) different root cause, cc @chunhtai 

## Steps to Reproduce

1. Run attached code below
2. hot restart first
3. click detail page
4. press back
5. web successfully directed to the first page

**Expected results:** clean log at console

**Actual results:** got some errors in log

<details close>
<summary>Code</summary>

```import 'package:flutter/material.dart';

 void main() => runApp(App());

 class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: <String, WidgetBuilder>{
        '/': (_) => FirstPage(),
        '/d': (_) => SecondPage(),
      }
    );
  }
 }

 class FirstPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(body:Center(
      child: RaisedButton(onPressed: () => Navigator.of(context).pushNamed('/d', arguments: {"value": 1000})),
    ));
  }
 }

 class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(body:Center(
      child: Text('second page'),
    ));
  }
 }
```
</details>

<details>
  <summary>Logs</summary>

```
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:284:14
                    _userProvidedRouteName != null
                    is not true
                        at Object.throw_ [as throw] (http://localhost:55332/dart_sdk.js:5333:11)
                        at Object.assertFailed (http://localhost:55332/dart_sdk.js:5269:15)
                        at _engine.SingleEntryBrowserHistory.new.onPopState (http://localhost:55332/dart_sdk.js:148687:59)
[ +166 ms] Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/navigation/history.dart:239:12
                    _isOriginEntry(state)
                    is not true
                        at Object.throw_ [as throw] (http://localhost:55332/dart_sdk.js:5333:11)
                        at Object.assertFailed (http://localhost:55332/dart_sdk.js:5269:15)
                        at _engine.SingleEntryBrowserHistory.new.[_unwrapOriginState] (http://localhost:55332/dart_sdk.js:148663:57)
                        at _engine.SingleEntryBrowserHistory.new.tearDown (http://localhost:55332/dart_sdk.js:148723:79)
                        at tearDown.next (<anonymous>)
                        at http://localhost:55332/dart_sdk.js:39031:33
                        at _RootZone.runUnary (http://localhost:55332/dart_sdk.js:38888:58)
                        at _FutureListener.thenAwait.handleValue (http://localhost:55332/dart_sdk.js:33874:29)
                        at handleValueCallback (http://localhost:55332/dart_sdk.js:34434:49)
                        at Function._propagateToListeners (http://localhost:55332/dart_sdk.js:34472:17)
                        at _Future.new.[_completeWithValue] (http://localhost:55332/dart_sdk.js:34314:23)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:55332/dart_sdk.js:34337:35)
                        at Object._microtaskLoop (http://localhost:55332/dart_sdk.js:39175:13)
                        at _startMicrotaskLoop (http://localhost:55332/dart_sdk.js:39181:13)
                        at http://localhost:55332/dart_sdk.js:34688:9



```
</details>

<details close>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.1 20D74 darwin-x64, locale
    en-ID)
    • Flutter version 2.0.6 at /Users/ahmadn/flutter
    • Framework revision 1d9032c7e1 (11 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ahmadn/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 90.0.4430.212
```
</details>

**Comment by billyinferno** [comment]
I tried on Flutter 2.2.2 and got the same error, do I need to create new issue, or just put it here?

**Comment by darshankawar** [comment]
@billyinferno 
The fix was merged in master, so please switch to latest master and try again to see the fix.
