### ISSUE TITLE
Pre Launch Error (API (unsupported))

### ISSUE THREAD

**Issue by exampaqs** [flutter/flutter#82252]
trying to launch my app, i got this error of unsupported APIs from play store:

API: Landroid/util/LongArray;->get(I)J
stack trace:
`StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/util/LongArray;->get(I)J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:113)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:4)
	at io.flutter.embedding.android.k.j(Unknown Source:178)
	at io.flutter.embedding.android.f.m(Unknown Source:149)
	at io.flutter.embedding.android.e.D(Unknown Source:3)
	at io.flutter.embedding.android.e.onCreate(Unknown Source:31)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
`StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:92)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:4)
	at io.flutter.embedding.android.k.j(Unknown Source:178)
	at io.flutter.embedding.android.f.m(Unknown Source:149)
	at io.flutter.embedding.android.e.D(Unknown Source:3)
	at io.flutter.embedding.android.e.onCreate(Unknown Source:31)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

and two others. please what do i do?

**Comment by darshankawar** [comment]
@exampaqs 
Please see [this](https://github.com/flutter/flutter/issues/36915#issuecomment-525668810) and [this](https://github.com/flutter/flutter/issues/36915#issuecomment-642369537) comment for your reference.

Closing this based on the issue comments referred.
