### ISSUE TITLE
 Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)

### ISSUE THREAD

**Issue by akhil-ge0rge** [flutter/flutter#82363]
I was following  Flutter beginner tutorial from [The Net Ninja](https://www.youtube.com/watch?v=WdXcJdhWcEY&list=PL4cUxeGkcC9jLYyp2Aoh6hcWuxFDX6PBJ&index=26). it keep getting this error that I cant fix. Please help me if you can!!.

**Error  :**  

```
E/flutter ( 9001): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)
E/flutter ( 9001): //jsonplaceholder.typicode.com
E/flutter ( 9001): ^
E/flutter ( 9001):
E/flutter ( 9001): #0      int._throwFormatException (dart:core-patch/integers_patch.dart:131:5)
E/flutter ( 9001): #1      int._parseRadix (dart:core-patch/integers_patch.dart:157:16)
E/flutter ( 9001): #2      int._parse (dart:core-patch/integers_patch.dart:100:12)
E/flutter ( 9001): #3      int.parse (dart:core-patch/integers_patch.dart:63:12)
E/flutter ( 9001): #4      _Uri._makeHttpUri (dart:core/uri.dart:1591:49)
E/flutter ( 9001): #5      new _Uri.http (dart:core/uri.dart:1456:12)
E/flutter ( 9001): #6      _LoadingState.getData
package:worldtime/pages/loading.dart:12
E/flutter ( 9001): #7      _LoadingState.initState
package:worldtime/pages/loading.dart:20
E/flutter ( 9001): #8      StatefulElement._firstBuild
package:flutter/…/widgets/framework.dart:4632
E/flutter ( 9001): #9      ComponentElement.mount
package:flutter/…/widgets/framework.dart:4469
E/flutter ( 9001): #10     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3541
E/flutter ( 9001): #11     Element.updateChild
package:flutter/…/widgets/framework.dart:3306
E/flutter ( 9001): #12     SingleChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:5974
E/flutter ( 9001): #13     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3541
E/flutter ( 9001): #14     Element.updateChild
package:flutter/…/widgets/framework.dart:3306
E/flutter ( 9001): #15     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4520
E/flutter ( 9001): #16     Element.rebuild
package:flutter/…/widgets/framework.dart:4189
E/flutter ( 9001): #17     ComponentElement._firstBuild
package:flutter/…/widgets/framework.dart:4474
E/flutter ( 9001): #18     ComponentElement.mount
package:flutter/…/widgets/framework.dart:4469
E/flutter ( 9001): #19     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3541
E/flutter ( 9001): #20     Element.updateChild
package:flutter/…/widgets/framework.dart:3306
E/flutter ( 9001): #21     SingleChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:5974
E/flutter ( 9001): #22     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3541
E/flutter ( 9001): #23     Element.updateChild
package:flutter/…/widgets/framework.dart:3306
E/flutter ( 9001): #24     SingleChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:5974
E/flutter ( 9001): #25     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3541
E/flutter ( 9001): #26     Element.updateChild
package:flutter/…/widgets/framework.dart:3306
```

**Code :** 

```
import 'package:flutter/material.dart';
import 'package:http/http.dart';

class Loading extends StatefulWidget {
  @override
  _LoadingState createState() => _LoadingState();
}

class _LoadingState extends State<Loading> {
  void getData() async {
    Response response = await get(
      Uri.http("https://jsonplaceholder.typicode.com", "todos/1"),
    );
    print(response.body);
  }

  @override
  void initState() {
    super.initState();
    getData();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Text("Loading Screen"),
    );
  }
}

```

@FlutterIssues

**Comment by akhil-ge0rge** [comment]
**Change Code to :** 

`Response response = await get(Uri.parse('https://jsonplaceholder.typicode.com/todos/1'));`
