### ISSUE TITLE
[web] `showDatePicker` on web shows an error when date selected. 

### ISSUE THREAD

**Issue by ZiyadF296** [flutter/flutter#82375]
## Steps to Reproduce

Create a default flutter project. Replace the code in the `main.dart` with the below:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String? title;

  MyHomePage({Key? key, this.title}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title!)),
      body: Center(
        child: MaterialButton(
          onPressed: () async {
            DateTime? _d = await showDatePicker(
              context: context,
              initialDate: DateTime.now(),
              firstDate: DateTime.now(),
              lastDate: DateTime.now(),
            );
            if (_d != null) {
              print(_d);
              ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text('$_d is the selected date')));
            }
          },
          child: Text('Select Date'),
        ),
      ),
    );
  }
}
```

Once `main.dart` is replaced, run the app on WEB. This issue can only be found on the web.

**Expected results:** 
Nothing gets dumped to the console.

**Actual results:** 
If uncaught exceptions is turned on, the app stops and I get the error. However, if it is off, it all gets thrown in the console. The error that gets thrown in the console is below in the logs section:

<details>
  <summary>Logs</summary>

```
Launching lib\main.dart on Chrome in debug mode...
Debug service listening on ws://127.0.0.1:53341/upnvNjJs6tc=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:53341/upnvNjJs6tc=/ws
Error: Expected a value of type 'String', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:53170/dart_sdk.js:5031:11)
    at Object.castError (http://localhost:53170/dart_sdk.js:5004:15)
    at Object.cast [as as] (http://localhost:53170/dart_sdk.js:5313:17)
    at Function.as (http://localhost:53170/dart_sdk.js:42399:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:53170/dart_sdk.js:155296:38)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:53170/dart_sdk.js:155212:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:2180:38)
    at _DefaultBinaryMessenger.send (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:2224:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:948:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:53170/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:53170/dart_sdk.js:37259:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:946:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:1078:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:1056:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:53170/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:53170/dart_sdk.js:37259:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:1055:20)
    at vibrate (http://localhost:53170/packages/flutter/src/services/haptic_feedback.dart.lib.js:30:55)
    at vibrate.next (<anonymous>)
    at runBody (http://localhost:53170/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:53170/dart_sdk.js:37259:7)
    at Function.vibrate (http://localhost:53170/packages/flutter/src/services/haptic_feedback.dart.lib.js:29:20)
    at calendar_date_picker._CalendarDatePickerState.new.[_vibrate] (http://localhost:53170/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2654:42)
    at calendar_date_picker._CalendarDatePickerState.new.[_handleDayChanged] (http://localhost:53170/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2702:21)
    at calendar_date_picker._MonthPickerState.new.[_handleDateSelected] (http://localhost:53170/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3130:11)
    at http://localhost:53170/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3539:28
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:53170/packages/flutter/src/material/icon_button.dart.lib.js:50084:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:53170/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:53170/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:53170/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:53170/packages/flutter/src/gestures/tap.dart.lib.js:169:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:53170/packages/flutter/src/gestures/recognizer.dart.lib.js:456:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:53170/packages/flutter/src/gestures/pointer_router.dart.lib.js:103:9)
    at http://localhost:53170/packages/flutter/src/gestures/pointer_router.dart.lib.js:138:26
    at LinkedMap.new.forEach (http://localhost:53170/dart_sdk.js:25047:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:53170/packages/flutter/src/gestures/pointer_router.dart.lib.js:135:29)
    at pointer_router.PointerRouter.new.route (http://localhost:53170/packages/flutter/src/gestures/pointer_router.dart.lib.js:127:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:330:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:313:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:53170/packages/flutter/src/rendering/layer.dart.lib.js:6071:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:284:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:257:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:246:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:236:65)
    at Object.invoke1 (http://localhost:53170/dart_sdk.js:173274:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:53170/dart_sdk.js:155199:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:53170/dart_sdk.js:155813:49)
    at http://localhost:53170/dart_sdk.js:156230:28
    at http://localhost:53170/dart_sdk.js:156186:16
    at http://localhost:53170/dart_sdk.js:155906:11

```

```
Analyzing app...                                                        
No issues found! (ran in 11.0s)
```

```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ziyad\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.56.1)
    • VS Code at C:\Users\ziyad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```

</details>

**Comment by ggichure** [comment]
To me looks like the picker was cancelled ,

try using the .then to show scaffold or perform any operations on the picked date 

```
 await showDatePicker(
              context: context,
              initialDate: DateTime.now(),
              firstDate: DateTime.now(),
              lastDate: DateTime.now(),
            ).then((val){ 

my functions});
```

**Comment by ZiyadF296** [comment]
Here is the updated code snippet:
```dart
await showDatePicker(
              context: context,
              initialDate: DateTime.now(),
              firstDate: DateTime.now(),
              lastDate: DateTime.now(),
            ).then((value) {
              if (value != null) {
                print(value);
                ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('$value is the selected date')));
              }
            });
```

**Comment by ggichure** [comment]
> Here is the updated code snippet:
> 
> ```dart
> await showDatePicker(
>               context: context,
>               initialDate: DateTime.now(),
>               firstDate: DateTime.now(),
>               lastDate: DateTime.now(),
>             ).then((value) {
>               if (value != null) {
>                 print(value);
>                 ScaffoldMessenger.of(context).showSnackBar(
>                     SnackBar(content: Text('$value is the selected date')));
>               }
>             });
> ```
this should work. does it print a value?

**Comment by ZiyadF296** [comment]
Yes, it does. The old example prints the value as well.
However, type error gets asserted. Check initial comment. @ggichure

**Comment by darshankawar** [comment]
@ZiyadF296 
Ran your code sample on latest master and stable using both renderers, but didn't get the exception you mentioned. The selected date is printed in the console everytime I tap OK.

```
💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:50863/J2_VOcBy9fo=
Activating Dart DevTools...                                         3.1s
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A50863%2FJ2_VOcBy9fo%3D
2021-05-13 00:00:00.000
2021-05-13 00:00:00.000
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

Are there any specific steps you took that leads to that error ?

**Comment by ZiyadF296** [comment]
Did you run it on flutter web?

**Comment by ZiyadF296** [comment]
Also, I would consider turning on uncought exceptions

**Comment by darshankawar** [comment]
@ZiyadF296 
Yes I ran it on web. See the console log I shared earlier.
Also, turn on uncaught exceptions in IDE or in browser console ?

**Comment by ZiyadF296** [comment]
Turn uncaught exceptions in IDE @darshankawar

**Comment by darshankawar** [comment]
@ZiyadF296 
Tried the same, but seeing the selected date printed in console properly:

```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:50135/AyCT1UCqe_k=/ws
Debug service listening on ws://127.0.0.1:50135/AyCT1UCqe_k=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:50135/AyCT1UCqe_k=/ws
2021-05-14 00:00:00.000
2021-05-14 00:00:00.000
```

**Comment by ZiyadF296** [comment]
Yup, just realized, I totally forgot to mention to migrate the app to sound null-safety.
That is the error, with null safety. @darshankawar

**Comment by darshankawar** [comment]
Thanks for pointing that out. With null safety ON along with enabling uncaught exceptions, I see the same behavior as mentioned:

<details>
<summary>console error log </summary>

```


Error: Expected a value of type 'String', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:53170/dart_sdk.js:5031:11)
    at Object.castError (http://localhost:53170/dart_sdk.js:5004:15)
    at Object.cast [as as] (http://localhost:53170/dart_sdk.js:5313:17)
    at Function.as (http://localhost:53170/dart_sdk.js:42399:19)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:53170/dart_sdk.js:155296:38)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:53170/dart_sdk.js:155212:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:2180:38)
    at _DefaultBinaryMessenger.send (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:2224:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:948:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:53170/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:53170/dart_sdk.js:37259:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:946:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:1078:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:1056:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:53170/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:53170/dart_sdk.js:37259:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:53170/packages/flutter/src/services/system_channels.dart.lib.js:1055:20)
    at vibrate (http://localhost:53170/packages/flutter/src/services/haptic_feedback.dart.lib.js:30:55)
    at vibrate.next (<anonymous>)
    at runBody (http://localhost:53170/dart_sdk.js:37228:34)
    at Object._async [as async] (http://localhost:53170/dart_sdk.js:37259:7)
    at Function.vibrate (http://localhost:53170/packages/flutter/src/services/haptic_feedback.dart.lib.js:29:20)
    at calendar_date_picker._CalendarDatePickerState.new.[_vibrate] (http://localhost:53170/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2654:42)
    at calendar_date_picker._CalendarDatePickerState.new.[_handleDayChanged] (http://localhost:53170/packages/flutter/src/material/calendar_date_picker.dart.lib.js:2702:21)
    at calendar_date_picker._MonthPickerState.new.[_handleDateSelected] (http://localhost:53170/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3130:11)
    at http://localhost:53170/packages/flutter/src/material/calendar_date_picker.dart.lib.js:3539:28
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:53170/packages/flutter/src/material/icon_button.dart.lib.js:50084:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:53170/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:53170/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:53170/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:53170/packages/flutter/src/gestures/tap.dart.lib.js:169:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:53170/packages/flutter/src/gestures/recognizer.dart.lib.js:456:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:53170/packages/flutter/src/gestures/pointer_router.dart.lib.js:103:9)
    at http://localhost:53170/packages/flutter/src/gestures/pointer_router.dart.lib.js:138:26
    at LinkedMap.new.forEach (http://localhost:53170/dart_sdk.js:25047:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:53170/packages/flutter/src/gestures/pointer_router.dart.lib.js:135:29)
    at pointer_router.PointerRouter.new.route (http://localhost:53170/packages/flutter/src/gestures/pointer_router.dart.lib.js:127:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:330:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:313:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:53170/packages/flutter/src/rendering/layer.dart.lib.js:6071:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:284:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:257:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:246:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:53170/packages/flutter/src/gestures/binding.dart.lib.js:236:65)
    at Object.invoke1 (http://localhost:53170/dart_sdk.js:173274:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:53170/dart_sdk.js:155199:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:53170/dart_sdk.js:155813:49)
    at http://localhost:53170/dart_sdk.js:156230:28
    at http://localhost:53170/dart_sdk.js:156186:16
    at http://localhost:53170/dart_sdk.js:155906:11
```

</details>

<details>
<summary> code sample </summary>

```
dhs@Dhss-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-2.0.pre.203, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.203 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c533ab6515 (4 hours ago), 2021-05-13 23:04:02 -0700
    • Engine revision 0507f4a9a7
    • Dart version 2.14.0 (build 2.14.0-114.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.
dhs@Dhss-MacBook-Pro ~ % 




```

</details>
