### ISSUE TITLE
Running into "SkiaObjectCollectionError: RuntimeError: memory access out of bounds" error

### ISSUE THREAD

**Issue by yasinallana** [flutter/flutter#82416]
## Steps to Reproduce

use the code in [this repository](https://github.com/yasinallana/Flutter-web-issue) and then switch the ui rapidly using the buttons on the left side of the screen i.e. "Company Details" , "Shareholder Detaills", "Company Document", "Declaration".

**Expected results:** No memory access out of bounds.

**Actual results:** seeing "SkiaObjectCollectionError: RuntimeError: memory access out of bounds" error continuously. 

<details>
  <summary>Logs</summary>

```
Error: SkiaObjectCollectionError: RuntimeError: memory access out of bounds
https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 158:166                                                      mc
https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 197:352                                                      delete
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/canvaskit_api.dart 1860:18  collectSkiaObjectsNow
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/canvaskit_api.dart 1828:7   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19  internalCallback
    at Object.throw_ [as throw] (http://localhost:54055/dart_sdk.js:5333:11)
    at _engine.ProductionCollector.new.collectSkiaObjectsNow (http://localhost:54055/dart_sdk.js:138487:19)
    at http://localhost:54055/dart_sdk.js:138453:14
    at internalCallback (http://localhost:54055/dart_sdk.js:25103:11)
```

```
Analyzing kratos_flutter...                                             
No issues found! (ran in 2.5s)
```

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.964], locale en-US)
    • Flutter version 2.0.6 at D:\Yasin\Developement\Tools\FlutterSDK       
    • Framework revision 1d9032c7e1 (13 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2) 
    • Android SDK at D:\Yasin\Developement\Tools\AndroidSDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Yasin\Developement\Tools\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.1)
    • VS Code at C:\Users\Yasin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212       
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56        

• No issues found!
```

</details>

### Additionally
Additionally facing `ASSERT: 0.000000 != 16.000000` logs in the debug console in vscode as well as chrome

![Screenshot (23)](https://user-images.githubusercontent.com/12084947/118081636-62b16480-b3d9-11eb-88df-3017faf108dc.png)

**Comment by darshankawar** [comment]
@yasinallana 
Thanks for the report. From your repo, I see that you are using couple of 3rd party plugins, like `measured_size` and `flutter_svg`.
Does the exception occur if you remove those plugins and their relevant code ? If you haven't tried that already, can you check that once and confirm ?

**Comment by yasinallana** [comment]
@darshankawar Yes the exception still occurs when i remove the third party plugins.
![image](https://user-images.githubusercontent.com/12084947/118103666-c8ace480-b3f7-11eb-8951-4a15b1c19c8c.png)

**Comment by darshankawar** [comment]
@yasinallana 
I am unable to replicate the `memory access out of bounds` error in the browser console. But I see below log in the IDE console after switching between the said buttons fast:

```
dhs@Dhss-MacBook-Pro Flutter-web-issue % flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             16.1s
Debug service listening on ws://127.0.0.1:52521/MDZoWbVyxIc=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
Error: SkiaObjectCollectionError: RuntimeError: memory access out of bounds
https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 158:166         mc
https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 197:352         delete
lib/_engine/engine/canvaskit/canvaskit_api.dart 1860:18                  collectSkiaObjectsNow
lib/_engine/engine/canvaskit/canvaskit_api.dart 1828:7                   <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19  internalCallback

    at Object.throw_ [as throw] (http://localhost:52498/dart_sdk.js:5333:11)
    at _engine.ProductionCollector.new.collectSkiaObjectsNow (http://localhost:52498/dart_sdk.js:138487:19)
    at http://localhost:52498/dart_sdk.js:138453:14
    at internalCallback (http://localhost:52498/dart_sdk.js:25103:11)
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following NativeJavaScriptObject object was thrown during a scheduler callback:
  RuntimeError: unreachable

When the exception was thrown, this was the stack:
https://unpkg.com/canvaskit-wasm@0.24.0/bin/canvaskit.js 170:242  Canvas$drawPicture
lib/_engine/engine/canvaskit/canvas.dart 173:14                   drawPicture
lib/_engine/engine/canvaskit/layer.dart 378:17                    paint
lib/_engine/engine/canvaskit/layer.dart 114:14                    paintChildren
lib/_engine/engine/canvaskit/layer.dart 447:5                     paint
lib/_engine/engine/canvaskit/layer.dart 114:14                    paintChildren
lib/_engine/engine/canvaskit/layer.dart 311:5                     paint
lib/_engine/engine/canvaskit/layer.dart 114:14                    paintChildren
lib/_engine/engine/canvaskit/layer.dart 311:5                     paint
lib/_engine/engine/canvaskit/layer.dart 114:14                    paintChildren
lib/_engine/engine/canvaskit/layer.dart 311:5                     paint
lib/_engine/engine/canvaskit/layer_tree.dart 52:7                 paint
lib/_engine/engine/canvaskit/layer_tree.dart 97:16                <fn>
lib/_engine/engine/profiler.dart 36:18                            timeAction
lib/_engine/engine/canvaskit/layer_tree.dart 96:5                 raster
lib/_engine/engine/canvaskit/rasterizer.dart 34:22                draw
lib/_engine/engine/platform_dispatcher.dart 509:7                 render
lib/ui/src/ui/window.dart 87:50                                   render
packages/flutter/src/rendering/view.dart 220:15                   compositeFrame
packages/flutter/src/rendering/binding.dart 457:18                drawFrame
packages/flutter/src/widgets/binding.dart 874:13                  drawFrame
packages/flutter/src/rendering/binding.dart 319:5                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1144:15               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1082:9                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 998:5                 [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 896:13                invoke
lib/_engine/engine/platform_dispatcher.dart 145:5                 invokeOnDrawFrame
lib/_engine/engine.dart 259:45                                    <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by yasinallana** [comment]
@yasinallana yes this is the error i receive, i also receive it in browser console by first opening the console before rapid switching.

**Comment by darshankawar** [comment]
@yasinallana 
Never mind, there's similar open issue desribing your case, https://github.com/flutter/flutter/issues/80140
Please follow-up there for updates.
Closing this as duplicate.
