### ISSUE TITLE
Analyser dosent work in files where it uses an self created class method named "catchError"

### ISSUE THREAD

**Issue by henrikskul** [flutter/flutter#82443]
## Steps to Reproduce

1. create an class with an method named "catchError".
2. use this method in another file.
3. .The analyser/linter dosent work in this file, because it uses the self created catchError method.

**Expected results:** That the analyser should work. If "catchError" should not be a name of an self created method, the analyser should tell so.

**Actual results:** Analyser dosent detect errors in the file that uses the self created catchError method.

I have reproduced the error here https://github.com/henrikskul/Flutter_catch_error_bug.

#### Output of `flutter analyze` in the project

```
flutter analyze
Analyzing flutter_catc_error_bug...
No issues found! (ran in 3.1s)
```

#### Output of `flutter run` in the project

<details> 
<summary>logs</summary> 
	
```console
flutter run
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
lib/ButtonWithoutLinting.dart:15:11: Error: 'the' isn't a type.

          the linter should show an error here

          ^^^

lib/ButtonWithoutLinting.dart:15:15: Error: Expected ';' after this.

          the linter should show an error here

              ^^^^^^

lib/ButtonWithoutLinting.dart:15:22: Error: 'should' isn't a type.

          the linter should show an error here

                     ^^^^^^

lib/ButtonWithoutLinting.dart:15:29: Error: Expected ';' after this.

          the linter should show an error here

                            ^^^^

lib/ButtonWithoutLinting.dart:15:34: Error: 'an' isn't a type.

          the linter should show an error here

                                 ^^

lib/ButtonWithoutLinting.dart:15:37: Error: Expected ';' after this.

          the linter should show an error here

                                    ^^^^^

lib/ButtonWithoutLinting.dart:15:43: Error: Expected ';' after this.

          the linter should show an error here

                                          ^^^^

lib/ButtonWithoutLinting.dart:15:43: Error: The getter 'here' isn't defined for the class 'ButtonWithoutLinting'.

 - 'ButtonWithoutLinting' is from 'package:flutter_catc_error_bug/ButtonWithoutLinting.dart' ('lib/ButtonWithoutLinting.dart').

Try correcting the name to the name of an existing getter, or defining a getter or field named 'here'.

          the linter should show an error here

                                          ^^^^





FAILURE: Build failed with an exception.



* Where:

Script 'C:\dev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991



* What went wrong:

Execution failed for task ':app:compileFlutterBuildDebug'.

> Process 'command 'C:\dev\flutter\bin\flutter.bat'' finished with non-zero exit value 1



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 14s
Running Gradle task 'assembleDebug'...                             15,4s
Exception: Gradle task assembleDebug failed with exit code 1
```

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
flutter doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19041.450], locale nb-NO)
    • Flutter version 2.0.6 at C:\dev\flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\henriks\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\henriks\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.56.1)
    • VS Code at C:\Users\henriks\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @henrikskul 
Thanks for filing the issue!

<details> 
<summary>logs</summary> 
	
```console
[  +25 ms] Running "flutter pub get" in Flutter_catch_error_bug... (completed in 1,554ms)
[ +117 ms] Generating
C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistr
ant.java
[  +43 ms] ro.hardware = ranchu
[  +11 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +24 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +7 ms] Skipping target: gen_dart_plugin_registrant
[   +2 ms] _composite: Starting due to {}
[   +1 ms] _composite: Complete
[   +4 ms] complete
[   +6 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +6 ms] C:\Users\Taha\Code\flutter_master\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\Taha\Code\flutter_master\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\Taha\Code\flutter_master\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Taha\AppData\Local\Temp\flutter_tools.cd4f8a37\flutter_tool.923c604a\app.dill --packages
C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +20 ms] executing: C:\Users\Taha\Code\SDK\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +19 ms] <- compile package:flutter_catc_error_bug/main.dart
[  +44 ms] --------- beginning of main
           05-14 17:41:01.973 E/GnssHAL_GnssInterface( 1790): gnssSvStatusCb: b: input svInfo.flags is 8
[   +9 ms] executing: C:\Users\Taha\Code\SDK\platform-tools\adb.exe version
[  +54 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as C:\Users\Taha\Code\SDK\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\Taha\Code\SDK\platform-tools\adb.exe start-server
[  +28 ms] Building APK
[  +18 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] Using gradle from C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\android\gradlew.bat.
[  +11 ms] executing: C:\Users\Taha\Code\android-studio\jre\bin\java -version
[ +116 ms] Exit code 0 from: C:\Users\Taha\Code\android-studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +1 ms] executing: [C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\android/]
C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\lib\main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2350 ms] lib/ButtonWithoutLinting.dart:15:11: Error: 'the' isn't a type.
[        ]           the linter should show an error here
[        ]           ^^^
[  +25 ms] lib/ButtonWithoutLinting.dart:15:15: Error: Expected ';' after this.
[        ]           the linter should show an error here
[        ]               ^^^^^^
[        ] lib/ButtonWithoutLinting.dart:15:22: Error: 'should' isn't a type.
[        ]           the linter should show an error here
[        ]                      ^^^^^^
[        ] lib/ButtonWithoutLinting.dart:15:29: Error: Expected ';' after this.
[        ]           the linter should show an error here
[        ]                             ^^^^
[        ] lib/ButtonWithoutLinting.dart:15:34: Error: 'an' isn't a type.
[        ]           the linter should show an error here
[        ]                                  ^^
[        ] lib/ButtonWithoutLinting.dart:15:37: Error: Expected ';' after this.
[        ]           the linter should show an error here
[        ]                                     ^^^^^
[        ] lib/ButtonWithoutLinting.dart:15:43: Error: Expected ';' after this.
[        ]           the linter should show an error here
[        ]                                           ^^^^
[   +1 ms] lib/ButtonWithoutLinting.dart:15:43: Error: The getter 'here' isn't defined for the class
'ButtonWithoutLinting'.
[        ]  - 'ButtonWithoutLinting' is from 'package:flutter_catc_error_bug/ButtonWithoutLinting.dart'
('lib/ButtonWithoutLinting.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'here'.
[        ]           the linter should show an error here
[        ]                                           ^^^^
[+2199 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +77 ms] executing: [C:\Users\Taha\Code\flutter_master/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +5 ms] [  +78 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 9108c06217c2c1363dbc0659048d6f94329adf2a
[        ] [        ] executing: [C:\Users\Taha\Code\flutter_master/] git tag --points-at
9108c06217c2c1363dbc0659048d6f94329adf2a
[        ] [  +52 ms] Exit code 0 from: git tag --points-at 9108c06217c2c1363dbc0659048d6f94329adf2a
[        ] [   +1 ms] executing: [C:\Users\Taha\Code\flutter_master/] git describe --match *.*.* --long --tags
9108c06217c2c1363dbc0659048d6f94329adf2a
[        ] [  +86 ms] Exit code 0 from: git describe --match *.*.* --long --tags
9108c06217c2c1363dbc0659048d6f94329adf2a
[        ] [        ] 2.3.0-1.0.pre-205-g9108c06217
[        ] [   +5 ms] executing: [C:\Users\Taha\Code\flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [C:\Users\Taha\Code\flutter_master/] git ls-remote --get-url origin
[        ] [  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +56 ms] executing: [C:\Users\Taha\Code\flutter_master/] git rev-parse --abbrev-ref HEAD
[        ] [  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +62 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +101 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +43 ms] Initializing file store
[        ] [  +22 ms] Skipping target: gen_localizations
[        ] [  +13 ms] Skipping target: gen_dart_plugin_registrant
[        ] [   +2 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [  +11 ms] C:\Users\Taha\Code\flutter_master\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\Taha\Code\flutter_master\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\Taha\Code\flutter_master\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
--no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --no-link-platform --packages
C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\.dart_tool\package_config.json --output-dill
C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\.dart_tool\flutter_build\4b312ede7e44295aeef9638b9864385e\app.dill
--depfile
C:\Users\Taha\StudioProjects\Flutter_catch_error_bug\.dart_tool\flutter_build\4b312ede7e44295aeef9638b9864385e\kernel_sn
apshot.d package:flutter_catc_error_bug/main.dart
[+1855 ms] [+2440 ms] lib/ButtonWithoutLinting.dart:15:11: Error: 'the' isn't a type.
[        ] [   +1 ms]           the linter should show an error here
[        ] [        ]           ^^^
[   +1 ms] [   +4 ms] lib/ButtonWithoutLinting.dart:15:15: Error: Expected ';' after this.
[   +1 ms] [        ]           the linter should show an error here
[        ] [        ]               ^^^^^^
[        ] [   +2 ms] lib/ButtonWithoutLinting.dart:15:22: Error: 'should' isn't a type.
[        ] [        ]           the linter should show an error here
[        ] [        ]                      ^^^^^^
[        ] [        ] lib/ButtonWithoutLinting.dart:15:29: Error: Expected ';' after this.
[        ] [        ]           the linter should show an error here
[        ] [        ]                             ^^^^
[        ] [        ] lib/ButtonWithoutLinting.dart:15:34: Error: 'an' isn't a type.
[        ] [        ]           the linter should show an error here
[        ] [        ]                                  ^^
[        ] [        ] lib/ButtonWithoutLinting.dart:15:37: Error: Expected ';' after this.
[        ] [        ]           the linter should show an error here
[        ] [        ]                                     ^^^^^
[        ] [        ] lib/ButtonWithoutLinting.dart:15:43: Error: Expected ';' after this.
[        ] [        ]           the linter should show an error here
[        ] [        ]                                           ^^^^
[        ] [   +6 ms] lib/ButtonWithoutLinting.dart:15:43: Error: The getter 'here' isn't defined for the class
'ButtonWithoutLinting'.
[        ] [        ]  - 'ButtonWithoutLinting' is from 'package:flutter_catc_error_bug/ButtonWithoutLinting.dart'
('lib/ButtonWithoutLinting.dart').
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named
'here'.
[        ] [        ]           the linter should show an error here
[        ] [        ]                                           ^^^^
[+5795 ms] [+5720 ms] Persisting file store
[        ] [   +2 ms] Done persisting file store
[   +1 ms] [   +3 ms] Target kernel_snapshot failed: Exception
[   +1 ms]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:229:7)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:838:9)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:776:32)
[   +1 ms]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:605:16)
[   +1 ms]            <asynchronous suspension>
[        ]            #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1090:27)
[   +1 ms]            <asynchronous suspension>
[        ]            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +4 ms]
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1090:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[   +1 ms]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +9 ms] "flutter assemble" took 8,418ms.
[        ] [  +72 ms] ensureAnalyticsSent: 71ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[  +35 ms] > Task :app:compileFlutterBuildDebug FAILED
[   +1 ms] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[   +1 ms] Script 'C:\Users\Taha\Code\flutter_master\packages\flutter_tools\gradle\flutter.gradle' line: 1035
[   +1 ms] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command 'C:\Users\Taha\Code\flutter_master\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 12s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[ +514 ms] Running Gradle task 'assembleDebug'... (completed in 13.0s)
[   +4 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 15,411ms.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:664:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1090:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +33 ms] ensureAnalyticsSent: 30ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
PS C:\Users\Taha\StudioProjects\Flutter_catch_error_bug>
```

</details>


Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.6 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.205, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.3.0-2.0.pre.205 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9108c06217 (9 hours ago), 2021-05-14 02:14:03 -0400
    • Engine revision c75ec8ea4d
    • Dart version 2.14.0 (build 2.14.0-115.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 90.0.818.56

• No issues found!
```
		
</details>

**Comment by jmagman** [comment]
@henrikskul would you mind re-filing this in https://github.com/dart-lang/sdk/ so the dart team can take a look?

**Comment by henrikskul** [comment]
issue is now re-filled here: https://github.com/dart-lang/sdk/issues/46051

**Comment by jmagman** [comment]
Thanks, @henrikskul! Closing.
