### ISSUE TITLE
[engine] ninja fails with cryptic "gyp-win-tool" error trying to rebuild after gclient sync

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#82468]
I am frequently unable to rebuild the engine incrementally on Windows 10 due to the following error. I have to delete whole `host_debug_unopt` and compile from scratch, which takes considerably longer.

Error:

```
[3010/3243] COPY dart.exe dart-sdk/bin/dart.exe
FAILED: dart-sdk/bin/dart.exe
C:/code/depot_tools/bootstrap-2@3_8_10_chromium_17_bin/python/bin/python.exe gyp-win-tool recursive-mirror dart.exe dart-sdk/bin/dart.exe
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    os.unlink(dest)
```

I have never seen this error on non-incremental builds. Deleting `host_debug_unopt` fixes it every time.

(sometime the error is about not having access to dart.exe, but I didn't get it this time; I'll file a separate issue if I see that one).

**Comment by yjbanov** [comment]
This hasn't happened to me in a while. Closing.
