### ISSUE TITLE
flutter buld appbundle error For input string: in version build number line.

### ISSUE THREAD

**Issue by jordantsap** [flutter/flutter#82561]
```console
* Where:
Build file 'C:\Users\iordanis\AndroidStudioProjects\safein\android\app\build.gradle' line: 51

* What went wrong:
A problem occurred evaluating project ':app'.
> For input string: in version build number.
```
<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.746], locale el-GR)
    • Flutter version 2.0.6 at L:\flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\iordanis\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

</details>

Android Studio 4.2.1

Gradle version : distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

```gradle
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
<details> 
<summary>logs</summary> 
	
```console
$ flutter build appbundle -v output
[  +69 ms] executing: [L:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +47 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] executing: [L:\flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +33 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +36 ms] executing: [L:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [L:\flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [L:\flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +61 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +51 ms] Skipping pub get: version match.
[  +17 ms] Found plugin app_settings at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\app_settings-4.0.4\
[  +15 ms] Found plugin connectivity at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\connectivity-3.0.3\
[   +2 ms] Found plugin connectivity_for_web at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\connectivity_for_web-0.4.0\
[   +1 ms] Found plugin connectivity_macos at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\connectivity_macos-0.2.0\
[  +12 ms] Found plugin flutter_sms at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_sms-2.3.1\
[   +1 ms] Found plugin geolocator at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\geolocator-7.0.1\
[   +2 ms] Found plugin geolocator_web at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\geolocator_web-2.0.3\
[  +14 ms] Found plugin path_provider_linux at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +3 ms] Found plugin path_provider_windows at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[   +2 ms] Found plugin permission_handler at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\permission_handler-6.1.1\
[  +10 ms] Found plugin shared_preferences at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +1 ms] Found plugin shared_preferences_linux at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +1 ms] Found plugin shared_preferences_macos at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +2 ms] Found plugin shared_preferences_web at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +1 ms] Found plugin shared_preferences_windows at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[   +1 ms] Found plugin smsker at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\smsker-0.1.1\
[   +9 ms] Found plugin url_launcher at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[   +1 ms] Found plugin url_launcher_linux at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[   +1 ms] Found plugin url_launcher_macos at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +1 ms] Found plugin url_launcher_web at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[        ] Found plugin url_launcher_windows at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +91 ms] Found plugin app_settings at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\app_settings-4.0.4\
[   +6 ms] Found plugin connectivity at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\connectivity-3.0.3\
[   +1 ms] Found plugin connectivity_for_web at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\connectivity_for_web-0.4.0\
[        ] Found plugin connectivity_macos at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\connectivity_macos-0.2.0\
[   +6 ms] Found plugin flutter_sms at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_sms-2.3.1\
[   +1 ms] Found plugin geolocator at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\geolocator-7.0.1\
[   +1 ms] Found plugin geolocator_web at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\geolocator_web-2.0.3\
[   +7 ms] Found plugin path_provider_linux at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_windows at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\path_provider_windows-2.0.0\
[   +2 ms] Found plugin permission_handler at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\permission_handler-6.1.1\
[   +4 ms] Found plugin shared_preferences at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[        ] Found plugin shared_preferences_linux at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[        ] Found plugin shared_preferences_macos at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +1 ms] Found plugin shared_preferences_web at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +1 ms] Found plugin shared_preferences_windows at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[        ] Found plugin smsker at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\smsker-0.1.1\
[   +5 ms] Found plugin url_launcher at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-6.0.3\
[        ] Found plugin url_launcher_linux at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_linux-2.0.0\
[        ] Found plugin url_launcher_macos at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_macos-2.0.0\
[   +1 ms] Found plugin url_launcher_web at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_web-2.0.0\
[        ] Found plugin url_launcher_windows at C:\Users\iordanis\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher_windows-2.0.0\
[  +17 ms] Generating C:\Users\iordanis\AndroidStudioProjects\safein\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +63 ms] Building without sound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[  +19 ms] Running Gradle task 'bundleRelease'...
[   +3 ms] Using gradle from C:\Users\iordanis\AndroidStudioProjects\safein\android\gradlew.bat.
[        ] C:\Users\iordanis\AndroidStudioProjects\safein\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +8 ms] executing: [C:\Users\iordanis\AndroidStudioProjects\safein\android/] C:\Users\iordanis\AndroidStudioProjects\safein\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib\main.dart -Ptrack-widget-creation=true -Ptree-shake-icons=true bundleRelease
[+1746 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file 'C:\Users\iordanis\AndroidStudioProjects\safein\android\app\build.gradle' line: 51
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':app'.
[        ] > For input string: "9999999999"
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[ +575 ms] Running Gradle task 'bundleRelease'... (completed in 2.330ms)
[   +4 ms] "flutter appbundle" took 2.838ms.
[   +3 ms] Gradle task bundleRelease failed with exit code 1
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:411:7)
           <asynchronous suspension>
           #2      _AndroidBuilderImpl.buildAab (package:flutter_tools/src/android/android_builder.dart:121:7)
           <asynchronous suspension>
           #3      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:90:5)
           <asynchronous suspension>
           #4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #14     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #16     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #17     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #18     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +51 ms] ensureAnalyticsSent: 49ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

**Comment by TahaTesser** [comment]
Hi @jordantsap 
Have you modify your `safein\android\app\build.gradle`, checkout line 51, it points to something wrong. 

Can you please provide this build.gradle` from android/app folder (not android)?

Thank you

**Comment by jordantsap** [comment]
The only change that i made was in line 53 for debugSymbolLevel bellow  the line for versionName flutterVersionName
ndk {
            debugSymbolLevel 'FULL'
        }

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
android {
    compileSdkVersion 30
    ndkVersion "22.1.7171670"

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "eu.anathesis.safein"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        ndk {
            debugSymbolLevel 'FULL'
        }
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

android.buildTypes.release.ndk.debugSymbolLevel

**Comment by jordantsap** [comment]
> Hi @jordantsap
> Have you modify your `safein\android\app\build.gradle`, checkout line 51, it points to something wrong.
> 
> Can you please provide this build.gradle` from android/app folder (not android)?
> 
> Thank you

Its not always happening
for example if the version number is something like below 9 digits long, it accepts it

**Comment by TahaTesser** [comment]
Hi @jordantsap 

> for example if the version number is something like below 9 digits long, it accepts it?

Can you please share your `pubspec.yaml` too?

**Comment by jordantsap** [comment]
name: safein
description: Helps customers by sending sms and email to accommodation services after checkin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.16+9999999999
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

#  path_provider: 2.0.0
#  flutter_sms: ^2.1.1
  flutter_sms: #^2.3.1 #^1.1.0
#  permission_handler: ^5.0.1+1
  permission_handler: #^6.1.1
  mailer: #^3.2.1
#  shared_preferences: ^0.5.12+4
  shared_preferences: #^2.0.5
  app_settings: #^4.0.4
  geolocator: #^7.0.1
#  connectivity: ^2.0.2
  connectivity: #^3.0.3
  after_layout: #^1.0.7+2
  http: #^0.12.2
  country_code_picker: #^1.7.0
#  url_launcher: ^5.4.2
  url_launcher: #^6.0.3
  smsker: ^0.1.1

#  pull_to_refresh: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
# no indentation for icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/safein_launcher_icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this
  assets:
    - languages/el.json
    - languages/en.json
    - aclogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by TahaTesser** [comment]
Hi @jordantsap 
Native Android app also crashes this kinda versioning, this is not an issue with Flutter. 

You try it yourself, create a native Android app from Android Studio without Flutter

### Crashes
```console
    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 99999
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```

### Work fine
```console
    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 9999999999
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
```

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
