### ISSUE TITLE
Flutter container bottom-center aligned in a stack not fully aligned at the bottom

### ISSUE THREAD

**Issue by tmdarwen** [flutter/flutter#82578]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
Replace main.dart with:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Container(
            decoration: BoxDecoration(
              color: Colors.black,
            ),
            child: Center(
              child: Container(
                  height: 300,
                  width: 300,
                  child: Stack(children: [
                    Container(color: Colors.yellow),
                    Align(
                        alignment: Alignment.bottomCenter,
                        child: SizedBox(
                            height: 50,
                            child: Container(
                              color: Colors.grey.shade900.withOpacity(0.9),
                            )))
                  ])),
            )));
  }
}

```
3. Run the application in Chrome

**Expected results:**
The bottom centered container should show no yellow on the bottom edge, the left edge or the right edge.  Sometimes it does as you resize Chrome's window size.

**Actual results:**
The bottom centered container sometimes shows yellow on the bottom edge, the left edge or the right edge as you resize Chrome's window size.  

As shown here: https://i.stack.imgur.com/CF6Ol.png

Please see this more more details: https://stackoverflow.com/questions/67539672/flutter-container-bottom-center-aligned-in-a-stack-not-fully-aligned-at-the-bott/67539863?noredirect=1#comment119380349_67539863

<details>
  <summary>Logs</summary>

```
PS C:\NonSys\FlutterBug\myapp> flutter run --verbose
[  +84 ms] executing: [C:\NonSys\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +94 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[   +1 ms] executing: [C:\NonSys\flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +72 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +38 ms] executing: [C:\NonSys\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\NonSys\flutter/] git ls-remote --get-url origin
[  +45 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +83 ms] executing: [C:\NonSys\flutter/] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +79 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +61 ms] executing: C:\Users\terence.darwen\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +49 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +73 ms] Multiple devices found:
[  +23 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
[   +1 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212
[   +2 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+13862 ms] Q
[  +11 ms] "flutter run" took 14,124ms.
[  +17 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DeviceManager._chooseOneOfAvailableDevices (package:flutter_tools/src/device.dart:306:7)
           <asynchronous suspension>
           #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:294:37)
           <asynchronous suspension>
           #3      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1193:28)
           <asynchronous suspension>
           #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:440:15)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1114:5)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #9      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #15     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #17     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #18     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #19     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +161 ms] ensureAnalyticsSent: 150ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
PS C:\NonSys\FlutterBug\myapp> flutter run --verbose
[  +89 ms] executing: [C:\NonSys\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +87 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] executing: [C:\NonSys\flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[  +73 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +38 ms] executing: [C:\NonSys\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\NonSys\flutter/] git ls-remote --get-url origin
[  +46 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +87 ms] executing: [C:\NonSys\flutter/] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +73 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] executing: C:\Users\terence.darwen\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +48 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +73 ms] Multiple devices found:
[  +25 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
[   +1 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+8685 ms] 2
[  +12 ms] Skipping pub get: version match.
[ +121 ms] Generating C:\NonSys\FlutterBug\myapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +99 ms] Launching lib\main.dart on Chrome in debug mode...
[ +123 ms] Updating assets
[  +76 ms] Waiting for connection from debug service on Chrome...
[  +93 ms] <- reset
[   +9 ms] C:\NonSys\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\NonSys\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\NonSys\flutter\bin\cache\flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\TERENC~1.DAR\AppData\Local\Temp\flutter_tools.1aae4075\flutter_tool.aafa09d\app.dill--libraries-spec file:///C:/NonSys/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\NonSys\FlutterBug\myapp\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root C:\Users\TERENC~1.DAR\AppData\Local\Temp\flutter_tools.1aae4075\flutter_tools.f9c8dcf1 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///C:/NonSys/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +12 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+15745 ms] Waiting for connection from debug service on Chrome... (completed in 15.8s)
[   +1 ms] Synced 29.1MB.
[        ] <- accept
[        ] Caching compiled dill
[ +247 ms] Using Opening in existing browser session.

[ +905 ms] [CHROME]:
[  +11 ms] [CHROME]:DevTools listening on ws://127.0.0.1:59992/devtools/browser/b4879423-f97a-43e3-8400-2907a787d1ee
[ +217 ms] DwdsInjector: Received request for entrypoint at http://localhost:59970/main_module.bootstrap.js
[   +6 ms] MetadataProvider: Loading debug metadata...
[  +12 ms] MetadataProvider: Loaded debug metadata
[   +6 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:59970/main_module.bootstrap.js
[+5282 ms] DevHandler: Debug service listening on ws://127.0.0.1:60035/EI36EbYj_Y8=/ws

[   +9 ms] Debug service listening on ws://127.0.0.1:60035/EI36EbYj_Y8=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms]   To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[+42618 ms] DevHandler: Stopped debug service on ws://127.0.0.1:60033

[+4165 ms] Application finished.
[   +4 ms] "flutter run" took 78,747ms.
[  +82 ms] ensureAnalyticsSent: 79ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[ +173 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@tmdarwen 
Can you provide `flutter doctor -v` ? 
I verified on latest master using Mac, on which the reported behavior doesn't occur.

<img width="625" alt="Screenshot 2021-05-17 at 3 27 31 PM" src="https://user-images.githubusercontent.com/67046386/118470699-8b609380-b724-11eb-85af-145191b8a0f7.png">


<details>
<summary> code sample </summary>

```
[✓] Flutter (Channel master, 2.3.0-2.0.pre.240, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.240 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e364e30c90 (6 hours ago), 2021-05-16 19:40:00 -0700
    • Engine revision 193be59942
    • Dart version 2.14.0 (build
      2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.



```

</details>

**Comment by tmdarwen** [comment]
Ah, yes, apologies for leaving off the flutter doctor output in my original report.  I've added it below.  @darshankawar interesting it's not happening on Mac.  Did you try changing the window size of the browser?  I find as I change the window size of Chrome the issue will occur about 50% of the time.

```
PS C:\NonSys\FlutterBug\myapp> flutter doctor -v
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.6 at C:\NonSys\flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\terence.darwen\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\terence.darwen\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

**Comment by darshankawar** [comment]
Yes. I think it's specific to Windows machine, since on mac, I wasn't able to replicate it.
Resizing the browser window does show yellow edge at the bottom.

Flutter master version : `Channel master, 2.3.0-2.0.pre.253` on Windows 10.
