### ISSUE TITLE
MissingPluginException(No implementation found for method DatabaseReference#set on channel plugins.flutter.io/firebase_database

### ISSUE THREAD

**Issue by watoo** [flutter/flutter#82608]
I'm using firebase real-time database. 

**Packages:**
firebase_core: ^1.0.3
firebase_database: ^6.1.2

- setup firebase for android, and its saving data fine
- setup firebase for web (https://firebase.flutter.dev/docs/installation/web/) and it's giving below error.

**Error:**

```
Error: MissingPluginException(No implementation found for method DatabaseReference#set on channel plugins.flutter.io/firebase_database)
    at Object.throw_ [as throw] (http://127.0.0.1:8080/dart_sdk.js:5355:11)
    at MethodChannel._invokeMethod (http://127.0.0.1:8080/packages/flutter/src/services/system_channels.dart.lib.js:962:21)
    at _invokeMethod.next (<anonymous>)
    at http://127.0.0.1:8080/dart_sdk.js:39215:33
    at _RootZone.runUnary (http://127.0.0.1:8080/dart_sdk.js:39072:58)
    at _FutureListener.thenAwait.handleValue (http://127.0.0.1:8080/dart_sdk.js:34058:29)
    at handleValueCallback (http://127.0.0.1:8080/dart_sdk.js:34618:49)
    at Function._propagateToListeners (http://127.0.0.1:8080/dart_sdk.js:34656:17)
    at _Future.new.[_completeWithValue] (http://127.0.0.1:8080/dart_sdk.js:34498:23)
    at async._AsyncCallbackEntry.new.callback (http://127.0.0.1:8080/dart_sdk.js:34521:35)
    at Object._microtaskLoop (http://127.0.0.1:8080/dart_sdk.js:39359:13)
    at _startMicrotaskLoop (http://127.0.0.1:8080/dart_sdk.js:39365:13)
    at http://127.0.0.1:8080/dart_sdk.js:34872:9
```

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.3.0-0.1.pre, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.56.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by SirusCodes** [comment]
Realtime DB doesn't support flutter web yet.
https://firebase.flutter.dev/#:~:text=realtime%20database

**Comment by stuartmorgan** [comment]
Closing per above.

Also, in the future please report issues with third-party plugins to their developers, not here.
