### ISSUE TITLE
[camera] plugin Cannot change flashMode to FlashMode.off in front camera

### ISSUE THREAD

**Issue by II11II** [flutter/flutter#82627]
When setFlashMode to FlashMode.off it throws errors
**Test device:** Samsung s9 android 10
```
I/flutter (19389): [setFlashModeFailed, Device does not have flash capabilities]
I/flutter (19389): [CameraException(setFlashModeFailed, Device does not have flash capabilities), #0      CameraController.setFlashMode (package:camera/src/camera_controller.dart:577:7)
I/flutter (19389): <asynchronous suspension>
I/flutter (19389): #1      _AppCameraState.setFlashMode (package:yool/app/presentation/page/camera/app_camera.dart:482:7)
I/flutter (19389): <asynchronous suspension>
I/flutter (19389): #2      _AppCameraState.cameraButtons.<anonymous closure>.<anonymous closure> (package:yool/app/presentation/page/camera/app_camera.dart:319:20)
I/flutter (19389): <asynchronous suspension>
I/flutter (19389): ]

```

```camera: ^0.8.1```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-arm, locale
    ru-UZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] VS Code (version 1.56.0)
[✓] Connected device (3 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)

• No issues found!
```

**Comment by II11II** [comment]
**Extra output**

```
I/ViewRootImpl@8f7ded2[MainActivity](19389): ViewPostIme pointer 0
I/ViewRootImpl@8f7ded2[MainActivity](19389): ViewPostIme pointer 1
I/ViewRootImpl@8f7ded2[MainActivity](19389): ViewPostIme pointer 0
I/ViewRootImpl@8f7ded2[MainActivity](19389): ViewPostIme pointer 1
I/ViewRootImpl@8f7ded2[MainActivity](19389): ViewPostIme pointer 0
I/ViewRootImpl@8f7ded2[MainActivity](19389): ViewPostIme pointer 1
I/CameraManagerGlobal(19389): Camera 2 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client uz.yim.yool API Level 2
I/CameraManagerGlobal(19389): Camera 2 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client uz.yim.yool API Level 2
I/Camera  (19389): [FPS Range Available] is:[15, 15]
I/Camera  (19389): [FPS Range Available] is:[15, 20]
I/Camera  (19389): [FPS Range Available] is:[20, 20]
I/Camera  (19389): [FPS Range Available] is:[10, 24]
I/Camera  (19389): [FPS Range Available] is:[24, 24]
I/Camera  (19389): [FPS Range Available] is:[7, 30]
I/Camera  (19389): [FPS Range Available] is:[8, 30]
I/Camera  (19389): [FPS Range Available] is:[10, 30]
I/Camera  (19389): [FPS Range Available] is:[15, 30]
I/Camera  (19389): [FPS Range Available] is:[30, 30]
I/Camera  (19389): [FPS Range] is:[7, 30]
D/SensorManager(19389): registerListener :: 1, LSM6DSL Acceleration Sensor, 200000, 0,  
E/MethodChannel#plugins.flutter.io/camera(19389): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(19389): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.camera2.CameraDevice.getId()' on a null object reference
E/MethodChannel#plugins.flutter.io/camera(19389): 	at io.flutter.plugins.camera.Camera.setFlashMode(Camera.java:717)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:142)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at android.os.Looper.loop(Looper.java:197)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/MethodChannel#plugins.flutter.io/camera(19389): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/CameraManagerGlobal(19389): Camera 2 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client uz.yim.yool API Level 2
I/flutter (19389): [CameraException(error, Attempt to invoke virtual method 'java.lang.String android.hardware.camera2.CameraDevice.getId()' on a null object reference), #0      CameraController.setFlashMode (package:camera/src/camera_controller.dart:577:7)
I/flutter (19389): <asynchronous suspension>
I/flutter (19389): #1      _AppCameraState.initCamera (package:yool/app/presentation/page/camera/app_camera.dart:100:4)
I/flutter (19389): <asynchronous suspension>
I/flutter (19389): #2      _AppCameraState._getAvailableCameras (package:yool/app/presentation/page/camera/app_camera.dart:81:7)
I/flutter (19389): <asynchronous suspension>
I/flutter (19389): ]
I/CameraManagerGlobal(19389): Camera 2 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client uz.yim.yool API Level 2

```

**Comment by II11II** [comment]
This code makes to throw error:

```
 @override
  void initState() {
    super.initState();

    WidgetsBinding.instance?.addObserver(this);
    _getAvailableCameras();
  }

  Future<void> _getAvailableCameras() async {
    cameras = await availableCameras();

    if (cameras.isNotEmpty) {
      await initCamera(cameras.last);
    }
  }

  Future<void> initCamera(CameraDescription cameraDescription) async {
    if (controller != null) controller!.dispose();
    controller = CameraController(
        // Get a specific camera from the list of available cameras.
        cameraDescription,
        // Define the resolution to use.
        ResolutionPreset.max,
        enableAudio: true,
        imageFormatGroup: ImageFormatGroup.jpeg);


    controller!.initialize().then((value) => setState(() {

          _flashNotifier.value = controller!.value.flashMode;
        }));
   await controller!.setFlashMode(FlashMode.off);
  }
```

**Comment by darshankawar** [comment]
@II11II 
It'd be great if you could provide a complete reproducible code sample that we can directly copy paste and run to verify the issue.

Using your code, I am getting compile error on `flashNotifier`:

<img width="483" alt="Screenshot 2021-05-17 at 4 08 47 PM" src="https://user-images.githubusercontent.com/67046386/118475773-4b9caa80-b72a-11eb-996b-ac60a6580bd9.png">


Also, can you test your code against this PR and see if it resolves your issue ? 
https://github.com/flutter/plugins/pull/3651

**Comment by II11II** [comment]
> @II11II 
> It'd be great if you could provide a complete reproducible code sample that we can directly copy paste and run to verify the issue.
> 
> Using your code, I am getting compile error on `flashNotifier`:
> 
> <img width="483" alt="Screenshot 2021-05-17 at 4 08 47 PM" src="https://user-images.githubusercontent.com/67046386/118475773-4b9caa80-b72a-11eb-996b-ac60a6580bd9.png">
> 
> 
> Also, can you test your code against this PR and see if it resolves your issue ? 
> https://github.com/flutter/plugins/pull/3651

Hi @darshankawar 🖐
Thank you

https://github.com/flutter/plugins/pull/3651#issuecomment-824676690

This pr helped to solve this issue.
 
Please, Flutter team allow this pr to be merged
