### ISSUE TITLE
Nullpointer Exception with onPanUpdate() calling a CustomPainter.

### ISSUE THREAD

**Issue by Marvin10193** [flutter/flutter#82636]
I have a simple Scaffold with a GestureDetector that has a CustomPaint child drawing a rectangle.
Now if I call onPanUpdate() and want to call another CustomPainter for example to paint over the rectangle based on the touches position a NullPointer Exception is thrown.

```
The method 'drawPoints' was called on null.
Receiver: null
Tried calling: drawPoints(Instance of 'PointMode', Instance(length:1) of '_GrowableList', Instance of 'Paint')
```

Here is a small Demo Code to illustrate the Issue, the position of the touchpoints from onPanUpdate are correctly passed to the painter, yet an exception is still thrown.

```
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Crash',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Canvas crashCanvas;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("crash"),
      ),
      body: Center(
        child: GestureDetector(
          child: CustomPaint(size: Size(200, 200), painter: MyPainter()),
          onPanUpdate: (details) {
            MyPainterDetails(details).paint(this.crashCanvas, Size(100, 100));
          },
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class MyPainterDetails extends CustomPainter {
  DragUpdateDetails details;
  MyPainterDetails(this.details);

  @override
  void paint(Canvas canvas, Size size) {
    print(details.globalPosition.dx.toString() +
        "," +
        details.globalPosition.dy.toString());
    canvas.drawPoints(
        ui.PointMode.points,
        [Offset(details.globalPosition.dx, details.globalPosition.dy)],
        Paint()..color = Colors.red);
  }

  @override
  bool shouldRepaint(CustomPainter old) {
    return true;
  }
}

class MyPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(
        Offset(0, 0) & Size(200, 200), Paint()..color = Colors.orange);
  }

  @override
  bool shouldRepaint(CustomPainter old) {
    return true;
  }
}
```

**Comment by Marvin10193** [comment]
The first time the Exception is throwns this also shows up:

```
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      MyPainterDetails.paint
package:flutter_application_1/main.dart:57
#2      _MyHomePageState.build.<anonymous closure>
package:flutter_application_1/main.dart:40
#3      DragGestureRecognizer._checkUpdate.<anonymous closure>
package:flutter/…/gestures/monodrag.dart:436
#4      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:182
...
Handler: "onUpdate"
Recognizer: PanGestureRecognizer#f3a83
    debugOwner: GestureDetector
    start behavior: start
```

This also happens when using the "Touchable" package, which provides a very similar idea of drawing inside other shapes using the onPanUpdate function, maybe the error there can also help to narrow down the issues, see:

https://github.com/nateshmbhat/touchable/issues/19

**Comment by TahaTesser** [comment]
Hi @Marvin10193 
Thanks for filing the issue

Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'dart:ui' as ui;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Crash',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Canvas crashCanvas;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("crash"),
      ),
      body: Center(
        child: GestureDetector(
          child: CustomPaint(size: Size(200, 200), painter: MyPainter()),
          onPanUpdate: (details) {
            MyPainterDetails(details).paint(this.crashCanvas, Size(100, 100));
          },
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class MyPainterDetails extends CustomPainter {
  DragUpdateDetails details;
  MyPainterDetails(this.details);

  @override
  void paint(Canvas canvas, Size size) {
    print(details.globalPosition.dx.toString() +
        "," +
        details.globalPosition.dy.toString());
    canvas.drawPoints(
        ui.PointMode.points,
        [Offset(details.globalPosition.dx, details.globalPosition.dy)],
        Paint()..color = Colors.red);
  }

  @override
  bool shouldRepaint(CustomPainter old) {
    return true;
  }
}

class MyPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(
        Offset(0, 0) & Size(200, 200), Paint()..color = Colors.orange);
  }

  @override
  bool shouldRepaint(CustomPainter old) {
    return true;
  }
}

``` 

</details>

<details> 
<summary>logs</summary> 
	
```console
                    CodeSign /Users/tahatesser/StudioProjects/master_flutter/build/ios/Debug-iphonesimulator/Runner.app (in
                    target 'Runner' from project 'Runner')
                        cd /Users/tahatesser/StudioProjects/master_flutter/ios
                        export
                        CODESIGN_ALLOCATE\=/Volumes/Extreme/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/
                        usr/bin/codesign_allocate

                        Signing Identity:     "-"

                        /usr/bin/codesign --force --sign - --entitlements
                        /Users/tahatesser/Library/Developer/Xcode/DerivedData/Runner-fozhnrbljlzmspdvyyycqobvucew/Build/Inter
                        mediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Runner.app.xcent --timestamp\=none
                        /Users/tahatesser/StudioProjects/master_flutter/build/ios/Debug-iphonesimulator/Runner.app

                    ** BUILD SUCCEEDED **
[ +123 ms]  └─Compiling, linking and signing... (completed in 4.7s)
[   +1 ms] Xcode build done.                                           20.7s
[   +4 ms] executing: rsync -av --delete
/Users/tahatesser/StudioProjects/master_flutter/build/ios/Debug-iphonesimulator/Runner.app
/Users/tahatesser/StudioProjects/master_flutter/build/ios/iphonesimulator
[ +510 ms] building file list ... done
                    Runner.app/
                    Runner.app/Info.plist
                    Runner.app/PkgInfo
                    Runner.app/Runner
                    Runner.app/Base.lproj/
                    Runner.app/Base.lproj/LaunchScreen.storyboardc/
                    Runner.app/Base.lproj/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
                    Runner.app/Base.lproj/LaunchScreen.storyboardc/Info.plist
                    Runner.app/Base.lproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
                    Runner.app/Base.lproj/Main.storyboardc/
                    Runner.app/Base.lproj/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib
                    Runner.app/Base.lproj/Main.storyboardc/Info.plist
                    Runner.app/Base.lproj/Main.storyboardc/UIViewController-BYZ-38-t0r.nib
                    Runner.app/Frameworks/
                    Runner.app/Frameworks/App.framework/
                    Runner.app/Frameworks/App.framework/App
                    Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources
                    Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json
                    Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json
                    Runner.app/Frameworks/App.framework/flutter_assets/NOTICES.Z
                    Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
                    Runner.app/_CodeSignature/CodeResources

                    sent 35368670 bytes  received 408 bytes  23579385.33 bytes/sec
                    total size is 101920179  speedup is 2.88
[   +6 ms] executing: xcrun simctl install D5A130FB-A402-4C16-8F33-7806BCE32682
/Users/tahatesser/StudioProjects/master_flutter/build/ios/iphonesimulator/Runner.app
[ +717 ms] executing: /usr/bin/plutil -convert json -o -
/Users/tahatesser/StudioProjects/master_flutter/build/ios/iphonesimulator/Runner.app/Info.plist
[  +12 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Users/tahatesser/StudioProjects/master_flutter/build/ios/iphonesimulator/Runner.app/Info.plist
[   +1 ms]
{"CFBundleName":"master_flutter","DTXcode":"1250","DTSDKName":"iphonesimulator14.5","UILaunchStoryboardName":"LaunchScreen","
CFBundleIcons~ipad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60",
"AppIcon76x76","AppIcon83.5x83.5"],"CFBundleIconName":"AppIcon"}},"DTSDKBuild":"18E182","CFBundleDevelopmentRegion":"en","CFB
undleVersion":"1","BuildMachineOSBuild":"20E241","DTPlatformName":"iphonesimulator","CFBundlePackageType":"APPL","UIMainStory
boardFile":"Main","CFBundleSupportedPlatforms":["iPhoneSimulator"],"CFBundleShortVersionString":"1.0.0","CFBundleInfoDictiona
ryVersion":"6.0","CFBundleExecutable":"Runner","DTCompiler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrienta
tions~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft
","UIInterfaceOrientationLandscapeRight"],"MinimumOSVersion":"9.0","CFBundleIdentifier":"com.nevercode.triage","UIDeviceFamil
y":[1,2],"DTPlatformVersion":"14.5","CFBundleSignature":"????","CFBundleIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["
AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"12E262","LSRequire
sIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","U
IInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"NSBonjourServices":["_dartobservatory
._tcp"],"DTPlatformBuild":"18E182","NSLocalNetworkUsageDescription":"Allow Flutter tools on your computer to connect and
debug your application. This prompt will not appear on release builds."}
[   +5 ms] executing: xcrun simctl launch D5A130FB-A402-4C16-8F33-7806BCE32682 com.nevercode.triage --enable-dart-profiling
--enable-checked-mode --verify-entry-points --observatory-port=0
[ +307 ms] com.nevercode.triage: 35206
[        ] Waiting for observatory port to be available...
[ +537 ms] Observatory URL on device: http://127.0.0.1:64222/aGCMUubKHP8=/
[  +12 ms] Caching compiled dill
[ +216 ms] Connecting to service protocol: http://127.0.0.1:64222/aGCMUubKHP8=/
[ +221 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:64222/aGCMUubKHP8=/.
[ +117 ms] DDS is listening at http://127.0.0.1:64227/q3qE5iElKc8=/.
[  +92 ms] Successfully connected to service protocol: http://127.0.0.1:64222/aGCMUubKHP8=/
[  +27 ms] DevFS: Creating new filesystem on the device (null)
[  +22 ms] DevFS: Created new filesystem on the device
(file:///Users/tahatesser/Library/Developer/CoreSimulator/Devices/D5A130FB-A402-4C16-8F33-7806BCE32682/data/Containers/Data/A
pplication/E460CE6C-503D-41E4-9B1A-4DDD619A7CF0/tmp/master_flutterjBXV4r/master_flutter/)
[   +3 ms] Updating assets
[ +111 ms] Syncing files to device iPhone 12...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +5 ms] <- recompile package:master_flutter/main.dart 52c91741-6f4b-42b5-b203-f924a0ea3387
[        ] <- 52c91741-6f4b-42b5-b203-f924a0ea3387
[ +146 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device iPhone 12... (completed in 154ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +9 ms] Connected to _flutterView/0x7fba7801ae20.
[   +5 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +1 ms] An Observatory debugger and profiler on iPhone 12 is available at: http://127.0.0.1:64227/q3qE5iElKc8=/
[ +771 ms] DevTools activation throttled until 2021-05-18 04:24:14.657303.
[ +523 ms] The Flutter DevTools debugger and profiler on iPhone 12 is available at:
                    http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A64227%2Fq3qE5iElKc8%3D%2F
[+5001 ms] flutter: 183.66665649414062,455.0
[  +82 ms] 
           ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
           The following NoSuchMethodError was thrown while handling a gesture:
           The method 'drawPoints' was called on null.
           Receiver: null
           Tried calling: drawPoints(Instance of 'PointMode', Instance(length:1) of '_GrowableList', Instance
           of 'Paint')
           
           When the exception was thrown, this was the stack:
           #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
           #1      MyPainterDetails.paint (package:master_flutter/main.dart:56:12)
           #2      _MyHomePageState.build.<anonymous closure> (package:master_flutter/main.dart:39:39)
           #3      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:445:55)
           #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
           #5      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:445:7)
           #6      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:298:9)
           #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
           #8      PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:139:9)
           #9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
           #10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
           #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
           #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
           #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
           #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
           #15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
           #16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
           #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
           #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
           #22     _invoke1 (dart:ui/hooks.dart:182:10)
           #23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
           #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
           (elided 3 frames from dart:async)
           
           Handler: "onUpdate"
           Recognizer:
             PanGestureRecognizer#e95bc
           ════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>


Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.6
    • iPhone 12 (mobile)     • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.240, on macOS 11.3.1 20E241
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.240 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e364e30c90 (11 hours ago), 2021-05-16 19:40:00 -0700
    • Engine revision 193be59942
    • Dart version 2.14.0 (build
      2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.6
    • iPhone 12 (mobile)     • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```
		
</details>

**Comment by goderbauer** [comment]
In both of these examples `crashCanvas` is never initialized, so it will be null. Also, you cannot just call the paint method of a CustomPainter. A CustomPainter is usually used as an argument to a CustomPaint widget, see https://master-api.flutter.dev/flutter/widgets/CustomPaint-class.html.

**Comment by Marvin10193** [comment]
I know this is not the place to ask for help with personal code,
but even if the Canvas would be correctly initialized, then still currently there does not exist a smart/easy way to allow drawing inside another CustomPaint object using a gestureDetector as we cannot simply call the paint method of a CustomPainter as you explained, correct?
