### ISSUE TITLE
[tool_crash] ClientException

### ISSUE THREAD

**Issue by zneti-sourour** [flutter/flutter#82699]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=4200b257b27f1499 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ClientException
```
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:50:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:45:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:272:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:441:16)
#5      _rootRunBinary (dart:async/zone.dart:1378:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#12     _addErrorWithReplacement (dart:async/stream_pipe.dart:176:8)
#13     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:277:11)
#14     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#15     _rootRunBinary (dart:async/zone.dart:1378:47)
#16     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#17     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#18     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#19     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#20     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#21     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#22     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#23     _StreamController.addError (dart:async/stream_controller.dart:569:5)
#24     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1163:22)
```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [version 10.0.19042.985], locale fr-FR)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (4 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.53.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • SM G532F (mobile) • 4200b257b27f1499 • android-arm    • Android 6.0.1 (API 23)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 90.0.818.62

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6
### Plugins
connectivity-3.0.3
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
flutter_plugin_android_lifecycle-2.0.1
image_cropper-1.4.0
image_picker-0.7.4
image_picker_for_web-2.0.0
libphonenumber-2.0.0
libphonenumber_plugin-0.2.3
libphonenumber_web-0.2.0+1
package_info_plus-1.0.1
package_info_plus_macos-1.1.1
package_info_plus_web-1.0.1
qr_code_scanner-0.4.0
url_launcher-6.0.3
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0

**Comment by darshankawar** [comment]
@zneti-sourour 
You seem to have filed this issue before also, https://github.com/flutter/flutter/issues/81999, for which our response was to try and switch to latest master and see if you still get same issue or not, because this issue has been fixed already, https://github.com/flutter/flutter/issues/81999#issuecomment-834136133

`flutter channel master`
`flutter upgrade`
`flutter --no-color run --machine --track-widget-creation --device-id=4200b257b27f1499 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart`

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
