### ISSUE TITLE
Flutter Plugin Error in Android Studio with git checkout to commit Sha1

### ISSUE THREAD

**Issue by Sardorbekcyber** [flutter/flutter#82691]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

I have opened test branch and checked out to it with commit Sha1 in android/kotlin project but git error from flutter plugin

## Version information

Android Studio `4.2` • Flutter plugin `io.flutter 56.0.2` • Dart plugin `202.8488`

No Flutter sdk configured.

## Exception

null

```
com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file://D:/MobilKassa/mr5lib_v1.2; original:273; found:-; File.exists()=false
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.handleInvalidDirectory(VirtualDirectoryImpl.java:191)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:112)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:78)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:478)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:45)
	at io.flutter.bazel.Workspace.findContainingWorkspaceFile(Workspace.java:362)
	at io.flutter.bazel.Workspace.lambda$findWorkspaceFile$0(Workspace.java:340)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:857)
	at io.flutter.bazel.Workspace.findWorkspaceFile(Workspace.java:353)
	at io.flutter.bazel.Workspace.loadUncached(Workspace.java:252)
	at io.flutter.bazel.WorkspaceCache.refresh(WorkspaceCache.java:132)
	at io.flutter.bazel.WorkspaceCache.lambda$scheduleRefresh$1(WorkspaceCache.java:76)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:808)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by darshankawar** [comment]
@Sardorbekcyber 
This seems to be an issue with the Flutter intellij plugin for AS for which you may need to report this in dedicated repo: https://github.com/flutter/flutter-intellij/issues/new.

Closing from here.
