### ISSUE TITLE
Android build fails with `FileSystemException: Directory listing failed` exception

### ISSUE THREAD

**Issue by flipswitchingmonkey** [flutter/flutter#82697]
#### Issue
Android build `flutter build apk --debug --verbose` fails with `FileSystemException: Directory listing failed` exception, apparently caused by some sort of looping directory appending. No symlinks are being used for assets or inside the project (at least not created by me)

#### Version
Flutter 2.2.0-10.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 06e2fd6357 (9 days ago) • 2021-05-08 11:28:22 -0700
Engine • revision a123e75c60
Tools • Dart 2.13.0 (build 2.13.0-211.14.beta)

Tried to downgrade to previous beta version, no difference.

<details>
  <summary>Doctor</summary>

```
[✓] Flutter (Channel beta, 2.2.0-10.2.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-DE)
    • Flutter version 2.2.0-10.2.pre at /Applications/flutter
    • Framework revision b5017bf8de (3 weeks ago), 2021-04-28 17:09:53 -0700
    • Engine revision 91ed51e05c
    • Dart version 2.13.0 (build 2.13.0-211.13.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/michael/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/michael/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/michael/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```
</details>

<details>
  <summary>Error Log</summary>

```
  [ +102 ms] [  +17 ms] Target debug_android_application failed: FileSystemException: Directory listing failed, path =
'/Users/michael/Dev/de.xxx.xxx.xxx.xxx/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/flutter/profile/flutter_assets/android/app/build/intermediates/flutter/debug/flutter_as
sets/android/app/build/intermediates/flutter/release/flutter_assets/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/
intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/release/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/flutter_assets/android/app/build/intermediates/merged_assets/debug/out/' (OS Error: File name too
long, errno = 63)
[   +8 ms]            #0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:37:68)
[        ]            #1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
[        ]            #2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
[        ]            #3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
[        ]            #4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:902:78)
[        ]            #5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:738:37)
[        ]            #6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:643:9)
[        ]            #7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:229:53)
[        ]            <asynchronous suspension>
[        ]            #8      copyAssets (package:flutter_tools/src/build_system/targets/assets.dart:56:26)
[        ]            <asynchronous suspension>
[        ]            #9      AndroidAssetBundle.build (package:flutter_tools/src/build_system/targets/android.dart:65:34)
[        ]            <asynchronous suspension>
[        ]            #10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
[        ]            <asynchronous suspension>
[        ]            #12     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #15     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #19     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #21     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +10 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:335:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[   +1 ms] [  +24 ms] "flutter assemble" took 34,055ms.
[        ] [  +27 ms] ensureAnalyticsSent: 26ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +2 ms] exiting with code 1
```
</details>

**Comment by flipswitchingmonkey** [comment]
So after removing the android/app/build folder completelty and refreshing all packages, it appears to be working again.

It would still be good to know how these nested paths can happen

**Comment by TahaTesser** [comment]
Hi @flipswitchingmonkey 
No issues on the `beta` channel on macOS when building with `flutter build apk --debug --verbose` 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.2.0-10.3.pre, on macOS 11.3.1 20E241 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.0-10.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 06e2fd6357 (10 days ago), 2021-05-08 11:28:22 -0700
    • Engine revision a123e75c60
    • Dart version 2.13.0 (build 2.13.0-211.14.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • IN2011 (mobile)    • c9d8ee0c                             • android-arm64
      • Android 11 (API 30)
    • iPhone 12 (mobile) • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

Can you please reproduce with a new project and provide complete logs 
`flutter create myapp`
`cd myapp`
`flutter build apk --debug --verbose`

**Comment by flipswitchingmonkey** [comment]
Yeah it does not happen any more after the cleanup. This may be one of those things that only happens when all the stars align over a dung heap. I guess we can close this for now and if it happens again I'll try and take a snapshot.

**Comment by TahaTesser** [comment]
Hi @flipswitchingmonkey 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
