### ISSUE TITLE
Exception: Null check operator used on a null value when calling jumpToPage after first build

### ISSUE THREAD

**Issue by saibotma** [flutter/flutter#82787]
## Steps to Reproduce
- Have `PageView` with a `PageController`
- Register a onNextFrame callback in `initState` using the following code
```dart
void onNextFrame(FutureOr<void> Function() method) {
  WidgetsBinding.instance!.addPostFrameCallback((_) async {
    final completer = Completer<void>();
    // ignore: void_checks
    completer.complete(method());
    await completer.future;
  });
}
```
- Initialize `PageController` by calling the default constructor in `initState`
- both check that `controller.hasClients` is true and call `controller.jumpToPage` in the previously registered callback

Related issues:
- https://github.com/flutter/flutter/issues/66250

**Expected results:**
The PageView should jump to the desired index.

**Actual results:** 
```console
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:172)
#1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:380)
#2      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:207)
```
<details>
  <summary>Logs</summary>
  
```comsole
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:172)
#1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:380)
#2      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:207)

```

```

[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H1030 darwin-x64, locale en-DE)
    • Flutter version 2.0.6 at /Users/tobias/Documents/Dev/tapped/projects/appella/appella_app/.flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tobias/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2018.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 182.4323.44

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    • IntelliJ at /Users/tobias/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Tobias’s iPhone (mobile) • 8b798eed53199f1046bc52e9f41762dd0ce95403 • ios            • iOS 12.5.3
    • macOS (desktop)          • macos                                    • darwin-x64     • Mac OS X 10.15.7 19H1030 darwin-x64
    • Chrome (web)             • chrome                                   • web-javascript • Google Chrome 90.0.4430.212
    ! Error: Tobias’s iPhone is busy: Copying cache files from device. Xcode will continue when Tobias’s iPhone is finished. (code -10)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @saibotma 
When running the code sample, I don't see such an exception 

Reproduced the issue using the following minimal code sample 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:async';

/// Flutter code sample for PageView

// Here is an example of [PageView]. It creates a centered [Text] in each of the three pages
// which scroll horizontally.

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatelessWidget(),
      ),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatefulWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  _MyStatelessWidgetState createState() => _MyStatelessWidgetState();
}

class _MyStatelessWidgetState extends State<MyStatelessWidget> {
    late PageController controller;


  @override
  void initState() {
    // TODO: implement initState
    super.initState();
     controller = PageController(initialPage: 0);
    onNextFrame(() {

      controller.jumpToPage(2);
    });
  }

  void onNextFrame(FutureOr<void> Function() method) {
    WidgetsBinding.instance!.addPostFrameCallback((_) async {
      final completer = Completer<void>();
      // ignore: void_checks
      completer.complete(method());
      await completer.future;
    });
  }

  @override
  Widget build(BuildContext context) {
    return PageView(
      /// [PageView.scrollDirection] defaults to [Axis.horizontal].
      /// Use [Axis.vertical] to scroll vertically.
      scrollDirection: Axis.horizontal,
      controller: controller,
      children: const <Widget>[
        Center(
          child: Text('First Page'),
        ),
        Center(
          child: Text('Second Page'),
        ),
        Center(
          child: Text('Third Page'),
        )
      ],
    );
  }
}

``` 

</details>

Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.6
    • iPhone 12 (mobile)     • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-2.0.pre.253, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.253 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bac5a0db3b (12 hours ago), 2021-05-18 10:19:03 +0800
    • Engine revision 3cda7f5807
    • Dart version 2.14.0 (build 2.14.0-119.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[!] Android Studio
    • Android Studio at /Volumes/Extreme/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.6
    • iPhone 12 (mobile)     • D5A130FB-A402-4C16-8F33-7806BCE32682 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.
```
		
</details>

✅ : Reproducible ❌: Not Reproducible

Can you please try the code I provided?
Thank you

**Comment by saibotma** [comment]
Thanks for giving it a try. I also checked it out and could not reproduce the issue. I will close the issue for now until i can reproduce it again.
