### ISSUE TITLE
[video_player] In android video player doesn't play video on page view although its videoPlayerController state is playing

### ISSUE THREAD

**Issue by hyobbb** [flutter/flutter#82798]
## Steps to Reproduce

1. Test code

I am testing video player widget which subscribes the boolean stream to play and pause
The player widget is like below:

```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';


class TestPlayer extends StatefulWidget {
  final String url;
  final Stream<bool> playSignal;

  const TestPlayer({
    required this.url,
    required this.playSignal,
    Key? key,
  }) : super(key: key);

  @override
  _PlayerState createState() => _PlayerState();
}

class _PlayerState extends State<TestPlayer> with TickerProviderStateMixin {
  VideoPlayerController? videoPlayerController;
  StreamSubscription? playSubscription;

  _initialize() async {
    videoPlayerController = VideoPlayerController.network(widget.url);
    await videoPlayerController!.initialize();
    videoPlayerController?.addListener(_videoStatusListener);
    playSubscription = widget.playSignal.listen((shouldPlay) {
      if (shouldPlay) {
        videoPlayerController?.play();
      } else {
        videoPlayerController?.pause();
      }
    });

    if (this.mounted) {
      videoPlayerController?.play();
    }
  }

  _videoStatusListener() {
    if (videoPlayerController != null &&
        videoPlayerController!.value.isPlaying) {
      print('playing');
    }
  }

  @override
  void dispose() {
    videoPlayerController?.dispose();
    playSubscription?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final maxHeight = constraints.maxHeight;
        final maxWidth = constraints.maxWidth;
        return FutureBuilder(
          future: _initialize(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done &&
                videoPlayerController != null) {
              return Container(
                width: maxHeight,
                height: maxWidth,
                child: AspectRatio(
                  aspectRatio: videoPlayerController!.value.aspectRatio,
                  child: VideoPlayer(videoPlayerController!),
                ),
              );
            } else {
              return Container();
            }
          },
        );
      },
    );
  }
}

```

I implemented the TestPlayer with PageView widget.
When page is scrolling it call pause() method in PlayerController which adds false to its stream and 
when the page stops to scroll and position fixed it calls play() method which adds true to its stream.
Codes are like below:

```

class Play extends StatefulWidget {
  final videos = [
    'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
    'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4',
  ];
  
  @override
  _PlayState createState() => _PlayState();
}

class _PlayState extends State<Play> {
  PageController pageController = PageController();
  final controller = PlayerController();

  @override
  void initState() {
    pageController.addListener(() {
      if ((pageController.page! - pageController.page!.toInt()) == 0 &&
          (pageController.offset <= pageController.position.maxScrollExtent) &&
          (pageController.offset >= pageController.position.minScrollExtent)) {
        ///when page view scroll fixed
        controller.play();
      } else {
        ///on scrolling page view
        controller.pause();
      }
    });
    super.initState();
  }

  @override
  void dispose() {
    pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: PageView(
          controller: pageController,
          children: [
            TestPlayer(
              url: widget.videos.first,
              playSignal: controller.playSignal,
            ),
            TestPlayer(
              url: widget.videos.first,
              playSignal: controller.playSignal,
            ),
          ],
        ),
      ),
    );
  }
}

```
```
import 'dart:async';
import 'package:rxdart/rxdart.dart';


class PlayerController {
  final _playSignal = BehaviorSubject<bool>();
  final _volume = BehaviorSubject<double>();
  Stream<bool> get playSignal => _playSignal.stream;
  Stream<double> get volume => _volume.stream;

  void play() {
    _playSignal.add(true);
  }

  void pause() {
    _playSignal.add(false);
  }

  void setVolume(double vol) {
    if(vol<0){
      _volume.add(0.0);
    } else if(vol>1){
      _volume.add(1.0);
    } else {
      _volume.add(vol);
    }
  }

  void dispose() {
    _playSignal.close();
    _volume.close();
  }
}

```

**Expected results:** 
When I am scrolling the page view VideoPlayer initialize its VideoPlayerController but it doesn't play because it is listening to the playPause stream. Whenever the scroll stoped and page position is fixed to integer it should resume the video. 

**Actual results:** 
In iOS it behaves as expected, however in android it doesn't work when the page is changed.
I tried to call play() method using onPageChanged callback but it is the same.
In status callback of VideoPlayerController it says that it is playing as I am printing it to console.
However the VideoPlayer doesn't play the video and it remains paused.

<details>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en-KR)
    • Flutter version 2.0.6 at /Users/hyobbb/development/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hyobbb/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM G970N (mobile) • R39M30264QW • android-arm64  • Android 11 (API 30)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```

</details>

**Comment by hyobbb** [comment]
Just clone this project and run example project to reproduce the error on android device
https://github.com/hyobbb/flutter_custom_video_player.git

**Comment by darshankawar** [comment]
@hyobbb 
From your code sample, I see that you are using below 3rd party plugins:

`  flutter_cache_manager: ^3.0.2  cached_network_image: ^3.0.0  rxdart: ^0.26.0`

Does the said behavior occur if you don't use above plugins and their relevant code ?
If so, please provide updated code sample without any 3rd party plugin code.

Thanks.

**Comment by hyobbb** [comment]
@darshankawar 

The issue can be reproduced without these plugins. I replaced rxdart usage with broadcast stream controller and updated the project. The example project runs with video_player plugin and pure flutter code. I left flutter cache manager and cached network image plugins for further implementation. Should I remove them too although they are not in use for the sample code?

**Comment by darshankawar** [comment]
Thanks @hyobbb for the updated code sample. Using it, I see a similar behavior on Android (verified on S10), although the same code works on iOS.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.6 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by WSDDi** [comment]
我在ios端web页面使用video_player，视频黑屏且无法播放

**Comment by jslattery26** [comment]
I'm also having this issue. For me, in the PageView when you scroll even the tiniest bit, but stay on the same page, the video stops. even the _controller.value.isPlaying is still true. you can call _controller.play() to resolve it but its difficult to catch if the user scrolls a tiny bit and stays on the same page.

when i scroll fully to the next page and come back, the video acts normal again. This is only on android for me as well. Looking at the logs i notice this error every time it happens:

```
E/MediaCodecVideoRenderer: Failed to call Surface.setFrameRate
      java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurfaceFrameRateV30(MediaCodecVideoRenderer.java:1128)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.clearSurfaceFrameRate(MediaCodecVideoRenderer.java:1115)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onStopped(MediaCodecVideoRenderer.java:442)
        at com.google.android.exoplayer2.BaseRenderer.stop(BaseRenderer.java:164)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.ensureStopped(ExoPlayerImplInternal.java:1497)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1506)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1254)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1218)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:483)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException: Surface has already been released.
        at android.view.Surface.checkNotReleasedLocked(Surface.java:696)
        at android.view.Surface.setFrameRate(Surface.java:905)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurfaceFrameRateV30(MediaCodecVideoRenderer.java:1128) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.clearSurfaceFrameRate(MediaCodecVideoRenderer.java:1115) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onStopped(MediaCodecVideoRenderer.java:442) 
        at com.google.android.exoplayer2.BaseRenderer.stop(BaseRenderer.java:164) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.ensureStopped(ExoPlayerImplInternal.java:1497) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1506) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1254) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1218) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:483) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by fidelisakilan** [comment]
did anyone find a workaround for this issue
