### ISSUE TITLE
Works with --debug but not with --release

### ISSUE THREAD

**Issue by DavidMihola** [flutter/flutter#8281]
## Steps to Reproduce

The following code works just fine and does what I expected when I run it with the `--debug` flag:

``` 
    runApp(
      new MaterialApp(
        title: 'Test',
        home: new DefaultTabController(
          length: 2,
          child: new Scaffold(
            appBar: new AppBar(
              title: new Text("Test"),
              bottom: new TabBar(
                tabs: <Widget>[
                  new Tab(text: "Page 1"),
                  new Tab(text: "Page 2"),
                ],
              ),
            ),
            body: new TabBarView(
                children: <Widget>[
                  new Center(child: new Text("loading")),
                  new Center(child: new Text("loading")),
                ]),
          ),
        ),
      ),
    );
```

However, when I run it with the `--release` flag, the content panes of the `TabBarView` remain empty and I get the following exception:

## Logs

```
dmta@elite:~/flutter/neueApp$ flutter run --release --verbose
[  +38 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb devices -l
[        ] List of devices attached
           4653feec               device usb:2-3.4 product:OnePlus3 model:ONEPLUS_A3003 device:OnePlus3T
[  +16 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell getprop
[ +110 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec logcat -v time -t 1
[  +64 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec logcat -v time -t 1
[        ] --------- beginning of main
           02-18 22:05:57.724 E/WCNSS_FILTER( 7193): do_ioctl,tty_clock_flag=USERIAL_OP_CLK_ON,clock=USERIAL_OP_CLK_OFF
[  +16 ms] Launching lib/main.dart on ONEPLUS A3003 in release mode...
[   +1 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec logcat -v time
[   +2 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb version
[   +4 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb version
[        ] Android Debug Bridge version 1.0.36
           Revision 0e9850346394-android
[   +2 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb start-server
[   +4 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb start-server
[        ] Stopping app 'app.apk' on ONEPLUS A3003.
[   +1 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell am force-stop com.yourcompany.neueApp
[ +409 ms] Building APK
[  +17 ms] Looking for YAML at 'pubspec.yaml'
[  +52 ms] No services specified in the manifest
[        ] Building APK in release mode  (android-arm-release)...
[   +3 ms] Building build/app.flx
[ +128 ms] which zip
[   +5 ms] Encoding zip file to build/app.flx
[  +18 ms] [build/flx/] zip -q /home/dmta/flutter/neueApp/build/app.flx fonts/KabelLTStd-Book.otf fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE
[  +41 ms] Exit code 0 from: zip -q /home/dmta/flutter/neueApp/build/app.flx fonts/KabelLTStd-Book.otf fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE
[        ] Built build/app.flx.
[   +7 ms] /home/dmta/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64/gen_snapshot --assert_initializer --await_is_keyword --vm_snapshot_data=build/aot/vm_snapshot_data --isolate_snapshot_data=build/aot/isolate_snapshot_data --packages=.packages --url_mapping=dart:ui,/home/dmta/flutter/flutter/bin/cache/pkg/sky_engine/dart_ui/ui.dart --url_mapping=dart:jni,/home/dmta/flutter/flutter/bin/cache/pkg/sky_engine/dart_jni/jni.dart --url_mapping=dart:vmservice_sky,/home/dmta/flutter/flutter/bin/cache/pkg/sky_engine/sdk_ext/vmservice_io.dart --print_snapshot_sizes --embedder_entry_points_manifest=/home/dmta/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/dart_vm_entry_points.txt --embedder_entry_points_manifest=/home/dmta/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/dart_io_entries.txt --snapshot_kind=app-aot-blobs --vm_snapshot_instructions=build/aot/vm_snapshot_instr --isolate_snapshot_instructions=build/aot/isolate_snapshot_instr --embedder_entry_points_manifest=/home/dmta/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/dart_vm_entry_points_android.txt --no-sim-use-hardfp --no-use-integer-division /home/dmta/flutter/neueApp/lib/main.dart
[+7882 ms] VMIsolate(CodeSize): 78935
                   Isolate(CodeSize): 1493346
                   ReadOnlyData(CodeSize): 1514432
                   Instructions(CodeSize): 3600528
                   Total(CodeSize): 6687241
[   +2 ms] Building APK; buildMode: release.
[   +6 ms] /home/dmta/development/android-sdk-linux/build-tools/25.0.2/dx --dex --force-jumbo --output /tmp/flutter_toolsOXDGY2/classes.dex /home/dmta/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/classes.dex.jar
[ +142 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/build-tools/25.0.2/dx --dex --force-jumbo --output /tmp/flutter_toolsOXDGY2/classes.dex /home/dmta/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/classes.dex.jar
[  +42 ms] /home/dmta/development/android-sdk-linux/build-tools/25.0.2/aapt package -M android/AndroidManifest.xml -A /tmp/flutter_toolsOXDGY2/assets -I /home/dmta/development/android-sdk-linux/platforms/android-25/android.jar -F /tmp/flutter_toolsOXDGY2/app.apk.unaligned -S /home/dmta/flutter/neueApp/android/res /tmp/flutter_toolsOXDGY2/artifacts
[+3111 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/build-tools/25.0.2/aapt package -M android/AndroidManifest.xml -A /tmp/flutter_toolsOXDGY2/assets -I /home/dmta/development/android-sdk-linux/platforms/android-25/android.jar -F /tmp/flutter_toolsOXDGY2/app.apk.unaligned -S /home/dmta/flutter/neueApp/android/res /tmp/flutter_toolsOXDGY2/artifacts
[        ] Warning! Signing the APK using the debug keystore.
[        ] You will need a real keystore to distribute your application.
[        ] /usr/bin/jarsigner -keystore /home/dmta/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/chromium-debug.keystore -storepass chromium -keypass chromium -digestalg SHA1 -sigalg MD5withRSA /tmp/flutter_toolsOXDGY2/app.apk.unaligned chromiumdebugkey
[+2107 ms] Exit code 0 from: /usr/bin/jarsigner -keystore /home/dmta/flutter/flutter/bin/cache/artifacts/engine/android-arm-release/chromium-debug.keystore -storepass chromium -keypass chromium -digestalg SHA1 -sigalg MD5withRSA /tmp/flutter_toolsOXDGY2/app.apk.unaligned chromiumdebugkey
[        ] jar signed.
           
           Warning: 
           No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2112-09-11) or after any future revocation date.
[        ] /home/dmta/development/android-sdk-linux/build-tools/25.0.2/zipalign -f 4 /tmp/flutter_toolsOXDGY2/app.apk.unaligned build/app.apk
[  +15 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/build-tools/25.0.2/zipalign -f 4 /tmp/flutter_toolsOXDGY2/app.apk.unaligned build/app.apk
[        ] calculateSha: build/app.apk
[ +161 ms] Built build/app.apk (8.0MB).
[   +2 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell pm list packages com.yourcompany.neueApp
[ +365 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell pm list packages com.yourcompany.neueApp
[        ] package:com.yourcompany.neueApp
[   +3 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell cat /data/local/tmp/sky.com.yourcompany.neueApp.sha1
[  +22 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell cat /data/local/tmp/sky.com.yourcompany.neueApp.sha1
[        ] cc20876d4fab4172a27615bcd397111b574b533d
[        ] Installing APK.
[        ] /home/dmta/development/android-sdk-linux/platform-tools/adb version
[   +6 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb version
[        ] Android Debug Bridge version 1.0.36
           Revision 0e9850346394-android
[        ] /home/dmta/development/android-sdk-linux/platform-tools/adb start-server
[   +5 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb start-server
[        ] Installing build/app.apk...
[        ] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec install -r build/app.apk
[+3753 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec install -r build/app.apk
[   +3 ms] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell echo -n b0033b63dc0ceccd0e91f9c9366a766a722d8c47 > /data/local/tmp/sky.com.yourcompany.neueApp.sha1
[  +30 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell echo -n b0033b63dc0ceccd0e91f9c9366a766a722d8c47 > /data/local/tmp/sky.com.yourcompany.neueApp.sha1
[        ] ONEPLUS A3003 startApp
[        ] /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true com.yourcompany.neueApp/io.flutter.app.FlutterActivity
[ +443 ms] Exit code 0 from: /home/dmta/development/android-sdk-linux/platform-tools/adb -s 4653feec shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true com.yourcompany.neueApp/io.flutter.app.FlutterActivity
[        ] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.yourcompany.neueApp/io.flutter.app.FlutterActivity (has extras) }
[        ] Application running.
[   +1 ms] To repeat this help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
[ +286 ms] I/flutter (18161): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[   +2 ms] I/flutter (18161): The following UnsupportedError was thrown during performLayout():
[        ] I/flutter (18161): Unsupported operation: Result of truncating division is Infinity or NaN
[        ] I/flutter (18161): 
[        ] I/flutter (18161): When the exception was thrown, this was the stack:
[        ] I/flutter (18161): #0      _Double._trunc_div (dart:core-patch/double.dart:33)
[        ] I/flutter (18161): #1      _Double.~/ (dart:core-patch/double.dart:31)
[        ] I/flutter (18161): #2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:40)
[        ] I/flutter (18161): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #4      RenderViewportBase.layoutOneSide (package:flutter/src/rendering/sliver.dart:1222)
[        ] I/flutter (18161): #5      RenderViewport._attemptLayout (package:flutter/src/rendering/sliver.dart:1711)
[        ] I/flutter (18161): #6      RenderViewport.performLayout (package:flutter/src/rendering/sliver.dart:1640)
[        ] I/flutter (18161): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #8      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #10     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #12     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #14     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #16     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #18     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #20     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124)
[        ] I/flutter (18161): #21     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:163)
[        ] I/flutter (18161): #22     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194)
[        ] I/flutter (18161): #23     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338)
[        ] I/flutter (18161): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #33     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #35     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #37     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #38     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2352)
[        ] I/flutter (18161): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #40     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #42     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:354)
[        ] I/flutter (18161): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #44     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #46     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #48     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #50     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[        ] I/flutter (18161): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[        ] I/flutter (18161): #52     RenderView.performLayout (package:flutter/src/rendering/view.dart:114)
[        ] I/flutter (18161): #53     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1618)
[        ] I/flutter (18161): #54     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953)
[  +27 ms] I/flutter (18161): #55     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:225)
[        ] I/flutter (18161): #56     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:333)
[        ] I/flutter (18161): #57     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170)
[        ] I/flutter (18161): #58     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676)
[        ] I/flutter (18161): #59     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611)
[        ] I/flutter (18161): #60     runApp (package:flutter/src/widgets/binding.dart:405)
[        ] I/flutter (18161): #61     main (file:///home/dmta/flutter/neueApp/lib/main.dart:18)
[        ] I/flutter (18161): #62     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
[        ] I/flutter (18161): #63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[        ] I/flutter (18161): 
[        ] I/flutter (18161): The following RenderObject was being processed when the exception was fired:
[        ] I/flutter (18161):   RenderSliverFill#997594199 relayoutBoundary=up1 NEEDS-LAYOUT
[        ] I/flutter (18161):   parentData: paintOffset=Offset(0.0, 0.0)
[        ] I/flutter (18161):   constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
[        ] I/flutter (18161):   scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 0.0viewportMainAxisExtent: 0.0)
[        ] I/flutter (18161):   geometry: null
[        ] I/flutter (18161):   no children current live
[        ] I/flutter (18161): This RenderObject has no descendants.
[        ] I/flutter (18161): 
[        ] I/flutter (18161): ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] I/flutter (18161): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
[        ] I/flutter (18161): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
[   +9 ms] I/flutter (18161): Another exception was thrown: Unsupported operation: Result of truncating division is Infinity or NaN
[        ] I/flutter (18161): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
[        ] I/flutter (18161): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.

```

```
dmta@elite:~/flutter/neueApp$ flutter analyze
Analyzing lib/main.dart...
[hint] Dead code. (lib/main.dart, line 42, col 10)
[hint] Dead code. (lib/main.dart, line 11, col 14)
[hint] Dead code. (lib/main.dart, line 150, col 16)
[hint] The method '_handleCartChanged' isn't used. (lib/main.dart, line 682, col 8)
[hint] Dead code. (lib/main.dart, line 424, col 5)
[hint] Dead code. (lib/main.dart, line 471, col 12)
(Ran in 7.7s)
```

Nothing of the output of `flutter analyze` is related to the code used in this example.

## Flutter Doctor

```
dmta@elite:~/flutter/neueApp$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/dmta/flutter/flutter
    • Framework revision 257be181fd (16 hours ago), 2017-02-17 21:38:20
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /home/dmta/development/android-sdk-linux
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /home/dmta/development/android-sdk-linux
    • Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[-] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] IntelliJ IDEA Community Edition (version Flutter)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.10

[✓] Connected devices
    • ONEPLUS A3003 • 4653feec • android-arm • Android 7.0 (API 24)

```
> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by abarth** [comment]
Looks like a divide by zero because in release we get to layout before we know hte size of the viewport (and so we assume its zero).  Thanks!

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/8282

**Comment by DavidMihola** [comment]
Thanks for fixing that so quickly! But I am afraid that's all that was to that...

I checked out the most recent commit on `master`:

```
dmta@elite:~/flutter/flutter$ git log | head
commit 64bae978f1886a02d10bd36c3022dfabe947201a
Author: Adam Barth <github@adambarth.com>
Date:   Sat Feb 18 21:00:27 2017 -0800

    Add some dartdocs for slivers (#8284)

commit a8e847aba9b64e8d58e4ea0c5ade9ee1dd4c356b
Author: Adam Barth <github@adambarth.com>
Date:   Sat Feb 18 13:38:56 2017 -0800
```

I added some logging for debugging:

```
dmta@elite:~/flutter/flutter$ git diff packages/
diff --git a/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart b/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart
index 7eda952..9f9f9f2 100644
--- a/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart
+++ b/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart
@@ -37,9 +37,13 @@ abstract class RenderSliverFixedExtentBoxAdaptor extends RenderSliverMultiBoxAda
       maxExtent: itemExtent,
     );
 
+    print("itemExtent: " + itemExtent.toString() + ", scrollOffset: " + scrollOffset.toString());
+
     final int firstIndex = itemExtent > 0.0 ? math.max(0, scrollOffset ~/ itemExtent) : 0;
     final int targetLastIndex = itemExtent > 0.0 ? math.max(0, (targetEndScrollOffset / itemExtent).ceil() - 1) : 0;
 
+    print("firstIndex: " + firstIndex.toString() + ", targetLastIndex: " + targetLastIndex.toString());
+
     if (firstChild != null) {
       final int oldFirstIndex = indexOf(firstChild);
       final int oldLastIndex = indexOf(lastChild);
```

And now I get this log when my app malfunctions:

```
dmta@elite:~/flutter/neueApp$ flutter run --release
Launching lib/main.dart on ONEPLUS A3003 in release mode...
Building APK in release mode  (android-arm-release)...      
Warning! Signing the APK using the debug keystore.
You will need a real keystore to distribute your application.
Installing build/app.apk...                           4.1s

To repeat this help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
I/flutter ( 4158): itemExtent: 0.0, scrollOffset: 0.0
I/flutter ( 4158): firstIndex: 0, targetLastIndex: 0
I/flutter ( 4158): itemExtent: 360.0, scrollOffset: NaN
I/flutter ( 4158): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4158): The following UnsupportedError was thrown during performLayout():
I/flutter ( 4158): Unsupported operation: Result of truncating division is Infinity or NaN
I/flutter ( 4158): 
I/flutter ( 4158): When the exception was thrown, this was the stack:
I/flutter ( 4158): #0      _Double._trunc_div (dart:core-patch/double.dart:33)
I/flutter ( 4158): #1      _Double.~/ (dart:core-patch/double.dart:31)
I/flutter ( 4158): #2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:42)
I/flutter ( 4158): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
I/flutter ( 4158): #4      RenderViewportBase.layoutOneSide (package:flutter/src/rendering/sliver.dart:1319)
I/flutter ( 4158): #5      RenderViewport._attemptLayout (package:flutter/src/rendering/sliver.dart:1808)
I/flutter ( 4158): #6      RenderViewport.performLayout (package:flutter/src/rendering/sliver.dart:1737)
I/flutter ( 4158): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
```

So, there seems to be some trouble with the `scrollOffset`, too. Of, course, the problem could possibly be in my code - I am really new to Flutter...

**Comment by DavidMihola** [comment]
Oh, since I cannot re-open this issue, should I create a new one instead?

**Comment by DavidMihola** [comment]
FWIW, checking that `scrollOffset` and `targetEndScrollOffset` are not `NaN` didn't help either...

```
    print("itemExtent: " + itemExtent.toString() + ", scrollOffset: " + scrollOffset.toString() + ", targetEndScrollOffset: " + targetEndScrollOffset.toString());

    final int firstIndex = !scrollOffset.isNaN && itemExtent > 0.0 ? math.max(0, scrollOffset ~/ itemExtent) : 0;
    final int targetLastIndex = !targetEndScrollOffset.isNaN && itemExtent > 0.0 ? math.max(0, (targetEndScrollOffset / itemExtent).ceil() - 1) : 0;

    print("firstIndex: " + firstIndex.toString() + ", targetLastIndex: " + targetLastIndex.toString());
```

It just moved the problem to another place:

```
I/flutter (10104): itemExtent: 0.0, scrollOffset: 0.0, targetEndScrollOffset: 0.0
I/flutter (10104): firstIndex: 0, targetLastIndex: 0
I/flutter (10104): itemExtent: 360.0, scrollOffset: NaN, targetEndScrollOffset: NaN
I/flutter (10104): firstIndex: 0, targetLastIndex: 0
I/flutter (10104): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10104): The following UnsupportedError was thrown during performLayout():
I/flutter (10104): Unsupported operation: Result of truncating division is Infinity or NaN
I/flutter (10104): 
I/flutter (10104): When the exception was thrown, this was the stack:
I/flutter (10104): #0      _Double._trunc_div (dart:core-patch/double.dart:33)
I/flutter (10104): #1      _Double.~/ (dart:core-patch/double.dart:31)
I/flutter (10104): #2      PageScrollPhysics._roundToPage (package:flutter/src/widgets/scroll_physics.dart:155)
I/flutter (10104): #3      PageScrollPhysics._getTargetPixels (package:flutter/src/widgets/scroll_physics.dart:165)
I/flutter (10104): #4      PageScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/scroll_physics.dart:176)
I/flutter (10104): #5      ScrollPosition.beginBallisticActivity (package:flutter/src/widgets/scroll_position.dart:475)
I/flutter (10104): #6      IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:548)
I/flutter (10104): #7      ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:343)
I/flutter (10104): #8      RenderViewport.performLayout (package:flutter/src/rendering/sliver.dart:1741)
```

**Comment by DavidMihola** [comment]
But, for now, is it safe to assume that code that runs fine in debug mode will eventually work just as well in release mode?

**Comment by eseidelGoogle** [comment]
It's best to open a new bug to keep things clear (feel free to reference this one of course).

**Comment by abarth** [comment]
> But, for now, is it safe to assume that code that runs fine in debug mode will eventually work just as well in release mode?

That is the intent, but of course there might be bugs.
