### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): No host specified in URI http://:52385/ws

### ISSUE THREAD

**Issue by ParthJadav** [flutter/flutter#82814]
## Command
```
flutter run --machine --target lib\main.dart -d 192.168.1.11:5555 --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): No host specified in URI http://:52385/ws
```
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2425:9)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2341:7)
#2      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1025:24)
#3      WebSocket.connect (dart:_http/websocket.dart:379:22)
#4      _defaultOpenChannel (package:flutter_tools/src/vmservice.dart:135:33)
#5      _connect (package:flutter_tools/src/vmservice.dart:326:50)
#6      connectToVmService (package:flutter_tools/src/vmservice.dart:304:19)
#7      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:249:27)
#8      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:232:43)
#9      _rootRunUnary (dart:async/zone.dart:1362:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
#15     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#16     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
#17     _rootRunUnary (dart:async/zone.dart:1362:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#24     _rootRun (dart:async/zone.dart:1346:47)
```
```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-GB)
    • Flutter version 2.0.6 at D:\Android_SDK\flutter_sdk\flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android_SDK\sdk\
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code, 64-bit edition (version 1.56.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • vivo 1951 (mobile) • 192.168.1.11:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome            • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)         • edge              • web-javascript • Microsoft Edge 90.0.818.49

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 63062a64432cce03315d6b5196fda7912866eb37
### Plugins
integration_test

**Comment by darshankawar** [comment]
Haven't come across similar / duplicate of this tool_crash before. So labeling it accordingly.

@ParthJadav Does it generate any crash log such as `flutter_01.log` ? If so, can you provide it ?

**Comment by ParthJadav** [comment]
PFA as you asked and my project contains only one file main.dart and I am also pasting that code below

[flutter_01.log](https://github.com/flutter/flutter/files/6508117/flutter_01.log)

import 'package:flutter/material.dart';

main.dart

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('My First App'),
          centerTitle: true,
        ),
        body: Center(
          child: Text('Hello there!'),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {  },
          child: Text('Click'),
        ),
      ),
    ),
  );
}
