### ISSUE TITLE
Crash: scrollOffset is NaN in --release mode 

### ISSUE THREAD

**Issue by DavidMihola** [flutter/flutter#8285]
## Steps to Reproduce

This is a follow-up/variation of #8281 - while the @abarth's bugfix from #8282 did fix part of the crash, there is still the problem that both `scrollOffset` and `targetEndScrollOffset` are both `NaN` at some point, also causing the calculation to crash. *As before, this all applies only to the --release mode; everything works fine in --debug mode.*

Based on the most recent commit on master...

```
dmta@elite:~/flutter/flutter$ git log | head
commit 64bae978f1886a02d10bd36c3022dfabe947201a
Author: Adam Barth <github@adambarth.com>
Date:   Sat Feb 18 21:00:27 2017 -0800

    Add some dartdocs for slivers (#8284)

commit a8e847aba9b64e8d58e4ea0c5ade9ee1dd4c356b
Author: Adam Barth <github@adambarth.com>
Date:   Sat Feb 18 13:38:56 2017 -0800
```

... I added some logging for debugging:

```
dmta@elite:~/flutter/flutter$ git diff packages/
diff --git a/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart b/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart
index 7eda952..9f9f9f2 100644
--- a/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart
+++ b/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart
@@ -37,9 +37,13 @@ abstract class RenderSliverFixedExtentBoxAdaptor extends RenderSliverMultiBoxAda
       maxExtent: itemExtent,
     );
 
+    print("itemExtent: " + itemExtent.toString() + ", scrollOffset: " + scrollOffset.toString() + ", targetEndScrollOffset: " + targetEndScrollOffset.toString());
+
     final int firstIndex = itemExtent > 0.0 ? math.max(0, scrollOffset ~/ itemExtent) : 0;
     final int targetLastIndex = itemExtent > 0.0 ? math.max(0, (targetEndScrollOffset / itemExtent).ceil() - 1) : 0;
 
+    print("firstIndex: " + firstIndex.toString() + ", targetLastIndex: " + targetLastIndex.toString());
+
     if (firstChild != null) {
       final int oldFirstIndex = indexOf(firstChild);
       final int oldLastIndex = indexOf(lastChild);
```

And now I get this log when my app malfunctions:

```
dmta@elite:~/flutter/neueApp$ flutter run --release
Launching lib/main.dart on ONEPLUS A3003 in release mode...
Building APK in release mode  (android-arm-release)...      
Warning! Signing the APK using the debug keystore.
You will need a real keystore to distribute your application.
Installing build/app.apk...                           4.1s

To repeat this help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
I/flutter ( 4158): itemExtent: 0.0, scrollOffset: 0.0
I/flutter ( 4158): firstIndex: 0, targetLastIndex: 0
I/flutter ( 4158): itemExtent: 360.0, scrollOffset: NaN
I/flutter ( 4158): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4158): The following UnsupportedError was thrown during performLayout():
I/flutter ( 4158): Unsupported operation: Result of truncating division is Infinity or NaN
I/flutter ( 4158): 
I/flutter ( 4158): When the exception was thrown, this was the stack:
I/flutter ( 4158): #0      _Double._trunc_div (dart:core-patch/double.dart:33)
I/flutter ( 4158): #1      _Double.~/ (dart:core-patch/double.dart:31)
I/flutter ( 4158): #2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:42)
I/flutter ( 4158): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
I/flutter ( 4158): #4      RenderViewportBase.layoutOneSide (package:flutter/src/rendering/sliver.dart:1319)
I/flutter ( 4158): #5      RenderViewport._attemptLayout (package:flutter/src/rendering/sliver.dart:1808)
I/flutter ( 4158): #6      RenderViewport.performLayout (package:flutter/src/rendering/sliver.dart:1737)
I/flutter ( 4158): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
```

Checking that `scrollOffset` and `targetEndScrollOffset` are not `NaN` didn't help either...

```
    print("itemExtent: " + itemExtent.toString() + ", scrollOffset: " + scrollOffset.toString() + ", targetEndScrollOffset: " + targetEndScrollOffset.toString());

    final int firstIndex = !scrollOffset.isNaN && itemExtent > 0.0 ? math.max(0, scrollOffset ~/ itemExtent) : 0;
    final int targetLastIndex = !targetEndScrollOffset.isNaN && itemExtent > 0.0 ? math.max(0, (targetEndScrollOffset / itemExtent).ceil() - 1) : 0;

    print("firstIndex: " + firstIndex.toString() + ", targetLastIndex: " + targetLastIndex.toString());
```

It just moved the problem to another place:

```
I/flutter (10104): itemExtent: 0.0, scrollOffset: 0.0, targetEndScrollOffset: 0.0
I/flutter (10104): firstIndex: 0, targetLastIndex: 0
I/flutter (10104): itemExtent: 360.0, scrollOffset: NaN, targetEndScrollOffset: NaN
I/flutter (10104): firstIndex: 0, targetLastIndex: 0
I/flutter (10104): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10104): The following UnsupportedError was thrown during performLayout():
I/flutter (10104): Unsupported operation: Result of truncating division is Infinity or NaN
I/flutter (10104): 
I/flutter (10104): When the exception was thrown, this was the stack:
I/flutter (10104): #0      _Double._trunc_div (dart:core-patch/double.dart:33)
I/flutter (10104): #1      _Double.~/ (dart:core-patch/double.dart:31)
I/flutter (10104): #2      PageScrollPhysics._roundToPage (package:flutter/src/widgets/scroll_physics.dart:155)
I/flutter (10104): #3      PageScrollPhysics._getTargetPixels (package:flutter/src/widgets/scroll_physics.dart:165)
I/flutter (10104): #4      PageScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/scroll_physics.dart:176)
I/flutter (10104): #5      ScrollPosition.beginBallisticActivity (package:flutter/src/widgets/scroll_position.dart:475)
I/flutter (10104): #6      IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:548)
I/flutter (10104): #7      ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:343)
I/flutter (10104): #8      RenderViewport.performLayout (package:flutter/src/rendering/sliver.dart:1741)
```

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/8286

Sorry for missing this before.

**Comment by DavidMihola** [comment]
Great - with this patch it all seems to work! Thanks a lot for fixing it so quickly! I am starting to get really excited about Flutter but until it can (1) play videos and (2) display HTML it will be tough sell at work, so I'll have to play with it on the weekends...
