### ISSUE TITLE
WIP | MacOS & Linux Dev Environments Breaking Each Others Build | Plugin Folder Missing [Linux]

### ISSUE THREAD

**Issue by MateusAmin** [flutter/flutter#82855]
This is going to take a second to sort out. But every time I (linux env) merge something from my colleagues mac based dev environment my build does not work. Could be their git setup I suppose.

What ends up happening on my end is all the plugins break. With no plugin folders existing.

Workaround: reinitialize project on share and copy over code.

## Steps to Reproduce

WIP; will update ASAP.

## Logs

<details>
<summary>Logs</summary>

```
gui > flutter run -d linux --verbose
[  +61 ms] executing: uname -m
[  +30 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +7 ms] executing: [/home/mea/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +13 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5c09eecd0d5ea428d163de12d12d6bd9a7a8b16c
[   +1 ms] executing: [/home/mea/snap/flutter/common/flutter/] git tag --points-at
5c09eecd0d5ea428d163de12d12d6bd9a7a8b16c
[  +12 ms] Exit code 0 from: git tag --points-at 5c09eecd0d5ea428d163de12d12d6bd9a7a8b16c
[   +1 ms] executing: [/home/mea/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags
5c09eecd0d5ea428d163de12d12d6bd9a7a8b16c
[  +35 ms] Exit code 0 from: git describe --match *.*.* --long --tags 5c09eecd0d5ea428d163de12d12d6bd9a7a8b16c
[        ] 2.3.0-1.0.pre-264-g5c09eecd0d
[   +5 ms] executing: [/home/mea/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/mea/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +92 ms] executing: [/home/mea/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +66 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] executing: /home/mea/Android/Sdk/platform-tools/adb devices -l
[  +32 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +118 ms] executing: /home/mea/Android/Sdk/platform-tools/adb devices -l
[  +18 ms] Skipping pub get: version match.
[ +140 ms] Initializing file store
[   +9 ms] Skipping target: gen_localizations
[   +8 ms] Skipping target: gen_dart_plugin_registrant
[   +3 ms] Skipping target: _composite
[   +3 ms] complete
[  +12 ms] Launching lib/main.dart on Linux in debug mode...
[   +8 ms] /home/mea/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/mea/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/mea/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.OBNTTC/flutter_tool.XAQYEV/app.dill --packages
/home/mea/ocol/gui/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +56 ms] Building Linux application...
[  +44 ms] <- compile package:gui/main.dart
[   +3 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/mea/ocol/gui/linux
[  +14 ms] List of devices attached
[   +3 ms] List of devices attached
[ +168 ms] CMake Error at flutter/generated_plugins.cmake:13 (add_subdirectory):
[   +3 ms]   add_subdirectory given source
[   +1 ms]   "flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux" which is not
[        ]   an existing directory.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:69 (include)
[        ] CMake Error at flutter/generated_plugins.cmake:13 (add_subdirectory):
[        ]   add_subdirectory given source
[        ]   "flutter/ephemeral/.plugin_symlinks/file_selector_linux/linux" which is not
[        ]   an existing directory.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:69 (include)
[   +1 ms] -- Configuring incomplete, errors occurred!
[   +1 ms] See also "/home/mea/ocol/gui/build/linux/x64/debug/CMakeFiles/CMakeOutput.log".
[  +19 ms] Building Linux application... (completed in 251ms)
[+9922 ms] Exception: Unable to generate build files
[        ] "flutter run" took 10,731ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:664:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1090:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +51 ms] ensureAnalyticsSent: 48ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

```
gui > flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-2.0.pre.264, on Ubuntu 20.04.2 LTS 5.8.0-53-generic, locale en_US.UTF-8)
    • Flutter version 2.3.0-2.0.pre.264 at /home/mea/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c09eecd0d (43 minutes ago), 2021-05-18 13:19:03 -0700
    • Engine revision 3cda7f5807
    • Dart version 2.14.0 (build 2.14.0-119.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/mea/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java
      binary in your PATH. You can download the JDK from
      https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.2 LTS 5.8.0-53-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 2 categories.
```

</details>

**Comment by jonahwilliams** [comment]
`flutter/ephemeral/` should be gitignored. In fact, it is in the gitignore for all the projects we generate

**Comment by stuartmorgan** [comment]
Can you link to a repository and commit that reproduce this?

**Comment by MateusAmin** [comment]
> `flutter/ephemeral/` should be gitignored. In fact, it is in the gitignore for all the projects we generate

Yes, it is. I recall, I ran a flutter clean for another issue upon merge so that is what probably did in those folders.

**Comment by MateusAmin** [comment]
Working on replicating the bug. Will ping you when I get something actionable going.

**Comment by TahaTesser** [comment]
Hi @MateusAmin 
Please provide the reproducible project whenever it is ready
Thank you

**Comment by MateusAmin** [comment]
I could not reproduce. And it works on my other linux machine so I am going to close for now.

Will reopen if I can get something concrete.
