### ISSUE TITLE
Flutter CLI doesn't work

### ISSUE THREAD

**Issue by black-purple** [flutter/flutter#82868]
Whenever I run a flutter command I run into this issue. First time noticed when I tried to create a new project.
My machine is a Manjaro LINUX.

```Unhandled exception:
Null check operator used on a null value
#0      getExecutablePath (package:process/src/interface/common.dart:86:46)
#1      _getExecutable (package:process/src/interface/local_process_manager.dart:142:10)
#2      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:106:32)
#3      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:685:24)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#5      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:684:12)
#6      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:373:51)
#7      _PosixUtils.hostPlatform (package:flutter_tools/src/base/os.dart:266:25)
#8      new BuildLinuxCommand (package:flutter_tools/src/commands/build_linux.dart:29:32)
#9      new BuildCommand (package:flutter_tools/src/commands/build.dart:39:19)
#10     generateCommands (package:flutter_tools/executable.dart:148:3)
#11     main.<anonymous closure> (package:flutter_tools/executable.dart:93:11)
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:48:13)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension
```

flutter doctor output also gives me the same output. 

```[black@manjaro ~]$ flutter doctor
Unhandled exception:
Null check operator used on a null value
#0      getExecutablePath (package:process/src/interface/common.dart:86:46)
#1      _getExecutable (package:process/src/interface/local_process_manager.dart:142:10)
#2      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:106:32)
#3      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:685:24)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#5      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:684:12)
#6      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:373:51)
#7      _PosixUtils.hostPlatform (package:flutter_tools/src/base/os.dart:266:25)
#8      new BuildLinuxCommand (package:flutter_tools/src/commands/build_linux.dart:29:32)
#9      new BuildCommand (package:flutter_tools/src/commands/build.dart:39:19)
#10     generateCommands (package:flutter_tools/executable.dart:148:3)
#11     main.<anonymous closure> (package:flutter_tools/executable.dart:93:11)
#12     run.<anonymous closure> (package:flutter_tools/runner.dart:48:13)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

I tried removing the flutter folder and downloading it again but I face the same issue.

**Comment by jonahwilliams** [comment]
This is failing here: https://github.com/google/process.dart/blob/0c9aeac86dcc4e3a6cf760b76fed507107e244d5/lib/src/interface/common.dart#L86

Looks like you don't have a PATH variable at all?

**Comment by black-purple** [comment]
> This is failing here: https://github.com/google/process.dart/blob/0c9aeac86dcc4e3a6cf760b76fed507107e244d5/lib/src/interface/common.dart#L86
> 
> Looks like you don't have a PATH variable at all?

everything works as expected in my environment and the path variable is there. But If ith's about the path variable I think I know where the problem is.

**Comment by black-purple** [comment]
Problem Solved!! 

My path Variable had several entries for flutter location due to script I'm developing. 
Thank you for the help! 
I'll close the issue.
