### ISSUE TITLE
it does not open flutter to create projects neither with android studio nor with visual studio code

### ISSUE THREAD

**Issue by ranitaram** [flutter/flutter#82880]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --template app --description A new Flutter application. --org com.example --platforms android,ios flutter_app

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\src\flutter\packages\flutter_tools\templates\template_manifest.json' (OS Error: El sistema no puede encontrar la ruta especificada.
, errno = 3)

```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#5      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:209:22)
#6      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#7      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:208:12)
#8      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:498:37)
#9      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:484:30)
#10     CreateBase.renderTemplate (package:flutter_tools/src/commands/create_base.dart:385:25)
#11     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:398:29)
#12     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:259:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
<asynchronous suspension>
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#23     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#25     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#26     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.6, on Microsoft Windows [VersiÃ³n 10.0.19042.985], locale es-MX)
    • Flutter version 2.0.6 at C:\src\flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Ramses Indalecio\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Ramses Indalecio\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.62

• No issues found!
```

**Comment by ZurMaD** [comment]
Duplicated of

**Comment by darshankawar** [comment]
@ranitaram 
Per [this](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004) comment, this issue is already fixed and available only on Master version. So you may need to switch to latest master and try the command again to see the fix.

```
flutter channel master
flutter upgrade
```

Closing this as already fixed. If you still get same exception on latest master too, write in comments and I'll reopen it.
Thanks.
