### ISSUE TITLE
NTP.now() throws UnimplementedError on flutter web #32

### ISSUE THREAD

**Issue by awaisdev5765** [flutter/flutter#82893]
got an UnimplementedError Exception when calling NTP.now() resp. getNtpOffset() on Flutter web.
Does somebody know why this happens?

[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.804], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.1)
[√] Connected device (2 available)

Exception has occurred.
"Error: UnimplementedError
at Object.throw_ [as throw] (http://localhost:52592/dart_sdk.js:5334:11)
at bind (http://localhost:52592/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:3434:21)
at bind.next ()
at runBody (http://localhost:52592/dart_sdk.js:39052:34)
at Object._async [as async] (http://localhost:52592/dart_sdk.js:39083:7)
at Function.bind (http://localhost:52592/packages/universal_io/src/io_impl_js/sync_socket.dart.lib.js:3431:20)
at getNtpOffset (http://localhost:52592/packages/ntp/ntp.dart.lib.js:128:63)
at getNtpOffset.next ()
at http://localhost:52592/dart_sdk.js:39032:33
at _RootZone.runUnary (http://localhost:52592/dart_sdk.js:38889:58)
at _FutureListener.thenAwait.handleValue (http://localhost:52592/dart_sdk.js:33875:29)
at handleValueCallback (http://localhost:52592/dart_sdk.js:34435:49)
at Function._propagateToListeners (http://localhost:52592/dart_sdk.js:34473:17)
at _Future.new.[_completeWithValue] (http://localhost:52592/dart_sdk.js:34315:23)
at async._AsyncCallbackEntry.new.callback (http://localhost:52592/dart_sdk.js:34338:35)
at Object._microtaskLoop (http://localhost:52592/dart_sdk.js:39176:13)
at _startMicrotaskLoop (http://localhost:52592/dart_sdk.js:39182:13)
at http://localhost:52592/dart_sdk.js:34689:9"

**Comment by balvinderz** [comment]
ntp is not supported for flutter web . you can check which platforms are supported by the plugin by going to this page
https://pub.dev/packages/ntp

**Comment by awaisdev5765** [comment]
so any sugesstion

**Comment by balvinderz** [comment]
raise a issue there.

**Comment by awaisdev5765** [comment]
already done

**Comment by balvinderz** [comment]
you can close this issue then. issues here are only related to flutter and  flutter plugins. not for third party plugins.
