### ISSUE TITLE
Asset only deferred components cause startup crash

### ISSUE THREAD

**Issue by NicolaVerbeeck** [flutter/flutter#82903]
## Steps to Reproduce

1. Create an application with deferred components containing ONLY assets. (Aka: no **loadingUnitMapping** is generated/required). Using the recommended `FlutterPlayStoreSplitApplication`
2. See that the prebuild validator notifies that `<meta-data android:name="io.flutter.embedding.engine.deferredcomponents.DeferredComponentManager.loadingUnitMapping" android:value=""/>` is required in the base module manifest
3. Ensure proguard does not obfuscate the `DeferredComponentManager` (or it won't resolve the correct key to load from the manifest)
4. Run the app

**Expected results:** App runs normally

**Actual results:** Crash during startup because the empty manifest value is being split and parsed as an integer in `PlayStoreDeferredComponentManager` which does not work. (String split returns for the empty string an array containing the empty string, not an empty array)

<details>
  <summary>Logs</summary>

```
java.lang.RuntimeException: Unable to create application io.flutter.app.FlutterPlayStoreSplitApplication: java.lang.NumberFormatException: For input string: ""
                         E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
                         E      at android.app.ActivityThread.access$1300(ActivityThread.java:219)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
                         E      at android.os.Handler.dispatchMessage(Handler.java:107)
                         E      at android.os.Looper.loop(Looper.java:214)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7356)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
                         E  Caused by: java.lang.NumberFormatException: For input string: ""
                         E      at java.lang.Integer.parseInt(Integer.java:627)
                         E      at java.lang.Integer.parseInt(Integer.java:650)
                         E      at io.flutter.embedding.engine.deferredcomponents.PlayStoreDeferredComponentManager.<init>(PlayStoreDeferredComponentManager.java:25)
                         E      at io.flutter.app.FlutterPlayStoreSplitApplication.onCreate(FlutterPlayStoreSplitApplication.java:2)
                         E      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
                         E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
```

Flutter doctor (relevant part)
```
[✓] Flutter (Channel unknown, 2.2.0, on macOS 11.3 20E232 darwin-x64, locale en-BE)
    • Flutter version 2.2.0 at /Users/<redactd>/fvm/versions/2.2.0
    • Framework revision b22742018b (4 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
```

</details>

**Comment by TahaTesser** [comment]
Hi @NicolaVerbeeck 
Thanks for filing the issue and the PR. 
I'm following [doc](https://flutter.dev/docs/perf/deferred-components#:~:text=Flutter%20has%20the%20capability%20to,as%20a%20%E2%80%9Cdeferred%20component%E2%80%9D) to reproduce and your steps are a bit specific. 
Do you mind creating a sample repo to reproduce this?
Thank you

**Comment by NicolaVerbeeck** [comment]
@TahaTesser here you go: https://github.com/NicolaVerbeeck/deferred_crash_example

**Comment by TahaTesser** [comment]
Hi @NicolaVerbeeck 
Thanks so much for the sample, I can reproduce the crash

Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.0 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b22742018b (6 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-13.0.pre.87, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.3.0-13.0.pre.87 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d6a925326 (3 hours ago), 2021-05-21 01:09:02 -0400
    • Engine revision 20260fb95f
    • Dart version 2.14.0 (build 2.14.0-134.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (5 available)
    • IN2011 (mobile)         • c9d8ee0c • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.19042.985]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 90.0.4430.212
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 90.0.818.56

• No issues found!
```
		
</details>

✅ : Reproducible ❌: Not Reproducible

**Comment by NicolaVerbeeck** [comment]
@TahaTesser thanks for taking the time to triage!

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/26333 Should fix this.
