### ISSUE TITLE
flutter debug APK is different from release APK

### ISSUE THREAD

**Issue by vendz** [flutter/flutter#82914]
## Steps to Reproduce
I made a phone auth app and it was working fine in debug APK but as soon as I generated release APK it wasn't showing me the same results.

for further details my code is available here: https://github.com/vendz/phone_auth_flutter

**Expected results:** 
![alt text](https://i.imgur.com/4fwYptL.jpg)

**Actual results:** 
![alt text](https://i.imgur.com/tzy3Iy4.jpg)

<details>
  <summary>Logs</summary>

```
[ +119 ms] executing: [/Users/vanditkhushee/developer/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +117 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[   +1 ms] executing: [/Users/vanditkhushee/developer/flutter/] git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[ +231 ms] Exit code 0 from: git tag --points-at 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
[        ] 2.0.6
[  +88 ms] executing: [/Users/vanditkhushee/developer/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [/Users/vanditkhushee/developer/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +158 ms] executing: [/Users/vanditkhushee/developer/flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +19 ms] executing: sw_vers -productName
[  +96 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +63 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.1
[        ] executing: sw_vers -buildVersion
[  +56 ms] Exit code 0 from: sw_vers -buildVersion
[   +4 ms] 20C69
[  +61 ms] executing: sysctl hw.optional.arm64
[  +38 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[ +160 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +121 ms] executing: /Users/vanditkhushee/Library/Android/sdk/platform-tools/adb devices -l
[  +26 ms] executing: /usr/bin/xcode-select --print-path
[  +13 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[   +1 ms] /Library/Developer/CommandLineTools
[  +35 ms] executing: sysctl hw.optional.arm64
[  +27 ms] Exit code 1 from: sysctl hw.optional.arm64
[  +10 ms] sysctl: unknown oid 'hw.optional.arm64'
[   +2 ms] executing: xcrun xcodebuild -version
[  +44 ms] Exit code 72 from: xcrun xcodebuild -version
[   +1 ms] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[   +5 ms] Xcode not found. Run 'flutter doctor' for more information.
[  +18 ms] executing: xcrun xcodebuild -version
[  +46 ms] Exit code 72 from: xcrun xcodebuild -version
[   +1 ms] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[ +203 ms] List of devices attached
[  +15 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +34 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +157 ms] executing: xcrun xcodebuild -version
[  +20 ms] Exit code 72 from: xcrun xcodebuild -version
[   +2 ms] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[ +193 ms] Skipping pub get: version match.
[  +69 ms] Found plugin firebase_auth at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.1.4/
[  +18 ms] Found plugin firebase_auth_web at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.1.2/
[  +20 ms] Found plugin firebase_core at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.1.1/
[  +11 ms] Found plugin firebase_core_web at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.3/
[ +275 ms] Found plugin firebase_auth at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.1.4/
[   +4 ms] Found plugin firebase_auth_web at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.1.2/
[   +2 ms] Found plugin firebase_core at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.1.1/
[   +5 ms] Found plugin firebase_core_web at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.3/
[  +80 ms] Generating
/Users/vanditkhushee/Downloads/vandit/programming/Flutter/phone_authentication_flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +76 ms] executing: xcrun xcodebuild -version
[  +14 ms] Exit code 72 from: xcrun xcodebuild -version
[        ] xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
[ +242 ms] Launching lib/main.dart on Chrome in debug mode...
[ +200 ms] Updating assets
[ +165 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +3 ms] Waiting for connection from debug service on Chrome...
[  +50 ms] Found plugin firebase_auth at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.1.4/
[  +14 ms] Found plugin firebase_auth_web at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.1.2/
[   +9 ms] Found plugin firebase_core at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.1.1/
[  +27 ms] Found plugin firebase_core_web at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.3/
[ +186 ms] Found plugin firebase_auth at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.1.4/
[  +10 ms] Found plugin firebase_auth_web at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.1.2/
[   +4 ms] Found plugin firebase_core at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.1.1/
[  +27 ms] Found plugin firebase_core_web at /Users/vanditkhushee/developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.3/
[ +187 ms] <- reset
[  +17 ms] /Users/vanditkhushee/developer/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/vanditkhushee/developer/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/vanditkhushee/developer/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/lp/zkv7fht16gn2ckspj40qmnmh0000gp/T/flutter_tools.7y8pPZ/flutter_tool.KzIT97/app.dill --libraries-spec
file:///Users/vanditkhushee/developer/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/Users/vanditkhushee/Downloads/vandit/programming/Flutter/phone_authentication_flutter/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-root /var/folders/lp/zkv7fht16gn2ckspj40qmnmh0000gp/T/flutter_tools.7y8pPZ/flutter_tools.BIUsAt --filesystem-scheme
org-dartlang-app --initialize-from-dill build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///Users/vanditkhushee/developer/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +61 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+25524 ms] Waiting for connection from debug service on Chrome... (completed in 26.1s)
[        ] Synced 30.8MB.
[        ] <- accept
[        ] Caching compiled dill
[ +192 ms] Using Google Chrome 90.0.4430.212 

[+1789 ms] [CHROME]:
[   +4 ms] [CHROME]:DevTools listening on ws://127.0.0.1:62157/devtools/browser/fd16d26b-007b-4b87-b42e-2f29b385242e
[+1871 ms] DwdsInjector: Received request for entrypoint at http://localhost:62134/main_module.bootstrap.js
[  +72 ms] MetadataProvider: Loading debug metadata...
[  +93 ms] MetadataProvider: Loaded debug metadata
[  +29 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:62134/main_module.bootstrap.js
[+3364 ms] DevHandler: Debug service listening on ws://127.0.0.1:62179/0_Gy8uQU2Pg=/ws

[  +33 ms] Debug service listening on ws://127.0.0.1:62179/0_Gy8uQU2Pg=/ws
[   +2 ms] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[  +13 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[ +891 ms] Error: [core/not-initialized] Firebase has not been correctly initialized. Have you added the Firebase import scripts to your index.html file? 
                    
                    View the Web Installation documentation for more information: https://firebase.flutter.dev/docs/installation/web
                    
                        at Object.throw_ [as throw] (http://localhost:62134/dart_sdk.js:5333:11)
                        at initializeApp (http://localhost:62134/packages/firebase_core_web/firebase_core_web.dart.lib.js:106:27)
                        at initializeApp.next (<anonymous>)
                        at runBody (http://localhost:62134/dart_sdk.js:39051:34)
                        at Object._async [as async] (http://localhost:62134/dart_sdk.js:39082:7)
                        at firebase_core_web.FirebaseCoreWeb.new.initializeApp (http://localhost:62134/packages/firebase_core_web/firebase_core_web.dart.lib.js:94:20)
                        at initializeApp (http://localhost:62134/packages/firebase_core/firebase_core.dart.lib.js:114:59)
                        at initializeApp.next (<anonymous>)
                        at runBody (http://localhost:62134/dart_sdk.js:39051:34)
                        at Object._async [as async] (http://localhost:62134/dart_sdk.js:39082:7)
                        at Function.initializeApp (http://localhost:62134/packages/firebase_core/firebase_core.dart.lib.js:113:20)
                        at main$ (http://localhost:62134/packages/phone_authentication_flutter/main.dart.lib.js:160:36)
                        at main$.next (<anonymous>)
                        at runBody (http://localhost:62134/dart_sdk.js:39051:34)
                        at Object._async [as async] (http://localhost:62134/dart_sdk.js:39082:7)
                        at main$ (http://localhost:62134/packages/phone_authentication_flutter/main.dart.lib.js:158:18)
                        at main (http://localhost:62134/web_entrypoint.dart.lib.js:49:29)
                        at main.next (<anonymous>)
                        at http://localhost:62134/dart_sdk.js:39031:33
                        at _RootZone.runUnary (http://localhost:62134/dart_sdk.js:38888:58)
                        at _FutureListener.thenAwait.handleValue (http://localhost:62134/dart_sdk.js:33874:29)
                        at handleValueCallback (http://localhost:62134/dart_sdk.js:34434:49)
                        at Function._propagateToListeners (http://localhost:62134/dart_sdk.js:34472:17)
                        at _Future.new.[_completeWithValue] (http://localhost:62134/dart_sdk.js:34314:23)
                        at http://localhost:62134/dart_sdk.js:33525:46
                        at _RootZone.runUnary (http://localhost:62134/dart_sdk.js:38888:58)
                        at _FutureListener.then.handleValue (http://localhost:62134/dart_sdk.js:33874:29)
                        at handleValueCallback (http://localhost:62134/dart_sdk.js:34434:49)
                        at Function._propagateToListeners (http://localhost:62134/dart_sdk.js:34472:17)
                        at _Future.new.[_completeWithValue] (http://localhost:62134/dart_sdk.js:34314:23)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:62134/dart_sdk.js:34337:35)
                        at Object._microtaskLoop (http://localhost:62134/dart_sdk.js:39175:13)
                        at _startMicrotaskLoop (http://localhost:62134/dart_sdk.js:39181:13)
                        at http://localhost:62134/dart_sdk.js:34688:9
[+13531 ms] DevHandler: Stopped debug service on ws://127.0.0.1:62175

[+1504 ms] Application finished.
[   +3 ms] "flutter run" took 51,951ms.
[ +261 ms] ensureAnalyticsSent: 255ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[ +186 ms] Shutdown hooks complete
[        ] exiting with code 0
```

```
Analyzing phone_authentication_flutter...                               
No issues found! (ran in 5.6s)
```

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.1 20C69 darwin-x64, locale en-IN)
    • Flutter version 2.0.6 at /Users/vanditkhushee/developer/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vanditkhushee/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 2 categories.
```

</details>

**Comment by vendz** [comment]
I have also tried 

- flutter clean 
- followed the documentation here: https://flutter.dev/docs/deployment/android

**Comment by PollyGlot** [comment]
Every time when I saw a grey screen in a production app it always meant that something was or returned `null`. Check your code for null errors. Also it is better to update your Flutter to the latest stable version if you haven't done that yet.

**Comment by vendz** [comment]
but if something was returning null then why does it appear perfect in debug mode

**Comment by vendz** [comment]
alright, so I fixed it. I had to make some changes to the `container` widget and `flexible` widget., I still don't know how it was causing the problem but it's fixed.
