### ISSUE TITLE
UWP  run/build failed at master branch

### ISSUE THREAD

**Issue by zmtzawqlp** [flutter/flutter#82917]
I enable uwp config as flutter config said in master branch, and create an demo with 'flutter create xx_demo'.
```
Settings:
  enable-web: true
  enable-windows-desktop: true
  enable-windows-uwp-desktop: true

Analytics reporting is currently enabled.
```

But it failed to run or build uwp, errors are as following: 

```
[        ]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncOperationCompletedHandler<TResult>,H>' that has a non-virtual        
destructor results in undefined behavior [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncOperationCompletedHandler<TResult>,H>' that has a non-virtual        
destructor results in undefined behavior [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class 'winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>' that has a non-virtual destructor results in undefinedbehavior [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncOperationCompletedHandler<TResult>,H>' that has a non-virtual        
destructor results in undefined behavior [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncOperationCompletedHandler<TResult>,H>' that has a non-virtual        
destructor results in undefined behavior [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class 'winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>' that has a non-virtual destructor results in undefinedbehavior [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract
class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncActionCompletedHandler,H>' that has a non-virtual destructor results 
in undefined behavior [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class
'winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::ApplicationModel::Core::CoreApplicationView,winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs>,H>' that has a non-virtual destructor results in undefined behavior
[E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +3 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncActionCompletedHandler,H>' that has a non-virtual destructor results 
in undefined behavior [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract 
class
'winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::ApplicationModel::Core::CoreApplicationView,winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs>,H>' that has a non-virtual destructor results in undefined behavior
[E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms] “E:\Flutter\github\xx_demo\build\winuwp\ALL_BUILD.vcxproj”(默认目标) (1) ->
[        ] “E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj”(默认目标) (3) ->
[        ] (ClCompile 目标) ->
[        ]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: the following warning istreated as an error (compiling source file E:\Flutter\github\xx_demo\winuwp\runner_uwp\flutter_frameworkview.cpp)
[E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: the following warning istreated as an error (compiling source file E:\Flutter\github\xx_demo\winuwp\runner_uwp\main.cpp)
[E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
[   +2 ms]     10 个警告
[   +1 ms]     2 个错误
[   +1 ms] 已用时间 00:00:20.38
[  +48 ms] Building Windows UWP application... (completed in 44.9s)
[   +2 ms] "flutter winuwp" took 46,941ms.
[   +6 ms] Build process failed.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/windows/build_windows.dart:299:5)
           <asynchronous suspension>
           #2      buildWindowsUwp (package:flutter_tools/src/windows/build_windows.dart:171:5)
           <asynchronous suspension>
           #3      BuildWindowsUwpCommand.runCommand (package:flutter_tools/src/commands/build_winuwp.dart:54:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1090:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)   
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +131 ms] ensureAnalyticsSent: 123ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

```
[√] Flutter (Channel master, 2.3.0-13.0.pre.13, on Microsoft Windows [Version 10.0.19041.985], locale zh-CN)
    • Flutter version 2.3.0-13.0.pre.13 at E:\Flutter\flutter_source\master
    • Upstream repository https://gitee.com/mirrors/Flutter.git
    • Framework revision d6fa9bbf91 (24 hours ago), 2021-05-18 08:55:38 -0700
    • Engine revision 3cda7f5807
    • Dart version 2.14.0 (build 2.14.0-119.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\zmtza\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.30011.22
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\zmtza\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19041.985]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 89.0.4389.90
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 90.0.818.62

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
@clarkezone This is the issue I mentioned hitting (/cc also @cbracken)

@zmtzawqlp Does installing a newer version of the Windows 10 SDK, then rebuilding after deleting `build/`, resolve this for you?

**Comment by zmtzawqlp** [comment]
> @clarkezone This is the issue I mentioned hitting (/cc also @cbracken)
> 
> @zmtzawqlp Does installing a newer version of the Windows 10 SDK, then rebuilding after deleting `build/`, resolve this for you?

yes，it works after i update widnwos sdk to 10.0.19041.0.

**Comment by zmtzawqlp** [comment]
but it crashed with following:

LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]

**Comment by zmtzawqlp** [comment]
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3327,5): warning : APPX4001: Build property AppxBundlePlatforms is not explicitly set and is calculated based on currently building architecture. Use 'Create App Package' wizard or edit project file to set it. [E:\Flutter\github\xx_demo\build\winuwp\runner_uwp\app.vcxproj]

**Comment by zmtzawqlp** [comment]
flutter run -d winuwp

```
[+3350 ms] error: install failed for package
file:///E:/Flutter/github/xx_demo/build/winuwp/runner_uwp/AppPackages/app/app_1.1.0.0_Debug_Test/app_1.1.0.0_x64_Debug.msixbundle with error:
[   +2 ms] Failed to install file:///E:/Flutter/github/xx_demo/build/winuwp/runner_uwp/AppPackages/app/app_1.1.0.0_Debug_Test/app_1.1.0.0_x64_Debug.msixbundle
[   +6 ms] Failed to install app package
[  +17 ms] Error launching application on Windows (UWP).
[  +13 ms] "flutter run" took 186,977ms.
[  +28 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1102:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +201 ms] ensureAnalyticsSent: 173ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

flutter doctor -v

```
[√] Flutter (Channel master, 2.3.0-13.0.pre.111, on Microsoft Windows [Version 10.0.19041.985], locale zh-CN)
    • Flutter version 2.3.0-13.0.pre.111 at E:\Flutter\flutter_source\master
    • Upstream repository https://gitee.com/mirrors/Flutter.git
    • Framework revision c99f60b82f (23 hours ago), 2021-05-21 22:49:03 -0400
    • Engine revision 3fa3eb3a60
    • Dart version 2.14.0 (build 2.14.0-138.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\zmtza\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\zmtza\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (5 available)
    • PCT AL10 (mobile)       • emulator-5554 • android-x86     • Android 7.1.2 (API 25)
    • Windows (desktop)       • windows       • windows-x64     • Microsoft Windows [Version 10.0.19041.985]
    • Windows (UWP) (desktop) • winuwp        • windows-uwp-x64 • 
    • Chrome (web)            • chrome        • web-javascript  • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript  • Microsoft Edge 90.0.818.66

• No issues found!

```

**Comment by Hadi7546** [comment]
Solve my problem. 
Just update Windows 10 SDK

**Comment by zmtzawqlp** [comment]
i try to run demo on anther machine, still failed

flutter run -d winuwp -v

```
[  +24 ms] [  +21 ms] Target unpack_windows_uwp failed: Exception: Missing clientSourceDirectory:
D:\Flutter\flutter_source\master\bin\cache\artifacts\engine\windows-x64\cpp_client_wrapper
[  +51 ms]            #0      unpackDesktopArtifacts (package:flutter_tools/src/build_system/targets/desktop.dart:62:7)
[  +30 ms]            #1      UnpackWindowsUwp.build (package:flutter_tools/src/build_system/targets/windows.dart:159:29)
[   +1 ms]            #2      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:838:27)
[   +2 ms]            <asynchronous suspension>
[   +2 ms]            #3      Future.wait.<anonymous closure> (dart:async/future.dart)
[  +33 ms]            <asynchronous suspension>
[  +15 ms]            #4      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:776:32)[  +14 ms]            <asynchronous suspension>
[   +1 ms]            #5      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:605:16)   
[   +1 ms]            <asynchronous suspension>
[  +29 ms]            #6      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
[   +1 ms]            <asynchronous suspension>
[   +2 ms]            #7      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1102:27)
[  +13 ms]            <asynchronous suspension>
[   +2 ms]            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +1 ms]            <asynchronous suspension>
[   +9 ms]            #9      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #10     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[   +4 ms]            <asynchronous suspension>
[   +6 ms]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)      
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #12     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[   +1 ms]            <asynchronous suspension>
[        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)      
[   +1 ms]            <asynchronous suspension>
[   +7 ms]            #15     main (package:flutter_tools/executable.dart:91:3)
[   +3 ms]            <asynchronous suspension>
[   +5 ms] [  +28 ms] "flutter assemble" took 2,869ms.
[  +49 ms] [  +31 ms] 
[   +1 ms]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[  +24 ms]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
[   +1 ms]            <asynchronous suspension>
[   +3 ms]            #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1102:27)
[   +2 ms]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)      
[   +1 ms]            <asynchronous suspension>
[   +8 ms]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[   +2 ms]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)      
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[   +7 ms]            <asynchronous suspension>
[   +5 ms]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[   +1 ms]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)      
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[   +7 ms]            <asynchronous suspension>
[   +1 ms] [ +309 ms] ensureAnalyticsSent: 306ms
[   +1 ms] [   +3 ms] Running shutdown hooks
[   +1 ms] [        ] Shutdown hooks complete
[   +1 ms] [  +10 ms] exiting with code 1
[  +58 ms] Building Windows UWP application... (completed in 6.0s)
[+12189 ms] Exception: Unable to generate build files
[   +2 ms] "flutter run" took 19,459ms.
[  +34 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1102:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)    
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +205 ms] ensureAnalyticsSent: 196ms
[   +7 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

flutter doctor -v
```
[√] Flutter (Channel master, 2.3.0-13.0.pre.111, on Microsoft Windows [Version 10.0.19041.985], locale zh-CN)
    • Flutter version 2.3.0-13.0.pre.111 at D:\Flutter\flutter_source\master
    • Upstream repository https://gitee.com/mirrors/Flutter.git
    • Framework revision c99f60b82f (2 days ago), 2021-05-21 22:49:03 -0400
    • Engine revision 3fa3eb3a60
    • Dart version 2.14.0 (build 2.14.0-138.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31313.79
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\zmtzawqlp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19041.985]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • Google Chrome 88.0.4324.104
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 90.0.818.66

• No issues found!
```

**Comment by clarkezone** [comment]
You may be missing the c++ UWP tools do you have those installed?

**Comment by AlexV525** [comment]
> You may be missing the c++ UWP tools do you have those installed?

See #84489, which the `cpp_client_wrapper` is not extracted after it gets downloaded. Download the wrapper file and extract it manually to the path solve the wrapper problem.

**Comment by AlexV525** [comment]
> file:///E:/Flutter/github/xx_demo/build/winuwp/runner_uwp/AppPackages/app/app_1.1.0.0_Debug_Test/app_1.1.0.0_x64_Debug.msixbundle with error:
> [   +2 ms] Failed to install file:///E:/Flutter/github/xx_demo/build/winuwp/runner_uwp/AppPackages/app/app_1.1.0.0_Debug_Test/app_1.1.0.0_x64_Debug.msixbundle

@zmtzawqlp For this issue, uninstall the installed app on Windows first, then you can re-run (re-install) it again. This is because windows does not allow apps installed with the same version.

**Comment by cbracken** [comment]
Closing this since our intent is to wind down development on, and remove the UWP embedder in order to focus on the Win32 embedder which, over time, will start to adopt Windows SDK support (once our supported OSes is a subset of those that support doing so).

See: https://github.com/flutter/flutter/issues/14967#issuecomment-1085490495
