### ISSUE TITLE
Windows bot is getting an error starting GOMA

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#82944]
example: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/10060/overview

```
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
waiting for compiler_proxy to respond...
E0519 12:50:52.894920 13484 named_pipe_client_win.cc:47] The system cannot find the file specified.

E0519 12:50:52.894920 13484 goma_ipc.cc:71] call failed: Failed to connect to goma_fuchsia.ipc
GOMA: port request failed. connect_success: 0, err: -1 Failed to connect to goma_fuchsia.ipc, http_return_code: 0
ports are owned by following processes:

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
compiler_proxy.exe            1068 Console                    1    389,216 K

Traceback (most recent call last):
  File "C:\b\s\w\ir\cache\goma\client\goma_ctl.py", line 3031, in <module>
    sys.exit(main())
  File "C:\b\s\w\ir\cache\goma\client\goma_ctl.py", line 3026, in main
    goma.Dispatch(sys.argv[1:])
  File "C:\b\s\w\ir\cache\goma\client\goma_ctl.py", line 1418, in Dispatch
    self._action_mappings.get(args[0], self._DefaultAction)()
  File "C:\b\s\w\ir\cache\goma\client\goma_ctl.py", line 1046, in _RestartCompilerProxy
    self._StartCompilerProxy()
  File "C:\b\s\w\ir\cache\goma\client\goma_ctl.py", line 778, in _StartCompilerProxy
    self._GenericStartCompilerProxy(ensure=False)
  File "C:\b\s\w\ir\cache\goma\client\goma_ctl.py", line 754, in _GenericStartCompilerProxy
    self._env.ExecCompilerProxy()
  File "C:\b\s\w\ir\cache\goma\client\goma_ctl.py", line 2101, in ExecCompilerProxy
    return self._GetCompilerProxyPort(proc=proc)  # set the new gomacc_port.
  File "C:\b\s\w\ir\cache\goma\client\goma_ctl.py", line 1661, in _GetCompilerProxyPort
    raise e
__main__.Error: compiler_proxy is not ready? pid=1068
```

**Comment by yusufm** [comment]
There is an older issue (https://b.corp.google.com/issues/163571808) that might be relevant to this.

**Comment by yusufm** [comment]
I kicked off a retry and the job seems to have progressed further than the original failure point:

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20Host%20Engine/10061/overview

@gaaclarke are you still seeing this error in other places? Have you been successful in retrying the jobs?

**Comment by yusufm** [comment]
https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine has passed multiple runs now and I'll close this issue.

Please reopen if there are other jobs that are still encountering this problem.
