### ISSUE TITLE
'package:flutter/src/rendering/sliver.dart': Failed assertion: line 1685:

### ISSUE THREAD

**Issue by emembrives** [flutter/flutter#8296]
While developing https://fuchsia-review.googlesource.com/20930 in Fuchsia, I got the following exception:

```
[00010.969] 07593.07621>  EXCEPTION CAUGHT BY RENDERING LIBRARY 
[00010.973] 07593.07621> The following assertion was thrown during performResize():
[00010.980] 07593.07621> 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 1685:
[00010.980] 07593.07621> 'constraints.hasBoundedHeight && constraints.hasBoundedWidth': is not true.
[00010.985] 07593.07621> 
[00010.985] 07593.07621> Either the assertion indicates an error in the framework itself, or we should provide substantially
[00010.985] 07593.07621> more information in this error message to help you determine and fix the underlying cause.
[00010.985] 07593.07621> In either case, please report this assertion by filing a bug on GitHub:
[00010.986] 07593.07621>   https://github.com/flutter/flutter/issues/new
[00010.986] 07593.07621> 
[00010.986] 07593.07621> When the exception was thrown, this was the stack:
[00010.993] 07593.07621> #2      RenderViewport.performResize (package:flutter/src/rendering/sliver.dart:1685)
[00010.993] 07593.07621> #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1727)
[00010.993] 07593.07621> #4      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.993] 07593.07621> #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.993] 07593.07621> #6      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.993] 07593.07621> #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.994] 07593.07621> #8      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.994] 07593.07621> #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.994] 07593.07621> #10     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.994] 07593.07621> #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.994] 07593.07621> #12     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.994] 07593.07621> #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.994] 07593.07621> #14     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.994] 07593.07621> #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.994] 07593.07621> #16     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:477)
[00010.994] 07593.07621> #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.994] 07593.07621> #18     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124)
[00010.994] 07593.07621> #19     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:86)
[00010.994] 07593.07621> #20     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194)
[00010.994] 07593.07621> #21     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338)
[00010.995] 07593.07621> #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.995] 07593.07621> #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.995] 07593.07621> #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.995] 07593.07621> #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.995] 07593.07621> #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.995] 07593.07621> #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.995] 07593.07621> #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.996] 07593.07621> #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.996] 07593.07621> #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.996] 07593.07621> #31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.996] 07593.07621> #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.996] 07593.07621> #33     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.996] 07593.07621> #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.996] 07593.07621> #35     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.996] 07593.07621> #36     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2352)
[00010.996] 07593.07621> #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.996] 07593.07621> #38     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.996] 07593.07621> #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.997] 07593.07621> #40     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:354)
[00010.997] 07593.07621> #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.997] 07593.07621> #42     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.997] 07593.07621> #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.997] 07593.07621> #44     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.997] 07593.07621> #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.997] 07593.07621> #46     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.997] 07593.07621> #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.997] 07593.07621> #48     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.997] 07593.07621> #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.998] 07593.07621> #50     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100)
[00010.998] 07593.07621> #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1742)
[00010.998] 07593.07621> #52     RenderView.performLayout (package:flutter/src/rendering/view.dart:114)
[00010.998] 07593.07621> #53     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1618)
[00010.998] 07593.07621> #54     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953)
[00010.998] 07593.07621> #55     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:225)
[00010.998] 07593.07621> #56     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:333)
[00010.998] 07593.07621> #57     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170)
[00010.998] 07593.07621> #58     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676)
[00010.998] 07593.07621> #59     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611)
[00010.998] 07593.07621> #60     runApp (package:flutter/src/widgets/binding.dart:405)
[00010.998] 07593.07621> #61     main (/usr/local/google/home/etiennej/chrome/fuchsia/apps/modular/examples/todo_story/lib/main.dart:227)
[00010.998] 07593.07621> #62     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
[00010.998] 07593.07621> #63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
[00010.999] 07593.07621> (elided 2 frames from class _AssertionError)
[00011.109] 07593.07621> 
[00011.109] 07593.07621> The following RenderObject was being processed when the exception was fired:
[00011.109] 07593.07621>   RenderViewport#684825189 NEEDS-LAYOUT
[00011.109] 07593.07621>   creator: Viewport  IgnorePointer-[GlobalKey#546239015]  Listener  _GestureSemantics 
[00011.109] 07593.07621>   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#349950641]  RepaintBoundary 
[00011.109] 07593.07621>   CustomPaint  RepaintBoundary  NotificationListener<ScrollNotification> 
[00011.109] 07593.07621>   GlowingOverscrollIndicator  Scrollable  ListView  
[00011.109] 07593.07621>   parentData: <none>
[00011.109] 07593.07621>   constraints: BoxConstraints(w=0.0, 0.0<=h<=Infinity)
[00011.109] 07593.07621>   size: MISSING
[00011.109] 07593.07621>   AxisDirection.down
[00011.109] 07593.07621>   offset: ScrollPosition(offset: 0.0, IdleScrollActivity, ScrollDirection.idle, range: null..null,
[00011.109] 07593.07621>   viewport: null)
[00011.109] 07593.07621>   anchor: 0.0
[00011.109] 07593.07621> This RenderObject had the following child:
[00011.109] 07593.07621>   RenderSliverList#162609071 NEEDS-LAYOUT
[00011.109] 07593.07621> 
[00011.115] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.120] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.125] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.130] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.135] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.140] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.145] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.151] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.155] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.197] 07593.07621> Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
[00011.209] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2082: '!_needsLayout': is not true.
[00011.309] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 1685: 'constraints.hasBoundedHeight && constraints.hasBoundedWidth': is not true.
[00011.316] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.321] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.326] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.331] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.336] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.341] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.346] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.351] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.356] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1353: 'hasSize': is not true.
[00011.357] 07593.07621> Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
[00011.372] 07593.07621> Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2082: '!_needsLayout': is not true.
```

**Comment by abarth** [comment]
This often happens when a ListView is used inside another ListView.  By default, ListView expands in the scrolling direction, but when it's inside another ListView there is unlimited space to expand into.  The two common solutions are:

1) Use a BlockBody instead of a ListView.  There's no reason to use a nested ListView because it will never scroll.  Instead, the BlockBody widget has the same layout as a ListView but doesn't scroll.

2) Use the shrinkWrap: true property of ListView.  This property causes the ListView to adopt the height of the sum of all its children's height rather than expand to fill its container.  This approach is useful when your ListView will sometimes be used in a scrolling container and sometimes now.

I'll update the error message to have this information.

**Comment by FaisalAbid** [comment]
I didn't know about shrinkWrap, thats cool. My solution to this was setting double.infinity on the height of the listview

**Comment by Hixie** [comment]
@FaisalAbid can you elaborate on that?

**Comment by FaisalAbid** [comment]
My mistake, I looked at the code again and I solved the issue a different way. 

I put the listview in a container and gave that **width** a double.inf 
Basically I had the following

`  return new ListView.builder(
      itemBuilder: (BuildContext context, index){
        return <Widget>[
          _getHeroCarosuel(),
        ][index];
      },
      itemCount: 1
  );`

```
_getHeroCarosuel() {
  var horizontalList = new ListView.builder(
      scrollDirection: Axis.horizontal,
      itemBuilder: (context, index){
        return <Widget>[
          new Image.network("http://img.wennermedia.com/social/rs-189213-GettyImages_162848166.jpg", fit: ImageFit.fitWidth),
          new Image.network("http://static.srcdn.com/wp-content/uploads/2016/10/John-Wick-2-Poster-NYCC.jpg", fit: ImageFit.fitWidth)
        ][index];
      },itemCount: 2
  );

  return new Container(width: double.INFINITY, height: 225.0, child: horizontalList);
}
```

Notice how getHeroCarosuel returns a new Container with a width of double.infinity and the child being the horizontalList

if I was returning just the horizontalList here, I would get the error in this issue

**Comment by reeteshverma39** [comment]
check shrinwrap:true its working

**Comment by amatshiye** [comment]
@FaisalAbid Thank you. Your solution worked on mine.

**Comment by bingzhao0719** [comment]
> My mistake, I looked at the code again and I solved the issue a different way.
> 
> I put the listview in a container and gave that **width** a double.inf
> Basically I had the following
> 
> ` return new ListView.builder( itemBuilder: (BuildContext context, index){ return <Widget>[ _getHeroCarosuel(), ][index]; }, itemCount: 1 );`
> 
> ```
> _getHeroCarosuel() {
>   var horizontalList = new ListView.builder(
>       scrollDirection: Axis.horizontal,
>       itemBuilder: (context, index){
>         return <Widget>[
>           new Image.network("http://img.wennermedia.com/social/rs-189213-GettyImages_162848166.jpg", fit: ImageFit.fitWidth),
>           new Image.network("http://static.srcdn.com/wp-content/uploads/2016/10/John-Wick-2-Poster-NYCC.jpg", fit: ImageFit.fitWidth)
>         ][index];
>       },itemCount: 2
>   );
> 
>   return new Container(width: double.INFINITY, height: 225.0, child: horizontalList);
> }
> ```
> 
> Notice how getHeroCarosuel returns a new Container with a width of double.infinity and the child being the horizontalList
> 
> if I was returning just the horizontalList here, I would get the error in this issue

Although this does solve the problem of error reporting, what I want is that this listview can't have a definite height to wrap the content, depending on the height of the item.
