### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by ariffmma** [flutter/flutter#82974]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:26:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:677:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1165:11)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:264:11)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:152:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
```
```
[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 1.22.3 at C:\flutter
    • Framework revision 8874f21e79 (7 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\ANABATA\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\ANABATA\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\ANABATA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
flutter_paystack-1.0.3+1
shared_preferences-0.5.6+3
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4
stripe_payment-1.0.6

**Comment by oengmengthong** [comment]
me too. and also can not run to build ios app.

**Comment by iapicca** [comment]
>  Flutter version 1.22.3 at C:\flutter

@ariffmma 
can you run `flutter upgrade -f`

**Comment by darshankawar** [comment]
@ariffmma 
Apart from above suggestion, this issue was fixed and may be only available on master per [this](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004) comment. So run below commands and see if it resolves your issue.

```
flutter channel master
flutter upgrade
flutter pub get
```

I am going ahead and closing this as already fixed in master. If you still see the issue on latest master, write in comments and I'll reopen it.
