### ISSUE TITLE
 CMake Error: The current CMakeCache.txt directory /root/parts/colibri/build/build/linux/x64/release/CMakeCache.txt is different than the directoryer/build/linux/x64/release where CMakeCache.txt was created. 

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#82993]
Hi, I am almost there publish my very first linux APP to snap store. 
But I got a seems easy error but don't know why and how to fix it:

```
[ +435 ms] CMake Error: The current CMakeCache.txt directory /root/parts/colibri/build/build/linux/x64/release/CMakeCache.txt is different than the directory
flutter/build/linux/x64/release where CMakeCache.txt was created. This may result in binaries being created in the
wrong place. If you are not sure, reedit the CMakeCache.txt
[   +7 ms] CMake Error: The source "/root/parts/colibri/build/linux/CMakeLists.txt" does not match the source
flutter/linux/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
[  +38 ms] Building Linux application... (completed in 491ms)
[        ] "flutter linux" took 1,044ms.
[   +6 ms] Unable to generate build files
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmake (package:flutter_tools/src/linux/build_linux.dart:156:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:76:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:88:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1089:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

```

This **might not be flutter issue, but related about release APP so might be something lacked in doc**.

I know this is because of CMakeCache directory not same, but :

1) I dont have any `/root/parts` dir:
```
ls /root/parts/colibri/build                                                                               2 master!?
ls: cannot access '/root/parts/colibri/build': No such file or directory

```

2) I just run `snapcraft`, what could be the reason? How to fix?

**Comment by TahaTesser** [comment]
Hi @jinfagang 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter build linux --verbose` logs running the minimal code sample?
Thank you

**Comment by jinfagang** [comment]
@tadaspetra For sure.

```
flutter doctor                                                                                                master!
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on Linux, locale en_HK.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!

```

For building `flutter build linux` I got no problems:

```
[  +81 ms] Building Linux application... (completed in 40.9s)
[        ] "flutter linux" took 41,281ms.
[ +253 ms] ensureAnalyticsSent: 251ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0

```

**Comment by TahaTesser** [comment]
Hi  @jinfagang 
Is the when running or building? 
Please provide complete logs that shows this error with  a complete reproducible minimal code sample
```
[ +435 ms] CMake Error: The current CMakeCache.txt directory /root/parts/colibri/build/build/linux/x64/release/CMakeCache.txt is different than the directory
flutter/build/linux/x64/release where CMakeCache.txt was created. This may result in binaries being created in the
wrong place. If you are not sure, reedit the CMakeCache.txt
[   +7 ms] CMake Error: The source "/root/parts/colibri/build/linux/CMakeLists.txt" does not match the source
flutter/linux/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
[  +38 ms] Building Linux application... (completed in 491ms)
[        ] "flutter linux" took 1,044ms.
[   +6 ms] Unable to generate build files
```

**Comment by jinfagang** [comment]
@tadaspetra Sorry, I think I make you missunderstood my problem.

I am running into this when run `snapcraft` while using `flutter build linux` got no problem.

That `snapcraft` I just do by the doc from flutter uploading app to snapstore.

**Comment by TahaTesser** [comment]
Hi @jinfagang
Thanks are you following this [doc](https://flutter.dev/docs/deployment/linux#overview-of-snapcraft)?

**Comment by jinfagang** [comment]
I solve this issue by deleting build, thanks
