### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/yangzhengyou/Documents/flutter/1.17.1/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.

### ISSUE THREAD

**Issue by MicroKibaco** [flutter/flutter#82990]
## Command
```
flutter --quiet assemble --depfile /Users/yangzhengyou/Documents/huolala/user-flutter/.android/Flutter/build/intermediates/flutter/release/flutter_build.d --output /Users/yangzhengyou/Documents/huolala/user-flutter/.android/Flutter/build/intermediates/flutter/release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/yangzhengyou/Documents/flutter/1.17.1/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      GenSnapshot.run (package:flutter_tools/src/base/build.dart:74:26)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:198:56)
#6      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:233:52)
#7      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:614:25)
<asynchronous suspension>
#8      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:569:35)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#11     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:569:21)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#12     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:498:36)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:189:58)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, v1.17.1, on macOS 11.3 20E232, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/yangzhengyou/Documents/flutter/1.17.1
    • Framework revision f7a6a7906b (1 year ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yangzhengyou/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /Users/yangzhengyou/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • M2102J2SC • 81097937 • android-arm64 • Android 11 (API 30)

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.userflutter
**iOS bundle identifier**: com.huolala.user
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
device_info-0.4.2+3
flutter_boost-7a7923c0d4f345f3206c9653468bcd8d9193d102
flutter-bugly-b9d2b4a6a8ad120bc5c48f08f89897f00211aa7e
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+2
sqflite-1.3.1+2

**Comment by darshankawar** [comment]
@MicroKibaco 
You are on very old version. Please upgrade to latest master using below commands and try again which should fix your issue.

flutter channel master
flutter upgrade

Note: This issue was fixed already, https://github.com/flutter/flutter/issues/68475

Closing this as already fixed and you need to upgrade to see the change. If you disagree, write in comments and I'll reopen.
