### ISSUE TITLE
exception from flutter create when parsing a gradle  android studio version

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#8301]
It looks like we're parsing a gradle / android studio version as a semver version, but I don't think there's any guarantee that the version string will be a valid semver version.

## command

flutter --no-color create /Users/devoncarew/temp/test_123

## exception

FormatException: Could not parse "2.12".

```
package:pub_semver/src/version.dart 116                                         Version.Version.parse
package:flutter_tools/src/android/android_studio_validator.dart 117             ConfiguredGradleValidator.validate
package:flutter_tools/src/doctor.dart 90                                        Doctor.summaryText
package:flutter_tools/src/doctor.dart 81                                        Doctor.summary
package:flutter_tools/src/commands/create.dart 116                              CreateCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148                       FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119                       FlutterCommand.run
package:args/command_runner.dart 194                                            CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 221                FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                                            CommandRunner.run.<fn>
dart:async                                                                      Future.Future.sync
package:args/command_runner.dart 109                                            CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 150                FlutterCommandRunner.run
package:flutter_tools/executable.dart 128                                       main.<fn>.<fn>
package:stack_trace                                                             Chain.capture
package:flutter_tools/executable.dart 127                                       main.<fn>
package:flutter_tools/src/base/context.dart 76                                  AppContext._run
package:flutter_tools/src/base/context.dart 66                                  AppContext.runInZone.<fn>
dart:async                                                                      runZoned
package:flutter_tools/src/base/context.dart 65                                  AppContext.runInZone
package:flutter_tools/executable.dart 98                                        main
../../projects/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart 8  main
===== asynchronous gap ===========================
dart:async                                                                      _Completer.completeError
package:flutter_tools/src/android/android_studio_validator.dart 136             ConfiguredGradleValidator.validate
===== asynchronous gap ===========================
dart:async                                                                      Future.Future.microtask
package:flutter_tools/src/android/android_studio_validator.dart                 ConfiguredGradleValidator.validate
package:flutter_tools/src/doctor.dart 90                                        Doctor.summaryText
===== asynchronous gap ===========================
dart:async                                                                      _asyncThenWrapperHelper
package:flutter_tools/src/doctor.dart                                           Doctor.summaryText
package:flutter_tools/src/doctor.dart 81                                        Doctor.summary
===== asynchronous gap ===========================
dart:async                                                                      Future.Future.microtask
package:flutter_tools/src/doctor.dart                                           Doctor.summary
package:flutter_tools/src/commands/create.dart 116                              CreateCommand.runCommand
===== asynchronous gap ===========================
dart:async                                                                      _asyncThenWrapperHelper
package:flutter_tools/src/commands/create.dart                                  CreateCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148                       FlutterCommand.verifyThenRunCommand
===== asynchronous gap ===========================
dart:async                                                                      _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart                           FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119                       FlutterCommand.run
package:args/command_runner.dart 194                                            CommandRunner.runCommand
===== asynchronous gap ===========================
dart:async                                                                      Future.Future.microtask
package:args/command_runner.dart                                                CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 221                FlutterCommandRunner.runCommand
===== asynchronous gap ===========================
dart:async                                                                      _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart                    FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                                            CommandRunner.run.<fn>
dart:async                                                                      Future.Future.sync
package:args/command_runner.dart 109                                            CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 150                FlutterCommandRunner.run
package:flutter_tools/executable.dart 128                                       main.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                                      Future.Future.microtask
package:flutter_tools/executable.dart                                           main.<fn>.<fn>
package:stack_trace                                                             Chain.capture
package:flutter_tools/executable.dart 127                                       main.<fn>
```

## flutter doctor

```
encountered exception: FormatException: Could not parse "2.12".

#0      Version.Version.parse (package:pub_semver/src/version.dart:116)
#1      ConfiguredGradleValidator.validate (package:flutter_tools/src/android/android_studio_validator.dart:117)
<asynchronous suspension>
#2      Doctor.diagnose (package:flutter_tools/src/doctor.dart:126)
<asynchronous suspension>
#3      _doctorText.<anonymous closure> (package:flutter_tools/executable.dart:222)
#4      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#5      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#6      _rootRun (dart:async/zone.dart:1150)
#7      _CustomZone.run (dart:async/zone.dart:1026)
#8      runZoned (dart:async/zone.dart:1503)
#9      AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#10     _doctorText (package:flutter_tools/executable.dart:222)
<asynchronous suspension>
#11     _createCrashReport (package:flutter_tools/executable.dart:197)
<asynchronous suspension>
#12     main.<anonymous closure>.<anonymous closure> (package:flutter_tools/executable.dart:169)
#13     _rootRunBinary (dart:async/zone.dart:1170)
#14     _ZoneDelegate.runBinary (dart:async/zone.dart:714)
#15     StackZoneSpecification._handleUncaughtError (package:stack_trace/src/stack_zone_specification.dart:141)
#16     _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)
#17     _Future._propagateToListeners (dart:async/future_impl.dart:586)
#18     _Future._completeError (dart:async/future_impl.dart:485)
#19     _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#20     _Completer.completeError (dart:async/future_impl.dart:27)
#21     main.<anonymous closure>.<anonymous closure> (package:flutter_tools/executable.dart:130)
<asynchronous suspension>
#22     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:93)
#23     _rootRun (dart:async/zone.dart:1150)
#24     _CustomZone.run (dart:async/zone.dart:1026)
#25     runZoned (dart:async/zone.dart:1503)
#26     Chain.capture (package:stack_trace/src/chain.dart:91)
#27     main.<anonymous closure> (package:flutter_tools/executable.dart:127)
<asynchronous suspension>
#28     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#29     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#30     _rootRun (dart:async/zone.dart:1150)
#31     _CustomZone.run (dart:async/zone.dart:1026)
#32     runZoned (dart:async/zone.dart:1503)
#33     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#34     main (package:flutter_tools/executable.dart:98)
<asynchronous suspension>
#35     main (file:///Users/devoncarew/projects/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by jakobr-google** [comment]
Dup of #8298
