### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The method 'contains' was called on null.Receiver: nullTried calling: contains("ext.flutter.activeDevToolsServerAddress")

### ISSUE THREAD

**Issue by Abdullah-Ajmal147** [flutter/flutter#83083]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=R58M4480ELP --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'contains' was called on null.
Receiver: null
Tried calling: contains("ext.flutter.activeDevToolsServerAddress")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      waitForExtension (package:flutter_tools/src/resident_runner.dart:1483:31)
<asynchronous suspension>
#2      ResidentRunner._callDevToolsUriExtension (package:flutter_tools/src/resident_runner.dart:1302:5)
<asynchronous suspension>
#3      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#4      ResidentRunner.maybeCallDevToolsUriServiceExtension (package:flutter_tools/src/resident_runner.dart:1291:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /media/abdullah/Workspace/flutter sdk/flutter
    • Framework revision b1395592de (7 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/abdullah/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_242-release"
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "1.8.0_242-release"

[✓] VS Code (version 1.54.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM A205F (mobile) • R58M4480ELP • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b1395592de68cc8ac4522094ae59956dd21a91db

**Comment by darshankawar** [comment]
@Abdullah-Ajmal147 
A similar issue was fixed, https://github.com/flutter/flutter/issues/75466.
Can you try to switch to latest master and run your command again to see if it works for you ?

```
flutter channel master
flutter upgrade
flutter --no-color run --machine --track-widget-creation --device-id=R58M4480ELP --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart
```

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
