### ISSUE TITLE
iOS: Time Picker not set time after pressing ok button in Enterprise build

### ISSUE THREAD

**Issue by mehtahardikr** [flutter/flutter#83096]
## Steps to Reproduce
```dart
class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  String _selectedTime;

  // We don't need to pass a context to the _show() function
  // You can safety use context as below
  Future<void> _show() async {
    final TimeOfDay result = await showTimePicker(
        context: context, initialTime: TimeOfDay.now() );
    if (result != null) {
      setState(() {
        _selectedTime = result.format(context);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: Center(
        child: Text(
          _selectedTime != null ? _selectedTime : 'No time selected!',
          style: TextStyle(fontSize: 30),
        ),
      ),
      floatingActionButton:
          ElevatedButton(onPressed: _show, child: Text('Show Time Picker')),
    );
  }
}
```

 link : (https://drive.google.com/file/d/1TNz211Ud8SmWtnRj7NK0zswUVmzzYPFa/view)

**Expected results:** 
it should work in real device after generate enterprise build
**Actual results:** 
it works fine with simulator and device while debug run
once enterprise build generated, it not able to pick selected time on ok button tap.

<details>
  <summary>Logs</summary>
Please refer video for enterprise build : 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 2.0.5 at /Users/UserA/Library/Android/flutter
    • Framework revision adc687823a (5 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/UserA/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @mehtahardikr 
When simply running the code on the simulator, it works as expected 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b22742018b (9 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • D72A5DAA-24E6-421B-B4F5-7CFAFB498040 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 90.0.4430.212

• No issues found!

```

</details>

> it should work in real device after generate enterprise build

Can you please clarify "generate enterprise build"  and reproducible steps



Thank you

**Comment by mehtahardikr** [comment]
@TahaTesser  : When i generate archieve from product menu of xcode for distribution purspose by selecting  enterprise option.  and  one more thing i noticed that, its fails on device  < 14.5.1 iOS version also.Can you please try this.

**Comment by TahaTesser** [comment]
Hi @mehtahardikr 
Ah, unfortunately, I don't have the Apple Developer **Enterprise** program to test this issue. I just have regular membership, enterprise build doesn't support it
This issue needs further triage

**Comment by mehtahardikr** [comment]
@TahaTesser  : Thanks for that.  Please keep me posted on that. Thanks again.

**Comment by mehtahardikr** [comment]
@TahaTesser  : is there any updates ?

**Comment by mehtahardikr** [comment]
@TahaTesser  : do i need to wait for triage ? as i have to make app live and because of this issue its still pending.

**Comment by TahaTesser** [comment]
Hi @mehtahardikr 
I just published a sample to my app in the app store (not Enterprise), I can pick time with no issues

<details> 
<summary>preview</summary> 


| Testflight  | Video |
| --------------- | --------------- |
<img src="https://user-images.githubusercontent.com/48603081/120304458-79f8b900-c2d8-11eb-8202-0b048a3d7ffe.PNG" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/120304608-9a287800-c2d8-11eb-94d6-d1aa91cda649.gif" height="450" /> |





</details>



Unfortunately, I don't have access to the Apple Enterprise account, soon somebody from the Flutter team would look at this issue.

**Comment by mehtahardikr** [comment]
@TahaTesser  : thanks buddy for support. I have found issue.
the issue is not actuly related to that time picker but when i try to use `DateFormat.jm().parser('12:00') `that time its crashes.
i just check  and thats happening in signed and enterprise build only. 

and here are the logs of `intl` lib failed on signed and enterprise version:
```
Unhandled Exception: FormatException: Trying to read   from 10:00 at position 6
    #0      _DateFormatField.throwFormatException (package:intl/src/intl/date_format_field.dart:86)
    #1      _DateFormatField.parseLiteral (package:intl/src/intl/date_format_field.dart:55)
    #2      _DateFormatQuotedField.parse (package:intl/src/intl/date_format_field.dart:118)
    #3      DateFormat._parse (package:intl/src/intl/date_format.dart:394)
    #4      DateFormat.parse (package:intl/src/intl/date_format.dart:325)
```

**Comment by TahaTesser** [comment]
@mehtahardikr 
In that case, I recommend you file an issue in `intl` GitHub, thanks for the update, appreciate it 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
