### ISSUE TITLE
[tool_crash] ProcessException: Directory name is invalid. Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 267

### ISSUE THREAD

**Issue by Kaosc** [flutter/flutter#83107]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Dizin adı geçersiz.
 Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 267
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:664:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:663:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:425:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:444:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:283:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:223:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/flutter_cache.dart:121:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:546:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1143:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
```
```
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.985], locale tr-TR)
    • Flutter version 2.2.0 at C:\src\flutter
    • Framework revision b22742018b (7 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Kaosc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.62

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jonahwilliams** [comment]
Hey @Kaosc , could you provide a few more details to us to help us fix this one?

 1. Does the file ` C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat` exist? If so, what happens if you try and run it?
 2. How did you install flutter?

**Comment by Kaosc** [comment]
I fix the issue with downloading the flutter sdk and set the path again. I guess something went wrong while im downloading or extracting the sdk files.

**Comment by jonahwilliams** [comment]
So you downloaded this from the website? It would be really great to know what went wrong so we could fix it...

**Comment by Kaosc** [comment]
I download the Flutter SDK from the website. After extracting the files I added the flutter path from the environment variables and ran flutter doctor. I received a warning that the specified path was not found on cmd. But flutter commands show up after this warning. I took ownership of the files and tried again, but the result did not change. So I deleted all the flutter files and path. I downloaded the SDK again with 3rd party software and reinstalled and did not encounter the same problem. In my case the issue was the some files were damaged while downloading or extracting I guess.

**Comment by zanderso** [comment]
As a sanity check, I downloaded the 2.2 SDK onto my Windows box and extracted with the Windows extractor, and again with WinRAR, and was not able to reproduce this. Nevertheless, the tool could have better checks against corrupted artifacts.
