### ISSUE TITLE
[google_maps_flutter]

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#83126]
I just launched the application:

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following NoSuchMethodError was thrown building _BodyBuilder:
                    The method 'map' was called on null.
                    Receiver: null
                    Tried calling: map<MapEntry<MapsObjectId<Marker>, Marker>>(Closure: (Marker) =>
                    MapEntry<MapsObjectId<Marker>, Marker>)

                    The relevant error-causing widget was:
                      Scaffold-[LabeledGlobalKey<ScaffoldState>#49800] file:///myapp/lib/any.dart:1586:1

                    When the exception was thrown, this was the stack:
                    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
                    #1      keyByMapsObjectId (package:google_maps_flutter_platform_interface/src/types/utils/maps_object.dart:10:54)
                    #2      keyByMarkerId (package:google_maps_flutter_platform_interface/src/types/utils/marker.dart:10:10)
                    #3      _GoogleMapState.initState (package:google_maps_flutter/src/google_map.dart:270:16)
                    #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4711:57)
                    #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
                    #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
                    #7      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
                    #8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:32)
                    ...     Normal element mounting (19 frames)
                    #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
                    #28     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
                    #29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:32)
                    ...     Normal element mounting (267 frames)
                    #296    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
                    #297    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
                    #298    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6232:32)
                    ...     Normal element mounting (510 frames)
                    #808    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
                    #809    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6221:36)
                    #810    Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
                    #811    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5654:32)
                    #812    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6243:17)
                    #813    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #814    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
                    #815    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
                    #816    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
                    #817    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
                    #818    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #819    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
                    #820    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
                    #821    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
                    #822    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #823    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
                    #824    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
                    #825    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
                    #826    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
                    #827    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #828    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
                    #829    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #830    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
                    #831    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
                    #832    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
                    #833    StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
                    #834    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #835    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
                    #836    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #837    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
                    #838    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #839    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
                    #840    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
                    #841    ProxyElement.update (package:flutter/src/widgets/framework.dart:4922:5)
                    #842    Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
                    #843    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
                    #844    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
                    #845    Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
                    #846    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
                    #847    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
                    #848    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
                    #849    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
                    #850    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
                    #851    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
                    #855    _invoke (dart:ui/hooks.dart:163:10)
                    #856    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
                    #857    _drawFrame (dart:ui/hooks.dart:126:31)
                    (elided 3 frames from dart:async)

**Comment by imeDevelopers** [comment]
Changing C:\Users\MYUSER\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_maps_flutter_platform_interface-2.0.4\lib\src\types\utils\maps_object.dart

From:
```
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import '../maps_object.dart';

/// Converts an [Iterable] of [MapsObject]s in a Map of [MapObjectId] -> [MapObject].
Map<MapsObjectId<T>, T> keyByMapsObjectId<T extends MapsObject>(
    Iterable<T> objects) {
  return Map<MapsObjectId<T>, T>.fromEntries(objects.map((T object) =>
      MapEntry<MapsObjectId<T>, T>(
          object.mapsId as MapsObjectId<T>, object.clone())));
}

/// Converts a Set of [MapsObject]s into something serializable in JSON.
Object serializeMapsObjectSet(Set<MapsObject> mapsObjects) {
  return mapsObjects.map<Object>((MapsObject p) => p.toJson()).toList();
}
```


To:
```
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import '../maps_object.dart';

/// Converts an [Iterable] of [MapsObject]s in a Map of [MapObjectId] -> [MapObject].
Map<MapsObjectId<T>, T> keyByMapsObjectId<T extends MapsObject>(
    Iterable<T> objects) {
  if(objects == null){return <MapsObjectId<T>, T>{};}
  return Map<MapsObjectId<T>, T>.fromEntries(objects.map((T object) =>
      MapEntry<MapsObjectId<T>, T>(
          object.mapsId as MapsObjectId<T>, object.clone())));
}

/// Converts a Set of [MapsObject]s into something serializable in JSON.
Object serializeMapsObjectSet(Set<MapsObject> mapsObjects) {
  if(mapsObjects == null){return [];}
  return mapsObjects.map<Object>((MapsObject p) => p.toJson()).toList();
}
```

SOLVED THE PROBLEM, YOU SHOULD UPDATE THIS FILE IN THE PLUGIN, THANKS.
