### ISSUE TITLE
iOS: Running with a local profile build tries to run clang_x64/gen_snapshot_arm64

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#83133]
**invocation:** `flutter --local-engine-src-path ~/dev/engine/src --local-engine=ios_profile run --profile`
**log:**
```
               [   +6 ms] executing: /Users/aaclarke/dev/engine/src/out/ios_profile/clang_x64/gen_snapshot_arm64 --deterministic --snapshot_kind=app-aot-assembly

--assembly=/Users/aaclarke/dev/flutter/dev/benchmarks/platform_channels_benchmarks/.dart_tool/flutter_build/e55b1c8104495b7ee97cf0b96930f981/arm64/snapshot_assembly.S --strip
               /Users/aaclarke/dev/flutter/dev/benchmarks/platform_channels_benchmarks/.dart_tool/flutter_build/e55b1c8104495b7ee97cf0b96930f981/app.dill
               [   +5 ms] Persisting file store
               [   +8 ms] Done persisting file store
               [   +4 ms] Target aot_assembly_profile failed: ProcessException: Failed to find "/Users/aaclarke/dev/engine/src/out/ios_profile/clang_x64/gen_snapshot_arm64" in the
search
               path.
                            Command: /Users/aaclarke/dev/engine/src/out/ios_profile/clang_x64/gen_snapshot_arm64 
                          #0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:58:7)
                          #1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
                          #2      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
                          #3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
```

**Evaluation:**
Notice /Users/aaclarke/dev/engine/src/out/ios_profile/clang_x64/gen_snapshot_arm64, that seems like an incorrect path.  That file doesn't exist.

**Comment by gaaclarke** [comment]
duplicate https://github.com/flutter/flutter/issues/38933
