### ISSUE TITLE
Handle Android device being out of disk space more gracefully

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#83142]
```
ianh@burmese:~/dev/bug79063$ run --profile --purge-persistent-cache
Downloading Web SDK...                                           2,238ms
Running "flutter pub get" in bug79063...                           529ms
Launching lib/main.dart on Lenovo TB 8504F in profile mode...
Running Gradle task 'assembleProfile'...                           25.4s
✓  Built build/app/outputs/flutter-apk/app-profile.apk (9.9MB).
Installing build/app/outputs/flutter-apk/app.apk...                366ms
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /home/ianh/dev/bug79063/build/app/outputs/flutter-apk/app.apk: 
Exception occurred while executing:
android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:422)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:1380)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:201)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:109)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23064)
	at android.os.Binder.shellCommand(Binder.java:594)
	at android.os.Binder.onTransact(Binder.java:492)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2658)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3961)
	at android.os.Binder.execTransact(Binder.java:697)
Caused by: java.io.IOException: Requested internal only, but not enough space
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:499)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:417)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:432)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:511)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:420)
	... 10 more
Error running application on Lenovo TB 8504F.
ianh@burmese:~/dev/bug79063$
```

Seems like we should be able to recognize this error and handle it more gracefully.

**Comment by jonahwilliams** [comment]
TIL that is what happens when you run out of space

**Comment by jonahwilliams** [comment]
we don't even get a code from ADB? :(

**Comment by Hixie** [comment]
I mean... we get a `1`, does that count? :-)

**Comment by blasten** [comment]
Similar to `gradle_errors.dart`, we could have `adb_errors.dart`.
