### ISSUE TITLE
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'

### ISSUE THREAD

**Issue by SavanRajyaguru** [flutter/flutter#83197]
Hii, I am creating new flutter app related to AR . 
I configure my app using this article:  [https://medium.com/@difrancescogianmarco/arcore-flutter-plugin-configurations-3ee53f2dc749](url)

I add some code in this file location given in the article

> ### [Projectname]->app->src->main->AndroidManifest.xml

```
<!-- "AR Required" apps must declare minSdkVersion ≥ 24 -->
    <uses-sdk android:minSdkVersion="24" />

    <uses-permission android:name="android.permission.CAMERA" />

    <!-- Indicates that app requires ARCore ("AR Required"). Ensures app is only
         visible in the Google Play Store on devices that support ARCore.
    -->
    <uses-feature android:name="android.hardware.camera.ar" />

    <application>
        …
        <!-- Indicates that app requires ARCore ("AR Required"). Causes Google
             Play Store to download and install ARCore when the app is installed.
        -->
        <meta-data android:name="com.google.ar.core" android:value="required" />
    </application>
```

> ### flutter run --verbose

```
[ +243 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +130 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] d72bfb8d073c6cf943a6637290dd3f8cdad11831
[   +1 ms] executing: [C:\src\flutter/] git tag --points-at d72bfb8d073c6cf943a6637290dd3f8cdad11831
[  +83 ms] Exit code 0 from: git tag --points-at d72bfb8d073c6cf943a6637290dd3f8cdad11831
[   +1 ms] 2.3.0-0.1.pre
[  +16 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +71 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +81 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +307 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] dev
[ +131 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] executing: C:\Users\Savan Rajyaguru\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +57 ms] List of devices attached
           12c6d4860005           device product:vince model:Redmi_Note_5 device:vince transport_id:2
[   +9 ms] C:\Users\Savan Rajyaguru\AppData\Local\Android\sdk\platform-tools\adb.exe -s 12c6d4860005 shell getprop
[ +196 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +185 ms] Skipping pub get: version match.
[  +12 ms] Found plugin arcore_flutter_plugin at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\
[ +378 ms] Found plugin arcore_flutter_plugin at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\
[  +98 ms] Generating S:\Firebase Flutter App\augmented_reality_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +119 ms] ro.hardware = qcom
[  +74 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +6 ms] complete
[  +11 ms] Launching lib\main.dart on Redmi Note 5 in debug mode...
[  +12 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\SAVANR~1\AppData\Local\Temp\flutter_tools.24a4e798\flutter_tool.b0d2c3d4\app.dill --packages S:\Firebase Flutter
App\augmented_reality_app\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +41 ms] executing: C:\Users\Savan Rajyaguru\AppData\Local\Android\sdk\platform-tools\adb.exe -s 12c6d4860005 shell -x logcat -v time -t 1
[  +27 ms] <- compile package:augmented_reality_app/main.dart
[ +298 ms] --------- beginning of main
                    05-23 11:05:55.198 W/CrashLoopRemedyLog( 6669): unable to delete remedy log, instaCrash: true
[  +16 ms] executing: C:\Users\Savan Rajyaguru\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +27 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as C:\Users\Savan Rajyaguru\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +5 ms] executing: C:\Users\Savan Rajyaguru\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +30 ms] Building APK
[  +33 ms] Running Gradle task 'assembleDebug'...
[  +11 ms] Using gradle from S:\Firebase Flutter App\augmented_reality_app\android\gradlew.bat.
[  +10 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +187 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +3 ms] executing: [S:\Firebase Flutter App\augmented_reality_app\android/] S:\Firebase Flutter App\augmented_reality_app\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm64 -Ptarget=S:\Firebase Flutter App\augmented_reality_app\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2789 ms] > Configure project :arcore_flutter_plugin
[   +2 ms] WARNING: The option setting 'android.enableR8=true' is deprecated.
[   +1 ms] It will be removed in version 5.0 of the Android Gradle plugin.
[   +1 ms] You will no longer be able to disable R8
[+2184 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [ +128 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [  +93 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] d72bfb8d073c6cf943a6637290dd3f8cdad11831
[        ] [        ] executing: [C:\src\flutter/] git tag --points-at d72bfb8d073c6cf943a6637290dd3f8cdad11831
[   +1 ms] [  +75 ms] Exit code 0 from: git tag --points-at d72bfb8d073c6cf943a6637290dd3f8cdad11831
[        ] [        ] 2.3.0-0.1.pre
[        ] [   +8 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/dev
[        ] [        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[   +1 ms] [  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[   +2 ms] [  +72 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[   +1 ms] [  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] dev
[        ] [  +83 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [ +135 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[   +1 ms] [  +48 ms] Initializing file store
[   +1 ms] [  +20 ms] Done initializing file store
[        ] [  +54 ms] Skipping target: gen_localizations
[ +733 ms] [ +780 ms] Skipping target: kernel_snapshot
[ +394 ms] [ +432 ms] Skipping target: debug_android_application
[   +1 ms] [        ] Persisting file store
[ +196 ms] [ +150 ms] Done persisting file store
[   +3 ms] [  +15 ms] build succeeded.
[  +91 ms] [  +43 ms] "flutter assemble" took 1,697ms.
[ +301 ms] [ +305 ms] ensureAnalyticsSent: 293ms
[   +1 ms] [   +1 ms] Running shutdown hooks
[   +1 ms] [        ] Shutdown hooks complete
[   +1 ms] [   +1 ms] exiting with code 0
[        ] Parameter format not correct -
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :arcore_flutter_plugin:preBuild UP-TO-DATE
[        ] > Task :arcore_flutter_plugin:preDebugBuild UP-TO-DATE
[  +89 ms] > Task :arcore_flutter_plugin:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :arcore_flutter_plugin:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] > Task :arcore_flutter_plugin:writeDebugAarMetadata UP-TO-DATE
[        ] > Task :app:checkDebugAarMetadata UP-TO-DATE
[  +96 ms] > Task :app:cleanMergeDebugAssets
[   +1 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders NO-SOURCE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :arcore_flutter_plugin:mergeDebugShaders UP-TO-DATE
[        ] > Task :arcore_flutter_plugin:compileDebugShaders NO-SOURCE
[        ] > Task :arcore_flutter_plugin:generateDebugAssets UP-TO-DATE
[        ] > Task :arcore_flutter_plugin:packageDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +297 ms] > Task :app:copyFlutterAssetsDebug
[   +4 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +6 ms] > Task :app:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :arcore_flutter_plugin:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :arcore_flutter_plugin:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :arcore_flutter_plugin:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :arcore_flutter_plugin:packageDebugResources UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +1 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[   +3 ms] > Task :arcore_flutter_plugin:extractDeepLinksDebug UP-TO-DATE
[  +78 ms] > Task :arcore_flutter_plugin:processDebugManifest UP-TO-DATE
[   +2 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifestForPackage UP-TO-DATE
[   +1 ms] > Task :arcore_flutter_plugin:compileDebugLibraryResources UP-TO-DATE
[        ] > Task :arcore_flutter_plugin:parseDebugLocalResources UP-TO-DATE
[  +83 ms] > Task :arcore_flutter_plugin:generateDebugRFile UP-TO-DATE
[ +898 ms] > Task :app:processDebugResources
[   +1 ms] > Task :arcore_flutter_plugin:generateDebugBuildConfig UP-TO-DATE
[+2908 ms] > Task :arcore_flutter_plugin:compileDebugKotlin FAILED
[   +2 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 28 actionable tasks: 6 executed, 22 up-to-date
[   +2 ms] e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArCoreView.kt: (245,
38): Object is not abstract and does not implement abstract member public abstract fun onActivityCreated(@NonNull p0: Activity, @Nullable p1: Bundle?): Unit defined in
android.app.Application.ActivityLifecycleCallbacks
[   +6 ms] e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArCoreView.kt: (246,
13): 'onActivityCreated' overrides nothing
[   +1 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 11s
[ +542 ms] Running Gradle task 'assembleDebug'... (completed in 12.0s)
[ +649 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 14,543ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1059:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +150 ms] ensureAnalyticsSent: 145ms
[   +6 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

**Comment by darshankawar** [comment]
@SavanRajyaguru 
This doesn't seem to be an issue in the framework. Since you are using 3rd party plugin, please open this issue in dedicated plugin repo to get help on resolution: https://github.com/giandifra/arcore_flutter_plugin/issues

Closing from here.

**Comment by SavanRajyaguru** [comment]
@darshankawar Thank You 
Can you help to solve this issue? [https://github.com/flutter/flutter/issues/83234](url)
It has been closed but its not solve
