### ISSUE TITLE
flutter call android always throw MissingPluginException(No implementation found for method getDeviceInfo

### ISSUE THREAD

**Issue by Reinoal** [flutter/flutter#83210]
what did I do wrong? All dependencies are added.
I've tried many things, and the result is always the same.

```console
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getDeviceInfo on channel faxian.com/device_info)
E/flutter (22021): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (22021): <asynchronous suspension>
E/flutter (22021): #1      _LoginPageState._getDeviceInfo (package:flutter_faxian/pages/login/index.dart:84:20)
E/flutter (22021): <asynchronous suspension>
```

```
android 11
```

```
Framework • revision adc687823a (5 weeks ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3
```

```
const info_Channel = const MethodChannel("faxian.com/device_info");

void _getDeviceInfo()async{
    final result = await info_Channel.invokeMethod("getDeviceInfo");
    print(result);
  }
```

```xml
<meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"
                tools:replace="android:resource" />
<meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

```java
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        flutterEngine.plugins.add(GetDevicePlugin())
        super.configureFlutterEngine(flutterEngine)
    }
}

class GetDevicePlugin:FlutterActivity(), FlutterPlugin, MethodChannel.MethodCallHandler{

    private val CHANNEL = "faxian.com/device_info"

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        if (call.method.equals("getDeviceInfo")){
            result.success("------flutter call android getDeviceInfo------")
        }
    }

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        val channel = MethodChannel(binding.binaryMessenger, CHANNEL)
        channel.setMethodCallHandler(this)
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
    }
}
```

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
```

</details>

**Comment by TahaTesser** [comment]
Hi @Reinoal 
Seems to have an issue with your code

I just followed this [doc](https://flutter.dev/docs/development/platform-integration/platform-channels), there is no issue 

```kt
package com.example.stable_flutter

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity : FlutterActivity() {
    private val CHANNEL = "samples.flutter.dev/battery"


    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
            if (call.method == "getBatteryLevel") {
                result.success("------flutter call getBatteryLevel------")
            } else {
                result.notImplemented()
            }
        }
    }
}
```

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  static const platform = const MethodChannel('samples.flutter.dev/battery');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          try {
            final String result =
                await platform.invokeMethod('getBatteryLevel');
            print(result);
          } on PlatformException catch (e) {}
        },
      ),
    );
  }
}

```


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
