### ISSUE TITLE
Building appbundle issue: Target kernel_snapshot failed

### ISSUE THREAD

**Issue by figengungor** [flutter/flutter#83238]
## Steps to Reproduce

1. I'm trying to build appbundle with Process as following:
```dart
await Process.run('flutter', ['build', 'appbundle', '--no-tree-shake-icons','--release', '--verbose'],
            workingDirectory: Constants.getProjectDirectory(config))
        .then((ProcessResult results) async{
      await ErrorUtils.checkProcessExitCode(config.deployment.id,
          results, ErrorCode.BUILD_APP_BUNDLE_ERROR);
    });
```

**Expected results:** 
It should create the appbundle.

**Actual results:** 
It gives me the following error:
```
Build failed with an exception.
[        ] * Where:
[        ] Script '/var/theproject/libs/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/var/theproject/libs/flutter/bin/flutter'' finished with non-zero exit value 1
```

You can check logs for full exception:

<details>
  <summary>Logs</summary>

```
Target kernel_snapshot failed: Exception
[  +24 ms]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:267:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:801:27)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #9      _rootRun (dart:async/zone.dart:1190:13)
[        ]            #10     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[        ] [  +12 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:238:7)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +1 ms]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #35     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[   +7 ms]            #42     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #43     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #44     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #45     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #47     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #48     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #49     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #50     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #51     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #52     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #53     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #54     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #55     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #56     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #57     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #58     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #59     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #60     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #61     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #62     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #63     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #64     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #65     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #66     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #67     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #68     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
[        ]            #69     _rootRunBinary (dart:async/zone.dart:1214:47)
[        ]            #70     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
[        ]            #71     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
[   +1 ms]            #72     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
[   +2 ms]            #73     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
[        ]            #74     Future._completeError (dart:async/future_impl.dart:537:5)
[        ]            #75     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
[        ]            #76     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart)
[        ]            #77     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #78     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #79     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #80     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #81     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #82     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #83     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #84     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #85     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
[        ]            #86     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #87     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #88     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #89     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[   +2 ms]            #90     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #91     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #92     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
[        ]            #93     _rootRun (dart:async/zone.dart:1190:13)
[        ]            #94     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #95     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #96     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #97     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #98     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #99     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #100    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[ +401 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/var/theproject/libs/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/var/theproject/libs/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 5m 58s
[  +10 ms] Gradle task bundleRelease failed with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

```
```

```
Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.6 at /var/theproject/libs/flutter
    • Framework revision 9b2d32b605 (4 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /var/theproject/libs/android-sdk-linux
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @figengungor 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by figengungor** [comment]
Here's my updated flutter doctor -v result:

```
 Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.2 at /var/appforyou/libs/flutter
    • Framework revision d79295af24 (6 days ago), 2021-06-11 08:56:01
      -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at /var/appforyou/libs/android-sdk-linux
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-b08)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome
      executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

Exception:

```
Dart snapshot generator failed with exit code -9                        
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/var/appforyou/libs/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/var/appforyou/libs/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 6m 51s                                                  
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     412.5s
Gradle task assembleRelease failed with exit code 1
```

Sorry I cannot share a minimal code sample. I have a huge project and this happens randomly. 

Do you have any idea what might be the issue or how can I debug this?

**Comment by TahaTesser** [comment]
Hi @figengungor 
Thanks for the update, unfortunately without a complete reproducible/code sample it is hard to pin the issue. 
Can you please try to isolate the issue and provide the reproducible steps
Thank you

**Comment by hamad22h** [comment]
[]()

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
