### ISSUE TITLE
Oops; flutter has exited unexpectedly. (Version.Version.parse)

### ISSUE THREAD

**Issue by darrellpf** [flutter/flutter#8329]
New version code is failing on parsing Android Studio version

(file upload doesn't support log so just dumped it here)
----------------------------
more /home/darrell/IdeaProjects/flutter/examples/flutter_gallery/flutter_01.log
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color upgrade

## exception

FormatException: Could not parse "3.2".

```
package:pub_semver/src/version.dart 116                                Version.Version.parse
package:flutter_tools/src/android/android_studio_validator.dart 117    ConfiguredGradleValidator.validate
package:flutter_tools/src/doctor.dart 126                              Doctor.diagnose
package:flutter_tools/src/commands/upgrade.dart 80                     UpgradeCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148              FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119              FlutterCommand.run
package:args/command_runner.dart 194                                   CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 221       FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                                   CommandRunner.run.<fn>
dart:async                                                             Future.Future.sync
package:args/command_runner.dart 109                                   CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 150       FlutterCommandRunner.run
package:flutter_tools/executable.dart 128                              main.<fn>.<fn>
package:stack_trace                                                    Chain.capture
package:flutter_tools/executable.dart 127                              main.<fn>
package:flutter_tools/src/base/context.dart 76                         AppContext._run
package:flutter_tools/src/base/context.dart 66                         AppContext.runInZone.<fn>
dart:async                                                             runZoned
package:flutter_tools/src/base/context.dart 65                         AppContext.runInZone
package:flutter_tools/executable.dart 98                               main
/home/darrell/flutter/packages/flutter_tools/bin/flutter_tools.dart 8  main
===== asynchronous gap ===========================
dart:async                                                             _Completer.completeError
package:flutter_tools/src/android/android_studio_validator.dart 136    ConfiguredGradleValidator.validate
===== asynchronous gap ===========================
dart:async                                                             Future.Future.microtask
package:flutter_tools/src/android/android_studio_validator.dart        ConfiguredGradleValidator.validate
package:flutter_tools/src/doctor.dart 126                              Doctor.diagnose
===== asynchronous gap ===========================
dart:async                                                             _asyncThenWrapperHelper
package:flutter_tools/src/doctor.dart                                  Doctor.diagnose
package:flutter_tools/src/commands/upgrade.dart 80                     UpgradeCommand.runCommand
===== asynchronous gap ===========================
dart:async                                                             _asyncThenWrapperHelper
package:flutter_tools/src/commands/upgrade.dart                        UpgradeCommand.runCommand
package:flutter_tools/src/runner/flutter_command.dart 148              FlutterCommand.verifyThenRunCommand
===== asynchronous gap ===========================
dart:async                                                             _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart                  FlutterCommand.verifyThenRunCommand
package:flutter_tools/src/runner/flutter_command.dart 119              FlutterCommand.run
package:args/command_runner.dart 194                                   CommandRunner.runCommand
===== asynchronous gap ===========================
dart:async                                                             Future.Future.microtask
package:args/command_runner.dart                                       CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 221       FlutterCommandRunner.runCommand
===== asynchronous gap ===========================
dart:async                                                             _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart           FlutterCommandRunner.runCommand
package:args/command_runner.dart 109                                   CommandRunner.run.<fn>
dart:async                                                             Future.Future.sync
package:args/command_runner.dart 109                                   CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 150       FlutterCommandRunner.run
package:flutter_tools/executable.dart 128                              main.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                             Future.Future.microtask
package:flutter_tools/executable.dart                                  main.<fn>.<fn>
package:stack_trace                                                    Chain.capture
package:flutter_tools/executable.dart 127                              main.<fn>
```

## flutter doctor

```
encountered exception: FormatException: Could not parse "3.2".

#0      Version.Version.parse (package:pub_semver/src/version.dart:116)
#1      ConfiguredGradleValidator.validate (package:flutter_tools/src/android/android_studio_validator.dart:117)
<asynchronous suspension>
#2      Doctor.diagnose (package:flutter_tools/src/doctor.dart:126)
<asynchronous suspension>
#3      _doctorText.<anonymous closure> (package:flutter_tools/executable.dart:222)
#4      AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#5      AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#6      _rootRun (dart:async/zone.dart:1150)
#7      _CustomZone.run (dart:async/zone.dart:1026)
#8      runZoned (dart:async/zone.dart:1503)
#9      AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#10     _doctorText (package:flutter_tools/executable.dart:222)
<asynchronous suspension>
#11     _createCrashReport (package:flutter_tools/executable.dart:197)
<asynchronous suspension>
#12     main.<anonymous closure>.<anonymous closure> (package:flutter_tools/executable.dart:169)
#13     _rootRunBinary (dart:async/zone.dart:1170)
#14     _ZoneDelegate.runBinary (dart:async/zone.dart:714)
#15     StackZoneSpecification._handleUncaughtError (package:stack_trace/src/stack_zone_specification.dart:141)
#16     _CustomZone.handleUncaughtError (dart:async/zone.dart:1005)
#17     _Future._propagateToListeners (dart:async/future_impl.dart:586)
#18     _Future._completeError (dart:async/future_impl.dart:485)
#19     _SyncCompleter._completeError (dart:async/future_impl.dart:56)
#20     _Completer.completeError (dart:async/future_impl.dart:27)
#21     main.<anonymous closure>.<anonymous closure> (package:flutter_tools/executable.dart:130)
<asynchronous suspension>
#22     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:93)
#23     _rootRun (dart:async/zone.dart:1150)
#24     _CustomZone.run (dart:async/zone.dart:1026)
#25     runZoned (dart:async/zone.dart:1503)
#26     Chain.capture (package:stack_trace/src/chain.dart:91)
#27     main.<anonymous closure> (package:flutter_tools/executable.dart:127)
<asynchronous suspension>
#28     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#29     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#30     _rootRun (dart:async/zone.dart:1150)
#31     _CustomZone.run (dart:async/zone.dart:1026)
#32     runZoned (dart:async/zone.dart:1503)
#33     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#34     main (package:flutter_tools/executable.dart:98)
<asynchronous suspension>
#35     main (file:///home/darrell/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


## Flutter Doctor
Running flutter doctor...
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/darrell/flutter
    • Framework revision a745fd58be (29 minutes ago), 2017-02-22 14:35:49
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /home/darrell/Android/Sdk
    • Platform android-25, build-tools 25.0.0
    • Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

[-] Android Studio (version 2.3)
    • Android Studio at /home/darrell/android-studio
    ✗ Gradle not found.
    • Try updating or re-installing Android Studio.

**Comment by cbracken** [comment]
@jakobr-google

**Comment by jakobr-google** [comment]
This isn't the new version code, it's still using pub_semver. Are you synced past 3676ffe477c1f5b2013bcbbcb8547fcb743fb2af?

**Comment by darrellpf** [comment]
I synced this morning. Thought this bug might be related to new code added for #8298

**Comment by darrellpf** [comment]
Synced again... looks fixed so I might have been between useful versions.

/home/darrell/flutter/bin/flutter --no-color upgrade
Upgrading Flutter from /home/darrell/flutter...
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision a745fd58be (5 hours ago) • 2017-02-22 14:35:49
Engine • revision ab09530927
Tools • Dart 1.23.0-dev.0.0

Running 'flutter packages upgrade' in flutter_gallery...

Running flutter doctor...
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/darrell/flutter
    • Framework revision a745fd58be (5 hours ago), 2017-02-22 14:35:49
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /home/darrell/Android/Sdk
    • Platform android-25, build-tools 25.0.0

[✓] Android Studio (version 2.3)
    • Android Studio at /home/darrell/android-studio
    • Gradle version 3.2

[✓] Gradle (3.2)
    • gradle-dir = /home/darrell/android-studio/gradle/gradle-3.2
    • Consider removing the gradle-dir setting to use Gradle from Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.10

[-] IntelliJ IDEA Community Edition (version 2017.1)
    • Dart plugin version 171.3019.10
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1 (API 25) (emulator)
Process finished with exit code 0

**Comment by cbracken** [comment]
Thanks for confirming! If you run into this again please re-open.

**Comment by jakobr-google** [comment]
And BTW, you should be able to remove the workaround for #8298 now (by running `flutter config --gradle-dir=`).
