### ISSUE TITLE
[tool_crash] StateError: Bad state: StreamSink is closed

### ISSUE THREAD

**Issue by XcodeSheng** [flutter/flutter#83330]
## Command
```
flutter --no-color attach --machine --device-id=AAB0B67C-5C75-46F5-B5B6-29C3FC800C91 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: StreamSink is closed
```
#0      _StreamSinkImpl.add (dart:_http/http_impl.dart:632:7)
#1      _WebSocketImpl.add (dart:_http/websocket_impl.dart:1223:11)
#2      VmService._processRequest (package:vm_service/src/vm_service.dart:2098:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.6 at /Users/aikucun/flutter/flutter
    • Framework revision 1d9032c7e1 (4 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/aikucun/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • AAB0B67C-5C75-46F5-B5B6-29C3FC800C91 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 90.0.4430.212
    ! Error: nie的 iPhone is not connected. Xcode will continue when nie的 iPhone is connected. (code -13)

• No issues found!

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.mengxiang.akc.flutter
**iOS bundle identifier**: com.mengxiang.akc.flutter
**Creation channel**: null
**Creation framework version**: null
### Plugins
flutter_boost-a3938eff699cfa9bd6e922ba736339db4f976314
mx-log-c10939aa50cb97e9b40b85fb717f4ecb343cc2ef
package_info-0.4.3+4
path_provider_linux-0.0.1+2
path_provider_windows-0.0.4+3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3

**Comment by iapicca** [comment]
related to https://github.com/dart-lang/webdev/issues/943

**Comment by darshankawar** [comment]
In flutter repo, the last occurence of opening this issue was last year, https://github.com/flutter/flutter/issues/58315.

A similar one was fixed in dart-lang/webdev https://github.com/dart-lang/webdev/issues/943

**Comment by darshankawar** [comment]
Keeping this open for further insights and investigation.

Cc: @grouma

**Comment by darshankawar** [comment]
@XcodeSheng 
Can you confirm if you are still facing this issue when you run the said command using latest stable version ?
