### ISSUE TITLE
Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.

### ISSUE THREAD

**Issue by namangor04** [flutter/flutter#83336]
## Steps to Reproduce

1. Create an Alert Dialog with A textField in it,
2.  Click on the text field. The error Occurs.

**Expected results:** No errors

**Actual results:** 

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RendererBinding._scheduleMouseTrackerUpdate (package:flutter/src/rendering/binding.dart:334:12)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
...
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RendererBinding._scheduleMouseTrackerUpdate (package:flutter/src/rendering/binding.dart:334:12)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:329:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
...
====================================================================================================

```

<details>
  <summary>Logs</summary>

```
The error doesn't show up here in the flutter run --verbose log
```

```
Analyzing <app-name>...

   info - Don't import implementation files from another package - lib\generated_plugin_registrant.dart:8:8 - implementation_imports

1 issue found. (ran in 41.6s)
```

flutter doctor -v

```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
    • Flutter version 2.2.0 at F:\SDKs\Flutter\flutter
    • Framework revision b22742018b (10 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\SDKs\android_sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: F:\IDEs\android_studio_ide\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at F:\IDEs\android_studio_ide
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code
    • VS Code at C:\Users\Naman Bharat Gor\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (4 available)
    • CPH1809 (mobile)  • 4f95065e • android-arm64  • Android 8.1.0 (API 27)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @namangor04 
Unable to reproduce the issue based on your instructions. 

Here I created a code sample to try

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  Future<void> _launchMyDialog(BuildContext context) async {
    return showDialog<void>(
      context: context,
      barrierDismissible: false, // user must tap button!
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text('Alert Dialog'),
          content: SingleChildScrollView(
            child: ListBody(children: <Widget>[
              FlutterLogo(size: 300),
              TextField(),
            ]),
          ),
          actions: <Widget>[
            TextButton(
              child: Text('Close'),
              onPressed: () {
                Navigator.of(context).pop();
              },
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => _launchMyDialog(context),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b22742018b (11 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.6
    • iPhone 12 (mobile)     • D72A5DAA-24E6-421B-B4F5-7CFAFB498040 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```

</details>


Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample that shows this error?
Thank you

**Comment by namangor04** [comment]
Now the error has suddenly disappeared, and I am not able to reproduce it with the same code that gave that error. Also, your code doesn't give me the error. I had updated to Flutter 2.2 after the error so that might have solved the issue I guess. Thank you for your assistance.
