### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: The image dimensions must be positive

### ISSUE THREAD

**Issue by zhonghanwen** [flutter/flutter#83341]
* Log
```
Fatal Exception: java.lang.IllegalArgumentException: The image dimensions must be positive
       at android.media.ImageReader.<init>(ImageReader.java:236)
       at android.media.ImageReader.newInstance(ImageReader.java:132)
       at io.flutter.embedding.android.FlutterImageView.createImageReader(FlutterImageView.java:19)
       at io.flutter.embedding.android.FlutterImageView.resizeIfNeeded(FlutterImageView.java:35)
       at io.flutter.embedding.android.FlutterImageView.onSizeChanged(FlutterImageView.java:27)
       at android.view.View.sizeChange(View.java:19914)
       at android.view.View.setFrame(View.java:19875)
       at android.view.View.layout(View.java:19778)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:888)
       at android.view.View.layout(View.java:19781)
       at android.view.ViewGroup.layout(ViewGroup.java:6144)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2681)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2384)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7292)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
       at android.view.Choreographer.doCallbacks(Choreographer.java:790)
       at android.view.Choreographer.doFrame(Choreographer.java:721)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

* flutter doctor -v

```
[✓] Flutter (Channel unknown, 2.0.6, on Mac OS X 10.14.5 18F132 darwin-x64, locale en-CN)
    • Flutter version 2.0.6 at /Users/zhonghanwen/flutter
    • Framework revision 1d9032c7e1 (3 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/zhonghanwen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.6.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio 2.0.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • AOSP on Shamu (mobile) • ZX1G22RP5Z • android-arm    • Android 7.1.1 (API 25)
    • MI 9 (mobile)          • e39dc1fb   • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

```

**Comment by zhonghanwen** [comment]
@TahaTesser the crash is firebase Crashlytics report.

**Comment by TahaTesser** [comment]
Hi @zhonghanwen 
Can you please your `pubspec.yaml`, the list of affected devices and if possible your `flutter run --release --verbose` running on the same OS version as the affected devices.
Thank you

**Comment by zhonghanwen** [comment]
//pubspec.yaml
```
name: com.nodetower.tahiti
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  quiver: '>=2.0.0 <3.0.0'
  dio: ^3.0.9
  json_annotation: ^2.4.0
  cupertino_icons: ^0.1.2
  fluro: 1.6.3
  rxdart: ^0.22.0
  stack_trace: ^1.9.3

  webview_flutter: ^0.3.9+1

  flutter_spinkit: ^3.1.0
  shimmer: ^1.0.0
  fluttertoast: ^3.1.3
  firebase_remote_config: ^0.3.1+1
  get_it: ^4.0.4
  firebase_crashlytics: ^0.2.1+1
  firebase_analytics: ^6.3.0
  device_info: ^1.0.0
  google_mobile_ads: 0.12.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.1
  json_serializable: ^3.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - ...

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true

```

Sorry, i don't found same os version devcies.

**Comment by zhonghanwen** [comment]
@TahaTesser Can you help me take a look at this question? https://github.com/flutter/flutter/issues/83204

**Comment by chinmaygarde** [comment]
There is no reproducible test case but the code also looks like it can be a lot more defensive [in checking for negative dimensions](https://github.com/flutter/engine/blob/05e680e202af9a92461070cb2d9982acad46c83c/shell/platform/android/io/flutter/embedding/android/FlutterImageView.java#L74).

**Comment by chinmaygarde** [comment]
cc @blasten

**Comment by zhonghanwen** [comment]
@chinmaygarde @blasten difficult to solve this problem？？？

**Comment by zhonghanwen** [comment]
A month has not solve the problem, so disappointed with flutter project.
jiu zhe!!!
jiu zhe!!!
jiu zhe!!!
