### ISSUE TITLE
Failed assertion: line 5013 pos 12: '!_debugLocked': is not true

### ISSUE THREAD

**Issue by ParikshitTiwari** [flutter/flutter#83385]
I am getting this exception when hot reload screen while i'm not calling Navigator's any function. 

```console
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#0643c](dirty, dependencies: [UnmanagedRestorationScope, HeroControllerScope], state: NavigatorState#f2b55(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5253 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp file:///D:/Flutter%20Projects/filetrackingsystem/lib/main.dart:14:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5253:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 6 of 817 libraries in 3,295ms.
```

Please help me...

**Comment by TahaTesser** [comment]
Hi @ParikshitTiwari 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
