### ISSUE TITLE
HTTPClient Invalid argument(s): No host specified in URI

### ISSUE THREAD

**Issue by michi2** [flutter/flutter#83411]
## Steps to Reproduce
I'm using an Image.network() with the parameters loadingBuilder and errorBuilder.
Everything works fine but after navigating to another page (it doesn't matter to which) the following error gets thrown:

```
======== Exception caught by image resource service ================================================
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI file:///

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2672:9)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2567:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:89:59)
#3      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:504:13)
...
Image provider: NetworkImage("", scale: 1.0)
Image key: NetworkImage("", scale: 1.0)
====================================================================================================

======== Exception caught by image resource service ================================================
The following HandshakeException was thrown resolving an image codec:
Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:359))

When the exception was thrown, this was the stack: 
Image provider: NetworkImage("https://i.stack.imgur.co", scale: 1.0)
Image key: NetworkImage("https://i.stack.imgur.co", scale: 1.0)
====================================================================================================
```

I saw on StackOverflow then that the Image.network() (also NetworkImage!) tries to get renderUrl asynchronously. Before the render Url is fetched back, it is null. NetworkImage(renderUrl ?? '') then tries to use empty string as the url and result in the exception. So I added some code to check if the Url is empty and the error does not get thrown anymore, but it still doesn't work very fine. When I for example provide just a false image url then the following error gets thrown when navigating to another page:

`myUrl.isNotEmpty ? Image.network(myUrl) : Text('Error')`

```
======== Exception caught by image resource service ================================================
The following HandshakeException was thrown resolving an image codec:
Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:359))

When the exception was thrown, this was the stack: 
Image provider: NetworkImage("https://i.stack.imgur.co", scale: 1.0)
Image key: NetworkImage("https://i.stack.imgur.co", scale: 1.0)
====================================================================================================
```

I think this exceptions shouldn't be thrown

```
[✓] Flutter (Channel dev, 2.3.0-12.1.pre, on macOS 11.3.1 20E241 darwin-x64, locale en-AT)
    • Flutter version 2.3.0-12.1.pre at /Users/michi/Coding/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9c825981c (8 days ago), 2021-05-18 14:07:52 -0700
    • Engine revision 26e217e6c3
    • Dart version 2.14.0 (build 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/michi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (1 available)
    • iPhone 11 Pro (mobile) • 56372E98-D216-4B53-9C21-53EC7133BAB0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0
      (simulator)

• No issues found!

```

**Comment by TahaTesser** [comment]
Hi @michi2 
Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
