### ISSUE TITLE
 Target debug_universal_framework failed: Exception: Failed to codesign

### ISSUE THREAD

**Issue by jezer07** [flutter/flutter#83472]
Hi, I’m encountering this error:  Target debug_universal_framework failed: Exception: Failed to codesign. When I try to run my existing project on an iOS simulator or device. I also tried to run a new flutter project but got the same error. 
My Xcode version is 12.4

## Steps to Reproduce

1. Run `flutter create bug`.
2. cd bug/
3. run  `flutter run --verbose`

**Expected results:** 
Should be able to run on an iOS device

**Actual results:**
Encountering ` Command PhaseScriptExecution failed with a nonzero exit code`
 
```

<details>
  <summary>Logs</summary>
                   /bin/sh -c /Users/jecrespo/Library/Developer/Xcode/DerivedData/Runner-ghkobsxcdrgkiybraorjcnhkgpwv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh
               ♦ /Users/jecrespo/Frameworks/flutter/bin/flutter --verbose assemble --no-version-check --output=/Users/jecrespo/Projects/bug/build/ios/Debug-iphonesimulator/ -dTargetPlatform=ios -dTargetFile=/Users/jecrespo/Projects/bug/lib/main.dart -dBuildMode=debug
               -dIosArchs=x86_64 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode=
               -dCodesignIdentity=- --ExtraGenSnapshotOptions= --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== --ExtraFrontEndOptions= debug_ios_bundle_flutter_assets
               [ +140 ms] executing: sysctl hw.optional.arm64
               [  +30 ms] Exit code 1 from: sysctl hw.optional.arm64
               [   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
               [  +12 ms] executing: [/Users/jecrespo/Frameworks/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
               [  +14 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
               [        ] b22742018b3edf16c6cadd7b76d9db5e7f9064b5
               [   +1 ms] executing: [/Users/jecrespo/Frameworks/flutter/] git tag --points-at b22742018b3edf16c6cadd7b76d9db5e7f9064b5
               [  +39 ms] Exit code 0 from: git tag --points-at b22742018b3edf16c6cadd7b76d9db5e7f9064b5
               [        ] 2.2.0
               [   +8 ms] executing: [/Users/jecrespo/Frameworks/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
               [  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
               [        ] origin/stable
               [        ] executing: [/Users/jecrespo/Frameworks/flutter/] git ls-remote --get-url origin
               [  +11 ms] Exit code 0 from: git ls-remote --get-url origin
               [        ] https://github.com/flutter/flutter.git
               [ +104 ms] executing: [/Users/jecrespo/Frameworks/flutter/] git rev-parse --abbrev-ref HEAD
               [  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
               [        ] stable
               [  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
               [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
               [ +117 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
               [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
               [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
               [   +3 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
               [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
               [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
               [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
               [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
               [  +27 ms] Initializing file store
               [   +8 ms] Done initializing file store
               [ +365 ms] Skipping target: debug_unpack_ios
               [   +2 ms] Skipping target: gen_localizations
               [ +729 ms] Skipping target: kernel_snapshot
               [   +3 ms] debug_universal_framework: Starting due to {}
               [  +14 ms] executing: sysctl hw.optional.arm64
               [   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
               [        ] sysctl: unknown oid 'hw.optional.arm64'
               [   +2 ms] executing: xcrun clang -x c -arch x86_64 /var/folders/7_/cd2nmd6s1bs1kz0j7y92_62r0000gp/T/flutter_tools.nlxiC3/flutter_tools_stub_source.WNFB37/debug_app.cc -dynamiclib -fembed-bitcode-marker -miphoneos-version-min=8.0 -Xlinker -rpath -Xlinker
               @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -install_name @rpath/App.framework/App -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -o
               /Users/jecrespo/Projects/bug/.dart_tool/flutter_build/ce9fd9db7b914526df83a56eda44dcea/App.framework/App
               [ +131 ms] Persisting file store
               [   +9 ms] Done persisting file store
               [   +7 ms] Target debug_universal_framework failed: Exception: Failed to codesign /Users/jecrespo/Projects/bug/.dart_tool/flutter_build/ce9fd9db7b914526df83a56eda44dcea/App.framework/App with identity -.
                          /Users/jecrespo/Projects/bug/.dart_tool/flutter_build/ce9fd9db7b914526df83a56eda44dcea/App.framework/App: Operation not permitted
           
                          #0      _signFramework (package:flutter_tools/src/build_system/targets/ios.dart:641:5)
                          #1      _createStubAppFramework (package:flutter_tools/src/build_system/targets/ios.dart:621:3)
                          <asynchronous suspension>
                          #2      DebugUniversalFramework.build (package:flutter_tools/src/build_system/targets/ios.dart:233:5)
                          <asynchronous suspension>
                          #3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
                          <asynchronous suspension>
                          #4      Future.wait.<anonymous closure> (dart:async/future.dart)
                          <asynchronous suspension>
                          #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
                          <asynchronous suspension>
                          #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
                          <asynchronous suspension>
                          #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
                          <asynchronous suspension>
                          #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
                          <asynchronous suspension>
                          #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
                          <asynchronous suspension>
                          #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
                          <asynchronous suspension>
                          #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
                          <asynchronous suspension>
                          #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #16     main (package:flutter_tools/executable.dart:91:3)
                          <asynchronous suspension>
           
               [  +16 ms] "flutter assemble" took 1,475ms.
               [   +4 ms] 
                          #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                          #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:335:7)
                          <asynchronous suspension>
                          #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
                          <asynchronous suspension>
                          #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
                          <asynchronous suspension>
                          #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
                          <asynchronous suspension>
                          #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
                          <asynchronous suspension>
                          #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #10     main (package:flutter_tools/executable.dart:91:3)
                          <asynchronous suspension>
           
           
               [   +3 ms] ensureAnalyticsSent: 1ms
               [   +1 ms] Running shutdown hooks
               [        ] Shutdown hooks complete
               [   +1 ms] exiting with code 1
               Command PhaseScriptExecution failed with a nonzero exit code
           
           
[  +18 ms] Could not build the application for the simulator.
[   +2 ms] Error launching application on iPhone 8.
[   +4 ms] "flutter run" took 32,372ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +67 ms] ensureAnalyticsSent: 65ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1


```
```
```

Analyzing bug...                                                        
No issues found! (ran in 3.7s)

```
```

[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-SG)
    • Flutter version 2.2.0 at /Users/jecrespo/Frameworks/flutter
    • Framework revision b22742018b (12 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jecrespo/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/jecrespo/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

</details>

**Comment by darshankawar** [comment]
From the verbose log, the error is:

`Target debug_universal_framework failed: Exception: Failed to codesign /Users/jecrespo/Projects/bug/.dart_tool/flutter_build/ce9fd9db7b914526df83a56eda44dcea/App.framework/App with identity -.
                          /Users/jecrespo/Projects/bug/.dart_tool/flutter_build/ce9fd9db7b914526df83a56eda44dcea/App.framework/App: Operation not permitted`


`-dIosArchs=x86_64` seems to be fine.


Complete command is:

`flutter --verbose assemble --no-version-check --output=/Users/jecrespo/Projects/bug/build/ios/Debug-iphonesimulator/ -dTargetPlatform=ios -dTargetFile=/Users/jecrespo/Projects/bug/lib/main.dart -dBuildMode=debug
               -dIosArchs=x86_64 -dSdkRoot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode=
               -dCodesignIdentity=- --ExtraGenSnapshotOptions= --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== --ExtraFrontEndOptions= debug_ios_bundle_flutter_assets`

may be something going on here `dEnableBitcode=
               -dCodesignIdentity=- --ExtraGenSnapshotOptions= --`

**Comment by darshankawar** [comment]
Similar variants https://github.com/flutter/flutter/issues/54146 and https://github.com/flutter/flutter/issues/80978

**Comment by darshankawar** [comment]
@jezer07 

Are you using any assets in your project ? If so, can you try to comment out the assets section from it, run `flutter clean` and try again to see if you get same error or not ?

Moreover, can you switch to latest master channel and try again to see if issue still persists or not ?

```
flutter channel master
flutter upgrade
```

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
