### ISSUE TITLE
Infra: Devicelab linux-8 machine in staging pool is offline (quarantined)

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#83486]
The linux machine in the devicelab swarming pool is offline (quarantined), saying there is no device attached.

I would like this bot to be working, so that we can test running devicelab tests using a local engine (downloaded from an isolate).  This is in order to test tip-of-tree Dart and engine in the device lab.  I can proceed with testing the recipe changes using the mac machines in the swarming pool, but we would like to run these tests on linux machines.

I do not seem to have permissions to add the infra label, or any labels, to this issue.

**Comment by keyonghan** [comment]
swarming server seems to go with python3 again.

**Comment by keyonghan** [comment]
Switched to python2, but build fails immediately once started:
```
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "virtualenv.py", line 2328, in <module>
    main()
  File "virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "virtualenv.py", line 945, in create_environment
    download=download,
  File "virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/s/w/ir/cache/vp...cf131b/bin/python2.7 - setuptools pip wheel failed with error code 2
```
Confirmed from LUCI team this is a vpython bug most likely. 

Filed crbug/1214015 to track.

**Comment by keyonghan** [comment]
A couple of issues happened on linux8.
Salt dev has been updated to use python3, and switched across different versions. However, states got installed on linux8 in between, causing some glitches.

What I have done to bring it back to online temporally:
1) bring salt back first by switching default python3 from `Python 3.8.10+chromium.17` to `python3.7`
2) reinstall latest salt states on linux8
3) manually switched swarming server from python3 to python2 (salt dev is using python3 by default, but our linux bots are blocked on fuchsia bug: 74910, which needs chromium team supporting python3)

To do:
once chromium team unblocks from upstream, we can switch back to the default python3.

Things to note:
When this bot fails a task, and gets rebooted, the default python3 may be picked up again and cause issues. But we expect the blocker will be addressed soon.

**Comment by keyonghan** [comment]
Chromium blocking bug: crbug/1198820

**Comment by godofredoc** [comment]
Removing from ticket queue as this requires a fix on chromium to support python3.

**Comment by keyonghan** [comment]
Upstream support landed, and linux 8 is working fine with python3. Closing.
