### ISSUE TITLE
[in_app_purchase] Unhandled Exception: PlatformException(storekit_duplicate_product_object) on iOS

### ISSUE THREAD

**Issue by BaranMichal25** [flutter/flutter#83521]
**Exception:**
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(storekit_duplicate_product_object, There is a pending transaction for the same product identifier. Please either wait for it to be finished or finish it manually using `completePurchase` to avoid edge cases., {applicationUsername: null, requestData: null, quantity: 1, productIdentifier: test_premium, simulatesAskToBuyInSandbox: false}, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      SKPaymentQueueWrapper.addPayment (package:in_app_purchase_ios/src/store_kit_wrappers/sk_payment_queue_wrapper.dart:91:5)
<asynchronous suspension>
#3      InAppPurchaseIosPlatform.buyNonConsumable (package:in_app_purchase_ios/src/in_app_purchase_ios_platform.dart:63:5)
<asynchronous suspension>
```

**Steps to reproduce:**
On iOS (Sandbox) when continuously calling `buyNonConsumable()` with same product, without completing the purchases.

I realise it's a mistake, but I think that the error should be handled and delivered via `purchaseStream` _or_ it should be stated in documentation of method `buyNonConsumable` that it can throw an exception. 

**Plugin version:**
`in_app_purchase: 1.0.1`

<details>
  <summary>Flutter doctor</summary>
 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
[✓] Connected device (2 available)

• No issues found!

</details>

**Comment by BaranMichal25** [comment]
Looks like it was already reported: https://github.com/flutter/flutter/issues/79473
