### ISSUE TITLE
app freezes when running with custom embedder in flutter stable 2.2

### ISSUE THREAD

**Issue by ardera** [flutter/flutter#83529]
It seems like flutter commit [`0c00942`](https://github.com/flutter/flutter/commit/0c0094257ab38a76d89096545027df24ca0ff4e4) broke something in flutter-pi. Any app I run gets stuck after the first frame. Touch events still reach the dart VM, but apparently flutter never requests a new frame using the the embedder vsync callback.

The previous engine roll commit (flutter commit `33a9d6c`) works absolutely fine however. [Here's the diff](https://github.com/flutter/engine/compare/a252ec09b74cca0f8d8d3450566bf77c77f81e8d...c4678d65a62b87649ddfce0254131569e421d6f9) between the two engine commits

The engine commits in between are vsync-related, and that'd make sense because a colleague of mine has an embedder that doesn't specify the vsync callback, and he doesn't experience the issue.

Anyone have some idea what could be going on? I can try to create a minimal example for reproducing the issue if that helps

*EDIT:* flutter doctor and reproduction steps:
```
hannes@pop-os:~/devel/flutter_sdk$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.2.0, on Linux, locale de_DE.UTF-8)
    • Flutter version 2.2.0 at /home/hannes/devel/flutter_sdk
    • Framework revision b22742018b (vor 13 Tagen), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/hannes/devel/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Chrome (web)          • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Raspberry Pi (mobile) • pi     • linux-arm64    • Raspberry Pi 4 Model B+

! Doctor found issues in 1 category.
```

**Steps to reproduce**
I have a minimal embedder reproducing the issue: [minimal embedder](https://gist.github.com/ardera/60af806830cc80f4a61451b6c333cb50). Needs to be compiled with `-lsystemd` and `-lflutter_engine` (so also make sure you have the `libsystemd-dev` package  installed)

1. build the engine with custom embedders as the target, either the 2.2 stable one or the `c4678d65a62b` one, which is the first one that shows the issue.
2. put the compiled `icudtl.dat` inside `/usr/lib` (on the device you want to run the custom embedder on)
3. compile the minimal embedder. This needs the `flutter_embedder.h` of the engine build in the same directory.
4. checkout the correct flutter SDK: `flutter channel stable` for the 2.2 stable one or `git checkout 0c00942` for the first SDK that shows the issue.
5. create a new hello world app: `flutter create hello_world`
6. inside the `onPressed` callback of the floating action button, add some print command like `print("button was pressed");`
7. build the asset bundle for that app: `flutter build bundle`
8. deploy the asset bundle to `/tmp/hello_world` on the device you want to run the embedder on:
    - for example, `rsync -a ./build/flutter_assets/ pi@raspberrypi:/tmp/hello_world`
9. run the embedder
10. If you run it, you'll see:
    1. flutter requests a frame,
    2. that frame request is responded to by the embedder
    3. flutter presents a frame
    4. flutter requests a new frame
    5. that frame request is responded to by the embedder
    6. flutter requests yet another frame
    7. that frame request is queued since the previous frame has not yet been presented
    8. nothing happens after that, flutter will never present or request anything again

EDIT: Added a minimal embedder reproducing the issue.

**Comment by TahaTesser** [comment]
Hi @ardera 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete and complete reproducible steps
Thank you

**Comment by ardera** [comment]
@TahaTesser added the info

**Comment by chinmaygarde** [comment]
I'm going to reason about the threading and vsync handling in the reproducible use case. It would also be helpful if you also pasted the thread dump from `gdb` via `thread apply all bt`.

**Comment by ardera** [comment]
Sure. This is with SDK `0c00942` and engine `c4678d6`:

<details>

```
(gdb) thread apply all bt

Thread 16 (Thread 0xad9fe3e0 (LWP 24820)):
#0  futex_reltimed_wait_cancelable (private=0, reltime=0xad9fd810, expected=0, 
    futex_word=0x31784) at ../sysdeps/unix/sysv/linux/futex-internal.h:142
#1  __pthread_cond_wait_common (abstime=0xad9fd8a4, mutex=0x2, cond=0x31758)
    at pthread_cond_wait.c:533
#2  __pthread_cond_timedwait (cond=0x31758, mutex=0x2, abstime=0xad9fd8a4)
    at pthread_cond_wait.c:667
#3  0xb5ca5ed6 in dart::Monitor::WaitMicros (this=0x31740, micros=4999999)
    at ../../../engine/src/third_party/dart/runtime/vm/os_thread_linux.cc:467
#4  0xb5c0764a in dart::MonitorLocker::WaitMicros (this=0xad9fdd4c, 
    micros=4999999)
    at ../../../engine/src/third_party/dart/runtime/vm/lockers.h:181
#5  0xb5d19794 in dart::ThreadPool::WorkerLoop (this=0x31738, worker=0x29e10)
    at ../../../engine/src/third_party/dart/runtime/vm/thread_pool.cc:183
#6  0xb5d19bee in dart::ThreadPool::Worker::Main (args=171536)
    at ../../../engine/src/third_party/dart/runtime/vm/thread_pool.cc:323
#7  0xb5ca53ae in dart::ThreadStart (data_ptr=0x28618)
    at ../../../engine/src/third_party/dart/runtime/vm/os_thread_linux.cc:153
#8  0xb5038494 in start_thread (arg=0xad9fe3e0) at pthread_create.c:486
#9  0xb5146578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 14 (Thread 0xaf6803e0 (LWP 24816)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0xb452b448) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0xb452b420) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0xb452b420, mutex=0x0) at pthread_cond_wait.c:655
#3  0xb5ca5e66 in dart::Monitor::WaitMicros (this=0xb452b408, micros=0) at ../../../engine/src/third_party/dart/runtime/vm/os_thread_linux.cc:462
#4  0xb5ca5e0c in dart::Monitor::Wait (this=0xb452b408, millis=0) at ../../../engine/src/third_party/dart/runtime/vm/os_thread_linux.cc:447
#5  0xb5be14ca in dart::MonitorLocker::Wait (this=0xaf67fc74, millis=0) at ../../../engine/src/third_party/dart/runtime/vm/lockers.h:173
#6  0xb5d27c84 in dart::BackgroundCompiler::Run (this=0xb452b400) at ../../../engine/src/third_party/dart/runtime/vm/compiler/jit/compiler.cc:1193
#7  0xb5d29728 in dart::BackgroundCompilerTask::Run (this=0xb452c718) at ../../../engine/src/third_party/dart/runtime/vm/compiler/jit/compiler.cc:1117
#8  0xb5d196d6 in dart::ThreadPool::WorkerLoop (this=0x31738, worker=0xb4540958) at ../../../engine/src/third_party/dart/runtime/vm/thread_pool.cc:158
#9  0xb5d19bee in dart::ThreadPool::Worker::Main (args=3025406296) at ../../../engine/src/third_party/dart/runtime/vm/thread_pool.cc:323
#10 0xb5ca53ae in dart::ThreadStart (data_ptr=0xb452e610) at ../../../engine/src/third_party/dart/runtime/vm/os_thread_linux.cc:153
#11 0xb5038494 in start_thread (arg=0xaf6803e0) at pthread_create.c:486
#12 0xb5146578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 9 (Thread 0xb3cfe3e0 (LWP 24809)):
#0  0xb51469d0 in epoll_wait (epfd=<optimized out>, events=0xb3cfdc30, maxevents=16, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0xb5a9cc42 in dart::bin::EventHandlerImplementation::Poll (args=176896) at ../../../engine/src/third_party/dart/runtime/bin/eventhandler_linux.cc:392
#2  0xb5ab8ffa in dart::bin::ThreadStart (data_ptr=0x2ae90) at ../../../engine/src/third_party/dart/runtime/bin/thread_linux.cc:93
#3  0xb5038494 in start_thread (arg=0xb3cfe3e0) at pthread_create.c:486
#4  0xb5146578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 8 (Thread 0xaeafe3e0 (LWP 24808)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x2aab8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0x2aa90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x2aa90, mutex=0x0) at pthread_cond_wait.c:655
#3  0xb53593a6 in std::__1::__libcpp_condvar_wait (__cv=0x2aa90, __m=0x2aa78) at ../../../engine/src/third_party/libcxx/include/__threading_support:288
#4  0xb5359364 in std::__1::condition_variable::wait (this=0x2aa90, lk=...) at ../../../engine/src/third_party/libcxx/src/condition_variable.cpp:44
#5  0xb5381eee in std::__1::condition_variable::wait<fml::ConcurrentMessageLoop::WorkerMain()::$_1>(std::__1::unique_lock<std::__1::mutex>&, fml::ConcurrentMessageLoop::WorkerMain()::$_1) (this=0x2aa90, __lk=..., __pred=...) at ../../../engine/src/third_party/libcxx/include/__mutex_base:364
#6  0xb5381d80 in fml::ConcurrentMessageLoop::WorkerMain (this=0x2aa60) at ../../../engine/src/flutter/fml/concurrent_message_loop.cc:80
#7  0xb5384176 in fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0::operator()() const (this=0x2add4) at ../../../engine/src/flutter/fml/concurrent_message_loop.cc:26
#8  0xb5384112 in std::__1::__invoke<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0> (__f=...) at ../../../engine/src/third_party/libcxx/include/type_traits:3530
#9  0xb53840d6 in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0>&, std::__1::__tuple_indices<>) (__t=...) at ../../../engine/src/third_party/libcxx/include/thread:341
#10 0xb5383dae in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0> >(void*) (__vp=0x2add0) at ../../../engine/src/third_party/libcxx/include/thread:351
#11 0xb5038494 in start_thread (arg=0xaeafe3e0) at pthread_create.c:486
#12 0xb5146578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (Thread 0xaf2ff3e0 (LWP 24807)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x2aab8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0x2aa90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x2aa90, mutex=0x0) at pthread_cond_wait.c:655
#3  0xb53593a6 in std::__1::__libcpp_condvar_wait (__cv=0x2aa90, __m=0x2aa78) at ../../../engine/src/third_party/libcxx/include/__threading_support:288
#4  0xb5359364 in std::__1::condition_variable::wait (this=0x2aa90, lk=...) at ../../../engine/src/third_party/libcxx/src/condition_variable.cpp:44
#5  0xb5381eee in std::__1::condition_variable::wait<fml::ConcurrentMessageLoop::WorkerMain()::$_1>(std::__1::unique_lock<std::__1::mutex>&, fml::ConcurrentMessageLoop::WorkerMain()::$_1) (this=0x2aa90, __lk=..., __pred=...) at ../../../engine/src/third_party/libcxx/include/__mutex_base:364
#6  0xb5381d80 in fml::ConcurrentMessageLoop::WorkerMain (this=0x2aa60) at ../../../engine/src/flutter/fml/concurrent_message_loop.cc:80
#7  0xb5384176 in fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0::operator()() const (this=0x2ad04) at ../../../engine/src/flutter/fml/concurrent_message_loop.cc:26
#8  0xb5384112 in std::__1::__invoke<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0> (__f=...) at ../../../engine/src/third_party/libcxx/include/type_traits:3530
#9  0xb53840d6 in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0>&, std::__1::__tuple_indices<>) (__t=...) at ../../../engine/src/third_party/libcxx/include/thread:341
#10 0xb5383dae in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0> >(void*) (__vp=0x2ad00) at ../../../engine/src/third_party/libcxx/include/thread:351
#11 0xb5038494 in start_thread (arg=0xaf2ff3e0) at pthread_create.c:486
#12 0xb5146578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (Thread 0xafe813e0 (LWP 24806)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x2aab8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0x2aa90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x2aa90, mutex=0x0) at pthread_cond_wait.c:655
#3  0xb53593a6 in std::__1::__libcpp_condvar_wait (__cv=0x2aa90, __m=0x2aa78) at ../../../engine/src/third_party/libcxx/include/__threading_support:288
#4  0xb5359364 in std::__1::condition_variable::wait (this=0x2aa90, lk=...) at ../../../engine/src/third_party/libcxx/src/condition_variable.cpp:44
#5  0xb5381eee in std::__1::condition_variable::wait<fml::ConcurrentMessageLoop::WorkerMain()::$_1>(std::__1::unique_lock<std::__1::mutex>&, fml::ConcurrentMessageLoop::WorkerMain()::$_1) (this=0x2aa90, __lk=..., __pred=...) at ../../../engine/src/third_party/libcxx/include/__mutex_base:364
#6  0xb5381d80 in fml::ConcurrentMessageLoop::WorkerMain (this=0x2aa60) at ../../../engine/src/flutter/fml/concurrent_message_loop.cc:80
#7  0xb5384176 in fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0::operator()() const (this=0x2ac34) at ../../../engine/src/flutter/fml/concurrent_message_loop.cc:26
#8  0xb5384112 in std::__1::__invoke<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0> (__f=...) at ../../../engine/src/third_party/libcxx/include/type_traits:3530
#9  0xb53840d6 in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0>&, std::__1::__tuple_indices<>) (__t=...) at ../../../engine/src/third_party/libcxx/include/thread:341
#10 0xb5383dae in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0> >(void*) (__vp=0x2ac30) at ../../../engine/src/third_party/libcxx/include/thread:351
#11 0xb5038494 in start_thread (arg=0xafe813e0) at pthread_create.c:486
#12 0xb5146578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0xb06823e0 (LWP 24805)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x2aab8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0x2aa90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x2aa90, mutex=0x0) at pthread_cond_wait.c:655
#3  0xb53593a6 in std::__1::__libcpp_condvar_wait (__cv=0x2aa90, __m=0x2aa78) at ../../../engine/src/third_party/libcxx/include/__threading_support:288
#4  0xb5359364 in std::__1::condition_variable::wait (this=0x2aa90, lk=...) at ../../../engine/src/third_party/libcxx/src/condition_variable.cpp:44
#5  0xb5381eee in std::__1::condition_variable::wait<fml::ConcurrentMessageLoop::WorkerMain()::$_1>(std::__1::unique_lock<std::__1::mutex>&, fml::ConcurrentMessageLoop::WorkerMain()::$_1) (this=0x2aa90, __lk=..., __pred=...) at ../../../engine/src/third_party/libcxx/include/__mutex_base:364
#6  0xb5381d80 in fml::ConcurrentMessageLoop::WorkerMain (this=0x2aa60) at ../../../engine/src/flutter/fml/concurrent_message_loop.cc:80
#7  0xb5384176 in fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0::operator()() const (this=0x2ab44) at ../../../engine/src/flutter/fml/concurrent_message_loop.cc:26
#8  0xb5384112 in std::__1::__invoke<fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0> (__f=...) at ../../../engine/src/third_party/libcxx/include/type_traits:3530
#9  0xb53840d6 in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0>&, std::__1::__tuple_indices<>) (__t=...) at ../../../engine/src/third_party/libcxx/include/thread:341
#10 0xb5383dae in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::ConcurrentMessageLoop::ConcurrentMessageLoop(unsigned int)::$_0> >(void*) (__vp=0x2ab40) at ../../../engine/src/third_party/libcxx/include/thread:351
#11 0xb5038494 in start_thread (arg=0xb06823e0) at pthread_create.c:486
#12 0xb5146578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0xb3aff3e0 (LWP 24804)):
#0  0xb51469d0 in epoll_wait (epfd=<optimized out>, events=0xb3afed40, maxevents=1, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0xb53961bc in fml::MessageLoopLinux::Run (this=0xb31005c8) at ../../../engine/src/flutter/fml/platform/linux/message_loop_linux.cc:53
#2  0xb538c35c in fml::MessageLoopImpl::DoRun (this=0xb31005c8) at ../../../engine/src/flutter/fml/message_loop_impl.cc:96
#3  0xb538be30 in fml::MessageLoop::Run (this=0xb31005b8) at ../../../engine/src/flutter/fml/message_loop.cc:49
#4  0xb53937fe in fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const (this=0x28c1c) at ../../../engine/src/flutter/fml/thread.cc:35
#5  0xb5393790 in std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> (__f=...) at ../../../engine/src/third_party/libcxx/include/type_traits:3530
#6  0xb539375e in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>) (__t=...) at ../../../engine/src/third_party/libcxx/include/thread:341
#7  0xb53935d8 in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) (__vp=0x28c18) at ../../../engine/src/third_party/libcxx/include/thread:351
#8  0xb5038494 in start_thread (arg=0xb3aff3e0) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x3f2

Thread 3 (Thread 0xb44ff3e0 (LWP 24803)):
#0  0xb51469d0 in epoll_wait (epfd=<optimized out>, events=0xb44fed40, maxevents=1, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0xb53961bc in fml::MessageLoopLinux::Run (this=0xb3b005c8) at ../../../engine/src/flutter/fml/platform/linux/message_loop_linux.cc:53
#2  0xb538c35c in fml::MessageLoopImpl::DoRun (this=0xb3b005c8) at ../../../engine/src/flutter/fml/message_loop_impl.cc:96
#3  0xb538be30 in fml::MessageLoop::Run (this=0xb3b005b8) at ../../../engine/src/flutter/fml/message_loop.cc:49
#4  0xb53937fe in fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const (this=0x28abc) at ../../../engine/src/flutter/fml/thread.cc:35
#5  0xb5393790 in std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> (__f=...) at ../../../engine/src/third_party/libcxx/include/type_traits:3530
#6  0xb539375e in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>) (__t=...) at ../../../engine/src/third_party/libcxx/include/thread:341
#7  0xb53935d8 in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) (__vp=0x28ab8) at ../../../engine/src/third_party/libcxx/include/thread:351
#8  0xb5038494 in start_thread (arg=0xb44ff3e0) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x3f2

Thread 2 (Thread 0xb4e0a3e0 (LWP 24802)):
#0  0xb51469d0 in epoll_wait (epfd=<optimized out>, events=0xb4e09d40, maxevents=1, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
#1  0xb53961bc in fml::MessageLoopLinux::Run (this=0xb45005c8) at ../../../engine/src/flutter/fml/platform/linux/message_loop_linux.cc:53
#2  0xb538c35c in fml::MessageLoopImpl::DoRun (this=0xb45005c8) at ../../../engine/src/flutter/fml/message_loop_impl.cc:96
#3  0xb538be30 in fml::MessageLoop::Run (this=0xb45005b8) at ../../../engine/src/flutter/fml/message_loop.cc:49
#4  0xb53937fe in fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const (this=0x28954) at ../../../engine/src/flutter/fml/thread.cc:35
#5  0xb5393790 in std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> (__f=...) at ../../../engine/src/third_party/libcxx/include/type_traits:3530
#6  0xb539375e in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>) (__t=...) at ../../../engine/src/third_party/libcxx/include/thread:341
#7  0xb53935d8 in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) (__vp=0x28950) at ../../../engine/src/third_party/libcxx/include/thread:351
#8  0xb5038494 in start_thread (arg=0xb4e0a3e0) at pthread_create.c:486
Backtrace stopped: Cannot access memory at address 0x3f2

Thread 1 (Thread 0xb6ff5010 (LWP 24789)):
#0  __GI___select (timeout=0x0, exceptfds=0xbefff170, writefds=0xbefff170, readfds=0xbefff170, nfds=5) at ../sysdeps/unix/sysv/linux/select.c:41
#1  __GI___select (nfds=5, readfds=0xbefff170, writefds=0xbefff170, exceptfds=0xbefff170, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:37
#2  0x00011dc4 in main (argc=1, argv=0xbefff4e4) at ./minimal.c:468
```

</details>

**Comment by ardera** [comment]
Btw, I also experienced similiar hangups starting from flutter 2.0 sometimes when a window metrics event was sent at runtime. Those hangups looked exactly the same as the one in this issue. The engine requested a frame, embedder responded, engine didn't draw anything, then requested another frame, and then nothing ever happens after. Didn't happen too often though. Sometimes it would happen after the 2nd window metrics event sent to the engine, sometimes after the 20th, so probably some kind of race condition. Don't have a reproduction steps for that though

**Comment by HidenoriMatsubayashi** [comment]
I can easily reproduce the same issue when I use the flutter gallery app, too. It doesn't seem to freeze without using the Vsync callback. 
https://user-images.githubusercontent.com/62131389/122492305-7c6d4980-d020-11eb-9023-346c76fdb4f8.mov

**Comment by HidenoriMatsubayashi** [comment]
@ardera 

I tried to reproduce the issue using Flutter 2.5.0-5.2.pre (7a4c4505f6a7a1aa758d62b58150dce43cfa473f) version, but I couldn't. Can you still reproduce it now?
