### ISSUE TITLE
Stream has been disposed

### ISSUE THREAD

**Issue by joy2helloworld** [flutter/flutter#83545]
code：
```
InkWell(
            child: Container(
                child: _value
                    ? Image.asset("packages/flutter_base_plugin/assets/images/ic_switch_on.png", width: 52, height: 28)
                    : Image.asset("packages/flutter_base_plugin/assets/images/ic_switch_off.png",
                        width: 52, height: 28)),
            onTap: () {
              _value=!_value;
              setState(() {
              });
            },
          )
```
![image](https://user-images.githubusercontent.com/8622657/119945581-3b0cef80-bfc8-11eb-822b-bfbda0dceb82.png)

An exception will be reported when switching back and forth :

```
Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.

The relevant error-causing widget was: 
  Container file:///xxxx/wd_cell.dart:50:20
When the exception was thrown, this was the stack: 
#0      ImageStreamCompleter._checkDisposed (package:flutter/src/painting/image_stream.dart:583:7)
#1      ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:499:5)
#2      MultiFrameImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:978:11)
#3      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:367:26)
#4      _ImageState._listenToStream (package:flutter/src/widgets/image.dart:1255:19)

flutter doctor：
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.3 19D76 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ✗ Xcode 11.7.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.


```

**Comment by darshankawar** [comment]
@joy2helloworld 
Tried your code sample on latest stable, but wasn't able to replicate the issue:

```
return Scaffold(
      body: Center(
          child: InkWell(
            child: Container(
                child: _value ? Image.asset('assets/image.png', width: 52,height: 28) : Image.asset('assets/flutterlogo.png', width: 52, height: 28)
            ),
            onTap: () {
              _value=!_value;
              setState(() {

              });
            },
          )
      ),
    );
```

I see a Switch button in your screenshot, which I didn't use in updated code sample as shown above. If my sample looks incomplete, can you provide a complete minimal code that involves switch widget, so that I can try that and verify ?

**Comment by joy2helloworld** [comment]
> @joy2helloworld
> Tried your code sample on latest stable, but wasn't able to replicate the issue:
> 
> ```
> return Scaffold(
>       body: Center(
>           child: InkWell(
>             child: Container(
>                 child: _value ? Image.asset('assets/image.png', width: 52,height: 28) : Image.asset('assets/flutterlogo.png', width: 52, height: 28)
>             ),
>             onTap: () {
>               _value=!_value;
>               setState(() {
> 
>               });
>             },
>           )
>       ),
>     );
> ```
> 
> I see a Switch button in your screenshot, which I didn't use in updated code sample as shown above. If my sample looks incomplete, can you provide a complete minimal code that involves switch widget, so that I can try that and verify ?

Sorry, my mistake, replacing ImageCache in my project caused the exception

**Comment by darshankawar** [comment]
@joy2helloworld 
Does that mean your issue is resolved or no ?

**Comment by joy2helloworld** [comment]
> @joy2helloworld
> Does that mean your issue is resolved or no ?

Yes it has been resolved

**Comment by darshankawar** [comment]
Thanks for confirming. Closing based on above comment.
