### ISSUE TITLE
flutter not wok on windows.  Error pub get failed (1; The system cannot find the path specified.)

### ISSUE THREAD

**Issue by tnikolai2** [flutter/flutter#83583]
flutter upgrade
```console
The system cannot find the path specified.
The system cannot find the path specified.
Flutter is already up to date on channel stable
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (34 hours ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

flutter packages get -v

<details> 
<summary>logs</summary> 
	
```console
The system cannot find the path specified.
The system cannot find the path specified.
[  +62 ms] executing: [E:\g\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] executing: [E:\g\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +42 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] 2.2.1
[   +4 ms] executing: [E:\g\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [E:\g\flutter/] git ls-remote --get-url origin
[  +29 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +98 ms] executing: [E:\g\flutter/] git rev-parse --abbrev-ref HEAD
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +71 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +40 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +86 ms] Running "flutter pub get" in f1...
[   +9 ms] executing: [E:\g\flutterPRG\f1/] E:\g\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose get --no-precompile
[  +35 ms] The system cannot find the path specified.
[  +30 ms] The system cannot find the path specified.
[  +75 ms] FINE: Pub 2.13.1
[  +45 ms] MSG : Resolving dependencies...
[  +21 ms] SLVR: fact: f1 is 1.0.0+1
[   +5 ms] SLVR: derived: f1
[  +21 ms] SLVR: fact: f1 depends on flutter any from sdk
[   +1 ms] SLVR: fact: f1 depends on cupertino_icons ^1.0.2
[        ] SLVR: fact: f1 depends on flutter_test any from sdk
[        ] SLVR:   selecting f1
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: cupertino_icons ^1.0.2
[        ] SLVR:   derived: flutter any from sdk
[   +7 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on test_api 0.3.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on path 1.8.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on fake_async 1.2.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on clock 1.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.10.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on vector_math 2.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on async 2.6.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on boolean_selector 2.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on characters 1.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on charcode 1.2.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on collection 1.15.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.10
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on meta 1.3.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on source_span 1.8.1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.2.0
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on typed_data 1.3.0
[   +1 ms] SLVR:     selecting flutter_test 0.0.0 from sdk
[        ] SLVR:     derived: typed_data 1.3.0
[        ] SLVR:     derived: term_glyph 1.2.0
[        ] SLVR:     derived: string_scanner 1.1.0
[        ] SLVR:     derived: stream_channel 2.1.0
[   +1 ms] SLVR:     derived: source_span 1.8.1
[        ] SLVR:     derived: meta 1.3.0
[        ] SLVR:     derived: matcher 0.12.10
[        ] SLVR:     derived: collection 1.15.0
[        ] SLVR:     derived: charcode 1.2.0
[        ] SLVR:     derived: characters 1.1.0
[   +1 ms] SLVR:     derived: boolean_selector 2.1.0
[        ] SLVR:     derived: async 2.6.1
[        ] SLVR:     derived: vector_math 2.1.0
[        ] SLVR:     derived: stack_trace 1.10.0
[        ] SLVR:     derived: clock 1.1.0
[        ] SLVR:     derived: fake_async 1.2.0
[        ] SLVR:     derived: path 1.8.0
[   +1 ms] SLVR:     derived: test_api 0.3.0
[        ] SLVR:       selecting cupertino_icons 1.0.3
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on characters 1.1.0
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on collection 1.15.0
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on meta 1.3.0
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on typed_data 1.3.0
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on vector_math 2.1.0
[        ] SLVR:       fact: flutter 0.0.0 from sdk depends on sky_engine any from sdk
[        ] SLVR:         selecting flutter 0.0.0 from sdk
[        ] SLVR:         derived: sky_engine any from sdk
[        ] SLVR:         fact: typed_data 1.3.0 depends on collection ^1.15.0
[        ] SLVR:           selecting typed_data 1.3.0
[   +1 ms] SLVR:             selecting term_glyph 1.2.0
[   +3 ms] SLVR:             fact: string_scanner 1.1.0 depends on charcode ^1.2.0
[        ] SLVR:             fact: string_scanner 1.1.0 depends on source_span ^1.8.0
[        ] SLVR:               selecting string_scanner 1.1.0
[   +2 ms] SLVR:               fact: stream_channel 2.1.0 depends on async ^2.5.0
[        ] SLVR:                 selecting stream_channel 2.1.0
[   +2 ms] SLVR:                 fact: source_span 1.8.1 depends on collection ^1.15.0
[        ] SLVR:                 fact: source_span 1.8.1 depends on path ^1.8.0
[        ] SLVR:                 fact: source_span 1.8.1 depends on term_glyph ^1.2.0
[        ] SLVR:                   selecting source_span 1.8.1
[   +1 ms] SLVR:                     selecting meta 1.3.0
[   +3 ms] SLVR:                     fact: matcher 0.12.10 depends on stack_trace ^1.10.0
[   +1 ms] SLVR:                       selecting matcher 0.12.10
[   +3 ms] SLVR:                         selecting collection 1.15.0
[   +4 ms] SLVR:                           selecting charcode 1.2.0
[   +3 ms] SLVR:                             selecting characters 1.1.0
[   +3 ms] SLVR:                             fact: boolean_selector 2.1.0 depends on source_span ^1.8.0
[        ] SLVR:                             fact: boolean_selector 2.1.0 depends on string_scanner ^1.1.0
[        ] SLVR:                               selecting boolean_selector 2.1.0
[   +3 ms] SLVR:                               fact: async 2.6.1 depends on meta ^1.1.7
[        ] SLVR:                               fact: async 2.6.1 depends on collection ^1.15.0
[        ] SLVR:                                 selecting async 2.6.1
[   +1 ms] SLVR:                                   selecting vector_math 2.1.0
[   +3 ms] SLVR:                                   fact: stack_trace 1.10.0 depends on path ^1.8.0
[   +1 ms] SLVR:                                     selecting stack_trace 1.10.0
[   +1 ms] SLVR:                                       selecting clock 1.1.0
[   +2 ms] SLVR:                                       fact: fake_async 1.2.0 depends on clock ^1.1.0
[        ] SLVR:                                       fact: fake_async 1.2.0 depends on collection ^1.15.0
[        ] SLVR:                                         selecting fake_async 1.2.0
[        ] SLVR:                                           selecting path 1.8.0
[   +2 ms] SLVR:                                           fact: test_api 0.3.0 depends on async ^2.5.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on boolean_selector ^2.1.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on collection ^1.15.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on meta ^1.3.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on path ^1.8.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on source_span ^1.8.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on stack_trace ^1.10.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on stream_channel ^2.1.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on string_scanner ^1.1.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on term_glyph ^1.2.0
[        ] SLVR:                                           fact: test_api 0.3.0 depends on matcher >=0.12.10 <0.12.11
[        ] SLVR:                                             selecting test_api 0.3.0
[        ] SLVR:                                               selecting sky_engine 0.0.99 from sdk
[  +92 ms] SLVR: Version solving took 0:00:00.226746 seconds.
[   +1 ms]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (0.247s).
[  +63 ms] MSG :   async 2.6.1 (2.7.0 available)
[   +1 ms]     |   meta 1.3.0 (1.4.0 available)
[        ]     |   test_api 0.3.0 (0.4.0 available)
[  +33 ms] IO  : Writing 3440 characters to text file .\pubspec.lock.
[   +1 ms] FINE: Contents:
[        ]     | # Generated by pub
[        ]     | # See https://dart.dev/tools/pub/glossary#lockfile
[        ]     | packages:
[        ]     |   async:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: async
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[   +1 ms]     |     version: "2.6.1"
[        ]     |   boolean_selector:
[   +1 ms]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: boolean_selector
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.1.0"
[        ]     |   characters:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: characters
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0"
[        ]     |   charcode:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: charcode
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.2.0"
[        ]     |   clock:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: clock
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0"
[        ]     |   collection:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: collection
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.15.0"
[        ]     |   cupertino_icons:
[        ]     |     dependency: "direct main"
[        ]     |     description:
[        ]     |       name: cupertino_icons
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.0.3"
[        ]     |   fake_async:
[        ]     |     dependency: transitive
[        ]     |     description:
[   +1 ms]     |       name: fake_async
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.2.0"
[        ]     |   flutter:
[        ]     |     dependency: "direct main"
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.0"
[        ]     |   flutter_test:
[        ]     |     dependency: "direct dev"
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.0"
[        ]     |   matcher:
[        ]     |     dependency: transitive
[   +1 ms]     |     description:
[        ]     |       name: matcher
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[   +1 ms]     |     version: "0.12.10"
[        ]     |   meta:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: meta
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.3.0"
[        ]     |   path:
[        ]     |     dependency: transitive
[        ]     |     description:
[   +1 ms]     |       name: path
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.8.0"
[        ]     |   sky_engine:
[        ]     |     dependency: transitive
[        ]     |     description: flutter
[        ]     |     source: sdk
[        ]     |     version: "0.0.99"
[        ]     |   source_span:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: source_span
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.8.1"
[        ]     |   stack_trace:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: stack_trace
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.10.0"
[        ]     |   stream_channel:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: stream_channel
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.1.0"
[        ]     |   string_scanner:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: string_scanner
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.1.0"
[        ]     |   term_glyph:
[        ]     |     dependency: transitive
[        ]     |     description:
[   +1 ms]     |       name: term_glyph
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.2.0"
[        ]     |   test_api:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: test_api
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "0.3.0"
[        ]     |   typed_data:
[   +1 ms]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: typed_data
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "1.3.0"
[        ]     |   vector_math:
[        ]     |     dependency: transitive
[        ]     |     description:
[        ]     |       name: vector_math
[        ]     |       url: "https://pub.dartlang.org"
[        ]     |     source: hosted
[        ]     |     version: "2.1.0"
[        ]     | sdks:
[        ]     |   dart: ">=2.12.0 <3.0.0"
[        ] IO  : Writing 2326 characters to text file .\.packages.
[        ] FINE: Contents:
[        ]     | # This file is deprecated. Tools should instead consume 
[        ]     | # `.dart_tools/package_config.json`.
[        ]     | # 
[        ]     | # For more info see: https://dart.dev/go/dot-packages-deprecation
[        ]     | # 
[        ]     | # Generated by pub on 2021-05-29 08:46:10.419219.
[        ]     | async:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/async-2.6.1/lib/
[        ]     | boolean_selector:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/boolean_selector-2.1.0/lib/
[        ]     | characters:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/characters-1.1.0/lib/
[        ]     | charcode:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/charcode-1.2.0/lib/
[        ]     | clock:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/clock-1.1.0/lib/
[        ]     | collection:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/collection-1.15.0/lib/
[        ]     | cupertino_icons:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/cupertino_icons-1.0.3/lib/
[        ]     | fake_async:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fake_async-1.2.0/lib/
[        ]     | flutter:file:///E:/g/flutter/packages/flutter/lib/
[        ]     | flutter_test:file:///E:/g/flutter/packages/flutter_test/lib/
[        ]     | matcher:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/matcher-0.12.10/lib/
[        ]     | meta:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/meta-1.3.0/lib/
[        ]     | path:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/path-1.8.0/lib/
[   +1 ms]     | sky_engine:file:///E:/g/flutter/bin/cache/pkg/sky_engine/lib/
[        ]     | source_span:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/source_span-1.8.1/lib/
[        ]     | stack_trace:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/stack_trace-1.10.0/lib/
[        ]     | stream_channel:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/stream_channel-2.1.0/lib/
[        ]     | string_scanner:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/string_scanner-1.1.0/lib/
[        ]     | term_glyph:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/term_glyph-1.2.0/lib/
[        ]     | test_api:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/test_api-0.3.0/lib/
[        ]     | typed_data:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/typed_data-1.3.0/lib/
[        ]     | vector_math:file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/vector_math-2.1.0/lib/
[        ]     | f1:lib/
[        ] MSG : Got dependencies!
[   +1 ms] IO  : Writing 4674 characters to text file .\.dart_tool\package_config.json.
[        ] FINE: Contents:
[   +1 ms]     | {
[        ]     |   "configVersion": 2,
[        ]     |   "packages": [
[        ]     |     {
[        ]     |       "name": "async",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/async-2.6.1",
[   +2 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "boolean_selector",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/boolean_selector-2.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[   +1 ms]     |     },
[        ]     |     {
[        ]     |       "name": "characters",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/characters-1.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "charcode",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/charcode-1.2.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "clock",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/clock-1.1.0",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "collection",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/collection-1.15.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "cupertino_icons",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/cupertino_icons-1.0.3",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "fake_async",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fake_async-1.2.0",
[        ]     |       "packageUri": "lib/",
[   +1 ms]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "flutter",
[        ]     |       "rootUri": "file:///E:/g/flutter/packages/flutter",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[   +1 ms]     |     {
[        ]     |       "name": "flutter_test",
[        ]     |       "rootUri": "file:///E:/g/flutter/packages/flutter_test",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[   +1 ms]     |     {
[        ]     |       "name": "matcher",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/matcher-0.12.10",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "meta",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/meta-1.3.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "path",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/path-1.8.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[   +1 ms]     |     {
[        ]     |       "name": "sky_engine",
[        ]     |       "rootUri": "file:///E:/g/flutter/bin/cache/pkg/sky_engine",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "source_span",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/source_span-1.8.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[   +1 ms]     |       "name": "stack_trace",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/stack_trace-1.10.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "stream_channel",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/stream_channel-2.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "string_scanner",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/string_scanner-1.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[   +1 ms]     |     },
[        ]     |     {
[        ]     |       "name": "term_glyph",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/term_glyph-1.2.0",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "test_api",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/test_api-0.3.0",
[  +10 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[   +3 ms]     |     },
[        ]     |     {
[        ]     |       "name": "typed_data",
[   +2 ms]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/typed_data-1.3.0",
[   +1 ms]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "vector_math",
[        ]     |       "rootUri": "file:///C:/Users/kol/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/vector_math-2.1.0",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[        ]     |     },
[        ]     |     {
[   +1 ms]     |       "name": "f1",
[        ]     |       "rootUri": "../",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.12"
[   +1 ms]     |     }
[        ]     |   ],
[        ]     |   "generated": "2021-05-29T05:46:10.476067Z",
[        ]     |   "generator": "pub",
[        ]     |   "generatorVersion": "2.13.1"
[        ]     | }
[  +13 ms] Running "flutter pub get" in f1... (completed in 747ms)
[   +1 ms] "flutter get" took 910ms.
[   +4 ms] pub get failed (1;     | })
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:323:7)
           <asynchronous suspension>
           #2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:223:7)
           <asynchronous suspension>
           #3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:133:7)
           <asynchronous suspension>
           #4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:166:5)
           <asynchronous suspension>
           #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #13     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +158 ms] ensureAnalyticsSent: 156ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

**Comment by TahaTesser** [comment]
Hi @tnikolai2 
This seems to be an issue with `pub`, see https://github.com/flutter/flutter/issues/78773
Please open the issue in the dedicated [repository](https://github.com/dart-lang/pub).
Closing, as this isn't an issue with Flutter itself.  
Thank you
