### ISSUE TITLE
Navigator.dart: Failed assertion: line 4709 pos 12: '!_debugLocked': on hot reload and on Navigator.push

### ISSUE THREAD

**Issue by LuigiSavino** [flutter/flutter#83598]
STEP TO REPRODUCE (Only debug mode):
Click on this button in debug mode:

```
_bottomButton() =>
      FloatingActionButton(
          backgroundColor: Colors.black,
          child: Badge(
              showBadge: UIData.number_of_products > 0,
              badgeContent: Text(UIData.number_of_products.toString()),
              badgeColor: Colors.green,
              child: Icon(Icons.shopping_cart, color: Colors.white,)),
          onPressed: () {
            Navigator.pushReplacement(
                context, MaterialPageRoute(builder: (context) => CartPage())).then((value_of_cart) {setState(() {
            });});});
```
 or...
Hot reload anywhere
BUG 

```
W/ple.app_comand(12464): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
[        ] W/ple.app_comand(12464): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[        ] W/ple.app_comand(12464): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[+6995 ms] 
                    ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
                    The following assertion was thrown while handling a gesture:
                    'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4709 pos 12: '!_debugLocked':
                    is not true.
                    
                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md
                    
                    When the exception was thrown, this was the stack:
                    #2      NavigatorState._pushReplacementEntry (package:flutter/src/widgets/navigator.dart:4709:12)
                    #3      NavigatorState.pushReplacement (package:flutter/src/widgets/navigator.dart:4650:5)
                    #4      Navigator.pushReplacement (package:flutter/src/widgets/navigator.dart:2238:34)
                    #5      _MenuPageState._bottomButton.<anonymous closure> (package:app_comande/screens/menu_page.dart:76:23)
                    #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
                    #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
                    #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
                    #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
                    #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
                    #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
                    #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
                    #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
                    #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
                    #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
                    #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
                    #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
                    #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
                    #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
                    #20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
                    #21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
                    #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
                    #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
                    #27     _invoke1 (dart:ui/hooks.dart:182:10)
                    #28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
                    #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
                    (elided 5 frames from class _AssertionError and dart:async)
                    
                    Handler: "onTap"
                    Recognizer:
                      TapGestureRecognizer#01b1a
```

```
```
Flutter Analyze
```
      info • The value of the local variable 'count' isn't used • lib/screens/cart_page.dart:28:25 • unused_local_variable
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.26.0-18.0.pre.
          • lib/screens/cart_page.dart:177:30 • deprecated_member_use
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.26.0-18.0.pre.
          • lib/screens/cart_page.dart:207:20 • deprecated_member_use
   info • Unused import: 'package:flutter/scheduler.dart' • lib/screens/detail_page.dart:4:8 • unused_import
   info • The declaration '_colorWidget' isn't referenced • lib/screens/detail_page.dart:137:10 • unused_element
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.26.0-18.0.pre.
          • lib/screens/detail_page.dart:170:11 • deprecated_member_use
   info • Name non-constant identifiers using lowerCamelCase • lib/screens/detail_page.dart:183:28 • non_constant_identifier_names
   info • Unused import: 'package:flutter/foundation.dart' • lib/screens/home_page.dart:3:8 • unused_import
   info • The operand can't be null, so the condition is always true • lib/screens/home_page.dart:35:16 • unnecessary_null_comparison
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MenuPage.barcode • lib/screens/menu_page.dart:10:7 •
          must_be_immutable
   info • Name non-constant identifiers using lowerCamelCase • lib/screens/menu_page.dart:77:85 • non_constant_identifier_names
   info • 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. •
          lib/utils/app_theme.dart:26:7 • deprecated_member_use
   info • 'subtitle' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is subtitle2. This feature was deprecated after v1.13.8. •
          lib/utils/app_theme.dart:30:7 • deprecated_member_use
   info • 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature was deprecated after v1.13.8. •
          lib/utils/app_theme.dart:58:7 • deprecated_member_use
   info • 'subtitle' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is subtitle2. This feature was deprecated after v1.13.8. •
          lib/utils/app_theme.dart:62:7 • deprecated_member_use
   info • Unused import: 'package:flutter/material.dart' • lib/utils/uidata.dart:6:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/uidata.dart:24:23 • non_constant_identifier_names
   info • Avoid using braces in interpolation when not needed • lib/utils/uidata.dart:28:66 • unnecessary_brace_in_string_interps
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/uidata.dart:32:15 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/uidata.dart:34:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/uidata.dart:36:14 • non_constant_identifier_names
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Product.item • lib/widgets/product.dart:12:7 • must_be_immutable
   info • 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after
          v1.26.0-18.0.pre. • lib/widgets/product.dart:144:23 • deprecated_member_use
```

**Flutter doctor**

```
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale it_IT.UTF-8)
    • Flutter version 2.2.1 at /home/luigi/Developement/flutter
    • Framework revision 02c026b03c (2 giorni fa), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/luigi/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • Mi 9T Pro (mobile) • 22318ab2 • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 91.0.4472.7
```

**Comment by LuigiSavino** [comment]
For which concern the android license i get another error:
```
flutter doctor --android-licenses                                                                                                                                       64 ✘ 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

**Comment by TahaTesser** [comment]
Hi @LuigiSavino
Can you please try running the codes sample below and try the reproduce the issue 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(

          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          Navigator.pushReplacement(
                  context, MaterialPageRoute(builder: (context) => CartPage()))
              .then((value_of_cart) {
            setState(() {});
          });
        },
      ),
    );
  }
}

class CartPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
    );
  }
}

``` 

</details>

If the problem persists, can you please provide your `flutter doctor -v` complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by LuigiSavino** [comment]
Hi @TahaTesser, thanks for your response. The problem seems to be fixed in your code but when i try using the pushReplacement in my code the problem persists.
How should I do?

**Comment by TahaTesser** [comment]
Hi @LuigiSavino 
It must be something from your code that causing the issue, please try to isolate the code
Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by LuigiSavino** [comment]
Hi @TahaTesser ,
I noticed that the code that generates the error is the HomePageScreen

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:app_comande/screens/menu_page.dart';
import 'package:app_comande/utils/uidata.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';

class HomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late Barcode result;
  late QRViewController controller;
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');

  // In order to get hot reload to work we need to pause the camera if the platform
  // is android, or resume the camera if the platform is iOS.
  @override
  void reassemble() {
    super.reassemble();
    if (Platform.isAndroid) {
      controller.pauseCamera();
    }
    controller.resumeCamera();
  }

  @override
  Widget build(BuildContext context) {
    try {
      if (result != null)
        Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) =>
                    MenuPage(UIData.restaurant, UIData.table)));
      else {
        return Scaffold(
          body: Column(
            children: <Widget>[Expanded(flex: 4, child: _buildQrView(context))],
          ),
        );
      }
    } finally {
      // ignore: control_flow_in_finally
      return Scaffold(
        body: Column(
          children: <Widget>[Expanded(flex: 4, child: _buildQrView(context))],
        ),
      );
    }
  }

  Widget _buildQrView(BuildContext context) {
    // For this example we check how width or tall the device is and change the scanArea and overlay accordingly.
    var scanArea = (MediaQuery.of(context).size.width < 400 ||
            MediaQuery.of(context).size.height < 400)
        ? 150.0
        : 300.0;
    // To ensure the Scanner view is properly sizes after rotation
    // we need to listen for Flutter SizeChanged notification and update controller
    return QRView(
      key: qrKey,
      onQRViewCreated: _onQRViewCreated,
      overlay: QrScannerOverlayShape(
          borderColor: Colors.blue,
          borderRadius: 10,
          borderLength: 30,
          borderWidth: 10,
          cutOutSize: scanArea),
    );
  }

  void _onQRViewCreated(QRViewController controller) {
    setState(() {
      this.controller = controller;
    });
    controller.scannedDataStream.listen((scanData) {
      setState(() {
        result = scanData;
        print(result.code.substring(0, result.code.indexOf('/')));
        print(result.code.substring(result.code.indexOf('/')+1));
        UIData.restaurant = result.code.substring(0, result.code.indexOf('/'));
        UIData.table = result.code.substring(result.code.indexOf('/')+1);
      });
    });
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}
```

Do you have any idea of the reason why the QRCode generates this error?

**Comment by TahaTesser** [comment]
Hi @LuigiSavino 
Your code is using third-party package, if you can reproduce the issue without third-party package then it would be a Flutter issue, if not, please file an issue on package's GitHub

**Comment by LuigiSavino** [comment]
Ok, thank you @TahaTesser
