### ISSUE TITLE
Focusing TextField with autofillHint on web throws exception

### ISSUE THREAD

**Issue by stx** [flutter/flutter#83618]
Focusing a TextField with an autofillHint (maybe just email, not sure) on web throws this exception on master:

**LateInitializationError: Local 'command' has not been initialized.**

## Steps to Reproduce

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(
          keyboardType: TextInputType.emailAddress,
          autofillHints: const <String>[
            AutofillHints.email,
          ],
        ),
      ),
    );
  }
}
```

Start debugging and tap the TextField in Chrome.

<details>
  <summary>Logs</summary>

```
Error: LateInitializationError: Local 'command' has not been initialized.
    at Object.throw_ [as throw] (http://localhost:49510/dart_sdk.js:5054:11)
    at command$35get (http://localhost:49510/dart_sdk.js:173250:41)
    at _engine.TextEditingChannel.new.handleTextInput (http://localhost:49510/dart_sdk.js:173327:41)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:49510/dart_sdk.js:161897:39)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:49510/dart_sdk.js:161764:33)
    at _DefaultBinaryMessenger.send (http://localhost:49510/packages/flutter/src/services/system_channels.dart.lib.js:2057:38)
    at OptionalMethodChannel._invokeMethod (http://localhost:49510/packages/flutter/src/services/system_channels.dart.lib.js:921:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:49510/dart_sdk.js:37456:34)
    at Object._async [as async] (http://localhost:49510/dart_sdk.js:37487:7)
    at OptionalMethodChannel.[_invokeMethod]
    (http://localhost:49510/packages/flutter/src/services/system_channels.dart.lib.js:919:20)
    at OptionalMethodChannel.[_invokeMethod]
    (http://localhost:49510/packages/flutter/src/services/system_channels.dart.lib.js:1012:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:49510/packages/flutter/src/services/system_channels.dart.lib.js:1008:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:49510/dart_sdk.js:37456:34)
    at Object._async [as async] (http://localhost:49510/dart_sdk.js:37487:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:49510/packages/flutter/src/services/system_channels.dart.lib.js:1007:20)
    at text_input.TextInput.__.[_requestAutofill]
    (http://localhost:49510/packages/flutter/src/services/text_input.dart.lib.js:1322:22)
    at text_input.TextInputConnection.__.requestAutofill
    (http://localhost:49510/packages/flutter/src/services/text_input.dart.lib.js:1060:55)
    at editable_text.EditableTextState.new.[_openInputConnection]
    (http://localhost:49510/packages/flutter/src/widgets/widget_span.dart.lib.js:46540:58)
    at editable_text.EditableTextState.new.[_openOrCloseInputConnectionIfNeeded]
    (http://localhost:49510/packages/flutter/src/widgets/widget_span.dart.lib.js:46562:39)
    at editable_text.EditableTextState.new.[_handleFocusChanged]
    (http://localhost:49510/packages/flutter/src/widgets/widget_span.dart.lib.js:46772:52)
    at focus_manager.FocusNode.new.notifyListeners
    (http://localhost:49510/packages/flutter/src/foundation/change_notifier.dart.lib.js:138:31)
    at focus_manager.FocusNode.new.[_notify] (http://localhost:49510/packages/flutter/src/widgets/widget_span.dart.lib.js:49649:12)
    at focus_manager.FocusManager.new.[_applyFocusChange]
    (http://localhost:49510/packages/flutter/src/widgets/widget_span.dart.lib.js:50368:26)
    at Object._microtaskLoop (http://localhost:49510/dart_sdk.js:37560:13)
    at _startMicrotaskLoop (http://localhost:49510/dart_sdk.js:37566:13)
    at http://localhost:49510/dart_sdk.js:33316:9
```

```
```

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.120, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.120 at /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c42ec8592f (27 hours ago), 2021-05-28 22:34:02 -0400
    • Engine revision aca8aa2335
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • Apollo (mobile) • da060dc78ac99566c39cb688206b34cb424a5ee1 • ios            • iOS 14.5.1
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 91.0.4472.77

! Doctor found issues in 1 category.
```

</details>

**Comment by hellochenwang** [comment]
I'm having the same issue.

**Comment by cedvdb** [comment]
same issue can be seen under dev branch here:

https://github.com/cedvdb/phone_form_field/tree/dev

**Comment by semsturgut** [comment]
same here 😕

**Comment by cedvdb** [comment]
Someone mind reopening ? Alternatively I'll create a new issue

**Comment by cedvdb** [comment]
@semsturgut  I opened a new one https://github.com/flutter/flutter/issues/87343
