### ISSUE TITLE
after upgrade flutter latest version still failed builing apk

### ISSUE THREAD

**Issue by denisciala** [flutter/flutter#83624]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s Command: D:\development\qc_opname1\android\gradlew.bat, OS error code: 1
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      flavorUndefinedHandler.<anonymous closure> (package:flutter_tools/src/android/gradle_errors.dart:294:38)
<asynchronous suspension>
#3      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:469:42)
<asynchronous suspension>
#4      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:231:5)
<asynchronous suspension>
#5      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.10586], locale en-ID)
    • Flutter version 2.2.1 at D:\development\flutter
    • Framework revision 02c026b03c (3 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\development\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\development\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\user\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2e540931f73593e35627592ca4f9a4ca3035ed31
### Plugins
flutter_plugin_android_lifecycle-1.0.11
google_maps_flutter-0.5.33
image_picker-0.6.7+22
location-2.5.4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
sqflite-1.3.2+4

**Comment by darshankawar** [comment]
@denisciala 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/63933
Please follow-up there for updates.
Closing this as duplicate.
