### ISSUE TITLE
shared_preferences doesn't work in ios simulator

### ISSUE THREAD

**Issue by BatanGaming** [flutter/flutter#83656]
## Steps to Reproduce
1. Run
```bash
flutter create bug
cd bug
flutter pub add shared_preferences
flutter run
```
2. Update the files as follows: 
- `lib/main.dart`
```dart
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  final prefs = await SharedPreferences.getInstance();
}
```

**Expected results:** No exception throws.

**Actual results:**
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
#3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:49)
#4      MethodChannelSharedPreferencesStore.getAll (package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:44:25)
#5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:180:57)
#6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:56:19)
#7      main (package:bug/main.dart:4:41)
#8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#9      _rootRun (dart:async/zone.dart:1354:13)
<…>
```

<details>
  <summary>Logs</summary>

[verbose](https://github.com/flutter/flutter/files/6569187/logs.txt)

```
Analyzing bug...
No issues found! (ran in 1.5s)
```

```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-arm, locale ru-RU)
    • Flutter version 2.2.0 at /Users/batangaming/flutter
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/batangaming/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 302596F4-F863-4337-8260-935B921CDAD4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
You need to call `WidgetsFlutterBinding.ensureInitialized()` if you want to use a plugin that early; see https://github.com/flutter/flutter/issues/78028

**Comment by BatanGaming** [comment]
Thanks, it works
