### ISSUE TITLE
[camera] Out of memory crash when handling large XFile 

### ISSUE THREAD

**Issue by zltnDC** [flutter/flutter#83665]
**Description:**
I think the problem is loading the entire file into memory.

https://github.com/flutter/packages/blob/cdabfd3472e2bc99d90412b5d8dad4004b77e02d/packages/cross_file/lib/src/types/io.dart#L66

It works better.
```
final XFile file = await _controller.stopVideoRecording();
...
final sourceFile = File(file.path);
await sourceFile.copy(path);
```

**Steps to Reproduce:**

1. Record long video ( >15 minutes) in high quality using camera package
2. Stop recording and use toSave method on the XFile object
3. If we do not have enough memory, our app will crash

I tested it on Samsung sm-g800f, android 6.0.1, camera: ^0.7.0

**Expected results:** 
Our video should be saved to new path.

<details>
  <summary>Logs</summary>

```
E/Dart    (30288): ../../third_party/dart/runtime/vm/raw_object_snapshot.cc: 1565: error: Out of memory.

E/DartVM  (30288): version=2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "android_arm"

E/DartVM  (30288): pid=30288, thread=30355, isolate_group=main(0x58c91500), isolate=main(0x5bca3e00)

E/DartVM  (30288): isolate_instructions=5a4450c0, vm_instructions=5a4450c0

E/DartVM  (30288):   pc 0x5a509709 fp 0x5917dcf8 /data/app/pl.quittercheck.dev-2/lib/arm/libflutter.so+0x1384709

E/DartVM  (30288): -- End of DumpStackTrace

E/DartVM  (30288): [exit     : sp(0) fp(0x5917e05c) pc(0)]

E/DartVM  (30288): [dart     : sp(0x5917e064) fp(0x5917e080) pc(0x5cba6448) dart:isolate__SendPortImpl@1026248__sendInternal@1026248 ]

E/DartVM  (30288): [dart     : sp(0x5917e088) fp(0x5917e0a0) pc(0x5cba637c) dart:isolate__SendPortImpl@1026248_send ]

E/DartVM  (30288): [dart     : sp(0x5917e0a8) fp(0x5917e0d8) pc(0x6b714bd4) dart:io__IOService@14069316__dispatch@14069316 ]

E/DartVM  (30288): [dart     : sp(0x5917e0e0) fp(0x5917e118) pc(0x6d5289a8) dart:io__RandomAccessFile@14069316__dispatch@14069316 ]

E/DartVM  (30288): [dart     : sp(0x5917e120) fp(0x5917e178) pc(0x7cd2647c) dart:io__RandomAccessFile@14069316_writeFrom ]

E/DartVM  (30288): [dart     : sp(0x5917e180) fp(0x5917e1a4) pc(0x7cd25bdc) dart:io__File@14069316_writeAsBytes_<anonymous closure> ]

E/DartVM  (30288): [dart     : sp(0x5917e1ac) fp(0x5917e1f4) pc(0x7cd57d5c) *dart:async_::__rootRunUnary@4048458 ]

E/DartVM  (30288): [dart     : sp(0x5917e1fc) fp(0x5917e238) pc(0x7cd76ed0) *dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]

E/DartVM  (30288): [dart     : sp(0x5917e240) fp(0x5917e28c) pc(0x69949d88) dart:async__CustomZone@4048458_runUnary ]

E/DartVM  (30288): [dart     : sp(0x5917e294) fp(0x5917e2b4) pc(0x6994987c) dart:async__FutureListener@4048458_handleValue ]

E/DartVM  (30288): [dart     : sp(0x5917e2bc) fp(0x5917e2e8) pc(0x699494bc) dart:async__Future@4048458__propagateToListeners@4048458_handleValueCallback ]

E/DartVM  (30288): [dart     : sp(0x5917e2f0) fp(0x5917e32c) pc(0x699485b4) dart:async__Future@4048458__propagateToListeners@4048458 ]

E/DartVM  (30288): [dart     : sp(0x5917e334) fp(0x5917e350) pc(0x69946db4) dart:async__Future@4048458__completeWithValue@4048458 ]

E/DartVM  (30288): [dart     : sp(0x5917e358) fp(0x5917e370) pc(0x699469d8) dart:async__Future@4048458__asyncCompleteWithValue@4048458_<anonymous closure> ]

E/DartVM  (30288): [dart     : sp(0x5917e378) fp(0x5917e3ac) pc(0x5cbb77e0) dart:async_::__rootRun@4048458 ]

E/DartVM  (30288): [dart     : sp(0x5917e3b4) fp(0x5917e3e4) pc(0x5cbb73c0) dart:async_::__rootRun@4048458__rootRun@4048458 ]

E/DartVM  (30288): [dart     : sp(0x5917e3ec) fp(0x5917e434) pc(0x5cbb69d8) dart:async__CustomZone@4048458_run ]

E/DartVM  (30288): [dart     : sp(0x5917e43c) fp(0x5917e46c) pc(0x69946870) dart:async__CustomZone@4048458_runGuarded ]

E/DartVM  (30288): [dart     : sp(0x5917e474) fp(0x5917e48c) pc(0x69946750) dart:async__CustomZone@4048458_bindCallbackGuarded_<anonymous closure> ]

E/DartVM  (30288): [dart     : sp(0x5917e494) fp(0x5917e4b0) pc(0x699464b4) dart:async_::__microtaskLoop@4048458 ]

E/DartVM  (30288): [dart     : sp(0x5917e4b8) fp(0x5917e4d0) pc(0x69946034) dart:async_::__startMicrotaskLoop@4048458 ]

E/DartVM  (30288): [dart     : sp(0x5917e4d8) fp(0x5917e4e8) pc(0x69945f38) dart:async_::__startMicrotaskLoop@4048458__startMicrotaskLoop@4048458 ]

E/DartVM  (30288): [entry    : sp(0x5917e4f0) fp(0x5917e564) pc(0x5ba81118)]

F/libc    (30288): Fatal signal 6 (SIGABRT), code -6 in tid 30355 (1.ui)

```

</details>

**Comment by TahaTesser** [comment]
Hi @zltnDC 
As mentioned, I have modified the official sample to reproduce the issue, recorded for 17 min and  couldn't reproduce the crash


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.1 at /home/taha/Code/flutter_stable
    • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.22.0
[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)        • linux    • linux-x64      • Linux
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.77
• No issues found!
```

</details>


First, make sure e you're using the latest `camera: ^0.8.1+1`, the camera has improved a lot recently, the issue might not exist on latest version.

**Comment by zltnDC** [comment]
Hi I have prepared a sample app according to your suggestions.

https://github.com/zltnDC/flutter-camera-memory-exception

Please, take a look at the source code and readme for more details.

I reproduced this bug on other phones:

Xiaomi M2007J17G • android-arm64 • Android 10 (API 29)
Length: ~19 min
The workaround works
XFile.saveTo does not work

<details>
  <summary>Logs</summary>

```
[+1119301 ms] W/ple.camera_bug( 7384): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
[        ] W/ple.camera_bug( 7384): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
[   +6 ms] W/ple.camera_bug( 7384): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[        ] W/ple.camera_bug( 7384): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[ +846 ms] I/flutter ( 7384): start copy
[+33543 ms] I/flutter ( 7384): copy operation performed
[  +51 ms] I/flutter ( 7384): fileName(copy) length: 4080418204
[ +498 ms] I/flutter ( 7384): delete(copy) operation performed
[+16966 ms] I/flutter ( 7384): start saveTo
[+2056 ms] W/System  ( 7384): A resource failed to call release.
[   +7 ms] W/System  ( 7384): A resource failed to call release.
[+2340 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] executing: /Users/cudzik/Library/Android/sdk/platform-tools/adb -s 28c16e8e forward --list
[  +11 ms] Exit code 0 from: /Users/cudzik/Library/Android/sdk/platform-tools/adb -s 28c16e8e forward --list
[        ] 28c16e8e tcp:57391 tcp:39883
[   +1 ms] executing: /Users/cudzik/Library/Android/sdk/platform-tools/adb -s 28c16e8e forward --remove tcp:57391
[  +14 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.camera_bugs/code_cache/camera_bugsXGVIIZ/camera_bugs/)
[ +258 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed


```

</details>

iPhone X • iOS 13.6

Length: ~16 min
The workaround works
XFile.saveTo does not work

<details>
  <summary>Logs</summary>

```
[+874426 ms] flutter: start copy
[+76002 ms] flutter: copy operation performed
[   +1 ms] flutter: fileName(copy) length: 2930433629
[  +17 ms] flutter: delete(copy) operation performed
[+28811 ms] flutter: start saveTo
[   +6 ms] Runner(367,0x16dfd7000) malloc: can't allocate region
[   +1 ms] :*** mach_vm_map(size=2930442240, flags: 100) failed (error code=3)
[   +1 ms] Runner(367,0x16dfd7000) malloc: *** set a breakpoint in malloc_error_break to debug
[   +5 ms] flutter: FileSystemException: read failed, path = '/var/mobile/Containers/Data/Application/E60ADF48-B551-4E93-80D6-2A620918AB25/Documents/camera/videos/REC_9C88C194-E1C8-442C-972A-E41FB75B3FE7.mp4' (OS Error: Cannot allocate memory, errno = 12)
[   +1 ms] flutter: #0      _RandomAccessFile.read.<anonymous closure>  (dart:io/file_impl.dart:746:9)
[        ] #1      _rootRunUnary  (dart:async/zone.dart:1362:47)
[   +1 ms] #2      _CustomZone.runUnary  (dart:async/zone.dart:1265:19)
[   +1 ms] <asynchronous suspension>
[        ] #3      XFile.saveTo 
package:cross_file/…/types/io.dart:66
[        ] <asynchronous suspension>
[        ] #4      _MyHomePageState.saveToOperation 
package:camera_bugs/main.dart:172
[        ] <asynchronous suspension>

```

</details>

**Comment by TahaTesser** [comment]
Hi @zltnDC 
Thanks for the details, I can confirm the issue.  The issue is from Flutter engine most likely since the file is heavy and you're operations  at runtime

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    en-US)
    • Flutter version 2.2.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision d79295af24 (10 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 91.0.4472.106

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.414, on macOS 11.4 20F71
    darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.414 at
      /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 757c3add14 (9 hours ago), 2021-06-20 22:29:02 -0400
    • Engine revision 9520bb15b3
    • Dart version 2.14.0 (build 2.14.0-228.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            •
      iOS 14.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.4 20F71 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 91.0.4472.106

• No issues found!

```
		
</details>

✅ : No Issue ❌: Issue reproduced

**Comment by chinmaygarde** [comment]
Removing the engine tag as the copy in a plugin seems to be reading all the contents into memory. `dart:io`s routines should not bring all the contents into memory and there are platform specific ways plugins can use to avoid a copy to memory as well.

**Comment by chinmaygarde** [comment]
cc @stuartmorgan

**Comment by stuartmorgan** [comment]
Looks like the dart:io implementation there just wasn't well thought out.

**Comment by chinmaygarde** [comment]
The [implementation](https://github.com/flutter/packages/blob/cdabfd3472e2bc99d90412b5d8dad4004b77e02d/packages/cross_file/lib/src/types/io.dart#L66) is not is `dart:io` though. Am I missing something?

**Comment by stuartmorgan** [comment]
That line is calling `File.writeAsBytes` which is from `dart:io`, and is in a class that is [explicitly documented as being the `dart:io`-based implementation](https://github.com/flutter/packages/blob/cdabfd3472e2bc99d90412b5d8dad4004b77e02d/packages/cross_file/lib/src/types/io.dart#L13), so I don't know how you're civilizing that it's not that implementation.

**Comment by chinmaygarde** [comment]
AFAIK, `File.copy` creates a new copy of the existing file without reading its contents into memory. So, instead of calling `File.writeAsBytes` after reading said bytes, it could directly call `File.copy(_file.path)` without incurring the overhead.

**Comment by stuartmorgan** [comment]
Yes, that's why I said the current implementation wasn't well thought out.

**Comment by chinmaygarde** [comment]
Oh, when you said "the `dart:io` implementation there", I thought you meant the implementation of `File.copy` in `dart:io`. Yeah, the update to XFile should be trivial though.

**Comment by TahaTesser** [comment]
Thanks for the details everyone
