### ISSUE TITLE
'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by mhabashy** [flutter/flutter#83680]
```onsole
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!
```
Hello I have the same issue wondering if installing  the beta is the best solution

any help will be greatly appreciated 

```console
-I/Users/habashy/Library/Developer/Xcode/DerivedData/Runner-gfixyrqmotsyorcunhnbrizsbqpv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources-normal/x86_64 -Xcc
                            -I/Users/habashy/Library/Developer/Xcode/DerivedData/Runner-gfixyrqmotsyorcunhnbrizsbqpv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources/x86_64
-Xcc
                            -I/Users/habashy/Library/Developer/Xcode/DerivedData/Runner-gfixyrqmotsyorcunhnbrizsbqpv/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/DerivedSources -Xcc
-DDEBUG\=1 -Xcc
                            -DCOCOAPODS\=1 -target-sdk-version 14.5 -serialize-diagnostics-path
                            /Users/habashy/Library/Developer/Xcode/DerivedData/Runner-gfixyrqmotsyorcunhnbrizsbqpv/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-2HMDNKUB774XR.dia
                            /Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/ios/Runner/Runner-Bridging-Header.h -emit-pch -pch-output-dir
                            /Users/habashy/Library/Developer/Xcode/DerivedData/Runner-gfixyrqmotsyorcunhnbrizsbqpv/Build/Intermediates.noindex/PrecompiledHeaders
                        /Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/ios/Runner/Runner-Bridging-Header.h:1:9: note: in file included from
                        /Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/ios/Runner/Runner-Bridging-Header.h:1:
                        #import "GeneratedPluginRegistrant.h"
                                ^
                        /Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/ios/Runner/GeneratedPluginRegistrant.h:8:9: error: 'Flutter/Flutter.h' file not found
                        #import <Flutter/Flutter.h>
                                ^
                        1 error generated.
                        <unknown>:0: error: failed to emit precompiled header

'/Users/habashy/Library/Developer/Xcode/DerivedData/Runner-gfixyrqmotsyorcunhnbrizsbqpv/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3JTKNPAW42V5P-clang_1REEOC79ZZG84.pch' for
                        bridging header '/Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/ios/Runner/Runner-Bridging-Header.h'
                        /Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/ios/Runner/Runner-Bridging-Header.h:1:9: note: in file included from
                        /Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/ios/Runner/Runner-Bridging-Header.h:1:
                        #import "GeneratedPluginRegistrant.h"
                                ^
                        2 errors generated.
                    
                        <unknown>:0: error: generate-pch command failed with exit code 1 (use -v to see invocation)
                        /Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range
of supported
                        deployment target versions is 9.0 to 14.5.99. (in target 'Flutter' from project 'Pods')
                    
[+6802 ms] Could not build the application for the simulator.
[   +3 ms] Error launching application on iPhone 12 Pro Max.
[   +3 ms] "flutter run" took 55,006ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

_Originally posted by @mhabashy in https://github.com/flutter/flutter/issues/74210#issuecomment-851733705_

**Comment by TahaTesser** [comment]
Hi @mhabashy 
Can you please provide a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample? (logs will long so copy them in a text file and drop them in a the comments below
Thank you

**Comment by LianYangCn** [comment]
I’m very curious, where exactly is “Flutter/Flutter.h” and why It can’t be found so often.

**Comment by mhabashy** [comment]
Hi, TahaTesser thanks for the help. I can't post a minimal code sample it's a really large application for a community that really is picky on code privacy.  It worked before I updated to Flutter 2.2. Currently was able to get the web version to work and the android version to work. With the Android version, I disabled notifications to get to work because flutter_messaging with give me the hard time, and that got it to run.  

In been trying to get the iOS running all weekend. 

[here is the flutter run --verbose](http://stmarystmina.org/files/flutter.h_not_found_bug.txt)

and the flutter crash report. 

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ios

## exception

ProcessException: ProcessException: Process exited abnormally:
xcodebuild: error: Scheme Runner is not currently configured for the build action.
  Command: xcrun xcodebuild -configuration Release -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/habashy/Desktop/suscopts/suscoptsflutter/suscoptsportal/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/9c/llg_jl4x59509z_gjfmshsf00000gn/T/flutter_tools.fYc2WS/flutter_build_log_pipe.Z0Tsmr/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:340:21)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:374:47)
<asynchronous suspension>
#3      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:257:37)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.1 at /Users/habashy/Documents/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/habashy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/habashy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/habashy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Users/habashy/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • AE87914B-8D3A-4D5E-89BE-CD1BF32D79CC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

Thanks in advance

**Comment by jmagman** [comment]
@mhabashy I don't see the `Run Script` build step that Flutter uses to move its frameworks to the right place.  Did you remove it?
<img width="1296" alt="Screen Shot 2021-06-01 at 11 51 19 AM" src="https://user-images.githubusercontent.com/682784/120375490-b83daa80-c2cf-11eb-9c65-5863e25961fc.png">

**Comment by mhabashy** [comment]
Okay don't remove it but I had the `For Install builds only` checked. Believe checked this when I was trying to debug another issue with firebase. Thanks for the help hope wasn't to much trouble.
