### ISSUE TITLE
Confusing navigator exception when missing key?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#8372]
```
Installing android/app/build/outputs/apk/app.apk...  11.0s
E/flutter (25315): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (25315): 'package:flutter/src/material/app.dart': Failed assertion: line 68: '!routes.containsKey(Navigator.defaultRouteName) || (home == null)': is not true.
E/flutter (25315): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:33)
E/flutter (25315): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:29)
E/flutter (25315): #2      MaterialApp.MaterialApp (package:flutter/src/material/app.dart:68)
E/flutter (25315): #3      main (lib/main.dart:5)
E/flutter (25315): #4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
E/flutter (25315): #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
Syncing files to device...                            5.7s
```

What is that message telling me?

My example:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: 'Test',
      home: new Home(),
      routes: {
        '/': (BuildContext _) => new Home(),
        '/other': (BuildContext _) => new OtherPage(),
      },
    ),
  );
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      key: const ValueKey('/'),
      appBar: new AppBar(
        title: new Text('Home'),
      ),
      body: new Card(
        child: new RaisedButton(
          child: new Text('Press Me'),
          onPressed: () {
            Navigator.pushNamed(context, '/other');
          },
        ),
      ),
    );
  }
}

class OtherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      key: const ValueKey('/other'),
      appBar: new AppBar(
        title: new Text('Other'),
      ),
      body: new Text('Other'),
    );
  }
}
```

This is me working on https://github.com/flutter/flutter/issues/8080 using an example modified from  https://github.com/flutter/flutter/issues/8163

**Comment by eseidelGoogle** [comment]
It looks like the error is actually caused by me both defining home: as well as a route named '/':

```
    new MaterialApp(
      title: 'Test',
      home: new Home(),
      routes: {
        '/': (BuildContext _) => new Home(),
        '/other': (BuildContext _) => new OtherPage(),
      },
    ),
```

Seems like we could do better error handling in MaterialApp?

**Comment by Hixie** [comment]
We are going to push this bug to beyond m3 since it doesn't fit our current priorities.

**Comment by clocksmith** [comment]
The current error message for this example is

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#f554a):
flutter: If the home property is specified, the routes table cannot include an entry for "/", since it would
flutter: be redundant.
flutter: 'package:flutter/src/widgets/app.dart': Failed assertion: line 168 pos 10: 'home == null ||
flutter:          !routes.containsKey(Navigator.defaultRouteName)'
```

I think the new language fixes this issue.
