### ISSUE TITLE
docs_test failed: tool execution failed: git status exit with non-zero exit code: -1284960497

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83762]
```
dartdoc:stderr:   error: tool execution failed: Tool "snippet" returned non-zero exit code (255) when run as "/b/s/w/ir/x/w/flutter sdk/bin/cache/dart-sdk/bin/dart /b/s/w/ir/x/t/dartdoc_snapshot_cache_KFUHBM/snapshot_0 --type=snippet" from /b/s/w/ir/x/w/flutter sdk/dev/docs
dartdoc:stderr: Input to snippet was:
dartdoc:stderr:
dartdoc:stderr: A 1990s-era "OK" button:
dartdoc:stderr:
dartdoc:stderr: ```dart
dartdoc:stderr: Container(
dartdoc:stderr:   decoration: const BoxDecoration(
dartdoc:stderr:     border: Border(
dartdoc:stderr:       top: BorderSide(width: 1.0, color: Color(0xFFFFFFFF)),
dartdoc:stderr:       left: BorderSide(width: 1.0, color: Color(0xFFFFFFFF)),
dartdoc:stderr:       right: BorderSide(width: 1.0, color: Color(0xFF000000)),
dartdoc:stderr:       bottom: BorderSide(width: 1.0, color: Color(0xFF000000)),
dartdoc:stderr:     ),
dartdoc:stderr:   ),
dartdoc:stderr:   child: Container(
dartdoc:stderr:     padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 2.0),
dartdoc:stderr:     decoration: const BoxDecoration(
dartdoc:stderr:       border: Border(
dartdoc:stderr:         top: BorderSide(width: 1.0, color: Color(0xFFDFDFDF)),
dartdoc:stderr:         left: BorderSide(width: 1.0, color: Color(0xFFDFDFDF)),
dartdoc:stderr:         right: BorderSide(width: 1.0, color: Color(0xFF7F7F7F)),
dartdoc:stderr:         bottom: BorderSide(width: 1.0, color: Color(0xFF7F7F7F)),
dartdoc:stderr:       ),
dartdoc:stderr:       color: Color(0xFFBFBFBF),
dartdoc:stderr:     ),
dartdoc:stderr:     child: const Text(
dartdoc:stderr:       'OK',
dartdoc:stderr:       textAlign: TextAlign.center,
dartdoc:stderr:       style: TextStyle(color: Color(0xFF000000))
dartdoc:stderr:     ),
dartdoc:stderr:   ),
dartdoc:stderr: )
dartdoc:stderr: ```
dartdoc:stderr: Stderr output was:
dartdoc:stderr: Unhandled exception:
dartdoc:stderr: git status exit with non-zero exit code: -1284960497
dartdoc:stderr: #0      getChannelName (package:snippets/main.dart:28:5)
dartdoc:stderr: #1      main (package:snippets/main.dart:185:18)
dartdoc:stderr: #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
dartdoc:stderr: #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
dartdoc:stderr:
```
https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_test/1055

Failed on unrelated PR https://github.com/flutter/flutter/pull/83756.

**Comment by jmagman** [comment]
\cc @gspencergoog #49845

**Comment by gspencergoog** [comment]
I have no idea what that return value indicates: status should only ever return zero.

I've created a PR to add more verbose failure output when the snippets tool fails because git fails:  https://github.com/flutter/flutter/pull/83806

**Comment by jmagman** [comment]
Passed on rerun, reducing priority.

**Comment by jmagman** [comment]
Another one: https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_test/1079

**Comment by Hixie** [comment]
I've no idea what this could be but if we haven't seen it in over a year it's probably not worth keeping the issue around. Closing.
