### ISSUE TITLE
SliverGeometry exception in logs [seems harmless otherwise]

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#8378]
I observed this exception while playing with the app today. I am not sure how to reproduce it reliably. We are not using SliverAppBar or scroller yet.

```
I/flutter (19919): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (19919): The following assertion was thrown during performLayout():
I/flutter (19919): SliverGeometry has a layoutExtent that exceeds its paintExtent.
I/flutter (19919): The paintExtent is 249.8100445182619, but the layoutExtent is 249.81004451826192. Maybe you have
I/flutter (19919): fallen prey to floating point rounding errors, and should explicitly apply the min() or max()
I/flutter (19919): functions, or the clamp() method, to the layoutExtent? 
I/flutter (19919): 
I/flutter (19919): When the exception was thrown, this was the stack:
I/flutter (19919): #0      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:499:9)
I/flutter (19919): #2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:497:12)
I/flutter (19919): #3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:756:21)
I/flutter (19919): #4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1744:19)
I/flutter (19919): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1744:14)
I/flutter (19919): #7      RenderViewportBase.layoutOneSide (package:flutter/src/rendering/sliver.dart:1319:13)
I/flutter (19919): #8      RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/sliver.dart:2072:12)
I/flutter (19919): #9      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/sliver.dart:2035:20)
I/flutter (19919): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #11     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #13     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #15     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #17     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #19     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #21     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (19919): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1742:7)
I/flutter (19919): #29     RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:827:13)
I/flutter (19919): #30     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1618:7)
I/flutter (19919): #31     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:953:18)
I/flutter (19919): #32     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:225:19)
I/flutter (19919): #33     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:333:23)
I/flutter (19919): #34     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
I/flutter (19919): #35     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676:15)
I/flutter (19919): #36     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611:9)
I/flutter (19919): #37     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (19919): (elided 2 frames from class _AssertionError)
I/flutter (19919): 
I/flutter (19919): The following RenderObject was being processed when the exception was fired:
I/flutter (19919):   RenderSliverPadding#645323507 relayoutBoundary=up11
I/flutter (19919):   creator: SliverPadding ← ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#944536500] ← Listener ←
I/flutter (19919):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#866821776] ←
I/flutter (19919):   Scrollable ← ListView ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
I/flutter (19919):   NotificationListener<ScrollNotification> ← ⋯
I/flutter (19919):   parentData: layoutOffset=0.0
I/flutter (19919):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (19919):   scrollOffset: 6.2, remainingPaintExtent: 587.4, crossAxisExtent: 230.0viewportMainAxisExtent:
I/flutter (19919):   587.4)
I/flutter (19919):   geometry: SliverGeometry(scrollExtent: 256.0, paintExtent: 249.8, layoutExtent: 249.8,
I/flutter (19919):   maxPaintExtent: 256.0, hitTestExtent: 249.8, scrollOffsetCorrection: 0.0)
I/flutter (19919): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (19919):   RenderSliverFixedExtentList#406148980 relayoutBoundary=up12
I/flutter (19919):     RenderRepaintBoundary#665953289
I/flutter (19919):       RenderOpacity#69931647
I/flutter (19919):         RenderSemanticsGestureHandler#390378371
I/flutter (19919):           RenderPointerListener#579700814
I/flutter (19919):     RenderRepaintBoundary#749317846
I/flutter (19919):       RenderOpacity#518316569
I/flutter (19919):         RenderSemanticsGestureHandler#668177495
I/flutter (19919):           RenderPointerListener#235605070
I/flutter (19919):     RenderRepaintBoundary#372213716
I/flutter (19919):       RenderOpacity#669253674
I/flutter (19919):         RenderSemanticsGestureHandler#462240836
I/flutter (19919):           RenderPointerListener#561360554
I/flutter (19919):     RenderRepaintBoundary#288825658
I/flutter (19919):       RenderOpacity#946513081
I/flutter (19919):         RenderSemanticsGestureHandler#489422843
I/flutter (19919):           RenderPointerListener#1041710162
I/flutter (19919):     RenderRepaintBoundary#822447757
I/flutter (19919):       RenderOpacity#1040795807
I/flutter (19919):         RenderSemanticsGestureHandler#297948512
I/flutter (19919):           RenderPointerListener#536823314
I/flutter (19919): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by abarth** [comment]
I can see how this might happen, and I have a patch that I think addresses the issue, but I'm not sure how to test it because I cannot reproduce this issue myself.  If you figure out how to reproduce it, let me know and I can test my fix.

**Comment by mehmetf** [comment]
One idea for reproducing:

- Put your patch in google3.
- Build our app in emulator mode [reach out to me for instructions if you don't know]
- Try opening the dropdowns that appear in pacing/target tabs below the tab bar. This is also not 100% consistent but it happens more than half the time by my count.
