### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "reg" in the search path. Command: reg, OS error code: 0

### ISSUE THREAD

**Issue by sidneysimoes** [flutter/flutter#83869]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "reg" in the search path. Command: reg, OS error code: 0
```
#0      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:89:7)
#1      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:642:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#3      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:641:12)
#4      MicrosoftEdgeDevice._getSdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:273:56)
#5      MicrosoftEdgeDevice.sdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:270:78)
#6      MicrosoftEdgeDevice._meetsVersionConstraint (package:flutter_tools/src/web/web_device.dart:261:38)
#7      WebDevices.pollingGetDevices (package:flutter_tools/src/web/web_device.dart:355:30)
#8      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:397:60)
#9      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:387:12)
#10     DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:165:20)
#11     DeviceManager.getDevices (package:flutter_tools/src/device.dart:154:11)
#12     DeviceBasedDevelopmentArtifacts.requiredArtifacts (package:flutter_tools/src/runner/flutter_command.dart:1366:62)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1144:43)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [versÃ£o 10.0.19043.1023], locale pt-BR)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (6 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\SiS\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Progra~1\Java\jdk-16.0.1\bin\bin\java
    ✗ Cannot execute C:\Progra~1\Java\jdk-16.0.1\bin\bin\java to determine the version

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.23.0

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "reg" in the search path.
        Command: reg 
    • #0      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:89:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:642:24)
      #2      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
      #3      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:641:12)
      #4      MicrosoftEdgeDevice._getSdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:273:56)
      #5      MicrosoftEdgeDevice.sdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:270:78)
      #6      MicrosoftEdgeDevice._meetsVersionConstraint (package:flutter_tools/src/web/web_device.dart:261:38)
      #7      WebDevices.pollingGetDevices (package:flutter_tools/src/web/web_device.dart:355:30)
      #8      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:397:60)
      #9      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:387:12)
      #10     DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:165:20)
      #11     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:510:55)
      #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #13     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #14     _rootRun (dart:async/zone.dart:1354:13)
      #15     _CustomZone.run (dart:async/zone.dart:1258:19)
      #16     _runZoned (dart:async/zone.dart:1789:10)
      #17     runZonedGuarded (dart:async/zone.dart:1777:12)
      #18     runZoned (dart:async/zone.dart:1708:12)
      #19     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #20     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:199:9)
      #21     Doctor.diagnose (package:flutter_tools/src/doctor.dart:303:47)
      #22     _doctorText (package:flutter_tools/runner.dart:232:18)
      #23     _handleToolError (package:flutter_tools/runner.dart:157:27)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>


! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by darshankawar** [comment]
@sidneysimoes 
Did you follow the installation steps as mentioned in the [document](https://flutter.dev/docs/get-started/install/windows) ? and accordingly set the PATH properly ?

Also Can you provide `flutter doctor -vv` ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
