### ISSUE TITLE
Camera Plugin Crash - java.lang.NumberFormatException: For input string: "/dev/video10"

### ISSUE THREAD

**Issue by Gallax** [flutter/flutter#83912]
I'm executing the example in flutter camera plugin page and the following Exception was occurred

---------------------------
# Exception 

```
I/CameraManagerGlobal( 3183): Connecting to camera service
D/CameraManager( 3183): supportsCamera2ApiLocked cameraId:/dev/video10
D/CameraManager( 3183): supportsCamera2ApiLocked cameraId:/dev/video10
I/Camera  ( 3183): [FPS Range Available] is:[7, 15]
I/Camera  ( 3183): [FPS Range Available] is:[15, 30]
I/Camera  ( 3183): [FPS Range] is:[15, 30]
E/MethodChannel#plugins.flutter.io/camera( 3183): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera( 3183): java.lang.NumberFormatException: For input string: "/dev/video10"
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at java.lang.Integer.parseInt(Integer.java:604)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at java.lang.Integer.parseInt(Integer.java:650)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.plugins.camera.CameraUtils.getBestAvailableCamcorderProfileForResolutionPreset(CameraUtils.java:133)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.plugins.camera.Camera.<init>(Camera.java:152)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:361)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$MethodCallHandlerImpl(MethodCallHandlerImpl.java:77)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.plugins.camera.-$$Lambda$MethodCallHandlerImpl$kQOHgMggqzdMNqkzF-YukQrdRi8.onResult(Unknown Source:6)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:53)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:70)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter ( 3183): Instance of 'MethodChannel'
E/flutter ( 3183): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: CameraException(error, For input string: "/dev/video10")
E/flutter ( 3183): #0      MethodChannelCamera.createCamera (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:100:7)
E/flutter ( 3183): <asynchronous suspension>
E/flutter ( 3183): #1      CameraController.initialize (package:camera/src/camera_controller.dart:272:19)
E/flutter ( 3183): <asynchronous suspension>
E/flutter ( 3183): 
```

----------------------------------------

```
# Executed Code

List<CameraDescription> ?cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  cameras = await availableCameras();
  runApp(CameraApp());
}

class CameraApp extends StatefulWidget {
  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  CameraController ?controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(cameras![0], ResolutionPreset.max);
    controller!.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller!.value.isInitialized) {
      return Container();
    }
    return MaterialApp(
      home: CameraPreview(controller!),
    );
  }
}
```

**Comment by darshankawar** [comment]
@Gallax 
What device does it crash on ? I mean Android or iOS ?

I tried your code sample along with the plugin example using latest plugin version, but didn't get the crash you mentioned. I was able to launch the camera properly on iPhone device, as below:


https://user-images.githubusercontent.com/67046386/120773345-e4ab2e00-c53e-11eb-85d0-cf8dda27813d.MP4

**Comment by Gallax** [comment]
The crash occurred on android platform.
I suppose the problem is the name of camera "/dev/video10"

I noticed in the emulator when I use "availableCameras" the camera ids are integers as "0", "1".

But in this physical device the name is "/dev/video10"
and this is a problem when you convert it to int

E/MethodChannel#plugins.flutter.io/camera( 3183): java.lang.NumberFormatException: For input string: "/dev/video10"
E/MethodChannel#plugins.flutter.io/camera( 3183): 	at java.lang.Integer.parseInt(Integer.java:604)

**Comment by darshankawar** [comment]
Thanks for confirming. I see a similar issue while running on iOS simulator, on which it throws below error:

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running pod install...
Running Xcode build...
Xcode build done.                                           19.1s
Debug service listening on ws://127.0.0.1:54389/bC_TQ9UOWgg=/ws
Syncing files to device iPhone 12 Pro Max...

======== Exception caught by widgets library =======================================================
The following RangeError was thrown attaching to the render tree:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      _CameraAppState.initState (package:camera_example/main.dart:974:43)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4711:57)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
...
====================================================================================================
```

<details>
<summary> complete code sample </summary>

```


import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

List<CameraDescription> ?cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  cameras = await availableCameras();
  runApp(CameraApp());
}

class CameraApp extends StatefulWidget {
  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  CameraController ?controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(cameras![0], ResolutionPreset.max);
    controller!.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller!.value.isInitialized) {
      return Container();
    }
    return MaterialApp(
      home: CameraPreview(controller!),
    );
  }
}

```

</details>

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.1 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!




```

</details>

**Comment by darshankawar** [comment]
Cc: @mvanbeusekom

**Comment by stuartmorgan** [comment]
The Android overhaul in 0.9.0 catches `NumberFormatException` when parsing camera IDs, so closing as obsolete.
