### ISSUE TITLE
`Platform.executable` throws Unhandled Exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by ueman** [flutter/flutter#83921]
Calling `Platform.executable` throws `Unhandled Exception: type 'Null' is not a subtype of type 'String'` on macOS.
It might be worth to check this on other platforms too.

## Steps to Reproduce

```dart
import 'dart:io';

void main() {
  print(Platform.executable);
}
```

**Expected results:** 

Any output regarding the executable.

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      _Platform.executable (dart:io/platform_impl.dart:36:30)
#1      _Platform.executable (dart:io/platform_impl.dart)
#2      Platform.executable (dart:io/platform.dart:134:45)
#3      main
package:reproducable_example/main.dart:4
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#5      _rootRun (dart:async/zone.dart:1354:13)
#6      _CustomZone.run (dart:async/zone.dart:1258:19)
#7      _runZoned (dart:async/zone.dart:1789:10)
#8      runZonedGuarded (dart:async/zone.dart:1777:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

```
Analyzing reproducable_example...                                       
No issues found! (ran in 1.1s)
```

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.3.1 20E241 darwin-x64, locale de-DE)
    • Flutter version 2.2.1 at /Users/jonas/Documents/projects/flutter
    • Framework revision 02c026b03c (7 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jonas/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/jonas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/jonas/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
This seems to be happening on Mobile and desktop, so doesn't look like specific to any platform, but related to framework.

 On Mobile (iOS) and `sdk: ">=2.12.0 <3.0.0"`:
```

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           30.7s
Debug service listening on ws://127.0.0.1:52469/oskxbI83M68=/ws
Syncing files to device iPhone 12 Pro Max...
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      _Platform.executable (dart:io/platform_impl.dart:36:30)
#1      _Platform.executable (dart:io/platform_impl.dart)
#2      Platform.executable (dart:io/platform.dart:134:45)
#3      main (package:macbug/main.dart:4:18)
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#5      _rootRun (dart:async/zone.dart:1354:13)
#6      _CustomZone.run (dart:async/zone.dart:1258:19)
#7      _runZoned (dart:async/zone.dart:1789:10)
#8      runZonedGuarded (dart:async/zone.dart:1777:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Same as above on desktop running `flutter run -d macos`.

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.1 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision 02c026b03c (4 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.77

• No issues found!




```

</details>

**Comment by darkstarx** [comment]
Bug still exists.
```
[√] Flutter (Channel master, 2.11.0-0.0.pre.452, on Microsoft Windows [Version 10.0.19043.1466], locale    ru-RU)
    • Flutter version 2.11.0-0.0.pre.452 at C:\Users\darkz\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba01ec8faa (14 hours ago), 2022-02-05 22:05:18 -0500
    • Engine revision 0712096899
    • Dart version 2.17.0 (build 2.17.0-85.0.dev)  
    • DevTools version 2.10.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed        
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.20348.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed        
      instructions).

[√] VS Code, 64-bit edition (version 1.63.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1466]       
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.43

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by basharbachir** [comment]
Bug still exists for sorry .

**Comment by maheshmnj** [comment]
Reproducible on stable 2.10.5 and master 2.13 Reproduction details can be found here https://github.com/flutter/flutter/issues/102138#issuecomment-1102585465

**Comment by cbracken** [comment]
### Desktop platforms
* [ ] macOS
* [ ] Windows
* [ ] Linux

### Mobile platforms
* [ ] iOS
* [ ] Android

**Comment by cbracken** [comment]
As of https://github.com/flutter/engine/pull/33127, `Platform.executable` no longer returns null. On platforms that use the embedder API and specify `FlutterProjectArgs::command_line_argv` with at least one element, we now return the first argument in that array, otherwise we default to returning `"Flutter"`.

As part of that patch I added `Settings::executable_name_`. I'll patch this up on the iOS and Android embedders to produce a more relevant value in followup patches.
