### ISSUE TITLE
Flutter does not run on MacOS, with MacOS as the device, if Anaconda is installed.

### ISSUE THREAD

**Issue by PopeJuliusII** [flutter/flutter#84081]
# Steps to Reproduce

1. Get a mac with anaconda installed. (My `.zshrc` is below.)
2. Run the following command: `cd && cd Desktop && flutter channel dev && flutter upgrade && flutter create myproject && cd myproject && flutter run -d macos`.

# Steps to Fix

1. Comment out the lines (below) from the `.zshrc`.

# Logs and Stuff

## zshrc

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/name/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/name/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/name/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/name/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

## Flutter Doctor

Command: `flutter doctor -v`
Output:

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.225, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.3.0-17.0.pre.225 at /Users/name/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2794dea0df (24 hours ago), 2021-06-05 16:04:04 -0400
    • Engine revision 03d645e782
    • Dart version 2.14.0 (build 2.14.0-182.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/name/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

## Flutter Run

Command: `flutter run -d macos`
Output: 
```
Launching lib/main.dart on macOS in debug mode...
ld: unknown option: -target
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
** BUILD FAILED **

Building macOS application...
Exception: Build process failed
```

## Flutter Run -v

Command: `flutter run -d macos -v`
Output [ending]: 
```
[   +4 ms] ** BUILD FAILED **
[   +2 ms] The following build commands failed:
[        ] 	Ld /Users/name/Desktop/MyApp/myapp/build/macos/Build/Products/Debug/myapp.app/Contents/MacOS/myapp normal
[        ] (1 failure)
[  +32 ms] Building macOS application... (completed in 4.3s)
[+2207 ms] Exception: Build process failed
[   +2 ms] "flutter run" took 8,864ms.
[   +5 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:671:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by stuartmorgan** [comment]
> Output [ending]:

You've removed the portion that says what the linker errors are. Please provide the complete verbose output.

**Comment by PopeJuliusII** [comment]
It's too long for GitHub ("You can't comment at this time — your comment is too long (maximum is 65536 characters)."), so I've attached it as a text file. Sorry for the inconvenience, @stuartmorgan .

[Conda Flutter Error Verbose Output.txt](https://github.com/flutter/flutter/files/6606694/Conda.Flutter.Error.Verbose.Output.txt)

**Comment by stuartmorgan** [comment]
> `/Users/name/anaconda3/bin/x86_64-apple-darwin13.4.0-ld -target x86_64-apple-macos10.11 [...]
> ld: unknown option: -target

You have overridden your linker with one that apparently isn't compatible with Xcode. If you make system-level changes that break `xcodebuild`, then building with the `flutter` tool isn't going to work by extension.

You'll need to either remove that linker from your path, or, if your package manager is only changing your path for terminals and not GUI apps, do all of Flutter builds by doing a failed `flutter build` to do Flutter-specific setup any time you update Flutter and doing your actually build from the Xcode UI.
