### ISSUE TITLE
Assertion `primaryDelta == null` Thrown When Scroll Dragging and Device Orientation Changes

### ISSUE THREAD

**Issue by searchy2** [flutter/flutter#84085]
## Steps to Reproduce

1. This issue is consistently reproducible. The key to to have a drag gesture active and not "finish" when the device orientation change occurs.
2. Scroll and change the device orientation while performing a scroll gesture.
3. If the exception doesn't appear, continue scrolling and changing the orientation until the assertion is thrown. 
4. Note, it can be difficult to get the device orientation to change while dragging because the OS blocks orientation change if there is an interaction. 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      body: Stack(children: <Widget>[
        SingleChildScrollView(
          child: Container(
            margin: EdgeInsets.symmetric(horizontal: 32),
            child: Column(children: [
              ...List.generate(
                100,
                (index) => Container(
                    height: 50,
                    margin: EdgeInsets.only(bottom: 8),
                    color: Colors.amber),
              ),
            ]),
          ),
        )
      ]),
    );
  }
}
```

**Expected results:**
No assertion thrown.

**Actual results:**
```
======== Exception caught by gesture library =======================================================
The following assertion was thrown while routing a pointer event:
'package:flutter/src/gestures/drag_details.dart': Failed assertion: line 144 pos 10: 'primaryDelta == null
           || (primaryDelta == delta.dx && delta.dy == 0.0)
           || (primaryDelta == delta.dy && delta.dx == 0.0)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      new DragUpdateDetails (package:flutter/src/gestures/drag_details.dart:144:10)
#3      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:429:41)
#4      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:9)
#5      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
#6      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
...
====================================================================================================
```

<details>
  <summary>Logs</summary>

```
[+61995 ms] D/DecorView(15778): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d56d91a[MainActivity]
[+3713 ms] D/DecorView(15778): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d56d91a[MainActivity]
[+7549 ms]
           ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
           The following assertion was thrown while routing a pointer event:
           'package:flutter/src/gestures/drag_details.dart': Failed assertion: line 144 pos 10: 'primaryDelta
           == null
                      || (primaryDelta == delta.dx && delta.dy == 0.0)
                      || (primaryDelta == delta.dy && delta.dx == 0.0)': is not true.

           Either the assertion indicates an error in the framework itself, or we should provide substantially
           more information in this error message to help you determine and fix the underlying cause.
           In either case, please report this assertion by filing a bug on GitHub:
             https://github.com/flutter/flutter/issues/new?template=2_bug.md

           When the exception was thrown, this was the stack:
           #2      new DragUpdateDetails (package:flutter/src/gestures/drag_details.dart:144:10)
           #3      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:429:41)
           #4      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:289:9)
           #5      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
           #6      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
           #7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
           #8      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
           #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
           #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
           #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
           #12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
           #13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
           #14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
           #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
           #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
           #20     _invoke1 (dart:ui/hooks.dart:182:10)
           #21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
           #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
           (elided 5 frames from class _AssertionError and dart:async)

           router: Instance of 'PointerRouter'
           route: Closure: (PointerEvent) => void from Function 'handleEvent':.
           event: _TransformedPointerMoveEvent#d9e58(position: Offset(NaN, Infinity))
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +3 ms]
           Another exception was thrown: 'package:flutter/src/gestures/drag_details.dart': Failed assertion: line 144 pos 10: 'primaryDelta == null
[   +5 ms]
           Another exception was thrown: 'package:flutter/src/gestures/drag_details.dart': Failed assertion: line 144 pos 10: 'primaryDelta == null

```

```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 2.2.1 at F:\Development\flutter-sdk
    • Framework revision 02c026b03c (10 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at F:\Development\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = F:\Development\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.56.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • ONEPLUS A6013 (mobile) • 26bd994b • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 6.1.7601]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 89.0.774.77

```

</details>

**Comment by TahaTesser** [comment]
Hi @searchy2 
I tried Oneplus 8, K20 pro both devices stop the scrolling animation before orientation changes. Only Oneplus throws refresh rate but no issue as you described. 

Is there a motion that requires to reproduce or perhaps a widget test can reproduce this more accurately?


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1023], locale en-US)
    • Flutter version 2.2.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 02c026b03c (11 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (5 available)
    • IN2011 (mobile)         • c9d8ee0c      • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1023]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
