### ISSUE TITLE
Flutter Windows: cannot build Windows App error MSB8066

### ISSUE THREAD

**Issue by LeXuanKhanh** [flutter/flutter#84115]
Hi, I'm getting the error MSB8066 like #80179, #75611,#79381,#64419, but the problem is my project path doesn't contain space character but it still get error

```
CUSTOMBUILD : error : Cannot run with sound null safety, because the following dependencies [D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'D:\work\flutter_project\flutter_youtube_downloader\build\windows\CMakeFiles\079a7490c25e8a1e7333fe16494562a7\flutter_windows.dll.rule;D:\work\flutter_project\flutter_youtube_downloader\build\windows\CMakeFiles\782162d8d25b8edf7b0745f9e3b80bb9\flutter_assemble.rule' exited with code 1. [D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
```

Flutter doctor -v:

```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-001)
    • Flutter version 2.2.1 at D:\flutter
    • Framework revision 02c026b03c (11 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\lexua\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\lexua\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!
```
Flutter run --verbose, the log is kinda long:
```
[  +70 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +386 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] executing: [D:\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +53 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] 2.2.1
[   +5 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\flutter/] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +101 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +66 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] executing: C:\Users\lexua\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +14 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +55 ms] executing: C:\Users\lexua\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +10 ms] Skipping pub get: version match.
[  +26 ms] Found plugin path_provider at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[   +5 ms] Found plugin path_provider_linux at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +1 ms] Found plugin path_provider_macos at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[  +27 ms] Found plugin integration_test at D:\flutter\packages\integration_test\
[ +245 ms] Found plugin path_provider at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.28\
[        ] Found plugin path_provider_linux at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[        ] Found plugin path_provider_macos at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at D:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.5\
[  +17 ms] Found plugin integration_test at D:\flutter\packages\integration_test\
[   +4 ms] Generating D:\work\flutter_project\flutter_youtube_downloader\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +97 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +3 ms] complete
[   +3 ms] Launching lib\main.dart on Windows in debug mode...
[   +3 ms] D:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\lexua\AppData\Local\Temp\flutter_tools.d71ec85e\flutter_tool.7a53d214\app.dill --packages D:\work\flutter_project\flutter_youtube_downloader\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --initialize-from-dill build\ec97fc97316ce73f47c62e6f5be0e204.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +17 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +26 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "5efe6f22",
               "installDate": "2021-01-20T11:35:03Z",
               "installationName": "VisualStudio/16.8.4+30907.101",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.8.30907.101",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.8.4",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2021-01-20T11:35:03.9749563Z",
               "catalog": {
                 "buildBranch": "d16.8",
                 "buildVersion": "16.8.30907.101",
                 "id": "VisualStudio/16.8.4+30907.101",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.8.4",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "4",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.8.4+30907.101",
                 "requiredEngineVersion": "2.8.3267.30329"
               },
               "properties": {
                 "campaignId": "",
                 "channelManifestId": "VisualStudio.16.Release/16.8.4+30907.101",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
Building Windows application...
[  +32 ms] <- compile package:flutter_youtube_downloader/main.dart
[   +1 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S D:\work\flutter_project\flutter_youtube_downloader\windows -B build\windows -G Visual Studio 16 2019
[  +16 ms] List of devices attached
[   +2 ms] List of devices attached
[  +42 ms] -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
[  +15 ms] -- Configuring done
[ +369 ms] -- Generating done
[  +25 ms] -- Build files have been written to: D:/work/flutter_project/flutter_youtube_downloader/build/windows
[   +5 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build build\windows --config Debug --target INSTALL --verbose
[ +137 ms] Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[  +56 ms] Build started 07/06/2021 10:05:36 pm.
[ +269 ms] Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\INSTALL.vcxproj" on node 1 (default targets).
[        ] Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\INSTALL.vcxproj" (1) is building "D:\work\flutter_project\flutter_youtube_downloader\build\windows\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +96 ms] Error: Cannot run with sound null safety, because the following dependencies
[        ] don't support null safety:
[        ]  - package:process_run
[        ]  - package:path_provider
[        ]  - package:path_provider_linux
[        ]  - package:path_provider_windows
[        ]  - package:path_provider_platform_interface
[        ]  - package:xdg_directories
[        ]  - package:plugin_platform_interface
[        ]  - package:args
[        ] For solutions, see https://dart.dev/go/unsound-null-safety
[  +37 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +66 ms]   Checking Build System
[  +79 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
[        ] Done Building Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\ZERO_CHECK.vcxproj" (default targets).
[ +122 ms] Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\INSTALL.vcxproj" (1) is building "D:\work\flutter_project\flutter_youtube_downloader\build\windows\ALL_BUILD.vcxproj" (3) on node 1 (default targets).
[        ] Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\ALL_BUILD.vcxproj" (3) is building "D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_wrapper_app.vcxproj" (4) on node 1 (default targets).
[        ] Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_wrapper_app.vcxproj" (4) is building "D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj" (5) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Touching "x64\Debug\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[   +2 ms] CustomBuild:
[        ]   "The build of 'D:\work\flutter_project\flutter_youtube_downloader\build\windows\CMakeFiles\782162d8d25b8edf7b0745f9e3b80bb9\flutter_assemble.rule' depends on 'D:\WORK\FLUTTER_PROJECT\FLUTTER_YOUTUBE_DOWNLOADER\WINDOWS\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS.DLL' which is produced by the build of 'D:\work\flutter_project\flutter_youtube_downloader\build\windows\CMakeFiles\079a7490c25e8a1e7333fe16494562a7\flutter_windows.dll.rule'. The items cannot be built in parallel."
[  +46 ms]   Generating D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/flutter_windows.dll, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/flutter_export.h, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/flutter_windows.h, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/flutter_messenger.h, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/flutter_plugin_registrar.h, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/flutter_texture_registrar.h, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/cpp_client_wrapper/core_implementations.cc, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/cpp_client_wrapper/standard_codec.cc, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/cpp_client_wrapper/plugin_registrar.cc, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/cpp_client_wrapper/flutter_engine.cc, D:/work/flutter_project/flutter_youtube_downloader/windows/flutter/ephemeral/cpp_client_wrapper/flutter_view_controller.cc, _phony_
[+1373 ms]   [  +72 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +401 ms]   [ +425 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ]   [        ] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ]   [        ] executing: [D:\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +72 ms]   [  +72 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ]   [        ] 2.2.1
[   +5 ms]   [   +5 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +44 ms]   [  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ]   [        ] origin/stable
[        ]   [        ] executing: [D:\flutter/] git ls-remote --get-url origin
[  +43 ms]   [  +43 ms] Exit code 0 from: git ls-remote --get-url origin
[        ]   [        ] https://github.com/flutter/flutter.git
[  +58 ms]   [  +58 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[  +44 ms]   [  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ]   [        ] stable
[  +59 ms]   [  +59 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms]   [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +100 ms]   [ +100 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +2 ms]   [   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +34 ms]   [  +34 ms] Initializing file store
[  +18 ms]   [  +18 ms] Done initializing file store
[  +52 ms]   [  +52 ms] Skipping target: gen_localizations
[+2812 ms]   [+2812 ms] Skipping target: unpack_windows
[ +269 ms]   [ +269 ms] kernel_snapshot: Starting due to {}
[   +9 ms]   [   +9 ms] D:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev D:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root D:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --packages D:\work\flutter_project\flutter_youtube_downloader\.dart_tool\package_config.json --output-dill D:\work\flutter_project\flutter_youtube_downloader\.dart_tool\flutter_build\0e7aff9ed8fbf48d9f2fb70b6b9d13ef\app.dill --depfile D:\work\flutter_project\flutter_youtube_downloader\.dart_tool\flutter_build\0e7aff9ed8fbf48d9f2fb70b6b9d13ef\kernel_snapshot.d package:flutter_youtube_downloader/main.dart
[+1052 ms] CUSTOMBUILD : [+1046 ms] error : Cannot run with sound null safety, because the following dependencies [D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj]
[        ]   [   +1 ms] don't support null safety:
[        ]   [        ]  - package:process_run
[        ]   [        ]  - package:path_provider
[        ]   [        ]  - package:path_provider_linux
[        ]   [        ]  - package:path_provider_windows
[        ]   [        ]  - package:path_provider_platform_interface
[        ]   [        ]  - package:xdg_directories
[        ]   [        ]  - package:plugin_platform_interface
[        ]   [        ]  - package:args
[        ]   [        ] For solutions, see https://dart.dev/go/unsound-null-safety
[+8082 ms]   [+8088 ms] Persisting file store
[  +10 ms]   [  +11 ms] Done persisting file store
[   +2 ms]   [   +2 ms] Target kernel_snapshot failed: Exception
[        ]              #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:291:7)
[        ]              <asynchronous suspension>
[        ]              #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
[        ]              <asynchronous suspension>
[        ]              #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]              <asynchronous suspension>
[        ]              #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]              <asynchronous suspension>
[        ]              #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
[        ]              <asynchronous suspension>
[        ]              #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
[        ]              <asynchronous suspension>
[        ]              #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]              <asynchronous suspension>
[        ]              #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]              <asynchronous suspension>
[        ]              #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]              <asynchronous suspension>
[        ]              #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]              <asynchronous suspension>
[        ]              #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]              <asynchronous suspension>
[        ]              #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #14     main (package:flutter_tools/executable.dart:91:3)
[        ]              <asynchronous suspension>
[   +6 ms]   [  +10 ms] "flutter assemble" took 12,482ms.
[   +5 ms]   [   +5 ms] 
[        ]              #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]              #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:335:7)
[        ]              <asynchronous suspension>
[        ]              #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]              <asynchronous suspension>
[        ]              #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]              <asynchronous suspension>
[        ]              #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]              <asynchronous suspension>
[        ]              #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]              <asynchronous suspension>
[        ]              #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]              <asynchronous suspension>
[        ]              #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]              <asynchronous suspension>
[        ]              #10     main (package:flutter_tools/executable.dart:91:3)
[        ]              <asynchronous suspension>
[ +266 ms]   [ +268 ms] ensureAnalyticsSent: 267ms
[        ]   [   +1 ms] Running shutdown hooks
[        ]   [        ] Shutdown hooks complete
[        ]   [        ] exiting with code 1
[   +1 ms] Done Building Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj" (default targets) -- FAILED.
[  +52 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'D:\work\flutter_project\flutter_youtube_downloader\build\windows\CMakeFiles\079a7490c25e8a1e7333fe16494562a7\flutter_windows.dll.rule;D:\work\flutter_project\flutter_youtube_downloader\build\windows\CMakeFiles\782162d8d25b8edf7b0745f9e3b80bb9\flutter_assemble.rule' exited with code 1. [D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj]
[        ] Done Building Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_wrapper_app.vcxproj" (default targets) -- FAILED.
[  +62 ms] Done Building Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\ALL_BUILD.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "D:\work\flutter_project\flutter_youtube_downloader\build\windows\INSTALL.vcxproj" (default targets) -- FAILED.
[        ] Build FAILED.
[   +7 ms] "D:\work\flutter_project\flutter_youtube_downloader\build\windows\INSTALL.vcxproj" (default target) (1) ->
[        ] "D:\work\flutter_project\flutter_youtube_downloader\build\windows\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_wrapper_app.vcxproj" (default target) (4) ->
[        ] "D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj" (default target) (5) ->
[        ] (CustomBuild target) -> 
[        ]   CUSTOMBUILD : [+1046 ms] error : Cannot run with sound null safety, because the following dependencies [D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj]
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'D:\work\flutter_project\flutter_youtube_downloader\build\windows\CMakeFiles\079a7490c25e8a1e7333fe16494562a7\flutter_windows.dll.rule;D:\work\flutter_project\flutter_youtube_downloader\build\windows\CMakeFiles\782162d8d25b8edf7b0745f9e3b80bb9\flutter_assemble.rule' exited with code 1. [D:\work\flutter_project\flutter_youtube_downloader\build\windows\flutter\flutter_assemble.vcxproj]
[        ]     0 Warning(s)
[        ]     2 Error(s)
[        ] Time Elapsed 00:00:15.69
[  +12 ms] Exception: Build process failed.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +11 ms] "flutter run" took 17,084ms.
```

**Comment by stuartmorgan** [comment]
> [  +96 ms] Error: Cannot run with sound null safety, because the following dependencies
> [        ] don't support null safety:
> [        ]  - package:process_run
> [        ]  - package:path_provider
> [        ]  - package:path_provider_linux
> [        ]  - package:path_provider_windows
> [        ]  - package:path_provider_platform_interface
> [        ]  - package:xdg_directories
> [        ]  - package:plugin_platform_interface
> [        ]  - package:args
> [        ] For solutions, see https://dart.dev/go/unsound-null-safety

You've attempted to enable null safety without updating your dependencies. That's not a valid build mode without extra flags.
