### ISSUE TITLE
Invalid BoxConstraints

### ISSUE THREAD

**Issue by enjalot** [flutter/flutter#8413]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

I'm consistently getting the following error when I tap on my TextField. I've tried several combinations of layouts, stripping everything down as much as possible and it still happens

The layout code is a page within a TabView and returns a scaffold like:
```dart
return new Scaffold(
      key: _scaffoldKey,
      body: new Form(
        key: _formKey,
          child: new ListView(
            children: [
              new TextField(
                labelText: "Add comment",
                onSaved: (InputValue val) { _comment = val.text; },
              )
            ]
          )
      )
    );
```

What i really want is to have an input anchored to the bottom of the screen, so I was using a Stack layout where my first non-positioned element was a ListView and then I positioned a Row containing my input. I didn't know if that was the problem so I stripped things down to the code above.

## Logs

Run your application with `flutter run` and attach all the log output.
```
I/flutter (13963): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13963): The following assertion was thrown during performLayout():
I/flutter (13963): The _ScaffoldLayout custom multichild layout delegate provided invalid box constraints for the child
I/flutter (13963): with id "_ScaffoldSlot.body".
I/flutter (13963): BoxConstraints has non-normalized height constraints.
I/flutter (13963): The offending constraints were:
I/flutter (13963):   BoxConstraints(0.0<=w<=411.4, 0.0<=h<=-134.1; NOT NORMALIZED)
I/flutter (13963): The minimum width and height must be greater than or equal to zero.
I/flutter (13963): The maximum width must be greater than or equal to the minimum width.
I/flutter (13963): The maximum height must be greater than or equal to the minimum height.
I/flutter (13963): 
I/flutter (13963): When the exception was thrown, this was the stack:
I/flutter (13963): #0      MultiChildLayoutDelegate.layoutChild.<anonymous closure> (package:flutter/src/rendering/custom_layout.dart:114:9)
I/flutter (13963): #2      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:98:12)
I/flutter (13963): #3      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:86:7)
I/flutter (13963): #4      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter (13963): #5      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter (13963): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #7      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #9      RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #11     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #13     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #15     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:71:18)
I/flutter (13963): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #17     RenderViewportBase.layoutOneSide (package:flutter/src/rendering/viewport.dart:139:13)
I/flutter (13963): #18     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:688:12)
I/flutter (13963): #19     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:617:20)
I/flutter (13963): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #21     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #23     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #27     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:100:13)
I/flutter (13963): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1741:7)
I/flutter (13963): #33     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:124:11)
I/flutter (13963): #34     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:86:7)
I/flutter (13963): #35     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:194:7)
I/flutter (13963): #36     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:338:14)
I/flutter (13963): #37     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1617:7)
I/flutter (13963): #38     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:952:18)
I/flutter (13963): #39     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:225:19)
I/flutter (13963): #40     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:333:23)
I/flutter (13963): #41     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:170:5)
I/flutter (13963): #42     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:676:15)
I/flutter (13963): #43     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:611:9)
I/flutter (13963): #44     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:83)
I/flutter (13963): (elided one frame from class _AssertionError)
I/flutter (13963): 
I/flutter (13963): The following RenderObject was being processed when the exception was fired:
I/flutter (13963):   RenderCustomMultiChildLayoutBox#14098452 NEEDS-LAYOUT
I/flutter (13963):   creator: CustomMultiChildLayout ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (13963):   _InkFeatures-[GlobalKey ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (13963):   DecoratedBox ← Container ← DecoratedBox ← Container ← AnimatedContainer ← Material ←
I/flutter (13963):   PrimaryScrollController ← ⋯
I/flutter (13963):   parentData: <none>
I/flutter (13963):   constraints: BoxConstraints(w=411.4, h=210.7)
I/flutter (13963):   size: Size(411.4, 210.7)
I/flutter (13963): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (13963):   RenderConstrainedBox#346250651 relayoutBoundary=up1
I/flutter (13963):     RenderRepaintBoundary#769642433 relayoutBoundary=up2
I/flutter (13963):       RenderCustomPaint#701376685 relayoutBoundary=up3
I/flutter (13963):         RenderRepaintBoundary#720595033 relayoutBoundary=up4
I/flutter (13963):           RenderSemanticsGestureHandler#244020802 relayoutBoundary=up5
I/flutter (13963):   RenderStack#99136739 relayoutBoundary=up1
I/flutter (13963): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.
```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/enjalot/code/oss/flutter
    • Framework revision a002e72022 (26 hours ago), 2017-02-23 15:08:25
    • Engine revision ab09530927
    • Tools Dart version 1.23.0-dev.0.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /Users/enjalot/Library/Android/sdk
    • Platform android-25, build-tools 25.0.0
    • Java Development Kit (JDK) found: javac 1.8.0_111

[-] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    ✗ ios-deploy not installed: 1.9.0 is required.
      Install via 'brew install ios-deploy'.

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.2)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.8.1

[✓] Connected devices
    • Nexus 5X • 00fb6af11580afd0 • android-arm • Android 7.1.1 (API 25)

```
> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by abarth** [comment]
Thanks for the report.  Fix in https://github.com/flutter/flutter/pull/8415
