### ISSUE TITLE
Path provider null error

### ISSUE THREAD

**Issue by evolvingkid** [flutter/flutter#84174]
i add path provider and use
`
Directory appDocDir = await getApplicationDocumentsDirectory();
`
It causes error

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 5490): #0      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:148
E/flutter ( 5490): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:155
E/flutter ( 5490): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:339
E/flutter ( 5490): #3      MethodChannelPathProvider.getApplicationDocumentsPath
package:path_provider_platform_interface/src/method_channel_path_provider.dart:50
E/flutter ( 5490): #4      getApplicationDocumentsDirectory
package:path_provider/path_provider.dart:138
E/flutter ( 5490): #5      main
package:bootcamp/main.dart:9
E/flutter ( 5490): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 5490): #7      _rootRun (dart:async/zone.dart:1354:13)

**Comment by evolvingkid** [comment]
it was because of WidgetsFlutterBinding.ensureInitialized(); on initailze.
