### ISSUE TITLE
package:flutter/src/rendering/object.dart: Failed assertion: line 2653 pos 12: '!_needsLayout'

### ISSUE THREAD

**Issue by dulkith** [flutter/flutter#84173]
Flutter app crash randomly when running on an android device.

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#c43c7 NEEDS-LAYOUT to calculate
semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2653 pos 12: '!_needsLayout'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2653:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#4      Iterable.forEach (dart:core/iterable.dart:257:30)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)
#6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#7      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#8      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#9      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#10     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#11     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#12     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#13     Iterable.forEach (dart:core/iterable.dart:257:30)
#14     RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:222:10)
#15     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#16     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#17     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3266:14)
#18     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#19     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#20     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#21     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#22     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4663:11)
#23     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#24     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#25     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#26     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#27     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#28     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#29     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#30     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#31     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#32     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#33     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#34     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#35     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#36     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#37     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#38     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#39     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#40     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#41     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#42     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#43     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#44     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#45     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#46     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#47     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#48     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#49     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#50     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#51     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#52     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#53     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3331:14)
#54     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#55     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#56     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#57     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#58     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#59     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#60     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#61     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#62     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#63     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#64     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#65     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#66     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#67     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#68     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#69     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3331:14)
#70     RenderSliverMultiBoxAdaptor.visitChildrenForSemantics (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:398:11)
#71     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#72     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#73     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#74     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#75     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#76     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#77     Iterable.forEach (dart:core/iterable.dart:257:30)
#78     RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:222:10)
#79     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#80     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#81     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3266:14)
#82     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#83     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#84     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#85     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#86     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4663:11)
#87     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#88     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#89     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#90     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#91     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#92     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#93     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#94     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#95     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#96     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#97     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#98     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#99     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#100    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2675:61)
#101    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3048:14)
#102    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2760:5)
#103    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
#104    RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2631:41)
#105    PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1076:16)
#106    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:467:21)
#107    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#108    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#109    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#110    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#111    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#115    _invoke (dart:ui/hooks.dart:163:10)
#116    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#117    _drawFrame (dart:ui/hooks.dart:126:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
I/System.out(24521): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(24521): (HTTPLog)-Static: isSBSettingEnabled false
Lost connection to device.

```

`flutter doctor`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode not installed; this is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)
    ! Device 192.168.8.140:5555 is offline.

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@dulkith 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?

**Comment by dulkith** [comment]
The special page or wideget where this error occurred was accidentally received this exception

`flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/Dulkith/Documents/development/flutter
    • Framework revision 02c026b03c (12 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Dulkith/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode not installed; this is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77

```

**Comment by darshankawar** [comment]
@dulkith 
Also please provide a reproducible code sample that we can directly use to verify this.

Thanks.

**Comment by dulkith** [comment]
> @dulkith
> Also please provide a reproducible code sample that we can directly use to verify this.
> 
> Thanks.

There is no specific code sample for this error, Randomly I got this error after update flutter.

**Comment by darshankawar** [comment]
@dulkith 
It seems to be coming from `flutter_staggered_grid_view` plugin:

`RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)`

If you remove that plugin code and try again, does it replicate the issue ?

See another similar issue that we closed pertaining to that plugin, https://github.com/flutter/flutter/issues/81182

**Comment by gabrielamota29** [comment]
For the support, I had the same issue. I will investigate how I got the error since It happened and I was not paying attention to the part of the code that I was executing. 

Here are the logs:

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderIndexedSemantics#31dd4 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2653 pos 12: '!_needsLayout'

2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      RenderObject._getSemanticsForParent
package:flutter/…/rendering/object.dart:2653
#3      RenderObject._getSemanticsForParent.<anonymous closure>
package:flutter/…/rendering/object.dart:2675
#4      Iterable.forEach (dart:core/iterable.dart:257:30)
#5      RenderSliverVariableSizeBoxAdaptor.visitChildren
package:flutter_staggered_grid_view/…/rendering/sliver_variable_size_box_adaptor.dart:296
#6      RenderObject.visitChildrenForSemantics
package:flutter/…/rendering/object.dart:2760
...
════════════════════════════════════════════════════════════════════════════════
