### ISSUE TITLE
App Stops when Android alarm  manager flutter runs when app is in background

### ISSUE THREAD

**Issue by ifeoluwajoshua** [flutter/flutter#84186]
The application gets killed when app runs in the background it works well in foreground

error from debug console

Starting AlarmService... W/FlutterEngineCxnRegstry(23646): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@63fd595) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@27f86aa). E/AndroidRuntime(23646): FATAL EXCEPTION: main E/AndroidRuntime(23646): Process: com.joart.agroai, PID: 23646 E/AndroidRuntime(23646): java.lang.RuntimeException: Unable to create service io.flutter.plugins.androidalarmmanager.AlarmService: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference E/AndroidRuntime(23646): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3377) E/AndroidRuntime(23646): at android.app.ActivityThread.-wrap4(Unknown Source:0) E/AndroidRuntime(23646): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1702) E/AndroidRuntime(23646): at android.os.Handler.dispatchMessage(Handler.java:106) E/AndroidRuntime(23646): at android.os.Looper.loop(Looper.java:164) E/AndroidRuntime(23646): at android.app.ActivityThread.main(ActivityThread.java:6524) E/AndroidRuntime(23646): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime(23646): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:451) E/AndroidRuntime(23646): at com.

flutter doctor - v

C:\Users\Ayomide\Desktop\agroai>flutter doctor -v
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.0 at C:\src\flutter\flutter
    • Framework revision 60bd88df91 (3 months ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at C:\Users\Ayomide\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Ayomide\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!

**Comment by ifeoluwajoshua** [comment]
alright thanks
