### ISSUE TITLE
flutter generates unnecessary "drawable" folder causing runtime exeption!

### ISSUE THREAD

**Issue by cmedamine** [flutter/flutter#84297]
![github issue](https://user-images.githubusercontent.com/68339403/121423992-bd9e9300-c968-11eb-9995-9a485dd7f8b8.png)

```
E/AndroidRuntime(30175): FATAL EXCEPTION: main
E/AndroidRuntime(30175): Process: com.example.avito_clone_demo, PID: 30175
E/AndroidRuntime(30175): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.avito_clone_demo/com.example.avito_clone_demo.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040015
E/AndroidRuntime(30175): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
E/AndroidRuntime(30175): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
E/AndroidRuntime(30175): 	at android.app.ActivityThread.access$1200(ActivityThread.java:152)
E/AndroidRuntime(30175): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
E/AndroidRuntime(30175): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30175): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(30175): 	at android.app.ActivityThread.main(ActivityThread.java:5538)
E/AndroidRuntime(30175): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30175): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(30175): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime(30175): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/AndroidRuntime(30175): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040015
E/AndroidRuntime(30175): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2450)
E/AndroidRuntime(30175): 	at android.content.res.Resources.loadDrawable(Resources.java:2350)
E/AndroidRuntime(30175): 	at android.content.res.HwResources.loadDrawable(HwResources.java:589)
E/AndroidRuntime(30175): 	at android.content.res.Resources.getDrawable(Resources.java:772)
E/AndroidRuntime(30175): 	at android.content.res.Resources.getDrawable(Resources.java:738)
E/AndroidRuntime(30175): 	at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:493)
E/AndroidRuntime(30175): 	at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:469)
E/AndroidRuntime(30175): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:301)
E/AndroidRuntime(30175): 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:518)
Launching lib\main.dart on hi6210sft in debug mode...
lib\main.dart:1
Note: C:\Development\flutter-sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.1\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Note: C:\Development\flutter-sdk\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.3.0\android\src\main\java\io\flutter\plugins\firebase\auth\FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build\app\outputs\flutter-apk\app-debug.apk.
E/AndroidRuntime(30175): FATAL EXCEPTION: main
E/AndroidRuntime(30175): Process: com.example.avito_clone_demo, PID: 30175
E/AndroidRuntime(30175): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.avito_clone_demo/com.example.avito_clone_demo.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040015
E/AndroidRuntime(30175): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
E/AndroidRuntime(30175): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
E/AndroidRuntime(30175): 	at android.app.ActivityThread.access$1200(ActivityThread.java:152)
E/AndroidRuntime(30175): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
E/AndroidRuntime(30175): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30175): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(30175): 	at android.app.ActivityThread.main(ActivityThread.java:5538)
E/AndroidRuntime(30175): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30175): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(30175): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime(30175): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```
```
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Development\android-sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Development\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Nxer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

• No issues found!
```

**Comment by npsulav** [comment]
``` File res/drawable-v21/launch_background.xml from drawable resource ID #0x7f040015```
This means you are using `launch_background.xm`l from `drawable-v21` but `drawable-v21` does not contain any `launch_background.xml`.
you can copy the `launch_background.xml` from `drawable` to `drawable-v21` and it should work without any error.

**Comment by cmedamine** [comment]
do you get the same error every time you lunch the app???

**Comment by TahaTesser** [comment]
Hi @cmedamine

[Template](https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/templates/app/android.tmpl/app/src/main/res/drawable-v21/launch_background.xml) does add this folder but it won't throw any errors unless you modified your project.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
