### ISSUE TITLE
Package image_picker: ^0.8.0+3 =>  PlatformException(already_active, Image picker is already active, null, null)

### ISSUE THREAD

**Issue by hello-deepak** [flutter/flutter#84324]
I am using the current version of  image_picker: ^0.8.0+3.

Minimal Code : 

```
_imgFromCamera() async {
    try {
     
      final pickedFile =
          await _picker.getImage(source: ImageSource.camera);
      setState(() {
        _imageFile = pickedFile;
      });
      _setImagePath(pickedFile.path);
    } catch (e) {
      print("camera pick error: " + e.toString());
    }
  }

  _imgFromGallery() async {
    try {
   
      final pickedFile =
          await _picker.getImage(source: ImageSource.gallery);

      setState(() {
        _imageFile = pickedFile;
      });
      _setImagePath(pickedFile.path);
    } catch (e) {
      print("gallery pick error: " + e.toString());
    }
  }


```

Error is producing when clicking to access the camera, well  its asking the permission first then giving the below error.
<details>
<summary>Error Logs</summary>

```

D/ViewRootImpl[MainActivity]( 4863): windowFocusChanged hasFocus=false inTouchMode=true
D/AndroidRuntime( 4863): Shutting down VM
E/AndroidRuntime( 4863): FATAL EXCEPTION: main
E/AndroidRuntime( 4863): Process: iheritage.icimod.iheritage, PID: 4863
E/AndroidRuntime( 4863): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2345, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {iheritage.icimod.iheritage/iheritage.icimod.iheritage.MainActivity}: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider
E/AndroidRuntime( 4863): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5209)
E/AndroidRuntime( 4863): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5250)
E/AndroidRuntime( 4863): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 4863): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 4863): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 4863): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
E/AndroidRuntime( 4863): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4863): 	at android.os.Looper.loop(Looper.java:245)
E/AndroidRuntime( 4863): 	at android.app.ActivityThread.main(ActivityThread.java:8004)
E/AndroidRuntime( 4863): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4863): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime( 4863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
E/AndroidRuntime( 4863): Caused by: java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider
E/AndroidRuntime( 4863): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/AndroidRuntime( 4863): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/AndroidRuntime( 4863): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/AndroidRuntime( 4863): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$3.resolveFileProviderUriForFile(ImagePickerDelegate.java:158)
E/AndroidRuntime( 4863): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:363)
E/AndroidRuntime( 4863): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onRequestPermissionsResult(ImagePickerDelegate.java:413)
E/AndroidRuntime( 4863): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
E/AndroidRuntime( 4863): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
E/AndroidRuntime( 4863): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
E/AndroidRuntime( 4863): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:648)
E/AndroidRuntime( 4863): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8472)
E/AndroidRuntime( 4863): 	at android.app.Activity.dispatchActivityResult(Activity.java:8320)
E/AndroidRuntime( 4863): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5202)
E/AndroidRuntime( 4863): 	... 11 more
I/Process ( 4863): Sending signal. PID: 4863 SIG: 9
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"163","method":"getMemoryUsage","params":{"isolateId":"isolates/4185999271076303"}}
```
</details>

And after that if I try to access it again: 

<details>
<summary>Error Log: </summary>

```
E/MethodChannel#plugins.flutter.io/image_picker(26826): Failed to handle method call
E/MethodChannel#plugins.flutter.io/image_picker(26826): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$3.resolveFileProviderUriForFile(ImagePickerDelegate.java:158)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:363)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:337)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:299)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at android.os.Looper.loop(Looper.java:195)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at android.app.ActivityThread.main(ActivityThread.java:8004)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/MethodChannel#plugins.flutter.io/image_picker(26826): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
I/flutter (26826): gallery pick error: PlatformException(error, Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider, null, java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider
I/flutter (26826): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
I/flutter (26826): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
I/flutter (26826): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
I/flutter (26826): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$3.resolveFileProviderUriForFile(ImagePickerDelegate.java:158)
I/flutter (26826): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:363)
I/flutter (26826): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:337)
I/flutter (26826): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:299)
I/flutter (26826): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHan
```
</details>

And after that: 

<details>
<summary>Error log</summary>

```
PlatformException(already_active, Image picker is already active, null, null)
```
</details>

**Comment by darshankawar** [comment]
@hello-deepak Hi,
Is this same issue as you already reported https://github.com/flutter/flutter/issues/83985 ?
Did you get a chance to do https://github.com/flutter/flutter/issues/83985#issuecomment-856489466 ?

**Comment by hello-deepak** [comment]
hi @darshankawar 

Yes, it's the same issue.

Except as per 0.8.0+3 version of image_picker, now its asking permission to use camera but the error is same.

**Comment by darshankawar** [comment]
Keeping it open for further insights from team.

Cc: @ydag

**Comment by renefloor** [comment]
@hello-deepak I'm not able to reproduce it with your example. Can you tell a bit more about the device? Are you having this issue on every Android device, or a specific one? Also the Android version would be useful.

When I run your code `_imgFromCamera` the plugin doesn't ask for permission, so this doesn't really seem like a complete minimal example. If you create a github repo with a complete (but minimal) app example I'm willing to dig into it further.

The following line of your crash log seems most relevant to me.
>Couldn't find meta-data for provider with authority iheritage.icimod.iheritage.flutter.image_provider

However, this seems ok to me: 
https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/android/src/main/AndroidManifest.xml#L10-L12
https://github.com/flutter/plugins/blob/master/packages/image_picker/image_picker/android/src/main/res/xml/flutter_image_picker_file_paths.xml

**Comment by hello-deepak** [comment]
Thank you @darshankawar and @renefloor 

Now its working after removing all the permission such as 
```

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.FLASHLIGHT" />
 <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>
```

and putting the following queries

```
 <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
    </queries>
```
