### ISSUE TITLE
Generating tree maps for Linux Android AOT release builds sometimes fails

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#84377]
See:

1. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/10487/overview
2. https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/23413/overview
3. https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/23440/overview

This is happening sporadically.

**Comment by godofredoc** [comment]
This seems like a build problem. Removing from infra queue.

**Comment by godofredoc** [comment]
The flakes started after this change:

https://flutter-review.googlesource.com/c/recipes/+/14501
https://flutter-review.googlesource.com/c/recipes/+/14501/7/recipes/engine.py#592

**Comment by yusufm** [comment]
Here is the location where the max_concurrent_invocations is specificed:

https://devops-console-oss.corp.google.com/flutter/infra/+/master:config/engine_config.star;l=242

**Comment by iskakaushik** [comment]
After investigating https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/10487/overview. I wanted to validate the failing `nm` check on the `libflutter.so` file. I downloaded `libflutter.so` from [the right shard](https://isolateserver.appspot.com/browse?namespace=default-gzip&hash=72abc864eea1260eddc89371fd9a932173870eb0). To do this I had to:

1. `git clone https://chromium.googlesource.com/infra/luci/luci-py`
2. `python isolateserver.py download -I isolateserver.appspot.com --namespace default-gzip -f 6467a7082bc2ff13d34d7039d47d2e259791cf68 libflutter.so`

Running `nm` on this seems to correctly print the symbols. This makes me suspect that something went wrong with the `api.isolate.download` call or after that. I'm going to add additional debug commands to print debug details about the file (size, running file command on it) etc. Would appreciate additional ideas to debug this bizzare failure.

ccing some folks who I think could have some ideas: @jason-simmons , @chinmaygarde 

copying the [stack trace](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8844783636082617649/+/u/Upload_artifacts_android-arm-release/generate_treemap_for_android-arm-release/stdout) here for ease of reference:

```
addr2line: /b/s/w/ir/cache/builder/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-addr2line
nm: /usr/bin/nm
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/third_party/dart/runtime/third_party/binary_size/src/run_binary_size_analysis.py", line 710, in <module>
    sys.exit(main())
  File "/b/s/w/ir/cache/builder/src/third_party/dart/runtime/third_party/binary_size/src/run_binary_size_analysis.py", line 691, in main
    symbols = GetNmSymbols(opts.nm_in, nm_out, opts.library, opts.jobs,
  File "/b/s/w/ir/cache/builder/src/third_party/dart/runtime/third_party/binary_size/src/run_binary_size_analysis.py", line 398, in GetNmSymbols
    RunElfSymbolizer(outfile, library, addr2line_binary, nm_binary, jobs,
  File "/b/s/w/ir/cache/builder/src/third_party/dart/runtime/third_party/binary_size/src/run_binary_size_analysis.py", line 246, in RunElfSymbolizer
    nm_output = RunNm(library, nm_binary)
  File "/b/s/w/ir/cache/builder/src/third_party/dart/runtime/third_party/binary_size/src/run_binary_size_analysis.py", line 383, in RunNm
    raise Exception(err_output)
Exception: b'/usr/bin/nm: /b/s/w/ir/cache/builder/src/out/android_release/libflutter.so: File format not recognized\n'
```

**Comment by iskakaushik** [comment]
This hasn't happened since the last 100 try builds and 30 prod builds. I've added additional logging in https://flutter-review.googlesource.com/c/recipes/+/14561 and https://flutter-review.googlesource.com/c/recipes/+/14582. I will keep it open and reduce the priority to reprioritize root-causing this if this happens again.
