### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/usr/bin/xcodebuild -listInformation about project "Runner":    Targets:        Runner    Build Configurations:        Debug        Release        Profile    If no build configuration is specified and -scheme is not passed then "Release" is used.    Schemes:        Runner Command: xcrun, OS error code: -11

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#84381]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8844920638476138192/+/u/run_test.dart_for_build_tests_shard_and_subshard_4_4/stdout

## Command
```
flutter build ios --no-codesign --debug -v
```

## Logs
```
ProcessException: Process exited abnormally:
Command line invocation:
    /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/usr/bin/xcodebuild -list

Information about project "Runner":
    Targets:
        Runner

    Build Configurations:
        Debug
        Release
        Profile

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        Runner Command: xcrun, OS error code: -11
```
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:241:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:651:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:619:36)
<asynchronous suspension>
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:562:51)
<asynchronous suspension>
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:539:41)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:118:36)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:84:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp (package:flutter_tools/src/commands/build_ios.dart:216:26)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:248:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel unknown, 2.3.0-17.0.pre.276, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 2.3.0-17.0.pre.276 at /opt/s/w/ir/x/w/flutter
    • Upstream repository unknown
    • Framework revision b7f9859725 (34 minutes ago), 2021-06-09 16:21:04 +0900
    • Engine revision 132669b021
    • Dart version 2.14.0 (build 2.14.0-189.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/s/w/ir/cache/android
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /opt/s/w/ir/cache/android
    • ANDROID_SDK_ROOT = /opt/s/w/ir/cache/android
    • Java binary at: /opt/s/w/ir/cache/java/contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/s/w/ir/cache/chrome/chrome/chrome-mac/Chromium.app/Contents/MacOS/Chromium

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Chromium 84.0.4147.0

! Doctor found issues in 1 category.

```

**Comment by darshankawar** [comment]
Sharing my findings here:

Ran the command `flutter build ios --no-codesign --debug` on latest stable version (3.3.4) which completed as expected without throwing the report error.

```
dhs@Dhss-MacBook-Pro test_app % flutter build ios --no-codesign --debug   
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building com.example.testApp for device (ios)...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      1,889ms
Xcode build done.                                            5.7s
Built /Users/dhs/Documents/NCFlutter/test_app/build/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro test_app % 
```

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
[✓] VS Code (version 1.62.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by vashworth** [comment]
Closing.
