### ISSUE TITLE
Can't run my app on Windows

### ISSUE THREAD

**Issue by AhmedAbouelkher** [flutter/flutter#84420]
## Steps to Reproduce

1. Create a new Flutter project.
2. Run on Windows.

**Expected results:** 
The app can't be built due to `CMake` error.

**Actual results:** 
The app should run normally.

<details>
  <summary>Logs</summary>

```
PS D:\Flutter Project\Archive\WORKING Project\flutter_application_1> flutter run --verbose

[  +48 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +298 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] executing: [C:\flutter/] git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[  +20 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] 2.2.1
[   +4 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin     
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +197 ms] Unable to locate an Android SDK.
[   +5 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +43 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +69 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.    
[  +50 ms] Multiple devices found:
[  +17 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.985]
[        ] Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.101
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.37
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[+5041 ms] 1
[   +8 ms] Skipping pub get: version match.
[  +76 ms] Generating D:\Flutter Project\Archive\WORKING Project\flutter_application_1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +72 ms] Initializing file store
[   +6 ms] Skipping target: gen_localizations
[   +4 ms] complete
[   +2 ms] Launching lib\main.dart on Windows in debug mode...
[   +3 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata        
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\Ahmed\AppData\Local\Temp\flutter_tools.d71c4fd4\flutter_tool.55c8ac63\app.dill --packages D:\Flutter
Project\Archive\WORKING Project\flutter_application_1\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +22 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[  +21 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] [
             {
               "instanceId": "c3b94b18",
               "installDate": "2021-06-11T08:04:01Z",
               "installationName": "VisualStudio/16.0.2+28803.202",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise",
               "installationVersion": "16.0.28803.202",
               "productId": "Microsoft.VisualStudio.Product.Enterprise",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Enterprise 2019",
               "description": "Microsoft DevOps solution for productivity and coordination across teams of any size",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "installChannelUri": "E:\\ChannelManifest.json",
               "layoutPath": "E:\\",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.0.2",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2021-06-11T08:04:01.7565208Z",
               "catalog": {
                 "buildBranch": "d16.0",
                 "buildVersion": "16.0.28803.202",
                 "id": "VisualStudio/16.0.2+28803.202",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.0.2",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "2",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.0.2+28803.202",
                 "requiredEngineVersion": "2.0.3297.47373"
               },
               "properties": {
                 "campaignId": "",
                 "channelManifestId": "VisualStudio.16.Release/16.0.2+28803.202",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[   +5 ms] Building Windows application...
[   +6 ms] <- compile package:flutter_application_1/main.dart
[   +2 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S D:\Flutter 
Project\Archive\WORKING Project\flutter_application_1\windows -B build\windows -G Visual Studio 16 2019
[  +19 ms] CMake Error: Could not create named generator Visual Studio 16 2019
[   +1 ms] Generators
[        ]   Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
[        ]                                  Optional [arch] can be "Win64" or "ARM".
[        ]   Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
[        ]                                  Optional [arch] can be "Win64" or "ARM".
[        ]   Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
[        ]                                  Optional [arch] can be "Win64" or "ARM".
[        ]   Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
[        ]                                  Optional [arch] can be "Win64" or "ARM".
[        ]   Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
[        ]                                  Optional [arch] can be "Win64" or "IA64".
[        ]   Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
[        ]                                  Optional [arch] can be "Win64" or "IA64".
[        ]   Borland Makefiles            = Generates Borland makefiles.
[        ]   NMake Makefiles              = Generates NMake makefiles.
[        ]   NMake Makefiles JOM          = Generates JOM makefiles.
[        ]   Green Hills MULTI            = Generates Green Hills MULTI files
[        ]                                  (experimental, work-in-progress).
[        ]   MSYS Makefiles               = Generates MSYS makefiles.
[        ]   MinGW Makefiles              = Generates a make file for use with
[        ]                                  mingw32-make.
[        ]   Unix Makefiles               = Generates standard UNIX makefiles.
[        ]   Ninja                        = Generates build.ninja files.
[        ]   Watcom WMake                 = Generates Watcom WMake makefiles.
[        ]   CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
[        ]   CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
[        ]   CodeBlocks - NMake Makefiles JOM
[        ]                                = Generates CodeBlocks project files.
[        ]   CodeBlocks - Ninja           = Generates CodeBlocks project files.
[        ]   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
[        ]   CodeLite - MinGW Makefiles   = Generates CodeLite project files.
[        ]   CodeLite - NMake Makefiles   = Generates CodeLite project files.
[        ]   CodeLite - Ninja             = Generates CodeLite project files.
[        ]   CodeLite - Unix Makefiles    = Generates CodeLite project files.
[        ]   Sublime Text 2 - MinGW Makefiles
[        ]                                = Generates Sublime Text 2 project files.
[        ]   Sublime Text 2 - NMake Makefiles
[        ]                                = Generates Sublime Text 2 project files.
[        ]   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
[        ]   Sublime Text 2 - Unix Makefiles
[        ]                                = Generates Sublime Text 2 project files.
[        ]   Kate - MinGW Makefiles       = Generates Kate project files.
[        ]   Kate - NMake Makefiles       = Generates Kate project files.
[        ]   Kate - Ninja                 = Generates Kate project files.
[        ]   Kate - Unix Makefiles        = Generates Kate project files.
[        ]   Eclipse CDT4 - NMake Makefiles
[        ]                                = Generates Eclipse CDT 4.0 project files.
[        ]   Eclipse CDT4 - MinGW Makefiles
[        ]                                = Generates Eclipse CDT 4.0 project files.
[        ]   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
[        ]   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
[  +12 ms] Building Windows application... (completed in 52ms)
[+4813 ms] Exception: Unable to generate build files
[        ] "flutter run" took 10,313ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +101 ms] ensureAnalyticsSent: 97ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```
PS D:\Flutter Project\Archive\WORKING Project\flutter_application_1> flutter analyze
Analyzing flutter_application_1...                                      
No issues found! (ran in 3.1s)
```

```
PS D:\Flutter Project\Archive\WORKING Project\flutter_application_1> flutter doctor -v
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.985], locale en-US)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (2 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.0.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.0.28803.202
    • Windows 10 SDK version 10.0.17763.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.57.0)
    • VS Code at C:\Users\Ahmed\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.37

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hi @AhmedAbouelkher 
This seems to be an issue with your setup, See this [SO](https://stackoverflow.com/questions/66607779/cmake-error-could-not-create-named-generator-visual-studio-16-2019-in-flutter)

Make sure you've all components properly (uninstall/reinstall) & update any VS or any components that needs update and restart the system and 

![image](https://user-images.githubusercontent.com/48603081/121678545-fb61ff80-cabf-11eb-9e6e-ac08762f9765.png)

**Comment by AhmedAbouelkher** [comment]
I have updated `Windows 10 SDK` version `10.0.19041.0` to the last version and installed the last version of `CMake`.
No luck so far.

**Comment by AhmedAbouelkher** [comment]
Solved by coping newly installed CMake files to ```C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake```
