### ISSUE TITLE
Flutter crashes when a FutureBuilder replaces a SliverFillViewport with a SliverList.

### ISSUE THREAD

**Issue by Phelicks** [flutter/flutter#84440]
## Steps to Reproduce

1. Use this Widget:
```
class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: [
        FutureBuilder<int>(
          future: Future<void>.delayed(Duration(seconds: 5)).then((value) => 1),
          builder: (context, snapshot) {
            if (snapshot.data == null) {
              return SliverFillViewport(
                delegate: SliverChildListDelegate.fixed(<Widget>[
                  Text("Show this first..."),
                ]),
              );
            }

            return SliverList(
              delegate: SliverChildListDelegate.fixed(<Widget>[
                Text("...then show this!"),
              ]),
            );
          },
        ),
      ],
    );
  }
}
```
2. Wait 5 seconds, Flutter will crash as soon as the SliverList should be displayed.
5. Change SliverList to a second SliverFillViewport. Flutter will not crash anymore.
3. Retry with this widget. Note the SliverToBoxAdapter before the FutureBuilder:
```
class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      slivers: [
        SliverToBoxAdapter(child: const SizedBox()),
        FutureBuilder<int>(
          future: Future<void>.delayed(Duration(seconds: 5)).then((value) => 1),
          builder: (context, snapshot) {
            if (snapshot.data == null) {
              return SliverFillViewport(
                delegate: SliverChildListDelegate.fixed(<Widget>[
                  Text("Show this first..."),
                ]),
              );
            }

            return SliverList(
              delegate: SliverChildListDelegate.fixed(<Widget>[
                Text("...then show this!"),
              ]),
            );
          },
        ),
      ],
    );
  }
}
```
4. The Widget will also not crash.

**Expected results:** 
Flutter should not crash when the SliverFillViewport changes to a SliverList.

**Actual results:** 
Flutter will crash and all of the UI becomes unresponsive. 

<details>
  <summary>Logs</summary>

```
[+3509 ms] 
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1696 pos 12: 'center!.parent
== this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
    https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RenderViewport.indexOfFirstChild (package:flutter/src/rendering/viewport.dart:1696:12)
#3      RenderViewportBase.debugDescribeChildren (package:flutter/src/rendering/viewport.dart:968:17)
#4      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2994:48)
#5      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1567:32)
#6      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#7      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1632:19)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#12     new List.of (dart:core-patch/array_patch.dart:50:28)
#13     ListIterable.toList (dart:_internal/iterable.dart:212:44)
#14     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1633:8)
#15     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1595:25)
#16     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1608:6)
#17     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1499:18)
#18     WidgetInspectorService._reportError (package:flutter/src/widgets/widget_inspector.dart:919:44)
#19     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1107:14)
#20     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1310:18)
#21     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1639:7)
#22     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
#23     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
#24     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
#25     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#26     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#27     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#28     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#32     _invoke (dart:ui/hooks.dart:163:10)
#33     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#34     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
```

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale de-DE)
    • Flutter version 2.2.1 at /Users/_/Library/flutter
    • Framework revision 02c026b03c (vor 2 Wochen), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/_/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/_/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Pixel 3 XL (mobile) • 8AKY0M511 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos     • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)        • chrome    • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Phelicks 
Can you check out [this](https://newbedev.com/how-to-use-futurebuilder-inside-sliverlist) link and see if it helps ?

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
