### ISSUE TITLE
Fresh Flutter Install: A problem occurred evaluating project ':app'.

### ISSUE THREAD

**Issue by shhackleton** [flutter/flutter#84538]
Hello! I'm having a problem while running the sample app provided by the flutter team in android studio using a virtual device. I've just installed android studio and flutter. I tried running the same code on Chrome and it works fine.

## Steps to Reproduce

1. Create a new sample flutter project using android studio
2. Create virtual device, I'm using Pixel 4 API 30 with R system image.
3. Run main.dart

## Logs

<details>

```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\federico\AndroidStudioProjects\test_delete\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> org/jetbrains/kotlin/cli/common/PropertiesKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
```

```
```

## Flutter doctor

```
PS C:\Users\federico\AndroidStudioProjects\test_delete> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale es-AR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.57.0)
[√] Connected device (3 available)

• No issues found!
```

```
```

## flutter run --verbose

```
PS C:\Users\federico\AndroidStudioProjects\test_delete> flutter run --verbose
[  +88 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +598 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] executing: [C:\flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[  +51 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] 2.2.2
[   +5 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +136 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +107 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] executing: C:\Users\federico\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +48 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm
           transport_id:1
[   +9 ms] C:\Users\federico\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +58 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +87 ms] Skipping pub get: version match.
[ +126 ms] Generating
C:\Users\federico\AndroidStudioProjects\test_delete\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistra
nt.java
[  +78 ms] ro.hardware = ranchu
[  +21 ms] Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling
software
           rendering with "--enable-software-rendering".
[  +44 ms] Initializing file store
[  +30 ms] Skipping target: gen_localizations
[   +8 ms] complete
[   +6 ms] Launching lib\main.dart on sdk gphone x86 in debug mode...
[   +5 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\federico\AppData\Local\Temp\flutter_tools.a77bbb2e\flutter_tool.9f3e5efb\app.dill --packages
C:\Users\federico\AndroidStudioProjects\test_delete\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +15 ms] executing: C:\Users\federico\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x
logcat -v time -t 1
[  +13 ms] <- compile package:test_delete/main.dart
[  +85 ms] --------- beginning of main
           06-13 20:42:56.148 E/wifi_forwarder(  477): RemoteConnection failed to initialize: RemoteConnection failed to
           open pipe
[  +21 ms] executing: C:\Users\federico\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +21 ms] Android Debug Bridge version 1.0.41
           Version 31.0.2-7242960
           Installed as C:\Users\federico\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\federico\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +47 ms] Building APK
[  +18 ms] Running Gradle task 'assembleDebug'...
[   +7 ms] Using gradle from C:\Users\federico\AndroidStudioProjects\test_delete\android\gradlew.bat.
[  +16 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +193 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +4 ms] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +3 ms] executing: [C:\Users\federico\AndroidStudioProjects\test_delete\android/]
C:\Users\federico\AndroidStudioProjects\test_delete\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=C:\Users\federico\AndroidStudioProjects\test_delete\lib\main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+2033 ms] FAILURE: Build failed with an exception.
[   +5 ms] * Where:
[   +1 ms] Build file 'C:\Users\federico\AndroidStudioProjects\test_delete\android\app\build.gradle' line: 25
[   +1 ms] * What went wrong:
[        ] A problem occurred evaluating project ':app'.
[        ] > org/jetbrains/kotlin/cli/common/PropertiesKt
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 1s
[ +561 ms] Running Gradle task 'assembleDebug'... (completed in 2.822ms)
[+5829 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 9.554ms.
[   +5 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +112 ms] ensureAnalyticsSent: 109ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

</details>

Java version: 
java 16.0.1 2021-04-20

Gradle:

```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (Oracle Corporation 16.0.1+9-24)
OS:           Windows 10 10.0 amd64
```

**Comment by darshankawar** [comment]
@shhackleton 
It's failing due to below error:

```
`* What went wrong:
A problem occurred evaluating project ':app'.
> org/jetbrains/kotlin/cli/common/PropertiesKt`
```
And seems to be coming from jetbrains / Java itself, as the kotlin version doesn't seem to work with JDK 16. Take a look at [this](https://youtrack.jetbrains.com/issue/KTIJ-18046) issue and comments and see if any of the solutions mentioned works for you (downgrading jdk version).

Also, take a look at this issue tracker in kotlinlang.org for same issue: https://discuss.kotlinlang.org/t/java-lang-noclassdeffounderror-org-jetbrains-kotlin-cli-common-propertieskt/19193/13 and see any of the solutions mentioned works for you.

Closing from here as this isn't an issue with framework, but seems to be coming from Kotlin.
