### ISSUE TITLE
Flutter Web, script to provide PWA functionality causes errors on profile/release mode when using canvaskit

### ISSUE THREAD

**Issue by chessasuke** [flutter/flutter#84573]
## Steps to Reproduce

1. Create a default app.
2. Integrate firebase (add libraries to the index.html)
3. Run in profile mode (if running with the HTML web-renderer flag works ok)

When running the flutter app in profile mode u can see in the google inspector some binding issues:

BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
js_primitives.dart:47     at BindingError.<anonymous> (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:130708)
js_primitives.dart:47     at new BindingError (eval at createNamedFunction (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:130417), <anonymous>:4:34)
js_primitives.dart:47     at throwBindingError (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:134225)
js_primitives.dart:47     at upcastPointer (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:140630)
js_primitives.dart:47     at RegisteredPointer.nonConstNoSmartPtrRawPointerToWireType [as toWireType] (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:143398)
js_primitives.dart:47     at Canvas$drawParagraph [as drawParagraph] (eval at new_ (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:152523), <anonymous>:8:26)
js_primitives.dart:47     at JavaScriptObject.drawParagraph$3 (http://localhost:62205/main.dart.js:44475:23)
js_primitives.dart:47     at Object.drawParagraph$3$x (http://localhost:62205/main.dart.js:10081:43)
js_primitives.dart:47     at CkCanvas.drawParagraph$2 (http://localhost:62205/main.dart.js:27886:9)
js_primitives.dart:47     at CanvasKitCanvas.drawParagraph$2 (http://localhost:62205/main.dart.js:28349:29)
js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'

In the index.html if the default script to provide PWA functionality is commented out the app works ok
```
  <script>
    var serviceWorkerVersion = null;
    var scriptLoaded = false;
    function loadMainDartJs() {
      if (scriptLoaded) {
        return;
      }
      scriptLoaded = true;
      var scriptTag = document.createElement('script');
      scriptTag.src = 'main.dart.js';
      scriptTag.type = 'application/javascript';
      document.body.append(scriptTag);
    }

    if ('serviceWorker' in navigator) {
      // Service workers are supported. Use them.
      window.addEventListener('load', function () {
        // Wait for registration to finish before dropping the <script> tag.
        // Otherwise, the browser will load the script multiple times,
        // potentially different versions.
        var serviceWorkerUrl = 'flutter_service_worker.js?v=' + serviceWorkerVersion;
        navigator.serviceWorker.register(serviceWorkerUrl)
          .then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener('statechange', () => {
                if (serviceWorker.state == 'activated') {
                  console.log('Installed new service worker.');
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing ?? reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log('New service worker available.');
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log('Loading app from service worker.');
              loadMainDartJs();
            }
          });

        // If service worker doesn't succeed in a reasonable amount of time,
        // fallback to plaint <script> tag.
        setTimeout(() => {
          if (!scriptLoaded) {
            console.warn(
              'Failed to load app from service worker. Falling back to plain <script> tag.',
            );
            loadMainDartJs();
          }
        }, 4000);
      });
    } else {
      // Service workers not supported. Just drop the <script> tag.
      loadMainDartJs();
    }
  </script>
```

```
No issues found! (ran in 1.4s)
```

 

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale es-ES)
    • Flutter version 2.2.2 at C:\src\flutter\flutter
    • Framework revision d79295af24 (3 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\cahev\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\cahev\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1052]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!


```

</details>

**Comment by darshankawar** [comment]
> 2\. Integrate firebase (add libraries to the index.html)

@chessasuke Does the error occur if you don't integrate firebase ?

Also, which script section inside `index.html` need to comment out which then works ?

Thanks.

**Comment by chessasuke** [comment]
The one that I copied in the description. It's the one that has this default comment when we create a new project:

  

To see the error u need to run in profile or release. Also must be in the default web-renderer canvaskit, if running with the web-renderer HTML flag it wont show.

U don't need actually to integrate any firebase service, the error shows without adding any SDK to the html.

**Comment by darshankawar** [comment]
Thanks for the details.  I see the same behavior using latest stable.

<details>
<summary>browser console log</summary>

```

    Uncaught TypeError: Cannot read property 'toString' of null
    at _PointerAdapter_setup_closure1.call$1 (pointer_binding.dart:488)
    at _PointerAdapter__addPointerEventListener_closure.call$1 (pointer_binding.dart:506)
    at _BaseAdapter_addEventListener_closure.call$1 (pointer_binding.dart:214)
    at invokeClosure (js_helper.dart:1826)
    at js_helper.dart:1858
js_primitives.dart:47 BindingError: Expected null or instance of Paragraph, got an instance of Paragraph
js_primitives.dart:47     at BindingError.<anonymous> (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:130708)
js_primitives.dart:47     at new BindingError (eval at createNamedFunction (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:130417), <anonymous>:4:34)
js_primitives.dart:47     at throwBindingError (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:134225)
js_primitives.dart:47     at upcastPointer (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:140630)
js_primitives.dart:47     at RegisteredPointer.nonConstNoSmartPtrRawPointerToWireType [as toWireType] (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:143398)
js_primitives.dart:47     at Canvas$drawParagraph [as drawParagraph] (eval at new_ (https://unpkg.com/canvaskit-wasm@0.25.1/bin/profiling/canvaskit.js:9:152523), <anonymous>:8:26)
js_primitives.dart:47     at JavaScriptObject.drawParagraph$3 (http://localhost:53698/main.dart.js:46222:23)
js_primitives.dart:47     at Object.drawParagraph$3$x (http://localhost:53698/main.dart.js:10244:43)
js_primitives.dart:47     at CkCanvas.drawParagraph$2 (http://localhost:53698/main.dart.js:29347:9)
js_primitives.dart:47     at CanvasKitCanvas.drawParagraph$2 (http://localhost:53698/main.dart.js:29810:29)
4js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'

```

</details>



<details>
<summary>flutter doctor -v</summary>

```console
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/dhs/Documents/Fluttersdk/flutter
    • Framework revision d79295af24 (5 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 • ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 91.0.4472.106

• No issues found!

```
</details>

**Comment by yjbanov** [comment]
We've upgraded to CanvasKit 0.27. Does it still happen on the master channel?

**Comment by chessasuke** [comment]
I don't see the problem now, thanks!!
