### ISSUE TITLE
Building error when I add firebase_core and cloud_firestore ? 

### ISSUE THREAD

**Issue by Sormox** [flutter/flutter#84582]
Hello this wired error when i add firebase 
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6 to pubspec.yaml . hOw to fix it 

`Plugin project :firebase_core_web not found. Please update settings.gradle. Plugin project :firebase_auth_web not found. Please update settings.gradle. Plugin project :cloud_firestore_web not found. Please update settings.gradle. D8: Cannot fit requested classes in a single dex file (# methods: 80933 > 65536) com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:  The number of method references in a .dex file cannot exceed 64K. Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html 	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131) 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118) 	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102) 	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444) 	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335) 	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50) 	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47) 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65) 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61) 	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98) 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61) 	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44) 	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41) 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416) 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBu`

**Comment by Sormox** [comment]
first fix I found is https://github.com/FirebaseExtended/flutterfire/issues/2599#issuecomment-632651771 . after that fix also error is 

`FAILURE: Build failed with an exception.  * Where: Build file 'C:\Users\Darm-Pc\Documents\Flutter_project\parking_app\android\build.gradle' line: 28  * What went wrong: A problem occurred evaluating root project 'android'. > Project with path ':app' could not be found in project ':cloud_firestore'.  * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.  * Get more help at https://help.gradle.org  BUILD FAILED in 989ms Exception: Gradle task assembleDebug failed with exit code 1`

also I find a fix https://stackoverflow.com/questions/62223356/d8-cannot-fit-requested-classes-in-a-single-dex-file

**Comment by Sormox** [comment]
after that third error rise   `D8: Cannot fit requested classes in a single dex file (# methods: 80987 > 65536) com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:  The number of method references in a .dex file cannot exceed 64K. Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html 	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131) 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118) 	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102) 	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444) 	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335) 	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50) 	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47) 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65) 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61) 	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98) 	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61) 	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44) 	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41) 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416) 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406) 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165) 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuil` 

and the fix is https://stackoverflow.com/questions/62223356/d8-cannot-fit-requested-classes-in-a-single-dex-file . 

**Now My app runs 0 error =)**

**Comment by Sormox** [comment]
Fixed Completely 14/6/2021 7:40 pm
