### ISSUE TITLE
[engine] local iOS engine fails on macOS Monterey

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#84654]
#### On macOS Monterey

1. Follow [Setting up the Engine development environment](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment)
2. Move to [Compiling for iOS (from macOS)](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-ios-from-macos).

When executing `./flutter/tools/gn --ios --unoptimized` 

```console
tahatesser@Tahas-MBP src % ./flutter/tools/gn --ios --unoptimized

GOMA usage was specified but can't be found, falling back to local builds. Set the GOMA_DIR environment variable to fix GOMA.
Generating GN files in: out/ios_debug_unopt
ERROR at //build/config/mac/mac_sdk.gni:38:7: Script returned non-zero exit code.
      exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
      ^----------
Current dir: /Volumes/Extreme/engine/src/out/ios_debug_unopt/
Command: python /Volumes/Extreme/engine/src/build/mac/find_sdk.py --print_sdk_path 10.12
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Volumes/Extreme/engine/src/build/mac/find_sdk.py", line 101, in <module>
    print(main())
  File "/Volumes/Extreme/engine/src/build/mac/find_sdk.py", line 68, in main
    raise Exception('No %s+ SDK found' % min_sdk_version)
Exception: No 10.12+ SDK found

See //build/toolchain/mac/BUILD.gn:10:1: whence it was imported.
import("//build/config/mac/mac_sdk.gni")
^--------------------------------------
See //BUILD.gn:6:1: which caused the file to be included.
group("default") {
^-----------------
tahatesser@Tahas-MBP src % 
```

This wasn't an issue on macOS Big Sur

cc: @chinmaygarde 
Need a fix for this soon so I can run the engine locally for a couple of Flutter issues, thank you!

**Comment by TahaTesser** [comment]
Perhaps the engine needs updated `min_sdk_version` to be able to run on macOS Monterey?

**Comment by TahaTesser** [comment]
Closing, this looks like a setup issue
