### ISSUE TITLE
Androidmanifest.xml problem and emulator problem..

### ISSUE THREAD

**Issue by coja99** [flutter/flutter#84692]
Hello everyone, I have this problem that I don't know how to fix. Could someone please help me, i have this androidmanifest.xml problem, and also when I run something on my emulator, it shows this.
TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:57556/packages/firebase_core_web/src/interop/core.dart.lib.js:31:101)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:57556/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:773:64)
    at Function.registerWith (http://localhost:57556/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:692:73)
    at Object.registerPlugins (http://localhost:57556/packages/first_flutter_app/generated_plugin_registrant.dart.lib.js:16:46)
    at main (http://localhost:57556/web_entrypoint.dart.lib.js:31:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:57556/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:57556/dart_sdk.js:37453:7)
    at main$ (http://localhost:57556/web_entrypoint.dart.lib.js:30:18)
    at http://localhost:57556/main_module.bootstrap.js:19:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:57556/main_module.bootstrap.js:18:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:57556/dwds/src/injected/client.js:8825:21)
    at http://localhost:57556/dwds/src/injected/client.js:22713:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:57556/dwds/src/injected/client.js:3851:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:57556/dwds/src/injected/client.js:11063:12)
    at Object._asyncStartSync (http://localhost:57556/dwds/src/injected/client.js:3815:20)
    at main__closure1.$call$body$main__closure (http://localhost:57556/dwds/src/injected/client.js:22725:16)
    at main__closure1.call$1 (http://localhost:57556/dwds/src/injected/client.js:22652:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:57556/dwds/src/injected/client.js:4185:16)
    at _CustomZone.runUnary$2$2 (http://localhost:57556/dwds/src/injected/client.js:12436:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57556/dwds/src/injected/client.js:12383:14)
    at _ControllerSubscription._sendData$1 (http://localhost:57556/dwds/src/injected/client.js:11959:19)
    at _DelayedData.perform$1 (http://localhost:57556/dwds/src/injected/client.js:12148:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:57556/dwds/src/injected/client.js:12197:14)
    at Object._microtaskLoop (http://localhost:57556/dwds/src/injected/client.js:4023:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:57556/dwds/src/injected/client.js:4029:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:57556/dwds/src/injected/client.js:10932:9)
    at invokeClosure (http://localhost:57556/dwds/src/injected/client.js:1259:26)
    at MutationObserver.<anonymous> (http://localhost:57556/dwds/src/injected/client.js:1278:18)

![Screenshot 2021-06-16 at 10 39 32](https://user-images.githubusercontent.com/61987441/122193592-e953d880-ce94-11eb-98a0-bd9dad43fe0e.png) This screenshot is of my androidmanifest.xml... It says Attribute android:icon is not allowed here...

**Comment by darshankawar** [comment]
@coja99 
The error is pointing to `TypeError: Cannot read property 'app' of undefined
at Object.app$ [as app] (http://localhost:57556/packages/firebase_core_web/src/interop/core.dart.lib.js:31:101)
at new cloud_firestore_web.FirebaseFirestoreWeb.new`

Are you using `cloud_firestore` or any other firebase plugins ?
Can you provide `flutter doctor -v` and `pubspec.yaml` ?

**Comment by coja99** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale
    en-GB)
    • Flutter version 2.2.2 at /Users/vladajovanovic/Desktop/FlutterSDK/flutter
    • Framework revision d79295af24 (5 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vladajovanovic/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Internet
      Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 16.0.1+9-24)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at
      /Users/vladajovanovic/Desktop/FlutterSDK/flutter/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome
      91.0.4472.106

! Doctor found issues in 3 categories.


And this is my pubspec:
name: first_flutter_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  firebase_storage: ^8.1.3
  firebase_core: ^1.3.0
  cloud_firestore_web: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/prijava.png
    - images/registracija.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by darshankawar** [comment]
@coja99 
If you remove the firebase plugins and try again, does the error persist ?

```
cloud_firestore: ^2.2.2
firebase_auth: ^1.4.1
firebase_storage: ^8.1.3
firebase_core: ^1.3.0
cloud_firestore_web: ^2.1.2
```

**Comment by coja99** [comment]
@darshankawar 
Well, if i delete that, I will have to edit my whole code...

**Comment by darshankawar** [comment]
@coja99 
This seems to be an issue with Firebase. See below similar reported issues:

https://stackoverflow.com/questions/61716199/flutter-web-and-firebase-authentication-typeerror-cannot-read-property-app-of

https://github.com/FirebaseExtended/flutterfire/issues/2455
https://github.com/FirebaseExtended/flutterfire/issues/3073

Also see this issue comment / workaround / solution and check if it helps to resolve your issue.

Closing from here. If issue still persists using firebase plugins, please open this in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues
