### ISSUE TITLE
Scrollbar throws due to recent assert changes

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#84735]
## Steps to Reproduce

1. PrimaryScrollController (or any other scroll controller that attaches both to scrollbar and view) -> 
PageTransitionSwitcher ->
SharedAxisTransition ->
Scrollbar ->
View
2. Animate the switcher

Related PR https://github.com/flutter/flutter/pull/81278

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:animations/animations.dart';

void main() {
  runApp(App());
}

class App extends StatefulWidget {
  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  late final views = [
    for (int i = 0; i < 5; i++)
      Scrollbar(
        interactive: true,
        key: ValueKey(i),
        child: ListView.builder(
          itemCount: 100,
          itemBuilder: (context, index) => Text(index.toString()),
        ),
      ),
  ];

  int index = 0;
  void _handleTap() {
    setState(() {
      index += 1;
      if (index == views.length) {
        index = 0;
      }
    });
  }

  final controller = ScrollController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App',
      home: PrimaryScrollController(
        controller: controller,
        child: Scaffold(
          body: Column(
            children: [
              ElevatedButton(onPressed: _handleTap, child: Text('sample text')),
              Expanded(
                child: PageTransitionSwitcher(
                  duration: const Duration(milliseconds: 300),
                  transitionBuilder: (child, animation, secondaryAnimation) {
                    return SharedAxisTransition(
                      transitionType: SharedAxisTransitionType.horizontal,
                      animation: animation,
                      secondaryAnimation: secondaryAnimation,
                      fillColor: Colors.transparent,
                      child: child,
                    );
                  },
                  child: views[index],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
  <summary>Logs</summary>

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
The PrimaryScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The PrimaryScrollController is used by default for ScrollViews with an Axis.vertical ScrollDirection, unless the ScrollView has been provided its own ScrollController. More than one Scrollable may have tried to use the PrimaryScrollController of the current context.

When the exception was thrown, this was the stack
#0      RawScrollbarState._checkForValidScrollPosition.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1101
#1      RawScrollbarState._checkForValidScrollPosition
package:flutter/…/widgets/scrollbar.dart:1125
#2      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1042
#3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1088
#5      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
#9      _invoke (dart:ui/hooks.dart:163:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#11     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

```

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.375, on Microsoft Windows [Version 10.0.19041.1052], locale ru-RU)
    • Flutter version 2.3.0-17.0.pre.375 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • Framework revision 57a565c706 (19 hours ago), 2021-06-15 18:44:02 -0700
    • Engine revision e0011fa561
    • Dart version 2.14.0 (build 2.14.0-211.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1052]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.101
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 91.0.864.41

! Doctor found issues in 1 category.
```

</details>

**Comment by nt4f04uNd** [comment]
It looks like TabBarView suffers from the same issue

**Comment by Piinks** [comment]
I assume #81278 will reveal some poorly configured scrollbars, but yeah, it does seem a little over eager. I am working on a patch now that moves the assertion to a more appropriate place and takes into account if the scrollbar is actually visible.

**Comment by Piinks** [comment]
Related: https://github.com/flutter/gallery/issues/523

**Comment by Piinks** [comment]
Thank you for the test cases by the way! :)

**Comment by Piinks** [comment]
Both of these samples are the exact case these assertions are trying to help with. The scrollbars in these examples are explicitly interactive, but are also using the same PrimaryScrollController. These should all have unique scroll controllers. If the assertion does not catch this, then the scrollbar might crash when the user tries to interact with it and more than one position is attached.

There are a couple of ways to resolve this, you can provide a unique scroll controller to each ListView.controller, or you can have the ListViews not use the PrimaryScrollController by setting ListView.primary to false.

I am still going to adjust this assertion a bit to be more specific, but I think we definitely want to catch and inform the developer in this case.

**Comment by Piinks** [comment]
>  or you can have the ListViews not use the PrimaryScrollController by setting ListView.primary to false.

Sorry, that last case is if ScrollBehavior.buildScrollbar is applying the scrollbar, since Scrollable will create a unique scroll controller in that case.

**Comment by nt4f04uNd** [comment]
I see, thanks. Was confused a bit since it was working out fine perfectly fine for my use case, i.e. PageTransitionSwitcher, since at the time user is able to drag the scrollbar, the second view, the controller was attached to, is already gone. I agree this is a valid assertion
