### ISSUE TITLE
Simple flutter class doesn't work as expected

### ISSUE THREAD

**Issue by MinorWannaBeDev** [flutter/flutter#84784]
## Steps to Reproduce

I made this simple class  to represent a generic chat window:

```dart
class ChatMessage extends StatelessWidget{
  final messageids = [1,2,3,4];

  @override
  Widget build(BuildContext context){
    return Column(
      children: [Row(children: [ListView()]), Row(children: [TextFormField(
        decoration: InputDecoration(
          hintText: "Input your message here"
        ),
      )])],
    );
  }
}
```
**Expected results:** 
I wanted to make a new widget class, composed of an input field at the bottom, and a listview with many Message objects.

**Actual results:** 
The code doesn't work at all, maybe I skipped some important steps, however, this the message that is outputted when building the app.

**Console output:**
```
Performing hot reload...
Syncing files to device sdk gphone x86 arm...

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performResize():
Vertical viewport was given unbounded height.

Viewports expand in the scrolling direction to fill their container. In this case, a vertical viewport was given an unlimited amount of vertical space in which to expand. This situation typically happens when a scrollable widget is nested inside another scrollable widget.

If this widget is always nested in a scrollable widget there is no need to use a viewport because there will always be enough vertical space for the children. In this case, consider using a Column instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size the height of the viewport to the sum of the heights of its children.

The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
When the exception was thrown, this was the stack: 
#0      RenderViewport.computeDryLayout.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1365:15)
#1      RenderViewport.computeDryLayout (package:flutter/src/rendering/viewport.dart:1426:6)
#2      RenderBox.performResize (package:flutter/src/rendering/box.dart:2342:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1763:9)
#4      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
...
The following RenderObject was being processed when the exception was fired: RenderViewport#731f1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(unconstrained)
...  size: MISSING
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#951e6(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#d14dc, ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#731f1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(unconstrained)
  size: MISSING
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#951e6(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#d14dc, ScrollDirection.idle)
  anchor: 0.0
...  center child: RenderSliverPadding#2704d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 0.0)
...    constraints: MISSING
...    geometry: null
...    padding: EdgeInsets.zero
...    textDirection: ltr
...    child: RenderSliverList#df03b NEEDS-LAYOUT NEEDS-PAINT
...      parentData: paintOffset=Offset(0.0, 0.0)
...      constraints: MISSING
...      geometry: null
...      no children current live
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderViewport#731f1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderViewport#731f1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderIgnorePointer#35035 relayoutBoundary=up15 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderSemanticsAnnotations#26c03 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderPointerListener#597dc relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderSemanticsGestureHandler#f2b98 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderPointerListener#e9767 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: _RenderScrollSemantics#6079e relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderRepaintBoundary#9e8bf relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderCustomPaint#05d62 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:45:33
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderRepaintBoundary#b8edc relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Row file:///C:/src/test_app/lib/main.dart:45:18
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderFlex#f4c75 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Column file:///C:/src/test_app/lib/main.dart:44:12
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderFlex#237c1 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:26:18
====================================================================================================
Reloaded 1 of 601 libraries in 3,334ms.

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderRepaintBoundary#9baec relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:26:18
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1940:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:119:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
#5      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213:28)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
...
The following RenderObject was being processed when the exception was fired: RenderIndexedSemantics#ebb30 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: index=0; layoutOffset=0.0 (can use size)
...  constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
...  semantic boundary
...  size: MISSING
...  index: 0
RenderObject: RenderIndexedSemantics#ebb30 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: index=0; layoutOffset=0.0 (can use size)
  constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
  semantic boundary
  size: MISSING
  index: 0
...  child: RenderRepaintBoundary#9baec relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
...    size: MISSING
...    usefulness ratio: no metrics collected yet (never painted)
...    child: RenderFlex#237c1 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
...      size: MISSING
...      direction: vertical
...      mainAxisAlignment: start
...      mainAxisSize: max
...      crossAxisAlignment: center
...      verticalDirection: down
...      child 1: RenderFlex#f4c75 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=Infinity)
...        size: MISSING
...        direction: horizontal
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        textDirection: ltr
...        verticalDirection: down
...        child 1: RenderRepaintBoundary#b8edc relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          needs compositing
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(unconstrained)
...          size: MISSING
...          usefulness ratio: no metrics collected yet (never painted)
...      child 2: RenderFlex#37fe4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...        constraints: MISSING
...        size: MISSING
...        direction: horizontal
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        textDirection: ltr
...        verticalDirection: down
...        child 1: RenderMouseRegion#8169b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...          listeners: enter, exit
...          cursor: SystemMouseCursor(text)
====================================================================================================

======== Exception caught by rendering library =====================================================
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 544 pos 12: 'child.hasSize': is not true.
The relevant error-causing widget was: 
  ListView file:///C:/src/test_app/lib/main.dart:26:18
====================================================================================================
```
Here is the full code:
```dart
import "package:flutter/material.dart";
import "package:english_words/english_words.dart";

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}


class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("testing range"),
        centerTitle: true,
        backgroundColor: Colors.red[500],
      ),
      body: Center(
          child: ListView(
            children: [
            ChatMessage()
            ],

          )
      ),
    );
  }
}



class ChatMessage extends StatelessWidget{
  final messageids = [1,2,3,4];

  @override
  Widget build(BuildContext context){
    return Column(
      children: [Row(children: [ListView()]), Row(children: [TextFormField(
        decoration: InputDecoration(
          hintText: "Input your message here"
        ),
      )])],
    );
  }
}
```
I am using android studio to build it on android platform, the error message tells me that this assertion error is either an internal error or undocumented behavior.

Thank you for your help.

</details>

**Comment by darshankawar** [comment]
@MinorWannaBeDev 
As the log says:

```
`The following assertion was thrown during performResize():
Vertical viewport was given unbounded height.

Viewports expand in the scrolling direction to fill their container. In this case, a vertical viewport was given an unlimited amount of vertical space in which to expand. This situation typically happens when a scrollable widget is nested inside another scrollable widget.

If this widget is always nested in a scrollable widget there is no need to use a viewport because there will always be enough vertical space for the children. In this case, consider using a Column instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size the height of the viewport to the sum of the heights of its children.`
```

Did you try to follow the solution mentioned in it ?

```

In this case, a vertical viewport was given an unlimited amount of vertical space in which to expand. This situation typically happens when a scrollable widget is nested inside another scrollable widget.

If this widget is always nested in a scrollable widget there is no need to use a viewport because there will always be enough vertical space for the children. In this case, consider using a Column instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size the height of the viewport to the sum of the heights of its children.`
```

**Comment by MinorWannaBeDev** [comment]
Thanks for your response.
I tried adding shrinkWrap and scroll direction in the listview, however, the same error occurs only with a different error message.
After that, I simply removed the Row() widget that wrapped the elements of the column and it worked as expected.
Is this expected behavior?

**Comment by darshankawar** [comment]
@MinorWannaBeDev 
Since you had `Row` inside `Column` and inside it you had `ListView` and `TextFormField` which has potential to grow to infinity if not given a width or size, so in this case, you can try to use `SizedBox` and give it a custom width or wrap your textfield with `Flexible` which takes the minimum available space to render.

You may search for similar behavior on StackOverflow for further reference.
I am going ahead and closing this as non-issue. If you disagree, write in comments and I'll reopen it.
