### ISSUE TITLE
DragTarget crash  if Draggable data field is not set, but data is not required.

### ISSUE THREAD

**Issue by MousyBusiness** [flutter/flutter#84816]
### DragTarget crashes if Draggable data field is not set, but data is not required. 

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/41450491/122479820-9fb5db80-cfc3-11eb-91d3-1bd7a07de3e8.png">

Specifically the issue is in `didDrop` in `drag_target.dart` which asserts `data` is not null:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/41450491/122479901-c2e08b00-cfc3-11eb-89bf-f9d07a0435ba.png">

### Suggestion
Make `data` field required.

**Comment by darshankawar** [comment]
@MousyBusiness 
Can you provide `flutter doctor -v` and [complete minimal code sample](https://stackoverflow.com/help/minimal-reproducible-example) in text format that shows this issue ?
Thanks.

**Comment by MousyBusiness** [comment]
```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/mousybusiness/Flutter/flutter
    • Framework revision d79295af24 (7 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/mousybusiness/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Draggable(
                // data: Colors.yellow,
                feedback: Container(height: 100, width: 100, color: Colors.green),
                child: Container(height: 100, width: 100, color: Colors.yellow.withOpacity(0.3))),
            Container(height: 100, width: 100, color: Colors.amber.withOpacity(0.3)),
            Container(height: 100, width: 100, color: Colors.red.withOpacity(0.3)),
            DragTarget(onWillAccept: (o) {
              return true;
            }, onAccept: (o) {
              print("onAccept");
            }, onLeave: (o) {
              print("onLeave");
            }, builder: (context, candidateData, rejectedData) {
              return Container(height: 100, width: 100, color: Colors.blue);
            }),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by MousyBusiness** [comment]
drag the first square onto the last square

**Comment by darshankawar** [comment]
Thanks for the details. I see the same behavior on latest master.

<details>
<summary>log</summary>

```

======== Exception caught by gesture library =======================================================
The following _CastError was thrown while routing a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _DragTargetState.didDrop (package:flutter/src/widgets/drag_target.dart:831:38)
#1      _DragAvatar.finishDrag (package:flutter/src/widgets/drag_target.dart:991:22)
#2      _DragAvatar.end (package:flutter/src/widgets/drag_target.dart:909:5)
#3      MultiDragPointerState._up (package:flutter/src/gestures/multidrag.dart:144:14)
#4      MultiDragGestureRecognizer._handleEvent (package:flutter/src/gestures/multidrag.dart:256:13)
#5      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#6      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#8      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:289:11)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#20     _invoke1 (dart:ui/hooks.dart:182:10)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 3 frames from dart:async)
====================================================================================================





```

</details>


<details>
<summary>flutter doctor -v</summary>

```console
/Users/dhs/Documents/Fluttersdk/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 2.3.0-17.0.pre.397, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-GB)
    • Flutter version 2.3.0-17.0.pre.397 at /Users/dhs/Documents/Fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 03034e9e4a (4 hours ago), 2021-06-18 00:14:03 -0700
    • Engine revision ced58ef9c1
    • Dart version 2.14.0 (build 2.14.0-217.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.106

• No issues found!

```
</details>

**Comment by Piinks** [comment]
The change is being reverted, re-opening.

**Comment by TahaTesser** [comment]
Re-applying priority label from a new duplicate https://github.com/flutter/flutter/issues/106097

**Comment by TahaTesser** [comment]
Should we make the `data` field required if https://github.com/flutter/flutter/pull/97355 is not the way to go?
cc: @Piinks

**Comment by Piinks** [comment]
> Should we make the data field required

It looks like it is already required, at least it is where the prior (reverted) change to make it nullable was: 

https://github.com/flutter/flutter/blob/7ad47233a9a38b2847f6a4f4cbcd90690adab10e/packages/flutter/lib/src/widgets/drag_target.dart#L651

Is this a mistake from the NNBD migration? I am not very familiar with this API, but it does look like it has a contradiction built into it. There's

- `Draggable.data`
  - not required
  - nullable
- `DragTargetDetails.data`
  - required
  - not nullable
- `_DragAvatar.data`
  - not required
  - nullable

**Comment by TahaTesser** [comment]
@Piinks 
Thanks! That's a great observation, I should've looked into that pattern.

**Comment by ValentinVignal** [comment]
Hello, to fix this issue, should `data` be made non-nullable and required or should the code support it when it is `null`?

**Comment by MousyBusiness** [comment]
Since drag and drop doesn’t have a purpose without data, I’d vote to make it required, but that may be a breaking change so there might be push back. It would be easiest to just handled the null value properly

**Comment by chinmoy12c** [comment]
@Piinks should this be made required as a fix, or does having a null data field make sense? Currently, I'm not able to work out a use case in which a null field would be useful 🤔.

**Comment by Piinks** [comment]
> should this be made required as a fix, or does having a null data field make sense?

It's been a while since I looked at this, unfortunately I do not recall and the customer failure that caused the change to be reverted is not available. If someone were to put up another PR we could run the tests internally and find out more then.

**Comment by sstadtl** [comment]
I ran into this problem today. 
why is "data" not required if DragTarget crashes without "data"
