### ISSUE TITLE
[pigeon] Pigeon doesn't generate code when using nested class with enum

### ISSUE THREAD

**Issue by fmolina199** [flutter/flutter#84848]
## Steps to Reproduce

1. Create a pigeon file with the following:
```dart
import 'package:pigeon/pigeon.dart';

enum Test {
  ENUM1,
  ENUM2
}

class Class1 {
  Test? test;
}

class Class2 {
  Class1? class1;
}

@HostApi()
abstract class Api {
  void method(Class2 class2);
}

void configurePigeon(PigeonOptions opts) {
  opts.dartOut = 'lib/pigeon/test.dart';
  opts.dartTestOut = 'test/pigeon/test.dart';
  opts.objcHeaderOut = 'ios/Classes/test.h';
  opts.objcSourceOut = 'ios/Classes/test.m';
  opts.objcOptions!.prefix = 'Test';
  opts.javaOut = 'android/src/main/java/com/test/Test.java';
  opts.javaOptions!.package = 'com.test';
}
```

2. Run pigeon generator 
```shell
flutter pub run pigeon --input pigeons/test.dart
```

**Expected results:** Class are generated correctly

**Actual results:**
Seem following exception:
```
Unhandled exception:
Exception: unrecognized datatype for field:"test" of type:"Test"
#0      getHostDatatype (package:pigeon/generator_tools.dart:177:7)
#1      generateJava.<anonymous closure>.<anonymous closure> (package:pigeon/java_generator.dart:286:45)
#2      Indent.nest (package:pigeon/generator_tools.dart:108:9)
#3      Indent.scoped (package:pigeon/generator_tools.dart:84:5)
#4      generateJava.<anonymous closure> (package:pigeon/java_generator.dart:284:14)
#5      Indent.nest (package:pigeon/generator_tools.dart:108:9)
#6      Indent.scoped (package:pigeon/generator_tools.dart:84:5)
#7      generateJava (package:pigeon/java_generator.dart:255:10)
#8      JavaGenerator.generate (package:pigeon/pigeon_lib.dart:313:5)
#9      Pigeon.run (package:pigeon/pigeon_lib.dart:639:21)
<asynchronous suspension>
#10     main (file:///tmp/flutter_pigeon.YMVSQR/_pigeon_temp_.dart:8:17)
<asynchronous suspension>
```

@gaaclarke

**Comment by gaaclarke** [comment]
@GaryQian you interested in taking a look?  Looks like we're missing some recursion somewheres.

**Comment by GaryQian** [comment]
Looking!

**Comment by gaaclarke** [comment]
I looked at this a bit and if the enum is referenced elsewhere it isn't a problem.  (While that is a workaround, we should have a fix for this quickly).

```dart
import 'package:pigeon/pigeon.dart';

enum State {
  Pending,
  Success,
  Error,
}

class Data {
  State? state;
}

class Nested {
  Data? data;
}

@HostApi()
abstract class EnumApi2Host {
  // Uncomment the next line and it will compile fine.
  // Data echo(Data data);
  void doit(Nested nested);
}
```
