### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.videoplayer.VideoPlayer.seekTo(int)

### ISSUE THREAD

**Issue by bholendraofficial** [flutter/flutter#84906]
<details> 
<summary>logs</summary> 
	
```console
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.videoplayer.VideoPlayer.seekTo(int)' on a null object reference, null, null)
E/flutter (14826): #0      VideoPlayerApi.seekTo (package:video_player_platform_interface/messages.dart:365:7)
E/flutter (14826): <asynchronous suspension>
E/flutter (14826): #1      VideoPlayerController.seekTo (package:video_player/video_player.dart:494:5)
E/flutter (14826): <asynchronous suspension>
E/flutter (14826): #2      FlickControlManager.seekTo (package:flick_video_player/src/manager/control_manager.dart:105:5)
E/flutter (14826): <asynchronous suspension>
E/flutter (14826): 
I/MediaCodec(14826): setCodecState state : 1
D/TransportRuntime.CctTransportBackend(14826): Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
I/System.out(14826): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(14826): (HTTPLog)-Static: isSBSettingEnabled false
I/ACodec  (14826): [OMX.Exynos.avc.dec] signalFlush
I/ACodec  (14826): [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 0/5 input, 0/16 output).
I/ACodec  (14826): [OMX.Exynos.avc.dec] Now Flushing
I/ACodec  (14826): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
I/ACodec  (14826): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
I/ACodec  (14826): [OMX.Exynos.avc.dec] Now Executing
I/TransportRuntime.CctTransportBackend(14826): Status Code: 200
I/TransportRuntime.CctTransportBackend(14826): Content-Type: application/json; charset=UTF-8
I/TransportRuntime.CctTransportBackend(14826): Content-Encoding: gzip
I/ACodec  (14826): [OMX.Exynos.avc.dec] signalFlush
I/ACodec  (14826): [OMX.Exynos.avc.dec] ExecutingState flushing now (codec owns 0/5 input, 0/16 output).
I/ACodec  (14826): [OMX.Exynos.avc.dec] Now Flushing
I/ACodec  (14826): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,0)
I/ACodec  (14826): [OMX.Exynos.avc.dec] FlushingState onOMXEvent(0,1,1)
I/ACodec  (14826): [OMX.Exynos.avc.dec] Now Executing
```

</details>

**Comment by TahaTesser** [comment]
Hi @bholendraofficial 
Can you please provide your `flutter doctor -v` , your `pubspec.yaml`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
