### ISSUE TITLE
`SnackBar` constructor assertions don't take into account `SnackBarThemeData.behavior`

### ISSUE THREAD

**Issue by sullenel** [flutter/flutter#84935]
There is a way to set snackbar behavior via `SnackBarThemeData`, but the margin can only be set via the `SnackBar`'s constructor. Due to this, when the margin is specified and the `behavior` is set to `SnackBarBehavior.floating` via the theme, the latter must be duplicated in the constructor call cause otherwise the following assertion throws.

https://github.com/flutter/flutter/blob/25ba467b5a9bf1a3a9c84ca70d7c807ac4da5200/packages/flutter/lib/src/material/snack_bar.dart#L259

The same is true for the `width` property. 
https://github.com/flutter/flutter/blob/25ba467b5a9bf1a3a9c84ca70d7c807ac4da5200/packages/flutter/lib/src/material/snack_bar.dart#L263

## Steps to Reproduce
Run the following code

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        snackBarTheme: SnackBarThemeData(
          behavior: SnackBarBehavior.floating, // <--
        ),
      ),
      debugShowCheckedModeBanner: false,
      home: ScaffoldMessenger(
        child: Scaffold(
          body: Center(
            child: MyWidget(),
          ),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TextButton(
      onPressed: () {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Test'),
            // behavior: SnackBarBehavior.floating, // assertion error without this
            margin: const EdgeInsets.all(16),
          ),
        );
      },
      child: Text('Show'),
    );
  }
}
```

**Expected results:**
No errors since the behavior is set via the theme

**Actual results:** 
```
Margin can only be used with floating behavior
'package:flutter/src/material/snack_bar.dart':
Failed assertion: line 259 pos 10: 'margin == null || behavior == SnackBarBehavior.floating'
```

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.411, on Microsoft Windows [Version 10.0.19041.1052], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
[✓] Android Studio (version 4.2.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (4 available)

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
<details>
<summary>error log</summary>

```

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
Margin can only be used with floating behavior
'package:flutter/src/material/snack_bar.dart':
Failed assertion: line 259 pos 10: 'margin == null || behavior == SnackBarBehavior.floating'

When the exception was thrown, this was the stack: 
#2      new SnackBar (package:flutter/src/material/snack_bar.dart:259:10)
#3      MyWidget.build.<anonymous closure> (package:macbug/main.dart:34:11)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:558:9)
#10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#17     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:289:11)
#18     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#19     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#25     _invoke1 (dart:ui/hooks.dart:182:10)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#40e40
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(215.7, 456.0)
  finalLocalPosition: Offset(33.7, 11.0)
  button: 1
  sent tap down
====================================================================================================





```

</details>

<details>
<summary> flutter doctor -v </summary>

```
dhs@Dhss-MacBook-Pro ncflutter % flutter doctor -v
[✓] Flutter (Channel master, 2.3.0-17.0.pre.414, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-17.0.pre.414 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 757c3add14 (7 hours ago), 2021-06-20 22:29:02 -0400
    • Engine revision 9520bb15b3
    • Dart version 2.14.0 (build 2.14.0-228.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.106

• No issues found!

```

</details>

**Comment by HansMuller** [comment]
CC @Piinks
