### ISSUE TITLE
Integration test scrollUntilVisible is not working.

### ISSUE THREAD

**Issue by XenLabsNikhil** [flutter/flutter#85046]
## Steps to Reproduce

I am trying to write integration test for flutter ListView.builder & scroll to specific item in the list. 

This gives error - 
```
type 'ListView' is not a subtype of type 'Scrollable' in type cast
```

Below are the details for the same - 

pubspec.yaml file
```
name: sample_integration_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

```

lib/main.dart file
```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(1000, (i) => 'Item $i'),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  MyApp({Key? key, required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: ListView.builder(
          key: Key("list"),
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              key: Key("item" + index.toString()),
              title: Text('${items[index]}'),
            );
          },
        ),
      ),
    );
  }
}

```

test_driver/integration_test.dart file
```
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();
```

integration_test/app_test.dart file
```
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:sample_integration_test/main.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  // Tests will go here...
  testWidgets(
    "Listview.builder scroll test",
    (WidgetTester tester) async {
      // Testing starts at the root widget in the widget tree

      await tester.pumpWidget(MyApp(
        items: List<String>.generate(1000, (i) => 'Item $i'),
      ));

      // await tester.tap(find.byType(FloatingActionButton));
      // // Wait for all the animations to finish
      await tester.pumpAndSettle();

      final list = find.byKey(Key("list"));
      final selectedItem = find.byKey(Key("item5"));

      await tester.scrollUntilVisible(selectedItem, -200.0,
          scrollable: list, maxScrolls: 200);

      await Future.delayed(const Duration(seconds: 1));
    },
  );
}

```

Command to run the test - 

```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
```

**Expected results:** 

Test passed

**Actual results:** 

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following _CastError was thrown running a test:
type 'ListView' is not a subtype of type 'Scrollable' in type 
cast

```
Running "flutter pub get" in sample_integration_test...          1,655ms
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         8.6s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                10.0s
W/Gralloc3(15285): mapper 3.x is not supported
W/Choreographer(15285): Already have a pending vsync event.  There should only be one at a time.
I/Choreographer(15285): Skipped 34 frames!  The application may be doing too much work on its main thread.
D/OnePlusJankManager(15285):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle =
com.example.sample_integration_test/com.example.sample_integration_test.MainActivity--- jank level = 3
D/SharedPreferencesImpl(15285): Time required to fsync /data/user/0/com.example.sample_integration_test/shared_prefs/embryo.xml: [<1: 0, <2: 0, <4: 0, <8: 0,
<16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 1, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:58922/W5EAvArSXzQ=/
VMServiceFlutterDriver: Isolate found with number: 3707526729812319
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (15285): 00:00 +0: Listview.builder scroll test
VMServiceFlutterDriver: Connected to Flutter application.
I/flutter (15285): (The following exception is now available via WidgetTester.takeException:)
I/flutter (15285): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (15285): The following _CastError was thrown running a test:
I/flutter (15285): type 'ListView' is not a subtype of type 'Scrollable' in type cast
I/flutter (15285): 
I/flutter (15285): When the exception was thrown, this was the stack:
I/flutter (15285): #0      WidgetController.widget (package:flutter_test/src/controller.dart:67:44)
I/flutter (15285): #1      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
I/flutter (15285): #2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
I/flutter (15285): #5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
I/flutter (15285): #6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
I/flutter (15285): #7      main.<anonymous closure>
(file:///Users/xenlabs/Documents/Nikhil/Trial_Apps/sample_integration_test/integration_test/app_test.dart:26:20)
I/flutter (15285): <asynchronous suspension>
I/flutter (15285): <asynchronous suspension>
I/flutter (15285): (elided 3 frames from dart:async and package:stack_trace)
I/flutter (15285): 
I/flutter (15285): The test description was:
I/flutter (15285):   Listview.builder scroll test
I/flutter (15285): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15285): (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when
another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected
the exception.)
I/flutter (15285): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (15285): The following _CastError was thrown running a test:
I/flutter (15285): type 'ListView' is not a subtype of type 'Scrollable' in type cast
I/flutter (15285): 
I/flutter (15285): When the exception was thrown, this was the stack:
I/flutter (15285): #0      WidgetController.widget (package:flutter_test/src/controller.dart:67:44)
I/flutter (15285): #1      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
I/flutter (15285): #2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
I/flutter (15285): #5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
I/flutter (15285): #6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
I/flutter (15285): #7      main.<anonymous closure>
(file:///Users/xenlabs/Documents/Nikhil/Trial_Apps/sample_integration_test/integration_test/app_test.dart:26:20)
I/flutter (15285): <asynchronous suspension>
I/flutter (15285): <asynchronous suspension>
I/flutter (15285): (elided 3 frames from dart:async and package:stack_trace)
I/flutter (15285): 
I/flutter (15285): The test description was:
I/flutter (15285):   Listview.builder scroll test
I/flutter (15285): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15285): 00:02 +0: Listview.builder scroll test [E]
I/flutter (15285):   Test failed. See exception logs above.
I/flutter (15285):   The test description was: Listview.builder scroll test
I/flutter (15285):   
I/flutter (15285): 00:02 +0 -1: (tearDownAll)
W/ntegration_tes(15285): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist,
linking, allowed)
I/flutter (15285): 00:02 +1 -1: Some tests failed.
Failure Details:
Failure in method: Listview.builder scroll test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following _CastError was thrown running a test:
type 'ListView' is not a subtype of type 'Scrollable' in type
cast

When the exception was thrown, this was the stack:
#0      WidgetController.widget (package:flutter_test/src/controller.dart:67:44)
#1      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
#5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
#7      main.<anonymous closure> (file:///Users/xenlabs/Documents/Nikhil/Trial_Apps/sample_integration_test/integration_test/app_test.dart:26:20)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The test description was:
  Listview.builder scroll test
═════════════════════════════════════════════════════════════════

end of failure 1

```

<details>
  <summary>Logs</summary>

flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.0)
[✓] Connected device (3 available)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @XenLabsNikhil 
You don't need to provide `scrollable` since your finder is already finding scrollable (ListView in this)

Update your test with the following and test will pass 
`await tester.scrollUntilVisible(selectedItem, -200.0, maxScrolls: 200);`

[scrollUntilVisible ](https://api.flutter.dev/flutter/flutter_test/WidgetController/scrollUntilVisible.html) mentions  `scrollable`  is null, this will find scrollable

**Comment by XenLabsNikhil** [comment]
> Hi @XenLabsNikhil
> You don't need to provide `scrollable` since your finder is already finding scrollable (ListView in this)
> 
> Update your test with the following and test will pass
> `await tester.scrollUntilVisible(selectedItem, -200.0, maxScrolls: 200);`
> 
> ```
> I/flutter ( 9791): 00:00 +0: Listview.builder scroll test
> VMServiceFlutterDriver: Connected to Flutter application.
> I/flutter ( 9791): 00:02 +1: (tearDownAll)
> I/flutter ( 9791): 00:02 +2: All tests passed!
> All tests passed.
> ```
> 
> [scrollUntilVisible ](https://api.flutter.dev/flutter/flutter_test/WidgetController/scrollUntilVisible.html) mentions `scrollable` is null, this will find scrollable

@TahaTesser 
I tried this but it works for item with key **item5** which is already visible on the screen. 
But once I change it to **item50** it does not work. 

```
final selectedItem = find.byKey(Key("item50"));
await tester.scrollUntilVisible(selectedItem, -200.0, maxScrolls: 200);
```

The error I got here is below

```
I/flutter (23124): 00:19 +0 -1: (tearDownAll)
W/ntegration_tes(23124): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z
(greylist, linking, allowed)
I/flutter (23124): 00:19 +1 -1: Some tests failed.
Failure Details:
Failure in method: Listview.builder scroll test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:498:25)
#1      WidgetController.element (package:flutter_test/src/controller.dart:112:30)
#2      WidgetController.dragUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1181:38)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Listview.builder scroll test
═════════════════════════════════════════════════════════════════

end of failure 1

```

**Comment by TahaTesser** [comment]
Hi @XenLabsNikhil 
Try the following, test passes with 50th item visible on the screen
```dart
 final list = find.byKey(Key("list"));
      final selectedItem = find.byKey(Key("item50"));

      await tester.scrollUntilVisible(selectedItem, 200);

      await Future.delayed(const Duration(seconds: 1));
```

**Comment by vrnvorona** [comment]
Hello, @TahaTesser.
Isn't it not recommended to use Future.delayed instead of pump?

**Comment by XenLabsNikhil** [comment]
> Hi @XenLabsNikhil
> Try the following, test passes with 50th item visible on the screen
> 
> ```dart
>  final list = find.byKey(Key("list"));
>       final selectedItem = find.byKey(Key("item50"));
> 
>       await tester.scrollUntilVisible(selectedItem, 200);
> 
>       await Future.delayed(const Duration(seconds: 1));
> ```

Hello @TahaTesser ,

Thank you. This solution worked if there is only one scrollable list. 

I tried this on the screen with 2 lists & faced issues in it. Below is the code - 

**main.dart**
```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(1000, (i) => 'Item $i'),
    places: List<String>.generate(1000, (i) => 'Place $i'),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;
  final List<String> places;

  MyApp({Key? key, required this.items, required this.places})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Column(
          children: [
            Expanded(
              child: ListView.builder(
                key: Key("list"),
                itemCount: items.length,
                itemBuilder: (context, index) {
                  return ListTile(
                    key: Key("item" + index.toString()),
                    title: Text('${items[index]}'),
                  );
                },
              ),
            ),
            Expanded(
              child: ListView.builder(
                key: Key("places"),
                itemCount: places.length,
                itemBuilder: (context, index) {
                  return ListTile(
                    key: Key("place" + index.toString()),
                    title: Text('${places[index]}'),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**app_test.dart**
```
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:sample_integration_test/main.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  // Tests will go here...
  testWidgets(
    "Listview.builder scroll test",
    (WidgetTester tester) async {
      // Testing starts at the root widget in the widget tree

      await tester.pumpWidget(MyApp(
        items: List<String>.generate(1000, (i) => 'Item $i'),
        places: List<String>.generate(1000, (i) => 'Place $i'),
      ));

      // // Wait for all the animations to finish
      await tester.pumpAndSettle();

      final list = find.byKey(Key("list"));
      final selectedItem = find.byKey(Key("item50"));
      final places = find.byKey(Key("places"));
      final selectedPlace = find.byKey(Key("place50"));

      // await tester.scrollUntilVisible(selectedItem, 200.0,
      //     scrollable: list, maxScrolls: 200);
      // await Future.delayed(const Duration(seconds: 1));

      await tester.scrollUntilVisible(selectedItem, 200.0);
      await Future.delayed(const Duration(seconds: 1));
      await tester.scrollUntilVisible(selectedPlace, 200.0);
      await Future.delayed(const Duration(seconds: 1));
    },
  );
}

```

Here, when I use 

`await tester.scrollUntilVisible(selectedItem, 200.0);`

This gives error as below

```
I/flutter (17172): 00:02 +1 -1: Some tests failed.
Failure Details:
Failure in method: Listview.builder scroll test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following StateError was thrown running a test:
Bad state: Too many elements
```

And when I use 

```
      await tester.scrollUntilVisible(selectedItem, 200.0,
          scrollable: list, maxScrolls: 200);
```

This gives error as below 

```
I/flutter (23403): 00:02 +1 -1: Some tests failed.
Failure Details:
Failure in method: Listview.builder scroll test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following _CastError was thrown running a test:
type 'ListView' is not a subtype of type 'Scrollable' in type
cast

```

**Comment by TahaTesser** [comment]
Hi @XenLabsNikhil 
Looks like it is an issue when scrolling multiple scroll views, I don't see any documentation on this
Labelling for documentation and official example
Thank you

**Comment by XenLabsNikhil** [comment]
> Hi @XenLabsNikhil
> Looks like it is an issue when scrolling multiple scroll views, I don't see any documentation on this
> Labelling for documentation and official example
> Thank you

Hi @TahaTesser 
I had the same problem while looking for an example of this.
Thank you.

**Comment by orestesgaolin** [comment]
I have similar problem, I have two nested ListViews and trying to scroll one with 

```
     await tester.scrollUntilVisible(
        find.byKey(const Key('deviceDetails_separatedListView')),
        500,
        scrollable: find.byKey(const Key('deviceDetails_mainListView')),
      );
```

this throws with the error as above:

```
The following _CastError was thrown running a test:
type 'ListView' is not a subtype of type 'Scrollable' in type cast

When the exception was thrown, this was the stack:
#0      WidgetController.widget (package:flutter_test/src/controller.dart:67:44)
#1      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1139:15)
#2      WidgetController.scrollUntilVisible.<anonymous closure> (package:flutter_test/src/controller.dart:1137:39)
#5      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#6      WidgetController.scrollUntilVisible (package:flutter_test/src/controller.dart:1137:27)
```

as `ListView` is not `Scrollable` but `BoxScrollView`

**Comment by brenodt** [comment]
@XenLabsNikhil @orestesgaolin  Maybe you can try something in the lines of the below:

#### app_test.dart
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:sample_integration_test/main.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  // Tests will go here...
  testWidgets(
    "Listview.builder scroll test",
    (tester) async {
      // Testing starts at the root widget in the widget tree

      await tester.pumpWidget(MyApp(
        items: List<String>.generate(1000, (i) => 'Item $i'),
        places: List<String>.generate(1000, (i) => 'Place $i'),
      ));

      // Wait for all the animations to finish
      await tester.pumpAndSettle();

      // list finders
      final list = find.byKey(Key("list"));
      final places = find.byKey(Key("places"));

      // scrollable finders
      final scrollable = find.byWidgetPredicate((w) => w is Scrollable);
      final scrollableOfList = find.descendant(of: list, matching: scrollable);
      final scrollableOfPlaces = find.descendant(of: places, matching: scrollable);

      final selectedItem = find.byKey(Key("item50"));
      final selectedPlace = find.byKey(Key("place50"));

      await tester.scrollUntilVisible(selectedItem, 200.0, scrollable: scrollableOfList);
      await tester.pump();

      await tester.scrollUntilVisible(selectedPlace, 200.0, scrollable: scrollableOfPlaces);
      await tester.pump();
    },
  );
}
```

The reason you can't pass in the finder for your `ListView` object directly into the `scrollable` parameter is that, essentially, `ListView` is wrapping the `Scrollable` object for you, eliminating a bunch of boilerplate and simplifying the implementation on your end.

Therefore, this is why `ListView` is not a sub-type of `Scrollable`. It doesn't simply extends this object. It rather uses it _as a part_ of its implementation.

By fetching the closest `Scrollable` that is a descendant of a specific list, the expected behavior is achieved.

**Comment by XenLabsNikhil** [comment]
Hi @brenodt 

This worked as expected. 
Also understood the explanation given by you. 

I think, this does need the official documentation from flutter for everyone who is following integration test in their testing phase.

Thank you.

**Comment by feinstein** [comment]
I think it would be beneficial if `scrollUntilVisible` could be smart enough to accept the types of scrollable widgets provided by Flutter automatically (`ListView`, `SingleChildScrollView`, etc).
