### ISSUE TITLE
ChoiceChip has some weird white rounded corners

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [flutter/flutter#85086]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: main.dart code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color(0xff343f56),
      body: ChoiceChip(
        label: Text("DUPA"),
        backgroundColor: Color(0xff232e45),
        selectedColor: Color(0xff232e45),
        selected:
            true,
      ),
    );
  }
}
```
3. Just run the app.

**Expected results:**
I wanted a normal looking, dark screen, with a chip of even darker color.

**Actual results:**

The chip has strange white corners. The same result on web debug, apk debug and apk release installed on my Redmi 5.
![image](https://user-images.githubusercontent.com/19879399/123014214-040edb80-d3c6-11eb-9bb4-1b5e53e240a6.png)

<details>
  <summary>Logs</summary>

```
[ +195 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +916 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] d79295af24c3ed621c33713ecda14ad196fd9c31
[   +1 ms] executing: [C:\flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[  +96 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[        ] 2.2.2
[  +13 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +81 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +68 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +244 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +79 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +156 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +126 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +89 ms] List of devices attached
           9ea4c25d7cf5           device product:rosy model:Redmi_5 device:rosy transport_id:3
[  +11 ms] C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 shell getprop
[ +382 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +175 ms] Skipping pub get: version match.
[ +222 ms] Generating C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +127 ms] ro.hardware = qcom
[  +84 ms] Initializing file store
[  +32 ms] Skipping target: gen_localizations
[  +22 ms] complete
[  +11 ms] Launching lib\main.dart on Redmi 5 in debug mode...
[  +17 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Dawid\AppData\Local\Temp\flutter_tools.185af72b\flutter_tool.f889013f\app.dill --packages
C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts    
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\3c113a45063dc6628e68a4111abcacad.cache.dill.track.dill     
--enable-experiment=alternative-invalidation-strategy
[  +45 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 shell -x logcat -v time -t 1
[  +48 ms] <- compile package:bug/main.dart
[ +240 ms] --------- beginning of main
                    06-23 01:47:20.361 D/BtGatt.ScanManager( 1739): configureRegularScanParams() - ScanSetting Scan mode=2
                    mLastConfiguredScanSetting=2
[  +27 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe version
[ +104 ms] Android Debug Bridge version 1.0.41
                    Version 31.0.2-7242960
                    Installed as C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +9 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +41 ms] Building APK
[  +98 ms] Running Gradle task 'assembleDebug'...
[  +17 ms] Using gradle from C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\android\gradlew.bat.
[  +26 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +316 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.8" 2020-07-14
           OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
           OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
[   +4 ms] executing: [C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\android/]
C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
-Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1588 ms] Welcome to Gradle 6.7!
[   +1 ms] Here are the highlights of this release:
[   +1 ms]  - File system watching is ready for production use
[   +5 ms]  - Declare the version of Java your build requires
[   +3 ms]  - Java 15 support
[   +4 ms] For more details see https://docs.gradle.org/6.7/release-notes.html
[+6049 ms] > Task :app:compileFlutterBuildDebug
[   +3 ms] [ +205 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +999 ms] [+1124 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [   +1 ms] d79295af24c3ed621c33713ecda14ad196fd9c31
[   +2 ms] [   +1 ms] executing: [C:\flutter/] git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[ +185 ms] [ +112 ms] Exit code 0 from: git tag --points-at d79295af24c3ed621c33713ecda14ad196fd9c31
[   +2 ms] [        ] 2.2.2
[   +1 ms] [  +18 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +90 ms] [ +103 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +9 ms] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +99 ms] [  +88 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] [        ] https://github.com/flutter/flutter.git
[ +199 ms] [ +203 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] [  +83 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[ +292 ms] [ +199 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] [   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +6 ms] [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +22 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +447 ms] [ +570 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +11 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +7 ms] [   +9 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +5 ms] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +5 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +132 ms] [ +140 ms] Initializing file store
[  +91 ms] [  +71 ms] Skipping target: gen_localizations
[   +2 ms] [  +28 ms] kernel_snapshot: Starting due to {}
[   +2 ms] [  +30 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true 
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages
C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\.dart_tool\package_config.json --output-dill
C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\.dart_tool\flutter_build\845275bc252f67b1a206a6217a216b60\app.dill --depfile
C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\.dart_tool\flutter_build\845275bc252f67b1a206a6217a216b60\kernel_snapshot.d package:bug/main.dart  
[+21290 ms] [+21262 ms] kernel_snapshot: Complete
[+1100 ms] [+1083 ms] debug_android_application: Starting due to {}
[ +407 ms] [ +387 ms] debug_android_application: Complete
[+1199 ms] [+1260 ms] Persisting file store
[  +92 ms] [  +21 ms] Done persisting file store
[        ] [  +17 ms] build succeeded.
[   +1 ms] [  +44 ms] "flutter assemble" took 25 001ms.
[ +105 ms] [  +88 ms] ensureAnalyticsSent: 74ms
[   +2 ms] [   +2 ms] Running shutdown hooks
[   +1 ms] [        ] Shutdown hooks complete
[   +2 ms] [        ] exiting with code 0
[ +483 ms] > Task :app:packLibsflutterBuildDebug
[  +17 ms] > Task :app:preBuild UP-TO-DATE
[  +36 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +3 ms] > Task :app:compileDebugAidl NO-SOURCE
[  +15 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +9 ms] > Task :app:generateDebugBuildConfig
[  +30 ms] > Task :app:checkDebugAarMetadata
[   +1 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[  +99 ms] > Task :app:mergeDebugShaders
[  +14 ms] > Task :app:compileDebugShaders NO-SOURCE
[   +7 ms] > Task :app:generateDebugAssets UP-TO-DATE
[  +75 ms] > Task :app:mergeDebugAssets
[ +591 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues
[        ] > Task :app:generateDebugResources
[+1210 ms] > Task :app:createDebugCompatibleScreenManifests
[ +284 ms] > Task :app:extractDeepLinksDebug
[ +825 ms] > Task :app:processDebugMainManifest
[  +34 ms] > Task :app:processDebugManifest
[ +275 ms] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[ +279 ms] > Task :app:javaPreCompileDebug
[  +27 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +2 ms] > Task :app:mergeDebugResources
[   +8 ms] > Task :app:checkDebugDuplicateClasses
[ +246 ms] > Task :app:mergeDebugJniLibFolders
[ +113 ms] > Task :app:desugarDebugFileDependencies
[  +19 ms] > Task :app:validateSigningDebug
[ +179 ms] > Task :app:processDebugManifestForPackage
[+1488 ms] > Task :app:compressDebugAssets
[ +614 ms] > Task :app:processDebugResources
[+2001 ms] > Task :app:mergeExtDexDebug
[+2617 ms] > Task :app:compileDebugKotlin
[+2668 ms] > Task :app:mergeDebugNativeLibs
[+1495 ms] > Task :app:compileDebugJavaWithJavac
[   +5 ms] > Task :app:compileDebugSources
[ +614 ms] > Task :app:dexBuilderDebug
[+1185 ms] > Task :app:stripDebugDebugSymbols
[   +9 ms] Unable to strip the following libraries, packaging them as they are: libflutter.so.
[ +291 ms] > Task :app:mergeDebugJavaResource
[ +395 ms] > Task :app:mergeDexDebug
[+3707 ms] > Task :app:packageDebug
[ +300 ms] > Task :app:assembleDebug
[   +2 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +1 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] BUILD SUCCESSFUL in 56s
[        ] 32 actionable tasks: 31 executed, 1 up-to-date
[ +553 ms] Running Gradle task 'assembleDebug'... (completed in 57,8s)
[  +73 ms] calculateSha: LocalDirectory: 'C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\build\app\outputs\flutter-apk'/app.apk
[+1185 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[  +11 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree
C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +36 ms] Exit code 0 from: C:\Users\Dawid\AppData\Local\Android\sdk\build-tools\30.0.3\aapt dump xmltree
C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.bug" (Raw: "com.example.bug")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="bug" (Raw: "bug")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")  
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.bug.MainActivity" (Raw: "com.example.bug.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +17 ms] Stopping app 'app.apk' on Redmi 5.
[   +1 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 shell am force-stop com.example.bug
[ +216 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 shell pm list packages com.example.bug
[+2348 ms] Installing APK.
[   +4 ms] Installing build\app\outputs\flutter-apk\app.apk...
[   +1 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 install -t -r
C:\Users\Dawid\Documents\Projekty\Flutter\Test\bug\build\app\outputs\flutter-apk\app.apk
[+26948 ms] Performing Streamed Install
                     Success
[   +5 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 27,0s)
[   +7 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 shell echo -n
c4ed1dc3657aff7e4a54bef137979dd85b0592b4 > /data/local/tmp/sky.com.example.bug.sha1
[ +220 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 shell -x logcat -v time -t 1
[ +227 ms] --------- beginning of system
                    06-23 01:48:50.485 W/AppOps  ( 1584): Bad call: specified package com.google.android.gms under uid 10096 but it is really 10021   
                    06-23 01:48:50.485 W/AppOps  ( 1584): java.lang.RuntimeException: here
                    06-23 01:48:50.485 W/AppOps  ( 1584):       at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1444)
                    06-23 01:48:50.485 W/AppOps  ( 1584):       at com.android.server.AppOpsService.checkPackage(AppOpsService.java:1112)
                    06-23 01:48:50.485 W/AppOps  ( 1584):       at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:169)   
                    06-23 01:48:50.485 W/AppOps  ( 1584):       at android.os.Binder.execTransact(Binder.java:704)
[  +13 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 shell am start -a android.intent.action.RUN -f
0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true        
com.example.bug/com.example.bug.MainActivity
[ +466 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.bug/.MainActivity (has extras) }
[   +4 ms] Waiting for observatory port to be available...
[+5550 ms] Observatory URL on device: http://127.0.0.1:35079/5L1IxVVi3_w=/
[   +3 ms] executing: C:\Users\Dawid\AppData\Local\Android\sdk\platform-tools\adb.exe -s 9ea4c25d7cf5 forward tcp:0 tcp:35079
[  +38 ms] 57856
[   +1 ms] Forwarded host port 57856 to device port 35079 for Observatory
[   +8 ms] Caching compiled dill
[  +65 ms] Connecting to service protocol: http://127.0.0.1:57856/5L1IxVVi3_w=/
[ +930 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:57856/5L1IxVVi3_w=/.
[+3075 ms] DDS is listening at http://127.0.0.1:57861/KMecJ3FIjzc=/.
[ +102 ms] Successfully connected to service protocol: http://127.0.0.1:57856/5L1IxVVi3_w=/
[  +50 ms] DevFS: Creating new filesystem on the device (null)
[  +54 ms] D/vndksupport( 4213): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal
namespace.
[   +1 ms] D/vndksupport( 4213): Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
[  +77 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.bug/code_cache/bugGTGYOD/bug/)
[   +3 ms] Updating assets
[ +151 ms] Syncing files to device Redmi 5...
[   +3 ms] <- reset
[   +1 ms] Compiling dart to kernel with 0 updated files
[   +4 ms] <- recompile package:bug/main.dart a5d38f08-9e88-4e4e-8e63-861b4e5e24e6
[        ] <- a5d38f08-9e88-4e4e-8e63-861b4e5e24e6
[ +171 ms] Updating files.
[        ] DevFS: Sync finished
[   +3 ms] Syncing files to device Redmi 5... (completed in 184ms)
[   +3 ms] Synced 0.0MB.
[   +3 ms] <- accept
[ +415 ms] Connected to _flutterView/0x722aa98820.
[   +5 ms] Flutter run key commands.
[   +6 ms] r Hot reload. 
[   +5 ms] R Hot restart.
[   +2 ms] h Repeat this help message.
[   +2 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[   +1 ms]  Running with sound null safety 
[   +8 ms] An Observatory debugger and profiler on Redmi 5 is available at: http://127.0.0.1:57861/KMecJ3FIjzc=/
[ +887 ms] The Flutter DevTools debugger and profiler on Redmi 5 is available at:
http://127.0.0.1:9103?uri=http%3A%2F%2F127.0.0.1%3A57861%2FKMecJ3FIjzc%3D%2F
```

```
Analyzing bug...                                                        
No issues found! (ran in 39.0s)
```

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale pl-PL)
    • Flutter version 2.2.2 at C:\flutter
    • Framework revision d79295af24 (11 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Dawid\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\Dawid\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Redmi 5 (mobile) • 9ea4c25d7cf5 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)     • chrome       • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)       • edge         • web-javascript • Microsoft Edge 91.0.864.54
```

</details>

**Comment by TahaTesser** [comment]
Hi @dawid-niedzwiecki 
This is a known issue https://github.com/flutter/flutter/issues/54370
Read this https://github.com/flutter/flutter/issues/54370#issuecomment-611714132 for details
Closing as duplicate
