### ISSUE TITLE
Swipe Away demo crashes when you let the sun shine

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#851]
Clicking the "Let the sun shine" drawer checkbox in the card_collection.dart widget example causes an assert.

```
android: I/flutter : The following exception was raised during paint():
android: I/flutter : 'packages/flutter/src/rendering/object.dart': Failed assertion: line 330: '!needsCompositing' is not true.
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      PaintingContext.pushShaderMask (packages/flutter/src/rendering/object.dart:330)
android: I/flutter : #2      RenderShaderMask.paint (packages/flutter/src/rendering/proxy_box.dart:585)
android: I/flutter : #3      RenderObject._paintWithContext (packages/flutter/src/rendering/object.dart:996)
android: I/flutter : #4      PaintingContext.paintChild (packages/flutter/src/rendering/object.dart:93)
android: I/flutter : #5      RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (packages/flutter/src/rendering/box.dart:807)
android: I/flutter : #6      RenderStack.paintStack (packages/flutter/src/rendering/stack.dart:437)
android: I/flutter : #7      RenderStackBase.paint (packages/flutter/src/rendering/stack.dart:392)
android: I/flutter : #8      RenderObject._paintWithContext (packages/flutter/src/rendering/object.dart:996)
```

**Comment by abarth** [comment]
Fixed!
