### ISSUE TITLE
Master branch throwing a scrollController error after upgrading flutter to the latest commit. 

### ISSUE THREAD

**Issue by therenca** [flutter/flutter#85105]
This error is being thrown by flutter. I am unable to solve it as it does not appear to be caused by the application code. There were no errors before upgrade, after doing a flutter upgrade --force on the master branch for the destkop environment, this error started showing .... 

<details> 
<summary>logs</summary> 
	
```console
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided 

ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack
#0      RawScrollbarState._checkForValidScrollPosition.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1101
#1      RawScrollbarState._checkForValidScrollPosition
package:flutter/…/widgets/scrollbar.dart:1125
#2      RawScrollbarState._maybeTriggerScrollbar.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1042
#3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1088
#5      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:996
#9      _invoke (dart:ui/hooks.dart:163:10)
#10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#11     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)
```

</details>

**Comment by arualana** [comment]
Same when using https://pub.dev/packages/flutter_portal

**Comment by TahaTesser** [comment]
Hi @therenca 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by therenca** [comment]
after syncing to the latest commit, the runtime error is no longer occurring. thanks

**Comment by TahaTesser** [comment]
Hi @therenca 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
