### ISSUE TITLE
flutter run fails to start app

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#85117]
`flutter run` fails to start app but only on my iPhone 12 mini. It works fine on my iPhone 7. Running from Xcode works fine also.
It does not work if I run `flutter run` from CLI on my iPhone 12 mini.

flutter run -v:
```
[        ] Application launched on the device. Waiting for observatory port.
[+30047 ms] Installing and launching... (completed in 45.2s)
[   +2 ms] Error launching application on Tudor’s iPhone.
[  +12 ms] "flutter run" took 70,959ms.
[  +31 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +25 ms] (lldb) process detach
[ +239 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale en-RO)
    • Flutter version 2.2.1 at /Users/tudorwork/dev/flutter
    • Framework revision 02c026b03c (4 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Applications/androidsdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /Applications/androidsdk/platform-tools
    • ANDROID_SDK_ROOT = /Applications/androidsdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Tudor’s iPhone (mobile) • 00008101-00020CA108E1401E • ios • iOS 14.6

! Doctor found issues in 2 categories.
```

**Comment by phucntbepos** [comment]
I have the same issue on my iPad gen 8, iPadOS 14.6
 
`flutter run -v`
```[+1989 ms] (lldb) command source -s 0 '/tmp/9E0ED814-D04F-49E4-BBDC-49849D3A956D/fruitstrap-lldb-prep-cmds-00008020_000970900261402E'
[        ] Executing commands in '/tmp/9E0ED814-D04F-49E4-BBDC-49849D3A956D/fruitstrap-lldb-prep-cmds-00008020_000970900261402E'.
[        ] (lldb)     platform select remote-ios --sysroot '/Users/phucnguyen/Library/Developer/Xcode/iOS DeviceSupport/14.6 (18F72)/Symbols'
[        ]   Platform: remote-ios
[        ]  Connected: no
[        ]   SDK Path: "/Users/phucnguyen/Library/Developer/Xcode/iOS DeviceSupport/14.6 (18F72)/Symbols"
[        ] (lldb)     target create "/Users/phucnguyen/Documents/be-projects/bepos-flutter/build/ios/iphoneos/Runner.app"
[+8517 ms] Current executable set to '/Users/phucnguyen/Documents/be-projects/bepos-flutter/build/ios/iphoneos/Runner.app' (arm64).
[        ] (lldb)     script fruitstrap_device_app="/private/var/containers/Bundle/Application/CEEB3D26-E6BC-4BA4-AB3F-0AEE44937612/Runner.app"
[ +515 ms] (lldb)     script fruitstrap_connect_url="connect://127.0.0.1:51531"
[        ] (lldb)     script fruitstrap_output_path=""
[        ] (lldb)     script fruitstrap_error_path=""
[        ] (lldb)     target modules search-paths add /usr "/Users/phucnguyen/Library/Developer/Xcode/iOS DeviceSupport/14.6 (18F72)/Symbols/usr" /System "/Users/phucnguyen/Library/Developer/Xcode/iOS DeviceSupport/14.6
(18F72)/Symbols/System" "/private/var/containers/Bundle/Application/CEEB3D26-E6BC-4BA4-AB3F-0AEE44937612" "/Users/phucnguyen/Documents/be-projects/bepos-flutter/build/ios/iphoneos"
"/var/containers/Bundle/Application/CEEB3D26-E6BC-4BA4-AB3F-0AEE44937612" "/Users/phucnguyen/Documents/be-projects/bepos-flutter/build/ios/iphoneos" /Developer "/Users/phucnguyen/Library/Developer/Xcode/iOS DeviceSupport/14.6
(18F72)/Symbols/Developer"
[  +24 ms] (lldb)     command script import "/tmp/9E0ED814-D04F-49E4-BBDC-49849D3A956D/fruitstrap_00008020_000970900261402E.py"
[   +3 ms] (lldb)     command script add -f fruitstrap_00008020_000970900261402E.connect_command connect
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000970900261402E.run_command run
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000970900261402E.autoexit_command autoexit
[        ] (lldb)     command script add -s asynchronous -f fruitstrap_00008020_000970900261402E.safequit_command safequit
[        ] (lldb)     connect
[  +50 ms] (lldb)     run
[ +580 ms] success
[        ] Application launched on the device. Waiting for observatory port.
[+30059 ms] Installing and launching... (completed in 82.1s)
[   +3 ms] Error launching application on be’s iPad.
[  +17 ms] "flutter run" took 1,482,359ms.
[  +17 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[   +9 ms] (lldb) process detach
[ +129 ms] ensureAnalyticsSent: 133ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
`flutter doctor -v`
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-VN)
    • Flutter version 2.2.2 at /opt/homebrew/Caskroom/flutter/2.2.2/flutter
    • Framework revision d79295af24 (12 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/phucnguyen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • be’s iPad (mobile) • 00008020-000970900261402E • ios            • iOS 14.6
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @tudor07 @phucntbepos 
Can you please provide complete logs from `flutter run -v`, paste the logs in a text file and drop in the comments below 
Thank you

**Comment by phucntbepos** [comment]
Hi @TahaTesser 
This is my entire `flutter run -v`
[flutter_run_verbose.txt](https://github.com/flutter/flutter/files/6724078/flutter_run_verbose.txt)

**Comment by bretmh** [comment]
Dealing with the same issue. I just build to my target device via xcode just fine as a work around.  Seems to be specific to my phone / configuration for my phone. Once i use a different iPhone it builds from flutter run fine.

**Comment by TahaTesser** [comment]
This actually looks like https://github.com/flutter/flutter/issues/72161
Closing as diuplicate of https://github.com/flutter/flutter/issues/72161

**Comment by Gastrolize** [comment]
Update to IOS 14.7, Xcode 13 Beta 3 and Flutter channel master fix's this issue. Make sure to completely uninstall the Xcode and set the Command Line Tools in Scheme > Edit Scheme > to xcode 13
