### ISSUE TITLE
[Web] : In release/profile mode, TabBar with flexibleSpace throws `NoSuchMethodError` exception

### ISSUE THREAD

**Issue by Zzy0706** [flutter/flutter#85136]
## Steps to Reproduce

Hi, 
When I launch in Release/Profile mode, the following code will cause the problem shown in the picture.

**Expected results:** 
 in debug model
![image](https://user-images.githubusercontent.com/27463212/123128796-05034400-d47e-11eb-8386-e178f41445c7.png)

**Actual results:** 
 in release/profile model
![image](https://user-images.githubusercontent.com/27463212/123128922-1e0bf500-d47e-11eb-9ee7-579b1c9de5d7.png)

<details>
  <summary>Code</summary>

```
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(

      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: DefaultTabController(
              length: 2,
              child: NestedScrollView(
                  headerSliverBuilder:
                      (BuildContext context, bool innerBoxIsScrolled) {
                    return [
                      SliverOverlapAbsorber(
                        handle: NestedScrollView.sliverOverlapAbsorberHandleFor(
                            context),
                        sliver: SliverAppBar(
                          pinned: true,
                          expandedHeight: 240,
                          floating: true,
                          flexibleSpace: FlexibleSpaceBar(
                            background: Container(
                              height: 200,
                              color: Colors.red,
                            ),
                          ),
                          bottom: TabBar(tabs: [
                            Tab(
                              text: '1',
                            ),
                            Tab(
                              text: '2',
                            ),
                          ]),
                        ),
                      ),
                    ];
                  },
                  body: TabBarView(children: [Center(),Center(),]))),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
NoSuchMethodError: method not found: 'get$value' on null
js_primitives.dart:47     at _TabBarState.get$_indicator (http://localhost:51322/main.dart.js:70701:17)
js_primitives.dart:47     at _TabBarState._initIndicatorPainter$0 (http://localhost:51322/main.dart.js:70745:20)
js_primitives.dart:47     at _TabBarState.didChangeDependencies$0 (http://localhost:51322/main.dart.js:70766:12)
js_primitives.dart:47     at StatefulElement._firstBuild$0 (http://localhost:51322/main.dart.js:91626:19)
js_primitives.dart:47     at StatefulElement.mount$2 (http://localhost:51322/main.dart.js:91498:12)
js_primitives.dart:47     at MultiChildRenderObjectElement.inflateWidget$2 (http://localhost:51322/main.dart.js:91273:16)
js_primitives.dart:47     at MultiChildRenderObjectElement.mount$2 (http://localhost:51322/main.dart.js:92085:26)
js_primitives.dart:47     at InheritedElement.inflateWidget$2 (http://localhost:51322/main.dart.js:91273:16)
js_primitives.dart:47     at InheritedElement.updateChild$3 (http://localhost:51322/main.dart.js:91197:26)
js_primitives.dart:47     at InheritedElement.performRebuild$0 (http://localhost:51322/main.dart.js:91521:41)
```

```
Analyzing demo_bug...
No issues found! (ran in 1.0s)

```

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1055], locale zh-CN)
    • Flutter version 2.2.2 at C:\Develop\flutter
    • Framework revision d79295af24 (12 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Flutter download mirror "https://mirrors.tuna.tsinghua.edu.cn/flutter"

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\zzy\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Develop\jdk-11\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11+28)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
Verified this on latest stable and master and see the same behavior using both renderers in release mode:

```
NoSuchMethodError: method not found: 'gq' on null
js_primitives.dart:47     at wl.gSE (http://localhost:54020/main.dart.js:36779:5)
js_primitives.dart:47     at wl.SG (http://localhost:54020/main.dart.js:36805:5)
js_primitives.dart:47     at wl.aG (http://localhost:54020/main.dart.js:36820:6)
js_primitives.dart:47     at f5.u6 (http://localhost:54020/main.dart.js:47127:34)
js_primitives.dart:47     at f5.dX (http://localhost:54020/main.dart.js:47083:6)
js_primitives.dart:47     at dU.qn (http://localhost:54020/main.dart.js:46982:3)
js_primitives.dart:47     at dU.dX (http://localhost:54020/main.dart.js:47341:40)
js_primitives.dart:47     at dq.qn (http://localhost:54020/main.dart.js:46982:3)
js_primitives.dart:47     at dq.cI (http://localhost:54020/main.dart.js:46942:16)
js_primitives.dart:47     at dq.fa (http://localhost:54020/main.dart.js:47090:32)
2js_primitives.dart:47 Another exception was thrown: Instance of 'minified:eg<void>'
```

1. In debug mode:

<img width="914" alt="Screenshot 2021-06-25 at 3 33 39 PM" src="https://user-images.githubusercontent.com/67046386/123408729-f8d8cd00-d5ca-11eb-86c0-5c18db80819e.png">


2. In release mode:

<img width="929" alt="Screenshot 2021-06-25 at 3 34 21 PM" src="https://user-images.githubusercontent.com/67046386/123408749-fe361780-d5ca-11eb-946c-76bc68361e5d.png">

<details>
<summary> master flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.504, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-17.0.pre.504 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 102acbe39d (43 minutes ago), 2021-06-24 22:51:02 -0700
    • Engine revision 4bf9d638c2
    • Dart version 2.14.0 (build 2.14.0-245.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!


```

</details>

<details>
<summary> stable flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.2 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision d79295af24 (11 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.106

• No issues found!



```

</details>

**Comment by ferhatb** [comment]
Changing tabs.dart code from:
if (widget.automaticIndicatorColorAdjustment && color.value == Material.of(context)?.color?.value)
      color = Colors.white;

to:
final Color? materialColor = Material.of(context)?.color;
    if (widget.automaticIndicatorColorAdjustment &&
        color.value == materialColor?.value)

Fixes issue. since DDC and dart2js don't agree, i assume a bug in dart2js.

**Comment by enghitalo** [comment]
Same problem here.
The problem not happen in --release when delete bottom or flexibleSpace in SliverAppBar widget.

**Comment by enghitalo** [comment]
But I have the messages in browser console:
`Installed new service worker.
js_primitives.dart:47 NoSuchMethodError: method not found: 'gl' on null
js_primitives.dart:47     at zS.gWH (http://localhost:34287/main.dart.js:40966:5)
js_primitives.dart:47     at zS.WJ (http://localhost:34287/main.dart.js:40992:5)
js_primitives.dart:47     at zS.aJ (http://localhost:34287/main.dart.js:41007:6)
js_primitives.dart:47     at hl.vL (http://localhost:34287/main.dart.js:52097:32)
js_primitives.dart:47     at hl.eO (http://localhost:34287/main.dart.js:52053:6)
js_primitives.dart:47     at eU.rM (http://localhost:34287/main.dart.js:51945:3)
js_primitives.dart:47     at eU.eO (http://localhost:34287/main.dart.js:52310:40)
js_primitives.dart:47     at ej.rM (http://localhost:34287/main.dart.js:51945:3)
js_primitives.dart:47     at ej.dB (http://localhost:34287/main.dart.js:51905:16)
js_primitives.dart:47     at ej.hs (http://localhost:34287/main.dart.js:52060:32)
146js_primitives.dart:47 Another exception was thrown: Instance of 'minified:eO<void>'`

**Comment by a-siva** [comment]
//cc @sigmundch this issue has been marked as P1 and probably needs an owner. If it is not reproducible or needs more information maybe we should bump the priority down.

**Comment by sigmundch** [comment]
I just tested the repro on a recent version of flutter (which is using Dart 3.1.0-dev), and it worked out of the box without modifications 🎉

We have made many changes in the global analysis in dart2js fixing subtle bugs in the last couple years since this was filed. It is likely the issue here was caused by one of those bugs, and that's the reason it is working now.

Given that we can no longer repro, I'll close this as fixed/obsolete. If anyone encounters a similar issue again, please don't hesitate to file a new issue.
