### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for D:\Android\flutter_2\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.

### ISSUE THREAD

**Issue by CalvinML** [flutter/flutter#85205]
## Command
```
flutter --quiet assemble --depfile F:\project\app\InkPi\build\app\intermediates\flutter\release/flutter_build.d --output F:\project\app\InkPi\build\app\intermediates\flutter\release -dTargetFile=lib\main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true -dTreeShakeIcons=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for D:\Android\flutter_2\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:232:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
```
```
[✓] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.17763.1823], locale zh-CN)
    • Flutter version 2.0.1 at D:\Android\flutter_2
    • Framework revision c5a4b4029c (4 months ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] Connected device (2 available)
    • Redmi K30 5G (mobile) • 8f6e2383 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
app_settings-4.1.0
audioplayer-0.8.1
auto_orientation-2.0.2
city_pickers-0.2.0
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
flutter_blue-0.8.0
flutter_plugin_android_lifecycle-1.0.11
flutter_share_me-0.9.2
flutter_webview_plugin
fluttertoast-4.0.1
fluwx-2.6.2
image_cropper-1.4.0
image_gallery_saver-1.6.9
image_picker-0.6.6+5
ota_update-3.0.2
package_info-0.4.3+4
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
permission_handler-5.1.0+2
qr_code_scanner-0.4.0
screen-0.0.5
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
vibration-1.7.3
vibration_web-1.6.2
video_player-2.1.5
video_player_web-2.0.1
webview_flutter-2.0.8
wifi_iot-0.2.2

**Comment by 0xf10yd** [comment]
make sure flutter_2\bin\cache\artifacts\engine\android-arm-release\windows-x64\ has gen_snapshot.exe file

**Comment by CalvinML** [comment]
> make sure flutter_2\bin\cache\artifacts\engine\android-arm-release\windows-x64\ has gen_snapshot.exe file

Okay, it's been fixed. It was deleted by security software by mistake

**Comment by 0xf10yd** [comment]
Ok, closed

**Comment by darshankawar** [comment]
Closing this as resolved based on above comments.
