### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by jfiyar** [flutter/flutter#85200]
## Command
```
flutter attach
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:327:17)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale zh-CN)
    • Flutter version 2.2.2 at D:\app\flutter
    • Framework revision d79295af24 (13 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\app\android studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at D:\app\android studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at D:\app\IntelliJ IDEA 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\misty\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • IN2010 (mobile) • 10.0.67.40:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome          • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)      • edge            • web-javascript • Microsoft Edge 91.0.864.54

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.haowuxiu.shai.flutter
**iOS bundle identifier**: com.haowuxiu.shai.flutter
**Creation channel**: stable
**Creation framework version**: 78910062997c3a836feee883712c241a5fd22983
### Plugins
flutter_boost-a3938eff699cfa9bd6e922ba736339db4f976314
video_player-2.1.4
video_player_web-2.0.0
wakelock-0.4.0
wakelock_macos-0.1.0+1
wakelock_web-0.2.0+1
webview_flutter-2.0.8

**Comment by darshankawar** [comment]
@jfiyar 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/84898
Please try the steps mentioned in that issue [comment](https://github.com/flutter/flutter/issues/84898#issuecomment-864891154) and see if it works for you.
If not, comment in that issue for further reference.

Closing this as duplicate.
