### ISSUE TITLE
Android Studio Layout Editor has problems with FlutterView

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter#8527]
An exception is displayed in the Layout Editor in Android Studio when choosing the design tab and a FlutterView is used in a layout file for example like this:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:orientation="vertical"
  android:layout_width="match_parent"
  android:layout_height="match_parent">

  <io.flutter.view.FlutterView
    android:id="@+id/flutter_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    />
</LinearLayout>

It says:

 Rendering Problems 
The following classes could not be instantiated:
          - io.flutter.view.FlutterView (Open Class, Show Exception, Clear Cache)

Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.ClassNotFoundException: org.json.JSONException Copy stack to clipboard 

Clicking on 'show Exception' it shows this stacktrace:

java.lang.ClassNotFoundException: org.json.JSONException
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:160)
	at com.android.tools.idea.rendering.RenderClassLoader.findClass(RenderClassLoader.java:54)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:90)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:193)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2673)
	at java.lang.Class.getConstructor0(Class.java:3077)
	at java.lang.Class.getConstructor(Class.java:1827)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:396)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:172)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:105)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$72(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by eseidelGoogle** [comment]
Makes sense.  I'm not surprised there is a little bit of editor tool integration we need to do for our android.View subclass.  Likely similar when using FlutterView in Xcode's InterfaceBuilder too.

**Comment by szakarias** [comment]
It's not as big a problem in Xcode since the InterfaceBuilder allows you to work with native components surrounding the Flutter view. In Android Studio the experience with the Layout Editor is quite bad since the exception keeps popping up with every change.

**Comment by zoechi** [comment]
Should this be moved to flutter/flutter-intellij?
