### ISSUE TITLE
As of a76c352d Flutter Gallery transitions test is failing

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#8532]
This started at a76c352d. It always fails at the "Colors" demo.

## Steps to Reproduce

Connect an Android device, then:

```
cd dev/devicelab
dart bin/run.dart -t flutter_gallery__transition_perf
```

## Logs

[Full log](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9hNzZjMzUyZDU3MmI4MzNhMDQwMWYyY2I1NzNjMGM4OWZjYjA0MWZhDAsSBFRhc2sYgICAgICAsAoM)

```
Testing "Tabs" demo
Success
Testing "Text fields" demo
Success
Testing "Tooltips" demo
Success
Testing "Colors" demo
00:57 [32m+0[0m[31m -1[0m: flutter gallery transitions all demos[0m
  DriverError: Error in Flutter application: Timeout while executing scrollIntoView: TimeoutException after 0:00:05.000000: Future not completed
  #0      FlutterDriverExtension.call (package:flutter_driver/src/extension.dart:130)
  
  #1      BindingBase.registerServiceExtension. (package:flutter/src/foundation/binding.dart:302)
  
  #2      _runExtension (dart:developer-patch/developer.dart:79)
  
  Original error: null
  Original stack trace:
  null
      
  package:flutter_driver/src/driver.dart 288:7   FlutterDriver._sendCommand
  package:flutter_driver/src/driver.dart 371:18  FlutterDriver.scrollIntoView
  test_driver/transitions_perf_test.dart 148:24  main...
  package:flutter_driver/src/driver.dart 452:17  FlutterDriver.traceAction
  test_driver/transitions_perf_test.dart 142:40  main..
  ===== asynchronous gap ===========================
  dart:async                                     _Completer.completeError
  package:flutter_driver/src/driver.dart 292:3   FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async                                     _asyncThenWrapperHelper
  package:flutter_driver/src/driver.dart         FlutterDriver._sendCommand
  package:flutter_driver/src/driver.dart 371:18  FlutterDriver.scrollIntoView
  ===== asynchronous gap ===========================
  dart:async                                     Future.Future.microtask
  package:flutter_driver/src/driver.dart         FlutterDriver.scrollIntoView
  test_driver/transitions_perf_test.dart 148:24  main...
  ===== asynchronous gap ===========================
  dart:async                                     _asyncThenWrapperHelper
  test_driver/transitions_perf_test.dart         main...
  package:flutter_driver/src/driver.dart 452:17  FlutterDriver.traceAction
  ===== asynchronous gap ===========================
  dart:async                                     _asyncThenWrapperHelper
  package:flutter_driver/src/driver.dart         FlutterDriver.traceAction
  test_driver/transitions_perf_test.dart 142:40  main..
  ===== asynchronous gap ===========================
  dart:async                                     Future.Future.microtask
  test_driver/transitions_perf_test.dart         main..
  package:test                                   Declarer.test..
```

**Comment by yjbanov** [comment]
The test in question lives here: https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/test_driver/transitions_perf_test.dart

**Comment by xster** [comment]
Checking
