### ISSUE TITLE
Android Studio (the doctor check crashed)

### ISSUE THREAD

**Issue by nonvtec4700** [flutter/flutter#85395]
## Steps to Reproduce

1. ...Run "flutter doctor" in Flutter

## Logs

<details>
<summary>Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = 'C:\Users\Chad Brezina\Documents\Android\Android Studio" .plugins' (OS
      Error: The filename, directory name, or volume label syntax is incorrect.
      , errno = 123)</summary>

```
```

>flutter doctor -v
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1052], locale en-US)
    • Flutter version 2.2.2 at C:\Flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = 'C:\Users\Chad Brezina\Documents\Android\Android Studio" .plugins' (OS
      Error: The filename, directory name, or volume label syntax is incorrect.
      , errno = 123)
    • #0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
      #1      ForwardingFileSystemEntity.existsSync
      (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
      #2      ErrorHandlingDirectory.existsSync.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:479:22)
      #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
      #4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:478:12)
      #5      AndroidStudio.pluginsPath (package:flutter_tools/src/android/android_studio.dart:186:52)
      #6      AndroidStudioValidator.validate (package:flutter_tools/src/android/android_studio_validator.dart:46:17)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #9      _rootRun (dart:async/zone.dart:1354:13)
      #10     _CustomZone.run (dart:async/zone.dart:1258:19)
      #11     _runZoned (dart:async/zone.dart:1789:10)
      #12     runZonedGuarded (dart:async/zone.dart:1777:12)
      #13     runZoned (dart:async/zone.dart:1708:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:199:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:303:47)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1192:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.59

! Doctor found issues in 1 category.

</details>

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/83195
