### ISSUE TITLE
Clipboard not works in another isolate on Windows/macOS desktop

### ISSUE THREAD

**Issue by TENX-S** [flutter/flutter#85424]
OS: Windows 10 19042.1055 / macOS 11.4 (Intel chip)
I'm trying to build the code below to flutter desktop. 
```dart
import 'dart:isolate';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  String content = 'waiting';

  late Isolate _notify;
  late ReceivePort _notifyPort;

  void _startNotify() async {
    _notifyPort = ReceivePort();
    _notify = await Isolate.spawn(_getClipboard, _notifyPort.sendPort);
    _notifyPort.listen(_handler);
  }

  static void _getClipboard(SendPort sendPort) async {
    ClipboardData? data = await Clipboard.getData(Clipboard.kTextPlain);
    sendPort.send(data!.text);
  }

  void _handler(dynamic clipContent) {
    setState(() {
      content = clipContent;
    });
  }

  void _stopNotify() {
    _notifyPort.close();
    _notify.kill(priority: Isolate.immediate);
  }

  @override
  void initState() {
    super.initState();
    _startNotify();
  }

  @override
  void dispose() {
    super.dispose();
    _stopNotify();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text(content),
    );
  }
}
```
Clipboard works perfectly fine on the main isolate, but I need to poll the clipboard regularly. I put this process into another isolates, and the system clipboard is not empty, but the data I get is `null`, that's the problem. 

Output:
```shell
[ERROR:flutter/runtime/dart_isolate.cc(1137)] Unhandled exception:
Null check operator used on a null value
#0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
#2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:461:18)
#3      Clipboard.getData (package:flutter/src/services/clipboard.dart:54:72)
#4      _HomePageState._getClipboard (package:paste_demo/main.dart:36:43)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

`flutter doctor`:
```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1055], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.2)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code, 64-bit edition (version 1.57.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by TENX-S** [comment]
Maybe related to [#13973](https://github.com/flutter/flutter/issues/13937)
