### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for E:\development\AndroidProjects\y-merchants-flutter-module-2.0\.fvm\flutter_sdk\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.

### ISSUE THREAD

**Issue by Terran-Marine** [flutter/flutter#85426]
## Command
```
flutter --quiet assemble --depfile E:\development\AndroidProjects\y-merchants-flutter-module-2.0\.android\Flutter\build\intermediates\flutter\release/flutter_build.d --output E:\development\AndroidProjects\y-merchants-flutter-module-2.0\.android\Flutter\build\intermediates\flutter\release -dTargetFile=lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true android_aot_bundle_release_android-arm android_aot_bundle_release_android-arm64 android_aot_bundle_release_android-x64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for E:\development\AndroidProjects\y-merchants-flutter-module-2.0\.fvm\flutter_sdk\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:232:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#14     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#15     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#16     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
```
```
[✓] Flutter (Channel unknown, 2.0.5, on Microsoft Windows [Version 10.0.19043.1055], locale zh-CN)
    • Flutter version 2.0.5 at E:\development\AndroidProjects\y-merchants-flutter-module-2.0\.fvm\flutter_sdk
    • Framework revision adc687823a (2 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Edge (web) • edge • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.flutter_module
**iOS bundle identifier**: com.example.flutterModule
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe
### Plugins
fluttertoast-8.0.7
loading_indicator_view-1.1.0
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
url_launcher-6.0.7
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.1
url_launcher_windows-2.0.0

**Comment by darshankawar** [comment]
@Terran-Marine 
Check if `bin\cache\artifacts\engine\android-arm-release\windows-x64\` path has `gen_snapshot.exe file`. It may be possible that it could have been deleted by security software by accident. 


Also, a similar issue was fixed, #68475 few months ago. So you should upgrade your version to get latest fixes.

I am going ahead and closing this as already fixed. Solution is to upgrade version (to latest stable or master). If after upgrading, you still see the same issue, write in comments and I'll reopen it.
Thanks.
