### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'printTrace' was called on null.Receiver: nullTried calling: printTrace

### ISSUE THREAD

**Issue by bagedevimo** [flutter/flutter#85420]
## Command
```
flutter driver --driver=test_driver/integration_test.dart --target=integration_test/end_to_end_test.dart --use-existing-app http://127.0.0.1:53911/uLA7GqY35do=/
```

## Steps to Reproduce
1. Run flutter driver on an integration_test, with `--keep-app-running`
2. Try run the app again using the provided URL from step 1.

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'printTrace' was called on null.
Receiver: null
Tried calling: printTrace
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      _defaultOpenChannel.handleError (package:flutter_tools/src/vmservice.dart:114:54)
#2      _defaultOpenChannel.handleError (package:flutter_tools/src/vmservice.dart:113:27)
#3      _defaultOpenChannel (package:flutter_tools/src/vmservice.dart:155:24)
<asynchronous suspension>
#4      createVmServiceDelegate (package:flutter_tools/src/vmservice.dart:334:32)
<asynchronous suspension>
#5      _connect (package:flutter_tools/src/vmservice.dart:357:48)
<asynchronous suspension>
#6      FlutterDriverService.reuseApplication (package:flutter_tools/src/drive/drive_service.dart:221:18)
<asynchronous suspension>
#7      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:253:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale en-NZ)
    • Flutter version 2.2.2 at /usr/local/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/benanderson/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio 4.2 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.5+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
flutter_secure_storage-4.0.0
integration_test
location
location_web-3.0.0
package_info-2.0.0
package_info_plus-1.0.0
package_info_plus_macos-1.0.0
package_info_plus_web-1.0.0
path_provider_linux-2.0.0
path_provider_windows-2.0.0
plain_notification_token-1e9dc89f04d51e1feec6834aada8fa1049e5c0db
sentry_flutter-5.0.0
shared_preferences-2.0.3
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
url_launcher-6.0.2
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0

**Comment by raywhiteside** [comment]
Same issue

**Comment by danagbemava-nc** [comment]
The tool has since been migrated to null safety so it is likely that this issue has been fixed. If anyone still experiences this crash on the latest version of flutter stable, kindly file a new issue and provide all the relevant information. 

Thank you
