### ISSUE TITLE
[tool_crash] SocketException: Read failed, OS Error: Input/output error, errno = 5

### ISSUE THREAD

**Issue by l1Dan** [flutter/flutter#85447]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Read failed, OS Error: Input/output error, errno = 5
```
#0      _NativeSocket.read (dart:io-patch/socket_patch.dart:1054:33)
#1      _RawSocket.read (dart:io-patch/socket_patch.dart:1746:26)
#2      _Socket._onData (dart:io-patch/socket_patch.dart:2159:28)
#3      _rootRunUnary (dart:async/zone.dart:1370:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#9      _StreamController._add (dart:async/stream_controller.dart:607:7)
#10     _StreamController.add (dart:async/stream_controller.dart:554:5)
#11     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-CN)
    • Flutter version 2.2.2 at /Users/lidan/Sources/flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 16510F2A-E630-4A16-BE26-59F7C32E6F97 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.mall
**iOS bundle identifier**: com.example.mall
**Creation channel**: stable
**Creation framework version**: d79295af24c3ed621c33713ecda14ad196fd9c31

**Comment by darshankawar** [comment]
A bit similar to https://github.com/flutter/flutter/issues/74846, but the log from above is different. Labeling it accordingly.
