### ISSUE TITLE
[tool_crash] YamlException

### ISSUE THREAD

**Issue by Tsengel1129** [flutter/flutter#85441]
## Command
```
flutter pub upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
YamlException
```
#0      Scanner._fetchValue (package:yaml/src/scanner.dart:723:9)
#1      Scanner._fetchNextToken (package:yaml/src/scanner.dart:465:11)
#2      Scanner._fetchMoreTokens (package:yaml/src/scanner.dart:347:7)
#3      Scanner.peek (package:yaml/src/scanner.dart:325:27)
#4      Parser._parseBlockMappingKey (package:yaml/src/parser.dart:421:26)
#5      Parser._stateMachine (package:yaml/src/parser.dart:95:16)
#6      Parser.parse (package:yaml/src/parser.dart:56:19)
#7      Loader._loadMapping (package:yaml/src/loader.dart:172:23)
#8      Loader._loadNode (package:yaml/src/loader.dart:89:16)
#9      Loader._loadDocument (package:yaml/src/loader.dart:65:20)
#10     Loader.load (package:yaml/src/loader.dart:57:20)
#11     loadYamlDocument (package:yaml/yaml.dart:69:25)
#12     loadYamlNode (package:yaml/yaml.dart:54:5)
#13     generateLocalizationsSyntheticPackage (package:flutter_tools/src/dart/generate_synthetic_packages.dart:33:29)
#14     PackagesInteractiveGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:331:13)
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1192:12)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.59

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
flutter_plugin_android_lifecycle-1.0.11
image_picker-0.6.7+22
shared_preferences-0.5.7+3
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by jonahwilliams** [comment]
You have to actually fill out the template to report a bug
