### ISSUE TITLE
[inspector] callback for "ext.flutter.inspector.getDetailsSubtree": type 'Null' is not a subtype of type 'String' of 'function result'

### ISSUE THREAD

**Issue by woinbo** [flutter/flutter#85467]
```terminal
════════ Exception caught by Flutter framework ═════════════════════════════════
The following _TypeError was thrown during a service extension callback for "ext.flutter.inspector.getDetailsSubtree":
type 'Null' is not a subtype of type 'String' of 'function result'

When the exception was thrown, this was the stack
#0      _Location.toJsonMap (package:flutter/src/widgets/widget_inspector.dart)
package:flutter/…/widgets/widget_inspector.dart:1
#1      _Location.toJsonMap.<anonymous closure>
package:flutter/…/widgets/widget_inspector.dart:2853
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════
type 'Null' is not a subtype of type 'String' of 'function result'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════
type 'Null' is not a subtype of type 'String' of 'function result'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════
type 'Null' is not a subtype of type 'String' of 'function result'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════
type 'Null' is not a subtype of type 'String' of 'function result'
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by Flutter framework ═════════════════════════════════```

**Comment by TahaTesser** [comment]
HI @woinbo 
Can you please provide your `flutter doctor -v` & a complete reproducible steps, IDE you're using for widget inspector
Thank you

**Comment by woinbo** [comment]
- 1: flutter doctor -v
```terminal
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ankit\AppData\Local\Android\Sdk\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\ankit\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Java\jdk-11.0.11\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\ankit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • CPH1823 (mobile) • BI5SZTPRHYW8LFU8 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 91.0.864.59

! Doctor found issues in 1 category.```

I am using VS-CODE.
No specific reproducible steps since it occurs any time while working with an inspector. Like right now I was working on my companies project and this error occurred again.

**Comment by TahaTesser** [comment]
Related to https://github.com/flutter/flutter/issues/81587

**Comment by jacob314** [comment]
This was fixed.
