### ISSUE TITLE
I'm trying to fetch and play my backend videos through the video_player plugin, but it's throwing errors loading the URL:  Link end with .mp4  

### ISSUE THREAD

**Issue by Aryankaushik2312** [flutter/flutter#85513]
<details> 
<summary>logs</summary> 
	
```console
E/ExoPlayerImplInternal(10564): Playback error E/ExoPlayerImplInternal(10564):
com.google.android.exoplayer2.ExoPlaybackException: Source error E/ExoPlayerImplInternal(10564): at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(10564): at android.os.Handler.dispatchMessage(Handler.java:102) E/ExoPlayerImplInternal(10564): at android.os.Looper.loop(Looper.java:223) E/ExoPlayerImplInternal(10564): at android.os.HandlerThread.run(HandlerThread.java:67) E/ExoPlayerImplInternal(10564): Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FragmentedMp4Extractor, Mp4Extractor, FlvExtractor, FlacExtractor, WavExtractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream. E/ExoPlayerImplInternal(10564): at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(10564): at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1024)
E/ExoPlayerImplInternal(10564): at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal(10564): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(10564): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
E/ExoPlayerImplInternal(10564): at java.lang.Thread.run(Thread.java:923)
```

</details>

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
