### ISSUE TITLE
[tool_crash] sdkmanager tool was found, but failed to run  AND ProcessException: The parameter is incorrect OS error code: 87

### ISSUE THREAD

**Issue by MassimoVlacancich** [flutter/flutter#85552]
Hi flutter team,

I am having some issues getting flutter to run nearly any command, all of them quit with error `ProcessException: The parameter is incorrect.`

The issue started when I upgraded android studio, running `flutter emulators` would constantly fail, and none of my flutter tests would start.   

So here is what I have tried:

1. I cleaned everything up:
   - uninstalled: `flutter`, `java`, `androidStudio`
   - removed all SDKs and JDKs from my machine
   - removed all environment variables
2. I re-installed android studio and the latest Android SDK and command line tools
3. I re-installed flutter
4. I added `flutter` env variables and checked that Android studio correctly picked up the ones it needed.
5. (verified that AndroidStudio could run a simple app)

I have attempted various combinations of the above:
 - I know flutter is meant to work with Java8, so I installed oracle java8 jdk, made sure AndroidStudio was using it and installed `flutter` again, but I encountered the same error.
 - I have seen a few people run flutter with openJDK11, so I tried that too (of course by removing java8 first and cleaning all env variables), no success
 - I have tried to use older and even obsolete versions of the Android cmd tools, no success
 - I tried to use AndroidStudio 3.6, no success
 - I tried older SDKs (28.0.1) but no success either.

I no longer know which route to take, I have copied below all logs from the commands run; I really need to deliver some work so I would really appreciate your help figuring this one out.

### Commands run
```
flutter doctor --android-licenses
flutter emulators
```

####  --android-licenses command
*Command*: `flutter --android-licenses --verbose`
```
Android sdkmanager tool was found, but failed to run (C:\Users\Massimo\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat): "ProcessException: The parameter is incorrect.

  Command: C:\Users\Massimo\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat --licenses".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:454:7)
<asynchronous suspension>
#2      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:26)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

#### emulators command
*Command*: `flutter emulators`
```
ProcessException: The parameter is incorrect.
 Command: C:\Users\Massimo\AppData\Local\Android\sdk\emulator\emulator.exe, OS error code: 87

#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:565:18)
#3      Process.run (dart:io-patch/process_patch.dart:47:12)
#4      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:74:22)
#5      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:642:24)
#6      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#7      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:641:12)
#8      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:267:59)
#9      AndroidEmulators._getEmulatorAvds (package:flutter_tools/src/android/android_emulator.dart:65:56)
#10     AndroidEmulators.emulators (package:flutter_tools/src/android/android_emulator.dart:56:43)
#11     EmulatorManager.getAllAvailableEmulators.<anonymous closure> (package:flutter_tools/src/emulator.dart:82:41)
#12     EmulatorManager.getAllAvailableEmulators.<anonymous closure> (package:flutter_tools/src/emulator.dart:81:67)
#13     Future.forEach.<anonymous closure> (dart:async/future.dart:495:26)
#14     Future.doWhile.<anonymous closure> (dart:async/future.dart:535:26)
#15     _rootRunUnary (dart:async/zone.dart:1362:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#18     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1207:26)
#19     Future.doWhile (dart:async/future.dart:551:18)
#20     Future.forEach (dart:async/future.dart:493:12)
#21     EmulatorManager.getAllAvailableEmulators (package:flutter_tools/src/emulator.dart:81:18)
#22     EmulatorsCommand._listEmulators (package:flutter_tools/src/commands/emulators.dart:91:33)
#23     EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:54:13)
#24     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1192:12)
```

#### Flutter doctor output

This is the output of my last set up:
 - cleaned up as described above
 - downloaded AndroidStudio 4.2
 - did NOT add any java JDKs apart from the one embedded with AndroidStudio
 - downloaded the latest version of `flutter`

```
[✓] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.18363.1556], locale en-GB)
    • Flutter version 2.2.2 at C:\Users\Massimo\Documents\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Massimo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Massimo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 1 category.

```

Thanks in advance for your help!

**Comment by TahaTesser** [comment]
Hi @MassimoVlacancich 
This looks like some sort of edge case issue, the path looks right but it throws `code: 87` which is cod for incorrect path 

Previously reported issues 
https://github.com/flutter/flutter/issues/34016
https://github.com/flutter/flutter/issues/43443

**Comment by MassimoVlacancich** [comment]
HI @TahaTesser , thanks for getting back to me.
Is there something I can do on my side to make this work?
I currently cannot do any Flutter dev on my main machine due to this issue

**Comment by asashour** [comment]
What is the output of running on the `cmd`

    C:\Users\Massimo\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat  --licenses

**Comment by MassimoVlacancich** [comment]
Interestingly and weirdly this fixed itself after coming back from my holiday... not sure why or how, cannot replicate the issue now
this ticket can be closed

**Comment by TahaTesser** [comment]
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
