### ISSUE TITLE
cannot using pytorch_android on release mode

### ISSUE THREAD

**Issue by guchengxi1994** [flutter/flutter#85744]
I was using flutter plus a custom gan model to do some tests, it worked on debug mode but failed on release mode.

bug is

`E/AndroidRuntime(24185): FATAL EXCEPTION: main E/AndroidRuntime(24185): Process: com.example.flutter_access_android, PID: 24185 E/AndroidRuntime(24185): java.lang.NoSuchMethodError: no static or non-static method "Lorg/pytorch/PyTorchAndroid;.nativeSetNumThreads(I)V" E/AndroidRuntime(24185): at java.lang.Runtime.nativeLoad(Native Method) E/AndroidRuntime(24185): at java.lang.Runtime.doLoad(Runtime.java:447) E/AndroidRuntime(24185): at java.lang.Runtime.loadLibrary(Runtime.java:382) E/AndroidRuntime(24185): at java.lang.System.loadLibrary(System.java:1086) E/AndroidRuntime(24185): at c.a.a.a.c.a() E/AndroidRuntime(24185): at c.a.a.a.a.c() E/AndroidRuntime(24185): at org.pytorch.PyTorchAndroid.<clinit>() E/AndroidRuntime(24185): at com.example.flutter_access_android.MainActivity.M() E/AndroidRuntime(24185): at com.example.flutter_access_android.MainActivity.O() E/AndroidRuntime(24185): at com.example.flutter_access_android.MainActivity.P() E/AndroidRuntime(24185): at com.example.flutter_access_android.a.a() E/AndroidRuntime(24185): at d.a.c.a.i$a.a() E/AndroidRuntime(24185): at io.flutter.embedding.engine.e.b.c() E/AndroidRuntime(24185): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage() E/AndroidRuntime(24185): at android.os.MessageQueue.nativePollOnce(Native Method) E/AndroidRuntime(24185): at android.os.MessageQueue.next(MessageQueue.java:335) E/AndroidRuntime(24185): at android.os.Looper.loop(Looper.java:166) E/AndroidRuntime(24185): at android.app.ActivityThread.main(ActivityThread.java:5982) E/AndroidRuntime(24185): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime(24185): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852) E/AndroidRuntime(24185): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)`

![image](https://user-images.githubusercontent.com/33513462/124206850-be18ec80-db16-11eb-9b09-034c329254da.png)

It seems some files are not available.

I used pytorch_android:1.7.0 and pytorch_android:1.9.0 , but both of them failed.

i tried it without flutter, it worked good, so how can i build a flutter apk with pytorch_android?

Is there any problems when i use flutter to build a pytorth_android apk?

**Comment by guchengxi1994** [comment]
my code can be found here.

[https://github.com/guchengxi1994/pytorch-mobile-trial/tree/main/flutter_access_android](url)
