### ISSUE TITLE
Canvas kit throwing errors when trying to paste into text field

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#85740]
```
NoSuchMethodError: method not found: 'value' on null
main.dart.js:23215     at Object.toWireType (http://127.0.0.1:9101/assets/canvaskit/profiling/canvaskit.js:9:156828)
main.dart.js:23215     at Paragraph$_getRectsForRange [as _getRectsForRange] (eval at new_ (http://127.0.0.1:9101/assets/canvaskit/profiling/canvaskit.js:9:147774), <anonymous>:10:26)
main.dart.js:23215     at Paragraph.CanvasKit.Paragraph.getRectsForRange (http://127.0.0.1:9101/assets/canvaskit/profiling/canvaskit.js:9:50941)
main.dart.js:23215     at JavaScriptObject.getRectsForRange$4 (http://127.0.0.1:9101/main.dart.js:84184:23)
main.dart.js:23215     at Object.getRectsForRange$4$x (http://127.0.0.1:9101/main.dart.js:24430:43)
main.dart.js:23215     at CkParagraph.getBoxesForRange$4$boxHeightStyle$boxWidthStyle (http://127.0.0.1:9101/main.dart.js:67709:42)
main.dart.js:23215     at CkParagraph.getBoxesForRange$3$boxHeightStyle (http://127.0.0.1:9101/main.dart.js:67712:19)
main.dart.js:23215     at TextPainter._getRectFromDownstream$2 (http://127.0.0.1:9101/main.dart.js:180461:48)
main.dart.js:23215     at TextPainter._computeCaretMetrics$2 (http://127.0.0.1:9101/main.dart.js:180536:24)
main.dart.js:23215     at _FloatingCursorPainter.paint$3 (http://127.0.0.1:9101/main.dart.js:184070:12)
```

@hterkelsen 
CC @jacob314 

This bug is seen on the landing screen for DevTools, so would be best to fix ASAP. When you paste into the connect dialog text box, this error is thrown and the text doesn't show up in the text field.

**Comment by TahaTesser** [comment]
Hi @kenzieschmoll 
Running on the master, access http://localhost:9100/#/? and pasted some text, no such error in the chrome console

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/taha/Code/flutter_stable
    • Framework revision f4abaa0735 (19 hours ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-1ubuntu1
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

</details>

**Comment by devoncarew** [comment]
@TahaTesser - note that DevTools is using canvaskit, so in order to repro you may have to set up your flutter web app to use that.

**Comment by TahaTesser** [comment]
@devoncarew 
Thank you, my initial thought so same but I don't see any error in the flutter logs or chrome log so I thought it must be in devtools only 

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
``` 

</details>


### Preview

![Untitled](https://user-images.githubusercontent.com/48603081/124301589-b5e99d00-db68-11eb-9025-67bce321c5bc.png)


### Logs
<details> 
<summary>logs</summary> 
	
```console
taha@pop-os:~/StudioProjects/master_flutter$ fmrwc
[  +65 ms] executing: uname -m
[  +34 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +9 ms] executing: [/home/taha/Code/flutter_master/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] dbd3f0e0d8bd3f11bd029fc471cd351fca2a65cf
[   +1 ms] executing: [/home/taha/Code/flutter_master/] git tag --points-at dbd3f0e0d8bd3f11bd029fc471cd351fca2a65cf
[  +19 ms] Exit code 0 from: git tag --points-at dbd3f0e0d8bd3f11bd029fc471cd351fca2a65cf
[   +2 ms] executing: [/home/taha/Code/flutter_master/] git describe --match *.*.* --long --tags dbd3f0e0d8bd3f11bd029fc471cd351fca2a65cf
[  +40 ms] Exit code 0 from: git describe --match *.*.* --long --tags dbd3f0e0d8bd3f11bd029fc471cd351fca2a65cf
[        ] 2.3.0-16.0.pre-632-gdbd3f0e0d8
[   +6 ms] executing: [/home/taha/Code/flutter_master/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/taha/Code/flutter_master/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +96 ms] executing: [/home/taha/Code/flutter_master/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +99 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +102 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +89 ms] Skipping pub get: version match.
[ +148 ms] Generating /home/taha/StudioProjects/master_flutter/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +180 ms] Launching lib/main.dart on Chrome in debug mode...
[ +115 ms] Updating assets
[  +96 ms] Waiting for connection from debug service on Chrome...
[ +124 ms] <- reset
[   +7 ms] /home/taha/Code/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/taha/Code/flutter_master/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/taha/Code/flutter_master/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true --output-dill /tmp/flutter_tools.MXEPDK/flutter_tool.LJMNAJ/app.dill --libraries-spec
file:///home/taha/Code/flutter_master/bin/cache/flutter_web_sdk/libraries.json --packages
/home/taha/StudioProjects/master_flutter/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root /tmp/flutter_tools.MXEPDK/flutter_tools.ERZEUX --filesystem-scheme org-dartlang-app --initialize-from-dill
build/53e88b6d212d259e8bb56a28570ef36b.cache.dill.track.dill --platform
file:///home/taha/Code/flutter_master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +15 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+26101 ms] Waiting for connection from debug service on Chrome... (completed in 26.2s)
[   +1 ms] Synced 26.0MB.
[        ] <- accept
[        ] Caching compiled dill
[ +148 ms] Using Google Chrome 91.0.4472.114 

[  +64 ms] executing: uname -m
[   +6 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +252 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:35831/devtools/browser/e144522c-f6d1-40fd-bc53-a77de5832698
[ +660 ms] DwdsInjector: Received request for entrypoint at http://localhost:34563/main_module.bootstrap.js
[  +20 ms] MetadataProvider: Loading debug metadata...
[  +91 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +20 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:34563/main_module.bootstrap.js
[+2766 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +98 ms] DevHandler: Debug service listening on ws://127.0.0.1:39319/k_vZNBMOAjU=/ws

[  +40 ms] This app is linked to the debug service: ws://127.0.0.1:39319/k_vZNBMOAjU=/ws
[  +18 ms] Debug service listening on ws://127.0.0.1:39319/k_vZNBMOAjU=/ws
[        ] 💪 Running with sound null safety 💪
[   +8 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:39319/k_vZNBMOAjU=
[ +556 ms] DevTools activation throttled until 2021-07-03 02:25:55.392543.
[+5750 ms] The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:39319/k_vZNBMOAjU=
```

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.632, on Pop!_OS 21.04 5.11.0-7620-generic, locale en_US.UTF-8)
    • Flutter version 2.3.0-17.0.pre.632 at /home/taha/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dbd3f0e0d8 (6 hours ago), 2021-07-02 06:06:03 -0400
    • Engine revision 314cf7a4f2
    • Dart version 2.14.0 (build 2.14.0-269.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/taha/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/taha/Code/SDK
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-1ubuntu1
    • cmake version 3.18.4
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 21.04 5.11.0-7620-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by kenzieschmoll** [comment]
Is that a ddc build? I see the debug banner. This was with a dart2js build with canvas kit enabled. Steps to repro with Devtools:

1. From the main devtools directory run ./tool/publish.sh (note that you may have to tweak the version here https://github.com/flutter/devtools/blob/master/tool/build_release.sh#L17  to match the version in in the engine for your checkout is Flutter - see the comment at that code link)
2. Once that completes run dart packages/devtools/bin/devtools.dart and try to paste something into the connect text field for the DevTools instance that launches

**Comment by yjbanov** [comment]
Following the instructions from https://github.com/flutter/flutter/issues/85740#issuecomment-873121677 I get this error (on Windows and on macOS):

```
Unhandled exception:
Invalid argument(s): A directory corresponding to fileSystemPath "C:\code\flutter\devtools\packages\devtools\build" could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/external_handlers.dart:38:23)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:193:15)
<asynchronous suspension>
#3      serveDevToolsWithArgs (package:devtools_server/src/server.dart:70:10)
<asynchronous suspension>
```

**Comment by hterkelsen** [comment]
Hi, I'm unable to repro the bug on my machine (Mac OS, Chrome, Flutter master). I was able to build and run the devtools app using the steps provided `./tools/publish.sh` then `dart bin/devtools.dart` and I was able to paste a URL into the "Connect" text field with no messages in the Console and the devtools app working normally.

Is the problem still reproducible on your end? What OS and browser are you running on?

```
Flutter 2.5.0-2.0.pre.30 • channel master • git@github.com:hterkelsen/flutter.git
Framework • revision cc03623c1a (31 minutes ago) • 2021-07-27 16:19:04 -0400
Engine • revision e92c10d760
Tools • Dart 2.14.0 (build 2.14.0-356.0.dev
```
