### ISSUE TITLE
Web autofill throw exception

### ISSUE THREAD

**Issue by karabanovbs** [flutter/flutter#85807]
When I press autocomplete  dart throw this exception:

```console
errors.dart:187 Uncaught Error: Expected a value of type 'KeyboardEvent$', but got one of type 'Event$'
    at Object.throw_ [as throw] (errors.dart:236)
    at Object.castError (errors.dart:84)
    at Object.cast [as as] (operations.dart:442)
    at Function.as_C [as as] (classes.dart:635)
    at keyboard_binding.dart:135
    at keyboard_binding.dart:109
DartError @ errors.dart:187
throw_ @ errors.dart:236
castError @ errors.dart:84
cast @ operations.dart:442
as_C @ classes.dart:635
(anonymous) @ keyboard_binding.dart:135
(anonymous) @ keyboard_binding.dart:109
errors.dart:187 Uncaught Error: Expected a value of type 'KeyboardEvent$', but got one of type 'Event$'
    at Object.throw_ [as throw] (errors.dart:236)
    at Object.castError (errors.dart:84)
    at Object.cast [as as] (operations.dart:442)
    at Function.as_C [as as] (classes.dart:635)
    at keyboard_binding.dart:138
    at keyboard_binding.dart:109
DartError @ errors.dart:187
throw_ @ errors.dart:236
castError @ errors.dart:84
cast @ operations.dart:442
as_C @ classes.dart:635
(anonymous) @ keyboard_binding.dart:138
(anonymous) @ keyboard_binding.dart:109
```

https://user-images.githubusercontent.com/14288495/124334068-65e1f900-dbaf-11eb-9742-fde0f3d602f5.mov

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatelessWidget(),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        width: 100,
        child: TextFormField(
          autofillHints: [AutofillHints.telephoneNumber],
          keyboardType: TextInputType.phone,
          inputFormatters: [
            FilteringTextInputFormatter.digitsOnly,
          ],
        ),
      ),
    );
  }
}

```

## My env
```console
boriskarabanov@MacBook-Pro-Boris clubslane % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)
    ! Error: DNS s4502 is busy: Copying cache files from device. Xcode will continue when DNS s4502 is finished. (code -10)

• No issues found!

```

**Comment by karabanovbs** [comment]
Maybe this related to [this](https://github.com/dart-lang/sdk/issues/36488)

**Comment by TahaTesser** [comment]
Hi @karabanovbs 
I tried different computers, running your code sample, simply doesn't show autofill suggestion, in fact, I can't type anything in the field when running on chrome on macOS, Linux


<details> 
<summary>logs</summary> 
	
```console
ncaught (in promise) Error: LateInitializationError: Local 'command' has not been initialized.
    at Object.throw_ [as throw] (errors.dart:236)
    at command$35get (text_editing.dart:1542)
    at _engine.TextEditingChannel.new.handleTextInput (text_editing.dart:1614)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (platform_dispatcher.dart:431)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (platform_dispatcher.dart:258)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (binding.dart:259)
    at _DefaultBinaryMessenger.send (binding.dart:308)
    at OptionalMethodChannel._invokeMethod (platform_channel.dart:148)
    at _invokeMethod.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at OptionalMethodChannel.[_invokeMethod] (platform_channel.dart:146)
    at OptionalMethodChannel.[_invokeMethod] (platform_channel.dart:474)
    at OptionalMethodChannel.invokeMethod (platform_channel.dart:461)
    at invokeMethod.next (<anonymous>)
    at runBody (async_patch.dart:84)
    at Object._async [as async] (async_patch.dart:123)
    at OptionalMethodChannel.invokeMethod (platform_channel.dart:460)
    at text_input.TextInput.__.[_requestAutofill] (text_input.dart:1422)
    at text_input.TextInputConnection.__.requestAutofill (text_input.dart:968)
    at editable_text.EditableTextState.new.[_openInputConnection] (editable_text.dart:2058)
    at editable_text.EditableTextState.new.[_openOrCloseInputConnectionIfNeeded] (editable_text.dart:2086)
    at editable_text.EditableTextState.new.[_handleFocusChanged] (editable_text.dart:2408)
    at focus_manager.FocusNode.new.notifyListeners (change_notifier.dart:243)
    at focus_manager.FocusNode.new.[_notify] (focus_manager.dart:1052)
    at focus_manager.FocusManager.new.[_applyFocusChange] (focus_manager.dart:1800)
    at Object._microtaskLoop (schedule_microtask.dart:40)
    at _startMicrotaskLoop (schedule_microtask.dart:49)
    at async_patch.dart:166
```

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5268h darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios
      • iOS 12.5.3
    • macOS (desktop)        • macos                                    •
      darwin-x64     • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 91.0.4472.114
    ! Error: Taha’s iPhone is busy: Making Taha’s iPhone ready for development.
      Xcode will continue when Taha’s iPhone is finished. (code -10)

• No issues found!
```

</details>

Can you please `flutter  run -d chrome -v` logs running the code sample and focus the textfield

**Comment by karabanovbs** [comment]
Hi @TahaTesser.
Are you sure that chrome instance, that startup for debug, know about previous input data for use in autofill?
Try one or more times submit value for use in autofill in future.

Previously I don't see LateInitializationError, is it deferent issue or part of this, i don't know?

<details>
  <summary>logs</summary>
  
```console
[        ] Restarted application in 64ms.
[+3502 ms] Error: LateInitializationError: Local 'command' has not been initialized.
                        at Object.throw_ [as throw] (http://localhost:65463/dart_sdk.js:5041:11)
                        at command$35get (http://localhost:65463/dart_sdk.js:170859:41)
                        at _engine.TextEditingChannel.new.handleTextInput (http://localhost:65463/dart_sdk.js:170936:41)
                        at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:65463/dart_sdk.js:157234:39)
                        at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:65463/dart_sdk.js:157101:33)
                        at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:65463/packages/flutter/src/services/system_channels.dart.lib.js:2110:38)
                        at _DefaultBinaryMessenger.send (http://localhost:65463/packages/flutter/src/services/system_channels.dart.lib.js:2152:40)
                        at OptionalMethodChannel._invokeMethod (http://localhost:65463/packages/flutter/src/services/system_channels.dart.lib.js:938:50)
                        at _invokeMethod.next (<anonymous>)
                        at runBody (http://localhost:65463/dart_sdk.js:37422:34)
                        at Object._async [as async] (http://localhost:65463/dart_sdk.js:37453:7)
                        at OptionalMethodChannel.[_invokeMethod] (http://localhost:65463/packages/flutter/src/services/system_channels.dart.lib.js:936:20)
                        at OptionalMethodChannel.[_invokeMethod] (http://localhost:65463/packages/flutter/src/services/system_channels.dart.lib.js:1059:34)
                        at OptionalMethodChannel.invokeMethod (http://localhost:65463/packages/flutter/src/services/system_channels.dart.lib.js:1039:36)
                        at invokeMethod.next (<anonymous>)
                        at runBody (http://localhost:65463/dart_sdk.js:37422:34)
                        at Object._async [as async] (http://localhost:65463/dart_sdk.js:37453:7)
                        at OptionalMethodChannel.invokeMethod (http://localhost:65463/packages/flutter/src/services/system_channels.dart.lib.js:1038:20)
                        at text_input.TextInput.__.[_requestAutofill] (http://localhost:65463/packages/flutter/src/services/text_input.dart.lib.js:1315:22)
                        at text_input.TextInputConnection.__.requestAutofill (http://localhost:65463/packages/flutter/src/services/text_input.dart.lib.js:1060:55)
                        at editable_text.EditableTextState.new.[_openInputConnection] (http://localhost:65463/packages/flutter/src/widgets/widget_span.dart.lib.js:45128:56)
                        at editable_text.EditableTextState.new.[_openOrCloseInputConnectionIfNeeded] (http://localhost:65463/packages/flutter/src/widgets/widget_span.dart.lib.js:45150:37)
                        at editable_text.EditableTextState.new.[_handleFocusChanged] (http://localhost:65463/packages/flutter/src/widgets/widget_span.dart.lib.js:45358:50)
                        at focus_manager.FocusNode.new.notifyListeners (http://localhost:65463/packages/flutter/src/foundation/change_notifier.dart.lib.js:106:41)
                        at focus_manager.FocusNode.new.[_notify] (http://localhost:65463/packages/flutter/src/widgets/widget_span.dart.lib.js:48239:12)
                        at focus_manager.FocusManager.new.[_applyFocusChange] (http://localhost:65463/packages/flutter/src/widgets/widget_span.dart.lib.js:48969:26)
                        at Object._microtaskLoop (http://localhost:65463/dart_sdk.js:37526:13)
                        at _startMicrotaskLoop (http://localhost:65463/dart_sdk.js:37532:13)
                        at http://localhost:65463/dart_sdk.js:33303:9
[+3575 ms] Error: Expected a value of type 'KeyboardEvent$', but got one of type 'Event$'
                        at Object.throw_ [as throw] (http://localhost:65463/dart_sdk.js:5041:11)
                        at Object.castError (http://localhost:65463/dart_sdk.js:5014:15)
                        at Object.cast [as as] (http://localhost:65463/dart_sdk.js:5323:17)
                        at Function.as_C [as as] (http://localhost:65463/dart_sdk.js:4960:19)
                        at http://localhost:65463/dart_sdk.js:156312:149
                        at http://localhost:65463/dart_sdk.js:156291:18
[   +1 ms] Error: Expected a value of type 'KeyboardEvent$', but got one of type 'Event$'
               at Object.throw_ [as throw] (http://localhost:65463/dart_sdk.js:5041:11)
               at Object.castError (http://localhost:65463/dart_sdk.js:5014:15)
               at Object.cast [as as] (http://localhost:65463/dart_sdk.js:5323:17)
               at Function.as_C [as as] (http://localhost:65463/dart_sdk.js:4960:19)
               at http://localhost:65463/dart_sdk.js:156313:147
               at http://localhost:65463/dart_sdk.js:156291:18

```
</details>

<details>
  <summary>flutter doctor -v</summary>
  
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale ru-RU)
    • Flutter version 2.2.3 at /Users/boriskarabanov/dev/sdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/boriskarabanov/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/boriskarabanov/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/boriskarabanov/Library/Android/sdk
    • Java binary at: /Users/boriskarabanov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/boriskarabanov/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Users/boriskarabanov/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • DNS s4502 (mobile)     • 323c1501ac89e45a8a7d4f96378b819cc7ef3d5c • ios            • iOS 14.6
    • iPhone 12 Pro (mobile) • 6F881E3D-C0AC-46C6-A570-AD594DA69259     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 91.0.4472.114
    ! Error: DNS s4502 is busy: Copying cache files from device. Xcode will continue when DNS s4502 is finished. (code -10)

• No issues found!


```
</details>

**Comment by TahaTesser** [comment]
Hi @karabanovbs 
Previously I added autofill details in debug instance in the settings, no suggestions were provided and only `LateInitializationError` was thrown
Today I ran on using `flutter run -d web-server` and use regular chrome window, the suggestion is provided and I can reproduce `: Expected a value of type 'KeyboardEvent$', but got one of type 'Event$'` exception  on the latest `stable` channel 

However when I tried on the `beta`, there no errors in the console 

| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/124583347-9ea5fa80-de5b-11eb-8919-d611971352a7.png" height="450" />	|




<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.3.0-24.1.pre, on macOS 12.0 21A5268h darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-24.1.pre at /Users/tahatesser/Code/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 615957513e (11 days ago), 2021-06-25 09:24:44 -0700
    • Engine revision 9d517f475b
    • Dart version 2.14.0 (build 2.14.0-188.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>


 
 Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by karabanovbs** [comment]
Hi @TahaTesser, thanks you, on beta channel really no errors. Looks Good.

**Comment by TahaTesser** [comment]
Hi @karabanovbs 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
