### ISSUE TITLE
google_sign_in update for new plugin APIs

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#8581]
## Steps to Reproduce

1. Run google_sign_in example
2. boot up. 

1. First issue: In the GoogleSignIn, HostMessages is deprecated and replaced with PlatformMessages. 
2. If HostMessages is replaced with PlatformMessages, the Flutter sdk library has to be added to imports. 
3. Then boot up exception occurs. It looks like calling the wrapper method doesn't exist. 

## Logs
Starting up after the code after the change above. 

```
Launching lib/main.dart on Nexus 9 in debug mode...
Uninstalling old version...
E/flutter ( 6140): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 6140): NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 6140): Receiver: null
E/flutter ( 6140): Tried calling: []("isSuccess")
E/flutter ( 6140): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
E/flutter ( 6140): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
E/flutter ( 6140): #2      GoogleSignInResult.GoogleSignInResult._ (package:google_sign_in/google_sign_in.dart:32)
E/flutter ( 6140): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:44)
E/flutter ( 6140): <asynchronous suspension>
E/flutter ( 6140): #4      GoogleSignIn.signInSilently (package:google_sign_in/google_sign_in.dart:48)
E/flutter ( 6140): #5      SignInDemoState.initState (/Users/branflake2267/git/google_sign_in/example/lib/main.dart:32)
E/flutter ( 6140): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3018)
E/flutter ( 6140): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885)
E/flutter ( 6140): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276)
E/flutter ( 6140): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2102)
E/flutter ( 6140): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922)
E/flutter ( 6140): #11     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812)
E/flutter ( 6140): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890)
E/flutter ( 6140): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885)
E/flutter ( 6140): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276)
E/flutter ( 6140): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2102)
E/flutter ( 6140): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922)
E/flutter ( 6140): #17     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812)
E/flutter ( 6140): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890)
E/flutter ( 6140): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885)
E/flutter ( 6140): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276)
E/flutter ( 6140): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2102)
E/flutter ( 6140): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848)
E/flutter ( 6140): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276)
E/flutter ( 6140): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2102)
E/flutter ( 6140): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848)
E/flutter ( 6140): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276)
E/flutter ( 6140): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2102)
E/flutter ( 6140): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922)
E/flutter ( 6140): #29     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812)
E/flutter ( 6140): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890)
E/flutter ( 6140): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3025)
E/flutter ( 6140): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885)
E/flutter ( 6140): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276)
E/flutter ( 6140): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2102)
E/flutter ( 6140): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922)
E/flutter ( 6140): #36     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812)
E/flutter ( 6140): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890)
E/flutter ( 6140): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3025)
E/flutter ( 6140): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885)
E/flutter ( 6140): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276)
E/flutter ( 6140): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2102)
E/flutter ( 6140): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848)
E/flutter ( 6140): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276)
E/flutter ( 6140): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2102)
E/flutter ( 6140): #45     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848)
E/flutter ( 6140): #46     Element.

Restarted in 1272 ms.
Restart complete.
E/flutter ( 6140): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 6140): NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 6140): Receiver: null
E/flutter ( 6140): Tried calling: []("isSuccess")
E/flutter ( 6140): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
E/flutter ( 6140): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
E/flutter ( 6140): #2      GoogleSignInResult.GoogleSignInResult._ (package:google_sign_in/google_sign_in.dart:32:26)
E/flutter ( 6140): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:44:16)
E/flutter ( 6140): <asynchronous suspension>
E/flutter ( 6140): #4      GoogleSignIn.signInSilently (package:google_sign_in/google_sign_in.dart:48:57)
E/flutter ( 6140): #5      SignInDemoState.initState (/data/user/0/com.yourcompany.GoogleSignInExample/cache/examplelzbdna/example/lib/main.dart:32:18)
E/flutter ( 6140): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3018:14)
E/flutter ( 6140): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922:16)
E/flutter ( 6140): #11     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812:5)
E/flutter ( 6140): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890:5)
E/flutter ( 6140): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922:16)
E/flutter ( 6140): #17     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812:5)
E/flutter ( 6140): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890:5)
E/flutter ( 6140): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848:14)
E/flutter ( 6140): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848:14)
E/flutter ( 6140): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922:16)
E/flutter ( 6140): #29     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812:5)
E/flutter ( 6140): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890:5)
E/flutter ( 6140): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3025:22)
E/flutter ( 6140): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922:16)
E/flutter ( 6140): #36     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812:5)
E/flutter ( 6140): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890:5)
E/flutter ( 6140): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3025:22)
E/flutter ( 6140): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848:14)
E/flutter ( 6140): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #44     Element.updateChild (package:flutter/sr

Restarted in 1145 ms.
Restart complete.
E/flutter ( 6140): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 6140): NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 6140): Receiver: null
E/flutter ( 6140): Tried calling: []("isSuccess")
E/flutter ( 6140): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
E/flutter ( 6140): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
E/flutter ( 6140): #2      GoogleSignInResult.GoogleSignInResult._ (package:google_sign_in/google_sign_in.dart:32:26)
E/flutter ( 6140): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:44:16)
E/flutter ( 6140): <asynchronous suspension>
E/flutter ( 6140): #4      GoogleSignIn.signInSilently (package:google_sign_in/google_sign_in.dart:48:57)
E/flutter ( 6140): #5      SignInDemoState.initState (/data/user/0/com.yourcompany.GoogleSignInExample/cache/examplelzbdna/example/lib/main.dart:32:18)
E/flutter ( 6140): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3018:14)
E/flutter ( 6140): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922:16)
E/flutter ( 6140): #11     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812:5)
E/flutter ( 6140): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890:5)
E/flutter ( 6140): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922:16)
E/flutter ( 6140): #17     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812:5)
E/flutter ( 6140): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890:5)
E/flutter ( 6140): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848:14)
E/flutter ( 6140): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848:14)
E/flutter ( 6140): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922:16)
E/flutter ( 6140): #29     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812:5)
E/flutter ( 6140): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890:5)
E/flutter ( 6140): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3025:22)
E/flutter ( 6140): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2922:16)
E/flutter ( 6140): #36     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2812:5)
E/flutter ( 6140): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2890:5)
E/flutter ( 6140): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3025:22)
E/flutter ( 6140): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2885:5)
E/flutter ( 6140): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2102:12)
E/flutter ( 6140): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3848:14)
E/flutter ( 6140): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2276:14)
E/flutter ( 6140): #44     Element.updateChild (package:flutter/sr

```

## Flutter Doctor
// skipping

**Comment by eseidelGoogle** [comment]
@collinjackson

**Comment by collinjackson** [comment]
I am in the process of updating google_sign_in to use the new interop APIs. The APIs are still changing on iOS, but as soon as they land I'll update this plugin.
