### ISSUE TITLE
`Null check operator used on a null value` with PageView's controller

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#85867]
Facing this for few days now on the latest stable. Haven't found any existing issue so...

## Steps to Reproduce

1. Run the code below.

**Expected results:** No crash

**Actual results:** `Null check operator used on a null value`

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Page()));

class Page extends StatefulWidget {
  @override
  _BankAppState createState() => _BankAppState();
}

class _BankAppState extends State<Page> {
  late PageController _pageController = PageController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView.builder(
        itemCount: 4,
        controller: _pageController,
        itemBuilder: (context, index) {
          // Calling this cause the issue.
          debugPrint(_pageController.page.toString());
          return Container(color: Colors.primaries[index]);
        },
      ),
    );
  }
}
```

<details>
  <summary>Logs</summary>

```bash
Performing hot restart...
Syncing files to device iPhone 12 Pro Max...
Restarted application in 306ms.

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      ScrollPosition.minScrollExtent (package:flutter/src/widgets/scroll_position.dart:136:49)
#1      _PagePosition.page (package:flutter/src/widgets/page_view.dart:388:22)
#2      PageController.page (package:flutter/src/widgets/page_view.dart:181:21)
#3      _BankAppState.build.<anonymous closure> (package:flutter_challenges/banking_app.dart:69:38)
#4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
...
====================================================================================================
flutter: 0.0

```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-AO)
    • Flutter version 2.2.3 at /Users/pedromassango/dev/sdk/flutter_stable
    • Framework revision f4abaa0735 (3 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

```

</details>

**Comment by darshankawar** [comment]
@pedromassango Hi,
Any reason you are using `debugPrint(_pageController.page.toString());` instead of `debugPrint(_pageController.toString());` ?
Using the latter, it works and prints properly as below:

```
flutter: PageController#88bfb(one client, offset 0.0)
flutter: PageController#88bfb(one client, offset 32.0)
flutter: PageController#88bfb(one client, offset 445.8)
flutter: PageController#88bfb(one client, offset 857.2)
```

**Comment by pedromassango** [comment]
> Any reason you are using `debugPrint(_pageController.page.toString());` instead of `debugPrint(_pageController.toString());` ?

No really. However, the point it that this code throws an exception.

You can replace that with: `_pageController.page!.toDouble()` which is what I was trying to do.

On a side note: this code still crashes even if you define the `initialPage` in the controller.

**Comment by darshankawar** [comment]
Thanks for the details.
```

Performing hot restart...
Syncing files to device iPhone 12 Pro Max...
Restarted application in 418ms.

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      ScrollPosition.minScrollExtent (package:flutter/src/widgets/scroll_position.dart:136:49)
#1      _PagePosition.page (package:flutter/src/widgets/page_view.dart:388:22)
#2      PageController.page (package:flutter/src/widgets/page_view.dart:181:21)
#3      _BankAppState.build.<anonymous closure> (package:macbug/main.dart:21:38)
#4      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455:22)
...
====================================================================================================
flutter: 0.0
```

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by ominibyte** [comment]
This error is not just particular to PageView. I'm using `ListWheelScrollView.useDelegate` with `FixedExtentScrollPhysics` and  `FixedExtentScrollController` and I have the same issue.

Seems like a few null checks needs to be added.

**Comment by Levi-Lesches** [comment]
Related to #60578 (not quite a duplicate since that was initially about something else, but now they're the same).

**Comment by DieGlueckswurst** [comment]
really annyoing issue. Wish Flutter would update this! Is there ay workaround for this at the moment? @Levi-Lesches

**Comment by Levi-Lesches** [comment]
There are some suggested workarounds in the above issue: 

> The issue is due to the widget having no size. (loading a Network images for example). A placeolder with a size should avoid this issue.

> FYI, I found a workaround: Use a `FutureBuilder`. You can wrap your widget into it and it will show without the exception.
You might consider using a `SynchronousFuture` to make it not blink.

**Comment by DieGlueckswurst** [comment]
@Levi-Lesches but what exactly should I put inside the FutureBuilder?

**Comment by Levi-Lesches** [comment]
Seems like you put the Image.network in there, with a useless future that completes immediately, like `Future.value(0)`

**Comment by pedromassango** [comment]
Finally found a workaround for this bug: Make sure you check for the content dimensions before trying to access a content-related property.

```dart
    if (!_scrollController.position.hasContentDimensions) {
      return;
    }
    // It is now safe to use anything related to position.
    final maxScrollExtent = _scrollController.position.maxScrollExtent;

```

**Comment by markusaksli-nc** [comment]
This now throws an assertion that explains this so closing this as fixed.

> Page value is only available after content dimensions are established.
