### ISSUE TITLE
Flutter : Build failed on linux from last two releases on DEV channel.

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#85889]
I am facing build failed issue from last two releases and here are the details.

flutter doctor -v

```
[✓] Flutter (Channel dev, 2.4.0-0.0.pre, on Ubuntu 18.04.5 LTS 5.4.0-62-generic, locale en_GB.UTF-8)
    • Flutter version 2.4.0-0.0.pre at /home/ravi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96bbcd006f (5 days ago), 2021-06-30 03:43:41 -0400
    • Engine revision c633b2a6a0
    • Dart version 2.14.0 (build 2.14.0-258.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 18.04.5 LTS 5.4.0-62-generic
```

Error Logs : 

```
[ +174 ms] [  +31 ms] /home/ravi/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/ravi/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/ravi/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --packages /home/ravi/unoplayer/.dart_tool/package_config.json
--output-dill /home/ravi/unoplayer/.dart_tool/flutter_build/c1dfb8ca6bad497237f68ada164d9a47/app.dill --depfile
/home/ravi/unoplayer/.dart_tool/flutter_build/c1dfb8ca6bad497237f68ada164d9a47/kernel_snapshot.d package:signageplayer/main.dart
[   +1 ms] [+11596 ms] ../flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:100:17: Error: The method
'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
[   +2 ms] [   +2 ms]  - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart'
('../flutter/packages/flutter/lib/src/services/platform_channel.dart').
[        ] [        ] Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
[        ] [        ]         channel.setMockMessageHandler(null);
[        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^
[        ] [   +2 ms] ../flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:102:17: Error: The method
'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
[        ] [        ]  - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart'
('../flutter/packages/flutter/lib/src/services/platform_channel.dart').
[        ] [        ] Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
[        ] [        ]         channel.setMockMessageHandler((dynamic message) async {
[        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:114:17: Error: The method
'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
[        ] [        ]  - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart'
('../flutter/packages/flutter/lib/src/services/platform_channel.dart').
[        ] [        ] Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
[        ] [        ]         channel.setMockMessageHandler(null);
[        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] ../flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:116:17: Error: The method
'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
[        ] [        ]  - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart'
('../flutter/packages/flutter/lib/src/services/platform_channel.dart').
[        ] [        ] Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
[        ] [        ]         channel.setMockMessageHandler((dynamic message) async {
[        ] [        ]                 ^^^^^^^^^^^^^^^^^^^^^
[        ] [+7986 ms] Persisting file store
[        ] [  +19 ms] Done persisting file store
[        ] [   +3 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:229:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
[        ]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
[        ]            <asynchronous suspension>
[        ]            #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +12 ms] "flutter assemble" took 21,102ms.
[        ] [   +6 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [ +234 ms] ensureAnalyticsSent: 232ms
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[  +24 ms] Building Linux application... (completed in 59.3s)
[   +2 ms] Exception: Build process failed
[   +3 ms] "flutter run" took 60,079ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:671:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +254 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by TahaTesser** [comment]
HI @unoravi 
Can you please try the following 
`flutter clean`
`flutter pub upgrade`
`flutter pub get` 
`flutter run -d linux -v`

**Comment by unoravi** [comment]
@TahaTesser 
Issue resolved.. 

Thanks
