### ISSUE TITLE
Using square brackets to access index of list not working in Flutter release and profile on web

### ISSUE THREAD

**Issue by maffe03** [flutter/flutter#85895]
## Steps to Reproduce

The following code is provided in the syncfusion_flutter_charts library: 
```
final CartesianChartPoint<dynamic> currentPoint =
          _getChartPoint(seriesRenderer, series.dataSource[index], index)!;
```
Using flutter build web --profile the following code is output:
`currentPoint = F._getChartPoint(seriesRenderer, t9.$index(t8, pointIndex), pointIndex);`

**Expected results:** 
No error and chart is displayed.

**Actual results:** 
```
NoSuchMethodError: method not found: '$index' (t9.$index is not a function)
VM83250 main.dart.js:20320     at _ChartSeries._populateDataPoints$1 (http://localhost:3000/main.dart.js:119877:62)
VM83250 main.dart.js:20320     at _ContainerArea_build_closure.call$2 (http://localhost:3000/main.dart.js:119468:10)
VM83250 main.dart.js:20320     at _LayoutBuilderElement__layout_layoutCallback.call$0 (http://localhost:3000/main.dart.js:103706:28)
VM83250 main.dart.js:20320     at BuildOwner.buildScope$2 (http://localhost:3000/main.dart.js:101140:22)
VM83250 main.dart.js:20320     at _LayoutBuilderElement._layout$1 (http://localhost:3000/main.dart.js:103688:19)
VM83250 main.dart.js:20320     at Object.eval (eval at Closure_forwardCallTo (http://localhost:3000/main.dart.js:18201:14), <anonymous>:3:41)
VM83250 main.dart.js:20320     at RenderObject_invokeLayoutCallback_closure.call$0 (http://localhost:3000/main.dart.js:87836:21)
VM83250 main.dart.js:20320     at PipelineOwner._enableMutationsToDirtySubtrees$1 (http://localhost:3000/main.dart.js:87224:18)
VM83250 main.dart.js:20320     at _RenderLayoutBuilder.invokeLayoutCallback$1$1 (http://localhost:3000/main.dart.js:87472:90)
VM83250 main.dart.js:20320     at _RenderLayoutBuilder.performLayout$0 (http://localhost:3000/main.dart.js:103817:15)
2VM83250 main.dart.js:20320 Another exception was thrown: Instance of 'ErrorSummary'
```

Replacing `series.dataSource[index]` with `series.dataSource.elementAt(index)` "solves" the problem.

I'm running the flutter code as a frontend to a express.js web server, if that has any impact.
<details>
  <summary>Logs</summary>

```
   info • Unused import: 'package:intl/intl.dart' • lib/main.dart:10:8 •
          unused_import
   info • Prefer using lowerCamelCase for constant names • lib/main.dart:29:7
          • constant_identifier_names
```

```
[✓] Flutter (Channel beta, 2.3.0-24.1.pre, on Mac OS X 10.15.7 19H15
    darwin-x64, locale sv)
    • Flutter version 2.3.0-24.1.pre at /Users/manfred/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 615957513e (10 days ago), 2021-06-25 09:24:44 -0700
    • Engine revision 9d517f475b
    • Dart version 2.14.0 (build 2.14.0-188.5.beta)

[!] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for
      iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 2 categories.
```
</details>

**Comment by darshankawar** [comment]
@maffe03 
The [plugin](https://pub.dev/packages/syncfusion_flutter_charts) you are using is a 3rd party. Can you try to access index of list using core code, something like below and see if it still replicates the issue ?

```
final fruitList = ['apple', 'orange', 'mango'];
final fruitMap = fruitList.asMap(); // {0: 'apple', 1: 'orange', 2: 'mango'}

// To access 'orange' use the index 1.
final myFruit = fruitMap[1] // 'orange'
```

**Comment by maffe03** [comment]
Nevermind, found a solution. I needed to provide static data to the chart. Interesting that it was a run-time error though.

**Comment by darshankawar** [comment]
Closing this as resolved based on above comment.
