### ISSUE TITLE
WidgetTester finds text even when it is not visible on screen

### ISSUE THREAD

**Issue by speaking-in-code** [flutter/flutter#85927]
## Issue

Finders run in WidgetTester find elements even when they are not rendered.

As an example, this happens with the ExpansionPanel widget. If isExpanded is false, the body of ExpansionPanel is not rendered. WidgetTester can't tell, and finds the test.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

Replace lib/main.dart with this code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Expansion Panel Demo'),
      ),
      body: SingleChildScrollView(
        child: ExpansionPanelList(
          children: [
            _closedPanel(),
            _openPanel(),
          ]
        ),
      ),
    );
  }

  ExpansionPanel _closedPanel() {
    return ExpansionPanel(
      headerBuilder: (context, isExpanded) => Text('Closed Panel'),
      body: Text('Hidden Body'),
      isExpanded: false,
    );
  }

  ExpansionPanel _openPanel() {
    return ExpansionPanel(
      headerBuilder: (context, isExpanded) => Text('Open Panel'),
      body: Text('Visible Body'),
      isExpanded: true,
    );
  }
}
```

Replace test/widget_test.dart with this code:
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:bug/main.dart';

void main() {
  testWidgets('Expansion panel body not visible', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
    expect(find.text('Visible Body'), findsOneWidget);
    expect(find.text('Hidden Body'), findsNothing);
  });
}
```

3. Run `flutter test`

**Expected results:** 

 The test expectation `expect(find.text('Hidden Body'), findsNothing)` should pass

**Actual results:** 

 The test expectation `expect(find.text('Hidden Body'), findsNothing)` fails. The test thinks the Hidden Body widget is rendered.

<details>
  <summary>Logs</summary>
```
$ flutter test
00:04 +0: Expansion panel body not visible                                     
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: no matching nodes in the widget tree
  Actual: _TextFinder:<exactly one widget with text "Hidden Body" (ignoring offstage widgets):
Text("Hidden Body", dependencies: [DefaultTextStyle, MediaQuery])>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/brian/sb/widget_tester/bug/test/widget_test.dart:10:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...

This was caught by the test expectation on the following line:
  file:///Users/brian/sb/widget_tester/bug/test/widget_test.dart line 10
The test description was:
  Expansion panel body not visible
════════════════════════════════════════════════════════════════════════════════════════════════════
00:04 +0 -1: Expansion panel body not visible [E]                              
  Test failed. See exception logs above.
  The test description was: Expansion panel body not visible
  
00:04 +0 -1: Some tests failed.                                                
```

</details>

**Comment by darshankawar** [comment]
I see the same behavior using latest stable.

<details>
<summary>test log</summary>

```

dhs@Dhss-MacBook-Pro macbug % flutter test
00:02 +0: Expansion panel body not visible                                                                                                                                               
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: no matching nodes in the widget tree
  Actual: _TextFinder:<exactly one widget with text "Hidden Body" (ignoring offstage widgets):
Text("Hidden Body", dependencies: [DefaultTextStyle, MediaQuery])>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/dhs/Documents/NCFlutter/macbug/test/widget_test.dart:9:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
...

This was caught by the test expectation on the following line:
  file:///Users/dhs/Documents/NCFlutter/macbug/test/widget_test.dart line 9
The test description was:
  Expansion panel body not visible
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: Expansion panel body not visible [E]                                                                                                                                        
  Test failed. See exception logs above.
  The test description was: Expansion panel body not visible
  
00:02 +0 -1: Some tests failed.                                                                                                                                                          
dhs@Dhss-MacBook-Pro macbug % 



```

</details>

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by tirth-patel-nc** [comment]
# Triage Report

I was able to reproduce the issue using the provided code sample on both the `stable (3.29.3)` and `master (3.32.0-1.0.pre.474)` channels.

<details>
<summary>Code Sample (Same as OP)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Expansion Panel Demo'),
      ),
      body: SingleChildScrollView(
        child: ExpansionPanelList(
          children: [
            _closedPanel(),
            _openPanel(),
          ]
        ),
      ),
    );
  }

  ExpansionPanel _closedPanel() {
    return ExpansionPanel(
      headerBuilder: (context, isExpanded) => Text('Closed Panel'),
      body: Text('Hidden Body'),
      isExpanded: false,
    );
  }

  ExpansionPanel _openPanel() {
    return ExpansionPanel(
      headerBuilder: (context, isExpanded) => Text('Open Panel'),
      body: Text('Visible Body'),
      isExpanded: true,
    );
  }
}
```

</details>

<details>
<summary>Test File (Same as OP)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:bug/main.dart';

void main() {
  testWidgets('Expansion panel body not visible', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());
    expect(find.text('Visible Body'), findsOneWidget);
    expect(find.text('Hidden Body'), findsNothing);
  });
}
```

</details>

<details>
<summary>Test Failure Log</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: no matching candidates
  Actual: _TextWidgetFinder:<Found 1 widget with text "Hidden Body": [
            Text("Hidden Body", dependencies: [DefaultSelectionStyle, DefaultTextStyle,
MediaQuery]),
          ]>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/tirthpatel/StudioProjects/hello_world/test/widget_test.dart:10:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:193:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1064:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/tirthpatel/StudioProjects/hello_world/test/widget_test.dart line 10
The test description was:
  Expansion panel body not visible
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

<details>
  <summary>stable (3.29.3) - flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.29.3, on macOS 15.4.1 24E263 darwin-arm64, locale
    en-IN) [970ms]
    • Flutter version 3.29.3 on channel stable at
      /Users/tirthpatel/Development/flutter_stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ea121f8859 (4 weeks ago), 2025-04-11 19:10:07 +0000
    • Engine revision cf56914b32
    • Dart version 3.7.2
    • DevTools version 2.42.3

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
    [855ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on
      this machine.
      To manually set the JDK path, use: `flutter config
      --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [556ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [9ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [9ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [8ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available) [5.5s]
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.4.1 24E263 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 135.0.7049.115

[✓] Network resources [559ms]
    • All expected network resources are available.

• No issues found!
```

</details>

<details>
  <summary>master (3.32.0-1.0.pre.474) - flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.32.0-1.0.pre.474, on macOS 15.4.1 24E263 darwin-arm64, locale en-IN) [1,380ms]
    • Flutter version 3.32.0-1.0.pre.474 on channel master at /Users/tirthpatel/Development/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83082c19b7 (6 hours ago), 2025-05-08 15:54:18 -0700
    • Engine revision 83082c19b7
    • Dart version 3.9.0 (build 3.9.0-100.2.beta)
    • DevTools version 2.46.0

[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0) [761ms]
    • Android SDK at /Users/tirthpatel/Library/Android/sdk
    • Emulator version 35.4.9.0 (build_id 13025442) (CL:N/A)
    • Platform android-36, build-tools 36.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
      This is the JDK bundled with the latest Android Studio installation on this machine.
      To manually set the JDK path, use: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.3) [428ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16E140
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.3) [7ms]
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.6+-13355223-b631.42)

[✓] VS Code (version 1.99.3) [6ms]
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.110.0

[✓] Connected device (2 available) [5.5s]
    • macOS (desktop) • macos  • darwin-arm64   • macOS 15.4.1 24E263 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 136.0.7103.93

[✓] Network resources [599ms]
    • All expected network resources are available.

• No issues found!
```

</details>
