### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listxcodebuild: error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: /usr/bin/xcodebuild, OS error code: 74

### ISSUE THREAD

**Issue by zhangdaming1230** [flutter/flutter#85939]
## Command
```
flutter build ios --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: /usr/bin/xcodebuild, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:323:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:381:50)
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:546:67)
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:528:41)
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:470:56)
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:447:47)
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart:365:50)
#8      IOSApp.fromIosProject (package:flutter_tools/src/application_package.dart:348:28)
#9      ApplicationPackageStore.getPackageForPlatform (package:flutter_tools/src/application_package.dart:433:30)
#10     BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:70:59)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppCon

**Comment by darshankawar** [comment]
@zhangdaming1230 
I am assuming you are on older version of stable, because this issue was fixed last year, https://github.com/flutter/flutter/issues/57083. I recommend you to upgrade to latest stable / master and try the command again which should not cause this issue.

I am going ahead and closing this as already fixed.
