### ISSUE TITLE
[flutter_plugin_tools] FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#86052]
It seems that when Flutter checks run in CI, and Flutter needs to notify the user that there's a new version, some commands might fail like this:

https://cirrus-ci.com/task/5440777804316672?logs=drive#L14

This seems to be caused by the output of `flutter devices --machine` ([called here](https://github.com/flutter/plugins/blob/master/script/tool/lib/src/drive_examples_command.dart#L204-L213)) starting with a notification of "there's a new version of flutter!":

```
./script/tool_runner.sh drive-examples --ios --exclude $PLUGINS_TO_EXCLUDE_INTEGRATION_TESTS
running drive-examples --ios --exclude in_app_purchase_ios,ios_platform_images,sensors
Unhandled exception:
FormatException: Unexpected character (at character 1)
╔════════════════════════════════════════════════════════════════════════════╗
^
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:506:36)
#5      JsonCodec.decode (dart:convert/json.dart:157:41)
#6      jsonDecode (dart:convert/json.dart:96:10)
#7      DriveExamplesCommand._getDevicesForPlatform (package:flutter_plugin_tools/src/drive_examples_command.dart:212:10)
<asynchronous suspension>
#8      DriveExamplesCommand.initializeRun (package:flutter_plugin_tools/src/drive_examples_command.dart:94:36)
<asynchronous suspension>
#9      PackageLoopingCommand._runInternal (package:flutter_plugin_tools/src/common/package_looping_command.dart:203:5)
<asynchronous suspension>
#10     PackageLoopingCommand.run (package:flutter_plugin_tools/src/common/package_looping_command.dart:190:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     main.<anonymous closure> (package:flutter_plugin_tools/src/main.dart)
<asynchronous suspension>
Exit status: 255
```

_Note the first line of output that the script is attempting to parse:_

```
╔════════════════════════════════════════════════════════════════════════════╗
```

**Comment by stuartmorgan** [comment]
Not being on a channel will prevent this; I'll need to see if changing to checking out by tag is enough, or if needs a more complex workaround.

It's also clearly a `flutter` bug, which I'll file separately (since we'll need to work around it for stable.)

**Comment by ditman** [comment]
> It's also clearly a flutter bug, which I'll file separately (since we'll need to work around it for stable.)

Yes, they might want to output the banner to stderr :/

**Comment by ditman** [comment]
Thanks for the super quick fix!!
