### ISSUE TITLE
[tool_crash] ClientException

### ISSUE THREAD

**Issue by ErosHel** [flutter/flutter#86088]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=b1a2304b0ccc60d63275516b1cf0e3b427046ad8 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ClientException
```
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:49:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:45:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:272:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:712:16)
#5      _rootRunBinary (dart:async/zone.dart:1378:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#12     _addErrorWithReplacement (dart:async/stream_pipe.dart:176:8)
#13     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:277:11)
#14     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#15     _rootRunBinary (dart:async/zone.dart:1378:47)
#16     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#17     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#18     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#19     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#20     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#21     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#22     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#23     _StreamController.addError (dart:async/stream_controller.dart:569:5)
#24     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1183:22)
```
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5268h darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/hel/soft/flutter
    • Framework revision f4abaa0735 (7 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/hel/Library/Android/sdk
    • Java binary at: /Users/hel/Library/Java/JavaVirtualMachines/azul-1.8.0_292/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.54.0.21-CA-macos-aarch64) (build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Users/hel/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.6222.4.2111.7407564/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Users/hel/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 7 Plus (mobile) • b1a2304b0ccc60d63275516b1cf0e3b427046ad8 • ios            • iOS 14.0.1
    • Chrome (web)                     • chrome                                   • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b22742018b3edf16c6cadd7b76d9db5e7f9064b5
### Plugins
device_info_plus-1.0.1
device_info_plus_macos-1.0.1
device_info_plus_web-1.0.1
flutter_plugin_android_lifecycle-2.0.2
fluttertoast-8.0.7
image_picker-0.8.1+3
image_picker_for_web-2.0.0
path_provider_linux-2.0.0
path_provider_windows-2.0.1
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0

**Comment by darshankawar** [comment]
@ErosHel 
This issue was fixed and merged into master, #73356
Please switch to latest master and try the same command again to see if it works or issue still persists.

```
flutter channel master
flutter upgrade
flutter --no-color run --machine --track-widget-creation --device-id=b1a2304b0ccc60d63275516b1cf0e3b427046ad8 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart
```

Closing this for now as this is already fixed. If after switching to latest master you see the same issue again, write in comments and I'll reopen it.
