### ISSUE TITLE
hashValues doesn't throw with Iterables

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#86080]
## Steps to Reproduce

Use an iterable inside `hashValues`

**Expected results:** assertion on this line https://github.com/flutter/engine/blob/221c82954df228026ab93f3876dcb485e2e1305b/lib/ui/hash_codes.dart#L17

**Actual results:** nothing

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('Counter increments smoke test', () async {
    Test([]);
    Test({});
    Test(<int>{});
  });
}

class Test {
  Test(this.iterable) {
    hashValues(
      hashList(iterable),
      hashList(iterable),
    );
  }
  final Iterable iterable;
}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.4.0-1.0.pre.112, on Microsoft Windows [Version 10.0.19041.1052], locale ru-RU)
    • Flutter version 2.4.0-1.0.pre.112 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • Framework revision 3bac804112 (33 minutes ago), 2021-07-08 03:01:04 -0400
    • Engine revision 99a2904675
    • Dart version 2.14.0 (build 2.14.0-288.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1052]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.
```

</details>

Additional context: I could trigger this exception once in undetermined conditions (not this test) on a framework revision from a few weeks ago, but unfortunately I lost those conditions and cannot longer trigger it back

**Comment by TahaTesser** [comment]
Hi @nt4f04uNd 
Thanks for filing the issue!  I can confirm the behavioir

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (7 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • def0ad20 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.22000.51]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.64

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.114, on Microsoft Windows [Version 10.0.22000.51], locale en-US)
    • Flutter version 2.4.0-1.0.pre.114 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bc1b91c4b3 (3 hours ago), 2021-07-08 04:11:04 -0400
    • Engine revision c989ae17b7
    • Dart version 2.14.0 (build 2.14.0-289.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.57.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile)  • def0ad20 • android-arm64   • Android 10 (API 29)
    • Windows (desktop)       • windows  • windows-x64     • Microsoft Windows [Version 10.0.22000.51]
    • Windows (UWP) (desktop) • winuwp   • windows-uwp-x64 •
    • Chrome (web)            • chrome   • web-javascript  • Google Chrome 91.0.4472.124
    • Edge (web)              • edge     • web-javascript  • Microsoft Edge 91.0.864.64

• No issues found!
```
		
</details>

✅ : No Issue ❌: Issue reproduced

**Comment by jonahwilliams** [comment]
asserts won't trigger in unless the platform dills were compiled in the engine with asserts enabled. I wonder if we're missing a flag

**Comment by chinmaygarde** [comment]
cc @a-siva. We are not enabling asserts in the platform dills at all (in `compile_platform.gni`). So it makes sense that these are stripped away. Can we not strip this in a the debug runtime mode please?

**Comment by a-siva** [comment]
> cc @a-siva. We are not enabling asserts in the platform dills at all (in `compile_platform.gni`). So it makes sense that these are stripped away. Can we not strip this in a the debug runtime mode please? Not sure how to route this.

The front end does not strip out the asserts, it retains them in the kernel file and at runtime the VM then turns on the asserts. In the example above is the application running in development mode (under JIT) or as an AOT application ?
I tried a simple example as follows:
```
main() {
  assert(false);
  print("Hello");
}

> /usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/dart pkg/vm/bin/gen_kernel.dart --platform=/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/vm_platform_strong.dill ~/tmp/hello.dart

>/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/dart ~/tmp/hello.dart.dill 
Hello

> /usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/dart --enable-asserts ~/tmp/hello.dart.dill
Unhandled exception:
'file:///usr/local/google/home/asiva/tmp/hello.dart': Failed assertion: line 2 pos 10: 'false': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      main (file:///usr/local/google/home/asiva/tmp/hello.dart:2:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)


>/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/dart pkg/vm/bin/gen_kernel.dart --platform=/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/vm_platform_strong.dill --aot ~/tmp/hello.dart

>/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/gen_snapshot --snapshot_kind=app-aot-elf --elf=/usr/local/google/home/asiva/tmp/hello.aot ~/tmp/hello.dart.dill

>/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/dart_precompiled_runtime ~/tmp/hello.aot
Hello

>/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/gen_snapshot --snapshot_kind=app-aot-elf --elf=/usr/local/google/home/asiva/tmp/hello.aot --enable-asserts ~/tmp/hello.dart.dill

>/usr/local/google/home/asiva/workspace/dart-tot/sdk/out/ReleaseX64/dart_precompiled_runtime --enable-asserts ~/tmp/hello.aot
Hello
```

If you notice in the above example the kernel file (~/tmp/.hello.dart.dill) is always the same as is generated without the --enable-asserts option.
~

**Comment by chinmaygarde** [comment]
> In the example above is the application running in development mode (under JIT) or as an AOT application ?

I don't have an answer to this question. We may need to add this test case to the engine unit-test harness and run in the different modes to find out.

**Comment by nt4f04uNd** [comment]
Closing, since there's an open issue to deprecate this https://github.com/flutter/flutter/issues/85431
