### ISSUE TITLE
'The flutter tool cannot access the file or directory' on windows (flutter 2.2.3)

### ISSUE THREAD

**Issue by Tilto0822** [flutter/flutter#86095]
## Steps to Reproduce

1. I'm installing flutter 2.2.3 by git clone, and run `flutter doctor`
2. And for accept the android license, I ran `flutter doctor --android-licenses`
3. but it shows an error, and I can't solve this by anything

## Logs

<details>
<summary>Logs</summary>

```
PS C:\Users\tilto> flutter doctor --android-licenses
Unhandled exception:
Exception: null. The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:778:3)
#2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:768:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:588:7)
#4      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:684:12)
#5      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:373:51)
#6      _runGit (package:flutter_tools/src/version.dart:658:23)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:67:47)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:230:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#13     flutterVersion (package:flutter_tools/src/globals.dart:52:46)
#14     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:226:33)
#15     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#16     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#17     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#18     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#19     featureFlags (package:flutter_tools/src/features.dart:10:42)
#20     CreateBase.addPlatformsOptions (package:flutter_tools/src/commands/create_base.dart:149:13)
#21     new CreateCommand (package:flutter_tools/src/commands/create.dart:35:5)
#22     generateCommands (package:flutter_tools/executable.dart:152:3)
#23     main.<anonymous closure> (package:flutter_tools/executable.dart:93:11)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:48:13)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

</details>

**Comment by darshankawar** [comment]
@Tilto0822 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/70216
Please follow-up in it for further updates.

Also, as a workaround, try [this](https://github.com/flutter/flutter/issues/73674#issuecomment-758011657) solution and see if it works for you.
Closing this as duplicate.
