### ISSUE TITLE
Creating app-aot-elf with engine (aarch64) built with runtime=release causes abort

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#86112]
Engine version 9d517f475ba1282b619477bde8e708d6a34287cf (this week's beta channel)

I get the following error: 

```
| 872e180e-6f34-472e-a36f-065e22d12aa6 app.dill 0
| Warning: Generating ELF library without DWARF debugging information.
| ../../third_party/dart/runtime/vm/clustered_snapshot.cc: 6563: error: Reference for object Type: (H3621e047) TextureController<C1X0> is unallocated
| Aborted (core dumped)
```

The pattern I use to create the AOT image is identical between debug, profile, and release builds of engine.  This only happens when engine is built with runtime=release.

```
flutter build bundle
dart ${ENGINE_SDK}/frontend_server.dart.snapshot --aot --tfa --target=flutter --sdk-root ${ENGINE_SDK} --output-dill app.dill lib/main.dart
${ENGINE_SDK}/clang_x64/gen_snapshot --deterministic --snapshot_kind=app-aot-elf --elf=libapp.so --strip app.dill
```

@csells

**Comment by chinmaygarde** [comment]
We might need more information here. Are the repro steps or a reduced test case perhaps? Maybe even a backtrace. You said this was on the beta channel. Is this a regression? If so, when was the last known good roll?

**Comment by jwinarske** [comment]
It showed up randomly in builds last week.  I haven't seen it since.

Has this been a known issue in the past?  What can cause this?

**Comment by chinmaygarde** [comment]
No, I haven't seen issues of this type in the past. Ryan might be better able to tell which subsystems were affected recently.

**Comment by rmacnak-google** [comment]
This is potentially related to recent changes in the representation of function types or changes in tree-shaking. But we haven't seen this particular error before, and will the need the stack trace at a minimum (and most likely a reproduction) to debug it.

**Comment by mraleph** [comment]
@rmacnak-google there is seemingly a repro on b/190457957#comment17 - though it might have bit rotted since Jun 16.

**Comment by chinmaygarde** [comment]
Ryan tried to follow the instructions in the referenced issue but couldn't get it to repro either. So we are stalled on progress here. @jwinarske is there a chance we'll be able to get a backtrace or coredump? FML has utilities for dumping the backtrace that perhaps we can wire up in your embedder. Unless you have other forms of crash reporting already hooked up.

**Comment by jwinarske** [comment]
@chinmaygarde At this point I do not get a consistent repro in pipeline builds.  If I can consistently repro on local build I can provide backtrace or coredump.  So far I am not able to repro on local build.

**Comment by a-siva** [comment]
> @chinmaygarde At this point I do not get a consistent repro in pipeline builds. If I can consistently repro on local build I can provide backtrace or coredump. So far I am not able to repro on local build.

@jwinarske are you still seeing the above error intermittently with the newer builds? Your comment seems to indicate you still get the error but  not in a consistent manner, is that correct.

**Comment by zanderso** [comment]
Dart hash is 0cc2dddef12a1d63d08f993b63667623e584b459 at engine hash 9d517f475ba1282b619477bde8e708d6a34287cf

**Comment by infernalboy** [comment]
May be this helps

```
[   +1 ms] [  +19 ms] executing: /home/infernalboy/soft/flutter/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot --deterministic --snapshot_kind=app-aot-elf
--elf=/{our path to project}/.dart_tool/flutter_build/b629751a3c20bf395060efb5b4785623/app.so --strip
/{our path to project}/.dart_tool/flutter_build/b629751a3c20bf395060efb5b4785623/app.dill
[   +1 ms] [+8165 ms] ===== CRASH =====
[        ] [   +3 ms] si_signo=Segmentation fault(11), si_code=2, si_addr=0x5dce30
[        ] [ +799 ms] Dart snapshot generator failed with exit code -6
[        ] [   +7 ms] Persisting file store
[        ] [  +35 ms] Done persisting file store
[        ] [  +40 ms] Target aot_elf_release failed: Exception: AOT snapshotter exited with code -6
[        ]            #0      AotElfBase.build (package:flutter_tools/src/build_system/targets/common.dart:287:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[  +17 ms]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
[   +4 ms]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
[        ]            <asynchronous suspension>
[        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[   +1 ms]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[   +4 ms]            #10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[   +1 ms]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +9 ms]            <asynchronous suspension>
[        ]            #16     main (package:flutter_tools/executable.dart:92:3)
[        ]            <asynchronous suspension>
[        ] [  +33 ms] "flutter assemble" took 11,184ms.
[        ] [  +16 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:92:3)
[        ]            <asynchronous suspension>
[        ] [ +186 ms] ensureAnalyticsSent: 183ms
[        ] [   +2 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[ +110 ms] Building Linux application... (completed in 13.9s)
[   +6 ms] Exception: Build process failed
[  +15 ms] "flutter run" took 15,878ms.
```

**Comment by a-siva** [comment]
> May be this helps
> 
> ```
> [   +1 ms] [  +19 ms] executing: /home/infernalboy/soft/flutter/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot --deterministic --snapshot_kind=app-aot-elf
> --elf=/{our path to project}/.dart_tool/flutter_build/b629751a3c20bf395060efb5b4785623/app.so --strip
> /{our path to project}/.dart_tool/flutter_build/b629751a3c20bf395060efb5b4785623/app.dill
> [   +1 ms] [+8165 ms] ===== CRASH =====
> [        ] [   +3 ms] si_signo=Segmentation fault(11), si_code=2, si_addr=0x5dce30
> [        ] [ +799 ms] Dart snapshot generator failed with exit code -6
> [        ] [   +7 ms] Persisting file store
> [        ] [  +35 ms] Done persisting file store
> [        ] [  +40 ms] Target aot_elf_release failed: Exception: AOT snapshotter exited with code -6
> [        ]            #0      AotElfBase.build (package:flutter_tools/src/build_system/targets/common.dart:287:7)
> [        ]            <asynchronous suspension>
> [        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
> [        ]            <asynchronous suspension>
> [        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
> [        ]            <asynchronous suspension>
> [  +17 ms]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
> [   +4 ms]            <asynchronous suspension>
> [        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
> [        ]            <asynchronous suspension>
> [        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
> [        ]            <asynchronous suspension>
> [        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
> [        ]            <asynchronous suspension>
> [        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
> [        ]            <asynchronous suspension>
> [        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
> [        ]            <asynchronous suspension>
> [   +1 ms]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [   +4 ms]            #10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
> [        ]            <asynchronous suspension>
> [        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
> [        ]            <asynchronous suspension>
> [        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
> [        ]            <asynchronous suspension>
> [        ]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
> [        ]            <asynchronous suspension>
> [   +1 ms]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [   +9 ms]            <asynchronous suspension>
> [        ]            #16     main (package:flutter_tools/executable.dart:92:3)
> [        ]            <asynchronous suspension>
> [        ] [  +33 ms] "flutter assemble" took 11,184ms.
> [        ] [  +16 ms] 
> [        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
> [        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
> [        ]            <asynchronous suspension>
> [        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
> [        ]            <asynchronous suspension>
> [        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
> [        ]            <asynchronous suspension>
> [        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
> [        ]            <asynchronous suspension>
> [        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
> [        ]            <asynchronous suspension>
> [        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
> [        ]            <asynchronous suspension>
> [        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> [        ]            <asynchronous suspension>
> [        ]            #10     main (package:flutter_tools/executable.dart:92:3)
> [        ]            <asynchronous suspension>
> [        ] [ +186 ms] ensureAnalyticsSent: 183ms
> [        ] [   +2 ms] Running shutdown hooks
> [        ] [        ] Shutdown hooks complete
> [        ] [        ] exiting with code 1
> [        ] ninja: build stopped: subcommand failed.
> [ +110 ms] Building Linux application... (completed in 13.9s)
> [   +6 ms] Exception: Build process failed
> [  +15 ms] "flutter run" took 15,878ms.
> ```

This seems like a stacktrace from flutter tools and not the AOT snapshotter process which had the SEGV crash, do you see another stacktrace in your log ?

**Comment by infernalboy** [comment]
> > May be this helps
> > ```
> > [   +1 ms] [  +19 ms] executing: /home/infernalboy/soft/flutter/bin/cache/artifacts/engine/linux-x64-release/gen_snapshot --deterministic --snapshot_kind=app-aot-elf
> > --elf=/{our path to project}/.dart_tool/flutter_build/b629751a3c20bf395060efb5b4785623/app.so --strip
> > /{our path to project}/.dart_tool/flutter_build/b629751a3c20bf395060efb5b4785623/app.dill
> > [   +1 ms] [+8165 ms] ===== CRASH =====
> > [        ] [   +3 ms] si_signo=Segmentation fault(11), si_code=2, si_addr=0x5dce30
> > [        ] [ +799 ms] Dart snapshot generator failed with exit code -6
> > [        ] [   +7 ms] Persisting file store
> > [        ] [  +35 ms] Done persisting file store
> > [        ] [  +40 ms] Target aot_elf_release failed: Exception: AOT snapshotter exited with code -6
> > [        ]            #0      AotElfBase.build (package:flutter_tools/src/build_system/targets/common.dart:287:7)
> > [        ]            <asynchronous suspension>
> > [        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
> > [        ]            <asynchronous suspension>
> > [        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
> > [        ]            <asynchronous suspension>
> > [  +17 ms]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
> > [   +4 ms]            <asynchronous suspension>
> > [        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
> > [        ]            <asynchronous suspension>
> > [        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
> > [        ]            <asynchronous suspension>
> > [        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
> > [        ]            <asynchronous suspension>
> > [        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
> > [        ]            <asynchronous suspension>
> > [        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
> > [        ]            <asynchronous suspension>
> > [   +1 ms]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> > [        ]            <asynchronous suspension>
> > [   +4 ms]            #10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
> > [        ]            <asynchronous suspension>
> > [        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
> > [        ]            <asynchronous suspension>
> > [        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> > [        ]            <asynchronous suspension>
> > [        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
> > [        ]            <asynchronous suspension>
> > [        ]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
> > [        ]            <asynchronous suspension>
> > [   +1 ms]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> > [   +9 ms]            <asynchronous suspension>
> > [        ]            #16     main (package:flutter_tools/executable.dart:92:3)
> > [        ]            <asynchronous suspension>
> > [        ] [  +33 ms] "flutter assemble" took 11,184ms.
> > [        ] [  +16 ms] 
> > [        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
> > [        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
> > [        ]            <asynchronous suspension>
> > [        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1126:27)
> > [        ]            <asynchronous suspension>
> > [        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> > [        ]            <asynchronous suspension>
> > [        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
> > [        ]            <asynchronous suspension>
> > [        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
> > [        ]            <asynchronous suspension>
> > [        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> > [        ]            <asynchronous suspension>
> > [        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
> > [        ]            <asynchronous suspension>
> > [        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
> > [        ]            <asynchronous suspension>
> > [        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
> > [        ]            <asynchronous suspension>
> > [        ]            #10     main (package:flutter_tools/executable.dart:92:3)
> > [        ]            <asynchronous suspension>
> > [        ] [ +186 ms] ensureAnalyticsSent: 183ms
> > [        ] [   +2 ms] Running shutdown hooks
> > [        ] [        ] Shutdown hooks complete
> > [        ] [        ] exiting with code 1
> > [        ] ninja: build stopped: subcommand failed.
> > [ +110 ms] Building Linux application... (completed in 13.9s)
> > [   +6 ms] Exception: Build process failed
> > [  +15 ms] "flutter run" took 15,878ms.
> > ```
> 
> This seems like a stacktrace from flutter tools and not the AOT snapshotter process which had the SEGV crash, do you see another stacktrace in your log ?

Only this.  

```
  +1 ms] [+1091 ms] aot_elf_release: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have
updated contents:
```

The crush (in my case) happens on channels beta and dev. On stable channel project is builds successful

**Comment by mraleph** [comment]
@infernalboy Please file a separate issue for this crash as it is most certainly unrelated to this (#86112) issue. Ultimately to make progress we would need more information about the crash or a reproduction.

**Comment by zanderso** [comment]
Closing as stale.
