### ISSUE TITLE
Unhandled Exception: CameraException(INVALID_PATH, The platform "TargetPlatform.android" did not return a path while reporting success. The platform should always return a valid path or report an error.)

### ISSUE THREAD

**Issue by julius-stuemmler** [flutter/flutter#86169]
## Infos for Reproduce

I simply want to record a video. The code is based on the example code of the camera dependency from pub.dev `camera: ^0.8.1+3`. 

### System infos
- Android Emulator (Google Pixel 4) from Android Studio
- API 30 / Android 11.0

### My Code

<details> 
<summary>code snippet</summary> 

```dart
class _VideoPageState extends State<VideoPage>
    with WidgetsBindingObserver, TickerProviderStateMixin {
  CameraController? controller;
  XFile? imageFile;
  XFile? videoFile;
  VideoPlayerController? videoController;
  bool enableAudio = true;
  late AnimationController _flashModeControlRowAnimationController;
  late AnimationController _exposureModeControlRowAnimationController;


  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance?.addObserver(this);

    CameraDescription backCamera = new CameraDescription(
        name: "0",
        lensDirection: CameraLensDirection.back,
        sensorOrientation: 270);
    controller = CameraController(
      backCamera,
      ResolutionPreset.veryHigh,
      enableAudio: enableAudio,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );
  }

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);
    _flashModeControlRowAnimationController.dispose();
    _exposureModeControlRowAnimationController.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isInitialized) {
      return;
    }

    if (state == AppLifecycleState.inactive) {
      cameraController.dispose();
    } else if (state == AppLifecycleState.resumed) {
      CameraDescription backCamera = new CameraDescription(
          name: "0",
          lensDirection: CameraLensDirection.back,
          sensorOrientation: 270);
      controller = CameraController(
        backCamera,
        ResolutionPreset.veryHigh,
        enableAudio: enableAudio,
        imageFormatGroup: ImageFormatGroup.jpeg,
      );
    }
  }

  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        key: _scaffoldKey,
        body: FutureBuilder(
          future: initCameraController(),
          builder: (context, snapshot) {
            return SafeArea(
              top: true,
              bottom: true,
              child: Stack(
                children: [
                  Container(
                    child: Padding(
                      padding: const EdgeInsets.all(1.0),
                      child: Center(
                        child: _cameraPreviewWidget(),
                      ),
                    ),
                    decoration: BoxDecoration(
                      color: Colors.black,
                      border: Border.all(
                        color: controller != null &&
                            controller!.value.isRecordingVideo
                            ? Colors.redAccent
                            : Colors.grey,
                        width: 3.0,
                      ),
                    ),
                  ),
                  Column(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Container(
                        padding: EdgeInsets.symmetric(
                            vertical: 6.0, horizontal: 10.0),
                        color: Colors.black.withOpacity(0.5),
                        child: Row(
                          children: <Widget>[
                            IconButton(
                                icon: Icon(Icons.close_rounded,
                                    color: Colors.white, size: 28),
                                onPressed: () {Navigator.pop(context); controller!.dispose();}),
                            Container()
                          ],
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        ),
                      ),
                      Container(
                          color: Colors.black.withOpacity(0.5),
                          padding: EdgeInsets.symmetric(
                              horizontal: 10, vertical: 12),
                          child: _captureControlRowWidget()),
                    ],
                  )
                ],
              ),
            );
          },
        ));
  }

  // Display the preview from the camera (or a message if the preview is not available).
  Widget _cameraPreviewWidget() {
    final CameraController? cameraController = controller;

    print(controller);

    if (cameraController == null || !cameraController.value.isInitialized) {
      return const Text(
        'Tap a camera',
        style: TextStyle(
          color: Colors.white,
          fontSize: 24.0,
          fontWeight: FontWeight.w900,
        ),
      );
    } else {
      return Listener(
        child: CameraPreview(
          controller!,
          child: Container()
        ),
      );
    }
  }

  // Display the control bar with buttons to take pictures and record videos.
  Widget _captureControlRowWidget() {
    final CameraController? cameraController = controller;

    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      mainAxisSize: MainAxisSize.max,
      children: <Widget>[
        IconButton(
          icon: cameraController != null &&
              cameraController.value.isRecordingPaused
              ? Icon(Icons.play_arrow)
              : Icon(Icons.pause),
          color: Colors.blue,
          onPressed: cameraController != null &&
              cameraController.value.isInitialized &&
              cameraController.value.isRecordingVideo
              ? (cameraController.value.isRecordingPaused)
              ? onResumeButtonPressed
              : onPauseButtonPressed
              : null,
        ),
        CircleAvatar(
          radius: 30,
          backgroundColor: AppColors.mainAccent,
          child: CircleAvatar(
              radius: 27.5,
              backgroundColor: Colors.white,
              child: IconButton(
                icon: cameraController != null &&
                    cameraController.value.isInitialized &&
                    cameraController.value.isRecordingVideo
                    ? const Icon(Icons.stop, color: AppColors.error, size: 28,) : const Icon(Icons.videocam, color: AppColors.mainAccent, size: 28,),
                color: Colors.blue,
                onPressed: cameraController != null &&
                    cameraController.value.isInitialized &&
                    !cameraController.value.isRecordingVideo
                    ? onVideoRecordButtonPressed
                    : onStopButtonPressed,
              )
          ),
        ),
        Container(width: 50,)
      ],
    );
  }

  void showInSnackBar(String message) {
    // ignore: deprecated_member_use
    _scaffoldKey.currentState?.showSnackBar(SnackBar(content: Text(message)));
  }

  void onVideoRecordButtonPressed() {
    startVideoRecording().then((_) {
      if (mounted) setState(() {});
    });
  }

  void onStopButtonPressed() {
    stopVideoRecording().then((file) {
      if (mounted) setState(() {});
      if (file != null) {
        showInSnackBar('Video recorded to ${file.path}');
        videoFile = file;
      }
    });
  }

  void onPauseButtonPressed() {
    pauseVideoRecording().then((_) {
      if (mounted) setState(() {});
      showInSnackBar('Video recording paused');
    });
  }

  void onResumeButtonPressed() {
    resumeVideoRecording().then((_) {
      if (mounted) setState(() {});
      showInSnackBar('Video recording resumed');
    });
  }

  Future<void> startVideoRecording() async {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isInitialized) {
      showInSnackBar('Error: select a camera first.');
      return;
    }

    if (cameraController.value.isRecordingVideo) {
      // A recording is already started, do nothing.
      return;
    }

    try {
      await cameraController.startVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      return;
    }
  }

  Future<XFile?> stopVideoRecording() async {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isRecordingVideo) {
      return null;
    }

    try {
      return cameraController.stopVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
  }

  Future<void> pauseVideoRecording() async {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isRecordingVideo) {
      return null;
    }

    try {
      await cameraController.pauseVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      rethrow;
    }
  }

  Future<void> resumeVideoRecording() async {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isRecordingVideo) {
      return null;
    }

    try {
      await cameraController.resumeVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      rethrow;
    }
  }

  void _showCameraException(CameraException e) {
    logError(e.code, e.description);
    showInSnackBar('Error: ${e.code}\n${e.description}');
  }

  Future<void> initCameraController() async {
    await controller!.initialize();
  }
}
```

</details>

## My Error

```console
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: CameraException(INVALID_PATH, The platform "TargetPlatform.android" did not return a path while reporting success. The platform should always return a valid path or report an error.)
E/flutter (12283): #0      MethodChannelCamera.stopVideoRecording (package:camera_platform_interface/src/method_channel/method_channel_camera.dart:240:7)
E/flutter (12283): <asynchronous suspension>
E/flutter (12283): #1      CameraController.stopVideoRecording (package:camera/src/camera_controller.dart:478:20)
E/flutter (12283): <asynchronous suspension>
E/flutter (12283): 
I/flutter (12283): CameraController#bddc3(CameraValue(isRecordingVideo: true, isInitialized: true, errorDescription: null, previewSize: Size(1280.0, 720.0), isStreamingImages: false, flashMode: FlashMode.auto, exposureMode: ExposureMode.auto, focusMode: FocusMode.auto, exposurePointSupported: true, focusPointSupported: true, deviceOrientation: DeviceOrientation.portraitUp, lockedCaptureOrientation: null, recordingOrientation: DeviceOrientation.portraitUp))
```

if there are any further questions or any other needed information, feel free to ask!

**Comment by julius-stuemmler** [comment]
@TahaTesser I updated the code in the start post, I think it is minimal now.

**Comment by TahaTesser** [comment]
Hi @julius-stuemmler 
Your code sample is still messy, hard coded camera values and lots of untested controllers and conditions
Instead please try the official example https://pub.dev/packages/camera/example, edit the official if necessary to reproduce 

I tried the official sample, ti works fine on Android

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
