### ISSUE TITLE
Using the CLI to accept the android license crashes

### ISSUE THREAD

**Issue by cadaniel** [flutter/flutter#86184]
## Steps to Reproduce

run flutter doctor --android-licenses

Don't know if it's relevant but I'm running an M1 Mac Mini, AS is 4.2.1

## Logs

<details>
<summary>Logs</summary>

```
casey@Caseys-Mac-mini normative % flutter doctor --android-licenses 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more


```

```

casey@Caseys-Mac-mini normative % flutter doctor -v 
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-CA)
    • Flutter version 2.2.3 at /Users/casey/flutter
    • Framework revision f4abaa0735 (8 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/casey/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Users/casey/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 9F2B654C-42A3-4578-BE0E-D780E396F04A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • iPhone 11 (mobile)         • 1AD57844-0FB8-4309-B473-A38E1403B152 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.106

! Doctor found issues in 1 category.
```

</details>

**Comment by jonahwilliams** [comment]
Do you have all of the dependencies installed as per https://flutter.dev/docs/get-started/install/windows#install-android-studio ?

specifically: Android SDK, Android SDK Command-line Tools, and Android SDK Build-Tools?

**Comment by cadaniel** [comment]
I have in the past yes. 

I tried to update my android studio path since I installed via JetBrains tool box, and now it can't find android studio at all. 

What path is it looking for on mac? Becuase the Android Stuido.app directory does not seem to be it.

**Comment by TahaTesser** [comment]
Hi @cadaniel 

> run flutter doctor --android-licenses

<img width="758" alt="Screenshot 2021-07-12 at 2 20 54 PM" src="https://user-images.githubusercontent.com/48603081/125279434-9c8ce180-e31c-11eb-8c42-60025ba9c897.png">

Go to SDK manager in Android Studio, make sure this is downloaded then execute `flutter doctor --android-licenses` and accept the licenses



> I tried to update my android studio path since I installed via JetBrains toolbox, and now it can't find android studio at all.


I just installed Android Studio from Jetbrains toolbox, Android Studio is detected, Please provide `flutter doctor -v` with this issue. 

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5268h darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (11 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 14.6
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
tahatesser@Tahas-MacBook-P
```

</details>

**Comment by naoliv** [comment]
I am having exactly the same issue here:

```
$ flutter doctor --android-licenses
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

I always updated it without any kind of problems before.

![](https://user-images.githubusercontent.com/982338/125530705-a0f736de-b215-41f4-9b7e-714c60c66d52.png)

<details>
  <summary>flutter doctor -v</summary>

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale pt_BR.UTF-8)
    • Flutter version 2.2.3 at /home/naoliv/Android/flutter
    • Framework revision f4abaa0735 (12 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/naoliv/Android/Sdk/
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /home/naoliv/Android/android-studio/jre/bin/java
    • Java version openjdk version "11.0.8" 2020-07-14
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 12.0.1-1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.2)
    • Android Studio at /home/naoliv/Android/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version openjdk version "11.0.8" 2020-07-14

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /mnt/naoliv/intellij/idea-IC-202.8194.7
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.58.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```

</details>

I don't think this problem is related with not accepting something (or even caused by some user mistake), since I did change nothing between the last successful update and this last one.

**Comment by jonahwilliams** [comment]
You don't have the command line tools installed, you need to install those.

> I don't think this problem is related with not accepting something (or even caused by some user mistake), since I did change nothing between the last successful update and this last one.

The Android SDK updated their JDK and the platform tools no longer works, that is the issue

**Comment by naoliv** [comment]
> You don't have the command line tools installed, you need to install those.

Indeed my mistake here! :-)
Thanks!

From my part it's a wishlist now: we should get a nicer message with `flutter doctor --android-licenses` instead seeing a exception.

**Comment by jonahwilliams** [comment]
We have implemented a new `flutter doctor` check, but it won't be in the previous stable version. Sorry for the confusion here

**Comment by cadaniel** [comment]
I never got an answer as to what directory to point it to on macOS, because it's not accepting the path to the application folder.

**Comment by TahaTesser** [comment]
Hi @cadaniel 
It is pointing to 
'/Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java`
     
If you finder go to with `Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085`, you can locate it 

      
      
      
I just tried Android Studio from Jetbrains toolbox, removed license on purpose for testing
```console
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
```

Then accepted licenses 
```console
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.
```

Some users experiencing this issue resolve by reinstalling cmd-tools, can you please try reinstalling?

**Comment by cadaniel** [comment]
So the .app directory isn't correct 
```
casey@Caseys-Mac-mini normative % flutter config --android-sdk /Users/casey/Library/Application\ Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908
Setting "android-sdk" value to "/Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908".

You may need to restart any open editors for them to read new settings.
casey@Caseys-Mac-mini normative % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-CA)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] Connected device (2 available)


```


```
casey@Caseys-Mac-mini normative % flutter config --android-sdk /Users/casey/Library/Application\ Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android\ Studio.app
Setting "android-sdk" value to "/Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app".

You may need to restart any open editors for them to read new settings.
casey@Caseys-Mac-mini normative % flutter doctor                                                                                                                                  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-CA)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
```

The docs just say "android studio directory" which isn't really helpful.

**Comment by cadaniel** [comment]
So I figured it out. 

You *DO NOT* want the android studio directory as suggested by docs. You want the SDK path. 

This can be found in the SDK manager itself at the top. 

![Screen Shot 2021-07-20 at 1 40 13 PM](https://user-images.githubusercontent.com/5515671/126385411-1371dd91-e19f-4593-baf3-b8ebcbd854d4.png)


This might be helpful to add to the actual docs.

**Comment by TahaTesser** [comment]
@naoliv 
I think you're mistaking Android Studio directory for SDK,  `flutter config --android-studio-dir <directory>` is for Android Studio,

**Comment by cadaniel** [comment]
@TahaTesser The thing is setting the android studio directory to the .app directory on my mac didn't work. I had to set it to the SDK location.
