### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:Command line invocation:    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -listUser defaults from command line:    IDEPackageSupportUseBuiltinSCM = YESxcodebuild: error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: xcrun, OS error code: 74

### ISSUE THREAD

**Issue by ValentinAhrend** [flutter/flutter#86190]
## Command
```
flutter build ios
```
## Logs
ProcessException: Process exited abnormally:
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled. Command: xcrun, OS error code: 74
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:124:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:276:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:470:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/project.dart:619:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/project.dart:601:35)
<asynchronous suspension>
#5      IosProject._parseProductBundleIdentifier (package:flutter_tools/src/project.dart:543:50)
<asynchronous suspension>
#6      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:520:41)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:118:36)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:83:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp (package:flutter_tools/src/commands/build_ios.dart:212:26)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:244:33)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on
    macOS 11.2.3 20D91 darwin-x64,
    locale en-DE)
    • Flutter version 2.2.3 at
      /Users/valentinahrend/flutter
    • Framework revision f4abaa0735 (8
      days ago), 2021-07-01 12:46:11
      -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for
    Android devices (Android SDK
    version 30.0.2)
    • Android SDK at
      /Users/valentinahrend/Library/An
      droid/sdk
    • Platform android-30, build-tools
      30.0.2
    • Java binary at:
      /Applications/Android
      Studio.app/Contents/jre/jdk/Cont
      ents/Home/bin/java
    • Java version OpenJDK Runtime
      Environment (build
      1.8.0_212-release-1586-b4-578421
      1)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at
      /Applications/Xcode.app/Contents
      /Developer
    • Xcode 12.5.1, Build version
      12E507
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve
        the iOS and macOS platform
        side's plugin code that
        responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins
        will not work on iOS or macOS.
        For more info, see
        https://flutter.dev/platform-p
        lugins
      To install see
      https://guides.cocoapods.org/usi
      ng/getting-started.html#installa
      tion for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at
      /Applications/Android
      Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime
      Environment (build
      1.8.0_212-release-1586-b4-578421
      1)

[✓] IntelliJ IDEA Community Edition
    (version 2020.2)
    • IntelliJ at
      /Applications/IntelliJ IDEA
      CE.app
    • Flutter plugin can be installed
      from:
      🔨
      https://plugins.jetbrains.com/pl
      ugin/9212-flutter
    • Dart plugin can be installed
      from:
      🔨
      https://plugins.jetbrains.com/pl
      ugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual
      Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) •
      A3386C79-5782-4E87-9E30-2DD48CD2
      FD1E • ios            •
      com.apple.CoreSimulator.SimRunti
      me.iOS-14-5 (simulator)
    • macOS (desktop)    • macos
      • darwin-x64     • macOS 11.2.3
      20D91 darwin-x64
    • Chrome (web)       • chrome
      • web-javascript • Google Chrome
      91.0.4472.114

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: 8af6b2f038c1172e61d418869363a28dffec3cb4
### Plugins
apple_sign_in-0.1.0
camera-0.5.8+17
cloud_firestore-0.14.4
cloud_firestore_web-0.2.1+2
device_info-0.4.2+10
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_database-4.4.0
firebase_messaging-7.0.3
firebase_storage-4.0.1
flutter_applovin_max-0.1.0
flutter_archive-3.0.0
flutter_image_compress-1.0.0
flutter_local_notifications-2.0.2
flutter_plugin_android_lifecycle-1.0.11
fluttertoast-7.1.8
image_picker-0.6.7+22
path_provider-0.4.1
path_provider_linux-0.0.1+2
path_provider_windows-0.0.5
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by darshankawar** [comment]
@ValentinAhrend 
This was fixed in this issue, https://github.com/flutter/flutter/issues/57083
Can you try by switching to latest master and run the same command again and see if you still get the same error or not?

```
flutter channel master
flutter upgrade
flutter build ios
```

**Comment by ValentinAhrend** [comment]
@darshankawar I already solved this issue by recreating my project. But thanks anyways!
