### ISSUE TITLE
Google maps crashes when second concurrent emulator starts (With google maps plugin running on both)

### ISSUE THREAD

**Issue by patrickgahan** [flutter/flutter#86193]
When trying to debug on concurrent simulators (One Android and one iOS), the second emulator to start triggers a crash on the one that was already running with the google maps plugin. This wasn't happening before the upgrade to the latest flutter version 2.2.3.

I'm trying to downgrade to 2.2.2 and check if this still happens so that I can isolate the issue.

You can see the stack error thrown below.
I haven't tried on a clean project but I assume this should be easy to reproduce with a clean project and the google maps plugin (I will try it too and post the results here)

Thank you!

PlatformException(error, Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:86) at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59) at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233) at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85) at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(MessageQueue.java:335) at android.os.Looper.loop(Looper.java:183) at android.app.ActivityThread.main(ActivityThread.java:7656) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) ). Error thrown null.
StandardMethodCodec.decodeEnvelope (message_codecs.dart:597)
MethodChannel._invokeMethod (platform_channel.dart:158)
PlatformViewsService.initUiKitView (platform_views.dart:217)
_UiKitViewState._createNewUiKitView (platform_view.dart:630)

**Comment by TahaTesser** [comment]
Hi @patrickgahan 
Thanks for filing the issue, this is bizarre, at first, I wasn't if it would reproduce 

When running the same app on iOS Simulator and Android Emulator using VS Code `launch.json` at the same time, one of them emulator crashes with a blank page (no other widgets are loaded too), and the emulator loads fine. 

| Preview | 
| --------------- | 
<img src="https://user-images.githubusercontent.com/48603081/125304716-7b38ef00-e336-11eb-9a41-d4fa3afd5298.png" height="450" />	|



If I run the app one by one on each simulator the emulator or simulator then emulator, no errors are throw, maps load.

### Code sample
[Official sampe](https://pub.dev/packages/google_maps_flutter/example)


### Logs
<details> 
<summary>logs</summary> 
	
```console
E/MethodChannel#flutter/platform_views(16295): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (16295): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
E/flutter (16295): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:86)
```

</details>

|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5268h darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (11 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554                        •
      android-x86    • Android 11 (API 30) (emulator)
    • Taha’s iPhone (mobile)  • 00008020-001059882212002E            • ios
      • iOS 14.6
    • iPhone 12 Pro (mobile)  • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)         • macos                                •
      darwin-x64     • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)            • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```

```console[✓] Flutter (Channel master, 2.4.0-1.0.pre.189, on macOS 12.0 21A5268h
    darwin-x64, locale en-GB)
    • Flutter version 2.4.0-1.0.pre.189 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6a844360a (5 hours ago), 2021-07-12 05:06:04 -0400
    • Engine revision 7851449b4d
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5554                        •
      android-x86    • Android 11 (API 30) (emulator)
    • Taha’s iPhone (mobile)  • 00008020-001059882212002E            • ios
      • iOS 14.6 18F72
    • iPhone 12 Pro (mobile)  • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)         • macos                                •
      darwin-x64     • macOS 12.0 21A5268h darwin-x64
    • Chrome (web)            • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.

```
		
</details>

✅ : No Issue ❌: Issue reproduced
