### ISSUE TITLE
How to disable shrink and minifyEnabled for specific dependencies in android

### ISSUE THREAD

**Issue by 4-alok** [flutter/flutter#86265]
*How to disable shrink and minifyEnabled for specific dependencies*

I'm working on a sentence detection flutter plugin in Java. It works perfectly in the run, debug, and profile mode, but it fails in release or build mode.

error on release mode

````
I/flutter ( 2762): PlatformException(error, d.a.d.c: Could not instantiate the opennlp.tools.sentdetect.SentenceDetectorFactory. The initialization throw an exception., null, java.lang.IllegalArgumentException: d.a.d.c: Could not instantiate the opennlp.tools.sentdetect.SentenceDetectorFactory. The initialization throw an exception.
I/flutter ( 2762):      at d.a.d.i.c.j(Unknown Source:31)
I/flutter ( 2762):      at d.a.d.i.c.l(Unknown Source:82)
I/flutter ( 2762):      at d.a.d.i.c.<init>(Unknown Source:4)
I/flutter ( 2762):      at d.a.c.g.<init>(Unknown Source:2)
I/flutter ( 2762):      at b.a.a.a.b.d(Unknown Source:19)
I/flutter ( 2762):      at b.a.a.a.b.b(Unknown Source:30)
I/flutter ( 2762):      at c.a.c.a.i$a.a(Unknown Source:17)
I/flutter ( 2762):      at io.flutter.embedding.engine.e.b.c(Unknown Source:57)
I/flutter ( 2762):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
I/flutter ( 2762):      at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter ( 2762):      at android.os.MessageQueue.next(MessageQueue.java:336)
I/flutter ( 2762):      at android.os.Looper.loop(Looper.java:174)
I/flutter ( 2762):      at android.app.ActivityThread.main(ActivityThread.java:7615)
I/flutter ( 2762):      at java.lang.reflect.Method.invoke(Native Method)
I/flutter ( 2762):      at com.android.internal.os.RuntimeInit$Met
````

In **build.gradle** I found that **if minifyEnabled is true**, the above error appears and when **minifyEnabled and shrink are false** everything works fine.

dependencies
```
dependencies {
    api group: "org.apache.opennlp", name: "opennlp-tools", version: "1.9.3"
}
```
my java code 
````java
  private List<String> processText(String text) {
    AssetManager assetManager = context.getAssets();
    InputStream inputStream = null;
    List<String> sentencesList = Collections.<String>emptyList();
    try {
      inputStream = assetManager.open("opennlp-en-ud-ewt-sentence.bin");
      SentenceModel model = new SentenceModel(inputStream);
      SentenceDetectorME sentenceDetector = new SentenceDetectorME(model);
      sentencesList = Arrays.asList(sentenceDetector.sentDetect(text));
      for(String s: sentencesList){
        Log.d("JavaSide", s);
      }
      return Arrays.asList(sentenceDetector.sentDetect(text));

    } catch (IOException e) {
      e.printStackTrace();
    }
    return sentencesList;
  }
````

**Comment by darshankawar** [comment]
@4-alok 
Your question is better suited for support channels like StackOverflow, as this is more of a `how to` question rather than describing a bug or a feature request.
Closing from here. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by 4-alok** [comment]
Please reopen, I'm desperate for assistance. @darshankawar
