### ISSUE TITLE
[tool_crash] LateError: (#0      DartDevelopmentServiceImpl._server (package:dds/src/dds_impl.dart))

### ISSUE THREAD

**Issue by kerwin162** [flutter/flutter#86264]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --web-renderer html --web-hostname 10.10.9.234 --web-port 8989 --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
LateError: (#0      DartDevelopmentServiceImpl._server (package:dds/src/dds_impl.dart))
```
#0      DartDevelopmentServiceImpl._server (package:dds/src/dds_impl.dart)
#1      DartDevelopmentServiceImpl.shutdown (package:dds/src/dds_impl.dart:173:11)
#2      DartDevelopmentServiceImpl.startService.<anonymous closure> (package:dds/src/dds_impl.dart:86:11)
#3      _rootRunBinary (dart:async/zone.dart:1452:47)
#4      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:175:22)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#8      Future._completeError (dart:async/future_impl.dart:610:5)
#9      Future.wait.<anonymous closure> (dart:async/future.dart:413:23)
#10     _rootRunUnary (dart:async/zone.dart:1436:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.4.0-1.0.pre.182, on Deepin 20.2.2 5.10.36-amd64-desktop, locale zh_CN.UTF-8)
    • Flutter version 2.4.0-1.0.pre.182 at /home/jinglong/Program/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2175e64e4f (2 小时前), 2021-07-11 18:36:30 -0700
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/jinglong/Program/Android/Studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.57.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.0/8,::1
    ! NO_PROXY does not contain 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
file_picker-3.0.3
flutter_inappwebview-5.3.2
flutter_keyboard_visibility-5.0.2
flutter_keyboard_visibility_web-2.0.0
flutter_plugin_android_lifecycle-2.0.2
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
searchable_dropdown-1.1.3
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
webview_flutter-2.0.9

**Comment by darshankawar** [comment]
I don't see a similar issue or stacktrace, so labeling as applicable.

**Comment by yjbanov** [comment]
This likely doesn't happen any more.
