### ISSUE TITLE
[tool_crash] ProcessException: No such file or directory Command: /home/ishimwe/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub, OS error code: 2

### ISSUE THREAD

**Issue by Divin17** [flutter/flutter#86287]
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: No such file or directory Command: /home/ishimwe/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/pub, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymou

**Comment by asashour** [comment]
Duplicate of #86020 and #86214

**Comment by Divin17** [comment]
Thx
