### ISSUE TITLE
[palette_generator] Incorrect region scaling when resizing changes the aspect ratio of the image 

### ISSUE THREAD

**Issue by felix-oq** [flutter/flutter#86281]
When using the `PaletteGenerator.fromImageProvider(...)` function, the passed region is not processed correctly if the image size changes the aspect ratio of the original image. It could also generate errors that the region is outside the image, even though the region fits into the resized image.

An example for reproducing the bug with an ImageProvider that provides an image with a resolution of 600x400:
```
var _paletteGenerator = await PaletteGenerator.fromImageProvider(
      _imageProvider,
      size: Size(100, 100),
      region: Rect.fromCircle(
          center: Offset(50, 50),
          radius: 25),
    );
```
In this example, the image is resized from an aspect ratio of 3:2 to an aspect ratio of 1:1. The provided region fits into the resized image but the function call yields an AssertionError stating, that the provided region is outside the image.

The error is due to the region scaling in palette_generator.dart:
```
final double scale = image.width / size.width;
      newRegion = Rect.fromLTRB(
        region.left * scale,
        region.top * scale,
        region.right * scale,
        region.bottom * scale,
      );
```
There the region scaling is done using just a single scaling factor that is determined using only the width of the image. To resolve this bug, a second scaling factor would be needed that additionally accounts for the height of the image.

**Comment by darshankawar** [comment]
@felix-oq 
Ran the plugin's official [example](https://pub.dev/packages/palette_generator/example) and added your code snippet above, which resulted in below exception:

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: 'package:palette_generator/palette_generator.dart': Failed assertion: line 109 pos 9: 'region == null ||
            (region.bottomRight.dx <= image.width &&
                region.bottomRight.dy <= image.height)': Region Rect.fromLTRB(175.0, 175.0, 525.0, 525.0) is outside the image 700x366
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      PaletteGenerator.fromImage (package:palette_generator/palette_generator.dart:109:9)
#3      PaletteGenerator.fromImageProvider (package:palette_generator/palette_generator.dart:209:29)
<asynchronous suspension>
#4      _ImageColorsState._updatePaletteGenerator (package:kids/main.dart:83:24)
<asynchronous suspension>
```

Is this the exception you are talking about ?

**Comment by felix-oq** [comment]
Yes, exactly, that is the exception.
