### ISSUE TITLE
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 259 pos 16: 'child == null || indexOf(child) > index': is not true.

### ISSUE THREAD

**Issue by wanghuasheng** [flutter/flutter#86401]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Listener:
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 259 pos 16: 'child == null || indexOf(child) > index': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  SmartRefresher file:///Users/apple/workspace/app/packages/common/lib/src/bloc/widgets/pull_to_load.dart:94:23
When the exception was thrown, this was the stack: 
#2      RenderSliverMultiBoxAdaptor._debugVerifyChildOrder (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:259:16)
#3      RenderSliverMultiBoxAdaptor.debugChildIntegrityEnabled=.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:234:14)
#4      RenderSliverMultiBoxAdaptor.debugChildIntegrityEnabled= (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:236:6)
#5      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1125:20)
#6      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1055:7)
...
====================================================================================================

```

**Comment by darshankawar** [comment]
@wanghuasheng 
Please provide `flutter doctor -v` and a complete minimal reproducible code sample to properly address this issue.
Also you can do google search using the error you are getting to see if they help.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
