### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for /Users/muhammadrizwan/flutter/bin/cache/artifacts/engine/android-arm64-release/darwin-x64/gen_snapshot.

### ISSUE THREAD

**Issue by muhammadrizwaan** [flutter/flutter#86442]
## Command
```
flutter --quiet assemble --depfile /Users/muhammadrizwan/Flutter Projects/truckoom_freelance/build/app/intermediates/flutter/release/flutter_build.d --output /Users/muhammadrizwan/Flutter Projects/truckoom_freelance/build/app/intermediates/flutter/release -dTargetFile=/Users/muhammadrizwan/Flutter Projects/truckoom_freelance/lib/main.dart -dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true --DartDefines=flutter.inspector.structuredErrors%3Dtrue android_aot_bundle_release_android-arm64
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/muhammadrizwan/flutter/bin/cache/artifacts/engine/android-arm64-release/darwin-x64/gen_snapshot.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:124:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:40:30)
#2      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#3      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#4      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#5      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#6      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#7      GenSnapshot.run (package:flutter_tools/src/base/build.dart:73:26)
#8      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:56)
#9      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:232:52)
#10     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
<asynchronous suspension>
#11     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#12     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
<asynchronous suspension>
#13     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
<asynchronous suspension>
#14     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/muhammadrizwan/flutter
    • Framework revision b1395592de (3 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/muhammadrizwan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • RMX2020 (mobile) • TSI7FM4T4DBMAQEE • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.7.3+73
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f30b7f4db93ee747cd727df747941a28ead25ff5
### Plugins
cloud_firestore-0.12.11
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
device_info-0.4.2+10
esys_flutter_share-1.0.2
ext_storage-1.0.3
firebase_analytics-5.0.16
firebase_analytics_web-0.1.1
firebase_auth-0.14.0+9
firebase_core-0.4.5
firebase_core_web-0.1.1+2
firebase_messaging-6.0.16
flutter_absolute_path-1.0.6
flutter_downloader-1.5.2
flutter_local_notifications-4.0.1+2
flutter_native_image-0.0.5+3
flutter_plugin_android_lifecycle-1.0.11
fluttertoastalert-1.0.3
geocoder-0.2.1
geolocator-4.0.3
google_api_availability-2.0.4
google_maps_flutter-0.5.33
image_picker-0.6.7+21
location-3.0.2
location_permissions-2.0.5
location_web-1.0.0
multi_image_picker-4.7.14
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
permission-0.1.7
permission_handler-4.4.0
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by darshankawar** [comment]
@muhammadrizwaan 
This issue was fixed as part of https://github.com/flutter/flutter/issues/68475.
I recommend you to upgrade to latest stable (2.2.3) or latest master and try again to see it work properly.

Closing as this is already fixed. If after upgrading to latest versions, you still see the issue, write in comments and I'll reopen.
