### ISSUE TITLE
[tool_crash] ClientException

### ISSUE THREAD

**Issue by MRJNLCN** [flutter/flutter#86451]
## Command
```
flutter run --machine --start-paused -d ddda659b205ecec53ea1e2360e31c0f0786f2749 --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ClientException
```
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:49:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:45:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:272:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:712:16)
#5      _rootRunBinary (dart:async/zone.dart:1378:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#12     _addErrorWithReplacement (dart:async/stream_pipe.dart:176:8)
#13     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:277:11)
#14     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#15     _rootRunBinary (dart:async/zone.dart:1378:47)
#16     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#17     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#18     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#19     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#20     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#21     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#22     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#23     _StreamController.addError (dart:async/stream_controller.dart:569:5)
#24     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1183:22)
```
```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1217 darwin-x64, locale tr-AZ)
    • Flutter version 2.2.3 at /Users/aljan/Developer/flutter
    • Framework revision f4abaa0735 (13 g"un "once), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/aljan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • Mansur iPhone (mobile) • ddda659b205ecec53ea1e2360e31c0f0786f2749 • ios            • iOS 14.4.2
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 91.0.4472.114

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 9b2d32b605630f28625709ebd9d78ab3016b2bf6
### Plugins
camera-0.8.1+3
firebase_core-1.3.0
firebase_core_web-1.1.0
firebase_messaging-10.0.3
firebase_messaging_web-2.0.2
flutter_ffmpeg-0.4.0
flutter_local_notifications-6.0.0
flutter_plugin_android_lifecycle-2.0.2
flutter_secure_storage-4.2.0
image_picker-0.8.1+3
image_picker_for_web-2.0.0
package_info_plus-1.0.3
package_info_plus_macos-1.1.1
package_info_plus_web-1.0.2
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.0
photo_manager-1.2.5
sentry_flutter-5.1.0
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
VideoCompress-583e7003db41f205c7d5de3f5a5eb24934fb3fc0
video_player-2.1.9
video_player_web-2.0.1
video_thumbnail-0.3.3
wakelock-0.5.2
wakelock_macos-0.1.0+1
wakelock_web-0.2.0+1

**Comment by darshankawar** [comment]
@MRJNLCN 
This issue was fixed and merged into master, #73356
Please switch to latest master and try the same command again to see if it works or issue still persists.

```
flutter channel master
flutter upgrade
flutter run --machine --start-paused -d ddda659b205ecec53ea1e2360e31c0f0786f2749 --dart-define=flutter.inspector.structuredErrors=true --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --target lib/main.dart
```

Closing this for now as this is already fixed. If after switching to latest master you see the same issue again, write in comments and I'll reopen it.
