### ISSUE TITLE
Crash on flutter run

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#8661]
```
03-08 14:20:42.132 31820 31820 D AndroidRuntime: Shutting down VM
03-08 14:20:42.133 31820 31820 E AndroidRuntime: FATAL EXCEPTION: main
03-08 14:20:42.133 31820 31820 E AndroidRuntime: Process: com.google.fuchsia.armadillo, PID: 31820
03-08 14:20:42.133 31820 31820 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application org.domokit.sky.shell.SkyApplication: java.lang.ClassNotFoundException: Didn't find class "org.domokit.sky.shell.SkyApplication" on path: DexPathList[[zip file "/data/app/com.google.fuchsia.armadillo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.fuchsia.armadillo-2/lib/arm, /system/fake-libs, /data/app/com.google.fuchsia.armadillo-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5335)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.domokit.sky.shell.SkyApplication" on path: DexPathList[[zip file "/data/app/com.google.fuchsia.armadillo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.fuchsia.armadillo-2/lib/arm, /system/fake-libs, /data/app/com.google.fuchsia.armadillo-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
03-08 14:20:42.133 31820 31820 E AndroidRuntime: 	... 9 more
03-08 14:20:42.135   501   740 W ActivityManager:   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
03-08 14:20:42.183   501  4820 I OpenGLRenderer: Initialized EGL, version 1.4
03-08 14:20:42.183   501  4820 D OpenGLRenderer: Swap behavior 2
03-08 14:20:42.637   501   515 W ActivityManager: Activity pause timeout for ActivityRecord{6003a04 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity t586 f}
03-08 14:20:42.649   501   515 I WindowManager: Failed to capture screenshot of Token{2de1bed ActivityRecord{6003a04 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity t586 f}} appWin=Window{722c59c u0 Starting com.google.fuchsia.armadillo} drawState=3
03-08 14:20:42.698 30933 30933 I MicroDetector: Keeping mic open: false
03-08 14:20:42.699 30933 31499 I AudioController: internalShutdown
03-08 14:20:42.699 30933 31499 I MicrophoneInputStream: mic_close com.google.android.apps.gsa.speech.audio.af@26a840d
03-08 14:20:42.699 30933 30986 I MicroRecognitionRunner: Stopping hotword detection.
03-08 14:20:42.699 30933 31236 E AudioRecord-JNI: Error -4 during AudioRecord native read
03-08 14:20:42.701 30933 30960 I DeviceStateChecker: DeviceStateChecker cancelled
03-08 14:20:42.708   501   523 I WindowManager: Destroying surface Surface(name=Starting com.google.fuchsia.armadillo) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.WindowManagerService.removeWindow:2300 com.android.server.wm.Session.remove:193 
03-08 14:20:42.729   243   340 I SoundTriggerHwService::Module: void android::SoundTriggerHwService::Module::onCallbackEvent(const sp<android::SoundTriggerHwService::CallbackEvent> &) mClient == 0

```

**Comment by apwilson** [comment]
I didn't have android studio installed.  It was suggested that installing it would fix the issue.  It did not.  Here's my flutter doctor output:

```
[130] ~/fuchsia/apps/sysui/armadillo$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at ~/fuchsia/lib/flutter
    • Framework revision 906103dd10 (71 minutes ago), 2017-03-08 13:33:06
    • Engine revision 6e54f5e31f
    • Tools Dart version 1.23.0-dev.2.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at ~/android-sdk-linux
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = ~/android-sdk-linux
    • OpenJDK Runtime Environment (build 1.8.0_112-google-v7-146844476-143772575)

[✓] Android Studio (version 2.3)
    • Android Studio at ~/Downloads/android-studio
    • Gradle version 3.2

[✓] Connected devices
    • Pixel C • 5A17000207 • android-arm • Android 7.0 (API 24)
```

**Comment by eseidelGoogle** [comment]
SkyApplication was recently removed.  Presumably the java side of your app needs an update?

@jason-simmons or @chinmaygarde might know?

**Comment by eseidelGoogle** [comment]
Looks like it did: https://github.com/flutter/engine/commit/6e54f5e31f084d2e54a510959f68b89e4d2fdffd

**Comment by Hixie** [comment]
`rm -rf android; cd ..; flutter create <dirname>` fixed it

**Comment by chinmaygarde** [comment]
Can we close this ticket if the `create` updated the template?

**Comment by Hixie** [comment]
At some point we should probably improve our error handling for this kind of situation, but we probably have other bugs tracking that so sure.
