### ISSUE TITLE
[video_player] PlatformException(NPE) when playing video from assets just after initialization

### ISSUE THREAD

**Issue by Silver-Fullbuster** [flutter/flutter#86705]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
	-  Add any video file to assets folder (`assets/videos/intro_closeup.mp4`)
	- Update pubspec to use `video_player: 2.1.10`
	- Add `assets/videos/` folder in pubspec 
	- Update `main.dart` to the following:

<details>
<summary>main.dart</summary>

```Dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: OnBoardScreen(),
    );
  }
}

class OnBoardScreen extends StatefulWidget {
  @override
  _OnBoardScreenState createState() => _OnBoardScreenState();
}

class _OnBoardScreenState extends State<OnBoardScreen> {
  late VideoPlayerController _controller;

  bool pushed = false;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/videos/intro_closeup.mp4')
      ..initialize().then((_) => setState(() {}));
    _controller.setLooping(false);
    _controller.addListener(() {
      if (_controller.value.isInitialized && !_controller.value.isPlaying) {
        if (!pushed) {
          pushed = true;
          Navigator.of(context).pushReplacement(
            CupertinoPageRoute(
              builder: (context) => MyHomePage(),
            ),
          );
        }
      }
    });
    _controller.play();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: null,
      backgroundColor: Color(0xFF212121),
      body: Center(
        child: _controller.value.isInitialized
            ? AspectRatio(
                aspectRatio: _controller.value.aspectRatio,
                child: VideoPlayer(_controller),
              )
            : Container(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Bug Test"),
      ),
    );
  }
}
```

</details>

3. Run the app

**Expected results:** 

Video player plays the whole video, and then shifts to next screen

**Actual results:** 

Video shows 1 frame for a moment and shift to the next screen
`video_player: 2.1.9` works without issues

<details>
  <summary>Logs</summary>

Runtime Logs:
```
E/flutter (13076): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugins.videoplayer.VideoPlayer.seekTo(int)' on a null object reference, null, null)
E/flutter (13076): #0      VideoPlayerApi.seekTo (package:video_player_platform_interface/messages.dart:365:7)
E/flutter (13076): <asynchronous suspension>
E/flutter (13076): #1      VideoPlayerController.seekTo (package:video_player/video_player.dart:502:5)
E/flutter (13076): <asynchronous suspension>
E/flutter (13076): #2      VideoPlayerController.play (package:video_player/video_player.dart:398:7)
E/flutter (13076): <asynchronous suspension>
E/flutter (13076): 

```

flutter doctor -v
```
C:\Users\Mehul\GithubProjects\video_2_1_10_test>flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1052], locale en-IN)
    • Flutter version 2.2.3 at C:\Users\Mehul\flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Mehul\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (3 available)
    • Pixel 4a (mobile) • 14051JEC200964 • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 91.0.864.70

• No issues found!
```

</details>

**Comment by hamdikahloun** [comment]
Hi @Silver-Fullbuster 
Can you add please `assets/videos/video.mp4` in `pubspec`.

```
  assets:
   - assets/videos/video.mp4
```

**Comment by Silver-Fullbuster** [comment]
I'd like to clarify I used a different filename in my code, my video file in assets is `assets/videos/intro_closeup.mp4`

No change in behaviour after adding `assets/videos/intro_closeup.mp4` in `pubspec.yaml`:

2,1,10 still immediately errors after showing first frame of video
2,1,9 works without issues

**Comment by maheshmnj** [comment]
Hi @Silver-Fullbuster, 
From your code I could see that you are trying to play a video before its initialized, I modified the initState like this and it works fine.

```
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/video/chromecast.mp4')
      ..initialize().then((_) {
        setState(() {});
        _controller.play();
        _controller.setLooping(false);
        _controller.addListener(() {
          if (_controller.value.isInitialized && !_controller.value.isPlaying) {
            if (!pushed) {
              pushed = true;
              Navigator.of(context).pushReplacement(
                CupertinoPageRoute(
                  builder: (context) => MyHomePage(),
                ),
              );
            }
          }
        });
      });
  }
```  

As an alternative I would recommend to detect completion of video like this 

```
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/video/chromecast.mp4')
      ..initialize().then((_) {
        setState(() {});
        _controller.play();
        _controller.setLooping(false);
        _controller.addListener(() {
          final isCompleted =
              _controller.value.position == _controller.value.duration;
          if (isCompleted) {
            print('video ended do something now');
            Navigator.of(context).pushReplacement(
              CupertinoPageRoute(
                builder: (context) => MyHomePage(),
              ),
            );
          }
        });
      });
  }
  ```
I am going to close this issue as invalid if you disagree feel free to comment and I will reopen it.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS
      11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 91.0.4472.164

• No issues found!
```
</details>

Thank you.
