### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by Steadyoung** [flutter/flutter#86848]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=05157df5bc8ca33e --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:221:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:220:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:137:53)
#7      AndroidPlugin._supportedEmbedings (package:flutter_tools/src/platform_plugins.dart:91:70)
#8      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:83:30)
#9      _extractPlatformMaps (package:flutter_tools/src/plugins.dart:606:40)
#10     _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:622:5)
#11     injectPlugins (package:flutter_tools/src/plugins.dart:1202:11)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:322:5)
<asynchronous suspension>
#13     FlutterComman

**Comment by maheshmnj** [comment]
Hi @Steadyoung, 
Thanks for filing the issue, Please provide the output of flutter doctor -v along with [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), This helps to better investigate the issue.

Thank you.

**Comment by maheshmnj** [comment]
@Steadyoung there is already a similar issue describing this case https://github.com/flutter/flutter/issues/86848, You may follow up there for further updates. Closing this issue as a duplicate if you disagree feel free to comment and I will reopen it.

Thank you.
