### ISSUE TITLE
image_picker doesn't work in release mode

### ISSUE THREAD

**Issue by Finn1510** [flutter/flutter#86878]
Image_picker works fine in debug mode (connected to a real device:
Poco F2 Pro MIUI 12.5 Android 11).
However it doesnt work if I do flutter run --release or if I build a release apk. 
the Error that always pops op is the following: 

```
[+14311 ms] E/flutter (18149): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
[   +1 ms] E/flutter (18149):   at java.util.Objects.requireNonNull(Objects.java:220)
[   +1 ms] E/flutter (18149):   at java.util.Arrays$ArrayList.<init>(Arrays.java:3738)
[        ] E/flutter (18149):   at java.util.Arrays.asList(Arrays.java:3725)
[   +1 ms] E/flutter (18149):   at io.flutter.plugins.imagepicker.f.a(Unknown Source:16)
[   +1 ms] E/flutter (18149):   at io.flutter.plugins.imagepicker.f.b(Unknown Source:15)
[        ] E/flutter (18149):   at io.flutter.plugins.imagepicker.e$a.a(Unknown Source:2)
[        ] E/flutter (18149):   at io.flutter.plugins.imagepicker.e.D(Unknown Source:6)
[        ] E/flutter (18149):   at io.flutter.plugins.imagepicker.e.I(Unknown Source:10)
[   +1 ms] E/flutter (18149):   at io.flutter.plugins.imagepicker.ImagePickerPlugin.g(Unknown Source:236)
[   +1 ms] E/flutter (18149):   at c.a.c.a.i$a.a(Unknown Source:17)
[   +1 ms] E/flutter (18149):   at io.flutter.embedding.engine.e.b.c(Unknown Source:57)
[   +1 ms] E/flutter (18149):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
[   +1 ms] E/flutter (18149):   at android.os.MessageQueue.nativePollOnce(Native Method)
[   +3 ms] E/flutter (18149):   at android.os.MessageQueue.next(Unknown Source:17)
[   +1 ms] E/flutter (18149):   at android.os.Looper.loop(Unknown Source:77)
[   +1 ms] E/flutter (18149):   at android.app.ActivityThread.main(Unknown Source:101)
[        ] E/flutter (18149):   at java.lang.reflect.Method.invoke(Native Method)
[   +1 ms] E/flutter (18149):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
[        ] E/flutter (18149):   at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
[   +1 ms] E/flutter (18149): )
[        ] E/flutter (18149): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
[        ] E/flutter (18149): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
[        ] E/flutter (18149): <asynchronous suspension>
[        ] E/flutter (18149): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188)
[   +1 ms] E/flutter (18149): <asynchronous suspension>
[        ] E/flutter (18149): #3      _AddBookPageState.getImage (package:booktimeline/addBook.dart:204)
[        ] E/flutter (18149): <asynchronous suspension>
[        ] E/flutter (18149):
```

it pops up everytime I click my "get image from gallery" or get image from camera" button. 

Full log is here (copied from vscode debug console while running "flutter run --release -v):
[log.txt](https://github.com/flutter/flutter/files/6863668/log.txt)

My AndroidMainfest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.booktimeline">
    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
    </queries>
   
   <application
        android:label="booktimeline"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
        
        
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

results of "flutter doctor -v" : 
```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.685], locale de-DE)
    • Flutter version 2.2.3 at E:\_flutter\src\flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)      
    • Android SDK at C:\Users\flipg\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\AdoptOpenJDK\jdk-11.0.10.9-hotspot\bin\java.exe
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio
    • Android Studio at E:\programme\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X android-studio-dir = E:\programme\AndroidStudio
    X Android Studio not found at E:\programme\AndroidStudio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\flipg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • Redmi K30 Pro (mobile) • 9f4fe6f • android-arm64  • Android 11 (API 30)
    • Chrome (web)           • chrome  • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)             • edge    • web-javascript • Microsoft Edge 91.0.864.71


```

**Comment by maheshmnj** [comment]
Hi @Finn1510, Thanks for filing the issue, I am able to reproduce the issue while picking the image via camera on the latest stable channel, but not on the master channel with the latest ```image_picker: ^0.8.2```, The plugin works fine on the master channel in release mode.
You may switch to the latest master channel  by running 

```
flutter channel master
flutter upgrade
```

until the fix lands on the stable channel.


<details>
<summary>code sample</summary>

```
import 'dart:io';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter ImagePicker Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _increment() {}

  Widget imageBuilder(File file, int index) {
    if (file != null && file.path.isNotEmpty) {
      return Image.file(
        File(
          file.path,
        ),
        fit: BoxFit.cover,
      );
    } else {
      return imagePlaceHolder(index);
    }
  }

  Future<XFile?> pickImage(ImageSource source) async {
    final image = await _picker.pickImage(
        source: source,
        maxWidth: 800,
        maxHeight: 800,
        preferredCameraDevice: CameraDevice.rear);
    return image;
  }

  Widget imagePlaceHolder(int index) {
    return Container(
      // padding: EdgeInsets.only(right),
      alignment: Alignment.center,
      decoration: BoxDecoration(
        border: Border(
            right: index % 2 == 0 ? BorderSide() : BorderSide.none,
            bottom: BorderSide()),
      ),
      child: Icon(Icons.add_a_photo),
    );
  }

  final _picker = ImagePicker();

  List<File> images = [];

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    List.generate(4, (x) => images.add(File('')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: GridView.builder(
                itemCount: 4,
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2),
                itemBuilder: (context, index) => GestureDetector(
                    onTap: () async {
         
                      final image = await pickImage(
                           ImageSource.camera);
                      setState(() {
                        images[index] = File(image!.path);
                      });
                    },
                    child: imageBuilder(images[index], index)),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>logs</summary>

```
E/flutter (30519): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (30519):      at java.util.Objects.requireNonNull(Objects.java:220)
E/flutter (30519):      at java.util.Arrays$ArrayList.<init>(Arrays.java:3738)
E/flutter (30519):      at java.util.Arrays.asList(Arrays.java:3725)
E/flutter (30519):      at io.flutter.plugins.imagepicker.f.a(Unknown Source:16)
E/flutter (30519):      at io.flutter.plugins.imagepicker.f.a(Unknown Source:15)
E/flutter (30519):      at io.flutter.plugins.imagepicker.e$a.a(Unknown Source:2)
E/flutter (30519):      at io.flutter.plugins.imagepicker.e.j(Unknown Source:6)
E/flutter (30519):      at io.flutter.plugins.imagepicker.e.d(Unknown Source:10)
E/flutter (30519):      at io.flutter.plugins.imagepicker.ImagePickerPlugin.a(Unknown Source:245)
E/flutter (30519):      at b.a.c.a.i$a.a(Unknown Source:17)
E/flutter (30519):      at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
E/flutter (30519):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (30519):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (30519):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (30519):      at android.os.Looper.loop(Looper.java:193)
E/flutter (30519):      at android.app.ActivityThread.main(ActivityThread.java:8061)
E/flutter (30519):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (30519):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/flutter (30519):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (30519): )
E/flutter (30519): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (30519): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #3      _MyHomePageState.pickImage (package:counter_app/main.dart:52)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #4      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:counter_app/main.dart:102)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): 
E/flutter (30519): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
E/flutter (30519): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (30519): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #3      _MyHomePageState.pickImage (package:counter_app/main.dart:52)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #4      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:counter_app/main.dart:102)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): 
E/flutter (30519): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
E/flutter (30519): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (30519): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #3      _MyHomePageState.pickImage (package:counter_app/main.dart:52)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #4      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:counter_app/main.dart:102)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): 
E/flutter (30519): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
E/flutter (30519): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (30519): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #3      _MyHomePageState.pickImage (package:counter_app/main.dart:52)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): #4      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:counter_app/main.dart:102)
E/flutter (30519): <asynchronous suspension>
E/flutter (30519): 
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS
      11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 91.0.4472.164

• No issues found!
```

```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.166, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.166 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2dc11a85ff (4 hours ago), 2021-07-22 17:56:03 -0700
    • Engine revision fbbb3b3f7b
    • Dart version 2.14.0 (build 2.14.0-343.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30)
      (emulator)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71
      darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      91.0.4472.164

• No issues found!
```
</details>

**Comment by Finn1510** [comment]
Hi @maheshmnj Thanks for replying that quick! I switched to the latest master channel but unfortunately I still get the same error as before. I also tried it with your code sample on a [different machine](https://github.com/flutter/flutter/files/6869612/doctor.txt.txt)
also running flutter master and still got the error.

**Comment by maheshmnj** [comment]
could you please paste the output of `flutter doctor -v` on your master channel.

**Comment by Finn1510** [comment]
output of `flutter doctor -v`
```
[√] Flutter (Channel master, 2.4.0-5.0.pre.181, on Microsoft Windows [Version 10.0.19042.685], locale de-DE)
    • Flutter version 2.4.0-5.0.pre.181 at E:\_flutter\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5478470d99 (3 days ago), 2021-07-24 14:38:05 -0400
    • Engine revision 05884794d2
    • Dart version 2.14.0 (build 2.14.0-350.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\flipg\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\flipg\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!
```

**Comment by maheshmnj** [comment]
@Finn1510 I am able to reproduce the issue on the latest master channel as well using Xiaomi k20 Pro in release mode. The app works fine in debug mode but while taking a picture via the camera in release mode the exception is thrown.

<details>
<summary>code sample</summary>

```
import 'dart:io';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter ImagePicker Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _increment() {}

  Widget imageBuilder(File file, int index) {
    if (file != null && file.path.isNotEmpty) {
      return Image.file(
        File(
          file.path,
        ),
        fit: BoxFit.cover,
      );
    } else {
      return imagePlaceHolder(index);
    }
  }

  Future<XFile?> pickImage(ImageSource source) async {
    final image = await _picker.pickImage(
        source: source,
        maxWidth: 800,
        maxHeight: 800,
        preferredCameraDevice: CameraDevice.rear);
    return image;
  }

  Widget imagePlaceHolder(int index) {
    return Container(
      // padding: EdgeInsets.only(right),
      alignment: Alignment.center,
      decoration: BoxDecoration(
        border: Border(
            right: index % 2 == 0 ? BorderSide() : BorderSide.none,
            bottom: BorderSide()),
      ),
      child: Icon(Icons.add_a_photo),
    );
  }

  final _picker = ImagePicker();

  List<File> images = [];

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    List.generate(4, (x) => images.add(File('')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: GridView.builder(
                itemCount: 4,
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2),
                itemBuilder: (context, index) => GestureDetector(
                    onTap: () async {
         
                      final image = await pickImage(
                           ImageSource.camera);
                      setState(() {
                        images[index] = File(image!.path);
                      });
                    },
                    child: imageBuilder(images[index], index)),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>Logs</summary>

```
q Quit (terminate the application on the device).
E/flutter (23676): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter (23676):      at java.util.Objects.requireNonNull(Objects.java:220)
E/flutter (23676):      at java.util.Arrays$ArrayList.<init>(Arrays.java:3738)
E/flutter (23676):      at java.util.Arrays.asList(Arrays.java:3725)
E/flutter (23676):      at io.flutter.plugins.imagepicker.f.a(Unknown Source:16)
E/flutter (23676):      at io.flutter.plugins.imagepicker.f.a(Unknown Source:15)
E/flutter (23676):      at io.flutter.plugins.imagepicker.e$a.a(Unknown Source:2)
E/flutter (23676):      at io.flutter.plugins.imagepicker.e.j(Unknown Source:6)
E/flutter (23676):      at io.flutter.plugins.imagepicker.e.d(Unknown Source:10)
E/flutter (23676):      at io.flutter.plugins.imagepicker.ImagePickerPlugin.a(Unknown Source:245)
E/flutter (23676):      at b.a.c.a.i$a.a(Unknown Source:17)
E/flutter (23676):      at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
E/flutter (23676):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (23676):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23676):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (23676):      at android.os.Looper.loop(Looper.java:193)
E/flutter (23676):      at android.app.ActivityThread.main(ActivityThread.java:8061)
E/flutter (23676):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23676):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/flutter (23676):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (23676): )
E/flutter (23676): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (23676): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #3      _ImagePickerSampleState.pickImage (package:counter_app/image_picker.dart:34)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #4      _ImagePickerSampleState.build.<anonymous closure>.<anonymous closure> (package:counter_app/image_picker.dart:83)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): 
E/flutter (23676): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
E/flutter (23676): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (23676): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #3      _ImagePickerSampleState.pickImage (package:counter_app/image_picker.dart:34)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #4      _ImagePickerSampleState.build.<anonymous closure>.<anonymous closure> (package:counter_app/image_picker.dart:83)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): 
E/flutter (23676): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
E/flutter (23676): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (23676): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #2      MethodChannelImagePicker.getImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:188)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #3      _ImagePickerSampleState.pickImage (package:counter_app/image_picker.dart:34)
E/flutter (23676): <asynchronous suspension>
E/flutter (23676): #4      _ImagePickerSampleState.build.<anonymous closure>.<anonymous closure> (package:counter_app/image_picker.dart:83)
E/flutter (23676): <asynchronous suspension>
```
</details>

**Comment by michaeltintiuc** [comment]
Are there any updates? Release builds seem to be still broken on both master and stable channels while debug ones work fine

**Comment by Finn1510** [comment]
yeah a while back after upgrading the package it started working for me again too
