### ISSUE TITLE
Ship apple silicon dart SDK binaries now that Dart 2.14.0-281.0.dev and higher have arm64 builds available for download

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#86926]
Hi- I have been following the apple silicon support progress for quite some time now. Just the other day the Dart team announced apple silicon arm64 builds are now available on the dev/beta channels: https://github.com/dart-lang/sdk/issues/42773#issuecomment-883430554

The latest flutter dev channel `2.4.0-4.0.pre` is shipping dart `2.14.0-301.0.dev` which does have an arm64 build available:

<img width="924" alt="Screen Shot 2021-07-23 at 5 43 06 AM" src="https://user-images.githubusercontent.com/9597207/126764815-b575c622-d70c-4167-8d14-033a75560512.png">

But Flutter is still shipping just the x86_64 binary:
```
➜ file ~/Projects/flutter/bin/cache/dart-sdk/bin/dart
/Users/andrewcoutts/Projects/flutter/bin/cache/dart-sdk/bin/dart: Mach-O 64-bit executable x86_64
```

Here's how the `file` command output looks for a native AS arm64 binary:
```
➜ file /Applications/Docker.app/Contents/MacOS/Docker 
/Applications/Docker.app/Contents/MacOS/Docker: Mach-O 64-bit executable arm64
```

Related (but unable to comment): https://github.com/flutter/flutter/issues/60118

**Comment by Dararii** [comment]
Any update on this issue?

**Comment by bichoalexis** [comment]
Same issue here! I couldn't found any solution yet 🥺

**Comment by acoutts** [comment]
@chinmaygarde is it trivial to build our own engine that would use the AS binary for dart? Seems like we would just need to check `uname -m` in the flutter dart bash script, and if it returns `arm64` then point to that binary to execute.

**Comment by acoutts** [comment]
If anyone has a workaround we can use in the meantime, I would be happy to try it out. There are issues running unit tests with the intel binaries using rosetta, where some tests fail:

```
TestDeviceException(Shell subprocess crashed with unexpected exit code -5.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:224:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:206:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:486:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:539:11)
<asynchronous suspension>
```

Because of this I need to always run my test suite on an intel mac to be sure it's passing.

**Comment by acoutts** [comment]
Are there any estimates for when we can plan to expect this?

**Comment by bichoalexis** [comment]
Flutter 2.5.0 is supposed to run dart with arm64 support but I'm still having the same problem, were you able to solve it?

**Comment by acoutts** [comment]
That’s just for the simulator running in native apple silicon, not the dart build command(s).

**Comment by bichoalexis** [comment]
Oh that was disappointed, I understood wrong thanks of this topic [https://medium.com/dartlang/announcing-dart-2-14-b48b9bb2fb67](url) ☹️ I hope they will add dart support soon.

**Comment by acoutts** [comment]
Thanks. So the issue seems to be that we have the build the flutter engine from an arm64 mac, but as per my issue here I was unable to build it following the engine wiki. https://github.com/dart-lang/sdk/issues/47511

So this is not as simple as including some pre-built dart binaries like I thought when submitting this issue.

@dnfield would it be worth me filing a separate issue about being unable to build the flutter engine on an apple silicon mac, or does that fall under this issue of making it available for download?

**Comment by dnfield** [comment]
@zanderso would know

**Comment by jmagman** [comment]
Reopening and making this a subtask of #60118.

Work on this is ongoing:
https://github.com/flutter/flutter/pull/97278

**Comment by Sunbreak** [comment]
Apple Silicon Dart SDK is available since [flutter-2.11-candidate.7](https://github.com/flutter/flutter/tree/flutter-2.11-candidate.7)

```sh
% ./bin/flutter --version
Flutter 2.10.0-1.0.pre.345 • channel flutter-2.11-candidate.7 • https://github.com/flutter/flutter
Framework • revision a0abb7e89e (3 days ago) • 2022-01-31 16:05:20 -0500
Engine • revision 800afbf27a
Tools • Dart 2.17.0 (build 2.17.0-69.0.dev) • DevTools 2.10.0-dev.1
% file bin/cache/dart-sdk/bin/dart
bin/cache/dart-sdk/bin/dart: Mach-O 64-bit executable arm64
```

**Comment by anzbert** [comment]
> Apple Silicon Dart SDK is available since [flutter-2.11-candidate.7](https://github.com/flutter/flutter/tree/flutter-2.11-candidate.7)
> 
> ```shell
> % ./bin/flutter --version
> Flutter 2.10.0-1.0.pre.345 • channel flutter-2.11-candidate.7 • https://github.com/flutter/flutter
> Framework • revision a0abb7e89e (3 days ago) • 2022-01-31 16:05:20 -0500
> Engine • revision 800afbf27a
> Tools • Dart 2.17.0 (build 2.17.0-69.0.dev) • DevTools 2.10.0-dev.1
> % file bin/cache/dart-sdk/bin/dart
> bin/cache/dart-sdk/bin/dart: Mach-O 64-bit executable arm64
> ```

hey thx. that totally worked!
i guess i'll just follow the latest 2.11 release candidates now to get native apple silicon support :)
at least until 2.11 is released or M1 support is in the beta.

**Comment by zanderso** [comment]
@Sunbreak @anzbert I think `flutter upgrade` will get you the right bits, but there's some more infra work needed (https://github.com/flutter/flutter/issues/97658) to get the arm64 Dart SDK into the Flutter SDK archives on the website. Thanks for your patience.

**Comment by anzbert** [comment]
I see what you mean. I've tried using the 2.11 release candidate, which
shows as an apple process in the activity monitor. But android debugs
resulted in crashes, which is why I am back with 2.10 until the apple
builds become more stable.

Thx for all the great work!

**Comment by zanderso** [comment]
@anzbert Please file new issues for any crashers you're seeing in 2.11. Thanks!

**Comment by Sunbreak** [comment]
Shipped on beta channel now: https://github.com/flutter/flutter/releases/tag/2.11.0-0.1.pre

**Comment by anzbert** [comment]
hmm i still get plenty of intel processes in the 2.11 beta in the activity monitor.

running flutter-2.11-candidate.11 at the moment and that is only using apple processes and works fine for me.

**Comment by Sunbreak** [comment]
```sh
wangkun42@wangkun42s-MacBook-Pro flutter-beta % git log -1
commit b101bfe32f634566e7cb2791a9efe19cf8828b15 (HEAD -> beta, tag: 2.11.0-0.1.pre, origin/flutter-2.11-candidate.7, origin/dev, origin/beta)
Author: godofredoc <godofredoc@google.com>
Date:   Wed Feb 16 07:36:54 2022 -0800

    'Update Engine revision to e3559935720ea88dfcdf9079c394ffdb5146ceab for beta release 2.11.0-0.1.pre' (#98561)
```
```
wangkun42@wangkun42s-MacBook-Pro flutter-beta % file bin/cache/dart-sdk/bin/dart
bin/cache/dart-sdk/bin/dart: Mach-O 64-bit executable arm64
```
```
wangkun42@wangkun42s-MacBook-Pro flutter-beta % bin/cache/dart-sdk/bin/dart --version
Dart SDK version: 2.17.0-69.2.beta (beta) (Mon Feb 14 13:41:58 2022 +0100) on "macos_arm64"
```

@anzbert You'd better close any IDE or process using Dart Language Server and start with the new Dart SDK

**Comment by anzbert** [comment]
i think that did it. i just rebooted and switched channel again + flutter upgrade . thx @Sunbreak  !!

**Comment by jmagman** [comment]
@zanderso this is done, right? Or did you want to wait until it's reached stable?
![Screen Shot 2022-03-30 at 10 24 16 AM](https://user-images.githubusercontent.com/682784/160894955-5141fa37-bf52-4af6-805b-dd31dd3dc029.png)
