### ISSUE TITLE
TextField - exception on deleting last char

### ISSUE THREAD

**Issue by zs-dima** [flutter/flutter#87017]
`TextField` fires exception on deleting last char.

## Steps to Reproduce

1. Run app on Android Emulator with `TextField` widget.
  (`TextField` could use `TextEditingController` or `onChanged` - any way same issue appear)
2. Enter any text into the `TextField`
3. Delete entered text by pressing `Backspace` continuously
4. When you will delete last char exception appear:
(and on next `TextField` focus last char will appear again)

**Actual results:**
```
E/MethodChannel#flutter/textinput( 5945): Failed to handle method call
E/MethodChannel#flutter/textinput( 5945): java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)
E/MethodChannel#flutter/textinput( 5945): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:726)
E/MethodChannel#flutter/textinput( 5945): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:693)
E/MethodChannel#flutter/textinput( 5945): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:99)
E/MethodChannel#flutter/textinput( 5945): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput( 5945): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter/textinput( 5945): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:819)
E/MethodChannel#flutter/textinput( 5945): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput( 5945): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/textinput( 5945): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/textinput( 5945): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/textinput( 5945): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 5945): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/textinput( 5945): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter ( 5945): [E] PlatformException(error, invalid composing range: (0, 0), null, java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)
I/flutter ( 5945): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:726)
I/flutter ( 5945): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:693)
I/flutter ( 5945): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:99)
I/flutter ( 5945): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
I/flutter ( 5945): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
I/flutter ( 5945): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:819)
I/flutter ( 5945): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter ( 5945): 	at android.os.MessageQueue.next(MessageQueue.java:335)
I/flutter ( 5945): 	at android.os.Looper.loop(Looper.java:183)
I/flutter ( 5945): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
I/flutter ( 5945): 	at java.lang.reflect.Method.invoke(N
```

**Expected results:** 
1. On next `TextField` focus - last char will not appear.
2. Exception will not appear.

<details>

```
[√] Flutter (Channel dev, 2.4.0-4.0.pre, on Microsoft Windows [Version 10.0.19043.1110], locale ru-RU)
    • Flutter version 2.4.0-4.0.pre at c:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (2 weeks ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at c:\android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = c:\android\sdk
    • Java binary at: c:\Program Files\Java\jdk1.8.0_291\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.70
```

</details>

**Comment by maheshmnj** [comment]
Hi @zs-dima,
Thanks for filing the issue I am able to reproduce it on the latest master channel but not on the stable channel. when deleting the last character using the delete key on the computer's keyboard the `IndexOutOfBoundsException` is thrown. This exception isn't thrown with the emulator's keyboard.
 
 <details>
 <summary>logs</summary>
 
 ```
 W/IInputConnectionWrapper( 4361): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4361): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4361): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4361): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 4361): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4361): endBatchEdit on inactive InputConnection
E/MethodChannel#flutter/textinput( 4361): Failed to handle method call
E/MethodChannel#flutter/textinput( 4361): java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)
E/MethodChannel#flutter/textinput( 4361): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:726)
E/MethodChannel#flutter/textinput( 4361): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:693)
E/MethodChannel#flutter/textinput( 4361): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:99)
E/MethodChannel#flutter/textinput( 4361): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/textinput( 4361): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter/textinput( 4361): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:862)
E/MethodChannel#flutter/textinput( 4361): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/textinput( 4361): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/textinput( 4361): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/textinput( 4361): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/textinput( 4361): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/textinput( 4361): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/textinput( 4361): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 4361): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, invalid composing range: (0, 0), null, java.lang.IndexOutOfBoundsException: invalid composing range: (0, 0)
E/flutter ( 4361): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.<init>(TextInputChannel.java:726)
E/flutter ( 4361): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$TextEditState.fromJson(TextInputChannel.java:693)
E/flutter ( 4361): 	at io.flutter.embedding.engine.systemchannels.TextInputChannel$1.onMethodCall(TextInputChannel.java:99)
E/flutter ( 4361): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 4361): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter ( 4361): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:862)
E/flutter ( 4361): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 4361): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 4361): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 4361): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 4361): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4361): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 4361): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 4361): )
E/flutter ( 4361): #0      JSONMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:164
E/flutter ( 4361): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter ( 4361): <asynchronous suspension>
E/flutter ( 4361):
 ```
 </details>
 
 <details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.164

• No issues found!
```

```
[✓] Flutter (Channel master, 2.4.0-5.0.pre.166, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.166 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2dc11a85ff (4 hours ago), 2021-07-22 17:56:03 -0700
    • Engine revision fbbb3b3f7b
    • Dart version 2.14.0 (build 2.14.0-343.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30)
      (emulator)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71
      darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      91.0.4472.164

• No issues found!
```
</details>

**Comment by zs-dima** [comment]
@maheshmnj thanks for looking into
I reproduced this issue with Dev channel on Android emulator

**Comment by zs-dima** [comment]
@maheshmnj 
> I reproduced this issue with Dev channel
you could see `flutter doctor -v` details I provided in the issue `Details`

**Comment by HansMuller** [comment]
CC @justinmc

**Comment by blasten** [comment]
The range 0, 0 is valid. Only -1 is documented as a bad state. https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/text/SpannableStringBuilder.java;l=818;drc=master?q=getSpanStart&ss=android%2Fplatform%2Fsuperproject
