### ISSUE TITLE
ReorderableListView throws NPE if any it's child has height > container height

### ISSUE THREAD

**Issue by eugene-kalaganov** [flutter/flutter#87093]
There are only two items but it doesn't matter. If any item has height bigger scrollable area after reordering it throws en error:
```
======== Exception caught by gesture library =======================================================
The following _CastError was thrown while routing a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      SliverReorderableListState._itemOffsetAt (package:flutter/src/widgets/reorderable_list.dart:801:51)
#1      SliverReorderableListState._dragEnd.<anonymous closure> (package:flutter/src/widgets/reorderable_list.dart:636:32)
#2      State.setState (package:flutter/src/widgets/framework.dart:1088:30)
#3      SliverReorderableListState._dragEnd (package:flutter/src/widgets/reorderable_list.dart:624:5)
#4      _DragInfo.end (package:flutter/src/widgets/reorderable_list.dart:1150:12)
...
====================================================================================================
```
To reproduce it just start an example, hold on the first item and drag it down until items are switch positions.

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)

• No issues found!
```

```
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Home());
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final h = MediaQuery.of(context).size.height + 100;
    return Scaffold(
      appBar: AppBar(title: Text('ReorderableListView NPE')),
      body: ReorderableListView(
        onReorder: (p1, p2) {},
        children: [
          Container(
            key: Key('item 0'),
            height: 300,
            color: Colors.green,
          ),
          Container(
            key: Key('item 1'),
            height: h,
            color: Colors.red,
          ),
        ],
      ),
    );
  }
}
```
https://user-images.githubusercontent.com/15782257/127118098-6ba6d444-d3ba-4d05-b7bb-49f1e8b29098.mov

**Comment by darshankawar** [comment]
Verified on latest stable (2.2.3) and master (2.4.0-5.0.pre.202) and observed same exception:

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           42.4s
Debug service listening on ws://127.0.0.1:52523/EOe7aF4DJDc=/ws
Syncing files to device iPhone 12 Pro Max...

======== Exception caught by gesture library =======================================================
The following _CastError was thrown while routing a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      SliverReorderableListState._itemOffsetAt (package:flutter/src/widgets/reorderable_list.dart:801:51)
#1      SliverReorderableListState._dragEnd.<anonymous closure> (package:flutter/src/widgets/reorderable_list.dart:636:32)
#2      State.setState (package:flutter/src/widgets/framework.dart:1088:30)
#3      SliverReorderableListState._dragEnd (package:flutter/src/widgets/reorderable_list.dart:624:5)
#4      _DragInfo.end (package:flutter/src/widgets/reorderable_list.dart:1150:12)
...
====================================================================================================
```

The error doesn't occur in non null-safety version, ie, in `sdk: ">=2.7.0 <3.0.0"`
<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
This appears to be a problem with items getting kicked out of the cache because the big item fills the entire viewport. While I am not sure yet how to fix this in the framework, a possible workaround in the app is to set the `cacheExtent` on the list to be as large as the biggest item (if you know that ahead of time):

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Home());
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final h = MediaQuery.of(context).size.height + 100;
    return Scaffold(
      appBar: AppBar(title: Text('ReorderableListView NPE')),
      body: ReorderableListView(
        onReorder: (p1, p2) {},
        children: [
          Container(
            key: Key('item 0'),
            height: 300,
            color: Colors.green,
          ),
          Container(
            key: Key('item 1'),
            height: h,
            color: Colors.red,
          ),
        ],
        cacheExtent: h,
      ),
    );
  }
}
```

**Comment by rohansohonee1** [comment]
Tried by giving this (don't have the height ahead of time):
```
cacheExtent: MediaQuery.of(context).size.height * 1.5,
```

**Stack trace**
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'Ria'.
#00 pc 0xc2f743 com.agendaboa.app (SliverReorderableListState._itemOffsetAt [reorderable_list.dart:885])
#01 pc 0xc2f593 com.agendaboa.app (SliverReorderableListState._dragEnd.<anonymous closure> [reorderable_list.dart:746])
#02 pc 0x9062af com.agendaboa.app (State.setState [framework.dart:1114])
#03 pc 0xc2f28b com.agendaboa.app (SliverReorderableListState._dragEnd [reorderable_list.dart:734])
#04 pc 0xc2f233 com.agendaboa.app (SliverReorderableListState._dragEnd [reorderable_list.dart:733])
#05 pc 0xbfd1a3 com.agendaboa.app (_DragInfo.end [reorderable_list.dart:1255])
#06 pc 0x4bdaa7 com.agendaboa.app (MultiDragPointerState._up [multidrag.dart:158])
#07 pc 0x4bd83b com.agendaboa.app (MultiDragGestureRecognizer._handleEvent [multidrag.dart:266])
#08 pc 0x4bd6b3 com.agendaboa.app (MultiDragGestureRecognizer._handleEvent [multidrag.dart:254])
#09 pc 0xce9f67 com.agendaboa.app (PointerRouter._dispatch [pointer_router.dart:98])
#10 pc 0x3c6bfb com.agendaboa.app (PointerRouter._dispatchEventToRoutes.<anonymous closure> [pointer_router.dart:143])
#11 pc 0x43e0a3 com.agendaboa.app (_LinkedHashMapMixin.forEach [compact_hash.dart:617])
#12 pc 0x3c6b73 com.agendaboa.app (PointerRouter._dispatchEventToRoutes [pointer_router.dart:141])
#13 pc 0x3c6af3 com.agendaboa.app (PointerRouter.route [pointer_router.dart:127])
#14 pc 0x504713 com.agendaboa.app (GestureBinding.handleEvent [binding.dart:460])
#15 pc 0xce9ec3 com.agendaboa.app (GestureBinding.dispatchEvent [binding.dart:440])
#16 pc 0x3c69ef com.agendaboa.app (RendererBinding.dispatchEvent [binding.dart:337])
#17 pc 0x3c694b com.agendaboa.app (GestureBinding._handlePointerEventImmediately [binding.dart:395])
#18 pc 0x3c62f3 com.agendaboa.app (GestureBinding._flushPointerEventQueue [binding.dart:357])
#19 pc 0x604583 com.agendaboa.app (GestureBinding._handlePointerDataPacket [binding.dart:295])
#20 pc 0x60448f com.agendaboa.app (GestureBinding._handlePointerDataPacket [binding.dart:290])
#21 pc 0x399e0f com.agendaboa.app (_invoke1 [hooks.dart:167])
#22 pc 0x399d57 com.agendaboa.app (PlatformDispatcher._dispatchPointerDataPacket [platform_dispatcher.dart:341])
#23 pc 0x399ce3 com.agendaboa.app (_dispatchPointerDataPacket [hooks.dart:94])
```

```
Device
Brand:motorola
Model:Moto G (5S)
Orientation: Portrait
RAM free: 546.11 MB
Disk free: 11.39 GB
Operating System
Version:Android 7.1.1
Orientation: Portrait
Rooted:No
Crash
Date:Mar 1, 2023, 6:18:01 PM
App version:3.7.3 (176)
```

Flutter version: 3.3.8

**Comment by avocadohooman** [comment]
What is the latest status on this issue? I just received the same error message
