### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by darktheft** [flutter/flutter#87091]
I'm still getting error please help me 

my flutter -version

[√] Flutter (Channel dev, 2.4.0-4.0.pre, on Microsoft Windows [Version 10.0.19043.1110], locale en-IN)
    • Flutter version 2.4.0-4.0.pre at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (2 weeks ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

Launching lib\main.dart on SM M013F in debug mode...
Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1567)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1469)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                           1,485ms
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darktheft** [comment]
I solve my problem i just open in android studio and gradle delete and rebuild
