### ISSUE TITLE
Flutter engine build failed.

### ISSUE THREAD

**Issue by windows7lake** [flutter/flutter#87090]
following https://github.com/flutter/flutter/wiki/Compiling-the-engine to build engine code, but failed.
run command `flutter/tools/gn --unoptimized --runtime-mode=debug` and report as follow.
```
GOMA usage was specified but can't be found, falling back to local builds. Set the GOMA_DIR environment variable to fix GOMA.
Generating GN files in: out/host_debug_unopt
ERROR at //build/config/ios/ios_sdk.gni:54:27: Script returned non-zero exit code.
    _ios_sim_sdk_result = exec_script("ios_sdk.py", ios_sdk_args, "list lines")
                          ^----------
Current dir: /Users/yinglin/Workspace/FlutterWorker/engine/src/out/host_debug_unopt/
Command: python /Users/yinglin/Workspace/FlutterWorker/engine/src/build/config/ios/ios_sdk.py --sdk iphonesimulator
Returned 1.
stderr:

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Traceback (most recent call last):
  File "/Users/yinglin/Workspace/FlutterWorker/engine/src/build/config/ios/ios_sdk.py", line 50, in <module>
    sys.exit(main(sys.argv))
  File "/Users/yinglin/Workspace/FlutterWorker/engine/src/build/config/ios/ios_sdk.py", line 34, in main
    sdk_output = subprocess.check_output(command).decode('utf-8').strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['xcodebuild', '-version', '-sdk', 'iphonesimulator', 'Path']' returned non-zero exit status 1

See //build/toolchain/mac/BUILD.gn:9:1: whence it was imported.
import("//build/config/ios/ios_sdk.gni")
^--------------------------------------
See //BUILD.gn:6:1: which caused the file to be included.
group("default") {
^-----------------

```

**Comment by windows7lake** [comment]
The same as #80506

**Comment by hndrbrm** [comment]
Read from the error, it seems Xcode still not yet installed.

**Comment by windows7lake** [comment]
@hndrbrm Thanks，my fault, xcode install failed.
