### ISSUE TITLE
[tool_crash] ProcessException: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. Command: ~\AppData\Local\Google\Chrome\Application\chrome.exe, OS error code: 14001

### ISSUE THREAD

**Issue by MAZIShadow** [flutter/flutter#87103]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
 Command: ~\AppData\Local\Google\Chrome\Application\chrome.exe, OS error code: 14001
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:44:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:664:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:663:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:243:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:221:36)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:136:17)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:541:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Tools\flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at ~\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: ~/.sdkman/candidates/java/current\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at ~\AppData\Local\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7727

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • unknown
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03

**Comment by MAZIShadow** [comment]
For Chrome shows unknow because i created symlink to brave.exe

**Comment by darshankawar** [comment]
@MAZIShadow 
Can you check this link and see if it helps to resolve your issue, https://www.majorgeeks.com/content/page/solved_the_application_has_failed_to_start_because_its_side_by_side_configuration_is_incorrect_error.html

If not, can you try to reinstall Google chrome and see if it works ?

**Comment by MAZIShadow** [comment]
I removed Brave Browser clean up after, then install chrome and now everything is working.
@darshankawar thanks for help
