### ISSUE TITLE
web_tool_tests 'Unable to connect to Chrome debug port:...'

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#87148]
I see the following error in the last example (https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/2827). Flutter doctor throws earlier in the test as well.

Related: #84012
Related: #85043

```
Unable to connect to Chrome debug port: 46569
   FormatException: Unexpected character (at character 1)
  <html>
  ^
  

  #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
  #1      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:401:9)
  <asynchronous suspension>
  #2      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:136:17)
  <asynchronous suspension>
  #3      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:303:9)
  <asynchronous suspension>
  #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
  <asynchronous suspension>
```

**Comment by annagrin** [comment]
duplicate of https://github.com/flutter/flutter/issues/84012
