### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso., errno = 32.  A lot of android project files get deleted after the crash.

### ISSUE THREAD

**Issue by juanp88** [flutter/flutter#87140]
This happens when I tried to update packages using `flutter pub get`, 

## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:469:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:573:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:468:12)
#6      _deleteIfExistsSync (package:flutter_tools/src/project.dart:1060:15)
#7      AndroidProject._regenerateLibrary (package:flutter_tools/src/project.dart:953:5)
#8      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:928:13)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:302:21)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:167:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [VersiÃ³n 10.0.19042.1023], locale es-CO)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Juan\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Juan\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Juan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.55

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.flutter_integration
**iOS bundle identifier**: com.example.flutterIntegration
**Creation channel**: stable
**Creation framework version**: adc687823a831bbebe28bdccfac1a628ca621513
### Plugins
audio_session-0.0.11
device_info-1.0.0
flutter_plugin_android_lifecycle-1.0.11
image_picker-0.6.7+22
just_audio-0.6.15+1
just_audio_web-0.2.3
local_auth-0.6.3+4
open_file-3.2.1
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
permission_handler-5.1.0+2
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
speech_to_text-3.2.0
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
webview_flutter-1.0.7

In addition, after this crash a lot of my Android project files get deleted:

![gitStatus](https://user-images.githubusercontent.com/23729744/127232435-7ca2b293-34a5-4861-8d3f-3d28292e0d89.PNG)

**Comment by darshankawar** [comment]
@juanp88 
This issue was fixed and merged a while ago, https://github.com/flutter/flutter/issues/69109
Can you switch to latest master and try to run the same command again to see if it works ?

```
flutter channel master
flutter upgrade
flutter pub get
```

**Comment by juanp88** [comment]
So far that seems to fix the error but the AndroidManisfestFile and Build.gradle gets "reseted" to a default layout everytime, it's that normal?

**Comment by darshankawar** [comment]
@juanp88 
That may not be related to this issue. You may file a new issue highlighting the behavior you are seeing.
I am going ahead and closing this as fixed as your original tool_crash issue seems to have resolved after switching to latest master. If you disagree, write in comments and I'll reopen it.
Thanks.
