### ISSUE TITLE
Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true

### ISSUE THREAD

**Issue by sils** [flutter/flutter#87175]
## Steps to Reproduce

Hey, I don't have time to do a full minimal reproducible thing right now for you but the error message tells me to report this as it's a framework bug so here's your report, hope it helps :)

I basically have an app with an AppScaffold that uses a bottomNavigationBar with `shape: const CircularNotchedRectangle(),` and then:

```
floatingActionButton:
            ((MediaQuery.of(context).viewInsets.bottom < 20.0)
                ? FloatingActionButton(
                    onPressed: () {
                      Navigator.pushNamedAndRemoveUntil(
                        context,
                        '/home',
                        (route) => false,
                      );
                    },
                    child: const Icon(Icons.directions_run),
                    backgroundColor: Theme.of(context).primaryColor,
                  )
                : null),
```

The purpose here is to hide the FAB if the keyboard is not there while keeping the content properly scrollable.

The issue appeared when I added the mediaquery condition.

**Expected results:** No error message ;)

**Actual results:** See logs.

<details>
  <summary>Logs</summary>

```
E/flutter ( 7137): #12     DiagnosticsNode.toJsonMap
package:flutter/…/foundation/diagnostics.dart:1608
E/flutter ( 7137): #13     DiagnosticsProperty.toJsonMap
package:flutter/…/foundation/diagnostics.dart:2694
E/flutter ( 7137): #14     DiagnosticsNode.toJsonList.<anonymous closure>
package:flutter/…/foundation/diagnostics.dart:1632
E/flutter ( 7137): #15     MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
E/flutter ( 7137): #16     ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
E/flutter ( 7137): #17     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter ( 7137): #18     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 7137): #19     new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter ( 7137): #20     ListIterable.toList (dart:_internal/iterable.dart:212:44)
E/flutter ( 7137): #21     DiagnosticsNode.toJsonList
package:flutter/…/foundation/diagnostics.dart:1633
E/flutter ( 7137): #22     DiagnosticsNode.toJsonMap.<anonymous closure>
package:flutter/…/foundation/diagnostics.dart:1595
E/flutter ( 7137): #23     DiagnosticsNode.toJsonMap
package:flutter/…/foundation/diagnostics.dart:1608
E/flutter ( 7137): #24     WidgetInspectorService._nodeToJson
package:flutter/…/widgets/widget_inspector.dart:1499
E/flutter ( 7137): #25     WidgetInspectorService._reportError
package:flutter/…/widgets/widget_inspector.dart:919
E/flutter ( 7137): #26     FlutterError.reportError
package:flutter/…/foundation/assertions.dart:1107
E/flutter ( 7137): #27     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1146
E/flutter ( 7137): #28     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1090
E/flutter ( 7137): #29     _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 7137): #30     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 7137): #31     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter ( 7137):

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      RendererBinding._scheduleMouseTrackerUpdate
package:flutter/…/rendering/binding.dart:334
#3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
#4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1082
(elided 5 frames from class _AssertionError and dart:async)
```

Flutter analyze
```
No issues found! (ran in 4.5s)
flutter analyze  6,12s user 3,01s system 146% cpu 6,218 total
```

Flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/lasse/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/lasse/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/113/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/113/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment]
Hi @sils
Thanks for filing  the issue
I can't reproduce with FAB and bottom appear

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      bottomNavigationBar: BottomAppBar(
        shape: const CircularNotchedRectangle(),
        child: Container(
          height: 100,
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.endDocked,
      floatingActionButton: ((MediaQuery.of(context).viewInsets.bottom < 20.0)
          ? FloatingActionButton(
              onPressed: () {
                print('FAB');
              },
              child: const Icon(Icons.directions_run),
              backgroundColor: Theme.of(context).primaryColor,
            )
          : null),
    );
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

> The purpose here is to hide the FAB if the keyboard is not there while keeping the content properly scrollable.


Is there a possibility it could reproduce by adding the above to my minimal code sample to reproduce the issue? Feel free edit the code sample above to make it reproducible 
Thank you

**Comment by sils** [comment]
@TahaTesser hey, how important is this issue to you? I have used a cleaner solution for hiding my fab now by extending the standardfablocation class.

In case googlers hit this:

```
class FixedCenterDockedFabLocation extends StandardFabLocation
    with FabCenterOffsetX, FabDockedOffsetY {
  const FixedCenterDockedFabLocation();

  @override
  String toString() => 'FloatingActionButtonLocation.fixedCenterDocked';

  @override
  double getOffsetY(
      ScaffoldPrelayoutGeometry scaffoldGeometry, double adjustment) {
    final double contentBottom = scaffoldGeometry.contentBottom;
    final double bottomMinInset = scaffoldGeometry.minInsets.bottom;
    if (bottomMinInset > 0) {
      // Hide if there's a keyboard
      return contentBottom;
    }
    return super.getOffsetY(scaffoldGeometry, adjustment);
  }
}
```

With that, my issue is gone for me.

Let me know if you care about this issue enough so that it makes sense to drill down to its cause. In that case I can look into it, otherwise we might just want to drop this and reopen if other users have similar issues.
