### ISSUE TITLE
Can not load  assets(AssetManifest.json) use `FlutterEngineGroup`

### ISSUE THREAD

**Issue by walterFeng** [flutter/flutter#87173]
## Steps to Reproduce
1.create android project and add flutter support

2.show different fragment use `FlutterEngineGroup` and `FlutterFragment.withCachedEngine`

3.load image in different fragment,  get error.

[simple demo to Get this error](https://github.com/walterFeng/crashReportFlutter/tree/feature/multiple_flutters)

## Log 
<details>
  <summary>error logs</summary>

```java
======== Exception caught by image resource service =======================
The following assertion was thrown while resolving an image:
Unable to load asset: AssetManifest.json

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:68:27)
<asynchronous suspension>
Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#4fa3e(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, size: Size(329.0, 64.0), platform: android)
==================================================================
```

</details>

## Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```java
  [✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.1 20D74 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.5 at /Applications/flutter
    • Framework revision adc687823a (3 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/walter/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/walter/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • ELE AL00 (mobile) • Q5S0219412002409 • android-arm64  • Android 10 (API 29)
    • D2s (mobile)      • TC05209K40371    • android-arm    • Android 7.1.2 (API 25)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 92.0.4515.107
```

</details>

**Comment by TahaTesser** [comment]
Hi @walterFeng
Just ran the code sample on `stable`, no `Unable to load asset: AssetManifest.json` in the logs


<details> 
<summary>logs</summary> 
	
```console
[  +49 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more
information see #56466.
[   +3 ms] Syncing files to device IN2011...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:client_register/main.dart 7d6534c6-fc7f-445c-b47e-a363ed2a2c08
[        ] <- 7d6534c6-fc7f-445c-b47e-a363ed2a2c08
[  +66 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device IN2011... (completed in 72ms)
[   +1 ms] Synced 0.0MB.
[   +1 ms] <- accept
[  +19 ms] Connected to _flutterView/0x6e18bb2e00.
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[        ] An Observatory debugger and profiler on IN2011 is available at: http://127.0.0.1:60436/rnQWSYiOplA=/
[ +533 ms] The Flutter DevTools debugger and profiler on IN2011 is available at:
                    http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A60436%2FrnQWSYiOplA%3D%2F
[+1019 ms] I/309     (17553): package:cc.yourdream.register took:2247 calssname:android.app.ActivityThread$H
callback:null what:159
[   +4 ms] I/Choreographer(17553): Skipped 250 frames!  The application may be doing too much work on its main thread.
[ +587 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ........ 0,0-1080,2296} parent width 1080 parent height 2296 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ........ 0,0-1080,2296} viewRate 0 width 1080 height 2296
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ........ 0,0-1080,2296} parent width 1080 parent height 2296 mRatio 1.2
[   +3 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ........ 0,0-1080,2296} viewRate 0 width 1080 height 2296
[   +2 ms] I/OpenGLRenderer(17553): Davey! duration=3377ms; Flags=1, IntendedVsync=724136513475115,
Vsync=724139291252865, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=724139297395270,
AnimationStart=724139297441885, PerformTraversalsStart=724139300079801, DrawStart=724139886003603,
SyncQueued=724139887835374, SyncStart=724139888580947, IssueDrawCommandsStart=724139888731832,
SwapBuffers=724139890586989, FrameCompleted=724139891444280, DequeueBufferDuration=595833, QueueBufferDuration=334323,
GpuCompleted=4037269259134,
[  +14 ms] I/Choreographer(17553): Skipped 53 frames!  The application may be doing too much work on its main thread.
[+360064 ms] W/DisplayEventDispatcher(17553): dispatcher 0x6d48bbf230 ~ ignoring unknown event type 0x6d746f6e
[        ] W/DisplayEventDispatcher(17553): dispatcher 0x6d98beb1d0 ~ ignoring unknown event type 0x6d746f6e
[  +35 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ......ID 0,0-1080,2251} parent width 1080 parent height 2251 mRatio 1.2
[   +1 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ......ID 0,0-1080,2251} viewRate 0 width 1080 height 2251
[        ] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ........ 0,0-1080,2251} parent width 1080 parent height 2251 mRatio 1.2
[        ] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ........ 0,0-1080,2251} viewRate 0 width 1080 height 2251
[  +45 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ........ 0,0-1080,2251} parent width 1080 parent height 2251 mRatio 1.2
[  +11 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ........ 0,0-1080,2251} viewRate 0 width 1080 height 2251
[   +1 ms] D/DecorView(17553): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@aa373b5[MainActivity]
[        ] D/ViewRootImpl[MainActivity](17553): windowFocusChanged hasFocus=true inTouchMode=true
[+1030 ms] D/ViewRootImpl[MainActivity](17553): windowFocusChanged hasFocus=false inTouchMode=true
[+7409 ms] D/DecorView(17553): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@aa373b5[MainActivity]
[   +3 ms] D/ViewRootImpl[MainActivity](17553): windowFocusChanged hasFocus=true inTouchMode=true
[   +7 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ........ 0,0-1080,2251} parent width 1080 parent height 2251 mRatio 1.2
[   +3 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ........ 0,0-1080,2251} viewRate 0 width 1080 height 2251
[ +603 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{1dbb567
VFED..... ......I. 0,0-0,0} parent width 0 parent height 0 mRatio 1.2
[   +6 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{11ac526
V.E...... ......I. 0,0-0,0} viewRate 0 width 0 height 0
[ +114 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{1dbb567
VFED..... ......ID 0,0-493,500} parent width 493 parent height 500 mRatio 1.2
[   +3 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{11ac526
V.E...... ......ID 0,0-493,500} viewRate 0 width 493 height 500
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{1dbb567
VFED..... ........ 0,0-493,500} parent width 493 parent height 500 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{11ac526
V.E...... ........ 0,0-493,500} viewRate 0 width 493 height 500
[ +609 ms] I/flutter (17553): walter:329.0,925.3125,0.0
[   +3 ms] I/flutter (17553): walter: FrameCallback:0
[+1480 ms] I/flutter (17553): walter:329.0,925.3125,5512.5
[   +2 ms] I/flutter (17553): walter: FrameCallback:0
[   +2 ms] I/flutter (17553): walter:printReceipt
[   +2 ms] E/addDartWidget(17553): layout2131034203
[   +3 ms] I/flutter (17553): result:true
[  +79 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{1dbb567
VFED..... ......ID 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{11ac526
V.E...... ......ID 0,0-926,5513} viewRate 0 width 926 height 5513
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{1dbb567
VFED..... ........ 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{11ac526
V.E...... ........ 0,0-926,5513} viewRate 0 width 926 height 5513
[+1517 ms] D/OverScroller(17553): setting mVelocityAccuCount to: 1
[+3322 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{1dbb567
VFED..... ........ 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +3 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{11ac526
V.E...... ........ 0,0-926,5513} viewRate 0 width 926 height 5513
[+1356 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{cb1bc72
VFED..... ......I. 0,0-0,0} parent width 0 parent height 0 mRatio 1.2
[   +3 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f5a57d
V.E...... ......I. 0,0-0,0} viewRate 0 width 0 height 0
[ +119 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{cb1bc72
VFED..... ......ID 0,0-493,500} parent width 493 parent height 500 mRatio 1.2
[   +1 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f5a57d
V.E...... ......ID 0,0-493,500} viewRate 0 width 493 height 500
[   +1 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{cb1bc72
VFED..... ........ 0,0-493,500} parent width 493 parent height 500 mRatio 1.2
[        ] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f5a57d
V.E...... ........ 0,0-493,500} viewRate 0 width 493 height 500
[ +586 ms] I/flutter (17553): walter:329.0,925.3125,0.0
[   +2 ms] I/flutter (17553): walter: FrameCallback:0
[+1513 ms] I/flutter (17553): walter:329.0,925.3125,5512.5
[   +2 ms] I/flutter (17553): walter: FrameCallback:0
[   +2 ms] I/flutter (17553): walter:printReceipt
[   +2 ms] E/addDartWidget(17553): layout2131034203
[   +2 ms] I/flutter (17553): result:true
[   +3 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{cb1bc72
VFED..... ......ID 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f5a57d
V.E...... ......ID 0,0-926,5513} viewRate 0 width 926 height 5513
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{cb1bc72
VFED..... ........ 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f5a57d
V.E...... ........ 0,0-926,5513} viewRate 0 width 926 height 5513
[+4942 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{cb1bc72
VFED..... ........ 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +1 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f5a57d
V.E...... ........ 0,0-926,5513} viewRate 0 width 926 height 5513
[+22837 ms] W/DisplayEventDispatcher(17553): dispatcher 0x6d98beb1d0 ~ ignoring unknown event type 0x6d746f6e
[   +1 ms] W/DisplayEventDispatcher(17553): dispatcher 0x6d48bbf230 ~ ignoring unknown event type 0x6d746f6e
[ +390 ms] D/ViewRootImpl[MainActivity](17553): windowFocusChanged hasFocus=false inTouchMode=true
[+24189 ms] W/DisplayEventDispatcher(17553): dispatcher 0x6d98beb1d0 ~ ignoring unknown event type 0x6d746f6e
[  +53 ms] W/DisplayEventDispatcher(17553): dispatcher 0x6d48bbf230 ~ ignoring unknown event type 0x6d746f6e
[   +5 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ......I. 0,0-1080,2251} parent width 1080 parent height 2251 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ......I. 0,0-1080,2251} viewRate 0 width 1080 height 2251
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ........ 0,0-1080,2251} parent width 1080 parent height 2251 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ........ 0,0-1080,2251} viewRate 0 width 1080 height 2251
[   +2 ms] D/DecorView(17553): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@aa373b5[MainActivity]
[        ] D/ViewRootImpl[MainActivity](17553): windowFocusChanged hasFocus=true inTouchMode=true
[        ] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{70b6dbb
VFED..... ........ 0,0-1080,2251} parent width 1080 parent height 2251 mRatio 1.2
[        ] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{f73069f
V.E...... ........ 0,0-1080,2251} viewRate 0 width 1080 height 2251
[   +3 ms] D/ActivityThread(17553): pid:17553 tid:17553 doframe Callback
[+21462 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{3d2cbbf
VFED..... ......I. 0,0-0,0} parent width 0 parent height 0 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{eb15dde
V.E...... ......I. 0,0-0,0} viewRate 0 width 0 height 0
[ +120 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{3d2cbbf
VFED..... ......ID 0,0-493,500} parent width 493 parent height 500 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{eb15dde
V.E...... ......ID 0,0-493,500} viewRate 0 width 493 height 500
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{3d2cbbf
VFED..... ........ 0,0-493,500} parent width 493 parent height 500 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{eb15dde
V.E...... ........ 0,0-493,500} viewRate 0 width 493 height 500
[ +572 ms] I/flutter (17553): walter:329.0,925.3125,0.0
[   +2 ms] I/flutter (17553): walter: FrameCallback:0
[+1504 ms] I/flutter (17553): walter:329.0,925.3125,5512.5
[   +2 ms] I/flutter (17553): walter: FrameCallback:0
[   +2 ms] I/flutter (17553): walter:printReceipt
[   +2 ms] E/addDartWidget(17553): layout2131034203
[   +4 ms] I/flutter (17553): result:true
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{3d2cbbf
VFED..... ......ID 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{eb15dde
V.E...... ......ID 0,0-926,5513} viewRate 0 width 926 height 5513
[   +1 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{3d2cbbf
VFED..... ........ 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +1 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{eb15dde
V.E...... ........ 0,0-926,5513} viewRate 0 width 926 height 5513
[+4919 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{3d2cbbf
VFED..... ........ 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +1 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{eb15dde
V.E...... ........ 0,0-926,5513} viewRate 0 width 926 height 5513
[+11760 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{5f03b4c
VFED..... ......I. 0,0-0,0} parent width 0 parent height 0 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{c99cf7f
V.E...... ......I. 0,0-0,0} viewRate 0 width 0 height 0
[ +117 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{5f03b4c
VFED..... ......ID 0,0-493,500} parent width 493 parent height 500 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{c99cf7f
V.E...... ......ID 0,0-493,500} viewRate 0 width 493 height 500
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{5f03b4c
VFED..... ........ 0,0-493,500} parent width 493 parent height 500 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{c99cf7f
V.E...... ........ 0,0-493,500} viewRate 0 width 493 height 500
[ +589 ms] I/flutter (17553): walter:329.0,925.3125,0.0
[   +2 ms] I/flutter (17553): walter: FrameCallback:0
[+1505 ms] I/flutter (17553): walter:329.0,925.3125,5512.5
[   +2 ms] I/flutter (17553): walter: FrameCallback:0
[   +1 ms] I/flutter (17553): walter:printReceipt
[   +2 ms] E/addDartWidget(17553): layout2131034203
[   +2 ms] I/flutter (17553): result:true
[   +7 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{5f03b4c
VFED..... ......ID 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{c99cf7f
V.E...... ......ID 0,0-926,5513} viewRate 0 width 926 height 5513
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{5f03b4c
VFED..... ........ 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +2 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{c99cf7f
V.E...... ........ 0,0-926,5513} viewRate 0 width 926 height 5513
[+4912 ms] D/OpScreenModeManager(17553): setRefreshRate parent io.flutter.embedding.android.FlutterView{5f03b4c
VFED..... ........ 0,0-926,5513} parent width 926 parent height 5513 mRatio 1.2
[   +1 ms] D/OpScreenModeManager(17553): setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{c99cf7f
V.E...... ........ 0,0-926,5513} viewRate 0 width 926 height 5513
```
	
</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\Taha\Code\flutter_stable
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • IN2011 (mobile)   • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 91.0.864.71

! Doctor found issues in 1 category.
```

</details>

I see you're using an older stable channel 

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by walterFeng** [comment]
> Hi @walterFeng
> Just ran the code sample on `stable`, no `Unable to load asset: AssetManifest.json` in the logs
> 
> logs
> flutter doctor -v
> I see you're using an older stable channel
> 
> Can you please upgrade to the latest `stable` and try again
> Execute the following commands to upgrade
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`

**Comment by walterFeng** [comment]
Load assets does not work only when in debug mode and connected to the androidStudio debugger. Disconnect the device, then kill and restart the app, everything works.

**Comment by TahaTesser** [comment]
Hi @walterFeng 
Can you please try a different device or emulator?
Also please provide complete logs with the issue from `flutter run -v' similar to https://github.com/flutter/flutter/issues/87173#issuecomment-888358400

**Comment by walterFeng** [comment]
> Hi @walterFeng
> Can you please try a different device or emulator?
> Also please provide complete logs with the issue from `flutter run -v' similar to [#87173 (comment)](https://github.com/flutter/flutter/issues/87173#issuecomment-888358400)

Doesn't work on all my devices:
 • ELE AL00 (mobile) • Q5S0219412002409 • android-arm64  • Android 10 (API 29)
 • D2s (mobile)      • TC05209K40371    • android-arm    • Android 7.1.2 (API 25)
 • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)

**Comment by TahaTesser** [comment]
Hi @walterFeng 

> Run the code sample on stable，then click the second button. The image will not be seen and the error log will appear.


Thanks, I can reproduce the issue on the stable 

![Screenshot_1627643956](https://user-images.githubusercontent.com/48603081/127646353-d47cd0f6-1f1e-47a6-926b-4e2503700e95.png)


However, it seems to work on the latest beta 
![Screenshot_1627641955](https://user-images.githubusercontent.com/48603081/127646356-d38fa577-4982-4b39-a8b1-f63481b60992.png)



<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel beta, 2.4.0-4.2.pre, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.4.0-4.2.pre at C:\Users\Taha\Code\flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f18b9281c2 (8 days ago), 2021-07-22 14:08:30 -0700
    • Engine revision 844c29f42a
    • Dart version 2.14.0 (build 2.14.0-301.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\android-sdk
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.0 Preview 2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.0.31521.260
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.58.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1110]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!
```

</details>


Can you please upgrade to the latest  `beta` and try again
Execute the following commands to upgrade
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

Thank you

**Comment by walterFeng** [comment]
> Hi @walterFeng
> 
> > Run the code sample on stable，then click the second button. The image will not be seen and the error log will appear.
> 
> Thanks, I can reproduce the issue on the stable
> 
> ![Screenshot_1627643956](https://user-images.githubusercontent.com/48603081/127646353-d47cd0f6-1f1e-47a6-926b-4e2503700e95.png)
> 
> However, it seems to work on the latest beta
> ![Screenshot_1627641955](https://user-images.githubusercontent.com/48603081/127646356-d38fa577-4982-4b39-a8b1-f63481b60992.png)
> 
> flutter doctor -v
> Can you please upgrade to the latest `beta` and try again
> Execute the following commands to upgrade
> `flutter channel beta`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> Thank you

Hi, @TahaTesser
 You are right, it is work on the latest beta

**Comment by TahaTesser** [comment]
Hi @walterFeng 
Thanks for the confirmation, closing as fixed
