### ISSUE TITLE
flutter run crash on  iOS14.5

### ISSUE THREAD

**Issue by zmm2tysu** [flutter/flutter#87184]
### Flutter Doctor

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)

• No issues found!
```

#### Podfile One
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
#### Podfile Two
```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end
```

The difference between two files is at the top and bottom.
The point is when I use the Podfile two , flutter throw Exception when flutter run even if changed my flutter channel to master

#### Error Log
```
[  +22 ms] Error launching application on raccoon.
[   +6 ms] "flutter run" took 35,299ms.
[   +5 ms] 
 #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
 #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
 <asynchronous suspension>
 #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
 <asynchronous suspension>
 #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 <asynchronous suspension>
 #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
 <asynchronous suspension>
 #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
 <asynchronous suspension>
 #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 <asynchronous suspension>
 #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
 <asynchronous suspension>
 #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
 <asynchronous suspension>
 #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
 <asynchronous suspension>
 #10     main (package:flutter_tools/executable.dart:91:3)
 <asynchronous suspension>
```

How can I solve it?

**Comment by TahaTesser** [comment]
Hi @zmm2tysu 
This looks like the same issue as https://github.com/flutter/flutter/issues/87012
Please add [this](https://github.com/flutter/flutter/issues/87012#issuecomment-887183237) to your podfile and try again

Thank you

**Comment by zmm2tysu** [comment]
Wow!
It works!
Thanks a lot!

**Comment by zmm2tysu** [comment]
Unfortunately, It happended again.

![image](https://user-images.githubusercontent.com/20849786/127726690-347b3dbe-d7f0-41ba-9086-f7808b64e2d7.png)

The Application launched on the device. Waiting for observatory port too long and then cash

**Comment by zmm2tysu** [comment]
when I change the flutter channel to master, more error info appreas

![image](https://user-images.githubusercontent.com/20849786/127731013-5064cc11-b900-4d3d-8601-681c00dd564b.png)

**Comment by TahaTesser** [comment]
That's not the same issue, observatory timeout issue https://github.com/flutter/flutter/issues/72161
Closing
