### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Invalid internet address 

### ISSUE THREAD

**Issue by sokunsamnang** [flutter/flutter#87190]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Invalid internet address 
```
#0      new _InternetAddress.fromString (dart:io-patch/socket_patch.dart:238:9)
#1      new InternetAddress (dart:io-patch/socket_patch.dart:72:29)
#2      ProtocolDiscovery._forwardPort (package:flutter_tools/src/protocol_discovery.dart:152:9)
<asynchronous suspension>
#3      Stream.asyncMap.<anonymous closure>.add (dart:async/stream.dart)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.2 at /home/sanvuthy/flutter
    • Framework revision d79295af24 (7 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/sanvuthy/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/sanvuthy/Android/Sdk
    • Java binary at: /home/sanvuthy/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /home/sanvuthy/Downloads/android-studio
    • Flutter plugin version 52.1.1
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • SM N920C (mobile) • 0715f74b27cc3038 • android-arm64 • Android 7.0 (API 24)
    • V2025 (mobile)    • 11761d79         • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.5.0+15
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
app_settings-4.1.1
connectivity-3.0.6
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
file_picker-3.0.3
firebase_core-1.3.0
firebase_core_web-1.1.0
firebase_remote_config-0.10.0+2
flutter_absolute_path-1.0.6
flutter_image_compress-1.0.0
flutter_plugin_android_lifecycle-2.0.2
flutter_webview_plugin-0.4.0
fluttertoast-8.0.7
geolocator-5.2.1
google_api_availability-2.0.4
internet_speed_test-1.5.0
libphonenumber-2.0.1
libphonenumber_plugin-0.2.3
libphonenumber_web-0.2.0+1
location-4.3.0
location_permissions-2.0.5
location_web-3.1.1
multi_image_picker2-5.0.02
onesignal_flutter-3.0.0
package_info-2.0.2
path_provider-2.0.2
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.1
permission_handler-8.1.4+2
qr_code_scanner-0.4.0
quick_actions-0.6.0+2
share-2.0.4
shared_preferences-2.0.6
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
url_launcher-6.0.9
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.1
url_launcher_windows-2.0.0
wifi_connector-1.0.2
wifi_iot-0.3.4

**Comment by darshankawar** [comment]
@sokunsamnang 
Can you provide a code sample using which you get this error after trying to run `flutter run` ?
Or do you get this error for any flutter command ?
