### ISSUE TITLE
Flutter DragTarget Failed assertion: line 814 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true

### ISSUE THREAD

**Issue by DnXLogic** [flutter/flutter#87216]
Hi, 

I am facing an issue with the Drag Drop feature, showing below error after dropping the item:

======== Exception caught by gesture library =======================================================
The following assertion was thrown while routing a pointer event:
'package:flutter/src/widgets/drag_target.dart': Failed assertion: line 814 pos 12: '_candidateAvatars.contains(avatar) || _rejectedAvatars.contains(avatar)': is not true.

When the exception was thrown, this was the stack: 
#2      _DragTargetState.didLeave (package:flutter/src/widgets/drag_target.dart:814:12)
#3      _DragAvatar._leaveAllEntered (package:flutter/src/widgets/drag_target.dart:984:26)
#4      _DragAvatar.finishDrag (package:flutter/src/widgets/drag_target.dart:995:5)
#5      _DragAvatar.end (package:flutter/src/widgets/drag_target.dart:909:5)
#6      MultiDragPointerState._up (package:flutter/src/gestures/multidrag.dart:144:14)

**Comment by darshankawar** [comment]
@DnXLogic 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this error ?
Thanks.
