### ISSUE TITLE
FontFeature.characterVariant OpenType CharacterVariant features not working beyond cv20

### ISSUE THREAD

**Issue by Darkade** [flutter/flutter#87246]
## Steps to Reproduce

Take any OTF font with Character Variants beyond cv20 and flutter will throw a runtime exception.

```
        Text(
          '00',
          style: TextStyle(
              fontFamily: 'Dicier-Round-Light',
              fontSize: 22,
              fontFeatures: [
                FontFeature.characterVariant(40),
              ]),
        )
```

Here I am using [Dicier](https://speakthesky.itch.io/typeface-dicier) a custom font with many different Character Variants where using, for example, `cv40` will not work.

**Expected results:**

All OTF fonts may support up to 99 character variants as explained in the OTF documentation. So this should work

https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#cv01-cv99

**Actual results:**

When using a CV beyond 20 flutter will throw an error on runtime. This is because an assertion in the engine that asserts the cv is `1<= cv <= 20` this is incorrect. You can see it  in the engine code here `lib/ui/text.dart`

I have made a PR that addresses this issue. It's a very simple fix but without it OFT fonts is rather lacking.

https://github.com/flutter/engine/pull/27745

---

I think this error was introduced because OTF fonts have a similar feature called Stylistic Sets, that do go from ss01 to ss20. But cv can go from cv01 to cv99 as previously mentioned

Thank you

**Comment by darshankawar** [comment]
Verified on latest stable and master and replicable using the official sample code too. https://api.flutter.dev/flutter/dart-ui/FontFeature/FontFeature.characterVariant.html#Dart.dart:ui.FontFeature.characterVariant.1

For `FontFeature.characterVariant(1)` to `FontFeature.characterVariant(20)`, works well, but for `FontFeature.characterVariant(21)` and beyond, throws below error:

<details>
<summary>console error log</summary>

```



======== Exception caught by widgets library =======================================================
The following assertion was thrown building Demo(dirty):
'dart:ui/text.dart': Failed assertion: line 467 pos 12: '<optimized out>': is not true.

The relevant error-causing widget was: 
  Demo file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:7:11
When the exception was thrown, this was the stack: 
#2      new FontFeature.characterVariant (dart:ui/text.dart:467:12)
#3      Demo.build (package:macbug/main.dart:24:27)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4648:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Demo(dirty):
'dart:ui/text.dart': Failed assertion: line 467 pos 12: '<optimized out>': is not true.

The relevant error-causing widget was: 
  Demo file:///Users/dhs/Documents/NCFlutter/macbug/lib/main.dart:7:11
When the exception was thrown, this was the stack: 
#2      new FontFeature.characterVariant (dart:ui/text.dart:467:12)
#3      Demo.build (package:macbug/main.dart:24:27)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4648:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
...
====================================================================================================







```

</details>

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>

**Comment by Darkade** [comment]
PR is passing all tests

**Comment by Hixie** [comment]
Yeah this is fine, it was just a copy/paste error (original code was for ssXX, which goes up to 20).

**Comment by MrBirb** [comment]
@Darkade I believe your PR landed. Can this be closed?
