### ISSUE TITLE
Error in  build android

### ISSUE THREAD

**Issue by ZaunSupremoXV** [flutter/flutter#87288]
I have the error when I run `flutter run`, it says it has an error in the gradle.

Error message:
```
Launching lib\main.dart on SM J810M in debug mode...
                                                                        
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: failed writing to 'C:\Users\erick\Documents\Projeto\test_app\build\app\intermediates\runtime_symbol_list\debug\R.txt': Os dados são inválidos. (13).



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        62,8s
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
✏️  Creating `android\settings_aar.gradle`...                        2ms
✓ `android\settings_aar.gradle` created successfully.
Building plugin path_provider...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   25,1s
✓ Built build\app\outputs\repo.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: failed writing to 'C:\Users\erick\Documents\Projeto\test_app\build\app\intermediates\runtime_symbol_list\debug\R.txt': Os dados são inválidos. (13).



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

```

Error message in `flutter run --verbose`:
```
[  +94 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:processDebugResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[        ]      AAPT: error: failed writing to
'C:\Users\erick\Documents\Projeto\test_app\build\app\intermediates\runtime_symbol_list\debug\R.txt': Os dados são
inválidos. (13).
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[ +101 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] 24 actionable tasks: 14 executed, 10 up-to-date
[   +1 ms] BUILD FAILED in 14s
[+2997 ms] Running Gradle task 'assembleDebug'... (completed in 18,1s)
[   +4 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 43.210ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +259 ms] ensureAnalyticsSent: 254ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

Flutter version:  2.2.3
O.S: Windows 10

**Comment by maheshmnj** [comment]
Hi @ZaunSupremoXV, This issue looks related to gradle and not with flutter, I would recommend you to please ask such questions on communities like StackOverflow. 
Closing this issue as invalid if you disagree feel free to comment and I will reopen it.

ps: You may try this solution mentioned here https://stackoverflow.com/a/62919369/8253662

Thank you.
