### ISSUE TITLE
Flutter Web - errors on deployed version but not local

### ISSUE THREAD

**Issue by mzdm** [flutter/flutter#87282]
## Steps to Reproduce

I can't figure out what the issue is with the version deployed to Firebase. It works fine on local (web/desktop).
I can't provide a reproducible sample as I do not where the issue exactly is. Is there a way to see where minified errors points to ?

I'm getting on Firebase version:
```js
TypeError: null: type 'minified:uv' is not a subtype of type 'minified:kZ'
main.dart.js:11775     at Object.d (https://sketch-vision-deploy.web.app/main.dart.js:10582:3)
main.dart.js:11775     at Object.aOk (https://sketch-vision-deploy.web.app/main.dart.js:11238:18)
main.dart.js:11775     at jK.b2K [as a] (https://sketch-vision-deploy.web.app/main.dart.js:11233:3)
main.dart.js:11775     at Ko.lc (https://sketch-vision-deploy.web.app/main.dart.js:28905:31)
main.dart.js:11775     at tt.swf (https://sketch-vision-deploy.web.app/main.dart.js:28696:3)
main.dart.js:11775     at XS.agD (https://sketch-vision-deploy.web.app/main.dart.js:59960:3)
main.dart.js:11775     at XS.jN (https://sketch-vision-deploy.web.app/main.dart.js:59967:3)
main.dart.js:11775     at TA.b4 (https://sketch-vision-deploy.web.app/main.dart.js:65195:3)
main.dart.js:11775     at TA.S0 (https://sketch-vision-deploy.web.app/main.dart.js:63995:7)
main.dart.js:11775     at v1.ey (https://sketch-vision-deploy.web.app/main.dart.js:63730:19)
174main.dart.js:11775 Another exception was thrown: Instance of 'minified:iv<void>'
```

No error on local.

Note that I think last month or so it worked fine.

Related repo: https://github.com/mzdm/sketch_vision https://sketch-vision-deploy.web.app/
(how to see the error - 2nd menu sketch paint - next page - next page (classify) - hierarchy icon - see errors in the console

<details>
  <summary>Logs</summary>

```
C:\Users\matej>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version
    10.0.19043.1110], locale cs-CZ)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (3 available)

• No issues found!
```

</details>

How can I debug to see where the issue is?

**Comment by darshankawar** [comment]
@mzdm 
Check below links and see if they help to debug:

https://github.com/flutter/flutter/issues/71410#issuecomment-738329093
https://stackoverflow.com/questions/59239793/how-to-fix-the-minifiedaqvoid-flutter-web-error

**Comment by mzdm** [comment]
Unfortunately, that did not help - it works fine with that run flags.

Note that the error occurs on the screen where Firebase/Network calls are not used, but I do not what else it can be then..

**Comment by darshankawar** [comment]
Also check this issue and underlying comments. https://github.com/flutter/flutter/issues/44912#issuecomment-657656996
May be you need to revisit your code structure and see if you get any leads based on implementation.

**Comment by mzdm** [comment]
I was actually running locally on `stable` channel while on the repo it runs on `beta` channel 🙈

Thanks for the hints! 

```
[√] Flutter (Channel beta, 2.4.0-4.2.pre, on Microsoft Windows [Version
    10.0.19043.1110], locale cs-CZ)
```

Now the error is more readable when running with `flutter run -d chrome --profile`:
```dart
TypeError: null: type 'JSNull' is not a subtype of type 'SkDeletable'
js_primitives.dart:47     at Object.wrapException (http://localhost:57177/main.dart.js:17924:17)
js_primitives.dart:47     at Object._failedAsCheck (http://localhost:57177/main.dart.js:19380:15)
js_primitives.dart:47     at Rti._generalAsCheckImplementation [as _as] (http://localhost:57177/main.dart.js:19369:9)
js_primitives.dart:47     at CkMaskFilter.ManagedSkiaObject$1 (http://localhost:57177/main.dart.js:51690:77)
js_primitives.dart:47     at CkPaint.set$maskFilter (http://localhost:57177/main.dart.js:51303:10)
js_primitives.dart:47     at _BoxDecorationPainter._paintShadows$3 (http://localhost:57177/main.dart.js:114105:16)
js_primitives.dart:47     at _BoxDecorationPainter.paint$3 (http://localhost:57177/main.dart.js:114124:13)
js_primitives.dart:47     at RenderDecoratedBox.paint$2 (http://localhost:57177/main.dart.js:124551:12)
js_primitives.dart:47     at RenderDecoratedBox._paintWithContext$2 (http://localhost:57177/main.dart.js:122241:15)
js_primitives.dart:47     at PaintingContext.paintChild$2 (http://localhost:57177/main.dart.js:121651:15)
379js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
10js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
```



What could it be? Why it works fine on stable but crashes on beta, maybe some regression?

**Comment by mzdm** [comment]
Looks like it was fixed on `master` channel https://github.com/flutter/engine/pull/27710 👍
would be worth cherry-picking at least to beta channel imo, since many people encountered seems like
