### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'isMacOSEnabled' was called on null.Receiver: nullTried calling: isMacOSEnabled

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#87317]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. Press `o` 3 times to switch to Android, iOS, then fuchsia
2. Press `o` again
3. I never set up my environment for Mac or Windows, that's probably what's causing it. 

## Logs
```
NoSuchMethodError: NoSuchMethodError: The getter 'isMacOSEnabled' was called on null.
Receiver: null
Tried calling: isMacOSEnabled

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      nextPlatform (package:flutter_tools/src/resident_runner.dart:1703:24)
#2      ResidentWebRunner.debugTogglePlatform (package:flutter_tools/src/isolated/resident_web_runner.dart:309:31)
<asynchronous suspension>
#3      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1644:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-US)
    • Flutter version 2.2.3 at C:\Users\levi\flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\levi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.164
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.55

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f4abaa0735eba4dfd8f33f73363911d63931fe03
### Plugins
video_player-2.1.10
video_player_web-2.0.1

**Comment by darshankawar** [comment]
@Levi-Lesches 
Do you get this error only after step 1 and step 2 as mentioned above, or directly after running `flutter run -d chrome` ?
Can you also provide complete log ?

**Comment by Levi-Lesches** [comment]
This happens after pressing `o` four times _after_ running `flutter run -d chrome`. It's the switch to `macOS` that confuses the tool.

<details>
<summary>Full Logs with <code>flutter -v run -d chrome</code></summary>

```
flutter -v run -d chrome
[ +166 ms] executing: [C:\Users\USERNAME\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +673 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +1 ms] executing: [C:\Users\USERNAME\flutter/] git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[  +78 ms] Exit code 0 from: git tag --points-at f4abaa0735eba4dfd8f33f73363911d63931fe03
[   +1 ms] 2.2.3
[   +8 ms] executing: [C:\Users\USERNAME\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Users\USERNAME\flutter/] git ls-remote --get-url origin
[  +50 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +205 ms] executing: [C:\Users\USERNAME\flutter/] git rev-parse --abbrev-ref HEAD
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +189 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +110 ms] executing: C:\Users\USERNAME\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +96 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +132 ms] executing: C:\Users\USERNAME\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +19 ms] Skipping pub get: version match.
[  +55 ms] Found plugin video_player at C:\Users\USERNAME\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.10\
[  +16 ms] Found plugin video_player_web at C:\Users\USERNAME\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.1\
[ +197 ms] Found plugin video_player at C:\Users\USERNAME\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.10\
[  +13 ms] Found plugin video_player_web at C:\Users\USERNAME\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.1\
[  +33 ms] Generating C:\Users\USERNAME\Coding\Flutter\video_controls_example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +123 ms] List of devices attached
[ +103 ms] Launching lib\main.dart on Chrome in debug mode...
[  +69 ms] List of devices attached
[ +164 ms] Updating assets
[ +220 ms] Waiting for connection from debug service on Chrome...
[  +63 ms] Found plugin video_player at C:\Users\USERNAME\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.10\
[   +5 ms] Found plugin video_player_web at C:\Users\USERNAME\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.1\
[  +61 ms] Found plugin video_player at C:\Users\USERNAME\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-2.1.10\
[  +12 ms] Found plugin video_player_web at C:\Users\USERNAME\flutter\.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.1\
[ +229 ms] <- reset
[  +17 ms] C:\Users\USERNAME\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\USERNAME\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\USERNAME\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\USERNAME\AppData\Local\Temp\flutter_tools.3cb6a5d2\flutter_tool.113b8768\app.dill --libraries-spec file:///C:/Users/USERNAME/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
C:\Users\USERNAME\Coding\Flutter\video_controls_example\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root C:\Users\USERNAME\AppData\Local\Temp\flutter_tools.3cb6a5d2\flutter_tools.ce564e51 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///C:/Users/USERNAME/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +41 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+25141 ms] Waiting for connection from debug service on Chrome... (completed in 25.6s)
[   +4 ms] Synced 28.5MB.
[  +10 ms] <- accept
[   +1 ms] Caching compiled dill
[+12849 ms] [CHROME]:
[  +44 ms] [CHROME]:DevTools listening on ws://127.0.0.1:56068/devtools/browser/5552e38c-62a5-42ea-9f1b-47de780c6a74
[+1572 ms] DwdsInjector: Received request for entrypoint at http://localhost:57696/main_module.bootstrap.js
[  +14 ms] MetadataProvider: Loading debug metadata...
[  +41 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +20 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:57696/main_module.bootstrap.js
[+5157 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[ +104 ms] DevHandler: Debug service listening on ws://127.0.0.1:50567/zg7cAj3tHlQ=/ws

[  +41 ms] This app is linked to the debug service: ws://127.0.0.1:50567/zg7cAj3tHlQ=/ws
[  +25 ms] Debug service listening on ws://127.0.0.1:50567/zg7cAj3tHlQ=/ws
[   +1 ms]  Running with sound null safety
[   +6 ms]   To hot restart changes while running, press "r" or "R".
[   +5 ms] For a more detailed help message, press "h". To quit, press "q".
[+26253 ms] Switched operating system to android
[+2312 ms] Switched operating system to iOS
[+1138 ms] Switched operating system to fuchsia
[+1254 ms] NoSuchMethodError: The getter 'isMacOSEnabled' was called on null.
                    Receiver: null
                    Tried calling: isMacOSEnabled
                    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
                    #1      nextPlatform (package:flutter_tools/src/resident_runner.dart:1703:24)
                    #2      ResidentWebRunner.debugTogglePlatform (package:flutter_tools/src/isolated/resident_web_runner.dart:309:31)
                    <asynchronous suspension>
                    #3      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1644:7)
                    <asynchronous suspension>

[ +167 ms] DevHandler: Stopped debug service on ws://127.0.0.1:50565


[+14685 ms] Sending crash report to Google.
[  +39 ms] Failed to clean up temp directory: C:\Users\USERNAME\AppData\Local\Temp\flutter_tools.3cb6a5d2\flutter_tools.ce564e51
[   +7 ms] Application finished.
[  +24 ms] "flutter run" took 92,831ms.
[ +282 ms] Crash report sent (report ID: f8d727e1ef0e7311)
[   +9 ms] Oops; flutter has exited unexpectedly: "NoSuchMethodError: The getter 'isMacOSEnabled' was called on null.
           Receiver: null
           Tried calling: isMacOSEnabled".
[  +92 ms] executing: C:\Program Files\Android\jre\bin\java -version
[ +526 ms] Exit code 0 from: C:\Program Files\Android\jre\bin\java -version
[  +13 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +54 ms] executing: C:\Program Files\Android\jre\bin\java -version
[ +157 ms] Exit code 0 from: C:\Program Files\Android\jre\bin\java -version
[   +5 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +16 ms] executing: [C:\Users\USERNAME\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[ +102 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[   +8 ms] 4 weeks ago
[ +158 ms] java -version
[ +316 ms] executing: C:\Users\USERNAME\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +85 ms] List of devices attached
[+7093 ms] A crash report has been written to C:\Users\USERNAME\Coding\Flutter\video_controls_example\flutter_02.log.
[   +4 ms] This crash may already be reported. Check GitHub for similar crashes.
[  +10 ms]
https://github.com/flutter/flutter/issues?q=is%3Aissue+NoSuchMethodError%3A+The+getter+%27isMacOSEnabled%27+was+called+on+null.%0AReceiver%3A+null%0ATried+calling%3A+isMacOSEnabled

[   +2 ms] To report your crash to the Flutter team, first read the guide to filing a bug.
[   +1 ms] https://flutter.dev/docs/resources/bug-reports

[   +1 ms] Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
[  +32 ms] Attempting git.io shortener:
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+NoSuchMethodError%3A+NoSuchMethodError%3A+The+getter+%27isMacOSEnabled%27+was+called+on+null.%0AReceiver%3A+null%0AT
ried+calling%3A+isMacOSEnabled&body=%23%23+Command%0A%60%60%60%0Aflutter+-v+run+-d+chrome%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0ANoSuch
MethodError%3A+NoSuchMethodError%3A+The+getter+%27isMacOSEnabled%27+was+called+on+null.%0AReceiver%3A+null%0ATried+calling%3A+isMacOSEnabled%0A%60%60%60%0A%230++++++Object.noSuchMethod+
%28dart%3Acore-patch%2Fobject_patch.dart%3A54%3A5%29%0A%231++++++nextPlatform+%28package%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A1703%3A24%29%0A%232++++++ResidentWebRunner.debugT
ogglePlatform+%28package%3Aflutter_tools%2Fsrc%2Fisolated%2Fresident_web_runner.dart%3A309%3A31%29%0A%3Casynchronous+suspension%3E%0A%233++++++TerminalHandler.processTerminalInput+%28pa
ckage%3Aflutter_tools%2Fsrc%2Fresident_runner.dart%3A1644%3A7%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+2.2.3%2C+on+Micro
soft+Windows+%5BVersion+10.0.19043.1110%5D%2C+locale+en-US%29%0A++++%E2%80%A2+Flutter+version+2.2.3+at+C%3A%5CUsers%5CUSERNAME%5Cflutter%0A++++%E2%80%A2+Framework+revision+f4abaa0735+%284+w
eeks+ago%29%2C+2021-07-01+12%3A46%3A11+-0700%0A++++%E2%80%A2+Engine+revision+241c87ad80%0A++++%E2%80%A2+Dart+version+2.13.4%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+
devices+%28Android+SDK+version+29.0.2%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5CUSERNAME%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%80%A2+Platform+android-30%2C+build-tools+29.0.2%0
A++++%E2%80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5Cjre%5Cbin%5Cjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+1.8.0_202-release-1483-b03%29%0D%0A+
+++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files+%28x86%29%5CGoogle%5CChrome%5CApplication%5C
chrome.exe%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+3.5%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%0A++++%E2%80%A2+Flutter+plugin+version+42.1.1%0A++++%E2
%80%A2+Dart+plugin+version+191.8593%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+1.8.0_202-release-1483-b03%29%0D%0A%0A%5B%E2%9C%93%5D+Connected+device+%282+availab
le%29%0A++++%E2%80%A2+Chrome+%28web%29+%E2%80%A2+chrome+%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+91.0.4472.164%0A++++%E2%80%A2+Edge+%28web%29+++%E2%80%A2+edge+++%E2%80%A2+web-ja
vascript+%E2%80%A2+Microsoft+Edge+92.0.902.55%0A%0A%E2%80%A2+No+issues+found%21%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3
A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS
+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+f4abaa0735eba4dfd8f33f73363911d63931fe03%0A%23%23%23+Plugins%0Avide
o_player-2.1.10%0Avideo_player_web-2.0.1%0A%0A&labels=tool%2Csevere%3A+crash
[ +509 ms] https://git.io/JBwOo

[   +9 ms] ensureAnalyticsSent: 1ms
[  +16 ms] Running shutdown hooks
[  +15 ms] Shutdown hooks complete
[  +15 ms] exiting with code 1
```

</details>

**Comment by darshankawar** [comment]
Thanks for the details. I am able to replicate this using latest stable and running below steps:

1. Run `flutter run -d chrome`
2. Press `o` 3 times which shows below logs in console:

```
Switched operating system to android

Switched operating system to iOS

Switched operating system to fuchsia


```

Then press `o` again which shows below error:

```
NoSuchMethodError: The getter 'isMacOSEnabled' was called on null.
Receiver: null
Tried calling: isMacOSEnabled
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      nextPlatform (package:flutter_tools/src/resident_runner.dart:1703:24)
#2      ResidentWebRunner.debugTogglePlatform (package:flutter_tools/src/isolated/resident_web_runner.dart:309:31)
<asynchronous suspension>
#3      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1644:7)
<asynchronous suspension>



Application finished.
Oops; flutter has exited unexpectedly: "NoSuchMethodError: The getter 'isMacOSEnabled' was called on null.
Receiver: null
Tried calling: isMacOSEnabled".
A crash report has been written to /Users/dhs/Documents/NCFlutter/macbug/flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+NoSuchMethodError%3A+The+getter+%27isMacOSEnabled%27+was+called+on+null.%0AReceiver%3A+null%0ATried+calling%3A+isMacOSEnabled

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JBH6T

dhs@Dhss-MacBook-Pro macbug % 

```

Although this seems to be only happening on stable. Also tried on latest master (2.5.0-2.0.pre.113) and followed above steps again which didn't crash and switched to `macos` properly as below:
```

Switched operating system to android

Switched operating system to iOS

Switched operating system to fuchsia

Switched operating system to macOS

Switched operating system to android

Switched operating system to iOS

Switched operating system to fuchsia

Switched operating system to macOS


```

@Levi-Lesches 
You can switch to latest master because it doesn't occur there, maybe the fix is not in stable yet.

**Comment by Levi-Lesches** [comment]
Oh okay. I don't really need the `macOS` platform, I was just fiddling with the buttons on my keyboard while waiting for my app to do something. Just reported to let you know, but I'll close if it's already been fixed.
