### ISSUE TITLE
Image_Picker doesn't function properly in One Plus 3 & 3T

### ISSUE THREAD

**Issue by rmControls** [flutter/flutter#87405]
## Steps to Reproduce

It is related to the issue [#85392](https://github.com/flutter/flutter/issues/85392). Since it is closed I am creating new ticket.

```
XFile? pickedFile = await _picker.pickImage(
                  source: ImageSource.camera,
                  maxWidth: 400,
                );
```

```
XFile? pickedFile = await _picker.pickImage(
                  source: ImageSource.gallery,
                  maxWidth: 400,
                );
```
**Expected results:It should Launch Camera or Gallery to pick Image (It doesn't work all the time)

**Actual results:** 

<details>
  <summary>Logs</summary>

W/Binder ( 4938): Caught a RuntimeException from the binder stub implementation.
W/Binder ( 4938): java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=4938, uid=10075 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
W/Binder ( 4938): at android.os.Parcel.readException(Parcel.java:1943)
W/Binder ( 4938): at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
W/Binder ( 4938): at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
W/Binder ( 4938): at android.content.ContentProviderProxy.delete(ContentProviderNative.java:561)
W/Binder ( 4938): at android.content.ContentResolver.delete(ContentResolver.java:1749)
W/Binder ( 4938): at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:68)
W/Binder ( 4938): at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:60)
W/Binder ( 4938): at android.os.Binder.execTransact(Binder.java:692)

or 

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @rmControls, could you please share the output of `flutter doctor -v` with the exact steps to reproduce the issue and also what version of the [image_picker](https://pub.dev/packages/image_picker) plugin are you using?

**Comment by rmControls** [comment]
`flutter doctor -v`

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
    • Flutter version 2.2.3 at G:\FlutterLab\flutter_sdk\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = D:\android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\abcde\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.62
```

**Image Picker Version:**
`image_picker: ^0.8.2`


**Reproduce-able Code**
As said this error occurs only in OnePlus 3 & 3t. 

```
final _picker = ImagePicker();

XFile? pickedFile = await _picker.pickImage(
                  source: ImageSource.camera,
                  maxWidth: 400,
                );

XFile? pickedFile = await _picker.pickImage(
                  source: ImageSource.gallery,
                  maxWidth: 400,
                );


```

**Comment by maheshmnj** [comment]
The issue is not reproducible on Android xiaomi k20 pro on the latest stable channel.

Could you please try switching to the master channel by running 

```
flutter channel master
flutter upgrade
flutter clean
```
and see if it is reproducible there.
you can switch back to stable channel again by running `flutter channel stable`

<details>
<summary>code sample</summary>

```
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());


class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        color: Colors.white,
        title: 'Flutter Demo',
        theme: ThemeData(primarySwatch: Colors.blue),
        home: ImagePickerSample()
        );
  }
}
class ImagePickerSample extends StatefulWidget {
  ImagePickerSample({Key? key, this.title = 'Image Picker Sample'})
      : super(key: key);

  final String title;

  @override
  _ImagePickerSampleState createState() => _ImagePickerSampleState();
}

class _ImagePickerSampleState extends State<ImagePickerSample> {
  Widget imageBuilder(File file, int index) {
    if (file != null && file.path.isNotEmpty) {
      return Image.file(
        File(
          file.path,
        ),
        fit: BoxFit.cover,
      );
    } else {
      return imagePlaceHolder(index);
    }
  }

  Future<XFile?> pickImage(ImageSource source) async {
    try {
      final image = await _picker.pickImage(
        source: source,
      );
      return image;
    } catch (e, stackTrace) {
      return XFile('');
    }
  }

  Widget imagePlaceHolder(int index) {
    return Container(
      // padding: EdgeInsets.only(right),
      alignment: Alignment.center,
      decoration: BoxDecoration(
        border: Border(
            right: index % 2 == 0 ? BorderSide() : BorderSide.none,
            bottom: BorderSide()),
      ),
      child: Icon(Icons.add_a_photo),
    );
  }

  final _picker = ImagePicker();

  List<File> images = [];

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    List.generate(4, (x) => images.add(File('')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: GridView.builder(
                itemCount: 4,
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 2),
                itemBuilder: (context, index) => GestureDetector(
                    onTap: () async {
                      final image = await pickImage(ImageSource.gallery);
                      setState(() {
                        images[index] = File(image!.path);
                      });
                    },
                    child: imageBuilder(images[index], index)),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)     • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

Thanks
