### ISSUE TITLE
/api/github-webhook-pullrequest failing to process request

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#87507]
```
GitHub Error: 
  Message: Invalid request.

Only 65535 characters are allowed; 74057 were supplied.

#0      GitHub.handleStatusCode (package:github/src/common/github.dart:429:9)
#1      GitHub.request (package:github/src/common/github.dart:372:7)
<asynchronous suspension>
#2      GitHub.requestJson (package:github/src/common/github.dart:268:22)
<asynchronous suspension>
#3      GithubChecksUtil.updateCheckRun.<anonymous closure> (package:cocoon_service/src/foundation/github_checks_util.dart:63:7)
<asynchronous suspension>
#4      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#5      Scheduler.triggerPresubmitTargets (package:cocoon_service/src/service/scheduler.dart:377:7)
<asynchronous suspension>
#6      GithubWebhook._scheduleIfMergeable (package:cocoon_service/src/request_handlers/github_webhook.dart:162:5)
<asynchronous suspension>
#7      GithubWebhook._handlePullRequest (package:cocoon_service/src/request_handlers/github_webhook.dart:117:9)
<asynchronous suspension>
#8      GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:62:11)
<asynchronous suspension>
#9      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#10     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:254:9)
<asynchronous suspension>

```

**Comment by godofredoc** [comment]
@CaseyHillers did you get a chance to triage this issue?

**Comment by CaseyHillers** [comment]
I haven't looked at this. Should this be in the ticket queue?

**Comment by godofredoc** [comment]
It would be useful to get it triaged when the context is fresh. Most likely it will require batch processing using cloud functions or similar. Once it is triaged we can move it out of the queue.

**Comment by godofredoc** [comment]
\cc @keyonghan can you please update this bug with the triage data

**Comment by keyonghan** [comment]
Most likely this is due to summary consolidation of all sub tests (triggered from the builder itself) exceeding the limit. 
See also: https://github.com/flutter/flutter/issues/90224
