### ISSUE TITLE
[Add2App] `Caused by java.lang.NullPointerException...FlutterActivityAndFragmentDelegate.onPostResume()' on a null object reference` 

### ISSUE THREAD

**Issue by EdStepashkin** [flutter/flutter#87526]
In our application we use flutter as a part of our android application. 
https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen

After we updated flutter to 2.2.3 version we got a lot of crash (Firebase Crashlytics). 

Now we don't have steps to reproduce this problem(but we're trying to find them), we have just log in Firebase Crashlytics. 

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {ua.myapp/ua.myapp.flutterbridge.FlutterViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onPostResume()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4789)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4832)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)


Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onPostResume()' on a null object reference

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onPostResume()' on a null object reference
       at io.flutter.embedding.android.FlutterFragment.onPostResume(FlutterFragment.java:645)
       at io.flutter.embedding.android.FlutterFragmentActivity.onPostResume(FlutterFragmentActivity.java:473)
       at android.app.Activity.performResume(Activity.java:8248)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4779)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4832)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)


```

 **flutter doctor -v**

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale ru)
    • Flutter version 2.2.3 at /Users/dmytronazarenko/AndroidStudioProjects/Flutter/fluttersdk
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dmytronazarenko/AndroidSdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/dmytronazarenko/AndroidSdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
```

**Comment by TahaTesser** [comment]
H @EdStepashkin 
Thanks for filing the issue,

I tried similar issue for `FlutterActivityAndFragmentDelegate.onPostResume()'` but couldn't find a duplicate

**Comment by Kabilan21** [comment]
Hi @EdStepashkin 

I was facing a similar issue in an add2app scenario. In my case, I have a Mainactivity which holds a native fragment and a flutter fragment.

  @Override
    public void onPostResume() {
        super.onPostResume();
        flutterFragment.onPostResume();
    }

if flutterFragement is null, then the above crash occurs.

A simple workaround is removing the above piece of code. But if it is removed, the app will crash when it was brought to the foreground after a long time it was kept in the memory.

**Comment by chinmaygarde** [comment]
The location of the NPE is clear. But, I am not sure how we got into this situation. Presumably, there is some unexpected sequence of lifecycle events. cc @blasten Should we defensively check all delegate call sites for null? But, I am not sure if that just kicks the can down the road.

**Comment by rahuldev91** [comment]
Any workaround for this. getting many crashes 
<img width="1157" alt="Screenshot 2021-09-01 at 9 57 39 AM" src="https://user-images.githubusercontent.com/66363362/131611950-58020cdd-7328-497d-97a1-44d671b89bad.png">
