### ISSUE TITLE
Failed assertion: line 455 pos 7: '_ticker != null'  in showModalBottomSheet 

### ISSUE THREAD

**Issue by radha1990kumari** [flutter/flutter#87592]
It works as expected if I don't provide my animation controller which I provide only to decrease the default appearing time of the bottom  sheet. 
## Steps to Reproduce
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      home: HomePage(),
    ));

class HomePage extends StatefulWidget {
  HomePage({Key key}) : super(key: key);

  @override
  HomePageWithState createState() => HomePageWithState();
}

class HomePageWithState extends State<HomePage>
    with SingleTickerProviderStateMixin {
  AnimationController controller;
  @override
  void initState() {
    super.initState();
    controller = BottomSheet.createAnimationController(this);
    controller.duration = Duration(seconds: 1);
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Test Detection"),
      ),
      body: Column(
        children: [
          Center(
            child: GestureDetector(
              onTap: () {
                showModalBottomSheet(
                    context: context,
                    transitionAnimationController: controller,
                    builder: (context) {
                      return Container(
                        color: Colors.purple,
                        child: Container(
                          height: 335,
                          padding: EdgeInsets.all(20),
                          child: SingleChildScrollView(
                            physics: BouncingScrollPhysics(),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                SizedBox(
                                  height: 20,
                                ),
                              ],
                            ),
                          ),
                        ),
                      );
                    });
              },
              child: Container(
                height: 250,
                color: Colors.green,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Expected results:** 
Should show bottom sheet on Tap. 
**Actual results:** 
Works only first time then I get this error 
```
The following assertion was thrown while handling a gesture:
AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
Failed assertion: line 455 pos 7: '_ticker != null'

```
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Verified this on latest stable and saw the same behavior.

<details>
<summary>console error log</summary>

```

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
Failed assertion: line 455 pos 7: '_ticker != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:455:7)
#3      TransitionRoute.didPush (package:flutter/src/widgets/routes.dart:216:25)
#4      ModalRoute.didPush (package:flutter/src/widgets/routes.dart:1107:18)
#5      _RouteEntry.handlePush (package:flutter/src/widgets/navigator.dart:3013:46)
#6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3958:17)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#65ace
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(221.3, 278.0)
  finalLocalPosition: Offset(221.3, 175.0)
  button: 1
  sent tap down
====================================================================================================







```

</details>


<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.2.3 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision f4abaa0735 (4 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

• No issues found!





```

</details>
