### ISSUE TITLE
difficulty in building Flutter engine locally

### ISSUE THREAD

**Issue by abhilashraju** [flutter/flutter#87632]
## Steps to Reproduce
I was following steps mentioned here
https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
However I am finding some difficulty in step gclient sync.
I am getting the following error which running gclient sync

## Logs
```
gclient.bat sync
The system cannot open the device or file specified.

C:\Users\rabhil\work\flutter\engine>C:\Users\rabhil\work\dart_tool\gclient.py sync
Syncing projects: 100% ( 1/ 1) src/flutter

src/flutter (ERROR)
----------------------------------------
[0:00:00] Started.
----------------------------------------
Traceback (most recent call last):
  File "C:\Users\rabhil\work\dart_tool\metrics.py", line 291, in print_notice_and_exit
    yield
  File "C:\Users\rabhil\work\dart_tool\gclient.py", line 3229, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\Users\rabhil\work\dart_tool\gclient.py", line 3215, in main
    return dispatcher.execute(OptionParser(), argv)
  File "C:\Users\rabhil\work\dart_tool\subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "C:\Users\rabhil\work\dart_tool\gclient.py", line 2769, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "C:\Users\rabhil\work\dart_tool\gclient.py", line 1809, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "C:\Users\rabhil\work\dart_tool\gclient_utils.py", line 967, in flush
    reraise(e[0], e[1], e[2])
  File "C:\Users\rabhil\work\dart_tool\gclient_utils.py", line 1044, in run
    self.item.run(*self.args, **self.kwargs)
  File "C:\Users\rabhil\work\dart_tool\gclient.py", line 945, in run
    file_list)
  File "C:\Users\rabhil\work\dart_tool\gclient_scm.py", line 132, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "C:\Users\rabhil\work\dart_tool\gclient_scm.py", line 511, in update
    mirror = self._GetMirror(url, options, revision, revision_ref)
  File "C:\Users\rabhil\work\dart_tool\gclient_scm.py", line 953, in _GetMirror
    if not self.cache_dir:
  File "C:\Users\rabhil\work\dart_tool\gclient_scm.py", line 218, in cache_dir
    return git_cache.Mirror.GetCachePath()
  File "C:\Users\rabhil\work\dart_tool\git_cache.py", line 190, in GetCachePath
    ['cache.cachepath']).decode('utf-8', 'ignore').strip()
  File "C:\Python27\lib\subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @abhilashraju 

> gclient.bat sync
> The system cannot open the device or file specified.
> 
> C:\Users\rabhil\work\flutter\engine>C:\Users\rabhil\work\dart_tool\gclient.py sync


It would be just `gclient sync`, not sure what commands you're executing here

I have no issue following the docs https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment  for `gclient sync`

Can you please provide what steps you took?
Thank you

**Comment by abhilashraju** [comment]
my configuration is as follows
1)Visual Studio 2019 installed
2)Windows 10 SDK installed
3) extracted the depot_tools and added the path for the same in the path env-variable
3)Fork https://github.com/flutter/engine  - done
4) https://help.github.com/articles/generating-ssh-keys/. (checked - seems to be working fine. I could clone the forked repo ( did it just to make sure git clone works)
5) Create an empty directory called engine
6) Create a .gclient file in the engine and added a .gclient file and inserted the content as mentioned.
7) gclient sync - gave me "The system cannot open the device or file specified"  
8) gclient.bat - gave me the same error
9) gclient.py sync -gave me the above error that I pasted in the logs

**Comment by abhilashraju** [comment]
Hint : there seems to be some kind of protection applied to the files under depote_tools. I had to manually remove the protection by right-clicking files. Did not work at the directory level. 
After that gclient sync seems to be working. Waiting for the result...
