### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by alexandru-basarab** [flutter/flutter#87642]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:56210 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      _StringBase._concatRangeNative (dart:core-patch/string_patch.dart:947:34)
#1      StringBuffer.toString (dart:core-patch/string_buffer_patch.dart:130:23)
#2      _JsonStringStringifier.stringify (dart:convert/json.dart:863:19)
#3      _JsonDocument.bind.<anonymous closure> (package:stream_channel/src/json_document_transformer.dart:32:16)
#4      _HandlerSink.add (package:async/src/stream_sink_transformer/handler_transformer.dart:61:17)
#5      DelegatingStreamSink.add (package:async/src/delegate/stream_sink.dart:35:11)
#6      DelegatingStreamSink.add (package:async/src/delegate/stream_sink.dart:35:11)
#7      Server._handleRequest (package:json_rpc_2/src/server.dart:192:34)
#8      _rootRunUnary (dart:async/zone.dart:1436:47)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:160:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:767:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:796:13)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:264:13)
#13     Server._handleSingleRequest (package:json_rpc_2/src/server.dart)
#14     _rootRunUnary (dart:async/zone.dart:1436:47)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:160:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:767:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:796:13)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:466:9)
#19     _rootRun (dart:async/zone.dart:1428:13)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```
```
[✓] Flutter (Channel dev, 2.4.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
    • Flutter version 2.4.0-4.0.pre at C:\Users\Oahaha\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cc00e7e6bc (3 weeks ago), 2021-07-11 18:21:02 -0400
    • Engine revision ed25e8f01e
    • Dart version 2.14.0 (build 2.14.0-301.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.2.0)
    • Android Studio at D:\programs\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 02c026b03cd31dd3f867e5faeb7e104cce174c5f
### Plugins
connectivity-3.0.6
connectivity_for_web-0.4.0
connectivity_macos-0.2.0
file_picker-3.0.4
firebase_core-1.4.0
firebase_core_web-1.1.0
firebase_messaging-10.0.4
firebase_messaging_web-2.0.3
flutter_plugin_android_lifecycle-2.0.2
geolocator-7.4.0
geolocator_android-1.0.0
geolocator_apple-1.0.0
geolocator_web-2.0.6
path_provider_linux-2.0.2
path_provider_windows-2.0.3
shared_preferences-2.0.6
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.1
shared_preferences_windows-2.0.2

**Comment by darshankawar** [comment]
I don't see a similar / duplicate open issue for same crash. 
Labeling it accordingly.

**Comment by alexandru-basarab** [comment]
i think it's my potato laptop, but if it's a memory leak somewhere maybe someone will fix it.

**Comment by ditman** [comment]
@alexandru-basarab can you share a minimal reproduction of the code that shows the crash?

In the stack trace I see:

```
#3      _JsonDocument.bind.<anonymous closure> (package:stream_channel/src/json_document_transformer.dart:32:16)
```

Are you handling huge JSON files? :)

**Comment by AlexandruBasarab** [comment]
The project is dead so no idea how to reproduce it, and I don't remember how did ended up getting that out of memory. Sorry

**Comment by ditman** [comment]
Sorry we didn't get to this earlier @AlexandruBasarab! I'm going to close this one then.
