### ISSUE TITLE
Test flake: "Received app.stop event while waiting for app.<???> event"

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#87659]
From https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8839853339867337232/+/u/run_test.dart_for_web_tool_tests_shard_and_subshard_web/stdout?format=raw

Seen when run on CI against 8212b58a7f5816a1d6d013cf9c5df9eef9bcc01e

```
  Exception: Received app.stop event while waiting for app.started event
  
  [  +89 ms] FINE: Pub 2.14.0-377.0.dev
  [  +36 ms] SLVR: fact: test is 0.0.0
  [   +7 ms] SLVR: derived: test
  [  +22 ms] SLVR: fact: test depends on flutter any from sdk
  [        ] SLVR: fact: test depends on flutter_test any from sdk
  [   +1 ms] SLVR:   selecting test
  [        ] SLVR:   derived: flutter_test any from sdk
  [        ] SLVR:   derived: flutter any from sdk
  [  +17 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on test_api 0.4.2
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on path 1.8.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on fake_async 1.2.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on clock 1.1.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.10.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on vector_math 2.1.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on async 2.8.1
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on boolean_selector 2.1.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on characters 1.1.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on charcode 1.3.1
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on collection 1.15.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.10
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on meta 1.7.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on source_span 1.8.1
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.1.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.1.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.2.0
  [        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on typed_data 1.3.0
  [        ] SLVR:     selecting flutter_test 0.0.0 from sdk
  [        ] SLVR:     derived: typed_data 1.3.0
  [        ] SLVR:     derived: term_glyph 1.2.0
  [        ] SLVR:     derived: string_scanner 1.1.0
  [        ] SLVR:     derived: stream_channel 2.1.0
  [        ] SLVR:     derived: source_span 1.8.1
  [        ] SLVR:     derived: meta 1.7.0
  [        ] SLVR:     derived: matcher 0.12.10
  [        ] SLVR:     derived: collection 1.15.0
  [        ] SLVR:     derived: charcode 1.3.1
  [        ] SLVR:     derived: characters 1.1.0
  [        ] SLVR:     derived: boolean_selector 2.1.0
  [        ] SLVR:     derived: async 2.8.1
  [        ] SLVR:     derived: vector_math 2.1.0
  [        ] SLVR:     derived: stack_trace 1.10.0
  [        ] SLVR:     derived: clock 1.1.0
  [        ] SLVR:     derived: fake_async 1.2.0
  [        ] SLVR:     derived: path 1.8.0
  [        ] SLVR:     derived: test_api 0.4.2
  [   +7 ms] SLVR:     fact: flutter 0.0.0 from sdk depends on characters 1.1.0
  [        ] SLVR:     fact: flutter 0.0.0 from sdk depends on collection 1.15.0
  [        ] SLVR:     fact: flutter 0.0.0 from sdk depends on meta 1.7.0
  [        ] SLVR:     fact: flutter 0.0.0 from sdk depends on typed_data 1.3.0
  [        ] SLVR:     fact: flutter 0.0.0 from sdk depends on vector_math 2.1.0
  [        ] SLVR:     fact: flutter 0.0.0 from sdk depends on sky_engine any from sdk
  [        ] SLVR:       selecting flutter 0.0.0 from sdk
  [        ] SLVR:       derived: sky_engine any from sdk
  [  +10 ms] SLVR:       fact: typed_data 1.3.0 depends on collection ^1.15.0
  [        ] SLVR:         selecting typed_data 1.3.0
  [   +3 ms] SLVR:           selecting term_glyph 1.2.0
  [   +3 ms] SLVR:           fact: string_scanner 1.1.0 depends on charcode ^1.2.0
  [        ] SLVR:           fact: string_scanner 1.1.0 depends on source_span ^1.8.0
  [        ] SLVR:             selecting string_scanner 1.1.0
  [   +3 ms] SLVR:             fact: stream_channel 2.1.0 depends on async ^2.5.0
  [        ] SLVR:               selecting stream_channel 2.1.0
  [   +3 ms] SLVR:               fact: source_span 1.8.1 depends on collection ^1.15.0
  [        ] SLVR:               fact: source_span 1.8.1 depends on path ^1.8.0
  [        ] SLVR:               fact: source_span 1.8.1 depends on term_glyph ^1.2.0
  [        ] SLVR:                 selecting source_span 1.8.1
  [   +2 ms] SLVR:                   selecting meta 1.7.0
  [   +3 ms] SLVR:                   fact: matcher 0.12.10 depends on stack_trace ^1.10.0
  [        ] SLVR:                     selecting matcher 0.12.10
  [   +3 ms] SLVR:                       selecting collection 1.15.0
  [   +3 ms] SLVR:                         selecting charcode 1.3.1
  [   +3 ms] SLVR:                           selecting characters 1.1.0
  [   +2 ms] SLVR:                           fact: boolean_selector 2.1.0 depends on source_span ^1.8.0
  [        ] SLVR:                           fact: boolean_selector 2.1.0 depends on string_scanner ^1.1.0
  [        ] SLVR:                             selecting boolean_selector 2.1.0
  [   +2 ms] SLVR:                             fact: async 2.8.1 depends on collection ^1.15.0
  [        ] SLVR:                             fact: async 2.8.1 depends on meta ^1.1.7
  [        ] SLVR:                               selecting async 2.8.1
  [   +3 ms] SLVR:                                 selecting vector_math 2.1.0
  [   +2 ms] SLVR:                                 fact: stack_trace 1.10.0 depends on path ^1.8.0
  [        ] SLVR:                                   selecting stack_trace 1.10.0
  [   +2 ms] SLVR:                                     selecting clock 1.1.0
  [   +2 ms] SLVR:                                     fact: fake_async 1.2.0 depends on clock ^1.1.0
  [        ] SLVR:                                     fact: fake_async 1.2.0 depends on collection ^1.15.0
  [        ] SLVR:                                       selecting fake_async 1.2.0
  [   +2 ms] SLVR:                                         selecting path 1.8.0
  [   +3 ms] SLVR:                                         fact: test_api 0.4.2 depends on async ^2.5.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on boolean_selector ^2.1.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on collection ^1.15.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on meta ^1.3.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on source_span ^1.8.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on stack_trace ^1.10.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on stream_channel ^2.1.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on string_scanner ^1.1.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on term_glyph ^1.2.0
  [        ] SLVR:                                         fact: test_api 0.4.2 depends on matcher >=0.12.10 <0.12.11
  [        ] SLVR:                                           selecting test_api 0.4.2
  [   +1 ms] SLVR:                                             selecting sky_engine 0.0.99 from sdk
  [ +133 ms] SLVR: Version solving took 0:00:00.276699 seconds.
  [        ]     | Tried 1 solutions.
  [        ] FINE: Resolving dependencies finished (0.307s).
  [ +137 ms] IO  : Writing 3268 characters to text file ./pubspec.lock.
  [        ] FINE: Contents:
  [        ]     | # Generated by pub
  [        ]     | # See https://dart.dev/tools/pub/glossary#lockfile
  [        ]     | packages:
  [        ]     |   async:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: async
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "2.8.1"
  [        ]     |   boolean_selector:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: boolean_selector
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "2.1.0"
  [        ]     |   characters:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: characters
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.1.0"
  [        ]     |   charcode:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: charcode
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.3.1"
  [        ]     |   clock:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: clock
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.1.0"
  [        ]     |   collection:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: collection
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.15.0"
  [        ]     |   fake_async:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: fake_async
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.2.0"
  [        ]     |   flutter:
  [        ]     |     dependency: "direct main"
  [        ]     |     description: flutter
  [        ]     |     source: sdk
  [        ]     |     version: "0.0.0"
  [        ]     |   flutter_test:
  [        ]     |     dependency: "direct dev"
  [        ]     |     description: flutter
  [        ]     |     source: sdk
  [        ]     |     version: "0.0.0"
  [        ]     |   matcher:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: matcher
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "0.12.10"
  [        ]     |   meta:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: meta
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.7.0"
  [        ]     |   path:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: path
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.8.0"
  [        ]     |   sky_engine:
  [        ]     |     dependency: transitive
  [        ]     |     description: flutter
  [        ]     |     source: sdk
  [        ]     |     version: "0.0.99"
  [        ]     |   source_span:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: source_span
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.8.1"
  [        ]     |   stack_trace:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: stack_trace
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.10.0"
  [        ]     |   stream_channel:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: stream_channel
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "2.1.0"
  [        ]     |   string_scanner:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: string_scanner
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.1.0"
  [        ]     |   term_glyph:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: term_glyph
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.2.0"
  [        ]     |   test_api:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: test_api
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "0.4.2"
  [        ]     |   typed_data:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: typed_data
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "1.3.0"
  [        ]     |   vector_math:
  [        ]     |     dependency: transitive
  [        ]     |     description:
  [        ]     |       name: vector_math
  [        ]     |       url: "https://pub.dartlang.org"
  [        ]     |     source: hosted
  [        ]     |     version: "2.1.0"
  [        ]     | sdks:
  [        ]     |   dart: ">=2.12.0 <3.0.0"
  [        ] IO  : Writing 2005 characters to text file ./.packages.
  [        ] FINE: Contents:
  [        ]     | # This file is deprecated. Tools should instead consume 
  [        ]     | # `.dart_tool/package_config.json`.
  [        ]     | # 
  [        ]     | # For more info see: https://dart.dev/go/dot-packages-deprecation
  [        ]     | # 
  [        ]     | # Generated by pub on 2021-08-04 05:54:29.406489.
  [        ]     | async:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/async-2.8.1/lib/
  [        ]     | boolean_selector:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0/lib/
  [        ]     | characters:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0/lib/
  [        ]     | charcode:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/charcode-1.3.1/lib/
  [        ]     | clock:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/clock-1.1.0/lib/
  [        ]     | collection:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0/lib/
  [        ]     | fake_async:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/fake_async-1.2.0/lib/
  [        ]     | flutter:file:///b/s/w/ir/x/w/flutter/packages/flutter/lib/
  [        ]     | flutter_test:file:///b/s/w/ir/x/w/flutter/packages/flutter_test/lib/
  [        ]     | matcher:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.10/lib/
  [        ]     | meta:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/
  [        ]     | path:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/path-1.8.0/lib/
  [        ]     | sky_engine:file:///b/s/w/ir/x/w/flutter/bin/cache/pkg/sky_engine/lib/
  [        ]     | source_span:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.1/lib/
  [        ]     | stack_trace:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.10.0/lib/
  [        ]     | stream_channel:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.1.0/lib/
  [        ]     | string_scanner:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0/lib/
  [        ]     | term_glyph:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.2.0/lib/
  [        ]     | test_api:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/test_api-0.4.2/lib/
  [        ]     | typed_data:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/typed_data-1.3.0/lib/
  [        ]     | vector_math:file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.0/lib/
  [        ]     | test:lib/
  [   +3 ms] IO  : Writing 4259 characters to text file ./.dart_tool/package_config.json.
  [        ] FINE: Contents:
  [        ]     | {
  [        ]     |   "configVersion": 2,
  [        ]     |   "packages": [
  [        ]     |     {
  [        ]     |       "name": "async",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/async-2.8.1",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "boolean_selector",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "characters",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/characters-1.1.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "charcode",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/charcode-1.3.1",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [   +1 ms]     |     },
  [        ]     |     {
  [        ]     |       "name": "clock",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/clock-1.1.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "collection",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/collection-1.15.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "fake_async",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/fake_async-1.2.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "flutter",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/flutter/packages/flutter",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "flutter_test",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/flutter/packages/flutter_test",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "matcher",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.10",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "meta",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/meta-1.7.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "path",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/path-1.8.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "sky_engine",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/flutter/bin/cache/pkg/sky_engine",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "source_span",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/source_span-1.8.1",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "stack_trace",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.10.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "stream_channel",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/stream_channel-2.1.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "string_scanner",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.1.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "term_glyph",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/term_glyph-1.2.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "test_api",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/test_api-0.4.2",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "typed_data",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/typed_data-1.3.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "vector_math",
  [        ]     |       "rootUri": "file:///b/s/w/ir/x/w/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.0",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     },
  [        ]     |     {
  [        ]     |       "name": "test",
  [        ]     |       "rootUri": "../",
  [        ]     |       "packageUri": "lib/",
  [        ]     |       "languageVersion": "2.12"
  [        ]     |     }
  [        ]     |   ],
  [        ]     |   "generated": "2021-08-04T05:54:29.422386Z",
  [        ]     |   "generator": "pub",
  [        ]     |   "generatorVersion": "2.14.0-377.0.dev"
  [        ]     | }
  [+1767 ms] SocketException: Failed to create server socket (OS Error: Address already in use, errno = 98), address = 127.0.0.1, port = 34971
             #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:962:7)
             <asynchronous suspension>
             #1      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:177:20)
             <asynchronous suspension>
             #2      DebugService.start (package:dwds/src/services/debug_service.dart:257:18)
             <asynchronous suspension>
             #3      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:223:26)
             <asynchronous suspension>
             #4      Dwds.debugConnection (package:dwds/dwds.dart:89:28)
             <asynchronous suspension>
             #5      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:682:15)
             <asynchronous suspension>
  
  Failed to establish connection with the application instance in Chrome.
  This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
  
  #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
  #1      ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:332:7)
  <asynchronous suspension>
  #2      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:595:9)
  <asynchronous suspension>
  #3      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:593:5)
  <asynchronous suspension>
  #4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:552:15)
  <asynchronous suspension>
  #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
  <asynchronous suspension>
  #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
  <asynchronous suspension>
  #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
  <asynchronous suspension>
  #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
  <asynchronous suspension>
  #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
  <asynchronous suspension>
  #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
  <asynchronous suspension>
  #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
  <asynchronous suspension>
  #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
  <asynchronous suspension>
  #13     main (package:flutter_tools/executable.dart:92:3)
  <asynchronous suspension>
  ```

**Comment by tvolkert** [comment]
@aam is this something you could help with?  The error thrown was a `ChromeDebugException ` while in this `try` block:

https://github.com/flutter/flutter/blob/8212b58a7f5816a1d6d013cf9c5df9eef9bcc01e/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L255-L317

**Comment by aam** [comment]
I don't have immediate ideas.
Perhaps @annagrin who is driving debugging and expression evaluation on the web have some thoughts.
Also cc @grouma for the code in dwds debug_service.dart which seems to be causing 'Address already in use' exception.

**Comment by annagrin** [comment]
This looks like a duplicate of https://github.com/flutter/flutter/issues/84012

I am trying the following fix currently in webdev: https://github.com/dart-lang/webdev/pull/1379

**Comment by tvolkert** [comment]
Thanks @annagrin - closing as a dup of #84012
