### ISSUE TITLE
Keyboard input stops working if exception is thrown in `KeyEventManager.handleRawKeyMessage`

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#87688]
Example stack trace:
```
flutter: #0      ListSelectionPopoverHelper.showTaskListsPopover.<anonymous closure>.<anonymous closure> (package:superlist/ui/popovers/popover_helper.dart:396:26)
flutter: #1      _SelectionPopoverState._onEscapePressed (package:superlist/design_system/components/popovers/selection_popover/selection_popover.dart:234:25)
flutter: #2      CallbackAction.invoke (package:flutter/src/widgets/actions.dart:481:49)
flutter: #3      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:520:21)
flutter: #4      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:830:38)
flutter: #5      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:1171:20)
flutter: #6      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1761:32)
flutter: #8      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:830:35)
flutter: #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
flutter: #10     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
flutter: #11     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
flutter: #12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
```

After this happens every key press results in
```
flutter: Another exception was thrown: A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#2e333(physicalKey: PhysicalKeyboardKey#70029(usbHidUsage: "0x00070029", debugName: "Escape"), logicalKey: LogicalKeyboardKey#0001b(keyId: "0x10000001b", keyLabel: "Escape", debugName: "Escape"), character: "imeStamp: 123:10:36.491769)
```

**Comment by TahaTesser** [comment]
Hi @knopp 
Can you please provide a complete reproducible minimal code sample?
Thank you
