### ISSUE TITLE
getIsolate: Invalid argument (isolateId): Unrecognized isolatId

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#87690]
On Flutter dev 2.5.0-1.0.pre
Command:

```
run --machine --target lib\main.dart -d chrome --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/ --web-renderer html
```

```
Thread 0 main thread RPCError:
getIsolate: (-32603) getIsolate: Invalid argument (isolateId): Unrecognized isolate id. (Supported isolate: 7163): "6512"
#0      ChromeProxyService._getIsolate (package:dwds/src/services/chrome_proxy_service.dart:542:5)
#1      ChromeProxyService.getIsolate (package:dwds/src/services/chrome_proxy_service.dart:549:12)<asynchronous suspension>
#2      VmServerConnection._delegateRequest (package:vm_service/src/vm_service.dart:1366:22)<asynchronous suspension>
at new _OutstandingRequest(vm_service.dart:1626)
at VmService._call(vm_service.dart:2109)
at VmService.getIsolate(vm_service.dart:1866)
at FlutterVmService.getIsolateOrNull(vmservice.dart:898)
at FlutterVmService.findExtensionIsolate(vmservice.dart:864)
at <asynchronous gap>(async)
at FlutterResidentDevtoolsHandler._waitForExtensionsForDevice(resident_devtools_handler.dart:171)
at <asynchronous gap>(async)
at Future.wait.<anonymous closure>(future.dart)
at <asynchronous gap>(async)
at FlutterResidentDevtoolsHandler._devicesWithExtensions(resident_devtools_handler.dart:161)
at <asynchronous gap>(async)
at FlutterResidentDevtoolsHandler.hotRestart(resident_devtools_handler.dart:238)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment]
cc @annagrin

**Comment by annagrin** [comment]
@christopherfujino still would need a repro to mark it as "passed triage".

**Comment by christopherfujino** [comment]
> @christopherfujino still would need a repro to mark it as "passed triage".

Do you use the `passed first triage` label as part of your triage process? And if so, would it be possible to use `passed secondary triage` instead?

I believe the way the flutter team uses these labels is that the triage contractors look at all issues that do not have `passed first triage` on it, and add that label once an issue has been accurately routed to a sub-team, and then the sub-teams add `passed secondary triage` once they have taken a look at it. Do I have that correct @mamuseferha ?

**Comment by mamuseferha** [comment]
@christopherfujino Usually we as triagers apply passed first triage labels for the issues that are internal to the flutter team or logged by flutter team members for tracking something internally. 

Another usage of that label is for production crash issues for which there isn't a concrete reproducible use case, adding that label indicates we have gone through the issue and added more labels as applicable and is ready for secondary triage.

**Comment by annagrin** [comment]
Well it can't pass my secondary triage without the repro:) I added a label to indicate that it is currently blocked on that.

**Comment by christopherfujino** [comment]
> Well it can't pass my secondary triage without the repro:) I added a label to indicate that it is currently blocked on that.

Sounds good
