### ISSUE TITLE
RawKeyDownEvent || _keysPressed.isNotEmpty

### ISSUE THREAD

**Issue by menggod** [flutter/flutter#87720]
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#aeae5(logicalKey: LogicalKeyboardKey#700e0(keyId: "0x1000700e0", keyLabel: "Control Left", debugName: "Control Left"), physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left")) and its data: RawKeyEventDataMacOs(keyLabel: , keyCode: 59, characters: , unmodifiedCharacters: , modifiers: 0, modifiers down: {})
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 666 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:666:7)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
#5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
#6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:223:15)

**Comment by TahaTesser** [comment]
Hi @menggod 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you
