### ISSUE TITLE
[WebView_flutter] Disable keyboard in webview

### ISSUE THREAD

**Issue by 94wogus** [flutter/flutter#87806]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:**

**Actual results:** 
When the keyboard comes up from the webview, the webview is automatically refreshed.
![Recording_2021-08-06-22-25-42](https://user-images.githubusercontent.com/40576978/128517765-0c3421de-adef-463d-ae2c-745f57b17cd5.gif)

<details>
  <summary>Logs</summary>

```
[  +21 ms] I/flutter (12255): /webview
[ +342 ms] I/TouchFilterInputStageHelper(12255): [needTouchEventFilter] Displayid : 44
[+2723 ms] I/ViewRootImpl(12255): ViewRoot's Touch Event : ACTION_DOWN
[   +7 ms] I/ViewGroup(12255): ACTION_DOWN: android.widget.LinearLayout{b589c24 V.E...... ........ 0,0-1080,2334}
[        ] I/ViewGroup(12255): ACTION_DOWN: android.widget.FrameLayout{c25a38d V.E...... ........ 0,0-1080,2334 #1020002 android:id/content}
[        ] E/ntit.saiv.rabi(12255): No package ID 24 found for ID 0x245a3c5c.
[        ] I/ViewGroup(12255): ACTION_DOWN: android.widget.FrameLayout{fe9c942 V.E...... ........ 0,0-1080,2334 #245a3c5c}
[        ] I/ViewGroup(12255): ACTION_DOWN: io.flutter.embedding.android.FlutterSplashView{ce8fd53 V.E...... ........ 0,0-1080,2334 #1}
[        ] I/ViewGroup(12255): ACTION_DOWN: io.flutter.embedding.android.FlutterView{d955690 VFE...... .F...... 0,0-1080,2334 aid=1073741824}
[        ] I/ViewGroup(12255): ACTION_DOWN: io.flutter.embedding.android.FlutterSurfaceView{c55eb89 V.E...... ........ 0,0-1080,2334}
[  +45 ms] I/ViewRootImpl(12255): ViewRoot's Touch Event : ACTION_UP
[        ] I/ViewGroup(12255): ACTION_UP: android.widget.LinearLayout{b589c24 V.E...... ........ 0,0-1080,2334}
[        ] I/ViewGroup(12255): ACTION_UP: android.widget.FrameLayout{c25a38d V.E...... ........ 0,0-1080,2334 #1020002 android:id/content}
[        ] E/ntit.saiv.rabi(12255): No package ID 24 found for ID 0x245a3c5c.
[        ] I/ViewGroup(12255): ACTION_UP: android.widget.FrameLayout{fe9c942 V.E...... ........ 0,0-1080,2334 #245a3c5c}
[        ] I/ViewGroup(12255): ACTION_UP: io.flutter.embedding.android.FlutterSplashView{ce8fd53 V.E...... ........ 0,0-1080,2334 #1}
[        ] I/ViewGroup(12255): ACTION_UP: io.flutter.embedding.android.FlutterView{d955690 VFE...... .F...... 0,0-1080,2334 aid=1073741824}
[  +22 ms] I/ViewGroup(12255): ACTION_DOWN: android.widget.LinearLayout{b30e758 V.E...... ........ 0,0-1080,2143}
[        ] I/ViewGroup(12255): ACTION_DOWN: android.widget.FrameLayout{5f80b1 V.E...... ........ 0,0-1080,2143 #1020002 android:id/content}
[        ] I/ViewGroup(12255): ACTION_DOWN: io.flutter.plugin.platform.SingleViewPresentation$AccessibilityDelegatingFrameLayout{bc5e996 VFE...... .F...... 0,0-1080,2143}
[        ] I/ViewGroup(12255): ACTION_DOWN: io.flutter.plugin.platform.SingleViewPresentation$FakeWindowViewGroup{745917 V.E...... ........ 0,0-1080,2143}
[        ] I/ViewGroup(12255): ACTION_DOWN: android.widget.FrameLayout{3792104 V.E...... ........ 0,0-1080,2143}
[        ] I/ViewGroup(12255): ACTION_DOWN: io.flutter.plugins.webviewflutter.InputAwareWebView{fba76ed VFEDHVC.. ........ 0,0-1080,2143}
[  +12 ms] I/ViewGroup(12255): ACTION_UP: android.widget.LinearLayout{b30e758 V.E...... ........ 0,0-1080,2143}
[        ] I/ViewGroup(12255): ACTION_UP: android.widget.FrameLayout{5f80b1 V.E...... ........ 0,0-1080,2143 #1020002 android:id/content}
[   +2 ms] I/ViewGroup(12255): ACTION_UP: io.flutter.plugin.platform.SingleViewPresentation$AccessibilityDelegatingFrameLayout{bc5e996 VFE...... .F...... 0,0-1080,2143}
[        ] I/ViewGroup(12255): ACTION_UP: android.widget.FrameLayout{3792104 V.E...... ........ 0,0-1080,2143}
[        ] I/ViewGroup(12255): ACTION_UP: io.flutter.plugins.webviewflutter.InputAwareWebView{fba76ed VFEDHVC.. ........ 0,0-1080,2143}
[  +31 ms] W/cr_AwAutofillManager(12255): Autofill is disabled: AutofillManager isn't available in given Context.
[   +2 ms] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=44 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{fba76ed VFEDHVC.. .F...... 0,0-1080,2143}
[  +20 ms] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=44 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{fba76ed VFEDHVC.. .F...... 0,0-1080,2143}
[        ] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=44 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{fba76ed VFEDHVC.. .F...... 0,0-1080,2143}
[ +457 ms] I/TouchFilterInputStageHelper(12255): [needTouchEventFilter] Displayid : 45
[  +14 ms] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=44 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{fba76ed VFEDHVC.. .F...... 0,0-1080,2143}
[        ] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=44 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{fba76ed VFEDHVC.. .F...... 0,0-1080,2143}
[ +290 ms] I/TouchFilterInputStageHelper(12255): [needTouchEventFilter] Displayid : 46
[        ] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=45 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{3c8c3e7 VFEDHVC.. ........ 0,0-1080,1809}
[ +245 ms] I/TouchFilterInputStageHelper(12255): [needTouchEventFilter] Displayid : 47
[   +9 ms] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=46 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{b18602e VFEDHVC.. ........ 0,0-1080,1316}
[ +239 ms] I/TouchFilterInputStageHelper(12255): [needTouchEventFilter] Displayid : 48
[   +4 ms] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=47 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{20d1678 VFEDHVC.. ........ 0,0-1080,1201}
[  +23 ms] W/cr_AwContents(12255): Application attempted to call on a destroyed WebView
[        ] W/cr_AwContents(12255): java.lang.Throwable
[        ] W/cr_AwContents(12255):      at org.chromium.android_webview.AwContents.r(chromium-TrichromeWebViewGoogle6432.aab-stable-451513134:2)
[        ] W/cr_AwContents(12255):      at ob.loadingStateChanged(chromium-TrichromeWebViewGoogle6432.aab-stable-451513134:2)
[        ] W/cr_AwContents(12255):      at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] W/cr_AwContents(12255):      at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] W/cr_AwContents(12255):      at android.os.Looper.loop(Looper.java:183)
[        ] W/cr_AwContents(12255):      at android.app.ActivityThread.main(ActivityThread.java:7867)
[        ] W/cr_AwContents(12255):      at java.lang.reflect.Method.invoke(Native Method)
[        ] W/cr_AwContents(12255):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[        ] W/cr_AwContents(12255):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
[ +196 ms] I/TouchFilterInputStageHelper(12255): [needTouchEventFilter] Displayid : 49
[   +4 ms] V/InputMethodManager(12255): b/117267690: Failed to get fallback IMM with expected displayId=48 actual IMM#displayId=0
view=io.flutter.plugins.webviewflutter.InputAwareWebView{7e77cf2 VFEDHVC.. ........ 0,0-1080,1999}
[  +19 ms] W/cr_AwContents(12255): Application attempted to call on a destroyed WebView
[        ] W/cr_AwContents(12255): java.lang.Throwable
[        ] W/cr_AwContents(12255):      at org.chromium.android_webview.AwContents.r(chromium-TrichromeWebViewGoogle6432.aab-stable-451513134:2)
[        ] W/cr_AwContents(12255):      at ob.loadingStateChanged(chromium-TrichromeWebViewGoogle6432.aab-stable-451513134:2)
[        ] W/cr_AwContents(12255):      at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] W/cr_AwContents(12255):      at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] W/cr_AwContents(12255):      at android.os.Looper.loop(Looper.java:183)
[        ] W/cr_AwContents(12255):      at android.app.ActivityThread.main(ActivityThread.java:7867)
[        ] W/cr_AwContents(12255):      at java.lang.reflect.Method.invoke(Native Method)
[        ] W/cr_AwContents(12255):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[        ] W/cr_AwContents(12255):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

```
Analyzing rabit...                                                      
No issues found! (ran in 2.6s)
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-arm, locale ko-KR)
    • Flutter version 2.2.3 at /Users/wogus/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wogus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.11+9-LTS-194)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • LM G900N (mobile) • LMG900Nc1eda018 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 92.0.4515.131
```

</details>

**Comment by 94wogus** [comment]
```
W/cr_AwAutofillManager(26327): Autofill is disabled: AutofillManager isn't available in given Context.
V/InputMethodManager(26327): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{d5a67ee VFEDHVCL. .F...... 0,0-1080,2143}
V/InputMethodManager(26327): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{d5a67ee VFEDHVCL. .F...... 0,0-1080,2143}
V/InputMethodManager(26327): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{d5a67ee VFEDHVCL. .F...... 0,0-1080,2143}
I/TouchFilterInputStageHelper(26327): [needTouchEventFilter] Displayid : 14
V/InputMethodManager(26327): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{d5a67ee VFEDHVCL. .F...... 0,0-1080,2143}
V/InputMethodManager(26327): b/117267690: Failed to get fallback IMM with expected displayId=13 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{d5a67ee VFEDHVCL. .F...... 0,0-1080,2143}
E/BufferQueueProducer(26327): [SurfaceTexture-0-26327-3](id:66d700000003,api:1,p:1105,c:26327) dequeueBuffer: BufferQueue has been abandoned
D/AAudio  (26327): AAudioStream_requestStop(s#2) called
D/AAudioStream(26327): setState(s#2) from 4 to 9
V/AudioTrack(26327): stop(28): prior state:STATE_ACTIVE
D/ntit.saiv.rabi(26327): PlayerBase::stop() from IPlayer
D/AAudioStream(26327): setState(s#2) from 9 to 10
I/TouchFilterInputStageHelper(26327): [needTouchEventFilter] Displayid : 15
V/InputMethodManager(26327): b/117267690: Failed to get fallback IMM with expected displayId=14 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{b7d5fac VFEDHVCL. ........ 0,0-1080,2035}
I/TouchFilterInputStageHelper(26327): [needTouchEventFilter] Displayid : 16
V/InputMethodManager(26327): b/117267690: Failed to get fallback IMM with expected displayId=15 actual IMM#displayId=0 view=com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebView{8dfa74 VFEDHVCL. ........ 0,0-1080,1316}
```

**Comment by 94wogus** [comment]
UniqueKey Issue
