### ISSUE TITLE
Error: The return type of the method 'HomeScreen.createState' is '_HomeScreenState', which does not match the return type, 'State<StatefulWidget>', of the overridden method, 'StatefulWidget.createState'.

### ISSUE THREAD

**Issue by SavanRajyaguru** [flutter/flutter#87805]
I am creating Covid-19 tracker app. Where i am useing this [https://api.covid19india.org/state_district_wise.json](url) api. whenever i import this api data modal class into the HomeScreen widget i got an Error.

> ### pubspec.yaml

```
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  http: ^0.12.2
```

> ### ApiData Modal File
```
import 'dart:convert';
import 'package:http/http.dart';


Future<Api> getUserData() async{
  Api api = new Api();
  final url = "https://api.covid19india.org/state_district_wise.json";
  Response response = await get(Uri.decodeFull(url));
  print(url);
  if(response.statusCode == 200){
    // print("Data: ${response.body}");
    print(api.state);
    return Api.fromJson(json.decode(response.body));
  }else{
    throw Exception("Error: UserData class");
  }
}

class City{
  final int confirmed, deceased, recovered;

  City({this.confirmed, this.deceased, this.recovered});

  factory City.fromJson(Map<String, dynamic> json){
    return City(
      confirmed: json['confirmed'],
      deceased: json['deceased'],
      recovered: json['recovered']
    );
  }
}

class DistrictData{
  final City city;

  DistrictData({this.city});

  factory DistrictData.fromJson(Map<String, dynamic> json){
    return DistrictData(
      city: City.fromJson(
        json['Ahmedabad']
      ),
    );
  }
}

class State{
  final DistrictData districtData;

  State({this.districtData});

  factory State.fromJson(Map<String, dynamic> json){
    return State(
      districtData: json['districtData']
    );
  }
}

class Api{
  final State state;

  Api({this.state});

  factory Api.fromJson(Map<String, dynamic> json){
    return Api(
      state: json['Gujarat']
    );
  }
}
```

> ### HomeScreen File
```
import 'package:covid19_app/Widget/ApiData.dart';
import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  Future<Api> data;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    data = getUserData();
    // print(data);
  }
  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return FutureBuilder(
      future: data,
      builder: (context, AsyncSnapshot snepshot){
        var snepshots = snepshot.data;
        if(snepshot.hasData){
          return Scaffold(
            appBar: AppBar(
              title: Text("Covid-19 Tracker"),
              centerTitle: true,
            ),
            body: Center(
              child: Flexible(
                child: Container(
                  child: Text("Hii"),
                ),
              ),
            ),
          );
        }
        else if(snepshot.hasError){
          return Container(
            width: double.infinity,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Icon(Icons.error_outline,color: Colors.red,size: 60,),
                Text("\nRestart Your App!",style: TextStyle(
                    fontSize: 24,
                    color: Colors.red,
                    decoration: TextDecoration.none
                ),)
              ],
            ),
          );
        }
        return Center(child: CircularProgressIndicator());
      },
    );
  }
}
```

> ### Error Massage
```
lib/Screen/HomeScreen.dart:11:32: Error: Expected 0 type arguments.
class _HomeScreenState extends State<HomeScreen> {
                               ^
lib/Screen/HomeScreen.dart:8:20: Error: The return type of the method 'HomeScreen.createState' is '_HomeScreenState', which does not match the return type, 'State<StatefulWidget>', of the overridden method, 'StatefulWidget.createState'.
 - '_HomeScreenState' is from 'package:covid19_app/Screen/HomeScreen.dart' ('lib/Screen/HomeScreen.dart').
 - 'State' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Change to a subtype of 'State<StatefulWidget>'.
  _HomeScreenState createState() => _HomeScreenState();
                   ^
/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart:758:9: Context: This is the overridden method ('createState').
  State createState(); // ignore: no_logic_in_create_state, this is the original sin
        ^
lib/Screen/HomeScreen.dart:17:11: Error: Superclass has no method named 'initState'.
    super.initState();
          ^^^^^^^^^
lib/Screen/HomeScreen.dart:18:12: Error: The method 'getApiData' isn't defined for the class '_HomeScreenState'.
 - '_HomeScreenState' is from 'package:covid19_app/Screen/HomeScreen.dart' ('lib/Screen/HomeScreen.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getApiData'.
    data = getApiData();
           ^^^^^^^^^^
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      ProgramCompiler._emitSuperTarget (package:dev_compiler/src/kernel/compiler.dart:5293:41)
#2      ProgramCompiler.visitSuperMethodInvocation (package:dev_compiler/src/kernel/compiler.dart:5286:24)
#3      SuperMethodInvocation.accept (package:kernel/ast.dart:6209:44)
#4      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3790:20)
#5      ProgramCompiler.visitExpressionStatement (package:dev_compiler/src/kernel/compiler.dart:3871:12)
#6      ExpressionStatement.accept (package:kernel/ast.dart:8765:43)
#7      ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3696:20)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#10     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#11     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#12     new List.of (dart:core-patch/array_patch.dart:50:28)
#13     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#14     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:3884:62)
#15     Block.accept (package:kernel/ast.dart:8821:43)
#16     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3696:20)
#17     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:3729:18)
#18     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:3500:17)
#19     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2300:25)
#20     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:3534:18)
#21     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:3496:17)
#22     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:3313:11)
#23     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:1907:12)
#24     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:1848:23)
#25     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:692:21)
#26     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:614:21)
#27     List.forEach (dart:core-patch/growable_array.dart:403:8)
#28     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:563:23)
#29     List.forEach (dart:core-patch/growable_array.dart:403:8)
#30     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:423:15)
#31     JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:152:33)
<asynchronous suspension>
#32     FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:649:32)
<asynchronous suspension>
#33     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:557:9)
<asynchronous suspension>
#34     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1132:11)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.
```

**Comment by maheshmnj** [comment]
Hi @SavanRajyaguru

>'_HomeScreenState' is from 'package:covid19_app/Screen/HomeScreen.dart' ('lib/Screen/HomeScreen.dart').
'State' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').

From the error I can understand that, your class name are causing ambiguity with imports as a result the framework is not able to decide between the two classes. This is because State class is defined by you in `ApiData.dart` and also present in `framework.dart`, You can deal with this by either changing the name of your `State` class in ApiData.dart or use named imports in homescreen  using `as`

```
import 'package:covid19_app/Widget/ApiData.dart' as api;  
```

docs: https://dart.dev/guides/language/effective-dart/style
stackoveflow: https://stackoverflow.com/a/19723473/8253662

 In the future, please don't file such issues seeking assistance on personal code. Closing, as this isn't an issue with the Flutter framework but with your code. If you disagree, write in the comments and I will reopen it.
 
Thank you
